include::./index.adoc[]

[[v58-6-0]]
=== Hebreus, 6
// naa ?, NAA - Nova Almeida Atualizada

[[v58-6-1]]

^<<v58-6-1,1>>^ Por isso, deixando os princípios elementares da doutrina de Cristo, avancemos para o que é perfeito, não lançando de novo a base do arrependimento de obras mortas e da fé em Deus,

[[v58-6-2]]

^<<v58-6-2,2>>^ o ensino de batismos e da imposição de mãos, da ressurreição dos mortos e do juízo eterno.

[[v58-6-3]]

^<<v58-6-3,3>>^ Isso faremos, se Deus o permitir.

[[v58-6-4]]

^<<v58-6-4,4>>^ É impossível, pois, que aqueles que uma vez foram iluminados, provaram o dom celestial, se tornaram participantes do Espírito Santo,

[[v58-6-5]]

^<<v58-6-5,5>>^ provaram a boa palavra de Deus e os poderes do mundo vindouro

[[v58-6-6]]

^<<v58-6-6,6>>^ e caíram, sim, é impossível outra vez renová-los para arrependimento, visto que, de novo, estão crucificando para si mesmos o Filho de Deus e expondo-o à zombaria.

[[v58-6-7]]

^<<v58-6-7,7>>^ Porque a terra que absorve a chuva que frequentemente cai sobre ela e produz plantas úteis para aqueles que a cultivam recebe bênção da parte de Deus;

[[v58-6-8]]

^<<v58-6-8,8>>^ mas, se produz espinhos e ervas daninhas, é rejeitada e está perto da maldição; e o seu fim é ser queimada.

[[v58-6-9]]

^<<v58-6-9,9>>^ Quanto a vocês, meus amados, ainda que falemos desta maneira, estamos certos de que coisas melhores os esperam, coisas relacionadas com a salvação.

[[v58-6-10]]

^<<v58-6-10,10>>^ Porque Deus não é injusto para se esquecer do trabalho que vocês fizeram e do amor que mostraram para com o seu nome, pois vocês serviram e ainda estão servindo aos santos.

[[v58-6-11]]

^<<v58-6-11,11>>^ Desejamos que cada um de vocês continue mostrando, até o fim, o mesmo empenho para a plena certeza da esperança,

[[v58-6-12]]

^<<v58-6-12,12>>^ para que não se tornem preguiçosos, mas imitadores daqueles que, pela fé e pela paciência, herdam as promessas.

[[v58-6-13]]

^<<v58-6-13,13>>^ Pois, quando Deus fez a promessa a Abraão, visto que não tinha ninguém superior por quem jurar, jurou por si mesmo,

[[v58-6-14]]

^<<v58-6-14,14>>^ dizendo: "Certamente eu o abençoarei e multiplicarei os seus descendentes."

[[v58-6-15]]

^<<v58-6-15,15>>^ E assim, depois de esperar com paciência, Abraão obteve a promessa.

[[v58-6-16]]

^<<v58-6-16,16>>^ Porque as pessoas juram pelo que lhes é superior, e o juramento, servindo de garantia, põe fim a toda discussão.

[[v58-6-17]]

^<<v58-6-17,17>>^ Por isso, Deus, quando quis mostrar com mais clareza aos herdeiros da promessa que o seu propósito era imutável, confirmou-o com um juramento.

[[v58-6-18]]

^<<v58-6-18,18>>^ Ele fez isso para que, mediante duas coisas imutáveis, nas quais é impossível que Deus minta, nós, que já corremos para o refúgio, tenhamos forte alento, para tomar posse da esperança que nos foi proposta.

[[v58-6-19]]

^<<v58-6-19,19>>^ Temos esta esperança por âncora da alma, segura e firme e que entra no santuário que fica atrás do véu,

[[v58-6-20]]

^<<v58-6-20,20>>^ onde Jesus, como precursor, entrou por nós, tendo-se tornado sumo sacerdote para sempre, segundo a ordem de Melquisedeque.

'''

xref:058-hebreus/058-hebreus-005.adoc#v58-5-0[&#60; Capítulo Anterior] | <<v58-6-0,Topo>> | xref:058-hebreus/058-hebreus-007.adoc#v58-7-0[Próximo Capítulo &#62;]