include::./index.adoc[]

[[v58-4-0]]
=== Hebreus, 4
// naa ?, NAA - Nova Almeida Atualizada

[[v58-4-1]]

^<<v58-4-1,1>>^ Portanto, visto que nos foi deixada a promessa de entrar no descanso de Deus, tenhamos cuidado para não parecer que algum de vocês deixou de alcançá-la.

[[v58-4-2]]

^<<v58-4-2,2>>^ Porque também a nós foram anunciadas as boas-novas, exatamente como aconteceu com eles. Mas a palavra que eles ouviram não lhes trouxe proveito, porque não foram unidos por meio da fé com aqueles que a ouviram.

[[v58-4-3]]

^<<v58-4-3,3>>^ Nós, porém, que cremos, entramos no descanso, conforme Deus disse: "Assim, jurei na minha ira: ‘Não entrarão no meu descanso.’" Ele disse isso, mesmo que as obras já estivessem concluídas desde a fundação do mundo.

[[v58-4-4]]

^<<v58-4-4,4>>^ Porque, em certo lugar, assim disse a respeito do sétimo dia: "No sétimo dia, Deus descansou de todas as obras que tinha feito."

[[v58-4-5]]

^<<v58-4-5,5>>^ E, novamente, no mesmo lugar: "Não entrarão no meu descanso."

[[v58-4-6]]

^<<v58-4-6,6>>^ Visto, portanto, que resta entrarem alguns naquele descanso e que, por causa da desobediência, não entraram aqueles aos quais anteriormente foram anunciadas as boas-novas,

[[v58-4-7]]

^<<v58-4-7,7>>^ de novo, determina certo dia, "hoje", falando por Davi, muito tempo depois, segundo antes tinha sido declarado: "Hoje, se ouvirem a sua voz, não endureçam o coração."

[[v58-4-8]]

^<<v58-4-8,8>>^ Ora, se Josué lhes tivesse dado descanso, não falaria, posteriormente, a respeito de outro dia.

[[v58-4-9]]

^<<v58-4-9,9>>^ Portanto, resta um repouso sabático para o povo de Deus.

[[v58-4-10]]

^<<v58-4-10,10>>^ Porque aquele que entrou no descanso de Deus, também ele mesmo descansou de suas obras, como Deus descansou das suas.

[[v58-4-11]]

^<<v58-4-11,11>>^ Portanto, esforcemo-nos por entrar naquele descanso, a fim de que ninguém caia, segundo aquele exemplo de desobediência.

[[v58-4-12]]

^<<v58-4-12,12>>^ Porque a palavra de Deus é viva e eficaz, e mais cortante do que qualquer espada de dois gumes, e penetra até o ponto de dividir alma e espírito, juntas e medulas, e é apta para julgar os pensamentos e propósitos do coração.

[[v58-4-13]]

^<<v58-4-13,13>>^ E não há criatura que não seja manifesta na sua presença; pelo contrário, todas as coisas estão descobertas e expostas aos olhos daquele a quem temos de prestar contas.

[[v58-4-14]]

^<<v58-4-14,14>>^ Tendo, pois, Jesus, o Filho de Deus, como grande sumo sacerdote que adentrou os céus, conservemos firmes a nossa confissão.

[[v58-4-15]]

^<<v58-4-15,15>>^ Porque não temos sumo sacerdote que não possa se compadecer das nossas fraquezas; pelo contrário, ele foi tentado em todas as coisas, à nossa semelhança, mas sem pecado.

[[v58-4-16]]

^<<v58-4-16,16>>^ Portanto, aproximemo-nos do trono da graça com confiança, a fim de recebermos misericórdia e encontrarmos graça para ajuda em momento oportuno.

'''

xref:058-hebreus/058-hebreus-003.adoc#v58-3-0[&#60; Capítulo Anterior] | <<v58-4-0,Topo>> | xref:058-hebreus/058-hebreus-005.adoc#v58-5-0[Próximo Capítulo &#62;]