include::./index.adoc[]

[[v58-12-0]]
=== Hebreus, 12
// naa ?, NAA - Nova Almeida Atualizada

[[v58-12-1]]

^<<v58-12-1,1>>^ Portanto, também nós, visto que temos a rodear-nos tão grande nuvem de testemunhas, livremo-nos de todo peso e do pecado que tão firmemente se apega a nós e corramos com perseverança a carreira que nos está proposta,

[[v58-12-2]]

^<<v58-12-2,2>>^ olhando firmemente para o Autor e Consumador da fé, Jesus, o qual, em troca da alegria que lhe estava proposta, suportou a cruz, sem se importar com a vergonha, e agora está sentado à direita do trono de Deus.

[[v58-12-3]]

^<<v58-12-3,3>>^ Portanto, pensem naquele que suportou tamanha oposição dos pecadores contra si mesmo, para que vocês não se cansem nem desanimem.

[[v58-12-4]]

^<<v58-12-4,4>>^ Na luta contra o pecado, vocês ainda não resistiram até o sangue.

[[v58-12-5]]

^<<v58-12-5,5>>^ E vocês se esqueceram da exortação que lhes é dirigida, como a filhos: "Filho meu, não despreze a correção que vem do Senhor, nem desanime quando você é repreendido por ele;

[[v58-12-6]]

^<<v58-12-6,6>>^ porque o Senhor corrige a quem ama e castiga todo filho a quem aceita."

[[v58-12-7]]

^<<v58-12-7,7>>^ É para disciplina que vocês perseveram. Deus os trata como filhos. E qual é o filho a quem o pai não corrige?

[[v58-12-8]]

^<<v58-12-8,8>>^ Mas, se estão sem essa correção, da qual todos se tornaram participantes, então vocês são bastardos e não filhos.

[[v58-12-9]]

^<<v58-12-9,9>>^ Além disso, tínhamos os nossos pais humanos, que nos corrigiam, e nós os respeitávamos. Será que, então, não nos sujeitaremos muito mais ao Pai espiritual, para vivermos?

[[v58-12-10]]

^<<v58-12-10,10>>^ Pois eles nos corrigiam por pouco tempo, segundo melhor lhes parecia; Deus, porém, nos disciplina para o nosso próprio bem, a fim de sermos participantes da sua santidade.

[[v58-12-11]]

^<<v58-12-11,11>>^ Na verdade, toda disciplina, ao ser aplicada, não parece ser motivo de alegria, mas de tristeza. Porém, mais tarde, produz fruto pacífico aos que têm sido por ela exercitados, fruto de justiça.

[[v58-12-12]]

^<<v58-12-12,12>>^ Por isso, levantem as mãos cansadas e fortaleçam os joelhos vacilantes.

[[v58-12-13]]

^<<v58-12-13,13>>^ Façam caminhos retos para os seus pés, para que o manco não se desvie, mas seja curado.

[[v58-12-14]]

^<<v58-12-14,14>>^ Procurem viver em paz com todos e busquem a santificação, sem a qual ninguém verá o Senhor.

[[v58-12-15]]

^<<v58-12-15,15>>^ Cuidem para que ninguém fique afastado da graça de Deus, e que nenhuma raiz de amargura, brotando, cause perturbação, e, por meio dela, muitos sejam contaminados.

[[v58-12-16]]

^<<v58-12-16,16>>^ E cuidem para que não haja nenhum impuro ou profano, como foi Esaú, o qual, por um prato de comida, vendeu o seu direito de primogenitura.

[[v58-12-17]]

^<<v58-12-17,17>>^ Vocês sabem também que, posteriormente, querendo herdar a bênção, foi rejeitado, pois não achou lugar de arrependimento, embora, com lágrimas, o tivesse buscado.

[[v58-12-18]]

^<<v58-12-18,18>>^ Ora, vocês não chegaram ao fogo palpável e aceso, à escuridão, às trevas, à tempestade,

[[v58-12-19]]

^<<v58-12-19,19>>^ ao toque da trombeta e ao som de palavras tais, que aqueles que ouviram isso pediram que não lhes fosse dito mais nada,

[[v58-12-20]]

^<<v58-12-20,20>>^ pois já não suportavam o que lhes era ordenado: "Até um animal, se tocar o monte, será apedrejado."

[[v58-12-21]]

^<<v58-12-21,21>>^ Na verdade, o espetáculo era tão horrível, que Moisés disse: "Estou apavorado e trêmulo!"

[[v58-12-22]]

^<<v58-12-22,22>>^ Pelo contrário, vocês chegaram ao monte Sião e à cidade do Deus vivo, a Jerusalém celestial, e a milhares de anjos. Vocês chegaram à assembleia festiva,

[[v58-12-23]]

^<<v58-12-23,23>>^ a igreja dos primogênitos arrolados nos céus. Vocês chegaram a Deus, o Juiz de todos, e aos espíritos dos justos aperfeiçoados,

[[v58-12-24]]

^<<v58-12-24,24>>^ e a Jesus, o Mediador da nova aliança, e ao sangue da aspersão, que fala melhor do que o sangue de Abel.

[[v58-12-25]]

^<<v58-12-25,25>>^ Tenham cuidado e não se recusem a ouvir aquele que fala. Pois, se os que se recusaram a ouvir quem divinamente os advertia na terra não escaparam, muito menos escaparemos nós, se nos desviarmos daquele que dos céus nos adverte.

[[v58-12-26]]

^<<v58-12-26,26>>^ Naquele tempo, a voz dele abalou a terra, mas agora ele promete, dizendo: "Mais uma vez eu farei tremer não só a terra, mas também o céu."

[[v58-12-27]]

^<<v58-12-27,27>>^ Ora, as palavras "mais uma vez" significam a remoção dessas coisas abaladas, ou seja, das coisas criadas, para que permaneçam as coisas que não podem ser abaladas.

[[v58-12-28]]

^<<v58-12-28,28>>^ Por isso, recebendo nós um Reino inabalável, retenhamos a graça, pela qual sirvamos a Deus de modo agradável, com reverência e temor.

[[v58-12-29]]

^<<v58-12-29,29>>^ Porque o nosso Deus é fogo consumidor.

'''

xref:058-hebreus/058-hebreus-011.adoc#v58-11-0[&#60; Capítulo Anterior] | <<v58-12-0,Topo>> | xref:058-hebreus/058-hebreus-013.adoc#v58-13-0[Próximo Capítulo &#62;]