include::./index.adoc[]

[[v58-9-0]]
=== Hebreus, 9
// naa ?, NAA - Nova Almeida Atualizada

[[v58-9-1]]

^<<v58-9-1,1>>^ Ora, a primeira aliança também tinha preceitos de culto divino e o seu santuário terrestre.

[[v58-9-2]]

^<<v58-9-2,2>>^ Porque foi edificado um tabernáculo, cuja parte da frente, onde estavam o candelabro, a mesa e os pães da proposição, se chama o Santo Lugar.

[[v58-9-3]]

^<<v58-9-3,3>>^ Por trás do segundo véu se encontrava o tabernáculo que se chama o Santo dos Santos,

[[v58-9-4]]

^<<v58-9-4,4>>^ ao qual pertencia um altar de ouro para o incenso e a arca da aliança totalmente coberta de ouro, na qual estava uma urna de ouro contendo o maná, o bordão de Arão, que floresceu, e as tábuas da aliança.

[[v58-9-5]]

^<<v58-9-5,5>>^ Sobre a arca estavam os querubins de glória, que, com a sua sombra, cobriam o propiciatório. Mas dessas coisas não falaremos, agora, com mais detalhes.

[[v58-9-6]]

^<<v58-9-6,6>>^ Ora, depois que foram feitos todos esses preparativos, os sacerdotes entram continuamente no primeiro tabernáculo para realizar os serviços sagrados.

[[v58-9-7]]

^<<v58-9-7,7>>^ Mas, no segundo, o sumo sacerdote entra sozinho uma vez por ano, não sem sangue, que oferece por si e pelos pecados de ignorância do povo.

[[v58-9-8]]

^<<v58-9-8,8>>^ Com isto o Espírito Santo quer dar a entender que o caminho do Santuário ainda não se manifestou, enquanto o primeiro tabernáculo continua erguido.

[[v58-9-9]]

^<<v58-9-9,9>>^ Isso é uma parábola para a época presente, na qual se oferecem dons e sacrifícios, embora estes, no que diz respeito à consciência, sejam ineficazes para aperfeiçoar aquele que presta culto,

[[v58-9-10]]

^<<v58-9-10,10>>^ pois não passam de ordenanças da carne, baseadas somente em comidas, bebidas e diversas cerimônias de purificação, impostas até o tempo oportuno de reforma.

[[v58-9-11]]

^<<v58-9-11,11>>^ Quando, porém, Cristo veio como sumo sacerdote dos bens já realizados, mediante o maior e mais perfeito tabernáculo, não feito por mãos humanas, quer dizer, não desta criação,

[[v58-9-12]]

^<<v58-9-12,12>>^ e não pelo sangue de bodes e de bezerros, mas pelo seu próprio sangue, ele entrou no Santuário, uma vez por todas, e obteve uma eterna redenção.

[[v58-9-13]]

^<<v58-9-13,13>>^ Portanto, se o sangue de bodes e de touros e a cinza de uma novilha, aspergidos sobre os contaminados, os santificam quanto à purificação da carne,

[[v58-9-14]]

^<<v58-9-14,14>>^ muito mais o sangue de Cristo, que, pelo Espírito eterno, a si mesmo ofereceu sem mácula a Deus, purificará a nossa consciência de obras mortas, para servirmos ao Deus vivo!

[[v58-9-15]]

^<<v58-9-15,15>>^ Por isso mesmo, ele é o Mediador da nova aliança, a fim de que os que foram chamados recebam a promessa da herança eterna, visto que houve uma morte para remissão das transgressões que foram cometidas sob a primeira aliança.

[[v58-9-16]]

^<<v58-9-16,16>>^ Porque, onde há um testamento, é necessário constatar a morte de quem o fez.

[[v58-9-17]]

^<<v58-9-17,17>>^ Sim, porque um testamento só é confirmado depois da morte de quem o fez, pois de maneira nenhuma um testamento tem força de lei enquanto ainda vive quem o fez.

[[v58-9-18]]

^<<v58-9-18,18>>^ Por isso, nem a primeira aliança foi estabelecida sem sangue.

[[v58-9-19]]

^<<v58-9-19,19>>^ Porque, havendo Moisés proclamado a todo o povo todos os mandamentos conforme a lei, pegou o sangue dos bezerros e dos bodes, com água, lã tingida de escarlate e hissopo e aspergiu não só o próprio livro, como também todo o povo,

[[v58-9-20]]

^<<v58-9-20,20>>^ dizendo: "Este é o sangue da aliança que Deus ordenou para vocês."

[[v58-9-21]]

^<<v58-9-21,21>>^ Igualmente também aspergiu com sangue o tabernáculo e todos os utensílios do serviço sagrado.

[[v58-9-22]]

^<<v58-9-22,22>>^ De fato, segundo a lei, quase todas as coisas são purificadas com sangue; e sem derramamento de sangue não há remissão.

[[v58-9-23]]

^<<v58-9-23,23>>^ Era necessário, portanto, que as figuras das coisas que estão nos céus fossem purificadas com tais sacrifícios, mas as próprias coisas celestiais requerem sacrifícios superiores àqueles.

[[v58-9-24]]

^<<v58-9-24,24>>^ Porque Cristo não entrou em santuário feito por mãos humanas, figura do verdadeiro Santuário, porém no próprio céu, para comparecer, agora, por nós, diante de Deus.

[[v58-9-25]]

^<<v58-9-25,25>>^ Ele não entrou para oferecer a si mesmo muitas vezes, como o sumo sacerdote entra todos os anos no Santo dos Santos com sangue alheio.

[[v58-9-26]]

^<<v58-9-26,26>>^ Se fosse assim, ele precisaria ter sofrido muitas vezes desde a fundação do mundo; agora, porém, ao chegar o fim dos tempos, ele se manifestou uma vez por todas, para aniquilar o pecado por meio do sacrifício de si mesmo.

[[v58-9-27]]

^<<v58-9-27,27>>^ E, assim como aos homens está ordenado morrerem uma só vez, vindo, depois disso, o juízo,

[[v58-9-28]]

^<<v58-9-28,28>>^ assim também Cristo, tendo-se oferecido uma vez por todas para tirar os pecados de muitos, aparecerá segunda vez, não para tirar pecados, mas para salvar aqueles que esperam por ele.

'''

xref:058-hebreus/058-hebreus-008.adoc#v58-8-0[&#60; Capítulo Anterior] | <<v58-9-0,Topo>> | xref:058-hebreus/058-hebreus-010.adoc#v58-10-0[Próximo Capítulo &#62;]