include::./index.adoc[]

[[v58-3-0]]
=== Hebreus, 3
// naa ?, NAA - Nova Almeida Atualizada

[[v58-3-1]]

^<<v58-3-1,1>>^ Por isso, santos irmãos, vocês que são participantes da vocação celestial, considerem atentamente o Apóstolo e Sumo Sacerdote da nossa confissão, Jesus,

[[v58-3-2]]

^<<v58-3-2,2>>^ o qual é fiel àquele que o constituiu, como também Moisés foi fiel em toda a casa de Deus.

[[v58-3-3]]

^<<v58-3-3,3>>^ No entanto, assim como aquele que edifica uma casa tem maior honra do que a casa em si, também Jesus tem sido considerado digno de maior glória do que Moisés.

[[v58-3-4]]

^<<v58-3-4,4>>^ Pois toda casa é edificada por alguém, mas aquele que edificou todas as coisas é Deus.

[[v58-3-5]]

^<<v58-3-5,5>>^ E Moisés foi fiel, em toda a casa de Deus, como servo, para testemunho das coisas que haviam de ser anunciadas.

[[v58-3-6]]

^<<v58-3-6,6>>^ Cristo, porém, como Filho, é fiel em sua casa. Esta casa somos nós, se guardarmos firme a ousadia e a exultação da esperança.

[[v58-3-7]]

^<<v58-3-7,7>>^ Por isso, como diz o Espírito Santo: "Hoje, se ouvirem a sua voz,

[[v58-3-8]]

^<<v58-3-8,8>>^ não endureçam o coração como foi na rebelião, no dia da tentação no deserto,

[[v58-3-9]]

^<<v58-3-9,9>>^ onde os pais de vocês me tentaram, pondo-me à prova, e viram as minhas obras durante quarenta anos.

[[v58-3-10]]

^<<v58-3-10,10>>^ Por isso, me indignei contra essa geração e disse: ‘O coração deles sempre se afasta de mim; e eles não conheceram os meus caminhos.’

[[v58-3-11]]

^<<v58-3-11,11>>^ Assim, jurei na minha ira: ‘Não entrarão no meu descanso.’"

[[v58-3-12]]

^<<v58-3-12,12>>^ Tenham cuidado, irmãos, para que nenhum de vocês tenha um coração mau e descrente, que se afaste do Deus vivo.

[[v58-3-13]]

^<<v58-3-13,13>>^ Pelo contrário, animem uns aos outros todos os dias, durante o tempo que se chama "hoje", a fim de que nenhum de vocês seja endurecido pelo engano do pecado.

[[v58-3-14]]

^<<v58-3-14,14>>^ Porque temos nos tornado participantes de Cristo, se, de fato, guardarmos firme, até o fim, a confiança que, desde o princípio, tivemos.

[[v58-3-15]]

^<<v58-3-15,15>>^ Como se diz: "Hoje, se ouvirem a sua voz, não endureçam o coração, como foi na rebelião."

[[v58-3-16]]

^<<v58-3-16,16>>^ E quem foram os que ouviram e, mesmo assim, se rebelaram? Não foram todos os que saíram do Egito por meio de Moisés?

[[v58-3-17]]

^<<v58-3-17,17>>^ E contra quem Deus se indignou durante quarenta anos? Não foi contra os que pecaram, cujos cadáveres caíram no deserto?

[[v58-3-18]]

^<<v58-3-18,18>>^ E a quem jurou que não entrariam no seu descanso, senão aos que foram desobedientes?

[[v58-3-19]]

^<<v58-3-19,19>>^ Assim, vemos que não puderam entrar por causa da incredulidade.

'''

xref:058-hebreus/058-hebreus-002.adoc#v58-2-0[&#60; Capítulo Anterior] | <<v58-3-0,Topo>> | xref:058-hebreus/058-hebreus-004.adoc#v58-4-0[Próximo Capítulo &#62;]