include::./index.adoc[]

[[v58-7-0]]
=== Hebreus, 7
// naa ?, NAA - Nova Almeida Atualizada

[[v58-7-1]]

^<<v58-7-1,1>>^ Porque este Melquisedeque, rei de Salém, sacerdote do Deus Altíssimo, foi ao encontro de Abraão, quando este voltava da matança dos reis, e o abençoou.

[[v58-7-2]]

^<<v58-7-2,2>>^ Foi para ele que Abraão separou o dízimo de tudo. Primeiramente o nome dele significa "rei da justiça"; depois também é "rei de Salém", ou seja, "rei da paz".

[[v58-7-3]]

^<<v58-7-3,3>>^ Sem pai, sem mãe, sem genealogia, ele não teve princípio de dias nem fim de existência, mas, feito semelhante ao Filho de Deus, permanece sacerdote para sempre.

[[v58-7-4]]

^<<v58-7-4,4>>^ Vejam como era grande esse a quem Abraão, o patriarca, pagou o dízimo tirado dos melhores despojos.

[[v58-7-5]]

^<<v58-7-5,5>>^ Ora, os que dentre os filhos de Levi recebem o sacerdócio têm ordem, de acordo com a lei, de recolher os dízimos do povo, ou seja, dos seus irmãos, embora estes sejam descendentes de Abraão.

[[v58-7-6]]

^<<v58-7-6,6>>^ Entretanto, aquele cuja genealogia não se inclui entre os filhos de Levi recebeu dízimos de Abraão e abençoou aquele que havia recebido as promessas.

[[v58-7-7]]

^<<v58-7-7,7>>^ Evidentemente, não há dúvida de que o inferior é abençoado pelo superior.

[[v58-7-8]]

^<<v58-7-8,8>>^ Aliás, aqui os que recebem dízimos são homens mortais, porém ali o dízimo foi recebido por aquele de quem se testifica que vive.

[[v58-7-9]]

^<<v58-7-9,9>>^ E, por assim dizer, também Levi, que recebe dízimos, pagou-os na pessoa de Abraão.

[[v58-7-10]]

^<<v58-7-10,10>>^ Porque Levi, por assim dizer, já estava no corpo de seu pai Abraão, quando Melquisedeque foi ao encontro deste.

[[v58-7-11]]

^<<v58-7-11,11>>^ Portanto, se a perfeição fosse possível por meio do sacerdócio levítico — pois foi com base nele que o povo recebeu a lei —, que necessidade haveria ainda de que se levantasse outro sacerdote, segundo a ordem de Melquisedeque, e não segundo a ordem de Arão?

[[v58-7-12]]

^<<v58-7-12,12>>^ Pois, quando se muda o sacerdócio, necessariamente muda também a lei.

[[v58-7-13]]

^<<v58-7-13,13>>^ Porque aquele de quem são ditas estas coisas pertence a outra tribo, da qual ninguém prestou serviço diante do altar.

[[v58-7-14]]

^<<v58-7-14,14>>^ Pois é evidente que nosso Senhor procedeu de Judá, tribo à qual Moisés nunca falou nada a respeito de sacerdócio.

[[v58-7-15]]

^<<v58-7-15,15>>^ E isto é ainda muito mais evidente, quando, à semelhança de Melquisedeque, surge outro sacerdote,

[[v58-7-16]]

^<<v58-7-16,16>>^ constituído não conforme a lei de mandamento carnal, mas segundo o poder de vida que não tem fim.

[[v58-7-17]]

^<<v58-7-17,17>>^ Porque dele se testifica: "Você é sacerdote para sempre, segundo a ordem de Melquisedeque."

[[v58-7-18]]

^<<v58-7-18,18>>^ Portanto, por um lado, se revoga a ordenança anterior, por causa de sua fraqueza e inutilidade,

[[v58-7-19]]

^<<v58-7-19,19>>^ pois a lei nunca aperfeiçoou coisa alguma; e, por outro lado, se introduz esperança superior, pela qual nos chegamos a Deus.

[[v58-7-20]]

^<<v58-7-20,20>>^ E isto não se deu sem juramento. Porque os outros são feitos sacerdotes sem juramento,

[[v58-7-21]]

^<<v58-7-21,21>>^ mas este foi feito sacerdote com juramento, por aquele que lhe disse: "O Senhor jurou e não se arrependerá: ‘Você é sacerdote para sempre.’"

[[v58-7-22]]

^<<v58-7-22,22>>^ Por isso mesmo, Jesus se tornou fiador de superior aliança.

[[v58-7-23]]

^<<v58-7-23,23>>^ Ora, os outros são feitos sacerdotes em maior número, porque a morte os impede de continuar;

[[v58-7-24]]

^<<v58-7-24,24>>^ Jesus, no entanto, porque continua para sempre, tem o seu sacerdócio imutável.

[[v58-7-25]]

^<<v58-7-25,25>>^ Por isso, também pode salvar totalmente os que por ele se aproximam de Deus, vivendo sempre para interceder por eles.

[[v58-7-26]]

^<<v58-7-26,26>>^ Porque nos convinha um sumo sacerdote como este, santo, inculpável, sem mácula, separado dos pecadores e exaltado acima dos céus,

[[v58-7-27]]

^<<v58-7-27,27>>^ que não tem necessidade, como os outros sumos sacerdotes, de oferecer sacrifícios todos os dias, primeiro, por seus próprios pecados, depois, pelos do povo; porque fez isto uma vez por todas, quando a si mesmo ofereceu.

[[v58-7-28]]

^<<v58-7-28,28>>^ Porque a lei constitui homens sujeitos a fraquezas como sumos sacerdotes, mas a palavra do juramento, que foi posterior à lei, constitui o Filho, perfeito para sempre.

'''

xref:058-hebreus/058-hebreus-006.adoc#v58-6-0[&#60; Capítulo Anterior] | <<v58-7-0,Topo>> | xref:058-hebreus/058-hebreus-008.adoc#v58-8-0[Próximo Capítulo &#62;]