include::./index.adoc[]

[[v58-10-0]]
=== Hebreus, 10
// naa ?, NAA - Nova Almeida Atualizada

[[v58-10-1]]

^<<v58-10-1,1>>^ Ora, visto que a lei é apenas uma sombra dos bens vindouros, não a imagem real das coisas, nunca consegue aperfeiçoar aqueles que se aproximam de Deus com os mesmos sacrifícios que, ano após ano, continuamente, eles oferecem.

[[v58-10-2]]

^<<v58-10-2,2>>^ Se isto fosse possível, será que os sacrifícios não teriam deixado de ser oferecidos? Porque os que prestam culto, tendo sido purificados uma vez por todas, não mais teriam consciência de pecados!

[[v58-10-3]]

^<<v58-10-3,3>>^ Entretanto, nesses sacrifícios ocorre recordação de pecados todos os anos,

[[v58-10-4]]

^<<v58-10-4,4>>^ porque é impossível que o sangue de touros e de bodes remova pecados.

[[v58-10-5]]

^<<v58-10-5,5>>^ Por isso, ao entrar no mundo, Cristo disse: "Sacrifício e oferta não quiseste, mas preparaste um corpo para mim;

[[v58-10-6]]

^<<v58-10-6,6>>^ não te agradaste de holocaustos e ofertas pelo pecado.

[[v58-10-7]]

^<<v58-10-7,7>>^ Então eu disse: ‘Eis aqui estou! No rolo do livro está escrito a meu respeito. Estou aqui para fazer, ó Deus, a tua vontade.’"

[[v58-10-8]]

^<<v58-10-8,8>>^ Depois de dizer, como acima: "Sacrifícios, ofertas, holocaustos e ofertas pelo pecado não quiseste, nem deles te agradaste" — coisas que se oferecem segundo a lei —,

[[v58-10-9]]

^<<v58-10-9,9>>^ num segundo momento acrescentou: "Eis aqui estou para fazer, ó Deus, a tua vontade." Ele remove o primeiro para estabelecer o segundo.

[[v58-10-10]]

^<<v58-10-10,10>>^ Nessa vontade é que temos sido santificados, mediante a oferta do corpo de Jesus Cristo, uma vez por todas.

[[v58-10-11]]

^<<v58-10-11,11>>^ Ora, todo sacerdote se apresenta, dia após dia, para exercer o serviço sagrado e oferecer muitas vezes os mesmos sacrifícios, que nunca jamais podem remover pecados.

[[v58-10-12]]

^<<v58-10-12,12>>^ Jesus, porém, tendo oferecido, para sempre, um único sacrifício pelos pecados, assentou-se à direita de Deus,

[[v58-10-13]]

^<<v58-10-13,13>>^ aguardando, daí em diante, até que os seus inimigos sejam postos por estrado dos seus pés.

[[v58-10-14]]

^<<v58-10-14,14>>^ Porque, com uma única oferta, aperfeiçoou para sempre os que estão sendo santificados.

[[v58-10-15]]

^<<v58-10-15,15>>^ E disto nos dá testemunho também o Espírito Santo. Porque, após ter dito:

[[v58-10-16]]

^<<v58-10-16,16>>^ "Esta é a aliança que farei com eles, depois daqueles dias, diz o Senhor: Imprimirei as minhas leis no coração deles e as inscreverei sobre a sua mente",

[[v58-10-17]]

^<<v58-10-17,17>>^ acrescenta: "Também dos seus pecados e das suas iniquidades jamais me lembrarei."

[[v58-10-18]]

^<<v58-10-18,18>>^ Ora, onde há remissão de pecados, não existe mais necessidade de sacrifício pelo pecado.

[[v58-10-19]]

^<<v58-10-19,19>>^ Portanto, meus irmãos, tendo ousadia para entrar no Santuário, pelo sangue de Jesus,

[[v58-10-20]]

^<<v58-10-20,20>>^ pelo novo e vivo caminho que ele nos abriu por meio do véu, isto é, pela sua carne,

[[v58-10-21]]

^<<v58-10-21,21>>^ e tendo um grande sacerdote sobre a casa de Deus,

[[v58-10-22]]

^<<v58-10-22,22>>^ aproximemo-nos com um coração sincero, em plena certeza de fé, tendo o coração purificado de má consciência e o corpo lavado com água pura.

[[v58-10-23]]

^<<v58-10-23,23>>^ Guardemos firme a confissão da esperança, sem vacilar, pois quem fez a promessa é fiel.

[[v58-10-24]]

^<<v58-10-24,24>>^ Cuidemos também de nos animar uns aos outros no amor e na prática de boas obras.

[[v58-10-25]]

^<<v58-10-25,25>>^ Não deixemos de nos congregar, como é costume de alguns. Pelo contrário, façamos admoestações, ainda mais agora que vocês veem que o Dia se aproxima.

[[v58-10-26]]

^<<v58-10-26,26>>^ Porque, se continuarmos a pecar de propósito, depois de termos recebido o conhecimento da verdade, já não resta sacrifício pelos pecados.

[[v58-10-27]]

^<<v58-10-27,27>>^ Pelo contrário, resta apenas uma terrível expectativa de juízo e fogo vingador prestes a consumir os adversários.

[[v58-10-28]]

^<<v58-10-28,28>>^ Quem tiver rejeitado a lei de Moisés morre sem misericórdia, pelo depoimento de duas ou três testemunhas.

[[v58-10-29]]

^<<v58-10-29,29>>^ Imaginem quanto mais severo deve ser o castigo daquele que pisou o Filho de Deus, profanou o sangue da aliança com o qual foi santificado e insultou o Espírito da graça!

[[v58-10-30]]

^<<v58-10-30,30>>^ Pois conhecemos aquele que disse: "A mim pertence a vingança; eu retribuirei." E outra vez: "O Senhor julgará o seu povo."

[[v58-10-31]]

^<<v58-10-31,31>>^ Horrível coisa é cair nas mãos do Deus vivo.

[[v58-10-32]]

^<<v58-10-32,32>>^ Lembrem-se dos dias passados, quando, depois que foram iluminados, vocês sustentaram grande luta e sofrimentos.

[[v58-10-33]]

^<<v58-10-33,33>>^ Em certos momentos vocês foram transformados em espetáculo, tanto para serem insultados quanto para serem maltratados; em outros vocês se tornaram coparticipantes com aqueles que foram tratados assim.

[[v58-10-34]]

^<<v58-10-34,34>>^ Porque vocês não apenas se compadeceram dos encarcerados, mas também aceitaram com alegria a espoliação dos seus bens, porque sabiam que tinham um patrimônio superior e durável.

[[v58-10-35]]

^<<v58-10-35,35>>^ Portanto, não percam a confiança de vocês, porque ela tem grande recompensa.

[[v58-10-36]]

^<<v58-10-36,36>>^ Vocês precisam perseverar, para que, havendo feito a vontade de Deus, alcancem a promessa.

[[v58-10-37]]

^<<v58-10-37,37>>^ "Porque, ainda dentro de pouco tempo, aquele que vem virá e não irá demorar;

[[v58-10-38]]

^<<v58-10-38,38>>^ mas o meu justo viverá pela fé; e, se retroceder, dele a minha alma não se agradará."

[[v58-10-39]]

^<<v58-10-39,39>>^ Nós, porém, não somos dos que retrocedem para a perdição, mas somos da fé, para a preservação da alma.

'''

xref:058-hebreus/058-hebreus-009.adoc#v58-9-0[&#60; Capítulo Anterior] | <<v58-10-0,Topo>> | xref:058-hebreus/058-hebreus-011.adoc#v58-11-0[Próximo Capítulo &#62;]