include::./index.adoc[]

[[v58-8-0]]
=== Hebreus, 8
// naa ?, NAA - Nova Almeida Atualizada

[[v58-8-1]]

^<<v58-8-1,1>>^ Ora, o essencial das coisas que estamos dizendo é que temos tal sumo sacerdote, que se assentou à direita do trono da Majestade nos céus,

[[v58-8-2]]

^<<v58-8-2,2>>^ como ministro do santuário e do verdadeiro tabernáculo que o Senhor erigiu, e não o homem.

[[v58-8-3]]

^<<v58-8-3,3>>^ Pois todo sumo sacerdote é constituído para oferecer dons e sacrifícios; por isso, era necessário que também esse sumo sacerdote tivesse o que oferecer.

[[v58-8-4]]

^<<v58-8-4,4>>^ Se ele estivesse na terra, nem mesmo sacerdote seria, visto existirem aqueles que oferecem os dons segundo a lei.

[[v58-8-5]]

^<<v58-8-5,5>>^ Estes ministram em figura e sombra das coisas celestiais, assim como Moisés foi divinamente instruído, quando estava para construir o tabernáculo. Pois Deus disse: "Tenha cuidado para fazer tudo de acordo com o modelo que foi mostrado a você no monte."

[[v58-8-6]]

^<<v58-8-6,6>>^ Mas agora Jesus obteve um ministério tanto mais excelente, quanto é também Mediador de superior aliança instituída com base em superiores promessas.

[[v58-8-7]]

^<<v58-8-7,7>>^ Porque, se aquela primeira aliança tivesse sido sem defeito, de maneira alguma estaria sendo buscado lugar para uma segunda aliança.

[[v58-8-8]]

^<<v58-8-8,8>>^ E, de fato, repreendendo-os, diz: "Eis aí vêm dias, diz o Senhor, e firmarei nova aliança com a casa de Israel e com a casa de Judá,

[[v58-8-9]]

^<<v58-8-9,9>>^ não segundo a aliança que fiz com os seus pais, no dia em que os tomei pela mão, para os tirar da terra do Egito; pois eles não continuaram na minha aliança, e eu não dei atenção a eles, diz o Senhor.

[[v58-8-10]]

^<<v58-8-10,10>>^ Porque esta é a aliança que farei com a casa de Israel, depois daqueles dias, diz o Senhor: Imprimirei as minhas leis na mente deles e as inscreverei sobre o seu coração; e eu serei o seu Deus, e eles serão o meu povo.

[[v58-8-11]]

^<<v58-8-11,11>>^ E não ensinará jamais cada um ao seu próximo, nem cada um ao seu irmão, dizendo: ‘Conheça o Senhor’; porque todos me conhecerão, desde o menor até o maior deles.

[[v58-8-12]]

^<<v58-8-12,12>>^ Pois, para com as suas iniquidades, usarei de misericórdia e dos seus pecados jamais me lembrarei."

[[v58-8-13]]

^<<v58-8-13,13>>^ Quando ele diz "nova aliança", torna antiquada a primeira. Ora, aquilo que se torna antiquado e envelhecido está prestes a desaparecer.

'''

xref:058-hebreus/058-hebreus-007.adoc#v58-7-0[&#60; Capítulo Anterior] | <<v58-8-0,Topo>> | xref:058-hebreus/058-hebreus-009.adoc#v58-9-0[Próximo Capítulo &#62;]