include::./index.adoc[]

[[v63-1-0]]
=== 2 João, 1
// naa ?, NAA - Nova Almeida Atualizada

[[v63-1-1]]

^<<v63-1-1,1>>^ O presbítero à senhora eleita e aos seus filhos, a quem eu amo na verdade — e não somente eu, mas também todos os que conhecem a verdade —,

[[v63-1-2]]

^<<v63-1-2,2>>^ por causa da verdade que permanece em nós e conosco estará para sempre.

[[v63-1-3]]

^<<v63-1-3,3>>^ Que a graça, a misericórdia e a paz, da parte de Deus Pai e de Jesus Cristo, o Filho do Pai, estejam conosco em verdade e amor.

[[v63-1-4]]

^<<v63-1-4,4>>^ Fiquei muito alegre por ter encontrado alguns de seus filhos que andam na verdade, de acordo com o mandamento que recebemos do Pai.

[[v63-1-5]]

^<<v63-1-5,5>>^ E agora, senhora, peço-lhe, não como se escrevesse mandamento novo, mas o mesmo que temos tido desde o princípio: que nos amemos uns aos outros.

[[v63-1-6]]

^<<v63-1-6,6>>^ E o amor é este: que andemos segundo os mandamentos de Deus. Este mandamento, como vocês ouviram desde o princípio, é que vocês vivam nesse amor.

[[v63-1-7]]

^<<v63-1-7,7>>^ Porque muitos enganadores têm saído mundo afora, os quais não confessam que Jesus Cristo veio em carne; este é o enganador e o anticristo.

[[v63-1-8]]

^<<v63-1-8,8>>^ Tenham cuidado para que não percam aquilo que temos realizado com esforço, mas recebam plena recompensa.

[[v63-1-9]]

^<<v63-1-9,9>>^ Todo aquele que vai além da doutrina de Cristo e nela não permanece não tem Deus; o que permanece na doutrina, esse tem tanto o Pai como o Filho.

[[v63-1-10]]

^<<v63-1-10,10>>^ Se alguém for até vocês e não levar esta doutrina, não o recebam em casa, nem lhe deem as boas-vindas.

[[v63-1-11]]

^<<v63-1-11,11>>^ Porque aquele que lhe dá boas-vindas se faz cúmplice das suas obras más.

[[v63-1-12]]

^<<v63-1-12,12>>^ Ainda tinha muitas coisas a lhes escrever, mas não quis fazê-lo com papel e tinta, pois espero ir visitá-los, e conversaremos pessoalmente, para que a nossa alegria seja completa.

[[v63-1-13]]

^<<v63-1-13,13>>^ Os filhos da sua irmã eleita mandam saudações.

'''

xref:062-1-joao/062-1-joao-005.adoc#v62-5-0[&#60; Capítulo Anterior] | <<v63-1-0,Topo>> | xref:064-3-joao/064-3-joao-001.adoc#v64-1-0[Próximo Capítulo &#62;]