include::./index.adoc[]

[[v53-2-0]]
=== 2 Tessalonicenses, 2
// naa ?, NAA - Nova Almeida Atualizada

[[v53-2-1]]

^<<v53-2-1,1>>^ Irmãos, no que diz respeito à vinda de nosso Senhor Jesus Cristo e à nossa reunião com ele, pedimos

[[v53-2-2]]

^<<v53-2-2,2>>^ que vocês não se deixem demover facilmente de seu modo de pensar, nem fiquem perturbados, quer por espírito, quer por palavra, quer por carta, como se procedesse de nós, dando a entender que o Dia do Senhor já chegou.

[[v53-2-3]]

^<<v53-2-3,3>>^ Ninguém, de modo nenhum, os engane, porque isto não acontecerá sem que primeiro venha a apostasia e seja revelado o homem da iniquidade, o filho da perdição,

[[v53-2-4]]

^<<v53-2-4,4>>^ o qual se opõe e se levanta contra tudo o que se chama Deus ou é objeto de culto, a ponto de assentar-se no santuário de Deus, apresentando-se como se fosse o próprio Deus.

[[v53-2-5]]

^<<v53-2-5,5>>^ Vocês não lembram que eu costumava lhes dizer estas coisas, quando ainda estava com vocês?

[[v53-2-6]]

^<<v53-2-6,6>>^ E, agora, vocês sabem o que o detém, para que ele seja revelado a seu tempo.

[[v53-2-7]]

^<<v53-2-7,7>>^ Porque o mistério da iniquidade já opera e aguarda somente que seja afastado aquele que agora o detém.

[[v53-2-8]]

^<<v53-2-8,8>>^ Então será revelado o iníquo, a quem o Senhor Jesus matará com o sopro de sua boca e destruirá pela manifestação de sua vinda.

[[v53-2-9]]

^<<v53-2-9,9>>^ Ora, o aparecimento do iníquo é segundo a ação de Satanás, com todo poder, sinais e prodígios da mentira,

[[v53-2-10]]

^<<v53-2-10,10>>^ e com todo engano de injustiça aos que estão perecendo, porque não acolheram o amor da verdade para serem salvos.

[[v53-2-11]]

^<<v53-2-11,11>>^ É por este motivo que Deus lhes envia a operação do erro, para darem crédito à mentira,

[[v53-2-12]]

^<<v53-2-12,12>>^ a fim de serem condenados todos os que não creram na verdade, mas tiveram prazer na injustiça.

[[v53-2-13]]

^<<v53-2-13,13>>^ Mas devemos sempre dar graças a Deus por vocês, irmãos amados pelo Senhor, porque Deus os escolheu desde o princípio para a salvação, pela santificação do Espírito e fé na verdade.

[[v53-2-14]]

^<<v53-2-14,14>>^ Foi para isso que também Deus os chamou mediante o nosso evangelho, para que vocês alcancem a glória de nosso Senhor Jesus Cristo.

[[v53-2-15]]

^<<v53-2-15,15>>^ Assim, pois, irmãos, fiquem firmes e guardem as tradições que lhes foram ensinadas, seja por palavra, seja por carta nossa.

[[v53-2-16]]

^<<v53-2-16,16>>^ Que o próprio Jesus Cristo, nosso Senhor, e Deus, o nosso Pai, que nos amou e nos deu eterna consolação e boa esperança, pela graça,

[[v53-2-17]]

^<<v53-2-17,17>>^ console o coração de vocês e os fortaleça em toda boa obra e boa palavra.

'''

xref:053-2-tessalonicenses/053-2-tessalonicenses-001.adoc#v53-1-0[&#60; Capítulo Anterior] | <<v53-2-0,Topo>> | xref:053-2-tessalonicenses/053-2-tessalonicenses-003.adoc#v53-3-0[Próximo Capítulo &#62;]