include::./index.adoc[]

[[v53-3-0]]
=== 2 Tessalonicenses, 3
// naa ?, NAA - Nova Almeida Atualizada

[[v53-3-1]]

^<<v53-3-1,1>>^ Finalmente, irmãos, orem por nós, para que a palavra do Senhor se propague e seja glorificada, como aconteceu entre vocês.

[[v53-3-2]]

^<<v53-3-2,2>>^ Orem também para que sejamos livres das pessoas perversas e más; porque a fé não é de todos.

[[v53-3-3]]

^<<v53-3-3,3>>^ Mas o Senhor é fiel. Ele os fortalecerá e os guardará do Maligno.

[[v53-3-4]]

^<<v53-3-4,4>>^ Temos confiança no Senhor quanto a vocês, de que não só estão praticando as coisas que lhes ordenamos, como também continuarão a fazê-las.

[[v53-3-5]]

^<<v53-3-5,5>>^ Que o Senhor conduza o coração de vocês ao amor de Deus e à perseverança de Cristo.

[[v53-3-6]]

^<<v53-3-6,6>>^ Irmãos, em nome do nosso Senhor Jesus Cristo, ordenamos a vocês que se afastem de todo irmão que vive de forma desordenada e não segundo a tradição que vocês receberam de nós.

[[v53-3-7]]

^<<v53-3-7,7>>^ Porque vocês mesmos sabem como devem nos imitar, visto que nunca vivemos de forma desordenada quando estivemos entre vocês,

[[v53-3-8]]

^<<v53-3-8,8>>^ nem jamais comemos pão à custa dos outros. Pelo contrário, trabalhamos com esforço e fadiga, de noite e de dia, a fim de não sermos pesados a nenhum de vocês.

[[v53-3-9]]

^<<v53-3-9,9>>^ Não que não tivéssemos o direito de receber algo, mas porque tínhamos em vista apresentar a nós mesmos como exemplo, para que vocês nos imitassem.

[[v53-3-10]]

^<<v53-3-10,10>>^ Porque, quando ainda estávamos com vocês, ordenamos isto: "Se alguém não quer trabalhar, também não coma."

[[v53-3-11]]

^<<v53-3-11,11>>^ Pois, de fato, ouvimos que há entre vocês algumas pessoas que vivem de forma desordenada. Não trabalham, mas se intrometem na vida dos outros.

[[v53-3-12]]

^<<v53-3-12,12>>^ A essas pessoas determinamos e exortamos, no Senhor Jesus Cristo, que, trabalhando tranquilamente, comam o seu próprio pão.

[[v53-3-13]]

^<<v53-3-13,13>>^ Quanto a vocês, irmãos, não se cansem de fazer o bem.

[[v53-3-14]]

^<<v53-3-14,14>>^ Caso alguém não obedeça à nossa palavra dada por esta carta, vejam de quem se trata e não se associem com ele, para que fique envergonhado.

[[v53-3-15]]

^<<v53-3-15,15>>^ Contudo, não o tratem como inimigo, mas admoestem-no como irmão.

[[v53-3-16]]

^<<v53-3-16,16>>^ Que o Senhor da paz, ele mesmo, dê a vocês a paz, sempre e de todas as maneiras. O Senhor esteja com todos vocês.

[[v53-3-17]]

^<<v53-3-17,17>>^ A saudação é de próprio punho: Paulo. Este é o sinal em cada carta; é assim que eu assino.

[[v53-3-18]]

^<<v53-3-18,18>>^ A graça de nosso Senhor Jesus Cristo esteja com todos vocês.

'''

xref:053-2-tessalonicenses/053-2-tessalonicenses-002.adoc#v53-2-0[&#60; Capítulo Anterior] | <<v53-3-0,Topo>> | xref:054-1-timoteo/054-1-timoteo-001.adoc#v54-1-0[Próximo Capítulo &#62;]