include::./index.adoc[]

[[v53-1-0]]
=== 2 Tessalonicenses, 1
// naa ?, NAA - Nova Almeida Atualizada

[[v53-1-1]]

^<<v53-1-1,1>>^ Paulo, Silvano e Timóteo, à igreja dos tessalonicenses, em Deus, nosso Pai, e no Senhor Jesus Cristo.

[[v53-1-2]]

^<<v53-1-2,2>>^ Que a graça e a paz de Deus, nosso Pai, e do Senhor Jesus Cristo estejam com vocês.

[[v53-1-3]]

^<<v53-1-3,3>>^ Irmãos, devemos sempre dar graças a Deus por vocês, como convém, pois a fé que vocês têm cresce cada vez mais, e o amor que todos vocês têm uns pelos outros vai aumentando.

[[v53-1-4]]

^<<v53-1-4,4>>^ É por isso que nós mesmos nos orgulhamos de vocês nas igrejas de Deus, por causa da perseverança e da fé que vocês demonstram em todas as perseguições e tribulações que estão suportando.

[[v53-1-5]]

^<<v53-1-5,5>>^ Isso é sinal evidente do justo juízo de Deus, para que vocês sejam considerados dignos do Reino de Deus, pelo qual vocês também estão sofrendo.

[[v53-1-6]]

^<<v53-1-6,6>>^ Pois, de fato, é justo para com Deus que ele retribua com tribulação aos que causam tribulação a vocês

[[v53-1-7]]

^<<v53-1-7,7>>^ e que dê a vocês, que estão sendo atribulados, alívio juntamente conosco, quando do céu se manifestar o Senhor Jesus com os anjos do seu poder,

[[v53-1-8]]

^<<v53-1-8,8>>^ em chama de fogo, tomando vingança contra os que não conhecem a Deus e contra os que não obedecem ao evangelho de nosso Senhor Jesus.

[[v53-1-9]]

^<<v53-1-9,9>>^ Estes sofrerão penalidade de eterna destruição, banidos da face do Senhor e da glória do seu poder,

[[v53-1-10]]

^<<v53-1-10,10>>^ quando ele vier, naquele Dia, para ser glorificado nos seus santos e ser admirado em todos os que creram. Isto inclui vocês, que creram em nosso testemunho.

[[v53-1-11]]

^<<v53-1-11,11>>^ Por isso, também não cessamos de orar por vocês, pedindo que o nosso Deus os torne dignos da sua vocação e cumpra com poder todo propósito de bondade e obra de fé,

[[v53-1-12]]

^<<v53-1-12,12>>^ a fim de que o nome de nosso Senhor Jesus seja glorificado em vocês e vocês sejam glorificados nele, segundo a graça do nosso Deus e do Senhor Jesus Cristo.

'''

xref:052-1-tessalonicenses/052-1-tessalonicenses-005.adoc#v52-5-0[&#60; Capítulo Anterior] | <<v53-1-0,Topo>> | xref:053-2-tessalonicenses/053-2-tessalonicenses-002.adoc#v53-2-0[Próximo Capítulo &#62;]