include::./index.adoc[]

[[v19-72-0]]
=== Salmos, 72
// naa ?, NAA - Nova Almeida Atualizada

[[v19-72-1]]

^<<v19-72-1,1>>^ Concede ao rei, ó Deus, os teus juízos e a tua justiça, ao filho do rei.

[[v19-72-2]]

^<<v19-72-2,2>>^ Que ele julgue o teu povo com justiça e os teus aflitos, com retidão.

[[v19-72-3]]

^<<v19-72-3,3>>^ Os montes trarão paz ao povo; também as colinas a trarão, com justiça.

[[v19-72-4]]

^<<v19-72-4,4>>^ Que o rei julgue os aflitos do povo, salve os filhos dos necessitados e esmague o opressor.

[[v19-72-5]]

^<<v19-72-5,5>>^ Ele permanecerá enquanto existir o sol e enquanto durar a lua, através das gerações.

[[v19-72-6]]

^<<v19-72-6,6>>^ Seja ele como chuva que desce sobre a campina ceifada, como aguaceiros que regam a terra.

[[v19-72-7]]

^<<v19-72-7,7>>^ Que em seus dias floresçam os justos, e haja abundância de paz até que cesse de haver lua.

[[v19-72-8]]

^<<v19-72-8,8>>^ Domine ele de mar a mar e desde o rio até os confins da terra.

[[v19-72-9]]

^<<v19-72-9,9>>^ Curvem-se diante dele os habitantes do deserto, e os seus inimigos lambam o pó.

[[v19-72-10]]

^<<v19-72-10,10>>^ Que os reis de Társis e das ilhas lhe paguem tributo; os reis de Sabá e de Sebá lhe ofereçam presentes.

[[v19-72-11]]

^<<v19-72-11,11>>^ E todos os reis se prostrem diante dele; todas as nações o sirvam.

[[v19-72-12]]

^<<v19-72-12,12>>^ Porque ele livra os necessitados que pedem socorro, e também os aflitos e aqueles que não têm quem os ajude.

[[v19-72-13]]

^<<v19-72-13,13>>^ Ele se compadece dos fracos e dos necessitados e salva a alma dos que precisam de auxílio.

[[v19-72-14]]

^<<v19-72-14,14>>^ Ele os redime da opressão e da violência, e precioso lhe é o sangue deles.

[[v19-72-15]]

^<<v19-72-15,15>>^ Viva o rei! E que lhe deem ouro de Sabá! Que continuamente se faça por ele oração, e o bendigam todos os dias.

[[v19-72-16]]

^<<v19-72-16,16>>^ Haja na terra abundância de cereais, que ondulem até o alto dos montes. Sejam os seus frutos como os do Líbano, e das cidades floresçam os habitantes como a erva da terra.

[[v19-72-17]]

^<<v19-72-17,17>>^ Que o nome do rei permaneça para sempre, e que prospere enquanto o sol brilhar! Que todos sejam abençoados por meio dele, e que todas as nações lhe chamem bem-aventurado.

[[v19-72-18]]

^<<v19-72-18,18>>^ Bendito seja o Senhor  Deus, o Deus de Israel, o único que faz maravilhas!

[[v19-72-19]]

^<<v19-72-19,19>>^ Bendito para sempre o seu glorioso nome, e da sua glória se encha toda a terra. Amém e amém!

[[v19-72-20]]

^<<v19-72-20,20>>^ Aqui terminam as orações de Davi, filho de Jessé.

'''

xref:019-salmos/019-salmos-071.adoc#v19-71-0[&#60; Capítulo Anterior] | <<v19-72-0,Topo>> | xref:019-salmos/019-salmos-073.adoc#v19-73-0[Próximo Capítulo &#62;]