include::./index.adoc[]

[[v19-65-0]]
=== Salmos, 65
// naa ?, NAA - Nova Almeida Atualizada

[[v19-65-1]]

^<<v19-65-1,1>>^ A ti, ó Deus, o louvor é devido em Sião, e a ti se pagarão os votos.

[[v19-65-2]]

^<<v19-65-2,2>>^ Ó tu que escutas a oração, a ti virão todas as pessoas,

[[v19-65-3]]

^<<v19-65-3,3>>^ por causa de suas iniquidades. Se prevalecem as nossas transgressões, tu as perdoas.

[[v19-65-4]]

^<<v19-65-4,4>>^ Bem-aventurado aquele a quem escolhes e aproximas de ti, para que habite nos teus átrios. Ficaremos satisfeitos com a bondade de tua casa — o teu santo templo.

[[v19-65-5]]

^<<v19-65-5,5>>^ Com tremendos feitos nos respondes em tua justiça, ó Deus, Salvador nosso, esperança de todos os confins da terra e dos mares longínquos.

[[v19-65-6]]

^<<v19-65-6,6>>^ Com a tua força consolidas os montes, cingido de poder.

[[v19-65-7]]

^<<v19-65-7,7>>^ Tu acalmas o rugido dos mares, o ruído das suas ondas e o tumulto dos povos.

[[v19-65-8]]

^<<v19-65-8,8>>^ Os que habitam nos confins da terra temem os teus sinais; os que vêm do Oriente e do Ocidente, tu os fazes exultar de júbilo.

[[v19-65-9]]

^<<v19-65-9,9>>^ Tu visitas a terra e a regas; tu a enriqueces grandemente. Os ribeiros de Deus são abundantes de água; provês o cereal, porque para isso preparas a terra,

[[v19-65-10]]

^<<v19-65-10,10>>^ regando-lhe os sulcos e desmanchando os torrões. Tu a amoleces com chuviscos e lhe abençoas a produção.

[[v19-65-11]]

^<<v19-65-11,11>>^ Coroas o ano da tua bondade; as tuas pegadas destilam fartura,

[[v19-65-12]]

^<<v19-65-12,12>>^ destilam sobre as pastagens do deserto, e de júbilo se revestem as colinas.

[[v19-65-13]]

^<<v19-65-13,13>>^ Os campos se cobrem de rebanhos, e os vales se enchem de espigas; exultam de alegria e cantam.

'''

xref:019-salmos/019-salmos-064.adoc#v19-64-0[&#60; Capítulo Anterior] | <<v19-65-0,Topo>> | xref:019-salmos/019-salmos-066.adoc#v19-66-0[Próximo Capítulo &#62;]