include::./index.adoc[]

[[v19-48-0]]
=== Salmos, 48
// naa ?, NAA - Nova Almeida Atualizada

[[v19-48-1]]

^<<v19-48-1,1>>^ Grande é o Senhor e mui digno de ser louvado, na cidade do nosso Deus, seu santo monte.

[[v19-48-2]]

^<<v19-48-2,2>>^ Alto e belo, alegria de toda a terra, é o monte Sião, para os lados do Norte, a cidade do grande Rei.

[[v19-48-3]]

^<<v19-48-3,3>>^ Nos palácios dela, Deus se faz conhecer como alto refúgio.

[[v19-48-4]]

^<<v19-48-4,4>>^ Por isso, eis que os reis se uniram e juntos a atacaram.

[[v19-48-5]]

^<<v19-48-5,5>>^ Quando viram, se espantaram; ficaram com medo e fugiram apressados.

[[v19-48-6]]

^<<v19-48-6,6>>^ O terror ali os venceu, e sentiram dores como de mulher que está dando à luz.

[[v19-48-7]]

^<<v19-48-7,7>>^ Com vento leste destruíste as naus de Társis.

[[v19-48-8]]

^<<v19-48-8,8>>^ Como temos ouvido dizer, agora vimos que aconteceu na cidade do Senhor  dos Exércitos, na cidade do nosso Deus. Deus a estabelece para sempre.

[[v19-48-9]]

^<<v19-48-9,9>>^ Pensamos, ó Deus, na tua misericórdia no meio do teu templo.

[[v19-48-10]]

^<<v19-48-10,10>>^ Como o teu nome, ó Deus, assim o teu louvor se estende até os confins da terra; a tua mão direita está cheia de justiça.

[[v19-48-11]]

^<<v19-48-11,11>>^ Alegre-se o monte Sião, exultem as filhas de Judá, por causa dos teus juízos.

[[v19-48-12]]

^<<v19-48-12,12>>^ Andem em volta de Sião, rodeiem-na toda, contem as suas torres;

[[v19-48-13]]

^<<v19-48-13,13>>^ notem bem as suas muralhas, observem os seus palácios, para que possam contar às gerações vindouras

[[v19-48-14]]

^<<v19-48-14,14>>^ que este é Deus, o nosso Deus para todo o sempre; ele será nosso guia até a morte.

'''

xref:019-salmos/019-salmos-047.adoc#v19-47-0[&#60; Capítulo Anterior] | <<v19-48-0,Topo>> | xref:019-salmos/019-salmos-049.adoc#v19-49-0[Próximo Capítulo &#62;]