include::./index.adoc[]

[[v19-98-0]]
=== Salmos, 98
// naa ?, NAA - Nova Almeida Atualizada

[[v19-98-1]]

^<<v19-98-1,1>>^ Cantem ao Senhor um cântico novo, porque ele tem feito maravilhas; a sua mão direita e o seu braço santo lhe alcançaram a vitória.

[[v19-98-2]]

^<<v19-98-2,2>>^ O Senhor  fez notória a sua salvação; manifestou a sua justiça diante dos olhos das nações.

[[v19-98-3]]

^<<v19-98-3,3>>^ Lembrou-se da sua misericórdia e da sua fidelidade para com a casa de Israel; todos os confins da terra viram a salvação do nosso Deus.

[[v19-98-4]]

^<<v19-98-4,4>>^ Celebrem com júbilo ao Senhor , todos os moradores da terra; gritem de alegria, exultem e cantem louvores.

[[v19-98-5]]

^<<v19-98-5,5>>^ Cantem com harpa louvores ao Senhor , com harpa e voz de canto;

[[v19-98-6]]

^<<v19-98-6,6>>^ com trombetas e ao som de buzinas, exultem diante do Senhor , que é rei.

[[v19-98-7]]

^<<v19-98-7,7>>^ Ruja o mar e a sua plenitude, o mundo e os que nele habitam.

[[v19-98-8]]

^<<v19-98-8,8>>^ Os rios batam palmas, e juntos cantem de júbilo os montes,

[[v19-98-9]]

^<<v19-98-9,9>>^ na presença do Senhor , porque ele vem julgar a terra; julgará o mundo com justiça e os povos, com retidão.

'''

xref:019-salmos/019-salmos-097.adoc#v19-97-0[&#60; Capítulo Anterior] | <<v19-98-0,Topo>> | xref:019-salmos/019-salmos-099.adoc#v19-99-0[Próximo Capítulo &#62;]