include::./index.adoc[]

[[v19-102-0]]
=== Salmos, 102
// naa ?, NAA - Nova Almeida Atualizada

[[v19-102-1]]

^<<v19-102-1,1>>^ Ouve, Senhor , a minha súplica, e cheguem a ti os meus clamores.

[[v19-102-2]]

^<<v19-102-2,2>>^ Não escondas de mim o teu rosto no dia da minha angústia; inclina-me os ouvidos; no dia em que eu clamar, responde-me depressa.

[[v19-102-3]]

^<<v19-102-3,3>>^ Porque os meus dias desaparecem como fumaça, e os meus ossos queimam como se estivessem no fogo.

[[v19-102-4]]

^<<v19-102-4,4>>^ Cortado como a erva, secou-se o meu coração; até me esqueço de comer o meu pão.

[[v19-102-5]]

^<<v19-102-5,5>>^ Os meus ossos já se apegam à pele, por causa do meu dolorido gemer.

[[v19-102-6]]

^<<v19-102-6,6>>^ Sou como o pelicano no deserto, como a coruja das ruínas.

[[v19-102-7]]

^<<v19-102-7,7>>^ Não durmo e sou como o passarinho solitário nos telhados.

[[v19-102-8]]

^<<v19-102-8,8>>^ Os meus inimigos me insultam a toda hora; furiosos contra mim, praguejam com o meu próprio nome.

[[v19-102-9]]

^<<v19-102-9,9>>^ Por pão tenho comido cinza e as lágrimas se misturam com a minha bebida,

[[v19-102-10]]

^<<v19-102-10,10>>^ por causa da tua indignação e da tua ira, porque me elevaste e depois me abateste.

[[v19-102-11]]

^<<v19-102-11,11>>^ Como a sombra que declina, assim são os meus dias, e eu vou secando como a relva.

[[v19-102-12]]

^<<v19-102-12,12>>^ Tu, porém, Senhor , permaneces para sempre, e a memória do teu nome, de geração em geração.

[[v19-102-13]]

^<<v19-102-13,13>>^ Tu te levantarás e terás piedade de Sião; é tempo de te compadeceres dela, e já chegou a sua hora.

[[v19-102-14]]

^<<v19-102-14,14>>^ Porque os teus servos amam até as pedras de Sião e se compadecem do seu pó.

[[v19-102-15]]

^<<v19-102-15,15>>^ Todas as nações temerão o nome do Senhor , e todos os reis da terra temerão a sua glória,

[[v19-102-16]]

^<<v19-102-16,16>>^ quando o Senhor  reconstruir Sião e se manifestar na sua glória,

[[v19-102-17]]

^<<v19-102-17,17>>^ quando atender à oração do desamparado e não desprezar as suas preces.

[[v19-102-18]]

^<<v19-102-18,18>>^ Isto ficará registrado para as gerações futuras, e um povo, que há de ser criado, louvará o Senhor , dizendo:

[[v19-102-19]]

^<<v19-102-19,19>>^ "O Senhor , do alto do seu santuário, desde os céus, olhou para a terra,

[[v19-102-20]]

^<<v19-102-20,20>>^ a fim de ouvir o gemido dos cativos e libertar os condenados à morte."

[[v19-102-21]]

^<<v19-102-21,21>>^ Em Sião será anunciado o nome do Senhor e o seu louvor, em Jerusalém,

[[v19-102-22]]

^<<v19-102-22,22>>^ quando se reunirem os povos e os reinos, para servirem o Senhor .

[[v19-102-23]]

^<<v19-102-23,23>>^ Ele me abateu a força no caminho e abreviou os meus dias.

[[v19-102-24]]

^<<v19-102-24,24>>^ Eu disse: Deus meu, não me leves na metade de minha vida; tu, cujos anos se estendem por todas as gerações.

[[v19-102-25]]

^<<v19-102-25,25>>^ Em tempos remotos, lançaste os fundamentos da terra; e os céus são obra das tuas mãos.

[[v19-102-26]]

^<<v19-102-26,26>>^ Eles perecerão, mas tu permaneces; todos eles envelhecerão como veste, como roupa os mudarás, e serão mudados.

[[v19-102-27]]

^<<v19-102-27,27>>^ Tu, porém, és sempre o mesmo, e os teus anos jamais terão fim.

[[v19-102-28]]

^<<v19-102-28,28>>^ Os filhos dos teus servos habitarão seguros, e diante de ti se estabelecerá a sua descendência.

'''

xref:019-salmos/019-salmos-101.adoc#v19-101-0[&#60; Capítulo Anterior] | <<v19-102-0,Topo>> | xref:019-salmos/019-salmos-103.adoc#v19-103-0[Próximo Capítulo &#62;]