include::./index.adoc[]

[[v19-69-0]]
=== Salmos, 69
// naa ?, NAA - Nova Almeida Atualizada

[[v19-69-1]]

^<<v19-69-1,1>>^ Salva-me, ó Deus, porque as águas me sobem até a alma.

[[v19-69-2]]

^<<v19-69-2,2>>^ Estou atolado num profundo lamaçal, que não dá pé. Entrei em águas profundas, e estou sendo arrastado pela correnteza.

[[v19-69-3]]

^<<v19-69-3,3>>^ Estou cansado de clamar, e a minha garganta secou; os meus olhos esmorecem de tanto esperar por meu Deus.

[[v19-69-4]]

^<<v19-69-4,4>>^ Os que, sem razão, me odeiam são mais numerosos do que os cabelos da minha cabeça; são poderosos os que querem me destruir, os que com falsos motivos são meus inimigos; por isso, tenho de restituir o que não roubei.

[[v19-69-5]]

^<<v19-69-5,5>>^ Tu, ó Deus, bem conheces a minha insensatez, e as minhas culpas não te são ocultas.

[[v19-69-6]]

^<<v19-69-6,6>>^ Não sejam envergonhados por minha causa os que esperam em ti, ó Senhor , Deus dos Exércitos; nem por minha causa sofram vexame os que te buscam, ó Deus de Israel.

[[v19-69-7]]

^<<v19-69-7,7>>^ Pois tenho suportado afrontas por amor de ti, e o meu rosto se cobre de vergonha.

[[v19-69-8]]

^<<v19-69-8,8>>^ Tornei-me um estranho para os meus irmãos e um desconhecido para os filhos da minha mãe.

[[v19-69-9]]

^<<v19-69-9,9>>^ Pois o zelo da tua casa me consumiu, e as ofensas dos que te insultam caem sobre mim.

[[v19-69-10]]

^<<v19-69-10,10>>^ Chorei, jejuei, mas até isto se tornou motivo de deboche para mim.

[[v19-69-11]]

^<<v19-69-11,11>>^ Pus um pano de saco por roupa e me tornei motivo de provérbio para eles.

[[v19-69-12]]

^<<v19-69-12,12>>^ Os que se assentam junto ao portão da cidade falam de mim, e sou motivo para cantigas de bêbados.

[[v19-69-13]]

^<<v19-69-13,13>>^ Quanto a mim, porém, Senhor , faço a ti, em tempo favorável, a minha oração. Responde-me, ó Deus, pela riqueza da tua graça. Pela tua fidelidade em socorrer,

[[v19-69-14]]

^<<v19-69-14,14>>^ livra-me do lamaçal, para que eu não me afunde; que eu seja salvo dos que me odeiam e das profundezas das águas.

[[v19-69-15]]

^<<v19-69-15,15>>^ Não deixes que a corrente das águas me arraste, nem que as profundezas do abismo me engulam, nem que se feche sobre mim a boca do poço.

[[v19-69-16]]

^<<v19-69-16,16>>^ Responde-me, Senhor , pois compassiva é a tua graça; volta-te para mim segundo a riqueza das tuas misericórdias.

[[v19-69-17]]

^<<v19-69-17,17>>^ Não escondas o rosto ao teu servo, pois estou angustiado; responde-me depressa.

[[v19-69-18]]

^<<v19-69-18,18>>^ Aproxima-te de minha alma e redime-a; resgata-me por causa dos meus inimigos.

[[v19-69-19]]

^<<v19-69-19,19>>^ Tu conheces a minha afronta, a minha vergonha e o meu vexame; todos os meus adversários estão à tua vista.

[[v19-69-20]]

^<<v19-69-20,20>>^ As afrontas partiram o meu coração, e desfaleci. Esperei por piedade, mas foi em vão. Esperei por consoladores, mas não apareceu ninguém.

[[v19-69-21]]

^<<v19-69-21,21>>^ Por alimento me deram fel e na minha sede me deram a beber vinagre.

[[v19-69-22]]

^<<v19-69-22,22>>^ Que a mesa deles se torne em laço diante deles, e a prosperidade, em armadilha.

[[v19-69-23]]

^<<v19-69-23,23>>^ Que os olhos deles se escureçam, para que não vejam; e faze com que as suas costas não parem de tremer.

[[v19-69-24]]

^<<v19-69-24,24>>^ Derrama sobre eles a tua indignação, e que o furor da tua ira os alcance.

[[v19-69-25]]

^<<v19-69-25,25>>^ Fique deserta a sua morada, e não haja quem habite nas suas tendas.

[[v19-69-26]]

^<<v19-69-26,26>>^ Pois perseguem a quem tu feriste e ficam falando sobre as dores daqueles a quem golpeaste.

[[v19-69-27]]

^<<v19-69-27,27>>^ Soma-lhes iniquidade à iniquidade, e que não tenham acesso à tua justiça.

[[v19-69-28]]

^<<v19-69-28,28>>^ Sejam riscados do Livro dos Vivos e não sejam incluídos na lista dos justos.

[[v19-69-29]]

^<<v19-69-29,29>>^ Quanto a mim, porém, estou sofrendo e aflito; que a tua salvação, ó Deus, me ponha num alto refúgio.

[[v19-69-30]]

^<<v19-69-30,30>>^ Louvarei com cânticos o nome de Deus; quero exaltá-lo com ações de graças.

[[v19-69-31]]

^<<v19-69-31,31>>^ Isso será muito mais agradável ao Senhor do que um boi ou um novilho com chifres e cascos.

[[v19-69-32]]

^<<v19-69-32,32>>^ Que os aflitos vejam isso e se alegrem; quanto a vocês que buscam a Deus, que o seu coração se reanime.

[[v19-69-33]]

^<<v19-69-33,33>>^ Porque o Senhor ouve os necessitados e não despreza os seus prisioneiros.

[[v19-69-34]]

^<<v19-69-34,34>>^ Louvem-no os céus e a terra, os mares e tudo o que neles se move.

[[v19-69-35]]

^<<v19-69-35,35>>^ Porque Deus salvará Sião e edificará as cidades de Judá; habitarão ali e tomarão posse de Sião.

[[v19-69-36]]

^<<v19-69-36,36>>^ Também a descendência dos seus servos a herdará, e nela habitarão os que amam o nome de Deus.

'''

xref:019-salmos/019-salmos-068.adoc#v19-68-0[&#60; Capítulo Anterior] | <<v19-69-0,Topo>> | xref:019-salmos/019-salmos-070.adoc#v19-70-0[Próximo Capítulo &#62;]