include::./index.adoc[]

[[v19-115-0]]
=== Salmos, 115
// naa ?, NAA - Nova Almeida Atualizada

[[v19-115-1]]

^<<v19-115-1,1>>^ Não a nós, Senhor , não a nós, mas ao teu nome dá glória, por amor da tua misericórdia e da tua fidelidade.

[[v19-115-2]]

^<<v19-115-2,2>>^ Por que diriam as nações: "Onde está o Deus deles?"

[[v19-115-3]]

^<<v19-115-3,3>>^ O nosso Deus está no céu e faz tudo como lhe agrada.

[[v19-115-4]]

^<<v19-115-4,4>>^ Os ídolos das nações são prata e ouro, obra de mãos humanas.

[[v19-115-5]]

^<<v19-115-5,5>>^ Têm boca e não falam; têm olhos e não veem;

[[v19-115-6]]

^<<v19-115-6,6>>^ têm ouvidos e não ouvem; têm nariz e não cheiram;

[[v19-115-7]]

^<<v19-115-7,7>>^ têm mãos e não apalpam; têm pés e não andam; som nenhum lhes sai da garganta.

[[v19-115-8]]

^<<v19-115-8,8>>^ Tornem-se semelhantes a eles os que os fazem e todos os que neles confiam.

[[v19-115-9]]

^<<v19-115-9,9>>^ Ó Israel, confie no Senhor ! Ele é o seu amparo e o seu escudo.

[[v19-115-10]]

^<<v19-115-10,10>>^ Casa de Arão, confie no Senhor ! Ele é o seu amparo e o seu escudo.

[[v19-115-11]]

^<<v19-115-11,11>>^ Vocês que temem o Senhor , confiem no Senhor ! Ele é o seu amparo e o seu escudo.

[[v19-115-12]]

^<<v19-115-12,12>>^ O Senhor  lembrou-se de nós; ele nos abençoará; abençoará a casa de Israel, abençoará a casa de Arão.

[[v19-115-13]]

^<<v19-115-13,13>>^ Ele abençoa os que temem o Senhor , tanto pequenos como grandes.

[[v19-115-14]]

^<<v19-115-14,14>>^ O Senhor  os abençoe mais e mais, a vocês e aos seus filhos.

[[v19-115-15]]

^<<v19-115-15,15>>^ Que vocês sejam abençoados pelo Senhor , que fez os céus e a terra.

[[v19-115-16]]

^<<v19-115-16,16>>^ Os céus são os céus do Senhor , mas a terra ele deu aos filhos dos homens.

[[v19-115-17]]

^<<v19-115-17,17>>^ Os mortos não louvam o Senhor , nem os que descem à região do silêncio podem fazer isso.

[[v19-115-18]]

^<<v19-115-18,18>>^ Nós, porém, bendiremos o Senhor , desde agora e para sempre. Aleluia!

'''

xref:019-salmos/019-salmos-114.adoc#v19-114-0[&#60; Capítulo Anterior] | <<v19-115-0,Topo>> | xref:019-salmos/019-salmos-116.adoc#v19-116-0[Próximo Capítulo &#62;]