include::./index.adoc[]

[[v19-146-0]]
=== Salmos, 146
// naa ?, NAA - Nova Almeida Atualizada

[[v19-146-1]]

^<<v19-146-1,1>>^ Aleluia! Louve, ó minha alma, o Senhor .

[[v19-146-2]]

^<<v19-146-2,2>>^ Louvarei o Senhor durante a minha vida; cantarei louvores ao meu Deus enquanto eu viver.

[[v19-146-3]]

^<<v19-146-3,3>>^ Não confiem em príncipes, nem nos filhos dos homens, em quem não há salvação.

[[v19-146-4]]

^<<v19-146-4,4>>^ Sai-lhes o espírito, e eles voltam ao pó; nesse mesmo dia, acabam todos os seus planos.

[[v19-146-5]]

^<<v19-146-5,5>>^ Bem-aventurado aquele que tem o Deus de Jacó por seu auxílio, cuja esperança está no Senhor , seu Deus,

[[v19-146-6]]

^<<v19-146-6,6>>^ que fez os céus e a terra, o mar e tudo o que neles há e mantém para sempre a sua fidelidade.

[[v19-146-7]]

^<<v19-146-7,7>>^ Que faz justiça aos oprimidos e dá pão aos que têm fome. O Senhor  liberta os encarcerados.

[[v19-146-8]]

^<<v19-146-8,8>>^ O Senhor  abre os olhos aos cegos, o Senhor  levanta os abatidos, o Senhor  ama os justos.

[[v19-146-9]]

^<<v19-146-9,9>>^ O Senhor  guarda o estrangeiro, ampara o órfão e a viúva, porém transtorna o caminho dos ímpios.

[[v19-146-10]]

^<<v19-146-10,10>>^ O Senhor  reina para sempre; o seu Deus, ó Sião, reina de geração em geração. Aleluia!

'''

xref:019-salmos/019-salmos-145.adoc#v19-145-0[&#60; Capítulo Anterior] | <<v19-146-0,Topo>> | xref:019-salmos/019-salmos-147.adoc#v19-147-0[Próximo Capítulo &#62;]