include::./index.adoc[]

[[v19-63-0]]
=== Salmos, 63
// naa ?, NAA - Nova Almeida Atualizada

[[v19-63-1]]

^<<v19-63-1,1>>^ Ó Deus, tu és o meu Deus; eu te busco ansiosamente. A minha alma tem sede de ti; meu corpo te almeja, como terra árida, exausta e sem água.

[[v19-63-2]]

^<<v19-63-2,2>>^ Assim, quero ver-te no santuário, para contemplar a tua força e a tua glória.

[[v19-63-3]]

^<<v19-63-3,3>>^ Porque a tua graça é melhor do que a vida; os meus lábios te louvam.

[[v19-63-4]]

^<<v19-63-4,4>>^ Assim, eu te bendirei enquanto viver; em teu nome, levanto as mãos.

[[v19-63-5]]

^<<v19-63-5,5>>^ Como de saborosa comida se farta a minha alma; e, com júbilo nos lábios, a minha boca te louva,

[[v19-63-6]]

^<<v19-63-6,6>>^ no meu leito, quando de ti me recordo e em ti medito, durante as vigílias da noite.

[[v19-63-7]]

^<<v19-63-7,7>>^ Porque tu tens sido o meu auxílio; à sombra das tuas asas, eu canto de alegria.

[[v19-63-8]]

^<<v19-63-8,8>>^ A minha alma apega-se a ti; a tua mão direita me ampara.

[[v19-63-9]]

^<<v19-63-9,9>>^ Porém os que procuram destruir a minha vida descerão às profundezas da terra.

[[v19-63-10]]

^<<v19-63-10,10>>^ Serão entregues ao poder da espada e virão a ser pasto dos chacais.

[[v19-63-11]]

^<<v19-63-11,11>>^ Mas o rei se alegrará em Deus; quem por ele jura se gloriará, pois se tapará a boca dos que proferem mentira.

'''

xref:019-salmos/019-salmos-062.adoc#v19-62-0[&#60; Capítulo Anterior] | <<v19-63-0,Topo>> | xref:019-salmos/019-salmos-064.adoc#v19-64-0[Próximo Capítulo &#62;]