include::./index.adoc[]

[[v19-33-0]]
=== Salmos, 33
// naa ?, NAA - Nova Almeida Atualizada

[[v19-33-1]]

^<<v19-33-1,1>>^ Exultem no Senhor , ó justos! Aos que são retos fica bem louvá-lo.

[[v19-33-2]]

^<<v19-33-2,2>>^ Louvem o Senhor  com harpa, louvem-no com cânticos na lira de dez cordas.

[[v19-33-3]]

^<<v19-33-3,3>>^ Cantem-lhe um cântico novo, toquem com arte e com júbilo.

[[v19-33-4]]

^<<v19-33-4,4>>^ Porque a palavra do Senhor é reta, e todo o seu proceder é fiel.

[[v19-33-5]]

^<<v19-33-5,5>>^ Ele ama a justiça e o direito; a terra está cheia da bondade do Senhor .

[[v19-33-6]]

^<<v19-33-6,6>>^ Os céus por sua palavra se fizeram, e, pelo sopro de sua boca, o exército deles.

[[v19-33-7]]

^<<v19-33-7,7>>^ Ele ajunta em montão as águas do mar; e em reservatório encerra os abismos.

[[v19-33-8]]

^<<v19-33-8,8>>^ Que toda a terra tema o Senhor , que tremam todos os habitantes do mundo.

[[v19-33-9]]

^<<v19-33-9,9>>^ Pois ele falou, e tudo se fez; ele ordenou, e tudo passou a existir.

[[v19-33-10]]

^<<v19-33-10,10>>^ O Senhor  frustra os planos das nações e anula os intentos dos povos.

[[v19-33-11]]

^<<v19-33-11,11>>^ O plano do Senhor dura para sempre; os intentos do seu coração, por todas as gerações.

[[v19-33-12]]

^<<v19-33-12,12>>^ Feliz a nação cujo Deus é o Senhor , e o povo que ele escolheu para a sua herança.

[[v19-33-13]]

^<<v19-33-13,13>>^ O Senhor  olha dos céus e vê todos os filhos dos homens;

[[v19-33-14]]

^<<v19-33-14,14>>^ do lugar de sua morada, observa todos os moradores da terra,

[[v19-33-15]]

^<<v19-33-15,15>>^ ele, que forma o coração de todos eles, que contempla todas as suas obras.

[[v19-33-16]]

^<<v19-33-16,16>>^ Não há rei que se salve com o poder dos seus exércitos; nem por sua muita força se livra o valente.

[[v19-33-17]]

^<<v19-33-17,17>>^ O cavalo não garante a vitória; apesar de sua grande força, a ninguém pode livrar.

[[v19-33-18]]

^<<v19-33-18,18>>^ Eis que os olhos do Senhor estão sobre os que o temem, sobre os que esperam na sua misericórdia,

[[v19-33-19]]

^<<v19-33-19,19>>^ para livrar a alma deles da morte, e, no tempo da fome, conservar-lhes a vida.

[[v19-33-20]]

^<<v19-33-20,20>>^ Nossa alma espera no Senhor , nosso auxílio e escudo.

[[v19-33-21]]

^<<v19-33-21,21>>^ Nele, o nosso coração se alegra, pois confiamos no seu santo nome.

[[v19-33-22]]

^<<v19-33-22,22>>^ Seja sobre nós, Senhor , a tua misericórdia, como de ti esperamos.

'''

xref:019-salmos/019-salmos-032.adoc#v19-32-0[&#60; Capítulo Anterior] | <<v19-33-0,Topo>> | xref:019-salmos/019-salmos-034.adoc#v19-34-0[Próximo Capítulo &#62;]