include::./index.adoc[]

[[v19-32-0]]
=== Salmos, 32
// naa ?, NAA - Nova Almeida Atualizada

[[v19-32-1]]

^<<v19-32-1,1>>^ Bem-aventurado aquele cuja transgressão é perdoada, cujo pecado é coberto.

[[v19-32-2]]

^<<v19-32-2,2>>^ Bem-aventurado é aquele a quem o Senhor não atribui iniquidade e em cujo espírito não há engano.

[[v19-32-3]]

^<<v19-32-3,3>>^ Enquanto calei os meus pecados, envelheceram os meus ossos pelos meus constantes gemidos todo o dia.

[[v19-32-4]]

^<<v19-32-4,4>>^ Porque a tua mão pesava dia e noite sobre mim, e o meu vigor secou como no calor do verão.

[[v19-32-5]]

^<<v19-32-5,5>>^ Confessei-te o meu pecado e a minha iniquidade não mais ocultei. Eu disse: "Confessarei ao Senhor as minhas transgressões"; e tu perdoaste a iniquidade do meu pecado.

[[v19-32-6]]

^<<v19-32-6,6>>^ Sendo assim, todo o que é piedoso te fará súplicas em tempo de poder te encontrar. Com efeito, quando transbordarem muitas águas, não o atingirão.

[[v19-32-7]]

^<<v19-32-7,7>>^ Tu és o meu esconderijo; tu me preservas da tribulação e me cercas de alegres cantos de livramento.

[[v19-32-8]]

^<<v19-32-8,8>>^ Eu o instruirei e lhe ensinarei o caminho que você deve seguir; e, sob as minhas vistas, lhe darei conselho.

[[v19-32-9]]

^<<v19-32-9,9>>^ Não sejam como o cavalo ou a mula, que não têm entendimento, que são dominados com freios e cabrestos; do contrário não obedecem a você.

[[v19-32-10]]

^<<v19-32-10,10>>^ Muitos são os sofrimentos do ímpio, mas o que confia no Senhor , a misericórdia o cercará.

[[v19-32-11]]

^<<v19-32-11,11>>^ Alegrem-se no Senhor e regozijem-se, ó justos; exultem, todos vocês que são retos de coração.

'''

xref:019-salmos/019-salmos-031.adoc#v19-31-0[&#60; Capítulo Anterior] | <<v19-32-0,Topo>> | xref:019-salmos/019-salmos-033.adoc#v19-33-0[Próximo Capítulo &#62;]