include::./index.adoc[]

[[v19-5-0]]
=== Salmos, 5
// naa ?, NAA - Nova Almeida Atualizada

[[v19-5-1]]

^<<v19-5-1,1>>^ Dá ouvidos, Senhor , às minhas palavras e acode ao meu gemido.

[[v19-5-2]]

^<<v19-5-2,2>>^ Escuta, Rei meu e Deus meu, a minha voz que clama, pois a ti é que imploro.

[[v19-5-3]]

^<<v19-5-3,3>>^ De manhã, Senhor , ouves a minha voz; de manhã te apresento a minha oração e fico esperando.

[[v19-5-4]]

^<<v19-5-4,4>>^ Pois tu não és Deus que se agrade com a iniquidade, e contigo não subsiste o mal.

[[v19-5-5]]

^<<v19-5-5,5>>^ Os arrogantes não permanecerão na tua presença; odeias todos os que praticam a iniquidade.

[[v19-5-6]]

^<<v19-5-6,6>>^ Tu destróis os que proferem mentira; o Senhor  abomina o sanguinário e o fraudulento.

[[v19-5-7]]

^<<v19-5-7,7>>^ Eu, porém, pela riqueza da tua misericórdia, entrarei na tua casa e me prostrarei diante do teu santo templo, no teu temor.

[[v19-5-8]]

^<<v19-5-8,8>>^ Senhor , guia-me na tua justiça, por causa dos meus adversários; endireita diante de mim o teu caminho.

[[v19-5-9]]

^<<v19-5-9,9>>^ Porque na boca dos meus adversários não há sinceridade; o íntimo deles está cheio de crimes; a garganta deles é sepulcro aberto, e com a língua lisonjeiam.

[[v19-5-10]]

^<<v19-5-10,10>>^ Declara-os culpados, ó Deus; que eles caiam por seus próprios planos. Rejeita-os por causa de suas muitas transgressões, pois se rebelaram contra ti.

[[v19-5-11]]

^<<v19-5-11,11>>^ Mas alegrem-se todos os que confiam em ti; cantem de júbilo para sempre, porque tu os defendes; e em ti se gloriem os que amam o teu nome.

[[v19-5-12]]

^<<v19-5-12,12>>^ Pois tu, Senhor , abençoas o justo e, como escudo, o cercas da tua bondade.

'''

xref:019-salmos/019-salmos-004.adoc#v19-4-0[&#60; Capítulo Anterior] | <<v19-5-0,Topo>> | xref:019-salmos/019-salmos-006.adoc#v19-6-0[Próximo Capítulo &#62;]