include::./index.adoc[]

[[v19-53-0]]
=== Salmos, 53
// naa ?, NAA - Nova Almeida Atualizada

[[v19-53-1]]

^<<v19-53-1,1>>^ Diz o insensato no seu coração: "Não há Deus." Corrompem-se e praticam iniquidade; já não há quem faça o bem.

[[v19-53-2]]

^<<v19-53-2,2>>^ Do céu Deus olha para os filhos dos homens, para ver se há quem entenda, se há quem busque a Deus.

[[v19-53-3]]

^<<v19-53-3,3>>^ Todos se desviaram e juntamente se corromperam; não há quem faça o bem, não há nem um sequer.

[[v19-53-4]]

^<<v19-53-4,4>>^ Será que não entendem nada esses que praticam a iniquidade, que devoram o meu povo como se comessem pão e que não invocam a Deus?

[[v19-53-5]]

^<<v19-53-5,5>>^ Ficam tomados de grande pavor, onde não há o que temer; porque Deus dispersa os ossos daqueles que cercam você; você faz com que fiquem envergonhados, porque Deus os rejeita.

[[v19-53-6]]

^<<v19-53-6,6>>^ Quem dera que de Sião viesse já a salvação de Israel! Quando Deus restaurar a sorte do seu povo, Jacó exultará e Israel se encherá de alegria.

'''

xref:019-salmos/019-salmos-052.adoc#v19-52-0[&#60; Capítulo Anterior] | <<v19-53-0,Topo>> | xref:019-salmos/019-salmos-054.adoc#v19-54-0[Próximo Capítulo &#62;]