include::./index.adoc[]

[[v19-76-0]]
=== Salmos, 76
// naa ?, NAA - Nova Almeida Atualizada

[[v19-76-1]]

^<<v19-76-1,1>>^ Deus é conhecido em Judá; grande é o seu nome em Israel.

[[v19-76-2]]

^<<v19-76-2,2>>^ Em Salém está o seu tabernáculo, e, em Sião, a sua morada.

[[v19-76-3]]

^<<v19-76-3,3>>^ Ali, despedaçou ele as flechas, o escudo, a espada e a batalha.

[[v19-76-4]]

^<<v19-76-4,4>>^ Tu és ilustre e mais glorioso do que os montes eternos.

[[v19-76-5]]

^<<v19-76-5,5>>^ Os corajosos foram despojados; jazem a dormir o seu sono, e nenhum dos valentes pode valer-se das próprias mãos.

[[v19-76-6]]

^<<v19-76-6,6>>^ Ante a tua repreensão, ó Deus de Jacó, carros de guerra e cavalos foram lançados num sono profundo.

[[v19-76-7]]

^<<v19-76-7,7>>^ Tu, sim, tu és terrível; se estás irado, quem pode permanecer na tua presença?

[[v19-76-8]]

^<<v19-76-8,8>>^ Desde os céus fizeste ouvir o teu juízo; a terra tremeu e se aquietou,

[[v19-76-9]]

^<<v19-76-9,9>>^ quando Deus se levantou para julgar e salvar todos os humildes da terra.

[[v19-76-10]]

^<<v19-76-10,10>>^ Pois até a ira humana há de louvar-te; e da ira restante te cingirás.

[[v19-76-11]]

^<<v19-76-11,11>>^ Façam votos ao Senhor , seu Deus, e tratem de cumpri-los; todos os que o rodeiam tragam presentes àquele que deve ser temido.

[[v19-76-12]]

^<<v19-76-12,12>>^ Ele acaba com o orgulho dos príncipes; ele é tremendo para os reis da terra.

'''

xref:019-salmos/019-salmos-075.adoc#v19-75-0[&#60; Capítulo Anterior] | <<v19-76-0,Topo>> | xref:019-salmos/019-salmos-077.adoc#v19-77-0[Próximo Capítulo &#62;]