include::./index.adoc[]

[[v19-25-0]]
=== Salmos, 25
// naa ?, NAA - Nova Almeida Atualizada

[[v19-25-1]]

^<<v19-25-1,1>>^ A ti, Senhor , elevo a minha alma.

[[v19-25-2]]

^<<v19-25-2,2>>^ Deus meu, em ti confio. Não seja eu envergonhado, nem exultem sobre mim os meus inimigos.

[[v19-25-3]]

^<<v19-25-3,3>>^ Na verdade, dos que em ti esperam, ninguém será envergonhado; envergonhados serão os que, sem motivo, procedem traiçoeiramente.

[[v19-25-4]]

^<<v19-25-4,4>>^ Faze-me conhecer os teus caminhos, Senhor ; ensina-me as tuas veredas.

[[v19-25-5]]

^<<v19-25-5,5>>^ Guia-me na tua verdade e ensina-me, pois tu és o Deus da minha salvação, em quem eu espero todo o dia.

[[v19-25-6]]

^<<v19-25-6,6>>^ Lembra-te, Senhor , das tuas misericórdias e das tuas bondades, que são desde a eternidade.

[[v19-25-7]]

^<<v19-25-7,7>>^ Não te lembres dos meus pecados da mocidade, nem das minhas transgressões. Lembra-te de mim, segundo a tua misericórdia, por causa da tua bondade, ó Senhor .

[[v19-25-8]]

^<<v19-25-8,8>>^ Bom e reto é o Senhor , por isso aponta o caminho aos pecadores.

[[v19-25-9]]

^<<v19-25-9,9>>^ Guia os humildes na justiça e ensina aos mansos o seu caminho.

[[v19-25-10]]

^<<v19-25-10,10>>^ Todas as veredas do Senhor são misericórdia e verdade para os que guardam a sua aliança e os seus testemunhos.

[[v19-25-11]]

^<<v19-25-11,11>>^ Por causa do teu nome, Senhor , perdoa a minha iniquidade, que é grande.

[[v19-25-12]]

^<<v19-25-12,12>>^ Àquele que teme o Senhor , ele o instruirá no caminho que deve escolher.

[[v19-25-13]]

^<<v19-25-13,13>>^ Na prosperidade repousará a sua alma, e a sua descendência herdará a terra.

[[v19-25-14]]

^<<v19-25-14,14>>^ O Senhor  confia o seu segredo aos que o temem, aos quais ele dará a conhecer a sua aliança.

[[v19-25-15]]

^<<v19-25-15,15>>^ Os meus olhos se elevam continuamente ao Senhor , pois ele tirará os meus pés do laço.

[[v19-25-16]]

^<<v19-25-16,16>>^ Volta-te para mim e tem compaixão, porque estou sozinho e aflito.

[[v19-25-17]]

^<<v19-25-17,17>>^ Alivia-me as tribulações do coração; tira-me das minhas angústias.

[[v19-25-18]]

^<<v19-25-18,18>>^ Considera as minhas aflições e o meu sofrimento e perdoa todos os meus pecados.

[[v19-25-19]]

^<<v19-25-19,19>>^ Considera os meus inimigos, pois são muitos e têm por mim um ódio mortal.

[[v19-25-20]]

^<<v19-25-20,20>>^ Guarda a minha alma e livra-me; não seja eu envergonhado, pois em ti me refugio.

[[v19-25-21]]

^<<v19-25-21,21>>^ Que a sinceridade e a retidão me preservem, porque em ti espero.

[[v19-25-22]]

^<<v19-25-22,22>>^ Ó Deus, redime Israel de todas as suas tribulações.

'''

xref:019-salmos/019-salmos-024.adoc#v19-24-0[&#60; Capítulo Anterior] | <<v19-25-0,Topo>> | xref:019-salmos/019-salmos-026.adoc#v19-26-0[Próximo Capítulo &#62;]