include::./index.adoc[]

[[v19-38-0]]
=== Salmos, 38
// naa ?, NAA - Nova Almeida Atualizada

[[v19-38-1]]

^<<v19-38-1,1>>^ Não me repreendas, Senhor , na tua ira, nem me castigues no teu furor.

[[v19-38-2]]

^<<v19-38-2,2>>^ Cravam-se em mim as tuas setas, e a tua mão recai sobre mim.

[[v19-38-3]]

^<<v19-38-3,3>>^ Não há parte sã na minha carne, por causa da tua indignação; não há saúde nos meus ossos, por causa do meu pecado.

[[v19-38-4]]

^<<v19-38-4,4>>^ Pois já se elevam acima de minha cabeça as minhas iniquidades; como fardos pesados, excedem as minhas forças.

[[v19-38-5]]

^<<v19-38-5,5>>^ Tenho feridas que cheiram mal e estão cheias de pus, por causa da minha insensatez.

[[v19-38-6]]

^<<v19-38-6,6>>^ Sinto-me encurvado e muito abatido, ando de luto o dia todo.

[[v19-38-7]]

^<<v19-38-7,7>>^ Os meus lombos ardem, e não há parte sã na minha carne.

[[v19-38-8]]

^<<v19-38-8,8>>^ Estou aflito e mui quebrantado; dou gemidos por causa do desassossego do meu coração.

[[v19-38-9]]

^<<v19-38-9,9>>^ Na tua presença, Senhor, estão os meus desejos todos, e a minha ansiedade não te é oculta.

[[v19-38-10]]

^<<v19-38-10,10>>^ O meu coração bate acelerado, faltam-me as forças, e a luz dos meus olhos, até essa me deixou!

[[v19-38-11]]

^<<v19-38-11,11>>^ Os meus amigos e companheiros afastam-se da minha desgraça, e os meus parentes ficam de longe.

[[v19-38-12]]

^<<v19-38-12,12>>^ Armam ciladas contra mim os que tramam tirar-me a vida; os que me procuram fazer o mal dizem coisas perniciosas e imaginam engano todo o dia.

[[v19-38-13]]

^<<v19-38-13,13>>^ Mas eu, como surdo, não ouço e, qual mudo, não abro a boca.

[[v19-38-14]]

^<<v19-38-14,14>>^ Sou como quem não ouve e em cujos lábios não há réplica.

[[v19-38-15]]

^<<v19-38-15,15>>^ Pois em ti, Senhor , espero; tu me responderás, Senhor, Deus meu.

[[v19-38-16]]

^<<v19-38-16,16>>^ Porque eu dizia: "Não deixes que eles se alegrem de mim e contra mim se engrandeçam quando me resvala o pé."

[[v19-38-17]]

^<<v19-38-17,17>>^ Pois estou prestes a tropeçar; a minha dor está sempre diante de mim.

[[v19-38-18]]

^<<v19-38-18,18>>^ Confesso a minha iniquidade; suporto tristeza por causa do meu pecado.

[[v19-38-19]]

^<<v19-38-19,19>>^ Mas os meus inimigos são vigorosos e fortes, e são muitos os que sem motivo me odeiam.

[[v19-38-20]]

^<<v19-38-20,20>>^ Aqueles que pagam o mal pelo bem são meus adversários, porque eu sigo o que é bom.

[[v19-38-21]]

^<<v19-38-21,21>>^ Não me desampares, Senhor ; Deus meu, não te ausentes de mim.

[[v19-38-22]]

^<<v19-38-22,22>>^ Apressa-te em socorrer-me, Senhor, salvação minha.

'''

xref:019-salmos/019-salmos-037.adoc#v19-37-0[&#60; Capítulo Anterior] | <<v19-38-0,Topo>> | xref:019-salmos/019-salmos-039.adoc#v19-39-0[Próximo Capítulo &#62;]