include::./index.adoc[]

[[v19-74-0]]
=== Salmos, 74
// naa ?, NAA - Nova Almeida Atualizada

[[v19-74-1]]

^<<v19-74-1,1>>^ Ó Deus, por que nos rejeitas para sempre? Por que se acende a tua ira contra as ovelhas do teu pasto?

[[v19-74-2]]

^<<v19-74-2,2>>^ Lembra-te da tua congregação, que adquiriste desde a antiguidade, que remiste para ser a tribo da tua herança. Lembra-te do monte Sião, no qual tens habitado.

[[v19-74-3]]

^<<v19-74-3,3>>^ Dirige os teus passos para as ruínas perpétuas, para tudo de mau que o inimigo fez no santuário.

[[v19-74-4]]

^<<v19-74-4,4>>^ Os teus adversários bramam no lugar das assembleias e erguem as suas próprias insígnias como sinais.

[[v19-74-5]]

^<<v19-74-5,5>>^ Parecem-se com os que empunham os seus machados no espesso da floresta;

[[v19-74-6]]

^<<v19-74-6,6>>^ e agora, com os seus machados e martelos, destroem todos os entalhes de madeira.

[[v19-74-7]]

^<<v19-74-7,7>>^ Incendeiam o teu santuário; profanam a morada do teu nome, arrasando-a até o chão.

[[v19-74-8]]

^<<v19-74-8,8>>^ Disseram no seu coração: "Acabemos com eles de uma vez." Queimaram todos os lugares santos de Deus na terra.

[[v19-74-9]]

^<<v19-74-9,9>>^ Já não vemos os nossos sinais; já não há profeta; nem há, entre nós, quem saiba até quando isso vai durar.

[[v19-74-10]]

^<<v19-74-10,10>>^ Até quando, ó Deus, o adversário nos afrontará? Será que o inimigo blasfemará o teu nome para sempre?

[[v19-74-11]]

^<<v19-74-11,11>>^ Por que retiras a tua mão, sim, a tua mão direita, e a conservas no teu seio?

[[v19-74-12]]

^<<v19-74-12,12>>^ Mas Deus é meu Rei desde a antiguidade; ele é quem opera feitos salvadores no meio da terra.

[[v19-74-13]]

^<<v19-74-13,13>>^ Tu, com o teu poder, dividiste o mar; esmagaste sobre as águas a cabeça dos monstros marinhos.

[[v19-74-14]]

^<<v19-74-14,14>>^ Despedaçaste as cabeças do Leviatã e o deste por alimento às criaturas do deserto.

[[v19-74-15]]

^<<v19-74-15,15>>^ Tu abriste fontes e ribeiros; secaste rios caudalosos.

[[v19-74-16]]

^<<v19-74-16,16>>^ Teu é o dia; tua também é a noite; a luz e o sol, tu os formaste.

[[v19-74-17]]

^<<v19-74-17,17>>^ Fixaste os confins da terra; verão e inverno, tu os fizeste.

[[v19-74-18]]

^<<v19-74-18,18>>^ Lembra-te disto: o inimigo tem insultado o Senhor , e um povo insensato tem blasfemado o teu nome.

[[v19-74-19]]

^<<v19-74-19,19>>^ Não entregues à rapina a vida de tua pomba, nem te esqueças para sempre da vida dos teus aflitos.

[[v19-74-20]]

^<<v19-74-20,20>>^ Lembra-te da tua aliança, pois os lugares tenebrosos da terra estão cheios de moradas de violência.

[[v19-74-21]]

^<<v19-74-21,21>>^ Não fique envergonhado o oprimido; que o aflito e o necessitado louvem o teu nome.

[[v19-74-22]]

^<<v19-74-22,22>>^ Levanta-te, ó Deus, e defende a tua causa; lembra-te de como o ímpio te afronta todos os dias.

[[v19-74-23]]

^<<v19-74-23,23>>^ Não te esqueças da gritaria dos teus inimigos, do sempre crescente tumulto dos teus adversários.

'''

xref:019-salmos/019-salmos-073.adoc#v19-73-0[&#60; Capítulo Anterior] | <<v19-74-0,Topo>> | xref:019-salmos/019-salmos-075.adoc#v19-75-0[Próximo Capítulo &#62;]