include::./index.adoc[]

[[v19-55-0]]
=== Salmos, 55
// naa ?, NAA - Nova Almeida Atualizada

[[v19-55-1]]

^<<v19-55-1,1>>^ Dá ouvidos, ó Deus, à minha oração; não te escondas da minha súplica.

[[v19-55-2]]

^<<v19-55-2,2>>^ Atende-me e responde-me; sinto-me perplexo em minha queixa e ando perturbado,

[[v19-55-3]]

^<<v19-55-3,3>>^ por causa do clamor do inimigo e da opressão do ímpio; pois sobre mim lançam calamidade e furiosamente me hostilizam.

[[v19-55-4]]

^<<v19-55-4,4>>^ O meu coração estremece no peito, terrores de morte caem sobre mim.

[[v19-55-5]]

^<<v19-55-5,5>>^ Temor e tremor me sobrevêm, e o horror se apodera de mim.

[[v19-55-6]]

^<<v19-55-6,6>>^ Então eu disse: Quem me dera ter asas como a pomba! Voaria e acharia descanso.

[[v19-55-7]]

^<<v19-55-7,7>>^ Eis que fugiria para longe e ficaria no deserto.

[[v19-55-8]]

^<<v19-55-8,8>>^ Depressa eu me abrigaria do vendaval e da tempestade.

[[v19-55-9]]

^<<v19-55-9,9>>^ Destrói, Senhor, e confunde os seus conselhos, porque vejo violência e conflitos na cidade.

[[v19-55-10]]

^<<v19-55-10,10>>^ Dia e noite andam em volta dela, nas suas muralhas, e, dentro delas, reinam a corrupção e a maldade.

[[v19-55-11]]

^<<v19-55-11,11>>^ Há destruição no meio da cidade; das suas praças não se afastam a opressão e o engano.

[[v19-55-12]]

^<<v19-55-12,12>>^ Porque não é um inimigo que me afronta; se o fosse, eu o suportaria; nem é o que me odeia quem se exalta contra mim, pois dele eu me esconderia;

[[v19-55-13]]

^<<v19-55-13,13>>^ mas é você, homem meu igual, meu companheiro e meu íntimo amigo.

[[v19-55-14]]

^<<v19-55-14,14>>^ Juntos nos entretínhamos e íamos com a multidão à Casa de Deus.

[[v19-55-15]]

^<<v19-55-15,15>>^ Que a morte os assalte, e vivos desçam à sepultura! Porque há maldade nas suas moradas e no seu íntimo.

[[v19-55-16]]

^<<v19-55-16,16>>^ Eu, porém, invocarei a Deus, e o Senhor  me salvará.

[[v19-55-17]]

^<<v19-55-17,17>>^ À tarde, pela manhã e ao meio-dia, farei as minhas queixas e lamentarei; e ele ouvirá a minha voz.

[[v19-55-18]]

^<<v19-55-18,18>>^ Em paz ele livra a minha alma dos que me perseguem; pois são muitos contra mim.

[[v19-55-19]]

^<<v19-55-19,19>>^ Deus ouvirá e lhes responderá, ele, que preside desde a eternidade, porque não há neles mudança nenhuma, e não temem a Deus.

[[v19-55-20]]

^<<v19-55-20,20>>^ Tal homem estendeu as mãos contra os que tinham paz com ele; violou a sua aliança.

[[v19-55-21]]

^<<v19-55-21,21>>^ A sua fala era mais macia que a manteiga, porém no coração havia guerra; as suas palavras eram mais suaves que o azeite, mas eram, de fato, espadas afiadas.

[[v19-55-22]]

^<<v19-55-22,22>>^ Lance os seus cuidados sobre o Senhor e ele o susterá; jamais permitirá que o justo seja abalado.

[[v19-55-23]]

^<<v19-55-23,23>>^ Tu, porém, ó Deus, os lançarás na cova profunda. Homens sanguinários e fraudulentos não chegarão à metade dos seus dias; eu, todavia, confiarei em ti.

'''

xref:019-salmos/019-salmos-054.adoc#v19-54-0[&#60; Capítulo Anterior] | <<v19-55-0,Topo>> | xref:019-salmos/019-salmos-056.adoc#v19-56-0[Próximo Capítulo &#62;]