include::./index.adoc[]

[[v19-24-0]]
=== Salmos, 24
// naa ?, NAA - Nova Almeida Atualizada

[[v19-24-1]]

^<<v19-24-1,1>>^ Ao Senhor  pertence a terra e a sua plenitude, o mundo e os que nele habitam.

[[v19-24-2]]

^<<v19-24-2,2>>^ Porque ele fundou-a sobre os mares e sobre as correntes a estabeleceu.

[[v19-24-3]]

^<<v19-24-3,3>>^ Quem subirá ao monte do Senhor ? Quem há de permanecer no seu santo lugar?

[[v19-24-4]]

^<<v19-24-4,4>>^ O que é limpo de mãos e puro de coração, que não entrega a sua alma à falsidade, nem faz juramentos com a intenção de enganar.

[[v19-24-5]]

^<<v19-24-5,5>>^ Este receberá do Senhor a bênção e a justiça do Deus da sua salvação.

[[v19-24-6]]

^<<v19-24-6,6>>^ Esta é a geração dos que o buscam, dos que buscam a face do Deus de Jacó.

[[v19-24-7]]

^<<v19-24-7,7>>^ Levantem as suas cabeças, ó portas! Levantem-se, ó portais eternos, para que entre o Rei da glória.

[[v19-24-8]]

^<<v19-24-8,8>>^ Quem é o Rei da glória? O Senhor , forte e poderoso, o Senhor , poderoso nas batalhas.

[[v19-24-9]]

^<<v19-24-9,9>>^ Levantem as suas cabeças, ó portas! Levantem-se, ó portais eternos, para que entre o Rei da glória.

[[v19-24-10]]

^<<v19-24-10,10>>^ Quem é esse Rei da glória? O Senhor  dos Exércitos, ele é o Rei da glória.

'''

xref:019-salmos/019-salmos-023.adoc#v19-23-0[&#60; Capítulo Anterior] | <<v19-24-0,Topo>> | xref:019-salmos/019-salmos-025.adoc#v19-25-0[Próximo Capítulo &#62;]