include::./index.adoc[]

[[v19-57-0]]
=== Salmos, 57
// naa ?, NAA - Nova Almeida Atualizada

[[v19-57-1]]

^<<v19-57-1,1>>^ Tem misericórdia de mim, ó Deus, tem misericórdia, pois em ti a minha alma se refugia; à sombra das tuas asas me abrigo, até que passem as calamidades.

[[v19-57-2]]

^<<v19-57-2,2>>^ Clamarei ao Deus Altíssimo, ao Deus que por mim tudo executa.

[[v19-57-3]]

^<<v19-57-3,3>>^ Dos céus ele me envia o seu auxílio e me livra; cobre de vergonha os que procuram me destruir. Envia a sua misericórdia e a sua fidelidade.

[[v19-57-4]]

^<<v19-57-4,4>>^ A minha alma está rodeada de leões, ávidos por devorar os filhos dos homens; lanças e flechas são os seus dentes, espada afiada é a língua deles.

[[v19-57-5]]

^<<v19-57-5,5>>^ Sê exaltado, ó Deus, acima dos céus; e em toda a terra brilhe a tua glória.

[[v19-57-6]]

^<<v19-57-6,6>>^ Armaram uma rede aos meus passos, a minha alma está abatida. Abriram uma cova diante de mim, mas eles mesmos caíram nela.

[[v19-57-7]]

^<<v19-57-7,7>>^ Firme está o meu coração, ó Deus, o meu coração está firme; cantarei e entoarei louvores.

[[v19-57-8]]

^<<v19-57-8,8>>^ Acorde, ó minha alma! Acordem, lira e harpa! Quero acordar o alvorecer.

[[v19-57-9]]

^<<v19-57-9,9>>^ Eu te darei graças entre os povos; cantarei louvores a ti entre as nações.

[[v19-57-10]]

^<<v19-57-10,10>>^ Pois a tua misericórdia se eleva até os céus, e a tua fidelidade, até as nuvens.

[[v19-57-11]]

^<<v19-57-11,11>>^ Sê exaltado, ó Deus, acima dos céus; e em toda a terra brilhe a tua glória.

'''

xref:019-salmos/019-salmos-056.adoc#v19-56-0[&#60; Capítulo Anterior] | <<v19-57-0,Topo>> | xref:019-salmos/019-salmos-058.adoc#v19-58-0[Próximo Capítulo &#62;]