include::./index.adoc[]

[[v19-2-0]]
=== Salmos, 2
// naa ?, NAA - Nova Almeida Atualizada

[[v19-2-1]]

^<<v19-2-1,1>>^ Por que se enfurecem as nações e os povos imaginam coisas vãs?

[[v19-2-2]]

^<<v19-2-2,2>>^ Os reis da terra se levantam, e as autoridades conspiram contra o Senhor  e contra o seu Ungido, dizendo:

[[v19-2-3]]

^<<v19-2-3,3>>^ "Vamos romper os seus laços e sacudir de nós as suas algemas."

[[v19-2-4]]

^<<v19-2-4,4>>^ Aquele que habita nos céus dá risada; o Senhor zomba deles.

[[v19-2-5]]

^<<v19-2-5,5>>^ Na sua ira, a seu tempo, lhes falará e no seu furor os deixará apavorados, dizendo:

[[v19-2-6]]

^<<v19-2-6,6>>^ "Eu constituí o meu Rei sobre o meu santo monte Sião."

[[v19-2-7]]

^<<v19-2-7,7>>^ O rei diz: "Proclamarei o decreto do Senhor . Ele me disse: ‘Você é meu Filho, hoje eu gerei você.

[[v19-2-8]]

^<<v19-2-8,8>>^ Peça, e eu lhe darei as nações por herança e as extremidades da terra por sua possessão.

[[v19-2-9]]

^<<v19-2-9,9>>^ Com uma vara de ferro você as quebrará e as despedaçará como um vaso de oleiro.’"

[[v19-2-10]]

^<<v19-2-10,10>>^ Agora, pois, ó reis, sejam prudentes; deixem-se advertir, juízes da terra.

[[v19-2-11]]

^<<v19-2-11,11>>^ Sirvam o Senhor  com temor e alegrem-se nele com tremor.

[[v19-2-12]]

^<<v19-2-12,12>>^ Beijem o Filho para que não se irrite, e não pereçam no caminho; porque em breve se acenderá a sua ira. Bem-aventurados todos os que nele se refugiam.

'''

xref:019-salmos/019-salmos-001.adoc#v19-1-0[&#60; Capítulo Anterior] | <<v19-2-0,Topo>> | xref:019-salmos/019-salmos-003.adoc#v19-3-0[Próximo Capítulo &#62;]