include::./index.adoc[]

[[v19-132-0]]
=== Salmos, 132
// naa ?, NAA - Nova Almeida Atualizada

[[v19-132-1]]

^<<v19-132-1,1>>^ Lembra-te, Senhor , de Davi e de todas as suas provações.

[[v19-132-2]]

^<<v19-132-2,2>>^ Lembra-te de como ele jurou ao Senhor e fez votos ao Poderoso de Jacó, dizendo:

[[v19-132-3]]

^<<v19-132-3,3>>^ "Não entrarei na tenda em que moro, nem me deitarei no leito em que repouso;

[[v19-132-4]]

^<<v19-132-4,4>>^ não darei sono aos meus olhos, nem repouso às minhas pálpebras,

[[v19-132-5]]

^<<v19-132-5,5>>^ enquanto eu não encontrar um lugar para o Senhor , uma morada para o Poderoso de Jacó."

[[v19-132-6]]

^<<v19-132-6,6>>^ Ouvimos dizer que a arca estava em Efrata e a encontramos no campo de Jaar.

[[v19-132-7]]

^<<v19-132-7,7>>^ Entremos na sua morada, adoremos diante do estrado de seus pés.

[[v19-132-8]]

^<<v19-132-8,8>>^ Levanta-te, Senhor , e entra no lugar do teu repouso, tu e a arca do teu poder.

[[v19-132-9]]

^<<v19-132-9,9>>^ Vistam-se de justiça os teus sacerdotes, e exultem os teus fiéis.

[[v19-132-10]]

^<<v19-132-10,10>>^ Por amor de Davi, teu servo, não rejeites o teu ungido.

[[v19-132-11]]

^<<v19-132-11,11>>^ O Senhor  jurou a Davi com firme juramento e dele não se desviará: "Farei com que no seu trono se assente um dos seus descendentes.

[[v19-132-12]]

^<<v19-132-12,12>>^ Se os filhos de você guardarem a minha aliança e o testemunho que eu lhes ensinar, também os filhos deles se assentarão para sempre no seu trono."

[[v19-132-13]]

^<<v19-132-13,13>>^ Pois o Senhor  escolheu Sião, preferiu-a por sua morada, dizendo:

[[v19-132-14]]

^<<v19-132-14,14>>^ "Este é para sempre o lugar do meu repouso; aqui habitarei, pois este é o meu desejo.

[[v19-132-15]]

^<<v19-132-15,15>>^ Abençoarei com abundância o seu mantimento e de pão fartarei os seus pobres.

[[v19-132-16]]

^<<v19-132-16,16>>^ Vestirei de salvação os seus sacerdotes, e de júbilo exultarão os seus fiéis.

[[v19-132-17]]

^<<v19-132-17,17>>^ Ali, farei brotar o poder de Davi; preparei uma lâmpada para o meu ungido.

[[v19-132-18]]

^<<v19-132-18,18>>^ Cobrirei de vexame os seus inimigos, mas sobre ele brilhará a sua coroa."

'''

xref:019-salmos/019-salmos-131.adoc#v19-131-0[&#60; Capítulo Anterior] | <<v19-132-0,Topo>> | xref:019-salmos/019-salmos-133.adoc#v19-133-0[Próximo Capítulo &#62;]