include::./index.adoc[]

[[v19-83-0]]
=== Salmos, 83
// naa ?, NAA - Nova Almeida Atualizada

[[v19-83-1]]

^<<v19-83-1,1>>^ Ó Deus, não te cales! Não te emudeças, nem fiques inativo, ó Deus!

[[v19-83-2]]

^<<v19-83-2,2>>^ Os teus inimigos se alvoroçam, e os que te odeiam levantam a cabeça.

[[v19-83-3]]

^<<v19-83-3,3>>^ Tramam astutamente contra o teu povo e conspiram contra os teus protegidos.

[[v19-83-4]]

^<<v19-83-4,4>>^ Eles dizem: "Venham, vamos riscá-los da lista dos povos! E que ninguém mais se lembre do nome de Israel!"

[[v19-83-5]]

^<<v19-83-5,5>>^ Pois tramam de comum acordo e firmam aliança contra ti.

[[v19-83-6]]

^<<v19-83-6,6>>^ São as tendas de Edom e os ismaelitas, Moabe e os hagarenos,

[[v19-83-7]]

^<<v19-83-7,7>>^ Gebal, Amom e Amaleque, a Filístia com os habitantes de Tiro.

[[v19-83-8]]

^<<v19-83-8,8>>^ Também a Assíria se alia com eles, e se constituem braço forte aos filhos de Ló.

[[v19-83-9]]

^<<v19-83-9,9>>^ Faze com eles como fizeste com Midiã, como fizeste com Sísera e com Jabim no ribeiro de Quisom;

[[v19-83-10]]

^<<v19-83-10,10>>^ eles foram destruídos em En-Dor e se tornaram adubo para a terra.

[[v19-83-11]]

^<<v19-83-11,11>>^ Sejam os seus nobres como Orebe e como Zeebe, e os seus príncipes, como Zeba e como Salmuna,

[[v19-83-12]]

^<<v19-83-12,12>>^ que disseram: "Vamos nos apoderar das habitações de Deus."

[[v19-83-13]]

^<<v19-83-13,13>>^ Deus meu, faze-os como folhas impelidas por um redemoinho, como a palha que o vento leva.

[[v19-83-14]]

^<<v19-83-14,14>>^ Como o fogo devora um bosque e as chamas incendeiam os montes,

[[v19-83-15]]

^<<v19-83-15,15>>^ assim persegue-os com a tua tempestade e amedronta-os com o teu vendaval.

[[v19-83-16]]

^<<v19-83-16,16>>^ Cobre o rosto deles de vergonha, para que busquem o teu nome, Senhor .

[[v19-83-17]]

^<<v19-83-17,17>>^ Sejam envergonhados e confundidos para sempre; que pereçam em completa desgraça.

[[v19-83-18]]

^<<v19-83-18,18>>^ Então reconhecerão que só tu, cujo nome é Senhor , és o Altíssimo sobre toda a terra.

'''

xref:019-salmos/019-salmos-082.adoc#v19-82-0[&#60; Capítulo Anterior] | <<v19-83-0,Topo>> | xref:019-salmos/019-salmos-084.adoc#v19-84-0[Próximo Capítulo &#62;]