include::./index.adoc[]

[[v19-12-0]]
=== Salmos, 12
// naa ?, NAA - Nova Almeida Atualizada

[[v19-12-1]]

^<<v19-12-1,1>>^ Salva-nos, Senhor ! Porque já não há quem seja piedoso; desaparecem os fiéis entre os filhos dos homens.

[[v19-12-2]]

^<<v19-12-2,2>>^ Falam com falsidade uns aos outros, falam com lábios bajuladores e coração fingido.

[[v19-12-3]]

^<<v19-12-3,3>>^ Que o Senhor  corte todos os lábios bajuladores e a língua que fala soberbamente.

[[v19-12-4]]

^<<v19-12-4,4>>^ Pois dizem: "Com a nossa língua prevaleceremos; os lábios são nossos; quem é senhor sobre nós?"

[[v19-12-5]]

^<<v19-12-5,5>>^ "Por causa da opressão dos pobres e do gemido dos necessitados, eu me levantarei agora", diz o Senhor , "e porei a salvo aquele que anseia por isso."

[[v19-12-6]]

^<<v19-12-6,6>>^ As palavras do Senhor são palavras puras, prata refinada em forno de barro, depurada sete vezes.

[[v19-12-7]]

^<<v19-12-7,7>>^ Sim, Senhor , tu nos guardarás; tu nos livrarás desta geração para sempre.

[[v19-12-8]]

^<<v19-12-8,8>>^ Os perversos andam por toda parte, quando aquilo que não presta é exaltado entre os filhos dos homens.

'''

xref:019-salmos/019-salmos-011.adoc#v19-11-0[&#60; Capítulo Anterior] | <<v19-12-0,Topo>> | xref:019-salmos/019-salmos-013.adoc#v19-13-0[Próximo Capítulo &#62;]