include::./index.adoc[]

[[v19-66-0]]
=== Salmos, 66
// naa ?, NAA - Nova Almeida Atualizada

[[v19-66-1]]

^<<v19-66-1,1>>^ Aclamem a Deus, todas as terras!

[[v19-66-2]]

^<<v19-66-2,2>>^ Cantem louvores à glória do seu nome, deem glória ao seu louvor.

[[v19-66-3]]

^<<v19-66-3,3>>^ Digam isto a Deus: "Que tremendos são os teus feitos! Pela grandeza do teu poder, a ti se mostram submissos os teus inimigos.

[[v19-66-4]]

^<<v19-66-4,4>>^ Toda a terra se prostra diante de ti, e canta louvores a ti; canta louvores ao teu nome."

[[v19-66-5]]

^<<v19-66-5,5>>^ Venham e vejam as obras de Deus: tremendos feitos para com os filhos dos homens!

[[v19-66-6]]

^<<v19-66-6,6>>^ Transformou o mar em terra seca; eles atravessaram o rio a pé; ali, nos alegramos nele.

[[v19-66-7]]

^<<v19-66-7,7>>^ Ele, em seu poder, governa eternamente; os seus olhos vigiam as nações. Não se exaltem os rebeldes!

[[v19-66-8]]

^<<v19-66-8,8>>^ Bendigam, ó povos, o nosso Deus; façam ouvir a voz do seu louvor.

[[v19-66-9]]

^<<v19-66-9,9>>^ É ele quem preserva com vida a nossa alma e não permite que resvalem os nossos pés.

[[v19-66-10]]

^<<v19-66-10,10>>^ Pois tu, ó Deus, nos provaste; tu nos refinaste como se faz com a prata.

[[v19-66-11]]

^<<v19-66-11,11>>^ Tu nos deixaste cair na armadilha; puseste uma pesada carga nas nossas costas;

[[v19-66-12]]

^<<v19-66-12,12>>^ fizeste com que os nossos inimigos cavalgassem sobre a nossa cabeça; passamos pelo fogo e pela água; porém, afinal, nos trouxeste para um lugar espaçoso.

[[v19-66-13]]

^<<v19-66-13,13>>^ Entrarei na tua casa com holocaustos; a ti pagarei os meus votos,

[[v19-66-14]]

^<<v19-66-14,14>>^ que os meus lábios fizeram, e que, no dia da angústia, a minha boca prometeu.

[[v19-66-15]]

^<<v19-66-15,15>>^ Oferecerei a ti holocaustos de animais gordos, com aroma de carneiros; oferecerei novilhos e cabritos.

[[v19-66-16]]

^<<v19-66-16,16>>^ Venham e escutem, todos vocês que temem a Deus, e eu contarei o que ele tem feito por minha alma.

[[v19-66-17]]

^<<v19-66-17,17>>^ A ele clamei com a boca; com a língua o exaltei.

[[v19-66-18]]

^<<v19-66-18,18>>^ Se, no coração, eu tivesse contemplado iniquidade, o Senhor não teria me ouvido.

[[v19-66-19]]

^<<v19-66-19,19>>^ Entretanto, Deus me ouviu e atendeu a voz da minha oração.

[[v19-66-20]]

^<<v19-66-20,20>>^ Bendito seja Deus, que não rejeitou a minha oração, nem afastou de mim a sua graça.

'''

xref:019-salmos/019-salmos-065.adoc#v19-65-0[&#60; Capítulo Anterior] | <<v19-66-0,Topo>> | xref:019-salmos/019-salmos-067.adoc#v19-67-0[Próximo Capítulo &#62;]