include::./index.adoc[]

[[v19-116-0]]
=== Salmos, 116
// naa ?, NAA - Nova Almeida Atualizada

[[v19-116-1]]

^<<v19-116-1,1>>^ Amo o Senhor , porque ele ouve a minha voz e as minhas súplicas.

[[v19-116-2]]

^<<v19-116-2,2>>^ Porque inclinou para mim os seus ouvidos, eu o invocarei por toda a minha vida.

[[v19-116-3]]

^<<v19-116-3,3>>^ Laços de morte me cercaram, e angústias do inferno se apoderaram de mim; fiquei aflito e triste.

[[v19-116-4]]

^<<v19-116-4,4>>^ Então invoquei o nome do Senhor : "Ó Senhor , livra a minha alma."

[[v19-116-5]]

^<<v19-116-5,5>>^ Compassivo e justo é o Senhor ; o nosso Deus é misericordioso.

[[v19-116-6]]

^<<v19-116-6,6>>^ O Senhor  vela pelos simples; quando eu estava prostrado, ele me salvou.

[[v19-116-7]]

^<<v19-116-7,7>>^ Ó minha alma, volte ao seu sossego, pois o Senhor  tem sido bom para você.

[[v19-116-8]]

^<<v19-116-8,8>>^ Pois livraste da morte a minha alma, das lágrimas, os meus olhos, da queda, os meus pés.

[[v19-116-9]]

^<<v19-116-9,9>>^ Andarei na presença do Senhor , na terra dos viventes.

[[v19-116-10]]

^<<v19-116-10,10>>^ Eu cria, mesmo quando eu disse: "Estou muito aflito."

[[v19-116-11]]

^<<v19-116-11,11>>^ Eu disse na minha perturbação: "Todas as pessoas são mentirosas."

[[v19-116-12]]

^<<v19-116-12,12>>^ Que darei ao Senhor por todos os seus benefícios para comigo?

[[v19-116-13]]

^<<v19-116-13,13>>^ Erguerei o cálice da salvação e invocarei o nome do Senhor .

[[v19-116-14]]

^<<v19-116-14,14>>^ Cumprirei os meus votos ao Senhor , na presença de todo o seu povo.

[[v19-116-15]]

^<<v19-116-15,15>>^ Preciosa é aos olhos do Senhor a morte dos seus santos.

[[v19-116-16]]

^<<v19-116-16,16>>^ Senhor , eu sou de fato teu servo; eu sou teu servo, filho da tua serva; quebraste as correntes que me prendiam.

[[v19-116-17]]

^<<v19-116-17,17>>^ A ti oferecerei sacrifícios de ações de graças e invocarei o nome do Senhor .

[[v19-116-18]]

^<<v19-116-18,18>>^ Cumprirei os meus votos ao Senhor , na presença de todo o seu povo,

[[v19-116-19]]

^<<v19-116-19,19>>^ nos átrios da Casa do Senhor , em seu meio, ó Jerusalém. Aleluia!

'''

xref:019-salmos/019-salmos-115.adoc#v19-115-0[&#60; Capítulo Anterior] | <<v19-116-0,Topo>> | xref:019-salmos/019-salmos-117.adoc#v19-117-0[Próximo Capítulo &#62;]