include::./index.adoc[]

[[v19-47-0]]
=== Salmos, 47
// naa ?, NAA - Nova Almeida Atualizada

[[v19-47-1]]

^<<v19-47-1,1>>^ Batam palmas, todos os povos; aclamem a Deus com vozes de júbilo.

[[v19-47-2]]

^<<v19-47-2,2>>^ Pois o Senhor  Altíssimo é tremendo, é o grande rei de toda a terra.

[[v19-47-3]]

^<<v19-47-3,3>>^ Ele nos submeteu os povos e pôs as nações debaixo dos nossos pés.

[[v19-47-4]]

^<<v19-47-4,4>>^ Escolheu para nós a nossa herança, a glória de Jacó, a quem ele ama.

[[v19-47-5]]

^<<v19-47-5,5>>^ Deus subiu em meio a aclamações, o Senhor , ao som de trombeta.

[[v19-47-6]]

^<<v19-47-6,6>>^ Cantem louvores a Deus, cantem louvores; cantem louvores ao nosso Rei, cantem louvores.

[[v19-47-7]]

^<<v19-47-7,7>>^ Deus é o Rei de toda a terra; cantem louvores com harmonioso cântico.

[[v19-47-8]]

^<<v19-47-8,8>>^ Deus reina sobre as nações; Deus se assenta no seu santo trono.

[[v19-47-9]]

^<<v19-47-9,9>>^ Os príncipes dos povos se reúnem com o povo do Deus de Abraão, porque a Deus pertencem os escudos da terra; ele se exaltou gloriosamente.

'''

xref:019-salmos/019-salmos-046.adoc#v19-46-0[&#60; Capítulo Anterior] | <<v19-47-0,Topo>> | xref:019-salmos/019-salmos-048.adoc#v19-48-0[Próximo Capítulo &#62;]