include::./index.adoc[]

[[v19-136-0]]
=== Salmos, 136
// naa ?, NAA - Nova Almeida Atualizada

[[v19-136-1]]

^<<v19-136-1,1>>^ Deem graças ao Senhor , porque ele é bom, porque a sua misericórdia dura para sempre.

[[v19-136-2]]

^<<v19-136-2,2>>^ Deem graças ao Deus dos deuses, porque a sua misericórdia dura para sempre.

[[v19-136-3]]

^<<v19-136-3,3>>^ Deem graças ao Senhor dos senhores, porque a sua misericórdia dura para sempre.

[[v19-136-4]]

^<<v19-136-4,4>>^ Ao único que opera grandes maravilhas, porque a sua misericórdia dura para sempre.

[[v19-136-5]]

^<<v19-136-5,5>>^ Àquele que com entendimento fez os céus, porque a sua misericórdia dura para sempre.

[[v19-136-6]]

^<<v19-136-6,6>>^ Àquele que estendeu a terra sobre as águas, porque a sua misericórdia dura para sempre.

[[v19-136-7]]

^<<v19-136-7,7>>^ Àquele que fez os grandes luzeiros, porque a sua misericórdia dura para sempre.

[[v19-136-8]]

^<<v19-136-8,8>>^ Fez o sol para presidir o dia, porque a sua misericórdia dura para sempre.

[[v19-136-9]]

^<<v19-136-9,9>>^ Fez a lua e as estrelas para presidirem a noite, porque a sua misericórdia dura para sempre.

[[v19-136-10]]

^<<v19-136-10,10>>^ Àquele que matou os primogênitos do Egito, porque a sua misericórdia dura para sempre.

[[v19-136-11]]

^<<v19-136-11,11>>^ E tirou Israel do meio deles, porque a sua misericórdia dura para sempre.

[[v19-136-12]]

^<<v19-136-12,12>>^ Ele os tirou com mão poderosa e braço estendido, porque a sua misericórdia dura para sempre.

[[v19-136-13]]

^<<v19-136-13,13>>^ Àquele que dividiu o mar Vermelho em duas partes, porque a sua misericórdia dura para sempre.

[[v19-136-14]]

^<<v19-136-14,14>>^ E fez Israel passar pelo meio dele, porque a sua misericórdia dura para sempre.

[[v19-136-15]]

^<<v19-136-15,15>>^ Mas lançou Faraó e o seu exército no mar Vermelho, porque a sua misericórdia dura para sempre.

[[v19-136-16]]

^<<v19-136-16,16>>^ Àquele que conduziu o seu povo pelo deserto, porque a sua misericórdia dura para sempre.

[[v19-136-17]]

^<<v19-136-17,17>>^ Àquele que matou reis poderosos, porque a sua misericórdia dura para sempre.

[[v19-136-18]]

^<<v19-136-18,18>>^ E tirou a vida de reis famosos, porque a sua misericórdia dura para sempre.

[[v19-136-19]]

^<<v19-136-19,19>>^ Matou Seom, rei dos amorreus, porque a sua misericórdia dura para sempre.

[[v19-136-20]]

^<<v19-136-20,20>>^ E matou Ogue, rei de Basã, porque a sua misericórdia dura para sempre.

[[v19-136-21]]

^<<v19-136-21,21>>^ E deu a terra deles em herança, porque a sua misericórdia dura para sempre.

[[v19-136-22]]

^<<v19-136-22,22>>^ Em herança a Israel, seu servo, porque a sua misericórdia dura para sempre.

[[v19-136-23]]

^<<v19-136-23,23>>^ Àquele que se lembrou de nós em nosso abatimento, porque a sua misericórdia dura para sempre.

[[v19-136-24]]

^<<v19-136-24,24>>^ E nos libertou dos nossos inimigos, porque a sua misericórdia dura para sempre.

[[v19-136-25]]

^<<v19-136-25,25>>^ Ele dá alimento a todos os seres vivos, porque a sua misericórdia dura para sempre.

[[v19-136-26]]

^<<v19-136-26,26>>^ Deem louvores ao Deus dos céus, porque a sua misericórdia dura para sempre.

'''

xref:019-salmos/019-salmos-135.adoc#v19-135-0[&#60; Capítulo Anterior] | <<v19-136-0,Topo>> | xref:019-salmos/019-salmos-137.adoc#v19-137-0[Próximo Capítulo &#62;]