include::./index.adoc[]

[[v19-68-0]]
=== Salmos, 68
// naa ?, NAA - Nova Almeida Atualizada

[[v19-68-1]]

^<<v19-68-1,1>>^ Deus se levanta; os seus inimigos se dispersam; os que o odeiam fogem da sua presença.

[[v19-68-2]]

^<<v19-68-2,2>>^ Como se dissipa a fumaça, assim tu os dispersas; como a cera se derrete perto do fogo, assim os ímpios somem da presença de Deus.

[[v19-68-3]]

^<<v19-68-3,3>>^ Os justos, porém, se alegram; exultam na presença de Deus e folgam de alegria.

[[v19-68-4]]

^<<v19-68-4,4>>^ Cantem a Deus, cantem louvores ao seu nome; exaltem aquele que cavalga sobre as nuvens. Senhor  é o seu nome; exultem diante dele.

[[v19-68-5]]

^<<v19-68-5,5>>^ Pai dos órfãos e juiz das viúvas é Deus em sua santa morada.

[[v19-68-6]]

^<<v19-68-6,6>>^ Deus faz com que o solitário more em família; liberta os cativos e lhes dá prosperidade; só os rebeldes habitam em terra estéril.

[[v19-68-7]]

^<<v19-68-7,7>>^ Ao saíres, ó Deus, à frente do teu povo, ao avançares pelo deserto,

[[v19-68-8]]

^<<v19-68-8,8>>^ a terra tremeu; também os céus gotejaram na presença de Deus; o próprio Sinai tremeu na presença de Deus, do Deus de Israel.

[[v19-68-9]]

^<<v19-68-9,9>>^ Chuva abundante derramaste, ó Deus, sobre a tua herança; quando ela já estava exausta, tu a restabeleceste.

[[v19-68-10]]

^<<v19-68-10,10>>^ Aí habitou o teu povo; em tua bondade, ó Deus, fizeste provisão para os necessitados.

[[v19-68-11]]

^<<v19-68-11,11>>^ O Senhor deu a palavra, e grande é o exército das mensageiras das boas-novas:

[[v19-68-12]]

^<<v19-68-12,12>>^ "Reis de exércitos fogem! Eles fogem!" E a dona de casa reparte os despojos.

[[v19-68-13]]

^<<v19-68-13,13>>^ Por que estão repousando entre as cercas dos apriscos? As asas da pomba são cobertas de prata, cujas penas maiores têm o brilho do ouro puro.

[[v19-68-14]]

^<<v19-68-14,14>>^ Quando o Todo-Poderoso ali dispersa os reis, cai neve sobre o monte Salmom.

[[v19-68-15]]

^<<v19-68-15,15>>^ Monte altíssimo é o monte de Basã; serra de elevações é o monte de Basã.

[[v19-68-16]]

^<<v19-68-16,16>>^ Por que olham com inveja, ó montes elevados, para o monte que Deus escolheu para sua habitação? O Senhor  habitará nele para sempre.

[[v19-68-17]]

^<<v19-68-17,17>>^ Os carros de Deus são vinte mil, sim, milhares de milhares. No meio deles, está o Senhor; o Sinai tornou-se em santuário.

[[v19-68-18]]

^<<v19-68-18,18>>^ Subiste às alturas, levaste cativo o cativeiro; recebeste homens por dádivas, até mesmo rebeldes, para que o Senhor  Deus habite no meio deles.

[[v19-68-19]]

^<<v19-68-19,19>>^ Bendito seja o Senhor que, dia a dia, leva o nosso fardo! Deus é a nossa salvação.

[[v19-68-20]]

^<<v19-68-20,20>>^ O nosso Deus é o Deus libertador; com Deus, o Senhor , está o escaparmos da morte.

[[v19-68-21]]

^<<v19-68-21,21>>^ Sim, Deus parte a cabeça dos seus inimigos e racha o crânio do que anda nos seus próprios delitos.

[[v19-68-22]]

^<<v19-68-22,22>>^ O Senhor disse: "Eu os trarei de Basã, eu os farei voltar das profundezas do mar,

[[v19-68-23]]

^<<v19-68-23,23>>^ para que você banhe o seu pé em sangue, e a língua dos seus cães tenha a sua porção dos inimigos."

[[v19-68-24]]

^<<v19-68-24,24>>^ Viu-se, ó Deus, o teu cortejo, o cortejo do meu Deus, do meu Rei, no santuário.

[[v19-68-25]]

^<<v19-68-25,25>>^ Os cantores iam na frente, atrás vinham os tocadores de instrumentos de cordas, em meio às moças com tamborins.

[[v19-68-26]]

^<<v19-68-26,26>>^ Bendigam a Deus nas congregações, bendigam o Senhor , vocês que são da linhagem de Israel.

[[v19-68-27]]

^<<v19-68-27,27>>^ Ali está o mais novo, Benjamim, que os precede, os príncipes de Judá, em grande número, os príncipes de Zebulom e os príncipes de Naftali.

[[v19-68-28]]

^<<v19-68-28,28>>^ Reúne, ó Deus, a tua força, força divina que usaste a nosso favor,

[[v19-68-29]]

^<<v19-68-29,29>>^ oriunda do teu templo em Jerusalém. Os reis te oferecerão presentes.

[[v19-68-30]]

^<<v19-68-30,30>>^ Reprime a fera dos canaviais, a multidão dos fortes como touros e dos povos com novilhos, pisando sobre os que cobiçam barras de prata. Dispersa os povos que têm prazer na guerra.

[[v19-68-31]]

^<<v19-68-31,31>>^ Príncipes vêm do Egito; a Etiópia corre a estender mãos cheias para Deus.

[[v19-68-32]]

^<<v19-68-32,32>>^ Reinos da terra, cantem a Deus, cantem louvores ao Senhor,

[[v19-68-33]]

^<<v19-68-33,33>>^ àquele que vai montado sobre os céus, os céus da antiguidade; eis que ele faz ouvir a sua voz, voz poderosa.

[[v19-68-34]]

^<<v19-68-34,34>>^ Deem glória a Deus! A sua majestade está sobre Israel, e a sua fortaleza, nos céus.

[[v19-68-35]]

^<<v19-68-35,35>>^ Ó Deus, tu és tremendo no teu santuário! O Deus de Israel, ele dá força e poder ao seu povo. Bendito seja Deus!

'''

xref:019-salmos/019-salmos-067.adoc#v19-67-0[&#60; Capítulo Anterior] | <<v19-68-0,Topo>> | xref:019-salmos/019-salmos-069.adoc#v19-69-0[Próximo Capítulo &#62;]