include::./index.adoc[]

[[v19-64-0]]
=== Salmos, 64
// naa ?, NAA - Nova Almeida Atualizada

[[v19-64-1]]

^<<v19-64-1,1>>^ Ouve, ó Deus, a minha voz na minha queixa; preserva a minha vida do terror do inimigo.

[[v19-64-2]]

^<<v19-64-2,2>>^ Esconde-me da conspiração dos malfeitores e do tumulto dos que praticam a iniquidade.

[[v19-64-3]]

^<<v19-64-3,3>>^ Eles afiam a língua como espada e apontam, quais flechas, palavras amargas,

[[v19-64-4]]

^<<v19-64-4,4>>^ para, às escondidas, atingirem o íntegro; contra ele disparam repentinamente e não temem.

[[v19-64-5]]

^<<v19-64-5,5>>^ Teimam no mau propósito; falam em secretamente armar ciladas, e dizem: "Quem nos verá?"

[[v19-64-6]]

^<<v19-64-6,6>>^ Planejam iniquidades e dizem: "O plano que fizemos é perfeito!" Os pensamentos e o coração de cada um deles são um abismo.

[[v19-64-7]]

^<<v19-64-7,7>>^ Mas Deus atira contra eles uma flecha; de repente, ficarão feridos.

[[v19-64-8]]

^<<v19-64-8,8>>^ Assim, serão levados a tropeçar; a própria língua se voltará contra eles; todos os que os veem balançam a cabeça.

[[v19-64-9]]

^<<v19-64-9,9>>^ Todas as pessoas temerão, e anunciarão as obras de Deus, e entenderão o que ele faz.

[[v19-64-10]]

^<<v19-64-10,10>>^ O justo se alegra no Senhor e nele confia; e se gloriam todos os retos de coração.

'''

xref:019-salmos/019-salmos-063.adoc#v19-63-0[&#60; Capítulo Anterior] | <<v19-64-0,Topo>> | xref:019-salmos/019-salmos-065.adoc#v19-65-0[Próximo Capítulo &#62;]