include::./index.adoc[]

[[v19-99-0]]
=== Salmos, 99
// naa ?, NAA - Nova Almeida Atualizada

[[v19-99-1]]

^<<v19-99-1,1>>^ Reina o Senhor ; tremam os povos. Ele está entronizado acima dos querubins; abale-se a terra.

[[v19-99-2]]

^<<v19-99-2,2>>^ O Senhor  é grande em Sião e está exaltado acima de todos os povos.

[[v19-99-3]]

^<<v19-99-3,3>>^ Celebrem eles o teu nome grande e tremendo, porque é santo.

[[v19-99-4]]

^<<v19-99-4,4>>^ És rei poderoso que ama a justiça; tu estabeleces o direito, executas o juízo e a justiça em Jacó.

[[v19-99-5]]

^<<v19-99-5,5>>^ Exaltem o Senhor , nosso Deus, e prostrem-se diante do estrado de seus pés. O Senhor  é santo.

[[v19-99-6]]

^<<v19-99-6,6>>^ Moisés e Arão, entre os seus sacerdotes, e, Samuel, entre os que lhe invocam o nome, clamavam ao Senhor , e ele os ouvia.

[[v19-99-7]]

^<<v19-99-7,7>>^ Falava-lhes na coluna de nuvem; eles guardavam os seus mandamentos e a lei que lhes tinha dado.

[[v19-99-8]]

^<<v19-99-8,8>>^ Tu lhes respondeste, ó Senhor , nosso Deus; foste para eles Deus perdoador, ainda que os tenhas castigado por seus atos.

[[v19-99-9]]

^<<v19-99-9,9>>^ Exaltem o Senhor , nosso Deus, e prostrem-se diante do seu santo monte, porque santo é o Senhor , nosso Deus.

'''

xref:019-salmos/019-salmos-098.adoc#v19-98-0[&#60; Capítulo Anterior] | <<v19-99-0,Topo>> | xref:019-salmos/019-salmos-100.adoc#v19-100-0[Próximo Capítulo &#62;]