include::./index.adoc[]

[[v19-62-0]]
=== Salmos, 62
// naa ?, NAA - Nova Almeida Atualizada

[[v19-62-1]]

^<<v19-62-1,1>>^ Somente em Deus a minha alma espera silenciosa; dele vem a minha salvação.

[[v19-62-2]]

^<<v19-62-2,2>>^ Só ele é a minha rocha, a minha salvação e o meu alto refúgio; não serei muito abalado.

[[v19-62-3]]

^<<v19-62-3,3>>^ Até quando vocês atacarão um homem, todos vocês, para o derrubarem, como se fosse uma parede pendida ou um muro prestes a cair?

[[v19-62-4]]

^<<v19-62-4,4>>^ Só pensam em derrubá-lo da sua dignidade. Eles se alegram na mentira; de boca bendizem, porém no interior maldizem.

[[v19-62-5]]

^<<v19-62-5,5>>^ Somente em Deus, ó minha alma, espere silenciosa, porque dele vem a minha esperança.

[[v19-62-6]]

^<<v19-62-6,6>>^ Só ele é a minha rocha, a minha salvação e o meu alto refúgio; não serei jamais abalado.

[[v19-62-7]]

^<<v19-62-7,7>>^ De Deus dependem a minha salvação e a minha glória; ele é a minha forte rocha e o meu refúgio.

[[v19-62-8]]

^<<v19-62-8,8>>^ Confie nele em todo tempo, ó povo; derrame diante dele o seu coração. Deus é o nosso refúgio.

[[v19-62-9]]

^<<v19-62-9,9>>^ Pura vaidade são os homens plebeus; os de fina estirpe não passam de falsidade; pesados em balança, eles juntos são mais leves do que a vaidade.

[[v19-62-10]]

^<<v19-62-10,10>>^ Não confiem na opressão, nem ponham falsas esperanças na rapina. Se as riquezas de vocês aumentam, não ponham nelas o coração.

[[v19-62-11]]

^<<v19-62-11,11>>^ Uma vez Deus falou, duas vezes ouvi isto: Que o poder pertence a Deus,

[[v19-62-12]]

^<<v19-62-12,12>>^ e a ti, Senhor, pertence a graça, pois a cada um retribuis segundo as suas obras.

'''

xref:019-salmos/019-salmos-061.adoc#v19-61-0[&#60; Capítulo Anterior] | <<v19-62-0,Topo>> | xref:019-salmos/019-salmos-063.adoc#v19-63-0[Próximo Capítulo &#62;]