include::./index.adoc[]

[[v19-42-0]]
=== Salmos, 42
// naa ?, NAA - Nova Almeida Atualizada

[[v19-42-1]]

^<<v19-42-1,1>>^ Assim como a corça suspira pelas correntes das águas, assim, por ti, ó Deus, suspira a minha alma.

[[v19-42-2]]

^<<v19-42-2,2>>^ A minha alma tem sede de Deus, do Deus vivo. Quando irei e me apresentarei diante da face de Deus?

[[v19-42-3]]

^<<v19-42-3,3>>^ As minhas lágrimas têm sido o meu alimento dia e noite, enquanto me dizem continuamente: "E o seu Deus, onde está?"

[[v19-42-4]]

^<<v19-42-4,4>>^ Lembro-me destas coisas — e dentro de mim se derrama a minha alma —, de como eu passava com a multidão de povo e os guiava em procissão à Casa de Deus, entre gritos de alegria e louvor, multidão em festa.

[[v19-42-5]]

^<<v19-42-5,5>>^ Por que você está abatida, ó minha alma? Por que se perturba dentro de mim? Espere em Deus, pois ainda o louvarei, a ele, meu auxílio e Deus meu.

[[v19-42-6]]

^<<v19-42-6,6>>^ Sinto abatida dentro de mim a minha alma; lembro-me, portanto, de ti, nas terras do Jordão, no Hermom, e no monte Mizar.

[[v19-42-7]]

^<<v19-42-7,7>>^ Um abismo chama outro abismo, ao ruído das tuas cachoeiras; todas as tuas ondas e vagas passaram sobre mim.

[[v19-42-8]]

^<<v19-42-8,8>>^ Contudo, o Senhor , durante o dia, me concede a sua misericórdia, e de noite está comigo o seu cântico, uma oração ao Deus da minha vida.

[[v19-42-9]]

^<<v19-42-9,9>>^ Pergunto a Deus, minha rocha: "Por que te esqueceste de mim? Por que hei de andar eu lamentando sob a opressão dos meus inimigos?"

[[v19-42-10]]

^<<v19-42-10,10>>^ Os meus ossos se esmigalham, quando os meus adversários me insultam, perguntando sem parar: "E o seu Deus, onde está?"

[[v19-42-11]]

^<<v19-42-11,11>>^ Por que você está abatida, ó minha alma? Por que se perturba dentro de mim? Espere em Deus, pois ainda o louvarei, a ele, meu auxílio e Deus meu.

'''

xref:019-salmos/019-salmos-041.adoc#v19-41-0[&#60; Capítulo Anterior] | <<v19-42-0,Topo>> | xref:019-salmos/019-salmos-043.adoc#v19-43-0[Próximo Capítulo &#62;]