include::./index.adoc[]

[[v19-40-0]]
=== Salmos, 40
// naa ?, NAA - Nova Almeida Atualizada

[[v19-40-1]]

^<<v19-40-1,1>>^ Esperei com paciência pelo Senhor ; ele se inclinou para mim e me ouviu quando clamei por socorro.

[[v19-40-2]]

^<<v19-40-2,2>>^ Tirou-me de um poço de perdição, de um atoleiro de lama; colocou os meus pés sobre uma rocha e firmou os meus passos.

[[v19-40-3]]

^<<v19-40-3,3>>^ E me pôs nos lábios um cântico novo, um hino de louvor ao nosso Deus. Muitos verão essas coisas, temerão e confiarão no Senhor .

[[v19-40-4]]

^<<v19-40-4,4>>^ Bem-aventurado é aquele que põe no Senhor a sua confiança e não se volta para os arrogantes, nem para os que seguem a mentira.

[[v19-40-5]]

^<<v19-40-5,5>>^ São muitas, Senhor , Deus meu, as maravilhas que tens operado e também os teus desígnios para conosco; não há ninguém que possa se igualar a ti. Eu quisera anunciá-los e deles falar, mas são mais do que se pode contar.

[[v19-40-6]]

^<<v19-40-6,6>>^ Sacrifícios e ofertas não quiseste; abriste os meus ouvidos; holocaustos e ofertas pelo pecado não requeres.

[[v19-40-7]]

^<<v19-40-7,7>>^ Então eu disse: "Eis aqui estou, no rolo do livro está escrito a meu respeito;

[[v19-40-8]]

^<<v19-40-8,8>>^ agrada-me fazer a tua vontade, ó Deus meu; a tua lei está dentro do meu coração."

[[v19-40-9]]

^<<v19-40-9,9>>^ Proclamei as boas-novas de justiça na grande congregação; jamais cerrei os lábios, tu o sabes, Senhor .

[[v19-40-10]]

^<<v19-40-10,10>>^ Não ocultei no coração a tua justiça; proclamei a tua fidelidade e a tua salvação; não escondi da grande congregação a tua graça e a tua verdade.

[[v19-40-11]]

^<<v19-40-11,11>>^ Não retenhas de mim, Senhor , as tuas misericórdias; que a tua graça e a tua verdade sempre me guardem.

[[v19-40-12]]

^<<v19-40-12,12>>^ São incontáveis os males que me cercam; as minhas iniquidades me alcançaram, tantas, que me impedem a visão; são mais numerosas que os cabelos de minha cabeça, e o coração desfalece.

[[v19-40-13]]

^<<v19-40-13,13>>^ Agrada-te, Senhor , em me livrar; apressa-te, ó Senhor , em me socorrer.

[[v19-40-14]]

^<<v19-40-14,14>>^ Que sejam envergonhados e cobertos de vexame todos os que buscam tirar-me a vida; retrocedam e cubram-se de vergonha os que se alegram com o meu mal.

[[v19-40-15]]

^<<v19-40-15,15>>^ Sofram perturbação por causa da sua vergonha aqueles que me dizem: "Bem feito! Bem feito!"

[[v19-40-16]]

^<<v19-40-16,16>>^ Exultem e em ti se alegrem todos os que te buscam; os que amam a tua salvação digam sempre: "O Senhor  seja engrandecido!"

[[v19-40-17]]

^<<v19-40-17,17>>^ Eu sou pobre e necessitado, porém o Senhor cuida de mim. Tu és o meu amparo e o meu libertador; não te demores, ó Deus meu!

'''

xref:019-salmos/019-salmos-039.adoc#v19-39-0[&#60; Capítulo Anterior] | <<v19-40-0,Topo>> | xref:019-salmos/019-salmos-041.adoc#v19-41-0[Próximo Capítulo &#62;]