include::./index.adoc[]

[[v19-35-0]]
=== Salmos, 35
// naa ?, NAA - Nova Almeida Atualizada

[[v19-35-1]]

^<<v19-35-1,1>>^ Ó Senhor , defende a minha causa contra os que me acusam; luta contra aqueles que me atacam.

[[v19-35-2]]

^<<v19-35-2,2>>^ Embraça o escudo e a couraça e ergue-te em meu auxílio.

[[v19-35-3]]

^<<v19-35-3,3>>^ Empunha a lança e reprime o passo dos meus perseguidores. Dize à minha alma: "Eu sou a sua salvação."

[[v19-35-4]]

^<<v19-35-4,4>>^ Sejam confundidos e cobertos de vexame os que buscam tirar-me a vida; retrocedam e sejam envergonhados os que tramam contra mim.

[[v19-35-5]]

^<<v19-35-5,5>>^ Sejam como a palha que o vento leva, impelindo-os o anjo do Senhor .

[[v19-35-6]]

^<<v19-35-6,6>>^ Que o caminho deles fique escuro e se torne escorregadio, e que o anjo do Senhor  os persiga.

[[v19-35-7]]

^<<v19-35-7,7>>^ Pois sem razão me armaram ciladas, sem motivo abriram uma cova para mim.

[[v19-35-8]]

^<<v19-35-8,8>>^ Venha sobre o inimigo a destruição, quando ele menos esperar; e prendam-no os laços que tramou ocultamente; caia neles para a sua própria ruína.

[[v19-35-9]]

^<<v19-35-9,9>>^ Então a minha alma se alegrará no Senhor e se regozijará na sua salvação.

[[v19-35-10]]

^<<v19-35-10,10>>^ Todos os meus ossos dirão: " Senhor , quem é semelhante a ti? Pois livras o aflito daquele que é mais forte do que ele; livras o pobre e o necessitado daqueles que os exploram."

[[v19-35-11]]

^<<v19-35-11,11>>^ Falsas testemunhas se levantam e me interrogam sobre coisas que eu não sei.

[[v19-35-12]]

^<<v19-35-12,12>>^ Pagam-me o mal pelo bem, o que é desolação para a minha alma.

[[v19-35-13]]

^<<v19-35-13,13>>^ Quanto a mim, porém, estando eles enfermos, as minhas roupas eram pano de saco; eu afligia a minha alma com jejum e em oração me reclinava sobre o peito.

[[v19-35-14]]

^<<v19-35-14,14>>^ Portava-me como se eles fossem meus amigos ou meus irmãos; andava curvado, de luto, como quem chora por sua mãe.

[[v19-35-15]]

^<<v19-35-15,15>>^ Quando, porém, tropecei, eles se alegraram e se reuniram; reuniram-se contra mim; homens sem valor, que eu não conhecia, dilaceraram-me sem tréguas;

[[v19-35-16]]

^<<v19-35-16,16>>^ como hipócritas zombadores numa festa, rangiam os dentes contra mim.

[[v19-35-17]]

^<<v19-35-17,17>>^ Até quando, Senhor, ficarás olhando? Livra-me da violência deles; salva dos leões a minha preciosa vida.

[[v19-35-18]]

^<<v19-35-18,18>>^ Renderei graças na grande congregação, te louvarei no meio da multidão poderosa.

[[v19-35-19]]

^<<v19-35-19,19>>^ Não se alegrem de mim os que, sem razão, são meus inimigos; não pisquem os olhos os que sem motivo me odeiam.

[[v19-35-20]]

^<<v19-35-20,20>>^ Não é de paz que eles falam; pelo contrário, tramam enganos contra os pacíficos da terra.

[[v19-35-21]]

^<<v19-35-21,21>>^ Escancaram contra mim a boca e dizem: "Pegamos! Pegamos! Vimos tudo com os nossos próprios olhos!"

[[v19-35-22]]

^<<v19-35-22,22>>^ Tu, Senhor , tens visto isso; não te cales; Senhor, não te ausentes de mim.

[[v19-35-23]]

^<<v19-35-23,23>>^ Acorda e desperta para me fazeres justiça! Defende a minha causa, Deus meu e Senhor meu.

[[v19-35-24]]

^<<v19-35-24,24>>^ Julga-me, Senhor , Deus meu, segundo a tua justiça; não permitas que se alegrem à minha custa.

[[v19-35-25]]

^<<v19-35-25,25>>^ Não digam eles lá no seu íntimo: "Agora, sim! Cumpriu-se o nosso desejo!" Não digam: "Acabamos com ele!"

[[v19-35-26]]

^<<v19-35-26,26>>^ Envergonhem-se e, juntos, sejam cobertos de vexame os que se alegram com o meu mal! Cubram-se de vergonha e humilhação os que se engrandecem contra mim!

[[v19-35-27]]

^<<v19-35-27,27>>^ Cantem de júbilo e se alegrem os que têm prazer na minha retidão! Que eles digam sempre: "Glorificado seja o Senhor , que se compraz na prosperidade do seu servo!"

[[v19-35-28]]

^<<v19-35-28,28>>^ E a minha língua celebrará a tua justiça e o teu louvor todo o dia.

'''

xref:019-salmos/019-salmos-034.adoc#v19-34-0[&#60; Capítulo Anterior] | <<v19-35-0,Topo>> | xref:019-salmos/019-salmos-036.adoc#v19-36-0[Próximo Capítulo &#62;]