include::./index.adoc[]

[[v19-26-0]]
=== Salmos, 26
// naa ?, NAA - Nova Almeida Atualizada

[[v19-26-1]]

^<<v19-26-1,1>>^ Faze-me justiça, Senhor , pois tenho andado na minha integridade e confio no Senhor , sem vacilar.

[[v19-26-2]]

^<<v19-26-2,2>>^ Examina-me, Senhor , e prova-me; sonda o meu coração e os meus pensamentos.

[[v19-26-3]]

^<<v19-26-3,3>>^ Pois a tua misericórdia, tenho-a diante dos olhos e tenho andado na tua verdade.

[[v19-26-4]]

^<<v19-26-4,4>>^ Não me tenho assentado com gente falsa e com os hipócritas não me associo.

[[v19-26-5]]

^<<v19-26-5,5>>^ Detesto a assembleia dos malfeitores e com os ímpios não me assento.

[[v19-26-6]]

^<<v19-26-6,6>>^ Lavo as mãos na inocência e, assim, andarei, Senhor , ao redor do teu altar,

[[v19-26-7]]

^<<v19-26-7,7>>^ para entoar, com voz alta, os louvores e proclamar todas as tuas maravilhas.

[[v19-26-8]]

^<<v19-26-8,8>>^ Eu amo, Senhor , a habitação de tua casa e o lugar onde a tua glória reside.

[[v19-26-9]]

^<<v19-26-9,9>>^ Não colhas a minha alma com a dos pecadores, nem a minha vida com a dos sanguinários,

[[v19-26-10]]

^<<v19-26-10,10>>^ em cujas mãos há crimes e cuja mão direita está cheia de subornos.

[[v19-26-11]]

^<<v19-26-11,11>>^ Quanto a mim, porém, ando na minha integridade; livra-me e tem compaixão de mim.

[[v19-26-12]]

^<<v19-26-12,12>>^ O meu pé está firme em terreno plano; nas congregações, bendirei o Senhor .

'''

xref:019-salmos/019-salmos-025.adoc#v19-25-0[&#60; Capítulo Anterior] | <<v19-26-0,Topo>> | xref:019-salmos/019-salmos-027.adoc#v19-27-0[Próximo Capítulo &#62;]