include::./index.adoc[]

[[v19-144-0]]
=== Salmos, 144
// naa ?, NAA - Nova Almeida Atualizada

[[v19-144-1]]

^<<v19-144-1,1>>^ Bendito seja o Senhor , rocha minha, que treina as minhas mãos para a batalha e os dedos, para a guerra.

[[v19-144-2]]

^<<v19-144-2,2>>^ Ele é a minha misericórdia e a minha fortaleza, meu alto refúgio e meu libertador, meu escudo, aquele em quem confio e quem me submete o meu povo.

[[v19-144-3]]

^<<v19-144-3,3>>^ Senhor , que é o homem para que dele tomes conhecimento? E o filho do homem, para que o estimes?

[[v19-144-4]]

^<<v19-144-4,4>>^ O ser humano é como um sopro; os seus dias são como a sombra que passa.

[[v19-144-5]]

^<<v19-144-5,5>>^ Abaixa, Senhor , os teus céus e desce; toca os montes, para que fumeguem.

[[v19-144-6]]

^<<v19-144-6,6>>^ Manda relâmpagos e dispersa os meus inimigos; arremessa as tuas flechas para fazê-los fugir.

[[v19-144-7]]

^<<v19-144-7,7>>^ Estende a mão lá do alto; livra-me e salva-me das muitas águas e do poder de estranhos,

[[v19-144-8]]

^<<v19-144-8,8>>^ cuja boca profere mentiras, e cuja mão direita é a mão direita da falsidade.

[[v19-144-9]]

^<<v19-144-9,9>>^ A ti, ó Deus, entoarei um cântico novo; na lira de dez cordas, te cantarei louvores.

[[v19-144-10]]

^<<v19-144-10,10>>^ É ele quem dá aos reis a vitória; quem livra o seu servo Davi da espada maligna.

[[v19-144-11]]

^<<v19-144-11,11>>^ Livra-me e salva-me do poder de estranhos, cuja boca profere mentiras, e cuja mão direita é a mão direita da falsidade.

[[v19-144-12]]

^<<v19-144-12,12>>^ Que os nossos filhos sejam, na sua mocidade, como plantas viçosas, e que as nossas filhas sejam como colunas, esculpidas para um palácio.

[[v19-144-13]]

^<<v19-144-13,13>>^ Que os nossos celeiros transbordem, cheios de todo tipo de provisões. Que os nossos rebanhos produzam a milhares e a dezenas de milhares, em nossos campos.

[[v19-144-14]]

^<<v19-144-14,14>>^ Que o nosso gado seja fértil, e as vacas não percam as suas crias. Não haja gritos de lamento em nossas praças.

[[v19-144-15]]

^<<v19-144-15,15>>^ Bem-aventurado o povo a quem assim sucede! Sim, feliz é o povo cujo Deus é o Senhor !

'''

xref:019-salmos/019-salmos-143.adoc#v19-143-0[&#60; Capítulo Anterior] | <<v19-144-0,Topo>> | xref:019-salmos/019-salmos-145.adoc#v19-145-0[Próximo Capítulo &#62;]