include::./index.adoc[]

[[v19-106-0]]
=== Salmos, 106
// naa ?, NAA - Nova Almeida Atualizada

[[v19-106-1]]

^<<v19-106-1,1>>^ Aleluia! Deem graças ao Senhor , porque ele é bom, porque a sua misericórdia dura para sempre.

[[v19-106-2]]

^<<v19-106-2,2>>^ Quem saberá contar os poderosos feitos do Senhor ou anunciar todo o seu louvor?

[[v19-106-3]]

^<<v19-106-3,3>>^ Bem-aventurados os que guardam a retidão e os que praticam a justiça em todo tempo.

[[v19-106-4]]

^<<v19-106-4,4>>^ Lembra-te de mim, Senhor , segundo a tua bondade para com o teu povo; visita-me com a tua salvação,

[[v19-106-5]]

^<<v19-106-5,5>>^ para que eu veja a prosperidade dos teus escolhidos, e me alegre com a alegria do teu povo, e me glorie com a tua herança.

[[v19-106-6]]

^<<v19-106-6,6>>^ Pecamos, como os nossos pais; cometemos iniquidade, procedemos mal.

[[v19-106-7]]

^<<v19-106-7,7>>^ Nossos pais, no Egito, não entenderam as tuas maravilhas; não se lembraram da multidão das tuas misericórdias e foram rebeldes junto ao mar, o mar Vermelho.

[[v19-106-8]]

^<<v19-106-8,8>>^ Mas Deus os salvou por amor do seu nome, para lhes revelar o seu poder.

[[v19-106-9]]

^<<v19-106-9,9>>^ Repreendeu o mar Vermelho, e ele secou; ele os fez passar pelos abismos, como por um deserto.

[[v19-106-10]]

^<<v19-106-10,10>>^ Salvou-os das mãos de quem os odiava e os resgatou do poder do inimigo.

[[v19-106-11]]

^<<v19-106-11,11>>^ As águas cobriram os seus opressores; nem um deles escapou.

[[v19-106-12]]

^<<v19-106-12,12>>^ Então creram nas suas palavras e lhe cantaram louvor.

[[v19-106-13]]

^<<v19-106-13,13>>^ Logo, porém, se esqueceram das obras de Deus e não esperaram pelos seus desígnios.

[[v19-106-14]]

^<<v19-106-14,14>>^ Entregaram-se à cobiça, no deserto; e, nos lugares áridos, puseram Deus à prova.

[[v19-106-15]]

^<<v19-106-15,15>>^ Concedeu-lhes o que pediram, mas enviou-lhes também uma doença terrível.

[[v19-106-16]]

^<<v19-106-16,16>>^ Tiveram inveja de Moisés, no acampamento, e de Arão, o santo do Senhor .

[[v19-106-17]]

^<<v19-106-17,17>>^ A terra se abriu, engoliu Datã, e cobriu o grupo de Abirão.

[[v19-106-18]]

^<<v19-106-18,18>>^ Um fogo se acendeu contra o grupo deles; as chamas devoraram os ímpios.

[[v19-106-19]]

^<<v19-106-19,19>>^ Em Horebe, fizeram um bezerro e adoraram o ídolo de metal fundido.

[[v19-106-20]]

^<<v19-106-20,20>>^ E, assim, trocaram a glória de Deus pela imagem de um novilho que come capim.

[[v19-106-21]]

^<<v19-106-21,21>>^ Esqueceram-se de Deus, seu Salvador, que, no Egito, havia feito coisas grandiosas,

[[v19-106-22]]

^<<v19-106-22,22>>^ maravilhas na terra de Cam, tremendos feitos no mar Vermelho.

[[v19-106-23]]

^<<v19-106-23,23>>^ Deus os teria exterminado, como tinha dito, se Moisés, seu escolhido, não se houvesse intercedido, impedindo que o seu furor os destruísse.

[[v19-106-24]]

^<<v19-106-24,24>>^ Também desprezaram a terra aprazível e não deram crédito à palavra de Deus;

[[v19-106-25]]

^<<v19-106-25,25>>^ pelo contrário, murmuraram em suas tendas e não ouviram a voz do Senhor .

[[v19-106-26]]

^<<v19-106-26,26>>^ Então lhes jurou, de mão erguida, que os havia de arrasar no deserto;

[[v19-106-27]]

^<<v19-106-27,27>>^ e também espalharia entre as nações a sua descendência e os dispersaria por outras terras.

[[v19-106-28]]

^<<v19-106-28,28>>^ Também se juntaram a Baal-Peor e comeram os sacrifícios dos ídolos mortos.

[[v19-106-29]]

^<<v19-106-29,29>>^ Assim, com tais ações, provocaram a ira do Senhor ; e a peste se espalhou entre eles.

[[v19-106-30]]

^<<v19-106-30,30>>^ Então se levantou Fineias e executou o juízo; e a peste cessou.

[[v19-106-31]]

^<<v19-106-31,31>>^ Isso lhe foi atribuído como justiça, de geração em geração, para sempre.

[[v19-106-32]]

^<<v19-106-32,32>>^ Depois, provocaram Deus nas águas de Meribá, e, por causa deles, aconteceu uma desgraça com Moisés,

[[v19-106-33]]

^<<v19-106-33,33>>^ pois foram rebeldes ao Espírito de Deus, e Moisés falou sem refletir.

[[v19-106-34]]

^<<v19-106-34,34>>^ Não exterminaram os povos, como o Senhor lhes havia ordenado.

[[v19-106-35]]

^<<v19-106-35,35>>^ Em vez disso, se mesclaram com as nações e aprenderam os seus costumes.

[[v19-106-36]]

^<<v19-106-36,36>>^ Adoraram os seus ídolos, os quais se tornaram armadilha para eles.

[[v19-106-37]]

^<<v19-106-37,37>>^ Sacrificaram seus filhos e suas filhas aos demônios.

[[v19-106-38]]

^<<v19-106-38,38>>^ Derramaram sangue inocente, o sangue de seus filhos e filhas, que sacrificaram aos ídolos de Canaã; e a terra foi contaminada com sangue.

[[v19-106-39]]

^<<v19-106-39,39>>^ Assim se contaminaram com as suas obras e se prostituíram nos seus feitos.

[[v19-106-40]]

^<<v19-106-40,40>>^ Por isso, acendeu-se a ira do Senhor  contra o seu povo, e ele abominou a sua própria herança

[[v19-106-41]]

^<<v19-106-41,41>>^ e os entregou ao poder das nações; sobre eles dominaram os que os odiavam.

[[v19-106-42]]

^<<v19-106-42,42>>^ Também os oprimiram os seus inimigos, sob cujo poder foram subjugados.

[[v19-106-43]]

^<<v19-106-43,43>>^ Muitas vezes os libertou, mas eles o provocaram com os seus planos e, na sua iniquidade, foram abatidos.

[[v19-106-44]]

^<<v19-106-44,44>>^ Mas Deus olhou para eles quando estavam angustiados e lhes ouviu o clamor;

[[v19-106-45]]

^<<v19-106-45,45>>^ lembrou-se, a favor deles, de sua aliança e se compadeceu, segundo a multidão de suas misericórdias.

[[v19-106-46]]

^<<v19-106-46,46>>^ Fez também com que deles tivessem compaixão todos os que os levaram cativos.

[[v19-106-47]]

^<<v19-106-47,47>>^ Salva-nos, Senhor , nosso Deus, e congrega-nos dentre as nações, para que demos graças ao teu santo nome e nos gloriemos no teu louvor.

[[v19-106-48]]

^<<v19-106-48,48>>^ Bendito seja o Senhor , Deus de Israel, de eternidade a eternidade; e todo o povo diga: "Amém!" Aleluia!

'''

xref:019-salmos/019-salmos-105.adoc#v19-105-0[&#60; Capítulo Anterior] | <<v19-106-0,Topo>> | xref:019-salmos/019-salmos-107.adoc#v19-107-0[Próximo Capítulo &#62;]