include::./index.adoc[]

[[v19-61-0]]
=== Salmos, 61
// naa ?, NAA - Nova Almeida Atualizada

[[v19-61-1]]

^<<v19-61-1,1>>^ Ouve, ó Deus, a minha súplica; atende à minha oração.

[[v19-61-2]]

^<<v19-61-2,2>>^ Desde os confins da terra clamo por ti, no abatimento do meu coração. Leva-me para a rocha que é alta demais para mim;

[[v19-61-3]]

^<<v19-61-3,3>>^ pois tu tens sido o meu refúgio e uma torre forte contra o inimigo.

[[v19-61-4]]

^<<v19-61-4,4>>^ Que eu possa habitar no teu tabernáculo para sempre e abrigar-me no esconderijo das tuas asas.

[[v19-61-5]]

^<<v19-61-5,5>>^ Pois ouviste, ó Deus, os meus votos e me deste a herança dos que temem o teu nome.

[[v19-61-6]]

^<<v19-61-6,6>>^ Dias sobre dias acrescentas ao rei; os seus anos duram gerações após gerações.

[[v19-61-7]]

^<<v19-61-7,7>>^ Que ele permaneça para sempre diante de Deus; concede-lhe que a bondade e a fidelidade o preservem.

[[v19-61-8]]

^<<v19-61-8,8>>^ Assim, cantarei louvores ao teu nome para sempre, para cumprir, dia após dia, os meus votos.

'''

xref:019-salmos/019-salmos-060.adoc#v19-60-0[&#60; Capítulo Anterior] | <<v19-61-0,Topo>> | xref:019-salmos/019-salmos-062.adoc#v19-62-0[Próximo Capítulo &#62;]