include::./index.adoc[]

[[v19-37-0]]
=== Salmos, 37
// naa ?, NAA - Nova Almeida Atualizada

[[v19-37-1]]

^<<v19-37-1,1>>^ Não se irrite por causa dos malfeitores, nem tenha inveja dos que praticam a iniquidade.

[[v19-37-2]]

^<<v19-37-2,2>>^ Pois em breve eles secarão como a relva e murcharão como a erva verde.

[[v19-37-3]]

^<<v19-37-3,3>>^ Confie no Senhor  e faça o bem; habite na terra e alimente-se da verdade.

[[v19-37-4]]

^<<v19-37-4,4>>^ Agrade-se do Senhor , e ele satisfará os desejos do seu coração.

[[v19-37-5]]

^<<v19-37-5,5>>^ Entregue o seu caminho ao Senhor , confie nele, e o mais ele fará.

[[v19-37-6]]

^<<v19-37-6,6>>^ Fará com que a sua justiça sobressaia como a luz e que o seu direito brilhe como o sol ao meio-dia.

[[v19-37-7]]

^<<v19-37-7,7>>^ Descanse no Senhor e espere nele; não se irrite por causa daquele que prospera em seu caminho, por causa do que realiza os seus maus desígnios.

[[v19-37-8]]

^<<v19-37-8,8>>^ Deixe a ira, abandone o furor; não se irrite; certamente isso acabará mal.

[[v19-37-9]]

^<<v19-37-9,9>>^ Porque os malfeitores serão exterminados, mas os que esperam no Senhor  possuirão a terra.

[[v19-37-10]]

^<<v19-37-10,10>>^ Mais um pouco de tempo, e já não existirão os ímpios; você procurará no lugar onde eles estavam e não os encontrará.

[[v19-37-11]]

^<<v19-37-11,11>>^ Mas os mansos herdarão a terra e terão alegria na abundância de paz.

[[v19-37-12]]

^<<v19-37-12,12>>^ Os ímpios fazem planos contra os justos e contra eles rangem os dentes.

[[v19-37-13]]

^<<v19-37-13,13>>^ O Senhor dá risada dos ímpios, pois vê que o dia deles está chegando.

[[v19-37-14]]

^<<v19-37-14,14>>^ Os ímpios puxam da espada e preparam o arco para abater os pobres e necessitados, para matar os que trilham o reto caminho.

[[v19-37-15]]

^<<v19-37-15,15>>^ Mas a espada deles lhes atravessará o próprio coração, e os seus arcos serão despedaçados.

[[v19-37-16]]

^<<v19-37-16,16>>^ Mais vale o pouco do justo que a abundância de muitos ímpios.

[[v19-37-17]]

^<<v19-37-17,17>>^ Pois os braços dos ímpios serão quebrados, mas os justos, o Senhor  os sustém.

[[v19-37-18]]

^<<v19-37-18,18>>^ O Senhor  conhece os dias dos íntegros; a herança deles permanecerá para sempre.

[[v19-37-19]]

^<<v19-37-19,19>>^ Não serão envergonhados nos tempos difíceis e nos dias da fome se fartarão.

[[v19-37-20]]

^<<v19-37-20,20>>^ Os ímpios, no entanto, perecerão, e os inimigos do Senhor  serão como as mais belas pastagens: desaparecerão, como desaparece a fumaça.

[[v19-37-21]]

^<<v19-37-21,21>>^ O ímpio pede emprestado e não paga; o justo, porém, se compadece e dá.

[[v19-37-22]]

^<<v19-37-22,22>>^ Aqueles a quem o Senhor  abençoa possuirão a terra; e serão exterminados aqueles a quem ele amaldiçoa.

[[v19-37-23]]

^<<v19-37-23,23>>^ O Senhor  firma os passos do homem bom e se agrada do seu caminho;

[[v19-37-24]]

^<<v19-37-24,24>>^ se cair, não ficará prostrado, porque o Senhor o segura pela mão.

[[v19-37-25]]

^<<v19-37-25,25>>^ Fui moço e agora sou velho, porém jamais vi o justo desamparado, nem a sua descendência a mendigar o pão.

[[v19-37-26]]

^<<v19-37-26,26>>^ É sempre compassivo e empresta, e a sua descendência será uma bênção.

[[v19-37-27]]

^<<v19-37-27,27>>^ Afaste-se do mal e pratique o bem, e a sua morada será perpétua.

[[v19-37-28]]

^<<v19-37-28,28>>^ Pois o Senhor  ama a justiça e não desampara os seus santos. Serão preservados para sempre, mas a descendência dos ímpios será exterminada.

[[v19-37-29]]

^<<v19-37-29,29>>^ Os justos herdarão a terra e nela habitarão para sempre.

[[v19-37-30]]

^<<v19-37-30,30>>^ Da boca do justo procede sabedoria, e a sua língua fala o que é justo.

[[v19-37-31]]

^<<v19-37-31,31>>^ No coração, ele tem a lei do seu Deus; os seus passos não vacilarão.

[[v19-37-32]]

^<<v19-37-32,32>>^ O perverso espreita o justo e procura tirar-lhe a vida.

[[v19-37-33]]

^<<v19-37-33,33>>^ Mas o Senhor  não o deixará nas mãos do perverso, nem o condenará quando for julgado.

[[v19-37-34]]

^<<v19-37-34,34>>^ Espere no Senhor e ande nos seus caminhos; ele o exaltará para que você herde a terra; você verá quando os ímpios forem exterminados.

[[v19-37-35]]

^<<v19-37-35,35>>^ Vi um ímpio prepotente expandir-se como um cedro do Líbano.

[[v19-37-36]]

^<<v19-37-36,36>>^ Passei, e eis que havia desaparecido; procurei-o, e já não foi encontrado.

[[v19-37-37]]

^<<v19-37-37,37>>^ Observe aquele que é íntegro e reto; porque o futuro dele será de paz.

[[v19-37-38]]

^<<v19-37-38,38>>^ Quanto aos transgressores, serão todos destruídos; a descendência dos ímpios será exterminada.

[[v19-37-39]]

^<<v19-37-39,39>>^ Mas a salvação dos justos vem do Senhor ; ele é a fortaleza deles em tempos de angústia.

[[v19-37-40]]

^<<v19-37-40,40>>^ O Senhor  os ajuda e os livra; livra-os dos ímpios e os salva, porque nele buscam refúgio.

'''

xref:019-salmos/019-salmos-036.adoc#v19-36-0[&#60; Capítulo Anterior] | <<v19-37-0,Topo>> | xref:019-salmos/019-salmos-038.adoc#v19-38-0[Próximo Capítulo &#62;]