include::./index.adoc[]

[[v19-49-0]]
=== Salmos, 49
// naa ?, NAA - Nova Almeida Atualizada

[[v19-49-1]]

^<<v19-49-1,1>>^ Povos todos, escutem isto; deem ouvidos, todos os moradores da terra,

[[v19-49-2]]

^<<v19-49-2,2>>^ tanto os humildes como os poderosos, todos juntamente, os ricos e os pobres.

[[v19-49-3]]

^<<v19-49-3,3>>^ Os meus lábios falarão sabedoria, e o meu coração terá pensamentos profundos.

[[v19-49-4]]

^<<v19-49-4,4>>^ Inclinarei os meus ouvidos a uma parábola, decifrarei o meu enigma ao som da harpa.

[[v19-49-5]]

^<<v19-49-5,5>>^ Por que temerei nos dias maus, quando me cercar a iniquidade dos que me perseguem,

[[v19-49-6]]

^<<v19-49-6,6>>^ dos que confiam nos seus bens e se gloriam na sua muita riqueza?

[[v19-49-7]]

^<<v19-49-7,7>>^ Ao irmão, verdadeiramente, ninguém o pode remir, nem pagar por ele a Deus o seu resgate —

[[v19-49-8]]

^<<v19-49-8,8>>^ pois a redenção da alma deles é caríssima, e cessará a tentativa para sempre —,

[[v19-49-9]]

^<<v19-49-9,9>>^ para que continue a viver perpetuamente e não venha a morrer.

[[v19-49-10]]

^<<v19-49-10,10>>^ Porque vê-se que os sábios morrem, e que perecem também os tolos e estúpidos, os quais deixam as suas riquezas para os outros.

[[v19-49-11]]

^<<v19-49-11,11>>^ Em seu íntimo pensam que as suas casas serão perpétuas e, as suas moradas, para todas as gerações; chegam a dar o seu próprio nome às suas terras.

[[v19-49-12]]

^<<v19-49-12,12>>^ Todavia, o ser humano não permanece em sua ostentação; pelo contrário, é como os animais, que perecem.

[[v19-49-13]]

^<<v19-49-13,13>>^ Tal proceder é tolice deles; mas os seus seguidores aplaudem o que eles dizem.

[[v19-49-14]]

^<<v19-49-14,14>>^ Como ovelhas são postos na sepultura; a morte é o seu pastor; eles descem diretamente para a cova, onde a sua formosura se consome; o mundo dos mortos é o lugar em que habitam.

[[v19-49-15]]

^<<v19-49-15,15>>^ Mas Deus remirá a minha alma do poder da morte, pois ele me tomará para si.

[[v19-49-16]]

^<<v19-49-16,16>>^ Não tenha medo, quando alguém enriquecer, quando aumentar a glória de sua casa;

[[v19-49-17]]

^<<v19-49-17,17>>^ pois, quando morrer, nada levará consigo, a sua glória não o acompanhará.

[[v19-49-18]]

^<<v19-49-18,18>>^ Ainda que durante a vida ele tenha se lisonjeado, e ainda que o louvem quando faz o bem a si mesmo,

[[v19-49-19]]

^<<v19-49-19,19>>^ irá juntar-se à geração de seus pais, os quais já não verão a luz.

[[v19-49-20]]

^<<v19-49-20,20>>^ O ser humano, revestido de honrarias, mas sem entendimento, é como os animais, que perecem.

'''

xref:019-salmos/019-salmos-048.adoc#v19-48-0[&#60; Capítulo Anterior] | <<v19-49-0,Topo>> | xref:019-salmos/019-salmos-050.adoc#v19-50-0[Próximo Capítulo &#62;]