include::./index.adoc[]

[[v19-140-0]]
=== Salmos, 140
// naa ?, NAA - Nova Almeida Atualizada

[[v19-140-1]]

^<<v19-140-1,1>>^ Senhor , livra-me dos maus; protege-me dos homens violentos,

[[v19-140-2]]

^<<v19-140-2,2>>^ que planejam o mal em seu coração e vivem provocando conflitos.

[[v19-140-3]]

^<<v19-140-3,3>>^ Aguçam a língua como a serpente; sob os lábios têm veneno de víbora.

[[v19-140-4]]

^<<v19-140-4,4>>^ Guarda-me, Senhor , das mãos dos ímpios, protege-me dos homens violentos, que se empenham por me desviar os passos.

[[v19-140-5]]

^<<v19-140-5,5>>^ Os soberbos ocultaram armadilhas e cordas contra mim, estenderam uma rede à beira do caminho; armaram ciladas contra mim.

[[v19-140-6]]

^<<v19-140-6,6>>^ Digo ao Senhor : "Tu és o meu Deus." Escuta, Senhor , a voz das minhas súplicas.

[[v19-140-7]]

^<<v19-140-7,7>>^ Ó Senhor  Deus, força da minha salvação, tu me protegeste a cabeça no dia da batalha.

[[v19-140-8]]

^<<v19-140-8,8>>^ Não concedas, Senhor , aos ímpios os seus desejos; não permitas que sejam bem-sucedidos os seus maus propósitos.

[[v19-140-9]]

^<<v19-140-9,9>>^ Se exaltam a cabeça os que me cercam, que a maldade dos seus lábios caia sobre eles.

[[v19-140-10]]

^<<v19-140-10,10>>^ Caiam sobre eles brasas vivas, sejam atirados ao fogo, lançados em abismos para que não mais se levantem.

[[v19-140-11]]

^<<v19-140-11,11>>^ O caluniador não se estabelecerá na terra; ao homem violento, o mal o perseguirá com golpe sobre golpe.

[[v19-140-12]]

^<<v19-140-12,12>>^ Sei que o Senhor  defenderá a causa do oprimido e o direito do necessitado.

[[v19-140-13]]

^<<v19-140-13,13>>^ Assim, os justos renderão graças ao teu nome; os retos habitarão na tua presença.

'''

xref:019-salmos/019-salmos-139.adoc#v19-139-0[&#60; Capítulo Anterior] | <<v19-140-0,Topo>> | xref:019-salmos/019-salmos-141.adoc#v19-141-0[Próximo Capítulo &#62;]