include::./index.adoc[]

[[v19-45-0]]
=== Salmos, 45
// naa ?, NAA - Nova Almeida Atualizada

[[v19-45-1]]

^<<v19-45-1,1>>^ O meu coração transborda de belas palavras. Ao rei consagro o que compus; a minha língua é como a pena de um hábil escritor.

[[v19-45-2]]

^<<v19-45-2,2>>^ O senhor, ó rei, é o mais formoso dos filhos dos homens; a graça se extravasou nos seus lábios; por isso, Deus o abençoou para sempre.

[[v19-45-3]]

^<<v19-45-3,3>>^ Cinja a espada no seu flanco, herói; cinja a sua glória e a sua majestade!

[[v19-45-4]]

^<<v19-45-4,4>>^ E nessa majestade cavalgue vitoriosamente, pela causa da verdade e da justiça; e a sua mão direita lhe ensinará proezas.

[[v19-45-5]]

^<<v19-45-5,5>>^ As suas flechas são afiadas e penetram o coração dos inimigos do rei; os povos caem submissos aos seus pés.

[[v19-45-6]]

^<<v19-45-6,6>>^ O teu trono, ó Deus, é para todo o sempre; cetro de justiça é o cetro do teu reino.

[[v19-45-7]]

^<<v19-45-7,7>>^ O senhor, ó rei, ama a justiça e odeia a iniquidade; por isso, Deus, o seu Deus, o ungiu com o óleo de alegria, como a nenhum dos seus companheiros.

[[v19-45-8]]

^<<v19-45-8,8>>^ Todas as suas roupas cheiram a mirra, aloés e cássia; de palácios de marfim ressoam instrumentos de cordas que o alegram.

[[v19-45-9]]

^<<v19-45-9,9>>^ Filhas de reis se encontram entre as suas damas de honra; à sua direita está a rainha enfeitada com ouro finíssimo de Ofir.

[[v19-45-10]]

^<<v19-45-10,10>>^ Ouça, filha, olhe e preste atenção: esqueça o seu povo e a casa de seu pai.

[[v19-45-11]]

^<<v19-45-11,11>>^ Então o rei ficará encantado com a sua formosura; por ser ele o seu senhor, incline-se diante dele.

[[v19-45-12]]

^<<v19-45-12,12>>^ A filha de Tiro virá trazendo presentes; os mais ricos do povo lhe pedirão favores.

[[v19-45-13]]

^<<v19-45-13,13>>^ A filha do rei é toda formosura no interior do palácio; os seus vestidos são enfeitados de ouro.

[[v19-45-14]]

^<<v19-45-14,14>>^ Em roupas bordadas conduzem-na diante do rei; as virgens, suas companheiras que a seguem, serão trazidas à sua presença, ó rei.

[[v19-45-15]]

^<<v19-45-15,15>>^ Serão conduzidas com alegria e regozijo; entrarão no palácio do rei.

[[v19-45-16]]

^<<v19-45-16,16>>^ Em lugar de seus pais, estarão os seus filhos, colocados como príncipes por toda a terra.

[[v19-45-17]]

^<<v19-45-17,17>>^ Farei com que o seu nome seja celebrado de geração em geração, e, assim, os povos o louvarão para todo o sempre.

'''

xref:019-salmos/019-salmos-044.adoc#v19-44-0[&#60; Capítulo Anterior] | <<v19-45-0,Topo>> | xref:019-salmos/019-salmos-046.adoc#v19-46-0[Próximo Capítulo &#62;]