include::./index.adoc[]

[[v19-149-0]]
=== Salmos, 149
// naa ?, NAA - Nova Almeida Atualizada

[[v19-149-1]]

^<<v19-149-1,1>>^ Aleluia! Cantem ao Senhor um cântico novo; cantem o seu louvor na assembleia dos santos.

[[v19-149-2]]

^<<v19-149-2,2>>^ Alegre-se Israel no seu Criador; exultem no seu Rei os filhos de Sião.

[[v19-149-3]]

^<<v19-149-3,3>>^ Louvem o nome do Senhor com danças; cantem-lhe salmos ao som de tamborins e harpas.

[[v19-149-4]]

^<<v19-149-4,4>>^ Porque o Senhor se agrada do seu povo e exalta os humildes com a salvação.

[[v19-149-5]]

^<<v19-149-5,5>>^ Que os santos exultem de glória, e no seu leito cantem de júbilo.

[[v19-149-6]]

^<<v19-149-6,6>>^ Nos seus lábios estejam os altos louvores de Deus, e, nas suas mãos, uma espada de dois gumes,

[[v19-149-7]]

^<<v19-149-7,7>>^ para exercer vingança entre as nações e castigo sobre os povos;

[[v19-149-8]]

^<<v19-149-8,8>>^ para prender os seus reis com correntes e os seus nobres, com cadeias de ferro;

[[v19-149-9]]

^<<v19-149-9,9>>^ para executar contra eles a sentença escrita, o que será honra para todos os seus santos. Aleluia!

'''

xref:019-salmos/019-salmos-148.adoc#v19-148-0[&#60; Capítulo Anterior] | <<v19-149-0,Topo>> | xref:019-salmos/019-salmos-150.adoc#v19-150-0[Próximo Capítulo &#62;]