include::./index.adoc[]

[[v19-103-0]]
=== Salmos, 103
// naa ?, NAA - Nova Almeida Atualizada

[[v19-103-1]]

^<<v19-103-1,1>>^ Bendiga, minha alma, o Senhor , e tudo o que há em mim bendiga o seu santo nome.

[[v19-103-2]]

^<<v19-103-2,2>>^ Bendiga, minha alma, o Senhor , e não se esqueça de nem um só de seus benefícios.

[[v19-103-3]]

^<<v19-103-3,3>>^ Ele é quem perdoa todas as suas iniquidades; quem cura todas as suas enfermidades;

[[v19-103-4]]

^<<v19-103-4,4>>^ quem da cova redime a sua vida e coroa você de graça e misericórdia.

[[v19-103-5]]

^<<v19-103-5,5>>^ É ele quem enche de bens a sua vida, de modo que a sua mocidade se renova como a da águia.

[[v19-103-6]]

^<<v19-103-6,6>>^ O Senhor  faz justiça e julga todos os oprimidos.

[[v19-103-7]]

^<<v19-103-7,7>>^ Manifestou os seus caminhos a Moisés e os seus feitos aos filhos de Israel.

[[v19-103-8]]

^<<v19-103-8,8>>^ O Senhor  é compassivo e bondoso; tardio em irar-se e rico em bondade.

[[v19-103-9]]

^<<v19-103-9,9>>^ Não repreende perpetuamente, nem conserva para sempre a sua ira.

[[v19-103-10]]

^<<v19-103-10,10>>^ Não nos trata segundo os nossos pecados, nem nos retribui conforme as nossas iniquidades.

[[v19-103-11]]

^<<v19-103-11,11>>^ Pois quanto o céu se eleva acima da terra, assim é grande a sua misericórdia para com os que o temem.

[[v19-103-12]]

^<<v19-103-12,12>>^ Quanto o Oriente está longe do Ocidente, assim ele afasta de nós as nossas transgressões.

[[v19-103-13]]

^<<v19-103-13,13>>^ Como um pai se compadece de seus filhos, assim o Senhor  se compadece dos que o temem.

[[v19-103-14]]

^<<v19-103-14,14>>^ Pois ele conhece a nossa estrutura e sabe que somos pó.

[[v19-103-15]]

^<<v19-103-15,15>>^ Quanto ao ser humano, os seus dias são como a relva. Como a flor do campo, assim ele floresce;

[[v19-103-16]]

^<<v19-103-16,16>>^ mas, soprando nela o vento, desaparece e não conhecerá, daí em diante, o seu lugar.

[[v19-103-17]]

^<<v19-103-17,17>>^ Mas a misericórdia do Senhor é de eternidade a eternidade sobre os que o temem, e a sua justiça, sobre os filhos dos filhos,

[[v19-103-18]]

^<<v19-103-18,18>>^ para com os que guardam a sua aliança e para com os que se lembram dos seus preceitos e os cumprem.

[[v19-103-19]]

^<<v19-103-19,19>>^ Nos céus, o Senhor estabeleceu o seu trono, e o seu reino domina sobre tudo.

[[v19-103-20]]

^<<v19-103-20,20>>^ Bendigam o Senhor os seus anjos, valorosos em poder, que executam as suas ordens e lhe obedecem à palavra.

[[v19-103-21]]

^<<v19-103-21,21>>^ Bendigam o Senhor todos os seus exércitos, ministros seus, que fazem a sua vontade.

[[v19-103-22]]

^<<v19-103-22,22>>^ Bendigam o Senhor todas as suas obras, em todos os lugares do seu domínio. Bendiga, minha alma, o Senhor .

'''

xref:019-salmos/019-salmos-102.adoc#v19-102-0[&#60; Capítulo Anterior] | <<v19-103-0,Topo>> | xref:019-salmos/019-salmos-104.adoc#v19-104-0[Próximo Capítulo &#62;]