include::./index.adoc[]

[[v19-141-0]]
=== Salmos, 141
// naa ?, NAA - Nova Almeida Atualizada

[[v19-141-1]]

^<<v19-141-1,1>>^ Senhor , eu clamo a ti; apressa-te em me socorrer! Inclina os ouvidos à minha voz, quando te invoco.

[[v19-141-2]]

^<<v19-141-2,2>>^ Suba à tua presença a minha oração como incenso, e seja o erguer de minhas mãos como oferenda vespertina.

[[v19-141-3]]

^<<v19-141-3,3>>^ Põe guarda à minha boca, Senhor ; vigia a porta dos meus lábios.

[[v19-141-4]]

^<<v19-141-4,4>>^ Não permitas que o meu coração se incline para o mal, para a prática da perversidade na companhia de malfeitores; e que eu não coma das suas iguarias.

[[v19-141-5]]

^<<v19-141-5,5>>^ Fira-me o justo, e isso será um favor; repreenda-me, e será como óleo sobre a minha cabeça, a qual não há de rejeitá-lo. Continuarei a orar enquanto os perversos praticam maldade.

[[v19-141-6]]

^<<v19-141-6,6>>^ Quando os seus juízes forem lançados do alto de uma rocha, eles ouvirão as minhas palavras, que são agradáveis.

[[v19-141-7]]

^<<v19-141-7,7>>^ Como quando se lavra e sulca a terra, assim os nossos ossos são espalhados à boca da sepultura.

[[v19-141-8]]

^<<v19-141-8,8>>^ Pois em ti, Senhor  Deus, estão os meus olhos: em ti confio; não desampares a minha alma.

[[v19-141-9]]

^<<v19-141-9,9>>^ Guarda-me dos laços que me armaram e das armadilhas dos que praticam iniquidade.

[[v19-141-10]]

^<<v19-141-10,10>>^ Que os ímpios caiam nas suas próprias redes, enquanto eu escapo ileso.

'''

xref:019-salmos/019-salmos-140.adoc#v19-140-0[&#60; Capítulo Anterior] | <<v19-141-0,Topo>> | xref:019-salmos/019-salmos-142.adoc#v19-142-0[Próximo Capítulo &#62;]