include::./index.adoc[]

[[v19-81-0]]
=== Salmos, 81
// naa ?, NAA - Nova Almeida Atualizada

[[v19-81-1]]

^<<v19-81-1,1>>^ Cantem de júbilo a Deus, força nossa; celebrem o Deus de Jacó.

[[v19-81-2]]

^<<v19-81-2,2>>^ Cantem louvores e façam soar os tamborins, a suave harpa e também a lira.

[[v19-81-3]]

^<<v19-81-3,3>>^ Toquem a trombeta na Festa da Lua Nova, na lua cheia, dia da nossa festa.

[[v19-81-4]]

^<<v19-81-4,4>>^ É preceito para Israel, é prescrição do Deus de Jacó.

[[v19-81-5]]

^<<v19-81-5,5>>^ Ele o ordenou, como lei, a José, ao marchar contra a terra do Egito. Ouvi uma linguagem que eu não conhecia, dizendo:

[[v19-81-6]]

^<<v19-81-6,6>>^ "Livrei os seus ombros do peso, e as mãos de vocês ficaram livres dos cestos.

[[v19-81-7]]

^<<v19-81-7,7>>^ Na angústia, vocês clamaram e eu os livrei; do esconderijo do trovão eu lhes respondi; e eu os pus à prova junto às águas de Meribá.

[[v19-81-8]]

^<<v19-81-8,8>>^ Escute, meu povo, as minhas admoestações. Ó Israel, se ao menos você me escutasse!

[[v19-81-9]]

^<<v19-81-9,9>>^ Não haja no meio de vocês nenhum deus estranho, nem se prostrem diante de um deus estrangeiro.

[[v19-81-10]]

^<<v19-81-10,10>>^ Eu sou o Senhor , o Deus de vocês, que os tirei da terra do Egito. Abram bem a boca, e eu a encherei.

[[v19-81-11]]

^<<v19-81-11,11>>^ Mas o meu povo não escutou a minha voz; Israel não quis saber de mim.

[[v19-81-12]]

^<<v19-81-12,12>>^ Assim, deixei que andassem na teimosia do seu coração, e seguissem as suas próprias inclinações.

[[v19-81-13]]

^<<v19-81-13,13>>^ Ah! Se o meu povo me escutasse, se Israel andasse nos meus caminhos!

[[v19-81-14]]

^<<v19-81-14,14>>^ Eu derrotaria logo os seus inimigos e voltaria a minha mão contra os seus adversários.

[[v19-81-15]]

^<<v19-81-15,15>>^ Os que odeiam o Senhor se submeteriam a ele, e isto duraria para sempre.

[[v19-81-16]]

^<<v19-81-16,16>>^ Mas a vocês eu sustentaria com o trigo mais fino e os saciaria com o mel que escorre da rocha."

'''

xref:019-salmos/019-salmos-080.adoc#v19-80-0[&#60; Capítulo Anterior] | <<v19-81-0,Topo>> | xref:019-salmos/019-salmos-082.adoc#v19-82-0[Próximo Capítulo &#62;]