include::./index.adoc[]

[[v19-112-0]]
=== Salmos, 112
// naa ?, NAA - Nova Almeida Atualizada

[[v19-112-1]]

^<<v19-112-1,1>>^ Aleluia! Bem-aventurado é aquele que teme o Senhor e tem grande prazer nos seus mandamentos.

[[v19-112-2]]

^<<v19-112-2,2>>^ A sua descendência será poderosa na terra; a geração dos justos será abençoada.

[[v19-112-3]]

^<<v19-112-3,3>>^ Na sua casa há prosperidade e riqueza, e a sua justiça permanece para sempre.

[[v19-112-4]]

^<<v19-112-4,4>>^ Aos justos, nasce luz nas trevas; ele é bondoso, compassivo e justo.

[[v19-112-5]]

^<<v19-112-5,5>>^ Feliz aquele que se compadece e empresta; ele defenderá a sua causa em juízo;

[[v19-112-6]]

^<<v19-112-6,6>>^ não será jamais abalado; será tido em memória eterna.

[[v19-112-7]]

^<<v19-112-7,7>>^ Não se atemoriza de más notícias; o seu coração é firme, confiante no Senhor .

[[v19-112-8]]

^<<v19-112-8,8>>^ O seu coração, bem firmado, não teme, até que veja a derrota dos seus inimigos.

[[v19-112-9]]

^<<v19-112-9,9>>^ Distribui, dá aos pobres; a sua justiça permanece para sempre, e o seu poder se exaltará em glória.

[[v19-112-10]]

^<<v19-112-10,10>>^ O ímpio vê isso e fica com raiva; range os dentes e se consome. O desejo dos ímpios perecerá.

'''

xref:019-salmos/019-salmos-111.adoc#v19-111-0[&#60; Capítulo Anterior] | <<v19-112-0,Topo>> | xref:019-salmos/019-salmos-113.adoc#v19-113-0[Próximo Capítulo &#62;]