include::./index.adoc[]

[[v19-14-0]]
=== Salmos, 14
// naa ?, NAA - Nova Almeida Atualizada

[[v19-14-1]]

^<<v19-14-1,1>>^ Diz o insensato no seu coração: "Não há Deus." São corruptos e praticam abominação; já não há quem faça o bem.

[[v19-14-2]]

^<<v19-14-2,2>>^ Do céu o Senhor  olha para os filhos dos homens, para ver se há quem tenha entendimento, se há quem busque a Deus.

[[v19-14-3]]

^<<v19-14-3,3>>^ Todos se desviaram e juntamente se corromperam; não há quem faça o bem, não há nem um sequer.

[[v19-14-4]]

^<<v19-14-4,4>>^ Será que não entendem nada todos esses que praticam a iniquidade, que devoram o meu povo como se comessem pão, e que não invocam o Senhor ?

[[v19-14-5]]

^<<v19-14-5,5>>^ Lá, ficarão tomados de grande pavor, porque Deus está com a linhagem do justo.

[[v19-14-6]]

^<<v19-14-6,6>>^ Vocês querem frustrar o conselho dos humildes, mas o Senhor  é o refúgio deles.

[[v19-14-7]]

^<<v19-14-7,7>>^ Quem dera que de Sião viesse já a salvação de Israel! Quando o Senhor  restaurar a sorte do seu povo, Jacó exultará e Israel se encherá de alegria.

'''

xref:019-salmos/019-salmos-013.adoc#v19-13-0[&#60; Capítulo Anterior] | <<v19-14-0,Topo>> | xref:019-salmos/019-salmos-015.adoc#v19-15-0[Próximo Capítulo &#62;]