include::./index.adoc[]

[[v19-90-0]]
=== Salmos, 90
// naa ?, NAA - Nova Almeida Atualizada

[[v19-90-1]]

^<<v19-90-1,1>>^ Senhor, tu tens sido o nosso refúgio, de geração em geração.

[[v19-90-2]]

^<<v19-90-2,2>>^ Antes que os montes nascessem e tu formasses a terra e o mundo, de eternidade a eternidade, tu és Deus.

[[v19-90-3]]

^<<v19-90-3,3>>^ Tu reduzes o ser humano ao pó e dizes: "Voltem ao pó, filhos dos homens."

[[v19-90-4]]

^<<v19-90-4,4>>^ Pois mil anos, aos teus olhos, são como o dia de ontem que se foi e como a vigília da noite.

[[v19-90-5]]

^<<v19-90-5,5>>^ Tu os arrastas na torrente; são como um sono. São como a relva que floresce de madrugada;

[[v19-90-6]]

^<<v19-90-6,6>>^ de madrugada, viceja e floresce; à tarde, murcha e seca.

[[v19-90-7]]

^<<v19-90-7,7>>^ Pois somos consumidos pela tua ira e pelo teu furor, conturbados.

[[v19-90-8]]

^<<v19-90-8,8>>^ Puseste as nossas iniquidades diante de ti e, sob a luz do teu rosto, os nossos pecados ocultos.

[[v19-90-9]]

^<<v19-90-9,9>>^ Pois todos os nossos dias se passam na tua ira; acabam-se os nossos anos como um breve pensamento.

[[v19-90-10]]

^<<v19-90-10,10>>^ Os dias da nossa vida sobem a setenta anos ou, em havendo vigor, a oitenta; neste caso, o melhor deles é canseira e enfado, porque tudo passa rapidamente, e nós voamos.

[[v19-90-11]]

^<<v19-90-11,11>>^ Quem conhece o poder da tua ira? E a tua cólera, segundo o temor que te é devido?

[[v19-90-12]]

^<<v19-90-12,12>>^ Ensina-nos a contar os nossos dias, para que alcancemos coração sábio.

[[v19-90-13]]

^<<v19-90-13,13>>^ Volta-te, Senhor ! Até quando estarás indignado? Tem compaixão dos teus servos.

[[v19-90-14]]

^<<v19-90-14,14>>^ Sacia-nos de manhã com a tua bondade, para que cantemos de júbilo e nos alegremos todos os nossos dias.

[[v19-90-15]]

^<<v19-90-15,15>>^ Alegra-nos por tantos dias quantos nos tens afligido, por tantos anos quantos suportamos a adversidade.

[[v19-90-16]]

^<<v19-90-16,16>>^ Aos teus servos apareçam as tuas obras, e a seus filhos, a tua glória.

[[v19-90-17]]

^<<v19-90-17,17>>^ Seja sobre nós a graça do Senhor, nosso Deus; confirma sobre nós as obras das nossas mãos, sim, confirma a obra das nossas mãos.

'''

xref:019-salmos/019-salmos-089.adoc#v19-89-0[&#60; Capítulo Anterior] | <<v19-90-0,Topo>> | xref:019-salmos/019-salmos-091.adoc#v19-91-0[Próximo Capítulo &#62;]