include::./index.adoc[]

[[v19-18-0]]
=== Salmos, 18
// naa ?, NAA - Nova Almeida Atualizada

[[v19-18-1]]

^<<v19-18-1,1>>^ Eu te amo, ó Senhor , força minha.

[[v19-18-2]]

^<<v19-18-2,2>>^ O Senhor  é a minha rocha, a minha fortaleza, o meu libertador; o meu Deus, o meu rochedo em que me refugio; o meu escudo, a força da minha salvação, o meu alto refúgio.

[[v19-18-3]]

^<<v19-18-3,3>>^ Invoco o Senhor , digno de ser louvado, e serei salvo dos meus inimigos.

[[v19-18-4]]

^<<v19-18-4,4>>^ Laços de morte me cercaram; torrentes de perdição me impuseram terror.

[[v19-18-5]]

^<<v19-18-5,5>>^ Cadeias infernais me envolveram, e tramas de morte me surpreenderam.

[[v19-18-6]]

^<<v19-18-6,6>>^ Na minha angústia, invoquei o Senhor ; gritei por socorro ao meu Deus. Do seu templo ele ouviu a minha voz, e o meu clamor chegou aos seus ouvidos.

[[v19-18-7]]

^<<v19-18-7,7>>^ Então a terra se abalou e tremeu; vacilaram também os fundamentos dos montes e se abalaram, porque Deus estava irado.

[[v19-18-8]]

^<<v19-18-8,8>>^ Das suas narinas subiu fumaça, e fogo devorador saiu da sua boca; dele saíram brasas ardentes.

[[v19-18-9]]

^<<v19-18-9,9>>^ Ele baixou os céus e desceu, e teve sob os pés densa escuridão.

[[v19-18-10]]

^<<v19-18-10,10>>^ Cavalgava um querubim e voou; foi levado sobre as asas do vento.

[[v19-18-11]]

^<<v19-18-11,11>>^ Das trevas fez um manto em que se ocultou; escuridão de águas e espessas nuvens dos céus eram o seu abrigo.

[[v19-18-12]]

^<<v19-18-12,12>>^ Do resplendor que diante dele havia, as densas nuvens se desfizeram em granizo e brasas de fogo.

[[v19-18-13]]

^<<v19-18-13,13>>^ O Senhor  trovejou nos céus; o Altíssimo levantou a sua voz, e houve granizo e brasas de fogo.

[[v19-18-14]]

^<<v19-18-14,14>>^ Atirou as suas flechas e espalhou os meus inimigos; multiplicou os seus raios e os dispersou.

[[v19-18-15]]

^<<v19-18-15,15>>^ Então se viu o leito das águas, e se descobriram os fundamentos do mundo, pela tua repreensão, Senhor , pelo sopro impetuoso das tuas narinas.

[[v19-18-16]]

^<<v19-18-16,16>>^ Do alto o Senhor  me estendeu a mão e me segurou; ele me tirou das águas profundas.

[[v19-18-17]]

^<<v19-18-17,17>>^ Livrou-me de forte inimigo e dos que me odiavam, pois eram mais poderosos do que eu.

[[v19-18-18]]

^<<v19-18-18,18>>^ Eles me atacaram no dia da minha calamidade, mas o Senhor  me serviu de amparo.

[[v19-18-19]]

^<<v19-18-19,19>>^ Trouxe-me para um lugar espaçoso; livrou-me, porque ele se agradou de mim.

[[v19-18-20]]

^<<v19-18-20,20>>^ O Senhor  me retribuiu segundo a minha justiça; recompensou-me conforme a pureza das minhas mãos.

[[v19-18-21]]

^<<v19-18-21,21>>^ Pois tenho guardado os caminhos do Senhor e não me afastei perversamente do meu Deus.

[[v19-18-22]]

^<<v19-18-22,22>>^ Porque todos os seus juízos estão diante de mim, e não rejeitei os seus preceitos.

[[v19-18-23]]

^<<v19-18-23,23>>^ Também fui íntegro para com ele e me guardei da iniquidade.

[[v19-18-24]]

^<<v19-18-24,24>>^ Por isso, o Senhor  me retribuiu segundo a minha justiça, conforme a pureza das minhas mãos, na sua presença.

[[v19-18-25]]

^<<v19-18-25,25>>^ Para com quem é fiel, fiel te mostras; com o íntegro, também íntegro.

[[v19-18-26]]

^<<v19-18-26,26>>^ Com o puro, puro te mostras; com o perverso, inflexível.

[[v19-18-27]]

^<<v19-18-27,27>>^ Porque tu salvas o povo humilde, mas os olhos soberbos, tu os abates.

[[v19-18-28]]

^<<v19-18-28,28>>^ Porque fazes resplandecer a minha lâmpada; o Senhor , meu Deus, derrama luz nas minhas trevas.

[[v19-18-29]]

^<<v19-18-29,29>>^ Pois contigo posso atacar exércitos; com o meu Deus salto muralhas.

[[v19-18-30]]

^<<v19-18-30,30>>^ O caminho de Deus é perfeito; a palavra do Senhor  é confiável; ele é escudo para todos os que nele se refugiam.

[[v19-18-31]]

^<<v19-18-31,31>>^ Pois quem é Deus além do Senhor ? E quem é rochedo, a não ser o nosso Deus?

[[v19-18-32]]

^<<v19-18-32,32>>^ O Deus que me revestiu de força e aperfeiçoou o meu caminho,

[[v19-18-33]]

^<<v19-18-33,33>>^ ele deu aos meus pés a ligeireza das corças e me firmou nas minhas alturas.

[[v19-18-34]]

^<<v19-18-34,34>>^ Ele treinou as minhas mãos para o combate, tanto que os meus braços vergaram um arco de bronze.

[[v19-18-35]]

^<<v19-18-35,35>>^ Também me deste o escudo da tua salvação; a tua mão direita me susteve, e a tua clemência me engrandeceu.

[[v19-18-36]]

^<<v19-18-36,36>>^ Alargaste o caminho sob meus passos, e os meus pés não vacilaram.

[[v19-18-37]]

^<<v19-18-37,37>>^ Persegui os meus inimigos e os alcancei, e só voltei depois de ter acabado com eles.

[[v19-18-38]]

^<<v19-18-38,38>>^ Esmaguei-os a tal ponto, que não puderam se levantar; caíram sob os meus pés.

[[v19-18-39]]

^<<v19-18-39,39>>^ Pois me cingiste de força para o combate e me submeteste os que se levantaram contra mim.

[[v19-18-40]]

^<<v19-18-40,40>>^ Também puseste em fuga os meus inimigos, e os que me odiavam, eu os exterminei.

[[v19-18-41]]

^<<v19-18-41,41>>^ Gritaram por socorro, mas não houve quem os salvasse; clamaram ao Senhor , mas ele não respondeu.

[[v19-18-42]]

^<<v19-18-42,42>>^ Então os reduzi a pó, o pó que o vento leva; lancei-os fora como a lama das ruas.

[[v19-18-43]]

^<<v19-18-43,43>>^ Dos conflitos do povo me livraste e me fizeste cabeça das nações; um povo que eu não conhecia me serviu.

[[v19-18-44]]

^<<v19-18-44,44>>^ Bastou-lhe ouvir a minha voz, logo me obedeceu; os estrangeiros se mostram submissos a mim.

[[v19-18-45]]

^<<v19-18-45,45>>^ Os estrangeiros fraquejaram e, tremendo, saíram das suas fortalezas.

[[v19-18-46]]

^<<v19-18-46,46>>^ O Senhor  vive! Bendita seja a minha rocha! Exaltado seja o Deus da minha salvação,

[[v19-18-47]]

^<<v19-18-47,47>>^ o Deus que por mim tomou vingança e me submeteu povos;

[[v19-18-48]]

^<<v19-18-48,48>>^ o Deus que me livrou dos meus inimigos; sim, tu que me exaltaste acima dos meus adversários e me livraste dos homens violentos.

[[v19-18-49]]

^<<v19-18-49,49>>^ Por isso, eu te glorificarei entre os gentios, ó Senhor , e cantarei louvores ao teu nome.

[[v19-18-50]]

^<<v19-18-50,50>>^ É ele quem dá grandes vitórias ao seu rei e usa de misericórdia para com o seu ungido, com Davi e sua posteridade, para sempre.

'''

xref:019-salmos/019-salmos-017.adoc#v19-17-0[&#60; Capítulo Anterior] | <<v19-18-0,Topo>> | xref:019-salmos/019-salmos-019.adoc#v19-19-0[Próximo Capítulo &#62;]