include::./index.adoc[]

[[v19-27-0]]
=== Salmos, 27
// naa ?, NAA - Nova Almeida Atualizada

[[v19-27-1]]

^<<v19-27-1,1>>^ O Senhor  é a minha luz e a minha salvação; de quem terei medo? O Senhor  é a fortaleza da minha vida; a quem temerei?

[[v19-27-2]]

^<<v19-27-2,2>>^ Quando malfeitores me sobrevêm para me destruir, meus opressores e inimigos, eles é que tropeçam e caem.

[[v19-27-3]]

^<<v19-27-3,3>>^ Ainda que um exército se acampe contra mim, não se atemorizará o meu coração; e, se estourar contra mim a guerra, ainda assim terei confiança.

[[v19-27-4]]

^<<v19-27-4,4>>^ Uma coisa peço ao Senhor e a buscarei: que eu possa morar na Casa do Senhor todos os dias da minha vida, para contemplar a beleza do Senhor e meditar no seu templo.

[[v19-27-5]]

^<<v19-27-5,5>>^ Pois, no dia da adversidade, ele me ocultará no seu abrigo; no interior do seu tabernáculo, me acolherá; ele me porá no alto de uma rocha.

[[v19-27-6]]

^<<v19-27-6,6>>^ Agora, será exaltada a minha cabeça acima dos inimigos que me cercam. No seu tabernáculo, oferecerei sacrifícios de júbilo; cantarei e salmodiarei ao Senhor .

[[v19-27-7]]

^<<v19-27-7,7>>^ Ouve, Senhor , a minha voz; eu clamo; tem compaixão de mim e responde-me.

[[v19-27-8]]

^<<v19-27-8,8>>^ Ao meu coração me ocorre: "Busquem a minha presença." Buscarei, pois, Senhor , a tua presença.

[[v19-27-9]]

^<<v19-27-9,9>>^ Não me escondas, Senhor , a tua face; não rejeites com ira o teu servo. Tu és o meu auxílio; não me deixes, nem me abandones, ó Deus da minha salvação.

[[v19-27-10]]

^<<v19-27-10,10>>^ Porque, se o meu pai e a minha mãe me abandonarem, o Senhor  me acolherá.

[[v19-27-11]]

^<<v19-27-11,11>>^ Ensina-me, Senhor , o teu caminho e guia-me por vereda plana, por causa dos meus inimigos.

[[v19-27-12]]

^<<v19-27-12,12>>^ Não me entregues à vontade dos meus adversários; pois contra mim se levantam falsas testemunhas e os que só respiram crueldade.

[[v19-27-13]]

^<<v19-27-13,13>>^ Eu creio que verei a bondade do Senhor na terra dos viventes.

[[v19-27-14]]

^<<v19-27-14,14>>^ Espere no Senhor . Anime-se, e fortifique-se o seu coração; espere, pois, no Senhor .

'''

xref:019-salmos/019-salmos-026.adoc#v19-26-0[&#60; Capítulo Anterior] | <<v19-27-0,Topo>> | xref:019-salmos/019-salmos-028.adoc#v19-28-0[Próximo Capítulo &#62;]