include::./index.adoc[]

[[v19-138-0]]
=== Salmos, 138
// naa ?, NAA - Nova Almeida Atualizada

[[v19-138-1]]

^<<v19-138-1,1>>^ Eu te darei graças, Senhor , de todo o meu coração; na presença dos poderosos te cantarei louvores.

[[v19-138-2]]

^<<v19-138-2,2>>^ Voltado para o teu santo templo, eu me prostrarei e louvarei o teu nome, por causa da tua misericórdia e da tua verdade, pois engrandeceste acima de tudo o teu nome e a tua palavra.

[[v19-138-3]]

^<<v19-138-3,3>>^ No dia em que eu clamei, tu me respondeste e alentaste a força de minha alma.

[[v19-138-4]]

^<<v19-138-4,4>>^ Todos os reis da terra te louvarão, Senhor , quando ouvirem as palavras da tua boca,

[[v19-138-5]]

^<<v19-138-5,5>>^ e cantarão os caminhos do Senhor , pois grande é a glória do Senhor .

[[v19-138-6]]

^<<v19-138-6,6>>^ O Senhor  é excelso, contudo, atenta para os humildes; os soberbos, ele os conhece de longe.

[[v19-138-7]]

^<<v19-138-7,7>>^ Se ando em meio à angústia, tu me refazes a vida; estendes a mão contra a ira dos meus inimigos; a tua mão direita me salva.

[[v19-138-8]]

^<<v19-138-8,8>>^ O que diz respeito a mim o Senhor  levará a bom termo; a tua misericórdia, ó Senhor , dura para sempre; não desampares as obras das tuas mãos.

'''

xref:019-salmos/019-salmos-137.adoc#v19-137-0[&#60; Capítulo Anterior] | <<v19-138-0,Topo>> | xref:019-salmos/019-salmos-139.adoc#v19-139-0[Próximo Capítulo &#62;]