include::./index.adoc[]

[[v19-56-0]]
=== Salmos, 56
// naa ?, NAA - Nova Almeida Atualizada

[[v19-56-1]]

^<<v19-56-1,1>>^ Tem misericórdia de mim, ó Deus, porque os homens querem me destruir; todo o dia eles me oprimem e lutam contra mim.

[[v19-56-2]]

^<<v19-56-2,2>>^ Os meus inimigos sempre querem me destruir; são muitos os que atrevidamente me combatem.

[[v19-56-3]]

^<<v19-56-3,3>>^ Quando eu ficar com medo, hei de confiar em ti.

[[v19-56-4]]

^<<v19-56-4,4>>^ Em Deus, cuja palavra eu exalto, neste Deus ponho a minha confiança e nada temerei. Que me pode fazer um mortal?

[[v19-56-5]]

^<<v19-56-5,5>>^ Todo o dia torcem as minhas palavras; os seus pensamentos são todos contra mim para o mal.

[[v19-56-6]]

^<<v19-56-6,6>>^ Ajuntam-se, escondem-se, espionam os meus passos, como aguardando a hora de me tirarem a vida.

[[v19-56-7]]

^<<v19-56-7,7>>^ Dá-lhes a retribuição segundo a sua iniquidade. Derruba os povos, ó Deus, na tua ira!

[[v19-56-8]]

^<<v19-56-8,8>>^ Contaste os meus passos quando sofri perseguições. Recolhe as minhas lágrimas no teu odre; não estão elas inscritas no teu livro?

[[v19-56-9]]

^<<v19-56-9,9>>^ No dia em que eu te invocar, os meus inimigos baterão em retirada. Uma coisa eu sei: que Deus é por mim.

[[v19-56-10]]

^<<v19-56-10,10>>^ Em Deus, cuja palavra eu louvo, no Senhor , cuja palavra eu louvo,

[[v19-56-11]]

^<<v19-56-11,11>>^ neste Deus ponho a minha confiança e nada temerei. Que me pode fazer um simples ser humano?

[[v19-56-12]]

^<<v19-56-12,12>>^ Os votos que fiz, eu os manterei, ó Deus; trarei as ofertas de ações de graças.

[[v19-56-13]]

^<<v19-56-13,13>>^ Pois da morte livraste a minha alma, sim, livraste da queda os meus pés, para que eu ande na presença de Deus, na luz da vida.

'''

xref:019-salmos/019-salmos-055.adoc#v19-55-0[&#60; Capítulo Anterior] | <<v19-56-0,Topo>> | xref:019-salmos/019-salmos-057.adoc#v19-57-0[Próximo Capítulo &#62;]