include::./index.adoc[]

[[v19-113-0]]
=== Salmos, 113
// naa ?, NAA - Nova Almeida Atualizada

[[v19-113-1]]

^<<v19-113-1,1>>^ Aleluia! Louvem, ó servos do Senhor , louvem o nome do Senhor .

[[v19-113-2]]

^<<v19-113-2,2>>^ Bendito seja o nome do Senhor , agora e para sempre.

[[v19-113-3]]

^<<v19-113-3,3>>^ Do nascimento do sol até o momento em que se põe, louvado seja o nome do Senhor .

[[v19-113-4]]

^<<v19-113-4,4>>^ Excelso é o Senhor , acima de todas as nações, e a sua glória está acima dos céus.

[[v19-113-5]]

^<<v19-113-5,5>>^ Quem é semelhante ao Senhor , nosso Deus, cujo trono está nas alturas,

[[v19-113-6]]

^<<v19-113-6,6>>^ que se inclina para ver o que se passa no céu e sobre a terra?

[[v19-113-7]]

^<<v19-113-7,7>>^ Ele levanta o pobre do pó e tira o necessitado do monte de lixo,

[[v19-113-8]]

^<<v19-113-8,8>>^ para o fazer sentar ao lado dos príncipes, sim, com os príncipes do seu povo.

[[v19-113-9]]

^<<v19-113-9,9>>^ O Senhor  faz com que a mulher estéril viva em família e seja alegre mãe de filhos. Aleluia!

'''

xref:019-salmos/019-salmos-112.adoc#v19-112-0[&#60; Capítulo Anterior] | <<v19-113-0,Topo>> | xref:019-salmos/019-salmos-114.adoc#v19-114-0[Próximo Capítulo &#62;]