include::./index.adoc[]

[[v19-10-0]]
=== Salmos, 10
// naa ?, NAA - Nova Almeida Atualizada

[[v19-10-1]]

^<<v19-10-1,1>>^ Por que, Senhor , te conservas longe? Por que te escondes nas horas de angústia?

[[v19-10-2]]

^<<v19-10-2,2>>^ Com arrogância, os ímpios perseguem os pobres; que eles sejam apanhados nas ciladas que armaram!

[[v19-10-3]]

^<<v19-10-3,3>>^ Pois o perverso se gloria da sua própria cobiça, o avarento maldiz o Senhor e blasfema contra ele.

[[v19-10-4]]

^<<v19-10-4,4>>^ Em sua soberba, o perverso não investiga; tudo o que ele pensa é que Deus não existe.

[[v19-10-5]]

^<<v19-10-5,5>>^ São prósperos os caminhos dele em todo tempo; muito acima e longe dele estão os teus juízos; quanto aos seus adversários, ele a todos trata com desprezo.

[[v19-10-6]]

^<<v19-10-6,6>>^ Pois lá no seu íntimo diz: "Jamais serei abalado; de geração em geração, nenhum mal me sobrevirá."

[[v19-10-7]]

^<<v19-10-7,7>>^ A sua boca está cheia de maldição, enganos e opressão; debaixo da língua ele tem insulto e maldade.

[[v19-10-8]]

^<<v19-10-8,8>>^ Põe-se de tocaia nas aldeias, trucida os inocentes nos lugares ocultos; seus olhos espreitam o desamparado.

[[v19-10-9]]

^<<v19-10-9,9>>^ Ele se põe de emboscada, como o leão na sua caverna; está de emboscada para enlaçar o pobre: apanha-o e o arrasta com a sua rede.

[[v19-10-10]]

^<<v19-10-10,10>>^ Abaixa-se, rasteja; nas suas garras caem os necessitados.

[[v19-10-11]]

^<<v19-10-11,11>>^ Diz ele, no seu íntimo: "Deus se esqueceu, virou o rosto e nunca verá isto."

[[v19-10-12]]

^<<v19-10-12,12>>^ Levanta-te, Senhor ! Ó Deus, ergue a tua mão! Não te esqueças dos pobres.

[[v19-10-13]]

^<<v19-10-13,13>>^ Por que o ímpio despreza Deus, dizendo no seu íntimo que Deus não lhe pedirá contas?

[[v19-10-14]]

^<<v19-10-14,14>>^ Tu, porém, tens visto isso, porque atentas ao sofrimento e à dor, para que os possas tomar em tuas mãos. A ti se entrega o desamparado; tu tens sido o defensor do órfão.

[[v19-10-15]]

^<<v19-10-15,15>>^ Quebra o braço do perverso e do malvado; pede contas da sua maldade, até que a descubras de todo.

[[v19-10-16]]

^<<v19-10-16,16>>^ O Senhor  é rei eterno: da sua terra somem as nações.

[[v19-10-17]]

^<<v19-10-17,17>>^ Tens ouvido, Senhor , o desejo dos humildes; tu lhes firmarás o coração e ouvirás o seu clamor,

[[v19-10-18]]

^<<v19-10-18,18>>^ para fazeres justiça ao órfão e ao oprimido, a fim de que o ser humano, que é da terra, não volte a espalhar o terror.

'''

xref:019-salmos/019-salmos-009.adoc#v19-9-0[&#60; Capítulo Anterior] | <<v19-10-0,Topo>> | xref:019-salmos/019-salmos-011.adoc#v19-11-0[Próximo Capítulo &#62;]