include::./index.adoc[]

[[v19-58-0]]
=== Salmos, 58
// naa ?, NAA - Nova Almeida Atualizada

[[v19-58-1]]

^<<v19-58-1,1>>^ Será que vocês, juízes, tomam decisões justas? Julgam com retidão os filhos dos homens?

[[v19-58-2]]

^<<v19-58-2,2>>^ Longe disso! Pelo contrário, no íntimo vocês planejam iniquidades e distribuem na terra a violência de suas mãos.

[[v19-58-3]]

^<<v19-58-3,3>>^ Os ímpios se desviam desde a sua concepção; nascem e já se desencaminham, proferindo mentiras.

[[v19-58-4]]

^<<v19-58-4,4>>^ Têm veneno semelhante ao veneno da serpente; são como a víbora surda, que tapa os ouvidos,

[[v19-58-5]]

^<<v19-58-5,5>>^ para não ouvir a voz dos encantadores, do mais fascinante em encantamentos.

[[v19-58-6]]

^<<v19-58-6,6>>^ Ó Deus, quebra-lhes os dentes na boca; arranca, Senhor , as presas dos leõezinhos.

[[v19-58-7]]

^<<v19-58-7,7>>^ Que eles desapareçam como as águas que se escoam; ao dispararem flechas, que elas se despedacem.

[[v19-58-8]]

^<<v19-58-8,8>>^ Sejam como a lesma, que se dilui ao passar; como o aborto de mulher, que nunca vejam a luz do sol.

[[v19-58-9]]

^<<v19-58-9,9>>^ Como espinheiros, antes que as panelas de vocês sintam deles o calor, tanto os verdes como os que estão em brasa, serão arrebatados como por um redemoinho.

[[v19-58-10]]

^<<v19-58-10,10>>^ Os justos se alegrarão ao verem a vingança; banharão os pés no sangue dos ímpios.

[[v19-58-11]]

^<<v19-58-11,11>>^ Então se dirá: "Na verdade, há recompensa para os justos; de fato há um Deus que julga na terra."

'''

xref:019-salmos/019-salmos-057.adoc#v19-57-0[&#60; Capítulo Anterior] | <<v19-58-0,Topo>> | xref:019-salmos/019-salmos-059.adoc#v19-59-0[Próximo Capítulo &#62;]