include::./index.adoc[]

[[v19-9-0]]
=== Salmos, 9
// naa ?, NAA - Nova Almeida Atualizada

[[v19-9-1]]

^<<v19-9-1,1>>^ Eu te louvarei, Senhor , de todo o meu coração; contarei todas as tuas maravilhas.

[[v19-9-2]]

^<<v19-9-2,2>>^ Em ti me alegrarei e exultarei; ao teu nome, ó Altíssimo, eu cantarei louvores.

[[v19-9-3]]

^<<v19-9-3,3>>^ Pois, ao retrocederem os meus inimigos, tropeçam e somem da tua presença.

[[v19-9-4]]

^<<v19-9-4,4>>^ Porque defendes o meu direito e a minha causa; no trono te assentas e julgas retamente.

[[v19-9-5]]

^<<v19-9-5,5>>^ Tu repreendes as nações, destróis o ímpio e para todo o sempre lhes apagas o nome.

[[v19-9-6]]

^<<v19-9-6,6>>^ Quanto aos inimigos, estão consumidos, suas ruínas são perpétuas; arrasaste as suas cidades; até a memória deles pereceu.

[[v19-9-7]]

^<<v19-9-7,7>>^ Mas o Senhor  permanece no seu trono eternamente, trono que erigiu para julgar.

[[v19-9-8]]

^<<v19-9-8,8>>^ Ele mesmo julga o mundo com justiça; julgará os povos com retidão.

[[v19-9-9]]

^<<v19-9-9,9>>^ O Senhor  é também alto refúgio para o oprimido, refúgio nas horas de angústia.

[[v19-9-10]]

^<<v19-9-10,10>>^ Em ti, pois, confiam os que conhecem o teu nome, porque tu, Senhor , não desamparas os que te buscam.

[[v19-9-11]]

^<<v19-9-11,11>>^ Cantem louvores ao Senhor , que habita em Sião; proclamem entre os povos o que ele tem feito.

[[v19-9-12]]

^<<v19-9-12,12>>^ Pois aquele que requer o sangue lembra-se deles e não se esquece do clamor dos aflitos.

[[v19-9-13]]

^<<v19-9-13,13>>^ Compadece-te de mim, Senhor ; vê a que sofrimentos me reduziram os que me odeiam, tu que me levantas das portas da morte;

[[v19-9-14]]

^<<v19-9-14,14>>^ para que, às portas da filha de Sião, eu proclame todos os teus louvores e me alegre na tua salvação.

[[v19-9-15]]

^<<v19-9-15,15>>^ As nações se afundaram na cova que fizeram, no laço que esconderam ficou preso o seu pé.

[[v19-9-16]]

^<<v19-9-16,16>>^ O Senhor  se dá a conhecer pelo juízo que executa; os ímpios ficam enredados nas obras de suas próprias mãos.

[[v19-9-17]]

^<<v19-9-17,17>>^ No inferno serão lançados os perversos, todas as nações que se esquecem de Deus.

[[v19-9-18]]

^<<v19-9-18,18>>^ Pois o necessitado não será esquecido para sempre, e a esperança dos aflitos não será frustrada perpetuamente.

[[v19-9-19]]

^<<v19-9-19,19>>^ Levanta-te, Senhor ; não deixes que os mortais prevaleçam. Sejam as nações julgadas na tua presença.

[[v19-9-20]]

^<<v19-9-20,20>>^ Infunde-lhes o medo, Senhor ; saibam as nações que não passam de simples mortais.

'''

xref:019-salmos/019-salmos-008.adoc#v19-8-0[&#60; Capítulo Anterior] | <<v19-9-0,Topo>> | xref:019-salmos/019-salmos-010.adoc#v19-10-0[Próximo Capítulo &#62;]