include::./index.adoc[]

[[v19-101-0]]
=== Salmos, 101
// naa ?, NAA - Nova Almeida Atualizada

[[v19-101-1]]

^<<v19-101-1,1>>^ Cantarei a respeito da bondade e da justiça; a ti, Senhor , cantarei.

[[v19-101-2]]

^<<v19-101-2,2>>^ Quero, com sabedoria, refletir no caminho da perfeição. Quando virás ao meu encontro? Em minha casa, andarei com sinceridade de coração.

[[v19-101-3]]

^<<v19-101-3,3>>^ Não porei coisa injusta diante dos meus olhos. Detesto a conduta dos que se desviam. Nada disto se pegará em mim.

[[v19-101-4]]

^<<v19-101-4,4>>^ Longe de mim o coração perverso; não quero conhecer o mal.

[[v19-101-5]]

^<<v19-101-5,5>>^ Ao que às escondidas calunia o próximo, a esse destruirei; o que tem olhar arrogante e coração orgulhoso, não o suportarei.

[[v19-101-6]]

^<<v19-101-6,6>>^ Os meus olhos procurarão os fiéis da terra, para que morem comigo; o que anda em reto caminho, esse me servirá.

[[v19-101-7]]

^<<v19-101-7,7>>^ Não ficará em minha casa o que usa de fraude; o que fala mentiras não permanecerá diante dos meus olhos.

[[v19-101-8]]

^<<v19-101-8,8>>^ Manhã após manhã, destruirei todos os ímpios da terra, para limpar a cidade do Senhor dos que praticam a iniquidade.

'''

xref:019-salmos/019-salmos-100.adoc#v19-100-0[&#60; Capítulo Anterior] | <<v19-101-0,Topo>> | xref:019-salmos/019-salmos-102.adoc#v19-102-0[Próximo Capítulo &#62;]