include::./index.adoc[]

[[v19-4-0]]
=== Salmos, 4
// naa ?, NAA - Nova Almeida Atualizada

[[v19-4-1]]

^<<v19-4-1,1>>^ Responde-me quando clamo, ó Deus da minha justiça; na angústia, tu me deste alívio; tem misericórdia de mim e ouve a minha oração.

[[v19-4-2]]

^<<v19-4-2,2>>^ Filhos dos homens, até quando vocês vão querer transformar a minha glória em vergonha? Até quando amarão a vaidade e buscarão a mentira?

[[v19-4-3]]

^<<v19-4-3,3>>^ Saibam, porém, que o Senhor distingue para si o piedoso; o Senhor  me ouve quando eu clamo por ele.

[[v19-4-4]]

^<<v19-4-4,4>>^ Tremam de medo e não pequem; consultem no travesseiro o coração e sosseguem.

[[v19-4-5]]

^<<v19-4-5,5>>^ Ofereçam sacrifícios de justiça e confiem no Senhor .

[[v19-4-6]]

^<<v19-4-6,6>>^ Há muitos que dizem: "Quem nos dará a conhecer o bem?" Senhor , levanta sobre nós a luz do teu rosto.

[[v19-4-7]]

^<<v19-4-7,7>>^ Mais alegria me puseste no coração do que a alegria deles, quando eles têm fartura de cereal e de vinho.

[[v19-4-8]]

^<<v19-4-8,8>>^ Em paz me deito e logo pego no sono, porque só tu, Senhor , me fazes repousar seguro.

'''

xref:019-salmos/019-salmos-003.adoc#v19-3-0[&#60; Capítulo Anterior] | <<v19-4-0,Topo>> | xref:019-salmos/019-salmos-005.adoc#v19-5-0[Próximo Capítulo &#62;]