include::./index.adoc[]

[[v19-50-0]]
=== Salmos, 50
// naa ?, NAA - Nova Almeida Atualizada

[[v19-50-1]]

^<<v19-50-1,1>>^ Fala o Poderoso, o Senhor  Deus, e chama a terra desde o Oriente até o Ocidente.

[[v19-50-2]]

^<<v19-50-2,2>>^ Desde Sião, excelência de formosura, resplandece Deus.

[[v19-50-3]]

^<<v19-50-3,3>>^ O nosso Deus vem e não guarda silêncio. À frente dele vem um fogo devorador, e ao seu redor ruge grande tormenta.

[[v19-50-4]]

^<<v19-50-4,4>>^ Ele intima os céus lá em cima e a terra, para julgar o seu povo.

[[v19-50-5]]

^<<v19-50-5,5>>^ Ele diz: "Congreguem os meus santos, os que comigo fizeram aliança por meio de sacrifícios."

[[v19-50-6]]

^<<v19-50-6,6>>^ Os céus anunciam a sua justiça, porque é o próprio Deus que julga.

[[v19-50-7]]

^<<v19-50-7,7>>^ "Escute, meu povo, e eu falarei; ó Israel, e eu testemunharei contra você. Eu sou Deus, o seu Deus.

[[v19-50-8]]

^<<v19-50-8,8>>^ Não o repreendo pelos seus sacrifícios, nem pelos holocaustos que você continuamente me oferece.

[[v19-50-9]]

^<<v19-50-9,9>>^ Não aceitarei novilhos da sua casa, nem bodes dos seus apriscos.

[[v19-50-10]]

^<<v19-50-10,10>>^ Pois são meus todos os animais do bosque e o gado aos milhares sobre as montanhas.

[[v19-50-11]]

^<<v19-50-11,11>>^ Conheço todas as aves dos montes, e são meus todos os animais que vivem no campo."

[[v19-50-12]]

^<<v19-50-12,12>>^ "Se eu tivesse fome, não teria necessidade de dizê-lo a você, pois meu é o mundo e a sua plenitude.

[[v19-50-13]]

^<<v19-50-13,13>>^ Acaso como eu carne de touros? Ou bebo sangue de cabritos?

[[v19-50-14]]

^<<v19-50-14,14>>^ Ofereça a Deus sacrifício de ações de graças e cumpra os seus votos para com o Altíssimo.

[[v19-50-15]]

^<<v19-50-15,15>>^ Invoque-me no dia da angústia; eu o livrarei, e você me glorificará."

[[v19-50-16]]

^<<v19-50-16,16>>^ Mas ao ímpio Deus diz: "De que lhe serve repetir os meus preceitos e ter nos lábios a minha aliança,

[[v19-50-17]]

^<<v19-50-17,17>>^ se você odeia a disciplina e rejeita as minhas palavras?

[[v19-50-18]]

^<<v19-50-18,18>>^ Se vê um ladrão, você se torna amigo dele, e aos adúlteros você se associa.

[[v19-50-19]]

^<<v19-50-19,19>>^ Abre a boca para o mal, e a sua língua trama enganos.

[[v19-50-20]]

^<<v19-50-20,20>>^ Senta-se para falar contra o seu irmão e difama o filho de sua mãe.

[[v19-50-21]]

^<<v19-50-21,21>>^ Você tem feito essas coisas, e eu me calei; você pensava que eu era igual a você; mas agora eu o repreenderei e porei tudo à sua vista."

[[v19-50-22]]

^<<v19-50-22,22>>^ "Considerem, pois, nisto, vocês que se esquecem de Deus, para que eu não os despedace, sem haver quem os livre.

[[v19-50-23]]

^<<v19-50-23,23>>^ Aquele que me oferece sacrifício de ações de graças, esse me glorificará; e ao que prepara o seu caminho, farei com que veja a salvação de Deus."

'''

xref:019-salmos/019-salmos-049.adoc#v19-49-0[&#60; Capítulo Anterior] | <<v19-50-0,Topo>> | xref:019-salmos/019-salmos-051.adoc#v19-51-0[Próximo Capítulo &#62;]