include::./index.adoc[]

[[v19-39-0]]
=== Salmos, 39
// naa ?, NAA - Nova Almeida Atualizada

[[v19-39-1]]

^<<v19-39-1,1>>^ Eu disse comigo mesmo: "Guardarei os meus caminhos, para não pecar com a língua; porei mordaça à minha boca, enquanto os ímpios estiverem na minha presença."

[[v19-39-2]]

^<<v19-39-2,2>>^ Emudeci em silêncio, calei a respeito do bem, e a minha dor se agravou.

[[v19-39-3]]

^<<v19-39-3,3>>^ O coração me ardia no peito; enquanto eu meditava, um fogo se acendeu dentro de mim. Então eu disse em voz alta:

[[v19-39-4]]

^<<v19-39-4,4>>^ " Senhor , dá-me a conhecer o meu fim e qual é a soma dos meus dias, para que eu reconheça a minha fragilidade."

[[v19-39-5]]

^<<v19-39-5,5>>^ Deste aos meus dias o comprimento de alguns palmos; à tua presença, o prazo da minha vida é nada. Na verdade, todo ser humano, por mais firme que esteja, é pura vaidade.

[[v19-39-6]]

^<<v19-39-6,6>>^ De fato, o ser humano passa como uma sombra. Em vão se inquieta; amontoa tesouros e não sabe quem ficará com eles.

[[v19-39-7]]

^<<v19-39-7,7>>^ E eu, Senhor, que espero? Tu és a minha esperança.

[[v19-39-8]]

^<<v19-39-8,8>>^ Livra-me de todas as minhas iniquidades; não permitas que os insensatos zombem de mim.

[[v19-39-9]]

^<<v19-39-9,9>>^ Emudeço, não abro os lábios porque tu fizeste isso.

[[v19-39-10]]

^<<v19-39-10,10>>^ Tira de sobre mim o teu flagelo; pelo golpe de tua mão, estou perecendo.

[[v19-39-11]]

^<<v19-39-11,11>>^ Quando castigas alguém com repreensões, por causa do pecado, destróis nele, como traça, o que tem de precioso. De fato, o ser humano é pura vaidade.

[[v19-39-12]]

^<<v19-39-12,12>>^ Ouve, Senhor , a minha oração, escuta-me quando grito por socorro. Não fiques insensível às minhas lágrimas, porque sou forasteiro diante de ti, peregrino como todos os meus pais o foram.

[[v19-39-13]]

^<<v19-39-13,13>>^ Desvia de mim o olhar, para que eu tome alento, antes que eu passe e deixe de existir.

'''

xref:019-salmos/019-salmos-038.adoc#v19-38-0[&#60; Capítulo Anterior] | <<v19-39-0,Topo>> | xref:019-salmos/019-salmos-040.adoc#v19-40-0[Próximo Capítulo &#62;]