include::./index.adoc[]

[[v19-30-0]]
=== Salmos, 30
// naa ?, NAA - Nova Almeida Atualizada

[[v19-30-1]]

^<<v19-30-1,1>>^ Eu te exaltarei, Senhor , porque tu me livraste e não permitiste que os meus inimigos se alegrassem contra mim.

[[v19-30-2]]

^<<v19-30-2,2>>^ Senhor , meu Deus, clamei a ti por socorro, e tu me curaste.

[[v19-30-3]]

^<<v19-30-3,3>>^ Senhor , da sepultura fizeste subir a minha alma; preservaste-me a vida para que não descesse ao abismo.

[[v19-30-4]]

^<<v19-30-4,4>>^ Cantem louvores ao Senhor , vocês que são os seus santos, e deem graças ao seu santo nome.

[[v19-30-5]]

^<<v19-30-5,5>>^ Porque a sua ira dura só um momento, mas o seu favor dura a vida inteira. O choro pode durar uma noite, mas a alegria vem pela manhã.

[[v19-30-6]]

^<<v19-30-6,6>>^ Eu disse na minha prosperidade: "Jamais serei abalado."

[[v19-30-7]]

^<<v19-30-7,7>>^ Tu, Senhor , por teu favor fizeste permanecer forte a minha montanha; apenas voltaste o rosto, fiquei logo com medo.

[[v19-30-8]]

^<<v19-30-8,8>>^ Por ti, Senhor , clamei; ao Senhor implorei.

[[v19-30-9]]

^<<v19-30-9,9>>^ Que proveito obterás no meu sangue, quando baixo à cova? Será que o pó é capaz de te louvar? Poderá ele declarar a tua verdade?

[[v19-30-10]]

^<<v19-30-10,10>>^ Ouve, Senhor , e tem compaixão de mim; sê tu, Senhor , o meu auxílio.

[[v19-30-11]]

^<<v19-30-11,11>>^ Tornaste o meu pranto em dança alegre; tiraste o meu pano de saco e me cingiste de alegria,

[[v19-30-12]]

^<<v19-30-12,12>>^ para que o meu espírito te cante louvores e não se cale. Senhor , Deus meu, graças te darei para sempre.

'''

xref:019-salmos/019-salmos-029.adoc#v19-29-0[&#60; Capítulo Anterior] | <<v19-30-0,Topo>> | xref:019-salmos/019-salmos-031.adoc#v19-31-0[Próximo Capítulo &#62;]