include::./index.adoc[]

[[v19-52-0]]
=== Salmos, 52
// naa ?, NAA - Nova Almeida Atualizada

[[v19-52-1]]

^<<v19-52-1,1>>^ Por que você se gloria na maldade, ó homem poderoso? Pois a bondade de Deus dura para sempre.

[[v19-52-2]]

^<<v19-52-2,2>>^ Com a língua você trama planos de destruição; ela é como navalha afiada, que só produz enganos.

[[v19-52-3]]

^<<v19-52-3,3>>^ Você ama o mal mais do que o bem; prefere mentir a falar a verdade.

[[v19-52-4]]

^<<v19-52-4,4>>^ Você ama todas as palavras devoradoras, ó língua fraudulenta!

[[v19-52-5]]

^<<v19-52-5,5>>^ Também Deus o destruirá para sempre; ele o pegará e arrancará da tenda em que você habita e o extirpará da terra dos viventes.

[[v19-52-6]]

^<<v19-52-6,6>>^ Os justos verão tudo isso, temerão e vão rir dele, dizendo:

[[v19-52-7]]

^<<v19-52-7,7>>^ "Eis o homem que não fazia de Deus a sua fortaleza, mas confiava na abundância dos seus próprios bens e se fortalecia na sua perversidade."

[[v19-52-8]]

^<<v19-52-8,8>>^ Quanto a mim, porém, sou como a oliveira verde na Casa de Deus; confio na misericórdia de Deus para todo o sempre.

[[v19-52-9]]

^<<v19-52-9,9>>^ Sempre te louvarei, porque assim o fizeste; na presença dos teus fiéis, esperarei no teu nome, porque é bom.

'''

xref:019-salmos/019-salmos-051.adoc#v19-51-0[&#60; Capítulo Anterior] | <<v19-52-0,Topo>> | xref:019-salmos/019-salmos-053.adoc#v19-53-0[Próximo Capítulo &#62;]