include::./index.adoc[]

[[v19-7-0]]
=== Salmos, 7
// naa ?, NAA - Nova Almeida Atualizada

[[v19-7-1]]

^<<v19-7-1,1>>^ Senhor , meu Deus, em ti me refugio; salva-me de todos os que me perseguem e livra-me,

[[v19-7-2]]

^<<v19-7-2,2>>^ para que ninguém, como leão, me arrebate, despedaçando-me, não havendo quem me livre.

[[v19-7-3]]

^<<v19-7-3,3>>^ Senhor , meu Deus, se eu fiz isso de que me culpam, se cometi alguma injustiça,

[[v19-7-4]]

^<<v19-7-4,4>>^ se paguei com o mal a quem estava em paz comigo, eu, que poupei aquele que sem razão me oprimia,

[[v19-7-5]]

^<<v19-7-5,5>>^ então que o inimigo me persiga e me alcance, pisoteie no chão a minha vida e reduza a pó a minha glória.

[[v19-7-6]]

^<<v19-7-6,6>>^ Levanta-te, Senhor , na tua indignação, mostra a tua grandeza contra a fúria dos meus adversários e desperta-te em meu favor, segundo o juízo que designaste.

[[v19-7-7]]

^<<v19-7-7,7>>^ Reúnam-se os povos ao redor de ti, e das alturas domina sobre eles.

[[v19-7-8]]

^<<v19-7-8,8>>^ O Senhor  julga os povos; julga-me, Senhor , segundo a minha justiça e segundo a integridade que há em mim.

[[v19-7-9]]

^<<v19-7-9,9>>^ Que cesse a maldade dos ímpios. Fortalece o justo, pois sondas a mente e o coração, ó Deus justo.

[[v19-7-10]]

^<<v19-7-10,10>>^ Deus é o meu escudo; ele salva os retos de coração.

[[v19-7-11]]

^<<v19-7-11,11>>^ Deus é justo juiz, Deus que sente indignação todos os dias.

[[v19-7-12]]

^<<v19-7-12,12>>^ Se alguém não se converter, Deus afiará a sua espada; já armou e deixou pronto o seu arco;

[[v19-7-13]]

^<<v19-7-13,13>>^ para ele já preparou armas mortais, fez as suas setas inflamadas.

[[v19-7-14]]

^<<v19-7-14,14>>^ Eis que o ímpio está com dores de iniquidade; concebeu a maldade e dá à luz a mentira.

[[v19-7-15]]

^<<v19-7-15,15>>^ Abre e aprofunda uma cova, e cai nesse mesmo poço que faz.

[[v19-7-16]]

^<<v19-7-16,16>>^ A sua maldade recai sobre a cabeça, e sobre o próprio crânio desce a sua violência.

[[v19-7-17]]

^<<v19-7-17,17>>^ Eu, porém, louvarei o Senhor , segundo a sua justiça, e cantarei louvores ao nome do Senhor  Altíssimo.

'''

xref:019-salmos/019-salmos-006.adoc#v19-6-0[&#60; Capítulo Anterior] | <<v19-7-0,Topo>> | xref:019-salmos/019-salmos-008.adoc#v19-8-0[Próximo Capítulo &#62;]