include::./index.adoc[]

[[v19-96-0]]
=== Salmos, 96
// naa ?, NAA - Nova Almeida Atualizada

[[v19-96-1]]

^<<v19-96-1,1>>^ Cantem ao Senhor um cântico novo, cantem ao Senhor , todas as terras.

[[v19-96-2]]

^<<v19-96-2,2>>^ Cantem ao Senhor , bendigam o seu nome; proclamem a sua salvação, dia após dia.

[[v19-96-3]]

^<<v19-96-3,3>>^ Anunciem entre as nações a sua glória, entre todos os povos, as suas maravilhas.

[[v19-96-4]]

^<<v19-96-4,4>>^ Porque o Senhor  é grande e digno de ser louvado, mais temível do que todos os deuses.

[[v19-96-5]]

^<<v19-96-5,5>>^ Porque todos os deuses dos povos não passam de ídolos; o Senhor , porém, fez os céus.

[[v19-96-6]]

^<<v19-96-6,6>>^ Glória e majestade estão diante dele, força e formosura, no seu santuário.

[[v19-96-7]]

^<<v19-96-7,7>>^ Deem ao Senhor , ó famílias dos povos, deem ao Senhor  glória e força.

[[v19-96-8]]

^<<v19-96-8,8>>^ Deem ao Senhor a glória devida ao seu nome; tragam ofertas e entrem nos seus átrios.

[[v19-96-9]]

^<<v19-96-9,9>>^ Adorem o Senhor na beleza da sua santidade; tremam diante dele, todas as terras.

[[v19-96-10]]

^<<v19-96-10,10>>^ Digam entre as nações: "Reina o Senhor ." Ele firmou o mundo para que não se abale e julga os povos com justiça.

[[v19-96-11]]

^<<v19-96-11,11>>^ Alegrem-se os céus, e a terra exulte; ruja o mar e a sua plenitude.

[[v19-96-12]]

^<<v19-96-12,12>>^ Alegre-se o campo e tudo o que nele há; cantem de alegria todas as árvores do bosque,

[[v19-96-13]]

^<<v19-96-13,13>>^ na presença do Senhor , porque vem, vem julgar a terra; julgará o mundo com justiça e os povos, de acordo com a sua fidelidade.

'''

xref:019-salmos/019-salmos-095.adoc#v19-95-0[&#60; Capítulo Anterior] | <<v19-96-0,Topo>> | xref:019-salmos/019-salmos-097.adoc#v19-97-0[Próximo Capítulo &#62;]