include::./index.adoc[]

[[v19-148-0]]
=== Salmos, 148
// naa ?, NAA - Nova Almeida Atualizada

[[v19-148-1]]

^<<v19-148-1,1>>^ Aleluia! Louvem o Senhor  do alto dos céus, louvem o Senhor  nas alturas.

[[v19-148-2]]

^<<v19-148-2,2>>^ Louvem o Senhor , todos os seus anjos; louvem-no, todos os seus exércitos celestiais.

[[v19-148-3]]

^<<v19-148-3,3>>^ Louvem o Senhor , sol e lua; louvem-no, todas as estrelas luzentes.

[[v19-148-4]]

^<<v19-148-4,4>>^ Louvem o Senhor , céus dos céus e as águas que estão acima do firmamento.

[[v19-148-5]]

^<<v19-148-5,5>>^ Louvem o nome do Senhor , pois ele deu uma ordem, e foram criados.

[[v19-148-6]]

^<<v19-148-6,6>>^ Ele os estabeleceu para todo o sempre; fixou-lhes uma ordem que não será mudada.

[[v19-148-7]]

^<<v19-148-7,7>>^ Desde a terra, louvem o Senhor ! Louvem-no, monstros marinhos e todos os abismos;

[[v19-148-8]]

^<<v19-148-8,8>>^ fogo e granizo, neve e vapor e ventos fortes que lhe executam a palavra;

[[v19-148-9]]

^<<v19-148-9,9>>^ montes e todas as colinas, árvores frutíferas e todos os cedros;

[[v19-148-10]]

^<<v19-148-10,10>>^ feras e todo o gado, animais que rastejam e aves;

[[v19-148-11]]

^<<v19-148-11,11>>^ reis da terra e todos os povos, príncipes e todos os juízes da terra;

[[v19-148-12]]

^<<v19-148-12,12>>^ rapazes e moças, velhos e crianças.

[[v19-148-13]]

^<<v19-148-13,13>>^ Louvem o nome do Senhor , porque só o seu nome é excelso; a sua majestade está acima da terra e do céu.

[[v19-148-14]]

^<<v19-148-14,14>>^ Ele exalta o poder do seu povo, o louvor de todos os seus santos, dos filhos de Israel, povo que lhe é chegado. Aleluia!

'''

xref:019-salmos/019-salmos-147.adoc#v19-147-0[&#60; Capítulo Anterior] | <<v19-148-0,Topo>> | xref:019-salmos/019-salmos-149.adoc#v19-149-0[Próximo Capítulo &#62;]