include::./index.adoc[]

[[v19-145-0]]
=== Salmos, 145
// naa ?, NAA - Nova Almeida Atualizada

[[v19-145-1]]

^<<v19-145-1,1>>^ Eu te exaltarei, ó Deus meu e Rei; bendirei o teu nome para todo o sempre.

[[v19-145-2]]

^<<v19-145-2,2>>^ Todos os dias te bendirei e louvarei o teu nome para todo o sempre.

[[v19-145-3]]

^<<v19-145-3,3>>^ Grande é o Senhor e mui digno de ser louvado; a sua grandeza é insondável.

[[v19-145-4]]

^<<v19-145-4,4>>^ Uma geração louvará à outra geração as tuas obras e anunciará os teus poderosos feitos.

[[v19-145-5]]

^<<v19-145-5,5>>^ Meditarei no glorioso esplendor da tua majestade e nas tuas maravilhas.

[[v19-145-6]]

^<<v19-145-6,6>>^ Falarão do poder dos teus feitos tremendos, e eu anunciarei a tua grandeza.

[[v19-145-7]]

^<<v19-145-7,7>>^ Divulgarão a memória da tua imensa bondade e com júbilo celebrarão a tua justiça.

[[v19-145-8]]

^<<v19-145-8,8>>^ Bondoso e compassivo é o Senhor , tardio em irar-se e grande em misericórdia.

[[v19-145-9]]

^<<v19-145-9,9>>^ O Senhor  é bom para todos, e as suas misericórdias permeiam todas as suas obras.

[[v19-145-10]]

^<<v19-145-10,10>>^ Todas as tuas obras te renderão graças, Senhor ; e os teus santos te bendirão.

[[v19-145-11]]

^<<v19-145-11,11>>^ Falarão da glória do teu reino e confessarão o teu poder,

[[v19-145-12]]

^<<v19-145-12,12>>^ para que os filhos dos homens conheçam os teus feitos poderosos e a glória da majestade do teu reino.

[[v19-145-13]]

^<<v19-145-13,13>>^ O teu reino é um reino eterno, e o teu domínio subsiste por todas as gerações. O Senhor  é fiel em todas as suas palavras e santo em todas as suas obras.

[[v19-145-14]]

^<<v19-145-14,14>>^ O Senhor  sustém todos os que vacilam e levanta todos os que estão prostrados.

[[v19-145-15]]

^<<v19-145-15,15>>^ Em ti esperam os olhos de todos, e tu, a seu tempo, lhes dás o alimento.

[[v19-145-16]]

^<<v19-145-16,16>>^ Abres a mão e satisfazes os desejos de todos os viventes.

[[v19-145-17]]

^<<v19-145-17,17>>^ Justo é o Senhor  em todos os seus caminhos, bondoso em todas as suas obras.

[[v19-145-18]]

^<<v19-145-18,18>>^ Perto está o Senhor de todos os que o invocam, de todos os que o invocam em verdade.

[[v19-145-19]]

^<<v19-145-19,19>>^ Ele satisfaz o desejo dos que o temem; ouve o seu clamor e os salva.

[[v19-145-20]]

^<<v19-145-20,20>>^ O Senhor  protege todos os que o amam; porém todos os ímpios serão exterminados.

[[v19-145-21]]

^<<v19-145-21,21>>^ A minha boca proclamará o louvor do Senhor . Que todos os seres vivos louvem o seu santo nome, para todo o sempre.

'''

xref:019-salmos/019-salmos-144.adoc#v19-144-0[&#60; Capítulo Anterior] | <<v19-145-0,Topo>> | xref:019-salmos/019-salmos-146.adoc#v19-146-0[Próximo Capítulo &#62;]