include::./index.adoc[]

[[v19-11-0]]
=== Salmos, 11
// naa ?, NAA - Nova Almeida Atualizada

[[v19-11-1]]

^<<v19-11-1,1>>^ No Senhor  me refugio. Como então vocês dizem à minha alma: "Fuja como um pássaro para o seu monte"?

[[v19-11-2]]

^<<v19-11-2,2>>^ Porque eis aí os ímpios, armando os seus arcos; colocam a flecha na corda, para, às escondidas, dispararem contra os retos de coração.

[[v19-11-3]]

^<<v19-11-3,3>>^ Ora, se forem destruídos os fundamentos, que poderá fazer o justo?

[[v19-11-4]]

^<<v19-11-4,4>>^ O Senhor  está no seu santo templo; nos céus o Senhor  tem o seu trono; os seus olhos estão atentos, as suas pálpebras sondam os filhos dos homens.

[[v19-11-5]]

^<<v19-11-5,5>>^ O Senhor  põe à prova o justo e o ímpio; mas ele abomina o que ama a violência.

[[v19-11-6]]

^<<v19-11-6,6>>^ Fará chover sobre os perversos brasas de fogo e enxofre, e vento abrasador será a parte do cálice deles.

[[v19-11-7]]

^<<v19-11-7,7>>^ Por ser justo, o Senhor  ama a justiça; os retos lhe contemplarão a face.

'''

xref:019-salmos/019-salmos-010.adoc#v19-10-0[&#60; Capítulo Anterior] | <<v19-11-0,Topo>> | xref:019-salmos/019-salmos-012.adoc#v19-12-0[Próximo Capítulo &#62;]