include::./index.adoc[]

[[v19-28-0]]
=== Salmos, 28
// naa ?, NAA - Nova Almeida Atualizada

[[v19-28-1]]

^<<v19-28-1,1>>^ A ti clamo, ó Senhor ; rocha minha, não sejas surdo para comigo; porque, se te calares quanto a mim, serei semelhante aos que descem à cova.

[[v19-28-2]]

^<<v19-28-2,2>>^ Ouve a voz das minhas súplicas, quando a ti clamar por socorro, quando erguer as mãos para o teu santuário.

[[v19-28-3]]

^<<v19-28-3,3>>^ Não me arrastes com os ímpios, com os que praticam a iniquidade. Eles falam de paz ao seu próximo, porém no coração têm perversidade.

[[v19-28-4]]

^<<v19-28-4,4>>^ Paga-lhes segundo as suas obras, segundo a maldade dos seus atos. Dá-lhes conforme a obra de suas mãos, retribui-lhes o que merecem.

[[v19-28-5]]

^<<v19-28-5,5>>^ E, visto que não compreendem os feitos do Senhor , nem o que as suas mãos fazem, ele os derrubará e não os reedificará.

[[v19-28-6]]

^<<v19-28-6,6>>^ Bendito seja o Senhor , porque ouviu a voz das minhas súplicas!

[[v19-28-7]]

^<<v19-28-7,7>>^ O Senhor  é a minha força e o meu escudo; nele o meu coração confia, nele fui socorrido; por isso, o meu coração exulta, e com o meu cântico o louvarei.

[[v19-28-8]]

^<<v19-28-8,8>>^ O Senhor  é a força do seu povo, o refúgio salvador do seu ungido.

[[v19-28-9]]

^<<v19-28-9,9>>^ Salva o teu povo e abençoa a tua herança; apascenta-os e exalta-os para sempre.

'''

xref:019-salmos/019-salmos-027.adoc#v19-27-0[&#60; Capítulo Anterior] | <<v19-28-0,Topo>> | xref:019-salmos/019-salmos-029.adoc#v19-29-0[Próximo Capítulo &#62;]