include::./index.adoc[]

[[v19-86-0]]
=== Salmos, 86
// naa ?, NAA - Nova Almeida Atualizada

[[v19-86-1]]

^<<v19-86-1,1>>^ Inclina, Senhor , os teus ouvidos e responde-me, pois estou aflito e necessitado.

[[v19-86-2]]

^<<v19-86-2,2>>^ Preserva a minha alma, pois eu sou piedoso. Ó Deus meu, salva o teu servo que em ti confia.

[[v19-86-3]]

^<<v19-86-3,3>>^ Compadece-te de mim, ó Senhor, pois a ti clamo todo o dia.

[[v19-86-4]]

^<<v19-86-4,4>>^ Alegra a alma do teu servo, porque a ti, Senhor, elevo a minha alma.

[[v19-86-5]]

^<<v19-86-5,5>>^ Pois tu, Senhor, és bom e perdoador; rico em misericórdia para com todos os que te invocam.

[[v19-86-6]]

^<<v19-86-6,6>>^ Escuta, Senhor , a minha oração e atende à voz das minhas súplicas.

[[v19-86-7]]

^<<v19-86-7,7>>^ No dia da minha angústia clamo a ti, porque me respondes.

[[v19-86-8]]

^<<v19-86-8,8>>^ Não há entre os deuses quem seja semelhante a ti, Senhor; e nada existe que se compare às tuas obras.

[[v19-86-9]]

^<<v19-86-9,9>>^ Todas as nações que fizeste virão, se prostrarão diante de ti, Senhor, e glorificarão o teu nome.

[[v19-86-10]]

^<<v19-86-10,10>>^ Pois tu és grande e operas maravilhas; só tu és Deus!

[[v19-86-11]]

^<<v19-86-11,11>>^ Ensina-me, Senhor , o teu caminho, e andarei na tua verdade; põe em meu coração o desejo de temer o teu nome.

[[v19-86-12]]

^<<v19-86-12,12>>^ Eu te darei graças, Senhor, Deus meu, de todo o coração, e glorificarei para sempre o teu nome.

[[v19-86-13]]

^<<v19-86-13,13>>^ Pois grande é a tua misericórdia para comigo, e me livraste a alma do mais profundo poder da morte.

[[v19-86-14]]

^<<v19-86-14,14>>^ Ó Deus, os soberbos se levantaram contra mim, e um bando de violentos procura tirar-me a vida; eles não te consideram.

[[v19-86-15]]

^<<v19-86-15,15>>^ Mas tu, Senhor, és Deus compassivo e bondoso, tardio em irar-se e grande em misericórdia e fidelidade.

[[v19-86-16]]

^<<v19-86-16,16>>^ Volta-te para mim e tem compaixão de mim; concede a tua força ao teu servo e salva o filho da tua serva.

[[v19-86-17]]

^<<v19-86-17,17>>^ Mostra-me um sinal do teu favor, para que o vejam e se envergonhem os que me odeiam; pois tu, Senhor , me ajudas e me consolas.

'''

xref:019-salmos/019-salmos-085.adoc#v19-85-0[&#60; Capítulo Anterior] | <<v19-86-0,Topo>> | xref:019-salmos/019-salmos-087.adoc#v19-87-0[Próximo Capítulo &#62;]