include::./index.adoc[]

[[v19-22-0]]
=== Salmos, 22
// naa ?, NAA - Nova Almeida Atualizada

[[v19-22-1]]

^<<v19-22-1,1>>^ Deus meu, Deus meu, por que me desamparaste? Por que se acham longe de minha salvação as palavras de meu gemido?

[[v19-22-2]]

^<<v19-22-2,2>>^ Deus meu, clamo de dia, e não me respondes; também de noite, porém não tenho sossego.

[[v19-22-3]]

^<<v19-22-3,3>>^ Contudo, tu és santo, entronizado entre os louvores de Israel.

[[v19-22-4]]

^<<v19-22-4,4>>^ Nossos pais confiaram em ti; confiaram, e tu os livraste.

[[v19-22-5]]

^<<v19-22-5,5>>^ A ti clamaram e escaparam; confiaram em ti e não foram envergonhados.

[[v19-22-6]]

^<<v19-22-6,6>>^ Mas eu sou verme e não um ser humano; afrontado pelos homens e desprezado pelo povo.

[[v19-22-7]]

^<<v19-22-7,7>>^ Todos os que me veem zombam de mim; fazem caretas e balançam a cabeça, dizendo:

[[v19-22-8]]

^<<v19-22-8,8>>^ "Confiou no Senhor ! Ele que o livre! Salve-o, pois nele tem prazer."

[[v19-22-9]]

^<<v19-22-9,9>>^ Contudo, tu és quem me fez nascer; e me preservaste, estando eu ainda ao seio de minha mãe.

[[v19-22-10]]

^<<v19-22-10,10>>^ A ti me entreguei desde o meu nascimento; desde o ventre de minha mãe, tu és o meu Deus.

[[v19-22-11]]

^<<v19-22-11,11>>^ Não te distancies de mim, porque a tribulação está próxima, e não há quem me ajude.

[[v19-22-12]]

^<<v19-22-12,12>>^ Muitos touros me cercam, fortes touros de Basã me rodeiam.

[[v19-22-13]]

^<<v19-22-13,13>>^ Contra mim abrem a boca, como faz o leão que despedaça e ruge.

[[v19-22-14]]

^<<v19-22-14,14>>^ Derramei-me como água, e todos os meus ossos se desconjuntaram; meu coração fez-se como cera, derreteu-se dentro de mim.

[[v19-22-15]]

^<<v19-22-15,15>>^ Secou-se o meu vigor, como um caco de barro, e a língua se me apega ao céu da boca; assim, me deitas no pó da morte.

[[v19-22-16]]

^<<v19-22-16,16>>^ Cães me cercam; um bando de malfeitores me rodeia; traspassaram-me as mãos e os pés.

[[v19-22-17]]

^<<v19-22-17,17>>^ Posso contar todos os meus ossos; os meus inimigos estão olhando para mim e me encarando.

[[v19-22-18]]

^<<v19-22-18,18>>^ Repartem entre si as minhas roupas e sobre a minha túnica lançam sortes.

[[v19-22-19]]

^<<v19-22-19,19>>^ Tu, porém, Senhor , não te afastes de mim; força minha, apressa-te em me socorrer.

[[v19-22-20]]

^<<v19-22-20,20>>^ Livra a minha alma da espada, e, das presas do cão, a minha vida.

[[v19-22-21]]

^<<v19-22-21,21>>^ Salva-me da boca do leão e dos chifres dos búfalos; sim, tu me respondes.

[[v19-22-22]]

^<<v19-22-22,22>>^ A meus irmãos declararei o teu nome; no meio da congregação eu te louvarei.

[[v19-22-23]]

^<<v19-22-23,23>>^ Louvem o Senhor , vocês que o temem; glorifiquem-no, todos vocês, descendência de Jacó; temam-no, todos vocês, posteridade de Israel.

[[v19-22-24]]

^<<v19-22-24,24>>^ Porque não desprezou nem detestou a dor do aflito, nem ocultou dele o seu rosto, mas o ouviu, quando lhe gritou por socorro.

[[v19-22-25]]

^<<v19-22-25,25>>^ De ti vem o meu louvor na grande congregação; cumprirei os meus votos na presença dos que o temem.

[[v19-22-26]]

^<<v19-22-26,26>>^ Os sofredores hão de comer e fartar-se; louvarão o Senhor aqueles que o buscam. Que o coração de vocês viva para sempre!

[[v19-22-27]]

^<<v19-22-27,27>>^ Os confins da terra se lembrarão do Senhor e a ele se converterão; diante dele se prostrarão todas as famílias das nações.

[[v19-22-28]]

^<<v19-22-28,28>>^ Pois do Senhor  é o reino, é ele quem governa as nações.

[[v19-22-29]]

^<<v19-22-29,29>>^ Todos os ricos da terra hão de comer e adorar, e todos os que descem ao pó se prostrarão diante dele, até aquele que não pode preservar a própria vida.

[[v19-22-30]]

^<<v19-22-30,30>>^ A posteridade o servirá, e se falará do Senhor à geração vindoura.

[[v19-22-31]]

^<<v19-22-31,31>>^ Virão e anunciarão a justiça dele; ao povo que há de nascer, contarão que foi ele quem o fez.

'''

xref:019-salmos/019-salmos-021.adoc#v19-21-0[&#60; Capítulo Anterior] | <<v19-22-0,Topo>> | xref:019-salmos/019-salmos-023.adoc#v19-23-0[Próximo Capítulo &#62;]