include::./index.adoc[]

[[v19-79-0]]
=== Salmos, 79
// naa ?, NAA - Nova Almeida Atualizada

[[v19-79-1]]

^<<v19-79-1,1>>^ Ó Deus, as nações invadiram a tua herança, profanaram o teu santo templo, reduziram Jerusalém a um montão de ruínas.

[[v19-79-2]]

^<<v19-79-2,2>>^ Deram os cadáveres dos teus servos por alimento às aves dos céus e a carne dos teus santos, às feras da terra.

[[v19-79-3]]

^<<v19-79-3,3>>^ Derramaram como água o sangue deles ao redor de Jerusalém, e não houve quem lhes desse sepultura.

[[v19-79-4]]

^<<v19-79-4,4>>^ Tornamo-nos objeto de deboche para os nossos vizinhos, de escárnio e de zombaria dos que nos rodeiam.

[[v19-79-5]]

^<<v19-79-5,5>>^ Até quando, Senhor ? Será para sempre a tua ira? Queimará como o fogo o teu zelo?

[[v19-79-6]]

^<<v19-79-6,6>>^ Derrama o teu furor sobre as nações que não te conhecem e sobre os reinos que não invocam o teu nome.

[[v19-79-7]]

^<<v19-79-7,7>>^ Porque eles devoraram Jacó e destruíram as suas moradas.

[[v19-79-8]]

^<<v19-79-8,8>>^ Não nos faças pagar pelas iniquidades de nossos pais; que as tuas misericórdias venham depressa ao nosso encontro, pois estamos muito abatidos.

[[v19-79-9]]

^<<v19-79-9,9>>^ Ajuda-nos, ó Deus e Salvador nosso, pela glória do teu nome; livra-nos e perdoa os nossos pecados, por amor do teu nome.

[[v19-79-10]]

^<<v19-79-10,10>>^ Por que diriam as nações: "Onde está o Deus deles?" Seja manifesta entre as nações e diante dos nossos olhos a vingança do sangue dos teus servos, que foi derramado.

[[v19-79-11]]

^<<v19-79-11,11>>^ Chegue à tua presença o gemido dos prisioneiros; com o teu grande poder, preserva os que estão condenados à morte.

[[v19-79-12]]

^<<v19-79-12,12>>^ Retribui, Senhor, aos nossos vizinhos sete vezes mais as afrontas com que te afrontaram.

[[v19-79-13]]

^<<v19-79-13,13>>^ Quanto a nós, teu povo e ovelhas do teu pasto, para sempre te daremos graças; de geração em geração proclamaremos os teus louvores.

'''

xref:019-salmos/019-salmos-078.adoc#v19-78-0[&#60; Capítulo Anterior] | <<v19-79-0,Topo>> | xref:019-salmos/019-salmos-080.adoc#v19-80-0[Próximo Capítulo &#62;]