include::./index.adoc[]

[[v19-3-0]]
=== Salmos, 3
// naa ?, NAA - Nova Almeida Atualizada

[[v19-3-1]]

^<<v19-3-1,1>>^ Senhor , como tem crescido o número dos meus adversários! São numerosos os que se levantam contra mim.

[[v19-3-2]]

^<<v19-3-2,2>>^ São muitos os que dizem de mim: "Não há em Deus salvação para ele."

[[v19-3-3]]

^<<v19-3-3,3>>^ Porém tu, Senhor , és o meu escudo protetor, és a minha glória e o que exalta a minha cabeça.

[[v19-3-4]]

^<<v19-3-4,4>>^ Com a minha voz clamo ao Senhor , e ele do seu santo monte me responde.

[[v19-3-5]]

^<<v19-3-5,5>>^ Eu me deito e pego no sono; acordo, porque o Senhor me sustenta.

[[v19-3-6]]

^<<v19-3-6,6>>^ Não tenho medo dos milhares que tomam posição contra mim de todos os lados.

[[v19-3-7]]

^<<v19-3-7,7>>^ Levanta-te, Senhor ! Salva-me, Deus meu, pois desferes um golpe no queixo de todos os meus inimigos e quebras os dentes dos ímpios.

[[v19-3-8]]

^<<v19-3-8,8>>^ Do Senhor  é a salvação. A tua bênção esteja sobre o teu povo!

'''

xref:019-salmos/019-salmos-002.adoc#v19-2-0[&#60; Capítulo Anterior] | <<v19-3-0,Topo>> | xref:019-salmos/019-salmos-004.adoc#v19-4-0[Próximo Capítulo &#62;]