include::./index.adoc[]

[[v19-78-0]]
=== Salmos, 78
// naa ?, NAA - Nova Almeida Atualizada

[[v19-78-1]]

^<<v19-78-1,1>>^ Meu povo, escute a minha lei; dê ouvidos às palavras da minha boca.

[[v19-78-2]]

^<<v19-78-2,2>>^ Abrirei os meus lábios para proferir parábolas e publicarei enigmas dos tempos antigos.

[[v19-78-3]]

^<<v19-78-3,3>>^ O que ouvimos e aprendemos, o que os nossos pais nos contaram,

[[v19-78-4]]

^<<v19-78-4,4>>^ não o encobriremos a seus filhos; contaremos à geração vindoura os louvores do Senhor , e o seu poder, e as maravilhas que fez.

[[v19-78-5]]

^<<v19-78-5,5>>^ Ele estabeleceu um testemunho em Jacó, e instituiu uma lei em Israel, e ordenou aos nossos pais que os transmitissem a seus filhos,

[[v19-78-6]]

^<<v19-78-6,6>>^ a fim de que a nova geração os conhecesse, e os filhos que ainda hão de nascer se levantassem e, por sua vez, os contassem aos seus descendentes;

[[v19-78-7]]

^<<v19-78-7,7>>^ para que pusessem a sua confiança em Deus e não se esquecessem dos feitos de Deus, mas lhe observassem os mandamentos;

[[v19-78-8]]

^<<v19-78-8,8>>^ e que não fossem, como seus pais, geração obstinada e rebelde, geração de coração inconstante, e cujo espírito não foi fiel a Deus.

[[v19-78-9]]

^<<v19-78-9,9>>^ Os filhos de Efraim, embora armados com arcos, bateram em retirada no dia do combate.

[[v19-78-10]]

^<<v19-78-10,10>>^ Não guardaram a aliança de Deus, não quiseram andar na sua lei;

[[v19-78-11]]

^<<v19-78-11,11>>^ esqueceram-se das suas obras e das maravilhas que lhes havia mostrado.

[[v19-78-12]]

^<<v19-78-12,12>>^ Deus fez prodígios na presença de seus pais na terra do Egito, no campo de Zoã.

[[v19-78-13]]

^<<v19-78-13,13>>^ Dividiu o mar e os fez passar por ele; fez parar as águas como um montão.

[[v19-78-14]]

^<<v19-78-14,14>>^ Durante o dia, os guiou com uma nuvem e de noite, com um clarão de fogo.

[[v19-78-15]]

^<<v19-78-15,15>>^ No deserto, fendeu rochas e lhes deu de beber abundantemente como de abismos.

[[v19-78-16]]

^<<v19-78-16,16>>^ Da pedra fez brotar torrentes, fez manar água como rios.

[[v19-78-17]]

^<<v19-78-17,17>>^ Mas, ainda assim, continuaram a pecar contra ele e se rebelaram, no deserto, contra o Altíssimo.

[[v19-78-18]]

^<<v19-78-18,18>>^ Tentaram a Deus no seu coração, pedindo alimento que lhes fosse do gosto.

[[v19-78-19]]

^<<v19-78-19,19>>^ Falaram contra Deus, dizendo: "Será que Deus pode preparar-nos uma mesa no deserto?

[[v19-78-20]]

^<<v19-78-20,20>>^ É verdade que ele feriu a rocha, e dela manaram águas, transbordaram as torrentes. Mas será que ele pode dar-nos pão também? Ou fornecer carne para o seu povo?"

[[v19-78-21]]

^<<v19-78-21,21>>^ Ouvindo isto, o Senhor  ficou indignado; acendeu-se fogo contra Jacó, e também se levantou o seu furor contra Israel,

[[v19-78-22]]

^<<v19-78-22,22>>^ porque não creram em Deus, nem confiaram na sua salvação.

[[v19-78-23]]

^<<v19-78-23,23>>^ Mesmo assim, deu ordens às nuvens e abriu as portas dos céus;

[[v19-78-24]]

^<<v19-78-24,24>>^ fez chover maná sobre eles, para alimentá-los, e lhes deu cereal do céu.

[[v19-78-25]]

^<<v19-78-25,25>>^ Todos comeram o pão dos anjos; ele enviou-lhes comida à vontade.

[[v19-78-26]]

^<<v19-78-26,26>>^ Fez soprar no céu o vento do Oriente e pelo seu poder conduziu o vento do Sul.

[[v19-78-27]]

^<<v19-78-27,27>>^ Também fez chover sobre eles carne como poeira e aves numerosas como a areia do mar.

[[v19-78-28]]

^<<v19-78-28,28>>^ Fez com que caíssem no meio do arraial deles, ao redor de suas tendas.

[[v19-78-29]]

^<<v19-78-29,29>>^ Então comeram e se fartaram a valer; pois lhes fez o que desejavam.

[[v19-78-30]]

^<<v19-78-30,30>>^ Porém não reprimiram o apetite. Ainda tinham o alimento na boca,

[[v19-78-31]]

^<<v19-78-31,31>>^ quando se elevou contra eles a ira de Deus, e entre os seus mais robustos semeou a morte, e prostrou os jovens de Israel.

[[v19-78-32]]

^<<v19-78-32,32>>^ Apesar de tudo isso, continuaram a pecar e não creram nas maravilhas de Deus.

[[v19-78-33]]

^<<v19-78-33,33>>^ Por isso, ele fez com que os seus dias se dissipassem num sopro e os seus anos, em súbito terror.

[[v19-78-34]]

^<<v19-78-34,34>>^ Quando os fazia morrer, eles o buscavam; arrependidos, procuravam Deus.

[[v19-78-35]]

^<<v19-78-35,35>>^ Lembravam-se de que Deus era a sua rocha e o Deus Altíssimo, o seu Redentor.

[[v19-78-36]]

^<<v19-78-36,36>>^ Lisonjeavam-no, porém de boca, e com a língua lhe mentiam.

[[v19-78-37]]

^<<v19-78-37,37>>^ Porque o coração deles não era firme para com ele, nem foram fiéis à sua aliança.

[[v19-78-38]]

^<<v19-78-38,38>>^ Ele, porém, que é misericordioso, perdoa a iniquidade e não destrói; muitas vezes desvia a sua ira e não desperta toda a sua indignação.

[[v19-78-39]]

^<<v19-78-39,39>>^ Lembra-se de que eles são simples mortais, vento que passa e não volta mais.

[[v19-78-40]]

^<<v19-78-40,40>>^ Quantas vezes se rebelaram contra ele no deserto e nos lugares áridos lhe causaram tristeza!

[[v19-78-41]]

^<<v19-78-41,41>>^ Tornaram a pôr Deus à prova, ofenderam o Santo de Israel.

[[v19-78-42]]

^<<v19-78-42,42>>^ Não se lembraram do poder dele, nem do dia em que os resgatou do adversário;

[[v19-78-43]]

^<<v19-78-43,43>>^ de como no Egito ele operou os seus sinais e os seus prodígios, no campo de Zoã;

[[v19-78-44]]

^<<v19-78-44,44>>^ e transformou em sangue os rios deles, para que das suas correntes não bebessem.

[[v19-78-45]]

^<<v19-78-45,45>>^ Enviou contra eles enxames de moscas que os devorassem e rãs que os destruíssem.

[[v19-78-46]]

^<<v19-78-46,46>>^ Entregou às lagartas as suas colheitas e aos gafanhotos, o fruto do seu trabalho.

[[v19-78-47]]

^<<v19-78-47,47>>^ Com chuvas de pedra lhes destruiu as vinhas e os seus sicômoros, com geada.

[[v19-78-48]]

^<<v19-78-48,48>>^ Entregou ao granizo o gado deles e aos raios, os seus rebanhos.

[[v19-78-49]]

^<<v19-78-49,49>>^ Lançou contra eles o furor da sua ira: cólera, indignação e calamidade, legião de anjos portadores de males.

[[v19-78-50]]

^<<v19-78-50,50>>^ Deu livre curso à sua ira; não poupou da morte a alma deles, mas entregou a vida deles à peste.

[[v19-78-51]]

^<<v19-78-51,51>>^ Matou todos os primogênitos no Egito, as primícias do vigor nas tendas de Cam.

[[v19-78-52]]

^<<v19-78-52,52>>^ Fez sair o seu povo como ovelhas e o guiou pelo deserto, como um rebanho.

[[v19-78-53]]

^<<v19-78-53,53>>^ Dirigiu-o com segurança, e não tiveram medo, ao passo que o mar submergiu os seus inimigos.

[[v19-78-54]]

^<<v19-78-54,54>>^ Levou-os até a sua terra santa, até o monte que a sua mão direita adquiriu.

[[v19-78-55]]

^<<v19-78-55,55>>^ Da presença deles expulsou as nações, cuja região repartiu com eles por herança; e nas suas tendas fez habitar as tribos de Israel.

[[v19-78-56]]

^<<v19-78-56,56>>^ Ainda assim, tentaram o Deus Altíssimo, e a ele resistiram, e não lhe guardaram os testemunhos.

[[v19-78-57]]

^<<v19-78-57,57>>^ Tornaram atrás e foram infiéis como os seus pais; desviaram-se como um arco enganoso.

[[v19-78-58]]

^<<v19-78-58,58>>^ Pois o provocaram à ira com os seus lugares altos e com as suas imagens de escultura despertaram o seu ciúme.

[[v19-78-59]]

^<<v19-78-59,59>>^ Deus ouviu isso e se indignou; rejeitou completamente o povo de Israel.

[[v19-78-60]]

^<<v19-78-60,60>>^ Por isso, abandonou o tabernáculo de Siló, a tenda de sua morada aqui na terra,

[[v19-78-61]]

^<<v19-78-61,61>>^ e passou a arca da aliança ao cativeiro, e a sua glória, à mão do adversário.

[[v19-78-62]]

^<<v19-78-62,62>>^ Entregou o seu povo à espada e se encolerizou contra a sua própria herança.

[[v19-78-63]]

^<<v19-78-63,63>>^ O fogo devorou os jovens deles, e as suas donzelas não tiveram canto nupcial.

[[v19-78-64]]

^<<v19-78-64,64>>^ Os seus sacerdotes caíram à espada, e as suas viúvas não fizeram lamentações.

[[v19-78-65]]

^<<v19-78-65,65>>^ Então o Senhor despertou como de um sono, como um valente que grita excitado pelo vinho;

[[v19-78-66]]

^<<v19-78-66,66>>^ fez recuar a golpes os seus adversários e os entregou a perpétuo desprezo.

[[v19-78-67]]

^<<v19-78-67,67>>^ Além disso, rejeitou a tenda de José e não elegeu a tribo de Efraim.

[[v19-78-68]]

^<<v19-78-68,68>>^ Pelo contrário, escolheu a tribo de Judá, o monte Sião, que ele amava.

[[v19-78-69]]

^<<v19-78-69,69>>^ E construiu o seu santuário durável como os céus e firme como a terra que estabeleceu para sempre.

[[v19-78-70]]

^<<v19-78-70,70>>^ Também escolheu o seu servo Davi, e o tirou do aprisco das ovelhas,

[[v19-78-71]]

^<<v19-78-71,71>>^ do cuidado das ovelhas e suas crias, para ser o pastor de Jacó, seu povo, e de Israel, sua herança.

[[v19-78-72]]

^<<v19-78-72,72>>^ E ele os apascentou segundo a integridade do seu coração e os dirigiu com sábias mãos.

'''

xref:019-salmos/019-salmos-077.adoc#v19-77-0[&#60; Capítulo Anterior] | <<v19-78-0,Topo>> | xref:019-salmos/019-salmos-079.adoc#v19-79-0[Próximo Capítulo &#62;]