include::./index.adoc[]

[[v19-92-0]]
=== Salmos, 92
// naa ?, NAA - Nova Almeida Atualizada

[[v19-92-1]]

^<<v19-92-1,1>>^ Bom é render graças ao Senhor e cantar louvores ao teu nome, ó Altíssimo,

[[v19-92-2]]

^<<v19-92-2,2>>^ anunciar de manhã a tua misericórdia e, durante as noites, a tua fidelidade,

[[v19-92-3]]

^<<v19-92-3,3>>^ com instrumentos de dez cordas, ao som da lira e com a solenidade da harpa.

[[v19-92-4]]

^<<v19-92-4,4>>^ Pois me alegraste, Senhor , com os teus feitos; exultarei nas obras das tuas mãos.

[[v19-92-5]]

^<<v19-92-5,5>>^ Como são grandes, Senhor , as tuas obras! Os teus pensamentos, que profundos!

[[v19-92-6]]

^<<v19-92-6,6>>^ O tolo não compreende, e o insensato não percebe isto:

[[v19-92-7]]

^<<v19-92-7,7>>^ ainda que os ímpios brotem como a erva, e floresçam todos os que praticam a iniquidade, serão destruídos para sempre.

[[v19-92-8]]

^<<v19-92-8,8>>^ Mas tu, Senhor , és o Altíssimo eternamente.

[[v19-92-9]]

^<<v19-92-9,9>>^ Eis que os teus inimigos, Senhor , eis que os teus inimigos perecerão; serão dispersos todos os que praticam a iniquidade.

[[v19-92-10]]

^<<v19-92-10,10>>^ Porém tu exaltas o meu poder como o do boi selvagem; derramas sobre mim o óleo fresco.

[[v19-92-11]]

^<<v19-92-11,11>>^ Os meus olhos veem a derrota dos inimigos que me espreitam, e os meus ouvidos escutam os gritos dos malfeitores que contra mim se levantam.

[[v19-92-12]]

^<<v19-92-12,12>>^ O justo florescerá como a palmeira, crescerá como o cedro no Líbano.

[[v19-92-13]]

^<<v19-92-13,13>>^ Plantados na Casa do Senhor , florescerão nos átrios do nosso Deus.

[[v19-92-14]]

^<<v19-92-14,14>>^ Na velhice ainda darão frutos, serão cheios de seiva e de verdor,

[[v19-92-15]]

^<<v19-92-15,15>>^ para anunciar que o Senhor  é reto. Ele é a minha rocha, e nele não há injustiça.

'''

xref:019-salmos/019-salmos-091.adoc#v19-91-0[&#60; Capítulo Anterior] | <<v19-92-0,Topo>> | xref:019-salmos/019-salmos-093.adoc#v19-93-0[Próximo Capítulo &#62;]