include::./index.adoc[]

[[v19-6-0]]
=== Salmos, 6
// naa ?, NAA - Nova Almeida Atualizada

[[v19-6-1]]

^<<v19-6-1,1>>^ Senhor , não me repreendas na tua ira, nem me castigues no teu furor.

[[v19-6-2]]

^<<v19-6-2,2>>^ Tem compaixão de mim, Senhor , porque eu me sinto debilitado; sara-me, Senhor , porque os meus ossos estão abalados.

[[v19-6-3]]

^<<v19-6-3,3>>^ Também a minha alma está profundamente perturbada; mas tu, Senhor , até quando?

[[v19-6-4]]

^<<v19-6-4,4>>^ Volta-te, Senhor , e socorre-me; salva-me por tua graça.

[[v19-6-5]]

^<<v19-6-5,5>>^ Pois, na morte, não há recordação de ti; no sepulcro, quem te dará louvor?

[[v19-6-6]]

^<<v19-6-6,6>>^ Estou cansado de tanto gemer; todas as noites faço nadar o meu leito, de minhas lágrimas o alago.

[[v19-6-7]]

^<<v19-6-7,7>>^ De tristeza os meus olhos se consomem, envelhecem por causa de todos os meus adversários.

[[v19-6-8]]

^<<v19-6-8,8>>^ Afastem-se de mim, todos vocês que praticam a iniquidade, porque o Senhor  ouviu a voz do meu lamento;

[[v19-6-9]]

^<<v19-6-9,9>>^ o Senhor  ouviu a minha súplica; o Senhor  acolhe a minha oração.

[[v19-6-10]]

^<<v19-6-10,10>>^ Sejam envergonhados e fiquem extremamente perturbados todos os meus inimigos; retirem-se, num instante, cobertos de vergonha.

'''

xref:019-salmos/019-salmos-005.adoc#v19-5-0[&#60; Capítulo Anterior] | <<v19-6-0,Topo>> | xref:019-salmos/019-salmos-007.adoc#v19-7-0[Próximo Capítulo &#62;]