include::./index.adoc[]

[[v19-109-0]]
=== Salmos, 109
// naa ?, NAA - Nova Almeida Atualizada

[[v19-109-1]]

^<<v19-109-1,1>>^ Ó Deus do meu louvor, não te cales!

[[v19-109-2]]

^<<v19-109-2,2>>^ Pois contra mim se abriram lábios maldosos e fraudulentos; com língua mentirosa falam contra mim.

[[v19-109-3]]

^<<v19-109-3,3>>^ Cercam-me com palavras odiosas e me atacam sem motivo.

[[v19-109-4]]

^<<v19-109-4,4>>^ Em paga do meu amor, me hostilizam; eu, porém, oro.

[[v19-109-5]]

^<<v19-109-5,5>>^ Pagaram-me o bem com o mal; o amor, com ódio.

[[v19-109-6]]

^<<v19-109-6,6>>^ Suscita contra ele um ímpio, e que à sua direita esteja um acusador.

[[v19-109-7]]

^<<v19-109-7,7>>^ Quando o julgarem, que ele seja condenado; e que a oração dele seja tida como pecado.

[[v19-109-8]]

^<<v19-109-8,8>>^ Sejam poucos os seus dias, e outro tome o seu encargo.

[[v19-109-9]]

^<<v19-109-9,9>>^ Fiquem órfãos os seus filhos, e viúva, a sua esposa.

[[v19-109-10]]

^<<v19-109-10,10>>^ Andem errantes os seus filhos e mendiguem; e sejam expulsos das ruínas de suas casas.

[[v19-109-11]]

^<<v19-109-11,11>>^ Que um credor se aposse de tudo o que ele tem; que estranhos saqueiem o fruto do seu trabalho.

[[v19-109-12]]

^<<v19-109-12,12>>^ Ninguém tenha misericórdia dele, nem haja quem se compadeça dos seus filhos órfãos.

[[v19-109-13]]

^<<v19-109-13,13>>^ Desapareça a sua posteridade, e que o seu nome se extinga na geração seguinte.

[[v19-109-14]]

^<<v19-109-14,14>>^ Que a iniquidade de seus pais fique viva na memória do Senhor , e não se apague o pecado de sua mãe.

[[v19-109-15]]

^<<v19-109-15,15>>^ Permaneçam ante os olhos do Senhor , para que faça desaparecer da terra a sua memória.

[[v19-109-16]]

^<<v19-109-16,16>>^ Porque ele não se lembrou de usar de misericórdia, mas perseguiu o pobre e o necessitado, bem como o quebrantado de coração, para os entregar à morte.

[[v19-109-17]]

^<<v19-109-17,17>>^ Amou a maldição: que ela o apanhe! Não quis a bênção: que ela se afaste dele.

[[v19-109-18]]

^<<v19-109-18,18>>^ Vestiu-se de maldição como de uma túnica: que ela penetre, como água, no seu interior, e nos seus ossos, como azeite.

[[v19-109-19]]

^<<v19-109-19,19>>^ Seja para ele como a roupa que o cobre e como o cinto com que sempre se cinge.

[[v19-109-20]]

^<<v19-109-20,20>>^ Que esta seja, da parte do Senhor , a recompensa dos que me acusam e dos que falam mal de mim.

[[v19-109-21]]

^<<v19-109-21,21>>^ Mas tu, Senhor  Deus, age por mim, por amor do teu nome; livra-me, porque é boa a tua misericórdia.

[[v19-109-22]]

^<<v19-109-22,22>>^ Porque sou pobre e necessitado e, dentro de mim, sinto ferido o coração.

[[v19-109-23]]

^<<v19-109-23,23>>^ Vou passando, como a sombra que declina; sou atirado para longe, como um gafanhoto.

[[v19-109-24]]

^<<v19-109-24,24>>^ De tanto jejuar, os meus joelhos vacilam, e o meu corpo definha de magreza.

[[v19-109-25]]

^<<v19-109-25,25>>^ Tornei-me para eles objeto de zombaria; quando me veem, balançam a cabeça.

[[v19-109-26]]

^<<v19-109-26,26>>^ Socorre-me, Senhor , meu Deus! Salva-me segundo a tua misericórdia.

[[v19-109-27]]

^<<v19-109-27,27>>^ Para que saibam que isso vem das tuas mãos; que tu, Senhor , o fizeste.

[[v19-109-28]]

^<<v19-109-28,28>>^ Amaldiçoem eles, mas tu, abençoa. Sejam envergonhados os que se levantam contra mim; alegre-se, porém, o teu servo.

[[v19-109-29]]

^<<v19-109-29,29>>^ Cubram-se de vexame os meus adversários, e a sua própria vergonha os envolva como um manto.

[[v19-109-30]]

^<<v19-109-30,30>>^ Muitas graças darei ao Senhor com os meus lábios; eu o louvarei no meio da multidão;

[[v19-109-31]]

^<<v19-109-31,31>>^ porque ele se põe à direita do pobre, para o livrar daqueles que o condenam.

'''

xref:019-salmos/019-salmos-108.adoc#v19-108-0[&#60; Capítulo Anterior] | <<v19-109-0,Topo>> | xref:019-salmos/019-salmos-110.adoc#v19-110-0[Próximo Capítulo &#62;]