include::./index.adoc[]

[[v19-51-0]]
=== Salmos, 51
// naa ?, NAA - Nova Almeida Atualizada

[[v19-51-1]]

^<<v19-51-1,1>>^ Compadece-te de mim, ó Deus, segundo a tua benignidade; e, segundo a multidão das tuas misericórdias, apaga as minhas transgressões.

[[v19-51-2]]

^<<v19-51-2,2>>^ Lava-me completamente da minha iniquidade e purifica-me do meu pecado.

[[v19-51-3]]

^<<v19-51-3,3>>^ Pois eu conheço as minhas transgressões, e o meu pecado está sempre diante de mim.

[[v19-51-4]]

^<<v19-51-4,4>>^ Pequei contra ti, contra ti somente, e fiz o que é mau aos teus olhos, de maneira que serás tido por justo no teu falar e puro no teu julgar.

[[v19-51-5]]

^<<v19-51-5,5>>^ Eu nasci na iniquidade, e em pecado me concebeu a minha mãe.

[[v19-51-6]]

^<<v19-51-6,6>>^ Eis que te agradas da verdade no íntimo e no oculto me fazes conhecer a sabedoria.

[[v19-51-7]]

^<<v19-51-7,7>>^ Purifica-me com hissopo, e ficarei limpo; lava-me, e ficarei mais alvo do que a neve.

[[v19-51-8]]

^<<v19-51-8,8>>^ Faze-me ouvir júbilo e alegria, para que exultem os ossos que esmagaste.

[[v19-51-9]]

^<<v19-51-9,9>>^ Esconde o teu rosto dos meus pecados e apaga todas as minhas iniquidades.

[[v19-51-10]]

^<<v19-51-10,10>>^ Cria em mim, ó Deus, um coração puro e renova dentro de mim um espírito inabalável.

[[v19-51-11]]

^<<v19-51-11,11>>^ Não me lances fora da tua presença, nem me retires o teu Santo Espírito.

[[v19-51-12]]

^<<v19-51-12,12>>^ Restitui-me a alegria da tua salvação e sustenta-me com um espírito voluntário.

[[v19-51-13]]

^<<v19-51-13,13>>^ Então ensinarei aos transgressores os teus caminhos, e os pecadores se converterão a ti.

[[v19-51-14]]

^<<v19-51-14,14>>^ Livra-me dos crimes de sangue, ó Deus, Deus da minha salvação, e a minha língua exaltará a tua justiça.

[[v19-51-15]]

^<<v19-51-15,15>>^ Abre, Senhor, os meus lábios, e a minha boca manifestará o teu louvor.

[[v19-51-16]]

^<<v19-51-16,16>>^ Pois não te agradas de sacrifícios; do contrário, eu os ofereceria; e não tens prazer em holocaustos.

[[v19-51-17]]

^<<v19-51-17,17>>^ Sacrifício agradável a Deus é o espírito quebrantado; coração quebrantado e contrito, não o desprezarás, ó Deus.

[[v19-51-18]]

^<<v19-51-18,18>>^ Faze bem a Sião, segundo a tua boa vontade; edifica as muralhas de Jerusalém.

[[v19-51-19]]

^<<v19-51-19,19>>^ Então te agradarás dos sacrifícios de justiça, dos holocaustos e das ofertas queimadas; e sobre o teu altar serão oferecidos novilhos.

'''

xref:019-salmos/019-salmos-050.adoc#v19-50-0[&#60; Capítulo Anterior] | <<v19-51-0,Topo>> | xref:019-salmos/019-salmos-052.adoc#v19-52-0[Próximo Capítulo &#62;]