include::./index.adoc[]

[[v19-16-0]]
=== Salmos, 16
// naa ?, NAA - Nova Almeida Atualizada

[[v19-16-1]]

^<<v19-16-1,1>>^ Guarda-me, ó Deus, porque em ti me refugio.

[[v19-16-2]]

^<<v19-16-2,2>>^ Digo ao Senhor : "Tu és o meu Senhor; outro bem não possuo, senão a ti somente."

[[v19-16-3]]

^<<v19-16-3,3>>^ Quanto aos santos que há na terra, eles são os notáveis nos quais tenho todo o meu prazer.

[[v19-16-4]]

^<<v19-16-4,4>>^ Muitas serão as dores dos que trocam o Senhor por outros deuses; não oferecerei as suas libações de sangue, e os meus lábios não pronunciarão os nomes deles.

[[v19-16-5]]

^<<v19-16-5,5>>^ O Senhor  é a porção da minha herança e o meu cálice; tu sustentas a minha sorte.

[[v19-16-6]]

^<<v19-16-6,6>>^ As minhas divisas caíram em lugares agradáveis; é linda a minha herança.

[[v19-16-7]]

^<<v19-16-7,7>>^ Bendigo o Senhor , que me aconselha; pois até durante a noite o meu coração me ensina.

[[v19-16-8]]

^<<v19-16-8,8>>^ Tenho o Senhor  sempre diante de mim; estando ele à minha direita, não serei abalado.

[[v19-16-9]]

^<<v19-16-9,9>>^ Por isso o meu coração se alegra e o meu espírito exulta; até o meu corpo repousará seguro.

[[v19-16-10]]

^<<v19-16-10,10>>^ Pois não deixarás a minha alma na morte, nem permitirás que o teu Santo veja corrupção.

[[v19-16-11]]

^<<v19-16-11,11>>^ Tu me farás ver os caminhos da vida; na tua presença há plenitude de alegria, à tua direita, há delícias perpetuamente.

'''

xref:019-salmos/019-salmos-015.adoc#v19-15-0[&#60; Capítulo Anterior] | <<v19-16-0,Topo>> | xref:019-salmos/019-salmos-017.adoc#v19-17-0[Próximo Capítulo &#62;]