include::./index.adoc[]

[[v19-60-0]]
=== Salmos, 60
// naa ?, NAA - Nova Almeida Atualizada

[[v19-60-1]]

^<<v19-60-1,1>>^ Ó Deus, tu nos rejeitaste e nos dispersaste. Tens estado indignado, mas agora restabelece-nos!

[[v19-60-2]]

^<<v19-60-2,2>>^ Abalaste a terra e a fendeste; repara-lhe as brechas, pois ela ameaça ruir.

[[v19-60-3]]

^<<v19-60-3,3>>^ Fizeste o teu povo experimentar reveses e nos deste a beber um vinho que atordoa.

[[v19-60-4]]

^<<v19-60-4,4>>^ Deste um estandarte aos que te temem, para fugirem de diante do arco.

[[v19-60-5]]

^<<v19-60-5,5>>^ Para que os teus amados sejam livres, salva-nos com a tua mão direita e responde-nos.

[[v19-60-6]]

^<<v19-60-6,6>>^ Deus falou na sua santidade: "Exultarei; dividirei Siquém e medirei o vale de Sucote.

[[v19-60-7]]

^<<v19-60-7,7>>^ Gileade é meu e meu é também Manassés; Efraim é o meu capacete; Judá é o meu cetro.

[[v19-60-8]]

^<<v19-60-8,8>>^ Moabe, porém, é a minha bacia de lavar; sobre Edom atirarei a minha sandália; sobre a Filístia jubilarei."

[[v19-60-9]]

^<<v19-60-9,9>>^ Quem me conduzirá à cidade fortificada? Quem me guiará até Edom?

[[v19-60-10]]

^<<v19-60-10,10>>^ Não nos rejeitaste, ó Deus? Tu não sais, ó Deus, com os nossos exércitos!

[[v19-60-11]]

^<<v19-60-11,11>>^ Presta-nos auxílio na angústia, pois vão é o socorro humano.

[[v19-60-12]]

^<<v19-60-12,12>>^ Em Deus faremos proezas, porque ele mesmo pisará os nossos adversários.

'''

xref:019-salmos/019-salmos-059.adoc#v19-59-0[&#60; Capítulo Anterior] | <<v19-60-0,Topo>> | xref:019-salmos/019-salmos-061.adoc#v19-61-0[Próximo Capítulo &#62;]