include::./index.adoc[]

[[v19-46-0]]
=== Salmos, 46
// naa ?, NAA - Nova Almeida Atualizada

[[v19-46-1]]

^<<v19-46-1,1>>^ Deus é o nosso refúgio e fortaleza, socorro bem presente nas tribulações.

[[v19-46-2]]

^<<v19-46-2,2>>^ Portanto, não temeremos, ainda que a terra se transtorne e os montes se abalem no seio dos mares;

[[v19-46-3]]

^<<v19-46-3,3>>^ ainda que as águas tumultuem e espumejem e na sua fúria os montes estremeçam.

[[v19-46-4]]

^<<v19-46-4,4>>^ Há um rio, cujas correntes alegram a cidade de Deus, o santuário das moradas do Altíssimo.

[[v19-46-5]]

^<<v19-46-5,5>>^ Deus está no meio dela; jamais será abalada. Deus a ajudará desde o romper da manhã.

[[v19-46-6]]

^<<v19-46-6,6>>^ Bramam nações, reinos se abalam. Deus faz ouvir a sua voz, e a terra se dissolve.

[[v19-46-7]]

^<<v19-46-7,7>>^ O Senhor  dos Exércitos está conosco; o Deus de Jacó é o nosso refúgio.

[[v19-46-8]]

^<<v19-46-8,8>>^ Venham contemplar as obras do Senhor , que tem feito desolações na terra.

[[v19-46-9]]

^<<v19-46-9,9>>^ Ele faz cessar as guerras até os confins do mundo, quebra o arco e despedaça a lança; queima os carros no fogo.

[[v19-46-10]]

^<<v19-46-10,10>>^ Aquietem-se e saibam que eu sou Deus; sou exaltado entre as nações, sou exaltado na terra.

[[v19-46-11]]

^<<v19-46-11,11>>^ O Senhor  dos Exércitos está conosco; o Deus de Jacó é o nosso refúgio.

'''

xref:019-salmos/019-salmos-045.adoc#v19-45-0[&#60; Capítulo Anterior] | <<v19-46-0,Topo>> | xref:019-salmos/019-salmos-047.adoc#v19-47-0[Próximo Capítulo &#62;]