include::./index.adoc[]

[[v55-2-0]]
=== 2 Timóteo, 2
// naa ?, NAA - Nova Almeida Atualizada

[[v55-2-1]]

^<<v55-2-1,1>>^ Quanto a você, meu filho, fortifique-se na graça que há em Cristo Jesus.

[[v55-2-2]]

^<<v55-2-2,2>>^ E o que você ouviu de mim na presença de muitas testemunhas, isso mesmo transmita a homens fiéis, idôneos para instruir a outros.

[[v55-2-3]]

^<<v55-2-3,3>>^ Participe dos meus sofrimentos como bom soldado de Cristo Jesus.

[[v55-2-4]]

^<<v55-2-4,4>>^ Nenhum soldado em serviço se envolve em negócios desta vida, porque o seu objetivo é agradar aquele que o recrutou.

[[v55-2-5]]

^<<v55-2-5,5>>^ Igualmente, o atleta não é coroado se não competir segundo as regras.

[[v55-2-6]]

^<<v55-2-6,6>>^ O lavrador que trabalha deve ser o primeiro a participar dos frutos.

[[v55-2-7]]

^<<v55-2-7,7>>^ Pense bem no que acabo de dizer, porque o Senhor dará a você compreensão em todas as coisas.

[[v55-2-8]]

^<<v55-2-8,8>>^ Lembre-se de Jesus Cristo, ressuscitado dentre os mortos, descendente de Davi, segundo o meu evangelho.

[[v55-2-9]]

^<<v55-2-9,9>>^ É por ele que estou sofrendo até algemas, como malfeitor. Mas a palavra de Deus não está algemada.

[[v55-2-10]]

^<<v55-2-10,10>>^ Por esta razão, tudo suporto por causa dos eleitos, para que também eles obtenham a salvação que está em Cristo Jesus, com glória eterna.

[[v55-2-11]]

^<<v55-2-11,11>>^ Fiel é esta palavra: "Se já morremos com ele, também viveremos com ele;

[[v55-2-12]]

^<<v55-2-12,12>>^ se perseveramos, também com ele reinaremos; se o negamos, ele, por sua vez, nos negará;

[[v55-2-13]]

^<<v55-2-13,13>>^ se somos infiéis, ele permanece fiel, pois de maneira nenhuma pode negar a si mesmo."

[[v55-2-14]]

^<<v55-2-14,14>>^ Relembre a todos essas coisas, dando testemunho solene diante de Deus, para que evitem brigas a respeito de palavras, pois isso não serve para nada, a não ser para prejudicar os ouvintes.

[[v55-2-15]]

^<<v55-2-15,15>>^ Procure apresentar-se a Deus aprovado, como obreiro que não tem de que se envergonhar, que maneja bem a palavra da verdade.

[[v55-2-16]]

^<<v55-2-16,16>>^ Evite, igualmente, os falatórios inúteis e profanos, pois os que se entregam a isso avançarão cada vez mais na impiedade.

[[v55-2-17]]

^<<v55-2-17,17>>^ Além disso, a linguagem deles corrói como câncer. Entre esses estão Himeneu e Fileto,

[[v55-2-18]]

^<<v55-2-18,18>>^ que se desviaram da verdade, dizendo que a ressurreição já aconteceu, e estão pervertendo alguns em sua fé.

[[v55-2-19]]

^<<v55-2-19,19>>^ Entretanto, o firme fundamento de Deus permanece, tendo este selo: "O Senhor conhece os que lhe pertencem." E mais: "Afaste-se da injustiça todo aquele que professa o nome do Senhor."

[[v55-2-20]]

^<<v55-2-20,20>>^ Ora, numa grande casa não há somente utensílios de ouro e de prata; há também de madeira e de barro. Alguns, para honra; outros, porém, para desonra.

[[v55-2-21]]

^<<v55-2-21,21>>^ Assim, pois, se alguém se purificar destes erros, será utensílio para honra, santificado e útil ao seu senhor, estando preparado para toda boa obra.

[[v55-2-22]]

^<<v55-2-22,22>>^ Fuja das paixões da mocidade. Siga a justiça, a fé, o amor e a paz com os que, de coração puro, invocam o Senhor.

[[v55-2-23]]

^<<v55-2-23,23>>^ Evite as discussões insensatas e absurdas, pois você sabe que elas só provocam brigas.

[[v55-2-24]]

^<<v55-2-24,24>>^ O servo do Senhor não deve andar metido em brigas, mas deve ser brando para com todos, apto para ensinar, paciente,

[[v55-2-25]]

^<<v55-2-25,25>>^ disciplinando com mansidão os que se opõem a ele, na expectativa de que Deus lhes conceda não só o arrependimento para conhecerem a verdade,

[[v55-2-26]]

^<<v55-2-26,26>>^ mas também o retorno à sensatez, a fim de que se livrem dos laços do diabo, que os prendeu para fazerem o que ele quer.

'''

xref:055-2-timoteo/055-2-timoteo-001.adoc#v55-1-0[&#60; Capítulo Anterior] | <<v55-2-0,Topo>> | xref:055-2-timoteo/055-2-timoteo-003.adoc#v55-3-0[Próximo Capítulo &#62;]