include::./index.adoc[]

[[v55-4-0]]
=== 2 Timóteo, 4
// naa ?, NAA - Nova Almeida Atualizada

[[v55-4-1]]

^<<v55-4-1,1>>^ Diante de Deus e de Cristo Jesus, que há de julgar vivos e mortos, pela sua manifestação e pelo seu Reino, peço a você com insistência

[[v55-4-2]]

^<<v55-4-2,2>>^ que pregue a palavra, insista, quer seja oportuno, quer não, corrija, repreenda, exorte com toda a paciência e doutrina.

[[v55-4-3]]

^<<v55-4-3,3>>^ Pois virá o tempo em que não suportarão a sã doutrina; pelo contrário, se rodearão de mestres segundo as suas próprias cobiças, como que sentindo coceira nos ouvidos.

[[v55-4-4]]

^<<v55-4-4,4>>^ Eles se recusarão a dar ouvidos à verdade, entregando-se às fábulas.

[[v55-4-5]]

^<<v55-4-5,5>>^ Mas você seja sóbrio em todas as coisas, suporte as aflições, faça o trabalho de um evangelista, cumpra plenamente o seu ministério.

[[v55-4-6]]

^<<v55-4-6,6>>^ Quanto a mim, já estou sendo oferecido por libação, e o tempo da minha partida chegou.

[[v55-4-7]]

^<<v55-4-7,7>>^ Combati o bom combate, completei a carreira, guardei a fé.

[[v55-4-8]]

^<<v55-4-8,8>>^ Desde agora me está guardada a coroa da justiça, que o Senhor, reto juiz, me dará naquele Dia; e não somente a mim, mas também a todos os que amam a sua vinda.

[[v55-4-9]]

^<<v55-4-9,9>>^ Empenhe-se por vir até aqui o mais depressa possível.

[[v55-4-10]]

^<<v55-4-10,10>>^ Porque Demas, tendo amado o presente século, me abandonou e se foi para Tessalônica. Crescente foi para a Galácia. Tito foi para a Dalmácia.

[[v55-4-11]]

^<<v55-4-11,11>>^ Somente Lucas está comigo. Encontre Marcos e traga-o junto com você, pois me é útil para o ministério.

[[v55-4-12]]

^<<v55-4-12,12>>^ Quanto a Tíquico, mandei-o para Éfeso.

[[v55-4-13]]

^<<v55-4-13,13>>^ Quando você vier, traga a capa que deixei em Trôade, na casa de Carpo. Traga também os livros, especialmente os pergaminhos.

[[v55-4-14]]

^<<v55-4-14,14>>^ Alexandre, o ferreiro, me causou muitos males; o Senhor dará a retribuição de acordo com o que ele fez.

[[v55-4-15]]

^<<v55-4-15,15>>^ Tome cuidado com ele também você, porque resistiu fortemente às nossas palavras.

[[v55-4-16]]

^<<v55-4-16,16>>^ Na minha primeira defesa, ninguém foi a meu favor; todos me abandonaram. Que isto não lhes seja posto na conta!

[[v55-4-17]]

^<<v55-4-17,17>>^ Mas o Senhor esteve ao meu lado e me revestiu de forças, para que, através de mim, a pregação fosse plenamente cumprida, e todos os gentios a ouvissem. E fui libertado da boca do leão.

[[v55-4-18]]

^<<v55-4-18,18>>^ O Senhor me livrará também de toda obra maligna e me levará salvo para o seu Reino celestial. A ele, glória para todo o sempre. Amém!

[[v55-4-19]]

^<<v55-4-19,19>>^ Dê saudações a Prisca e Áquila, e à casa de Onesíforo.

[[v55-4-20]]

^<<v55-4-20,20>>^ Erasto ficou em Corinto. Quanto a Trófimo, deixei-o doente em Mileto.

[[v55-4-21]]

^<<v55-4-21,21>>^ Faça o possível para vir antes do inverno. Êubulo manda saudações; o mesmo fazem Prudente, Lino, Cláudia e todos os irmãos.

[[v55-4-22]]

^<<v55-4-22,22>>^ O Senhor esteja com o seu espírito. A graça esteja com vocês.

'''

xref:055-2-timoteo/055-2-timoteo-003.adoc#v55-3-0[&#60; Capítulo Anterior] | <<v55-4-0,Topo>> | xref:056-tito/056-tito-001.adoc#v56-1-0[Próximo Capítulo &#62;]