include::./index.adoc[]

[[v55-3-0]]
=== 2 Timóteo, 3
// naa ?, NAA - Nova Almeida Atualizada

[[v55-3-1]]

^<<v55-3-1,1>>^ Mas você precisa saber disto: nos últimos dias sobrevirão tempos difíceis.

[[v55-3-2]]

^<<v55-3-2,2>>^ Pois os seres humanos serão egoístas, avarentos, orgulhosos, arrogantes, blasfemadores, desobedientes aos pais, ingratos, ímpios,

[[v55-3-3]]

^<<v55-3-3,3>>^ sem afeição natural, implacáveis, caluniadores, sem domínio de si, cruéis, inimigos do bem,

[[v55-3-4]]

^<<v55-3-4,4>>^ traidores, atrevidos, convencidos, mais amigos dos prazeres do que amigos de Deus,

[[v55-3-5]]

^<<v55-3-5,5>>^ tendo forma de piedade, mas negando o poder dela. Fique longe também destes.

[[v55-3-6]]

^<<v55-3-6,6>>^ Pois entre estes se encontram os que se infiltram nas casas e conseguem cativar mulheres tolas, sobrecarregadas de pecados, que são levadas por todo tipo de desejos,

[[v55-3-7]]

^<<v55-3-7,7>>^ que estão sempre aprendendo e nunca conseguem chegar ao conhecimento da verdade.

[[v55-3-8]]

^<<v55-3-8,8>>^ E do mesmo modo que Janes e Jambres resistiram a Moisés, também estes resistem à verdade. São homens que têm a mente totalmente corrompida, reprovados quanto à fé.

[[v55-3-9]]

^<<v55-3-9,9>>^ Mas esses não irão longe, porque a insensatez deles ficará evidente a todos, como também aconteceu com a insensatez de Janes e Jambres.

[[v55-3-10]]

^<<v55-3-10,10>>^ Mas você tem seguido de perto o meu ensino, a minha conduta, o meu propósito, a minha fé, a minha paciência, o meu amor, a minha perseverança,

[[v55-3-11]]

^<<v55-3-11,11>>^ as minhas perseguições e os meus sofrimentos, os quais tive de enfrentar em Antioquia, Icônio e Listra. Quantas perseguições sofri! Porém o Senhor me livrou de todas elas.

[[v55-3-12]]

^<<v55-3-12,12>>^ Na verdade, todos os que querem viver piedosamente em Cristo Jesus serão perseguidos.

[[v55-3-13]]

^<<v55-3-13,13>>^ Mas os perversos e impostores irão de mal a pior, enganando e sendo enganados.

[[v55-3-14]]

^<<v55-3-14,14>>^ Quanto a você, permaneça naquilo que aprendeu e em que acredita firmemente, sabendo de quem você o aprendeu

[[v55-3-15]]

^<<v55-3-15,15>>^ e que, desde a infância, você conhece as sagradas letras, que podem torná-lo sábio para a salvação pela fé em Cristo Jesus.

[[v55-3-16]]

^<<v55-3-16,16>>^ Toda a Escritura é inspirada por Deus e útil para o ensino, para a repreensão, para a correção, para a educação na justiça,

[[v55-3-17]]

^<<v55-3-17,17>>^ a fim de que o servo de Deus seja perfeito e perfeitamente habilitado para toda boa obra.

'''

xref:055-2-timoteo/055-2-timoteo-002.adoc#v55-2-0[&#60; Capítulo Anterior] | <<v55-3-0,Topo>> | xref:055-2-timoteo/055-2-timoteo-004.adoc#v55-4-0[Próximo Capítulo &#62;]