include::./index.adoc[]

[[v55-1-0]]
=== 2 Timóteo, 1
// naa ?, NAA - Nova Almeida Atualizada

[[v55-1-1]]

^<<v55-1-1,1>>^ Paulo, apóstolo de Cristo Jesus pela vontade de Deus, conforme a promessa da vida em Cristo Jesus,

[[v55-1-2]]

^<<v55-1-2,2>>^ ao amado filho Timóteo. Que a graça, a misericórdia e a paz, da parte de Deus Pai e de Cristo Jesus, nosso Senhor, estejam com você.

[[v55-1-3]]

^<<v55-1-3,3>>^ Dou graças a Deus, a quem, desde os meus antepassados, sirvo com a consciência limpa, porque, sem cessar, lembro de você nas minhas orações, noite e dia.

[[v55-1-4]]

^<<v55-1-4,4>>^ Lembro das suas lágrimas e estou ansioso por ver você, para que eu transborde de alegria.

[[v55-1-5]]

^<<v55-1-5,5>>^ Lembro da sua fé sem fingimento, a mesma que, primeiramente, habitou em sua avó Loide e em sua mãe Eunice, e estou certo de que habita também em você.

[[v55-1-6]]

^<<v55-1-6,6>>^ Por esta razão, venho lembrar-lhe que reavive o dom de Deus que está em você pela imposição das minhas mãos.

[[v55-1-7]]

^<<v55-1-7,7>>^ Porque Deus não nos deu espírito de covardia, mas de poder, de amor e de moderação.

[[v55-1-8]]

^<<v55-1-8,8>>^ Portanto, não se envergonhe do testemunho de nosso Senhor, nem do seu prisioneiro, que sou eu. Pelo contrário, participe comigo dos sofrimentos a favor do evangelho, segundo o poder de Deus,

[[v55-1-9]]

^<<v55-1-9,9>>^ que nos salvou e nos chamou com santa vocação, não segundo as nossas obras, mas conforme a sua própria determinação e graça que nos foi dada em Cristo Jesus, antes dos tempos eternos,

[[v55-1-10]]

^<<v55-1-10,10>>^ e manifestada agora pelo aparecimento de nosso Salvador Cristo Jesus. Ele não só destruiu a morte, como trouxe à luz a vida e a imortalidade, mediante o evangelho.

[[v55-1-11]]

^<<v55-1-11,11>>^ Para este evangelho eu fui designado pregador, apóstolo e mestre

[[v55-1-12]]

^<<v55-1-12,12>>^ e, por isso, estou sofrendo estas coisas. Mas não me envergonho, porque sei em quem tenho crido e estou certo de que ele é poderoso para guardar aquilo que me foi confiado até aquele Dia.

[[v55-1-13]]

^<<v55-1-13,13>>^ Mantenha o padrão das sãs palavras que de mim você ouviu com fé e com o amor que há em Cristo Jesus.

[[v55-1-14]]

^<<v55-1-14,14>>^ Por meio do Espírito Santo, que habita em nós, guarde o bom tesouro que lhe foi confiado.

[[v55-1-15]]

^<<v55-1-15,15>>^ Você já deve estar ciente de que todos os da província da Ásia me abandonaram. Entre eles estão Fígelo e Hermógenes.

[[v55-1-16]]

^<<v55-1-16,16>>^ Que o Senhor conceda misericórdia à casa de Onesíforo, porque, muitas vezes, me deu ânimo e nunca se envergonhou das minhas algemas.

[[v55-1-17]]

^<<v55-1-17,17>>^ Pelo contrário, quando chegou a Roma, me procurou com persistência até me encontrar.

[[v55-1-18]]

^<<v55-1-18,18>>^ O Senhor lhe conceda que, naquele Dia, ache misericórdia da parte do Senhor. Você sabe, melhor do que eu, quantos serviços ele me prestou em Éfeso.

'''

xref:054-1-timoteo/054-1-timoteo-006.adoc#v54-6-0[&#60; Capítulo Anterior] | <<v55-1-0,Topo>> | xref:055-2-timoteo/055-2-timoteo-002.adoc#v55-2-0[Próximo Capítulo &#62;]