include::./index.adoc[]

[[v15-3-0]]
=== Esdras, 3
// naa ?, NAA - Nova Almeida Atualizada

[[v15-3-1]]

^<<v15-3-1,1>>^ Quando chegou o sétimo mês e os filhos de Israel já estavam morando nas suas cidades, o povo se reuniu, como um só homem, em Jerusalém.

[[v15-3-2]]

^<<v15-3-2,2>>^ Então levantou-se Jesua, filho de Jozadaque, e seus irmãos, sacerdotes, e Zorobabel, filho de Sealtiel, e seus irmãos e edificaram o altar do Deus de Israel, para oferecerem holocaustos sobre ele, como está escrito na Lei de Moisés, homem de Deus.

[[v15-3-3]]

^<<v15-3-3,3>>^ Firmaram o altar sobre as suas bases; e, apesar de estarem sob o terror dos povos de outras terras, ofereceram sobre ele holocaustos ao Senhor , de manhã e de tarde.

[[v15-3-4]]

^<<v15-3-4,4>>^ Celebraram a Festa dos Tabernáculos, como está escrito, e ofereceram holocaustos diários, segundo o número ordenado para cada dia.

[[v15-3-5]]

^<<v15-3-5,5>>^ Depois disto, ofereceram o holocausto contínuo e os sacrifícios das Festas da Lua Nova e de todas as festas fixas do Senhor , bem como os sacrifícios dos que traziam ofertas voluntárias ao Senhor .

[[v15-3-6]]

^<<v15-3-6,6>>^ Desde o primeiro dia do sétimo mês, começaram a oferecer holocaustos ao Senhor , embora ainda não tivessem sido postos os fundamentos do templo do Senhor .

[[v15-3-7]]

^<<v15-3-7,7>>^ Então deram dinheiro aos pedreiros e aos carpinteiros, bem como comida, bebida e azeite aos homens de Tiro e de Sidom, para trazerem do Líbano madeira de cedro até o mar, até Jope, segundo a permissão que lhes tinha dado Ciro, rei da Pérsia.

[[v15-3-8]]

^<<v15-3-8,8>>^ No segundo ano depois que eles voltaram à Casa de Deus, em Jerusalém, no segundo mês, Zorobabel, filho de Sealtiel, e Jesua, filho de Jozadaque, e os seus outros irmãos, sacerdotes e levitas, e todos os que voltaram do cativeiro a Jerusalém puseram mãos à obra e constituíram levitas com mais de vinte anos para supervisionar a reconstrução da Casa do Senhor .

[[v15-3-9]]

^<<v15-3-9,9>>^ Então se apresentaram Jesua com os seus filhos e os seus irmãos, Cadmiel e os seus filhos, os filhos de Judá, para juntamente supervisionarem os que faziam a obra na Casa de Deus, bem como os filhos de Henadade, seus filhos e seus irmãos, os levitas.

[[v15-3-10]]

^<<v15-3-10,10>>^ Quando os construtores lançaram os alicerces do templo do Senhor , apresentaram-se os sacerdotes, paramentados e com trombetas, e os levitas, filhos de Asafe, com címbalos, para louvarem o Senhor , segundo as instruções deixadas por Davi, rei de Israel.

[[v15-3-11]]

^<<v15-3-11,11>>^ Cantavam responsivamente, louvando e dando graças ao Senhor , com estas palavras: Ele é bom, porque a sua misericórdia dura para sempre sobre Israel. E todo o povo jubilou com altas vozes, louvando o Senhor  por terem sido lançados os alicerces da Casa do Senhor .

[[v15-3-12]]

^<<v15-3-12,12>>^ Porém muitos dos sacerdotes, levitas e chefes de famílias, já idosos, que tinham visto o primeiro templo, choraram em alta voz quando, diante de seus olhos, foram lançados os alicerces deste templo; muitos, no entanto, levantaram as vozes com gritos de alegria.

[[v15-3-13]]

^<<v15-3-13,13>>^ E assim não se podiam distinguir as vozes de alegria das vozes do choro do povo; pois o povo gritava tão alto, que as vozes se ouviam de longe.

'''

xref:015-esdras/015-esdras-002.adoc#v15-2-0[&#60; Capítulo Anterior] | <<v15-3-0,Topo>> | xref:015-esdras/015-esdras-004.adoc#v15-4-0[Próximo Capítulo &#62;]