include::./index.adoc[]

[[v15-10-0]]
=== Esdras, 10
// naa ?, NAA - Nova Almeida Atualizada

[[v15-10-1]]

^<<v15-10-1,1>>^ Enquanto Esdras orava e fazia confissão, chorando prostrado diante da Casa de Deus, uma enorme congregação de israelitas — homens, mulheres e crianças — se reuniu em volta dele. E o povo chorava amargamente.

[[v15-10-2]]

^<<v15-10-2,2>>^ Então Secanias, filho de Jeiel, um dos filhos de Elão, tomou a palavra e disse a Esdras: — Nós temos transgredido contra o nosso Deus, casando com mulheres estrangeiras, que pertencem aos povos desta terra. Mas, quanto a isto, ainda há esperança para Israel.

[[v15-10-3]]

^<<v15-10-3,3>>^ Façamos agora uma aliança com o nosso Deus, de que despediremos todas essas mulheres e os seus filhos, segundo o conselho do meu senhor e dos que tremem diante do mandamento do nosso Deus. Que se faça segundo a Lei.

[[v15-10-4]]

^<<v15-10-4,4>>^ Levante-se, pois isto é incumbência sua, e nós o apoiaremos. Seja forte e mãos à obra!

[[v15-10-5]]

^<<v15-10-5,5>>^ Então Esdras se levantou e fez com que os principais sacerdotes, os levitas e todo o Israel jurassem que fariam segundo esta palavra. E eles juraram.

[[v15-10-6]]

^<<v15-10-6,6>>^ Esdras se retirou de onde estava, diante da Casa de Deus, e foi para a câmara de Joanã, filho de Eliasibe. Ao entrar ali, não comeu pão nem bebeu água, porque pranteava por causa da infidelidade dos que tinham voltado do exílio.

[[v15-10-7]]

^<<v15-10-7,7>>^ Depois anunciaram em Judá e Jerusalém que todos os que tinham voltado do exílio deviam se reunir em Jerusalém

[[v15-10-8]]

^<<v15-10-8,8>>^ e que, se alguém, em três dias, não viesse, segundo o conselho dos chefes e dos anciãos, todos os seus bens seriam totalmente destruídos, e ele mesmo seria excluído da congregação dos que voltaram do exílio.

[[v15-10-9]]

^<<v15-10-9,9>>^ Então todos os homens de Judá e Benjamim, em três dias, se reuniram em Jerusalém. No dia vinte do nono mês, todo o povo se assentou na praça da Casa de Deus, tremendo por causa daquele assunto e por causa da chuva intensa.

[[v15-10-10]]

^<<v15-10-10,10>>^ Então o sacerdote Esdras se levantou e lhes disse: — Vocês foram infiéis, casando com mulheres estrangeiras, aumentando a culpa de Israel.

[[v15-10-11]]

^<<v15-10-11,11>>^ Portanto, façam confissão ao Senhor , Deus dos seus pais, e façam o que lhe agrada. Separem-se dos povos desta terra e das mulheres estrangeiras.

[[v15-10-12]]

^<<v15-10-12,12>>^ E toda a congregação respondeu em voz alta: — Que assim seja! Faremos segundo as suas palavras.

[[v15-10-13]]

^<<v15-10-13,13>>^ Porém o povo é muito e, sendo a época das chuvas, não podemos ficar aqui do lado de fora. E isto não é coisa que se faça em um ou dois dias, pois somos muitos os que transgredimos neste assunto.

[[v15-10-14]]

^<<v15-10-14,14>>^ Que os nossos chefes decidam por toda a congregação, e que todos os que em nossas cidades casaram com mulheres estrangeiras venham a eles num dia marcado, acompanhados dos anciãos e dos juízes de cada cidade, até que se afaste de nós o furor da ira do nosso Deus, por causa desta situação.

[[v15-10-15]]

^<<v15-10-15,15>>^ Apenas Jônatas, filho de Asael, e Jazeías, filho de Ticvá, se opuseram a isso, apoiados por Mesulão e pelo levita Sabetai.

[[v15-10-16]]

^<<v15-10-16,16>>^ Os que voltaram do exílio fizeram assim. Então o sacerdote Esdras escolheu nominalmente os chefes de famílias, segundo a casa de seus pais; e se sentaram no primeiro dia do décimo mês para examinar essa questão.

[[v15-10-17]]

^<<v15-10-17,17>>^ E, no primeiro dia do primeiro mês, concluíram o exame de todos os casos de homens que haviam casado com mulheres estrangeiras.

[[v15-10-18]]

^<<v15-10-18,18>>^ Dentre os filhos dos sacerdotes, foram encontrados os seguintes que tinham casado com mulheres estrangeiras: dos filhos de Jesua, filho de Jozadaque, e de seus irmãos: Maaseias, Eliézer, Jaribe e Gedalias.

[[v15-10-19]]

^<<v15-10-19,19>>^ Com um aperto de mão, prometeram mandar embora as suas mulheres e, por serem culpados, ofereceram um carneiro do rebanho pela sua culpa.

[[v15-10-20]]

^<<v15-10-20,20>>^ Dos filhos de Imer: Hanani e Zebadias.

[[v15-10-21]]

^<<v15-10-21,21>>^ Dos filhos de Harim: Maaseias, Elias, Semaías, Jeiel e Uzias.

[[v15-10-22]]

^<<v15-10-22,22>>^ Dos filhos de Pasur: Elioenai, Maaseias, Ismael, Natanael, Jozabade e Elasa.

[[v15-10-23]]

^<<v15-10-23,23>>^ Dos levitas: Jozabade e Simei, Quelaías, também chamado de Quelita, Petaías, Judá e Eliézer.

[[v15-10-24]]

^<<v15-10-24,24>>^ Dos cantores: Eliasibe; dos porteiros: Salum, Telém e Uri.

[[v15-10-25]]

^<<v15-10-25,25>>^ E de Israel, dos filhos de Parós: Ramias, Jezias, Malquias, Miamim, Eleazar, Malquias e Benaia.

[[v15-10-26]]

^<<v15-10-26,26>>^ Dos filhos de Elão: Matanias, Zacarias, Jeiel, Abdi, Jerimote e Elias.

[[v15-10-27]]

^<<v15-10-27,27>>^ Dos filhos de Zatu: Elioenai, Eliasibe, Matanias, Jerimote, Zabade e Aziza.

[[v15-10-28]]

^<<v15-10-28,28>>^ Dos filhos de Bebai: Joanã, Hananias, Zabai e Atlai.

[[v15-10-29]]

^<<v15-10-29,29>>^ Dos filhos de Bani: Mesulão, Maluque, Adaías, Jasube, Seal e Jerimote.

[[v15-10-30]]

^<<v15-10-30,30>>^ Dos filhos de Paate-Moabe: Adna, Quelal, Benaia, Maaseias, Matanias, Bezalel, Binui e Manassés.

[[v15-10-31]]

^<<v15-10-31,31>>^ Dos filhos de Harim: Eliézer, Issias, Malquias, Semaías, Simeão,

[[v15-10-32]]

^<<v15-10-32,32>>^ Benjamim, Maluque e Semarias.

[[v15-10-33]]

^<<v15-10-33,33>>^ Dos filhos de Hasum: Matenai, Matatá, Zabade, Elifelete, Jeremai, Manassés e Simei.

[[v15-10-34]]

^<<v15-10-34,34>>^ Dos filhos de Bani: Maadai, Anrão, Uel,

[[v15-10-35]]

^<<v15-10-35,35>>^ Benaia, Bedias, Queluí,

[[v15-10-36]]

^<<v15-10-36,36>>^ Vanias, Meremote, Eliasibe,

[[v15-10-37]]

^<<v15-10-37,37>>^ Matanias, Matenai, Jaasai,

[[v15-10-38]]

^<<v15-10-38,38>>^ Bani, Binui, Simei,

[[v15-10-39]]

^<<v15-10-39,39>>^ Selemias, Natã, Adaías,

[[v15-10-40]]

^<<v15-10-40,40>>^ Macnadbai, Sasai, Sarai,

[[v15-10-41]]

^<<v15-10-41,41>>^ Azarel, Selemias, Semarias,

[[v15-10-42]]

^<<v15-10-42,42>>^ Salum, Amarias e José.

[[v15-10-43]]

^<<v15-10-43,43>>^ Dos filhos de Nebo: Jeiel, Matitias, Zabade, Zebina, Jadai, Joel e Benaia.

[[v15-10-44]]

^<<v15-10-44,44>>^ Todos estes tinham casado com mulheres estrangeiras, e alguns deles tinham filhos destas mulheres.

'''

xref:015-esdras/015-esdras-009.adoc#v15-9-0[&#60; Capítulo Anterior] | <<v15-10-0,Topo>> | xref:016-neemias/016-neemias-001.adoc#v16-1-0[Próximo Capítulo &#62;]