include::./index.adoc[]

[[v15-6-0]]
=== Esdras, 6
// naa ?, NAA - Nova Almeida Atualizada

[[v15-6-1]]

^<<v15-6-1,1>>^ Então o rei Dario deu ordem, e foi feita uma busca nos arquivos reais da Babilônia, onde se guardavam os documentos.

[[v15-6-2]]

^<<v15-6-2,2>>^ Em Ecbatana, a fortaleza que está na província da Média, se achou um rolo, e nele estava escrito um memorial que dizia assim:

[[v15-6-3]]

^<<v15-6-3,3>>^ "O rei Ciro, no primeiro ano do seu reinado, baixou o seguinte decreto: Com respeito à Casa de Deus, em Jerusalém, ela deve ser reconstruída para ser um lugar em que se ofereçam sacrifícios. Os seus fundamentos serão firmes, a sua altura será de vinte e sete metros e a sua largura será de vinte e sete metros, com três carreiras de grandes pedras e uma carreira de madeira nova.

[[v15-6-4]]

^<<v15-6-4,4>>^ As despesas serão pagas pelo palácio real.

[[v15-6-5]]

^<<v15-6-5,5>>^ Além disto, os utensílios de ouro e de prata da Casa de Deus, que Nabucodonosor havia tirado do templo de Jerusalém, levando-os para a Babilônia, serão devolvidos para o templo de Jerusalém, cada utensílio para o seu lugar; serão recolocados na Casa de Deus."

[[v15-6-6]]

^<<v15-6-6,6>>^ "E agora você, Tatenai, governador da região do outro lado do Eufrates, e também Setar-Bozenai e os seus companheiros, os afarsaquitas, que estão do outro lado do rio, fiquem longe daquele lugar.

[[v15-6-7]]

^<<v15-6-7,7>>^ Não interrompam a obra desta Casa de Deus, para que o governador dos judeus e os seus anciãos reedifiquem a Casa de Deus no seu antigo lugar.

[[v15-6-8]]

^<<v15-6-8,8>>^ Também estou decretando o que vocês devem fazer com estes anciãos dos judeus, para que reedifiquem esta Casa de Deus, a saber, que da tesouraria real, isto é, dos tributos recebidos da região do outro lado do rio Eufrates, se pague, diligentemente, a despesa a estes homens, para que a obra não seja interrompida.

[[v15-6-9]]

^<<v15-6-9,9>>^ Também lhes seja dado, dia após dia, sem falta, aquilo de que necessitam: novilhos, carneiros e cordeiros, para os holocaustos ao Deus dos céus; e também trigo, sal, vinho e azeite, segundo a determinação dos sacerdotes que estão em Jerusalém.

[[v15-6-10]]

^<<v15-6-10,10>>^ Isto para que ofereçam sacrifícios de aroma agradável ao Deus dos céus e orem pela vida do rei e dos seus filhos.

[[v15-6-11]]

^<<v15-6-11,11>>^ Também estou decretando que, se alguém alterar este decreto, uma viga seja arrancada da sua casa, e que ele seja levantado e pendurado nela; e que a sua casa seja transformada num montão de entulho.

[[v15-6-12]]

^<<v15-6-12,12>>^ Que o Deus que fez habitar ali o seu nome derrube todos os reis e povos que estenderem a mão para alterar o decreto e para destruir esta Casa de Deus, que está em Jerusalém. Eu, Dario, baixei o decreto; que se execute com toda a diligência."

[[v15-6-13]]

^<<v15-6-13,13>>^ Então Tatenai, o governador da região deste lado do Eufrates, Setar-Bozenai e os seus companheiros assim o fizeram com toda a diligência, segundo o que o rei Dario havia decretado.

[[v15-6-14]]

^<<v15-6-14,14>>^ Os anciãos dos judeus iam construindo e prosperando em virtude do que profetizaram os profetas Ageu e Zacarias, filho de Ido. Reconstruíram o templo e o terminaram segundo a ordem do Deus de Israel e segundo o decreto de Ciro, de Dario e de Artaxerxes, reis da Pérsia.

[[v15-6-15]]

^<<v15-6-15,15>>^ Terminaram a construção deste templo no terceiro dia do mês de adar, no sexto ano do reinado do rei Dario.

[[v15-6-16]]

^<<v15-6-16,16>>^ Os filhos de Israel, os sacerdotes, os levitas e o restante dos exilados celebraram com alegria a dedicação desta Casa de Deus.

[[v15-6-17]]

^<<v15-6-17,17>>^ Para a dedicação desta Casa de Deus ofereceram cem novilhos, duzentos carneiros, quatrocentos cordeiros e doze cabritos, para oferta pelo pecado de todo o Israel, segundo o número das tribos de Israel.

[[v15-6-18]]

^<<v15-6-18,18>>^ Estabeleceram os sacerdotes nos seus turnos e os levitas nas suas divisões, para o serviço de Deus em Jerusalém, segundo está escrito no Livro de Moisés.

[[v15-6-19]]

^<<v15-6-19,19>>^ Os que voltaram do cativeiro celebraram a Páscoa no dia catorze do primeiro mês.

[[v15-6-20]]

^<<v15-6-20,20>>^ Os sacerdotes e os levitas tinham se purificado, e todos, sem exceção, estavam limpos. Mataram o cordeiro da Páscoa para todos os que voltaram do cativeiro, para os sacerdotes, seus irmãos, e para si mesmos.

[[v15-6-21]]

^<<v15-6-21,21>>^ Assim, os filhos de Israel que tinham voltado do exílio comeram a Páscoa, juntamente com todos os que, unindo-se a eles, se haviam separado das coisas impuras dos gentios da terra, para buscarem o Senhor , Deus de Israel.

[[v15-6-22]]

^<<v15-6-22,22>>^ Celebraram a Festa dos Pães sem Fermento durante sete dias, com alegria, porque o Senhor  os tinha alegrado, mudando o coração do rei da Assíria a favor deles, para lhes fortalecer as mãos na obra da Casa de Deus, o Deus de Israel.

'''

xref:015-esdras/015-esdras-005.adoc#v15-5-0[&#60; Capítulo Anterior] | <<v15-6-0,Topo>> | xref:015-esdras/015-esdras-007.adoc#v15-7-0[Próximo Capítulo &#62;]