include::./index.adoc[]

[[v15-5-0]]
=== Esdras, 5
// naa ?, NAA - Nova Almeida Atualizada

[[v15-5-1]]

^<<v15-5-1,1>>^ O profeta Ageu e o profeta Zacarias, filho de Ido, profetizaram aos judeus que estavam em Judá e em Jerusalém, em nome do Deus de Israel, que estava sobre eles.

[[v15-5-2]]

^<<v15-5-2,2>>^ Então Zorobabel, filho de Sealtiel, e Jesua, filho de Jozadaque, começaram a reconstruir a Casa de Deus, em Jerusalém. Os referidos profetas de Deus estavam com eles e os ajudavam.

[[v15-5-3]]

^<<v15-5-3,3>>^ Nesse tempo, Tatenai, governador da região deste lado do Eufrates, e Setar-Bozenai e os seus companheiros vieram até eles e assim lhes perguntaram: — Quem deu ordem para vocês reconstruírem este templo e restaurarem esta muralha?

[[v15-5-4]]

^<<v15-5-4,4>>^ Perguntaram mais: — E quais são os nomes dos homens que estão construindo este edifício?

[[v15-5-5]]

^<<v15-5-5,5>>^ Porém os olhos de Deus estavam sobre os anciãos dos judeus, de maneira que não foram obrigados a parar, até que o assunto chegasse a Dario, e viesse resposta por carta sobre isso.

[[v15-5-6]]

^<<v15-5-6,6>>^ Eis a cópia da carta que Tatenai, o governador da região deste lado do Eufrates, com Setar-Bozenai e os seus companheiros, os afarsaquitas, que estavam deste lado do rio, enviaram ao rei Dario,

[[v15-5-7]]

^<<v15-5-7,7>>^ na qual lhe deram um relatório nos seguintes termos: "Ao rei Dario, toda a paz!

[[v15-5-8]]

^<<v15-5-8,8>>^ Saiba o rei que nós fomos à província de Judá, ao templo do grande Deus, que está sendo construído com grandes pedras. A madeira está sendo colocada nas paredes, e a obra está sendo feita com diligência e avançando nas mãos deles.

[[v15-5-9]]

^<<v15-5-9,9>>^ Perguntamos aos anciãos e assim lhes dissemos: ‘Quem deu ordem para vocês reconstruírem este templo e restaurarem esta muralha?’

[[v15-5-10]]

^<<v15-5-10,10>>^ Além disto, perguntamos também pelos nomes deles, para informar ao senhor, para que pudéssemos enviar por escrito ao rei os nomes dos homens que são os chefes deles.

[[v15-5-11]]

^<<v15-5-11,11>>^ Esta foi a resposta que nos deram: ‘Nós somos servos do Deus dos céus e da terra e estamos reconstruindo o templo que há muitos anos tinha sido construído, o qual um grande rei de Israel construiu e terminou.

[[v15-5-12]]

^<<v15-5-12,12>>^ Mas, depois que os nossos pais provocaram o Deus dos céus à ira, ele os entregou nas mãos de Nabucodonosor, rei da Babilônia, o caldeu, o qual destruiu este templo e transportou o povo para a Babilônia.

[[v15-5-13]]

^<<v15-5-13,13>>^ Porém Ciro, rei da Babilônia, no primeiro ano do seu reinado, deu ordem para que esta Casa de Deus fosse reconstruída.

[[v15-5-14]]

^<<v15-5-14,14>>^ Também os utensílios de ouro e de prata, da Casa de Deus, que Nabucodonosor tinha levado do templo de Jerusalém e colocado no templo da Babilônia, o rei Ciro os tirou de lá, e foram dados a um homem cujo nome era Sesbazar, a quem tinha nomeado governador

[[v15-5-15]]

^<<v15-5-15,15>>^ e a quem disse: "Pegue estes utensílios, vá e leve-os ao templo de Jerusalém, e que a Casa de Deus seja reconstruída no seu antigo lugar."

[[v15-5-16]]

^<<v15-5-16,16>>^ Então veio o dito Sesbazar e lançou os fundamentos da Casa de Deus, em Jerusalém; e, daí para cá, o templo tem estado em construção, mas ainda não está acabado.’

[[v15-5-17]]

^<<v15-5-17,17>>^ Agora, se parecer bem ao rei, que se busque nos arquivos reais, na Babilônia, se é verdade que há uma ordem do rei Ciro para reconstruir esta Casa de Deus, em Jerusalém. E que o rei nos faça saber a sua vontade quanto a isto."

'''

xref:015-esdras/015-esdras-004.adoc#v15-4-0[&#60; Capítulo Anterior] | <<v15-5-0,Topo>> | xref:015-esdras/015-esdras-006.adoc#v15-6-0[Próximo Capítulo &#62;]