include::./index.adoc[]

[[v15-1-0]]
=== Esdras, 1
// naa ?, NAA - Nova Almeida Atualizada

[[v15-1-1]]

^<<v15-1-1,1>>^ No primeiro ano do reinado de Ciro, rei da Pérsia, para que se cumprisse a palavra do Senhor , por boca de Jeremias, o Senhor  despertou o espírito de Ciro, rei da Pérsia, que ordenou que se proclamasse em todo o seu reino e que se pusesse por escrito o seguinte:

[[v15-1-2]]

^<<v15-1-2,2>>^ "Assim diz Ciro, rei da Pérsia: O Senhor , Deus dos céus, me deu todos os reinos da terra e me encarregou de lhe edificar um templo em Jerusalém, que fica em Judá.

[[v15-1-3]]

^<<v15-1-3,3>>^ Aquele dentre vocês que for do seu povo, que o seu Deus esteja com ele e que suba para Jerusalém, que fica em Judá, e edifique a Casa do Senhor , Deus de Israel; ele é o Deus que está em Jerusalém.

[[v15-1-4]]

^<<v15-1-4,4>>^ Todo aquele que restar, seja qual for o lugar em que habita, que os homens desse lugar o ajudem com prata, ouro, bens e gado, além das dádivas voluntárias para a Casa de Deus, em Jerusalém."

[[v15-1-5]]

^<<v15-1-5,5>>^ Então se levantaram os chefes de famílias de Judá e de Benjamim, os sacerdotes e os levitas e todos aqueles cujo espírito Deus despertou, para subirem a edificar a Casa do Senhor , em Jerusalém.

[[v15-1-6]]

^<<v15-1-6,6>>^ Todos os que moravam nos arredores os ajudaram com objetos de prata e de ouro, bens, gado e coisas preciosas, além de todas as ofertas voluntárias.

[[v15-1-7]]

^<<v15-1-7,7>>^ Também o rei Ciro entregou os utensílios da Casa do Senhor , os quais Nabucodonosor tinha trazido de Jerusalém e colocado na casa de seus deuses.

[[v15-1-8]]

^<<v15-1-8,8>>^ Ciro, rei da Pérsia, tirou esses utensílios sob a direção do tesoureiro Mitredate, que os entregou contados a Sesbazar, príncipe de Judá.

[[v15-1-9]]

^<<v15-1-9,9>>^ Eis o número deles: trinta bacias de ouro, mil bacias de prata, vinte e nove facas,

[[v15-1-10]]

^<<v15-1-10,10>>^ trinta taças de ouro, quatrocentas e dez taças de prata de menor qualidade e mil outros objetos.

[[v15-1-11]]

^<<v15-1-11,11>>^ Todos os utensílios de ouro e de prata foram cinco mil e quatrocentos. Sesbazar levou todos esses consigo, quando os exilados voltaram da Babilônia para Jerusalém.

'''

xref:014-2-cronicas/014-2-cronicas-036.adoc#v14-36-0[&#60; Capítulo Anterior] | <<v15-1-0,Topo>> | xref:015-esdras/015-esdras-002.adoc#v15-2-0[Próximo Capítulo &#62;]