include::./index.adoc[]

[[v15-7-0]]
=== Esdras, 7
// naa ?, NAA - Nova Almeida Atualizada

[[v15-7-1]]

^<<v15-7-1,1>>^ Passadas estas coisas, no reinado de Artaxerxes, rei da Pérsia, Esdras veio da Babilônia. Esdras era filho de Seraías, filho de Azarias, filho de Hilquias,

[[v15-7-2]]

^<<v15-7-2,2>>^ filho de Salum, filho de Zadoque, filho de Aitube,

[[v15-7-3]]

^<<v15-7-3,3>>^ filho de Amarias, filho de Azarias, filho de Meraiote,

[[v15-7-4]]

^<<v15-7-4,4>>^ filho de Zeraías, filho de Uzi, filho de Buqui,

[[v15-7-5]]

^<<v15-7-5,5>>^ filho de Abisua, filho de Fineias, filho de Eleazar, filho de Arão, o sumo sacerdote.

[[v15-7-6]]

^<<v15-7-6,6>>^ Ele era escriba versado na Lei de Moisés, dada pelo Senhor , Deus de Israel. E, como a mão do Senhor , seu Deus, estava sobre ele, o rei lhe deu tudo o que ele havia pedido.

[[v15-7-7]]

^<<v15-7-7,7>>^ Também vieram para Jerusalém alguns dos filhos de Israel, dos sacerdotes, dos levitas, dos cantores, dos porteiros e dos servidores do templo. Isto foi no sétimo ano do reinado de Artaxerxes.

[[v15-7-8]]

^<<v15-7-8,8>>^ Esdras chegou a Jerusalém no quinto mês, no sétimo ano deste rei.

[[v15-7-9]]

^<<v15-7-9,9>>^ Ele partiu da Babilônia no primeiro dia do primeiro mês, e, no primeiro dia do quinto mês, chegou a Jerusalém, porque a mão bondosa do seu Deus estava sobre ele.

[[v15-7-10]]

^<<v15-7-10,10>>^ Porque Esdras pôs no coração o propósito de buscar a Lei do Senhor , cumpri-la e ensinar em Israel os seus estatutos e os seus juízos.

[[v15-7-11]]

^<<v15-7-11,11>>^ Esta é a cópia da carta que o rei Artaxerxes entregou ao sacerdote Esdras, o escriba versado nas palavras, nos mandamentos e nos estatutos que o Senhor  deu a Israel:

[[v15-7-12]]

^<<v15-7-12,12>>^ "Artaxerxes, rei dos reis, ao sacerdote Esdras, escriba da Lei do Deus do céu: Paz perfeita!

[[v15-7-13]]

^<<v15-7-13,13>>^ Estou decretando que, no meu reino, todo aquele do povo de Israel e dos seus sacerdotes e levitas que quiser ir com você para Jerusalém, que vá.

[[v15-7-14]]

^<<v15-7-14,14>>^ Você está sendo autorizado pelo rei e os seus sete conselheiros para fazer uma averiguação em Judá e em Jerusalém, segundo a Lei do seu Deus, a qual está em suas mãos.

[[v15-7-15]]

^<<v15-7-15,15>>^ Leve a prata e o ouro que o rei e os seus conselheiros espontaneamente ofereceram ao Deus de Israel, cuja habitação está em Jerusalém.

[[v15-7-16]]

^<<v15-7-16,16>>^ Leve também a prata e o ouro que você achar em toda a província da Babilônia, com as ofertas voluntárias do povo e dos sacerdotes, oferecidas espontaneamente para o templo de seu Deus, em Jerusalém.

[[v15-7-17]]

^<<v15-7-17,17>>^ Empregue esse dinheiro com diligência e compre novilhos, carneiros, cordeiros, com as suas ofertas de cereais e as suas libações, para oferecer sobre o altar do templo do seu Deus, em Jerusalém.

[[v15-7-18]]

^<<v15-7-18,18>>^ Com o resto da prata e do ouro, você e os seus irmãos podem fazer o que acharem melhor, segundo a vontade do seu Deus.

[[v15-7-19]]

^<<v15-7-19,19>>^ E os utensílios que lhe foram dados para o serviço da casa do seu Deus, restitua-os diante do Deus de Jerusalém.

[[v15-7-20]]

^<<v15-7-20,20>>^ E tudo mais que for necessário para o templo de seu Deus e que você tiver de providenciar será pago pela casa dos tesouros do rei.

[[v15-7-21]]

^<<v15-7-21,21>>^ Eu mesmo, o rei Artaxerxes, estou decretando a todos os tesoureiros que estão do outro lado do Eufrates o que segue: entreguem diligentemente tudo o que o sacerdote Esdras, escriba da Lei do Deus do céu, solicitar,

[[v15-7-22]]

^<<v15-7-22,22>>^ até três mil e quatrocentos quilos de prata, dez mil quilos de trigo, dois mil litros de vinho, dois mil litros de azeite e sal à vontade.

[[v15-7-23]]

^<<v15-7-23,23>>^ Tudo o que for ordenado pelo Deus do céu, que se faça com exatidão para o templo do Deus do céu. Pois por que haveria grande ira sobre o reino do rei e dos seus filhos?

[[v15-7-24]]

^<<v15-7-24,24>>^ Também informamos, a respeito de todos os sacerdotes e levitas, cantores, porteiros, de todos os que servem nesta Casa de Deus, que não será lícito impor-lhes nem direitos, nem impostos, nem pedágios.

[[v15-7-25]]

^<<v15-7-25,25>>^ E você, Esdras, conforme a sabedoria que o seu Deus lhe deu, nomeie magistrados e juízes que julguem todo o povo que está na região do outro lado do Eufrates, isto é, todos os que conhecem as leis do seu Deus; e que elas sejam ensinadas aos que não as conhecem.

[[v15-7-26]]

^<<v15-7-26,26>>^ Todo aquele que não observar a lei do seu Deus e a lei do rei com diligência, seja condenado ou à morte, ou ao desterro, ou ao confisco de bens, ou à prisão."

[[v15-7-27]]

^<<v15-7-27,27>>^ — Bendito seja o Senhor , Deus de nossos pais, que deste modo moveu o coração do rei para adornar a Casa do Senhor , em Jerusalém;

[[v15-7-28]]

^<<v15-7-28,28>>^ e que estendeu para mim a sua misericórdia diante do rei, dos seus conselheiros e de todos os seus príncipes poderosos. Assim, eu me animei, porque a mão do Senhor , meu Deus, estava sobre mim, e reuni alguns chefes de Israel para voltarem comigo.

'''

xref:015-esdras/015-esdras-006.adoc#v15-6-0[&#60; Capítulo Anterior] | <<v15-7-0,Topo>> | xref:015-esdras/015-esdras-008.adoc#v15-8-0[Próximo Capítulo &#62;]