include::./index.adoc[]

[[v57-1-0]]
=== Filemom, 1
// naa ?, NAA - Nova Almeida Atualizada

[[v57-1-1]]

^<<v57-1-1,1>>^ Paulo, prisioneiro de Cristo Jesus, e o irmão Timóteo, ao amado Filemom, que é também nosso colaborador,

[[v57-1-2]]

^<<v57-1-2,2>>^ à igreja que se reúne em sua casa, à irmã Áfia e a Arquipo, nosso companheiro de lutas.

[[v57-1-3]]

^<<v57-1-3,3>>^ Que a graça e a paz de Deus, nosso Pai, e do Senhor Jesus Cristo estejam com vocês.

[[v57-1-4]]

^<<v57-1-4,4>>^ Dou graças ao meu Deus, lembrando sempre de você nas minhas orações,

[[v57-1-5]]

^<<v57-1-5,5>>^ porque tenho ouvido falar da fé que você tem no Senhor Jesus e do seu amor por todos os santos.

[[v57-1-6]]

^<<v57-1-6,6>>^ Oro para que a comunhão da sua fé se torne eficaz no pleno conhecimento de todo o bem que há em nós, para com Cristo.

[[v57-1-7]]

^<<v57-1-7,7>>^ Pois, irmão, o seu amor me trouxe grande alegria e consolo, visto que o coração dos santos tem sido reanimado por você.

[[v57-1-8]]

^<<v57-1-8,8>>^ Pois bem, ainda que eu sinta plena liberdade em Cristo para ordenar a você o que convém ser feito,

[[v57-1-9]]

^<<v57-1-9,9>>^ prefiro, no entanto, pedir em nome do amor, sendo o que sou, Paulo, o velho, e agora também prisioneiro de Cristo Jesus.

[[v57-1-10]]

^<<v57-1-10,10>>^ Faço um pedido em favor de meu filho Onésimo, que gerei entre algemas.

[[v57-1-11]]

^<<v57-1-11,11>>^ Antes, ele era inútil para você; atualmente, porém, é útil, para você e para mim.

[[v57-1-12]]

^<<v57-1-12,12>>^ Eu o estou mandando de volta a você — ele, quero dizer, o meu próprio coração.

[[v57-1-13]]

^<<v57-1-13,13>>^ Eu queria conservá-lo comigo, para que ele me servisse em seu lugar nas algemas que carrego por causa do evangelho.

[[v57-1-14]]

^<<v57-1-14,14>>^ Mas não quis fazer nada sem o seu consentimento, para que a sua bondade não venha a ser como que uma obrigação, mas algo que é feito de livre vontade.

[[v57-1-15]]

^<<v57-1-15,15>>^ Talvez ele tenha sido afastado de você temporariamente, a fim de que você o receba para sempre,

[[v57-1-16]]

^<<v57-1-16,16>>^ não como escravo, mas, muito mais do que escravo, como irmão caríssimo, especialmente de mim e, com maior razão, de você, quer como ser humano, quer como irmão no Senhor.

[[v57-1-17]]

^<<v57-1-17,17>>^ Portanto, se você me considera companheiro, receba-o como receberia a mim.

[[v57-1-18]]

^<<v57-1-18,18>>^ E, se ele causou algum dano a você ou lhe deve alguma coisa, ponha tudo na minha conta.

[[v57-1-19]]

^<<v57-1-19,19>>^ Eu, Paulo, de próprio punho, escrevo isto: Eu pagarei. É claro que não preciso dizer que você me deve a própria vida.

[[v57-1-20]]

^<<v57-1-20,20>>^ Sim, irmão, que eu receba de você, no Senhor, este benefício. Reanime o meu coração em Cristo.

[[v57-1-21]]

^<<v57-1-21,21>>^ Certo, como estou, da sua obediência, eu escrevo a você, sabendo que fará mais do que estou pedindo.

[[v57-1-22]]

^<<v57-1-22,22>>^ E, ao mesmo tempo, prepare-me também pousada, pois espero que, por meio das orações de vocês, eu lhes seja restituído.

[[v57-1-23]]

^<<v57-1-23,23>>^ Epafras, prisioneiro comigo, em Cristo Jesus,

[[v57-1-24]]

^<<v57-1-24,24>>^ Marcos, Aristarco, Demas e Lucas, meus colaboradores, mandam saudações a você.

[[v57-1-25]]

^<<v57-1-25,25>>^ A graça do Senhor Jesus Cristo esteja com o espírito de todos vocês.

'''

xref:056-tito/056-tito-003.adoc#v56-3-0[&#60; Capítulo Anterior] | <<v57-1-0,Topo>> | xref:058-hebreus/058-hebreus-001.adoc#v58-1-0[Próximo Capítulo &#62;]