include::./index.adoc[]

[[v39-3-0]]
=== Malaquias, 3
// naa ?, NAA - Nova Almeida Atualizada

[[v39-3-1]]

^<<v39-3-1,1>>^ — Eis que eu envio o meu mensageiro, que preparará o caminho diante de mim. De repente, o Senhor, a quem vocês buscam, virá ao seu templo; e o mensageiro da aliança, a quem vocês desejam, eis que ele vem, diz o Senhor  dos Exércitos.

[[v39-3-2]]

^<<v39-3-2,2>>^ Mas quem poderá suportar o dia da sua vinda? E quem poderá subsistir quando ele aparecer? Porque ele é como o fogo do ourives e como o sabão dos lavandeiros.

[[v39-3-3]]

^<<v39-3-3,3>>^ Ele se assentará como derretedor e purificador de prata. Purificará os filhos de Levi e os refinará como ouro e como prata. E eles trarão ao Senhor  as ofertas justas.

[[v39-3-4]]

^<<v39-3-4,4>>^ Então a oferta de Judá e de Jerusalém será agradável ao Senhor , como nos dias da antiguidade e como nos primeiros anos.

[[v39-3-5]]

^<<v39-3-5,5>>^ — Virei até vocês para juízo. Terei pressa em testemunhar contra os feiticeiros, contra os adúlteros, contra os que juram falsamente, contra os que oprimem os trabalhadores, as viúvas e os órfãos, torcem o direito dos estrangeiros, e não me temem, diz o Senhor  dos Exércitos.

[[v39-3-6]]

^<<v39-3-6,6>>^ — Porque eu, o Senhor , não mudo; por isso, vocês, filhos de Jacó, não foram destruídos.

[[v39-3-7]]

^<<v39-3-7,7>>^ Desde os dias dos seus pais, vocês se afastaram dos meus estatutos e não os guardaram. Voltem para mim, e eu voltarei para vocês, diz o Senhor  dos Exércitos. Mas vocês perguntam: "Como havemos de voltar?"

[[v39-3-8]]

^<<v39-3-8,8>>^ Será que alguém pode roubar a Deus? Mas vocês estão me roubando e ainda perguntam: "Em que te roubamos?" Nos dízimos e nas ofertas.

[[v39-3-9]]

^<<v39-3-9,9>>^ Com maldição vocês são amaldiçoados, porque estão me roubando, vocês, a nação toda.

[[v39-3-10]]

^<<v39-3-10,10>>^ Tragam todos os dízimos à casa do Tesouro, para que haja mantimento na minha casa. Ponham-me à prova nisto, diz o Senhor  dos Exércitos, se eu não lhes abrir as janelas do céu e não derramar sobre vocês bênção sem medida.

[[v39-3-11]]

^<<v39-3-11,11>>^ Por causa de vocês, repreenderei o devorador, para que não consuma os produtos da terra, e não deixarei que as suas videiras nos campos fiquem sem frutos, diz o Senhor  dos Exércitos.

[[v39-3-12]]

^<<v39-3-12,12>>^ Todas as nações dirão que vocês são felizes, porque vocês serão uma terra de delícias, diz o Senhor  dos Exércitos.

[[v39-3-13]]

^<<v39-3-13,13>>^ — Vocês disseram palavras duras contra mim, diz o Senhor , e ainda perguntam: "O que falamos contra ti?"

[[v39-3-14]]

^<<v39-3-14,14>>^ Vocês dizem: "É inútil servir a Deus. De que nos adianta guardar os seus preceitos e andar de luto diante do Senhor  dos Exércitos?

[[v39-3-15]]

^<<v39-3-15,15>>^ Agora, pois, nós vamos dizer que os soberbos é que são felizes. Também os que praticam o mal prosperam; sim, eles tentam o Senhor  e escapam."

[[v39-3-16]]

^<<v39-3-16,16>>^ Então os que temiam o Senhor  falavam uns aos outros. O Senhor  escutou com atenção o que diziam. Havia um memorial escrito diante dele para os que temem o Senhor  e para os que se lembram do seu nome.

[[v39-3-17]]

^<<v39-3-17,17>>^ — Eles serão a minha propriedade peculiar, naquele dia que prepararei, diz o Senhor  dos Exércitos. Eu os pouparei como um homem poupa seu filho que o serve.

[[v39-3-18]]

^<<v39-3-18,18>>^ Então vocês verão mais uma vez a diferença entre o justo e o ímpio, entre o que serve a Deus e o que não o serve.

'''

xref:039-malaquias/039-malaquias-002.adoc#v39-2-0[&#60; Capítulo Anterior] | <<v39-3-0,Topo>> | xref:039-malaquias/039-malaquias-004.adoc#v39-4-0[Próximo Capítulo &#62;]