include::./index.adoc[]

[[v39-1-0]]
=== Malaquias, 1
// naa ?, NAA - Nova Almeida Atualizada

[[v39-1-1]]

^<<v39-1-1,1>>^ Sentença pronunciada pelo Senhor  contra Israel, por meio de Malaquias.

[[v39-1-2]]

^<<v39-1-2,2>>^ O Senhor  diz: — Eu sempre os amei. Mas vocês perguntam: — Como é que nos amaste? E o Senhor  responde: — Esaú era irmão de Jacó, mas eu amei Jacó

[[v39-1-3]]

^<<v39-1-3,3>>^ e desprezei Esaú. Fiz dos montes de Edom uma desolação e dei a sua herança aos chacais do deserto.

[[v39-1-4]]

^<<v39-1-4,4>>^ Se Edom disser: "Fomos destruídos, mas vamos reconstruir o que está em ruínas", o Senhor  dos Exércitos responderá: "Eles podem até reconstruir, mas eu vou derrubar outra vez. E a terra deles será chamada de ‘Terra Da Maldade’ e ‘Povo Contra Quem O Senhor  Está Irado Para Sempre’."

[[v39-1-5]]

^<<v39-1-5,5>>^ Vocês verão isso com os seus olhos e dirão: — O Senhor  é grande também fora das fronteiras de Israel.

[[v39-1-6]]

^<<v39-1-6,6>>^ — O filho honra o pai, e o servo respeita o seu senhor. Se eu sou pai, onde está a minha honra? E, se eu sou senhor, onde está o respeito para comigo? Eu, o Senhor  dos Exércitos, pergunto isso a vocês, sacerdotes que desprezam o meu nome. Mas vocês perguntam: "Como desprezamos o teu nome?"

[[v39-1-7]]

^<<v39-1-7,7>>^ Vocês oferecem pão impuro sobre o meu altar e ainda perguntam: "Em que te havemos profanado?" Nisso de pensarem que a mesa do Senhor  pode ser desprezada.

[[v39-1-8]]

^<<v39-1-8,8>>^ Quando vocês oferecem em sacrifício um animal cego, será que isso não está errado? E, quando trazem um animal coxo ou doente, será que isso não está errado? Ora, experimentem oferecer um animal desses ao seu governador! Será que ele se agradará de vocês ou será favorável a vocês? — diz o Senhor  dos Exércitos.

[[v39-1-9]]

^<<v39-1-9,9>>^ — E agora, sacerdotes, supliquem o favor de Deus, para que nos conceda a sua graça. Mas, com tais ofertas nas mãos, será que ele será favorável a vocês? — diz o Senhor  dos Exércitos.

[[v39-1-10]]

^<<v39-1-10,10>>^ Quem dera houvesse entre vocês alguém que fechasse as portas do templo, para que não acendessem em vão o fogo do meu altar! Eu não tenho prazer em vocês, diz o Senhor  dos Exércitos, nem aceitarei as suas ofertas.

[[v39-1-11]]

^<<v39-1-11,11>>^ Mas, desde o nascente do sol até o poente, é grande o meu nome entre as nações. Em todos os lugares lhe é queimado incenso e são trazidas ofertas puras, porque é grande o meu nome entre as nações, diz o Senhor  dos Exércitos.

[[v39-1-12]]

^<<v39-1-12,12>>^ Mas vocês estão profanando o meu nome, quando pensam que a mesa do Senhor  é impura, e que a comida que é oferecida sobre ela pode ser desprezada.

[[v39-1-13]]

^<<v39-1-13,13>>^ E vocês dizem ainda: "Que canseira!" E torcem o nariz para isso, diz o Senhor  dos Exércitos. Oferecem animais roubados, coxos ou doentes. Vocês acham que eu vou aceitar isso? — diz o Senhor .

[[v39-1-14]]

^<<v39-1-14,14>>^ Maldito seja o enganador, que, tendo um animal sadio no seu rebanho, promete e oferece ao Senhor  um defeituoso! Porque eu sou grande Rei, diz o Senhor  dos Exércitos, e o meu nome é terrível entre as nações.

'''

xref:038-zacarias/038-zacarias-014.adoc#v38-14-0[&#60; Capítulo Anterior] | <<v39-1-0,Topo>> | xref:039-malaquias/039-malaquias-002.adoc#v39-2-0[Próximo Capítulo &#62;]