include::./index.adoc[]

[[v39-4-0]]
=== Malaquias, 4
// naa ?, NAA - Nova Almeida Atualizada

[[v39-4-1]]

^<<v39-4-1,1>>^ — Pois eis que vem o dia, queimando como fornalha. Todos os soberbos e todos os que praticam o mal serão como a palha; o dia que vem os queimará, diz o Senhor  dos Exércitos, de modo que não lhes deixará nem raiz nem ramo.

[[v39-4-2]]

^<<v39-4-2,2>>^ Mas para vocês que temem o meu nome nascerá o sol da justiça, trazendo salvação nas suas asas. Vocês sairão e saltarão como bezerros soltos da estrebaria.

[[v39-4-3]]

^<<v39-4-3,3>>^ Vocês pisarão os ímpios, pois eles se farão cinzas debaixo das plantas dos pés de vocês, naquele dia que prepararei, diz o Senhor  dos Exércitos.

[[v39-4-4]]

^<<v39-4-4,4>>^ — Lembrem-se da Lei de Moisés, meu servo, a qual lhe prescrevi em Horebe para todo o Israel, a saber, estatutos e juízos.

[[v39-4-5]]

^<<v39-4-5,5>>^ — Eis que eu lhes enviarei o profeta Elias, antes que venha o grande e terrível Dia do Senhor .

[[v39-4-6]]

^<<v39-4-6,6>>^ Ele converterá o coração dos pais aos seus filhos e o coração dos filhos aos seus pais, para que eu não venha e castigue a terra com maldição.

'''

xref:039-malaquias/039-malaquias-003.adoc#v39-3-0[&#60; Capítulo Anterior] | <<v39-4-0,Topo>> | xref:040-mateus/040-mateus-001.adoc#v40-1-0[Próximo Capítulo &#62;]