include::./index.adoc[]

[[v39-2-0]]
=== Malaquias, 2
// naa ?, NAA - Nova Almeida Atualizada

[[v39-2-1]]

^<<v39-2-1,1>>^ — E agora, sacerdotes, este mandamento é para vocês.

[[v39-2-2]]

^<<v39-2-2,2>>^ Se não ouvirem e não se importarem com a necessidade de honrar o meu nome, diz o Senhor  dos Exércitos, enviarei sobre vocês a maldição e amaldiçoarei as suas bênçãos. Aliás, já as amaldiçoei, porque vocês não se importaram com a honra devida ao meu nome.

[[v39-2-3]]

^<<v39-2-3,3>>^ Eis que reprovarei a sua descendência, passarei no rosto de vocês o esterco dos animais sacrificados nas suas festas, e vocês serão levados embora com esse esterco.

[[v39-2-4]]

^<<v39-2-4,4>>^ Então vocês saberão que eu lhes enviei este mandamento, para que se mantenha a minha aliança com Levi, diz o Senhor  dos Exércitos.

[[v39-2-5]]

^<<v39-2-5,5>>^ — Minha aliança com ele foi de vida e de paz, e foi isso que eu lhe dei, para que me temesse; e, de fato, ele me temeu e tremeu por causa do meu nome.

[[v39-2-6]]

^<<v39-2-6,6>>^ A verdadeira instrução esteve na sua boca, e nenhuma injustiça se achou em seus lábios. Ele andou comigo em paz e em retidão, e afastou muitos da iniquidade.

[[v39-2-7]]

^<<v39-2-7,7>>^ Porque os lábios do sacerdote devem guardar o conhecimento, e da sua boca todos devem buscar a instrução, porque ele é mensageiro do Senhor  dos Exércitos.

[[v39-2-8]]

^<<v39-2-8,8>>^ — Mas vocês se desviaram do caminho e, por meio de sua instrução, levaram muitos a tropeçar; vocês violaram a aliança de Levi, diz o Senhor  dos Exércitos.

[[v39-2-9]]

^<<v39-2-9,9>>^ Por isso, também eu os fiz desprezíveis e indignos diante de todo o povo, na medida em que vocês não guardaram os meus caminhos e se mostraram parciais na aplicação da lei.

[[v39-2-10]]

^<<v39-2-10,10>>^ Não temos nós todos o mesmo Pai? Não nos criou o mesmo Deus? Por que, então, seremos desleais uns para com os outros, profanando a aliança de nossos pais?

[[v39-2-11]]

^<<v39-2-11,11>>^ Judá tem sido infiel, e abominação foi cometida em Israel e em Jerusalém. Porque Judá profanou o santuário do Senhor , o qual ele ama, e se casou com a adoradora de deus estranho.

[[v39-2-12]]

^<<v39-2-12,12>>^ O Senhor  eliminará das tendas de Jacó aquele que fizer isso, seja ele quem for, mesmo que apresente ofertas ao Senhor  dos Exércitos.

[[v39-2-13]]

^<<v39-2-13,13>>^ Há outra coisa que vocês fazem: cobrem de lágrimas o altar do Senhor , com choro e gemidos, porque ele já não olha para a oferta nem a aceita com prazer.

[[v39-2-14]]

^<<v39-2-14,14>>^ E vocês perguntam: "Por quê?" Porque o Senhor  foi testemunha da aliança entre você e a mulher da sua mocidade, a quem você foi infiel, sendo ela a sua companheira e a mulher da sua aliança.

[[v39-2-15]]

^<<v39-2-15,15>>^ Não fez o Senhor  somente um, mesmo que lhe sobrasse o espírito? E por que somente um? Porque buscava uma descendência piedosa. Portanto, tenham cuidado para que ninguém seja infiel para com a mulher da sua mocidade.

[[v39-2-16]]

^<<v39-2-16,16>>^ Porque o Senhor , o Deus de Israel, diz que odeia o divórcio e também aquele que cobre de violência as suas roupas, diz o Senhor  dos Exércitos. Portanto, tenham cuidado e não sejam infiéis.

[[v39-2-17]]

^<<v39-2-17,17>>^ Vocês estão cansando o Senhor  com as suas palavras, e ainda perguntam: "Em que nós o cansamos?" Nisso de dizerem: "Aqueles que fazem o mal passam por bons aos olhos do Senhor , e é desses que ele se agrada." Ou: "Onde está o Deus da justiça?"

'''

xref:039-malaquias/039-malaquias-001.adoc#v39-1-0[&#60; Capítulo Anterior] | <<v39-2-0,Topo>> | xref:039-malaquias/039-malaquias-003.adoc#v39-3-0[Próximo Capítulo &#62;]