include::./index.adoc[]

[[v25-2-0]]
=== Lamentações, 2
// naa ?, NAA - Nova Almeida Atualizada

[[v25-2-1]]

^<<v25-2-1,1>>^ Álefe — Como o Senhor, na sua ira, cobriu de nuvens a filha de Sião! Precipitou do céu à terra a glória de Israel e, no dia da sua ira, não se lembrou do estrado de seus pés. Bete —

[[v25-2-2]]

^<<v25-2-2,2>>^ O Senhor devorou todas as moradas de Jacó e não teve piedade; no seu furor, derrubou as fortalezas da filha de Judá; lançou por terra e profanou o reino e os seus príncipes. Guímel —

[[v25-2-3]]

^<<v25-2-3,3>>^ No furor da sua ira, cortou toda a força de Israel; retirou a sua mão direita em face do inimigo. Consumiu Jacó como labareda de fogo que devora tudo ao seu redor. Dálete —

[[v25-2-4]]

^<<v25-2-4,4>>^ Entesou o seu arco, como se fosse um inimigo; firmou a sua mão direita, como se fosse um adversário. Destruiu tudo o que era formoso à vista; derramou o seu furor, como fogo, sobre a tenda da filha de Sião. Hê —

[[v25-2-5]]

^<<v25-2-5,5>>^ O Senhor se tornou como inimigo, devorando Israel; devorou todos os seus palácios, destruiu as suas fortalezas e multiplicou na filha de Judá o pranto e a lamentação. Vau —

[[v25-2-6]]

^<<v25-2-6,6>>^ Demoliu com violência o seu tabernáculo, como se fosse uma horta; destruiu o lugar da sua congregação. O Senhor , em Sião, entregou ao esquecimento as festas e o sábado e, na indignação da sua ira, rejeitou com desprezo o rei e o sacerdote. Zaine —

[[v25-2-7]]

^<<v25-2-7,7>>^ O Senhor rejeitou o seu altar e detestou o seu santuário. Entregou nas mãos dos inimigos os muros dos seus castelos; eles deram gritos na Casa do Senhor , como se fosse dia de festa. Hete —

[[v25-2-8]]

^<<v25-2-8,8>>^ O Senhor  resolveu destruir a muralha da filha de Sião; estendeu o cordel e não retirou a sua mão destruidora. Fez gemer a muralha e as paredes; juntas enfraqueceram. Tete —

[[v25-2-9]]

^<<v25-2-9,9>>^ Os seus portões caíram por terra; ele quebrou e despedaçou as suas trancas. O seu rei e os seus príncipes estão entre as nações onde já não vigora a lei; os seus profetas não recebem mais visões do Senhor . Iode —

[[v25-2-10]]

^<<v25-2-10,10>>^ Os anciãos da filha de Sião estão sentados no chão, em silêncio; lançam pó sobre a cabeça, vestindo roupa feita de pano de saco; as virgens de Jerusalém abaixam a cabeça até o chão. Cafe —

[[v25-2-11]]

^<<v25-2-11,11>>^ Com lágrimas se consumiram os meus olhos, a minha alma se agita; o meu coração se derramou de angústia por causa da calamidade da filha do meu povo, porque crianças e bebês desmaiam pelas ruas da cidade. Lâmede —

[[v25-2-12]]

^<<v25-2-12,12>>^ Perguntam às suas mães: "O que temos para comer e beber?", ao mesmo tempo em que desfalecem como o ferido pelas ruas da cidade ou quando dão o último suspiro nos braços de sua mãe. Mem —

[[v25-2-13]]

^<<v25-2-13,13>>^ O que posso lhe dizer? A quem você se assemelha, ó filha de Jerusalém? A quem posso compará-la, para lhe trazer consolo, ó virgem filha de Sião? Porque a sua calamidade é tão grande como o mar; quem poderá curá-la? Num —

[[v25-2-14]]

^<<v25-2-14,14>>^ As visões que os seus profetas lhe anunciaram eram falsas e enganosas. Eles não expuseram a maldade do que você fazia, para restaurarem a sua sorte, mas anunciaram visões falsas, que a levaram ao cativeiro. Sâmeque —

[[v25-2-15]]

^<<v25-2-15,15>>^ Todos os que passam pelo caminho zombam, batendo palmas, vaiam e balançam a cabeça diante da filha de Jerusalém. Perguntam: "É esta a cidade que chamavam de Perfeição da Formosura, a alegria de toda a terra?" Pê —

[[v25-2-16]]

^<<v25-2-16,16>>^ Todos os seus inimigos abrem a boca contra você, vaiam, rangem os dentes e dizem: "Nós acabamos com ela! Certamente este é o dia que esperávamos! Conseguimos! Esse dia chegou!" Aim —

[[v25-2-17]]

^<<v25-2-17,17>>^ O Senhor  fez o que tinha em vista; cumpriu a ameaça que pronunciou desde os dias da antiguidade. Derrubou sem dó nem piedade; deixou que os inimigos se alegrassem por causa de você e exaltou o poder dos seus adversários. Tsadê —

[[v25-2-18]]

^<<v25-2-18,18>>^ O coração do povo clama ao Senhor. Ó muralha da filha de Sião, que as suas lágrimas corram como um ribeiro, de dia e de noite! Não descanse! Que a menina de seus olhos não pare de chorar! Cofe —

[[v25-2-19]]

^<<v25-2-19,19>>^ Levante-se e clame de noite, no princípio das vigílias. Derrame, como água, o coração diante do Senhor; levante a ele as mãos, pela vida de seus filhinhos, que desfalecem de fome nas esquinas de todas as ruas. Rexe —

[[v25-2-20]]

^<<v25-2-20,20>>^ Vê, ó Senhor , e considera a quem trataste assim! Será que as mulheres deviam comer o fruto de si mesmas, as crianças que elas tanto amam? Ou será que os sacerdotes e profetas deviam ser mortos no santuário do Senhor? Chim —

[[v25-2-21]]

^<<v25-2-21,21>>^ Os jovens e os velhos jazem por terra pelas ruas; as minhas virgens e os meus jovens foram mortos à espada. Tu os mataste no dia da tua ira; fizeste matança sem dó nem piedade. Tau —

[[v25-2-22]]

^<<v25-2-22,22>>^ Convocaste de toda parte terrores contra mim, como se fosse um dia de festa; não houve quem escapasse ou ficasse com vida no dia da ira do Senhor . Os filhos que tive e criei, o meu inimigo os consumiu.

'''

xref:025-lamentacoes/025-lamentacoes-001.adoc#v25-1-0[&#60; Capítulo Anterior] | <<v25-2-0,Topo>> | xref:025-lamentacoes/025-lamentacoes-003.adoc#v25-3-0[Próximo Capítulo &#62;]