include::./index.adoc[]

[[v25-1-0]]
=== Lamentações, 1
// naa ?, NAA - Nova Almeida Atualizada

[[v25-1-1]]

^<<v25-1-1,1>>^ Álefe — Como jaz solitária a cidade outrora populosa! Tornou-se como viúva a que foi grande entre as nações! Princesa entre as províncias, ficou sujeita a trabalhos forçados! Bete —

[[v25-1-2]]

^<<v25-1-2,2>>^ Chora amargamente de noite, e as lágrimas lhe correm pelo rosto. Entre todos os seus amantes não tem quem a console. Todos os seus amigos a traíram; tornaram-se seus inimigos. Guímel —

[[v25-1-3]]

^<<v25-1-3,3>>^ Judá foi levado ao exílio, afligido e sob grande servidão; agora habita entre as nações, sem encontrar descanso. Todos os seus perseguidores o apanharam nas suas angústias. Dálete —

[[v25-1-4]]

^<<v25-1-4,4>>^ Os caminhos de Sião estão de luto, porque não há quem venha à reunião solene. Todas as suas portas estão desertas, os seus sacerdotes vivem gemendo, as suas virgens estão tristes, e ela mesma se acha em amargura. Hê —

[[v25-1-5]]

^<<v25-1-5,5>>^ Os seus adversários a dominam, os seus inimigos prosperam. Porque o Senhor  a afligiu, por causa da multidão das suas transgressões; os seus filhinhos tiveram de ir para o exílio, na frente dos adversários. Vau —

[[v25-1-6]]

^<<v25-1-6,6>>^ Da filha de Sião já se passou todo o esplendor. Os seus príncipes ficaram sendo como corços que não acham pasto e caminham exaustos na frente do perseguidor. Zaine —

[[v25-1-7]]

^<<v25-1-7,7>>^ Agora que está aflita e andando sem rumo, Jerusalém se lembra de todas as coisas preciosas que teve nos tempos antigos. Ela se recorda de como o seu povo caiu nas mãos do adversário, sem que ninguém viesse socorrê-la, e de como os adversários a viram e deram risada da sua queda. Hete —

[[v25-1-8]]

^<<v25-1-8,8>>^ Jerusalém pecou gravemente; por isso, se tornou repugnante. Todos os que a honravam agora a desprezam, porque viram a sua nudez; ela também geme e se retira envergonhada. Tete —

[[v25-1-9]]

^<<v25-1-9,9>>^ A sua impureza está nas suas saias. Ela não pensava no que poderia acontecer; por isso, caiu de modo espantoso e não tem quem a console. Vê, Senhor , a minha aflição, porque o inimigo se exalta. Iode —

[[v25-1-10]]

^<<v25-1-10,10>>^ O adversário pôs a mão em todas as coisas preciosas dela. Ela viu as nações entrarem no seu santuário, apesar de teres proibido que entrassem na tua congregação. Cafe —

[[v25-1-11]]

^<<v25-1-11,11>>^ Todo o seu povo anda gemendo e à procura de pão; trocaram as suas coisas preciosas por mantimento, para poderem restaurar as forças. Vê, Senhor , e contempla, pois me tornei desprezível. Lâmede —

[[v25-1-12]]

^<<v25-1-12,12>>^ Todos vocês que passam pelo caminho, será que isto não os comove? Olhem e vejam se há dor igual à minha, essa dor que me sobreveio, com que o Senhor  me afligiu no dia do furor da sua ira. Mem —

[[v25-1-13]]

^<<v25-1-13,13>>^ Lá do alto ele enviou fogo aos meus ossos, o qual se apoderou deles; estendeu uma rede aos meus pés, e me fez voltar para trás; deixou-me desolada e sofrendo todo o dia. Num —

[[v25-1-14]]

^<<v25-1-14,14>>^ Ele, com a sua mão, fez das minhas transgressões um jugo; elas foram entretecidas e penduradas no meu pescoço. O Senhor abateu a minha força; ele me entregou nas mãos daqueles contra os quais não posso resistir. Sâmeque —

[[v25-1-15]]

^<<v25-1-15,15>>^ O Senhor dispersou todos os valentes que estavam comigo; convocou um exército contra mim, para esmagar os meus jovens; o Senhor pisou, como num lagar, a virgem filha de Judá. Aim —

[[v25-1-16]]

^<<v25-1-16,16>>^ Por estas coisas, eu choro; os meus olhos, os meus olhos se desfazem em lágrimas. Porque o consolador, que devia restaurar as minhas forças, se afastou de mim. Os meus filhos estão desolados, porque o inimigo prevaleceu. Pê —

[[v25-1-17]]

^<<v25-1-17,17>>^ Sião estende as mãos, e não há quem a console. O Senhor  ordenou a respeito de Jacó que os seus vizinhos se tornem seus inimigos; para eles, Jerusalém se tornou coisa imunda. Tsadê —

[[v25-1-18]]

^<<v25-1-18,18>>^ Justo é o Senhor , pois me rebelei contra a sua palavra. Escutem, todos os povos, e vejam a minha dor; as minhas virgens e os meus jovens foram levados para o cativeiro. Cofe —

[[v25-1-19]]

^<<v25-1-19,19>>^ Chamei os meus amantes, mas eles me enganaram; os meus sacerdotes e os meus anciãos morreram na cidade, quando estavam à procura de mantimento para restaurarem as suas forças. Rexe —

[[v25-1-20]]

^<<v25-1-20,20>>^ Olha, Senhor , porque estou angustiada! A minha alma se agita, o meu coração está transtornado dentro de mim, porque gravemente me rebelei contra ti. Lá fora, a espada mata os filhos; aqui dentro, a morte se propaga. Chim —

[[v25-1-21]]

^<<v25-1-21,21>>^ Ouvem-se os meus gemidos, mas não tenho quem me console. Todos os meus inimigos que souberam da minha desgraça se alegram, porque tu a fizeste cair sobre mim; mas, quando trouxeres o dia que anunciaste, eles serão semelhantes a mim. Tau —

[[v25-1-22]]

^<<v25-1-22,22>>^ Venha toda a sua iniquidade à tua presença, e faze com eles como fizeste comigo por causa de todas as minhas transgressões; porque os meus gemidos são muitos, e o meu coração desfalece.

'''

xref:024-jeremias/024-jeremias-052.adoc#v24-52-0[&#60; Capítulo Anterior] | <<v25-1-0,Topo>> | xref:025-lamentacoes/025-lamentacoes-002.adoc#v25-2-0[Próximo Capítulo &#62;]