include::./index.adoc[]

[[v5-22-0]]
=== Deuteronômio, 22
// naa ?, NAA - Nova Almeida Atualizada

[[v5-22-1]]

^<<v5-22-1,1>>^ — Se você notar que um boi ou uma ovelha de seu compatriota se extraviou, não se omita, mas, sem falta, leve os animais de volta ao dono.

[[v5-22-2]]

^<<v5-22-2,2>>^ Se este não for o seu vizinho ou for alguém que você não conhece, leve os animais para casa e fique com eles até que o dono venha buscá-los; então você os entregará a ele.

[[v5-22-3]]

^<<v5-22-3,3>>^ Faça o mesmo com o jumento, com a roupa, ou com qualquer outra coisa que o seu compatriota perder e que você achar; você não pode se omitir.

[[v5-22-4]]

^<<v5-22-4,4>>^ — Se você enxergar o jumento ou o boi que pertence ao seu compatriota caído no caminho, não se omita; sem falta ajude-o a levantar o animal.

[[v5-22-5]]

^<<v5-22-5,5>>^ — A mulher não deve usar roupa de homem, e o homem não deve vestir roupa de mulher, pois quem faz isso é abominável ao Senhor , seu Deus.

[[v5-22-6]]

^<<v5-22-6,6>>^ — Se, no caminho, você encontrar um ninho de ave, em alguma árvore ou no chão, com passarinhos ou ovos, e a mãe sobre os passarinhos ou sobre os ovos, não pegue a mãe com os filhotes.

[[v5-22-7]]

^<<v5-22-7,7>>^ Você pode ficar com os filhotes, mas deixe a mãe ir, livremente, para que tudo vá bem com você, e para que você prolongue os seus dias.

[[v5-22-8]]

^<<v5-22-8,8>>^ — Quando você construir uma casa nova, faça um parapeito no terraço, para que você não traga culpa de sangue sobre a casa, se alguém de algum modo cair do terraço.

[[v5-22-9]]

^<<v5-22-9,9>>^ — Não plante outra semente na sua vinha, para que não se profane toda a produção, tanto da vinha quanto da semente que você plantou.

[[v5-22-10]]

^<<v5-22-10,10>>^ — Não lavre a terra com junta de boi e jumento.

[[v5-22-11]]

^<<v5-22-11,11>>^ — Não vista roupa feita de pano de lã e linho misturados.

[[v5-22-12]]

^<<v5-22-12,12>>^ — Coloque franjas nos quatro cantos do manto que você usa.

[[v5-22-13]]

^<<v5-22-13,13>>^ — Se um homem casar com uma mulher, e, depois de ter tido relações com ela, passar a odiá-la,

[[v5-22-14]]

^<<v5-22-14,14>>^ e lhe atribuir atos vergonhosos, e a difamar, dizendo: "Casei com esta mulher e, quando tive relações com ela, descobri que não era virgem",

[[v5-22-15]]

^<<v5-22-15,15>>^ então o pai e a mãe da moça levarão as provas da virgindade da moça aos anciãos da cidade, junto ao portão.

[[v5-22-16]]

^<<v5-22-16,16>>^ O pai da moça dirá aos anciãos: "Dei minha filha por mulher a este homem, porém ele passou a odiá-la.

[[v5-22-17]]

^<<v5-22-17,17>>^ Eis que lhe atribuiu atos vergonhosos, dizendo: ‘Descobri que a sua filha não era virgem.’ Mas aqui estão as provas da virgindade de minha filha." E estenderão a roupa dela diante dos anciãos da cidade,

[[v5-22-18]]

^<<v5-22-18,18>>^ os quais pegarão o homem, o açoitarão

[[v5-22-19]]

^<<v5-22-19,19>>^ e o condenarão a pagar cem barras de prata ao pai da moça, porque difamou uma virgem de Israel. Ela ficará sendo mulher dele, e ele não poderá mandá-la embora durante a sua vida.

[[v5-22-20]]

^<<v5-22-20,20>>^ — Porém, se isso for verdade, ou seja, se ficar provado que a moça não era virgem,

[[v5-22-21]]

^<<v5-22-21,21>>^ então a levarão à porta da casa de seu pai, e os homens de sua cidade a apedrejarão até que morra, pois cometeu um ato infame em Israel, prostituindo-se na casa de seu pai. Assim vocês eliminarão o mal do meio de vocês.

[[v5-22-22]]

^<<v5-22-22,22>>^ — Se um homem for encontrado deitado com uma mulher que tem marido, ambos devem ser mortos, o homem que se deitou com a mulher e a mulher. Assim vocês eliminarão o mal de Israel.

[[v5-22-23]]

^<<v5-22-23,23>>^ — Se uma moça virgem tiver casamento contratado, e outro homem a encontrar na cidade e tiver relações com ela,

[[v5-22-24]]

^<<v5-22-24,24>>^ vocês devem trazer ambos ao portão daquela cidade e apedrejá-los até que morram; a moça, porque não gritou por socorro, estando na cidade, e o homem, porque humilhou a mulher do seu próximo. Assim vocês eliminarão o mal do meio de vocês.

[[v5-22-25]]

^<<v5-22-25,25>>^ — Porém, se um homem, no campo, encontrar uma moça que tem casamento contratado, e a forçar, e tiver relações com ela, então morrerá só o homem que teve relações com ela;

[[v5-22-26]]

^<<v5-22-26,26>>^ à moça vocês não devem fazer nada; ela não tem culpa de morte, porque este caso é semelhante ao do homem que se levanta contra o seu próximo e lhe tira a vida.

[[v5-22-27]]

^<<v5-22-27,27>>^ Pois o homem encontrou a moça no campo; a moça que tinha o casamento contratado gritou, e não houve quem a livrasse.

[[v5-22-28]]

^<<v5-22-28,28>>^ — Se um homem encontrar uma moça virgem, que não tem casamento contratado, e a pegar à força, e tiver relações com ela, e eles forem apanhados,

[[v5-22-29]]

^<<v5-22-29,29>>^ então o homem que teve relações com ela pagará ao pai da moça cinquenta barras de prata; e, uma vez que a humilhou, terá de recebê-la por esposa; não poderá mandá-la embora durante a sua vida.

[[v5-22-30]]

^<<v5-22-30,30>>^ — Nenhum homem terá relações com a sua madrasta e não profanará o leito de seu pai.

'''

xref:005-deuteronomio/005-deuteronomio-021.adoc#v5-21-0[&#60; Capítulo Anterior] | <<v5-22-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-023.adoc#v5-23-0[Próximo Capítulo &#62;]