include::./index.adoc[]

[[v5-6-0]]
=== Deuteronômio, 6
// naa ?, NAA - Nova Almeida Atualizada

[[v5-6-1]]

^<<v5-6-1,1>>^ — São estes os mandamentos, os estatutos e os juízos que o Senhor , seu Deus, ordenou que fossem ensinados a vocês, para que vocês os cumprissem na terra em que vão entrar e possuir,

[[v5-6-2]]

^<<v5-6-2,2>>^ para que durante todos os dias da sua vida vocês, os seus filhos, e os filhos dos seus filhos temam o Senhor , seu Deus, e guardem todos os seus estatutos e mandamentos que eu lhes ordeno, e para que os seus dias sejam prolongados.

[[v5-6-3]]

^<<v5-6-3,3>>^ Portanto, escute, Israel, e tenha o cuidado de cumprir esses mandamentos, para que tudo lhes corra bem e vocês muito se multipliquem na terra que mana leite e mel, como o Senhor , o Deus dos seus pais, lhes prometeu.

[[v5-6-4]]

^<<v5-6-4,4>>^ — Escute, Israel, o Senhor , nosso Deus, é o único Senhor .

[[v5-6-5]]

^<<v5-6-5,5>>^ Portanto, ame o Senhor , seu Deus, de todo o seu coração, de toda a sua alma e com toda a sua força.

[[v5-6-6]]

^<<v5-6-6,6>>^ Estas palavras que hoje lhe ordeno estarão no seu coração.

[[v5-6-7]]

^<<v5-6-7,7>>^ Você as inculcará a seus filhos, e delas falará quando estiver sentado em sua casa, andando pelo caminho, ao deitar-se e ao levantar-se.

[[v5-6-8]]

^<<v5-6-8,8>>^ Também deve amarrá-las como sinal na sua mão, e elas lhe serão por frontal entre os olhos.

[[v5-6-9]]

^<<v5-6-9,9>>^ E você as escreverá nos umbrais de sua casa e nas suas portas.

[[v5-6-10]]

^<<v5-6-10,10>>^ — Quando, pois, o Senhor , seu Deus, tiver levado vocês para a terra que, sob juramento, prometeu aos seus pais Abraão, Isaque e Jacó, que daria a vocês — uma terra com grandes e boas cidades, que vocês não construíram;

[[v5-6-11]]

^<<v5-6-11,11>>^ com casas cheias de tudo o que é bom, que vocês não encheram; com poços abertos, que vocês não cavaram; com vinhas e olivais, que vocês não plantaram — e quando vocês comerem e se fartarem,

[[v5-6-12]]

^<<v5-6-12,12>>^ tenham o cuidado de não esquecer o Senhor , que os tirou da terra do Egito, da casa da servidão.

[[v5-6-13]]

^<<v5-6-13,13>>^ Temam o Senhor , seu Deus, sirvam a ele e jurem somente pelo nome dele.

[[v5-6-14]]

^<<v5-6-14,14>>^ Não sigam outros deuses, nenhum dos deuses dos povos que estiverem à sua volta,

[[v5-6-15]]

^<<v5-6-15,15>>^ porque o Senhor , seu Deus, é Deus zeloso no meio de vocês, para que a ira do Senhor , seu Deus, não se acenda contra vocês e os destrua de sobre a face da terra.

[[v5-6-16]]

^<<v5-6-16,16>>^ — Não ponham à prova o Senhor , seu Deus, como o fizeram em Massá.

[[v5-6-17]]

^<<v5-6-17,17>>^ Guardem cuidadosamente os mandamentos do Senhor , seu Deus, os seus testemunhos e os seus estatutos que ele lhes ordenou.

[[v5-6-18]]

^<<v5-6-18,18>>^ Façam o que é reto e bom aos olhos do Senhor , para que tudo lhes vá bem, e para que vocês entrem e possuam a boa terra que o Senhor , sob juramento, prometeu aos pais de vocês,

[[v5-6-19]]

^<<v5-6-19,19>>^ expulsando todos os inimigos de diante de vocês, como o Senhor  prometeu.

[[v5-6-20]]

^<<v5-6-20,20>>^ — Quando, no futuro, os seus filhos perguntarem: "Que significam os testemunhos, estatutos e juízos que o Senhor , nosso Deus, lhes ordenou?",

[[v5-6-21]]

^<<v5-6-21,21>>^ vocês dirão a eles: "Nós éramos escravos de Faraó, no Egito, mas o Senhor  nos tirou de lá com mão poderosa.

[[v5-6-22]]

^<<v5-6-22,22>>^ Diante dos nossos olhos o Senhor  fez sinais e maravilhas, grandes e terríveis, contra o Egito e contra Faraó e toda a sua casa.

[[v5-6-23]]

^<<v5-6-23,23>>^ Ele nos tirou do Egito, para nos trazer e nos dar a terra que, sob juramento, prometeu aos nossos pais.

[[v5-6-24]]

^<<v5-6-24,24>>^ O Senhor  nos ordenou que cumpríssemos todos estes estatutos e temêssemos o Senhor , nosso Deus, para o nosso perpétuo bem, para nos preservar a vida, como tem feito até hoje.

[[v5-6-25]]

^<<v5-6-25,25>>^ E será justiça para nós, quando tivermos cuidado de cumprir todos estes mandamentos diante do Senhor , nosso Deus, como ele nos ordenou."

'''

xref:005-deuteronomio/005-deuteronomio-005.adoc#v5-5-0[&#60; Capítulo Anterior] | <<v5-6-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-007.adoc#v5-7-0[Próximo Capítulo &#62;]