include::./index.adoc[]

[[v5-3-0]]
=== Deuteronômio, 3
// naa ?, NAA - Nova Almeida Atualizada

[[v5-3-1]]

^<<v5-3-1,1>>^ — Depois, voltamos e fomos na direção de Basã. E Ogue, rei de Basã, saiu ao nosso encontro, ele e todo o seu povo, para lutar contra nós em Edrei.

[[v5-3-2]]

^<<v5-3-2,2>>^ Então o Senhor  me disse: "Não tenha medo, porque eu o entreguei nas suas mãos, ele, todo o seu povo e a terra dele. Você fará com ele como fez com Seom, rei dos amorreus, que habitava em Hesbom."

[[v5-3-3]]

^<<v5-3-3,3>>^ E o Senhor , nosso Deus, entregou em nossas mãos também Ogue, rei de Basã, e todo o seu povo; lutamos contra ele, até que não sobrasse ninguém.

[[v5-3-4]]

^<<v5-3-4,4>>^ Nesse tempo, tomamos todas as suas cidades. Não houve nenhuma cidade que não lhe tomássemos: sessenta cidades, toda a região de Argobe, o reino de Ogue, em Basã.

[[v5-3-5]]

^<<v5-3-5,5>>^ Todas estas cidades eram fortificadas com altas muralhas, portões e ferrolhos. Tomamos também muitas outras cidades que não tinham muralhas.

[[v5-3-6]]

^<<v5-3-6,6>>^ Nós as destruímos totalmente, como fizemos com Seom, rei de Hesbom, destruindo por completo cada uma das cidades com os seus homens, suas mulheres e crianças.

[[v5-3-7]]

^<<v5-3-7,7>>^ Porém todo o gado e o despojo das cidades tomamos para nós, por presa.

[[v5-3-8]]

^<<v5-3-8,8>>^ — Assim, nesse tempo, tomamos a terra das mãos daqueles dois reis dos amorreus que estavam além do Jordão: desde o ribeiro de Arnom até o monte Hermom.

[[v5-3-9]]

^<<v5-3-9,9>>^ (Os sidônios chamam o Hermom de Siriom; porém os amorreus o chamam de Senir.)

[[v5-3-10]]

^<<v5-3-10,10>>^ Tomamos todas as cidades do planalto, todo o Gileade e todo o Basã, até Salca e Edrei, cidades do reino de Ogue, em Basã.

[[v5-3-11]]

^<<v5-3-11,11>>^ (Ogue, rei de Basã, era o último sobrevivente dos refains. A cama dele era feita de ferro e ainda se encontra em Rabá dos filhos de Amom. Tinha quatro metros de comprimento e um metro e oitenta de largura, pela medida comum.)

[[v5-3-12]]

^<<v5-3-12,12>>^ — Tomamos posse desta terra nesse tempo. A região que vai de Aroer, que está junto ao vale de Arnom, e a metade da região montanhosa de Gileade, com as suas cidades, dei aos rubenitas e gaditas.

[[v5-3-13]]

^<<v5-3-13,13>>^ O resto de Gileade e toda a região de Basã, o reino de Ogue, dei à meia tribo de Manassés. (Toda aquela região de Argobe, todo o Basã, se chamava a terra dos refains.)

[[v5-3-14]]

^<<v5-3-14,14>>^ Jair, filho de Manassés, tomou toda a região de Argobe até a fronteira dos gesuritas e maacatitas, isto é, Basã, e às aldeias chamou pelo seu nome: Havote-Jair, até o dia de hoje.

[[v5-3-15]]

^<<v5-3-15,15>>^ A Maquir dei Gileade.

[[v5-3-16]]

^<<v5-3-16,16>>^ Aos rubenitas e gaditas dei desde Gileade até o vale de Arnom, cujo meio serve de fronteira; e até o ribeiro de Jaboque, na fronteira dos filhos de Amom,

[[v5-3-17]]

^<<v5-3-17,17>>^ bem como a Arabá e o Jordão por fronteira, desde Quinerete até o mar da Arabá, o mar Salgado, pelas encostas do monte Pisga, para o leste.

[[v5-3-18]]

^<<v5-3-18,18>>^ — Nesse mesmo tempo, eu lhes ordenei, dizendo: "O Senhor , o Deus de vocês, lhes deu esta terra, para que vocês tomem posse dela. Todos os homens valentes, armados, devem passar adiante de seus irmãos, os filhos de Israel.

[[v5-3-19]]

^<<v5-3-19,19>>^ Tão somente as mulheres, as crianças e o gado de vocês — porque sei que vocês têm muito gado — ficarão nas cidades que já lhes dei.

[[v5-3-20]]

^<<v5-3-20,20>>^ Vocês deverão lutar até que o Senhor  dê descanso a seus irmãos como deu a vocês, para que eles também ocupem a terra que o Senhor , o Deus de vocês, está dando a eles do outro lado do Jordão; depois, vocês poderão voltar, cada um à propriedade que lhe dei."

[[v5-3-21]]

^<<v5-3-21,21>>^ — Também, nesse tempo, dei ordem a Josué, dizendo: "Você viu tudo o que o Senhor , o Deus de vocês, tem feito com esses dois reis; assim o Senhor  fará com todos os reinos em que você entrar.

[[v5-3-22]]

^<<v5-3-22,22>>^ Não tenham medo deles, porque o Senhor , o Deus de vocês, é o que luta por vocês."

[[v5-3-23]]

^<<v5-3-23,23>>^ — Também eu, nesse tempo, implorei ao Senhor , dizendo:

[[v5-3-24]]

^<<v5-3-24,24>>^ "Ó Senhor  Deus, já começaste a mostrar ao teu servo a tua grandeza e a tua mão poderosa! Pois que deus há, nos céus ou na terra, que possa fazer as obras e os feitos poderosos que tu realizas?

[[v5-3-25]]

^<<v5-3-25,25>>^ Peço-te que me deixes passar, para que eu veja esta boa terra que está do outro lado do Jordão, esta boa região montanhosa e o Líbano."

[[v5-3-26]]

^<<v5-3-26,26>>^ Porém o Senhor  estava indignado contra mim, por causa de vocês, e não me ouviu. Pelo contrário, ele me disse: "Basta! Não me fale mais nisso.

[[v5-3-27]]

^<<v5-3-27,27>>^ Suba ao alto do monte Pisga e levante os olhos para o oeste, para o norte, para o sul e para o leste e contemple com os seus próprios olhos, porque você não passará este Jordão.

[[v5-3-28]]

^<<v5-3-28,28>>^ Dê ordens a Josué, anime-o e fortaleça-o; porque ele irá à frente deste povo e o fará possuir a terra que você apenas verá."

[[v5-3-29]]

^<<v5-3-29,29>>^ — Assim, ficamos no vale diante de Bete-Peor.

'''

xref:005-deuteronomio/005-deuteronomio-002.adoc#v5-2-0[&#60; Capítulo Anterior] | <<v5-3-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-004.adoc#v5-4-0[Próximo Capítulo &#62;]