include::./index.adoc[]

[[v5-15-0]]
=== Deuteronômio, 15
// naa ?, NAA - Nova Almeida Atualizada

[[v5-15-1]]

^<<v5-15-1,1>>^ — Ao final de cada sete anos, vocês devem cancelar as dívidas.

[[v5-15-2]]

^<<v5-15-2,2>>^ Este é o modo como isso será feito: todo credor que emprestou alguma coisa ao seu próximo dará por pago o que havia emprestado; não exigirá pagamento do seu próximo ou do seu compatriota, porque a remissão do Senhor  é proclamada.

[[v5-15-3]]

^<<v5-15-3,3>>^ Do estranho vocês podem exigir o pagamento da dívida, mas o que tiverem emprestado aos seus compatriotas vocês devem dar por quitado,

[[v5-15-4]]

^<<v5-15-4,4>>^ para que não haja pobre no meio de vocês. Porque o Senhor , o Deus de vocês, os abençoará ricamente na terra que lhes dá por herança, para que vocês tomem posse dela,

[[v5-15-5]]

^<<v5-15-5,5>>^ se apenas ouvirem atentamente a voz do Senhor , seu Deus, cumprindo todos estes mandamentos que hoje lhes ordeno.

[[v5-15-6]]

^<<v5-15-6,6>>^ Pois o Senhor , seu Deus, os abençoará, conforme prometeu. Assim, vocês emprestarão a muitas nações, mas não tomarão empréstimos; e dominarão muitas nações, porém elas não terão domínio sobre vocês.

[[v5-15-7]]

^<<v5-15-7,7>>^ — Se houver algum pobre entre vocês, no meio dos seus irmãos, em alguma das cidades de vocês, na terra que o Senhor , seu Deus, lhes dá, não endureçam o seu coração, nem fechem as mãos a seu compatriota pobre;

[[v5-15-8]]

^<<v5-15-8,8>>^ pelo contrário, devem abrir a mão para ele e lhe emprestar o que lhe falta, tudo aquilo de que tiver necessidade.

[[v5-15-9]]

^<<v5-15-9,9>>^ Tenham cuidado para que não haja pensamento vil em seu coração e vocês digam: "Está próximo o sétimo ano, o ano do perdão das dívidas", fazendo com que os olhos de vocês sejam malignos para com o seu compatriota pobre, e vocês não lhe deem nada, e ele clame ao Senhor  contra vocês, e vocês sejam culpados de pecado.

[[v5-15-10]]

^<<v5-15-10,10>>^ Vocês devem dar livremente, sem maldade no coração, quando lhe derem o que ele precisa, porque, por isso, o Senhor , seu Deus, os abençoará em todas as suas obras e em tudo o que vocês empreenderem.

[[v5-15-11]]

^<<v5-15-11,11>>^ Pois nunca deixará de haver pobres na terra. Por isso, eu ordeno a vocês que, livremente, abram a mão para o seu compatriota, para o necessitado, para o pobre que vive na terra de vocês.

[[v5-15-12]]

^<<v5-15-12,12>>^ — Se um de seus compatriotas, hebreu ou hebreia, for vendido a você como escravo, ele trabalhará para você durante seis anos; mas no sétimo ano você lhe dará a liberdade.

[[v5-15-13]]

^<<v5-15-13,13>>^ E, quando você o puser em liberdade, não o mande embora de mãos vazias.

[[v5-15-14]]

^<<v5-15-14,14>>^ Liberalmente, você deve lhe fornecer animais do seu rebanho e do produto da sua eira e do seu lagar; daquilo com que o Senhor , seu Deus, o tiver abençoado, você lhe dará.

[[v5-15-15]]

^<<v5-15-15,15>>^ Lembre-se de que você foi escravo na terra do Egito e de que o Senhor , seu Deus, o resgatou; por isso, hoje estou dando esta ordem a você.

[[v5-15-16]]

^<<v5-15-16,16>>^ — Se, porém, o escravo disser: "Não quero me afastar de você", porque ama você e a sua casa e por se sentir bem com você,

[[v5-15-17]]

^<<v5-15-17,17>>^ então você deve pegar um furador e furar a orelha dele, na porta, e ele será seu escravo para sempre. Faça o mesmo com a escrava que quiser ficar.

[[v5-15-18]]

^<<v5-15-18,18>>^ Não pareça aos seus olhos algo difícil deixar que ele fique livre, porque durante seis anos ele o serviu por metade do salário de um trabalhador diarista. Assim, o Senhor , seu Deus, abençoará você em tudo o que fizer.

[[v5-15-19]]

^<<v5-15-19,19>>^ Do seu gado e de suas ovelhas, consagrem ao Senhor , seu Deus, todo primogênito macho. Com os primogênitos do gado vocês não devem trabalhar, nem devem tosquiar os primogênitos das suas ovelhas.

[[v5-15-20]]

^<<v5-15-20,20>>^ De ano em ano vocês e as suas casas devem comer esses animais diante do Senhor , no lugar que o Senhor  escolher.

[[v5-15-21]]

^<<v5-15-21,21>>^ Porém, se um desses animais tiver algum defeito, se for coxo, ou cego, ou tiver outro defeito grave, não o sacrifiquem ao Senhor , seu Deus.

[[v5-15-22]]

^<<v5-15-22,22>>^ Vocês devem comer a carne desses animais na cidade em que moram. Tanto as pessoas impuras como as puras poderão comer dessa carne, como se come a carne da gazela ou do veado.

[[v5-15-23]]

^<<v5-15-23,23>>^ Tão somente não comam o sangue; este vocês devem derramar sobre a terra como se fosse água.

'''

xref:005-deuteronomio/005-deuteronomio-014.adoc#v5-14-0[&#60; Capítulo Anterior] | <<v5-15-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-016.adoc#v5-16-0[Próximo Capítulo &#62;]