include::./index.adoc[]

[[v5-5-0]]
=== Deuteronômio, 5
// naa ?, NAA - Nova Almeida Atualizada

[[v5-5-1]]

^<<v5-5-1,1>>^ Moisés chamou todo o Israel e lhe disse: — Escute, Israel, os estatutos e juízos que hoje lhes anuncio, para que vocês os aprendam e tenham o cuidado de pôr em prática.

[[v5-5-2]]

^<<v5-5-2,2>>^ O Senhor , nosso Deus, fez aliança conosco em Horebe.

[[v5-5-3]]

^<<v5-5-3,3>>^ Não foi com nossos pais que o Senhor  fez esta aliança, e sim conosco, todos os que hoje aqui estamos vivos.

[[v5-5-4]]

^<<v5-5-4,4>>^ Face a face o Senhor  falou conosco, no monte, do meio do fogo.

[[v5-5-5]]

^<<v5-5-5,5>>^ Naquela ocasião, eu me coloquei entre o Senhor  e vocês, para lhes anunciar a palavra do Senhor , porque vocês ficaram com medo do fogo e não subiram o monte. E o Senhor  disse:

[[v5-5-6]]

^<<v5-5-6,6>>^ — "Eu sou o Senhor , seu Deus, que o tirei da terra do Egito, da casa da servidão."

[[v5-5-7]]

^<<v5-5-7,7>>^ — "Não tenha outros deuses diante de mim."

[[v5-5-8]]

^<<v5-5-8,8>>^ — "Não faça para você imagem de escultura, nem semelhança alguma do que há em cima no céu, nem embaixo na terra, nem nas águas debaixo da terra.

[[v5-5-9]]

^<<v5-5-9,9>>^ Não adore essas coisas, nem preste culto a elas, porque eu, o Senhor , seu Deus, sou Deus zeloso, que visito a iniquidade dos pais nos filhos até a terceira e quarta geração daqueles que me odeiam,

[[v5-5-10]]

^<<v5-5-10,10>>^ mas faço misericórdia até mil gerações daqueles que me amam e guardam os meus mandamentos."

[[v5-5-11]]

^<<v5-5-11,11>>^ — "Não tome o nome do Senhor , seu Deus, em vão, porque o Senhor  não terá por inocente o que tomar o seu nome em vão."

[[v5-5-12]]

^<<v5-5-12,12>>^ — "Guarde o dia de sábado, para o santificar, como o Senhor , seu Deus, lhe ordenou.

[[v5-5-13]]

^<<v5-5-13,13>>^ Seis dias você trabalhará e fará toda a sua obra,

[[v5-5-14]]

^<<v5-5-14,14>>^ mas o sétimo dia é o sábado dedicado ao Senhor , seu Deus; não faça nenhum trabalho nesse dia, nem você, nem o seu filho, nem a sua filha, nem o seu servo, nem a sua serva, nem o seu boi, nem o seu jumento ou qualquer outro dos seus animais, nem o estrangeiro das suas portas para dentro, para que o seu servo e a sua serva descansem como você.

[[v5-5-15]]

^<<v5-5-15,15>>^ Lembre-se de que você foi escravo na terra do Egito e que o Senhor , seu Deus, o tirou de lá com mão poderosa e braço estendido. Por isso o Senhor , seu Deus, ordenou que você guardasse o dia de sábado."

[[v5-5-16]]

^<<v5-5-16,16>>^ — "Honre o seu pai e a sua mãe, como o Senhor , seu Deus, lhe ordenou, para que você tenha uma longa vida e para que tudo vá bem com você na terra que o Senhor , seu Deus, lhe dá."

[[v5-5-17]]

^<<v5-5-17,17>>^ — "Não mate."

[[v5-5-18]]

^<<v5-5-18,18>>^ — "Não cometa adultério."

[[v5-5-19]]

^<<v5-5-19,19>>^ — "Não furte."

[[v5-5-20]]

^<<v5-5-20,20>>^ — "Não dê falso testemunho contra o seu próximo."

[[v5-5-21]]

^<<v5-5-21,21>>^ — "Não cobice a mulher do seu próximo. Não deseje a casa do seu próximo, nem o seu campo, nem o seu servo, nem a sua serva, nem o seu boi, nem o seu jumento, nem coisa alguma que pertença ao seu próximo."

[[v5-5-22]]

^<<v5-5-22,22>>^ — São estas as palavras que o Senhor  falou a toda a congregação de vocês, junto ao monte. Ele falou do meio do fogo, da nuvem e da escuridão, com voz forte, e nada acrescentou. Ele escreveu essas palavras em duas tábuas de pedra, e as deu para mim.

[[v5-5-23]]

^<<v5-5-23,23>>^ Quando ouviram a voz que vinha do meio das trevas, enquanto o monte estava em chamas, vocês se aproximaram de mim, todos os chefes das tribos e os anciãos,

[[v5-5-24]]

^<<v5-5-24,24>>^ e disseram: "Eis que aqui o Senhor , nosso Deus, nos mostrou a sua glória e a sua grandeza, e ouvimos a sua voz do meio do fogo. Hoje vimos que Deus fala com as pessoas e que elas permanecem vivas.

[[v5-5-25]]

^<<v5-5-25,25>>^ Agora, pois, por que morreríamos? Pois este grande fogo nos consumirá! Se continuarmos a ouvir a voz do Senhor , nosso Deus, morreremos.

[[v5-5-26]]

^<<v5-5-26,26>>^ Afinal, de toda a humanidade, quem é que ouviu a voz do Deus vivo falar do meio do fogo, como nós ouvimos, e permaneceu vivo?

[[v5-5-27]]

^<<v5-5-27,27>>^ Aproxime-se você e ouça tudo o que o Senhor , nosso Deus, disser. Você nos dirá tudo o que o Senhor , nosso Deus, lhe disser. Nós ouviremos e cumpriremos o que for dito."

[[v5-5-28]]

^<<v5-5-28,28>>^ — Quando o Senhor  ouviu o que vocês disseram, quando falavam comigo, o Senhor  me disse: "Eu ouvi as palavras que este povo lhe falou, e em tudo eles falaram muito bem.

[[v5-5-29]]

^<<v5-5-29,29>>^ Quem dera que eles sempre tivessem tal coração, e sempre me temessem e guardassem todos os meus mandamentos! Assim tudo iria bem para eles e para os filhos deles, para sempre!

[[v5-5-30]]

^<<v5-5-30,30>>^ Vá e diga-lhes que voltem para as suas tendas.

[[v5-5-31]]

^<<v5-5-31,31>>^ Mas você fique aqui comigo, e eu lhe direi todos os mandamentos, estatutos e juízos que você lhes ensinará, para que os cumpram na terra que eu lhes darei para que seja deles."

[[v5-5-32]]

^<<v5-5-32,32>>^ — Tenham o cuidado de fazer como o Senhor , seu Deus, lhes ordenou. Não se desviem, nem para a direita nem para a esquerda.

[[v5-5-33]]

^<<v5-5-33,33>>^ Andem em todo o caminho que o Senhor , seu Deus, lhes ordenou, para que vocês vivam, para que tudo lhes vá bem, e para que se prolonguem os seus dias na terra que irão possuir.

'''

xref:005-deuteronomio/005-deuteronomio-004.adoc#v5-4-0[&#60; Capítulo Anterior] | <<v5-5-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-006.adoc#v5-6-0[Próximo Capítulo &#62;]