include::./index.adoc[]

[[v5-27-0]]
=== Deuteronômio, 27
// naa ?, NAA - Nova Almeida Atualizada

[[v5-27-1]]

^<<v5-27-1,1>>^ Moisés e os anciãos de Israel deram ordens ao povo, dizendo: — Guardem todos estes mandamentos que hoje lhes ordeno.

[[v5-27-2]]

^<<v5-27-2,2>>^ No dia em que vocês passarem o Jordão e entrarem na terra que o Senhor , seu Deus, lhes dá, levantem pedras grandes e pintem-nas com cal.

[[v5-27-3]]

^<<v5-27-3,3>>^ Ao passarem, escrevam nessas pedras todas as palavras desta lei, para que vocês entrem na terra que o Senhor , seu Deus, lhes dá, terra que mana leite e mel, como o Senhor , o Deus dos seus pais, lhes prometeu.

[[v5-27-4]]

^<<v5-27-4,4>>^ Quando vocês tiverem passado o Jordão, levantem essas pedras no monte Ebal, como hoje lhes ordeno, e pintem-nas com cal.

[[v5-27-5]]

^<<v5-27-5,5>>^ Ali vocês devem construir um altar ao Senhor , seu Deus, altar de pedras que não tenham sido trabalhadas com instrumentos de ferro.

[[v5-27-6]]

^<<v5-27-6,6>>^ Construam o altar do Senhor , seu Deus, com pedras toscas e sobre este altar lhe ofereçam holocaustos.

[[v5-27-7]]

^<<v5-27-7,7>>^ Também sacrifiquem ofertas pacíficas; comam ali e alegrem-se na presença do Senhor , seu Deus.

[[v5-27-8]]

^<<v5-27-8,8>>^ Nessas pedras, escrevam, de forma bem nítida, todas as palavras desta lei.

[[v5-27-9]]

^<<v5-27-9,9>>^ Moisés, juntamente com os sacerdotes levitas, disse ainda a todo o Israel: — Fique em silêncio e escute, ó Israel! Hoje vocês vieram a ser o povo do Senhor , seu Deus.

[[v5-27-10]]

^<<v5-27-10,10>>^ Portanto, obedeçam à voz do Senhor , seu Deus, e cumpram os mandamentos e os estatutos que hoje lhes ordeno.

[[v5-27-11]]

^<<v5-27-11,11>>^ Naquele dia, Moisés deu ordem ao povo, dizendo:

[[v5-27-12]]

^<<v5-27-12,12>>^ — Quando vocês tiverem passado o Jordão, estas tribos devem se colocar sobre o monte Gerizim, para abençoar o povo: Simeão, Levi, Judá, Issacar, José e Benjamim.

[[v5-27-13]]

^<<v5-27-13,13>>^ E estas tribos estarão sobre o monte Ebal, para amaldiçoar o povo: Rúben, Gade, Aser, Zebulom, Dã e Naftali.

[[v5-27-14]]

^<<v5-27-14,14>>^ Os levitas testificarão a todo o povo de Israel em alta voz e dirão:

[[v5-27-15]]

^<<v5-27-15,15>>^ — "Maldito o homem que fizer imagem de escultura ou de fundição, abominável ao Senhor , obra de artífice, e a puser em lugar oculto." E todo o povo responderá: "Amém!"

[[v5-27-16]]

^<<v5-27-16,16>>^ — "Maldito aquele que desprezar o seu pai ou a sua mãe." E todo o povo dirá: "Amém!"

[[v5-27-17]]

^<<v5-27-17,17>>^ — "Maldito aquele que mudar os marcos de divisa do seu próximo." E todo o povo dirá: "Amém!"

[[v5-27-18]]

^<<v5-27-18,18>>^ — "Maldito aquele que fizer o cego errar o caminho." E todo o povo dirá: "Amém!"

[[v5-27-19]]

^<<v5-27-19,19>>^ — "Maldito aquele que perverter o direito do estrangeiro, do órfão e da viúva." E todo o povo dirá: "Amém!"

[[v5-27-20]]

^<<v5-27-20,20>>^ — "Maldito aquele que tiver relações sexuais com a madrasta, porque profanaria o leito de seu pai." E todo o povo dirá: "Amém!"

[[v5-27-21]]

^<<v5-27-21,21>>^ — "Maldito aquele que tiver relações sexuais com um animal." E todo o povo dirá: "Amém!"

[[v5-27-22]]

^<<v5-27-22,22>>^ — "Maldito aquele que tiver relações sexuais com a sua irmã, filha de seu pai ou filha de sua mãe." E todo o povo dirá: "Amém!"

[[v5-27-23]]

^<<v5-27-23,23>>^ — "Maldito aquele que tiver relações sexuais com sua sogra." E todo o povo dirá: "Amém!"

[[v5-27-24]]

^<<v5-27-24,24>>^ — "Maldito aquele que matar o seu próximo às escondidas." E todo o povo dirá: "Amém!"

[[v5-27-25]]

^<<v5-27-25,25>>^ — "Maldito aquele que aceitar suborno para matar pessoa inocente." E todo o povo dirá: "Amém!"

[[v5-27-26]]

^<<v5-27-26,26>>^ — "Maldito aquele que não confirmar as palavras desta lei, não as cumprindo." E todo o povo dirá: "Amém!"

'''

xref:005-deuteronomio/005-deuteronomio-026.adoc#v5-26-0[&#60; Capítulo Anterior] | <<v5-27-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-028.adoc#v5-28-0[Próximo Capítulo &#62;]