include::./index.adoc[]

[[v5-4-0]]
=== Deuteronômio, 4
// naa ?, NAA - Nova Almeida Atualizada

[[v5-4-1]]

^<<v5-4-1,1>>^ — Agora, pois, ó Israel, ouça os estatutos e os juízos que eu lhes ensino, para que vocês os cumpram, para que vivam, entrem e tomem posse da terra que o Senhor , o Deus de seus pais, está dando a vocês.

[[v5-4-2]]

^<<v5-4-2,2>>^ Não acrescentem nada à palavra que eu lhes ordeno, nem diminuam nada dela, para que vocês guardem os mandamentos do Senhor , o Deus de vocês, que eu lhes ordeno.

[[v5-4-3]]

^<<v5-4-3,3>>^ Com os seus próprios olhos vocês viram o que o Senhor  fez por causa de Baal-Peor, pois o Senhor , seu Deus, eliminou do meio de vocês todos os que seguiram Baal-Peor.

[[v5-4-4]]

^<<v5-4-4,4>>^ Porém vocês que permaneceram fiéis ao Senhor , seu Deus, todos hoje estão vivos.

[[v5-4-5]]

^<<v5-4-5,5>>^ — Eis que eu lhes tenho ensinado estatutos e juízos, como o Senhor , meu Deus, me ordenou, para que vocês os cumpram na terra que passarão a possuir.

[[v5-4-6]]

^<<v5-4-6,6>>^ Portanto, guardem e cumpram essas leis, porque isto será a sabedoria e o entendimento de vocês aos olhos dos povos que, ouvindo todos esses estatutos, dirão: "De fato, este grande povo é gente sábia e inteligente."

[[v5-4-7]]

^<<v5-4-7,7>>^ Pois que grande nação há que tenha deuses tão chegados a si como o Senhor , nosso Deus, todas as vezes que o invocamos?

[[v5-4-8]]

^<<v5-4-8,8>>^ E que grande nação há que tenha estatutos e juízos tão justos como toda esta lei que hoje eu lhes proponho?

[[v5-4-9]]

^<<v5-4-9,9>>^ — Tão somente tenham cuidado e guardem bem a sua alma, para que vocês não se esqueçam daquelas coisas que os seus olhos têm visto, e elas não se afastem do seu coração todos os dias da sua vida. Vocês também contarão isso aos seus filhos e aos filhos dos seus filhos.

[[v5-4-10]]

^<<v5-4-10,10>>^ Não se esqueçam do dia em que vocês estiveram diante do Senhor , seu Deus, em Horebe, quando o Senhor  me disse: "Reúna este povo, e os farei ouvir as minhas palavras, a fim de que aprendam a temer-me durante todos os dias em que viverem na terra e também as ensinem aos seus filhos."

[[v5-4-11]]

^<<v5-4-11,11>>^ — Então vocês chegaram e ficaram ao pé do monte. E o monte estava em chamas que subiam até o céu, e havia trevas, nuvens e escuridão.

[[v5-4-12]]

^<<v5-4-12,12>>^ Então o Senhor  falou a vocês do meio do fogo e vocês ouviram o som das palavras dele. Vocês ouviram a voz, mas não viram aparência nenhuma; só escutaram a voz.

[[v5-4-13]]

^<<v5-4-13,13>>^ Então ele anunciou a sua aliança, que ordenou a vocês, os dez mandamentos, e os escreveu em duas tábuas de pedra.

[[v5-4-14]]

^<<v5-4-14,14>>^ Ao mesmo tempo o Senhor  ordenou que eu ensinasse a vocês estatutos e juízos, para que os cumprissem na terra que passarão a possuir.

[[v5-4-15]]

^<<v5-4-15,15>>^ — Tenham cuidado! Guardem bem a sua alma. Porque vocês não viram aparência nenhuma no dia em que o Senhor , o Deus de vocês, lhes falou em Horebe, no meio do fogo.

[[v5-4-16]]

^<<v5-4-16,16>>^ Portanto, tenham cuidado para não se corromperem e fazerem para si alguma imagem esculpida na forma de ídolo, semelhança de homem ou de mulher,

[[v5-4-17]]

^<<v5-4-17,17>>^ semelhança de algum animal que há na terra, semelhança de alguma ave que voa pelos céus,

[[v5-4-18]]

^<<v5-4-18,18>>^ semelhança de algum animal que rasteja sobre a terra, semelhança de algum peixe que há nas águas debaixo da terra.

[[v5-4-19]]

^<<v5-4-19,19>>^ Quando levantarem os olhos para os céus e verem o sol, a lua e as estrelas, a saber, todo o exército dos céus, cuidem para que vocês não sejam seduzidos a inclinar-se diante deles e prestar culto a essas coisas que o Senhor , seu Deus, repartiu a todos os povos debaixo dos céus.

[[v5-4-20]]

^<<v5-4-20,20>>^ Mas quanto a vocês, o Senhor  os tomou e os tirou da fornalha de ferro do Egito, para que sejam povo da sua herança, como hoje se vê.

[[v5-4-21]]

^<<v5-4-21,21>>^ — Também o Senhor  se indignou contra mim, por causa de vocês, e jurou que eu não passaria o Jordão e não entraria na boa terra que o Senhor , seu Deus, lhes dá por herança.

[[v5-4-22]]

^<<v5-4-22,22>>^ Porque eu morrerei neste lugar; não passarei o Jordão. Mas vocês vão passar o Jordão e possuir aquela boa terra.

[[v5-4-23]]

^<<v5-4-23,23>>^ Tenham o cuidado de não se esquecer da aliança que o Senhor , seu Deus, fez com vocês. Não façam para si nenhuma imagem esculpida, semelhança de alguma coisa que o Senhor , o Deus de vocês, proibiu.

[[v5-4-24]]

^<<v5-4-24,24>>^ Porque o Senhor , o Deus de vocês, é fogo consumidor, é Deus zeloso.

[[v5-4-25]]

^<<v5-4-25,25>>^ — Quando, pois, gerarem filhos e tiverem netos, e já estiverem muito tempo na terra, e se corromperem, e fizerem alguma imagem esculpida, semelhança de alguma coisa, e praticarem o que é mau aos olhos do Senhor , o Deus de vocês, para o provocar à ira,

[[v5-4-26]]

^<<v5-4-26,26>>^ hoje tomo o céu e a terra por testemunhas contra vocês, que vocês serão imediatamente eliminados da terra da qual, passando o Jordão, vocês tomarão posse. Vocês não prolongarão os seus dias nela; pelo contrário, serão totalmente destruídos.

[[v5-4-27]]

^<<v5-4-27,27>>^ O Senhor  os espalhará entre os povos, e restarão apenas alguns de vocês entre as gentes aonde o Senhor  os levará.

[[v5-4-28]]

^<<v5-4-28,28>>^ Lá, vocês servirão a deuses que são obra de mãos humanas, madeira e pedra, que não veem, nem ouvem, nem comem, nem cheiram.

[[v5-4-29]]

^<<v5-4-29,29>>^ De lá, vocês buscarão o Senhor , seu Deus, e o acharão, quando o buscarem de todo o coração e de toda a sua alma.

[[v5-4-30]]

^<<v5-4-30,30>>^ Quando estiverem em angústia, e todas estas coisas lhes sobrevierem nos últimos dias, e vocês se voltarem para o Senhor , seu Deus, e lhe atenderem a voz,

[[v5-4-31]]

^<<v5-4-31,31>>^ então o Senhor , o Deus de vocês, não os abandonará, porque é Deus misericordioso, nem os destruirá, nem se esquecerá da aliança que jurou aos pais de vocês.

[[v5-4-32]]

^<<v5-4-32,32>>^ — Agora, pois, perguntem aos tempos passados, que transcorreram antes de vocês, desde o dia em que Deus criou o ser humano sobre a terra, desde uma extremidade do céu até a outra, se já aconteceu algo tão grandioso como isto ou se em algum momento se ouviu falar de coisa semelhante.

[[v5-4-33]]

^<<v5-4-33,33>>^ Perguntem se algum povo ouviu a voz de algum deus falando do meio do fogo, como vocês ouviram, e ficaram vivos;

[[v5-4-34]]

^<<v5-4-34,34>>^ ou se já houve um deus que tentou ir tomar para si um povo do meio de outro povo, com provas, com sinais, com milagres, com lutas, com mão poderosa, com braço estendido e com feitos espantosos, segundo tudo o que o Senhor , seu Deus, fez por vocês no Egito, como vocês viram com os seus próprios olhos.

[[v5-4-35]]

^<<v5-4-35,35>>^ Isso foi mostrado a vocês para que soubessem que o Senhor  é Deus; nenhum outro há, além dele.

[[v5-4-36]]

^<<v5-4-36,36>>^ Dos céus ele fez com que ouvissem a sua voz, para ensiná-los, e sobre a terra lhes mostrou o seu grande fogo, e do meio do fogo vocês ouviram as suas palavras.

[[v5-4-37]]

^<<v5-4-37,37>>^ Ele amou os pais de vocês e escolheu os seus descendentes depois deles; por isso o Senhor  os tirou do Egito com a sua presença e com a sua grande força,

[[v5-4-38]]

^<<v5-4-38,38>>^ para expulsar da frente de vocês nações maiores e mais poderosas do que vocês, para fazer com que vocês entrassem na terra deles e dá-la a vocês por herança, como hoje se vê.

[[v5-4-39]]

^<<v5-4-39,39>>^ — Por isso, hoje vocês saberão e refletirão em seu coração que só o Senhor  é Deus em cima no céu e embaixo na terra; não há nenhum outro deus.

[[v5-4-40]]

^<<v5-4-40,40>>^ Portanto, guardem os seus estatutos e os seus mandamentos que hoje lhes ordeno, para que tudo vá bem com vocês e com os seus filhos depois de vocês e para que vocês prolonguem os seus dias na terra que o Senhor , seu Deus, lhes está dando para todo o sempre.

[[v5-4-41]]

^<<v5-4-41,41>>^ Então Moisés separou três cidades além do Jordão, para o nascente do sol,

[[v5-4-42]]

^<<v5-4-42,42>>^ para que ali pudesse se refugiar o homicida que tivesse matado, involuntariamente, o seu próximo, de quem, antes daquilo, não tivesse ódio algum. Esse homicida poderia se refugiar numa destas cidades e salvar a sua vida.

[[v5-4-43]]

^<<v5-4-43,43>>^ As cidades eram Bezer, no deserto, no planalto, para os rubenitas; Ramote, em Gileade, para os gaditas; e Golã, em Basã, para os manassitas.

[[v5-4-44]]

^<<v5-4-44,44>>^ Esta é a lei que Moisés apresentou aos filhos de Israel.

[[v5-4-45]]

^<<v5-4-45,45>>^ São estes os testemunhos, os estatutos e os juízos que Moisés falou aos filhos de Israel, quando saíram do Egito,

[[v5-4-46]]

^<<v5-4-46,46>>^ além do Jordão, no vale diante de Bete-Peor, na terra de Seom, rei dos amorreus, que habitava em Hesbom, a quem Moisés e os filhos de Israel derrotaram quando saíram do Egito,

[[v5-4-47]]

^<<v5-4-47,47>>^ e tomaram posse da terra dele, bem como da terra de Ogue, rei de Basã, dois reis dos amorreus, que estavam além do Jordão, para o nascente do sol.

[[v5-4-48]]

^<<v5-4-48,48>>^ Essas terras se estendiam desde Aroer, que está à beira do vale de Arnom, até o monte Siom, que é Hermom,

[[v5-4-49]]

^<<v5-4-49,49>>^ e incluíam toda a Arabá, além do Jordão, do lado leste, até o mar da Arabá, pelas encostas do monte Pisga.

'''

xref:005-deuteronomio/005-deuteronomio-003.adoc#v5-3-0[&#60; Capítulo Anterior] | <<v5-4-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-005.adoc#v5-5-0[Próximo Capítulo &#62;]