include::./index.adoc[]

[[v5-21-0]]
=== Deuteronômio, 21
// naa ?, NAA - Nova Almeida Atualizada

[[v5-21-1]]

^<<v5-21-1,1>>^ — Se na terra que o Senhor , seu Deus, lhes dá para que tomem posse dela, alguém for achado morto, caído no campo, sem que se saiba quem o matou,

[[v5-21-2]]

^<<v5-21-2,2>>^ os anciãos e os juízes devem sair e medir a distância entre o morto e as cidades ao redor.

[[v5-21-3]]

^<<v5-21-3,3>>^ Os anciãos da cidade mais próxima do morto tomarão uma novilha do rebanho, que ainda não tenha sido usada no trabalho, nem puxado com o jugo,

[[v5-21-4]]

^<<v5-21-4,4>>^ e a trarão a um vale de águas correntes, que não foi lavrado, nem semeado; e ali, naquele vale, desnucarão a novilha.

[[v5-21-5]]

^<<v5-21-5,5>>^ Então se aproximarão os sacerdotes, filhos de Levi, porque o Senhor , o Deus de vocês, os escolheu para o servirem, para abençoarem em nome do Senhor  e, por sua palavra, decidirem toda demanda e todo caso de violência.

[[v5-21-6]]

^<<v5-21-6,6>>^ Todos os anciãos dessa cidade mais próxima do morto lavarão as mãos sobre a novilha desnucada no vale

[[v5-21-7]]

^<<v5-21-7,7>>^ e dirão: "As nossas mãos não derramaram este sangue, e os nossos olhos não viram quem o derramou.

[[v5-21-8]]

^<<v5-21-8,8>>^ Perdoa o teu povo de Israel, que tu, ó Senhor , resgataste, e não ponhas a culpa do sangue inocente no meio do teu povo de Israel." E a culpa daquele sangue lhe será perdoada.

[[v5-21-9]]

^<<v5-21-9,9>>^ Assim vocês eliminarão a culpa do sangue inocente do meio de vocês, pois farão o que é reto aos olhos do Senhor .

[[v5-21-10]]

^<<v5-21-10,10>>^ Quando vocês saírem para fazer guerra aos seus inimigos, e o Senhor , seu Deus, os entregar nas suas mãos e vocês fizerem prisioneiros de guerra,

[[v5-21-11]]

^<<v5-21-11,11>>^ se algum de vocês vir entre eles uma mulher bonita, gostar dela e quiser tomá-la por esposa,

[[v5-21-12]]

^<<v5-21-12,12>>^ deve levá-la para casa, onde ela rapará a cabeça, cortará as unhas,

[[v5-21-13]]

^<<v5-21-13,13>>^ e trocará a roupa que estava usando ao ser capturada. Ela permanecerá em casa e ficará de luto pelo pai e pela mãe durante um mês. Depois disto você pode tomá-la; você será o seu marido e ela será a sua mulher.

[[v5-21-14]]

^<<v5-21-14,14>>^ E, se você não gostar mais dela, deixe que ela vá para onde quiser. Você não pode vendê-la por dinheiro nem maltratá-la, porque a humilhou.

[[v5-21-15]]

^<<v5-21-15,15>>^ — Se um homem tiver duas mulheres, uma a quem ama e outra a quem não ama, e as duas lhe derem filhos, e o primogênito for da que ele não ama,

[[v5-21-16]]

^<<v5-21-16,16>>^ no dia em que repartir a herança entre os filhos, não poderá dar a primogenitura ao filho da amada, preferindo-o ao filho da que ele não ama e que é de fato o primogênito.

[[v5-21-17]]

^<<v5-21-17,17>>^ Pelo contrário, deve reconhecer por primogênito o filho da mulher que ele não ama, dando-lhe dobrada porção de tudo o que possuir, porque aquele é o primogênito do seu vigor; o direito da primogenitura é dele.

[[v5-21-18]]

^<<v5-21-18,18>>^ — Se alguém tiver um filho teimoso e rebelde, que não obedece à voz de seu pai nem à voz de sua mãe e, mesmo quando castigado, não lhes dá ouvidos,

[[v5-21-19]]

^<<v5-21-19,19>>^ seu pai e sua mãe o pegarão e o levarão aos anciãos da cidade, junto ao portão daquele lugar,

[[v5-21-20]]

^<<v5-21-20,20>>^ e dirão: "Este nosso filho é rebelde e teimoso, não dá ouvidos à nossa voz, é comilão e beberrão."

[[v5-21-21]]

^<<v5-21-21,21>>^ Então todos os homens da cidade o apedrejarão até que morra. Assim vocês eliminarão o mal do meio de vocês; todo o Israel ouvirá e temerá.

[[v5-21-22]]

^<<v5-21-22,22>>^ — Se alguém tiver cometido um pecado que é passível da pena de morte, e tiver sido morto, e vocês o pendurarem num madeiro,

[[v5-21-23]]

^<<v5-21-23,23>>^ o seu cadáver não deve permanecer no madeiro durante a noite. É preciso sepultá-lo no mesmo dia, pois o que for pendurado no madeiro é maldito de Deus. Assim vocês não contaminarão a terra que o Senhor , seu Deus, lhes dá por herança.

'''

xref:005-deuteronomio/005-deuteronomio-020.adoc#v5-20-0[&#60; Capítulo Anterior] | <<v5-21-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-022.adoc#v5-22-0[Próximo Capítulo &#62;]