include::./index.adoc[]

[[v5-16-0]]
=== Deuteronômio, 16
// naa ?, NAA - Nova Almeida Atualizada

[[v5-16-1]]

^<<v5-16-1,1>>^ — Guardem o mês de abibe e celebrem a Páscoa do Senhor , seu Deus, porque, no mês de abibe, o Senhor , seu Deus, os tirou do Egito, de noite.

[[v5-16-2]]

^<<v5-16-2,2>>^ Sacrifiquem como oferta de Páscoa ao Senhor , seu Deus, um animal do rebanho ou do gado, no lugar que o Senhor  escolher para ali fazer habitar o seu nome.

[[v5-16-3]]

^<<v5-16-3,3>>^ Na Páscoa, vocês não devem comer pão fermentado. Durante sete dias, comam pães sem fermento, o pão da aflição — porque às pressas vocês saíram do Egito —, para que todos os dias da vida vocês se lembrem do dia em que saíram da terra do Egito.

[[v5-16-4]]

^<<v5-16-4,4>>^ Durante os sete dias nenhum fermento deve ser encontrado com vocês, em todo o seu território. Também da carne do animal que vocês sacrificarem à tarde, no primeiro dia, nada deve ficar até a manhã seguinte.

[[v5-16-5]]

^<<v5-16-5,5>>^ Vocês não podem sacrificar a Páscoa em nenhuma das cidades que o Senhor , seu Deus, lhes dá,

[[v5-16-6]]

^<<v5-16-6,6>>^ a não ser no lugar que o Senhor , seu Deus, escolher para ali fazer habitar o seu nome. Ali vocês devem oferecer o sacrifício da Páscoa à tarde, ao pôr do sol, na hora em que saíram do Egito.

[[v5-16-7]]

^<<v5-16-7,7>>^ Cozinhem e comam a carne no lugar que o Senhor , seu Deus, escolher; na manhã do dia seguinte vocês podem voltar para as suas tendas.

[[v5-16-8]]

^<<v5-16-8,8>>^ Durante seis dias comam pães sem fermento, e, no sétimo dia, haverá reunião solene ao Senhor , seu Deus; não façam nenhum trabalho nesse dia.

[[v5-16-9]]

^<<v5-16-9,9>>^ — Contem sete semanas. Quando começarem a fazer a colheita, iniciem a contagem das sete semanas.

[[v5-16-10]]

^<<v5-16-10,10>>^ Celebrem a Festa das Semanas ao Senhor , seu Deus, com ofertas voluntárias trazidas por vocês, segundo o Senhor , seu Deus, os tiver abençoado.

[[v5-16-11]]

^<<v5-16-11,11>>^ Alegrem-se diante do Senhor , seu Deus, vocês, os seus filhos, as suas filhas, os seus escravos, as suas escravas, os levitas que moram nas cidades de vocês, os estrangeiros, os órfãos e as viúvas que estão no meio de vocês, no lugar que o Senhor , seu Deus, escolher para ali fazer habitar o seu nome.

[[v5-16-12]]

^<<v5-16-12,12>>^ Lembrem-se de que vocês foram escravos no Egito, guardem e cumpram estes estatutos.

[[v5-16-13]]

^<<v5-16-13,13>>^ — A Festa dos Tabernáculos deve ser celebrada durante sete dias, depois que tiverem recolhido o produto da eira e do lagar.

[[v5-16-14]]

^<<v5-16-14,14>>^ Alegrem-se nessa festa, vocês, os seus filhos, as suas filhas, os seus escravos, as suas escravas, os levitas, os estrangeiros, os órfãos e as viúvas que moram nas cidades de vocês.

[[v5-16-15]]

^<<v5-16-15,15>>^ Durante sete dias vocês celebrarão a festa ao Senhor , seu Deus, no lugar que o Senhor  escolher. Porque o Senhor , o Deus de vocês, os abençoará em todas as suas colheitas e em tudo o que vocês fizerem, e por isso vocês certamente poderão se alegrar.

[[v5-16-16]]

^<<v5-16-16,16>>^ — Três vezes por ano, todos os homens israelitas devem apresentar-se diante do Senhor , seu Deus, no lugar que ele escolher, na Festa dos Pães sem Fermento, na Festa das Semanas e na Festa dos Tabernáculos. Não devem se apresentar de mãos vazias diante do Senhor ,

[[v5-16-17]]

^<<v5-16-17,17>>^ mas cada um oferecerá na proporção em que possa dar, segundo a bênção que o Senhor , seu Deus, lhe houver concedido.

[[v5-16-18]]

^<<v5-16-18,18>>^ — Nomeiem juízes e oficiais em todas as cidades que o Senhor , seu Deus, lhes der entre as suas tribos, para que julguem o povo com justiça.

[[v5-16-19]]

^<<v5-16-19,19>>^ Vocês não devem torcer a justiça, não devem tratar as pessoas com parcialidade, nem aceitar suborno, porque o suborno cega os olhos dos sábios e subverte a causa dos justos.

[[v5-16-20]]

^<<v5-16-20,20>>^ Sigam a justiça, somente a justiça, para que vivam e herdem a terra que o Senhor , seu Deus, lhes dá.

[[v5-16-21]]

^<<v5-16-21,21>>^ Não estabeleçam um poste da deusa Aserá, plantando qualquer árvore junto ao altar que vocês construírem para o Senhor , seu Deus.

[[v5-16-22]]

^<<v5-16-22,22>>^ Nem levantem coluna, porque isso o Senhor , o Deus de vocês, odeia.

'''

xref:005-deuteronomio/005-deuteronomio-015.adoc#v5-15-0[&#60; Capítulo Anterior] | <<v5-16-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-017.adoc#v5-17-0[Próximo Capítulo &#62;]