include::./index.adoc[]

[[v5-32-0]]
=== Deuteronômio, 32
// naa ?, NAA - Nova Almeida Atualizada

[[v5-32-1]]

^<<v5-32-1,1>>^ Inclinem os ouvidos, ó céus, e falarei; e ouça a terra as palavras da minha boca.

[[v5-32-2]]

^<<v5-32-2,2>>^ Goteje a minha doutrina como a chuva, destile a minha palavra como o orvalho, como chuvisco sobre a relva e como gotas de água sobre a erva.

[[v5-32-3]]

^<<v5-32-3,3>>^ Porque proclamarei o nome do Senhor . Louvem a grandeza do nosso Deus.

[[v5-32-4]]

^<<v5-32-4,4>>^ Eis a Rocha! Suas obras são perfeitas, porque todos os seus caminhos são juízo. Deus é fidelidade, e nele não há injustiça; é justo e reto.

[[v5-32-5]]

^<<v5-32-5,5>>^ Procederam corruptamente contra ele, já não são seus filhos, e sim suas manchas; é geração perversa e deformada.

[[v5-32-6]]

^<<v5-32-6,6>>^ É assim que vocês retribuem ao Senhor , povo tolo e insensato? Não é ele o Pai de vocês, que os adquiriu, que os fez e estabeleceu?

[[v5-32-7]]

^<<v5-32-7,7>>^ Lembrem-se dos dias da antiguidade, atentem para os anos de sucessivas gerações. Perguntem aos seus pais, e eles informarão; aos seus anciãos, e eles lhes dirão.

[[v5-32-8]]

^<<v5-32-8,8>>^ Quando o Altíssimo distribuía as heranças às nações, quando separava os filhos dos homens uns dos outros, fixou as fronteiras dos povos, segundo o número dos filhos de Israel.

[[v5-32-9]]

^<<v5-32-9,9>>^ Porque a porção do Senhor é o seu povo; Jacó é a parte da sua herança.

[[v5-32-10]]

^<<v5-32-10,10>>^ Ele o encontrou numa terra deserta e num ermo solitário povoado de uivos; rodeou-o e cuidou dele, guardou-o como a menina dos olhos.

[[v5-32-11]]

^<<v5-32-11,11>>^ Como a águia desperta a sua ninhada e voeja sobre os seus filhotes, estende as asas e, tomando-os, os leva sobre elas,

[[v5-32-12]]

^<<v5-32-12,12>>^ assim, só o Senhor  guiou o seu povo, e não havia com ele deus estranho.

[[v5-32-13]]

^<<v5-32-13,13>>^ Ele o fez cavalgar sobre os altos da terra, comer o produto do campo, chupar mel da rocha e azeite da pedra dura;

[[v5-32-14]]

^<<v5-32-14,14>>^ alimentou-o com coalhada de vacas e leite de ovelhas, com a gordura dos cordeiros, dos carneiros que pastam em Basã e dos bodes, com o melhor trigo. E vocês beberam o sangue das uvas, o vinho.

[[v5-32-15]]

^<<v5-32-15,15>>^ Mas Jesurum engordou e deu coices — vocês engordaram, engrossaram, se estufaram! Ele abandonou a Deus, que o fez, desprezou a Rocha da sua salvação.

[[v5-32-16]]

^<<v5-32-16,16>>^ Com deuses estranhos eles provocaram ciúmes, com abominações o irritaram.

[[v5-32-17]]

^<<v5-32-17,17>>^ Ofereceram sacrifícios aos demônios, não a Deus; sacrificaram a deuses que não conheceram, novos deuses que vieram há pouco, diante dos quais os seus pais não tremeram.

[[v5-32-18]]

^<<v5-32-18,18>>^ Não se lembraram da Rocha que os gerou; e se esqueceram do Deus que os fez nascer.

[[v5-32-19]]

^<<v5-32-19,19>>^ O Senhor  viu isso e os desprezou, por causa da provocação de seus filhos e suas filhas.

[[v5-32-20]]

^<<v5-32-20,20>>^ Ele disse: "Esconderei deles o rosto, verei qual será o seu fim; porque são uma geração perversa, filhos em quem não há lealdade.

[[v5-32-21]]

^<<v5-32-21,21>>^ Provocaram ciúmes em mim com aquilo que não é Deus; com seus ídolos me provocaram à ira. Portanto, provocarei ciúmes neles com aquele que não é povo; com uma nação tola os despertarei à ira.

[[v5-32-22]]

^<<v5-32-22,22>>^ Porque um fogo se acendeu no meu furor e queimará até o mais profundo do inferno, consumirá a terra e as suas colheitas e incendiará os fundamentos dos montes.

[[v5-32-23]]

^<<v5-32-23,23>>^ Amontoarei males sobre eles; esgotarei as minhas flechas contra eles.

[[v5-32-24]]

^<<v5-32-24,24>>^ Consumidos serão pela fome, devorados pela febre e peste violenta. Contra eles enviarei animais selvagens e veneno de criaturas que se arrastam no pó.

[[v5-32-25]]

^<<v5-32-25,25>>^ Do lado de fora, a espada causará devastação; em casa, o pavor, tanto ao jovem como à virgem, tanto à criança de peito como ao homem de cabelos brancos.

[[v5-32-26]]

^<<v5-32-26,26>>^ Eu disse que os espalharia por todos os cantos e que faria cessar a sua memória dentre os homens,

[[v5-32-27]]

^<<v5-32-27,27>>^ se eu não tivesse receado a provocação do inimigo, para que os seus adversários não se iludam, para que não digam: ‘A nossa mão prevaleceu, e não foi o Senhor quem fez tudo isto.’

[[v5-32-28]]

^<<v5-32-28,28>>^ Porque o meu povo é gente sem juízo, e neles não há entendimento.

[[v5-32-29]]

^<<v5-32-29,29>>^ Quem dera fossem eles sábios! Então entenderiam isto e compreenderiam qual será o seu fim.

[[v5-32-30]]

^<<v5-32-30,30>>^ Como poderia um só perseguir mil, e dois fazerem fugir dez mil, se a sua Rocha não os tivesse vendido, se o Senhor não os tivesse entregue?

[[v5-32-31]]

^<<v5-32-31,31>>^ Porque a rocha deles não é como a nossa Rocha; e os próprios inimigos o atestam.

[[v5-32-32]]

^<<v5-32-32,32>>^ Porque a vinha deles é da vinha de Sodoma e dos campos de Gomorra; as suas uvas são uvas de veneno, seus cachos são amargos;

[[v5-32-33]]

^<<v5-32-33,33>>^ o vinho deles é veneno de serpentes e peçonha terrível de víboras.

[[v5-32-34]]

^<<v5-32-34,34>>^ Não está isto guardado comigo, selado nos meus tesouros?

[[v5-32-35]]

^<<v5-32-35,35>>^ A mim pertence a vingança, a retribuição, a seu tempo, quando o pé deles resvalar; porque o dia da sua calamidade está próximo, e o seu destino se apressa em chegar."

[[v5-32-36]]

^<<v5-32-36,36>>^ Porque o Senhor  fará justiça ao seu povo e se compadecerá dos seus servos, quando notar que o poder deles se foi, e já não há nem escravo nem livre.

[[v5-32-37]]

^<<v5-32-37,37>>^ Então dirá: "Onde estão os seus deuses? E a rocha em quem confiavam?

[[v5-32-38]]

^<<v5-32-38,38>>^ Deuses que comiam a gordura de seus sacrifícios e bebiam o vinho de suas libações? Que eles se levantem e os ajudem, para que haja um esconderijo para vocês!

[[v5-32-39]]

^<<v5-32-39,39>>^ Vejam, agora, que eu, sim, eu sou Ele, e que não há nenhum deus além de mim; eu mato e eu faço viver; eu firo e eu saro; e não há quem possa livrar alguém da minha mão.

[[v5-32-40]]

^<<v5-32-40,40>>^ Levanto a mão aos céus e afirmo por minha vida eterna:

[[v5-32-41]]

^<<v5-32-41,41>>^ se eu afiar a minha espada reluzente, e a minha mão exercitar o juízo, tomarei vingança contra os meus adversários e retribuirei aos que me odeiam.

[[v5-32-42]]

^<<v5-32-42,42>>^ Embriagarei as minhas setas de sangue — a minha espada comerá carne —, do sangue dos mortos e dos prisioneiros, das cabeças cabeludas do inimigo."

[[v5-32-43]]

^<<v5-32-43,43>>^ Ó nações, louvem com o povo de Deus, porque o Senhor  vingará o sangue dos seus servos, tomará vingança dos seus adversários e fará expiação pela terra do seu povo.

[[v5-32-44]]

^<<v5-32-44,44>>^ Moisés veio e falou todas as palavras deste cântico aos ouvidos do povo, ele e Josué, filho de Num.

[[v5-32-45]]

^<<v5-32-45,45>>^ Quando Moisés acabou de falar todas estas palavras a todo o Israel,

[[v5-32-46]]

^<<v5-32-46,46>>^ disse-lhes: — Guardem no coração todas as palavras que hoje testifico entre vocês, para que ordenem a seus filhos que tratem de cumprir todas as palavras desta Lei.

[[v5-32-47]]

^<<v5-32-47,47>>^ Porque esta palavra não é para vocês coisa vã; pelo contrário, é a sua vida; e, por esta mesma palavra, vocês prolongarão os dias na terra em que, passando o Jordão, vocês vão entrar e da qual tomarão posse.

[[v5-32-48]]

^<<v5-32-48,48>>^ Naquele mesmo dia, o Senhor  falou a Moisés, dizendo:

[[v5-32-49]]

^<<v5-32-49,49>>^ — Suba a este monte de Abarim, ao monte Nebo, que está na terra de Moabe, em frente de Jericó, e veja a terra de Canaã, que dou como propriedade aos filhos de Israel.

[[v5-32-50]]

^<<v5-32-50,50>>^ Você vai morrer no monte, ao qual terá subido, e será reunido ao seu povo, como Arão, o seu irmão, morreu no monte Hor e foi reunido ao seu povo.

[[v5-32-51]]

^<<v5-32-51,51>>^ Porque vocês foram infiéis a mim no meio dos filhos de Israel, nas águas de Meribá de Cades, no deserto de Zim, pois não me santificaram no meio dos filhos de Israel.

[[v5-32-52]]

^<<v5-32-52,52>>^ Por isso você verá a terra à sua frente, mas não entrará nela, na terra que dou aos filhos de Israel.

'''

xref:005-deuteronomio/005-deuteronomio-031.adoc#v5-31-0[&#60; Capítulo Anterior] | <<v5-32-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-033.adoc#v5-33-0[Próximo Capítulo &#62;]