include::./index.adoc[]

[[v5-2-0]]
=== Deuteronômio, 2
// naa ?, NAA - Nova Almeida Atualizada

[[v5-2-1]]

^<<v5-2-1,1>>^ — Depois, voltamos e seguimos para o deserto, na direção do mar Vermelho, como o Senhor  me havia ordenado, e por muitos dias rodeamos os montes de Seir.

[[v5-2-2]]

^<<v5-2-2,2>>^ Então o Senhor  me falou, dizendo:

[[v5-2-3]]

^<<v5-2-3,3>>^ "Vocês já rodearam bastante estes montes; agora sigam para o norte.

[[v5-2-4]]

^<<v5-2-4,4>>^ Ordene ao povo, dizendo: ‘Vocês passarão pelo território de seus irmãos, os filhos de Esaú, que habitam em Seir. Eles terão medo de vocês; portanto, tenham muito cuidado.

[[v5-2-5]]

^<<v5-2-5,5>>^ Não entrem em conflito com eles, porque da terra deles não darei a vocês nem mesmo a pisada da planta de um pé; pois a Esaú dei por herança os montes de Seir.

[[v5-2-6]]

^<<v5-2-6,6>>^ Comprarão deles, por dinheiro, comida, para que possam comer, e também água, para que possam beber.’"

[[v5-2-7]]

^<<v5-2-7,7>>^ Pois o Senhor , seu Deus, os abençoou em tudo o que vocês fizeram. Ele sabe que vocês estão andando por este grande deserto. Durante estes quarenta anos o Senhor , seu Deus, esteve com vocês; coisa nenhuma lhes faltou.

[[v5-2-8]]

^<<v5-2-8,8>>^ — Assim, passamos ao lado do território de nossos irmãos, os filhos de Esaú, que habitavam em Seir, bem como do caminho da Arabá, de Elate e de Eziom-Geber. Voltamos e seguimos o caminho do deserto de Moabe.

[[v5-2-9]]

^<<v5-2-9,9>>^ Então o Senhor  me disse: "Não provoque Moabe e não entre em conflito com eles, porque não darei a você herança da terra deles; porque dei Ar em herança aos filhos de Ló."

[[v5-2-10]]

^<<v5-2-10,10>>^ (Antigamente os emins habitavam nela, povo grande, numeroso e alto como os anaquins.

[[v5-2-11]]

^<<v5-2-11,11>>^ Também eles foram considerados refains, como os anaquins; e os moabitas os chamavam de emins.

[[v5-2-12]]

^<<v5-2-12,12>>^ Antigamente também os horeus habitavam em Seir; porém os filhos de Esaú os expulsaram dali, os destruíram de diante de si e habitaram no lugar deles, assim como Israel fez à terra da sua herança, que o Senhor  lhes tinha dado.)

[[v5-2-13]]

^<<v5-2-13,13>>^ "Agora levantem-se e passem o ribeiro de Zerede." — Assim, passamos o ribeiro de Zerede.

[[v5-2-14]]

^<<v5-2-14,14>>^ O tempo que caminhamos, desde Cades-Barneia até passarmos o ribeiro de Zerede, foram trinta e oito anos, até que toda aquela geração dos homens de guerra desapareceu do meio do arraial, como o Senhor  lhes havia jurado.

[[v5-2-15]]

^<<v5-2-15,15>>^ A mão do Senhor  estava contra eles, para os destruir do meio do arraial, até que todos desaparecessem.

[[v5-2-16]]

^<<v5-2-16,16>>^ — Quando todos os homens de guerra já haviam desaparecido do meio do povo, consumidos pela morte,

[[v5-2-17]]

^<<v5-2-17,17>>^ o Senhor  me falou, dizendo:

[[v5-2-18]]

^<<v5-2-18,18>>^ "Hoje você passará por Ar, na fronteira de Moabe,

[[v5-2-19]]

^<<v5-2-19,19>>^ e chegará até diante dos filhos de Amom. Não os provoque e não entre em conflito com eles, porque da terra dos filhos de Amom não lhe darei herança, porque a tenho dado por herança aos filhos de Ló."

[[v5-2-20]]

^<<v5-2-20,20>>^ (Também esta é considerada terra dos refains; antigamente habitavam nela refains, e os amonitas os chamavam de zanzumins,

[[v5-2-21]]

^<<v5-2-21,21>>^ povo grande, numeroso e alto como os anaquins; o Senhor  os destruiu diante dos amonitas; estes os expulsaram dali e habitaram no lugar deles.

[[v5-2-22]]

^<<v5-2-22,22>>^ O Senhor  fez com eles assim como fez com os filhos de Esaú que habitavam em Seir, de diante dos quais destruiu os horeus. Os filhos de Esaú os expulsaram e habitaram no lugar deles até hoje;

[[v5-2-23]]

^<<v5-2-23,23>>^ também os caftorins que saíram de Caftor destruíram os aveus, que habitavam em aldeias até Gaza, e habitaram no lugar deles.)

[[v5-2-24]]

^<<v5-2-24,24>>^ "Levantem-se, sigam adiante e passem o ribeiro de Arnom; eis que entrego nas mãos de vocês Seom, amorreu, rei de Hesbom, bem como a terra dele; comecem a ocupação e entrem em guerra com eles.

[[v5-2-25]]

^<<v5-2-25,25>>^ Hoje começarei a incutir o terror e o medo de vocês aos povos que estão debaixo do céu; os que ouvirem a sua fama tremerão diante de vocês e ficarão angustiados."

[[v5-2-26]]

^<<v5-2-26,26>>^ — Então desde o deserto de Quedemote mandei mensageiros a Seom, rei de Hesbom, com palavras de paz, dizendo:

[[v5-2-27]]

^<<v5-2-27,27>>^ "Deixe-nos passar pela sua terra. Iremos somente pela estrada; não nos desviaremos para a direita nem para a esquerda.

[[v5-2-28]]

^<<v5-2-28,28>>^ Você nos venderá o alimento que comermos e também a água que bebermos; tão somente deixe-nos passar a pé,

[[v5-2-29]]

^<<v5-2-29,29>>^ como fizeram os filhos de Esaú, que habitam em Seir, e os moabitas, que habitam em Ar, até que passemos o Jordão e entremos na terra que o Senhor , nosso Deus, nos está dando."

[[v5-2-30]]

^<<v5-2-30,30>>^ Mas Seom, rei de Hesbom, não nos quis deixar passar pela terra dele, porque o Senhor , o Deus de vocês, havia endurecido o espírito dele e tornado inflexível o seu coração, para entregá-lo nas mãos de vocês, como hoje se vê.

[[v5-2-31]]

^<<v5-2-31,31>>^ — O Senhor  me disse: "Eis que já comecei a dar a você Seom e a terra dele; comece agora a tomar posse do país dele."

[[v5-2-32]]

^<<v5-2-32,32>>^ Então Seom saiu ao nosso encontro, ele e todo o seu povo, para lutar contra nós em Jaza.

[[v5-2-33]]

^<<v5-2-33,33>>^ E o Senhor , nosso Deus, o entregou em nossas mãos e nós o derrotamos, a ele, aos filhos dele e a todo o seu povo.

[[v5-2-34]]

^<<v5-2-34,34>>^ Naquele tempo, tomamos todas as suas cidades e a cada uma destruímos com os seus homens, mulheres e crianças; não deixamos nenhum sobrevivente.

[[v5-2-35]]

^<<v5-2-35,35>>^ Somente tomamos, por presa, o gado e o despojo das cidades conquistadas.

[[v5-2-36]]

^<<v5-2-36,36>>^ Desde Aroer, que está à beira do vale de Arnom, e a cidade que nele está, até Gileade, não houve nenhuma cidade que fosse alta demais para nós; tudo isto o Senhor , nosso Deus, nos entregou.

[[v5-2-37]]

^<<v5-2-37,37>>^ Vocês apenas não se aproximaram da terra dos filhos de Amom, nem de toda a região que fica às margens do ribeiro de Jaboque, nem das cidades da região montanhosa, nem de qualquer outro lugar que o Senhor , nosso Deus, nos havia proibido de atacar.

'''

xref:005-deuteronomio/005-deuteronomio-001.adoc#v5-1-0[&#60; Capítulo Anterior] | <<v5-2-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-003.adoc#v5-3-0[Próximo Capítulo &#62;]