include::./index.adoc[]

[[v5-10-0]]
=== Deuteronômio, 10
// naa ?, NAA - Nova Almeida Atualizada

[[v5-10-1]]

^<<v5-10-1,1>>^ — Naquele tempo, o Senhor  me disse: "Corte duas tábuas de pedra, como as primeiras, e suba o monte para encontrar-se comigo. Faça também uma arca de madeira.

[[v5-10-2]]

^<<v5-10-2,2>>^ Escreverei nas duas tábuas as palavras que estavam nas primeiras, e que você quebrou; depois você as colocará na arca."

[[v5-10-3]]

^<<v5-10-3,3>>^ — Assim, fiz uma arca de madeira de acácia, cortei duas tábuas de pedra, como as primeiras, e subi o monte com as duas tábuas na mão.

[[v5-10-4]]

^<<v5-10-4,4>>^ Então o Senhor  escreveu nas tábuas, segundo a primeira escritura, os dez mandamentos que ele havia falado a vocês no dia da congregação, no monte, no meio do fogo. Depois o Senhor  entregou as tábuas para mim.

[[v5-10-5]]

^<<v5-10-5,5>>^ Então me virei e desci do monte, e pus as tábuas na arca que eu havia feito; e ali estão, como o Senhor  me ordenou.

[[v5-10-6]]

^<<v5-10-6,6>>^ (Os filhos de Israel partiram de Beerote-Benê-Jaacã e foram para Mosera. Ali morreu Arão e ali foi sepultado. Eleazar, seu filho, oficiou como sacerdote em seu lugar.

[[v5-10-7]]

^<<v5-10-7,7>>^ Dali partiram para Gudgodá e de Gudgodá foram para Jotbatá, terra de ribeiros de águas.)

[[v5-10-8]]

^<<v5-10-8,8>>^ — Por esse mesmo tempo, o Senhor  separou a tribo de Levi para levar a arca da aliança do Senhor , para estar diante do Senhor , para o servir e para abençoar em seu nome até o dia de hoje.

[[v5-10-9]]

^<<v5-10-9,9>>^ Por isso Levi não tem parte nem herança com os seus irmãos; o Senhor  é a sua herança, como o Senhor , o Deus de vocês, lhe prometeu.

[[v5-10-10]]

^<<v5-10-10,10>>^ — Permaneci no monte, como da primeira vez, quarenta dias e quarenta noites. Mais uma vez o Senhor  me ouviu e não quis destruir vocês.

[[v5-10-11]]

^<<v5-10-11,11>>^ Porém o Senhor  me disse: "Levante-se e ponha-se a caminho diante do povo, para que entrem e tomem posse da terra que, sob juramento, prometi dar aos pais deles."

[[v5-10-12]]

^<<v5-10-12,12>>^ — E agora, Israel, o que é que o Senhor  requer de vocês? Não é que vocês temam o Senhor , seu Deus, andem em todos os seus caminhos, amem e sirvam o Senhor , seu Deus, de todo o coração e de toda a alma,

[[v5-10-13]]

^<<v5-10-13,13>>^ para guardarem os mandamentos do Senhor  e os seus estatutos que hoje lhes ordeno, para o bem de vocês?

[[v5-10-14]]

^<<v5-10-14,14>>^ Eis que os céus e os céus dos céus são do Senhor , o Deus de vocês; a ele pertencem a terra e tudo o que nela há.

[[v5-10-15]]

^<<v5-10-15,15>>^ Mas o Senhor  se afeiçoou tão somente aos pais de vocês para os amar; e a vocês, descendentes deles, ele escolheu do meio de todos os povos, como hoje se vê.

[[v5-10-16]]

^<<v5-10-16,16>>^ Portanto, circuncidem o coração de vocês e deixem de ser teimosos.

[[v5-10-17]]

^<<v5-10-17,17>>^ Pois o Senhor , o Deus de vocês, é o Deus dos deuses e o Senhor dos senhores, o Deus grande, poderoso e temível, que não trata as pessoas com parcialidade, nem aceita suborno.

[[v5-10-18]]

^<<v5-10-18,18>>^ Ele faz justiça aos órfãos e às viúvas e ama os estrangeiros, dando-lhes comida e roupa.

[[v5-10-19]]

^<<v5-10-19,19>>^ Portanto, amem os estrangeiros, porque vocês foram estrangeiros na terra do Egito.

[[v5-10-20]]

^<<v5-10-20,20>>^ Temam o Senhor , seu Deus, e sirvam a ele; sejam fiéis a ele e jurem somente pelo seu nome.

[[v5-10-21]]

^<<v5-10-21,21>>^ Ele é o seu louvor e o Deus de vocês, que em favor de vocês fez estas grandes e temíveis coisas que vocês viram com os seus próprios olhos.

[[v5-10-22]]

^<<v5-10-22,22>>^ Quando os pais de vocês desceram ao Egito, eram apenas setenta pessoas; agora o Senhor , seu Deus, fez de vocês uma multidão tão numerosa como as estrelas do céu.

'''

xref:005-deuteronomio/005-deuteronomio-009.adoc#v5-9-0[&#60; Capítulo Anterior] | <<v5-10-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-011.adoc#v5-11-0[Próximo Capítulo &#62;]