include::./index.adoc[]

[[v5-33-0]]
=== Deuteronômio, 33
// naa ?, NAA - Nova Almeida Atualizada

[[v5-33-1]]

^<<v5-33-1,1>>^ Esta é a bênção que Moisés, homem de Deus, deu aos filhos de Israel, antes da sua morte.

[[v5-33-2]]

^<<v5-33-2,2>>^ Ele disse: O Senhor  veio do Sinai e lhes alvoreceu de Seir; resplandeceu desde o monte Parã. Ele veio das miríades de santos; à sua direita, havia para eles o fogo da lei.

[[v5-33-3]]

^<<v5-33-3,3>>^ Na verdade, amas os povos; todos os teus santos estão na tua mão; eles se colocam a teus pés e aprendem das tuas palavras.

[[v5-33-4]]

^<<v5-33-4,4>>^ Moisés nos deu a Lei, a herança da congregação de Jacó.

[[v5-33-5]]

^<<v5-33-5,5>>^ O Senhor  se tornou rei em Jesurum, quando se congregaram os chefes do povo com as tribos de Israel.

[[v5-33-6]]

^<<v5-33-6,6>>^ Que Rúben viva e não morra; e que não sejam poucos os seus homens!

[[v5-33-7]]

^<<v5-33-7,7>>^ Isto é o que disse de Judá: Ouve, ó Senhor , a voz de Judá e faze com que volte ao seu povo; com as tuas mãos, luta por ele e sê tu ajuda contra os seus inimigos.

[[v5-33-8]]

^<<v5-33-8,8>>^ De Levi disse: Dá, ó Deus, o teu Tumim e o teu Urim para o homem fidedigno, que tu provaste em Massá, com quem discutiste nas águas de Meribá;

[[v5-33-9]]

^<<v5-33-9,9>>^ aquele que disse a seu pai e a sua mãe: "Nunca os vi"; e que não conheceu os seus irmãos e não estimou os seus filhos, pois guardou a tua palavra e observou a tua aliança.

[[v5-33-10]]

^<<v5-33-10,10>>^ Ensina os teus juízos a Jacó e a tua lei, a Israel; oferece incenso às tuas narinas e holocausto, sobre o teu altar.

[[v5-33-11]]

^<<v5-33-11,11>>^ Abençoa o seu poder, ó Senhor , e aceita a obra das suas mãos; fere os lombos dos que se levantam contra ele e o odeiam, para que nunca mais se levantem.

[[v5-33-12]]

^<<v5-33-12,12>>^ De Benjamim disse: O amado do Senhor  habitará seguro com ele; todo o dia o Senhor  o protegerá, e ele descansará nos seus braços.

[[v5-33-13]]

^<<v5-33-13,13>>^ De José disse: Bendita do Senhor  seja a sua terra, com o que é mais excelente dos céus, do orvalho e das profundezas;

[[v5-33-14]]

^<<v5-33-14,14>>^ com o que é mais excelente daquilo que o sol amadurece e daquilo que os meses produzem;

[[v5-33-15]]

^<<v5-33-15,15>>^ com o que é mais excelente dos montes antigos e mais excelente das colinas eternas;

[[v5-33-16]]

^<<v5-33-16,16>>^ com o que é mais excelente da terra e da sua plenitude e da bondade daquele que apareceu na sarça. Que tudo isto venha sobre a cabeça de José, sobre a cabeça do príncipe entre seus irmãos.

[[v5-33-17]]

^<<v5-33-17,17>>^ Ele tem a imponência do primogênito de um touro, e os seus chifres são como os de um boi selvagem; com eles rechaçará todos os povos até as extremidades da terra. Tais, pois, são as miríades de Efraim, e tais são os milhares de Manassés.

[[v5-33-18]]

^<<v5-33-18,18>>^ De Zebulom disse: Alegre-se, Zebulom, nas suas viagens, e você, Issacar, nas suas tendas.

[[v5-33-19]]

^<<v5-33-19,19>>^ Os dois chamarão os povos ao monte; ali oferecerão sacrifícios aceitáveis, porque sugam a abundância dos mares e os tesouros escondidos da areia.

[[v5-33-20]]

^<<v5-33-20,20>>^ De Gade disse: Bendito aquele que expande o território de Gade! Como leoa ele fica à espreita e despedaça o braço e o alto da cabeça.

[[v5-33-21]]

^<<v5-33-21,21>>^ Ficou com a melhor parte, porque ali estava escondida a porção que cabe ao chefe; ele veio com os chefes do povo, executou a justiça do Senhor e os seus juízos para com Israel.

[[v5-33-22]]

^<<v5-33-22,22>>^ De Dã disse: Dã é um leãozinho que vem saltando de Basã.

[[v5-33-23]]

^<<v5-33-23,23>>^ De Naftali disse: Naftali receberá favores e, cheio da bênção do Senhor , possuirá o lago e o Sul.

[[v5-33-24]]

^<<v5-33-24,24>>^ De Aser disse: Bendito seja Aser entre os filhos de Jacó! Que ele seja favorecido pelos seus irmãos e banhe em azeite os seus pés.

[[v5-33-25]]

^<<v5-33-25,25>>^ Sejam de ferro e de bronze os seus ferrolhos, e que a sua paz dure como os seus dias.

[[v5-33-26]]

^<<v5-33-26,26>>^ Não há ninguém como Deus, ó Jesurum! Ele cavalga sobre os céus para ajudar você e com a sua alteza, sobre as nuvens.

[[v5-33-27]]

^<<v5-33-27,27>>^ O Deus eterno é a sua habitação e, por baixo de você, ele estende os braços eternos. Ele expulsou os inimigos de diante de você e disse: "Destrua-os".

[[v5-33-28]]

^<<v5-33-28,28>>^ Israel, pois, habitará seguro, a fonte de Jacó habitará a sós numa terra de cereal e de vinho; e os seus céus destilarão orvalho.

[[v5-33-29]]

^<<v5-33-29,29>>^ Feliz é você, ó Israel! Quem é como você? Povo salvo pelo Senhor , que é o escudo que o socorre, a espada que lhe dá alteza. Assim, os seus inimigos se sujeitarão a você, e você pisará os seus altos.

'''

xref:005-deuteronomio/005-deuteronomio-032.adoc#v5-32-0[&#60; Capítulo Anterior] | <<v5-33-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-034.adoc#v5-34-0[Próximo Capítulo &#62;]