include::./index.adoc[]

[[v5-18-0]]
=== Deuteronômio, 18
// naa ?, NAA - Nova Almeida Atualizada

[[v5-18-1]]

^<<v5-18-1,1>>^ — Os sacerdotes levitas e toda a tribo de Levi não terão parte nem herança em Israel; comerão das ofertas queimadas ao Senhor  e daquilo que lhes é devido.

[[v5-18-2]]

^<<v5-18-2,2>>^ Não terão herança no meio de seus compatriotas; o Senhor  é a herança deles, como ele mesmo lhes prometeu.

[[v5-18-3]]

^<<v5-18-3,3>>^ Será este, pois, o direito devido aos sacerdotes, da parte do povo, dos que oferecerem sacrifício, seja gado ou rebanho: devem dar ao sacerdote a espádua, as queixadas e o estômago.

[[v5-18-4]]

^<<v5-18-4,4>>^ Vocês devem dar-lhes as primícias do cereal, do vinho e do azeite e as primícias da tosquia das ovelhas.

[[v5-18-5]]

^<<v5-18-5,5>>^ Porque o Senhor , o Deus de vocês, escolheu os levitas e os filhos deles do meio de todas as tribos de Israel para ministrarem em nome do Senhor , todos os dias.

[[v5-18-6]]

^<<v5-18-6,6>>^ — Se um levita que estiver morando em qualquer das cidades de todo o Israel vier com todo o desejo da sua alma ao lugar que o Senhor  escolheu,

[[v5-18-7]]

^<<v5-18-7,7>>^ e ministrar em nome do Senhor , o Deus de vocês, como fazem todos os outros levitas que ali ministram diante do Senhor ,

[[v5-18-8]]

^<<v5-18-8,8>>^ ele deverá receber porção igual à dos outros levitas para comer, além das vendas do seu patrimônio.

[[v5-18-9]]

^<<v5-18-9,9>>^ — Quando vocês entrarem na terra que o Senhor , seu Deus, lhes der, não aprendam os costumes abomináveis daqueles povos.

[[v5-18-10]]

^<<v5-18-10,10>>^ Que não exista entre vocês ninguém que queime o seu filho ou a sua filha em sacrifício, nem que seja adivinho, prognosticador, agoureiro, feiticeiro,

[[v5-18-11]]

^<<v5-18-11,11>>^ encantador, necromante, praticante de magia, ou alguém que consulte os mortos,

[[v5-18-12]]

^<<v5-18-12,12>>^ pois todo aquele que faz tal coisa é abominação ao Senhor ; e por estas abominações o Senhor , o Deus de vocês, está expulsando esses povos de diante de vocês.

[[v5-18-13]]

^<<v5-18-13,13>>^ Sejam perfeitos para com o Senhor , seu Deus.

[[v5-18-14]]

^<<v5-18-14,14>>^ Porque as nações dessa terra que vocês vão possuir ouvem os prognosticadores e os adivinhos, mas o Senhor , o Deus de vocês, não permitiu que vocês fizessem tal coisa.

[[v5-18-15]]

^<<v5-18-15,15>>^ — O Senhor , seu Deus, fará com que do meio de vocês, do meio dos seus irmãos, se levante um profeta semelhante a mim; a ele vocês devem ouvir.

[[v5-18-16]]

^<<v5-18-16,16>>^ Porque isso foi o que vocês pediram ao Senhor , seu Deus, em Horebe, no dia em que o povo estava reunido. Vocês disseram: "Não nos faça ouvir de novo a voz do Senhor , nosso Deus, nem ver este grande fogo, para que não morramos."

[[v5-18-17]]

^<<v5-18-17,17>>^ Então o Senhor  me disse: "Eles estão corretos naquilo que disseram.

[[v5-18-18]]

^<<v5-18-18,18>>^ Farei com que se levante do meio de seus irmãos um profeta semelhante a você, em cuja boca porei as minhas palavras, e ele lhes falará tudo o que eu lhe ordenar.

[[v5-18-19]]

^<<v5-18-19,19>>^ De todo aquele que não ouvir as minhas palavras, que ele falar em meu nome, disso lhe pedirei contas."

[[v5-18-20]]

^<<v5-18-20,20>>^ — Porém o profeta que tiver a presunção de falar alguma palavra em meu nome, algo que eu não mandei que falasse, ou o que falar em nome de outros deuses, esse profeta deve ser morto.

[[v5-18-21]]

^<<v5-18-21,21>>^ Se vocês pensarem: "Como conheceremos a palavra que o Senhor  não falou?",

[[v5-18-22]]

^<<v5-18-22,22>>^ saibam que, quando esse profeta falar em nome do Senhor , e a palavra dele não se cumprir, nem acontecer o que ele profetizou, esta é uma palavra que o Senhor  não falou. Tal profeta falou isso com presunção; não tenham medo dele.

'''

xref:005-deuteronomio/005-deuteronomio-017.adoc#v5-17-0[&#60; Capítulo Anterior] | <<v5-18-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-019.adoc#v5-19-0[Próximo Capítulo &#62;]