include::./index.adoc[]

[[v34-3-0]]
=== Naum, 3
// naa ?, NAA - Nova Almeida Atualizada

[[v34-3-1]]

^<<v34-3-1,1>>^ Ai da cidade sanguinária, toda cheia de mentiras e de roubo e que não solta a sua presa!

[[v34-3-2]]

^<<v34-3-2,2>>^ Eis o estalo dos açoites, o estrondo das rodas, o galope dos cavalos e os carros que vão saltando!

[[v34-3-3]]

^<<v34-3-3,3>>^ Os cavaleiros que esporeiam, as espadas brilhantes, as lanças reluzentes, uma multidão de feridos, massa de cadáveres, mortos sem fim — chegam a tropeçar sobre os mortos.

[[v34-3-4]]

^<<v34-3-4,4>>^ Tudo isso por causa da grande prostituição da bela e encantadora prostituta, da mestra de feitiçarias, que seduzia as nações com a sua prostituição e os povos, com as suas feitiçarias.

[[v34-3-5]]

^<<v34-3-5,5>>^ "Eis que eu estou contra você", diz o Senhor  dos Exércitos. "Levantarei as abas de sua saia sobre o seu rosto, e mostrarei às nações a sua nudez, e aos reinos, as suas vergonhas.

[[v34-3-6]]

^<<v34-3-6,6>>^ Vou jogar sujeira sobre você, tratá-la com desprezo e transformá-la em espetáculo.

[[v34-3-7]]

^<<v34-3-7,7>>^ Todos os que a virem fugirão de você e dirão: ‘Nínive está destruída!’ Quem terá compaixão dela? De onde buscarei quem a console?"

[[v34-3-8]]

^<<v34-3-8,8>>^ Será que você é melhor do que Tebas, que estava situada junto ao Nilo, cercada de águas, protegida pelo mar e tendo as águas por muralha?

[[v34-3-9]]

^<<v34-3-9,9>>^ A Etiópia e o Egito eram a sua força, força sem limites; Pute e Líbia eram seus aliados.

[[v34-3-10]]

^<<v34-3-10,10>>^ Todavia, ela foi levada ao exílio, foi para o cativeiro. Também os seus filhos foram despedaçados nas esquinas de todas as ruas. Sobre os seus nobres lançaram sortes, e todos os seus grandes foram presos com correntes.

[[v34-3-11]]

^<<v34-3-11,11>>^ Também você, Nínive, será embriagada e se esconderá. Também você procurará um refúgio contra o inimigo.

[[v34-3-12]]

^<<v34-3-12,12>>^ Todas as suas fortalezas são como figueiras com figos prematuros: é só sacudir a figueira, que os figos caem na boca de quem os há de comer.

[[v34-3-13]]

^<<v34-3-13,13>>^ Eis que os seus soldados são como mulheres. Os portões do seu país estão completamente abertos para os seus inimigos; o fogo destruiu as trancas.

[[v34-3-14]]

^<<v34-3-14,14>>^ Tire água para o tempo do cerco, reforce as suas fortalezas, entre no lodo e pise o barro, pegue as formas para fazer tijolos.

[[v34-3-15]]

^<<v34-3-15,15>>^ No entanto, você será consumida pelo fogo e exterminada pela espada como folhas devoradas pelos gafanhotos. Multipliquem-se como os gafanhotos! Tornem-se tão numerosos como eles!

[[v34-3-16]]

^<<v34-3-16,16>>^ Os seus negociantes eram mais numerosos do que as estrelas do céu, mas como gafanhotos bateram asas e voaram.

[[v34-3-17]]

^<<v34-3-17,17>>^ Os seus príncipes eram como gafanhotos, e os seus chefes, como gafanhotos grandes, que pousam nos muros em dias de frio; quando o sol aparece, voam embora, e não se sabe para onde vão.

[[v34-3-18]]

^<<v34-3-18,18>>^ Os seus pastores dormem, ó rei da Assíria; os seus nobres cochilam. O seu povo está espalhado pelos montes, e não há quem possa ajuntá-lo.

[[v34-3-19]]

^<<v34-3-19,19>>^ Não há remédio para o seu mal; o seu ferimento é grave. Todos os que ouvirem falar do que aconteceu com você baterão palmas. Pois quem não foi vítima da sua crueldade sem fim?

'''

xref:034-naum/034-naum-002.adoc#v34-2-0[&#60; Capítulo Anterior] | <<v34-3-0,Topo>> | xref:035-habacuque/035-habacuque-001.adoc#v35-1-0[Próximo Capítulo &#62;]