include::./index.adoc[]

[[v48-4-0]]
=== Gálatas, 4
// naa ?, NAA - Nova Almeida Atualizada

[[v48-4-1]]

^<<v48-4-1,1>>^ Digo, porém, o seguinte: durante o tempo em que o herdeiro é menor de idade, em nada difere de um escravo, mesmo sendo senhor de tudo.

[[v48-4-2]]

^<<v48-4-2,2>>^ Mas está sob tutores e curadores até o tempo predeterminado pelo pai.

[[v48-4-3]]

^<<v48-4-3,3>>^ Assim, também nós, quando éramos menores, estávamos escravizados aos rudimentos do mundo.

[[v48-4-4]]

^<<v48-4-4,4>>^ Mas, quando chegou a plenitude do tempo, Deus enviou o seu Filho, nascido de mulher, nascido sob a lei,

[[v48-4-5]]

^<<v48-4-5,5>>^ para resgatar os que estavam sob a lei, a fim de que recebêssemos a adoção de filhos.

[[v48-4-6]]

^<<v48-4-6,6>>^ E, porque vocês são filhos, Deus enviou o Espírito de seu Filho ao nosso coração, e esse Espírito clama: "Aba, Pai!"

[[v48-4-7]]

^<<v48-4-7,7>>^ Assim, você já não é mais escravo, porém filho; e, sendo filho, também é herdeiro por Deus.

[[v48-4-8]]

^<<v48-4-8,8>>^ Mas, no passado, quando não conheciam a Deus, vocês eram escravos de deuses que, por natureza, não são deuses.

[[v48-4-9]]

^<<v48-4-9,9>>^ Mas agora que vocês conhecem a Deus, ou melhor, agora que vocês são conhecidos por Deus, como é que estão voltando outra vez aos rudimentos fracos e pobres, aos quais de novo querem servir como escravos?

[[v48-4-10]]

^<<v48-4-10,10>>^ Vocês guardam dias, meses, tempos e anos.

[[v48-4-11]]

^<<v48-4-11,11>>^ Receio que o meu trabalho por vocês tenha sido em vão.

[[v48-4-12]]

^<<v48-4-12,12>>^ Sejam como eu sou, porque também eu sou como vocês. Isto é o que lhes peço, irmãos. Vocês não me ofenderam em nada.

[[v48-4-13]]

^<<v48-4-13,13>>^ E vocês sabem que eu lhes preguei o evangelho a primeira vez por causa de uma enfermidade física.

[[v48-4-14]]

^<<v48-4-14,14>>^ E, por mais que a minha enfermidade na carne lhes tenha sido uma provação, vocês não me trataram com desprezo nem desgosto. Pelo contrário, me receberam como anjo de Deus, como o próprio Cristo Jesus.

[[v48-4-15]]

^<<v48-4-15,15>>^ O que aconteceu com a felicidade que vocês tinham? Porque posso dar testemunho de que, se fosse possível, vocês teriam arrancado os próprios olhos para me dar!

[[v48-4-16]]

^<<v48-4-16,16>>^ Será que, por dizer a verdade, me tornei inimigo de vocês?

[[v48-4-17]]

^<<v48-4-17,17>>^ Esses que se mostram tão zelosos em relação a vocês não estão sendo sinceros. O que eles querem é afastar vocês de mim, para que vocês se interessem por eles.

[[v48-4-18]]

^<<v48-4-18,18>>^ É bom ser sempre zeloso pelo bem e não apenas quando estou com vocês,

[[v48-4-19]]

^<<v48-4-19,19>>^ meus filhos, por quem, de novo, estou sofrendo as dores de parto, até que Cristo seja formado em vocês.

[[v48-4-20]]

^<<v48-4-20,20>>^ Bem que eu gostaria de estar agora aí com vocês e falar em outro tom de voz, porque estou perplexo com vocês.

[[v48-4-21]]

^<<v48-4-21,21>>^ Digam-me vocês, os que querem estar sob a lei: será que vocês não ouvem o que a lei diz?

[[v48-4-22]]

^<<v48-4-22,22>>^ Pois está escrito que Abraão teve dois filhos: um da mulher escrava e outro da mulher livre.

[[v48-4-23]]

^<<v48-4-23,23>>^ O filho da escrava nasceu segundo a carne; o filho da mulher livre nasceu mediante a promessa.

[[v48-4-24]]

^<<v48-4-24,24>>^ Estas coisas são alegóricas, porque essas mulheres são duas alianças. Uma se refere ao monte Sinai, que gera para a escravidão; esta é Agar.

[[v48-4-25]]

^<<v48-4-25,25>>^ Ora, Agar é o monte Sinai, na Arábia, e corresponde à Jerusalém atual, que está em escravidão com os seus filhos.

[[v48-4-26]]

^<<v48-4-26,26>>^ Mas a Jerusalém lá de cima é livre e ela é a nossa mãe.

[[v48-4-27]]

^<<v48-4-27,27>>^ Porque está escrito: "Alegre-se, ó estéril, você que não dá à luz; exulte e grite, você que não sente dores de parto; porque os filhos da mulher abandonada são mais numerosos do que os filhos da que tem marido."

[[v48-4-28]]

^<<v48-4-28,28>>^ Mas vocês, irmãos, são filhos da promessa, como Isaque.

[[v48-4-29]]

^<<v48-4-29,29>>^ Como, porém, no passado, aquele que nasceu segundo a carne perseguia o que nasceu segundo o Espírito, assim também acontece agora.

[[v48-4-30]]

^<<v48-4-30,30>>^ Mas o que diz a Escritura? Ela diz: "Mande embora a escrava e seu filho, porque de modo nenhum o filho da escrava será herdeiro com o filho da mulher livre."

[[v48-4-31]]

^<<v48-4-31,31>>^ Portanto, irmãos, somos filhos não da escrava, mas da livre.

'''

xref:048-galatas/048-galatas-003.adoc#v48-3-0[&#60; Capítulo Anterior] | <<v48-4-0,Topo>> | xref:048-galatas/048-galatas-005.adoc#v48-5-0[Próximo Capítulo &#62;]