include::./index.adoc[]

[[v48-5-0]]
=== Gálatas, 5
// naa ?, NAA - Nova Almeida Atualizada

[[v48-5-1]]

^<<v48-5-1,1>>^ Para a liberdade foi que Cristo nos libertou. Por isso, permaneçam firmes e não se submetam, de novo, a jugo de escravidão.

[[v48-5-2]]

^<<v48-5-2,2>>^ Eu, Paulo, lhes digo que, se vocês se deixarem circuncidar, Cristo não terá valor nenhum para vocês.

[[v48-5-3]]

^<<v48-5-3,3>>^ De novo, testifico a todo homem que se deixa circuncidar que o mesmo está obrigado a guardar toda a lei.

[[v48-5-4]]

^<<v48-5-4,4>>^ Vocês que procuram justificar-se pela lei estão separados de Cristo; vocês caíram da graça de Deus.

[[v48-5-5]]

^<<v48-5-5,5>>^ Porque nós, pelo Espírito, aguardamos a esperança da justiça que provém da fé.

[[v48-5-6]]

^<<v48-5-6,6>>^ Porque, em Cristo Jesus, nem a circuncisão, nem a incircuncisão têm valor algum, mas a fé que atua pelo amor.

[[v48-5-7]]

^<<v48-5-7,7>>^ Vocês vinham correndo bem! Quem foi que os impediu de continuar a obedecer à verdade?

[[v48-5-8]]

^<<v48-5-8,8>>^ Esta persuasão não vem daquele que os chamou.

[[v48-5-9]]

^<<v48-5-9,9>>^ Um pouco de fermento leveda toda a massa.

[[v48-5-10]]

^<<v48-5-10,10>>^ Tenho confiança no Senhor de que vocês não mudarão a sua forma de pensar. Mas aquele que está perturbando vocês, seja ele quem for, sofrerá a condenação.

[[v48-5-11]]

^<<v48-5-11,11>>^ Mas, irmãos, se ainda prego a circuncisão, por que continuo sendo perseguido? Nesse caso, estaria desfeito o escândalo da cruz.

[[v48-5-12]]

^<<v48-5-12,12>>^ Quem dera até se mutilassem aqueles que estão perturbando vocês.

[[v48-5-13]]

^<<v48-5-13,13>>^ Porque vocês, irmãos, foram chamados à liberdade. Mas não usem a liberdade para dar ocasião à carne; pelo contrário, sejam servos uns dos outros, pelo amor.

[[v48-5-14]]

^<<v48-5-14,14>>^ Porque toda a lei se cumpre em um só preceito, a saber: "Ame o seu próximo como a você mesmo."

[[v48-5-15]]

^<<v48-5-15,15>>^ Mas, se vocês ficam mordendo e devorando uns aos outros, tenham cuidado para que não sejam mutuamente destruídos.

[[v48-5-16]]

^<<v48-5-16,16>>^ Digo, porém, o seguinte: vivam no Espírito e vocês jamais satisfarão os desejos da carne.

[[v48-5-17]]

^<<v48-5-17,17>>^ Porque a carne luta contra o Espírito, e o Espírito luta contra a carne, porque são opostos entre si, para que vocês não façam o que querem.

[[v48-5-18]]

^<<v48-5-18,18>>^ Mas, se são guiados pelo Espírito, vocês não estão debaixo da lei.

[[v48-5-19]]

^<<v48-5-19,19>>^ Ora, as obras da carne são conhecidas e são: imoralidade sexual, impureza, libertinagem,

[[v48-5-20]]

^<<v48-5-20,20>>^ idolatria, feitiçarias, inimizades, rixas, ciúmes, iras, discórdias, divisões, facções,

[[v48-5-21]]

^<<v48-5-21,21>>^ invejas, bebedeiras, orgias e coisas semelhantes a estas. Declaro a vocês, como antes já os preveni, que os que praticam tais coisas não herdarão o Reino de Deus.

[[v48-5-22]]

^<<v48-5-22,22>>^ Mas o fruto do Espírito é: amor, alegria, paz, longanimidade, benignidade, bondade, fidelidade,

[[v48-5-23]]

^<<v48-5-23,23>>^ mansidão, domínio próprio. Contra estas coisas não há lei.

[[v48-5-24]]

^<<v48-5-24,24>>^ E os que são de Cristo Jesus crucificaram a carne, com as suas paixões e os seus desejos.

[[v48-5-25]]

^<<v48-5-25,25>>^ Se vivemos no Espírito, andemos também no Espírito.

[[v48-5-26]]

^<<v48-5-26,26>>^ Não nos deixemos possuir de vanglória, provocando uns aos outros, tendo inveja uns dos outros.

'''

xref:048-galatas/048-galatas-004.adoc#v48-4-0[&#60; Capítulo Anterior] | <<v48-5-0,Topo>> | xref:048-galatas/048-galatas-006.adoc#v48-6-0[Próximo Capítulo &#62;]