include::./index.adoc[]

[[v48-1-0]]
=== Gálatas, 1
// naa ?, NAA - Nova Almeida Atualizada

[[v48-1-1]]

^<<v48-1-1,1>>^ Paulo, apóstolo — não da parte de pessoas, nem por meio de homem algum, mas por Jesus Cristo e por Deus Pai, que o ressuscitou dos mortos —,

[[v48-1-2]]

^<<v48-1-2,2>>^ e todos os irmãos que estão comigo, às igrejas da Galácia.

[[v48-1-3]]

^<<v48-1-3,3>>^ Que a graça e a paz estejam com vocês, da parte de Deus, nosso Pai, e do Senhor Jesus Cristo,

[[v48-1-4]]

^<<v48-1-4,4>>^ o qual entregou a si mesmo pelos nossos pecados, para nos livrar deste mundo perverso, segundo a vontade de nosso Deus e Pai,

[[v48-1-5]]

^<<v48-1-5,5>>^ a quem seja a glória para todo o sempre. Amém!

[[v48-1-6]]

^<<v48-1-6,6>>^ Estou muito surpreso em ver que vocês estão passando tão depressa daquele que os chamou na graça de Cristo para outro evangelho,

[[v48-1-7]]

^<<v48-1-7,7>>^ o qual, na verdade, não é outro. Porém, há alguns que estão perturbando vocês e querem perverter o evangelho de Cristo.

[[v48-1-8]]

^<<v48-1-8,8>>^ Mas, ainda que nós ou mesmo um anjo vindo do céu pregue a vocês um evangelho diferente daquele que temos pregado, que esse seja anátema.

[[v48-1-9]]

^<<v48-1-9,9>>^ Como já dissemos, e agora repito, se alguém está pregando a vocês um evangelho diferente daquele que já receberam, que esse seja anátema.

[[v48-1-10]]

^<<v48-1-10,10>>^ Por acaso eu procuro, agora, o favor das pessoas ou o favor de Deus? Ou procuro agradar pessoas? Se ainda estivesse procurando agradar pessoas, eu não seria servo de Cristo.

[[v48-1-11]]

^<<v48-1-11,11>>^ Mas informo a vocês, irmãos, que o evangelho por mim anunciado não é mensagem humana,

[[v48-1-12]]

^<<v48-1-12,12>>^ porque eu não o recebi de ser humano algum, nem me foi ensinado, mas eu o recebi mediante revelação de Jesus Cristo.

[[v48-1-13]]

^<<v48-1-13,13>>^ Porque vocês ouviram qual foi, no passado, o meu modo de agir no judaísmo, como, de forma violenta, eu perseguia a igreja de Deus e procurava destruí-la.

[[v48-1-14]]

^<<v48-1-14,14>>^ E, na minha nação, quanto ao judaísmo, levava vantagem sobre muitos da minha idade, sendo extremamente zeloso das tradições dos meus pais.

[[v48-1-15]]

^<<v48-1-15,15>>^ Mas, quando Deus, que me separou antes de eu nascer e me chamou pela sua graça, achou por bem

[[v48-1-16]]

^<<v48-1-16,16>>^ revelar seu Filho em mim, para que eu o pregasse entre os gentios, não fui imediatamente consultar outras pessoas,

[[v48-1-17]]

^<<v48-1-17,17>>^ nem fui a Jerusalém para me encontrar com os que já eram apóstolos antes de mim, mas fui para as regiões da Arábia e voltei, outra vez, para Damasco.

[[v48-1-18]]

^<<v48-1-18,18>>^ Passados três anos, fui a Jerusalém para me encontrar com Cefas e fiquei quinze dias com ele.

[[v48-1-19]]

^<<v48-1-19,19>>^ E não vi outro dos apóstolos, a não ser Tiago, o irmão do Senhor.

[[v48-1-20]]

^<<v48-1-20,20>>^ Ora, a respeito do que estou escrevendo a vocês, afirmo diante de Deus que não estou mentindo.

[[v48-1-21]]

^<<v48-1-21,21>>^ Depois, fui para as regiões da Síria e da Cilícia.

[[v48-1-22]]

^<<v48-1-22,22>>^ E eu não era conhecido pessoalmente pelas igrejas da Judeia, que estão em Cristo.

[[v48-1-23]]

^<<v48-1-23,23>>^ Ouviam somente dizer: "Aquele que antes nos perseguia, agora prega a fé que no passado procurava destruir."

[[v48-1-24]]

^<<v48-1-24,24>>^ E glorificavam a Deus a meu respeito.

'''

xref:047-2-corintios/047-2-corintios-013.adoc#v47-13-0[&#60; Capítulo Anterior] | <<v48-1-0,Topo>> | xref:048-galatas/048-galatas-002.adoc#v48-2-0[Próximo Capítulo &#62;]