include::./index.adoc[]

[[v48-6-0]]
=== Gálatas, 6
// naa ?, NAA - Nova Almeida Atualizada

[[v48-6-1]]

^<<v48-6-1,1>>^ Irmãos, se alguém for surpreendido em alguma falta, vocês, que são espirituais, restaurem essa pessoa com espírito de brandura. E que cada um tenha cuidado para que não seja também tentado.

[[v48-6-2]]

^<<v48-6-2,2>>^ Levem as cargas uns dos outros e, assim, estarão cumprindo a lei de Cristo.

[[v48-6-3]]

^<<v48-6-3,3>>^ Porque, se alguém julga ser alguma coisa, não sendo nada, engana a si mesmo.

[[v48-6-4]]

^<<v48-6-4,4>>^ Mas que cada um examine o seu próprio modo de agir e, então, terá motivo de gloriar-se unicamente em si e não em outro.

[[v48-6-5]]

^<<v48-6-5,5>>^ Porque cada um levará o seu próprio fardo.

[[v48-6-6]]

^<<v48-6-6,6>>^ Mas aquele que está sendo instruído na palavra compartilhe todas as coisas boas com aquele que o instrui.

[[v48-6-7]]

^<<v48-6-7,7>>^ Não se enganem: de Deus não se zomba. Pois aquilo que a pessoa semear, isso também colherá.

[[v48-6-8]]

^<<v48-6-8,8>>^ Quem semeia para a sua própria carne, da carne colherá corrupção; mas quem semeia para o Espírito, do Espírito colherá vida eterna.

[[v48-6-9]]

^<<v48-6-9,9>>^ E não nos cansemos de fazer o bem, porque no tempo certo faremos a colheita, se não desanimarmos.

[[v48-6-10]]

^<<v48-6-10,10>>^ Por isso, enquanto tivermos oportunidade, façamos o bem a todos, mas principalmente aos da família da fé.

[[v48-6-11]]

^<<v48-6-11,11>>^ Vejam com que letras grandes escrevi a vocês de próprio punho.

[[v48-6-12]]

^<<v48-6-12,12>>^ Todos os que querem ostentar-se na carne, esses querem obrigar vocês a se deixarem circuncidar, e agem assim somente para não serem perseguidos por causa da cruz de Cristo.

[[v48-6-13]]

^<<v48-6-13,13>>^ Pois nem mesmo os que se deixam circuncidar guardam a lei, mas querem apenas que vocês se submetam à circuncisão para que eles possam se gloriar na carne de vocês.

[[v48-6-14]]

^<<v48-6-14,14>>^ Mas longe de mim gloriar-me, senão na cruz de nosso Senhor Jesus Cristo, pela qual o mundo está crucificado para mim, e eu estou crucificado para o mundo.

[[v48-6-15]]

^<<v48-6-15,15>>^ Pois nem a circuncisão é coisa alguma, nem a incircuncisão, mas o ser nova criatura.

[[v48-6-16]]

^<<v48-6-16,16>>^ E, a todos os que andarem em conformidade com esta regra, paz e misericórdia sejam sobre eles e sobre o Israel de Deus.

[[v48-6-17]]

^<<v48-6-17,17>>^ Quanto ao mais, ninguém me moleste; porque eu trago no corpo as marcas de Jesus.

[[v48-6-18]]

^<<v48-6-18,18>>^ A graça de nosso Senhor Jesus Cristo esteja com o espírito de vocês, irmãos. Amém!

'''

xref:048-galatas/048-galatas-005.adoc#v48-5-0[&#60; Capítulo Anterior] | <<v48-6-0,Topo>> | xref:049-efesios/049-efesios-001.adoc#v49-1-0[Próximo Capítulo &#62;]