include::./index.adoc[]

[[v21-10-0]]
=== Eclesiastes, 10
// naa ?, NAA - Nova Almeida Atualizada

[[v21-10-1]]

^<<v21-10-1,1>>^ Assim como a mosca morta faz o óleo do perfumador exalar mau cheiro, assim também uma pequena tolice pode ter mais peso do que a sabedoria e a honra.

[[v21-10-2]]

^<<v21-10-2,2>>^ O coração do sábio se inclina para o bem, mas o coração do tolo se inclina para o mal.

[[v21-10-3]]

^<<v21-10-3,3>>^ Quando o tolo vai pelo caminho, falta-lhe o entendimento; e, assim, mostra a todos que é mesmo um tolo.

[[v21-10-4]]

^<<v21-10-4,4>>^ Se aquele que governa ficar indignado contra você, não deixe o seu lugar, porque o ânimo sereno acalma grandes ofensas.

[[v21-10-5]]

^<<v21-10-5,5>>^ Ainda há um mal que vi debaixo do sol, um erro cometido pelos que governam:

[[v21-10-6]]

^<<v21-10-6,6>>^ os tolos colocados em muitos postos elevados, enquanto os ricos ocupam os postos inferiores.

[[v21-10-7]]

^<<v21-10-7,7>>^ Vi servos andando a cavalo e príncipes andando a pé como se fossem servos.

[[v21-10-8]]

^<<v21-10-8,8>>^ Quem abre uma cova acaba caindo nela, e quem arromba um muro será mordido por uma cobra.

[[v21-10-9]]

^<<v21-10-9,9>>^ Quem arranca pedras será ferido por elas, e o que racha lenha se expõe ao perigo.

[[v21-10-10]]

^<<v21-10-10,10>>^ Se o machado está embotado e ninguém o afia, é preciso redobrar a força; mas com sabedoria se obtém êxito.

[[v21-10-11]]

^<<v21-10-11,11>>^ Se a cobra morder antes de estar encantada, de nada adianta o trabalho do encantador.

[[v21-10-12]]

^<<v21-10-12,12>>^ As palavras do sábio lhe trazem favor, mas o tolo é destruído pelo que diz;

[[v21-10-13]]

^<<v21-10-13,13>>^ as primeiras palavras de sua boca são tolice, e as últimas, loucura perversa.

[[v21-10-14]]

^<<v21-10-14,14>>^ O tolo multiplica as palavras, mas o ser humano não sabe o que vai acontecer. Quem poderá lhe dizer o que será depois dele?

[[v21-10-15]]

^<<v21-10-15,15>>^ O trabalho do tolo o fatiga, pois nem sabe ir à cidade.

[[v21-10-16]]

^<<v21-10-16,16>>^ Ai de você, ó terra cujo rei é criança e cujos príncipes se banqueteiam já de manhã.

[[v21-10-17]]

^<<v21-10-17,17>>^ Feliz é você, ó terra cujo rei é filho de nobres e cujos príncipes se sentam à mesa a seu tempo para refazer as forças e não para se embriagar.

[[v21-10-18]]

^<<v21-10-18,18>>^ Por causa da preguiça o teto desaba, e por causa dos braços cruzados a casa tem goteiras.

[[v21-10-19]]

^<<v21-10-19,19>>^ As festas são feitas para rir, o vinho alegra a vida, e o dinheiro dá conta de tudo.

[[v21-10-20]]

^<<v21-10-20,20>>^ Nem em pensamento fale mal do rei, e não fale mal do rico nem mesmo quando você estiver sozinho em seu quarto, porque as aves do céu poderiam levar a sua voz, e o que tem asas poderia contar o que você falou.

'''

xref:021-eclesiastes/021-eclesiastes-009.adoc#v21-9-0[&#60; Capítulo Anterior] | <<v21-10-0,Topo>> | xref:021-eclesiastes/021-eclesiastes-011.adoc#v21-11-0[Próximo Capítulo &#62;]