include::./index.adoc[]

[[v21-12-0]]
=== Eclesiastes, 12
// naa ?, NAA - Nova Almeida Atualizada

[[v21-12-1]]

^<<v21-12-1,1>>^ Lembre-se do seu Criador nos dias da sua mocidade, antes que venham os dias maus, e cheguem os anos em que você dirá: "Não tenho neles prazer."

[[v21-12-2]]

^<<v21-12-2,2>>^ Lembre-se do Criador antes que se escureçam o sol, a lua e as estrelas, e as nuvens voltem depois da chuva.

[[v21-12-3]]

^<<v21-12-3,3>>^ Lembre-se dele antes do dia em que tremerem os guardas da casa, os seus braços, e se curvarem os homens que no passado eram fortes, as suas pernas, e cessarem os moedores da sua boca, por já serem poucos, e se escurecerem os que olham pelas janelas, os seus olhos.

[[v21-12-4]]

^<<v21-12-4,4>>^ Faça isso antes que as portas da rua se fechem e o ruído das pedras do moinho se torne difícil de ouvir; quando você se levantar à voz das aves, e todas as harmonias, filhas da música, começarem a desaparecer;

[[v21-12-5]]

^<<v21-12-5,5>>^ quando você tiver medo do que é alto e se espantar no caminho; quando florescer como a amendoeira, e o gafanhoto lhe for um peso; e quando você perder o apetite. Porque o ser humano vai à morada eterna, e os pranteadores andarão rodeando pela praça.

[[v21-12-6]]

^<<v21-12-6,6>>^ Lembre-se do seu Criador, antes que se rompa o fio de prata, e se despedace o copo de ouro, e se quebre o cântaro junto à fonte, e se desfaça a roda junto ao poço,

[[v21-12-7]]

^<<v21-12-7,7>>^ e o pó volte à terra, de onde veio, e o espírito volte a Deus, que o deu.

[[v21-12-8]]

^<<v21-12-8,8>>^ Vaidade de vaidade, diz o Pregador, tudo é vaidade.

[[v21-12-9]]

^<<v21-12-9,9>>^ O Pregador, além de sábio, ainda ensinou ao povo o conhecimento; e, atentando e examinando, compôs muitos provérbios.

[[v21-12-10]]

^<<v21-12-10,10>>^ O Pregador procurou achar palavras agradáveis e escrever com retidão palavras de verdade.

[[v21-12-11]]

^<<v21-12-11,11>>^ As palavras dos sábios são como aguilhões, e as coleções de sentenças são como pregos bem-fixados; elas provêm de um único Pastor.

[[v21-12-12]]

^<<v21-12-12,12>>^ Além do mais, meu filho, leve em conta o seguinte: não há limite para fazer livros, e o muito estudar é enfado da carne.

[[v21-12-13]]

^<<v21-12-13,13>>^ De tudo o que se ouviu, a conclusão é esta: tema a Deus e guarde os seus mandamentos, porque isto é o dever de cada pessoa.

[[v21-12-14]]

^<<v21-12-14,14>>^ Porque Deus há de trazer a juízo todas as obras, até as que estão escondidas, quer sejam boas, quer sejam más.

'''

xref:021-eclesiastes/021-eclesiastes-011.adoc#v21-11-0[&#60; Capítulo Anterior] | <<v21-12-0,Topo>> | xref:022-canticos/022-canticos-001.adoc#v22-1-0[Próximo Capítulo &#62;]