include::./index.adoc[]

[[v21-1-0]]
=== Eclesiastes, 1
// naa ?, NAA - Nova Almeida Atualizada

[[v21-1-1]]

^<<v21-1-1,1>>^ Palavras do Pregador, filho de Davi, rei de Jerusalém.

[[v21-1-2]]

^<<v21-1-2,2>>^ Vaidade de vaidades, diz o Pregador. Vaidade de vaidades! Tudo é vaidade.

[[v21-1-3]]

^<<v21-1-3,3>>^ Que proveito alguém tem de todo o seu trabalho, com que se afadiga debaixo do sol?

[[v21-1-4]]

^<<v21-1-4,4>>^ Geração vai e geração vem, mas a terra permanece para sempre.

[[v21-1-5]]

^<<v21-1-5,5>>^ O sol se levanta, e o sol se põe, e volta ao seu lugar, onde nasce de novo.

[[v21-1-6]]

^<<v21-1-6,6>>^ O vento vai para o sul e faz o seu giro para o norte; dá voltas e mais voltas e retorna aos seus circuitos.

[[v21-1-7]]

^<<v21-1-7,7>>^ Todos os rios correm para o mar, e o mar não se enche; ao lugar para onde correm os rios, para lá eles voltam a correr.

[[v21-1-8]]

^<<v21-1-8,8>>^ Todas as coisas são canseiras tais, que ninguém as pode exprimir; os olhos não se fartam de ver, nem os ouvidos se enchem de ouvir.

[[v21-1-9]]

^<<v21-1-9,9>>^ O que foi é o que há de ser; e o que se fez, isso se tornará a fazer; não há nada de novo debaixo do sol.

[[v21-1-10]]

^<<v21-1-10,10>>^ Será que existe alguma coisa de que se possa dizer: "Veja! Isto é novo!"? Não! Já existiu em tempos passados, muito antes de nós.

[[v21-1-11]]

^<<v21-1-11,11>>^ Já não há lembrança das coisas que se foram; e das coisas que ainda virão também não haverá memória entre os que hão de vir depois delas.

[[v21-1-12]]

^<<v21-1-12,12>>^ Eu, o Pregador, venho sendo rei de Israel, em Jerusalém.

[[v21-1-13]]

^<<v21-1-13,13>>^ Dediquei-me a investigar e a me informar com sabedoria a respeito de tudo o que se faz debaixo do céu. Que enfadonho trabalho Deus impôs aos filhos dos homens, para com ele os afligir!

[[v21-1-14]]

^<<v21-1-14,14>>^ Vi todas as obras que se fazem debaixo do sol, e eis que tudo é vaidade e correr atrás do vento.

[[v21-1-15]]

^<<v21-1-15,15>>^ Aquilo que é torto não pode ser endireitado; e o que falta não pode ser contado.

[[v21-1-16]]

^<<v21-1-16,16>>^ Eu disse a mim mesmo: "Eu me tornei importante e superei em sabedoria todos os que governaram em Jerusalém antes de mim. O meu coração tem tido larga experiência da sabedoria e do conhecimento."

[[v21-1-17]]

^<<v21-1-17,17>>^ Assim, procurei conhecer a sabedoria e saber o que é a tolice e a falta de juízo; mas descobri que também isto é correr atrás do vento.

[[v21-1-18]]

^<<v21-1-18,18>>^ Porque na muita sabedoria há muito enfado; e quem aumenta o seu conhecimento aumenta também a sua dor.

'''

xref:020-proverbios/020-proverbios-031.adoc#v20-31-0[&#60; Capítulo Anterior] | <<v21-1-0,Topo>> | xref:021-eclesiastes/021-eclesiastes-002.adoc#v21-2-0[Próximo Capítulo &#62;]