include::./index.adoc[]

[[v21-5-0]]
=== Eclesiastes, 5
// naa ?, NAA - Nova Almeida Atualizada

[[v21-5-1]]

^<<v21-5-1,1>>^ Guarde o pé, quando você entrar na Casa de Deus. Chegar-se para ouvir é melhor do que oferecer um sacrifício de tolos, que fazem o mal sem se dar conta.

[[v21-5-2]]

^<<v21-5-2,2>>^ Que a sua boca não se precipite, nem se apresse o seu coração em pronunciar uma palavra diante de Deus. Porque Deus está nos céus, e você, aqui na terra. Portanto, sejam poucas as suas palavras.

[[v21-5-3]]

^<<v21-5-3,3>>^ Porque das muitas preocupações vêm os sonhos, e do muito falar, palavras tolas.

[[v21-5-4]]

^<<v21-5-4,4>>^ Quando você fizer algum voto a Deus, não demore a cumpri-lo, pois ele não se agrada de tolos. Cumpra o voto que você faz.

[[v21-5-5]]

^<<v21-5-5,5>>^ Melhor é não fazer voto do que fazer e não cumprir.

[[v21-5-6]]

^<<v21-5-6,6>>^ Não consinta que a sua boca o leve a pecar, nem diga ao mensageiro de Deus que foi descuido. Por que fazer com que Deus fique irado por causa do que você diz e deixar que ele destrua o que você fez?

[[v21-5-7]]

^<<v21-5-7,7>>^ Porque, como na multidão dos sonhos há vaidade, assim também nas muitas palavras. Portanto, tema a Deus.

[[v21-5-8]]

^<<v21-5-8,8>>^ Se você notar em alguma província opressão de pobres e roubo em lugar do direito e da justiça, não fique admirado com isso; porque o que está num posto elevado tem acima de si outro mais elevado que o explora, e sobre estes há ainda outros mais elevados que também exploram.

[[v21-5-9]]

^<<v21-5-9,9>>^ O proveito da terra é para todos; até o rei se serve do campo.

[[v21-5-10]]

^<<v21-5-10,10>>^ Quem ama o dinheiro jamais se fartará de dinheiro; e quem ama a abundância nunca ficará satisfeito com o que ganha. Também isto é vaidade.

[[v21-5-11]]

^<<v21-5-11,11>>^ Onde os bens se multiplicam, também se multiplicam os que deles comem. E que proveito têm os donos, a não ser o de ver esses bens com os seus olhos?

[[v21-5-12]]

^<<v21-5-12,12>>^ Doce é o sono do trabalhador, quer coma pouco, quer muito; mas a fartura do rico não o deixa dormir.

[[v21-5-13]]

^<<v21-5-13,13>>^ Há um grave mal que vi debaixo do sol: as riquezas que os seus donos guardam para o seu próprio prejuízo.

[[v21-5-14]]

^<<v21-5-14,14>>^ E, se essas riquezas se perdem num mau negócio, o filho que esse homem gerou ficará de mãos vazias.

[[v21-5-15]]

^<<v21-5-15,15>>^ Como saiu do ventre de sua mãe, a saber, nu, assim voltará, indo-se como veio; e do seu trabalho nada poderá levar consigo.

[[v21-5-16]]

^<<v21-5-16,16>>^ Também isto é um grave mal: precisamente como veio, assim ele vai. E que proveito terá de haver trabalhado para o vento?

[[v21-5-17]]

^<<v21-5-17,17>>^ Em todos os seus dias, comeu o seu pão nas trevas, com muito enfado, com enfermidades e indignação.

[[v21-5-18]]

^<<v21-5-18,18>>^ Eis o que eu vi: boa e bela coisa é comer e beber e desfrutar o que conseguiu de todo o seu trabalho, com que se afadigou debaixo do sol, durante os poucos dias da vida que Deus lhe deu; porque esta é a sua porção.

[[v21-5-19]]

^<<v21-5-19,19>>^ Quanto àquele a quem Deus conferiu riquezas e bens e lhe deu poder para deles comer, receber a sua porção e desfrutar do seu trabalho, isto é dom de Deus.

[[v21-5-20]]

^<<v21-5-20,20>>^ Porque não ficará pensando muito nos dias da sua vida, pois Deus lhe enche o coração de alegria.

'''

xref:021-eclesiastes/021-eclesiastes-004.adoc#v21-4-0[&#60; Capítulo Anterior] | <<v21-5-0,Topo>> | xref:021-eclesiastes/021-eclesiastes-006.adoc#v21-6-0[Próximo Capítulo &#62;]