include::./index.adoc[]

[[v21-9-0]]
=== Eclesiastes, 9
// naa ?, NAA - Nova Almeida Atualizada

[[v21-9-1]]

^<<v21-9-1,1>>^ Tenho refletido sobre todas estas coisas para chegar à seguinte conclusão: os justos e os sábios, com os seus feitos, estão nas mãos de Deus; e, se é amor ou se é ódio que está à sua espera, isso ninguém sabe. Ninguém sabe o que vai acontecer.

[[v21-9-2]]

^<<v21-9-2,2>>^ Tudo acontece igualmente com todos: o mesmo acontece com o justo e com o ímpio, com o bom e com o mau, com o puro e com o impuro, com o que oferece sacrifícios e com o que não os oferece, com o bom e com o pecador, tanto com o que faz juramentos como com aquele que tem medo de fazê-los.

[[v21-9-3]]

^<<v21-9-3,3>>^ Este é o mal que há em tudo o que se faz debaixo do sol: a mesma coisa acontece com todos. Também o coração das pessoas está cheio de maldade; está cheio de loucura enquanto elas vivem; depois, rumo aos mortos.

[[v21-9-4]]

^<<v21-9-4,4>>^ Para aquele que está entre os vivos há esperança, porque mais vale um cão vivo do que um leão morto.

[[v21-9-5]]

^<<v21-9-5,5>>^ Porque os vivos sabem que vão morrer, mas os mortos não sabem nada e não têm nenhuma recompensa a receber, porque a memória deles jaz no esquecimento.

[[v21-9-6]]

^<<v21-9-6,6>>^ Amor, ódio e inveja para eles já não existem mais; eles estão afastados para sempre de tudo o que se faz debaixo do sol.

[[v21-9-7]]

^<<v21-9-7,7>>^ Portanto, vá e coma com alegria o seu pão e beba com prazer o seu vinho, pois Deus já se agradou do que você faz.

[[v21-9-8]]

^<<v21-9-8,8>>^ Que as suas vestes sejam sempre brancas, e que nunca falte óleo sobre a sua cabeça.

[[v21-9-9]]

^<<v21-9-9,9>>^ Aproveite a vida com a mulher que você ama, todos os dias dessa vida fugaz que Deus lhe deu debaixo do sol, porque esta é a parte que lhe cabe nesta vida pelo trabalho com que você se afadigou debaixo do sol.

[[v21-9-10]]

^<<v21-9-10,10>>^ Tudo o que vier às suas mãos para fazer, faça-o conforme as suas forças, porque na sepultura, que é para onde você vai, não há obra, nem projetos, nem conhecimento, nem sabedoria alguma.

[[v21-9-11]]

^<<v21-9-11,11>>^ Vi ainda debaixo do sol que os mais rápidos nem sempre ganham a corrida, que os mais fortes nem sempre vencem a batalha, que os sábios nem sempre têm pão, que os prudentes nem sempre têm riqueza, que os inteligentes nem sempre são honrados, mas que tudo depende do tempo e do acaso.

[[v21-9-12]]

^<<v21-9-12,12>>^ Pois ninguém sabe a sua hora. Assim como os peixes que são apanhados na rede traiçoeira e como os pássaros que são pegos na armadilha, assim também os filhos dos homens se enredam no tempo da calamidade, quando esta cai de repente sobre eles.

[[v21-9-13]]

^<<v21-9-13,13>>^ Também vi este exemplo de sabedoria debaixo do sol, que me pareceu excelente.

[[v21-9-14]]

^<<v21-9-14,14>>^ Havia uma pequena cidade onde moravam poucos homens. Um rei poderoso atacou a cidade, sitiou-a e levantou contra ela grandes rampas de ataque.

[[v21-9-15]]

^<<v21-9-15,15>>^ Nessa cidade se encontrava um homem pobre e sábio, que poderia ter livrado a cidade com a sua sabedoria; no entanto, ninguém se lembrou daquele pobre.

[[v21-9-16]]

^<<v21-9-16,16>>^ Então eu concluí que a sabedoria é melhor do que a força, mesmo que a sabedoria do pobre seja desprezada, e as suas palavras não sejam ouvidas.

[[v21-9-17]]

^<<v21-9-17,17>>^ As palavras dos sábios, ouvidas em silêncio, valem mais do que os gritos de quem governa entre tolos.

[[v21-9-18]]

^<<v21-9-18,18>>^ Melhor é a sabedoria do que as armas de guerra, mas um só pecador destrói muitas coisas boas.

'''

xref:021-eclesiastes/021-eclesiastes-008.adoc#v21-8-0[&#60; Capítulo Anterior] | <<v21-9-0,Topo>> | xref:021-eclesiastes/021-eclesiastes-010.adoc#v21-10-0[Próximo Capítulo &#62;]