include::./index.adoc[]

[[v21-8-0]]
=== Eclesiastes, 8
// naa ?, NAA - Nova Almeida Atualizada

[[v21-8-1]]

^<<v21-8-1,1>>^ Quem é como o sábio? E quem sabe a interpretação das coisas? A sabedoria faz reluzir o rosto de uma pessoa e muda a dureza do seu semblante.

[[v21-8-2]]

^<<v21-8-2,2>>^ Eu digo a você: observe o mandamento do rei, e isso por causa do juramento que você fez diante de Deus.

[[v21-8-3]]

^<<v21-8-3,3>>^ Não tenha pressa em sair da presença dele, nem insista em fazer o que é mau, porque ele faz o que bem entende.

[[v21-8-4]]

^<<v21-8-4,4>>^ Porque a palavra do rei tem autoridade suprema. Quem pode lhe perguntar: "O que você está fazendo?"

[[v21-8-5]]

^<<v21-8-5,5>>^ Quem guarda o mandamento não experimenta nenhum mal; e o coração do sábio conhece o tempo e o modo certo de agir.

[[v21-8-6]]

^<<v21-8-6,6>>^ Porque há um tempo e um modo para todo propósito; porque é grande o mal que pesa sobre o ser humano.

[[v21-8-7]]

^<<v21-8-7,7>>^ Ninguém sabe o que vai acontecer. Pois quem poderá lhe dizer o que vai acontecer?

[[v21-8-8]]

^<<v21-8-8,8>>^ Não há ninguém que tenha domínio sobre o espírito para o reter; nem tampouco quem tenha poder sobre o dia da morte. Não há como escapar desse combate, e a maldade não poderá livrar os que a praticam.

[[v21-8-9]]

^<<v21-8-9,9>>^ Tudo isso vi quando comecei a pensar no que se faz debaixo do sol. Há um tempo em que uma pessoa tem domínio sobre outra pessoa, para seu próprio mal.

[[v21-8-10]]

^<<v21-8-10,10>>^ Assim também vi os ímpios serem sepultados com honra, ao passo que os que frequentavam o lugar santo foram esquecidos na cidade onde fizeram o bem. Também isto é vaidade.

[[v21-8-11]]

^<<v21-8-11,11>>^ Como não se executa logo a sentença contra uma obra má, o coração humano está inteiramente disposto a praticar o mal.

[[v21-8-12]]

^<<v21-8-12,12>>^ Ainda que o pecador faça o mal cem vezes, e a vida dele se prolongue, eu sei com certeza que tudo correrá bem para os que temem a Deus.

[[v21-8-13]]

^<<v21-8-13,13>>^ Mas nada correrá bem para o ímpio, e ele não prolongará os seus dias; será como a sombra, visto que não teme a Deus.

[[v21-8-14]]

^<<v21-8-14,14>>^ Ainda há outra vaidade sobre a terra: justos que são tratados segundo as obras dos ímpios, e ímpios que são tratados segundo as obras dos justos. Digo que também isto é vaidade.

[[v21-8-15]]

^<<v21-8-15,15>>^ Por isso exalto a alegria, porque para o ser humano não há nada melhor debaixo do sol do que comer, beber e alegrar-se; pois isso o acompanhará no seu trabalho nos dias da vida que Deus lhe dá debaixo do sol.

[[v21-8-16]]

^<<v21-8-16,16>>^ Quando me dediquei a conhecer a sabedoria e a ver o trabalho que há sobre a terra — pois nem de dia nem de noite se consegue conciliar o sono —,

[[v21-8-17]]

^<<v21-8-17,17>>^ contemplei toda a obra de Deus e vi que o ser humano não pode compreender a obra que se faz debaixo do sol; por mais que se esforce para a descobrir, não a entenderá; e, ainda que o sábio diga que conseguirá conhecê-la, nem por isso a poderá achar.

'''

xref:021-eclesiastes/021-eclesiastes-007.adoc#v21-7-0[&#60; Capítulo Anterior] | <<v21-8-0,Topo>> | xref:021-eclesiastes/021-eclesiastes-009.adoc#v21-9-0[Próximo Capítulo &#62;]