include::./index.adoc[]

[[v21-4-0]]
=== Eclesiastes, 4
// naa ?, NAA - Nova Almeida Atualizada

[[v21-4-1]]

^<<v21-4-1,1>>^ Vi ainda todas as opressões praticadas debaixo do sol: vi as lágrimas dos que foram oprimidos, sem que ninguém os consolasse; vi a violência na mão dos opressores, sem que ninguém consolasse os oprimidos.

[[v21-4-2]]

^<<v21-4-2,2>>^ Por isso considero mais felizes os que já morreram, mais do que os que ainda vivem.

[[v21-4-3]]

^<<v21-4-3,3>>^ Porém mais feliz do que uns e outros é aquele que ainda não nasceu e não viu as más obras que se fazem debaixo do sol.

[[v21-4-4]]

^<<v21-4-4,4>>^ Então vi que toda fadiga e toda habilidade no trabalho provêm da inveja do ser humano contra o seu próximo. Também isto é vaidade e correr atrás do vento.

[[v21-4-5]]

^<<v21-4-5,5>>^ O tolo cruza os braços e destrói a si mesmo.

[[v21-4-6]]

^<<v21-4-6,6>>^ Melhor é um punhado de descanso do que ambas as mãos cheias de trabalho e correr atrás do vento.

[[v21-4-7]]

^<<v21-4-7,7>>^ Então considerei outra vaidade debaixo do sol:

[[v21-4-8]]

^<<v21-4-8,8>>^ um homem sem ninguém, que não tem filhos nem irmãos, mas que não cessa de trabalhar e cujos olhos não se fartam de riquezas. E ele não pergunta: "Para quem estou trabalhando, se não aproveito as coisas boas da vida?" Também isto é vaidade e enfadonho trabalho.

[[v21-4-9]]

^<<v21-4-9,9>>^ Melhor é serem dois do que um, porque maior é o pagamento pelo seu trabalho.

[[v21-4-10]]

^<<v21-4-10,10>>^ Porque se caírem, um levanta o companheiro. Mas ai do que estiver só, pois, caindo, não haverá quem o levante.

[[v21-4-11]]

^<<v21-4-11,11>>^ Também, se dois dormirem juntos, eles se aquecerão; mas, se for um sozinho, como se aquecerá?

[[v21-4-12]]

^<<v21-4-12,12>>^ Se alguém quiser dominar um deles, os dois poderão resistir; o cordão de três dobras não se rompe com facilidade.

[[v21-4-13]]

^<<v21-4-13,13>>^ Melhor é o jovem pobre e sábio do que o rei velho e tolo, que já não se deixa admoestar.

[[v21-4-14]]

^<<v21-4-14,14>>^ Porque ele saiu da prisão para reinar, embora tenha nascido pobre em seu reino.

[[v21-4-15]]

^<<v21-4-15,15>>^ Vi todos os viventes que andam debaixo do sol com o jovem sucessor, que ficará em lugar do rei.

[[v21-4-16]]

^<<v21-4-16,16>>^ Era sem conta todo o povo que ele dominava, mas os que virão depois não estarão contentes com ele. Na verdade, também isto é vaidade e correr atrás do vento.

'''

xref:021-eclesiastes/021-eclesiastes-003.adoc#v21-3-0[&#60; Capítulo Anterior] | <<v21-4-0,Topo>> | xref:021-eclesiastes/021-eclesiastes-005.adoc#v21-5-0[Próximo Capítulo &#62;]