include::./index.adoc[]

[[v21-11-0]]
=== Eclesiastes, 11
// naa ?, NAA - Nova Almeida Atualizada

[[v21-11-1]]

^<<v21-11-1,1>>^ Lance o seu pão sobre as águas, porque depois de muitos dias você o achará.

[[v21-11-2]]

^<<v21-11-2,2>>^ Reparta com sete e até mesmo com oito, porque você não sabe que mal sobrevirá à terra.

[[v21-11-3]]

^<<v21-11-3,3>>^ Se as nuvens estão cheias, derramam chuva sobre a terra; se uma árvore cair para o sul ou para o norte, no lugar em que cair, aí ficará.

[[v21-11-4]]

^<<v21-11-4,4>>^ Quem somente observa o vento nunca semeará, e o que olha para as nuvens nunca fará a colheita.

[[v21-11-5]]

^<<v21-11-5,5>>^ Assim como você não conhece o caminho do vento, nem sabe como se formam os ossos no ventre da mulher grávida, assim também não entende as obras de Deus, que faz todas as coisas.

[[v21-11-6]]

^<<v21-11-6,6>>^ Semeie a sua semente de manhã e à tarde não fique de braços cruzados, porque você não sabe qual irá prosperar: se esta, se aquela ou se ambas serão igualmente boas.

[[v21-11-7]]

^<<v21-11-7,7>>^ Doce é a luz, e agradável aos olhos é ver o sol.

[[v21-11-8]]

^<<v21-11-8,8>>^ Mesmo que alguém viva muitos anos, deve alegrar-se em todos eles; contudo, deve lembrar-se de que há dias de trevas, que serão muitos, e que tudo o que virá é vaidade.

[[v21-11-9]]

^<<v21-11-9,9>>^ Alegre-se, jovem, na sua mocidade, e que o seu coração lhe dê muita alegria nos dias da sua juventude. Ande nos caminhos que satisfazem ao seu coração e agradam aos seus olhos; saiba, porém, que de todas estas coisas Deus lhe pedirá contas.

[[v21-11-10]]

^<<v21-11-10,10>>^ Afaste do seu coração a mágoa e remova de seu corpo a dor, porque a juventude e a primavera da vida são vaidade.

'''

xref:021-eclesiastes/021-eclesiastes-010.adoc#v21-10-0[&#60; Capítulo Anterior] | <<v21-11-0,Topo>> | xref:021-eclesiastes/021-eclesiastes-012.adoc#v21-12-0[Próximo Capítulo &#62;]