include::./index.adoc[]

[[v6-7-0]]
=== Josué, 7
// naa ?, NAA - Nova Almeida Atualizada

[[v6-7-1]]

^<<v6-7-1,1>>^ Mas os filhos de Israel foram infiéis em relação às coisas condenadas, porque Acã, filho de Carmi, filho de Zabdi, filho de Zera, da tribo de Judá, pegou para si uma parte das coisas condenadas. A ira do Senhor  se acendeu contra os filhos de Israel.

[[v6-7-2]]

^<<v6-7-2,2>>^ Josué enviou alguns homens de Jericó até a cidade de Ai, que está junto a Bete-Áven, a leste de Betel, e lhes falou, dizendo: — Vão e espiem a terra. Os homens foram e espiaram a cidade.

[[v6-7-3]]

^<<v6-7-3,3>>^ E voltaram a Josué e lhe disseram: — Não é necessário que vá todo o povo; bastam uns dois ou três mil homens, para atacar a cidade de Ai. Não fatigue ali todo o povo, porque são poucos os inimigos.

[[v6-7-4]]

^<<v6-7-4,4>>^ Assim, apenas uns três mil homens do povo foram até lá, os quais fugiram diante dos homens da cidade de Ai.

[[v6-7-5]]

^<<v6-7-5,5>>^ Os homens dali mataram uns trinta e seis deles, e perseguiram os outros desde o portão da cidade até as pedreiras, e os derrotaram na descida. E o coração do povo se derreteu e se tornou como água.

[[v6-7-6]]

^<<v6-7-6,6>>^ Então Josué rasgou a sua roupa e se prostrou com o rosto em terra diante da arca do Senhor  até a tarde, ele e os anciãos de Israel; e puseram pó sobre a cabeça.

[[v6-7-7]]

^<<v6-7-7,7>>^ E Josué disse: — Ah! Senhor  Deus, por que fizeste este povo passar o Jordão, para nos entregares nas mãos dos amorreus, para sermos destruídos? Antes tivéssemos nos contentado em ficar do outro lado do Jordão!

[[v6-7-8]]

^<<v6-7-8,8>>^ Ah! Senhor, que direi? Pois Israel virou as costas diante dos seus inimigos!

[[v6-7-9]]

^<<v6-7-9,9>>^ Quando os cananeus e todos os moradores da terra ouvirem isto, nos cercarão e apagarão o nosso nome da face da terra; e, então, que farás ao teu grande nome?

[[v6-7-10]]

^<<v6-7-10,10>>^ Então o Senhor  disse a Josué: — Levante-se! Por que você está assim prostrado sobre o seu rosto?

[[v6-7-11]]

^<<v6-7-11,11>>^ Israel pecou. Quebraram a minha aliança, aquilo que eu lhes havia ordenado, pois tomaram das coisas condenadas, furtaram, mentiram e até debaixo da sua bagagem o puseram.

[[v6-7-12]]

^<<v6-7-12,12>>^ Por isso os filhos de Israel não puderam resistir aos seus inimigos; viraram as costas diante deles, porque Israel está condenado à destruição. Não continuarei com vocês, se não eliminarem do meio de vocês a coisa roubada.

[[v6-7-13]]

^<<v6-7-13,13>>^ — Levante-se, santifique o povo e diga: "Santifiquem-se para amanhã, porque assim diz o Senhor , Deus de Israel: ‘Há coisas condenadas no meio de vocês, ó Israel. Vocês não poderão resistir aos seus inimigos enquanto não eliminarem do meio de vocês as coisas condenadas.

[[v6-7-14]]

^<<v6-7-14,14>>^ Pela manhã, pois, vocês se apresentarão, segundo as suas tribos; e a tribo que o Senhor  designar por sorteio se apresentará, segundo as famílias; e a família que o Senhor  designar se apresentará por casas; e a casa que o Senhor  designar se apresentará homem por homem.

[[v6-7-15]]

^<<v6-7-15,15>>^ Aquele que for achado com a coisa condenada será queimado, ele e tudo o que tiver, porque quebrou a aliança do Senhor  e cometeu um ato infame em Israel.’"

[[v6-7-16]]

^<<v6-7-16,16>>^ Então Josué se levantou de madrugada e fez com que Israel se apresentasse, segundo as suas tribos; e a sorte caiu sobre a tribo de Judá.

[[v6-7-17]]

^<<v6-7-17,17>>^ Ele fez com que se apresentasse a tribo de Judá, e a família indicada foi a dos zeraítas. Fez com que se apresentasse a família dos zeraítas, homem por homem, e a família indicada foi a de Zabdi.

[[v6-7-18]]

^<<v6-7-18,18>>^ E, fazendo com que se apresentasse a família de Zabdi, homem por homem, o indicado foi Acã, filho de Carmi, filho de Zabdi, filho de Zera, da tribo de Judá.

[[v6-7-19]]

^<<v6-7-19,19>>^ Então Josué disse a Acã: — Meu filho, dê glória ao Senhor , Deus de Israel, e renda louvores a ele. E conte-me, agora, o que foi que você fez; não me esconda nada.

[[v6-7-20]]

^<<v6-7-20,20>>^ Acã respondeu a Josué: — É verdade, eu pequei contra o Senhor , Deus de Israel, e fiz assim e assim.

[[v6-7-21]]

^<<v6-7-21,21>>^ Quando vi entre o despojo uma boa capa babilônica, uns dois quilos e meio de prata e uma barra de ouro pesando mais de meio quilo, cobicei essas coisas e as peguei para mim; e eis que estão escondidas na terra, no meio da minha tenda, e a prata, por baixo.

[[v6-7-22]]

^<<v6-7-22,22>>^ Então Josué enviou mensageiros que foram correndo à tenda de Acã; e eis que tudo estava escondido nela, e a prata estava por baixo.

[[v6-7-23]]

^<<v6-7-23,23>>^ Tiraram aquelas coisas do meio da tenda, e as trouxeram a Josué e a todos os filhos de Israel, e as colocaram diante do Senhor .

[[v6-7-24]]

^<<v6-7-24,24>>^ Então Josué e todo o Israel com ele pegaram Acã, filho de Zera, e a prata, a capa, a barra de ouro, os filhos e as filhas dele, os seus bois, os seus jumentos, as suas ovelhas, a sua tenda e tudo o que ele tinha e os levaram para o vale de Acor.

[[v6-7-25]]

^<<v6-7-25,25>>^ Josué disse a Acã: — Por que você trouxe esta calamidade sobre nós? O Senhor  hoje trará calamidade sobre você. E todo o Israel o apedrejou. E, depois de apedrejá-los, ainda os queimou.

[[v6-7-26]]

^<<v6-7-26,26>>^ E levantaram sobre ele um montão de pedras, que permanece até o dia de hoje. Assim, o Senhor  apagou o furor da sua ira. Por isso aquele lugar se chama o vale de Acor até o dia de hoje.

'''

xref:006-josue/006-josue-006.adoc#v6-6-0[&#60; Capítulo Anterior] | <<v6-7-0,Topo>> | xref:006-josue/006-josue-008.adoc#v6-8-0[Próximo Capítulo &#62;]