include::./index.adoc[]

[[v6-15-0]]
=== Josué, 15
// naa ?, NAA - Nova Almeida Atualizada

[[v6-15-1]]

^<<v6-15-1,1>>^ A sorte da tribo dos filhos de Judá, segundo as suas famílias, caiu para o sul, até o limite de Edom, até o deserto de Zim, até a extremidade do lado sul.

[[v6-15-2]]

^<<v6-15-2,2>>^ O seu limite ao sul foi desde a extremidade do mar Salgado, desde a baía que olha para o sul;

[[v6-15-3]]

^<<v6-15-3,3>>^ sai para o sul, até a subida de Acrabim, passa por Zim, sobe do sul a Cades-Barneia,

[[v6-15-4]]

^<<v6-15-4,4>>^ passa por Hezrom, sobe a Adar e rodeia Carca; passa por Azmom e sai ao ribeiro do Egito; as saídas deste limite vão até o mar. Este será o limite de vocês do lado sul.

[[v6-15-5]]

^<<v6-15-5,5>>^ O limite para o leste será o mar Salgado, até a foz do Jordão; e o limite para o norte será da baía do mar, começando com a embocadura do Jordão,

[[v6-15-6]]

^<<v6-15-6,6>>^ limite que sobe até Bete-Hogla e passa do norte a Bete-Arabá, subindo até a pedra de Boã, filho de Rúben,

[[v6-15-7]]

^<<v6-15-7,7>>^ subindo ainda este limite a Debir desde o vale de Acor, olhando para o norte, rumo a Gilgal, a qual está à subida de Adumim, que está para o sul do ribeiro; daí, o limite passa até as águas de En-Semes; e as suas saídas estarão do lado de En-Rogel.

[[v6-15-8]]

^<<v6-15-8,8>>^ Deste ponto sobe pelo vale de Ben-Hinom, do lado dos jebuseus do Sul, isto é, Jerusalém; e este limite sobe até o alto do monte que está diante do vale de Hinom, para o oeste, que está no fim do vale dos Refains, do lado norte.

[[v6-15-9]]

^<<v6-15-9,9>>^ Então o limite vai desde o alto do monte até a fonte das águas de Neftoa; e sai até as cidades do monte Efrom; este limite vai ainda até Baalá, isto é, Quiriate-Jearim.

[[v6-15-10]]

^<<v6-15-10,10>>^ Então o limite dá volta desde Baalá, para o oeste, até o monte Seir, passa ao lado do monte de Jearim do lado norte, isto é, Quesalom, e, descendo a Bete-Semes, passa por Timna.

[[v6-15-11]]

^<<v6-15-11,11>>^ Segue mais ainda o limite ao lado de Ecrom, para o norte, e, indo a Siquerom, passa o monte de Baalá, saindo em Jabneel, para terminar no mar.

[[v6-15-12]]

^<<v6-15-12,12>>^ O limite do lado oeste é o mar Grande e as suas imediações. Estes são os limites dos filhos de Judá ao redor, segundo as suas famílias.

[[v6-15-13]]

^<<v6-15-13,13>>^ Josué deu a Calebe, filho de Jefoné, uma parte no meio dos filhos de Judá, segundo o Senhor  lhe havia ordenado, a saber, Quiriate-Arba, isto é, Hebrom. Este Arba era o pai de Anaque.

[[v6-15-14]]

^<<v6-15-14,14>>^ Dali Calebe expulsou os três filhos de Anaque: Sesai, Aimã e Talmai, gerados de Anaque.

[[v6-15-15]]

^<<v6-15-15,15>>^ Então Calebe avançou contra os moradores de Debir, cujo nome havia sido Quiriate-Sefer.

[[v6-15-16]]

^<<v6-15-16,16>>^ Calebe disse: — Darei a minha filha Acsa por mulher ao homem que atacar e conquistar Quiriate-Sefer.

[[v6-15-17]]

^<<v6-15-17,17>>^ Quem conquistou a cidade foi Otniel, filho de Quenaz, irmão de Calebe. E Calebe lhe deu a sua filha Acsa por mulher.

[[v6-15-18]]

^<<v6-15-18,18>>^ Esta, quando foi morar com Otniel, insistiu com ele para que pedisse um campo ao pai dela. Quando ela desceu do jumento, Calebe lhe perguntou: — O que é que você quer?

[[v6-15-19]]

^<<v6-15-19,19>>^ Ela respondeu: — Quero que me dê um presente. Já que o senhor me deu uma terra seca, me dê também algumas fontes de água. Então Calebe lhe deu as fontes superiores e as fontes inferiores.

[[v6-15-20]]

^<<v6-15-20,20>>^ Esta é a herança da tribo dos filhos de Judá, segundo as suas famílias.

[[v6-15-21]]

^<<v6-15-21,21>>^ As cidades no extremo sul da tribo dos filhos de Judá, na direção do território de Edom, eram estas: Cabzeel, Éder, Jagur,

[[v6-15-22]]

^<<v6-15-22,22>>^ Quiná, Dimona, Adada,

[[v6-15-23]]

^<<v6-15-23,23>>^ Quedes, Hazor, Itnã,

[[v6-15-24]]

^<<v6-15-24,24>>^ Zife, Telém, Bealote,

[[v6-15-25]]

^<<v6-15-25,25>>^ Hazor-Hadata, Queriote-Hezrom, que é Hazor,

[[v6-15-26]]

^<<v6-15-26,26>>^ Amã, Sema, Molada,

[[v6-15-27]]

^<<v6-15-27,27>>^ Hazar-Gada, Hesmom, Bete-Palete,

[[v6-15-28]]

^<<v6-15-28,28>>^ Hazar-Sual, Berseba, Biziotiá,

[[v6-15-29]]

^<<v6-15-29,29>>^ Baalá, Iim, Ezém,

[[v6-15-30]]

^<<v6-15-30,30>>^ Eltolade, Quesil, Horma,

[[v6-15-31]]

^<<v6-15-31,31>>^ Ziclague, Madmana, Sansana,

[[v6-15-32]]

^<<v6-15-32,32>>^ Lebaote, Silim, Aim e Rimom. Ao todo, vinte e nove cidades com as suas aldeias.

[[v6-15-33]]

^<<v6-15-33,33>>^ Na Sefelá, as cidades eram Estaol, Zorá, Asná,

[[v6-15-34]]

^<<v6-15-34,34>>^ Zanoa, En-Ganim, Tapua, Enã,

[[v6-15-35]]

^<<v6-15-35,35>>^ Jarmute, Adulão, Socó, Azeca,

[[v6-15-36]]

^<<v6-15-36,36>>^ Saaraim, Aditaim, Gedera e Gederotaim. Ao todo, catorze cidades com as suas aldeias.

[[v6-15-37]]

^<<v6-15-37,37>>^ Zenã, Hadasa, Migdal-Gade,

[[v6-15-38]]

^<<v6-15-38,38>>^ Dileã, Mispa, Jocteel,

[[v6-15-39]]

^<<v6-15-39,39>>^ Laquis, Boscate, Eglom,

[[v6-15-40]]

^<<v6-15-40,40>>^ Cabom, Laamás, Quitlis,

[[v6-15-41]]

^<<v6-15-41,41>>^ Gederote, Bete-Dagom, Naamá e Maquedá. Ao todo, dezesseis cidades com as suas aldeias.

[[v6-15-42]]

^<<v6-15-42,42>>^ Libna, Eter, Asã,

[[v6-15-43]]

^<<v6-15-43,43>>^ Ifta, Asná, Nezibe,

[[v6-15-44]]

^<<v6-15-44,44>>^ Queila, Aczibe e Maressa. Ao todo, nove cidades com as suas aldeias.

[[v6-15-45]]

^<<v6-15-45,45>>^ Ecrom com as suas vilas e aldeias;

[[v6-15-46]]

^<<v6-15-46,46>>^ desde Ecrom até o mar, todas as que estão do lado de Asdode, com as suas aldeias.

[[v6-15-47]]

^<<v6-15-47,47>>^ Asdode, as suas vilas e aldeias; Gaza, as suas vilas e aldeias, até o rio do Egito e o mar Grande com as suas imediações.

[[v6-15-48]]

^<<v6-15-48,48>>^ Na região montanhosa, as cidades eram Samir, Jatir, Socó,

[[v6-15-49]]

^<<v6-15-49,49>>^ Daná, Quiriate-Sana, que é Debir,

[[v6-15-50]]

^<<v6-15-50,50>>^ Anabe, Estemoa, Anim,

[[v6-15-51]]

^<<v6-15-51,51>>^ Gósen, Holom e Gilo. Ao todo, onze cidades com as suas aldeias.

[[v6-15-52]]

^<<v6-15-52,52>>^ Arabe, Dumá, Esã,

[[v6-15-53]]

^<<v6-15-53,53>>^ Janim, Bete-Tapua, Afeca,

[[v6-15-54]]

^<<v6-15-54,54>>^ Hunta, Quiriate-Arba, que é Hebrom, e Zior. Ao todo, nove cidades com as suas aldeias.

[[v6-15-55]]

^<<v6-15-55,55>>^ Maom, Carmelo, Zife, Jutá,

[[v6-15-56]]

^<<v6-15-56,56>>^ Jezreel, Jocdeão, Zanoa,

[[v6-15-57]]

^<<v6-15-57,57>>^ Caim, Gibeá e Timna. Ao todo, dez cidades com as suas aldeias.

[[v6-15-58]]

^<<v6-15-58,58>>^ Halul, Bete-Zur, Gedor,

[[v6-15-59]]

^<<v6-15-59,59>>^ Maarate, Bete-Anote e Eltecom. Ao todo, seis cidades com as suas aldeias.

[[v6-15-60]]

^<<v6-15-60,60>>^ Quiriate-Baal, que é Quiriate-Jearim, e Rabá. Ao todo, duas cidades com as suas aldeias.

[[v6-15-61]]

^<<v6-15-61,61>>^ No deserto, as cidades eram Bete-Arabá, Midim, Secaca,

[[v6-15-62]]

^<<v6-15-62,62>>^ Nibsã, Cidade do Sal e En-Gedi. Ao todo, seis cidades com as suas aldeias.

[[v6-15-63]]

^<<v6-15-63,63>>^ Mas os filhos de Judá não puderam expulsar os jebuseus que viviam em Jerusalém. Assim, os jebuseus moram com os filhos de Judá em Jerusalém até o dia de hoje.

'''

xref:006-josue/006-josue-014.adoc#v6-14-0[&#60; Capítulo Anterior] | <<v6-15-0,Topo>> | xref:006-josue/006-josue-016.adoc#v6-16-0[Próximo Capítulo &#62;]