include::./index.adoc[]

[[v6-10-0]]
=== Josué, 10
// naa ?, NAA - Nova Almeida Atualizada

[[v6-10-1]]

^<<v6-10-1,1>>^ Quando Adoni-Zedeque, rei de Jerusalém, ouviu que Josué havia tomado a cidade de Ai e a havia destruído totalmente, fazendo com Ai e com o seu rei o mesmo que havia feito com Jericó e com o seu rei, e que os moradores de Gibeão tinham feito paz com os israelitas e estavam no meio deles,

[[v6-10-2]]

^<<v6-10-2,2>>^ ficou com muito medo, porque Gibeão era uma cidade grande, tão grande como uma das cidades reais e ainda maior do que Ai, e todos os seus homens eram valentes.

[[v6-10-3]]

^<<v6-10-3,3>>^ Por isso Adoni-Zedeque, rei de Jerusalém, enviou mensageiros a Hoão, rei de Hebrom, e a Pirã, rei de Jarmute, e a Jafia, rei de Laquis, e a Debir, rei de Eglom, dizendo:

[[v6-10-4]]

^<<v6-10-4,4>>^ — Venham até aqui e me ajudem. Vamos atacar Gibeão, porque fez paz com Josué e com os filhos de Israel.

[[v6-10-5]]

^<<v6-10-5,5>>^ Então se ajuntaram cinco reis dos amorreus, o rei de Jerusalém, o rei de Hebrom, o rei de Jarmute, o rei de Laquis e o rei de Eglom, eles e todas as suas tropas; vieram e acamparam junto a Gibeão e atacaram a cidade.

[[v6-10-6]]

^<<v6-10-6,6>>^ Os homens de Gibeão mandaram dizer a Josué, no arraial de Gilgal: — Não deixe de ajudar estes seus servos. Venha depressa até aqui! Livre-nos e ajude-nos, pois todos os reis dos amorreus que moram nas montanhas se ajuntaram contra nós.

[[v6-10-7]]

^<<v6-10-7,7>>^ Então Josué partiu de Gilgal, ele e todo o exército com ele e todos os valentes.

[[v6-10-8]]

^<<v6-10-8,8>>^ E o Senhor  disse a Josué: — Não tenha medo deles, porque eu os entreguei nas suas mãos. Nenhum deles poderá resistir a você.

[[v6-10-9]]

^<<v6-10-9,9>>^ Josué os atacou de surpresa, porque tinha marchado durante toda a noite, saindo de Gilgal.

[[v6-10-10]]

^<<v6-10-10,10>>^ O Senhor  fez com que eles entrassem em pânico diante de Israel, e os derrotou completamente em Gibeão, e os foi perseguindo pelo caminho que sobe a Bete-Horom, e os derrotou até Azeca e Maquedá.

[[v6-10-11]]

^<<v6-10-11,11>>^ E aconteceu que, enquanto eles fugiam de Israel, na descida de Bete-Horom, o Senhor  fez cair do céu sobre eles grandes pedras, até Azeca, e morreram. Mais foram os que morreram pela chuva de pedras do que os que foram mortos à espada pelos filhos de Israel.

[[v6-10-12]]

^<<v6-10-12,12>>^ Então Josué falou ao Senhor , no dia em que o Senhor  entregou os amorreus nas mãos dos filhos de Israel. E, na presença dos israelitas, ele disse: "Sol, detenha-se em Gibeão, e você, lua, pare no vale de Aijalom."

[[v6-10-13]]

^<<v6-10-13,13>>^ E o sol se deteve, e a lua parou até que o povo se vingou de seus inimigos. Não está isso escrito no Livro dos Justos? O sol se deteve no meio do céu e não se apressou a pôr-se, por quase um dia inteiro.

[[v6-10-14]]

^<<v6-10-14,14>>^ Não houve dia semelhante a este, nem antes nem depois dele, tendo o Senhor , assim, atendido à voz de um homem; porque o Senhor  lutava por Israel.

[[v6-10-15]]

^<<v6-10-15,15>>^ Então Josué voltou ao arraial, em Gilgal, e todo o Israel foi com ele.

[[v6-10-16]]

^<<v6-10-16,16>>^ Aqueles cinco reis fugiram e se esconderam numa caverna em Maquedá.

[[v6-10-17]]

^<<v6-10-17,17>>^ E foi dito a Josué: — Os cinco reis foram achados. Estão escondidos numa caverna em Maquedá.

[[v6-10-18]]

^<<v6-10-18,18>>^ Então Josué disse: — Rolem grandes pedras até a entrada da caverna e ponham junto a ela alguns homens para que fiquem vigiando. Mas vocês não se detenham.

[[v6-10-19]]

^<<v6-10-19,19>>^ Persigam os seus inimigos e matem os que vão ficando para trás. Não os deixem entrar nas cidades deles, porque o Senhor , o Deus de vocês, já os entregou nas mãos de vocês.

[[v6-10-20]]

^<<v6-10-20,20>>^ Quando Josué e os filhos de Israel acabaram de derrotá-los completamente, até consumi-los, e os que conseguiram escapar tinham entrado nas cidades fortificadas,

[[v6-10-21]]

^<<v6-10-21,21>>^ todo o povo voltou em paz para junto de Josué, no acampamento de Maquedá. E não houve ninguém que movesse a língua contra os filhos de Israel.

[[v6-10-22]]

^<<v6-10-22,22>>^ Depois Josué disse: — Abram a entrada da caverna e tragam para mim aqueles cinco reis que lá se encontram.

[[v6-10-23]]

^<<v6-10-23,23>>^ Eles fizeram assim e da caverna lhe trouxeram os cinco reis: o rei de Jerusalém, o de Hebrom, o de Jarmute, o de Laquis e o de Eglom.

[[v6-10-24]]

^<<v6-10-24,24>>^ Quando os reis foram trazidos a Josué, este chamou todos os homens de Israel e disse aos capitães do exército que tinham ido com ele: — Venham e ponham o pé sobre o pescoço destes reis. E eles foram e puseram os pés sobre o pescoço deles.

[[v6-10-25]]

^<<v6-10-25,25>>^ Então Josué disse aos capitães do exército: — Não tenham medo, nem fiquem assustados. Sejam fortes e corajosos, porque assim o Senhor  fará com todos os seus inimigos, contra os quais vocês lutarem.

[[v6-10-26]]

^<<v6-10-26,26>>^ Depois disto, Josué matou os reis e os pendurou em cinco árvores. E eles ficaram pendurados ali até a tarde.

[[v6-10-27]]

^<<v6-10-27,27>>^ Ao pôr do sol, Josué ordenou que os tirassem das árvores. E lançaram-nos na caverna onde se haviam escondido. Na entrada da caverna, puseram grandes pedras, que estão lá até o dia de hoje.

[[v6-10-28]]

^<<v6-10-28,28>>^ No mesmo dia, Josué tomou a cidade de Maquedá e a feriu à espada, bem como ao seu rei; destruiu-os totalmente e a todos os que nela estavam, sem deixar nem sequer um. Fez com o rei de Maquedá o mesmo que havia feito com o rei de Jericó.

[[v6-10-29]]

^<<v6-10-29,29>>^ Então Josué, e todo o Israel com ele, foi de Maquedá a Libna e atacou a cidade.

[[v6-10-30]]

^<<v6-10-30,30>>^ E o Senhor  a entregou nas mãos de Israel, tanto a cidade como o seu rei, e a feriu à espada, a ela e todos os que nela estavam, sem deixar nem sequer um. Fez com o seu rei o mesmo que havia feito com o rei de Jericó.

[[v6-10-31]]

^<<v6-10-31,31>>^ Então Josué, e todo o Israel com ele, foi de Libna a Laquis; cercou a cidade e a atacou.

[[v6-10-32]]

^<<v6-10-32,32>>^ E o Senhor  entregou Laquis nas mãos de Israel, que, no dia seguinte, a tomou e a feriu à espada, a ela e todos os que nela estavam, conforme tudo o que havia feito com Libna.

[[v6-10-33]]

^<<v6-10-33,33>>^ Horão, rei de Gezer, saiu para ajudar Laquis; porém Josué o derrotou, a ele e o seu povo, sem deixar nem sequer um.

[[v6-10-34]]

^<<v6-10-34,34>>^ E Josué, e todo o Israel com ele, foi de Laquis a Eglom. Cercaram a cidade e a atacaram;

[[v6-10-35]]

^<<v6-10-35,35>>^ e, no mesmo dia, a tomaram e a feriram à espada; e destruíram totalmente os que nela estavam, conforme tudo o que haviam feito com Laquis.

[[v6-10-36]]

^<<v6-10-36,36>>^ Depois, Josué, e todo o Israel com ele, foi de Eglom a Hebrom. E guerrearam contra ela,

[[v6-10-37]]

^<<v6-10-37,37>>^ tomaram a cidade e a feriram à espada, tanto o seu rei como todas as suas cidades e todos os que nelas estavam, sem deixar nem sequer um, conforme tudo o que haviam feito com Eglom. Josué executou a condenação contra ela e contra todos os que nela estavam.

[[v6-10-38]]

^<<v6-10-38,38>>^ Então Josué, e todo o Israel com ele, voltou e atacou Debir;

[[v6-10-39]]

^<<v6-10-39,39>>^ e tomou a cidade com o seu rei e todas as suas cidades e as feriu à espada. Todos os que nelas estavam, destruiu-os totalmente sem deixar nem sequer um. Como havia feito com Hebrom, com Libna e o seu rei, também fez com Debir e o seu rei.

[[v6-10-40]]

^<<v6-10-40,40>>^ Assim Josué conquistou toda aquela terra, a região montanhosa, o Neguebe, a Sefelá e as descidas das águas, e derrotou todos os seus reis. Destruiu tudo o que tinha fôlego de vida, sem deixar nem sequer um, como o Senhor , o Deus de Israel, havia ordenado.

[[v6-10-41]]

^<<v6-10-41,41>>^ Josué os derrotou desde Cades-Barneia até Gaza, bem como toda a terra de Gósen até Gibeão.

[[v6-10-42]]

^<<v6-10-42,42>>^ E, de uma só vez, Josué venceu todos estes reis e tomou as suas terras, porque o Senhor , o Deus de Israel, lutava por Israel.

[[v6-10-43]]

^<<v6-10-43,43>>^ Então Josué, e todo o Israel com ele, voltou ao arraial em Gilgal.

'''

xref:006-josue/006-josue-009.adoc#v6-9-0[&#60; Capítulo Anterior] | <<v6-10-0,Topo>> | xref:006-josue/006-josue-011.adoc#v6-11-0[Próximo Capítulo &#62;]