include::./index.adoc[]

[[v6-13-0]]
=== Josué, 13
// naa ?, NAA - Nova Almeida Atualizada

[[v6-13-1]]

^<<v6-13-1,1>>^ Josué já era bem idoso e o Senhor  lhe disse: — Você já é bem idoso, e ainda ficou muita terra para ser conquistada.

[[v6-13-2]]

^<<v6-13-2,2>>^ Esta é a terra ainda não conquistada: todas as regiões dos filisteus e toda a Gesur;

[[v6-13-3]]

^<<v6-13-3,3>>^ desde Sior, que está diante do Egito, até o limite de Ecrom, para o norte, que se considera como dos cananeus; cinco governantes dos filisteus: o de Gaza, o de Asdode, o de Asquelom, o de Gate e o de Ecrom; e os aveus,

[[v6-13-4]]

^<<v6-13-4,4>>^ ao sul, além de toda a terra dos cananeus e Meara, que é dos sidônios, até Afeca, na fronteira dos amorreus;

[[v6-13-5]]

^<<v6-13-5,5>>^ e ainda a terra dos gibleus e todo o Líbano, para o leste, desde Baal-Gade, ao pé do monte Hermom, até a entrada de Hamate;

[[v6-13-6]]

^<<v6-13-6,6>>^ todos os que habitam nas montanhas desde o Líbano até Misrefote-Maim, todos os sidônios. Eu os expulsarei de diante dos filhos de Israel; reparta, pois, a terra por herança a Israel, como ordenei a você.

[[v6-13-7]]

^<<v6-13-7,7>>^ Distribua, agora, a terra por herança às nove tribos e à meia tribo de Manassés.

[[v6-13-8]]

^<<v6-13-8,8>>^ Com a outra meia tribo, os rubenitas e os gaditas já receberam a sua herança do outro lado do Jordão, para o leste, como já lhes tinha dado Moisés, servo do Senhor .

[[v6-13-9]]

^<<v6-13-9,9>>^ Começando com Aroer, que está à borda do vale de Arnom, mais a cidade que está no meio do vale, todo o planalto de Medeba até Dibom;

[[v6-13-10]]

^<<v6-13-10,10>>^ e todas as cidades de Seom, rei dos amorreus, que reinou em Hesbom, até a fronteira dos filhos de Amom.

[[v6-13-11]]

^<<v6-13-11,11>>^ E Gileade, o território dos gesuritas, o dos maacatitas, todo o monte Hermom e toda a Basã até Salca;

[[v6-13-12]]

^<<v6-13-12,12>>^ todo o reino de Ogue, em Basã, que reinou em Astarote e em Edrei, que ficou do resto dos refains, o qual Moisés derrotou e expulsou.

[[v6-13-13]]

^<<v6-13-13,13>>^ Porém os filhos de Israel não expulsaram os gesuritas, nem os maacatitas; pelo contrário, Gesur e Maacate permaneceram no meio de Israel até o dia de hoje.

[[v6-13-14]]

^<<v6-13-14,14>>^ Foi somente à tribo de Levi que Moisés não deu herança; as ofertas queimadas do Senhor , Deus de Israel, são a sua herança, como já lhe tinha dito.

[[v6-13-15]]

^<<v6-13-15,15>>^ Moisés deu herança à tribo dos filhos de Rúben, segundo as suas famílias,

[[v6-13-16]]

^<<v6-13-16,16>>^ começando o seu território com Aroer, que está à borda do vale de Arnom, mais a cidade que está no meio do vale e todo o planalto até Medeba;

[[v6-13-17]]

^<<v6-13-17,17>>^ Hesbom e todas as suas cidades, que estão no planalto: Dibom, Bamote-Baal e Bete-Baal-Meom,

[[v6-13-18]]

^<<v6-13-18,18>>^ Jaza, Quedemote, Mefaate;

[[v6-13-19]]

^<<v6-13-19,19>>^ Quiriataim, Sibma, Zerete-Saar, no monte do vale;

[[v6-13-20]]

^<<v6-13-20,20>>^ Bete-Peor, as encostas do monte Pisga e Bete-Jesimote;

[[v6-13-21]]

^<<v6-13-21,21>>^ e todas as cidades do planalto e todo o reino de Seom, rei dos amorreus, que reinou em Hesbom, a quem Moisés derrotou, bem como os príncipes de Midiã, Evi, Requém, Zur, Hur e Reba, príncipes de Seom, moradores da terra.

[[v6-13-22]]

^<<v6-13-22,22>>^ Além de outros que foram mortos, os filhos de Israel também mataram à espada Balaão, filho de Beor, o adivinho.

[[v6-13-23]]

^<<v6-13-23,23>>^ A fronteira dos filhos de Rúben é o Jordão e suas imediações; esta é a herança dos filhos de Rúben, segundo as suas famílias: as cidades com suas aldeias.

[[v6-13-24]]

^<<v6-13-24,24>>^ Moisés deu herança à tribo de Gade, a saber, a seus filhos, segundo as suas famílias.

[[v6-13-25]]

^<<v6-13-25,25>>^ O seu território incluía Jazer, todas as cidades de Gileade e metade da terra dos filhos de Amom, até Aroer, que está diante de Rabá;

[[v6-13-26]]

^<<v6-13-26,26>>^ desde Hesbom até Ramate-Mispa e Betonim; e desde Maanaim até o limite de Debir;

[[v6-13-27]]

^<<v6-13-27,27>>^ e, no vale: Bete-Arã, Bete-Ninra, Sucote e Zafom, o resto do reino de Seom, rei de Hesbom, mais o Jordão e suas imediações, até a extremidade do mar de Quinerete, do outro lado do Jordão, na direção do leste.

[[v6-13-28]]

^<<v6-13-28,28>>^ Esta é a herança dos filhos de Gade, segundo as suas famílias: as cidades com as suas aldeias.

[[v6-13-29]]

^<<v6-13-29,29>>^ Moisés também deu herança à meia tribo de Manassés, segundo as suas famílias.

[[v6-13-30]]

^<<v6-13-30,30>>^ O seu território começava com Maanaim e incluía todo o Basã, todo o reino de Ogue, rei de Basã, e todas as aldeias de Jair, que estão em Basã, sessenta cidades;

[[v6-13-31]]

^<<v6-13-31,31>>^ e metade de Gileade, Astarote e Edrei, cidades do reino de Ogue, em Basã. Estas foram dadas aos filhos de Maquir, filho de Manassés, a saber, à metade dos filhos de Maquir, segundo as suas famílias.

[[v6-13-32]]

^<<v6-13-32,32>>^ São estas as heranças que Moisés repartiu nas campinas de Moabe, do outro lado do Jordão, na altura de Jericó, para o leste.

[[v6-13-33]]

^<<v6-13-33,33>>^ Porém à tribo de Levi Moisés não deu herança; o Senhor , Deus de Israel, é a sua herança, como já lhe tinha dito.

'''

xref:006-josue/006-josue-012.adoc#v6-12-0[&#60; Capítulo Anterior] | <<v6-13-0,Topo>> | xref:006-josue/006-josue-014.adoc#v6-14-0[Próximo Capítulo &#62;]