include::./index.adoc[]

[[v6-23-0]]
=== Josué, 23
// naa ?, NAA - Nova Almeida Atualizada

[[v6-23-1]]

^<<v6-23-1,1>>^ Muito tempo havia se passado desde que o Senhor  tinha dado a Israel repouso de todos os seus inimigos ao redor. Josué agora já era bem idoso.

[[v6-23-2]]

^<<v6-23-2,2>>^ Ele chamou todo o Israel, os seus anciãos, os seus chefes, os seus juízes e os seus oficiais e lhes disse: — Já estou bem velho,

[[v6-23-3]]

^<<v6-23-3,3>>^ e vocês já viram tudo o que o Senhor , seu Deus, fez com todas essas nações por causa de vocês, porque o Senhor , seu Deus, é o que lutou por vocês.

[[v6-23-4]]

^<<v6-23-4,4>>^ Vejam bem: por sorteio eu reparti entre as tribos de vocês estas nações que restam, juntamente com todas as nações que tenho eliminado, desde o Jordão até o mar Grande, na direção do pôr do sol.

[[v6-23-5]]

^<<v6-23-5,5>>^ O Senhor , seu Deus, as afastará e as expulsará da presença de vocês; e vocês tomarão posse das terras dessas nações, como o Senhor , seu Deus, prometeu.

[[v6-23-6]]

^<<v6-23-6,6>>^ — Portanto, esforcem-se muito para guardar e cumprir tudo o que está escrito no Livro da Lei de Moisés, para que dela não se afastem, nem para a direita nem para a esquerda,

[[v6-23-7]]

^<<v6-23-7,7>>^ e para que não se misturem com essas nações que restaram entre vocês. Não façam menção dos nomes de seus deuses, nem jurem por eles. Não sirvam, nem adorem esses deuses.

[[v6-23-8]]

^<<v6-23-8,8>>^ Pelo contrário, apeguem-se ao Senhor , seu Deus, como vocês têm feito até o dia de hoje.

[[v6-23-9]]

^<<v6-23-9,9>>^ Porque o Senhor  expulsou de diante de vocês grandes e fortes nações; e, até o dia de hoje, ninguém conseguiu resistir a vocês.

[[v6-23-10]]

^<<v6-23-10,10>>^ Um só de vocês perseguirá mil, pois o Senhor , seu Deus, é quem luta por vocês, como ele prometeu.

[[v6-23-11]]

^<<v6-23-11,11>>^ — Portanto, empenhem-se em amar o Senhor , seu Deus.

[[v6-23-12]]

^<<v6-23-12,12>>^ Porque, se vocês se desviarem dele e se apegarem ao que resta dessas nações que ainda se encontram entre vocês, e se unirem com elas por meio de casamento, e se misturarem com elas, e elas com vocês,

[[v6-23-13]]

^<<v6-23-13,13>>^ saibam com certeza que o Senhor , seu Deus, não expulsará mais essas nações de diante de vocês. Pelo contrário, elas serão um laço e uma rede para vocês, e açoite nas costas e espinhos nos olhos, até que vocês desapareçam desta boa terra que o Senhor , seu Deus, lhes deu.

[[v6-23-14]]

^<<v6-23-14,14>>^ — Eis que hoje sigo pelo caminho de todos os mortais, e vocês sabem de todo o coração e de toda a alma que nem uma só promessa falhou de todas as boas palavras que o Senhor , seu Deus, lhes falou; todas se cumpriram, nem uma delas falhou.

[[v6-23-15]]

^<<v6-23-15,15>>^ E assim como se cumpriram todas estas boas coisas que o Senhor , seu Deus, lhes prometeu, assim o Senhor  também cumprirá contra vocês todas as ameaças, até que os destrua de sobre a boa terra que o Senhor , seu Deus, lhes deu.

[[v6-23-16]]

^<<v6-23-16,16>>^ Se violarem a aliança que o Senhor , seu Deus, lhes ordenou, e forem e servirem outros deuses, e os adorarem, a ira do Senhor  se acenderá sobre vocês, e logo vocês desaparecerão da boa terra que ele lhes deu.

'''

xref:006-josue/006-josue-022.adoc#v6-22-0[&#60; Capítulo Anterior] | <<v6-23-0,Topo>> | xref:006-josue/006-josue-024.adoc#v6-24-0[Próximo Capítulo &#62;]