include::./index.adoc[]

[[v6-3-0]]
=== Josué, 3
// naa ?, NAA - Nova Almeida Atualizada

[[v6-3-1]]

^<<v6-3-1,1>>^ Josué se levantou de madrugada, e, tendo ele e todos os filhos de Israel partido de Sitim, vieram até o Jordão e pousaram ali antes que passassem.

[[v6-3-2]]

^<<v6-3-2,2>>^ Ao fim de três dias, os oficiais passaram pelo meio do arraial

[[v6-3-3]]

^<<v6-3-3,3>>^ e deram ordens ao povo, dizendo: — Quando vocês virem que os sacerdotes levitas estão levando a arca da aliança do Senhor , seu Deus, saiam também do lugar em que vocês estão e sigam a arca.

[[v6-3-4]]

^<<v6-3-4,4>>^ Contudo, deixem uma distância de cerca de um quilômetro entre vocês e a arca; não se aproximem dela. Dessa forma, vocês saberão o caminho pelo qual devem ir, visto que nunca antes passaram por tal caminho.

[[v6-3-5]]

^<<v6-3-5,5>>^ Josué disse ao povo: — Santifiquem-se, porque amanhã o Senhor  fará maravilhas no meio de vocês.

[[v6-3-6]]

^<<v6-3-6,6>>^ E também falou aos sacerdotes, dizendo: — Levantem a arca da aliança e passem adiante do povo. Levantaram, pois, a arca da aliança e foram andando adiante do povo.

[[v6-3-7]]

^<<v6-3-7,7>>^ Então o Senhor  disse a Josué: — Hoje começarei a engrandecer você aos olhos de todo o Israel, para que saibam que, como estive com Moisés, assim estarei com você.

[[v6-3-8]]

^<<v6-3-8,8>>^ Portanto, você dará uma ordem aos sacerdotes que levam a arca da aliança, dizendo: "Quando chegarem às margens das águas do Jordão, parem ali."

[[v6-3-9]]

^<<v6-3-9,9>>^ Então Josué disse aos filhos de Israel: — Venham cá e ouçam as palavras do Senhor , seu Deus.

[[v6-3-10]]

^<<v6-3-10,10>>^ Josué continuou: — Nisto vocês saberão que o Deus vivo está no meio de vocês e que sem falta expulsará de diante de vocês os cananeus, os heteus, os heveus, os ferezeus, os girgaseus, os amorreus e os jebuseus.

[[v6-3-11]]

^<<v6-3-11,11>>^ Eis que a arca da aliança do Senhor de toda a terra vai passar o Jordão na frente de vocês.

[[v6-3-12]]

^<<v6-3-12,12>>^ E agora escolham doze homens das tribos de Israel, um de cada tribo.

[[v6-3-13]]

^<<v6-3-13,13>>^ Quando as plantas dos pés dos sacerdotes que levam a arca do Senhor  Deus, o Senhor de toda a terra, tocarem nas águas do Jordão, elas serão cortadas, a saber, as águas que vêm de cima, e se amontoarão.

[[v6-3-14]]

^<<v6-3-14,14>>^ Quando o povo saiu das suas tendas, para passar o Jordão, os sacerdotes que levavam a arca da aliança iam adiante do povo.

[[v6-3-15]]

^<<v6-3-15,15>>^ E, quando os que levavam a arca chegaram ao Jordão, e os seus pés se molharam na beira das águas (porque o Jordão transbordava sobre todas as suas ribanceiras, durante todo o tempo da colheita),

[[v6-3-16]]

^<<v6-3-16,16>>^ as águas que vinham de cima pararam de correr; levantaram-se num montão, numa grande distância, até a cidade de Adã, que fica ao lado de Sartã; e as águas que desciam ao mar da Arabá, que é o mar Salgado, foram completamente cortadas. Então o povo passou diante de Jericó.

[[v6-3-17]]

^<<v6-3-17,17>>^ Porém os sacerdotes que levavam a arca da aliança do Senhor  pararam firmes no meio do Jordão, e todo o Israel passou a pé enxuto, atravessando o Jordão.

'''

xref:006-josue/006-josue-002.adoc#v6-2-0[&#60; Capítulo Anterior] | <<v6-3-0,Topo>> | xref:006-josue/006-josue-004.adoc#v6-4-0[Próximo Capítulo &#62;]