include::./index.adoc[]

[[v6-5-0]]
=== Josué, 5
// naa ?, NAA - Nova Almeida Atualizada

[[v6-5-1]]

^<<v6-5-1,1>>^ Quando todos os reis dos amorreus que habitavam deste lado do Jordão, a oeste, e todos os reis dos cananeus que estavam junto ao mar ouviram que o Senhor  tinha secado as águas do Jordão diante dos filhos de Israel, até que tivéssemos passado, o coração deles se derreteu de medo e ficaram desanimados, por causa dos filhos de Israel.

[[v6-5-2]]

^<<v6-5-2,2>>^ Naquele tempo o Senhor  disse a Josué: — Faça facas de pedra e passe de novo a circuncidar os filhos de Israel.

[[v6-5-3]]

^<<v6-5-3,3>>^ Então Josué fez facas de pedra e circuncidou os filhos de Israel em Gibeate-Haralote.

[[v6-5-4]]

^<<v6-5-4,4>>^ Foi esta a razão por que Josué os circuncidou: todo o povo que tinha saído do Egito, os homens, todos os homens de guerra, tinham morrido pelo caminho, no deserto.

[[v6-5-5]]

^<<v6-5-5,5>>^ Porque todo o povo que saiu do Egito estava circuncidado, mas a nenhum deles que havia nascido no deserto, pelo caminho, depois de terem saído do Egito, haviam circuncidado.

[[v6-5-6]]

^<<v6-5-6,6>>^ Porque os filhos de Israel andaram quarenta anos pelo deserto, até desaparecer toda a nação, a saber, os homens de guerra que saíram do Egito, que não obedeceram à voz do Senhor , aos quais o Senhor  tinha jurado que não lhes deixaria ver a terra que o Senhor , sob juramento, prometeu dar a seus pais, terra que mana leite e mel.

[[v6-5-7]]

^<<v6-5-7,7>>^ Porém em seu lugar pôs os filhos deles, e a estes Josué circuncidou. Estavam incircuncisos, porque não os circuncidaram no caminho.

[[v6-5-8]]

^<<v6-5-8,8>>^ Depois que toda a nação foi circuncidada, ficaram no seu lugar no arraial, até que sararam.

[[v6-5-9]]

^<<v6-5-9,9>>^ Então o Senhor  disse a Josué: — Hoje removi de vocês a vergonha do Egito. Por isso aquele lugar foi chamado de Gilgal até o dia de hoje.

[[v6-5-10]]

^<<v6-5-10,10>>^ Enquanto os filhos de Israel estavam acampados em Gilgal, celebraram a Páscoa no dia catorze do mês, à tarde, nas campinas de Jericó.

[[v6-5-11]]

^<<v6-5-11,11>>^ No dia seguinte à Páscoa, comeram do fruto da terra; nesse mesmo dia comeram pães sem fermento e cereais tostados.

[[v6-5-12]]

^<<v6-5-12,12>>^ Um dia depois de terem comido do produto da terra, o maná cessou, e os filhos de Israel não mais o tiveram; mas, naquele ano, comeram do que foi colhido na terra de Canaã.

[[v6-5-13]]

^<<v6-5-13,13>>^ Quando Josué estava perto de Jericó, levantou os olhos e olhou; e eis que se achava em pé diante dele um homem que trazia na mão uma espada. Josué se aproximou dele e perguntou: — Você é dos nossos ou dos nossos adversários?

[[v6-5-14]]

^<<v6-5-14,14>>^ Ele respondeu: — Não sou nem uma coisa nem outra. Sou príncipe do exército do Senhor  e acabo de chegar. Então Josué se prostrou com o rosto em terra e o adorou. E lhe disse: — Que diz meu senhor ao seu servo?

[[v6-5-15]]

^<<v6-5-15,15>>^ O príncipe do exército do Senhor  respondeu a Josué: — Tire as sandálias dos pés, porque o lugar em que você está é santo. E Josué fez assim.

'''

xref:006-josue/006-josue-004.adoc#v6-4-0[&#60; Capítulo Anterior] | <<v6-5-0,Topo>> | xref:006-josue/006-josue-006.adoc#v6-6-0[Próximo Capítulo &#62;]