include::./index.adoc[]

[[v6-12-0]]
=== Josué, 12
// naa ?, NAA - Nova Almeida Atualizada

[[v6-12-1]]

^<<v6-12-1,1>>^ Estes são os reis da terra que os filhos de Israel derrotaram e de cujas terras se apossaram do outro lado do Jordão, na direção do leste, desde o ribeiro de Arnom até o monte Hermom e toda a planície do leste:

[[v6-12-2]]

^<<v6-12-2,2>>^ Seom, rei dos amorreus, que habitava em Hesbom e dominava desde Aroer, que está à beira do vale de Arnom, e desde o meio do vale e a metade de Gileade até o ribeiro de Jaboque, limite dos filhos de Amom;

[[v6-12-3]]

^<<v6-12-3,3>>^ desde a campina até o mar de Quinerete, para o leste, e até o mar da Campina, o mar Salgado, para o leste, pelo caminho de Bete-Jesimote; e desde o sul abaixo das encostas do monte Pisga.

[[v6-12-4]]

^<<v6-12-4,4>>^ Também derrotaram Ogue, rei de Basã, um dos remanescentes dos refains que morava em Astarote e em Edrei.

[[v6-12-5]]

^<<v6-12-5,5>>^ Ele dominava no monte Hermom, em Salca e em toda a Basã, até a fronteira dos gesuritas e dos maacatitas, e metade de Gileade, até a fronteira de Seom, rei de Hesbom.

[[v6-12-6]]

^<<v6-12-6,6>>^ Moisés, servo do Senhor , e os filhos de Israel os derrotaram. E Moisés, servo do Senhor , deu esta terra como propriedade aos rubenitas, aos gaditas e à meia tribo de Manassés.

[[v6-12-7]]

^<<v6-12-7,7>>^ Estes são os reis da terra que Josué e os filhos de Israel derrotaram deste lado do Jordão, na direção do oeste, desde Baal-Gade, no vale do Líbano, até o monte Halaque, que sobe a Seir, e cuja terra Josué deu como propriedade às tribos de Israel, segundo as suas divisões,

[[v6-12-8]]

^<<v6-12-8,8>>^ a saber, o que havia na região montanhosa, na Sefelá, na Arabá, nas descidas das águas, no deserto e no Neguebe, onde estava o heteu, o amorreu, o cananeu, o ferezeu, o heveu e o jebuseu:

[[v6-12-9]]

^<<v6-12-9,9>>^ o rei de Jericó; o rei de Ai, que está ao lado de Betel;

[[v6-12-10]]

^<<v6-12-10,10>>^ o rei de Jerusalém; o rei de Hebrom;

[[v6-12-11]]

^<<v6-12-11,11>>^ o rei de Jarmute; o rei de Laquis;

[[v6-12-12]]

^<<v6-12-12,12>>^ o rei de Eglom; o rei de Gezer;

[[v6-12-13]]

^<<v6-12-13,13>>^ o rei de Debir; o rei de Geder;

[[v6-12-14]]

^<<v6-12-14,14>>^ o rei de Horma; o rei de Arade;

[[v6-12-15]]

^<<v6-12-15,15>>^ o rei de Libna; o rei de Adulão;

[[v6-12-16]]

^<<v6-12-16,16>>^ o rei de Maquedá; o rei de Betel;

[[v6-12-17]]

^<<v6-12-17,17>>^ o rei de Tapua; o rei de Héfer;

[[v6-12-18]]

^<<v6-12-18,18>>^ o rei de Afeca; o rei de Lasarom;

[[v6-12-19]]

^<<v6-12-19,19>>^ o rei de Madom; o rei de Hazor;

[[v6-12-20]]

^<<v6-12-20,20>>^ o rei de Sinrom-Merom; o rei de Acsafe;

[[v6-12-21]]

^<<v6-12-21,21>>^ o rei de Taanaque; o rei de Megido;

[[v6-12-22]]

^<<v6-12-22,22>>^ o rei de Quedes; o rei de Jocneão do Carmelo;

[[v6-12-23]]

^<<v6-12-23,23>>^ o rei de Dor, em Nafate-Dor; o rei de Goim, em Gilgal;

[[v6-12-24]]

^<<v6-12-24,24>>^ e o rei de Tirza. Ao todo, trinta e um reis.

'''

xref:006-josue/006-josue-011.adoc#v6-11-0[&#60; Capítulo Anterior] | <<v6-12-0,Topo>> | xref:006-josue/006-josue-013.adoc#v6-13-0[Próximo Capítulo &#62;]