include::./index.adoc[]

[[v6-9-0]]
=== Josué, 9
// naa ?, NAA - Nova Almeida Atualizada

[[v6-9-1]]

^<<v6-9-1,1>>^ Todos os reis que estavam do lado oeste do Jordão, nas montanhas e nas campinas, em toda a costa do mar Grande até o Líbano ficaram sabendo disso. Eram os reis dos heteus, dos amorreus, dos cananeus, dos ferezeus, dos heveus e dos jebuseus.

[[v6-9-2]]

^<<v6-9-2,2>>^ Então eles se ajuntaram de comum acordo, para guerrear contra Josué e contra Israel.

[[v6-9-3]]

^<<v6-9-3,3>>^ Mas os moradores de Gibeão, ouvindo o que Josué tinha feito com Jericó e com Ai,

[[v6-9-4]]

^<<v6-9-4,4>>^ usaram de astúcia: foram e se fingiram de embaixadores, levando sacos velhos sobre os seus jumentos e odres de vinho, velhos, rasgados e cheios de remendos,

[[v6-9-5]]

^<<v6-9-5,5>>^ calçando sandálias velhas e remendadas e vestindo roupas velhas. E todo o pão que traziam para comer era seco e bolorento.

[[v6-9-6]]

^<<v6-9-6,6>>^ Foram a Josué, no arraial, em Gilgal, e lhe disseram, a ele e aos homens de Israel: — Viemos de uma terra distante e queremos que vocês façam uma aliança conosco.

[[v6-9-7]]

^<<v6-9-7,7>>^ Mas os homens de Israel responderam aos heveus: — Talvez vocês morem aqui perto. Como podemos fazer uma aliança com vocês?

[[v6-9-8]]

^<<v6-9-8,8>>^ Então disseram a Josué: — Somos seus servos. Mas Josué perguntou: — Quem são vocês? De onde vêm?

[[v6-9-9]]

^<<v6-9-9,9>>^ Eles responderam: — Estes seus servos vieram de uma terra muito distante, por causa do nome do Senhor , seu Deus. Pois ouvimos a sua fama e tudo o que fez no Egito,

[[v6-9-10]]

^<<v6-9-10,10>>^ e tudo o que fez com os dois reis dos amorreus que estavam do outro lado do Jordão, a saber, Seom, rei de Hesbom, e Ogue, rei de Basã, que estava em Astarote.

[[v6-9-11]]

^<<v6-9-11,11>>^ Por isso os nossos anciãos e todos os moradores da nossa terra nos disseram: "Levem com vocês alimentos para a viagem e vão ao encontro deles, dizendo: ‘Somos seus servos; façam uma aliança conosco.’

[[v6-9-12]]

^<<v6-9-12,12>>^ Este nosso pão nós pegamos em nossas casas quando ainda estava quente, no dia em que saímos para vir falar com vocês, e agora aqui está ele, já seco e bolorento.

[[v6-9-13]]

^<<v6-9-13,13>>^ Estes odres eram novos quando os enchemos de vinho, mas agora já estão rasgados. E estas nossas roupas e estas nossas sandálias já envelheceram, por causa da longa viagem."

[[v6-9-14]]

^<<v6-9-14,14>>^ Então os israelitas aceitaram os alimentos deles e não pediram conselho ao Senhor .

[[v6-9-15]]

^<<v6-9-15,15>>^ Josué concedeu-lhes paz e fez com eles a aliança de lhes poupar a vida; e os chefes da congregação confirmaram isso com juramento.

[[v6-9-16]]

^<<v6-9-16,16>>^ Ao fim de três dias, depois de terem feito a aliança com eles, souberam que eram seus vizinhos e que moravam perto deles.

[[v6-9-17]]

^<<v6-9-17,17>>^ Pois, partindo os filhos de Israel, chegaram às cidades deles ao terceiro dia. E as cidades deles eram Gibeão, Cefira, Beerote e Quiriate-Jearim.

[[v6-9-18]]

^<<v6-9-18,18>>^ Os filhos de Israel não os atacaram, porque os chefes da congregação lhes haviam jurado pelo Senhor , Deus de Israel. Por isso toda a congregação murmurou contra os chefes.

[[v6-9-19]]

^<<v6-9-19,19>>^ Então todos os chefes disseram a toda a congregação: — Nós juramos a eles pelo Senhor , Deus de Israel; por isso, não podemos tocar neles.

[[v6-9-20]]

^<<v6-9-20,20>>^ Isto, porém, lhes faremos: vamos deixá-los viver, para que não venha grande ira sobre nós, por causa do juramento que lhes fizemos.

[[v6-9-21]]

^<<v6-9-21,21>>^ E os chefes acrescentaram: — Deixem que vivam. E assim eles se tornaram rachadores de lenha e tiradores de água para toda a congregação, como os chefes lhes tinham dito.

[[v6-9-22]]

^<<v6-9-22,22>>^ Josué chamou os gibeonitas e lhes disse: — Por que vocês nos enganaram, dizendo que moravam bem longe de nós, quando na verdade moram aqui perto?

[[v6-9-23]]

^<<v6-9-23,23>>^ Agora vocês estão sob maldição e entre vocês nunca deixará de haver escravos, rachadores de lenha e tiradores de água para a casa do meu Deus.

[[v6-9-24]]

^<<v6-9-24,24>>^ Então eles responderam a Josué: — É que foi anunciado a estes seus servos, como certo, que o Senhor , seu Deus, havia ordenado ao seu servo Moisés que lhes desse toda esta terra e destruísse todos os seus moradores diante de vocês. Tememos muito pela nossa vida por causa de vocês e foi por isso que fizemos aquilo.

[[v6-9-25]]

^<<v6-9-25,25>>^ Eis que estamos nas suas mãos; trate-nos segundo lhe parecer bom e reto.

[[v6-9-26]]

^<<v6-9-26,26>>^ Josué fez como tinha dito e livrou-os das mãos dos filhos de Israel; e não os mataram.

[[v6-9-27]]

^<<v6-9-27,27>>^ Naquele dia, Josué os fez rachadores de lenha e tiradores de água para a congregação e para o altar do Senhor , até o dia de hoje, no lugar que Deus escolhesse.

'''

xref:006-josue/006-josue-008.adoc#v6-8-0[&#60; Capítulo Anterior] | <<v6-9-0,Topo>> | xref:006-josue/006-josue-010.adoc#v6-10-0[Próximo Capítulo &#62;]