include::./index.adoc[]

[[v6-8-0]]
=== Josué, 8
// naa ?, NAA - Nova Almeida Atualizada

[[v6-8-1]]

^<<v6-8-1,1>>^ O Senhor  disse a Josué: — Não tenha medo, nem fique assustado. Leve com você toda a gente de guerra, prepare-se e marche contra a cidade de Ai. Eis que entreguei em suas mãos o rei de Ai, o seu povo, a sua cidade, e a sua terra.

[[v6-8-2]]

^<<v6-8-2,2>>^ Você fará com a cidade de Ai e com o seu rei o que fez com Jericó e com o seu rei, exceto que desta vez vocês poderão saquear os seus despojos e o seu gado. Ponha emboscadas à cidade, por detrás dela.

[[v6-8-3]]

^<<v6-8-3,3>>^ Então Josué se preparou com toda a gente de guerra para marchar contra a cidade de Ai. Josué escolheu trinta mil homens valentes e os enviou de noite.

[[v6-8-4]]

^<<v6-8-4,4>>^ Deu-lhes uma ordem, dizendo: — Ponham-se de emboscada contra a cidade, por detrás dela; não se distanciem muito da cidade; e todos estejam alertas.

[[v6-8-5]]

^<<v6-8-5,5>>^ Eu e todo o povo que está comigo nos aproximaremos da cidade; e, quando eles saírem contra nós, como da primeira vez, fugiremos deles.

[[v6-8-6]]

^<<v6-8-6,6>>^ Vamos deixar que saiam atrás de nós, até que os tiremos da cidade; porque dirão: "Estão fugindo de nós como da primeira vez." Assim, fugiremos deles.

[[v6-8-7]]

^<<v6-8-7,7>>^ Então vocês sairão da emboscada e tomarão a cidade; porque o Senhor , o seu Deus, entregará a cidade nas mãos de vocês.

[[v6-8-8]]

^<<v6-8-8,8>>^ Depois de tomar a cidade, ponham fogo nela. Façam segundo a palavra do Senhor . Vejam bem: é isto que estou ordenando a vocês.

[[v6-8-9]]

^<<v6-8-9,9>>^ Assim, Josué os enviou, e eles se foram à emboscada; e ficaram entre Betel e Ai, a oeste da cidade de Ai. Porém Josué passou aquela noite no meio do povo.

[[v6-8-10]]

^<<v6-8-10,10>>^ Josué se levantou de madrugada, convocou o povo, e marcharam ele e os anciãos de Israel, diante do povo, contra a cidade de Ai.

[[v6-8-11]]

^<<v6-8-11,11>>^ Marcharam também todos os homens de guerra que estavam com ele. Aproximaram-se e chegaram em frente da cidade; e acamparam do lado norte de Ai. Havia um vale entre eles e a cidade de Ai.

[[v6-8-12]]

^<<v6-8-12,12>>^ Josué reuniu uns cinco mil homens e os pôs entre Betel e Ai, em emboscada, a oeste da cidade.

[[v6-8-13]]

^<<v6-8-13,13>>^ Assim foi disposto o povo: todo o acampamento ao norte da cidade e a emboscada a oeste dela. E naquela noite Josué foi até o meio do vale.

[[v6-8-14]]

^<<v6-8-14,14>>^ E aconteceu que, ao ver isso, o rei da cidade de Ai e os homens daquele lugar se apressaram e, levantando-se de madrugada, saíram de encontro a Israel, à batalha, diante das campinas. Porque o rei não sabia que uma emboscada estava armada contra ele atrás da cidade.

[[v6-8-15]]

^<<v6-8-15,15>>^ Josué e todo o Israel fizeram de conta que estavam sendo derrotados por eles e fugiram pelo caminho do deserto.

[[v6-8-16]]

^<<v6-8-16,16>>^ Por isso todo o povo que estava na cidade foi convocado para os perseguir; e perseguiram Josué e foram afastados da cidade.

[[v6-8-17]]

^<<v6-8-17,17>>^ Nem um só homem ficou em Ai, nem em Betel; todos saíram atrás dos israelitas. Deixaram a cidade aberta e perseguiram Israel.

[[v6-8-18]]

^<<v6-8-18,18>>^ Então o Senhor  disse a Josué: — Estenda na direção da cidade de Ai a lança que você tem na mão, porque entregarei a cidade nas suas mãos. E Josué estendeu a sua lança na direção da cidade.

[[v6-8-19]]

^<<v6-8-19,19>>^ Então a emboscada se levantou apressadamente do seu lugar, e, ao estender ele a mão, vieram à cidade e a tomaram; e apressaram-se e puseram fogo nela.

[[v6-8-20]]

^<<v6-8-20,20>>^ Quando os homens da cidade de Ai se viraram para trás, olharam, e eis que a fumaça da cidade subia ao céu, e não puderam fugir nem para um lado nem para outro; porque o povo que fugia para o deserto se voltou contra os que os perseguiam.

[[v6-8-21]]

^<<v6-8-21,21>>^ Quando Josué e todo o Israel viram que a emboscada havia tomado a cidade e que a fumaça da cidade subia, voltaram e atacaram os homens de Ai.

[[v6-8-22]]

^<<v6-8-22,22>>^ Da cidade saíram os outros ao encontro do inimigo, que, assim, ficou no meio de Israel, uns de uma parte, outros de outra. E os atacaram de tal maneira, que nenhum deles sobreviveu, nem escapou.

[[v6-8-23]]

^<<v6-8-23,23>>^ Porém o rei da cidade de Ai foi capturado com vida e levado a Josué.

[[v6-8-24]]

^<<v6-8-24,24>>^ Quando os israelitas acabaram de matar todos os moradores da cidade de Ai no campo e no deserto onde os tinham perseguido, e todos tinham caído a fio de espada e já estavam mortos, todo o Israel voltou à cidade de Ai, e a passaram a fio de espada.

[[v6-8-25]]

^<<v6-8-25,25>>^ Os que morreram naquele dia, tanto homens como mulheres, foram doze mil, todos os moradores da cidade de Ai.

[[v6-8-26]]

^<<v6-8-26,26>>^ Porque Josué não retirou a mão que havia estendido com a lança até haver destruído totalmente os moradores da cidade.

[[v6-8-27]]

^<<v6-8-27,27>>^ Os israelitas saquearam para si o gado e os despojos daquela cidade, segundo a palavra do Senhor , que havia ordenado a Josué.

[[v6-8-28]]

^<<v6-8-28,28>>^ Então Josué pôs fogo na cidade de Ai e a reduziu, para sempre, a um montão, a ruínas até o dia de hoje.

[[v6-8-29]]

^<<v6-8-29,29>>^ Enforcou o rei da cidade de Ai numa árvore e o deixou ali até a tarde; ao pôr do sol, por ordem de Josué, tiraram o cadáver da árvore e o jogaram na entrada do portão da cidade. E sobre ele levantaram um montão de pedras, que permanece até o dia de hoje.

[[v6-8-30]]

^<<v6-8-30,30>>^ Então Josué edificou um altar ao Senhor , Deus de Israel, no monte Ebal,

[[v6-8-31]]

^<<v6-8-31,31>>^ como Moisés, servo do Senhor , havia ordenado aos filhos de Israel, segundo o que está escrito no Livro da Lei de Moisés, a saber, um altar de pedras toscas, que não tinham sido trabalhadas com instrumentos de ferro. Sobre esse altar ofereceram holocaustos ao Senhor  e apresentaram ofertas pacíficas.

[[v6-8-32]]

^<<v6-8-32,32>>^ Ali Josué escreveu, em pedras, uma cópia da lei de Moisés, que este já havia escrito diante dos filhos de Israel.

[[v6-8-33]]

^<<v6-8-33,33>>^ Todo o Israel, tanto estrangeiros como naturais, com os seus anciãos, os seus chefes e os seus juízes estavam de um e de outro lado da arca, diante dos sacerdotes levitas que levavam a arca da aliança do Senhor . Metade deles se postou em frente do monte Gerizim, e a outra metade, em frente do monte Ebal, como Moisés, servo do Senhor , havia ordenado anteriormente, para que o povo de Israel fosse abençoado.

[[v6-8-34]]

^<<v6-8-34,34>>^ Depois, Josué leu todas as palavras da lei, a bênção e a maldição, segundo tudo o que está escrito no Livro da Lei.

[[v6-8-35]]

^<<v6-8-35,35>>^ Não houve uma só palavra, de tudo o que Moisés havia ordenado, que Josué não lesse para toda a congregação de Israel, e para as mulheres, as crianças e os estrangeiros que viviam no meio deles.

'''

xref:006-josue/006-josue-007.adoc#v6-7-0[&#60; Capítulo Anterior] | <<v6-8-0,Topo>> | xref:006-josue/006-josue-009.adoc#v6-9-0[Próximo Capítulo &#62;]