include::./index.adoc[]

[[v6-22-0]]
=== Josué, 22
// naa ?, NAA - Nova Almeida Atualizada

[[v6-22-1]]

^<<v6-22-1,1>>^ Então Josué chamou os rubenitas, os gaditas e a meia tribo de Manassés

[[v6-22-2]]

^<<v6-22-2,2>>^ e lhes disse: — Vocês fizeram tudo o que Moisés, servo do Senhor , lhes ordenou e também foram obedientes a mim em tudo o que lhes ordenei.

[[v6-22-3]]

^<<v6-22-3,3>>^ Durante todo esse tempo, até o dia de hoje, vocês não abandonaram os seus irmãos; pelo contrário, tiveram o cuidado de guardar o mandamento do Senhor , seu Deus.

[[v6-22-4]]

^<<v6-22-4,4>>^ Agora o Senhor , seu Deus, já concedeu repouso aos irmãos de vocês, como lhes havia prometido. Voltem, pois, agora, e vão para as suas tendas, à terra que lhes pertence, que Moisés, servo do Senhor , deu a vocês do outro lado do Jordão.

[[v6-22-5]]

^<<v6-22-5,5>>^ Mas tenham o maior cuidado em guardar o mandamento e a lei que Moisés, servo do Senhor , lhes ordenou: que vocês amem o Senhor , seu Deus, andem em todos os seus caminhos, guardem os seus mandamentos, sejam fiéis a ele e o sirvam de todo o coração e de toda a alma.

[[v6-22-6]]

^<<v6-22-6,6>>^ Assim, Josué os abençoou e os despediu. E eles foram para as suas tendas.

[[v6-22-7]]

^<<v6-22-7,7>>^ Ora, Moisés tinha dado herança em Basã à meia tribo de Manassés; porém à outra metade da tribo Josué deu herança entre os seus irmãos, deste lado do Jordão, para o oeste. E Josué, ao despedi-los para as suas tendas, os abençoou

[[v6-22-8]]

^<<v6-22-8,8>>^ e lhes disse: — Voltem para as suas tendas com grandes riquezas, com muito gado, prata, ouro, bronze, ferro e muitas roupas. Repartam com os seus irmãos o despojo que tomaram dos inimigos.

[[v6-22-9]]

^<<v6-22-9,9>>^ Assim, os filhos de Rúben, os filhos de Gade e a meia tribo de Manassés voltaram e se retiraram dos filhos de Israel em Siló, que está na terra de Canaã, para irem à terra de Gileade, à terra da sua propriedade, de que foram feitos possuidores, segundo o mandado do Senhor , por meio de Moisés.

[[v6-22-10]]

^<<v6-22-10,10>>^ Quando chegaram à região próxima ao Jordão, na terra de Canaã, os filhos de Rúben, os filhos de Gade e a meia tribo de Manassés edificaram um altar junto ao Jordão, altar grande e vistoso.

[[v6-22-11]]

^<<v6-22-11,11>>^ Os filhos de Israel ouviram dizer: — Eis que os filhos de Rúben, os filhos de Gade e a meia tribo de Manassés edificaram um altar diante da terra de Canaã, perto do Jordão, do lado dos filhos de Israel.

[[v6-22-12]]

^<<v6-22-12,12>>^ Quando os filhos de Israel ouviram isso, toda a congregação dos filhos de Israel se reuniu em Siló, para fazer guerra contra eles.

[[v6-22-13]]

^<<v6-22-13,13>>^ E os filhos de Israel enviaram Fineias, filho do sacerdote Eleazar, aos filhos de Rúben, aos filhos de Gade e à meia tribo de Manassés.

[[v6-22-14]]

^<<v6-22-14,14>>^ Com ele foram dez chefes, um de cada tribo de Israel, sendo cada um deles chefe da casa de seus pais entre os grupos de milhares de Israel.

[[v6-22-15]]

^<<v6-22-15,15>>^ Eles se dirigiram à terra de Gileade, onde estavam os filhos de Rúben, os filhos de Gade e a meia tribo de Manassés, e lhes falaram, dizendo:

[[v6-22-16]]

^<<v6-22-16,16>>^ — Assim diz toda a congregação do Senhor : Que infidelidade é esta que vocês cometeram contra o Deus de Israel, deixando hoje de seguir o Senhor , edificando um altar para vocês, para se rebelarem contra o Senhor ?

[[v6-22-17]]

^<<v6-22-17,17>>^ Será que não nos bastou a iniquidade de Peor, de que até hoje ainda não nos purificamos, apesar de ter vindo uma praga sobre a congregação do Senhor ,

[[v6-22-18]]

^<<v6-22-18,18>>^ para que hoje vocês deixem de seguir o Senhor ? Se hoje vocês se rebelam contra o Senhor , amanhã ele ficará irado com toda a congregação de Israel.

[[v6-22-19]]

^<<v6-22-19,19>>^ Se a terra que vocês receberam por herança é imunda, passem para a terra que pertence ao Senhor , onde está o tabernáculo do Senhor , e tomem posse entre nós. Porém não se rebelem contra o Senhor , nem se rebelem contra nós, edificando para vocês um altar que não é o altar do Senhor , nosso Deus.

[[v6-22-20]]

^<<v6-22-20,20>>^ Não cometeu Acã, filho de Zera, infidelidade no que diz respeito às coisas condenadas? E não veio ira sobre toda a congregação de Israel? Pois aquele homem não morreu sozinho na sua iniquidade.

[[v6-22-21]]

^<<v6-22-21,21>>^ Então os filhos de Rúben, os filhos de Gade e a meia tribo de Manassés responderam aos cabeças dos grupos de milhares de Israel:

[[v6-22-22]]

^<<v6-22-22,22>>^ — O Poderoso, Deus, o Senhor ! O Poderoso, Deus, o Senhor , ele sabe, e Israel mesmo o saberá. Se foi em rebeldia ou por infidelidade contra o Senhor  que fizemos isso, não nos poupem a vida no dia de hoje.

[[v6-22-23]]

^<<v6-22-23,23>>^ Se edificamos um altar para deixarmos de seguir o Senhor , ou para, sobre ele, oferecermos holocausto e oferta de cereais, ou, sobre ele, fazermos oferta pacífica, que o Senhor  mesmo nos responsabilize por isso.

[[v6-22-24]]

^<<v6-22-24,24>>^ Pelo contrário, fizemos isso por causa da seguinte preocupação: amanhã talvez os filhos de vocês dirão aos nossos filhos: "O que é que vocês têm a ver com o Senhor , o Deus de Israel?

[[v6-22-25]]

^<<v6-22-25,25>>^ Porque o Senhor  pôs o Jordão por limite entre nós e vocês, ó filhos de Rúben e filhos de Gade. Vocês não têm nada a ver com o Senhor !" E, assim, bem poderiam os filhos de vocês afastar os nossos filhos do temor do Senhor .

[[v6-22-26]]

^<<v6-22-26,26>>^ Por isso dissemos: "Vamos edificar um altar, não para holocausto, nem para sacrifício,

[[v6-22-27]]

^<<v6-22-27,27>>^ mas para que entre nós e vocês e entre as nossas gerações depois de nós nos sirva de testemunho, e possamos servir o Senhor  na presença dele com os nossos holocaustos, os nossos sacrifícios e as nossas ofertas pacíficas." E também para que, no futuro, os filhos de vocês não digam aos nossos filhos: "Vocês não têm nada a ver com o Senhor ."

[[v6-22-28]]

^<<v6-22-28,28>>^ Por isso dissemos: Se, no futuro, disserem algo assim a nós ou aos nossos descendentes, responderemos: "Vejam o modelo do altar do Senhor  que os nossos pais fizeram, não para holocausto, nem para sacrifício, mas para testemunho entre nós e vocês."

[[v6-22-29]]

^<<v6-22-29,29>>^ Longe de nós a intenção de nos rebelarmos contra o Senhor  e deixarmos hoje de seguir o Senhor , edificando um altar para holocausto, oferta de cereais ou sacrifício, altar que não é o altar do Senhor , nosso Deus, que está diante do seu tabernáculo.

[[v6-22-30]]

^<<v6-22-30,30>>^ Quando o sacerdote Fineias, os chefes da congregação e os cabeças dos grupos de milhares de Israel que estavam com ele ouviram as palavras que disseram os filhos de Rúben, os filhos de Gade e os filhos de Manassés, deram-se por satisfeitos.

[[v6-22-31]]

^<<v6-22-31,31>>^ E Fineias, filho do sacerdote Eleazar, disse aos filhos de Rúben, aos filhos de Gade e aos filhos de Manassés: — Hoje sabemos que o Senhor  está no meio de nós, porque vocês não cometeram infidelidade contra o Senhor . Assim vocês livraram os filhos de Israel da mão do Senhor .

[[v6-22-32]]

^<<v6-22-32,32>>^ Fineias, filho do sacerdote Eleazar, e os chefes, deixando os filhos de Rúben e os filhos de Gade, voltaram da terra de Gileade para a terra de Canaã, aos filhos de Israel, e lhes deram relatório de tudo.

[[v6-22-33]]

^<<v6-22-33,33>>^ Com esta resposta os filhos de Israel se deram por satisfeitos e bendisseram a Deus. E não falaram mais de ir e fazer guerra contra eles, para destruírem a terra em que habitavam os filhos de Rúben e os filhos de Gade.

[[v6-22-34]]

^<<v6-22-34,34>>^ Os filhos de Rúben e os filhos de Gade chamaram o altar de "Testemunho", porque disseram: "É um testemunho entre nós de que o Senhor  é Deus."

'''

xref:006-josue/006-josue-021.adoc#v6-21-0[&#60; Capítulo Anterior] | <<v6-22-0,Topo>> | xref:006-josue/006-josue-023.adoc#v6-23-0[Próximo Capítulo &#62;]