include::./index.adoc[]

[[v6-19-0]]
=== Josué, 19
// naa ?, NAA - Nova Almeida Atualizada

[[v6-19-1]]

^<<v6-19-1,1>>^ Saiu a segunda sorte a Simeão, à tribo dos filhos de Simeão, segundo as suas famílias, e a herança deles ficava no meio da herança dos filhos de Judá.

[[v6-19-2]]

^<<v6-19-2,2>>^ Na herança receberam Berseba, Seba, Molada,

[[v6-19-3]]

^<<v6-19-3,3>>^ Hazar-Sual, Balá, Ezém,

[[v6-19-4]]

^<<v6-19-4,4>>^ Eltolade, Betul, Horma,

[[v6-19-5]]

^<<v6-19-5,5>>^ Ziclague, Bete-Marcabote, Hazar-Susa,

[[v6-19-6]]

^<<v6-19-6,6>>^ Bete-Lebaote e Saruém. Ao todo, treze cidades com as suas aldeias.

[[v6-19-7]]

^<<v6-19-7,7>>^ Aim, Rimom, Eter e Asã; ao todo, quatro cidades com as suas aldeias.

[[v6-19-8]]

^<<v6-19-8,8>>^ E todas as aldeias que havia ao redor destas cidades, até Baalate-Ber, que é Ramá do Neguebe. Esta era a herança da tribo dos filhos de Simeão, segundo as suas famílias.

[[v6-19-9]]

^<<v6-19-9,9>>^ A herança dos filhos de Simeão foi tirada da porção dos filhos de Judá, pois a herança destes era demasiadamente grande para eles. Por isso os filhos de Simeão receberam a sua herança no meio dos filhos de Judá.

[[v6-19-10]]

^<<v6-19-10,10>>^ Saiu a terceira sorte aos filhos de Zebulom, segundo as suas famílias. O limite da sua herança ia até Saride.

[[v6-19-11]]

^<<v6-19-11,11>>^ O seu limite subia, pelo oeste, a Marala, tocava em Dabesete e chegava até o ribeiro que está diante de Jocneão.

[[v6-19-12]]

^<<v6-19-12,12>>^ De Saride, voltava para o leste, para o nascente do sol, até o limite de Quislote-Tabor, saía a Daberate, e ia subindo a Jafia;

[[v6-19-13]]

^<<v6-19-13,13>>^ dali, passava, para o nascente, a Gate-Hefer, a Ete-Cazim, ia a Rimom, que se estendia até Neá,

[[v6-19-14]]

^<<v6-19-14,14>>^ e, rodeando-a, o limite passava, para o norte, a Hanatom e terminava no vale de Ifta-El.

[[v6-19-15]]

^<<v6-19-15,15>>^ Ainda Catate, Naalal, Sinrom, Idala e Belém, completando doze cidades com as suas aldeias.

[[v6-19-16]]

^<<v6-19-16,16>>^ Esta era a herança dos filhos de Zebulom, segundo as suas famílias; estas cidades com as suas aldeias.

[[v6-19-17]]

^<<v6-19-17,17>>^ A quarta sorte saiu a Issacar, aos filhos de Issacar, segundo as suas famílias.

[[v6-19-18]]

^<<v6-19-18,18>>^ O seu território incluía Jezreel, Quesulote, Suném,

[[v6-19-19]]

^<<v6-19-19,19>>^ Hafaraim, Siom, Anacarate,

[[v6-19-20]]

^<<v6-19-20,20>>^ Rabite, Quisião, Ebes,

[[v6-19-21]]

^<<v6-19-21,21>>^ Remete, En-Ganim, En-Hada e Bete-Pasês.

[[v6-19-22]]

^<<v6-19-22,22>>^ O limite tocava o Tabor, Saazima e Bete-Semes e terminava no Jordão. Ao todo, dezesseis cidades com as suas aldeias.

[[v6-19-23]]

^<<v6-19-23,23>>^ Esta era a herança da tribo dos filhos de Issacar, segundo as suas famílias; estas cidades com as suas aldeias.

[[v6-19-24]]

^<<v6-19-24,24>>^ Saiu a quinta sorte à tribo dos filhos de Aser, segundo as suas famílias.

[[v6-19-25]]

^<<v6-19-25,25>>^ O seu território incluía Helcate, Hali, Béten, Acsafe,

[[v6-19-26]]

^<<v6-19-26,26>>^ Alameleque, Amade e Misal; e tocava o Carmelo, para o oeste, e Sior-Libnate;

[[v6-19-27]]

^<<v6-19-27,27>>^ voltava para o nascente do sol, Bete-Dagom, e tocava Zebulom e o vale de Ifta-El, ao norte de Bete-Emeque e de Neiel, e vinha sair a Cabul, pela esquerda,

[[v6-19-28]]

^<<v6-19-28,28>>^ Ebrom, Reobe, Hamom e Caná, até a grande Sidom.

[[v6-19-29]]

^<<v6-19-29,29>>^ O limite voltava a Ramá e até a cidade fortificada de Tiro; então tornava a Hosa, para terminar no mar, na região de Aczibe;

[[v6-19-30]]

^<<v6-19-30,30>>^ também Umá, Afeca e Reobe, completando vinte e duas cidades com as suas aldeias.

[[v6-19-31]]

^<<v6-19-31,31>>^ Esta era a herança da tribo dos filhos de Aser, segundo as suas famílias; estas cidades com as suas aldeias.

[[v6-19-32]]

^<<v6-19-32,32>>^ Saiu a sexta sorte aos filhos de Naftali, segundo as suas famílias.

[[v6-19-33]]

^<<v6-19-33,33>>^ O seu limite ia desde Helefe, do carvalho em Zaananim, Adami-Nequebe, Jabneel, até Lacum e terminava no Jordão.

[[v6-19-34]]

^<<v6-19-34,34>>^ O limite voltava, pelo oeste, a Aznote-Tabor, de onde passava a Hucoque; tocava Zebulom, ao sul, e Aser, a oeste, e Judá, pelo Jordão, ao nascente do sol.

[[v6-19-35]]

^<<v6-19-35,35>>^ As cidades fortificadas eram Zidim, Zer, Hamate, Racate, Quinerete,

[[v6-19-36]]

^<<v6-19-36,36>>^ Adamá, Ramá, Hazor,

[[v6-19-37]]

^<<v6-19-37,37>>^ Quedes, Edrei, En-Hazor,

[[v6-19-38]]

^<<v6-19-38,38>>^ Irom, Migdal-El, Horém, Bete-Anate e Bete-Semes. Ao todo, dezenove cidades com as suas aldeias.

[[v6-19-39]]

^<<v6-19-39,39>>^ Esta era a herança da tribo dos filhos de Naftali, segundo as suas famílias; estas cidades com as suas aldeias.

[[v6-19-40]]

^<<v6-19-40,40>>^ A sétima sorte saiu à tribo dos filhos de Dã, segundo as suas famílias.

[[v6-19-41]]

^<<v6-19-41,41>>^ O território da sua herança incluía Zorá, Estaol, Ir-Semes,

[[v6-19-42]]

^<<v6-19-42,42>>^ Saalabim, Aijalom, Itla,

[[v6-19-43]]

^<<v6-19-43,43>>^ Elom, Timna, Ecrom,

[[v6-19-44]]

^<<v6-19-44,44>>^ Elteque, Gibetom, Baalate,

[[v6-19-45]]

^<<v6-19-45,45>>^ Jeúde, Benê-Beraque, Gate-Rimom,

[[v6-19-46]]

^<<v6-19-46,46>>^ Me-Jarcom e Racom, com o território diante de Jope.

[[v6-19-47]]

^<<v6-19-47,47>>^ Mas o território dos filhos de Dã era pequeno demais para eles. Por isso os filhos de Dã foram e atacaram Lesém, e a tomaram, matando os moradores a fio de espada. E tomando posse da cidade, foram morar nela e lhe chamaram Dã, segundo o nome de Dã, seu pai.

[[v6-19-48]]

^<<v6-19-48,48>>^ Esta era a herança da tribo dos filhos de Dã, segundo as suas famílias; estas cidades com as suas aldeias.

[[v6-19-49]]

^<<v6-19-49,49>>^ Quando acabaram de repartir a terra em herança, segundo os seus territórios, os filhos de Israel deram a Josué, filho de Num, uma herança no meio deles.

[[v6-19-50]]

^<<v6-19-50,50>>^ Segundo o mandado do Senhor , deram-lhe a cidade que ele havia pedido, Timnate-Sera, na região montanhosa de Efraim. Josué reedificou a cidade e morou nela.

[[v6-19-51]]

^<<v6-19-51,51>>^ Estas foram as heranças que Eleazar, o sacerdote, e Josué, filho de Num, e os chefes das famílias repartiram por sorteio, em herança, pelas tribos dos filhos de Israel, em Siló, diante do Senhor , à porta da tenda do encontro. E assim acabaram de repartir a terra.

'''

xref:006-josue/006-josue-018.adoc#v6-18-0[&#60; Capítulo Anterior] | <<v6-19-0,Topo>> | xref:006-josue/006-josue-020.adoc#v6-20-0[Próximo Capítulo &#62;]