include::./index.adoc[]

[[v6-18-0]]
=== Josué, 18
// naa ?, NAA - Nova Almeida Atualizada

[[v6-18-1]]

^<<v6-18-1,1>>^ Toda a congregação dos filhos de Israel se reuniu em Siló, e ali armaram a tenda do encontro. E a terra estava sujeita diante deles.

[[v6-18-2]]

^<<v6-18-2,2>>^ Sete tribos dos filhos de Israel ainda não tinham recebido a sua herança.

[[v6-18-3]]

^<<v6-18-3,3>>^ Então Josué disse aos filhos de Israel: — Até quando vocês terão preguiça de entrar e tomar posse da terra que o Senhor , o Deus de seus pais, deu a vocês?

[[v6-18-4]]

^<<v6-18-4,4>>^ Escolham três homens de cada tribo, para que eu os envie, eles se disponham, percorram a terra, façam uma descrição por escrito segundo a herança das tribos e depois voltem para junto de mim.

[[v6-18-5]]

^<<v6-18-5,5>>^ Dividirão a terra em sete partes: Judá ficará no seu território, ao sul, e a casa de José ficará no seu território, ao norte.

[[v6-18-6]]

^<<v6-18-6,6>>^ Descrevam a terra em sete partes e me tragam essa descrição, para que aqui diante do Senhor , nosso Deus, eu lhes faça o sorteio.

[[v6-18-7]]

^<<v6-18-7,7>>^ Porque os levitas não têm parte entre vocês, pois a parte deles é o sacerdócio do Senhor . Gade, Rúben e a meia tribo de Manassés já haviam recebido a sua herança do outro lado do Jordão, na direção do leste, a qual lhes foi dada por Moisés, servo do Senhor .

[[v6-18-8]]

^<<v6-18-8,8>>^ Então aqueles homens se levantaram e se foram. E Josué deu a seguinte ordem aos que iam fazer a descrição da terra: — Vão, percorram a terra, façam uma descrição dela e voltem para mim. Aqui em Siló, diante do Senhor , farei o sorteio para vocês.

[[v6-18-9]]

^<<v6-18-9,9>>^ Assim os homens foram, percorreram a terra, fizeram dela uma descrição num livro, cidade por cidade, em sete partes, e voltaram a Josué, ao arraial em Siló.

[[v6-18-10]]

^<<v6-18-10,10>>^ Então Josué lhes lançou as sortes em Siló, diante do Senhor . E ali Josué repartiu a terra, segundo as suas divisões, aos filhos de Israel.

[[v6-18-11]]

^<<v6-18-11,11>>^ Saiu a sorte da tribo dos filhos de Benjamim, segundo as suas famílias; e o território sorteado ficava entre os filhos de Judá e os filhos de José.

[[v6-18-12]]

^<<v6-18-12,12>>^ O seu limite foi para o lado norte desde o Jordão; subia ao lado de Jericó, para o norte, e subia pela região montanhosa, para o oeste, para terminar no deserto de Bete-Áven.

[[v6-18-13]]

^<<v6-18-13,13>>^ E dali o limite passava a Luz, ao lado de Luz, que é Betel, para o sul; descia a Atarote-Adar, ao pé do monte que está do lado sul de Bete-Horom-de-Baixo.

[[v6-18-14]]

^<<v6-18-14,14>>^ O limite seguia e voltava ao lado oeste, para o sul do monte que está diante de Bete-Horom, para o sul, e terminava em Quiriate-Baal, que é Quiriate-Jearim, cidade dos filhos de Judá; este era o lado oeste.

[[v6-18-15]]

^<<v6-18-15,15>>^ O lado do sul começava na extremidade leste de Quiriate-Jearim e seguia até a fonte das águas de Neftoa;

[[v6-18-16]]

^<<v6-18-16,16>>^ o limite descia até a extremidade do monte que está diante do vale de Ben-Hinom, ao norte do vale dos Refains, e descia pelo vale de Hinom do lado dos jebuseus, para o sul; e baixava a En-Rogel;

[[v6-18-17]]

^<<v6-18-17,17>>^ volvia-se para o norte, chegava a En-Semes, de onde passava para Gelilote, que está diante da subida de Adumim, e descia à pedra de Boã, filho de Rúben;

[[v6-18-18]]

^<<v6-18-18,18>>^ passava pela vertente norte, diante da planície, e descia à planície.

[[v6-18-19]]

^<<v6-18-19,19>>^ Depois, o limite passava até o lado de Bete-Hogla, para o norte, para terminar na baía do mar Salgado, na desembocadura do Jordão, ao sul; este era o limite do sul.

[[v6-18-20]]

^<<v6-18-20,20>>^ Do lado leste, o Jordão era o seu limite. Esta era a herança dos filhos de Benjamim nos seus limites ao redor, segundo as suas famílias.

[[v6-18-21]]

^<<v6-18-21,21>>^ As cidades da tribo dos filhos de Benjamim, segundo as suas famílias, eram Jericó, Bete-Hogla, Emeque-Quesis,

[[v6-18-22]]

^<<v6-18-22,22>>^ Bete-Arabá, Zemaraim, Betel,

[[v6-18-23]]

^<<v6-18-23,23>>^ Avim, Pará, Ofra,

[[v6-18-24]]

^<<v6-18-24,24>>^ Quefar-Amonai, Ofni e Gaba. Ao todo, doze cidades com as suas aldeias.

[[v6-18-25]]

^<<v6-18-25,25>>^ Gibeão, Ramá, Beerote,

[[v6-18-26]]

^<<v6-18-26,26>>^ Mispa, Cefira, Mosa,

[[v6-18-27]]

^<<v6-18-27,27>>^ Requém, Irpeel, Tarala,

[[v6-18-28]]

^<<v6-18-28,28>>^ Zela, Elefe, Jebus, que é Jerusalém, Gibeá e Quiriate. Ao todo, catorze cidades com as suas aldeias. Esta era a herança dos filhos de Benjamim, segundo as suas famílias.

'''

xref:006-josue/006-josue-017.adoc#v6-17-0[&#60; Capítulo Anterior] | <<v6-18-0,Topo>> | xref:006-josue/006-josue-019.adoc#v6-19-0[Próximo Capítulo &#62;]