include::./index.adoc[]

[[v6-17-0]]
=== Josué, 17
// naa ?, NAA - Nova Almeida Atualizada

[[v6-17-1]]

^<<v6-17-1,1>>^ Também caiu a sorte à tribo de Manassés, que era o primogênito de José. Maquir, o primogênito de Manassés, pai de Gileade, porque era homem de guerra, recebeu Gileade e Basã.

[[v6-17-2]]

^<<v6-17-2,2>>^ Os outros filhos de Manassés também receberam a sua parte, segundo as suas famílias, a saber, os filhos de Abiezer, os filhos de Heleque, os filhos de Asriel, os filhos de Siquém, os filhos de Héfer, os filhos de Semida. Estes são os filhos de Manassés, filho de José, segundo as suas famílias.

[[v6-17-3]]

^<<v6-17-3,3>>^ Porém Zelofeade, filho de Héfer, filho de Gileade, filho de Maquir, filho de Manassés, não teve filhos, mas só filhas, que se chamavam Macla, Noa, Hogla, Milca e Tirza.

[[v6-17-4]]

^<<v6-17-4,4>>^ Estas chegaram diante de Eleazar, o sacerdote, e diante de Josué, filho de Num, e diante dos chefes, dizendo: — O Senhor  ordenou a Moisés que nos fosse dada uma herança no meio de nossos parentes. Assim, segundo a ordem do Senhor , Josué lhes deu herança no meio dos parentes de seu pai.

[[v6-17-5]]

^<<v6-17-5,5>>^ Couberam a Manassés dez quinhões, além da terra de Gileade e Basã, que está do outro lado do Jordão;

[[v6-17-6]]

^<<v6-17-6,6>>^ porque tanto as filhas de Manassés como os filhos dele receberam herança. Os outros filhos de Manassés receberam a terra de Gileade.

[[v6-17-7]]

^<<v6-17-7,7>>^ O limite de Manassés foi desde Aser até Micmetate, que está a leste de Siquém; e este limite vai, na direção do sul, até os moradores de En-Tapua.

[[v6-17-8]]

^<<v6-17-8,8>>^ A terra de Tapua pertencia a Manassés, mas Tapua, ainda que situada no limite de Manassés, era dos filhos de Efraim.

[[v6-17-9]]

^<<v6-17-9,9>>^ Então o limite desce ao ribeiro de Caná. As cidades, entre as de Manassés, ao sul do ribeiro, pertenciam a Efraim; então o limite de Manassés vai ao norte do ribeiro, terminando no mar.

[[v6-17-10]]

^<<v6-17-10,10>>^ Efraim, ao sul, Manassés, ao norte, e o mar é seu limite; pelo norte, tocam em Aser e, pelo leste, em Issacar.

[[v6-17-11]]

^<<v6-17-11,11>>^ Porque, nos territórios de Issacar e Aser, Manassés tinha Bete-Seã e as suas vilas, Ibleão e as suas vilas, os habitantes de Dor e as suas vilas, os habitantes de En-Dor e as suas vilas, os habitantes de Taanaque e as suas vilas e os habitantes de Megido e as suas vilas, a região das três colinas.

[[v6-17-12]]

^<<v6-17-12,12>>^ E os filhos de Manassés não puderam expulsar os moradores daquelas cidades, porque os cananeus persistiam em morar nessa terra.

[[v6-17-13]]

^<<v6-17-13,13>>^ Quando os filhos de Israel se tornaram fortes, sujeitaram os cananeus a trabalhos forçados, porém não os expulsaram totalmente.

[[v6-17-14]]

^<<v6-17-14,14>>^ Então o povo dos filhos de José disse a Josué: — Por que você nos deu por herança apenas uma sorte e uma porção, sendo nós um povo numeroso, visto que o Senhor  até aqui nos tem abençoado?

[[v6-17-15]]

^<<v6-17-15,15>>^ Josué respondeu: — Se vocês são um povo numeroso, subam à floresta e abram ali uma clareira na terra dos ferezeus e dos refains, visto que a região montanhosa de Efraim é estreita demais para vocês.

[[v6-17-16]]

^<<v6-17-16,16>>^ Então os filhos de José disseram: — A região montanhosa não nos basta. E todos os cananeus que vivem na planície têm carros de ferro, tanto os que estão em Bete-Seã e nas suas vilas como os que estão no vale de Jezreel.

[[v6-17-17]]

^<<v6-17-17,17>>^ Então Josué disse à casa de José, a Efraim e a Manassés: — Vocês são um povo numeroso e forte. Vocês não terão só uma parte,

[[v6-17-18]]

^<<v6-17-18,18>>^ mas a região montanhosa será de vocês. Ainda que seja uma floresta, vocês poderão cortá-la, e até as suas extremidades será toda de vocês. Porque vocês expulsarão os cananeus, embora eles tenham carros de ferro e sejam fortes.

'''

xref:006-josue/006-josue-016.adoc#v6-16-0[&#60; Capítulo Anterior] | <<v6-17-0,Topo>> | xref:006-josue/006-josue-018.adoc#v6-18-0[Próximo Capítulo &#62;]