include::./index.adoc[]

[[v6-2-0]]
=== Josué, 2
// naa ?, NAA - Nova Almeida Atualizada

[[v6-2-1]]

^<<v6-2-1,1>>^ Da localidade de Sitim, Josué, filho de Num, enviou secretamente dois espias, dizendo: — Vão e observem a terra e a cidade de Jericó. Eles foram e entraram na casa de uma mulher prostituta, cujo nome era Raabe, e pousaram ali.

[[v6-2-2]]

^<<v6-2-2,2>>^ Então a seguinte notícia chegou aos ouvidos do rei de Jericó: — Eis que, esta noite, vieram aqui uns homens dos filhos de Israel para espiar a terra.

[[v6-2-3]]

^<<v6-2-3,3>>^ Por isso, o rei de Jericó mandou dizer a Raabe: — Traga para fora esses homens que vieram a você e que estão aí em sua casa, porque vieram espiar toda a terra.

[[v6-2-4]]

^<<v6-2-4,4>>^ Mas a mulher, que havia escondido os dois homens, respondeu: — É verdade que os homens vieram a mim, mas eu não sabia de onde eram.

[[v6-2-5]]

^<<v6-2-5,5>>^ Quando o portão da cidade ia ser fechado, sendo já escuro, eles saíram. Não sei para onde foram. Se forem depressa atrás deles, ainda os alcançarão.

[[v6-2-6]]

^<<v6-2-6,6>>^ Ela, porém, os tinha levado para o terraço da casa e os havia escondido entre as canas de linho que havia colocado em ordem no terraço.

[[v6-2-7]]

^<<v6-2-7,7>>^ Aqueles homens foram atrás dos espias pelo caminho que leva aos vaus do Jordão. E, depois que eles saíram, fechou-se o portão da cidade.

[[v6-2-8]]

^<<v6-2-8,8>>^ Antes que os espias se deitassem, Raabe foi aonde eles estavam, no terraço,

[[v6-2-9]]

^<<v6-2-9,9>>^ e lhes disse: — Bem sei que o Senhor  deu esta terra a vocês, e que o pavor que vocês estão causando caiu sobre nós, e que todos os moradores da terra estão se derretendo de medo.

[[v6-2-10]]

^<<v6-2-10,10>>^ Porque ouvimos que o Senhor  secou as águas do mar Vermelho diante de vocês, quando saíram do Egito. Também ouvimos o que vocês fizeram com os dois reis dos amorreus, Seom e Ogue, que estavam do outro lado do Jordão, os quais vocês destruíram.

[[v6-2-11]]

^<<v6-2-11,11>>^ Quando ouvimos isso, o nosso coração se derreteu, todos ficamos desanimados, por causa da presença de vocês. Porque o Senhor , o Deus de vocês, é Deus em cima nos céus e embaixo na terra.

[[v6-2-12]]

^<<v6-2-12,12>>^ E agora jurem pelo Senhor  que, assim como usei de misericórdia para com vocês, vocês também usarão de misericórdia para com a casa de meu pai e que me darão um sinal certo

[[v6-2-13]]

^<<v6-2-13,13>>^ de que conservarão a vida de meu pai e de minha mãe, dos meus irmãos e das minhas irmãs, com tudo o que eles têm, e de que livrarão a nossa vida da morte.

[[v6-2-14]]

^<<v6-2-14,14>>^ Então os homens lhe disseram: — A nossa vida responderá pela de vocês, se vocês não denunciarem esta nossa missão. E, quando o Senhor  nos der esta terra, usaremos de bondade e de fidelidade para com você.

[[v6-2-15]]

^<<v6-2-15,15>>^ Então ela os fez descer por uma corda pela janela, porque a casa em que ela morava estava construída sobre a muralha da cidade.

[[v6-2-16]]

^<<v6-2-16,16>>^ E disse a eles: — Vão para o monte, para que os perseguidores não os encontrem. Escondam-se lá durante três dias, até que eles voltem; e, depois, sigam o seu caminho.

[[v6-2-17]]

^<<v6-2-17,17>>^ Os homens lhe disseram: — Estaremos desobrigados deste seu juramento que você nos fez jurar,

[[v6-2-18]]

^<<v6-2-18,18>>^ se, quando entrarmos nesta terra, você não amarrar este cordão de fio de escarlate na janela por onde você nos fez descer; e se você não reunir em sua casa o seu pai, a sua mãe, os seus irmãos e toda a família de seu pai.

[[v6-2-19]]

^<<v6-2-19,19>>^ Quem sair para fora da porta da casa será responsável pelo que lhe acontecer, e nós seremos inocentes; mas, se alguém puser a mão em alguém que estiver com você dentro de casa, nós seremos responsáveis.

[[v6-2-20]]

^<<v6-2-20,20>>^ E, se você denunciar esta nossa missão, estaremos desobrigados do juramento que você nos fez jurar.

[[v6-2-21]]

^<<v6-2-21,21>>^ E ela disse: — Que seja assim como vocês disseram. Então Raabe os despediu, e eles se foram. E ela amarrou o cordão de escarlate na janela.

[[v6-2-22]]

^<<v6-2-22,22>>^ Os espias foram e chegaram ao monte. E ficaram lá durante três dias, até que os perseguidores voltaram a Jericó; porque os perseguidores os procuraram por todo o caminho, porém não os acharam.

[[v6-2-23]]

^<<v6-2-23,23>>^ Assim, os dois homens voltaram. Desceram do monte, passaram o rio, e vieram a Josué, filho de Num, e lhe contaram tudo o que lhes havia acontecido.

[[v6-2-24]]

^<<v6-2-24,24>>^ E disseram a Josué: — Certamente o Senhor  entregou toda esta terra em nossas mãos, e todos os seus moradores estão se derretendo de medo por causa de nós.

'''

xref:006-josue/006-josue-001.adoc#v6-1-0[&#60; Capítulo Anterior] | <<v6-2-0,Topo>> | xref:006-josue/006-josue-003.adoc#v6-3-0[Próximo Capítulo &#62;]