include::./index.adoc[]

[[v6-14-0]]
=== Josué, 14
// naa ?, NAA - Nova Almeida Atualizada

[[v6-14-1]]

^<<v6-14-1,1>>^ São estas as heranças que os filhos de Israel receberam na terra de Canaã, e que Eleazar, o sacerdote, e Josué, filho de Num, e os chefes das famílias das tribos dos filhos de Israel repartiram entre eles.

[[v6-14-2]]

^<<v6-14-2,2>>^ A distribuição da herança foi feita por sorteio, como o Senhor  havia ordenado por meio de Moisés, a respeito das nove tribos e meia.

[[v6-14-3]]

^<<v6-14-3,3>>^ Porque às duas tribos e meia Moisés já tinha dado herança do outro lado do Jordão; mas aos levitas não tinha dado herança entre os seus irmãos.

[[v6-14-4]]

^<<v6-14-4,4>>^ Os filhos de José constituíram duas tribos, Manassés e Efraim. Aos levitas não deram herança na terra, a não ser cidades em que habitassem e os seus arredores para seu gado e para sua posse.

[[v6-14-5]]

^<<v6-14-5,5>>^ Como o Senhor  havia ordenado a Moisés, assim fizeram os filhos de Israel e repartiram a terra.

[[v6-14-6]]

^<<v6-14-6,6>>^ Os filhos de Judá chegaram a Josué em Gilgal. E Calebe, filho de Jefoné, o quenezeu, lhe disse: — Você sabe o que o Senhor  falou a Moisés, homem de Deus, em Cades-Barneia, a respeito de mim e de você.

[[v6-14-7]]

^<<v6-14-7,7>>^ Eu tinha quarenta anos quando Moisés, servo do Senhor , me enviou de Cades-Barneia para espiar a terra. E eu lhe relatei o que estava no meu coração.

[[v6-14-8]]

^<<v6-14-8,8>>^ Os meus irmãos que tinham ido comigo amedrontaram o povo, mas eu perseverei em seguir o Senhor , meu Deus.

[[v6-14-9]]

^<<v6-14-9,9>>^ Então Moisés, naquele dia, jurou, dizendo: "Certamente a terra em que você pôs o pé será sua e de seus filhos, em herança perpétua, pois você perseverou em seguir o Senhor , meu Deus."

[[v6-14-10]]

^<<v6-14-10,10>>^ — E, agora, eis que o Senhor  me conservou com vida, como prometeu. Quarenta e cinco anos se passaram desde que o Senhor  falou essas palavras a Moisés, quando Israel ainda andava no deserto; e, agora, eis que estou com oitenta e cinco anos.

[[v6-14-11]]

^<<v6-14-11,11>>^ Estou tão forte hoje como no dia em que Moisés me enviou. A força que eu tinha naquele dia eu ainda tenho agora, tanto para combater na guerra como para fazer o que for necessário.

[[v6-14-12]]

^<<v6-14-12,12>>^ Dê-me agora este monte de que o Senhor  falou naquele dia, pois, naquele dia, você ouviu que lá estavam os anaquins, morando em cidades grandes e fortificadas. Se o Senhor  Deus estiver comigo, poderei expulsá-los, como ele mesmo prometeu.

[[v6-14-13]]

^<<v6-14-13,13>>^ Josué o abençoou e deu a cidade de Hebrom a Calebe, filho de Jefoné, para ser a herança dele.

[[v6-14-14]]

^<<v6-14-14,14>>^ Por isso, Hebrom passou a ser de Calebe, filho de Jefoné, o quenezeu, em herança até o dia de hoje, visto que havia perseverado em seguir o Senhor , Deus de Israel.

[[v6-14-15]]

^<<v6-14-15,15>>^ Antes disso o nome de Hebrom era Quiriate-Arba; este Arba foi o maior homem entre os anaquins. E a terra repousou da guerra.

'''

xref:006-josue/006-josue-013.adoc#v6-13-0[&#60; Capítulo Anterior] | <<v6-14-0,Topo>> | xref:006-josue/006-josue-015.adoc#v6-15-0[Próximo Capítulo &#62;]