include::./index.adoc[]

[[v6-11-0]]
=== Josué, 11
// naa ?, NAA - Nova Almeida Atualizada

[[v6-11-1]]

^<<v6-11-1,1>>^ Quando Jabim, rei de Hazor, ouviu isto, enviou mensageiros a Jobabe, rei de Madom, ao rei Sinrom, ao rei Acsafe

[[v6-11-2]]

^<<v6-11-2,2>>^ e aos reis que estavam na região montanhosa ao norte, na Arabá ao sul de Quinerete, na Sefelá e em Nafate-Dor, do lado do mar,

[[v6-11-3]]

^<<v6-11-3,3>>^ aos cananeus do leste e do oeste: aos amorreus, aos heteus, aos ferezeus, aos jebuseus nas montanhas e aos heveus ao pé do Hermom, na terra de Mispa.

[[v6-11-4]]

^<<v6-11-4,4>>^ Saíram, pois, estes e todas as suas tropas com eles, muito povo, em multidão como a areia que está na praia do mar, e também muitos cavalos e carros de guerra.

[[v6-11-5]]

^<<v6-11-5,5>>^ Todos estes reis se ajuntaram, vieram e acamparam junto às águas de Merom, para lutar contra Israel.

[[v6-11-6]]

^<<v6-11-6,6>>^ O Senhor  disse a Josué: — Não tenha medo deles, porque amanhã, a esta mesma hora, eu os entregarei, todos mortos, aos filhos de Israel. Você mutilará os cavalos deles e queimará os seus carros de guerra.

[[v6-11-7]]

^<<v6-11-7,7>>^ Josué e todos os homens de guerra com ele avançaram de surpresa contra eles junto às águas de Merom, e os atacaram.

[[v6-11-8]]

^<<v6-11-8,8>>^ O Senhor  os entregou nas mãos de Israel, que os atacou e perseguiu até a grande Sidom, e até Misrefote-Maim, e até o vale de Mispa, ao leste. Os israelitas os mataram sem deixar nem sequer um.

[[v6-11-9]]

^<<v6-11-9,9>>^ Josué fez com eles como o Senhor  lhe havia ordenado: mutilou os cavalos deles e queimou os seus carros de guerra.

[[v6-11-10]]

^<<v6-11-10,10>>^ Nesse mesmo tempo, Josué voltou, tomou Hazor e feriu à espada o seu rei, porque naquela época Hazor era a capital de todos esses reinos.

[[v6-11-11]]

^<<v6-11-11,11>>^ Mataram à espada todos os que nela estavam e os destruíram totalmente; ninguém sobreviveu. E a cidade de Hazor foi queimada.

[[v6-11-12]]

^<<v6-11-12,12>>^ Josué tomou todas essas cidades e também os seus reis. Matou todos, destruindo-os totalmente, como Moisés, servo do Senhor , havia ordenado.

[[v6-11-13]]

^<<v6-11-13,13>>^ Mas os israelitas não queimaram as cidades que estavam sobre as colinas, exceto Hazor, que Josué queimou.

[[v6-11-14]]

^<<v6-11-14,14>>^ Os israelitas saquearam para si todos os despojos dessas cidades e também o gado; porém mataram à espada todas as pessoas, até que as destruíram; e ninguém sobreviveu.

[[v6-11-15]]

^<<v6-11-15,15>>^ Como o Senhor  havia ordenado a Moisés, seu servo, assim Moisés ordenou a Josué; e assim Josué o fez. Nem uma só palavra deixou de cumprir de tudo o que o Senhor  havia ordenado a Moisés.

[[v6-11-16]]

^<<v6-11-16,16>>^ Assim Josué tomou toda aquela terra, a saber, a região montanhosa, todo o Neguebe, toda a terra de Gósen, a Sefelá, a Arabá e a região montanhosa de Israel com as suas planícies;

[[v6-11-17]]

^<<v6-11-17,17>>^ desde o monte Halaque, que sobe a Seir, até Baal-Gade, no vale do Líbano, ao pé do monte Hermom; também venceu todos os seus reis e os matou.

[[v6-11-18]]

^<<v6-11-18,18>>^ Por muito tempo, Josué fez guerra contra todos esses reis.

[[v6-11-19]]

^<<v6-11-19,19>>^ Não houve cidade que fizesse paz com os filhos de Israel, a não ser os heveus, moradores de Gibeão; todas as demais foram tomadas por meio de guerra.

[[v6-11-20]]

^<<v6-11-20,20>>^ Porque do Senhor  vinha o endurecimento do seu coração para saírem à guerra contra Israel, a fim de que fossem totalmente destruídos e não se tivesse piedade alguma; pelo contrário, fossem totalmente destruídos, como o Senhor  havia ordenado a Moisés.

[[v6-11-21]]

^<<v6-11-21,21>>^ Naquele tempo, Josué foi e eliminou os anaquins da região montanhosa, de Hebrom, de Debir, de Anabe, e de todas as montanhas de Judá, e de todas as montanhas de Israel; Josué os destruiu totalmente com as suas cidades.

[[v6-11-22]]

^<<v6-11-22,22>>^ Nem um dos anaquins sobreviveu na terra dos filhos de Israel; somente em Gaza, Gate e Asdode permaneceram alguns.

[[v6-11-23]]

^<<v6-11-23,23>>^ Assim Josué tomou toda esta terra, segundo tudo o que o Senhor  tinha dito a Moisés. E Josué deu a terra em herança aos filhos de Israel, conforme as suas divisões e tribos. E a terra repousou da guerra.

'''

xref:006-josue/006-josue-010.adoc#v6-10-0[&#60; Capítulo Anterior] | <<v6-11-0,Topo>> | xref:006-josue/006-josue-012.adoc#v6-12-0[Próximo Capítulo &#62;]