include::./index.adoc[]

[[v50-2-0]]
=== Filipenses, 2
// naa ?, NAA - Nova Almeida Atualizada

[[v50-2-1]]

^<<v50-2-1,1>>^ Portanto, se existe alguma exortação em Cristo, alguma consolação de amor, alguma comunhão do Espírito, se há profundo afeto e sentimento de compaixão,

[[v50-2-2]]

^<<v50-2-2,2>>^ então completem a minha alegria, tendo o mesmo modo de pensar, tendo o mesmo amor e sendo unidos de alma e mente.

[[v50-2-3]]

^<<v50-2-3,3>>^ Não façam nada por interesse pessoal ou vaidade, mas por humildade, cada um considerando os outros superiores a si mesmo,

[[v50-2-4]]

^<<v50-2-4,4>>^ não tendo em vista somente os seus próprios interesses, mas também os dos outros.

[[v50-2-5]]

^<<v50-2-5,5>>^ Tenham entre vocês o mesmo modo de pensar de Cristo Jesus,

[[v50-2-6]]

^<<v50-2-6,6>>^ que, mesmo existindo na forma de Deus, não considerou o ser igual a Deus algo que deveria ser retido a qualquer custo.

[[v50-2-7]]

^<<v50-2-7,7>>^ Pelo contrário, ele se esvaziou, assumindo a forma de servo, tornando-se semelhante aos seres humanos. E, reconhecido em figura humana,

[[v50-2-8]]

^<<v50-2-8,8>>^ ele se humilhou, tornando-se obediente até a morte, e morte de cruz.

[[v50-2-9]]

^<<v50-2-9,9>>^ Por isso também Deus o exaltou sobremaneira e lhe deu o nome que está acima de todo nome,

[[v50-2-10]]

^<<v50-2-10,10>>^ para que ao nome de Jesus se dobre todo joelho, nos céus, na terra e debaixo da terra,

[[v50-2-11]]

^<<v50-2-11,11>>^ e toda língua confesse que Jesus Cristo é Senhor, para glória de Deus Pai.

[[v50-2-12]]

^<<v50-2-12,12>>^ Assim, meus amados, como vocês sempre obedeceram, não só na minha presença, porém, muito mais agora, na minha ausência, desenvolvam a sua salvação com temor e tremor,

[[v50-2-13]]

^<<v50-2-13,13>>^ porque Deus é quem efetua em vocês tanto o querer como o realizar, segundo a sua boa vontade.

[[v50-2-14]]

^<<v50-2-14,14>>^ Façam tudo sem murmurações nem discussões,

[[v50-2-15]]

^<<v50-2-15,15>>^ para que sejam irrepreensíveis e puros, filhos de Deus inculpáveis no meio de uma geração pervertida e corrupta, na qual vocês brilham como luzeiros no mundo,

[[v50-2-16]]

^<<v50-2-16,16>>^ preservando a palavra da vida. Assim, no Dia de Cristo, poderei me gloriar de que não corri em vão, nem me esforcei inutilmente.

[[v50-2-17]]

^<<v50-2-17,17>>^ Entretanto, mesmo que eu seja oferecido como libação sobre o sacrifício e serviço da fé que vocês têm, fico contente e me alegro com todos vocês.

[[v50-2-18]]

^<<v50-2-18,18>>^ Assim, também vocês, pela mesma razão, fiquem contentes e se alegrem comigo.

[[v50-2-19]]

^<<v50-2-19,19>>^ Espero no Senhor Jesus enviar-lhes Timóteo o mais breve possível, a fim de que eu me sinta animado também ao receber notícias de vocês.

[[v50-2-20]]

^<<v50-2-20,20>>^ Porque não tenho ninguém com esse mesmo sentimento e que se preocupe tão sinceramente por vocês.

[[v50-2-21]]

^<<v50-2-21,21>>^ Todos os outros buscam os seus próprios interesses e não os de Jesus Cristo.

[[v50-2-22]]

^<<v50-2-22,22>>^ Quanto a Timóteo, vocês conhecem o seu caráter provado, pois serviu ao evangelho, junto comigo, como um filho trabalha ao lado do pai.

[[v50-2-23]]

^<<v50-2-23,23>>^ Portanto, este é quem espero enviar, tão logo eu saiba como vai ficar a minha situação.

[[v50-2-24]]

^<<v50-2-24,24>>^ Mas confio no Senhor que também eu mesmo em breve irei até aí.

[[v50-2-25]]

^<<v50-2-25,25>>^ No entanto, julguei necessário enviar-lhes Epafrodito, meu irmão, cooperador e companheiro de lutas, e, da parte de vocês, mensageiro e auxiliar nas minhas necessidades.

[[v50-2-26]]

^<<v50-2-26,26>>^ Ele tinha muita saudade de todos vocês e estava angustiado porque vocês ficaram sabendo que ele adoeceu.

[[v50-2-27]]

^<<v50-2-27,27>>^ De fato, adoeceu e estava à beira da morte. Mas Deus se compadeceu dele — e não somente dele, mas também de mim —, para que eu não tivesse tristeza sobre tristeza.

[[v50-2-28]]

^<<v50-2-28,28>>^ Por isso, tanto mais me apresso em mandá-lo, para que, vendo-o novamente, vocês fiquem alegres e eu tenha menos tristeza.

[[v50-2-29]]

^<<v50-2-29,29>>^ Recebam-no, pois, no Senhor, com toda a alegria, e honrem sempre os que são como ele.

[[v50-2-30]]

^<<v50-2-30,30>>^ Porque, por causa da obra de Cristo, ele quase morreu, arriscando a própria vida, para suprir a ajuda que vocês não podiam me dar pessoalmente.

'''

xref:050-filipenses/050-filipenses-001.adoc#v50-1-0[&#60; Capítulo Anterior] | <<v50-2-0,Topo>> | xref:050-filipenses/050-filipenses-003.adoc#v50-3-0[Próximo Capítulo &#62;]