include::./index.adoc[]

[[v50-4-0]]
=== Filipenses, 4
// naa ?, NAA - Nova Almeida Atualizada

[[v50-4-1]]

^<<v50-4-1,1>>^ Portanto, meus amados irmãos, de quem tenho muita saudade, vocês que são a minha alegria e coroa, sim, meus amados, permaneçam, deste modo, firmes no Senhor.

[[v50-4-2]]

^<<v50-4-2,2>>^ Peço a Evódia e peço a Síntique que, no Senhor, tenham o mesmo modo de pensar.

[[v50-4-3]]

^<<v50-4-3,3>>^ E peço também a você, fiel companheiro de jugo, que auxilie essas mulheres, pois juntas se esforçaram comigo no evangelho, juntamente com Clemente e com os demais cooperadores meus, cujos nomes se encontram no Livro da Vida.

[[v50-4-4]]

^<<v50-4-4,4>>^ Alegrem-se sempre no Senhor; outra vez digo: alegrem-se!

[[v50-4-5]]

^<<v50-4-5,5>>^ Que a moderação de vocês seja conhecida por todos. Perto está o Senhor.

[[v50-4-6]]

^<<v50-4-6,6>>^ Não fiquem preocupados com coisa alguma, mas, em tudo, sejam conhecidos diante de Deus os pedidos de vocês, pela oração e pela súplica, com ações de graças.

[[v50-4-7]]

^<<v50-4-7,7>>^ E a paz de Deus, que excede todo entendimento, guardará o coração e a mente de vocês em Cristo Jesus.

[[v50-4-8]]

^<<v50-4-8,8>>^ Finalmente, irmãos, tudo o que é verdadeiro, tudo o que é respeitável, tudo o que é justo, tudo o que é puro, tudo o que é amável, tudo o que é de boa fama, se alguma virtude há e se algum louvor existe, seja isso o que ocupe o pensamento de vocês.

[[v50-4-9]]

^<<v50-4-9,9>>^ O que também aprenderam, receberam e ouviram de mim, e o que viram em mim, isso ponham em prática; e o Deus da paz estará com vocês.

[[v50-4-10]]

^<<v50-4-10,10>>^ Fiquei muito alegre no Senhor porque, agora, uma vez mais, renasceu o cuidado que vocês têm por mim. Na verdade, vocês já tinham esse cuidado antes, só que lhes faltava oportunidade.

[[v50-4-11]]

^<<v50-4-11,11>>^ Digo isto, não porque esteja necessitado, porque aprendi a viver contente em toda e qualquer situação.

[[v50-4-12]]

^<<v50-4-12,12>>^ Sei o que é passar necessidade e sei também o que é ter em abundância; aprendi o segredo de toda e qualquer circunstância, tanto de estar alimentado como de ter fome, tanto de ter em abundância como de passar necessidade.

[[v50-4-13]]

^<<v50-4-13,13>>^ Tudo posso naquele que me fortalece.

[[v50-4-14]]

^<<v50-4-14,14>>^ No entanto, vocês fizeram bem, associando-se comigo nas aflições.

[[v50-4-15]]

^<<v50-4-15,15>>^ E como vocês, filipenses, sabem muito bem, no início da pregação do evangelho, quando parti da Macedônia, nenhuma igreja se associou comigo nessa questão de dar e receber, exceto vocês, somente.

[[v50-4-16]]

^<<v50-4-16,16>>^ Porque até quando eu estava em Tessalônica, por mais de uma vez vocês mandaram o bastante para as minhas necessidades.

[[v50-4-17]]

^<<v50-4-17,17>>^ Não que eu esteja pedindo ajuda, pois o que realmente me interessa é o fruto que aumente o crédito na conta de vocês.

[[v50-4-18]]

^<<v50-4-18,18>>^ Recebi tudo e tenho até de sobra. Estou suprido, desde que Epafrodito me entregou o que vocês me mandaram, que é uma oferta de aroma agradável, um sacrifício que Deus aceita e que lhe agrada.

[[v50-4-19]]

^<<v50-4-19,19>>^ E o meu Deus, segundo a sua riqueza em glória, há de suprir, em Cristo Jesus, tudo aquilo de que vocês precisam.

[[v50-4-20]]

^<<v50-4-20,20>>^ A nosso Deus e Pai seja a glória para todo o sempre. Amém!

[[v50-4-21]]

^<<v50-4-21,21>>^ Saúdem cada um dos santos em Cristo Jesus. Os irmãos que estão comigo mandam saudações.

[[v50-4-22]]

^<<v50-4-22,22>>^ Todos os santos mandam saudações, especialmente os da casa de César.

[[v50-4-23]]

^<<v50-4-23,23>>^ A graça do Senhor Jesus Cristo esteja com o espírito de vocês.

'''

xref:050-filipenses/050-filipenses-003.adoc#v50-3-0[&#60; Capítulo Anterior] | <<v50-4-0,Topo>> | xref:051-colossenses/051-colossenses-001.adoc#v51-1-0[Próximo Capítulo &#62;]