include::./index.adoc[]

[[v31-1-0]]
=== Obadias, 1
// naa ?, NAA - Nova Almeida Atualizada

[[v31-1-1]]

^<<v31-1-1,1>>^ Visão de Obadias. Assim diz o Senhor  Deus a respeito de Edom: "Ouvimos uma notícia vinda do Senhor , e um mensageiro foi enviado às nações para dizer: ‘Preparem-se! Preparem-se para a guerra contra Edom!’

[[v31-1-2]]

^<<v31-1-2,2>>^ Eis que fiz de você uma nação pequena entre as outras, muito desprezada.

[[v31-1-3]]

^<<v31-1-3,3>>^ O orgulho do seu coração o enganou. Você vive nas fendas das rochas, num lugar elevado, e diz em seu íntimo: ‘Quem poderá me jogar lá para baixo?’

[[v31-1-4]]

^<<v31-1-4,4>>^ Ainda que você suba como a águia e faça o seu ninho entre as estrelas, de lá eu o derrubarei", diz o Senhor .

[[v31-1-5]]

^<<v31-1-5,5>>^ "Se ladrões o atacassem ou assaltantes viessem de noite — como você está destruído! — não levariam só o que lhes bastasse? Se fossem até você os que colhem uvas, não deixariam pelo menos alguns cachos?

[[v31-1-6]]

^<<v31-1-6,6>>^ Como foram saqueados os bens de Esaú! Como foram vasculhados os seus tesouros escondidos!

[[v31-1-7]]

^<<v31-1-7,7>>^ Todos os seus aliados, ó Edom, o empurraram para fora do seu território. Aqueles que estavam em paz com você o enganaram e prevaleceram contra você. Aqueles que sentam à sua mesa prepararam uma armadilha para os seus pés. E não há em Edom entendimento."

[[v31-1-8]]

^<<v31-1-8,8>>^ "Naquele dia", diz o Senhor , "destruirei os sábios de Edom e o entendimento do monte de Esaú.

[[v31-1-9]]

^<<v31-1-9,9>>^ Os seus valentes, ó Temã, ficarão apavorados, para que, do monte de Esaú, todos sejam exterminados pela matança."

[[v31-1-10]]

^<<v31-1-10,10>>^ "Por causa da violência feita ao seu irmão Jacó, você ficará coberto de vergonha e será exterminado para sempre.

[[v31-1-11]]

^<<v31-1-11,11>>^ No dia em que estranhos levaram os bens de seu irmão Jacó, você estava presente; quando estrangeiros entraram pelos portões e lançaram sortes sobre Jerusalém, você mesmo era um deles.

[[v31-1-12]]

^<<v31-1-12,12>>^ Você não devia ter olhado com prazer para o dia do seu irmão, o dia da sua calamidade. Você não devia ter-se alegrado pelo que aconteceu com os filhos de Judá, no dia da sua ruína. Você não devia ter falado de boca cheia, no dia da angústia.

[[v31-1-13]]

^<<v31-1-13,13>>^ Você não devia ter entrado pelo portão do meu povo, no dia da sua calamidade. Você não devia ter olhado com prazer para o seu mal, no dia da sua calamidade. Você não devia ter posto as mãos sobre os seus bens, no dia da sua calamidade.

[[v31-1-14]]

^<<v31-1-14,14>>^ Você não devia ter parado nas encruzilhadas, para exterminar os que escapassem. Você não devia ter entregado ao inimigo os que escaparam com vida, no dia da angústia."

[[v31-1-15]]

^<<v31-1-15,15>>^ "Porque o Dia do Senhor está prestes a vir sobre todas as nações. Você será tratado da mesma forma como tratou os outros; o mal que você fez cairá sobre a sua cabeça.

[[v31-1-16]]

^<<v31-1-16,16>>^ Porque, assim como vocês beberam no meu santo monte, assim todas as nações beberão sem parar; irão beber, engolir, e serão como se nunca tivessem existido."

[[v31-1-17]]

^<<v31-1-17,17>>^ "Mas, no monte Sião, haverá livramento. O monte será santo, e os da casa de Jacó tomarão posse de sua herança.

[[v31-1-18]]

^<<v31-1-18,18>>^ A casa de Jacó será fogo e a casa de José será chama, mas a casa de Esaú será a palha. O fogo e a chama incendiarão a palha e a consumirão; e ninguém mais restará da casa de Esaú, porque o Senhor  o falou."

[[v31-1-19]]

^<<v31-1-19,19>>^ "Os de Neguebe tomarão posse do monte de Esaú, e os da Sefelá ocuparão o território dos filisteus; tomarão posse também dos campos de Efraim e dos campos de Samaria; e Benjamim tomará posse de Gileade.

[[v31-1-20]]

^<<v31-1-20,20>>^ Os cativos do exército dos filhos de Israel tomarão posse do território dos cananeus até Sarepta, e os cativos de Jerusalém, que estão em Sefarade, tomarão posse das cidades do Sul.

[[v31-1-21]]

^<<v31-1-21,21>>^ Salvadores hão de subir ao monte Sião, para julgarem o monte de Esaú; e o reino será do Senhor ."

'''

xref:030-amos/030-amos-009.adoc#v30-9-0[&#60; Capítulo Anterior] | <<v31-1-0,Topo>> | xref:032-jonas/032-jonas-001.adoc#v32-1-0[Próximo Capítulo &#62;]