include::./index.adoc[]

[[v26-5-0]]
=== Ezequiel, 5
// naa ?, NAA - Nova Almeida Atualizada

[[v26-5-1]]

^<<v26-5-1,1>>^ — Filho do homem, pegue uma espada afiada e use-a como navalha de barbeiro, passando-a pela sua cabeça e pela sua barba. Depois, pegue uma balança e reparta os cabelos que você cortou.

[[v26-5-2]]

^<<v26-5-2,2>>^ Queime uma terça parte no meio da cidade, quando se cumprirem os dias do cerco. Pegue outra terça parte e corte-a com a espada, enquanto você rodeia a cidade. Espalhe a outra terça parte ao vento, e irei atrás deles com a espada.

[[v26-5-3]]

^<<v26-5-3,3>>^ Mas pegue uns poucos cabelos e prenda-os nas bordas das suas roupas.

[[v26-5-4]]

^<<v26-5-4,4>>^ Pegue ainda alguns cabelos, jogue-os no fogo, e deixe que se queimem. Dali sairá um fogo contra toda a casa de Israel.

[[v26-5-5]]

^<<v26-5-5,5>>^ — Assim diz o Senhor  Deus: Esta é Jerusalém; eu a coloquei no meio das nações, com os outros países ao seu redor.

[[v26-5-6]]

^<<v26-5-6,6>>^ Ela, porém, se rebelou contra os meus juízos e os meus estatutos, sendo mais perversa do que as nações e os países ao seu redor. Porque os moradores de Jerusalém rejeitaram os meus juízos e não andaram nos meus estatutos.

[[v26-5-7]]

^<<v26-5-7,7>>^ Portanto, assim diz o Senhor  Deus: Vocês são mais rebeldes do que as nações que estão ao seu redor. Não andaram nos meus estatutos, não executaram os meus juízos, nem procederam segundo o direito das nações ao redor de vocês.

[[v26-5-8]]

^<<v26-5-8,8>>^ Por isso, assim diz o Senhor  Deus: Eis que eu, eu mesmo, estou contra você, Jerusalém, e vou executar os meus juízos dentro de você, à vista das nações.

[[v26-5-9]]

^<<v26-5-9,9>>^ Farei com você o que nunca fiz e o que jamais farei de novo, por causa de todas as suas abominações.

[[v26-5-10]]

^<<v26-5-10,10>>^ Por isso, os pais vão devorar os próprios filhos dentro de você, ó Jerusalém, e os filhos vão devorar os pais. Executarei em você os meus juízos e tudo o que restar de você espalharei aos quatro ventos.

[[v26-5-11]]

^<<v26-5-11,11>>^ Portanto, porque você profanou o meu santuário com todas as suas coisas detestáveis e com todas as suas abominações, tão certo como eu vivo, diz o Senhor  Deus, eu me retirarei. Os meus olhos não terão piedade, e eu não a pouparei.

[[v26-5-12]]

^<<v26-5-12,12>>^ Uma terça parte dos seus moradores morrerá de peste e será consumida pela fome dentro de suas muralhas; outra terça parte cairá à espada nos seus arredores; e a outra terça parte espalharei aos quatro ventos e irei atrás dela com a espada na mão.

[[v26-5-13]]

^<<v26-5-13,13>>^ — Assim se cumprirá a minha ira, satisfarei neles o meu furor e me acalmarei. Saberão que eu, o Senhor , falei motivado pelo meu zelo, quando cumprir neles o meu furor.

[[v26-5-14]]

^<<v26-5-14,14>>^ Jerusalém, farei de você uma desolação e objeto de deboche entre as nações que estão ao seu redor, à vista de todos os que passarem.

[[v26-5-15]]

^<<v26-5-15,15>>^ — Assim, você será objeto de deboche e de zombaria, um exemplo de castigo e um motivo de espanto às nações que estão ao seu redor, quando eu executar em você juízos com ira e indignação, em furiosos castigos. Eu, o Senhor , falei.

[[v26-5-16]]

^<<v26-5-16,16>>^ Quando eu atirar contra eles as flechas mortais da fome, flechas destruidoras, que eu enviarei para destruir vocês, então aumentarei a fome entre vocês e lhes cortarei o suprimento de pão.

[[v26-5-17]]

^<<v26-5-17,17>>^ Enviarei sobre vocês a fome, e animais selvagens que os deixarão sem filhos; a peste e o derramamento de sangue passarão por você, e trarei a espada contra você. Eu, o Senhor , falei.

'''

xref:026-ezequiel/026-ezequiel-004.adoc#v26-4-0[&#60; Capítulo Anterior] | <<v26-5-0,Topo>> | xref:026-ezequiel/026-ezequiel-006.adoc#v26-6-0[Próximo Capítulo &#62;]