include::./index.adoc[]

[[v26-12-0]]
=== Ezequiel, 12
// naa ?, NAA - Nova Almeida Atualizada

[[v26-12-1]]

^<<v26-12-1,1>>^ A palavra do Senhor  veio a mim, dizendo:

[[v26-12-2]]

^<<v26-12-2,2>>^ — Filho do homem, você mora no meio da casa rebelde, que tem olhos para ver e não vê, tem ouvidos para ouvir e não ouve, porque é casa rebelde.

[[v26-12-3]]

^<<v26-12-3,3>>^ — Filho do homem, prepare a bagagem de exílio e durante o dia, à vista deles, vá para o exílio. Do lugar onde você está, vá para outro lugar, à vista deles. Talvez eles entendam, embora sejam casa rebelde.

[[v26-12-4]]

^<<v26-12-4,4>>^ À vista deles, durante o dia, traga para fora a sua bagagem de exílio. Depois, à tarde, saia, à vista deles, como se estivesse indo para o exílio.

[[v26-12-5]]

^<<v26-12-5,5>>^ Abra um buraco na parede, à vista deles, e saia por ali.

[[v26-12-6]]

^<<v26-12-6,6>>^ À vista deles, ponha a bagagem nos ombros e saia com ela quando já for escuro. Cubra o rosto para que você não possa ver o chão, porque eu fiz de você um sinal para a casa de Israel.

[[v26-12-7]]

^<<v26-12-7,7>>^ Como me foi ordenado, assim eu fiz: de dia, levei para fora a minha bagagem de exílio. Depois, à tarde, com as minhas mãos abri um buraco na parede. Saí quando já era escuro, levando nos ombros a bagagem, à vista deles.

[[v26-12-8]]

^<<v26-12-8,8>>^ Pela manhã, a palavra do Senhor  veio a mim, dizendo:

[[v26-12-9]]

^<<v26-12-9,9>>^ — Filho do homem, a casa de Israel, aquela casa rebelde, não lhe perguntou o que você estava fazendo?

[[v26-12-10]]

^<<v26-12-10,10>>^ Pois diga-lhes: Assim diz o Senhor  Deus: "Esta sentença refere-se ao que governa em Jerusalém e a toda a casa de Israel, que está no meio dela."

[[v26-12-11]]

^<<v26-12-11,11>>^ Diga: "Eu sou um sinal para vocês. Como eu fiz, assim será feito com eles; irão para o exílio, para o cativeiro.

[[v26-12-12]]

^<<v26-12-12,12>>^ O príncipe que está no meio deles levará nos ombros a bagagem e, no escuro, sairá. Abrirá um buraco na parede para sair por ele. Cobrirá o rosto para que os seus olhos não vejam o chão.

[[v26-12-13]]

^<<v26-12-13,13>>^ Também estenderei a minha rede sobre ele, e será apanhado nas minhas malhas. Eu o levarei para a Babilônia, à terra dos caldeus, mas ele não a verá, ainda que venha a morrer ali.

[[v26-12-14]]

^<<v26-12-14,14>>^ Espalharei aos quatro ventos todos os que, para o ajudarem, estão ao redor dele, e todas as suas tropas; irei atrás deles com a espada na mão.

[[v26-12-15]]

^<<v26-12-15,15>>^ Saberão que eu sou o Senhor , quando eu os dispersar entre as nações e os espalhar por outras terras.

[[v26-12-16]]

^<<v26-12-16,16>>^ Deixarei que alguns poucos escapem da espada, da fome e da peste, para que publiquem todas as suas coisas abomináveis entre as nações para onde forem; e saberão que eu sou o Senhor ."

[[v26-12-17]]

^<<v26-12-17,17>>^ Então a palavra do Senhor  veio a mim, dizendo:

[[v26-12-18]]

^<<v26-12-18,18>>^ — Filho do homem, você comerá o seu pão com tremor e beberá a sua água com estremecimento e ansiedade.

[[v26-12-19]]

^<<v26-12-19,19>>^ E você dirá ao povo da terra: Assim diz o Senhor  Deus a respeito dos moradores de Jerusalém, na terra de Israel: "Eles comerão o seu pão com ansiedade e beberão a sua água com espanto, porque a terra deles será despojada de tudo o que contém, por causa da violência de todos os que nela habitam.

[[v26-12-20]]

^<<v26-12-20,20>>^ As cidades habitadas cairão em ruínas, e a terra se tornará em desolação; e vocês saberão que eu sou o Senhor ."

[[v26-12-21]]

^<<v26-12-21,21>>^ A palavra do Senhor  veio a mim, dizendo:

[[v26-12-22]]

^<<v26-12-22,22>>^ — Filho do homem, que provérbio é esse que vocês têm na terra de Israel: "Os dias passam, e as profecias fracassam"?

[[v26-12-23]]

^<<v26-12-23,23>>^ Portanto, diga-lhes: Assim diz o Senhor  Deus: "Darei um basta nesse provérbio, e ele não será mais usado em Israel." Mas diga-lhes: "Os dias vêm vindo, e as profecias vão se cumprindo."

[[v26-12-24]]

^<<v26-12-24,24>>^ Porque não haverá mais nenhuma profecia falsa nem adivinhação lisonjeira no meio da casa de Israel.

[[v26-12-25]]

^<<v26-12-25,25>>^ Porque eu, o Senhor , falarei, e a palavra que eu falar se cumprirá e não será adiada. Porque falarei a palavra e a cumprirei, diz o Senhor  Deus, enquanto vocês, que são casa rebelde, ainda estiverem vivos.

[[v26-12-26]]

^<<v26-12-26,26>>^ A palavra do Senhor  veio a mim, dizendo:

[[v26-12-27]]

^<<v26-12-27,27>>^ — Filho do homem, eis que os da casa de Israel dizem: "As visões que esse homem tem se referem a dias futuros, e as suas profecias tratam de tempos distantes."

[[v26-12-28]]

^<<v26-12-28,28>>^ Portanto, diga-lhes: Assim diz o Senhor  Deus: "Nenhuma das minhas palavras será adiada, e a palavra que eu falar se cumprirá", diz o Senhor  Deus.

'''

xref:026-ezequiel/026-ezequiel-011.adoc#v26-11-0[&#60; Capítulo Anterior] | <<v26-12-0,Topo>> | xref:026-ezequiel/026-ezequiel-013.adoc#v26-13-0[Próximo Capítulo &#62;]