include::./index.adoc[]

[[v26-19-0]]
=== Ezequiel, 19
// naa ?, NAA - Nova Almeida Atualizada

[[v26-19-1]]

^<<v26-19-1,1>>^ — Quanto a você, faça uma lamentação sobre os príncipes de Israel.

[[v26-19-2]]

^<<v26-19-2,2>>^ Diga: "Que bela leoa entre os leões era a sua mãe! Deitada entre os leõezinhos, criou os seus filhotes.

[[v26-19-3]]

^<<v26-19-3,3>>^ Criou um dos seus filhotinhos, que, ao se tornar um leãozinho, aprendeu a despedaçar a presa; chegou a devorar gente.

[[v26-19-4]]

^<<v26-19-4,4>>^ Quando as nações ouviram falar dele, o apanharam na cova que fizeram, e ele foi levado com ganchos para a terra do Egito.

[[v26-19-5]]

^<<v26-19-5,5>>^ Vendo frustrada e perdida a sua esperança, a leoa pegou outro dos seus filhotes e o fez leãozinho.

[[v26-19-6]]

^<<v26-19-6,6>>^ Este, andando entre os leões, veio a ser um leãozinho e aprendeu a despedaçar a presa; chegou a devorar gente.

[[v26-19-7]]

^<<v26-19-7,7>>^ Destruiu palácios e arrasou cidades. A terra e os seus moradores ficaram assustados, ao ouvirem o seu rugido.

[[v26-19-8]]

^<<v26-19-8,8>>^ Então se ajuntaram contra ele os povos das províncias vizinhas. Estenderam sobre ele a rede, e ele foi apanhado na cova que fizeram.

[[v26-19-9]]

^<<v26-19-9,9>>^ Com ganchos, meteram-no dentro de uma jaula e o levaram ao rei da Babilônia. Deixaram-no preso, para que nunca mais se ouvisse o seu rugido nos montes de Israel."

[[v26-19-10]]

^<<v26-19-10,10>>^ "Sua mãe era como uma videira dentro da vinha, plantada junto às águas; ela frutificou e se encheu de ramos, por causa das muitas águas.

[[v26-19-11]]

^<<v26-19-11,11>>^ Os galhos fortes se tornaram para ela cetros de dominadores. A sua estatura se elevou até as nuvens, e na sua altura era visível com a multidão dos seus ramos.

[[v26-19-12]]

^<<v26-19-12,12>>^ Mas ela foi arrancada com furor e jogada no chão. O vento leste secou os seus frutos. Seus fortes galhos foram quebrados e secaram; o fogo os consumiu.

[[v26-19-13]]

^<<v26-19-13,13>>^ Agora, a videira está plantada no deserto, numa terra seca e sedenta.

[[v26-19-14]]

^<<v26-19-14,14>>^ Do ramo principal saiu fogo que consumiu o seu fruto, de maneira que já não há nela galho forte que sirva de cetro para dominar." Esta é uma lamentação e ficará servindo de lamentação.

'''

xref:026-ezequiel/026-ezequiel-018.adoc#v26-18-0[&#60; Capítulo Anterior] | <<v26-19-0,Topo>> | xref:026-ezequiel/026-ezequiel-020.adoc#v26-20-0[Próximo Capítulo &#62;]