include::./index.adoc[]

[[v26-43-0]]
=== Ezequiel, 43
// naa ?, NAA - Nova Almeida Atualizada

[[v26-43-1]]

^<<v26-43-1,1>>^ Então o homem me levou ao portão, ao portão que dá para o leste.

[[v26-43-2]]

^<<v26-43-2,2>>^ E eis que, do lado leste, vinha a glória do Deus de Israel. A sua voz era como o som de muitas águas, e a terra resplandeceu por causa da sua glória.

[[v26-43-3]]

^<<v26-43-3,3>>^ O aspecto da visão era como o da visão que eu tive quando vim destruir a cidade e como as visões que tive junto ao rio Quebar. Então caí com o rosto em terra.

[[v26-43-4]]

^<<v26-43-4,4>>^ A glória do Senhor  entrou no templo pelo portão que dá para o leste.

[[v26-43-5]]

^<<v26-43-5,5>>^ O Espírito me levantou e me levou ao átrio interior, e eis que a glória do Senhor  enchia o templo.

[[v26-43-6]]

^<<v26-43-6,6>>^ Enquanto o homem estava em pé ao meu lado, ouvi uma voz que me foi dirigida do interior do templo.

[[v26-43-7]]

^<<v26-43-7,7>>^ O Senhor  me disse: — Filho do homem, este é o lugar do meu trono e o lugar das plantas dos meus pés, onde habitarei no meio dos filhos de Israel para sempre. Nunca mais a casa de Israel contaminará o meu santo nome, nem eles nem os seus reis, com as suas prostituições e com o cadáver dos seus reis, nos seus lugares altos.

[[v26-43-8]]

^<<v26-43-8,8>>^ Quando puseram o seu limiar junto ao meu limiar e os seus batentes junto aos meus batentes, havendo apenas uma parede entre mim e eles, contaminaram o meu santo nome com as abominações que cometeram; por isso, eu os consumi na minha ira.

[[v26-43-9]]

^<<v26-43-9,9>>^ Agora, que eles lancem para longe de mim a sua prostituição e o cadáver dos seus reis, e habitarei no meio deles para sempre.

[[v26-43-10]]

^<<v26-43-10,10>>^ — Filho do homem, mostre à casa de Israel este templo, para que eles se envergonhem das suas iniquidades; deixe que tirem as medidas desse modelo perfeito.

[[v26-43-11]]

^<<v26-43-11,11>>^ Se eles se envergonharem de tudo o que fizeram, faça com que conheçam a planta deste templo e o seu arranjo, as suas saídas, as suas entradas, todas as suas formas, todos os seus estatutos, todas as suas disposições e todas as suas leis. Escreva isto na presença deles para que observem todas as suas instituições e todos os seus estatutos e os cumpram.

[[v26-43-12]]

^<<v26-43-12,12>>^ Esta é a lei do templo: no alto do monte, todo o terreno ao redor será santíssimo. Eis que esta é a lei do templo.

[[v26-43-13]]

^<<v26-43-13,13>>^ São estas as medidas do altar, usando-se o mesmo sistema de medidas utilizado para medir o templo. A calha tem meio metro de fundura e meio metro de largura; e a sua borda, em todo o seu contorno, é de um palmo. E esta é a altura do altar:

[[v26-43-14]]

^<<v26-43-14,14>>^ da calha, no chão, até a parte inferior, um metro, com meio metro de largura. Da parte menor até a parte maior, dois metros, com meio metro de largura.

[[v26-43-15]]

^<<v26-43-15,15>>^ A lareira tem dois metros de altura; da lareira para cima se projetam quatro chifres.

[[v26-43-16]]

^<<v26-43-16,16>>^ A lareira tem seis metros de comprimento e seis metros de largura, um quadrado com quatro lados iguais.

[[v26-43-17]]

^<<v26-43-17,17>>^ A parte do meio tem sete metros de comprimento e sete metros de largura, com quatro lados iguais; a borda ao redor dela é de vinte e cinco centímetros. A calha ao redor do altar tem meio metro. Os degraus do altar estão voltados para o leste.

[[v26-43-18]]

^<<v26-43-18,18>>^ Então ele me disse: — Filho do homem, assim diz o Senhor  Deus: São estas as determinações do altar, no dia em que o fizerem, para oferecerem sobre ele holocaustos e para sobre ele aspergirem sangue.

[[v26-43-19]]

^<<v26-43-19,19>>^ Aos sacerdotes levitas, que são da descendência de Zadoque, que se aproximam de mim, diz o Senhor  Deus, para me servirem, você dará um novilho para oferta pelo pecado.

[[v26-43-20]]

^<<v26-43-20,20>>^ Você pegará um pouco do sangue e o porá sobre os quatro chifres do altar, e nos quatro cantos da parte do meio, e na borda ao redor. Assim, você fará a purificação do altar e a expiação por ele.

[[v26-43-21]]

^<<v26-43-21,21>>^ Então você pegará o novilho da oferta pelo pecado, o qual será queimado no lugar do templo para isso designado, fora do santuário.

[[v26-43-22]]

^<<v26-43-22,22>>^ No segundo dia, você oferecerá um bode sem defeito como oferta pelo pecado; e purificarão o altar, como o purificaram com o novilho.

[[v26-43-23]]

^<<v26-43-23,23>>^ Quando você tiver acabado de o purificar, ofereça um novilho sem defeito e, do rebanho, um carneiro sem defeito.

[[v26-43-24]]

^<<v26-43-24,24>>^ Ofereça-os diante do Senhor ; os sacerdotes espalharão sal sobre eles e os oferecerão em holocausto ao Senhor .

[[v26-43-25]]

^<<v26-43-25,25>>^ Durante sete dias, você oferecerá cada dia um bode como oferta pelo pecado; também prepararão um novilho e, do rebanho, um carneiro sem defeito.

[[v26-43-26]]

^<<v26-43-26,26>>^ Durante sete dias, farão expiação pelo altar e o purificarão; e, assim, o consagrarão.

[[v26-43-27]]

^<<v26-43-27,27>>^ Tendo eles cumprido estes dias, no oitavo dia, e dali em diante, os sacerdotes oferecerão sobre o altar os holocaustos e as ofertas pacíficas que vocês trouxerem; e eu me agradarei de vocês, diz o Senhor  Deus.

'''

xref:026-ezequiel/026-ezequiel-042.adoc#v26-42-0[&#60; Capítulo Anterior] | <<v26-43-0,Topo>> | xref:026-ezequiel/026-ezequiel-044.adoc#v26-44-0[Próximo Capítulo &#62;]