include::./index.adoc[]

[[v26-13-0]]
=== Ezequiel, 13
// naa ?, NAA - Nova Almeida Atualizada

[[v26-13-1]]

^<<v26-13-1,1>>^ A palavra do Senhor  veio a mim, dizendo:

[[v26-13-2]]

^<<v26-13-2,2>>^ — Filho do homem, profetize contra os profetas de Israel. A esses que profetizam o que lhes vem do coração, diga que ouçam a palavra do Senhor .

[[v26-13-3]]

^<<v26-13-3,3>>^ — Assim diz o Senhor  Deus: "Ai dos profetas insensatos, que seguem o seu próprio espírito sem nada terem visto!

[[v26-13-4]]

^<<v26-13-4,4>>^ Os seus profetas, ó Israel, são como chacais entre as ruínas.

[[v26-13-5]]

^<<v26-13-5,5>>^ Vocês não foram consertar as brechas, nem fizeram muralhas para a casa de Israel, para que ela permaneça firme na batalha do Dia do Senhor .

[[v26-13-6]]

^<<v26-13-6,6>>^ As visões que eles tiveram são falsas e as adivinhações são mentirosas. Dizem: ‘O Senhor  disse’, quando o Senhor  não os enviou. E ainda esperam que a palavra se cumpra!

[[v26-13-7]]

^<<v26-13-7,7>>^ Não é fato que vocês tiveram visões falsas e anunciaram adivinhações mentirosas, quando disseram: ‘O Senhor  diz’, sendo que eu não disse nada?"

[[v26-13-8]]

^<<v26-13-8,8>>^ — Portanto, assim diz o Senhor  Deus: "Como vocês anunciam falsidades e têm visões mentirosas, por isso eu estou contra vocês, diz o Senhor  Deus.

[[v26-13-9]]

^<<v26-13-9,9>>^ Minha mão será contra os profetas que têm visões falsas e que adivinham mentiras. Não estarão no conselho do meu povo, não serão inscritos nos registros da casa de Israel, nem entrarão na terra de Israel. E vocês saberão que eu sou o Senhor  Deus.

[[v26-13-10]]

^<<v26-13-10,10>>^ Porque andam enganando, sim, enganando o meu povo, dizendo: ‘Paz’, quando não há paz. E, quando se constrói uma parede sem argamassa, os profetas a cobrem com cal.

[[v26-13-11]]

^<<v26-13-11,11>>^ Diga aos que estão aplicando a cal que a parede ruirá. Haverá chuva torrencial. Vocês, pedras de granizo, cairão, e um vento tempestuoso irromperá.

[[v26-13-12]]

^<<v26-13-12,12>>^ Quando a parede cair, certamente vão perguntar: ‘Onde está a cal com que vocês a caiaram?’"

[[v26-13-13]]

^<<v26-13-13,13>>^ — Portanto, assim diz o Senhor  Deus: "No meu furor, mandarei um vento tempestuoso; na minha ira, haverá chuva torrencial; e, na minha indignação, pedras de granizo, para a destruir.

[[v26-13-14]]

^<<v26-13-14,14>>^ Derrubarei a parede que vocês cobriram com cal. Vou arrasá-la, para que apareçam os seus alicerces. Quando a parede cair, vocês serão destruídos no meio dela e saberão que eu sou o Senhor .

[[v26-13-15]]

^<<v26-13-15,15>>^ Assim, cumprirei o meu furor contra a parede e contra os que a cobriram com cal. E direi a vocês: ‘Já não existe parede, como também não existem aqueles que a cobriram de cal,

[[v26-13-16]]

^<<v26-13-16,16>>^ os profetas de Israel que profetizam a respeito de Jerusalém e para ela têm visões de paz, quando não há paz’", diz o Senhor  Deus.

[[v26-13-17]]

^<<v26-13-17,17>>^ — Filho do homem, vire o seu rosto contra as filhas do seu povo que profetizam o que lhes vem do próprio coração. Profetize contra elas

[[v26-13-18]]

^<<v26-13-18,18>>^ e diga: Assim diz o Senhor  Deus: "Ai das que costuram fitinhas mágicas para serem usadas em todas as articulações das mãos e fazem véus para cabeças de todo tamanho, para enredarem as pessoas! Vocês querem enredar a vida do meu povo para preservar a própria vida?

[[v26-13-19]]

^<<v26-13-19,19>>^ Vocês me profanaram no meio do meu povo por punhados de cevada e por pedaços de pão, para matarem pessoas que não deveriam morrer e para deixarem com vida aqueles que não deveriam viver, mentindo, assim, ao meu povo, que escuta mentiras."

[[v26-13-20]]

^<<v26-13-20,20>>^ — Portanto, assim diz o Senhor  Deus: "Eis que eu sou contra as fitinhas mágicas que vocês usam para enredar as pessoas como se fossem pássaros. Eu as arrancarei dos seus braços, e deixarei livres aqueles que vocês enredaram como se fossem pássaros.

[[v26-13-21]]

^<<v26-13-21,21>>^ Também rasgarei os véus e livrarei o meu povo das mãos de vocês. Ele nunca mais estará ao alcance de vocês para ser caçado. E vocês, mulheres, saberão que eu sou o Senhor ."

[[v26-13-22]]

^<<v26-13-22,22>>^ — "Visto que com mentiras vocês desanimaram o coração do justo, não o havendo eu entristecido, e fortaleceram as mãos do ímpio para que não se desviasse do seu mau caminho e vivesse,

[[v26-13-23]]

^<<v26-13-23,23>>^ por isso vocês não terão mais visões falsas, e nunca mais farão adivinhações. Livrarei o meu povo das mãos de vocês, e vocês, mulheres, saberão que eu sou o Senhor ."

'''

xref:026-ezequiel/026-ezequiel-012.adoc#v26-12-0[&#60; Capítulo Anterior] | <<v26-13-0,Topo>> | xref:026-ezequiel/026-ezequiel-014.adoc#v26-14-0[Próximo Capítulo &#62;]