include::./index.adoc[]

[[v26-44-0]]
=== Ezequiel, 44
// naa ?, NAA - Nova Almeida Atualizada

[[v26-44-1]]

^<<v26-44-1,1>>^ Então o homem me fez voltar para o portão exterior do santuário, que dá para o leste e que estava fechado.

[[v26-44-2]]

^<<v26-44-2,2>>^ E o Senhor  me disse: — Este portão permanecerá fechado; não deverá ser aberto. Ninguém entrará por ele, porque o Senhor , o Deus de Israel, entrou por ele. Por isso, permanecerá fechado.

[[v26-44-3]]

^<<v26-44-3,3>>^ Quanto ao príncipe, ele se assentará ali por ser príncipe, para comer o pão diante do Senhor . Entrará pelo vestíbulo da porta e sairá pelo mesmo caminho.

[[v26-44-4]]

^<<v26-44-4,4>>^ Depois, o homem me levou para a frente do templo, passando pelo portão do norte. Olhei, e eis que a glória do Senhor  enchia a Casa do Senhor ; então caí com o rosto em terra.

[[v26-44-5]]

^<<v26-44-5,5>>^ E o Senhor  me disse: — Filho do homem, preste atenção, veja com os próprios olhos e ouça com os próprios ouvidos tudo o que eu lhe disser a respeito de todas as determinações da Casa do Senhor  e de todas as suas leis. Preste atenção na entrada do templo e em todas as saídas do santuário.

[[v26-44-6]]

^<<v26-44-6,6>>^ — Diga aos rebeldes, à casa de Israel: Assim diz o Senhor  Deus: "Basta de todas essas suas abominações, ó casa de Israel!

[[v26-44-7]]

^<<v26-44-7,7>>^ Porque vocês levaram estrangeiros, incircuncisos de coração e incircuncisos de carne, para estarem em meu santuário e profaná-lo, a saber, o meu templo, quando oferecem o meu pão, a gordura e o sangue. Vocês quebraram a minha aliança, fazendo todas essas abominações.

[[v26-44-8]]

^<<v26-44-8,8>>^ Vocês não cumpriram as prescrições a respeito das minhas coisas sagradas, mas constituíram estrangeiros para executarem o serviço no meu santuário em lugar de vocês."

[[v26-44-9]]

^<<v26-44-9,9>>^ — Assim diz o Senhor  Deus: Nenhum estrangeiro que se encontra no meio dos filhos de Israel, incircunciso de coração ou incircunciso de carne, entrará no meu santuário.

[[v26-44-10]]

^<<v26-44-10,10>>^ Os levitas, porém, que se afastaram de mim quando Israel se desviou, que se desviaram de mim, para ir atrás dos seus ídolos, levarão sobre si a sua iniquidade.

[[v26-44-11]]

^<<v26-44-11,11>>^ Contudo, eles poderão servir no meu santuário como guardas dos portões e ministros do templo. Eles matarão os animais do holocausto e do sacrifício para o povo e estarão diante do povo para o servir.

[[v26-44-12]]

^<<v26-44-12,12>>^ Mas, porque serviram o povo na presença dos seus ídolos e puseram diante da casa de Israel um tropeço que os levou a cair em iniquidade, por isso, jurei a respeito deles, diz o Senhor  Deus, que eles levarão sobre si a sua iniquidade.

[[v26-44-13]]

^<<v26-44-13,13>>^ Não se aproximarão de mim, para me servirem no sacerdócio, nem se aproximarão de nenhuma de todas as minhas coisas sagradas, que são santíssimas, mas levarão sobre si a sua vergonha e as suas abominações que cometeram.

[[v26-44-14]]

^<<v26-44-14,14>>^ Contudo, eu os encarregarei da guarda do templo, de todo o serviço e de tudo o que tiver de ser feito nele.

[[v26-44-15]]

^<<v26-44-15,15>>^ — Mas os sacerdotes levitas, os filhos de Zadoque, que cumpriram as prescrições do meu santuário, quando os filhos de Israel se desviaram de mim, eles se aproximarão de mim, para me servirem, e estarão diante de mim, para me oferecerem a gordura e o sangue, diz o Senhor  Deus.

[[v26-44-16]]

^<<v26-44-16,16>>^ Eles entrarão no meu santuário, e se aproximarão da minha mesa, para me servirem, e cumprirão as minhas prescrições.

[[v26-44-17]]

^<<v26-44-17,17>>^ Quando entrarem pelos portões do átrio interior, usarão vestes de linho. Não deverão usar nada feito de lã, quando servirem nos portões do átrio interior ou dentro do templo.

[[v26-44-18]]

^<<v26-44-18,18>>^ Deverão usar turbantes de linho na cabeça e calções de linho sobre as coxas. Não deverão usar nada que os leve a suar.

[[v26-44-19]]

^<<v26-44-19,19>>^ Quando saírem para o átrio exterior, para junto do povo, deverão tirar as vestes com que ministraram, deixando-as nas santas câmaras. Deverão usar outras roupas, para que, com as suas vestes, não santifiquem o povo.

[[v26-44-20]]

^<<v26-44-20,20>>^ Não raparão a cabeça, nem deixarão o cabelo ficar comprido; pelo contrário, devem cortá-lo como convém.

[[v26-44-21]]

^<<v26-44-21,21>>^ Nenhum sacerdote beberá vinho quando entrar no átrio interior.

[[v26-44-22]]

^<<v26-44-22,22>>^ O sacerdote não se casará nem com viúva nem com mulher divorciada, mas somente com uma virgem da linhagem da casa de Israel ou com a viúva de um sacerdote.

[[v26-44-23]]

^<<v26-44-23,23>>^ Os sacerdotes ensinarão o meu povo a distinguir entre o santo e o profano e lhe darão entendimento quanto à diferença entre o impuro e o puro.

[[v26-44-24]]

^<<v26-44-24,24>>^ Quando houver litígio, eles atuarão como juízes, decidindo a questão segundo o meu direito. Guardarão as minhas leis e os meus estatutos em todas as festas fixas e santificarão os meus sábados.

[[v26-44-25]]

^<<v26-44-25,25>>^ — Não se aproximarão de nenhuma pessoa morta, porque se contaminariam. Apenas se o morto for o pai, a mãe, um filho, uma filha, um irmão, ou uma irmã que não tiver marido, poderão se contaminar.

[[v26-44-26]]

^<<v26-44-26,26>>^ Depois que ele se purificar de novo, deverá esperar sete dias.

[[v26-44-27]]

^<<v26-44-27,27>>^ No dia em que ele entrar no lugar santo, no átrio interior, para ministrar no lugar santo, apresentará a sua oferta pelo pecado, diz o Senhor  Deus.

[[v26-44-28]]

^<<v26-44-28,28>>^ — Os sacerdotes terão uma herança; eu sou a sua herança. Vocês não lhes darão nenhuma propriedade em Israel; eu sou a sua propriedade.

[[v26-44-29]]

^<<v26-44-29,29>>^ As ofertas de cereais, as ofertas pelo pecado e as ofertas pela culpa eles comerão; e toda coisa consagrada em Israel será deles.

[[v26-44-30]]

^<<v26-44-30,30>>^ O melhor de todos os primeiros frutos de toda espécie e toda oferta de toda espécie serão dos sacerdotes. Também a primeira parte do cereal moído vocês darão aos sacerdotes, para que façam repousar a bênção sobre a casa de vocês.

[[v26-44-31]]

^<<v26-44-31,31>>^ Os sacerdotes não comerão nenhum pássaro ou animal que tenha morrido por si mesmo ou que tenha sido dilacerado por outro animal.

'''

xref:026-ezequiel/026-ezequiel-043.adoc#v26-43-0[&#60; Capítulo Anterior] | <<v26-44-0,Topo>> | xref:026-ezequiel/026-ezequiel-045.adoc#v26-45-0[Próximo Capítulo &#62;]