include::./index.adoc[]

[[v26-11-0]]
=== Ezequiel, 11
// naa ?, NAA - Nova Almeida Atualizada

[[v26-11-1]]

^<<v26-11-1,1>>^ Então o Espírito me levantou e me levou ao portão leste da Casa do Senhor , a qual dá para o leste. À entrada do portão, estavam vinte e cinco homens. No meio deles, vi Jazanias, filho de Azur, e Pelatias, filho de Benaías, chefes do povo.

[[v26-11-2]]

^<<v26-11-2,2>>^ E disse-me: — Filho do homem, são estes os homens que planejam o mal e dão conselhos perversos nesta cidade.

[[v26-11-3]]

^<<v26-11-3,3>>^ Eles dizem: "Não está próximo o tempo de construir casas. Esta cidade é a panela, e nós somos a carne."

[[v26-11-4]]

^<<v26-11-4,4>>^ Portanto, profetize contra eles, profetize, ó filho do homem.

[[v26-11-5]]

^<<v26-11-5,5>>^ Então o Espírito do Senhor  caiu sobre mim e me disse: — Fale: Assim diz o Senhor : "É isso o que vocês estão dizendo, ó casa de Israel. Porque eu sei o que passa pela mente de vocês.

[[v26-11-6]]

^<<v26-11-6,6>>^ Vocês multiplicaram os seus mortos nesta cidade e encheram as ruas de cadáveres.

[[v26-11-7]]

^<<v26-11-7,7>>^ Portanto, assim diz o Senhor  Deus: Os mortos que vocês largaram no meio da cidade são a carne, e a cidade é a panela; quanto a vocês, eu os expulsarei da cidade.

[[v26-11-8]]

^<<v26-11-8,8>>^ Vocês ficaram com medo da espada, mas é a espada que trarei sobre vocês, diz o Senhor  Deus.

[[v26-11-9]]

^<<v26-11-9,9>>^ Levarei vocês para fora da cidade e os entregarei nas mãos de estrangeiros, e executarei juízos entre vocês.

[[v26-11-10]]

^<<v26-11-10,10>>^ Vocês cairão à espada. Nos confins de Israel, eu os julgarei, e vocês saberão que eu sou o Senhor .

[[v26-11-11]]

^<<v26-11-11,11>>^ Esta cidade não será uma panela para vocês, e vocês não serão a carne dentro dela. Nos confins de Israel, eu os julgarei,

[[v26-11-12]]

^<<v26-11-12,12>>^ e vocês saberão que eu sou o Senhor . Pois vocês não andaram nos meus estatutos, nem executaram os meus juízos; pelo contrário, agiram segundo os juízos das nações que estão ao redor de vocês."

[[v26-11-13]]

^<<v26-11-13,13>>^ Enquanto eu profetizava, Pelatias, filho de Benaías, morreu. Então caí com o rosto em terra, clamei em alta voz e disse: — Ah! Senhor  Deus! Darás fim ao remanescente de Israel?

[[v26-11-14]]

^<<v26-11-14,14>>^ A palavra do Senhor  veio a mim, dizendo:

[[v26-11-15]]

^<<v26-11-15,15>>^ — Filho do homem, os seus irmãos, os seus próprios irmãos, os seus parentes e toda a casa de Israel, todos eles são aqueles a quem os moradores de Jerusalém disseram: "Afastem-se do Senhor ! A nós é que esta terra foi dada como herança."

[[v26-11-16]]

^<<v26-11-16,16>>^ — Portanto, diga: Assim diz o Senhor  Deus: "Embora eu os tenha expulsado para o meio das nações e embora eu os tenha espalhado por outras terras, eu lhes servirei de santuário, por um pouco de tempo, nas terras para onde foram."

[[v26-11-17]]

^<<v26-11-17,17>>^ — Por isso, diga: Assim diz o Senhor  Deus: "Eu os ajuntarei do meio dos povos, e os recolherei das terras por onde foram espalhados, e lhes darei a terra de Israel.

[[v26-11-18]]

^<<v26-11-18,18>>^ Voltarão para ali e tirarão dela todos os seus ídolos detestáveis e todas as suas abominações.

[[v26-11-19]]

^<<v26-11-19,19>>^ Eu lhes darei um só coração, e porei um espírito novo dentro deles; tirarei deles o coração de pedra e lhes darei coração de carne,

[[v26-11-20]]

^<<v26-11-20,20>>^ para que andem nos meus estatutos e guardem os meus juízos, e os executem. Eles serão o meu povo, e eu serei o seu Deus.

[[v26-11-21]]

^<<v26-11-21,21>>^ Mas, quanto àqueles cujo coração segue os seus ídolos detestáveis e as suas abominações, eu lhes darei o que merecem por seus atos", diz o Senhor  Deus.

[[v26-11-22]]

^<<v26-11-22,22>>^ Então os querubins elevaram as suas asas, e as rodas os acompanhavam; e a glória do Deus de Israel estava no alto, sobre eles.

[[v26-11-23]]

^<<v26-11-23,23>>^ A glória do Senhor  subiu do meio da cidade e se pôs sobre o monte que está a leste da cidade.

[[v26-11-24]]

^<<v26-11-24,24>>^ Depois, o Espírito me levantou e me levou à Caldeia, para junto dos exilados, numa visão pelo Espírito de Deus. E a visão que eu havia tido se afastou de mim.

[[v26-11-25]]

^<<v26-11-25,25>>^ Então contei aos exilados todas as coisas que o Senhor  me havia mostrado.

'''

xref:026-ezequiel/026-ezequiel-010.adoc#v26-10-0[&#60; Capítulo Anterior] | <<v26-11-0,Topo>> | xref:026-ezequiel/026-ezequiel-012.adoc#v26-12-0[Próximo Capítulo &#62;]