include::./index.adoc[]

[[v26-23-0]]
=== Ezequiel, 23
// naa ?, NAA - Nova Almeida Atualizada

[[v26-23-1]]

^<<v26-23-1,1>>^ A palavra do Senhor  veio a mim, dizendo:

[[v26-23-2]]

^<<v26-23-2,2>>^ — Filho do homem, houve duas mulheres, filhas da mesma mãe.

[[v26-23-3]]

^<<v26-23-3,3>>^ Elas se prostituíram no Egito; tornaram-se prostitutas quando eram jovens. Ali foram apertados os seus peitos e apalpados os seios da sua virgindade.

[[v26-23-4]]

^<<v26-23-4,4>>^ Os nomes delas eram Oolá, a mais velha, e Oolibá, sua irmã. Elas eram minhas e tiveram filhos e filhas. Quanto aos nomes, Oolá é Samaria e Oolibá é Jerusalém.

[[v26-23-5]]

^<<v26-23-5,5>>^ — Oolá se prostituiu quando era minha. Inflamou-se pelos seus amantes, pelos assírios, seus vizinhos,

[[v26-23-6]]

^<<v26-23-6,6>>^ que se vestiam de azul, governadores e comandantes, todos jovens atraentes, cavaleiros montados em cavalos.

[[v26-23-7]]

^<<v26-23-7,7>>^ Ela se prostituiu com eles, que eram todos a fina flor dos filhos da Assíria, e com todos aqueles pelos quais se inflamava; com todos os seus ídolos ela se contaminou.

[[v26-23-8]]

^<<v26-23-8,8>>^ Não abandonou a prostituição que havia começado no Egito. Porque, quando era jovem, os homens se deitaram com ela, apalparam os seios da sua virgindade e a trataram como prostituta.

[[v26-23-9]]

^<<v26-23-9,9>>^ Por isso, eu a entreguei nas mãos dos seus amantes, nas mãos dos filhos da Assíria, pelos quais havia se inflamado.

[[v26-23-10]]

^<<v26-23-10,10>>^ Estes descobriram as vergonhas dela, levaram os seus filhos e as suas filhas, e a mataram à espada. Ela se tornou falada entre as mulheres por causa dos juízos que executaram sobre ela.

[[v26-23-11]]

^<<v26-23-11,11>>^ — Apesar de ter visto isso, sua irmã Oolibá se corrompeu mais do que ela em sua paixão, e a sua prostituição foi pior do que a de sua irmã.

[[v26-23-12]]

^<<v26-23-12,12>>^ Inflamou-se pelos filhos da Assíria, governadores e comandantes, seus vizinhos, vestidos com primor, cavaleiros montados em cavalos, todos jovens atraentes.

[[v26-23-13]]

^<<v26-23-13,13>>^ Vi que também ela havia se contaminado; o caminho de ambas era o mesmo.

[[v26-23-14]]

^<<v26-23-14,14>>^ Aumentou a sua prostituição, porque viu figuras de homens gravadas na parede, imagens dos caldeus, pintados de vermelho,

[[v26-23-15]]

^<<v26-23-15,15>>^ de lombos cingidos e turbantes pendentes da cabeça, todos com aparência de oficiais, semelhantes aos filhos da Babilônia, nascidos na Caldeia.

[[v26-23-16]]

^<<v26-23-16,16>>^ Vendo-os, Oolibá se inflamou por eles e lhes mandou mensageiros à Caldeia.

[[v26-23-17]]

^<<v26-23-17,17>>^ Então os filhos da Babilônia vieram se deitar com ela no leito dos amores e a contaminaram com as suas prostituições. Após contaminar-se com eles, enojada, ela os abandonou.

[[v26-23-18]]

^<<v26-23-18,18>>^ Assim, depois que ela mostrou a sua prostituição e a sua nudez, eu a abandonei, com nojo, assim como havia abandonado a irmã dela.

[[v26-23-19]]

^<<v26-23-19,19>>^ Mas Oolibá multiplicou as suas prostituições, lembrando-se dos dias da sua juventude, quando era prostituta na terra do Egito.

[[v26-23-20]]

^<<v26-23-20,20>>^ Inflamou-se pelos seus amantes, cujos membros eram como o de jumento e cuja ejaculação era como a dos cavalos.

[[v26-23-21]]

^<<v26-23-21,21>>^ Assim, você trouxe à memória a perversidade dos seus tempos de jovem, quando os do Egito apalpavam os seus seios e apertavam os peitos da sua juventude.

[[v26-23-22]]

^<<v26-23-22,22>>^ — Por isso, Oolibá, assim diz o Senhor  Deus: "Eis que despertarei contra você os seus amantes, os quais, com nojo, você abandonou, e os trarei contra você de todos os lados:

[[v26-23-23]]

^<<v26-23-23,23>>^ os filhos da Babilônia e todos os caldeus de Pecode, de Soa, de Coa e todos os filhos da Assíria com eles, jovens atraentes, governadores e comandantes, oficiais e homens de renome, todos montados em cavalos.

[[v26-23-24]]

^<<v26-23-24,24>>^ Virão contra você com armas, carros de guerra e carretas, e com um grande exército. Eles se colocarão contra você com escudos grandes, escudos pequenos e capacetes. Deixarei que a julguem, e eles a julgarão segundo as suas leis.

[[v26-23-25]]

^<<v26-23-25,25>>^ Porei contra você o meu zelo, e eles a tratarão com furor. Cortarão o seu nariz e as suas orelhas, e o que restar cairá à espada; levarão os seus filhos e as suas filhas, e quem ainda lhe restar será consumido pelo fogo.

[[v26-23-26]]

^<<v26-23-26,26>>^ Eles arrancarão as suas roupas e levarão as suas belas joias.

[[v26-23-27]]

^<<v26-23-27,27>>^ Assim, acabarei com a sua perversidade e com a prostituição que você trouxe da terra do Egito. Você não levantará os olhos para eles e não se lembrará mais do Egito."

[[v26-23-28]]

^<<v26-23-28,28>>^ — Porque assim diz o Senhor  Deus: "Eis que eu a entregarei nas mãos daqueles que você odeia, nas mãos daqueles que, com nojo, você abandonou.

[[v26-23-29]]

^<<v26-23-29,29>>^ Eles a tratarão com ódio, levarão todo o fruto do seu trabalho e a deixarão completamente nua. Ficará exposta a vergonha da sua prostituição, a sua perversidade e as suas devassidões.

[[v26-23-30]]

^<<v26-23-30,30>>^ Isso lhe acontecerá, porque você se prostituiu com os gentios e se contaminou com os seus ídolos.

[[v26-23-31]]

^<<v26-23-31,31>>^ Você andou no caminho de sua irmã; por isso, o copo que era dela eu entregarei a você."

[[v26-23-32]]

^<<v26-23-32,32>>^ — Assim diz o Senhor  Deus: "Você beberá o copo de sua irmã, que é fundo e largo. Você será motivo de riso e de zombaria, pois nele cabe muito.

[[v26-23-33]]

^<<v26-23-33,33>>^ Você ficará completamente bêbada e sentirá muita dor; o copo de sua irmã Samaria é copo de espanto e de desolação.

[[v26-23-34]]

^<<v26-23-34,34>>^ Você o beberá até a última gota, ficará roendo os cacos, e rasgará os próprios seios. Porque eu falei", diz o Senhor  Deus.

[[v26-23-35]]

^<<v26-23-35,35>>^ — Portanto, assim diz o Senhor  Deus: "Visto que você se esqueceu de mim e me virou as costas, também terá de sofrer as consequências da sua perversidade e das suas prostituições."

[[v26-23-36]]

^<<v26-23-36,36>>^ Disse-me ainda o Senhor : — Filho do homem, você está pronto para julgar Oolá e Oolibá? Mostre-lhes as suas abominações.

[[v26-23-37]]

^<<v26-23-37,37>>^ Porque elas cometeram adultério, e nas suas mãos há culpa de sangue. Adulteraram com os seus ídolos, e até os filhos que tiveram comigo elas ofereceram aos ídolos para serem consumidos pelo fogo.

[[v26-23-38]]

^<<v26-23-38,38>>^ E fizeram mais isto: no mesmo dia contaminaram o meu santuário e profanaram os meus sábados.

[[v26-23-39]]

^<<v26-23-39,39>>^ Pois, havendo sacrificado seus filhos aos ídolos, vieram, no mesmo dia, ao meu santuário para o profanarem; foi o que fizeram em meu templo.

[[v26-23-40]]

^<<v26-23-40,40>>^ E mais ainda: mandaram vir uns homens de longe, aos quais tinha sido enviado um mensageiro, e eis que eles vieram. Por amor deles, você se banhou, pintou os olhos e se enfeitou com joias.

[[v26-23-41]]

^<<v26-23-41,41>>^ Você se assentou num suntuoso leito, diante do qual se achava uma mesa preparada, sobre a qual você pôs o meu incenso e o meu óleo.

[[v26-23-42]]

^<<v26-23-42,42>>^ Ouvia-se com ela a voz de uma multidão alegre. Com homens de classe baixa foram trazidos do deserto uns bêbados, que puseram braceletes nas mãos delas e, na cabeça, belas coroas.

[[v26-23-43]]

^<<v26-23-43,43>>^ Então eu disse a respeito da mulher envelhecida em adultérios: "Agora ela vai continuar com as suas prostituições!"

[[v26-23-44]]

^<<v26-23-44,44>>^ E tiveram relações com ela, como quem tem relações com uma prostituta. Foi assim que tiveram relações com Oolá e Oolibá, essas mulheres depravadas.

[[v26-23-45]]

^<<v26-23-45,45>>^ Mas homens justos as julgarão como se julgam as adúlteras e as assassinas; porque são adúlteras, e, nas suas mãos, há culpa de sangue.

[[v26-23-46]]

^<<v26-23-46,46>>^ — Pois assim diz o Senhor  Deus: Trarei contra elas uma grande multidão e as entregarei ao tumulto e ao saque.

[[v26-23-47]]

^<<v26-23-47,47>>^ A multidão as apedrejará e as golpeará com as suas espadas; matarão os seus filhos e as suas filhas e queimarão as suas casas.

[[v26-23-48]]

^<<v26-23-48,48>>^ Assim, acabarei com a perversidade da terra, para que isso sirva de aviso a todas as mulheres e elas não sigam o exemplo da perversidade delas.

[[v26-23-49]]

^<<v26-23-49,49>>^ Vocês serão castigadas por causa da sua perversidade e sofrerão as consequências de seus pecados de idolatria. E saberão que eu sou o Senhor  Deus.

'''

xref:026-ezequiel/026-ezequiel-022.adoc#v26-22-0[&#60; Capítulo Anterior] | <<v26-23-0,Topo>> | xref:026-ezequiel/026-ezequiel-024.adoc#v26-24-0[Próximo Capítulo &#62;]