include::./index.adoc[]

[[v26-20-0]]
=== Ezequiel, 20
// naa ?, NAA - Nova Almeida Atualizada

[[v26-20-1]]

^<<v26-20-1,1>>^ No sétimo ano, no quinto mês, aos dez dias do mês, alguns dos anciãos de Israel vieram consultar o Senhor  e se assentaram diante de mim.

[[v26-20-2]]

^<<v26-20-2,2>>^ Então a palavra do Senhor  veio a mim, dizendo:

[[v26-20-3]]

^<<v26-20-3,3>>^ — Filho do homem, fale com os anciãos de Israel e diga-lhes: Assim diz o Senhor  Deus: "Por acaso vocês vieram para me consultar? Tão certo como eu vivo, diz o Senhor  Deus, vocês não me consultarão."

[[v26-20-4]]

^<<v26-20-4,4>>^ — Você está pronto para julgá-los, filho do homem? Você está pronto para julgá-los? Mostre-lhes as abominações que os pais deles praticaram

[[v26-20-5]]

^<<v26-20-5,5>>^ e diga-lhes: Assim diz o Senhor  Deus: "No dia em que escolhi Israel, levantando a mão, jurei à descendência da casa de Jacó e me dei a conhecer a eles na terra do Egito; levantei a mão e jurei, dizendo: ‘Eu sou o Senhor , seu Deus.’

[[v26-20-6]]

^<<v26-20-6,6>>^ Naquele dia, jurei tirá-los da terra do Egito e levá-los para uma terra que lhes tinha previsto, uma terra que mana leite e mel, coroa de todas as terras.

[[v26-20-7]]

^<<v26-20-7,7>>^ Então eu lhes disse: ‘Cada um de vocês deve jogar fora as abominações de que se agradam os seus olhos. Não se contaminem com os ídolos do Egito; eu sou o Senhor , seu Deus.’

[[v26-20-8]]

^<<v26-20-8,8>>^ Mas eles se rebelaram contra mim e não quiseram me ouvir. Ninguém jogava fora as abominações de que se agradavam os seus olhos, nem abandonava os ídolos do Egito. Então eu disse que derramaria sobre eles o meu furor, para cumprir a minha ira contra eles, no meio da terra do Egito.

[[v26-20-9]]

^<<v26-20-9,9>>^ Mas agi por amor do meu nome, para que não fosse profanado diante das nações no meio das quais eles estavam, diante das quais eu me dei a conhecer a eles, para os tirar da terra do Egito."

[[v26-20-10]]

^<<v26-20-10,10>>^ — "Eu os tirei da terra do Egito e os levei para o deserto.

[[v26-20-11]]

^<<v26-20-11,11>>^ Dei-lhes os meus estatutos e lhes fiz conhecer os meus juízos, pelos quais o ser humano viverá, se os cumprir.

[[v26-20-12]]

^<<v26-20-12,12>>^ Também lhes dei os meus sábados, para servirem de sinal entre mim e eles, para que soubessem que eu sou o Senhor  que os santifica.

[[v26-20-13]]

^<<v26-20-13,13>>^ Mas a casa de Israel se rebelou contra mim no deserto, não andando nos meus estatutos e rejeitando os meus juízos, pelos quais viverá aquele que os cumprir; e profanaram grandemente os meus sábados. Então eu disse que derramaria sobre eles o meu furor no deserto, para os consumir.

[[v26-20-14]]

^<<v26-20-14,14>>^ Mas agi por amor do meu nome, para que não fosse profanado aos olhos das nações diante das quais os tirei do Egito."

[[v26-20-15]]

^<<v26-20-15,15>>^ — "Além disso, no deserto, jurei que não os levaria à terra que lhes tinha dado, uma terra que mana leite e mel, coroa de todas as terras.

[[v26-20-16]]

^<<v26-20-16,16>>^ Porque rejeitaram os meus juízos, não andaram nos meus estatutos e profanaram os meus sábados, pois o seu coração se voltava para os seus ídolos.

[[v26-20-17]]

^<<v26-20-17,17>>^ Mas os meus olhos tiveram piedade deles e eu não os destruí, nem os consumi totalmente no deserto."

[[v26-20-18]]

^<<v26-20-18,18>>^ — "Então eu disse aos seus filhos no deserto: ‘Não andem nos estatutos de seus pais, nem guardem os seus juízos, nem se contaminem com os seus ídolos.

[[v26-20-19]]

^<<v26-20-19,19>>^ Eu sou o Senhor , seu Deus. Andem nos meus estatutos, guardem os meus juízos e coloquem-nos em prática.

[[v26-20-20]]

^<<v26-20-20,20>>^ Santifiquem os meus sábados, pois servirão de sinal entre mim e vocês, para que saibam que eu sou o Senhor , seu Deus.’

[[v26-20-21]]

^<<v26-20-21,21>>^ Mas também os filhos se rebelaram contra mim e não andaram nos meus estatutos, nem guardaram os meus juízos, pelos quais o ser humano viverá, se os cumprir; pelo contrário, eles profanaram os meus sábados. Então eu disse que derramaria sobre eles o meu furor, para cumprir contra eles a minha ira no deserto.

[[v26-20-22]]

^<<v26-20-22,22>>^ Mas contive a minha mão e agi por amor do meu nome, para que não fosse profanado aos olhos das nações diante das quais os tirei do Egito."

[[v26-20-23]]

^<<v26-20-23,23>>^ — "Mais uma vez, no deserto, jurei dispersá-los entre as nações e espalhá-los por outras terras,

[[v26-20-24]]

^<<v26-20-24,24>>^ porque não executaram os meus juízos, rejeitaram os meus estatutos, profanaram os meus sábados, e os seus olhos se voltavam para os ídolos de seus pais.

[[v26-20-25]]

^<<v26-20-25,25>>^ Por isso também lhes dei estatutos que não eram bons e juízos pelos quais não haviam de viver.

[[v26-20-26]]

^<<v26-20-26,26>>^ Permiti que eles se contaminassem com as suas dádivas, como quando queimavam os seus filhos primogênitos. Fiz isso para que ficassem horrorizados e para que soubessem que eu sou o Senhor ."

[[v26-20-27]]

^<<v26-20-27,27>>^ — Portanto, fale à casa de Israel, ó filho do homem, e diga-lhes: Assim diz o Senhor  Deus: "Ainda nisto os pais de vocês blasfemaram contra mim, na infidelidade que cometeram contra mim:

[[v26-20-28]]

^<<v26-20-28,28>>^ quando eu os introduzi na terra que havia jurado dar-lhes, onde quer que viam um monte alto e uma árvore frondosa, aí ofereciam os seus sacrifícios, apresentavam suas ofertas provocantes, punham os seus aromas agradáveis e ofereciam as suas libações.

[[v26-20-29]]

^<<v26-20-29,29>>^ Eu lhes perguntei: ‘Que lugar alto é esse, aonde vocês vão?’ Por isso, o seu nome tem sido Lugar Alto até o dia de hoje."

[[v26-20-30]]

^<<v26-20-30,30>>^ — Portanto, diga à casa de Israel: Assim diz o Senhor  Deus: "Será que vocês não estão se contaminando a exemplo dos pais de vocês, e se prostituindo com as suas abominações?

[[v26-20-31]]

^<<v26-20-31,31>>^ Quando oferecem as suas dádivas e queimam os seus filhos como sacrifício, vocês se contaminam com todos os seus ídolos, até o dia de hoje. Será que eu devo deixar que vocês me consultem, ó casa de Israel? Tão certo como eu vivo, diz o Senhor  Deus, vocês não me consultarão.

[[v26-20-32]]

^<<v26-20-32,32>>^ O que vocês têm em mente jamais acontecerá, ou seja, isso de dizer: ‘Seremos como as nações, como os povos de outras terras, adorando as árvores e as pedras.’"

[[v26-20-33]]

^<<v26-20-33,33>>^ — "Tão certo como eu vivo, diz o Senhor  Deus, hei de reinar sobre vocês com mão poderosa, com braço estendido e derramado furor.

[[v26-20-34]]

^<<v26-20-34,34>>^ Vou tirá-los do meio dos povos e congregá-los das terras por onde vocês foram espalhados, com mão forte, com braço estendido e derramado furor.

[[v26-20-35]]

^<<v26-20-35,35>>^ Vou levá-los ao deserto dos povos e ali entrarei em juízo com vocês, face a face.

[[v26-20-36]]

^<<v26-20-36,36>>^ Como entrei em juízo com os pais de vocês no deserto da terra do Egito, assim entrarei em juízo com vocês, diz o Senhor  Deus.

[[v26-20-37]]

^<<v26-20-37,37>>^ Eu os farei passar debaixo do meu cajado e os farei entrar no vínculo da aliança.

[[v26-20-38]]

^<<v26-20-38,38>>^ Tirarei do meio de vocês os rebeldes e os que transgrediram contra mim. Eu os farei sair da terra onde estão morando, mas eles não entrarão na terra de Israel. E vocês saberão que eu sou o Senhor ."

[[v26-20-39]]

^<<v26-20-39,39>>^ — "Quanto a vocês, ó casa de Israel, assim diz o Senhor  Deus: Que cada um vá e adore os seus ídolos, agora e mais tarde, já que vocês não querem me ouvir! Mas não profanem mais o meu santo nome com as suas dádivas e com os ídolos de vocês.

[[v26-20-40]]

^<<v26-20-40,40>>^ Porque no meu santo monte, no monte alto de Israel, diz o Senhor  Deus, ali toda a casa de Israel me adorará, toda a casa de Israel, naquela terra. Ali me agradarei deles. Ali requererei as ofertas de vocês, as primícias das dádivas e todas as coisas sagradas.

[[v26-20-41]]

^<<v26-20-41,41>>^ Eu me agradarei de vocês como de aroma agradável, quando eu os tirar do meio dos povos e os congregar das terras por onde vocês foram espalhados; e serei santificado diante das nações por meio de vocês.

[[v26-20-42]]

^<<v26-20-42,42>>^ Vocês saberão que eu sou o Senhor , quando eu os fizer entrar na terra de Israel, na terra que jurei dar aos pais de vocês.

[[v26-20-43]]

^<<v26-20-43,43>>^ Ali, vocês se lembrarão dos seus caminhos e de todas as ações com que se contaminaram e terão nojo de vocês mesmos, por todas as maldades que fizeram.

[[v26-20-44]]

^<<v26-20-44,44>>^ Saberão que eu sou o Senhor , quando eu agir com vocês por amor do meu nome, não segundo os seus maus caminhos, nem segundo as suas ações corruptas, ó casa de Israel", diz o Senhor  Deus.

[[v26-20-45]]

^<<v26-20-45,45>>^ A palavra do Senhor  veio a mim, dizendo:

[[v26-20-46]]

^<<v26-20-46,46>>^ — Filho do homem, vire o seu rosto para o Sul e fale contra ele. Profetize contra a floresta do campo do Sul

[[v26-20-47]]

^<<v26-20-47,47>>^ e diga à floresta do Sul: "Ouça a palavra do Senhor ! Assim diz o Senhor  Deus: Eis que acenderei em você um fogo que consumirá todas as árvores, tanto as verdes como as secas. A chama desse fogo não se apagará e todos os rostos, desde o Sul até o Norte, se queimarão.

[[v26-20-48]]

^<<v26-20-48,48>>^ E todos verão que eu, o Senhor , o acendi; não se apagará."

[[v26-20-49]]

^<<v26-20-49,49>>^ Então eu disse: — Ah! Senhor  Deus! Eles ficam dizendo que eu só sei contar parábolas!

'''

xref:026-ezequiel/026-ezequiel-019.adoc#v26-19-0[&#60; Capítulo Anterior] | <<v26-20-0,Topo>> | xref:026-ezequiel/026-ezequiel-021.adoc#v26-21-0[Próximo Capítulo &#62;]