include::./index.adoc[]

[[v26-46-0]]
=== Ezequiel, 46
// naa ?, NAA - Nova Almeida Atualizada

[[v26-46-1]]

^<<v26-46-1,1>>^ — Assim diz o Senhor  Deus: O portão do átrio interior, que dá para o leste, estará fechado durante os seis dias de trabalho, mas será aberto no sábado e também na Festa da Lua Nova.

[[v26-46-2]]

^<<v26-46-2,2>>^ O príncipe entrará de fora pelo vestíbulo do portão e permanecerá junto ao batente do portão. Os sacerdotes prepararão o holocausto dele e os seus sacrifícios pacíficos; ele se prostrará no limiar do portão e sairá. Mas o portão não será fechado até a tarde.

[[v26-46-3]]

^<<v26-46-3,3>>^ O povo da terra adorará na entrada do mesmo portão, nos sábados e nas Festas da Lua Nova, diante do Senhor .

[[v26-46-4]]

^<<v26-46-4,4>>^ O holocausto que o príncipe oferecer ao Senhor  será, no dia de sábado, seis cordeiros sem defeito e um carneiro sem defeito.

[[v26-46-5]]

^<<v26-46-5,5>>^ A oferta de cereais será de dezessete litros e meio para cada carneiro; para cada cordeiro, a oferta de cereais será o que ele puder dar; e, para cada medida de cereais, três litros e meio de azeite.

[[v26-46-6]]

^<<v26-46-6,6>>^ Mas, na Festa da Lua Nova, será um novilho sem defeito e seis cordeiros e um carneiro; eles serão sem defeito.

[[v26-46-7]]

^<<v26-46-7,7>>^ Preparará por oferta de cereais dezessete litros e meio para cada novilho e dezessete litros e meio para cada carneiro, mas, pelos cordeiros, segundo as suas posses; e, para cada medida de cereais, três litros e meio de azeite.

[[v26-46-8]]

^<<v26-46-8,8>>^ Quando o príncipe entrar, entrará pelo vestíbulo do portão e sairá pelo mesmo caminho.

[[v26-46-9]]

^<<v26-46-9,9>>^ — Mas, quando o povo da terra comparecer diante do Senhor , nas festas fixas, aquele que entrar pelo portão do norte, para adorar, sairá pelo portão do sul; e aquele que entrar pelo portão do sul sairá pelo portão do norte. Não sairá pelo mesmo portão pelo qual entrou, mas sairá pelo portão oposto.

[[v26-46-10]]

^<<v26-46-10,10>>^ O príncipe estará no meio deles, quando eles entrarem; quando eles saírem, ele sairá.

[[v26-46-11]]

^<<v26-46-11,11>>^ Nas solenidades e nas festas fixas, a oferta de cereais será de dezessete litros e meio para cada novilho e dezessete litros e meio para cada carneiro; mas, pelos cordeiros, será o que puder dar; e, para cada medida de cereais, três litros e meio de azeite.

[[v26-46-12]]

^<<v26-46-12,12>>^ — Quando o príncipe quiser oferecer um holocausto ou sacrifícios pacíficos, como oferta voluntária ao Senhor , então lhe abrirão o portão que dá para o leste, e ele oferecerá o seu holocausto e os seus sacrifícios pacíficos, como costuma fazer no dia de sábado. Ele sairá, e o portão será fechado depois que ele sair.

[[v26-46-13]]

^<<v26-46-13,13>>^ — Prepare um cordeiro de um ano, sem defeito, em holocausto ao Senhor , cada dia. Esta oferta deverá ser feita todas as manhãs.

[[v26-46-14]]

^<<v26-46-14,14>>^ Juntamente com ele, prepare todas as manhãs uma oferta de cereais para o Senhor : três litros de farinha e, para misturar com ela, um litro de azeite. Isto é estatuto perpétuo e contínuo.

[[v26-46-15]]

^<<v26-46-15,15>>^ Assim prepararão o cordeiro, a oferta de cereais e o azeite todas as manhãs, em holocausto contínuo.

[[v26-46-16]]

^<<v26-46-16,16>>^ — Assim diz o Senhor  Deus: Se o príncipe der um presente de sua herança a um dos seus filhos, ele pertencerá aos filhos; será propriedade deles por herança.

[[v26-46-17]]

^<<v26-46-17,17>>^ Mas, se ele der um presente da sua herança a um dos seus servos, isso será dele até o ano da liberdade, quando voltará a ser do príncipe. Porque aos seus filhos, e somente a eles, pertencerá a herança.

[[v26-46-18]]

^<<v26-46-18,18>>^ O príncipe não tomará nada da herança do povo, expulsando-os das suas propriedades. Da sua própria propriedade deixará herança aos seus filhos, para que o meu povo não seja espalhado, cada um para longe da sua propriedade.

[[v26-46-19]]

^<<v26-46-19,19>>^ Depois disto, o homem me levou, pela entrada que estava ao lado do portão, para as câmaras santas dos sacerdotes, as quais davam para o norte; e eis que havia um lugar nos fundos, para o lado oeste.

[[v26-46-20]]

^<<v26-46-20,20>>^ Ele me disse: — Este é o lugar onde os sacerdotes cozinharão a oferta pela culpa e a oferta pelo pecado e onde assarão as ofertas de cereais, para que não tragam nada para o átrio exterior e assim santifiquem o povo.

[[v26-46-21]]

^<<v26-46-21,21>>^ Então ele me levou para fora, para o átrio exterior, e me fez passar pelos quatro cantos do átrio; e eis que em cada canto do átrio havia outro átrio.

[[v26-46-22]]

^<<v26-46-22,22>>^ Nos quatro cantos do átrio havia átrios pequenos, menores, de vinte metros de comprimento por quinze de largura. Os quatro tinham as mesmas dimensões.

[[v26-46-23]]

^<<v26-46-23,23>>^ Havia um muro ao redor dos átrios, ao redor dos quatro, e havia lugares para cozinhar ao pé dos muros ao redor.

[[v26-46-24]]

^<<v26-46-24,24>>^ Então ele me disse: — São estas as cozinhas, onde os ministros do templo cozinharão os sacrifícios do povo.

'''

xref:026-ezequiel/026-ezequiel-045.adoc#v26-45-0[&#60; Capítulo Anterior] | <<v26-46-0,Topo>> | xref:026-ezequiel/026-ezequiel-047.adoc#v26-47-0[Próximo Capítulo &#62;]