include::./index.adoc[]

[[v26-45-0]]
=== Ezequiel, 45
// naa ?, NAA - Nova Almeida Atualizada

[[v26-45-1]]

^<<v26-45-1,1>>^ — Quando vocês repartirem a terra como herança, façam uma oferta ao Senhor , uma porção santa da terra. O comprimento dessa porção será de doze quilômetros e meio, e a largura será de cinco quilômetros; ela será santa em toda a sua extensão.

[[v26-45-2]]

^<<v26-45-2,2>>^ Dessa porção, o santuário será uma área quadrada de duzentos e cinquenta metros por duzentos e cinquenta, tendo ao redor uma área aberta de vinte e cinco metros de largura.

[[v26-45-3]]

^<<v26-45-3,3>>^ Dessa porção santa, separe uma área de doze quilômetros e meio de comprimento por cinco quilômetros de largura; ali estará o santuário, o lugar santíssimo.

[[v26-45-4]]

^<<v26-45-4,4>>^ Este será o lugar santo da terra, destinado aos sacerdotes, ministros do santuário, que dele se aproximam para servir o Senhor , e lhes servirá de lugar para as suas casas; será também um lugar santo para o santuário.

[[v26-45-5]]

^<<v26-45-5,5>>^ Os levitas, ministros do templo, terão uma propriedade de doze quilômetros e meio de comprimento por cinco de largura, onde poderão morar em suas cidades.

[[v26-45-6]]

^<<v26-45-6,6>>^ Separem uma área de dois quilômetros e meio de largura por doze quilômetros e meio de comprimento ao lado da porção santa, para ser propriedade da cidade; ela pertencerá a toda a casa de Israel.

[[v26-45-7]]

^<<v26-45-7,7>>^ — O príncipe terá a sua parte dos dois lados da porção santa e da propriedade da cidade, diante da porção santa e diante da propriedade da cidade. Do lado oeste se estenderá na direção do oeste, e do lado leste se estenderá na direção do leste. O comprimento corresponderá a uma das porções das tribos, desde a fronteira oeste até a fronteira leste.

[[v26-45-8]]

^<<v26-45-8,8>>^ Esta terra será a propriedade do príncipe em Israel. Os meus príncipes nunca mais oprimirão o meu povo; pelo contrário, distribuirão a terra à casa de Israel, segundo as suas tribos.

[[v26-45-9]]

^<<v26-45-9,9>>^ — Assim diz o Senhor  Deus: Basta, ó príncipes de Israel! Afastem a violência e a opressão e pratiquem o juízo e a justiça. Deixem de fazer explorações entre o meu povo, diz o Senhor  Deus.

[[v26-45-10]]

^<<v26-45-10,10>>^ — Tenham balanças justas, efa justo e bato justo.

[[v26-45-11]]

^<<v26-45-11,11>>^ O efa, para medir cereais, e o bato, para medir líquidos, serão da mesma capacidade, de maneira que o bato contenha a décima parte do ômer, e o efa contenha a décima parte do ômer. O ômer será a medida padrão.

[[v26-45-12]]

^<<v26-45-12,12>>^ O siclo será de vinte geras. Uma mina será igual a vinte siclos, mais vinte e cinco siclos, mais quinze siclos.

[[v26-45-13]]

^<<v26-45-13,13>>^ — Esta será a oferta que vocês farão: a sexta parte de um efa de cada ômer de trigo, e a sexta parte de um efa de cada ômer de cevada.

[[v26-45-14]]

^<<v26-45-14,14>>^ A porção determinada de azeite será a décima parte de um bato de cada coro de azeite. Um coro, como o ômer, tem dez batos.

[[v26-45-15]]

^<<v26-45-15,15>>^ De cada rebanho de duzentas cabeças, um cordeiro deverá ser tirado dos pastos ricos de Israel, para oferta de cereais, para holocausto e para sacrifício pacífico, para que façam expiação pelo povo, diz o Senhor  Deus.

[[v26-45-16]]

^<<v26-45-16,16>>^ Todo o povo da terra fará contribuição, para esta oferta, ao príncipe em Israel.

[[v26-45-17]]

^<<v26-45-17,17>>^ Estarão a cargo do príncipe os holocaustos, as ofertas de cereais e as libações, nas Festas da Lua Nova e nos sábados, em todas as festas fixas da casa de Israel. Ele mesmo proverá a oferta pelo pecado, a oferta de cereais, o holocausto e os sacrifícios pacíficos, para fazer expiação pela casa de Israel.

[[v26-45-18]]

^<<v26-45-18,18>>^ — Assim diz o Senhor  Deus: No primeiro mês, no primeiro dia do mês, você pegará um novilho sem defeito e fará a purificação do santuário.

[[v26-45-19]]

^<<v26-45-19,19>>^ O sacerdote pegará um pouco do sangue e o porá nos batentes do templo, nos quatro cantos da borda do altar e nos batentes do portão do átrio interior.

[[v26-45-20]]

^<<v26-45-20,20>>^ Faça o mesmo no sétimo dia do mês, por causa dos que pecam sem intenção ou por ignorância. Assim, vocês farão expiação pelo templo.

[[v26-45-21]]

^<<v26-45-21,21>>^ — No primeiro mês, no dia catorze do mês, vocês terão a Páscoa, festa de sete dias, em que comerão pães sem fermento.

[[v26-45-22]]

^<<v26-45-22,22>>^ O príncipe, no mesmo dia, por si e por todo o povo da terra, proverá um novilho para oferta pelo pecado.

[[v26-45-23]]

^<<v26-45-23,23>>^ Nos sete dias da festa, ele preparará um holocausto ao Senhor : sete novilhos e sete carneiros sem defeito, cada dia durante os sete dias; e um bode cada dia como oferta pelo pecado.

[[v26-45-24]]

^<<v26-45-24,24>>^ Também preparará uma oferta de cereais: dezessete litros e meio para cada novilho e para cada carneiro, e três litros e meio de azeite.

[[v26-45-25]]

^<<v26-45-25,25>>^ No dia quinze do sétimo mês e durante os sete dias da festa, fará o mesmo: a mesma oferta pelo pecado, o mesmo holocausto, a mesma oferta e a mesma porção de azeite.

'''

xref:026-ezequiel/026-ezequiel-044.adoc#v26-44-0[&#60; Capítulo Anterior] | <<v26-45-0,Topo>> | xref:026-ezequiel/026-ezequiel-046.adoc#v26-46-0[Próximo Capítulo &#62;]