include::./index.adoc[]

[[v26-38-0]]
=== Ezequiel, 38
// naa ?, NAA - Nova Almeida Atualizada

[[v26-38-1]]

^<<v26-38-1,1>>^ A palavra do Senhor  veio a mim, dizendo:

[[v26-38-2]]

^<<v26-38-2,2>>^ — Filho do homem, vire o seu rosto contra Gogue, da terra de Magogue, príncipe de Rôs, de Meseque e Tubal, e profetize contra ele,

[[v26-38-3]]

^<<v26-38-3,3>>^ dizendo: Assim diz o Senhor  Deus: "Eis que estou contra você, Gogue, príncipe de Rôs, de Meseque e Tubal.

[[v26-38-4]]

^<<v26-38-4,4>>^ Eu o farei mudar de direção, porei anzóis em seu queixo e o levarei para longe, juntamente com todo o seu exército: cavalos e cavaleiros, todos vestidos de armamento completo, grande multidão, com escudos, todos empunhando a espada;

[[v26-38-5]]

^<<v26-38-5,5>>^ persas e etíopes e Pute com eles, todos com escudo e capacete;

[[v26-38-6]]

^<<v26-38-6,6>>^ Gômer e todas as suas tropas; a casa de Togarma, do lado do Norte, e todas as suas tropas, muitos povos com você."

[[v26-38-7]]

^<<v26-38-7,7>>^ — "Prepare-se, sim, esteja preparado, você e toda a multidão de povo que se reuniu a você, e sirva-lhes de guarda.

[[v26-38-8]]

^<<v26-38-8,8>>^ Depois de muitos dias, você será convocado; no fim dos anos, você invadirá a terra que se recuperou da espada, cujo povo foi reunido dentre muitos povos sobre os montes de Israel, que por muito tempo estavam desolados. Este povo foi tirado do meio dos povos, e todos eles habitarão em segurança.

[[v26-38-9]]

^<<v26-38-9,9>>^ Então você subirá, virá como uma tempestade, será como uma nuvem que cobre a terra, você, e todas as suas tropas, e muitos povos com você."

[[v26-38-10]]

^<<v26-38-10,10>>^ — Assim diz o Senhor  Deus: "Naquele dia, certos pensamentos virão à sua mente e você conceberá um plano perverso.

[[v26-38-11]]

^<<v26-38-11,11>>^ Você dirá: ‘Vou invadir a terra das aldeias sem muralhas. Atacarei um povo pacífico que vive em segurança, todos em cidades sem muralhas, sem ferrolhos nem portões,

[[v26-38-12]]

^<<v26-38-12,12>>^ para levar o despojo, arrebatar a presa e levantar a mão contra as terras desertas que agora se acham habitadas e contra o povo que se congregou dentre as nações, o qual tem gado e bens e habita no meio da terra.’

[[v26-38-13]]

^<<v26-38-13,13>>^ Sabá e Dedã e os mercadores de Társis, e todos os seus governadores lhe dirão: ‘Você veio para levar o despojo? Você reuniu o seu bando para arrebatar a presa, para levar a prata e o ouro, para pegar o gado e os bens, para saquear grandes despojos?’"

[[v26-38-14]]

^<<v26-38-14,14>>^ — Portanto, profetize, filho do homem, e diga a Gogue: Assim diz o Senhor  Deus: "Será que, naquele dia, quando o meu povo de Israel estiver vivendo em segurança, você não ficará sabendo?

[[v26-38-15]]

^<<v26-38-15,15>>^ Você virá do seu lugar, dos lados do Norte, você e muitos povos com você, todos montados em cavalos, uma grande multidão e um poderoso exército.

[[v26-38-16]]

^<<v26-38-16,16>>^ Você subirá contra o meu povo de Israel, como nuvem, para cobrir a terra. Nos últimos dias, trarei você contra a minha terra, para que as nações me conheçam, quando eu tiver revelado a minha santidade em você, ó Gogue, diante das nações."

[[v26-38-17]]

^<<v26-38-17,17>>^ — Assim diz o Senhor  Deus: "Por acaso você não é aquele de quem falei nos tempos antigos, por meio dos meus servos, os profetas de Israel, que naqueles dias profetizaram, durante anos, que eu faria com que você viesse e atacasse o meu povo?

[[v26-38-18]]

^<<v26-38-18,18>>^ Naquele dia, quando Gogue vier contra a terra de Israel, diz o Senhor  Deus, eu ficarei furioso.

[[v26-38-19]]

^<<v26-38-19,19>>^ Pois, no meu zelo, no fogo do meu furor, eu disse que, naquele dia, haverá um grande terremoto na terra de Israel.

[[v26-38-20]]

^<<v26-38-20,20>>^ Os peixes do mar, as aves do céu, os animais selvagens, todos os animais que rastejam sobre a terra e todas as pessoas que estão sobre a face da terra tremerão diante de mim. Os montes virão abaixo, os rochedos se desfarão, e todas as muralhas desabarão por terra.

[[v26-38-21]]

^<<v26-38-21,21>>^ Convocarei a espada contra Gogue em todos os meus montes, diz o Senhor  Deus; a espada de cada um se voltará contra o seu próximo.

[[v26-38-22]]

^<<v26-38-22,22>>^ Eu o castigarei com peste e derramamento de sangue. Farei cair chuva torrencial, grandes pedras de granizo, fogo e enxofre sobre ele, sobre as suas tropas e sobre os muitos povos que estiverem com ele.

[[v26-38-23]]

^<<v26-38-23,23>>^ Assim, revelarei a minha grandeza e a minha santidade e me darei a conhecer aos olhos de muitas nações. E saberão que eu sou o Senhor ."

'''

xref:026-ezequiel/026-ezequiel-037.adoc#v26-37-0[&#60; Capítulo Anterior] | <<v26-38-0,Topo>> | xref:026-ezequiel/026-ezequiel-039.adoc#v26-39-0[Próximo Capítulo &#62;]