include::./index.adoc[]

[[v26-29-0]]
=== Ezequiel, 29
// naa ?, NAA - Nova Almeida Atualizada

[[v26-29-1]]

^<<v26-29-1,1>>^ No décimo ano, no décimo mês, aos doze dias do mês, a palavra do Senhor  veio a mim, dizendo:

[[v26-29-2]]

^<<v26-29-2,2>>^ — Filho do homem, vire o seu rosto contra Faraó, rei do Egito, e profetize contra ele e contra todo o Egito.

[[v26-29-3]]

^<<v26-29-3,3>>^ Fale e diga: Assim diz o Senhor  Deus: "Eis que estou contra você, Faraó, rei do Egito, crocodilo enorme, deitado no meio dos seus rios, e que diz: ‘O meu rio é meu; eu o fiz para mim mesmo.’

[[v26-29-4]]

^<<v26-29-4,4>>^ Mas eu porei anzóis em seus queixos e farei com que os peixes dos seus rios se apeguem às suas escamas. Vou tirá-lo do meio dos seus rios, juntamente com todos os peixes dos seus rios grudados nas suas escamas.

[[v26-29-5]]

^<<v26-29-5,5>>^ Vou lançá-lo no deserto, você e todos os peixes dos seus rios. Você cairá em campo aberto, não será recolhido nem sepultado. Eu o darei como alimento aos animais selvagens e às aves do céu.

[[v26-29-6]]

^<<v26-29-6,6>>^ E todos os moradores do Egito saberão que eu sou o Senhor ." — Porque os egípcios se tornaram um bordão de caniço para a casa de Israel.

[[v26-29-7]]

^<<v26-29-7,7>>^ Quando os israelitas o pegaram com a mão, você rachou e lhes rasgou o ombro; quando eles se apoiaram, você quebrou, fazendo tremer os lombos deles.

[[v26-29-8]]

^<<v26-29-8,8>>^ Por isso, assim diz o Senhor  Deus: "Eis que trarei sobre você a espada e eliminarei de você pessoas e animais.

[[v26-29-9]]

^<<v26-29-9,9>>^ A terra do Egito se tornará em desolação e deserto; e saberão que eu sou o Senhor . Porque você disse: ‘O rio é meu; eu o fiz’,

[[v26-29-10]]

^<<v26-29-10,10>>^ eis que estou contra você e contra os seus rios. Farei da terra do Egito um deserto, uma completa desolação, desde Migdol até Sevene, até as fronteiras da Etiópia.

[[v26-29-11]]

^<<v26-29-11,11>>^ Não passará por ela pé humano, nem pata de animal passará por ela, nem será habitada durante quarenta anos,

[[v26-29-12]]

^<<v26-29-12,12>>^ porque tornarei a terra do Egito em desolação, no meio de terras desoladas; as suas cidades no meio das cidades desertas se tornarão em desolação durante quarenta anos; dispersarei os egípcios entre as nações e os espalharei por outras terras."

[[v26-29-13]]

^<<v26-29-13,13>>^ — Mas assim diz o Senhor  Deus: Ao fim de quarenta anos, ajuntarei os egípcios do meio dos povos por onde foram espalhados.

[[v26-29-14]]

^<<v26-29-14,14>>^ Restaurarei a sorte dos egípcios e os farei voltar à terra de Patros, à terra de sua origem; e serão ali um reino humilde.

[[v26-29-15]]

^<<v26-29-15,15>>^ O Egito se tornará o mais humilde dos reinos e nunca mais se exaltará sobre as nações. Eu os diminuirei, para que não dominem sobre as nações.

[[v26-29-16]]

^<<v26-29-16,16>>^ A casa de Israel nunca mais porá a sua confiança no Egito, confiança essa que me traria à memória a iniquidade de Israel quando se voltava ao Egito em busca de socorro. Então eles saberão que eu sou o Senhor  Deus.

[[v26-29-17]]

^<<v26-29-17,17>>^ No vigésimo sétimo ano, no primeiro mês, no primeiro dia do mês, a palavra do Senhor  veio a mim, dizendo:

[[v26-29-18]]

^<<v26-29-18,18>>^ — Filho do homem, o rei Nabucodonosor, da Babilônia, conduziu o seu exército num difícil ataque à cidade de Tiro. Todas as cabeças se tornaram calvas e todos os ombros ficaram esfolados, mas nem ele nem o seu exército receberam qualquer recompensa pelo esforço que fizeram.

[[v26-29-19]]

^<<v26-29-19,19>>^ Portanto, assim diz o Senhor  Deus: Eis que eu darei a Nabucodonosor, rei da Babilônia, a terra do Egito. Ele levará a sua multidão, tomará o seu despojo e roubará a sua presa, e isto será o pagamento para o seu exército.

[[v26-29-20]]

^<<v26-29-20,20>>^ Como pagamento pelo seu esforço eu lhe dei a terra do Egito, visto que eles trabalharam para mim, diz o Senhor  Deus.

[[v26-29-21]]

^<<v26-29-21,21>>^ — Naquele dia, farei brotar o poder na casa de Israel. E a você, Ezequiel, permitirei que fale livremente no meio deles. E saberão que eu sou o Senhor .

'''

xref:026-ezequiel/026-ezequiel-028.adoc#v26-28-0[&#60; Capítulo Anterior] | <<v26-29-0,Topo>> | xref:026-ezequiel/026-ezequiel-030.adoc#v26-30-0[Próximo Capítulo &#62;]