include::./index.adoc[]

[[v26-39-0]]
=== Ezequiel, 39
// naa ?, NAA - Nova Almeida Atualizada

[[v26-39-1]]

^<<v26-39-1,1>>^ — Filho do homem, profetize contra Gogue e diga: Assim diz o Senhor  Deus: "Eis que estou contra você, Gogue, príncipe de Rôs, de Meseque e Tubal.

[[v26-39-2]]

^<<v26-39-2,2>>^ Eu o farei mudar de direção e o conduzirei. Farei com que você venha dos lados do Norte e o trarei aos montes de Israel.

[[v26-39-3]]

^<<v26-39-3,3>>^ Então tirarei o arco da sua mão esquerda e farei cair as flechas que estão em sua mão direita.

[[v26-39-4]]

^<<v26-39-4,4>>^ Nos montes de Israel, você cairá — você, todas as suas tropas e os povos que estão com você. Eu o entregarei a todo tipo de ave de rapina e aos animais selvagens, para que o devorem.

[[v26-39-5]]

^<<v26-39-5,5>>^ Você cairá em campo aberto, porque eu falei, diz o Senhor  Deus.

[[v26-39-6]]

^<<v26-39-6,6>>^ Porei fogo em Magogue e nos que vivem em segurança nas terras do mar. Então eles saberão que eu sou o Senhor .

[[v26-39-7]]

^<<v26-39-7,7>>^ Farei conhecido o meu santo nome no meio do meu povo de Israel e nunca mais deixarei que o meu santo nome seja profanado. Então as nações saberão que eu sou o Senhor , o Santo em Israel."

[[v26-39-8]]

^<<v26-39-8,8>>^ — Eis que vem e se cumprirá, diz o Senhor  Deus; este é o dia de que tenho falado.

[[v26-39-9]]

^<<v26-39-9,9>>^ Os moradores das cidades de Israel sairão e farão fogo com as armas, queimando as couraças e os escudos, os arcos e as flechas, os porretes e as lanças; farão fogo com tudo isso durante sete anos.

[[v26-39-10]]

^<<v26-39-10,10>>^ Não terão de trazer lenha do campo, nem a cortarão dos bosques, mas com as armas acenderão fogo. Saquearão aqueles que os saquearam e despojarão aqueles que os despojaram, diz o Senhor  Deus.

[[v26-39-11]]

^<<v26-39-11,11>>^ — Naquele dia, darei a Gogue um lugar de sepultura em Israel, o vale dos Viajantes, a leste do mar, que fará parar os que passarem por esse lugar. Gogue e todo o seu exército serão sepultados ali, e aquele lugar será chamado de Hamom-Gogue.

[[v26-39-12]]

^<<v26-39-12,12>>^ A casa de Israel levará sete meses para sepultá-los, a fim de limpar a terra.

[[v26-39-13]]

^<<v26-39-13,13>>^ Sim, todo o povo da terra os sepultará. E o dia em que eu for glorificado será para eles um dia memorável, diz o Senhor  Deus.

[[v26-39-14]]

^<<v26-39-14,14>>^ Serão separados homens que, sem cessar, percorrerão a terra para sepultar os que tenham ficado nela, para a limpar; depois de sete meses, iniciarão a busca.

[[v26-39-15]]

^<<v26-39-15,15>>^ Ao percorrerem a terra, se um deles encontrar um osso humano, porá ao lado um sinal, até que os coveiros o sepultem no vale do Exército de Gogue.

[[v26-39-16]]

^<<v26-39-16,16>>^ Também haverá uma cidade com o nome de Hamoná. Assim, limparão a terra.

[[v26-39-17]]

^<<v26-39-17,17>>^ — Filho do homem, assim diz o Senhor  Deus: Diga às aves de toda espécie e a todos os animais selvagens: "Reúnam-se e venham! Venham de toda parte para o sacrifício que eu estou oferecendo por vocês, um grande sacrifício nos montes de Israel. Vocês comerão carne e beberão sangue.

[[v26-39-18]]

^<<v26-39-18,18>>^ Comerão a carne dos poderosos e beberão o sangue dos príncipes da terra — os carneiros e cordeiros, os bodes e novilhos, todos engordados em Basã.

[[v26-39-19]]

^<<v26-39-19,19>>^ Vocês comerão gordura até se fartarem e beberão sangue até ficarem embriagados, no sacrifício que oferecerei por vocês.

[[v26-39-20]]

^<<v26-39-20,20>>^ À minha mesa, vocês se fartarão de cavalos e de cavaleiros, de valentes e de todos os homens de guerra", diz o Senhor  Deus.

[[v26-39-21]]

^<<v26-39-21,21>>^ — Manifestarei a minha glória entre as nações, e todas as nações verão o meu juízo, que eu tiver executado, e a minha mão, que eu tiver posto sobre elas.

[[v26-39-22]]

^<<v26-39-22,22>>^ Desse dia em diante, a casa de Israel saberá que eu sou o Senhor , seu Deus.

[[v26-39-23]]

^<<v26-39-23,23>>^ As nações saberão que a casa de Israel foi levada para o exílio por causa da sua iniquidade, porque foram infiéis a mim. Assim, escondi deles o meu rosto e os entreguei nas mãos dos seus adversários, e todos eles caíram à espada.

[[v26-39-24]]

^<<v26-39-24,24>>^ Eu os tratei de acordo com a sua impureza e as suas transgressões, e escondi deles o meu rosto.

[[v26-39-25]]

^<<v26-39-25,25>>^ — Portanto, assim diz o Senhor  Deus: Agora, restaurarei a sorte de Jacó e me compadecerei de toda a casa de Israel; terei zelo pelo meu santo nome.

[[v26-39-26]]

^<<v26-39-26,26>>^ Quando eles habitarem seguros na sua terra, sem haver quem os atemorize, esquecerão a sua vergonha e toda a infidelidade com que se rebelaram contra mim.

[[v26-39-27]]

^<<v26-39-27,27>>^ Quando eu tornar a trazê-los do meio dos povos, e os houver ajuntado das terras de seus inimigos, revelarei neles a minha santidade diante de muitas nações.

[[v26-39-28]]

^<<v26-39-28,28>>^ Saberão que eu sou o Senhor , seu Deus, quando virem que eu os enviei para o cativeiro entre as nações, e os tornei a ajuntar para voltarem à sua terra, e que não deixarei que nenhum deles fique no exílio.

[[v26-39-29]]

^<<v26-39-29,29>>^ Nunca mais esconderei deles o meu rosto, pois derramarei o meu Espírito sobre a casa de Israel, diz o Senhor  Deus.

'''

xref:026-ezequiel/026-ezequiel-038.adoc#v26-38-0[&#60; Capítulo Anterior] | <<v26-39-0,Topo>> | xref:026-ezequiel/026-ezequiel-040.adoc#v26-40-0[Próximo Capítulo &#62;]