include::./index.adoc[]

[[v26-36-0]]
=== Ezequiel, 36
// naa ?, NAA - Nova Almeida Atualizada

[[v26-36-1]]

^<<v26-36-1,1>>^ — Filho do homem, profetize para os montes de Israel e diga: Montes de Israel, ouçam a palavra do Senhor .

[[v26-36-2]]

^<<v26-36-2,2>>^ Assim diz o Senhor  Deus: "Os inimigos disseram a respeito de vocês: ‘Bem feito!’, e também: ‘Os eternos lugares altos são nossa herança.’"

[[v26-36-3]]

^<<v26-36-3,3>>^ Por isso, profetize e diga: Assim diz o Senhor  Deus: "Visto que eles os assolaram e procuraram abocanhar de todos os lados, para que vocês se tornassem propriedade do resto das nações e fossem alvo de falatório e difamação entre o povo,

[[v26-36-4]]

^<<v26-36-4,4>>^ por isso, ó montes de Israel, ouçam a palavra do Senhor  Deus: Assim diz o Senhor  Deus aos montes e às colinas, aos desfiladeiros e aos vales, aos lugares desertos e desolados e às cidades abandonadas, que se tornaram rapina e motivo de zombaria para o resto das nações vizinhas."

[[v26-36-5]]

^<<v26-36-5,5>>^ — Portanto, assim diz o Senhor  Deus: Certamente, no fogo do meu zelo, falei contra o resto das nações e contra todo o Edom. Eles se apropriaram da minha terra, com alegria de todo o coração e com profundo desprezo, para despovoá-la e saqueá-la.

[[v26-36-6]]

^<<v26-36-6,6>>^ — Portanto, profetize a respeito da terra de Israel e diga aos montes e às colinas, aos desfiladeiros e aos vales: Assim diz o Senhor  Deus: "Eis que falo no meu zelo e no meu furor, porque vocês tiveram de suportar a zombaria das nações.

[[v26-36-7]]

^<<v26-36-7,7>>^ Portanto, assim diz o Senhor  Deus: Juro que as nações que estão ao redor de vocês também serão motivo de zombaria.

[[v26-36-8]]

^<<v26-36-8,8>>^ Quanto a vocês, montes de Israel, vocês produzirão os seus ramos e darão os seus frutos para o meu povo de Israel, o qual está prestes a vir.

[[v26-36-9]]

^<<v26-36-9,9>>^ Porque eis que estou do lado de vocês. Eu me voltarei para vocês, e vocês serão lavrados e semeados.

[[v26-36-10]]

^<<v26-36-10,10>>^ Multiplicarei pessoas sobre vocês, toda a casa de Israel, sim, toda ela. As cidades serão habitadas e as ruínas serão reconstruídas.

[[v26-36-11]]

^<<v26-36-11,11>>^ Multiplicarei pessoas e animais sobre vocês. Eles se multiplicarão e serão fecundos. Farei com que vocês voltem a morar onde moravam no passado e os tratarei melhor do que no começo. Então vocês saberão que eu sou o Senhor .

[[v26-36-12]]

^<<v26-36-12,12>>^ Farei com que pessoas, o meu povo de Israel, andem sobre vocês, ó montes. Eles tomarão posse de vocês, vocês serão a herança deles, e nunca mais deixarão que eles fiquem sem os seus filhos."

[[v26-36-13]]

^<<v26-36-13,13>>^ — Assim diz o Senhor  Deus: "Visto que lhe dizem: ‘Você é uma terra que devora as pessoas, uma terra que deixa o povo sem filhos’,

[[v26-36-14]]

^<<v26-36-14,14>>^ certamente você não devorará mais as pessoas nem privará o seu povo dos seus filhos, diz o Senhor  Deus.

[[v26-36-15]]

^<<v26-36-15,15>>^ Não permitirei mais que você ouça a zombaria das nações ou tenha de suportar a vergonha dos povos. Nunca mais você deixará o seu povo sem os seus filhos", diz o Senhor  Deus.

[[v26-36-16]]

^<<v26-36-16,16>>^ A palavra do Senhor  veio a mim, dizendo:

[[v26-36-17]]

^<<v26-36-17,17>>^ — Filho do homem, quando os da casa de Israel moravam na sua terra, eles a contaminaram com os seus caminhos e as suas ações. Aos meus olhos, o caminho deles era como a impureza da menstruação.

[[v26-36-18]]

^<<v26-36-18,18>>^ Por isso, derramei o meu furor sobre eles, por causa do sangue que derramaram sobre a terra e por causa dos seus ídolos com que a contaminaram.

[[v26-36-19]]

^<<v26-36-19,19>>^ Eu os dispersei entre as nações, e foram espalhados por outras terras; segundo os seus caminhos e segundo as suas ações, eu os castiguei.

[[v26-36-20]]

^<<v26-36-20,20>>^ Quando chegaram às nações para onde foram, profanaram o meu santo nome, pois deles se dizia: "Esse é o povo do Senhor , mas eles tiveram de sair da terra dele."

[[v26-36-21]]

^<<v26-36-21,21>>^ Mas eu tratei de proteger o meu santo nome, que a casa de Israel profanou entre as nações para onde foi.

[[v26-36-22]]

^<<v26-36-22,22>>^ — Portanto, diga à casa de Israel: Assim diz o Senhor  Deus: "Não é por causa de vocês que eu faço isto, ó casa de Israel, mas pelo meu santo nome, que vocês profanaram entre as nações para onde foram.

[[v26-36-23]]

^<<v26-36-23,23>>^ Revelarei a santidade do meu grande nome, que foi profanado entre as nações, o qual vocês profanaram no meio delas. As nações saberão que eu sou o Senhor , diz o Senhor  Deus, quando eu manifestar a minha santidade diante delas por meio de vocês.

[[v26-36-24]]

^<<v26-36-24,24>>^ Eu os tirarei do meio das nações, eu os congregarei de todos os países e os trarei de volta para a sua própria terra.

[[v26-36-25]]

^<<v26-36-25,25>>^ Então aspergirei água pura sobre vocês, e vocês ficarão purificados. Eu os purificarei de todas as suas impurezas e de todos os seus ídolos.

[[v26-36-26]]

^<<v26-36-26,26>>^ Eu lhes darei um coração novo e porei dentro de vocês um espírito novo. Tirarei de vocês o coração de pedra e lhes darei um coração de carne.

[[v26-36-27]]

^<<v26-36-27,27>>^ Porei dentro de vocês o meu Espírito e farei com que andem nos meus estatutos, guardem e observem os meus juízos.

[[v26-36-28]]

^<<v26-36-28,28>>^ Vocês habitarão na terra que eu dei aos seus pais. Vocês serão o meu povo, e eu serei o seu Deus.

[[v26-36-29]]

^<<v26-36-29,29>>^ Eu os livrarei de todas as suas impurezas. Farei vir o trigo, e o multiplicarei, e não trarei fome sobre vocês.

[[v26-36-30]]

^<<v26-36-30,30>>^ Multiplicarei os frutos das árvores e as colheitas do campo, para que vocês nunca mais passem vergonha entre as nações por causa da fome.

[[v26-36-31]]

^<<v26-36-31,31>>^ Então vocês se lembrarão dos seus maus caminhos e das suas ações que não foram boas, e terão nojo de vocês mesmos por causa das suas iniquidades e das suas abominações.

[[v26-36-32]]

^<<v26-36-32,32>>^ Não é por causa de vocês, fique bem-entendido, que eu faço isto, diz o Senhor  Deus. Fiquem envergonhados e confusos por causa dos seus caminhos, ó casa de Israel."

[[v26-36-33]]

^<<v26-36-33,33>>^ — Assim diz o Senhor  Deus: No dia em que eu os purificar de todas as suas iniquidades, então farei com que as cidades sejam habitadas e as ruínas sejam reconstruídas.

[[v26-36-34]]

^<<v26-36-34,34>>^ A terra que estava abandonada será cultivada e deixará de ser um lugar abandonado aos olhos de todos os que passam.

[[v26-36-35]]

^<<v26-36-35,35>>^ Então se dirá: "Esta terra abandonada ficou como o jardim do Éden. As cidades que estavam desertas, abandonadas e em ruínas estão fortificadas e habitadas."

[[v26-36-36]]

^<<v26-36-36,36>>^ Então as nações que tiverem restado ao redor de vocês saberão que eu, o Senhor , reconstruí as cidades destruídas e replantei o que estava abandonado. Eu, o Senhor , falei e eu o cumprirei.

[[v26-36-37]]

^<<v26-36-37,37>>^ — Assim diz o Senhor  Deus: Deixarei que a casa de Israel peça que eu lhe faça ainda isto: que eu aumente o número de pessoas como se fosse um rebanho.

[[v26-36-38]]

^<<v26-36-38,38>>^ Como os rebanhos consagrados para os sacrifícios, os rebanhos de Jerusalém nas suas festas fixas, assim as cidades desertas se encherão de rebanhos de pessoas. E eles saberão que eu sou o Senhor .

'''

xref:026-ezequiel/026-ezequiel-035.adoc#v26-35-0[&#60; Capítulo Anterior] | <<v26-36-0,Topo>> | xref:026-ezequiel/026-ezequiel-037.adoc#v26-37-0[Próximo Capítulo &#62;]