include::./index.adoc[]

[[v26-16-0]]
=== Ezequiel, 16
// naa ?, NAA - Nova Almeida Atualizada

[[v26-16-1]]

^<<v26-16-1,1>>^ A palavra do Senhor  veio a mim, dizendo:

[[v26-16-2]]

^<<v26-16-2,2>>^ — Filho do homem, mostre a Jerusalém as suas abominações

[[v26-16-3]]

^<<v26-16-3,3>>^ e diga-lhe: Assim diz o Senhor  Deus a Jerusalém: — "Quanto à sua origem e ao seu nascimento, você procede da terra dos cananeus. O seu pai era amorreu, e a sua mãe era heteia.

[[v26-16-4]]

^<<v26-16-4,4>>^ Quanto ao seu nascimento, no dia em que você nasceu, não lhe cortaram o cordão umbilical, nem a lavaram com água para que ficasse limpa, nem a esfregaram com sal, nem a enrolaram em panos.

[[v26-16-5]]

^<<v26-16-5,5>>^ Ninguém olhou para você com piedade, para lhe fazer qualquer dessas coisas, compadecendo-se de você. Pelo contrário, no dia em que nasceu, você foi jogada em campo aberto, porque tiveram nojo de você."

[[v26-16-6]]

^<<v26-16-6,6>>^ — "Quando passei por perto e vi que você se revolvia no seu sangue, eu lhe disse: ‘Ainda que você esteja coberta de sangue, fique viva! Sim, ainda que você esteja coberta de sangue, fique viva!’

[[v26-16-7]]

^<<v26-16-7,7>>^ Eu a fiz crescer como uma planta do campo. Você cresceu, se desenvolveu e ficou muito bonita. Os seus seios tomaram forma, os cabelos cresceram, mas você estava completamente nua."

[[v26-16-8]]

^<<v26-16-8,8>>^ — "Quando passei de novo por perto e olhei para você, eis que você tinha chegado à idade do amor. Estendi sobre você as abas do meu manto e cobri a sua nudez. Fiz um juramento e entrei em aliança com você, diz o Senhor  Deus; e você passou a ser minha."

[[v26-16-9]]

^<<v26-16-9,9>>^ — "Então eu a lavei com água, limpei o sangue que a cobria e a ungi com óleo.

[[v26-16-10]]

^<<v26-16-10,10>>^ Também a vesti com roupas bordadas e lhe dei sandálias feitas com couro da melhor qualidade; eu a cingi de linho fino e a cobri de seda.

[[v26-16-11]]

^<<v26-16-11,11>>^ Também a enfeitei com joias: braceletes nas mãos e um colar no pescoço.

[[v26-16-12]]

^<<v26-16-12,12>>^ Coloquei um pendente em seu nariz, brincos nas orelhas e uma linda coroa na cabeça.

[[v26-16-13]]

^<<v26-16-13,13>>^ Assim, você foi enfeitada com ouro e prata; as suas roupas eram de linho fino, de seda e de bordados. Você se alimentou da melhor farinha, de mel e azeite; você era muito bonita e chegou a ser rainha.

[[v26-16-14]]

^<<v26-16-14,14>>^ A sua fama correu entre as nações, por causa da sua beleza, pois você era perfeita, por causa do meu esplendor que eu tinha posto sobre você, diz o Senhor  Deus."

[[v26-16-15]]

^<<v26-16-15,15>>^ — "Mas você confiou em sua beleza, e a sua fama fez com que você se prostituísse; e você se ofereceu a todos os que passavam, para ser deles.

[[v26-16-16]]

^<<v26-16-16,16>>^ Você pegou algumas de suas roupas e fez para si lugares altos enfeitados de diversas cores, nos quais você se prostituiu. Nunca antes havia acontecido algo assim, e jamais voltará a acontecer.

[[v26-16-17]]

^<<v26-16-17,17>>^ Você pegou as suas belas joias, feitas com o ouro e a prata que eu lhe tinha dado, e fez para si imagens de homens, com as quais você se prostituiu.

[[v26-16-18]]

^<<v26-16-18,18>>^ Você pegou os seus vestidos bordados e com eles cobriu as imagens; o meu óleo e o meu perfume você pôs diante delas.

[[v26-16-19]]

^<<v26-16-19,19>>^ A comida que eu lhe dei — a melhor farinha, o óleo e o mel, com que eu a sustentava — você também pôs diante delas em aroma agradável; e assim se fez, diz o Senhor  Deus."

[[v26-16-20]]

^<<v26-16-20,20>>^ — "Além disso, você pegou os filhos e as filhas que teve comigo e os sacrificou às imagens, para serem consumidos. Como se não bastasse essa sua prostituição,

[[v26-16-21]]

^<<v26-16-21,21>>^ você matou os meus filhos e os entregou a essas imagens como oferta pelo fogo.

[[v26-16-22]]

^<<v26-16-22,22>>^ Em todas as suas abominações e nas suas prostituições, você não se lembrou dos dias da sua mocidade, quando você estava completamente nua, revolvendo-se no seu sangue."

[[v26-16-23]]

^<<v26-16-23,23>>^ — "Depois de toda a sua maldade — ‘Ai! Ai de você!’, diz o Senhor  Deus —,

[[v26-16-24]]

^<<v26-16-24,24>>^ você construiu altares e um lugar elevado em cada praça.

[[v26-16-25]]

^<<v26-16-25,25>>^ Na entrada de todos os caminhos, você construiu um lugar elevado, profanou a sua beleza, se ofereceu a todos os que passavam e multiplicou as suas prostituições.

[[v26-16-26]]

^<<v26-16-26,26>>^ Você também se prostituiu com os filhos do Egito, seus vizinhos de membros avantajados, e multiplicou a sua prostituição, para me provocar à ira."

[[v26-16-27]]

^<<v26-16-27,27>>^ — "Por isso, estendi a mão contra você, diminuí o seu território e a entreguei à vontade daquelas que a odeiam, as filhas dos filisteus, que se envergonhavam da conduta depravada de vocês.

[[v26-16-28]]

^<<v26-16-28,28>>^ E, por ser insaciável, você também se prostituiu com os filhos da Assíria. E, prostituindo-se com eles, nem assim ficou satisfeita;

[[v26-16-29]]

^<<v26-16-29,29>>^ pelo contrário, você estendeu as suas prostituições até a Caldeia, essa terra de negociantes, mas nem com isso ficou satisfeita."

[[v26-16-30]]

^<<v26-16-30,30>>^ — "Como é fraco o seu coração, diz o Senhor  Deus, pois você faz todas estas coisas que são próprias de uma prostituta descarada.

[[v26-16-31]]

^<<v26-16-31,31>>^ Construindo os seus altares na entrada de todos os caminhos e o seu lugar elevado em cada praça, você não foi como a prostituta, porque desprezou o pagamento.

[[v26-16-32]]

^<<v26-16-32,32>>^ Você foi como a mulher adúltera, que, em lugar de seu marido, recebe os estranhos.

[[v26-16-33]]

^<<v26-16-33,33>>^ Todas as prostitutas recebem pagamento, mas você dá presentes a todos os seus amantes. Você faz isso para que venham de todas as partes adulterar com você.

[[v26-16-34]]

^<<v26-16-34,34>>^ Com você, na sua vida de prostituta, acontece o contrário do que se dá com outras mulheres. Ninguém pede que você se prostitua. Você faz o pagamento, e ninguém paga nada a você. Nisso você é diferente!"

[[v26-16-35]]

^<<v26-16-35,35>>^ — "Portanto, prostituta, ouça a palavra do Senhor .

[[v26-16-36]]

^<<v26-16-36,36>>^ Assim diz o Senhor  Deus: Por você ter derramado o seu dinheiro e deixado à mostra a sua nudez nas suas prostituições com os seus amantes; por causa também de todos os seus ídolos abomináveis e do sangue de seus filhos que você ofereceu a esses ídolos,

[[v26-16-37]]

^<<v26-16-37,37>>^ eis que reunirei todos os amantes que você quis agradar, tanto os que você amava como todos os que você odiava. Eu os trarei contra você de todos os lados e descobrirei as suas vergonhas diante deles, para que eles vejam toda a sua nudez.

[[v26-16-38]]

^<<v26-16-38,38>>^ Eu a julgarei como são julgadas as adúlteras e as assassinas; farei com que você seja vítima de furor e de ciúme.

[[v26-16-39]]

^<<v26-16-39,39>>^ Vou entregá-la nas mãos deles, e eles derrubarão os seus altares e lugares elevados. Vão despir você, levar as suas belas joias, e a deixarão completamente nua.

[[v26-16-40]]

^<<v26-16-40,40>>^ Trarão contra você uma multidão, irão apedrejá-la e a cortarão em pedaços com as suas espadas.

[[v26-16-41]]

^<<v26-16-41,41>>^ Queimarão as suas casas e executarão juízos contra você, à vista de muitas mulheres. Acabarei com a sua prostituição, e você não fará mais nenhum pagamento.

[[v26-16-42]]

^<<v26-16-42,42>>^ Desse modo, desafogarei em você o meu furor e deixarei de ter ciúmes de você. Estarei calmo e não ficarei mais irado.

[[v26-16-43]]

^<<v26-16-43,43>>^ Visto que você não se lembrou dos dias da sua mocidade e me provocou à ira com todas essas coisas, eis que também eu farei recair sobre a sua cabeça o castigo que os seus atos merecem, diz o Senhor  Deus. Não é fato que a todas as suas outras abominações você acrescentou esta depravação?"

[[v26-16-44]]

^<<v26-16-44,44>>^ — "Eis que todos os que usam provérbios usarão contra você o seguinte: ‘Tal mãe, tal filha.’

[[v26-16-45]]

^<<v26-16-45,45>>^ Você é filha da sua mãe, que teve nojo de seu marido e de seus filhos. E você é irmã das suas irmãs, que tiveram nojo de seus maridos e de seus filhos. A mãe de vocês era heteia, e o pai era amorreu."

[[v26-16-46]]

^<<v26-16-46,46>>^ — "A sua irmã mais velha é Samaria, que mora ao norte de você com as suas filhas; e a sua irmã mais nova, que mora ao sul de você, é Sodoma com as suas filhas.

[[v26-16-47]]

^<<v26-16-47,47>>^ Você andou nos mesmos caminhos em que elas andaram e fez as mesmas abominações que elas fizeram. E, como se isto não fosse o bastante, você ainda se corrompeu mais do que elas, em todos os seus caminhos.

[[v26-16-48]]

^<<v26-16-48,48>>^ Tão certo como eu vivo, diz o Senhor  Deus, a sua irmã Sodoma e as filhas dela não fizeram o que você e as suas filhas fizeram.

[[v26-16-49]]

^<<v26-16-49,49>>^ Eis que esta foi a iniquidade de sua irmã Sodoma: ela e as suas filhas foram orgulhosas, tiveram fartura de pão e próspera tranquilidade, mas nunca ampararam os pobres e os necessitados.

[[v26-16-50]]

^<<v26-16-50,50>>^ Foram arrogantes e fizeram abominações diante de mim. Ao ver isso, eu as removi daquele lugar.

[[v26-16-51]]

^<<v26-16-51,51>>^ Também Samaria não cometeu metade dos pecados que você cometeu. Você multiplicou as suas abominações mais do que elas e assim, com todas essas suas abominações, fez com que as suas irmãs parecessem mais justas do que são.

[[v26-16-52]]

^<<v26-16-52,52>>^ Agora, pois, suporte a sua humilhação, você que advogou a causa de suas irmãs. Diante dos pecados que você cometeu, que são mais abomináveis do que os pecados que elas cometeram, elas são mais justas do que você. Portanto, envergonhe-se e suporte a sua humilhação, pois você fez as suas irmãs parecerem mais justas do que você."

[[v26-16-53]]

^<<v26-16-53,53>>^ — "Restaurarei a sorte delas — a de Sodoma e de suas filhas e a de Samaria e de suas filhas — e restaurarei também a sua sorte entre elas,

[[v26-16-54]]

^<<v26-16-54,54>>^ para que você suporte a sua humilhação e seja envergonhada por tudo o que você fez, servindo-lhes de consolo.

[[v26-16-55]]

^<<v26-16-55,55>>^ Quando as suas irmãs, Sodoma com as suas filhas e Samaria com as suas filhas, voltarem ao seu primeiro estado, também você e as suas filhas voltarão ao seu primeiro estado.

[[v26-16-56]]

^<<v26-16-56,56>>^ Não é fato que, nos dias do seu orgulho, você usou o nome de sua irmã Sodoma como provérbio,

[[v26-16-57]]

^<<v26-16-57,57>>^ antes que se descobrissem as maldades que você fazia? Agora você se tornou, como ela, objeto de zombaria das filhas da Síria e de todos os que estão ao redor dela, as filhas dos filisteus que a desprezam.

[[v26-16-58]]

^<<v26-16-58,58>>^ Você terá de sofrer as consequências da perversidade e das abominações que você praticou, diz o Senhor ."

[[v26-16-59]]

^<<v26-16-59,59>>^ — Porque assim diz o Senhor  Deus: "Eu farei com você o mesmo que você fez, pois você desprezou o juramento e quebrou a aliança.

[[v26-16-60]]

^<<v26-16-60,60>>^ Mas eu me lembrarei da aliança que fiz com você nos dias da sua mocidade e com você estabelecerei uma aliança eterna.

[[v26-16-61]]

^<<v26-16-61,61>>^ Então você se lembrará dos seus caminhos e ficará envergonhada quando receber as suas irmãs, tanto as mais velhas como as mais novas. Eu as darei a você por filhas, mas não pela sua aliança.

[[v26-16-62]]

^<<v26-16-62,62>>^ Estabelecerei a minha aliança com você, e você saberá que eu sou o Senhor ,

[[v26-16-63]]

^<<v26-16-63,63>>^ para que você se lembre e fique envergonhada, e nunca mais abra a sua boca por causa da sua humilhação, quando eu lhe houver perdoado tudo o que você fez", diz o Senhor  Deus.

'''

xref:026-ezequiel/026-ezequiel-015.adoc#v26-15-0[&#60; Capítulo Anterior] | <<v26-16-0,Topo>> | xref:026-ezequiel/026-ezequiel-017.adoc#v26-17-0[Próximo Capítulo &#62;]