include::./index.adoc[]

[[v26-25-0]]
=== Ezequiel, 25
// naa ?, NAA - Nova Almeida Atualizada

[[v26-25-1]]

^<<v26-25-1,1>>^ A palavra do Senhor  veio a mim, dizendo:

[[v26-25-2]]

^<<v26-25-2,2>>^ — Filho do homem, vire o seu rosto contra os filhos de Amom e profetize contra eles.

[[v26-25-3]]

^<<v26-25-3,3>>^ Diga aos filhos de Amom: "Ouçam a palavra do Senhor  Deus! Assim diz o Senhor  Deus: Visto que vocês disseram: ‘Bem feito!’, quando o meu santuário foi profanado, quando a terra de Israel foi arrasada e quando a casa de Judá foi levada para o exílio,

[[v26-25-4]]

^<<v26-25-4,4>>^ eis que eu os entregarei ao poder dos filhos do Oriente, que estabelecerão os seus acampamentos no meio de vocês e ficarão morando aí. Eles comerão as frutas e beberão o leite de vocês.

[[v26-25-5]]

^<<v26-25-5,5>>^ Farei de Rabá uma estrebaria de camelos e dos filhos de Amom, um curral de ovelhas; e vocês saberão que eu sou o Senhor ."

[[v26-25-6]]

^<<v26-25-6,6>>^ — Porque assim diz o Senhor  Deus: "Visto que vocês bateram palmas, pularam de alegria e, com o mais profundo desprezo, se alegraram por causa da terra de Israel,

[[v26-25-7]]

^<<v26-25-7,7>>^ eis que estenderei a minha mão contra vocês e os darei por despojo às nações. Eu os eliminarei do meio das nações e os farei perecer do meio dos povos. Acabarei com vocês, e vocês saberão que eu sou o Senhor ."

[[v26-25-8]]

^<<v26-25-8,8>>^ — Assim diz o Senhor  Deus: Visto que Moabe e Seir dizem: "A casa de Judá é como qualquer outra nação",

[[v26-25-9]]

^<<v26-25-9,9>>^ eis que abrirei o flanco de Moabe, começando pelas cidades, sim, pelas cidades da fronteira, a glória daquela terra, Bete-Jesimote, Baal-Meom e Quiriataim.

[[v26-25-10]]

^<<v26-25-10,10>>^ Eu as darei aos povos do Oriente como propriedade, juntamente com os filhos de Amom, para que destes não haja memória entre as nações.

[[v26-25-11]]

^<<v26-25-11,11>>^ Também executarei juízos contra Moabe, e os moabitas saberão que eu sou o Senhor .

[[v26-25-12]]

^<<v26-25-12,12>>^ — Assim diz o Senhor  Deus: Visto que Edom se mostrou vingativo para com a casa de Judá e se fez culpado ao extremo, quando se vingou dela,

[[v26-25-13]]

^<<v26-25-13,13>>^ assim diz o Senhor  Deus: Também estenderei a mão contra Edom e eliminarei dele pessoas e animais. Farei de Edom um deserto, e desde Temã até Dedã cairão à espada.

[[v26-25-14]]

^<<v26-25-14,14>>^ Exercerei a minha vingança contra Edom, por meio do meu povo de Israel, que fará em Edom segundo a minha ira e segundo o meu furor. E os edomitas conhecerão a minha vingança, diz o Senhor  Deus.

[[v26-25-15]]

^<<v26-25-15,15>>^ — Assim diz o Senhor  Deus: Visto que os filisteus se mostraram vingativos e com profundo desprezo executaram vingança, para destruírem com inimizade sem fim,

[[v26-25-16]]

^<<v26-25-16,16>>^ assim diz o Senhor  Deus: Eis que eu estenderei a minha mão contra os filisteus, eliminarei os queretitas e destruirei o resto da costa do mar.

[[v26-25-17]]

^<<v26-25-17,17>>^ Tomarei deles grandes vinganças, com furiosas repreensões. E saberão que eu sou o Senhor , quando eu tiver exercido a minha vingança contra eles.

'''

xref:026-ezequiel/026-ezequiel-024.adoc#v26-24-0[&#60; Capítulo Anterior] | <<v26-25-0,Topo>> | xref:026-ezequiel/026-ezequiel-026.adoc#v26-26-0[Próximo Capítulo &#62;]