include::./index.adoc[]

[[v26-34-0]]
=== Ezequiel, 34
// naa ?, NAA - Nova Almeida Atualizada

[[v26-34-1]]

^<<v26-34-1,1>>^ A palavra do Senhor  veio a mim, dizendo:

[[v26-34-2]]

^<<v26-34-2,2>>^ — Filho do homem, profetize contra os pastores de Israel; profetize e diga-lhes: Assim diz o Senhor  Deus: "Ai dos pastores de Israel que apascentam a si mesmos! Será que os pastores não deveriam apascentar as ovelhas?

[[v26-34-3]]

^<<v26-34-3,3>>^ Vocês comem a gordura, vestem-se da lã e matam as melhores ovelhas para comer, mas não apascentam o rebanho.

[[v26-34-4]]

^<<v26-34-4,4>>^ Vocês não fortaleceram as fracas, não curaram as doentes, não enfaixaram as quebradas, não trouxeram de volta as desgarradas e não buscaram as perdidas, mas dominam sobre elas com força e tirania.

[[v26-34-5]]

^<<v26-34-5,5>>^ Assim, elas se espalharam, por não haver pastor, e se tornaram pasto para todos os animais selvagens.

[[v26-34-6]]

^<<v26-34-6,6>>^ As minhas ovelhas andam desgarradas por todos os montes e por todas as colinas. As minhas ovelhas andam espalhadas por toda a terra, sem haver quem as procure ou quem as busque."

[[v26-34-7]]

^<<v26-34-7,7>>^ — Por isso, pastores, ouçam a palavra do Senhor :

[[v26-34-8]]

^<<v26-34-8,8>>^ Tão certo como eu vivo, diz o Senhor  Deus, visto que as minhas ovelhas foram entregues à rapina e se tornaram pasto para todos os animais selvagens, por não haver pastor, e que os meus pastores não procuram as minhas ovelhas, pois apascentam a si mesmos e não apascentam as minhas ovelhas,

[[v26-34-9]]

^<<v26-34-9,9>>^ por isso, pastores, ouçam a palavra do Senhor :

[[v26-34-10]]

^<<v26-34-10,10>>^ Assim diz o Senhor  Deus: Eis que estou contra os pastores e lhes pedirei contas das minhas ovelhas. Farei com que deixem de apascentar ovelhas, e não apascentarão mais a si mesmos. Livrarei as minhas ovelhas da sua boca, para que já não lhes sirvam de comida.

[[v26-34-11]]

^<<v26-34-11,11>>^ — Porque assim diz o Senhor  Deus: Eis que eu mesmo procurarei as minhas ovelhas e as buscarei.

[[v26-34-12]]

^<<v26-34-12,12>>^ Como o pastor busca o seu rebanho, no dia em que encontra ovelhas dispersas, assim buscarei as minhas ovelhas. Eu as livrarei de todos os lugares por onde foram espalhadas no dia de nuvens e densas trevas.

[[v26-34-13]]

^<<v26-34-13,13>>^ Vou tirá-las do meio dos povos, e as congregarei dos diversos países, e as trarei de volta à sua terra. Vou apascentá-las nos montes de Israel, junto às correntes de água e em todos os lugares habitados da terra.

[[v26-34-14]]

^<<v26-34-14,14>>^ Deixarei que pastem em bons pastos, e nos altos montes de Israel será a sua pastagem. Ali elas se deitarão em boa pastagem e terão pastos bons nos montes de Israel.

[[v26-34-15]]

^<<v26-34-15,15>>^ Eu mesmo apascentarei as minhas ovelhas e as farei repousar, diz o Senhor  Deus.

[[v26-34-16]]

^<<v26-34-16,16>>^ Buscarei as perdidas, trarei de volta as desgarradas, enfaixarei as quebradas e curarei as doentes; mas destruirei as gordas e fortes. Eu as apascentarei com justiça.

[[v26-34-17]]

^<<v26-34-17,17>>^ — Quanto a vocês, minhas ovelhas, assim diz o Senhor  Deus: "Eis que julgarei entre ovelhas e ovelhas, entre carneiros e bodes.

[[v26-34-18]]

^<<v26-34-18,18>>^ Será que não lhes basta a boa pastagem? Ainda precisam pisar aos pés o resto do seu pasto? E não lhes basta o fato de terem bebido a água limpa? Ainda precisam turvar o resto com os pés?

[[v26-34-19]]

^<<v26-34-19,19>>^ As minhas ovelhas têm de comer o que vocês pisaram com os pés e beber o que vocês turvaram com os pés."

[[v26-34-20]]

^<<v26-34-20,20>>^ — Por isso, assim lhes diz o Senhor  Deus: "Eis que eu mesmo julgarei entre ovelhas gordas e ovelhas magras.

[[v26-34-21]]

^<<v26-34-21,21>>^ Visto que, com o lado e com o ombro, vocês dão empurrões e, com os chifres, rechaçam todas as ovelhas fracas até que as tenham espalhado por toda parte,

[[v26-34-22]]

^<<v26-34-22,22>>^ eu livrarei as minhas ovelhas, para que não mais sirvam de rapina, e julgarei entre ovelhas e ovelhas.

[[v26-34-23]]

^<<v26-34-23,23>>^ Porei sobre elas um só pastor, e ele as apascentará: o meu servo Davi. Ele as apascentará e será o seu pastor.

[[v26-34-24]]

^<<v26-34-24,24>>^ Eu, o Senhor , serei o seu Deus, e o meu servo Davi será príncipe no meio delas. Eu, o Senhor , falei."

[[v26-34-25]]

^<<v26-34-25,25>>^ — Farei uma aliança de paz com as minhas ovelhas. Livrarei a terra de animais selvagens, para que as minhas ovelhas vivam em segurança no deserto e durmam nos bosques.

[[v26-34-26]]

^<<v26-34-26,26>>^ Delas e dos lugares ao redor do meu monte, eu farei uma bênção. Farei descer a chuva a seu tempo; serão chuvas de bênção.

[[v26-34-27]]

^<<v26-34-27,27>>^ As árvores do campo darão o seu fruto, e a terra dará as suas colheitas. As ovelhas estarão seguras na sua terra e saberão que eu sou o Senhor , quando eu quebrar o jugo que pesava sobre elas e as livrar das mãos dos que as escravizavam.

[[v26-34-28]]

^<<v26-34-28,28>>^ Já não servirão de rapina aos gentios, nem serão devoradas por animais selvagens. Viverão em segurança, e não haverá quem as espante.

[[v26-34-29]]

^<<v26-34-29,29>>^ Eu lhes darei plantação memorável, e nunca mais serão vítimas de fome na terra, nem terão de suportar a zombaria das outras nações.

[[v26-34-30]]

^<<v26-34-30,30>>^ Saberão que eu, o Senhor , seu Deus, estou com elas e que elas são o meu povo, a casa de Israel, diz o Senhor  Deus.

[[v26-34-31]]

^<<v26-34-31,31>>^ — "Vocês são as minhas ovelhas, ovelhas do meu pasto. Vocês são o meu povo, e eu sou o seu Deus", diz o Senhor  Deus.

'''

xref:026-ezequiel/026-ezequiel-033.adoc#v26-33-0[&#60; Capítulo Anterior] | <<v26-34-0,Topo>> | xref:026-ezequiel/026-ezequiel-035.adoc#v26-35-0[Próximo Capítulo &#62;]