include::./index.adoc[]

[[v26-7-0]]
=== Ezequiel, 7
// naa ?, NAA - Nova Almeida Atualizada

[[v26-7-1]]

^<<v26-7-1,1>>^ A palavra do Senhor  veio a mim, dizendo:

[[v26-7-2]]

^<<v26-7-2,2>>^ — Filho do homem, assim diz o Senhor  Deus a respeito da terra de Israel: "Chegou o fim! O fim chegou sobre os quatro cantos da terra.

[[v26-7-3]]

^<<v26-7-3,3>>^ Agora o fim chegou sobre você, povo de Israel. Enviarei a minha ira sobre vocês. Eu os julgarei segundo os seus caminhos e farei cair sobre vocês todas as suas abominações.

[[v26-7-4]]

^<<v26-7-4,4>>^ Os meus olhos não terão piedade, e eu não os pouparei. Pelo contrário, eu darei o que vocês merecem por seus atos, e farei com que paguem por todas as suas abominações. E vocês saberão que eu sou o Senhor ."

[[v26-7-5]]

^<<v26-7-5,5>>^ — Assim diz o Senhor  Deus: "Calamidade após calamidade, eis que vêm.

[[v26-7-6]]

^<<v26-7-6,6>>^ Chegou o fim! O fim chegou, já despertou contra você!

[[v26-7-7]]

^<<v26-7-7,7>>^ A sua sentença chegou, ó morador desta terra. Chegou a hora. O dia está próximo, dia de tumulto, e não de alegria, sobre os montes.

[[v26-7-8]]

^<<v26-7-8,8>>^ Agora, em breve, derramarei o meu furor sobre você, cumprirei a minha ira contra você. Eu os castigarei segundo os seus caminhos e os farei pagar por todas as suas abominações.

[[v26-7-9]]

^<<v26-7-9,9>>^ Os meus olhos não terão piedade, e eu não os pouparei. Segundo os seus caminhos, assim os castigarei, e os farei pagar por suas abominações. E vocês saberão que eu, o Senhor , sou o que castiga."

[[v26-7-10]]

^<<v26-7-10,10>>^ "Eis o dia! Eis que chegou! Brotou a sentença, já floresceu a vara, reverdeceu a arrogância.

[[v26-7-11]]

^<<v26-7-11,11>>^ A violência se ergueu para servir de vara de maldade. Nada restará deles, nem da sua multidão, nem da sua riqueza, nem da sua glória.

[[v26-7-12]]

^<<v26-7-12,12>>^ Chegou a hora, o dia está próximo. Quem compra não se alegre, e quem vende não se entristeça, porque a ira cairá sobre todos eles.

[[v26-7-13]]

^<<v26-7-13,13>>^ Porque o vendedor não tornará a possuir aquilo que vendeu, por mais que viva. Porque a profecia contra todos eles não será revogada, e, por causa da própria maldade, ninguém preservará a vida."

[[v26-7-14]]

^<<v26-7-14,14>>^ "Tocaram a trombeta e prepararam tudo, mas ninguém vai à batalha, porque a minha ira cairá sobre todos eles.

[[v26-7-15]]

^<<v26-7-15,15>>^ Fora está a espada; dentro, a peste e a fome. Quem está no campo morre à espada, e quem está na cidade, a fome e a peste o consomem.

[[v26-7-16]]

^<<v26-7-16,16>>^ Se alguns deles, fugindo, escaparem, estarão pelos montes, como pombas dos vales, todos gemendo, cada um por causa da sua maldade.

[[v26-7-17]]

^<<v26-7-17,17>>^ Todas as mãos desfalecerão, e todos os joelhos se desfarão em água.

[[v26-7-18]]

^<<v26-7-18,18>>^ Vestirão roupa feita de pano de saco, e o terror tomará conta deles. Todos os rostos ficarão cobertos de vergonha, e todas as cabeças serão rapadas.

[[v26-7-19]]

^<<v26-7-19,19>>^ Jogarão a sua prata nas ruas, e o seu ouro será tratado como se fosse sujeira. Nem a sua prata nem o seu ouro poderão livrá-los no dia da ira do Senhor ; eles não saciarão a sua fome, nem lhes encherão o estômago, porque a prata e o ouro foram o tropeço que os levou a cair em iniquidade.

[[v26-7-20]]

^<<v26-7-20,20>>^ Dessas preciosas joias fizeram seu objeto de orgulho e fabricaram as suas abomináveis imagens e seus ídolos detestáveis. Por isso, fiz com que essas coisas se tornassem como sujeira para eles."

[[v26-7-21]]

^<<v26-7-21,21>>^ "Entregarei tudo isso nas mãos de estrangeiros, por presa, e aos ímpios da terra, por despojo; eles o profanarão.

[[v26-7-22]]

^<<v26-7-22,22>>^ Desviarei deles o rosto, e profanarão o meu tesouro; ladrões entrarão nele e o profanarão."

[[v26-7-23]]

^<<v26-7-23,23>>^ "Prepare uma corrente, porque a terra está cheia de crimes de sangue, e a cidade, cheia de violência.

[[v26-7-24]]

^<<v26-7-24,24>>^ Trarei aqui as piores nações, que tomarão posse das casas deles. Farei cessar a arrogância dos valentes, e os seus lugares santos serão profanados.

[[v26-7-25]]

^<<v26-7-25,25>>^ A destruição está a caminho! Eles buscarão paz, mas não haverá paz.

[[v26-7-26]]

^<<v26-7-26,26>>^ Virá miséria sobre miséria, e um rumor após o outro. Buscarão visões de profetas; do sacerdote perecerá a lei, e dos anciãos, o conselho.

[[v26-7-27]]

^<<v26-7-27,27>>^ O rei estará de luto, o príncipe se vestirá de horror, e as mãos do povo da terra tremerão de medo. Vou tratá-los segundo a sua conduta, e os julgarei pelos seus próprios critérios. E eles saberão que eu sou o Senhor ."

'''

xref:026-ezequiel/026-ezequiel-006.adoc#v26-6-0[&#60; Capítulo Anterior] | <<v26-7-0,Topo>> | xref:026-ezequiel/026-ezequiel-008.adoc#v26-8-0[Próximo Capítulo &#62;]