include::./index.adoc[]

[[v26-26-0]]
=== Ezequiel, 26
// naa ?, NAA - Nova Almeida Atualizada

[[v26-26-1]]

^<<v26-26-1,1>>^ No décimo primeiro ano, no primeiro dia do mês, a palavra do Senhor  veio a mim, dizendo:

[[v26-26-2]]

^<<v26-26-2,2>>^ — Filho do homem, Tiro disse a respeito de Jerusalém: "Bem feito! Foi arrombada a porta dos povos; ela se abriu para mim. Eu me tornarei rico, agora que ela foi arrasada."

[[v26-26-3]]

^<<v26-26-3,3>>^ Por isso, assim diz o Senhor  Deus: Eis que eu estou contra você, ó Tiro, e farei subir muitas nações contra você, assim como o mar faz subir as suas ondas.

[[v26-26-4]]

^<<v26-26-4,4>>^ Elas destruirão as muralhas de Tiro e derrubarão as suas torres; e eu varrerei o seu pó e farei dela uma rocha escalvada.

[[v26-26-5]]

^<<v26-26-5,5>>^ No meio do mar, ela virá a ser apenas um lugar onde pescadores secam as suas redes, porque eu o anunciei, diz o Senhor  Deus. E ela se tornará despojo para as nações.

[[v26-26-6]]

^<<v26-26-6,6>>^ Suas filhas que estão no continente serão mortas à espada; e saberão que eu sou o Senhor .

[[v26-26-7]]

^<<v26-26-7,7>>^ — Porque assim diz o Senhor  Deus: Eis que trarei contra Tiro o rei Nabucodonosor, que virá da Babilônia, do Norte, e que é o rei dos reis. Ele virá com cavalos e carros de guerra, com cavaleiros e com um enorme exército.

[[v26-26-8]]

^<<v26-26-8,8>>^ As suas filhas que estão no continente, ele as matará à espada. Construirá torres de ataque e levantará uma rampa contra você; virá com uma barreira de escudos.

[[v26-26-9]]

^<<v26-26-9,9>>^ Disporá os seus aríetes contra as suas muralhas e, com barras de ferro, derrubará as suas torres.

[[v26-26-10]]

^<<v26-26-10,10>>^ Os cavalos dele serão tantos que você ficará coberta de pó. As suas muralhas tremerão com o estrondo dos cavaleiros, das carretas e dos carros de guerra, quando ele entrar pelos seus portões como quem entra numa cidade em que se fez uma brecha na muralha.

[[v26-26-11]]

^<<v26-26-11,11>>^ Com os cascos dos seus cavalos, socará todas as suas ruas. Matará o seu povo à espada, e as suas fortes colunas cairão por terra.

[[v26-26-12]]

^<<v26-26-12,12>>^ Roubarão as suas riquezas e saquearão as suas mercadorias. Derrubarão as suas muralhas e arrasarão as suas casas luxuosas. As suas pedras, a sua madeira e o seu pó eles lançarão no meio das águas.

[[v26-26-13]]

^<<v26-26-13,13>>^ Farei cessar o ruído das suas canções, e não se ouvirá mais o som das suas harpas.

[[v26-26-14]]

^<<v26-26-14,14>>^ Farei de você uma rocha escalvada. Você virá a ser apenas um lugar onde pescadores secam as suas redes. Você jamais será reconstruída, porque eu, o Senhor , falei, diz o Senhor  Deus.

[[v26-26-15]]

^<<v26-26-15,15>>^ — Assim diz o Senhor  Deus a Tiro: "Não é fato que as terras do mar tremerão com o estrondo da sua queda, quando gemerem os feridos, quando se fizer espantosa matança em suas ruas?

[[v26-26-16]]

^<<v26-26-16,16>>^ Todos os príncipes do mar descerão dos seus tronos, tirarão de si os seus mantos e despirão as suas roupas bordadas. Eles se vestirão de tremores, ficarão sentados no chão, tremendo sem parar; e ficarão espantados por causa de você.

[[v26-26-17]]

^<<v26-26-17,17>>^ Farão uma lamentação sobre você, dizendo: ‘Como você está destruída, ó bem-povoada e afamada cidade, que dominava os mares, você e os seus moradores, que atemorizavam todos os que moram ali!

[[v26-26-18]]

^<<v26-26-18,18>>^ Agora as ilhas tremem, no dia da sua queda; as ilhas, que estão no mar, ficam assustadas com a sua ruína.’"

[[v26-26-19]]

^<<v26-26-19,19>>^ — Porque assim diz o Senhor  Deus: "Quando eu fizer de você uma cidade arrasada, como as cidades que não são habitadas, quando eu fizer o abismo vir sobre você e as muitas águas a cobrirem,

[[v26-26-20]]

^<<v26-26-20,20>>^ então farei você descer com os que descem à cova, ao povo antigo. Eu a farei habitar nas partes mais baixas da terra, em lugares desertos antigos, com os que descem à cova, para que você não seja mais habitada; e criarei coisas gloriosas na terra dos viventes.

[[v26-26-21]]

^<<v26-26-21,21>>^ Farei de você um grande espanto, e você deixará de existir; quando a procurarem, você jamais será encontrada", diz o Senhor  Deus.

'''

xref:026-ezequiel/026-ezequiel-025.adoc#v26-25-0[&#60; Capítulo Anterior] | <<v26-26-0,Topo>> | xref:026-ezequiel/026-ezequiel-027.adoc#v26-27-0[Próximo Capítulo &#62;]