include::./index.adoc[]

[[v26-41-0]]
=== Ezequiel, 41
// naa ?, NAA - Nova Almeida Atualizada

[[v26-41-1]]

^<<v26-41-1,1>>^ Então ele me levou ao templo e mediu os pilares, três metros de largura de um lado e três metros de largura do outro, que era a largura do tabernáculo.

[[v26-41-2]]

^<<v26-41-2,2>>^ A largura da entrada era de cinco metros, e as paredes laterais tinham dois metros e meio, uma de cada lado. Também mediu a profundidade da nave, e deu vinte metros; mediu a largura, e deu dez metros.

[[v26-41-3]]

^<<v26-41-3,3>>^ Entrou na parte interior, mediu o pilar da entrada, e deu um metro; mediu a largura da entrada, e deu três metros.

[[v26-41-4]]

^<<v26-41-4,4>>^ Também mediu o seu comprimento, e deu dez metros; mediu a largura, e deu dez metros, na parte frontal da nave. Então ele me disse: — Este é o Santo dos Santos.

[[v26-41-5]]

^<<v26-41-5,5>>^ Depois ele mediu a parede do templo: três metros de espessura. A largura de cada câmara lateral era de dois metros. Essas câmaras ficavam em toda a volta do templo.

[[v26-41-6]]

^<<v26-41-6,6>>^ As câmaras laterais estavam em três andares, câmara sobre câmara, trinta em cada andar. E havia reentrâncias na parede do templo ao redor, para as câmaras laterais, para que as vigas se apoiassem nelas e não fossem introduzidas na parede do templo.

[[v26-41-7]]

^<<v26-41-7,7>>^ As câmaras laterais aumentavam em largura de andar para andar, correspondendo às reentrâncias do templo de andar em andar ao redor; por isso o templo era mais largo em cima. Assim, se subia do andar inferior para o superior, passando pelo andar do meio.

[[v26-41-8]]

^<<v26-41-8,8>>^ E vi um pavimento elevado ao redor do templo; eram os alicerces das câmaras laterais de três metros de altura.

[[v26-41-9]]

^<<v26-41-9,9>>^ A grossura da parede externa das câmaras laterais era de dois metros e meio. A área aberta entre as câmaras laterais do templo

[[v26-41-10]]

^<<v26-41-10,10>>^ e as outras câmaras tinha dez metros de largura por todo o redor do templo.

[[v26-41-11]]

^<<v26-41-11,11>>^ As entradas das câmaras laterais estavam voltadas para a área aberta: uma entrada para o norte e outra para o sul; a largura da área que sobrava era de dois metros e meio ao redor.

[[v26-41-12]]

^<<v26-41-12,12>>^ O edifício que estava numa área separada, do lado oeste, tinha a largura de trinta e cinco metros. A parede do edifício tinha dois metros e meio de espessura ao redor, e o seu comprimento era de quarenta e cinco metros.

[[v26-41-13]]

^<<v26-41-13,13>>^ Então ele mediu o templo: cinquenta metros de comprimento. A área separada, o edifício e as suas paredes também tinham cinquenta metros de comprimento.

[[v26-41-14]]

^<<v26-41-14,14>>^ A largura da frente do templo e da área separada, do lado oeste, era de cinquenta metros.

[[v26-41-15]]

^<<v26-41-15,15>>^ Também mediu o comprimento do edifício, que estava na área separada e por detrás do templo, e as suas galerias em cada lado, e deu cinquenta metros. O templo propriamente dito, o Santíssimo, o vestíbulo do átrio,

[[v26-41-16]]

^<<v26-41-16,16>>^ os umbrais, as janelas estreitas e as galerias ao redor dos três, diante do umbral, estavam cobertos de madeira ao redor, e isto desde o chão até as janelas, que estavam cobertas.

[[v26-41-17]]

^<<v26-41-17,17>>^ No espaço em cima da porta, e até o templo de dentro e de fora, e em toda a parede ao redor, por dentro e por fora, havia obras de escultura,

[[v26-41-18]]

^<<v26-41-18,18>>^ a saber, querubins e palmeiras. Entre um querubim e outro querubim havia uma palmeira. Cada querubim tinha dois rostos:

[[v26-41-19]]

^<<v26-41-19,19>>^ um rosto humano olhava para a palmeira de um lado, e um rosto de leão olhava para a palmeira do outro lado. Era assim por todo o templo ao redor.

[[v26-41-20]]

^<<v26-41-20,20>>^ Desde o chão até acima da entrada havia querubins e palmeiras, até mesmo pela parede do templo.

[[v26-41-21]]

^<<v26-41-21,21>>^ Os batentes do templo eram quadrados, e a entrada do Santo dos Santos tinha a mesma aparência.

[[v26-41-22]]

^<<v26-41-22,22>>^ O altar de madeira tinha um metro e meio de altura, e o seu comprimento era de um metro. Os seus cantos, a sua base e os seus lados eram de madeira. O homem me disse: — Esta é a mesa que está diante do Senhor .

[[v26-41-23]]

^<<v26-41-23,23>>^ Tanto o templo quanto o Santo dos Santos tinham duas portas.

[[v26-41-24]]

^<<v26-41-24,24>>^ Havia duas folhas para as portas, duas folhas dobráveis; duas para cada porta.

[[v26-41-25]]

^<<v26-41-25,25>>^ Nelas, isto é, nas portas do templo, havia querubins e palmeiras, como havia nas paredes. Havia também uma cobertura feita de madeira na frente do vestíbulo por fora.

[[v26-41-26]]

^<<v26-41-26,26>>^ E havia janelas estreitas e palmeiras em ambos os lados do vestíbulo, bem como nas câmaras laterais do templo e na cobertura de madeira.

'''

xref:026-ezequiel/026-ezequiel-040.adoc#v26-40-0[&#60; Capítulo Anterior] | <<v26-41-0,Topo>> | xref:026-ezequiel/026-ezequiel-042.adoc#v26-42-0[Próximo Capítulo &#62;]