include::./index.adoc[]

[[v26-30-0]]
=== Ezequiel, 30
// naa ?, NAA - Nova Almeida Atualizada

[[v26-30-1]]

^<<v26-30-1,1>>^ A palavra do Senhor  veio a mim, dizendo:

[[v26-30-2]]

^<<v26-30-2,2>>^ — Filho do homem, profetize e diga: Assim diz o Senhor  Deus: "Gritem: Ah! Aquele dia!

[[v26-30-3]]

^<<v26-30-3,3>>^ Porque está perto o dia, sim, está perto o Dia do Senhor . Será um dia de nuvens, o tempo dos gentios.

[[v26-30-4]]

^<<v26-30-4,4>>^ A espada virá contra o Egito, e haverá grande angústia na Etiópia, quando caírem os feridos no Egito; o seu povo será levado para o cativeiro, e serão destruídos os seus fundamentos.

[[v26-30-5]]

^<<v26-30-5,5>>^ A Etiópia, Pute, Lude e toda a Arábia, os de Cube e os homens da terra da aliança cairão à espada juntamente com o Egito."

[[v26-30-6]]

^<<v26-30-6,6>>^ Assim diz o Senhor : "Também cairão os que sustêm o Egito, e será humilhado o orgulho do seu poder. Desde Migdol até Sevene, cairão à espada", diz o Senhor  Deus.

[[v26-30-7]]

^<<v26-30-7,7>>^ "Serão desolados no meio de terras desertas, e as suas cidades estarão no meio das cidades devastadas.

[[v26-30-8]]

^<<v26-30-8,8>>^ Saberão que eu sou o Senhor , quando eu tiver posto fogo no Egito e forem destruídos todos os que lhe prestavam auxílio."

[[v26-30-9]]

^<<v26-30-9,9>>^ — Naquele dia, enviarei mensageiros em navios, para amedrontarem o povo da Etiópia, que vive despreocupado, e haverá angústia entre eles no dia da ruína do Egito; pois eis que já vem.

[[v26-30-10]]

^<<v26-30-10,10>>^ Assim diz o Senhor  Deus: "Farei cessar a pompa do Egito, por meio de Nabucodonosor, rei da Babilônia.

[[v26-30-11]]

^<<v26-30-11,11>>^ Ele e o seu povo com ele, os mais terríveis das nações, serão levados para destruírem a terra; atacarão o Egito com suas espadas na mão e encherão a terra de mortos.

[[v26-30-12]]

^<<v26-30-12,12>>^ Secarei os rios e venderei a terra, entregando-a nas mãos dos maus. Por meio de estrangeiros, farei desolada a terra e a sua plenitude. Eu, o Senhor , falei."

[[v26-30-13]]

^<<v26-30-13,13>>^ Assim diz o Senhor  Deus: "Também destruirei os ídolos e eliminarei as imagens de Mênfis. Não haverá mais príncipe na terra do Egito, onde implantarei o terror.

[[v26-30-14]]

^<<v26-30-14,14>>^ Farei de Patros uma desolação, porei fogo em Zoã e executarei juízo em Tebas.

[[v26-30-15]]

^<<v26-30-15,15>>^ Derramarei o meu furor sobre Sim, fortaleza do Egito, e exterminarei a multidão de Tebas.

[[v26-30-16]]

^<<v26-30-16,16>>^ Atearei fogo no Egito. A cidade de Sim terá grande angústia, Tebas será destruída, e Mênfis terá adversários em pleno dia.

[[v26-30-17]]

^<<v26-30-17,17>>^ Os jovens de Áven e de Pi-Besete cairão à espada, e estas cidades irão para o cativeiro.

[[v26-30-18]]

^<<v26-30-18,18>>^ Em Tafnes, o dia se escurecerá, quando eu quebrar ali os jugos do Egito e nela cessar o orgulho do seu poder; uma nuvem a cobrirá, e as suas filhas irão para o cativeiro.

[[v26-30-19]]

^<<v26-30-19,19>>^ Assim, executarei juízo no Egito, e saberão que eu sou o Senhor ."

[[v26-30-20]]

^<<v26-30-20,20>>^ No décimo primeiro ano, no primeiro mês, aos sete dias do mês, a palavra do Senhor  veio a mim, dizendo:

[[v26-30-21]]

^<<v26-30-21,21>>^ — Filho do homem, eu quebrei o braço de Faraó, rei do Egito, e eis que não foi atado para que seja tratado com remédios, nem posto numa tala para tornar-se forte o bastante para empunhar a espada.

[[v26-30-22]]

^<<v26-30-22,22>>^ Portanto, assim diz o Senhor  Deus: Eis que eu estou contra Faraó, rei do Egito. Quebrarei os seus braços, tanto o forte como o que já está quebrado, e farei com que a espada caia da sua mão.

[[v26-30-23]]

^<<v26-30-23,23>>^ Dispersarei os egípcios entre as nações e os espalharei por outras terras.

[[v26-30-24]]

^<<v26-30-24,24>>^ Fortalecerei os braços do rei da Babilônia e porei a minha espada na mão dele. Porém quebrarei os braços de Faraó, que, diante dele, gemerá como geme quem foi mortalmente ferido.

[[v26-30-25]]

^<<v26-30-25,25>>^ Levantarei os braços do rei da Babilônia, mas os braços de Faraó cairão. Saberão que eu sou o Senhor , quando eu puser a minha espada na mão do rei da Babilônia e ele a estender contra a terra do Egito.

[[v26-30-26]]

^<<v26-30-26,26>>^ Dispersarei os egípcios entre as nações e os espalharei por outras terras. Assim eles saberão que eu sou o Senhor .

'''

xref:026-ezequiel/026-ezequiel-029.adoc#v26-29-0[&#60; Capítulo Anterior] | <<v26-30-0,Topo>> | xref:026-ezequiel/026-ezequiel-031.adoc#v26-31-0[Próximo Capítulo &#62;]