include::./index.adoc[]

[[v26-4-0]]
=== Ezequiel, 4
// naa ?, NAA - Nova Almeida Atualizada

[[v26-4-1]]

^<<v26-4-1,1>>^ — Filho do homem, pegue um tijolo, ponha-o diante de você e faça nele um desenho da cidade de Jerusalém.

[[v26-4-2]]

^<<v26-4-2,2>>^ Nesse desenho, a cidade deverá estar sitiada, com rampas e torres de ataque, acampamentos e aríetes em volta dela.

[[v26-4-3]]

^<<v26-4-3,3>>^ Pegue também uma assadeira de ferro e coloque-a como muro de ferro entre você e a cidade. Volte o seu rosto para a cidade. Ela será sitiada, e você a sitiará. Isso servirá de sinal para a casa de Israel.

[[v26-4-4]]

^<<v26-4-4,4>>^ — Deite-se também sobre o seu lado esquerdo e ponha sobre ele a maldade da casa de Israel. Conforme o número dos dias que se deitar sobre o seu lado esquerdo, você levará sobre si a maldade da casa de Israel.

[[v26-4-5]]

^<<v26-4-5,5>>^ Porque determinei que cada ano da sua maldade corresponda a um dia, num total de trezentos e noventa dias; e você levará sobre si a maldade da casa de Israel.

[[v26-4-6]]

^<<v26-4-6,6>>^ Quando você tiver cumprido esses dias, deite-se sobre o seu lado direito, e você levará sobre si a maldade da casa de Judá durante quarenta dias: um dia para cada ano.

[[v26-4-7]]

^<<v26-4-7,7>>^ Volte o seu rosto para o cerco de Jerusalém e, com o braço descoberto, profetize contra ela.

[[v26-4-8]]

^<<v26-4-8,8>>^ Eis que vou amarrá-lo com cordas, e assim você não poderá se virar de um lado para o outro até que você tenha cumprido os dias do seu cerco.

[[v26-4-9]]

^<<v26-4-9,9>>^ — Pegue trigo, cevada, favas, lentilha, aveia e centeio, coloque-os numa vasilha e com eles faça pão para você. Durante os dias em que você se deitar sobre o seu lado, trezentos e noventa dias, você comerá desse pão.

[[v26-4-10]]

^<<v26-4-10,10>>^ A sua comida será por peso, duzentos e quarenta gramas, que você comerá de tempos em tempos.

[[v26-4-11]]

^<<v26-4-11,11>>^ Também a água que você beber será medida: meio litro por dia, para beber de tempos em tempos.

[[v26-4-12]]

^<<v26-4-12,12>>^ O que você comer será como bolo de cevada, assado sobre esterco humano, à vista do povo.

[[v26-4-13]]

^<<v26-4-13,13>>^ E o Senhor  disse ainda: — Assim os filhos de Israel comerão a sua comida impura, entre as nações para onde os expulsarei.

[[v26-4-14]]

^<<v26-4-14,14>>^ Então eu disse: — Ah! Senhor  Deus! Eis que eu nunca me contaminei, pois, desde a minha mocidade até agora, nunca comi carne de animal que morreu por si ou que foi dilacerado por feras. Em minha boca jamais entrou qualquer carne abominável.

[[v26-4-15]]

^<<v26-4-15,15>>^ Então ele me disse: — Pois bem, vou deixar que você use esterco de vaca em lugar de esterco humano; asse o seu pão em cima dele.

[[v26-4-16]]

^<<v26-4-16,16>>^ Disse mais: — Filho do homem, eis que eu cortarei o suprimento de pão em Jerusalém. Comerão o pão por peso e com ansiedade; beberão a água por medida e com espanto.

[[v26-4-17]]

^<<v26-4-17,17>>^ Visto que lhes faltará o pão e a água, ficarão espantados uns com os outros e se consumirão nas suas maldades.

'''

xref:026-ezequiel/026-ezequiel-003.adoc#v26-3-0[&#60; Capítulo Anterior] | <<v26-4-0,Topo>> | xref:026-ezequiel/026-ezequiel-005.adoc#v26-5-0[Próximo Capítulo &#62;]