include::./index.adoc[]

[[v26-21-0]]
=== Ezequiel, 21
// naa ?, NAA - Nova Almeida Atualizada

[[v26-21-1]]

^<<v26-21-1,1>>^ A palavra do Senhor  veio a mim, dizendo:

[[v26-21-2]]

^<<v26-21-2,2>>^ — Filho do homem, vire o seu rosto contra Jerusalém, fale contra os santuários e profetize contra a terra de Israel.

[[v26-21-3]]

^<<v26-21-3,3>>^ Diga à terra de Israel: Assim diz o Senhor : "Eis que estou contra você. Vou tirar a minha espada da bainha, e eliminarei do seu meio tanto o justo como o ímpio.

[[v26-21-4]]

^<<v26-21-4,4>>^ Visto que eliminarei do seu meio o justo e o ímpio, a minha espada sairá da bainha contra todos, desde o Sul até o Norte.

[[v26-21-5]]

^<<v26-21-5,5>>^ Todos saberão que eu, o Senhor , tirei a minha espada da bainha e que não a porei de volta."

[[v26-21-6]]

^<<v26-21-6,6>>^ — Você, filho do homem, comece a gemer. Na presença deles, fique gemendo de coração quebrantado e com amargura.

[[v26-21-7]]

^<<v26-21-7,7>>^ Quando perguntarem: "Por que você está gemendo?", responda: "Por causa das notícias que estão chegando." Todo coração se derreterá, todas as mãos desfalecerão, todo espírito ficará angustiado e todos os joelhos se desfarão em água. Eis que virá, e se cumprirá, diz o Senhor  Deus.

[[v26-21-8]]

^<<v26-21-8,8>>^ A palavra do Senhor  veio a mim, dizendo:

[[v26-21-9]]

^<<v26-21-9,9>>^ — Filho do homem, profetize e diga: Assim diz o Senhor: "A espada, a espada está afiada e polida;

[[v26-21-10]]

^<<v26-21-10,10>>^ afiada para a matança, polida para reluzir como relâmpago. Israel diz: ‘Vamos nos alegrar! O cetro do meu filho despreza qualquer outra madeira.’

[[v26-21-11]]

^<<v26-21-11,11>>^ Mas Deus responde: ‘A espada foi entregue para ser polida, para ser manejada; está afiada e polida, para ser posta na mão do matador.

[[v26-21-12]]

^<<v26-21-12,12>>^ Grite e lamente, filho do homem, porque a espada será contra o meu povo, contra todos os príncipes de Israel. Estes, juntamente com o meu povo, estão entregues à espada; portanto, bata no peito em sinal de tristeza.

[[v26-21-13]]

^<<v26-21-13,13>>^ Pois haverá uma prova. E o que acontecerá, se o próprio cetro que desprezou a todos não vier a subsistir?’" — diz o Senhor  Deus.

[[v26-21-14]]

^<<v26-21-14,14>>^ — Filho do homem, profetize e bata com as mãos uma na outra. Que a espada golpeie duas vezes, sim, até três vezes. É a espada da matança, da grande matança, que os rodeia,

[[v26-21-15]]

^<<v26-21-15,15>>^ para que o coração se derreta e se multipliquem os que tropeçam. Junto a todas as portas faço reluzir a espada. Ah! Ela foi feita para ser raio e está afiada para matar.

[[v26-21-16]]

^<<v26-21-16,16>>^ Ó espada, vire-se com toda a força para a direita, vire-se para a esquerda, para onde quer que a sua lâmina se dirigir.

[[v26-21-17]]

^<<v26-21-17,17>>^ Também eu baterei as minhas mãos uma na outra e desafogarei o meu furor; eu, o Senhor , falei.

[[v26-21-18]]

^<<v26-21-18,18>>^ A palavra do Senhor  veio a mim, dizendo:

[[v26-21-19]]

^<<v26-21-19,19>>^ — Filho do homem, trace dois caminhos por onde a espada do rei da Babilônia poderá vir. Ambos devem sair da mesma terra. Faça um marco indicador e coloque-o na bifurcação do caminho para a cidade.

[[v26-21-20]]

^<<v26-21-20,20>>^ Indique o caminho para que a espada chegue a Rabá dos filhos de Amom, e a Jerusalém, a fortificada, em Judá.

[[v26-21-21]]

^<<v26-21-21,21>>^ Porque o rei da Babilônia irá parar na bifurcação, na entrada dos dois caminhos, para fazer adivinhações: sacudirá as flechas, consultará os ídolos do lar, examinará o fígado de um animal.

[[v26-21-22]]

^<<v26-21-22,22>>^ Na mão direita estará a adivinhação sobre Jerusalém, para dispor os aríetes, para abrir a boca com ordens de matar, para lançar gritos de guerra, para colocar os aríetes contra os portões, para levantar rampas e torres de ataque.

[[v26-21-23]]

^<<v26-21-23,23>>^ Aos moradores da cidade isso parecerá uma adivinhação falsa, pois eles têm em seu favor juramentos solenes. Mas Deus se lembrará da iniquidade deles, para que sejam presos.

[[v26-21-24]]

^<<v26-21-24,24>>^ — Portanto, assim diz o Senhor  Deus: "Visto que vocês me fazem lembrar da sua iniquidade, na medida em que as suas transgressões são descobertas e em todas as suas ações aparecem os seus pecados — sim, visto que vocês foram lembrados, serão presos por causa disso."

[[v26-21-25]]

^<<v26-21-25,25>>^ — Quanto a você, profano e ímpio príncipe de Israel, cujo dia chegou no tempo do seu castigo final,

[[v26-21-26]]

^<<v26-21-26,26>>^ assim diz o Senhor  Deus: "Tire o turbante e remova a coroa. O que é já não será o mesmo; o humilde será exaltado e o soberbo será abatido.

[[v26-21-27]]

^<<v26-21-27,27>>^ Ruína! Ruína! A ruínas a reduzirei, e ela já não será, até que venha aquele a quem caberá o julgamento; a ele eu a entregarei."

[[v26-21-28]]

^<<v26-21-28,28>>^ — E você, filho do homem, profetize e diga: Assim diz o Senhor  Deus a respeito dos filhos de Amom e a respeito dos seus insultos: "A espada, a espada está desembainhada, polida para a matança, para consumir, para reluzir como relâmpago.

[[v26-21-29]]

^<<v26-21-29,29>>^ Apesar das visões falsas e das adivinhações mentirosas, a espada será posta no pescoço dos profanos, dos perversos, cujo dia virá no tempo do castigo final.

[[v26-21-30]]

^<<v26-21-30,30>>^ Ponha a espada de volta na sua bainha. No lugar em que você foi formado, na terra do seu nascimento, eu o julgarei.

[[v26-21-31]]

^<<v26-21-31,31>>^ Derramarei sobre você a minha indignação, assoprarei contra você o fogo do meu furor e o entregarei nas mãos de homens brutais, mestres de destruição.

[[v26-21-32]]

^<<v26-21-32,32>>^ Você servirá de pasto ao fogo, o seu sangue será derramado no meio da terra, e você não será mais lembrado; porque eu, o Senhor , falei."

'''

xref:026-ezequiel/026-ezequiel-020.adoc#v26-20-0[&#60; Capítulo Anterior] | <<v26-21-0,Topo>> | xref:026-ezequiel/026-ezequiel-022.adoc#v26-22-0[Próximo Capítulo &#62;]