include::./index.adoc[]

[[v26-6-0]]
=== Ezequiel, 6
// naa ?, NAA - Nova Almeida Atualizada

[[v26-6-1]]

^<<v26-6-1,1>>^ A palavra do Senhor  veio a mim, dizendo:

[[v26-6-2]]

^<<v26-6-2,2>>^ — Filho do homem, volte o seu rosto para os montes de Israel e profetize contra eles, dizendo:

[[v26-6-3]]

^<<v26-6-3,3>>^ Montes de Israel, ouçam a palavra do Senhor  Deus. Assim diz o Senhor  Deus aos montes e às colinas, aos desfiladeiros e aos vales: Eis que eu, eu mesmo, trarei a espada sobre vocês e destruirei os seus lugares altos.

[[v26-6-4]]

^<<v26-6-4,4>>^ Os altares de sacrifício serão destruídos, e os altares onde vocês queimam incenso serão quebrados. Farei com que os mortos caiam diante dos seus ídolos.

[[v26-6-5]]

^<<v26-6-5,5>>^ Porei os cadáveres dos filhos de Israel diante dos seus ídolos e espalharei os ossos de vocês ao redor dos seus altares.

[[v26-6-6]]

^<<v26-6-6,6>>^ Onde quer que vocês morarem, as cidades serão destruídas e os lugares altos ficarão em ruínas, para que os altares sejam destruídos e arruinados, os seus ídolos sejam quebrados e extintos, os seus altares do incenso sejam eliminados, e as obras que vocês realizaram sejam desfeitas.

[[v26-6-7]]

^<<v26-6-7,7>>^ Os mortos cairão no meio de vocês, e vocês saberão que eu sou o Senhor .

[[v26-6-8]]

^<<v26-6-8,8>>^ — Mas deixarei um resto, porque alguns de vocês escaparão da espada entre as nações, quando forem espalhados por outras terras.

[[v26-6-9]]

^<<v26-6-9,9>>^ Aqueles que escaparem se lembrarão de mim entre as nações para onde foram levados em cativeiro. Lembrarão como eu sofri por causa do seu coração infiel, que se afastou de mim, e por causa dos seus olhos, que se prostituíram com os seus ídolos. Eles terão nojo de si mesmos, por causa das maldades que fizeram em todas as suas abominações.

[[v26-6-10]]

^<<v26-6-10,10>>^ Saberão que eu sou o Senhor  e que não foi sem motivo que eu disse que lhes faria este mal.

[[v26-6-11]]

^<<v26-6-11,11>>^ — Assim diz o Senhor  Deus: Contorça as mãos, bata os pés e diga: "Ah", por todas as terríveis abominações da casa de Israel! Pois cairão à espada, de fome e de peste.

[[v26-6-12]]

^<<v26-6-12,12>>^ O que estiver longe morrerá de peste; o que estiver perto cairá à espada; e o que sobreviver e for poupado morrerá de fome. Assim, neles cumprirei o meu furor.

[[v26-6-13]]

^<<v26-6-13,13>>^ Então vocês saberão que eu sou o Senhor , quando os seus mortos estiverem estendidos no meio dos seus ídolos, ao redor dos seus altares, em todas as colinas elevadas e no alto de todos os montes, debaixo de todas as árvores frondosas e debaixo de todos os carvalhos espessos, lugares onde ofereciam suave perfume a todos os seus ídolos.

[[v26-6-14]]

^<<v26-6-14,14>>^ Estenderei a mão sobre eles e, onde quer que estiverem morando, tornarei a terra em desolação, uma desolação desde o deserto até Ribla. E saberão que eu sou o Senhor .

'''

xref:026-ezequiel/026-ezequiel-005.adoc#v26-5-0[&#60; Capítulo Anterior] | <<v26-6-0,Topo>> | xref:026-ezequiel/026-ezequiel-007.adoc#v26-7-0[Próximo Capítulo &#62;]