include::./index.adoc[]

[[v26-37-0]]
=== Ezequiel, 37
// naa ?, NAA - Nova Almeida Atualizada

[[v26-37-1]]

^<<v26-37-1,1>>^ Veio sobre mim a mão do Senhor , e ele me levou pelo Espírito do Senhor  e me deixou no meio de um vale que estava cheio de ossos.

[[v26-37-2]]

^<<v26-37-2,2>>^ Ele me fez andar ao redor deles, e eu pude ver que eram muito numerosos na superfície do vale e estavam sequíssimos.

[[v26-37-3]]

^<<v26-37-3,3>>^ Então me perguntou: — Filho do homem, será que estes ossos podem reviver? Respondi: — Senhor  Deus, tu o sabes.

[[v26-37-4]]

^<<v26-37-4,4>>^ Então ele me disse: — Profetize para estes ossos e diga-lhes: "Ossos secos, ouçam a palavra do Senhor ."

[[v26-37-5]]

^<<v26-37-5,5>>^ — Assim diz o Senhor  Deus a estes ossos: "Eis que farei entrar em vocês o espírito, e vocês viverão.

[[v26-37-6]]

^<<v26-37-6,6>>^ Porei tendões sobre vocês, farei crescer carne sobre vocês e os cobrirei de pele. Porei em vocês o espírito, e vocês viverão. Então vocês saberão que eu sou o Senhor ."

[[v26-37-7]]

^<<v26-37-7,7>>^ Então profetizei como me havia sido ordenado. Enquanto eu profetizava, houve um ruído, um barulho de ossos que batiam contra ossos e se ajuntavam, cada osso ao seu osso.

[[v26-37-8]]

^<<v26-37-8,8>>^ Olhei, e eis que apareceram tendões sobre os ossos, cresceram as carnes, e eles se cobriram de pele. Mas não havia neles o espírito.

[[v26-37-9]]

^<<v26-37-9,9>>^ Então ele me disse: — Profetize ao espírito. Profetize, filho do homem, e diga ao espírito: Assim diz o Senhor  Deus: "Venha dos quatro ventos, ó espírito, e sopre sobre estes mortos, para que vivam."

[[v26-37-10]]

^<<v26-37-10,10>>^ Profetizei como ele me havia ordenado. O espírito entrou neles, eles viveram e se puseram em pé. Formavam um exército, um enorme exército.

[[v26-37-11]]

^<<v26-37-11,11>>^ Então ele me disse: — Filho do homem, esses ossos são toda a casa de Israel. Eis que dizem: "Os nossos ossos estão secos, perdemos a nossa esperança, fomos exterminados."

[[v26-37-12]]

^<<v26-37-12,12>>^ Portanto, profetize e diga-lhes: Assim diz o Senhor  Deus: "Eis que abrirei as sepulturas de vocês e os farei sair delas, ó povo meu, e os levarei de volta à terra de Israel.

[[v26-37-13]]

^<<v26-37-13,13>>^ Vocês saberão que eu sou o Senhor , quando eu abrir as sepulturas de vocês e os fizer sair delas, ó povo meu.

[[v26-37-14]]

^<<v26-37-14,14>>^ Porei em vocês o meu Espírito, e vocês viverão. Eu os estabelecerei na sua própria terra, e vocês saberão que eu sou o Senhor . Eu falei e eu o cumprirei, diz o Senhor ."

[[v26-37-15]]

^<<v26-37-15,15>>^ A palavra do Senhor  veio a mim, dizendo:

[[v26-37-16]]

^<<v26-37-16,16>>^ — Filho do homem, pegue um pedaço de madeira e escreva nele o seguinte: "De Judá e dos filhos de Israel, seus companheiros." Depois, pegue outro pedaço de madeira e escreva nele: "De José, pedaço de madeira de Efraim, e de toda a casa de Israel, seus companheiros."

[[v26-37-17]]

^<<v26-37-17,17>>^ Junte os pedaços de madeira um ao outro, faça deles um só pedaço, para que se tornem apenas um na sua mão.

[[v26-37-18]]

^<<v26-37-18,18>>^ Quando os filhos do seu povo perguntarem: "Você não vai nos explicar o que significa isso?",

[[v26-37-19]]

^<<v26-37-19,19>>^ responda: Assim diz o Senhor  Deus: "Eis que eu pegarei o pedaço de madeira de José, que está na mão de Efraim, e das tribos de Israel, suas companheiras, e o ajuntarei ao pedaço de Judá, e farei deles um só pedaço, e se tornarão apenas um na minha mão."

[[v26-37-20]]

^<<v26-37-20,20>>^ — Os pedaços de madeira em que você escreveu devem ficar na sua mão, para que o povo os veja.

[[v26-37-21]]

^<<v26-37-21,21>>^ Então diga-lhes: Assim diz o Senhor  Deus: "Eis que eu tirarei os filhos de Israel do meio das nações para onde eles foram, e os congregarei de todos os lugares ao redor, e os levarei para a sua própria terra.

[[v26-37-22]]

^<<v26-37-22,22>>^ Farei deles uma só nação na terra, nos montes de Israel, e um só rei será rei de todos eles. Nunca mais serão duas nações; nunca mais se dividirão em dois reinos.

[[v26-37-23]]

^<<v26-37-23,23>>^ Nunca mais se contaminarão com os seus ídolos, nem com as suas abominações, nem com qualquer das suas transgressões. Eu os livrarei de todas as suas apostasias em que pecaram e os purificarei. Assim, eles serão o meu povo, e eu serei o seu Deus."

[[v26-37-24]]

^<<v26-37-24,24>>^ — "O meu servo Davi reinará sobre eles, e todos eles terão um só pastor. Andarão nos meus juízos, guardarão os meus estatutos e os observarão.

[[v26-37-25]]

^<<v26-37-25,25>>^ Habitarão na terra que dei ao meu servo Jacó, na qual os pais de vocês habitaram. Habitarão nela, eles e os seus filhos e os filhos dos seus filhos, para sempre. E Davi, meu servo, será o príncipe deles para sempre.

[[v26-37-26]]

^<<v26-37-26,26>>^ Farei com eles uma aliança de paz; será uma aliança eterna. Eu os estabelecerei, os multiplicarei, e porei o meu santuário no meio deles para sempre.

[[v26-37-27]]

^<<v26-37-27,27>>^ O meu tabernáculo estará com eles; eu serei o seu Deus, e eles serão o meu povo.

[[v26-37-28]]

^<<v26-37-28,28>>^ As nações saberão que eu sou o Senhor  que santifico Israel, quando o meu santuário estiver no meio deles para sempre."

'''

xref:026-ezequiel/026-ezequiel-036.adoc#v26-36-0[&#60; Capítulo Anterior] | <<v26-37-0,Topo>> | xref:026-ezequiel/026-ezequiel-038.adoc#v26-38-0[Próximo Capítulo &#62;]