include::./index.adoc[]

[[v26-35-0]]
=== Ezequiel, 35
// naa ?, NAA - Nova Almeida Atualizada

[[v26-35-1]]

^<<v26-35-1,1>>^ A palavra do Senhor  veio a mim, dizendo:

[[v26-35-2]]

^<<v26-35-2,2>>^ — Filho do homem, vire o seu rosto contra o monte Seir e profetize contra ele.

[[v26-35-3]]

^<<v26-35-3,3>>^ Diga-lhe: Assim diz o Senhor  Deus: "Eis que estou contra você, monte Seir. Estenderei a minha mão contra você e o tornarei em desolação e espanto.

[[v26-35-4]]

^<<v26-35-4,4>>^ Deixarei desertas as suas cidades, e você será desolado. Então saberá que eu sou o Senhor .

[[v26-35-5]]

^<<v26-35-5,5>>^ Pois você guardou uma inimizade sem fim e deixou os filhos de Israel entregues ao poder da espada, no tempo da calamidade e do castigo final.

[[v26-35-6]]

^<<v26-35-6,6>>^ Por isso, tão certo como eu vivo, diz o Senhor  Deus, farei você sangrar, e o derramamento de sangue o perseguirá. Visto que você não odiou o derramamento de sangue, este o perseguirá.

[[v26-35-7]]

^<<v26-35-7,7>>^ Farei do monte Seir extrema desolação e eliminarei dele os que por ali passam e os que por ali voltam.

[[v26-35-8]]

^<<v26-35-8,8>>^ Encherei os seus montes de cadáveres; os mortos à espada ficarão caídos nas suas colinas, nos seus vales e em todas as suas correntes de água.

[[v26-35-9]]

^<<v26-35-9,9>>^ Farei de você uma desolação perpétua, e as suas cidades não voltarão a ser habitadas. Assim vocês saberão que eu sou o Senhor ."

[[v26-35-10]]

^<<v26-35-10,10>>^ — "Porque você disse: ‘Esses dois povos são meus e eu vou tomar posse dessas duas terras’, sendo que o Senhor  estava ali.

[[v26-35-11]]

^<<v26-35-11,11>>^ Por isso, tão certo como eu vivo, diz o Senhor  Deus, procederei segundo a sua ira e segundo a sua inveja, com que, no seu ódio, você os tratou. E eu me farei conhecido entre eles, quando castigar você.

[[v26-35-12]]

^<<v26-35-12,12>>^ Você saberá que eu, o Senhor , ouvi todas as blasfêmias que você falou contra os montes de Israel, dizendo: ‘Já estão arrasados e nos foram entregues por pasto.’

[[v26-35-13]]

^<<v26-35-13,13>>^ Vocês se exaltaram contra mim com aquilo que falaram e não pouparam palavras contra mim. Eu ouvi isso muito bem."

[[v26-35-14]]

^<<v26-35-14,14>>^ — Assim diz o Senhor  Deus: "Enquanto toda a terra se alegra, farei de você uma desolação.

[[v26-35-15]]

^<<v26-35-15,15>>^ Assim como você se alegrou quando a herança da casa de Israel foi arrasada, assim também farei com você. Você será arrasado, ó monte Seir e todo o Edom, sim, todo ele. Então saberão que eu sou o Senhor ."

'''

xref:026-ezequiel/026-ezequiel-034.adoc#v26-34-0[&#60; Capítulo Anterior] | <<v26-35-0,Topo>> | xref:026-ezequiel/026-ezequiel-036.adoc#v26-36-0[Próximo Capítulo &#62;]