include::./index.adoc[]

[[v26-22-0]]
=== Ezequiel, 22
// naa ?, NAA - Nova Almeida Atualizada

[[v26-22-1]]

^<<v26-22-1,1>>^ A palavra do Senhor  veio a mim, dizendo:

[[v26-22-2]]

^<<v26-22-2,2>>^ — Filho do homem, será que você está pronto para julgar? Está pronto para julgar a cidade sanguinária? Mostre-lhe todas as suas abominações

[[v26-22-3]]

^<<v26-22-3,3>>^ e diga: Assim diz o Senhor  Deus: "Ai da cidade que derrama sangue no meio de si, para que venha o seu tempo, e que faz ídolos contra si mesma, para se contaminar!

[[v26-22-4]]

^<<v26-22-4,4>>^ Você se tornou culpada pelo sangue que derramou e está contaminada pelos ídolos que fabricou. Você fez chegar o dia do seu julgamento e o término de seus anos. Por isso, fiz de você objeto de deboche das nações e de zombaria de todas as terras.

[[v26-22-5]]

^<<v26-22-5,5>>^ Tanto as que estão perto como as que estão longe zombarão de você, cidade de má fama, cheia de inquietação.

[[v26-22-6]]

^<<v26-22-6,6>>^ Eis que os príncipes de Israel, cada um segundo o seu poder, nada mais intentam, a não ser derramar sangue.

[[v26-22-7]]

^<<v26-22-7,7>>^ Em seu meio, desprezam o pai e a mãe, praticam extorsões contra o estrangeiro e são injustos com o órfão e a viúva.

[[v26-22-8]]

^<<v26-22-8,8>>^ Você desprezou as minhas coisas santas e profanou os meus sábados.

[[v26-22-9]]

^<<v26-22-9,9>>^ Em seu meio há homens que dizem calúnias para derramar sangue. Em seu meio, comem carne sacrificada nos montes e cometem perversidade.

[[v26-22-10]]

^<<v26-22-10,10>>^ Em seu meio, homens têm relações com a mulher do próprio pai e abusam da mulher no período da sua menstruação.

[[v26-22-11]]

^<<v26-22-11,11>>^ Um comete abominação com a mulher do seu próximo, outro contamina vergonhosamente a sua nora, e outro abusa da sua irmã, filha de seu pai.

[[v26-22-12]]

^<<v26-22-12,12>>^ Em seu meio, aceitam suborno para derramar sangue. Você emprestou com usura e cobrou juros. Você explorou o seu próximo com extorsão. Mas de mim você se esqueceu, diz o Senhor  Deus."

[[v26-22-13]]

^<<v26-22-13,13>>^ — "Eis que bato as minhas mãos uma na outra com furor contra a exploração que você praticou e por causa do sangue que foi derramado em seu meio.

[[v26-22-14]]

^<<v26-22-14,14>>^ Estará firme o seu coração? Estarão fortes as suas mãos, nos dias em que eu vier tratar com você? Eu, o Senhor , falei e eu o cumprirei.

[[v26-22-15]]

^<<v26-22-15,15>>^ Eu a dispersarei entre as nações, eu a espalharei por outras terras e acabarei com a sua impureza.

[[v26-22-16]]

^<<v26-22-16,16>>^ Você será profanada em si mesma, à vista das nações, e saberá que eu sou o Senhor ."

[[v26-22-17]]

^<<v26-22-17,17>>^ A palavra do Senhor  veio a mim, dizendo:

[[v26-22-18]]

^<<v26-22-18,18>>^ — Filho do homem, a casa de Israel se transformou em escória para mim. Todos eles são cobre, estanho, ferro e chumbo no meio do forno; eles são a escória da prata.

[[v26-22-19]]

^<<v26-22-19,19>>^ Portanto, assim diz o Senhor  Deus: Visto que todos vocês se transformaram em escória, eis que eu os ajuntarei no meio de Jerusalém.

[[v26-22-20]]

^<<v26-22-20,20>>^ Como se ajuntam a prata, o cobre, o ferro, o chumbo e o estanho no meio do forno, para assoprar o fogo sobre eles, a fim de se fundirem, assim na minha ira e no meu furor eu os ajuntarei, ali os deixarei e fundirei.

[[v26-22-21]]

^<<v26-22-21,21>>^ Eu os reunirei e assoprarei sobre vocês o fogo do meu furor; e vocês serão fundidos no meio de Jerusalém.

[[v26-22-22]]

^<<v26-22-22,22>>^ Como se funde a prata no meio do forno, assim vocês serão fundidos no meio dela. E saberão que eu, o Senhor , derramei o meu furor sobre vocês.

[[v26-22-23]]

^<<v26-22-23,23>>^ A palavra do Senhor  veio a mim, dizendo:

[[v26-22-24]]

^<<v26-22-24,24>>^ — Filho do homem, diga a essa terra: "Você é terra que não está purificada e que não tem chuva no dia da indignação.

[[v26-22-25]]

^<<v26-22-25,25>>^ Há, no meio dela, uma conspiração dos seus profetas. Como um leão que ruge, que arrebata a presa, assim eles devoram pessoas, se apossam de tesouros e coisas preciosas, multiplicam as viúvas no meio dela.

[[v26-22-26]]

^<<v26-22-26,26>>^ Os seus sacerdotes transgridem a minha lei e profanam as minhas coisas santas. Não fazem distinção entre o santo e o profano e não ensinam a diferença entre o puro e o impuro. Não respeitam os meus sábados, e assim sou profanado no meio deles.

[[v26-22-27]]

^<<v26-22-27,27>>^ Os seus líderes no meio dela são como lobos que arrebatam a presa para derramarem o sangue, para destruírem vidas e ganharem lucro desonesto.

[[v26-22-28]]

^<<v26-22-28,28>>^ Os seus profetas cobrem isso com cal, tendo visões falsas e predizendo mentiras. Dizem: ‘Assim diz o Senhor  Deus’, sem que o Senhor  tenha falado.

[[v26-22-29]]

^<<v26-22-29,29>>^ O povo da terra pratica extorsão e anda roubando. Fazem violência aos pobres e necessitados, e injustamente oprimem os estrangeiros."

[[v26-22-30]]

^<<v26-22-30,30>>^ — "Procurei entre eles um homem que reconstruísse a muralha e se colocasse na brecha diante de mim, a favor desta terra, para que eu não a destruísse, mas não encontrei ninguém.

[[v26-22-31]]

^<<v26-22-31,31>>^ Por isso, derramarei sobre eles a minha indignação, e com o fogo do meu furor os consumirei. Farei cair sobre a cabeça deles o castigo que os seus atos merecem", diz o Senhor  Deus.

'''

xref:026-ezequiel/026-ezequiel-021.adoc#v26-21-0[&#60; Capítulo Anterior] | <<v26-22-0,Topo>> | xref:026-ezequiel/026-ezequiel-023.adoc#v26-23-0[Próximo Capítulo &#62;]