include::./index.adoc[]

[[v26-42-0]]
=== Ezequiel, 42
// naa ?, NAA - Nova Almeida Atualizada

[[v26-42-1]]

^<<v26-42-1,1>>^ Depois disto, o homem me fez sair para o átrio exterior, para o lado norte, e me levou às câmaras que estavam para o lado norte, opostas ao edifício na área separada.

[[v26-42-2]]

^<<v26-42-2,2>>^ Esse edifício do lado norte tinha cinquenta metros de comprimento, e a largura era de vinte e cinco metros.

[[v26-42-3]]

^<<v26-42-3,3>>^ De um lado, dava para a área de dez metros que pertencia ao átrio interior e, de outro lado, dava para o pavimento que pertencia ao átrio exterior. Havia uma galeria frente a outra galeria em três andares.

[[v26-42-4]]

^<<v26-42-4,4>>^ Diante das câmaras havia uma passagem de cinco metros de largura, do lado de dentro, e cinquenta metros de comprimento; e as suas entradas eram para o lado norte.

[[v26-42-5]]

^<<v26-42-5,5>>^ As câmaras superiores eram mais estreitas, porque as galerias tiravam mais espaço destas do que das de baixo e das do meio do edifício.

[[v26-42-6]]

^<<v26-42-6,6>>^ Porque elas eram de três andares e não tinham colunas como as colunas dos átrios; por isso, as câmaras superiores eram mais estreitas do que as de baixo e as do meio.

[[v26-42-7]]

^<<v26-42-7,7>>^ Havia também um muro do lado de fora, diante das câmaras, no caminho do átrio exterior, diante das câmaras; esse muro tinha vinte e cinco metros de comprimento.

[[v26-42-8]]

^<<v26-42-8,8>>^ Pois o comprimento das câmaras, que estavam no átrio exterior, era de vinte e cinco metros; e eis que diante do templo a extensão era de cinquenta metros.

[[v26-42-9]]

^<<v26-42-9,9>>^ Na parte de baixo, do lado leste, ficava a entrada dessas câmaras, para quem entra nelas pelo átrio exterior.

[[v26-42-10]]

^<<v26-42-10,10>>^ Na largura do muro do átrio, do lado sul, diante do edifício na área separada, havia também câmaras

[[v26-42-11]]

^<<v26-42-11,11>>^ e uma passagem na frente delas. Tinham a feição das câmaras do lado norte, o mesmo comprimento, a mesma largura, as mesmas saídas, o mesmo arranjo. Como as entradas das câmaras do lado norte,

[[v26-42-12]]

^<<v26-42-12,12>>^ assim eram as entradas das câmaras do lado sul. Havia uma entrada no início da passagem, a saber, a passagem bem diante do muro correspondente, para quem entra pelo lado leste.

[[v26-42-13]]

^<<v26-42-13,13>>^ Então o homem me disse: — As câmaras do norte e as câmaras do sul, que estão diante da área separada, são câmaras santas, em que os sacerdotes, que se aproximam do Senhor , comerão as coisas santíssimas. Nelas também depositarão as coisas santíssimas, isto é, as ofertas de cereais e as ofertas pelo pecado e pela culpa; porque o lugar é santo.

[[v26-42-14]]

^<<v26-42-14,14>>^ Quando os sacerdotes entrarem, não deverão sair do santuário para o átrio exterior, mas porão ali as vestes com que ministraram, porque elas são santas; usarão outras roupas e assim se aproximarão do lugar destinado ao povo.

[[v26-42-15]]

^<<v26-42-15,15>>^ Quando acabou de medir o templo interior, ele me fez sair pelo portão que dá para o leste e mediu a área ao redor.

[[v26-42-16]]

^<<v26-42-16,16>>^ Mediu o lado leste com a cana de medir, e deu duzentos e cinquenta metros.

[[v26-42-17]]

^<<v26-42-17,17>>^ Mediu o lado norte, e deu duzentos e cinquenta metros.

[[v26-42-18]]

^<<v26-42-18,18>>^ Mediu também o lado sul: duzentos e cinquenta metros.

[[v26-42-19]]

^<<v26-42-19,19>>^ Voltou-se para o lado oeste e mediu; deu duzentos e cinquenta metros.

[[v26-42-20]]

^<<v26-42-20,20>>^ Assim, ele mediu a área pelos quatro lados. Havia um muro ao redor, de duzentos e cinquenta metros de comprimento e duzentos e cinquenta metros de largura, para fazer separação entre o santo e o profano.

'''

xref:026-ezequiel/026-ezequiel-041.adoc#v26-41-0[&#60; Capítulo Anterior] | <<v26-42-0,Topo>> | xref:026-ezequiel/026-ezequiel-043.adoc#v26-43-0[Próximo Capítulo &#62;]