include::./index.adoc[]

[[v26-15-0]]
=== Ezequiel, 15
// naa ?, NAA - Nova Almeida Atualizada

[[v26-15-1]]

^<<v26-15-1,1>>^ A palavra do Senhor  veio a mim, dizendo:

[[v26-15-2]]

^<<v26-15-2,2>>^ — Filho do homem, de todos os ramos das árvores da floresta, o que acontece com a lenha da videira?

[[v26-15-3]]

^<<v26-15-3,3>>^ Será que essa madeira pode ser empregada para fazer alguma obra? Será que é possível tirar dela uma estaca para pendurar objetos?

[[v26-15-4]]

^<<v26-15-4,4>>^ Eis que é jogada no fogo, para ser queimada. Se o fogo queima as duas extremidades, e o meio fica também carbonizado, será que serve para alguma obra?

[[v26-15-5]]

^<<v26-15-5,5>>^ Ora, se já não servia para nada quando estava inteira, muito menos servirá para fazer alguma coisa depois que o fogo a queimou ou estiver carbonizada.

[[v26-15-6]]

^<<v26-15-6,6>>^ — Portanto, assim diz o Senhor  Deus: Como a lenha da videira entre as árvores da floresta, que entreguei ao fogo para ser queimada, assim entregarei os moradores de Jerusalém.

[[v26-15-7]]

^<<v26-15-7,7>>^ Voltarei o rosto contra eles. Mesmo que saiam do fogo, o fogo os consumirá. E vocês saberão que eu sou o Senhor , quando tiver voltado o rosto contra eles.

[[v26-15-8]]

^<<v26-15-8,8>>^ Tornarei a terra em desolação, porque cometeram graves transgressões, diz o Senhor  Deus.

'''

xref:026-ezequiel/026-ezequiel-014.adoc#v26-14-0[&#60; Capítulo Anterior] | <<v26-15-0,Topo>> | xref:026-ezequiel/026-ezequiel-016.adoc#v26-16-0[Próximo Capítulo &#62;]