include::./index.adoc[]

[[v26-24-0]]
=== Ezequiel, 24
// naa ?, NAA - Nova Almeida Atualizada

[[v26-24-1]]

^<<v26-24-1,1>>^ A palavra do Senhor  veio a mim, no nono ano, no décimo mês, aos dez dias do mês, dizendo:

[[v26-24-2]]

^<<v26-24-2,2>>^ — Filho do homem, anote o dia de hoje, sim, o dia de hoje, porque o rei da Babilônia começa o cerco de Jerusalém neste dia.

[[v26-24-3]]

^<<v26-24-3,3>>^ Conte uma parábola à casa rebelde e diga: Assim diz o Senhor  Deus: "Ponha a panela no fogo, encha-a com água,

[[v26-24-4]]

^<<v26-24-4,4>>^ acrescente pedaços de carne, todos os bons pedaços — tanto da parte traseira como da parte dianteira; coloque também os melhores ossos.

[[v26-24-5]]

^<<v26-24-5,5>>^ Pegue isso dos melhores animais do rebanho. Empilhe lenha debaixo da panela, deixe ferver bem e cozinhe os ossos dentro dela."

[[v26-24-6]]

^<<v26-24-6,6>>^ — Portanto, assim diz o Senhor  Deus: Ai da cidade sanguinária, da panela cheia de ferrugem, ferrugem que não foi tirada dela! Tire de dentro a carne, pedaço por pedaço, sem escolha.

[[v26-24-7]]

^<<v26-24-7,7>>^ Porque a culpa de sangue está no meio dela. O sangue foi derramado sobre a rocha escalvada e não sobre a terra, para o cobrir com o pó.

[[v26-24-8]]

^<<v26-24-8,8>>^ Para fazer subir a indignação, para tomar vingança, eu pus o seu sangue numa rocha escalvada, para que não fosse coberto.

[[v26-24-9]]

^<<v26-24-9,9>>^ — Portanto, assim diz o Senhor  Deus: Ai da cidade sanguinária! Eu mesmo aumentarei a pilha de lenha.

[[v26-24-10]]

^<<v26-24-10,10>>^ Amontoe muita lenha, acenda o fogo, cozinhe a carne, engrosse o caldo, deixe que os ossos fiquem torrados.

[[v26-24-11]]

^<<v26-24-11,11>>^ Ponha a panela vazia sobre as brasas, para que ela aqueça, o seu cobre se torne candente, a impureza que está dentro dela se derreta e a sua ferrugem se consuma.

[[v26-24-12]]

^<<v26-24-12,12>>^ Trabalho inútil! A sua muita ferrugem não sai, nem pelo fogo.

[[v26-24-13]]

^<<v26-24-13,13>>^ Jerusalém, por causa de sua imunda perversidade, e porque eu quis purificá-la, mas você não ficou limpa, você não ficará pura de novo até que eu tenha satisfeito o meu furor contra você.

[[v26-24-14]]

^<<v26-24-14,14>>^ Eu, o Senhor , falei; será assim; eu o farei. Não voltarei atrás e não pouparei, nem mudarei de ideia. Você será julgada segundo os seus caminhos e segundo os seus atos, diz o Senhor  Deus.

[[v26-24-15]]

^<<v26-24-15,15>>^ A palavra do Senhor  veio a mim, dizendo:

[[v26-24-16]]

^<<v26-24-16,16>>^ — Filho do homem, eis que, com um só golpe, tirarei aquela que é a delícia dos seus olhos. Você não deve lamentar, nem chorar, nem derramar lágrimas.

[[v26-24-17]]

^<<v26-24-17,17>>^ Sofra em silêncio; não faça lamentação pelos mortos. Prenda o seu turbante; ponha as sandálias nos pés; não cubra o bigode, e não coma o pão que lhe mandarem.

[[v26-24-18]]

^<<v26-24-18,18>>^ Falei ao povo pela manhã, e à tarde a minha mulher morreu. Na manhã seguinte, fiz como me havia sido ordenado.

[[v26-24-19]]

^<<v26-24-19,19>>^ Então o povo me perguntou: — Você não vai nos explicar o que significa para nós isso que você está fazendo?

[[v26-24-20]]

^<<v26-24-20,20>>^ Eu respondi: — A palavra do Senhor  veio a mim, dizendo:

[[v26-24-21]]

^<<v26-24-21,21>>^ Diga à casa de Israel: Assim diz o Senhor  Deus: "Eis que profanarei o meu santuário, do qual vocês tanto se orgulham, que é a delícia dos seus olhos e o desejo do seu coração. Os filhos e as filhas que vocês deixaram para trás cairão à espada.

[[v26-24-22]]

^<<v26-24-22,22>>^ Vocês farão o que eu fiz: não cobrirão o bigode, nem comerão o pão que lhes mandarem.

[[v26-24-23]]

^<<v26-24-23,23>>^ Manterão o turbante na cabeça e as sandálias nos pés. Não irão lamentar nem chorar, mas serão consumidos nas suas maldades e gemerão uns pelos outros.

[[v26-24-24]]

^<<v26-24-24,24>>^ Assim, Ezequiel será um sinal para vocês: tudo o que ele fez vocês também farão. Quando isso acontecer, vocês saberão que eu sou o Senhor  Deus."

[[v26-24-25]]

^<<v26-24-25,25>>^ — Filho do homem, no dia em que eu lhes tirar o objeto do seu orgulho, a sua alegria e a sua glória, a delícia dos seus olhos e o desejo de seu coração — bem como os seus filhos e as suas filhas —,

[[v26-24-26]]

^<<v26-24-26,26>>^ nesse dia um sobrevivente virá falar com você, para lhe dar a notícia.

[[v26-24-27]]

^<<v26-24-27,27>>^ Nesse dia, você poderá abrir a sua boca para falar com aquele sobrevivente; você falará e não mais ficará mudo. Assim, você será um sinal para eles, e eles saberão que eu sou o Senhor .

'''

xref:026-ezequiel/026-ezequiel-023.adoc#v26-23-0[&#60; Capítulo Anterior] | <<v26-24-0,Topo>> | xref:026-ezequiel/026-ezequiel-025.adoc#v26-25-0[Próximo Capítulo &#62;]