include::./index.adoc[]

[[v26-17-0]]
=== Ezequiel, 17
// naa ?, NAA - Nova Almeida Atualizada

[[v26-17-1]]

^<<v26-17-1,1>>^ A palavra do Senhor  veio a mim, dizendo:

[[v26-17-2]]

^<<v26-17-2,2>>^ — Filho do homem, proponha um enigma e apresente uma parábola à casa de Israel.

[[v26-17-3]]

^<<v26-17-3,3>>^ Diga: Assim diz o Senhor  Deus: "Uma grande águia, de grandes asas, de comprida plumagem, cheia de penas de várias cores, veio ao Líbano e levou a ponta de um cedro.

[[v26-17-4]]

^<<v26-17-4,4>>^ Arrancou a ponta mais alta dos seus ramos e a levou para uma terra de negociantes; na cidade de mercadores, a deixou.

[[v26-17-5]]

^<<v26-17-5,5>>^ Depois, pegou uma semente da terra e a plantou num campo fértil; pegou-a e a plantou junto às muitas águas, como se fosse um salgueiro.

[[v26-17-6]]

^<<v26-17-6,6>>^ Ela cresceu e se tornou uma videira de pouca altura, mas esparramada, com os ramos virados para a águia e as raízes debaixo dela. Assim, ela se tornou uma videira, e produzia ramos, e lançava renovos."

[[v26-17-7]]

^<<v26-17-7,7>>^ "Houve outra grande águia, de grandes asas e de muitas penas. E eis que a videira lançou as suas raízes na direção dessa águia e estendeu para ela os seus ramos, desde o lugar onde estava plantada, para que a regasse.

[[v26-17-8]]

^<<v26-17-8,8>>^ Ela estava plantada em boa terra, junto a muitas águas, para produzir ramos, dar frutos e ser excelente videira."

[[v26-17-9]]

^<<v26-17-9,9>>^ — Diga: Assim diz o Senhor  Deus: "Será que ela vai prosperar? Será que a primeira águia não lhe arrancará as raízes e não cortará o seu fruto, para que se sequem todas as folhas de seus renovos? Não será necessária muita força nem muita gente para arrancá-la pelas raízes.

[[v26-17-10]]

^<<v26-17-10,10>>^ Mas, mesmo que esteja plantada, será que vai prosperar? Será que não vai secar completamente quando o vento leste tocar nela? No lugar onde está plantada, secará."

[[v26-17-11]]

^<<v26-17-11,11>>^ Então a palavra do Senhor  veio a mim, dizendo:

[[v26-17-12]]

^<<v26-17-12,12>>^ — Pergunte agora à casa rebelde: Será que vocês não sabem o que significa isso? Diga: Eis que o rei da Babilônia veio a Jerusalém, pegou o seu rei e os seus príncipes e os levou consigo para a Babilônia.

[[v26-17-13]]

^<<v26-17-13,13>>^ Escolheu um membro da família real, fez aliança com ele e tomou dele juramento. Levou os poderosos da terra,

[[v26-17-14]]

^<<v26-17-14,14>>^ para que o reino ficasse humilhado e não se levantasse, mas, guardando a sua aliança, pudesse subsistir.

[[v26-17-15]]

^<<v26-17-15,15>>^ Mas ele se rebelou contra o rei da Babilônia, enviando os seus mensageiros ao Egito, para conseguir cavalos e um grande exército. Será que prosperará ou conseguirá escapar aquele que faz tais coisas? Poderá quebrar a aliança e escapar?

[[v26-17-16]]

^<<v26-17-16,16>>^ — Tão certo como eu vivo, diz o Senhor  Deus, no lugar em que mora o rei que o pôs no trono, cujo juramento desprezou e cuja aliança quebrou, sim, junto dele, no meio da Babilônia será morto.

[[v26-17-17]]

^<<v26-17-17,17>>^ Faraó, nem com grande exército, nem com numerosa companhia, o ajudará na guerra, quando rampas e torres de ataque forem levantadas para destruir muitas vidas.

[[v26-17-18]]

^<<v26-17-18,18>>^ Ele desprezou o juramento, quebrando a aliança feita com aperto de mão, e praticou todas estas coisas; por isso, não escapará.

[[v26-17-19]]

^<<v26-17-19,19>>^ — Portanto, assim diz o Senhor  Deus: Tão certo como eu vivo, o meu juramento que ele desprezou e a minha aliança que ele quebrou, isto farei recair sobre a sua cabeça.

[[v26-17-20]]

^<<v26-17-20,20>>^ Estenderei sobre ele a minha rede, e ficará preso nas minhas malhas. Eu o levarei para a Babilônia e ali entrarei em juízo com ele por causa da rebeldia que praticou contra mim.

[[v26-17-21]]

^<<v26-17-21,21>>^ Todos os seus fugitivos, com todas as suas tropas, cairão à espada, e os que restarem serão espalhados aos quatro ventos. Então vocês saberão que eu, o Senhor , falei.

[[v26-17-22]]

^<<v26-17-22,22>>^ — Assim diz o Senhor  Deus: Também eu pegarei a ponta mais alta de um cedro e a plantarei; do principal dos seus ramos cortarei o renovo mais tenro e eu mesmo o plantarei sobre um monte alto e sublime.

[[v26-17-23]]

^<<v26-17-23,23>>^ No monte alto de Israel, o plantarei; ele produzirá ramos, dará frutos e se tornará um cedro excelente. Debaixo dele, viverão pássaros de todo tipo; à sombra dos seus ramos se aninharão aves de toda espécie.

[[v26-17-24]]

^<<v26-17-24,24>>^ Todas as árvores do campo saberão que eu, o Senhor , derrubo a árvore alta e elevo a baixa, seco a árvore verde e faço reverdecer a seca. Eu, o Senhor , falei e eu o cumprirei.

'''

xref:026-ezequiel/026-ezequiel-016.adoc#v26-16-0[&#60; Capítulo Anterior] | <<v26-17-0,Topo>> | xref:026-ezequiel/026-ezequiel-018.adoc#v26-18-0[Próximo Capítulo &#62;]