include::./index.adoc[]

[[v26-27-0]]
=== Ezequiel, 27
// naa ?, NAA - Nova Almeida Atualizada

[[v26-27-1]]

^<<v26-27-1,1>>^ A palavra do Senhor  veio a mim, dizendo:

[[v26-27-2]]

^<<v26-27-2,2>>^ — Filho do homem, faça uma lamentação sobre Tiro.

[[v26-27-3]]

^<<v26-27-3,3>>^ Diga a Tiro, que habita nas entradas do mar e negocia com os povos em muitas terras do mar: Assim diz o Senhor  Deus: "Ó Tiro, você diz que é a Perfeição da Formosura.

[[v26-27-4]]

^<<v26-27-4,4>>^ As suas fronteiras estão no coração dos mares; os que a construíram aperfeiçoaram a sua beleza.

[[v26-27-5]]

^<<v26-27-5,5>>^ Fabricaram todos os seus conveses de ciprestes de Senir; trouxeram cedros do Líbano para fazer o seu mastro.

[[v26-27-6]]

^<<v26-27-6,6>>^ Fizeram os seus remos de carvalhos de Basã; os seus bancos, fizeram-nos de marfim engastado em pinho de Chipre.

[[v26-27-7]]

^<<v26-27-7,7>>^ A sua vela era de linho fino bordado do Egito, para servir de estandarte; azul e púrpura das ilhas de Elisá eram o seu toldo.

[[v26-27-8]]

^<<v26-27-8,8>>^ Os moradores de Sidom e de Arvade foram os seus remadores; os seus sábios, ó Tiro, que se achavam dentro de você, esses foram os seus pilotos.

[[v26-27-9]]

^<<v26-27-9,9>>^ Os anciãos de Gebal e os seus sábios estavam dentro de você para reparar as brechas; todos os navios do mar e os marinheiros se achavam dentro de você, para comprar as suas mercadorias."

[[v26-27-10]]

^<<v26-27-10,10>>^ — Os persas, os lídios e os de Pute serviam no seu exército como homens de guerra; penduravam em você os seus escudos e capacetes; foram eles que a cobriram de glória.

[[v26-27-11]]

^<<v26-27-11,11>>^ Os filhos de Arvade e o seu exército estavam sobre as muralhas que a rodeavam, e os gamaditas ficavam de vigia nas torres; penduravam os seus escudos nas suas muralhas e aperfeiçoavam a sua beleza.

[[v26-27-12]]

^<<v26-27-12,12>>^ — Társis negociava com você, por causa da abundância de todo tipo de riquezas; em troca das suas mercadorias lhe traziam prata, ferro, estanho e chumbo.

[[v26-27-13]]

^<<v26-27-13,13>>^ Javã, Tubal e Meseque negociavam com você; em troca das suas mercadorias, davam escravos e objetos de bronze.

[[v26-27-14]]

^<<v26-27-14,14>>^ Os da casa de Togarma, em troca das suas mercadorias, davam cavalos, ginetes e mulas.

[[v26-27-15]]

^<<v26-27-15,15>>^ Os filhos de Dedã negociavam com você; muitas terras do mar eram o mercado das suas manufaturas; em troca, traziam dentes de marfim e madeira de ébano.

[[v26-27-16]]

^<<v26-27-16,16>>^ A Síria negociava com você por causa da multidão das suas manufaturas; por suas mercadorias, eles davam esmeralda, púrpura, obras bordadas, linho fino, coral e pedras preciosas.

[[v26-27-17]]

^<<v26-27-17,17>>^ Judá e a terra de Israel negociavam com você; pelas suas mercadorias, davam o trigo de Minite, confeitos, mel, azeite e bálsamo.

[[v26-27-18]]

^<<v26-27-18,18>>^ Damasco negociava com você, por causa da multidão das suas manufaturas, por causa da abundância de todo tipo de riquezas, dando em troca vinho de Helbom e lã de Saar.

[[v26-27-19]]

^<<v26-27-19,19>>^ Também Dã e Javã, de Uzal, pelas suas mercadorias, davam em troca ferro trabalhado, cássia e cálamo, que assim entravam no seu comércio.

[[v26-27-20]]

^<<v26-27-20,20>>^ Dedã negociava com você, trazendo mantas para cavalos.

[[v26-27-21]]

^<<v26-27-21,21>>^ A Arábia e todos os príncipes de Quedar eram seus clientes; negociavam com você, trazendo cordeiros, carneiros e bodes; nisto, negociavam com você.

[[v26-27-22]]

^<<v26-27-22,22>>^ Os mercadores de Sabá e Raamá negociavam com você; pelas suas mercadorias, davam em troca os mais finos aromas, pedras preciosas e ouro.

[[v26-27-23]]

^<<v26-27-23,23>>^ Harã, Cane e Éden, mercadores de Sabá, Assíria e Quilmade eram seus clientes.

[[v26-27-24]]

^<<v26-27-24,24>>^ Negociavam com você, trazendo todo tipo de mercadorias, tecidos de púrpura e bordados, tapetes de várias cores e cordas trançadas e fortes.

[[v26-27-25]]

^<<v26-27-25,25>>^ Os navios de Társis transportavam as suas mercadorias. "Você se enriqueceu e ficou famosa no coração dos mares.

[[v26-27-26]]

^<<v26-27-26,26>>^ Os seus remadores conduziram você sobre grandes águas; o vento leste a destroçou no coração dos mares.

[[v26-27-27]]

^<<v26-27-27,27>>^ As suas riquezas, as suas mercadorias, os seus bens, os seus marinheiros, os seus pilotos, os encarregados de reparar as brechas, os seus comerciantes e todos os soldados que estão dentro de você, juntamente com toda a multidão do povo que está dentro de você, se afundarão no coração dos mares no dia da sua ruína, ó Tiro.

[[v26-27-28]]

^<<v26-27-28,28>>^ Ao estrondo da gritaria dos seus pilotos, as praias tremerão.

[[v26-27-29]]

^<<v26-27-29,29>>^ Todos os remadores, os marinheiros, e todos os pilotos do mar descerão de seus navios e pararão em terra.

[[v26-27-30]]

^<<v26-27-30,30>>^ Farão ouvir a sua voz por causa de você e gritarão amargamente; lançarão pó sobre a cabeça e rolarão na cinza.

[[v26-27-31]]

^<<v26-27-31,31>>^ Raparão a cabeça por sua causa, vestirão roupa feita de pano de saco e chorarão por você com amargura de alma e com amarga lamentação.

[[v26-27-32]]

^<<v26-27-32,32>>^ Em seu pranto, farão uma lamentação sobre você, dizendo: ‘Quem era como Tiro, que agora está reduzida ao silêncio no meio do mar?

[[v26-27-33]]

^<<v26-27-33,33>>^ Quando as suas mercadorias eram exportadas pelos mares, você satisfez muitos povos; com as suas muitas riquezas e suas mercadorias você enriqueceu os reis da terra.

[[v26-27-34]]

^<<v26-27-34,34>>^ Agora você foi destroçada nos mares, nas profundezas das águas; se afundaram as suas mercadorias e toda a multidão que estava dentro de você.’"

[[v26-27-35]]

^<<v26-27-35,35>>^ "Todos os moradores das ilhas se espantam por causa de você; os seus reis estão apavorados e trazem o medo estampado no rosto.

[[v26-27-36]]

^<<v26-27-36,36>>^ Os mercadores entre os povos zombam de você; você se tornou objeto de espanto e deixará de existir para sempre."

'''

xref:026-ezequiel/026-ezequiel-026.adoc#v26-26-0[&#60; Capítulo Anterior] | <<v26-27-0,Topo>> | xref:026-ezequiel/026-ezequiel-028.adoc#v26-28-0[Próximo Capítulo &#62;]