include::./index.adoc[]

[[v26-40-0]]
=== Ezequiel, 40
// naa ?, NAA - Nova Almeida Atualizada

[[v26-40-1]]

^<<v26-40-1,1>>^ No vigésimo quinto ano do nosso exílio, no princípio do ano, no décimo dia do mês, catorze anos após a queda da cidade de Jerusalém, nesse mesmo dia, veio sobre mim a mão do Senhor , e ele me levou para lá.

[[v26-40-2]]

^<<v26-40-2,2>>^ Em visões, Deus me levou à terra de Israel e me pôs sobre um monte muito alto, sobre o qual havia uma estrutura de cidade, para o lado sul.

[[v26-40-3]]

^<<v26-40-3,3>>^ Ele me levou para lá, e eu vi um homem cuja aparência era como a do bronze. Estava em pé junto ao portão e tinha na mão um cordel de linho e uma cana de medir.

[[v26-40-4]]

^<<v26-40-4,4>>^ O homem me disse: — Filho do homem, veja com os próprios olhos, ouça com os próprios ouvidos e preste atenção em tudo o que eu lhe mostrar, porque para isso você foi trazido aqui. Anuncie à casa de Israel tudo o que você está vendo.

[[v26-40-5]]

^<<v26-40-5,5>>^ Vi uma muralha externa que rodeava todo o templo e, na mão do homem, uma cana de medir, que tinha três metros de comprimento. Ele mediu a largura da muralha e deu três metros; mediu a altura e deu três metros.

[[v26-40-6]]

^<<v26-40-6,6>>^ Então veio ao portão que dava para o leste e subiu pelos seus degraus. Mediu o limiar do portão e deu três metros de largura.

[[v26-40-7]]

^<<v26-40-7,7>>^ Cada câmara lateral tinha três metros de comprimento e três metros de largura. O espaço entre uma e outra câmara era de dois metros e meio. O limiar do portão, junto ao vestíbulo da porta interior, tinha três metros.

[[v26-40-8]]

^<<v26-40-8,8>>^ Também mediu o vestíbulo da porta interior e deu três metros.

[[v26-40-9]]

^<<v26-40-9,9>>^ Então mediu o vestíbulo do portão, que tinha quatro metros, e os seus pilares, que tinham um metro. O vestíbulo do portão está voltado para o templo.

[[v26-40-10]]

^<<v26-40-10,10>>^ O portão do lado leste possuía três câmaras de cada lado, cuja medida era a mesma para cada uma. Também os pilares de cada lado tinham a mesma medida.

[[v26-40-11]]

^<<v26-40-11,11>>^ Em seguida, ele mediu a largura da entrada do portão, que era de cinco metros; a profundidade da entrada era de seis metros e meio.

[[v26-40-12]]

^<<v26-40-12,12>>^ Diante de cada uma das câmaras havia uma mureta, que tinha meio metro de espessura. Cada câmara tinha três metros de cada lado.

[[v26-40-13]]

^<<v26-40-13,13>>^ Então ele mediu o portão desde a extremidade do teto de uma câmara até a da outra, e deu doze metros e meio. As portas das câmaras ficavam uma diante da outra.

[[v26-40-14]]

^<<v26-40-14,14>>^ Mediu a distância até os pilares, e deu trinta metros, e o átrio se estendia até os pilares ao redor da porta.

[[v26-40-15]]

^<<v26-40-15,15>>^ Desde a dianteira do portão da entrada até a dianteira do vestíbulo da porta interior, a distância era de vinte e cinco metros.

[[v26-40-16]]

^<<v26-40-16,16>>^ Havia também janelas com ripas fixas superpostas para as câmaras e para os pilares, e do mesmo modo, para os vestíbulos. As janelas ficavam ao redor pela parte de dentro, e nos pilares havia palmeiras esculpidas.

[[v26-40-17]]

^<<v26-40-17,17>>^ Ele me levou ao átrio exterior, e eis que havia nele câmaras e um pavimento em volta de todo o átrio. Diante deste pavimento havia trinta câmaras.

[[v26-40-18]]

^<<v26-40-18,18>>^ O pavimento ao lado das portas tinha o mesmo comprimento das portas; esse era o pavimento inferior.

[[v26-40-19]]

^<<v26-40-19,19>>^ Então mediu a largura desde a dianteira do portão inferior até a dianteira do átrio interior, e deu cinquenta metros do lado leste e do lado norte.

[[v26-40-20]]

^<<v26-40-20,20>>^ Quanto ao portão que dava para o norte, no átrio exterior, ele mediu o seu comprimento e a sua largura.

[[v26-40-21]]

^<<v26-40-21,21>>^ As suas câmaras, três de um lado e três do outro, os seus pilares e os seus vestíbulos tinham as mesmas medidas do primeiro portão: vinte e cinco metros de comprimento e doze metros e meio de largura.

[[v26-40-22]]

^<<v26-40-22,22>>^ As suas janelas, os seus vestíbulos e as suas palmeiras esculpidas tinham as mesmas medidas do portão que dava para o leste. Subia-se para esse portão por sete degraus, e o seu vestíbulo estava diante dele.

[[v26-40-23]]

^<<v26-40-23,23>>^ Esse portão do átrio interior estava diante do portão do norte, como no caso do portão do leste. Ele mediu de um portão a outro portão, e deu cinquenta metros.

[[v26-40-24]]

^<<v26-40-24,24>>^ Então ele me levou para o lado sul, e eis que havia ali um portão que dava para o sul. Ele mediu os seus pilares e os seus vestíbulos, que tinham as mesmas dimensões dos outros.

[[v26-40-25]]

^<<v26-40-25,25>>^ Havia também janelas ao redor dos seus vestíbulos, como as outras janelas; o comprimento era de vinte e cinco metros, e a largura, de doze metros e meio.

[[v26-40-26]]

^<<v26-40-26,26>>^ Havia uma escada de sete degraus, e o seu vestíbulo estava diante dela; e tinha palmeiras esculpidas nos pilares, tanto de um lado como do outro.

[[v26-40-27]]

^<<v26-40-27,27>>^ O átrio interior também tinha um portão que dava para o sul. Ele mediu de um portão ao outro, na direção do sul, e deu cinquenta metros.

[[v26-40-28]]

^<<v26-40-28,28>>^ Então ele me levou ao átrio interior pelo portão do sul; ele mediu o portão do sul, que tinha as mesmas dimensões dos outros.

[[v26-40-29]]

^<<v26-40-29,29>>^ As suas câmaras, os seus pilares e os seus vestíbulos tinham as mesmas medidas dos outros. Tinham também janelas ao redor dos seus vestíbulos; o comprimento era de vinte e cinco metros, e a largura, de doze metros e meio.

[[v26-40-30]]

^<<v26-40-30,30>>^ Havia vestíbulos ao redor; o comprimento era de vinte e cinco metros, e a largura, de doze metros e meio.

[[v26-40-31]]

^<<v26-40-31,31>>^ O seu vestíbulo dava para o átrio exterior, havia palmeiras esculpidas nos seus pilares, e a sua escada tinha oito degraus.

[[v26-40-32]]

^<<v26-40-32,32>>^ Depois, ele me levou ao átrio interior, para o leste, e mediu o portão, que tinha as mesmas dimensões dos outros portões.

[[v26-40-33]]

^<<v26-40-33,33>>^ Também as suas câmaras, os seus pilares e os seus vestíbulos tinham as mesmas medidas dos outros. Havia também janelas ao redor dos seus vestíbulos; o comprimento era de vinte e cinco metros, e a largura, de doze metros e meio.

[[v26-40-34]]

^<<v26-40-34,34>>^ O seu vestíbulo dava para o átrio exterior, havia palmeiras esculpidas nos seus pilares, de um e de outro lado, e a sua escada tinha oito degraus.

[[v26-40-35]]

^<<v26-40-35,35>>^ Então me levou ao portão do norte e o mediu; tinha as mesmas dimensões dos outros portões.

[[v26-40-36]]

^<<v26-40-36,36>>^ Também as suas câmaras, os seus pilares, os seus vestíbulos e as suas janelas ao redor; o comprimento era de vinte e cinco metros, e a largura, de doze metros e meio.

[[v26-40-37]]

^<<v26-40-37,37>>^ O seu vestíbulo dava para o átrio exterior, havia palmeiras esculpidas nos seus pilares, de um e de outro lado, e a sua escada tinha oito degraus.

[[v26-40-38]]

^<<v26-40-38,38>>^ Havia uma câmara com a sua entrada junto aos pilares dos vestíbulos onde lavavam os holocaustos.

[[v26-40-39]]

^<<v26-40-39,39>>^ No vestíbulo do portão havia duas mesas de um lado e duas do outro, para nelas se degolar os holocaustos e as ofertas pelo pecado e pela culpa.

[[v26-40-40]]

^<<v26-40-40,40>>^ Do lado de fora, na subida para a entrada do portão do norte havia duas mesas; e, no outro lado do vestíbulo do portão, havia duas mesas.

[[v26-40-41]]

^<<v26-40-41,41>>^ Quatro mesas de um lado, e quatro do outro lado do portão; oito mesas, sobre as quais eram mortos os animais do sacrifício.

[[v26-40-42]]

^<<v26-40-42,42>>^ As quatro mesas para os holocaustos eram de pedras lavradas. Tinham setenta e cinco centímetros de comprimento e de largura, e meio metro de altura. Sobre elas se punham os instrumentos com que matavam os animais para os holocaustos e os sacrifícios.

[[v26-40-43]]

^<<v26-40-43,43>>^ Ganchos, de sete centímetros e meio de comprimento, estavam fixados à parede, em toda a sua extensão. Mas a carne para os sacrifícios estava sobre as mesas.

[[v26-40-44]]

^<<v26-40-44,44>>^ Fora do portão interior, no átrio de dentro, estavam duas câmaras. Uma ficava ao lado do portão do norte, e dava para o sul; outra ficava ao lado do portão do sul, e dava para o norte.

[[v26-40-45]]

^<<v26-40-45,45>>^ Ele me disse: — Esta câmara que dá para o sul é para os sacerdotes que têm a guarda do templo,

[[v26-40-46]]

^<<v26-40-46,46>>^ e a câmara que dá para o norte é para os sacerdotes que têm a guarda do altar. São eles os filhos de Zadoque, os quais, dentre os filhos de Levi, se aproximam do Senhor  para o servir.

[[v26-40-47]]

^<<v26-40-47,47>>^ Ele mediu o átrio, que tinha cinquenta metros de comprimento e cinquenta de largura — um quadrado. O altar estava diante do templo.

[[v26-40-48]]

^<<v26-40-48,48>>^ Então me levou ao vestíbulo do templo. Mediu cada pilar do vestíbulo: dois metros e meio de um lado e dois metros e meio do outro. A largura do portão era de um metro e meio de um lado e um metro e meio do outro.

[[v26-40-49]]

^<<v26-40-49,49>>^ O comprimento do vestíbulo era de dez metros, e a largura, de seis metros. Era por degraus que se subia até lá. Havia colunas junto aos pilares, uma de um lado e outra do outro.

'''

xref:026-ezequiel/026-ezequiel-039.adoc#v26-39-0[&#60; Capítulo Anterior] | <<v26-40-0,Topo>> | xref:026-ezequiel/026-ezequiel-041.adoc#v26-41-0[Próximo Capítulo &#62;]