include::./index.adoc[]

[[v26-31-0]]
=== Ezequiel, 31
// naa ?, NAA - Nova Almeida Atualizada

[[v26-31-1]]

^<<v26-31-1,1>>^ No décimo primeiro ano, no terceiro mês, no primeiro dia do mês, a palavra do Senhor  veio a mim, dizendo:

[[v26-31-2]]

^<<v26-31-2,2>>^ — Filho do homem, diga a Faraó, rei do Egito, e à multidão do seu povo: "A quem você é semelhante em sua grandeza?

[[v26-31-3]]

^<<v26-31-3,3>>^ Eis que a Assíria era um cedro no Líbano, de lindos ramos, de sombrosa folhagem e de grande estatura, cujo topo chegava até as nuvens.

[[v26-31-4]]

^<<v26-31-4,4>>^ As águas o fizeram crescer; as fontes do abismo o fortaleceram, fazendo correr as suas torrentes no lugar em que ele estava plantado e enviando os seus ribeiros para todas as árvores do campo.

[[v26-31-5]]

^<<v26-31-5,5>>^ Cresceu mais do que todas as árvores do campo; os seus galhos se multiplicaram e os seus ramos se alongaram, por causa das muitas águas durante o seu crescimento.

[[v26-31-6]]

^<<v26-31-6,6>>^ Todas as aves do céu se aninhavam nos seus galhos, todos os animais do campo davam cria debaixo dos seus ramos, e todos os grandes povos se assentavam à sua sombra.

[[v26-31-7]]

^<<v26-31-7,7>>^ Ele era formoso na sua grandeza e na extensão dos seus ramos, porque as suas raízes estavam junto às muitas águas.

[[v26-31-8]]

^<<v26-31-8,8>>^ Os cedros no jardim de Deus não lhe eram rivais; os ciprestes não igualavam os seus ramos, e os plátanos não tinham renovos como os seus; nenhuma árvore no jardim de Deus se assemelhava a esse cedro na sua formosura.

[[v26-31-9]]

^<<v26-31-9,9>>^ Eu o fiz formoso, com a multidão dos seus ramos. Todas as árvores do Éden, que estavam no jardim de Deus, tinham inveja dele."

[[v26-31-10]]

^<<v26-31-10,10>>^ — Portanto, assim diz o Senhor  Deus: Visto que ela elevou a sua estatura, o seu topo chegou até as nuvens e o seu coração ficou orgulhoso da sua altura,

[[v26-31-11]]

^<<v26-31-11,11>>^ eu entregarei essa árvore nas mãos da mais poderosa das nações, que certamente lhe dará o tratamento que a sua impiedade merece. Eu a rejeitei.

[[v26-31-12]]

^<<v26-31-12,12>>^ Os mais terríveis estrangeiros dentre as nações a cortaram e a abandonaram. Os seus galhos caíram sobre os montes e por todos os vales; os seus ramos jazem quebrados em todos os ribeiros da terra; todos os povos da terra se retiraram da sua sombra e a deixaram.

[[v26-31-13]]

^<<v26-31-13,13>>^ Todas as aves do céu habitarão nas suas ruínas, e todos os animais selvagens se acolherão sob os seus ramos.

[[v26-31-14]]

^<<v26-31-14,14>>^ Isso aconteceu para que todas as árvores junto às águas não elevem a sua estatura nem levantem o seu topo até as nuvens, e para que as bem-regadas não venham a confiar em si, por causa da sua altura. Porque todas foram entregues à morte, às profundezas da terra, no meio dos filhos dos homens, com os que descem à cova.

[[v26-31-15]]

^<<v26-31-15,15>>^ — Assim diz o Senhor  Deus: No dia em que a árvore desceu ao mundo dos mortos, fiz com que houvesse luto. Por causa dela, cobri o abismo, retive as suas cadeias, e as suas muitas águas se detiveram; cobri o Líbano de preto, por causa dela, e todas as árvores do campo ficaram murchas por causa dela.

[[v26-31-16]]

^<<v26-31-16,16>>^ Fiz tremer as nações ao som da sua queda, quando a fiz descer ao mundo dos mortos com os que descem ao abismo. Todas as árvores do Éden, as mais bonitas e as melhores do Líbano, todas as que foram regadas pelas águas se consolavam nas profundezas da terra.

[[v26-31-17]]

^<<v26-31-17,17>>^ Também estas, com ela, descerão ao mundo dos mortos, para juntar-se com os que foram mortos à espada; sim, os que foram o braço dela e que estavam assentados à sua sombra entre as nações.

[[v26-31-18]]

^<<v26-31-18,18>>^ — A quem, pois, você é semelhante em glória e em grandeza entre as árvores do Éden? No entanto, você descerá às profundezas da terra com as árvores do Éden. No meio dos incircuncisos, você jazerá com os que foram mortos à espada. Este é Faraó e toda a sua pompa, diz o Senhor  Deus.

'''

xref:026-ezequiel/026-ezequiel-030.adoc#v26-30-0[&#60; Capítulo Anterior] | <<v26-31-0,Topo>> | xref:026-ezequiel/026-ezequiel-032.adoc#v26-32-0[Próximo Capítulo &#62;]