include::./index.adoc[]

[[v26-14-0]]
=== Ezequiel, 14
// naa ?, NAA - Nova Almeida Atualizada

[[v26-14-1]]

^<<v26-14-1,1>>^ Então alguns dos anciãos de Israel vieram e se assentaram diante de mim.

[[v26-14-2]]

^<<v26-14-2,2>>^ A palavra do Senhor  veio a mim, dizendo:

[[v26-14-3]]

^<<v26-14-3,3>>^ — Filho do homem, estes homens levantaram ídolos dentro de seu coração e puseram diante de si o tropeço que os leva a cair em iniquidade. Será que eu deveria permitir que eles me consultem?

[[v26-14-4]]

^<<v26-14-4,4>>^ Portanto, fale com eles e diga-lhes: Assim diz o Senhor  Deus: "Qualquer homem da casa de Israel que levantar ídolos dentro de seu coração e puser diante de si tropeço que o leva a cair em iniquidade e que depois vier consultar um profeta, eu, o Senhor , lhe responderei segundo a multidão dos seus ídolos.

[[v26-14-5]]

^<<v26-14-5,5>>^ Farei isso para que eu possa conquistar novamente a casa de Israel no seu próprio coração, porque todos se afastaram de mim para seguirem os seus ídolos."

[[v26-14-6]]

^<<v26-14-6,6>>^ — Portanto, diga à casa de Israel: Assim diz o Senhor  Deus: "Convertam-se e afastem-se dos seus ídolos; desviem o rosto de todas as suas abominações.

[[v26-14-7]]

^<<v26-14-7,7>>^ Porque qualquer homem da casa de Israel ou dos estrangeiros que moram em Israel que se afastar de mim, que levantar ídolos dentro de seu coração e que depois vier consultar um profeta, para me consultar por meio dele, a esse, eu, o Senhor , responderei por mim mesmo.

[[v26-14-8]]

^<<v26-14-8,8>>^ Voltarei o rosto contra o tal homem, farei dele um sinal e provérbio e o eliminarei do meio do meu povo. E vocês saberão que eu sou o Senhor ."

[[v26-14-9]]

^<<v26-14-9,9>>^ — "Se o profeta for enganado e falar alguma coisa, fui eu, o Senhor , que enganei esse profeta; estenderei a mão contra ele e o eliminarei do meio do meu povo de Israel.

[[v26-14-10]]

^<<v26-14-10,10>>^ Ambos levarão sobre si a sua iniquidade. A iniquidade daquele que consulta será como a do profeta,

[[v26-14-11]]

^<<v26-14-11,11>>^ para que a casa de Israel não se desvie mais de mim, nem mais se contamine com todas as suas transgressões. Eles serão o meu povo, e eu serei o seu Deus", diz o Senhor  Deus.

[[v26-14-12]]

^<<v26-14-12,12>>^ A palavra do Senhor  veio a mim, dizendo:

[[v26-14-13]]

^<<v26-14-13,13>>^ — Filho do homem, quando uma terra pecar contra mim, cometendo graves transgressões, estenderei a mão contra ela, e cortarei o suprimento de pão, enviarei contra ela fome e eliminarei dela pessoas e animais.

[[v26-14-14]]

^<<v26-14-14,14>>^ Mesmo que estivessem no meio dela estes três homens, Noé, Daniel e Jó, eles, pela sua justiça, salvariam apenas a sua própria vida, diz o Senhor  Deus.

[[v26-14-15]]

^<<v26-14-15,15>>^ — Se eu fizer passar pela terra animais selvagens, e eles a devastarem, assim que fique assolada, e ninguém possa passar por ela por causa das feras,

[[v26-14-16]]

^<<v26-14-16,16>>^ tão certo como eu vivo, diz o Senhor  Deus, mesmo que esses três homens estivessem no meio dela, não salvariam nem os seus filhos nem as suas filhas; só eles seriam salvos, e a terra seria assolada.

[[v26-14-17]]

^<<v26-14-17,17>>^ — Ou se eu fizer vir a espada sobre essa terra e disser: "Espada, passe pela terra"; e eu eliminar dela pessoas e animais,

[[v26-14-18]]

^<<v26-14-18,18>>^ tão certo como eu vivo, diz o Senhor  Deus, mesmo que esses três homens estivessem no meio dela, não salvariam nem os seus filhos nem as suas filhas; só eles seriam salvos.

[[v26-14-19]]

^<<v26-14-19,19>>^ — Ou se eu enviar a peste sobre essa terra e derramar o meu furor sobre ela com sangue, para eliminar dela pessoas e animais,

[[v26-14-20]]

^<<v26-14-20,20>>^ tão certo como eu vivo, diz o Senhor  Deus, mesmo que Noé, Daniel e Jó estivessem no meio dela, não salvariam nem o seu filho nem a sua filha; pela sua justiça salvariam apenas a sua própria vida.

[[v26-14-21]]

^<<v26-14-21,21>>^ — Porque assim diz o Senhor  Deus: Quanto pior não será, se eu enviar os meus quatro piores castigos, isto é, a espada, a fome, os animais selvagens e a peste, contra Jerusalém, para eliminar dela pessoas e animais?

[[v26-14-22]]

^<<v26-14-22,22>>^ Mas eis que alguns sobreviventes serão deixados nela, filhos e filhas que serão levados para fora. Eis que eles virão a vocês, e vocês verão a sua conduta e as suas ações. E ficarão consolados do mal que eu fiz vir sobre Jerusalém, sim, de tudo o que fiz vir sobre ela.

[[v26-14-23]]

^<<v26-14-23,23>>^ Eles os consolarão quando vocês virem a sua conduta e as suas ações. E vocês saberão que não foi sem motivo que fiz tudo o que fiz nela, diz o Senhor  Deus.

'''

xref:026-ezequiel/026-ezequiel-013.adoc#v26-13-0[&#60; Capítulo Anterior] | <<v26-14-0,Topo>> | xref:026-ezequiel/026-ezequiel-015.adoc#v26-15-0[Próximo Capítulo &#62;]