include::./index.adoc[]

[[v26-47-0]]
=== Ezequiel, 47
// naa ?, NAA - Nova Almeida Atualizada

[[v26-47-1]]

^<<v26-47-1,1>>^ Depois disto, o homem me fez voltar à entrada do templo, e eis que água saía de debaixo do limiar do templo e corria na direção do leste. Porque a fachada do templo dava para o leste. A água vinha de debaixo do lado direito do templo, do lado sul do altar.

[[v26-47-2]]

^<<v26-47-2,2>>^ Ele me fez sair pelo portão do norte, para dar uma volta por fora, até o portão exterior, que dá para o leste; e eis que a água borbulhava do lado direito.

[[v26-47-3]]

^<<v26-47-3,3>>^ O homem saiu para o leste, tendo na mão um cordel de medir. Mediu quinhentos metros e me fez passar pela água, que me dava pelos tornozelos.

[[v26-47-4]]

^<<v26-47-4,4>>^ Mediu mais quinhentos metros e me fez passar pela água, que me dava pelos joelhos. Mediu mais quinhentos metros e me fez passar pela água, que agora me dava pela cintura.

[[v26-47-5]]

^<<v26-47-5,5>>^ Mediu ainda outros quinhentos metros, e era já um rio que eu não podia atravessar, porque as águas tinham crescido. Eram águas em que se podia nadar, um rio pelo qual não se podia passar andando.

[[v26-47-6]]

^<<v26-47-6,6>>^ Então ele me perguntou: — Você viu isso, filho do homem? Então o homem me levou de volta à margem do rio.

[[v26-47-7]]

^<<v26-47-7,7>>^ Quando cheguei lá, eis que à margem do rio havia grande abundância de árvores, dos dois lados do rio.

[[v26-47-8]]

^<<v26-47-8,8>>^ Então me disse: — Estas águas correm para a região leste, descem ao vale do Jordão e entram no mar, cujas águas ficarão saudáveis.

[[v26-47-9]]

^<<v26-47-9,9>>^ Todos os seres vivos que povoam os lugares por onde este rio passar terão vida. E haverá muitíssimo peixe, porque essas águas chegaram lá. As águas do mar Morto se tornarão saudáveis, e tudo viverá por onde quer que esse rio passar.

[[v26-47-10]]

^<<v26-47-10,10>>^ Junto a ele se acharão pescadores. Desde En-Gedi até En-Eglaim haverá lugar para estender e secar as redes. Os peixes serão de muitas espécies, como os peixes do mar Grande.

[[v26-47-11]]

^<<v26-47-11,11>>^ Mas os seus charcos e os seus pântanos não se tornarão saudáveis; serão deixados para o sal.

[[v26-47-12]]

^<<v26-47-12,12>>^ Nas duas margens do rio nascerá todo tipo de árvore frutífera. As folhas dessas árvores não murcharão, e elas nunca deixarão de dar o seu fruto. Produzirão frutos novos todos os meses, porque são regadas pelas águas que saem do santuário. Os seus frutos servirão de alimento, e as suas folhas, de remédio.

[[v26-47-13]]

^<<v26-47-13,13>>^ — Assim diz o Senhor  Deus: Estas serão as fronteiras pelas quais vocês repartirão a terra como herança para as doze tribos de Israel. José terá duas partes.

[[v26-47-14]]

^<<v26-47-14,14>>^ Repartam a terra em partes iguais, pois jurei dá-la aos pais de vocês. Assim, esta mesma terra lhes será dada como herança.

[[v26-47-15]]

^<<v26-47-15,15>>^ — Este será o limite da terra: do lado norte, desde o mar Grande, pelo caminho de Hetlom, até a entrada de Zedade,

[[v26-47-16]]

^<<v26-47-16,16>>^ Hamate, Berota, Sibraim, que ficam na fronteira entre Damasco e Hamate, até Hazer-Haticom, que está na fronteira de Haurã.

[[v26-47-17]]

^<<v26-47-17,17>>^ Assim, a fronteira será desde o mar até Hazar-Enom, na fronteira de Damasco, ao norte, que é também a fronteira de Hamate. Esta será a fronteira do lado norte.

[[v26-47-18]]

^<<v26-47-18,18>>^ — No lado leste, a fronteira será entre Haurã e Damasco; entre Gileade e a terra de Israel, será o Jordão; vocês medirão desde o limite do norte até o mar Morto. Esta será a fronteira do lado leste.

[[v26-47-19]]

^<<v26-47-19,19>>^ — No lado sul, a fronteira irá desde Tamar até as águas de Meribá-Cades, e então seguindo o ribeiro do Egito até o mar Grande. Esta será a fronteira do lado sul.

[[v26-47-20]]

^<<v26-47-20,20>>^ — No lado oeste, a fronteira será o mar Grande, subindo até diante da entrada de Hamate. Esta será a fronteira do lado oeste.

[[v26-47-21]]

^<<v26-47-21,21>>^ — Repartam esta terra entre vocês, segundo as tribos de Israel.

[[v26-47-22]]

^<<v26-47-22,22>>^ Vocês devem reparti-la como herança para vocês e para os estrangeiros que moram no meio de vocês, que gerarem filhos no meio de vocês. Eles deverão ser considerados como naturais entre os filhos de Israel; junto com vocês, eles receberão uma herança no meio das tribos de Israel.

[[v26-47-23]]

^<<v26-47-23,23>>^ Na tribo em que o estrangeiro estiver morando, ali vocês lhe darão a sua herança, diz o Senhor  Deus.

'''

xref:026-ezequiel/026-ezequiel-046.adoc#v26-46-0[&#60; Capítulo Anterior] | <<v26-47-0,Topo>> | xref:026-ezequiel/026-ezequiel-048.adoc#v26-48-0[Próximo Capítulo &#62;]