include::./index.adoc[]

[[v26-28-0]]
=== Ezequiel, 28
// naa ?, NAA - Nova Almeida Atualizada

[[v26-28-1]]

^<<v26-28-1,1>>^ A palavra do Senhor  veio a mim, dizendo:

[[v26-28-2]]

^<<v26-28-2,2>>^ — Filho do homem, diga ao governante de Tiro: Assim diz o Senhor  Deus: "Visto que o seu coração se eleva e você diz: ‘Eu sou um deus; sobre a cadeira de um deus me assento no coração dos mares’, sendo você um simples homem, e não um deus, ainda que pense que o seu coração é como se fosse o coração de Deus —

[[v26-28-3]]

^<<v26-28-3,3>>^ sim, você pensa que é mais sábio do que Daniel, que não há segredo algum que se possa esconder de você,

[[v26-28-4]]

^<<v26-28-4,4>>^ que pela sua sabedoria e pelo seu entendimento você alcançou o seu poder e encheu os seus tesouros de ouro e prata,

[[v26-28-5]]

^<<v26-28-5,5>>^ que pela sua grande habilidade para fazer negócios você aumentou as suas riquezas e, por causa delas, se eleva o seu coração."

[[v26-28-6]]

^<<v26-28-6,6>>^ Por isso, assim diz o Senhor  Deus: "Visto que você pensa que o seu coração é como se fosse o coração de Deus,

[[v26-28-7]]

^<<v26-28-7,7>>^ eis que trarei contra você os mais terríveis estrangeiros dentre as nações, os quais irão com a espada na mão contra a beleza da sua sabedoria e mancharão o seu resplendor.

[[v26-28-8]]

^<<v26-28-8,8>>^ Eles farão com que você desça à cova, e você sofrerá morte violenta no coração dos mares.

[[v26-28-9]]

^<<v26-28-9,9>>^ Será que você ainda vai dizer que é Deus, quando estiver diante daquele que o matará? Pois ficará claro que você é um simples homem, e não Deus, quando estiver nas mãos daqueles que o matarão.

[[v26-28-10]]

^<<v26-28-10,10>>^ Você terá uma morte horrível, nas mãos de estrangeiros, porque eu falei", diz o Senhor  Deus.

[[v26-28-11]]

^<<v26-28-11,11>>^ A palavra do Senhor  veio a mim, dizendo:

[[v26-28-12]]

^<<v26-28-12,12>>^ — Filho do homem, faça uma lamentação sobre o rei de Tiro e diga-lhe: Assim diz o Senhor  Deus: "Você era o modelo da perfeição, cheio de sabedoria e perfeito em formosura.

[[v26-28-13]]

^<<v26-28-13,13>>^ Você estava no Éden, jardim de Deus, e se cobria de todas as pedras preciosas: sárdio, topázio, diamante, berilo, ônix, jaspe, safira, carbúnculo e esmeralda. Os seus engastes e ornamentos eram feitos de ouro e foram preparados no dia em que você foi criado.

[[v26-28-14]]

^<<v26-28-14,14>>^ Você era um querubim da guarda, que foi ungido. Eu o estabeleci. Você permanecia no monte santo de Deus e andava no meio das pedras brilhantes.

[[v26-28-15]]

^<<v26-28-15,15>>^ Você era perfeito nos seus caminhos, desde o dia em que foi criado até que se achou iniquidade em você.

[[v26-28-16]]

^<<v26-28-16,16>>^ Na multiplicação do seu comércio, você se encheu de violência e pecou. Por isso, ó querubim da guarda, eu o profanei e lancei fora do monte de Deus; eu o expulsei do meio das pedras brilhantes.

[[v26-28-17]]

^<<v26-28-17,17>>^ Você ficou orgulhoso por causa da sua formosura; corrompeu a sua sabedoria por causa do seu resplendor. Por isso, eu o lancei por terra; eu o coloquei diante dos reis, para que o contemplem.

[[v26-28-18]]

^<<v26-28-18,18>>^ Pela multidão das suas iniquidades, pela injustiça do seu comércio, você profanou os seus santuários. Por isso, fiz sair do meio de você um fogo, que o consumiu; eu o reduzi a cinzas sobre a terra, aos olhos de todos os que o contemplam.

[[v26-28-19]]

^<<v26-28-19,19>>^ Todos os que o conhecem entre os povos se espantam por causa de você; você se tornou objeto de espanto e deixará de existir para sempre."

[[v26-28-20]]

^<<v26-28-20,20>>^ A palavra do Senhor  veio a mim, dizendo:

[[v26-28-21]]

^<<v26-28-21,21>>^ — Filho do homem, vire o seu rosto contra Sidom, profetize contra ela

[[v26-28-22]]

^<<v26-28-22,22>>^ e diga: Assim diz o Senhor  Deus: "Eis que eu estou contra você, ó Sidom, e serei glorificado no meio de você. Saberão que eu sou o Senhor , quando nela executar juízos e nela me santificar.

[[v26-28-23]]

^<<v26-28-23,23>>^ Pois enviarei contra ela a peste e o sangue nas suas ruas; os feridos cairão no meio dela, pela espada contra ela, por todos os lados. E saberão que eu sou o Senhor ."

[[v26-28-24]]

^<<v26-28-24,24>>^ — Para a casa de Israel já não haverá espinho que a pique, nem ferrão que cause dor, entre todos os vizinhos que a tratam com desprezo; e saberão que eu sou o Senhor  Deus.

[[v26-28-25]]

^<<v26-28-25,25>>^ — Assim diz o Senhor  Deus: Quando eu congregar a casa de Israel do meio dos povos por onde estão espalhados e eu me santificar entre eles, diante das nações, então habitarão na terra que dei ao meu servo Jacó.

[[v26-28-26]]

^<<v26-28-26,26>>^ Habitarão nela seguros, edificarão casas e plantarão vinhas. Habitarão seguros, quando eu executar juízos contra todos os que os tratam com desprezo ao redor deles; e saberão que eu sou o Senhor , o Deus de Israel.

'''

xref:026-ezequiel/026-ezequiel-027.adoc#v26-27-0[&#60; Capítulo Anterior] | <<v26-28-0,Topo>> | xref:026-ezequiel/026-ezequiel-029.adoc#v26-29-0[Próximo Capítulo &#62;]