include::./index.adoc[]

[[v26-10-0]]
=== Ezequiel, 10
// naa ?, NAA - Nova Almeida Atualizada

[[v26-10-1]]

^<<v26-10-1,1>>^ Olhei, e eis que, no firmamento que estava por cima da cabeça dos querubins, havia algo como uma pedra de safira e que parecia ser um trono.

[[v26-10-2]]

^<<v26-10-2,2>>^ E falou ao homem vestido de linho: — Vá por entre as rodas até debaixo dos querubins e encha as mãos com brasas acesas que estão entre os querubins. Depois, espalhe as brasas sobre a cidade. Ele entrou, enquanto eu observava.

[[v26-10-3]]

^<<v26-10-3,3>>^ Os querubins estavam no lado sul do templo, quando o homem entrou; e uma nuvem encheu o átrio interior.

[[v26-10-4]]

^<<v26-10-4,4>>^ Então a glória do Senhor  se levantou de sobre o querubim e foi para a entrada do templo. O templo se encheu da nuvem, e o átrio ficou cheio do brilho da glória do Senhor .

[[v26-10-5]]

^<<v26-10-5,5>>^ O ruído das asas dos querubins se ouviu até o átrio exterior, como a voz do Deus Todo-Poderoso, quando fala.

[[v26-10-6]]

^<<v26-10-6,6>>^ Quando o Senhor  ordenou ao homem vestido de linho que fosse tirar fogo do meio das rodas, do meio dos querubins, ele entrou e se pôs junto às rodas.

[[v26-10-7]]

^<<v26-10-7,7>>^ Então um dos querubins estendeu a mão para o fogo que estava entre eles, pegou algumas brasas e as pôs nas mãos do homem que estava vestido de linho, o qual as pegou e saiu.

[[v26-10-8]]

^<<v26-10-8,8>>^ Os querubins tinham debaixo das suas asas o que parecia ser mão humana.

[[v26-10-9]]

^<<v26-10-9,9>>^ Olhei, e eis quatro rodas junto aos querubins, uma roda junto a cada querubim; o aspecto das rodas era brilhante como pedra de berilo.

[[v26-10-10]]

^<<v26-10-10,10>>^ Quanto ao seu aspecto, as quatro rodas tinham a mesma aparência; eram como se uma roda estivesse dentro da outra.

[[v26-10-11]]

^<<v26-10-11,11>>^ Quando elas andavam, podiam ir em quatro direções e não se viravam quando se moviam. Para onde a primeira roda ia, as outras seguiam; e elas não se viravam quando se moviam.

[[v26-10-12]]

^<<v26-10-12,12>>^ Todo o corpo dos querubins, suas costas, as mãos, as asas e também as rodas estavam cheias de olhos ao redor.

[[v26-10-13]]

^<<v26-10-13,13>>^ Quanto às rodas, pude ouvir que foram chamadas de "giratórias".

[[v26-10-14]]

^<<v26-10-14,14>>^ Cada um dos seres viventes tinha quatro rostos: o primeiro era rosto de querubim, o segundo, rosto humano, o terceiro, rosto de leão, e o quarto, rosto de águia.

[[v26-10-15]]

^<<v26-10-15,15>>^ Os querubins se elevaram. Estes eram os mesmos seres viventes que vi junto ao rio Quebar.

[[v26-10-16]]

^<<v26-10-16,16>>^ Quando os querubins se moviam, as rodas se moviam ao lado deles; quando os querubins levantavam as suas asas, para se elevarem da terra, as rodas não se separavam deles.

[[v26-10-17]]

^<<v26-10-17,17>>^ Quando eles paravam, as rodas paravam; e, quando eles se elevavam, as rodas também se elevavam; porque o espírito dos seres viventes estava nelas.

[[v26-10-18]]

^<<v26-10-18,18>>^ Então a glória do Senhor  saiu da entrada do templo e parou sobre os querubins.

[[v26-10-19]]

^<<v26-10-19,19>>^ Os querubins levantaram as suas asas e se elevaram da terra à minha vista, quando saíram acompanhados pelas rodas. Pararam à entrada do portão leste da Casa do Senhor , e a glória do Deus de Israel estava no alto, sobre eles.

[[v26-10-20]]

^<<v26-10-20,20>>^ Estes eram os mesmos seres viventes que vi debaixo do Deus de Israel, junto ao rio Quebar, e fiquei sabendo que eram querubins.

[[v26-10-21]]

^<<v26-10-21,21>>^ Cada um tinha quatro rostos e quatro asas e, debaixo das asas, o que parecia mãos humanas.

[[v26-10-22]]

^<<v26-10-22,22>>^ A aparência dos seus rostos era como a dos rostos que eu tinha visto junto ao rio Quebar; tinham o mesmo aspecto, eram os mesmos seres. Cada um andava para a sua frente.

'''

xref:026-ezequiel/026-ezequiel-009.adoc#v26-9-0[&#60; Capítulo Anterior] | <<v26-10-0,Topo>> | xref:026-ezequiel/026-ezequiel-011.adoc#v26-11-0[Próximo Capítulo &#62;]