include::./index.adoc[]

[[v26-48-0]]
=== Ezequiel, 48
// naa ?, NAA - Nova Almeida Atualizada

[[v26-48-1]]

^<<v26-48-1,1>>^ — São estes os nomes das tribos: desde a parte extrema do norte, via Hetlom, até a entrada de Hamate, até Hazar-Enom, o limite norte de Damasco até junto de Hamate e desde o lado leste até o oeste, Dã terá uma porção.

[[v26-48-2]]

^<<v26-48-2,2>>^ Limitando-se com Dã, desde o lado leste até o lado oeste, Aser terá uma porção.

[[v26-48-3]]

^<<v26-48-3,3>>^ Limitando-se com Aser, desde o lado leste até o lado oeste, Naftali terá uma porção.

[[v26-48-4]]

^<<v26-48-4,4>>^ Limitando-se com Naftali, desde o lado leste até o lado oeste, Manassés terá uma porção.

[[v26-48-5]]

^<<v26-48-5,5>>^ Limitando-se com Manassés, desde o lado leste até o lado oeste, Efraim terá uma porção.

[[v26-48-6]]

^<<v26-48-6,6>>^ Limitando-se com Efraim, desde o lado leste até o lado oeste, Rúben terá uma porção.

[[v26-48-7]]

^<<v26-48-7,7>>^ Limitando-se com Rúben, desde o lado leste até o lado oeste, Judá terá uma porção.

[[v26-48-8]]

^<<v26-48-8,8>>^ Limitando-se com Judá, desde o lado leste até o lado oeste, ficará a região sagrada que vocês devem separar. Terá doze quilômetros e meio de largura e o mesmo comprimento que o das outras porções, desde o lado leste até o lado oeste; o santuário estará no meio dela.

[[v26-48-9]]

^<<v26-48-9,9>>^ A região que vocês devem separar ao Senhor  terá doze quilômetros e meio de comprimento e cinco quilômetros de largura.

[[v26-48-10]]

^<<v26-48-10,10>>^ Esta região sagrada será dos sacerdotes. Terá, ao norte, doze quilômetros e meio, a oeste, cinco quilômetros de largura, a leste, cinco quilômetros de largura e ao sul, doze quilômetros e meio de comprimento; o santuário do Senhor  estará no meio dela.

[[v26-48-11]]

^<<v26-48-11,11>>^ Será para os sacerdotes santificados, para os filhos de Zadoque, que cumpriram o seu dever e não se desviaram como fizeram os levitas, quando os filhos de Israel se desviaram.

[[v26-48-12]]

^<<v26-48-12,12>>^ Será uma região especial dentro da região sagrada, um lugar santíssimo, fazendo limites com a porção dos levitas.

[[v26-48-13]]

^<<v26-48-13,13>>^ — Os levitas terão uma área de doze quilômetros e meio de comprimento por cinco quilômetros de largura, paralela à porção dos sacerdotes. Seu comprimento total será de doze quilômetros e meio, e a largura será de cinco quilômetros.

[[v26-48-14]]

^<<v26-48-14,14>>^ Não poderão vender nem trocar nenhuma parte dessa área. A melhor parte da terra não pode ser transferida a outros, porque é santa para o Senhor .

[[v26-48-15]]

^<<v26-48-15,15>>^ — A área que restar, de dois quilômetros e meio de largura por doze quilômetros e meio de comprimento será para o uso civil da cidade, para habitação e para arredores; a cidade ficará no meio.

[[v26-48-16]]

^<<v26-48-16,16>>^ Estas serão as suas dimensões: o lado norte, de dois mil duzentos e cinquenta metros, o lado sul, de dois mil duzentos e cinquenta metros, o lado leste, de dois mil duzentos e cinquenta metros, e o lado oeste, de dois mil duzentos e cinquenta metros.

[[v26-48-17]]

^<<v26-48-17,17>>^ Os arredores da cidade serão, ao norte, de cento e vinte e cinco metros, ao sul, de cento e vinte e cinco metros, a leste, de cento e vinte e cinco metros e, a oeste, de cento e vinte e cinco metros.

[[v26-48-18]]

^<<v26-48-18,18>>^ Quanto à área restante, paralela à região sagrada, será de cinco quilômetros para o leste e de cinco quilômetros para o oeste; e o seu produto será para o sustento daqueles que trabalham na cidade.

[[v26-48-19]]

^<<v26-48-19,19>>^ Essa parte será cultivada pelos trabalhadores da cidade, provindos de todas as tribos de Israel.

[[v26-48-20]]

^<<v26-48-20,20>>^ A região sagrada terá doze quilômetros e meio de cada lado, formando um quadrado, e incluirá a propriedade da cidade.

[[v26-48-21]]

^<<v26-48-21,21>>^ — O que restar de ambos os lados da região sagrada e da propriedade da cidade será do príncipe. Aquilo que se estende dos doze quilômetros e meio em direção do leste e também dos doze quilômetros e meio em direção oeste, paralelamente com as porções, será do príncipe; a região sagrada e o santuário do templo estarão no meio.

[[v26-48-22]]

^<<v26-48-22,22>>^ A área que pertence aos levitas e à cidade estará no meio daquilo que pertence ao príncipe. A área entre o território de Judá e o território de Benjamim será do príncipe.

[[v26-48-23]]

^<<v26-48-23,23>>^ — Quanto ao resto das tribos, desde o lado leste até o lado oeste, Benjamim terá uma porção.

[[v26-48-24]]

^<<v26-48-24,24>>^ Limitando-se com Benjamim, desde o lado leste até o lado oeste, Simeão terá uma porção.

[[v26-48-25]]

^<<v26-48-25,25>>^ Limitando-se com Simeão, desde o lado leste até o lado oeste, Issacar terá uma porção.

[[v26-48-26]]

^<<v26-48-26,26>>^ Limitando-se com Issacar, desde o lado leste até o lado oeste, Zebulom terá uma porção.

[[v26-48-27]]

^<<v26-48-27,27>>^ Limitando-se com Zebulom, desde o lado leste até o lado oeste, Gade terá uma porção.

[[v26-48-28]]

^<<v26-48-28,28>>^ Limitando-se com o território de Gade, ao sul, o limite será desde Tamar até as águas de Meribá-Cades, ao longo do ribeiro do Egito até o mar Grande.

[[v26-48-29]]

^<<v26-48-29,29>>^ — Esta é a terra que vocês repartirão como herança para as tribos de Israel, e estas são as suas porções, diz o Senhor  Deus.

[[v26-48-30]]

^<<v26-48-30,30>>^ — São estas as saídas da cidade: do lado norte, que mede dois mil duzentos e cinquenta metros,

[[v26-48-31]]

^<<v26-48-31,31>>^ três portões: o portão de Rúben, o de Judá e o de Levi, sendo que os portões da cidade terão os nomes das tribos de Israel;

[[v26-48-32]]

^<<v26-48-32,32>>^ do lado leste, dois mil duzentos e cinquenta metros e três portões, a saber: o portão de José, o de Benjamim e o de Dã;

[[v26-48-33]]

^<<v26-48-33,33>>^ do lado sul, dois mil duzentos e cinquenta metros e três portões: o portão de Simeão, o de Issacar e o de Zebulom;

[[v26-48-34]]

^<<v26-48-34,34>>^ do lado oeste, dois mil duzentos e cinquenta metros e os seus três portões: o portão de Gade, o de Aser e o de Naftali.

[[v26-48-35]]

^<<v26-48-35,35>>^ O contorno será de nove quilômetros. E o nome da cidade desde aquele dia será: "O Senhor  Está Ali".

'''

xref:026-ezequiel/026-ezequiel-047.adoc#v26-47-0[&#60; Capítulo Anterior] | <<v26-48-0,Topo>> | xref:027-daniel/027-daniel-001.adoc#v27-1-0[Próximo Capítulo &#62;]