include::./index.adoc[]

[[v26-2-0]]
=== Ezequiel, 2
// naa ?, NAA - Nova Almeida Atualizada

[[v26-2-1]]

^<<v26-2-1,1>>^ Esta voz me disse: — Filho do homem, fique em pé, e falarei com você.

[[v26-2-2]]

^<<v26-2-2,2>>^ Enquanto falava comigo, o Espírito entrou em mim e me fez ficar em pé, e ouvi aquele que falava comigo.

[[v26-2-3]]

^<<v26-2-3,3>>^ Ele me disse: — Filho do homem, eu vou enviá-lo aos filhos de Israel, às nações rebeldes que se rebelaram contra mim. Eles e os pais deles se revoltaram contra mim, até precisamente o dia de hoje.

[[v26-2-4]]

^<<v26-2-4,4>>^ Os filhos têm a mente fechada e o coração endurecido. Eu vou enviá-lo até eles, e você lhes dirá: "Assim diz o Senhor  Deus."

[[v26-2-5]]

^<<v26-2-5,5>>^ Eles, quer ouçam quer deixem de ouvir, porque são casa rebelde, saberão que um profeta esteve no meio deles.

[[v26-2-6]]

^<<v26-2-6,6>>^ — Você, filho do homem, não tenha medo deles nem do que eles disserem. Mesmo que você esteja entre sarças e espinhos e more com escorpiões, não tenha medo do que eles disserem nem se assuste com o rosto deles, porque são casa rebelde.

[[v26-2-7]]

^<<v26-2-7,7>>^ Você lhes dirá as minhas palavras, quer ouçam quer deixem de ouvir, pois são rebeldes.

[[v26-2-8]]

^<<v26-2-8,8>>^ — Você, filho do homem, ouça o que eu lhe digo: não seja rebelde como essa gente. Abra a boca e coma o que eu vou lhe dar.

[[v26-2-9]]

^<<v26-2-9,9>>^ Então olhei, e eis que certa mão se estendia para mim, e nela se achava o rolo de um livro.

[[v26-2-10]]

^<<v26-2-10,10>>^ Ela o desenrolou diante de mim, e estava escrito por dentro e por fora. No rolo, estavam escritas lamentações, gemidos e ais.

'''

xref:026-ezequiel/026-ezequiel-001.adoc#v26-1-0[&#60; Capítulo Anterior] | <<v26-2-0,Topo>> | xref:026-ezequiel/026-ezequiel-003.adoc#v26-3-0[Próximo Capítulo &#62;]