include::./index.adoc[]

[[v26-9-0]]
=== Ezequiel, 9
// naa ?, NAA - Nova Almeida Atualizada

[[v26-9-1]]

^<<v26-9-1,1>>^ Então ouvi que ele gritava em alta voz, dizendo: — Venham cá, vocês que estão encarregados da cidade, cada um com a sua arma destruidora na mão.

[[v26-9-2]]

^<<v26-9-2,2>>^ Eis que vinham seis homens pelo caminho do portão superior, que dá para o norte, cada um com a sua arma esmagadora na mão. Entre eles estava um homem vestido de linho, com um estojo de escriba à cintura. Eles entraram e se puseram junto ao altar de bronze.

[[v26-9-3]]

^<<v26-9-3,3>>^ A glória do Deus de Israel se levantou do querubim sobre o qual estava, indo até a entrada do templo. E o Senhor  clamou ao homem vestido de linho, que tinha o estojo de escriba à cintura,

[[v26-9-4]]

^<<v26-9-4,4>>^ e lhe disse: — Passe pelo meio da cidade, pelo meio de Jerusalém, e marque com um sinal a testa daqueles que suspiram e gemem por causa de todas as abominações que se cometem no meio dela.

[[v26-9-5]]

^<<v26-9-5,5>>^ Depois ouvi o Senhor  dizer aos outros homens: — Passem pela cidade após ele e matem! Que os olhos de vocês não tenham piedade e não poupem ninguém.

[[v26-9-6]]

^<<v26-9-6,6>>^ Matem os velhos, os jovens, as moças, as crianças e as mulheres, até exterminá-los. Mas não se aproximem de ninguém que tiver o sinal na testa. Comecem pelo meu santuário. Então começaram pelos anciãos que estavam diante do templo.

[[v26-9-7]]

^<<v26-9-7,7>>^ E ele lhes disse: — Contaminem o templo! Encham de mortos os seus átrios! Vão! Eles saíram e começaram a matar na cidade.

[[v26-9-8]]

^<<v26-9-8,8>>^ Enquanto a matança continuava, fiquei ali sozinho. Caí com o rosto em terra, clamei e disse: — Ah! Senhor  Deus! Será que vais destruir todo o restante de Israel, derramando o teu furor sobre Jerusalém?

[[v26-9-9]]

^<<v26-9-9,9>>^ Então me respondeu: — A iniquidade da casa de Israel e de Judá é excessivamente grande, a terra se encheu de sangue, e a cidade, de injustiça. E eles ainda dizem: "O Senhor  abandonou a terra, o Senhor  não nos vê."

[[v26-9-10]]

^<<v26-9-10,10>>^ Quanto a mim, os meus olhos não terão piedade, e não pouparei ninguém. Eu lhes darei o que merecem por seus atos.

[[v26-9-11]]

^<<v26-9-11,11>>^ Então o homem que estava vestido de linho e que tinha o estojo de escriba à cintura relatou, dizendo: — Fiz como me ordenaste.

'''

xref:026-ezequiel/026-ezequiel-008.adoc#v26-8-0[&#60; Capítulo Anterior] | <<v26-9-0,Topo>> | xref:026-ezequiel/026-ezequiel-010.adoc#v26-10-0[Próximo Capítulo &#62;]