include::./index.adoc[]

[[v26-33-0]]
=== Ezequiel, 33
// naa ?, NAA - Nova Almeida Atualizada

[[v26-33-1]]

^<<v26-33-1,1>>^ A palavra do Senhor  veio a mim, dizendo:

[[v26-33-2]]

^<<v26-33-2,2>>^ — Filho do homem, fale com os filhos de seu povo e diga-lhes: Quando eu fizer vir um exército inimigo sobre uma terra, se o povo dessa terra escolher um homem do meio deles e o constituir por seu atalaia,

[[v26-33-3]]

^<<v26-33-3,3>>^ e se, ao ver que o inimigo se aproxima, esse atalaia tocar a trombeta e avisar o povo,

[[v26-33-4]]

^<<v26-33-4,4>>^ então aquele que ouvir o som da trombeta e não se der por avisado, se o inimigo vier e o abater, esse será responsável pela sua própria morte.

[[v26-33-5]]

^<<v26-33-5,5>>^ Ele ouviu o som da trombeta e não se deu por avisado; será responsável por sua própria morte. Se ele tivesse dado atenção ao aviso, salvaria a sua vida.

[[v26-33-6]]

^<<v26-33-6,6>>^ Mas, se o atalaia vir que vem o inimigo e não tocar a trombeta, e o povo não for avisado, se o inimigo vier e abater um deles, este foi abatido na sua maldade, mas quem será responsável pela morte dele é o atalaia.

[[v26-33-7]]

^<<v26-33-7,7>>^ — Quanto a você, filho do homem, eu o constituí por atalaia sobre a casa de Israel. Portanto, você ouvirá a palavra da minha boca e lhes dará aviso da minha parte.

[[v26-33-8]]

^<<v26-33-8,8>>^ Se eu disser ao ímpio que ele certamente morrerá, e você não falar, para advertir o ímpio do seu mau caminho, esse ímpio morrerá na sua maldade, mas você será responsável pela morte dele.

[[v26-33-9]]

^<<v26-33-9,9>>^ Mas, se você falar ao ímpio, para o avisar do seu mau caminho, para que dele se converta, e ele não se converter do seu caminho, esse ímpio morrerá na sua maldade, mas você terá salvo a sua vida.

[[v26-33-10]]

^<<v26-33-10,10>>^ — Filho do homem, diga à casa de Israel: Vocês dizem: "Visto que as nossas transgressões e os nossos pecados estão sobre nós, e nós desfalecemos por causa deles, como poderemos viver?"

[[v26-33-11]]

^<<v26-33-11,11>>^ Diga-lhes: Tão certo como eu vivo, diz o Senhor  Deus, não tenho prazer na morte do ímpio, mas em que o ímpio se converta do seu caminho e viva. Convertam-se! Convertam-se dos seus maus caminhos! Por que vocês haveriam de morrer, ó casa de Israel?

[[v26-33-12]]

^<<v26-33-12,12>>^ — Filho do homem, diga aos filhos do seu povo: A justiça do justo não o livrará no dia da sua transgressão. Quanto à maldade do ímpio, não cairá por ela, no dia em que se converter da sua maldade; nem o justo pela sua justiça poderá viver no dia em que pecar.

[[v26-33-13]]

^<<v26-33-13,13>>^ Quando eu disser ao justo que certamente viverá, e ele, confiando na sua justiça, fizer maldade, não me lembrarei de nenhum dos seus atos de justiça, e ele morrerá por causa da injustiça que cometeu.

[[v26-33-14]]

^<<v26-33-14,14>>^ E, quando eu disser ao ímpio que certamente morrerá, e ele se converter do seu pecado, fizer o que é justo e reto,

[[v26-33-15]]

^<<v26-33-15,15>>^ restituir o penhor, devolver o que roubou, andar nos estatutos da vida e não fizer maldade, certamente viverá; não morrerá.

[[v26-33-16]]

^<<v26-33-16,16>>^ De todos os pecados que cometeu, nenhum deles será lembrado contra ele. Fez o que é justo e reto; certamente viverá.

[[v26-33-17]]

^<<v26-33-17,17>>^ — No entanto, os filhos do seu povo dizem: "O caminho do Senhor não é reto." Mas é o caminho deles que não é reto.

[[v26-33-18]]

^<<v26-33-18,18>>^ Se o justo se desviar da sua justiça e fizer maldade, morrerá nela.

[[v26-33-19]]

^<<v26-33-19,19>>^ E, se o ímpio se converter da sua maldade e fizer o que é justo e reto, por causa desses atos viverá.

[[v26-33-20]]

^<<v26-33-20,20>>^ No entanto, vocês dizem: "O caminho do Senhor não é reto." Mas eu os julgarei, cada um segundo os seus caminhos, ó casa de Israel.

[[v26-33-21]]

^<<v26-33-21,21>>^ No décimo segundo ano do nosso exílio, aos cinco dias do décimo mês, veio a mim um sobrevivente de Jerusalém, dizendo: "A cidade caiu."

[[v26-33-22]]

^<<v26-33-22,22>>^ Ora, na tarde do dia anterior, antes da chegada desse sobrevivente, a mão do Senhor  havia estado sobre mim e eu recuperei a fala. Assim, pela manhã, antes de chegar aquele homem, eu havia recuperado a fala, e não fiquei mais em silêncio.

[[v26-33-23]]

^<<v26-33-23,23>>^ Então a palavra do Senhor  veio a mim, dizendo:

[[v26-33-24]]

^<<v26-33-24,24>>^ — Filho do homem, os moradores desses lugares desertos da terra de Israel estão dizendo: "Abraão era um só, mas possuiu esta terra. Ora, como nós somos muitos, certamente esta terra nos foi dada como propriedade."

[[v26-33-25]]

^<<v26-33-25,25>>^ — Por isso, diga-lhes: Assim diz o Senhor  Deus: "Vocês comem carne com sangue, levantam os olhos para os seus ídolos, cometem assassinatos, e ainda pensam que hão de possuir a terra?

[[v26-33-26]]

^<<v26-33-26,26>>^ Vocês confiam em suas espadas, cometem abominações, cada um de vocês contamina a mulher do seu próximo, e ainda pensam que hão de possuir a terra?"

[[v26-33-27]]

^<<v26-33-27,27>>^ Diga-lhes que assim diz o Senhor  Deus: "Tão certo como eu vivo, os que estiverem em lugares desertos cairão à espada, e o que estiver em campo aberto, eu o entregarei aos animais selvagens, para que o devorem, e os que estiverem em fortalezas e em cavernas morrerão de peste.

[[v26-33-28]]

^<<v26-33-28,28>>^ Tornarei a terra em desolação e espanto, e o orgulho do seu poder chegará ao fim. Os montes de Israel ficarão tão desolados, que ninguém passará por eles.

[[v26-33-29]]

^<<v26-33-29,29>>^ Então saberão que eu sou o Senhor , quando eu tornar a terra em desolação e espanto, por todas as abominações que cometeram."

[[v26-33-30]]

^<<v26-33-30,30>>^ — Quanto a você, filho do homem, os filhos do seu povo falam de você junto às paredes e nas portas das casas, dizendo um ao outro, cada um ao seu irmão: "Venham, vamos ouvir a palavra que procede do Senhor ."

[[v26-33-31]]

^<<v26-33-31,31>>^ Eles vêm até você, como o povo costuma vir, assentam-se diante de você como meu povo e ouvem as suas palavras, mas não as põem em prática. Com a boca, professam muito amor, mas o coração deles só ambiciona lucro.

[[v26-33-32]]

^<<v26-33-32,32>>^ Para eles você não passa de alguém que canta canções de amor, tem uma bela voz e é um bom músico, porque ouvem as suas palavras, mas não as põem em prática.

[[v26-33-33]]

^<<v26-33-33,33>>^ Mas, quando isso vier — e certamente virá —, então saberão que um profeta esteve no meio deles.

'''

xref:026-ezequiel/026-ezequiel-032.adoc#v26-32-0[&#60; Capítulo Anterior] | <<v26-33-0,Topo>> | xref:026-ezequiel/026-ezequiel-034.adoc#v26-34-0[Próximo Capítulo &#62;]