include::./index.adoc[]

[[v61-1-0]]
=== 2 Pedro, 1
// naa ?, NAA - Nova Almeida Atualizada

[[v61-1-1]]

^<<v61-1-1,1>>^ Simão Pedro, servo e apóstolo de Jesus Cristo, aos que conosco obtiveram fé igualmente preciosa na justiça do nosso Deus e Salvador Jesus Cristo.

[[v61-1-2]]

^<<v61-1-2,2>>^ Que a graça e a paz lhes sejam multiplicadas, no pleno conhecimento de Deus e de Jesus, nosso Senhor.

[[v61-1-3]]

^<<v61-1-3,3>>^ Pelo poder de Deus nos foram concedidas todas as coisas que conduzem à vida e à piedade, pelo pleno conhecimento daquele que nos chamou para a sua própria glória e virtude.

[[v61-1-4]]

^<<v61-1-4,4>>^ Por meio delas, ele nos concedeu as suas preciosas e mui grandes promessas, para que por elas vocês se tornem coparticipantes da natureza divina, tendo escapado da corrupção das paixões que há no mundo.

[[v61-1-5]]

^<<v61-1-5,5>>^ Por causa disso, concentrando todos os seus esforços, acrescentem à fé que vocês têm a virtude; à virtude, o conhecimento;

[[v61-1-6]]

^<<v61-1-6,6>>^ ao conhecimento, o domínio próprio; ao domínio próprio, a perseverança; à perseverança, a piedade;

[[v61-1-7]]

^<<v61-1-7,7>>^ à piedade, a fraternidade; à fraternidade, o amor.

[[v61-1-8]]

^<<v61-1-8,8>>^ Porque essas qualidades, estando presentes e aumentando cada vez mais, farão com que vocês não sejam nem inativos, nem infrutíferos no pleno conhecimento do nosso Senhor Jesus Cristo.

[[v61-1-9]]

^<<v61-1-9,9>>^ Pois aquele que não tem estas coisas é cego, vendo só o que está perto, e se esqueceu da purificação dos seus antigos pecados.

[[v61-1-10]]

^<<v61-1-10,10>>^ Por isso, irmãos, procurem, com empenho cada vez maior, confirmar a vocação e a eleição de vocês; porque, fazendo assim, vocês jamais tropeçarão.

[[v61-1-11]]

^<<v61-1-11,11>>^ Pois desta maneira é que lhes será amplamente suprida a entrada no Reino eterno do nosso Senhor e Salvador Jesus Cristo.

[[v61-1-12]]

^<<v61-1-12,12>>^ Por esta razão, sempre estarei pronto para fazer com que vocês se lembrem destas coisas, embora já as conheçam e tenham sido confirmados na verdade que receberam.

[[v61-1-13]]

^<<v61-1-13,13>>^ Também considero justo, enquanto estou neste tabernáculo, despertar essas lembranças em vocês,

[[v61-1-14]]

^<<v61-1-14,14>>^ certo de que estou prestes a deixar o meu tabernáculo, como efetivamente nosso Senhor Jesus Cristo me revelou.

[[v61-1-15]]

^<<v61-1-15,15>>^ Mas, de minha parte, me esforçarei ao máximo para que sempre, mesmo depois da minha partida, vocês se lembrem dessas coisas.

[[v61-1-16]]

^<<v61-1-16,16>>^ Porque não lhes demos a conhecer o poder e a vinda do nosso Senhor Jesus Cristo seguindo fábulas engenhosamente inventadas, mas nós mesmos fomos testemunhas oculares da sua majestade.

[[v61-1-17]]

^<<v61-1-17,17>>^ Porque ele recebeu honra e glória da parte de Deus Pai, quando, pela Suprema Glória, lhe foi enviada a seguinte voz: "Este é o meu Filho amado, em quem me agrado."

[[v61-1-18]]

^<<v61-1-18,18>>^ Ora, nós ouvimos esta voz vinda do céu quando estávamos com ele no monte santo.

[[v61-1-19]]

^<<v61-1-19,19>>^ Assim, temos ainda mais segura a palavra profética, e vocês fazem bem em dar atenção a ela, como a uma luz que brilha em lugar escuro, até que o dia clareie e a estrela da alva nasça no coração de vocês.

[[v61-1-20]]

^<<v61-1-20,20>>^ Primeiramente, porém, saibam que nenhuma profecia da Escritura provém de interpretação pessoal;

[[v61-1-21]]

^<<v61-1-21,21>>^ porque nunca jamais qualquer profecia foi dada por vontade humana; entretanto, homens falaram da parte de Deus, movidos pelo Espírito Santo.

'''

xref:060-1-pedro/060-1-pedro-005.adoc#v60-5-0[&#60; Capítulo Anterior] | <<v61-1-0,Topo>> | xref:061-2-pedro/061-2-pedro-002.adoc#v61-2-0[Próximo Capítulo &#62;]