include::./index.adoc[]

[[v61-2-0]]
=== 2 Pedro, 2
// naa ?, NAA - Nova Almeida Atualizada

[[v61-2-1]]

^<<v61-2-1,1>>^ Assim como surgiram falsos profetas no meio do povo, também haverá falsos mestres entre vocês. Eles introduzirão heresias destruidoras, chegando a renegar o Soberano Senhor que os resgatou, trazendo sobre si mesmos repentina destruição.

[[v61-2-2]]

^<<v61-2-2,2>>^ E muitos seguirão as suas práticas libertinas, e, por causa deles, o caminho da verdade será difamado.

[[v61-2-3]]

^<<v61-2-3,3>>^ Movidos por avareza, eles explorarão vocês com palavras fictícias. Mas, para eles, a condenação decretada há muito tempo não tarda, e a destruição deles não caiu no esquecimento.

[[v61-2-4]]

^<<v61-2-4,4>>^ Pois Deus não poupou anjos quando pecaram, mas, lançando-os no inferno, prendeu-os com correntes de escuridão, reservando-os para o juízo.

[[v61-2-5]]

^<<v61-2-5,5>>^ E ele não poupou o mundo antigo, mas preservou Noé, pregador da justiça, e mais sete pessoas, quando fez vir o dilúvio sobre o mundo de ímpios.

[[v61-2-6]]

^<<v61-2-6,6>>^ E, reduzindo a cinzas as cidades de Sodoma e Gomorra, condenou-as à ruína completa, tendo-as posto como exemplo do que viria a acontecer com os que vivessem impiamente;

[[v61-2-7]]

^<<v61-2-7,7>>^ mas livrou o justo Ló, que ficava aflito com a conduta libertina daqueles insubordinados.

[[v61-2-8]]

^<<v61-2-8,8>>^ Porque esse homem justo, pelo que via e ouvia ao morar entre eles, atormentava a sua alma justa, dia após dia, por causa das obras iníquas que aqueles praticavam.

[[v61-2-9]]

^<<v61-2-9,9>>^ Assim, o Senhor sabe livrar da provação os piedosos e manter os injustos sob castigo, para o Dia do Juízo,

[[v61-2-10]]

^<<v61-2-10,10>>^ especialmente aqueles que, seguindo a carne, andam em desejos impuros e desprezam qualquer autoridade. Atrevidos, arrogantes, não temem difamar os gloriosos seres celestiais,

[[v61-2-11]]

^<<v61-2-11,11>>^ ao passo que anjos, embora maiores em força e poder, não proferem contra essas autoridades sentença difamatória na presença do Senhor.

[[v61-2-12]]

^<<v61-2-12,12>>^ Esses, porém, como animais irracionais, seres guiados pelo instinto e que nascem para serem capturados e mortos, falando mal daquilo que não entendem, na sua destruição também hão de ser destruídos,

[[v61-2-13]]

^<<v61-2-13,13>>^ recebendo injustiça como pagamento pela injustiça que praticam. Encontram prazer na satisfação de seus desejos libertinos em pleno dia. Como manchas e defeitos, encontram satisfação nas suas próprias mentiras, enquanto se banqueteiam com vocês.

[[v61-2-14]]

^<<v61-2-14,14>>^ Eles têm os olhos cheios de adultério e são insaciáveis no pecado. Enganam almas inconstantes e têm o coração exercitado na avareza, essa gente maldita.

[[v61-2-15]]

^<<v61-2-15,15>>^ Tendo abandonado o reto caminho, desviaram-se e seguiram pelo caminho de Balaão, filho de Beor, que amou o pagamento pela injustiça.

[[v61-2-16]]

^<<v61-2-16,16>>^ Mas ele foi repreendido pela sua transgressão: um animal de carga mudo, falando com voz humana, refreou a insensatez do profeta.

[[v61-2-17]]

^<<v61-2-17,17>>^ Esses tais são fontes sem água, névoas levadas pela tempestade, para os quais está reservada a mais profunda escuridão.

[[v61-2-18]]

^<<v61-2-18,18>>^ Porque, falando com arrogância palavras sem conteúdo, enganam com desejos libertinos de natureza carnal aqueles que de fato estavam se afastando dos que vivem no erro.

[[v61-2-19]]

^<<v61-2-19,19>>^ Prometem-lhes a liberdade, quando eles mesmos são escravos da corrupção, pois aquele que é vencido fica escravo do vencedor.

[[v61-2-20]]

^<<v61-2-20,20>>^ Portanto, se, depois de terem escapado das contaminações do mundo mediante o conhecimento do Senhor e Salvador Jesus Cristo, se deixam enredar de novo e são vencidos, o seu último estado se tornou pior do que o primeiro.

[[v61-2-21]]

^<<v61-2-21,21>>^ Pois teria sido melhor que eles nunca tivessem conhecido o caminho da justiça do que, após conhecê-lo, voltar atrás e se afastar do santo mandamento que lhes havia sido dado.

[[v61-2-22]]

^<<v61-2-22,22>>^ Com eles aconteceu o que diz certo provérbio muito verdadeiro: "O cão volta ao seu próprio vômito." E: "A porca lavada volta a rolar na lama."

'''

xref:061-2-pedro/061-2-pedro-001.adoc#v61-1-0[&#60; Capítulo Anterior] | <<v61-2-0,Topo>> | xref:061-2-pedro/061-2-pedro-003.adoc#v61-3-0[Próximo Capítulo &#62;]