include::./index.adoc[]

[[v38-11-0]]
=== Zacarias, 11
// naa ?, NAA - Nova Almeida Atualizada

[[v38-11-1]]

^<<v38-11-1,1>>^ Abra as suas portas, ó Líbano, para que o fogo consuma os seus cedros.

[[v38-11-2]]

^<<v38-11-2,2>>^ Chorem, ciprestes, porque os cedros caíram, porque as mais excelentes árvores foram destruídas. Chorem, carvalhos de Basã, porque a densa floresta foi derrubada.

[[v38-11-3]]

^<<v38-11-3,3>>^ Eis a voz de choro dos pastores, porque a sua glória foi destruída! Eis o rugido dos leõezinhos, porque o orgulho do Jordão foi destruído!

[[v38-11-4]]

^<<v38-11-4,4>>^ — Assim diz o Senhor , meu Deus: Apascente as ovelhas destinadas para o matadouro.

[[v38-11-5]]

^<<v38-11-5,5>>^ Aqueles que as compram matam-nas e não são punidos; os que as vendem dizem: "Louvado seja o Senhor ! Ficamos ricos!" E os pastores das ovelhas não se compadecem delas.

[[v38-11-6]]

^<<v38-11-6,6>>^ Certamente não terei mais compaixão dos moradores desta terra, diz o Senhor . Eis que eu entregarei cada um nas mãos do seu próximo e nas mãos do seu rei. Eles destruirão o país, e eu não os livrarei das mãos deles.

[[v38-11-7]]

^<<v38-11-7,7>>^ Apascentei as ovelhas destinadas para o matadouro pelos negociantes das ovelhas. Peguei dois cajados: a um chamei "Graça", e a outro, "União". E apascentei as ovelhas.

[[v38-11-8]]

^<<v38-11-8,8>>^ Em um mês destruí três pastores. Perdi a paciência com eles, e também eles se cansaram de mim.

[[v38-11-9]]

^<<v38-11-9,9>>^ Então eu disse: — Não serei mais o pastor de vocês. Quem tiver de morrer, que morra! Quem tiver de ser destruído, que seja! E os que restarem, que cada um coma a carne do seu próximo.

[[v38-11-10]]

^<<v38-11-10,10>>^ Peguei o cajado chamado Graça e o quebrei, para anular a minha aliança, que eu havia feito com todos os povos.

[[v38-11-11]]

^<<v38-11-11,11>>^ Portanto, a aliança foi anulada naquele dia. E os negociantes de ovelhas, que estavam me observando, reconheceram que isto era palavra do Senhor .

[[v38-11-12]]

^<<v38-11-12,12>>^ Eu lhes disse: — Se estiverem de acordo, paguem o meu salário; se não, deixem por isso mesmo. Então pesaram o meu salário: trinta moedas de prata.

[[v38-11-13]]

^<<v38-11-13,13>>^ Então o Senhor  me disse: — Pegue esse dinheiro, esse magnífico preço em que fui avaliado por eles, e jogue para o oleiro. Peguei as trinta moedas de prata e as joguei para o oleiro, na Casa do Senhor .

[[v38-11-14]]

^<<v38-11-14,14>>^ Depois, quebrei o segundo cajado, chamado União, para romper a irmandade entre Judá e Israel.

[[v38-11-15]]

^<<v38-11-15,15>>^ O Senhor  me disse: — Agora pegue os apetrechos de um pastor insensato.

[[v38-11-16]]

^<<v38-11-16,16>>^ Porque eis que eu levantarei na terra um pastor que não cuidará das ovelhas que estão perecendo, não buscará a desgarrada, não curará a que foi ferida, nem apascentará a sã, mas comerá a carne das ovelhas gordas e arrancará até os cascos delas.

[[v38-11-17]]

^<<v38-11-17,17>>^ Ai do pastor inútil, que abandona o rebanho! A espada cairá sobre o seu braço e sobre o seu olho direito; o braço ficará completamente seco, e o olho direito totalmente cego.

'''

xref:038-zacarias/038-zacarias-010.adoc#v38-10-0[&#60; Capítulo Anterior] | <<v38-11-0,Topo>> | xref:038-zacarias/038-zacarias-012.adoc#v38-12-0[Próximo Capítulo &#62;]