include::./index.adoc[]

[[v38-4-0]]
=== Zacarias, 4
// naa ?, NAA - Nova Almeida Atualizada

[[v38-4-1]]

^<<v38-4-1,1>>^ O anjo que falava comigo voltou e me despertou, como se desperta alguém do sono.

[[v38-4-2]]

^<<v38-4-2,2>>^ Ele me perguntou: — O que você está vendo? Respondi: — Vejo um candelabro todo de ouro e um vaso de azeite em cima com as suas sete lâmpadas e sete tubos, um para cada uma das lâmpadas que estão em cima do candelabro.

[[v38-4-3]]

^<<v38-4-3,3>>^ Junto ao candelabro vejo duas oliveiras, uma à direita do vaso de azeite, e a outra à sua esquerda.

[[v38-4-4]]

^<<v38-4-4,4>>^ Então perguntei ao anjo que falava comigo: — Meu senhor, o que é isto?

[[v38-4-5]]

^<<v38-4-5,5>>^ O anjo que falava comigo disse: — Você não sabe o que é isto? Respondi: — Não, meu senhor.

[[v38-4-6]]

^<<v38-4-6,6>>^ Ele prosseguiu e me disse: — Esta é a palavra do Senhor  a Zorobabel: "Não por força nem por poder, mas pelo meu Espírito", diz o Senhor  dos Exércitos.

[[v38-4-7]]

^<<v38-4-7,7>>^ — "Quem é você, ó grande monte? Diante de Zorobabel você será uma planície. Porque ele colocará a pedra de remate do templo, em meio a aclamações: ‘Haja graça e graça para ela!’"

[[v38-4-8]]

^<<v38-4-8,8>>^ Novamente a palavra do Senhor  veio a mim, dizendo:

[[v38-4-9]]

^<<v38-4-9,9>>^ — As mãos de Zorobabel lançaram os alicerces deste templo, e as mãos dele vão terminar a construção, para que vocês saibam que o Senhor  dos Exércitos é quem me enviou a vocês.

[[v38-4-10]]

^<<v38-4-10,10>>^ Pois quem despreza o dia dos humildes começos, esse ficará alegre ao ver o prumo nas mãos de Zorobabel. Aqueles sete olhos são os olhos do Senhor , que percorrem toda a terra.

[[v38-4-11]]

^<<v38-4-11,11>>^ Então perguntei ao anjo: — O que são as duas oliveiras à direita e à esquerda do candelabro?

[[v38-4-12]]

^<<v38-4-12,12>>^ E acrescentei uma segunda pergunta: — O que são aqueles dois ramos de oliveira que estão junto aos dois tubos de ouro, que vertem azeite dourado?

[[v38-4-13]]

^<<v38-4-13,13>>^ Ele me respondeu: — Você não sabe o que é isto? Eu respondi: — Não, meu senhor.

[[v38-4-14]]

^<<v38-4-14,14>>^ Então ele disse: — São os dois ungidos, que estão a serviço do Senhor de toda a terra.

'''

xref:038-zacarias/038-zacarias-003.adoc#v38-3-0[&#60; Capítulo Anterior] | <<v38-4-0,Topo>> | xref:038-zacarias/038-zacarias-005.adoc#v38-5-0[Próximo Capítulo &#62;]