include::./index.adoc[]

[[v38-10-0]]
=== Zacarias, 10
// naa ?, NAA - Nova Almeida Atualizada

[[v38-10-1]]

^<<v38-10-1,1>>^ Peçam ao Senhor  chuva no tempo das últimas chuvas; peçam ao Senhor , que faz as nuvens de chuva, e ele lhes dará chuva abundante e a cada um, a vegetação no campo.

[[v38-10-2]]

^<<v38-10-2,2>>^ Porque os ídolos do lar falam coisas vãs e os adivinhos veem mentiras e contam sonhos enganadores; oferecem consolações vazias. Por isso, o povo anda como ovelhas, aflito por não ter pastor.

[[v38-10-3]]

^<<v38-10-3,3>>^ "É contra os pastores que se acendeu a minha ira; castigarei os bodes que vão adiante do rebanho. Mas o Senhor  dos Exércitos cuidará do seu rebanho, a casa de Judá, e fará dela o seu majestoso cavalo na batalha.

[[v38-10-4]]

^<<v38-10-4,4>>^ De Judá sairá a pedra angular; dele, a estaca da tenda; dele, o arco de guerra; dele sairão todos os chefes juntos.

[[v38-10-5]]

^<<v38-10-5,5>>^ E serão como valentes que, na batalha, pisam aos pés os seus inimigos na lama das ruas. Lutarão, porque o Senhor está com eles, e envergonharão os que andam montados em cavalos."

[[v38-10-6]]

^<<v38-10-6,6>>^ "Fortalecerei a casa de Judá e salvarei a casa de José. Eu os farei voltar, porque me compadeço deles; e serão como se eu não os tivesse rejeitado, porque eu sou o Senhor , seu Deus, e os ouvirei.

[[v38-10-7]]

^<<v38-10-7,7>>^ Os de Efraim serão como um valente, e o seu coração se alegrará como se tivessem bebido vinho; os seus filhos verão isso e se alegrarão; o seu coração exultará no Senhor .

[[v38-10-8]]

^<<v38-10-8,8>>^ Eu lhes assobiarei e os reunirei, porque já os remi; eles se multiplicarão como antes tinham se multiplicado.

[[v38-10-9]]

^<<v38-10-9,9>>^ Embora eu os tenha espalhado entre os povos, eles se lembram de mim em lugares distantes; continuarão vivos com os seus filhos e voltarão.

[[v38-10-10]]

^<<v38-10-10,10>>^ Porque eu os farei voltar da terra do Egito e os congregarei da Assíria. Eu os trarei à terra de Gileade e ao Líbano, e não haverá lugar para todos.

[[v38-10-11]]

^<<v38-10-11,11>>^ Passarão pelo mar de angústia, serão feridas as ondas do mar, e todas as profundezas do Nilo se secarão. Então será derrubado o orgulho da Assíria, e o cetro do Egito será removido.

[[v38-10-12]]

^<<v38-10-12,12>>^ Eu os fortalecerei no Senhor , e eles andarão no meu nome", diz o Senhor .

'''

xref:038-zacarias/038-zacarias-009.adoc#v38-9-0[&#60; Capítulo Anterior] | <<v38-10-0,Topo>> | xref:038-zacarias/038-zacarias-011.adoc#v38-11-0[Próximo Capítulo &#62;]