include::./index.adoc[]

[[v38-9-0]]
=== Zacarias, 9
// naa ?, NAA - Nova Almeida Atualizada

[[v38-9-1]]

^<<v38-9-1,1>>^ A sentença pronunciada pelo Senhor é contra a terra de Hadraque e repousa sobre Damasco, porque o Senhor  põe os olhos sobre a humanidade e sobre todas as tribos de Israel.

[[v38-9-2]]

^<<v38-9-2,2>>^ Também repousa sobre Hamate, que faz fronteira com Damasco, e sobre Tiro e Sidom, cuja sabedoria é grande.

[[v38-9-3]]

^<<v38-9-3,3>>^ Tiro edificou para si uma fortaleza e amontoou prata como pó, e ouro como lama das ruas.

[[v38-9-4]]

^<<v38-9-4,4>>^ Eis que o Senhor tomará posse da cidade e jogará as riquezas dela no mar; e Tiro será consumida pelo fogo.

[[v38-9-5]]

^<<v38-9-5,5>>^ Asquelom verá isso e ficará com medo. Também Gaza ficará com medo e terá grande dor. Igualmente Ecrom, porque a sua esperança estará perdida. O rei de Gaza perecerá, e Asquelom não será habitada.

[[v38-9-6]]

^<<v38-9-6,6>>^ Um povo bastardo habitará em Asdode, e exterminarei o orgulho dos filisteus.

[[v38-9-7]]

^<<v38-9-7,7>>^ Da boca destes tirarei a carne com sangue e, dos seus dentes, as suas abominações. Então eles ficarão como um resto para o nosso Deus, e serão como chefes em Judá; e Ecrom será como os jebuseus.

[[v38-9-8]]

^<<v38-9-8,8>>^ Eu me acamparei ao redor da minha casa para defendê-la contra forças invasoras, para que ninguém passe, nem volte. Nunca mais passará sobre eles o opressor, porque agora vejo isso com os meus próprios olhos.

[[v38-9-9]]

^<<v38-9-9,9>>^ Alegre-se muito, ó filha de Sião! Exulte, ó filha de Jerusalém! Eis que o seu rei vem até você, justo e salvador, humilde, montado em jumento, num jumentinho, cria de jumenta.

[[v38-9-10]]

^<<v38-9-10,10>>^ Destruirei os carros de guerra de Efraim e os cavalos de Jerusalém; os arcos de guerra serão destruídos. Ele anunciará paz às nações; o seu domínio se estenderá de mar a mar e desde o Eufrates até os confins da terra.

[[v38-9-11]]

^<<v38-9-11,11>>^ Quanto a você, Sião, por causa do sangue da minha aliança com você, tirei os seus cativos da cova em que não havia água.

[[v38-9-12]]

^<<v38-9-12,12>>^ Voltem para a fortaleza, ó prisioneiros da esperança! Também hoje anuncio que lhes restituirei tudo em dobro.

[[v38-9-13]]

^<<v38-9-13,13>>^ Porque entesei Judá como meu arco de guerra e fiz de Efraim a minha flecha. Levantarei os seus filhos, ó Sião, contra os filhos da Grécia, e farei você semelhante à espada de um valente.

[[v38-9-14]]

^<<v38-9-14,14>>^ O Senhor  será visto sobre os filhos de Sião, e as suas flechas sairão como o relâmpago. O Senhor  Deus fará soar a trombeta e irá com os redemoinhos do Sul.

[[v38-9-15]]

^<<v38-9-15,15>>^ O Senhor  dos Exércitos protegerá o seu povo. Eles engolirão os inimigos e pisarão nas pedras atiradas com as fundas. Também beberão o sangue deles como se fosse vinho; eles se encherão como as bacias do sacrifício e ficarão ensopados como os cantos do altar.

[[v38-9-16]]

^<<v38-9-16,16>>^ Naquele dia, o Senhor , seu Deus, os salvará, como o rebanho do seu povo; porque eles são pedras de uma coroa e resplandecem na terra dele.

[[v38-9-17]]

^<<v38-9-17,17>>^ Pois quão grande é a sua bondade! E quão grande é a sua formosura! O trigo fará florescer os jovens, e o vinho, as moças.

'''

xref:038-zacarias/038-zacarias-008.adoc#v38-8-0[&#60; Capítulo Anterior] | <<v38-9-0,Topo>> | xref:038-zacarias/038-zacarias-010.adoc#v38-10-0[Próximo Capítulo &#62;]