include::./index.adoc[]

[[v38-7-0]]
=== Zacarias, 7
// naa ?, NAA - Nova Almeida Atualizada

[[v38-7-1]]

^<<v38-7-1,1>>^ No quarto ano do reinado de Dario, no quarto dia do nono mês, que é o mês de quisleu, a palavra do Senhor  veio a Zacarias.

[[v38-7-2]]

^<<v38-7-2,2>>^ Ora, o povo de Betel tinha enviado Sarezer, Regém-Meleque e seus companheiros, para suplicarem o favor do Senhor ,

[[v38-7-3]]

^<<v38-7-3,3>>^ perguntando aos sacerdotes, que estavam na Casa do Senhor  dos Exércitos, e aos profetas: "Devemos nós continuar a chorar, com jejum, no quinto mês, como temos feito por tantos anos?"

[[v38-7-4]]

^<<v38-7-4,4>>^ Então a palavra do Senhor  dos Exércitos veio a mim, dizendo:

[[v38-7-5]]

^<<v38-7-5,5>>^ — Pergunte a todo o povo desta terra e aos sacerdotes: Quando vocês jejuaram e prantearam, no quinto e no sétimo mês, durante estes setenta anos, será que foi realmente para mim que vocês jejuaram?

[[v38-7-6]]

^<<v38-7-6,6>>^ Quando vocês comem e bebem, não é para vocês mesmos que comem e bebem?

[[v38-7-7]]

^<<v38-7-7,7>>^ Será que vocês não ouviram as palavras que o Senhor  pregou pelo ministério dos profetas que nos precederam, quando Jerusalém estava habitada e em paz com as suas cidades ao redor dela, e o Sul e a Sefelá eram habitados?

[[v38-7-8]]

^<<v38-7-8,8>>^ A palavra do Senhor  veio a Zacarias, dizendo:

[[v38-7-9]]

^<<v38-7-9,9>>^ — Assim falou o Senhor  dos Exércitos: "Julguem segundo a verdade e sejam bondosos e misericordiosos uns com os outros.

[[v38-7-10]]

^<<v38-7-10,10>>^ Não oprimam a viúva, nem o órfão, nem o estrangeiro, nem o pobre, e que ninguém faça planos para prejudicar o seu próximo."

[[v38-7-11]]

^<<v38-7-11,11>>^ Porém eles não quiseram atender e, rebeldes, me viraram as costas e taparam os ouvidos, para que não ouvissem.

[[v38-7-12]]

^<<v38-7-12,12>>^ Sim, fizeram o seu coração duro como diamante, para que não ouvissem a lei, nem as palavras que o Senhor  dos Exércitos tinha enviado pelo seu Espírito, mediante os profetas que nos precederam; daí veio a grande ira do Senhor  dos Exércitos.

[[v38-7-13]]

^<<v38-7-13,13>>^ Visto que eu clamei, e eles não me ouviram, eles também clamaram, e eu não os ouvi, diz o Senhor  dos Exércitos.

[[v38-7-14]]

^<<v38-7-14,14>>^ Com uma tempestade, eu os espalhei por todas as nações que eles não conheciam. E a terra foi devastada atrás deles, de modo que ninguém passava por ela, nem voltava; porque da terra desejável fizeram uma desolação.

'''

xref:038-zacarias/038-zacarias-006.adoc#v38-6-0[&#60; Capítulo Anterior] | <<v38-7-0,Topo>> | xref:038-zacarias/038-zacarias-008.adoc#v38-8-0[Próximo Capítulo &#62;]