include::./index.adoc[]

[[v38-8-0]]
=== Zacarias, 8
// naa ?, NAA - Nova Almeida Atualizada

[[v38-8-1]]

^<<v38-8-1,1>>^ A palavra do Senhor  dos Exércitos veio a mim, dizendo:

[[v38-8-2]]

^<<v38-8-2,2>>^ — Assim diz o Senhor  dos Exércitos: Tenho grande amor por Sião. É um amor tão grande que me leva à indignação contra os seus inimigos.

[[v38-8-3]]

^<<v38-8-3,3>>^ — Assim diz o Senhor : Voltarei para Sião e habitarei no meio de Jerusalém. E Jerusalém será chamada de "Cidade Fiel", e o monte do Senhor  dos Exércitos será chamado de "Monte Santo".

[[v38-8-4]]

^<<v38-8-4,4>>^ — Assim diz o Senhor  dos Exércitos: Os velhos e as velhas voltarão a sentar-se nas praças de Jerusalém, levando cada um na mão a sua bengala, por causa da sua muita idade.

[[v38-8-5]]

^<<v38-8-5,5>>^ As praças da cidade se encherão de meninos e meninas, que nelas brincarão.

[[v38-8-6]]

^<<v38-8-6,6>>^ — Assim diz o Senhor  dos Exércitos: Isso pode parecer impossível aos olhos do remanescente deste povo naqueles dias, mas não será impossível para mim, diz o Senhor  dos Exércitos.

[[v38-8-7]]

^<<v38-8-7,7>>^ — Assim diz o Senhor  dos Exércitos: Eis que salvarei o meu povo, tirando-o da terra do Oriente e da terra do Ocidente.

[[v38-8-8]]

^<<v38-8-8,8>>^ Eu os trarei, e habitarão em Jerusalém. Eles serão o meu povo, e eu serei o seu Deus, em verdade e em justiça.

[[v38-8-9]]

^<<v38-8-9,9>>^ — Assim diz o Senhor  dos Exércitos: Sejam fortes, todos vocês que nestes dias estão ouvindo estas palavras da boca dos profetas, a saber, nos dias em que foram lançados os alicerces da Casa do Senhor  dos Exércitos, para que o templo fosse construído.

[[v38-8-10]]

^<<v38-8-10,10>>^ Porque, antes daqueles dias, não havia salário para os trabalhadores, nem pagamento pelo trabalho dos animais. Não havia paz para o que entrava, nem para o que saía, por causa dos inimigos, porque eu incitei cada um contra o seu próximo.

[[v38-8-11]]

^<<v38-8-11,11>>^ Mas, agora, não tratarei o remanescente deste povo como tratei o povo no passado, diz o Senhor  dos Exércitos.

[[v38-8-12]]

^<<v38-8-12,12>>^ Porque haverá semeadura em paz, as videiras darão o seu fruto, a terra, as suas colheitas, e os céus, o seu orvalho. E farei com que o remanescente deste povo herde tudo isso.

[[v38-8-13]]

^<<v38-8-13,13>>^ Casa de Judá e casa de Israel, assim como vocês foram uma maldição entre as nações, assim agora eu os salvarei, e vocês serão uma bênção. Não tenham medo! Pelo contrário, sejam fortes!

[[v38-8-14]]

^<<v38-8-14,14>>^ — Porque assim diz o Senhor  dos Exércitos: Assim como eu havia decidido castigar vocês, quando os seus pais me provocaram à ira, diz o Senhor  dos Exércitos, e não mudei de ideia,

[[v38-8-15]]

^<<v38-8-15,15>>^ também decidi agora fazer bem a Jerusalém e à casa de Judá nestes dias. Não tenham medo!

[[v38-8-16]]

^<<v38-8-16,16>>^ Eis as coisas que vocês devem fazer: Que cada um fale a verdade com o seu próximo. Nos tribunais, julguem com justiça, segundo a verdade, em favor da paz.

[[v38-8-17]]

^<<v38-8-17,17>>^ Que ninguém faça planos para prejudicar o seu próximo, nem ame o juramento falso, porque eu odeio todas estas coisas, diz o Senhor .

[[v38-8-18]]

^<<v38-8-18,18>>^ A palavra do Senhor  dos Exércitos veio a mim, dizendo:

[[v38-8-19]]

^<<v38-8-19,19>>^ — Assim diz o Senhor  dos Exércitos: O jejum do quarto mês, o do quinto, o do sétimo e o do décimo serão para a casa de Judá um dia de júbilo, alegria e festividades solenes. Portanto, amem a verdade e a paz.

[[v38-8-20]]

^<<v38-8-20,20>>^ — Assim diz o Senhor  dos Exércitos: Ainda virão povos e moradores de muitas cidades,

[[v38-8-21]]

^<<v38-8-21,21>>^ e os moradores de uma cidade irão à outra, dizendo: "Vamos depressa suplicar o favor do Senhor  e buscar o Senhor  dos Exércitos; eu também irei."

[[v38-8-22]]

^<<v38-8-22,22>>^ Muitos povos e nações poderosas virão a Jerusalém buscar o Senhor  dos Exércitos e suplicar o favor do Senhor .

[[v38-8-23]]

^<<v38-8-23,23>>^ — Assim diz o Senhor  dos Exércitos: Naqueles dias, dez homens, de todas as línguas das nações, pegarão, sim, pegarão na borda da roupa de um judeu e lhe dirão: "Queremos ir com vocês, porque ouvimos que Deus está com vocês."

'''

xref:038-zacarias/038-zacarias-007.adoc#v38-7-0[&#60; Capítulo Anterior] | <<v38-8-0,Topo>> | xref:038-zacarias/038-zacarias-009.adoc#v38-9-0[Próximo Capítulo &#62;]