include::./index.adoc[]

[[v38-1-0]]
=== Zacarias, 1
// naa ?, NAA - Nova Almeida Atualizada

[[v38-1-1]]

^<<v38-1-1,1>>^ No oitavo mês do segundo ano do reinado de Dario, a palavra do Senhor  veio ao profeta Zacarias, filho de Baraquias, filho de Ido, dizendo:

[[v38-1-2]]

^<<v38-1-2,2>>^ — O Senhor  ficou muito irado com os pais de vocês.

[[v38-1-3]]

^<<v38-1-3,3>>^ Portanto, diga-lhes: Assim diz o Senhor  dos Exércitos: "Voltem para mim, diz o Senhor  dos Exércitos, e eu voltarei para vocês, diz o Senhor  dos Exércitos.

[[v38-1-4]]

^<<v38-1-4,4>>^ Não sejam como os seus pais. Quando os primeiros profetas clamavam: ‘Assim diz o Senhor  dos Exércitos: Convertam-se dos seus maus caminhos e das suas obras más’, eles não ouviram nem me deram atenção, diz o Senhor .

[[v38-1-5]]

^<<v38-1-5,5>>^ Os pais de vocês, onde estão? E os profetas, será que ainda estão vivos?

[[v38-1-6]]

^<<v38-1-6,6>>^ E não é fato que as minhas palavras e os meus estatutos, que eu prescrevi aos profetas, meus servos, alcançaram os pais de vocês? Sim, estes se arrependeram e disseram: ‘Como o Senhor  dos Exércitos tinha intenção de nos tratar, segundo os nossos caminhos e segundo as nossas obras, assim ele nos tratou.’"

[[v38-1-7]]

^<<v38-1-7,7>>^ No vigésimo quarto dia do décimo primeiro mês, que é o mês de sebate, no segundo ano do reinado de Dario, a palavra do Senhor  veio ao profeta Zacarias, filho de Baraquias, filho de Ido.

[[v38-1-8]]

^<<v38-1-8,8>>^ Tive de noite uma visão, e eis um homem montado num cavalo vermelho. Ele estava parado entre as murtas que havia num vale profundo. Atrás dele se achavam cavalos vermelhos, baios e brancos.

[[v38-1-9]]

^<<v38-1-9,9>>^ Então perguntei: — Meu senhor, quem são estes? E o anjo que falava comigo respondeu: — Eu lhe mostrarei quem são eles.

[[v38-1-10]]

^<<v38-1-10,10>>^ Então o homem que estava entre as murtas disse: — Eles são os que o Senhor  enviou para percorrerem a terra.

[[v38-1-11]]

^<<v38-1-11,11>>^ Eles responderam ao anjo do Senhor , que estava entre as murtas, e disseram: — Nós já percorremos a terra, e eis que toda a terra está, agora, calma e tranquila.

[[v38-1-12]]

^<<v38-1-12,12>>^ Então o anjo do Senhor  disse: — Ó Senhor  dos Exércitos, até quando não terás compaixão de Jerusalém e das cidades de Judá, contra as quais estás indignado há setenta anos?

[[v38-1-13]]

^<<v38-1-13,13>>^ E o Senhor  respondeu com palavras boas, palavras consoladoras, ao anjo que falava comigo.

[[v38-1-14]]

^<<v38-1-14,14>>^ E este me disse: — Proclame: Assim diz o Senhor  dos Exércitos: "Tenho grande amor por Jerusalém e Sião.

[[v38-1-15]]

^<<v38-1-15,15>>^ E, com grande indignação, estou irado contra as nações que vivem confiantes. Porque eu estava um pouco indignado, mas elas agravaram o mal.

[[v38-1-16]]

^<<v38-1-16,16>>^ Portanto, assim diz o Senhor : Voltei-me para Jerusalém com misericórdia, e nela será reconstruído o meu templo, diz o Senhor  dos Exércitos. E o cordel será estendido sobre Jerusalém."

[[v38-1-17]]

^<<v38-1-17,17>>^ — Proclame outra vez, dizendo: Assim diz o Senhor  dos Exércitos: "As minhas cidades voltarão a transbordar de bens; o Senhor  voltará a consolar Sião e voltará a escolher Jerusalém."

[[v38-1-18]]

^<<v38-1-18,18>>^ Levantei os olhos e vi, e eis quatro chifres.

[[v38-1-19]]

^<<v38-1-19,19>>^ Perguntei ao anjo que falava comigo: — O que é isto? Ele me respondeu: — São os chifres que dispersaram Judá, Israel e Jerusalém.

[[v38-1-20]]

^<<v38-1-20,20>>^ O Senhor  me mostrou quatro ferreiros.

[[v38-1-21]]

^<<v38-1-21,21>>^ Então perguntei: — O que é que eles vêm fazer? Ele respondeu: — Aqueles são os chifres que dispersaram Judá, de maneira que ninguém pode levantar a cabeça. Mas estes ferreiros vieram para os amedrontar, para derrubar os chifres das nações que levantaram o seu poder contra a terra de Judá, para a espalhar.

'''

xref:037-ageu/037-ageu-002.adoc#v37-2-0[&#60; Capítulo Anterior] | <<v38-1-0,Topo>> | xref:038-zacarias/038-zacarias-002.adoc#v38-2-0[Próximo Capítulo &#62;]