include::./index.adoc[]

[[v38-2-0]]
=== Zacarias, 2
// naa ?, NAA - Nova Almeida Atualizada

[[v38-2-1]]

^<<v38-2-1,1>>^ Levantei os olhos e vi, e eis um homem que tinha na mão um cordel de medir.

[[v38-2-2]]

^<<v38-2-2,2>>^ Então perguntei: — Para onde você vai? Ele me respondeu: — Vou medir Jerusalém, para saber a sua largura e o seu comprimento.

[[v38-2-3]]

^<<v38-2-3,3>>^ Eis que o anjo que falava comigo se afastou, e outro anjo veio se encontrar com ele.

[[v38-2-4]]

^<<v38-2-4,4>>^ E lhe disse: — Corra e diga àquele jovem: "Jerusalém será habitada como as aldeias sem muralhas, por causa do grande número de pessoas e de animais que haverá nela.

[[v38-2-5]]

^<<v38-2-5,5>>^ Pois eu serei uma muralha de fogo ao redor dela, diz o Senhor , eu mesmo serei, no meio dela, a sua glória."

[[v38-2-6]]

^<<v38-2-6,6>>^ — Vamos! Vamos! Fujam da terra do Norte, diz o Senhor , porque eu espalhei vocês como os quatro ventos do céu, diz o Senhor .

[[v38-2-7]]

^<<v38-2-7,7>>^ Vamos! Fuja, Sião, você que habita com a filha da Babilônia.

[[v38-2-8]]

^<<v38-2-8,8>>^ — Pois assim diz o Senhor  dos Exércitos: Para obter a glória, ele me enviou às nações que saquearam os bens de vocês. Porque aquele que tocar em vocês toca na menina dos meus olhos.

[[v38-2-9]]

^<<v38-2-9,9>>^ Porque eis que agitarei a mão contra eles, e eles virão a ser a presa daqueles que os serviram. Assim vocês saberão que o Senhor  dos Exércitos é quem me enviou.

[[v38-2-10]]

^<<v38-2-10,10>>^ — Alegre-se e cante, ó filha de Sião, porque eis que venho e habitarei no meio de você, diz o Senhor .

[[v38-2-11]]

^<<v38-2-11,11>>^ Naquele dia, muitas nações se juntarão ao Senhor  e serão o meu povo. Habitarei em seu meio, e vocês saberão que o Senhor  dos Exércitos é quem me enviou a vocês.

[[v38-2-12]]

^<<v38-2-12,12>>^ Então o Senhor  herdará a terra de Judá como a sua porção na terra santa e voltará a escolher Jerusalém.

[[v38-2-13]]

^<<v38-2-13,13>>^ Calem-se todos diante do Senhor , porque ele se levantou da sua santa morada.

'''

xref:038-zacarias/038-zacarias-001.adoc#v38-1-0[&#60; Capítulo Anterior] | <<v38-2-0,Topo>> | xref:038-zacarias/038-zacarias-003.adoc#v38-3-0[Próximo Capítulo &#62;]