include::./index.adoc[]

[[v38-5-0]]
=== Zacarias, 5
// naa ?, NAA - Nova Almeida Atualizada

[[v38-5-1]]

^<<v38-5-1,1>>^ Tornei a levantar os olhos e vi, e eis um livro em forma de rolo que voava.

[[v38-5-2]]

^<<v38-5-2,2>>^ O anjo me perguntou: — O que você está vendo? Eu respondi: — Vejo um rolo voando, que tem nove metros de comprimento e quatro metros e meio de largura.

[[v38-5-3]]

^<<v38-5-3,3>>^ Então ele me disse: — Esta é a maldição que sai pela face de toda a terra. Porque quem roubar será expulso segundo a maldição, e quem jurar falsamente será expulso também segundo a mesma maldição.

[[v38-5-4]]

^<<v38-5-4,4>>^ Enviarei essa maldição, diz o Senhor  dos Exércitos, e a farei entrar na casa do ladrão e na casa do que jurar falsamente pelo meu nome; ela ficará nessas casas e consumirá a sua madeira e as suas pedras.

[[v38-5-5]]

^<<v38-5-5,5>>^ O anjo que falava comigo saiu e me disse: — Levante os olhos e veja o que é isto que está saindo.

[[v38-5-6]]

^<<v38-5-6,6>>^ Eu perguntei: — O que é isto? Ele me respondeu: — É um cesto que serve para medir. E acrescentou: — Isto é a iniquidade em toda a terra.

[[v38-5-7]]

^<<v38-5-7,7>>^ Então foi levantada a tampa de chumbo que cobria o cesto, e eis que uma mulher estava sentada dentro do cesto.

[[v38-5-8]]

^<<v38-5-8,8>>^ O anjo explicou: — Isto é a maldade. E a empurrou para o fundo do cesto, sobre cuja boca pôs o peso de chumbo.

[[v38-5-9]]

^<<v38-5-9,9>>^ Levantei os olhos e vi, e eis que saíram duas mulheres. Havia vento em suas asas, que eram como de cegonha; e levantaram o cesto entre a terra e o céu.

[[v38-5-10]]

^<<v38-5-10,10>>^ Então perguntei ao anjo que falava comigo: — Para onde elas estão levando o cesto?

[[v38-5-11]]

^<<v38-5-11,11>>^ Ele respondeu: — Para a terra de Sinar, onde edificarão um templo para aquela mulher. Quando o templo estiver concluído, ela será posta ali em seu próprio lugar.

'''

xref:038-zacarias/038-zacarias-004.adoc#v38-4-0[&#60; Capítulo Anterior] | <<v38-5-0,Topo>> | xref:038-zacarias/038-zacarias-006.adoc#v38-6-0[Próximo Capítulo &#62;]