include::./index.adoc[]

[[v38-14-0]]
=== Zacarias, 14
// naa ?, NAA - Nova Almeida Atualizada

[[v38-14-1]]

^<<v38-14-1,1>>^ Eis que vem o Dia do Senhor , em que o seu despojo será repartido dentro de você, ó Jerusalém.

[[v38-14-2]]

^<<v38-14-2,2>>^ Porque eu ajuntarei todas as nações para a batalha contra Jerusalém. A cidade será tomada, as casas serão saqueadas e as mulheres, violentadas. Metade da cidade será levada para o cativeiro, mas o restante do povo não será expulso da cidade.

[[v38-14-3]]

^<<v38-14-3,3>>^ Então o Senhor  sairá e lutará contra essas nações, como ele costumava lutar no dia da batalha.

[[v38-14-4]]

^<<v38-14-4,4>>^ Naquele dia, os seus pés estarão sobre o monte das Oliveiras, que está em frente de Jerusalém, para o leste. O monte das Oliveiras será fendido pelo meio, do leste ao oeste, formando um grande vale. Metade do monte se afastará para o norte, e a outra metade, para o sul.

[[v38-14-5]]

^<<v38-14-5,5>>^ Vocês fugirão pelo meu vale entre os montes, porque esse vale chegará até Azal. Sim, vocês fugirão como fugiram do terremoto nos dias de Uzias, rei de Judá. Então virá o Senhor , meu Deus, e todos os santos virão com ele.

[[v38-14-6]]

^<<v38-14-6,6>>^ Naquele dia, não haverá luz, mas frio e gelo.

[[v38-14-7]]

^<<v38-14-7,7>>^ Mas será um dia singular, um dia conhecido do Senhor . Não haverá separação entre dia e noite, pois mesmo depois de anoitecer ainda será dia claro.

[[v38-14-8]]

^<<v38-14-8,8>>^ Naquele dia, águas vivas correrão de Jerusalém, metade delas para o mar oriental, e a outra metade para o mar ocidental; isso acontecerá tanto no verão como no inverno.

[[v38-14-9]]

^<<v38-14-9,9>>^ O Senhor  será Rei sobre toda a terra. Naquele dia, um só será o Senhor , e um só será o seu nome.

[[v38-14-10]]

^<<v38-14-10,10>>^ Toda a terra se tornará em planície, desde Geba até Rimom, ao sul de Jerusalém. Mas Jerusalém será exaltada e habitada no seu lugar, desde o Portão de Benjamim até o lugar do primeiro portão, até o Portão da Esquina e desde a Torre de Hananel até os lagares do rei.

[[v38-14-11]]

^<<v38-14-11,11>>^ Será habitada, e já não haverá maldição; Jerusalém habitará segura.

[[v38-14-12]]

^<<v38-14-12,12>>^ Esta será a praga com que o Senhor  castigará todos os povos que guerrearem contra Jerusalém: a carne deles apodrecerá, estando eles em pé, os seus olhos apodrecerão nas suas órbitas, e a língua deles apodrecerá na boca.

[[v38-14-13]]

^<<v38-14-13,13>>^ Naquele dia, também haverá da parte do Senhor  grande confusão entre eles; cada um agarrará a mão do seu próximo, cada um levantará a mão contra o seu próximo.

[[v38-14-14]]

^<<v38-14-14,14>>^ Também Judá irá lutar em Jerusalém. E se ajuntarão as riquezas de todas as nações vizinhas: ouro, prata e roupas em grande abundância.

[[v38-14-15]]

^<<v38-14-15,15>>^ Como esta praga, assim será a praga dos cavalos, das mulas, dos camelos, dos jumentos e de todos os animais que estiverem naqueles arraiais.

[[v38-14-16]]

^<<v38-14-16,16>>^ Todos os que restarem de todas as nações que vieram contra Jerusalém subirão de ano em ano para adorar o Rei, o Senhor  dos Exércitos, e para celebrar a Festa dos Tabernáculos.

[[v38-14-17]]

^<<v38-14-17,17>>^ Se algum dos povos da terra não subir a Jerusalém, para adorar o Rei, o Senhor  dos Exércitos, esse povo ficará sem chuva.

[[v38-14-18]]

^<<v38-14-18,18>>^ Se os egípcios não subirem, nem vierem, ficarão sem chuva; virá sobre eles a praga com que o Senhor  castigará as nações que não subirem para celebrar a Festa dos Tabernáculos.

[[v38-14-19]]

^<<v38-14-19,19>>^ Este será o castigo dos egípcios e o castigo de todas as nações que não subirem para celebrar a Festa dos Tabernáculos.

[[v38-14-20]]

^<<v38-14-20,20>>^ Naquele dia, será gravado nas campainhas dos cavalos: "Santo ao Senhor ", e as panelas do templo do Senhor  serão como as bacias diante do altar;

[[v38-14-21]]

^<<v38-14-21,21>>^ sim, todas as panelas em Jerusalém e em Judá serão santas ao Senhor  dos Exércitos. Todos os que oferecerem sacrifícios usarão essas panelas para cozinhar a carne do sacrifício. Naquele dia, não haverá mais comerciantes no templo do Senhor  dos Exércitos.

'''

xref:038-zacarias/038-zacarias-013.adoc#v38-13-0[&#60; Capítulo Anterior] | <<v38-14-0,Topo>> | xref:039-malaquias/039-malaquias-001.adoc#v39-1-0[Próximo Capítulo &#62;]