include::./index.adoc[]

[[v38-3-0]]
=== Zacarias, 3
// naa ?, NAA - Nova Almeida Atualizada

[[v38-3-1]]

^<<v38-3-1,1>>^ Deus me mostrou o sumo sacerdote Josué, que estava diante do Anjo do Senhor ; mostrou também Satanás, que estava à direita de Josué, para o acusar.

[[v38-3-2]]

^<<v38-3-2,2>>^ Mas o Senhor  disse a Satanás: — Que o Senhor  o repreenda, Satanás! Sim, que o Senhor , que escolheu Jerusalém, o repreenda! Não é este um toco de lenha tirado do fogo?

[[v38-3-3]]

^<<v38-3-3,3>>^ Ora, Josué estava diante do Anjo vestido com roupas muito sujas.

[[v38-3-4]]

^<<v38-3-4,4>>^ O Anjo tomou a palavra e disse aos que estavam diante dele: — Tirem as roupas sujas que ele está usando. E a Josué ele disse: — Eis que tirei de você a sua iniquidade e agora o vestirei com roupas finas.

[[v38-3-5]]

^<<v38-3-5,5>>^ Então eu disse: — Ponham um turbante limpo na cabeça dele. Puseram um turbante limpo na cabeça dele e o vestiram, na presença do Anjo do Senhor ,

[[v38-3-6]]

^<<v38-3-6,6>>^ que disse a Josué:

[[v38-3-7]]

^<<v38-3-7,7>>^ — Assim diz o Senhor  dos Exércitos: Se você andar nos meus caminhos e observar os meus preceitos, você julgará o meu templo e guardará os meus átrios. Eu lhe darei livre acesso entre estes que aqui se encontram.

[[v38-3-8]]

^<<v38-3-8,8>>^ Portanto, escute, Josué, sumo sacerdote, você e os seus companheiros que estão sentados diante de você, porque estes homens são um sinal do que há de vir: eis que eu farei vir o meu servo, o Renovo.

[[v38-3-9]]

^<<v38-3-9,9>>^ Porque eis aqui a pedra que pus diante de Josué; sobre esta pedra única estão sete olhos. Eis que eu gravarei nela uma inscrição, diz o Senhor  dos Exércitos, e tirarei a iniquidade desta terra num só dia.

[[v38-3-10]]

^<<v38-3-10,10>>^ Naquele dia, diz o Senhor  dos Exércitos, cada um de vocês convidará o seu próximo para sentar-se debaixo da videira e debaixo da figueira.

'''

xref:038-zacarias/038-zacarias-002.adoc#v38-2-0[&#60; Capítulo Anterior] | <<v38-3-0,Topo>> | xref:038-zacarias/038-zacarias-004.adoc#v38-4-0[Próximo Capítulo &#62;]