include::./index.adoc[]

[[v38-6-0]]
=== Zacarias, 6
// naa ?, NAA - Nova Almeida Atualizada

[[v38-6-1]]

^<<v38-6-1,1>>^ Outra vez levantei os olhos e vi, e eis que quatro carruagens saíam do meio de dois montes, e estes montes eram de bronze.

[[v38-6-2]]

^<<v38-6-2,2>>^ Na primeira carruagem, os cavalos eram vermelhos; na segunda, eram pretos;

[[v38-6-3]]

^<<v38-6-3,3>>^ na terceira, eram brancos; e na quarta, eram baios. Todos eram fortes.

[[v38-6-4]]

^<<v38-6-4,4>>^ Então perguntei ao anjo que falava comigo: — Meu senhor, o que é isto?

[[v38-6-5]]

^<<v38-6-5,5>>^ O anjo respondeu: — São os quatro ventos do céu, que saem de onde estavam diante do Senhor de toda a terra.

[[v38-6-6]]

^<<v38-6-6,6>>^ A carruagem em que estão os cavalos pretos sai para a terra do Norte. Os cavalos brancos saem após eles, e os cavalos baios vão para a terra do Sul.

[[v38-6-7]]

^<<v38-6-7,7>>^ Assim, os cavalos fortes saem, forcejando para seguir adiante, para percorrerem a terra. O Senhor  lhes disse: — Vão e percorram a terra. E eles percorriam a terra.

[[v38-6-8]]

^<<v38-6-8,8>>^ Então ele me chamou e me disse: — Eis que aqueles que saíram para a terra do Norte fazem o meu Espírito repousar na terra do Norte.

[[v38-6-9]]

^<<v38-6-9,9>>^ A palavra do Senhor  veio a mim, dizendo:

[[v38-6-10]]

^<<v38-6-10,10>>^ — Receba o que foi trazido pelos exilados Heldai, Tobias e Jedaías, que voltaram da Babilônia, e no mesmo dia entre na casa de Josias, filho de Sofonias.

[[v38-6-11]]

^<<v38-6-11,11>>^ Receba a prata e o ouro, faça uma coroa e coloque-a na cabeça do sumo sacerdote Josué, filho de Jozadaque.

[[v38-6-12]]

^<<v38-6-12,12>>^ E diga-lhe: Assim diz o Senhor  dos Exércitos: "Eis aqui o homem cujo nome é Renovo. Ele brotará do seu lugar e edificará o templo do Senhor .

[[v38-6-13]]

^<<v38-6-13,13>>^ Ele mesmo edificará o templo do Senhor  e será revestido de glória. Ele se assentará no seu trono, e dominará, e será sacerdote no seu trono; e reinará perfeita união entre ambos os ofícios.

[[v38-6-14]]

^<<v38-6-14,14>>^ A coroa será para Helém, para Tobias, para Jedaías e para Hem, filho de Sofonias, como memorial no templo do Senhor .

[[v38-6-15]]

^<<v38-6-15,15>>^ Aqueles que estão longe virão e ajudarão a edificar o templo do Senhor , e vocês saberão que o Senhor  dos Exércitos me enviou a vocês. Isto acontecerá se vocês ouvirem atentamente a voz do Senhor , seu Deus."

'''

xref:038-zacarias/038-zacarias-005.adoc#v38-5-0[&#60; Capítulo Anterior] | <<v38-6-0,Topo>> | xref:038-zacarias/038-zacarias-007.adoc#v38-7-0[Próximo Capítulo &#62;]