include::./index.adoc[]

[[v27-9-0]]
=== Daniel, 9
// naa ?, NAA - Nova Almeida Atualizada

[[v27-9-1]]

^<<v27-9-1,1>>^ No primeiro ano do reinado de Dario, filho de Assuero, da linhagem dos medos, que foi constituído rei sobre os caldeus,

[[v27-9-2]]

^<<v27-9-2,2>>^ no primeiro ano do seu reinado, eu, Daniel, entendi, pelos livros, que, de acordo com o que o Senhor  havia falado ao profeta Jeremias, a desolação de Jerusalém iria durar setenta anos.

[[v27-9-3]]

^<<v27-9-3,3>>^ Voltei o rosto ao Senhor Deus, para o buscar com oração e súplicas, com jejum, vestido de pano de saco e sentado na cinza.

[[v27-9-4]]

^<<v27-9-4,4>>^ Orei ao Senhor , meu Deus, e fiz a seguinte confissão: — Ah! Senhor! Deus grande e temível, que guardas a aliança e a misericórdia para com os que te amam e guardam os teus mandamentos,

[[v27-9-5]]

^<<v27-9-5,5>>^ nós temos pecado e cometido iniquidades. Procedemos mal e fomos rebeldes, afastando-nos dos teus mandamentos e dos teus juízos.

[[v27-9-6]]

^<<v27-9-6,6>>^ Não demos ouvidos aos teus servos, os profetas, que em teu nome falaram aos nossos reis, aos nossos príncipes, aos nossos pais e a todo o povo da terra.

[[v27-9-7]]

^<<v27-9-7,7>>^ A ti, ó Senhor, pertence a justiça, mas a nós cabe o corar de vergonha, como hoje se vê, a saber, aos homens de Judá, aos moradores de Jerusalém, a todo o Israel, tanto os de perto como os de longe, em todas as terras para onde os expulsaste, por causa das transgressões que cometeram contra ti.

[[v27-9-8]]

^<<v27-9-8,8>>^ Ó Senhor , a nós pertence o corar de vergonha, aos nossos reis, aos nossos príncipes e aos nossos pais, porque temos pecado contra ti.

[[v27-9-9]]

^<<v27-9-9,9>>^ Ao Senhor, nosso Deus, pertence a misericórdia e o perdão, pois nos rebelamos contra ele

[[v27-9-10]]

^<<v27-9-10,10>>^ e não obedecemos à voz do Senhor , nosso Deus, para andarmos nas suas leis, que nos deu por meio dos seus servos, os profetas.

[[v27-9-11]]

^<<v27-9-11,11>>^ Sim, todo o Israel transgrediu a tua lei e se desviou, deixando de ouvir a tua voz. Por isso, as maldições que estão escritas na Lei de Moisés, servo de Deus, e que foram confirmadas com juramento, se derramaram sobre nós, porque pecamos contra ti.

[[v27-9-12]]

^<<v27-9-12,12>>^ Ele confirmou a sua palavra, que falou contra nós e contra os nossos juízes que nos julgavam, e fez vir sobre nós um grande mal. Nunca antes, debaixo do céu, havia acontecido algo como o que aconteceu com Jerusalém!

[[v27-9-13]]

^<<v27-9-13,13>>^ Como está escrito na Lei de Moisés, todo este mal nos sobreveio. Mas mesmo assim não temos implorado o favor do Senhor , nosso Deus, para nos convertermos das nossas iniquidades e nos aplicarmos à tua verdade.

[[v27-9-14]]

^<<v27-9-14,14>>^ O Senhor  tinha preparado esse mal e o fez cair sobre nós, pois o Senhor , nosso Deus, é justo em tudo o que faz, e nós não obedecemos à sua voz.

[[v27-9-15]]

^<<v27-9-15,15>>^ — Ó Senhor, nosso Deus, que tiraste o teu povo da terra do Egito com mão poderosa e adquiriste a fama que tens até o dia de hoje, nós temos pecado e cometido iniquidade.

[[v27-9-16]]

^<<v27-9-16,16>>^ Ó Senhor, segundo todas as tuas justiças, afasta a tua ira e o teu furor da tua cidade de Jerusalém, do teu santo monte, porque, por causa dos nossos pecados e por causa das iniquidades de nossos pais, Jerusalém e o teu povo se tornaram objeto de deboche para todos os que estão ao redor de nós.

[[v27-9-17]]

^<<v27-9-17,17>>^ E agora, ó nosso Deus, ouve a oração e as súplicas do teu servo. Por amor do Senhor, faze resplandecer o teu rosto sobre o teu santuário, que está abandonado.

[[v27-9-18]]

^<<v27-9-18,18>>^ Inclina, ó Deus meu, os ouvidos e ouve! Abre os olhos e olha para a nossa desolação e para a cidade que é chamada pelo teu nome! Lançamos as nossas súplicas diante de ti não porque confiamos em nossas justiças, mas porque confiamos em tuas muitas misericórdias.

[[v27-9-19]]

^<<v27-9-19,19>>^ Ó Senhor, ouve! Ó Senhor, perdoa! Ó Senhor, atende-nos e age! Não te demores, por amor de ti mesmo, ó meu Deus, porque a tua cidade e o teu povo são chamados pelo teu nome.

[[v27-9-20]]

^<<v27-9-20,20>>^ Enquanto eu ainda falava, orava, confessava o meu pecado e o pecado do meu povo de Israel e lançava a minha súplica diante do Senhor , meu Deus, pelo monte santo do meu Deus,

[[v27-9-21]]

^<<v27-9-21,21>>^ sim, enquanto eu assim orava, Gabriel, o homem que eu tinha visto na minha visão anterior, veio rapidamente, voando, e tocou em mim; era hora do sacrifício da tarde.

[[v27-9-22]]

^<<v27-9-22,22>>^ Ele queria instruir-me, falou comigo e disse: — Daniel, agora eu vim para dar a você inteligência e discernimento.

[[v27-9-23]]

^<<v27-9-23,23>>^ Quando você começou a fazer as suas súplicas, foi dada uma ordem, e eu vim para explicar tudo a você, porque Deus o ama muito. Portanto, preste atenção à mensagem e entenda a visão.

[[v27-9-24]]

^<<v27-9-24,24>>^ — Setenta semanas estão determinadas para o seu povo e para a sua santa cidade, para acabar com a transgressão, para dar fim aos pecados, para expiar a iniquidade, para trazer a justiça eterna, para selar a visão e a profecia e para ungir o Santo dos Santos.

[[v27-9-25]]

^<<v27-9-25,25>>^ Saiba e entenda isto: desde que foi dada a ordem para restaurar e para edificar Jerusalém até a vinda do Ungido, o Príncipe, haverá sete semanas e sessenta e duas semanas. As ruas e as muralhas serão reconstruídas, mas será um tempo de muita angústia.

[[v27-9-26]]

^<<v27-9-26,26>>^ Depois das sessenta e duas semanas, o Ungido será morto e não terá nada. O povo de um príncipe que há de vir destruirá a cidade e o santuário. O seu fim virá como uma inundação. Até o fim haverá guerra, e desolações foram determinadas.

[[v27-9-27]]

^<<v27-9-27,27>>^ Ele fará firme aliança com muitos, por uma semana. Na metade da semana, fará cessar o sacrifício e a oferta de cereais. Sobre a asa das abominações virá aquele que causa desolação, até que a destruição, que está determinada, seja derramada sobre ele.

'''

xref:027-daniel/027-daniel-008.adoc#v27-8-0[&#60; Capítulo Anterior] | <<v27-9-0,Topo>> | xref:027-daniel/027-daniel-010.adoc#v27-10-0[Próximo Capítulo &#62;]