include::./index.adoc[]

[[v27-10-0]]
=== Daniel, 10
// naa ?, NAA - Nova Almeida Atualizada

[[v27-10-1]]

^<<v27-10-1,1>>^ No terceiro ano de Ciro, rei da Pérsia, uma palavra foi revelada a Daniel, cujo nome é Beltessazar. A palavra era verdadeira e envolvia grande conflito. Ele entendeu a palavra e teve entendimento da visão.

[[v27-10-2]]

^<<v27-10-2,2>>^ Naqueles dias, eu, Daniel, fiquei de luto por três semanas.

[[v27-10-3]]

^<<v27-10-3,3>>^ Não comi nada que fosse saboroso, não provei carne nem vinho, e não me ungi com óleo algum, até que passaram as três semanas.

[[v27-10-4]]

^<<v27-10-4,4>>^ No dia vinte e quatro do primeiro mês, estando eu na margem do grande rio Tigre,

[[v27-10-5]]

^<<v27-10-5,5>>^ levantei os olhos e vi um homem vestido de linho, com um cinto de ouro puro de Ufaz na cintura.

[[v27-10-6]]

^<<v27-10-6,6>>^ O seu corpo era como o berilo, o seu rosto parecia um relâmpago, os seus olhos eram como tochas de fogo, os seus braços e os seus pés brilhavam como bronze polido, e a voz das suas palavras era como o barulho de uma multidão.

[[v27-10-7]]

^<<v27-10-7,7>>^ Só eu, Daniel, tive aquela visão. Os homens que estavam comigo nada viram, mas ficaram com muito medo, fugiram e se esconderam.

[[v27-10-8]]

^<<v27-10-8,8>>^ Assim, fiquei sozinho e contemplei esta grande visão, e não restou força em mim. O meu rosto mudou de cor e se desfigurou, e perdi as forças.

[[v27-10-9]]

^<<v27-10-9,9>>^ Contudo, ouvi a voz das suas palavras; e, ouvindo essa voz, caí sem sentidos, com o rosto em terra.

[[v27-10-10]]

^<<v27-10-10,10>>^ Eis que a mão de alguém tocou em mim, e me ajudou a ficar de joelhos, apoiado nas palmas das mãos.

[[v27-10-11]]

^<<v27-10-11,11>>^ Ele me disse: — Daniel, homem muito amado, esteja atento às palavras que vou lhe dizer. Fique em pé, porque fui enviado para falar com você. Enquanto ele falava comigo, eu me pus em pé, tremendo.

[[v27-10-12]]

^<<v27-10-12,12>>^ Então ele me disse: — Não tenha medo, Daniel, porque as suas palavras foram ouvidas, desde o primeiro dia em que você dispôs o coração a compreender e a se humilhar na presença do seu Deus. Foi por causa dessas suas palavras que eu vim.

[[v27-10-13]]

^<<v27-10-13,13>>^ Mas o príncipe do reino da Pérsia me resistiu durante vinte e um dias. Porém Miguel, um dos príncipes mais importantes, veio me ajudar, e eu fiquei ali com os reis da Pérsia.

[[v27-10-14]]

^<<v27-10-14,14>>^ Agora, vim para fazer com que você entenda o que vai acontecer com o seu povo nos últimos dias. Porque a visão se refere a dias ainda distantes.

[[v27-10-15]]

^<<v27-10-15,15>>^ Enquanto ele me dizia essas palavras, dirigi o olhar para o chão e fiquei mudo.

[[v27-10-16]]

^<<v27-10-16,16>>^ Então um ser semelhante aos filhos dos homens me tocou os lábios, e passei a falar. Eu disse àquele que estava diante de mim: — Meu senhor, essa visão me causou muita dor, e eu fiquei sem força alguma.

[[v27-10-17]]

^<<v27-10-17,17>>^ Como pode este seu servo falar com o meu senhor? Porque, quanto a mim, não me resta mais nenhuma força, e quase não posso respirar.

[[v27-10-18]]

^<<v27-10-18,18>>^ Então aquele ser semelhante a um homem tocou em mim outra vez e me fortaleceu.

[[v27-10-19]]

^<<v27-10-19,19>>^ E disse: — Não tenha medo, homem muito amado! Que a paz esteja com você! Anime-se! Sim, anime-se! Enquanto ele falava comigo, fiquei fortalecido e disse: — Fale agora, meu senhor, pois as suas palavras me fortaleceram.

[[v27-10-20]]

^<<v27-10-20,20>>^ E ele disse: — Você sabe por que eu vim? Agora voltarei a lutar contra o príncipe da Pérsia. Quando eu sair, eis que virá o príncipe da Grécia.

[[v27-10-21]]

^<<v27-10-21,21>>^ Mas eu direi a você o que está expresso no Livro da Verdade. E na minha luta contra eles não há ninguém que esteja ao meu lado, a não ser Miguel, o príncipe de vocês.

'''

xref:027-daniel/027-daniel-009.adoc#v27-9-0[&#60; Capítulo Anterior] | <<v27-10-0,Topo>> | xref:027-daniel/027-daniel-011.adoc#v27-11-0[Próximo Capítulo &#62;]