include::./index.adoc[]

[[v27-12-0]]
=== Daniel, 12
// naa ?, NAA - Nova Almeida Atualizada

[[v27-12-1]]

^<<v27-12-1,1>>^ — Nesse tempo, se levantará Miguel, o grande príncipe, o defensor dos filhos do povo de Deus, e haverá tempo de angústia, como nunca houve, desde que existem nações até aquele tempo. Mas, naquele tempo, o povo de Deus será salvo, todo aquele que for achado inscrito no livro.

[[v27-12-2]]

^<<v27-12-2,2>>^ Muitos dos que dormem no pó da terra ressuscitarão, uns para a vida eterna, outros para vergonha e horror eterno.

[[v27-12-3]]

^<<v27-12-3,3>>^ Os que forem sábios resplandecerão como o fulgor do firmamento, e os que conduzirem muitos à justiça brilharão como as estrelas, sempre e eternamente.

[[v27-12-4]]

^<<v27-12-4,4>>^ Quanto a você, Daniel, encerre as palavras e sele o livro, até o tempo do fim. Muitos correrão de um lado para outro, e o saber se multiplicará.

[[v27-12-5]]

^<<v27-12-5,5>>^ Então eu, Daniel, olhei, e eis que outros dois estavam em pé às margens do rio, um de cada lado.

[[v27-12-6]]

^<<v27-12-6,6>>^ Um deles perguntou ao homem vestido de linho, que estava sobre as águas do rio: — Quando se cumprirão estas maravilhas?

[[v27-12-7]]

^<<v27-12-7,7>>^ Então ouvi o homem vestido de linho, que estava sobre as águas do rio. Ele levantou a mão direita e a esquerda ao céu e jurou por aquele que vive eternamente, dizendo: — Passarão um tempo, tempos e metade de um tempo. E, quando tiverem acabado de destruir o poder do povo santo, estas coisas todas se cumprirão.

[[v27-12-8]]

^<<v27-12-8,8>>^ Eu ouvi, mas não entendi. Então perguntei: — Meu senhor, qual será o fim destas coisas?

[[v27-12-9]]

^<<v27-12-9,9>>^ Ele respondeu: — Siga o seu caminho, Daniel, porque estas palavras estão encerradas e seladas até o tempo do fim.

[[v27-12-10]]

^<<v27-12-10,10>>^ Muitos serão purificados, limpos e provados, mas os ímpios continuarão na sua impiedade, e nenhum deles entenderá; mas os sábios entenderão.

[[v27-12-11]]

^<<v27-12-11,11>>^ Depois do tempo em que o sacrifício diário for tirado e a abominação desoladora for estabelecida, haverá ainda mil duzentos e noventa dias.

[[v27-12-12]]

^<<v27-12-12,12>>^ Bem-aventurado o que espera e chega até mil trezentos e trinta e cinco dias.

[[v27-12-13]]

^<<v27-12-13,13>>^ — Quanto a você, siga o seu caminho até o fim. Você descansará e, ao fim dos dias, se levantará para receber a sua herança.

'''

xref:027-daniel/027-daniel-011.adoc#v27-11-0[&#60; Capítulo Anterior] | <<v27-12-0,Topo>> | xref:028-oseias/028-oseias-001.adoc#v28-1-0[Próximo Capítulo &#62;]