include::./index.adoc[]

[[v27-8-0]]
=== Daniel, 8
// naa ?, NAA - Nova Almeida Atualizada

[[v27-8-1]]

^<<v27-8-1,1>>^ No terceiro ano do reinado do rei Belsazar, eu, Daniel, tive uma visão. Isto aconteceu depois daquela visão que eu tive anteriormente.

[[v27-8-2]]

^<<v27-8-2,2>>^ Quando tive a visão, parecia que eu estava na cidadela de Susã, que fica na província de Elão. Nessa visão, eu estava junto ao rio Ulai.

[[v27-8-3]]

^<<v27-8-3,3>>^ Levantei os olhos e eis que, diante do rio, estava um carneiro, que tinha dois chifres. Os dois chifres eram compridos, mas um era mais comprido do que o outro; e o mais comprido apareceu por último.

[[v27-8-4]]

^<<v27-8-4,4>>^ Vi que o carneiro dava chifradas para o oeste, para o norte e para o sul, e nenhum animal podia resistir a ele, nem havia quem pudesse livrar-se do seu poder. Ele fazia o que bem queria e, assim, se engrandeceu cada vez mais.

[[v27-8-5]]

^<<v27-8-5,5>>^ Enquanto eu procurava entender isso, eis que um bode vinha do oeste percorrendo toda a terra, mas sem tocar no chão. Esse bode tinha um chifre bem visível entre os olhos.

[[v27-8-6]]

^<<v27-8-6,6>>^ Foi na direção do carneiro que tinha os dois chifres, que eu tinha visto diante do rio, e correu contra ele com todo o seu furioso poder.

[[v27-8-7]]

^<<v27-8-7,7>>^ Eu vi quando o bode chegou perto do carneiro e, enfurecido contra ele, o atacou e lhe quebrou os dois chifres. O carneiro não tinha força para resistir ao bode. O bode jogou o carneiro no chão e o pisou com os pés, e não houve quem pudesse livrar o carneiro do poder do bode.

[[v27-8-8]]

^<<v27-8-8,8>>^ O bode se engrandeceu cada vez mais. Porém, quando estava no auge do seu poder, o seu grande chifre foi quebrado, e em seu lugar saíram quatro chifres bem visíveis, que cresceram na direção dos quatro ventos do céu.

[[v27-8-9]]

^<<v27-8-9,9>>^ De um deles saiu um chifre pequeno, que se engrandeceu na direção do sul, do leste e da terra gloriosa.

[[v27-8-10]]

^<<v27-8-10,10>>^ Ele se engrandeceu tanto, que alcançou o exército dos céus. Lançou por terra alguns desse exército e das estrelas e os pisou com os pés.

[[v27-8-11]]

^<<v27-8-11,11>>^ Ele se engrandeceu tanto, que chegou a desafiar o príncipe desse exército. Tirou dele o sacrifício diário e destruiu o lugar do seu santuário.

[[v27-8-12]]

^<<v27-8-12,12>>^ O exército lhe foi entregue, com o sacrifício diário, por causa das transgressões. Lançou por terra a verdade, e tudo o que ele fez prosperou.

[[v27-8-13]]

^<<v27-8-13,13>>^ Depois, ouvi um santo que falava; e outro santo lhe perguntou: — Até quando vai durar a visão do sacrifício diário suprimido e da transgressão desoladora? Até quando o santuário e o exército ficarão entregues, para que sejam pisados aos pés?

[[v27-8-14]]

^<<v27-8-14,14>>^ Ele me disse: — Até duas mil e trezentas tardes e manhãs. Depois, o santuário será purificado.

[[v27-8-15]]

^<<v27-8-15,15>>^ Depois que tive a visão, eu, Daniel, procurei entendê-la. Foi quando se apresentou diante de mim um ser que tinha a aparência de homem.

[[v27-8-16]]

^<<v27-8-16,16>>^ E ouvi uma voz de homem que vinha das margens do rio Ulai e que gritou assim: — Gabriel, explique a visão a esse homem.

[[v27-8-17]]

^<<v27-8-17,17>>^ Ele veio para perto de onde eu estava. Quando chegou, fiquei com muito medo e caí com o rosto em terra. Mas ele me disse: — Filho do homem, você precisa entender que esta visão se refere ao tempo do fim.

[[v27-8-18]]

^<<v27-8-18,18>>^ Ele ainda falava comigo quando caí sem sentidos, com o rosto em terra. Ele, porém, me tocou, me pôs em pé

[[v27-8-19]]

^<<v27-8-19,19>>^ e disse: — Eis que vou lhe contar o que há de acontecer no último tempo da ira, porque esta visão se refere ao tempo determinado do fim.

[[v27-8-20]]

^<<v27-8-20,20>>^ Aquele carneiro com dois chifres, que você viu, são os reis da Média e da Pérsia.

[[v27-8-21]]

^<<v27-8-21,21>>^ O bode peludo é o rei da Grécia, e o chifre grande entre os olhos é o primeiro rei.

[[v27-8-22]]

^<<v27-8-22,22>>^ O fato de o chifre ter sido quebrado, levantando-se quatro chifres em lugar dele, significa que quatro reinos se levantarão deste povo, mas não com força igual à que ele tinha.

[[v27-8-23]]

^<<v27-8-23,23>>^ Quando se aproximar o fim desses reinos e as transgressões tiverem chegado ao máximo, surgirá um rei cruel e mestre em intrigas.

[[v27-8-24]]

^<<v27-8-24,24>>^ Grande será o seu poder, mas não por sua própria força. Causará destruições terríveis, e prosperará naquilo que fizer. Destruirá os poderosos e o povo santo.

[[v27-8-25]]

^<<v27-8-25,25>>^ Por sua astúcia, fará prosperar o engano. No seu coração ele se engrandecerá, e destruirá muitos que vivem despreocupadamente. Ele se levantará contra o Príncipe dos príncipes, mas será destruído sem intervenção humana.

[[v27-8-26]]

^<<v27-8-26,26>>^ — A visão das tardes e das manhãs, que lhe foi dada, é verdadeira. Mas guarde a visão em segredo, porque se refere a dias ainda bem distantes.

[[v27-8-27]]

^<<v27-8-27,27>>^ Eu, Daniel, enfraqueci e fiquei doente durante vários dias. Depois, me levantei e tratei dos negócios do rei. Fiquei espantado com a visão, e não havia quem a entendesse.

'''

xref:027-daniel/027-daniel-007.adoc#v27-7-0[&#60; Capítulo Anterior] | <<v27-8-0,Topo>> | xref:027-daniel/027-daniel-009.adoc#v27-9-0[Próximo Capítulo &#62;]