include::./index.adoc[]

[[v27-5-0]]
=== Daniel, 5
// naa ?, NAA - Nova Almeida Atualizada

[[v27-5-1]]

^<<v27-5-1,1>>^ O rei Belsazar deu um grande banquete a mil homens importantes do seu reino e bebeu vinho na presença deles.

[[v27-5-2]]

^<<v27-5-2,2>>^ Enquanto Belsazar bebia e apreciava o vinho, mandou trazer os utensílios de ouro e de prata que Nabucodonosor, o seu pai, havia tirado do templo de Jerusalém, para que ele, os homens importantes do reino e as mulheres e concubinas do rei os usassem para beber vinho.

[[v27-5-3]]

^<<v27-5-3,3>>^ Então trouxeram os utensílios de ouro, que haviam sido tirados do templo da Casa de Deus em Jerusalém, e beberam neles o rei, os homens importantes do reino e as mulheres e concubinas do rei.

[[v27-5-4]]

^<<v27-5-4,4>>^ Beberam o vinho e deram louvores aos deuses de ouro, de prata, de bronze, de ferro, de madeira e de pedra.

[[v27-5-5]]

^<<v27-5-5,5>>^ No mesmo instante, apareceram uns dedos de mão humana, que começaram a escrever na parede caiada do palácio real, no lugar iluminado pelo candelabro; e o rei via os dedos que estavam escrevendo.

[[v27-5-6]]

^<<v27-5-6,6>>^ Então o semblante do rei empalideceu, e os seus pensamentos o deixaram perturbado; as suas pernas bambearam, e os seus joelhos batiam um no outro.

[[v27-5-7]]

^<<v27-5-7,7>>^ O rei ordenou, em voz alta, que fossem chamados os encantadores, os caldeus e os feiticeiros. O rei disse aos sábios da Babilônia: — Aquele que ler o que está escrito na parede e me declarar a sua interpretação será vestido de púrpura, receberá uma corrente de ouro para pôr no pescoço e será o terceiro homem mais importante do meu reino.

[[v27-5-8]]

^<<v27-5-8,8>>^ Então entraram todos os sábios do rei, mas não puderam ler o que estava escrito na parede, nem revelar ao rei a sua interpretação.

[[v27-5-9]]

^<<v27-5-9,9>>^ Com isto, o rei Belsazar ficou muito perturbado e o seu semblante se tornou cada vez mais pálido. Os homens importantes do reino estavam perplexos.

[[v27-5-10]]

^<<v27-5-10,10>>^ A rainha-mãe, que tinha ouvido os gritos do rei e dos homens importantes do reino, entrou na sala do banquete e disse: — Que o rei viva eternamente! Não deixe que os seus pensamentos o perturbem, nem fique assim tão pálido.

[[v27-5-11]]

^<<v27-5-11,11>>^ Há aqui no seu reino um homem que tem o espírito dos santos deuses. Nos dias de seu pai, se achou nele luz, inteligência e sabedoria como a sabedoria dos deuses. O seu pai, o rei Nabucodonosor, sim, o seu pai, ó rei, o constituiu chefe dos magos, dos encantadores, dos caldeus e dos feiticeiros,

[[v27-5-12]]

^<<v27-5-12,12>>^ porque nesse Daniel, a quem o rei tinha dado o nome de Beltessazar, se acharam espírito excelente, conhecimento e inteligência, interpretação de sonhos, declaração de enigmas e solução de casos difíceis. Portanto, chame Daniel, e ele dará a interpretação.

[[v27-5-13]]

^<<v27-5-13,13>>^ Então Daniel foi levado à presença do rei. O rei falou com Daniel e lhe perguntou: — Você é aquele Daniel, dos exilados de Judá, que o rei, meu pai, trouxe de Judá?

[[v27-5-14]]

^<<v27-5-14,14>>^ Tenho ouvido dizer a seu respeito que o espírito dos deuses está em você, e que em você se acham luz, inteligência e excelente sabedoria.

[[v27-5-15]]

^<<v27-5-15,15>>^ Acabam de ser trazidos à minha presença os sábios e os encantadores, para lerem o que está escrito na parede e me darem a sua interpretação. Mas eles não puderam dar a interpretação dessas palavras.

[[v27-5-16]]

^<<v27-5-16,16>>^ Eu, porém, tenho ouvido dizer que você é capaz de dar interpretações e solucionar casos difíceis. Portanto, se você puder ler o que está escrito e me revelar a sua interpretação, você será vestido de púrpura, receberá uma corrente de ouro para pôr no pescoço e será o terceiro homem mais importante do meu reino.

[[v27-5-17]]

^<<v27-5-17,17>>^ Então Daniel respondeu e disse na presença do rei: — O senhor pode ficar com os seus presentes e dar as suas recompensas a outra pessoa. No entanto, vou ler para o rei o que está escrito na parede e lhe darei a interpretação.

[[v27-5-18]]

^<<v27-5-18,18>>^ Ó rei, o Deus Altíssimo deu o reino a Nabucodonosor, seu pai, bem como grandeza, glória e majestade.

[[v27-5-19]]

^<<v27-5-19,19>>^ Por causa da grandeza que lhe deu, pessoas de todos os povos, nações e línguas tremiam e temiam diante dele. Matava a quem queria e a quem queria deixava com vida; exaltava uns e humilhava outros.

[[v27-5-20]]

^<<v27-5-20,20>>^ Mas, quando o coração dele se elevou, e o seu espírito se tornou orgulhoso e arrogante, foi derrubado do seu trono real e perdeu toda a sua glória.

[[v27-5-21]]

^<<v27-5-21,21>>^ Foi expulso do meio dos filhos dos homens, o seu coração foi feito semelhante ao dos animais, e passou a morar com os jumentos selvagens. Comia capim como os bois e o seu corpo foi molhado pelo orvalho do céu, até que reconheceu que Deus, o Altíssimo, tem domínio sobre os reinos do mundo e os dá a quem ele quer.

[[v27-5-22]]

^<<v27-5-22,22>>^ — E o senhor, rei Belsazar, que é filho de Nabucodonosor, não humilhou o seu coração, mesmo sabendo de tudo isso.

[[v27-5-23]]

^<<v27-5-23,23>>^ Pelo contrário, se levantou contra o Senhor do céu, mandando trazer os utensílios do templo dele, para que o senhor, ó rei, as suas mulheres e concubinas, juntamente com os homens importantes do reino, bebessem vinho neles. Além disso, o senhor deu louvores aos deuses de prata, de ouro, de bronze, de ferro, de madeira e de pedra, que não veem, não ouvem e não sabem nada. Mas o senhor não deu glória a Deus, em cuja mão estão a sua vida e todos os seus caminhos.

[[v27-5-24]]

^<<v27-5-24,24>>^ É por isso que ele enviou aquela mão que escreveu na parede.

[[v27-5-25]]

^<<v27-5-25,25>>^ E o que está escrito é isto: Mene , Mene , Tequel  e Parsim .

[[v27-5-26]]

^<<v27-5-26,26>>^ — Esta é a interpretação daquilo: Mene : Deus contou os dias do seu reinado, ó rei, e pôs um fim nele.

[[v27-5-27]]

^<<v27-5-27,27>>^ Tequel : Você foi pesado na balança e achado em falta.

[[v27-5-28]]

^<<v27-5-28,28>>^ Peres : O seu reino foi dividido e entregue aos medos e aos persas.

[[v27-5-29]]

^<<v27-5-29,29>>^ Então Belsazar mandou que vestissem Daniel de púrpura, que lhe pusessem uma corrente de ouro no pescoço, e que proclamassem que passaria a ser o terceiro no governo do seu reino.

[[v27-5-30]]

^<<v27-5-30,30>>^ Naquela mesma noite, Belsazar, rei dos caldeus, foi morto.

[[v27-5-31]]

^<<v27-5-31,31>>^ E Dario, o medo, se apoderou do reino, quando tinha mais ou menos sessenta e dois anos de idade.

'''

xref:027-daniel/027-daniel-004.adoc#v27-4-0[&#60; Capítulo Anterior] | <<v27-5-0,Topo>> | xref:027-daniel/027-daniel-006.adoc#v27-6-0[Próximo Capítulo &#62;]