include::./index.adoc[]

[[v27-11-0]]
=== Daniel, 11
// naa ?, NAA - Nova Almeida Atualizada

[[v27-11-1]]

^<<v27-11-1,1>>^ Mas eu, no primeiro ano de Dario, o medo, me levantei para o fortalecer e animar.

[[v27-11-2]]

^<<v27-11-2,2>>^ — Agora, eu vou lhe dizer a verdade: eis que ainda três reis se levantarão na Pérsia, e o quarto será muito mais rico do que todos eles. Fortalecido por suas riquezas, instigará todos contra o reino da Grécia.

[[v27-11-3]]

^<<v27-11-3,3>>^ Depois, se levantará um rei poderoso, que reinará com grande domínio e fará o que quiser.

[[v27-11-4]]

^<<v27-11-4,4>>^ Mas, no auge do seu poder, o seu reino será quebrado e repartido para os quatro ventos do céu, mas não para a sua posteridade, nem com o mesmo poder com que ele reinou, porque o seu reino será arrancado e passará a outros fora de seus descendentes.

[[v27-11-5]]

^<<v27-11-5,5>>^ — O rei do Sul será forte, mas um dos seus príncipes será mais forte do que ele, e reinará, e será grande o seu domínio.

[[v27-11-6]]

^<<v27-11-6,6>>^ Mas, depois de alguns anos, eles se aliarão um com o outro. A filha do rei do Sul casará com o rei do Norte, para estabelecer a concórdia. Ela, porém, não conservará o seu poder, e ele não permanecerá, nem manterá o seu poder. Porque ela será entregue, juntamente com os que a trouxeram, o seu pai e aquele que a tomou por sua naqueles tempos.

[[v27-11-7]]

^<<v27-11-7,7>>^ Mas em lugar dele se levantará um renovo da linhagem dela, que avançará contra o exército do rei do Norte, entrará na sua fortaleza, lutará contra eles e prevalecerá.

[[v27-11-8]]

^<<v27-11-8,8>>^ Também levará como despojo para o Egito os deuses deles, as suas imagens fundidas e os seus objetos preciosos de prata e de ouro. Por alguns anos, ele deixará o rei do Norte em paz.

[[v27-11-9]]

^<<v27-11-9,9>>^ Depois, este avançará contra o reino do rei do Sul, mas voltará para a sua terra.

[[v27-11-10]]

^<<v27-11-10,10>>^ — Os seus filhos farão guerra e reunirão um grande exército. Um deles virá apressadamente, arrasará tudo e passará adiante; e, voltando, levará a guerra até a fortaleza do rei do Sul.

[[v27-11-11]]

^<<v27-11-11,11>>^ Então o rei do Sul ficará furioso e sairá para atacar o rei do Norte. Este reunirá um grande exército, que será entregue nas mãos do rei do Sul.

[[v27-11-12]]

^<<v27-11-12,12>>^ O grande exército será levado, e o coração do rei do Sul se exaltará; ele derrubará muitos milhares, porém não prevalecerá.

[[v27-11-13]]

^<<v27-11-13,13>>^ Porque o rei do Norte voltará, e reunirá um exército ainda maior do que o primeiro, e, depois de alguns anos, virá com um grande exército e abundantes provisões.

[[v27-11-14]]

^<<v27-11-14,14>>^ — Naqueles tempos, muitos se levantarão contra o rei do Sul. Também os violentos do seu povo, ó Daniel, se levantarão para cumprirem a visão, mas serão derrotados.

[[v27-11-15]]

^<<v27-11-15,15>>^ O rei do Norte virá, levantará rampas de ataque e tomará cidades fortificadas. As forças do Sul não poderão resistir. Nem mesmo os melhores soldados terão forças para resistir.

[[v27-11-16]]

^<<v27-11-16,16>>^ O invasor fará o que bem quiser, e não haverá quem lhe possa resistir. Ocupará a terra gloriosa, e tudo estará em suas mãos.

[[v27-11-17]]

^<<v27-11-17,17>>^ Resolverá vir com a força de todo o seu reino e entrará em acordo com o rei do Sul. Ele lhe dará uma filha em casamento, para destruir o reino do Sul, mas isto não vingará, nem será para a sua vantagem.

[[v27-11-18]]

^<<v27-11-18,18>>^ Depois, se voltará para as terras do mar e tomará muitas delas. Mas um príncipe porá fim à arrogância dele e fará com que pague por isso.

[[v27-11-19]]

^<<v27-11-19,19>>^ Então voltará para as fortalezas da sua própria terra, mas tropeçará e cairá, para nunca mais ser achado.

[[v27-11-20]]

^<<v27-11-20,20>>^ — Depois, se levantará em lugar dele um que fará passar um arrecadador de impostos pela glória do reino; mas, em poucos dias, será destruído, e isso sem ira nem batalha.

[[v27-11-21]]

^<<v27-11-21,21>>^ Depois, se levantará em seu lugar um homem desprezível, ao qual não tinham dado a dignidade real; mas ele virá de surpresa e tomará o reino, com intrigas.

[[v27-11-22]]

^<<v27-11-22,22>>^ Exércitos serão arrasados diante dele; serão esmagados, inclusive o príncipe da aliança.

[[v27-11-23]]

^<<v27-11-23,23>>^ Apesar da aliança com ele, usará de engano; subirá e se tornará forte com pouca gente.

[[v27-11-24]]

^<<v27-11-24,24>>^ Virá também de surpresa aos lugares mais férteis da província e fará o que nunca fizeram os seus pais, nem os pais de seus pais: repartirá entre eles a presa, os despojos e os bens; e fará os seus planos contra as fortalezas, mas só por certo tempo.

[[v27-11-25]]

^<<v27-11-25,25>>^ — Despertará a sua força e a sua coragem contra o rei do Sul, à frente de grande exército. O rei do Sul sairá à batalha com um grande e poderoso exército, mas não prevalecerá, porque farão planos contra ele.

[[v27-11-26]]

^<<v27-11-26,26>>^ Os que comerem as finas iguarias dele o destruirão, o exército dele será arrasado, e muitos serão mortos.

[[v27-11-27]]

^<<v27-11-27,27>>^ Também estes dois reis se empenharão em fazer o mal e, sentados à mesma mesa, falarão mentiras. Porém isso não prosperará, porque o fim virá no tempo determinado.

[[v27-11-28]]

^<<v27-11-28,28>>^ Então o rei do Norte voltará para a sua terra com grande riqueza, e o seu coração será contra a santa aliança; fará o que quiser e depois voltará para a sua terra.

[[v27-11-29]]

^<<v27-11-29,29>>^ — No tempo determinado, voltará a atacar o Sul, mas desta vez não será como foi na primeira vez,

[[v27-11-30]]

^<<v27-11-30,30>>^ porque virão contra ele navios de Quitim. Contrariado, ele voltará e se indignará contra a santa aliança, e fará o que quiser. E, tendo voltado, dará atenção aos que abandonaram a santa aliança.

[[v27-11-31]]

^<<v27-11-31,31>>^ Forças enviadas por ele profanarão o santuário e a fortaleza, acabarão com o sacrifício diário, estabelecendo a abominação desoladora.

[[v27-11-32]]

^<<v27-11-32,32>>^ Com lisonjas, perverterá aqueles que violaram a aliança, mas o povo que conhece o seu Deus se tornará forte e ativo.

[[v27-11-33]]

^<<v27-11-33,33>>^ Os sábios entre o povo ensinarão a muitos; todavia, cairão pela espada e pelo fogo, pelo cativeiro e pelo roubo, por algum tempo.

[[v27-11-34]]

^<<v27-11-34,34>>^ Ao caírem, receberão uma pequena ajuda; mas muitos se ajuntarão a eles com lisonjas.

[[v27-11-35]]

^<<v27-11-35,35>>^ Alguns dos sábios cairão para serem provados, purificados e limpos, até o tempo do fim, porque se dará ainda no tempo determinado.

[[v27-11-36]]

^<<v27-11-36,36>>^ — Este rei fará o que quiser, se levantará, e se engrandecerá sobre tudo o que se chama deus. Falará coisas incríveis contra o Deus dos deuses e será bem-sucedido, até que se cumpra a indignação; porque aquilo que está determinado será feito.

[[v27-11-37]]

^<<v27-11-37,37>>^ Não terá respeito aos deuses dos seus pais, nem ao deus que as mulheres preferem, nem a qualquer deus, porque se engrandecerá acima de tudo.

[[v27-11-38]]

^<<v27-11-38,38>>^ Mas, em lugar dos deuses, honrará o deus das fortalezas; a um deus que os seus pais não conheceram, honrará com ouro, com prata, com pedras preciosas e objetos de valor.

[[v27-11-39]]

^<<v27-11-39,39>>^ Com o auxílio de um deus estranho, atacará as mais poderosas fortalezas, e aos que o reconhecerem, multiplicará a honra, e os fará reinar sobre muitos, e lhes repartirá a terra por um preço.

[[v27-11-40]]

^<<v27-11-40,40>>^ — No tempo do fim, o rei do Sul lutará contra ele, e o rei do Norte arremeterá contra ele com carros de guerra, cavaleiros e com muitos navios, e entrará nas suas terras, e as inundará, e passará.

[[v27-11-41]]

^<<v27-11-41,41>>^ Entrará também na terra gloriosa, e muitos sucumbirão, mas Edom, Moabe e as primícias dos filhos de Amom escaparão do seu poder.

[[v27-11-42]]

^<<v27-11-42,42>>^ Estenderá a sua mão contra as terras, e nem mesmo a terra do Egito escapará.

[[v27-11-43]]

^<<v27-11-43,43>>^ Tomará posse dos tesouros de ouro e de prata e de todas as coisas preciosas do Egito; os líbios e os etíopes o seguirão.

[[v27-11-44]]

^<<v27-11-44,44>>^ Mas será perturbado por rumores vindos do Oriente e do Norte e sairá com grande furor, para destruir e exterminar muitos.

[[v27-11-45]]

^<<v27-11-45,45>>^ Armará as suas tendas palacianas entre o mar e o glorioso monte santo. Mas chegará ao seu fim, e não haverá quem o socorra.

'''

xref:027-daniel/027-daniel-010.adoc#v27-10-0[&#60; Capítulo Anterior] | <<v27-11-0,Topo>> | xref:027-daniel/027-daniel-012.adoc#v27-12-0[Próximo Capítulo &#62;]