include::./index.adoc[]

[[v27-4-0]]
=== Daniel, 4
// naa ?, NAA - Nova Almeida Atualizada

[[v27-4-1]]

^<<v27-4-1,1>>^ O rei Nabucodonosor às pessoas de todos os povos, nações e línguas, que habitam em toda a terra: "Que a paz lhes seja multiplicada!

[[v27-4-2]]

^<<v27-4-2,2>>^ Pareceu-me bem tornar conhecidos os sinais e as maravilhas que Deus, o Altíssimo, tem feito para comigo."

[[v27-4-3]]

^<<v27-4-3,3>>^ "Como são grandes os seus sinais, e como são poderosas as suas maravilhas! O seu reino é um reino eterno, e o seu domínio se estende de geração em geração."

[[v27-4-4]]

^<<v27-4-4,4>>^ — Eu, Nabucodonosor, estava tranquilo em minha casa e feliz no meu palácio.

[[v27-4-5]]

^<<v27-4-5,5>>^ Tive um sonho que me espantou. Quando eu estava na minha cama, os pensamentos e as visões que passaram diante dos meus olhos me perturbaram.

[[v27-4-6]]

^<<v27-4-6,6>>^ Por isso, expedi um decreto, ordenando que fossem trazidos à minha presença todos os sábios da Babilônia, para que me revelassem a interpretação do sonho.

[[v27-4-7]]

^<<v27-4-7,7>>^ Então vieram os magos, os encantadores, os caldeus e os feiticeiros. Eu lhes contei o sonho, mas eles não puderam me revelar a sua interpretação.

[[v27-4-8]]

^<<v27-4-8,8>>^ Por fim, apresentou-se Daniel, que é chamado de Beltessazar, em honra ao nome do meu deus. Ele tem o espírito dos santos deuses, e eu lhe contei o sonho, dizendo:

[[v27-4-9]]

^<<v27-4-9,9>>^ "Beltessazar, chefe dos magos, eu sei que você tem o espírito dos santos deuses e que não há mistério que você não possa explicar. Vou lhe contar o sonho que eu tive, para que você me diga o que ele significa.

[[v27-4-10]]

^<<v27-4-10,10>>^ Estas foram as visões que passaram diante dos meus olhos quando eu estava deitado na minha cama: eu estava olhando e vi uma árvore no meio da terra, cuja altura era enorme.

[[v27-4-11]]

^<<v27-4-11,11>>^ A árvore cresceu e se tornou forte, de maneira que a sua altura chegou até o céu; ela podia ser vista desde os confins da terra.

[[v27-4-12]]

^<<v27-4-12,12>>^ A sua folhagem era bela, o seu fruto era abundante, e nela havia sustento para todos. Debaixo dela os animais selvagens achavam sombra, e as aves do céu faziam morada nos seus ramos; e todos os seres vivos se alimentavam dela.

[[v27-4-13]]

^<<v27-4-13,13>>^ No meu sonho, quando eu estava na minha cama, vi um vigilante, um santo, que descia do céu,

[[v27-4-14]]

^<<v27-4-14,14>>^ gritando em alta voz: ‘Derrubem a árvore, cortem os seus ramos, arranquem as folhas e espalhem os seus frutos. Espantem os animais que estão debaixo dela e as aves que fazem morada nos seus ramos.

[[v27-4-15]]

^<<v27-4-15,15>>^ Mas o toco, com as raízes, deixem na terra, amarrado com correntes de ferro e de bronze, em meio à erva do campo. Que esse toco seja molhado pelo orvalho do céu, e que a parte que lhe cabe seja a erva da terra, junto com os animais.

[[v27-4-16]]

^<<v27-4-16,16>>^ Que o coração dele seja mudado, para que não seja mais coração humano, e lhe seja dado coração de animal; e passem sobre ele sete tempos.

[[v27-4-17]]

^<<v27-4-17,17>>^ Esta sentença é por decreto dos vigilantes, e esta ordem é por mandado dos santos, para que os que vivem saibam que o Altíssimo tem domínio sobre o reino dos homens. Ele dá esse reino a quem quer, e põe sobre ele até o mais humilde dos homens.’"

[[v27-4-18]]

^<<v27-4-18,18>>^ — Este foi o sonho que eu, rei Nabucodonosor, tive. Você, Beltessazar, diga a interpretação, porque todos os sábios do meu reino não puderam me revelar a interpretação. Mas eu sei que você pode, porque você tem o espírito dos santos deuses.

[[v27-4-19]]

^<<v27-4-19,19>>^ Então Daniel, cujo nome era Beltessazar, ficou perplexo por algum tempo, e os seus pensamentos o perturbavam. Então o rei lhe disse: — Beltessazar, não deixe que o sonho ou a sua interpretação o perturbem. Beltessazar respondeu: — Meu senhor, quem dera o sonho fosse a respeito daqueles que o odeiam, e a sua interpretação se aplicasse aos seus inimigos!

[[v27-4-20]]

^<<v27-4-20,20>>^ A árvore que o senhor viu, que cresceu e se tornou forte, cuja altura chegou até o céu, que foi vista por toda a terra,

[[v27-4-21]]

^<<v27-4-21,21>>^ cuja folhagem era bela, cujo fruto era abundante, na qual havia sustento para todos, debaixo da qual os animais selvagens achavam sombra, e em cujos ramos as aves do céu faziam morada,

[[v27-4-22]]

^<<v27-4-22,22>>^ aquela árvore é o senhor, ó rei, que cresceu e veio a ser forte. A sua grandeza, ó rei, cresceu e chega até o céu, e o seu domínio se estende até a extremidade da terra.

[[v27-4-23]]

^<<v27-4-23,23>>^ Quanto ao vigilante ou santo que o rei viu, que descia do céu e que dizia: "Cortem e destruam a árvore, mas deixem o toco com as raízes na terra, amarrado com correntes de ferro e de bronze, em meio à erva do campo; que esse toco seja molhado pelo orvalho do céu, e que a parte que lhe cabe seja com os animais selvagens, até que passem sobre ele sete tempos",

[[v27-4-24]]

^<<v27-4-24,24>>^ esta é a interpretação, ó rei, e este é o decreto do Altíssimo, que virá contra meu senhor, o rei:

[[v27-4-25]]

^<<v27-4-25,25>>^ o senhor será expulso do meio das pessoas, e a sua morada será com os animais selvagens; o senhor comerá capim como os bois, e será molhado pelo orvalho do céu; e passarão sete tempos, até que o senhor, ó rei, reconheça que o Altíssimo tem domínio sobre os reinos do mundo e os dá a quem ele quer.

[[v27-4-26]]

^<<v27-4-26,26>>^ Quanto ao que foi dito, que se deixasse o toco da árvore com as suas raízes, isto significa que o seu reino voltará a ser seu, depois que o senhor tiver reconhecido que o Céu domina.

[[v27-4-27]]

^<<v27-4-27,27>>^ Portanto, ó rei, aceite o meu conselho: abandone os seus pecados, praticando a justiça, e acabe com as suas iniquidades, usando de misericórdia para com os pobres; assim talvez a sua tranquilidade se prolongue.

[[v27-4-28]]

^<<v27-4-28,28>>^ Tudo isso, de fato, aconteceu com o rei Nabucodonosor.

[[v27-4-29]]

^<<v27-4-29,29>>^ Passados doze meses, quando estava passeando no terraço do palácio real da cidade da Babilônia,

[[v27-4-30]]

^<<v27-4-30,30>>^ o rei disse: — Não é esta a grande Babilônia que eu construí para a casa real, com o meu grandioso poder e para glória da minha majestade?

[[v27-4-31]]

^<<v27-4-31,31>>^ Enquanto o rei ainda falava, veio uma voz do céu, que disse: — A você, rei Nabucodonosor, se anuncia o seguinte: Este reino lhe foi tirado.

[[v27-4-32]]

^<<v27-4-32,32>>^ Você será expulso do meio das pessoas, e a sua morada será com os animais selvagens; você comerá capim como os bois, e passarão sete tempos, até que você reconheça que o Altíssimo tem domínio sobre os reinos do mundo e os dá a quem ele quer.

[[v27-4-33]]

^<<v27-4-33,33>>^ No mesmo instante, se cumpriu a palavra sobre Nabucodonosor. Ele foi expulso do meio das pessoas e começou a comer capim como os bois. O seu corpo foi molhado pelo orvalho do céu, até que lhe cresceram os cabelos como as penas da águia, e as suas unhas, como as garras das aves.

[[v27-4-34]]

^<<v27-4-34,34>>^ — Mas ao fim daqueles dias, eu, Nabucodonosor, levantei os olhos ao céu, e recuperei o entendimento. Então eu bendisse o Altíssimo, e louvei e glorifiquei aquele que vive para sempre: "O seu domínio é eterno, e o seu reino se estende de geração em geração.

[[v27-4-35]]

^<<v27-4-35,35>>^ Todos os moradores da terra são considerados como nada, e o Altíssimo faz o que quer com o exército do céu e com os moradores da terra. Não há quem possa deter a sua mão, nem questionar o que ele faz."

[[v27-4-36]]

^<<v27-4-36,36>>^ — Nesse tempo, recuperei o entendimento e, para a dignidade do meu reino, recuperei também a minha majestade e o meu resplendor. Os meus conselheiros e os homens importantes vieram me procurar, fui restabelecido no meu reino, e a minha grandeza se tornou ainda maior.

[[v27-4-37]]

^<<v27-4-37,37>>^ Agora eu, Nabucodonosor, louvo, engrandeço e glorifico o Rei do céu, porque todas as suas obras são verdadeiras, e os seus caminhos são justos. Ele tem poder para humilhar os orgulhosos.

'''

xref:027-daniel/027-daniel-003.adoc#v27-3-0[&#60; Capítulo Anterior] | <<v27-4-0,Topo>> | xref:027-daniel/027-daniel-005.adoc#v27-5-0[Próximo Capítulo &#62;]