include::./index.adoc[]

[[v27-3-0]]
=== Daniel, 3
// naa ?, NAA - Nova Almeida Atualizada

[[v27-3-1]]

^<<v27-3-1,1>>^ O rei Nabucodonosor fez uma imagem de ouro que tinha vinte e sete metros de altura e dois metros e setenta de largura, que ele levantou na planície de Dura, na província da Babilônia.

[[v27-3-2]]

^<<v27-3-2,2>>^ Então o rei Nabucodonosor mandou reunir os sátrapas, os prefeitos, os governadores, os juízes, os tesoureiros, os magistrados, os conselheiros e todos os oficiais das províncias, para que viessem à dedicação da imagem que o rei Nabucodonosor tinha levantado.

[[v27-3-3]]

^<<v27-3-3,3>>^ Então se reuniram os sátrapas, os prefeitos, os governadores, os juízes, os tesoureiros, os magistrados, os conselheiros e todos os oficiais das províncias, para a dedicação da imagem que o rei Nabucodonosor tinha levantado. E ficaram em pé diante da imagem que Nabucodonosor tinha levantado.

[[v27-3-4]]

^<<v27-3-4,4>>^ Nisto, o arauto proclamou em alta voz: — Ordena-se a vocês, pessoas de todos os povos, nações e línguas,

[[v27-3-5]]

^<<v27-3-5,5>>^ que, no momento em que ouvirem o som da trombeta, da flauta, da harpa, da cítara, da lira, da gaita de foles e de todo tipo de música, vocês se prostrem e adorem a imagem de ouro que o rei Nabucodonosor levantou.

[[v27-3-6]]

^<<v27-3-6,6>>^ Quem não se prostrar e não a adorar será, no mesmo instante, lançado na fornalha de fogo ardente.

[[v27-3-7]]

^<<v27-3-7,7>>^ Assim, quando ouviram o som da trombeta, da flauta, da harpa, da cítara, da lira e de todo tipo de música, pessoas de todos os povos, nações e línguas se prostraram e adoraram a imagem de ouro que o rei Nabucodonosor tinha levantado.

[[v27-3-8]]

^<<v27-3-8,8>>^ No mesmo instante, alguns homens caldeus se aproximaram e acusaram os judeus.

[[v27-3-9]]

^<<v27-3-9,9>>^ Disseram ao rei Nabucodonosor: — Que o rei viva eternamente!

[[v27-3-10]]

^<<v27-3-10,10>>^ O senhor, ó rei, baixou um decreto, ordenando que todo homem que ouvisse o som da trombeta, da flauta, da harpa, da cítara, da lira, da gaita de foles e de todo tipo de música deveria se prostrar e adorar a imagem de ouro,

[[v27-3-11]]

^<<v27-3-11,11>>^ e que todo aquele que não se prostrasse e não adorasse seria lançado na fornalha de fogo ardente.

[[v27-3-12]]

^<<v27-3-12,12>>^ Há uns homens judeus, que o senhor, ó rei, pôs como administradores da província da Babilônia: Sadraque, Mesaque e Abede-Nego. Esses homens fizeram pouco caso do senhor, ó rei; não prestam culto aos deuses do rei, nem adoram a imagem de ouro que o senhor levantou.

[[v27-3-13]]

^<<v27-3-13,13>>^ Então Nabucodonosor, irado e furioso, mandou chamar Sadraque, Mesaque e Abede-Nego, e eles foram levados à presença do rei.

[[v27-3-14]]

^<<v27-3-14,14>>^ Nabucodonosor lhes disse: — Sadraque, Mesaque e Abede-Nego, é verdade que vocês não prestam culto aos meus deuses, nem adoram a imagem de ouro que levantei?

[[v27-3-15]]

^<<v27-3-15,15>>^ Agora, pois, se vocês estão prontos, quando ouvirem o som da trombeta, da flauta, da cítara, da harpa, da lira, da gaita de foles, prostrem-se e adorem a imagem que eu fiz. Mas, se não a adorarem, serão, no mesmo instante, lançados na fornalha de fogo ardente. E quem é o deus que os poderá livrar das minhas mãos?

[[v27-3-16]]

^<<v27-3-16,16>>^ Sadraque, Mesaque e Abede-Nego responderam ao rei: — Ó Nabucodonosor, quanto a isto não precisamos nem responder.

[[v27-3-17]]

^<<v27-3-17,17>>^ Se o nosso Deus, a quem servimos, quiser livrar-nos, ele nos livrará da fornalha de fogo ardente e das suas mãos, ó rei.

[[v27-3-18]]

^<<v27-3-18,18>>^ E mesmo que ele não nos livre, fique sabendo, ó rei, que não prestaremos culto aos seus deuses, nem adoraremos a imagem de ouro que o senhor levantou.

[[v27-3-19]]

^<<v27-3-19,19>>^ Então Nabucodonosor se encheu de fúria e o aspecto do seu rosto se alterou em relação a Sadraque, Mesaque e Abede-Nego. Ordenou que se esquentasse a fornalha sete vezes mais do que de costume.

[[v27-3-20]]

^<<v27-3-20,20>>^ Ordenou aos soldados mais fortes do seu exército que amarrassem Sadraque, Mesaque e Abede-Nego e os jogassem na fornalha de fogo ardente.

[[v27-3-21]]

^<<v27-3-21,21>>^ Então estes homens foram amarrados com os seus mantos, túnicas, chapéus e as suas outras roupas e foram jogados na fornalha de fogo ardente.

[[v27-3-22]]

^<<v27-3-22,22>>^ Mas porque o rei exigia urgência e a fornalha estava superaquecida, as chamas do fogo mataram os homens que jogaram Sadraque, Mesaque e Abede-Nego dentro da fornalha.

[[v27-3-23]]

^<<v27-3-23,23>>^ E os três homens, Sadraque, Mesaque e Abede-Nego, caíram amarrados dentro da fornalha de fogo ardente.

[[v27-3-24]]

^<<v27-3-24,24>>^ Em seguida, o rei Nabucodonosor, muito espantado, se levantou depressa e perguntou aos seus conselheiros: — Não eram três os homens que amarramos e jogamos no fogo? Eles responderam: — É verdade, ó rei.

[[v27-3-25]]

^<<v27-3-25,25>>^ Mas o rei disse: — Eu, porém, estou vendo quatro homens soltos, andando no meio do fogo! Não sofreram nenhum dano! E o aspecto do quarto é semelhante a um filho dos deuses.

[[v27-3-26]]

^<<v27-3-26,26>>^ Então Nabucodonosor se aproximou da porta da fornalha de fogo ardente e gritou: — Sadraque, Mesaque e Abede-Nego, servos do Deus Altíssimo, venham para fora! Venham cá! Então Sadraque, Mesaque e Abede-Nego saíram do meio do fogo.

[[v27-3-27]]

^<<v27-3-27,27>>^ Os sátrapas, os prefeitos, os governadores e conselheiros do rei chegaram perto deles e viram que o fogo não teve poder algum sobre o corpo desses homens. Os cabelos da cabeça não foram chamuscados, os mantos não sofreram mudança, e eles não estavam com cheiro de fumaça.

[[v27-3-28]]

^<<v27-3-28,28>>^ Nabucodonosor disse: — Bendito seja o Deus de Sadraque, Mesaque e Abede-Nego, que enviou o seu anjo e livrou os seus servos, que confiaram nele, pois não quiseram cumprir a palavra do rei, preferindo entregar o seu corpo a servir e adorar um deus que não era o Deus deles.

[[v27-3-29]]

^<<v27-3-29,29>>^ Portanto, faço um decreto, ordenando que todo povo, nação e língua que disser blasfêmia contra o Deus de Sadraque, Mesaque e Abede-Nego seja despedaçado, e que as suas casas sejam reduzidas a ruínas. Porque não há outro deus que possa livrar como este.

[[v27-3-30]]

^<<v27-3-30,30>>^ Então o rei fez prosperar Sadraque, Mesaque e Abede-Nego na província da Babilônia.

'''

xref:027-daniel/027-daniel-002.adoc#v27-2-0[&#60; Capítulo Anterior] | <<v27-3-0,Topo>> | xref:027-daniel/027-daniel-004.adoc#v27-4-0[Próximo Capítulo &#62;]