include::./index.adoc[]

[[v13-4-0]]
=== 1 Crônicas, 4
// naa ?, NAA - Nova Almeida Atualizada

[[v13-4-1]]

^<<v13-4-1,1>>^ Os filhos de Judá foram: Perez, Hezrom, Carmi, Hur e Sobal.

[[v13-4-2]]

^<<v13-4-2,2>>^ Reaías, filho de Sobal, gerou Jaate; Jaate gerou Aumai e Laade; estas são as famílias dos zoratitas.

[[v13-4-3]]

^<<v13-4-3,3>>^ Estes foram os filhos do pai de Etã: Jezreel, Isma e Idbas; e o nome da irmã deles era Hazelelponi;

[[v13-4-4]]

^<<v13-4-4,4>>^ e mais Penuel, pai de Gedor, e Ezer, pai de Husa. Estes foram os filhos de Hur, o primogênito de Efrata e pai de Belém.

[[v13-4-5]]

^<<v13-4-5,5>>^ Asur, pai de Tecoa, teve duas mulheres: Hela e Naara.

[[v13-4-6]]

^<<v13-4-6,6>>^ Naara deu à luz Auzão, Héfer, Temeni e Haastari; estes foram os filhos de Naara.

[[v13-4-7]]

^<<v13-4-7,7>>^ Os filhos de Hela foram: Zerete, Isar e Etnã.

[[v13-4-8]]

^<<v13-4-8,8>>^ Coz gerou Anube e Zobeba e foi pai das famílias de Aarel, filho de Harum.

[[v13-4-9]]

^<<v13-4-9,9>>^ Jabez foi mais ilustre do que seus irmãos; a sua mãe deu-lhe o nome de Jabez, dizendo: "Porque com dores o dei à luz."

[[v13-4-10]]

^<<v13-4-10,10>>^ Jabez invocou o Deus de Israel, dizendo: Oh! Quem dera me abençoasses e expandisses o meu território! Que a tua mão esteja comigo! Preserva-me do mal, para que não me sobrevenha aflição! E Deus lhe concedeu o que ele tinha pedido.

[[v13-4-11]]

^<<v13-4-11,11>>^ Quelube, irmão de Suá, gerou Meir; este é o pai de Estom.

[[v13-4-12]]

^<<v13-4-12,12>>^ Estom gerou Bete-Rafa, Paseia e Teína, pai de Ir-Naás; estes foram os homens de Reca.

[[v13-4-13]]

^<<v13-4-13,13>>^ Os filhos de Quenaz foram: Otniel e Seraías; o filho de Otniel foi Hatate.

[[v13-4-14]]

^<<v13-4-14,14>>^ Meonotai gerou Ofra, e Seraías gerou Joabe, fundador do vale dos Artífices, porque os dali eram artífices.

[[v13-4-15]]

^<<v13-4-15,15>>^ Os filhos de Calebe, filho de Jefoné, foram: Iru, Elá e Naã; e o filho de Elá foi Quenaz.

[[v13-4-16]]

^<<v13-4-16,16>>^ Os filhos de Jealelel foram: Zife, Zifa, Tiria e Asareel.

[[v13-4-17]]

^<<v13-4-17,17>>^ Os filhos de Ezra foram: Jéter, Merede, Éfer e Jalom. Os filhos de Bitia, filha de Faraó, que Merede tomou por mulher, foram: Miriã, Samai e Isbá, pai de Estemoa.

[[v13-4-18]]

^<<v13-4-18,18>>^ E sua mulher, judia, deu à luz Jerede, pai de Gedor, Héber, pai de Socó, e Jecutiel, pai de Zanoa.

[[v13-4-19]]

^<<v13-4-19,19>>^ Os filhos da mulher de Hodias, irmã de Naã, foram: Abiqueila, o garmita, e Estemoa, o maacatita.

[[v13-4-20]]

^<<v13-4-20,20>>^ Os filhos de Simão foram: Amnom, Rina, Ben-Hanã e Tilom; e os filhos de Isi foram: Zoete e Ben-Zoete.

[[v13-4-21]]

^<<v13-4-21,21>>^ Os filhos de Selá, filho de Judá, foram: Er, pai de Leca, e Lada, pai de Maressa. Selá foi também pai das famílias da casa dos que trabalhavam com linho, em Bete-Asbeia,

[[v13-4-22]]

^<<v13-4-22,22>>^ bem como de Joquim, dos homens de Cozeba, de Joás, de Sarafe, os quais dominavam sobre Moabe, e de Jasubi-Leém. Estes registros são antigos.

[[v13-4-23]]

^<<v13-4-23,23>>^ Estes eram oleiros e habitantes de Netaim e de Gedera; moravam ali com o rei para o servirem.

[[v13-4-24]]

^<<v13-4-24,24>>^ Os filhos de Simeão foram: Nemuel, Jamim, Jaribe, Zerá e Saul,

[[v13-4-25]]

^<<v13-4-25,25>>^ de quem foi filho Salum, de quem foi filho Mibsão, de quem foi filho Misma.

[[v13-4-26]]

^<<v13-4-26,26>>^ O filho de Misma foi Hamuel, de quem foi filho Zacur, de quem foi filho Simei.

[[v13-4-27]]

^<<v13-4-27,27>>^ Simei teve dezesseis filhos e seis filhas; mas seus irmãos não tiveram muitos filhos, nem se multiplicaram todas as suas famílias como os filhos de Judá.

[[v13-4-28]]

^<<v13-4-28,28>>^ Habitavam em Berseba, em Molada, em Hazar-Sual,

[[v13-4-29]]

^<<v13-4-29,29>>^ em Bila, em Ezém, em Tolade,

[[v13-4-30]]

^<<v13-4-30,30>>^ em Betuel, em Horma, em Ziclague,

[[v13-4-31]]

^<<v13-4-31,31>>^ em Bete-Marcabote, em Hazar-Susim, em Bete-Biri e em Saaraim. Estas foram as suas cidades, até o reinado de Davi.

[[v13-4-32]]

^<<v13-4-32,32>>^ As suas aldeias foram: Etã, Aim, Rimom, Toquém e Asã; cinco cidades,

[[v13-4-33]]

^<<v13-4-33,33>>^ com todas as suas aldeias que estavam ao redor destas cidades, até Baal. Estas foram as suas habitações e tinham seu registro genealógico.

[[v13-4-34]]

^<<v13-4-34,34>>^ Estes, registrados por seus nomes, foram chefes nas suas famílias: Mesobabe, Janleque, Josa, filho de Amazias,

[[v13-4-35]]

^<<v13-4-35,35>>^ Joel, Jeú, filho de Josibias, filho de Seraías, filho de Asiel,

[[v13-4-36]]

^<<v13-4-36,36>>^ Elioenai, Jaacobá, Jesoaías, Asaías, Adiel, Jesimiel, Benaia,

[[v13-4-37]]

^<<v13-4-37,37>>^ Ziza, filho de Sifi, filho de Alom, filho de Jedaías, filho de Sinri, filho de Semaías;

[[v13-4-38]]

^<<v13-4-38,38>>^ e as famílias de seus pais se multiplicaram abundantemente.

[[v13-4-39]]

^<<v13-4-39,39>>^ Chegaram até a entrada de Gedor, a leste do vale, à procura de pasto para os seus rebanhos.

[[v13-4-40]]

^<<v13-4-40,40>>^ Acharam pasto farto e bom e a terra espaçosa, tranquila e pacífica, onde os descendentes de Cam haviam morado antes.

[[v13-4-41]]

^<<v13-4-41,41>>^ Estes, que estão registrados por seus nomes, foram nos dias de Ezequias, rei de Judá, e derrubaram as tendas, e atacaram os meunitas que se encontravam ali, e os destruíram totalmente até o dia de hoje, e ficaram morando no lugar deles, porque ali havia pasto para os seus rebanhos.

[[v13-4-42]]

^<<v13-4-42,42>>^ Também deles, dos filhos de Simeão, quinhentos homens foram ao monte Seir, tendo por capitães Pelatias, Nearias, Refaías e Uziel, filhos de Isi.

[[v13-4-43]]

^<<v13-4-43,43>>^ Mataram o restante dos que escaparam dos amalequitas e estão morando ali até o dia de hoje.

'''

xref:013-1-cronicas/013-1-cronicas-003.adoc#v13-3-0[&#60; Capítulo Anterior] | <<v13-4-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-005.adoc#v13-5-0[Próximo Capítulo &#62;]