include::./index.adoc[]

[[v13-14-0]]
=== 1 Crônicas, 14
// naa ?, NAA - Nova Almeida Atualizada

[[v13-14-1]]

^<<v13-14-1,1>>^ Hirão, rei de Tiro, enviou a Davi mensageiros, madeira de cedro, pedreiros e carpinteiros, para lhe construírem um palácio.

[[v13-14-2]]

^<<v13-14-2,2>>^ Então Davi reconheceu que o Senhor  o havia confirmado como rei sobre Israel e que tinha exaltado muito o seu reino por amor do seu povo de Israel.

[[v13-14-3]]

^<<v13-14-3,3>>^ Davi tomou ainda mais mulheres em Jerusalém e gerou ainda mais filhos e filhas.

[[v13-14-4]]

^<<v13-14-4,4>>^ São estes os nomes dos filhos de Davi que nasceram em Jerusalém: Samua, Sobabe, Natã, Salomão,

[[v13-14-5]]

^<<v13-14-5,5>>^ Ibar, Elisua, Elpelete,

[[v13-14-6]]

^<<v13-14-6,6>>^ Nogá, Nefegue, Jafia,

[[v13-14-7]]

^<<v13-14-7,7>>^ Elisama, Beeliada e Elifelete.

[[v13-14-8]]

^<<v13-14-8,8>>^ Quando os filisteus ouviram que Davi tinha sido ungido rei sobre todo o Israel, subiram todos para prendê-lo. Quando soube disso, Davi saiu contra eles.

[[v13-14-9]]

^<<v13-14-9,9>>^ Mas os filisteus vieram e investiram contra ele no vale dos Refains.

[[v13-14-10]]

^<<v13-14-10,10>>^ Então Davi consultou Deus, dizendo: — Devo atacar os filisteus? Tu os entregarás nas minhas mãos? O Senhor  respondeu: — Vá, porque os entregarei nas suas mãos.

[[v13-14-11]]

^<<v13-14-11,11>>^ Então Davi foi até Baal-Perazim e os derrotou ali. E disse: — Deus, por meio de mim, rompeu as fileiras inimigas, como as águas rompem barreiras. Por isso, chamaram aquele lugar de Baal-Perazim.

[[v13-14-12]]

^<<v13-14-12,12>>^ Os filisteus deixaram lá os seus deuses, e Davi ordenou que fossem queimados.

[[v13-14-13]]

^<<v13-14-13,13>>^ Os filisteus tornaram a subir e fizeram uma nova investida no vale.

[[v13-14-14]]

^<<v13-14-14,14>>^ De novo, Davi consultou Deus, e este lhe respondeu: — Não vá atrás deles, mas rodeie por detrás deles e ataque-os por diante das amoreiras.

[[v13-14-15]]

^<<v13-14-15,15>>^ Quando você ouvir um barulho de marcha pelas copas das amoreiras, saia para a batalha: é Deus que saiu à sua frente, para atacar o exército dos filisteus.

[[v13-14-16]]

^<<v13-14-16,16>>^ Davi fez como Deus lhe havia ordenado, e atacou o exército dos filisteus desde Gibeão até Gezer.

[[v13-14-17]]

^<<v13-14-17,17>>^ Assim a fama de Davi se espalhou por todas aquelas terras, e o Senhor  fez com que todas as nações tivessem medo dele.

'''

xref:013-1-cronicas/013-1-cronicas-013.adoc#v13-13-0[&#60; Capítulo Anterior] | <<v13-14-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-015.adoc#v13-15-0[Próximo Capítulo &#62;]