include::./index.adoc[]

[[v13-22-0]]
=== 1 Crônicas, 22
// naa ?, NAA - Nova Almeida Atualizada

[[v13-22-1]]

^<<v13-22-1,1>>^ Davi disse: — Aqui se levantará a Casa do Senhor  Deus e o altar do holocausto para Israel.

[[v13-22-2]]

^<<v13-22-2,2>>^ Davi deu ordem para que fossem reunidos os estrangeiros que estavam na terra de Israel, e encarregou pedreiros que preparassem pedras lavradas para a construção da Casa de Deus.

[[v13-22-3]]

^<<v13-22-3,3>>^ Davi ajuntou ferro em abundância, para os pregos das folhas dos portões e para as junções, bem como bronze em abundância, que nem foi pesado,

[[v13-22-4]]

^<<v13-22-4,4>>^ além de madeira de cedro sem conta, porque os homens de Tiro e de Sidom a traziam a Davi em grande quantidade.

[[v13-22-5]]

^<<v13-22-5,5>>^ Pois Davi dizia: — Meu filho Salomão ainda é moço e inexperiente, e o templo que será edificado para o Senhor  deve ser sobremodo magnífico, para nome e glória em todas as terras. Portanto, vou providenciar o necessário para a construção. Assim, antes de morrer, Davi providenciou materiais em abundância.

[[v13-22-6]]

^<<v13-22-6,6>>^ Então Davi chamou Salomão, seu filho, e lhe ordenou que edificasse um templo ao Senhor , Deus de Israel.

[[v13-22-7]]

^<<v13-22-7,7>>^ Davi disse a Salomão: — Meu filho, tive a intenção de edificar um templo ao nome do Senhor , meu Deus.

[[v13-22-8]]

^<<v13-22-8,8>>^ Porém a palavra do Senhor  veio a mim, dizendo: "Você derramou muito sangue e fez grandes guerras. Você não edificará um templo ao meu nome, porque derramou muito sangue na terra, na minha presença.

[[v13-22-9]]

^<<v13-22-9,9>>^ Eis que lhe nascerá um filho, que será homem pacífico, porque lhe darei descanso de todos os seus inimigos ao redor. Portanto, o nome dele será Salomão, e nos seus dias darei paz e tranquilidade a Israel.

[[v13-22-10]]

^<<v13-22-10,10>>^ Este edificará um templo ao meu nome. Ele me será por filho, e eu lhe serei por pai; e eu estabelecerei para sempre o trono do seu reino sobre Israel."

[[v13-22-11]]

^<<v13-22-11,11>>^ — Agora, meu filho, que o Senhor  esteja com você, a fim de que você prospere e possa edificar a Casa do Senhor , seu Deus, como ele disse a seu respeito.

[[v13-22-12]]

^<<v13-22-12,12>>^ Que o Senhor  lhe conceda prudência e entendimento, para que, quando for rei sobre Israel, você guarde a Lei do Senhor , seu Deus.

[[v13-22-13]]

^<<v13-22-13,13>>^ Então você prosperará, se tiver o cuidado de cumprir os estatutos e os juízos que o Senhor  ordenou a Moisés a respeito de Israel. Seja forte e corajoso, não tenha medo, nem fique assustado.

[[v13-22-14]]

^<<v13-22-14,14>>^ Eis que, com muito esforço, preparei para a Casa do Senhor  três mil e quatrocentas toneladas de ouro e mais de trinta e quatro mil toneladas de prata, e bronze e ferro em tal abundância, que nem foram pesados. Também preparei madeira e pedras, cuja quantidade você pode aumentar.

[[v13-22-15]]

^<<v13-22-15,15>>^ Além disso, você tem um grande número de trabalhadores: cortadores de pedras, pedreiros, carpinteiros e peritos em todo tipo de trabalho

[[v13-22-16]]

^<<v13-22-16,16>>^ em ouro, prata, bronze e ferro, que não se pode contar. Portanto, mãos à obra, e que o Senhor  esteja com você!

[[v13-22-17]]

^<<v13-22-17,17>>^ Davi ordenou a todos os chefes de Israel que ajudassem Salomão, seu filho, dizendo:

[[v13-22-18]]

^<<v13-22-18,18>>^ — Não está com vocês o Senhor , seu Deus? E não é fato que lhes deu paz por todos os lados? Pois ele entregou nas minhas mãos os moradores desta terra, a qual está sujeita diante do Senhor  e diante do seu povo.

[[v13-22-19]]

^<<v13-22-19,19>>^ Agora disponham o coração e a alma para buscar o Senhor , seu Deus. Preparem-se e comecem a construir o santuário do Senhor  Deus, para que a arca da aliança do Senhor  e os utensílios sagrados de Deus sejam trazidos a este templo, que será edificado ao nome do Senhor .

'''

xref:013-1-cronicas/013-1-cronicas-021.adoc#v13-21-0[&#60; Capítulo Anterior] | <<v13-22-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-023.adoc#v13-23-0[Próximo Capítulo &#62;]