include::./index.adoc[]

[[v13-26-0]]
=== 1 Crônicas, 26
// naa ?, NAA - Nova Almeida Atualizada

[[v13-26-1]]

^<<v13-26-1,1>>^ Quanto aos turnos dos porteiros: dos coraítas, Meselemias, filho de Coré, dos filhos de Asafe.

[[v13-26-2]]

^<<v13-26-2,2>>^ Os filhos de Meselemias foram: Zacarias, o primogênito, Jediael, o segundo, Zebadias, o terceiro, Jatniel, o quarto,

[[v13-26-3]]

^<<v13-26-3,3>>^ Elão, o quinto, Joanã, o sexto, Elioenai, o sétimo.

[[v13-26-4]]

^<<v13-26-4,4>>^ Os filhos de Obede-Edom foram: Semaías, o primogênito, Jeozabade, o segundo, Joá, o terceiro, Sacar, o quarto, Natanael, o quinto,

[[v13-26-5]]

^<<v13-26-5,5>>^ Amiel, o sexto, Issacar, o sétimo, Peuletai, o oitavo. Porque Deus tinha abençoado Obede-Edom.

[[v13-26-6]]

^<<v13-26-6,6>>^ Também a seu filho Semaías nasceram filhos, que dominaram sobre a casa de seu pai; porque foram homens valentes.

[[v13-26-7]]

^<<v13-26-7,7>>^ Os filhos de Semaías foram: Otni, Rafael, Obede e Elzabade, cujos irmãos Eliú e Semaquias eram homens valentes.

[[v13-26-8]]

^<<v13-26-8,8>>^ Todos estes foram dos filhos de Obede-Edom; eles, seus filhos e seus irmãos, homens capazes e robustos para o serviço; ao todo, sessenta e dois.

[[v13-26-9]]

^<<v13-26-9,9>>^ Os filhos e os irmãos de Meselemias, homens valentes, foram dezoito.

[[v13-26-10]]

^<<v13-26-10,10>>^ De Hosa, dos filhos de Merari, foram filhos: Sinri, a quem o pai constituiu chefe, ainda que não era o primogênito,

[[v13-26-11]]

^<<v13-26-11,11>>^ Hilquias, o segundo, Tebalias, o terceiro, Zacarias, o quarto; todos os filhos e irmãos de Hosa foram treze.

[[v13-26-12]]

^<<v13-26-12,12>>^ A estes turnos dos porteiros, isto é, a seus chefes, foi entregue a guarda, para servirem, como seus irmãos, na Casa do Senhor .

[[v13-26-13]]

^<<v13-26-13,13>>^ Para cada portão fizeram um sorteio para designar os deveres tanto dos pequenos como dos grandes, segundo as suas famílias.

[[v13-26-14]]

^<<v13-26-14,14>>^ A guarda do lado do leste caiu por sorteio a Selemias; depois, lançaram sorte sobre seu filho Zacarias, conselheiro prudente, e lhe saiu a guarda do lado do norte;

[[v13-26-15]]

^<<v13-26-15,15>>^ a Obede-Edom, a guarda do lado do sul; e a seus filhos, a guarda da casa de depósitos;

[[v13-26-16]]

^<<v13-26-16,16>>^ a Supim e Hosa, a guarda do oeste, junto ao portão de Salequete, na estrada que sobe. Uma guarda ficava ao lado de outra guarda.

[[v13-26-17]]

^<<v13-26-17,17>>^ A leste, estavam de guarda seis levitas; ao norte, quatro por dia; ao sul, quatro por dia, e, para a casa de depósitos, dois num lugar e dois noutro.

[[v13-26-18]]

^<<v13-26-18,18>>^ No átrio a oeste, quatro junto ao caminho, dois junto ao átrio.

[[v13-26-19]]

^<<v13-26-19,19>>^ São estes os turnos dos porteiros dos filhos dos coraítas e dos filhos de Merari.

[[v13-26-20]]

^<<v13-26-20,20>>^ Outros levitas, seus irmãos, tinham o encargo dos tesouros da Casa de Deus e dos tesouros das coisas consagradas:

[[v13-26-21]]

^<<v13-26-21,21>>^ os filhos de Ladã, descendentes dos gersonitas pertencentes a Ladã e chefes das famílias deste, da família de Gérson: Jeieli;

[[v13-26-22]]

^<<v13-26-22,22>>^ os filhos de Jeieli: Zetã e Joel, seu irmão; estes estavam encarregados dos tesouros da Casa do Senhor .

[[v13-26-23]]

^<<v13-26-23,23>>^ Dos anramitas, dos isaritas, dos hebronitas, dos uzielitas,

[[v13-26-24]]

^<<v13-26-24,24>>^ Sebuel, filho de Gérson, filho de Moisés, era oficial encarregado dos tesouros.

[[v13-26-25]]

^<<v13-26-25,25>>^ Seus irmãos: de Eliézer, foi filho Reabias, de quem foi filho Jesaías, de quem foi filho Jorão, de quem foi filho Zicri, de quem foi filho Selomite.

[[v13-26-26]]

^<<v13-26-26,26>>^ Este Selomite e os seus irmãos tinham a seu encargo todos os tesouros das coisas consagradas que o rei Davi e os chefes das famílias, capitães de milhares e de centenas e capitães do exército tinham dedicado.

[[v13-26-27]]

^<<v13-26-27,27>>^ Dos despojos das guerras as dedicaram para a conservação da Casa do Senhor .

[[v13-26-28]]

^<<v13-26-28,28>>^ Tinham também a seu encargo tudo o que havia sido dedicado por Samuel, o vidente, por Saul, filho de Quis, por Abner, filho de Ner, e por Joabe, filho de Zeruia. Tudo o que qualquer pessoa havia dedicado estava sob os cuidados de Selomite e seus irmãos.

[[v13-26-29]]

^<<v13-26-29,29>>^ Dos isaritas, Quenanias e seus filhos foram postos sobre Israel, para oficiais e juízes dos negócios externos.

[[v13-26-30]]

^<<v13-26-30,30>>^ Dos hebronitas, foram Hasabias e seus irmãos, homens valentes, mil e setecentos, que superintendiam Israel, além do Jordão para o oeste, em todo serviço do Senhor  e interesses do rei;

[[v13-26-31]]

^<<v13-26-31,31>>^ dos hebronitas, Jerias era o chefe. Quanto aos hebronitas, suas genealogias e famílias, se fizeram investigações no quadragésimo ano do reinado de Davi e se acharam entre eles homens valentes em Jazer de Gileade.

[[v13-26-32]]

^<<v13-26-32,32>>^ Seus irmãos, homens valentes, dois mil e setecentos, chefes das famílias; e o rei Davi os constituiu sobre os rubenitas, os gaditas e a meia tribo dos manassitas, para todos os negócios de Deus e para todos os negócios do rei.

'''

xref:013-1-cronicas/013-1-cronicas-025.adoc#v13-25-0[&#60; Capítulo Anterior] | <<v13-26-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-027.adoc#v13-27-0[Próximo Capítulo &#62;]