include::./index.adoc[]

[[v13-16-0]]
=== 1 Crônicas, 16
// naa ?, NAA - Nova Almeida Atualizada

[[v13-16-1]]

^<<v13-16-1,1>>^ Levaram a arca de Deus e a puseram no meio da tenda que Davi tinha preparado para ela. Então trouxeram holocaustos e ofertas pacíficas diante de Deus.

[[v13-16-2]]

^<<v13-16-2,2>>^ Depois de trazer os holocaustos e as ofertas pacíficas, Davi abençoou o povo em nome do Senhor .

[[v13-16-3]]

^<<v13-16-3,3>>^ E repartiu a todos em Israel, tanto homens como mulheres, a cada um, um bolo de pão, um bom pedaço de carne e passas.

[[v13-16-4]]

^<<v13-16-4,4>>^ Designou dentre os levitas os que haviam de ministrar diante da arca do Senhor , e celebrar, louvar e exaltar o Senhor , Deus de Israel, a saber,

[[v13-16-5]]

^<<v13-16-5,5>>^ Asafe, o chefe, Zacarias, o segundo, e depois Jeiel, Semiramote, Jeiel, Matitias, Eliabe, Benaia, Obede-Edom e Jeiel, com liras e harpas; e Asafe fazia ressoar os címbalos.

[[v13-16-6]]

^<<v13-16-6,6>>^ Os sacerdotes Benaia e Jaaziel estavam continuamente com trombetas, diante da arca da aliança de Deus.

[[v13-16-7]]

^<<v13-16-7,7>>^ Foi naquele dia que Davi encarregou, pela primeira vez, Asafe e seus irmãos de celebrarem com hinos o Senhor .

[[v13-16-8]]

^<<v13-16-8,8>>^ Deem graças ao Senhor , invoquem o seu nome; tornem conhecidos entre os povos os seus feitos.

[[v13-16-9]]

^<<v13-16-9,9>>^ Cantem a Deus, cantem louvores a ele; falem de todas as suas maravilhas.

[[v13-16-10]]

^<<v13-16-10,10>>^ Gloriem-se no seu santo nome; alegre-se o coração dos que buscam o Senhor .

[[v13-16-11]]

^<<v13-16-11,11>>^ Busquem o Senhor e o seu poder; busquem continuamente a sua presença.

[[v13-16-12]]

^<<v13-16-12,12>>^ Lembrem-se das maravilhas que ele fez, dos seus prodígios e dos juízos de seus lábios,

[[v13-16-13]]

^<<v13-16-13,13>>^ vocês, descendentes de Israel, seu servo, vocês, filhos de Jacó, seus escolhidos.

[[v13-16-14]]

^<<v13-16-14,14>>^ Ele é o Senhor , nosso Deus; os seus juízos permeiam toda a terra.

[[v13-16-15]]

^<<v13-16-15,15>>^ Lembra-se perpetuamente da sua aliança, da palavra que empenhou para mil gerações;

[[v13-16-16]]

^<<v13-16-16,16>>^ da aliança que fez com Abraão e do juramento que fez a Isaque;

[[v13-16-17]]

^<<v13-16-17,17>>^ o qual confirmou a Jacó por decreto e a Israel, por aliança perpétua,

[[v13-16-18]]

^<<v13-16-18,18>>^ dizendo: "Eu lhe darei a terra de Canaã como porção da sua herança."

[[v13-16-19]]

^<<v13-16-19,19>>^ Então eles eram em pequeno número, pouquíssimos e estrangeiros na terra de Canaã;

[[v13-16-20]]

^<<v13-16-20,20>>^ andavam de nação em nação, de um reino para outro reino.

[[v13-16-21]]

^<<v13-16-21,21>>^ Deus não permitiu que ninguém os oprimisse, e, por amor deles, repreendeu reis,

[[v13-16-22]]

^<<v13-16-22,22>>^ dizendo: "Não toquem nos meus ungidos, nem maltratem os meus profetas."

[[v13-16-23]]

^<<v13-16-23,23>>^ Cantem ao Senhor , todas as terras; proclamem a sua salvação, dia após dia.

[[v13-16-24]]

^<<v13-16-24,24>>^ Anunciem entre as nações a sua glória, entre todos os povos, as suas maravilhas.

[[v13-16-25]]

^<<v13-16-25,25>>^ Porque o Senhor  é grande e digno de ser louvado, mais temível do que todos os deuses.

[[v13-16-26]]

^<<v13-16-26,26>>^ Porque todos os deuses dos povos não passam de ídolos; o Senhor , porém, fez os céus.

[[v13-16-27]]

^<<v13-16-27,27>>^ Glória e majestade estão diante dele, força e alegria, no seu santuário.

[[v13-16-28]]

^<<v13-16-28,28>>^ Deem ao Senhor , ó famílias dos povos, deem ao Senhor  glória e força.

[[v13-16-29]]

^<<v13-16-29,29>>^ Deem ao Senhor  a glória devida ao seu nome; tragam ofertas e entrem nos seus átrios. Adorem o Senhor na beleza da sua santidade.

[[v13-16-30]]

^<<v13-16-30,30>>^ Tremam diante dele, todas as terras, pois ele firmou o mundo para que não se abale.

[[v13-16-31]]

^<<v13-16-31,31>>^ Alegrem-se os céus, e a terra exulte; diga-se entre as nações: "O Senhor  reina."

[[v13-16-32]]

^<<v13-16-32,32>>^ Ruja o mar e a sua plenitude; alegre-se o campo e tudo o que nele há.

[[v13-16-33]]

^<<v13-16-33,33>>^ Cantem de alegria as árvores do bosque, na presença do Senhor , porque vem julgar a terra.

[[v13-16-34]]

^<<v13-16-34,34>>^ Deem graças ao Senhor , porque ele é bom, porque a sua misericórdia dura para sempre.

[[v13-16-35]]

^<<v13-16-35,35>>^ E digam: "Salva-nos, ó Deus da nossa salvação, congrega-nos e livra-nos das nações, para que demos graças ao teu santo nome e nos gloriemos no teu louvor."

[[v13-16-36]]

^<<v13-16-36,36>>^ Bendito seja o Senhor , Deus de Israel, de eternidade a eternidade. E todo o povo disse: "Amém!" E louvou o Senhor .

[[v13-16-37]]

^<<v13-16-37,37>>^ Então Davi deixou Asafe e seus irmãos ali diante da arca da aliança do Senhor , para ministrarem continuamente diante dela, segundo o que estava ordenado para cada dia.

[[v13-16-38]]

^<<v13-16-38,38>>^ Também deixou Obede-Edom com os seus irmãos, em número de sessenta e oito, bem como Obede-Edom, filho de Jedutum, e Hosa, para serem porteiros.

[[v13-16-39]]

^<<v13-16-39,39>>^ E deixou Zadoque, o sacerdote, e os sacerdotes, seus irmãos, diante do tabernáculo do Senhor , num lugar alto de Gibeão,

[[v13-16-40]]

^<<v13-16-40,40>>^ para oferecerem continuamente ao Senhor  os holocaustos sobre o altar dos holocaustos, de manhã e de tarde, segundo tudo o que está escrito na Lei que o Senhor  havia ordenado a Israel.

[[v13-16-41]]

^<<v13-16-41,41>>^ E com eles deixou Hemã, Jedutum e os demais escolhidos, que foram nominalmente designados para louvarem o Senhor , porque a sua misericórdia dura para sempre.

[[v13-16-42]]

^<<v13-16-42,42>>^ Portanto, com eles estavam Hemã e Jedutum, que faziam ressoar trombetas, címbalos e instrumentos musicais usados para louvar a Deus. Os filhos de Jedutum eram porteiros.

[[v13-16-43]]

^<<v13-16-43,43>>^ Então todo o povo se retirou, cada um para sua casa; Davi também foi, para abençoar a sua casa.

'''

xref:013-1-cronicas/013-1-cronicas-015.adoc#v13-15-0[&#60; Capítulo Anterior] | <<v13-16-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-017.adoc#v13-17-0[Próximo Capítulo &#62;]