include::./index.adoc[]

[[v13-19-0]]
=== 1 Crônicas, 19
// naa ?, NAA - Nova Almeida Atualizada

[[v13-19-1]]

^<<v13-19-1,1>>^ Depois disto, morreu Naás, rei dos filhos de Amom, e seu filho reinou em seu lugar.

[[v13-19-2]]

^<<v13-19-2,2>>^ Então Davi disse: — Serei bondoso com Hanum, filho de Naás, porque o pai dele foi bondoso comigo. E Davi enviou mensageiros para consolar Hanum por causa da morte de seu pai. E os servos de Davi chegaram à terra dos filhos de Amom, a Hanum, para o consolarem.

[[v13-19-3]]

^<<v13-19-3,3>>^ Mas os príncipes dos filhos de Amom disseram a Hanum: — O senhor pensa que foi para honrar o seu pai que Davi mandou esses consoladores? Não teria sido mais para que esses servos enviados por ele conheçam, destruam e espionem a terra?

[[v13-19-4]]

^<<v13-19-4,4>>^ Então Hanum pegou os servos de Davi, rapou a barba deles, cortou metade das roupas até a altura das nádegas, e os mandou embora.

[[v13-19-5]]

^<<v13-19-5,5>>^ Alguns foram e contaram a Davi o que tinha acontecido com aqueles homens. Então o rei enviou mensageiros ao encontro deles, porque estavam muito envergonhados. O rei mandou dizer-lhes: — Fiquem em Jericó, até que a barba de vocês cresça de novo; depois, venham para cá.

[[v13-19-6]]

^<<v13-19-6,6>>^ Quando viram que haviam despertado o ódio de Davi, Hanum e os filhos de Amom pegaram trinta e quatro toneladas de prata, para contratar carros de guerra e cavaleiros da Mesopotâmia, dos sírios de Maaca e de Zobá.

[[v13-19-7]]

^<<v13-19-7,7>>^ Contrataram trinta e dois mil carros de guerra, bem como o rei de Maaca e a sua gente. Eles vieram e acamparam perto de Medeba. Também os filhos de Amom se ajuntaram das suas cidades e vieram para a guerra.

[[v13-19-8]]

^<<v13-19-8,8>>^ Davi soube disso e enviou contra eles Joabe com todo o exército dos valentes.

[[v13-19-9]]

^<<v13-19-9,9>>^ Os filhos de Amom saíram e se prepararam para a batalha à entrada do portão da cidade; porém os reis que vieram estavam à parte no campo.

[[v13-19-10]]

^<<v13-19-10,10>>^ Quando Joabe viu que a batalha estava preparada contra ele tanto pela frente como pela retaguarda, escolheu os melhores soldados de Israel e os formou em linha contra os sírios.

[[v13-19-11]]

^<<v13-19-11,11>>^ O resto do exército ele entregou a Abisai, seu irmão, e puseram-se em linha contra os filhos de Amom.

[[v13-19-12]]

^<<v13-19-12,12>>^ Joabe disse a Abisai: — Se os sírios forem mais fortes do que eu, você virá em meu socorro; e, se os filhos de Amom forem mais fortes do que você, eu irei em seu socorro.

[[v13-19-13]]

^<<v13-19-13,13>>^ Seja forte! Vamos lutar com coragem pelo nosso povo e pelas cidades de nosso Deus. E que o Senhor  Deus faça o que achar melhor.

[[v13-19-14]]

^<<v13-19-14,14>>^ Então Joabe avançou com o povo que estava com ele, e travaram batalha contra os sírios, que fugiram diante dele.

[[v13-19-15]]

^<<v13-19-15,15>>^ Quando os filhos de Amom viram que os sírios fugiam, também eles fugiram de Abisai, irmão de Joabe, e entraram na cidade. Então Joabe parou de lutar contra os filhos de Amom e voltou para Jerusalém.

[[v13-19-16]]

^<<v13-19-16,16>>^ Quando os sírios viram que tinham sido derrotados por Israel, enviaram mensageiros e chamaram os sírios que estavam do outro lado do rio Eufrates. Sofaque, comandante do exército de Hadadezer, marchava adiante deles.

[[v13-19-17]]

^<<v13-19-17,17>>^ Quando ficou sabendo disso, Davi reuniu todo o Israel, passou o Jordão, foi ao encontro deles e se pôs em ordem de batalha. Depois que Davi tinha feito isto, os sírios lutaram contra ele.

[[v13-19-18]]

^<<v13-19-18,18>>^ Porém os sírios fugiram de Israel, e Davi matou os condutores de sete mil carros de guerra e quarenta mil soldados de infantaria dos sírios; e matou Sofaque, o comandante do exército.

[[v13-19-19]]

^<<v13-19-19,19>>^ Quando os servos de Hadadezer viram que tinham sido vencidos por Israel, fizeram paz com Davi e o serviram. E os sírios nunca mais quiseram socorrer os filhos de Amom.

'''

xref:013-1-cronicas/013-1-cronicas-018.adoc#v13-18-0[&#60; Capítulo Anterior] | <<v13-19-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-020.adoc#v13-20-0[Próximo Capítulo &#62;]