include::./index.adoc[]

[[v13-28-0]]
=== 1 Crônicas, 28
// naa ?, NAA - Nova Almeida Atualizada

[[v13-28-1]]

^<<v13-28-1,1>>^ Davi convocou para Jerusalém todos os chefes de Israel, os chefes das tribos, os capitães dos turnos que serviam o rei, os capitães de mil e os de cem, os administradores de todos os bens e rebanhos do rei e de seus filhos, bem como os oficiais, os poderosos e todos os guerreiros valentes.

[[v13-28-2]]

^<<v13-28-2,2>>^ O rei Davi se pôs em pé e disse: — Meus irmãos e meu povo, escutem! Eu tive a intenção de edificar um templo onde pudesse repousar a arca da aliança do Senhor  e para que fosse o estrado dos pés do nosso Deus. Eu havia feito preparativos para essa construção.

[[v13-28-3]]

^<<v13-28-3,3>>^ Porém Deus me disse: "Você não edificará um templo ao meu nome, porque é homem de guerra e derramou muito sangue."

[[v13-28-4]]

^<<v13-28-4,4>>^ O Senhor , Deus de Israel, me escolheu de toda a casa de meu pai, para que eu fosse rei sobre Israel para sempre. Porque ele escolheu Judá por príncipe e, da casa de Judá, escolheu a casa de meu pai. E entre os filhos de meu pai se agradou de mim, para me fazer rei sobre todo o Israel.

[[v13-28-5]]

^<<v13-28-5,5>>^ E, de todos os meus filhos — porque muitos filhos me deu o Senhor  —, ele escolheu Salomão para se assentar no trono do reino do Senhor , sobre Israel.

[[v13-28-6]]

^<<v13-28-6,6>>^ E me disse: "O seu filho Salomão é quem edificará o meu templo e os meus átrios, porque o escolhi para filho e eu lhe serei por pai.

[[v13-28-7]]

^<<v13-28-7,7>>^ Estabelecerei o seu reino para sempre, se ele continuar a cumprir os meus mandamentos e os meus juízos, como tem feito até o dia de hoje."

[[v13-28-8]]

^<<v13-28-8,8>>^ Portanto, agora, diante de todo o Israel, a congregação do Senhor , e diante do nosso Deus, que me ouve, eu peço que vocês guardem e conheçam todos os mandamentos do Senhor , seu Deus, para que vocês possuam esta boa terra e possam deixá-la como herança aos seus filhos, para sempre.

[[v13-28-9]]

^<<v13-28-9,9>>^ — Quanto a você, meu filho Salomão, conheça o Deus de seu pai e sirva-o de coração íntegro e espírito voluntário, porque o Senhor  esquadrinha todos os corações e penetra todos os desígnios do pensamento. Se você o buscar, ele se deixará achar por você; mas, se você o abandonar, ele o rejeitará para sempre.

[[v13-28-10]]

^<<v13-28-10,10>>^ Agora tenha cuidado, porque o Senhor  o escolheu para edificar uma casa que sirva de santuário. Seja forte e mãos à obra!

[[v13-28-11]]

^<<v13-28-11,11>>^ Davi entregou a Salomão, seu filho, a planta do pórtico com as suas casas, as suas tesourarias, os seus cenáculos e as suas câmaras interiores, bem como do lugar do propiciatório.

[[v13-28-12]]

^<<v13-28-12,12>>^ Também entregou a planta de tudo o que tinha em mente com referência aos átrios da Casa do Senhor , e a todas as câmaras ao redor, para os tesouros da Casa de Deus e para os tesouros das coisas consagradas.

[[v13-28-13]]

^<<v13-28-13,13>>^ Deu-lhe instruções para organizar os turnos dos sacerdotes e dos levitas, e para toda obra do ministério da Casa do Senhor , e para todos os utensílios para o serviço da Casa do Senhor .

[[v13-28-14]]

^<<v13-28-14,14>>^ Especificou o peso do ouro para todos os utensílios de ouro de cada serviço; o peso da prata para todos os utensílios de prata de cada serviço;

[[v13-28-15]]

^<<v13-28-15,15>>^ o peso para os candelabros de ouro e as suas lâmpadas de ouro, para cada candelabro e suas lâmpadas, segundo o uso de cada um;

[[v13-28-16]]

^<<v13-28-16,16>>^ também o peso do ouro para cada uma das mesas da proposição, e o peso da prata para as mesas de prata;

[[v13-28-17]]

^<<v13-28-17,17>>^ ouro puro para os garfos, para as bacias e para os copos; para as taças de ouro o devido peso a cada uma, bem como para as taças de prata, a cada uma o seu peso;

[[v13-28-18]]

^<<v13-28-18,18>>^ o peso do ouro refinado para o altar do incenso, bem como, segundo a planta, o ouro para o carro dos querubins, que haviam de estender as asas e cobrir a arca da aliança do Senhor .

[[v13-28-19]]

^<<v13-28-19,19>>^ Davi disse: — Tudo isto me foi dado por escrito por mandado do Senhor , a saber, todas as obras desta planta.

[[v13-28-20]]

^<<v13-28-20,20>>^ Então Davi disse a Salomão, seu filho: — Seja forte e corajoso e mãos à obra! Não tenha medo, nem fique assustado, porque o Senhor  Deus, meu Deus, estará com você. Ele não o deixará, nem o abandonará, até que você termine todas as obras para o serviço da Casa do Senhor .

[[v13-28-21]]

^<<v13-28-21,21>>^ Eis aí os turnos dos sacerdotes e dos levitas para todo serviço da Casa de Deus. E, para toda obra, você poderá contar com voluntários competentes para fazer todo tipo de serviço. Também os chefes e todo o povo estarão inteiramente às suas ordens.

'''

xref:013-1-cronicas/013-1-cronicas-027.adoc#v13-27-0[&#60; Capítulo Anterior] | <<v13-28-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-029.adoc#v13-29-0[Próximo Capítulo &#62;]