include::./index.adoc[]

[[v13-21-0]]
=== 1 Crônicas, 21
// naa ?, NAA - Nova Almeida Atualizada

[[v13-21-1]]

^<<v13-21-1,1>>^ Então Satanás se levantou contra Israel e incitou Davi a levantar o censo de Israel.

[[v13-21-2]]

^<<v13-21-2,2>>^ Davi disse a Joabe e aos chefes do povo: — Vão e levantem o censo de Israel, desde Berseba até Dã, e tragam-me a apuração para que eu saiba o seu número.

[[v13-21-3]]

^<<v13-21-3,3>>^ Então Joabe disse: — Que o Senhor , seu Deus, multiplique este povo cem vezes mais! No entanto, meu rei e senhor, não são todos eles servos de meu senhor? Por que meu senhor requer isso? Por que trazer, assim, culpa sobre Israel?

[[v13-21-4]]

^<<v13-21-4,4>>^ Porém a palavra do rei prevaleceu contra Joabe. Então Joabe saiu e percorreu todo o Israel; depois, voltou para Jerusalém.

[[v13-21-5]]

^<<v13-21-5,5>>^ Joabe apresentou a Davi o resultado do recenseamento do povo: havia em Israel um milhão e cem mil homens que puxavam da espada; e em Judá eram quatrocentos e setenta mil homens que puxavam da espada.

[[v13-21-6]]

^<<v13-21-6,6>>^ Porém os de Levi e Benjamim não foram contados entre eles, porque a ordem do rei foi abominável a Joabe.

[[v13-21-7]]

^<<v13-21-7,7>>^ Tudo isto desagradou a Deus, e por isso ele castigou Israel.

[[v13-21-8]]

^<<v13-21-8,8>>^ Então Davi se dirigiu a Deus, dizendo: — Cometi um grande pecado ao fazer tal coisa. Mas agora peço-te que perdoes a iniquidade do teu servo, porque fiz uma grande loucura.

[[v13-21-9]]

^<<v13-21-9,9>>^ Então o Senhor  falou a Gade, o vidente de Davi, dizendo:

[[v13-21-10]]

^<<v13-21-10,10>>^ — Vá e diga a Davi: Assim diz o Senhor : "Eu lhe ofereço três opções; escolha uma delas, para que eu a execute contra você."

[[v13-21-11]]

^<<v13-21-11,11>>^ Gade foi falar com Davi e lhe disse: — Assim diz o Senhor : "Escolha o que você quer:

[[v13-21-12]]

^<<v13-21-12,12>>^ ou três anos de fome, ou que por três meses você seja consumido diante dos seus adversários, sendo alcançado pela espada dos seus inimigos, ou que por três dias a espada do Senhor , isto é, a peste na terra e o Anjo do Senhor  causem destruição em todos os territórios de Israel." Diga, agora, que resposta devo dar ao que me enviou.

[[v13-21-13]]

^<<v13-21-13,13>>^ Então Davi disse a Gade: — Estou muito angustiado. Porém é preferível que eu caia nas mãos do Senhor , porque muitas são as suas misericórdias; não quero cair nas mãos dos homens.

[[v13-21-14]]

^<<v13-21-14,14>>^ Então o Senhor  enviou a peste a Israel; e morreram setenta mil homens do povo de Israel.

[[v13-21-15]]

^<<v13-21-15,15>>^ Deus enviou um anjo a Jerusalém, para a destruir. Quando estava por destruí-la, o Senhor  olhou, mudou de ideia quanto a este mal e disse ao anjo destruidor: — Basta! Retire a sua mão. O Anjo do Senhor  estava junto à eira de Ornã, o jebuseu.

[[v13-21-16]]

^<<v13-21-16,16>>^ Davi ergueu os olhos e viu o Anjo do Senhor , que estava entre a terra e o céu, com a espada desembainhada na mão estendida contra Jerusalém. Então Davi e os anciãos, vestidos de pano de saco, se prostraram com o rosto em terra.

[[v13-21-17]]

^<<v13-21-17,17>>^ Davi falou para Deus: — Por acaso não fui eu quem mandou contar o povo? Eu é que pequei e fiz esse mal. Mas estas ovelhas o que fizeram? Ah! Senhor , meu Deus, que a tua mão seja contra mim e contra a casa de meu pai, mas não contra o teu povo, para castigá-lo.

[[v13-21-18]]

^<<v13-21-18,18>>^ Então o Anjo do Senhor  disse a Gade que mandasse Davi edificar um altar ao Senhor  na eira de Ornã, o jebuseu.

[[v13-21-19]]

^<<v13-21-19,19>>^ Davi foi segundo a palavra que Gade havia falado em nome do Senhor .

[[v13-21-20]]

^<<v13-21-20,20>>^ Ao voltar-se, Ornã viu o Anjo; e os seus quatro filhos que estavam com ele se esconderam. Ora, Ornã estava debulhando trigo.

[[v13-21-21]]

^<<v13-21-21,21>>^ Quando Davi estava indo ao encontro de Ornã, este olhou e viu Davi. E, saindo da eira, se inclinou diante de Davi, com o rosto em terra.

[[v13-21-22]]

^<<v13-21-22,22>>^ Davi disse a Ornã: — Dê-me este lugar da eira, a fim de edificar nele um altar ao Senhor , para que cesse a praga de sobre o povo. Venda-me este lugar pelo seu devido valor.

[[v13-21-23]]

^<<v13-21-23,23>>^ Então Ornã disse a Davi: — Que o rei, meu senhor, a tome para si e faça dela o que bem quiser. Eis que dou os bois para o holocausto, o debulhador de cereais para a lenha e o trigo para a oferta de cereais; dou tudo.

[[v13-21-24]]

^<<v13-21-24,24>>^ Porém o rei Davi disse a Ornã: — Não! Eu vou comprar pelo seu inteiro valor. Porque não tomarei o que é seu para dar ao Senhor , nem oferecerei holocausto que não me custe nada.

[[v13-21-25]]

^<<v13-21-25,25>>^ Davi pagou a Ornã por aquele lugar sete quilos e duzentos gramas de ouro.

[[v13-21-26]]

^<<v13-21-26,26>>^ Edificou ali um altar ao Senhor , ofereceu nele holocaustos e sacrifícios pacíficos e invocou o Senhor , que lhe respondeu com fogo do céu sobre o altar do holocausto.

[[v13-21-27]]

^<<v13-21-27,27>>^ O Senhor  deu ordem ao Anjo, e ele meteu a sua espada na bainha.

[[v13-21-28]]

^<<v13-21-28,28>>^ Naquele tempo, ao ver que o Senhor  lhe havia respondido na eira de Ornã, o jebuseu, Davi ofereceu sacrifícios ali.

[[v13-21-29]]

^<<v13-21-29,29>>^ Porque naquele tempo o tabernáculo do Senhor , que Moisés havia feito no deserto, e o altar do holocausto estavam no lugar alto de Gibeão.

[[v13-21-30]]

^<<v13-21-30,30>>^ Davi não podia ir até lá para consultar a Deus, porque estava com medo da espada do Anjo do Senhor .

'''

xref:013-1-cronicas/013-1-cronicas-020.adoc#v13-20-0[&#60; Capítulo Anterior] | <<v13-21-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-022.adoc#v13-22-0[Próximo Capítulo &#62;]