include::./index.adoc[]

[[v13-3-0]]
=== 1 Crônicas, 3
// naa ?, NAA - Nova Almeida Atualizada

[[v13-3-1]]

^<<v13-3-1,1>>^ Estes foram os filhos de Davi, que lhe nasceram em Hebrom: o primogênito, Amnom, de Ainoã, a jezreelita; o segundo, Daniel, de Abigail, a carmelita;

[[v13-3-2]]

^<<v13-3-2,2>>^ o terceiro, Absalão, filho de Maaca, filha de Talmai, rei de Gesur; o quarto, Adonias, filho de Hagite;

[[v13-3-3]]

^<<v13-3-3,3>>^ o quinto, Sefatias, de Abital; o sexto, Itreão, de Eglá, sua mulher.

[[v13-3-4]]

^<<v13-3-4,4>>^ Seis filhos lhe nasceram em Hebrom, porque ali reinou sete anos e seis meses; e trinta e três anos ele reinou em Jerusalém.

[[v13-3-5]]

^<<v13-3-5,5>>^ Estes lhe nasceram em Jerusalém: Simeia, Sobabe, Natã e Salomão; estes quatro lhe nasceram de Bate-Seba, filha de Amiel.

[[v13-3-6]]

^<<v13-3-6,6>>^ Nasceram-lhe mais Ibar, Elisama, Elifelete,

[[v13-3-7]]

^<<v13-3-7,7>>^ Nogá, Nefegue, Jafia,

[[v13-3-8]]

^<<v13-3-8,8>>^ Elisama, Eliada e Elifelete, nove ao todo.

[[v13-3-9]]

^<<v13-3-9,9>>^ Todos estes foram filhos de Davi, além dos filhos das concubinas; e Tamar, irmã deles.

[[v13-3-10]]

^<<v13-3-10,10>>^ O filho de Salomão foi Roboão, de quem foi filho Abias, de quem foi filho Asa, de quem foi filho Josafá;

[[v13-3-11]]

^<<v13-3-11,11>>^ de quem foi filho Jeorão, de quem foi filho Acazias, de quem foi filho Joás;

[[v13-3-12]]

^<<v13-3-12,12>>^ de quem foi filho Amazias, de quem foi filho Azarias, de quem foi filho Jotão;

[[v13-3-13]]

^<<v13-3-13,13>>^ de quem foi filho Acaz, de quem foi filho Ezequias, de quem foi filho Manassés;

[[v13-3-14]]

^<<v13-3-14,14>>^ de quem foi filho Amom, de quem foi filho Josias.

[[v13-3-15]]

^<<v13-3-15,15>>^ Os filhos de Josias foram: o primogênito, Joanã; o segundo, Jeoaquim; o terceiro, Zedequias; o quarto, Salum.

[[v13-3-16]]

^<<v13-3-16,16>>^ Os filhos de Jeoaquim foram: Jeconias e Zedequias.

[[v13-3-17]]

^<<v13-3-17,17>>^ Os filhos de Jeconias, o cativo, foram: Sealtiel,

[[v13-3-18]]

^<<v13-3-18,18>>^ Malquirão, Pedaías, Senazar, Jecamias, Hosama e Nedabias.

[[v13-3-19]]

^<<v13-3-19,19>>^ Os filhos de Pedaías foram: Zorobabel e Simei; os filhos de Zorobabel foram: Mesulão e Hananias; e Selomite, irmã deles;

[[v13-3-20]]

^<<v13-3-20,20>>^ e Hasuba, Oel, Berequias, Hasadias e Jusabe-Hesede; cinco ao todo.

[[v13-3-21]]

^<<v13-3-21,21>>^ Os filhos de Hananias foram: Pelatias e Jesaías; os filhos de Refaías, os filhos de Arnã, os filhos de Obadias, os filhos de Secanias.

[[v13-3-22]]

^<<v13-3-22,22>>^ O filho de Secanias foi Semaías; os filhos de Semaías foram: Hatus, Igal, Barias, Nearias e Safate, seis ao todo.

[[v13-3-23]]

^<<v13-3-23,23>>^ Os filhos de Nearias foram: Elioenai, Ezequias e Azricão, três ao todo.

[[v13-3-24]]

^<<v13-3-24,24>>^ Os filhos de Elioenai foram: Hodavias, Eliasibe, Pelaías, Acube, Joanã, Delaías e Anani, sete ao todo.

'''

xref:013-1-cronicas/013-1-cronicas-002.adoc#v13-2-0[&#60; Capítulo Anterior] | <<v13-3-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-004.adoc#v13-4-0[Próximo Capítulo &#62;]