include::./index.adoc[]

[[v13-5-0]]
=== 1 Crônicas, 5
// naa ?, NAA - Nova Almeida Atualizada

[[v13-5-1]]

^<<v13-5-1,1>>^ Quanto aos filhos de Rúben, o primogênito de Israel… Pois Rúben era o primogênito, mas, por ter profanado o leito de seu pai, o seu direito de primogenitura foi dado aos filhos de José, filho de Israel, de modo que, na genealogia, Rúben não foi contado como primogênito.

[[v13-5-2]]

^<<v13-5-2,2>>^ Judá, na verdade, foi poderoso entre seus irmãos, e dele veio o príncipe, mas o direito da primogenitura foi de José.

[[v13-5-3]]

^<<v13-5-3,3>>^ Os filhos de Rúben, o primogênito de Israel, foram estes: Enoque, Palu, Hezrom e Carmi.

[[v13-5-4]]

^<<v13-5-4,4>>^ O filho de Joel foi Semaías, de quem foi filho Gogue, de quem foi filho Simei,

[[v13-5-5]]

^<<v13-5-5,5>>^ de quem foi filho Mica, de quem foi filho Reaías, de quem foi filho Baal,

[[v13-5-6]]

^<<v13-5-6,6>>^ de quem foi filho Beera, o qual Tiglate-Pileser, rei da Assíria, levou cativo; ele foi chefe dos rubenitas.

[[v13-5-7]]

^<<v13-5-7,7>>^ Quanto a seus irmãos, pelas suas famílias, quando foram inscritos nas genealogias segundo as suas descendências, tinham por chefes Jeiel, Zacarias,

[[v13-5-8]]

^<<v13-5-8,8>>^ Bela, filho de Azaz, filho de Sema, filho de Joel, que habitaram em Aroer, até Nebo e Baal-Meom.

[[v13-5-9]]

^<<v13-5-9,9>>^ Também habitaram do lado leste, até a entrada do deserto, o qual se estende até o rio Eufrates, porque o seu gado se tinha multiplicado na terra de Gileade.

[[v13-5-10]]

^<<v13-5-10,10>>^ Nos dias de Saul, fizeram guerra aos hagarenos, que caíram pelo poder de sua mão, e habitaram nas tendas deles, em toda a terra fronteira de Gileade, do lado leste.

[[v13-5-11]]

^<<v13-5-11,11>>^ Os filhos de Gade habitaram em frente deles, na terra de Basã, até Salca.

[[v13-5-12]]

^<<v13-5-12,12>>^ Joel foi o cabeça, e Safã, o segundo; também Janai e Safate estavam em Basã.

[[v13-5-13]]

^<<v13-5-13,13>>^ Seus irmãos, segundo as suas casas paternas, foram: Micael, Mesulão, Seba, Jorai, Jacã, Zia e Héber, sete ao todo;

[[v13-5-14]]

^<<v13-5-14,14>>^ estes foram os filhos de Abiail, filho de Huri, filho de Jaroa, filho de Gileade, filho de Micael, filho de Jesisai, filho de Jado, filho de Buz.

[[v13-5-15]]

^<<v13-5-15,15>>^ Aí, filho de Abdiel, filho de Guni, foi o chefe da sua família.

[[v13-5-16]]

^<<v13-5-16,16>>^ Habitaram em Gileade, em Basã e suas aldeias, bem como até os limites de todos os arredores de Sarom.

[[v13-5-17]]

^<<v13-5-17,17>>^ Todos estes foram inscritos na genealogia, nos dias de Jotão, rei de Judá, e nos dias de Jeroboão, rei de Israel.

[[v13-5-18]]

^<<v13-5-18,18>>^ Dos filhos de Rúben, dos gaditas e da meia tribo de Manassés, homens valentes, que traziam escudo e espada, entesavam o arco e eram treinados para a guerra, houve quarenta e quatro mil setecentos e sessenta, capazes de sair à batalha.

[[v13-5-19]]

^<<v13-5-19,19>>^ Fizeram guerra aos hagarenos, a Jetur, a Nafis e a Nodabe.

[[v13-5-20]]

^<<v13-5-20,20>>^ Foram ajudados contra eles, e os hagarenos e todos os que estavam com eles foram entregues nas suas mãos; porque, na batalha, clamaram a Deus, que lhes deu ouvidos, porque confiaram nele.

[[v13-5-21]]

^<<v13-5-21,21>>^ Levaram o gado dos hagarenos: cinquenta mil camelos, duzentas e cinquenta mil ovelhas, dois mil jumentos; e cem mil pessoas.

[[v13-5-22]]

^<<v13-5-22,22>>^ Porque muitos caíram feridos à espada, pois a batalha era de Deus. E eles habitaram no lugar deles até o exílio.

[[v13-5-23]]

^<<v13-5-23,23>>^ Os filhos da meia tribo de Manassés habitaram naquela terra de Basã até Baal-Hermom, e Senir, e o monte Hermom; e eram numerosos.

[[v13-5-24]]

^<<v13-5-24,24>>^ Estes foram chefes de suas famílias, a saber: Éfer, Isi, Eliel, Azriel, Jeremias, Hodavias e Jadiel, guerreiros valentes, homens famosos, chefes de suas famílias.

[[v13-5-25]]

^<<v13-5-25,25>>^ Porém foram infiéis ao Deus de seus pais e se prostituíram, seguindo os deuses dos povos da terra que Deus tinha destruído diante deles.

[[v13-5-26]]

^<<v13-5-26,26>>^ Por isso o Deus de Israel despertou o espírito de Pul, rei da Assíria, ou seja, o espírito de Tiglate-Pileser, rei da Assíria, que levou cativos os rubenitas, os gaditas e a meia tribo de Manassés, e os fez morar em Hala, Habor e Hara e nas proximidades do rio Gozã, onde permanecem até o dia de hoje.

'''

xref:013-1-cronicas/013-1-cronicas-004.adoc#v13-4-0[&#60; Capítulo Anterior] | <<v13-5-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-006.adoc#v13-6-0[Próximo Capítulo &#62;]