include::./index.adoc[]

[[v13-9-0]]
=== 1 Crônicas, 9
// naa ?, NAA - Nova Almeida Atualizada

[[v13-9-1]]

^<<v13-9-1,1>>^ Todo o Israel foi registrado por genealogias e inscrito no Livro dos Reis de Israel. E Judá foi levado para o exílio à Babilônia, por causa da sua transgressão.

[[v13-9-2]]

^<<v13-9-2,2>>^ Os primeiros habitantes, que de novo vieram morar nas suas propriedades e nas suas cidades, foram os israelitas, os sacerdotes, os levitas e os servidores do templo.

[[v13-9-3]]

^<<v13-9-3,3>>^ Porém alguns dos filhos de Judá, dos filhos de Benjamim e dos filhos de Efraim e Manassés habitaram em Jerusalém:

[[v13-9-4]]

^<<v13-9-4,4>>^ Utai, filho de Amiúde, filho de Onri, filho de Inri, filho de Bani, dos filhos de Perez, filho de Judá;

[[v13-9-5]]

^<<v13-9-5,5>>^ dos silonitas: Asaías, o primogênito, e os seus filhos;

[[v13-9-6]]

^<<v13-9-6,6>>^ dos filhos de Zerá: Jeuel e os seus irmãos, seiscentos e noventa ao todo;

[[v13-9-7]]

^<<v13-9-7,7>>^ dos filhos de Benjamim: Salu, filho de Mesulão, filho de Hodavias, filho de Hassenuá;

[[v13-9-8]]

^<<v13-9-8,8>>^ Ibneias, filho de Jeroão, e Elá, filho de Uzi, filho de Micri, e Mesulão, filho de Sefatias, filho de Reuel, filho de Ibnijas;

[[v13-9-9]]

^<<v13-9-9,9>>^ e os seus irmãos, segundo as suas gerações, novecentos e cinquenta e seis ao todo. Todos estes homens foram chefes de famílias nas casas de suas famílias.

[[v13-9-10]]

^<<v13-9-10,10>>^ Dos sacerdotes: Jedaías, Jeoiaribe, Jaquim,

[[v13-9-11]]

^<<v13-9-11,11>>^ Azarias, filho de Hilquias, filho de Mesulão, filho de Zadoque, filho de Meraiote, filho de Aitube, chefe da Casa de Deus;

[[v13-9-12]]

^<<v13-9-12,12>>^ Adaías, filho de Jeroão, filho de Pasur, filho de Malquias, e Masai, filho de Adiel, filho de Jazera, filho de Mesulão, filho de Mesilemite, filho de Imer,

[[v13-9-13]]

^<<v13-9-13,13>>^ bem como os seus irmãos, chefes das suas famílias; mil setecentos e sessenta ao todo, homens capazes para a obra do ministério da Casa de Deus.

[[v13-9-14]]

^<<v13-9-14,14>>^ Dos levitas: Semaías, filho de Hassube, filho de Azricão, filho de Hasabias, dos filhos de Merari;

[[v13-9-15]]

^<<v13-9-15,15>>^ Baquebacar, Heres, Galal e Matanias, filho de Mica, filho de Zicri, filho de Asafe;

[[v13-9-16]]

^<<v13-9-16,16>>^ Obadias, filho de Semaías, filho de Galal, filho de Jedutum; Berequias, filho de Asa, filho de Elcana, morador das aldeias dos netofatitas.

[[v13-9-17]]

^<<v13-9-17,17>>^ Os porteiros: Salum, Acube, Talmom e Aimã e os irmãos deles; Salum era o chefe.

[[v13-9-18]]

^<<v13-9-18,18>>^ Estavam até agora de guarda à porta do rei, do lado do leste; tais foram os porteiros dos arraiais dos filhos de Levi.

[[v13-9-19]]

^<<v13-9-19,19>>^ Salum, filho de Coré, filho de Ebiasafe, filho de Corá, e seus irmãos da casa de seu pai, os coraítas, estavam encarregados da obra do ministério e eram guardas das portas do tabernáculo; e os seus pais tinham sido encarregados do arraial do Senhor  e eram guardas da entrada.

[[v13-9-20]]

^<<v13-9-20,20>>^ Fineias, filho de Eleazar, os regia nesse tempo, e o Senhor  estava com ele.

[[v13-9-21]]

^<<v13-9-21,21>>^ Zacarias, filho de Meselemias, era o porteiro da entrada da tenda do encontro.

[[v13-9-22]]

^<<v13-9-22,22>>^ Todos estes, escolhidos para guardas das portas, foram duzentos e doze. Estes foram registrados pelas suas genealogias nas suas respectivas aldeias; e Davi e Samuel, o vidente, os constituíram cada um no seu cargo.

[[v13-9-23]]

^<<v13-9-23,23>>^ Eles e os seus filhos guardavam os portões da Casa do Senhor , isto é, na casa da tenda.

[[v13-9-24]]

^<<v13-9-24,24>>^ Os porteiros estavam aos quatro lados: a leste, a oeste, ao norte e ao sul.

[[v13-9-25]]

^<<v13-9-25,25>>^ Seus irmãos, que habitavam nas suas aldeias, tinham de vir, de tempos em tempos, para servir com eles durante sete dias.

[[v13-9-26]]

^<<v13-9-26,26>>^ Porque havia sempre, naquele ofício, quatro porteiros principais, que eram levitas, e tinham a seu encargo as câmaras e os tesouros da Casa de Deus.

[[v13-9-27]]

^<<v13-9-27,27>>^ Estavam alojados ao redor da Casa de Deus, porque estavam encarregados da vigilância, e tinham o dever de abrir os portões todas as manhãs.

[[v13-9-28]]

^<<v13-9-28,28>>^ Alguns deles estavam encarregados dos utensílios usados no culto, porque estes eram contados quando eram trazidos e quando eram tirados.

[[v13-9-29]]

^<<v13-9-29,29>>^ Outros havia que estavam encarregados dos móveis e de todos os objetos do santuário, bem como da melhor farinha, do vinho, do azeite, do incenso e das especiarias.

[[v13-9-30]]

^<<v13-9-30,30>>^ Alguns dos filhos dos sacerdotes confeccionavam as especiarias.

[[v13-9-31]]

^<<v13-9-31,31>>^ Matitias, dentre os levitas, o primogênito de Salum, o coraíta, era o encarregado de fazer os pães para as ofertas.

[[v13-9-32]]

^<<v13-9-32,32>>^ Outros dos seus irmãos, dos filhos dos coatitas, tinham o encargo de preparar os pães da proposição para todos os sábados.

[[v13-9-33]]

^<<v13-9-33,33>>^ Quanto aos cantores, chefes das famílias entre os levitas, ficavam alojados nas câmaras do templo e estavam isentos de outros serviços; porque, dia e noite, estavam ocupados no seu serviço.

[[v13-9-34]]

^<<v13-9-34,34>>^ Estes foram chefes das famílias entre os levitas, chefes em suas gerações, e moravam em Jerusalém.

[[v13-9-35]]

^<<v13-9-35,35>>^ Em Gibeão habitou Jeiel, pai de Gibeão, cuja mulher se chamava Maaca;

[[v13-9-36]]

^<<v13-9-36,36>>^ e também o seu filho primogênito Abdom e ainda Zur, Quis, Baal, Ner, Nadabe,

[[v13-9-37]]

^<<v13-9-37,37>>^ Gedor, Aiô, Zacarias e Miclote.

[[v13-9-38]]

^<<v13-9-38,38>>^ Miclote gerou Simeia. Estes moraram em Jerusalém, perto dos seus irmãos.

[[v13-9-39]]

^<<v13-9-39,39>>^ Ner gerou Quis, e Quis gerou Saul. Saul gerou Jônatas, Malquisua, Abinadabe e Esbaal.

[[v13-9-40]]

^<<v13-9-40,40>>^ Filho de Jônatas foi Meribe-Baal, e Meribe-Baal gerou Mica.

[[v13-9-41]]

^<<v13-9-41,41>>^ Os filhos de Mica foram: Pitom, Meleque e Tareia.

[[v13-9-42]]

^<<v13-9-42,42>>^ Acaz gerou Jaerá, e Jaerá gerou Alemete, Azmavete e Zinri; e Zinri gerou Mosa.

[[v13-9-43]]

^<<v13-9-43,43>>^ Mosa gerou Bineá, de quem foi filho Refaías, de quem foi filho Eleasa, de quem foi filho Azel.

[[v13-9-44]]

^<<v13-9-44,44>>^ Azel teve seis filhos, cujos nomes foram Azricão, Bocru, Ismael, Searias, Obadias e Hanã; todos estes foram filhos de Azel.

'''

xref:013-1-cronicas/013-1-cronicas-008.adoc#v13-8-0[&#60; Capítulo Anterior] | <<v13-9-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-010.adoc#v13-10-0[Próximo Capítulo &#62;]