include::./index.adoc[]

[[v13-23-0]]
=== 1 Crônicas, 23
// naa ?, NAA - Nova Almeida Atualizada

[[v13-23-1]]

^<<v13-23-1,1>>^ Quando já era bem velho, Davi constituiu o seu filho Salomão rei sobre Israel.

[[v13-23-2]]

^<<v13-23-2,2>>^ Davi reuniu todos os chefes de Israel, bem como os sacerdotes e levitas.

[[v13-23-3]]

^<<v13-23-3,3>>^ Foram contados os levitas de trinta anos para cima, e seu número, contados um por um, foi de trinta e oito mil homens.

[[v13-23-4]]

^<<v13-23-4,4>>^ Destes, havia vinte e quatro mil para supervisionarem a obra da Casa do Senhor , seis mil oficiais e juízes,

[[v13-23-5]]

^<<v13-23-5,5>>^ quatro mil porteiros e quatro mil para louvarem o Senhor  com os instrumentos que Davi fez para esse fim.

[[v13-23-6]]

^<<v13-23-6,6>>^ Davi os repartiu por turnos, segundo os filhos de Levi: Gérson, Coate e Merari.

[[v13-23-7]]

^<<v13-23-7,7>>^ Os filhos de Gérson foram: Ladã e Simei.

[[v13-23-8]]

^<<v13-23-8,8>>^ Os filhos de Ladã foram: Jeiel, o chefe, Zetã e Joel, três ao todo.

[[v13-23-9]]

^<<v13-23-9,9>>^ Os filhos de Simei foram: Selomite, Haziel e Harã, três ao todo. Estes foram os chefes das famílias de Ladã.

[[v13-23-10]]

^<<v13-23-10,10>>^ Os filhos de Simei foram: Jaate, Ziza, Jeús e Berias. Estes foram os filhos de Simei, quatro ao todo.

[[v13-23-11]]

^<<v13-23-11,11>>^ Jaate era o chefe e Ziza era o segundo. Jeús e Berias não tiveram muitos filhos e por isso estes dois foram contados como uma só família.

[[v13-23-12]]

^<<v13-23-12,12>>^ Os filhos de Coate foram: Anrão, Isar, Hebrom e Uziel, quatro ao todo.

[[v13-23-13]]

^<<v13-23-13,13>>^ Os filhos de Anrão foram: Arão e Moisés. Arão foi separado para servir no Santo dos Santos, ele e os seus filhos, para sempre, e para queimar incenso diante do Senhor , para o servir e para dar a bênção em seu nome, para sempre.

[[v13-23-14]]

^<<v13-23-14,14>>^ Quanto a Moisés, homem de Deus, seus filhos foram contados entre a tribo de Levi.

[[v13-23-15]]

^<<v13-23-15,15>>^ Os filhos de Moisés foram: Gérson e Eliézer.

[[v13-23-16]]

^<<v13-23-16,16>>^ O filho de Gérson foi Sebuel, o chefe.

[[v13-23-17]]

^<<v13-23-17,17>>^ O filho de Eliézer foi Reabias, o chefe; e ele não teve outros filhos; mas os filhos de Reabias se multiplicaram grandemente.

[[v13-23-18]]

^<<v13-23-18,18>>^ Os filhos de Isar foram: Selomite, o chefe.

[[v13-23-19]]

^<<v13-23-19,19>>^ Os filhos de Hebrom foram: Jerias, o chefe, Amarias, o segundo, Jaaziel, o terceiro, e Jecameão, o quarto.

[[v13-23-20]]

^<<v13-23-20,20>>^ Os filhos de Uziel foram: Mica, o chefe, e Issias, o segundo.

[[v13-23-21]]

^<<v13-23-21,21>>^ Os filhos de Merari foram: Mali e Musi. Os filhos de Mali foram: Eleazar e Quis.

[[v13-23-22]]

^<<v13-23-22,22>>^ Eleazar morreu e não teve filhos, porém filhas; e os filhos de Quis, seus parentes, casaram com elas.

[[v13-23-23]]

^<<v13-23-23,23>>^ Os filhos de Musi foram: Mali, Éder e Jerimote, três ao todo.

[[v13-23-24]]

^<<v13-23-24,24>>^ Estes foram os filhos de Levi, segundo as suas famílias e chefes delas, segundo foram contados nominalmente, um por um, de vinte anos para cima, encarregados do ministério da Casa do Senhor .

[[v13-23-25]]

^<<v13-23-25,25>>^ Porque Davi disse: — O Senhor , Deus de Israel, deu paz ao seu povo e habitará em Jerusalém para sempre.

[[v13-23-26]]

^<<v13-23-26,26>>^ Assim, os levitas já não precisarão levar o tabernáculo e nenhum dos utensílios para o seu ministério.

[[v13-23-27]]

^<<v13-23-27,27>>^ Porque, segundo as últimas palavras de Davi, foram contados os filhos de Levi de vinte anos para cima.

[[v13-23-28]]

^<<v13-23-28,28>>^ O serviço deles era ajudar os filhos de Arão no ministério da Casa do Senhor , nos átrios e nas câmaras, na purificação de todas as coisas sagradas e na obra do ministério da Casa de Deus,

[[v13-23-29]]

^<<v13-23-29,29>>^ a saber, cuidar dos pães da proposição, da melhor farinha para a oferta de cereais, dos bolos sem fermento, das ofertas assadas e das misturadas com azeite, bem como dos pesos e das medidas.

[[v13-23-30]]

^<<v13-23-30,30>>^ Deviam estar presentes todas as manhãs e todas as tardes para darem graças ao Senhor  e o louvarem,

[[v13-23-31]]

^<<v13-23-31,31>>^ e sempre que fossem oferecidos os holocaustos do Senhor , nos sábados, nas Festas da Lua Nova e nas festas fixas, diante do Senhor , segundo o número determinado.

[[v13-23-32]]

^<<v13-23-32,32>>^ Os filhos de Levi deviam cuidar da tenda do encontro e do santuário e deviam ajudar os filhos de Arão, seus irmãos, no ministério da Casa do Senhor .

'''

xref:013-1-cronicas/013-1-cronicas-022.adoc#v13-22-0[&#60; Capítulo Anterior] | <<v13-23-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-024.adoc#v13-24-0[Próximo Capítulo &#62;]