include::./index.adoc[]

[[v13-29-0]]
=== 1 Crônicas, 29
// naa ?, NAA - Nova Almeida Atualizada

[[v13-29-1]]

^<<v13-29-1,1>>^ O rei Davi disse a toda a congregação: — Salomão, meu filho, o único a quem Deus escolheu, ainda é moço e inexperiente, e esta obra é grande, porque o palácio não é para homens, mas para o Senhor  Deus.

[[v13-29-2]]

^<<v13-29-2,2>>^ Portanto, com todas as minhas forças já preparei para o templo de meu Deus ouro para as obras de ouro, prata para as de prata, bronze para as de bronze, ferro para as de ferro e madeira para as de madeira; pedras de ônix, pedras de engaste, pedras de várias cores, de mosaicos e todo tipo de pedras preciosas, e mármore, e tudo em abundância.

[[v13-29-3]]

^<<v13-29-3,3>>^ E ainda, porque amo o templo de meu Deus, o ouro e a prata particulares que tenho dou para o templo de meu Deus, além de tudo o que preparei para o santuário:

[[v13-29-4]]

^<<v13-29-4,4>>^ cem toneladas de ouro, do ouro de Ofir, e duzentas e quarenta toneladas de prata purificada, para cobrir as paredes das casas;

[[v13-29-5]]

^<<v13-29-5,5>>^ ouro para os objetos de ouro e prata para os de prata, e para toda obra de mão dos artífices. Quem, pois, está disposto hoje a ofertar com generosidade para o Senhor ?

[[v13-29-6]]

^<<v13-29-6,6>>^ Então os chefes das famílias, os chefes das tribos de Israel, os capitães de mil e os de cem e até os administradores da obra do rei fizeram ofertas voluntárias

[[v13-29-7]]

^<<v13-29-7,7>>^ e deram para o serviço da Casa de Deus cento e setenta toneladas de ouro, dez mil barras de ouro, trezentas e quarenta toneladas de prata, seiscentas e doze toneladas de bronze e três mil e quatrocentas toneladas de ferro.

[[v13-29-8]]

^<<v13-29-8,8>>^ Os que possuíam pedras preciosas as trouxeram para o tesouro da Casa do Senhor , a cargo de Jeiel, o gersonita.

[[v13-29-9]]

^<<v13-29-9,9>>^ O povo se alegrou com tudo o que se fez voluntariamente, porque de coração íntegro fizeram ofertas voluntárias ao Senhor . Também o rei Davi se alegrou com grande júbilo.

[[v13-29-10]]

^<<v13-29-10,10>>^ Davi louvou o Senhor  diante de toda a congregação e disse: — Bendito és tu, Senhor , Deus de Israel, nosso pai, de eternidade a eternidade.

[[v13-29-11]]

^<<v13-29-11,11>>^ Teu, Senhor , é o poder, a grandeza, a honra, a vitória e a majestade, porque teu é tudo o que há nos céus e na terra. Teu, Senhor , é o reino, e tu te exaltaste como chefe sobre todos.

[[v13-29-12]]

^<<v13-29-12,12>>^ Riquezas e glória vêm de ti. Tu dominas sobre tudo, e na tua mão há força e poder. Contigo está o engrandecer e dar força a todos.

[[v13-29-13]]

^<<v13-29-13,13>>^ Agora, ó nosso Deus, graças te damos e louvamos o teu glorioso nome.

[[v13-29-14]]

^<<v13-29-14,14>>^ Porque quem sou eu, e quem é o meu povo para que pudéssemos dar voluntariamente estas coisas? Porque tudo vem de ti, e nós só damos o que vem das tuas mãos.

[[v13-29-15]]

^<<v13-29-15,15>>^ Porque somos estrangeiros diante de ti e peregrinos como todos os nossos pais. Os nossos dias sobre a terra são como a sombra, e não temos permanência.

[[v13-29-16]]

^<<v13-29-16,16>>^ Senhor , nosso Deus, toda esta abundância que preparamos para edificar um templo ao teu santo nome vem da tua mão e é toda tua.

[[v13-29-17]]

^<<v13-29-17,17>>^ Bem sei, meu Deus, que tu provas os corações e que te agradas da sinceridade. Eu também, na sinceridade de meu coração, dei voluntariamente todas estas coisas, e acabo de ver com alegria que o teu povo aqui reunido te faz ofertas voluntariamente.

[[v13-29-18]]

^<<v13-29-18,18>>^ Senhor , Deus de nossos pais Abraão, Isaque e Israel, conserva para sempre no coração do teu povo estas disposições e pensamentos; firma o coração deles em ti.

[[v13-29-19]]

^<<v13-29-19,19>>^ E ao meu filho Salomão dá coração íntegro para guardar os teus mandamentos, os teus testemunhos e os teus estatutos, fazendo tudo para edificar este palácio para o qual fiz todos estes preparativos.

[[v13-29-20]]

^<<v13-29-20,20>>^ Então Davi disse a toda a congregação: — Agora, louvem o Senhor , seu Deus. Então toda a congregação louvou o Senhor , Deus de seus pais. Todos inclinaram a cabeça, adoraram o Senhor  e se prostraram diante do rei.

[[v13-29-21]]

^<<v13-29-21,21>>^ No dia seguinte, trouxeram sacrifícios ao Senhor  e lhe ofereceram holocaustos de mil bezerros, mil carneiros, mil cordeiros, com as suas libações; sacrifícios em abundância por todo o Israel.

[[v13-29-22]]

^<<v13-29-22,22>>^ Comeram e beberam, naquele dia, diante do Senhor , com grande alegria. Pela segunda vez, fizeram rei a Salomão, filho de Davi, e o ungiram ao Senhor  por príncipe e a Zadoque, por sacerdote.

[[v13-29-23]]

^<<v13-29-23,23>>^ Salomão assentou-se no trono do Senhor  como rei em lugar de Davi, seu pai. Ele prosperou, e todo o Israel lhe obedecia.

[[v13-29-24]]

^<<v13-29-24,24>>^ Todos os oficiais, os soldados, e até todos os filhos do rei Davi prestaram homenagens ao rei Salomão.

[[v13-29-25]]

^<<v13-29-25,25>>^ O Senhor  engrandeceu muito Salomão diante de todo o Israel e lhe deu majestade real, qual antes dele não teve nenhum rei em Israel.

[[v13-29-26]]

^<<v13-29-26,26>>^ Assim, Davi, filho de Jessé, reinou sobre todo o Israel.

[[v13-29-27]]

^<<v13-29-27,27>>^ Ele reinou sobre Israel durante quarenta anos: sete anos em Hebrom e trinta e três em Jerusalém.

[[v13-29-28]]

^<<v13-29-28,28>>^ Morreu em boa velhice, cheio de dias, riquezas e glória; e Salomão, seu filho, reinou em seu lugar.

[[v13-29-29]]

^<<v13-29-29,29>>^ Os atos do rei Davi, tanto os primeiros como os últimos, estão escritos nas crônicas de Samuel, o vidente, nas crônicas de Natã, o profeta, e nas crônicas de Gade, o vidente.

[[v13-29-30]]

^<<v13-29-30,30>>^ Ali também está registrado o que se passou no seu reinado e se fala a respeito do seu poder e de todos os acontecimentos que se deram com ele, com Israel e com todos os reinos daquelas terras.

'''

xref:013-1-cronicas/013-1-cronicas-028.adoc#v13-28-0[&#60; Capítulo Anterior] | <<v13-29-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-001.adoc#v14-1-0[Próximo Capítulo &#62;]