include::./index.adoc[]

[[v13-15-0]]
=== 1 Crônicas, 15
// naa ?, NAA - Nova Almeida Atualizada

[[v13-15-1]]

^<<v13-15-1,1>>^ Davi fez também casas para si mesmo, na Cidade de Davi, e preparou um lugar para a arca de Deus e lhe armou uma tenda.

[[v13-15-2]]

^<<v13-15-2,2>>^ Então ele disse: — Ninguém pode levar a arca de Deus, a não ser os levitas, porque o Senhor  os escolheu para levarem a arca do Senhor  e o servirem para sempre.

[[v13-15-3]]

^<<v13-15-3,3>>^ Davi reuniu todo o Israel em Jerusalém, para trazer a arca do Senhor  para o lugar que ele havia preparado para ela.

[[v13-15-4]]

^<<v13-15-4,4>>^ Davi reuniu os filhos de Arão e os levitas.

[[v13-15-5]]

^<<v13-15-5,5>>^ Dos filhos de Coate veio Uriel, o chefe, e seus irmãos, cento e vinte;

[[v13-15-6]]

^<<v13-15-6,6>>^ dos filhos de Merari veio Asaías, o chefe, e seus irmãos, duzentos e vinte;

[[v13-15-7]]

^<<v13-15-7,7>>^ dos filhos de Gérson veio Joel, o chefe, e seus irmãos, cento e trinta;

[[v13-15-8]]

^<<v13-15-8,8>>^ dos filhos de Elisafã veio Semaías, o chefe, e seus irmãos, duzentos;

[[v13-15-9]]

^<<v13-15-9,9>>^ dos filhos de Hebrom veio Eliel, o chefe, e seus irmãos, oitenta;

[[v13-15-10]]

^<<v13-15-10,10>>^ dos filhos de Uziel veio Aminadabe, o chefe, e seus irmãos, cento e doze.

[[v13-15-11]]

^<<v13-15-11,11>>^ Davi chamou os sacerdotes Zadoque e Abiatar e os levitas Uriel, Asaías, Joel, Semaías, Eliel e Aminadabe

[[v13-15-12]]

^<<v13-15-12,12>>^ e lhes disse: — Vocês são os chefes das famílias dos levitas. Santifiquem a si mesmos e aos seus irmãos, para que possam trazer a arca do Senhor , Deus de Israel, ao lugar que preparei para ela.

[[v13-15-13]]

^<<v13-15-13,13>>^ Pois, visto que vocês não a carregaram na primeira vez, o Senhor , nosso Deus, irrompeu contra nós, porque não o buscamos, segundo nos tinha sido ordenado.

[[v13-15-14]]

^<<v13-15-14,14>>^ Então os sacerdotes e os levitas se santificaram, para trazer a arca do Senhor , Deus de Israel.

[[v13-15-15]]

^<<v13-15-15,15>>^ Os filhos dos levitas trouxeram a arca de Deus sobre os ombros pelos cabos, como Moisés havia ordenado, segundo a palavra do Senhor .

[[v13-15-16]]

^<<v13-15-16,16>>^ Davi ordenou aos chefes dos levitas que constituíssem os seus irmãos, os cantores, para que, acompanhados por instrumentos musicais, liras, harpas e címbalos, se fizessem ouvir, levantando a voz com alegria.

[[v13-15-17]]

^<<v13-15-17,17>>^ Assim, os levitas designaram Hemã, filho de Joel; e dos irmãos dele, Asafe, filho de Berequias; e dos filhos de Merari, irmãos deles, Etã, filho de Cusaías.

[[v13-15-18]]

^<<v13-15-18,18>>^ E com eles os seus irmãos da segunda ordem: Zacarias, Bene, Jaaziel, Semiramote, Jeiel, Uni, Eliabe, Benaia, Maaseias, Matitias, Elifeleu e Micneias e os porteiros Obede-Edom e Jeiel.

[[v13-15-19]]

^<<v13-15-19,19>>^ Assim, os cantores Hemã, Asafe e Etã se faziam ouvir com címbalos de bronze;

[[v13-15-20]]

^<<v13-15-20,20>>^ Zacarias, Aziel, Semiramote, Jeiel, Uni, Eliabe, Maaseias e Benaia, com liras, em voz de soprano;

[[v13-15-21]]

^<<v13-15-21,21>>^ Matitias, Elifeleu, Micneias, Obede-Edom, Jeiel e Azazias, com harpas, em voz de baixo, para conduzir o canto.

[[v13-15-22]]

^<<v13-15-22,22>>^ Quenanias, chefe dos levitas músicos, tinha o encargo de dirigir o canto, porque era perito nisso.

[[v13-15-23]]

^<<v13-15-23,23>>^ Berequias e Elcana eram porteiros da arca.

[[v13-15-24]]

^<<v13-15-24,24>>^ Sebanias, Josafá, Natanael, Amasai, Zacarias, Benaia e Eliézer, os sacerdotes, tocavam as trombetas diante da arca de Deus; Obede-Edom e Jeías eram porteiros da arca.

[[v13-15-25]]

^<<v13-15-25,25>>^ Davi, os anciãos de Israel e os capitães de milhares foram, com alegria, buscar a arca da aliança do Senhor  na casa de Obede-Edom.

[[v13-15-26]]

^<<v13-15-26,26>>^ E visto que Deus ajudou os levitas que levavam a arca da aliança do Senhor , ofereceram em sacrifício sete novilhos e sete carneiros.

[[v13-15-27]]

^<<v13-15-27,27>>^ Davi estava vestido com um manto de linho fino, bem como todos os levitas que levavam a arca, os cantores e Quenanias, chefe dos que levavam a arca e dos cantores; Davi vestia também uma estola sacerdotal de linho.

[[v13-15-28]]

^<<v13-15-28,28>>^ Assim, todo o Israel levou a arca da aliança do Senhor , com júbilo e ao som de clarins, trombetas e címbalos, fazendo ressoar harpas e liras.

[[v13-15-29]]

^<<v13-15-29,29>>^ Quando a arca da aliança do Senhor  estava entrando na Cidade de Davi, Mical, filha de Saul, olhou pela janela. E, ao ver o rei Davi dançando e se alegrando, ela o desprezou em seu coração.

'''

xref:013-1-cronicas/013-1-cronicas-014.adoc#v13-14-0[&#60; Capítulo Anterior] | <<v13-15-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-016.adoc#v13-16-0[Próximo Capítulo &#62;]