include::./index.adoc[]

[[v13-17-0]]
=== 1 Crônicas, 17
// naa ?, NAA - Nova Almeida Atualizada

[[v13-17-1]]

^<<v13-17-1,1>>^ E aconteceu que, quando Davi já morava em seu palácio, ele disse ao profeta Natã: — Eis que eu estou morando num palácio feito de cedro, mas a arca da aliança do Senhor  se encontra numa tenda.

[[v13-17-2]]

^<<v13-17-2,2>>^ Então Natã disse a Davi: — Faça tudo o que estiver em seu coração, porque Deus está com você.

[[v13-17-3]]

^<<v13-17-3,3>>^ Porém, naquela mesma noite, a palavra de Deus veio a Natã, dizendo:

[[v13-17-4]]

^<<v13-17-4,4>>^ — Vá e diga a Davi, meu servo: Assim diz o Senhor : "Não será você quem edificará um templo para minha habitação.

[[v13-17-5]]

^<<v13-17-5,5>>^ Desde o dia em que tirei Israel do Egito até o dia de hoje, não habitei em nenhum templo, mas tenho andado de tenda em tenda, de tabernáculo em tabernáculo.

[[v13-17-6]]

^<<v13-17-6,6>>^ Em todos os lugares em que andei com todo o Israel, por acaso falei alguma palavra com algum dos seus juízes, a quem mandei apascentar o meu povo, dizendo: ‘Por que vocês não construíram um templo de cedro para mim?’"

[[v13-17-7]]

^<<v13-17-7,7>>^ Agora diga ao meu servo Davi: Assim diz o Senhor  dos Exércitos: "Eu tirei você das pastagens e do trabalho de andar atrás das ovelhas, para que você fosse príncipe sobre o meu povo de Israel.

[[v13-17-8]]

^<<v13-17-8,8>>^ Estive com você por onde quer que você andou e eliminei todos os seus inimigos diante de você. Engrandecerei o seu nome, como só os grandes têm na terra.

[[v13-17-9]]

^<<v13-17-9,9>>^ Prepararei um lugar para o meu povo de Israel e o plantarei para que habite no seu lugar e não seja mais perturbado. E jamais os filhos da perversidade o afligirão, como no passado,

[[v13-17-10]]

^<<v13-17-10,10>>^ desde os dias em que mandei que houvesse juízes sobre o meu povo de Israel. Subjugarei todos os seus inimigos. Também lhe faço saber que o Senhor  fará uma casa para você.

[[v13-17-11]]

^<<v13-17-11,11>>^ Quando se cumprirem os seus dias e você for para junto de seus pais, então farei surgir depois de você o seu descendente, um dos seus filhos, e estabelecerei o seu reino.

[[v13-17-12]]

^<<v13-17-12,12>>^ Este edificará um templo para mim, e eu estabelecerei para sempre o seu trono.

[[v13-17-13]]

^<<v13-17-13,13>>^ Eu lhe serei por pai, e ele me será por filho. Não tirarei dele a minha misericórdia, como a retirei daquele que foi rei antes de você.

[[v13-17-14]]

^<<v13-17-14,14>>^ Mas eu o confirmarei na minha casa e no meu reino para sempre, e o seu trono será estabelecido para sempre."

[[v13-17-15]]

^<<v13-17-15,15>>^ Segundo todas estas palavras e conforme toda esta visão, assim Natã falou com Davi.

[[v13-17-16]]

^<<v13-17-16,16>>^ Então o rei Davi se pôs diante do Senhor  e disse: — Quem sou eu, Senhor  Deus, e qual é a minha casa, para que me tenhas trazido até aqui?

[[v13-17-17]]

^<<v13-17-17,17>>^ E como se isto fosse pouco aos teus olhos, ó Deus, também falaste a respeito da casa de teu servo para tempos distantes e me trataste como se eu fosse um homem ilustre, ó Senhor  Deus.

[[v13-17-18]]

^<<v13-17-18,18>>^ Que mais ainda te poderá dizer Davi a respeito das honras feitas a teu servo? Pois tu conheces bem o teu servo.

[[v13-17-19]]

^<<v13-17-19,19>>^ Ó Senhor , por amor de teu servo e segundo o teu coração, fizeste toda esta grandeza, para tornar conhecidas todas estas grandes coisas!

[[v13-17-20]]

^<<v13-17-20,20>>^ — Senhor , não há ninguém semelhante a ti, e não há outro Deus além de ti, segundo tudo o que nós mesmos temos ouvido.

[[v13-17-21]]

^<<v13-17-21,21>>^ Quem há como o teu povo de Israel, gente única na terra, a quem Deus foi resgatar para ser o seu povo, fazendo para ti mesmo um nome com estas grandes e tremendas coisas, desterrando as nações de diante do teu povo, que resgataste do Egito?

[[v13-17-22]]

^<<v13-17-22,22>>^ Estabeleceste o teu povo de Israel por teu povo para sempre e tu, ó Senhor , te fizeste o seu Deus.

[[v13-17-23]]

^<<v13-17-23,23>>^ — E agora, Senhor , quanto a esta palavra que disseste a respeito de teu servo e a respeito da sua casa, seja estabelecida para sempre; e faze como falaste.

[[v13-17-24]]

^<<v13-17-24,24>>^ Seja estabelecido e para sempre engrandecido o teu nome, e que se diga: "O Senhor  dos Exércitos, o Deus de Israel, é Deus para Israel." E a casa de Davi, teu servo, será estabelecida diante de ti.

[[v13-17-25]]

^<<v13-17-25,25>>^ Pois tu, Deus meu, fizeste ao teu servo a revelação de que lhe edificarias uma casa. Por isso, o teu servo se animou para fazer-te esta oração.

[[v13-17-26]]

^<<v13-17-26,26>>^ Agora, pois, ó Senhor , tu mesmo és Deus e tens prometido ao teu servo este bem.

[[v13-17-27]]

^<<v13-17-27,27>>^ Queiras, agora, abençoar a casa do teu servo, a fim de permanecer para sempre diante de ti, pois tu, ó Senhor , a abençoaste, e ela será abençoada para sempre.

'''

xref:013-1-cronicas/013-1-cronicas-016.adoc#v13-16-0[&#60; Capítulo Anterior] | <<v13-17-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-018.adoc#v13-18-0[Próximo Capítulo &#62;]