include::./index.adoc[]

[[v13-18-0]]
=== 1 Crônicas, 18
// naa ?, NAA - Nova Almeida Atualizada

[[v13-18-1]]

^<<v13-18-1,1>>^ Depois disso, Davi atacou os filisteus, derrotou-os e tomou Gate e as suas aldeias das mãos dos filisteus.

[[v13-18-2]]

^<<v13-18-2,2>>^ Também derrotou os moabitas, que se tornaram servos de Davi e lhe pagavam tributo.

[[v13-18-3]]

^<<v13-18-3,3>>^ Davi também derrotou Hadadezer, rei de Zobá, nas imediações de Hamate, quando aquele foi restabelecer o seu domínio sobre o rio Eufrates.

[[v13-18-4]]

^<<v13-18-4,4>>^ Davi tomou-lhe mil carros de guerra, sete mil cavaleiros e vinte mil soldados de infantaria. Mutilou todos os cavalos dos carros de guerra, com exceção dos que puxavam cem deles.

[[v13-18-5]]

^<<v13-18-5,5>>^ Os sírios de Damasco foram socorrer Hadadezer, rei de Zobá, mas Davi matou vinte e dois mil deles.

[[v13-18-6]]

^<<v13-18-6,6>>^ Davi pôs guarnições na Síria de Damasco, e os sírios se tornaram servos de Davi e lhe pagavam tributo. E o Senhor  dava vitórias a Davi por onde quer que ele ia.

[[v13-18-7]]

^<<v13-18-7,7>>^ Davi tomou os escudos de ouro que eram usados pelos oficiais de Hadadezer e os trouxe a Jerusalém.

[[v13-18-8]]

^<<v13-18-8,8>>^ Também de Tibate e de Cum, cidades de Hadadezer, Davi tomou grande quantidade de bronze, de que Salomão fez o mar de bronze, as colunas e os utensílios de bronze.

[[v13-18-9]]

^<<v13-18-9,9>>^ Quando Toú, rei de Hamate, soube que Davi tinha derrotado todo o exército de Hadadezer, rei de Zobá,

[[v13-18-10]]

^<<v13-18-10,10>>^ mandou seu filho Hadorão ao rei Davi, para o saudar e cumprimentá-lo por ter lutado contra Hadadezer e por havê-lo vencido. Acontece que Hadadezer de contínuo fazia guerra a Toú. Hadorão trouxe consigo objetos de ouro, de prata e de bronze,

[[v13-18-11]]

^<<v13-18-11,11>>^ que o rei Davi consagrou ao Senhor , juntamente com a prata e o ouro que havia trazido de todas as demais nações: de Edom, de Moabe, dos filhos de Amom, dos filisteus e de Amaleque.

[[v13-18-12]]

^<<v13-18-12,12>>^ Também Abisai, filho de Zeruia, matou dezoito mil edomitas no vale do Sal.

[[v13-18-13]]

^<<v13-18-13,13>>^ Pôs guarnições em Edom, e todos os edomitas se tornaram servos de Davi. E o Senhor  dava vitórias a Davi por onde quer que ele ia.

[[v13-18-14]]

^<<v13-18-14,14>>^ Davi reinou sobre todo o Israel; julgava e fazia justiça a todo o seu povo.

[[v13-18-15]]

^<<v13-18-15,15>>^ Joabe, filho de Zeruia, era comandante do exército; Josafá, filho de Ailude, era cronista.

[[v13-18-16]]

^<<v13-18-16,16>>^ Zadoque, filho de Aitube, e Abimeleque, filho de Abiatar, eram sacerdotes; e Sausa era o escrivão.

[[v13-18-17]]

^<<v13-18-17,17>>^ Benaia, filho de Joiada, era o comandante da guarda real. Os filhos de Davi, porém, eram os primeiros ao lado do rei.

'''

xref:013-1-cronicas/013-1-cronicas-017.adoc#v13-17-0[&#60; Capítulo Anterior] | <<v13-18-0,Topo>> | xref:013-1-cronicas/013-1-cronicas-019.adoc#v13-19-0[Próximo Capítulo &#62;]