include::./index.adoc[]

[[v59-5-0]]
=== Tiago, 5
// naa ?, NAA - Nova Almeida Atualizada

[[v59-5-1]]

^<<v59-5-1,1>>^ Escutem, agora, ricos! Chorem e lamentem, por causa das desgraças que virão sobre vocês.

[[v59-5-2]]

^<<v59-5-2,2>>^ As suas riquezas apodreceram, e as suas roupas foram comidas pelas traças.

[[v59-5-3]]

^<<v59-5-3,3>>^ O seu ouro e a sua prata estão enferrujados, e essa ferrugem será testemunha contra vocês e há de devorar, como fogo, o corpo de vocês. Nestes tempos do fim, vocês ajuntaram tesouros.

[[v59-5-4]]

^<<v59-5-4,4>>^ Eis que o salário dos trabalhadores que fizeram a colheita nos campos de vocês e que foi retido com fraude está clamando; e o clamor dos que fizeram a colheita chegou aos ouvidos do Senhor dos Exércitos.

[[v59-5-5]]

^<<v59-5-5,5>>^ Vocês têm tido uma vida de luxo e de prazeres sobre a terra; têm engordado em dia de matança.

[[v59-5-6]]

^<<v59-5-6,6>>^ Vocês têm condenado e matado o justo, sem que ele ofereça resistência.

[[v59-5-7]]

^<<v59-5-7,7>>^ Portanto, irmãos, sejam pacientes até a vinda do Senhor. Eis que o lavrador aguarda com paciência o precioso fruto da terra, até receber as primeiras e as últimas chuvas.

[[v59-5-8]]

^<<v59-5-8,8>>^ Sejam também vocês pacientes e fortaleçam o seu coração, pois a vinda do Senhor está próxima.

[[v59-5-9]]

^<<v59-5-9,9>>^ Irmãos, não se queixem uns dos outros, para que vocês não sejam julgados. Eis que o juiz está às portas.

[[v59-5-10]]

^<<v59-5-10,10>>^ Irmãos, tomem como exemplo de sofrimento e de paciência os profetas, que falaram em nome do Senhor.

[[v59-5-11]]

^<<v59-5-11,11>>^ Eis que consideramos felizes os que foram perseverantes. Vocês ouviram a respeito da paciência de Jó e sabem como o Senhor fez com que tudo acabasse bem; porque o Senhor é cheio de misericórdia e compaixão.

[[v59-5-12]]

^<<v59-5-12,12>>^ Acima de tudo, meus irmãos, não jurem nem pelo céu, nem pela terra, nem por outra coisa qualquer, mas que o "sim" de vocês seja "sim", e que o "não" de vocês seja "não", para que vocês não incorram em condenação.

[[v59-5-13]]

^<<v59-5-13,13>>^ Alguém de vocês está sofrendo? Faça oração. Alguém está alegre? Cante louvores.

[[v59-5-14]]

^<<v59-5-14,14>>^ Alguém de vocês está doente? Chame os presbíteros da igreja, e estes façam oração sobre ele, ungindo-o com óleo, em nome do Senhor.

[[v59-5-15]]

^<<v59-5-15,15>>^ E a oração da fé salvará o enfermo, e o Senhor o levantará. E, se houver cometido pecados, estes lhe serão perdoados.

[[v59-5-16]]

^<<v59-5-16,16>>^ Portanto, confessem os seus pecados uns aos outros e orem uns pelos outros, para que vocês sejam curados. Muito pode, por sua eficácia, a súplica do justo.

[[v59-5-17]]

^<<v59-5-17,17>>^ Elias era homem semelhante a nós, sujeito aos mesmos sentimentos, e orou com fervor para que não chovesse sobre a terra, e, por três anos e seis meses, não choveu.

[[v59-5-18]]

^<<v59-5-18,18>>^ Depois, orou de novo, e então o céu deu chuva, e a terra produziu os seus frutos.

[[v59-5-19]]

^<<v59-5-19,19>>^ Meus irmãos, se alguém entre vocês se desviar da verdade, e alguém o converter,

[[v59-5-20]]

^<<v59-5-20,20>>^ saibam que aquele que converte o pecador do seu caminho errado salvará da morte a alma dele e cobrirá uma multidão de pecados.

'''

xref:059-tiago/059-tiago-004.adoc#v59-4-0[&#60; Capítulo Anterior] | <<v59-5-0,Topo>> | xref:060-1-pedro/060-1-pedro-001.adoc#v60-1-0[Próximo Capítulo &#62;]