include::./index.adoc[]

[[v59-1-0]]
=== Tiago, 1
// naa ?, NAA - Nova Almeida Atualizada

[[v59-1-1]]

^<<v59-1-1,1>>^ Tiago, servo de Deus e do Senhor Jesus Cristo, às doze tribos que se encontram na Diáspora. Saudações.

[[v59-1-2]]

^<<v59-1-2,2>>^ Meus irmãos, tenham por motivo de grande alegria o fato de passarem por várias provações,

[[v59-1-3]]

^<<v59-1-3,3>>^ sabendo que a provação da fé que vocês têm produz perseverança.

[[v59-1-4]]

^<<v59-1-4,4>>^ Ora, a perseverança deve ter ação completa, para que vocês sejam perfeitos e íntegros, sem que lhes falte nada.

[[v59-1-5]]

^<<v59-1-5,5>>^ Se, porém, algum de vocês necessita de sabedoria, peça a Deus, que a todos dá com generosidade e sem reprovações, e ela lhe será concedida.

[[v59-1-6]]

^<<v59-1-6,6>>^ Peça-a, porém, com fé, em nada duvidando, pois o que duvida é semelhante à onda do mar, impelida e agitada pelo vento.

[[v59-1-7]]

^<<v59-1-7,7>>^ Que uma pessoa dessas não pense que alcançará do Senhor alguma coisa,

[[v59-1-8]]

^<<v59-1-8,8>>^ sendo indecisa e inconstante em todos os seus caminhos.

[[v59-1-9]]

^<<v59-1-9,9>>^ O irmão de condição humilde glorie-se na sua exaltação,

[[v59-1-10]]

^<<v59-1-10,10>>^ e o rico, na sua humilhação, porque ele passará como a flor do campo.

[[v59-1-11]]

^<<v59-1-11,11>>^ Porque o sol se levanta com seu calor ardente, a planta seca, a sua flor cai e a formosura do seu aspecto desaparece. Assim também o rico murchará em seus caminhos.

[[v59-1-12]]

^<<v59-1-12,12>>^ Bem-aventurado é aquele que suporta com perseverança a provação. Porque, depois de ter sido aprovado, receberá a coroa da vida, a qual o Senhor prometeu aos que o amam.

[[v59-1-13]]

^<<v59-1-13,13>>^ Ninguém, ao ser tentado, diga: "Sou tentado por Deus." Porque Deus não pode ser tentado pelo mal e ele mesmo não tenta ninguém.

[[v59-1-14]]

^<<v59-1-14,14>>^ Ao contrário, cada um é tentado pela sua própria cobiça, quando esta o atrai e seduz.

[[v59-1-15]]

^<<v59-1-15,15>>^ Então a cobiça, depois de haver concebido, dá à luz o pecado; e o pecado, uma vez consumado, gera a morte.

[[v59-1-16]]

^<<v59-1-16,16>>^ Não se enganem, meus amados irmãos.

[[v59-1-17]]

^<<v59-1-17,17>>^ Toda boa dádiva e todo dom perfeito vêm lá do alto, descendo do Pai das luzes, em quem não pode existir variação ou sombra de mudança.

[[v59-1-18]]

^<<v59-1-18,18>>^ Pois, segundo o seu querer, ele nos gerou pela palavra da verdade, para que fôssemos como que primícias das suas criaturas.

[[v59-1-19]]

^<<v59-1-19,19>>^ Vocês sabem estas coisas, meus amados irmãos. Cada um esteja pronto para ouvir, mas seja tardio para falar e tardio para ficar irado.

[[v59-1-20]]

^<<v59-1-20,20>>^ Porque a ira humana não produz a justiça de Deus.

[[v59-1-21]]

^<<v59-1-21,21>>^ Portanto, deixando toda impureza e acúmulo de maldade, acolham com mansidão a palavra implantada em vocês, a qual é poderosa para salvá-los.

[[v59-1-22]]

^<<v59-1-22,22>>^ Sejam praticantes da palavra e não somente ouvintes, enganando a vocês mesmos.

[[v59-1-23]]

^<<v59-1-23,23>>^ Porque, se alguém é ouvinte da palavra e não praticante, assemelha-se àquele que contempla o seu rosto natural num espelho;

[[v59-1-24]]

^<<v59-1-24,24>>^ pois contempla a si mesmo, se retira e logo esquece como era a sua aparência.

[[v59-1-25]]

^<<v59-1-25,25>>^ Mas aquele que atenta bem para a lei perfeita, lei da liberdade, e nela persevera, não sendo ouvinte que logo se esquece, mas operoso praticante, esse será bem-aventurado no que realizar.

[[v59-1-26]]

^<<v59-1-26,26>>^ Se alguém supõe ser religioso, mas não refreia a sua língua, está enganando a si mesmo; a sua religião é vã.

[[v59-1-27]]

^<<v59-1-27,27>>^ A religião pura e sem mácula para com o nosso Deus e Pai é esta: visitar os órfãos e as viúvas nas suas aflições e guardar-se incontaminado do mundo.

'''

xref:058-hebreus/058-hebreus-013.adoc#v58-13-0[&#60; Capítulo Anterior] | <<v59-1-0,Topo>> | xref:059-tiago/059-tiago-002.adoc#v59-2-0[Próximo Capítulo &#62;]