include::./index.adoc[]

[[v59-3-0]]
=== Tiago, 3
// naa ?, NAA - Nova Almeida Atualizada

[[v59-3-1]]

^<<v59-3-1,1>>^ Meus irmãos, não sejam, muitos de vocês, mestres, sabendo que seremos julgados com mais rigor.

[[v59-3-2]]

^<<v59-3-2,2>>^ Porque todos tropeçamos em muitas coisas. Se alguém não tropeça no falar, é um indivíduo perfeito, capaz de refrear também todo o corpo.

[[v59-3-3]]

^<<v59-3-3,3>>^ Ora, se colocamos um freio na boca dos cavalos, para que nos obedeçam, também lhes dirigimos o corpo inteiro.

[[v59-3-4]]

^<<v59-3-4,4>>^ Observem, igualmente, os navios que, sendo tão grandes e impelidos por fortes ventos, são dirigidos por um pequeníssimo leme, e levados para onde o piloto quer.

[[v59-3-5]]

^<<v59-3-5,5>>^ Assim, também a língua, pequeno órgão, se gaba de grandes coisas. Vejam como uma fagulha incendeia uma grande floresta!

[[v59-3-6]]

^<<v59-3-6,6>>^ Ora, a língua é um fogo; é um mundo de maldade. A língua está situada entre os membros do nosso corpo e contamina o corpo inteiro, e não só põe em chamas toda a carreira da existência humana, como também ela mesma é posta em chamas pelo inferno.

[[v59-3-7]]

^<<v59-3-7,7>>^ Pois toda espécie de animais, de aves, de répteis e de seres marinhos se doma e tem sido domada pelo gênero humano,

[[v59-3-8]]

^<<v59-3-8,8>>^ mas a língua ninguém é capaz de domar; é mal incontido, cheio de veneno mortal.

[[v59-3-9]]

^<<v59-3-9,9>>^ Com ela, bendizemos o Senhor e Pai; também, com ela, amaldiçoamos as pessoas, criadas à semelhança de Deus.

[[v59-3-10]]

^<<v59-3-10,10>>^ De uma só boca procede bênção e maldição. Meus irmãos, isso não deveria ser assim.

[[v59-3-11]]

^<<v59-3-11,11>>^ Por acaso pode a fonte jorrar do mesmo lugar água doce e água amarga?

[[v59-3-12]]

^<<v59-3-12,12>>^ Meus irmãos, será que a figueira pode produzir azeitonas ou a videira, figos? Assim, também, uma fonte de água salgada não pode dar água doce.

[[v59-3-13]]

^<<v59-3-13,13>>^ Quem entre vocês é sábio e inteligente? Mostre as suas obras em mansidão de sabedoria, mediante a sua boa conduta.

[[v59-3-14]]

^<<v59-3-14,14>>^ Se, pelo contrário, vocês têm em seu coração inveja amargurada e sentimento de rivalidade, não se gloriem disso, nem mintam contra a verdade.

[[v59-3-15]]

^<<v59-3-15,15>>^ Esta não é a sabedoria que desce lá do alto; pelo contrário, é terrena, animal e demoníaca.

[[v59-3-16]]

^<<v59-3-16,16>>^ Pois, onde há inveja e rivalidade, aí há confusão e toda espécie de coisas ruins.

[[v59-3-17]]

^<<v59-3-17,17>>^ Mas a sabedoria lá do alto é, primeiramente, pura; depois, pacífica, gentil, amigável, cheia de misericórdia e de bons frutos, imparcial, sem fingimento.

[[v59-3-18]]

^<<v59-3-18,18>>^ Ora, é em paz que se semeia o fruto da justiça, para os que promovem a paz.

'''

xref:059-tiago/059-tiago-002.adoc#v59-2-0[&#60; Capítulo Anterior] | <<v59-3-0,Topo>> | xref:059-tiago/059-tiago-004.adoc#v59-4-0[Próximo Capítulo &#62;]