include::./index.adoc[]

[[v59-4-0]]
=== Tiago, 4
// naa ?, NAA - Nova Almeida Atualizada

[[v59-4-1]]

^<<v59-4-1,1>>^ De onde procedem as guerras e brigas que há entre vocês? De onde, senão dos prazeres que estão em conflito dentro de vocês?

[[v59-4-2]]

^<<v59-4-2,2>>^ Vocês cobiçam e nada têm; matam e sentem inveja, mas nada podem obter; vivem a lutar e a fazer guerras. Nada têm, porque não pedem;

[[v59-4-3]]

^<<v59-4-3,3>>^ pedem e não recebem, porque pedem mal, para esbanjarem em seus prazeres.

[[v59-4-4]]

^<<v59-4-4,4>>^ Gente infiel! Vocês não sabem que a amizade do mundo é inimizade contra Deus? Aquele, pois, que quiser ser amigo do mundo se torna inimigo de Deus.

[[v59-4-5]]

^<<v59-4-5,5>>^ Ou vocês pensam que é em vão que a Escritura diz: "É com ciúme que por nós anseia o Espírito, que ele fez habitar em nós?"

[[v59-4-6]]

^<<v59-4-6,6>>^ Mas ele nos dá cada vez mais graça. Por isso diz: "Deus resiste aos soberbos, mas dá graça aos humildes."

[[v59-4-7]]

^<<v59-4-7,7>>^ Portanto, sujeitem-se a Deus, mas resistam ao diabo, e ele fugirá de vocês.

[[v59-4-8]]

^<<v59-4-8,8>>^ Cheguem perto de Deus, e ele se chegará a vocês. Limpem as mãos, pecadores! E vocês que são indecisos, purifiquem o coração.

[[v59-4-9]]

^<<v59-4-9,9>>^ Reconheçam a sua miséria, lamentem e chorem. Que o riso de vocês se transforme em pranto, e que a alegria de vocês se transforme em tristeza.

[[v59-4-10]]

^<<v59-4-10,10>>^ Humilhem-se diante do Senhor, e ele os exaltará.

[[v59-4-11]]

^<<v59-4-11,11>>^ Irmãos, não falem mal uns dos outros. Aquele que fala mal do irmão ou julga o seu irmão fala mal da lei e julga a lei; ora, se você julga a lei, não é observador da lei, mas juiz.

[[v59-4-12]]

^<<v59-4-12,12>>^ Um só é Legislador e Juiz, aquele que pode salvar e fazer perecer. Mas quem é você para julgar o seu próximo?

[[v59-4-13]]

^<<v59-4-13,13>>^ Escutem, agora, vocês que dizem: "Hoje ou amanhã, iremos para a cidade tal, e lá passaremos um ano, e faremos negócios, e teremos lucros."

[[v59-4-14]]

^<<v59-4-14,14>>^ Vocês não sabem o que acontecerá amanhã. O que é a vida de vocês? Vocês não passam de neblina que aparece por um instante e logo se dissipa.

[[v59-4-15]]

^<<v59-4-15,15>>^ Em vez disso, deveriam dizer: "Se Deus quiser, não só viveremos, como também faremos isto ou aquilo."

[[v59-4-16]]

^<<v59-4-16,16>>^ Agora, entretanto, vocês se orgulham das suas arrogantes pretensões. Todo orgulho semelhante a esse é mau.

[[v59-4-17]]

^<<v59-4-17,17>>^ Portanto, aquele que sabe que deve fazer o bem e não o faz, nisso está pecando.

'''

xref:059-tiago/059-tiago-003.adoc#v59-3-0[&#60; Capítulo Anterior] | <<v59-4-0,Topo>> | xref:059-tiago/059-tiago-005.adoc#v59-5-0[Próximo Capítulo &#62;]