include::./index.adoc[]

[[v56-2-0]]
=== Tito, 2
// naa ?, NAA - Nova Almeida Atualizada

[[v56-2-1]]

^<<v56-2-1,1>>^ Mas você ensine o que está de acordo com a sã doutrina.

[[v56-2-2]]

^<<v56-2-2,2>>^ Quanto aos homens idosos, que sejam moderados, respeitáveis, sensatos, sadios na fé, no amor e na perseverança.

[[v56-2-3]]

^<<v56-2-3,3>>^ Do mesmo modo, quanto às mulheres idosas, que tenham conduta reverente, não sejam caluniadoras, nem escravizadas a muito vinho. Que sejam mestras do bem,

[[v56-2-4]]

^<<v56-2-4,4>>^ a fim de instruírem as jovens recém-casadas a amar o marido e os filhos,

[[v56-2-5]]

^<<v56-2-5,5>>^ a serem sensatas, puras, boas donas de casa, bondosas, sujeitas ao marido, para que a palavra de Deus não seja difamada.

[[v56-2-6]]

^<<v56-2-6,6>>^ Do mesmo modo, quanto aos mais jovens, exorte-os para que, em todas as coisas, sejam moderados.

[[v56-2-7]]

^<<v56-2-7,7>>^ Seja você mesmo um exemplo de boas obras. No ensino, mostre integridade, reverência,

[[v56-2-8]]

^<<v56-2-8,8>>^ linguagem sadia e irrepreensível, para que o adversário seja envergonhado, não tendo nada de mau a dizer a nosso respeito.

[[v56-2-9]]

^<<v56-2-9,9>>^ Quanto aos servos, que sejam, em tudo, obedientes ao seu senhor, dando-lhe motivo de satisfação. Que não sejam respondões,

[[v56-2-10]]

^<<v56-2-10,10>>^ nem furtem, mas que deem prova de toda a fidelidade, a fim de que, em todas as coisas, manifestem a beleza da doutrina de Deus, nosso Salvador.

[[v56-2-11]]

^<<v56-2-11,11>>^ Porque a graça de Deus se manifestou, trazendo salvação a todos.

[[v56-2-12]]

^<<v56-2-12,12>>^ Ela nos educa para que, renegadas a impiedade e as paixões mundanas, vivamos neste mundo de forma sensata, justa e piedosa,

[[v56-2-13]]

^<<v56-2-13,13>>^ aguardando a bendita esperança e a manifestação da glória do nosso grande Deus e Salvador Jesus Cristo.

[[v56-2-14]]

^<<v56-2-14,14>>^ Ele deu a si mesmo por nós, a fim de nos remir de toda iniquidade e purificar, para si mesmo, um povo exclusivamente seu, dedicado à prática de boas obras.

[[v56-2-15]]

^<<v56-2-15,15>>^ Ensine estas coisas. Também exorte e repreenda com toda a autoridade. Que ninguém despreze você.

'''

xref:056-tito/056-tito-001.adoc#v56-1-0[&#60; Capítulo Anterior] | <<v56-2-0,Topo>> | xref:056-tito/056-tito-003.adoc#v56-3-0[Próximo Capítulo &#62;]