include::./index.adoc[]

[[v56-3-0]]
=== Tito, 3
// naa ?, NAA - Nova Almeida Atualizada

[[v56-3-1]]

^<<v56-3-1,1>>^ Lembre a todos que se sujeitem aos governantes e às autoridades, que sejam obedientes e estejam prontos para toda boa obra.

[[v56-3-2]]

^<<v56-3-2,2>>^ Que não difamem ninguém. Que sejam pacíficos, cordiais, dando provas de toda cortesia para com todos.

[[v56-3-3]]

^<<v56-3-3,3>>^ Pois nós também, no passado, éramos insensatos, desobedientes, desgarrados, escravos de todo tipo de paixões e prazeres, vivendo em maldade e inveja, sendo odiados e odiando-nos uns aos outros.

[[v56-3-4]]

^<<v56-3-4,4>>^ Mas quando se manifestou a bondade de Deus, nosso Salvador, e o seu amor por todos,

[[v56-3-5]]

^<<v56-3-5,5>>^ ele nos salvou, não por obras de justiça praticadas por nós, mas segundo a sua misericórdia. Ele nos salvou mediante o lavar regenerador e renovador do Espírito Santo,

[[v56-3-6]]

^<<v56-3-6,6>>^ que ele derramou sobre nós ricamente, por meio de Jesus Cristo, nosso Salvador,

[[v56-3-7]]

^<<v56-3-7,7>>^ a fim de que, justificados por graça, nos tornemos seus herdeiros, segundo a esperança da vida eterna.

[[v56-3-8]]

^<<v56-3-8,8>>^ Fiel é esta palavra, e quero que você fale ousadamente a respeito dessas coisas, para que os que creem em Deus se empenhem na prática de boas obras. Estas coisas são excelentes e proveitosas para todas as pessoas.

[[v56-3-9]]

^<<v56-3-9,9>>^ Evite discussões tolas, genealogias, controvérsias e debates sobre a lei; porque são inúteis e sem valor.

[[v56-3-10]]

^<<v56-3-10,10>>^ Evite a pessoa que provoca divisões, depois de admoestá-la uma ou duas vezes,

[[v56-3-11]]

^<<v56-3-11,11>>^ pois você sabe que tal pessoa está pervertida, vive pecando e por si mesma está condenada.

[[v56-3-12]]

^<<v56-3-12,12>>^ Quando eu lhe enviar Ártemas ou Tíquico, faça o possível para vir ao meu encontro em Nicópolis. Estou resolvido a passar o inverno ali.

[[v56-3-13]]

^<<v56-3-13,13>>^ Ajude, da melhor maneira possível, Zenas, o intérprete da lei, e também Apolo, para que não lhes falte nada para a viagem.

[[v56-3-14]]

^<<v56-3-14,14>>^ E, quanto aos nossos, que aprendam também a se empenhar na prática de boas obras a favor dos necessitados, para não se tornarem infrutíferos.

[[v56-3-15]]

^<<v56-3-15,15>>^ Todos os que estão comigo mandam saudações a você. Dê saudações àqueles que nos amam na fé. A graça esteja com todos vocês.

'''

xref:056-tito/056-tito-002.adoc#v56-2-0[&#60; Capítulo Anterior] | <<v56-3-0,Topo>> | xref:057-filemom/057-filemom-001.adoc#v57-1-0[Próximo Capítulo &#62;]