include::./index.adoc[]

[[v56-1-0]]
=== Tito, 1
// naa ?, NAA - Nova Almeida Atualizada

[[v56-1-1]]

^<<v56-1-1,1>>^ Paulo, servo de Deus e apóstolo de Jesus Cristo, para promover a fé que é dos eleitos de Deus e o pleno conhecimento da verdade segundo a piedade.

[[v56-1-2]]

^<<v56-1-2,2>>^ Escrevo na esperança da vida eterna que o Deus que não pode mentir prometeu antes dos tempos eternos

[[v56-1-3]]

^<<v56-1-3,3>>^ e, no momento oportuno, manifestou a sua palavra mediante a pregação que me foi confiada por ordem de Deus, nosso Salvador,

[[v56-1-4]]

^<<v56-1-4,4>>^ a Tito, verdadeiro filho, segundo a fé comum. Que a graça e a paz, da parte de Deus Pai e de Cristo Jesus, nosso Salvador, estejam com você.

[[v56-1-5]]

^<<v56-1-5,5>>^ Foi por esta causa que deixei você em Creta: para que pusesse em ordem as coisas restantes, bem como, em cada cidade, constituísse presbíteros, conforme prescrevi a você:

[[v56-1-6]]

^<<v56-1-6,6>>^ alguém que seja irrepreensível, marido de uma só mulher, que tenha filhos crentes que não são acusados de devassidão, nem são insubordinados.

[[v56-1-7]]

^<<v56-1-7,7>>^ Porque é indispensável que o bispo, por ser encarregado das coisas de Deus, seja irrepreensível, não arrogante, alguém que não se irrita facilmente, não apegado ao vinho, não violento, nem ganancioso.

[[v56-1-8]]

^<<v56-1-8,8>>^ Pelo contrário, o bispo deve ser hospitaleiro, amigo do bem, sensato, justo, piedoso, deve ter domínio de si,

[[v56-1-9]]

^<<v56-1-9,9>>^ ser apegado à palavra fiel, que está de acordo com a doutrina, para que possa exortar pelo reto ensino e convencer os que contradizem este ensino.

[[v56-1-10]]

^<<v56-1-10,10>>^ Porque existem muitos, especialmente os da circuncisão, que são insubordinados, falam coisas sem sentido e enganam os outros.

[[v56-1-11]]

^<<v56-1-11,11>>^ É preciso fazer com que se calem, porque andam pervertendo casas inteiras, ensinando o que não devem, com a intenção vergonhosa de ganhar dinheiro.

[[v56-1-12]]

^<<v56-1-12,12>>^ Foi um dos cretenses, um próprio profeta deles, que disse: "Os cretenses são sempre mentirosos, feras terríveis, comilões preguiçosos."

[[v56-1-13]]

^<<v56-1-13,13>>^ Este testemunho é verdadeiro. Portanto, repreenda-os severamente, para que sejam sadios na fé

[[v56-1-14]]

^<<v56-1-14,14>>^ e não se ocupem com fábulas judaicas, nem com mandamentos de gente que se desvia da verdade.

[[v56-1-15]]

^<<v56-1-15,15>>^ Todas as coisas são puras para os puros; mas, para os impuros e descrentes, nada é puro. Porque tanto a mente como a consciência deles estão corrompidas.

[[v56-1-16]]

^<<v56-1-16,16>>^ Afirmam que conhecem a Deus, mas o negam por meio do que fazem; é por isso que são abomináveis, desobedientes e reprovados para qualquer boa obra.

'''

xref:055-2-timoteo/055-2-timoteo-004.adoc#v55-4-0[&#60; Capítulo Anterior] | <<v56-1-0,Topo>> | xref:056-tito/056-tito-002.adoc#v56-2-0[Próximo Capítulo &#62;]