include::./index.adoc[]

[[v62-3-0]]
=== 1 João, 3
// naa ?, NAA - Nova Almeida Atualizada

[[v62-3-1]]

^<<v62-3-1,1>>^ Vejam que grande amor o Pai nos tem concedido, a ponto de sermos chamados filhos de Deus; e, de fato, somos filhos de Deus. Por essa razão, o mundo não nos conhece, porque não o conheceu.

[[v62-3-2]]

^<<v62-3-2,2>>^ Amados, agora somos filhos de Deus, mas ainda não se manifestou o que haveremos de ser. Sabemos que, quando ele se manifestar, seremos semelhantes a ele, porque haveremos de vê-lo como ele é.

[[v62-3-3]]

^<<v62-3-3,3>>^ E todo o que tem essa esperança nele purifica a si mesmo, assim como ele é puro.

[[v62-3-4]]

^<<v62-3-4,4>>^ Todo aquele que pratica o pecado também transgride a lei, porque o pecado é a transgressão da lei.

[[v62-3-5]]

^<<v62-3-5,5>>^ E vocês sabem que ele se manifestou para tirar os pecados, e nele não existe pecado.

[[v62-3-6]]

^<<v62-3-6,6>>^ Todo aquele que permanece nele não vive pecando; todo aquele que vive pecando não o viu, nem o conheceu.

[[v62-3-7]]

^<<v62-3-7,7>>^ Filhinhos, não se deixem enganar por ninguém. Aquele que pratica a justiça é justo, assim como ele é justo.

[[v62-3-8]]

^<<v62-3-8,8>>^ Aquele que pratica o pecado procede do diabo, porque o diabo vive pecando desde o princípio. Para isto se manifestou o Filho de Deus: para destruir as obras do diabo.

[[v62-3-9]]

^<<v62-3-9,9>>^ Todo aquele que é nascido de Deus não vive na prática de pecado, porque nele permanece a semente divina; esse não pode viver pecando, porque é nascido de Deus.

[[v62-3-10]]

^<<v62-3-10,10>>^ Nisto são manifestos os filhos de Deus e os filhos do diabo: todo aquele que não pratica a justiça não procede de Deus, e o mesmo vale para aquele que não ama o seu irmão.

[[v62-3-11]]

^<<v62-3-11,11>>^ Porque a mensagem que vocês ouviram desde o princípio é esta: que nos amemos uns aos outros.

[[v62-3-12]]

^<<v62-3-12,12>>^ Não sejamos como Caim, que era do Maligno e matou o seu irmão. E por que o matou? Porque as suas obras eram más, e as de seu irmão eram justas.

[[v62-3-13]]

^<<v62-3-13,13>>^ Irmãos, não se admirem se o mundo odeia vocês.

[[v62-3-14]]

^<<v62-3-14,14>>^ Nós sabemos que já passamos da morte para a vida, porque amamos os irmãos. Quem não ama permanece na morte.

[[v62-3-15]]

^<<v62-3-15,15>>^ Todo aquele que odeia o seu irmão é assassino, e vocês sabem que todo assassino não tem a vida eterna permanente em si.

[[v62-3-16]]

^<<v62-3-16,16>>^ Nisto conhecemos o amor: que Cristo deu a sua vida por nós; portanto, também nós devemos dar a nossa vida pelos irmãos.

[[v62-3-17]]

^<<v62-3-17,17>>^ Ora, se alguém possui recursos deste mundo e vê seu irmão passar necessidade, mas fecha o coração para essa pessoa, como pode permanecer nele o amor de Deus?

[[v62-3-18]]

^<<v62-3-18,18>>^ Filhinhos, não amemos de palavra, nem da boca para fora, mas de fato e de verdade.

[[v62-3-19]]

^<<v62-3-19,19>>^ E nisto conheceremos que somos da verdade, bem como, diante dele, tranquilizaremos o nosso coração.

[[v62-3-20]]

^<<v62-3-20,20>>^ Pois, se o nosso coração nos acusar, Deus é maior do que o nosso coração e conhece todas as coisas.

[[v62-3-21]]

^<<v62-3-21,21>>^ Amados, se o coração não nos acusar, temos confiança diante de Deus;

[[v62-3-22]]

^<<v62-3-22,22>>^ e aquilo que pedimos dele recebemos, porque guardamos os seus mandamentos e fazemos diante dele o que lhe é agradável.

[[v62-3-23]]

^<<v62-3-23,23>>^ E o seu mandamento é este: que creiamos no nome de seu Filho, Jesus Cristo, e nos amemos uns aos outros, segundo o mandamento que nos ordenou.

[[v62-3-24]]

^<<v62-3-24,24>>^ Quem guarda os seus mandamentos permanece em Deus, e Deus permanece nele. E nisto conhecemos que ele permanece em nós, pelo Espírito que nos deu.

'''

xref:062-1-joao/062-1-joao-002.adoc#v62-2-0[&#60; Capítulo Anterior] | <<v62-3-0,Topo>> | xref:062-1-joao/062-1-joao-004.adoc#v62-4-0[Próximo Capítulo &#62;]