include::./index.adoc[]

[[v62-5-0]]
=== 1 João, 5
// naa ?, NAA - Nova Almeida Atualizada

[[v62-5-1]]

^<<v62-5-1,1>>^ Todo aquele que crê que Jesus é o Cristo é nascido de Deus, e quem ama aquele que o gerou ama também o que dele é nascido.

[[v62-5-2]]

^<<v62-5-2,2>>^ Nisto sabemos que amamos os filhos de Deus: quando amamos a Deus e praticamos os seus mandamentos.

[[v62-5-3]]

^<<v62-5-3,3>>^ Porque este é o amor de Deus: que guardemos os seus mandamentos. E os seus mandamentos não são difíceis de guardar.

[[v62-5-4]]

^<<v62-5-4,4>>^ Porque todo o que é nascido de Deus vence o mundo. E esta é a vitória que vence o mundo: a nossa fé.

[[v62-5-5]]

^<<v62-5-5,5>>^ Quem é o que vence o mundo, senão aquele que crê que Jesus é o Filho de Deus?

[[v62-5-6]]

^<<v62-5-6,6>>^ Este é aquele que veio por meio de água e sangue, Jesus Cristo. Ele não veio somente com a água, mas com a água e com o sangue. E o Espírito é o que dá testemunho, porque o Espírito é a verdade.

[[v62-5-7]]

^<<v62-5-7,7>>^ Pois há três que dão testemunho:

[[v62-5-8]]

^<<v62-5-8,8>>^ o Espírito, a água e o sangue, e os três são unânimes num só propósito.

[[v62-5-9]]

^<<v62-5-9,9>>^ Se aceitamos o testemunho dos homens, o testemunho de Deus é maior. E este é o testemunho de Deus, que ele dá a respeito do seu Filho.

[[v62-5-10]]

^<<v62-5-10,10>>^ Aquele que crê no Filho de Deus tem, nele, esse testemunho. Aquele que não dá crédito a Deus faz de Deus um mentiroso, porque não crê no testemunho que Deus dá a respeito do seu Filho.

[[v62-5-11]]

^<<v62-5-11,11>>^ E o testemunho é este: que Deus nos deu a vida eterna, e esta vida está no seu Filho.

[[v62-5-12]]

^<<v62-5-12,12>>^ Quem tem o Filho tem a vida; quem não tem o Filho de Deus não tem a vida.

[[v62-5-13]]

^<<v62-5-13,13>>^ Estas coisas escrevi a vocês que creem no nome do Filho de Deus para que saibam que têm a vida eterna.

[[v62-5-14]]

^<<v62-5-14,14>>^ E esta é a confiança que temos para com ele: que, se pedirmos alguma coisa segundo a sua vontade, ele nos ouve.

[[v62-5-15]]

^<<v62-5-15,15>>^ E, se sabemos que ele nos ouve quanto ao que lhe pedimos, estamos certos de que obtemos os pedidos que lhe temos feito.

[[v62-5-16]]

^<<v62-5-16,16>>^ Se alguém vê o seu irmão cometer pecado que não leva à morte, pedirá, e Deus dará vida a esse irmão. Isso aos que cometem pecados que não levam à morte. Há pecado que leva à morte, e por esse não digo que se deva pedir.

[[v62-5-17]]

^<<v62-5-17,17>>^ Toda injustiça é pecado, e há pecado que não leva à morte.

[[v62-5-18]]

^<<v62-5-18,18>>^ Sabemos que todo aquele que é nascido de Deus não vive em pecado, porque quem é nascido de Deus guarda a si mesmo, e o Maligno não pode tocar nele.

[[v62-5-19]]

^<<v62-5-19,19>>^ Sabemos que somos de Deus e que o mundo inteiro jaz no Maligno.

[[v62-5-20]]

^<<v62-5-20,20>>^ Também sabemos que o Filho de Deus já veio e nos tem dado entendimento para reconhecermos aquele que é o Verdadeiro. E nós estamos naquele que é o Verdadeiro, em seu Filho, Jesus Cristo. Este é o verdadeiro Deus e a vida eterna.

[[v62-5-21]]

^<<v62-5-21,21>>^ Filhinhos, cuidado com os ídolos!

'''

xref:062-1-joao/062-1-joao-004.adoc#v62-4-0[&#60; Capítulo Anterior] | <<v62-5-0,Topo>> | xref:063-2-joao/063-2-joao-001.adoc#v63-1-0[Próximo Capítulo &#62;]