include::./index.adoc[]

[[v62-1-0]]
=== 1 João, 1
// naa ?, NAA - Nova Almeida Atualizada

[[v62-1-1]]

^<<v62-1-1,1>>^ O que era desde o princípio, o que ouvimos, o que vimos com os nossos próprios olhos, o que contemplamos e as nossas mãos apalparam, a respeito do Verbo da vida

[[v62-1-2]]

^<<v62-1-2,2>>^ — e a vida se manifestou, e nós a vimos e dela damos testemunho, e anunciamos a vocês a vida eterna, que estava com o Pai e nos foi manifestada —,

[[v62-1-3]]

^<<v62-1-3,3>>^ o que vimos e ouvimos anunciamos também a vocês, para que também vocês tenham comunhão conosco. Ora, a nossa comunhão é com o Pai e com o seu Filho, Jesus Cristo.

[[v62-1-4]]

^<<v62-1-4,4>>^ E escrevemos estas coisas para que a nossa alegria seja completa.

[[v62-1-5]]

^<<v62-1-5,5>>^ A mensagem que dele ouvimos e que anunciamos a vocês é esta: Deus é luz, e não há nele treva nenhuma.

[[v62-1-6]]

^<<v62-1-6,6>>^ Se dissermos que mantemos comunhão com ele e andarmos nas trevas, mentimos e não praticamos a verdade.

[[v62-1-7]]

^<<v62-1-7,7>>^ Se andarmos na luz, como ele está na luz, mantemos comunhão uns com os outros, e o sangue de Jesus, seu Filho, nos purifica de todo pecado.

[[v62-1-8]]

^<<v62-1-8,8>>^ Se dissermos que não temos pecado nenhum, a nós mesmos enganamos, e a verdade não está em nós.

[[v62-1-9]]

^<<v62-1-9,9>>^ Se confessarmos os nossos pecados, ele é fiel e justo para nos perdoar os pecados e nos purificar de toda injustiça.

[[v62-1-10]]

^<<v62-1-10,10>>^ Se dissermos que não cometemos pecado, fazemos dele um mentiroso, e a sua palavra não está em nós.

'''

xref:061-2-pedro/061-2-pedro-003.adoc#v61-3-0[&#60; Capítulo Anterior] | <<v62-1-0,Topo>> | xref:062-1-joao/062-1-joao-002.adoc#v62-2-0[Próximo Capítulo &#62;]