include::./index.adoc[]

[[v16-5-0]]
=== Neemias, 5
// naa ?, NAA - Nova Almeida Atualizada

[[v16-5-1]]

^<<v16-5-1,1>>^ Então se levantou grande clamor do povo e de suas mulheres contra os judeus, seus irmãos.

[[v16-5-2]]

^<<v16-5-2,2>>^ Porque havia os que diziam: — Somos muitos, nós, os nossos filhos e as nossas filhas. Precisamos conseguir trigo, para que possamos comer e continuar vivos.

[[v16-5-3]]

^<<v16-5-3,3>>^ Também houve os que diziam: — Nós tivemos de hipotecar as nossas terras, as nossas vinhas e as nossas casas, para conseguirmos trigo em meio a esta fome.

[[v16-5-4]]

^<<v16-5-4,4>>^ Houve ainda os que diziam: — Pegamos dinheiro emprestado até para pagar ao rei o tributo sobre as nossas terras e as nossas vinhas.

[[v16-5-5]]

^<<v16-5-5,5>>^ Nós somos da mesma carne que os nossos compatriotas, e os nossos filhos são tão bons como os deles. No entanto, eis que sujeitamos os nossos filhos e as nossas filhas para serem escravos. Algumas de nossas filhas já estão reduzidas à escravidão. Não podemos fazer nada para evitar isso, pois os nossos campos e as nossas vinhas já são de outros.

[[v16-5-6]]

^<<v16-5-6,6>>^ Fiquei muito irritado ao ouvir estas palavras e o clamor deles.

[[v16-5-7]]

^<<v16-5-7,7>>^ Depois de ter pensado bem a respeito disso, repreendi os nobres e magistrados e lhes disse: — Vocês são exploradores, cada um para com o seu irmão! E convoquei uma grande assembleia contra eles.

[[v16-5-8]]

^<<v16-5-8,8>>^ Disse-lhes: — Nós, de acordo com as nossas posses, resgatamos os judeus, nossos compatriotas, que foram vendidos aos gentios. E agora vocês estão querendo vender os seus compatriotas, para que tenhamos de comprá-los outra vez? Então eles se calaram e não acharam o que responder.

[[v16-5-9]]

^<<v16-5-9,9>>^ Disse mais: — Não é bom o que vocês estão fazendo. Não é fato que vocês deviam andar no temor do nosso Deus, para evitar a vergonha diante de nossos inimigos, os gentios?

[[v16-5-10]]

^<<v16-5-10,10>>^ Também eu, os meus companheiros e os meus servos lhes demos dinheiro emprestado e trigo. Mas, por favor, vamos parar com esta exploração.

[[v16-5-11]]

^<<v16-5-11,11>>^ Peço que hoje mesmo vocês lhes restituam as suas terras, as suas vinhas, os seus olivais e as suas casas, bem como a porcentagem do dinheiro, do trigo, do vinho e do azeite, que vocês exigiram deles.

[[v16-5-12]]

^<<v16-5-12,12>>^ Eles responderam: — Vamos restituir e nada pediremos deles. Faremos o que você está dizendo. Então chamei os sacerdotes e, na presença destes, fiz com que jurassem que fariam o que prometeram.

[[v16-5-13]]

^<<v16-5-13,13>>^ Também sacudi o meu manto e disse: — Que Deus faça o mesmo, sacudindo para fora de sua casa e de seu trabalho todo aquele que não cumprir esta promessa! Que assim seja sacudido e despojado. E toda a congregação respondeu: — Amém! E louvaram o Senhor . E o povo fez segundo a sua promessa.

[[v16-5-14]]

^<<v16-5-14,14>>^ Também desde o dia em que fui nomeado governador na terra de Judá, desde o vigésimo ano até o trigésimo segundo ano do reinado de Artaxerxes, doze anos, nem eu nem os meus companheiros comemos o pão que me cabia como governador.

[[v16-5-15]]

^<<v16-5-15,15>>^ Mas os primeiros governadores, que estiveram antes de mim, oprimiram o povo e tomaram dele pão e vinho, além de quarenta moedas de prata. Até os seus servos dominavam sobre o povo. Eu, porém, não fiz assim, por causa do temor de Deus.

[[v16-5-16]]

^<<v16-5-16,16>>^ Pelo contrário, também trabalhei na reconstrução da muralha, sem comprar nenhuma terra. E todos os meus servos se ajuntaram ali para a obra.

[[v16-5-17]]

^<<v16-5-17,17>>^ Também hospedei cento e cinquenta homens dos judeus e dos magistrados, além daqueles das nações vizinhas que vinham até nós.

[[v16-5-18]]

^<<v16-5-18,18>>^ O que se preparava para cada dia era um boi e seis ovelhas escolhidas. Também à minha custa eram preparadas aves e, de dez em dez dias, muito vinho de todos os tipos. Nem por isso exigi o pão devido ao governador, porque a servidão deste povo era grande.

[[v16-5-19]]

^<<v16-5-19,19>>^ "Lembra-te de mim para meu bem, ó meu Deus, e de tudo o que fiz por este povo."

'''

xref:016-neemias/016-neemias-004.adoc#v16-4-0[&#60; Capítulo Anterior] | <<v16-5-0,Topo>> | xref:016-neemias/016-neemias-006.adoc#v16-6-0[Próximo Capítulo &#62;]