include::./index.adoc[]

[[v16-6-0]]
=== Neemias, 6
// naa ?, NAA - Nova Almeida Atualizada

[[v16-6-1]]

^<<v16-6-1,1>>^ Quando Sambalate, Tobias, Gesém, o árabe, e o resto dos nossos inimigos ouviram que eu tinha reconstruído a muralha e que nela já não havia brecha nenhuma, ainda que até este tempo eu ainda não tivesse colocado os portões no seu lugar,

[[v16-6-2]]

^<<v16-6-2,2>>^ Sambalate e Gesém mandaram dizer a mim: "Venha, vamos nos encontrar numa das aldeias do vale de Ono." Na verdade, o que eles queriam era me fazer mal.

[[v16-6-3]]

^<<v16-6-3,3>>^ Por isso enviei-lhes mensageiros para dizer: — Estou fazendo uma grande obra e não posso descer até aí. Por que devo parar a obra para ir me encontrar com vocês?

[[v16-6-4]]

^<<v16-6-4,4>>^ Quatro vezes eles fizeram o mesmo pedido, mas eu lhes dei sempre a mesma resposta.

[[v16-6-5]]

^<<v16-6-5,5>>^ Então Sambalate me enviou pela quinta vez o seu servo, que trazia na mão uma carta aberta.

[[v16-6-6]]

^<<v16-6-6,6>>^ Nela estava escrito o seguinte: "Entre os gentios se ouviu, e Gesém também está dizendo, que você e os judeus estão querendo se rebelar e que, por isso, você está reconstruindo a muralha. Também, segundo se diz, você quer ser o rei deles,

[[v16-6-7]]

^<<v16-6-7,7>>^ e pôs alguns profetas para falarem a respeito de você em Jerusalém, dizendo: ‘Ele é o rei de Judá.’ Ora, isso certamente vai chegar aos ouvidos do rei. Portanto, venha agora e vamos, em conjunto, conversar a respeito disso."

[[v16-6-8]]

^<<v16-6-8,8>>^ Mandei dizer-lhe: — Nada disso que você está dizendo aconteceu. Você está inventando tudo.

[[v16-6-9]]

^<<v16-6-9,9>>^ O que todos eles queriam era nos amedrontar. Eles diziam: "As mãos deles largarão a obra, e ela não será concluída." "Agora, pois, ó Deus, fortalece as minhas mãos."

[[v16-6-10]]

^<<v16-6-10,10>>^ Quando fui à casa de Semaías, filho de Delaías, filho de Meetabel, que estava impedido de sair de casa, ele me disse: — Vamos nos encontrar na Casa de Deus, dentro do templo. Vamos fechar as portas do templo, porque virão matar você. De noite eles virão matar você.

[[v16-6-11]]

^<<v16-6-11,11>>^ Porém eu disse: — Você acha que um homem como eu fugiria? Alguém como eu entraria no templo para salvar a vida? De maneira nenhuma entrarei.

[[v16-6-12]]

^<<v16-6-12,12>>^ Então percebi que não era Deus quem o tinha enviado, mas que ele falou tal profecia contra mim porque Tobias e Sambalate o haviam subornado.

[[v16-6-13]]

^<<v16-6-13,13>>^ Para isto o subornaram, para me amedrontar e para que, fazendo isso, eu viesse a pecar, para que pudessem atacar a minha reputação e me afrontar.

[[v16-6-14]]

^<<v16-6-14,14>>^ "Lembra-te, meu Deus, de Tobias e de Sambalate, segundo as coisas que fizeram, e também da profetisa Noadia e dos outros profetas que quiseram me amedrontar."

[[v16-6-15]]

^<<v16-6-15,15>>^ A reconstrução da muralha foi terminada aos vinte e cinco dias do mês de elul, em cinquenta e dois dias.

[[v16-6-16]]

^<<v16-6-16,16>>^ Quando todos os nossos inimigos ouviram isso, todos os gentios à nossa volta temeram e decaíram muito no seu próprio conceito, porque reconheceram que foi por intervenção do nosso Deus que fizemos esta obra.

[[v16-6-17]]

^<<v16-6-17,17>>^ Também naqueles dias alguns nobres de Judá escreveram muitas cartas a Tobias, e cartas de Tobias vinham para eles.

[[v16-6-18]]

^<<v16-6-18,18>>^ Pois muitos em Judá eram aliados dele, porque era genro de Secanias, filho de Ará. E o seu filho Joanã havia casado com a filha de Mesulão, filho de Berequias.

[[v16-6-19]]

^<<v16-6-19,19>>^ Também falavam das suas boas ações na minha presença, e levavam a ele as minhas palavras. Tobias escrevia cartas para me amedrontar.

'''

xref:016-neemias/016-neemias-005.adoc#v16-5-0[&#60; Capítulo Anterior] | <<v16-6-0,Topo>> | xref:016-neemias/016-neemias-007.adoc#v16-7-0[Próximo Capítulo &#62;]