include::./index.adoc[]

[[v16-13-0]]
=== Neemias, 13
// naa ?, NAA - Nova Almeida Atualizada

[[v16-13-1]]

^<<v16-13-1,1>>^ Naquele dia, o Livro de Moisés foi lido para o povo, e nele achou-se escrito que os amonitas e os moabitas não deveriam jamais entrar na congregação de Deus,

[[v16-13-2]]

^<<v16-13-2,2>>^ porque não tinham ido ao encontro dos filhos de Israel com pão e água. Em vez disso, contrataram Balaão para os amaldiçoar. Mas o nosso Deus transformou a maldição em bênção.

[[v16-13-3]]

^<<v16-13-3,3>>^ Quando os israelitas ouviram esta lei, afastaram de Israel todos os estrangeiros.

[[v16-13-4]]

^<<v16-13-4,4>>^ Antes disto, o sacerdote Eliasibe, encarregado dos depósitos do templo do nosso Deus, parente de Tobias,

[[v16-13-5]]

^<<v16-13-5,5>>^ havia cedido para este uma grande sala. Anteriormente, era ali que se depositavam as ofertas de cereais, o incenso, os utensílios e os dízimos dos cereais, do vinho e do azeite, que eram destinados aos levitas, cantores e porteiros, bem como as contribuições para os sacerdotes.

[[v16-13-6]]

^<<v16-13-6,6>>^ Mas, quando isso aconteceu, eu não estava em Jerusalém, porque no trigésimo segundo ano de Artaxerxes, rei da Babilônia, eu tinha voltado para junto do rei. Mas, depois de certo tempo, pedi licença ao rei e voltei para Jerusalém.

[[v16-13-7]]

^<<v16-13-7,7>>^ Então soube do mal que Eliasibe havia feito para beneficiar Tobias, cedendo-lhe uma sala nos pátios da Casa de Deus.

[[v16-13-8]]

^<<v16-13-8,8>>^ Isso me deixou tão irritado, que atirei todos os móveis de Tobias para fora da sala.

[[v16-13-9]]

^<<v16-13-9,9>>^ Então ordenei que purificassem as salas, e coloquei ali outra vez os utensílios da Casa de Deus, com as ofertas de cereais e o incenso.

[[v16-13-10]]

^<<v16-13-10,10>>^ Também soube que as porções dos levitas não estavam sendo dadas a eles, de maneira que os levitas e os cantores, que faziam o serviço, tinham fugido cada um para o seu campo.

[[v16-13-11]]

^<<v16-13-11,11>>^ Então repreendi os magistrados e perguntei: — Por que a Casa de Deus ficou abandonada? Reuni os levitas e os cantores e os restituí aos seus postos.

[[v16-13-12]]

^<<v16-13-12,12>>^ Então todo o Judá trouxe os dízimos dos cereais, do vinho e do azeite aos depósitos.

[[v16-13-13]]

^<<v16-13-13,13>>^ Por tesoureiros dos depósitos pus Selemias, o sacerdote, Zadoque, o escrivão, e um levita chamado Pedaías. Como assistente deles pus Hanã, filho de Zacur, filho de Matanias. Estes homens foram achados fiéis e ficaram encarregados de distribuir as porções entre os seus irmãos.

[[v16-13-14]]

^<<v16-13-14,14>>^ "Lembra-te de mim, ó meu Deus, e não apagues o bem que eu fiz ao templo de meu Deus e ao seu serviço."

[[v16-13-15]]

^<<v16-13-15,15>>^ Naqueles dias, vi que em Judá havia homens que no sábado pisavam uvas nos lagares e traziam trigo que carregavam sobre jumentos. Também no dia de sábado traziam para Jerusalém vinho, uvas e figos e todo tipo de cargas. Protestei contra eles por venderem alimentos neste dia.

[[v16-13-16]]

^<<v16-13-16,16>>^ Também moravam em Jerusalém homens de Tiro que traziam peixes e todo tipo de mercadorias, que no sábado vendiam aos filhos de Judá e em Jerusalém.

[[v16-13-17]]

^<<v16-13-17,17>>^ Repreendi os nobres de Judá e lhes disse: — Que coisa errada é esta que vocês estão fazendo? Estão profanando o dia de sábado!

[[v16-13-18]]

^<<v16-13-18,18>>^ Por acaso os pais de vocês não fizeram o mesmo, levando o nosso Deus a trazer todo este mal sobre nós e sobre esta cidade? E vocês ainda estão trazendo ira maior sobre Israel, profanando o sábado.

[[v16-13-19]]

^<<v16-13-19,19>>^ Quando os portões de Jerusalém começavam a projetar a sua sombra antes do sábado, ordenei que fossem fechados. E determinei que não fossem abertos, a não ser depois do sábado. Coloquei alguns dos meus servos junto aos portões, para que nenhuma carga entrasse no dia de sábado.

[[v16-13-20]]

^<<v16-13-20,20>>^ Então os negociantes e os vendedores de todo tipo de mercadorias pernoitaram fora de Jerusalém, uma ou duas vezes.

[[v16-13-21]]

^<<v16-13-21,21>>^ Eu os repreendi e lhes disse: — Por que estão passando a noite diante da muralha? Se fizerem isso outra vez, eu usarei a força. Daí em diante não voltaram mais no sábado.

[[v16-13-22]]

^<<v16-13-22,22>>^ Também mandei aos levitas que se purificassem e viessem guardar os portões, para santificar o dia de sábado. "Também nisto, lembra-te de mim, ó meu Deus. Tem piedade de mim por tua grande misericórdia."

[[v16-13-23]]

^<<v16-13-23,23>>^ Vi também, naqueles dias, que judeus haviam casado com mulheres asdoditas, amonitas e moabitas.

[[v16-13-24]]

^<<v16-13-24,24>>^ E seus filhos falavam metade das palavras na língua de Asdode ou na língua de seu respectivo povo, mas não sabiam falar a língua dos judeus.

[[v16-13-25]]

^<<v16-13-25,25>>^ Eu os repreendi e os amaldiçoei; espanquei alguns deles e arranquei os seus cabelos. E os fiz jurar em nome de Deus, dizendo: — Não deem mais as suas filhas em casamento aos filhos deles, nem escolham mais as filhas deles para os seus filhos ou para vocês mesmos.

[[v16-13-26]]

^<<v16-13-26,26>>^ Não foi por causa disto que Salomão, rei de Israel, pecou? Entre muitas nações não havia rei semelhante a ele. Era amado por seu Deus, e Deus o colocou como rei sobre todo o Israel. Mas as mulheres estrangeiras o fizeram cair no pecado.

[[v16-13-27]]

^<<v16-13-27,27>>^ Será que devemos dar ouvidos a vocês, para fazermos todo este grande mal, sendo infiéis ao nosso Deus, casando com mulheres estrangeiras?

[[v16-13-28]]

^<<v16-13-28,28>>^ Um dos filhos de Joiada, filho do sumo sacerdote Eliasibe, era genro de Sambalate, o horonita. Por isso, eu o expulsei da minha presença.

[[v16-13-29]]

^<<v16-13-29,29>>^ "Lembra-te deles, ó meu Deus, pois contaminaram o sacerdócio e a aliança sacerdotal e levítica."

[[v16-13-30]]

^<<v16-13-30,30>>^ Assim, eu os purifiquei de tudo o que era estrangeiro e organizei o serviço dos sacerdotes e dos levitas, cada um na sua função.

[[v16-13-31]]

^<<v16-13-31,31>>^ Organizei também o fornecimento de lenha em tempos determinados, bem como das primícias. "Lembra-te de mim, ó meu Deus, para o meu bem."

'''

xref:016-neemias/016-neemias-012.adoc#v16-12-0[&#60; Capítulo Anterior] | <<v16-13-0,Topo>> | xref:017-ester/017-ester-001.adoc#v17-1-0[Próximo Capítulo &#62;]