include::./index.adoc[]

[[v16-3-0]]
=== Neemias, 3
// naa ?, NAA - Nova Almeida Atualizada

[[v16-3-1]]

^<<v16-3-1,1>>^ Então o sumo sacerdote Eliasibe se levantou com os seus irmãos, os sacerdotes, e reconstruíram o Portão das Ovelhas. Eles o consagraram, colocaram os portões no seu lugar e continuaram a reconstrução até a Torre dos Cem e a Torre de Hananel.

[[v16-3-2]]

^<<v16-3-2,2>>^ Ao lado dele trabalharam os homens de Jericó, e, ao lado deles, Zacur, filho de Inri.

[[v16-3-3]]

^<<v16-3-3,3>>^ Os filhos de Hassenaá reconstruíram o Portão dos Peixes. Colocaram as vigas e os portões nos seus lugares, com os seus ferrolhos e as trancas.

[[v16-3-4]]

^<<v16-3-4,4>>^ Ao lado deles, quem fez os reparos foi Meremote, filho de Urias, filho de Coz, e ao lado deste, Mesulão, filho de Berequias, filho de Mesezabel. Ao lado deste, Zadoque, filho de Baaná, fez os reparos.

[[v16-3-5]]

^<<v16-3-5,5>>^ Ao lado destes, trabalharam os tecoítas. Mas os seus nobres não se sujeitaram ao serviço do seu senhor.

[[v16-3-6]]

^<<v16-3-6,6>>^ Joiada, filho de Paseia, e Mesulão, filho de Besodias, repararam o Portão Velho. Colocaram as vigas e os portões nos seus lugares, com os seus ferrolhos e as trancas.

[[v16-3-7]]

^<<v16-3-7,7>>^ Ao lado deles, trabalharam Melatias, gibeonita, e Jadom, meronotita, homens de Gibeão e de Mispa, que pertenciam ao domínio do governador de além do Eufrates.

[[v16-3-8]]

^<<v16-3-8,8>>^ Ao seu lado, quem fez os reparos foi Uziel, filho de Haraías, um dos ourives, e, ao lado dele, Hananias, um dos perfumistas. Eles restauraram Jerusalém até a Muralha Larga.

[[v16-3-9]]

^<<v16-3-9,9>>^ Ao lado destes, trabalhou Refaías, filho de Hur, governador de metade do distrito de Jerusalém.

[[v16-3-10]]

^<<v16-3-10,10>>^ Ao seu lado, Jedaías, filho de Harumafe, fez os reparos em frente da sua casa; e, ao seu lado, Hatus, filho de Hasabneias, fez os reparos.

[[v16-3-11]]

^<<v16-3-11,11>>^ Malquias, filho de Harim, e Hassube, filho de Paate-Moabe, repararam o trecho seguinte e a Torre dos Fornos.

[[v16-3-12]]

^<<v16-3-12,12>>^ Ao lado dele, quem fez os reparos foi Salum, filho de Haloés, governador da outra metade do distrito de Jerusalém, ele e as suas filhas.

[[v16-3-13]]

^<<v16-3-13,13>>^ Hanum e os moradores de Zanoa repararam o Portão do Vale. Eles o reconstruíram, colocaram os portões no seu lugar, com os seus ferrolhos e as trancas, e ainda consertaram quinhentos metros da muralha, até o Portão do Monturo.

[[v16-3-14]]

^<<v16-3-14,14>>^ O Portão do Monturo foi reparado por Malquias, filho de Recabe, governador do distrito de Bete-Haquerém. Ele o reconstruiu, colocou os portões no seu lugar, com os seus ferrolhos e as trancas.

[[v16-3-15]]

^<<v16-3-15,15>>^ O Portão da Fonte foi reparado por Salum, filho de Col-Hozé, governador do distrito de Mispa. Ele o reconstruiu, fez uma cobertura, colocou os portões no seu lugar, com os seus ferrolhos e as trancas. Também reconstruiu a muralha do tanque de Selá, junto ao jardim do rei, até os degraus que descem da Cidade de Davi.

[[v16-3-16]]

^<<v16-3-16,16>>^ Ao lado dele, quem fez os reparos foi Neemias, filho de Azbuque, governador de metade do distrito de Bete-Zur, até em frente dos túmulos de Davi, até o tanque e até a casa dos heróis.

[[v16-3-17]]

^<<v16-3-17,17>>^ Depois dele, os levitas, Reum, filho de Bani, e, ao seu lado, Hasabias, governador da metade do distrito de Queila, fizeram os reparos.

[[v16-3-18]]

^<<v16-3-18,18>>^ Depois dele, os reparos foram feitos pelos seus irmãos: Bavai, filho de Henadade, governador da metade do distrito de Queila.

[[v16-3-19]]

^<<v16-3-19,19>>^ Ao seu lado, Ezer, filho de Jesua, governador de Mispa, reparou outro trecho em frente da subida para a casa das armas, na esquina da muralha.

[[v16-3-20]]

^<<v16-3-20,20>>^ Depois dele, Baruque, filho de Zabai, reparou com muito cuidado outro trecho, desde a esquina da muralha até a porta da casa de Eliasibe, o sumo sacerdote.

[[v16-3-21]]

^<<v16-3-21,21>>^ Depois dele, Meremote, filho de Urias, filho de Coz, reparou outro trecho, desde a porta da casa de Eliasibe até a extremidade da casa de Eliasibe.

[[v16-3-22]]

^<<v16-3-22,22>>^ Depois dele, quem fez os reparos foram os sacerdotes que moravam na campina.

[[v16-3-23]]

^<<v16-3-23,23>>^ Depois, Benjamim e Hassube fizeram os reparos, em frente da sua casa. Depois deles, Azarias, filho de Maaseias, filho de Ananias, reparou junto à sua casa.

[[v16-3-24]]

^<<v16-3-24,24>>^ Depois dele, Binui, filho de Henadade, reparou outro trecho, desde a casa de Azarias até a esquina.

[[v16-3-25]]

^<<v16-3-25,25>>^ Palal, filho de Uzai, reparou em frente da esquina e da torre que sai do palácio real superior, que está junto ao pátio da prisão. Depois dele, Pedaías, filho de Parós,

[[v16-3-26]]

^<<v16-3-26,26>>^ e os servos do templo que moravam em Ofel fizeram os reparos até em frente do Portão das Águas, na direção do leste, e até a torre alta.

[[v16-3-27]]

^<<v16-3-27,27>>^ Depois, os tecoítas repararam outro trecho, em frente da torre grande e alta, e até a Muralha de Ofel.

[[v16-3-28]]

^<<v16-3-28,28>>^ Para cima do Portão dos Cavalos, os sacerdotes fizeram os reparos, cada um em frente da sua casa.

[[v16-3-29]]

^<<v16-3-29,29>>^ Depois deles, Zadoque, filho de Imer, reparou em frente da sua casa e, depois dele, Semaías, filho de Secanias, guarda do Portão Leste, reparou o trecho seguinte.

[[v16-3-30]]

^<<v16-3-30,30>>^ Depois dele, Hananias, filho de Selemias, e Hanum, o sexto filho de Zalafe, repararam outro trecho. Depois deles, Mesulão, filho de Berequias, fez os reparos em frente de sua residência.

[[v16-3-31]]

^<<v16-3-31,31>>^ Depois dele, Malquias, filho de um ourives, fez os reparos até a casa dos servos do templo e dos mercadores, em frente do Portão da Guarda, até o terraço da esquina.

[[v16-3-32]]

^<<v16-3-32,32>>^ Entre o terraço da esquina e o Portão das Ovelhas, os reparos foram feitos pelos ourives e pelos mercadores.

'''

xref:016-neemias/016-neemias-002.adoc#v16-2-0[&#60; Capítulo Anterior] | <<v16-3-0,Topo>> | xref:016-neemias/016-neemias-004.adoc#v16-4-0[Próximo Capítulo &#62;]