include::./index.adoc[]

[[v16-2-0]]
=== Neemias, 2
// naa ?, NAA - Nova Almeida Atualizada

[[v16-2-1]]

^<<v16-2-1,1>>^ No mês de nisã, no vigésimo ano do reinado de Artaxerxes, uma vez posto o vinho diante dele, eu o peguei e ofereci ao rei. Ora, nunca antes eu tinha estado triste diante dele.

[[v16-2-2]]

^<<v16-2-2,2>>^ Então o rei me disse: — Por que o seu rosto está triste, se você não está doente? Isso tem de ser tristeza do coração! Então fiquei com muito medo

[[v16-2-3]]

^<<v16-2-3,3>>^ e lhe respondi: — Que o rei viva para sempre! Como não estaria triste o meu rosto, se a cidade onde estão sepultados os meus pais está em ruínas e os seus portões foram queimados?

[[v16-2-4]]

^<<v16-2-4,4>>^ O rei me disse: — O que você me pede agora? Então orei ao Deus dos céus

[[v16-2-5]]

^<<v16-2-5,5>>^ e disse ao rei: — Se for do agrado do rei, e se este seu servo encontrou favor em sua presença, peço que o rei me envie a Judá, à cidade onde estão os túmulos dos meus pais, para que eu a reconstrua.

[[v16-2-6]]

^<<v16-2-6,6>>^ Então o rei, que tinha a rainha sentada ao seu lado, me perguntou: — Quanto vai durar a sua ausência? Quando você voltará? Marquei certo prazo, e o rei se deu por satisfeito e me deixou ir.

[[v16-2-7]]

^<<v16-2-7,7>>^ Eu ainda disse ao rei: — Se for do agrado do rei, que ele me dê cartas para os governadores da região do outro lado do Eufrates, para que me permitam passar e entrar em Judá.

[[v16-2-8]]

^<<v16-2-8,8>>^ E também uma carta para Asafe, guarda das florestas do rei, para que me dê madeira para as vigas dos portões da cidadela do templo, para as muralhas da cidade e para a casa em que deverei me alojar. E o rei me deu o que eu pedi, porque a mão bondosa do meu Deus estava sobre mim.

[[v16-2-9]]

^<<v16-2-9,9>>^ Então fui aos governadores da região do outro lado do Eufrates e lhes entreguei as cartas do rei. Ora, o rei tinha enviado comigo oficiais do exército e cavaleiros.

[[v16-2-10]]

^<<v16-2-10,10>>^ Mas Sambalate, o horonita, e Tobias, o servo amonita, ficaram sabendo disto e não lhes agradou nem um pouco que alguém estivesse interessado no bem dos filhos de Israel.

[[v16-2-11]]

^<<v16-2-11,11>>^ Então cheguei a Jerusalém. Depois de esperar três dias,

[[v16-2-12]]

^<<v16-2-12,12>>^ me levantei à noite, junto com uns poucos homens que estavam comigo. Não declarei a ninguém o que o meu Deus havia posto no meu coração para eu fazer em Jerusalém. Não havia comigo animal algum, a não ser o que eu montava.

[[v16-2-13]]

^<<v16-2-13,13>>^ De noite, saí pelo Portão do Vale, em direção à Fonte do Dragão e ao Portão do Monturo, e inspecionei as muralhas de Jerusalém, que estavam em ruínas e cujos portões tinham sido destruídos pelo fogo.

[[v16-2-14]]

^<<v16-2-14,14>>^ Passei ao Portão da Fonte e ao Tanque do Rei, mas não havia lugar por onde o animal que eu montava pudesse passar.

[[v16-2-15]]

^<<v16-2-15,15>>^ Subi à noite pelo vale, sempre inspecionando as muralhas. Voltei, entrei pelo Portão do Vale e fui para casa.

[[v16-2-16]]

^<<v16-2-16,16>>^ Os magistrados não sabiam aonde eu tinha ido nem o que tinha feito, pois até ali eu não havia declarado coisa alguma, nem aos judeus, nem aos sacerdotes, nem aos nobres, nem aos magistrados, nem aos demais que iriam fazer a obra.

[[v16-2-17]]

^<<v16-2-17,17>>^ Então eu lhes disse: — Vocês estão vendo a miséria em que nós estamos: Jerusalém em ruínas e os seus portões destruídos pelo fogo. Venham, vamos reconstruir as muralhas de Jerusalém, para nos livrarmos desta vergonha.

[[v16-2-18]]

^<<v16-2-18,18>>^ E lhes declarei como a mão bondosa do meu Deus havia estado sobre mim e também as palavras que o rei me havia falado. Então disseram: — Vamos nos preparar e começar a reconstrução! Então se prepararam para fazer esta boa obra.

[[v16-2-19]]

^<<v16-2-19,19>>^ Porém, quando Sambalate, o horonita, Tobias, o servo amonita, e um árabe chamado Gesém souberam disso, zombaram de nós e nos desprezaram, dizendo: — O que é isso que vocês estão fazendo? Querem se rebelar contra o rei?

[[v16-2-20]]

^<<v16-2-20,20>>^ Então lhes respondi: — O Deus dos céus é quem fará com que sejamos bem-sucedidos. Nós, seus servos, vamos nos preparar e começar a reconstrução. Mas vocês não têm parte, nem direito, nem memorial em Jerusalém.

'''

xref:016-neemias/016-neemias-001.adoc#v16-1-0[&#60; Capítulo Anterior] | <<v16-2-0,Topo>> | xref:016-neemias/016-neemias-003.adoc#v16-3-0[Próximo Capítulo &#62;]