include::./index.adoc[]

[[v16-7-0]]
=== Neemias, 7
// naa ?, NAA - Nova Almeida Atualizada

[[v16-7-1]]

^<<v16-7-1,1>>^ Depois de reconstruída a muralha e colocados os portões no seu lugar, estabelecidos os porteiros, os cantores e os levitas,

[[v16-7-2]]

^<<v16-7-2,2>>^ eu nomeei Hanani, meu irmão, e Hananias, comandante da fortaleza, para que cuidassem da segurança de Jerusalém. Hananias era homem fiel e temente a Deus, mais do que muitos outros.

[[v16-7-3]]

^<<v16-7-3,3>>^ E eu lhes disse: — Os portões de Jerusalém não devem ser abertos antes que o sol faça sentir o seu calor. E os portões devem ser fechados e trancados enquanto os guardas ainda estão ali. Escolham guardas entre os moradores de Jerusalém, alguns para que fiquem nos postos de guarda e outros para que fiquem em frente das suas próprias casas.

[[v16-7-4]]

^<<v16-7-4,4>>^ A cidade era espaçosa e grande, mas havia pouca gente nela, e as casas ainda não haviam sido reconstruídas.

[[v16-7-5]]

^<<v16-7-5,5>>^ Então o meu Deus me pôs no coração que ajuntasse os nobres, os magistrados e o povo, para registrar as genealogias. Achei o livro da genealogia dos que foram os primeiros a voltar do cativeiro, e nele estava escrito:

[[v16-7-6]]

^<<v16-7-6,6>>^ Estes são os filhos da província que voltaram do cativeiro, do meio dos exilados que Nabucodonosor, rei da Babilônia, tinha levado para lá. Eles voltaram para Jerusalém e para Judá, cada um para a sua cidade,

[[v16-7-7]]

^<<v16-7-7,7>>^ e vieram com Zorobabel, Jesua, Neemias, Azarias, Raamias, Naamani, Mordecai, Bilsã, Misperete, Bigvai, Neum e Baaná. Eis o número dos homens do povo de Israel:

[[v16-7-8]]

^<<v16-7-8,8>>^ os filhos de Parós, dois mil cento e setenta e dois.

[[v16-7-9]]

^<<v16-7-9,9>>^ Os filhos de Sefatias, trezentos e setenta e dois.

[[v16-7-10]]

^<<v16-7-10,10>>^ Os filhos de Ará, seiscentos e cinquenta e dois.

[[v16-7-11]]

^<<v16-7-11,11>>^ Os filhos de Paate-Moabe, dos filhos de Jesua e de Joabe, dois mil oitocentos e dezoito.

[[v16-7-12]]

^<<v16-7-12,12>>^ Os filhos de Elão, mil duzentos e cinquenta e quatro.

[[v16-7-13]]

^<<v16-7-13,13>>^ Os filhos de Zatu, oitocentos e quarenta e cinco.

[[v16-7-14]]

^<<v16-7-14,14>>^ Os filhos de Zacai, setecentos e sessenta.

[[v16-7-15]]

^<<v16-7-15,15>>^ Os filhos de Binui, seiscentos e quarenta e oito.

[[v16-7-16]]

^<<v16-7-16,16>>^ Os filhos de Bebai, seiscentos e vinte e oito.

[[v16-7-17]]

^<<v16-7-17,17>>^ Os filhos de Azgade, dois mil trezentos e vinte e dois.

[[v16-7-18]]

^<<v16-7-18,18>>^ Os filhos de Adonicão, seiscentos e sessenta e sete.

[[v16-7-19]]

^<<v16-7-19,19>>^ Os filhos de Bigvai, dois mil e sessenta e sete.

[[v16-7-20]]

^<<v16-7-20,20>>^ Os filhos de Adim, seiscentos e cinquenta e cinco.

[[v16-7-21]]

^<<v16-7-21,21>>^ Os filhos de Ater, da família de Ezequias, noventa e oito.

[[v16-7-22]]

^<<v16-7-22,22>>^ Os filhos de Hasum, trezentos e vinte e oito.

[[v16-7-23]]

^<<v16-7-23,23>>^ Os filhos de Besai, trezentos e vinte e quatro.

[[v16-7-24]]

^<<v16-7-24,24>>^ Os filhos de Harife, cento e doze.

[[v16-7-25]]

^<<v16-7-25,25>>^ Os filhos de Gibeão, noventa e cinco.

[[v16-7-26]]

^<<v16-7-26,26>>^ Os homens de Belém e de Netofa, cento e oitenta e oito.

[[v16-7-27]]

^<<v16-7-27,27>>^ Os homens de Anatote, cento e vinte e oito.

[[v16-7-28]]

^<<v16-7-28,28>>^ Os homens de Bete-Azmavete, quarenta e dois.

[[v16-7-29]]

^<<v16-7-29,29>>^ Os homens de Quiriate-Jearim, Cefira e Beerote, setecentos e quarenta e três.

[[v16-7-30]]

^<<v16-7-30,30>>^ Os homens de Ramá e Geba, seiscentos e vinte e um.

[[v16-7-31]]

^<<v16-7-31,31>>^ Os homens de Micmás, cento e vinte e dois.

[[v16-7-32]]

^<<v16-7-32,32>>^ Os homens de Betel e Ai, cento e vinte e três.

[[v16-7-33]]

^<<v16-7-33,33>>^ Os homens do outro Nebo, cinquenta e dois.

[[v16-7-34]]

^<<v16-7-34,34>>^ Os filhos do outro Elão, mil duzentos e cinquenta e quatro.

[[v16-7-35]]

^<<v16-7-35,35>>^ Os filhos de Harim, trezentos e vinte.

[[v16-7-36]]

^<<v16-7-36,36>>^ Os filhos de Jericó, trezentos e quarenta e cinco.

[[v16-7-37]]

^<<v16-7-37,37>>^ Os filhos de Lode, Hadide e Ono, setecentos e vinte e um.

[[v16-7-38]]

^<<v16-7-38,38>>^ Os filhos de Senaá, três mil novecentos e trinta.

[[v16-7-39]]

^<<v16-7-39,39>>^ Os sacerdotes: os filhos de Jedaías, da casa de Jesua, novecentos e setenta e três.

[[v16-7-40]]

^<<v16-7-40,40>>^ Os filhos de Imer, mil e cinquenta e dois.

[[v16-7-41]]

^<<v16-7-41,41>>^ Os filhos de Pasur, mil duzentos e quarenta e sete.

[[v16-7-42]]

^<<v16-7-42,42>>^ Os filhos de Harim, mil e dezessete.

[[v16-7-43]]

^<<v16-7-43,43>>^ Os levitas: os filhos de Jesua, de Cadmiel, dos filhos de Hodeva, setenta e quatro.

[[v16-7-44]]

^<<v16-7-44,44>>^ Os cantores: os filhos de Asafe, cento e quarenta e oito.

[[v16-7-45]]

^<<v16-7-45,45>>^ Os porteiros: os filhos de Salum, os filhos de Ater, os filhos de Talmom, os filhos de Acube, os filhos de Hatita, os filhos de Sobai, cento e trinta e oito.

[[v16-7-46]]

^<<v16-7-46,46>>^ Os servidores do templo: os filhos de Zia, os filhos de Hasufa, os filhos de Tabaote,

[[v16-7-47]]

^<<v16-7-47,47>>^ os filhos de Queros, os filhos de Sia, os filhos de Padom,

[[v16-7-48]]

^<<v16-7-48,48>>^ os filhos de Lebana, os filhos de Hagaba, os filhos de Salmai,

[[v16-7-49]]

^<<v16-7-49,49>>^ os filhos de Hanã, os filhos de Gidel, os filhos de Gaar,

[[v16-7-50]]

^<<v16-7-50,50>>^ os filhos de Reaías, os filhos de Rezim, os filhos de Necoda,

[[v16-7-51]]

^<<v16-7-51,51>>^ os filhos de Gazão, os filhos de Uzá, os filhos de Paseia,

[[v16-7-52]]

^<<v16-7-52,52>>^ os filhos de Besai, os filhos de Meunim, os filhos de Nefusesim,

[[v16-7-53]]

^<<v16-7-53,53>>^ os filhos de Baquebuque, os filhos de Hacufa, os filhos de Harur,

[[v16-7-54]]

^<<v16-7-54,54>>^ os filhos de Bazlite, os filhos de Meída, os filhos de Harsa,

[[v16-7-55]]

^<<v16-7-55,55>>^ os filhos de Barcos, os filhos de Sísera, os filhos de Tama,

[[v16-7-56]]

^<<v16-7-56,56>>^ os filhos de Nesias e os filhos de Hatifa.

[[v16-7-57]]

^<<v16-7-57,57>>^ Os filhos dos servos de Salomão: os filhos de Sotai, os filhos de Soferete, os filhos de Perida,

[[v16-7-58]]

^<<v16-7-58,58>>^ os filhos de Jaala, os filhos de Darcom, os filhos de Gidel,

[[v16-7-59]]

^<<v16-7-59,59>>^ os filhos de Sefatias, os filhos de Hatil, os filhos de Poquerete-Hazebaim e os filhos de Amom.

[[v16-7-60]]

^<<v16-7-60,60>>^ Todos os servidores do templo e os filhos dos servos de Salomão eram trezentos e noventa e dois.

[[v16-7-61]]

^<<v16-7-61,61>>^ Os seguintes voltaram de Tel-Melá, Tel-Harsa, Querube, Adom e Imer, porém não puderam provar que as suas famílias e a sua linhagem eram de Israel:

[[v16-7-62]]

^<<v16-7-62,62>>^ os filhos de Delaías, os filhos de Tobias, os filhos de Necoda, seiscentos e quarenta e dois.

[[v16-7-63]]

^<<v16-7-63,63>>^ Dos sacerdotes: os filhos de Habaías, os filhos de Coz, os filhos de Barzilai, que tinha casado com uma das filhas de Barzilai, o gileadita, e que foi chamado pelo nome dele.

[[v16-7-64]]

^<<v16-7-64,64>>^ Estes procuraram o seu registro nos livros genealógicos, porém não acharam; por isso, foram considerados impuros para o sacerdócio.

[[v16-7-65]]

^<<v16-7-65,65>>^ O governador lhes disse que não comessem das coisas sagradas, até que se levantasse um sacerdote capaz de decidir a questão por meio de Urim e Tumim.

[[v16-7-66]]

^<<v16-7-66,66>>^ Toda esta congregação junta era de quarenta e dois mil trezentos e sessenta,

[[v16-7-67]]

^<<v16-7-67,67>>^ além dos seus servos e das suas servas, que eram sete mil trezentos e trinta e sete. Havia também duzentos e quarenta e cinco cantores e cantoras.

[[v16-7-68]]

^<<v16-7-68,68>>^ Os seus cavalos eram setecentos e trinta e seis; as suas mulas, duzentas e quarenta e cinco.

[[v16-7-69]]

^<<v16-7-69,69>>^ Os camelos eram quatrocentos e trinta e cinco e os jumentos, seis mil setecentos e vinte.

[[v16-7-70]]

^<<v16-7-70,70>>^ Alguns dos chefes das famílias contribuíram para a obra. O governador deu para o tesouro oito quilos e quatrocentos gramas de ouro, cinquenta bacias e quinhentas e trinta vestes sacerdotais.

[[v16-7-71]]

^<<v16-7-71,71>>^ E alguns mais dos chefes das famílias deram para o tesouro da obra cento e sessenta e oito quilos de ouro e mil e trezentos quilos de prata.

[[v16-7-72]]

^<<v16-7-72,72>>^ O que o restante do povo deu foram cento e sessenta e oito quilos de ouro, mil e duzentos quilos de prata e sessenta e sete vestes sacerdotais.

[[v16-7-73]]

^<<v16-7-73,73>>^ Os sacerdotes, os levitas, os porteiros, os cantores, alguns do povo, os servidores do templo e todo o Israel moravam nas suas cidades.

'''

xref:016-neemias/016-neemias-006.adoc#v16-6-0[&#60; Capítulo Anterior] | <<v16-7-0,Topo>> | xref:016-neemias/016-neemias-008.adoc#v16-8-0[Próximo Capítulo &#62;]