include::./index.adoc[]

[[v16-1-0]]
=== Neemias, 1
// naa ?, NAA - Nova Almeida Atualizada

[[v16-1-1]]

^<<v16-1-1,1>>^ Palavras de Neemias, filho de Hacalias. No mês de quisleu, no vigésimo ano, quando eu estava na cidadela de Susã,

[[v16-1-2]]

^<<v16-1-2,2>>^ veio Hanani, um dos meus irmãos, com alguns homens de Judá. Então lhes perguntei a respeito dos judeus que escaparam e que sobreviveram ao exílio e a respeito de Jerusalém.

[[v16-1-3]]

^<<v16-1-3,3>>^ E eles me responderam: — Os restantes, os que sobreviveram ao exílio e se encontram lá na província, estão em grande miséria e humilhação. As muralhas de Jerusalém continuam em ruínas, e os seus portões foram destruídos pelo fogo.

[[v16-1-4]]

^<<v16-1-4,4>>^ Quando ouvi estas palavras, eu me sentei, chorei e lamentei por alguns dias. Fiquei jejuando e orando diante do Deus dos céus.

[[v16-1-5]]

^<<v16-1-5,5>>^ Eu disse: — Ah! Senhor , Deus dos céus, Deus grande e temível, que guardas a aliança e a misericórdia para com aqueles que te amam e guardam os teus mandamentos!

[[v16-1-6]]

^<<v16-1-6,6>>^ Estejam atentos os teus ouvidos, e os teus olhos, abertos, para que atendas a oração do teu servo, que hoje faço diante de ti, dia e noite, pelos filhos de Israel, teus servos. Faço confissão dos pecados dos filhos de Israel, os quais temos cometido contra ti. Eu e a casa de meu pai pecamos.

[[v16-1-7]]

^<<v16-1-7,7>>^ Temos procedido de forma totalmente corrupta contra ti e não guardamos os mandamentos, nem os estatutos, nem os juízos que ordenaste a Moisés, teu servo.

[[v16-1-8]]

^<<v16-1-8,8>>^ Lembra-te da palavra que ordenaste a Moisés, teu servo, dizendo: "Se vocês forem infiéis, eu os espalharei entre os povos;

[[v16-1-9]]

^<<v16-1-9,9>>^ mas, se vocês se converterem a mim e guardarem os meus mandamentos, e os cumprirem, então, ainda que os seus desterrados estejam nos lugares mais distantes da terra, de lá os ajuntarei e os trarei para o lugar que escolhi para fazer habitar o meu nome."

[[v16-1-10]]

^<<v16-1-10,10>>^ Estes ainda são teus servos e o teu povo que resgataste com o teu grande poder e com a tua mão poderosa.

[[v16-1-11]]

^<<v16-1-11,11>>^ Ah! Senhor, estejam atentos os teus ouvidos à oração do teu servo e à oração dos teus servos que se agradam de temer o teu nome. Faze com que o teu servo seja bem-sucedido hoje e encontre misericórdia diante desse homem. Nesse tempo eu era copeiro do rei.

'''

xref:015-esdras/015-esdras-010.adoc#v15-10-0[&#60; Capítulo Anterior] | <<v16-1-0,Topo>> | xref:016-neemias/016-neemias-002.adoc#v16-2-0[Próximo Capítulo &#62;]