include::./index.adoc[]

[[v16-9-0]]
=== Neemias, 9
// naa ?, NAA - Nova Almeida Atualizada

[[v16-9-1]]

^<<v16-9-1,1>>^ No dia vinte e quatro deste sétimo mês, os filhos de Israel se reuniram para um jejum. Vestiam pano de saco e traziam terra sobre a cabeça.

[[v16-9-2]]

^<<v16-9-2,2>>^ Os da linhagem de Israel separaram-se de todos os estrangeiros, puseram-se em pé e fizeram confissão dos seus pecados e das iniquidades de seus pais.

[[v16-9-3]]

^<<v16-9-3,3>>^ Levantando-se no seu lugar, leram no Livro da Lei do Senhor , seu Deus, durante uma quarta parte do dia; e durante outra quarta parte do dia fizeram confissão e adoraram o Senhor , seu Deus.

[[v16-9-4]]

^<<v16-9-4,4>>^ Jesua, Bani, Cadmiel, Sebanias, Buni, Serebias, Bani e Quenani se puseram em pé no estrado dos levitas e clamaram em alta voz ao Senhor , seu Deus.

[[v16-9-5]]

^<<v16-9-5,5>>^ Os levitas Jesua, Cadmiel, Bani, Hasabneias, Serebias, Hodias, Sebanias e Petaías disseram: — Levantem-se e bendigam o Senhor , seu Deus, de eternidade a eternidade. Então se disse: — Bendito seja o teu nome glorioso, que ultrapassa todo bendizer e louvor.

[[v16-9-6]]

^<<v16-9-6,6>>^ Só tu és o Senhor ! Fizeste o céu, o céu dos céus e todo o seu exército, a terra e tudo o que nela há, os mares e tudo o que há neles. Tu conservas a todos com vida, e o exército dos céus te adora.

[[v16-9-7]]

^<<v16-9-7,7>>^ Tu és o Senhor , o Deus que escolheste Abrão, e o tiraste de Ur dos caldeus, e lhe puseste por nome Abraão.

[[v16-9-8]]

^<<v16-9-8,8>>^ Achaste o seu coração fiel diante de ti e com ele fizeste aliança, para dares à descendência dele a terra dos cananeus, dos heteus, dos amorreus, dos ferezeus, dos jebuseus e dos girgaseus; e cumpriste as tuas promessas, porque és justo.

[[v16-9-9]]

^<<v16-9-9,9>>^ — Viste a aflição dos nossos pais no Egito e ouviste o clamor deles junto ao mar Vermelho.

[[v16-9-10]]

^<<v16-9-10,10>>^ Fizeste sinais e maravilhas contra Faraó e seus servos e contra todo o povo da sua terra, porque soubeste que os trataram com arrogância; e assim adquiriste a fama que tens até o dia de hoje.

[[v16-9-11]]

^<<v16-9-11,11>>^ Dividiste o mar diante deles, de maneira que o atravessaram em terra seca; lançaste os seus perseguidores nas profundezas, como uma pedra nas águas impetuosas.

[[v16-9-12]]

^<<v16-9-12,12>>^ Tu os guiaste, durante o dia, com uma coluna de nuvem e, durante a noite, com uma coluna de fogo, para iluminar o caminho por onde deviam seguir.

[[v16-9-13]]

^<<v16-9-13,13>>^ Desceste sobre o monte Sinai, do céu falaste com eles e lhes deste juízos retos, leis verdadeiras, estatutos e mandamentos bons.

[[v16-9-14]]

^<<v16-9-14,14>>^ Tu lhes deste a conhecer o teu santo sábado, e lhes deste mandamentos, estatutos e lei, por meio de teu servo Moisés.

[[v16-9-15]]

^<<v16-9-15,15>>^ Quando estavam com fome lhes deste pão dos céus, e quando estavam com sede fizeste brotar água da rocha; e lhes disseste que entrassem para tomar posse da terra que, com juramento, prometeste dar a eles.

[[v16-9-16]]

^<<v16-9-16,16>>^ — Porém eles, os nossos pais, se tornaram arrogantes e teimosos, e não deram ouvidos aos teus mandamentos.

[[v16-9-17]]

^<<v16-9-17,17>>^ Recusaram ouvir-te e não se lembraram das tuas maravilhas, que fizeste no meio deles. Foram teimosos e na sua rebelião escolheram um chefe, com o propósito de voltarem para a sua servidão no Egito. Porém tu, ó Deus perdoador, bondoso e compassivo, tardio em irar-te e grande em bondade, tu não os abandonaste,

[[v16-9-18]]

^<<v16-9-18,18>>^ nem mesmo quando fizeram para si um bezerro de metal fundido e disseram: "Este é o seu deus, que o tirou do Egito"; e cometeram grandes blasfêmias.

[[v16-9-19]]

^<<v16-9-19,19>>^ — Mas tu, pela multidão das tuas misericórdias, não os abandonaste no deserto. A coluna de nuvem nunca se afastou deles durante o dia, para os guiar pelo caminho, nem a coluna de fogo durante a noite, para iluminar o caminho por onde deviam seguir.

[[v16-9-20]]

^<<v16-9-20,20>>^ E lhes concedeste o teu bom Espírito, para os ensinar. Não lhes negaste o teu maná, para poderem comer, e lhes deste água quando tiveram sede.

[[v16-9-21]]

^<<v16-9-21,21>>^ Durante quarenta anos tu os sustentaste no deserto, e nada lhes faltou; as roupas que eles usavam não envelheceram, e os seus pés não ficaram inchados.

[[v16-9-22]]

^<<v16-9-22,22>>^ — Também lhes deste reinos e povos, cujas terras repartiste entre eles. Assim, conquistaram a terra de Seom, rei de Hesbom, e a terra de Ogue, rei de Basã.

[[v16-9-23]]

^<<v16-9-23,23>>^ Multiplicaste os seus filhos como as estrelas do céu e os trouxeste à terra que tinhas prometido aos seus pais, dizendo que nela deveriam entrar.

[[v16-9-24]]

^<<v16-9-24,24>>^ Os filhos deles entraram e tomaram posse da terra. Subjugaste diante deles os moradores da terra, os cananeus, e os entregaste nas mãos deles, com os reis e os povos da terra, para fazerem com eles o que bem quisessem.

[[v16-9-25]]

^<<v16-9-25,25>>^ Conquistaram cidades fortificadas e terra fértil; tomaram posse de casas cheias de todo tipo de coisas boas, cisternas cavadas, vinhas e olivais e árvores frutíferas em abundância. Comeram, se fartaram, engordaram e viveram em delícias, pela tua grande bondade.

[[v16-9-26]]

^<<v16-9-26,26>>^ — Ainda assim foram desobedientes e se revoltaram contra ti; viraram as costas à tua Lei e mataram os teus profetas, que testemunhavam contra eles, para os fazerem voltar a ti; e cometeram grandes blasfêmias.

[[v16-9-27]]

^<<v16-9-27,27>>^ Por isso tu os entregaste nas mãos dos seus inimigos, que os oprimiram. Mas no tempo da sua angústia, clamaram a ti e dos céus tu os ouviste; e, segundo a tua grande misericórdia, lhes deste libertadores que os salvaram das mãos dos que os oprimiam.

[[v16-9-28]]

^<<v16-9-28,28>>^ Porém, quando se viam em descanso, tornavam a fazer o mal diante de ti, e tu os abandonavas nas mãos dos seus inimigos, para que dominassem sobre eles. Mas, quando se converteram e clamaram a ti, tu os ouviste dos céus e, segundo a tua misericórdia, os livraste muitas vezes.

[[v16-9-29]]

^<<v16-9-29,29>>^ Testemunhaste contra eles, para que voltassem à tua lei. Porém eles se mostraram arrogantes e não deram ouvidos aos teus mandamentos. Pecaram contra os teus juízos, pelos quais aquele que os cumprir viverá. Em sua rebeldia voltaram as costas, foram teimosos e não quiseram ouvir.

[[v16-9-30]]

^<<v16-9-30,30>>^ No entanto, tu os aturaste durante muitos anos e testemunhaste contra eles pelo teu Espírito, por meio dos teus profetas. Porém eles não quiseram ouvir e por isso os entregaste nas mãos dos povos de outras terras.

[[v16-9-31]]

^<<v16-9-31,31>>^ Mas, pela tua grande misericórdia, não acabaste com eles nem os abandonaste, porque tu és Deus clemente e misericordioso.

[[v16-9-32]]

^<<v16-9-32,32>>^ — Agora, pois, ó Deus nosso, ó Deus grande, poderoso e temível, que guardas a aliança e a misericórdia, não menosprezes toda a aflição que nos sobreveio, a nós, aos nossos reis, aos nossos príncipes, aos nossos sacerdotes, aos nossos profetas, aos nossos pais e a todo o teu povo, desde os dias dos reis da Assíria até o dia de hoje.

[[v16-9-33]]

^<<v16-9-33,33>>^ Tu foste justo em tudo o que nos aconteceu, pois agiste com fidelidade, enquanto nós procedemos mal.

[[v16-9-34]]

^<<v16-9-34,34>>^ Os nossos reis, os nossos príncipes, os nossos sacerdotes e os nossos pais não guardaram a tua lei, nem deram ouvidos aos mandamentos e aos testemunhos que lhes deste.

[[v16-9-35]]

^<<v16-9-35,35>>^ Pois eles, no seu reino, na abundância de bens que lhes deste, na terra espaçosa e fértil que puseste diante deles não te serviram, nem se converteram de suas obras más.

[[v16-9-36]]

^<<v16-9-36,36>>^ Eis que hoje somos escravos. E até na terra que deste aos nossos pais, para comerem o seu fruto e o seu bem, eis que somos escravos nela.

[[v16-9-37]]

^<<v16-9-37,37>>^ Seus abundantes produtos são para os reis que puseste sobre nós por causa dos nossos pecados. Estes reis dominam sobre nós e sobre o nosso gado, como bem entendem. Nós estamos em grande angústia!

[[v16-9-38]]

^<<v16-9-38,38>>^ — Por causa de tudo isso, nós fazemos uma aliança fiel, por escrito. E os nossos príncipes, os nossos levitas e os nossos sacerdotes puseram o seu selo sobre ela.

'''

xref:016-neemias/016-neemias-008.adoc#v16-8-0[&#60; Capítulo Anterior] | <<v16-9-0,Topo>> | xref:016-neemias/016-neemias-010.adoc#v16-10-0[Próximo Capítulo &#62;]