include::./index.adoc[]

[[v4-4-0]]
=== Números, 4
// naa ?, NAA - Nova Almeida Atualizada

[[v4-4-1]]

^<<v4-4-1,1>>^ O Senhor  disse a Moisés e a Arão:

[[v4-4-2]]

^<<v4-4-2,2>>^ — Levantem o censo dos filhos de Coate, do meio dos filhos de Levi, pelas suas famílias, segundo a casa de seus pais;

[[v4-4-3]]

^<<v4-4-3,3>>^ da idade de trinta anos para cima até os cinquenta será todo aquele que entrar neste serviço, para exercer algum encargo na tenda do encontro.

[[v4-4-4]]

^<<v4-4-4,4>>^ É este o serviço dos filhos de Coate na tenda do encontro, nas coisas santíssimas.

[[v4-4-5]]

^<<v4-4-5,5>>^ — Quando o arraial partir, Arão e seus filhos virão, tirarão o véu de cobrir, e, com ele, cobrirão a arca do testemunho;

[[v4-4-6]]

^<<v4-4-6,6>>^ por cima, lhe porão uma cobertura de peles finas e, sobre ela, estenderão um pano, todo azul, e passarão os cabos pelas argolas.

[[v4-4-7]]

^<<v4-4-7,7>>^ Também sobre a mesa da proposição estenderão um pano azul; e, sobre ela, porão os pratos, os recipientes do incenso, as taças e as jarras; também o pão contínuo estará sobre ela.

[[v4-4-8]]

^<<v4-4-8,8>>^ Depois, estenderão, em cima deles, um pano de carmesim, e, com a cobertura de peles finas, o cobrirão, e passarão os cabos pelas argolas.

[[v4-4-9]]

^<<v4-4-9,9>>^ Tomarão um pano azul e cobrirão o candelabro da iluminação, as suas lâmpadas, as suas tesouras de cortar pavios, os seus apagadores e todos os seus vasos de azeite com que o servem.

[[v4-4-10]]

^<<v4-4-10,10>>^ E envolverão a ele e todos os seus utensílios na cobertura de peles finas e o porão sobre os cabos.

[[v4-4-11]]

^<<v4-4-11,11>>^ Sobre o altar de ouro estenderão um pano azul, e, com a cobertura de peles finas, o cobrirão, e passarão os cabos pelas argolas.

[[v4-4-12]]

^<<v4-4-12,12>>^ Pegarão todos os utensílios do serviço com os quais servem no santuário e os envolverão num pano azul; então os cobrirão com uma cobertura de peles finas e os porão sobre os cabos.

[[v4-4-13]]

^<<v4-4-13,13>>^ Do altar tirarão as cinzas e, por cima dele, estenderão um pano de púrpura.

[[v4-4-14]]

^<<v4-4-14,14>>^ Sobre ele porão todos os seus utensílios com que o servem: os braseiros, os garfos, as pás e as bacias, todos os utensílios do altar; e, por cima dele, estenderão uma cobertura de peles finas e passarão os cabos pelas argolas.

[[v4-4-15]]

^<<v4-4-15,15>>^ Quando Arão e seus filhos tiverem acabado de cobrir o santuário e todos os móveis dele, e o arraial estiver pronto para partir, os filhos de Coate virão para levá-lo. Mas não tocarão nas coisas santas, para que não morram. São estas as coisas da tenda do encontro que os filhos de Coate devem levar.

[[v4-4-16]]

^<<v4-4-16,16>>^ — Eleazar, filho de Arão, o sacerdote, terá a seu encargo o azeite da iluminação, o incenso aromático, a oferta contínua de cereais e o óleo da unção; sim, terá a seu encargo todo o tabernáculo e tudo o que nele há, o santuário e os móveis.

[[v4-4-17]]

^<<v4-4-17,17>>^ O Senhor  disse a Moisés e a Arão:

[[v4-4-18]]

^<<v4-4-18,18>>^ — Não deixem que a tribo das famílias dos coatitas seja eliminada do meio dos levitas.

[[v4-4-19]]

^<<v4-4-19,19>>^ Para que eles fiquem vivos e não morram, quando se aproximarem das coisas santíssimas, façam o seguinte: Arão e seus filhos entrarão e lhes designarão a cada um o seu serviço e a sua carga.

[[v4-4-20]]

^<<v4-4-20,20>>^ Porém os coatitas não entrarão, nem por um instante, para ver as coisas santas, para que não morram.

[[v4-4-21]]

^<<v4-4-21,21>>^ O Senhor  disse ainda a Moisés:

[[v4-4-22]]

^<<v4-4-22,22>>^ — Levante o censo dos filhos de Gérson, segundo a casa de seus pais, segundo as suas famílias.

[[v4-4-23]]

^<<v4-4-23,23>>^ Da idade de trinta anos para cima até os cinquenta conte todo aquele que entrar neste serviço, para exercer algum encargo na tenda do encontro.

[[v4-4-24]]

^<<v4-4-24,24>>^ É este o serviço das famílias dos gersonitas para servir e levar cargas:

[[v4-4-25]]

^<<v4-4-25,25>>^ levarão as cortinas do tabernáculo, a tenda do encontro, sua cobertura, a cobertura de peles finas, que está sobre ele, o cortinado da porta da tenda do encontro,

[[v4-4-26]]

^<<v4-4-26,26>>^ as cortinas do pátio, o cortinado da porta do pátio, que rodeia o tabernáculo e o altar, as suas cordas e todos os objetos do seu serviço; e servirão em tudo o que diz respeito a estas coisas.

[[v4-4-27]]

^<<v4-4-27,27>>^ Todo o serviço dos filhos dos gersonitas, toda a sua carga e tudo o que devem fazer será segundo o mandado de Arão e de seus filhos; e vocês lhes determinarão tudo o que devem carregar.

[[v4-4-28]]

^<<v4-4-28,28>>^ Este é o serviço das famílias dos filhos dos gersonitas na tenda do encontro; o seu cargo estará sob a direção de Itamar, filho de Arão, o sacerdote.

[[v4-4-29]]

^<<v4-4-29,29>>^ — Quanto aos filhos de Merari, faça a contagem segundo as suas famílias e segundo a casa de seus pais.

[[v4-4-30]]

^<<v4-4-30,30>>^ Da idade de trinta anos para cima até os cinquenta conte todo aquele que entrar neste serviço, para exercer algum encargo na tenda do encontro.

[[v4-4-31]]

^<<v4-4-31,31>>^ Isto é o que eles terão de levar, segundo todo o seu serviço, na tenda do encontro: as tábuas do tabernáculo, os seus cabos, as suas colunas e as suas bases;

[[v4-4-32]]

^<<v4-4-32,32>>^ as colunas do pátio ao redor, as suas bases, as suas estacas e as suas cordas, com todos os seus utensílios e com tudo o que pertence ao seu serviço; e vocês designarão, nome por nome, os objetos que eles devem levar.

[[v4-4-33]]

^<<v4-4-33,33>>^ Este é o encargo das famílias dos filhos de Merari, segundo todo o seu serviço, na tenda do encontro, sob a direção de Itamar, filho de Arão, o sacerdote.

[[v4-4-34]]

^<<v4-4-34,34>>^ Moisés, Arão e os chefes do povo contaram os filhos dos coatitas, segundo as suas famílias e segundo a casa de seus pais,

[[v4-4-35]]

^<<v4-4-35,35>>^ da idade de trinta anos para cima até os cinquenta, todo aquele que entrou neste serviço, para exercer algum encargo na tenda do encontro.

[[v4-4-36]]

^<<v4-4-36,36>>^ Os que deles foram contados, segundo as suas famílias, foram dois mil setecentos e cinquenta.

[[v4-4-37]]

^<<v4-4-37,37>>^ São estes os que foram contados das famílias dos coatitas, todos os que serviam na tenda do encontro, os quais Moisés e Arão contaram, segundo o mandado do Senhor , por Moisés.

[[v4-4-38]]

^<<v4-4-38,38>>^ Os que foram contados dos filhos de Gérson, segundo as suas famílias e segundo a casa de seus pais,

[[v4-4-39]]

^<<v4-4-39,39>>^ da idade de trinta anos para cima até os cinquenta, todo aquele que entrou neste serviço, para exercer algum encargo na tenda do encontro,

[[v4-4-40]]

^<<v4-4-40,40>>^ os que deles foram contados, segundo as suas famílias, segundo a casa de seus pais, foram dois mil seiscentos e trinta.

[[v4-4-41]]

^<<v4-4-41,41>>^ São estes os que foram contados das famílias dos filhos de Gérson, todos os que serviam na tenda do encontro, os quais Moisés e Arão contaram, segundo o mandado do Senhor .

[[v4-4-42]]

^<<v4-4-42,42>>^ Os que foram contados das famílias dos filhos de Merari, segundo as suas famílias e segundo a casa de seus pais,

[[v4-4-43]]

^<<v4-4-43,43>>^ da idade de trinta anos para cima até os cinquenta, todo aquele que entrou neste serviço, para exercer algum encargo na tenda do encontro,

[[v4-4-44]]

^<<v4-4-44,44>>^ os que deles foram contados, segundo as suas famílias, foram três mil e duzentos.

[[v4-4-45]]

^<<v4-4-45,45>>^ São estes os que foram contados das famílias dos filhos de Merari, os quais Moisés e Arão contaram, segundo o mandado do Senhor , por Moisés.

[[v4-4-46]]

^<<v4-4-46,46>>^ Todos os que foram contados dos levitas, contados por Moisés, Arão e os chefes de Israel, segundo as suas famílias e segundo a casa de seus pais,

[[v4-4-47]]

^<<v4-4-47,47>>^ da idade de trinta anos para cima até os cinquenta, todos os que entraram para cumprir a tarefa do serviço e a de levarem cargas na tenda do encontro,

[[v4-4-48]]

^<<v4-4-48,48>>^ os que deles foram contados foram oito mil quinhentos e oitenta.

[[v4-4-49]]

^<<v4-4-49,49>>^ Segundo o mandado do Senhor , por Moisés, foram designados, cada um para o seu serviço e a sua carga; e deles foram contados, como o Senhor  havia ordenado a Moisés.

'''

xref:004-numeros/004-numeros-003.adoc#v4-3-0[&#60; Capítulo Anterior] | <<v4-4-0,Topo>> | xref:004-numeros/004-numeros-005.adoc#v4-5-0[Próximo Capítulo &#62;]