include::./index.adoc[]

[[v4-12-0]]
=== Números, 12
// naa ?, NAA - Nova Almeida Atualizada

[[v4-12-1]]

^<<v4-12-1,1>>^ Miriã e Arão falaram contra Moisés, por causa da mulher cuxita que este havia tomado; pois ele tinha tomado uma mulher cuxita.

[[v4-12-2]]

^<<v4-12-2,2>>^ E disseram: — Será que o Senhor  falou somente por meio de Moisés? Será que não falou também por meio de nós? E o Senhor  ouviu o que eles disseram.

[[v4-12-3]]

^<<v4-12-3,3>>^ Moisés era um homem muito manso, mais do que qualquer outro sobre a terra.

[[v4-12-4]]

^<<v4-12-4,4>>^ Imediatamente o Senhor  disse a Moisés, a Arão e a Miriã: — Vocês três, dirijam-se à tenda do encontro. E os três foram até lá.

[[v4-12-5]]

^<<v4-12-5,5>>^ Então o Senhor  desceu na coluna de nuvem e se pôs à porta da tenda. Depois, chamou Arão e Miriã, e eles se apresentaram.

[[v4-12-6]]

^<<v4-12-6,6>>^ Então o Senhor  disse: — Ouçam, agora, as minhas palavras: se entre vocês há um profeta, eu, o Senhor , em visão me faço conhecer a ele ou falo com ele em sonhos.

[[v4-12-7]]

^<<v4-12-7,7>>^ Não é assim com o meu servo Moisés, que é fiel em toda a minha casa.

[[v4-12-8]]

^<<v4-12-8,8>>^ Falo com ele face a face, claramente e não por enigmas; pois ele vê a forma do Senhor . Como, pois, vocês não tiveram medo de falar contra o meu servo, contra Moisés?

[[v4-12-9]]

^<<v4-12-9,9>>^ E a ira do Senhor  se acendeu contra eles; e ele se retirou.

[[v4-12-10]]

^<<v4-12-10,10>>^ Quando a nuvem se afastou de sobre a tenda, eis que Miriã estava leprosa, branca como a neve. Arão olhou para Miriã, e eis que ela estava coberta de lepra.

[[v4-12-11]]

^<<v4-12-11,11>>^ E Arão disse a Moisés: — Ah! Meu senhor, não ponha sobre nós este pecado, porque agimos de forma tola e pecamos.

[[v4-12-12]]

^<<v4-12-12,12>>^ Não permita que Miriã seja como um aborto, que, saindo do ventre de sua mãe, tenha metade de sua carne já consumida.

[[v4-12-13]]

^<<v4-12-13,13>>^ Moisés clamou ao Senhor , dizendo: — Ó Deus, peço-te que a cures.

[[v4-12-14]]

^<<v4-12-14,14>>^ O Senhor  respondeu a Moisés: — Se o pai de Miriã tivesse cuspido no rosto dela, não seria envergonhada por sete dias? Que ela seja encerrada sete dias fora do arraial e, depois, trazida de volta.

[[v4-12-15]]

^<<v4-12-15,15>>^ Assim, Miriã foi detida fora do arraial durante sete dias; e o povo não partiu enquanto Miriã não foi trazida de volta.

[[v4-12-16]]

^<<v4-12-16,16>>^ Porém, depois, o povo partiu de Hazerote e acampou no deserto de Parã.

'''

xref:004-numeros/004-numeros-011.adoc#v4-11-0[&#60; Capítulo Anterior] | <<v4-12-0,Topo>> | xref:004-numeros/004-numeros-013.adoc#v4-13-0[Próximo Capítulo &#62;]