include::./index.adoc[]

[[v4-29-0]]
=== Números, 29
// naa ?, NAA - Nova Almeida Atualizada

[[v4-29-1]]

^<<v4-29-1,1>>^ — No primeiro dia do sétimo mês, vocês terão uma santa convocação; não façam nenhum trabalho nesse dia. Nesse dia as trombetas tocarão.

[[v4-29-2]]

^<<v4-29-2,2>>^ Então, por holocausto, de aroma agradável ao Senhor , ofereçam um novilho, um carneiro e sete cordeiros de um ano, sem defeito.

[[v4-29-3]]

^<<v4-29-3,3>>^ A correspondente oferta de cereais da melhor farinha, amassada com azeite, será de seis litros para o novilho, quatro litros para o carneiro

[[v4-29-4]]

^<<v4-29-4,4>>^ e dois litros para cada um dos sete cordeiros.

[[v4-29-5]]

^<<v4-29-5,5>>^ Ofereçam também um bode, para oferta pelo pecado, para fazer expiação por vocês,

[[v4-29-6]]

^<<v4-29-6,6>>^ além do holocausto do mês e a correspondente oferta de cereais, do holocausto contínuo e a correspondente oferta de cereais, com as libações que acompanham, segundo o seu estatuto, em aroma agradável, oferta queimada ao Senhor .

[[v4-29-7]]

^<<v4-29-7,7>>^ — No dia dez deste sétimo mês, vocês terão santa convocação; vocês se humilharão e não farão nenhum trabalho.

[[v4-29-8]]

^<<v4-29-8,8>>^ Mas, por holocausto, em aroma agradável ao Senhor , ofereçam um novilho, um carneiro e sete cordeiros de um ano, todos sem defeito.

[[v4-29-9]]

^<<v4-29-9,9>>^ A correspondente oferta de cereais da melhor farinha, amassada com azeite, será seis litros para o novilho, quatro litros para o carneiro

[[v4-29-10]]

^<<v4-29-10,10>>^ e dois litros para cada um dos sete cordeiros.

[[v4-29-11]]

^<<v4-29-11,11>>^ Ofereçam também um bode, para oferta pelo pecado, além da oferta pelo pecado, para fazer expiação, e do holocausto contínuo, e da correspondente oferta de cereais, com as libações que acompanham.

[[v4-29-12]]

^<<v4-29-12,12>>^ — Aos quinze dias do sétimo mês, vocês terão santa convocação. Não façam nenhum trabalho, mas durante sete dias celebrem uma festa ao Senhor .

[[v4-29-13]]

^<<v4-29-13,13>>^ Por holocausto em oferta queimada, de aroma agradável ao Senhor , ofereçam treze novilhos, dois carneiros e catorze cordeiros de um ano, todos sem defeito.

[[v4-29-14]]

^<<v4-29-14,14>>^ A correspondente oferta de cereais da melhor farinha, amassada com azeite, será seis litros para cada um dos treze novilhos, quatro litros para cada um dos dois carneiros

[[v4-29-15]]

^<<v4-29-15,15>>^ e dois litros para cada um dos catorze cordeiros.

[[v4-29-16]]

^<<v4-29-16,16>>^ Ofereçam também um bode, para oferta pelo pecado, além do holocausto contínuo, a correspondente oferta de cereais e a libação que acompanha.

[[v4-29-17]]

^<<v4-29-17,17>>^ — No segundo dia, ofereçam doze novilhos, dois carneiros, catorze cordeiros de um ano, sem defeito,

[[v4-29-18]]

^<<v4-29-18,18>>^ com a oferta de cereais e as libações para os novilhos, para os carneiros e para os cordeiros, conforme o seu número, segundo o estatuto,

[[v4-29-19]]

^<<v4-29-19,19>>^ e um bode, para oferta pelo pecado, além do holocausto contínuo, a correspondente oferta de cereais e a libação que acompanha.

[[v4-29-20]]

^<<v4-29-20,20>>^ — No terceiro dia, ofereçam onze novilhos, dois carneiros, catorze cordeiros de um ano, sem defeito,

[[v4-29-21]]

^<<v4-29-21,21>>^ com a oferta de cereais e as libações para os novilhos, para os carneiros e para os cordeiros, conforme o seu número, segundo o estatuto,

[[v4-29-22]]

^<<v4-29-22,22>>^ e um bode, para oferta pelo pecado, além do holocausto contínuo, a correspondente oferta de cereais e a libação que acompanha.

[[v4-29-23]]

^<<v4-29-23,23>>^ — No quarto dia, ofereçam dez novilhos, dois carneiros, catorze cordeiros de um ano, sem defeito,

[[v4-29-24]]

^<<v4-29-24,24>>^ com a oferta de cereais e as libações para os novilhos, para os carneiros e para os cordeiros, conforme o seu número, segundo o estatuto,

[[v4-29-25]]

^<<v4-29-25,25>>^ e um bode, para oferta pelo pecado, além do holocausto contínuo, a correspondente oferta de cereais e a libação que acompanha.

[[v4-29-26]]

^<<v4-29-26,26>>^ — No quinto dia, ofereçam nove novilhos, dois carneiros, catorze cordeiros de um ano, sem defeito,

[[v4-29-27]]

^<<v4-29-27,27>>^ com a oferta de cereais e as libações para os novilhos, para os carneiros e para os cordeiros, conforme o seu número, segundo o estatuto,

[[v4-29-28]]

^<<v4-29-28,28>>^ e um bode, para oferta pelo pecado, além do holocausto contínuo, a correspondente oferta de cereais e a libação que acompanha.

[[v4-29-29]]

^<<v4-29-29,29>>^ — No sexto dia, ofereçam oito novilhos, dois carneiros, catorze cordeiros de um ano, sem defeito,

[[v4-29-30]]

^<<v4-29-30,30>>^ com a oferta de cereais e as libações para os novilhos, para os carneiros e para os cordeiros, conforme o seu número, segundo o estatuto,

[[v4-29-31]]

^<<v4-29-31,31>>^ e um bode, para oferta pelo pecado, além do holocausto contínuo, a correspondente oferta de cereais e a libação que acompanha.

[[v4-29-32]]

^<<v4-29-32,32>>^ — No sétimo dia, ofereçam sete novilhos, dois carneiros, catorze cordeiros de um ano, sem defeito,

[[v4-29-33]]

^<<v4-29-33,33>>^ com a oferta de cereais e as libações para os novilhos, para os carneiros e para os cordeiros, conforme o seu número, segundo o estatuto,

[[v4-29-34]]

^<<v4-29-34,34>>^ e um bode, para oferta pelo pecado, além do holocausto contínuo, a correspondente oferta de cereais e a libação que acompanha.

[[v4-29-35]]

^<<v4-29-35,35>>^ — No oitavo dia, vocês terão uma reunião solene; não façam nenhum trabalho nesse dia.

[[v4-29-36]]

^<<v4-29-36,36>>^ E, por holocausto, em oferta queimada de aroma agradável ao Senhor , ofereçam um novilho, um carneiro, sete cordeiros de um ano, sem defeito,

[[v4-29-37]]

^<<v4-29-37,37>>^ com a oferta de cereais e as libações para o novilho, para o carneiro e para os cordeiros, conforme o seu número, segundo o estatuto,

[[v4-29-38]]

^<<v4-29-38,38>>^ e um bode, para oferta pelo pecado, além do holocausto contínuo, a correspondente oferta de cereais e a libação que acompanha.

[[v4-29-39]]

^<<v4-29-39,39>>^ — Estas coisas vocês oferecerão ao Senhor  nas suas festas fixas, além dos seus votos e das suas ofertas voluntárias, para os seus holocaustos, as suas ofertas de cereais, as suas libações e as suas ofertas pacíficas.

[[v4-29-40]]

^<<v4-29-40,40>>^ E Moisés falou aos filhos de Israel, conforme tudo o que o Senhor  lhe havia ordenado.

'''

xref:004-numeros/004-numeros-028.adoc#v4-28-0[&#60; Capítulo Anterior] | <<v4-29-0,Topo>> | xref:004-numeros/004-numeros-030.adoc#v4-30-0[Próximo Capítulo &#62;]