include::./index.adoc[]

[[v4-22-0]]
=== Números, 22
// naa ?, NAA - Nova Almeida Atualizada

[[v4-22-1]]

^<<v4-22-1,1>>^ Os filhos de Israel partiram e acamparam nas campinas de Moabe, do outro lado do Jordão, na altura de Jericó.

[[v4-22-2]]

^<<v4-22-2,2>>^ Balaque, filho de Zipor, viu tudo o que Israel havia feito aos amorreus.

[[v4-22-3]]

^<<v4-22-3,3>>^ E os moabitas tiveram grande medo deste povo, porque era muito numeroso. E andavam angustiados por causa dos filhos de Israel.

[[v4-22-4]]

^<<v4-22-4,4>>^ Por isso o povo de Moabe disse aos anciãos dos midianitas: — Agora essa multidão vai lamber tudo o que houver ao redor de nós, como o boi lambe a erva do campo. Balaque, filho de Zipor, era o rei dos moabitas naquele tempo.

[[v4-22-5]]

^<<v4-22-5,5>>^ Ele enviou mensageiros a Balaão, filho de Beor, a Petor, que está junto ao rio Eufrates, na terra dos filhos do seu povo, para chamá-lo, dizendo: — Eis que um povo saiu do Egito, cobre a face da terra e está morando perto de mim.

[[v4-22-6]]

^<<v4-22-6,6>>^ Venha agora e, por favor, amaldiçoe este povo, pois eles são mais poderosos do que eu; talvez assim eu possa atacá-los e expulsá-los da terra. Porque sei que a quem você abençoar será abençoado, e a quem você amaldiçoar será amaldiçoado.

[[v4-22-7]]

^<<v4-22-7,7>>^ Então os anciãos dos moabitas e os anciãos dos midianitas foram, levando consigo o dinheiro para pagar os encantamentos. Chegaram ao lugar onde Balaão estava e lhe transmitiram as palavras de Balaque.

[[v4-22-8]]

^<<v4-22-8,8>>^ Balaão lhes disse: — Fiquem aqui esta noite, e lhes trarei a resposta, como o Senhor  me falar. Então os chefes dos moabitas ficaram com Balaão.

[[v4-22-9]]

^<<v4-22-9,9>>^ Deus veio a Balaão e perguntou: — Quem são esses homens que estão com você?

[[v4-22-10]]

^<<v4-22-10,10>>^ Balaão respondeu: — Balaque, rei dos moabitas, filho de Zipor, enviou esses homens para que me dissessem:

[[v4-22-11]]

^<<v4-22-11,11>>^ "Eis que o povo que saiu do Egito cobre a face da terra. Venha agora e amaldiçoe este povo; talvez eu possa combatê-lo e expulsá-lo daqui."

[[v4-22-12]]

^<<v4-22-12,12>>^ Então Deus disse a Balaão: — Não vá com eles, nem amaldiçoe o povo; porque é povo abençoado.

[[v4-22-13]]

^<<v4-22-13,13>>^ Na manhã seguinte Balaão se levantou e disse aos chefes de Balaque: — Voltem para a sua terra, porque o Senhor  não me deixa ir com vocês.

[[v4-22-14]]

^<<v4-22-14,14>>^ Então os chefes dos moabitas se levantaram, foram a Balaque e disseram: — Balaão se recusou a vir conosco.

[[v4-22-15]]

^<<v4-22-15,15>>^ De novo, Balaque enviou chefes, em maior número e mais honrados do que os primeiros.

[[v4-22-16]]

^<<v4-22-16,16>>^ Eles chegaram a Balaão e lhe disseram: — Assim diz Balaque, filho de Zipor: Peço-lhe que não se demore em vir até aqui,

[[v4-22-17]]

^<<v4-22-17,17>>^ porque eu o cobrirei de honras e farei tudo o que você me disser; venha, pois, e, por favor, amaldiçoe este povo.

[[v4-22-18]]

^<<v4-22-18,18>>^ Balaão respondeu aos oficiais de Balaque: — Ainda que Balaque me desse a sua casa cheia de prata e de ouro, eu não poderia transgredir o mandado do Senhor , meu Deus, para fazer coisa pequena ou grande.

[[v4-22-19]]

^<<v4-22-19,19>>^ Agora peço que fiquem aqui também esta noite, para que eu saiba o que mais o Senhor  me dirá.

[[v4-22-20]]

^<<v4-22-20,20>>^ De noite o Senhor  veio a Balaão e lhe disse: — Como aqueles homens vieram chamá-lo, levante-se e vá com eles; mas faça apenas o que eu lhe disser.

[[v4-22-21]]

^<<v4-22-21,21>>^ Balaão levantou-se pela manhã, preparou a sua jumenta e partiu com os chefes de Moabe.

[[v4-22-22]]

^<<v4-22-22,22>>^ Mas acendeu-se a ira de Deus, porque Balaão foi, e o Anjo do Senhor  se pôs por adversário no caminho dele. Ora, Balaão ia montado na sua jumenta, e dois de seus servos iam com ele.

[[v4-22-23]]

^<<v4-22-23,23>>^ A jumenta viu o Anjo do Senhor  parado no caminho, com a sua espada na mão; por isso a jumenta se desviou do caminho, indo pelo campo. Então Balaão espancou a jumenta para fazê-la voltar ao caminho.

[[v4-22-24]]

^<<v4-22-24,24>>^ Mas o Anjo do Senhor  pôs-se num caminho estreito entre as vinhas, havendo muro dos dois lados.

[[v4-22-25]]

^<<v4-22-25,25>>^ Quando a jumenta viu o Anjo do Senhor , encostou-se no muro e apertou o pé de Balaão contra ele. Por isso Balaão tornou a espancá-la.

[[v4-22-26]]

^<<v4-22-26,26>>^ Então o Anjo do Senhor  passou mais adiante e pôs-se num lugar estreito, onde não havia caminho para se desviar nem para a direita nem para a esquerda.

[[v4-22-27]]

^<<v4-22-27,27>>^ Quando a jumenta viu o Anjo do Senhor , deixou-se cair debaixo de Balaão. Balaão ficou irado e espancou a jumenta com uma vara.

[[v4-22-28]]

^<<v4-22-28,28>>^ Então o Senhor  fez a jumenta falar, e ela disse a Balaão: — O que foi que eu fiz a você, para que você me espancasse já três vezes?

[[v4-22-29]]

^<<v4-22-29,29>>^ Balaão respondeu à jumenta: — Foi porque você zombou de mim. Se eu tivesse uma espada na mão, mataria você agora mesmo!

[[v4-22-30]]

^<<v4-22-30,30>>^ A jumenta disse a Balaão: — Não é verdade que eu sou a sua jumenta, em que você tem montado toda a sua vida até hoje? Será que tem sido o meu costume fazer isso com você? Ele respondeu: — Não.

[[v4-22-31]]

^<<v4-22-31,31>>^ Então o Senhor  abriu os olhos a Balaão e ele viu o Anjo do Senhor , que estava no caminho, com a sua espada desembainhada na mão. Por isso Balaão inclinou a cabeça e se prostrou com o rosto em terra.

[[v4-22-32]]

^<<v4-22-32,32>>^ Então o Anjo do Senhor  lhe disse: — Por que você já espancou a sua jumenta três vezes? Eis que eu saí para ser o seu adversário, porque o seu caminho é perverso diante de mim.

[[v4-22-33]]

^<<v4-22-33,33>>^ A jumenta me viu e já três vezes se desviou de mim. Se ela não tivesse se desviado, eu teria matado você e a teria deixado com vida.

[[v4-22-34]]

^<<v4-22-34,34>>^ Então Balaão disse ao Anjo do Senhor : — Pequei, porque não sabia que você estava neste caminho para se opor a mim; agora, se parece mal aos seus olhos seguir viagem, voltarei.

[[v4-22-35]]

^<<v4-22-35,35>>^ O Anjo do Senhor  disse a Balaão: — Vá com esses homens, mas fale somente o que eu lhe disser. Assim, Balaão foi com os chefes de Balaque.

[[v4-22-36]]

^<<v4-22-36,36>>^ Quando Balaque ouviu que Balaão havia chegado, foi ao encontro dele até a cidade de Moabe, que está nos confins do Arnom e na fronteira extrema.

[[v4-22-37]]

^<<v4-22-37,37>>^ Balaque perguntou a Balaão: — Por acaso não mandei mensageiros para chamá-lo? Por que você não veio até aqui? Será que não posso, de fato, cobrir você de honrarias?

[[v4-22-38]]

^<<v4-22-38,38>>^ Balaão respondeu a Balaque: — Eis que estou aqui diante de você. Mas será que poderei, agora, falar alguma coisa? A palavra que Deus puser na minha boca, essa falarei.

[[v4-22-39]]

^<<v4-22-39,39>>^ Balaão foi com Balaque, e chegaram a Quiriate-Huzote.

[[v4-22-40]]

^<<v4-22-40,40>>^ Então Balaque sacrificou bois e ovelhas, e enviou uma parte da carne a Balaão e aos chefes que estavam com ele.

[[v4-22-41]]

^<<v4-22-41,41>>^ Na manhã seguinte, Balaque fez Balaão subir a Bamote-Baal; e dali Balaão viu a parte mais próxima do povo de Israel.

'''

xref:004-numeros/004-numeros-021.adoc#v4-21-0[&#60; Capítulo Anterior] | <<v4-22-0,Topo>> | xref:004-numeros/004-numeros-023.adoc#v4-23-0[Próximo Capítulo &#62;]