include::./index.adoc[]

[[v4-25-0]]
=== Números, 25
// naa ?, NAA - Nova Almeida Atualizada

[[v4-25-1]]

^<<v4-25-1,1>>^ Quando Israel estava em Sitim, o povo começou a prostituir-se com as filhas dos moabitas.

[[v4-25-2]]

^<<v4-25-2,2>>^ Estas convidaram o povo aos sacrifícios oferecidos aos seus deuses; e o povo comeu a carne dos sacrifícios e adorou os deuses dessas mulheres.

[[v4-25-3]]

^<<v4-25-3,3>>^ Assim, quando Israel se juntou ao culto a Baal-Peor, a ira do Senhor  se acendeu contra Israel.

[[v4-25-4]]

^<<v4-25-4,4>>^ O Senhor  disse a Moisés: — Reúna todos os chefes do povo e enforque-os diante do Senhor  ao ar livre, e a ardente ira do Senhor  se afastará de Israel.

[[v4-25-5]]

^<<v4-25-5,5>>^ Então Moisés disse aos juízes de Israel: — Cada um mate os homens da sua tribo que se juntaram a Baal-Peor.

[[v4-25-6]]

^<<v4-25-6,6>>^ Naquele momento, eis que um homem dos filhos de Israel trouxe para a sua tenda uma mulher midianita, à vista de Moisés e de toda a congregação dos filhos de Israel, enquanto eles choravam diante da tenda do encontro.

[[v4-25-7]]

^<<v4-25-7,7>>^ Quando Fineias, filho de Eleazar, filho do sacerdote Arão, viu isso, levantou-se do meio da congregação, e, pegando uma lança,

[[v4-25-8]]

^<<v4-25-8,8>>^ seguiu o homem israelita até o interior da tenda, e, com a lança, atravessou os dois, tanto o homem israelita quanto a mulher midianita, pelo ventre; então a praga cessou entre os filhos de Israel.

[[v4-25-9]]

^<<v4-25-9,9>>^ Os que morreram da praga foram vinte e quatro mil.

[[v4-25-10]]

^<<v4-25-10,10>>^ Então o Senhor  disse a Moisés:

[[v4-25-11]]

^<<v4-25-11,11>>^ — Fineias, filho de Eleazar, filho do sacerdote Arão, desviou a minha ira de sobre os filhos de Israel, pois estava animado com o meu zelo no meio deles, assim que, no meu zelo, não consumi os filhos de Israel.

[[v4-25-12]]

^<<v4-25-12,12>>^ Portanto, diga: Eis que lhe dou a minha aliança de paz.

[[v4-25-13]]

^<<v4-25-13,13>>^ E ele e a sua descendência terão a aliança do sacerdócio perpétuo, porque teve zelo pelo seu Deus e fez expiação pelos filhos de Israel.

[[v4-25-14]]

^<<v4-25-14,14>>^ O nome do israelita que foi morto, isto é, que foi morto com a mulher midianita, era Zinri, filho de Salu, chefe da casa paterna dos simeonitas.

[[v4-25-15]]

^<<v4-25-15,15>>^ O nome da mulher midianita que foi morta era Cosbi, filha de Zur, chefe do povo da casa paterna entre os midianitas.

[[v4-25-16]]

^<<v4-25-16,16>>^ O Senhor  disse a Moisés:

[[v4-25-17]]

^<<v4-25-17,17>>^ — Atormentem e ataquem os midianitas,

[[v4-25-18]]

^<<v4-25-18,18>>^ porque eles atormentaram vocês quando os enganaram no caso de Peor e no caso de Cosbi, filha do chefe dos midianitas, irmã deles, que foi morta no dia da praga no caso de Peor.

'''

xref:004-numeros/004-numeros-024.adoc#v4-24-0[&#60; Capítulo Anterior] | <<v4-25-0,Topo>> | xref:004-numeros/004-numeros-026.adoc#v4-26-0[Próximo Capítulo &#62;]