include::./index.adoc[]

[[v4-30-0]]
=== Números, 30
// naa ?, NAA - Nova Almeida Atualizada

[[v4-30-1]]

^<<v4-30-1,1>>^ Moisés falou aos chefes das tribos dos filhos de Israel, dizendo: — Esta é a palavra que o Senhor  ordenou:

[[v4-30-2]]

^<<v4-30-2,2>>^ Quando um homem fizer um voto ao Senhor  ou juramento para obrigar-se a alguma abstinência, não violará a sua palavra, mas fará segundo tudo o que prometeu.

[[v4-30-3]]

^<<v4-30-3,3>>^ Quando, porém, uma mulher fizer um voto ao Senhor  ou se obrigar a alguma abstinência, estando na casa de seu pai, na sua mocidade,

[[v4-30-4]]

^<<v4-30-4,4>>^ e seu pai, sabendo do voto e da abstinência a que ela se obrigou, não lhe disser nada, todos os seus votos serão válidos; terá de observar toda a abstinência a que se obrigou.

[[v4-30-5]]

^<<v4-30-5,5>>^ Mas, se o pai, no dia em que souber disso, o desaprovar, não será válido nenhum dos votos dela, nem lhe será preciso observar a abstinência a que se obrigou; o Senhor  perdoará isso a ela, porque o pai se opôs.

[[v4-30-6]]

^<<v4-30-6,6>>^ — Porém, se ela casar, ainda sob seus votos ou dito irrefletido dos seus lábios, com que a si mesma obrigou,

[[v4-30-7]]

^<<v4-30-7,7>>^ e seu marido, ouvindo-o, não disser nada no dia em que souber disso, serão válidos os votos dela, e ela terá de observar a abstinência a que se obrigou.

[[v4-30-8]]

^<<v4-30-8,8>>^ Mas, se seu marido o desaprovar no dia em que souber disso e anular o voto que estava sobre ela, bem como o dito irrefletido dos seus lábios, com que a si mesma obrigou, o Senhor  perdoará isso a ela.

[[v4-30-9]]

^<<v4-30-9,9>>^ Quanto ao voto da viúva ou da divorciada, tudo com que se obrigar lhe será válido.

[[v4-30-10]]

^<<v4-30-10,10>>^ — Porém, se ela fez voto na casa de seu marido ou com juramento se obrigou a alguma abstinência,

[[v4-30-11]]

^<<v4-30-11,11>>^ e seu marido o soube, mas não lhe disse nada, e não desaprovou o que ela fez, todos os votos dela serão válidos; e ela terá de observar toda a abstinência a que se obrigou.

[[v4-30-12]]

^<<v4-30-12,12>>^ Porém, se o marido anulou os votos no dia em que ficou sabendo, tudo o que saiu dos lábios dela, quer dos seus votos, quer da abstinência a que se obrigou, não será válido; o marido dela anulou os votos, e o Senhor  perdoará isso a ela.

[[v4-30-13]]

^<<v4-30-13,13>>^ Todo voto e todo juramento com que ela se obrigou, para se humilhar, seu marido pode confirmar ou anular.

[[v4-30-14]]

^<<v4-30-14,14>>^ Porém, se o marido, dia após dia, não disser nada, então confirma todos os votos dela e tudo aquilo a que ela se obrigou, porque não disse nada no dia em que ficou sabendo.

[[v4-30-15]]

^<<v4-30-15,15>>^ Porém, se ele anular os votos algum tempo depois de os ter ouvido, levará sobre si a iniquidade dela.

[[v4-30-16]]

^<<v4-30-16,16>>^ São estes os estatutos que o Senhor  ordenou a Moisés a respeito do marido e sua mulher, e a respeito do pai e sua filha moça, se ela estiver na casa de seu pai.

'''

xref:004-numeros/004-numeros-029.adoc#v4-29-0[&#60; Capítulo Anterior] | <<v4-30-0,Topo>> | xref:004-numeros/004-numeros-031.adoc#v4-31-0[Próximo Capítulo &#62;]