include::./index.adoc[]

[[v4-20-0]]
=== Números, 20
// naa ?, NAA - Nova Almeida Atualizada

[[v4-20-1]]

^<<v4-20-1,1>>^ Toda a congregação dos filhos de Israel chegou ao deserto de Zim, no primeiro mês, e o povo ficou em Cades. Ali Miriã morreu e ali ela foi sepultada.

[[v4-20-2]]

^<<v4-20-2,2>>^ Não havia água para o povo. Então se ajuntaram contra Moisés e contra Arão.

[[v4-20-3]]

^<<v4-20-3,3>>^ E o povo discutiu com Moisés, dizendo: — Antes tivéssemos morrido quando os nossos irmãos morreram diante do Senhor !

[[v4-20-4]]

^<<v4-20-4,4>>^ Por que vocês trouxeram a congregação do Senhor  a este deserto, para morrermos aqui, nós e os nossos animais?

[[v4-20-5]]

^<<v4-20-5,5>>^ E por que vocês nos tiraram do Egito, para nos trazer a este lugar horrível, onde não há cereais, nem figos, nem vinhas, nem romãs, nem água para beber?

[[v4-20-6]]

^<<v4-20-6,6>>^ Então Moisés e Arão saíram da presença do povo e foram para a porta da tenda do encontro e se lançaram sobre o seu rosto; e a glória do Senhor  lhes apareceu.

[[v4-20-7]]

^<<v4-20-7,7>>^ O Senhor  disse a Moisés:

[[v4-20-8]]

^<<v4-20-8,8>>^ — Pegue o seu bordão e ajunte o povo, você e Arão, o seu irmão. E, diante do povo, falem à rocha, e ela dará a sua água. Assim vocês tirarão água da rocha e darão de beber à congregação e aos animais.

[[v4-20-9]]

^<<v4-20-9,9>>^ Então Moisés pegou o bordão que estava diante do Senhor , como este lhe havia ordenado.

[[v4-20-10]]

^<<v4-20-10,10>>^ Moisés e Arão reuniram o povo diante da rocha. Então Moisés lhes disse: — Agora escutem, rebeldes! Será que teremos de fazer com que saia água desta rocha para vocês?

[[v4-20-11]]

^<<v4-20-11,11>>^ Moisés levantou a mão e feriu a rocha duas vezes com o seu bordão, e saíram muitas águas; e a congregação e os seus animais beberam.

[[v4-20-12]]

^<<v4-20-12,12>>^ Mas o Senhor  disse a Moisés e a Arão: — Porque não creram em mim, para me santificarem diante dos filhos de Israel, vocês não farão entrar este povo na terra que lhe dei.

[[v4-20-13]]

^<<v4-20-13,13>>^ São estas as águas de Meribá, porque os filhos de Israel discutiram com o Senhor ; e o Senhor  se santificou neles.

[[v4-20-14]]

^<<v4-20-14,14>>^ De Cades, Moisés enviou mensageiros ao rei de Edom, para dizer-lhe: — Assim diz o seu irmão Israel: Você conhece todas as aflições que nos sobrevieram.

[[v4-20-15]]

^<<v4-20-15,15>>^ Sabe como os nossos pais desceram ao Egito, e nós moramos no Egito muito tempo, e como os egípcios nos maltrataram, a nós e aos nossos pais.

[[v4-20-16]]

^<<v4-20-16,16>>^ Clamamos ao Senhor , e ele ouviu a nossa voz; mandou o Anjo e nos tirou do Egito. E eis que estamos em Cades, cidade nos confins do seu país.

[[v4-20-17]]

^<<v4-20-17,17>>^ Deixe-nos passar pela sua terra. Não passaremos pelo campo, nem pelas vinhas, nem beberemos a água dos poços. Iremos pela estrada real. Não nos desviaremos para a direita nem para a esquerda, até que passemos pelo seu país.

[[v4-20-18]]

^<<v4-20-18,18>>^ Porém o rei de Edom respondeu: — Não passem por aqui! Se o fizerem, sairei com a espada ao encontro de vocês.

[[v4-20-19]]

^<<v4-20-19,19>>^ Então os filhos de Israel lhe disseram: — Passaremos pelo caminho principal, e, se nós e o nosso gado bebermos das águas de vocês, pagaremos o preço delas. Não queremos outra coisa a não ser passar a pé.

[[v4-20-20]]

^<<v4-20-20,20>>^ Mas o rei de Edom respondeu: — Vocês não podem passar! E o rei de Edom veio ao encontro deles, com muita gente e com mão forte.

[[v4-20-21]]

^<<v4-20-21,21>>^ Assim os edomitas se recusaram a deixar Israel passar pelo seu país, e por isso Israel se desviou dali.

[[v4-20-22]]

^<<v4-20-22,22>>^ Então partiram de Cades, e os filhos de Israel, toda a congregação, foram ao monte Hor.

[[v4-20-23]]

^<<v4-20-23,23>>^ O Senhor  disse a Moisés e a Arão no monte Hor, nos confins da terra de Edom:

[[v4-20-24]]

^<<v4-20-24,24>>^ — Arão será reunido ao seu povo, porque não entrará na terra que dei aos filhos de Israel, pois vocês foram rebeldes à minha palavra, nas águas de Meribá.

[[v4-20-25]]

^<<v4-20-25,25>>^ Chame Arão e Eleazar, o filho dele, e diga-lhes que subam o monte Hor.

[[v4-20-26]]

^<<v4-20-26,26>>^ Depois tire as vestes sacerdotais de Arão e coloque-as em Eleazar, o filho dele; porque Arão será reunido ao seu povo e ali morrerá.

[[v4-20-27]]

^<<v4-20-27,27>>^ Moisés fez como o Senhor  lhe havia ordenado. Subiram o monte Hor, diante dos olhos de toda a congregação.

[[v4-20-28]]

^<<v4-20-28,28>>^ Moisés tirou as vestes sacerdotais de Arão e as pôs em Eleazar, o filho dele. E Arão morreu ali, no alto do monte. Depois disso Moisés e Eleazar desceram do monte.

[[v4-20-29]]

^<<v4-20-29,29>>^ Quando toda a congregação soube que Arão era morto, toda a casa de Israel chorou por Arão durante trinta dias.

'''

xref:004-numeros/004-numeros-019.adoc#v4-19-0[&#60; Capítulo Anterior] | <<v4-20-0,Topo>> | xref:004-numeros/004-numeros-021.adoc#v4-21-0[Próximo Capítulo &#62;]