include::./index.adoc[]

[[v4-27-0]]
=== Números, 27
// naa ?, NAA - Nova Almeida Atualizada

[[v4-27-1]]

^<<v4-27-1,1>>^ Então vieram as filhas de Zelofeade, filho de Héfer, filho de Gileade, filho de Maquir, filho de Manassés, entre as famílias de Manassés, filho de José. E são estes os nomes delas: Macla, Noa, Hogla, Milca e Tirza.

[[v4-27-2]]

^<<v4-27-2,2>>^ Elas se apresentaram diante de Moisés, diante do sacerdote Eleazar, diante dos chefes e diante de todo o povo, à porta da tenda do encontro, dizendo:

[[v4-27-3]]

^<<v4-27-3,3>>^ — Nosso pai morreu no deserto e não estava entre os que se ajuntaram contra o Senhor  no grupo de Corá; mas morreu por causa do seu próprio pecado e não teve nenhum filho homem.

[[v4-27-4]]

^<<v4-27-4,4>>^ Por que se tiraria o nome de nosso pai do meio da sua família, só porque não teve filhos? Dê-nos uma herança entre os parentes de nosso pai.

[[v4-27-5]]

^<<v4-27-5,5>>^ Moisés apresentou a causa delas ao Senhor .

[[v4-27-6]]

^<<v4-27-6,6>>^ E o Senhor  disse a Moisés:

[[v4-27-7]]

^<<v4-27-7,7>>^ — As filhas de Zelofeade estão pedindo o que é justo. Certamente você deve dar-lhes propriedade como herança entre os parentes do pai delas e deverá transferir a elas a herança do pai.

[[v4-27-8]]

^<<v4-27-8,8>>^ E diga aos filhos de Israel: Se alguém morrer e não tiver filho, passem a herança dele para a sua filha.

[[v4-27-9]]

^<<v4-27-9,9>>^ E, se não tiver filha, deem a herança aos irmãos dele.

[[v4-27-10]]

^<<v4-27-10,10>>^ Porém, se não tiver irmãos, deem a herança aos irmãos do pai dele.

[[v4-27-11]]

^<<v4-27-11,11>>^ Se também o pai não tiver irmãos, deem a herança ao parente mais chegado de sua família, para que tome posse dela. Isto será prescrição de direito aos filhos de Israel, como o Senhor  ordenou a Moisés.

[[v4-27-12]]

^<<v4-27-12,12>>^ Depois, o Senhor  disse a Moisés: — Suba a este monte Abarim e veja a terra que dei aos filhos de Israel.

[[v4-27-13]]

^<<v4-27-13,13>>^ E, depois de a ter visto, você também será reunido ao seu povo, assim como já aconteceu com o seu irmão Arão.

[[v4-27-14]]

^<<v4-27-14,14>>^ Porque, no deserto de Zim, quando a congregação discutia comigo, vocês foram rebeldes ao meu mandado de me santificar nas águas diante dos olhos do povo. São estas as águas de Meribá de Cades, no deserto de Zim.

[[v4-27-15]]

^<<v4-27-15,15>>^ Então Moisés disse ao Senhor :

[[v4-27-16]]

^<<v4-27-16,16>>^ — Que o Senhor , autor e conservador de toda vida, ponha um homem sobre esta congregação

[[v4-27-17]]

^<<v4-27-17,17>>^ que saia adiante deles, que entre adiante deles, que os faça sair e que os faça entrar, para que a congregação do Senhor  não seja como ovelhas que não têm pastor.

[[v4-27-18]]

^<<v4-27-18,18>>^ O Senhor  disse a Moisés: — Chame Josué, filho de Num, homem em quem há o Espírito, e imponha as mãos sobre ele.

[[v4-27-19]]

^<<v4-27-19,19>>^ Apresente-o ao sacerdote Eleazar e a toda a congregação, e, à vista de todos, transmita-lhe as suas ordens.

[[v4-27-20]]

^<<v4-27-20,20>>^ Ponha sobre ele uma parte da sua autoridade, para que toda a congregação dos filhos de Israel obedeça a ele.

[[v4-27-21]]

^<<v4-27-21,21>>^ Josué deverá se apresentar diante de Eleazar, o sacerdote, o qual por ele consultará o Senhor , de acordo com o juízo do Urim. Segundo a palavra do sacerdote, sairão e, segundo a sua palavra, entrarão, ele, e todos os filhos de Israel com ele, e toda a congregação.

[[v4-27-22]]

^<<v4-27-22,22>>^ Moisés fez como o Senhor  lhe havia ordenado: chamou Josué e o apresentou ao sacerdote Eleazar e a toda a congregação;

[[v4-27-23]]

^<<v4-27-23,23>>^ impôs as mãos sobre ele e lhe deu as suas ordens, como o Senhor  havia falado por meio de Moisés.

'''

xref:004-numeros/004-numeros-026.adoc#v4-26-0[&#60; Capítulo Anterior] | <<v4-27-0,Topo>> | xref:004-numeros/004-numeros-028.adoc#v4-28-0[Próximo Capítulo &#62;]