include::./index.adoc[]

[[v4-14-0]]
=== Números, 14
// naa ?, NAA - Nova Almeida Atualizada

[[v4-14-1]]

^<<v4-14-1,1>>^ Então toda a congregação se levantou e gritou em alta voz; e o povo chorou aquela noite.

[[v4-14-2]]

^<<v4-14-2,2>>^ Todos os filhos de Israel murmuraram contra Moisés e contra Arão; e toda a congregação lhes disse: — Quem dera tivéssemos morrido na terra do Egito ou mesmo neste deserto!

[[v4-14-3]]

^<<v4-14-3,3>>^ E por que o Senhor  nos traz a esta terra, para cairmos à espada e para que nossas mulheres e nossas crianças sejam por presa? Não seria melhor voltarmos para o Egito?

[[v4-14-4]]

^<<v4-14-4,4>>^ E diziam uns aos outros: — Vamos escolher um chefe e voltemos para o Egito.

[[v4-14-5]]

^<<v4-14-5,5>>^ Então Moisés e Arão caíram sobre o seu rosto diante da congregação dos filhos de Israel.

[[v4-14-6]]

^<<v4-14-6,6>>^ E Josué, filho de Num, e Calebe, filho de Jefoné, que eram daqueles que espiaram a terra, rasgaram as suas roupas

[[v4-14-7]]

^<<v4-14-7,7>>^ e falaram a toda a congregação dos filhos de Israel, dizendo: — A terra pela qual passamos para espiar é terra muitíssimo boa.

[[v4-14-8]]

^<<v4-14-8,8>>^ Se o Senhor  se agradar de nós, então nos fará entrar e nos dará essa terra, que é uma terra que mana leite e mel.

[[v4-14-9]]

^<<v4-14-9,9>>^ Tão somente não sejam rebeldes contra o Senhor  e não tenham medo do povo dessa terra, porque, como pão, os podemos devorar; a proteção que eles tinham se foi. O Senhor  está conosco; não tenham medo deles.

[[v4-14-10]]

^<<v4-14-10,10>>^ Apesar disso, toda a congregação disse que Josué e Calebe deviam ser apedrejados; porém a glória do Senhor  apareceu na tenda do encontro a todos os filhos de Israel.

[[v4-14-11]]

^<<v4-14-11,11>>^ O Senhor  disse a Moisés: — Até quando este povo me provocará e até quando não crerá em mim, apesar de todos os sinais que fiz no meio dele?

[[v4-14-12]]

^<<v4-14-12,12>>^ Vou feri-lo com pestilência e deserdá-lo; e farei de você povo maior e mais forte do que este.

[[v4-14-13]]

^<<v4-14-13,13>>^ Moisés respondeu ao Senhor : — Os egípcios não somente ouviram que, com o teu poder, fizeste este povo sair do meio deles,

[[v4-14-14]]

^<<v4-14-14,14>>^ mas também o disseram aos moradores desta terra. Eles ouviram que tu, ó Senhor , estás no meio deste povo, que face a face, ó Senhor , lhes apareces, tua nuvem está sobre eles e vais adiante deles numa coluna de nuvem, de dia, e, numa coluna de fogo, de noite.

[[v4-14-15]]

^<<v4-14-15,15>>^ Se matares este povo de uma só vez, as nações, que antes ouviram a tua fama, dirão:

[[v4-14-16]]

^<<v4-14-16,16>>^ "Visto que o Senhor  não conseguiu fazer este povo entrar na terra que lhe prometeu com juramento, matou-os no deserto."

[[v4-14-17]]

^<<v4-14-17,17>>^ Agora, pois, peço que a força do meu Senhor se engrandeça, como tens falado, dizendo:

[[v4-14-18]]

^<<v4-14-18,18>>^ "O Senhor  é tardio em irar-se e rico em bondade; ele perdoa a iniquidade e a transgressão, mas não inocenta o culpado, e visita a iniquidade dos pais nos filhos até a terceira e a quarta geração."

[[v4-14-19]]

^<<v4-14-19,19>>^ Perdoa, pois, a iniquidade deste povo, segundo a grandeza da tua misericórdia e como também tens perdoado a este povo desde a terra do Egito até aqui.

[[v4-14-20]]

^<<v4-14-20,20>>^ O Senhor  respondeu: — Conforme você me pediu, eu perdoei.

[[v4-14-21]]

^<<v4-14-21,21>>^ Porém, tão certo como eu vivo, e como toda a terra se encherá da glória do Senhor ,

[[v4-14-22]]

^<<v4-14-22,22>>^ nenhum dos homens que viram a minha glória e os prodígios que fiz no Egito e no deserto e, mesmo assim me puseram à prova já dez vezes e não obedeceram à minha voz,

[[v4-14-23]]

^<<v4-14-23,23>>^ nenhum deles verá a terra que, com juramento, prometi a seus pais; sim, nenhum daqueles que me desprezaram a verá.

[[v4-14-24]]

^<<v4-14-24,24>>^ Porém o meu servo Calebe, visto que nele houve outro espírito, e perseverou em seguir-me, eu o farei entrar na terra que espiou, e a sua descendência a possuirá.

[[v4-14-25]]

^<<v4-14-25,25>>^ Ora, os amalequitas e os cananeus habitam no vale; portanto, amanhã mudem de rumo e caminhem para o deserto, pelo caminho do mar Vermelho.

[[v4-14-26]]

^<<v4-14-26,26>>^ Depois, o Senhor  disse a Moisés e a Arão:

[[v4-14-27]]

^<<v4-14-27,27>>^ — Até quando vou aguentar esta má congregação que murmura contra mim? Tenho ouvido as murmurações que os filhos de Israel proferem contra mim.

[[v4-14-28]]

^<<v4-14-28,28>>^ Diga-lhes: "Tão certo como eu vivo, diz o Senhor , vou tratar vocês de acordo com o que falaram aos meus ouvidos.

[[v4-14-29]]

^<<v4-14-29,29>>^ Neste deserto, cairá o cadáver de vocês — de todos vocês que foram contados no censo, de vinte anos para cima, e que murmuraram contra mim.

[[v4-14-30]]

^<<v4-14-30,30>>^ Vocês não entrarão na terra na qual jurei que os faria habitar, com a exceção de Calebe, filho de Jefoné, e Josué, filho de Num.

[[v4-14-31]]

^<<v4-14-31,31>>^ Mas os seus filhos, dos quais vocês dizem que serão por presa, esses eu farei entrar nela; e eles conhecerão a terra que vocês desprezaram.

[[v4-14-32]]

^<<v4-14-32,32>>^ Porém, quanto a vocês, o seu cadáver cairá neste deserto.

[[v4-14-33]]

^<<v4-14-33,33>>^ Os filhos de vocês serão pastores neste deserto durante quarenta anos e levarão sobre si as infidelidades de vocês, até que o cadáver de vocês se consuma neste deserto.

[[v4-14-34]]

^<<v4-14-34,34>>^ Segundo o número dos dias em que vocês espiaram a terra, quarenta dias, cada dia representando um ano, vocês levarão sobre si as suas iniquidades durante quarenta anos e terão experiência do meu desagrado.

[[v4-14-35]]

^<<v4-14-35,35>>^ Eu, o Senhor , falei. Assim farei a toda esta má congregação, que se levantou contra mim; neste deserto, se consumirão e aí morrerão."

[[v4-14-36]]

^<<v4-14-36,36>>^ Os homens que Moisés havia mandado para espiar a terra e que, voltando, fizeram murmurar toda a congregação contra ele, falando mal da terra,

[[v4-14-37]]

^<<v4-14-37,37>>^ esses mesmos homens que falaram mal da terra morreram de praga diante do Senhor .

[[v4-14-38]]

^<<v4-14-38,38>>^ Mas Josué, filho de Num, e Calebe, filho de Jefoné, que eram dos homens que foram espiar a terra, sobreviveram.

[[v4-14-39]]

^<<v4-14-39,39>>^ Moisés falou estas palavras a todos os filhos de Israel, e o povo ficou muito triste.

[[v4-14-40]]

^<<v4-14-40,40>>^ Levantaram-se de manhã cedo e subiram ao alto do monte, dizendo: — Aqui estamos e subiremos ao lugar que o Senhor  nos prometeu, porque pecamos.

[[v4-14-41]]

^<<v4-14-41,41>>^ Porém Moisés respondeu: — Por que vocês estão transgredindo o mandado do Senhor ? Isso não prosperará.

[[v4-14-42]]

^<<v4-14-42,42>>^ Não vão, porque o Senhor  não estará no meio de vocês, e vocês serão derrotados pelos seus inimigos.

[[v4-14-43]]

^<<v4-14-43,43>>^ Porque os amalequitas e os cananeus estão logo ali adiante, e vocês cairão à espada. Uma vez que se desviaram do Senhor , o Senhor  não estará com vocês.

[[v4-14-44]]

^<<v4-14-44,44>>^ Contudo, eles teimaram em querer entrar na região montanhosa. No entanto, a arca da aliança do Senhor  e Moisés não saíram do meio do arraial.

[[v4-14-45]]

^<<v4-14-45,45>>^ Então os amalequitas e os cananeus que habitavam na região montanhosa desceram e os atacaram, derrotando-os até Horma.

'''

xref:004-numeros/004-numeros-013.adoc#v4-13-0[&#60; Capítulo Anterior] | <<v4-14-0,Topo>> | xref:004-numeros/004-numeros-015.adoc#v4-15-0[Próximo Capítulo &#62;]