include::./index.adoc[]

[[v4-36-0]]
=== Números, 36
// naa ?, NAA - Nova Almeida Atualizada

[[v4-36-1]]

^<<v4-36-1,1>>^ Os cabeças das casas paternas da família dos filhos de Gileade, filho de Maquir, filho de Manassés, das famílias dos filhos de José, foram falar com Moisés e com os chefes, cabeças das casas paternas dos filhos de Israel.

[[v4-36-2]]

^<<v4-36-2,2>>^ Eles disseram: — O Senhor  Deus ordenou a meu senhor que, por sorteio, dê esta terra em herança aos filhos de Israel; e a meu senhor foi ordenado pelo Senhor  Deus que a herança do nosso irmão Zelofeade fosse dada às filhas dele.

[[v4-36-3]]

^<<v4-36-3,3>>^ Porém, se elas casarem com algum dos filhos das outras tribos dos filhos de Israel, a herança delas seria diminuída da herança de nossos pais e acrescentada à herança da tribo a que vierem pertencer. Assim, seria tirada uma parte da herança que nos coube por sorteio.

[[v4-36-4]]

^<<v4-36-4,4>>^ E, quando chegar o Ano do Jubileu dos filhos de Israel, a herança delas será acrescentada à herança da tribo daqueles a que vierem pertencer. Assim, a herança delas será tirada da tribo de nossos pais.

[[v4-36-5]]

^<<v4-36-5,5>>^ Então Moisés deu ordem aos filhos de Israel, segundo o mandado do Senhor , dizendo: — A tribo dos filhos de José está pedindo o que é justo.

[[v4-36-6]]

^<<v4-36-6,6>>^ Esta é a palavra que o Senhor  deu a respeito das filhas de Zelofeade, dizendo: Elas podem casar com quem quiserem, desde que se casem na família da tribo do pai delas.

[[v4-36-7]]

^<<v4-36-7,7>>^ Assim, a herança dos filhos de Israel não passará de uma tribo a outra. Pois os filhos de Israel devem ficar vinculados cada um à herança da tribo de seus pais.

[[v4-36-8]]

^<<v4-36-8,8>>^ Qualquer filha que possuir alguma herança das tribos dos filhos de Israel deverá casar com alguém da família da tribo de seu pai, para que os filhos de Israel possuam cada um a herança de seus pais.

[[v4-36-9]]

^<<v4-36-9,9>>^ Assim, a herança não passará de uma tribo a outra; pois as tribos dos filhos de Israel devem ficar vinculadas cada uma à sua herança.

[[v4-36-10]]

^<<v4-36-10,10>>^ Como o Senhor  havia ordenado a Moisés, assim fizeram as filhas de Zelofeade,

[[v4-36-11]]

^<<v4-36-11,11>>^ pois Macla, Tirza, Hogla, Milca e Noa, filhas de Zelofeade, casaram com filhos de seus tios paternos.

[[v4-36-12]]

^<<v4-36-12,12>>^ Casaram nas famílias dos filhos de Manassés, filho de José, e a herança delas permaneceu na tribo da família de seu pai.

[[v4-36-13]]

^<<v4-36-13,13>>^ São estes os mandamentos e os juízos que o Senhor , por meio de Moisés, ordenou aos filhos de Israel nas campinas de Moabe, junto ao Jordão, na altura de Jericó.

'''

xref:004-numeros/004-numeros-035.adoc#v4-35-0[&#60; Capítulo Anterior] | <<v4-36-0,Topo>> | xref:005-deuteronomio/005-deuteronomio-001.adoc#v5-1-0[Próximo Capítulo &#62;]