include::./index.adoc[]

[[v4-17-0]]
=== Números, 17
// naa ?, NAA - Nova Almeida Atualizada

[[v4-17-1]]

^<<v4-17-1,1>>^ O Senhor  disse a Moisés:

[[v4-17-2]]

^<<v4-17-2,2>>^ — Fale aos filhos de Israel e receba deles bordões, um pela casa de cada pai de todos os seus chefes, segundo as casas de seus pais, isto é, doze bordões; escreva o nome de cada um sobre o seu bordão.

[[v4-17-3]]

^<<v4-17-3,3>>^ Porém o nome de Arão você escreverá sobre o bordão de Levi; porque cada cabeça da casa de seus pais terá um bordão.

[[v4-17-4]]

^<<v4-17-4,4>>^ Ponha esses bordões na tenda do encontro, diante da arca do testemunho, onde eu me encontro com vocês.

[[v4-17-5]]

^<<v4-17-5,5>>^ O bordão do homem que eu escolher, esse florescerá; assim, farei cessar as murmurações que os filhos de Israel proferem contra vocês.

[[v4-17-6]]

^<<v4-17-6,6>>^ Então Moisés falou aos filhos de Israel, e todos os seus chefes lhe deram bordões; cada um lhe deu um, segundo as casas de seus pais: doze bordões; e, entre eles, estava o bordão de Arão.

[[v4-17-7]]

^<<v4-17-7,7>>^ Moisés pôs estes bordões diante do Senhor , na tenda do testemunho.

[[v4-17-8]]

^<<v4-17-8,8>>^ No dia seguinte, Moisés entrou na tenda do testemunho, e eis que o bordão de Arão, pela casa de Levi, havia brotado, e, tendo feito sair brotos, havia produzido flores e dava amêndoas.

[[v4-17-9]]

^<<v4-17-9,9>>^ Então Moisés trouxe todos os bordões de diante do Senhor  a todos os filhos de Israel; e eles olharam, e cada um pegou o seu bordão.

[[v4-17-10]]

^<<v4-17-10,10>>^ O Senhor  disse a Moisés: — Torne a pôr o bordão de Arão diante da arca do testemunho, para que se guarde por sinal para filhos rebeldes. Assim você fará acabar as murmurações que eles proferem contra mim, para que não morram.

[[v4-17-11]]

^<<v4-17-11,11>>^ E Moisés fez assim. Como o Senhor  lhe havia ordenado, assim fez.

[[v4-17-12]]

^<<v4-17-12,12>>^ Então os filhos de Israel disseram a Moisés: — Eis que vamos morrer! Estamos perdidos! Estamos todos perdidos!

[[v4-17-13]]

^<<v4-17-13,13>>^ Todo aquele que se aproximar do tabernáculo do Senhor  morrerá. Será que todos vamos morrer?

'''

xref:004-numeros/004-numeros-016.adoc#v4-16-0[&#60; Capítulo Anterior] | <<v4-17-0,Topo>> | xref:004-numeros/004-numeros-018.adoc#v4-18-0[Próximo Capítulo &#62;]