include::./index.adoc[]

[[v4-35-0]]
=== Números, 35
// naa ?, NAA - Nova Almeida Atualizada

[[v4-35-1]]

^<<v4-35-1,1>>^ Nas campinas de Moabe, junto ao Jordão, na altura de Jericó, o Senhor  disse a Moisés:

[[v4-35-2]]

^<<v4-35-2,2>>^ — Ordene aos filhos de Israel que, da herança da sua posse, deem cidades aos levitas, em que possam morar, e também campos de pastagem ao redor das cidades.

[[v4-35-3]]

^<<v4-35-3,3>>^ Os levitas terão essas cidades para morar nelas. Os campos de pastagem ao redor das cidades serão para o gado, para os rebanhos e para todos os animais deles.

[[v4-35-4]]

^<<v4-35-4,4>>^ Os campos de pastagem ao redor das cidades que vocês darão aos levitas, desde a muralha da cidade para fora, serão de quatrocentos e cinquenta metros ao redor.

[[v4-35-5]]

^<<v4-35-5,5>>^ Fora da cidade, do lado leste, vocês devem medir novecentos metros; do lado sul, novecentos metros; do lado oeste, novecentos metros e do lado norte, novecentos metros, ficando a cidade no meio; estes lhes serão os campos de pastagem ao redor das cidades.

[[v4-35-6]]

^<<v4-35-6,6>>^ — Das cidades que vocês darão aos levitas, seis serão cidades de refúgio, as quais vocês darão para que, nelas, se acolha o homicida. Além destas, vocês darão aos levitas quarenta e duas cidades.

[[v4-35-7]]

^<<v4-35-7,7>>^ Todas as cidades que vocês darão aos levitas serão quarenta e oito cidades, juntamente com os campos de pastagem.

[[v4-35-8]]

^<<v4-35-8,8>>^ As cidades que vocês darão aos levitas devem ser da herança dos filhos de Israel. Se a tribo for numerosa, dará muitas cidades; se a tribo for pequena, dará poucas cidades; cada tribo dará das suas cidades aos levitas, na proporção da herança que lhe couber.

[[v4-35-9]]

^<<v4-35-9,9>>^ O Senhor  disse ainda a Moisés:

[[v4-35-10]]

^<<v4-35-10,10>>^ — Fale com os filhos de Israel e diga-lhes: Quando passarem o Jordão para entrar na terra de Canaã,

[[v4-35-11]]

^<<v4-35-11,11>>^ escolham para vocês algumas cidades que lhes sirvam de refúgio, para que, nelas, se acolha o homicida que matar alguém involuntariamente.

[[v4-35-12]]

^<<v4-35-12,12>>^ Nessas cidades o homicida poderá se refugiar do vingador do sangue, para que o homicida não morra antes de ser apresentado diante da congregação para julgamento.

[[v4-35-13]]

^<<v4-35-13,13>>^ Essas cidades que vocês derem serão seis cidades de refúgio para vocês.

[[v4-35-14]]

^<<v4-35-14,14>>^ Três destas cidades devem ficar deste lado do Jordão e três devem ficar na terra de Canaã; serão cidades de refúgio.

[[v4-35-15]]

^<<v4-35-15,15>>^ Estas seis cidades serão de refúgio para os filhos de Israel, e para o estrangeiro, e para o que se hospedar no meio deles, para que, nelas, se acolha aquele que matar alguém involuntariamente.

[[v4-35-16]]

^<<v4-35-16,16>>^ — Mas, se alguém ferir uma pessoa com instrumento de ferro, e essa pessoa morrer, é homicida; o homicida será morto.

[[v4-35-17]]

^<<v4-35-17,17>>^ Ou se alguém ferir uma pessoa, com pedra na mão, que possa causar a morte, e essa pessoa morrer, é homicida; o homicida será morto.

[[v4-35-18]]

^<<v4-35-18,18>>^ Ou se alguém ferir uma pessoa com instrumento de pau que tiver na mão, que possa causar a morte, e essa pessoa morrer, é homicida; o homicida será morto.

[[v4-35-19]]

^<<v4-35-19,19>>^ O vingador do sangue, ao encontrar o homicida, deverá matá-lo.

[[v4-35-20]]

^<<v4-35-20,20>>^ — Se alguém empurrar uma pessoa com ódio ou com má intenção lançar contra ela alguma coisa, e essa pessoa morrer,

[[v4-35-21]]

^<<v4-35-21,21>>^ ou, por inimizade, a ferir com a mão, e essa pessoa vier a morrer, aquele que feriu essa pessoa será morto; é homicida; o vingador do sangue, ao encontrar o homicida, deverá matá-lo.

[[v4-35-22]]

^<<v4-35-22,22>>^ Porém, se alguém empurrar outra pessoa subitamente, sem inimizade, ou contra ela lançar algum instrumento, sem má intenção,

[[v4-35-23]]

^<<v4-35-23,23>>^ ou, sem vê-la, deixar cair sobre ela alguma pedra que possa causar-lhe a morte, e essa pessoa morrer, não sendo sua inimiga, nem tendo a intenção de causar-lhe mal,

[[v4-35-24]]

^<<v4-35-24,24>>^ então a congregação julgará entre o matador e o vingador do sangue, segundo estas leis,

[[v4-35-25]]

^<<v4-35-25,25>>^ e livrará o homicida da mão do vingador do sangue, e o fará voltar à sua cidade de refúgio, onde havia se refugiado; ali, ficará até a morte do sumo sacerdote, que foi ungido com o santo óleo.

[[v4-35-26]]

^<<v4-35-26,26>>^ — Porém, se, em determinado momento, o homicida sair dos limites da sua cidade de refúgio, onde tinha se refugiado,

[[v4-35-27]]

^<<v4-35-27,27>>^ e o vingador do sangue o encontrar fora dos limites dela, se o vingador do sangue matar o homicida, não será culpado do sangue.

[[v4-35-28]]

^<<v4-35-28,28>>^ Pois deve ficar na sua cidade de refúgio até a morte do sumo sacerdote; porém, depois da morte deste, o homicida voltará à terra da sua posse.

[[v4-35-29]]

^<<v4-35-29,29>>^ Estas coisas serão por estatuto de direito para vocês de geração em geração, onde quer que vocês morarem.

[[v4-35-30]]

^<<v4-35-30,30>>^ — Todo aquele que matar uma pessoa será morto conforme o depoimento das testemunhas; mas uma só testemunha não deporá contra alguém para que morra.

[[v4-35-31]]

^<<v4-35-31,31>>^ Não aceitem resgate pela vida do homicida que é culpado de morte; ele deve ser morto.

[[v4-35-32]]

^<<v4-35-32,32>>^ Também não aceitem resgate por aquele que se acolher a uma cidade de refúgio e quiser voltar para a sua terra antes da morte do sumo sacerdote.

[[v4-35-33]]

^<<v4-35-33,33>>^ Assim, não profanem a terra em que vocês estão; porque o sangue profana a terra. Nenhuma expiação se fará pela terra por causa do sangue que nela for derramado, a não ser com o sangue daquele que o derramou.

[[v4-35-34]]

^<<v4-35-34,34>>^ Portanto, não contaminem a terra na qual vocês vivem, no meio da qual eu habito; pois eu, o Senhor , habito no meio dos filhos de Israel.

'''

xref:004-numeros/004-numeros-034.adoc#v4-34-0[&#60; Capítulo Anterior] | <<v4-35-0,Topo>> | xref:004-numeros/004-numeros-036.adoc#v4-36-0[Próximo Capítulo &#62;]