include::./index.adoc[]

[[v4-5-0]]
=== Números, 5
// naa ?, NAA - Nova Almeida Atualizada

[[v4-5-1]]

^<<v4-5-1,1>>^ O Senhor  disse a Moisés:

[[v4-5-2]]

^<<v4-5-2,2>>^ — Ordene aos filhos de Israel que expulsem do arraial todo leproso, todo o que tiver um fluxo e todo impuro por ter tocado em algum morto.

[[v4-5-3]]

^<<v4-5-3,3>>^ Tanto homem como mulher devem ser expulsos do arraial, para que não contaminem o arraial, no meio do qual eu habito.

[[v4-5-4]]

^<<v4-5-4,4>>^ Os filhos de Israel fizeram assim e os expulsaram do arraial. Como o Senhor  havia falado a Moisés, assim fizeram os filhos de Israel.

[[v4-5-5]]

^<<v4-5-5,5>>^ O Senhor  disse ainda a Moisés:

[[v4-5-6]]

^<<v4-5-6,6>>^ — Diga aos filhos de Israel: Quando um homem ou uma mulher cometer algum dos pecados que as pessoas cometem, ofendendo ao Senhor , tal pessoa é culpada.

[[v4-5-7]]

^<<v4-5-7,7>>^ Confessará o pecado que cometer e, pela culpa, fará plena restituição, lhe acrescentará a sua quinta parte, e dará tudo àquele contra quem se fez culpado.

[[v4-5-8]]

^<<v4-5-8,8>>^ Mas, se esse homem não tiver parente chegado, a quem possa fazer restituição pela culpa, então o que se restitui ao Senhor  pela culpa será do sacerdote, além do carneiro expiatório com que se fizer expiação pelo culpado.

[[v4-5-9]]

^<<v4-5-9,9>>^ Toda oferta de todas as coisas santas dos filhos de Israel, que trouxerem ao sacerdote, será deste

[[v4-5-10]]

^<<v4-5-10,10>>^ e também as coisas sagradas de cada um; o que alguém der ao sacerdote será deste.

[[v4-5-11]]

^<<v4-5-11,11>>^ O Senhor  disse a Moisés:

[[v4-5-12]]

^<<v4-5-12,12>>^ — Fale aos filhos de Israel e diga-lhes: Se a mulher de alguém se desviar e lhe for infiel,

[[v4-5-13]]

^<<v4-5-13,13>>^ de maneira que algum homem tenha tido relações com ela, e for oculto aos olhos de seu marido, e ela o tiver ocultado, havendo-se ela contaminado, e contra ela não houver testemunha, e não for surpreendida em flagrante,

[[v4-5-14]]

^<<v4-5-14,14>>^ e o espírito de ciúmes vier sobre o marido, e ele tiver ciúmes de sua mulher, por ela se haver contaminado, ou se ele tiver ciúmes, mesmo que ela não tenha se contaminado,

[[v4-5-15]]

^<<v4-5-15,15>>^ então esse homem levará a sua mulher ao sacerdote, juntamente com a sua oferta por ela: dois litros de farinha de cevada, sobre a qual não derramará azeite, nem sobre ela porá incenso, pois é oferta de cereais por ciúmes, oferta memorativa, que traz a iniquidade à memória.

[[v4-5-16]]

^<<v4-5-16,16>>^ — O sacerdote levará a mulher para a frente e a colocará diante do Senhor .

[[v4-5-17]]

^<<v4-5-17,17>>^ O sacerdote colocará um pouco de água santa num vaso de barro; também pegará do pó que houver no chão do tabernáculo e o colocará na água.

[[v4-5-18]]

^<<v4-5-18,18>>^ Apresentará a mulher diante do Senhor  e soltará a cabeleira dela; e lhe porá nas mãos a oferta memorativa de cereais, que é a oferta de cereais por ciúmes. A água amarga, que traz consigo a maldição, estará na mão do sacerdote.

[[v4-5-19]]

^<<v4-5-19,19>>^ O sacerdote fará com que a mulher jure, dizendo-lhe: "Se ninguém teve relações com você, e se você não se desviou para a impureza, estando sob o domínio de seu marido, você será livre destas águas amargas, que trazem maldição.

[[v4-5-20]]

^<<v4-5-20,20>>^ Mas, se você se desviou, quando sob o domínio de seu marido, e se contaminou, e algum homem, que não é o seu marido, teve relações com você…"

[[v4-5-21]]

^<<v4-5-21,21>>^ Então o sacerdote fará com que a mulher tome o juramento de maldição e lhe dirá: "O Senhor  ponha você por maldição e por praga no meio do seu povo, fazendo com que você fique estéril e inche o seu ventre;

[[v4-5-22]]

^<<v4-5-22,22>>^ e que esta água amaldiçoante penetre nas suas entranhas, para fazer com que inche o seu ventre e você fique estéril." Então a mulher dirá: "Amém! Amém!"

[[v4-5-23]]

^<<v4-5-23,23>>^ — O sacerdote escreverá estas maldições num livro e, com a água amarga, as apagará.

[[v4-5-24]]

^<<v4-5-24,24>>^ E fará com que a mulher beba a água amarga, que traz consigo a maldição; e, sendo bebida, lhe causará amargura.

[[v4-5-25]]

^<<v4-5-25,25>>^ O sacerdote pegará da mão da mulher a oferta de cereais por ciúmes e a moverá diante do Senhor ; e a trará ao altar.

[[v4-5-26]]

^<<v4-5-26,26>>^ Pegará um punhado da oferta de cereais, da oferta memorativa, e o queimará sobre o altar; e depois fará com que a mulher beba a água.

[[v4-5-27]]

^<<v4-5-27,27>>^ E, havendo-lhe dado a beber aquela água, se ela tiver se contaminado, tendo sido infiel a seu marido, a água amaldiçoante entrará nela para amargura, e o seu ventre ficará inchado e o útero secará; a mulher será por maldição no meio do seu povo.

[[v4-5-28]]

^<<v4-5-28,28>>^ Se a mulher não tiver se contaminado, mas estiver pura, então será livre e poderá ter filhos.

[[v4-5-29]]

^<<v4-5-29,29>>^ — Esta é a lei para o caso de ciúmes, quando a mulher, sob o domínio de seu marido, se desviar e for contaminada;

[[v4-5-30]]

^<<v4-5-30,30>>^ ou quando sobre o homem vier o espírito de ciúmes, e tiver ciúmes de sua mulher, apresente a mulher diante do Senhor , e o sacerdote execute nela toda esta lei.

[[v4-5-31]]

^<<v4-5-31,31>>^ O homem será livre da iniquidade, porém a mulher levará a sua iniquidade.

'''

xref:004-numeros/004-numeros-004.adoc#v4-4-0[&#60; Capítulo Anterior] | <<v4-5-0,Topo>> | xref:004-numeros/004-numeros-006.adoc#v4-6-0[Próximo Capítulo &#62;]