include::./index.adoc[]

[[v4-24-0]]
=== Números, 24
// naa ?, NAA - Nova Almeida Atualizada

[[v4-24-1]]

^<<v4-24-1,1>>^ Quando Balaão viu que era do agrado do Senhor  que ele abençoasse Israel, não foi esta vez, como antes, ao encontro de agouros, mas voltou o rosto para o deserto.

[[v4-24-2]]

^<<v4-24-2,2>>^ Balaão levantou os olhos e viu Israel acampado segundo as suas tribos. E o Espírito de Deus veio sobre Balaão

[[v4-24-3]]

^<<v4-24-3,3>>^ e ele proferiu a sua palavra, dizendo: "Palavra de Balaão, filho de Beor, palavra do homem de olhos abertos;

[[v4-24-4]]

^<<v4-24-4,4>>^ palavra daquele que ouve os ditos de Deus, daquele que tem a visão do Todo-Poderoso e prostra-se, porém de olhos abertos:

[[v4-24-5]]

^<<v4-24-5,5>>^ Como são boas as suas tendas, ó Jacó! Como são boas as suas moradas, ó Israel!

[[v4-24-6]]

^<<v4-24-6,6>>^ São como vales que se estendem, como jardins à beira dos rios, como árvores de sândalo que o Senhor  plantou, como cedros junto às águas.

[[v4-24-7]]

^<<v4-24-7,7>>^ Águas manarão de seus baldes, e as suas sementeiras terão águas abundantes. O seu rei se levantará mais do que Agague, e o seu reino será exaltado.

[[v4-24-8]]

^<<v4-24-8,8>>^ Deus tirou do Egito o povo de Israel, cujas forças são como as do boi selvagem; consumirá as nações inimigas, e quebrará seus ossos, e, com as suas flechas, os atravessará.

[[v4-24-9]]

^<<v4-24-9,9>>^ Israel abaixou-se, deitou-se como leão e como leoa; quem o despertará? Benditos os que abençoarem você, e malditos os que amaldiçoarem você."

[[v4-24-10]]

^<<v4-24-10,10>>^ Então Balaque ficou irado com Balaão, e bateu com uma mão na outra. Balaque disse a Balaão: — Eu o chamei para que você amaldiçoasse os meus inimigos, mas agora, já três vezes, você somente os abençoou.

[[v4-24-11]]

^<<v4-24-11,11>>^ Agora vá embora para a sua casa. Eu tinha dito que o cobriria de honras, mas eis que o Senhor  o privou delas.

[[v4-24-12]]

^<<v4-24-12,12>>^ Então Balaão disse a Balaque: — Não é verdade que eu também tinha dito aos mensageiros que você me enviou que,

[[v4-24-13]]

^<<v4-24-13,13>>^ mesmo que você me desse a sua casa cheia de prata e de ouro, eu não poderia transgredir o mandado do Senhor , fazendo bem ou mal por minha própria iniciativa? E não é verdade que eu disse que falaria apenas o que o Senhor  me dissesse?

[[v4-24-14]]

^<<v4-24-14,14>>^ Agora eis que volto ao meu povo. Mas antes disso, venha, pois quero avisá-lo do que este povo fará ao seu povo, nos últimos dias.

[[v4-24-15]]

^<<v4-24-15,15>>^ Então Balaão proferiu a sua palavra e disse: "Palavra de Balaão, filho de Beor, palavra do homem de olhos abertos;

[[v4-24-16]]

^<<v4-24-16,16>>^ palavra daquele que ouve os ditos de Deus e tem o conhecimento do Altíssimo; daquele que tem a visão do Todo-Poderoso e prostra-se, porém de olhos abertos:

[[v4-24-17]]

^<<v4-24-17,17>>^ Eu o vejo, porém não agora; eu o contemplo, mas não de perto. Uma estrela procederá de Jacó, de Israel subirá um cetro que ferirá as têmporas de Moabe e destruirá todos os filhos de Sete.

[[v4-24-18]]

^<<v4-24-18,18>>^ Edom será uma propriedade; Seir, que é inimigo dele, também será uma propriedade; mas Israel fará proezas.

[[v4-24-19]]

^<<v4-24-19,19>>^ De Jacó sairá o dominador; ele exterminará os que restam das cidades."

[[v4-24-20]]

^<<v4-24-20,20>>^ Balaão viu Amaleque, proferiu a sua palavra e disse: "Amaleque é o primeiro das nações, porém o seu fim será destruição."

[[v4-24-21]]

^<<v4-24-21,21>>^ Viu os queneus, proferiu a sua palavra e disse: "A sua habitação está segura, e você pôs o seu ninho na rocha.

[[v4-24-22]]

^<<v4-24-22,22>>^ Todavia, o queneu será consumido, até que Assur leve você cativo.

[[v4-24-23]]

^<<v4-24-23,23>>^ Balaão proferiu ainda a sua palavra e disse: Ai! Quem viverá, quando Deus fizer isto?

[[v4-24-24]]

^<<v4-24-24,24>>^ Homens virão da costa de Quitim em seus navios; afligirão Assur e Héber; e também eles mesmos perecerão."

[[v4-24-25]]

^<<v4-24-25,25>>^ Depois Balaão se levantou e se foi, e voltou para a sua terra. Também Balaque se foi pelo seu caminho.

'''

xref:004-numeros/004-numeros-023.adoc#v4-23-0[&#60; Capítulo Anterior] | <<v4-24-0,Topo>> | xref:004-numeros/004-numeros-025.adoc#v4-25-0[Próximo Capítulo &#62;]