include::./index.adoc[]

[[v4-23-0]]
=== Números, 23
// naa ?, NAA - Nova Almeida Atualizada

[[v4-23-1]]

^<<v4-23-1,1>>^ Então Balaão disse a Balaque: — Construa neste lugar sete altares e prepare sete novilhos e sete carneiros para mim.

[[v4-23-2]]

^<<v4-23-2,2>>^ Balaque fez como Balaão tinha dito, e os dois ofereceram um novilho e um carneiro sobre cada altar.

[[v4-23-3]]

^<<v4-23-3,3>>^ Então Balaão disse a Balaque: — Fique aqui junto do seu holocausto, e eu irei mais adiante; talvez o Senhor  venha ao meu encontro, e o que ele me mostrar direi a você. E Balaão subiu a um monte descampado.

[[v4-23-4]]

^<<v4-23-4,4>>^ Deus se encontrou com Balaão, e este lhe disse: — Preparei sete altares e sobre cada um ofereci um novilho e um carneiro.

[[v4-23-5]]

^<<v4-23-5,5>>^ Então o Senhor  pôs a palavra na boca de Balaão e disse: — Volte para Balaque e transmita a ele o que eu falei a você.

[[v4-23-6]]

^<<v4-23-6,6>>^ Quando Balaão voltou, eis que Balaque ainda estava junto do seu holocausto, ele e todos os chefes dos moabitas.

[[v4-23-7]]

^<<v4-23-7,7>>^ Então Balaão proferiu a sua palavra e disse: "Balaque me fez vir de Arã, o rei de Moabe, dos montes do Oriente. Venha — disse-me ele — e amaldiçoe Jacó; venha e denuncie Israel.

[[v4-23-8]]

^<<v4-23-8,8>>^ Como posso amaldiçoar a quem Deus não amaldiçoou? Como posso denunciar a quem o Senhor não denunciou?

[[v4-23-9]]

^<<v4-23-9,9>>^ Pois do alto dos rochedos vejo Israel e dos montes o contemplo: eis que é povo que habita só e não será reputado entre as nações.

[[v4-23-10]]

^<<v4-23-10,10>>^ Quem contou o pó de Jacó ou enumerou a quarta parte de Israel? Que eu morra a morte dos justos, e o meu fim seja como o deles."

[[v4-23-11]]

^<<v4-23-11,11>>^ Então Balaque disse a Balaão: — O que foi que você me fez? Eu o chamei para amaldiçoar os meus inimigos, mas eis que você somente os abençoou.

[[v4-23-12]]

^<<v4-23-12,12>>^ Mas Balaão respondeu: — Será que eu não deveria ter o cuidado de dizer apenas o que o Senhor  pôs na minha boca?

[[v4-23-13]]

^<<v4-23-13,13>>^ Então Balaque lhe disse: — Peço que venha comigo a outro lugar, de onde você poderá ver o povo. Você verá somente a parte mais próxima dele, mas não verá todos eles. E daquele lugar lance uma maldição sobre eles.

[[v4-23-14]]

^<<v4-23-14,14>>^ Balaque levou-o consigo ao campo de Zofim, no alto do monte Pisga; e edificou sete altares e sobre cada um ofereceu um novilho e um carneiro.

[[v4-23-15]]

^<<v4-23-15,15>>^ Então Balaão disse a Balaque: — Fique aqui junto do seu holocausto, e eu irei ali ao encontro do Senhor .

[[v4-23-16]]

^<<v4-23-16,16>>^ O Senhor  se encontrou com Balaão, pôs-lhe na boca a palavra e disse: — Volte para Balaque e transmita a ele o que eu falei a você.

[[v4-23-17]]

^<<v4-23-17,17>>^ Balaão voltou, e eis que Balaque ainda estava junto do holocausto, e os chefes dos moabitas estavam com ele. Balaque perguntou: — O que foi que o Senhor  falou?

[[v4-23-18]]

^<<v4-23-18,18>>^ Então Balaão proferiu a sua palavra e disse: "Levante-se, Balaque, e ouça; escute-me, filho de Zipor:

[[v4-23-19]]

^<<v4-23-19,19>>^ Deus não é homem, para que minta; nem filho de homem, para que mude de ideia. Será que, tendo ele prometido, não o fará? Ou, tendo falado, não o cumprirá?

[[v4-23-20]]

^<<v4-23-20,20>>^ Eis que recebi ordem para abençoar; ele abençoou, não o posso revogar.

[[v4-23-21]]

^<<v4-23-21,21>>^ Não viu desgraça em Jacó, nem contemplou calamidade em Israel; o Senhor , seu Deus, está com eles; no meio deles se ouvem aclamações ao seu Rei.

[[v4-23-22]]

^<<v4-23-22,22>>^ Deus os tirou do Egito; as forças deles são como as do boi selvagem.

[[v4-23-23]]

^<<v4-23-23,23>>^ Pois contra Jacó não vale encantamento, nem adivinhação contra Israel; agora, se poderá dizer de Jacó e de Israel: Que coisas tem feito Deus!

[[v4-23-24]]

^<<v4-23-24,24>>^ Eis que o povo se levanta como leoa e se ergue como leão; não se deita até que devore a presa e beba o sangue dos que forem mortos."

[[v4-23-25]]

^<<v4-23-25,25>>^ Então Balaque disse a Balaão: — Não amaldiçoe o povo, mas também não o abençoe.

[[v4-23-26]]

^<<v4-23-26,26>>^ Porém Balaão respondeu e disse a Balaque: — Eu não tinha dito a você: tudo o que o Senhor  falar, isso farei?

[[v4-23-27]]

^<<v4-23-27,27>>^ Então Balaque disse a Balaão: — Venha, por favor, que eu o levarei a outro lugar. Talvez pareça bem aos olhos de Deus que dali você amaldiçoe o povo.

[[v4-23-28]]

^<<v4-23-28,28>>^ Assim, Balaque levou Balaão consigo ao alto do monte Peor, de onde se avista o deserto.

[[v4-23-29]]

^<<v4-23-29,29>>^ Balaão disse a Balaque: — Construa neste lugar sete altares e prepare sete novilhos e sete carneiros para mim.

[[v4-23-30]]

^<<v4-23-30,30>>^ Balaque fez como Balaão havia ordenado e ofereceu sobre cada altar um novilho e um carneiro.

'''

xref:004-numeros/004-numeros-022.adoc#v4-22-0[&#60; Capítulo Anterior] | <<v4-23-0,Topo>> | xref:004-numeros/004-numeros-024.adoc#v4-24-0[Próximo Capítulo &#62;]