include::./index.adoc[]

[[v4-11-0]]
=== Números, 11
// naa ?, NAA - Nova Almeida Atualizada

[[v4-11-1]]

^<<v4-11-1,1>>^ O povo se queixou de sua sorte aos ouvidos do Senhor . Quando o Senhor  ouviu as reclamações, sua ira se acendeu, e fogo do Senhor  ardeu entre eles e consumiu algumas extremidades do arraial.

[[v4-11-2]]

^<<v4-11-2,2>>^ Então o povo clamou a Moisés. Este orou ao Senhor , e o fogo se apagou.

[[v4-11-3]]

^<<v4-11-3,3>>^ Por isso aquele lugar foi chamado de Taberá, porque o fogo do Senhor  se havia acendido entre eles.

[[v4-11-4]]

^<<v4-11-4,4>>^ E o populacho que estava no meio deles veio a ter grande desejo das comidas dos egípcios. Também os filhos de Israel começaram a chorar outra vez, dizendo: — Quem nos dará carne para comer?

[[v4-11-5]]

^<<v4-11-5,5>>^ Lembramos dos peixes que comíamos de graça no Egito. Que saudade dos pepinos, dos melões, dos alhos silvestres, das cebolas e dos alhos!

[[v4-11-6]]

^<<v4-11-6,6>>^ Mas agora a nossa alma está seca, e não vemos nada a não ser este maná.

[[v4-11-7]]

^<<v4-11-7,7>>^ O maná era como semente de coentro, e a sua aparência era semelhante à de bdélio.

[[v4-11-8]]

^<<v4-11-8,8>>^ O povo ia por toda parte e o colhia. Eles o moíam em moinhos ou o socavam em pilões. Depois o cozinhavam em panelas e dele faziam bolos. O sabor do maná era como o de bolos amassados com azeite.

[[v4-11-9]]

^<<v4-11-9,9>>^ Quando, de noite, descia o orvalho sobre o arraial, sobre este também caía o maná.

[[v4-11-10]]

^<<v4-11-10,10>>^ Então Moisés ouviu como o povo chorava por famílias, cada um à porta da sua tenda. O Senhor  ficou muito irado, e Moisés também não gostou daquilo.

[[v4-11-11]]

^<<v4-11-11,11>>^ Moisés disse ao Senhor : — Por que fizeste mal a teu servo, e por que não achei favor aos teus olhos, visto que puseste sobre mim a carga de todo este povo?

[[v4-11-12]]

^<<v4-11-12,12>>^ Será que fui eu quem concebeu todo este povo? Será que fui eu quem o deu à luz, para que me digas que o leve no colo, como a babá leva a criança que mama, até a terra que prometeste dar a seus pais?

[[v4-11-13]]

^<<v4-11-13,13>>^ Onde eu poderia conseguir carne para dar a todo este povo? Pois chora diante de mim, dizendo: "Dê-nos carne para comer."

[[v4-11-14]]

^<<v4-11-14,14>>^ Eu sozinho não posso levar todo este povo, pois é pesado demais para mim.

[[v4-11-15]]

^<<v4-11-15,15>>^ Se me tratas assim, mata-me de uma vez. Se achei favor aos teus olhos, peço que não me deixes ver a minha miséria.

[[v4-11-16]]

^<<v4-11-16,16>>^ O Senhor  disse a Moisés: — Reúna para mim setenta homens dos anciãos de Israel, que você sabe que são anciãos e superintendentes do povo, e traga-os diante da tenda do encontro, para que estejam ali com você.

[[v4-11-17]]

^<<v4-11-17,17>>^ Então descerei e ali falarei com você. Tirarei do Espírito que está sobre você e o porei sobre eles; e eles ajudarão você a levar a carga do povo, para que você não tenha de levá-la sozinho.

[[v4-11-18]]

^<<v4-11-18,18>>^ Diga ao povo: "Santifiquem-se para amanhã e vocês comerão carne, porque vocês choraram aos ouvidos do Senhor , dizendo: ‘Quem nos dará carne para comer? A vida era melhor no Egito.’" Por isso o Senhor  lhes dará carne e vocês poderão comer.

[[v4-11-19]]

^<<v4-11-19,19>>^ Não comerão um dia, nem dois dias, nem cinco, nem dez, nem ainda vinte,

[[v4-11-20]]

^<<v4-11-20,20>>^ mas um mês inteiro, até que saia pelo nariz, até que fiquem com nojo dela, porque vocês rejeitaram o Senhor , que está no meio de vocês, e choraram diante dele, dizendo: "Por que saímos do Egito?"

[[v4-11-21]]

^<<v4-11-21,21>>^ Moisés, porém, respondeu: — Este povo no meio do qual estou é de seiscentos mil homens em pé, e tu dizes: "Eu lhes darei carne, e eles a comerão durante um mês inteiro."

[[v4-11-22]]

^<<v4-11-22,22>>^ Quantos rebanhos de ovelhas e de gado teríamos de matar, para que tivessem o suficiente? Ou será que bastaria, se ajuntássemos para eles todos os peixes do mar?

[[v4-11-23]]

^<<v4-11-23,23>>^ Porém o Senhor  respondeu a Moisés: — Será que a mão do Senhor  se encurtou? Agora mesmo você verá se a minha palavra se cumprirá ou não!

[[v4-11-24]]

^<<v4-11-24,24>>^ Moisés saiu e contou ao povo as palavras do Senhor . Ele reuniu setenta homens dos anciãos do povo e os pôs ao redor da tenda.

[[v4-11-25]]

^<<v4-11-25,25>>^ Então o Senhor  desceu na nuvem e falou com Moisés. E, tirando do Espírito que estava sobre Moisés, o pôs sobre aqueles setenta anciãos. Quando o Espírito repousou sobre eles, profetizaram; mas isto nunca mais se repetiu.

[[v4-11-26]]

^<<v4-11-26,26>>^ Porém dois homens ficaram no arraial. Um se chamava Eldade, e o outro, Medade. O Espírito repousou sobre eles, porque estavam entre os inscritos, mesmo que não tivessem ido até a tenda; e profetizavam no arraial.

[[v4-11-27]]

^<<v4-11-27,27>>^ Então um jovem correu e anunciou a Moisés: — Eldade e Medade estão profetizando no arraial.

[[v4-11-28]]

^<<v4-11-28,28>>^ Josué, filho de Num, auxiliar de Moisés, um dos seus escolhidos, respondeu e disse: — Moisés, meu senhor, ordene que parem com isso.

[[v4-11-29]]

^<<v4-11-29,29>>^ Porém Moisés lhe disse: — Você está com ciúmes por mim? Eu gostaria que todo o povo do Senhor  fosse profeta, que o Senhor  lhes desse o seu Espírito!

[[v4-11-30]]

^<<v4-11-30,30>>^ Depois, Moisés se recolheu ao arraial, ele e os anciãos de Israel.

[[v4-11-31]]

^<<v4-11-31,31>>^ Então soprou um vento do Senhor , e trouxe codornizes do mar, e as espalhou pelo arraial em todas as direções, numa extensão de cerca de um dia de caminhada, a uma altura de quase um metro sobre a terra.

[[v4-11-32]]

^<<v4-11-32,32>>^ Todo aquele dia e toda aquela noite, e também no dia seguinte, o povo se levantou e recolheu as codornizes; o que menos recolheu teve dez montões; e as estenderam para si ao redor do arraial.

[[v4-11-33]]

^<<v4-11-33,33>>^ Enquanto a carne ainda estava entre os seus dentes, antes que fosse mastigada, a ira do Senhor  se acendeu contra o povo, e o feriu com uma terrível praga.

[[v4-11-34]]

^<<v4-11-34,34>>^ Por isso aquele lugar foi chamado de Quibrote-Hataavá, porque ali foi sepultado o povo que teve o desejo das comidas dos egípcios.

[[v4-11-35]]

^<<v4-11-35,35>>^ De Quibrote-Hataavá o povo partiu para Hazerote e ali ficou.

'''

xref:004-numeros/004-numeros-010.adoc#v4-10-0[&#60; Capítulo Anterior] | <<v4-11-0,Topo>> | xref:004-numeros/004-numeros-012.adoc#v4-12-0[Próximo Capítulo &#62;]