include::./index.adoc[]

[[v4-26-0]]
=== Números, 26
// naa ?, NAA - Nova Almeida Atualizada

[[v4-26-1]]

^<<v4-26-1,1>>^ Passada a praga, o Senhor  falou a Moisés e a Eleazar, filho do sacerdote Arão, dizendo:

[[v4-26-2]]

^<<v4-26-2,2>>^ — Levantem o censo de toda a congregação dos filhos de Israel, da idade de vinte anos para cima, segundo as casas de seus pais, todos os que, em Israel, forem capazes de sair à guerra.

[[v4-26-3]]

^<<v4-26-3,3>>^ Assim, nas campinas de Moabe, junto do Jordão, na altura de Jericó, Moisés e o sacerdote Eleazar falaram aos chefes de Israel, dizendo:

[[v4-26-4]]

^<<v4-26-4,4>>^ — Contem o povo da idade de vinte anos para cima, como o Senhor  havia ordenado a Moisés e aos filhos de Israel que saíram do Egito.

[[v4-26-5]]

^<<v4-26-5,5>>^ Rúben, o primogênito de Israel; os filhos de Rúben: de Enoque, a família dos enoquitas; de Palu, a família dos paluítas;

[[v4-26-6]]

^<<v4-26-6,6>>^ de Hezrom, a família dos hezronitas; de Carmi, a família dos carmitas.

[[v4-26-7]]

^<<v4-26-7,7>>^ São estas as famílias dos rubenitas, e deles foram contados quarenta e três mil e setecentos e trinta.

[[v4-26-8]]

^<<v4-26-8,8>>^ O filho de Palu: Eliabe.

[[v4-26-9]]

^<<v4-26-9,9>>^ Os filhos de Eliabe: Nemuel, Datã e Abirão. Estes, Datã e Abirão, são os que foram eleitos pela congregação e que se rebelaram contra Moisés e contra Arão, no grupo de Corá, quando se rebelaram contra o Senhor .

[[v4-26-10]]

^<<v4-26-10,10>>^ A terra abriu a boca e os engoliu com Corá, morrendo aquele grupo, quando o fogo consumiu duzentos e cinquenta homens, e isso serviu de advertência.

[[v4-26-11]]

^<<v4-26-11,11>>^ Mas os filhos de Corá não morreram.

[[v4-26-12]]

^<<v4-26-12,12>>^ Os filhos de Simeão, segundo as suas famílias: de Nemuel, a família dos nemuelitas; de Jamim, a família dos jaminitas; de Jaquim, a família dos jaquinitas;

[[v4-26-13]]

^<<v4-26-13,13>>^ de Zera, a família dos zeraítas; de Saul, a família dos saulitas.

[[v4-26-14]]

^<<v4-26-14,14>>^ São estas as famílias dos simeonitas, num total de vinte e dois mil e duzentos.

[[v4-26-15]]

^<<v4-26-15,15>>^ Os filhos de Gade, segundo as suas famílias: de Zefom, a família dos zefonitas; de Hagi, a família dos hagitas; de Suni, a família dos sunitas;

[[v4-26-16]]

^<<v4-26-16,16>>^ de Ozni, a família dos oznitas; de Eri, a família dos eritas;

[[v4-26-17]]

^<<v4-26-17,17>>^ de Arodi, a família dos aroditas; de Areli, a família dos arelitas.

[[v4-26-18]]

^<<v4-26-18,18>>^ São estas as famílias dos filhos de Gade, segundo os que foram deles contados, num total de quarenta mil e quinhentos.

[[v4-26-19]]

^<<v4-26-19,19>>^ Os filhos de Judá: Er e Onã; mas Er e Onã morreram na terra de Canaã.

[[v4-26-20]]

^<<v4-26-20,20>>^ Assim, os filhos de Judá foram, segundo as suas famílias: de Selá, a família dos selaítas; de Perez, a família dos perezitas; de Zera, a família dos zeraítas.

[[v4-26-21]]

^<<v4-26-21,21>>^ Os filhos de Perez foram: de Hezrom, a família dos hezronitas; de Hamul, a família dos hamulitas.

[[v4-26-22]]

^<<v4-26-22,22>>^ São estas as famílias de Judá, segundo os que foram deles contados, num total de setenta e seis mil e quinhentos.

[[v4-26-23]]

^<<v4-26-23,23>>^ Os filhos de Issacar, segundo as suas famílias, foram: de Tola, a família dos tolaítas; de Puva, a família dos puvitas;

[[v4-26-24]]

^<<v4-26-24,24>>^ de Jasube, a família dos jasubitas; de Sinrom, a família dos sinronitas.

[[v4-26-25]]

^<<v4-26-25,25>>^ São estas as famílias de Issacar, segundo os que foram deles contados, num total de sessenta e quatro mil e trezentos.

[[v4-26-26]]

^<<v4-26-26,26>>^ Os filhos de Zebulom, segundo as suas famílias, foram: de Serede, a família dos sereditas; de Elom, a família dos elonitas; de Jaleel, a família dos jaleelitas.

[[v4-26-27]]

^<<v4-26-27,27>>^ São estas as famílias dos zebulonitas, segundo os que foram deles contados, num total de sessenta mil e quinhentos.

[[v4-26-28]]

^<<v4-26-28,28>>^ Os filhos de José, segundo as suas famílias, foram Manassés e Efraim.

[[v4-26-29]]

^<<v4-26-29,29>>^ Os filhos de Manassés foram: de Maquir, a família dos maquiritas; e Maquir gerou Gileade; de Gileade, a família dos gileaditas.

[[v4-26-30]]

^<<v4-26-30,30>>^ São estes os filhos de Gileade: de Jezer, a família dos jezeritas; de Heleque, a família dos helequitas;

[[v4-26-31]]

^<<v4-26-31,31>>^ de Asriel, a família dos asrielitas; de Siquém, a família dos siquemitas.

[[v4-26-32]]

^<<v4-26-32,32>>^ De Semida, a família dos semidaítas; de Héfer, a família dos heferitas.

[[v4-26-33]]

^<<v4-26-33,33>>^ Porém Zelofeade, filho de Héfer, não tinha filhos; somente filhas. Os nomes das filhas de Zelofeade foram: Macla, Noa, Hogla, Milca e Tirza.

[[v4-26-34]]

^<<v4-26-34,34>>^ São estas as famílias de Manassés; os que foram deles contados foram cinquenta e dois mil e setecentos.

[[v4-26-35]]

^<<v4-26-35,35>>^ São estes os filhos de Efraim, segundo as suas famílias: de Sutela, a família dos sutelaítas; de Bequer, a família dos bequeritas; de Taã, a família dos taanitas.

[[v4-26-36]]

^<<v4-26-36,36>>^ São estes os filhos de Sutela: de Erã, a família dos eranitas.

[[v4-26-37]]

^<<v4-26-37,37>>^ São estas as famílias dos filhos de Efraim, segundo os que foram deles contados, num total de trinta e dois mil e quinhentos. São estes os filhos de José, segundo as suas famílias.

[[v4-26-38]]

^<<v4-26-38,38>>^ Os filhos de Benjamim, segundo as suas famílias: de Belá, a família dos belaítas; de Asbel, a família dos asbelitas; de Airão, a família dos airamitas;

[[v4-26-39]]

^<<v4-26-39,39>>^ de Sufã, a família dos sufamitas; de Hufã, a família dos hufamitas.

[[v4-26-40]]

^<<v4-26-40,40>>^ Os filhos de Belá foram: Arde e Naamã; de Arde, a família dos arditas; de Naamã, a família dos naamanitas.

[[v4-26-41]]

^<<v4-26-41,41>>^ São estes os filhos de Benjamim, segundo as suas famílias; os que foram deles contados foram quarenta e cinco mil e seiscentos.

[[v4-26-42]]

^<<v4-26-42,42>>^ São estes os filhos de Dã, segundo as suas famílias: de Suão, a família dos suamitas. São estas as famílias de Dã, segundo as suas famílias.

[[v4-26-43]]

^<<v4-26-43,43>>^ Todas as famílias dos suamitas, segundo os que foram deles contados, foram sessenta e quatro mil e quatrocentos.

[[v4-26-44]]

^<<v4-26-44,44>>^ Os filhos de Aser, segundo as suas famílias: de Imna, a família dos imnaítas; de Isvi, a família dos isvitas; de Berias, a família dos beriaítas.

[[v4-26-45]]

^<<v4-26-45,45>>^ Os filhos de Berias foram: de Héber, a família dos heberitas; de Malquiel, a família dos malquielitas.

[[v4-26-46]]

^<<v4-26-46,46>>^ O nome da filha de Aser foi Sera.

[[v4-26-47]]

^<<v4-26-47,47>>^ São estas as famílias dos filhos de Aser, segundo os que foram deles contados, num total de cinquenta e três mil e quatrocentos.

[[v4-26-48]]

^<<v4-26-48,48>>^ Os filhos de Naftali, segundo as suas famílias: de Jazeel, a família dos jazeelitas; de Guni, a família dos gunitas;

[[v4-26-49]]

^<<v4-26-49,49>>^ de Jezer, a família dos jezeritas; de Silém, a família dos silemitas.

[[v4-26-50]]

^<<v4-26-50,50>>^ São estas as famílias de Naftali, segundo as suas famílias; os que foram deles contados eram quarenta e cinco mil e quatrocentos.

[[v4-26-51]]

^<<v4-26-51,51>>^ São estes os contados dos filhos de Israel: seiscentos e um mil setecentos e trinta.

[[v4-26-52]]

^<<v4-26-52,52>>^ O Senhor  disse a Moisés:

[[v4-26-53]]

^<<v4-26-53,53>>^ — A estes se repartirá a terra em herança, segundo o censo.

[[v4-26-54]]

^<<v4-26-54,54>>^ À tribo mais numerosa você dará herança maior, e à pequena você dará herança menor; a herança será dada a cada tribo, em proporção ao seu número.

[[v4-26-55]]

^<<v4-26-55,55>>^ Todavia, a terra será repartida por sorteio; eles a herdarão segundo os nomes das tribos de seus pais.

[[v4-26-56]]

^<<v4-26-56,56>>^ A herança deles será repartida por sorteio entre as tribos maiores e menores.

[[v4-26-57]]

^<<v4-26-57,57>>^ São estes os que foram contados dos levitas, segundo as suas famílias: de Gérson, a família dos gersonitas; de Coate, a família dos coatitas; de Merari, a família dos meraritas.

[[v4-26-58]]

^<<v4-26-58,58>>^ São estas as famílias de Levi: a família dos libnitas, a família dos hebronitas, a família dos malitas, a família dos musitas, a família dos coraítas. Coate gerou Anrão.

[[v4-26-59]]

^<<v4-26-59,59>>^ A mulher de Anrão chamava-se Joquebede, filha de Levi, a qual lhe nasceu no Egito. De Anrão ela teve Arão, Moisés e Miriã, irmã deles.

[[v4-26-60]]

^<<v4-26-60,60>>^ A Arão nasceram Nadabe, Abiú, Eleazar e Itamar.

[[v4-26-61]]

^<<v4-26-61,61>>^ Nadabe e Abiú morreram quando levaram fogo estranho diante do Senhor .

[[v4-26-62]]

^<<v4-26-62,62>>^ Dos levitas foram contados vinte e três mil, todos os homens de um mês de idade para cima. Eles não foram contados entre os filhos de Israel, porque não lhes foi dada herança com os outros.

[[v4-26-63]]

^<<v4-26-63,63>>^ São estes os que foram contados por Moisés e o sacerdote Eleazar, que contaram os filhos de Israel nas campinas de Moabe, junto do Jordão, na altura de Jericó.

[[v4-26-64]]

^<<v4-26-64,64>>^ Entre estes, porém, não havia nenhum dos que foram contados por Moisés e pelo sacerdote Arão, quando levantaram o censo dos filhos de Israel no deserto do Sinai.

[[v4-26-65]]

^<<v4-26-65,65>>^ Porque o Senhor  tinha dito a respeito deles que certamente morreriam no deserto; e nenhum deles ficou, a não ser Calebe, filho de Jefoné, e Josué, filho de Num.

'''

xref:004-numeros/004-numeros-025.adoc#v4-25-0[&#60; Capítulo Anterior] | <<v4-26-0,Topo>> | xref:004-numeros/004-numeros-027.adoc#v4-27-0[Próximo Capítulo &#62;]