include::./index.adoc[]

[[v4-33-0]]
=== Números, 33
// naa ?, NAA - Nova Almeida Atualizada

[[v4-33-1]]

^<<v4-33-1,1>>^ São estas as caminhadas dos filhos de Israel que saíram da terra do Egito, segundo os seus exércitos, sob as ordens de Moisés e Arão.

[[v4-33-2]]

^<<v4-33-2,2>>^ Moisés escreveu os lugares de que saíram, caminhada após caminhada, conforme o mandado do Senhor . E são estas as suas caminhadas, segundo os lugares de que saíram:

[[v4-33-3]]

^<<v4-33-3,3>>^ eles partiram de Ramessés no décimo quinto dia do primeiro mês. No dia seguinte ao da Páscoa, os filhos de Israel saíram, corajosamente, aos olhos de todos os egípcios,

[[v4-33-4]]

^<<v4-33-4,4>>^ enquanto estes sepultavam todos os seus primogênitos, a quem o Senhor  havia matado entre eles; também contra os deuses o Senhor  executou juízos.

[[v4-33-5]]

^<<v4-33-5,5>>^ Os filhos de Israel partiram de Ramessés e acamparam em Sucote.

[[v4-33-6]]

^<<v4-33-6,6>>^ Partiram de Sucote e acamparam em Etã, que está no fim do deserto.

[[v4-33-7]]

^<<v4-33-7,7>>^ Partiram de Etã e voltaram a Pi-Hairote, que está diante de Baal-Zefom, e acamparam diante de Migdol.

[[v4-33-8]]

^<<v4-33-8,8>>^ Partiram de Pi-Hairote, passaram pelo meio do mar em direção ao deserto e, depois de terem caminhado três dias no deserto de Etã, acamparam em Mara.

[[v4-33-9]]

^<<v4-33-9,9>>^ Partiram de Mara e chegaram a Elim. Em Elim, havia doze fontes de água e setenta palmeiras; e acamparam ali.

[[v4-33-10]]

^<<v4-33-10,10>>^ Partiram de Elim e acamparam junto ao mar Vermelho.

[[v4-33-11]]

^<<v4-33-11,11>>^ Partiram do mar Vermelho e acamparam no deserto de Sim.

[[v4-33-12]]

^<<v4-33-12,12>>^ Partiram do deserto de Sim e acamparam em Dofca.

[[v4-33-13]]

^<<v4-33-13,13>>^ Partiram de Dofca e acamparam em Alus.

[[v4-33-14]]

^<<v4-33-14,14>>^ Partiram de Alus e acamparam em Refidim, porém ali não havia água para o povo beber.

[[v4-33-15]]

^<<v4-33-15,15>>^ Partiram de Refidim e acamparam no deserto do Sinai.

[[v4-33-16]]

^<<v4-33-16,16>>^ Partiram do deserto do Sinai e acamparam em Quibrote-Hataavá.

[[v4-33-17]]

^<<v4-33-17,17>>^ Partiram de Quibrote-Hataavá e acamparam em Hazerote.

[[v4-33-18]]

^<<v4-33-18,18>>^ Partiram de Hazerote e acamparam em Ritma.

[[v4-33-19]]

^<<v4-33-19,19>>^ Partiram de Ritma e acamparam em Rimom-Perez.

[[v4-33-20]]

^<<v4-33-20,20>>^ Partiram de Rimom-Perez e acamparam em Libna.

[[v4-33-21]]

^<<v4-33-21,21>>^ Partiram de Libna e acamparam em Rissa.

[[v4-33-22]]

^<<v4-33-22,22>>^ Partiram de Rissa e acamparam em Queelata.

[[v4-33-23]]

^<<v4-33-23,23>>^ Partiram de Queelata e acamparam no monte Sefer.

[[v4-33-24]]

^<<v4-33-24,24>>^ Partiram do monte Sefer e acamparam em Harada.

[[v4-33-25]]

^<<v4-33-25,25>>^ Partiram de Harada e acamparam em Maquelote.

[[v4-33-26]]

^<<v4-33-26,26>>^ Partiram de Maquelote e acamparam em Taate.

[[v4-33-27]]

^<<v4-33-27,27>>^ Partiram de Taate e acamparam em Tera.

[[v4-33-28]]

^<<v4-33-28,28>>^ Partiram de Tera e acamparam em Mitca.

[[v4-33-29]]

^<<v4-33-29,29>>^ Partiram de Mitca e acamparam em Hasmona.

[[v4-33-30]]

^<<v4-33-30,30>>^ Partiram de Hasmona e acamparam em Moserote.

[[v4-33-31]]

^<<v4-33-31,31>>^ Partiram de Moserote e acamparam em Benê-Jaacã.

[[v4-33-32]]

^<<v4-33-32,32>>^ Partiram de Benê-Jaacã e acamparam em Hor-Hagidgade.

[[v4-33-33]]

^<<v4-33-33,33>>^ Partiram de Hor-Hagidgade e acamparam em Jotbatá.

[[v4-33-34]]

^<<v4-33-34,34>>^ Partiram de Jotbatá e acamparam em Abrona.

[[v4-33-35]]

^<<v4-33-35,35>>^ Partiram de Abrona e acamparam em Eziom-Geber.

[[v4-33-36]]

^<<v4-33-36,36>>^ Partiram de Eziom-Geber e acamparam no deserto de Zim, que é Cades.

[[v4-33-37]]

^<<v4-33-37,37>>^ Partiram de Cades e acamparam no monte Hor, na fronteira da terra de Edom.

[[v4-33-38]]

^<<v4-33-38,38>>^ Então Arão, o sacerdote, subiu o monte Hor, segundo o mandado do Senhor ; e morreu ali, no primeiro dia do quinto mês do quadragésimo ano depois da saída dos filhos de Israel da terra do Egito.

[[v4-33-39]]

^<<v4-33-39,39>>^ Arão tinha cento e vinte e três anos de idade quando morreu no monte Hor.

[[v4-33-40]]

^<<v4-33-40,40>>^ Então o rei cananeu de Arade, que habitava o Sul da terra de Canaã, soube que os filhos de Israel estavam chegando.

[[v4-33-41]]

^<<v4-33-41,41>>^ Eles partiram do monte Hor e acamparam em Zalmona.

[[v4-33-42]]

^<<v4-33-42,42>>^ Partiram de Zalmona e acamparam em Punom.

[[v4-33-43]]

^<<v4-33-43,43>>^ Partiram de Punom e acamparam em Obote.

[[v4-33-44]]

^<<v4-33-44,44>>^ Partiram de Obote e acamparam em Ijé-Abarim, na fronteira de Moabe.

[[v4-33-45]]

^<<v4-33-45,45>>^ Partiram de Ijé-Abarim e acamparam em Dibom-Gade.

[[v4-33-46]]

^<<v4-33-46,46>>^ Partiram de Dibom-Gade e acamparam em Almom-Diblataim.

[[v4-33-47]]

^<<v4-33-47,47>>^ Partiram de Almom-Diblataim e acamparam nos montes de Abarim, diante de Nebo.

[[v4-33-48]]

^<<v4-33-48,48>>^ Partiram dos montes de Abarim e acamparam nas campinas de Moabe, junto ao Jordão, na altura de Jericó.

[[v4-33-49]]

^<<v4-33-49,49>>^ E acamparam junto ao Jordão, desde Bete-Jesimote até Abel-Sitim, nas campinas de Moabe.

[[v4-33-50]]

^<<v4-33-50,50>>^ Nas campinas de Moabe, junto ao Jordão, na altura de Jericó, o Senhor  disse a Moisés:

[[v4-33-51]]

^<<v4-33-51,51>>^ — Fale com os filhos de Israel e diga-lhes: Quando vocês tiverem passado o Jordão para entrar na terra de Canaã,

[[v4-33-52]]

^<<v4-33-52,52>>^ devem expulsar da frente de vocês todos os moradores da terra, destruir todas as pedras com figura e todas as imagens fundidas. Devem também derrubar todos os santuários nos lugares altos.

[[v4-33-53]]

^<<v4-33-53,53>>^ Tomem posse da terra e morem nela, porque eu lhes dei esta terra, para que vocês tomem posse dela.

[[v4-33-54]]

^<<v4-33-54,54>>^ Vocês herdarão a terra por sorteio, segundo as suas famílias. À tribo mais numerosa deem uma herança maior; à tribo pequena deem uma herança menor. Onde lhe cair a sorte, esse lugar lhe pertencerá; vocês herdarão segundo as tribos de seus pais.

[[v4-33-55]]

^<<v4-33-55,55>>^ Porém, se não expulsarem os moradores da terra, então os que vocês deixarem ficar serão para vocês como espinhos nos olhos e como aguilhões nas costas e eles os perturbarão na terra em que vocês irão morar.

[[v4-33-56]]

^<<v4-33-56,56>>^ E farei com vocês o que pensei fazer com eles.

'''

xref:004-numeros/004-numeros-032.adoc#v4-32-0[&#60; Capítulo Anterior] | <<v4-33-0,Topo>> | xref:004-numeros/004-numeros-034.adoc#v4-34-0[Próximo Capítulo &#62;]