include::./index.adoc[]

[[v4-16-0]]
=== Números, 16
// naa ?, NAA - Nova Almeida Atualizada

[[v4-16-1]]

^<<v4-16-1,1>>^ Corá, filho de Isar, filho de Coate, filho de Levi, tomou consigo Datã e Abirão, filhos de Eliabe, e também Om, filho de Pelete, todos da tribo de Rúben,

[[v4-16-2]]

^<<v4-16-2,2>>^ e se levantaram diante de Moisés com duzentos e cinquenta homens dos filhos de Israel, chefes da congregação, eleitos por ela, homens de renome,

[[v4-16-3]]

^<<v4-16-3,3>>^ e se ajuntaram contra Moisés e contra Arão e lhes disseram: — Basta! Toda a congregação é santa, cada um deles é santo, e o Senhor  está no meio deles. Por que, então, vocês se exaltam sobre a congregação do Senhor ?

[[v4-16-4]]

^<<v4-16-4,4>>^ Quando ouviu isto, Moisés caiu sobre o seu rosto.

[[v4-16-5]]

^<<v4-16-5,5>>^ E falou a Corá e a todo o seu grupo, dizendo: — Amanhã pela manhã, o Senhor  fará saber quem é dele e quem é o santo que ele fará chegar a si. Aquele a quem ele escolher, esse ele fará chegar a si.

[[v4-16-6]]

^<<v4-16-6,6>>^ Façam isto: peguem incensários, você, Corá e todo o seu grupo.

[[v4-16-7]]

^<<v4-16-7,7>>^ Ponham brasas nos incensários amanhã, coloquem incenso sobre as brasas diante do Senhor . O homem a quem o Senhor  escolher, este será o santo. E agora basta, filhos de Levi!

[[v4-16-8]]

^<<v4-16-8,8>>^ Moisés disse também a Corá: — Agora escutem, filhos de Levi!

[[v4-16-9]]

^<<v4-16-9,9>>^ Será que para vocês é pouca coisa o fato de o Deus de Israel os ter separado da congregação de Israel, para os fazer chegar a si, a fim de cumprirem o serviço do tabernáculo do Senhor  e estarem diante da congregação para ministrar-lhe?

[[v4-16-10]]

^<<v4-16-10,10>>^ Ele fez chegar você, Corá, e todos os seus irmãos, os filhos de Levi, com você. E agora vocês buscam também o sacerdócio?

[[v4-16-11]]

^<<v4-16-11,11>>^ Portanto, você e todo o seu grupo estão contra o Senhor . E Arão, o que é ele para que estejam murmurando contra ele?

[[v4-16-12]]

^<<v4-16-12,12>>^ Moisés mandou chamar Datã e Abirão, filhos de Eliabe. Porém eles disseram: — Não iremos!

[[v4-16-13]]

^<<v4-16-13,13>>^ Será que é pouca coisa o fato de você nos ter tirado de uma terra que mana leite e mel, para nos fazer morrer neste deserto? E agora você quer também se fazer príncipe sobre nós?

[[v4-16-14]]

^<<v4-16-14,14>>^ Além disso, você não nos levou a uma terra que mana leite e mel, nem nos deu campos e vinhas como herança. Você pensa que pode arrancar os olhos dessa gente? Pois não iremos!

[[v4-16-15]]

^<<v4-16-15,15>>^ Então Moisés ficou muito irado e disse ao Senhor : — Não atentes para a oferta deles! Não tirei deles nem um só jumento e não fiz mal a nenhum deles.

[[v4-16-16]]

^<<v4-16-16,16>>^ Moisés disse ainda a Corá: — Você e todo o seu grupo, ponham-se diante do Senhor  — você e eles, e também Arão — no dia de amanhã.

[[v4-16-17]]

^<<v4-16-17,17>>^ Cada um pegará o seu incensário e porá incenso nele. Que cada um traga o seu incensário diante do Senhor , duzentos e cinquenta incensários; também você e Arão, cada qual o seu.

[[v4-16-18]]

^<<v4-16-18,18>>^ Assim, pegaram cada qual o seu incensário, puseram brasas neles, sobre as brasas colocaram incenso e se puseram com Moisés e Arão diante da porta da tenda do encontro.

[[v4-16-19]]

^<<v4-16-19,19>>^ Corá reuniu contra eles todo o povo à porta da tenda do encontro. Então a glória do Senhor  apareceu a toda a congregação.

[[v4-16-20]]

^<<v4-16-20,20>>^ O Senhor  disse a Moisés e a Arão:

[[v4-16-21]]

^<<v4-16-21,21>>^ — Afastem-se do meio desta congregação, e eu os consumirei num momento.

[[v4-16-22]]

^<<v4-16-22,22>>^ Mas Moisés e Arão se prostraram sobre o seu rosto e disseram: — Ó Deus, autor e conservador de toda a vida, será que, pelo fato de pecar um só homem, ficarás indignado contra toda esta congregação?

[[v4-16-23]]

^<<v4-16-23,23>>^ O Senhor  respondeu a Moisés:

[[v4-16-24]]

^<<v4-16-24,24>>^ — Fale a toda esta congregação, dizendo: "Afastem-se da habitação de Corá, Datã e Abirão."

[[v4-16-25]]

^<<v4-16-25,25>>^ Então Moisés se levantou e foi para onde estavam Datã e Abirão; e os anciãos de Israel foram com ele.

[[v4-16-26]]

^<<v4-16-26,26>>^ E Moisés disse à congregação: — Peço que vocês se afastem das tendas destes homens perversos e não toquem em nada do que é deles, para que vocês não sejam destruídos por causa de todos os pecados que eles cometeram.

[[v4-16-27]]

^<<v4-16-27,27>>^ Eles se afastaram da habitação de Corá, Datã e Abirão. Datã e Abirão saíram e se puseram à porta da sua tenda, juntamente com suas mulheres, seus filhos e suas crianças.

[[v4-16-28]]

^<<v4-16-28,28>>^ Então Moisés disse: — Nisto vocês saberão que o Senhor  me enviou a realizar todas estas obras, que não procedem de mim mesmo:

[[v4-16-29]]

^<<v4-16-29,29>>^ se estes homens morrerem como morrem todas as pessoas e se forem visitados por qualquer castigo como se dá com todas as pessoas, então o Senhor  não me enviou.

[[v4-16-30]]

^<<v4-16-30,30>>^ Mas, se o Senhor  criar alguma coisa nova, e a terra abrir a sua boca e os engolir com tudo o que eles têm, e se eles descerem vivos ao mundo dos mortos, então vocês saberão que estes homens desprezaram o Senhor .

[[v4-16-31]]

^<<v4-16-31,31>>^ E aconteceu que, assim que Moisés acabou de dizer todas estas palavras, a terra debaixo deles se fendeu,

[[v4-16-32]]

^<<v4-16-32,32>>^ abriu a sua boca e os engoliu com as famílias deles, com todos os que eram partidários de Corá e com todos os bens deles.

[[v4-16-33]]

^<<v4-16-33,33>>^ Eles e tudo o que lhes pertencia desceram vivos ao mundo dos mortos; a terra os cobriu, e desapareceram do meio da congregação.

[[v4-16-34]]

^<<v4-16-34,34>>^ Todo o Israel que estava ao redor deles fugiu do grito deles. Todos gritavam: — Vamos fugir, para que a terra não venha a nos engolir também!

[[v4-16-35]]

^<<v4-16-35,35>>^ Então veio fogo do Senhor  e consumiu os duzentos e cinquenta homens que ofereciam o incenso.

[[v4-16-36]]

^<<v4-16-36,36>>^ O Senhor  disse a Moisés:

[[v4-16-37]]

^<<v4-16-37,37>>^ — Diga a Eleazar, filho de Arão, o sacerdote, que pegue os incensários do meio do incêndio e espalhe as brasas para longe, porque os incensários são santos.

[[v4-16-38]]

^<<v4-16-38,38>>^ Quanto aos incensários daqueles que pecaram contra a sua própria vida, que deles se façam lâminas para cobertura do altar, porque eles os trouxeram diante do Senhor ; por isso, são santos e serão por sinal aos filhos de Israel.

[[v4-16-39]]

^<<v4-16-39,39>>^ O sacerdote Eleazar pegou os incensários de metal que aqueles homens que foram queimados tinham trazido, e os incensários foram transformados em lâminas para cobertura do altar,

[[v4-16-40]]

^<<v4-16-40,40>>^ por memorial para os filhos de Israel, para que nenhum estranho, que não for da descendência de Arão, se aproxime para acender incenso diante do Senhor ; para que não seja como Corá e o seu grupo, como o Senhor  lhe tinha dito por meio de Moisés.

[[v4-16-41]]

^<<v4-16-41,41>>^ Mas, no dia seguinte, toda a congregação dos filhos de Israel murmurou contra Moisés e contra Arão, dizendo: — Vocês mataram o povo do Senhor .

[[v4-16-42]]

^<<v4-16-42,42>>^ Quando o povo se ajuntou contra Moisés e Arão, eles se viraram para a tenda do encontro. E eis que a nuvem a cobriu, e a glória do Senhor  apareceu.

[[v4-16-43]]

^<<v4-16-43,43>>^ Moisés e Arão foram para a frente da tenda do encontro.

[[v4-16-44]]

^<<v4-16-44,44>>^ Então o Senhor  falou a Moisés, dizendo:

[[v4-16-45]]

^<<v4-16-45,45>>^ — Saiam do meio desta congregação, e eu a consumirei num momento. Então eles se prostraram sobre o seu rosto.

[[v4-16-46]]

^<<v4-16-46,46>>^ Moisés disse a Arão: — Pegue o seu incensário, ponha nele algumas brasas do altar, coloque incenso sobre elas, vá depressa à congregação e faça expiação por eles; porque grande indignação saiu de diante do Senhor ; já começou a praga.

[[v4-16-47]]

^<<v4-16-47,47>>^ Arão pegou o incensário, como Moisés lhe havia falado, e correu para o meio da congregação. Eis que a praga já havia começado entre o povo. Arão colocou incenso nele e fez expiação pelo povo.

[[v4-16-48]]

^<<v4-16-48,48>>^ Pôs-se em pé entre os mortos e os vivos; e cessou a praga.

[[v4-16-49]]

^<<v4-16-49,49>>^ Ora, os que morreram daquela praga foram catorze mil e setecentos, fora os que morreram por causa de Corá.

[[v4-16-50]]

^<<v4-16-50,50>>^ Arão voltou para junto de Moisés, à porta da tenda do encontro; e cessou a praga.

'''

xref:004-numeros/004-numeros-015.adoc#v4-15-0[&#60; Capítulo Anterior] | <<v4-16-0,Topo>> | xref:004-numeros/004-numeros-017.adoc#v4-17-0[Próximo Capítulo &#62;]