include::./index.adoc[]

[[v4-6-0]]
=== Números, 6
// naa ?, NAA - Nova Almeida Atualizada

[[v4-6-1]]

^<<v4-6-1,1>>^ O Senhor  disse a Moisés:

[[v4-6-2]]

^<<v4-6-2,2>>^ — Fale aos filhos de Israel e diga-lhes: Quando alguém, seja homem seja mulher, fizer voto especial, o voto de nazireu, a fim de consagrar-se ao Senhor ,

[[v4-6-3]]

^<<v4-6-3,3>>^ deverá abster-se de vinho e de bebida forte. Não beberá vinagre de vinho, nem vinagre de bebida forte, nem tomará suco de uvas, nem comerá uvas frescas nem secas.

[[v4-6-4]]

^<<v4-6-4,4>>^ Todos os dias do seu nazireado não comerá nada que venha da videira, desde as sementes até as cascas.

[[v4-6-5]]

^<<v4-6-5,5>>^ Todos os dias do seu voto de nazireado não passará navalha pela cabeça; até que se cumpram os dias para os quais se consagrou ao Senhor , santo será, deixando o cabelo crescer livremente.

[[v4-6-6]]

^<<v4-6-6,6>>^ — Todos os dias da sua consagração ao Senhor , não se aproximará de um cadáver.

[[v4-6-7]]

^<<v4-6-7,7>>^ Mesmo que se trate de seu pai, de sua mãe, de seu irmão ou de sua irmã, por eles não se contaminará, quando morrerem; porque o nazireado do seu Deus está sobre a sua cabeça.

[[v4-6-8]]

^<<v4-6-8,8>>^ Por todos os dias do seu nazireado, será santo ao Senhor .

[[v4-6-9]]

^<<v4-6-9,9>>^ — Se alguém vier a morrer junto a ele subitamente, e contaminar a cabeça do seu nazireado, rapará a cabeça no dia da sua purificação; no sétimo dia, ele rapará a cabeça.

[[v4-6-10]]

^<<v4-6-10,10>>^ No oitavo dia, trará duas rolinhas ou dois pombinhos ao sacerdote, à porta da tenda do encontro.

[[v4-6-11]]

^<<v4-6-11,11>>^ O sacerdote oferecerá um como oferta pelo pecado e o outro, para holocausto; e fará expiação por ele, visto que pecou relativamente ao morto; assim, naquele mesmo dia, consagrará a sua cabeça.

[[v4-6-12]]

^<<v4-6-12,12>>^ Então consagrará os dias do seu nazireado ao Senhor  e, para oferta pela culpa, trará um cordeiro de um ano; os dias antecedentes serão perdidos, porque o seu nazireado foi contaminado.

[[v4-6-13]]

^<<v4-6-13,13>>^ — Esta é a lei para o nazireu: no dia em que se cumprirem os dias do seu nazireado, será trazido à porta da tenda do encontro.

[[v4-6-14]]

^<<v4-6-14,14>>^ Ele apresentará a sua oferta ao Senhor , um cordeiro de um ano, sem defeito, em holocausto, e uma cordeira de um ano, sem defeito, para oferta pelo pecado, e um carneiro, sem defeito, por oferta pacífica,

[[v4-6-15]]

^<<v4-6-15,15>>^ e um cesto de pães sem fermento, bolos feitos com a melhor farinha com azeite, amassados, e pãezinhos bem finos feitos sem fermento e untados com azeite, bem como a sua oferta de cereais e as suas libações.

[[v4-6-16]]

^<<v4-6-16,16>>^ O sacerdote os trará diante do Senhor  e apresentará a oferta pelo pecado e o holocausto.

[[v4-6-17]]

^<<v4-6-17,17>>^ Oferecerá o carneiro em sacrifício pacífico ao Senhor , com o cesto dos pães sem fermento. O sacerdote apresentará também a devida oferta de cereais e a libação.

[[v4-6-18]]

^<<v4-6-18,18>>^ O nazireu, à porta da tenda do encontro, rapará a cabeleira do seu nazireado, e, pegando o cabelo, o porá sobre o fogo que está debaixo do sacrifício pacífico.

[[v4-6-19]]

^<<v4-6-19,19>>^ — Depois, o sacerdote pegará o quarto dianteiro do carneiro, já assado, um bolo sem fermento do cesto, e um pãozinho bem fino feito sem fermento e os porá nas mãos do nazireu, depois de haver este rapado o cabelo do seu nazireado.

[[v4-6-20]]

^<<v4-6-20,20>>^ O sacerdote os moverá em oferta movida diante do Senhor ; isto é santo para o sacerdote, juntamente com o peito da oferta movida e com a coxa da oferta; depois disto, o nazireu pode beber vinho.

[[v4-6-21]]

^<<v4-6-21,21>>^ — Esta é a lei para o nazireu que fizer voto. A sua oferta ao Senhor  será segundo o seu nazireado, além do que as suas posses lhe permitirem. Segundo o voto que fizer, assim fará conforme a lei a respeito do seu nazireado.

[[v4-6-22]]

^<<v4-6-22,22>>^ O Senhor  disse a Moisés:

[[v4-6-23]]

^<<v4-6-23,23>>^ — Fale com Arão e com os seus filhos, dizendo que abençoem os filhos de Israel do seguinte modo:

[[v4-6-24]]

^<<v4-6-24,24>>^ "O Senhor  os abençoe e os guarde;

[[v4-6-25]]

^<<v4-6-25,25>>^ o Senhor  faça resplandecer o seu rosto sobre vocês e tenha misericórdia de vocês;

[[v4-6-26]]

^<<v4-6-26,26>>^ o Senhor  sobre vocês levante o seu rosto e lhes dê a paz."

[[v4-6-27]]

^<<v4-6-27,27>>^ — Assim, os sacerdotes porão o meu nome sobre os filhos de Israel, e eu os abençoarei.

'''

xref:004-numeros/004-numeros-005.adoc#v4-5-0[&#60; Capítulo Anterior] | <<v4-6-0,Topo>> | xref:004-numeros/004-numeros-007.adoc#v4-7-0[Próximo Capítulo &#62;]