include::./index.adoc[]

[[v4-28-0]]
=== Números, 28
// naa ?, NAA - Nova Almeida Atualizada

[[v4-28-1]]

^<<v4-28-1,1>>^ O Senhor  disse a Moisés:

[[v4-28-2]]

^<<v4-28-2,2>>^ — Ordene aos filhos de Israel e diga-lhes: Tenham cuidado da minha oferta, do meu alimento para as minhas ofertas queimadas, do aroma agradável, para me trazer essas ofertas no tempo determinado.

[[v4-28-3]]

^<<v4-28-3,3>>^ — Diga aos filhos de Israel: Esta é a oferta queimada que vocês devem oferecer ao Senhor , dia após dia: dois cordeiros de um ano, sem defeito, em holocausto contínuo.

[[v4-28-4]]

^<<v4-28-4,4>>^ Um cordeiro será oferecido de manhã, e o outro, ao crepúsculo da tarde,

[[v4-28-5]]

^<<v4-28-5,5>>^ junto com dois litros da melhor farinha, em oferta de cereais, amassada com um litro de azeite batido.

[[v4-28-6]]

^<<v4-28-6,6>>^ É holocausto contínuo que foi instituído no monte Sinai, de aroma agradável, oferta queimada ao Senhor .

[[v4-28-7]]

^<<v4-28-7,7>>^ A libação que acompanha o holocausto será um litro para cada cordeiro. E esta libação de bebida forte ao Senhor  será oferecida no santuário.

[[v4-28-8]]

^<<v4-28-8,8>>^ O outro cordeiro você oferecerá no crepúsculo da tarde. Como a oferta de cereais da manhã e como a libação que a acompanha, você o trará em oferta queimada de aroma agradável ao Senhor .

[[v4-28-9]]

^<<v4-28-9,9>>^ — No dia de sábado, ofereçam dois cordeiros de um ano, sem defeito, e quatro litros da melhor farinha, amassada com azeite, em oferta de cereais, e a libação que a acompanha.

[[v4-28-10]]

^<<v4-28-10,10>>^ Este é o holocausto de cada sábado, além do holocausto contínuo e a libação que o acompanha.

[[v4-28-11]]

^<<v4-28-11,11>>^ — No princípio de cada mês, ofereçam em holocausto ao Senhor  dois novilhos e um carneiro, sete cordeiros de um ano, sem defeito,

[[v4-28-12]]

^<<v4-28-12,12>>^ e seis litros da melhor farinha, amassada com azeite, em oferta de cereais, para um novilho; quatro litros da melhor farinha, amassada com azeite, em oferta de cereais, para um carneiro;

[[v4-28-13]]

^<<v4-28-13,13>>^ e dois litros da melhor farinha, amassada com azeite, em oferta de cereais, para um cordeiro; é holocausto de aroma agradável, oferta queimada ao Senhor .

[[v4-28-14]]

^<<v4-28-14,14>>^ As libações que acompanham serão dois litros de vinho para um novilho, um litro e meio para um carneiro, e um litro para um cordeiro. Este é o holocausto da lua nova de cada mês, para todos os meses do ano.

[[v4-28-15]]

^<<v4-28-15,15>>^ Também se trará um bode como oferta pelo pecado, ao Senhor , além do holocausto contínuo, com a libação que o acompanha.

[[v4-28-16]]

^<<v4-28-16,16>>^ — No primeiro mês, aos catorze dias do mês, é a Páscoa do Senhor .

[[v4-28-17]]

^<<v4-28-17,17>>^ Aos quinze dias do mesmo mês, haverá festa; sete dias se comerão pães sem fermento.

[[v4-28-18]]

^<<v4-28-18,18>>^ No primeiro dia, haverá santa convocação; não façam nenhum trabalho nesse dia,

[[v4-28-19]]

^<<v4-28-19,19>>^ mas apresentem uma oferta queimada em holocausto ao Senhor , dois novilhos, um carneiro e sete cordeiros de um ano, todos sem defeito.

[[v4-28-20]]

^<<v4-28-20,20>>^ A oferta de cereais que acompanha o holocausto será a melhor farinha, amassada com azeite. Ofereçam seis quilos da melhor farinha para um novilho e quatro quilos para um carneiro.

[[v4-28-21]]

^<<v4-28-21,21>>^ Para cada um dos sete cordeiros ofereçam dois quilos;

[[v4-28-22]]

^<<v4-28-22,22>>^ e um bode, para oferta pelo pecado, para fazer expiação por vocês.

[[v4-28-23]]

^<<v4-28-23,23>>^ Ofereçam estas coisas, além do holocausto da manhã, que é o holocausto contínuo.

[[v4-28-24]]

^<<v4-28-24,24>>^ Assim, ofereçam cada dia, durante sete dias, o alimento da oferta queimada em aroma agradável ao Senhor . Além do holocausto contínuo, ofereçam isto, juntamente com a libação que acompanha.

[[v4-28-25]]

^<<v4-28-25,25>>^ No sétimo dia, vocês terão santa convocação; não façam nenhum trabalho nesse dia.

[[v4-28-26]]

^<<v4-28-26,26>>^ — Vocês terão também santa convocação no dia das primícias, quando trouxerem oferta nova de cereais ao Senhor  durante a Festa das Semanas; não façam nenhum trabalho nesse dia.

[[v4-28-27]]

^<<v4-28-27,27>>^ Então ofereçam ao Senhor  por holocausto, em aroma agradável, dois novilhos, um carneiro e sete cordeiros de um ano.

[[v4-28-28]]

^<<v4-28-28,28>>^ A correspondente oferta de cereais da melhor farinha, amassada com azeite, será de seis litros para um novilho, quatro litros para um carneiro,

[[v4-28-29]]

^<<v4-28-29,29>>^ dois litros para cada um dos sete cordeiros.

[[v4-28-30]]

^<<v4-28-30,30>>^ Ofereçam também um bode, para fazer expiação por vocês.

[[v4-28-31]]

^<<v4-28-31,31>>^ Tragam todas estas ofertas, além do holocausto contínuo, da correspondente oferta de cereais, e das libações que a acompanham. Todos os animais devem ser sem defeito.

'''

xref:004-numeros/004-numeros-027.adoc#v4-27-0[&#60; Capítulo Anterior] | <<v4-28-0,Topo>> | xref:004-numeros/004-numeros-029.adoc#v4-29-0[Próximo Capítulo &#62;]