include::./index.adoc[]

[[v4-1-0]]
=== Números, 1
// naa ?, NAA - Nova Almeida Atualizada

[[v4-1-1]]

^<<v4-1-1,1>>^ No segundo ano após a saída dos filhos de Israel do Egito, no primeiro dia do segundo mês, o Senhor  falou a Moisés, no deserto do Sinai, na tenda do encontro, dizendo:

[[v4-1-2]]

^<<v4-1-2,2>>^ — Levantem o censo de toda a congregação dos filhos de Israel, segundo as suas famílias, segundo a casa de seus pais, contando todos os homens, nominalmente, cabeça por cabeça.

[[v4-1-3]]

^<<v4-1-3,3>>^ Da idade de vinte anos para cima, todos os capazes de sair à guerra em Israel, a esses você e Arão devem contar segundo os seus exércitos.

[[v4-1-4]]

^<<v4-1-4,4>>^ De cada tribo vocês terão a ajuda de um homem que seja chefe da casa de seus pais.

[[v4-1-5]]

^<<v4-1-5,5>>^ — Estes, pois, são os nomes dos homens que ajudarão vocês: de Rúben, Elizur, filho de Sedeur;

[[v4-1-6]]

^<<v4-1-6,6>>^ de Simeão, Selumiel, filho de Zurisadai;

[[v4-1-7]]

^<<v4-1-7,7>>^ de Judá, Naassom, filho de Aminadabe;

[[v4-1-8]]

^<<v4-1-8,8>>^ de Issacar, Natanael, filho de Zuar;

[[v4-1-9]]

^<<v4-1-9,9>>^ de Zebulom, Eliabe, filho de Helom;

[[v4-1-10]]

^<<v4-1-10,10>>^ dos filhos de José: de Efraim, Elisama, filho de Amiúde; de Manassés, Gamaliel, filho de Pedazur;

[[v4-1-11]]

^<<v4-1-11,11>>^ de Benjamim, Abidã, filho de Gideoni;

[[v4-1-12]]

^<<v4-1-12,12>>^ de Dã, Aiezer, filho de Amisadai;

[[v4-1-13]]

^<<v4-1-13,13>>^ de Aser, Pagiel, filho de Ocrã;

[[v4-1-14]]

^<<v4-1-14,14>>^ de Gade, Eliasafe, filho de Deuel;

[[v4-1-15]]

^<<v4-1-15,15>>^ de Naftali, Aira, filho de Enã.

[[v4-1-16]]

^<<v4-1-16,16>>^ Estes foram os escolhidos da congregação, os chefes das tribos de seus pais, os cabeças dos milhares de Israel.

[[v4-1-17]]

^<<v4-1-17,17>>^ Então Moisés e Arão reuniram estes homens, que foram designados pelos seus nomes.

[[v4-1-18]]

^<<v4-1-18,18>>^ E, tendo ajuntado toda a congregação no primeiro dia do segundo mês, declararam a descendência deles, segundo as suas famílias, segundo a casa de seus pais, contados nominalmente, de vinte anos para cima, cabeça por cabeça.

[[v4-1-19]]

^<<v4-1-19,19>>^ Como o Senhor  havia ordenado a Moisés, assim os contou no deserto do Sinai.

[[v4-1-20]]

^<<v4-1-20,20>>^ Dos filhos de Rúben, o primogênito de Israel, as suas gerações, pelas suas famílias, segundo a casa de seus pais, contados nominalmente, cabeça por cabeça, todos os homens de vinte anos para cima, todos os capazes de sair à guerra,

[[v4-1-21]]

^<<v4-1-21,21>>^ foram contados deles, da tribo de Rúben, quarenta e seis mil e quinhentos.

[[v4-1-22]]

^<<v4-1-22,22>>^ Dos filhos de Simeão, as suas gerações, pelas suas famílias, segundo a casa de seus pais, contados nominalmente, cabeça por cabeça, todos os homens de vinte anos para cima, todos os capazes de sair à guerra,

[[v4-1-23]]

^<<v4-1-23,23>>^ foram contados deles, da tribo de Simeão, cinquenta e nove mil e trezentos.

[[v4-1-24]]

^<<v4-1-24,24>>^ Dos filhos de Gade, as suas gerações, pelas suas famílias, segundo a casa de seus pais, contados nominalmente, de vinte anos para cima, todos os capazes de sair à guerra,

[[v4-1-25]]

^<<v4-1-25,25>>^ foram contados deles, da tribo de Gade, quarenta e cinco mil seiscentos e cinquenta.

[[v4-1-26]]

^<<v4-1-26,26>>^ Dos filhos de Judá, as suas gerações, pelas suas famílias, segundo a casa de seus pais, contados nominalmente, de vinte anos para cima, todos os capazes de sair à guerra,

[[v4-1-27]]

^<<v4-1-27,27>>^ foram contados deles, da tribo de Judá, setenta e quatro mil e seiscentos.

[[v4-1-28]]

^<<v4-1-28,28>>^ Dos filhos de Issacar, as suas gerações, pelas suas famílias, segundo a casa de seus pais, contados nominalmente, de vinte anos para cima, todos os capazes de sair à guerra,

[[v4-1-29]]

^<<v4-1-29,29>>^ foram contados deles, da tribo de Issacar, cinquenta e quatro mil e quatrocentos.

[[v4-1-30]]

^<<v4-1-30,30>>^ Dos filhos de Zebulom, as suas gerações, pelas suas famílias, segundo a casa de seus pais, contados nominalmente, de vinte anos para cima, todos os capazes de sair à guerra,

[[v4-1-31]]

^<<v4-1-31,31>>^ foram contados deles, da tribo de Zebulom, cinquenta e sete mil e quatrocentos.

[[v4-1-32]]

^<<v4-1-32,32>>^ Dos filhos de José, dos filhos de Efraim, as suas gerações, pelas suas famílias, segundo a casa de seus pais, contados nominalmente, de vinte anos para cima, todos os capazes de sair à guerra,

[[v4-1-33]]

^<<v4-1-33,33>>^ foram contados deles, da tribo de Efraim, quarenta mil e quinhentos.

[[v4-1-34]]

^<<v4-1-34,34>>^ Dos filhos de Manassés, as suas gerações, pelas suas famílias, segundo a casa de seus pais, contados nominalmente, de vinte anos para cima, todos os capazes de sair à guerra,

[[v4-1-35]]

^<<v4-1-35,35>>^ foram contados deles, da tribo de Manassés, trinta e dois mil e duzentos.

[[v4-1-36]]

^<<v4-1-36,36>>^ Dos filhos de Benjamim, as suas gerações, pelas suas famílias, segundo a casa de seus pais, contados nominalmente, de vinte anos para cima, todos os capazes de sair à guerra,

[[v4-1-37]]

^<<v4-1-37,37>>^ foram contados deles, da tribo de Benjamim, trinta e cinco mil e quatrocentos.

[[v4-1-38]]

^<<v4-1-38,38>>^ Dos filhos de Dã, as suas gerações, pelas suas famílias, segundo a casa de seus pais, contados nominalmente, de vinte anos para cima, todos os capazes de sair à guerra,

[[v4-1-39]]

^<<v4-1-39,39>>^ foram contados deles, da tribo de Dã, sessenta e dois mil e setecentos.

[[v4-1-40]]

^<<v4-1-40,40>>^ Dos filhos de Aser, as suas gerações, pelas suas famílias, segundo a casa de seus pais, contados nominalmente, de vinte anos para cima, todos os capazes de sair à guerra,

[[v4-1-41]]

^<<v4-1-41,41>>^ foram contados deles, da tribo de Aser, quarenta e um mil e quinhentos.

[[v4-1-42]]

^<<v4-1-42,42>>^ Dos filhos de Naftali, as suas gerações, pelas suas famílias, segundo a casa de seus pais, contados nominalmente, de vinte anos para cima, todos os capazes de sair à guerra,

[[v4-1-43]]

^<<v4-1-43,43>>^ foram contados deles, da tribo de Naftali, cinquenta e três mil e quatrocentos.

[[v4-1-44]]

^<<v4-1-44,44>>^ Estes foram os homens contados, os quais Moisés e Arão contaram com os chefes de Israel, que eram doze homens, cada um representando a casa de seus pais.

[[v4-1-45]]

^<<v4-1-45,45>>^ Assim, pois, todos os contados dos filhos de Israel, segundo a casa de seus pais, de vinte anos para cima, todos os capazes de sair à guerra,

[[v4-1-46]]

^<<v4-1-46,46>>^ todos os contados foram seiscentos e três mil quinhentos e cinquenta.

[[v4-1-47]]

^<<v4-1-47,47>>^ Mas os levitas, segundo a tribo de seus pais, não foram contados entre eles,

[[v4-1-48]]

^<<v4-1-48,48>>^ porque o Senhor  havia falado a Moisés, dizendo:

[[v4-1-49]]

^<<v4-1-49,49>>^ "Somente não faça a contagem da tribo de Levi, nem levante o censo deles entre os filhos de Israel.

[[v4-1-50]]

^<<v4-1-50,50>>^ Mas encarregue os levitas de cuidarem do tabernáculo do testemunho, de todos os seus utensílios e de tudo o que nele se encontra. Eles levarão o tabernáculo e todos os seus utensílios; eles ministrarão no tabernáculo e acamparão ao redor dele.

[[v4-1-51]]

^<<v4-1-51,51>>^ Quando o tabernáculo partir, os levitas o desarmarão; e, quando o tabernáculo for armado outra vez, os levitas o farão; o estranho que se aproximar será morto.

[[v4-1-52]]

^<<v4-1-52,52>>^ Os filhos de Israel acamparão, cada um no seu arraial e cada um junto ao seu estandarte, segundo as suas turmas.

[[v4-1-53]]

^<<v4-1-53,53>>^ Mas os levitas acamparão ao redor do tabernáculo do testemunho, para que não haja ira sobre a congregação dos filhos de Israel. Os levitas assumirão a tarefa de cuidar do tabernáculo do testemunho."

[[v4-1-54]]

^<<v4-1-54,54>>^ Assim fizeram os filhos de Israel. Segundo tudo o que o Senhor  havia ordenado a Moisés, assim o fizeram.

'''

xref:003-levitico/003-levitico-027.adoc#v3-27-0[&#60; Capítulo Anterior] | <<v4-1-0,Topo>> | xref:004-numeros/004-numeros-002.adoc#v4-2-0[Próximo Capítulo &#62;]