include::./index.adoc[]

[[v11-7-0]]
=== 1 Reis, 7
// naa ?, NAA - Nova Almeida Atualizada

[[v11-7-1]]

^<<v11-7-1,1>>^ Salomão construiu o seu palácio e levou treze anos para concluí-lo.

[[v11-7-2]]

^<<v11-7-2,2>>^ Ele construiu a Casa do Bosque do Líbano, de quarenta e quatro metros de comprimento, vinte e dois de largura e treze e meio de altura, sobre quatro fileiras de colunas de cedro e vigas de cedro sobre as colunas.

[[v11-7-3]]

^<<v11-7-3,3>>^ A cobertura era de cedro, abrangendo as câmaras laterais em número de quarenta e cinco, apoiadas em colunas, distribuídas em três fileiras de quinze.

[[v11-7-4]]

^<<v11-7-4,4>>^ Havia janelas em três fileiras, uma em frente das outras, agrupadas de três em três.

[[v11-7-5]]

^<<v11-7-5,5>>^ Todas as portas e janelas eram quadradas, ficando umas em frente das outras em três fileiras.

[[v11-7-6]]

^<<v11-7-6,6>>^ Depois, fez o Salão das Colunas, de vinte e dois metros de comprimento e treze e meio de largura. Havia um pórtico de colunas diante dele, e uma área coberta na frente do pórtico.

[[v11-7-7]]

^<<v11-7-7,7>>^ Também fez a Sala do Trono, a saber, a Sala do Julgamento, onde Salomão julgava. Ela era revestida de cedro desde o chão até o teto.

[[v11-7-8]]

^<<v11-7-8,8>>^ A casa, em que haveria de morar, ele fez em outro pátio, atrás da Sala do Trono, e era uma obra semelhante à anterior. Salomão também fez uma casa semelhante à Sala do Trono para a filha de Faraó, que havia tomado por mulher.

[[v11-7-9]]

^<<v11-7-9,9>>^ Todas estas construções eram de pedras valiosas, cortadas sob medida, serradas para o lado de dentro e para o lado de fora; e isto desde os alicerces até as beiras do teto, e por fora até o átrio maior.

[[v11-7-10]]

^<<v11-7-10,10>>^ Os alicerces eram de pedras valiosas, pedras grandes; pedras de quatro metros e meio e pedras de três metros e meio;

[[v11-7-11]]

^<<v11-7-11,11>>^ por cima delas, pedras valiosas, cortadas sob medida, e cedros.

[[v11-7-12]]

^<<v11-7-12,12>>^ Ao redor do grande átrio, havia três fileiras de pedras cortadas e uma fileira de vigas de cedro; assim era também o átrio interior da Casa do Senhor  e o pórtico daquela casa.

[[v11-7-13]]

^<<v11-7-13,13>>^ O rei Salomão enviou mensageiros que trouxessem de Tiro um homem chamado Hirão.

[[v11-7-14]]

^<<v11-7-14,14>>^ Ele era filho de uma viúva, da tribo de Naftali, e o pai dele, já falecido, era um homem de Tiro que trabalhava em bronze. Hirão era cheio de sabedoria, de entendimento e de ciência para fazer todo tipo de trabalho em bronze. Ele se apresentou ao rei Salomão e fez toda a sua obra.

[[v11-7-15]]

^<<v11-7-15,15>>^ Hirão fundiu duas colunas de bronze. A altura de cada uma era de oito metros, e um fio de cinco metros e quarenta era a medida de sua circunferência.

[[v11-7-16]]

^<<v11-7-16,16>>^ Também fez dois capitéis de bronze para pôr sobre o alto das colunas. A altura de cada um deles era de dois metros e vinte.

[[v11-7-17]]

^<<v11-7-17,17>>^ Havia obra de rede e ornamentos torcidos em forma de corrente, para os capitéis que estavam sobre o alto das colunas; sete para um capitel e sete para o outro.

[[v11-7-18]]

^<<v11-7-18,18>>^ Fez também romãs em duas fileiras por cima de uma das obras de rede, para cobrir o capitel no alto da coluna; o mesmo fez com o outro capitel.

[[v11-7-19]]

^<<v11-7-19,19>>^ Os capitéis que estavam no alto das colunas tinham o formato de lírios, como na Sala do Trono, e tinham um metro e oitenta de altura.

[[v11-7-20]]

^<<v11-7-20,20>>^ Perto do bojo, próximo à obra de rede, os capitéis que estavam no alto das duas colunas tinham duzentas romãs, dispostas em fileiras ao redor, sobre um e outro capitel.

[[v11-7-21]]

^<<v11-7-21,21>>^ Depois, levantou as colunas no pórtico do templo. Tendo levantado a coluna da direita, deu-lhe o nome de Jaquim; e, tendo levantado a coluna da esquerda, deu-lhe o nome de Boaz.

[[v11-7-22]]

^<<v11-7-22,22>>^ No alto das colunas estava a obra na forma de lírios. E, assim, foi terminado o trabalho das colunas.

[[v11-7-23]]

^<<v11-7-23,23>>^ Hirão fez também o mar de fundição, redondo, de quatro metros e meio de uma borda até a outra, e de dois metros e vinte de altura; e um fio de treze metros e meio era a medida de sua circunferência.

[[v11-7-24]]

^<<v11-7-24,24>>^ Por baixo da sua borda, ao redor, havia ornamentos em forma de cabaças, dez a cada meio metro; estavam em duas fileiras, fundidas quando se fundiu o mar de fundição.

[[v11-7-25]]

^<<v11-7-25,25>>^ O mar de fundição se apoiava sobre doze touros de bronze. Três olhavam para o norte; três, para o oeste; três, para o sul; e três, para o leste. O mar de fundição se apoiava sobre eles, cujas partes posteriores convergiam para dentro.

[[v11-7-26]]

^<<v11-7-26,26>>^ A grossura das paredes desse mar era de quatro dedos, e a sua borda, como borda de copo, era como uma flor de lírio. Nele cabiam cerca de quarenta mil litros.

[[v11-7-27]]

^<<v11-7-27,27>>^ Hirão fez também dez suportes de bronze. Cada um media um metro e oitenta de comprimento, um metro e oitenta de largura e um metro e trinta de altura.

[[v11-7-28]]

^<<v11-7-28,28>>^ Os suportes eram do seguinte modo: tinham painéis, que estavam entre molduras,

[[v11-7-29]]

^<<v11-7-29,29>>^ nos quais havia leões, bois e querubins. Nas molduras de cima e de baixo dos leões e dos bois, pendiam grinaldas decorativas.

[[v11-7-30]]

^<<v11-7-30,30>>^ Cada suporte tinha quatro rodas de bronze e eixos de bronze; os seus quatro pés tinham apoios debaixo da pia, apoios fundidos, e ao lado de cada um havia grinaldas decorativas.

[[v11-7-31]]

^<<v11-7-31,31>>^ A boca dos suportes estava dentro de uma guarnição que media quarenta e cinco centímetros de altura; a boca era redonda como a obra de um pedestal e tinha sessenta e sete centímetros de diâmetro. Também nela havia entalhes, e os seus painéis eram quadrados, não redondos.

[[v11-7-32]]

^<<v11-7-32,32>>^ As quatro rodas estavam debaixo dos painéis, e os eixos das rodas formavam uma peça com o suporte; cada roda tinha sessenta e sete centímetros de altura.

[[v11-7-33]]

^<<v11-7-33,33>>^ As rodas eram como as de um carro: os seus eixos, aros, raios e cubos eram todos fundidos.

[[v11-7-34]]

^<<v11-7-34,34>>^ Havia quatro apoios aos quatro cantos de cada suporte, que com este formavam uma peça.

[[v11-7-35]]

^<<v11-7-35,35>>^ No alto de cada suporte havia um cilindro de vinte e dois centímetros de altura; também, no alto de cada suporte, os apoios e painéis formavam uma só peça com ele.

[[v11-7-36]]

^<<v11-7-36,36>>^ Na superfície dos seus apoios e dos seus painéis, gravou querubins, leões e palmeiras, segundo o espaço de cada um, com grinaldas ao redor.

[[v11-7-37]]

^<<v11-7-37,37>>^ Deste modo, fez os dez suportes; todos tinham a mesma fundição, o mesmo tamanho e o mesmo entalhe.

[[v11-7-38]]

^<<v11-7-38,38>>^ Hirão também fez dez pias de bronze. Em cada uma cabiam cerca de oitocentos litros, e cada uma tinha um metro e oitenta de diâmetro. Sobre cada um dos dez suportes estava uma pia.

[[v11-7-39]]

^<<v11-7-39,39>>^ Pôs cinco suportes à direita do templo e cinco, à esquerda; porém o mar ele pôs ao lado direito do templo, para o lado sudeste.

[[v11-7-40]]

^<<v11-7-40,40>>^ Depois Hirão fez os caldeirões, as pás e as bacias. E assim ele terminou de fazer toda a obra para o rei Salomão, para a Casa do Senhor :

[[v11-7-41]]

^<<v11-7-41,41>>^ as duas colunas; os dois capitéis redondos que estavam no alto das duas colunas; as duas redes, para cobrirem os dois capitéis redondos que estavam no alto das colunas;

[[v11-7-42]]

^<<v11-7-42,42>>^ as quatrocentas romãs para as duas redes, isto é, duas fileiras de romãs para cada rede, para cobrirem os dois capitéis redondos que estavam no alto das colunas;

[[v11-7-43]]

^<<v11-7-43,43>>^ os dez suportes e as dez pias sobre eles;

[[v11-7-44]]

^<<v11-7-44,44>>^ o mar de fundição com os doze touros por baixo;

[[v11-7-45]]

^<<v11-7-45,45>>^ os caldeirões, as pás e as bacias. Todos estes utensílios que Hirão fez para o rei Salomão, para a Casa do Senhor , eram de bronze polido.

[[v11-7-46]]

^<<v11-7-46,46>>^ O rei os fez fundir em terra barrenta, na planície do Jordão, entre Sucote e Zaretã.

[[v11-7-47]]

^<<v11-7-47,47>>^ Salomão deixou de pesar todos os utensílios devido ao seu excessivo número, não se verificando, portanto, o peso do bronze.

[[v11-7-48]]

^<<v11-7-48,48>>^ Salomão também mandou fazer todos os utensílios do Santo Lugar do Senhor : o altar de ouro e a mesa de ouro, sobre a qual estavam os pães da proposição;

[[v11-7-49]]

^<<v11-7-49,49>>^ os candelabros de ouro finíssimo, cinco à direita e cinco à esquerda, diante do Santo dos Santos; as flores, as lâmpadas e as tesouras de cortar pavios, também de ouro;

[[v11-7-50]]

^<<v11-7-50,50>>^ também as taças, os apagadores, as bacias, os recipientes para incenso e os braseiros, de ouro finíssimo; as dobradiças para as portas da casa interior, que é o Santo dos Santos, e as das portas do Santo Lugar do templo, também de ouro.

[[v11-7-51]]

^<<v11-7-51,51>>^ Quando o rei Salomão terminou toda a obra que fez para a Casa do Senhor , trouxe as coisas que Davi, seu pai, havia dedicado: a prata, o ouro e os utensílios. Salomão pôs tudo isso entre os tesouros da Casa do Senhor .

'''

xref:011-1-reis/011-1-reis-006.adoc#v11-6-0[&#60; Capítulo Anterior] | <<v11-7-0,Topo>> | xref:011-1-reis/011-1-reis-008.adoc#v11-8-0[Próximo Capítulo &#62;]