include::./index.adoc[]

[[v11-2-0]]
=== 1 Reis, 2
// naa ?, NAA - Nova Almeida Atualizada

[[v11-2-1]]

^<<v11-2-1,1>>^ Quando se aproximava o dia da morte de Davi, ele deu ordens a Salomão, seu filho, dizendo:

[[v11-2-2]]

^<<v11-2-2,2>>^ — Eu vou pelo caminho de todos os mortais. Portanto, tenha coragem e seja homem!

[[v11-2-3]]

^<<v11-2-3,3>>^ Guarde os preceitos do Senhor , seu Deus, andando nos seus caminhos, guardando os seus estatutos, os seus mandamentos, os seus juízos e os seus testemunhos, como está escrito na Lei de Moisés. Assim, você será bem-sucedido em tudo o que fizer e por onde quer que você for,

[[v11-2-4]]

^<<v11-2-4,4>>^ e o Senhor  confirmará a promessa que me fez, dizendo: "Se os seus filhos guardarem o seu caminho, andando diante de mim fielmente, de todo o seu coração e de toda a sua alma, nunca lhe faltará sucessor ao trono de Israel."

[[v11-2-5]]

^<<v11-2-5,5>>^ — Você também sabe o que me fez Joabe, filho de Zeruia, e o que fez com os dois comandantes do exército de Israel, com Abner, filho de Ner, e com Amasa, filho de Jéter. Ele os matou e, em tempo de paz, vingou o sangue derramado em tempo de guerra, manchando com ele o cinto que trazia nos lombos e as sandálias nos pés.

[[v11-2-6]]

^<<v11-2-6,6>>^ Portanto, faça segundo a sabedoria que você tem e não permita que ele morra em paz com idade avançada.

[[v11-2-7]]

^<<v11-2-7,7>>^ Mas seja bondoso com os filhos de Barzilai, o gileadita, e que eles estejam entre os que sentam à sua mesa para comer, porque estiveram ao meu lado quando eu fugia por causa do seu irmão Absalão.

[[v11-2-8]]

^<<v11-2-8,8>>^ — Eis que você também terá de lidar com Simei, filho de Gera, filho de Benjamim, de Baurim, que me lançou uma terrível maldição no dia em que eu ia a Maanaim. Porém ele veio ao meu encontro junto ao Jordão, e eu, pelo Senhor , lhe jurei, dizendo que não o mataria à espada.

[[v11-2-9]]

^<<v11-2-9,9>>^ Mas, agora, não o tenha por inocente, pois você é um homem sábio e bem saberá o que deve fazer com ele para que ele seja sepultado com os cabelos brancos manchados de sangue.

[[v11-2-10]]

^<<v11-2-10,10>>^ Davi morreu e foi sepultado na Cidade de Davi.

[[v11-2-11]]

^<<v11-2-11,11>>^ Davi reinou sobre Israel durante quarenta anos: sete anos em Hebrom e trinta e três em Jerusalém.

[[v11-2-12]]

^<<v11-2-12,12>>^ Salomão assentou-se no trono de Davi, seu pai, e o seu reino se fortificou muito.

[[v11-2-13]]

^<<v11-2-13,13>>^ Então Adonias, filho de Hagite, foi até Bate-Seba, mãe de Salomão. Ela perguntou: — É de paz a sua vinda? E ele respondeu: — Sim, é de paz.

[[v11-2-14]]

^<<v11-2-14,14>>^ E acrescentou: — Tenho uma coisa para lhe dizer. Ela disse: — Fale.

[[v11-2-15]]

^<<v11-2-15,15>>^ Então Adonias disse: — A senhora bem sabe que o reino era meu e que todo o Israel esperava que eu reinasse. Mas o reino se transferiu e veio a ser de meu irmão, porque do Senhor  ele o recebeu.

[[v11-2-16]]

^<<v11-2-16,16>>^ Agora um só pedido lhe faço e peço que não me seja recusado. Ela lhe disse: — Fale.

[[v11-2-17]]

^<<v11-2-17,17>>^ Então Adonias disse: — Peço que a senhora fale com o rei Salomão, que não recusará um pedido seu, para que ele me dê por mulher Abisague, a sunamita.

[[v11-2-18]]

^<<v11-2-18,18>>^ Ao que Bate-Seba respondeu: — Está bem, eu falarei por você ao rei.

[[v11-2-19]]

^<<v11-2-19,19>>^ Então Bate-Seba foi até o rei Salomão, para falar-lhe em favor de Adonias. O rei se levantou para recebê-la e se inclinou diante dela. Depois se assentou no seu trono e mandou pôr uma cadeira para a sua mãe, e ela se assentou à sua direita.

[[v11-2-20]]

^<<v11-2-20,20>>^ Então Bate-Seba disse: — Só um pequeno pedido lhe faço e peço que não me seja recusado. E o rei disse: — Pode pedir, minha mãe, porque não recusarei um pedido seu.

[[v11-2-21]]

^<<v11-2-21,21>>^ Bate-Seba disse: — Peço que Abisague, a sunamita, seja dada por mulher a Adonias, seu irmão.

[[v11-2-22]]

^<<v11-2-22,22>>^ Então o rei Salomão disse à sua mãe: — Por que a senhora pede Abisague, a sunamita, para Adonias? Peça também para ele o reino, porque é meu irmão mais velho. Sim, para ele, e também para o sacerdote Abiatar e para Joabe, filho de Zeruia.

[[v11-2-23]]

^<<v11-2-23,23>>^ E o rei Salomão jurou pelo Senhor , dizendo: — Que Deus me castigue, se Adonias não falou esta palavra contra a sua própria vida.

[[v11-2-24]]

^<<v11-2-24,24>>^ E agora, tão certo como vive o Senhor , que me estabeleceu e me fez assentar no trono de Davi, meu pai, e me edificou casa, como tinha dito, Adonias morrerá no dia de hoje.

[[v11-2-25]]

^<<v11-2-25,25>>^ E o rei Salomão enviou Benaia, filho de Joiada, para atacar Adonias. Ele o atacou e foi assim que Adonias morreu.

[[v11-2-26]]

^<<v11-2-26,26>>^ E ao sacerdote Abiatar o rei disse: — Vá para Anatote, para os seus campos, porque você é homem digno de morte. Hoje, porém, não o matarei, porque você levou a arca do Senhor  Deus diante de Davi, meu pai, e porque se afligiu com todas as aflições de meu pai.

[[v11-2-27]]

^<<v11-2-27,27>>^ Salomão expulsou Abiatar, para que não mais fosse sacerdote do Senhor , cumprindo, assim, a palavra que o Senhor  tinha dito a respeito da casa de Eli, em Siló.

[[v11-2-28]]

^<<v11-2-28,28>>^ Quando esta notícia chegou a Joabe — porque Joabe tinha se desviado para seguir Adonias, embora não tivesse se desviado para seguir Absalão —, ele fugiu para o tabernáculo do Senhor  e pegou nas pontas do altar.

[[v11-2-29]]

^<<v11-2-29,29>>^ E alguém foi dizer ao rei Salomão que Joabe havia fugido para o tabernáculo do Senhor  e estava junto ao altar. Então Salomão enviou Benaia, filho de Joiada, dizendo: — Vá atacá-lo.

[[v11-2-30]]

^<<v11-2-30,30>>^ Benaia foi ao tabernáculo do Senhor  e disse a Joabe: — Assim diz o rei: "Saia daí." Ele respondeu: — Não saio! Vou morrer aqui. Então Benaia voltou com a resposta ao rei, dizendo: — Assim falou Joabe e foi isso que ele me respondeu.

[[v11-2-31]]

^<<v11-2-31,31>>^ E Salomão ordenou: — Faça o que ele disse. Mate-o e sepulte-o, para que você tire de mim e da casa de meu pai a culpa do sangue que Joabe derramou sem razão.

[[v11-2-32]]

^<<v11-2-32,32>>^ Assim, o Senhor  fará recair a culpa de sangue de Joabe sobre a cabeça dele, porque atacou dois homens mais justos e melhores do que ele e os matou à espada, sem que Davi, meu pai, o soubesse. Ele matou Abner, filho de Ner, comandante do exército de Israel, e Amasa, filho de Jéter, comandante do exército de Judá.

[[v11-2-33]]

^<<v11-2-33,33>>^ Assim, o sangue destes recairá sobre a cabeça de Joabe e sobre a cabeça da sua descendência para sempre; mas a Davi, à sua descendência, à sua casa e ao seu trono, o Senhor  dará paz para todo o sempre.

[[v11-2-34]]

^<<v11-2-34,34>>^ Então Benaia, filho de Joiada, atacou Joabe e o matou; e ele foi sepultado em sua casa, no deserto.

[[v11-2-35]]

^<<v11-2-35,35>>^ O rei pôs Benaia, filho de Joiada, como comandante do exército em lugar de Joabe, e, como sacerdote, colocou Zadoque em lugar de Abiatar.

[[v11-2-36]]

^<<v11-2-36,36>>^ Depois o rei mandou chamar Simei e lhe disse: — Construa uma casa para você em Jerusalém e fique morando aí. Não saia daí, nem para um lugar nem para outro.

[[v11-2-37]]

^<<v11-2-37,37>>^ Fique sabendo que, no dia em que você sair e passar o ribeiro de Cedrom, certamente será morto; então o seu sangue cairá sobre a sua cabeça.

[[v11-2-38]]

^<<v11-2-38,38>>^ Simei disse ao rei: — Está bem. Este seu servo fará o que o rei, meu senhor, ordenou. E Simei ficou morando em Jerusalém por muito tempo.

[[v11-2-39]]

^<<v11-2-39,39>>^ Mas, ao final de três anos, dois escravos de Simei fugiram para Aquis, filho de Maaca, rei de Gate. E foram contar isso a Simei, dizendo: — Eis que os seus escravos estão na cidade de Gate.

[[v11-2-40]]

^<<v11-2-40,40>>^ Então Simei se levantou, preparou o seu jumento e foi até Gate, para junto de Aquis, em busca dos seus escravos. Simei foi e trouxe de Gate os seus escravos.

[[v11-2-41]]

^<<v11-2-41,41>>^ Salomão foi avisado de que Simei tinha ido de Jerusalém a Gate e que já havia voltado.

[[v11-2-42]]

^<<v11-2-42,42>>^ Então o rei mandou chamar Simei e lhe disse: — Eu não fiz você jurar pelo Senhor  e não o avisei, dizendo: "No dia em que você sair para um lado ou para outro, saiba que você certamente será morto"? E você me disse: "Está bem; concordo."

[[v11-2-43]]

^<<v11-2-43,43>>^ Por que, então, você não guardou o juramento do Senhor , nem a ordem que lhe dei?

[[v11-2-44]]

^<<v11-2-44,44>>^ E o rei disse mais a Simei: — Você sabe muito bem e o seu coração reconhece todo o mal que fez a Davi, meu pai; por isso o Senhor  fez recair sobre a sua cabeça o mal que você fez.

[[v11-2-45]]

^<<v11-2-45,45>>^ Mas o rei Salomão será abençoado, e o trono de Davi será mantido diante do Senhor , para sempre.

[[v11-2-46]]

^<<v11-2-46,46>>^ O rei deu ordem a Benaia, filho de Joiada, e ele saiu, atacou Simei e o matou. E assim se firmou o reino sob o domínio de Salomão.

'''

xref:011-1-reis/011-1-reis-001.adoc#v11-1-0[&#60; Capítulo Anterior] | <<v11-2-0,Topo>> | xref:011-1-reis/011-1-reis-003.adoc#v11-3-0[Próximo Capítulo &#62;]