include::./index.adoc[]

[[v11-13-0]]
=== 1 Reis, 13
// naa ?, NAA - Nova Almeida Atualizada

[[v11-13-1]]

^<<v11-13-1,1>>^ Eis que, por ordem do Senhor , um homem de Deus foi de Judá a Betel; e Jeroboão estava junto ao altar, para queimar incenso.

[[v11-13-2]]

^<<v11-13-2,2>>^ Por ordem do Senhor , o profeta clamou contra o altar e disse: — Altar, altar! Assim diz o Senhor : "Eis que um filho nascerá à casa de Davi, cujo nome será Josias. Em cima de você ele sacrificará os sacerdotes dos lugares altos que queimam incenso em cima de você. Ossos humanos serão queimados em cima de você."

[[v11-13-3]]

^<<v11-13-3,3>>^ Naquele mesmo dia o profeta deu um sinal, dizendo: — Este é o sinal de que foi o Senhor  quem falou: Eis que o altar se fenderá, e as cinzas que estão sobre ele se espalharão.

[[v11-13-4]]

^<<v11-13-4,4>>^ Quando o rei ouviu as palavras que o homem de Deus proferiu contra o altar de Betel, Jeroboão estendeu a mão de sobre o altar, dizendo: — Prendam esse homem! Mas a mão que ele tinha estendido contra o homem de Deus secou, e ele não a podia recolher.

[[v11-13-5]]

^<<v11-13-5,5>>^ O altar se fendeu, e as cinzas se espalharam pelo chão, conforme o sinal que o homem de Deus tinha dado por ordem do Senhor .

[[v11-13-6]]

^<<v11-13-6,6>>^ Então o rei disse ao homem de Deus: — Implore o favor do Senhor , seu Deus, e ore por mim, para que eu possa recolher a mão. O homem de Deus implorou o favor do Senhor , e a mão do rei se recolheu e ficou como antes.

[[v11-13-7]]

^<<v11-13-7,7>>^ Então o rei disse ao homem de Deus: — Venha comigo até a minha casa e coma alguma coisa; e eu o recompensarei.

[[v11-13-8]]

^<<v11-13-8,8>>^ Porém o homem de Deus disse ao rei: — Ainda que me desse a metade da sua casa, eu não o acompanharia e não comeria nem beberia nada neste lugar.

[[v11-13-9]]

^<<v11-13-9,9>>^ Porque assim me ordenou o Senhor  Deus pela sua palavra, dizendo: "Não coma nem beba nada naquele lugar; e não volte pelo caminho por onde você foi."

[[v11-13-10]]

^<<v11-13-10,10>>^ E ele se foi por outro caminho, e não voltou pelo caminho por onde tinha ido a Betel.

[[v11-13-11]]

^<<v11-13-11,11>>^ Em Betel morava um velho profeta. Os seus filhos vieram e lhe contaram tudo o que o homem de Deus havia feito naquele dia em Betel. Também lhe contaram as palavras que ele tinha dito ao rei.

[[v11-13-12]]

^<<v11-13-12,12>>^ Então o pai perguntou aos seus filhos: — Por que caminho ele se foi? E eles lhe mostraram o caminho que havia sido tomado pelo homem de Deus que tinha vindo de Judá.

[[v11-13-13]]

^<<v11-13-13,13>>^ Então ele disse aos seus filhos: — Ponham a sela no meu jumento. Eles puseram a sela no jumento, e o profeta montou.

[[v11-13-14]]

^<<v11-13-14,14>>^ Então ele foi atrás do homem de Deus e, achando-o sentado debaixo de um carvalho, perguntou-lhe: — Você é o homem de Deus que veio de Judá? Ele respondeu: — Sou eu mesmo.

[[v11-13-15]]

^<<v11-13-15,15>>^ Então o velho profeta lhe disse: — Venha comigo até a minha casa e coma alguma coisa.

[[v11-13-16]]

^<<v11-13-16,16>>^ Mas o profeta de Judá respondeu: — Não posso voltar com você, nem entrar em sua casa. Não posso comer nem beber nada com você neste lugar.

[[v11-13-17]]

^<<v11-13-17,17>>^ Porque me foi dito pela palavra do Senhor : "Ali, você não deve comer nem beber nada; também não deve voltar pelo caminho por onde foi."

[[v11-13-18]]

^<<v11-13-18,18>>^ O velho profeta respondeu: — Também eu sou profeta como você, e um anjo me falou por ordem do Senhor , dizendo: "Faça-o voltar com você à sua casa, para que coma e beba alguma coisa." Mas isso era mentira.

[[v11-13-19]]

^<<v11-13-19,19>>^ Então ele voltou com o velho profeta e comeu e bebeu na casa dele.

[[v11-13-20]]

^<<v11-13-20,20>>^ Estando eles à mesa, a palavra do Senhor  veio ao profeta que o tinha feito voltar,

[[v11-13-21]]

^<<v11-13-21,21>>^ e ele gritou para o homem de Deus que tinha vindo de Judá, dizendo: — Assim diz o Senhor : "Você foi rebelde à palavra do Senhor  e não guardou o mandamento que o Senhor , seu Deus, lhe havia ordenado.

[[v11-13-22]]

^<<v11-13-22,22>>^ Você voltou, comeu e bebeu no lugar onde ele havia ordenado que você não deveria comer nem beber. Por isso, o seu cadáver não será sepultado no sepulcro dos seus pais."

[[v11-13-23]]

^<<v11-13-23,23>>^ Depois que ele tinha comido e bebido, o velho profeta pôs a sela no jumento para o homem de Deus a quem ele tinha feito voltar.

[[v11-13-24]]

^<<v11-13-24,24>>^ Ele foi embora e, no caminho, um leão o encontrou e o matou. O cadáver dele ficou estendido no caminho, e o jumento e o leão ficaram parados junto ao cadáver.

[[v11-13-25]]

^<<v11-13-25,25>>^ Eis que alguns homens passaram e viram o corpo jogado no caminho, bem como o leão parado junto ao corpo. Então foram e o disseram na cidade onde o velho profeta morava.

[[v11-13-26]]

^<<v11-13-26,26>>^ Quando o profeta que o tinha feito voltar do caminho ouviu isso, disse: — É o homem de Deus que foi rebelde à palavra do Senhor . Por isso, o Senhor  o entregou ao leão, que o despedaçou e matou, segundo a palavra que o Senhor  lhe tinha dito.

[[v11-13-27]]

^<<v11-13-27,27>>^ Então disse aos seus filhos: — Ponham a sela no meu jumento. E eles fizeram o que o pai pediu.

[[v11-13-28]]

^<<v11-13-28,28>>^ Ele foi e encontrou o cadáver estendido no caminho, e o jumento e o leão parados junto ao cadáver. O leão não tinha devorado o corpo, nem despedaçado o jumento.

[[v11-13-29]]

^<<v11-13-29,29>>^ Então o profeta levantou o cadáver do homem de Deus, pôs sobre o jumento e o levou de volta. Assim, o velho profeta entrou na cidade, para o chorar e sepultar.

[[v11-13-30]]

^<<v11-13-30,30>>^ Depositou o cadáver no seu próprio sepulcro. E o prantearam, dizendo: — Ah, meu irmão!

[[v11-13-31]]

^<<v11-13-31,31>>^ Depois de o haver sepultado, disse aos seus filhos: — Quando eu morrer, sepultem-me no túmulo em que o homem de Deus está sepultado; ponham os meus ossos junto aos ossos dele.

[[v11-13-32]]

^<<v11-13-32,32>>^ Porque certamente se cumprirá o que por ordem do Senhor  ele clamou contra o altar que está em Betel e contra todos os templos que existem nos lugares altos das cidades de Samaria.

[[v11-13-33]]

^<<v11-13-33,33>>^ Depois destas coisas, Jeroboão ainda persistiu em seu mau caminho; e continuou a constituir pessoas tiradas do meio do povo como sacerdotes para os lugares altos; a quem o desejasse, ele consagrava para sacerdote dos lugares altos.

[[v11-13-34]]

^<<v11-13-34,34>>^ Isso se tornou em pecado à casa de Jeroboão, para destruí-la e extingui-la da face da terra.

'''

xref:011-1-reis/011-1-reis-012.adoc#v11-12-0[&#60; Capítulo Anterior] | <<v11-13-0,Topo>> | xref:011-1-reis/011-1-reis-014.adoc#v11-14-0[Próximo Capítulo &#62;]