include::./index.adoc[]

[[v11-15-0]]
=== 1 Reis, 15
// naa ?, NAA - Nova Almeida Atualizada

[[v11-15-1]]

^<<v11-15-1,1>>^ No décimo oitavo ano do reinado de Jeroboão, filho de Nebate, Abias começou a reinar sobre Judá.

[[v11-15-2]]

^<<v11-15-2,2>>^ Ele reinou três anos em Jerusalém. A mãe dele se chamava Maaca e era filha de Absalão.

[[v11-15-3]]

^<<v11-15-3,3>>^ Abias andou em todos os pecados que seu pai havia cometido antes dele, e o seu coração não foi fiel ao Senhor , seu Deus, como havia sido fiel o coração de Davi, seu pai.

[[v11-15-4]]

^<<v11-15-4,4>>^ Mas, por amor a Davi, o Senhor , seu Deus, lhe deu uma lâmpada em Jerusalém, levantando seu filho depois dele e dando estabilidade a Jerusalém.

[[v11-15-5]]

^<<v11-15-5,5>>^ Porque Davi fez o que era reto aos olhos do Senhor  e não se desviou em nada daquilo que o Senhor  lhe havia ordenado, em todos os dias da sua vida, a não ser no caso de Urias, o heteu.

[[v11-15-6]]

^<<v11-15-6,6>>^ Roboão e Jeroboão estiveram sempre em guerra.

[[v11-15-7]]

^<<v11-15-7,7>>^ Quanto aos demais atos de Abias e a tudo o que fez, não está tudo escrito no Livro da História dos Reis de Judá? Também houve guerra entre Abias e Jeroboão.

[[v11-15-8]]

^<<v11-15-8,8>>^ Abias morreu, e eles o sepultaram na Cidade de Davi. E Asa, seu filho, reinou em seu lugar.

[[v11-15-9]]

^<<v11-15-9,9>>^ No vigésimo ano do reinado de Jeroboão, rei de Israel, Asa começou a reinar sobre Judá.

[[v11-15-10]]

^<<v11-15-10,10>>^ Ele reinou quarenta e um anos em Jerusalém. A mãe dele se chamava Maaca, e era filha de Absalão.

[[v11-15-11]]

^<<v11-15-11,11>>^ Asa fez o que era reto aos olhos do Senhor , como Davi, seu pai.

[[v11-15-12]]

^<<v11-15-12,12>>^ Porque tirou da terra os prostitutos cultuais e removeu todos os ídolos que seus pais fizeram.

[[v11-15-13]]

^<<v11-15-13,13>>^ Ele depôs também Maaca, sua mãe, da dignidade de rainha-mãe, porque ela havia feito uma abominável imagem para servir de poste da deusa Aserá. O rei Asa destruiu essa imagem e a queimou no vale do Cedrom.

[[v11-15-14]]

^<<v11-15-14,14>>^ Os lugares altos, porém, não foram destruídos. No entanto, o coração de Asa foi fiel ao Senhor  durante toda a sua vida.

[[v11-15-15]]

^<<v11-15-15,15>>^ Ele trouxe à Casa do Senhor  as coisas consagradas por seu pai e as coisas que ele mesmo havia consagrado: prata, ouro e utensílios.

[[v11-15-16]]

^<<v11-15-16,16>>^ Asa e Baasa, rei de Israel, estiveram sempre em guerra.

[[v11-15-17]]

^<<v11-15-17,17>>^ Porque Baasa, rei de Israel, invadiu Judá e começou a edificar a cidade de Ramá, para impedir a entrada e a saída do território de Asa, rei de Judá.

[[v11-15-18]]

^<<v11-15-18,18>>^ Então Asa pegou toda a prata e ouro restantes nos tesouros da Casa do Senhor  e os tesouros do palácio real e os entregou aos seus servos. E o rei Asa os enviou a Ben-Hadade, filho de Tabrimom, filho de Heziom, rei da Síria, que morava em Damasco, dizendo:

[[v11-15-19]]

^<<v11-15-19,19>>^ — Que haja uma aliança entre mim e você, como houve entre o meu pai e o seu pai. Eis que estou lhe enviando um presente, prata e ouro. Vá e anule a sua aliança com Baasa, rei de Israel, para que ele se retire do meu território.

[[v11-15-20]]

^<<v11-15-20,20>>^ Ben-Hadade deu ouvidos ao rei Asa e enviou os capitães dos seus exércitos contra as cidades de Israel. Eles conquistaram Ijom, Dã, Abel-Bete-Maaca e toda a região de Quinerete, com toda a terra de Naftali.

[[v11-15-21]]

^<<v11-15-21,21>>^ Quando Baasa soube disso, deixou de edificar Ramá e ficou em Tirza.

[[v11-15-22]]

^<<v11-15-22,22>>^ Então o rei Asa fez apregoar por toda a região de Judá que todos, sem exceção, deviam ajudar a trazer de Ramá as pedras e a madeira que Baasa havia usado para edificá-la. Com elas o rei Asa edificou Geba de Benjamim e Mispa.

[[v11-15-23]]

^<<v11-15-23,23>>^ Quanto aos demais atos de Asa, a todo o seu poder, a tudo o que fez e às cidades que edificou, não está tudo escrito no Livro da História dos Reis de Judá? Porém, no tempo da sua velhice, foi atacado por uma doença nos pés.

[[v11-15-24]]

^<<v11-15-24,24>>^ Asa morreu e foi sepultado na Cidade de Davi, seu pai. E Josafá, seu filho, reinou em seu lugar.

[[v11-15-25]]

^<<v11-15-25,25>>^ Nadabe, filho de Jeroboão, começou a reinar sobre Israel no segundo ano do reinado de Asa, rei de Judá, e reinou sobre Israel dois anos.

[[v11-15-26]]

^<<v11-15-26,26>>^ Fez o que era mau aos olhos do Senhor  e andou nos caminhos de seu pai e no pecado que seu pai levou Israel a cometer.

[[v11-15-27]]

^<<v11-15-27,27>>^ Baasa, filho de Aías, da casa de Issacar, conspirou contra ele e o matou em Gibetom, que era dos filisteus, quando Nadabe e todo o Israel cercavam Gibetom.

[[v11-15-28]]

^<<v11-15-28,28>>^ No terceiro ano do reinado de Asa, rei de Judá, Baasa matou Nadabe e passou a reinar em seu lugar.

[[v11-15-29]]

^<<v11-15-29,29>>^ Logo que começou a reinar, matou toda a descendência de Jeroboão. Não deixou ninguém com vida; exterminou todos, segundo a palavra do Senhor , anunciada por meio do seu servo Aías, de Siló,

[[v11-15-30]]

^<<v11-15-30,30>>^ por causa dos pecados que Jeroboão havia cometido e pelos que havia levado Israel a cometer, por causa da provocação com que havia irritado o Senhor , Deus de Israel.

[[v11-15-31]]

^<<v11-15-31,31>>^ Quanto aos demais atos de Nadabe e a tudo o que fez, não está tudo escrito no Livro da História dos Reis de Israel?

[[v11-15-32]]

^<<v11-15-32,32>>^ Asa e Baasa, rei de Israel, estiveram sempre em guerra.

[[v11-15-33]]

^<<v11-15-33,33>>^ No terceiro ano do reinado de Asa, rei de Judá, Baasa, filho de Aías, começou a reinar sobre todo o Israel, em Tirza, e reinou vinte e quatro anos.

[[v11-15-34]]

^<<v11-15-34,34>>^ Fez o que era mau aos olhos do Senhor  e andou no caminho de Jeroboão e no seu pecado, o qual havia feito Israel cometer.

'''

xref:011-1-reis/011-1-reis-014.adoc#v11-14-0[&#60; Capítulo Anterior] | <<v11-15-0,Topo>> | xref:011-1-reis/011-1-reis-016.adoc#v11-16-0[Próximo Capítulo &#62;]