include::./index.adoc[]

[[v11-4-0]]
=== 1 Reis, 4
// naa ?, NAA - Nova Almeida Atualizada

[[v11-4-1]]

^<<v11-4-1,1>>^ O rei Salomão reinou sobre todo o Israel.

[[v11-4-2]]

^<<v11-4-2,2>>^ E estes eram os seus altos oficiais: Azarias, filho de Zadoque, era o sacerdote;

[[v11-4-3]]

^<<v11-4-3,3>>^ Eliorefe e Aías, filhos de Sisa, eram secretários; Josafá, filho de Ailude, era o cronista;

[[v11-4-4]]

^<<v11-4-4,4>>^ Benaia, filho de Joiada, era comandante do exército; Zadoque e Abiatar eram sacerdotes;

[[v11-4-5]]

^<<v11-4-5,5>>^ Azarias, filho de Natã, era governador-chefe; Zabude, filho de Natã, era ministro e amigo do rei;

[[v11-4-6]]

^<<v11-4-6,6>>^ Aisar era o responsável pelo palácio; Adonirão, filho de Abda, era superintendente dos que realizavam trabalhos forçados.

[[v11-4-7]]

^<<v11-4-7,7>>^ Salomão tinha doze governadores sobre todo o Israel, que forneciam mantimento ao rei e ao seu palácio; cada um tinha de fornecer durante um mês do ano.

[[v11-4-8]]

^<<v11-4-8,8>>^ São estes os seus nomes: Ben-Hur, nas montanhas de Efraim;

[[v11-4-9]]

^<<v11-4-9,9>>^ Ben-Dequer, em Macaz, Saalabim, Bete-Semes, Elom e Bete-Hanã;

[[v11-4-10]]

^<<v11-4-10,10>>^ Ben-Hesede, em Arubote, Socó e toda a terra de Héfer;

[[v11-4-11]]

^<<v11-4-11,11>>^ Ben-Abinadabe, que era casado com Tafate, filha de Salomão, em toda a cordilheira de Dor;

[[v11-4-12]]

^<<v11-4-12,12>>^ Baaná, filho de Ailude, em Taanaque, Megido, e toda a Bete-Seã, que fica perto de Zaretã, abaixo de Jezreel, desde Bete-Seã até Abel-Meolá, até além de Jocmeão;

[[v11-4-13]]

^<<v11-4-13,13>>^ Ben-Geber, em Ramote-Gileade, nas aldeias de Jair, filho de Manassés, que estão em Gileade e também na região de Argobe, em Basã, sessenta grandes cidades com muralhas e ferrolhos de bronze;

[[v11-4-14]]

^<<v11-4-14,14>>^ Ainadabe, filho de Ido, em Maanaim;

[[v11-4-15]]

^<<v11-4-15,15>>^ Aimaás, que era casado com Basemate, outra filha de Salomão, em Naftali;

[[v11-4-16]]

^<<v11-4-16,16>>^ Baaná, filho de Husai, em Aser e Bealote;

[[v11-4-17]]

^<<v11-4-17,17>>^ Josafá, filho de Parua, em Issacar;

[[v11-4-18]]

^<<v11-4-18,18>>^ Simei, filho de Elá, em Benjamim;

[[v11-4-19]]

^<<v11-4-19,19>>^ Geber, filho de Uri, na terra de Gileade, a terra de Seom, rei dos amorreus, e de Ogue, rei de Basã; e havia só um governador nesta região.

[[v11-4-20]]

^<<v11-4-20,20>>^ O povo de Judá e Israel era tão numeroso como a areia que está na praia do mar; eles comiam, bebiam e se alegravam.

[[v11-4-21]]

^<<v11-4-21,21>>^ Salomão dominava sobre todos os reinos desde o Eufrates até a terra dos filisteus e até a fronteira do Egito. Esses reinos pagavam tributo e serviram Salomão durante todos os dias da sua vida.

[[v11-4-22]]

^<<v11-4-22,22>>^ As provisões diárias de Salomão eram três mil quilos da melhor farinha e seis mil quilos de farinha;

[[v11-4-23]]

^<<v11-4-23,23>>^ dez bois gordos, vinte bois de pasto e cem carneiros, além dos veados, as gazelas, os corços e aves bem-tratadas.

[[v11-4-24]]

^<<v11-4-24,24>>^ Porque Salomão dominava sobre toda a região e sobre todos os reis do lado de cá do Eufrates, desde Tifsa até Gaza, e tinha paz em toda a região ao redor.

[[v11-4-25]]

^<<v11-4-25,25>>^ Judá e Israel habitavam seguros, cada um debaixo da sua videira e debaixo da sua figueira, desde Dã até Berseba, durante todos os dias de Salomão.

[[v11-4-26]]

^<<v11-4-26,26>>^ Salomão tinha também quatro mil cavalos em estrebarias, para os seus carros de guerra, e doze mil cavaleiros.

[[v11-4-27]]

^<<v11-4-27,27>>^ Os governadores forneciam provisões, cada um no seu mês, ao rei Salomão e a todos os que chegavam à sua mesa; coisa nenhuma deixavam faltar.

[[v11-4-28]]

^<<v11-4-28,28>>^ Também levavam a cevada e a palha para os cavalos e os ginetes, para o lugar onde estivesse o rei, segundo lhes havia sido prescrito.

[[v11-4-29]]

^<<v11-4-29,29>>^ Deus deu a Salomão sabedoria, entendimento fora do comum e uma inteligência tão vasta como a areia que está na praia do mar.

[[v11-4-30]]

^<<v11-4-30,30>>^ A sabedoria de Salomão era maior do que a de todos os homens do Oriente e do que toda a sabedoria dos egípcios.

[[v11-4-31]]

^<<v11-4-31,31>>^ Era mais sábio do que todos os homens: mais sábio do que Etã, ezraíta, e do que Hemã, Calcol e Darda, filhos de Maol. E a sua fama se espalhou por todas as nações ao redor.

[[v11-4-32]]

^<<v11-4-32,32>>^ Compôs três mil provérbios, e os seus cânticos foram mil e cinco.

[[v11-4-33]]

^<<v11-4-33,33>>^ Falou sobre todas as plantas, desde o cedro que está no Líbano até o hissopo que brota dos muros; também falou sobre os animais e as aves, os animais que rastejam e os peixes.

[[v11-4-34]]

^<<v11-4-34,34>>^ De todos os povos vinha gente para ouvir a sabedoria de Salomão, e também mensageiros de todos os reis da terra que tinham ouvido falar da sua sabedoria.

'''

xref:011-1-reis/011-1-reis-003.adoc#v11-3-0[&#60; Capítulo Anterior] | <<v11-4-0,Topo>> | xref:011-1-reis/011-1-reis-005.adoc#v11-5-0[Próximo Capítulo &#62;]