include::./index.adoc[]

[[v11-20-0]]
=== 1 Reis, 20
// naa ?, NAA - Nova Almeida Atualizada

[[v11-20-1]]

^<<v11-20-1,1>>^ Ben-Hadade, rei da Síria, reuniu todo o seu exército. Estavam com ele trinta e dois reis com seus cavalos e carros de guerra. Ele subiu, cercou Samaria e lutou contra ela.

[[v11-20-2]]

^<<v11-20-2,2>>^ Enviou mensageiros à cidade, a Acabe, rei de Israel,

[[v11-20-3]]

^<<v11-20-3,3>>^ que lhe disseram: — Assim diz Ben-Hadade: "A sua prata e o seu ouro são meus; as suas mulheres e os seus melhores filhos também são meus."

[[v11-20-4]]

^<<v11-20-4,4>>^ O rei de Israel respondeu: — Seja conforme a sua palavra, ó rei, meu senhor; eu sou seu, e tudo o que tenho é seu.

[[v11-20-5]]

^<<v11-20-5,5>>^ Os mensageiros voltaram a Acabe e disseram: — Assim diz Ben-Hadade: "Quando enviei mensageiros que dissessem: ‘A sua prata, o seu ouro, as suas mulheres e os seus filhos são meus’, era para que você os entregasse para mim.

[[v11-20-6]]

^<<v11-20-6,6>>^ Se amanhã a estas horas eu tiver de enviar os meus servos até você, eles vasculharão o seu palácio e as casas dos seus oficiais e meterão as mãos em tudo o que você tem de precioso e o levarão."

[[v11-20-7]]

^<<v11-20-7,7>>^ Então o rei de Israel chamou todos os anciãos da sua terra e lhes disse: — Como vocês podem notar e ver, este homem procura o mal. Mandou exigir as minhas mulheres, os meus filhos, a minha prata e o meu ouro, e não os neguei a ele.

[[v11-20-8]]

^<<v11-20-8,8>>^ Todos os anciãos e todo o povo lhe disseram: — Não lhe dê ouvidos e não consinta.

[[v11-20-9]]

^<<v11-20-9,9>>^ Então Acabe disse aos mensageiros de Ben-Hadade: — Digam ao rei, meu senhor: "Farei tudo o que você pediu a este seu servo na primeira vez, porém não posso fazer o que você está pedindo agora." E os mensageiros se foram e deram esta resposta.

[[v11-20-10]]

^<<v11-20-10,10>>^ Ben-Hadade tornou a enviar mensageiros, dizendo: — Que os deuses me castiguem, se o pó de Samaria bastar para encher as mãos de todo o povo que me segue.

[[v11-20-11]]

^<<v11-20-11,11>>^ Porém o rei de Israel respondeu: — Digam ao rei Ben-Hadade: "Quem se veste para a batalha não deve se gabar como aquele que está se despindo depois da vitória."

[[v11-20-12]]

^<<v11-20-12,12>>^ Ben-Hadade ouviu esta resposta quando ele e os outros reis estavam bebendo nas tendas. Então ele disse aos seus servos: — Preparem-se para atacar. E eles se prepararam para atacar a cidade.

[[v11-20-13]]

^<<v11-20-13,13>>^ Eis que um profeta foi até Acabe, rei de Israel, e lhe disse: — Assim diz o Senhor : "Você viu toda esta grande multidão? Eis que hoje a entregarei nas suas mãos, e você saberá que eu sou o Senhor ."

[[v11-20-14]]

^<<v11-20-14,14>>^ Acabe perguntou: — Por meio de quem se dará isto? Ele respondeu: — Assim diz o Senhor : "Pelos servos dos chefes das províncias." Acabe perguntou: — Quem começará a batalha? E o profeta respondeu: — Você!

[[v11-20-15]]

^<<v11-20-15,15>>^ Então Acabe contou os servos dos chefes das províncias, e eram duzentos e trinta e dois. Depois, contou todo o povo, todos os filhos de Israel, e eram sete mil.

[[v11-20-16]]

^<<v11-20-16,16>>^ Saíram ao meio-dia. Ben-Hadade, porém, estava bebendo e embriagando-se nas tendas, ele e os reis, os trinta e dois reis que o ajudavam.

[[v11-20-17]]

^<<v11-20-17,17>>^ Saíram primeiro os servos dos chefes das províncias. Ben-Hadade mandou observadores que lhe deram avisos, dizendo: — Uns homens estão saindo de Samaria.

[[v11-20-18]]

^<<v11-20-18,18>>^ Ele disse: — Se vieram tratar de paz, prendam-nos vivos; se vieram lutar, prendam-nos vivos também.

[[v11-20-19]]

^<<v11-20-19,19>>^ Os servos dos chefes das províncias e o exército que os seguia saíram da cidade,

[[v11-20-20]]

^<<v11-20-20,20>>^ e cada um matou o homem contra quem lutava. Os sírios fugiram, e Israel os perseguiu. Porém Ben-Hadade, rei da Síria, escapou a cavalo, com alguns cavaleiros.

[[v11-20-21]]

^<<v11-20-21,21>>^ O rei de Israel saiu e destroçou os cavalos e os carros de guerra dos sírios, impondo-lhes grande derrota.

[[v11-20-22]]

^<<v11-20-22,22>>^ Então o profeta foi até o rei de Israel e lhe disse: — Vá, seja forte, considere e veja o que vai fazer, porque daqui a um ano o rei da Síria voltará a atacar.

[[v11-20-23]]

^<<v11-20-23,23>>^ Os servos do rei da Síria lhe disseram: — Os deuses deles são deuses dos montes, e por isso eles foram mais fortes do que nós. Mas vamos lutar contra eles na planície, e, por certo, seremos mais fortes do que eles.

[[v11-20-24]]

^<<v11-20-24,24>>^ Portanto, faça o seguinte: tire os reis, cada um do seu lugar, e substitua-os por capitães,

[[v11-20-25]]

^<<v11-20-25,25>>^ e forme outro exército igual em número ao que você perdeu, com outros tantos cavalos e outros tantos carros de guerra. E vamos lutar contra eles na planície e, por certo, seremos mais fortes do que eles. O rei deu ouvidos ao que disseram e assim o fez.

[[v11-20-26]]

^<<v11-20-26,26>>^ Decorrido um ano, Ben-Hadade convocou os sírios e subiu a Afeca para lutar contra Israel.

[[v11-20-27]]

^<<v11-20-27,27>>^ Também os filhos de Israel foram reunidos para a batalha. Eles foram providos de mantimentos e marcharam contra os sírios. Os filhos de Israel acamparam de frente para eles, como dois pequenos rebanhos de cabras, mas os sírios enchiam a terra.

[[v11-20-28]]

^<<v11-20-28,28>>^ Um homem de Deus se aproximou e foi falar com o rei de Israel, dizendo: — Assim diz o Senhor : "Porque os sírios disseram que o Senhor  é deus dos montes e não dos vales, entregarei toda esta grande multidão nas suas mãos, e assim vocês saberão que eu sou o Senhor ."

[[v11-20-29]]

^<<v11-20-29,29>>^ Sete dias estiveram acampados uns em frente dos outros. No sétimo dia, travou-se a batalha, e os filhos de Israel, num só dia, mataram dos sírios cem mil soldados da infantaria.

[[v11-20-30]]

^<<v11-20-30,30>>^ Os restantes fugiram para Afeca e entraram na cidade, mas a muralha da cidade caiu sobre os vinte e sete mil homens que restaram. Ben-Hadade fugiu, veio à cidade e se escondia de câmara em câmara.

[[v11-20-31]]

^<<v11-20-31,31>>^ Então os seus servos lhe disseram: — Eis que temos ouvido que os reis da casa de Israel são reis clementes. Por isso, ponhamos panos de saco sobre os lombos e cordas ao redor da cabeça e vamos até o rei de Israel; pode ser que ele lhe poupe a vida.

[[v11-20-32]]

^<<v11-20-32,32>>^ Então se cingiram com pano de saco pelos lombos, puseram cordas ao redor da cabeça e foram falar com o rei de Israel. Disseram: — O seu servo Ben-Hadade manda dizer: "Poupe-me a vida." Acabe respondeu: — Então ele ainda está vivo? Ele é meu irmão.

[[v11-20-33]]

^<<v11-20-33,33>>^ Aqueles homens tomaram isto como um bom sinal, logo se aproveitaram dessa palavra e disseram: — Sim, o seu irmão Ben-Hadade! O rei disse: — Vão e tragam-no aqui. Então Ben-Hadade saiu para se encontrar com Acabe, e este o fez subir na sua carruagem.

[[v11-20-34]]

^<<v11-20-34,34>>^ Ben-Hadade lhe disse: — Vou restituir as cidades que o meu pai tomou do seu pai. Você poderá vender os seus produtos em Damasco, como o meu pai fez em Samaria. E Acabe respondeu: — Com esta aliança, deixarei que você fique livre. Então Acabe fez uma aliança com ele e o deixou ir embora.

[[v11-20-35]]

^<<v11-20-35,35>>^ Então, por ordem do Senhor , um dos discípulos dos profetas disse ao seu companheiro: — Por favor, me esmurre. Mas o homem se recusou a fazê-lo,

[[v11-20-36]]

^<<v11-20-36,36>>^ e por isso o discípulo dos profetas lhe disse: — Visto que você não obedeceu à voz do Senhor , eis que, tão logo você se afastar de mim, um leão o matará. Quando ele se afastou, um leão o encontrou e o matou.

[[v11-20-37]]

^<<v11-20-37,37>>^ Então o profeta encontrou outro homem e lhe disse: — Por favor, me esmurre. Ele o esmurrou e o feriu.

[[v11-20-38]]

^<<v11-20-38,38>>^ Então o profeta partiu e ficou esperando o rei no caminho, disfarçado com uma venda sobre os olhos.

[[v11-20-39]]

^<<v11-20-39,39>>^ Quando o rei ia passando, o profeta gritou: — Este seu servo estava saindo do meio da batalha, quando um companheiro se voltou e me trouxe um homem, dizendo: "Vigie este homem. Se ele escapar, será a sua vida pela vida dele ou você pagará trinta e quatro quilos de prata."

[[v11-20-40]]

^<<v11-20-40,40>>^ Enquanto este seu servo estava ocupado daqui e dali, o homem se foi. O rei de Israel respondeu: — Esta é a sua sentença. Você mesmo a pronunciou.

[[v11-20-41]]

^<<v11-20-41,41>>^ Então ele se apressou e tirou a venda dos olhos, e o rei de Israel reconheceu que era um dos profetas.

[[v11-20-42]]

^<<v11-20-42,42>>^ E o profeta disse ao rei: — Assim diz o Senhor : "Porque você soltou o homem que eu havia condenado, será a sua vida pela vida dele e o seu povo pelo povo dele."

[[v11-20-43]]

^<<v11-20-43,43>>^ Então o rei de Israel se dirigiu à sua casa, aborrecido e indignado, e chegou a Samaria.

'''

xref:011-1-reis/011-1-reis-019.adoc#v11-19-0[&#60; Capítulo Anterior] | <<v11-20-0,Topo>> | xref:011-1-reis/011-1-reis-021.adoc#v11-21-0[Próximo Capítulo &#62;]