include::./index.adoc[]

[[v11-19-0]]
=== 1 Reis, 19
// naa ?, NAA - Nova Almeida Atualizada

[[v11-19-1]]

^<<v11-19-1,1>>^ Acabe contou a Jezabel tudo o que Elias havia feito e como havia matado todos os profetas à espada.

[[v11-19-2]]

^<<v11-19-2,2>>^ Então Jezabel mandou um mensageiro a Elias para dizer-lhe: — Que os deuses me castiguem se amanhã a estas horas eu não tiver feito com a sua vida o mesmo que você fez com a vida de cada um deles!

[[v11-19-3]]

^<<v11-19-3,3>>^ Elias ficou com medo, levantou-se e, para salvar a vida, se foi e chegou a Berseba, que pertence a Judá. E ali ele deixou o seu servo.

[[v11-19-4]]

^<<v11-19-4,4>>^ Ele mesmo, porém, foi para o deserto, caminhando um dia inteiro. Por fim, sentou-se debaixo de um zimbro. Sentiu vontade de morrer e orou: — Basta, Senhor ! Tira a minha vida, porque eu não sou melhor do que os meus pais.

[[v11-19-5]]

^<<v11-19-5,5>>^ Deitou-se e dormiu debaixo de um zimbro. E eis que um anjo tocou nele e lhe disse: — Levante-se e coma.

[[v11-19-6]]

^<<v11-19-6,6>>^ Elias olhou e viu, perto da sua cabeça, um pão assado sobre pedras em brasa e um jarro de água. Comeu, bebeu e tornou a dormir.

[[v11-19-7]]

^<<v11-19-7,7>>^ O anjo do Senhor  voltou, tocou nele e lhe disse: — Levante-se e coma, porque a viagem será longa.

[[v11-19-8]]

^<<v11-19-8,8>>^ Então Elias se levantou, comeu e bebeu. E, com a força daquela comida, caminhou quarenta dias e quarenta noites até Horebe, o monte de Deus.

[[v11-19-9]]

^<<v11-19-9,9>>^ Ali entrou numa caverna, onde passou a noite. E eis que a palavra do Senhor  veio a ele e lhe disse: — O que você está fazendo aqui, Elias?

[[v11-19-10]]

^<<v11-19-10,10>>^ Ele respondeu: — Tenho sido muito zeloso pelo Senhor , Deus dos Exércitos, porque os filhos de Israel deixaram a tua aliança, derrubaram os teus altares e mataram os teus profetas à espada. Só fiquei eu, e eles estão querendo tirar-me a vida.

[[v11-19-11]]

^<<v11-19-11,11>>^ Então foi-lhe dito: — Saia daí e fique diante do Senhor  no monte. Eis que o Senhor  estava passando. E um grande e forte vento fendia os montes e quebrava as rochas diante do Senhor . Mas o Senhor  não estava no vento. Depois do vento, houve um terremoto. Mas o Senhor  não estava no terremoto.

[[v11-19-12]]

^<<v11-19-12,12>>^ Depois do terremoto, veio um fogo. Mas o Senhor  não estava no fogo. E, depois do fogo, veio o som de um suave sussurro.

[[v11-19-13]]

^<<v11-19-13,13>>^ Quando Elias ouviu isso, cobriu o rosto com o manto e, saindo, pôs-se à entrada da caverna. Eis que veio uma voz e lhe disse: — O que você está fazendo aqui, Elias?

[[v11-19-14]]

^<<v11-19-14,14>>^ Ele respondeu: — Tenho sido muito zeloso pelo Senhor , Deus dos Exércitos, porque os filhos de Israel deixaram a tua aliança, derrubaram os teus altares e mataram os teus profetas à espada. Só fiquei eu, e eles estão querendo tirar-me a vida.

[[v11-19-15]]

^<<v11-19-15,15>>^ Então o Senhor  disse a Elias: — Vá, volte ao seu caminho para o deserto de Damasco. Chegando lá, unja Hazael como rei da Síria.

[[v11-19-16]]

^<<v11-19-16,16>>^ Unja também Jeú, filho de Ninsi, como rei de Israel e Eliseu, filho de Safate, de Abel-Meolá, como profeta em seu lugar.

[[v11-19-17]]

^<<v11-19-17,17>>^ Quem escapar à espada de Hazael, Jeú o matará; quem escapar à espada de Jeú, Eliseu o matará.

[[v11-19-18]]

^<<v11-19-18,18>>^ Também conservei em Israel sete mil, todos os joelhos que não se dobraram a Baal, e toda boca que não o beijou.

[[v11-19-19]]

^<<v11-19-19,19>>^ Elias saiu dali e encontrou Eliseu, filho de Safate, que estava lavrando com doze juntas de bois adiante dele; ele estava com a décima segunda junta. Elias passou por ele e lançou o seu manto sobre ele.

[[v11-19-20]]

^<<v11-19-20,20>>^ Então Eliseu deixou os bois, correu atrás de Elias e disse: — Deixe-me beijar o meu pai e a minha mãe e, então, eu o seguirei. Elias respondeu: — Vá e volte, pois você já sabe o que fiz com você.

[[v11-19-21]]

^<<v11-19-21,21>>^ Eliseu voltou para trás, pegou a junta de bois e os sacrificou. E, com os equipamentos dos bois, cozinhou a carne e a deu ao povo, e eles comeram. Então se levantou, seguiu Elias, e o servia.

'''

xref:011-1-reis/011-1-reis-018.adoc#v11-18-0[&#60; Capítulo Anterior] | <<v11-19-0,Topo>> | xref:011-1-reis/011-1-reis-020.adoc#v11-20-0[Próximo Capítulo &#62;]