include::./index.adoc[]

[[v11-1-0]]
=== 1 Reis, 1
// naa ?, NAA - Nova Almeida Atualizada

[[v11-1-1]]

^<<v11-1-1,1>>^ Quando o rei Davi já estava bem velho, envolviam-no com roupas, mas ele não se aquecia.

[[v11-1-2]]

^<<v11-1-2,2>>^ Então os seus servos lhe disseram: — Que se procure para o rei, nosso senhor, uma jovem donzela, que esteja diante do rei e tenha cuidado dele, e durma nos seus braços, para que o rei, nosso senhor, se aqueça.

[[v11-1-3]]

^<<v11-1-3,3>>^ Então procuraram em todo o território de Israel uma jovem formosa. Acharam Abisague, sunamita, e a levaram ao rei.

[[v11-1-4]]

^<<v11-1-4,4>>^ A jovem era muito bonita. Cuidava do rei e o servia, mas o rei não teve relações com ela.

[[v11-1-5]]

^<<v11-1-5,5>>^ Então Adonias, filho de Hagite, se exaltou e disse: — Eu serei o rei. Providenciou carros de guerra, cavaleiros e cinquenta homens que corressem na sua frente.

[[v11-1-6]]

^<<v11-1-6,6>>^ Seu pai jamais o tinha contrariado, dizendo: "Por que você fez isso ou aquilo?" Adonias tinha boa aparência e era mais jovem do que Absalão.

[[v11-1-7]]

^<<v11-1-7,7>>^ Ele tinha feito um acordo com Joabe, filho de Zeruia, e com Abiatar, o sacerdote, que o seguiam e apoiavam.

[[v11-1-8]]

^<<v11-1-8,8>>^ Porém Zadoque, o sacerdote, Benaia, filho de Joiada, Natã, o profeta, Simei, Reí e os valentes de Davi não apoiavam Adonias.

[[v11-1-9]]

^<<v11-1-9,9>>^ Certo dia Adonias sacrificou ovelhas, bois e bezerros gordos junto à pedra de Zoelete, que está perto de En-Rogel. Convidou todos os seus irmãos, os filhos do rei, e todos os homens de Judá que estavam a serviço do rei,

[[v11-1-10]]

^<<v11-1-10,10>>^ porém não convidou Natã, o profeta, nem Benaia, nem os valentes, nem Salomão, seu irmão.

[[v11-1-11]]

^<<v11-1-11,11>>^ Então Natã disse a Bate-Seba, mãe de Salomão: — Você não ouviu que Adonias, filho de Hagite, se proclamou rei e que nosso senhor, Davi, não sabe de nada?

[[v11-1-12]]

^<<v11-1-12,12>>^ Agora permita que eu lhe dê um conselho, para que você salve a sua vida e a vida do seu filho Salomão.

[[v11-1-13]]

^<<v11-1-13,13>>^ Vá, apresente-se ao rei Davi e diga: "Ó rei, meu senhor, não é verdade que você jurou a esta sua serva, dizendo: ‘O seu filho Salomão reinará depois de mim e ele se assentará no meu trono?’ Por que, então, Adonias se tornou rei?"

[[v11-1-14]]

^<<v11-1-14,14>>^ — Eis que, enquanto você ainda estiver falando com o rei, eu também entrarei depois de você e confirmarei as suas palavras.

[[v11-1-15]]

^<<v11-1-15,15>>^ Assim, Bate-Seba entrou no quarto do rei para falar com ele. O rei já era bem velho, e Abisague, a sunamita, o servia.

[[v11-1-16]]

^<<v11-1-16,16>>^ Bate-Seba inclinou a cabeça e prostrou-se diante do rei, que perguntou: — O que você quer?

[[v11-1-17]]

^<<v11-1-17,17>>^ Ela respondeu: — Meu senhor, você jurou a esta sua serva pelo Senhor , seu Deus, dizendo: "O seu filho Salomão reinará depois de mim e ele se assentará no meu trono."

[[v11-1-18]]

^<<v11-1-18,18>>^ Mas agora Adonias se proclamou rei, e você, ó rei, meu senhor, não sabe disso.

[[v11-1-19]]

^<<v11-1-19,19>>^ Ele sacrificou bois, bezerros gordos e ovelhas em abundância. Convidou todos os filhos do rei, Abiatar, o sacerdote, e Joabe, comandante do exército, mas não convidou o seu servo Salomão.

[[v11-1-20]]

^<<v11-1-20,20>>^ Porém, ó rei, meu senhor, todo o Israel tem os olhos em você, para que o rei diga quem se assentará no trono do rei, meu senhor, depois dele.

[[v11-1-21]]

^<<v11-1-21,21>>^ Do contrário, sucederá que, quando o rei, meu senhor, morrer, eu e o meu filho Salomão seremos tidos por culpados.

[[v11-1-22]]

^<<v11-1-22,22>>^ Enquanto Bate-Seba ainda falava com o rei, eis que o profeta Natã entrou.

[[v11-1-23]]

^<<v11-1-23,23>>^ E anunciaram isso ao rei, dizendo: — O profeta Natã está aí. Ele se apresentou ao rei e prostrou-se com o rosto em terra diante dele.

[[v11-1-24]]

^<<v11-1-24,24>>^ Natã perguntou: — Rei Davi, por acaso o senhor declarou, dizendo: "Adonias reinará depois de mim e é ele quem se assentará no meu trono"?

[[v11-1-25]]

^<<v11-1-25,25>>^ Porque hoje ele foi sacrificar bois, bezerros gordos e ovelhas em abundância. Convidou todos os filhos do rei, os chefes do exército e Abiatar, o sacerdote. E eis que estão comendo e bebendo com ele e gritando: "Viva o rei Adonias!"

[[v11-1-26]]

^<<v11-1-26,26>>^ Porém não convidou a mim, que sou servo do rei, nem Zadoque, o sacerdote, nem Benaia, filho de Joiada, nem Salomão, que é servo do meu senhor.

[[v11-1-27]]

^<<v11-1-27,27>>^ Será que isso teria sido feito por ordem do rei, meu senhor? E o senhor não contou nem a este seu servo quem se assentaria no seu trono, depois do senhor!

[[v11-1-28]]

^<<v11-1-28,28>>^ O rei Davi respondeu: — Chamem Bate-Seba. Ela se apresentou ao rei e se pôs diante dele.

[[v11-1-29]]

^<<v11-1-29,29>>^ Então o rei jurou, dizendo: — Tão certo como vive o Senhor , que remiu a minha alma de toda a angústia,

[[v11-1-30]]

^<<v11-1-30,30>>^ farei no dia de hoje como jurei a você pelo Senhor , Deus de Israel, dizendo: "O seu filho Salomão reinará depois de mim e se assentará no meu trono, em meu lugar."

[[v11-1-31]]

^<<v11-1-31,31>>^ Então Bate-Seba se inclinou, prostrou-se com o rosto em terra diante do rei e disse: — Que o rei Davi, meu senhor, viva para sempre!

[[v11-1-32]]

^<<v11-1-32,32>>^ O rei Davi disse: — Chamem Zadoque, o sacerdote, Natã, o profeta, e Benaia, filho de Joiada. E eles se apresentaram ao rei.

[[v11-1-33]]

^<<v11-1-33,33>>^ Então o rei disse: — Levem com vocês os meus servos, façam o meu filho Salomão montar na minha mula e levem-no a Giom.

[[v11-1-34]]

^<<v11-1-34,34>>^ Ali Zadoque, o sacerdote, com Natã, o profeta, o ungirão rei sobre Israel. Então toquem a trombeta e digam: "Viva o rei Salomão!"

[[v11-1-35]]

^<<v11-1-35,35>>^ Depois venham subindo com ele, e ele virá e se assentará no meu trono, pois é ele quem reinará em meu lugar. Porque ordenei que ele seja chefe sobre Israel e sobre Judá.

[[v11-1-36]]

^<<v11-1-36,36>>^ Então Benaia, filho de Joiada, respondeu ao rei: — Amém! Que o Senhor , Deus do rei, meu senhor, confirme isso!

[[v11-1-37]]

^<<v11-1-37,37>>^ Como o Senhor  Deus tem estado com o rei, meu senhor, assim esteja com Salomão e faça com que o trono dele seja maior do que o trono do rei Davi, meu senhor.

[[v11-1-38]]

^<<v11-1-38,38>>^ Então Zadoque, o sacerdote, Natã, o profeta, Benaia, filho de Joiada, e a guarda real fizeram Salomão montar na mula que era do rei Davi e o levaram a Giom.

[[v11-1-39]]

^<<v11-1-39,39>>^ Zadoque, o sacerdote, levou o chifre do azeite que estava no tabernáculo e ungiu Salomão. Tocaram a trombeta, e todo o povo gritou: — Viva o rei Salomão!

[[v11-1-40]]

^<<v11-1-40,40>>^ Todo o povo vinha subindo atrás de Salomão, tocando flautas e gritando de alegria. O barulho era tanto, que parecia que a terra estava se fendendo.

[[v11-1-41]]

^<<v11-1-41,41>>^ Adonias e todos os convidados que estavam com ele ouviram isso, quando acabavam de comer. Também Joabe ouviu o som da trombeta e perguntou: — Que significa esse alvoroço na cidade?

[[v11-1-42]]

^<<v11-1-42,42>>^ Enquanto ele falava, eis que chegou Jônatas, filho de Abiatar, o sacerdote. Adonias disse a Jônatas: — Entre aqui, porque você é um homem valente e deve estar trazendo boas notícias.

[[v11-1-43]]

^<<v11-1-43,43>>^ Mas Jônatas respondeu a Adonias: — Pelo contrário. Nosso senhor, o rei Davi, proclamou Salomão como rei.

[[v11-1-44]]

^<<v11-1-44,44>>^ E Davi enviou com ele Zadoque, o sacerdote, Natã, o profeta, Benaia, filho de Joiada, e os da guarda real; e eles fizeram Salomão montar na mula que era do rei.

[[v11-1-45]]

^<<v11-1-45,45>>^ Zadoque, o sacerdote, e Natã, o profeta, o ungiram rei em Giom. Eles voltaram de lá, cheios de alegria, e a cidade se alvoroçou. É esse o barulho que você ouviu.

[[v11-1-46]]

^<<v11-1-46,46>>^ Também Salomão já está sentado no trono do reino.

[[v11-1-47]]

^<<v11-1-47,47>>^ Além disso, os oficiais do rei foram cumprimentar Davi e disseram: "Que o seu Deus faça com que o nome de Salomão seja mais célebre do que o seu nome, e faça com que o trono dele seja maior do que o seu trono." E o rei se inclinou sobre o leito.

[[v11-1-48]]

^<<v11-1-48,48>>^ O rei também disse o seguinte: "Bendito seja o Senhor , Deus de Israel, que deu hoje quem se assente no meu trono, e permitiu que eu o visse com os meus próprios olhos."

[[v11-1-49]]

^<<v11-1-49,49>>^ Então todos os convidados que estavam com Adonias começaram a tremer, se levantaram e foram embora, cada um pelo seu caminho.

[[v11-1-50]]

^<<v11-1-50,50>>^ Porém Adonias, temendo Salomão, levantou-se, foi e pegou nas pontas do altar.

[[v11-1-51]]

^<<v11-1-51,51>>^ Então alguém foi dizer a Salomão: — Eis que Adonias tem medo do rei Salomão, porque pega nas pontas do altar, dizendo: "Que o rei Salomão me jure hoje que não matará este seu servo à espada."

[[v11-1-52]]

^<<v11-1-52,52>>^ Salomão respondeu: — Se for homem de bem, nem um de seus cabelos cairá no chão. Mas se fizer alguma maldade, morrerá.

[[v11-1-53]]

^<<v11-1-53,53>>^ Então o rei Salomão enviou mensageiros, e o fizeram descer do altar. Adonias veio e se prostrou diante do rei Salomão, que lhe disse: — Vá para a sua casa.

'''

xref:010-2-samuel/010-2-samuel-024.adoc#v10-24-0[&#60; Capítulo Anterior] | <<v11-1-0,Topo>> | xref:011-1-reis/011-1-reis-002.adoc#v11-2-0[Próximo Capítulo &#62;]