include::./index.adoc[]

[[v11-11-0]]
=== 1 Reis, 11
// naa ?, NAA - Nova Almeida Atualizada

[[v11-11-1]]

^<<v11-11-1,1>>^ Além da filha de Faraó, Salomão amou muitas mulheres estrangeiras: moabitas, amonitas, edomitas, sidônias e heteias,

[[v11-11-2]]

^<<v11-11-2,2>>^ mulheres das nações de que o Senhor  tinha dito aos filhos de Israel: "Não casem com elas, nem casem elas com vocês, pois perverteriam o coração de vocês, para seguirem os seus deuses." A estas Salomão se apegou pelo amor.

[[v11-11-3]]

^<<v11-11-3,3>>^ Tinha setecentas mulheres que eram princesas e trezentas concubinas; e suas mulheres lhe perverteram o coração.

[[v11-11-4]]

^<<v11-11-4,4>>^ Sendo já velho, suas mulheres lhe perverteram o coração para seguir outros deuses, e o coração dele não era fiel ao Senhor , seu Deus, como havia sido fiel o coração de Davi, seu pai.

[[v11-11-5]]

^<<v11-11-5,5>>^ Salomão seguiu Astarote, deusa dos sidônios, e Milcom, abominação dos amonitas.

[[v11-11-6]]

^<<v11-11-6,6>>^ Assim, Salomão fez o que era mau aos olhos do Senhor  e não perseverou em seguir o Senhor , como Davi, seu pai, havia feito.

[[v11-11-7]]

^<<v11-11-7,7>>^ Nesse tempo, sobre o monte que fica diante de Jerusalém, Salomão construiu um santuário a Quemos, abominação de Moabe, e a Moloque, abominação dos filhos de Amom.

[[v11-11-8]]

^<<v11-11-8,8>>^ Assim fez para todas as suas mulheres estrangeiras, as quais queimavam incenso e ofereciam sacrifícios aos seus deuses.

[[v11-11-9]]

^<<v11-11-9,9>>^ O Senhor  se indignou contra Salomão, por ter desviado o seu coração do Senhor , Deus de Israel, que lhe havia aparecido duas vezes

[[v11-11-10]]

^<<v11-11-10,10>>^ e ordenado que não seguisse outros deuses. Ele, porém, não guardou o que o Senhor  lhe havia ordenado.

[[v11-11-11]]

^<<v11-11-11,11>>^ Por isso o Senhor  disse a Salomão: — Já que você procedeu assim e não guardou a minha aliança, nem os meus estatutos que lhe ordenei, vou tirar o reino de você e dá-lo a um dos seus servos.

[[v11-11-12]]

^<<v11-11-12,12>>^ No entanto, por amor a Davi, seu pai, não farei isso enquanto você estiver vivo, mas durante o reinado do seu filho.

[[v11-11-13]]

^<<v11-11-13,13>>^ Todavia, não tirarei o reino todo; darei uma tribo a seu filho, por amor a Davi, meu servo, e por amor a Jerusalém, que escolhi.

[[v11-11-14]]

^<<v11-11-14,14>>^ O Senhor  levantou um adversário contra Salomão, a saber, Hadade, o edomita, que era da linhagem real de Edom.

[[v11-11-15]]

^<<v11-11-15,15>>^ Porque, quando Davi esteve em Edom, Joabe, o comandante do exército, que tinha ido sepultar os mortos, matou todos os homens em Edom.

[[v11-11-16]]

^<<v11-11-16,16>>^ Porque Joabe ficou ali seis meses com todo o Israel, até que eliminou todos os homens em Edom.

[[v11-11-17]]

^<<v11-11-17,17>>^ Porém Hadade fugiu para o Egito na companhia de alguns homens edomitas, dos servos de seu pai. Na ocasião, Hadade era ainda muito jovem.

[[v11-11-18]]

^<<v11-11-18,18>>^ Partiram de Midiã e foram até Parã, de onde levaram consigo alguns homens e chegaram ao Egito, a Faraó, rei do Egito, que deu a Hadade uma casa, e lhe prometeu sustento, e lhe deu terras.

[[v11-11-19]]

^<<v11-11-19,19>>^ Hadade encontrou favor aos olhos de Faraó, tanto que este lhe deu por mulher a irmã de sua própria mulher,

[[v11-11-20]]

^<<v11-11-20,20>>^ a irmã de Tafnes, a rainha. A irmã de Tafnes deu-lhe à luz seu filho Genubate, que foi criado por Tafnes na casa de Faraó, onde Genubate ficou entre os filhos de Faraó.

[[v11-11-21]]

^<<v11-11-21,21>>^ Quando Hadade soube no Egito que Davi tinha morrido e que Joabe, comandante do exército, estava morto, disse a Faraó: — Deixe-me voltar para a minha terra.

[[v11-11-22]]

^<<v11-11-22,22>>^ Então Faraó lhe perguntou: — Mas o que lhe falta comigo, para que você queira voltar para a sua terra? Hadade respondeu: — Não me falta nada; mas deixe-me ir.

[[v11-11-23]]

^<<v11-11-23,23>>^ Deus levantou mais um adversário contra Salomão, a saber, Rezom, filho de Eliada, que havia fugido de seu senhor Hadadezer, rei de Zobá.

[[v11-11-24]]

^<<v11-11-24,24>>^ Ele ajuntou homens e se fez chefe de um bando. Depois do morticínio feito por Davi, eles se foram para Damasco, onde habitaram e fizeram de Rezom o seu rei.

[[v11-11-25]]

^<<v11-11-25,25>>^ Este foi adversário de Israel durante toda a vida de Salomão, e lhe fez mal, como Hadade havia feito. Rezom detestava Israel e reinava sobre a Síria.

[[v11-11-26]]

^<<v11-11-26,26>>^ Jeroboão, filho de Nebate, efraimita de Zereda, servo de Salomão, e cuja mãe era uma viúva chamada Zerua, revoltou-se contra o rei.

[[v11-11-27]]

^<<v11-11-27,27>>^ Esta foi a causa por que levantou a sua mão contra o rei: Salomão estava edificando Milo e reparando as brechas da cidade de seu pai Davi.

[[v11-11-28]]

^<<v11-11-28,28>>^ Jeroboão era um homem valente e capaz. Quando Salomão viu que ele era um jovem que fazia bem o seu trabalho, ele o encarregou de todos os trabalhadores forçados da casa de José.

[[v11-11-29]]

^<<v11-11-29,29>>^ Aconteceu que, nesse tempo, quando Jeroboão estava saindo de Jerusalém, o profeta Aías, de Siló, o encontrou no caminho. O profeta estava usando uma capa nova, e os dois estavam sozinhos no campo.

[[v11-11-30]]

^<<v11-11-30,30>>^ Aías pegou a capa nova que estava usando, rasgou-a em doze pedaços

[[v11-11-31]]

^<<v11-11-31,31>>^ e disse a Jeroboão: — Pegue dez pedaços, porque assim diz o Senhor , Deus de Israel: "Eis que rasgarei o reino das mãos de Salomão, e a você darei dez tribos.

[[v11-11-32]]

^<<v11-11-32,32>>^ Porém ele terá uma tribo, por amor a Davi, meu servo, e por amor a Jerusalém, a cidade que escolhi de todas as tribos de Israel.

[[v11-11-33]]

^<<v11-11-33,33>>^ Porque Salomão me abandonou e se inclinou diante de Astarote, deusa dos sidônios, diante de Quemos, deus de Moabe, e diante de Milcom, deus dos filhos de Amom. Ele não andou nos meus caminhos para fazer o que é reto aos meus olhos, a saber, para guardar os meus estatutos e os meus juízos, como fez Davi, seu pai.

[[v11-11-34]]

^<<v11-11-34,34>>^ Porém não vou tirar de Salomão o reino todo; pelo contrário, farei com que ele governe durante todos os dias da sua vida, por amor a Davi, meu servo, que escolhi e que guardou os meus mandamentos e os meus estatutos.

[[v11-11-35]]

^<<v11-11-35,35>>^ Mas da mão do filho de Salomão tomarei o reino, a saber, as dez tribos, e as darei a você.

[[v11-11-36]]

^<<v11-11-36,36>>^ E ao filho dele darei uma tribo, para que Davi, meu servo, tenha sempre uma lâmpada diante de mim em Jerusalém, a cidade que escolhi para pôr ali o meu nome.

[[v11-11-37]]

^<<v11-11-37,37>>^ Quanto a você, eu o tomarei e você reinará sobre tudo o que desejar a sua alma; e você será rei sobre Israel.

[[v11-11-38]]

^<<v11-11-38,38>>^ Se você ouvir tudo o que eu lhe ordenar, e andar nos meus caminhos, e fizer o que é reto aos meus olhos, guardando os meus estatutos e os meus mandamentos, como fez Davi, meu servo, eu estarei com você, e lhe edificarei uma casa estável, como edifiquei para Davi, e darei Israel a você.

[[v11-11-39]]

^<<v11-11-39,39>>^ Por causa disso, afligirei a descendência de Davi, mas não para sempre."

[[v11-11-40]]

^<<v11-11-40,40>>^ Salomão tentou matar Jeroboão, mas este se levantou e fugiu para o Egito, para junto de Sisaque, rei do Egito; e ali permaneceu até a morte de Salomão.

[[v11-11-41]]

^<<v11-11-41,41>>^ Quanto aos demais atos de Salomão, a tudo o que fez e à sua sabedoria, não está tudo escrito no Livro da História de Salomão?

[[v11-11-42]]

^<<v11-11-42,42>>^ O tempo que Salomão reinou sobre todo o Israel, em Jerusalém, foi de quarenta anos.

[[v11-11-43]]

^<<v11-11-43,43>>^ Salomão morreu e foi sepultado na Cidade de Davi, seu pai, e Roboão, seu filho, reinou em seu lugar.

'''

xref:011-1-reis/011-1-reis-010.adoc#v11-10-0[&#60; Capítulo Anterior] | <<v11-11-0,Topo>> | xref:011-1-reis/011-1-reis-012.adoc#v11-12-0[Próximo Capítulo &#62;]