include::./index.adoc[]

[[v11-21-0]]
=== 1 Reis, 21
// naa ?, NAA - Nova Almeida Atualizada

[[v11-21-1]]

^<<v11-21-1,1>>^ Depois disto, aconteceu o seguinte: Nabote, o jezreelita, possuía uma vinha ao lado do palácio que Acabe, rei de Samaria, tinha em Jezreel.

[[v11-21-2]]

^<<v11-21-2,2>>^ Acabe disse a Nabote: — Dê-me a sua vinha, para que me sirva de horta, pois está perto, ao lado do meu palácio. Em troca eu lhe darei outra, melhor. Ou, se for do seu agrado, darei em dinheiro o que ela vale.

[[v11-21-3]]

^<<v11-21-3,3>>^ Porém Nabote disse a Acabe: — Que o Senhor  Deus me livre de lhe dar a herança de meus pais.

[[v11-21-4]]

^<<v11-21-4,4>>^ Então Acabe voltou para casa aborrecido e indignado com o que Nabote, o jezreelita, lhe havia falado, quando disse: "Não lhe darei a herança de meus pais." E se deitou na cama, voltou o rosto para a parede e não quis comer.

[[v11-21-5]]

^<<v11-21-5,5>>^ Porém Jezabel, a esposa, foi falar com ele e perguntou: — Que é isso que você tem? Por que está assim aborrecido e não quer comer nada?

[[v11-21-6]]

^<<v11-21-6,6>>^ Acabe respondeu: — É porque falei com Nabote, o jezreelita, e lhe disse: "Dê-me a sua vinha por dinheiro; ou, se preferir, lhe darei outra em troca." Porém ele disse: "Não lhe darei a minha vinha."

[[v11-21-7]]

^<<v11-21-7,7>>^ Então Jezabel, sua esposa, lhe disse: — Você está governando Israel ou não? Levante-se, venha comer e alegre o seu coração; eu lhe darei a vinha de Nabote, o jezreelita.

[[v11-21-8]]

^<<v11-21-8,8>>^ Então Jezabel escreveu cartas em nome de Acabe, selou-as com o sinete dele e as enviou aos anciãos e aos nobres que moravam com Nabote na cidade dele.

[[v11-21-9]]

^<<v11-21-9,9>>^ E nas cartas ela escreveu o seguinte: "Anunciem um dia de jejum e tragam Nabote para a frente do povo.

[[v11-21-10]]

^<<v11-21-10,10>>^ Ponham sentados na frente dele dois homens malignos, que testemunhem contra ele, dizendo: ‘Você blasfemou contra Deus e contra o rei.’ Depois, levem-no para fora e o apedrejem, para que morra."

[[v11-21-11]]

^<<v11-21-11,11>>^ Os homens daquela cidade, os anciãos e os nobres que moravam com Nabote fizeram o que Jezabel lhes ordenou, segundo estava escrito nas cartas que lhes havia mandado.

[[v11-21-12]]

^<<v11-21-12,12>>^ Anunciaram um dia de jejum e deram a Nabote um lugar de destaque na frente do povo.

[[v11-21-13]]

^<<v11-21-13,13>>^ Então vieram dois homens malignos, sentaram-se na frente dele e testemunharam contra ele, contra Nabote, diante do povo, dizendo: — Nabote blasfemou contra Deus e contra o rei. E o levaram para fora da cidade e o apedrejaram, e ele morreu.

[[v11-21-14]]

^<<v11-21-14,14>>^ Então mandaram dizer a Jezabel: — Nabote foi apedrejado e morreu.

[[v11-21-15]]

^<<v11-21-15,15>>^ Quando Jezabel ouviu que Nabote tinha sido apedrejado e estava morto, disse a Acabe: — Levante-se e tome posse da vinha que Nabote, o jezreelita, não quis dar a você por dinheiro. Porque Nabote não está mais vivo; morreu.

[[v11-21-16]]

^<<v11-21-16,16>>^ Quando Acabe ouviu que Nabote estava morto, levantou-se para ir até a vinha de Nabote, o jezreelita, para tomar posse dela.

[[v11-21-17]]

^<<v11-21-17,17>>^ Então a palavra do Senhor  veio a Elias, o tesbita, dizendo:

[[v11-21-18]]

^<<v11-21-18,18>>^ — Levante-se, vá encontrar-se com Acabe, rei de Israel, que mora em Samaria. Eis que ele está na vinha de Nabote, aonde foi para tomar posse dela.

[[v11-21-19]]

^<<v11-21-19,19>>^ Fale com ele, dizendo: Assim diz o Senhor : "Você matou e, ainda por cima, tomou a herança?" Fale também o seguinte: Assim diz o Senhor : "No mesmo lugar onde os cães lamberam o sangue de Nabote, cães lamberão o seu sangue — sim, o seu sangue."

[[v11-21-20]]

^<<v11-21-20,20>>^ Acabe perguntou a Elias: — Então, meu inimigo, você já me achou? Elias respondeu: — Achei, sim, porque você já se vendeu para fazer o que é mau aos olhos do Senhor .

[[v11-21-21]]

^<<v11-21-21,21>>^ Eis que trarei o mal sobre você, arrancarei a sua posteridade e exterminarei de Acabe todos do sexo masculino, quer escravo quer livre, em Israel.

[[v11-21-22]]

^<<v11-21-22,22>>^ Farei com a sua casa o mesmo que fiz com a casa de Jeroboão, filho de Nebate, e com a casa de Baasa, filho de Aías, por causa da provocação com que você me irritou e levou Israel a pecar.

[[v11-21-23]]

^<<v11-21-23,23>>^ — Também de Jezabel o Senhor  falou: "Os cães devorarão Jezabel dentro das muralhas de Jezreel.

[[v11-21-24]]

^<<v11-21-24,24>>^ Se alguém da casa de Acabe morrer na cidade, os cães o comerão; e se alguém morrer no campo, as aves do céu o comerão."

[[v11-21-25]]

^<<v11-21-25,25>>^ Nunca houve ninguém igual a Acabe, que se vendeu para fazer o que era mau aos olhos do Senhor , porque Jezabel, sua esposa, o instigava.

[[v11-21-26]]

^<<v11-21-26,26>>^ Ele fez grandes abominações, seguindo os ídolos, conforme tudo o que fizeram os amorreus, que o Senhor  expulsou de diante dos filhos de Israel.

[[v11-21-27]]

^<<v11-21-27,27>>^ Quando Acabe ouviu estas palavras, rasgou as suas roupas, cobriu-se de pano de saco e jejuou; dormia vestido de pano de saco e andava cabisbaixo.

[[v11-21-28]]

^<<v11-21-28,28>>^ Então a palavra do Senhor  veio a Elias, o tesbita, dizendo:

[[v11-21-29]]

^<<v11-21-29,29>>^ — Você viu como Acabe se humilhou diante de mim? Portanto, visto que ele se humilha diante de mim, não trarei este mal nos seus dias, mas nos dias de seu filho o trarei sobre a sua casa.

'''

xref:011-1-reis/011-1-reis-020.adoc#v11-20-0[&#60; Capítulo Anterior] | <<v11-21-0,Topo>> | xref:011-1-reis/011-1-reis-022.adoc#v11-22-0[Próximo Capítulo &#62;]