include::./index.adoc[]

[[v11-8-0]]
=== 1 Reis, 8
// naa ?, NAA - Nova Almeida Atualizada

[[v11-8-1]]

^<<v11-8-1,1>>^ Então Salomão congregou os anciãos de Israel, todos os chefes das tribos, os príncipes das famílias dos israelitas, diante de si em Jerusalém, para levarem a arca da aliança do Senhor  da Cidade de Davi, que é Sião, para o templo.

[[v11-8-2]]

^<<v11-8-2,2>>^ Todos os homens de Israel se congregaram junto ao rei Salomão na ocasião da festa, no mês de etanim, que é o sétimo.

[[v11-8-3]]

^<<v11-8-3,3>>^ Quando todos os anciãos de Israel chegaram, os sacerdotes pegaram a arca do Senhor

[[v11-8-4]]

^<<v11-8-4,4>>^ e a levaram para cima, com a tenda do encontro e com os utensílios sagrados que nela havia; os sacerdotes e levitas é que levaram tudo isso para o templo.

[[v11-8-5]]

^<<v11-8-5,5>>^ O rei Salomão e toda a congregação de Israel, que se havia reunido diante dele, estavam todos diante da arca, sacrificando ovelhas e bois, que, de tão numerosos, não se podiam contar.

[[v11-8-6]]

^<<v11-8-6,6>>^ Os sacerdotes puseram a arca da aliança do Senhor  no seu lugar, no santuário mais interior do templo, que é o Santo dos Santos, debaixo das asas dos querubins.

[[v11-8-7]]

^<<v11-8-7,7>>^ Pois os querubins estendiam as asas sobre o lugar da arca e, do alto, cobriam a arca e os seus cabos.

[[v11-8-8]]

^<<v11-8-8,8>>^ Os cabos sobressaíam tanto, que suas pontas eram vistas do Santo Lugar, diante do Santo dos Santos; porém de fora não podiam ser vistos. E ali estão até o dia de hoje.

[[v11-8-9]]

^<<v11-8-9,9>>^ Nada havia na arca a não ser as duas tábuas de pedra que Moisés havia colocado ali em Horebe, quando o Senhor  fez aliança com os filhos de Israel, ao saírem da terra do Egito.

[[v11-8-10]]

^<<v11-8-10,10>>^ Quando os sacerdotes saíram do santuário, uma nuvem encheu a Casa do Senhor ,

[[v11-8-11]]

^<<v11-8-11,11>>^ de maneira que os sacerdotes não puderam permanecer ali para ministrar, por causa da nuvem, porque a glória do Senhor  encheu a Casa do Senhor .

[[v11-8-12]]

^<<v11-8-12,12>>^ Então Salomão disse: — O Senhor  declarou que habitaria em trevas espessas.

[[v11-8-13]]

^<<v11-8-13,13>>^ Na verdade, edifiquei uma casa para tua morada, lugar para a tua eterna habitação.

[[v11-8-14]]

^<<v11-8-14,14>>^ Depois o rei voltou o rosto e abençoou toda a congregação de Israel, que se mantinha toda em pé.

[[v11-8-15]]

^<<v11-8-15,15>>^ Salomão disse: — Bendito seja o Senhor , o Deus de Israel, que falou pessoalmente com Davi, meu pai, e pelo seu poder cumpriu o que prometeu, dizendo:

[[v11-8-16]]

^<<v11-8-16,16>>^ "Desde o dia em que tirei o meu povo de Israel do Egito, não escolhi cidade alguma de todas as tribos de Israel para edificar um templo a fim de ali estabelecer o meu nome. Porém escolhi Davi para governar o meu povo de Israel."

[[v11-8-17]]

^<<v11-8-17,17>>^ — Também Davi, meu pai, havia proposto em seu coração edificar um templo ao nome do Senhor , o Deus de Israel.

[[v11-8-18]]

^<<v11-8-18,18>>^ Porém o Senhor  disse a Davi, meu pai: "Você fez bem quando resolveu em seu coração edificar um templo ao meu nome.

[[v11-8-19]]

^<<v11-8-19,19>>^ Todavia, não será você quem edificará esse templo; o seu filho, que descenderá de você, ele o edificará ao meu nome."

[[v11-8-20]]

^<<v11-8-20,20>>^ Assim, o Senhor  cumpriu a palavra que tinha dito, pois me levantei em lugar de Davi, meu pai, e me assentei no trono de Israel, como o Senhor  havia prometido, e edifiquei o templo ao nome do Senhor , o Deus de Israel.

[[v11-8-21]]

^<<v11-8-21,21>>^ E nele preparei um lugar para a arca, em que estão as tábuas da aliança que o Senhor  fez com os nossos pais, quando os tirou da terra do Egito.

[[v11-8-22]]

^<<v11-8-22,22>>^ Salomão se pôs diante do altar do Senhor , na presença de toda a congregação de Israel, estendeu as mãos para os céus

[[v11-8-23]]

^<<v11-8-23,23>>^ e disse: — Ó Senhor , Deus de Israel, não há Deus como tu, em cima nos céus nem embaixo na terra! Tu guardas a aliança e a misericórdia aos teus servos que de todo o coração andam diante de ti.

[[v11-8-24]]

^<<v11-8-24,24>>^ Cumpriste para com o teu servo Davi, meu pai, o que lhe prometeste; pessoalmente o disseste e pelo teu poder o cumpriste, como hoje se vê.

[[v11-8-25]]

^<<v11-8-25,25>>^ Agora, pois, ó Senhor , Deus de Israel, cumpre a outra promessa que fizeste a teu servo Davi, meu pai, quando declaraste, dizendo: "Nunca lhe faltará sucessor diante de mim, que se assente no trono de Israel, contanto que os seus filhos guardem o seu caminho, para andarem diante de mim como você andou."

[[v11-8-26]]

^<<v11-8-26,26>>^ Agora também, ó Deus de Israel, que se cumpra a palavra que disseste a teu servo Davi, meu pai.

[[v11-8-27]]

^<<v11-8-27,27>>^ — Mas será que, de fato, Deus poderia habitar na terra? Eis que os céus e até o céu dos céus não te podem conter, muito menos este templo que eu edifiquei.

[[v11-8-28]]

^<<v11-8-28,28>>^ Atenta, pois, para a oração de teu servo e para a sua súplica, ó Senhor , meu Deus, ouvindo o clamor e a oração que faz hoje o teu servo diante de ti.

[[v11-8-29]]

^<<v11-8-29,29>>^ Que os teus olhos estejam abertos noite e dia sobre este templo, sobre este lugar do qual disseste: "O meu nome estará ali", para ouvires a oração que o teu servo fizer neste lugar.

[[v11-8-30]]

^<<v11-8-30,30>>^ Ouve, pois, a súplica do teu servo e do teu povo de Israel, quando orarem neste lugar. Ouve no céu, lugar da tua habitação; ouve e perdoa.

[[v11-8-31]]

^<<v11-8-31,31>>^ — Se alguém pecar contra o seu próximo, e lhe for exigido que jure, e ele vier jurar diante do teu altar, neste templo,

[[v11-8-32]]

^<<v11-8-32,32>>^ ouve tu nos céus, age e julga os teus servos, condenando o ímpio, fazendo com que pague por seus atos, e justificando o justo, para lhe retribuíres segundo a sua justiça.

[[v11-8-33]]

^<<v11-8-33,33>>^ — Quando o teu povo de Israel, por ter pecado contra ti, for derrotado por um inimigo, e se converter a ti, confessar o teu nome, orar e suplicar a ti, neste templo,

[[v11-8-34]]

^<<v11-8-34,34>>^ ouve tu nos céus, perdoa o pecado do teu povo de Israel e faze-o voltar à terra que deste aos seus pais.

[[v11-8-35]]

^<<v11-8-35,35>>^ — Quando o céu se fechar, e não houver chuva, por ter o povo pecado contra ti, e ele orar neste lugar, confessar o teu nome e se converter dos seus pecados, depois de o haveres castigado,

[[v11-8-36]]

^<<v11-8-36,36>>^ ouve tu nos céus, perdoa o pecado de teus servos e do teu povo de Israel, ensinando-lhes o bom caminho em que devem andar, e envia chuva sobre esta tua terra, que deste em herança ao teu povo.

[[v11-8-37]]

^<<v11-8-37,37>>^ — Quando houver fome na terra ou peste, quando houver crestamento ou ferrugem, gafanhotos e larvas, quando inimigos cercarem as cidades do país ou houver alguma praga ou doença,

[[v11-8-38]]

^<<v11-8-38,38>>^ toda oração e súplica que qualquer homem ou todo o teu povo de Israel fizer, conhecendo cada um a ferida do seu coração e estendendo as mãos na direção deste templo,

[[v11-8-39]]

^<<v11-8-39,39>>^ ouve tu nos céus, lugar da tua habitação, perdoa, age e dá a cada um segundo todos os seus caminhos, visto que lhe conheces o coração, porque tu, só tu, és conhecedor do coração de todos os filhos dos homens;

[[v11-8-40]]

^<<v11-8-40,40>>^ para que te temam todos os dias que viverem na terra que deste aos nossos pais.

[[v11-8-41]]

^<<v11-8-41,41>>^ — Também ao estrangeiro, que não for do teu povo de Israel, porém vier de uma terra distante, por amor do teu nome

[[v11-8-42]]

^<<v11-8-42,42>>^ — porque ouvirão do teu grande nome, e da tua mão poderosa, e do teu braço estendido —, e orar, voltado para este templo,

[[v11-8-43]]

^<<v11-8-43,43>>^ ouve tu nos céus, lugar da tua habitação, e faze tudo o que o estrangeiro te pedir, a fim de que todos os povos da terra conheçam o teu nome, para te temerem como o teu povo de Israel e para saberem que este templo, que eu edifiquei, é chamado pelo teu nome.

[[v11-8-44]]

^<<v11-8-44,44>>^ — Quando o teu povo sair à guerra contra o seu inimigo, pelo caminho por onde os enviares, e orarem ao Senhor , voltados para esta cidade, que tu escolheste, e para este templo que edifiquei ao teu nome,

[[v11-8-45]]

^<<v11-8-45,45>>^ ouve tu nos céus a sua oração e a sua súplica e faze-lhes justiça.

[[v11-8-46]]

^<<v11-8-46,46>>^ — Quando pecarem contra ti — pois não há ninguém que não peque —, e tu te indignares contra eles e os entregares às mãos do inimigo, a fim de que os leve cativos à terra inimiga, longe ou perto daqui;

[[v11-8-47]]

^<<v11-8-47,47>>^ e se, na terra aonde forem levados cativos, caírem em si e se converterem, e, na terra do seu cativeiro, te suplicarem, dizendo: "Pecamos, procedemos mal e cometemos iniquidade";

[[v11-8-48]]

^<<v11-8-48,48>>^ e se eles se converterem a ti de todo o seu coração e de toda a sua alma, na terra de seus inimigos que os levarem cativos, e orarem a ti, voltados para a sua terra, que deste aos seus pais, para esta cidade que escolheste e para o templo que edifiquei ao teu nome,

[[v11-8-49]]

^<<v11-8-49,49>>^ ouve tu nos céus, lugar da tua habitação, a sua prece e a sua súplica e faze-lhes justiça;

[[v11-8-50]]

^<<v11-8-50,50>>^ perdoa ao teu povo, que houver pecado contra ti, todas as suas transgressões que houverem cometido contra ti; e move tu à compaixão os que os levaram cativos, para que se compadeçam deles.

[[v11-8-51]]

^<<v11-8-51,51>>^ Porque é o teu povo e a tua herança, que tiraste da terra do Egito, do meio da fornalha de ferro;

[[v11-8-52]]

^<<v11-8-52,52>>^ para que os teus olhos estejam abertos à súplica do teu servo e à súplica do teu povo de Israel, a fim de os ouvires em tudo o que clamarem a ti.

[[v11-8-53]]

^<<v11-8-53,53>>^ Pois tu, ó Senhor  Deus, os separaste dentre todos os povos da terra para serem a tua herança, como falaste por meio do teu servo Moisés, quando tiraste do Egito os nossos pais.

[[v11-8-54]]

^<<v11-8-54,54>>^ Quando Salomão acabou de fazer ao Senhor  toda esta oração e súplica, ele se levantou de diante do altar do Senhor , onde tinha se ajoelhado com as mãos estendidas para os céus.

[[v11-8-55]]

^<<v11-8-55,55>>^ Ele se pôs em pé e abençoou toda a congregação de Israel em alta voz, dizendo:

[[v11-8-56]]

^<<v11-8-56,56>>^ — Bendito seja o Senhor , que deu repouso ao seu povo de Israel, segundo tudo o que havia prometido! Nem uma só palavra falhou de todas as boas promessas que fez por meio de Moisés, seu servo.

[[v11-8-57]]

^<<v11-8-57,57>>^ Que o Senhor , nosso Deus, esteja conosco, assim como esteve com os nossos pais. Que ele não nos deixe nem nos abandone!

[[v11-8-58]]

^<<v11-8-58,58>>^ Que ele faça com que o nosso coração se incline para ele, a fim de andarmos em todos os seus caminhos e guardarmos os seus mandamentos, e os seus estatutos, e os seus juízos, que ordenou aos nossos pais.

[[v11-8-59]]

^<<v11-8-59,59>>^ Que estas minhas palavras, com que supliquei diante do Senhor , estejam presentes, diante do Senhor , nosso Deus, de dia e de noite, para que ele faça justiça ao seu servo e ao seu povo de Israel, segundo cada dia o exigir,

[[v11-8-60]]

^<<v11-8-60,60>>^ para que todos os povos da terra saibam que o Senhor  é Deus e que não há outro.

[[v11-8-61]]

^<<v11-8-61,61>>^ Que o coração de vocês seja fiel para com o Senhor , nosso Deus, para andarem nos seus estatutos e guardarem os seus mandamentos, como vocês estão fazendo hoje.

[[v11-8-62]]

^<<v11-8-62,62>>^ Então o rei e todo o Israel com ele ofereceram sacrifícios ao Senhor .

[[v11-8-63]]

^<<v11-8-63,63>>^ Salomão ofereceu em sacrifício pacífico ao Senhor  vinte e dois mil bois e cento e vinte mil ovelhas. Assim, o rei e todos os filhos de Israel consagraram a Casa do Senhor .

[[v11-8-64]]

^<<v11-8-64,64>>^ No mesmo dia, o rei consagrou o meio do átrio que estava diante da Casa do Senhor , pois ali ofereceu os holocaustos e as ofertas com a gordura dos sacrifícios pacíficos. Ele fez isso porque o altar de bronze que estava diante do Senhor  era muito pequeno para nele caberem os holocaustos, as ofertas de cereais e a gordura dos sacrifícios pacíficos.

[[v11-8-65]]

^<<v11-8-65,65>>^ Nesse tempo, Salomão celebrou a festa, e todo o Israel com ele, uma grande congregação, desde a entrada de Hamate até o rio do Egito, diante do Senhor , nosso Deus. Celebraram durante sete dias além dos primeiros sete, a saber, catorze dias.

[[v11-8-66]]

^<<v11-8-66,66>>^ No oitavo dia desta festa, Salomão despediu o povo, e eles abençoaram o rei. Então voltaram para as suas tendas, alegres e de coração contente por causa de todo o bem que o Senhor  tinha feito a Davi, seu servo, e a Israel, seu povo.

'''

xref:011-1-reis/011-1-reis-007.adoc#v11-7-0[&#60; Capítulo Anterior] | <<v11-8-0,Topo>> | xref:011-1-reis/011-1-reis-009.adoc#v11-9-0[Próximo Capítulo &#62;]