include::./index.adoc[]

[[v11-10-0]]
=== 1 Reis, 10
// naa ?, NAA - Nova Almeida Atualizada

[[v11-10-1]]

^<<v11-10-1,1>>^ Quando a rainha de Sabá ouviu falar da fama de Salomão, com respeito ao nome do Senhor , veio prová-lo com perguntas difíceis.

[[v11-10-2]]

^<<v11-10-2,2>>^ Chegou a Jerusalém com uma enorme comitiva, com camelos carregados de especiarias, grande quantidade de ouro e pedras preciosas. Ela se apresentou diante de Salomão e lhe expôs tudo o que trazia em sua mente.

[[v11-10-3]]

^<<v11-10-3,3>>^ Salomão respondeu todas as perguntas que ela fez, e não houve nada profundo demais que o rei não pudesse explicar.

[[v11-10-4]]

^<<v11-10-4,4>>^ Quando a rainha de Sabá viu toda a sabedoria de Salomão, o palácio que ele havia construído,

[[v11-10-5]]

^<<v11-10-5,5>>^ a comida que era servida na mesa dele, o lugar dos seus oficiais, o serviço dos seus criados e os trajes deles, seus copeiros, e o holocausto que oferecia na Casa do Senhor , ficou como fora de si

[[v11-10-6]]

^<<v11-10-6,6>>^ e disse ao rei: — É verdade o que ouvi na minha terra a respeito de você e a respeito da sua sabedoria.

[[v11-10-7]]

^<<v11-10-7,7>>^ Eu, porém, não acreditava naquelas palavras, até que vim e vi com os meus próprios olhos. Eis que não me contaram nem a metade: você supera em sabedoria e prosperidade a fama que ouvi.

[[v11-10-8]]

^<<v11-10-8,8>>^ Felizes os homens à sua volta, felizes estes seus servos que estão sempre diante de você e que ouvem a sua sabedoria!

[[v11-10-9]]

^<<v11-10-9,9>>^ Bendito seja o Senhor , seu Deus, que se agradou de você e o colocou no trono de Israel. O Senhor  ama Israel para sempre e, por isso, ele o constituiu rei, para que você execute o juízo e a justiça.

[[v11-10-10]]

^<<v11-10-10,10>>^ Ela entregou ao rei quatro toneladas de ouro, grande quantidade de especiarias e pedras preciosas. Nunca mais veio especiaria em tanta abundância, como a que a rainha de Sabá ofereceu ao rei Salomão.

[[v11-10-11]]

^<<v11-10-11,11>>^ Também os navios de Hirão, que transportavam ouro de Ofir, traziam de lá grande quantidade de madeira de sândalo e pedras preciosas.

[[v11-10-12]]

^<<v11-10-12,12>>^ Desta madeira de sândalo o rei mandou fazer corrimões para a Casa do Senhor  e para o palácio real, bem como harpas e liras para os cantores. Tal madeira nunca se havia trazido para ali, nem se viu mais semelhante madeira até o dia de hoje.

[[v11-10-13]]

^<<v11-10-13,13>>^ O rei Salomão deu à rainha de Sabá tudo o que ela quis e pediu, além de tudo o que lhe deu por sua generosidade real. Então ela voltou e foi para a sua terra, ela e os seus servos.

[[v11-10-14]]

^<<v11-10-14,14>>^ O peso do ouro que se trazia a Salomão a cada ano era de cerca de vinte e três toneladas,

[[v11-10-15]]

^<<v11-10-15,15>>^ além do que entrava dos vendedores e dos negociantes, de todos os reis da Arábia e dos governadores da terra.

[[v11-10-16]]

^<<v11-10-16,16>>^ O rei Salomão fez duzentos grandes escudos de ouro batido, empregando sete quilos e duzentos gramas de ouro em cada escudo.

[[v11-10-17]]

^<<v11-10-17,17>>^ Fez também trezentos escudos menores de ouro batido, empregando um quilo e oitocentos gramas de ouro em cada escudo. E o rei os pôs na Casa do Bosque do Líbano.

[[v11-10-18]]

^<<v11-10-18,18>>^ O rei fez também um grande trono de marfim e o cobriu de ouro puríssimo.

[[v11-10-19]]

^<<v11-10-19,19>>^ O trono tinha seis degraus, e o encosto do trono, ao alto, era redondo. De ambos os lados do assento havia um braço, e a figura de um leão junto a cada um dos braços.

[[v11-10-20]]

^<<v11-10-20,20>>^ Doze leões estavam ali sobre os seis degraus, um em cada extremo destes. Nunca se havia feito obra semelhante em nenhum outro reino.

[[v11-10-21]]

^<<v11-10-21,21>>^ Todas as taças que o rei Salomão usava para beber eram de ouro, e também de ouro puro eram todos os objetos da Casa do Bosque do Líbano. Não havia nada de prata, porque nos dias de Salomão não se dava nenhum valor a ela.

[[v11-10-22]]

^<<v11-10-22,22>>^ Porque o rei tinha no mar uma frota de Társis, junto com os navios de Hirão. De três em três anos, a frota voltava de Társis, trazendo ouro, prata, marfim, bugios e pavões.

[[v11-10-23]]

^<<v11-10-23,23>>^ Assim, o rei Salomão excedeu a todos os reis do mundo, tanto em riqueza como em sabedoria.

[[v11-10-24]]

^<<v11-10-24,24>>^ Todo o mundo queria ver Salomão para ouvir a sabedoria que Deus tinha posto no coração dele.

[[v11-10-25]]

^<<v11-10-25,25>>^ Cada um trazia o seu presente: objetos de prata e de ouro, roupas, armaduras, especiarias, cavalos e mulas. E foi assim ano após ano.

[[v11-10-26]]

^<<v11-10-26,26>>^ Salomão ajuntou carros de guerra e cavaleiros. Tinha mil e quatrocentos carros de guerra e doze mil cavaleiros, que espalhou pelas cidades onde mantinha os carros, deixando uma parte junto ao rei, em Jerusalém.

[[v11-10-27]]

^<<v11-10-27,27>>^ O rei fez com que, em Jerusalém, a prata fosse tão comum como as pedras e os cedros fossem tão numerosos como os sicômoros que estão na Sefelá.

[[v11-10-28]]

^<<v11-10-28,28>>^ Os cavalos de Salomão vinham do Egito e da Cilícia, e comerciantes do rei os importavam da Cilícia por certo preço.

[[v11-10-29]]

^<<v11-10-29,29>>^ Importava-se do Egito um carro de guerra por seiscentas moedas de prata e um cavalo por cento e cinquenta. Nas mesmas condições, as caravanas os traziam e os exportavam para todos os reis dos heteus e para os reis da Síria.

'''

xref:011-1-reis/011-1-reis-009.adoc#v11-9-0[&#60; Capítulo Anterior] | <<v11-10-0,Topo>> | xref:011-1-reis/011-1-reis-011.adoc#v11-11-0[Próximo Capítulo &#62;]