include::./index.adoc[]

[[v11-18-0]]
=== 1 Reis, 18
// naa ?, NAA - Nova Almeida Atualizada

[[v11-18-1]]

^<<v11-18-1,1>>^ Muito tempo depois, no terceiro ano da seca, a palavra do Senhor  veio a Elias, dizendo: — Vá apresentar-se a Acabe, porque farei cair chuva sobre a terra.

[[v11-18-2]]

^<<v11-18-2,2>>^ Então Elias foi se apresentar a Acabe. E a fome era extrema em Samaria.

[[v11-18-3]]

^<<v11-18-3,3>>^ Acabe chamou Obadias, o responsável pelo palácio. Este Obadias era um homem que temia muito o Senhor .

[[v11-18-4]]

^<<v11-18-4,4>>^ Assim, quando Jezabel exterminava os profetas do Senhor , Obadias tomou cem profetas e, em grupos de cinquenta, os escondeu em cavernas, e os sustentou com pão e água.

[[v11-18-5]]

^<<v11-18-5,5>>^ E Acabe disse a Obadias: — Vá pela terra a todas as fontes de água e a todos os vales; pode ser que achemos capim, para que salvemos a vida dos cavalos e das mulas e não percamos todos os animais.

[[v11-18-6]]

^<<v11-18-6,6>>^ Repartiram entre si a terra que iam percorrer; Acabe foi sozinho por um caminho, e Obadias foi sozinho por outro.

[[v11-18-7]]

^<<v11-18-7,7>>^ Quando Obadias já estava a caminho, eis que Elias se encontrou com ele. Obadias, reconhecendo-o, prostrou-se com o rosto em terra e disse: — É você mesmo? É o meu senhor Elias?

[[v11-18-8]]

^<<v11-18-8,8>>^ Ele respondeu: — Sim, sou eu. Vá e diga a seu senhor: "Eis que Elias está aqui."

[[v11-18-9]]

^<<v11-18-9,9>>^ Mas Obadias disse: — Em que pequei, para que você queira entregar este seu servo nas mãos de Acabe, e ele me mate?

[[v11-18-10]]

^<<v11-18-10,10>>^ Tão certo como vive o Senhor , seu Deus, não houve nação nem reino aonde meu senhor, o rei, não mandasse homens à sua procura. E, quando diziam: "Ele não está aqui", fazia aquele reino ou aquela nação jurar que não o haviam encontrado.

[[v11-18-11]]

^<<v11-18-11,11>>^ E agora você quer que eu vá dizer ao meu senhor, o rei, que Elias está aqui?

[[v11-18-12]]

^<<v11-18-12,12>>^ Pode ser que, tão logo eu me afaste de você, o Espírito do Senhor  Deus o leve não sei para onde, e, se eu der a notícia a Acabe e ele não o encontrar, ele matará a mim, este seu servo, que temo o Senhor  desde a minha mocidade.

[[v11-18-13]]

^<<v11-18-13,13>>^ Por acaso não contaram a meu senhor o que fiz, quando Jezabel matava os profetas do Senhor , como escondi cem dos profetas do Senhor  em cavernas, de cinquenta em cinquenta, e os sustentei com pão e água?

[[v11-18-14]]

^<<v11-18-14,14>>^ E agora você quer que eu vá e diga ao meu senhor que Elias está aqui? Ele vai me matar!

[[v11-18-15]]

^<<v11-18-15,15>>^ Elias respondeu: — Tão certo como vive o Senhor  dos Exércitos, a quem eu sirvo, hoje mesmo me apresentarei a ele.

[[v11-18-16]]

^<<v11-18-16,16>>^ Então Obadias foi se encontrar com Acabe e lhe deu a notícia. E Acabe foi se encontrar com Elias.

[[v11-18-17]]

^<<v11-18-17,17>>^ Quando Acabe viu Elias, disse: — Então é você, o perturbador de Israel?

[[v11-18-18]]

^<<v11-18-18,18>>^ Elias respondeu: — Eu não tenho perturbado Israel. Quem tem perturbado Israel é você e a casa de seu pai, porque vocês abandonaram os mandamentos do Senhor  e seguiram os baalins.

[[v11-18-19]]

^<<v11-18-19,19>>^ Agora ordene que todo o Israel venha se encontrar comigo no monte Carmelo. Convoque também os quatrocentos e cinquenta profetas de Baal e os quatrocentos profetas da deusa Aserá que são sustentados por Jezabel.

[[v11-18-20]]

^<<v11-18-20,20>>^ Então Acabe enviou mensageiros a todos os filhos de Israel e ajuntou os profetas no monte Carmelo.

[[v11-18-21]]

^<<v11-18-21,21>>^ Depois, Elias se aproximou de todo o povo e disse: — Até quando vocês ficarão pulando de um lado para outro? Se o Senhor  é Deus, sigam-no; se é Baal, sigam-no. Porém o povo não disse uma só palavra.

[[v11-18-22]]

^<<v11-18-22,22>>^ Então Elias disse ao povo: — Eu sou o único que restou dos profetas do Senhor , e os profetas de Baal são quatrocentos e cinquenta homens.

[[v11-18-23]]

^<<v11-18-23,23>>^ Tragam, agora, dois novilhos. Eles que escolham para si um dos novilhos e, cortando-o em pedaços, o ponham sobre a lenha, porém não ponham fogo. Eu prepararei o outro novilho e o porei sobre a lenha, mas não porei fogo.

[[v11-18-24]]

^<<v11-18-24,24>>^ Então eles invocarão o nome de seu deus, e eu invocarei o nome do Senhor . E há de ser que o deus que responder com fogo esse é que é Deus. E todo o povo respondeu: — É uma boa proposta!

[[v11-18-25]]

^<<v11-18-25,25>>^ Elias disse aos profetas de Baal: — Escolham um dos novilhos e preparem-no primeiro, porque vocês são muitos. Depois, invoquem o nome do deus de vocês, mas não ponham fogo na lenha.

[[v11-18-26]]

^<<v11-18-26,26>>^ Pegaram o novilho que lhes foi trazido, prepararam-no e invocaram o nome de Baal, desde a manhã até o meio-dia, dizendo: — Ó Baal, responde-nos! Porém não se ouviu nenhuma voz e não houve quem respondesse. E ficaram pulando ao redor do altar que tinham feito.

[[v11-18-27]]

^<<v11-18-27,27>>^ Ao meio-dia, Elias começou a zombar deles, dizendo: — Gritem mais alto, porque ele é deus! Pode ser que esteja meditando, atendendo a necessidades ou viajando. Talvez esteja dormindo e necessite que o acordem.

[[v11-18-28]]

^<<v11-18-28,28>>^ E eles clamavam em altas vozes e se cortavam com facas e com lanças, segundo o seu costume, até ficarem cobertos de sangue.

[[v11-18-29]]

^<<v11-18-29,29>>^ Passado o meio-dia, eles profetizaram, até a hora do sacrifício da tarde; porém não houve voz, nem resposta, nem atenção alguma.

[[v11-18-30]]

^<<v11-18-30,30>>^ Então Elias disse a todo o povo: — Aproximem-se de mim. E todo o povo se aproximou dele. Elias restaurou o altar do Senhor , que estava em ruínas.

[[v11-18-31]]

^<<v11-18-31,31>>^ Pegou doze pedras, segundo o número das tribos dos filhos de Jacó, a quem tinha vindo a palavra do Senhor , dizendo: "O seu nome será Israel."

[[v11-18-32]]

^<<v11-18-32,32>>^ Com aquelas pedras edificou o altar em nome do Senhor . Ao redor dele fez uma vala capaz de conter duas medidas de sementes

[[v11-18-33]]

^<<v11-18-33,33>>^ e então armou a lenha, cortou o novilho em pedaços e os pôs sobre a lenha.

[[v11-18-34]]

^<<v11-18-34,34>>^ Então disse: — Encham quatro cântaros com água e derramem sobre o holocausto e sobre a lenha. Disse ainda: — Façam isso outra vez. E eles o fizeram. Disse mais: — Façam isso pela terceira vez. E eles o fizeram pela terceira vez.

[[v11-18-35]]

^<<v11-18-35,35>>^ A água escorria do altar e enchia também a vala aberta.

[[v11-18-36]]

^<<v11-18-36,36>>^ Quando chegou a hora do sacrifício da tarde, o profeta Elias se aproximou do altar e disse: — Ó Senhor , Deus de Abraão, de Isaque e de Israel, que hoje se fique sabendo que tu és Deus em Israel, e que eu sou o teu servo e que, segundo a tua palavra, fiz todas estas coisas.

[[v11-18-37]]

^<<v11-18-37,37>>^ Responde-me, Senhor , responde-me, para que este povo saiba que tu, Senhor , és Deus e que fizeste o coração deles voltar para ti.

[[v11-18-38]]

^<<v11-18-38,38>>^ Então caiu fogo do Senhor  e consumiu o holocausto, a lenha, as pedras e a terra, e ainda lambeu a água que estava na vala.

[[v11-18-39]]

^<<v11-18-39,39>>^ Quando o povo viu isso, todos se prostraram com o rosto em terra e disseram: — O Senhor  é Deus! Só o Senhor  é Deus!

[[v11-18-40]]

^<<v11-18-40,40>>^ Então Elias disse: — Prendam os profetas de Baal! Que nem um deles escape! Eles os prenderam, e Elias os fez descer até o ribeiro de Quisom e ali os matou.

[[v11-18-41]]

^<<v11-18-41,41>>^ Então Elias disse a Acabe: — Suba, vá comer e beber, porque já se ouve o barulho de abundante chuva.

[[v11-18-42]]

^<<v11-18-42,42>>^ Acabe subiu para comer e beber, mas Elias subiu até o alto do Carmelo. Ali, encurvado para a terra, pôs o rosto entre os joelhos

[[v11-18-43]]

^<<v11-18-43,43>>^ e disse ao seu servo: — Vá e olhe para o lado do mar. Ele foi, olhou e disse: — Não vi nada. Então Elias disse: — Volte. E assim por sete vezes.

[[v11-18-44]]

^<<v11-18-44,44>>^ Na sétima vez o servo disse: — Eis que se levanta do mar uma nuvem pequena como a palma da mão de um homem. Então Elias disse: — Suba e diga a Acabe: "Apronte o seu carro e desça, para que a chuva não o detenha."

[[v11-18-45]]

^<<v11-18-45,45>>^ Em pouco tempo o céu escureceu, com nuvens e vento, e caiu grande chuva. Acabe subiu ao carro e foi para Jezreel.

[[v11-18-46]]

^<<v11-18-46,46>>^ A mão do Senhor  veio sobre Elias, que cingiu os lombos e correu na frente de Acabe, até a entrada de Jezreel.

'''

xref:011-1-reis/011-1-reis-017.adoc#v11-17-0[&#60; Capítulo Anterior] | <<v11-18-0,Topo>> | xref:011-1-reis/011-1-reis-019.adoc#v11-19-0[Próximo Capítulo &#62;]