include::./index.adoc[]

[[v11-3-0]]
=== 1 Reis, 3
// naa ?, NAA - Nova Almeida Atualizada

[[v11-3-1]]

^<<v11-3-1,1>>^ Salomão aliou-se com Faraó, rei do Egito, pois tomou por mulher a filha de Faraó. Ele a trouxe à Cidade de Davi, até que acabasse a construção do seu palácio, da Casa do Senhor  e da muralha em volta de Jerusalém.

[[v11-3-2]]

^<<v11-3-2,2>>^ Entretanto, o povo oferecia sacrifícios nos lugares altos, porque até aqueles dias ainda não se tinha edificado templo ao nome do Senhor .

[[v11-3-3]]

^<<v11-3-3,3>>^ Salomão amava o Senhor , andando nos preceitos de Davi, seu pai; porém oferecia sacrifícios e queimava incenso nos lugares altos.

[[v11-3-4]]

^<<v11-3-4,4>>^ O rei foi a Gibeão para lá oferecer sacrifícios, porque era o lugar alto mais importante. Naquele altar, Salomão ofereceu mil holocaustos.

[[v11-3-5]]

^<<v11-3-5,5>>^ Em Gibeão, o Senhor  apareceu a Salomão de noite, em sonhos. E Deus lhe disse: — Peça o que você quer que eu lhe dê.

[[v11-3-6]]

^<<v11-3-6,6>>^ Salomão respondeu: — Foste muito bondoso com o teu servo Davi, meu pai, porque ele andou contigo em fidelidade, em justiça e em retidão de coração, diante da tua face. Mantiveste para com ele esta grande bondade e lhe deste um filho que se assentasse no seu trono, como hoje se vê.

[[v11-3-7]]

^<<v11-3-7,7>>^ E agora, ó Senhor , meu Deus, tu fizeste reinar teu servo em lugar de Davi, meu pai. Mas eu não passo de uma criança, não sei como devo agir.

[[v11-3-8]]

^<<v11-3-8,8>>^ Teu servo está no meio do teu povo que escolheste, povo grande, tão numeroso que não se pode contar.

[[v11-3-9]]

^<<v11-3-9,9>>^ Dá, pois, ao teu servo coração compreensivo para governar o teu povo, para que, com prudência, saiba discernir entre o bem e o mal. Pois quem seria capaz de governar este teu grande povo?

[[v11-3-10]]

^<<v11-3-10,10>>^ Estas palavras agradaram ao Senhor, por haver Salomão pedido tal coisa.

[[v11-3-11]]

^<<v11-3-11,11>>^ E Deus lhe disse: — Já que você pediu isso e não me pediu longevidade, nem riquezas, nem a morte de seus inimigos, mas pediu entendimento, para discernir o que é justo,

[[v11-3-12]]

^<<v11-3-12,12>>^ eis que farei como você pediu. Eu lhe dou um coração sábio e inteligente, de maneira que antes de você nunca houve ninguém igual a você, nem haverá depois de você.

[[v11-3-13]]

^<<v11-3-13,13>>^ Também lhe dou o que você não me pediu, tanto riquezas como glória, de modo que, entre os reis, não haverá ninguém semelhante a você durante os dias da sua vida.

[[v11-3-14]]

^<<v11-3-14,14>>^ Se você andar nos meus caminhos e guardar os meus estatutos e os meus mandamentos, como fez Davi, seu pai, eu prolongarei os seus dias.

[[v11-3-15]]

^<<v11-3-15,15>>^ Salomão acordou, e eis que era um sonho. Voltou para Jerusalém, pôs-se diante da arca da aliança do Senhor , ofereceu holocaustos, apresentou ofertas pacíficas e deu um banquete a todos os seus oficiais.

[[v11-3-16]]

^<<v11-3-16,16>>^ Então duas prostitutas foram falar com o rei Salomão. Apresentaram-se diante dele

[[v11-3-17]]

^<<v11-3-17,17>>^ e uma das mulheres disse: — Ah! Meu senhor, eu e esta mulher moramos na mesma casa, onde dei à luz um filho.

[[v11-3-18]]

^<<v11-3-18,18>>^ No terceiro dia, depois do meu parto, também esta mulher teve um filho. Estávamos juntas. Não havia nenhuma outra pessoa conosco na casa; somente nós duas estávamos ali.

[[v11-3-19]]

^<<v11-3-19,19>>^ De noite, o filho desta mulher morreu, porque ela se deitou sobre ele.

[[v11-3-20]]

^<<v11-3-20,20>>^ Ela levantou-se no meio da noite e, enquanto esta sua serva dormia, tirou o meu filho, que estava do meu lado, e o pôs na cama dela; depois colocou o filho dela, morto, nos meus braços.

[[v11-3-21]]

^<<v11-3-21,21>>^ Quando eu me levantei de madrugada para dar de mamar ao meu filho, eis que ele estava morto. Porém, quando reparei nele pela manhã, eis que não era o filho que eu tinha dado à luz.

[[v11-3-22]]

^<<v11-3-22,22>>^ Então a outra mulher disse: — Não! O que está vivo é o meu filho; o seu é o que está morto. Porém a primeira mulher respondeu: — Não! O que está morto é o seu filho; o meu é o que está vivo. E assim elas falaram diante do rei.

[[v11-3-23]]

^<<v11-3-23,23>>^ Então o rei Salomão disse: — Esta diz: "O que está vivo é o meu filho, e o seu filho é o que está morto"; e a outra responde: "Não, o que está morto é o seu filho, e o meu filho é o que está vivo."

[[v11-3-24]]

^<<v11-3-24,24>>^ E o rei continuou: — Tragam-me uma espada. E trouxeram uma espada diante do rei.

[[v11-3-25]]

^<<v11-3-25,25>>^ Então o rei disse: — Cortem o menino que está vivo em duas partes e deem metade a uma e metade a outra.

[[v11-3-26]]

^<<v11-3-26,26>>^ Então se aguçou o amor materno da mulher cujo filho estava vivo e ela disse ao rei: — Ah! Meu senhor, deem a ela o menino vivo! Não o matem de jeito nenhum! Porém a outra dizia: — Ele não será nem meu nem seu. Podem cortá-lo ao meio!

[[v11-3-27]]

^<<v11-3-27,27>>^ Então o rei disse: — Entreguem o menino vivo à primeira mulher. Não o matem. Ela é a mãe do menino.

[[v11-3-28]]

^<<v11-3-28,28>>^ Todo o Israel ouviu a sentença que o rei havia proferido. E todos tiveram profundo respeito ao rei, porque viram que havia nele a sabedoria de Deus, para fazer justiça.

'''

xref:011-1-reis/011-1-reis-002.adoc#v11-2-0[&#60; Capítulo Anterior] | <<v11-3-0,Topo>> | xref:011-1-reis/011-1-reis-004.adoc#v11-4-0[Próximo Capítulo &#62;]