include::./index.adoc[]

[[v11-22-0]]
=== 1 Reis, 22
// naa ?, NAA - Nova Almeida Atualizada

[[v11-22-1]]

^<<v11-22-1,1>>^ Três anos se passaram sem haver guerra entre Síria e Israel.

[[v11-22-2]]

^<<v11-22-2,2>>^ Porém, no terceiro ano, Josafá, rei de Judá, foi visitar o rei de Israel.

[[v11-22-3]]

^<<v11-22-3,3>>^ Este perguntou aos seus servos: — Vocês não sabem que Ramote-Gileade é nossa, e nós ficamos quietos e não a tiramos das mãos do rei da Síria?

[[v11-22-4]]

^<<v11-22-4,4>>^ Então perguntou a Josafá: — Você vai comigo à batalha contra Ramote-Gileade? Josafá respondeu ao rei de Israel: — Sou como você é, o meu povo é como o seu povo, e os meus cavalos são como os seus cavalos.

[[v11-22-5]]

^<<v11-22-5,5>>^ Josafá disse mais ao rei de Israel: — Consulte primeiro a palavra do Senhor .

[[v11-22-6]]

^<<v11-22-6,6>>^ Então o rei de Israel reuniu os profetas, cerca de quatrocentos homens, e lhes perguntou: — Devo ir e lutar contra Ramote-Gileade ou devo me conter? Eles responderam: — Vá, porque o Senhor a entregará nas mãos do rei.

[[v11-22-7]]

^<<v11-22-7,7>>^ Mas Josafá perguntou: — Não há aqui ainda algum profeta do Senhor , para o consultarmos?

[[v11-22-8]]

^<<v11-22-8,8>>^ O rei de Israel respondeu a Josafá: — Há um ainda, por meio de quem podemos consultar o Senhor . Mas eu o odeio, porque nunca profetiza de mim o que é bom, mas somente o que é mau. É Micaías, filho de Inlá. Josafá disse: — O rei não deveria falar assim.

[[v11-22-9]]

^<<v11-22-9,9>>^ Então o rei de Israel chamou um oficial e disse: — Traga-me depressa Micaías, filho de Inlá.

[[v11-22-10]]

^<<v11-22-10,10>>^ O rei de Israel e Josafá, rei de Judá, estavam assentados, cada um no seu trono, vestidos de trajes reais, numa eira à entrada do portão da cidade de Samaria; e todos os profetas profetizavam diante deles.

[[v11-22-11]]

^<<v11-22-11,11>>^ Zedequias, filho de Quenaana, fez para si uns chifres de ferro e disse: — Assim diz o Senhor : "Com estes você dará chifradas nos sírios até que estejam destruídos."

[[v11-22-12]]

^<<v11-22-12,12>>^ Todos os profetas profetizaram assim, dizendo: — Suba a Ramote-Gileade! Você triunfará! O Senhor  a entregará nas mãos do rei.

[[v11-22-13]]

^<<v11-22-13,13>>^ O mensageiro que tinha ido chamar Micaías falou-lhe, dizendo: — Eis que as palavras dos profetas a uma voz predizem coisas boas para o rei. Portanto, que a sua palavra seja como a palavra de um deles; fale o que é bom.

[[v11-22-14]]

^<<v11-22-14,14>>^ Micaías respondeu: — Tão certo como vive o Senhor , o que o Senhor  me disser, isso falarei.

[[v11-22-15]]

^<<v11-22-15,15>>^ Quando ele chegou à presença do rei, este lhe perguntou: — Micaías, devemos ir a Ramote-Gileade para a batalha ou devemos nos conter? Ele respondeu: — Vá! Você triunfará! O Senhor  a entregará nas mãos do rei.

[[v11-22-16]]

^<<v11-22-16,16>>^ O rei lhe disse: — Quantas vezes devo fazer você jurar que não me fale a não ser a verdade em nome do Senhor ?

[[v11-22-17]]

^<<v11-22-17,17>>^ Então Micaías disse: — Vi todo o Israel disperso pelos montes, como ovelhas que não têm pastor. E o Senhor  Deus disse: "Estes não têm dono; que cada um volte em paz para a sua casa."

[[v11-22-18]]

^<<v11-22-18,18>>^ Então o rei de Israel disse a Josafá: — Eu não disse a você que a meu respeito ele não profetiza o que é bom, mas somente o que é mau?

[[v11-22-19]]

^<<v11-22-19,19>>^ Micaías prosseguiu: — Portanto, ouça a palavra do Senhor : Vi o Senhor  assentado no seu trono, e todo o exército do céu estava junto dele, à sua direita e à sua esquerda.

[[v11-22-20]]

^<<v11-22-20,20>>^ Então o Senhor  perguntou: "Quem enganará Acabe, para que vá e seja morto em Ramote-Gileade?" E um dizia uma coisa, e outro dizia outra coisa.

[[v11-22-21]]

^<<v11-22-21,21>>^ Então um espírito saiu, se apresentou diante do Senhor  e disse: "Eu o enganarei." O Senhor  perguntou: "Como?"

[[v11-22-22]]

^<<v11-22-22,22>>^ Ele respondeu: "Sairei e serei um espírito mentiroso na boca de todos os profetas do rei." Então o Senhor  disse: "Você conseguirá enganá-lo. Vá e faça assim."

[[v11-22-23]]

^<<v11-22-23,23>>^ E agora eis que o Senhor  pôs esse espírito mentiroso na boca de todos estes seus profetas e o Senhor  declarou que um mal vai lhe acontecer.

[[v11-22-24]]

^<<v11-22-24,24>>^ Então Zedequias, filho de Quenaana, chegou, deu uma bofetada em Micaías e perguntou: — Por onde é que passou o Espírito do Senhor  ao sair de mim para falar com você?

[[v11-22-25]]

^<<v11-22-25,25>>^ Micaías respondeu: — Eis que você o verá no dia em que estiver correndo de quarto em quarto, tentando se esconder!

[[v11-22-26]]

^<<v11-22-26,26>>^ Então o rei de Israel disse: — Prenda Micaías e leve-o de volta a Amom, governador da cidade, e a Joás, filho do rei.

[[v11-22-27]]

^<<v11-22-27,27>>^ E diga: "Assim diz o rei: Metam este homem na cadeia e o ponham a pão e água, até que eu volte em paz."

[[v11-22-28]]

^<<v11-22-28,28>>^ Micaías disse: — Se o rei de fato voltar em paz, é porque o Senhor  não falou por meio de mim. E acrescentou: — Que todos os povos ouçam isto!

[[v11-22-29]]

^<<v11-22-29,29>>^ O rei de Israel e Josafá, rei de Judá, foram atacar Ramote-Gileade.

[[v11-22-30]]

^<<v11-22-30,30>>^ O rei de Israel disse a Josafá: — Eu vou me disfarçar e entrar no combate, mas você use os seus trajes reais. E assim o rei de Israel se disfarçou e entrou no combate.

[[v11-22-31]]

^<<v11-22-31,31>>^ Ora, o rei da Síria havia ordenado aos trinta e dois capitães dos seus carros de guerra que não lutassem nem contra pequeno nem contra grande, mas somente contra o rei de Israel.

[[v11-22-32]]

^<<v11-22-32,32>>^ Quando os capitães dos carros viram Josafá, disseram: — Aquele certamente é o rei de Israel. E se dirigiram até ele para o atacar. Porém Josafá gritou.

[[v11-22-33]]

^<<v11-22-33,33>>^ Quando os capitães dos carros de guerra viram que não era o rei de Israel, deixaram de persegui-lo.

[[v11-22-34]]

^<<v11-22-34,34>>^ Então um homem entesou o arco e, atirando ao acaso, atingiu o rei de Israel por entre as juntas da sua armadura. Então o rei Acabe disse ao condutor do seu carro: — Dê a volta e leve-me para fora do combate, porque estou gravemente ferido.

[[v11-22-35]]

^<<v11-22-35,35>>^ A batalha se intensificou naquele dia. Quanto ao rei, seguraram-no em pé no seu carro de guerra de frente para os sírios, mas à tarde ele morreu. O sangue corria da ferida para o fundo do carro.

[[v11-22-36]]

^<<v11-22-36,36>>^ Ao pôr do sol, fez-se ouvir um grito pelo acampamento, que dizia: — Cada um para a sua cidade, e cada um para a sua terra!

[[v11-22-37]]

^<<v11-22-37,37>>^ Morto o rei, levaram-no a Samaria, onde o sepultaram.

[[v11-22-38]]

^<<v11-22-38,38>>^ Quando lavaram o carro de guerra junto à cisterna de Samaria, os cães lamberam o sangue do rei, segundo a palavra que o Senhor  tinha dito; as prostitutas banharam-se naquelas águas.

[[v11-22-39]]

^<<v11-22-39,39>>^ Quanto aos demais atos de Acabe, a tudo o que fez, ao palácio de marfim que construiu e a todas as cidades que edificou, não está tudo escrito no Livro da História dos Reis de Israel?

[[v11-22-40]]

^<<v11-22-40,40>>^ Assim, Acabe morreu, e Acazias, seu filho, reinou em seu lugar.

[[v11-22-41]]

^<<v11-22-41,41>>^ Josafá, filho de Asa, começou a reinar sobre Judá no quarto ano do reinado de Acabe, rei de Israel.

[[v11-22-42]]

^<<v11-22-42,42>>^ Josafá tinha trinta e cinco anos de idade quando começou a reinar e reinou vinte e cinco anos em Jerusalém. A mãe dele se chamava Azuba e era filha de Sili.

[[v11-22-43]]

^<<v11-22-43,43>>^ Josafá andou em todos os caminhos de Asa, seu pai; não se desviou deles e fez o que era reto aos olhos do Senhor .

[[v11-22-44]]

^<<v11-22-44,44>>^ Os lugares altos, porém, não foram destruídos; neles, o povo ainda oferecia sacrifícios e queimava incenso.

[[v11-22-45]]

^<<v11-22-45,45>>^ Josafá viveu em paz com o rei de Israel.

[[v11-22-46]]

^<<v11-22-46,46>>^ Quanto aos demais atos de Josafá, ao poder que mostrou e como guerreou, não está tudo escrito no Livro da História dos Reis de Judá?

[[v11-22-47]]

^<<v11-22-47,47>>^ Também exterminou da terra os restantes dos prostitutos cultuais que ficaram nos dias de Asa, seu pai.

[[v11-22-48]]

^<<v11-22-48,48>>^ Nessa época não havia rei em Edom, porém somente um governador.

[[v11-22-49]]

^<<v11-22-49,49>>^ Josafá fez grandes navios, para irem a Ofir em busca de ouro; porém não foram, porque os navios se quebraram em Eziom-Geber.

[[v11-22-50]]

^<<v11-22-50,50>>^ Então Acazias, filho de Acabe, disse a Josafá: — Deixe que os meus servos naveguem com os seus. Porém Josafá não quis.

[[v11-22-51]]

^<<v11-22-51,51>>^ Josafá morreu e foi sepultado na Cidade de Davi, seu pai; e Jeorão, seu filho, reinou em seu lugar.

[[v11-22-52]]

^<<v11-22-52,52>>^ Acazias, filho de Acabe, começou a reinar sobre Israel em Samaria, no décimo sétimo ano do reinado de Josafá, rei de Judá; e reinou dois anos sobre Israel.

[[v11-22-53]]

^<<v11-22-53,53>>^ Fez o que era mau aos olhos do Senhor , pois andou nos caminhos de seu pai, bem como nos caminhos de sua mãe e nos caminhos de Jeroboão, filho de Nebate, que levou Israel a pecar.

[[v11-22-54]]

^<<v11-22-54,54>>^ Ele serviu a Baal, e o adorou, como o seu pai havia feito antes dele, provocando o Senhor , Deus de Israel, à ira.

'''

xref:011-1-reis/011-1-reis-021.adoc#v11-21-0[&#60; Capítulo Anterior] | <<v11-22-0,Topo>> | xref:012-2-reis/012-2-reis-001.adoc#v12-1-0[Próximo Capítulo &#62;]