include::./index.adoc[]

[[v11-9-0]]
=== 1 Reis, 9
// naa ?, NAA - Nova Almeida Atualizada

[[v11-9-1]]

^<<v11-9-1,1>>^ E aconteceu que, quando Salomão acabou de edificar a Casa do Senhor , o palácio real e tudo o que tinha desejado e decidido fazer,

[[v11-9-2]]

^<<v11-9-2,2>>^ o Senhor  tornou a aparecer-lhe, como tinha aparecido em Gibeão.

[[v11-9-3]]

^<<v11-9-3,3>>^ E o Senhor  lhe disse: — Ouvi a sua oração e a súplica que você fez diante de mim. Santifiquei o templo que você edificou, a fim de pôr ali o meu nome para sempre; os meus olhos e o meu coração estarão ali todos os dias.

[[v11-9-4]]

^<<v11-9-4,4>>^ Se você andar diante de mim como fez o seu pai Davi, com integridade de coração e com sinceridade, fazendo segundo tudo o que lhe ordenei e guardando os meus estatutos e os meus juízos,

[[v11-9-5]]

^<<v11-9-5,5>>^ também confirmarei o trono de seu reino sobre Israel para sempre, como prometi a Davi, seu pai, dizendo: "Nunca lhe faltará sucessor ao trono de Israel."

[[v11-9-6]]

^<<v11-9-6,6>>^ Porém, se vocês ou os seus filhos se afastarem de mim e não guardarem os meus mandamentos e os meus estatutos, que eu lhes prescrevi, e se servirem outros deuses e os adorarem,

[[v11-9-7]]

^<<v11-9-7,7>>^ então eliminarei Israel da terra que lhe dei, e lançarei para longe da minha presença este templo, que santifiquei ao meu nome. E Israel virá a ser motivo de provérbio e de escárnio entre todos os povos.

[[v11-9-8]]

^<<v11-9-8,8>>^ E todo aquele que passar por este templo, agora tão exaltado, ficará espantado e zombará. E perguntarão: "Por que o Senhor  fez isto com esta terra e este templo?"

[[v11-9-9]]

^<<v11-9-9,9>>^ E a resposta será: "Porque deixaram o Senhor , seu Deus, que tirou da terra do Egito os seus pais, e se apegaram a outros deuses, os adoraram e os serviram. Por isso o Senhor  trouxe sobre eles todo este mal."

[[v11-9-10]]

^<<v11-9-10,10>>^ Ao fim de vinte anos, Salomão havia terminado as duas casas, a Casa do Senhor  e o palácio real.

[[v11-9-11]]

^<<v11-9-11,11>>^ Como Hirão, rei de Tiro, havia trazido a Salomão madeira de cedro e de cipreste e ouro, tanto quanto ele precisava, este lhe deu vinte cidades na terra da Galileia.

[[v11-9-12]]

^<<v11-9-12,12>>^ Hirão de Tiro foi ver as cidades que Salomão lhe tinha dado, mas elas não lhe agradaram.

[[v11-9-13]]

^<<v11-9-13,13>>^ Por isso disse a Salomão: — Que cidades são essas que você me deu, meu irmão? E lhes deram o nome de Terra de Cabul, que é usado até o dia de hoje.

[[v11-9-14]]

^<<v11-9-14,14>>^ Hirão tinha enviado ao rei quatro toneladas de ouro.

[[v11-9-15]]

^<<v11-9-15,15>>^ A razão por que Salomão impôs o trabalho forçado é esta: construir a Casa do Senhor , o seu próprio palácio, a fortaleza de Milo e a muralha de Jerusalém, bem como Hazor, Megido e Gezer.

[[v11-9-16]]

^<<v11-9-16,16>>^ Porque Faraó, rei do Egito, havia atacado e conquistado Gezer, queimando a cidade e matando os cananeus que moravam nela, entregando-a como dote à sua filha, mulher de Salomão.

[[v11-9-17]]

^<<v11-9-17,17>>^ Assim, Salomão reconstruiu Gezer, Bete-Horom-de-Baixo,

[[v11-9-18]]

^<<v11-9-18,18>>^ Baalate, Tadmor, no deserto daquela terra,

[[v11-9-19]]

^<<v11-9-19,19>>^ todas as cidades-armazéns que Salomão tinha, as cidades para os carros de guerra, as cidades para os cavaleiros e o que desejou enfim construir em Jerusalém, no Líbano e em toda a terra do seu domínio.

[[v11-9-20]]

^<<v11-9-20,20>>^ Quanto a todo o povo que restou dos amorreus, heteus, ferezeus, heveus e jebuseus e que não eram dos filhos de Israel,

[[v11-9-21]]

^<<v11-9-21,21>>^ e aos seus filhos, que restaram depois deles na terra, os quais os filhos de Israel não puderam destruir totalmente, esses Salomão reduziu à condição de trabalhadores forçados, até hoje.

[[v11-9-22]]

^<<v11-9-22,22>>^ Mas Salomão não obrigou nenhum israelita a trabalhar como escravo. Os israelitas eram homens de guerra, seus oficiais, seus comandantes, seus capitães, chefes dos seus carros de guerra e dos seus cavaleiros.

[[v11-9-23]]

^<<v11-9-23,23>>^ Os principais oficiais que estavam encarregados da obra de Salomão eram quinhentos e cinquenta, que tinham a seu encargo o povo que trabalhava na obra.

[[v11-9-24]]

^<<v11-9-24,24>>^ Quando a filha de Faraó se mudou da Cidade de Davi para o palácio que Salomão havia construído para ela, então ele construiu Milo.

[[v11-9-25]]

^<<v11-9-25,25>>^ Três vezes por ano Salomão oferecia holocaustos e sacrifícios pacíficos sobre o altar que havia edificado ao Senhor  e queimava incenso sobre o altar diante do Senhor . Assim ele terminou a construção do templo.

[[v11-9-26]]

^<<v11-9-26,26>>^ O rei Salomão também construiu uma frota de navios em Eziom-Geber, que fica perto de Elate, na praia do mar Vermelho, na terra de Edom.

[[v11-9-27]]

^<<v11-9-27,27>>^ Hirão enviou, com aquela frota, os seus servos, marinheiros conhecedores do mar, para acompanharem os servos de Salomão.

[[v11-9-28]]

^<<v11-9-28,28>>^ Chegaram a Ofir e de lá trouxeram para o rei Salomão mais de catorze toneladas de ouro.

'''

xref:011-1-reis/011-1-reis-008.adoc#v11-8-0[&#60; Capítulo Anterior] | <<v11-9-0,Topo>> | xref:011-1-reis/011-1-reis-010.adoc#v11-10-0[Próximo Capítulo &#62;]