include::./index.adoc[]

[[v11-16-0]]
=== 1 Reis, 16
// naa ?, NAA - Nova Almeida Atualizada

[[v11-16-1]]

^<<v11-16-1,1>>^ Então a palavra do Senhor  veio a Jeú, filho de Hanani, contra Baasa, dizendo:

[[v11-16-2]]

^<<v11-16-2,2>>^ — Eu o levantei do pó e fiz com que você se tornasse chefe sobre o meu povo de Israel, mas você tem andado no caminho de Jeroboão e tem feito o meu povo de Israel pecar, irritando-me com os seus pecados.

[[v11-16-3]]

^<<v11-16-3,3>>^ Por isso, Baasa, vou exterminar você e os seus descendentes e vou fazer com a sua casa o que fiz com a casa de Jeroboão, filho de Nebate.

[[v11-16-4]]

^<<v11-16-4,4>>^ Se alguém da casa de Baasa morrer na cidade, os cães o comerão; e se alguém morrer no campo, as aves do céu o comerão.

[[v11-16-5]]

^<<v11-16-5,5>>^ Quanto aos demais atos de Baasa, ao que fez e ao seu poder, não está tudo escrito no Livro da História dos Reis de Israel?

[[v11-16-6]]

^<<v11-16-6,6>>^ Baasa morreu e foi sepultado em Tirza. E Elá, seu filho, reinou em seu lugar.

[[v11-16-7]]

^<<v11-16-7,7>>^ Assim, por meio do profeta Jeú, filho de Hanani, a palavra do Senhor  veio contra Baasa e contra a sua descendência, por todo o mal que ele havia feito aos olhos do Senhor , irritando-o com as suas obras e fazendo-se igual à casa de Jeroboão, e também porque matou a casa de Jeroboão.

[[v11-16-8]]

^<<v11-16-8,8>>^ No vigésimo sexto ano do reinado de Asa, rei de Judá, Elá, filho de Baasa, começou a reinar sobre Israel em Tirza; e reinou dois anos.

[[v11-16-9]]

^<<v11-16-9,9>>^ Zinri, seu servo, comandante da metade dos carros de guerra, conspirou contra ele. Elá estava em Tirza, bebendo e embriagando-se na casa de Arsa, seu encarregado em Tirza.

[[v11-16-10]]

^<<v11-16-10,10>>^ Zinri entrou na casa, atacou Elá e o matou, no vigésimo sétimo ano do reinado de Asa, rei de Judá. E Zinri reinou em lugar de Elá.

[[v11-16-11]]

^<<v11-16-11,11>>^ Logo que começou a reinar e se assentou no trono, Zinri matou todos os descendentes de Baasa; não lhe deixou nenhum do sexo masculino, nem dos parentes, nem dos seus amigos.

[[v11-16-12]]

^<<v11-16-12,12>>^ Assim, Zinri exterminou todos os descendentes de Baasa, segundo a palavra do Senhor , anunciada por meio do profeta Jeú, contra Baasa,

[[v11-16-13]]

^<<v11-16-13,13>>^ por todos os pecados que Baasa e o seu filho Elá cometeram, e pelos pecados que fizeram Israel cometer, irritando o Senhor , Deus de Israel, com os seus ídolos.

[[v11-16-14]]

^<<v11-16-14,14>>^ Quanto aos demais atos de Elá e a tudo o que ele fez, não está tudo escrito no Livro da História dos Reis de Israel?

[[v11-16-15]]

^<<v11-16-15,15>>^ No vigésimo sétimo ano do reinado de Asa, rei de Judá, Zinri reinou sete dias em Tirza. O povo estava acampado contra Gibetom, cidade que pertencia aos filisteus.

[[v11-16-16]]

^<<v11-16-16,16>>^ O povo que estava acampado ouviu dizer: "Zinri conspirou contra o rei e o matou." Por isso, naquele mesmo dia, no arraial, todo o Israel constituiu rei sobre Israel a Onri, comandante do exército.

[[v11-16-17]]

^<<v11-16-17,17>>^ Onri saiu de Gibetom, estando todo o Israel com ele, e sitiou Tirza.

[[v11-16-18]]

^<<v11-16-18,18>>^ Quando Zinri viu que a cidade havia sido tomada, foi para a fortaleza do palácio real, pôs fogo no palácio real e morreu,

[[v11-16-19]]

^<<v11-16-19,19>>^ por causa dos pecados que havia cometido, fazendo o que era mau aos olhos do Senhor , andando no caminho de Jeroboão e no pecado que havia cometido, e fazendo Israel pecar.

[[v11-16-20]]

^<<v11-16-20,20>>^ Quanto aos demais atos de Zinri e à conspiração que fez, não está tudo escrito no Livro da História dos Reis de Israel?

[[v11-16-21]]

^<<v11-16-21,21>>^ Então o povo de Israel se dividiu em dois partidos: metade do povo seguia Tibni, filho de Ginate, para o fazer rei, e a outra metade seguia Onri.

[[v11-16-22]]

^<<v11-16-22,22>>^ Mas o povo que seguia Onri prevaleceu contra o que seguia Tibni, filho de Ginate. Tibni morreu, e Onri passou a reinar.

[[v11-16-23]]

^<<v11-16-23,23>>^ No trigésimo primeiro ano do reinado de Asa, rei de Judá, Onri começou a reinar sobre Israel e reinou doze anos. Em Tirza, reinou seis anos.

[[v11-16-24]]

^<<v11-16-24,24>>^ De Semer ele comprou o monte de Samaria por sessenta e oito quilos de prata e o fortificou. E à cidade que edificou sobre o monte chamou de Samaria, nome oriundo de Semer, dono do monte.

[[v11-16-25]]

^<<v11-16-25,25>>^ Onri fez o que era mau aos olhos do Senhor ; fez pior do que todos os reis que vieram antes dele.

[[v11-16-26]]

^<<v11-16-26,26>>^ Andou em todos os caminhos de Jeroboão, filho de Nebate, bem como nos pecados que este levou Israel a cometer, irritando o Senhor , Deus de Israel, com os seus ídolos.

[[v11-16-27]]

^<<v11-16-27,27>>^ Quanto aos demais atos de Onri, ao que fez e ao poder que manifestou, não está tudo escrito no Livro da História dos Reis de Israel?

[[v11-16-28]]

^<<v11-16-28,28>>^ Onri morreu e foi sepultado em Samaria. E Acabe, seu filho, reinou em seu lugar.

[[v11-16-29]]

^<<v11-16-29,29>>^ Acabe, filho de Onri, começou a reinar sobre Israel no trigésimo oitavo ano do reinado de Asa, rei de Judá. E Acabe, filho de Onri, reinou sobre Israel, em Samaria, vinte e dois anos.

[[v11-16-30]]

^<<v11-16-30,30>>^ Acabe, filho de Onri, fez o que era mau aos olhos do Senhor , mais do que todos os reis que vieram antes dele.

[[v11-16-31]]

^<<v11-16-31,31>>^ Como se fosse pouca coisa andar nos pecados de Jeroboão, filho de Nebate, Acabe foi mais longe e tomou por mulher Jezabel, filha de Etbaal, rei dos sidônios; e foi, serviu Baal e o adorou.

[[v11-16-32]]

^<<v11-16-32,32>>^ Levantou um altar a Baal, no templo de Baal que tinha edificado em Samaria.

[[v11-16-33]]

^<<v11-16-33,33>>^ Acabe fez também um poste da deusa Aserá, de maneira que cometeu mais abominações para irritar o Senhor , Deus de Israel, do que todos os reis de Israel que vieram antes dele.

[[v11-16-34]]

^<<v11-16-34,34>>^ Em seus dias, Hiel, o betelita, edificou Jericó. Quando ele lançou os alicerces da cidade, morreu Abirão, seu filho primogênito; e, quando colocou os portões, morreu Segube, seu filho mais novo, segundo a palavra do Senhor , anunciada por meio de Josué, filho de Num.

'''

xref:011-1-reis/011-1-reis-015.adoc#v11-15-0[&#60; Capítulo Anterior] | <<v11-16-0,Topo>> | xref:011-1-reis/011-1-reis-017.adoc#v11-17-0[Próximo Capítulo &#62;]