include::./index.adoc[]

[[v11-6-0]]
=== 1 Reis, 6
// naa ?, NAA - Nova Almeida Atualizada

[[v11-6-1]]

^<<v11-6-1,1>>^ No ano quatrocentos e oitenta, depois que os filhos de Israel saíram do Egito, Salomão, no quarto ano do seu reinado sobre Israel, no mês de zive, que é o segundo mês, começou a edificar a Casa do Senhor .

[[v11-6-2]]

^<<v11-6-2,2>>^ O templo que o rei Salomão edificou ao Senhor  tinha vinte e sete metros de comprimento, nove de largura e treze e meio de altura.

[[v11-6-3]]

^<<v11-6-3,3>>^ O pórtico à entrada do templo media nove metros no sentido da largura do Lugar Santo, contra quatro e meio de fundo.

[[v11-6-4]]

^<<v11-6-4,4>>^ Para o templo, fez janelas de ripas fixas superpostas.

[[v11-6-5]]

^<<v11-6-5,5>>^ Contra a parede do templo, tanto do santuário como do Santo dos Santos, edificou andares ao redor e fez câmaras laterais ao redor.

[[v11-6-6]]

^<<v11-6-6,6>>^ O andar de baixo tinha dois metros e vinte e cinco de largura, o do meio, dois metros e setenta, e o terceiro, três metros e dez. Pela parte de fora do templo ele fez reentrâncias para que as vigas não fossem introduzidas nas paredes.

[[v11-6-7]]

^<<v11-6-7,7>>^ O templo foi construído com pedras já preparadas nas pedreiras, de maneira que, durante a construção, não se ouviu nenhum barulho de martelo, machado ou qualquer outro instrumento de ferro.

[[v11-6-8]]

^<<v11-6-8,8>>^ A porta da câmara do andar térreo ficava no lado sul do templo, e por uma escada se subia ao segundo andar e, deste, ao terceiro.

[[v11-6-9]]

^<<v11-6-9,9>>^ Assim Salomão construiu o templo e o rematou, cobrindo-o com um tabuado de cedro.

[[v11-6-10]]

^<<v11-6-10,10>>^ Os andares que edificou em volta do templo tinham dois metros e vinte e cinco de altura cada um, e estavam ligados ao templo por meio de vigas de cedro.

[[v11-6-11]]

^<<v11-6-11,11>>^ Então a palavra do Senhor  veio a Salomão, dizendo:

[[v11-6-12]]

^<<v11-6-12,12>>^ — Quanto a este templo que você está edificando, se você andar nos meus estatutos, e executar os meus juízos, e guardar todos os meus mandamentos, andando neles, cumprirei para com você a minha palavra, a qual falei a Davi, seu pai.

[[v11-6-13]]

^<<v11-6-13,13>>^ E habitarei no meio dos filhos de Israel e não abandonarei o meu povo.

[[v11-6-14]]

^<<v11-6-14,14>>^ Assim Salomão construiu o templo e o rematou.

[[v11-6-15]]

^<<v11-6-15,15>>^ Também revestiu as paredes do templo por dentro com tábuas de cedro. Desde o soalho até o teto, cobriu as paredes com madeira por dentro; e cobriu o piso do templo com tábuas de cipreste.

[[v11-6-16]]

^<<v11-6-16,16>>^ Revestiu também os nove metros dos fundos do templo com tábuas de cedro, desde o chão até o teto; e esse interior ele constituiu em santuário, a saber, o Santo dos Santos.

[[v11-6-17]]

^<<v11-6-17,17>>^ O Santo Lugar do templo media dezoito metros de comprimento.

[[v11-6-18]]

^<<v11-6-18,18>>^ O cedro do templo por dentro era enfeitado com entalhes de frutos e flores abertas. Tudo era cedro; não se via nenhuma pedra.

[[v11-6-19]]

^<<v11-6-19,19>>^ No mais interior do templo, preparou o Santo dos Santos para nele colocar a arca da aliança do Senhor .

[[v11-6-20]]

^<<v11-6-20,20>>^ O Santo dos Santos tinha nove metros de comprimento, nove de largura e nove de altura; cobriu-o de ouro puro. Cobriu também de ouro o altar de cedro.

[[v11-6-21]]

^<<v11-6-21,21>>^ Por dentro, Salomão revestiu o templo de ouro puro; e fez passar correntes de ouro por dentro do Santo dos Santos, que também havia revestido de ouro.

[[v11-6-22]]

^<<v11-6-22,22>>^ Assim revestiu de ouro todo o interior do templo, e também todo o altar que estava diante do Santo dos Santos.

[[v11-6-23]]

^<<v11-6-23,23>>^ No Santo dos Santos, Salomão fez dois querubins de madeira de oliveira, cada um com quatro metros e meio de altura.

[[v11-6-24]]

^<<v11-6-24,24>>^ Cada asa de um querubim media dois metros e vinte e cinco. Portanto, de uma a outra extremidade de suas asas havia quatro metros e meio.

[[v11-6-25]]

^<<v11-6-25,25>>^ Assim, o outro querubim também era de quatro metros e meio; ambos os querubins tinham a mesma medida e a mesma forma.

[[v11-6-26]]

^<<v11-6-26,26>>^ A altura de um querubim era de quatro metros e meio; e essa era também a altura do outro.

[[v11-6-27]]

^<<v11-6-27,27>>^ Ele pôs os querubins no mais interior do templo. Os querubins estavam de asas estendidas, de maneira que a asa de um tocava numa parede, e a asa do outro tocava na outra parede; e as suas asas no meio da sala tocavam uma na outra.

[[v11-6-28]]

^<<v11-6-28,28>>^ E cobriu de ouro os querubins.

[[v11-6-29]]

^<<v11-6-29,29>>^ Em todas as paredes ao redor do templo, tanto na parte mais interior como na parte exterior, Salomão mandou esculpir entalhes de querubins, palmeiras e flores abertas.

[[v11-6-30]]

^<<v11-6-30,30>>^ Também revestiu de ouro o soalho, tanto na parte mais interior do templo como na parte exterior.

[[v11-6-31]]

^<<v11-6-31,31>>^ Para a entrada do Santo dos Santos, fez uma porta dupla de madeira de oliveira; a verga com as ombreiras formavam uma porta pentagonal.

[[v11-6-32]]

^<<v11-6-32,32>>^ Assim, fabricou de madeira de oliveira duas portas e mandou esculpir nelas entalhes de querubins, de palmeiras e de flores abertas; a estas, como as palmeiras e os querubins, revestiu de ouro.

[[v11-6-33]]

^<<v11-6-33,33>>^ Para a entrada do Santo Lugar, fez batentes de madeira de oliveira; entrada quadrilateral,

[[v11-6-34]]

^<<v11-6-34,34>>^ cujas duas portas eram de madeira de cipreste; e as duas tábuas de cada porta eram dobradiças.

[[v11-6-35]]

^<<v11-6-35,35>>^ E mandou esculpir nelas entalhes de querubins, de palmeiras e de flores abertas e revestiu esses entalhes de ouro.

[[v11-6-36]]

^<<v11-6-36,36>>^ Também edificou o átrio interior de três ordens de pedras cortadas e de uma ordem de vigas de cedro.

[[v11-6-37]]

^<<v11-6-37,37>>^ No quarto ano, no mês de zive, foi lançado o fundamento da Casa do Senhor .

[[v11-6-38]]

^<<v11-6-38,38>>^ E, no décimo primeiro ano, no mês de bul, que é o oitavo mês, o templo foi concluído com todas as suas dependências, tal como devia ser. Salomão levou sete anos para edificá-lo.

'''

xref:011-1-reis/011-1-reis-005.adoc#v11-5-0[&#60; Capítulo Anterior] | <<v11-6-0,Topo>> | xref:011-1-reis/011-1-reis-007.adoc#v11-7-0[Próximo Capítulo &#62;]