include::./index.adoc[]

[[v11-12-0]]
=== 1 Reis, 12
// naa ?, NAA - Nova Almeida Atualizada

[[v11-12-1]]

^<<v11-12-1,1>>^ Roboão foi a Siquém, porque todo o Israel se havia reunido ali, para o fazer rei.

[[v11-12-2]]

^<<v11-12-2,2>>^ Jeroboão, filho de Nebate, que ainda estava no Egito, para onde havia fugido da presença do rei Salomão, ouviu isso e voltou do Egito.

[[v11-12-3]]

^<<v11-12-3,3>>^ Mandaram chamá-lo, e ele veio com toda a congregação de Israel a Roboão, para lhe dizer:

[[v11-12-4]]

^<<v11-12-4,4>>^ — O seu pai nos impôs um pesado jugo; alivie a dura servidão de seu pai e o pesado jugo que ele nos impôs, e nós o serviremos.

[[v11-12-5]]

^<<v11-12-5,5>>^ Roboão respondeu: — Vão embora e voltem daqui a três dias. E o povo se foi.

[[v11-12-6]]

^<<v11-12-6,6>>^ O rei Roboão foi pedir conselho aos anciãos que haviam estado na presença de Salomão, seu pai, quando este ainda vivia, dizendo: — Como vocês me aconselham a responder a este povo?

[[v11-12-7]]

^<<v11-12-7,7>>^ Eles disseram: — Se hoje o senhor se tornar servo deste povo e o servir, e, em resposta, falar boas palavras, eles se farão seus servos para sempre.

[[v11-12-8]]

^<<v11-12-8,8>>^ Mas Roboão desprezou o conselho que os anciãos lhe tinham dado e foi pedir conselho aos jovens que haviam crescido com ele e o serviam.

[[v11-12-9]]

^<<v11-12-9,9>>^ Ele perguntou: — O que vocês me aconselham? O que devo responder a este povo que me pediu para aliviar o jugo que o meu pai lhes impôs?

[[v11-12-10]]

^<<v11-12-10,10>>^ E os jovens que haviam crescido com ele responderam: — Diga o seguinte a este povo que se queixa do pesado jugo que o seu pai lhe impôs e que pede para que ele seja aliviado. Diga-lhe o seguinte: "O meu dedo mínimo é mais grosso do que a cintura do meu pai.

[[v11-12-11]]

^<<v11-12-11,11>>^ Assim que, se o meu pai lhes impôs um jugo pesado, eu o tornarei ainda mais pesado. Meu pai castigou vocês com açoites; eu vou castigá-los com escorpiões."

[[v11-12-12]]

^<<v11-12-12,12>>^ No terceiro dia, Jeroboão e todo o povo foram falar com Roboão, como o rei lhes havia ordenado, dizendo que voltassem em três dias.

[[v11-12-13]]

^<<v11-12-13,13>>^ O rei deu uma resposta dura ao povo, porque havia desprezado o conselho dos anciãos.

[[v11-12-14]]

^<<v11-12-14,14>>^ Preferiu seguir o conselho dos jovens, dizendo: — Meu pai lhes impôs um pesado jugo, mas eu o tornarei ainda mais pesado. Meu pai castigou vocês com açoites; eu vou castigá-los com escorpiões.

[[v11-12-15]]

^<<v11-12-15,15>>^ Assim o rei não deu ouvidos ao povo, porque esta reviravolta vinha do Senhor , para confirmar a palavra que o Senhor  tinha dito a Jeroboão, filho de Nebate, por meio de Aías, o silonita.

[[v11-12-16]]

^<<v11-12-16,16>>^ Quando todo o Israel viu que o rei não lhe dava ouvidos, reagiu, dizendo: — Que parte temos nós em Davi? Não temos herança no filho de Jessé! Às suas tendas, ó Israel! Cuide, agora, de sua casa, ó Davi! Então Israel se foi às suas tendas.

[[v11-12-17]]

^<<v11-12-17,17>>^ Quanto aos filhos de Israel, porém, que moravam nas cidades de Judá, sobre eles reinou Roboão.

[[v11-12-18]]

^<<v11-12-18,18>>^ Então o rei Roboão enviou Adonirão, superintendente dos que realizavam trabalhos forçados, porém todo o Israel o apedrejou, e ele morreu. Mas o rei Roboão conseguiu subir no seu carro e fugiu para Jerusalém.

[[v11-12-19]]

^<<v11-12-19,19>>^ Assim, Israel se mantém rebelado contra a casa de Davi até o dia de hoje.

[[v11-12-20]]

^<<v11-12-20,20>>^ Quando todo o Israel soube que Jeroboão tinha voltado, mandaram chamá-lo para a congregação e o fizeram rei sobre todo o Israel. Ninguém seguiu a casa de Davi, a não ser a tribo de Judá.

[[v11-12-21]]

^<<v11-12-21,21>>^ Quando Roboão chegou a Jerusalém, reuniu toda a casa de Judá e a tribo de Benjamim, cento e oitenta mil homens escolhidos, treinados para a guerra, para lutar contra a casa de Israel, a fim de restituir o reino a Roboão, filho de Salomão.

[[v11-12-22]]

^<<v11-12-22,22>>^ Porém a palavra de Deus veio a Semaías, homem de Deus, dizendo:

[[v11-12-23]]

^<<v11-12-23,23>>^ — Diga a Roboão, filho de Salomão, rei de Judá, e a toda a casa de Judá, e a Benjamim, e ao resto do povo:

[[v11-12-24]]

^<<v11-12-24,24>>^ Assim diz o Senhor : "Não subam, nem lutem contra os seus irmãos, os filhos de Israel. Que cada um volte para a sua casa, porque eu é que fiz isto." E eles obedeceram à palavra do Senhor  e voltaram, como o Senhor  lhes havia ordenado.

[[v11-12-25]]

^<<v11-12-25,25>>^ Jeroboão edificou Siquém, na região montanhosa de Efraim, e passou a residir ali; dali edificou Penuel.

[[v11-12-26]]

^<<v11-12-26,26>>^ Então ele pensou: "Agora o reino voltará para a casa de Davi.

[[v11-12-27]]

^<<v11-12-27,27>>^ Se este povo subir para fazer sacrifícios na Casa do Senhor , em Jerusalém, o coração deles se voltará para o senhor deles, para Roboão, rei de Judá. Eles me matarão e voltarão para ele, para o rei de Judá."

[[v11-12-28]]

^<<v11-12-28,28>>^ Por isso, depois de se aconselhar, o rei fez dois bezerros de ouro e disse ao povo: — Basta de subir a Jerusalém! Eis aqui os seus deuses, ó Israel, que tiraram vocês da terra do Egito!

[[v11-12-29]]

^<<v11-12-29,29>>^ Pôs um em Betel e o outro em Dã.

[[v11-12-30]]

^<<v11-12-30,30>>^ E isso se tornou em pecado, pois o povo ia até Dã, cada um para adorar o bezerro.

[[v11-12-31]]

^<<v11-12-31,31>>^ Jeroboão fez também santuários nos lugares altos e, dentre o povo, constituiu sacerdotes que não eram dos filhos de Levi.

[[v11-12-32]]

^<<v11-12-32,32>>^ Instituiu uma festa no oitavo mês, no dia décimo quinto do mês, igual à festa que se realizava em Judá, e ofereceu sacrifícios no altar. Fez o mesmo em Betel e ofereceu sacrifícios aos bezerros que havia feito. Também em Betel estabeleceu sacerdotes que serviam nos lugares altos que havia construído.

[[v11-12-33]]

^<<v11-12-33,33>>^ No décimo quinto dia do oitavo mês, escolhido a seu bel-prazer, ele subiu ao altar que havia construído em Betel e ordenou uma festa para os filhos de Israel; subiu para queimar incenso.

'''

xref:011-1-reis/011-1-reis-011.adoc#v11-11-0[&#60; Capítulo Anterior] | <<v11-12-0,Topo>> | xref:011-1-reis/011-1-reis-013.adoc#v11-13-0[Próximo Capítulo &#62;]