include::./index.adoc[]

[[v11-14-0]]
=== 1 Reis, 14
// naa ?, NAA - Nova Almeida Atualizada

[[v11-14-1]]

^<<v11-14-1,1>>^ Naquele tempo, Abias, filho de Jeroboão, adoeceu.

[[v11-14-2]]

^<<v11-14-2,2>>^ Então Jeroboão disse à sua mulher: — Levante-se, ponha um disfarce para que não saibam que você é a mulher de Jeroboão e vá até Siló. Eis que lá está o profeta Aías, que disse a meu respeito que eu seria rei sobre este povo.

[[v11-14-3]]

^<<v11-14-3,3>>^ Leve com você dez pães, alguns bolos e um pote de mel e vá falar com ele. Ele lhe dirá o que vai acontecer com este menino.

[[v11-14-4]]

^<<v11-14-4,4>>^ A mulher de Jeroboão fez o que lhe foi pedido: levantou-se, foi até Siló e entrou na casa de Aías. Este já não podia ver, porque os seus olhos já não se moviam, por causa da velhice.

[[v11-14-5]]

^<<v11-14-5,5>>^ Porém o Senhor  disse a Aías: — Eis que a mulher de Jeroboão está vindo para lhe perguntar a respeito do filho dela, que está doente. Assim e assim você deve falar com ela. Ao chegar, ela vai estar disfarçada.

[[v11-14-6]]

^<<v11-14-6,6>>^ Quando ela estava entrando pela porta, Aías ouviu o ruído de seus pés e disse: — Entre, mulher de Jeroboão. Por que você veio disfarçada? Estou encarregado de lhe dar más notícias.

[[v11-14-7]]

^<<v11-14-7,7>>^ Vá e diga a Jeroboão: Assim diz o Senhor , Deus de Israel: "Eu tirei você do meio do povo e fiz com que você se tornasse chefe sobre o meu povo de Israel.

[[v11-14-8]]

^<<v11-14-8,8>>^ Tirei o reino da casa de Davi e o entreguei a você. Mas você não foi como o meu servo Davi, que guardou os meus mandamentos e me seguiu de todo o coração, fazendo somente o que é reto aos meus olhos.

[[v11-14-9]]

^<<v11-14-9,9>>^ Pelo contrário, você fez o mal, pior do que todos os reis que vieram antes de você. Fez outros deuses e imagens de fundição, para provocar-me à ira, e me virou as costas.

[[v11-14-10]]

^<<v11-14-10,10>>^ Portanto, eis que trarei o mal sobre a casa de Jeroboão, e eliminarei de Jeroboão todo e qualquer indivíduo do sexo masculino, tanto o escravo como o livre, e lançarei fora os descendentes da casa de Jeroboão como se lança fora o esterco, até que, de todo, ela se acabe.

[[v11-14-11]]

^<<v11-14-11,11>>^ Se alguém da casa de Jeroboão morrer na cidade, os cães o comerão; e se alguém morrer no campo, as aves do céu o comerão, porque o Senhor  o disse."

[[v11-14-12]]

^<<v11-14-12,12>>^ — Quanto a você, mulher de Jeroboão, levante-se e volte para casa. Quando você puser os pés na cidade, o menino morrerá.

[[v11-14-13]]

^<<v11-14-13,13>>^ Todo o Israel o pranteará e o sepultará. Ele será o único da casa de Jeroboão que será sepultado, porque nele se achou alguma coisa boa para com o Senhor , Deus de Israel, na casa de Jeroboão.

[[v11-14-14]]

^<<v11-14-14,14>>^ O Senhor , porém, levantará para si um rei sobre Israel, que eliminará, no seu dia, a casa de Jeroboão. Quando será? Já está acontecendo.

[[v11-14-15]]

^<<v11-14-15,15>>^ O Senhor  ferirá Israel para que se agite como a cana se agita nas águas. Vai arrancar Israel desta boa terra que ele deu aos seus pais e o espalhará para além do Eufrates, porque fizeram postes da deusa Aserá, provocando o Senhor  à ira.

[[v11-14-16]]

^<<v11-14-16,16>>^ Entregará Israel por causa dos pecados que Jeroboão cometeu e pelos que fez Israel cometer.

[[v11-14-17]]

^<<v11-14-17,17>>^ Então a mulher de Jeroboão se levantou, foi e chegou a Tirza. Quando ela chegou à soleira da porta, o menino morreu.

[[v11-14-18]]

^<<v11-14-18,18>>^ Sepultaram-no, e todo o Israel o pranteou, segundo a palavra do Senhor , anunciada por meio do profeta Aías, seu servo.

[[v11-14-19]]

^<<v11-14-19,19>>^ Quanto aos demais atos de Jeroboão, como guerreou e como reinou, está tudo escrito no Livro da História dos Reis de Israel.

[[v11-14-20]]

^<<v11-14-20,20>>^ Foi de vinte e dois anos o tempo que Jeroboão reinou. Ele morreu, e Nadabe, seu filho, reinou em seu lugar.

[[v11-14-21]]

^<<v11-14-21,21>>^ Roboão, filho de Salomão, reinou em Judá. Ele tinha quarenta e um anos de idade quando começou a reinar e reinou dezessete anos em Jerusalém, na cidade que o Senhor  havia escolhido de todas as tribos de Israel, para estabelecer ali o seu nome. A mãe de Roboão se chamava Naamá, e era amonita.

[[v11-14-22]]

^<<v11-14-22,22>>^ Judá fez o que era mau aos olhos do Senhor , e, com os pecados que cometeu, despertou o seu ciúme, mais do que os seus pais haviam feito.

[[v11-14-23]]

^<<v11-14-23,23>>^ Porque também os de Judá edificaram altos, estátuas, colunas e postes da deusa Aserá sobre todas as colinas e debaixo de todas as árvores frondosas.

[[v11-14-24]]

^<<v11-14-24,24>>^ Havia também na terra prostitutos cultuais. Fizeram segundo todas as coisas abomináveis das nações que o Senhor  havia expulsado de diante dos filhos de Israel.

[[v11-14-25]]

^<<v11-14-25,25>>^ No quinto ano do reinado de Roboão, Sisaque, rei do Egito, atacou Jerusalém.

[[v11-14-26]]

^<<v11-14-26,26>>^ Levou embora os tesouros da Casa do Senhor  e os tesouros do palácio real. Levou tudo, inclusive todos os escudos de ouro que Salomão tinha feito.

[[v11-14-27]]

^<<v11-14-27,27>>^ Em lugar destes, o rei Roboão fez escudos de bronze e os entregou nas mãos dos capitães da guarda, que guardavam o portão do palácio real.

[[v11-14-28]]

^<<v11-14-28,28>>^ Toda vez que o rei entrava na Casa do Senhor , os da guarda usavam os escudos e depois os devolviam à câmara da guarda.

[[v11-14-29]]

^<<v11-14-29,29>>^ Quanto aos demais atos de Roboão e a tudo o que ele fez, não está tudo escrito no Livro da História dos Reis de Judá?

[[v11-14-30]]

^<<v11-14-30,30>>^ Roboão e Jeroboão estiveram sempre em guerra.

[[v11-14-31]]

^<<v11-14-31,31>>^ Roboão morreu e foi sepultado nos túmulos de seus pais, na Cidade de Davi. A mãe dele se chamava Naamá, e era amonita. E Abias, filho de Roboão, reinou em seu lugar.

'''

xref:011-1-reis/011-1-reis-013.adoc#v11-13-0[&#60; Capítulo Anterior] | <<v11-14-0,Topo>> | xref:011-1-reis/011-1-reis-015.adoc#v11-15-0[Próximo Capítulo &#62;]