include::./index.adoc[]

[[v42-12-0]]
=== Lucas, 12
// naa ?, NAA - Nova Almeida Atualizada

[[v42-12-1]]

^<<v42-12-1,1>>^ Visto que milhares de pessoas se aglomeraram, a ponto de se atropelarem umas às outras, Jesus começou a dizer, antes de tudo, aos seus discípulos: — Cuidado com o fermento dos fariseus, que é a hipocrisia.

[[v42-12-2]]

^<<v42-12-2,2>>^ Não há nada encoberto que não venha a ser revelado, nem oculto que não venha a ser conhecido.

[[v42-12-3]]

^<<v42-12-3,3>>^ Porque tudo o que vocês disseram às escuras será ouvido em plena luz; e o que disseram ao pé do ouvido no interior da casa será proclamado dos telhados.

[[v42-12-4]]

^<<v42-12-4,4>>^ — Digo a vocês, meus amigos: não temam os que matam o corpo e, depois disso, nada mais podem fazer.

[[v42-12-5]]

^<<v42-12-5,5>>^ Eu, porém, vou mostrar a quem vocês devem temer: temam aquele que, depois de matar, tem poder para lançar no inferno. Sim, digo que a esse vocês devem temer.

[[v42-12-6]]

^<<v42-12-6,6>>^ — Não se vendem cinco pardais por duas moedinhas? Entretanto, Deus não se esquece de nenhum deles.

[[v42-12-7]]

^<<v42-12-7,7>>^ Até os cabelos da cabeça de vocês estão todos contados. Não temam! Vocês valem bem mais do que muitos pardais.

[[v42-12-8]]

^<<v42-12-8,8>>^ — Digo mais a vocês: todo aquele que me confessar diante dos outros, também o Filho do Homem o confessará diante dos anjos de Deus;

[[v42-12-9]]

^<<v42-12-9,9>>^ mas o que me negar diante das pessoas será negado diante dos anjos de Deus.

[[v42-12-10]]

^<<v42-12-10,10>>^ Todo aquele que disser uma palavra contra o Filho do Homem, isso lhe será perdoado; mas, para o que blasfemar contra o Espírito Santo, não haverá perdão.

[[v42-12-11]]

^<<v42-12-11,11>>^ — Quando levarem vocês às sinagogas ou à presença de governadores e autoridades, não se preocupem quanto à maneira como irão responder, nem quanto às coisas que tiverem de falar.

[[v42-12-12]]

^<<v42-12-12,12>>^ Porque o Espírito Santo lhes ensinará, naquela mesma hora, as coisas que vocês devem dizer.

[[v42-12-13]]

^<<v42-12-13,13>>^ Nesse ponto, um homem que estava no meio da multidão disse a Jesus: — Mestre, diga a meu irmão que reparta comigo a herança.

[[v42-12-14]]

^<<v42-12-14,14>>^ Mas Jesus lhe respondeu: — Homem, quem me nomeou juiz ou repartidor entre vocês?

[[v42-12-15]]

^<<v42-12-15,15>>^ Então lhes recomendou: — Tenham cuidado e não se deixem dominar por qualquer tipo de avareza, porque a vida de uma pessoa não consiste na abundância dos bens que ela tem.

[[v42-12-16]]

^<<v42-12-16,16>>^ E Jesus lhes contou ainda uma parábola, dizendo: — O campo de um homem rico produziu com abundância.

[[v42-12-17]]

^<<v42-12-17,17>>^ Então ele começou a pensar: "Que farei, pois não tenho onde armazenar a minha colheita?"

[[v42-12-18]]

^<<v42-12-18,18>>^ Até que disse: "Já sei! Destruirei os meus celeiros, construirei outros maiores e aí armazenarei todo o meu produto e todos os meus bens.

[[v42-12-19]]

^<<v42-12-19,19>>^ Então direi à minha alma: ‘Você tem em depósito muitos bens para muitos anos; descanse, coma, beba e aproveite a vida.’"

[[v42-12-20]]

^<<v42-12-20,20>>^ Mas Deus lhe disse: "Louco! Esta noite lhe pedirão a sua alma; e o que você tem preparado, para quem será?"

[[v42-12-21]]

^<<v42-12-21,21>>^ — Assim é o que ajunta tesouros para si mesmo, mas não é rico para com Deus.

[[v42-12-22]]

^<<v42-12-22,22>>^ A seguir, Jesus se dirigiu aos seus discípulos, dizendo: — Por isso, digo a vocês: não se preocupem com a sua vida, quanto ao que irão comer, nem com o corpo, quanto ao que irão vestir.

[[v42-12-23]]

^<<v42-12-23,23>>^ Porque a vida é mais do que o alimento, e o corpo, mais do que as roupas.

[[v42-12-24]]

^<<v42-12-24,24>>^ Observem os corvos, que não semeiam, não colhem, não têm despensa nem celeiros; contudo, Deus os sustenta. Vocês valem muito mais do que as aves!

[[v42-12-25]]

^<<v42-12-25,25>>^ Quem de vocês, por mais que se preocupe, pode acrescentar um côvado ao curso da sua vida?

[[v42-12-26]]

^<<v42-12-26,26>>^ Portanto, se não podem fazer nada quanto às coisas mínimas, por que se preocupam com as outras?

[[v42-12-27]]

^<<v42-12-27,27>>^ Observem como crescem os lírios: eles não trabalham, nem fiam. Eu, porém, afirmo a vocês que nem Salomão, em toda a sua glória, se vestiu como qualquer deles.

[[v42-12-28]]

^<<v42-12-28,28>>^ Ora, se Deus veste assim a erva que hoje está no campo e amanhã é lançada no forno, muito mais fará por vocês, homens de pequena fé!

[[v42-12-29]]

^<<v42-12-29,29>>^ Portanto, não fiquem perguntando o que irão comer ou beber e não fiquem preocupados com isso.

[[v42-12-30]]

^<<v42-12-30,30>>^ Porque os gentios de todo o mundo é que procuram estas coisas; mas o Pai de vocês sabe que vocês precisam delas.

[[v42-12-31]]

^<<v42-12-31,31>>^ Busquem, antes de tudo, o seu Reino, e estas coisas lhes serão acrescentadas.

[[v42-12-32]]

^<<v42-12-32,32>>^ — Não tenha medo, ó pequenino rebanho; porque o Pai de vocês se agradou em dar-lhes o seu Reino.

[[v42-12-33]]

^<<v42-12-33,33>>^ Vendam os seus bens e deem esmola; façam para vocês mesmos bolsas que não desgastem, tesouro inesgotável nos céus, onde o ladrão não chega, nem a traça corrói,

[[v42-12-34]]

^<<v42-12-34,34>>^ porque, onde estiver o tesouro de vocês, aí estará também o seu coração.

[[v42-12-35]]

^<<v42-12-35,35>>^ — Estejam preparados, com o corpo cingido e as lamparinas acesas.

[[v42-12-36]]

^<<v42-12-36,36>>^ Façam como os homens que esperam pelo seu senhor, ao voltar ele das festas de casamento; para que logo abram a porta, quando vier e bater.

[[v42-12-37]]

^<<v42-12-37,37>>^ Bem-aventurados aqueles servos a quem o senhor, quando vier, encontrar vigilantes. Em verdade lhes digo que ele há de cingir-se, dar-lhes lugar à mesa e, aproximando-se, os servirá.

[[v42-12-38]]

^<<v42-12-38,38>>^ Quer ele venha à meia-noite ou de madrugada, bem-aventurados serão eles, se os encontrar vigilantes.

[[v42-12-39]]

^<<v42-12-39,39>>^ Porém, considerem isto: se o pai de família soubesse a que hora viria o ladrão, não deixaria que a sua casa fosse arrombada.

[[v42-12-40]]

^<<v42-12-40,40>>^ Estejam também vocês preparados, porque o Filho do Homem virá à hora em que vocês menos esperam.

[[v42-12-41]]

^<<v42-12-41,41>>^ Então Pedro perguntou: — Senhor, esta parábola é só para nós ou também para todos?

[[v42-12-42]]

^<<v42-12-42,42>>^ O Senhor respondeu: — Quem é, pois, o mordomo fiel e prudente, a quem o senhor deixará encarregado dos demais servos da casa, para lhes dar o sustento no devido tempo?

[[v42-12-43]]

^<<v42-12-43,43>>^ Bem-aventurado aquele servo a quem seu senhor, quando vier, achar fazendo assim.

[[v42-12-44]]

^<<v42-12-44,44>>^ Em verdade lhes digo que lhe confiará todos os seus bens.

[[v42-12-45]]

^<<v42-12-45,45>>^ Mas o que acontecerá se aquele servo disser consigo mesmo: "Meu senhor demora para vir", e começar a espancar os empregados e as empregadas, a comer, a beber e a embriagar-se?

[[v42-12-46]]

^<<v42-12-46,46>>^ Virá o senhor daquele servo, em dia em que não o espera e em hora que não sabe, e irá aplicar-lhe um castigo severo, condenando-o com os infiéis.

[[v42-12-47]]

^<<v42-12-47,47>>^ — Aquele servo que conheceu a vontade de seu senhor e não se aprontou, nem fez segundo a sua vontade, será punido com muitos açoites.

[[v42-12-48]]

^<<v42-12-48,48>>^ Aquele, porém, que não soube a vontade do seu senhor e fez coisas dignas de reprovação levará poucos açoites. Mas àquele a quem muito foi dado, muito lhe será exigido; e àquele a quem muito se confia, muito mais lhe pedirão.

[[v42-12-49]]

^<<v42-12-49,49>>^ — Eu vim para lançar fogo sobre a terra, e bem que eu gostaria que já estivesse aceso.

[[v42-12-50]]

^<<v42-12-50,50>>^ Mas existe um batismo pelo qual tenho de passar, e como me angustio até que o mesmo se cumpra!

[[v42-12-51]]

^<<v42-12-51,51>>^ Vocês pensam que vim para dar paz à terra? Eu afirmo a vocês que não; pelo contrário, vim para trazer divisão.

[[v42-12-52]]

^<<v42-12-52,52>>^ Porque, daqui em diante, estarão cinco divididos numa casa: três contra dois e dois contra três.

[[v42-12-53]]

^<<v42-12-53,53>>^ Estarão divididos: pai contra filho, filho contra pai; mãe contra filha, filha contra mãe; sogra contra nora e nora contra sogra.

[[v42-12-54]]

^<<v42-12-54,54>>^ Jesus disse ainda às multidões: — Quando vocês veem uma nuvem subindo no oeste, logo dizem que vai chover, e assim acontece.

[[v42-12-55]]

^<<v42-12-55,55>>^ E, quando notam que sopra o vento sul, dizem que fará calor, e assim acontece.

[[v42-12-56]]

^<<v42-12-56,56>>^ Hipócritas! Vocês sabem interpretar a aparência da terra e do céu, mas não sabem discernir esta época?

[[v42-12-57]]

^<<v42-12-57,57>>^ — E por que não julgam também por vocês mesmos o que é justo?

[[v42-12-58]]

^<<v42-12-58,58>>^ Quando você for com o seu adversário ao magistrado, faça o possível para chegar a um acordo com ele enquanto vocês estão a caminho, para não acontecer que ele arraste você ao juiz, o juiz entregue você ao oficial de justiça e o oficial de justiça ponha você na prisão.

[[v42-12-59]]

^<<v42-12-59,59>>^ Digo-lhe que você não sairá dali enquanto não pagar o último centavo.

'''

xref:042-lucas/042-lucas-011.adoc#v42-11-0[&#60; Capítulo Anterior] | <<v42-12-0,Topo>> | xref:042-lucas/042-lucas-013.adoc#v42-13-0[Próximo Capítulo &#62;]