include::./index.adoc[]

[[v42-4-0]]
=== Lucas, 4
// naa ?, NAA - Nova Almeida Atualizada

[[v42-4-1]]

^<<v42-4-1,1>>^ Jesus, cheio do Espírito Santo, voltou do Jordão e foi guiado pelo mesmo Espírito, no deserto,

[[v42-4-2]]

^<<v42-4-2,2>>^ durante quarenta dias, sendo tentado pelo diabo. Nada comeu naqueles dias, ao fim dos quais teve fome.

[[v42-4-3]]

^<<v42-4-3,3>>^ Então o diabo disse a Jesus: — Se você é o Filho de Deus, mande que esta pedra se transforme em pão.

[[v42-4-4]]

^<<v42-4-4,4>>^ Mas Jesus lhe respondeu: — Está escrito: "O ser humano não viverá só de pão."

[[v42-4-5]]

^<<v42-4-5,5>>^ Então o diabo o levou para um lugar mais alto e num instante lhe mostrou todos os reinos do mundo.

[[v42-4-6]]

^<<v42-4-6,6>>^ E disse: — Eu lhe darei todo este poder e a glória destes reinos, porque isso me foi entregue, e posso dar a quem eu quiser.

[[v42-4-7]]

^<<v42-4-7,7>>^ Portanto, se você me adorar, tudo isso será seu.

[[v42-4-8]]

^<<v42-4-8,8>>^ Mas Jesus respondeu: — Está escrito: "Adore o Senhor, seu Deus, e preste culto somente a ele."

[[v42-4-9]]

^<<v42-4-9,9>>^ Então o diabo levou Jesus a Jerusalém, colocou-o sobre o pináculo do templo e disse: — Se você é o Filho de Deus, jogue-se daqui,

[[v42-4-10]]

^<<v42-4-10,10>>^ porque está escrito: "Aos seus anjos ele dará ordens a seu respeito, para que o guardem."

[[v42-4-11]]

^<<v42-4-11,11>>^ E: "Eles o sustentarão nas suas mãos, para que você não tropece em alguma pedra."

[[v42-4-12]]

^<<v42-4-12,12>>^ Jesus respondeu ao diabo: — Também foi dito: "Não ponha à prova o Senhor, seu Deus."

[[v42-4-13]]

^<<v42-4-13,13>>^ Tendo concluído todas as tentações, o diabo afastou-se de Jesus, até momento oportuno.

[[v42-4-14]]

^<<v42-4-14,14>>^ Então Jesus, no poder do Espírito, voltou para a Galileia, e a sua fama correu por toda aquela região.

[[v42-4-15]]

^<<v42-4-15,15>>^ E ensinava nas sinagogas, sendo elogiado por todos.

[[v42-4-16]]

^<<v42-4-16,16>>^ Jesus foi para Nazaré, onde havia sido criado. Num sábado, entrou na sinagoga, segundo o seu costume, e levantou-se para ler.

[[v42-4-17]]

^<<v42-4-17,17>>^ Então lhe deram o livro do profeta Isaías. E, abrindo o livro, achou o lugar onde está escrito:

[[v42-4-18]]

^<<v42-4-18,18>>^ "O Espírito do Senhor está sobre mim, porque ele me ungiu para evangelizar os pobres; enviou-me para proclamar libertação aos cativos e restauração da vista aos cegos, para pôr em liberdade os oprimidos,

[[v42-4-19]]

^<<v42-4-19,19>>^ e proclamar o ano aceitável do Senhor."

[[v42-4-20]]

^<<v42-4-20,20>>^ Tendo fechado o livro, Jesus o devolveu ao assistente e sentou-se. Todos na sinagoga tinham os olhos fixos nele.

[[v42-4-21]]

^<<v42-4-21,21>>^ Então Jesus começou a dizer: — Hoje se cumpriu a Escritura que vocês acabam de ouvir.

[[v42-4-22]]

^<<v42-4-22,22>>^ Todos davam testemunho dele e se maravilhavam das palavras cheias de graça que lhe saíam dos lábios. E perguntavam: — Não é este o filho de José?

[[v42-4-23]]

^<<v42-4-23,23>>^ Então Jesus disse: — Sem dúvida, vocês citarão para mim o provérbio: "Médico, cure-se a si mesmo." Dirão: "Tudo o que ouvimos que você fez em Cafarnaum, faça-o também aqui na sua terra."

[[v42-4-24]]

^<<v42-4-24,24>>^ E Jesus prosseguiu: — De fato, afirmo a vocês que nenhum profeta é bem recebido na sua própria terra.

[[v42-4-25]]

^<<v42-4-25,25>>^ Na verdade lhes digo que havia muitas viúvas em Israel no tempo de Elias, quando o céu se fechou por três anos e seis meses, reinando grande fome em toda a terra,

[[v42-4-26]]

^<<v42-4-26,26>>^ e Elias não foi enviado a nenhuma delas, a não ser a uma viúva de Sarepta de Sidom.

[[v42-4-27]]

^<<v42-4-27,27>>^ Havia também muitos leprosos em Israel nos dias do profeta Eliseu, e nenhum deles foi purificado, a não ser Naamã, o sírio.

[[v42-4-28]]

^<<v42-4-28,28>>^ Todos na sinagoga, ouvindo estas coisas, se encheram de ira.

[[v42-4-29]]

^<<v42-4-29,29>>^ E, levantando-se, expulsaram Jesus da cidade e o levaram até o alto do monte sobre o qual a cidade estava edificada, para que, de lá, pudessem atirá-lo abaixo.

[[v42-4-30]]

^<<v42-4-30,30>>^ Jesus, porém, passando pelo meio deles, foi embora.

[[v42-4-31]]

^<<v42-4-31,31>>^ E Jesus foi a Cafarnaum, cidade da Galileia, e os ensinava no sábado.

[[v42-4-32]]

^<<v42-4-32,32>>^ E maravilhavam-se com a sua doutrina, porque a sua palavra era com autoridade.

[[v42-4-33]]

^<<v42-4-33,33>>^ E apareceu na sinagoga um homem possuído de um espírito de demônio imundo, o qual gritou em alta voz:

[[v42-4-34]]

^<<v42-4-34,34>>^ — Ah! O que você quer conosco, Jesus Nazareno? Você veio para nos destruir? Sei muito bem quem você é: o Santo de Deus!

[[v42-4-35]]

^<<v42-4-35,35>>^ Mas Jesus o repreendeu, dizendo: — Cale-se e saia desse homem. O demônio, depois de o ter jogado no chão no meio de todos, saiu daquele homem sem lhe fazer mal.

[[v42-4-36]]

^<<v42-4-36,36>>^ Todos ficaram admirados e comentavam entre si: — Que palavra é esta? Pois, com autoridade e poder, ele ordena aos espíritos imundos, e eles saem.

[[v42-4-37]]

^<<v42-4-37,37>>^ E a fama de Jesus se espalhava por todos os lugares daquela região.

[[v42-4-38]]

^<<v42-4-38,38>>^ Deixando a sinagoga, Jesus foi para a casa de Simão. A sogra de Simão estava doente, com febre muito alta, e pediram a Jesus em favor dela.

[[v42-4-39]]

^<<v42-4-39,39>>^ E inclinando-se para ela, Jesus repreendeu a febre, e esta a deixou. E imediatamente ela se levantou e passou a servi-los.

[[v42-4-40]]

^<<v42-4-40,40>>^ Ao pôr do sol, todos os que tinham enfermos, com diferentes tipos de doença, os trouxeram a Jesus. E ele os curava, impondo as mãos sobre cada um deles.

[[v42-4-41]]

^<<v42-4-41,41>>^ Também de muitos saíam demônios, gritando e dizendo: — Você é o Filho de Deus! Ele, porém, os repreendia para que não falassem, pois sabiam que ele era o Cristo.

[[v42-4-42]]

^<<v42-4-42,42>>^ Quando amanheceu, Jesus saiu e foi para um lugar deserto. As multidões o procuravam, foram até junto dele e não queriam deixar que ele fosse embora.

[[v42-4-43]]

^<<v42-4-43,43>>^ Jesus, porém, lhes disse: — É necessário que eu anuncie o evangelho do Reino de Deus também nas outras cidades, pois é para isso que fui enviado.

[[v42-4-44]]

^<<v42-4-44,44>>^ E pregava nas sinagogas da Judeia.

'''

xref:042-lucas/042-lucas-003.adoc#v42-3-0[&#60; Capítulo Anterior] | <<v42-4-0,Topo>> | xref:042-lucas/042-lucas-005.adoc#v42-5-0[Próximo Capítulo &#62;]