include::./index.adoc[]

[[v42-5-0]]
=== Lucas, 5
// naa ?, NAA - Nova Almeida Atualizada

[[v42-5-1]]

^<<v42-5-1,1>>^ Aconteceu que Jesus estava junto ao lago de Genesaré, e a multidão o apertava para ouvir a palavra de Deus.

[[v42-5-2]]

^<<v42-5-2,2>>^ Então ele viu dois barcos junto à praia do lago. Os pescadores tinham desembarcado e estavam lavando as redes.

[[v42-5-3]]

^<<v42-5-3,3>>^ Entrando num dos barcos, que era o de Simão, Jesus pediu-lhe que o afastasse um pouco da praia; e, assentando-se, do barco ensinava as multidões.

[[v42-5-4]]

^<<v42-5-4,4>>^ Quando acabou de falar, Jesus disse a Simão: — Leve o barco para o lugar mais fundo do lago e então lancem as redes de vocês para pescar.

[[v42-5-5]]

^<<v42-5-5,5>>^ Em resposta, Simão disse: — Mestre, havendo trabalhado toda a noite, nada apanhamos; mas, sob esta sua palavra, lançarei as redes.

[[v42-5-6]]

^<<v42-5-6,6>>^ Fazendo isso, apanharam grande quantidade de peixes; e as redes deles começaram a se romper.

[[v42-5-7]]

^<<v42-5-7,7>>^ Então fizeram sinais aos companheiros do outro barco, para que fossem ajudá-los. E foram e encheram ambos os barcos, a ponto de quase afundarem.

[[v42-5-8]]

^<<v42-5-8,8>>^ Vendo isto, Simão Pedro prostrou-se aos pés de Jesus, dizendo: — Senhor, afaste-se de mim, porque sou pecador.

[[v42-5-9]]

^<<v42-5-9,9>>^ Pois, à vista da pesca que fizeram, a admiração se apoderou dele e de todos os seus companheiros,

[[v42-5-10]]

^<<v42-5-10,10>>^ bem como de Tiago e João, filhos de Zebedeu, que eram seus sócios. Então Jesus disse a Simão: — Não tenha medo! De agora em diante você será pescador de gente.

[[v42-5-11]]

^<<v42-5-11,11>>^ E, arrastando eles os barcos para a praia, deixando tudo, o seguiram.

[[v42-5-12]]

^<<v42-5-12,12>>^ Aconteceu que, estando Jesus numa das cidades, um homem coberto de lepra veio à sua presença. Quando ele viu Jesus, prostrou-se com o rosto em terra e pediu: — Senhor, se quiser, pode purificar-me.

[[v42-5-13]]

^<<v42-5-13,13>>^ E Jesus, estendendo a mão, tocou nele, dizendo: — Quero, sim. Fique limpo! E, no mesmo instante, a lepra daquele homem desapareceu.

[[v42-5-14]]

^<<v42-5-14,14>>^ Jesus ordenou-lhe que não contasse isso a ninguém. E acrescentou: — Mas vá, apresente-se ao sacerdote e ofereça pela purificação o sacrifício que Moisés ordenou, para servir de testemunho ao povo.

[[v42-5-15]]

^<<v42-5-15,15>>^ Porém o que se dizia a respeito de Jesus se espalhava cada vez mais, e grandes multidões afluíam para o ouvir e para serem curadas de suas enfermidades.

[[v42-5-16]]

^<<v42-5-16,16>>^ Jesus, porém, se retirava para lugares solitários e orava.

[[v42-5-17]]

^<<v42-5-17,17>>^ E aconteceu que, num daqueles dias, Jesus estava ensinando, e achavam-se ali assentados fariseus e mestres da Lei, vindos de todas as aldeias da Galileia, da Judeia e de Jerusalém. E o poder do Senhor estava com ele para curar.

[[v42-5-18]]

^<<v42-5-18,18>>^ Vieram, então, alguns homens trazendo um paralítico deitado num leito. Eles procuravam levá-lo para dentro e colocá-lo diante de Jesus.

[[v42-5-19]]

^<<v42-5-19,19>>^ E, não encontrando uma forma de fazer isso por causa da multidão, subiram ao telhado e, por entre as telhas, desceram o paralítico no seu leito, deixando-o no meio das pessoas, diante de Jesus.

[[v42-5-20]]

^<<v42-5-20,20>>^ Vendo-lhes a fé, Jesus disse ao paralítico: — Homem, os seus pecados estão perdoados.

[[v42-5-21]]

^<<v42-5-21,21>>^ E os escribas e fariseus começaram a pensar: — Quem é este que diz blasfêmias? Quem pode perdoar pecados, a não ser um, que é Deus?

[[v42-5-22]]

^<<v42-5-22,22>>^ Jesus, porém, conhecendo os pensamentos deles, disse-lhes: — O que vocês estão pensando em seu coração?

[[v42-5-23]]

^<<v42-5-23,23>>^ O que é mais fácil? Dizer: "Os seus pecados estão perdoados", ou dizer: "Levante-se e ande"?

[[v42-5-24]]

^<<v42-5-24,24>>^ Mas isto é para que vocês saibam que o Filho do Homem tem autoridade sobre a terra para perdoar pecados. E disse ao paralítico: — Eu digo a você: Levante-se, pegue o seu leito e vá para casa.

[[v42-5-25]]

^<<v42-5-25,25>>^ E imediatamente ele se levantou diante de todos e, pegando o leito em que até então estava deitado, voltou para casa, glorificando a Deus.

[[v42-5-26]]

^<<v42-5-26,26>>^ Todos ficaram muito admirados, davam glória a Deus e, cheios de temor, diziam: — Hoje vimos coisas extraordinárias!

[[v42-5-27]]

^<<v42-5-27,27>>^ Depois disso, Jesus saiu e viu um publicano, chamado Levi, sentado na coletoria. E lhe disse: — Siga-me!

[[v42-5-28]]

^<<v42-5-28,28>>^ Ele se levantou e, deixando tudo, o seguiu.

[[v42-5-29]]

^<<v42-5-29,29>>^ Então Levi lhe ofereceu um grande banquete em sua casa; e era grande o número de publicanos e outras pessoas que estavam com eles à mesa.

[[v42-5-30]]

^<<v42-5-30,30>>^ Os fariseus e seus escribas murmuravam contra os discípulos de Jesus, perguntando: — Por que vocês comem e bebem com os publicanos e pecadores?

[[v42-5-31]]

^<<v42-5-31,31>>^ Jesus tomou a palavra e disse: — Os sãos não precisam de médico, e sim os doentes.

[[v42-5-32]]

^<<v42-5-32,32>>^ Não vim chamar justos, e sim pecadores, ao arrependimento.

[[v42-5-33]]

^<<v42-5-33,33>>^ Então eles disseram a Jesus: — Os discípulos de João frequentemente jejuam e fazem orações, e os discípulos dos fariseus fazem o mesmo; mas os seus discípulos comem e bebem.

[[v42-5-34]]

^<<v42-5-34,34>>^ Jesus, porém, lhes disse: — Será que vocês podem fazer com que os convidados para o casamento jejuem enquanto o noivo está com eles?

[[v42-5-35]]

^<<v42-5-35,35>>^ No entanto, virão dias em que o noivo lhes será tirado, e então, naqueles dias, eles vão jejuar.

[[v42-5-36]]

^<<v42-5-36,36>>^ Também lhes contou uma parábola: — Ninguém tira um pedaço de uma roupa nova para colocar sobre roupa velha; pois, se o fizer, rasgará a roupa nova, e, além disso, o remendo da roupa nova não combinará com a roupa velha.

[[v42-5-37]]

^<<v42-5-37,37>>^ E ninguém põe vinho novo em odres velhos, porque, se fizer isso, o vinho novo romperá os odres, o vinho se derramará, e os odres se estragarão.

[[v42-5-38]]

^<<v42-5-38,38>>^ Pelo contrário, vinho novo deve ser posto em odres novos.

[[v42-5-39]]

^<<v42-5-39,39>>^ E ninguém, tendo bebido o vinho velho, prefere o novo, porque diz: "O velho é excelente."

'''

xref:042-lucas/042-lucas-004.adoc#v42-4-0[&#60; Capítulo Anterior] | <<v42-5-0,Topo>> | xref:042-lucas/042-lucas-006.adoc#v42-6-0[Próximo Capítulo &#62;]