include::./index.adoc[]

[[v42-17-0]]
=== Lucas, 17
// naa ?, NAA - Nova Almeida Atualizada

[[v42-17-1]]

^<<v42-17-1,1>>^ Jesus disse aos seus discípulos: — É inevitável que existam pedras de tropeço, mas ai de quem é responsável por elas!

[[v42-17-2]]

^<<v42-17-2,2>>^ Seria melhor para esse que uma pedra de moinho fosse pendurada ao seu pescoço e fosse atirado no mar do que fazer tropeçar um destes pequeninos.

[[v42-17-3]]

^<<v42-17-3,3>>^ — Tenham cuidado. Se o seu irmão pecar, repreenda-o; se ele se arrepender, perdoe-lhe.

[[v42-17-4]]

^<<v42-17-4,4>>^ Se pecar contra você sete vezes num dia e sete vezes vier para lhe dizer: "Estou arrependido", perdoe-lhe.

[[v42-17-5]]

^<<v42-17-5,5>>^ Então os apóstolos disseram ao Senhor: — Aumente-nos a fé.

[[v42-17-6]]

^<<v42-17-6,6>>^ Ao que o Senhor respondeu: — Se vocês tivessem fé como um grão de mostarda, diriam a esta amoreira: "Arranque-se e transplante-se no mar." E ela obedeceria.

[[v42-17-7]]

^<<v42-17-7,7>>^ — Qual de vocês, tendo um servo ocupado na lavoura ou em guardar o gado, lhe dirá quando ele voltar do campo: "Venha agora mesmo e sente-se à mesa"?

[[v42-17-8]]

^<<v42-17-8,8>>^ Não é verdade que, ao contrário, lhe dirá: "Prepare o meu jantar. Apronte-se e sirva-me enquanto eu como e bebo. Depois, você pode comer e beber"?

[[v42-17-9]]

^<<v42-17-9,9>>^ Será que ele terá de agradecer ao servo por ter feito o que lhe havia ordenado?

[[v42-17-10]]

^<<v42-17-10,10>>^ Assim também vocês, depois de terem feito tudo o que lhes foi ordenado, digam: "Somos servos inúteis, porque fizemos apenas o que devíamos fazer."

[[v42-17-11]]

^<<v42-17-11,11>>^ De caminho para Jerusalém, Jesus passava pelo meio de Samaria e da Galileia.

[[v42-17-12]]

^<<v42-17-12,12>>^ Ao entrar numa aldeia, saíram-lhe ao encontro dez leprosos,

[[v42-17-13]]

^<<v42-17-13,13>>^ que ficaram de longe e gritaram: — Jesus, Mestre, tenha compaixão de nós!

[[v42-17-14]]

^<<v42-17-14,14>>^ Ao vê-los, Jesus disse: — Vão e apresentem-se aos sacerdotes. Aconteceu que, indo eles, foram purificados.

[[v42-17-15]]

^<<v42-17-15,15>>^ Um dos dez, vendo que estava curado, voltou dando glória a Deus em alta voz

[[v42-17-16]]

^<<v42-17-16,16>>^ e prostrou-se com o rosto em terra aos pés de Jesus, agradecendo-lhe. E este era samaritano.

[[v42-17-17]]

^<<v42-17-17,17>>^ Então Jesus perguntou: — Não eram dez os que foram curados? Onde estão os nove?

[[v42-17-18]]

^<<v42-17-18,18>>^ Não se achou quem voltasse para dar glória a Deus, a não ser este estrangeiro?

[[v42-17-19]]

^<<v42-17-19,19>>^ E lhe disse: — Levante-se e vá; a sua fé salvou você.

[[v42-17-20]]

^<<v42-17-20,20>>^ Indagado pelos fariseus sobre quando viria o Reino de Deus, Jesus lhes respondeu: — O Reino de Deus não vem com visível aparência.

[[v42-17-21]]

^<<v42-17-21,21>>^ Nem dirão: "Ele está aqui!" Ou: "Lá está ele!" Porque o Reino de Deus está entre vocês.

[[v42-17-22]]

^<<v42-17-22,22>>^ A seguir, Jesus disse aos seus discípulos: — Virá o tempo em que vocês desejarão ver um dos dias do Filho do Homem, mas não verão.

[[v42-17-23]]

^<<v42-17-23,23>>^ E dirão a vocês: "Ele está aqui!" Ou: "Lá está ele!" Não saiam nem sigam essa gente.

[[v42-17-24]]

^<<v42-17-24,24>>^ Porque assim como o relâmpago, que resplandece e brilha de uma extremidade do céu até a outra, assim será, no seu dia, o Filho do Homem.

[[v42-17-25]]

^<<v42-17-25,25>>^ Mas é necessário que primeiro ele padeça muitas coisas e seja rejeitado por esta geração.

[[v42-17-26]]

^<<v42-17-26,26>>^ Assim como foi nos dias de Noé, será também nos dias do Filho do Homem:

[[v42-17-27]]

^<<v42-17-27,27>>^ comiam, bebiam, casavam e davam-se em casamento, até o dia em que Noé entrou na arca, veio o dilúvio e destruiu todos.

[[v42-17-28]]

^<<v42-17-28,28>>^ O mesmo aconteceu nos dias de Ló: comiam, bebiam, compravam, vendiam, plantavam e edificavam;

[[v42-17-29]]

^<<v42-17-29,29>>^ mas, no dia em que Ló saiu de Sodoma, choveu do céu fogo e enxofre e destruiu todos.

[[v42-17-30]]

^<<v42-17-30,30>>^ Assim será no dia em que o Filho do Homem se manifestar.

[[v42-17-31]]

^<<v42-17-31,31>>^ — Naquele dia, quem estiver no terraço e tiver os seus bens em casa não desça para tirá-los; e, de igual modo, quem estiver no campo não volte para trás.

[[v42-17-32]]

^<<v42-17-32,32>>^ Lembrem-se da mulher de Ló.

[[v42-17-33]]

^<<v42-17-33,33>>^ Quem tentar preservar a sua vida a perderá; e quem a perder, esse a salvará.

[[v42-17-34]]

^<<v42-17-34,34>>^ Digo a vocês que, naquela noite, duas pessoas estarão numa cama: uma será levada, e a outra será deixada.

[[v42-17-35]]

^<<v42-17-35,35>>^ Duas mulheres estarão juntas moendo trigo: uma será tomada, e a outra será deixada.

[[v42-17-36]]

^<<v42-17-36,36>>^ &#91;Dois estarão no campo: um será tomado, e o outro será deixado.&#93;

[[v42-17-37]]

^<<v42-17-37,37>>^ Então perguntaram a Jesus: — Onde será isso, Senhor? Ele respondeu: — Onde estiver o corpo, aí se ajuntarão também os abutres.

'''

xref:042-lucas/042-lucas-016.adoc#v42-16-0[&#60; Capítulo Anterior] | <<v42-17-0,Topo>> | xref:042-lucas/042-lucas-018.adoc#v42-18-0[Próximo Capítulo &#62;]