include::./index.adoc[]

[[v42-21-0]]
=== Lucas, 21
// naa ?, NAA - Nova Almeida Atualizada

[[v42-21-1]]

^<<v42-21-1,1>>^ Jesus estava observando e viu os ricos que lançavam seu dinheiro na caixa de ofertas.

[[v42-21-2]]

^<<v42-21-2,2>>^ Viu também certa viúva pobre lançar ali duas pequenas moedas.

[[v42-21-3]]

^<<v42-21-3,3>>^ Então Jesus disse: — Em verdade lhes digo que esta viúva pobre deu mais do que todos.

[[v42-21-4]]

^<<v42-21-4,4>>^ Porque todos esses deram como oferta daquilo que lhes sobrava; esta, porém, da sua pobreza deu tudo o que possuía, todo o seu sustento.

[[v42-21-5]]

^<<v42-21-5,5>>^ Alguns falavam a respeito do templo, como estava ornado de belas pedras e de dádivas.

[[v42-21-6]]

^<<v42-21-6,6>>^ Então Jesus disse: — Vocês estão vendo estas coisas? Virão dias em que não ficará pedra sobre pedra que não seja derrubada.

[[v42-21-7]]

^<<v42-21-7,7>>^ Perguntaram a Jesus: — Mestre, quando será isto? E que sinal haverá quando estas coisas estiverem para acontecer?

[[v42-21-8]]

^<<v42-21-8,8>>^ Jesus respondeu: — Tenham cuidado para não serem enganados. Porque muitos virão em meu nome, dizendo: "Sou eu!" E também: "Chegou a hora!" Porém não vão atrás deles.

[[v42-21-9]]

^<<v42-21-9,9>>^ Quando vocês ouvirem falar de guerras e revoluções, não fiquem assustados; pois é necessário que primeiro aconteçam estas coisas, mas o fim não será logo.

[[v42-21-10]]

^<<v42-21-10,10>>^ Então Jesus lhes disse: — Nação se levantará contra nação, e reino, contra reino.

[[v42-21-11]]

^<<v42-21-11,11>>^ Haverá grandes terremotos, epidemias e fome em vários lugares, coisas espantosas e também grandes sinais vindos do céu.

[[v42-21-12]]

^<<v42-21-12,12>>^ Antes, porém, de todas estas coisas, vocês serão presos e perseguidos. Vocês serão entregues às sinagogas e lançados nas prisões; serão levados à presença de reis e de governadores, por causa do meu nome.

[[v42-21-13]]

^<<v42-21-13,13>>^ Isto acontecerá para que vocês deem testemunho.

[[v42-21-14]]

^<<v42-21-14,14>>^ Tomem, pois, a decisão de não se preocupar com o que irão responder,

[[v42-21-15]]

^<<v42-21-15,15>>^ porque eu lhes darei palavras e sabedoria a que não poderão resistir nem contradizer todos os que se opuserem a vocês.

[[v42-21-16]]

^<<v42-21-16,16>>^ E vocês serão entregues até por seus próprios pais, irmãos, parentes e amigos; e eles matarão alguns de vocês.

[[v42-21-17]]

^<<v42-21-17,17>>^ Todos odiarão vocês por causa do meu nome.

[[v42-21-18]]

^<<v42-21-18,18>>^ Mas não se perderá um só fio de cabelo da cabeça de vocês.

[[v42-21-19]]

^<<v42-21-19,19>>^ É pela perseverança que vocês ganharão a sua alma.

[[v42-21-20]]

^<<v42-21-20,20>>^ — Quando, porém, vocês virem Jerusalém sitiada de exércitos, saibam que está próxima a sua devastação.

[[v42-21-21]]

^<<v42-21-21,21>>^ Então os que estiverem na Judeia fujam para os montes; os que se encontrarem dentro da cidade saiam dela; e os que estiverem nos campos não entrem na cidade.

[[v42-21-22]]

^<<v42-21-22,22>>^ Porque esses dias são de vingança, para se cumprir tudo o que está escrito.

[[v42-21-23]]

^<<v42-21-23,23>>^ Ai das que estiverem grávidas e das que amamentarem naqueles dias! Porque haverá grande aflição na terra e ira contra este povo.

[[v42-21-24]]

^<<v42-21-24,24>>^ Cairão a fio de espada e serão levados cativos para todas as nações; e, até que os tempos dos gentios se completem, Jerusalém será pisada por eles.

[[v42-21-25]]

^<<v42-21-25,25>>^ — Haverá sinais no sol, na lua e nas estrelas; sobre a terra, angústia entre as nações em perplexidade por causa do bramido do mar e das ondas.

[[v42-21-26]]

^<<v42-21-26,26>>^ Haverá pessoas que desmaiarão de terror e pela expectativa das coisas que sobrevirão ao mundo, pois os poderes dos céus serão abalados.

[[v42-21-27]]

^<<v42-21-27,27>>^ Então verão o Filho do Homem vindo numa nuvem, com poder e grande glória.

[[v42-21-28]]

^<<v42-21-28,28>>^ Ora, quando estas coisas começarem a acontecer, levantem-se e fiquem de cabeça erguida, porque a redenção de vocês se aproxima.

[[v42-21-29]]

^<<v42-21-29,29>>^ Jesus ainda lhes contou uma parábola, dizendo: — Olhem para a figueira e todas as árvores.

[[v42-21-30]]

^<<v42-21-30,30>>^ Quando veem que começam a brotar, vocês mesmos sabem que o verão está próximo.

[[v42-21-31]]

^<<v42-21-31,31>>^ Assim também, quando virem acontecer essas coisas, saibam que está próximo o Reino de Deus.

[[v42-21-32]]

^<<v42-21-32,32>>^ Em verdade lhes digo que não passará esta geração sem que tudo isto aconteça.

[[v42-21-33]]

^<<v42-21-33,33>>^ Passará o céu e a terra, porém as minhas palavras não passarão.

[[v42-21-34]]

^<<v42-21-34,34>>^ — Tenham cuidado para não acontecer que o coração de vocês fique sobrecarregado com as consequências da orgia, da embriaguez e das preocupações deste mundo, e para que aquele dia não venha sobre vocês repentinamente,

[[v42-21-35]]

^<<v42-21-35,35>>^ como uma armadilha. Pois sobrevirá a todos os que vivem sobre a face de toda a terra.

[[v42-21-36]]

^<<v42-21-36,36>>^ Portanto, vigiem o tempo todo, orando, para que vocês possam escapar de todas essas coisas que têm de acontecer e para que possam estar em pé na presença do Filho do Homem.

[[v42-21-37]]

^<<v42-21-37,37>>^ Jesus ensinava todos os dias no templo, mas à noite saía e ficava no monte chamado das Oliveiras.

[[v42-21-38]]

^<<v42-21-38,38>>^ E todo o povo madrugava para ir ao encontro dele no templo, a fim de ouvi-lo.

'''

xref:042-lucas/042-lucas-020.adoc#v42-20-0[&#60; Capítulo Anterior] | <<v42-21-0,Topo>> | xref:042-lucas/042-lucas-022.adoc#v42-22-0[Próximo Capítulo &#62;]