include::./index.adoc[]

[[v42-19-0]]
=== Lucas, 19
// naa ?, NAA - Nova Almeida Atualizada

[[v42-19-1]]

^<<v42-19-1,1>>^ Entrando em Jericó, Jesus atravessava a cidade.

[[v42-19-2]]

^<<v42-19-2,2>>^ Eis que um homem rico, chamado Zaqueu, chefe dos publicanos,

[[v42-19-3]]

^<<v42-19-3,3>>^ procurava ver quem era Jesus, mas não podia, por causa da multidão, por ser ele de pequena estatura.

[[v42-19-4]]

^<<v42-19-4,4>>^ Então, correndo adiante, subiu num sicômoro a fim de ver Jesus, porque ele havia de passar por ali.

[[v42-19-5]]

^<<v42-19-5,5>>^ Quando Jesus chegou àquele lugar, olhando para cima, disse: — Zaqueu, desça depressa, porque hoje preciso ficar na sua casa.

[[v42-19-6]]

^<<v42-19-6,6>>^ Zaqueu desceu depressa e o recebeu com alegria.

[[v42-19-7]]

^<<v42-19-7,7>>^ Todos os que viram isto murmuravam, dizendo que Jesus tinha se hospedado com um homem pecador.

[[v42-19-8]]

^<<v42-19-8,8>>^ Zaqueu, por sua vez, se levantou e disse ao Senhor: — Senhor, vou dar a metade dos meus bens aos pobres. E, se roubei alguma coisa de alguém, vou restituir quatro vezes mais.

[[v42-19-9]]

^<<v42-19-9,9>>^ Então Jesus lhe disse: — Hoje houve salvação nesta casa, pois também este é filho de Abraão.

[[v42-19-10]]

^<<v42-19-10,10>>^ Porque o Filho do Homem veio buscar e salvar o perdido.

[[v42-19-11]]

^<<v42-19-11,11>>^ Ouvindo eles estas coisas, Jesus contou uma parábola, visto estar perto de Jerusalém e lhes parecer que o Reino de Deus havia de manifestar-se imediatamente.

[[v42-19-12]]

^<<v42-19-12,12>>^ Por isso, Jesus disse: — Certo homem nobre partiu para uma terra distante, a fim de tomar posse de um reino e voltar.

[[v42-19-13]]

^<<v42-19-13,13>>^ Chamou dez dos seus servos, confiou-lhes dez minas e disse-lhes: "Negociem até que eu volte."

[[v42-19-14]]

^<<v42-19-14,14>>^ Mas os seus concidadãos o odiavam e enviaram após ele uma embaixada, dizendo: "Não queremos que este reine sobre nós."

[[v42-19-15]]

^<<v42-19-15,15>>^ — Quando ele voltou, depois de ter tomado posse do reino, mandou chamar os servos a quem tinha dado o dinheiro, a fim de saber quanto tinham conseguido ganhar em seus negócios.

[[v42-19-16]]

^<<v42-19-16,16>>^ — O primeiro se apresentou e disse: "Senhor, a sua mina rendeu dez."

[[v42-19-17]]

^<<v42-19-17,17>>^ O senhor lhe disse: "Muito bem, servo bom! E porque você foi fiel no pouco, terá autoridade sobre dez cidades."

[[v42-19-18]]

^<<v42-19-18,18>>^ — O segundo servo veio e disse: "Senhor, a sua mina rendeu cinco."

[[v42-19-19]]

^<<v42-19-19,19>>^ A este o senhor disse: "Você terá autoridade sobre cinco cidades."

[[v42-19-20]]

^<<v42-19-20,20>>^ — Então veio outro servo, dizendo: "Senhor, aqui está a sua mina, que eu guardei embrulhada num lenço.

[[v42-19-21]]

^<<v42-19-21,21>>^ Porque tive medo do senhor, que é homem rigoroso. O senhor retira o que não depositou e colhe o que não semeou."

[[v42-19-22]]

^<<v42-19-22,22>>^ Mas o senhor respondeu: "Servo mau, eu o julgarei usando as suas próprias palavras. Você sabia que eu sou homem rigoroso, que retiro o que não depositei e colho o que não semeei.

[[v42-19-23]]

^<<v42-19-23,23>>^ Por que você não pôs o meu dinheiro no banco? E, então, na minha vinda, eu o receberia com juros."

[[v42-19-24]]

^<<v42-19-24,24>>^ — E disse aos que estavam ali: "Tirem dele a mina e deem ao que tem as dez."

[[v42-19-25]]

^<<v42-19-25,25>>^ Eles ponderaram: "Senhor, ele já tem dez."

[[v42-19-26]]

^<<v42-19-26,26>>^ Ao que o senhor respondeu: "Pois eu declaro a vocês que a todo o que tem será dado ainda mais; mas ao que não tem, até o que tem lhe será tirado.

[[v42-19-27]]

^<<v42-19-27,27>>^ Mas quanto a esses meus inimigos, que não quiseram que eu reinasse sobre eles, tragam-nos aqui e os matem na minha presença."

[[v42-19-28]]

^<<v42-19-28,28>>^ E, depois de dizer isto, Jesus prosseguia a sua viagem para Jerusalém.

[[v42-19-29]]

^<<v42-19-29,29>>^ E aconteceu que, ao aproximar-se de Betfagé e de Betânia, junto ao monte das Oliveiras, Jesus enviou dois dos seus discípulos,

[[v42-19-30]]

^<<v42-19-30,30>>^ dizendo-lhes: — Vão até a aldeia que fica ali adiante e, ao entrar, encontrarão preso um jumentinho, o qual ainda ninguém montou; desprendam o jumentinho e tragam aqui.

[[v42-19-31]]

^<<v42-19-31,31>>^ Se alguém perguntar: "Por que o estão desprendendo?", respondam assim: "Porque o Senhor precisa dele."

[[v42-19-32]]

^<<v42-19-32,32>>^ E, indo os que foram mandados, acharam tudo conforme Jesus lhes tinha dito.

[[v42-19-33]]

^<<v42-19-33,33>>^ Quando eles estavam soltando o jumentinho, os donos do animal disseram: — Por que estão desprendendo o jumentinho?

[[v42-19-34]]

^<<v42-19-34,34>>^ Eles responderam: — Porque o Senhor precisa dele.

[[v42-19-35]]

^<<v42-19-35,35>>^ Então trouxeram o jumentinho até Jesus e, pondo as suas capas sobre o animal, ajudaram Jesus a montar.

[[v42-19-36]]

^<<v42-19-36,36>>^ À medida que Jesus avançava, as pessoas estendiam as suas capas no caminho.

[[v42-19-37]]

^<<v42-19-37,37>>^ E, quando Jesus se aproximava da descida do monte das Oliveiras, toda a multidão dos discípulos começou, com muita alegria, a louvar a Deus em alta voz, por todos os milagres que tinham visto.

[[v42-19-38]]

^<<v42-19-38,38>>^ Diziam: "Bendito é o Rei que vem em nome do Senhor! Paz no céu e glória nas maiores alturas!"

[[v42-19-39]]

^<<v42-19-39,39>>^ Alguns dos fariseus lhe disseram em meio à multidão: — Mestre, repreenda os seus discípulos!

[[v42-19-40]]

^<<v42-19-40,40>>^ Mas Jesus respondeu: — Eu afirmo a vocês que, se eles se calarem, as próprias pedras clamarão.

[[v42-19-41]]

^<<v42-19-41,41>>^ Quando Jesus ia chegando a Jerusalém, vendo a cidade, chorou por ela,

[[v42-19-42]]

^<<v42-19-42,42>>^ dizendo: — Ah! Se você soubesse, ainda hoje, o que é preciso para conseguir a paz! Mas isto está agora oculto aos seus olhos.

[[v42-19-43]]

^<<v42-19-43,43>>^ Pois virão dias em que os seus inimigos cercarão você de trincheiras e apertarão o cerco por todos os lados;

[[v42-19-44]]

^<<v42-19-44,44>>^ e vão arrasar você e matar todos os seus moradores. Não deixarão pedra sobre pedra, porque você não reconheceu o tempo em que Deus veio visitá-la.

[[v42-19-45]]

^<<v42-19-45,45>>^ Depois, entrando no templo, Jesus começou a expulsar os que ali vendiam,

[[v42-19-46]]

^<<v42-19-46,46>>^ dizendo-lhes: — Está escrito: "A minha casa será ‘Casa de Oração’." Mas vocês fizeram dela um covil de salteadores.

[[v42-19-47]]

^<<v42-19-47,47>>^ Diariamente, Jesus ensinava no templo. Os principais sacerdotes, os escribas e os maiorais do povo procuravam tirar-lhe a vida,

[[v42-19-48]]

^<<v42-19-48,48>>^ mas não achavam uma forma de fazer isso, porque todo o povo, ao ouvi-lo, era cativado por ele.

'''

xref:042-lucas/042-lucas-018.adoc#v42-18-0[&#60; Capítulo Anterior] | <<v42-19-0,Topo>> | xref:042-lucas/042-lucas-020.adoc#v42-20-0[Próximo Capítulo &#62;]