include::./index.adoc[]

[[v42-3-0]]
=== Lucas, 3
// naa ?, NAA - Nova Almeida Atualizada

[[v42-3-1]]

^<<v42-3-1,1>>^ No décimo quinto ano do reinado de Tibério César, sendo Pôncio Pilatos governador da Judeia, Herodes, tetrarca da Galileia, seu irmão Filipe, tetrarca da região da Itureia e Traconites, e Lisânias, tetrarca de Abilene,

[[v42-3-2]]

^<<v42-3-2,2>>^ sendo sumos sacerdotes Anás e Caifás, a palavra de Deus veio a João, filho de Zacarias, no deserto.

[[v42-3-3]]

^<<v42-3-3,3>>^ Ele percorreu toda a região nas imediações do rio Jordão, pregando batismo de arrependimento para remissão de pecados,

[[v42-3-4]]

^<<v42-3-4,4>>^ conforme está escrito no livro das palavras do profeta Isaías: "Voz do que clama no deserto: Preparem o caminho do Senhor, endireitem as suas veredas.

[[v42-3-5]]

^<<v42-3-5,5>>^ Todos os vales serão aterrados, e todos os montes e colinas serão nivelados; os caminhos tortuosos serão retificados, e as estradas irregulares serão aplanadas;

[[v42-3-6]]

^<<v42-3-6,6>>^ e toda a humanidade verá a salvação que vem de Deus."

[[v42-3-7]]

^<<v42-3-7,7>>^ João dizia às multidões que saíam para ser batizadas: — Raça de víboras! Quem deu a entender que vocês podem fugir da ira vindoura?

[[v42-3-8]]

^<<v42-3-8,8>>^ Produzam frutos dignos de arrependimento! E não comecem a dizer uns aos outros: "Temos por pai Abraão", porque eu afirmo a vocês que Deus pode fazer com que destas pedras surjam filhos a Abraão.

[[v42-3-9]]

^<<v42-3-9,9>>^ E também o machado já está posto à raiz das árvores. Portanto, toda árvore que não produz bom fruto é cortada e lançada ao fogo.

[[v42-3-10]]

^<<v42-3-10,10>>^ Então as multidões perguntaram a João: — O que é que devemos fazer?

[[v42-3-11]]

^<<v42-3-11,11>>^ Ele respondeu: — Quem tiver duas túnicas reparta com quem não tem, e quem tiver comida faça o mesmo.

[[v42-3-12]]

^<<v42-3-12,12>>^ Também alguns publicanos chegaram para ser batizados e perguntaram a João: — Mestre, o que devemos fazer?

[[v42-3-13]]

^<<v42-3-13,13>>^ Ele respondeu: — Não cobrem mais do que o estipulado.

[[v42-3-14]]

^<<v42-3-14,14>>^ Também soldados lhe perguntaram: — E nós, o que devemos fazer? E ele lhes disse: — Não sejam prepotentes, não façam denúncias falsas e contentem-se com o salário que vocês recebem.

[[v42-3-15]]

^<<v42-3-15,15>>^ Estando o povo na expectativa, e pensando todos em seu íntimo a respeito de João, se por acaso ele não seria o próprio Cristo,

[[v42-3-16]]

^<<v42-3-16,16>>^ João tratou de explicar a todos: — Eu, na verdade, batizo vocês com água, mas vem aquele que é mais poderoso do que eu, do qual não sou digno de desamarrar as correias das suas sandálias; ele os batizará com o Espírito Santo e com fogo.

[[v42-3-17]]

^<<v42-3-17,17>>^ Ele tem a pá em suas mãos, para limpar a sua eira e recolher o trigo no seu celeiro; porém queimará a palha num fogo que nunca se apaga.

[[v42-3-18]]

^<<v42-3-18,18>>^ E assim, com muitas outras exortações, João anunciava o evangelho ao povo.

[[v42-3-19]]

^<<v42-3-19,19>>^ Mas Herodes, o tetrarca, sendo repreendido por João por causa de Herodias, mulher de seu irmão, e por todas as maldades que o mesmo Herodes havia feito,

[[v42-3-20]]

^<<v42-3-20,20>>^ acrescentou a todas as outras ainda esta: mandou prender João.

[[v42-3-21]]

^<<v42-3-21,21>>^ Ao ser todo o povo batizado, Jesus também foi batizado. E aconteceu que, enquanto ele orava, o céu se abriu,

[[v42-3-22]]

^<<v42-3-22,22>>^ o Espírito Santo desceu sobre ele em forma corpórea como pomba, e do céu veio uma voz, que dizia: — Você é o meu Filho amado; em você me agrado.

[[v42-3-23]]

^<<v42-3-23,23>>^ Ora, Jesus tinha cerca de trinta anos quando começou o seu ministério. Era, conforme se pensava, filho de José, filho de Eli,

[[v42-3-24]]

^<<v42-3-24,24>>^ filho de Matate, filho de Levi, filho de Melqui, filho de Janai, filho de José,

[[v42-3-25]]

^<<v42-3-25,25>>^ filho de Matatias, filho de Amós, filho de Naum, filho de Esli, filho de Nagai,

[[v42-3-26]]

^<<v42-3-26,26>>^ filho de Maate, filho de Matatias, filho de Semei, filho de José, filho de Jodá,

[[v42-3-27]]

^<<v42-3-27,27>>^ filho de Joanã, filho de Resa, filho de Zorobabel, filho de Salatiel, filho de Neri,

[[v42-3-28]]

^<<v42-3-28,28>>^ filho de Melqui, filho de Adi, filho de Cosã, filho de Elmadã, filho de Er,

[[v42-3-29]]

^<<v42-3-29,29>>^ filho de Josué, filho de Eliézer, filho de Jorim, filho de Matate, filho de Levi,

[[v42-3-30]]

^<<v42-3-30,30>>^ filho de Simeão, filho de Judá, filho de José, filho de Jonã, filho de Eliaquim,

[[v42-3-31]]

^<<v42-3-31,31>>^ filho de Meleá, filho de Mená, filho de Matatá, filho de Natã, filho de Davi,

[[v42-3-32]]

^<<v42-3-32,32>>^ filho de Jessé, filho de Obede, filho de Boaz, filho de Salá, filho de Naassom,

[[v42-3-33]]

^<<v42-3-33,33>>^ filho de Aminadabe, filho de Admim, filho de Arni, filho de Esrom, filho de Perez, filho de Judá,

[[v42-3-34]]

^<<v42-3-34,34>>^ filho de Jacó, filho de Isaque, filho de Abraão, filho de Tera, filho de Naor,

[[v42-3-35]]

^<<v42-3-35,35>>^ filho de Serugue, filho de Ragaú, filho de Faleque, filho de Éber, filho de Salá,

[[v42-3-36]]

^<<v42-3-36,36>>^ filho de Cainã, filho de Arfaxade, filho de Sem, filho de Noé, filho de Lameque,

[[v42-3-37]]

^<<v42-3-37,37>>^ filho de Metusalém, filho de Enoque, filho de Jarede, filho de Maalalel, filho de Cainã,

[[v42-3-38]]

^<<v42-3-38,38>>^ filho de Enos, filho de Sete, filho de Adão, filho de Deus.

'''

xref:042-lucas/042-lucas-002.adoc#v42-2-0[&#60; Capítulo Anterior] | <<v42-3-0,Topo>> | xref:042-lucas/042-lucas-004.adoc#v42-4-0[Próximo Capítulo &#62;]