include::./index.adoc[]

[[v42-8-0]]
=== Lucas, 8
// naa ?, NAA - Nova Almeida Atualizada

[[v42-8-1]]

^<<v42-8-1,1>>^ Aconteceu, depois disso, que Jesus andava de cidade em cidade e de aldeia em aldeia, pregando e anunciando o evangelho do Reino de Deus. Iam com ele os doze discípulos,

[[v42-8-2]]

^<<v42-8-2,2>>^ e também algumas mulheres que haviam sido curadas de espíritos malignos e de enfermidades: Maria, chamada Madalena, da qual saíram sete demônios;

[[v42-8-3]]

^<<v42-8-3,3>>^ Joana, mulher de Cuza, procurador de Herodes; Suzana e muitas outras, as quais, com os seus bens, ajudavam Jesus e os seus discípulos.

[[v42-8-4]]

^<<v42-8-4,4>>^ Quando uma grande multidão se reuniu e pessoas de todas as cidades vieram até Jesus, ele disse por parábola:

[[v42-8-5]]

^<<v42-8-5,5>>^ — Um semeador saiu a semear. E, ao semear, uma parte caiu à beira do caminho, foi pisada, e as aves do céu a comeram.

[[v42-8-6]]

^<<v42-8-6,6>>^ Outra parte caiu sobre a pedra e, tendo crescido, secou por falta de umidade.

[[v42-8-7]]

^<<v42-8-7,7>>^ Outra caiu no meio dos espinhos; e os espinhos, ao crescerem com ela, a sufocaram.

[[v42-8-8]]

^<<v42-8-8,8>>^ Outra, enfim, caiu em boa terra; cresceu e produziu a cem por um. Dizendo isto, Jesus clamou: — Quem tem ouvidos para ouvir, ouça.

[[v42-8-9]]

^<<v42-8-9,9>>^ Então os discípulos de Jesus lhe perguntaram o que significava essa parábola.

[[v42-8-10]]

^<<v42-8-10,10>>^ Jesus respondeu: — A vocês é dado conhecer os mistérios do Reino de Deus, mas aos demais fala-se por parábolas, para que, vendo, não vejam e, ouvindo, não entendam.

[[v42-8-11]]

^<<v42-8-11,11>>^ — Este é o significado da parábola: a semente é a palavra de Deus.

[[v42-8-12]]

^<<v42-8-12,12>>^ Os que estão à beira do caminho são os que a ouviram; depois vem o diabo e tira-lhes a palavra do coração, para não acontecer que, crendo, sejam salvos.

[[v42-8-13]]

^<<v42-8-13,13>>^ Os que estão sobre a pedra são os que, ouvindo a palavra, a recebem com alegria. Estes não têm raiz, creem apenas por algum tempo e, na hora da provação, se desviam.

[[v42-8-14]]

^<<v42-8-14,14>>^ A parte que caiu entre espinhos, estes são os que ouviram e, no decorrer dos dias, foram sufocados com as preocupações, as riquezas e os prazeres desta vida; os seus frutos não chegam a amadurecer.

[[v42-8-15]]

^<<v42-8-15,15>>^ A parte que caiu na terra boa, estes são os que, tendo ouvido de bom e reto coração, retêm a palavra; estes frutificam com perseverança.

[[v42-8-16]]

^<<v42-8-16,16>>^ — Ninguém, depois de acender uma lamparina, a cobre com um vaso ou a põe debaixo de uma cama; pelo contrário, coloca-a num lugar em que ilumina bem, a fim de que os que entram vejam a luz.

[[v42-8-17]]

^<<v42-8-17,17>>^ Não há nada oculto que não venha a ser manifesto, nem escondido que não venha a ser conhecido e revelado.

[[v42-8-18]]

^<<v42-8-18,18>>^ Portanto, vejam como vocês ouvem. Porque ao que tiver, mais será dado; e ao que não tiver, até aquilo que julga ter lhe será tirado.

[[v42-8-19]]

^<<v42-8-19,19>>^ A mãe e os irmãos de Jesus chegaram até onde ele estava, mas não podiam aproximar-se por causa da multidão.

[[v42-8-20]]

^<<v42-8-20,20>>^ E lhe comunicaram: — A sua mãe e os seus irmãos estão lá fora e querem vê-lo.

[[v42-8-21]]

^<<v42-8-21,21>>^ Jesus, porém, lhes respondeu: — Minha mãe e meus irmãos são aqueles que ouvem a palavra de Deus e a praticam.

[[v42-8-22]]

^<<v42-8-22,22>>^ Aconteceu que, num daqueles dias, Jesus entrou num barco em companhia dos seus discípulos e lhes disse: — Vamos passar para a outra margem do lago. E partiram.

[[v42-8-23]]

^<<v42-8-23,23>>^ Enquanto navegavam, ele adormeceu. E sobreveio uma tempestade de vento no lago, e eles corriam perigo.

[[v42-8-24]]

^<<v42-8-24,24>>^ Chegando-se a Jesus, os discípulos o despertaram, dizendo: — Mestre, Mestre, estamos perecendo! Levantando-se, Jesus repreendeu o vento e a fúria da água. Tudo cessou e ficou bem calmo.

[[v42-8-25]]

^<<v42-8-25,25>>^ Então Jesus lhes perguntou: — Vocês não têm fé? Eles, possuídos de temor e admiração, diziam uns aos outros: — Quem é este que até manda nos ventos e nas ondas, e lhe obedecem?

[[v42-8-26]]

^<<v42-8-26,26>>^ Então rumaram para a terra dos gerasenos, que fica de frente para a Galileia.

[[v42-8-27]]

^<<v42-8-27,27>>^ Logo que Jesus desembarcou, veio da cidade ao seu encontro um homem possuído de demônios que, havia muito, não se vestia, nem habitava em casa alguma, porém vivia nos túmulos.

[[v42-8-28]]

^<<v42-8-28,28>>^ Quando ele viu Jesus, prostrou-se diante dele, dizendo com voz forte: — O que você quer comigo, Jesus, Filho do Deus Altíssimo? Peço-lhe que não me atormente.

[[v42-8-29]]

^<<v42-8-29,29>>^ Porque Jesus havia ordenado ao espírito imundo que saísse do homem, pois muitas vezes se havia apoderado dele. E, embora procurassem conservá-lo preso com cadeias e correntes, despedaçava tudo e era impelido pelo demônio para o deserto.

[[v42-8-30]]

^<<v42-8-30,30>>^ Jesus perguntou a ele: — Qual é o seu nome? Ele respondeu: — Legião. Isto porque muitos demônios tinham entrado nele.

[[v42-8-31]]

^<<v42-8-31,31>>^ Estes pediram a Jesus que não os mandasse para o abismo.

[[v42-8-32]]

^<<v42-8-32,32>>^ Ora, uma grande manada de porcos estava pastando ali no monte. E os demônios pediram a Jesus que os deixasse entrar naqueles porcos. E Jesus o permitiu.

[[v42-8-33]]

^<<v42-8-33,33>>^ Tendo os demônios saído do homem, entraram nos porcos, e a manada precipitou-se despenhadeiro abaixo, para dentro do lago, e se afogou.

[[v42-8-34]]

^<<v42-8-34,34>>^ Vendo o que tinha acontecido, os que tratavam dos porcos fugiram e foram anunciá-lo na cidade e pelos campos.

[[v42-8-35]]

^<<v42-8-35,35>>^ Então o povo saiu para ver o que tinha acontecido. Aproximando-se de Jesus, encontraram o homem de quem tinham saído os demônios, vestido, em perfeito juízo, sentado aos pés de Jesus; e temeram.

[[v42-8-36]]

^<<v42-8-36,36>>^ E algumas pessoas que tinham presenciado os fatos contaram-lhes também como o endemoniado tinha sido salvo.

[[v42-8-37]]

^<<v42-8-37,37>>^ Todo o povo da terra dos gerasenos pediu a Jesus que se retirasse, pois ficaram com muito medo. E Jesus, entrando de novo no barco, voltou.

[[v42-8-38]]

^<<v42-8-38,38>>^ O homem de quem tinham saído os demônios lhe pediu que o deixasse estar com ele. Jesus, porém, o despediu, dizendo:

[[v42-8-39]]

^<<v42-8-39,39>>^ — Volte para a sua casa e conte tudo o que Deus fez por você. Então ele foi, proclamando por toda a cidade o que Jesus lhe tinha feito.

[[v42-8-40]]

^<<v42-8-40,40>>^ Quando Jesus voltou, a multidão o recebeu com alegria, porque todos o estavam esperando.

[[v42-8-41]]

^<<v42-8-41,41>>^ Eis que veio um homem chamado Jairo, que era chefe da sinagoga, e, prostrando-se aos pés de Jesus, suplicou-lhe que fosse até a sua casa.

[[v42-8-42]]

^<<v42-8-42,42>>^ Pois tinha uma filha única de uns doze anos, que estava morrendo. Enquanto Jesus caminhava, as multidões o apertavam.

[[v42-8-43]]

^<<v42-8-43,43>>^ Certa mulher que, havia doze anos, vinha sofrendo de uma hemorragia e que havia gastado todos os seus bens com os médicos, sem que ninguém a pudesse curar,

[[v42-8-44]]

^<<v42-8-44,44>>^ veio por trás de Jesus e tocou na borda da capa dele. E logo a hemorragia dela estancou.

[[v42-8-45]]

^<<v42-8-45,45>>^ Mas Jesus perguntou: — Quem me tocou? Como todos negassem, Pedro disse: — Mestre, é a multidão que o rodeia e aperta!

[[v42-8-46]]

^<<v42-8-46,46>>^ Mas Jesus insistiu: — Alguém me tocou, porque senti que de mim saiu poder.

[[v42-8-47]]

^<<v42-8-47,47>>^ A mulher, vendo que não podia passar despercebida, aproximou-se trêmula e, prostrando-se diante de Jesus, declarou, à vista de todo o povo, o motivo por que havia tocado nele e como imediatamente tinha sido curada.

[[v42-8-48]]

^<<v42-8-48,48>>^ Então Jesus lhe disse: — Filha, a sua fé salvou você. Vá em paz.

[[v42-8-49]]

^<<v42-8-49,49>>^ Enquanto Jesus ainda falava, veio uma pessoa da casa do chefe da sinagoga, dizendo: — A sua filha já morreu; não incomode mais o Mestre.

[[v42-8-50]]

^<<v42-8-50,50>>^ Mas Jesus, ouvindo isto, lhe disse: — Não tenha medo; apenas creia, e ela será salva.

[[v42-8-51]]

^<<v42-8-51,51>>^ Tendo chegado à casa, Jesus não permitiu que ninguém entrasse com ele, a não ser Pedro, João e Tiago, além do pai e da mãe da menina.

[[v42-8-52]]

^<<v42-8-52,52>>^ E todos choravam e a pranteavam. Mas Jesus disse: — Não chorem; ela não está morta, mas dorme.

[[v42-8-53]]

^<<v42-8-53,53>>^ E riam-se dele, porque sabiam que ela estava morta.

[[v42-8-54]]

^<<v42-8-54,54>>^ Mas Jesus, tomando-a pela mão, disse em voz alta: — Menina, levante-se!

[[v42-8-55]]

^<<v42-8-55,55>>^ Voltou-lhe o espírito, ela imediatamente se levantou, e Jesus mandou que lhe dessem de comer.

[[v42-8-56]]

^<<v42-8-56,56>>^ Seus pais ficaram maravilhados, mas ele lhes advertiu que a ninguém contassem o que havia acontecido.

'''

xref:042-lucas/042-lucas-007.adoc#v42-7-0[&#60; Capítulo Anterior] | <<v42-8-0,Topo>> | xref:042-lucas/042-lucas-009.adoc#v42-9-0[Próximo Capítulo &#62;]