include::./index.adoc[]

[[v42-22-0]]
=== Lucas, 22
// naa ?, NAA - Nova Almeida Atualizada

[[v42-22-1]]

^<<v42-22-1,1>>^ Estava próxima a Festa dos Pães sem Fermento, chamada Páscoa.

[[v42-22-2]]

^<<v42-22-2,2>>^ Os principais sacerdotes e os escribas procuravam uma forma de matar Jesus; porque temiam o povo.

[[v42-22-3]]

^<<v42-22-3,3>>^ Ora, Satanás entrou em Judas, chamado Iscariotes, que era um dos doze.

[[v42-22-4]]

^<<v42-22-4,4>>^ Judas foi entender-se com os principais sacerdotes e os capitães sobre como lhes entregaria Jesus.

[[v42-22-5]]

^<<v42-22-5,5>>^ Eles se alegraram e combinaram em lhe dar dinheiro.

[[v42-22-6]]

^<<v42-22-6,6>>^ Judas concordou e buscava uma boa ocasião para lhes entregar Jesus, longe da multidão.

[[v42-22-7]]

^<<v42-22-7,7>>^ Chegou o dia da Festa dos Pães sem Fermento, em que era necessário fazer o sacrifício do cordeiro pascal.

[[v42-22-8]]

^<<v42-22-8,8>>^ Então Jesus enviou Pedro e João, dizendo: — Vão e preparem a Páscoa para que a comamos.

[[v42-22-9]]

^<<v42-22-9,9>>^ Eles lhe perguntaram: — Onde o senhor quer que a preparemos?

[[v42-22-10]]

^<<v42-22-10,10>>^ Jesus lhes explicou: — Ao entrar na cidade, vocês encontrarão um homem com um cântaro de água; sigam esse homem até a casa em que ele entrar

[[v42-22-11]]

^<<v42-22-11,11>>^ e digam ao dono da casa: "O Mestre pergunta: ‘Onde fica o aposento no qual comerei a Páscoa com os meus discípulos?’"

[[v42-22-12]]

^<<v42-22-12,12>>^ Ele lhes mostrará um espaçoso cenáculo mobiliado; ali façam os preparativos.

[[v42-22-13]]

^<<v42-22-13,13>>^ E, indo, acharam tudo como Jesus lhes tinha dito e prepararam a Páscoa.

[[v42-22-14]]

^<<v42-22-14,14>>^ Chegada a hora, Jesus se pôs à mesa, e os apóstolos estavam com ele.

[[v42-22-15]]

^<<v42-22-15,15>>^ Então Jesus lhes disse: — Tenho desejado ansiosamente comer esta Páscoa com vocês, antes do meu sofrimento.

[[v42-22-16]]

^<<v42-22-16,16>>^ Pois eu lhes digo que nunca mais a comerei, até que ela se cumpra no Reino de Deus.

[[v42-22-17]]

^<<v42-22-17,17>>^ E, pegando um cálice, depois de ter dado graças, disse: — Peguem e repartam entre vocês.

[[v42-22-18]]

^<<v42-22-18,18>>^ Pois eu digo a vocês que, de agora em diante, não mais beberei do fruto da videira, até que venha o Reino de Deus.

[[v42-22-19]]

^<<v42-22-19,19>>^ E, pegando um pão, tendo dado graças, o partiu e lhes deu, dizendo: — Isto é o meu corpo, que é dado por vocês; façam isto em memória de mim.

[[v42-22-20]]

^<<v42-22-20,20>>^ Do mesmo modo, depois da ceia, pegou o cálice, dizendo: — Este cálice é a nova aliança no meu sangue derramado por vocês.

[[v42-22-21]]

^<<v42-22-21,21>>^ — Mas eis que a mão do traidor está comigo à mesa.

[[v42-22-22]]

^<<v42-22-22,22>>^ Pois o Filho do Homem vai segundo o que está determinado, mas ai daquele por quem ele está sendo traído!

[[v42-22-23]]

^<<v42-22-23,23>>^ Então começaram a perguntar entre si qual deles seria o que estava para fazer isso.

[[v42-22-24]]

^<<v42-22-24,24>>^ Houve também entre eles uma discussão sobre qual deles parecia ser o maior.

[[v42-22-25]]

^<<v42-22-25,25>>^ Mas Jesus lhes disse: — Os reis dos povos dominam sobre eles, e os que exercem autoridade são chamados de benfeitores.

[[v42-22-26]]

^<<v42-22-26,26>>^ Mas vocês não são assim; pelo contrário, o maior entre vocês seja como o menor; e aquele que dirige seja como o que serve.

[[v42-22-27]]

^<<v42-22-27,27>>^ Pois qual é maior: aquele que está à mesa ou aquele que serve? Não é verdade que é aquele que está à mesa? Pois, no meio de vocês, eu sou como quem serve.

[[v42-22-28]]

^<<v42-22-28,28>>^ Vocês são os que têm permanecido comigo nas minhas tentações.

[[v42-22-29]]

^<<v42-22-29,29>>^ E eu confio a vocês um reino, assim como o meu Pai confiou a mim,

[[v42-22-30]]

^<<v42-22-30,30>>^ para que comam e bebam à minha mesa no meu Reino; e vocês se assentarão em tronos para julgar as doze tribos de Israel.

[[v42-22-31]]

^<<v42-22-31,31>>^ — Simão, Simão, eis que Satanás pediu para peneirar vocês como trigo!

[[v42-22-32]]

^<<v42-22-32,32>>^ Eu, porém, orei por você, para que a sua fé não desfaleça. E você, quando voltar para mim, fortaleça os seus irmãos.

[[v42-22-33]]

^<<v42-22-33,33>>^ Porém Pedro respondeu: — Estou pronto para ir com o Senhor, tanto para a prisão como para a morte.

[[v42-22-34]]

^<<v42-22-34,34>>^ Mas Jesus lhe disse: — Eu lhe digo, Pedro, que hoje, antes que o galo cante, você negará três vezes que me conhece.

[[v42-22-35]]

^<<v42-22-35,35>>^ A seguir, Jesus perguntou aos discípulos: — Quando eu os enviei sem bolsa, sem sacola e sem sandálias, por acaso faltou-lhes alguma coisa? Eles responderam: — Não faltou nada!

[[v42-22-36]]

^<<v42-22-36,36>>^ Então Jesus lhes disse: — Agora, porém, quem tem bolsa, pegue-a, e faça o mesmo com a sacola; e o que não tem espada, venda a sua capa e compre uma.

[[v42-22-37]]

^<<v42-22-37,37>>^ Pois eu lhes digo que é preciso que se cumpra em mim o que está escrito: "Ele foi contado com os malfeitores." Pois o que a mim se refere está sendo cumprido.

[[v42-22-38]]

^<<v42-22-38,38>>^ Então lhe disseram: — Senhor, aqui estão duas espadas! Jesus lhes respondeu: — Basta!

[[v42-22-39]]

^<<v42-22-39,39>>^ E, saindo, Jesus foi, como de costume, para o monte das Oliveiras; e os discípulos o acompanharam.

[[v42-22-40]]

^<<v42-22-40,40>>^ Chegando ao lugar escolhido, Jesus lhes disse: — Orem, para que vocês não caiam em tentação.

[[v42-22-41]]

^<<v42-22-41,41>>^ Ele, por sua vez, se afastou um pouco, e, de joelhos, orava,

[[v42-22-42]]

^<<v42-22-42,42>>^ dizendo: — Pai, se queres, afasta de mim este cálice! Contudo, não se faça a minha vontade, e sim a tua.

[[v42-22-43]]

^<<v42-22-43,43>>^ Então lhe apareceu um anjo do céu que o confortava.

[[v42-22-44]]

^<<v42-22-44,44>>^ E, estando em agonia, orava mais intensamente. E aconteceu que o suor dele se tornou como gotas de sangue caindo sobre a terra.

[[v42-22-45]]

^<<v42-22-45,45>>^ Levantando-se da oração, Jesus foi até onde os discípulos estavam, e os encontrou dormindo de tristeza.

[[v42-22-46]]

^<<v42-22-46,46>>^ E disse: — Por que vocês estão dormindo? Levantem-se e orem, para que não caiam em tentação.

[[v42-22-47]]

^<<v42-22-47,47>>^ Enquanto Jesus ainda falava, eis que chegou uma multidão. E um dos doze, que se chamava Judas, vinha à frente deles e se aproximou de Jesus para o beijar.

[[v42-22-48]]

^<<v42-22-48,48>>^ Jesus, porém, lhe disse: — Judas, com um beijo você trai o Filho do Homem?

[[v42-22-49]]

^<<v42-22-49,49>>^ Os que estavam ao redor de Jesus, vendo o que estava por acontecer, perguntaram: — Senhor, devemos atacar com as espadas?

[[v42-22-50]]

^<<v42-22-50,50>>^ Um deles golpeou o servo do sumo sacerdote e cortou-lhe a orelha direita.

[[v42-22-51]]

^<<v42-22-51,51>>^ Mas Jesus interveio, dizendo: — Deixem! Basta! E, tocando na orelha do homem, o curou.

[[v42-22-52]]

^<<v42-22-52,52>>^ Então Jesus disse aos principais sacerdotes, capitães do templo e anciãos que vieram prendê-lo: — Vocês vieram com espadas e porretes como para prender um salteador?

[[v42-22-53]]

^<<v42-22-53,53>>^ Todos os dias, estando eu com vocês no templo, vocês não tentaram me prender. Esta, porém, é a hora de vocês e a hora do poder das trevas.

[[v42-22-54]]

^<<v42-22-54,54>>^ Então, prendendo Jesus, levaram-no e o introduziram na casa do sumo sacerdote. Pedro seguia de longe.

[[v42-22-55]]

^<<v42-22-55,55>>^ Quando acenderam um fogo no meio do pátio e se assentaram juntos, Pedro tomou lugar entre eles.

[[v42-22-56]]

^<<v42-22-56,56>>^ Uma empregada, vendo-o sentado perto do fogo, fixou os olhos nele e disse: — Este também estava com ele.

[[v42-22-57]]

^<<v42-22-57,57>>^ Mas Pedro negou, dizendo: — Mulher, não o conheço.

[[v42-22-58]]

^<<v42-22-58,58>>^ Pouco depois, outro homem, ao ver Pedro, disse: — Você também é um deles. Mas Pedro disse: — Homem, eu não sou um deles.

[[v42-22-59]]

^<<v42-22-59,59>>^ E, tendo passado cerca de uma hora, outro afirmou, dizendo: — Com certeza este também estava com ele, porque também é galileu.

[[v42-22-60]]

^<<v42-22-60,60>>^ Mas Pedro insistiu: — Homem, não sei do que você está falando. E logo, enquanto Pedro ainda falava, o galo cantou.

[[v42-22-61]]

^<<v42-22-61,61>>^ Então, o Senhor voltou-se e fixou os olhos em Pedro. E Pedro se lembrou da palavra do Senhor, como lhe tinha dito: "Hoje, antes que o galo cante, você me negará três vezes."

[[v42-22-62]]

^<<v42-22-62,62>>^ E Pedro, saindo dali, chorou amargamente.

[[v42-22-63]]

^<<v42-22-63,63>>^ Os homens que detinham Jesus zombavam dele, davam-lhe pancadas e,

[[v42-22-64]]

^<<v42-22-64,64>>^ colocando uma venda sobre os olhos dele, diziam: — Profetize! Quem foi que bateu em você?

[[v42-22-65]]

^<<v42-22-65,65>>^ E muitas outras coisas diziam contra ele, blasfemando.

[[v42-22-66]]

^<<v42-22-66,66>>^ Logo que amanheceu, reuniu-se a assembleia dos anciãos do povo, tanto os principais sacerdotes como os escribas, e o conduziram ao Sinédrio, onde lhe disseram:

[[v42-22-67]]

^<<v42-22-67,67>>^ — Se você é o Cristo, diga-nos. Então Jesus lhes respondeu: — Se disser, vocês não vão acreditar.

[[v42-22-68]]

^<<v42-22-68,68>>^ E, se eu perguntar, vocês não me darão resposta.

[[v42-22-69]]

^<<v42-22-69,69>>^ Desde agora, o Filho do Homem estará sentado à direita do Deus Todo-Poderoso.

[[v42-22-70]]

^<<v42-22-70,70>>^ Todos perguntaram: — Então você é o Filho de Deus? Jesus respondeu: — Vocês dizem que eu sou.

[[v42-22-71]]

^<<v42-22-71,71>>^ Eles disseram: — Que necessidade ainda temos de testemunho? Porque nós mesmos ouvimos o que ele falou.

'''

xref:042-lucas/042-lucas-021.adoc#v42-21-0[&#60; Capítulo Anterior] | <<v42-22-0,Topo>> | xref:042-lucas/042-lucas-023.adoc#v42-23-0[Próximo Capítulo &#62;]