include::./index.adoc[]

[[v42-20-0]]
=== Lucas, 20
// naa ?, NAA - Nova Almeida Atualizada

[[v42-20-1]]

^<<v42-20-1,1>>^ Aconteceu que, num daqueles dias, estando Jesus a ensinar o povo no templo e a evangelizar, chegaram os principais sacerdotes e os escribas, juntamente com os anciãos,

[[v42-20-2]]

^<<v42-20-2,2>>^ e lhe perguntaram: — Diga-nos com que autoridade você faz estas coisas? Ou quem lhe deu esta autoridade?

[[v42-20-3]]

^<<v42-20-3,3>>^ Jesus respondeu: — Eu também vou fazer uma pergunta a vocês. Digam:

[[v42-20-4]]

^<<v42-20-4,4>>^ O batismo de João era do céu ou dos homens?

[[v42-20-5]]

^<<v42-20-5,5>>^ Então discutiram entre si: — Se dissermos: "Do céu", ele dirá: "Por que não acreditaram nele?"

[[v42-20-6]]

^<<v42-20-6,6>>^ Mas, se dissermos: "Dos homens", o povo todo nos apedrejará, porque está convicto de que João era profeta.

[[v42-20-7]]

^<<v42-20-7,7>>^ Por fim, responderam que não sabiam de onde era.

[[v42-20-8]]

^<<v42-20-8,8>>^ E Jesus lhes disse: — Então eu também não lhes digo com que autoridade faço estas coisas.

[[v42-20-9]]

^<<v42-20-9,9>>^ A seguir, Jesus passou a contar ao povo esta parábola: — Certo homem plantou uma vinha, arrendou-a para uns lavradores e ausentou-se do país por prazo considerável.

[[v42-20-10]]

^<<v42-20-10,10>>^ No devido tempo, mandou um servo aos lavradores para que lhe dessem do fruto da vinha. Mas os lavradores, depois de espancá-lo, o despacharam de mãos vazias.

[[v42-20-11]]

^<<v42-20-11,11>>^ Em vista disso, enviou-lhes outro servo, mas também a este espancaram e, depois de insultá-lo, despacharam de mãos vazias.

[[v42-20-12]]

^<<v42-20-12,12>>^ Mandou ainda um terceiro; também a este, depois de feri-lo, expulsaram.

[[v42-20-13]]

^<<v42-20-13,13>>^ Então o dono da vinha disse: "Que farei? Enviarei o meu filho amado; talvez o respeitem."

[[v42-20-14]]

^<<v42-20-14,14>>^ — Mas, quando os lavradores viram o filho, começaram a discutir entre si: "Este é o herdeiro; vamos matá-lo, para que a herança seja nossa."

[[v42-20-15]]

^<<v42-20-15,15>>^ E, lançando-o fora da vinha, o mataram. — Que lhes fará, pois, o dono da vinha?

[[v42-20-16]]

^<<v42-20-16,16>>^ Virá, exterminará aqueles lavradores e entregará a vinha a outros. Ao ouvir isto, disseram: — Que tal não aconteça!

[[v42-20-17]]

^<<v42-20-17,17>>^ Mas Jesus, com o olhar fixo neles, disse: — Que quer dizer então o que está escrito: "A pedra que os construtores rejeitaram, essa veio a ser a pedra angular"?

[[v42-20-18]]

^<<v42-20-18,18>>^ Todo o que cair sobre esta pedra ficará em pedaços; e aquele sobre quem ela cair ficará reduzido a pó.

[[v42-20-19]]

^<<v42-20-19,19>>^ Naquela mesma hora, os escribas e os principais sacerdotes procuravam prender Jesus, porque entenderam que ele havia contado essa parábola contra eles; mas temiam o povo.

[[v42-20-20]]

^<<v42-20-20,20>>^ Eles passaram a vigiar Jesus. Enviaram espiões que se fingiam de justos para ver se o apanhavam em alguma palavra, a fim de entregá-lo à jurisdição e à autoridade do governador.

[[v42-20-21]]

^<<v42-20-21,21>>^ Então lhe perguntaram: — Mestre, sabemos que o senhor fala e ensina corretamente e não se deixa levar pela aparência das pessoas, mas ensina o caminho de Deus segundo a verdade.

[[v42-20-22]]

^<<v42-20-22,22>>^ É lícito pagar imposto a César ou não?

[[v42-20-23]]

^<<v42-20-23,23>>^ Mas Jesus, percebendo a artimanha deles, respondeu:

[[v42-20-24]]

^<<v42-20-24,24>>^ — Mostrem-me um denário. De quem é a figura e a inscrição? Eles responderam: — De César. Então Jesus lhes disse:

[[v42-20-25]]

^<<v42-20-25,25>>^ — Pois deem a César o que é de César e a Deus o que é de Deus.

[[v42-20-26]]

^<<v42-20-26,26>>^ Não puderam apanhá-lo em palavra alguma diante do povo; e, admirados da sua resposta, calaram-se.

[[v42-20-27]]

^<<v42-20-27,27>>^ Chegando alguns dos saduceus, que dizem não haver ressurreição,

[[v42-20-28]]

^<<v42-20-28,28>>^ perguntaram a Jesus: — Mestre, Moisés nos deixou escrito que, se um homem casado morrer sem deixar filhos, o irmão desse homem deve casar com a viúva e gerar descendentes para o falecido.

[[v42-20-29]]

^<<v42-20-29,29>>^ Ora, havia sete irmãos: o primeiro casou e morreu sem filhos;

[[v42-20-30]]

^<<v42-20-30,30>>^ o segundo

[[v42-20-31]]

^<<v42-20-31,31>>^ e o terceiro também casaram com a viúva, e assim foi com os sete. Todos morreram sem deixar filhos.

[[v42-20-32]]

^<<v42-20-32,32>>^ Por fim, morreu também a mulher.

[[v42-20-33]]

^<<v42-20-33,33>>^ Portanto, na ressurreição, de qual deles a mulher será esposa? Porque os sete casaram com ela.

[[v42-20-34]]

^<<v42-20-34,34>>^ Jesus respondeu: — Os filhos deste mundo casam e se dão em casamento,

[[v42-20-35]]

^<<v42-20-35,35>>^ mas os que são considerados dignos de alcançar a era vindoura e a ressurreição dentre os mortos não casam, nem se dão em casamento.

[[v42-20-36]]

^<<v42-20-36,36>>^ Pois não podem mais morrer, porque são iguais aos anjos e são filhos de Deus, sendo filhos da ressurreição.

[[v42-20-37]]

^<<v42-20-37,37>>^ E que os mortos ressuscitam, Moisés o indicou no trecho referente à sarça, quando afirma que o Senhor é o Deus de Abraão, o Deus de Isaque e o Deus de Jacó.

[[v42-20-38]]

^<<v42-20-38,38>>^ Ora, Deus não é Deus de mortos, e sim de vivos; porque para ele todos vivem.

[[v42-20-39]]

^<<v42-20-39,39>>^ Então alguns dos escribas disseram: — Boa resposta, Mestre!

[[v42-20-40]]

^<<v42-20-40,40>>^ E não ousaram mais fazer perguntas a Jesus.

[[v42-20-41]]

^<<v42-20-41,41>>^ Mas Jesus lhes perguntou: — Como se pode dizer que o Cristo é filho de Davi?

[[v42-20-42]]

^<<v42-20-42,42>>^ Pois o próprio Davi afirma no Livro dos Salmos: "Disse o Senhor ao meu Senhor: ‘Sente-se à minha direita,

[[v42-20-43]]

^<<v42-20-43,43>>^ até que eu ponha os seus inimigos por estrado dos seus pés.’"

[[v42-20-44]]

^<<v42-20-44,44>>^ — Portanto, Davi o chama de Senhor. Então como ele pode ser filho de Davi?

[[v42-20-45]]

^<<v42-20-45,45>>^ Quando todo o povo estava ouvindo, Jesus disse aos seus discípulos:

[[v42-20-46]]

^<<v42-20-46,46>>^ — Cuidado com os escribas, que gostam de andar com vestes talares e muito apreciam as saudações nas praças, as primeiras cadeiras nas sinagogas e os primeiros lugares nos banquetes.

[[v42-20-47]]

^<<v42-20-47,47>>^ Eles devoram as casas das viúvas e, para o justificar, fazem longas orações. Estes sofrerão juízo muito mais severo.

'''

xref:042-lucas/042-lucas-019.adoc#v42-19-0[&#60; Capítulo Anterior] | <<v42-20-0,Topo>> | xref:042-lucas/042-lucas-021.adoc#v42-21-0[Próximo Capítulo &#62;]