include::./index.adoc[]

[[v42-24-0]]
=== Lucas, 24
// naa ?, NAA - Nova Almeida Atualizada

[[v42-24-1]]

^<<v42-24-1,1>>^ Mas, no primeiro dia da semana, alta madrugada, as mulheres foram ao túmulo, levando os óleos aromáticos que haviam preparado.

[[v42-24-2]]

^<<v42-24-2,2>>^ Encontraram a pedra removida do túmulo,

[[v42-24-3]]

^<<v42-24-3,3>>^ mas, ao entrar, não acharam o corpo do Senhor Jesus.

[[v42-24-4]]

^<<v42-24-4,4>>^ Aconteceu que, perplexas a esse respeito, apareceram-lhes dois homens com roupas resplandecentes.

[[v42-24-5]]

^<<v42-24-5,5>>^ Estando elas com muito medo e baixando os olhos para o chão, eles disseram: — Por que vocês estão procurando entre os mortos aquele que vive?

[[v42-24-6]]

^<<v42-24-6,6>>^ Ele não está aqui, mas ressuscitou. Lembrem-se do que ele falou para vocês, estando ainda na Galileia:

[[v42-24-7]]

^<<v42-24-7,7>>^ "É necessário que o Filho do Homem seja entregue nas mãos de pecadores, seja crucificado e ressuscite no terceiro dia."

[[v42-24-8]]

^<<v42-24-8,8>>^ Então elas se lembraram das palavras de Jesus.

[[v42-24-9]]

^<<v42-24-9,9>>^ E, voltando do túmulo, anunciaram todas estas coisas aos onze e a todos os outros que estavam com eles.

[[v42-24-10]]

^<<v42-24-10,10>>^ Essas mulheres eram Maria Madalena, Joana e Maria, mãe de Tiago; também as demais que estavam com elas confirmaram estas coisas aos apóstolos.

[[v42-24-11]]

^<<v42-24-11,11>>^ Mas para eles tais palavras pareciam um delírio; eles não acreditaram no que as mulheres diziam.

[[v42-24-12]]

^<<v42-24-12,12>>^ Pedro, porém, levantando-se, correu ao túmulo. E, abaixando-se, viu somente os lençóis de linho e nada mais; e retirou-se para casa, admirado com o que tinha acontecido.

[[v42-24-13]]

^<<v42-24-13,13>>^ Naquele mesmo dia, dois discípulos estavam indo para uma aldeia chamada Emaús, que ficava a uns dez quilômetros de Jerusalém.

[[v42-24-14]]

^<<v42-24-14,14>>^ E iam conversando a respeito de tudo o que tinha acontecido.

[[v42-24-15]]

^<<v42-24-15,15>>^ Enquanto conversavam e discutiam, o próprio Jesus se aproximou e ia com eles.

[[v42-24-16]]

^<<v42-24-16,16>>^ Porém os olhos deles estavam como que impedidos de o reconhecer.

[[v42-24-17]]

^<<v42-24-17,17>>^ Então ele lhes perguntou: — O que é que vocês estão discutindo pelo caminho? E eles pararam entristecidos.

[[v42-24-18]]

^<<v42-24-18,18>>^ Um, porém, chamado Cleopas, respondeu: — Será que você é o único que esteve em Jerusalém e não sabe o que aconteceu lá, nestes últimos dias?

[[v42-24-19]]

^<<v42-24-19,19>>^ Ele lhes perguntou: — Do que se trata? Eles explicaram: — Aquilo que aconteceu com Jesus, o Nazareno, que era profeta, poderoso em obras e palavras, diante de Deus e de todo o povo,

[[v42-24-20]]

^<<v42-24-20,20>>^ e como os principais sacerdotes e as nossas autoridades o entregaram para ser condenado à morte e o crucificaram.

[[v42-24-21]]

^<<v42-24-21,21>>^ Nós esperávamos que fosse ele quem havia de redimir Israel. Mas, depois de tudo isto, já estamos no terceiro dia desde que essas coisas aconteceram.

[[v42-24-22]]

^<<v42-24-22,22>>^ É verdade também que algumas mulheres do nosso grupo nos surpreenderam. Indo de madrugada ao túmulo

[[v42-24-23]]

^<<v42-24-23,23>>^ e não achando o corpo de Jesus, voltaram dizendo que tinham tido uma visão de anjos, os quais afirmam que ele vive.

[[v42-24-24]]

^<<v42-24-24,24>>^ De fato, alguns dos nossos foram ao túmulo e verificaram a exatidão do que as mulheres disseram; mas não o viram.

[[v42-24-25]]

^<<v42-24-25,25>>^ Então ele lhes disse: — Como vocês são insensatos e demoram para crer em tudo o que os profetas disseram!

[[v42-24-26]]

^<<v42-24-26,26>>^ Não é verdade que o Cristo tinha de sofrer e entrar na sua glória?

[[v42-24-27]]

^<<v42-24-27,27>>^ E, começando por Moisés e todos os Profetas, explicou-lhes o que constava a respeito dele em todas as Escrituras.

[[v42-24-28]]

^<<v42-24-28,28>>^ Quando se aproximavam da aldeia para onde iam, ele fez menção de passar adiante.

[[v42-24-29]]

^<<v42-24-29,29>>^ Mas eles o convenceram a ficar, dizendo: — Fique conosco, porque é tarde, e o dia já está chegando ao fim. E entrou para ficar com eles.

[[v42-24-30]]

^<<v42-24-30,30>>^ E aconteceu que, quando estavam à mesa, ele pegou o pão e o abençoou; depois, partiu o pão e o deu a eles.

[[v42-24-31]]

^<<v42-24-31,31>>^ Então os olhos deles se abriram, e eles reconheceram Jesus; mas ele desapareceu da presença deles.

[[v42-24-32]]

^<<v42-24-32,32>>^ E disseram um ao outro: — Não é verdade que o coração nos ardia no peito, quando ele nos falava pelo caminho, quando nos explicava as Escrituras?

[[v42-24-33]]

^<<v42-24-33,33>>^ E, na mesma hora, levantando-se, voltaram para Jerusalém, onde acharam reunidos os onze e outros com eles,

[[v42-24-34]]

^<<v42-24-34,34>>^ os quais diziam: — De fato, o Senhor ressuscitou e já apareceu a Simão!

[[v42-24-35]]

^<<v42-24-35,35>>^ Então os dois contaram o que lhes tinha acontecido no caminho e como tinham reconhecido o Senhor no partir do pão.

[[v42-24-36]]

^<<v42-24-36,36>>^ Falavam eles ainda estas coisas quando Jesus apareceu no meio deles e lhes disse: — Que a paz esteja com vocês!

[[v42-24-37]]

^<<v42-24-37,37>>^ Eles, porém, ficaram assustados e com medo, pensando que estavam vendo um espírito.

[[v42-24-38]]

^<<v42-24-38,38>>^ Mas ele lhes disse: — Por que vocês estão assustados? E por que surgem dúvidas no coração de vocês?

[[v42-24-39]]

^<<v42-24-39,39>>^ Vejam as minhas mãos e os meus pés, que sou eu mesmo. Toquem em mim e vejam que é verdade, porque um espírito não tem carne nem ossos, como vocês estão vendo que eu tenho.

[[v42-24-40]]

^<<v42-24-40,40>>^ Dizendo isto, mostrou-lhes as mãos e os pés.

[[v42-24-41]]

^<<v42-24-41,41>>^ E, por não acreditarem eles ainda, por causa da alegria, e como estavam admirados, Jesus lhes disse: — Vocês têm aqui alguma coisa para comer?

[[v42-24-42]]

^<<v42-24-42,42>>^ Então lhe apresentaram um pedaço de peixe assado,

[[v42-24-43]]

^<<v42-24-43,43>>^ e ele comeu na presença deles.

[[v42-24-44]]

^<<v42-24-44,44>>^ A seguir, Jesus lhes disse: — São estas as palavras que eu lhes falei, estando ainda com vocês: era necessário que se cumprisse tudo o que está escrito a respeito de mim na Lei de Moisés, nos Profetas e nos Salmos.

[[v42-24-45]]

^<<v42-24-45,45>>^ Então lhes abriu o entendimento para compreenderem as Escrituras.

[[v42-24-46]]

^<<v42-24-46,46>>^ E disse-lhes: — Assim está escrito que o Cristo tinha de sofrer, ressuscitar dentre os mortos no terceiro dia,

[[v42-24-47]]

^<<v42-24-47,47>>^ e que em seu nome se pregasse arrependimento para remissão de pecados a todas as nações, começando em Jerusalém.

[[v42-24-48]]

^<<v42-24-48,48>>^ Vocês são testemunhas destas coisas.

[[v42-24-49]]

^<<v42-24-49,49>>^ Eis que envio sobre vocês a promessa de meu Pai; permaneçam, pois, na cidade, até que vocês sejam revestidos do poder que vem do alto.

[[v42-24-50]]

^<<v42-24-50,50>>^ Então Jesus os levou para fora, até Betânia. E, erguendo as mãos, os abençoou.

[[v42-24-51]]

^<<v42-24-51,51>>^ Aconteceu que, enquanto os abençoava, ia-se retirando deles, sendo elevado para o céu.

[[v42-24-52]]

^<<v42-24-52,52>>^ Então eles, adorando-o, voltaram para Jerusalém cheios de alegria.

[[v42-24-53]]

^<<v42-24-53,53>>^ E estavam sempre no templo, louvando a Deus.

'''

xref:042-lucas/042-lucas-023.adoc#v42-23-0[&#60; Capítulo Anterior] | <<v42-24-0,Topo>> | xref:043-joao/043-joao-001.adoc#v43-1-0[Próximo Capítulo &#62;]