include::./index.adoc[]

[[v42-15-0]]
=== Lucas, 15
// naa ?, NAA - Nova Almeida Atualizada

[[v42-15-1]]

^<<v42-15-1,1>>^ Aproximavam-se de Jesus todos os publicanos e pecadores para o ouvir.

[[v42-15-2]]

^<<v42-15-2,2>>^ Os fariseus e os escribas murmuravam, dizendo: — Este recebe pecadores e come com eles.

[[v42-15-3]]

^<<v42-15-3,3>>^ Então Jesus lhes contou esta parábola:

[[v42-15-4]]

^<<v42-15-4,4>>^ — Qual de vocês é o homem que, possuindo cem ovelhas e perdendo uma delas, não deixa no deserto as noventa e nove e vai em busca da que se perdeu, até encontrá-la?

[[v42-15-5]]

^<<v42-15-5,5>>^ E, quando a encontra, põe-na sobre os ombros, cheio de alegria.

[[v42-15-6]]

^<<v42-15-6,6>>^ E, indo para casa, reúne os amigos e vizinhos, dizendo-lhes: "Alegrem-se comigo, porque já achei a minha ovelha perdida."

[[v42-15-7]]

^<<v42-15-7,7>>^ Digo a vocês que, assim, haverá mais alegria no céu por um pecador que se arrepende do que por noventa e nove justos que não necessitam de arrependimento.

[[v42-15-8]]

^<<v42-15-8,8>>^ — Ou qual é a mulher que, tendo dez dracmas, se perder uma delas, não acende a lamparina, varre a casa e a procura com muito empenho até encontrá-la?

[[v42-15-9]]

^<<v42-15-9,9>>^ E, quando a encontra, reúne as amigas e vizinhas, dizendo: "Alegrem-se comigo, porque achei a dracma que eu tinha perdido."

[[v42-15-10]]

^<<v42-15-10,10>>^ Eu afirmo a vocês que a mesma alegria existe diante dos anjos de Deus por um pecador que se arrepende.

[[v42-15-11]]

^<<v42-15-11,11>>^ Jesus continuou: — Certo homem tinha dois filhos.

[[v42-15-12]]

^<<v42-15-12,12>>^ O mais moço deles disse ao pai: "Pai, quero que o senhor me dê a parte dos bens que me cabe." E o pai repartiu os bens entre eles.

[[v42-15-13]]

^<<v42-15-13,13>>^ — Passados não muitos dias, o filho mais moço, ajuntando tudo o que era seu, partiu para uma terra distante e lá desperdiçou todos os seus bens, vivendo de forma desenfreada.

[[v42-15-14]]

^<<v42-15-14,14>>^ — Depois de ter consumido tudo, sobreveio àquele país uma grande fome, e ele começou a passar necessidade.

[[v42-15-15]]

^<<v42-15-15,15>>^ Então foi pedir trabalho a um dos cidadãos daquela terra, e este o mandou para os seus campos a fim de cuidar dos porcos.

[[v42-15-16]]

^<<v42-15-16,16>>^ Ali, ele desejava alimentar-se das alfarrobas que os porcos comiam, mas ninguém lhe dava nada.

[[v42-15-17]]

^<<v42-15-17,17>>^ Então, caindo em si, disse: "Quantos trabalhadores de meu pai têm pão com fartura, e eu aqui estou morrendo de fome!

[[v42-15-18]]

^<<v42-15-18,18>>^ Vou me arrumar, voltar para o meu pai e lhe dizer: ‘Pai, pequei contra Deus e diante do senhor;

[[v42-15-19]]

^<<v42-15-19,19>>^ já não sou digno de ser chamado de seu filho; trate-me como um dos seus trabalhadores.’"

[[v42-15-20]]

^<<v42-15-20,20>>^ E, arrumando-se, foi para o seu pai. — Vinha ele ainda longe, quando seu pai o avistou e, compadecido dele, correndo, o abraçou e beijou.

[[v42-15-21]]

^<<v42-15-21,21>>^ E o filho lhe disse: "Pai, pequei contra Deus e diante do senhor; já não sou digno de ser chamado de seu filho."

[[v42-15-22]]

^<<v42-15-22,22>>^ O pai, porém, disse aos servos: "Tragam depressa a melhor roupa e vistam nele. Ponham um anel no dedo dele e sandálias nos pés.

[[v42-15-23]]

^<<v42-15-23,23>>^ Tragam e matem o bezerro gordo. Vamos comer e festejar,

[[v42-15-24]]

^<<v42-15-24,24>>^ porque este meu filho estava morto e reviveu, estava perdido e foi achado." E começaram a festejar.

[[v42-15-25]]

^<<v42-15-25,25>>^ — Ora, o filho mais velho estava no campo. Quando voltava, ao aproximar-se da casa, ouviu a música e as danças.

[[v42-15-26]]

^<<v42-15-26,26>>^ Chamou um dos empregados e perguntou o que era aquilo.

[[v42-15-27]]

^<<v42-15-27,27>>^ E ele informou: "O seu irmão voltou e, por tê-lo recuperado com saúde, o seu pai mandou matar o bezerro gordo."

[[v42-15-28]]

^<<v42-15-28,28>>^ — O filho mais velho se indignou e não queria entrar. Saindo, porém, o pai, procurava convencê-lo a entrar.

[[v42-15-29]]

^<<v42-15-29,29>>^ Mas ele respondeu ao seu pai: "Faz tantos anos que sirvo o senhor e nunca transgredi um mandamento seu. Mas o senhor nunca me deu um cabrito sequer para fazer uma festa com os meus amigos.

[[v42-15-30]]

^<<v42-15-30,30>>^ Mas, quando veio esse seu filho, que sumiu com os bens do senhor, gastando tudo com prostitutas, o senhor mandou matar o bezerro gordo para ele!"

[[v42-15-31]]

^<<v42-15-31,31>>^ — Então o pai respondeu: "Meu filho, você está sempre comigo; tudo o que eu tenho é seu.

[[v42-15-32]]

^<<v42-15-32,32>>^ Mas era preciso festejar e alegrar-se, porque este seu irmão estava morto e reviveu, estava perdido e foi achado."

'''

xref:042-lucas/042-lucas-014.adoc#v42-14-0[&#60; Capítulo Anterior] | <<v42-15-0,Topo>> | xref:042-lucas/042-lucas-016.adoc#v42-16-0[Próximo Capítulo &#62;]