include::./index.adoc[]

[[v42-11-0]]
=== Lucas, 11
// naa ?, NAA - Nova Almeida Atualizada

[[v42-11-1]]

^<<v42-11-1,1>>^ Jesus estava orando em certo lugar e, quando terminou, um dos seus discípulos lhe pediu: — Senhor, ensine-nos a orar como também João ensinou os discípulos dele.

[[v42-11-2]]

^<<v42-11-2,2>>^ Então Jesus disse: — Quando vocês orarem, digam: "Pai, santificado seja o teu nome; venha o teu Reino;

[[v42-11-3]]

^<<v42-11-3,3>>^ o pão nosso de cada dia dá-nos diariamente;

[[v42-11-4]]

^<<v42-11-4,4>>^ perdoa-nos os nossos pecados, pois também nós perdoamos a todo o que nos deve; e não nos deixes cair em tentação."

[[v42-11-5]]

^<<v42-11-5,5>>^ Jesus disse ainda: — Se um de vocês tiver um amigo e for procurá-lo à meia-noite, dizendo: "Amigo, me empreste três pães,

[[v42-11-6]]

^<<v42-11-6,6>>^ porque outro amigo meu chegou de viagem e eu não tenho nada para lhe oferecer";

[[v42-11-7]]

^<<v42-11-7,7>>^ e se o outro lhe responder lá de dentro: "Deixe-me em paz! A porta já está fechada, e eu e os meus filhos já estamos deitados. Não posso me levantar para lhe dar os pães",

[[v42-11-8]]

^<<v42-11-8,8>>^ digo a vocês que, se ele não se levantar para dar esses pães por ser seu amigo, ele o fará por causa do incômodo e lhe dará tudo de que tiver necessidade.

[[v42-11-9]]

^<<v42-11-9,9>>^ — Por isso, digo a vocês: Peçam e lhes será dado; busquem e acharão; batam, e a porta será aberta para vocês.

[[v42-11-10]]

^<<v42-11-10,10>>^ Pois todo o que pede recebe; o que busca encontra; e a quem bate, a porta será aberta.

[[v42-11-11]]

^<<v42-11-11,11>>^ Quem de vocês, sendo pai, daria uma cobra ao filho que lhe pede um peixe?

[[v42-11-12]]

^<<v42-11-12,12>>^ Ou daria um escorpião ao filho que lhe pede um ovo?

[[v42-11-13]]

^<<v42-11-13,13>>^ Ora, se vocês, que são maus, sabem dar coisas boas aos seus filhos, quanto mais o Pai celeste dará o Espírito Santo aos que lhe pedirem!

[[v42-11-14]]

^<<v42-11-14,14>>^ Certo dia, Jesus estava expulsando um demônio que era mudo. E aconteceu que, ao sair o demônio, o mudo passou a falar. E as multidões se admiravam.

[[v42-11-15]]

^<<v42-11-15,15>>^ Mas alguns deles diziam: — Ele expulsa os demônios pelo poder de Belzebu, o maioral dos demônios.

[[v42-11-16]]

^<<v42-11-16,16>>^ E outros, tentando-o, pediam dele um sinal vindo do céu.

[[v42-11-17]]

^<<v42-11-17,17>>^ Mas Jesus, sabendo o que passava pela mente deles, disse-lhes: — Todo reino dividido contra si mesmo ficará deserto, e casa sobre casa cairá.

[[v42-11-18]]

^<<v42-11-18,18>>^ Se também Satanás estiver dividido contra si mesmo, como o seu reino subsistirá? Isto porque vocês dizem que eu expulso os demônios por Belzebu.

[[v42-11-19]]

^<<v42-11-19,19>>^ E, se eu expulso os demônios por Belzebu, por quem os filhos de vocês os expulsam? Por isso, eles mesmos serão os juízes de vocês.

[[v42-11-20]]

^<<v42-11-20,20>>^ Se, porém, eu expulso os demônios pelo dedo de Deus, certamente é chegado o Reino de Deus sobre vocês.

[[v42-11-21]]

^<<v42-11-21,21>>^ Quando o valente, bem-armado, guarda a sua própria casa, todos os seus bens ficam em segurança.

[[v42-11-22]]

^<<v42-11-22,22>>^ Mas, se aparece alguém mais valente do que ele, vence-o, tira-lhe a armadura em que confiava e reparte os seus despojos.

[[v42-11-23]]

^<<v42-11-23,23>>^ Quem não é por mim é contra mim; e quem comigo não ajunta espalha.

[[v42-11-24]]

^<<v42-11-24,24>>^ — Quando o espírito imundo sai de uma pessoa, anda por lugares áridos, procurando repouso. E, não o achando, diz: "Voltarei para a minha casa, de onde saí."

[[v42-11-25]]

^<<v42-11-25,25>>^ E, voltando, a encontra varrida e arrumada.

[[v42-11-26]]

^<<v42-11-26,26>>^ Então vai e leva consigo outros sete espíritos, piores do que ele, e, entrando, habitam ali. E o último estado daquela pessoa se torna pior do que o primeiro.

[[v42-11-27]]

^<<v42-11-27,27>>^ Aconteceu que, ao dizer Jesus estas palavras, uma mulher, que estava no meio da multidão, disse a ele, erguendo a voz: — Bem-aventurado o ventre que concebeu você e os seios que o amamentaram!

[[v42-11-28]]

^<<v42-11-28,28>>^ Jesus, porém, respondeu: — Pelo contrário! Mais bem-aventurados são os que ouvem a palavra de Deus e a guardam!

[[v42-11-29]]

^<<v42-11-29,29>>^ Visto que aumentavam as multidões em volta dele, Jesus começou a dizer: — Esta é uma geração perversa! Pede sinal; mas nenhum sinal lhe será dado, senão o de Jonas.

[[v42-11-30]]

^<<v42-11-30,30>>^ Porque, assim como Jonas foi sinal para os ninivitas, o Filho do Homem o será para esta geração.

[[v42-11-31]]

^<<v42-11-31,31>>^ A rainha do Sul se levantará, no Juízo, com os homens desta geração e os condenará, porque veio dos confins da terra para ouvir a sabedoria de Salomão. E aqui está quem é maior do que Salomão.

[[v42-11-32]]

^<<v42-11-32,32>>^ Ninivitas se levantarão, no Juízo, com esta geração e a condenarão, porque se arrependeram com a pregação de Jonas. E aqui está quem é maior do que Jonas.

[[v42-11-33]]

^<<v42-11-33,33>>^ — Ninguém, depois de acender uma lamparina, a coloca em lugar escondido, nem debaixo de um cesto, mas num lugar em que ilumina bem, a fim de que os que entram vejam a luz.

[[v42-11-34]]

^<<v42-11-34,34>>^ Os olhos são a lâmpada do corpo. Se os seus olhos forem bons, todo o seu corpo será cheio de luz; mas, se forem maus, o seu corpo ficará em trevas.

[[v42-11-35]]

^<<v42-11-35,35>>^ Portanto, tenha cuidado para que a luz que está em você não sejam trevas.

[[v42-11-36]]

^<<v42-11-36,36>>^ Pois, se todo o seu corpo for luminoso, sem ter qualquer parte em trevas, será todo resplandecente como a lamparina quando ilumina você em plena luz.

[[v42-11-37]]

^<<v42-11-37,37>>^ Ao falar Jesus estas palavras, um fariseu o convidou para uma refeição na sua casa. Entrando na casa, Jesus tomou lugar à mesa.

[[v42-11-38]]

^<<v42-11-38,38>>^ O fariseu admirou-se ao ver que Jesus não tinha se lavado antes de comer.

[[v42-11-39]]

^<<v42-11-39,39>>^ Mas o Senhor lhe disse: — Vocês, fariseus, limpam o exterior do copo e do prato; mas o interior de vocês está cheio de roubo e de maldade.

[[v42-11-40]]

^<<v42-11-40,40>>^ Seus tolos! Quem fez o exterior não é o mesmo que fez o interior?

[[v42-11-41]]

^<<v42-11-41,41>>^ Mas deem como esmola o que está dentro do copo e do prato, e tudo lhes será limpo.

[[v42-11-42]]

^<<v42-11-42,42>>^ Mas ai de vocês, fariseus! Porque vocês dão o dízimo da hortelã, da arruda e de todas as hortaliças, e desprezam a justiça e o amor de Deus. Vocês deveriam fazer estas coisas, sem omitir aquelas.

[[v42-11-43]]

^<<v42-11-43,43>>^ Ai de vocês, fariseus! Porque gostam da primeira cadeira nas sinagogas e das saudações nas praças.

[[v42-11-44]]

^<<v42-11-44,44>>^ Ai de vocês que são como as sepulturas invisíveis, sobre as quais as pessoas passam sem perceber!

[[v42-11-45]]

^<<v42-11-45,45>>^ Então, tomando a palavra, um dos intérpretes da Lei disse a Jesus: — Mestre, ao dizer estas coisas o senhor está ofendendo também a nós!

[[v42-11-46]]

^<<v42-11-46,46>>^ Mas Jesus respondeu: — Ai de vocês também, intérpretes da Lei! Porque sobrecarregam os outros com fardos superiores às suas forças, mas vocês nem sequer com um dedo tocam nesses fardos.

[[v42-11-47]]

^<<v42-11-47,47>>^ Ai de vocês! Porque edificam os túmulos dos profetas que os pais de vocês assassinaram.

[[v42-11-48]]

^<<v42-11-48,48>>^ Assim, são testemunhas e aprovam com cumplicidade as obras dos pais de vocês; porque eles mataram os profetas, e vocês edificam túmulos para eles.

[[v42-11-49]]

^<<v42-11-49,49>>^ Por isso, também disse a sabedoria de Deus: "Mandarei para eles profetas e apóstolos, e a alguns deles matarão e a outros perseguirão",

[[v42-11-50]]

^<<v42-11-50,50>>^ para que desta geração se peçam contas do sangue dos profetas, derramado desde a fundação do mundo,

[[v42-11-51]]

^<<v42-11-51,51>>^ desde o sangue de Abel até o sangue de Zacarias, que foi assassinado entre o altar e o santuário. Sim, eu afirmo a vocês que se pedirão contas a esta geração.

[[v42-11-52]]

^<<v42-11-52,52>>^ Ai de vocês, intérpretes da Lei! Porque vocês pegaram a chave do conhecimento. No entanto, vocês mesmos não entraram e impediram os que estavam entrando.

[[v42-11-53]]

^<<v42-11-53,53>>^ Quando Jesus saiu dali, os escribas e fariseus começaram a contestá-lo com veemência, fazendo perguntas a respeito de muitos assuntos,

[[v42-11-54]]

^<<v42-11-54,54>>^ com o objetivo de tirar daquilo que ele dizia um motivo para o acusar.

'''

xref:042-lucas/042-lucas-010.adoc#v42-10-0[&#60; Capítulo Anterior] | <<v42-11-0,Topo>> | xref:042-lucas/042-lucas-012.adoc#v42-12-0[Próximo Capítulo &#62;]