include::./index.adoc[]

[[v42-16-0]]
=== Lucas, 16
// naa ?, NAA - Nova Almeida Atualizada

[[v42-16-1]]

^<<v42-16-1,1>>^ Jesus disse também aos seus discípulos: — Certo homem rico tinha um administrador. Um dia, ele recebeu uma denúncia de que esse administrador estava desperdiçando os bens dele.

[[v42-16-2]]

^<<v42-16-2,2>>^ Então, chamando-o, lhe disse: "Que é isto que ouço a seu respeito? Preste contas da sua administração, porque você não pode mais ser o meu administrador."

[[v42-16-3]]

^<<v42-16-3,3>>^ — O administrador, então, se pôs a pensar: "Que farei, agora que estou sendo demitido pelo meu patrão? Trabalhar na terra, não posso. De mendigar, tenho vergonha.

[[v42-16-4]]

^<<v42-16-4,4>>^ Já sei o que vou fazer, para que, quando for demitido, as pessoas me recebam em suas casas."

[[v42-16-5]]

^<<v42-16-5,5>>^ — Tendo chamado cada um dos devedores do seu patrão, perguntou ao primeiro: "Quanto você deve ao meu patrão?"

[[v42-16-6]]

^<<v42-16-6,6>>^ Ele respondeu: "Cem barris de azeite." Então o administrador disse: "Pegue a sua conta, sente-se depressa e escreva cinquenta."

[[v42-16-7]]

^<<v42-16-7,7>>^ Depois, perguntou a outro: "E você, quanto deve?" Ele respondeu: "Cem sacos de trigo." O administrador lhe disse: "Pegue a sua conta e escreva oitenta."

[[v42-16-8]]

^<<v42-16-8,8>>^ E o patrão elogiou o administrador infiel por sua esperteza. Porque os filhos do mundo são mais espertos na sua própria geração do que os filhos da luz.

[[v42-16-9]]

^<<v42-16-9,9>>^ — E eu recomendo a vocês: usem a riqueza injusta para fazer amigos, para que, quando a riqueza faltar, vocês sejam recebidos nos tabernáculos eternos.

[[v42-16-10]]

^<<v42-16-10,10>>^ — Quem é fiel no pouco também é fiel no muito; e quem é injusto no pouco também é injusto no muito.

[[v42-16-11]]

^<<v42-16-11,11>>^ Portanto, se vocês não forem fiéis na aplicação da riqueza injusta, quem lhes confiará a verdadeira riqueza?

[[v42-16-12]]

^<<v42-16-12,12>>^ Se vocês não são fiéis na aplicação do que é dos outros, quem lhes dará o que é de vocês?

[[v42-16-13]]

^<<v42-16-13,13>>^ Nenhum servo pode servir a dois senhores; porque irá odiar um e amar o outro ou irá se dedicar a um e desprezar o outro. Vocês não podem servir a Deus e à riqueza.

[[v42-16-14]]

^<<v42-16-14,14>>^ Os fariseus, que eram avarentos, ouviam tudo isto e zombavam de Jesus.

[[v42-16-15]]

^<<v42-16-15,15>>^ Mas Jesus lhes disse: — Vocês são os que se justificam diante dos homens, mas Deus conhece o coração de vocês; pois aquilo que é elevado entre homens é abominação diante de Deus.

[[v42-16-16]]

^<<v42-16-16,16>>^ — A Lei e os Profetas duraram até João; desde esse tempo o evangelho do Reino de Deus vem sendo anunciado, e todos se esforçam para entrar nele.

[[v42-16-17]]

^<<v42-16-17,17>>^ E é mais fácil passar o céu e a terra do que cair um til sequer da Lei.

[[v42-16-18]]

^<<v42-16-18,18>>^ — Quem repudiar a sua mulher e casar com outra comete adultério; e aquele que casa com a mulher repudiada pelo marido também comete adultério.

[[v42-16-19]]

^<<v42-16-19,19>>^ — Ora, havia certo homem rico que se vestia de púrpura e de linho finíssimo e que se alegrava todos os dias com grande ostentação.

[[v42-16-20]]

^<<v42-16-20,20>>^ Havia também certo mendigo, chamado Lázaro, coberto de feridas, que ficava deitado à porta da casa do rico.

[[v42-16-21]]

^<<v42-16-21,21>>^ Ele desejava alimentar-se das migalhas que caíam da mesa do rico, e até os cães vinham lamber-lhe as feridas.

[[v42-16-22]]

^<<v42-16-22,22>>^ E aconteceu que o mendigo morreu e foi levado pelos anjos para junto de Abraão. Morreu também o rico e foi sepultado.

[[v42-16-23]]

^<<v42-16-23,23>>^ — No inferno, estando em tormentos, o rico levantou os olhos e viu ao longe Abraão, e Lázaro junto dele.

[[v42-16-24]]

^<<v42-16-24,24>>^ Então, gritando, disse: "Pai Abraão, tenha misericórdia de mim! E mande que Lázaro molhe a ponta do dedo em água e me refresque a língua, porque estou atormentado neste fogo."

[[v42-16-25]]

^<<v42-16-25,25>>^ Mas Abraão disse: "Filho, lembre-se de que você recebeu os seus bens durante a sua vida, enquanto Lázaro só teve males. Agora, porém, ele está consolado aqui, enquanto você está em tormentos.

[[v42-16-26]]

^<<v42-16-26,26>>^ E, além de tudo, há um grande abismo entre nós e vocês, de modo que os que querem passar daqui até vocês não podem, nem os de lá passar para cá."

[[v42-16-27]]

^<<v42-16-27,27>>^ Então o rico disse: "Pai, eu peço que mande Lázaro à minha casa paterna,

[[v42-16-28]]

^<<v42-16-28,28>>^ porque tenho cinco irmãos; para que lhes dê testemunho, a fim de que não venham também para este lugar de tormento."

[[v42-16-29]]

^<<v42-16-29,29>>^ Abraão respondeu: "Eles têm Moisés e os Profetas; ouçam-nos."

[[v42-16-30]]

^<<v42-16-30,30>>^ Mas ele insistiu: "Não, pai Abraão; se alguém dentre os mortos for até lá, eles irão se arrepender."

[[v42-16-31]]

^<<v42-16-31,31>>^ Abraão, porém, lhe respondeu: "Se não ouvem Moisés e os Profetas, também não se deixarão convencer, mesmo que ressuscite alguém dentre os mortos."

'''

xref:042-lucas/042-lucas-015.adoc#v42-15-0[&#60; Capítulo Anterior] | <<v42-16-0,Topo>> | xref:042-lucas/042-lucas-017.adoc#v42-17-0[Próximo Capítulo &#62;]