include::./index.adoc[]

[[v42-9-0]]
=== Lucas, 9
// naa ?, NAA - Nova Almeida Atualizada

[[v42-9-1]]

^<<v42-9-1,1>>^ Tendo Jesus convocado os doze, deu-lhes poder e autoridade sobre todos os demônios e para curar doenças.

[[v42-9-2]]

^<<v42-9-2,2>>^ Também os enviou a pregar o Reino de Deus e a curar os enfermos.

[[v42-9-3]]

^<<v42-9-3,3>>^ E disse-lhes: — Não levem nada para o caminho: nem bordão, nem sacola, nem pão, nem dinheiro; vocês também não devem ter duas túnicas.

[[v42-9-4]]

^<<v42-9-4,4>>^ Na casa em que vocês entrarem, fiquem ali até saírem daquele lugar.

[[v42-9-5]]

^<<v42-9-5,5>>^ E onde quer que não receberem vocês, ao saírem daquela cidade sacudam o pó dos pés em testemunho contra eles.

[[v42-9-6]]

^<<v42-9-6,6>>^ Então, saindo, percorriam todas as aldeias, anunciando o evangelho e fazendo curas por toda parte.

[[v42-9-7]]

^<<v42-9-7,7>>^ Ora, o tetrarca Herodes soube de tudo o que se passava e ficou perplexo, porque alguns diziam: "João ressuscitou dentre os mortos."

[[v42-9-8]]

^<<v42-9-8,8>>^ Outros diziam: "Elias apareceu." E ainda outros diziam: "Um dos antigos profetas ressuscitou."

[[v42-9-9]]

^<<v42-9-9,9>>^ Herodes, porém, disse: — Eu mandei decapitar João. Quem, então, é este a respeito do qual tenho ouvido tais coisas? E se esforçava para vê-lo.

[[v42-9-10]]

^<<v42-9-10,10>>^ Ao regressarem, os apóstolos relataram a Jesus tudo o que tinham feito. Ele, levando-os consigo, retirou-se à parte para uma cidade chamada Betsaida.

[[v42-9-11]]

^<<v42-9-11,11>>^ Mas as multidões souberam disso e o seguiram. Acolhendo-as, Jesus lhes falava a respeito do Reino de Deus e socorria os que tinham necessidade de cura.

[[v42-9-12]]

^<<v42-9-12,12>>^ Mas o dia estava chegando ao fim. Então os doze se aproximaram de Jesus e disseram: — Despeça a multidão, para que, indo às aldeias e campos ao redor, se hospedem e encontrem alimento; pois estamos aqui em lugar deserto.

[[v42-9-13]]

^<<v42-9-13,13>>^ Jesus, porém, lhes disse: — Deem vocês mesmos de comer a eles. Os discípulos responderam: — Não temos mais que cinco pães e dois peixes, a não ser que nós mesmos vamos e compremos comida para todo este povo.

[[v42-9-14]]

^<<v42-9-14,14>>^ Porque estavam ali cerca de cinco mil homens. Então Jesus disse aos seus discípulos: — Façam com que se assentem em grupos de cinquenta.

[[v42-9-15]]

^<<v42-9-15,15>>^ Eles atenderam, fazendo com que todos se assentassem.

[[v42-9-16]]

^<<v42-9-16,16>>^ E Jesus, pegando os cinco pães e os dois peixes, erguendo os olhos para o céu, os abençoou, partiu e deu aos discípulos para que os distribuíssem entre o povo.

[[v42-9-17]]

^<<v42-9-17,17>>^ Todos comeram e se fartaram; e dos pedaços que sobraram foram recolhidos doze cestos.

[[v42-9-18]]

^<<v42-9-18,18>>^ E aconteceu que, enquanto Jesus estava orando em particular, achavam-se presentes os discípulos, a quem perguntou: — Quem as multidões dizem que eu sou?

[[v42-9-19]]

^<<v42-9-19,19>>^ Eles responderam: — Uns dizem que é João Batista; outros dizem que é Elias; e ainda outros dizem que um dos antigos profetas ressuscitou.

[[v42-9-20]]

^<<v42-9-20,20>>^ Então Jesus perguntou: — E vocês, quem dizem que eu sou? Respondendo, Pedro disse: — O Cristo de Deus.

[[v42-9-21]]

^<<v42-9-21,21>>^ Jesus, porém, advertindo-os, mandou que a ninguém declarassem tal coisa,

[[v42-9-22]]

^<<v42-9-22,22>>^ dizendo: — É necessário que o Filho do Homem sofra muitas coisas, seja rejeitado pelos anciãos, pelos principais sacerdotes e pelos escribas, seja morto e, no terceiro dia, ressuscite.

[[v42-9-23]]

^<<v42-9-23,23>>^ Jesus dizia a todos: — Se alguém quer vir após mim, negue a si mesmo, dia a dia tome a sua cruz e siga-me.

[[v42-9-24]]

^<<v42-9-24,24>>^ Pois quem quiser salvar a sua vida a perderá; e quem perder a vida por minha causa, esse a salvará.

[[v42-9-25]]

^<<v42-9-25,25>>^ De que adianta uma pessoa ganhar o mundo inteiro, se vier a perder-se ou causar dano a si mesma?

[[v42-9-26]]

^<<v42-9-26,26>>^ Pois quem se envergonhar de mim e das minhas palavras, dele se envergonhará o Filho do Homem, quando vier na sua glória e na glória do Pai e dos santos anjos.

[[v42-9-27]]

^<<v42-9-27,27>>^ Em verdade lhes digo que alguns dos que aqui se encontram não passarão pela morte até que vejam o Reino de Deus.

[[v42-9-28]]

^<<v42-9-28,28>>^ Cerca de oito dias depois de proferidas estas palavras, Jesus levou consigo Pedro, João e Tiago e subiu ao monte com o propósito de orar.

[[v42-9-29]]

^<<v42-9-29,29>>^ E aconteceu que, enquanto ele orava, a aparência do seu rosto se transfigurou e a roupa dele ficou de um branco brilhante.

[[v42-9-30]]

^<<v42-9-30,30>>^ E eis que dois homens falavam com ele: eram Moisés e Elias,

[[v42-9-31]]

^<<v42-9-31,31>>^ que apareceram em glória e falavam da morte de Jesus, que ele estava para cumprir em Jerusalém.

[[v42-9-32]]

^<<v42-9-32,32>>^ Pedro e seus companheiros estavam caindo de sono; mas, conservando-se acordados, viram a glória de Jesus e os dois homens que estavam com ele.

[[v42-9-33]]

^<<v42-9-33,33>>^ Quando estes começaram a se afastar de Jesus, Pedro lhe disse: — Mestre, bom é estarmos aqui. Façamos três tendas: uma para o senhor, outra para Moisés e outra para Elias. Porém, Pedro não sabia o que estava dizendo.

[[v42-9-34]]

^<<v42-9-34,34>>^ Enquanto assim falava, veio uma nuvem e os envolveu. E ficaram com medo ao entrar na nuvem.

[[v42-9-35]]

^<<v42-9-35,35>>^ E dela veio uma voz que dizia: — Este é o meu Filho, o meu eleito; escutem o que ele diz!

[[v42-9-36]]

^<<v42-9-36,36>>^ Depois daquela voz, perceberam que Jesus estava sozinho. Eles ficaram calados e, naqueles dias, não contaram nada a ninguém a respeito do que tinham visto.

[[v42-9-37]]

^<<v42-9-37,37>>^ No dia seguinte, quando eles desceram do monte, uma grande multidão veio ao encontro de Jesus.

[[v42-9-38]]

^<<v42-9-38,38>>^ E eis que, do meio da multidão, surgiu um homem, dizendo em alta voz: — Mestre, peço que o senhor olhe o meu filho, porque é o único que tenho.

[[v42-9-39]]

^<<v42-9-39,39>>^ Um espírito se apodera dele, e, de repente, o menino grita, e o espírito o convulsiona até espumar; e dificilmente o deixa, depois de o ter maltratado.

[[v42-9-40]]

^<<v42-9-40,40>>^ Pedi aos seus discípulos que o expulsassem, mas eles não puderam.

[[v42-9-41]]

^<<v42-9-41,41>>^ Jesus exclamou: — Ó geração incrédula e perversa! Até quando estarei com vocês e terei de suportá-los? Traga o seu filho aqui.

[[v42-9-42]]

^<<v42-9-42,42>>^ Quando o menino estava se aproximando, o demônio o atirou no chão e o convulsionou; mas Jesus repreendeu o espírito imundo, curou o menino e o entregou ao pai.

[[v42-9-43]]

^<<v42-9-43,43>>^ E todos ficaram maravilhados com a majestade de Deus. Como todos estavam admirados com tudo o que Jesus fazia, ele disse aos seus discípulos:

[[v42-9-44]]

^<<v42-9-44,44>>^ — Prestem bem atenção nas seguintes palavras: o Filho do Homem está para ser entregue nas mãos dos homens.

[[v42-9-45]]

^<<v42-9-45,45>>^ Eles, porém, não entendiam isso, e lhes foi encoberto para que não o compreendessem. E temiam fazer perguntas a Jesus a respeito deste assunto.

[[v42-9-46]]

^<<v42-9-46,46>>^ Surgiu entre os discípulos uma discussão sobre qual deles seria o maior.

[[v42-9-47]]

^<<v42-9-47,47>>^ Mas Jesus, sabendo o que se passava no coração deles, pegou uma criança, colocou-a junto de si

[[v42-9-48]]

^<<v42-9-48,48>>^ e lhes disse: — Quem receber esta criança em meu nome é a mim que recebe; e quem receber a mim recebe aquele que me enviou; porque aquele que for o menor de todos entre vocês, esse é que é grande.

[[v42-9-49]]

^<<v42-9-49,49>>^ João tomou a palavra e disse: — Mestre, vimos certo homem que expulsava demônios em seu nome, mas nós o proibimos de fazer isso, porque não segue conosco.

[[v42-9-50]]

^<<v42-9-50,50>>^ Mas Jesus lhe disse: — Não proíbam, pois quem não é contra vocês é a favor de vocês.

[[v42-9-51]]

^<<v42-9-51,51>>^ E aconteceu que, ao se completarem os dias em que seria elevado ao céu, Jesus manifestou, no semblante, a firme resolução de ir para Jerusalém.

[[v42-9-52]]

^<<v42-9-52,52>>^ E enviou mensageiros que fossem na frente. Indo eles, entraram numa aldeia de samaritanos para lhe preparar pousada.

[[v42-9-53]]

^<<v42-9-53,53>>^ Mas não o receberam, porque o aspecto dele era de quem, decisivamente, ia para Jerusalém.

[[v42-9-54]]

^<<v42-9-54,54>>^ Vendo isto, os discípulos Tiago e João perguntaram: — Senhor, quer que mandemos descer fogo do céu para os consumir?

[[v42-9-55]]

^<<v42-9-55,55>>^ Mas Jesus, voltando-se, os repreendeu.

[[v42-9-56]]

^<<v42-9-56,56>>^ E seguiram para outra aldeia.

[[v42-9-57]]

^<<v42-9-57,57>>^ Enquanto seguiam pelo caminho, alguém disse a Jesus: — Vou segui-lo para onde quer que o senhor for.

[[v42-9-58]]

^<<v42-9-58,58>>^ Mas Jesus lhe respondeu: — As raposas têm as suas tocas e as aves do céu têm os seus ninhos, mas o Filho do Homem não tem onde reclinar a cabeça.

[[v42-9-59]]

^<<v42-9-59,59>>^ A outro Jesus disse: — Siga-me! Mas ele respondeu: — Senhor, deixe-me ir primeiro sepultar o meu pai.

[[v42-9-60]]

^<<v42-9-60,60>>^ Mas Jesus insistiu: — Deixe que os mortos sepultem os seus mortos. Você, porém, vá e anuncie o Reino de Deus.

[[v42-9-61]]

^<<v42-9-61,61>>^ Outro lhe disse: — Senhor, quero segui-lo, mas permita que antes disso eu me despeça das pessoas da minha casa.

[[v42-9-62]]

^<<v42-9-62,62>>^ Mas Jesus lhe respondeu: — Ninguém que põe a mão no arado e olha para trás é apto para o Reino de Deus.

'''

xref:042-lucas/042-lucas-008.adoc#v42-8-0[&#60; Capítulo Anterior] | <<v42-9-0,Topo>> | xref:042-lucas/042-lucas-010.adoc#v42-10-0[Próximo Capítulo &#62;]