include::./index.adoc[]

[[v42-6-0]]
=== Lucas, 6
// naa ?, NAA - Nova Almeida Atualizada

[[v42-6-1]]

^<<v42-6-1,1>>^ Aconteceu que, num sábado, Jesus passava pelas searas, e os seus discípulos colhiam e comiam espigas, debulhando-as com as mãos.

[[v42-6-2]]

^<<v42-6-2,2>>^ E alguns dos fariseus lhes disseram: — Por que vocês fazem o que não é lícito aos sábados?

[[v42-6-3]]

^<<v42-6-3,3>>^ Jesus tomou a palavra e disse: — Vocês nem ao menos leram o que Davi fez quando teve fome, ele e os seus companheiros?

[[v42-6-4]]

^<<v42-6-4,4>>^ Como entrou na casa de Deus e, pegando os pães da proposição, comeu e deu também aos que estavam com ele, pães que não lhes era lícito comer, mas exclusivamente aos sacerdotes?

[[v42-6-5]]

^<<v42-6-5,5>>^ Então Jesus lhes disse: — O Filho do Homem é senhor do sábado.

[[v42-6-6]]

^<<v42-6-6,6>>^ Aconteceu que, em outro sábado, Jesus entrou na sinagoga e começou a ensinar. Estava ali um homem que tinha a mão direita ressequida.

[[v42-6-7]]

^<<v42-6-7,7>>^ Os escribas e os fariseus observavam Jesus, procurando ver se ele faria uma cura no sábado, a fim de acharem de que o acusar.

[[v42-6-8]]

^<<v42-6-8,8>>^ Mas Jesus, conhecendo os pensamentos deles, disse ao homem da mão ressequida: — Levante-se e venha para o meio. E ele, levantando-se, ficou em pé.

[[v42-6-9]]

^<<v42-6-9,9>>^ Então Jesus disse a eles: — Vou fazer uma pergunta a vocês: é lícito no sábado fazer o bem ou fazer o mal? Salvar uma vida ou deixar que se perca?

[[v42-6-10]]

^<<v42-6-10,10>>^ Então Jesus, olhando para todos que estavam ao seu redor, disse ao homem: — Estenda a mão! Ele assim o fez, e a mão lhe foi restaurada.

[[v42-6-11]]

^<<v42-6-11,11>>^ Mas eles se encheram de furor e discutiam entre si quanto ao que fariam contra Jesus.

[[v42-6-12]]

^<<v42-6-12,12>>^ Naqueles dias, Jesus se retirou para o monte, a fim de orar, e passou a noite orando a Deus.

[[v42-6-13]]

^<<v42-6-13,13>>^ E, quando amanheceu, chamou a si os seus discípulos e escolheu doze dentre eles, aos quais deu também o nome de apóstolos:

[[v42-6-14]]

^<<v42-6-14,14>>^ Simão, a quem acrescentou o nome de Pedro, e André, seu irmão; Tiago e João; Filipe e Bartolomeu;

[[v42-6-15]]

^<<v42-6-15,15>>^ Mateus e Tomé; Tiago, filho de Alfeu, e Simão, chamado Zelote;

[[v42-6-16]]

^<<v42-6-16,16>>^ Judas, filho de Tiago, e Judas Iscariotes, que se tornou traidor.

[[v42-6-17]]

^<<v42-6-17,17>>^ E, descendo com eles do monte, Jesus parou num lugar plano onde se encontravam muitos discípulos seus e grande multidão do povo, de toda a Judeia, de Jerusalém e do litoral de Tiro e de Sidom,

[[v42-6-18]]

^<<v42-6-18,18>>^ que vieram para o ouvir e para ser curados de suas doenças. Também os atormentados por espíritos imundos eram curados.

[[v42-6-19]]

^<<v42-6-19,19>>^ E todos da multidão procuravam tocar em Jesus, porque dele saía poder; e curava todos.

[[v42-6-20]]

^<<v42-6-20,20>>^ Então, olhando para os seus discípulos, Jesus lhes disse: — Bem-aventurados são vocês, os pobres, porque o Reino de Deus é de vocês.

[[v42-6-21]]

^<<v42-6-21,21>>^ — Bem-aventurados são vocês que agora têm fome, porque serão saciados. — Bem-aventurados são vocês que agora choram, porque vocês hão de rir.

[[v42-6-22]]

^<<v42-6-22,22>>^ — Bem-aventurados são vocês quando as pessoas os odiarem, expulsarem da sua companhia, insultarem e rejeitarem o nome de vocês como indigno, por causa do Filho do Homem.

[[v42-6-23]]

^<<v42-6-23,23>>^ Alegrem-se naquele dia e exultem, porque grande é a recompensa de vocês no céu; porque os pais dessas pessoas fizeram o mesmo com os profetas.

[[v42-6-24]]

^<<v42-6-24,24>>^ — Mas ai de vocês, os ricos, porque vocês já receberam a consolação!

[[v42-6-25]]

^<<v42-6-25,25>>^ — Ai de vocês que agora estão fartos, porque vocês vão passar fome! — Ai de vocês que agora estão rindo, porque vocês vão lamentar e chorar!

[[v42-6-26]]

^<<v42-6-26,26>>^ — Ai de vocês, quando todos os elogiarem, porque os pais dessas pessoas fizeram o mesmo com os falsos profetas!

[[v42-6-27]]

^<<v42-6-27,27>>^ — Digo, porém, a vocês que me ouvem: amem os seus inimigos, façam o bem aos que odeiam vocês.

[[v42-6-28]]

^<<v42-6-28,28>>^ Abençoem aqueles que os amaldiçoam, orem pelos que maltratam vocês.

[[v42-6-29]]

^<<v42-6-29,29>>^ Ao que lhe bate numa face, ofereça também a outra; e, ao que lhe tirar a capa, deixe que leve também a túnica.

[[v42-6-30]]

^<<v42-6-30,30>>^ Dê a todo o que lhe pedir alguma coisa; e, se alguém levar o que é seu, não exija que seja devolvido.

[[v42-6-31]]

^<<v42-6-31,31>>^ Façam aos outros o mesmo que vocês querem que eles façam a vocês.

[[v42-6-32]]

^<<v42-6-32,32>>^ — Se vocês amam aqueles que os amam, que recompensa terão? Porque até os pecadores amam aqueles que os amam.

[[v42-6-33]]

^<<v42-6-33,33>>^ Se fizerem o bem aos que lhes fazem o bem, que recompensa terão? Até os pecadores fazem isso.

[[v42-6-34]]

^<<v42-6-34,34>>^ E, se emprestam àqueles de quem esperam receber, que recompensa terão? Também os pecadores emprestam aos pecadores, para receberem outro tanto.

[[v42-6-35]]

^<<v42-6-35,35>>^ Vocês, porém, amem os seus inimigos, façam o bem e emprestem, sem esperar nada em troca; vocês terão uma grande recompensa e serão filhos do Altíssimo. Pois ele é bondoso até para os ingratos e maus.

[[v42-6-36]]

^<<v42-6-36,36>>^ Sejam misericordiosos, como também é misericordioso o Pai de vocês.

[[v42-6-37]]

^<<v42-6-37,37>>^ — Não julguem e vocês não serão julgados; não condenem e vocês não serão condenados; perdoem e serão perdoados;

[[v42-6-38]]

^<<v42-6-38,38>>^ deem e lhes será dado; boa medida, prensada, sacudida e transbordante será dada a vocês; porque com a medida com que tiverem medido vocês serão medidos também.

[[v42-6-39]]

^<<v42-6-39,39>>^ Jesus lhes contou também uma parábola: — Será que um cego pode guiar outro cego? Não é fato que ambos cairão num buraco?

[[v42-6-40]]

^<<v42-6-40,40>>^ — O discípulo não está acima do seu mestre; todo aquele, porém, que for bem-instruído será como o seu mestre.

[[v42-6-41]]

^<<v42-6-41,41>>^ — Por que você vê o cisco no olho do seu irmão, mas não repara na trave que está no seu próprio olho?

[[v42-6-42]]

^<<v42-6-42,42>>^ Como você poderá dizer a seu irmão: "Deixe, irmão, que eu tire o cisco que está no seu olho", se você não repara na trave que está no seu próprio olho? Hipócrita! Tire primeiro a trave do seu olho e então você verá claramente para tirar o cisco que está no olho do seu irmão.

[[v42-6-43]]

^<<v42-6-43,43>>^ — Não há árvore boa que dê mau fruto, nem árvore má que dê bom fruto.

[[v42-6-44]]

^<<v42-6-44,44>>^ Porque cada árvore é conhecida pelos frutos que produz. Porque não se colhem figos de ervas daninhas, nem se apanham uvas dos espinheiros.

[[v42-6-45]]

^<<v42-6-45,45>>^ A pessoa boa tira o bem do bom tesouro do coração, e a pessoa má tira o mal do mau tesouro; porque a boca fala do que está cheio o coração.

[[v42-6-46]]

^<<v42-6-46,46>>^ — Por que vocês me chamam "Senhor, Senhor!", e não fazem o que eu mando?

[[v42-6-47]]

^<<v42-6-47,47>>^ Eu vou mostrar a vocês a quem é semelhante todo aquele que vem a mim, ouve as minhas palavras e as pratica.

[[v42-6-48]]

^<<v42-6-48,48>>^ Esse é semelhante a um homem que, ao construir uma casa, cavou, abriu profunda vala e lançou o alicerce sobre a rocha. Quando veio a enchente, as águas bateram contra aquela casa e não a puderam abalar, por ter sido bem-construída.

[[v42-6-49]]

^<<v42-6-49,49>>^ Mas o que ouve e não pratica é semelhante a um homem que construiu uma casa sobre a terra, sem alicerces, e, quando as águas bateram contra ela, logo desabou; e aconteceu que foi grande a ruína daquela casa.

'''

xref:042-lucas/042-lucas-005.adoc#v42-5-0[&#60; Capítulo Anterior] | <<v42-6-0,Topo>> | xref:042-lucas/042-lucas-007.adoc#v42-7-0[Próximo Capítulo &#62;]