include::./index.adoc[]

[[v42-13-0]]
=== Lucas, 13
// naa ?, NAA - Nova Almeida Atualizada

[[v42-13-1]]

^<<v42-13-1,1>>^ Naquela mesma ocasião, estavam ali algumas pessoas que falaram para Jesus a respeito dos galileus cujo sangue Pilatos havia misturado com os sacrifícios que os mesmos realizavam.

[[v42-13-2]]

^<<v42-13-2,2>>^ Então Jesus lhes disse: — Vocês pensam que esses galileus eram mais pecadores do que todos os outros galileus, por terem padecido estas coisas?

[[v42-13-3]]

^<<v42-13-3,3>>^ Digo a vocês que não eram; se, porém, não se arrependerem, todos vocês também perecerão.

[[v42-13-4]]

^<<v42-13-4,4>>^ E, quanto àqueles dezoito sobre os quais desabou a torre de Siloé e os matou, vocês pensam que eles eram mais culpados do que todos os outros moradores de Jerusalém?

[[v42-13-5]]

^<<v42-13-5,5>>^ Digo a vocês que não eram; mas, se não se arrependerem, todos vocês também perecerão.

[[v42-13-6]]

^<<v42-13-6,6>>^ E Jesus contou a seguinte parábola: — Certo homem tinha uma figueira plantada na sua vinha e, vindo procurar fruto nela, não achou.

[[v42-13-7]]

^<<v42-13-7,7>>^ Então disse ao homem que cuidava da vinha: "Já faz três anos que venho procurar fruto nesta figueira e não encontro nada. Portanto, corte-a! Por que ela ainda está ocupando inutilmente a terra?"

[[v42-13-8]]

^<<v42-13-8,8>>^ Mas o homem que cuidava da vinha respondeu: "Senhor, deixe-a ainda este ano, até que eu escave ao redor dela e ponha estrume.

[[v42-13-9]]

^<<v42-13-9,9>>^ Se vier a dar fruto, muito bem. Se não der fruto, o senhor poderá cortá-la."

[[v42-13-10]]

^<<v42-13-10,10>>^ Num sábado, Jesus estava ensinando numa das sinagogas.

[[v42-13-11]]

^<<v42-13-11,11>>^ E chegou ali uma mulher possuída de um espírito de enfermidade, havia já dezoito anos; ela andava encurvada, sem poder se endireitar de modo nenhum.

[[v42-13-12]]

^<<v42-13-12,12>>^ Ao vê-la, Jesus a chamou e lhe disse: — Mulher, você está livre da sua enfermidade.

[[v42-13-13]]

^<<v42-13-13,13>>^ E, impondo-lhe as mãos, ela imediatamente se endireitou e dava glória a Deus.

[[v42-13-14]]

^<<v42-13-14,14>>^ O chefe da sinagoga, indignado por ver que Jesus curava no sábado, disse à multidão: — Há seis dias em que se deve trabalhar. Venham nesses dias para serem curados, mas não no sábado.

[[v42-13-15]]

^<<v42-13-15,15>>^ Porém o Senhor lhe respondeu: — Hipócritas! Cada um de vocês não desprende da manjedoura, no sábado, o seu boi ou o seu jumento, para levá-lo a beber?

[[v42-13-16]]

^<<v42-13-16,16>>^ Por que motivo não se devia livrar deste cativeiro, em dia de sábado, esta filha de Abraão, a quem Satanás trazia presa há dezoito anos?

[[v42-13-17]]

^<<v42-13-17,17>>^ Tendo Jesus dito estas palavras, todos os seus adversários ficaram envergonhados. Entretanto, o povo se alegrava por todos os feitos gloriosos que Jesus realizava.

[[v42-13-18]]

^<<v42-13-18,18>>^ Jesus disse: — A que é semelhante o Reino de Deus, e a que o compararei?

[[v42-13-19]]

^<<v42-13-19,19>>^ É semelhante a um grão de mostarda, que um homem plantou na sua horta; e cresceu e fez-se árvore; e as aves do céu se aninharam nos seus ramos.

[[v42-13-20]]

^<<v42-13-20,20>>^ Disse mais: — A que compararei o Reino de Deus?

[[v42-13-21]]

^<<v42-13-21,21>>^ É semelhante ao fermento que uma mulher pegou e misturou em três medidas de farinha, até ficar tudo levedado.

[[v42-13-22]]

^<<v42-13-22,22>>^ Jesus passava por cidades e aldeias, ensinando e caminhando para Jerusalém.

[[v42-13-23]]

^<<v42-13-23,23>>^ E alguém lhe perguntou: — Senhor, são poucos os que são salvos?

[[v42-13-24]]

^<<v42-13-24,24>>^ Jesus respondeu: — Esforcem-se por entrar pela porta estreita! Pois eu afirmo a vocês que muitos procurarão entrar, mas não conseguirão.

[[v42-13-25]]

^<<v42-13-25,25>>^ Quando o dono da casa se tiver levantado e fechado a porta, e vocês, do lado de fora, começarem a bater, dizendo: "Senhor, abra a porta para nós", ele responderá: "Não sei de onde vocês são."

[[v42-13-26]]

^<<v42-13-26,26>>^ Então vocês dirão: "Comíamos e bebíamos com o senhor. Além disso, o senhor ensinava em nossas ruas."

[[v42-13-27]]

^<<v42-13-27,27>>^ Mas ele dirá a vocês: "Não sei de onde vocês são; afastem-se de mim, vocês todos que praticam o mal."

[[v42-13-28]]

^<<v42-13-28,28>>^ Ali haverá choro e ranger de dentes, quando vocês virem Abraão, Isaque, Jacó e todos os profetas no Reino de Deus, mas vocês lançados fora.

[[v42-13-29]]

^<<v42-13-29,29>>^ Muitos virão do Oriente e do Ocidente, do Norte e do Sul e tomarão lugar à mesa no Reino de Deus.

[[v42-13-30]]

^<<v42-13-30,30>>^ Porém, de fato, há últimos que serão primeiros, e primeiros que serão últimos.

[[v42-13-31]]

^<<v42-13-31,31>>^ Naquela mesma hora, alguns fariseus vieram para dizer a Jesus: — Vá embora daqui, porque Herodes quer matá-lo.

[[v42-13-32]]

^<<v42-13-32,32>>^ Ele, porém, lhes respondeu: — Vão e digam a essa raposa que hoje e amanhã expulso demônios e curo doentes, e no terceiro dia terminarei.

[[v42-13-33]]

^<<v42-13-33,33>>^ Porém, preciso caminhar hoje, amanhã e depois, porque não se espera que um profeta morra fora de Jerusalém.

[[v42-13-34]]

^<<v42-13-34,34>>^ — Jerusalém, Jerusalém! Você mata os profetas e apedreja os que lhe são enviados! Quantas vezes eu quis reunir os seus filhos, como a galinha ajunta os do seu próprio ninho debaixo das asas, mas vocês não quiseram!

[[v42-13-35]]

^<<v42-13-35,35>>^ Eis que a casa de vocês ficará deserta. E eu afirmo a vocês que não me verão mais, até que venham a dizer: "Bendito o que vem em nome do Senhor!"

'''

xref:042-lucas/042-lucas-012.adoc#v42-12-0[&#60; Capítulo Anterior] | <<v42-13-0,Topo>> | xref:042-lucas/042-lucas-014.adoc#v42-14-0[Próximo Capítulo &#62;]