include::./index.adoc[]

[[v42-1-0]]
=== Lucas, 1
// naa ?, NAA - Nova Almeida Atualizada

[[v42-1-1]]

^<<v42-1-1,1>>^ Visto que muitos já empreenderam uma narração coordenada dos fatos que entre nós se realizaram,

[[v42-1-2]]

^<<v42-1-2,2>>^ conforme nos transmitiram os que desde o princípio foram deles testemunhas oculares e ministros da palavra,

[[v42-1-3]]

^<<v42-1-3,3>>^ igualmente a mim pareceu bem, depois de cuidadosa investigação de tudo desde a sua origem, dar-lhe por escrito, excelentíssimo Teófilo, uma exposição em ordem,

[[v42-1-4]]

^<<v42-1-4,4>>^ para que você tenha plena certeza das verdades em que foi instruído.

[[v42-1-5]]

^<<v42-1-5,5>>^ Nos dias de Herodes, rei da Judeia, houve um sacerdote chamado Zacarias, do turno de Abias. A mulher dele era das filhas de Arão e se chamava Isabel.

[[v42-1-6]]

^<<v42-1-6,6>>^ Ambos eram justos diante de Deus, vivendo de forma irrepreensível em todos os preceitos e mandamentos do Senhor.

[[v42-1-7]]

^<<v42-1-7,7>>^ Eles não tinham filhos, porque Isabel era estéril, e os dois já tinham idade avançada.

[[v42-1-8]]

^<<v42-1-8,8>>^ E aconteceu que, enquanto Zacarias exercia o sacerdócio diante de Deus na ordem do seu turno, coube-lhe por sorteio,

[[v42-1-9]]

^<<v42-1-9,9>>^ segundo o costume sacerdotal, entrar no santuário do Senhor para queimar o incenso.

[[v42-1-10]]

^<<v42-1-10,10>>^ Durante esse tempo, toda a multidão do povo permanecia na parte de fora, orando.

[[v42-1-11]]

^<<v42-1-11,11>>^ E eis que apareceu a Zacarias um anjo do Senhor, em pé, à direita do altar do incenso.

[[v42-1-12]]

^<<v42-1-12,12>>^ Ao vê-lo, Zacarias ficou assustado, e o temor se apoderou dele.

[[v42-1-13]]

^<<v42-1-13,13>>^ O anjo, porém, lhe disse: — Não tenha medo, Zacarias, porque a sua oração foi ouvida. Isabel, sua esposa, dará à luz um filho, a quem você dará o nome de João.

[[v42-1-14]]

^<<v42-1-14,14>>^ Você ficará alegre e feliz, e muitos ficarão contentes com o nascimento dele.

[[v42-1-15]]

^<<v42-1-15,15>>^ Pois ele será grande diante do Senhor, não beberá vinho nem bebida forte, e será cheio do Espírito Santo, já desde o ventre materno.

[[v42-1-16]]

^<<v42-1-16,16>>^ Ele converterá muitos dos filhos de Israel ao Senhor, seu Deus.

[[v42-1-17]]

^<<v42-1-17,17>>^ E irá adiante do Senhor no espírito e poder de Elias, para converter o coração dos pais aos filhos, converter os desobedientes à prudência dos justos e habilitar para o Senhor um povo preparado.

[[v42-1-18]]

^<<v42-1-18,18>>^ Então Zacarias perguntou ao anjo: — Como terei certeza disso? Pois eu sou velho, e a minha mulher também já tem idade avançada.

[[v42-1-19]]

^<<v42-1-19,19>>^ O anjo respondeu: — Eu sou Gabriel, que estou a serviço de Deus, e fui enviado para falar com você e lhe trazer esta boa notícia.

[[v42-1-20]]

^<<v42-1-20,20>>^ Todavia, você ficará mudo e não poderá falar até o dia em que estas coisas vierem a acontecer, porque você não acreditou nas minhas palavras, as quais, no devido tempo, se cumprirão.

[[v42-1-21]]

^<<v42-1-21,21>>^ O povo estava esperando Zacarias e admirava-se com a demora dele no santuário.

[[v42-1-22]]

^<<v42-1-22,22>>^ Quando Zacarias saiu, não lhes podia falar. Então entenderam que ele havia tido uma visão no santuário. E expressava-se por sinais e permanecia mudo.

[[v42-1-23]]

^<<v42-1-23,23>>^ Aconteceu que, terminados os dias do seu ministério, Zacarias voltou para casa.

[[v42-1-24]]

^<<v42-1-24,24>>^ Passados esses dias, Isabel, a mulher de Zacarias, ficou grávida. E ela não saiu de casa durante cinco meses, dizendo:

[[v42-1-25]]

^<<v42-1-25,25>>^ — Foi isto o que o Senhor me fez, ao contemplar-me, para acabar com a minha vergonha diante das pessoas.

[[v42-1-26]]

^<<v42-1-26,26>>^ No sexto mês, o anjo Gabriel foi enviado por Deus a uma cidade da Galileia, chamada Nazaré,

[[v42-1-27]]

^<<v42-1-27,27>>^ a uma virgem que estava comprometida a casar com um homem da casa de Davi, cujo nome era José. A virgem se chamava Maria.

[[v42-1-28]]

^<<v42-1-28,28>>^ E, aproximando-se dela, o anjo disse: — Salve, agraciada! O Senhor está com você.

[[v42-1-29]]

^<<v42-1-29,29>>^ Ela, porém, ao ouvir esta palavra, perturbou-se muito e pôs-se a pensar no que poderia significar esta saudação.

[[v42-1-30]]

^<<v42-1-30,30>>^ Mas o anjo lhe disse: — Não tenha medo, Maria; porque você foi abençoada por Deus.

[[v42-1-31]]

^<<v42-1-31,31>>^ Você ficará grávida e dará à luz um filho, a quem chamará pelo nome de Jesus.

[[v42-1-32]]

^<<v42-1-32,32>>^ Este será grande e será chamado Filho do Altíssimo. Deus, o Senhor, lhe dará o trono de Davi, seu pai.

[[v42-1-33]]

^<<v42-1-33,33>>^ Ele reinará para sempre sobre a casa de Jacó, e o seu reinado não terá fim.

[[v42-1-34]]

^<<v42-1-34,34>>^ Então Maria disse ao anjo: — Como será isto, se eu nunca tive relações com homem algum?

[[v42-1-35]]

^<<v42-1-35,35>>^ O anjo respondeu: — O Espírito Santo virá sobre você, e o poder do Altíssimo a envolverá com a sua sombra; por isso, também o ente santo que há de nascer será chamado Filho de Deus.

[[v42-1-36]]

^<<v42-1-36,36>>^ E Isabel, sua parenta, igualmente está grávida, apesar de sua idade avançada, sendo este já o sexto mês de gestação para aquela que diziam ser estéril.

[[v42-1-37]]

^<<v42-1-37,37>>^ Porque para Deus não há nada impossível.

[[v42-1-38]]

^<<v42-1-38,38>>^ Então Maria disse: — Aqui está a serva do Senhor; que aconteça comigo o que você falou. Então o anjo foi embora.

[[v42-1-39]]

^<<v42-1-39,39>>^ Naqueles dias, Maria se aprontou e foi depressa à região montanhosa, a uma cidade de Judá.

[[v42-1-40]]

^<<v42-1-40,40>>^ Entrou na casa de Zacarias e saudou Isabel.

[[v42-1-41]]

^<<v42-1-41,41>>^ Quando Isabel ouviu a saudação de Maria, a criança lhe estremeceu no ventre. Então Isabel ficou cheia do Espírito Santo.

[[v42-1-42]]

^<<v42-1-42,42>>^ E exclamou em alta voz: — Bendita é você entre as mulheres, e bendito o fruto do seu ventre!

[[v42-1-43]]

^<<v42-1-43,43>>^ E que grande honra é para mim receber a visita da mãe do meu Senhor!

[[v42-1-44]]

^<<v42-1-44,44>>^ Pois, logo que me chegou aos ouvidos a voz da saudação que você fez, a criança estremeceu de alegria dentro de mim.

[[v42-1-45]]

^<<v42-1-45,45>>^ Bem-aventurada a que creu, porque serão cumpridas as palavras que lhe foram ditas da parte do Senhor.

[[v42-1-46]]

^<<v42-1-46,46>>^ Então Maria disse: "A minha alma engrandece ao Senhor,

[[v42-1-47]]

^<<v42-1-47,47>>^ e o meu espírito se alegrou em Deus, meu Salvador,

[[v42-1-48]]

^<<v42-1-48,48>>^ porque ele atentou para a humildade da sua serva. Pois, desde agora, todas as gerações me considerarão bem-aventurada,

[[v42-1-49]]

^<<v42-1-49,49>>^ porque o Poderoso me fez grandes coisas. Santo é o seu nome.

[[v42-1-50]]

^<<v42-1-50,50>>^ A sua misericórdia vai de geração em geração sobre os que o temem.

[[v42-1-51]]

^<<v42-1-51,51>>^ Agiu com o seu braço valorosamente; dispersou os que, no coração, alimentavam pensamentos soberbos.

[[v42-1-52]]

^<<v42-1-52,52>>^ Derrubou dos seus tronos os poderosos e exaltou os humildes.

[[v42-1-53]]

^<<v42-1-53,53>>^ Encheu de bens os famintos e despediu vazios os ricos.

[[v42-1-54]]

^<<v42-1-54,54>>^ Amparou Israel, seu servo, a fim de lembrar-se da sua misericórdia

[[v42-1-55]]

^<<v42-1-55,55>>^ a favor de Abraão e de sua descendência, para sempre, como havia prometido aos nossos pais."

[[v42-1-56]]

^<<v42-1-56,56>>^ Maria permaneceu cerca de três meses com Isabel e voltou para casa.

[[v42-1-57]]

^<<v42-1-57,57>>^ Quando chegou o tempo de Isabel dar à luz, ela teve um filho.

[[v42-1-58]]

^<<v42-1-58,58>>^ Os vizinhos e parentes ouviram que o Senhor tinha usado de grande misericórdia para com Isabel e se alegraram com ela.

[[v42-1-59]]

^<<v42-1-59,59>>^ Aconteceu que, no oitavo dia, foram circuncidar o menino e queriam dar-lhe o nome de seu pai, Zacarias.

[[v42-1-60]]

^<<v42-1-60,60>>^ Mas a mãe do menino disse: — De modo nenhum! Ele será chamado João.

[[v42-1-61]]

^<<v42-1-61,61>>^ Disseram-lhe: — Mas você não tem nenhum parente com esse nome!

[[v42-1-62]]

^<<v42-1-62,62>>^ Fizeram sinais, perguntando ao pai do menino que nome queria que lhe dessem.

[[v42-1-63]]

^<<v42-1-63,63>>^ Então, pedindo uma tabuinha, ele escreveu: — O nome dele é João. E todos se admiraram.

[[v42-1-64]]

^<<v42-1-64,64>>^ Imediatamente a boca de Zacarias se abriu e a língua se soltou. Então começou a falar, louvando a Deus.

[[v42-1-65]]

^<<v42-1-65,65>>^ Todos os vizinhos deles ficaram possuídos de temor, e essas coisas foram divulgadas por toda a região montanhosa da Judeia.

[[v42-1-66]]

^<<v42-1-66,66>>^ Todos os que as ouviram guardavam-nas no coração, dizendo: — O que virá a ser este menino? E a mão do Senhor estava com ele.

[[v42-1-67]]

^<<v42-1-67,67>>^ Zacarias, o pai de João, cheio do Espírito Santo, profetizou, dizendo:

[[v42-1-68]]

^<<v42-1-68,68>>^ "Bendito seja o Senhor, Deus de Israel, porque visitou e redimiu o seu povo,

[[v42-1-69]]

^<<v42-1-69,69>>^ e nos suscitou plena e poderosa salvação na casa de Davi, seu servo,

[[v42-1-70]]

^<<v42-1-70,70>>^ como havia prometido, desde a antiguidade, por boca dos seus santos profetas,

[[v42-1-71]]

^<<v42-1-71,71>>^ para nos libertar dos nossos inimigos e das mãos de todos os que nos odeiam;

[[v42-1-72]]

^<<v42-1-72,72>>^ para usar de misericórdia com os nossos pais e lembrar-se da sua santa aliança

[[v42-1-73]]

^<<v42-1-73,73>>^ e do juramento que fez a nosso pai Abraão,

[[v42-1-74]]

^<<v42-1-74,74>>^ de conceder-nos que, livres das mãos de inimigos, o adorássemos sem temor,

[[v42-1-75]]

^<<v42-1-75,75>>^ em santidade e justiça diante dele, todos os nossos dias.

[[v42-1-76]]

^<<v42-1-76,76>>^ E você, menino, será chamado profeta do Altíssimo, porque precederá o Senhor, preparando-lhe os caminhos,

[[v42-1-77]]

^<<v42-1-77,77>>^ para dar ao seu povo conhecimento da salvação, por meio da remissão dos seus pecados,

[[v42-1-78]]

^<<v42-1-78,78>>^ graças à profunda misericórdia de nosso Deus, pela qual nos visitará o sol nascente das alturas,

[[v42-1-79]]

^<<v42-1-79,79>>^ para iluminar os que jazem nas trevas e na sombra da morte, e dirigir os nossos pés pelo caminho da paz."

[[v42-1-80]]

^<<v42-1-80,80>>^ O menino crescia e se fortalecia em espírito. E viveu nos desertos até o dia em que havia de manifestar-se a Israel.

'''

xref:041-marcos/041-marcos-016.adoc#v41-16-0[&#60; Capítulo Anterior] | <<v42-1-0,Topo>> | xref:042-lucas/042-lucas-002.adoc#v42-2-0[Próximo Capítulo &#62;]