include::./index.adoc[]

[[v42-10-0]]
=== Lucas, 10
// naa ?, NAA - Nova Almeida Atualizada

[[v42-10-1]]

^<<v42-10-1,1>>^ Depois disso, o Senhor escolheu outros setenta e os enviou de dois em dois, para que fossem adiante dele a cada cidade e lugar onde ele haveria de passar.

[[v42-10-2]]

^<<v42-10-2,2>>^ E lhes disse: — A seara é grande, mas os trabalhadores são poucos. Por isso, peçam ao Senhor da seara que mande trabalhadores para a sua seara.

[[v42-10-3]]

^<<v42-10-3,3>>^ Vão! Eis que eu os envio como cordeiros para o meio de lobos.

[[v42-10-4]]

^<<v42-10-4,4>>^ Não levem bolsa, nem sacola, nem sandálias; e não saúdem ninguém pelo caminho.

[[v42-10-5]]

^<<v42-10-5,5>>^ Ao entrarem numa casa, digam primeiro: "Paz seja nesta casa!"

[[v42-10-6]]

^<<v42-10-6,6>>^ Se houver ali uma pessoa que ama a paz, sobre ela repousará a paz de vocês; se não houver, a paz voltará sobre vocês.

[[v42-10-7]]

^<<v42-10-7,7>>^ Fiquem na mesma casa, comendo e bebendo do que eles tiverem; porque o trabalhador é digno do seu salário. Não fiquem mudando de casa em casa.

[[v42-10-8]]

^<<v42-10-8,8>>^ Quando entrarem numa cidade e ali forem bem-recebidos, comam do que lhes for oferecido.

[[v42-10-9]]

^<<v42-10-9,9>>^ Curem os doentes que nela houver e digam ao povo dali: "O Reino de Deus se aproximou de vocês."

[[v42-10-10]]

^<<v42-10-10,10>>^ Porém, quando entrarem numa cidade e não forem bem-recebidos, saiam pelas ruas, dizendo:

[[v42-10-11]]

^<<v42-10-11,11>>^ "Até o pó desta cidade, que grudou nos nossos pés, sacudimos contra vocês! No entanto, saibam que está próximo o Reino de Deus."

[[v42-10-12]]

^<<v42-10-12,12>>^ Eu digo a vocês que, naquele dia, haverá menos rigor para Sodoma do que para aquela cidade.

[[v42-10-13]]

^<<v42-10-13,13>>^ — Ai de você, Corazim! Ai de você, Betsaida! Porque, se em Tiro e em Sidom se tivessem operado os milagres que foram feitos em vocês, há muito que elas teriam se arrependido, assentadas em pano de saco e cinza.

[[v42-10-14]]

^<<v42-10-14,14>>^ Mas, no Juízo, haverá menos rigor para Tiro e Sidom do que para vocês.

[[v42-10-15]]

^<<v42-10-15,15>>^ — E você, Cafarnaum, pensa que será elevada até o céu? Será jogada no inferno!

[[v42-10-16]]

^<<v42-10-16,16>>^ — Quem ouve vocês ouve a mim; e quem rejeita vocês é a mim que rejeita; quem, porém, me rejeita está rejeitando aquele que me enviou.

[[v42-10-17]]

^<<v42-10-17,17>>^ Então os setenta voltaram, cheios de alegria, dizendo: — Senhor, em seu nome os próprios demônios se submetem a nós!

[[v42-10-18]]

^<<v42-10-18,18>>^ Jesus lhes disse: — Eu via Satanás caindo do céu como um relâmpago.

[[v42-10-19]]

^<<v42-10-19,19>>^ Eis que eu dei a vocês autoridade para pisarem cobras e escorpiões e sobre todo o poder do inimigo, e nada, absolutamente, lhes causará dano.

[[v42-10-20]]

^<<v42-10-20,20>>^ No entanto, alegrem-se, não porque os espíritos se submetem a vocês, e sim porque o nome de cada um de vocês está registrado no céu.

[[v42-10-21]]

^<<v42-10-21,21>>^ Naquela hora, Jesus exultou no Espírito Santo e exclamou: — Graças te dou, ó Pai, Senhor do céu e da terra, porque escondeste estas coisas dos sábios e instruídos e as revelaste aos pequeninos. Sim, ó Pai, porque assim foi do teu agrado.

[[v42-10-22]]

^<<v42-10-22,22>>^ — Tudo me foi entregue por meu Pai. Ninguém sabe quem é o Filho, a não ser o Pai; e também ninguém sabe quem é o Pai, a não ser o Filho e aquele a quem o Filho o quiser revelar.

[[v42-10-23]]

^<<v42-10-23,23>>^ E, voltando-se para os seus discípulos, Jesus lhes disse em particular: — Bem-aventurados os olhos que veem as coisas que vocês estão vendo.

[[v42-10-24]]

^<<v42-10-24,24>>^ Pois eu lhes digo que muitos profetas e reis quiseram ver o que vocês estão vendo, mas não viram; e quiseram ouvir o que vocês estão ouvindo, mas não ouviram.

[[v42-10-25]]

^<<v42-10-25,25>>^ E eis que certo homem, intérprete da Lei, se levantou com o objetivo de pôr Jesus à prova e lhe perguntou: — Mestre, que farei para herdar a vida eterna?

[[v42-10-26]]

^<<v42-10-26,26>>^ Então Jesus lhe perguntou: — O que está escrito na Lei? Como você a entende?

[[v42-10-27]]

^<<v42-10-27,27>>^ A isto ele respondeu: — "Ame o Senhor, seu Deus, de todo o seu coração, de toda a sua alma, com todas as suas forças e todo o seu entendimento." E: "Ame o seu próximo como você ama a si mesmo."

[[v42-10-28]]

^<<v42-10-28,28>>^ Então Jesus lhe disse: — Você respondeu corretamente. Faça isto e você viverá.

[[v42-10-29]]

^<<v42-10-29,29>>^ Mas ele, querendo justificar-se, perguntou a Jesus: — Quem é o meu próximo?

[[v42-10-30]]

^<<v42-10-30,30>>^ Jesus prosseguiu, dizendo: — Um homem descia de Jerusalém para Jericó e caiu nas mãos de alguns ladrões. Estes, depois de lhe tirar a roupa e lhe causar muitos ferimentos, retiraram-se, deixando-o semimorto.

[[v42-10-31]]

^<<v42-10-31,31>>^ Por casualidade, um sacerdote estava descendo por aquele mesmo caminho e, vendo aquele homem, passou de largo.

[[v42-10-32]]

^<<v42-10-32,32>>^ De igual modo, um levita descia por aquele lugar e, vendo-o, passou de largo.

[[v42-10-33]]

^<<v42-10-33,33>>^ Certo samaritano, que seguia o seu caminho, passou perto do homem e, vendo-o, compadeceu-se dele.

[[v42-10-34]]

^<<v42-10-34,34>>^ E, aproximando-se, fez curativos nos ferimentos dele, aplicando-lhes óleo e vinho. Depois, colocou aquele homem sobre o seu próprio animal, levou-o para uma hospedaria e tratou dele.

[[v42-10-35]]

^<<v42-10-35,35>>^ No dia seguinte, separou dois denários e os entregou ao hospedeiro, dizendo: "Cuide deste homem. E, se você gastar algo a mais, farei o reembolso quando eu voltar."

[[v42-10-36]]

^<<v42-10-36,36>>^ Então Jesus perguntou: — Qual destes três lhe parece ter sido o próximo do homem que caiu nas mãos dos ladrões?

[[v42-10-37]]

^<<v42-10-37,37>>^ O intérprete da Lei respondeu: — O que usou de misericórdia para com ele. Então Jesus lhe disse: — Vá e faça o mesmo.

[[v42-10-38]]

^<<v42-10-38,38>>^ Quando eles seguiam viagem, Jesus entrou numa aldeia. E certa mulher, chamada Marta, hospedou-o na sua casa.

[[v42-10-39]]

^<<v42-10-39,39>>^ Marta tinha uma irmã, chamada Maria, que, assentada aos pés do Senhor, ouvia o seu ensino.

[[v42-10-40]]

^<<v42-10-40,40>>^ Marta agitava-se de um lado para outro, ocupada em muitos serviços. Então se aproximou de Jesus e disse: — O Senhor não se importa com o fato de minha irmã ter deixado que eu fique sozinha para servir? Diga-lhe que venha me ajudar.

[[v42-10-41]]

^<<v42-10-41,41>>^ Mas o Senhor respondeu: — Marta! Marta! Você anda inquieta e se preocupa com muitas coisas,

[[v42-10-42]]

^<<v42-10-42,42>>^ mas apenas uma é necessária. Maria escolheu a boa parte, e esta não lhe será tirada.

'''

xref:042-lucas/042-lucas-009.adoc#v42-9-0[&#60; Capítulo Anterior] | <<v42-10-0,Topo>> | xref:042-lucas/042-lucas-011.adoc#v42-11-0[Próximo Capítulo &#62;]