include::./index.adoc[]

[[v20-25-0]]
=== Provérbios, 25
// naa ?, NAA - Nova Almeida Atualizada

[[v20-25-1]]

^<<v20-25-1,1>>^ Também estes são provérbios de Salomão, que foram transcritos pelos homens a serviço de Ezequias, rei de Judá.

[[v20-25-2]]

^<<v20-25-2,2>>^ A glória de Deus é encobrir as coisas, mas a glória dos reis é investigá-las.

[[v20-25-3]]

^<<v20-25-3,3>>^ Como a altura dos céus e a profundeza da terra, assim também o coração dos reis é insondável.

[[v20-25-4]]

^<<v20-25-4,4>>^ Tire a escória da prata, e sairá um vaso para o ourives;

[[v20-25-5]]

^<<v20-25-5,5>>^ tire o ímpio da presença do rei, e o seu trono se firmará na justiça.

[[v20-25-6]]

^<<v20-25-6,6>>^ Não se glorie na presença do rei, nem se ponha no meio dos grandes,

[[v20-25-7]]

^<<v20-25-7,7>>^ porque melhor é que lhe digam: "Suba para cá!", do que ser humilhado diante do príncipe. A respeito do que os seus olhos viram,

[[v20-25-8]]

^<<v20-25-8,8>>^ não se apresse a levar ao tribunal, pois, ao fim, o que é que você fará, se o seu próximo o puser em apuros?

[[v20-25-9]]

^<<v20-25-9,9>>^ Defenda a sua causa diretamente com o seu próximo e não revele o segredo do outro.

[[v20-25-10]]

^<<v20-25-10,10>>^ Do contrário, quem o ouvir poderá envergonhá-lo, e você nunca se livrará dessa má fama.

[[v20-25-11]]

^<<v20-25-11,11>>^ Como maçãs de ouro em bandejas de prata, assim é a palavra dita a seu tempo.

[[v20-25-12]]

^<<v20-25-12,12>>^ Como pendentes e joias de ouro puro, assim é a repreensão dada por um sábio a um ouvinte atento.

[[v20-25-13]]

^<<v20-25-13,13>>^ Como o frescor de neve no tempo da colheita, assim é o mensageiro fiel para com os que o enviam, porque refrigera a alma dos seus senhores.

[[v20-25-14]]

^<<v20-25-14,14>>^ Como nuvens e ventos que não trazem chuva, assim é aquele que se gaba de presentes que não deu.

[[v20-25-15]]

^<<v20-25-15,15>>^ Com paciência se convence um príncipe, e a língua branda quebra ossos.

[[v20-25-16]]

^<<v20-25-16,16>>^ Você encontrou mel? Coma apenas o suficiente, para que você não fique enjoado e venha a vomitá-lo.

[[v20-25-17]]

^<<v20-25-17,17>>^ Não seja frequente na casa do seu próximo, para que ele não se canse de você e passe a detestá-lo.

[[v20-25-18]]

^<<v20-25-18,18>>^ Martelo, espada e flecha aguda é o que levanta falso testemunho contra o seu próximo.

[[v20-25-19]]

^<<v20-25-19,19>>^ Como dente quebrado e pé sem firmeza, assim é a confiança numa pessoa desleal em tempo de angústia.

[[v20-25-20]]

^<<v20-25-20,20>>^ Como quem se despe num dia de frio e como vinagre sobre feridas, assim é o que entoa canções para quem está aflito.

[[v20-25-21]]

^<<v20-25-21,21>>^ Se o seu inimigo tiver fome, dê-lhe de comer; se tiver sede, dê-lhe de beber,

[[v20-25-22]]

^<<v20-25-22,22>>^ porque assim você amontoará brasas vivas sobre a cabeça dele, e o Senhor  recompensará você.

[[v20-25-23]]

^<<v20-25-23,23>>^ O vento norte traz chuva, e a língua que espalha calúnias traz o rosto irado.

[[v20-25-24]]

^<<v20-25-24,24>>^ Melhor é morar no canto do terraço do que com uma mulher briguenta na mesma casa.

[[v20-25-25]]

^<<v20-25-25,25>>^ Como água fria para quem tem sede, assim é a boa notícia que vem de um país distante.

[[v20-25-26]]

^<<v20-25-26,26>>^ Como fonte que foi turvada e manancial contaminado, assim é o justo que cede ao ímpio.

[[v20-25-27]]

^<<v20-25-27,27>>^ Comer muito mel não é bom; assim, procurar a própria honra não é honra.

[[v20-25-28]]

^<<v20-25-28,28>>^ Como cidade derrubada, que não tem muralhas, assim é aquele que não tem domínio próprio.

'''

xref:020-proverbios/020-proverbios-024.adoc#v20-24-0[&#60; Capítulo Anterior] | <<v20-25-0,Topo>> | xref:020-proverbios/020-proverbios-026.adoc#v20-26-0[Próximo Capítulo &#62;]