include::./index.adoc[]

[[v20-26-0]]
=== Provérbios, 26
// naa ?, NAA - Nova Almeida Atualizada

[[v20-26-1]]

^<<v20-26-1,1>>^ Como a neve no verão e como a chuva no tempo da colheita, assim a honra não fica bem a um tolo.

[[v20-26-2]]

^<<v20-26-2,2>>^ Como o pássaro que foge e como a andorinha no seu voo, assim a maldição sem motivo não se cumpre.

[[v20-26-3]]

^<<v20-26-3,3>>^ O açoite é para o cavalo, o freio, para o jumento, e a vara, para as costas dos tolos.

[[v20-26-4]]

^<<v20-26-4,4>>^ Não responda ao insensato segundo a sua tolice, para que você não se torne semelhante a ele.

[[v20-26-5]]

^<<v20-26-5,5>>^ Responda ao insensato segundo a sua tolice, para que ele não seja sábio aos seus próprios olhos.

[[v20-26-6]]

^<<v20-26-6,6>>^ Como cortar os pés e sofrer dano, assim é mandar mensagens por meio de um tolo.

[[v20-26-7]]

^<<v20-26-7,7>>^ As pernas do coxo pendem bambas; assim é o provérbio na boca dos tolos.

[[v20-26-8]]

^<<v20-26-8,8>>^ Como amarrar a pedra na funda, assim é dar honra a um tolo.

[[v20-26-9]]

^<<v20-26-9,9>>^ Como o espinho que entra na mão de um bêbado, assim é o provérbio na boca dos tolos.

[[v20-26-10]]

^<<v20-26-10,10>>^ Como um flecheiro que fere a todos, assim é o que contrata os tolos e os primeiros que passam.

[[v20-26-11]]

^<<v20-26-11,11>>^ Como o cão que volta ao seu próprio vômito, assim é o insensato que repete a sua tolice.

[[v20-26-12]]

^<<v20-26-12,12>>^ Você viu alguém que é sábio aos seus próprios olhos? Há mais esperança para um tolo do que para ele.

[[v20-26-13]]

^<<v20-26-13,13>>^ O preguiçoso diz: "Um leão está no caminho! Um leão está no meio da rua!"

[[v20-26-14]]

^<<v20-26-14,14>>^ A porta gira nas dobradiças; o preguiçoso se vira na cama.

[[v20-26-15]]

^<<v20-26-15,15>>^ O preguiçoso põe a mão no prato e não quer ter o trabalho de a levar à boca.

[[v20-26-16]]

^<<v20-26-16,16>>^ O preguiçoso é mais sábio aos seus próprios olhos do que sete homens que sabem responder bem.

[[v20-26-17]]

^<<v20-26-17,17>>^ Quem se mete na discussão dos outros é como aquele que pega pelas orelhas um cão que vai passando.

[[v20-26-18]]

^<<v20-26-18,18>>^ Como o louco que lança fogo, flechas e morte,

[[v20-26-19]]

^<<v20-26-19,19>>^ assim é aquele que engana o seu próximo e diz: "Fiz isso por brincadeira."

[[v20-26-20]]

^<<v20-26-20,20>>^ Sem lenha, o fogo se apaga; e, não havendo difamador, cessa a discórdia.

[[v20-26-21]]

^<<v20-26-21,21>>^ O que o carvão é para as brasas e a lenha é para o fogo, o briguento é para acender uma discussão.

[[v20-26-22]]

^<<v20-26-22,22>>^ As palavras do difamador são comida fina, que desce para o mais interior do ventre.

[[v20-26-23]]

^<<v20-26-23,23>>^ Como vaso de barro coberto de prata, assim são os lábios amorosos e o coração mau.

[[v20-26-24]]

^<<v20-26-24,24>>^ Quem odeia dissimula com os lábios, mas no seu íntimo esconde a falsidade;

[[v20-26-25]]

^<<v20-26-25,25>>^ quando ele vier com palavras suaves, não acredite nele, porque tem sete abominações em seu coração.

[[v20-26-26]]

^<<v20-26-26,26>>^ Ainda que o seu ódio se encubra com falsidade, a sua maldade será exposta aos olhos de todos.

[[v20-26-27]]

^<<v20-26-27,27>>^ Quem abre uma cova acaba caindo nela; e a pedra rolará sobre quem a pôs em movimento.

[[v20-26-28]]

^<<v20-26-28,28>>^ A língua falsa odeia aqueles a quem engana, e a boca lisonjeira é causa de ruína.

'''

xref:020-proverbios/020-proverbios-025.adoc#v20-25-0[&#60; Capítulo Anterior] | <<v20-26-0,Topo>> | xref:020-proverbios/020-proverbios-027.adoc#v20-27-0[Próximo Capítulo &#62;]