include::./index.adoc[]

[[v20-18-0]]
=== Provérbios, 18
// naa ?, NAA - Nova Almeida Atualizada

[[v20-18-1]]

^<<v20-18-1,1>>^ O solitário busca o seu próprio interesse e se opõe à verdadeira sabedoria.

[[v20-18-2]]

^<<v20-18-2,2>>^ O tolo não tem prazer no entendimento, mas apenas em externar o que pensa.

[[v20-18-3]]

^<<v20-18-3,3>>^ Com a maldade vem também o desprezo; com a desonra vem a vergonha.

[[v20-18-4]]

^<<v20-18-4,4>>^ As palavras de uma pessoa são águas profundas, e a fonte da sabedoria é um ribeiro que transborda.

[[v20-18-5]]

^<<v20-18-5,5>>^ Não é bom ser parcial com os ímpios, para torcer o direito contra os justos.

[[v20-18-6]]

^<<v20-18-6,6>>^ Os lábios do tolo entram na discussão, e a sua boca clama por açoites.

[[v20-18-7]]

^<<v20-18-7,7>>^ A boca do tolo é a sua própria destruição, e os seus lábios são uma armadilha para a sua alma.

[[v20-18-8]]

^<<v20-18-8,8>>^ As palavras do difamador são comida fina, que desce para o mais interior do ventre.

[[v20-18-9]]

^<<v20-18-9,9>>^ Quem é negligente no seu trabalho já é irmão do desperdiçador.

[[v20-18-10]]

^<<v20-18-10,10>>^ Torre forte é o nome do Senhor ; o justo corre para ela e está seguro.

[[v20-18-11]]

^<<v20-18-11,11>>^ Os bens do rico são a sua cidade fortificada e, segundo imagina, uma alta muralha.

[[v20-18-12]]

^<<v20-18-12,12>>^ Antes da ruína, o coração humano se gaba, mas a humildade precede a honra.

[[v20-18-13]]

^<<v20-18-13,13>>^ Responder antes de ouvir é tolice e vergonha.

[[v20-18-14]]

^<<v20-18-14,14>>^ O espírito firme sustenta a pessoa na sua doença, mas o espírito abatido, quem o pode suportar?

[[v20-18-15]]

^<<v20-18-15,15>>^ O coração do sábio adquire o conhecimento, e o ouvido dos sábios procura o saber.

[[v20-18-16]]

^<<v20-18-16,16>>^ Um presente que se dá abre portas e leva alguém à presença dos grandes.

[[v20-18-17]]

^<<v20-18-17,17>>^ O primeiro que pleiteia a sua causa parece justo, até que vem o outro e o examina.

[[v20-18-18]]

^<<v20-18-18,18>>^ Um sorteio põe fim às rixas e decide questões entre os poderosos.

[[v20-18-19]]

^<<v20-18-19,19>>^ Um irmão ofendido resiste mais que uma fortaleza, e as rixas são como as trancas das portas de um castelo.

[[v20-18-20]]

^<<v20-18-20,20>>^ Do fruto da boca o coração se farta; do que produzem os lábios ele se satisfaz.

[[v20-18-21]]

^<<v20-18-21,21>>^ A morte e a vida estão no poder da língua; quem bem a utiliza come do seu fruto.

[[v20-18-22]]

^<<v20-18-22,22>>^ Quem acha uma esposa acha o bem; recebeu uma bênção do Senhor .

[[v20-18-23]]

^<<v20-18-23,23>>^ O pobre fala com súplicas, mas o rico responde com dureza.

[[v20-18-24]]

^<<v20-18-24,24>>^ Quem tem muitos amigos pode cair em desgraça; mas há amigo mais chegado que um irmão.

'''

xref:020-proverbios/020-proverbios-017.adoc#v20-17-0[&#60; Capítulo Anterior] | <<v20-18-0,Topo>> | xref:020-proverbios/020-proverbios-019.adoc#v20-19-0[Próximo Capítulo &#62;]