include::./index.adoc[]

[[v20-8-0]]
=== Provérbios, 8
// naa ?, NAA - Nova Almeida Atualizada

[[v20-8-1]]

^<<v20-8-1,1>>^ Por acaso, não clama a Sabedoria? E o Entendimento não faz ouvir a sua voz?

[[v20-8-2]]

^<<v20-8-2,2>>^ A Sabedoria se coloca no topo dos lugares elevados, junto ao caminho, nas encruzilhadas das veredas.

[[v20-8-3]]

^<<v20-8-3,3>>^ Junto aos portões, à entrada da cidade, à entrada dos portões ela está gritando:

[[v20-8-4]]

^<<v20-8-4,4>>^ "É para vocês, homens, que eu clamo; e a minha voz se dirige aos filhos dos homens.

[[v20-8-5]]

^<<v20-8-5,5>>^ Vocês, ingênuos, entendam a prudência; e vocês, tolos, entendam a sabedoria.

[[v20-8-6]]

^<<v20-8-6,6>>^ Escutem, pois falarei coisas excelentes; os meus lábios dirão o que é reto.

[[v20-8-7]]

^<<v20-8-7,7>>^ Porque a minha boca proclamará a verdade; os meus lábios detestam a maldade.

[[v20-8-8]]

^<<v20-8-8,8>>^ Todas as palavras da minha boca são justas; não há nelas nenhuma coisa torta, nem perversa.

[[v20-8-9]]

^<<v20-8-9,9>>^ Todas são retas para os que têm compreensão e justas, para os que acham o conhecimento.

[[v20-8-10]]

^<<v20-8-10,10>>^ Aceitem o meu ensino, em vez da prata, e o conhecimento, em lugar do ouro escolhido.

[[v20-8-11]]

^<<v20-8-11,11>>^ Porque a sabedoria é melhor do que as joias, e tudo o que se possa desejar não se compara com ela.

[[v20-8-12]]

^<<v20-8-12,12>>^ Eu, a Sabedoria, moro com a prudência e disponho de conhecimento e de conselhos.

[[v20-8-13]]

^<<v20-8-13,13>>^ O temor do Senhor  consiste em odiar o mal. Eu odeio a soberba, a arrogância, o mau caminho e a boca que fala coisas perversas.

[[v20-8-14]]

^<<v20-8-14,14>>^ Meu é o conselho e a verdadeira sabedoria; eu sou o Entendimento, minha é a fortaleza.

[[v20-8-15]]

^<<v20-8-15,15>>^ Por meio de mim os reis governam, e os príncipes decretam justiça.

[[v20-8-16]]

^<<v20-8-16,16>>^ Por meio de mim governam os príncipes, os nobres e todos os juízes da terra.

[[v20-8-17]]

^<<v20-8-17,17>>^ Eu amo os que me amam; os que me procuram me encontram.

[[v20-8-18]]

^<<v20-8-18,18>>^ Riquezas e honra estão comigo, bens duráveis e justiça.

[[v20-8-19]]

^<<v20-8-19,19>>^ O meu fruto é melhor do que o ouro, do que o ouro refinado; e o meu rendimento é maior do que a prata escolhida.

[[v20-8-20]]

^<<v20-8-20,20>>^ Ando pelo caminho da justiça e sigo as veredas do juízo,

[[v20-8-21]]

^<<v20-8-21,21>>^ para dotar de bens os que me amam e encher os seus tesouros."

[[v20-8-22]]

^<<v20-8-22,22>>^ O Senhor  me possuía no início da sua obra, antes das suas obras mais antigas.

[[v20-8-23]]

^<<v20-8-23,23>>^ Fui estabelecida desde a eternidade, desde o princípio, antes do começo da terra.

[[v20-8-24]]

^<<v20-8-24,24>>^ Nasci antes de haver abismos, quando ainda não havia fontes carregadas de águas.

[[v20-8-25]]

^<<v20-8-25,25>>^ Antes que os montes fossem firmados, antes de haver colinas, eu nasci.

[[v20-8-26]]

^<<v20-8-26,26>>^ Deus ainda não tinha feito a terra, nem os seus campos, nem sequer o princípio do pó do mundo.

[[v20-8-27]]

^<<v20-8-27,27>>^ Eu estava lá quando ele preparava os céus, quando traçava o horizonte sobre a face do abismo.

[[v20-8-28]]

^<<v20-8-28,28>>^ Estava lá quando ele firmava as nuvens de cima, quando estabelecia as fontes do abismo,

[[v20-8-29]]

^<<v20-8-29,29>>^ quando fixava ao mar os seus limites, para que as águas não transgredissem a sua ordem. Quando ele compunha os fundamentos da terra,

[[v20-8-30]]

^<<v20-8-30,30>>^ eu estava com ele e era o seu arquiteto. Dia após dia eu era a sua alegria, divertindo-me em todo o tempo na sua presença,

[[v20-8-31]]

^<<v20-8-31,31>>^ divertindo-me no seu mundo habitável e achando alegria junto aos filhos dos homens.

[[v20-8-32]]

^<<v20-8-32,32>>^ Agora, meus filhos, escutem o que eu digo, porque felizes são os que guardam os meus caminhos.

[[v20-8-33]]

^<<v20-8-33,33>>^ Ouçam o ensino, sejam sábios e não o rejeitem.

[[v20-8-34]]

^<<v20-8-34,34>>^ Feliz é aquele que me ouve, vigiando dia após dia diante das minhas portas, esperando na entrada da minha casa.

[[v20-8-35]]

^<<v20-8-35,35>>^ Pois quem me encontra encontra a vida e alcança favor do Senhor .

[[v20-8-36]]

^<<v20-8-36,36>>^ Mas quem peca contra mim violenta a própria alma. Todos os que me odeiam amam a morte.

'''

xref:020-proverbios/020-proverbios-007.adoc#v20-7-0[&#60; Capítulo Anterior] | <<v20-8-0,Topo>> | xref:020-proverbios/020-proverbios-009.adoc#v20-9-0[Próximo Capítulo &#62;]