include::./index.adoc[]

[[v20-19-0]]
=== Provérbios, 19
// naa ?, NAA - Nova Almeida Atualizada

[[v20-19-1]]

^<<v20-19-1,1>>^ Melhor é o pobre que anda na sua integridade do que o perverso de lábios, que é um tolo.

[[v20-19-2]]

^<<v20-19-2,2>>^ Não é bom agir sem pensar; quem se precipita acaba pecando.

[[v20-19-3]]

^<<v20-19-3,3>>^ A tolice de uma pessoa perverte o seu caminho, mas é contra o Senhor  que o seu coração se irrita.

[[v20-19-4]]

^<<v20-19-4,4>>^ Na riqueza, os amigos se multiplicam; mas o pobre, até o seu único amigo o abandona.

[[v20-19-5]]

^<<v20-19-5,5>>^ A falsa testemunha não ficará impune, e o que profere mentiras não escapará.

[[v20-19-6]]

^<<v20-19-6,6>>^ Ao generoso, muitos o adulam, e todos são amigos de quem dá presentes.

[[v20-19-7]]

^<<v20-19-7,7>>^ Se os irmãos do pobre o detestam, quanto mais se afastarão dele os seus amigos! Corre atrás deles com súplicas, mas não os alcança.

[[v20-19-8]]

^<<v20-19-8,8>>^ Quem adquire sabedoria ama a sua alma; o que conserva o entendimento acha o bem.

[[v20-19-9]]

^<<v20-19-9,9>>^ A falsa testemunha não ficará impune, e o que profere mentiras perecerá.

[[v20-19-10]]

^<<v20-19-10,10>>^ Ao tolo não fica bem viver no luxo; quanto menos ao escravo dominar os príncipes!

[[v20-19-11]]

^<<v20-19-11,11>>^ O bom senso leva a pessoa a controlar a sua ira; a sua glória é perdoar as ofensas.

[[v20-19-12]]

^<<v20-19-12,12>>^ A indignação do rei é como o rugido do leão, mas a sua bondade é como o orvalho sobre a relva.

[[v20-19-13]]

^<<v20-19-13,13>>^ Um filho tolo é a desgraça do pai, e uma esposa briguenta é como uma goteira que não para.

[[v20-19-14]]

^<<v20-19-14,14>>^ A casa e os bens vêm como herança dos pais, mas a esposa sensata vem do Senhor .

[[v20-19-15]]

^<<v20-19-15,15>>^ A preguiça faz cair em profundo sono, e o ocioso passará fome.

[[v20-19-16]]

^<<v20-19-16,16>>^ Quem guarda o mandamento guarda a sua alma, mas o que despreza os seus caminhos, esse morrerá.

[[v20-19-17]]

^<<v20-19-17,17>>^ Quem se compadece do pobre empresta ao Senhor , e este lhe retribuirá o benefício.

[[v20-19-18]]

^<<v20-19-18,18>>^ Corrija o seu filho, enquanto há esperança, mas não se exceda a ponto de matá-lo.

[[v20-19-19]]

^<<v20-19-19,19>>^ Aquele que se deixa levar pela ira terá de sofrer o castigo; porque, se você o livrar, terá de livrá-lo de novo.

[[v20-19-20]]

^<<v20-19-20,20>>^ Ouça os conselhos e receba a instrução, para que você seja sábio a partir de agora.

[[v20-19-21]]

^<<v20-19-21,21>>^ Há muitos planos no coração do ser humano, mas o propósito do Senhor permanecerá.

[[v20-19-22]]

^<<v20-19-22,22>>^ O que torna alguém agradável é a sua misericórdia; o pobre é preferível ao mentiroso.

[[v20-19-23]]

^<<v20-19-23,23>>^ O temor do Senhor conduz à vida; aquele que o tem ficará satisfeito, e mal nenhum o visitará.

[[v20-19-24]]

^<<v20-19-24,24>>^ O preguiçoso põe a mão no prato e não quer ter o trabalho de a levar à boca.

[[v20-19-25]]

^<<v20-19-25,25>>^ Castigue o zombador, e o ingênuo aprenderá a prudência; repreenda o sábio, e ele crescerá no conhecimento.

[[v20-19-26]]

^<<v20-19-26,26>>^ Quem maltrata o seu pai ou manda embora a sua mãe é filho que causa vergonha e traz desonra.

[[v20-19-27]]

^<<v20-19-27,27>>^ Meu filho, se deixar de ouvir a instrução, você se desviará das palavras do conhecimento.

[[v20-19-28]]

^<<v20-19-28,28>>^ A testemunha depravada zomba da justiça, e a boca dos ímpios devora a iniquidade.

[[v20-19-29]]

^<<v20-19-29,29>>^ Preparados estão os juízos para os zombadores e os açoites para as costas dos tolos.

'''

xref:020-proverbios/020-proverbios-018.adoc#v20-18-0[&#60; Capítulo Anterior] | <<v20-19-0,Topo>> | xref:020-proverbios/020-proverbios-020.adoc#v20-20-0[Próximo Capítulo &#62;]