include::./index.adoc[]

[[v20-14-0]]
=== Provérbios, 14
// naa ?, NAA - Nova Almeida Atualizada

[[v20-14-1]]

^<<v20-14-1,1>>^ A mulher sábia edifica a sua casa, mas a insensata a derruba com as próprias mãos.

[[v20-14-2]]

^<<v20-14-2,2>>^ Quem anda na retidão teme o Senhor , mas o que anda em caminhos tortuosos, esse o despreza.

[[v20-14-3]]

^<<v20-14-3,3>>^ Na boca do tolo está a vara para a sua própria soberba, mas os lábios dos sábios os protegerão.

[[v20-14-4]]

^<<v20-14-4,4>>^ Quando não há bois, o celeiro fica vazio, mas pela força do boi há abundância de colheitas.

[[v20-14-5]]

^<<v20-14-5,5>>^ A testemunha verdadeira não mente, mas a testemunha falsa despeja mentiras.

[[v20-14-6]]

^<<v20-14-6,6>>^ O zombador procura a sabedoria e não a encontra, mas o sábio adquire o conhecimento com facilidade.

[[v20-14-7]]

^<<v20-14-7,7>>^ Fuja da presença do insensato, porque nele você não encontrará palavras de conhecimento.

[[v20-14-8]]

^<<v20-14-8,8>>^ A sabedoria do prudente é entender o seu próprio caminho, mas a insensatez dos tolos é enganadora.

[[v20-14-9]]

^<<v20-14-9,9>>^ Os insensatos zombam do pecado, mas entre os retos há boa vontade.

[[v20-14-10]]

^<<v20-14-10,10>>^ O coração conhece a sua própria amargura, e da alegria que ele sente os estranhos não poderão participar.

[[v20-14-11]]

^<<v20-14-11,11>>^ A casa dos ímpios será destruída, mas a tenda dos retos florescerá.

[[v20-14-12]]

^<<v20-14-12,12>>^ Há caminho que ao ser humano parece direito, mas o fim dele é caminho de morte.

[[v20-14-13]]

^<<v20-14-13,13>>^ Até no riso o coração pode ter dor, e o fim da alegria pode ser a tristeza.

[[v20-14-14]]

^<<v20-14-14,14>>^ O infiel de coração sofre as consequências dos seus próprios caminhos, mas quem é de bem é recompensado pelo seu próprio proceder.

[[v20-14-15]]

^<<v20-14-15,15>>^ O ingênuo dá crédito a tudo o que se diz, mas o prudente reflete antes de dar um passo.

[[v20-14-16]]

^<<v20-14-16,16>>^ O sábio é cauteloso e se desvia do mal, mas o tolo é afoito e se dá por seguro.

[[v20-14-17]]

^<<v20-14-17,17>>^ Quem logo se irrita comete loucuras, e aquele que tem más intenções será odiado.

[[v20-14-18]]

^<<v20-14-18,18>>^ Os ingênuos herdam a tolice, mas os prudentes se coroam de conhecimento.

[[v20-14-19]]

^<<v20-14-19,19>>^ Os maus se inclinarão diante dos bons, e os ímpios farão súplicas junto às portas do justo.

[[v20-14-20]]

^<<v20-14-20,20>>^ O pobre é odiado até pelo seu vizinho, mas o rico tem muitos amigos.

[[v20-14-21]]

^<<v20-14-21,21>>^ Quem despreza o seu vizinho peca, mas o que se compadece dos pobres é feliz.

[[v20-14-22]]

^<<v20-14-22,22>>^ Por acaso não se afastam do caminho os que planejam o mal? Mas haverá amor e fidelidade para os que planejam o bem.

[[v20-14-23]]

^<<v20-14-23,23>>^ Em todo trabalho há proveito; meras palavras, porém, levam à penúria.

[[v20-14-24]]

^<<v20-14-24,24>>^ Para os sábios a riqueza é coroa, mas a tolice dos insensatos não passa de tolice.

[[v20-14-25]]

^<<v20-14-25,25>>^ A testemunha verdadeira salva vidas, mas quem profere mentiras é enganador.

[[v20-14-26]]

^<<v20-14-26,26>>^ Quem teme ao Senhor tem forte amparo, e isso é refúgio para os seus filhos.

[[v20-14-27]]

^<<v20-14-27,27>>^ O temor do Senhor é fonte de vida para evitar os laços da morte.

[[v20-14-28]]

^<<v20-14-28,28>>^ Na multidão do povo está a glória do rei, mas na falta de povo está a ruína do príncipe.

[[v20-14-29]]

^<<v20-14-29,29>>^ Quem tarda em irar-se é grande em entendimento, mas o que facilmente perde a calma faz um elogio à loucura.

[[v20-14-30]]

^<<v20-14-30,30>>^ O ânimo sereno é a vida do corpo, mas a inveja é a podridão dos ossos.

[[v20-14-31]]

^<<v20-14-31,31>>^ Quem oprime o pobre insulta aquele que o criou, mas o que se compadece do necessitado honra a Deus.

[[v20-14-32]]

^<<v20-14-32,32>>^ O ímpio é derrubado pela sua maldade, mas o justo, até na morte tem esperança.

[[v20-14-33]]

^<<v20-14-33,33>>^ No coração do prudente repousa a sabedoria, mas o que há no interior dos tolos logo se manifesta.

[[v20-14-34]]

^<<v20-14-34,34>>^ A justiça é a glória da nação, mas o pecado é a vergonha dos povos.

[[v20-14-35]]

^<<v20-14-35,35>>^ O servo prudente recebe o favor do rei, mas o que causa vergonha é objeto do seu furor.

'''

xref:020-proverbios/020-proverbios-013.adoc#v20-13-0[&#60; Capítulo Anterior] | <<v20-14-0,Topo>> | xref:020-proverbios/020-proverbios-015.adoc#v20-15-0[Próximo Capítulo &#62;]