include::./index.adoc[]

[[v20-29-0]]
=== Provérbios, 29
// naa ?, NAA - Nova Almeida Atualizada

[[v20-29-1]]

^<<v20-29-1,1>>^ Quem teima em rejeitar a repreensão será destruído de repente sem que haja remédio.

[[v20-29-2]]

^<<v20-29-2,2>>^ Quando os justos se multiplicam, o povo se alegra; quando o ímpio domina, então o povo lamenta.

[[v20-29-3]]

^<<v20-29-3,3>>^ Quem ama a sabedoria alegra o seu pai, mas o companheiro de prostitutas desperdiça os bens.

[[v20-29-4]]

^<<v20-29-4,4>>^ O rei justo traz estabilidade ao país, mas o amigo de impostos o leva à ruína.

[[v20-29-5]]

^<<v20-29-5,5>>^ Quem lisonjeia o seu próximo está armando uma rede para os seus pés.

[[v20-29-6]]

^<<v20-29-6,6>>^ Na transgressão do homem mau, há uma armadilha, mas o justo canta e se alegra.

[[v20-29-7]]

^<<v20-29-7,7>>^ O justo se interessa pelo direito dos pobres, mas o ímpio não se importa com isso.

[[v20-29-8]]

^<<v20-29-8,8>>^ Os zombadores alvoroçam a cidade, mas os sábios acalmam os ânimos.

[[v20-29-9]]

^<<v20-29-9,9>>^ Se o sábio discute com um insensato, quer este se enfureça, quer se ria, não haverá descanso.

[[v20-29-10]]

^<<v20-29-10,10>>^ Os homens sanguinários odeiam o íntegro, mas os retos procuram o seu bem.

[[v20-29-11]]

^<<v20-29-11,11>>^ O tolo derrama toda a sua ira, mas o sábio se domina e a reprime.

[[v20-29-12]]

^<<v20-29-12,12>>^ Se um governador dá atenção a palavras mentirosas, todos os seus servos virão a ser perversos.

[[v20-29-13]]

^<<v20-29-13,13>>^ O pobre e o seu opressor têm algo em comum: é o Senhor  quem dá luz aos olhos de ambos.

[[v20-29-14]]

^<<v20-29-14,14>>^ O rei que julga os pobres segundo a verdade firmará o seu trono para sempre.

[[v20-29-15]]

^<<v20-29-15,15>>^ A vara e a disciplina dão sabedoria, mas a criança entregue a si mesma envergonha a sua mãe.

[[v20-29-16]]

^<<v20-29-16,16>>^ Quando os ímpios se multiplicam, multiplicam-se as transgressões, mas os justos verão a ruína deles.

[[v20-29-17]]

^<<v20-29-17,17>>^ Corrija o seu filho, e você terá descanso; ele será um prazer para a sua alma.

[[v20-29-18]]

^<<v20-29-18,18>>^ Não havendo profecia, o povo se corrompe; mas o que guarda a lei, esse é feliz.

[[v20-29-19]]

^<<v20-29-19,19>>^ O servo não se emendará com palavras, porque, mesmo que entenda, não obedecerá.

[[v20-29-20]]

^<<v20-29-20,20>>^ Você viu alguém que é precipitado no falar? Há mais esperança para um tolo do que para ele.

[[v20-29-21]]

^<<v20-29-21,21>>^ Se alguém mimar o escravo desde a infância, por fim ele vai querer ser filho.

[[v20-29-22]]

^<<v20-29-22,22>>^ A pessoa colérica provoca discórdias, e quem facilmente fica irado multiplica as transgressões.

[[v20-29-23]]

^<<v20-29-23,23>>^ O orgulho do ser humano o abaterá, mas o humilde de espírito obterá honra.

[[v20-29-24]]

^<<v20-29-24,24>>^ Quem tem parte com um ladrão odeia a própria alma; mesmo ouvindo a maldição, permanece calado.

[[v20-29-25]]

^<<v20-29-25,25>>^ Quem tem medo dos outros cai numa armadilha, mas o que confia no Senhor está seguro.

[[v20-29-26]]

^<<v20-29-26,26>>^ Muitos buscam o favor daquele que governa, mas a justiça do Senhor vem para todos.

[[v20-29-27]]

^<<v20-29-27,27>>^ Para os justos, a pessoa iníqua é abominação, e o reto em seu caminho é abominação ao ímpio.

'''

xref:020-proverbios/020-proverbios-028.adoc#v20-28-0[&#60; Capítulo Anterior] | <<v20-29-0,Topo>> | xref:020-proverbios/020-proverbios-030.adoc#v20-30-0[Próximo Capítulo &#62;]