include::./index.adoc[]

[[v20-15-0]]
=== Provérbios, 15
// naa ?, NAA - Nova Almeida Atualizada

[[v20-15-1]]

^<<v20-15-1,1>>^ A resposta branda desvia o furor, mas a palavra dura suscita a ira.

[[v20-15-2]]

^<<v20-15-2,2>>^ A língua dos sábios adorna o conhecimento, mas a boca dos insensatos derrama tolices.

[[v20-15-3]]

^<<v20-15-3,3>>^ Os olhos do Senhor estão em todo lugar, contemplando os maus e os bons.

[[v20-15-4]]

^<<v20-15-4,4>>^ A língua serena é árvore de vida, mas a língua perversa esmaga o espírito.

[[v20-15-5]]

^<<v20-15-5,5>>^ O insensato despreza a instrução de seu pai, mas o que aceita a repreensão consegue a prudência.

[[v20-15-6]]

^<<v20-15-6,6>>^ Na casa do justo há grande tesouro, mas no lucro dos ímpios há infelicidade.

[[v20-15-7]]

^<<v20-15-7,7>>^ As palavras dos sábios difundem o conhecimento, mas o coração dos insensatos não procede assim.

[[v20-15-8]]

^<<v20-15-8,8>>^ O Senhor  detesta o sacrifício dos ímpios, mas a oração dos retos é o seu prazer.

[[v20-15-9]]

^<<v20-15-9,9>>^ O Senhor  detesta o caminho do ímpio, mas ama o que segue a justiça.

[[v20-15-10]]

^<<v20-15-10,10>>^ Disciplina rigorosa há para o que abandona o caminho, e quem odeia a repreensão morrerá.

[[v20-15-11]]

^<<v20-15-11,11>>^ O mundo dos mortos e o abismo estão expostos diante do Senhor ; quanto mais o coração dos filhos dos homens!

[[v20-15-12]]

^<<v20-15-12,12>>^ O zombador não gosta de quem o repreende, nem se aproxima dos sábios.

[[v20-15-13]]

^<<v20-15-13,13>>^ O coração alegre embeleza o rosto, mas com a tristeza do coração o espírito se abate.

[[v20-15-14]]

^<<v20-15-14,14>>^ O coração sábio busca o conhecimento, mas a boca dos insensatos se alimenta de estupidez.

[[v20-15-15]]

^<<v20-15-15,15>>^ Para quem está aflito, todos os dias são maus, mas a vida de quem tem o coração alegre é uma festa contínua.

[[v20-15-16]]

^<<v20-15-16,16>>^ Melhor é o pouco, havendo o temor do Senhor , do que um grande tesouro onde há inquietação.

[[v20-15-17]]

^<<v20-15-17,17>>^ Melhor é um prato de legumes onde há amor do que um boi inteiro acompanhado de ódio.

[[v20-15-18]]

^<<v20-15-18,18>>^ Quem se irrita facilmente provoca discórdia, mas quem é tardio em ficar irado acalma os conflitos.

[[v20-15-19]]

^<<v20-15-19,19>>^ O caminho do preguiçoso é como que cercado de espinhos, mas a vereda dos justos é plana.

[[v20-15-20]]

^<<v20-15-20,20>>^ O filho sábio alegra o seu pai, mas o insensato despreza a sua mãe.

[[v20-15-21]]

^<<v20-15-21,21>>^ Quem não tem juízo se alegra com a sua tolice, mas quem é sábio anda retamente.

[[v20-15-22]]

^<<v20-15-22,22>>^ Sem conselhos os projetos fracassam, mas com muitos conselheiros há sucesso.

[[v20-15-23]]

^<<v20-15-23,23>>^ Que alegria é ter a resposta adequada! Como é boa a palavra dita na hora certa!

[[v20-15-24]]

^<<v20-15-24,24>>^ Para o sábio, o caminho da vida leva para cima, para desviar do inferno, embaixo.

[[v20-15-25]]

^<<v20-15-25,25>>^ O Senhor  derruba a casa dos orgulhosos, mas preserva a herança da viúva.

[[v20-15-26]]

^<<v20-15-26,26>>^ O Senhor  detesta os planos dos maus, mas as palavras bondosas lhe são aprazíveis.

[[v20-15-27]]

^<<v20-15-27,27>>^ Quem é ávido por lucro desonesto arruína a sua casa, mas o que odeia o suborno, esse viverá.

[[v20-15-28]]

^<<v20-15-28,28>>^ O coração do justo medita o que há de responder, mas a boca dos ímpios derrama maldades.

[[v20-15-29]]

^<<v20-15-29,29>>^ O Senhor  está longe dos ímpios, mas ouve a oração dos justos.

[[v20-15-30]]

^<<v20-15-30,30>>^ O brilho nos olhos alegra o coração; uma boa notícia fortalece até os ossos.

[[v20-15-31]]

^<<v20-15-31,31>>^ Quem dá ouvidos à repreensão construtiva terá a sua morada no meio dos sábios.

[[v20-15-32]]

^<<v20-15-32,32>>^ Quem rejeita a disciplina despreza a si mesmo, mas o que aceita a repreensão adquire entendimento.

[[v20-15-33]]

^<<v20-15-33,33>>^ O temor do Senhor é instrução na sabedoria, e a humildade precede a honra.

'''

xref:020-proverbios/020-proverbios-014.adoc#v20-14-0[&#60; Capítulo Anterior] | <<v20-15-0,Topo>> | xref:020-proverbios/020-proverbios-016.adoc#v20-16-0[Próximo Capítulo &#62;]