include::./index.adoc[]

[[v20-22-0]]
=== Provérbios, 22
// naa ?, NAA - Nova Almeida Atualizada

[[v20-22-1]]

^<<v20-22-1,1>>^ Mais vale o bom nome do que as muitas riquezas; ser estimado é melhor do que a prata e o ouro.

[[v20-22-2]]

^<<v20-22-2,2>>^ O rico e o pobre têm algo em comum: o Senhor  fez tanto um como o outro.

[[v20-22-3]]

^<<v20-22-3,3>>^ O prudente vê o mal e se esconde; mas os ingênuos seguem em frente e sofrem as consequências.

[[v20-22-4]]

^<<v20-22-4,4>>^ A recompensa da humildade e do temor do Senhor são riquezas, honra e vida.

[[v20-22-5]]

^<<v20-22-5,5>>^ No caminho do perverso há espinhos e armadilhas; quem quer guardar a sua vida afasta-se deles.

[[v20-22-6]]

^<<v20-22-6,6>>^ Ensine a criança no caminho em que deve andar, e ainda quando for velho não se desviará dele.

[[v20-22-7]]

^<<v20-22-7,7>>^ O rico domina sobre o pobre, e o que pede emprestado é servo de quem empresta.

[[v20-22-8]]

^<<v20-22-8,8>>^ O que semeia a injustiça colhe a desgraça, e a vara da sua indignação será destruída.

[[v20-22-9]]

^<<v20-22-9,9>>^ O generoso será abençoado, porque reparte o seu pão com os pobres.

[[v20-22-10]]

^<<v20-22-10,10>>^ Mande embora o zombador, e com ele se irá a discórdia; cessarão as discussões e a vergonha.

[[v20-22-11]]

^<<v20-22-11,11>>^ Quem ama a pureza do coração e é habilidoso no falar terá a amizade do rei.

[[v20-22-12]]

^<<v20-22-12,12>>^ Os olhos do Senhor preservam o conhecimento, mas ele subverte as palavras dos infiéis.

[[v20-22-13]]

^<<v20-22-13,13>>^ O preguiçoso diz: "Um leão está lá fora! Serei morto no meio da rua!"

[[v20-22-14]]

^<<v20-22-14,14>>^ Cova profunda é a boca da mulher estranha; aquele contra quem o Senhor  se irar cairá nela.

[[v20-22-15]]

^<<v20-22-15,15>>^ A tolice está ligada ao coração da criança, mas a vara da disciplina a afastará dela.

[[v20-22-16]]

^<<v20-22-16,16>>^ Quem oprime o pobre para enriquecer a si ou o que dá presentes ao rico certamente empobrecerá.

[[v20-22-17]]

^<<v20-22-17,17>>^ Preste atenção e ouça as palavras dos sábios; aplique o coração aos meus ensinamentos.

[[v20-22-18]]

^<<v20-22-18,18>>^ Porque será agradável se você os guardar em seu coração e se tiver todos eles presentes nos seus lábios.

[[v20-22-19]]

^<<v20-22-19,19>>^ Quero que a sua confiança esteja no Senhor ; por isso, hoje dou esta instrução a você — a você mesmo.

[[v20-22-20]]

^<<v20-22-20,20>>^ Por acaso, não lhe escrevi trinta provérbios de conselhos e conhecimentos?

[[v20-22-21]]

^<<v20-22-21,21>>^ Fiz isso para que você tenha certeza das palavras da verdade, a fim de que possa responder claramente aos que lhe fizerem perguntas.

[[v20-22-22]]

^<<v20-22-22,22>>^ Não roube o pobre, porque é pobre, nem oprima o necessitado no tribunal,

[[v20-22-23]]

^<<v20-22-23,23>>^ porque o Senhor  defenderá a causa deles e tirará a vida daqueles que os exploram.

[[v20-22-24]]

^<<v20-22-24,24>>^ Não faça amizade com quem facilmente fica irado, nem ande na companhia de quem é agressivo,

[[v20-22-25]]

^<<v20-22-25,25>>^ para que você não aprenda os seus caminhos e, assim, fique preso numa armadilha.

[[v20-22-26]]

^<<v20-22-26,26>>^ Não esteja entre os que se comprometem e ficam por fiadores de dívidas,

[[v20-22-27]]

^<<v20-22-27,27>>^ pois, se você não tiver com que pagar, vão acabar lhe tirando até mesmo a cama em que costuma se deitar!

[[v20-22-28]]

^<<v20-22-28,28>>^ Não remova os marcos antigos que os seus pais colocaram.

[[v20-22-29]]

^<<v20-22-29,29>>^ Você está vendo alguém que é habilidoso naquilo que faz? Ele será posto diante de reis; não estará a serviço da plebe.

'''

xref:020-proverbios/020-proverbios-021.adoc#v20-21-0[&#60; Capítulo Anterior] | <<v20-22-0,Topo>> | xref:020-proverbios/020-proverbios-023.adoc#v20-23-0[Próximo Capítulo &#62;]