include::./index.adoc[]

[[v20-9-0]]
=== Provérbios, 9
// naa ?, NAA - Nova Almeida Atualizada

[[v20-9-1]]

^<<v20-9-1,1>>^ A Sabedoria construiu a sua casa, esculpiu para si sete colunas.

[[v20-9-2]]

^<<v20-9-2,2>>^ Matou os seus animais para a festa e preparou o seu vinho; também já arrumou a sua mesa.

[[v20-9-3]]

^<<v20-9-3,3>>^ Enviou as suas criadas para que, dos lugares mais altos da cidade, façam este convite:

[[v20-9-4]]

^<<v20-9-4,4>>^ "Quem é ingênuo, venha para cá." Aos que não têm juízo ela diz:

[[v20-9-5]]

^<<v20-9-5,5>>^ "Venham, comam do meu pão e bebam do vinho que preparei.

[[v20-9-6]]

^<<v20-9-6,6>>^ Afastem-se dos ingênuos e vivam; andem pelo caminho do entendimento."

[[v20-9-7]]

^<<v20-9-7,7>>^ Quem repreende o zombador traz afronta sobre si; e quem censura o ímpio será insultado.

[[v20-9-8]]

^<<v20-9-8,8>>^ Não repreenda o zombador, para que ele não odeie você; repreenda o sábio, e ele o amará.

[[v20-9-9]]

^<<v20-9-9,9>>^ Dê instrução ao sábio, e ele se tornará mais sábio ainda; ensine o justo, e ele crescerá na prudência.

[[v20-9-10]]

^<<v20-9-10,10>>^ O temor do Senhor  é o princípio da sabedoria; conhecer o Santo é ter entendimento.

[[v20-9-11]]

^<<v20-9-11,11>>^ Porque por mim se multiplicarão os seus dias, e aumentarão os anos de sua vida.

[[v20-9-12]]

^<<v20-9-12,12>>^ Se você é sábio, é sábio para si mesmo; se é zombador, só você sofrerá as consequências.

[[v20-9-13]]

^<<v20-9-13,13>>^ A loucura é mulher espalhafatosa; é tola e não sabe coisa alguma.

[[v20-9-14]]

^<<v20-9-14,14>>^ Senta-se junto à porta de sua casa, toma uma cadeira no lugar mais alto da cidade,

[[v20-9-15]]

^<<v20-9-15,15>>^ para dizer aos que passam e seguem direito o seu caminho:

[[v20-9-16]]

^<<v20-9-16,16>>^ "Quem for ingênuo, venha para cá." E aos que não têm juízo ela diz:

[[v20-9-17]]

^<<v20-9-17,17>>^ "A água roubada é doce, e o pão comido às escondidas é saboroso."

[[v20-9-18]]

^<<v20-9-18,18>>^ Eles, porém, não sabem que ali estão os mortos, que os seus convidados estão nas profundezas do inferno.

'''

xref:020-proverbios/020-proverbios-008.adoc#v20-8-0[&#60; Capítulo Anterior] | <<v20-9-0,Topo>> | xref:020-proverbios/020-proverbios-010.adoc#v20-10-0[Próximo Capítulo &#62;]