include::./index.adoc[]

[[v20-3-0]]
=== Provérbios, 3
// naa ?, NAA - Nova Almeida Atualizada

[[v20-3-1]]

^<<v20-3-1,1>>^ Meu filho, não se esqueça dos meus ensinos, e que o seu coração guarde os meus mandamentos,

[[v20-3-2]]

^<<v20-3-2,2>>^ porque eles aumentarão os seus dias e lhe acrescentarão anos de vida e paz.

[[v20-3-3]]

^<<v20-3-3,3>>^ Não deixe que a bondade e a fidelidade abandonem você. Amarre-as ao pescoço; escreva-as na tábua do seu coração

[[v20-3-4]]

^<<v20-3-4,4>>^ e você encontrará favor e boa compreensão diante de Deus e das outras pessoas.

[[v20-3-5]]

^<<v20-3-5,5>>^ Confie no Senhor de todo o seu coração e não se apoie no seu próprio entendimento.

[[v20-3-6]]

^<<v20-3-6,6>>^ Reconheça o Senhor  em todos os seus caminhos, e ele endireitará as suas veredas.

[[v20-3-7]]

^<<v20-3-7,7>>^ Não seja sábio aos seus próprios olhos; tema o Senhor  e afaste-se do mal.

[[v20-3-8]]

^<<v20-3-8,8>>^ Isto será como um remédio para o seu corpo e refrigério para os seus ossos.

[[v20-3-9]]

^<<v20-3-9,9>>^ Honre o Senhor  com os seus bens e com as primícias de toda a sua renda;

[[v20-3-10]]

^<<v20-3-10,10>>^ e os seus celeiros ficarão completamente cheios, e os seus lagares transbordarão de vinho.

[[v20-3-11]]

^<<v20-3-11,11>>^ Meu filho, não rejeite a disciplina do Senhor , nem se aborreça com a sua repreensão.

[[v20-3-12]]

^<<v20-3-12,12>>^ Porque o Senhor  repreende a quem ama, assim como um pai repreende o filho a quem quer bem.

[[v20-3-13]]

^<<v20-3-13,13>>^ Feliz é quem acha a sabedoria; feliz é aquele que alcança o entendimento.

[[v20-3-14]]

^<<v20-3-14,14>>^ Porque o lucro que a sabedoria dá é melhor do que o lucro da prata, e a sua renda é melhor do que o ouro mais fino.

[[v20-3-15]]

^<<v20-3-15,15>>^ A sabedoria é mais preciosa do que as joias, e tudo o que você possa desejar não se compara com ela.

[[v20-3-16]]

^<<v20-3-16,16>>^ Em sua mão direita ela oferece vida longa, e na sua mão esquerda ela tem riquezas e honra.

[[v20-3-17]]

^<<v20-3-17,17>>^ Os seus caminhos são caminhos agradáveis, e todas as suas veredas são paz.

[[v20-3-18]]

^<<v20-3-18,18>>^ Ela é árvore de vida para os que a alcançam, e felizes são todos os que a retêm.

[[v20-3-19]]

^<<v20-3-19,19>>^ O Senhor  com sabedoria lançou os fundamentos da terra; com inteligência estabeleceu os céus.

[[v20-3-20]]

^<<v20-3-20,20>>^ Pelo seu conhecimento os abismos se romperam, e as nuvens destilam o orvalho.

[[v20-3-21]]

^<<v20-3-21,21>>^ Meu filho, que estas coisas não se afastem dos seus olhos; guarde a verdadeira sabedoria e o discernimento;

[[v20-3-22]]

^<<v20-3-22,22>>^ porque serão vida para a sua alma e enfeite para o seu pescoço.

[[v20-3-23]]

^<<v20-3-23,23>>^ Então você andará seguro no seu caminho, e o seu pé não tropeçará.

[[v20-3-24]]

^<<v20-3-24,24>>^ Quando se deitar, você não terá medo; sim, você se deitará e o seu sono será tranquilo.

[[v20-3-25]]

^<<v20-3-25,25>>^ Não temerá o pavor repentino, nem a desgraça dos ímpios, quando vier.

[[v20-3-26]]

^<<v20-3-26,26>>^ Porque o Senhor será a sua segurança e ele não deixará que os seus pés sejam presos.

[[v20-3-27]]

^<<v20-3-27,27>>^ Não deixe de fazer o bem aos que dele precisam, estando em sua mão o poder de fazê-lo.

[[v20-3-28]]

^<<v20-3-28,28>>^ Não diga ao seu próximo: "Vá e volte mais tarde; amanhã eu terei algo para dar", se você tem isso em suas mãos agora.

[[v20-3-29]]

^<<v20-3-29,29>>^ Não planeje nenhum mal contra o seu próximo, pois ele mora ao seu lado e confia em você.

[[v20-3-30]]

^<<v20-3-30,30>>^ Não entre em litígio com alguém, se ele não tiver feito nenhum mal a você.

[[v20-3-31]]

^<<v20-3-31,31>>^ Não tenha inveja do homem violento, nem siga nenhum de seus caminhos;

[[v20-3-32]]

^<<v20-3-32,32>>^ porque o Senhor detesta o perverso, mas aos retos trata com intimidade.

[[v20-3-33]]

^<<v20-3-33,33>>^ A maldição do Senhor  está sobre a casa dos ímpios, porém a morada dos justos ele abençoa.

[[v20-3-34]]

^<<v20-3-34,34>>^ Certamente ele zomba dos zombadores, mas dá graça aos humildes.

[[v20-3-35]]

^<<v20-3-35,35>>^ Os sábios herdarão honra, mas aos tolos está reservada a vergonha.

'''

xref:020-proverbios/020-proverbios-002.adoc#v20-2-0[&#60; Capítulo Anterior] | <<v20-3-0,Topo>> | xref:020-proverbios/020-proverbios-004.adoc#v20-4-0[Próximo Capítulo &#62;]