include::./index.adoc[]

[[v20-27-0]]
=== Provérbios, 27
// naa ?, NAA - Nova Almeida Atualizada

[[v20-27-1]]

^<<v20-27-1,1>>^ Não se gabe do dia de amanhã, porque você não sabe o que ele trará à luz.

[[v20-27-2]]

^<<v20-27-2,2>>^ Deixe que outros o louvem, e não a sua própria boca; um estranho, e não você mesmo.

[[v20-27-3]]

^<<v20-27-3,3>>^ Pesada é a pedra, e a areia também; mas a ira do insensato é mais pesada do que as duas.

[[v20-27-4]]

^<<v20-27-4,4>>^ Cruel é o furor e impetuosa é a ira, mas quem pode resistir à inveja?

[[v20-27-5]]

^<<v20-27-5,5>>^ Melhor é a repreensão franca do que o amor encoberto.

[[v20-27-6]]

^<<v20-27-6,6>>^ Leais são as feridas feitas pelo que ama, porém os beijos de quem odeia são enganosos.

[[v20-27-7]]

^<<v20-27-7,7>>^ Quem está farto pisa o favo de mel, mas para o faminto até o amargo é doce.

[[v20-27-8]]

^<<v20-27-8,8>>^ Como a ave que vagueia longe do seu ninho, assim é quem anda vagueando longe do seu lar.

[[v20-27-9]]

^<<v20-27-9,9>>^ Como o óleo e o perfume alegram o coração, assim o amigo encontra doçura no conselho cordial.

[[v20-27-10]]

^<<v20-27-10,10>>^ Não abandone o seu amigo, nem o amigo do seu pai. Não vá para a casa do seu irmão no dia da adversidade; mais vale o vizinho perto do que o irmão longe.

[[v20-27-11]]

^<<v20-27-11,11>>^ Meu filho, seja sábio e alegre o meu coração, para que eu saiba responder àqueles que me afrontam.

[[v20-27-12]]

^<<v20-27-12,12>>^ O prudente vê o mal e se esconde; mas os ingênuos seguem em frente e sofrem as consequências.

[[v20-27-13]]

^<<v20-27-13,13>>^ Que se tome a roupa daquele que fica por fiador de um estranho; que ela sirva de penhor, quando ele se obriga por mulher estranha.

[[v20-27-14]]

^<<v20-27-14,14>>^ Se alguém bendiz o seu vizinho em alta voz, logo de manhã, a sua bênção soará como maldição.

[[v20-27-15]]

^<<v20-27-15,15>>^ A goteira contínua num dia chuvoso e a esposa briguenta são semelhantes;

[[v20-27-16]]

^<<v20-27-16,16>>^ contê-la seria conter o vento, seria pegar o óleo com a mão.

[[v20-27-17]]

^<<v20-27-17,17>>^ O ferro se afia com ferro, e uma pessoa, pela presença do seu próximo.

[[v20-27-18]]

^<<v20-27-18,18>>^ Quem cuida da figueira comerá do seu fruto; e o que trata bem o seu senhor será honrado.

[[v20-27-19]]

^<<v20-27-19,19>>^ Como a água reflete o rosto, assim o coração reflete o que a pessoa é.

[[v20-27-20]]

^<<v20-27-20,20>>^ O mundo dos mortos e o abismo nunca se fartam, e os olhos do ser humano nunca se satisfazem.

[[v20-27-21]]

^<<v20-27-21,21>>^ Como o crisol prova a prata e o forno prova o ouro, assim o homem é provado pelos elogios que recebe.

[[v20-27-22]]

^<<v20-27-22,22>>^ Mesmo que você moesse o insensato como se soca o cereal num pilão, a tolice não se afastaria dele.

[[v20-27-23]]

^<<v20-27-23,23>>^ Procure conhecer o estado das suas ovelhas e cuide dos seus rebanhos,

[[v20-27-24]]

^<<v20-27-24,24>>^ porque as riquezas não duram para sempre, nem a coroa, de geração em geração.

[[v20-27-25]]

^<<v20-27-25,25>>^ Quando o feno for removido, aparecerem os renovos e se recolher o capim dos montes,

[[v20-27-26]]

^<<v20-27-26,26>>^ então os cordeiros lhe darão a lã para a roupa, os bodes serão vendidos para pagar o campo

[[v20-27-27]]

^<<v20-27-27,27>>^ e as cabras produzirão leite em abundância para alimentar você, alimentar a sua casa e sustentar as suas servas.

'''

xref:020-proverbios/020-proverbios-026.adoc#v20-26-0[&#60; Capítulo Anterior] | <<v20-27-0,Topo>> | xref:020-proverbios/020-proverbios-028.adoc#v20-28-0[Próximo Capítulo &#62;]