include::./index.adoc[]

[[v20-31-0]]
=== Provérbios, 31
// naa ?, NAA - Nova Almeida Atualizada

[[v20-31-1]]

^<<v20-31-1,1>>^ Palavras do rei Lemuel, de Massá, que a mãe dele lhe ensinou.

[[v20-31-2]]

^<<v20-31-2,2>>^ O que lhe direi, meu filho, filho do meu ventre? Que lhe direi, ó filho dos meus votos?

[[v20-31-3]]

^<<v20-31-3,3>>^ Não dê às mulheres a sua força, nem os seus caminhos às que destroem os reis.

[[v20-31-4]]

^<<v20-31-4,4>>^ Não é próprio dos reis, ó Lemuel, não é próprio dos reis beber vinho, nem dos príncipes desejar bebida forte.

[[v20-31-5]]

^<<v20-31-5,5>>^ Quando eles bebem, se esquecem da lei e pervertem o direito de todos os aflitos.

[[v20-31-6]]

^<<v20-31-6,6>>^ Deem bebida forte aos que estão morrendo e vinho, aos amargurados de espírito;

[[v20-31-7]]

^<<v20-31-7,7>>^ para que bebam e se esqueçam da sua pobreza, e não se lembrem mais da sua miséria.

[[v20-31-8]]

^<<v20-31-8,8>>^ Abra a boca a favor do mudo, pelo direito de todos os desamparados.

[[v20-31-9]]

^<<v20-31-9,9>>^ Abra a boca, julgue retamente e faça justiça aos pobres e aos necessitados.

[[v20-31-10]]

^<<v20-31-10,10>>^ Mulher virtuosa, quem a achará? O seu valor muito excede o de finas joias.

[[v20-31-11]]

^<<v20-31-11,11>>^ O coração do seu marido confia nela, e não haverá falta de ganho.

[[v20-31-12]]

^<<v20-31-12,12>>^ Ela lhe faz bem e não mal, todos os dias da sua vida.

[[v20-31-13]]

^<<v20-31-13,13>>^ Busca lã e linho e de bom grado trabalha com as mãos.

[[v20-31-14]]

^<<v20-31-14,14>>^ É como o navio mercante: de longe traz o seu pão.

[[v20-31-15]]

^<<v20-31-15,15>>^ É ainda noite, e ela já se levanta, e dá mantimento à sua casa e tarefa às suas servas.

[[v20-31-16]]

^<<v20-31-16,16>>^ Ela examina uma propriedade e adquire-a; planta uma vinha com a renda do seu trabalho.

[[v20-31-17]]

^<<v20-31-17,17>>^ Cinge os lombos com força e fortalece os seus braços.

[[v20-31-18]]

^<<v20-31-18,18>>^ Ela percebe que o seu ganho é bom; a sua lâmpada não se apaga de noite.

[[v20-31-19]]

^<<v20-31-19,19>>^ Estende as mãos ao fuso, mãos que pegam na roca.

[[v20-31-20]]

^<<v20-31-20,20>>^ Abre a mão aos aflitos; e ainda a estende aos necessitados.

[[v20-31-21]]

^<<v20-31-21,21>>^ Quanto à sua casa, não teme a neve, pois todos andam vestidos de lã escarlate.

[[v20-31-22]]

^<<v20-31-22,22>>^ Faz para si cobertas, veste-se de linho fino e de púrpura.

[[v20-31-23]]

^<<v20-31-23,23>>^ Seu marido é estimado entre os juízes, quando se assenta com os anciãos da terra.

[[v20-31-24]]

^<<v20-31-24,24>>^ Ela faz roupas de linho fino e as vende; ela fornece cintas aos comerciantes.

[[v20-31-25]]

^<<v20-31-25,25>>^ A força e a dignidade são os seus vestidos, e, quanto ao dia de amanhã, não tem preocupações.

[[v20-31-26]]

^<<v20-31-26,26>>^ Fala com sabedoria, e a instrução da bondade está na sua língua.

[[v20-31-27]]

^<<v20-31-27,27>>^ Cuida do bom andamento da sua casa e não come o pão da preguiça.

[[v20-31-28]]

^<<v20-31-28,28>>^ Seus filhos se levantam e a chamam de bem-aventurada; seu marido a louva, dizendo:

[[v20-31-29]]

^<<v20-31-29,29>>^ "Muitas mulheres são virtuosas no que fazem, mas você supera todas elas."

[[v20-31-30]]

^<<v20-31-30,30>>^ Enganosa é a graça, e vã é a formosura, mas a mulher que teme o Senhor , essa será louvada.

[[v20-31-31]]

^<<v20-31-31,31>>^ Deem a ela o fruto das suas mãos, e que de público as suas obras a louvem.

'''

xref:020-proverbios/020-proverbios-030.adoc#v20-30-0[&#60; Capítulo Anterior] | <<v20-31-0,Topo>> | xref:021-eclesiastes/021-eclesiastes-001.adoc#v21-1-0[Próximo Capítulo &#62;]