include::./index.adoc[]

[[v20-1-0]]
=== Provérbios, 1
// naa ?, NAA - Nova Almeida Atualizada

[[v20-1-1]]

^<<v20-1-1,1>>^ Provérbios de Salomão, filho de Davi, rei de Israel,

[[v20-1-2]]

^<<v20-1-2,2>>^ para aprender a sabedoria e o ensino; para entender as palavras de inteligência;

[[v20-1-3]]

^<<v20-1-3,3>>^ para obter o ensino do bom proceder, a justiça, o juízo e a equidade;

[[v20-1-4]]

^<<v20-1-4,4>>^ para dar prudência aos simples e conhecimento e discernimento aos jovens.

[[v20-1-5]]

^<<v20-1-5,5>>^ Que o sábio ouça e cresça em prudência; e que o instruído adquira habilidade

[[v20-1-6]]

^<<v20-1-6,6>>^ para entender provérbios e parábolas, as palavras e os enigmas dos sábios.

[[v20-1-7]]

^<<v20-1-7,7>>^ O temor do Senhor é o princípio do saber, mas os insensatos desprezam a sabedoria e o ensino.

[[v20-1-8]]

^<<v20-1-8,8>>^ Meu filho, ouça o ensino de seu pai e não despreze a instrução de sua mãe.

[[v20-1-9]]

^<<v20-1-9,9>>^ Porque serão um diadema de graça para a sua cabeça e colares para o seu pescoço.

[[v20-1-10]]

^<<v20-1-10,10>>^ Meu filho, se os pecadores quiserem seduzir você, não consinta.

[[v20-1-11]]

^<<v20-1-11,11>>^ Talvez eles digam: "Venha conosco! Vamos preparar uma emboscada para matar alguém; vamos espreitar os inocentes, ainda que sem motivo.

[[v20-1-12]]

^<<v20-1-12,12>>^ Vamos engoli-los vivos, como o mundo dos mortos, e inteiros, como os que descem ao abismo.

[[v20-1-13]]

^<<v20-1-13,13>>^ Acharemos todo tipo de bens preciosos; encheremos a nossa casa de despojos.

[[v20-1-14]]

^<<v20-1-14,14>>^ Junte-se a nós! Teremos todos uma só bolsa."

[[v20-1-15]]

^<<v20-1-15,15>>^ Meu filho, não se ponha a caminho com eles; fique com os seus pés longe das suas veredas!

[[v20-1-16]]

^<<v20-1-16,16>>^ Porque os pés deles correm para o mal e se apressam a derramar sangue.

[[v20-1-17]]

^<<v20-1-17,17>>^ Pois em vão se estende a rede se a ave estiver olhando;

[[v20-1-18]]

^<<v20-1-18,18>>^ mas estes armam emboscadas contra o seu próprio sangue e ficam à espreita contra a própria vida.

[[v20-1-19]]

^<<v20-1-19,19>>^ Este é o fim de todo ganancioso; e este espírito de ganância tira a vida de quem o possui.

[[v20-1-20]]

^<<v20-1-20,20>>^ A Sabedoria grita nas ruas; nas praças, levanta a sua voz.

[[v20-1-21]]

^<<v20-1-21,21>>^ Do alto das muralhas clama, à entrada dos portões e nas cidades profere as suas palavras:

[[v20-1-22]]

^<<v20-1-22,22>>^ "Até quando vocês, ingênuos, amarão a ingenuidade? E vocês, zombadores, até quando terão prazer na zombaria? E vocês, tolos, até quando odiarão o conhecimento?

[[v20-1-23]]

^<<v20-1-23,23>>^ Deem ouvidos à minha repreensão; eis que derramarei o meu espírito sobre vocês e lhes darei a conhecer as minhas palavras.

[[v20-1-24]]

^<<v20-1-24,24>>^ Mas porque clamei, e vocês se recusaram a ouvir; porque estendi a minha mão, e não houve quem atendesse;

[[v20-1-25]]

^<<v20-1-25,25>>^ — pelo contrário, rejeitaram todo o meu conselho e não quiseram a minha repreensão —

[[v20-1-26]]

^<<v20-1-26,26>>^ também eu darei risada da desgraça de vocês; ficarei zombando quando chegar o terror,

[[v20-1-27]]

^<<v20-1-27,27>>^ quando o terror chegar como a tormenta, quando a calamidade chegar como o redemoinho, quando lhes sobrevierem o aperto e a angústia.

[[v20-1-28]]

^<<v20-1-28,28>>^ Então eles me invocarão, mas eu não responderei; sairão à minha procura, porém não me encontrarão.

[[v20-1-29]]

^<<v20-1-29,29>>^ Porque odiaram o conhecimento e não preferiram o temor do Senhor ;

[[v20-1-30]]

^<<v20-1-30,30>>^ não quiseram o meu conselho e desprezaram toda a minha repreensão.

[[v20-1-31]]

^<<v20-1-31,31>>^ Portanto, comerão do fruto da sua conduta e dos seus próprios conselhos se fartarão.

[[v20-1-32]]

^<<v20-1-32,32>>^ Os ingênuos são mortos porque se desviam da sabedoria; os tolos são destruídos por estarem satisfeitos consigo mesmos.

[[v20-1-33]]

^<<v20-1-33,33>>^ Mas o que me der ouvidos habitará seguro, tranquilo e sem temor do mal."

'''

xref:019-salmos/019-salmos-150.adoc#v19-150-0[&#60; Capítulo Anterior] | <<v20-1-0,Topo>> | xref:020-proverbios/020-proverbios-002.adoc#v20-2-0[Próximo Capítulo &#62;]