include::./index.adoc[]

[[v20-24-0]]
=== Provérbios, 24
// naa ?, NAA - Nova Almeida Atualizada

[[v20-24-1]]

^<<v20-24-1,1>>^ Não tenha inveja dos maus nem queira estar com eles,

[[v20-24-2]]

^<<v20-24-2,2>>^ porque o coração deles planeja a violência, e os seus lábios falam para ferir.

[[v20-24-3]]

^<<v20-24-3,3>>^ Com a sabedoria se constrói a casa, e com a inteligência ela se firma;

[[v20-24-4]]

^<<v20-24-4,4>>^ pelo conhecimento os seus cômodos se encherão de todo tipo de bens, preciosos e agradáveis.

[[v20-24-5]]

^<<v20-24-5,5>>^ Quem é sábio é forte, e aquele que tem conhecimento consolida a sua força.

[[v20-24-6]]

^<<v20-24-6,6>>^ Porque com prudência você deve fazer a guerra; na multidão de conselheiros está a vitória.

[[v20-24-7]]

^<<v20-24-7,7>>^ A sabedoria é elevada demais para o insensato; no tribunal, ele não abre a boca.

[[v20-24-8]]

^<<v20-24-8,8>>^ Quem só pensa em fazer o mal será chamado "mestre de intrigas".

[[v20-24-9]]

^<<v20-24-9,9>>^ Os planos do tolo são pecado, e o zombador é abominável às pessoas.

[[v20-24-10]]

^<<v20-24-10,10>>^ Se você se mostra fraco no dia da angústia, é porque a sua força é pequena.

[[v20-24-11]]

^<<v20-24-11,11>>^ Liberte os que estão sendo levados para a morte e salve os que cambaleiam ao ser levados para a matança.

[[v20-24-12]]

^<<v20-24-12,12>>^ Você poderá dizer: "Não sabíamos de nada!" Mas será que aquele que pesa os corações não o perceberá? Aquele que atenta para a sua alma não ficará sabendo? E não pagará ele a cada um segundo as suas obras?

[[v20-24-13]]

^<<v20-24-13,13>>^ Meu filho, coma mel, porque é saudável, e o favo, porque é doce ao seu paladar.

[[v20-24-14]]

^<<v20-24-14,14>>^ Saiba que assim é a sabedoria para a sua alma. Se você a encontrar, haverá um futuro, e a sua esperança não será frustrada.

[[v20-24-15]]

^<<v20-24-15,15>>^ Não espie a habitação do justo, ó perverso, nem destrua o lugar do seu repouso,

[[v20-24-16]]

^<<v20-24-16,16>>^ porque sete vezes cairá o justo e se levantará; mas os perversos são derrubados pela calamidade.

[[v20-24-17]]

^<<v20-24-17,17>>^ Quando o seu inimigo cair, não se alegre, nem se regozije o seu coração quando ele tropeçar,

[[v20-24-18]]

^<<v20-24-18,18>>^ para que o Senhor  não veja isso e se desagrade, e desvie do inimigo a sua ira.

[[v20-24-19]]

^<<v20-24-19,19>>^ Não se irrite por causa dos malfeitores, nem tenha inveja dos ímpios,

[[v20-24-20]]

^<<v20-24-20,20>>^ porque os maus não terão futuro, e a lâmpada dos ímpios se apagará.

[[v20-24-21]]

^<<v20-24-21,21>>^ Meu filho, tema o Senhor  e o rei; não se meta com os revoltosos,

[[v20-24-22]]

^<<v20-24-22,22>>^ porque de repente serão destruídos, e a ruína que virá do Senhor e do rei, quem a conhecerá?

[[v20-24-23]]

^<<v20-24-23,23>>^ Estes também são provérbios dos sábios. Parcialidade no julgamento não é bom.

[[v20-24-24]]

^<<v20-24-24,24>>^ Quem disser ao ímpio: "Você é justo" será amaldiçoado pelos povos e detestado pelas nações.

[[v20-24-25]]

^<<v20-24-25,25>>^ Mas haverá bem-estar para os que repreenderem o ímpio, e sobre eles virão grandes bênçãos.

[[v20-24-26]]

^<<v20-24-26,26>>^ Como beijo nos lábios, assim é a resposta com palavras sinceras.

[[v20-24-27]]

^<<v20-24-27,27>>^ Cuide dos seus negócios lá fora, apronte a lavoura no campo e, depois, edifique a sua casa.

[[v20-24-28]]

^<<v20-24-28,28>>^ Não testemunhe sem motivo contra o seu próximo, nem o engane com os seus lábios.

[[v20-24-29]]

^<<v20-24-29,29>>^ Não diga: "Vou fazer com ele o mesmo que ele fez comigo; pagarei a cada um segundo as suas obras."

[[v20-24-30]]

^<<v20-24-30,30>>^ Passei pelo campo do preguiçoso e junto à vinha do homem sem juízo.

[[v20-24-31]]

^<<v20-24-31,31>>^ Eis que tudo estava cheio de espinhos e coberto de urtigas; e o muro de pedra estava em ruínas.

[[v20-24-32]]

^<<v20-24-32,32>>^ Ao contemplar aquilo, eu fiquei pensando; olhei, e tirei a seguinte lição:

[[v20-24-33]]

^<<v20-24-33,33>>^ Um pouco de sono, um breve cochilo, braços cruzados para descansar,

[[v20-24-34]]

^<<v20-24-34,34>>^ e a sua pobreza virá como um ladrão, a miséria atacará como um homem armado.

'''

xref:020-proverbios/020-proverbios-023.adoc#v20-23-0[&#60; Capítulo Anterior] | <<v20-24-0,Topo>> | xref:020-proverbios/020-proverbios-025.adoc#v20-25-0[Próximo Capítulo &#62;]