include::./index.adoc[]

[[v20-11-0]]
=== Provérbios, 11
// naa ?, NAA - Nova Almeida Atualizada

[[v20-11-1]]

^<<v20-11-1,1>>^ O Senhor  detesta balanças desonestas, mas o peso justo é o seu prazer.

[[v20-11-2]]

^<<v20-11-2,2>>^ Quando vem a soberba, a desgraça não tarda, mas com os humildes está a sabedoria.

[[v20-11-3]]

^<<v20-11-3,3>>^ A integridade dos retos os guia, mas a falsidade dos infiéis os destruirá.

[[v20-11-4]]

^<<v20-11-4,4>>^ As riquezas não servem para nada no dia da ira, mas a justiça livra da morte.

[[v20-11-5]]

^<<v20-11-5,5>>^ A justiça do íntegro endireita o seu caminho, mas o ímpio cai pela sua impiedade.

[[v20-11-6]]

^<<v20-11-6,6>>^ A justiça dos retos os livrará, mas os infiéis serão apanhados na sua própria ambição.

[[v20-11-7]]

^<<v20-11-7,7>>^ Quando morre o ímpio, morre a sua esperança, e o que ele esperava do seu poder se dissipa.

[[v20-11-8]]

^<<v20-11-8,8>>^ O justo é libertado da angústia, mas o ímpio a recebe em lugar dele.

[[v20-11-9]]

^<<v20-11-9,9>>^ O ímpio destrói o próximo com o que diz, mas os justos são libertados pelo conhecimento.

[[v20-11-10]]

^<<v20-11-10,10>>^ A cidade se alegra com o bem-estar dos justos, mas dá gritos de alegria quando perecem os ímpios.

[[v20-11-11]]

^<<v20-11-11,11>>^ Pela bênção dos retos a cidade é exaltada, mas pela boca dos ímpios é destruída.

[[v20-11-12]]

^<<v20-11-12,12>>^ Quem fala mal do seu próximo não tem juízo; o homem prudente se cala.

[[v20-11-13]]

^<<v20-11-13,13>>^ O mexeriqueiro revela os segredos, mas o fiel de espírito os encobre.

[[v20-11-14]]

^<<v20-11-14,14>>^ Não havendo direção sábia, o povo fracassa; com muitos conselheiros, há segurança.

[[v20-11-15]]

^<<v20-11-15,15>>^ Quem fica por fiador de um estranho acaba tendo um problema, mas o que foge de ser fiador estará seguro.

[[v20-11-16]]

^<<v20-11-16,16>>^ A mulher bondosa alcança honra; os poderosos adquirem riqueza.

[[v20-11-17]]

^<<v20-11-17,17>>^ O homem bondoso faz bem a si mesmo, mas o cruel fere a si mesmo.

[[v20-11-18]]

^<<v20-11-18,18>>^ O ímpio recebe um salário ilusório, mas o que semeia justiça terá recompensa verdadeira.

[[v20-11-19]]

^<<v20-11-19,19>>^ Tão certo como a justiça conduz para a vida, quem segue o mal caminha para a morte.

[[v20-11-20]]

^<<v20-11-20,20>>^ O Senhor  detesta os perversos de coração, mas os que andam com integridade são o seu prazer.

[[v20-11-21]]

^<<v20-11-21,21>>^ É evidente que os maus serão castigados, mas a geração dos justos será poupada.

[[v20-11-22]]

^<<v20-11-22,22>>^ Como joia de ouro em focinho de porco, assim é a mulher bonita que não tem juízo.

[[v20-11-23]]

^<<v20-11-23,23>>^ O desejo dos justos tende somente para o bem, mas a expectativa dos ímpios resulta em ira.

[[v20-11-24]]

^<<v20-11-24,24>>^ Uns dão com generosidade e têm cada vez mais; outros retêm mais do que é justo e acabam na pobreza.

[[v20-11-25]]

^<<v20-11-25,25>>^ A pessoa generosa prosperará, e quem dá de beber terá a sua sede saciada.

[[v20-11-26]]

^<<v20-11-26,26>>^ O povo amaldiçoa quem retém o trigo, mas bênção virá sobre a cabeça daquele que o vende.

[[v20-11-27]]

^<<v20-11-27,27>>^ Quem procura o bem alcança favor; quem corre atrás do mal acaba encontrando o que procura.

[[v20-11-28]]

^<<v20-11-28,28>>^ Quem confia nas suas riquezas cairá, mas os justos reverdecerão como as folhagens.

[[v20-11-29]]

^<<v20-11-29,29>>^ Aquele que perturba a sua casa herdará o vento, e o insensato será servo do sábio de coração.

[[v20-11-30]]

^<<v20-11-30,30>>^ O fruto do justo é árvore de vida, e o que ganha almas é sábio.

[[v20-11-31]]

^<<v20-11-31,31>>^ Se o justo é punido na terra, quanto mais o ímpio e o pecador!

'''

xref:020-proverbios/020-proverbios-010.adoc#v20-10-0[&#60; Capítulo Anterior] | <<v20-11-0,Topo>> | xref:020-proverbios/020-proverbios-012.adoc#v20-12-0[Próximo Capítulo &#62;]