include::./index.adoc[]

[[v40-19-0]]
=== Mateus, 19
// naa ?, NAA - Nova Almeida Atualizada

[[v40-19-1]]

^<<v40-19-1,1>>^ Quando Jesus acabou de proferir estas palavras, deixou a Galileia e foi para o território da Judeia, além do Jordão.

[[v40-19-2]]

^<<v40-19-2,2>>^ Grandes multidões o seguiram, e ele as curou ali.

[[v40-19-3]]

^<<v40-19-3,3>>^ Alguns fariseus se aproximaram de Jesus e, testando-o, perguntaram: — É lícito ao homem repudiar a sua mulher por qualquer motivo?

[[v40-19-4]]

^<<v40-19-4,4>>^ Jesus respondeu: — Vocês não leram que o Criador, desde o princípio, os fez homem e mulher

[[v40-19-5]]

^<<v40-19-5,5>>^ e que disse: "Por isso o homem deixará o seu pai e a sua mãe e se unirá à sua mulher, tornando-se os dois uma só carne"?

[[v40-19-6]]

^<<v40-19-6,6>>^ De modo que já não são mais dois, porém uma só carne. Portanto, que ninguém separe o que Deus ajuntou.

[[v40-19-7]]

^<<v40-19-7,7>>^ Os fariseus perguntaram: — Então por que Moisés ordenou dar uma carta de divórcio e repudiar a mulher?

[[v40-19-8]]

^<<v40-19-8,8>>^ Jesus respondeu: — Foi por causa da dureza do coração de vocês que Moisés permitiu que vocês repudiassem a mulher, mas não foi assim desde o princípio.

[[v40-19-9]]

^<<v40-19-9,9>>^ Eu, porém, lhes digo: quem repudiar a sua mulher, não sendo por causa de relações sexuais ilícitas, e casar com outra comete adultério.

[[v40-19-10]]

^<<v40-19-10,10>>^ Os discípulos de Jesus disseram: — Se essa é a situação do homem em relação à sua mulher, não convém casar.

[[v40-19-11]]

^<<v40-19-11,11>>^ Jesus, porém, lhes respondeu: — Nem todos são aptos para aceitar este ensinamento, mas apenas aqueles a quem isso é dado.

[[v40-19-12]]

^<<v40-19-12,12>>^ Porque há eunucos de nascença; há outros a quem os homens fizeram tais; e há outros que se fizeram eunucos, por causa do Reino dos Céus. Quem é apto para aceitar isto, que aceite.

[[v40-19-13]]

^<<v40-19-13,13>>^ Então trouxeram algumas crianças a Jesus para que ele lhes impusesse as mãos e orasse, mas os discípulos os repreendiam.

[[v40-19-14]]

^<<v40-19-14,14>>^ Jesus, porém, disse: — Deixem os pequeninos e não os impeçam de vir a mim, porque dos tais é o Reino dos Céus.

[[v40-19-15]]

^<<v40-19-15,15>>^ E, tendo-lhes imposto as mãos, retirou-se dali.

[[v40-19-16]]

^<<v40-19-16,16>>^ E eis que alguém, aproximando-se de Jesus, lhe perguntou: — Mestre, que farei de bom para alcançar a vida eterna?

[[v40-19-17]]

^<<v40-19-17,17>>^ Jesus respondeu: — Por que você me pergunta a respeito do que é bom? Bom só existe um. Mas, se você quer entrar na vida, guarde os mandamentos.

[[v40-19-18]]

^<<v40-19-18,18>>^ E ele lhe perguntou: — Quais? Jesus respondeu: — "Não mate, não cometa adultério, não furte, não dê falso testemunho;

[[v40-19-19]]

^<<v40-19-19,19>>^ honre o seu pai e a sua mãe e ame o seu próximo como você ama a si mesmo."

[[v40-19-20]]

^<<v40-19-20,20>>^ O jovem disse: — Tudo isso tenho observado. O que me falta ainda?

[[v40-19-21]]

^<<v40-19-21,21>>^ Jesus respondeu: — Se você quer ser perfeito, vá, venda os seus bens, dê o dinheiro aos pobres e você terá um tesouro nos céus; depois, venha e siga-me.

[[v40-19-22]]

^<<v40-19-22,22>>^ Mas o jovem, ouvindo esta palavra, retirou-se triste, porque era dono de muitas propriedades.

[[v40-19-23]]

^<<v40-19-23,23>>^ Então Jesus disse aos seus discípulos: — Em verdade lhes digo que um rico dificilmente entrará no Reino dos Céus.

[[v40-19-24]]

^<<v40-19-24,24>>^ E ainda lhes digo que é mais fácil um camelo passar pelo fundo de uma agulha do que um rico entrar no Reino de Deus.

[[v40-19-25]]

^<<v40-19-25,25>>^ Ouvindo isto, os discípulos ficaram muito admirados e perguntaram: — Sendo assim, quem pode ser salvo?

[[v40-19-26]]

^<<v40-19-26,26>>^ Jesus, olhando para eles, disse: — Para os seres humanos isto é impossível, mas para Deus tudo é possível.

[[v40-19-27]]

^<<v40-19-27,27>>^ Então Pedro, tomando a palavra, disse: — Eis que nós deixamos tudo e seguimos o senhor; que será, pois, de nós?

[[v40-19-28]]

^<<v40-19-28,28>>^ Jesus lhes respondeu: — Em verdade lhes digo que, na regeneração, quando o Filho do Homem se assentar no trono da sua glória, vocês que me seguiram também se assentarão em doze tronos para julgar as doze tribos de Israel.

[[v40-19-29]]

^<<v40-19-29,29>>^ E todo aquele que tiver deixado casas, irmãos, irmãs, pai, mãe, filhos ou campos, por causa do meu nome, receberá muitas vezes mais e herdará a vida eterna.

[[v40-19-30]]

^<<v40-19-30,30>>^ Porém muitos primeiros serão últimos; e os últimos serão primeiros.

'''

xref:040-mateus/040-mateus-018.adoc#v40-18-0[&#60; Capítulo Anterior] | <<v40-19-0,Topo>> | xref:040-mateus/040-mateus-020.adoc#v40-20-0[Próximo Capítulo &#62;]