include::./index.adoc[]

[[v40-4-0]]
=== Mateus, 4
// naa ?, NAA - Nova Almeida Atualizada

[[v40-4-1]]

^<<v40-4-1,1>>^ A seguir, Jesus foi levado pelo Espírito ao deserto, para ser tentado pelo diabo.

[[v40-4-2]]

^<<v40-4-2,2>>^ E, depois de jejuar quarenta dias e quarenta noites, teve fome.

[[v40-4-3]]

^<<v40-4-3,3>>^ Então o tentador, aproximando-se, disse a Jesus: — Se você é o Filho de Deus, mande que estas pedras se transformem em pães.

[[v40-4-4]]

^<<v40-4-4,4>>^ Jesus, porém, respondeu: — Está escrito: "O ser humano não viverá só de pão, mas de toda palavra que procede da boca de Deus."

[[v40-4-5]]

^<<v40-4-5,5>>^ Então o diabo levou Jesus à Cidade Santa, colocou-o sobre o pináculo do templo

[[v40-4-6]]

^<<v40-4-6,6>>^ e disse: — Se você é o Filho de Deus, jogue-se daqui, porque está escrito: "Aos seus anjos ele dará ordens a seu respeito. E eles o sustentarão nas suas mãos, para que você não tropece em alguma pedra."

[[v40-4-7]]

^<<v40-4-7,7>>^ Jesus respondeu: — Também está escrito: "Não ponha à prova o Senhor, seu Deus."

[[v40-4-8]]

^<<v40-4-8,8>>^ O diabo ainda levou Jesus a um monte muito alto, mostrou-lhe todos os reinos do mundo e a glória deles

[[v40-4-9]]

^<<v40-4-9,9>>^ e disse: — Tudo isso lhe darei se, prostrado, você me adorar.

[[v40-4-10]]

^<<v40-4-10,10>>^ Então Jesus lhe ordenou: — Vá embora, Satanás, porque está escrito: "Adore o Senhor, seu Deus, e preste culto somente a ele."

[[v40-4-11]]

^<<v40-4-11,11>>^ Com isto, o diabo deixou Jesus, e eis que vieram anjos e o serviram.

[[v40-4-12]]

^<<v40-4-12,12>>^ Ao ouvir que João tinha sido preso, Jesus voltou para a Galileia.

[[v40-4-13]]

^<<v40-4-13,13>>^ E, deixando Nazaré, foi morar em Cafarnaum, situada à beira-mar, na região de Zebulom e Naftali.

[[v40-4-14]]

^<<v40-4-14,14>>^ Isso aconteceu para se cumprir o que tinha sido dito por meio do profeta Isaías:

[[v40-4-15]]

^<<v40-4-15,15>>^ "Terra de Zebulom, terra de Naftali, caminho do mar, além do Jordão, Galileia dos gentios!

[[v40-4-16]]

^<<v40-4-16,16>>^ O povo que vivia em trevas viu grande luz, e aos que viviam na região e sombra da morte resplandeceu-lhes a luz."

[[v40-4-17]]

^<<v40-4-17,17>>^ Daí em diante Jesus começou a pregar e a dizer: — Arrependam-se, porque está próximo o Reino dos Céus.

[[v40-4-18]]

^<<v40-4-18,18>>^ Caminhando junto ao mar da Galileia, Jesus viu dois irmãos, Simão, chamado Pedro, e André. Eles lançavam as redes ao mar, porque eram pescadores.

[[v40-4-19]]

^<<v40-4-19,19>>^ Jesus lhes disse: — Venham comigo, e eu os farei pescadores de gente.

[[v40-4-20]]

^<<v40-4-20,20>>^ Então eles deixaram imediatamente as redes e o seguiram.

[[v40-4-21]]

^<<v40-4-21,21>>^ Pouco mais adiante, Jesus viu outros dois irmãos, Tiago, filho de Zebedeu, e João, o irmão dele. Eles estavam no barco em companhia de seu pai, consertando as redes; e Jesus os chamou.

[[v40-4-22]]

^<<v40-4-22,22>>^ Então eles, no mesmo instante, deixaram o barco e seu pai e seguiram Jesus.

[[v40-4-23]]

^<<v40-4-23,23>>^ Jesus percorria toda a Galileia, ensinando nas sinagogas, pregando o evangelho do Reino e curando todo tipo de doenças e enfermidades entre o povo.

[[v40-4-24]]

^<<v40-4-24,24>>^ E a sua fama correu por toda a Síria. Trouxeram-lhe, então, todos os doentes, acometidos de várias enfermidades e tormentos: endemoniados, epilépticos e paralíticos. E ele os curou.

[[v40-4-25]]

^<<v40-4-25,25>>^ E da Galileia, de Decápolis, de Jerusalém, da Judeia e do outro lado do Jordão numerosas multidões o seguiam.

'''

xref:040-mateus/040-mateus-003.adoc#v40-3-0[&#60; Capítulo Anterior] | <<v40-4-0,Topo>> | xref:040-mateus/040-mateus-005.adoc#v40-5-0[Próximo Capítulo &#62;]