include::./index.adoc[]

[[v40-21-0]]
=== Mateus, 21
// naa ?, NAA - Nova Almeida Atualizada

[[v40-21-1]]

^<<v40-21-1,1>>^ Quando se aproximaram de Jerusalém e chegaram a Betfagé, ao monte das Oliveiras, Jesus enviou dois discípulos,

[[v40-21-2]]

^<<v40-21-2,2>>^ dizendo-lhes: — Vão até a aldeia que está diante de vocês e logo encontrarão presa uma jumenta e, com ela, um jumentinho. Desprendam e tragam para mim.

[[v40-21-3]]

^<<v40-21-3,3>>^ E, se alguém disser alguma coisa, respondam: "O Senhor precisa deles." E logo ele deixará que vocês tragam os animais.

[[v40-21-4]]

^<<v40-21-4,4>>^ Ora, isto aconteceu para se cumprir o que foi dito por meio do profeta:

[[v40-21-5]]

^<<v40-21-5,5>>^ "Digam à filha de Sião: Eis que o seu Rei vem até você, humilde, montado em jumenta, e num jumentinho, cria de animal de carga."

[[v40-21-6]]

^<<v40-21-6,6>>^ Indo os discípulos e tendo feito como Jesus lhes havia ordenado,

[[v40-21-7]]

^<<v40-21-7,7>>^ trouxeram a jumenta e o jumentinho. Então puseram em cima deles as suas capas, e sobre elas Jesus montou.

[[v40-21-8]]

^<<v40-21-8,8>>^ E a maior parte da multidão estendeu as suas capas no caminho, e outros cortavam ramos de árvores, espalhando-os pelo caminho.

[[v40-21-9]]

^<<v40-21-9,9>>^ E as multidões, tanto as que iam adiante dele como as que o seguiam, clamavam: "Hosana ao Filho de Davi! Bendito o que vem em nome do Senhor! Hosana nas maiores alturas!"

[[v40-21-10]]

^<<v40-21-10,10>>^ E, quando Jesus entrou em Jerusalém, toda a cidade se alvoroçou. E perguntavam: — Quem é este?

[[v40-21-11]]

^<<v40-21-11,11>>^ E as multidões respondiam: — Este é o profeta Jesus, de Nazaré da Galileia!

[[v40-21-12]]

^<<v40-21-12,12>>^ Jesus entrou no templo e expulsou todos os que ali vendiam e compravam. Derrubou as mesas dos cambistas e as cadeiras dos que vendiam pombas.

[[v40-21-13]]

^<<v40-21-13,13>>^ E disse-lhes: — Está escrito: "A minha casa será chamada ‘Casa de Oração’." Mas vocês estão fazendo dela um covil de salteadores.

[[v40-21-14]]

^<<v40-21-14,14>>^ Cegos e coxos se aproximaram de Jesus, no templo, e ele os curou.

[[v40-21-15]]

^<<v40-21-15,15>>^ Mas, quando os principais sacerdotes e os escribas viram as maravilhas que Jesus fazia e as crianças que gritavam no templo: "Hosana ao Filho de Davi!", ficaram indignados e perguntaram a Jesus:

[[v40-21-16]]

^<<v40-21-16,16>>^ — Você está ouvindo o que estão dizendo? Jesus respondeu: — Sim! Vocês nunca leram: "Da boca de pequeninos e crianças de peito tiraste o perfeito louvor"?

[[v40-21-17]]

^<<v40-21-17,17>>^ E, deixando-os, saiu da cidade e foi para Betânia, onde passou a noite.

[[v40-21-18]]

^<<v40-21-18,18>>^ Cedo de manhã, ao voltar para a cidade, Jesus teve fome.

[[v40-21-19]]

^<<v40-21-19,19>>^ E, vendo uma figueira à beira do caminho, aproximou-se dela, mas não encontrou nada, a não ser folhas. Então Jesus disse à figueira: — Nunca mais nasça fruto de você! E a figueira secou imediatamente.

[[v40-21-20]]

^<<v40-21-20,20>>^ Quando os discípulos viram isso, ficaram admirados e disseram: — Como a figueira secou depressa!

[[v40-21-21]]

^<<v40-21-21,21>>^ Ao que Jesus lhes disse: — Em verdade lhes digo que, se tiverem fé e não duvidarem, não somente farão o que foi feito à figueira, mas até mesmo, se disserem a este monte: "Levante-se e jogue-se no mar", assim será feito.

[[v40-21-22]]

^<<v40-21-22,22>>^ E tudo o que pedirem em oração, crendo, vocês receberão.

[[v40-21-23]]

^<<v40-21-23,23>>^ Jesus entrou no templo e, quando já estava ensinando, os principais sacerdotes e os anciãos do povo se aproximaram dele e perguntaram: — Com que autoridade você faz estas coisas? E quem lhe deu esta autoridade?

[[v40-21-24]]

^<<v40-21-24,24>>^ Jesus respondeu: — Eu também vou fazer uma pergunta a vocês. Se me responderem, também eu lhes direi com que autoridade faço estas coisas.

[[v40-21-25]]

^<<v40-21-25,25>>^ De onde era o batismo de João: do céu ou dos homens? E eles discutiam entre si: — Se dissermos: "Do céu", ele nos dirá: "Então por que não acreditaram nele?"

[[v40-21-26]]

^<<v40-21-26,26>>^ Mas, se dissermos: "Dos homens", é de temer o povo. Porque todos consideram João um profeta.

[[v40-21-27]]

^<<v40-21-27,27>>^ Então responderam a Jesus: — Não sabemos. E ele, por sua vez, lhes disse: — Então eu também não lhes digo com que autoridade faço estas coisas.

[[v40-21-28]]

^<<v40-21-28,28>>^ — O que vocês acham? Um homem tinha dois filhos. Chegando-se ao primeiro, disse: "Filho, vá hoje trabalhar na vinha."

[[v40-21-29]]

^<<v40-21-29,29>>^ Ele respondeu: "Não quero ir." Mas depois, arrependido, foi.

[[v40-21-30]]

^<<v40-21-30,30>>^ Dirigindo-se ao outro filho, o pai disse a mesma coisa. Ele respondeu: "Sim, senhor." Mas não foi.

[[v40-21-31]]

^<<v40-21-31,31>>^ Qual dos dois fez a vontade do pai? Eles responderam: — O primeiro. Então Jesus disse: — Em verdade lhes digo que os publicanos e as prostitutas estão entrando no Reino de Deus primeiro que vocês.

[[v40-21-32]]

^<<v40-21-32,32>>^ Porque João veio até vocês no caminho da justiça, e vocês não acreditaram nele; no entanto, os publicanos e as prostitutas acreditaram. Vocês, porém, mesmo vendo isso, não se arrependeram depois para acreditar nele.

[[v40-21-33]]

^<<v40-21-33,33>>^ — Escutem outra parábola. Havia um homem, dono de terras, que plantou uma vinha. Pôs uma cerca em volta dela, construiu nela um lagar, edificou uma torre e arrendou a vinha a uns lavradores. Depois, ausentou-se do país.

[[v40-21-34]]

^<<v40-21-34,34>>^ Quando chegou o tempo da colheita, o dono da vinha mandou os seus servos aos lavradores, para receber os frutos que cabiam a ele.

[[v40-21-35]]

^<<v40-21-35,35>>^ Mas os lavradores, agarrando os servos, espancaram um, mataram outro e apedrejaram ainda outro.

[[v40-21-36]]

^<<v40-21-36,36>>^ O dono enviou ainda outros servos em maior número; e os lavradores fizeram a mesma coisa com eles.

[[v40-21-37]]

^<<v40-21-37,37>>^ Por último, o dono da vinha enviou-lhes o seu próprio filho, pensando: "O meu filho eles respeitarão."

[[v40-21-38]]

^<<v40-21-38,38>>^ Mas os lavradores, vendo o filho, disseram uns aos outros: "Este é o herdeiro; venham, vamos matá-lo e ficar com a herança dele para nós."

[[v40-21-39]]

^<<v40-21-39,39>>^ E, agarrando-o, lançaram-no fora da vinha e o mataram.

[[v40-21-40]]

^<<v40-21-40,40>>^ Quando, pois, vier o dono da vinha, que fará àqueles lavradores?

[[v40-21-41]]

^<<v40-21-41,41>>^ Eles responderam: — Fará perecer horrivelmente aqueles malvados e arrendará a vinha a outros lavradores que lhe entregarão os frutos no tempo certo.

[[v40-21-42]]

^<<v40-21-42,42>>^ Então Jesus perguntou: — Vocês nunca leram nas Escrituras: "A pedra que os construtores rejeitaram, essa veio a ser a pedra angular. Isto procede do Senhor e é maravilhoso aos nossos olhos"?

[[v40-21-43]]

^<<v40-21-43,43>>^ — Portanto, eu lhes digo que o Reino de Deus será tirado de vocês e entregue a um povo que lhe produza os respectivos frutos.

[[v40-21-44]]

^<<v40-21-44,44>>^ Todo o que cair sobre esta pedra ficará em pedaços; e aquele sobre quem ela cair ficará reduzido a pó.

[[v40-21-45]]

^<<v40-21-45,45>>^ Os principais sacerdotes e os fariseus, ouvindo estas parábolas, entenderam que Jesus falava a respeito deles;

[[v40-21-46]]

^<<v40-21-46,46>>^ e, embora quisessem prendê-lo, tinham medo das multidões, porque estas o consideravam como profeta.

'''

xref:040-mateus/040-mateus-020.adoc#v40-20-0[&#60; Capítulo Anterior] | <<v40-21-0,Topo>> | xref:040-mateus/040-mateus-022.adoc#v40-22-0[Próximo Capítulo &#62;]