include::./index.adoc[]

[[v40-23-0]]
=== Mateus, 23
// naa ?, NAA - Nova Almeida Atualizada

[[v40-23-1]]

^<<v40-23-1,1>>^ Então Jesus falou às multidões e aos seus discípulos:

[[v40-23-2]]

^<<v40-23-2,2>>^ — Na cadeira de Moisés se assentaram os escribas e os fariseus.

[[v40-23-3]]

^<<v40-23-3,3>>^ Portanto, façam e observem tudo o que eles disserem a vocês, mas não os imitem em suas obras; porque dizem e não fazem.

[[v40-23-4]]

^<<v40-23-4,4>>^ Atam fardos pesados, difíceis de carregar, e os põem sobre os ombros dos outros, mas eles mesmos nem com o dedo querem movê-los.

[[v40-23-5]]

^<<v40-23-5,5>>^ Praticam todas as suas obras a fim de serem vistos pelos outros; pois alargam os seus filactérios e alongam as franjas de suas capas.

[[v40-23-6]]

^<<v40-23-6,6>>^ Gostam do primeiro lugar nos banquetes e das primeiras cadeiras nas sinagogas,

[[v40-23-7]]

^<<v40-23-7,7>>^ das saudações nas praças e de serem chamados de "mestre".

[[v40-23-8]]

^<<v40-23-8,8>>^ Mas vocês não serão chamados de "mestre", porque um só é Mestre de vocês, e todos vocês são irmãos.

[[v40-23-9]]

^<<v40-23-9,9>>^ Aqui na terra, não chamem ninguém de "pai", porque só um é o Pai de vocês, aquele que está nos céus.

[[v40-23-10]]

^<<v40-23-10,10>>^ Nem queiram ser chamados de "guias", porque um só é o Guia de vocês, o Cristo.

[[v40-23-11]]

^<<v40-23-11,11>>^ Mas o maior entre vocês será o servo de vocês.

[[v40-23-12]]

^<<v40-23-12,12>>^ Quem se exaltar será humilhado; e quem se humilhar será exaltado.

[[v40-23-13]]

^<<v40-23-13,13>>^ — Ai de vocês, escribas e fariseus, hipócritas, porque vocês fecham o Reino dos Céus diante das pessoas; pois vocês mesmos não entram, nem deixam entrar os que estão entrando!

[[v40-23-14]]

^<<v40-23-14,14>>^ &#91;— Ai de vocês, escribas e fariseus, hipócritas, porque vocês devoram as casas das viúvas e, para o justificar, fazem longas orações; por isso, vocês sofrerão juízo muito mais severo!&#93;

[[v40-23-15]]

^<<v40-23-15,15>>^ — Ai de vocês, escribas e fariseus, hipócritas, porque vocês percorrem o mar e a terra para fazer um prosélito; e, uma vez feito, o tornam filho do inferno duas vezes mais do que vocês!

[[v40-23-16]]

^<<v40-23-16,16>>^ — Ai de vocês, guias cegos, que dizem: "Se alguém jurar pelo santuário, isso não tem importância; mas, se alguém jurar pelo ouro do santuário, fica obrigado pelo que jurou!"

[[v40-23-17]]

^<<v40-23-17,17>>^ Seus tolos e cegos! Qual é mais importante: o ouro ou o santuário que santifica o ouro?

[[v40-23-18]]

^<<v40-23-18,18>>^ E vocês dizem: "Se alguém jurar pelo altar, isso não tem importância; mas, se alguém jurar pela oferta que está sobre o altar, fica obrigado pelo que jurou."

[[v40-23-19]]

^<<v40-23-19,19>>^ Cegos! Qual é mais importante: a oferta ou o altar que santifica a oferta?

[[v40-23-20]]

^<<v40-23-20,20>>^ Portanto, quem jurar pelo altar jura por ele e por tudo o que está sobre ele.

[[v40-23-21]]

^<<v40-23-21,21>>^ Quem jurar pelo santuário jura por ele e por aquele que nele habita;

[[v40-23-22]]

^<<v40-23-22,22>>^ e quem jurar pelo céu jura pelo trono de Deus e por aquele que está sentado no trono.

[[v40-23-23]]

^<<v40-23-23,23>>^ — Ai de vocês, escribas e fariseus, hipócritas, porque vocês dão o dízimo da hortelã, do endro e do cominho e desprezam os preceitos mais importantes da Lei: a justiça, a misericórdia e a fé. Mas vocês deviam fazer estas coisas, sem omitir aquelas!

[[v40-23-24]]

^<<v40-23-24,24>>^ Guias cegos! Coam um mosquito, mas engolem um camelo!

[[v40-23-25]]

^<<v40-23-25,25>>^ — Ai de vocês, escribas e fariseus, hipócritas, porque vocês limpam o exterior do copo e do prato, mas estes, por dentro, estão cheios de roubo e de glutonaria!

[[v40-23-26]]

^<<v40-23-26,26>>^ Fariseu cego! Limpe primeiro o interior do copo, para que também o seu exterior fique limpo!

[[v40-23-27]]

^<<v40-23-27,27>>^ — Ai de vocês, escribas e fariseus, hipócritas, porque vocês são semelhantes aos sepulcros pintados de branco, que, por fora, se mostram belos, mas interiormente estão cheios de ossos de mortos e de toda podridão!

[[v40-23-28]]

^<<v40-23-28,28>>^ Assim também vocês, por fora, parecem justos aos olhos dos outros, mas, por dentro, estão cheios de hipocrisia e de maldade.

[[v40-23-29]]

^<<v40-23-29,29>>^ — Ai de vocês, escribas e fariseus, hipócritas, porque vocês edificam os sepulcros dos profetas, enfeitam os túmulos dos justos

[[v40-23-30]]

^<<v40-23-30,30>>^ e dizem: "Se nós tivéssemos vivido nos dias de nossos pais, não teríamos sido seus cúmplices, quando mataram os profetas!"

[[v40-23-31]]

^<<v40-23-31,31>>^ Assim, vocês dão testemunho contra si mesmos de que são filhos dos que mataram os profetas.

[[v40-23-32]]

^<<v40-23-32,32>>^ Portanto, tratem de terminar aquilo que os pais de vocês começaram.

[[v40-23-33]]

^<<v40-23-33,33>>^ — Serpentes, raça de víboras! Como esperam escapar da condenação do inferno?

[[v40-23-34]]

^<<v40-23-34,34>>^ Por isso, eis que eu lhes envio profetas, sábios e escribas. A uns vocês matarão e a outros crucificarão; a outros ainda vocês açoitarão nas sinagogas e perseguirão de cidade em cidade;

[[v40-23-35]]

^<<v40-23-35,35>>^ para que recaia sobre vocês todo o sangue justo derramado sobre a terra, desde o sangue do justo Abel até o sangue de Zacarias, filho de Baraquias, a quem vocês mataram entre o santuário e o altar.

[[v40-23-36]]

^<<v40-23-36,36>>^ Em verdade lhes digo que todas estas coisas hão de vir sobre a presente geração.

[[v40-23-37]]

^<<v40-23-37,37>>^ — Jerusalém, Jerusalém! Você mata os profetas e apedreja os que lhe são enviados! Quantas vezes eu quis reunir os seus filhos, como a galinha ajunta os seus pintinhos debaixo das asas, mas vocês não quiseram!

[[v40-23-38]]

^<<v40-23-38,38>>^ Eis que a casa de vocês ficará deserta.

[[v40-23-39]]

^<<v40-23-39,39>>^ Pois eu lhes afirmo que, desde agora, não me verão mais, até que venham a dizer: "Bendito o que vem em nome do Senhor!"

'''

xref:040-mateus/040-mateus-022.adoc#v40-22-0[&#60; Capítulo Anterior] | <<v40-23-0,Topo>> | xref:040-mateus/040-mateus-024.adoc#v40-24-0[Próximo Capítulo &#62;]