include::./index.adoc[]

[[v40-26-0]]
=== Mateus, 26
// naa ?, NAA - Nova Almeida Atualizada

[[v40-26-1]]

^<<v40-26-1,1>>^ Quando Jesus acabou de proferir estas palavras, disse aos seus discípulos:

[[v40-26-2]]

^<<v40-26-2,2>>^ — Vocês sabem que, daqui a dois dias, será celebrada a Páscoa, e o Filho do Homem será entregue para ser crucificado.

[[v40-26-3]]

^<<v40-26-3,3>>^ Então os principais sacerdotes e os anciãos do povo se reuniram no palácio do sumo sacerdote, chamado Caifás,

[[v40-26-4]]

^<<v40-26-4,4>>^ e deliberaram prender Jesus, à traição, e matá-lo.

[[v40-26-5]]

^<<v40-26-5,5>>^ Mas diziam: — Não durante a festa, para que não haja tumulto entre o povo.

[[v40-26-6]]

^<<v40-26-6,6>>^ Quando Jesus estava em Betânia, na casa de Simão, o leproso,

[[v40-26-7]]

^<<v40-26-7,7>>^ aproximou-se dele uma mulher, trazendo um frasco feito de alabastro com um perfume precioso, que ela derramou sobre a cabeça de Jesus, estando ele à mesa.

[[v40-26-8]]

^<<v40-26-8,8>>^ Vendo isto, os discípulos ficaram indignados e disseram: — Para que este desperdício?

[[v40-26-9]]

^<<v40-26-9,9>>^ Este perfume poderia ter sido vendido por muito dinheiro, para ser dado aos pobres.

[[v40-26-10]]

^<<v40-26-10,10>>^ Mas Jesus, sabendo disto, lhes disse: — Por que vocês estão incomodando esta mulher? Ela praticou uma boa ação para comigo.

[[v40-26-11]]

^<<v40-26-11,11>>^ Porque os pobres estarão sempre com vocês, mas a mim vocês nem sempre terão.

[[v40-26-12]]

^<<v40-26-12,12>>^ Porque, derramando este perfume sobre o meu corpo, ela o fez para o meu sepultamento.

[[v40-26-13]]

^<<v40-26-13,13>>^ Em verdade lhes digo que, onde for pregado em todo o mundo este evangelho, também será contado o que ela fez, para memória dela.

[[v40-26-14]]

^<<v40-26-14,14>>^ Então um dos doze, chamado Judas Iscariotes, foi falar com os principais sacerdotes.

[[v40-26-15]]

^<<v40-26-15,15>>^ Ele disse: — Quanto me darão para que eu o entregue a vocês? E pagaram-lhe trinta moedas de prata.

[[v40-26-16]]

^<<v40-26-16,16>>^ E, desse momento em diante, Judas buscava uma boa ocasião para entregar Jesus.

[[v40-26-17]]

^<<v40-26-17,17>>^ No primeiro dia da Festa dos Pães sem Fermento, os discípulos vieram a Jesus e lhe perguntaram: — Onde quer que façamos os preparativos para que o senhor possa comer a Páscoa?

[[v40-26-18]]

^<<v40-26-18,18>>^ E ele lhes respondeu: — Vão até a cidade, procurem certo homem e digam: "O Mestre diz: O meu tempo está próximo. É em sua casa que celebrarei a Páscoa com os meus discípulos."

[[v40-26-19]]

^<<v40-26-19,19>>^ E eles fizeram como Jesus lhes havia ordenado e prepararam a Páscoa.

[[v40-26-20]]

^<<v40-26-20,20>>^ Ao cair da tarde, Jesus pôs-se à mesa com os doze discípulos.

[[v40-26-21]]

^<<v40-26-21,21>>^ E, enquanto comiam, Jesus disse: — Em verdade lhes digo que um de vocês vai me trair.

[[v40-26-22]]

^<<v40-26-22,22>>^ E eles, muito entristecidos, começaram um por um a perguntar-lhe: — Por acaso seria eu, Senhor?

[[v40-26-23]]

^<<v40-26-23,23>>^ Jesus respondeu: — O que comigo põe a mão no prato, esse vai me trair.

[[v40-26-24]]

^<<v40-26-24,24>>^ O Filho do Homem vai, como está escrito a seu respeito; mas ai daquele por quem o Filho do Homem está sendo traído! Melhor seria para ele se nunca tivesse nascido!

[[v40-26-25]]

^<<v40-26-25,25>>^ Então Judas, que o traía, perguntou: — Por acaso sou eu, Mestre? Jesus respondeu: — Você acabou de dizer isso.

[[v40-26-26]]

^<<v40-26-26,26>>^ Enquanto comiam, Jesus pegou um pão, e, abençoando-o, o partiu e deu aos discípulos, dizendo: — Tomem, comam; isto é o meu corpo.

[[v40-26-27]]

^<<v40-26-27,27>>^ A seguir, Jesus pegou um cálice e, tendo dado graças, o deu aos seus discípulos, dizendo: — Bebam todos dele;

[[v40-26-28]]

^<<v40-26-28,28>>^ porque isto é o meu sangue, o sangue da aliança, derramado em favor de muitos, para remissão de pecados.

[[v40-26-29]]

^<<v40-26-29,29>>^ E digo a vocês que, desta hora em diante, nunca mais beberei deste fruto da videira, até aquele dia em que beberei com vocês o vinho novo, no Reino de meu Pai.

[[v40-26-30]]

^<<v40-26-30,30>>^ E, tendo cantado um hino, saíram para o monte das Oliveiras.

[[v40-26-31]]

^<<v40-26-31,31>>^ Então Jesus disse aos discípulos: — Esta noite serei uma pedra de tropeço para todos vocês, porque está escrito: "Ferirei o pastor, e as ovelhas do rebanho ficarão dispersas."

[[v40-26-32]]

^<<v40-26-32,32>>^ Mas, depois da minha ressurreição, irei adiante de vocês para a Galileia.

[[v40-26-33]]

^<<v40-26-33,33>>^ Mas Pedro, tomando a palavra, disse a Jesus: — Ainda que o senhor venha a ser um tropeço para todos, nunca o será para mim.

[[v40-26-34]]

^<<v40-26-34,34>>^ Mas Jesus lhe disse: — Em verdade lhe digo que, nesta noite, antes que o galo cante, você me negará três vezes.

[[v40-26-35]]

^<<v40-26-35,35>>^ Pedro insistiu: — Ainda que me seja necessário morrer com o senhor, de modo nenhum o negarei. E todos os discípulos disseram o mesmo.

[[v40-26-36]]

^<<v40-26-36,36>>^ Em seguida, Jesus foi com eles a um lugar chamado Getsêmani. E disse aos discípulos: — Sentem-se aqui, enquanto eu vou ali orar.

[[v40-26-37]]

^<<v40-26-37,37>>^ E, levando consigo Pedro e os dois filhos de Zebedeu, começou a sentir-se tomado de tristeza e de angústia.

[[v40-26-38]]

^<<v40-26-38,38>>^ Então lhes disse: — A minha alma está profundamente triste até a morte; fiquem aqui e vigiem comigo.

[[v40-26-39]]

^<<v40-26-39,39>>^ E, adiantando-se um pouco, prostrou-se sobre o seu rosto, orando e dizendo: — Meu Pai, se é possível, que passe de mim este cálice! Contudo, não seja como eu quero, e sim como tu queres.

[[v40-26-40]]

^<<v40-26-40,40>>^ E, voltando para os discípulos, achou-os dormindo. E disse a Pedro: — Então nem uma hora vocês puderam vigiar comigo?

[[v40-26-41]]

^<<v40-26-41,41>>^ Vigiem e orem, para que não caiam em tentação; o espírito, na verdade, está pronto, mas a carne é fraca.

[[v40-26-42]]

^<<v40-26-42,42>>^ Retirando-se pela segunda vez, orou de novo, dizendo: — Meu Pai, se não é possível que este cálice passe de mim sem que eu o beba, faça-se a tua vontade.

[[v40-26-43]]

^<<v40-26-43,43>>^ E, voltando, achou-os outra vez dormindo; porque os olhos deles estavam pesados.

[[v40-26-44]]

^<<v40-26-44,44>>^ Deixando-os novamente, foi orar pela terceira vez, repetindo as mesmas palavras.

[[v40-26-45]]

^<<v40-26-45,45>>^ Então voltou para os discípulos e lhes disse: — Vocês ainda estão dormindo e descansando! Eis que é chegada a hora, e o Filho do Homem está sendo entregue nas mãos de pecadores.

[[v40-26-46]]

^<<v40-26-46,46>>^ Levantem-se, vamos embora! Eis que o traidor se aproxima.

[[v40-26-47]]

^<<v40-26-47,47>>^ E enquanto Jesus ainda falava, eis que chegou Judas, um dos doze, e, com ele, grande multidão com espadas e porretes, vinda da parte dos principais sacerdotes e dos anciãos do povo.

[[v40-26-48]]

^<<v40-26-48,48>>^ Ora, o traidor tinha dado a eles um sinal: "Aquele que eu beijar, é esse; prendam-no."

[[v40-26-49]]

^<<v40-26-49,49>>^ E logo, aproximando-se de Jesus, Judas disse: — Salve, Mestre! E o beijou.

[[v40-26-50]]

^<<v40-26-50,50>>^ Jesus, porém, lhe disse: — Amigo, o que você veio fazer? Nisto, aproximando-se eles, agarraram Jesus e o prenderam.

[[v40-26-51]]

^<<v40-26-51,51>>^ E eis que um dos que estavam com Jesus, estendendo a mão, sacou da espada e, golpeando o servo do sumo sacerdote, cortou-lhe a orelha.

[[v40-26-52]]

^<<v40-26-52,52>>^ Então Jesus lhe disse: — Coloque a espada de volta no seu lugar, pois todos os que lançam mão da espada à espada perecerão.

[[v40-26-53]]

^<<v40-26-53,53>>^ Ou você acha que não posso pedir a meu Pai, e ele me mandaria neste momento mais de doze legiões de anjos?

[[v40-26-54]]

^<<v40-26-54,54>>^ Mas como, então, se cumpririam as Escrituras, que dizem que assim deve acontecer?

[[v40-26-55]]

^<<v40-26-55,55>>^ Naquele momento, Jesus disse às multidões: — Vocês vieram com espadas e porretes para prender-me, como se eu fosse um salteador? Todos os dias, no templo, eu me assentava ensinando, e vocês não me prenderam.

[[v40-26-56]]

^<<v40-26-56,56>>^ Tudo isto, porém, aconteceu para que se cumprissem as Escrituras dos profetas. Então todos os discípulos o deixaram e fugiram.

[[v40-26-57]]

^<<v40-26-57,57>>^ E os que prenderam Jesus o levaram à casa de Caifás, o sumo sacerdote, onde se haviam reunido os escribas e os anciãos.

[[v40-26-58]]

^<<v40-26-58,58>>^ Pedro o seguia de longe até o pátio do sumo sacerdote. E, tendo entrado, assentou-se entre os servos, para ver como aquilo ia terminar.

[[v40-26-59]]

^<<v40-26-59,59>>^ E os principais sacerdotes e todo o Sinédrio procuravam algum testemunho falso contra Jesus, a fim de o condenarem à morte.

[[v40-26-60]]

^<<v40-26-60,60>>^ E não acharam, apesar de terem sido apresentadas muitas testemunhas falsas. Mas, afinal, compareceram duas, afirmando:

[[v40-26-61]]

^<<v40-26-61,61>>^ — Este disse: "Posso destruir o santuário de Deus e reconstruí-lo em três dias."

[[v40-26-62]]

^<<v40-26-62,62>>^ E, levantando-se o sumo sacerdote, perguntou a Jesus: — Você não diz nada em resposta ao que estes depõem contra você?

[[v40-26-63]]

^<<v40-26-63,63>>^ Jesus, porém, guardou silêncio. E o sumo sacerdote lhe disse: — Eu exijo que nos diga, tendo o Deus vivo por testemunha, se você é o Cristo, o Filho de Deus.

[[v40-26-64]]

^<<v40-26-64,64>>^ Jesus respondeu: — É o senhor mesmo quem está dizendo isso. Mas eu lhes digo que, desde agora, vocês verão o Filho do Homem sentado à direita do Todo-Poderoso e vindo sobre as nuvens do céu.

[[v40-26-65]]

^<<v40-26-65,65>>^ Então o sumo sacerdote rasgou as suas vestes e disse: — Blasfemou! Por que ainda precisamos de testemunhas? Eis que agora mesmo vocês ouviram a blasfêmia!

[[v40-26-66]]

^<<v40-26-66,66>>^ O que vocês acham? E eles responderam: — É réu de morte.

[[v40-26-67]]

^<<v40-26-67,67>>^ Então alguns cuspiram no rosto de Jesus e bateram nele. E outros o esbofeteavam, dizendo:

[[v40-26-68]]

^<<v40-26-68,68>>^ — Profetize para nós, ó Cristo! Quem foi que bateu em você?

[[v40-26-69]]

^<<v40-26-69,69>>^ Pedro estava sentado fora no pátio. Uma empregada se aproximou e lhe disse: — Você também estava com Jesus, o galileu.

[[v40-26-70]]

^<<v40-26-70,70>>^ Mas ele negou diante de todos e disse: — Não sei o que você está dizendo.

[[v40-26-71]]

^<<v40-26-71,71>>^ Quando se dirigia para a porta, Pedro foi visto por outra empregada, que disse aos que estavam ali: — Este também estava com Jesus, o Nazareno.

[[v40-26-72]]

^<<v40-26-72,72>>^ E ele negou outra vez, com juramento: — Não conheço esse homem.

[[v40-26-73]]

^<<v40-26-73,73>>^ Pouco depois, aproximando-se os que estavam ali, disseram a Pedro: — Com certeza você também é um deles, porque o seu modo de falar o denuncia.

[[v40-26-74]]

^<<v40-26-74,74>>^ Então ele começou a praguejar e a jurar: — Não conheço esse homem! E no mesmo instante o galo cantou.

[[v40-26-75]]

^<<v40-26-75,75>>^ Então Pedro se lembrou da palavra que Jesus lhe tinha dito: "Antes que o galo cante, você me negará três vezes."  E Pedro, saindo dali, chorou amargamente.

'''

xref:040-mateus/040-mateus-025.adoc#v40-25-0[&#60; Capítulo Anterior] | <<v40-26-0,Topo>> | xref:040-mateus/040-mateus-027.adoc#v40-27-0[Próximo Capítulo &#62;]