include::./index.adoc[]

[[v40-8-0]]
=== Mateus, 8
// naa ?, NAA - Nova Almeida Atualizada

[[v40-8-1]]

^<<v40-8-1,1>>^ Quando Jesus desceu do monte, grandes multidões o seguiram.

[[v40-8-2]]

^<<v40-8-2,2>>^ E eis que um leproso aproximou-se e o adorou, dizendo: — Senhor, se quiser, pode me purificar.

[[v40-8-3]]

^<<v40-8-3,3>>^ E Jesus, estendendo a mão, tocou nele, dizendo: — Quero, sim. Fique limpo! E, no mesmo instante, ele ficou limpo da sua lepra.

[[v40-8-4]]

^<<v40-8-4,4>>^ Então Jesus lhe disse: — Olhe, não conte isso a ninguém, mas vá, apresente-se ao sacerdote e faça a oferta que Moisés ordenou, para servir de testemunho ao povo.

[[v40-8-5]]

^<<v40-8-5,5>>^ Tendo Jesus entrado em Cafarnaum, um centurião se aproximou dele, implorando:

[[v40-8-6]]

^<<v40-8-6,6>>^ — Senhor, o meu servo está na minha casa, de cama, paralítico, sofrendo horrivelmente.

[[v40-8-7]]

^<<v40-8-7,7>>^ Jesus lhe disse: — Eu vou lá curá-lo.

[[v40-8-8]]

^<<v40-8-8,8>>^ Mas o centurião respondeu: — Senhor, não sou digno de recebê-lo em minha casa. Mas apenas mande com uma palavra, e o meu servo será curado.

[[v40-8-9]]

^<<v40-8-9,9>>^ Porque também eu sou homem sujeito à autoridade, tenho soldados às minhas ordens e digo a este: "Vá", e ele vai; e a outro: "Venha", e ele vem; e ao meu servo: "Faça isto", e ele o faz.

[[v40-8-10]]

^<<v40-8-10,10>>^ Ao ouvir isso, Jesus ficou admirado e disse aos que o acompanhavam: — Em verdade lhes digo que nem mesmo em Israel encontrei fé como esta.

[[v40-8-11]]

^<<v40-8-11,11>>^ Digo a vocês que muitos virão do Oriente e do Ocidente e tomarão lugar à mesa com Abraão, Isaque e Jacó no Reino dos Céus.

[[v40-8-12]]

^<<v40-8-12,12>>^ Mas os filhos do Reino serão lançados para fora, nas trevas; ali haverá choro e ranger de dentes.

[[v40-8-13]]

^<<v40-8-13,13>>^ Então Jesus disse ao centurião: — Vá! E seja feito conforme você crê. E, naquela mesma hora, o servo do centurião foi curado.

[[v40-8-14]]

^<<v40-8-14,14>>^ Tendo Jesus chegado à casa de Pedro, viu a sogra deste acamada, com febre.

[[v40-8-15]]

^<<v40-8-15,15>>^ Mas Jesus tomou-a pela mão, e a febre a deixou. Ela se levantou e passou a servi-lo.

[[v40-8-16]]

^<<v40-8-16,16>>^ Ao cair da tarde, trouxeram a Jesus muitos endemoniados. E apenas com a palavra expulsou os espíritos e curou todos os que estavam doentes,

[[v40-8-17]]

^<<v40-8-17,17>>^ para se cumprir o que foi dito por meio do profeta Isaías: "Ele mesmo tomou as nossas enfermidades e carregou as nossas doenças."

[[v40-8-18]]

^<<v40-8-18,18>>^ Vendo Jesus muita gente ao seu redor, ordenou que passassem para a outra margem.

[[v40-8-19]]

^<<v40-8-19,19>>^ Então, aproximando-se dele um escriba, disse a Jesus: — Mestre, vou segui-lo para onde quer que o senhor for.

[[v40-8-20]]

^<<v40-8-20,20>>^ Mas Jesus lhe respondeu: — As raposas têm as suas tocas e as aves do céu têm os seus ninhos, mas o Filho do Homem não tem onde reclinar a cabeça.

[[v40-8-21]]

^<<v40-8-21,21>>^ E outro dos discípulos lhe disse: — Senhor, deixe-me ir primeiro sepultar o meu pai.

[[v40-8-22]]

^<<v40-8-22,22>>^ Mas Jesus respondeu: — Siga-me e deixe que os mortos sepultem os seus mortos.

[[v40-8-23]]

^<<v40-8-23,23>>^ Jesus entrou no barco e os seus discípulos o seguiram.

[[v40-8-24]]

^<<v40-8-24,24>>^ E eis que levantou-se no mar uma grande tempestade, de modo que as ondas cobriam o barco. Jesus, porém, estava dormindo.

[[v40-8-25]]

^<<v40-8-25,25>>^ Mas os discípulos foram acordá-lo, dizendo: — Senhor, salve-nos! Estamos perecendo!

[[v40-8-26]]

^<<v40-8-26,26>>^ Então Jesus perguntou: — Por que vocês são tão medrosos, homens de pequena fé? E, levantando-se, repreendeu os ventos e o mar; e tudo ficou bem calmo.

[[v40-8-27]]

^<<v40-8-27,27>>^ E aqueles homens ficaram admirados, dizendo: — Quem é este que até os ventos e o mar lhe obedecem?

[[v40-8-28]]

^<<v40-8-28,28>>^ Quando Jesus chegou à outra margem, à terra dos gadarenos, dois endemoniados foram ao seu encontro, saindo dentre os túmulos. Eles eram tão furiosos, que ninguém podia passar por aquele caminho.

[[v40-8-29]]

^<<v40-8-29,29>>^ E eis que gritaram: — O que você quer conosco, Filho de Deus? Você veio aqui nos atormentar antes do tempo?

[[v40-8-30]]

^<<v40-8-30,30>>^ Ora, uma grande manada de porcos estava pastando não longe deles.

[[v40-8-31]]

^<<v40-8-31,31>>^ Então os demônios pediram a Jesus com insistência: — Se você vai nos expulsar, mande-nos para a manada de porcos.

[[v40-8-32]]

^<<v40-8-32,32>>^ Jesus disse: — Pois vão. E eles, saindo, entraram nos porcos; e eis que toda a manada se precipitou, despenhadeiro abaixo, para dentro do mar, e morreram nas águas.

[[v40-8-33]]

^<<v40-8-33,33>>^ Os que tratavam dos porcos fugiram e, chegando à cidade, anunciaram todas estas coisas e o que tinha acontecido com os endemoniados.

[[v40-8-34]]

^<<v40-8-34,34>>^ Então a cidade toda saiu para encontrar-se com Jesus. E, ao vê-lo, pediram-lhe com insistência que se retirasse da terra deles.

'''

xref:040-mateus/040-mateus-007.adoc#v40-7-0[&#60; Capítulo Anterior] | <<v40-8-0,Topo>> | xref:040-mateus/040-mateus-009.adoc#v40-9-0[Próximo Capítulo &#62;]