include::./index.adoc[]

[[v40-11-0]]
=== Mateus, 11
// naa ?, NAA - Nova Almeida Atualizada

[[v40-11-1]]

^<<v40-11-1,1>>^ Quando Jesus acabou de dar estas instruções a seus doze discípulos, saiu dali para ir ensinar e pregar nas cidades deles.

[[v40-11-2]]

^<<v40-11-2,2>>^ Quando João, no cárcere, ouviu falar das obras de Cristo, mandou que seus discípulos fossem perguntar:

[[v40-11-3]]

^<<v40-11-3,3>>^ — Você é aquele que estava para vir ou devemos esperar outro?

[[v40-11-4]]

^<<v40-11-4,4>>^ Então Jesus lhes respondeu: — Voltem e anunciem a João o que estão ouvindo e vendo:

[[v40-11-5]]

^<<v40-11-5,5>>^ os cegos veem, os coxos andam, os leprosos são purificados, os surdos ouvem, os mortos são ressuscitados e aos pobres está sendo pregado o evangelho.

[[v40-11-6]]

^<<v40-11-6,6>>^ E bem-aventurado é aquele que não achar em mim motivo de tropeço.

[[v40-11-7]]

^<<v40-11-7,7>>^ Quando os discípulos de João foram embora, Jesus começou a dizer ao povo a respeito de João: — O que vocês foram ver no deserto? Um caniço agitado pelo vento?

[[v40-11-8]]

^<<v40-11-8,8>>^ O que vocês foram ver? Um homem vestido de roupas finas? Os que vestem roupas finas moram nos palácios reais.

[[v40-11-9]]

^<<v40-11-9,9>>^ Sim, o que foram ver? Um profeta? Sim, eu lhes digo, e muito mais do que um profeta.

[[v40-11-10]]

^<<v40-11-10,10>>^ Este é aquele de quem está escrito: "Eis que eu envio adiante de você o meu mensageiro, que preparará o caminho diante de você."

[[v40-11-11]]

^<<v40-11-11,11>>^ — Em verdade lhes digo: entre os nascidos de mulher, não apareceu ninguém maior do que João Batista; mas o menor no Reino dos Céus é maior do que ele.

[[v40-11-12]]

^<<v40-11-12,12>>^ Desde os dias de João Batista até agora, o Reino dos Céus sofre violência, e os que usam de força se apoderam dele.

[[v40-11-13]]

^<<v40-11-13,13>>^ Porque todos os Profetas e a Lei profetizaram até João.

[[v40-11-14]]

^<<v40-11-14,14>>^ E, se vocês o querem reconhecer, ele mesmo é Elias, que estava para vir.

[[v40-11-15]]

^<<v40-11-15,15>>^ Quem tem ouvidos para ouvir, ouça.

[[v40-11-16]]

^<<v40-11-16,16>>^ — Mas a que compararei esta geração? É semelhante a meninos que, sentados nas praças, gritam aos companheiros:

[[v40-11-17]]

^<<v40-11-17,17>>^ "Nós tocamos flauta, mas vocês não dançaram; entoamos lamentações, mas vocês não prantearam."

[[v40-11-18]]

^<<v40-11-18,18>>^ — Pois veio João, que não comia nem bebia, e as pessoas dizem: "Ele tem demônio!"

[[v40-11-19]]

^<<v40-11-19,19>>^ Veio o Filho do Homem, comendo e bebendo, e as pessoas dizem: "Eis aí um glutão e bebedor de vinho, amigo de publicanos e pecadores!" Mas a sabedoria é justificada por suas obras.

[[v40-11-20]]

^<<v40-11-20,20>>^ Então Jesus começou a repreender as cidades nas quais ele tinha feito muitos milagres, pelo fato de não terem se arrependido:

[[v40-11-21]]

^<<v40-11-21,21>>^ — Ai de você, Corazim! Ai de você, Betsaida! Porque, se em Tiro e em Sidom se tivessem operado os milagres que foram feitos em vocês, há muito que elas teriam se arrependido com pano de saco e cinza.

[[v40-11-22]]

^<<v40-11-22,22>>^ Mas eu digo a vocês que, no Dia do Juízo, haverá menos rigor para Tiro e Sidom do que para vocês.

[[v40-11-23]]

^<<v40-11-23,23>>^ — E você, Cafarnaum, pensa que será elevada até o céu? Será jogada no inferno! Porque, se em Sodoma se tivessem operado os milagres que foram feitos em você, ela teria permanecido até o dia de hoje.

[[v40-11-24]]

^<<v40-11-24,24>>^ Mas eu digo a vocês que, no Dia do Juízo, haverá menos rigor para a terra de Sodoma do que para você.

[[v40-11-25]]

^<<v40-11-25,25>>^ Por aquele tempo, Jesus exclamou: — Graças te dou, ó Pai, Senhor do céu e da terra, porque escondeste estas coisas dos sábios e instruídos e as revelaste aos pequeninos.

[[v40-11-26]]

^<<v40-11-26,26>>^ Sim, ó Pai, porque assim foi do teu agrado.

[[v40-11-27]]

^<<v40-11-27,27>>^ Tudo me foi entregue por meu Pai. Ninguém conhece o Filho, a não ser o Pai; e ninguém conhece o Pai, a não ser o Filho e aquele a quem o Filho o quiser revelar.

[[v40-11-28]]

^<<v40-11-28,28>>^ — Venham a mim todos vocês que estão cansados e sobrecarregados, e eu os aliviarei.

[[v40-11-29]]

^<<v40-11-29,29>>^ Tomem sobre vocês o meu jugo e aprendam de mim, porque sou manso e humilde de coração; e vocês acharão descanso para a sua alma.

[[v40-11-30]]

^<<v40-11-30,30>>^ Porque o meu jugo é suave, e o meu fardo é leve.

'''

xref:040-mateus/040-mateus-010.adoc#v40-10-0[&#60; Capítulo Anterior] | <<v40-11-0,Topo>> | xref:040-mateus/040-mateus-012.adoc#v40-12-0[Próximo Capítulo &#62;]