include::./index.adoc[]

[[v40-24-0]]
=== Mateus, 24
// naa ?, NAA - Nova Almeida Atualizada

[[v40-24-1]]

^<<v40-24-1,1>>^ Jesus saiu do templo e, enquanto caminhava, os seus discípulos se aproximaram para lhe mostrar as construções do templo.

[[v40-24-2]]

^<<v40-24-2,2>>^ Ele, porém, lhes disse: — Vocês estão vendo todas estas coisas? Em verdade lhes digo que não ficará aqui pedra sobre pedra que não seja derrubada.

[[v40-24-3]]

^<<v40-24-3,3>>^ Jesus estava sentado no monte das Oliveiras quando os discípulos se aproximaram dele e, em particular, lhe pediram: — Diga-nos quando essas coisas vão acontecer e que sinal haverá da sua vinda e do fim dos tempos.

[[v40-24-4]]

^<<v40-24-4,4>>^ E Jesus respondeu: — Tenham cuidado para que ninguém os engane.

[[v40-24-5]]

^<<v40-24-5,5>>^ Porque muitos virão em meu nome, dizendo: "Eu sou o Cristo"; e enganarão a muitos.

[[v40-24-6]]

^<<v40-24-6,6>>^ E vocês ouvirão falar de guerras e rumores de guerras. Fiquem atentos e não se assustem, porque é necessário que isso aconteça, mas ainda não é o fim.

[[v40-24-7]]

^<<v40-24-7,7>>^ Porque nação se levantará contra nação, e reino, contra reino. Haverá fomes e terremotos em vários lugares.

[[v40-24-8]]

^<<v40-24-8,8>>^ Porém todas essas coisas são o princípio das dores.

[[v40-24-9]]

^<<v40-24-9,9>>^ — Vocês serão entregues para serem maltratados e eles os matarão. Vocês serão odiados por todas as nações por causa do meu nome.

[[v40-24-10]]

^<<v40-24-10,10>>^ Nesse tempo, muitos hão de se escandalizar, trair e odiar uns aos outros.

[[v40-24-11]]

^<<v40-24-11,11>>^ Muitos falsos profetas se levantarão e enganarão a muitos.

[[v40-24-12]]

^<<v40-24-12,12>>^ E, por se multiplicar a maldade, o amor se esfriará de quase todos.

[[v40-24-13]]

^<<v40-24-13,13>>^ Aquele, porém, que ficar firme até o fim, esse será salvo.

[[v40-24-14]]

^<<v40-24-14,14>>^ E será pregado este evangelho do Reino por todo o mundo, para testemunho a todas as nações. Então virá o fim.

[[v40-24-15]]

^<<v40-24-15,15>>^ — Quando, pois, vocês virem, situado no lugar santo, o abominável da desolação de que falou o profeta Daniel (quem lê entenda),

[[v40-24-16]]

^<<v40-24-16,16>>^ então os que estiverem na Judeia fujam para os montes.

[[v40-24-17]]

^<<v40-24-17,17>>^ Quem estiver no terraço não desça para tirar de casa alguma coisa.

[[v40-24-18]]

^<<v40-24-18,18>>^ E quem estiver no campo não volte atrás para buscar a sua capa.

[[v40-24-19]]

^<<v40-24-19,19>>^ Ai das que estiverem grávidas e das que amamentarem naqueles dias!

[[v40-24-20]]

^<<v40-24-20,20>>^ Orem para que a fuga de vocês não aconteça no inverno, nem no sábado.

[[v40-24-21]]

^<<v40-24-21,21>>^ Porque nesse tempo haverá grande tribulação, como nunca houve desde o princípio do mundo até agora e nunca jamais haverá.

[[v40-24-22]]

^<<v40-24-22,22>>^ Não tivessem aqueles dias sido abreviados, ninguém seria salvo; mas, por causa dos escolhidos, tais dias serão abreviados.

[[v40-24-23]]

^<<v40-24-23,23>>^ — Então, se alguém disser a vocês: "Olhem! Aqui está o Cristo!" ou: "Ali está ele!", não acreditem.

[[v40-24-24]]

^<<v40-24-24,24>>^ Porque surgirão falsos cristos e falsos profetas, operando grandes sinais e prodígios, para enganar, se possível, os próprios eleitos.

[[v40-24-25]]

^<<v40-24-25,25>>^ Eis que tenho predito isso a vocês.

[[v40-24-26]]

^<<v40-24-26,26>>^ Portanto, se disserem a vocês: "Eis que ele está no deserto!", não vão lá. Ou, se disserem: "Eis que ele está no interior da casa!", não acreditem.

[[v40-24-27]]

^<<v40-24-27,27>>^ Porque, assim como o relâmpago sai do Oriente e brilha até o Ocidente, assim será a vinda do Filho do Homem.

[[v40-24-28]]

^<<v40-24-28,28>>^ Onde estiver o cadáver, aí se ajuntarão os abutres.

[[v40-24-29]]

^<<v40-24-29,29>>^ — Logo em seguida à tribulação daqueles dias, o sol escurecerá, a lua não dará a sua claridade, as estrelas cairão do firmamento e os poderes dos céus serão abalados.

[[v40-24-30]]

^<<v40-24-30,30>>^ Então aparecerá no céu o sinal do Filho do Homem. Todos os povos da terra se lamentarão e verão o Filho do Homem vindo sobre as nuvens do céu, com poder e grande glória.

[[v40-24-31]]

^<<v40-24-31,31>>^ E ele enviará os seus anjos, com grande som de trombeta, os quais reunirão os seus escolhidos dos quatro ventos, de uma a outra extremidade dos céus.

[[v40-24-32]]

^<<v40-24-32,32>>^ — Aprendam a parábola da figueira: quando já os seus ramos se renovam e as folhas brotam, vocês sabem que o verão está próximo.

[[v40-24-33]]

^<<v40-24-33,33>>^ Assim, também vocês, quando virem todas estas coisas, saibam que está próximo, às portas.

[[v40-24-34]]

^<<v40-24-34,34>>^ Em verdade lhes digo que não passará esta geração sem que tudo isto aconteça.

[[v40-24-35]]

^<<v40-24-35,35>>^ Passará o céu e a terra, porém as minhas palavras não passarão.

[[v40-24-36]]

^<<v40-24-36,36>>^ — Mas a respeito daquele dia e hora ninguém sabe, nem os anjos dos céus, nem o Filho, senão o Pai.

[[v40-24-37]]

^<<v40-24-37,37>>^ Pois assim como foi nos dias de Noé, assim será também a vinda do Filho do Homem.

[[v40-24-38]]

^<<v40-24-38,38>>^ Pois assim como nos dias anteriores ao dilúvio comiam e bebiam, casavam e davam-se em casamento, até o dia em que Noé entrou na arca,

[[v40-24-39]]

^<<v40-24-39,39>>^ e não o perceberam, até que veio o dilúvio e os levou a todos, assim será também a vinda do Filho do Homem.

[[v40-24-40]]

^<<v40-24-40,40>>^ Então dois estarão no campo: um será levado, e o outro será deixado;

[[v40-24-41]]

^<<v40-24-41,41>>^ duas mulheres estarão trabalhando num moinho: uma será levada, e a outra será deixada.

[[v40-24-42]]

^<<v40-24-42,42>>^ — Portanto, vigiem, porque vocês não sabem em que dia virá o Senhor de vocês.

[[v40-24-43]]

^<<v40-24-43,43>>^ Porém, considerem isto: se o pai de família soubesse a que hora viria o ladrão, vigiaria e não deixaria que a sua casa fosse arrombada.

[[v40-24-44]]

^<<v40-24-44,44>>^ Por isso, estejam também vocês preparados, porque o Filho do Homem virá à hora em que vocês menos esperam.

[[v40-24-45]]

^<<v40-24-45,45>>^ — Quem é, pois, o servo fiel e prudente, a quem o senhor deixou encarregado dos demais servos, para lhes dar o sustento a seu tempo?

[[v40-24-46]]

^<<v40-24-46,46>>^ Bem-aventurado aquele servo a quem seu senhor, quando vier, achar fazendo assim.

[[v40-24-47]]

^<<v40-24-47,47>>^ Em verdade lhes digo que lhe confiará todos os seus bens.

[[v40-24-48]]

^<<v40-24-48,48>>^ Mas o que acontecerá se aquele servo, sendo mau, disser consigo mesmo: "Meu senhor demora para vir",

[[v40-24-49]]

^<<v40-24-49,49>>^ e começar a espancar os seus companheiros e a comer e beber com os bêbados?

[[v40-24-50]]

^<<v40-24-50,50>>^ Virá o senhor daquele servo, em dia em que não o espera e em hora que não sabe,

[[v40-24-51]]

^<<v40-24-51,51>>^ e irá aplicar-lhe um castigo severo, condenando-o com os hipócritas. Ali haverá choro e ranger de dentes.

'''

xref:040-mateus/040-mateus-023.adoc#v40-23-0[&#60; Capítulo Anterior] | <<v40-24-0,Topo>> | xref:040-mateus/040-mateus-025.adoc#v40-25-0[Próximo Capítulo &#62;]