include::./index.adoc[]

[[v40-28-0]]
=== Mateus, 28
// naa ?, NAA - Nova Almeida Atualizada

[[v40-28-1]]

^<<v40-28-1,1>>^ Passado o sábado, no começo do primeiro dia da semana, Maria Madalena e a outra Maria foram ver o túmulo.

[[v40-28-2]]

^<<v40-28-2,2>>^ E eis que houve um grande terremoto; porque um anjo do Senhor desceu do céu e, aproximando-se, removeu a pedra e sentou sobre ela.

[[v40-28-3]]

^<<v40-28-3,3>>^ O aspecto dele era como um relâmpago, e a sua roupa era branca como a neve.

[[v40-28-4]]

^<<v40-28-4,4>>^ E os guardas, com medo do anjo, tremeram e ficaram como se estivessem mortos.

[[v40-28-5]]

^<<v40-28-5,5>>^ Mas o anjo, dirigindo-se às mulheres, disse: — Não tenham medo! Sei que vocês procuram Jesus, que foi crucificado.

[[v40-28-6]]

^<<v40-28-6,6>>^ Ele não está aqui; ressuscitou, como tinha dito. Venham ver onde ele jazia.

[[v40-28-7]]

^<<v40-28-7,7>>^ Agora vão depressa e digam aos seus discípulos que ele ressuscitou dos mortos e vai adiante de vocês para a Galileia; lá vocês o verão. É como acabei de dizer a vocês.

[[v40-28-8]]

^<<v40-28-8,8>>^ E, retirando-se elas apressadamente do sepulcro, tomadas de medo e grande alegria, correram para anunciar isso aos discípulos.

[[v40-28-9]]

^<<v40-28-9,9>>^ E eis que Jesus veio ao encontro delas e disse: — Salve! E elas, aproximando-se, abraçaram os pés dele e o adoraram.

[[v40-28-10]]

^<<v40-28-10,10>>^ Então Jesus lhes disse: — Não tenham medo! Vão dizer aos meus irmãos que se dirijam à Galileia e lá eles me verão.

[[v40-28-11]]

^<<v40-28-11,11>>^ E, enquanto elas iam, eis que alguns da guarda foram à cidade e contaram aos principais sacerdotes tudo o que havia acontecido.

[[v40-28-12]]

^<<v40-28-12,12>>^ Reunindo-se eles em conselho com os anciãos, deram grande soma de dinheiro aos soldados,

[[v40-28-13]]

^<<v40-28-13,13>>^ recomendando-lhes: — Digam isto: "Os discípulos dele vieram de noite, enquanto estávamos dormindo, e roubaram o corpo."

[[v40-28-14]]

^<<v40-28-14,14>>^ E, se isto chegar ao conhecimento do governador, nós o convenceremos e faremos com que vocês não tenham maiores preocupações.

[[v40-28-15]]

^<<v40-28-15,15>>^ Os soldados receberam o dinheiro e fizeram como tinham sido instruídos. Esta versão se espalhou entre os judeus até o dia de hoje.

[[v40-28-16]]

^<<v40-28-16,16>>^ Os onze discípulos partiram para a Galileia, para o monte que Jesus lhes havia designado.

[[v40-28-17]]

^<<v40-28-17,17>>^ E, quando viram Jesus, o adoraram; mas alguns duvidaram.

[[v40-28-18]]

^<<v40-28-18,18>>^ Jesus, aproximando-se, falou-lhes, dizendo: — Toda a autoridade me foi dada no céu e na terra.

[[v40-28-19]]

^<<v40-28-19,19>>^ Portanto, vão e façam discípulos de todas as nações, batizando-os em nome do Pai, do Filho e do Espírito Santo,

[[v40-28-20]]

^<<v40-28-20,20>>^ ensinando-os a guardar todas as coisas que tenho ordenado a vocês. E eis que estou com vocês todos os dias até o fim dos tempos.

'''

xref:040-mateus/040-mateus-027.adoc#v40-27-0[&#60; Capítulo Anterior] | <<v40-28-0,Topo>> | xref:041-marcos/041-marcos-001.adoc#v41-1-0[Próximo Capítulo &#62;]