include::./index.adoc[]

[[v40-17-0]]
=== Mateus, 17
// naa ?, NAA - Nova Almeida Atualizada

[[v40-17-1]]

^<<v40-17-1,1>>^ Seis dias depois, Jesus tomou consigo Pedro e os irmãos Tiago e João e os levou, em particular, a um alto monte.

[[v40-17-2]]

^<<v40-17-2,2>>^ E Jesus foi transfigurado diante deles. O seu rosto resplandecia como o sol, e as suas roupas se tornaram brancas como a luz.

[[v40-17-3]]

^<<v40-17-3,3>>^ E eis que lhes apareceram Moisés e Elias, falando com Jesus.

[[v40-17-4]]

^<<v40-17-4,4>>^ Então Pedro, tomando a palavra, disse a Jesus: — Senhor, bom é estarmos aqui. Se o senhor quiser, farei aqui três tendas: uma para o senhor, outra para Moisés e outra para Elias.

[[v40-17-5]]

^<<v40-17-5,5>>^ Falava ele ainda, quando uma nuvem luminosa os envolveu; e eis, vindo da nuvem, uma voz que dizia: — Este é o meu Filho amado, em quem me agrado; escutem o que ele diz!

[[v40-17-6]]

^<<v40-17-6,6>>^ Ao ouvirem aquela voz, os discípulos caíram de bruços, tomados de grande medo.

[[v40-17-7]]

^<<v40-17-7,7>>^ Jesus aproximou-se e tocou neles, dizendo: — Levantem-se e não tenham medo!

[[v40-17-8]]

^<<v40-17-8,8>>^ Então eles, levantando os olhos, não viram mais ninguém, a não ser Jesus.

[[v40-17-9]]

^<<v40-17-9,9>>^ Ao descerem do monte, Jesus lhes ordenou: — Não contem a ninguém o que vocês viram, até que o Filho do Homem ressuscite dentre os mortos.

[[v40-17-10]]

^<<v40-17-10,10>>^ Mas os discípulos perguntaram a Jesus: — Por que, então, os escribas dizem ser necessário que Elias venha primeiro?

[[v40-17-11]]

^<<v40-17-11,11>>^ Jesus respondeu: — De fato, Elias virá e restaurará todas as coisas.

[[v40-17-12]]

^<<v40-17-12,12>>^ Eu, porém, lhes digo que Elias já veio, e não o reconheceram; pelo contrário, fizeram com ele tudo o que quiseram. Assim também o Filho do Homem irá sofrer nas mãos deles.

[[v40-17-13]]

^<<v40-17-13,13>>^ Então os discípulos entenderam que ele estava se referindo a João Batista.

[[v40-17-14]]

^<<v40-17-14,14>>^ Quando eles chegaram para junto da multidão, um homem se aproximou de Jesus, ajoelhou-se e disse:

[[v40-17-15]]

^<<v40-17-15,15>>^ — Senhor, tenha pena do meu filho, porque ele tem convulsões e sofre muito; pois muitas vezes cai no fogo e outras tantas cai na água.

[[v40-17-16]]

^<<v40-17-16,16>>^ Apresentei-o aos seus discípulos, mas eles não puderam curá-lo.

[[v40-17-17]]

^<<v40-17-17,17>>^ Jesus exclamou: — Ó geração incrédula e perversa! Até quando estarei com vocês? Até quando terei de suportá-los? Tragam o menino até aqui.

[[v40-17-18]]

^<<v40-17-18,18>>^ E Jesus repreendeu o demônio, e este saiu do menino; e, desde aquela hora, o menino ficou curado.

[[v40-17-19]]

^<<v40-17-19,19>>^ Então os discípulos, aproximando-se de Jesus, perguntaram em particular: — Por que motivo nós não pudemos expulsá-lo?

[[v40-17-20]]

^<<v40-17-20,20>>^ Jesus respondeu: — Por causa da pequenez da fé que vocês têm. Pois em verdade lhes digo que, se tiverem fé como um grão de mostarda, dirão a este monte: "Mude-se daqui para lá", e ele se mudará. Nada lhes será impossível.

[[v40-17-21]]

^<<v40-17-21,21>>^ &#91;Mas esse tipo de demônio só pode ser expulso por meio de oração e jejum.&#93;

[[v40-17-22]]

^<<v40-17-22,22>>^ Quando eles estavam reunidos na Galileia, Jesus lhes disse: — O Filho do Homem está para ser entregue nas mãos dos homens,

[[v40-17-23]]

^<<v40-17-23,23>>^ e estes o matarão; mas, ao terceiro dia, ressuscitará. Então os discípulos ficaram muito tristes.

[[v40-17-24]]

^<<v40-17-24,24>>^ Quando Jesus e os discípulos chegaram a Cafarnaum, os que cobravam o imposto das duas dracmas se dirigiram a Pedro e perguntaram: — O Mestre de vocês não paga as duas dracmas?

[[v40-17-25]]

^<<v40-17-25,25>>^ Pedro respondeu: — Claro que paga! Quando Pedro estava entrando em casa, Jesus se adiantou, dizendo: — Simão, o que você acha? De quem os reis da terra cobram impostos ou tributo: dos seus filhos ou dos estranhos?

[[v40-17-26]]

^<<v40-17-26,26>>^ Quando Pedro respondeu: "Dos estranhos", Jesus lhe disse: — Logo, os filhos estão isentos.

[[v40-17-27]]

^<<v40-17-27,27>>^ Mas, para que não os escandalizemos, vá ao mar, jogue o anzol e puxe o primeiro peixe que fisgar. Ao abrir a boca do peixe, você encontrará uma moeda. Pegue essa moeda e entregue aos cobradores, para pagar o meu imposto e o seu.

'''

xref:040-mateus/040-mateus-016.adoc#v40-16-0[&#60; Capítulo Anterior] | <<v40-17-0,Topo>> | xref:040-mateus/040-mateus-018.adoc#v40-18-0[Próximo Capítulo &#62;]