include::./index.adoc[]

[[v40-5-0]]
=== Mateus, 5
// naa ?, NAA - Nova Almeida Atualizada

[[v40-5-1]]

^<<v40-5-1,1>>^ Ao ver as multidões, Jesus subiu ao monte. Ele se assentou e os seus discípulos se aproximaram dele.

[[v40-5-2]]

^<<v40-5-2,2>>^ Então ele passou a ensiná-los. Jesus disse:

[[v40-5-3]]

^<<v40-5-3,3>>^ — Bem-aventurados os pobres em espírito, porque deles é o Reino dos Céus.

[[v40-5-4]]

^<<v40-5-4,4>>^ — Bem-aventurados os que choram, porque serão consolados.

[[v40-5-5]]

^<<v40-5-5,5>>^ — Bem-aventurados os mansos, porque herdarão a terra.

[[v40-5-6]]

^<<v40-5-6,6>>^ — Bem-aventurados os que têm fome e sede de justiça, porque serão saciados.

[[v40-5-7]]

^<<v40-5-7,7>>^ — Bem-aventurados os misericordiosos, porque alcançarão misericórdia.

[[v40-5-8]]

^<<v40-5-8,8>>^ — Bem-aventurados os limpos de coração, porque verão a Deus.

[[v40-5-9]]

^<<v40-5-9,9>>^ — Bem-aventurados os pacificadores, porque serão chamados filhos de Deus.

[[v40-5-10]]

^<<v40-5-10,10>>^ — Bem-aventurados os perseguidos por causa da justiça, porque deles é o Reino dos Céus.

[[v40-5-11]]

^<<v40-5-11,11>>^ — Bem-aventurados são vocês quando, por minha causa, os insultarem e os perseguirem, e, mentindo, disserem todo mal contra vocês.

[[v40-5-12]]

^<<v40-5-12,12>>^ Alegrem-se e exultem, porque é grande a sua recompensa nos céus; pois assim perseguiram os profetas que viveram antes de vocês.

[[v40-5-13]]

^<<v40-5-13,13>>^ — Vocês são o sal da terra; ora, se o sal vier a ser insípido, como lhe restaurar o sabor? Para nada mais presta senão para, lançado fora, ser pisado pelos homens.

[[v40-5-14]]

^<<v40-5-14,14>>^ — Vocês são a luz do mundo. Não se pode esconder uma cidade situada no alto de um monte.

[[v40-5-15]]

^<<v40-5-15,15>>^ Nem se acende uma lamparina para colocá-la debaixo de um cesto, mas num lugar adequado onde ilumina bem todos os que estão na casa.

[[v40-5-16]]

^<<v40-5-16,16>>^ Assim brilhe também a luz de vocês diante dos outros, para que vejam as boas obras que vocês fazem e glorifiquem o Pai de vocês, que está nos céus.

[[v40-5-17]]

^<<v40-5-17,17>>^ — Não pensem que vim revogar a Lei ou os Profetas; não vim para revogar, mas para cumprir.

[[v40-5-18]]

^<<v40-5-18,18>>^ Porque em verdade lhes digo: até que o céu e a terra passem, nem um i ou um til jamais passará da Lei, até que tudo se cumpra.

[[v40-5-19]]

^<<v40-5-19,19>>^ Aquele, pois, que desrespeitar um destes mandamentos, ainda que dos menores, e ensinar os outros a fazer o mesmo, será considerado mínimo no Reino dos Céus; aquele, porém, que os observar e ensinar, esse será considerado grande no Reino dos Céus.

[[v40-5-20]]

^<<v40-5-20,20>>^ Porque eu afirmo que, se a justiça de vocês não exceder em muito a dos escribas e fariseus, jamais entrarão no Reino dos Céus.

[[v40-5-21]]

^<<v40-5-21,21>>^ — Vocês ouviram o que foi dito aos antigos: "Não mate." E ainda: "Quem matar estará sujeito a julgamento."

[[v40-5-22]]

^<<v40-5-22,22>>^ Eu, porém, lhes digo que todo aquele que se irar contra o seu irmão estará sujeito a julgamento; e quem insultar o seu irmão estará sujeito a julgamento do tribunal; e quem o chamar de tolo estará sujeito ao inferno de fogo.

[[v40-5-23]]

^<<v40-5-23,23>>^ Portanto, se você estiver trazendo a sua oferta ao altar e lá se lembrar que o seu irmão tem alguma coisa contra você,

[[v40-5-24]]

^<<v40-5-24,24>>^ deixe diante do altar a sua oferta e vá primeiro reconciliar-se com o seu irmão; e então volte e faça a sua oferta.

[[v40-5-25]]

^<<v40-5-25,25>>^ — Entre em acordo sem demora com o seu adversário, enquanto você está com ele a caminho, para que o adversário não entregue você ao juiz, o juiz entregue você ao oficial de justiça, e você seja jogado na prisão.

[[v40-5-26]]

^<<v40-5-26,26>>^ Em verdade lhe digo que você não sairá dali enquanto não pagar o último centavo.

[[v40-5-27]]

^<<v40-5-27,27>>^ — Vocês ouviram o que foi dito: "Não cometa adultério."

[[v40-5-28]]

^<<v40-5-28,28>>^ Eu, porém, lhes digo: todo o que olhar para uma mulher com intenção impura, já cometeu adultério com ela no seu coração.

[[v40-5-29]]

^<<v40-5-29,29>>^ — Se o seu olho direito leva você a tropeçar, arranque-o e jogue-o fora. Pois é preferível você perder uma parte do seu corpo do que ter o corpo inteiro lançado no inferno.

[[v40-5-30]]

^<<v40-5-30,30>>^ E, se a sua mão direita leva você a tropeçar, corte-a e jogue-a fora. Pois é preferível você perder uma parte do seu corpo do que o corpo inteiro ir para o inferno.

[[v40-5-31]]

^<<v40-5-31,31>>^ — Também foi dito: "Aquele que repudiar a sua mulher deve dar-lhe uma carta de divórcio."

[[v40-5-32]]

^<<v40-5-32,32>>^ Eu, porém, lhes digo: quem repudiar a sua mulher, exceto em caso de relações sexuais ilícitas, a expõe a se tornar adúltera; e aquele que casar com a repudiada comete adultério.

[[v40-5-33]]

^<<v40-5-33,33>>^ — Vocês também ouviram o que foi dito aos antigos: "Não faça juramento falso, mas cumpra rigorosamente para com o Senhor o que você jurou."

[[v40-5-34]]

^<<v40-5-34,34>>^ Eu, porém, lhes digo: não jurem de modo nenhum; nem pelo céu, por ser o trono de Deus;

[[v40-5-35]]

^<<v40-5-35,35>>^ nem pela terra, por ser estrado de seus pés; nem por Jerusalém, por ser a cidade do grande Rei.

[[v40-5-36]]

^<<v40-5-36,36>>^ Não jure pela sua cabeça, porque você não pode fazer com que um só cabelo fique branco ou preto.

[[v40-5-37]]

^<<v40-5-37,37>>^ Que a palavra de vocês seja: Sim, sim; não, não. O que passar disto vem do Maligno.

[[v40-5-38]]

^<<v40-5-38,38>>^ — Vocês ouviram o que foi dito: "Olho por olho, dente por dente."

[[v40-5-39]]

^<<v40-5-39,39>>^ Eu, porém, lhes digo: Não resistam ao perverso. Se alguém lhe der um tapa na face direita, ofereça-lhe também a face esquerda.

[[v40-5-40]]

^<<v40-5-40,40>>^ Se alguém quer processar você e tirar-lhe a túnica, deixe que leve também a capa.

[[v40-5-41]]

^<<v40-5-41,41>>^ Se alguém obrigar você a andar uma milha, vá com ele duas.

[[v40-5-42]]

^<<v40-5-42,42>>^ Dê a quem lhe pede e não volte as costas ao que quer lhe pedir emprestado.

[[v40-5-43]]

^<<v40-5-43,43>>^ — Vocês ouviram o que foi dito: "Ame o seu próximo e odeie o seu inimigo."

[[v40-5-44]]

^<<v40-5-44,44>>^ Eu, porém, lhes digo: amem os seus inimigos e orem pelos que perseguem vocês,

[[v40-5-45]]

^<<v40-5-45,45>>^ para demonstrarem que são filhos do Pai de vocês, que está nos céus. Porque ele faz o seu sol nascer sobre maus e bons e vir chuvas sobre justos e injustos.

[[v40-5-46]]

^<<v40-5-46,46>>^ Porque, se vocês amam aqueles que os amam, que recompensa terão? Os publicanos também não fazem o mesmo?

[[v40-5-47]]

^<<v40-5-47,47>>^ E, se saudarem somente os seus irmãos, o que é que estão fazendo de mais? Os gentios também não fazem o mesmo?

[[v40-5-48]]

^<<v40-5-48,48>>^ Portanto, sejam perfeitos como é perfeito o Pai de vocês, que está no céu.

'''

xref:040-mateus/040-mateus-004.adoc#v40-4-0[&#60; Capítulo Anterior] | <<v40-5-0,Topo>> | xref:040-mateus/040-mateus-006.adoc#v40-6-0[Próximo Capítulo &#62;]