include::./index.adoc[]

[[v40-3-0]]
=== Mateus, 3
// naa ?, NAA - Nova Almeida Atualizada

[[v40-3-1]]

^<<v40-3-1,1>>^ Naqueles dias, apareceu João Batista pregando no deserto da Judeia.

[[v40-3-2]]

^<<v40-3-2,2>>^ Ele dizia: — Arrependam-se, porque está próximo o Reino dos Céus.

[[v40-3-3]]

^<<v40-3-3,3>>^ Pois é a João que se refere o que foi dito por meio do profeta Isaías: "Voz do que clama no deserto: Preparem o caminho do Senhor, endireitem as suas veredas."

[[v40-3-4]]

^<<v40-3-4,4>>^ João usava uma roupa feita de pelos de camelo e um cinto de couro. O seu alimento eram gafanhotos e mel silvestre.

[[v40-3-5]]

^<<v40-3-5,5>>^ Então os moradores de Jerusalém, de toda a Judeia e de toda a região em volta do Jordão iam até onde ele estava.

[[v40-3-6]]

^<<v40-3-6,6>>^ E, confessando os seus pecados, eram batizados por ele no rio Jordão.

[[v40-3-7]]

^<<v40-3-7,7>>^ Quando João viu que muitos fariseus e saduceus vinham ao seu batismo, disse-lhes: — Raça de víboras! Quem deu a entender que vocês podem fugir da ira que está por vir?

[[v40-3-8]]

^<<v40-3-8,8>>^ Produzam fruto digno de arrependimento!

[[v40-3-9]]

^<<v40-3-9,9>>^ E não pensem que podem dizer uns aos outros: "Temos por pai Abraão", porque eu afirmo a vocês que Deus pode fazer com que destas pedras surjam filhos a Abraão.

[[v40-3-10]]

^<<v40-3-10,10>>^ E o machado já está posto à raiz das árvores. Portanto, toda árvore que não produz bom fruto é cortada e lançada ao fogo.

[[v40-3-11]]

^<<v40-3-11,11>>^ Eu batizo vocês com água, para arrependimento; mas aquele que vem depois de mim é mais poderoso do que eu, do qual não sou digno de carregar as sandálias. Ele os batizará com o Espírito Santo e com fogo.

[[v40-3-12]]

^<<v40-3-12,12>>^ Ele tem a pá em suas mãos, limpará a sua eira e recolherá o seu trigo no celeiro; porém queimará a palha num fogo que nunca se apaga.

[[v40-3-13]]

^<<v40-3-13,13>>^ Por esse tempo, Jesus foi da Galileia para o rio Jordão, a fim de que João o batizasse.

[[v40-3-14]]

^<<v40-3-14,14>>^ João, porém, quis convencê-lo a mudar de ideia, dizendo: — Eu é que preciso ser batizado por você, e é você que vem a mim?

[[v40-3-15]]

^<<v40-3-15,15>>^ Mas Jesus respondeu: — Deixe por enquanto, porque assim nos convém cumprir toda a justiça. Então ele concordou.

[[v40-3-16]]

^<<v40-3-16,16>>^ Depois de batizado, Jesus logo saiu da água. E eis que os céus se abriram e ele viu o Espírito de Deus descendo como pomba, vindo sobre ele.

[[v40-3-17]]

^<<v40-3-17,17>>^ E eis que uma voz dos céus dizia: — Este é o meu Filho amado, em quem me agrado.

'''

xref:040-mateus/040-mateus-002.adoc#v40-2-0[&#60; Capítulo Anterior] | <<v40-3-0,Topo>> | xref:040-mateus/040-mateus-004.adoc#v40-4-0[Próximo Capítulo &#62;]