include::./index.adoc[]

[[v40-22-0]]
=== Mateus, 22
// naa ?, NAA - Nova Almeida Atualizada

[[v40-22-1]]

^<<v40-22-1,1>>^ De novo Jesus lhes falou por parábolas, dizendo:

[[v40-22-2]]

^<<v40-22-2,2>>^ — O Reino dos Céus é semelhante a um rei que preparou uma festa de casamento para seu filho.

[[v40-22-3]]

^<<v40-22-3,3>>^ Enviou os seus servos a chamar os convidados para a festa, mas estes não quiseram vir.

[[v40-22-4]]

^<<v40-22-4,4>>^ Enviou ainda outros servos, dizendo: "Digam aos convidados: Eis que já preparei o meu banquete; os meus bois e animais da engorda já foram abatidos, e tudo está pronto; venham para a festa."

[[v40-22-5]]

^<<v40-22-5,5>>^ Mas os convidados não se importaram e se foram, um para o seu campo, outro para o seu negócio.

[[v40-22-6]]

^<<v40-22-6,6>>^ Outros, agarrando os servos, os maltrataram e mataram.

[[v40-22-7]]

^<<v40-22-7,7>>^ — O rei ficou furioso e, enviando as suas tropas, exterminou aqueles assassinos e incendiou a cidade deles.

[[v40-22-8]]

^<<v40-22-8,8>>^ Então disse aos seus servos: "A festa está pronta, mas os convidados não eram dignos.

[[v40-22-9]]

^<<v40-22-9,9>>^ Vão, pois, para as encruzilhadas dos caminhos e convidem para o banquete todos os que vocês encontrarem."

[[v40-22-10]]

^<<v40-22-10,10>>^ E, saindo aqueles servos pelas estradas, reuniram todos os que encontraram, maus e bons; e a sala do banquete ficou cheia de convidados.

[[v40-22-11]]

^<<v40-22-11,11>>^ — Mas, quando o rei entrou para ver os que estavam à mesa, notou ali um homem que não trazia veste nupcial

[[v40-22-12]]

^<<v40-22-12,12>>^ e perguntou-lhe: "Amigo, como você entrou aqui sem veste nupcial?" E ele emudeceu.

[[v40-22-13]]

^<<v40-22-13,13>>^ Então o rei ordenou aos serventes: "Amarrem os pés e as mãos dele e atirem-no para fora, nas trevas; ali haverá choro e ranger de dentes."

[[v40-22-14]]

^<<v40-22-14,14>>^ Porque muitos são chamados, mas poucos são escolhidos.

[[v40-22-15]]

^<<v40-22-15,15>>^ Então os fariseus se retiraram e consultaram entre si como surpreenderiam Jesus em alguma palavra.

[[v40-22-16]]

^<<v40-22-16,16>>^ E enviaram-lhe discípulos, juntamente com os herodianos, para lhe dizer: — Mestre, sabemos que o senhor é verdadeiro e que ensina o caminho de Deus de acordo com a verdade, sem se importar com a opinião dos outros, porque não olha para a aparência das pessoas.

[[v40-22-17]]

^<<v40-22-17,17>>^ Assim sendo, diga-nos o que o senhor acha: é lícito pagar imposto a César ou não?

[[v40-22-18]]

^<<v40-22-18,18>>^ Mas Jesus, percebendo a maldade deles, respondeu: — Hipócritas, por que vocês estão me pondo à prova?

[[v40-22-19]]

^<<v40-22-19,19>>^ Mostrem-me a moeda do imposto. Trouxeram-lhe um denário.

[[v40-22-20]]

^<<v40-22-20,20>>^ E Jesus lhes perguntou: — De quem é esta figura e esta inscrição?

[[v40-22-21]]

^<<v40-22-21,21>>^ Eles responderam: — De César. Então Jesus lhes disse: — Deem, pois, a César o que é de César e a Deus o que é de Deus.

[[v40-22-22]]

^<<v40-22-22,22>>^ Ouvindo isto, se admiraram e, deixando-o, foram embora.

[[v40-22-23]]

^<<v40-22-23,23>>^ Naquele dia, alguns saduceus, que dizem não haver ressurreição, aproximaram-se de Jesus e lhe perguntaram:

[[v40-22-24]]

^<<v40-22-24,24>>^ — Mestre, Moisés disse: "Se alguém morrer, não tendo filhos, o irmão desse homem deve casar com a viúva e gerar descendentes para o falecido."

[[v40-22-25]]

^<<v40-22-25,25>>^ Ora, havia entre nós sete irmãos. O primeiro, tendo casado, morreu e, não tendo descendência, deixou sua mulher para seu irmão.

[[v40-22-26]]

^<<v40-22-26,26>>^ O mesmo aconteceu com o segundo, com o terceiro, até o sétimo.

[[v40-22-27]]

^<<v40-22-27,27>>^ Por fim, depois de todos, morreu também a mulher.

[[v40-22-28]]

^<<v40-22-28,28>>^ Portanto, na ressurreição, de qual dos sete ela será esposa? Porque todos casaram com ela.

[[v40-22-29]]

^<<v40-22-29,29>>^ Jesus respondeu: — O erro de vocês está no fato de não conhecerem as Escrituras nem o poder de Deus.

[[v40-22-30]]

^<<v40-22-30,30>>^ Porque, na ressurreição, nem casam, nem se dão em casamento, mas são como os anjos no céu.

[[v40-22-31]]

^<<v40-22-31,31>>^ Quanto à ressurreição dos mortos, vocês nunca leram o que Deus disse a vocês:

[[v40-22-32]]

^<<v40-22-32,32>>^ "Eu sou o Deus de Abraão, o Deus de Isaque e o Deus de Jacó"? Ele não é Deus de mortos, e sim de vivos.

[[v40-22-33]]

^<<v40-22-33,33>>^ Ouvindo isto, as multidões se maravilhavam da sua doutrina.

[[v40-22-34]]

^<<v40-22-34,34>>^ Entretanto, os fariseus, sabendo que Jesus havia silenciado os saduceus, reuniram-se em conselho.

[[v40-22-35]]

^<<v40-22-35,35>>^ E um deles, intérprete da Lei, querendo pôr Jesus à prova, perguntou-lhe:

[[v40-22-36]]

^<<v40-22-36,36>>^ — Mestre, qual é o grande mandamento na Lei?

[[v40-22-37]]

^<<v40-22-37,37>>^ Jesus respondeu: — "Ame o Senhor, seu Deus, de todo o seu coração, de toda a sua alma e de todo o seu entendimento."

[[v40-22-38]]

^<<v40-22-38,38>>^ Este é o grande e primeiro mandamento.

[[v40-22-39]]

^<<v40-22-39,39>>^ E o segundo, semelhante a este, é: "Ame o seu próximo como você ama a si mesmo."

[[v40-22-40]]

^<<v40-22-40,40>>^ Destes dois mandamentos dependem toda a Lei e os Profetas.

[[v40-22-41]]

^<<v40-22-41,41>>^ Estando reunidos os fariseus, Jesus lhes perguntou:

[[v40-22-42]]

^<<v40-22-42,42>>^ — O que vocês pensam do Cristo? De quem é filho? Eles responderam: — De Davi.

[[v40-22-43]]

^<<v40-22-43,43>>^ E Jesus perguntou: — Então, como é que Davi, pelo Espírito, chama o Cristo de Senhor, dizendo:

[[v40-22-44]]

^<<v40-22-44,44>>^ "Disse o Senhor ao meu Senhor: ‘Sente-se à minha direita, até que eu ponha os seus inimigos debaixo dos seus pés’"?

[[v40-22-45]]

^<<v40-22-45,45>>^ — Portanto, se Davi o chama de Senhor, como ele pode ser filho de Davi?

[[v40-22-46]]

^<<v40-22-46,46>>^ E ninguém podia lhe responder uma palavra; e a partir daquele dia ninguém mais ousou fazer perguntas.

'''

xref:040-mateus/040-mateus-021.adoc#v40-21-0[&#60; Capítulo Anterior] | <<v40-22-0,Topo>> | xref:040-mateus/040-mateus-023.adoc#v40-23-0[Próximo Capítulo &#62;]