include::./index.adoc[]

[[v40-27-0]]
=== Mateus, 27
// naa ?, NAA - Nova Almeida Atualizada

[[v40-27-1]]

^<<v40-27-1,1>>^ Ao romper o dia, todos os principais sacerdotes e os anciãos do povo entraram em conselho contra Jesus, para o matarem;

[[v40-27-2]]

^<<v40-27-2,2>>^ e, amarrando-o, levaram-no e o entregaram ao governador Pilatos.

[[v40-27-3]]

^<<v40-27-3,3>>^ Então Judas, que o traiu, vendo que Jesus havia sido condenado, tocado de remorso, devolveu as trinta moedas de prata aos principais sacerdotes e aos anciãos, dizendo:

[[v40-27-4]]

^<<v40-27-4,4>>^ — Pequei, traindo sangue inocente. Eles, porém, responderam: — Que nos importa? Isso é com você.

[[v40-27-5]]

^<<v40-27-5,5>>^ Então Judas, atirando as moedas de prata para dentro do templo, retirou-se e se enforcou.

[[v40-27-6]]

^<<v40-27-6,6>>^ E os principais sacerdotes, pegando as moedas, disseram: — Não é lícito colocá-las no cofre das ofertas, porque é preço de sangue.

[[v40-27-7]]

^<<v40-27-7,7>>^ E, tendo deliberado, compraram com elas o campo do oleiro, para cemitério de forasteiros.

[[v40-27-8]]

^<<v40-27-8,8>>^ Por isso, aquele campo é chamado, até o dia de hoje, Campo de Sangue.

[[v40-27-9]]

^<<v40-27-9,9>>^ Então se cumpriu o que foi dito por meio do profeta Jeremias: "Pegaram as trinta moedas de prata, preço em que foi estimado aquele a quem alguns dos filhos de Israel avaliaram,

[[v40-27-10]]

^<<v40-27-10,10>>^ e as deram pelo campo do oleiro, assim como me ordenou o Senhor."

[[v40-27-11]]

^<<v40-27-11,11>>^ Jesus estava em pé diante do governador, e este o interrogou, dizendo: — Você é o rei dos judeus? Jesus respondeu: — O senhor está dizendo isso.

[[v40-27-12]]

^<<v40-27-12,12>>^ E, sendo acusado pelos principais sacerdotes e pelos anciãos, Jesus nada respondeu.

[[v40-27-13]]

^<<v40-27-13,13>>^ Então Pilatos perguntou: — Não está ouvindo quantas acusações fazem contra você?

[[v40-27-14]]

^<<v40-27-14,14>>^ Mas Jesus não respondeu nem uma palavra, a ponto de o governador ficar muito admirado.

[[v40-27-15]]

^<<v40-27-15,15>>^ Ora, por ocasião da festa, o governador costumava soltar ao povo um preso, conforme eles quisessem.

[[v40-27-16]]

^<<v40-27-16,16>>^ Naquela ocasião, eles tinham um preso muito conhecido, chamado Barrabás.

[[v40-27-17]]

^<<v40-27-17,17>>^ Estando, pois, o povo reunido, Pilatos lhes perguntou: — Quem vocês querem que eu solte: Barrabás ou Jesus, chamado Cristo?

[[v40-27-18]]

^<<v40-27-18,18>>^ Porque sabia que era por inveja que eles tinham entregado Jesus.

[[v40-27-19]]

^<<v40-27-19,19>>^ E, estando Pilatos sentado no tribunal, a mulher dele mandou dizer-lhe: — Não se envolva com esse justo, porque hoje, em sonho, sofri muito por causa dele.

[[v40-27-20]]

^<<v40-27-20,20>>^ Mas os principais sacerdotes e os anciãos persuadiram o povo a que pedisse Barrabás e condenasse Jesus à morte.

[[v40-27-21]]

^<<v40-27-21,21>>^ De novo, o governador perguntou: — Qual dos dois vocês querem que eu solte? Eles responderam: — Barrabás!

[[v40-27-22]]

^<<v40-27-22,22>>^ Pilatos lhes perguntou: — Que farei, então, com Jesus, chamado Cristo? Todos responderam: — Que seja crucificado!

[[v40-27-23]]

^<<v40-27-23,23>>^ Pilatos continuou: — Que mal ele fez? Porém eles gritavam cada vez mais: — Que seja crucificado!

[[v40-27-24]]

^<<v40-27-24,24>>^ Vendo Pilatos que nada conseguia e que, ao contrário, o tumulto aumentava, mandou trazer água e lavou as mãos diante do povo, dizendo: — Estou inocente do sangue deste homem; fique o caso com vocês!

[[v40-27-25]]

^<<v40-27-25,25>>^ E o povo todo respondeu: — Que o sangue dele caia sobre nós e sobre os nossos filhos!

[[v40-27-26]]

^<<v40-27-26,26>>^ Então Pilatos lhes soltou Barrabás. E, depois de mandar açoitar Jesus, entregou-o para ser crucificado.

[[v40-27-27]]

^<<v40-27-27,27>>^ Logo a seguir, os soldados do governador, levando Jesus para o Pretório, reuniram em torno dele toda a tropa.

[[v40-27-28]]

^<<v40-27-28,28>>^ Tiraram a roupa de Jesus e o vestiram com um manto escarlate.

[[v40-27-29]]

^<<v40-27-29,29>>^ E, tecendo uma coroa de espinhos, a puseram na cabeça dele, e colocaram um caniço na sua mão direita. E, ajoelhando-se diante dele, zombavam, dizendo: — Salve, rei dos judeus!

[[v40-27-30]]

^<<v40-27-30,30>>^ E, cuspindo nele, pegaram o caniço e batiam na sua cabeça.

[[v40-27-31]]

^<<v40-27-31,31>>^ Depois de terem zombado dele, tiraram-lhe o manto e o vestiram com as suas próprias roupas. Então o levaram para ser crucificado.

[[v40-27-32]]

^<<v40-27-32,32>>^ Ao saírem, encontraram um cireneu, chamado Simão, a quem obrigaram a carregar a cruz de Jesus.

[[v40-27-33]]

^<<v40-27-33,33>>^ E, chegando a um lugar chamado Gólgota, que significa "Lugar da Caveira",

[[v40-27-34]]

^<<v40-27-34,34>>^ deram vinho com fel para Jesus beber; mas ele, provando-o, não quis beber.

[[v40-27-35]]

^<<v40-27-35,35>>^ Depois de o crucificarem, repartiram entre si as roupas dele, tirando a sorte.

[[v40-27-36]]

^<<v40-27-36,36>>^ E, assentados ali, o guardavam.

[[v40-27-37]]

^<<v40-27-37,37>>^ Por cima da cabeça de Jesus puseram por escrito a acusação contra ele: " Este é Jesus, o Rei dos Judeus ".

[[v40-27-38]]

^<<v40-27-38,38>>^ E dois ladrões foram crucificados com ele, um à sua direita e outro à sua esquerda.

[[v40-27-39]]

^<<v40-27-39,39>>^ Os que iam passando blasfemavam contra ele, balançando a cabeça e dizendo:

[[v40-27-40]]

^<<v40-27-40,40>>^ — Ei, você que destrói o santuário e em três dias o reedifica! Salve a si mesmo, se você é o Filho de Deus, e desça da cruz!

[[v40-27-41]]

^<<v40-27-41,41>>^ De igual modo, os principais sacerdotes com os escribas e anciãos, zombando, diziam:

[[v40-27-42]]

^<<v40-27-42,42>>^ — Salvou os outros, a si mesmo não pode salvar. É rei de Israel! Que ele desça da cruz, e então creremos nele.

[[v40-27-43]]

^<<v40-27-43,43>>^ Confiou em Deus; pois que Deus venha livrá-lo agora, se, de fato, lhe quer bem; porque ele disse: "Sou Filho de Deus."

[[v40-27-44]]

^<<v40-27-44,44>>^ Também os ladrões que haviam sido crucificados com ele o insultavam.

[[v40-27-45]]

^<<v40-27-45,45>>^ A partir do meio-dia, houve trevas sobre toda a terra até as três horas da tarde.

[[v40-27-46]]

^<<v40-27-46,46>>^ Por volta de três horas da tarde, Jesus clamou em alta voz, dizendo: — Eli, Eli, lemá sabactani?  — Isso quer dizer: "Deus meu, Deus meu, por que me desamparaste?"

[[v40-27-47]]

^<<v40-27-47,47>>^ Alguns dos que estavam ali, ouvindo isto, diziam: — Ele chama por Elias.

[[v40-27-48]]

^<<v40-27-48,48>>^ E, logo, um deles correu a buscar uma esponja e, tendo-a embebido em vinagre e colocado na ponta de um caniço, deu-lhe de beber.

[[v40-27-49]]

^<<v40-27-49,49>>^ Os outros, porém, diziam: — Espere! Vejamos se Elias vem salvá-lo.

[[v40-27-50]]

^<<v40-27-50,50>>^ E Jesus, clamando outra vez em alta voz, entregou o espírito.

[[v40-27-51]]

^<<v40-27-51,51>>^ Eis que o véu do santuário se rasgou em duas partes, de alto a baixo; a terra tremeu e as rochas se partiram;

[[v40-27-52]]

^<<v40-27-52,52>>^ os túmulos se abriram, e muitos corpos de santos já falecidos ressuscitaram;

[[v40-27-53]]

^<<v40-27-53,53>>^ e, saindo dos túmulos depois da ressurreição de Jesus, entraram na cidade santa e apareceram a muitos.

[[v40-27-54]]

^<<v40-27-54,54>>^ O centurião e os que com ele guardavam Jesus, vendo o terremoto e tudo o que se passava, ficaram possuídos de grande temor e disseram: — Verdadeiramente este era o Filho de Deus.

[[v40-27-55]]

^<<v40-27-55,55>>^ Estavam ali muitas mulheres, observando de longe. Eram as que vinham seguindo Jesus desde a Galileia, para o servir.

[[v40-27-56]]

^<<v40-27-56,56>>^ Entre elas estavam Maria Madalena, Maria, mãe de Tiago e de José, e a mulher de Zebedeu.

[[v40-27-57]]

^<<v40-27-57,57>>^ Ao cair da tarde, veio um homem rico de Arimateia, chamado José, que era também discípulo de Jesus.

[[v40-27-58]]

^<<v40-27-58,58>>^ Este foi até Pilatos e lhe pediu o corpo de Jesus. Então Pilatos mandou que o corpo lhe fosse entregue.

[[v40-27-59]]

^<<v40-27-59,59>>^ E José, levando o corpo, envolveu-o num lençol limpo de linho

[[v40-27-60]]

^<<v40-27-60,60>>^ e o depositou no seu túmulo novo, que ele tinha mandado abrir na rocha; e, rolando uma grande pedra para a entrada do túmulo, foi embora.

[[v40-27-61]]

^<<v40-27-61,61>>^ Estavam ali, sentadas em frente do túmulo, Maria Madalena e a outra Maria.

[[v40-27-62]]

^<<v40-27-62,62>>^ No dia seguinte, que é o dia depois da preparação, os principais sacerdotes e os fariseus se reuniram com Pilatos

[[v40-27-63]]

^<<v40-27-63,63>>^ e lhe disseram: — Senhor, nós lembramos que aquele enganador, enquanto vivia, disse: "Depois de três dias ressuscitarei."

[[v40-27-64]]

^<<v40-27-64,64>>^ Portanto, mande que o túmulo seja guardado com segurança até o terceiro dia, para que não aconteça que, vindo os discípulos dele, o roubem e depois digam ao povo: "Ressuscitou dos mortos." E este último engano será pior do que o primeiro.

[[v40-27-65]]

^<<v40-27-65,65>>^ Pilatos respondeu: — Uma escolta está à disposição de vocês. Vão e guardem o túmulo como bem entenderem.

[[v40-27-66]]

^<<v40-27-66,66>>^ Indo eles, montaram guarda ao túmulo, selando a pedra e deixando ali a escolta.

'''

xref:040-mateus/040-mateus-026.adoc#v40-26-0[&#60; Capítulo Anterior] | <<v40-27-0,Topo>> | xref:040-mateus/040-mateus-028.adoc#v40-28-0[Próximo Capítulo &#62;]