include::./index.adoc[]

[[v40-15-0]]
=== Mateus, 15
// naa ?, NAA - Nova Almeida Atualizada

[[v40-15-1]]

^<<v40-15-1,1>>^ Então alguns fariseus e escribas vieram de Jerusalém até Jesus e perguntaram:

[[v40-15-2]]

^<<v40-15-2,2>>^ — Por que os seus discípulos transgridem a tradição dos anciãos? Pois não lavam as mãos, quando comem.

[[v40-15-3]]

^<<v40-15-3,3>>^ Jesus, porém, lhes respondeu: — Por que também vocês transgridem o mandamento de Deus, por causa da tradição de vocês?

[[v40-15-4]]

^<<v40-15-4,4>>^ Porque Deus disse: "Honre o seu pai e a sua mãe." E: "Quem maldisser o seu pai ou a sua mãe seja punido de morte."

[[v40-15-5]]

^<<v40-15-5,5>>^ Vocês, porém, dizem que, se alguém disser ao seu pai ou à sua mãe: "A ajuda que você poderia receber de mim é oferta ao Senhor",

[[v40-15-6]]

^<<v40-15-6,6>>^ esse não precisará mais honrar os seus pais. E, assim, vocês invalidam a palavra de Deus, por causa da tradição de vocês.

[[v40-15-7]]

^<<v40-15-7,7>>^ Hipócritas! Bem profetizou Isaías a respeito de vocês, dizendo:

[[v40-15-8]]

^<<v40-15-8,8>>^ "Este povo me honra com os lábios, mas o seu coração está longe de mim.

[[v40-15-9]]

^<<v40-15-9,9>>^ E em vão me adoram, ensinando doutrinas que são preceitos humanos."

[[v40-15-10]]

^<<v40-15-10,10>>^ E, convocando a multidão, Jesus disse: — Escutem e entendam:

[[v40-15-11]]

^<<v40-15-11,11>>^ o que contamina a pessoa não é o que entra pela boca, mas o que sai da boca; isto, sim, contamina a pessoa.

[[v40-15-12]]

^<<v40-15-12,12>>^ Então, aproximando-se dele os discípulos, disseram: — Sabia que os fariseus, ouvindo o que o senhor disse, ficaram escandalizados?

[[v40-15-13]]

^<<v40-15-13,13>>^ Mas ele respondeu: — Toda planta que meu Pai celeste não plantou será arrancada.

[[v40-15-14]]

^<<v40-15-14,14>>^ Esqueçam os fariseus; são cegos, guias de cegos. Ora, se um cego guiar outro cego, ambos cairão num buraco.

[[v40-15-15]]

^<<v40-15-15,15>>^ Então Pedro disse a Jesus: — Explique-nos esta parábola.

[[v40-15-16]]

^<<v40-15-16,16>>^ Jesus, porém, disse: — Também vocês ainda não entenderam?

[[v40-15-17]]

^<<v40-15-17,17>>^ Não compreendem que tudo o que entra pela boca desce para o estômago e depois é eliminado?

[[v40-15-18]]

^<<v40-15-18,18>>^ Mas o que sai da boca vem do coração, e é isso que contamina a pessoa.

[[v40-15-19]]

^<<v40-15-19,19>>^ Porque do coração procedem maus pensamentos, homicídios, adultérios, imoralidade sexual, furtos, falsos testemunhos, blasfêmias.

[[v40-15-20]]

^<<v40-15-20,20>>^ São estas as coisas que contaminam a pessoa; mas o comer sem lavar as mãos não a contamina.

[[v40-15-21]]

^<<v40-15-21,21>>^ Saindo dali, Jesus foi para a região de Tiro e Sidom.

[[v40-15-22]]

^<<v40-15-22,22>>^ E eis que uma mulher cananeia, que tinha vindo daqueles lados, clamava: — Senhor, Filho de Davi, tenha compaixão de mim! Minha filha está horrivelmente endemoniada.

[[v40-15-23]]

^<<v40-15-23,23>>^ Jesus, porém, não lhe respondeu palavra. Então os seus discípulos, aproximando-se, disseram: — Mande-a embora, pois vem gritando atrás de nós.

[[v40-15-24]]

^<<v40-15-24,24>>^ Mas Jesus respondeu: — Não fui enviado senão às ovelhas perdidas da casa de Israel.

[[v40-15-25]]

^<<v40-15-25,25>>^ Ela, porém, veio e o adorou, dizendo: — Senhor, me ajude!

[[v40-15-26]]

^<<v40-15-26,26>>^ Jesus respondeu: — Não é correto pegar o pão dos filhos e jogá-lo aos cachorrinhos.

[[v40-15-27]]

^<<v40-15-27,27>>^ A mulher disse: — É verdade, Senhor, pois os cachorrinhos comem das migalhas que caem da mesa dos seus donos.

[[v40-15-28]]

^<<v40-15-28,28>>^ Então Jesus exclamou: — Mulher, que grande fé você tem! Que seja feito como você quer. E, desde aquele momento, a filha dela ficou curada.

[[v40-15-29]]

^<<v40-15-29,29>>^ Saindo dali, Jesus foi para junto do mar da Galileia; e, subindo ao monte, assentou-se ali.

[[v40-15-30]]

^<<v40-15-30,30>>^ E vieram a ele muitas multidões trazendo consigo coxos, cegos, aleijados, mudos e muitos outros e os deixaram junto aos pés de Jesus; e ele os curou.

[[v40-15-31]]

^<<v40-15-31,31>>^ O povo ficou maravilhado ao ver que os mudos falavam, os aleijados recuperavam a saúde, os coxos andavam e os cegos viam. E glorificavam o Deus de Israel.

[[v40-15-32]]

^<<v40-15-32,32>>^ Então Jesus chamou os seus discípulos e disse: — Tenho compaixão desta gente, porque já faz três dias que eles estão comigo e não têm o que comer. E não quero mandá-los para casa em jejum, para que não desfaleçam pelo caminho.

[[v40-15-33]]

^<<v40-15-33,33>>^ Mas os discípulos lhe disseram: — Onde haverá neste deserto pão suficiente para saciar tão grande multidão?

[[v40-15-34]]

^<<v40-15-34,34>>^ Jesus perguntou: — Quantos pães vocês têm? Eles responderam: — Sete pães e alguns peixinhos.

[[v40-15-35]]

^<<v40-15-35,35>>^ Então, tendo mandado o povo assentar-se no chão,

[[v40-15-36]]

^<<v40-15-36,36>>^ pegou os sete pães e os peixes e, tendo dado graças, os partiu e deu aos discípulos, e estes distribuíram ao povo.

[[v40-15-37]]

^<<v40-15-37,37>>^ Todos comeram e se fartaram; e, dos pedaços que sobraram, recolheram sete cestos cheios.

[[v40-15-38]]

^<<v40-15-38,38>>^ Ora, os que comeram eram quatro mil homens, além de mulheres e crianças.

[[v40-15-39]]

^<<v40-15-39,39>>^ E, tendo despedido as multidões, Jesus entrou no barco e foi para o território de Magadã.

'''

xref:040-mateus/040-mateus-014.adoc#v40-14-0[&#60; Capítulo Anterior] | <<v40-15-0,Topo>> | xref:040-mateus/040-mateus-016.adoc#v40-16-0[Próximo Capítulo &#62;]