include::./index.adoc[]

[[v40-6-0]]
=== Mateus, 6
// naa ?, NAA - Nova Almeida Atualizada

[[v40-6-1]]

^<<v40-6-1,1>>^ — Evitem praticar as suas obras de justiça diante dos outros para serem vistos por eles; porque, sendo assim, vocês já não terão nenhuma recompensa junto do Pai de vocês, que está nos céus.

[[v40-6-2]]

^<<v40-6-2,2>>^ — Quando, pois, você der esmola, não fique tocando trombeta nas sinagogas e nas ruas, como fazem os hipócritas, para serem elogiados pelos outros. Em verdade lhes digo que eles já receberam a sua recompensa.

[[v40-6-3]]

^<<v40-6-3,3>>^ Mas, ao dar esmola, que a sua mão esquerda ignore o que a mão direita está fazendo,

[[v40-6-4]]

^<<v40-6-4,4>>^ para que a sua esmola fique em secreto. E o seu Pai, que vê em secreto, lhe dará a recompensa.

[[v40-6-5]]

^<<v40-6-5,5>>^ — E, quando orarem, não sejam como os hipócritas, que gostam de orar em pé nas sinagogas e nos cantos das praças, para serem vistos pelos outros. Em verdade lhes digo que eles já receberam a sua recompensa.

[[v40-6-6]]

^<<v40-6-6,6>>^ Mas, ao orar, entre no seu quarto e, fechada a porta, ore ao seu Pai, que está em secreto. E o seu Pai, que vê em secreto, lhe dará a recompensa.

[[v40-6-7]]

^<<v40-6-7,7>>^ E, orando, não usem vãs repetições, como os gentios; porque eles pensam que por muito falar serão ouvidos.

[[v40-6-8]]

^<<v40-6-8,8>>^ Não sejam, portanto, como eles; porque o Pai de vocês sabe o que vocês precisam, antes mesmo de lhe pedirem.

[[v40-6-9]]

^<<v40-6-9,9>>^ — Portanto, orem assim: "Pai nosso, que estás nos céus, santificado seja o teu nome;

[[v40-6-10]]

^<<v40-6-10,10>>^ venha o teu Reino; seja feita a tua vontade, assim na terra como no céu;

[[v40-6-11]]

^<<v40-6-11,11>>^ o pão nosso de cada dia nos dá hoje;

[[v40-6-12]]

^<<v40-6-12,12>>^ e perdoa-nos as nossas dívidas, assim como nós também perdoamos aos nossos devedores;

[[v40-6-13]]

^<<v40-6-13,13>>^ e não nos deixes cair em tentação; mas livra-nos do mal &#91;pois teu é o Reino, o poder e a glória para sempre. Amém&#93;!"

[[v40-6-14]]

^<<v40-6-14,14>>^ — Porque, se perdoarem aos outros as ofensas deles, também o Pai de vocês, que está no céu, perdoará vocês;

[[v40-6-15]]

^<<v40-6-15,15>>^ se, porém, não perdoarem aos outros as ofensas deles, também o Pai de vocês não perdoará as ofensas de vocês.

[[v40-6-16]]

^<<v40-6-16,16>>^ — Quando vocês jejuarem, não fiquem com uma aparência triste, como os hipócritas; porque desfiguram o rosto a fim de parecer aos outros que estão jejuando. Em verdade lhes digo que eles já receberam a sua recompensa.

[[v40-6-17]]

^<<v40-6-17,17>>^ Mas você, quando jejuar, unja a cabeça e lave o rosto,

[[v40-6-18]]

^<<v40-6-18,18>>^ a fim de não parecer aos outros que você está jejuando, e sim ao seu Pai, em secreto. E o seu Pai, que vê em secreto, lhe dará a recompensa.

[[v40-6-19]]

^<<v40-6-19,19>>^ — Não acumulem tesouros sobre a terra, onde as traças e a ferrugem corroem e onde ladrões escavam e roubam;

[[v40-6-20]]

^<<v40-6-20,20>>^ mas ajuntem tesouros no céu, onde as traças e a ferrugem não corroem, e onde ladrões não escavam, nem roubam.

[[v40-6-21]]

^<<v40-6-21,21>>^ Porque, onde estiver o seu tesouro, aí estará também o seu coração.

[[v40-6-22]]

^<<v40-6-22,22>>^ — Os olhos são a lâmpada do corpo. Se os seus olhos forem bons, todo o seu corpo será cheio de luz;

[[v40-6-23]]

^<<v40-6-23,23>>^ se, porém, os seus olhos forem maus, todo o seu corpo estará em trevas. Portanto, se a luz que existe em você são trevas, que grandes trevas serão!

[[v40-6-24]]

^<<v40-6-24,24>>^ — Ninguém pode servir a dois senhores; porque ou irá odiar um e amar o outro, ou irá se dedicar a um e desprezar o outro. Vocês não podem servir a Deus e às riquezas.

[[v40-6-25]]

^<<v40-6-25,25>>^ — Por isso, digo a vocês: não se preocupem com a sua vida, quanto ao que irão comer ou beber; nem com o corpo, quanto ao que irão vestir. Não é a vida mais do que o alimento, e não é o corpo mais do que as roupas?

[[v40-6-26]]

^<<v40-6-26,26>>^ Observem as aves do céu, que não semeiam, não colhem, nem ajuntam em celeiros. No entanto, o Pai de vocês, que está no céu, as sustenta. Será que vocês não valem muito mais do que as aves?

[[v40-6-27]]

^<<v40-6-27,27>>^ Quem de vocês, por mais que se preocupe, pode acrescentar um côvado ao curso da sua vida?

[[v40-6-28]]

^<<v40-6-28,28>>^ — E por que se preocupam com o que vão vestir? Observem como crescem os lírios do campo: eles não trabalham, nem fiam.

[[v40-6-29]]

^<<v40-6-29,29>>^ Eu, porém, afirmo a vocês que nem Salomão, em toda a sua glória, se vestiu como qualquer deles.

[[v40-6-30]]

^<<v40-6-30,30>>^ Ora, se Deus veste assim a erva do campo, que hoje existe e amanhã é lançada no forno, não fará muito mais por vocês, homens de pequena fé?

[[v40-6-31]]

^<<v40-6-31,31>>^ Portanto, não se preocupem, dizendo: "Que comeremos?", "Que beberemos?" ou "Com que nos vestiremos?"

[[v40-6-32]]

^<<v40-6-32,32>>^ Porque os gentios é que procuram todas estas coisas. O Pai de vocês, que está no céu, sabe que vocês precisam de todas elas.

[[v40-6-33]]

^<<v40-6-33,33>>^ Mas busquem em primeiro lugar o Reino de Deus e a sua justiça, e todas estas coisas lhes serão acrescentadas.

[[v40-6-34]]

^<<v40-6-34,34>>^ — Portanto, não se preocupem com o dia de amanhã, pois o amanhã trará os seus cuidados; basta ao dia o seu próprio mal.

'''

xref:040-mateus/040-mateus-005.adoc#v40-5-0[&#60; Capítulo Anterior] | <<v40-6-0,Topo>> | xref:040-mateus/040-mateus-007.adoc#v40-7-0[Próximo Capítulo &#62;]