include::./index.adoc[]

[[v40-16-0]]
=== Mateus, 16
// naa ?, NAA - Nova Almeida Atualizada

[[v40-16-1]]

^<<v40-16-1,1>>^ Os fariseus e os saduceus se aproximaram de Jesus e, tentando-o, pediram-lhe que lhes mostrasse um sinal vindo do céu.

[[v40-16-2]]

^<<v40-16-2,2>>^ Mas Jesus respondeu: — Chegada a tarde, vocês dizem: "Teremos tempo bom, porque o céu está avermelhado."

[[v40-16-3]]

^<<v40-16-3,3>>^ E, pela manhã, vocês dizem: "Hoje teremos tempestade, porque o céu está de um vermelho sombrio." Na verdade, vocês sabem interpretar a aparência do céu. Então como não são capazes de interpretar os sinais dos tempos?

[[v40-16-4]]

^<<v40-16-4,4>>^ Uma geração perversa e adúltera pede um sinal, mas nenhum sinal lhe será dado, senão o de Jonas. E, deixando-os, Jesus se retirou.

[[v40-16-5]]

^<<v40-16-5,5>>^ Ora, tendo os discípulos passado para a outra margem do lago, esqueceram-se de levar pão.

[[v40-16-6]]

^<<v40-16-6,6>>^ E Jesus lhes disse: — Fiquem atentos e tenham cuidado com o fermento dos fariseus e dos saduceus.

[[v40-16-7]]

^<<v40-16-7,7>>^ Eles, porém, começaram a discutir entre si, dizendo: — Ele diz isso porque não trouxemos pão.

[[v40-16-8]]

^<<v40-16-8,8>>^ Jesus percebeu isso e perguntou: — Por que estão discutindo entre vocês, homens de pequena fé, sobre o fato de não terem pão?

[[v40-16-9]]

^<<v40-16-9,9>>^ Vocês ainda não percebem, nem se lembram dos cinco pães para cinco mil homens e de quantos cestos vocês recolheram?

[[v40-16-10]]

^<<v40-16-10,10>>^ Nem dos sete pães para os quatro mil e de quantos cestos vocês recolheram?

[[v40-16-11]]

^<<v40-16-11,11>>^ Como não compreendem que eu não estava falando com vocês a respeito de pães? Tenham cuidado com o fermento dos fariseus e dos saduceus.

[[v40-16-12]]

^<<v40-16-12,12>>^ Então entenderam que Jesus lhes tinha dito que tivessem cuidado não com o fermento usado no pão, mas com a doutrina dos fariseus e saduceus.

[[v40-16-13]]

^<<v40-16-13,13>>^ Indo Jesus para a região de Cesareia de Filipe, perguntou a seus discípulos: — Quem os outros dizem que é o Filho do Homem?

[[v40-16-14]]

^<<v40-16-14,14>>^ E eles responderam: — Uns dizem que é João Batista; outros dizem que é Elias; e outros dizem que é Jeremias ou um dos profetas.

[[v40-16-15]]

^<<v40-16-15,15>>^ Ao que Jesus perguntou: — E vocês, quem dizem que eu sou?

[[v40-16-16]]

^<<v40-16-16,16>>^ Respondendo, Simão Pedro disse: — O senhor é o Cristo, o Filho do Deus vivo.

[[v40-16-17]]

^<<v40-16-17,17>>^ Então Jesus lhe afirmou: — Bem-aventurado é você, Simão Barjonas, porque não foi carne e sangue que revelaram isso a você, mas meu Pai, que está nos céus.

[[v40-16-18]]

^<<v40-16-18,18>>^ Também eu lhe digo que você é Pedro, e sobre esta pedra edificarei a minha igreja, e as portas do inferno não prevalecerão contra ela.

[[v40-16-19]]

^<<v40-16-19,19>>^ Eu lhe darei as chaves do Reino dos Céus; o que você ligar na terra terá sido ligado nos céus; e o que você desligar na terra terá sido desligado nos céus.

[[v40-16-20]]

^<<v40-16-20,20>>^ Então Jesus ordenou aos discípulos que não dissessem a ninguém que ele era o Cristo.

[[v40-16-21]]

^<<v40-16-21,21>>^ Desde esse tempo, Jesus começou a mostrar aos seus discípulos que era necessário que ele fosse para Jerusalém, sofresse muitas coisas nas mãos dos anciãos, dos principais sacerdotes e dos escribas, fosse morto e, no terceiro dia, ressuscitasse.

[[v40-16-22]]

^<<v40-16-22,22>>^ Então Pedro, chamando-o à parte, começou a repreendê-lo, dizendo: — Que Deus não permita, Senhor! Isso de modo nenhum irá lhe acontecer.

[[v40-16-23]]

^<<v40-16-23,23>>^ Mas Jesus, voltando-se, disse a Pedro: — Saia da minha frente, Satanás! Você é para mim uma pedra de tropeço, porque não leva em consideração as coisas de Deus, e sim as dos homens.

[[v40-16-24]]

^<<v40-16-24,24>>^ Então Jesus disse aos seus discípulos: — Se alguém quer vir após mim, negue a si mesmo, tome a sua cruz e siga-me.

[[v40-16-25]]

^<<v40-16-25,25>>^ Pois quem quiser salvar a sua vida a perderá; e quem perder a vida por minha causa, esse a achará.

[[v40-16-26]]

^<<v40-16-26,26>>^ De que adiantará uma pessoa ganhar o mundo inteiro e perder a sua alma? Ou que dará uma pessoa em troca de sua alma?

[[v40-16-27]]

^<<v40-16-27,27>>^ Porque o Filho do Homem há de vir na glória de seu Pai, com os seus anjos, e então retribuirá a cada um conforme as suas obras.

[[v40-16-28]]

^<<v40-16-28,28>>^ Em verdade lhes digo que, dos que aqui se encontram, existem alguns que não passarão pela morte até que vejam o Filho do Homem vir no seu Reino.

'''

xref:040-mateus/040-mateus-015.adoc#v40-15-0[&#60; Capítulo Anterior] | <<v40-16-0,Topo>> | xref:040-mateus/040-mateus-017.adoc#v40-17-0[Próximo Capítulo &#62;]