include::./index.adoc[]

[[v40-25-0]]
=== Mateus, 25
// naa ?, NAA - Nova Almeida Atualizada

[[v40-25-1]]

^<<v40-25-1,1>>^ — Então o Reino dos Céus será semelhante a dez virgens que, pegando as suas lamparinas, saíram a encontrar-se com o noivo.

[[v40-25-2]]

^<<v40-25-2,2>>^ Cinco delas eram imprudentes, e cinco, prudentes.

[[v40-25-3]]

^<<v40-25-3,3>>^ As imprudentes, ao pegar as suas lamparinas, não levaram óleo consigo,

[[v40-25-4]]

^<<v40-25-4,4>>^ mas as prudentes, além das lamparinas, levaram óleo nas vasilhas.

[[v40-25-5]]

^<<v40-25-5,5>>^ E, como o noivo estava demorando, todas ficaram sonolentas e adormeceram.

[[v40-25-6]]

^<<v40-25-6,6>>^ Mas, à meia-noite, ouviu-se um grito: "Eis o noivo! Saiam ao encontro dele!"

[[v40-25-7]]

^<<v40-25-7,7>>^ — Então todas aquelas virgens se levantaram e prepararam as suas lamparinas.

[[v40-25-8]]

^<<v40-25-8,8>>^ E as imprudentes disseram às prudentes: "Deem a nós um pouco do óleo que vocês trouxeram, porque as nossas lamparinas estão se apagando."

[[v40-25-9]]

^<<v40-25-9,9>>^ Mas as prudentes responderam: "Não! Porque então vai faltar tanto para nós como para vocês! Vão aos que o vendem e comprem óleo para vocês."

[[v40-25-10]]

^<<v40-25-10,10>>^ E, saindo elas para comprar, chegou o noivo, e as que estavam preparadas entraram com ele para a festa do casamento. E fechou-se a porta.

[[v40-25-11]]

^<<v40-25-11,11>>^ Mais tarde, chegaram as virgens imprudentes, dizendo: "Senhor, senhor, abra a porta para nós!"

[[v40-25-12]]

^<<v40-25-12,12>>^ Mas o noivo respondeu: "Em verdade lhes digo que não as conheço."

[[v40-25-13]]

^<<v40-25-13,13>>^ Portanto, vigiem, porque vocês não sabem o dia nem a hora.

[[v40-25-14]]

^<<v40-25-14,14>>^ — Pois será como um homem que, ausentando-se do país, chamou os seus servos e lhes confiou os seus bens.

[[v40-25-15]]

^<<v40-25-15,15>>^ A um deu cinco talentos, a outro deu dois e a outro deu um, de acordo com a capacidade de cada um deles; e então partiu.

[[v40-25-16]]

^<<v40-25-16,16>>^ O servo que tinha recebido cinco talentos saiu imediatamente a negociar com eles e ganhou outros cinco.

[[v40-25-17]]

^<<v40-25-17,17>>^ Do mesmo modo, o que tinha recebido dois ganhou outros dois.

[[v40-25-18]]

^<<v40-25-18,18>>^ Mas o servo que tinha recebido um talento, saindo, fez um buraco na terra e escondeu o dinheiro do seu senhor.

[[v40-25-19]]

^<<v40-25-19,19>>^ — Depois de muito tempo, o senhor daqueles servos voltou e fez um ajuste de contas com eles.

[[v40-25-20]]

^<<v40-25-20,20>>^ Aproximando-se o que tinha recebido cinco talentos, entregou outros cinco, dizendo: "O senhor me confiou cinco talentos; eis aqui outros cinco que ganhei."

[[v40-25-21]]

^<<v40-25-21,21>>^ O senhor disse: "Muito bem, servo bom e fiel; você foi fiel no pouco, sobre o muito o colocarei; venha participar da alegria do seu senhor."

[[v40-25-22]]

^<<v40-25-22,22>>^ — E, aproximando-se também o que tinha recebido dois talentos, disse: "O senhor me confiou dois talentos; eis aqui outros dois que ganhei."

[[v40-25-23]]

^<<v40-25-23,23>>^ Então o senhor disse: "Muito bem, servo bom e fiel; você foi fiel no pouco, sobre o muito o colocarei; venha participar da alegria do seu senhor."

[[v40-25-24]]

^<<v40-25-24,24>>^ — Chegando, por fim, o que tinha recebido um talento, disse: "Sabendo que o senhor é um homem severo, que colhe onde não plantou e ajunta onde não espalhou,

[[v40-25-25]]

^<<v40-25-25,25>>^ fiquei com medo e escondi o seu talento na terra; aqui está o que é seu."

[[v40-25-26]]

^<<v40-25-26,26>>^ Mas o senhor respondeu: "Servo mau e preguiçoso! Você sabia que eu colho onde não plantei e ajunto onde não espalhei?

[[v40-25-27]]

^<<v40-25-27,27>>^ Então você devia ter entregado o meu dinheiro aos banqueiros, e eu, ao voltar, receberia com juros o que é meu."

[[v40-25-28]]

^<<v40-25-28,28>>^ — "Portanto, tirem dele o talento e deem ao que tem dez.

[[v40-25-29]]

^<<v40-25-29,29>>^ Porque a todo o que tem, mais será dado, e terá em abundância; mas ao que não tem, até o que tem lhe será tirado.

[[v40-25-30]]

^<<v40-25-30,30>>^ Quanto ao servo inútil, lancem-no para fora, nas trevas. Ali haverá choro e ranger de dentes."

[[v40-25-31]]

^<<v40-25-31,31>>^ — Quando o Filho do Homem vier na sua majestade e todos os anjos com ele, então se assentará no trono da sua glória.

[[v40-25-32]]

^<<v40-25-32,32>>^ Todas as nações serão reunidas em sua presença, e ele separará uns dos outros, como o pastor separa as ovelhas dos cabritos:

[[v40-25-33]]

^<<v40-25-33,33>>^ porá as ovelhas à sua direita e os cabritos, à sua esquerda.

[[v40-25-34]]

^<<v40-25-34,34>>^ — Então o Rei dirá aos que estiverem à sua direita: "Venham, benditos de meu Pai! Venham herdar o Reino que está preparado para vocês desde a fundação do mundo.

[[v40-25-35]]

^<<v40-25-35,35>>^ Porque tive fome, e vocês me deram de comer; tive sede, e vocês me deram de beber; eu era forasteiro, e vocês me hospedaram;

[[v40-25-36]]

^<<v40-25-36,36>>^ eu estava nu, e vocês me vestiram; enfermo, e me visitaram; preso, e foram me ver."

[[v40-25-37]]

^<<v40-25-37,37>>^ — Então os justos perguntarão: "Quando foi que vimos o senhor com fome e lhe demos de comer? Ou com sede e lhe demos de beber?

[[v40-25-38]]

^<<v40-25-38,38>>^ E quando foi que vimos o senhor como forasteiro e o hospedamos? Ou nu e o vestimos?

[[v40-25-39]]

^<<v40-25-39,39>>^ E quando foi que vimos o senhor enfermo ou preso e fomos visitá-lo?"

[[v40-25-40]]

^<<v40-25-40,40>>^ — O Rei, respondendo, lhes dirá: "Em verdade lhes digo que, sempre que o fizeram a um destes meus pequeninos irmãos, foi a mim que o fizeram."

[[v40-25-41]]

^<<v40-25-41,41>>^ — Então o Rei dirá também aos que estiverem à sua esquerda: "Afastem-se de mim, malditos, para o fogo eterno, preparado para o diabo e seus anjos.

[[v40-25-42]]

^<<v40-25-42,42>>^ Porque tive fome, e vocês não me deram de comer; tive sede, e vocês não me deram de beber;

[[v40-25-43]]

^<<v40-25-43,43>>^ sendo forasteiro, vocês não me hospedaram; estando nu, vocês não me vestiram; achando-me enfermo e preso, vocês não foram me ver."

[[v40-25-44]]

^<<v40-25-44,44>>^ — E eles lhe perguntarão: "Quando foi que vimos o senhor com fome, com sede, forasteiro, nu, enfermo ou preso e não o socorremos?"

[[v40-25-45]]

^<<v40-25-45,45>>^ — Então o Rei responderá: "Em verdade lhes digo que, sempre que o deixaram de fazer a um destes mais pequeninos, foi a mim que o deixaram de fazer."

[[v40-25-46]]

^<<v40-25-46,46>>^ E estes irão para o castigo eterno, porém os justos irão para a vida eterna.

'''

xref:040-mateus/040-mateus-024.adoc#v40-24-0[&#60; Capítulo Anterior] | <<v40-25-0,Topo>> | xref:040-mateus/040-mateus-026.adoc#v40-26-0[Próximo Capítulo &#62;]