include::./index.adoc[]

[[v40-10-0]]
=== Mateus, 10
// naa ?, NAA - Nova Almeida Atualizada

[[v40-10-1]]

^<<v40-10-1,1>>^ Tendo Jesus chamado os seus doze discípulos, deu-lhes autoridade sobre espíritos imundos para os expulsar e para curar todo tipo de doenças e enfermidades.

[[v40-10-2]]

^<<v40-10-2,2>>^ Ora, os nomes dos doze apóstolos são estes: primeiro, Simão, chamado Pedro, e André, seu irmão; Tiago, filho de Zebedeu, e João, seu irmão;

[[v40-10-3]]

^<<v40-10-3,3>>^ Filipe e Bartolomeu; Tomé e Mateus, o publicano; Tiago, filho de Alfeu, e Tadeu;

[[v40-10-4]]

^<<v40-10-4,4>>^ Simão, o Zelote, e Judas Iscariotes, que foi quem o traiu.

[[v40-10-5]]

^<<v40-10-5,5>>^ Jesus enviou esses doze, dando-lhes as seguintes instruções: — Não tomem o caminho que leva aos gentios, nem entrem nas cidades dos samaritanos,

[[v40-10-6]]

^<<v40-10-6,6>>^ mas, de preferência, procurem as ovelhas perdidas da casa de Israel.

[[v40-10-7]]

^<<v40-10-7,7>>^ Pelo caminho, preguem que está próximo o Reino dos Céus.

[[v40-10-8]]

^<<v40-10-8,8>>^ Curem enfermos, ressuscitem mortos, purifiquem leprosos, expulsem demônios. Vocês receberam de graça; portanto, deem de graça.

[[v40-10-9]]

^<<v40-10-9,9>>^ Não levem ouro, nem prata, nem cobre em seus cintos;

[[v40-10-10]]

^<<v40-10-10,10>>^ nem sacola para o caminho, nem duas túnicas, nem sandálias, nem bordão; porque o trabalhador é digno do seu alimento.

[[v40-10-11]]

^<<v40-10-11,11>>^ — E, em qualquer cidade ou aldeia em que vocês entrarem, perguntem quem nelas é digno; e fiquem ali até saírem daquele lugar.

[[v40-10-12]]

^<<v40-10-12,12>>^ Ao entrarem na casa, saúdem-na.

[[v40-10-13]]

^<<v40-10-13,13>>^ Se a casa for digna, que a paz de vocês venha sobre ela; se, porém, não for digna, a paz voltará para vocês.

[[v40-10-14]]

^<<v40-10-14,14>>^ Se alguém não quiser recebê-los nem ouvir as palavras de vocês, ao saírem daquela casa ou daquela cidade, sacudam o pó dos pés.

[[v40-10-15]]

^<<v40-10-15,15>>^ Em verdade lhes digo que haverá menos rigor para Sodoma e Gomorra, no Dia do Juízo, do que para aquela cidade.

[[v40-10-16]]

^<<v40-10-16,16>>^ — Eis que eu os envio como ovelhas para o meio de lobos. Portanto, sejam prudentes como as serpentes e simples como as pombas.

[[v40-10-17]]

^<<v40-10-17,17>>^ Tenham cuidado com os homens, porque eles os entregarão aos tribunais e os açoitarão nas suas sinagogas.

[[v40-10-18]]

^<<v40-10-18,18>>^ Por minha causa vocês serão levados à presença de governadores e de reis, para lhes servir de testemunho, a eles e aos gentios.

[[v40-10-19]]

^<<v40-10-19,19>>^ E, quando entregarem vocês, não se preocupem quanto a como ou o que irão falar, porque, naquela hora, lhes será concedido o que vocês dirão.

[[v40-10-20]]

^<<v40-10-20,20>>^ Afinal, não são vocês que estão falando, mas o Espírito do Pai de vocês é quem fala por meio de vocês.

[[v40-10-21]]

^<<v40-10-21,21>>^ — Um irmão entregará à morte outro irmão, e o pai entregará o filho. Haverá filhos que se levantarão contra os seus pais e os matarão.

[[v40-10-22]]

^<<v40-10-22,22>>^ Todos odiarão vocês por causa do meu nome; aquele, porém, que ficar firme até o fim, esse será salvo.

[[v40-10-23]]

^<<v40-10-23,23>>^ Quando, porém, perseguirem vocês numa cidade, fujam para outra. Porque em verdade lhes digo que não terão percorrido as cidades de Israel, até que venha o Filho do Homem.

[[v40-10-24]]

^<<v40-10-24,24>>^ — O discípulo não está acima do seu mestre, nem o servo está acima do seu senhor.

[[v40-10-25]]

^<<v40-10-25,25>>^ Basta ao discípulo ser como o seu mestre, e ao servo ser como o seu senhor. Se chamaram o dono da casa de Belzebu, quanto mais os membros da sua casa!

[[v40-10-26]]

^<<v40-10-26,26>>^ — Portanto, não tenham medo deles. Pois não há nada encoberto que não venha a ser revelado, nem oculto que não venha a ser conhecido.

[[v40-10-27]]

^<<v40-10-27,27>>^ O que lhes digo às escuras, repitam a plena luz; e o que é dito para vocês ao pé do ouvido, proclamem dos telhados.

[[v40-10-28]]

^<<v40-10-28,28>>^ Não temam os que matam o corpo, mas não podem matar a alma; pelo contrário, temam aquele que pode fazer perecer no inferno tanto a alma como o corpo.

[[v40-10-29]]

^<<v40-10-29,29>>^ — Não se vendem dois pardais por uma moedinha? Entretanto, nenhum deles cairá no chão sem o consentimento do Pai de vocês.

[[v40-10-30]]

^<<v40-10-30,30>>^ E, quanto a vocês, até os cabelos da cabeça de vocês estão todos contados.

[[v40-10-31]]

^<<v40-10-31,31>>^ Portanto, não temam! Vocês valem bem mais do que muitos pardais.

[[v40-10-32]]

^<<v40-10-32,32>>^ — Portanto, todo aquele que me confessar diante dos outros, também eu o confessarei diante de meu Pai, que está nos céus;

[[v40-10-33]]

^<<v40-10-33,33>>^ mas aquele que me negar diante das pessoas, também eu o negarei diante de meu Pai, que está nos céus.

[[v40-10-34]]

^<<v40-10-34,34>>^ — Não pensem que eu vim trazer paz à terra; não vim trazer paz, mas espada.

[[v40-10-35]]

^<<v40-10-35,35>>^ Pois vim causar divisão entre o homem e o seu pai; entre a filha e a sua mãe e entre a nora e a sua sogra.

[[v40-10-36]]

^<<v40-10-36,36>>^ Assim, os inimigos de uma pessoa serão os da sua própria casa.

[[v40-10-37]]

^<<v40-10-37,37>>^ — Quem ama o seu pai ou a sua mãe mais do que a mim não é digno de mim; quem ama o seu filho ou a sua filha mais do que a mim não é digno de mim;

[[v40-10-38]]

^<<v40-10-38,38>>^ e quem não toma a sua cruz e vem após mim não é digno de mim.

[[v40-10-39]]

^<<v40-10-39,39>>^ Quem acha a sua vida a perderá; e quem perde a vida por minha causa, esse a achará.

[[v40-10-40]]

^<<v40-10-40,40>>^ — Quem recebe vocês é a mim que recebe; e quem recebe a mim recebe aquele que me enviou.

[[v40-10-41]]

^<<v40-10-41,41>>^ Quem recebe um profeta, no caráter de profeta, receberá a recompensa de profeta; quem recebe um justo, no caráter de justo, receberá a recompensa de justo.

[[v40-10-42]]

^<<v40-10-42,42>>^ E quem der de beber, ainda que seja um copo de água fria, a um destes pequeninos, por ser este meu discípulo, em verdade lhes digo que de modo nenhum perderá a sua recompensa.

'''

xref:040-mateus/040-mateus-009.adoc#v40-9-0[&#60; Capítulo Anterior] | <<v40-10-0,Topo>> | xref:040-mateus/040-mateus-011.adoc#v40-11-0[Próximo Capítulo &#62;]