include::./index.adoc[]

[[v40-13-0]]
=== Mateus, 13
// naa ?, NAA - Nova Almeida Atualizada

[[v40-13-1]]

^<<v40-13-1,1>>^ Naquele mesmo dia, Jesus saiu de casa e se assentou à beira-mar.

[[v40-13-2]]

^<<v40-13-2,2>>^ E grandes multidões se reuniram em volta dele, de modo que entrou num barco e se assentou. E toda a multidão estava em pé na praia.

[[v40-13-3]]

^<<v40-13-3,3>>^ E de muitas coisas lhes falou por parábolas, dizendo: — Eis que o semeador saiu a semear.

[[v40-13-4]]

^<<v40-13-4,4>>^ E, ao semear, uma parte caiu à beira do caminho, e, vindo as aves, a comeram.

[[v40-13-5]]

^<<v40-13-5,5>>^ Outra parte caiu em solo rochoso, onde a terra era pouca, e logo nasceu, visto não ser profunda a terra.

[[v40-13-6]]

^<<v40-13-6,6>>^ Saindo, porém, o sol, a queimou; e, porque não tinha raiz, secou-se.

[[v40-13-7]]

^<<v40-13-7,7>>^ Outra parte caiu entre os espinhos; e os espinhos cresceram e a sufocaram.

[[v40-13-8]]

^<<v40-13-8,8>>^ Outra, enfim, caiu em boa terra e deu fruto: a cem, a sessenta e a trinta por um.

[[v40-13-9]]

^<<v40-13-9,9>>^ Quem tem ouvidos para ouvir, ouça.

[[v40-13-10]]

^<<v40-13-10,10>>^ Então os discípulos se aproximaram de Jesus e lhe perguntaram: — Por que o senhor fala com eles por meio de parábolas?

[[v40-13-11]]

^<<v40-13-11,11>>^ Ao que Jesus respondeu: — Porque a vocês é dado conhecer os mistérios do Reino dos Céus, mas àqueles isso não é concedido.

[[v40-13-12]]

^<<v40-13-12,12>>^ Pois ao que tem, mais será dado, e terá em abundância; mas, ao que não tem, até o que tem lhe será tirado.

[[v40-13-13]]

^<<v40-13-13,13>>^ Por isso, falo com eles por meio de parábolas: porque, vendo, não veem; e, ouvindo, não ouvem, nem entendem.

[[v40-13-14]]

^<<v40-13-14,14>>^ Assim, neles se cumpre a profecia de Isaías: "Ouvindo, vocês ouvirão e de modo nenhum entenderão; vendo, vocês verão e de modo nenhum perceberão.

[[v40-13-15]]

^<<v40-13-15,15>>^ Porque o coração deste povo está endurecido; ouviram com os ouvidos tapados e fecharam os olhos; para não acontecer que vejam com os olhos, ouçam com os ouvidos, entendam com o coração, se convertam e sejam por mim curados."

[[v40-13-16]]

^<<v40-13-16,16>>^ — Bem-aventurados, porém, são os olhos de vocês, porque veem; e bem-aventurados são os ouvidos de vocês, porque ouvem.

[[v40-13-17]]

^<<v40-13-17,17>>^ Pois em verdade lhes digo que muitos profetas e justos desejaram ver o que vocês estão vendo, mas não viram; e quiseram ouvir o que vocês estão ouvindo, mas não ouviram.

[[v40-13-18]]

^<<v40-13-18,18>>^ — Ouçam, portanto, o que significa a parábola do semeador.

[[v40-13-19]]

^<<v40-13-19,19>>^ A todos os que ouvem a palavra do Reino e não a compreendem, vem o Maligno e arrebata o que lhes foi semeado no coração. Este é o que foi semeado à beira do caminho.

[[v40-13-20]]

^<<v40-13-20,20>>^ O que foi semeado em solo rochoso, esse é o que ouve a palavra e logo a recebe com alegria.

[[v40-13-21]]

^<<v40-13-21,21>>^ Mas ele não tem raiz em si mesmo, sendo de pouca duração. Quando chega a angústia ou a perseguição por causa da palavra, logo se escandaliza.

[[v40-13-22]]

^<<v40-13-22,22>>^ O que foi semeado entre os espinhos é o que ouve a palavra, porém as preocupações deste mundo e a fascinação das riquezas sufocam a palavra, e ela fica infrutífera.

[[v40-13-23]]

^<<v40-13-23,23>>^ Mas o que foi semeado em boa terra é o que ouve a palavra e a compreende; este frutifica e produz a cem, a sessenta e a trinta por um.

[[v40-13-24]]

^<<v40-13-24,24>>^ Jesus lhes propôs outra parábola, dizendo: — O Reino dos Céus é semelhante a um homem que semeou boa semente no seu campo.

[[v40-13-25]]

^<<v40-13-25,25>>^ Mas, enquanto todos estavam dormindo, veio o inimigo dele, semeou o joio no meio do trigo e foi embora.

[[v40-13-26]]

^<<v40-13-26,26>>^ E, quando as plantas cresceram e produziram fruto, apareceu também o joio.

[[v40-13-27]]

^<<v40-13-27,27>>^ Então os servos do dono da casa chegaram e disseram: "Patrão, o senhor não semeou boa semente no seu campo? De onde, então, vem o joio?"

[[v40-13-28]]

^<<v40-13-28,28>>^ Ele, porém, lhes respondeu: "Um inimigo fez isso." Mas os servos lhe perguntaram: "O senhor quer que a gente vá e arranque o joio?"

[[v40-13-29]]

^<<v40-13-29,29>>^ O dono da casa respondeu: "Não! Porque, ao separar o joio, vocês poderão arrancar também com ele o trigo.

[[v40-13-30]]

^<<v40-13-30,30>>^ Deixem que cresçam juntos até a colheita. E, no tempo da colheita, direi aos ceifeiros: ‘Ajuntem primeiro o joio e amarrem-no em feixes para ser queimado; mas recolham o trigo no meu celeiro.’"

[[v40-13-31]]

^<<v40-13-31,31>>^ Jesus lhes propôs outra parábola, dizendo: — O Reino dos Céus é semelhante a um grão de mostarda, que um homem pegou e plantou no seu campo.

[[v40-13-32]]

^<<v40-13-32,32>>^ Esse grão é, na verdade, a menor de todas as sementes, mas, quando cresce, é maior do que as hortaliças, e chega a ser uma árvore, de modo que as aves do céu vêm se aninhar nos seus ramos.

[[v40-13-33]]

^<<v40-13-33,33>>^ Jesus lhes contou ainda outra parábola: — O Reino dos Céus é semelhante ao fermento que uma mulher pegou e misturou em três medidas de farinha, até ficar tudo levedado.

[[v40-13-34]]

^<<v40-13-34,34>>^ Jesus disse todas estas coisas às multidões por parábolas e sem parábolas nada lhes dizia.

[[v40-13-35]]

^<<v40-13-35,35>>^ Isso aconteceu para se cumprir o que foi dito por meio do profeta: "Abrirei a minha boca em parábolas; publicarei coisas ocultas desde a criação do mundo."

[[v40-13-36]]

^<<v40-13-36,36>>^ Então, despedindo as multidões, Jesus foi para casa. E, aproximando-se dele os seus discípulos, disseram: — Explique-nos a parábola do joio do campo.

[[v40-13-37]]

^<<v40-13-37,37>>^ E Jesus respondeu: — O que semeia a boa semente é o Filho do Homem.

[[v40-13-38]]

^<<v40-13-38,38>>^ O campo é o mundo. A boa semente são os filhos do Reino; o joio são os filhos do Maligno.

[[v40-13-39]]

^<<v40-13-39,39>>^ O inimigo que o semeou é o diabo. A colheita é o fim dos tempos, e os ceifeiros são os anjos.

[[v40-13-40]]

^<<v40-13-40,40>>^ Pois, assim como o joio é colhido e jogado no fogo, assim será no fim dos tempos.

[[v40-13-41]]

^<<v40-13-41,41>>^ O Filho do Homem mandará os seus anjos, que ajuntarão do seu Reino todos os que servem de pedra de tropeço e os que praticam o mal

[[v40-13-42]]

^<<v40-13-42,42>>^ e os lançarão na fornalha acesa; ali haverá choro e ranger de dentes.

[[v40-13-43]]

^<<v40-13-43,43>>^ Então os justos resplandecerão como o sol, no Reino de seu Pai. Quem tem ouvidos para ouvir, ouça.

[[v40-13-44]]

^<<v40-13-44,44>>^ — O Reino dos Céus é semelhante a um tesouro escondido no campo, que um homem achou e escondeu. Então, transbordante de alegria, vai, vende tudo o que tem e compra aquele campo.

[[v40-13-45]]

^<<v40-13-45,45>>^ — O Reino dos Céus é também semelhante a um homem que negocia e procura boas pérolas.

[[v40-13-46]]

^<<v40-13-46,46>>^ Quando encontrou uma pérola de grande valor, ele foi, vendeu tudo o que tinha e comprou a pérola.

[[v40-13-47]]

^<<v40-13-47,47>>^ — O Reino dos Céus é ainda semelhante a uma rede que foi lançada ao mar e apanhou peixes de toda espécie.

[[v40-13-48]]

^<<v40-13-48,48>>^ E, quando já estava cheia, os pescadores a arrastaram para a praia e, assentados, escolheram os bons para os cestos e jogaram fora os ruins.

[[v40-13-49]]

^<<v40-13-49,49>>^ Assim será no fim dos tempos: os anjos sairão, separarão os maus dentre os justos

[[v40-13-50]]

^<<v40-13-50,50>>^ e os lançarão na fornalha acesa; ali haverá choro e ranger de dentes.

[[v40-13-51]]

^<<v40-13-51,51>>^ Então Jesus perguntou: — Vocês entenderam todas estas coisas? Eles responderam: — Sim!

[[v40-13-52]]

^<<v40-13-52,52>>^ Então Jesus lhes disse: — Por isso, todo escriba instruído no Reino dos Céus é semelhante a um pai de família que tira do seu depósito coisas novas e coisas velhas.

[[v40-13-53]]

^<<v40-13-53,53>>^ Quando Jesus acabou de contar essas parábolas, retirou-se dali.

[[v40-13-54]]

^<<v40-13-54,54>>^ E, chegando à sua terra, ensinava-os na sinagoga, de modo que se maravilhavam e diziam: — De onde lhe vêm esta sabedoria e estes poderes miraculosos?

[[v40-13-55]]

^<<v40-13-55,55>>^ Não é este o filho do carpinteiro? A sua mãe não se chama Maria, e seus irmãos não são Tiago, José, Simão e Judas?

[[v40-13-56]]

^<<v40-13-56,56>>^ Todas as suas irmãs não vivem entre nós? Então, de onde lhe vem tudo isto?

[[v40-13-57]]

^<<v40-13-57,57>>^ E escandalizavam-se por causa dele. Jesus, porém, lhes disse: — Nenhum profeta é desprezado, a não ser na sua terra e na sua casa.

[[v40-13-58]]

^<<v40-13-58,58>>^ E não fez ali muitos milagres, por causa da incredulidade deles.

'''

xref:040-mateus/040-mateus-012.adoc#v40-12-0[&#60; Capítulo Anterior] | <<v40-13-0,Topo>> | xref:040-mateus/040-mateus-014.adoc#v40-14-0[Próximo Capítulo &#62;]