include::./index.adoc[]

[[v22-1-0]]
=== Cânticos, 1
// naa ?, NAA - Nova Almeida Atualizada

[[v22-1-1]]

^<<v22-1-1,1>>^ Cântico dos cânticos de Salomão.

[[v22-1-2]]

^<<v22-1-2,2>>^ Beije-me com os beijos de sua boca! Porque o seu amor é melhor do que o vinho.

[[v22-1-3]]

^<<v22-1-3,3>>^ Suave é o aroma dos seus perfumes; como perfume derramado é o seu nome. Por isso, as donzelas o amam.

[[v22-1-4]]

^<<v22-1-4,4>>^ Leve-me com você! Vamos depressa! O rei me introduziu nos seus aposentos. Exultaremos e nos alegraremos por sua causa; do seu amor nos lembraremos, mais do que do vinho. Não é sem razão que o amam.

[[v22-1-5]]

^<<v22-1-5,5>>^ Eu sou morena e bonita, ó filhas de Jerusalém, como as tendas de Quedar, como as cortinas de Salomão.

[[v22-1-6]]

^<<v22-1-6,6>>^ Não olhem para a minha pele morena, porque o sol me queimou. Os filhos de minha mãe se indignaram contra mim e me puseram por guarda das vinhas; mas a minha vinha, que me pertence, não a guardei.

[[v22-1-7]]

^<<v22-1-7,7>>^ Diga-me, ó amado de minha alma: Onde você apascenta o seu rebanho? Onde você o faz repousar ao meio-dia? Diga, para que eu não ande vagando junto ao rebanho dos seus companheiros.

[[v22-1-8]]

^<<v22-1-8,8>>^ Se você, a mais bela das mulheres, não o sabe, siga as pisadas dos rebanhos e apascente os seus cabritos junto às tendas dos pastores.

[[v22-1-9]]

^<<v22-1-9,9>>^ Comparo você, minha querida, com as éguas das carruagens de Faraó.

[[v22-1-10]]

^<<v22-1-10,10>>^ O seu rosto fica lindo com os enfeites, o seu pescoço, com os colares.

[[v22-1-11]]

^<<v22-1-11,11>>^ Faremos para você enfeites de ouro, com incrustações de prata.

[[v22-1-12]]

^<<v22-1-12,12>>^ Enquanto o rei está assentado à sua mesa, o meu nardo exala o seu perfume.

[[v22-1-13]]

^<<v22-1-13,13>>^ O meu amado é para mim como um sachê de mirra, posto entre os meus seios.

[[v22-1-14]]

^<<v22-1-14,14>>^ O meu amado é para mim como um ramalhete de flores de hena nas vinhas de En-Gedi.

[[v22-1-15]]

^<<v22-1-15,15>>^ Como você é bela, minha querida! Como você é bela! Os seus olhos são como pombas.

[[v22-1-16]]

^<<v22-1-16,16>>^ Como você é belo, meu amado! Como é encantador! O nosso leito é de viçosa relva.

[[v22-1-17]]

^<<v22-1-17,17>>^ As vigas da nossa casa são os cedros, e o nosso teto são os ciprestes.

'''

xref:021-eclesiastes/021-eclesiastes-012.adoc#v21-12-0[&#60; Capítulo Anterior] | <<v22-1-0,Topo>> | xref:022-canticos/022-canticos-002.adoc#v22-2-0[Próximo Capítulo &#62;]