include::./index.adoc[]

[[v22-8-0]]
=== Cânticos, 8
// naa ?, NAA - Nova Almeida Atualizada

[[v22-8-1]]

^<<v22-8-1,1>>^ Quem dera que você fosse meu irmão, amamentado aos seios de minha mãe! Se eu o encontrasse na rua, poderia beijá-lo, e não me desprezariam!

[[v22-8-2]]

^<<v22-8-2,2>>^ Eu o levaria para a casa da minha mãe, e você me ensinaria; eu lhe daria de beber vinho aromático e o suco das minhas romãs.

[[v22-8-3]]

^<<v22-8-3,3>>^ A sua mão esquerda estaria debaixo da minha cabeça, e a sua direita me abraçaria.

[[v22-8-4]]

^<<v22-8-4,4>>^ Filhas de Jerusalém, jurem pelas gazelas e pelas corças selvagens que vocês não acordarão nem despertarão o amor, até que este o queira.

[[v22-8-5]]

^<<v22-8-5,5>>^ Quem é esta que vem subindo do deserto, apoiada em seu amado? Debaixo da macieira eu o despertei; ali a sua mãe teve dores de parto, ali esteve com dores aquela que o deu à luz.

[[v22-8-6]]

^<<v22-8-6,6>>^ Ponha-me como selo sobre o seu coração, como selo sobre o seu braço, porque o amor é tão forte como a morte, e o ciúme é tão duro como a sepultura. As suas chamas são chamas de fogo, são labaredas enormes.

[[v22-8-7]]

^<<v22-8-7,7>>^ As muitas águas não poderiam apagar o amor, nem os rios, afogá-lo. Ainda que alguém oferecesse todos os bens da sua casa para comprar o amor, receberia em troca apenas desprezo.

[[v22-8-8]]

^<<v22-8-8,8>>^ Temos uma irmãzinha que ainda não tem seios. Que faremos por esta nossa irmã, no dia em que for pedida em casamento?

[[v22-8-9]]

^<<v22-8-9,9>>^ Se ela fosse uma muralha, edificaríamos sobre ela uma torre de prata; se ela fosse uma porta, nós a reforçaríamos com tábuas de cedro.

[[v22-8-10]]

^<<v22-8-10,10>>^ Eu sou uma muralha, e os meus seios, como as suas torres. Por isso, sou para ele como aquela que encontra a paz.

[[v22-8-11]]

^<<v22-8-11,11>>^ Salomão teve uma vinha em Baal-Hamom. Ele a entregou a uns lavradores, e cada um lhe trazia pelo seu fruto mil moedas de prata.

[[v22-8-12]]

^<<v22-8-12,12>>^ A minha vinha, que me pertence, dessa cuido eu! Você, Salomão, terá as suas mil moedas, e os que guardam o fruto dela, as suas duzentas.

[[v22-8-13]]

^<<v22-8-13,13>>^ Você, que habita nos jardins, os meus companheiros querem ouvir a sua voz! Eu também quero ouvi-la.

[[v22-8-14]]

^<<v22-8-14,14>>^ Venha depressa, meu amado, correndo como um gamo ou um filho da gazela sobre os montes perfumados.

'''

xref:022-canticos/022-canticos-007.adoc#v22-7-0[&#60; Capítulo Anterior] | <<v22-8-0,Topo>> | xref:023-isaias/023-isaias-001.adoc#v23-1-0[Próximo Capítulo &#62;]