include::./index.adoc[]

[[v22-6-0]]
=== Cânticos, 6
// naa ?, NAA - Nova Almeida Atualizada

[[v22-6-1]]

^<<v22-6-1,1>>^ Para onde foi o seu amado, ó mais bela das mulheres? Que rumo tomou o seu amado, para que a ajudemos a encontrá-lo?

[[v22-6-2]]

^<<v22-6-2,2>>^ O meu amado desceu ao seu jardim, aos canteiros de bálsamo, para pastorear nos jardins e para colher os lírios.

[[v22-6-3]]

^<<v22-6-3,3>>^ Eu sou do meu amado, e o meu amado é meu; ele apascenta o seu rebanho entre os lírios.

[[v22-6-4]]

^<<v22-6-4,4>>^ Minha querida, você é bonita como Tirza, encantadora como Jerusalém, impressionante como um exército com bandeiras.

[[v22-6-5]]

^<<v22-6-5,5>>^ Desvie de mim os seus olhos, porque eles me perturbam. Os seus cabelos são como um rebanho de cabras que descem ondeantes de Gileade.

[[v22-6-6]]

^<<v22-6-6,6>>^ Os seus dentes são como um rebanho de ovelhas que sobem do lavadouro; cada uma tem o seu par, e nenhuma está faltando.

[[v22-6-7]]

^<<v22-6-7,7>>^ As suas faces, como romã partida, brilham através do véu.

[[v22-6-8]]

^<<v22-6-8,8>>^ Sessenta são as rainhas, oitenta, as concubinas, e as virgens, sem número;

[[v22-6-9]]

^<<v22-6-9,9>>^ mas uma só é a minha pombinha sem defeito, a mais querida da sua mãe, a predileta daquela que a deu à luz. As outras mulheres a veem e dizem que ela é feliz; as rainhas e as concubinas a louvam.

[[v22-6-10]]

^<<v22-6-10,10>>^ Quem é esta que aparece como a alva do dia, bonita como a lua, pura como o sol, impressionante como um exército com bandeiras?

[[v22-6-11]]

^<<v22-6-11,11>>^ Desci ao jardim das nogueiras, para ver os renovos do vale, para ver se brotavam as videiras, se as romãzeiras estavam em flor.

[[v22-6-12]]

^<<v22-6-12,12>>^ Não sei como, imaginei-me no carro do meu nobre povo!

[[v22-6-13]]

^<<v22-6-13,13>>^ Volte, volte, sulamita! Volte, volte, para que nós a contemplemos. Por que vocês querem contemplar a sulamita na dança de Maanaim?

'''

xref:022-canticos/022-canticos-005.adoc#v22-5-0[&#60; Capítulo Anterior] | <<v22-6-0,Topo>> | xref:022-canticos/022-canticos-007.adoc#v22-7-0[Próximo Capítulo &#62;]