include::./index.adoc[]

[[v22-2-0]]
=== Cânticos, 2
// naa ?, NAA - Nova Almeida Atualizada

[[v22-2-1]]

^<<v22-2-1,1>>^ Eu sou a rosa de Sarom, o lírio dos vales.

[[v22-2-2]]

^<<v22-2-2,2>>^ Como um lírio entre os espinhos, assim é a minha querida entre as donzelas.

[[v22-2-3]]

^<<v22-2-3,3>>^ Como a macieira entre as árvores do bosque, assim é o meu amado entre os jovens. Desejo muito a sua sombra e debaixo dela me assento, e o seu fruto é doce ao meu paladar.

[[v22-2-4]]

^<<v22-2-4,4>>^ Ele me levou à sala do banquete, e o seu estandarte sobre mim é o amor.

[[v22-2-5]]

^<<v22-2-5,5>>^ Sustentem-me com passas, confortem-me com maçãs, pois estou morrendo de amor.

[[v22-2-6]]

^<<v22-2-6,6>>^ A sua mão esquerda está debaixo da minha cabeça, e a direita me abraça.

[[v22-2-7]]

^<<v22-2-7,7>>^ Filhas de Jerusalém, jurem pelas gazelas e pelas corças selvagens que vocês não acordarão nem despertarão o amor, até que este o queira.

[[v22-2-8]]

^<<v22-2-8,8>>^ Ouço a voz do meu amado. Eis que ele vem, saltando sobre os montes, pulando sobre as colinas.

[[v22-2-9]]

^<<v22-2-9,9>>^ O meu amado é semelhante ao gamo ou ao filho da gazela. Eis que ele está detrás de nossa parede, olhando pelas janelas, espreitando pelas grades.

[[v22-2-10]]

^<<v22-2-10,10>>^ O meu amado fala e me diz: Levante-se, minha querida, minha linda, e venha comigo.

[[v22-2-11]]

^<<v22-2-11,11>>^ Porque eis que passou o inverno, a chuva cessou e se foi,

[[v22-2-12]]

^<<v22-2-12,12>>^ aparecem as flores na terra, chegou o tempo de cantarem as aves, e já se ouve a voz da rolinha em nossa terra.

[[v22-2-13]]

^<<v22-2-13,13>>^ A figueira começou a dar seus figos, e as vinhas em flor exalam o seu aroma. Levante-se, minha querida, minha linda, e venha comigo.

[[v22-2-14]]

^<<v22-2-14,14>>^ Minha pombinha, escondida nas fendas dos penhascos, no esconderijo das rochas escarpadas, mostre-me o seu rosto, deixe-me ouvir a sua voz; porque a sua voz é doce, e o seu rosto é lindo.

[[v22-2-15]]

^<<v22-2-15,15>>^ Peguem as raposas, as raposinhas, que devastam os vinhedos, porque as nossas vinhas estão em flor.

[[v22-2-16]]

^<<v22-2-16,16>>^ O meu amado é meu, e eu sou dele; ele apascenta o seu rebanho entre os lírios.

[[v22-2-17]]

^<<v22-2-17,17>>^ Antes que rompa o dia e fujam as sombras, volte, meu amado. Venha correndo como o gamo ou o filho das gazelas sobre os montes de Beter.

'''

xref:022-canticos/022-canticos-001.adoc#v22-1-0[&#60; Capítulo Anterior] | <<v22-2-0,Topo>> | xref:022-canticos/022-canticos-003.adoc#v22-3-0[Próximo Capítulo &#62;]