include::./index.adoc[]

[[v22-5-0]]
=== Cânticos, 5
// naa ?, NAA - Nova Almeida Atualizada

[[v22-5-1]]

^<<v22-5-1,1>>^ Já entrei no meu jardim, meu amor, minha noiva. Colhi a minha mirra com as especiarias, comi o meu favo com o mel, bebi o meu vinho com o leite. Comam e bebam, meus amigos; até ficarem embriagados de amor.

[[v22-5-2]]

^<<v22-5-2,2>>^ Eu dormia, mas o meu coração estava acordado. Eis a voz do meu amado, que está batendo: Deixe-me entrar, meu amor, minha querida, minha pombinha sem defeito, porque a minha cabeça está cheia de orvalho, e os meus cabelos, das gotas da noite.

[[v22-5-3]]

^<<v22-5-3,3>>^ Já tirei a minha túnica! Como posso vesti-la outra vez? Já lavei os pés! Como voltar a sujá-los?

[[v22-5-4]]

^<<v22-5-4,4>>^ O meu amado meteu a mão pela fresta, e o meu coração estremeceu.

[[v22-5-5]]

^<<v22-5-5,5>>^ Eu me levantei para abrir a porta ao meu amado. As minhas mãos destilavam mirra, e os meus dedos deixavam escorrer mirra preciosa sobre a tranca da porta.

[[v22-5-6]]

^<<v22-5-6,6>>^ Abri a porta ao meu amado, mas ele já tinha se afastado e ido embora. Eu tinha estremecido, quando ele me falou. Busquei-o, mas não o achei; chamei-o, mas ele não respondeu.

[[v22-5-7]]

^<<v22-5-7,7>>^ Os guardas, que rondavam a cidade, me encontraram; eles me espancaram e me feriram; os guardas das muralhas tomaram o meu manto.

[[v22-5-8]]

^<<v22-5-8,8>>^ Filhas de Jerusalém, jurem: se encontrarem o meu amado, digam que estou morrendo de amor.

[[v22-5-9]]

^<<v22-5-9,9>>^ O que é que o seu amado tem que os outros não tenham, ó mais bela das mulheres? O que é que o seu amado tem que os outros não tenham, para que você nos faça jurar?

[[v22-5-10]]

^<<v22-5-10,10>>^ O meu amado é alvo e rosado, o mais destacado entre dez mil.

[[v22-5-11]]

^<<v22-5-11,11>>^ A sua cabeça é como o ouro mais depurado, os seus cabelos ondulados são pretos como o corvo.

[[v22-5-12]]

^<<v22-5-12,12>>^ Os seus olhos são como pombas junto ao ribeiro, brancas como leite, banhando-se junto às correntes das águas.

[[v22-5-13]]

^<<v22-5-13,13>>^ As suas faces são como canteiros de bálsamo, como colinas de ervas aromáticas. Os seus lábios são como lírios que gotejam mirra preciosa.

[[v22-5-14]]

^<<v22-5-14,14>>^ As suas mãos são cilindros de ouro enfeitados de turquesas. O seu ventre é como alvo marfim, coberto de safiras.

[[v22-5-15]]

^<<v22-5-15,15>>^ As suas pernas são colunas de mármore, assentadas sobre bases de ouro puro. O aspecto do meu amado é como o do Líbano; ele é elegante como os cedros.

[[v22-5-16]]

^<<v22-5-16,16>>^ O seu falar é muito suave; sim, ele é totalmente desejável. Assim é o meu amado, assim é o meu esposo, ó filhas de Jerusalém.

'''

xref:022-canticos/022-canticos-004.adoc#v22-4-0[&#60; Capítulo Anterior] | <<v22-5-0,Topo>> | xref:022-canticos/022-canticos-006.adoc#v22-6-0[Próximo Capítulo &#62;]