include::./index.adoc[]

[[v17-1-0]]
=== Ester, 1
// naa ?, NAA - Nova Almeida Atualizada

[[v17-1-1]]

^<<v17-1-1,1>>^ Isto aconteceu nos dias de Assuero, o Assuero que reinou sobre cento e vinte e sete províncias, desde a Índia até a Etiópia.

[[v17-1-2]]

^<<v17-1-2,2>>^ Naqueles dias, quando Assuero reinava na cidadela de Susã,

[[v17-1-3]]

^<<v17-1-3,3>>^ no terceiro ano do seu reinado, deu um banquete a todos os seus oficiais e servidores. O exército da Pérsia e da Média, bem como os nobres e os governadores das províncias estavam presentes.

[[v17-1-4]]

^<<v17-1-4,4>>^ Então Assuero mostrou as riquezas da glória do seu reino e o esplendor da sua excelente grandeza durante muitos dias, durante cento e oitenta dias.

[[v17-1-5]]

^<<v17-1-5,5>>^ Passados esses dias, o rei deu um banquete a todo o povo que estava na cidadela de Susã, tanto para os maiores como para os menores, durante sete dias, no pátio do jardim do palácio real.

[[v17-1-6]]

^<<v17-1-6,6>>^ Havia cortinas de algodão, brancas e azuis, amarradas com cordões de linho e de púrpura a argolas de prata e a colunas de alabastro. A armação dos leitos era de ouro e de prata, sobre um piso de pórfiro, de mármore, de alabastro e de pedras preciosas.

[[v17-1-7]]

^<<v17-1-7,7>>^ A bebida era servida em taças de ouro, de vários tipos, e havia muito vinho real, graças à generosidade do rei.

[[v17-1-8]]

^<<v17-1-8,8>>^ Bebiam sem restrições, como estava prescrito, pois o rei havia ordenado a todos os oficiais da sua casa que fizessem segundo a vontade de cada um.

[[v17-1-9]]

^<<v17-1-9,9>>^ Também a rainha Vasti deu um banquete às mulheres no palácio do rei Assuero.

[[v17-1-10]]

^<<v17-1-10,10>>^ No sétimo dia, quando o seu coração já estava alegre por causa do vinho, o rei Assuero ordenou a Meumã, Bizta, Harbona, Bigtá, Abagta, Zetar e Carcas, os sete eunucos que serviam na presença dele,

[[v17-1-11]]

^<<v17-1-11,11>>^ que trouxessem à sua presença a rainha Vasti, com a coroa real. Ele queria mostrar aos povos e aos príncipes a beleza dela, pois ela era muito bonita.

[[v17-1-12]]

^<<v17-1-12,12>>^ Porém a rainha Vasti se recusou a atender a ordem do rei, transmitida por meio dos eunucos. Diante disso, o rei muito se enfureceu e se inflamou de raiva.

[[v17-1-13]]

^<<v17-1-13,13>>^ Então o rei consultou os sábios que entendiam dos tempos, porque era seu costume fazer isso na presença de todos os que conheciam a lei e o direito.

[[v17-1-14]]

^<<v17-1-14,14>>^ E os mais chegados a ele eram: Carsena, Setar, Admata, Társis, Meres, Marsena e Memucã, os sete príncipes dos persas e dos medos, que tinham acesso direto ao rei e se assentavam como principais no reino.

[[v17-1-15]]

^<<v17-1-15,15>>^ Ele perguntou: — Segundo a lei, o que se deve fazer à rainha Vasti, por não haver cumprido a ordem do rei Assuero, transmitida por meio dos eunucos?

[[v17-1-16]]

^<<v17-1-16,16>>^ Então Memucã disse na presença do rei e dos príncipes: — A rainha Vasti não somente ofendeu o rei, mas também todos os príncipes e todos os povos de todas as províncias do rei Assuero.

[[v17-1-17]]

^<<v17-1-17,17>>^ Porque a notícia do que a rainha fez chegará a todas as mulheres, de modo que desprezarão o seu marido, dizendo: "O rei Assuero mandou que a rainha Vasti fosse trazida à sua presença, mas ela não foi."

[[v17-1-18]]

^<<v17-1-18,18>>^ Hoje mesmo, as princesas da Pérsia e da Média, ao ouvirem o que a rainha fez, dirão o mesmo a todos os príncipes do rei. E assim haverá muito desprezo e indignação.

[[v17-1-19]]

^<<v17-1-19,19>>^ Se for do agrado do rei, que ele baixe um decreto real, e que se inscreva nas leis dos persas e dos medos e não se revogue, que Vasti fica proibida de comparecer à presença do rei Assuero. E que o rei dê o reino dela a outra que seja melhor do que ela.

[[v17-1-20]]

^<<v17-1-20,20>>^ Quando este decreto do rei for proclamado em todo o seu reino, que é tão vasto, todas as mulheres darão honra a seu marido, tanto ao mais importante como ao menos importante.

[[v17-1-21]]

^<<v17-1-21,21>>^ O conselho agradou tanto ao rei como aos príncipes; e o rei fez o que Memucã havia sugerido.

[[v17-1-22]]

^<<v17-1-22,22>>^ Enviou cartas a todas as províncias do reino, a cada província segundo o seu modo de escrever e a cada povo segundo a sua língua: que cada homem fosse senhor em sua casa, e que se falasse a língua do seu povo.

'''

xref:016-neemias/016-neemias-013.adoc#v16-13-0[&#60; Capítulo Anterior] | <<v17-1-0,Topo>> | xref:017-ester/017-ester-002.adoc#v17-2-0[Próximo Capítulo &#62;]