include::./index.adoc[]

[[v17-3-0]]
=== Ester, 3
// naa ?, NAA - Nova Almeida Atualizada

[[v17-3-1]]

^<<v17-3-1,1>>^ Depois disto, o rei Assuero engrandeceu Hamã, filho de Hamedata, agagita, e o exaltou, e lhe deu um cargo mais elevado do que o de todos os oficiais que estavam com ele.

[[v17-3-2]]

^<<v17-3-2,2>>^ Todos os servos do rei, que estavam à porta do rei, se inclinavam e se prostravam diante de Hamã, porque esta era a ordem do rei a respeito dele. Mordecai, porém, não se inclinava nem se prostrava.

[[v17-3-3]]

^<<v17-3-3,3>>^ Então os servos do rei, que estavam à porta do rei, perguntaram a Mordecai: — Por que você está transgredindo as ordens do rei?

[[v17-3-4]]

^<<v17-3-4,4>>^ Dia após dia eles falavam com Mordecai, mas ele não lhes dava ouvidos. Então contaram isso a Hamã, para ver se as palavras de Mordecai se manteriam em pé, porque ele lhes tinha declarado que era judeu.

[[v17-3-5]]

^<<v17-3-5,5>>^ Quando Hamã viu que Mordecai não se inclinava nem se prostrava diante dele, encheu-se de furor.

[[v17-3-6]]

^<<v17-3-6,6>>^ Porém julgou que era pouco, nos seus propósitos, atentar apenas contra Mordecai, porque lhe haviam declarado de que povo era Mordecai. Por isso, Hamã procurou destruir todos os judeus, povo de Mordecai, que havia em todo o reino de Assuero.

[[v17-3-7]]

^<<v17-3-7,7>>^ No primeiro mês, que é o mês de nisã, no décimo segundo ano do reinado de Assuero, foi lançado o Pur, isto é, fizeram um sorteio na presença de Hamã, para determinar o dia e o mês; e foi sorteado o décimo segundo mês, que é o mês de adar.

[[v17-3-8]]

^<<v17-3-8,8>>^ Então Hamã disse ao rei Assuero: — Existe um povo espalhado e disperso entre os povos em todas as províncias do seu reino, cujas leis são diferentes das leis de todos os povos. Eles não cumprem as leis do rei e por isso não convém tolerá-los.

[[v17-3-9]]

^<<v17-3-9,9>>^ Se for do agrado do rei, decrete-se que sejam mortos, e eu porei nas mãos dos que executarem a obra trezentas e quarenta toneladas de prata para que entrem nos tesouros do rei.

[[v17-3-10]]

^<<v17-3-10,10>>^ Então o rei tirou da mão o seu anel-sinete e o deu a Hamã, filho de Hamedata, agagita, inimigo dos judeus,

[[v17-3-11]]

^<<v17-3-11,11>>^ e lhe disse: — Fique com essa prata e faça com esse povo o que bem quiser.

[[v17-3-12]]

^<<v17-3-12,12>>^ No dia treze do primeiro mês, chamaram os secretários do rei e, segundo tudo o que Hamã havia ordenado, se escreveu aos sátrapas do rei, aos governadores de todas as províncias e aos chefes de cada povo. A ordem devia ser endereçada a cada província no seu próprio modo de escrever e a cada povo na sua própria língua. Foi escrita em nome do rei Assuero e selada com o anel-sinete do rei.

[[v17-3-13]]

^<<v17-3-13,13>>^ As cartas foram enviadas por meio de mensageiros a todas as províncias do rei, com instruções para que num só dia, o dia treze do décimo segundo mês, que é o mês de adar, todos os judeus, tanto os jovens como os velhos, as mulheres e as crianças, fossem destruídos, mortos e aniquilados, e que os seus bens fossem saqueados.

[[v17-3-14]]

^<<v17-3-14,14>>^ Uma cópia da carta, que determinava a proclamação da lei em todas as províncias, foi enviada a todos os povos, para que se preparassem para aquele dia.

[[v17-3-15]]

^<<v17-3-15,15>>^ Os mensageiros, impelidos pela ordem do rei, partiram imediatamente. E a lei foi proclamada na cidadela de Susã. O rei Assuero e Hamã se assentaram para beber, mas a cidade de Susã estava perplexa.

'''

xref:017-ester/017-ester-002.adoc#v17-2-0[&#60; Capítulo Anterior] | <<v17-3-0,Topo>> | xref:017-ester/017-ester-004.adoc#v17-4-0[Próximo Capítulo &#62;]