include::./index.adoc[]

[[v17-4-0]]
=== Ester, 4
// naa ?, NAA - Nova Almeida Atualizada

[[v17-4-1]]

^<<v17-4-1,1>>^ Quando Mordecai soube tudo o que havia passado, rasgou as suas roupas, se cobriu de pano de saco e de cinza, e saiu pela cidade, clamando em alta voz e soltando gritos de amargura.

[[v17-4-2]]

^<<v17-4-2,2>>^ Chegou até a porta do rei, porque ninguém vestido de pano de saco podia entrar pela porta do rei.

[[v17-4-3]]

^<<v17-4-3,3>>^ Em todas as províncias aonde chegava a palavra do rei e a sua lei, havia entre os judeus grande luto, com jejum, choro e lamentação; e muitos se deitavam em pano de saco e em cinza.

[[v17-4-4]]

^<<v17-4-4,4>>^ Então as servas de Ester e os eunucos vieram e contaram a ela o que se passava. A rainha ficou muito aflita. Mandou roupas para que Mordecai pudesse tirar a vestimenta de pano de saco e se vestisse, mas ele não aceitou.

[[v17-4-5]]

^<<v17-4-5,5>>^ Então Ester chamou Hataque, um dos eunucos do rei, que este tinha escolhido para a servir, e lhe ordenou que fosse a Mordecai para saber o que se passava e por que ele estava fazendo aquilo.

[[v17-4-6]]

^<<v17-4-6,6>>^ Hataque foi até a praça da cidade para encontrar-se com Mordecai junto à porta do rei.

[[v17-4-7]]

^<<v17-4-7,7>>^ Mordecai contou tudo o que havia acontecido com ele. Disse também a quantia certa de prata que Hamã tinha prometido pagar aos tesouros do rei pelo aniquilamento dos judeus.

[[v17-4-8]]

^<<v17-4-8,8>>^ Também lhe deu uma cópia do decreto escrito que havia sido publicado em Susã, ordenando a destruição dos judeus. Mordecai pediu a Hataque que mostrasse a cópia a Ester e a pusesse a par de tudo, a fim de que ela fosse falar com o rei e lhe pedisse misericórdia e, na sua presença, lhe suplicasse pelo povo dela.

[[v17-4-9]]

^<<v17-4-9,9>>^ Hataque voltou e transmitiu a Ester as palavras de Mordecai.

[[v17-4-10]]

^<<v17-4-10,10>>^ Então Ester falou com Hataque e mandou que ele entregasse a seguinte mensagem a Mordecai:

[[v17-4-11]]

^<<v17-4-11,11>>^ "Todos os servos do rei e o povo das províncias do rei sabem que, para qualquer homem ou mulher que, sem ser chamado, entrar no pátio interior para falar com o rei, não há outra sentença que não a de morte, a não ser que o rei estenda para essa pessoa o cetro de ouro, para que viva. E eu, nestes trinta dias, não fui chamada para comparecer diante do rei."

[[v17-4-12]]

^<<v17-4-12,12>>^ Estas palavras de Ester foram transmitidas a Mordecai.

[[v17-4-13]]

^<<v17-4-13,13>>^ Então Mordecai pediu que respondessem a Ester: "Não pense que, por estar no palácio real, você será a única, entre todos os judeus, que conseguirá escapar.

[[v17-4-14]]

^<<v17-4-14,14>>^ Porque, se você ficar calada agora, de outro lugar virá socorro e livramento para os judeus, mas você e a casa de seu pai perecerão. Mas quem sabe se não foi para uma conjuntura como esta que você foi elevada à condição de rainha?"

[[v17-4-15]]

^<<v17-4-15,15>>^ Então Ester pediu que levassem a Mordecai a seguinte resposta:

[[v17-4-16]]

^<<v17-4-16,16>>^ "Vá e reúna todos os judeus que estiverem em Susã, e jejuem por mim. Não comam nem bebam nada durante três dias, nem de noite nem de dia. Eu e as minhas servas também jejuaremos. Depois, irei falar com o rei, ainda que seja contra a lei; se eu tiver de morrer, morrerei."

[[v17-4-17]]

^<<v17-4-17,17>>^ Então Mordecai foi e fez tudo o que Ester lhe havia ordenado.

'''

xref:017-ester/017-ester-003.adoc#v17-3-0[&#60; Capítulo Anterior] | <<v17-4-0,Topo>> | xref:017-ester/017-ester-005.adoc#v17-5-0[Próximo Capítulo &#62;]