include::./index.adoc[]

[[v17-5-0]]
=== Ester, 5
// naa ?, NAA - Nova Almeida Atualizada

[[v17-5-1]]

^<<v17-5-1,1>>^ No terceiro dia, Ester se aprontou com os seus trajes reais e se pôs no pátio interior do palácio real, em frente à residência do rei. O rei estava sentado no seu trono real, voltado para a porta da residência.

[[v17-5-2]]

^<<v17-5-2,2>>^ Quando o rei viu a rainha Ester parada no pátio, ela alcançou favor diante dele, e o rei estendeu-lhe o cetro de ouro que tinha na mão. Ester se aproximou e tocou na ponta do cetro.

[[v17-5-3]]

^<<v17-5-3,3>>^ Então o rei perguntou: — O que é que você tem, rainha Ester? Qual é o seu pedido? Até a metade do reino lhe será dado.

[[v17-5-4]]

^<<v17-5-4,4>>^ Ester respondeu: — Se for do seu agrado, venha hoje com Hamã ao banquete que preparei para o rei.

[[v17-5-5]]

^<<v17-5-5,5>>^ Então o rei disse: — Peçam a Hamã que venha depressa, para que possamos atender ao pedido de Ester. Assim, o rei e Hamã foram ao banquete que Ester havia preparado.

[[v17-5-6]]

^<<v17-5-6,6>>^ Enquanto bebiam vinho, o rei disse a Ester: — Qual é o seu pedido? Peça, e lhe será dado. O que você quer? Será dado, mesmo que seja metade do reino.

[[v17-5-7]]

^<<v17-5-7,7>>^ Ester respondeu: — Meu pedido e o meu desejo são o seguinte:

[[v17-5-8]]

^<<v17-5-8,8>>^ se achei favor diante do rei, e se for do agrado do rei conceder o meu pedido e cumprir o meu desejo, então que o rei venha com Hamã ao banquete que vou preparar para eles amanhã. Então farei o pedido que o rei me concede.

[[v17-5-9]]

^<<v17-5-9,9>>^ Naquele dia, Hamã saiu alegre e animado. Mas ficou furioso ao encontrar Mordecai junto à porta do rei e ver que ele não se levantava nem tremia diante dele.

[[v17-5-10]]

^<<v17-5-10,10>>^ Porém Hamã se conteve e foi para casa. Depois mandou vir os seus amigos e Zeres, sua mulher.

[[v17-5-11]]

^<<v17-5-11,11>>^ Hamã falou sobre a glória das suas riquezas, a multidão de seus filhos, tudo em que o rei o tinha engrandecido e como o tinha exaltado sobre os oficiais e servos do rei.

[[v17-5-12]]

^<<v17-5-12,12>>^ E Hamã acrescentou: — A própria rainha Ester a ninguém mais convidou para vir com o rei ao banquete que tinha preparado, a não ser a mim. E também para amanhã estou convidado por ela, juntamente com o rei.

[[v17-5-13]]

^<<v17-5-13,13>>^ Porém tudo isto não me satisfaz, enquanto eu vir o judeu Mordecai sentado junto à porta do rei.

[[v17-5-14]]

^<<v17-5-14,14>>^ Então Zeres, a mulher de Hamã, e todos os amigos dele disseram: — Mande fazer uma forca de vinte e dois metros de altura e, pela manhã, diga ao rei que nela enforquem Mordecai. Então vá alegre com o rei ao banquete. A sugestão foi bem-aceita por Hamã, que mandou levantar a forca.

'''

xref:017-ester/017-ester-004.adoc#v17-4-0[&#60; Capítulo Anterior] | <<v17-5-0,Topo>> | xref:017-ester/017-ester-006.adoc#v17-6-0[Próximo Capítulo &#62;]