include::./index.adoc[]

[[v17-9-0]]
=== Ester, 9
// naa ?, NAA - Nova Almeida Atualizada

[[v17-9-1]]

^<<v17-9-1,1>>^ No dia treze do décimo segundo mês, que é o mês de adar, quando a palavra do rei e a sua ordem deveriam ser executadas, no dia em que os inimigos dos judeus esperavam apoderar-se deles, aconteceu o contrário, pois os judeus é que se apoderaram dos que os odiavam.

[[v17-9-2]]

^<<v17-9-2,2>>^ Nas suas cidades, em todas as províncias do rei Assuero, os judeus se reuniram para atacar aqueles que queriam destruí-los. E ninguém podia resistir-lhes, porque o terror que inspiravam caiu sobre todos aqueles povos.

[[v17-9-3]]

^<<v17-9-3,3>>^ Todos os oficiais das províncias, os sátrapas, os governadores e os oficiais do rei auxiliavam os judeus, porque o temor de Mordecai tinha caído sobre eles.

[[v17-9-4]]

^<<v17-9-4,4>>^ Porque Mordecai era grande na casa do rei, e a fama dele se espalhava por todas as províncias; o seu poder ia aumentando cada vez mais.

[[v17-9-5]]

^<<v17-9-5,5>>^ Assim, os judeus mataram todos os seus inimigos a golpes de espada, matando, destruindo e fazendo com os seus inimigos o que bem quiseram.

[[v17-9-6]]

^<<v17-9-6,6>>^ Na cidadela de Susã, os judeus mataram e destruíram quinhentos homens.

[[v17-9-7]]

^<<v17-9-7,7>>^ Mataram também Parsandata, Dalfom, Aspata,

[[v17-9-8]]

^<<v17-9-8,8>>^ Porata, Adalia, Aridata,

[[v17-9-9]]

^<<v17-9-9,9>>^ Farmasta, Arisai, Aridai e Vaizata,

[[v17-9-10]]

^<<v17-9-10,10>>^ que eram os dez filhos de Hamã, filho de Hamedata, o inimigo dos judeus; porém no despojo não tocaram.

[[v17-9-11]]

^<<v17-9-11,11>>^ No mesmo dia, o rei foi informado do número dos mortos na cidadela de Susã.

[[v17-9-12]]

^<<v17-9-12,12>>^ O rei disse à rainha Ester: — Na cidadela de Susã, os judeus mataram e destruíram quinhentos homens e os dez filhos de Hamã. E nas demais províncias do rei, o que será que fizeram? E agora, qual é o seu pedido? Peça, e lhe será dado. Você tem ainda algum outro desejo? Será concedido.

[[v17-9-13]]

^<<v17-9-13,13>>^ Então Ester disse: — Se for do agrado do rei, permita aos judeus de Susã que também amanhã façam segundo o decreto de hoje e pendurem em forca os cadáveres dos dez filhos de Hamã.

[[v17-9-14]]

^<<v17-9-14,14>>^ Então o rei ordenou que assim se fizesse. Um decreto foi publicado em Susã, e os cadáveres dos dez filhos de Hamã foram pendurados na forca.

[[v17-9-15]]

^<<v17-9-15,15>>^ Os judeus de Susã se reuniram também no dia catorze do mês de adar, e mataram trezentos homens em Susã; porém no despojo não tocaram.

[[v17-9-16]]

^<<v17-9-16,16>>^ Também os demais judeus que viviam nas províncias do rei se reuniram e se organizaram para defender a vida e se livrar dos seus inimigos. Mataram setenta e cinco mil dos que os odiavam; porém no despojo não tocaram.

[[v17-9-17]]

^<<v17-9-17,17>>^ Isto aconteceu no dia treze do mês de adar. No dia catorze, descansaram e fizeram dele um dia de festa e de alegria.

[[v17-9-18]]

^<<v17-9-18,18>>^ Mas os judeus de Susã se reuniram nos dias treze e catorze do mesmo mês. Descansaram no dia quinze e fizeram dele um dia de festa e de alegria.

[[v17-9-19]]

^<<v17-9-19,19>>^ Por isso os judeus das vilas, que moram nas aldeias do campo, fazem do dia catorze do mês de adar um dia de alegria, de banquetes e de festa, e um dia em que mandam presentes uns aos outros.

[[v17-9-20]]

^<<v17-9-20,20>>^ Mordecai escreveu estas coisas e enviou cartas a todos os judeus que moravam em todas as províncias do rei Assuero, aos de perto e aos de longe,

[[v17-9-21]]

^<<v17-9-21,21>>^ ordenando-lhes que comemorassem o dia catorze do mês de adar e o dia quinze do mesmo mês, todos os anos,

[[v17-9-22]]

^<<v17-9-22,22>>^ como os dias em que os judeus se livraram dos seus inimigos, o mês em que a tristeza virou alegria e o luto se transformou em festa. E que esses fossem dias de festa e de alegria, de troca de presentes e dádivas aos pobres.

[[v17-9-23]]

^<<v17-9-23,23>>^ Assim, os judeus aceitaram como costume o que, naquele tempo, haviam feito pela primeira vez, segundo Mordecai lhes havia ordenado por escrito.

[[v17-9-24]]

^<<v17-9-24,24>>^ Porque Hamã, filho de Hamedata, o agagita, inimigo de todos os judeus, tinha planejado destruir os judeus; e tinha lançado o "Pur", isto é, sortes, para os assolar e destruir.

[[v17-9-25]]

^<<v17-9-25,25>>^ Mas Ester foi falar com o rei, e ele ordenou por cartas que o plano perverso de Hamã, que ele tinha elaborado contra os judeus, recaísse sobre a própria cabeça dele, e que ele e os seus filhos fossem enforcados.

[[v17-9-26]]

^<<v17-9-26,26>>^ Por isso, esses dias são chamados de "Purim", do nome "Pur". Daí, por causa de todas as palavras daquela carta, e do que testemunharam, e do que lhes havia acontecido,

[[v17-9-27]]

^<<v17-9-27,27>>^ os judeus decidiram que eles mesmos, os seus descendentes e todos os que viessem se juntar a eles não deixariam de comemorar estes dois dias segundo o que se havia escrito a respeito deles, no tempo marcado, todos os anos.

[[v17-9-28]]

^<<v17-9-28,28>>^ E que estes dias seriam lembrados e comemorados geração após geração, por todas as famílias, em todas as províncias e em todas as cidades, e que estes dias de Purim jamais iriam desaparecer entre os judeus, e que a memória deles jamais se extinguiria entre os seus descendentes.

[[v17-9-29]]

^<<v17-9-29,29>>^ Então a rainha Ester, filha de Abiail, e o judeu Mordecai escreveram, com toda a autoridade, uma segunda carta, para confirmar a carta de Purim.

[[v17-9-30]]

^<<v17-9-30,30>>^ Mandaram cartas a todos os judeus, às cento e vinte e sete províncias do reino de Assuero, com palavras amigáveis e sinceras,

[[v17-9-31]]

^<<v17-9-31,31>>^ para confirmar estes dias de Purim nos seus tempos determinados, como o judeu Mordecai e a rainha Ester lhes haviam ordenado, e como eles mesmos já o tinham estabelecido sobre si e sobre a sua descendência, a respeito do jejum e do seu lamento.

[[v17-9-32]]

^<<v17-9-32,32>>^ E o decreto de Ester estabeleceu estas particularidades de Purim; e se escreveu no livro.

'''

xref:017-ester/017-ester-008.adoc#v17-8-0[&#60; Capítulo Anterior] | <<v17-9-0,Topo>> | xref:017-ester/017-ester-010.adoc#v17-10-0[Próximo Capítulo &#62;]