include::./index.adoc[]

[[v17-7-0]]
=== Ester, 7
// naa ?, NAA - Nova Almeida Atualizada

[[v17-7-1]]

^<<v17-7-1,1>>^ O rei foi com Hamã ao banquete da rainha Ester.

[[v17-7-2]]

^<<v17-7-2,2>>^ No segundo dia, durante o banquete do vinho, o rei perguntou a Ester: — Qual é o seu pedido, rainha Ester? Você será atendida. O que você quer? Até a metade do reino lhe será dado.

[[v17-7-3]]

^<<v17-7-3,3>>^ Então a rainha Ester disse: — Se eu tiver obtido o seu favor, ó rei, e se for do agrado do rei, que a minha vida seja a resposta ao meu pedido e que, como desejo, eu possa ter o meu povo.

[[v17-7-4]]

^<<v17-7-4,4>>^ Porque fomos vendidos, eu e o meu povo, para sermos destruídos, mortos e aniquilados de vez. Se ainda nos tivessem vendido como escravos e escravas, eu me calaria, pois não valeria a pena incomodar o rei por uma coisa dessas.

[[v17-7-5]]

^<<v17-7-5,5>>^ Então o rei Assuero perguntou à rainha Ester: — Quem é esse cujo coração o instigou a fazer uma coisa dessas? Onde está esse homem?

[[v17-7-6]]

^<<v17-7-6,6>>^ Ester respondeu: — O adversário e inimigo é este malvado Hamã. Então Hamã ficou apavorado diante do rei e da rainha.

[[v17-7-7]]

^<<v17-7-7,7>>^ O rei, no seu furor, se levantou do banquete do vinho e passou para o jardim do palácio. Hamã, porém, ficou para rogar por sua vida à rainha Ester, pois viu que o mal contra ele já estava determinado pelo rei.

[[v17-7-8]]

^<<v17-7-8,8>>^ Quando o rei voltou do jardim do palácio para a casa do banquete do vinho, Hamã tinha caído sobre o divã em que se achava Ester. Então o rei disse: — Será que ele queria desonrar a rainha diante de mim, aqui no meu palácio? Quando o rei acabou de dizer estas palavras, cobriram o rosto de Hamã.

[[v17-7-9]]

^<<v17-7-9,9>>^ Então Harbona, um dos eunucos que serviam o rei, disse: — Eis que existe junto à casa de Hamã a forca de vinte e dois metros de altura que ele preparou para Mordecai, aquele que havia falado em defesa do rei. Então o rei disse: — Que ele seja enforcado nela!

[[v17-7-10]]

^<<v17-7-10,10>>^ E assim enforcaram Hamã na forca que ele tinha preparado para Mordecai. Então o furor do rei se aplacou.

'''

xref:017-ester/017-ester-006.adoc#v17-6-0[&#60; Capítulo Anterior] | <<v17-7-0,Topo>> | xref:017-ester/017-ester-008.adoc#v17-8-0[Próximo Capítulo &#62;]