include::./index.adoc[]

[[v17-8-0]]
=== Ester, 8
// naa ?, NAA - Nova Almeida Atualizada

[[v17-8-1]]

^<<v17-8-1,1>>^ Naquele mesmo dia, o rei Assuero deu à rainha Ester a casa de Hamã, inimigo dos judeus. E Mordecai foi trazido à presença do rei, porque Ester revelou que ele era seu parente.

[[v17-8-2]]

^<<v17-8-2,2>>^ O rei pegou o seu anel-sinete, que havia tomado de Hamã, e o deu a Mordecai. E Ester pôs Mordecai por administrador da casa de Hamã.

[[v17-8-3]]

^<<v17-8-3,3>>^ Ester voltou a falar com o rei. Ela se lançou aos pés dele e, com lágrimas, lhe implorou que revogasse a maldade de Hamã, o agagita, e a trama que ele havia arquitetado contra os judeus.

[[v17-8-4]]

^<<v17-8-4,4>>^ O rei estendeu o cetro de ouro para Ester. Então ela se levantou, pôs-se em pé diante do rei

[[v17-8-5]]

^<<v17-8-5,5>>^ e disse: — Se for do agrado do rei, se eu achei favor diante dele, se isto parecer justo aos olhos do rei e se nisto lhe agrado, que se escreva uma ordem revogando os decretos concebidos por Hamã, filho de Hamedata, o agagita, os quais ele escreveu para aniquilar os judeus que se encontram em todas as províncias do rei.

[[v17-8-6]]

^<<v17-8-6,6>>^ Pois como poderei ver a desgraça que sobrevirá ao meu povo? E como poderei ver a destruição da minha parentela?

[[v17-8-7]]

^<<v17-8-7,7>>^ Então o rei Assuero disse à rainha Ester e ao judeu Mordecai: — Eis que dei a Ester a casa de Hamã, que foi pendurado numa forca, porque tinha planejado matar os judeus.

[[v17-8-8]]

^<<v17-8-8,8>>^ E agora, em nome do rei, escrevam aos judeus o que bem lhes parecer e selem o documento com o anel-sinete do rei. Porque os decretos feitos em nome do rei e que foram selados com o seu anel-sinete não podem ser revogados.

[[v17-8-9]]

^<<v17-8-9,9>>^ Então foram chamados imediatamente os secretários do rei, aos vinte e três dias do mês de sivã, que é o terceiro mês. E, segundo tudo o que Mordecai ordenou, foi redigido um decreto para os judeus, para os sátrapas, para os governadores e para os oficiais das províncias que se estendem da Índia até a Etiópia, cento e vinte e sete províncias, a cada uma no seu próprio modo de escrever, e a cada povo na sua própria língua; e também aos judeus segundo o seu próprio modo de escrever e na sua própria língua.

[[v17-8-10]]

^<<v17-8-10,10>>^ Escreveu-se em nome do rei Assuero, e se selou com o anel-sinete do rei. As cartas foram enviadas por meio de mensageiros montados em ginetes criados nas estrebarias do rei.

[[v17-8-11]]

^<<v17-8-11,11>>^ Nas cartas, o rei permitia aos judeus de cada cidade que se reunissem e se organizassem para defender a sua vida, para destruir, matar e aniquilar de vez toda e qualquer força armada do povo da província que viesse contra eles, crianças e mulheres, e que se saqueassem os seus bens,

[[v17-8-12]]

^<<v17-8-12,12>>^ num mesmo dia, em todas as províncias do rei Assuero, no dia treze do décimo segundo mês, que é o mês de adar.

[[v17-8-13]]

^<<v17-8-13,13>>^ Uma cópia da carta, que determinava a proclamação da lei em todas as províncias, foi enviada a todos os povos, para que os judeus se preparassem para aquele dia, para se vingarem dos seus inimigos.

[[v17-8-14]]

^<<v17-8-14,14>>^ Os mensageiros, montados em ginetes que se usavam no serviço do rei, partiram imediatamente, impelidos pela ordem do rei. E a lei foi publicada na cidadela de Susã.

[[v17-8-15]]

^<<v17-8-15,15>>^ Então Mordecai saiu da presença do rei com trajes reais em azul-celeste e branco, com uma grande coroa de ouro e um manto de linho fino e púrpura. E a cidade de Susã exultou e se alegrou.

[[v17-8-16]]

^<<v17-8-16,16>>^ Para os judeus houve felicidade, alegria, júbilo e honra.

[[v17-8-17]]

^<<v17-8-17,17>>^ Também em cada província e em cada cidade aonde chegava a palavra do rei e a sua ordem, havia entre os judeus alegria e júbilo, banquetes e festas. E muitos que eram dos povos da terra se tornaram judeus, porque o temor dos judeus tinha caído sobre eles.

'''

xref:017-ester/017-ester-007.adoc#v17-7-0[&#60; Capítulo Anterior] | <<v17-8-0,Topo>> | xref:017-ester/017-ester-009.adoc#v17-9-0[Próximo Capítulo &#62;]