include::./index.adoc[]

[[v3-7-0]]
=== Levítico, 7
// naa ?, NAA - Nova Almeida Atualizada

[[v3-7-1]]

^<<v3-7-1,1>>^ — Esta é a lei a respeito da oferta pela culpa; coisa santíssima é.

[[v3-7-2]]

^<<v3-7-2,2>>^ O animal que é oferta pelo pecado será morto no lugar onde são mortos os animais oferecidos em holocausto, e o seu sangue será aspergido sobre o altar, ao redor.

[[v3-7-3]]

^<<v3-7-3,3>>^ Dessa oferta se oferecerá toda a gordura, a cauda e a gordura que cobre as entranhas;

[[v3-7-4]]

^<<v3-7-4,4>>^ também ambos os rins e a gordura que está sobre eles, junto aos lombos; e a membrana sobre o fígado, que deve ser tirada com os rins.

[[v3-7-5]]

^<<v3-7-5,5>>^ O sacerdote o queimará sobre o altar em oferta queimada ao Senhor ; é oferta pela culpa.

[[v3-7-6]]

^<<v3-7-6,6>>^ Todos os homens da linhagem sacerdotal podem comer dela; no lugar santo, se comerá; coisa santíssima é.

[[v3-7-7]]

^<<v3-7-7,7>>^ — Como a oferta pelo pecado, assim será a oferta pela culpa; uma única lei haverá para elas: será do sacerdote que, com ela, fizer expiação.

[[v3-7-8]]

^<<v3-7-8,8>>^ O sacerdote que oferecer o holocausto de alguém terá o couro do holocausto que oferece.

[[v3-7-9]]

^<<v3-7-9,9>>^ Também toda oferta de cereais que for assada no forno, ou que se preparar na frigideira e na assadeira, será do sacerdote que a oferece.

[[v3-7-10]]

^<<v3-7-10,10>>^ Toda oferta de cereais amassada com azeite ou seca será de todos os filhos de Arão; cada um receberá a sua parte.

[[v3-7-11]]

^<<v3-7-11,11>>^ — Esta é a lei a respeito das ofertas pacíficas que alguém pode oferecer ao Senhor .

[[v3-7-12]]

^<<v3-7-12,12>>^ Se fizer por ação de graças, com a oferta de ação de graças trará bolos sem fermento amassados com azeite, pãezinhos sem fermento bem finos e untados com azeite e bolos feitos com a melhor farinha bem amassados com azeite.

[[v3-7-13]]

^<<v3-7-13,13>>^ Com os bolos trará, por sua oferta, pão levedado, com o sacrifício de sua oferta pacífica por ação de graças.

[[v3-7-14]]

^<<v3-7-14,14>>^ E, de toda oferta, trará um bolo por oferta ao Senhor , que será do sacerdote que aspergir o sangue da oferta pacífica.

[[v3-7-15]]

^<<v3-7-15,15>>^ Mas a carne do sacrifício de ação de graças da sua oferta pacífica se comerá no dia do seu oferecimento; nada se deixará dela até a manhã seguinte.

[[v3-7-16]]

^<<v3-7-16,16>>^ — E, se o sacrifício da oferta de alguém for voto ou oferta voluntária, no dia em que oferecer o seu sacrifício se comerá; e o que dele ficar também poderá ser comido no dia seguinte.

[[v3-7-17]]

^<<v3-7-17,17>>^ Porém o que ainda restar da carne do sacrifício ao terceiro dia, será queimado.

[[v3-7-18]]

^<<v3-7-18,18>>^ Se da carne do sacrifício pacífico se comer ao terceiro dia, aquele que a ofereceu não será aceito, nem lhe será atribuído o sacrifício; coisa abominável será, e a pessoa que dela comer levará a sua iniquidade.

[[v3-7-19]]

^<<v3-7-19,19>>^ — A carne que tocar alguma coisa impura não se comerá; será queimada. Quem estiver puro poderá comer a carne do sacrifício.

[[v3-7-20]]

^<<v3-7-20,20>>^ Porém, se alguma pessoa, tendo sobre si impureza, comer a carne do sacrifício pacífico, que é do Senhor , será eliminada do meio do seu povo.

[[v3-7-21]]

^<<v3-7-21,21>>^ Se uma pessoa tocar alguma coisa impura, como impureza humana, ou um animal impuro, ou qualquer impureza abominável, e comer da carne do sacrifício pacífico, que é do Senhor , será eliminada do meio do seu povo.

[[v3-7-22]]

^<<v3-7-22,22>>^ O Senhor  disse a Moisés:

[[v3-7-23]]

^<<v3-7-23,23>>^ — Fale aos filhos de Israel, dizendo: Não comam gordura de boi, nem de carneiro, nem de cabra.

[[v3-7-24]]

^<<v3-7-24,24>>^ A gordura do animal que morre por si mesmo e a do animal que é dilacerado por feras podem servir para qualquer outro uso, mas de maneira nenhuma poderá ser comida.

[[v3-7-25]]

^<<v3-7-25,25>>^ Quem comer a gordura do animal, do qual se trouxer ao Senhor  oferta queimada, será eliminado do meio do seu povo.

[[v3-7-26]]

^<<v3-7-26,26>>^ — Não comam sangue em qualquer das suas habitações, quer seja sangue de aves, quer seja sangue de gado.

[[v3-7-27]]

^<<v3-7-27,27>>^ Toda pessoa que comer algum sangue será eliminada do meio do seu povo.

[[v3-7-28]]

^<<v3-7-28,28>>^ O Senhor  disse a Moisés:

[[v3-7-29]]

^<<v3-7-29,29>>^ — Fale aos filhos de Israel, dizendo: Quem oferecer ao Senhor  o seu sacrifício pacífico trará a sua oferta ao Senhor . Do seu sacrifício pacífico

[[v3-7-30]]

^<<v3-7-30,30>>^ trará com suas próprias mãos as ofertas queimadas do Senhor . Trará a gordura do peito com o peito, para movê-lo por oferta movida diante do Senhor .

[[v3-7-31]]

^<<v3-7-31,31>>^ O sacerdote queimará a gordura sobre o altar, porém o peito será de Arão e de seus filhos.

[[v3-7-32]]

^<<v3-7-32,32>>^ Também a coxa direita vocês deverão dar ao sacerdote como oferta tirada dos sacrifícios pacíficos que vocês oferecem.

[[v3-7-33]]

^<<v3-7-33,33>>^ Aquele dos filhos de Arão que oferecer o sangue do sacrifício pacífico e a gordura, esse terá a coxa direita por sua porção.

[[v3-7-34]]

^<<v3-7-34,34>>^ Porque tomei dos filhos de Israel, dos seus sacrifícios pacíficos, o peito que é movido e a coxa da oferta e os dei a Arão, o sacerdote, e a seus filhos, por direito perpétuo dos filhos de Israel.

[[v3-7-35]]

^<<v3-7-35,35>>^ Esta é a porção de Arão e a porção de seus filhos, das ofertas queimadas do Senhor , no dia em que foram apresentados para oficiarem como sacerdotes ao Senhor .

[[v3-7-36]]

^<<v3-7-36,36>>^ Isto é o que o Senhor  ordenou que os filhos de Israel dessem a eles, no dia em que os ungiu; estatuto perpétuo é de geração em geração.

[[v3-7-37]]

^<<v3-7-37,37>>^ Esta é a lei a respeito do holocausto, da oferta de cereais, da oferta pelo pecado, da oferta pela culpa, da consagração e do sacrifício pacífico,

[[v3-7-38]]

^<<v3-7-38,38>>^ que o Senhor  ordenou a Moisés no monte Sinai, no dia em que ordenou aos filhos de Israel que oferecessem as suas ofertas ao Senhor , no deserto do Sinai.

'''

xref:003-levitico/003-levitico-006.adoc#v3-6-0[&#60; Capítulo Anterior] | <<v3-7-0,Topo>> | xref:003-levitico/003-levitico-008.adoc#v3-8-0[Próximo Capítulo &#62;]