include::./index.adoc[]

[[v3-2-0]]
=== Levítico, 2
// naa ?, NAA - Nova Almeida Atualizada

[[v3-2-1]]

^<<v3-2-1,1>>^ — Quando alguma pessoa fizer oferta de cereais ao Senhor , a sua oferta será da melhor farinha; derramará azeite sobre a farinha e porá incenso sobre ela.

[[v3-2-2]]

^<<v3-2-2,2>>^ Levará a oferta aos filhos de Arão, os sacerdotes, e um deles pegará um punhado da melhor farinha e do seu azeite com todo o seu incenso e os queimará como porção memorial sobre o altar; é oferta queimada, de aroma agradável ao Senhor .

[[v3-2-3]]

^<<v3-2-3,3>>^ O que ficar da oferta de cereais será de Arão e de seus filhos; é coisa santíssima das ofertas queimadas ao Senhor .

[[v3-2-4]]

^<<v3-2-4,4>>^ — Quando você trouxer oferta de cereais, assada no forno, será de bolos sem fermento feitos com a melhor farinha, amassados com azeite e pãezinhos bem finos, sem fermento e untados com azeite.

[[v3-2-5]]

^<<v3-2-5,5>>^ Se a oferta que você trouxer for de cereais cozida na assadeira, será da melhor farinha sem fermento amassada com azeite.

[[v3-2-6]]

^<<v3-2-6,6>>^ Você a partirá em pedaços e derramará azeite sobre ela; é oferta de cereais.

[[v3-2-7]]

^<<v3-2-7,7>>^ Se a oferta que você trouxer for de cereais preparados na frigideira, deverá ser da melhor farinha com azeite.

[[v3-2-8]]

^<<v3-2-8,8>>^ — E a oferta de cereais que será feita daquilo, você a trará ao Senhor ; será apresentada ao sacerdote, o qual a levará ao altar.

[[v3-2-9]]

^<<v3-2-9,9>>^ Da oferta de cereais o sacerdote pegará a porção memorial e a queimará sobre o altar; é oferta queimada, de aroma agradável ao Senhor .

[[v3-2-10]]

^<<v3-2-10,10>>^ O que ficar da oferta de cereais será de Arão e de seus filhos; é coisa santíssima das ofertas queimadas ao Senhor .

[[v3-2-11]]

^<<v3-2-11,11>>^ — Nenhuma oferta de cereais, que você apresentar ao Senhor , será feita com fermento; porque vocês não devem queimar nem fermento nem mel como oferta ao Senhor .

[[v3-2-12]]

^<<v3-2-12,12>>^ Vocês podem trazê-los ao Senhor  como oferta das primícias, mas não os porão sobre o altar como aroma agradável.

[[v3-2-13]]

^<<v3-2-13,13>>^ Tempere com sal todas as suas ofertas de cereais. Na sua oferta de cereais você não deixará faltar o sal da aliança do seu Deus; em todas as suas ofertas você aplicará sal.

[[v3-2-14]]

^<<v3-2-14,14>>^ — Se você trouxer ao Senhor  oferta de cereais das primícias, faça a oferta de cereais das suas primícias de espigas verdes, tostadas ao fogo, isto é, os grãos esmagados de espigas verdes.

[[v3-2-15]]

^<<v3-2-15,15>>^ Derrame azeite sobre ela e, por cima, ponha incenso; é oferta de cereais.

[[v3-2-16]]

^<<v3-2-16,16>>^ Assim, o sacerdote queimará a porção memorial dos grãos de espigas esmagados e do azeite, com todo o incenso; é oferta queimada ao Senhor .

'''

xref:003-levitico/003-levitico-001.adoc#v3-1-0[&#60; Capítulo Anterior] | <<v3-2-0,Topo>> | xref:003-levitico/003-levitico-003.adoc#v3-3-0[Próximo Capítulo &#62;]