include::./index.adoc[]

[[v3-17-0]]
=== Levítico, 17
// naa ?, NAA - Nova Almeida Atualizada

[[v3-17-1]]

^<<v3-17-1,1>>^ O Senhor  disse a Moisés:

[[v3-17-2]]

^<<v3-17-2,2>>^ — Fale a Arão, a seus filhos e aos filhos de Israel e diga-lhes: Isto é o que o Senhor  ordenou, dizendo:

[[v3-17-3]]

^<<v3-17-3,3>>^ — Qualquer homem da casa de Israel que matar um boi, um cordeiro ou uma cabra, no arraial ou fora dele,

[[v3-17-4]]

^<<v3-17-4,4>>^ e não os trouxer à porta da tenda do encontro, como oferta ao Senhor  diante do seu tabernáculo, a tal homem será atribuída a culpa do sangue; ele derramou sangue e por isso será eliminado do seu povo.

[[v3-17-5]]

^<<v3-17-5,5>>^ Isto é assim para que os filhos de Israel, trazendo os seus sacrifícios, que oferecem em campo aberto, os apresentem ao Senhor , à porta da tenda do encontro, ao sacerdote, e os ofereçam por sacrifícios pacíficos ao Senhor .

[[v3-17-6]]

^<<v3-17-6,6>>^ O sacerdote aspergirá o sangue sobre o altar do Senhor , à porta da tenda do encontro, e queimará a gordura de aroma agradável ao Senhor .

[[v3-17-7]]

^<<v3-17-7,7>>^ Nunca mais oferecerão os seus sacrifícios aos demônios, com os quais eles se prostituem; isso lhes será por estatuto perpétuo nas suas gerações.

[[v3-17-8]]

^<<v3-17-8,8>>^ — Diga-lhes também: Qualquer homem da casa de Israel ou dos estrangeiros que peregrinam entre vocês que oferecer holocausto ou sacrifício

[[v3-17-9]]

^<<v3-17-9,9>>^ e não o trouxer à porta da tenda do encontro, para oferecê-lo ao Senhor , esse homem será eliminado do seu povo.

[[v3-17-10]]

^<<v3-17-10,10>>^ — Qualquer homem da casa de Israel ou dos estrangeiros que peregrinam entre vocês que comer sangue, contra ele me voltarei e o eliminarei do seu povo.

[[v3-17-11]]

^<<v3-17-11,11>>^ Porque a vida da carne está no sangue. Eu o tenho dado a vocês sobre o altar, para fazer expiação pela vida de vocês, porque é o sangue que fará expiação pela vida.

[[v3-17-12]]

^<<v3-17-12,12>>^ Portanto, tenho dito aos filhos de Israel: nenhum de vocês comerá sangue, nem o estrangeiro que peregrina entre vocês o comerá.

[[v3-17-13]]

^<<v3-17-13,13>>^ — Qualquer homem dos filhos de Israel ou dos estrangeiros que peregrinam entre vocês que caçar animal ou ave que se pode comer derramará o sangue e o cobrirá com pó.

[[v3-17-14]]

^<<v3-17-14,14>>^ Porque a vida de toda carne é o seu sangue. Por isso, tenho dito aos filhos de Israel que não comam o sangue de nenhuma carne, porque a vida de toda carne é o seu sangue; todo o que comer será eliminado.

[[v3-17-15]]

^<<v3-17-15,15>>^ — Qualquer pessoa, natural da terra ou estrangeira, que comer carne de um animal que morre por si ou que é dilacerado por feras lavará as suas roupas, se banhará em água e ficará impura até a tarde; depois, estará pura.

[[v3-17-16]]

^<<v3-17-16,16>>^ Mas, se não lavar a roupa, nem banhar o corpo, levará sobre si a sua iniquidade.

'''

xref:003-levitico/003-levitico-016.adoc#v3-16-0[&#60; Capítulo Anterior] | <<v3-17-0,Topo>> | xref:003-levitico/003-levitico-018.adoc#v3-18-0[Próximo Capítulo &#62;]