include::./index.adoc[]

[[v3-21-0]]
=== Levítico, 21
// naa ?, NAA - Nova Almeida Atualizada

[[v3-21-1]]

^<<v3-21-1,1>>^ O Senhor  disse a Moisés: — Fale aos sacerdotes, os filhos de Arão, e diga-lhes: O sacerdote não se contaminará por causa de um morto entre o seu povo,

[[v3-21-2]]

^<<v3-21-2,2>>^ a não ser que se trate de um parente mais chegado: a mãe, o pai, um filho, uma filha, um irmão.

[[v3-21-3]]

^<<v3-21-3,3>>^ Também no caso da morte de uma irmã virgem, chegada a ele, que ainda não teve marido, pode contaminar-se.

[[v3-21-4]]

^<<v3-21-4,4>>^ Ele, sendo homem principal entre o seu povo, não se contaminará, pois ele se profanaria.

[[v3-21-5]]

^<<v3-21-5,5>>^ Os sacerdotes não farão calva na sua cabeça e não cortarão as extremidades da barba, nem farão cortes no próprio corpo.

[[v3-21-6]]

^<<v3-21-6,6>>^ Serão santos para o seu Deus e não profanarão o nome do seu Deus, porque oferecem as ofertas queimadas do Senhor , o pão de seu Deus; portanto, serão santos.

[[v3-21-7]]

^<<v3-21-7,7>>^ Não poderão casar com mulher prostituta ou desonrada, nem com mulher divorciada de seu marido, pois o sacerdote é santo para o seu Deus.

[[v3-21-8]]

^<<v3-21-8,8>>^ Portanto, você deve considerá-lo santo, porque oferece o pão do seu Deus. Ele será santo para vocês, porque eu, o Senhor  que os santifico, sou santo.

[[v3-21-9]]

^<<v3-21-9,9>>^ Se a filha de um sacerdote se desonrar, entregando-se à prostituição, profana o pai dela; será queimada.

[[v3-21-10]]

^<<v3-21-10,10>>^ — O sumo sacerdote entre seus irmãos, sobre cuja cabeça foi derramado o óleo da unção, e que for consagrado para usar as vestes sagradas, não deixará os cabelos sem pentear, nem rasgará as suas roupas.

[[v3-21-11]]

^<<v3-21-11,11>>^ Não se aproximará de cadáver algum, nem se contaminará por causa do seu pai ou da sua mãe.

[[v3-21-12]]

^<<v3-21-12,12>>^ Não sairá do santuário, nem profanará o santuário do seu Deus, pois a consagração do óleo da unção do seu Deus está sobre ele. Eu sou o Senhor .

[[v3-21-13]]

^<<v3-21-13,13>>^ Ele tomará por mulher uma virgem.

[[v3-21-14]]

^<<v3-21-14,14>>^ Não casará com viúva, divorciada, desonrada ou prostituta, mas tomará por mulher uma virgem do seu povo.

[[v3-21-15]]

^<<v3-21-15,15>>^ E não profanará a sua descendência entre o seu povo, porque eu sou o Senhor , que o santifico.

[[v3-21-16]]

^<<v3-21-16,16>>^ O Senhor  disse a Moisés:

[[v3-21-17]]

^<<v3-21-17,17>>^ — Fale a Arão, dizendo: Nenhum dos seus descendentes, nas suas gerações, em quem houver algum defeito se aproximará para oferecer o pão do seu Deus.

[[v3-21-18]]

^<<v3-21-18,18>>^ Pois nenhum homem em quem houver defeito se aproximará: seja um homem cego, coxo, de rosto mutilado ou desproporcionado,

[[v3-21-19]]

^<<v3-21-19,19>>^ homem que tiver o pé quebrado ou mão quebrada,

[[v3-21-20]]

^<<v3-21-20,20>>^ que for corcunda, anão, que tiver defeito nos olhos, sarna, feridas na pele, ou que tiver testículo esmagado.

[[v3-21-21]]

^<<v3-21-21,21>>^ Nenhum homem da descendência de Arão, o sacerdote, em quem houver algum defeito se aproximará para oferecer as ofertas queimadas do Senhor ; ele tem defeito; não se aproximará para oferecer o pão do seu Deus.

[[v3-21-22]]

^<<v3-21-22,22>>^ Poderá comer o pão do seu Deus, tanto do santíssimo como do santo.

[[v3-21-23]]

^<<v3-21-23,23>>^ Porém não poderá entrar até o véu, nem se aproximará do altar, porque tem defeito, para que não profane os meus santuários, porque eu sou o Senhor , que os santifico.

[[v3-21-24]]

^<<v3-21-24,24>>^ Foi isso que Moisés disse a Arão, aos filhos deste e a todos os filhos de Israel.

'''

xref:003-levitico/003-levitico-020.adoc#v3-20-0[&#60; Capítulo Anterior] | <<v3-21-0,Topo>> | xref:003-levitico/003-levitico-022.adoc#v3-22-0[Próximo Capítulo &#62;]