include::./index.adoc[]

[[v3-20-0]]
=== Levítico, 20
// naa ?, NAA - Nova Almeida Atualizada

[[v3-20-1]]

^<<v3-20-1,1>>^ O Senhor  disse a Moisés:

[[v3-20-2]]

^<<v3-20-2,2>>^ — Diga também aos filhos de Israel: Qualquer dos filhos de Israel, ou dos estrangeiros que peregrinam em Israel, que entregar um de seus filhos a Moloque será morto; o povo da terra o apedrejará.

[[v3-20-3]]

^<<v3-20-3,3>>^ Voltarei o meu rosto contra esse homem e o eliminarei do meio do seu povo, porque entregou um de seus filhos a Moloque, contaminando, assim, o meu santuário e profanando o meu santo nome.

[[v3-20-4]]

^<<v3-20-4,4>>^ Se o povo da terra fechar os olhos para o que esse homem fez, ao entregar um de seus filhos a Moloque, e não o matar,

[[v3-20-5]]

^<<v3-20-5,5>>^ então eu voltarei o meu rosto contra esse homem e contra a sua família e o eliminarei do meio do seu povo, com todos os que o seguem e se prostituem com Moloque.

[[v3-20-6]]

^<<v3-20-6,6>>^ — Quando alguém se virar para os necromantes e feiticeiros, para se prostituir com eles, eu voltarei o meu rosto contra ele e o eliminarei do meio do seu povo.

[[v3-20-7]]

^<<v3-20-7,7>>^ Portanto, santifiquem-se e sejam santos, pois eu sou o Senhor , o Deus de vocês.

[[v3-20-8]]

^<<v3-20-8,8>>^ Guardem os meus estatutos e tratem de cumpri-los. Eu sou o Senhor , que os santifico.

[[v3-20-9]]

^<<v3-20-9,9>>^ — Se um homem amaldiçoar o seu pai ou a sua mãe, será morto. Amaldiçoou o seu pai ou a sua mãe; é responsável pela própria morte.

[[v3-20-10]]

^<<v3-20-10,10>>^ — Se um homem adulterar com a mulher do seu próximo, será morto o adúltero e a adúltera.

[[v3-20-11]]

^<<v3-20-11,11>>^ O homem que tiver relações com a mulher de seu pai terá envergonhado o seu pai; tanto aquele homem quanto a mulher serão mortos; o seu sangue cairá sobre eles.

[[v3-20-12]]

^<<v3-20-12,12>>^ Se um homem tiver relações com a nora, ambos serão mortos; fizeram confusão; o seu sangue cairá sobre eles.

[[v3-20-13]]

^<<v3-20-13,13>>^ Se também um homem tiver relações com outro homem, como se fosse mulher, ambos praticaram coisa abominável; serão mortos; o seu sangue cairá sobre eles.

[[v3-20-14]]

^<<v3-20-14,14>>^ Se um homem tiver relações com uma mulher e com a mãe dela, isso é algo vergonhoso; queimarão tanto ele quanto elas, para que não haja maldade no meio de vocês.

[[v3-20-15]]

^<<v3-20-15,15>>^ Se também um homem tiver relações com um animal, será morto; matem também o animal.

[[v3-20-16]]

^<<v3-20-16,16>>^ Se uma mulher se aproximar de algum animal e tiver relações com ele, matem tanto a mulher como o animal; o seu sangue cairá sobre eles.

[[v3-20-17]]

^<<v3-20-17,17>>^ — Se um homem casar com a sua irmã, filha de seu pai ou filha de sua mãe, e se ele tiver relações com ela e ela tiver relações com ele, será uma indecência; portanto, serão eliminados na presença dos filhos do seu povo; ele envergonhou a sua irmã; levará sobre si a sua iniquidade.

[[v3-20-18]]

^<<v3-20-18,18>>^ Se um homem se deitar com uma mulher no período da menstruação dela e tiver relações com ela, descobrindo a sua fonte, e ela descobrir a fonte do seu sangue, ambos serão eliminados do meio do seu povo.

[[v3-20-19]]

^<<v3-20-19,19>>^ Também não tenha relações com a irmã de sua mãe ou a irmã de seu pai, porque significa ter relações com uma parenta; levarão sobre si a sua iniquidade.

[[v3-20-20]]

^<<v3-20-20,20>>^ Se um homem tiver relações com a tia, envergonhou o seu tio; levarão seu pecado sobre si; morrerão sem filhos.

[[v3-20-21]]

^<<v3-20-21,21>>^ Se um homem tomar a mulher de seu irmão, isso é impureza; envergonhou o seu irmão; ficarão sem filhos.

[[v3-20-22]]

^<<v3-20-22,22>>^ — Guardem, portanto, todos os meus estatutos e cumpram todos os meus juízos, para que a terra para a qual eu os estou levando, para nela habitar, não os vomite de lá.

[[v3-20-23]]

^<<v3-20-23,23>>^ Não andem nos costumes dos povos que eu vou expulsar de diante de vocês, porque fizeram todas estas coisas; por isso, me aborreci deles.

[[v3-20-24]]

^<<v3-20-24,24>>^ Mas a vocês eu já disse que herdarão a terra deles; eu a darei a vocês em herança, terra que mana leite e mel. Eu sou o Senhor , o Deus de vocês, que os separei dos outros povos.

[[v3-20-25]]

^<<v3-20-25,25>>^ — Portanto, façam distinção entre os animais puros e os impuros e entre as aves impuras e as puras; não se façam abomináveis por causa dos animais, ou das aves, ou de tudo o que se arrasta sobre a terra, os quais separei de vocês, para que as considerem impuras.

[[v3-20-26]]

^<<v3-20-26,26>>^ Sejam santos para mim, porque eu, o Senhor , sou santo e os separei dos outros povos, para que sejam meus.

[[v3-20-27]]

^<<v3-20-27,27>>^ — O homem ou a mulher que for necromante ou feiticeiro será morto; será apedrejado; o seu sangue cairá sobre ele.

'''

xref:003-levitico/003-levitico-019.adoc#v3-19-0[&#60; Capítulo Anterior] | <<v3-20-0,Topo>> | xref:003-levitico/003-levitico-021.adoc#v3-21-0[Próximo Capítulo &#62;]