include::./index.adoc[]

[[v3-13-0]]
=== Levítico, 13
// naa ?, NAA - Nova Almeida Atualizada

[[v3-13-1]]

^<<v3-13-1,1>>^ O Senhor  disse a Moisés e a Arão:

[[v3-13-2]]

^<<v3-13-2,2>>^ — Quando uma pessoa tiver na sua pele inchação, pústula ou mancha lustrosa, e isto se tornar na sua pele como praga de lepra, essa pessoa será levada a Arão, o sacerdote, ou a um de seus filhos, sacerdotes.

[[v3-13-3]]

^<<v3-13-3,3>>^ O sacerdote examinará a praga na pele, e, se os pelos na praga se tornaram brancos e a praga parecer mais profunda do que a pele da sua carne, é praga de lepra; o sacerdote examinará a pessoa e a declarará impura.

[[v3-13-4]]

^<<v3-13-4,4>>^ Se a mancha lustrosa na pele for branca e não parecer mais profunda do que a pele, e os pelos não se tornaram brancos, então o sacerdote encerrará por sete dias a pessoa que tem a praga.

[[v3-13-5]]

^<<v3-13-5,5>>^ No sétimo dia, o sacerdote a examinará. Se, na opinião dele, a praga tiver parado e não se espalhou na pele daquela pessoa, então o sacerdote a encerrará por mais sete dias.

[[v3-13-6]]

^<<v3-13-6,6>>^ No sétimo dia, o sacerdote a examinará outra vez. Se a lepra se tornou pálida e não se espalhou na pele, então o sacerdote a declarará pura; é apenas uma pústula. A pessoa lavará as suas roupas e estará pura.

[[v3-13-7]]

^<<v3-13-7,7>>^ Mas, se a pústula se espalha muito na pele, depois que a pessoa se mostrou ao sacerdote para a sua purificação, terá de se mostrar outra vez ao sacerdote.

[[v3-13-8]]

^<<v3-13-8,8>>^ Este a examinará, e se a pústula tiver se alastrado pela pele, o sacerdote declarará que a pessoa está impura; é lepra.

[[v3-13-9]]

^<<v3-13-9,9>>^ — Quando uma pessoa tiver praga de lepra, será levada ao sacerdote.

[[v3-13-10]]

^<<v3-13-10,10>>^ Este a examinará, e, se houver inchação branca na pele, a qual tornou brancos os pelos, e houver carne viva na inchação,

[[v3-13-11]]

^<<v3-13-11,11>>^ é lepra crônica na pele; portanto, o sacerdote declarará que a pessoa está impura; não encerrará essa pessoa, porque está impura.

[[v3-13-12]]

^<<v3-13-12,12>>^ Se a lepra se espalhar de todo na pele e cobrir a pele da pessoa que tem a lepra, desde a cabeça até os pés, quanto podem ver os olhos do sacerdote,

[[v3-13-13]]

^<<v3-13-13,13>>^ então este a examinará. Se a lepra cobriu toda a carne, o sacerdote declarará que a pessoa que tem a mancha está pura; a lepra tornou-se branca; a pessoa está pura.

[[v3-13-14]]

^<<v3-13-14,14>>^ Mas, no dia em que aparecer nela carne viva, será impura.

[[v3-13-15]]

^<<v3-13-15,15>>^ Ao ver a carne viva, o sacerdote declarará que a pessoa está impura; a carne viva é impura; é lepra.

[[v3-13-16]]

^<<v3-13-16,16>>^ Se a carne viva mudar e ficar de novo branca, então a pessoa virá ao sacerdote,

[[v3-13-17]]

^<<v3-13-17,17>>^ e este a examinará. Se a lepra se tornou branca, então o sacerdote declarará que a pessoa que tem a praga está pura.

[[v3-13-18]]

^<<v3-13-18,18>>^ — Quando sarar a carne em cuja pele houver uma úlcera,

[[v3-13-19]]

^<<v3-13-19,19>>^ e no lugar da úlcera aparecer uma inchação branca ou mancha lustrosa, de um branco que puxa para o vermelho, a pessoa terá de se mostrar ao sacerdote.

[[v3-13-20]]

^<<v3-13-20,20>>^ O sacerdote examinará a inchação, e, se ela parece mais profunda do que a pele, e os seus pelos se tornaram brancos, o sacerdote declarará que a pessoa está impura; é praga de lepra, que brotou da úlcera.

[[v3-13-21]]

^<<v3-13-21,21>>^ Porém, se o sacerdote a examinar, e nela não houver pelos brancos, e ela não estiver mais profunda do que a pele, porém pálida, então o sacerdote encerrará essa pessoa por sete dias.

[[v3-13-22]]

^<<v3-13-22,22>>^ Se a inchação se espalhar na pele, o sacerdote declarará que a pessoa está impura; é lepra.

[[v3-13-23]]

^<<v3-13-23,23>>^ Mas, se a mancha lustrosa parar no seu lugar, não se espalhando, é cicatriz da úlcera; o sacerdote, pois, declarará que a pessoa está pura.

[[v3-13-24]]

^<<v3-13-24,24>>^ — Quando, na pele, houver queimadura de fogo, e a carne viva da queimadura se tornar em mancha lustrosa, de um branco que puxa para o vermelho ou para o branco,

[[v3-13-25]]

^<<v3-13-25,25>>^ o sacerdote a examinará. Se os pelos da mancha lustrosa se tornaram brancos, e ela parece mais profunda do que a pele, é lepra que brotou na queimadura. O sacerdote declarará que a pessoa está impura; é a praga de lepra.

[[v3-13-26]]

^<<v3-13-26,26>>^ Porém, se o sacerdote a examinar, e não houver pelos brancos na mancha lustrosa, e ela não estiver mais profunda do que a pele, mas for de cor pálida, o sacerdote encerrará a pessoa por sete dias.

[[v3-13-27]]

^<<v3-13-27,27>>^ Depois, no sétimo dia, o sacerdote a examinará, e, se a mancha tiver se alastrado pela pele, o sacerdote declarará que a pessoa está impura; é praga de lepra.

[[v3-13-28]]

^<<v3-13-28,28>>^ Mas, se a mancha lustrosa parar no seu lugar e não se espalhar na pele, mas se tornou pálida, é inchação da queimadura; portanto, o sacerdote declarará que a pessoa está pura, porque é cicatriz da queimadura.

[[v3-13-29]]

^<<v3-13-29,29>>^ — Quando um homem ou uma mulher tiver praga na cabeça ou no queixo,

[[v3-13-30]]

^<<v3-13-30,30>>^ o sacerdote examinará a praga. Se ela parece mais profunda do que a pele, e se nela houver pelos finos amarelados, o sacerdote declarará que a pessoa está impura; é micose, é lepra da cabeça ou do queixo.

[[v3-13-31]]

^<<v3-13-31,31>>^ Mas, se o sacerdote, havendo examinado a praga da micose, achar que ela não parece mais profunda do que a pele, e, se nela não houver pelos pretos, então o sacerdote encerrará a pessoa que tem a praga da micose por sete dias.

[[v3-13-32]]

^<<v3-13-32,32>>^ No sétimo dia, o sacerdote examinará a praga; se a micose não tiver se espalhado, e nela não houver pelos amarelos, e a micose não parecer mais profunda do que a pele,

[[v3-13-33]]

^<<v3-13-33,33>>^ então a pessoa será rapada; mas não se rapará a micose. O sacerdote, por mais sete dias, encerrará a pessoa que tem a micose.

[[v3-13-34]]

^<<v3-13-34,34>>^ No sétimo dia, o sacerdote examinará a micose; se ela não tiver se alastrado pela pele e não parecer mais profunda do que a pele, o sacerdote declarará pura essa pessoa; ela lavará as suas roupas e estará pura.

[[v3-13-35]]

^<<v3-13-35,35>>^ Mas, se a micose, depois da sua purificação, tiver se espalhado muito na pele,

[[v3-13-36]]

^<<v3-13-36,36>>^ então o sacerdote a examinará; se a micose tiver se espalhado na pele, o sacerdote não precisa procurar pelos amarelados; está impura.

[[v3-13-37]]

^<<v3-13-37,37>>^ Mas, se, na opinião do sacerdote, a micose parou, e pelos pretos cresceram nela, a micose está sarada; a pessoa está pura, e o sacerdote declarará que ela está pura.

[[v3-13-38]]

^<<v3-13-38,38>>^ — E, quando um homem ou uma mulher tiver manchas lustrosas na pele,

[[v3-13-39]]

^<<v3-13-39,39>>^ então o sacerdote examinará a pessoa. Se na pele aparecerem manchas pálidas, brancas, é uma pequena ferida branca que brotou na pele; a pessoa está pura.

[[v3-13-40]]

^<<v3-13-40,40>>^ — Quando os cabelos do homem lhe caírem da cabeça, é calva; contudo, está puro.

[[v3-13-41]]

^<<v3-13-41,41>>^ Se lhe caírem na frente da cabeça, é antecalva; contudo, está puro.

[[v3-13-42]]

^<<v3-13-42,42>>^ Porém, se, na calva ou na antecalva, houver praga branca, que puxa para o vermelho, é lepra, brotando na calva ou na antecalva.

[[v3-13-43]]

^<<v3-13-43,43>>^ O sacerdote examinará o homem, e, se a inchação da praga, na sua calva ou antecalva, está branca, puxando para o vermelho, como parece a lepra na pele,

[[v3-13-44]]

^<<v3-13-44,44>>^ aquele homem é leproso, está impuro; o sacerdote declarará que ele está impuro; a sua praga está na cabeça.

[[v3-13-45]]

^<<v3-13-45,45>>^ — As roupas do leproso, em quem está a praga, serão rasgadas, e os seus cabelos deixados sem pentear; com a mão sobre a boca, gritará: Impuro! Impuro!

[[v3-13-46]]

^<<v3-13-46,46>>^ Será impuro durante os dias em que a praga estiver nele; está impuro, habitará só; a sua habitação será fora do arraial.

[[v3-13-47]]

^<<v3-13-47,47>>^ — Quando também em alguma roupa houver praga de mofo, roupa de lã ou de linho,

[[v3-13-48]]

^<<v3-13-48,48>>^ seja na urdidura, seja na trama, de linho ou de lã, em couro ou em qualquer objeto feito de couro,

[[v3-13-49]]

^<<v3-13-49,49>>^ se a praga for esverdeada ou avermelhada na roupa, na pele, na urdidura ou na trama, em qualquer coisa feita de couro, é a praga de mofo, e deverá ser mostrada ao sacerdote.

[[v3-13-50]]

^<<v3-13-50,50>>^ O sacerdote examinará a praga e encerrará, por sete dias, aquilo que tem a praga.

[[v3-13-51]]

^<<v3-13-51,51>>^ Então, no sétimo dia, examinará a praga; se ela tiver se alastrado pela roupa, na urdidura ou na trama, seja no couro, seja qual for a obra em que se empregue, é mofo que se espalha; isso é impuro.

[[v3-13-52]]

^<<v3-13-52,52>>^ Ele queimará aquela roupa, seja a urdidura, seja a trama, de lã, de linho ou qualquer coisa feita de couro, em que se acha a praga, pois é mofo que se espalha; tudo deverá ser queimado.

[[v3-13-53]]

^<<v3-13-53,53>>^ — Mas, se o sacerdote examinar e a praga não tiver se espalhado na roupa, nem na urdidura, nem na trama, nem em qualquer coisa feita de couro,

[[v3-13-54]]

^<<v3-13-54,54>>^ então o sacerdote ordenará que se lave aquilo em que havia a praga e o encerrará por mais sete dias.

[[v3-13-55]]

^<<v3-13-55,55>>^ O sacerdote, examinando a coisa em que havia praga, depois de lavada aquela, se a praga não mudou a sua cor, nem se espalhou, está impura; terá de ser queimada com fogo; é mofo que se espalha, seja no avesso ou no direito.

[[v3-13-56]]

^<<v3-13-56,56>>^ Mas, se o sacerdote examinar a mancha, e esta se tornou pálida depois de lavada, então rasgará aquela parte da roupa, do couro, da urdidura ou da trama.

[[v3-13-57]]

^<<v3-13-57,57>>^ Se a praga ainda aparecer na roupa, quer na urdidura, quer na trama, ou em qualquer coisa feita de couro, é mofo que se espalha; com fogo terá de ser queimado aquilo em que está a praga.

[[v3-13-58]]

^<<v3-13-58,58>>^ Mas a roupa, quer na urdidura, quer na trama, ou qualquer coisa feita de couro, que você lavar e de que a praga desaparecer, deve ser lavada mais uma vez e estará pura.

[[v3-13-59]]

^<<v3-13-59,59>>^ Esta é a lei a respeito da praga do mofo da roupa de lã ou de linho, quer na urdidura, quer na trama; ou de qualquer coisa feita de couro, para se poder declará-las puras ou impuras.

'''

xref:003-levitico/003-levitico-012.adoc#v3-12-0[&#60; Capítulo Anterior] | <<v3-13-0,Topo>> | xref:003-levitico/003-levitico-014.adoc#v3-14-0[Próximo Capítulo &#62;]