include::./index.adoc[]

[[v3-24-0]]
=== Levítico, 24
// naa ?, NAA - Nova Almeida Atualizada

[[v3-24-1]]

^<<v3-24-1,1>>^ O Senhor  disse a Moisés:

[[v3-24-2]]

^<<v3-24-2,2>>^ — Ordene aos filhos de Israel que lhe tragam azeite puro de oliveira, azeite batido, para o candelabro, para que haja lâmpada acesa continuamente.

[[v3-24-3]]

^<<v3-24-3,3>>^ Na tenda do encontro fora do véu, que está diante da arca do testemunho, Arão a conservará em ordem, desde a tarde até pela manhã, continuamente, diante do Senhor ; este será estatuto perpétuo de geração em geração.

[[v3-24-4]]

^<<v3-24-4,4>>^ Sobre o candeeiro de ouro puro conservará em ordem as lâmpadas diante do Senhor , continuamente.

[[v3-24-5]]

^<<v3-24-5,5>>^ — Pegue também da melhor farinha e dela faça doze pães, cada um deles com dois quilos.

[[v3-24-6]]

^<<v3-24-6,6>>^ E coloque-os em duas fileiras, seis em cada fileira, sobre a mesa de ouro puro, diante do Senhor .

[[v3-24-7]]

^<<v3-24-7,7>>^ Sobre cada fileira coloque incenso puro, que será, para o pão, como porção memorial; é oferta queimada ao Senhor .

[[v3-24-8]]

^<<v3-24-8,8>>^ Em cada sábado, Arão os porá em ordem diante do Senhor , continuamente, da parte dos filhos de Israel, por aliança perpétua.

[[v3-24-9]]

^<<v3-24-9,9>>^ Esses pães serão de Arão e de seus filhos, os quais os comerão num lugar santo, porque são coisa santíssima para eles, das ofertas queimadas ao Senhor , como estatuto perpétuo.

[[v3-24-10]]

^<<v3-24-10,10>>^ Havia entre os filhos de Israel o filho de uma israelita, cujo pai era um egípcio. O filho dessa israelita e certo homem israelita brigaram no arraial.

[[v3-24-11]]

^<<v3-24-11,11>>^ Então o filho da mulher israelita blasfemou contra o nome do Senhor  e o amaldiçoou; por isso o levaram a Moisés. O nome da mãe dele era Selomite, filha de Dibri, da tribo de Dã.

[[v3-24-12]]

^<<v3-24-12,12>>^ E o levaram à prisão, até que o Senhor  lhes declarasse o que deviam fazer.

[[v3-24-13]]

^<<v3-24-13,13>>^ O Senhor  disse a Moisés:

[[v3-24-14]]

^<<v3-24-14,14>>^ — Leve o homem que blasfemou para fora do arraial. E todos os que o ouviram porão as mãos sobre a cabeça dele, e toda a congregação o apedrejará.

[[v3-24-15]]

^<<v3-24-15,15>>^ Você dirá aos filhos de Israel: Quem amaldiçoar o seu Deus levará sobre si o seu pecado.

[[v3-24-16]]

^<<v3-24-16,16>>^ Aquele que blasfemar contra o nome do Senhor  será morto; toda a congregação o apedrejará. Tanto o estrangeiro como o natural da terra, blasfemando contra o nome do Senhor , será morto.

[[v3-24-17]]

^<<v3-24-17,17>>^ — Quem matar alguém será morto.

[[v3-24-18]]

^<<v3-24-18,18>>^ Mas quem matar um animal deve restituí-lo: igual por igual.

[[v3-24-19]]

^<<v3-24-19,19>>^ Se alguém desfigurar o seu próximo, como ele fez, assim lhe será feito:

[[v3-24-20]]

^<<v3-24-20,20>>^ fratura por fratura, olho por olho, dente por dente; como ele tiver desfigurado a algum homem, assim se fará com ele.

[[v3-24-21]]

^<<v3-24-21,21>>^ Quem matar um animal restituirá outro; quem matar um homem será morto.

[[v3-24-22]]

^<<v3-24-22,22>>^ Vocês terão uma e a mesma lei para o estrangeiro e para o natural da terra; pois eu sou o Senhor , o Deus de vocês.

[[v3-24-23]]

^<<v3-24-23,23>>^ Então Moisés disse aos filhos de Israel que levassem o que tinha blasfemado para fora do arraial e o apedrejassem; e os filhos de Israel fizeram como o Senhor  havia ordenado a Moisés.

'''

xref:003-levitico/003-levitico-023.adoc#v3-23-0[&#60; Capítulo Anterior] | <<v3-24-0,Topo>> | xref:003-levitico/003-levitico-025.adoc#v3-25-0[Próximo Capítulo &#62;]