include::./index.adoc[]

[[v3-25-0]]
=== Levítico, 25
// naa ?, NAA - Nova Almeida Atualizada

[[v3-25-1]]

^<<v3-25-1,1>>^ O Senhor  disse a Moisés, no monte Sinai:

[[v3-25-2]]

^<<v3-25-2,2>>^ — Fale aos filhos de Israel e diga-lhes: Quando entrarem na terra que eu lhes dou, a própria terra guardará um sábado dedicado ao Senhor .

[[v3-25-3]]

^<<v3-25-3,3>>^ Durante seis anos vocês semearão os seus campos, e durante seis anos vocês podarão as suas vinhas e colherão os frutos delas.

[[v3-25-4]]

^<<v3-25-4,4>>^ Porém, no sétimo ano, haverá um sábado de descanso solene para a terra, um sábado dedicado ao Senhor ; não semeiem os seus campos, nem façam a poda de suas vinhas.

[[v3-25-5]]

^<<v3-25-5,5>>^ Não façam a colheita do que nascer por si mesmo nos seus campos, nem colham as uvas de suas vinhas que não foram podadas; será um ano de descanso solene para a terra.

[[v3-25-6]]

^<<v3-25-6,6>>^ Mas vocês poderão comer os frutos da terra em descanso — vocês, os seus escravos, as suas escravas, os seus trabalhadores diaristas e os estrangeiros que moram com vocês.

[[v3-25-7]]

^<<v3-25-7,7>>^ Também o seu gado e os animais que estão na sua terra comerão tudo o que a terra produzir.

[[v3-25-8]]

^<<v3-25-8,8>>^ — Conte sete semanas de anos, isto é, sete vezes sete anos, de maneira que os dias das sete semanas de anos somem quarenta e nove anos.

[[v3-25-9]]

^<<v3-25-9,9>>^ Então, no sétimo mês, aos dez dias do mês, você fará soar a trombeta; no Dia da Expiação, vocês farão soar a trombeta por toda a terra de vocês.

[[v3-25-10]]

^<<v3-25-10,10>>^ Santifiquem o quinquagésimo ano e proclamem liberdade na terra a todos os seus moradores. Esse será um ano de jubileu para vocês, e cada um de vocês voltará à sua propriedade, cada um de vocês voltará à sua família.

[[v3-25-11]]

^<<v3-25-11,11>>^ O quinquagésimo ano será jubileu para vocês; não semeiem o campo, não colham o que nascer por si mesmo, nem colham as uvas das vinhas não podadas.

[[v3-25-12]]

^<<v3-25-12,12>>^ Porque é jubileu, será santo para vocês; o produto do campo vocês podem comer.

[[v3-25-13]]

^<<v3-25-13,13>>^ — Neste Ano do Jubileu, cada um de vocês voltará à sua propriedade.

[[v3-25-14]]

^<<v3-25-14,14>>^ — Quando você vender algo ao seu próximo ou comprar alguma coisa dele, não explore o seu irmão.

[[v3-25-15]]

^<<v3-25-15,15>>^ Você comprará do seu próximo com base no número dos anos desde o último Jubileu; e, segundo o número dos anos das colheitas até o próximo Jubileu, ele venderá a você.

[[v3-25-16]]

^<<v3-25-16,16>>^ Sendo muitos os anos, você aumentará o preço e, sendo poucos, você abaixará o preço; porque ele está vendendo a você o número das colheitas.

[[v3-25-17]]

^<<v3-25-17,17>>^ Que ninguém explore o seu próximo; cada um, porém, tema o seu Deus; porque eu sou o Senhor , o Deus de vocês.

[[v3-25-18]]

^<<v3-25-18,18>>^ — Observem os meus estatutos e cumpram os meus juízos; assim, vocês habitarão seguros na terra.

[[v3-25-19]]

^<<v3-25-19,19>>^ A terra dará o seu fruto, e vocês terão comida à vontade e nela habitarão em segurança.

[[v3-25-20]]

^<<v3-25-20,20>>^ Se vocês perguntarem: "Que comeremos no sétimo ano, se não podemos semear nem fazer a colheita?",

[[v3-25-21]]

^<<v3-25-21,21>>^ saibam que eu lhes darei a minha bênção no sexto ano, para que a terra produza o suficiente para três anos.

[[v3-25-22]]

^<<v3-25-22,22>>^ No oitavo ano, vocês semearão e comerão da colheita anterior até o nono ano; até que venha a colheita do nono ano, vocês comerão da antiga.

[[v3-25-23]]

^<<v3-25-23,23>>^ Também a terra não será vendida em definitivo, porque a terra é minha; pois vocês são para mim estrangeiros e peregrinos.

[[v3-25-24]]

^<<v3-25-24,24>>^ Portanto, em todas as terras da propriedade de vocês, permitam que as terras sejam resgatadas.

[[v3-25-25]]

^<<v3-25-25,25>>^ — Se alguém do seu povo empobrecer e vender alguma parte das suas propriedades, então virá o seu resgatador, seu parente, e resgatará o que esse seu irmão vendeu.

[[v3-25-26]]

^<<v3-25-26,26>>^ Se alguém não tiver resgatador, porém vier a tornar-se próspero e achar o bastante com que a remir,

[[v3-25-27]]

^<<v3-25-27,27>>^ então contará os anos desde a sua venda, e o que ficar restituirá ao homem a quem vendeu; e assim poderá voltar à sua propriedade.

[[v3-25-28]]

^<<v3-25-28,28>>^ Mas, se as suas posses não lhe permitirem reavê-la, então a propriedade que for vendida ficará na mão do comprador até o Ano do Jubileu; porém, no Ano do Jubileu, sairá do poder deste, e aquele poderá voltar para a sua propriedade.

[[v3-25-29]]

^<<v3-25-29,29>>^ — Se alguém vender uma casa de moradia em cidade murada, poderá resgatá-la antes que se complete um ano a contar de sua venda; durante um ano, será lícito o seu resgate.

[[v3-25-30]]

^<<v3-25-30,30>>^ Se, depois de passado um ano, não for resgatada, então a casa que estiver na cidade que tem muralhas pertencerá em definitivo ao que a comprou, de geração em geração; não sairá do poder dele no Jubileu.

[[v3-25-31]]

^<<v3-25-31,31>>^ Mas as casas das aldeias que não têm muralhas ao redor serão estimadas como os campos da terra; para elas haverá resgate, e sairão do poder do comprador no Jubileu.

[[v3-25-32]]

^<<v3-25-32,32>>^ Mas, com respeito às cidades dos levitas, às casas das cidades da sua propriedade, os levitas terão direito perpétuo de resgate.

[[v3-25-33]]

^<<v3-25-33,33>>^ Se o levita não resgatar a casa que vendeu, então a casa comprada na cidade da sua propriedade sairá do poder do comprador, no Jubileu; porque as casas das cidades dos levitas são a sua propriedade no meio dos filhos de Israel.

[[v3-25-34]]

^<<v3-25-34,34>>^ Mas o campo em volta das suas cidades não será vendido, porque pertence a eles para sempre.

[[v3-25-35]]

^<<v3-25-35,35>>^ — Se alguém do seu povo se tornar pobre e as suas mãos se enfraquecerem, então você tem o dever de sustentá-lo; ele viverá com você como estrangeiro e peregrino.

[[v3-25-36]]

^<<v3-25-36,36>>^ Não cobre dele juros nem ganho, mas tema o seu Deus, para que esse seu irmão possa viver perto de você.

[[v3-25-37]]

^<<v3-25-37,37>>^ Não cobre juros sobre o dinheiro que emprestar a ele, nem dê mantimento a ele esperando obter lucro.

[[v3-25-38]]

^<<v3-25-38,38>>^ Eu sou o Senhor , o Deus de vocês, que os tirei da terra do Egito, para dar a vocês a terra de Canaã e para ser o seu Deus.

[[v3-25-39]]

^<<v3-25-39,39>>^ — Também se alguém do seu povo se tornar pobre, estando ele com você, e vender-se a você, não o faça servir como escravo.

[[v3-25-40]]

^<<v3-25-40,40>>^ Trate-o como um trabalhador diarista ou estrangeiro que mora com você. Até o Ano do Jubileu ele trabalhará para você;

[[v3-25-41]]

^<<v3-25-41,41>>^ então ficará livre de você, ele e os filhos dele, e voltará à sua família e à propriedade de seus pais.

[[v3-25-42]]

^<<v3-25-42,42>>^ Porque eles são meus servos, que tirei da terra do Egito; não serão vendidos como escravos.

[[v3-25-43]]

^<<v3-25-43,43>>^ Não domine sobre eles com tirania, mas tema o seu Deus.

[[v3-25-44]]

^<<v3-25-44,44>>^ — Quanto aos escravos ou escravas que vocês tiverem, virão das nações que estão ao redor de vocês; delas vocês comprarão escravos e escravas.

[[v3-25-45]]

^<<v3-25-45,45>>^ Também poderão comprá-los dos filhos dos estrangeiros que peregrinam entre vocês, deles e das famílias deles que estiverem com vocês, que nasceram na terra de vocês; e eles se tornarão propriedade de vocês.

[[v3-25-46]]

^<<v3-25-46,46>>^ Vocês poderão deixá-los como herança para os seus filhos depois de vocês, para que sejam propriedade deles. Vocês poderão fazer com que esses sirvam perpetuamente, mas sobre os seus irmãos, os filhos de Israel, vocês não devem dominar com tirania uns sobre os outros.

[[v3-25-47]]

^<<v3-25-47,47>>^ — Se um estrangeiro ou peregrino que mora no meio do povo enriquecer, e se alguém do seu povo tornar-se pobre e vender-se como escravo a esse estrangeiro ou peregrino que mora no meio do povo, ou a alguém da família desse estrangeiro,

[[v3-25-48]]

^<<v3-25-48,48>>^ depois de haver-se vendido, haverá ainda possibilidade de resgate para ele. Um de seus parentes poderá resgatá-lo:

[[v3-25-49]]

^<<v3-25-49,49>>^ seu tio ou primo poderá resgatá-lo; um outro parente da sua família também poderá resgatá-lo; ou, se tiver condições, poderá resgatar a si mesmo.

[[v3-25-50]]

^<<v3-25-50,50>>^ Com aquele que o comprou acertará contas desde o ano em que se vendeu a ele até o Ano do Jubileu; o preço da sua venda será segundo o número dos anos, conforme se paga a um trabalhador diarista.

[[v3-25-51]]

^<<v3-25-51,51>>^ Se ainda faltarem muitos anos, devolverá proporcionalmente a eles, do dinheiro pelo qual foi comprado, o preço do seu resgate.

[[v3-25-52]]

^<<v3-25-52,52>>^ Se restarem poucos anos até o Ano do Jubileu, então fará contas com ele e pagará, em proporção aos anos restantes, o preço do seu resgate.

[[v3-25-53]]

^<<v3-25-53,53>>^ Como trabalhador diarista, de ano em ano, estará com aquele que o comprou; não permita que o comprador domine sobre ele com tirania.

[[v3-25-54]]

^<<v3-25-54,54>>^ Se não for resgatado por nenhum desses meios, sairá no Ano do Jubileu, ele e seus filhos com ele.

[[v3-25-55]]

^<<v3-25-55,55>>^ Porque é a mim que os filhos de Israel servem. Eles são meus servos, que tirei da terra do Egito. Eu sou o Senhor , o Deus de vocês.

'''

xref:003-levitico/003-levitico-024.adoc#v3-24-0[&#60; Capítulo Anterior] | <<v3-25-0,Topo>> | xref:003-levitico/003-levitico-026.adoc#v3-26-0[Próximo Capítulo &#62;]