include::./index.adoc[]

[[v3-6-0]]
=== Levítico, 6
// naa ?, NAA - Nova Almeida Atualizada

[[v3-6-1]]

^<<v3-6-1,1>>^ O Senhor  falou a Moisés, dizendo:

[[v3-6-2]]

^<<v3-6-2,2>>^ — Se uma pessoa pecar e cometer ofensa contra o Senhor , negando ao seu próximo o que este lhe deu em depósito, ou como penhor; ou se roubar, ou tiver usado de extorsão para com o seu próximo;

[[v3-6-3]]

^<<v3-6-3,3>>^ ou se, tendo achado um objeto perdido, negar com falso juramento que o achou, ou fizer alguma outra coisa de todas em que se costuma pecar,

[[v3-6-4]]

^<<v3-6-4,4>>^ será, pois, que, tendo pecado e ficado culpada, essa pessoa restituirá aquilo que roubou, ou que extorquiu, ou o depósito que lhe foi dado, ou o perdido que achou,

[[v3-6-5]]

^<<v3-6-5,5>>^ ou tudo aquilo sobre que jurou falsamente. Restituirá por inteiro e a isso ainda acrescentará a quinta parte. Entregará isso àquele a quem pertence no dia em que trouxer a oferta pela culpa.

[[v3-6-6]]

^<<v3-6-6,6>>^ E, por sua oferta pela culpa, trará, do rebanho, ao Senhor  um carneiro sem defeito, devidamente avaliado, para a oferta pela culpa; trará o carneiro ao sacerdote.

[[v3-6-7]]

^<<v3-6-7,7>>^ E o sacerdote fará expiação por essa pessoa diante do Senhor , e ela será perdoada de qualquer dessas coisas que fez e que a tornou culpada.

[[v3-6-8]]

^<<v3-6-8,8>>^ O Senhor  disse a Moisés:

[[v3-6-9]]

^<<v3-6-9,9>>^ — Ordene a Arão e a seus filhos, dizendo: Esta é a lei a respeito do holocausto: o holocausto ficará sobre as brasas do altar toda a noite até pela manhã, e o fogo do altar nunca poderá ser apagado.

[[v3-6-10]]

^<<v3-6-10,10>>^ O sacerdote vestirá a sua túnica de linho e os calções de linho sobre a pele nua, e levantará a cinza, quando o fogo houver consumido o holocausto sobre o altar, e a colocará ao lado do altar.

[[v3-6-11]]

^<<v3-6-11,11>>^ Depois, despirá as suas vestes e porá outras roupas; e levará a cinza para fora do arraial a um lugar puro.

[[v3-6-12]]

^<<v3-6-12,12>>^ — O fogo sempre ficará aceso sobre o altar; não deve ser apagado. O sacerdote acenderá lenha no altar cada manhã, e sobre ele porá em ordem o holocausto, e sobre ele queimará a gordura das ofertas pacíficas.

[[v3-6-13]]

^<<v3-6-13,13>>^ O fogo queimará continuamente sobre o altar; não deve ser apagado.

[[v3-6-14]]

^<<v3-6-14,14>>^ — Esta é a lei a respeito da oferta de cereais: os filhos de Arão a oferecerão diante do Senhor , diante do altar.

[[v3-6-15]]

^<<v3-6-15,15>>^ Um dos sacerdotes pegará um punhado da melhor farinha da oferta de cereais com seu azeite e todo o incenso que está sobre a oferta de cereais e o queimará sobre o altar, como porção memorial de aroma agradável ao Senhor .

[[v3-6-16]]

^<<v3-6-16,16>>^ O restante da oferta Arão e seus filhos comerão. Deve ser comido sem fermento, em lugar santo; no pátio da tenda do encontro, o comerão.

[[v3-6-17]]

^<<v3-6-17,17>>^ Isso não poderá ser preparado com fermento; é a porção das minhas ofertas queimadas que dei aos sacerdotes; coisa santíssima é, como a oferta pelo pecado e a oferta pela culpa.

[[v3-6-18]]

^<<v3-6-18,18>>^ Todos os homens que são descendentes de Arão podem comer da oferta de cereais; estatuto perpétuo será para as gerações de vocês dentre as ofertas queimadas do Senhor ; tudo o que tocar nelas será santo.

[[v3-6-19]]

^<<v3-6-19,19>>^ O Senhor  disse a Moisés:

[[v3-6-20]]

^<<v3-6-20,20>>^ — Esta é a oferta de Arão e de seus filhos, que oferecerão ao Senhor  no dia em que aquele for ungido: dois litros da melhor farinha pela oferta contínua de cereais; metade dela será oferecida pela manhã, e a outra metade, à tarde.

[[v3-6-21]]

^<<v3-6-21,21>>^ Será feita numa assadeira, com azeite; traga-a bem amassada. Em pedaços cozidos você trará a oferta de cereais de aroma agradável ao Senhor .

[[v3-6-22]]

^<<v3-6-22,22>>^ Também o sacerdote, que entre os filhos de Arão for ungido em seu lugar, fará o mesmo; por estatuto perpétuo será de todo queimada ao Senhor .

[[v3-6-23]]

^<<v3-6-23,23>>^ Assim, toda a oferta de cereais trazida por um sacerdote será totalmente queimada; não poderá ser comida.

[[v3-6-24]]

^<<v3-6-24,24>>^ O Senhor  disse a Moisés:

[[v3-6-25]]

^<<v3-6-25,25>>^ — Fale a Arão e a seus filhos, dizendo: Esta é a lei a respeito da oferta pelo pecado: o animal que é oferta pelo pecado será morto no lugar onde são mortos os animais oferecidos em holocausto, diante do Senhor ; coisa santíssima é.

[[v3-6-26]]

^<<v3-6-26,26>>^ O sacerdote que a oferecer pelo pecado a comerá; no lugar santo se comerá, no pátio da tenda do encontro.

[[v3-6-27]]

^<<v3-6-27,27>>^ Tudo o que tocar a carne da oferta será santo; se alguém aspergir desse sangue sobre a sua roupa, você terá de lavar aquilo sobre que o sangue caiu, no lugar santo.

[[v3-6-28]]

^<<v3-6-28,28>>^ E o vaso de barro em que a carne for cozida será quebrado; porém, se for cozida num vaso de bronze, o vaso deverá ser esfregado e lavado com água.

[[v3-6-29]]

^<<v3-6-29,29>>^ Somente os homens da linhagem sacerdotal poderão comer dessa carne; coisa santíssima é.

[[v3-6-30]]

^<<v3-6-30,30>>^ Porém não se comerá nenhuma oferta pelo pecado, cujo sangue se traz à tenda do encontro, para fazer expiação no santuário; essa terá de ser queimada no fogo.

'''

xref:003-levitico/003-levitico-005.adoc#v3-5-0[&#60; Capítulo Anterior] | <<v3-6-0,Topo>> | xref:003-levitico/003-levitico-007.adoc#v3-7-0[Próximo Capítulo &#62;]