include::./index.adoc[]

[[v3-1-0]]
=== Levítico, 1
// naa ?, NAA - Nova Almeida Atualizada

[[v3-1-1]]

^<<v3-1-1,1>>^ O Senhor  chamou Moisés e, da tenda do encontro, lhe disse:

[[v3-1-2]]

^<<v3-1-2,2>>^ — Fale aos filhos de Israel e diga-lhes: Quando alguém trouxer oferta ao Senhor , traga um animal do rebanho de gado ou do rebanho de gado miúdo.

[[v3-1-3]]

^<<v3-1-3,3>>^ — Se a oferta for holocausto do rebanho de gado, o homem trará um macho sem defeito. Ele o trará à porta da tenda do encontro, para que o homem seja aceito diante do Senhor .

[[v3-1-4]]

^<<v3-1-4,4>>^ Porá a mão sobre a cabeça do holocausto, para que seja aceito a favor dele, para a sua expiação.

[[v3-1-5]]

^<<v3-1-5,5>>^ Depois, matará o novilho diante do Senhor . Os filhos de Arão, os sacerdotes, apresentarão o sangue e o aspergirão ao redor sobre o altar que está diante da porta da tenda do encontro.

[[v3-1-6]]

^<<v3-1-6,6>>^ Então ele tirará o couro do animal e o cortará em pedaços.

[[v3-1-7]]

^<<v3-1-7,7>>^ E os filhos do sacerdote Arão acenderão fogo sobre o altar e porão em ordem lenha sobre o fogo.

[[v3-1-8]]

^<<v3-1-8,8>>^ Também os filhos de Arão, os sacerdotes, colocarão em ordem os pedaços, a saber, a cabeça e a gordura, sobre a lenha que está no fogo sobre o altar.

[[v3-1-9]]

^<<v3-1-9,9>>^ Porém as entranhas e as pernas, o sacerdote as lavará com água; e queimará tudo isso sobre o altar; é holocausto, oferta queimada, de aroma agradável ao Senhor .

[[v3-1-10]]

^<<v3-1-10,10>>^ — Se a oferta for de gado miúdo, de carneiros ou de cabritos, para holocausto, trará um macho sem defeito.

[[v3-1-11]]

^<<v3-1-11,11>>^ E matará o animal ao lado do altar, para o lado norte, diante do Senhor . Os filhos de Arão, os sacerdotes, aspergirão o seu sangue sobre o altar, ao redor.

[[v3-1-12]]

^<<v3-1-12,12>>^ Depois, ele o cortará em pedaços, junto com a cabeça e a gordura; e o sacerdote os porá em ordem sobre a lenha que está no fogo sobre o altar.

[[v3-1-13]]

^<<v3-1-13,13>>^ Porém as entranhas e as pernas serão lavadas com água; e o sacerdote oferecerá tudo isso e o queimará sobre o altar; é holocausto, oferta queimada, de aroma agradável ao Senhor .

[[v3-1-14]]

^<<v3-1-14,14>>^ — Se a oferta ao Senhor  for holocausto de aves, trará a sua oferta de rolinhas ou de pombinhos.

[[v3-1-15]]

^<<v3-1-15,15>>^ O sacerdote a trará ao altar, destroncará a cabeça da ave, sem a separar do pescoço, e a queimará sobre o altar; o sangue da ave, ele o fará correr na parede do altar.

[[v3-1-16]]

^<<v3-1-16,16>>^ Tirará o papo com suas penas e o jogará junto ao altar, para o lado leste, no lugar da cinza.

[[v3-1-17]]

^<<v3-1-17,17>>^ Então abrirá a ave, puxando pelas asas, mas sem separá-la em duas metades; o sacerdote a queimará sobre o altar, em cima da lenha que está no fogo; é holocausto, oferta queimada, de aroma agradável ao Senhor .

'''

xref:002-exodo/002-exodo-040.adoc#v2-40-0[&#60; Capítulo Anterior] | <<v3-1-0,Topo>> | xref:003-levitico/003-levitico-002.adoc#v3-2-0[Próximo Capítulo &#62;]