include::./index.adoc[]

[[v3-16-0]]
=== Levítico, 16
// naa ?, NAA - Nova Almeida Atualizada

[[v3-16-1]]

^<<v3-16-1,1>>^ O Senhor  falou a Moisés, depois da morte dos dois filhos de Arão, quando estes chegaram diante do Senhor  e morreram.

[[v3-16-2]]

^<<v3-16-2,2>>^ O Senhor  disse a Moisés: — Diga a seu irmão Arão que não entre no santuário a qualquer hora, para dentro do véu, diante do propiciatório que está sobre a arca, para que não morra; porque aparecerei na nuvem sobre o propiciatório.

[[v3-16-3]]

^<<v3-16-3,3>>^ Mas é assim que Arão deverá entrar no santuário: com um novilho, para oferta pelo pecado, e um carneiro, para holocausto.

[[v3-16-4]]

^<<v3-16-4,4>>^ Ele vestirá a túnica sagrada de linho, terá as calças de linho sobre a pele, porá o cinto de linho na cintura e se cobrirá com a mitra de linho; são estas as vestes sagradas. Banhará o seu corpo em água e então porá essas vestes.

[[v3-16-5]]

^<<v3-16-5,5>>^ — Da congregação dos filhos de Israel pegará dois bodes, para a oferta pelo pecado, e um carneiro, para o holocausto.

[[v3-16-6]]

^<<v3-16-6,6>>^ Arão trará o novilho da sua oferta pelo pecado e fará expiação por si e pela sua casa.

[[v3-16-7]]

^<<v3-16-7,7>>^ Também pegará os dois bodes e os porá diante do Senhor , à porta da tenda do encontro.

[[v3-16-8]]

^<<v3-16-8,8>>^ Lançará sortes sobre os dois bodes: uma sorte para o Senhor , e a outra para o bode emissário.

[[v3-16-9]]

^<<v3-16-9,9>>^ Arão fará chegar o bode sobre o qual cair a sorte para o Senhor  e o oferecerá por oferta pelo pecado.

[[v3-16-10]]

^<<v3-16-10,10>>^ Mas o bode sobre o qual cair a sorte para bode emissário será apresentado vivo diante do Senhor , para fazer expiação por meio dele e enviá-lo ao deserto como bode emissário.

[[v3-16-11]]

^<<v3-16-11,11>>^ — Arão fará chegar o novilho da sua oferta pelo pecado e fará expiação por si e pela sua casa; matará o novilho da sua oferta pelo pecado.

[[v3-16-12]]

^<<v3-16-12,12>>^ Pegará também, de sobre o altar, o incensário cheio de brasas de fogo, diante do Senhor , e dois punhados de incenso aromático bem moído e o trará para dentro do véu.

[[v3-16-13]]

^<<v3-16-13,13>>^ Porá o incenso sobre o fogo, diante do Senhor , para que a nuvem do incenso cubra o propiciatório, que está sobre a arca do testemunho. Assim, Arão não correrá o risco de ser morto.

[[v3-16-14]]

^<<v3-16-14,14>>^ Ele pegará um pouco do sangue do novilho e, com o dedo, o aspergirá sobre a frente do propiciatório; e, diante do propiciatório, aspergirá sete vezes do sangue, com o dedo.

[[v3-16-15]]

^<<v3-16-15,15>>^ — Depois, matará o bode da oferta pelo pecado, que será para o povo. Trará o sangue do bode para dentro do véu e fará com esse sangue como fez com o sangue do novilho; ele o aspergirá no propiciatório e também diante dele.

[[v3-16-16]]

^<<v3-16-16,16>>^ Assim, fará expiação pelo santuário por causa das impurezas dos filhos de Israel e por causa das suas transgressões e de todos os seus pecados. Fará o mesmo pela tenda do encontro, que está com eles no meio das suas impurezas.

[[v3-16-17]]

^<<v3-16-17,17>>^ Ninguém poderá estar na tenda do encontro quando Arão entrar para fazer propiciação no santuário, até que ele saia depois de feita a expiação por si mesmo, pela sua casa e por toda a congregação de Israel.

[[v3-16-18]]

^<<v3-16-18,18>>^ Então sairá para junto do altar, que está diante do Senhor , e fará expiação pelo altar. Pegará um pouco do sangue do novilho e do sangue do bode e o porá sobre os chifres do altar, ao redor.

[[v3-16-19]]

^<<v3-16-19,19>>^ Do sangue aspergirá, com o dedo, sete vezes sobre o altar, o purificará e o santificará das impurezas dos filhos de Israel.

[[v3-16-20]]

^<<v3-16-20,20>>^ — Depois de fazer expiação pelo santuário, pela tenda do encontro e pelo altar, Arão fará chegar o bode vivo.

[[v3-16-21]]

^<<v3-16-21,21>>^ Porá as duas mãos sobre a cabeça do bode vivo e sobre ele confessará todas as iniquidades dos filhos de Israel, todas as suas transgressões e todos os seus pecados; e os porá sobre a cabeça do bode. Depois, enviará o bode ao deserto, pela mão de um homem à disposição para isso.

[[v3-16-22]]

^<<v3-16-22,22>>^ Assim, aquele bode levará sobre si todas as iniquidades deles para terra solitária; e o homem soltará o bode no deserto.

[[v3-16-23]]

^<<v3-16-23,23>>^ — Depois, Arão virá à tenda do encontro, despirá as vestes de linho que havia usado quando tinha entrado no santuário e ali as deixará.

[[v3-16-24]]

^<<v3-16-24,24>>^ Banhará o seu corpo em água no lugar santo e porá as suas roupas. Então sairá, e oferecerá o seu holocausto e o holocausto do povo, e fará expiação por si e pelo povo.

[[v3-16-25]]

^<<v3-16-25,25>>^ Também queimará a gordura da oferta pelo pecado sobre o altar.

[[v3-16-26]]

^<<v3-16-26,26>>^ E aquele que tiver levado o bode emissário lavará as suas roupas, banhará o seu corpo em água e, depois, entrará no arraial.

[[v3-16-27]]

^<<v3-16-27,27>>^ Mas o novilho e o bode da oferta pelo pecado, cujo sangue foi trazido para fazer expiação no santuário, serão levados para fora do arraial; o couro, a carne e o excremento deles serão queimados.

[[v3-16-28]]

^<<v3-16-28,28>>^ Aquele que o queimar lavará as suas roupas, banhará o seu corpo em água e, depois, entrará no arraial.

[[v3-16-29]]

^<<v3-16-29,29>>^ — Isso lhes será por estatuto perpétuo: no sétimo mês, aos dez dias do mês, vocês se humilharão e não farão nenhum trabalho, nem o natural da terra nem o estrangeiro que peregrina entre vocês.

[[v3-16-30]]

^<<v3-16-30,30>>^ Porque, naquele dia, se fará expiação por vocês, para purificá-los; e vocês serão purificados de todos os seus pecados, diante do Senhor .

[[v3-16-31]]

^<<v3-16-31,31>>^ É sábado de descanso solene para vocês, e vocês se humilharão; é estatuto perpétuo.

[[v3-16-32]]

^<<v3-16-32,32>>^ Aquele que for ungido e consagrado para oficiar como sacerdote no lugar de seu pai é que fará a expiação, havendo posto as vestes de linho, as vestes santas;

[[v3-16-33]]

^<<v3-16-33,33>>^ fará expiação pelo santuário, pela tenda do encontro e pelo altar; também a fará pelos sacerdotes e por todo o povo da congregação.

[[v3-16-34]]

^<<v3-16-34,34>>^ Isto lhes será por estatuto perpétuo, para fazer expiação uma vez por ano pelos filhos de Israel, por causa dos seus pecados. E Arão fez como o Senhor  havia ordenado a Moisés.

'''

xref:003-levitico/003-levitico-015.adoc#v3-15-0[&#60; Capítulo Anterior] | <<v3-16-0,Topo>> | xref:003-levitico/003-levitico-017.adoc#v3-17-0[Próximo Capítulo &#62;]