include::./index.adoc[]

[[v3-27-0]]
=== Levítico, 27
// naa ?, NAA - Nova Almeida Atualizada

[[v3-27-1]]

^<<v3-27-1,1>>^ O Senhor  disse ainda a Moisés:

[[v3-27-2]]

^<<v3-27-2,2>>^ — Fale aos filhos de Israel e diga-lhes: Quando alguém fizer um voto especial ao Senhor  com respeito a pessoas, o resgate será feito conforme a seguinte avaliação.

[[v3-27-3]]

^<<v3-27-3,3>>^ Se o objeto da avaliação for um homem, da idade de vinte anos até a de sessenta, a avaliação será de seiscentos gramas de prata, segundo o peso padrão do santuário.

[[v3-27-4]]

^<<v3-27-4,4>>^ Porém, se for mulher, a avaliação será de trezentos e sessenta gramas.

[[v3-27-5]]

^<<v3-27-5,5>>^ Se a idade for de cinco anos até vinte, a avaliação do homem será de duzentos e quarenta gramas, e a da mulher será de cento e vinte gramas.

[[v3-27-6]]

^<<v3-27-6,6>>^ Se a idade for de um mês até cinco anos, a avaliação do homem será de sessenta gramas de prata, e a avaliação pela mulher será de trinta e seis gramas de prata.

[[v3-27-7]]

^<<v3-27-7,7>>^ De sessenta anos para cima, se for homem, a avaliação será de cento e oitenta gramas; se mulher, cento e vinte gramas.

[[v3-27-8]]

^<<v3-27-8,8>>^ Mas, se for pobre e não puder pagar o previsto, então se apresentará ao sacerdote, para que este faça a avaliação; o sacerdote avaliará segundo o que permitem as posses de quem fez o voto.

[[v3-27-9]]

^<<v3-27-9,9>>^ — Se o que foi prometido for animal dos que se oferecem ao Senhor , tudo o que desse animal se der ao Senhor  será santo.

[[v3-27-10]]

^<<v3-27-10,10>>^ Não se poderá substituir ou trocar um animal bom por um ruim ou um ruim por um bom; porém, se de algum modo se trocar animal por animal, tanto um como o outro serão santos.

[[v3-27-11]]

^<<v3-27-11,11>>^ Se for animal impuro dos que não podem ser oferecidos ao Senhor , então apresentará o animal diante do sacerdote.

[[v3-27-12]]

^<<v3-27-12,12>>^ O sacerdote o avaliará, seja bom ou mau; segundo a avaliação do sacerdote, assim será.

[[v3-27-13]]

^<<v3-27-13,13>>^ Porém, se de algum modo o resgatar, então acrescentará a quinta parte ao que foi avaliado.

[[v3-27-14]]

^<<v3-27-14,14>>^ — Quando alguém dedicar a sua casa para ser santa ao Senhor , o sacerdote a avaliará, seja boa ou seja má; como o sacerdote a avaliar, assim será.

[[v3-27-15]]

^<<v3-27-15,15>>^ Mas, se a pessoa que a dedicou quiser resgatar a casa, então acrescentará a quinta parte do dinheiro à avaliação feita, e a casa ficará com a pessoa.

[[v3-27-16]]

^<<v3-27-16,16>>^ — Se alguém dedicar ao Senhor  parte do campo da sua herança, então a avaliação será segundo a semente necessária para o semear: cem quilos de cevada será avaliado por seiscentos gramas de prata.

[[v3-27-17]]

^<<v3-27-17,17>>^ Se dedicar o seu campo desde o Ano do Jubileu, a avaliação será pelo valor integral.

[[v3-27-18]]

^<<v3-27-18,18>>^ Mas, se dedicar o seu campo depois do Ano do Jubileu, então o sacerdote calculará o valor segundo os anos restantes até o Ano do Jubileu, de modo que o preço será menor.

[[v3-27-19]]

^<<v3-27-19,19>>^ Se aquele que dedicou o campo de algum modo o quiser resgatar, então acrescentará a quinta parte do dinheiro à avaliação feita, e o campo ficará com ele.

[[v3-27-20]]

^<<v3-27-20,20>>^ Se não quiser resgatar o campo ou se o vender a outro homem, nunca mais poderá ser resgatado.

[[v3-27-21]]

^<<v3-27-21,21>>^ Porém, havendo o campo saído livre no Ano do Jubileu, será santo ao Senhor , como campo consagrado; a posse dele será do sacerdote.

[[v3-27-22]]

^<<v3-27-22,22>>^ — Se alguém dedicar ao Senhor  o campo que comprou, e não for parte da sua herança,

[[v3-27-23]]

^<<v3-27-23,23>>^ então o sacerdote calculará o valor da avaliação até o Ano do Jubileu; e, no mesmo dia, pagará o valor da avaliação como coisa santa ao Senhor .

[[v3-27-24]]

^<<v3-27-24,24>>^ No Ano do Jubileu, o campo tornará àquele que o vendeu, àquele de quem era a posse do campo por herança.

[[v3-27-25]]

^<<v3-27-25,25>>^ Toda a avaliação se fará segundo o peso padrão do santuário; o peso padrão será de doze gramas.

[[v3-27-26]]

^<<v3-27-26,26>>^ — Mas o primogênito de um animal, por já pertencer ao Senhor , ninguém o dedicará; seja boi ou gado miúdo, é do Senhor .

[[v3-27-27]]

^<<v3-27-27,27>>^ Mas, se for de um animal impuro, poderá ser resgatado, segundo a avaliação, com o acréscimo de uma quinta parte do valor; se não for resgatado, poderá ser vendido, segundo a avaliação.

[[v3-27-28]]

^<<v3-27-28,28>>^ — No entanto, nada do que alguém consagrar por completo ao Senhor , de tudo o que tem, seja homem, animal ou campo da sua herança, se poderá vender, nem resgatar; toda coisa assim consagrada será santíssima ao Senhor .

[[v3-27-29]]

^<<v3-27-29,29>>^ Ninguém que dentre os homens for consagrado por completo ao Senhor  poderá ser resgatado; terá de ser morto.

[[v3-27-30]]

^<<v3-27-30,30>>^ — Também todos os dízimos da terra, tanto dos cereais do campo como dos frutos das árvores, são do Senhor ; são santos ao Senhor .

[[v3-27-31]]

^<<v3-27-31,31>>^ Se alguém quiser resgatar alguma coisa dos seus dízimos, acrescentará a isso a quinta parte.

[[v3-27-32]]

^<<v3-27-32,32>>^ — Quanto aos dízimos do gado e do rebanho, de tudo o que passar debaixo do bordão do pastor, o dízimo será santo ao Senhor .

[[v3-27-33]]

^<<v3-27-33,33>>^ Não se investigará se é bom ou mau, nem poderá ser trocado; mas, se de algum modo o trocar, tanto um quanto o outro serão santos; não poderão ser resgatados.

[[v3-27-34]]

^<<v3-27-34,34>>^ São estes os mandamentos que o Senhor  ordenou a Moisés, para os filhos de Israel, no monte Sinai.

'''

xref:003-levitico/003-levitico-026.adoc#v3-26-0[&#60; Capítulo Anterior] | <<v3-27-0,Topo>> | xref:004-numeros/004-numeros-001.adoc#v4-1-0[Próximo Capítulo &#62;]