include::./index.adoc[]

[[v3-15-0]]
=== Levítico, 15
// naa ?, NAA - Nova Almeida Atualizada

[[v3-15-1]]

^<<v3-15-1,1>>^ O Senhor  disse a Moisés e a Arão:

[[v3-15-2]]

^<<v3-15-2,2>>^ — Falem aos filhos de Israel e digam-lhes: Qualquer homem que tiver fluxo seminal do seu corpo ficará impuro por causa do fluxo.

[[v3-15-3]]

^<<v3-15-3,3>>^ Esta, pois, será a sua impureza por causa do seu fluxo: se o seu corpo vaza o fluxo ou se o seu corpo o estanca, esta é a sua impureza.

[[v3-15-4]]

^<<v3-15-4,4>>^ Toda cama em que se deitar o que tiver fluxo ficará impura; e tudo sobre que ele se assentar ficará impuro.

[[v3-15-5]]

^<<v3-15-5,5>>^ Quem tocar na cama dele terá de lavar as suas roupas, se banhará em água e ficará impuro até a tarde.

[[v3-15-6]]

^<<v3-15-6,6>>^ Quem se assentar sobre aquilo em que se havia assentado o homem que tem o fluxo lavará as suas roupas, se banhará em água e ficará impuro até a tarde.

[[v3-15-7]]

^<<v3-15-7,7>>^ Quem tocar o corpo do que tem o fluxo lavará as suas roupas, se banhará em água e ficará impuro até a tarde.

[[v3-15-8]]

^<<v3-15-8,8>>^ Se o homem que tem o fluxo cuspir sobre uma pessoa pura, essa pessoa lavará as suas roupas, se banhará em água e ficará impura até a tarde.

[[v3-15-9]]

^<<v3-15-9,9>>^ Também toda sela em que cavalgar o que tem o fluxo ficará impura.

[[v3-15-10]]

^<<v3-15-10,10>>^ Quem tocar alguma coisa que esteve debaixo dele ficará impuro até a tarde; e aquele que levar alguma dessas coisas lavará as suas roupas, se banhará em água e ficará impuro até a tarde.

[[v3-15-11]]

^<<v3-15-11,11>>^ Também todo aquele em quem tocar o que tiver o fluxo, sem haver lavado as suas mãos com água, lavará as suas roupas, se banhará em água e ficará impuro até a tarde.

[[v3-15-12]]

^<<v3-15-12,12>>^ O vaso de barro em que tocar o que tem o fluxo será quebrado; porém todo vaso de madeira será lavado com água.

[[v3-15-13]]

^<<v3-15-13,13>>^ — Quando, pois, o que tem o fluxo estiver puro dele, serão contados sete dias para a sua purificação; lavará as suas roupas, banhará o corpo em águas correntes e ficará puro.

[[v3-15-14]]

^<<v3-15-14,14>>^ No oitavo dia, pegará duas rolinhas ou dois pombinhos, e virá diante do Senhor , à porta da tenda do encontro, e os dará ao sacerdote.

[[v3-15-15]]

^<<v3-15-15,15>>^ Este os oferecerá, um para oferta pelo pecado, e o outro, para holocausto; e, assim, o sacerdote fará, por ele, expiação do seu fluxo diante do Senhor .

[[v3-15-16]]

^<<v3-15-16,16>>^ — Quando um homem tiver emissão de sêmen, banhará todo o seu corpo em água e ficará impuro até a tarde.

[[v3-15-17]]

^<<v3-15-17,17>>^ Toda roupa e toda peça de couro em que houver sêmen têm de ser lavadas em água e ficarão impuras até a tarde.

[[v3-15-18]]

^<<v3-15-18,18>>^ Se um homem tiver relações com mulher e tiver emissão do sêmen, ambos se banharão em água e ficarão impuros até a tarde.

[[v3-15-19]]

^<<v3-15-19,19>>^ — A mulher, quando tiver o fluxo de sangue, se este for o fluxo habitual do corpo dela, estará sete dias na sua menstruação, e quem a tocar ficará impuro até a tarde.

[[v3-15-20]]

^<<v3-15-20,20>>^ Tudo sobre que ela se deitar durante a menstruação ficará impuro; e tudo sobre que se assentar ficará impuro.

[[v3-15-21]]

^<<v3-15-21,21>>^ Quem tocar no leito dela lavará as suas roupas, se banhará em água e ficará impuro até a tarde.

[[v3-15-22]]

^<<v3-15-22,22>>^ Quem tocar alguma coisa sobre que ela se tiver assentado lavará as suas roupas, se banhará em água e ficará impuro até a tarde.

[[v3-15-23]]

^<<v3-15-23,23>>^ Também quem tocar alguma coisa que estiver sobre a cama ou sobre aquilo em que ela se assentou, esse ficará impuro até a tarde.

[[v3-15-24]]

^<<v3-15-24,24>>^ Se um homem tiver relações com a mulher, e a menstruação dela tocar nele, ficará impuro por sete dias; e toda cama sobre que ele se deitar ficará impura.

[[v3-15-25]]

^<<v3-15-25,25>>^ — Quando uma mulher tiver um fluxo de sangue por muitos dias fora do tempo da sua menstruação, ou quando tiver fluxo do sangue por mais tempo do que o habitual, todos os dias do fluxo ela ficará impura, como nos dias da sua menstruação.

[[v3-15-26]]

^<<v3-15-26,26>>^ Toda cama sobre que se deitar durante os dias do seu fluxo será como a cama em que ela se deita na sua menstruação; e toda coisa sobre que se assentar ficará impura, conforme a impureza da sua menstruação.

[[v3-15-27]]

^<<v3-15-27,27>>^ Quem tocar estas coisas ficará impuro; portanto, lavará as suas roupas, se banhará em água e ficará impuro até a tarde.

[[v3-15-28]]

^<<v3-15-28,28>>^ Porém, quando lhe cessar o fluxo, então se contarão sete dias, e depois estará pura.

[[v3-15-29]]

^<<v3-15-29,29>>^ No oitavo dia, pegará duas rolinhas ou dois pombinhos e os trará ao sacerdote à porta da tenda do encontro.

[[v3-15-30]]

^<<v3-15-30,30>>^ Então o sacerdote oferecerá um para oferta pelo pecado, e o outro, para holocausto; o sacerdote fará, por ela, expiação do fluxo da sua impureza diante do Senhor .

[[v3-15-31]]

^<<v3-15-31,31>>^ — Assim, vocês separarão os filhos de Israel das suas impurezas, para que não morram nelas, ao contaminarem o meu tabernáculo, que está no meio deles.

[[v3-15-32]]

^<<v3-15-32,32>>^ Esta é a lei a respeito daquele que tem o fluxo, daquele que tem emissão de sêmen e que, por causa dela, fica impuro,

[[v3-15-33]]

^<<v3-15-33,33>>^ da mulher em sua menstruação, daquele que tem o fluxo, seja homem ou mulher, e do homem que se deita com mulher impura.

'''

xref:003-levitico/003-levitico-014.adoc#v3-14-0[&#60; Capítulo Anterior] | <<v3-15-0,Topo>> | xref:003-levitico/003-levitico-016.adoc#v3-16-0[Próximo Capítulo &#62;]