include::./index.adoc[]

[[v3-4-0]]
=== Levítico, 4
// naa ?, NAA - Nova Almeida Atualizada

[[v3-4-1]]

^<<v3-4-1,1>>^ O Senhor  disse a Moisés:

[[v3-4-2]]

^<<v3-4-2,2>>^ — Fale aos filhos de Israel, dizendo: Quando alguém cometer pecado involuntário contra qualquer dos mandamentos do Senhor , por fazer contra algum deles o que não se deve fazer,

[[v3-4-3]]

^<<v3-4-3,3>>^ se o sacerdote ungido pecar, de tal maneira que o povo se torne culpado, oferecerá ao Senhor , como oferta pelo pecado, um novilho sem defeito.

[[v3-4-4]]

^<<v3-4-4,4>>^ Trará o novilho à porta da tenda do encontro, diante do Senhor , porá a mão sobre a cabeça do novilho e o matará diante do Senhor .

[[v3-4-5]]

^<<v3-4-5,5>>^ Então o sacerdote ungido pegará um pouco do sangue do novilho e o trará à tenda do encontro;

[[v3-4-6]]

^<<v3-4-6,6>>^ e, molhando o dedo no sangue, o aspergirá sete vezes diante do Senhor , diante do véu do santuário.

[[v3-4-7]]

^<<v3-4-7,7>>^ O sacerdote também porá um pouco daquele sangue sobre os chifres do altar do incenso aromático, diante do Senhor , altar que está na tenda do encontro. Todo o restante do sangue do novilho ele derramará na base do altar do holocausto, que está à porta da tenda do encontro.

[[v3-4-8]]

^<<v3-4-8,8>>^ O sacerdote tirará toda a gordura do novilho da expiação: a gordura que cobre as entranhas e toda a gordura que está no meio das entranhas,

[[v3-4-9]]

^<<v3-4-9,9>>^ os dois rins, a gordura que está sobre eles e junto aos lombos, e a membrana sobre o fígado, que tirará junto com os rins,

[[v3-4-10]]

^<<v3-4-10,10>>^ assim como se tira isso do novilho do sacrifício pacífico. E o sacerdote queimará essas partes sobre o altar do holocausto.

[[v3-4-11]]

^<<v3-4-11,11>>^ Mas o couro do novilho, toda a sua carne, a cabeça, as pernas, as entranhas e o excremento,

[[v3-4-12]]

^<<v3-4-12,12>>^ a saber, o novilho todo, levará para fora do arraial, a um lugar puro, onde se lança a cinza, e o queimará sobre a lenha; será queimado onde se lança a cinza.

[[v3-4-13]]

^<<v3-4-13,13>>^ — Mas, se toda a congregação de Israel cometer pecado involuntário, e isso for oculto aos olhos da coletividade, e se fizerem, contra algum dos mandamentos do Senhor , aquilo que não se deve fazer, e forem culpados,

[[v3-4-14]]

^<<v3-4-14,14>>^ e o pecado que cometeram for notório, então a coletividade trará um novilho como oferta pelo pecado e o apresentará diante da tenda do encontro.

[[v3-4-15]]

^<<v3-4-15,15>>^ Os anciãos da congregação porão as mãos sobre a cabeça do novilho diante do Senhor ; e o novilho será morto diante do Senhor .

[[v3-4-16]]

^<<v3-4-16,16>>^ Então o sacerdote ungido levará uma parte do sangue do novilho à tenda do encontro;

[[v3-4-17]]

^<<v3-4-17,17>>^ molhará o dedo no sangue e o aspergirá sete vezes diante do Senhor , diante do véu.

[[v3-4-18]]

^<<v3-4-18,18>>^ Depois, porá um pouco daquele sangue sobre os chifres do altar que está diante do Senhor , na tenda do encontro. Todo o restante do sangue ele derramará na base do altar do holocausto, que está à porta da tenda do encontro.

[[v3-4-19]]

^<<v3-4-19,19>>^ Tirará do novilho toda a gordura e a queimará sobre o altar,

[[v3-4-20]]

^<<v3-4-20,20>>^ e fará com este novilho como fez com o novilho da oferta pelo pecado. Assim, o sacerdote fará expiação por eles, e eles serão perdoados.

[[v3-4-21]]

^<<v3-4-21,21>>^ Depois, levará o novilho para fora do arraial e o queimará como queimou o primeiro novilho; é oferta pelo pecado da coletividade.

[[v3-4-22]]

^<<v3-4-22,22>>^ — Quando um chefe pecar, fazendo de forma involuntária alguma das coisas que o Senhor , seu Deus, ordenou que não se fizessem, e se tornar culpado;

[[v3-4-23]]

^<<v3-4-23,23>>^ ou se o pecado em que ele caiu lhe for notificado, trará por sua oferta um bode sem defeito.

[[v3-4-24]]

^<<v3-4-24,24>>^ Porá a mão sobre a cabeça do bode e o matará no lugar onde são mortos os animais oferecidos em holocausto, diante do Senhor ; é oferta pelo pecado.

[[v3-4-25]]

^<<v3-4-25,25>>^ Então o sacerdote, com o dedo, pegará um pouco do sangue da oferta pelo pecado e o porá sobre os chifres do altar do holocausto. Todo o restante do sangue derramará na base do altar do holocausto.

[[v3-4-26]]

^<<v3-4-26,26>>^ Como no caso do sacrifício pacífico, queimará toda a gordura sobre o altar. Assim, o sacerdote fará expiação por ele, no que se refere ao pecado, e este lhe será perdoado.

[[v3-4-27]]

^<<v3-4-27,27>>^ — Se qualquer pessoa do povo da terra cometer pecado involuntário, por fazer alguma das coisas que o Senhor  ordenou que não se fizessem, e se tornar culpada;

[[v3-4-28]]

^<<v3-4-28,28>>^ ou se o pecado em que ela caiu lhe for notificado, trará por sua oferta uma cabra sem defeito, pelo pecado que cometeu.

[[v3-4-29]]

^<<v3-4-29,29>>^ Porá a mão sobre a cabeça da oferta pelo pecado e matará o animal no lugar do holocausto.

[[v3-4-30]]

^<<v3-4-30,30>>^ Então o sacerdote, com o dedo, pegará um pouco do sangue da oferta e o porá sobre os chifres do altar do holocausto. Todo o restante do sangue derramará na base do altar.

[[v3-4-31]]

^<<v3-4-31,31>>^ Tirará toda a gordura, como se tira a gordura do sacrifício pacífico; o sacerdote a queimará sobre o altar como aroma agradável ao Senhor . Assim, o sacerdote fará expiação pela pessoa, e o pecado lhe será perdoado.

[[v3-4-32]]

^<<v3-4-32,32>>^ — Mas, se trouxer uma cordeira como oferta pelo pecado, deverá trazer uma fêmea sem defeito.

[[v3-4-33]]

^<<v3-4-33,33>>^ Porá a mão sobre a cabeça da oferta pelo pecado e matará o animal como oferta pelo pecado, no lugar onde são mortos os animais oferecidos em holocausto.

[[v3-4-34]]

^<<v3-4-34,34>>^ Então o sacerdote, com o dedo, pegará um pouco do sangue da oferta pelo pecado e o porá sobre os chifres do altar do holocausto. Todo o restante do sangue derramará na base do altar.

[[v3-4-35]]

^<<v3-4-35,35>>^ O sacerdote tirará toda a gordura, como se tira a gordura do cordeiro do sacrifício pacífico, e a queimará sobre o altar, em cima das ofertas queimadas do Senhor . Assim, o sacerdote, por essa pessoa, fará expiação do pecado que ela cometeu, e o pecado lhe será perdoado.

'''

xref:003-levitico/003-levitico-003.adoc#v3-3-0[&#60; Capítulo Anterior] | <<v3-4-0,Topo>> | xref:003-levitico/003-levitico-005.adoc#v3-5-0[Próximo Capítulo &#62;]