include::./index.adoc[]

[[v3-22-0]]
=== Levítico, 22
// naa ?, NAA - Nova Almeida Atualizada

[[v3-22-1]]

^<<v3-22-1,1>>^ O Senhor  disse a Moisés:

[[v3-22-2]]

^<<v3-22-2,2>>^ — Diga a Arão e aos seus filhos que se abstenham das ofertas sagradas, dedicadas a mim pelos filhos de Israel, para que não profanem o meu santo nome. Eu sou o Senhor .

[[v3-22-3]]

^<<v3-22-3,3>>^ Diga-lhes: Ao longo de suas gerações, qualquer descendente de vocês que se aproximar das ofertas sagradas que os filhos de Israel dedicam ao Senhor , tendo sobre si a sua impureza, será eliminado da minha presença. Eu sou o Senhor .

[[v3-22-4]]

^<<v3-22-4,4>>^ — Ninguém da descendência de Arão que for leproso ou tiver fluxo comerá das ofertas sagradas, até que esteja puro. Também não poderá comer das ofertas sagradas o que tocar alguma coisa impura por causa de um morto ou aquele que tiver emissão de sêmen;

[[v3-22-5]]

^<<v3-22-5,5>>^ nem aquele que tocar algum animal que rasteja pelo chão, com o que se faz impuro, ou alguma pessoa, com a qual se faz impuro, seja qual for a impureza dessa pessoa.

[[v3-22-6]]

^<<v3-22-6,6>>^ Quem tocar em tais coisas ficará impuro até a tarde e não comerá das ofertas sagradas sem primeiro banhar o seu corpo em água.

[[v3-22-7]]

^<<v3-22-7,7>>^ Depois do pôr do sol estará puro e poderá comer das ofertas sagradas, porque este é o seu alimento.

[[v3-22-8]]

^<<v3-22-8,8>>^ Do animal que morre por si mesmo ou é dilacerado por outro animal não comerá, para não se contaminar com isso. Eu sou o Senhor .

[[v3-22-9]]

^<<v3-22-9,9>>^ Guardarão, pois, a obrigação que têm para comigo, para que, por isso, não levem sobre si pecado e morram, havendo feito profanação. Eu sou o Senhor , que os santifico.

[[v3-22-10]]

^<<v3-22-10,10>>^ — Nenhum estranho poderá comer das ofertas sagradas; nem o hóspede do sacerdote nem o seu trabalhador diarista poderão comer das ofertas sagradas.

[[v3-22-11]]

^<<v3-22-11,11>>^ Mas, se o sacerdote comprar algum escravo com o seu dinheiro, este poderá comer delas; os que nascerem na casa do sacerdote, estes poderão comer do seu pão.

[[v3-22-12]]

^<<v3-22-12,12>>^ Se a filha do sacerdote se casar com um estranho, ela não poderá comer da oferta das coisas sagradas.

[[v3-22-13]]

^<<v3-22-13,13>>^ Mas, se a filha do sacerdote for viúva ou divorciada, não tiver filhos e tiver voltado à casa de seu pai, como na sua mocidade, poderá comer do pão de seu pai; mas nenhum estranho poderá comer desse alimento.

[[v3-22-14]]

^<<v3-22-14,14>>^ — Se alguém, por engano, comer a oferta sagrada, deverá acrescentar a ela a sua quinta parte e a dará ao sacerdote com a oferta sagrada.

[[v3-22-15]]

^<<v3-22-15,15>>^ Os sacerdotes não devem profanar as coisas sagradas que os filhos de Israel oferecem ao Senhor ,

[[v3-22-16]]

^<<v3-22-16,16>>^ pois assim os fariam levar sobre si a culpa da iniquidade, comendo as ofertas sagradas; porque eu sou o Senhor , que os santifico.

[[v3-22-17]]

^<<v3-22-17,17>>^ O Senhor  disse a Moisés:

[[v3-22-18]]

^<<v3-22-18,18>>^ — Fale a Arão, a seus filhos e a todos os filhos de Israel e diga-lhes: Quando um homem da casa de Israel ou dos estrangeiros em Israel apresentar a sua oferta ao Senhor  em holocausto, quer em cumprimento de seus votos ou como ofertas voluntárias,

[[v3-22-19]]

^<<v3-22-19,19>>^ para que seja aceitável deverá oferecer um macho sem defeito, seja do gado, do rebanho de ovelhas ou de cabras.

[[v3-22-20]]

^<<v3-22-20,20>>^ Porém todo o que tiver defeito, esse vocês não poderão oferecer; porque não seria aceito em favor de vocês.

[[v3-22-21]]

^<<v3-22-21,21>>^ Quando alguém oferecer sacrifício pacífico ao Senhor , quer em cumprimento de voto ou como oferta voluntária, do gado ou do rebanho, o animal deve ser sem defeito para ser aceitável; nele, não poderá haver defeito nenhum.

[[v3-22-22]]

^<<v3-22-22,22>>^ O cego, aleijado, mutilado, ulceroso, sarnoso ou cheio de feridas na pele, vocês não os devem oferecer ao Senhor  e deles não devem apresentar como oferta queimada ao Senhor  sobre o altar.

[[v3-22-23]]

^<<v3-22-23,23>>^ Porém novilho ou cordeiro desproporcionados vocês poderão oferecer por oferta voluntária, mas não será aceito se for para cumprir um voto.

[[v3-22-24]]

^<<v3-22-24,24>>^ Não ofereçam ao Senhor  animal que tiver os testículos machucados, moídos, arrancados ou cortados; não façam isso em sua terra.

[[v3-22-25]]

^<<v3-22-25,25>>^ Também da mão de um estrangeiro nenhum desses animais vocês poderão oferecer como pão do Deus de vocês, porque são corrompidos pelo defeito que há neles; não serão aceitos em favor de vocês.

[[v3-22-26]]

^<<v3-22-26,26>>^ O Senhor  disse ainda a Moisés:

[[v3-22-27]]

^<<v3-22-27,27>>^ — Quando nascer um bezerro, um cordeiro ou um cabrito, ele ficará sete dias com a mãe dele; do oitavo dia em diante será aceito por oferta queimada ao Senhor .

[[v3-22-28]]

^<<v3-22-28,28>>^ Quer seja vaca ou ovelha, não mate a ela e seu filhote, ambos no mesmo dia.

[[v3-22-29]]

^<<v3-22-29,29>>^ Quando vocês oferecerem sacrifício de ação de graças ao Senhor , façam-no para que vocês sejam aceitos.

[[v3-22-30]]

^<<v3-22-30,30>>^ No mesmo dia, será comido; e, dele, não deixem ficar nada até a manhã seguinte. Eu sou o Senhor .

[[v3-22-31]]

^<<v3-22-31,31>>^ — Guardem e cumpram os meus mandamentos. Eu sou o Senhor .

[[v3-22-32]]

^<<v3-22-32,32>>^ Não profanem o meu santo nome, mas serei santificado no meio dos filhos de Israel. Eu sou o Senhor , que os santifico,

[[v3-22-33]]

^<<v3-22-33,33>>^ que os tirei da terra do Egito, para ser o Deus de vocês. Eu sou o Senhor .

'''

xref:003-levitico/003-levitico-021.adoc#v3-21-0[&#60; Capítulo Anterior] | <<v3-22-0,Topo>> | xref:003-levitico/003-levitico-023.adoc#v3-23-0[Próximo Capítulo &#62;]