include::./index.adoc[]

[[v3-14-0]]
=== Levítico, 14
// naa ?, NAA - Nova Almeida Atualizada

[[v3-14-1]]

^<<v3-14-1,1>>^ O Senhor  disse a Moisés:

[[v3-14-2]]

^<<v3-14-2,2>>^ — Esta será a lei a respeito do leproso no dia da sua purificação: o leproso será levado ao sacerdote;

[[v3-14-3]]

^<<v3-14-3,3>>^ este sairá fora do arraial e o examinará. Se a praga da lepra estiver curada,

[[v3-14-4]]

^<<v3-14-4,4>>^ o sacerdote mandará trazer, para aquele que se houver de purificar, duas aves vivas e puras, madeira de cedro, pano escarlate e hissopo.

[[v3-14-5]]

^<<v3-14-5,5>>^ O sacerdote mandará que se mate uma das aves num vaso de barro, sobre águas correntes.

[[v3-14-6]]

^<<v3-14-6,6>>^ Depois o sacerdote pegará a ave que ficou viva, a madeira de cedro, o pano escarlate e o hissopo e os molhará no sangue da ave que foi morta sobre as águas correntes.

[[v3-14-7]]

^<<v3-14-7,7>>^ E aspergirá sete vezes sobre aquele que há de purificar-se da lepra; então o declarará puro e soltará a ave que ficou viva para o campo aberto.

[[v3-14-8]]

^<<v3-14-8,8>>^ Aquele que tem de se purificar lavará as suas roupas, rapará todos os seus pelos, se banhará com água e estará puro; depois, entrará no arraial, porém ficará fora da sua tenda por sete dias.

[[v3-14-9]]

^<<v3-14-9,9>>^ No sétimo dia, rapará todo o seu cabelo, a cabeça, a barba e as sobrancelhas; rapará todos os pelos, lavará as suas roupas, banhará o corpo com água e estará puro.

[[v3-14-10]]

^<<v3-14-10,10>>^ — No oitavo dia, pegará dois cordeiros sem defeito, uma cordeira sem defeito, de um ano, seis litros da melhor farinha, para oferta de cereais, amassada com azeite, e separadamente um copo de azeite.

[[v3-14-11]]

^<<v3-14-11,11>>^ O sacerdote que faz a purificação apresentará o homem que houver de purificar-se e essas coisas diante do Senhor , à porta da tenda do encontro;

[[v3-14-12]]

^<<v3-14-12,12>>^ pegará um dos cordeiros e o oferecerá por oferta pela culpa juntamente com o copo de azeite; e os moverá por oferta movida diante do Senhor .

[[v3-14-13]]

^<<v3-14-13,13>>^ Depois matará o cordeiro no lugar onde são mortos os animais da oferta pelo pecado e do holocausto, no lugar santo; porque tanto a oferta pela culpa como a oferta pelo pecado são para o sacerdote; são coisas santíssimas.

[[v3-14-14]]

^<<v3-14-14,14>>^ O sacerdote pegará um pouco do sangue da oferta pela culpa e o porá sobre a ponta da orelha direita daquele que tem de purificar-se, sobre o polegar da sua mão direita e sobre o polegar do seu pé direito.

[[v3-14-15]]

^<<v3-14-15,15>>^ Também pegará o copo de azeite e derramará um pouco na palma da própria mão esquerda.

[[v3-14-16]]

^<<v3-14-16,16>>^ Molhará o dedo direito no azeite que está na mão esquerda e daquele azeite aspergirá, com o dedo, sete vezes diante do Senhor ;

[[v3-14-17]]

^<<v3-14-17,17>>^ do restante do azeite que está na mão, o sacerdote porá um pouco sobre a ponta da orelha direita daquele que tem de purificar-se, sobre o polegar da sua mão direita e sobre o polegar do seu pé direito, em cima do sangue da oferta pela culpa.

[[v3-14-18]]

^<<v3-14-18,18>>^ O restante do azeite que está na mão do sacerdote ele porá sobre a cabeça daquele que tem de purificar-se; assim, o sacerdote fará expiação por ele diante do Senhor .

[[v3-14-19]]

^<<v3-14-19,19>>^ — Então o sacerdote fará a oferta pelo pecado e fará expiação por aquele que tem de purificar-se da sua impureza. Depois, matará o animal do holocausto

[[v3-14-20]]

^<<v3-14-20,20>>^ e o oferecerá com a oferta de cereais sobre o altar; assim, o sacerdote fará expiação pelo homem, e este ficará puro.

[[v3-14-21]]

^<<v3-14-21,21>>^ Se for pobre, e as suas posses não lhe permitirem trazer tanto, pegará um cordeiro para oferta pela culpa como oferta movida, para fazer expiação por ele, e dois litros da melhor farinha, amassada com azeite, para oferta de cereais, um copo de azeite,

[[v3-14-22]]

^<<v3-14-22,22>>^ duas rolinhas ou dois pombinhos, segundo as suas posses, dos quais um será para oferta pelo pecado, e o outro, para holocausto.

[[v3-14-23]]

^<<v3-14-23,23>>^ No oitavo dia da sua purificação, trará isso ao sacerdote, à porta da tenda do encontro, diante do Senhor .

[[v3-14-24]]

^<<v3-14-24,24>>^ O sacerdote pegará o cordeiro da oferta pela culpa e o copo de azeite e os moverá por oferta movida diante do Senhor .

[[v3-14-25]]

^<<v3-14-25,25>>^ Então o sacerdote matará o cordeiro da oferta pela culpa, pegará um pouco do sangue da oferta pela culpa e o porá sobre a ponta da orelha direita daquele que tem de purificar-se, sobre o polegar da sua mão direita e sobre o polegar do seu pé direito.

[[v3-14-26]]

^<<v3-14-26,26>>^ Derramará um pouco do azeite na palma da própria mão esquerda;

[[v3-14-27]]

^<<v3-14-27,27>>^ e, com o dedo direito, aspergirá do azeite que está na sua mão esquerda sete vezes diante do Senhor .

[[v3-14-28]]

^<<v3-14-28,28>>^ Então, do azeite que está na sua mão, o sacerdote porá um pouco na ponta da orelha direita daquele que tem de purificar-se, no polegar da sua mão direita e no polegar do seu pé direito, por cima do sangue da oferta pela culpa.

[[v3-14-29]]

^<<v3-14-29,29>>^ O restante do azeite que está na mão do sacerdote ele porá sobre a cabeça do que tem de purificar-se, para fazer expiação por ele diante do Senhor .

[[v3-14-30]]

^<<v3-14-30,30>>^ Oferecerá uma das rolinhas ou um dos pombinhos, segundo as suas posses;

[[v3-14-31]]

^<<v3-14-31,31>>^ será um para oferta pelo pecado, e o outro, para holocausto, além da oferta de cereais; e, assim, o sacerdote fará expiação por aquele que tem de purificar-se diante do Senhor .

[[v3-14-32]]

^<<v3-14-32,32>>^ Esta é a lei a respeito daquele em quem está a praga da lepra, cujas posses não lhe permitem o que é preciso para a sua purificação.

[[v3-14-33]]

^<<v3-14-33,33>>^ O Senhor  disse a Moisés e a Arão:

[[v3-14-34]]

^<<v3-14-34,34>>^ — Quando vocês entrarem na terra de Canaã, que lhes darei por herança, e eu enviar a praga do mofo a alguma casa da terra que vocês passarão a possuir,

[[v3-14-35]]

^<<v3-14-35,35>>^ o dono da casa fará saber ao sacerdote, dizendo: "Parece-me que existe algo como que uma praga em minha casa."

[[v3-14-36]]

^<<v3-14-36,36>>^ O sacerdote ordenará que se esvazie a casa, antes que venha para examinar a praga, para que não seja contaminado tudo o que está na casa. Depois o sacerdote virá para examinar a casa

[[v3-14-37]]

^<<v3-14-37,37>>^ e examinará a praga. Se, nas paredes da casa, há manchas esverdeadas ou avermelhadas e parecem mais fundas que a parede,

[[v3-14-38]]

^<<v3-14-38,38>>^ então o sacerdote sairá da casa e a fechará por sete dias.

[[v3-14-39]]

^<<v3-14-39,39>>^ No sétimo dia, o sacerdote voltará e examinará a casa. Se notar que a praga se alastrou nas paredes da casa,

[[v3-14-40]]

^<<v3-14-40,40>>^ ele ordenará que arranquem as pedras em que estiver a praga e que as lancem fora da cidade num lugar impuro;

[[v3-14-41]]

^<<v3-14-41,41>>^ e fará raspar a casa por dentro, ao redor, e o pó que houverem raspado lançarão, fora da cidade, num lugar impuro.

[[v3-14-42]]

^<<v3-14-42,42>>^ Depois pegarão outras pedras e as colocarão no lugar das primeiras; e rebocarão a casa com outra argamassa.

[[v3-14-43]]

^<<v3-14-43,43>>^ — Se a praga tornar a brotar na casa, depois de arrancadas as pedras, raspada a casa e de novo rebocada,

[[v3-14-44]]

^<<v3-14-44,44>>^ então o sacerdote entrará e examinará. Se a praga tiver se alastrado pela casa, há nela mofo que se espalha; está impura.

[[v3-14-45]]

^<<v3-14-45,45>>^ O sacerdote mandará derrubar a casa, as pedras e a sua madeira, bem como todo o reboco da casa; e se levará tudo para fora da cidade, a um lugar impuro.

[[v3-14-46]]

^<<v3-14-46,46>>^ Aquele que entrar na casa, enquanto está fechada, ficará impuro até a tarde.

[[v3-14-47]]

^<<v3-14-47,47>>^ Também o que se deitar na casa terá de lavar as suas roupas; e quem nela comer terá de lavar as suas roupas.

[[v3-14-48]]

^<<v3-14-48,48>>^ — Porém, se o sacerdote entrar na casa, e, examinando, verificar que a praga não se alastrou pela casa, depois que ela foi rebocada, o sacerdote a declarará pura, porque a praga está curada.

[[v3-14-49]]

^<<v3-14-49,49>>^ Para purificar a casa, pegará duas aves, madeira de cedro, pano escarlate e hissopo,

[[v3-14-50]]

^<<v3-14-50,50>>^ e matará uma ave num vaso de barro sobre águas correntes.

[[v3-14-51]]

^<<v3-14-51,51>>^ Depois, pegará a madeira de cedro, o hissopo, o pano escarlate e a ave que ficou viva, os molhará no sangue da ave que foi morta e nas águas correntes e aspergirá a casa sete vezes.

[[v3-14-52]]

^<<v3-14-52,52>>^ Assim, purificará aquela casa com o sangue da ave, com as águas correntes, com a ave que ficou viva, com a madeira de cedro, com o hissopo e com o pano escarlate.

[[v3-14-53]]

^<<v3-14-53,53>>^ Então soltará a ave que ficou viva para fora da cidade, para o campo aberto; assim, fará expiação pela casa, e ficará pura.

[[v3-14-54]]

^<<v3-14-54,54>>^ Esta é a lei para todos os tipos de praga de lepra, de micose,

[[v3-14-55]]

^<<v3-14-55,55>>^ de mofo das roupas e das casas,

[[v3-14-56]]

^<<v3-14-56,56>>^ da inchação, da pústula e das manchas lustrosas,

[[v3-14-57]]

^<<v3-14-57,57>>^ para ensinar quando alguma coisa é pura ou impura. Esta é a lei a respeito da lepra.

'''

xref:003-levitico/003-levitico-013.adoc#v3-13-0[&#60; Capítulo Anterior] | <<v3-14-0,Topo>> | xref:003-levitico/003-levitico-015.adoc#v3-15-0[Próximo Capítulo &#62;]