include::./index.adoc[]

[[v3-18-0]]
=== Levítico, 18
// naa ?, NAA - Nova Almeida Atualizada

[[v3-18-1]]

^<<v3-18-1,1>>^ O Senhor  disse a Moisés:

[[v3-18-2]]

^<<v3-18-2,2>>^ — Fale aos filhos de Israel e diga-lhes: Eu sou o Senhor , o Deus de vocês.

[[v3-18-3]]

^<<v3-18-3,3>>^ Não façam como se faz na terra do Egito, onde vocês moraram, nem façam como se faz na terra de Canaã, para onde eu os estou levando. Não andem segundo os estatutos desses povos.

[[v3-18-4]]

^<<v3-18-4,4>>^ Cumpram os meus juízos e guardem os meus estatutos, para andarem neles. Eu sou o Senhor , o Deus de vocês.

[[v3-18-5]]

^<<v3-18-5,5>>^ Portanto, guardem os meus estatutos e os meus juízos. Aquele que os cumprir, por eles viverá. Eu sou o Senhor .

[[v3-18-6]]

^<<v3-18-6,6>>^ — Nenhum homem se aproximará de qualquer parenta próxima, para ter relações sexuais com ela. Eu sou o Senhor .

[[v3-18-7]]

^<<v3-18-7,7>>^ Não envergonhe o seu pai, tendo relações com a própria mãe. Ela é a sua mãe; não tenha relações com ela.

[[v3-18-8]]

^<<v3-18-8,8>>^ Não tenha relações com a mulher de seu pai; este é um direito que somente o seu pai tem.

[[v3-18-9]]

^<<v3-18-9,9>>^ Não tenha relações com a sua irmã, filha de seu pai ou filha de sua mãe, nascida em casa ou fora de casa.

[[v3-18-10]]

^<<v3-18-10,10>>^ Não tenha relações com a filha do seu filho ou com a filha de sua filha; não faça isso, porque seria uma vergonha para você.

[[v3-18-11]]

^<<v3-18-11,11>>^ Não tenha relações com a filha da mulher de seu pai, gerada por seu pai; ela é a sua irmã.

[[v3-18-12]]

^<<v3-18-12,12>>^ Não tenha relações com a irmã do seu pai; ela é parenta de seu pai.

[[v3-18-13]]

^<<v3-18-13,13>>^ Não tenha relações com a irmã de sua mãe, pois ela é parenta de sua mãe.

[[v3-18-14]]

^<<v3-18-14,14>>^ Não envergonhe o irmão de seu pai, tendo relações com a mulher dele; ela é a sua tia.

[[v3-18-15]]

^<<v3-18-15,15>>^ Não tenha relações com a sua nora; ela é a mulher de seu filho; não tenha relações com ela.

[[v3-18-16]]

^<<v3-18-16,16>>^ Não tenha relações com a mulher de seu irmão; este é um direito que somente o seu irmão tem.

[[v3-18-17]]

^<<v3-18-17,17>>^ Não tenha relações com uma mulher e com a filha dela; não tenha relações com a filha do filho dela, nem com a filha da filha dela; são parentes; é algo vergonhoso.

[[v3-18-18]]

^<<v3-18-18,18>>^ E não case com a irmã de sua mulher, de modo que se torne rival dela, nem tenha relações com a outra, enquanto a sua mulher estiver viva.

[[v3-18-19]]

^<<v3-18-19,19>>^ — Não se aproxime da mulher, para ter relações com ela, durante a sua menstruação.

[[v3-18-20]]

^<<v3-18-20,20>>^ Nem se deite com a mulher do seu próximo, para ter relações sexuais, porque isso torna você impuro.

[[v3-18-21]]

^<<v3-18-21,21>>^ E não entregue nenhum dos seus descendentes para que se dedique a Moloque. Não profane o nome do seu Deus. Eu sou o Senhor .

[[v3-18-22]]

^<<v3-18-22,22>>^ — Não se deite com outro homem para ter relações com ele como se fosse mulher; é abominação.

[[v3-18-23]]

^<<v3-18-23,23>>^ Nem tenha relações com um animal, para se contaminar com ele; e também a mulher não se porá diante de um animal, para ajuntar-se com ele; é confusão.

[[v3-18-24]]

^<<v3-18-24,24>>^ — Não se contaminem com nenhuma destas coisas, porque com todas estas coisas se contaminaram as nações que eu vou expulsar da presença de vocês.

[[v3-18-25]]

^<<v3-18-25,25>>^ A terra se contaminou; eu a castiguei por sua iniquidade, e ela vomitou os seus moradores.

[[v3-18-26]]

^<<v3-18-26,26>>^ Vocês, porém, guardarão os meus estatutos e os meus juízos, e não farão nenhuma dessas abominações, nem o natural da terra, nem o estrangeiro que peregrina entre vocês.

[[v3-18-27]]

^<<v3-18-27,27>>^ Porque os moradores desta terra que nela estavam antes de vocês fizeram todas essas abominações, e a terra se contaminou.

[[v3-18-28]]

^<<v3-18-28,28>>^ Que não aconteça que a terra vomite vocês também, por terem se contaminado, como vomitou o povo que nela estava antes de vocês.

[[v3-18-29]]

^<<v3-18-29,29>>^ Todo aquele que fizer alguma dessas abominações, sim, aqueles que as cometerem serão eliminados do seu povo.

[[v3-18-30]]

^<<v3-18-30,30>>^ — Portanto, vocês devem guardar a obrigação que têm para comigo, não praticando nenhum dos costumes abomináveis que foram praticados antes de vocês, e não se contaminem com eles. Eu sou o Senhor , o Deus de vocês.

'''

xref:003-levitico/003-levitico-017.adoc#v3-17-0[&#60; Capítulo Anterior] | <<v3-18-0,Topo>> | xref:003-levitico/003-levitico-019.adoc#v3-19-0[Próximo Capítulo &#62;]