include::./index.adoc[]

[[v28-10-0]]
=== Oséias, 10
// naa ?, NAA - Nova Almeida Atualizada

[[v28-10-1]]

^<<v28-10-1,1>>^ "Israel era uma videira de ramagem viçosa, que dava o seu fruto. Quanto mais abundantes os frutos, maior o número de altares; quanto mais a terra produzia, tanto mais embelezavam as colunas sagradas.

[[v28-10-2]]

^<<v28-10-2,2>>^ O coração deles está dividido e agora terão de pagar por isso. O Senhor  quebrará os altares deles e destruirá as colunas sagradas."

[[v28-10-3]]

^<<v28-10-3,3>>^ "Agora eles vão dizer: ‘Não temos rei, porque não tememos o Senhor . E o rei, que poderia fazer por nós?’

[[v28-10-4]]

^<<v28-10-4,4>>^ Falam palavras vãs, juram falsamente e fazem alianças; por isso, o juízo brota como erva venenosa nos sulcos dos campos.

[[v28-10-5]]

^<<v28-10-5,5>>^ Os moradores de Samaria ficarão com medo por causa do bezerro de Bete-Áven; o seu povo se lamentará por causa dele, e os sacerdotes idólatras tremerão por causa da sua glória, que já se foi.

[[v28-10-6]]

^<<v28-10-6,6>>^ Também o bezerro será levado à Assíria como presente para o grande rei. Efraim se cobrirá de vexame, e Israel ficará com vergonha do seu ídolo de madeira."

[[v28-10-7]]

^<<v28-10-7,7>>^ "O rei de Samaria será como lasca de madeira na superfície da água.

[[v28-10-8]]

^<<v28-10-8,8>>^ Os lugares altos de Áven, que são o pecado de Israel, serão destruídos; espinhos e ervas daninhas crescerão sobre os seus altares. E o povo dirá aos montes: ‘Cubram-nos!’ E às colinas: ‘Caiam em cima de nós!’"

[[v28-10-9]]

^<<v28-10-9,9>>^ "Desde os dias de Gibeá, você pecou, ó Israel, e nesse pecado você permaneceu. Será que a batalha contra os filhos da perversidade não há de alcançá-los em Gibeá?

[[v28-10-10]]

^<<v28-10-10,10>>^ Eu os castigarei na medida do meu desejo. Os povos se ajuntarão contra eles, quando eu os punir por causa de sua dupla transgressão.

[[v28-10-11]]

^<<v28-10-11,11>>^ Porque Efraim era uma bezerra domada, que gostava de pisar o trigo na eira. Coloquei o jugo sobre o seu belo pescoço; atrelei Efraim ao carro. Judá lavrará, Jacó lhe desfará os torrões.

[[v28-10-12]]

^<<v28-10-12,12>>^ Então eu disse: ‘Semeiem a justiça e colham a misericórdia. Lavrem o campo não cultivado, porque é tempo de buscar o Senhor , até que ele venha, e chova a justiça sobre vocês.’"

[[v28-10-13]]

^<<v28-10-13,13>>^ "Vocês lavraram para a maldade, colheram a injustiça e comeram os frutos da mentira. Vocês confiaram nos seus carros de guerra e na multidão dos seus valentes,

[[v28-10-14]]

^<<v28-10-14,14>>^ e por isso entre o seu povo se levantará o tumulto de guerra, e todas as suas fortalezas serão destruídas, como Salmã destruiu Bete-Arbel no dia da batalha. As mães foram despedaçadas com os seus filhos.

[[v28-10-15]]

^<<v28-10-15,15>>^ Assim se fará com você, ó Betel, por causa da sua grande maldade. Ao amanhecer, o rei de Israel será totalmente destruído."

'''

xref:028-oseias/028-oseias-009.adoc#v28-9-0[&#60; Capítulo Anterior] | <<v28-10-0,Topo>> | xref:028-oseias/028-oseias-011.adoc#v28-11-0[Próximo Capítulo &#62;]