include::./index.adoc[]

[[v28-7-0]]
=== Oséias, 7
// naa ?, NAA - Nova Almeida Atualizada

[[v28-7-1]]

^<<v28-7-1,1>>^ Quando tento sarar Israel, se descobre a iniquidade de Efraim e a maldade de Samaria, porque praticam a falsidade; ladrões invadem as casas e bandos assaltam nas ruas.

[[v28-7-2]]

^<<v28-7-2,2>>^ Não se dão conta de que eu me lembro de todas as suas maldades. Agora estão rodeados pelas suas más ações, que estão sempre diante de mim.

[[v28-7-3]]

^<<v28-7-3,3>>^ Alegram o rei com as suas maldades, e os príncipes, com as suas mentiras.

[[v28-7-4]]

^<<v28-7-4,4>>^ Todos eles são adúlteros. São semelhantes ao forno aceso pelo padeiro, que não precisa atiçar o fogo desde que sovou a massa até que seja levedada.

[[v28-7-5]]

^<<v28-7-5,5>>^ No dia da festa do nosso rei, os príncipes adoeceram de tanto beber vinho, e o rei estendeu a mão aos zombadores.

[[v28-7-6]]

^<<v28-7-6,6>>^ Enquanto estão à espreita, preparam o coração como um forno: durante a noite o seu furor se abranda, mas, pela manhã, queima como um fogo abrasador.

[[v28-7-7]]

^<<v28-7-7,7>>^ Todos eles são quentes como um forno e consomem os seus juízes. Todos os seus reis caem, mas não há ninguém entre eles que me invoque."

[[v28-7-8]]

^<<v28-7-8,8>>^ "Efraim se mistura com os povos e é um pão que não foi virado na hora de assar.

[[v28-7-9]]

^<<v28-7-9,9>>^ Estrangeiros sugam as suas forças, mas ele não percebe; cabelos brancos se espalham pela cabeça, mas ele não o sabe.

[[v28-7-10]]

^<<v28-7-10,10>>^ A arrogância de Israel abertamente dá testemunho contra eles, mas eles não voltam para o Senhor , seu Deus, nem o buscam em tudo isso."

[[v28-7-11]]

^<<v28-7-11,11>>^ "Porque Efraim é como uma pomba ingênua, sem entendimento: chamam o Egito e se voltam para a Assíria.

[[v28-7-12]]

^<<v28-7-12,12>>^ Quando forem, estenderei a minha rede sobre eles e farei com que desçam como as aves do céu. Eu os castigarei de acordo com o que ouviram na sua congregação.

[[v28-7-13]]

^<<v28-7-13,13>>^ — Ai deles! Porque fugiram de mim. Destruição sobre eles, porque se rebelaram contra mim! Eu os remiria, mas eles falam mentiras contra mim."

[[v28-7-14]]

^<<v28-7-14,14>>^ "Não clamam a mim de coração, mas dão uivos nas suas camas. Eles se ajuntam para o trigo e para o vinho, mas se rebelam contra mim.

[[v28-7-15]]

^<<v28-7-15,15>>^ Eu treinei e fortaleci os seus braços, mas eles planejam o mal contra mim.

[[v28-7-16]]

^<<v28-7-16,16>>^ Eles voltam, mas não para o Altíssimo. Fizeram-se como um arco defeituoso. Os seus príncipes serão mortos à espada, por causa da insolência da sua língua. Serão motivo de zombaria na terra do Egito."

'''

xref:028-oseias/028-oseias-006.adoc#v28-6-0[&#60; Capítulo Anterior] | <<v28-7-0,Topo>> | xref:028-oseias/028-oseias-008.adoc#v28-8-0[Próximo Capítulo &#62;]