include::./index.adoc[]

[[v28-2-0]]
=== Oséias, 2
// naa ?, NAA - Nova Almeida Atualizada

[[v28-2-1]]

^<<v28-2-1,1>>^ Chamem seus irmãos de Ami, e suas irmãs de Ruamá.

[[v28-2-2]]

^<<v28-2-2,2>>^ "Acusem a mãe de vocês, acusem-na, porque ela não é minha mulher, e eu não sou seu marido. Que ela afaste as suas prostituições de sua presença e os seus adultérios de entre os seus seios.

[[v28-2-3]]

^<<v28-2-3,3>>^ Do contrário, eu a deixarei sem roupa e nua como no dia em que nasceu. Eu a tornarei semelhante a um deserto, a uma terra seca, e deixarei que morra de sede.

[[v28-2-4]]

^<<v28-2-4,4>>^ E não terei compaixão de seus filhos, porque são filhos de uma prostituta.

[[v28-2-5]]

^<<v28-2-5,5>>^ Pois a mãe deles se prostituiu; aquela que os concebeu agiu de forma vergonhosa. Porque disse: ‘Irei atrás dos meus amantes, que me dão o meu pão e a minha água, a minha lã e o meu linho, o meu azeite e as minhas bebidas.’"

[[v28-2-6]]

^<<v28-2-6,6>>^ "Portanto, eis que cercarei o seu caminho com espinhos e levantarei um muro contra ela, para que ela não ache as suas veredas.

[[v28-2-7]]

^<<v28-2-7,7>>^ Ela correrá atrás dos seus amantes, mas não os alcançará; irá procurá-los, mas não os encontrará. Então dirá: ‘Vou voltar para o meu primeiro marido, porque a minha vida era melhor naquele tempo do que agora.’

[[v28-2-8]]

^<<v28-2-8,8>>^ Ela não reconheceu que fui eu que lhe dei o trigo, o vinho e o azeite; fui eu que lhe multipliquei a prata e o ouro, que eles usaram para Baal.

[[v28-2-9]]

^<<v28-2-9,9>>^ Portanto, farei com que, no devido tempo, ela devolva o meu trigo e o meu vinho. Tirarei dela a minha lã e o meu linho, que deviam cobrir a sua nudez.

[[v28-2-10]]

^<<v28-2-10,10>>^ Agora descobrirei as suas vergonhas aos olhos dos seus amantes, e ninguém a livrará da minha mão.

[[v28-2-11]]

^<<v28-2-11,11>>^ Farei cessar toda a sua alegria, as suas festas, as Festas de Lua Nova, os seus sábados e todas as suas solenidades.

[[v28-2-12]]

^<<v28-2-12,12>>^ Devastarei as suas videiras e as suas figueiras, das quais ela diz: ‘Este é o pagamento que recebi dos meus amantes.’ Farei com que virem mato, e os animais selvagens as devorarão.

[[v28-2-13]]

^<<v28-2-13,13>>^ Eu a castigarei pelos dias dos baalins, nos quais lhes queimou incenso, e se enfeitou com os seus pendentes e com as suas joias, e andou atrás de seus amantes, mas de mim se esqueceu", diz o Senhor .

[[v28-2-14]]

^<<v28-2-14,14>>^ "Portanto, eis que eu a atrairei, e a levarei para o deserto, e lhe falarei ao coração.

[[v28-2-15]]

^<<v28-2-15,15>>^ E ali eu lhe devolverei as suas vinhas e farei do vale de Acor uma porta de esperança. Ali ela me responderá como nos dias da sua mocidade e como no dia em que saiu da terra do Egito.

[[v28-2-16]]

^<<v28-2-16,16>>^ Naquele dia", diz o Senhor , "ela me chamará de ‘Meu Marido’, e não me chamará mais de ‘Meu Baal’.

[[v28-2-17]]

^<<v28-2-17,17>>^ Removerei da sua boca os nomes dos baalins, e ela não mais se lembrará desses nomes.

[[v28-2-18]]

^<<v28-2-18,18>>^ Naquele dia, farei a favor dela uma aliança com os animais selvagens, com as aves do céu e com os animais que rastejam sobre a terra. Tirarei da terra o arco, a espada e a guerra e farei com que o meu povo repouse em segurança.

[[v28-2-19]]

^<<v28-2-19,19>>^ Farei de você a minha esposa para sempre. Farei de você a minha esposa em justiça, em juízo, em bondade e em misericórdia.

[[v28-2-20]]

^<<v28-2-20,20>>^ Farei de você a minha esposa em fidelidade, e você conhecerá o Senhor ."

[[v28-2-21]]

^<<v28-2-21,21>>^ "Naquele dia, eu responderei", diz o Senhor , "responderei aos céus, e estes responderão à terra;

[[v28-2-22]]

^<<v28-2-22,22>>^ a terra responderá ao trigo, ao vinho e ao azeite; e estes responderão a Jezreel.

[[v28-2-23]]

^<<v28-2-23,23>>^ Semearei Israel para mim mesmo na terra e terei compaixão de Lo-Ruamá. E para Lo-Ami direi: ‘Você é o meu povo!’ Ele responderá: ‘Tu és o meu Deus!’"

'''

xref:028-oseias/028-oseias-001.adoc#v28-1-0[&#60; Capítulo Anterior] | <<v28-2-0,Topo>> | xref:028-oseias/028-oseias-003.adoc#v28-3-0[Próximo Capítulo &#62;]