include::./index.adoc[]

[[v28-4-0]]
=== Oséias, 4
// naa ?, NAA - Nova Almeida Atualizada

[[v28-4-1]]

^<<v28-4-1,1>>^ Filhos de Israel, escutem a palavra do Senhor . Porque o Senhor  tem uma controvérsia com os moradores da terra: "Não há verdade, nem amor, nem conhecimento de Deus na terra,

[[v28-4-2]]

^<<v28-4-2,2>>^ mas apenas juramento falso, mentira e assassinato, roubo e adultério. Há violência e homicídios sobre homicídios.

[[v28-4-3]]

^<<v28-4-3,3>>^ Por isso, a terra está de luto, e todos os seus moradores desfalecem, juntamente com os animais do campo e com as aves do céu; e até os peixes do mar estão morrendo."

[[v28-4-4]]

^<<v28-4-4,4>>^ "Todavia, que ninguém acuse, nem repreenda, porque a minha acusação é contra vocês, sacerdotes.

[[v28-4-5]]

^<<v28-4-5,5>>^ Por isso, vocês tropeçarão de dia, e os profetas, juntamente com vocês, tropeçarão de noite; e eu destruirei a mãe de vocês.

[[v28-4-6]]

^<<v28-4-6,6>>^ O meu povo está sendo destruído, pois lhe falta o conhecimento. Pelo fato de vocês, sacerdotes, rejeitarem o conhecimento, também eu os rejeitarei, para que não sejam mais sacerdotes diante de mim; visto que se esqueceram da lei do seu Deus, também eu me esquecerei dos seus filhos."

[[v28-4-7]]

^<<v28-4-7,7>>^ "Quanto mais estes se multiplicaram, tanto mais contra mim pecaram; eu mudarei a sua honra em vergonha.

[[v28-4-8]]

^<<v28-4-8,8>>^ Alimentam-se do pecado do meu povo e o seu maior desejo é que o povo continue a pecar.

[[v28-4-9]]

^<<v28-4-9,9>>^ Por isso, tal povo, tal sacerdote; eu os castigarei pela sua conduta e lhes darei o que merecem por seus atos.

[[v28-4-10]]

^<<v28-4-10,10>>^ Comerão, mas não ficarão satisfeitos; eles se entregarão à prostituição, mas não se multiplicarão, porque deixaram de adorar o Senhor ."

[[v28-4-11]]

^<<v28-4-11,11>>^ "A prostituição, o vinho envelhecido e o vinho novo tiram o entendimento.

[[v28-4-12]]

^<<v28-4-12,12>>^ O meu povo consulta os seus ídolos de madeira, e um pedaço de pau lhes dá resposta. Porque um espírito de prostituição os enganou, e eles, prostituindo-se, abandonaram o seu Deus.

[[v28-4-13]]

^<<v28-4-13,13>>^ Sacrificam no alto dos montes e queimam incenso sobre as colinas, debaixo dos carvalhos, dos álamos e dos terebintos, porque é boa a sua sombra. Por isso, as filhas de vocês se prostituem, e as suas noras adulteram."

[[v28-4-14]]

^<<v28-4-14,14>>^ "Não castigarei as filhas de vocês, que se prostituem, nem as suas noras, quando adulteram, porque os próprios homens se retiram com as meretrizes e oferecem sacrifícios com as prostitutas cultuais. E um povo que não tem entendimento corre para a sua perdição."

[[v28-4-15]]

^<<v28-4-15,15>>^ "Se você, Israel, quer se prostituir, pelo menos não faça com que Judá se torne culpado. Não venham a Gilgal, nem subam a Bete-Áven. E não jurem, dizendo: ‘Tão certo como vive o Senhor .’

[[v28-4-16]]

^<<v28-4-16,16>>^ Como vaca rebelde, Israel se rebelou. Será que o Senhor pode apascentá-los num lugar espaçoso como se fossem cordeiros?"

[[v28-4-17]]

^<<v28-4-17,17>>^ "Efraim está entregue aos ídolos; é deixá-lo.

[[v28-4-18]]

^<<v28-4-18,18>>^ Tendo acabado de beber, eles se entregam à prostituição; os seus príncipes amam apaixonadamente a desonra.

[[v28-4-19]]

^<<v28-4-19,19>>^ O vento os envolveu nas suas asas, e eles ficarão envergonhados por causa dos seus sacrifícios."

'''

xref:028-oseias/028-oseias-003.adoc#v28-3-0[&#60; Capítulo Anterior] | <<v28-4-0,Topo>> | xref:028-oseias/028-oseias-005.adoc#v28-5-0[Próximo Capítulo &#62;]