include::./index.adoc[]

[[v28-9-0]]
=== Oséias, 9
// naa ?, NAA - Nova Almeida Atualizada

[[v28-9-1]]

^<<v28-9-1,1>>^ "Não se alegre, Israel, nem exulte como os outros povos. Porque você se prostituiu, abandonando o seu Deus. Você gostou de receber o pagamento de prostituta em todas as eiras de cereais.

[[v28-9-2]]

^<<v28-9-2,2>>^ A eira e o lagar não os alimentarão; e o vinho novo lhes faltará.

[[v28-9-3]]

^<<v28-9-3,3>>^ Não permanecerão na terra do Senhor ; Efraim voltará para o Egito, e na Assíria comerão comida impura."

[[v28-9-4]]

^<<v28-9-4,4>>^ "Não oferecerão libações de vinho ao Senhor , nem os seus sacrifícios lhe serão agradáveis. O pão que comerem será como pão de pranteadores, e todos os que dele comerem ficarão impuros. Esse pão será exclusivamente para eles; não entrará na Casa do Senhor ."

[[v28-9-5]]

^<<v28-9-5,5>>^ "O que vocês farão no dia da solenidade e no dia da festa do Senhor ?

[[v28-9-6]]

^<<v28-9-6,6>>^ Porque eis que eles fugiram por causa da destruição. O Egito os reunirá, e Mênfis os sepultará. Os seus tesouros de prata ficarão para as urtigas; espinhos tomarão conta das suas moradas."

[[v28-9-7]]

^<<v28-9-7,7>>^ "Chegaram os dias do castigo, chegaram os dias da retribuição. Israel ficará sabendo. O profeta é um tolo, e o homem de espírito é um louco, por causa da abundância da sua iniquidade, ó Israel, e do seu imenso ódio.

[[v28-9-8]]

^<<v28-9-8,8>>^ O profeta é sentinela contra Efraim, ao lado de meu Deus, mas o laço do passarinheiro se encontra em todos os seus caminhos, e inimizade no templo do seu Deus.

[[v28-9-9]]

^<<v28-9-9,9>>^ Eles se afundaram na corrupção, como nos dias de Gibeá. O Senhor  se lembrará das suas injustiças e castigará os pecados que eles cometeram."

[[v28-9-10]]

^<<v28-9-10,10>>^ "Encontrei Israel como uvas no deserto; vi os pais de vocês como as primícias da figueira nova. Mas eles foram para Baal-Peor, consagraram-se à vergonhosa idolatria e se tornaram tão abomináveis como aquilo que amaram.

[[v28-9-11]]

^<<v28-9-11,11>>^ Quanto a Efraim, a sua glória voará como ave; não haverá nascimento, nem gravidez, nem concepção.

[[v28-9-12]]

^<<v28-9-12,12>>^ Ainda que venham a criar os seus filhos, eu os privarei deles, para que não fique nem um sequer. Ai deles, quando deles eu me afastar!

[[v28-9-13]]

^<<v28-9-13,13>>^ Aos meus olhos, Efraim era como Tiro, plantado num lugar agradável; mas Efraim levará os seus filhos ao matador.

[[v28-9-14]]

^<<v28-9-14,14>>^ Dá-lhes, ó Senhor ! O que lhes darás? Dá-lhes um ventre estéril e seios sem leite."

[[v28-9-15]]

^<<v28-9-15,15>>^ "Toda a maldade deles se acha em Gilgal; foi ali que comecei a odiá-los. Por causa da maldade das suas ações, eu os expulsarei da minha casa. Não os amarei mais. Todos os seus príncipes são rebeldes."

[[v28-9-16]]

^<<v28-9-16,16>>^ "Efraim está ferido. Secaram-se as suas raízes; não dará fruto. E mesmo que as mulheres voltem a dar à luz, eu matarei esses filhos queridos.

[[v28-9-17]]

^<<v28-9-17,17>>^ O meu Deus os rejeitará, porque não lhe dão ouvidos; e andarão sem rumo entre as nações."

'''

xref:028-oseias/028-oseias-008.adoc#v28-8-0[&#60; Capítulo Anterior] | <<v28-9-0,Topo>> | xref:028-oseias/028-oseias-010.adoc#v28-10-0[Próximo Capítulo &#62;]