include::./index.adoc[]

[[v28-6-0]]
=== Oséias, 6
// naa ?, NAA - Nova Almeida Atualizada

[[v28-6-1]]

^<<v28-6-1,1>>^ "Venham e voltemos para o Senhor ! Porque ele nos despedaçou, mas vai nos curar; ele nos feriu, mas vai atar as feridas.

[[v28-6-2]]

^<<v28-6-2,2>>^ Depois de dois dias, nos dará vida; ao terceiro dia, nos ressuscitará, e viveremos diante dele.

[[v28-6-3]]

^<<v28-6-3,3>>^ Conheçamos e prossigamos em conhecer o Senhor ! Como o amanhecer, a sua vinda é certa; ele descerá sobre nós como a chuva, como chuva fora de época que rega a terra."

[[v28-6-4]]

^<<v28-6-4,4>>^ "Que farei com você, Efraim? Que farei com você, Judá? Porque o amor de vocês é como a névoa da manhã e como o orvalho da madrugada, que logo desaparece.

[[v28-6-5]]

^<<v28-6-5,5>>^ Por isso, os abati por meio dos profetas; pela palavra da minha boca, os matei; e os meus juízos sairão como a luz.

[[v28-6-6]]

^<<v28-6-6,6>>^ Pois quero misericórdia, e não sacrifício; conhecimento de Deus, mais do que holocaustos."

[[v28-6-7]]

^<<v28-6-7,7>>^ "Mas eles transgrediram a aliança, como Adão; eles foram infiéis a mim.

[[v28-6-8]]

^<<v28-6-8,8>>^ Gileade é a cidade dos que praticam a injustiça, manchada de sangue.

[[v28-6-9]]

^<<v28-6-9,9>>^ Como bandos de assaltantes que espreitam alguém, assim é a companhia dos sacerdotes, pois matam no caminho para Siquém; praticam perversidades.

[[v28-6-10]]

^<<v28-6-10,10>>^ Vejo uma coisa horrenda na casa de Israel: ali está a prostituição de Efraim; Israel se contaminou."

[[v28-6-11]]

^<<v28-6-11,11>>^ "Também você, Judá, será ceifado, quando eu remover o cativeiro do meu povo.

'''

xref:028-oseias/028-oseias-005.adoc#v28-5-0[&#60; Capítulo Anterior] | <<v28-6-0,Topo>> | xref:028-oseias/028-oseias-007.adoc#v28-7-0[Próximo Capítulo &#62;]