include::./index.adoc[]

[[v28-5-0]]
=== Oséias, 5
// naa ?, NAA - Nova Almeida Atualizada

[[v28-5-1]]

^<<v28-5-1,1>>^ "Ouçam isto, sacerdotes! Fique atenta, ó casa de Israel! Dê ouvidos, ó casa do rei! Porque a sentença é contra vocês! Pois vocês foram um laço em Mispa e uma rede estendida sobre o Tabor.

[[v28-5-2]]

^<<v28-5-2,2>>^ Os rebeldes se aprofundaram na matança, mas eu castigarei todos eles."

[[v28-5-3]]

^<<v28-5-3,3>>^ "Eu conheço Efraim, e Israel não me está oculto. Porque você, Efraim, se prostituiu, e Israel está contaminado.

[[v28-5-4]]

^<<v28-5-4,4>>^ O que eles fazem não lhes permitem voltar para o seu Deus, porque um espírito de prostituição está no meio deles, e não conhecem o Senhor ."

[[v28-5-5]]

^<<v28-5-5,5>>^ "A arrogância de Israel abertamente dá testemunho contra eles; Israel e Efraim cairão por causa da sua iniquidade, e Judá cairá juntamente com eles.

[[v28-5-6]]

^<<v28-5-6,6>>^ Com os seus rebanhos e o seu gado irão em busca do Senhor , mas não o acharão; ele se afastou deles.

[[v28-5-7]]

^<<v28-5-7,7>>^ Foram infiéis ao Senhor , porque tiveram filhos bastardos; agora a Festa da Lua Nova os consumirá com as suas plantações."

[[v28-5-8]]

^<<v28-5-8,8>>^ "Toquem a trombeta em Gibeá e façam soar o alarme em Ramá! Comecem a gritar em Bete-Áven! Cuidado, Benjamim!

[[v28-5-9]]

^<<v28-5-9,9>>^ Efraim se tornará em desolação no dia do castigo; entre as tribos de Israel, tornei conhecido o que se cumprirá.

[[v28-5-10]]

^<<v28-5-10,10>>^ Os príncipes de Judá são como os que mudam os marcos; derramarei o meu furor sobre eles como água.

[[v28-5-11]]

^<<v28-5-11,11>>^ Efraim está oprimido e esmagado pelo juízo, porque preferiu seguir a vaidade.

[[v28-5-12]]

^<<v28-5-12,12>>^ Portanto, para Efraim eu serei como a traça e para a casa de Judá, como a podridão."

[[v28-5-13]]

^<<v28-5-13,13>>^ "Quando Efraim viu a sua enfermidade e Judá notou a sua ferida, Efraim se dirigiu à Assíria e enviou mensageiros ao grande rei. Mas ele não tem condições de curá-los, nem de sarar a sua ferida.

[[v28-5-14]]

^<<v28-5-14,14>>^ Porque para Efraim eu serei como um leão, e para a casa de Judá, como um leãozinho. Eu, eu mesmo, os despedaçarei e depois irei embora; vou arrastá-los comigo, e não haverá quem possa livrá-los."

[[v28-5-15]]

^<<v28-5-15,15>>^ "Irei e voltarei para o meu lugar, até que se reconheçam culpados e busquem a minha face; estando angustiados, eles me buscarão ansiosamente."

'''

xref:028-oseias/028-oseias-004.adoc#v28-4-0[&#60; Capítulo Anterior] | <<v28-5-0,Topo>> | xref:028-oseias/028-oseias-006.adoc#v28-6-0[Próximo Capítulo &#62;]