include::./index.adoc[]

[[v28-8-0]]
=== Oséias, 8
// naa ?, NAA - Nova Almeida Atualizada

[[v28-8-1]]

^<<v28-8-1,1>>^ "Toque a trombeta! Ele vem como a águia contra a casa do Senhor , porque transgrediram a minha aliança e se rebelaram contra a minha lei.

[[v28-8-2]]

^<<v28-8-2,2>>^ Eles me invocam, dizendo: ‘Nosso Deus! Nós, Israel, te conhecemos.’

[[v28-8-3]]

^<<v28-8-3,3>>^ Mas Israel rejeitou o que é bom; o inimigo o perseguirá."

[[v28-8-4]]

^<<v28-8-4,4>>^ "Eles estabeleceram reis, mas não da minha parte; constituíram príncipes, mas eu não o soube. Com a sua prata e com o seu ouro fizeram ídolos para si, para a sua própria destruição.

[[v28-8-5]]

^<<v28-8-5,5>>^ O seu bezerro, ó Samaria, é rejeitado. A minha ira se acende contra eles. Até quando eles serão incapazes da inocência?

[[v28-8-6]]

^<<v28-8-6,6>>^ Porque esse bezerro vem de Israel; é obra de artífice, não é Deus. Esse bezerro de Samaria será quebrado em pedaços."

[[v28-8-7]]

^<<v28-8-7,7>>^ "Porque semeiam ventos e colherão tempestades. O cereal que estiver por ser colhido não terá espigas, e não haverá farinha; e, se houver, os estrangeiros a comerão.

[[v28-8-8]]

^<<v28-8-8,8>>^ Israel foi devorado. Agora está entre as nações como coisa de que ninguém se agrada.

[[v28-8-9]]

^<<v28-8-9,9>>^ Porque foram pedir ajuda à Assíria, como um jumento selvagem que segue o seu próprio rumo. Efraim contratou amantes.

[[v28-8-10]]

^<<v28-8-10,10>>^ Todavia, ainda que contratem amantes entre as nações para socorrê-los, eu os reunirei para juízo. Já começaram a definhar sob a opressão do poderoso rei."

[[v28-8-11]]

^<<v28-8-11,11>>^ "Visto que Efraim multiplicou altares para pecar, estes altares lhe serviram para pecar.

[[v28-8-12]]

^<<v28-8-12,12>>^ Embora eu lhe escreva a minha lei em dez mil preceitos, estes seriam tidos como coisa estranha.

[[v28-8-13]]

^<<v28-8-13,13>>^ Amam o sacrifício; por isso, sacrificam, pois gostam de carne e a comem, mas o Senhor  não os aceita. Agora ele se lembrará da iniquidade deles e castigará os pecados que cometeram. Vou mandá-los de volta para o Egito!

[[v28-8-14]]

^<<v28-8-14,14>>^ Porque Israel se esqueceu do seu Criador e edificou palácios, e Judá multiplicou cidades fortificadas; mas eu enviarei fogo contra as suas cidades, fogo que consumirá os seus palácios."

'''

xref:028-oseias/028-oseias-007.adoc#v28-7-0[&#60; Capítulo Anterior] | <<v28-8-0,Topo>> | xref:028-oseias/028-oseias-009.adoc#v28-9-0[Próximo Capítulo &#62;]