include::./index.adoc[]

[[v28-13-0]]
=== Oséias, 13
// naa ?, NAA - Nova Almeida Atualizada

[[v28-13-1]]

^<<v28-13-1,1>>^ "Quando Efraim falava, havia tremor; foi exaltado em Israel. Mas ele se fez culpado por causa de Baal e morreu.

[[v28-13-2]]

^<<v28-13-2,2>>^ Agora, pecam cada vez mais, e da sua prata fazem imagens de fundição, ídolos segundo o seu conceito, todos obra de artífices, e dizem: ‘Ofereçam sacrifícios a eles.’ Chegam até a beijar esses bezerros!

[[v28-13-3]]

^<<v28-13-3,3>>^ Por isso, serão como a névoa da manhã, como o orvalho da madrugada, que logo desaparece, como a palha que o vento leva da eira e como a fumaça que sai por uma janela."

[[v28-13-4]]

^<<v28-13-4,4>>^ "Mas eu sou o Senhor , seu Deus, desde a terra do Egito. Portanto, vocês não conhecerão outro deus além de mim, porque não há salvador, a não ser eu.

[[v28-13-5]]

^<<v28-13-5,5>>^ Eu os conheci no deserto, em terra muito seca.

[[v28-13-6]]

^<<v28-13-6,6>>^ Quando tinham comida, eles se fartaram, e, uma vez fartos, seu coração se encheu de orgulho; por isso, se esqueceram de mim.

[[v28-13-7]]

^<<v28-13-7,7>>^ Portanto, serei para eles como um leão; como um leopardo, ficarei espreitando no caminho.

[[v28-13-8]]

^<<v28-13-8,8>>^ Como ursa, roubada dos seus filhotes, eu os atacarei e lhes rasgarei o peito. Como leão, eu os devorarei ali mesmo; como um animal selvagem, os farei em pedaços."

[[v28-13-9]]

^<<v28-13-9,9>>^ "A sua ruína, ó Israel, vem de você, e só de mim, o seu socorro.

[[v28-13-10]]

^<<v28-13-10,10>>^ Onde está, agora, o seu rei, para que o salve em todas as suas cidades? E os seus juízes, dos quais você disse: ‘Dê-me um rei e príncipes’?

[[v28-13-11]]

^<<v28-13-11,11>>^ Eu lhe dei um rei na minha ira, e o tirei de você no meu furor."

[[v28-13-12]]

^<<v28-13-12,12>>^ "As iniquidades de Efraim estão atadas juntas; o seu pecado está armazenado.

[[v28-13-13]]

^<<v28-13-13,13>>^ As dores de parto virão, mas ele é filho insensato; porque será tempo de nascer, mas ele não estará no lugar por onde deve vir ao mundo."

[[v28-13-14]]

^<<v28-13-14,14>>^ "Eu os remirei do poder do inferno e os resgatarei da morte. Onde estão, ó morte, as suas pragas? Onde está, ó inferno, a sua destruição? Meus olhos estarão fechados para a compaixão."

[[v28-13-15]]

^<<v28-13-15,15>>^ "Ainda que Efraim dê frutos entre os irmãos, virá o vento leste, vento do Senhor , subindo do deserto; ele secará a sua nascente e estancará a sua fonte; ele saqueará o tesouro de todas as coisas preciosas.

[[v28-13-16]]

^<<v28-13-16,16>>^ Samaria levará sobre si a sua culpa, porque se rebelou contra o seu Deus; cairá à espada, seus filhos serão despedaçados, e as suas mulheres grávidas serão abertas pelo meio."

'''

xref:028-oseias/028-oseias-012.adoc#v28-12-0[&#60; Capítulo Anterior] | <<v28-13-0,Topo>> | xref:028-oseias/028-oseias-014.adoc#v28-14-0[Próximo Capítulo &#62;]