include::./index.adoc[]

[[v28-14-0]]
=== Oséias, 14
// naa ?, NAA - Nova Almeida Atualizada

[[v28-14-1]]

^<<v28-14-1,1>>^ "Israel, volte para o Senhor , seu Deus, porque você caiu por causa dos seus pecados.

[[v28-14-2]]

^<<v28-14-2,2>>^ Tragam palavras de arrependimento e convertam-se ao Senhor , dizendo: ‘Perdoa toda a nossa iniquidade, aceita o que é bom e, em vez de novilhos, os sacrifícios dos nossos lábios.

[[v28-14-3]]

^<<v28-14-3,3>>^ A Assíria não nos salvará. Não iremos montados em cavalos e não mais diremos às obras das nossas mãos que elas são o nosso Deus. Porque só em ti o órfão encontra misericórdia.’"

[[v28-14-4]]

^<<v28-14-4,4>>^ "Vou curar a rebeldia deles. Vou amá-los de boa vontade, porque a minha ira se afastou deles.

[[v28-14-5]]

^<<v28-14-5,5>>^ Serei para Israel como orvalho; ele florescerá como o lírio e lançará as suas raízes como o cedro do Líbano.

[[v28-14-6]]

^<<v28-14-6,6>>^ Os seus ramos se estenderão, o seu esplendor será como o da oliveira, e a sua fragrância, como a do cedro do Líbano.

[[v28-14-7]]

^<<v28-14-7,7>>^ Os que se assentavam à sua sombra voltarão; serão vivificados como o trigo e florescerão como a videira; a sua fama será como a do vinho do Líbano."

[[v28-14-8]]

^<<v28-14-8,8>>^ "Ó Efraim, que tenho eu a ver com os ídolos? Sou eu que ouço as suas orações e cuido de você! Eu sou como o cipreste verde; de mim procede o seu fruto."

[[v28-14-9]]

^<<v28-14-9,9>>^ Quem é sábio, que entenda estas coisas! Quem é inteligente, que as compreenda! Porque os caminhos do Senhor são retos, e os justos andarão neles, mas os transgressores neles cairão.

'''

xref:028-oseias/028-oseias-013.adoc#v28-13-0[&#60; Capítulo Anterior] | <<v28-14-0,Topo>> | xref:029-joel/029-joel-001.adoc#v29-1-0[Próximo Capítulo &#62;]