include::./index.adoc[]

[[v28-1-0]]
=== Oséias, 1
// naa ?, NAA - Nova Almeida Atualizada

[[v28-1-1]]

^<<v28-1-1,1>>^ Palavra do Senhor  que foi dirigida a Oseias, filho de Beeri, nos dias de Uzias, Jotão, Acaz e Ezequias, reis de Judá, e nos dias de Jeroboão, filho de Joás, rei de Israel.

[[v28-1-2]]

^<<v28-1-2,2>>^ Quando, pela primeira vez, o Senhor  falou por meio de Oseias, o Senhor  lhe disse: — Vá e case com uma prostituta, e tenha com ela filhos de uma prostituta. Porque a terra se prostituiu, desviando-se do Senhor .

[[v28-1-3]]

^<<v28-1-3,3>>^ Então Oseias foi e casou com Gômer, filha de Diblaim, que ficou grávida e lhe deu um filho.

[[v28-1-4]]

^<<v28-1-4,4>>^ E o Senhor  disse a Oseias: — Ponha nele o nome de Jezreel, porque daqui a pouco castigarei a casa de Jeú por causa do sangue derramado em Jezreel. Vou acabar com o reino da casa de Israel.

[[v28-1-5]]

^<<v28-1-5,5>>^ Naquele dia, quebrarei o arco de Israel no vale de Jezreel.

[[v28-1-6]]

^<<v28-1-6,6>>^ Gômer ficou grávida outra vez e deu à luz uma filha. Então o Senhor  disse a Oseias: — Ponha nela o nome de Lo-Ruamá, porque não voltarei a ter compaixão da casa de Israel, para lhe perdoar.

[[v28-1-7]]

^<<v28-1-7,7>>^ Porém da casa de Judá eu terei compaixão e os salvarei pelo Senhor , seu Deus. Porque não os salvarei pelo arco, nem pela espada, nem pela guerra, nem pelos cavalos, nem pelos cavaleiros.

[[v28-1-8]]

^<<v28-1-8,8>>^ Depois de ter desmamado Lo-Ruamá, Gômer ficou grávida mais uma vez e deu à luz um filho.

[[v28-1-9]]

^<<v28-1-9,9>>^ E o Senhor  disse: — Ponha nele o nome de Lo-Ami, porque vocês não são o meu povo, nem eu serei o seu Deus.

[[v28-1-10]]

^<<v28-1-10,10>>^ Todavia, o número dos filhos de Israel será como a areia do mar, que não se pode medir, nem contar. E acontecerá que, no lugar em que lhes foi dito: "Vocês não são o meu povo", ali mesmo se dirá a eles: "Vocês são filhos do Deus vivo."

[[v28-1-11]]

^<<v28-1-11,11>>^ Os filhos de Judá e os filhos de Israel serão reunidos, e constituirão sobre si uma só cabeça. Eles se levantarão da terra, porque grande será o dia de Jezreel.

'''

xref:027-daniel/027-daniel-012.adoc#v27-12-0[&#60; Capítulo Anterior] | <<v28-1-0,Topo>> | xref:028-oseias/028-oseias-002.adoc#v28-2-0[Próximo Capítulo &#62;]