include::./index.adoc[]

[[v28-12-0]]
=== Oséias, 12
// naa ?, NAA - Nova Almeida Atualizada

[[v28-12-1]]

^<<v28-12-1,1>>^ Efraim apascenta o vento e persegue o vento leste o dia inteiro. Multiplica mentiras e destruição. Faz aliança com a Assíria, mas o azeite é levado para o Egito."

[[v28-12-2]]

^<<v28-12-2,2>>^ "O Senhor  tem uma controvérsia com Judá e castigará Jacó segundo a sua conduta; ele lhe dará o que merece por seus atos.

[[v28-12-3]]

^<<v28-12-3,3>>^ No ventre, Jacó pegou no calcanhar de seu irmão; no vigor da sua idade, lutou com Deus.

[[v28-12-4]]

^<<v28-12-4,4>>^ Lutou com o anjo e venceu; chorou e pediu que o abençoasse. Em Betel, encontrou Deus, e ali Deus falou com ele.

[[v28-12-5]]

^<<v28-12-5,5>>^ O Senhor , o Deus dos Exércitos, o Senhor  é o seu nome.

[[v28-12-6]]

^<<v28-12-6,6>>^ Quanto a você, volte para o seu Deus, siga o amor e a justiça, e espere sempre no seu Deus."

[[v28-12-7]]

^<<v28-12-7,7>>^ "Como mercador que tem nas mãos uma balança desonesta e ama a opressão,

[[v28-12-8]]

^<<v28-12-8,8>>^ Efraim diz: ‘Certamente fiquei rico! Encontrei muitas riquezas! Em todos esses meus esforços, não encontrarão em mim nenhum delito, nada que seja pecado.’

[[v28-12-9]]

^<<v28-12-9,9>>^ Mas eu sou o Senhor , seu Deus, desde a terra do Egito; eu ainda os farei habitar em tendas, como nos dias da festa."

[[v28-12-10]]

^<<v28-12-10,10>>^ "Falei aos profetas e multipliquei as visões; e, pelo ministério dos profetas, propus símiles.

[[v28-12-11]]

^<<v28-12-11,11>>^ Será que há transgressão em Gileade? Eles são pura vaidade! Em Gilgal sacrificam bois; os seus altares serão como montões de pedra nos sulcos dos campos.

[[v28-12-12]]

^<<v28-12-12,12>>^ Jacó fugiu para a terra da Síria; ali Israel trabalhou para conseguir uma esposa e por ela guardou o gado.

[[v28-12-13]]

^<<v28-12-13,13>>^ Mas o Senhor , por meio de um profeta, tirou Israel do Egito e, por um profeta, cuidou do seu povo.

[[v28-12-14]]

^<<v28-12-14,14>>^ Efraim amargamente o provocou à ira; por isso, o seu Senhor fará com que ele pague pelo sangue que derramou e lhe retribuirá pelas suas afrontas."

'''

xref:028-oseias/028-oseias-011.adoc#v28-11-0[&#60; Capítulo Anterior] | <<v28-12-0,Topo>> | xref:028-oseias/028-oseias-013.adoc#v28-13-0[Próximo Capítulo &#62;]