include::./index.adoc[]

[[v28-3-0]]
=== Oséias, 3
// naa ?, NAA - Nova Almeida Atualizada

[[v28-3-1]]

^<<v28-3-1,1>>^ O Senhor  me disse: — Vá outra vez e ame uma mulher, que é amada por outro e é adúltera, assim como o Senhor  ama os filhos de Israel, embora eles olhem para outros deuses e amem bolos de passas.

[[v28-3-2]]

^<<v28-3-2,2>>^ Assim, comprei-a por quinze peças de prata e cento e cinquenta quilos de cevada.

[[v28-3-3]]

^<<v28-3-3,3>>^ E eu disse a ela: — Você vai ficar comigo por muito tempo. Você não deve se prostituir, nem se entregar a outro homem. E eu farei o mesmo em relação a você.

[[v28-3-4]]

^<<v28-3-4,4>>^ Porque os filhos de Israel ficarão por muito tempo sem rei, sem príncipe, sem sacrifício, sem coluna, sem estola sacerdotal ou ídolos do lar.

[[v28-3-5]]

^<<v28-3-5,5>>^ Depois, os filhos de Israel voltarão e buscarão o Senhor , seu Deus, e Davi, seu rei; e, nos últimos dias, tremendo, se aproximarão do Senhor  e da sua bondade.

'''

xref:028-oseias/028-oseias-002.adoc#v28-2-0[&#60; Capítulo Anterior] | <<v28-3-0,Topo>> | xref:028-oseias/028-oseias-004.adoc#v28-4-0[Próximo Capítulo &#62;]