include::./index.adoc[]

[[v41-1-0]]
=== Marcos, 1
// naa ?, NAA - Nova Almeida Atualizada

[[v41-1-1]]

^<<v41-1-1,1>>^ Princípio do evangelho de Jesus Cristo, Filho de Deus.

[[v41-1-2]]

^<<v41-1-2,2>>^ Como está escrito na profecia de Isaías: "Eis que envio o meu mensageiro adiante de você, o qual preparará o seu caminho.

[[v41-1-3]]

^<<v41-1-3,3>>^ Voz do que clama no deserto: Preparem o caminho do Senhor, endireitem as suas veredas."

[[v41-1-4]]

^<<v41-1-4,4>>^ E foi assim que João Batista apareceu no deserto, pregando batismo de arrependimento para remissão de pecados.

[[v41-1-5]]

^<<v41-1-5,5>>^ E toda a região da Judeia e todos os moradores de Jerusalém iam até ele. E, confessando os seus pecados, eram batizados por ele no rio Jordão.

[[v41-1-6]]

^<<v41-1-6,6>>^ A roupa de João era feita de pelos de camelo. Ele usava um cinto de couro e se alimentava de gafanhotos e mel silvestre.

[[v41-1-7]]

^<<v41-1-7,7>>^ E João pregava, dizendo: — Depois de mim vem aquele que é mais poderoso do que eu, do qual não sou digno de, curvando-me, desamarrar as correias das suas sandálias.

[[v41-1-8]]

^<<v41-1-8,8>>^ Eu batizei vocês com água; ele, porém, os batizará com o Espírito Santo.

[[v41-1-9]]

^<<v41-1-9,9>>^ Naqueles dias, Jesus veio de Nazaré da Galileia e foi batizado por João no rio Jordão.

[[v41-1-10]]

^<<v41-1-10,10>>^ Logo ao sair da água, Jesus viu os céus se abrindo e o Espírito descendo como pomba sobre ele.

[[v41-1-11]]

^<<v41-1-11,11>>^ Então veio uma voz dos céus, que dizia: — Você é o meu Filho amado; em você me agrado.

[[v41-1-12]]

^<<v41-1-12,12>>^ E logo o Espírito conduziu Jesus ao deserto,

[[v41-1-13]]

^<<v41-1-13,13>>^ onde ficou durante quarenta dias, sendo tentado por Satanás. Estava com as feras, e os anjos o serviam.

[[v41-1-14]]

^<<v41-1-14,14>>^ Depois de João ter sido preso, Jesus foi para a Galileia, pregando o evangelho de Deus.

[[v41-1-15]]

^<<v41-1-15,15>>^ Ele dizia: — O tempo está cumprido, e o Reino de Deus está próximo; arrependam-se e creiam no evangelho.

[[v41-1-16]]

^<<v41-1-16,16>>^ Caminhando junto ao mar da Galileia, Jesus viu os irmãos Simão e André, que lançavam a rede ao mar, porque eram pescadores.

[[v41-1-17]]

^<<v41-1-17,17>>^ Jesus lhes disse: — Venham comigo, e eu farei com que sejam pescadores de gente.

[[v41-1-18]]

^<<v41-1-18,18>>^ Então eles deixaram imediatamente as redes e o seguiram.

[[v41-1-19]]

^<<v41-1-19,19>>^ Pouco mais adiante, Jesus viu Tiago, filho de Zebedeu, e João, seu irmão, que estavam no barco consertando as redes,

[[v41-1-20]]

^<<v41-1-20,20>>^ e logo os chamou. E eles seguiram Jesus, deixando o seu pai Zebedeu no barco com os empregados.

[[v41-1-21]]

^<<v41-1-21,21>>^ Depois, entraram em Cafarnaum, e, logo no sábado, Jesus foi ensinar na sinagoga.

[[v41-1-22]]

^<<v41-1-22,22>>^ E maravilhavam-se com a sua doutrina, porque os ensinava como alguém que tem autoridade e não como os escribas.

[[v41-1-23]]

^<<v41-1-23,23>>^ E logo apareceu na sinagoga um homem possuído de espírito imundo, o qual gritou:

[[v41-1-24]]

^<<v41-1-24,24>>^ — O que você quer conosco, Jesus Nazareno? Você veio para nos destruir? Sei muito bem quem você é: o Santo de Deus!

[[v41-1-25]]

^<<v41-1-25,25>>^ Mas Jesus o repreendeu, dizendo: — Cale-se e saia desse homem.

[[v41-1-26]]

^<<v41-1-26,26>>^ Então o espírito imundo, agitando-o violentamente e gritando em alta voz, saiu dele.

[[v41-1-27]]

^<<v41-1-27,27>>^ Todos se admiraram, a ponto de perguntarem entre si: — Que é isto? Uma nova doutrina! Com autoridade ele ordena aos espíritos imundos, e eles lhe obedecem!

[[v41-1-28]]

^<<v41-1-28,28>>^ E a fama de Jesus se espalhou depressa em todas as direções, por toda a região da Galileia.

[[v41-1-29]]

^<<v41-1-29,29>>^ E, saindo da sinagoga, foram, com Tiago e João, para a casa de Simão e André.

[[v41-1-30]]

^<<v41-1-30,30>>^ A sogra de Simão estava de cama, com febre; e logo deram essa notícia a Jesus.

[[v41-1-31]]

^<<v41-1-31,31>>^ Então, aproximando-se, Jesus pegou na mão dela e fez com que ela se levantasse. A febre a deixou, e ela passou a servi-los.

[[v41-1-32]]

^<<v41-1-32,32>>^ À tarde, depois do pôr do sol, trouxeram a Jesus todos os enfermos e endemoniados.

[[v41-1-33]]

^<<v41-1-33,33>>^ Toda a cidade estava reunida à porta da casa.

[[v41-1-34]]

^<<v41-1-34,34>>^ E ele curou muitos que se achavam doentes de todo tipo de enfermidades. Também expulsou muitos demônios, não lhes permitindo que falassem, porque sabiam quem ele era.

[[v41-1-35]]

^<<v41-1-35,35>>^ Tendo-se levantado de madrugada, quando ainda estava escuro, Jesus saiu e foi para um lugar deserto, e ali orava.

[[v41-1-36]]

^<<v41-1-36,36>>^ Simão e os que estavam com ele procuraram Jesus por toda parte.

[[v41-1-37]]

^<<v41-1-37,37>>^ Quando o encontraram, lhe disseram: — Todos estão à sua procura.

[[v41-1-38]]

^<<v41-1-38,38>>^ Jesus, porém, lhes disse: — Vamos a outros lugares, aos povoados vizinhos, a fim de que eu pregue também ali, pois foi para isso que eu vim.

[[v41-1-39]]

^<<v41-1-39,39>>^ Então ele foi por toda a Galileia, pregando nas sinagogas deles e expulsando os demônios.

[[v41-1-40]]

^<<v41-1-40,40>>^ Um leproso se aproximou de Jesus e lhe pediu, de joelhos: — Se o senhor quiser, pode me purificar.

[[v41-1-41]]

^<<v41-1-41,41>>^ E Jesus, profundamente compadecido, estendeu a mão, tocou nele e disse: — Quero, sim. Fique limpo!

[[v41-1-42]]

^<<v41-1-42,42>>^ No mesmo instante, a lepra desapareceu dele, e ele ficou limpo.

[[v41-1-43]]

^<<v41-1-43,43>>^ E, advertindo-o severamente, logo o despediu.

[[v41-1-44]]

^<<v41-1-44,44>>^ E lhe disse: — Olhe! Não conte nada a ninguém, mas vá, apresente-se ao sacerdote e ofereça, pela sua purificação, o sacrifício que Moisés ordenou, para servir de testemunho ao povo.

[[v41-1-45]]

^<<v41-1-45,45>>^ Mas, tendo ele saído, começou a proclamar muitas coisas e a divulgar a notícia, a ponto de Jesus não poder mais entrar publicamente em nenhuma cidade. Por isso, permanecia fora, em lugares desertos. E de toda parte vinham ao encontro dele.

'''

xref:040-mateus/040-mateus-028.adoc#v40-28-0[&#60; Capítulo Anterior] | <<v41-1-0,Topo>> | xref:041-marcos/041-marcos-002.adoc#v41-2-0[Próximo Capítulo &#62;]