include::./index.adoc[]

[[v41-12-0]]
=== Marcos, 12
// naa ?, NAA - Nova Almeida Atualizada

[[v41-12-1]]

^<<v41-12-1,1>>^ Depois Jesus começou a falar-lhes por parábola: — Um homem plantou uma vinha. Pôs uma cerca em volta dela, construiu um lagar, edificou uma torre e arrendou a vinha a uns lavradores. Depois, ausentou-se do país.

[[v41-12-2]]

^<<v41-12-2,2>>^ No tempo da colheita, mandou um servo para que recebesse dos lavradores a sua parte dos frutos da vinha.

[[v41-12-3]]

^<<v41-12-3,3>>^ Mas os lavradores o agarraram, espancaram e o despacharam de mãos vazias.

[[v41-12-4]]

^<<v41-12-4,4>>^ De novo, enviou-lhes outro servo, e eles bateram na cabeça dele e o insultaram.

[[v41-12-5]]

^<<v41-12-5,5>>^ Mandou ainda outro servo, e a este mataram. Muitos outros lhes enviou, dos quais espancaram uns e mataram outros.

[[v41-12-6]]

^<<v41-12-6,6>>^ — Restava-lhe ainda um: o seu filho amado. Por fim, mandou o filho, pensando: "O meu filho eles respeitarão."

[[v41-12-7]]

^<<v41-12-7,7>>^ Mas os tais lavradores disseram entre si: "Este é o herdeiro; venham, vamos matá-lo, e a herança será nossa."

[[v41-12-8]]

^<<v41-12-8,8>>^ E, agarrando o filho, mataram-no e o lançaram fora da vinha.

[[v41-12-9]]

^<<v41-12-9,9>>^ — Que fará, pois, o dono da vinha? Virá, exterminará aqueles lavradores e entregará a vinha a outros.

[[v41-12-10]]

^<<v41-12-10,10>>^ Vocês ainda não leram este trecho da Escritura: "A pedra que os construtores rejeitaram, essa veio a ser a pedra angular.

[[v41-12-11]]

^<<v41-12-11,11>>^ Isto procede do Senhor e é maravilhoso aos nossos olhos"?

[[v41-12-12]]

^<<v41-12-12,12>>^ E procuravam prender Jesus, porque entenderam que ele havia contado essa parábola contra eles; mas temiam o povo. Então eles o deixaram e foram embora.

[[v41-12-13]]

^<<v41-12-13,13>>^ E enviaram a Jesus alguns dos fariseus e dos herodianos, para que o apanhassem em alguma palavra.

[[v41-12-14]]

^<<v41-12-14,14>>^ Chegando, disseram-lhe: — Mestre, sabemos que o senhor é verdadeiro e não se importa com a opinião dos outros, porque não olha a aparência das pessoas, mas, segundo a verdade, ensina o caminho de Deus; é lícito pagar imposto a César ou não? Devemos ou não devemos pagar?

[[v41-12-15]]

^<<v41-12-15,15>>^ Mas Jesus, percebendo a hipocrisia deles, respondeu: — Por que vocês estão me pondo à prova? Tragam-me um denário para que eu o veja.

[[v41-12-16]]

^<<v41-12-16,16>>^ Eles trouxeram. E Jesus lhes perguntou: — De quem é esta figura e esta inscrição? Eles responderam: — De César.

[[v41-12-17]]

^<<v41-12-17,17>>^ Então Jesus disse: — Deem a César o que é de César e a Deus o que é de Deus. E muito se admiraram dele.

[[v41-12-18]]

^<<v41-12-18,18>>^ Então alguns saduceus, que dizem não haver ressurreição, aproximaram-se de Jesus e lhe perguntaram:

[[v41-12-19]]

^<<v41-12-19,19>>^ — Mestre, Moisés nos deixou escrito que, se um homem morrer e deixar mulher sem filhos, o irmão desse homem deve casar com a viúva e gerar descendentes para o falecido.

[[v41-12-20]]

^<<v41-12-20,20>>^ Havia sete irmãos. O primeiro casou e morreu sem deixar filhos;

[[v41-12-21]]

^<<v41-12-21,21>>^ o segundo casou com a viúva e morreu, também sem deixar descendência; e o terceiro, da mesma forma.

[[v41-12-22]]

^<<v41-12-22,22>>^ E, assim, os sete não deixaram descendência. Por fim, depois de todos, morreu também a mulher.

[[v41-12-23]]

^<<v41-12-23,23>>^ Na ressurreição, quando eles ressuscitarem, de qual deles ela será a esposa? Porque os sete casaram com ela.

[[v41-12-24]]

^<<v41-12-24,24>>^ Jesus respondeu: — Será que o erro de vocês não está no fato de não conhecerem as Escrituras nem o poder de Deus?

[[v41-12-25]]

^<<v41-12-25,25>>^ Pois, quando ressuscitarem dentre os mortos, nem casarão, nem se darão em casamento, mas serão como os anjos nos céus.

[[v41-12-26]]

^<<v41-12-26,26>>^ Quanto aos mortos, que eles de fato ressuscitam, vocês nunca leram no Livro de Moisés, no trecho referente à sarça, como Deus lhe falou: "Eu sou o Deus de Abraão, o Deus de Isaque e o Deus de Jacó"?

[[v41-12-27]]

^<<v41-12-27,27>>^ Ele não é Deus de mortos, e sim de vivos. Vocês estão completamente enganados.

[[v41-12-28]]

^<<v41-12-28,28>>^ Chegando um dos escribas, que ouviu a discussão entre eles e viu que Jesus tinha dado uma boa resposta, perguntou-lhe: — Qual é o principal de todos os mandamentos?

[[v41-12-29]]

^<<v41-12-29,29>>^ Jesus respondeu: — O principal é: "Escute, ó Israel, o Senhor, nosso Deus, é o único Senhor!

[[v41-12-30]]

^<<v41-12-30,30>>^ Ame o Senhor, seu Deus, de todo o seu coração, de toda a sua alma, de todo o seu entendimento e com toda a sua força."

[[v41-12-31]]

^<<v41-12-31,31>>^ O segundo é: "Ame o seu próximo como você ama a si mesmo." Não há outro mandamento maior do que estes.

[[v41-12-32]]

^<<v41-12-32,32>>^ Então o escriba disse: — Muito bem, Mestre! E com verdade o senhor disse que ele é o único, e não há outro além dele,

[[v41-12-33]]

^<<v41-12-33,33>>^ e que amar a Deus de todo o coração e de todo o entendimento e com todas as forças e amar o próximo como a si mesmo é mais do que todos os holocaustos e sacrifícios.

[[v41-12-34]]

^<<v41-12-34,34>>^ Vendo Jesus que o escriba havia respondido sabiamente, declarou-lhe: — Você não está longe do Reino de Deus. E ninguém mais ousava fazer perguntas a Jesus.

[[v41-12-35]]

^<<v41-12-35,35>>^ Jesus, ensinando no templo, perguntou: — Como dizem os escribas que o Cristo é filho de Davi?

[[v41-12-36]]

^<<v41-12-36,36>>^ O próprio Davi falou, pelo Espírito Santo: "Disse o Senhor ao meu Senhor: ‘Sente-se à minha direita, até que eu ponha os seus inimigos debaixo dos seus pés.’"

[[v41-12-37]]

^<<v41-12-37,37>>^ — O próprio Davi chama o Cristo de Senhor; então como ele pode ser filho de Davi? E a grande multidão o ouvia com prazer.

[[v41-12-38]]

^<<v41-12-38,38>>^ E, ao ensinar, Jesus dizia: — Cuidado com os escribas, que gostam de andar com vestes talares e das saudações nas praças;

[[v41-12-39]]

^<<v41-12-39,39>>^ buscam as primeiras cadeiras nas sinagogas e os primeiros lugares nos banquetes;

[[v41-12-40]]

^<<v41-12-40,40>>^ devoram as casas das viúvas e, para o justificar, fazem longas orações. Estes sofrerão juízo muito mais severo.

[[v41-12-41]]

^<<v41-12-41,41>>^ Sentado diante da caixa de ofertas, Jesus observava como o povo lançava ali o dinheiro. Ora, muitos ricos depositavam grandes quantias.

[[v41-12-42]]

^<<v41-12-42,42>>^ Vindo, porém, uma viúva pobre, lançou duas pequenas moedas correspondentes a um quadrante.

[[v41-12-43]]

^<<v41-12-43,43>>^ E, chamando os seus discípulos, Jesus disse: — Em verdade lhes digo que esta viúva pobre lançou na caixa de ofertas mais do que todos os ofertantes.

[[v41-12-44]]

^<<v41-12-44,44>>^ Porque todos eles deram daquilo que lhes sobrava; ela, porém, da sua pobreza deu tudo o que possuía, todo o seu sustento.

'''

xref:041-marcos/041-marcos-011.adoc#v41-11-0[&#60; Capítulo Anterior] | <<v41-12-0,Topo>> | xref:041-marcos/041-marcos-013.adoc#v41-13-0[Próximo Capítulo &#62;]