include::./index.adoc[]

[[v41-9-0]]
=== Marcos, 9
// naa ?, NAA - Nova Almeida Atualizada

[[v41-9-1]]

^<<v41-9-1,1>>^ Dizia-lhes ainda: — Em verdade lhes digo que, dos que aqui se encontram, existem alguns que não passarão pela morte até que vejam ter chegado com poder o Reino de Deus.

[[v41-9-2]]

^<<v41-9-2,2>>^ Seis dias depois, Jesus tomou consigo Pedro, Tiago e João e os levou, em particular, a sós, a um alto monte. E Jesus foi transfigurado diante deles.

[[v41-9-3]]

^<<v41-9-3,3>>^ As suas roupas se tornaram resplandecentes, de um branco muito intenso, como nenhum lavandeiro no mundo as poderia alvejar.

[[v41-9-4]]

^<<v41-9-4,4>>^ E lhes apareceu Elias com Moisés, e estavam falando com Jesus.

[[v41-9-5]]

^<<v41-9-5,5>>^ Então Pedro, tomando a palavra, disse a Jesus: — Mestre, bom é estarmos aqui. Façamos três tendas: uma para o senhor, outra para Moisés e outra para Elias.

[[v41-9-6]]

^<<v41-9-6,6>>^ Pois não sabia o que dizer, por estarem eles apavorados.

[[v41-9-7]]

^<<v41-9-7,7>>^ A seguir, veio uma nuvem que os envolveu; e dela veio uma voz que dizia: — Este é o meu Filho amado; escutem o que ele diz!

[[v41-9-8]]

^<<v41-9-8,8>>^ E, de repente, olhando ao redor, não viram mais ninguém com eles, a não ser Jesus.

[[v41-9-9]]

^<<v41-9-9,9>>^ Ao descerem do monte, Jesus lhes ordenou que não divulgassem as coisas que tinham visto, até o dia em que o Filho do Homem ressuscitasse dentre os mortos.

[[v41-9-10]]

^<<v41-9-10,10>>^ Eles guardaram a recomendação, perguntando uns aos outros o que seria esse ressuscitar dentre os mortos.

[[v41-9-11]]

^<<v41-9-11,11>>^ Então perguntaram a Jesus: — Por que os escribas dizem ser necessário que Elias venha primeiro?

[[v41-9-12]]

^<<v41-9-12,12>>^ Jesus respondeu: — Elias, vindo primeiro, restaurará todas as coisas. Como, então, está escrito sobre o Filho do Homem que sofrerá muito e será desprezado?

[[v41-9-13]]

^<<v41-9-13,13>>^ Eu, porém, lhes digo que Elias já veio, e fizeram com ele tudo o que quiseram, como está escrito a respeito dele.

[[v41-9-14]]

^<<v41-9-14,14>>^ Quando eles se aproximaram dos outros discípulos, viram numerosa multidão ao redor deles e os escribas discutindo com eles.

[[v41-9-15]]

^<<v41-9-15,15>>^ E logo toda a multidão, ao ver Jesus, ficou surpresa e, correndo até ele, o saudava.

[[v41-9-16]]

^<<v41-9-16,16>>^ Então Jesus perguntou: — O que é que vocês estão discutindo com eles?

[[v41-9-17]]

^<<v41-9-17,17>>^ E um, do meio da multidão, respondeu: — Mestre, eu trouxe até o senhor o meu filho, que está possuído de um espírito mudo;

[[v41-9-18]]

^<<v41-9-18,18>>^ e este, sempre que se apossa dele, lança-o por terra, e ele espuma, range os dentes e vai definhando. Pedi aos seus discípulos que o expulsassem, mas eles não puderam.

[[v41-9-19]]

^<<v41-9-19,19>>^ Então Jesus exclamou: — Ó geração incrédula, até quando estarei com vocês? Até quando terei de suportá-los? Tragam o menino até aqui.

[[v41-9-20]]

^<<v41-9-20,20>>^ E eles o trouxeram. Quando ele viu Jesus, o espírito imediatamente agitou o menino com violência, e, caindo ele por terra, revolvia-se espumando.

[[v41-9-21]]

^<<v41-9-21,21>>^ Jesus perguntou ao pai do menino: — Há quanto tempo isso está acontecendo com ele? O pai respondeu: — Desde a infância;

[[v41-9-22]]

^<<v41-9-22,22>>^ e muitas vezes o tem lançado no fogo e na água, para o matar. Mas, se o senhor pode fazer alguma coisa, tenha compaixão de nós e ajude-nos.

[[v41-9-23]]

^<<v41-9-23,23>>^ Ao que Jesus respondeu: — "Se o senhor pode"? Tudo é possível ao que crê.

[[v41-9-24]]

^<<v41-9-24,24>>^ E imediatamente o pai do menino exclamou: — Eu creio! Ajude-me na minha falta de fé!

[[v41-9-25]]

^<<v41-9-25,25>>^ Vendo Jesus que muita gente estava se reunindo, repreendeu o espírito imundo, dizendo-lhe: — Espírito mudo e surdo, eu ordeno a você: Saia deste menino e nunca mais entre nele.

[[v41-9-26]]

^<<v41-9-26,26>>^ E ele, gritando e agitando-o muito, saiu, deixando-o como se estivesse morto, a ponto de muitos dizerem: — Morreu.

[[v41-9-27]]

^<<v41-9-27,27>>^ Mas Jesus, tomando-o pela mão, o ergueu, e ele se levantou.

[[v41-9-28]]

^<<v41-9-28,28>>^ Quando Jesus entrou em casa, os seus discípulos lhe perguntaram em particular: — Por que nós não pudemos expulsá-lo?

[[v41-9-29]]

^<<v41-9-29,29>>^ Jesus respondeu: — Esse tipo de espírito só pode ser expulso por meio de oração.

[[v41-9-30]]

^<<v41-9-30,30>>^ E, tendo saído dali, passavam pela Galileia, e Jesus não queria que ninguém o soubesse,

[[v41-9-31]]

^<<v41-9-31,31>>^ porque ensinava os seus discípulos e lhes dizia: — O Filho do Homem será entregue nas mãos dos homens, e estes o matarão; mas, três dias depois da sua morte, ressuscitará.

[[v41-9-32]]

^<<v41-9-32,32>>^ Eles, porém, não compreendiam isto e tinham medo de perguntar.

[[v41-9-33]]

^<<v41-9-33,33>>^ Chegaram, então, a Cafarnaum. Estando em casa, Jesus perguntou aos discípulos: — Sobre o que vocês estavam discutindo no caminho?

[[v41-9-34]]

^<<v41-9-34,34>>^ Mas eles se calaram, porque, no caminho, tinham discutido entre si sobre quem era o maior.

[[v41-9-35]]

^<<v41-9-35,35>>^ E Jesus, assentando-se, chamou os doze e lhes disse: — Se alguém quer ser o primeiro, será o último e servo de todos.

[[v41-9-36]]

^<<v41-9-36,36>>^ Trazendo uma criança, colocou-a no meio deles e, tomando-a nos braços, disse-lhes:

[[v41-9-37]]

^<<v41-9-37,37>>^ — Quem receber uma criança, tal como esta, em meu nome, recebe a mim; e quem receber a mim, não é a mim que recebe, mas aquele que me enviou.

[[v41-9-38]]

^<<v41-9-38,38>>^ João disse a Jesus: — Mestre, vimos um homem que expulsava demônios em seu nome, mas nós o proibimos de fazer isso, porque não nos seguia.

[[v41-9-39]]

^<<v41-9-39,39>>^ Mas Jesus respondeu: — Não o proíbam, porque não há ninguém que faça milagre em meu nome e, logo a seguir, possa falar mal de mim.

[[v41-9-40]]

^<<v41-9-40,40>>^ Pois quem não é contra nós é a favor de nós.

[[v41-9-41]]

^<<v41-9-41,41>>^ Pois aquele que lhes der de beber um copo de água, em meu nome, porque vocês são de Cristo, em verdade lhes digo que de modo nenhum perderá a sua recompensa.

[[v41-9-42]]

^<<v41-9-42,42>>^ — E, se alguém fizer tropeçar um destes pequeninos que creem em mim, seria melhor para esse que uma grande pedra de moinho fosse pendurada ao seu pescoço e fosse jogado no mar.

[[v41-9-43]]

^<<v41-9-43,43>>^ E, se a sua mão leva você a tropeçar, corte-a; pois é melhor você entrar aleijado na vida do que, tendo as duas mãos, ir para o inferno, para o fogo que nunca se apaga

[[v41-9-44]]

^<<v41-9-44,44>>^ &#91;onde não lhes morre o verme, nem o fogo se apaga&#93;.

[[v41-9-45]]

^<<v41-9-45,45>>^ E, se o seu pé leva você a tropeçar, corte-o; pois é melhor você entrar na vida aleijado do que, tendo os dois pés, ser lançado no inferno

[[v41-9-46]]

^<<v41-9-46,46>>^ &#91;onde não lhes morre o verme, nem o fogo se apaga&#93;.

[[v41-9-47]]

^<<v41-9-47,47>>^ E, se um dos seus olhos leva você a tropeçar, arranque-o; pois é melhor você entrar no Reino de Deus com um olho só do que, tendo os dois, ser lançado no inferno,

[[v41-9-48]]

^<<v41-9-48,48>>^ onde não lhes morre o verme, nem o fogo se apaga.

[[v41-9-49]]

^<<v41-9-49,49>>^ — Porque cada um será salgado com fogo.

[[v41-9-50]]

^<<v41-9-50,50>>^ O sal é bom; mas, se o sal vier a se tornar insípido, como lhe restaurar o sabor? Tenham sal em vocês mesmos e paz uns com os outros.

'''

xref:041-marcos/041-marcos-008.adoc#v41-8-0[&#60; Capítulo Anterior] | <<v41-9-0,Topo>> | xref:041-marcos/041-marcos-010.adoc#v41-10-0[Próximo Capítulo &#62;]