include::./index.adoc[]

[[v41-13-0]]
=== Marcos, 13
// naa ?, NAA - Nova Almeida Atualizada

[[v41-13-1]]

^<<v41-13-1,1>>^ Quando Jesus estava saindo do templo, um dos seus discípulos lhe disse: — Mestre! Que pedras, que construções!

[[v41-13-2]]

^<<v41-13-2,2>>^ Mas Jesus respondeu: — Você está vendo estas grandes construções? Não ficará aqui pedra sobre pedra que não seja derrubada.

[[v41-13-3]]

^<<v41-13-3,3>>^ Jesus estava sentado no monte das Oliveiras, diante do templo, quando Pedro, Tiago, João e André lhe perguntaram em particular:

[[v41-13-4]]

^<<v41-13-4,4>>^ — Diga-nos quando essas coisas vão acontecer e que sinal haverá quando todas elas estiverem para se cumprir.

[[v41-13-5]]

^<<v41-13-5,5>>^ Então Jesus começou a dizer-lhes: — Tenham cuidado para que ninguém os engane.

[[v41-13-6]]

^<<v41-13-6,6>>^ Muitos virão em meu nome, dizendo: "Sou eu"; e enganarão a muitos.

[[v41-13-7]]

^<<v41-13-7,7>>^ Quando vocês ouvirem falar de guerras e rumores de guerras, não se assustem; é necessário que isso aconteça, mas ainda não é o fim.

[[v41-13-8]]

^<<v41-13-8,8>>^ Porque nação se levantará contra nação, e reino, contra reino. Haverá terremotos em vários lugares e também fomes. Essas coisas são o princípio das dores.

[[v41-13-9]]

^<<v41-13-9,9>>^ — Estejam de sobreaviso, porque as pessoas os entregarão aos tribunais e às sinagogas. Vocês serão açoitados e, por minha causa, serão levados à presença de governadores e reis, para lhes servir de testemunho.

[[v41-13-10]]

^<<v41-13-10,10>>^ Mas é necessário que primeiro o evangelho seja pregado a todas as nações.

[[v41-13-11]]

^<<v41-13-11,11>>^ — Quando, pois, levarem vocês para os entregar, não se preocupem com o que irão dizer, mas digam o que lhes for concedido naquela hora. Porque não são vocês que estão falando, mas o Espírito Santo.

[[v41-13-12]]

^<<v41-13-12,12>>^ Um irmão entregará à morte outro irmão, e o pai entregará o filho. Haverá filhos que se levantarão contra os seus pais e os matarão.

[[v41-13-13]]

^<<v41-13-13,13>>^ Todos odiarão vocês por causa do meu nome; aquele, porém, que ficar firme até o fim, esse será salvo.

[[v41-13-14]]

^<<v41-13-14,14>>^ — Quando, pois, vocês virem o abominável da desolação situado onde não deve estar (quem lê entenda), então os que estiverem na Judeia fujam para os montes.

[[v41-13-15]]

^<<v41-13-15,15>>^ Quem estiver no terraço não desça nem entre para tirar de casa alguma coisa.

[[v41-13-16]]

^<<v41-13-16,16>>^ E quem estiver no campo não volte atrás para buscar a sua capa.

[[v41-13-17]]

^<<v41-13-17,17>>^ Ai das que estiverem grávidas e das que amamentarem naqueles dias!

[[v41-13-18]]

^<<v41-13-18,18>>^ Orem para que isso não aconteça no inverno.

[[v41-13-19]]

^<<v41-13-19,19>>^ Porque aqueles dias serão de tamanha tribulação, como nunca houve desde o princípio do mundo criado por Deus até agora e nunca jamais haverá.

[[v41-13-20]]

^<<v41-13-20,20>>^ Se o Senhor não tivesse abreviado aqueles dias, ninguém seria salvo. Mas, por causa dos eleitos que ele escolheu, Deus abreviou tais dias.

[[v41-13-21]]

^<<v41-13-21,21>>^ Então, se alguém disser a vocês: "Olhem! Aqui está o Cristo!" ou: "Olhem! Ali está ele!", não acreditem.

[[v41-13-22]]

^<<v41-13-22,22>>^ Porque surgirão falsos cristos e falsos profetas, operando sinais e prodígios, para enganar, se possível, os próprios eleitos.

[[v41-13-23]]

^<<v41-13-23,23>>^ Estejam de sobreaviso; tudo isso tenho predito a vocês.

[[v41-13-24]]

^<<v41-13-24,24>>^ — Mas, naqueles dias, após a referida tribulação, o sol escurecerá, a lua não dará a sua claridade,

[[v41-13-25]]

^<<v41-13-25,25>>^ as estrelas cairão do firmamento e os poderes dos céus serão abalados.

[[v41-13-26]]

^<<v41-13-26,26>>^ Então verão o Filho do Homem vindo nas nuvens, com grande poder e glória.

[[v41-13-27]]

^<<v41-13-27,27>>^ E então ele enviará os anjos e reunirá os seus escolhidos dos quatro ventos, da extremidade da terra até a extremidade do céu.

[[v41-13-28]]

^<<v41-13-28,28>>^ — Aprendam, pois, a parábola da figueira: quando já os seus ramos se renovam e as folhas brotam, vocês sabem que o verão está próximo.

[[v41-13-29]]

^<<v41-13-29,29>>^ Assim, também vocês, quando virem acontecer essas coisas, saibam que está próximo, às portas.

[[v41-13-30]]

^<<v41-13-30,30>>^ Em verdade lhes digo que não passará esta geração sem que tudo isto aconteça.

[[v41-13-31]]

^<<v41-13-31,31>>^ Passará o céu e a terra, porém as minhas palavras não passarão.

[[v41-13-32]]

^<<v41-13-32,32>>^ — Mas a respeito daquele dia ou da hora ninguém sabe, nem os anjos no céu, nem o Filho, senão o Pai.

[[v41-13-33]]

^<<v41-13-33,33>>^ — Estejam de sobreaviso e vigiem, porque vocês não sabem quando será o tempo.

[[v41-13-34]]

^<<v41-13-34,34>>^ É como um homem que, ausentando-se do país, deixa a sua casa, dá autoridade aos seus servos, a cada um a sua obrigação, e ao porteiro ordena que vigie.

[[v41-13-35]]

^<<v41-13-35,35>>^ Portanto, vigiem, porque vocês não sabem quando virá o dono da casa: se à tarde, se à meia-noite, se ao cantar do galo, se pela manhã;

[[v41-13-36]]

^<<v41-13-36,36>>^ para que, vindo ele inesperadamente, não encontre vocês dormindo.

[[v41-13-37]]

^<<v41-13-37,37>>^ O que, porém, digo a vocês, digo a todos: vigiem!

'''

xref:041-marcos/041-marcos-012.adoc#v41-12-0[&#60; Capítulo Anterior] | <<v41-13-0,Topo>> | xref:041-marcos/041-marcos-014.adoc#v41-14-0[Próximo Capítulo &#62;]