include::./index.adoc[]

[[v41-11-0]]
=== Marcos, 11
// naa ?, NAA - Nova Almeida Atualizada

[[v41-11-1]]

^<<v41-11-1,1>>^ Quando se aproximavam de Jerusalém, de Betfagé e Betânia, junto ao monte das Oliveiras, Jesus enviou dois dos seus discípulos

[[v41-11-2]]

^<<v41-11-2,2>>^ e disse-lhes: — Vão até a aldeia que está diante de vocês e logo, ao entrar, encontrarão preso um jumentinho, o qual ainda ninguém montou; desprendam o jumentinho e tragam aqui.

[[v41-11-3]]

^<<v41-11-3,3>>^ Se alguém perguntar: "Por que estão fazendo isso?", respondam: "O Senhor precisa dele e logo o mandará de volta para cá."

[[v41-11-4]]

^<<v41-11-4,4>>^ Então foram e acharam o jumentinho preso, junto ao portão, do lado de fora, na rua, e o desprenderam.

[[v41-11-5]]

^<<v41-11-5,5>>^ Alguns dos que ali estavam reclamaram: — O que estão fazendo, soltando o jumentinho?

[[v41-11-6]]

^<<v41-11-6,6>>^ Eles, porém, responderam conforme as instruções de Jesus. Então os deixaram ir.

[[v41-11-7]]

^<<v41-11-7,7>>^ Levaram o jumentinho a Jesus, puseram as suas capas sobre o animal, e Jesus montou nele.

[[v41-11-8]]

^<<v41-11-8,8>>^ Muitos estenderam as suas capas no caminho, e outros espalharam ramos que tinham cortado nos campos.

[[v41-11-9]]

^<<v41-11-9,9>>^ Tanto os que iam adiante dele como os que o seguiam clamavam: "Hosana! Bendito o que vem em nome do Senhor!

[[v41-11-10]]

^<<v41-11-10,10>>^ Bendito o Reino que vem, o reino de Davi, nosso pai! Hosana nas maiores alturas!"

[[v41-11-11]]

^<<v41-11-11,11>>^ E Jesus entrou em Jerusalém, no templo. E, tendo observado tudo, como já era tarde, saiu para Betânia com os doze.

[[v41-11-12]]

^<<v41-11-12,12>>^ No dia seguinte, quando saíram de Betânia, Jesus teve fome.

[[v41-11-13]]

^<<v41-11-13,13>>^ E, vendo de longe uma figueira com folhas, foi ver se nela acharia alguma coisa. Aproximando-se dela, nada achou, a não ser folhas; porque não era tempo de figos.

[[v41-11-14]]

^<<v41-11-14,14>>^ Então Jesus disse à figueira: — Nunca mais alguém coma dos seus frutos! E os discípulos de Jesus ouviram isto.

[[v41-11-15]]

^<<v41-11-15,15>>^ E foram para Jerusalém. Quando Jesus entrou no templo, começou a expulsar os que ali vendiam e compravam. Derrubou as mesas dos cambistas e as cadeiras dos que vendiam pombas,

[[v41-11-16]]

^<<v41-11-16,16>>^ e não permitia que alguém atravessasse o templo carregando algum objeto.

[[v41-11-17]]

^<<v41-11-17,17>>^ Também os ensinava e dizia: — Não é isso que está escrito: "A minha casa será chamada ‘Casa de Oração’ para todas as nações"? Mas vocês fizeram dela um covil de salteadores.

[[v41-11-18]]

^<<v41-11-18,18>>^ E os principais sacerdotes e escribas ouviram isso e procuravam uma maneira de matar Jesus, pois o temiam, porque toda a multidão se maravilhava de sua doutrina.

[[v41-11-19]]

^<<v41-11-19,19>>^ Em vindo a tarde, Jesus e os discípulos saíram da cidade.

[[v41-11-20]]

^<<v41-11-20,20>>^ E, passando eles pela manhã, viram que a figueira estava seca desde a raiz.

[[v41-11-21]]

^<<v41-11-21,21>>^ Então Pedro, lembrando-se, falou: — Mestre, eis que a figueira que o senhor amaldiçoou ficou seca.

[[v41-11-22]]

^<<v41-11-22,22>>^ Ao que Jesus lhes disse: — Tenham fé em Deus.

[[v41-11-23]]

^<<v41-11-23,23>>^ Porque em verdade lhes digo que, se alguém disser a este monte: "Levante-se e jogue-se no mar", e não duvidar no seu coração, mas crer que se fará o que diz, assim será com ele.

[[v41-11-24]]

^<<v41-11-24,24>>^ Por isso digo a vocês que tudo o que pedirem em oração, creiam que já o receberam, e assim será com vocês.

[[v41-11-25]]

^<<v41-11-25,25>>^ E, quando estiverem orando, se tiverem alguma coisa contra alguém, perdoem, para que o Pai de vocês, que está nos céus, perdoe as ofensas de vocês.

[[v41-11-26]]

^<<v41-11-26,26>>^ &#91;Mas, se vocês não perdoarem, também o Pai de vocês, que está nos céus, não perdoará as ofensas de vocês.&#93;

[[v41-11-27]]

^<<v41-11-27,27>>^ Então regressaram para Jerusalém. E enquanto Jesus andava pelo templo, os principais sacerdotes, os escribas e os anciãos vieram ao seu encontro

[[v41-11-28]]

^<<v41-11-28,28>>^ e lhe perguntaram: — Com que autoridade você faz estas coisas? Ou quem lhe deu esta autoridade para fazer isto?

[[v41-11-29]]

^<<v41-11-29,29>>^ Jesus respondeu: — Eu vou fazer uma pergunta a vocês. Respondam, e eu lhes direi com que autoridade faço estas coisas.

[[v41-11-30]]

^<<v41-11-30,30>>^ O batismo de João era do céu ou dos homens? Respondam!

[[v41-11-31]]

^<<v41-11-31,31>>^ E eles discutiam entre si: — Se dissermos: "Do céu", ele dirá: "Então por que não acreditaram nele?"

[[v41-11-32]]

^<<v41-11-32,32>>^ Se, porém, dissermos: "Dos homens", é de temer o povo. Porque todos pensavam que João era realmente um profeta.

[[v41-11-33]]

^<<v41-11-33,33>>^ Então responderam a Jesus: — Não sabemos. E Jesus, por sua vez, lhes disse: — Então eu também não lhes digo com que autoridade faço estas coisas.

'''

xref:041-marcos/041-marcos-010.adoc#v41-10-0[&#60; Capítulo Anterior] | <<v41-11-0,Topo>> | xref:041-marcos/041-marcos-012.adoc#v41-12-0[Próximo Capítulo &#62;]