include::./index.adoc[]

[[v41-15-0]]
=== Marcos, 15
// naa ?, NAA - Nova Almeida Atualizada

[[v41-15-1]]

^<<v41-15-1,1>>^ Logo pela manhã, os principais sacerdotes entraram em conselho com os anciãos, os escribas e todo o Sinédrio; e, amarrando Jesus, levaram-no e o entregaram a Pilatos.

[[v41-15-2]]

^<<v41-15-2,2>>^ Pilatos perguntou: — Você é o rei dos judeus? Jesus respondeu: — O senhor está dizendo isso.

[[v41-15-3]]

^<<v41-15-3,3>>^ E os principais sacerdotes o acusavam de muitas coisas.

[[v41-15-4]]

^<<v41-15-4,4>>^ Então Pilatos tornou a perguntar: — Você não vai responder nada? Veja quantas acusações fazem contra você!

[[v41-15-5]]

^<<v41-15-5,5>>^ Jesus, porém, não disse mais nada, a ponto de Pilatos muito se admirar.

[[v41-15-6]]

^<<v41-15-6,6>>^ Ora, por ocasião da festa, era costume soltar ao povo um dos presos, aquele que eles pedissem.

[[v41-15-7]]

^<<v41-15-7,7>>^ Havia um, chamado Barrabás, preso com rebeldes, os quais em um tumulto haviam cometido homicídio.

[[v41-15-8]]

^<<v41-15-8,8>>^ Vindo a multidão, começou a pedir que Pilatos lhes fizesse como de costume.

[[v41-15-9]]

^<<v41-15-9,9>>^ E Pilatos lhes respondeu, dizendo: — Vocês querem que eu lhes solte o rei dos judeus?

[[v41-15-10]]

^<<v41-15-10,10>>^ Pois ele bem percebia que era por inveja que os principais sacerdotes lhe haviam entregado Jesus.

[[v41-15-11]]

^<<v41-15-11,11>>^ Mas os principais sacerdotes incitaram a multidão no sentido de que lhes soltasse, de preferência, Barrabás.

[[v41-15-12]]

^<<v41-15-12,12>>^ E Pilatos lhes perguntou: — O que, então, vocês querem que eu faça com este a quem vocês chamam de rei dos judeus?

[[v41-15-13]]

^<<v41-15-13,13>>^ Eles gritaram: — Crucifique-o!

[[v41-15-14]]

^<<v41-15-14,14>>^ Mas Pilatos lhes disse: — Que mal fez ele? Porém eles gritavam cada vez mais: — Crucifique-o!

[[v41-15-15]]

^<<v41-15-15,15>>^ Então Pilatos, querendo contentar a multidão, lhes soltou Barrabás. E, depois de mandar açoitar Jesus, entregou-o para ser crucificado.

[[v41-15-16]]

^<<v41-15-16,16>>^ Então os soldados levaram Jesus para dentro do palácio, que é o Pretório, e reuniram toda a tropa.

[[v41-15-17]]

^<<v41-15-17,17>>^ Vestiram Jesus com um manto púrpura e, tecendo uma coroa de espinhos, a puseram na cabeça dele.

[[v41-15-18]]

^<<v41-15-18,18>>^ E o saudavam, dizendo: — Salve, rei dos judeus!

[[v41-15-19]]

^<<v41-15-19,19>>^ Batiam na cabeça dele com um caniço, cuspiam nele e, pondo-se de joelhos, o adoravam.

[[v41-15-20]]

^<<v41-15-20,20>>^ Depois de terem zombado dele, tiraram-lhe o manto púrpura e o vestiram com as suas próprias roupas. Então conduziram Jesus para fora a fim de o crucificarem.

[[v41-15-21]]

^<<v41-15-21,21>>^ E obrigaram Simão Cireneu, que passava, vindo do campo, pai de Alexandre e de Rufo, a carregar a cruz de Jesus.

[[v41-15-22]]

^<<v41-15-22,22>>^ E levaram Jesus para o Gólgota, que quer dizer "Lugar da Caveira".

[[v41-15-23]]

^<<v41-15-23,23>>^ Quiseram dar-lhe para beber vinho misturado com mirra, mas Jesus não aceitou.

[[v41-15-24]]

^<<v41-15-24,24>>^ Então o crucificaram e repartiram entre si as roupas dele, tirando a sorte, para ver o que cada um levaria.

[[v41-15-25]]

^<<v41-15-25,25>>^ Eram nove horas da manhã quando o crucificaram.

[[v41-15-26]]

^<<v41-15-26,26>>^ E a inscrição com a acusação contra ele dizia: " O Rei dos Judeus ".

[[v41-15-27]]

^<<v41-15-27,27>>^ Com ele crucificaram dois ladrões, um à sua direita e outro à sua esquerda.

[[v41-15-28]]

^<<v41-15-28,28>>^ &#91;E cumpriu-se a Escritura que diz: "Com malfeitores foi contado." &#93;

[[v41-15-29]]

^<<v41-15-29,29>>^ Os que iam passando blasfemavam contra ele, balançando a cabeça e dizendo: — Ah! Você que destrói o santuário e em três dias o reedifica!

[[v41-15-30]]

^<<v41-15-30,30>>^ Salve a si mesmo, descendo da cruz!

[[v41-15-31]]

^<<v41-15-31,31>>^ De igual modo, os principais sacerdotes com os escribas, zombando, diziam entre si: — Salvou os outros, a si mesmo não pode salvar.

[[v41-15-32]]

^<<v41-15-32,32>>^ Que o Cristo, o rei de Israel, desça agora da cruz para que vejamos e creiamos. Também os que com ele foram crucificados o insultavam.

[[v41-15-33]]

^<<v41-15-33,33>>^ Chegado o meio-dia, houve trevas sobre toda a terra até as três horas da tarde.

[[v41-15-34]]

^<<v41-15-34,34>>^ E às três horas, Jesus clamou em alta voz: — Eloí, Eloí, lemá sabactani?  — Isso quer dizer: "Deus meu, Deus meu, por que me desamparaste?"

[[v41-15-35]]

^<<v41-15-35,35>>^ E alguns dos que estavam ali, ouvindo isto, diziam: — Vejam! Ele chama por Elias!

[[v41-15-36]]

^<<v41-15-36,36>>^ E um deles correu para embeber uma esponja em vinagre e, colocando-a na ponta de um caniço, deu-lhe de beber, dizendo: — Esperem! Vejamos se Elias vem tirá-lo!

[[v41-15-37]]

^<<v41-15-37,37>>^ Mas Jesus, dando um forte grito, expirou.

[[v41-15-38]]

^<<v41-15-38,38>>^ E o véu do santuário se rasgou em duas partes, de alto a baixo.

[[v41-15-39]]

^<<v41-15-39,39>>^ O centurião que estava em frente de Jesus, vendo que assim havia expirado, disse: — Verdadeiramente este homem era o Filho de Deus.

[[v41-15-40]]

^<<v41-15-40,40>>^ Estavam também ali algumas mulheres, observando de longe. Entre elas estavam Maria Madalena, Maria, mãe de Tiago, o Menor, e de José, e ainda Salomé.

[[v41-15-41]]

^<<v41-15-41,41>>^ Quando Jesus estava na Galileia, essas mulheres o acompanhavam e serviam. E, além destas, havia muitas outras que tinham ido com ele para Jerusalém.

[[v41-15-42]]

^<<v41-15-42,42>>^ Ao cair da tarde, por ser o dia da preparação, isto é, a véspera do sábado,

[[v41-15-43]]

^<<v41-15-43,43>>^ José de Arimateia, ilustre membro do Sinédrio, que também esperava o Reino de Deus, dirigiu-se ousadamente a Pilatos e pediu o corpo de Jesus.

[[v41-15-44]]

^<<v41-15-44,44>>^ Mas Pilatos admirou-se de que ele já tivesse morrido. E, tendo chamado o centurião, perguntou-lhe se havia muito que Jesus tinha morrido.

[[v41-15-45]]

^<<v41-15-45,45>>^ Após certificar-se, pela informação do comandante, cedeu o corpo a José.

[[v41-15-46]]

^<<v41-15-46,46>>^ Este, baixando o corpo da cruz, envolveu-o num lençol que tinha comprado e o depositou num túmulo que tinha sido aberto numa rocha; e rolou uma pedra para a entrada do túmulo.

[[v41-15-47]]

^<<v41-15-47,47>>^ Maria Madalena e Maria, mãe de José, observaram onde ele foi posto.

'''

xref:041-marcos/041-marcos-014.adoc#v41-14-0[&#60; Capítulo Anterior] | <<v41-15-0,Topo>> | xref:041-marcos/041-marcos-016.adoc#v41-16-0[Próximo Capítulo &#62;]