include::./index.adoc[]

[[v41-2-0]]
=== Marcos, 2
// naa ?, NAA - Nova Almeida Atualizada

[[v41-2-1]]

^<<v41-2-1,1>>^ Dias depois, Jesus entrou de novo em Cafarnaum, e logo se ouviu dizer que ele estava em casa.

[[v41-2-2]]

^<<v41-2-2,2>>^ Muitos se reuniram ali, a ponto de não haver lugar nem mesmo junto à porta. E Jesus anunciava-lhes a palavra.

[[v41-2-3]]

^<<v41-2-3,3>>^ Trouxeram-lhe, então, um paralítico, carregado por quatro homens.

[[v41-2-4]]

^<<v41-2-4,4>>^ E, não podendo aproximar-se de Jesus, por causa da multidão, removeram o telhado no ponto correspondente ao lugar onde Jesus se encontrava e, pela abertura, desceram o leito em que o paralítico estava deitado.

[[v41-2-5]]

^<<v41-2-5,5>>^ Vendo-lhes a fé, Jesus disse ao paralítico: — Filho, os seus pecados estão perdoados.

[[v41-2-6]]

^<<v41-2-6,6>>^ Alguns escribas estavam sentados ali e pensavam em seu coração:

[[v41-2-7]]

^<<v41-2-7,7>>^ — Como ele se atreve a falar assim? Isto é blasfêmia! Quem pode perdoar pecados, a não ser um, que é Deus?

[[v41-2-8]]

^<<v41-2-8,8>>^ E Jesus, percebendo imediatamente em seu espírito que eles assim pensavam, disse-lhes: — Por que vocês estão pensando essas coisas em seu coração?

[[v41-2-9]]

^<<v41-2-9,9>>^ O que é mais fácil? Dizer ao paralítico: "Os seus pecados estão perdoados", ou dizer: "Levante-se, tome o seu leito e ande"?

[[v41-2-10]]

^<<v41-2-10,10>>^ Mas isto é para que vocês saibam que o Filho do Homem tem autoridade sobre a terra para perdoar pecados. E disse ao paralítico:

[[v41-2-11]]

^<<v41-2-11,11>>^ — Eu digo a você: Levante-se, pegue o seu leito e vá para casa.

[[v41-2-12]]

^<<v41-2-12,12>>^ Ele se levantou e, no mesmo instante, pegando o leito, retirou-se à vista de todos, a ponto de todos se admirarem e darem glória a Deus, dizendo: — Jamais vimos coisa assim!

[[v41-2-13]]

^<<v41-2-13,13>>^ De novo, Jesus foi para junto do mar, e toda a multidão vinha ao encontro dele, e ele os ensinava.

[[v41-2-14]]

^<<v41-2-14,14>>^ Quando ia passando, viu Levi, filho de Alfeu, sentado na coletoria e lhe disse: — Siga-me! Ele se levantou e o seguiu.

[[v41-2-15]]

^<<v41-2-15,15>>^ Achando-se Jesus à mesa, na casa de Levi, estavam junto com ele e com os seus discípulos muitos publicanos e pecadores; porque estes eram muitos e também o seguiam.

[[v41-2-16]]

^<<v41-2-16,16>>^ Os escribas dos fariseus, vendo Jesus comer em companhia dos pecadores e publicanos, perguntavam aos discípulos dele: — Por que ele come e bebe com os publicanos e pecadores?

[[v41-2-17]]

^<<v41-2-17,17>>^ Tendo ouvido isto, Jesus lhes respondeu: — Os sãos não precisam de médico, e sim os doentes; eu não vim chamar justos, e sim pecadores.

[[v41-2-18]]

^<<v41-2-18,18>>^ Ora, os discípulos de João e os fariseus estavam jejuando. Algumas pessoas foram perguntar a Jesus: — Por que os discípulos de João e os discípulos dos fariseus jejuam, mas os seus discípulos não jejuam?

[[v41-2-19]]

^<<v41-2-19,19>>^ Jesus respondeu: — Como podem os convidados para o casamento jejuar enquanto o noivo está com eles? Durante o tempo em que o noivo estiver presente, não podem jejuar.

[[v41-2-20]]

^<<v41-2-20,20>>^ No entanto, virão dias em que o noivo lhes será tirado, e então, naquele dia, eles vão jejuar.

[[v41-2-21]]

^<<v41-2-21,21>>^ Ninguém costura um remendo de pano novo em roupa velha; porque o remendo novo tira um pedaço da roupa velha, e o buraco fica ainda maior.

[[v41-2-22]]

^<<v41-2-22,22>>^ E ninguém põe vinho novo em odres velhos, porque, se fizer isso, o vinho romperá os odres e se perdem tanto o vinho como os odres. Mas põe-se vinho novo em odres novos.

[[v41-2-23]]

^<<v41-2-23,23>>^ Aconteceu que, num sábado, Jesus atravessava as searas, e os seus discípulos, ao passar, começaram a colher espigas.

[[v41-2-24]]

^<<v41-2-24,24>>^ Então os fariseus disseram a Jesus: — Olhe! Por que eles estão fazendo o que não é lícito aos sábados?

[[v41-2-25]]

^<<v41-2-25,25>>^ Ele lhes respondeu: — Vocês nunca leram o que Davi fez quando se viu em necessidade e teve fome, ele e os seus companheiros?

[[v41-2-26]]

^<<v41-2-26,26>>^ Como entrou na Casa de Deus, no tempo do sumo sacerdote Abiatar, e comeu os pães da proposição, os quais só aos sacerdotes era lícito comer, e ainda deu esses pães aos seus companheiros?

[[v41-2-27]]

^<<v41-2-27,27>>^ E Jesus acrescentou: — O sábado foi estabelecido por causa do homem, e não o homem por causa do sábado.

[[v41-2-28]]

^<<v41-2-28,28>>^ Assim, o Filho do Homem é senhor também do sábado.

'''

xref:041-marcos/041-marcos-001.adoc#v41-1-0[&#60; Capítulo Anterior] | <<v41-2-0,Topo>> | xref:041-marcos/041-marcos-003.adoc#v41-3-0[Próximo Capítulo &#62;]