include::./index.adoc[]

[[v41-16-0]]
=== Marcos, 16
// naa ?, NAA - Nova Almeida Atualizada

[[v41-16-1]]

^<<v41-16-1,1>>^ Passado o sábado, Maria Madalena, Maria, mãe de Tiago, e Salomé compraram óleos aromáticos para ungir o corpo de Jesus.

[[v41-16-2]]

^<<v41-16-2,2>>^ E, bem cedo, no primeiro dia da semana, ao nascer do sol, foram ao túmulo.

[[v41-16-3]]

^<<v41-16-3,3>>^ Diziam umas às outras: — Quem nos removerá a pedra da entrada do túmulo?

[[v41-16-4]]

^<<v41-16-4,4>>^ E, olhando, viram que a pedra já estava removida. É que a pedra era muito grande.

[[v41-16-5]]

^<<v41-16-5,5>>^ Entrando no túmulo, viram um jovem sentado ao lado direito, vestido de branco, e ficaram atemorizadas.

[[v41-16-6]]

^<<v41-16-6,6>>^ Ele, porém, lhes disse: — Não tenham medo! Vocês procuram Jesus, o Nazareno, que foi crucificado; ele ressuscitou, não está aqui; vejam o lugar onde o tinham colocado.

[[v41-16-7]]

^<<v41-16-7,7>>^ Mas vão e digam aos discípulos dele e a Pedro que ele vai adiante de vocês para a Galileia; lá vocês o verão, como ele disse.

[[v41-16-8]]

^<<v41-16-8,8>>^ E, saindo elas, fugiram do sepulcro, porque estavam tomadas de temor e assombro. E não contaram nada a ninguém, porque estavam com medo.

[[v41-16-9]]

^<<v41-16-9,9>>^ &#91;Havendo Jesus ressuscitado de manhã cedo no primeiro dia da semana, apareceu primeiro a Maria Madalena, da qual tinha expulsado sete demônios.

[[v41-16-10]]

^<<v41-16-10,10>>^ E, partindo ela, foi anunciá-lo àqueles que, tendo sido companheiros de Jesus, estavam tristes e choravam.

[[v41-16-11]]

^<<v41-16-11,11>>^ Estes, ouvindo que ele vivia e que tinha sido visto por ela, não acreditaram.

[[v41-16-12]]

^<<v41-16-12,12>>^ Depois disso, Jesus manifestou-se em outra forma a dois deles que estavam a caminho do campo.

[[v41-16-13]]

^<<v41-16-13,13>>^ E, indo, eles o anunciaram aos demais, mas também a estes dois eles não deram crédito.

[[v41-16-14]]

^<<v41-16-14,14>>^ Finalmente, Jesus apareceu aos onze, quando estavam à mesa, e censurou-lhes a incredulidade e a dureza de coração, porque não deram crédito aos que o tinham visto já ressuscitado.

[[v41-16-15]]

^<<v41-16-15,15>>^ E disse-lhes: — Vão por todo o mundo e preguem o evangelho a toda criatura.

[[v41-16-16]]

^<<v41-16-16,16>>^ Quem crer e for batizado será salvo; quem, porém, não crer será condenado.

[[v41-16-17]]

^<<v41-16-17,17>>^ Estes sinais acompanharão aqueles que creem: em meu nome, expulsarão demônios; falarão novas línguas;

[[v41-16-18]]

^<<v41-16-18,18>>^ pegarão em serpentes; e, se beberem alguma coisa mortífera, não lhes fará mal; se impuserem as mãos sobre enfermos, eles ficarão curados.

[[v41-16-19]]

^<<v41-16-19,19>>^ De fato, o Senhor Jesus, depois de lhes ter falado, foi recebido no céu e sentou-se à direita de Deus.

[[v41-16-20]]

^<<v41-16-20,20>>^ E eles foram e pregaram por toda parte, cooperando com eles o Senhor e confirmando a palavra por meio de sinais, que se seguiam.&#93;

'''

xref:041-marcos/041-marcos-015.adoc#v41-15-0[&#60; Capítulo Anterior] | <<v41-16-0,Topo>> | xref:042-lucas/042-lucas-001.adoc#v42-1-0[Próximo Capítulo &#62;]