include::./index.adoc[]

[[v41-14-0]]
=== Marcos, 14
// naa ?, NAA - Nova Almeida Atualizada

[[v41-14-1]]

^<<v41-14-1,1>>^ Dois dias depois seria celebrada a Páscoa e a Festa dos Pães sem Fermento. Os principais sacerdotes e os escribas procuravam uma forma de prender Jesus, à traição, para matá-lo.

[[v41-14-2]]

^<<v41-14-2,2>>^ Pois diziam: — Não durante a festa, para que não haja tumulto entre o povo.

[[v41-14-3]]

^<<v41-14-3,3>>^ Quando Jesus estava em Betânia, fazendo uma refeição na casa de Simão, o leproso, veio uma mulher, trazendo um frasco feito de alabastro com um perfume muito valioso, de nardo puro; e, quebrando o frasco, derramou o perfume sobre a cabeça de Jesus.

[[v41-14-4]]

^<<v41-14-4,4>>^ Alguns dos que estavam ali ficaram indignados e diziam entre si: — Para que este desperdício de perfume?

[[v41-14-5]]

^<<v41-14-5,5>>^ Este perfume poderia ter sido vendido por mais de trezentos denários, para ser dado aos pobres. E murmuravam contra ela.

[[v41-14-6]]

^<<v41-14-6,6>>^ Mas Jesus disse: — Deixem a mulher em paz! Por que vocês a estão incomodando? Ela praticou uma boa ação para comigo.

[[v41-14-7]]

^<<v41-14-7,7>>^ Porque os pobres estarão sempre com vocês, e, quando quiserem, podem fazer-lhes o bem, mas a mim vocês nem sempre terão.

[[v41-14-8]]

^<<v41-14-8,8>>^ Ela fez o que pôde: ungiu o meu corpo antecipadamente para a sepultura.

[[v41-14-9]]

^<<v41-14-9,9>>^ Em verdade lhes digo que, onde for pregado em todo o mundo o evangelho, também será contado o que ela fez, para memória dela.

[[v41-14-10]]

^<<v41-14-10,10>>^ E Judas Iscariotes, um dos doze, foi falar com os principais sacerdotes, para lhes entregar Jesus.

[[v41-14-11]]

^<<v41-14-11,11>>^ Eles, ouvindo isto, se alegraram e prometeram dar dinheiro a ele; nesse meio-tempo, Judas buscava uma boa ocasião para entregar Jesus.

[[v41-14-12]]

^<<v41-14-12,12>>^ E, no primeiro dia da Festa dos Pães sem Fermento, quando se fazia o sacrifício do cordeiro pascal, os discípulos de Jesus lhe perguntaram: — Onde quer que façamos os preparativos para que o senhor possa comer a Páscoa?

[[v41-14-13]]

^<<v41-14-13,13>>^ Então Jesus enviou dois dos seus discípulos, dizendo-lhes: — Vão até a cidade. Ali, um homem trazendo um cântaro de água sairá ao encontro de vocês.

[[v41-14-14]]

^<<v41-14-14,14>>^ Sigam esse homem e digam ao dono da casa em que ele entrar que o Mestre pergunta: "Onde fica o meu aposento no qual comerei a Páscoa com os meus discípulos?"

[[v41-14-15]]

^<<v41-14-15,15>>^ E ele lhes mostrará um espaçoso cenáculo mobiliado e pronto; ali façam os preparativos.

[[v41-14-16]]

^<<v41-14-16,16>>^ Os discípulos saíram, foram à cidade e, achando tudo como Jesus lhes tinha dito, prepararam a Páscoa.

[[v41-14-17]]

^<<v41-14-17,17>>^ Ao cair da tarde, Jesus chegou com os doze.

[[v41-14-18]]

^<<v41-14-18,18>>^ Quando estavam à mesa e comiam, Jesus disse: — Em verdade lhes digo que um de vocês, o que come comigo, vai me trair.

[[v41-14-19]]

^<<v41-14-19,19>>^ E eles começaram a entristecer-se e a perguntar-lhe, um por um: — Por acaso seria eu?

[[v41-14-20]]

^<<v41-14-20,20>>^ Jesus respondeu: — É um dos doze, o que comigo põe a mão no prato.

[[v41-14-21]]

^<<v41-14-21,21>>^ Pois o Filho do Homem vai, como está escrito a seu respeito; mas ai daquele por quem o Filho do Homem está sendo traído! Melhor seria para ele se nunca tivesse nascido!

[[v41-14-22]]

^<<v41-14-22,22>>^ E, enquanto comiam, Jesus pegou um pão e, abençoando-o, o partiu e lhes deu, dizendo: — Tomem; isto é o meu corpo.

[[v41-14-23]]

^<<v41-14-23,23>>^ A seguir, Jesus pegou um cálice e, tendo dado graças, o deu aos seus discípulos; e todos beberam dele.

[[v41-14-24]]

^<<v41-14-24,24>>^ Então lhes disse: — Isto é o meu sangue, o sangue da aliança, derramado em favor de muitos.

[[v41-14-25]]

^<<v41-14-25,25>>^ Em verdade lhes digo que nunca mais beberei do fruto da videira, até aquele dia em que beberei o vinho novo, no Reino de Deus.

[[v41-14-26]]

^<<v41-14-26,26>>^ E, tendo cantado um hino, saíram para o monte das Oliveiras.

[[v41-14-27]]

^<<v41-14-27,27>>^ E Jesus disse aos discípulos: — Serei uma pedra de tropeço para todos vocês, porque está escrito: "Ferirei o pastor, e as ovelhas ficarão dispersas."

[[v41-14-28]]

^<<v41-14-28,28>>^ Mas, depois da minha ressurreição, irei adiante de vocês para a Galileia.

[[v41-14-29]]

^<<v41-14-29,29>>^ Então Pedro disse a Jesus: — Ainda que o senhor venha a ser um tropeço para todos, não o será para mim!

[[v41-14-30]]

^<<v41-14-30,30>>^ Mas Jesus lhe disse: — Em verdade lhe digo que hoje, nesta noite, antes que o galo cante duas vezes, você me negará três vezes.

[[v41-14-31]]

^<<v41-14-31,31>>^ Mas Pedro insistia com mais veemência: — Ainda que me seja necessário morrer com o senhor, de modo nenhum o negarei. E todos os outros diziam a mesma coisa.

[[v41-14-32]]

^<<v41-14-32,32>>^ Então foram a um lugar chamado Getsêmani. Ali, Jesus disse aos seus discípulos: — Sentem-se aqui, enquanto eu vou orar.

[[v41-14-33]]

^<<v41-14-33,33>>^ E, levando consigo Pedro, Tiago e João, começou a sentir-se tomado de pavor e de angústia.

[[v41-14-34]]

^<<v41-14-34,34>>^ E lhes disse: — A minha alma está profundamente triste até a morte; fiquem aqui e vigiem.

[[v41-14-35]]

^<<v41-14-35,35>>^ E, adiantando-se um pouco, prostrou-se em terra; e orava para que, se possível, lhe fosse poupada aquela hora.

[[v41-14-36]]

^<<v41-14-36,36>>^ E dizia: — Aba, Pai, tudo te é possível; passa de mim este cálice! Porém não seja o que eu quero, e sim o que tu queres.

[[v41-14-37]]

^<<v41-14-37,37>>^ E, voltando, achou-os dormindo. E disse a Pedro: — Simão, você está dormindo? Não conseguiu vigiar nem uma hora?

[[v41-14-38]]

^<<v41-14-38,38>>^ Vigiem e orem, para que não caiam em tentação; o espírito, na verdade, está pronto, mas a carne é fraca.

[[v41-14-39]]

^<<v41-14-39,39>>^ Retirando-se de novo, orou repetindo as mesmas palavras.

[[v41-14-40]]

^<<v41-14-40,40>>^ E voltando, achou-os outra vez dormindo, porque os olhos deles estavam pesados; e não sabiam o que lhe responder.

[[v41-14-41]]

^<<v41-14-41,41>>^ E, quando voltou pela terceira vez, Jesus lhes disse: — Vocês ainda estão dormindo e descansando! Basta! Chegou a hora; o Filho do Homem está sendo entregue nas mãos dos pecadores.

[[v41-14-42]]

^<<v41-14-42,42>>^ Levantem-se, vamos embora! Eis que o traidor se aproxima.

[[v41-14-43]]

^<<v41-14-43,43>>^ E logo, enquanto Jesus ainda falava, chegou Judas, um dos doze, e, com ele, uma multidão com espadas e porretes, vinda da parte dos principais sacerdotes, escribas e anciãos.

[[v41-14-44]]

^<<v41-14-44,44>>^ Ora, o traidor tinha dado a eles um sinal: "Aquele que eu beijar, é esse; prendam e levem-no com segurança."

[[v41-14-45]]

^<<v41-14-45,45>>^ E logo que chegou, aproximando-se de Jesus, Judas disse: — Mestre! E o beijou.

[[v41-14-46]]

^<<v41-14-46,46>>^ Então eles agarraram Jesus e o prenderam.

[[v41-14-47]]

^<<v41-14-47,47>>^ Nisto, um dos que estavam ali, sacando da espada, feriu o servo do sumo sacerdote e cortou-lhe a orelha.

[[v41-14-48]]

^<<v41-14-48,48>>^ Jesus lhes disse: — Vocês vieram com espadas e porretes para prender-me, como se eu fosse um salteador?

[[v41-14-49]]

^<<v41-14-49,49>>^ Todos os dias eu estava com vocês no templo, ensinando, e vocês não me prenderam; mas isto é para que se cumprissem as Escrituras.

[[v41-14-50]]

^<<v41-14-50,50>>^ Então todos o deixaram e fugiram.

[[v41-14-51]]

^<<v41-14-51,51>>^ Um jovem, coberto unicamente com um lençol, seguia Jesus. Eles o agarraram,

[[v41-14-52]]

^<<v41-14-52,52>>^ mas ele largou o lençol e fugiu nu.

[[v41-14-53]]

^<<v41-14-53,53>>^ E levaram Jesus ao sumo sacerdote, e então se reuniram todos os principais sacerdotes, os anciãos e os escribas.

[[v41-14-54]]

^<<v41-14-54,54>>^ Pedro seguiu Jesus de longe até o interior do pátio do sumo sacerdote e estava assentado entre os servos, aquentando-se ao fogo.

[[v41-14-55]]

^<<v41-14-55,55>>^ E os principais sacerdotes e todo o Sinédrio procuravam algum testemunho contra Jesus para o condenar à morte, mas não achavam nada.

[[v41-14-56]]

^<<v41-14-56,56>>^ Pois muitos testemunhavam falsamente contra Jesus, mas os depoimentos não eram coerentes.

[[v41-14-57]]

^<<v41-14-57,57>>^ E, levantando-se alguns, testemunhavam falsamente, dizendo:

[[v41-14-58]]

^<<v41-14-58,58>>^ — Nós o ouvimos declarar: "Eu destruirei este santuário edificado por mãos humanas e, em três dias, construirei outro, não por mãos humanas."

[[v41-14-59]]

^<<v41-14-59,59>>^ Nem assim o testemunho deles era coerente.

[[v41-14-60]]

^<<v41-14-60,60>>^ E, levantando-se o sumo sacerdote, no meio, perguntou a Jesus: — Você não diz nada em resposta ao que estes depõem contra você?

[[v41-14-61]]

^<<v41-14-61,61>>^ Jesus, porém, guardou silêncio e nada respondeu. O sumo sacerdote tornou a interrogá-lo: — Você é o Cristo, o Filho do Deus Bendito?

[[v41-14-62]]

^<<v41-14-62,62>>^ Jesus respondeu: — Eu sou, e vocês verão o Filho do Homem sentado à direita do Todo-Poderoso e vindo com as nuvens do céu.

[[v41-14-63]]

^<<v41-14-63,63>>^ O sumo sacerdote, rasgando as suas vestes, disse: — Por que ainda precisamos de testemunhas?

[[v41-14-64]]

^<<v41-14-64,64>>^ Vocês ouviram a blasfêmia. Qual é o parecer de vocês? E todos o julgaram réu de morte.

[[v41-14-65]]

^<<v41-14-65,65>>^ Alguns começaram a cuspir nele, a cobrir-lhe o rosto, a bater nele e a dizer-lhe: — Profetize! E os guardas davam-lhe bofetadas.

[[v41-14-66]]

^<<v41-14-66,66>>^ Estando Pedro embaixo no pátio, veio uma das empregadas do sumo sacerdote

[[v41-14-67]]

^<<v41-14-67,67>>^ e, vendo Pedro, que se aquecia, fixou os olhos nele e disse: — Você também estava com Jesus, o Nazareno.

[[v41-14-68]]

^<<v41-14-68,68>>^ Mas ele negou, dizendo: — Não o conheço, nem compreendo o que você está falando. E saiu para o pórtico. E o galo cantou.

[[v41-14-69]]

^<<v41-14-69,69>>^ E a empregada, vendo-o, tornou a dizer aos que estavam ali: — Este é um deles.

[[v41-14-70]]

^<<v41-14-70,70>>^ Mas ele negou outra vez. E, pouco depois, os que estavam ali disseram outra vez a Pedro: — Com certeza você é um deles, porque também é galileu.

[[v41-14-71]]

^<<v41-14-71,71>>^ Ele, porém, começou a praguejar e a jurar: — Não conheço esse homem de quem vocês estão falando!

[[v41-14-72]]

^<<v41-14-72,72>>^ E no mesmo instante o galo cantou pela segunda vez. Então Pedro se lembrou da palavra que Jesus lhe tinha dito: "Antes que o galo cante duas vezes, você me negará três vezes."  E, caindo em si, começou a chorar.

'''

xref:041-marcos/041-marcos-013.adoc#v41-13-0[&#60; Capítulo Anterior] | <<v41-14-0,Topo>> | xref:041-marcos/041-marcos-015.adoc#v41-15-0[Próximo Capítulo &#62;]