include::./index.adoc[]

[[v41-6-0]]
=== Marcos, 6
// naa ?, NAA - Nova Almeida Atualizada

[[v41-6-1]]

^<<v41-6-1,1>>^ Tendo saído dali, Jesus foi para a sua terra, e os seus discípulos o acompanharam.

[[v41-6-2]]

^<<v41-6-2,2>>^ Chegando o sábado, começou a ensinar na sinagoga, e muitos, ouvindo-o, se maravilhavam, dizendo: — De onde lhe vem tudo isso? Que sabedoria é esta que lhe foi dada? E como se fazem tais maravilhas por suas mãos?

[[v41-6-3]]

^<<v41-6-3,3>>^ Não é este o carpinteiro, o filho de Maria e irmão de Tiago, José, Judas e Simão? As suas irmãs não vivem aqui entre nós? E escandalizavam-se por causa dele.

[[v41-6-4]]

^<<v41-6-4,4>>^ Jesus, porém, lhes disse: — Nenhum profeta é desprezado, a não ser na sua terra, entre os seus parentes e na sua casa.

[[v41-6-5]]

^<<v41-6-5,5>>^ Não pôde fazer ali nenhum milagre, a não ser curar uns poucos doentes, impondo-lhes as mãos.

[[v41-6-6]]

^<<v41-6-6,6>>^ E admirava-se da incredulidade deles. Jesus percorria as aldeias vizinhas, ensinando.

[[v41-6-7]]

^<<v41-6-7,7>>^ Chamou os doze e passou a enviá-los de dois em dois, dando-lhes autoridade sobre os espíritos imundos.

[[v41-6-8]]

^<<v41-6-8,8>>^ Ordenou-lhes que não levassem nada para o caminho, exceto um bordão; nem pão, nem sacola, nem dinheiro;

[[v41-6-9]]

^<<v41-6-9,9>>^ e que fossem calçados de sandálias e não usassem duas túnicas.

[[v41-6-10]]

^<<v41-6-10,10>>^ E recomendou-lhes: — Quando vocês entrarem numa casa, fiquem ali até saírem daquele lugar.

[[v41-6-11]]

^<<v41-6-11,11>>^ Se em algum lugar não quiserem recebê-los nem ouvi-los, ao saírem dali sacudam o pó dos pés, em testemunho contra eles.

[[v41-6-12]]

^<<v41-6-12,12>>^ Então, saindo eles, pregavam ao povo que se arrependesse.

[[v41-6-13]]

^<<v41-6-13,13>>^ Expulsavam muitos demônios e curavam numerosos enfermos, ungindo-os com óleo.

[[v41-6-14]]

^<<v41-6-14,14>>^ Isto chegou aos ouvidos do rei Herodes, porque o nome de Jesus havia se tornado conhecido. E alguns diziam: "João Batista ressuscitou dentre os mortos e, por isso, forças miraculosas operam nele."

[[v41-6-15]]

^<<v41-6-15,15>>^ Outros diziam: "É Elias." Ainda outros diziam: "É profeta como um dos antigos profetas."

[[v41-6-16]]

^<<v41-6-16,16>>^ Herodes, porém, ouvindo isto, disse: — É João, a quem eu mandei decapitar, que ressuscitou.

[[v41-6-17]]

^<<v41-6-17,17>>^ Porque o próprio Herodes havia mandado prender João e amarrá-lo na prisão, por causa de Herodias, mulher do seu irmão Filipe, com a qual Herodes havia casado.

[[v41-6-18]]

^<<v41-6-18,18>>^ Pois João lhe dizia: "Você não tem o direito de viver com a mulher do seu irmão."

[[v41-6-19]]

^<<v41-6-19,19>>^ Herodias odiava João Batista e queria matá-lo, mas não conseguia fazer isso.

[[v41-6-20]]

^<<v41-6-20,20>>^ Porque Herodes temia João, sabendo que era homem justo e santo, e o mantinha em segurança. E, quando o ouvia, ficava perplexo, embora gostasse de escutá-lo.

[[v41-6-21]]

^<<v41-6-21,21>>^ Chegando uma ocasião favorável, em que Herodes, no dia do seu aniversário, deu um banquete às autoridades, aos oficiais militares e às pessoas importantes da Galileia,

[[v41-6-22]]

^<<v41-6-22,22>>^ a filha de Herodias entrou no salão e, dançando, agradou a Herodes e aos seus convidados. Então o rei disse à jovem: — Peça o que quiser, e eu lhe darei.

[[v41-6-23]]

^<<v41-6-23,23>>^ E fez este juramento: — O que você me pedir eu lhe darei, mesmo que seja a metade do meu reino.

[[v41-6-24]]

^<<v41-6-24,24>>^ Ela saiu e foi perguntar à mãe: — O que pedirei? A mãe respondeu: — A cabeça de João Batista.

[[v41-6-25]]

^<<v41-6-25,25>>^ No mesmo instante, voltando apressadamente para junto do rei, disse: — Quero que, sem demora, o senhor me dê num prato a cabeça de João Batista.

[[v41-6-26]]

^<<v41-6-26,26>>^ O rei ficou muito triste, mas, por causa do juramento e dos que estavam com ele à mesa, não quis negar o pedido da jovem.

[[v41-6-27]]

^<<v41-6-27,27>>^ E, enviando logo o executor, mandou que lhe trouxessem a cabeça de João. Ele foi e o decapitou na prisão,

[[v41-6-28]]

^<<v41-6-28,28>>^ e, trazendo a cabeça num prato, a entregou à jovem, e esta, por sua vez, a entregou à sua mãe.

[[v41-6-29]]

^<<v41-6-29,29>>^ Os discípulos de João, logo que souberam disto, vieram, levaram o corpo dele e o colocaram num túmulo.

[[v41-6-30]]

^<<v41-6-30,30>>^ Os apóstolos voltaram à presença de Jesus e lhe relataram tudo o que tinham feito e ensinado.

[[v41-6-31]]

^<<v41-6-31,31>>^ E ele lhes disse: — Venham repousar um pouco, à parte, num lugar deserto. Isto porque eles não tinham tempo nem para comer, visto serem muitos os que iam e vinham.

[[v41-6-32]]

^<<v41-6-32,32>>^ Então foram de barco para um lugar deserto, à parte.

[[v41-6-33]]

^<<v41-6-33,33>>^ Muitos, porém, os viram sair e, reconhecendo-os, correram para lá, a pé, de todas as cidades, e chegaram antes deles.

[[v41-6-34]]

^<<v41-6-34,34>>^ Ao desembarcar, Jesus viu uma grande multidão e compadeceu-se dela, porque eram como ovelhas que não têm pastor. E começou a ensinar-lhes muitas coisas.

[[v41-6-35]]

^<<v41-6-35,35>>^ Como já era bastante tarde, os discípulos se aproximaram de Jesus e disseram: — Este lugar é deserto, e já é bastante tarde.

[[v41-6-36]]

^<<v41-6-36,36>>^ Mande essas pessoas embora, para que, indo pelos campos ao redor e pelas aldeias, comprem para si o que comer.

[[v41-6-37]]

^<<v41-6-37,37>>^ Jesus, porém, lhes disse: — Deem vocês mesmos de comer a eles. Mas eles disseram: — Iremos comprar duzentos denários de pão para lhes dar de comer?

[[v41-6-38]]

^<<v41-6-38,38>>^ E Jesus lhes disse: — Quantos pães vocês têm? Tratem de descobrir! Eles foram se informar e responderam: — Cinco pães e dois peixes.

[[v41-6-39]]

^<<v41-6-39,39>>^ Então Jesus lhes ordenou que todos se assentassem, em grupos, sobre a relva verde.

[[v41-6-40]]

^<<v41-6-40,40>>^ E eles o fizeram, repartindo-se em grupos de cem e de cinquenta.

[[v41-6-41]]

^<<v41-6-41,41>>^ Jesus, pegando os cinco pães e os dois peixes, erguendo os olhos para o céu, os abençoou. Depois partiu os pães e os deu aos seus discípulos para que os distribuíssem. E também repartiu os dois peixes entre todos.

[[v41-6-42]]

^<<v41-6-42,42>>^ Todos comeram e se fartaram,

[[v41-6-43]]

^<<v41-6-43,43>>^ e ainda recolheram doze cestos cheios de pedaços de pão e de peixe.

[[v41-6-44]]

^<<v41-6-44,44>>^ Os que comeram os pães eram cinco mil homens.

[[v41-6-45]]

^<<v41-6-45,45>>^ Logo a seguir, Jesus fez com que os seus discípulos entrassem no barco e fossem adiante dele para o outro lado, para Betsaida, enquanto ele despedia a multidão.

[[v41-6-46]]

^<<v41-6-46,46>>^ E, tendo-os despedido, ele subiu ao monte para orar.

[[v41-6-47]]

^<<v41-6-47,47>>^ Ao cair da tarde, o barco estava no meio do mar, e Jesus estava sozinho em terra.

[[v41-6-48]]

^<<v41-6-48,48>>^ De madrugada, vendo que os discípulos remavam com dificuldade, porque o vento lhes era contrário, Jesus foi até onde eles estavam, andando sobre o mar; e queria passar adiante deles.

[[v41-6-49]]

^<<v41-6-49,49>>^ Eles, porém, vendo-o andar sobre o mar, pensaram tratar-se de um fantasma e gritaram.

[[v41-6-50]]

^<<v41-6-50,50>>^ Pois todos viram Jesus e ficaram apavorados. Mas Jesus imediatamente falou com eles e disse: — Coragem! Sou eu. Não tenham medo!

[[v41-6-51]]

^<<v41-6-51,51>>^ Então subiu no barco para estar com eles, e o vento cessou. Ficaram totalmente perplexos,

[[v41-6-52]]

^<<v41-6-52,52>>^ porque não haviam compreendido o milagre dos pães, pois o coração deles estava endurecido.

[[v41-6-53]]

^<<v41-6-53,53>>^ Estando já no outro lado, chegaram à terra de Genesaré, onde atracaram.

[[v41-6-54]]

^<<v41-6-54,54>>^ Saindo eles do barco, o povo logo reconheceu Jesus.

[[v41-6-55]]

^<<v41-6-55,55>>^ E eles, percorrendo toda aquela região, começaram a trazer em leitos os enfermos e os levavam para onde ouviam que ele estava.

[[v41-6-56]]

^<<v41-6-56,56>>^ Onde quer que ele entrasse, nas aldeias, cidades ou campos, punham os enfermos nas praças, pedindo-lhe que os deixasse tocar ao menos na borda da sua roupa. E todos os que tocavam nela ficavam curados.

'''

xref:041-marcos/041-marcos-005.adoc#v41-5-0[&#60; Capítulo Anterior] | <<v41-6-0,Topo>> | xref:041-marcos/041-marcos-007.adoc#v41-7-0[Próximo Capítulo &#62;]