include::./index.adoc[]

[[v41-7-0]]
=== Marcos, 7
// naa ?, NAA - Nova Almeida Atualizada

[[v41-7-1]]

^<<v41-7-1,1>>^ Os fariseus e alguns escribas, vindos de Jerusalém, reuniram-se em volta de Jesus.

[[v41-7-2]]

^<<v41-7-2,2>>^ Eles viram que alguns dos discípulos de Jesus comiam pão com as mãos impuras, isto é, sem lavar.

[[v41-7-3]]

^<<v41-7-3,3>>^ Porque os fariseus e todos os judeus, observando a tradição dos anciãos, não comem sem lavar cuidadosamente as mãos.

[[v41-7-4]]

^<<v41-7-4,4>>^ Quando voltam da praça, não comem sem se lavar. E há muitas outras coisas que receberam para observar, como a lavagem de copos, jarros e vasos de metal e camas.

[[v41-7-5]]

^<<v41-7-5,5>>^ Os fariseus e os escribas perguntaram a Jesus: — Por que os seus discípulos não vivem conforme a tradição dos anciãos, mas comem com as mãos impuras?

[[v41-7-6]]

^<<v41-7-6,6>>^ Jesus respondeu: — Bem profetizou Isaías a respeito de vocês, hipócritas, como está escrito: "Este povo me honra com os lábios, mas o seu coração está longe de mim.

[[v41-7-7]]

^<<v41-7-7,7>>^ E em vão me adoram, ensinando doutrinas que são preceitos humanos."

[[v41-7-8]]

^<<v41-7-8,8>>^ — Rejeitando o mandamento de Deus, vocês guardam a tradição humana.

[[v41-7-9]]

^<<v41-7-9,9>>^ E disse-lhes ainda: — Vocês sempre encontram uma maneira de rejeitar o mandamento de Deus para guardarem a própria tradição.

[[v41-7-10]]

^<<v41-7-10,10>>^ Pois Moisés disse: "Honre o seu pai e a sua mãe." E: "Quem maldisser o seu pai ou a sua mãe seja punido de morte."

[[v41-7-11]]

^<<v41-7-11,11>>^ Vocês, porém, dizem que, se alguém disser ao seu pai ou à sua mãe: "A ajuda que você poderia receber de mim é Corbã, isto é, oferta ao Senhor",

[[v41-7-12]]

^<<v41-7-12,12>>^ então vocês o dispensam de fazer qualquer coisa em favor do seu pai ou da sua mãe,

[[v41-7-13]]

^<<v41-7-13,13>>^ invalidando a palavra de Deus por meio da tradição que vocês mesmos passam de pai para filho. E fazem muitas outras coisas semelhantes.

[[v41-7-14]]

^<<v41-7-14,14>>^ E, convocando outra vez a multidão, Jesus disse: — Escutem todos e entendam:

[[v41-7-15]]

^<<v41-7-15,15>>^ Não existe nada fora da pessoa que, entrando nela, possa contaminá-la; mas o que sai da pessoa é o que a contamina.

[[v41-7-16]]

^<<v41-7-16,16>>^ &#91;Se alguém tem ouvidos para ouvir, ouça.&#93;

[[v41-7-17]]

^<<v41-7-17,17>>^ Quando entrou em casa, deixando a multidão, os seus discípulos o interrogaram a respeito da parábola.

[[v41-7-18]]

^<<v41-7-18,18>>^ Jesus lhes disse: — Então vocês também não entendem? Não compreendem que tudo o que está fora da pessoa, entrando nela, não a pode contaminar,

[[v41-7-19]]

^<<v41-7-19,19>>^ porque não entra no coração dela, mas no estômago, e depois é eliminado? E, assim, Jesus considerou puros todos os alimentos.

[[v41-7-20]]

^<<v41-7-20,20>>^ E dizia: — O que sai da pessoa, isso é o que a contamina.

[[v41-7-21]]

^<<v41-7-21,21>>^ Porque de dentro, do coração das pessoas, é que procedem os maus pensamentos, as imoralidades sexuais, os furtos, os homicídios,

[[v41-7-22]]

^<<v41-7-22,22>>^ os adultérios, a avareza, as maldades, o engano, a libertinagem, a inveja, a blasfêmia, o orgulho, a falta de juízo.

[[v41-7-23]]

^<<v41-7-23,23>>^ Todos estes males vêm de dentro e contaminam a pessoa.

[[v41-7-24]]

^<<v41-7-24,24>>^ Levantando-se Jesus, saiu dali e foi para as terras de Tiro e Sidom. Tendo entrado numa casa, não queria que ninguém soubesse onde ele estava. No entanto, não pôde ocultar-se,

[[v41-7-25]]

^<<v41-7-25,25>>^ porque uma mulher, cuja filhinha estava possuída de espírito imundo, logo ouviu falar a respeito de Jesus. Ela veio e se ajoelhou aos pés dele.

[[v41-7-26]]

^<<v41-7-26,26>>^ Essa mulher era estrangeira, de origem siro-fenícia, e pedia a Jesus que expulsasse o demônio da sua filha.

[[v41-7-27]]

^<<v41-7-27,27>>^ Mas Jesus lhe disse: — Deixe primeiro que os filhos se fartem, porque não é correto pegar o pão dos filhos e jogá-lo aos cachorrinhos.

[[v41-7-28]]

^<<v41-7-28,28>>^ A mulher respondeu a ele: — Senhor, os cachorrinhos, debaixo da mesa, comem das migalhas das crianças.

[[v41-7-29]]

^<<v41-7-29,29>>^ Então Jesus disse à mulher: — Por causa desta palavra, você pode ir; o demônio já saiu da sua filha.

[[v41-7-30]]

^<<v41-7-30,30>>^ Quando a mulher voltou para casa, achou a menina sobre a cama, pois o demônio tinha saído dela.

[[v41-7-31]]

^<<v41-7-31,31>>^ De novo, Jesus se retirou das terras de Tiro e foi por Sidom até o mar da Galileia, através do território de Decápolis.

[[v41-7-32]]

^<<v41-7-32,32>>^ Então lhe trouxeram um surdo e gago e lhe suplicaram que impusesse as mãos sobre ele.

[[v41-7-33]]

^<<v41-7-33,33>>^ Jesus, tirando-o da multidão, à parte, pôs os dedos nos ouvidos dele; depois, cuspindo, aplicou saliva na língua do homem.

[[v41-7-34]]

^<<v41-7-34,34>>^ Então, erguendo os olhos ao céu, suspirou e disse: — Efatá!  — que quer dizer: "Abra-se!"

[[v41-7-35]]

^<<v41-7-35,35>>^ E logo os ouvidos do homem se abriram, e o empecilho da língua se soltou, e ele falava sem dificuldade.

[[v41-7-36]]

^<<v41-7-36,36>>^ Jesus lhes ordenou que não contassem isso a ninguém; porém, quanto mais recomendava, tanto mais eles o divulgavam.

[[v41-7-37]]

^<<v41-7-37,37>>^ Ficavam muito admirados, dizendo: — Tudo ele tem feito muito bem; faz até os surdos ouvirem e os mudos falarem.

'''

xref:041-marcos/041-marcos-006.adoc#v41-6-0[&#60; Capítulo Anterior] | <<v41-7-0,Topo>> | xref:041-marcos/041-marcos-008.adoc#v41-8-0[Próximo Capítulo &#62;]