include::./index.adoc[]

[[v41-5-0]]
=== Marcos, 5
// naa ?, NAA - Nova Almeida Atualizada

[[v41-5-1]]

^<<v41-5-1,1>>^ Jesus e os discípulos chegaram à outra margem do mar, à terra dos gerasenos.

[[v41-5-2]]

^<<v41-5-2,2>>^ Ao desembarcar, logo um homem possuído de espírito imundo veio dos túmulos ao encontro de Jesus.

[[v41-5-3]]

^<<v41-5-3,3>>^ Esse homem vivia nos túmulos, e ninguém podia prendê-lo, nem mesmo com correntes.

[[v41-5-4]]

^<<v41-5-4,4>>^ Porque, tendo sido muitas vezes preso com correntes e cadeias, as cadeias foram quebradas por ele, e as correntes foram despedaçadas. E ninguém conseguia dominá-lo.

[[v41-5-5]]

^<<v41-5-5,5>>^ Andava sempre, de noite e de dia, gritando por entre os túmulos e pelos montes, ferindo-se com pedras.

[[v41-5-6]]

^<<v41-5-6,6>>^ Quando, de longe, viu Jesus, correu e prostrou-se diante dele,

[[v41-5-7]]

^<<v41-5-7,7>>^ gritando em alta voz: — O que você quer comigo, Jesus, Filho do Deus Altíssimo? Por Deus, peço-lhe que não me atormente!

[[v41-5-8]]

^<<v41-5-8,8>>^ Ele disse isto, porque Jesus tinha dito a ele: "Espírito imundo, saia desse homem!"

[[v41-5-9]]

^<<v41-5-9,9>>^ Então Jesus lhe perguntou: — Qual é o seu nome? Ele respondeu: — Legião é o meu nome, porque somos muitos.

[[v41-5-10]]

^<<v41-5-10,10>>^ E pediu-lhe com insistência que não os mandasse para fora do país.

[[v41-5-11]]

^<<v41-5-11,11>>^ Ora, uma grande manada de porcos estava pastando ali pelo monte.

[[v41-5-12]]

^<<v41-5-12,12>>^ E os espíritos imundos pediram a Jesus: — Mande-nos para os porcos, para que entremos neles.

[[v41-5-13]]

^<<v41-5-13,13>>^ E Jesus o permitiu. Então, saindo os espíritos imundos, entraram nos porcos. E a manada, que era cerca de dois mil, precipitou-se despenhadeiro abaixo, para dentro do mar, onde se afogaram.

[[v41-5-14]]

^<<v41-5-14,14>>^ Os que tratavam dos porcos fugiram e foram anunciá-lo na cidade e pelos campos. Então o povo saiu para ver o que tinha acontecido.

[[v41-5-15]]

^<<v41-5-15,15>>^ Aproximando-se de Jesus, viram o endemoniado, o que antes estava dominado pela legião, assentado, vestido, em perfeito juízo; e temeram.

[[v41-5-16]]

^<<v41-5-16,16>>^ Os que haviam presenciado os fatos contaram-lhes o que tinha acontecido ao endemoniado e também falaram a respeito dos porcos.

[[v41-5-17]]

^<<v41-5-17,17>>^ E começaram a pedir com insistência que Jesus se retirasse da terra deles.

[[v41-5-18]]

^<<v41-5-18,18>>^ Quando Jesus estava entrando no barco, aquele que antes estava possuído pelos demônios pediu com insistência que Jesus o deixasse ficar com ele.

[[v41-5-19]]

^<<v41-5-19,19>>^ Jesus, porém, não o permitiu; ao contrário, ordenou-lhe: — Vá para a sua casa, para os seus parentes, e conte-lhes tudo o que o Senhor fez por você e como teve compaixão de você.

[[v41-5-20]]

^<<v41-5-20,20>>^ Então ele foi e começou a proclamar em Decápolis tudo o que Jesus lhe tinha feito; e todos se admiravam.

[[v41-5-21]]

^<<v41-5-21,21>>^ Tendo Jesus voltado de barco para o outro lado, reuniu-se em volta dele uma grande multidão; e ele estava junto do mar.

[[v41-5-22]]

^<<v41-5-22,22>>^ Então chegou um dos chefes da sinagoga, chamado Jairo, e, vendo-o, prostrou-se aos pés de Jesus

[[v41-5-23]]

^<<v41-5-23,23>>^ e lhe pediu com insistência: — Minha filhinha está morrendo; venha impor as mãos sobre ela, para que seja salva e viva.

[[v41-5-24]]

^<<v41-5-24,24>>^ Jesus foi com ele. Uma grande multidão seguia Jesus, apertando-o de todos os lados.

[[v41-5-25]]

^<<v41-5-25,25>>^ Estava ali certa mulher, que, havia doze anos, vinha sofrendo de uma hemorragia.

[[v41-5-26]]

^<<v41-5-26,26>>^ Ela havia padecido muito nas mãos de vários médicos e gastado tudo o que tinha, sem, contudo, melhorar de saúde; pelo contrário, piorava cada vez mais.

[[v41-5-27]]

^<<v41-5-27,27>>^ Tendo ouvido a fama de Jesus, a mulher chegou por trás, no meio da multidão, e tocou na capa dele.

[[v41-5-28]]

^<<v41-5-28,28>>^ Porque dizia: "Se eu apenas tocar na roupa dele, ficarei curada."

[[v41-5-29]]

^<<v41-5-29,29>>^ E logo a hemorragia estancou, e ela sentiu no corpo que estava curada daquele mal.

[[v41-5-30]]

^<<v41-5-30,30>>^ Jesus, reconhecendo imediatamente que dele havia saído poder, virando-se no meio da multidão, perguntou: — Quem tocou na minha roupa?

[[v41-5-31]]

^<<v41-5-31,31>>^ Os discípulos responderam: — O senhor está vendo que a multidão o aperta e ainda pergunta: "Quem me tocou?"

[[v41-5-32]]

^<<v41-5-32,32>>^ Ele, porém, olhava ao redor para ver quem tinha feito aquilo.

[[v41-5-33]]

^<<v41-5-33,33>>^ Então a mulher, amedrontada e trêmula, ciente do que lhe havia acontecido, veio, prostrou-se diante de Jesus e declarou-lhe toda a verdade.

[[v41-5-34]]

^<<v41-5-34,34>>^ Então Jesus lhe disse: — Filha, a sua fé salvou você. Vá em paz e fique livre desse mal.

[[v41-5-35]]

^<<v41-5-35,35>>^ Enquanto Jesus ainda falava, chegaram alguns da casa do chefe da sinagoga, dizendo: — A sua filha já morreu; por que você ainda incomoda o Mestre?

[[v41-5-36]]

^<<v41-5-36,36>>^ Mas Jesus, sem levar em conta tais palavras, disse ao chefe da sinagoga: — Não tenha medo; apenas creia!

[[v41-5-37]]

^<<v41-5-37,37>>^ Jesus não permitiu que ninguém o acompanhasse, a não ser Pedro e os irmãos Tiago e João.

[[v41-5-38]]

^<<v41-5-38,38>>^ Chegando à casa do chefe da sinagoga, Jesus viu o alvoroço, os que choravam e os que pranteavam muito.

[[v41-5-39]]

^<<v41-5-39,39>>^ Ao entrar, disse: — Por que vocês estão alvoroçados e chorando? A criança não está morta, mas dorme.

[[v41-5-40]]

^<<v41-5-40,40>>^ E riam-se dele. Mas Jesus, mandando que todos saíssem, levou consigo o pai e a mãe da criança e os que vieram com ele e entrou onde ela estava.

[[v41-5-41]]

^<<v41-5-41,41>>^ Tomando a criança pela mão, disse: — Talitá cumi!  — que quer dizer: "Menina, eu digo a você: Levante-se!"

[[v41-5-42]]

^<<v41-5-42,42>>^ Imediatamente a menina, que tinha doze anos, se levantou e começou a andar. Então todos ficaram muito admirados.

[[v41-5-43]]

^<<v41-5-43,43>>^ Mas Jesus ordenou-lhes expressamente que ninguém o soubesse. E mandou que dessem de comer à menina.

'''

xref:041-marcos/041-marcos-004.adoc#v41-4-0[&#60; Capítulo Anterior] | <<v41-5-0,Topo>> | xref:041-marcos/041-marcos-006.adoc#v41-6-0[Próximo Capítulo &#62;]