include::./index.adoc[]

[[v43-7-0]]
=== João, 7
// naa ?, NAA - Nova Almeida Atualizada

[[v43-7-1]]

^<<v43-7-1,1>>^ Passadas essas coisas, Jesus andava pela Galileia, porque não desejava andar pela Judeia, visto que os judeus queriam matá-lo.

[[v43-7-2]]

^<<v43-7-2,2>>^ E a festa dos judeus, chamada de Festa dos Tabernáculos, estava próxima.

[[v43-7-3]]

^<<v43-7-3,3>>^ Então os irmãos de Jesus se dirigiram a ele e disseram: — Deixe este lugar e vá para a Judeia, para que também os seus discípulos vejam as obras que você faz.

[[v43-7-4]]

^<<v43-7-4,4>>^ Porque, se alguém quer ser conhecido, não pode realizar os seus feitos em segredo. Já que você faz essas coisas, manifeste-se ao mundo.

[[v43-7-5]]

^<<v43-7-5,5>>^ Acontece que nem mesmo os irmãos de Jesus criam nele.

[[v43-7-6]]

^<<v43-7-6,6>>^ Então Jesus lhes disse: — O meu tempo ainda não chegou, mas para vocês qualquer tempo é oportuno.

[[v43-7-7]]

^<<v43-7-7,7>>^ O mundo não pode odiar vocês, mas a mim ele odeia, porque eu dou testemunho a respeito dele, dizendo que as suas obras são más.

[[v43-7-8]]

^<<v43-7-8,8>>^ Vão vocês para a festa. Eu não vou, porque o meu tempo ainda não se cumpriu.

[[v43-7-9]]

^<<v43-7-9,9>>^ Tendo dito isso, Jesus continuou na Galileia.

[[v43-7-10]]

^<<v43-7-10,10>>^ Depois que seus irmãos tinham ido à festa, Jesus também foi, não publicamente, mas em segredo.

[[v43-7-11]]

^<<v43-7-11,11>>^ Ora, os judeus o procuravam na festa e perguntavam: — Onde estará ele?

[[v43-7-12]]

^<<v43-7-12,12>>^ E havia grande murmuração a respeito de Jesus entre as multidões. Uns diziam: — Ele é bom. E outros afirmavam: — Não, não é! Ele engana o povo.

[[v43-7-13]]

^<<v43-7-13,13>>^ Entretanto, ninguém falava dele abertamente, por ter medo dos judeus.

[[v43-7-14]]

^<<v43-7-14,14>>^ Quando a festa já estava na metade, Jesus foi ao templo e começou a ensinar.

[[v43-7-15]]

^<<v43-7-15,15>>^ Então os judeus se maravilhavam e diziam: — Como é que ele pode ser letrado, se não chegou a estudar?

[[v43-7-16]]

^<<v43-7-16,16>>^ Jesus lhes respondeu: — O meu ensino não é meu, mas daquele que me enviou.

[[v43-7-17]]

^<<v43-7-17,17>>^ Se alguém quiser fazer a vontade de Deus, conhecerá a respeito da doutrina, se ela é de Deus ou se eu falo por mim mesmo.

[[v43-7-18]]

^<<v43-7-18,18>>^ Quem fala por si mesmo está buscando a sua própria glória; mas o que busca a glória de quem o enviou, esse é verdadeiro, e nele não há falsidade.

[[v43-7-19]]

^<<v43-7-19,19>>^ Não é fato que Moisés deu a Lei para vocês? Contudo, nenhum de vocês a cumpre. Por que estão querendo me matar?

[[v43-7-20]]

^<<v43-7-20,20>>^ A multidão respondeu: — Você tem demônio. Quem é que está querendo matá-lo?

[[v43-7-21]]

^<<v43-7-21,21>>^ Jesus respondeu: — Um só feito realizei, e todos vocês ficaram admirados.

[[v43-7-22]]

^<<v43-7-22,22>>^ Moisés lhes deu a circuncisão — se bem que ela não vem de Moisés, mas dos patriarcas —, e vocês fazem a circuncisão de um menino até mesmo no sábado.

[[v43-7-23]]

^<<v43-7-23,23>>^ E, se um menino pode ser circuncidado em dia de sábado, para que a Lei de Moisés não seja desrespeitada, por que vocês ficam indignados contra mim, pelo fato de eu ter curado por completo um homem num sábado?

[[v43-7-24]]

^<<v43-7-24,24>>^ Não julguem segundo a aparência, mas julguem pela reta justiça.

[[v43-7-25]]

^<<v43-7-25,25>>^ Alguns de Jerusalém diziam: — Não é este o homem que estão querendo matar?

[[v43-7-26]]

^<<v43-7-26,26>>^ Eis que ele fala abertamente, e ninguém lhe diz nada. Será que as autoridades reconhecem de fato que este é o Cristo?

[[v43-7-27]]

^<<v43-7-27,27>>^ Mas nós sabemos de onde este homem vem. Quando, porém, o Cristo vier, ninguém saberá de onde ele é.

[[v43-7-28]]

^<<v43-7-28,28>>^ Enquanto ensinava no templo, Jesus disse em voz alta: — Vocês não somente me conhecem, mas também sabem de onde eu sou. Eu não vim porque eu, de mim mesmo, o quisesse, mas aquele que me enviou é verdadeiro, aquele a quem vocês não conhecem.

[[v43-7-29]]

^<<v43-7-29,29>>^ Eu o conheço, porque venho da parte dele e ele me enviou.

[[v43-7-30]]

^<<v43-7-30,30>>^ Então quiseram prendê-lo, mas ninguém lhe pôs as mãos, porque a sua hora ainda não havia chegado.

[[v43-7-31]]

^<<v43-7-31,31>>^ Porém muitos dentre a multidão creram nele e diziam: — Quando o Cristo vier, será que vai fazer maiores sinais do que este homem tem feito?

[[v43-7-32]]

^<<v43-7-32,32>>^ Os fariseus, ouvindo a multidão murmurar essas coisas a respeito de Jesus, juntamente com os principais sacerdotes enviaram guardas para o prender.

[[v43-7-33]]

^<<v43-7-33,33>>^ Jesus disse: — Ainda por um pouco de tempo estou com vocês e depois irei para junto daquele que me enviou.

[[v43-7-34]]

^<<v43-7-34,34>>^ Vocês irão me procurar, mas não me acharão; vocês também não podem ir para onde eu estou.

[[v43-7-35]]

^<<v43-7-35,35>>^ Então os judeus disseram uns aos outros: — Para onde ele irá que não o possamos achar? Será que pretende ir para a diáspora entre os gregos, a fim de ensinar os gregos?

[[v43-7-36]]

^<<v43-7-36,36>>^ Que significa isso que ele diz: "Vocês irão me procurar, mas não me acharão; vocês também não podem ir para onde eu estou?"

[[v43-7-37]]

^<<v43-7-37,37>>^ No último dia, o grande dia da festa, Jesus se levantou e disse em voz alta: — Se alguém tem sede, venha a mim e beba.

[[v43-7-38]]

^<<v43-7-38,38>>^ Quem crer em mim, como diz a Escritura, do seu interior fluirão rios de água viva.

[[v43-7-39]]

^<<v43-7-39,39>>^ Isso ele disse a respeito do Espírito que os que nele cressem haviam de receber; pois o Espírito até aquele momento não tinha sido dado, porque Jesus ainda não havia sido glorificado.

[[v43-7-40]]

^<<v43-7-40,40>>^ Quando ouviram essas palavras, alguns do meio do povo diziam: — Este é verdadeiramente o profeta.

[[v43-7-41]]

^<<v43-7-41,41>>^ Outros diziam: — Ele é o Cristo. Outros, porém, perguntavam: — Por acaso o Cristo virá da Galileia?

[[v43-7-42]]

^<<v43-7-42,42>>^ Não diz a Escritura que o Cristo vem da descendência de Davi e da aldeia de Belém, de onde era Davi?

[[v43-7-43]]

^<<v43-7-43,43>>^ Assim, houve divisão entre o povo por causa dele.

[[v43-7-44]]

^<<v43-7-44,44>>^ Alguns queriam prendê-lo, mas ninguém lhe pôs as mãos.

[[v43-7-45]]

^<<v43-7-45,45>>^ Os guardas voltaram à presença dos principais sacerdotes e fariseus, e estes lhes perguntaram: — Por que vocês não o trouxeram?

[[v43-7-46]]

^<<v43-7-46,46>>^ Eles responderam: — Jamais alguém falou como este homem.

[[v43-7-47]]

^<<v43-7-47,47>>^ Os fariseus disseram aos guardas: — Será que também vocês foram enganados?

[[v43-7-48]]

^<<v43-7-48,48>>^ Por acaso alguma das autoridades ou algum dos fariseus creu nele?

[[v43-7-49]]

^<<v43-7-49,49>>^ Mas esse povo que nada sabe da lei é maldito.

[[v43-7-50]]

^<<v43-7-50,50>>^ Nicodemos, um deles, que antes tinha ido conversar com Jesus, perguntou-lhes:

[[v43-7-51]]

^<<v43-7-51,51>>^ — Será que a nossa lei condena um homem sem primeiro ouvi-lo e saber o que ele fez?

[[v43-7-52]]

^<<v43-7-52,52>>^ Eles responderam: — Por acaso também você é da Galileia? Examine e verá que da Galileia não se levanta profeta.

[[v43-7-53]]

^<<v43-7-53,53>>^ E cada um foi para a sua casa.

'''

xref:043-joao/043-joao-006.adoc#v43-6-0[&#60; Capítulo Anterior] | <<v43-7-0,Topo>> | xref:043-joao/043-joao-008.adoc#v43-8-0[Próximo Capítulo &#62;]