include::./index.adoc[]

[[v43-3-0]]
=== João, 3
// naa ?, NAA - Nova Almeida Atualizada

[[v43-3-1]]

^<<v43-3-1,1>>^ Havia entre os fariseus um homem chamado Nicodemos, um dos principais dos judeus.

[[v43-3-2]]

^<<v43-3-2,2>>^ Este, de noite, foi até Jesus e lhe disse: — Rabi, sabemos que o senhor é Mestre vindo da parte de Deus, porque ninguém pode fazer estes sinais que o senhor faz, se Deus não estiver com ele.

[[v43-3-3]]

^<<v43-3-3,3>>^ Jesus respondeu: — Em verdade, em verdade lhe digo que, se alguém não nascer de novo, não pode ver o Reino de Deus.

[[v43-3-4]]

^<<v43-3-4,4>>^ Nicodemos perguntou: — Como pode um homem nascer, sendo velho? Será que pode voltar ao ventre materno e nascer uma segunda vez?

[[v43-3-5]]

^<<v43-3-5,5>>^ Jesus respondeu: — Em verdade, em verdade lhe digo: quem não nascer da água e do Espírito não pode entrar no Reino de Deus.

[[v43-3-6]]

^<<v43-3-6,6>>^ O que é nascido da carne é carne, e o que é nascido do Espírito é espírito.

[[v43-3-7]]

^<<v43-3-7,7>>^ Não fique admirado por eu dizer: "Vocês precisam nascer de novo."

[[v43-3-8]]

^<<v43-3-8,8>>^ O vento sopra onde quer, você ouve o barulho que ele faz, mas não sabe de onde ele vem, nem para onde vai; assim é todo o que é nascido do Espírito.

[[v43-3-9]]

^<<v43-3-9,9>>^ Então Nicodemos perguntou: — Como pode ser isso? Jesus respondeu:

[[v43-3-10]]

^<<v43-3-10,10>>^ — Você é mestre em Israel e não compreende estas coisas?

[[v43-3-11]]

^<<v43-3-11,11>>^ Em verdade, em verdade lhe digo que nós falamos do que sabemos e damos testemunho do que vimos, mas vocês não aceitam o nosso testemunho.

[[v43-3-12]]

^<<v43-3-12,12>>^ Se vocês não creem quando falo sobre coisas terrenas, como crerão se eu lhes falar sobre as celestiais?

[[v43-3-13]]

^<<v43-3-13,13>>^ Ora, ninguém subiu ao céu, a não ser aquele que de lá desceu, o Filho do Homem.

[[v43-3-14]]

^<<v43-3-14,14>>^ — E assim como Moisés levantou a serpente no deserto, assim também é necessário que o Filho do Homem seja levantado,

[[v43-3-15]]

^<<v43-3-15,15>>^ para que todo o que nele crê tenha a vida eterna.

[[v43-3-16]]

^<<v43-3-16,16>>^ Porque Deus amou o mundo de tal maneira que deu o seu Filho unigênito, para que todo o que nele crê não pereça, mas tenha a vida eterna.

[[v43-3-17]]

^<<v43-3-17,17>>^ Porque Deus enviou o seu Filho ao mundo, não para que condenasse o mundo, mas para que o mundo fosse salvo por ele.

[[v43-3-18]]

^<<v43-3-18,18>>^ Quem nele crê não é condenado; mas o que não crê já está condenado, porque não crê no nome do unigênito Filho de Deus.

[[v43-3-19]]

^<<v43-3-19,19>>^ A condenação é esta: a luz veio ao mundo, mas os homens amaram mais as trevas do que a luz, porque as suas obras eram más.

[[v43-3-20]]

^<<v43-3-20,20>>^ Pois todo aquele que pratica o mal detesta a luz e não se aproxima da luz, para que as suas obras não sejam reprovadas.

[[v43-3-21]]

^<<v43-3-21,21>>^ Quem pratica a verdade se aproxima da luz, para que as suas obras sejam manifestas, porque são feitas em Deus.

[[v43-3-22]]

^<<v43-3-22,22>>^ Depois disso, Jesus foi com os seus discípulos para a terra da Judeia; ali permaneceu com eles e batizava.

[[v43-3-23]]

^<<v43-3-23,23>>^ Ora, João também estava batizando em Enom, perto de Salim, porque ali havia muitas águas, e o povo se dirigia para lá e era batizado.

[[v43-3-24]]

^<<v43-3-24,24>>^ Pois João ainda não havia sido preso.

[[v43-3-25]]

^<<v43-3-25,25>>^ Então surgiu uma discussão entre os discípulos de João e um judeu a respeito da purificação.

[[v43-3-26]]

^<<v43-3-26,26>>^ E foram até João e lhe disseram: — Mestre, aquele que estava com o senhor no outro lado do Jordão, do qual o senhor deu testemunho, está batizando, e todos vão até ele.

[[v43-3-27]]

^<<v43-3-27,27>>^ João respondeu: — Ninguém pode receber coisa alguma se não lhe for dada do céu.

[[v43-3-28]]

^<<v43-3-28,28>>^ Vocês mesmos são testemunhas de que eu disse: "Eu não sou o Cristo, mas fui enviado como o seu precursor."

[[v43-3-29]]

^<<v43-3-29,29>>^ O que tem a noiva é o noivo; o amigo do noivo que está presente e o escuta se alegra muito por causa da voz do noivo. Pois essa alegria já se cumpriu em mim.

[[v43-3-30]]

^<<v43-3-30,30>>^ Convém que ele cresça e que eu diminua.

[[v43-3-31]]

^<<v43-3-31,31>>^ Quem vem das alturas certamente está acima de todos; quem vem da terra é terreno e fala da terra. Quem veio do céu está acima de todos

[[v43-3-32]]

^<<v43-3-32,32>>^ e dá testemunho daquilo que viu e ouviu, mas ninguém aceita o seu testemunho.

[[v43-3-33]]

^<<v43-3-33,33>>^ Quem, porém, aceita o testemunho que ele dá certifica que Deus é verdadeiro.

[[v43-3-34]]

^<<v43-3-34,34>>^ Pois aquele que Deus enviou fala as palavras de Deus, porque Deus não dá o Espírito por medida.

[[v43-3-35]]

^<<v43-3-35,35>>^ O Pai ama o Filho e entregou todas as coisas nas mãos dele.

[[v43-3-36]]

^<<v43-3-36,36>>^ Por isso, quem crê no Filho tem a vida eterna; quem se mantém rebelde contra o Filho não verá a vida, mas sobre ele permanece a ira de Deus.

'''

xref:043-joao/043-joao-002.adoc#v43-2-0[&#60; Capítulo Anterior] | <<v43-3-0,Topo>> | xref:043-joao/043-joao-004.adoc#v43-4-0[Próximo Capítulo &#62;]