include::./index.adoc[]

[[v43-13-0]]
=== João, 13
// naa ?, NAA - Nova Almeida Atualizada

[[v43-13-1]]

^<<v43-13-1,1>>^ Antes da Festa da Páscoa, sabendo Jesus que era chegada a sua hora de passar deste mundo para o Pai, tendo amado os seus que estavam no mundo, amou-os até o fim.

[[v43-13-2]]

^<<v43-13-2,2>>^ Durante a ceia, tendo já o diabo posto no coração de Judas, filho de Simão Iscariotes, que traísse Jesus,

[[v43-13-3]]

^<<v43-13-3,3>>^ sabendo este que o Pai tinha confiado tudo às suas mãos, e que ele tinha vindo de Deus e voltava para Deus,

[[v43-13-4]]

^<<v43-13-4,4>>^ levantou-se da ceia, tirou a vestimenta de cima e, pegando uma toalha, cingiu-se com ela.

[[v43-13-5]]

^<<v43-13-5,5>>^ Em seguida Jesus pôs água numa bacia e começou a lavar os pés dos discípulos e a enxugá-los com a toalha com que estava cingido.

[[v43-13-6]]

^<<v43-13-6,6>>^ Quando se aproximou de Simão Pedro, este lhe perguntou: — Vai lavar os meus pés, Senhor?

[[v43-13-7]]

^<<v43-13-7,7>>^ Jesus respondeu: — O que eu faço você não compreende agora, mas vai entender depois.

[[v43-13-8]]

^<<v43-13-8,8>>^ Então Pedro disse: — O senhor nunca lavará os meus pés! Ao que Jesus respondeu: — Se eu não lavar, você não terá parte comigo.

[[v43-13-9]]

^<<v43-13-9,9>>^ Então Pedro lhe pediu: — Senhor, não somente os pés, mas também as mãos e a cabeça.

[[v43-13-10]]

^<<v43-13-10,10>>^ Jesus respondeu: — Quem já se banhou não precisa lavar nada, a não ser os pés, pois, quanto ao mais, está todo limpo. E vocês estão limpos, mas não todos.

[[v43-13-11]]

^<<v43-13-11,11>>^ Pois ele sabia quem era o traidor. Foi por isso que disse: "Nem todos estão limpos."

[[v43-13-12]]

^<<v43-13-12,12>>^ Depois de lhes ter lavado os pés, Jesus pôs de novo as suas vestimentas e, voltando à mesa, perguntou-lhes: — Vocês compreendem o que eu lhes fiz?

[[v43-13-13]]

^<<v43-13-13,13>>^ Vocês me chamam de Mestre e de Senhor e fazem bem, porque eu o sou.

[[v43-13-14]]

^<<v43-13-14,14>>^ Ora, se eu, sendo Senhor e Mestre, lavei os pés de vocês, também vocês devem lavar os pés uns dos outros.

[[v43-13-15]]

^<<v43-13-15,15>>^ Porque eu lhes dei o exemplo, para que, como eu fiz, vocês façam também.

[[v43-13-16]]

^<<v43-13-16,16>>^ Em verdade, em verdade lhes digo que o servo não é maior do que seu senhor, nem o enviado é maior do que aquele que o enviou.

[[v43-13-17]]

^<<v43-13-17,17>>^ Se vocês sabem estas coisas, bem-aventurados serão se as praticarem.

[[v43-13-18]]

^<<v43-13-18,18>>^ Não falo a respeito de todos vocês, pois eu conheço aqueles que escolhi. Mas é para que se cumpra a Escritura: "Aquele que come do meu pão levantou contra mim o seu calcanhar."

[[v43-13-19]]

^<<v43-13-19,19>>^ Desde já lhes digo isso, antes que aconteça, para que, quando acontecer, vocês creiam que Eu Sou .

[[v43-13-20]]

^<<v43-13-20,20>>^ Em verdade, em verdade lhes digo: quem recebe aquele que eu enviar recebe a mim; e quem recebe a mim recebe aquele que me enviou.

[[v43-13-21]]

^<<v43-13-21,21>>^ Depois de dizer isso, Jesus se angustiou em espírito e afirmou: — Em verdade, em verdade lhes digo que um de vocês vai me trair.

[[v43-13-22]]

^<<v43-13-22,22>>^ Então os discípulos olharam uns para os outros, sem saber a quem ele se referia.

[[v43-13-23]]

^<<v43-13-23,23>>^ Ao lado de Jesus estava reclinado um dos seus discípulos, aquele a quem ele amava.

[[v43-13-24]]

^<<v43-13-24,24>>^ Simão Pedro fez um sinal a esse, para que perguntasse a quem Jesus se referia.

[[v43-13-25]]

^<<v43-13-25,25>>^ Então aquele discípulo, reclinando-se sobre o peito de Jesus, perguntou: — Senhor, quem é?

[[v43-13-26]]

^<<v43-13-26,26>>^ Jesus respondeu: — É aquele a quem eu der o pedaço de pão molhado. Então Jesus pegou um pedaço de pão e, tendo-o molhado, deu-o a Judas, filho de Simão Iscariotes.

[[v43-13-27]]

^<<v43-13-27,27>>^ E, depois que Judas recebeu o pedaço de pão, imediatamente Satanás entrou nele. Então Jesus disse a Judas: — O que você pretende fazer, faça-o depressa.

[[v43-13-28]]

^<<v43-13-28,28>>^ Nenhum dos que estavam à mesa entendeu por que Jesus tinha dito isso.

[[v43-13-29]]

^<<v43-13-29,29>>^ Pois, como Judas era quem trazia a bolsa do dinheiro, alguns pensaram que Jesus tinha dito a ele: "Compre o que precisamos para a festa" ou, então, que havia solicitado que desse alguma coisa aos pobres.

[[v43-13-30]]

^<<v43-13-30,30>>^ Assim, tendo recebido o pedaço de pão, Judas logo saiu. E era noite.

[[v43-13-31]]

^<<v43-13-31,31>>^ Quando Judas saiu, Jesus disse: — Agora foi glorificado o Filho do Homem, e Deus foi glorificado nele.

[[v43-13-32]]

^<<v43-13-32,32>>^ Se Deus foi glorificado nele, também Deus o glorificará nele mesmo; e ele o glorificará imediatamente.

[[v43-13-33]]

^<<v43-13-33,33>>^ Filhinhos, ainda por um pouco estou com vocês. Vocês vão me procurar, mas o que eu disse aos judeus também agora digo a vocês: para onde eu vou vocês não podem ir.

[[v43-13-34]]

^<<v43-13-34,34>>^ Eu lhes dou um novo mandamento: que vocês amem uns aos outros. Assim como eu os amei, que também vocês amem uns aos outros.

[[v43-13-35]]

^<<v43-13-35,35>>^ Nisto todos conhecerão que vocês são meus discípulos: se tiverem amor uns aos outros.

[[v43-13-36]]

^<<v43-13-36,36>>^ Simão Pedro perguntou a Jesus: — Para onde o Senhor vai? Jesus respondeu: — Para onde eu vou você não poderá me seguir agora; mais tarde, porém, me seguirá.

[[v43-13-37]]

^<<v43-13-37,37>>^ Pedro disse: — Senhor, por que não posso segui-lo agora? Darei a minha vida pelo senhor.

[[v43-13-38]]

^<<v43-13-38,38>>^ Jesus respondeu: — Você dará a sua vida por mim? Em verdade, em verdade lhe digo: antes que o galo cante, três vezes você me negará.

'''

xref:043-joao/043-joao-012.adoc#v43-12-0[&#60; Capítulo Anterior] | <<v43-13-0,Topo>> | xref:043-joao/043-joao-014.adoc#v43-14-0[Próximo Capítulo &#62;]