include::./index.adoc[]

[[v43-12-0]]
=== João, 12
// naa ?, NAA - Nova Almeida Atualizada

[[v43-12-1]]

^<<v43-12-1,1>>^ Seis dias antes da Páscoa, Jesus foi para Betânia, onde estava Lázaro, a quem ele tinha ressuscitado dentre os mortos.

[[v43-12-2]]

^<<v43-12-2,2>>^ Prepararam-lhe, ali, uma ceia. Marta servia, e Lázaro era um dos que estavam à mesa com Jesus.

[[v43-12-3]]

^<<v43-12-3,3>>^ Então Maria, pegando um frasco de perfume de nardo puro, muito precioso, ungiu os pés de Jesus e os enxugou com os seus cabelos. E toda a casa se encheu com o cheiro do perfume.

[[v43-12-4]]

^<<v43-12-4,4>>^ Mas Judas Iscariotes, um dos seus discípulos, aquele que estava para trair Jesus, disse:

[[v43-12-5]]

^<<v43-12-5,5>>^ — Por que este perfume não foi vendido por trezentos denários e o valor não foi dado aos pobres?

[[v43-12-6]]

^<<v43-12-6,6>>^ Ele disse isso não porque se preocupava com os pobres, mas porque era ladrão e, tendo a bolsa do dinheiro, tirava o que era colocado nela.

[[v43-12-7]]

^<<v43-12-7,7>>^ Mas Jesus disse: — Deixe-a! Que ela guarde isto para o dia do meu sepultamento.

[[v43-12-8]]

^<<v43-12-8,8>>^ Porque os pobres estão sempre com vocês, mas a mim vocês nem sempre terão.

[[v43-12-9]]

^<<v43-12-9,9>>^ Uma numerosa multidão dos judeus ficou sabendo que Jesus estava em Betânia. Eles foram até lá não só por causa dele, mas também para ver Lázaro, a quem ele tinha ressuscitado dentre os mortos.

[[v43-12-10]]

^<<v43-12-10,10>>^ Mas os principais sacerdotes resolveram matar também Lázaro,

[[v43-12-11]]

^<<v43-12-11,11>>^ porque muitos dos judeus, por causa dele, voltavam crendo em Jesus.

[[v43-12-12]]

^<<v43-12-12,12>>^ No dia seguinte, a numerosa multidão que tinha vindo à festa, tendo ouvido que Jesus estava a caminho de Jerusalém,

[[v43-12-13]]

^<<v43-12-13,13>>^ pegou ramos de palmeiras e saiu ao encontro dele, clamando: "Hosana! Bendito o que vem em nome do Senhor e que é Rei de Israel!"

[[v43-12-14]]

^<<v43-12-14,14>>^ E Jesus, tendo conseguido um jumentinho, montou-o, segundo está escrito:

[[v43-12-15]]

^<<v43-12-15,15>>^ "Não tema, filha de Sião, eis que o seu Rei está vindo, montado num filho de jumenta."

[[v43-12-16]]

^<<v43-12-16,16>>^ Seus discípulos a princípio não compreenderam isso. Mas, quando Jesus foi glorificado, então eles se lembraram de que essas coisas estavam escritas a respeito dele e também de que tinham feito isso com ele.

[[v43-12-17]]

^<<v43-12-17,17>>^ A multidão que estava com Jesus quando ele chamou Lázaro do túmulo e o levantou dentre os mortos dava testemunho.

[[v43-12-18]]

^<<v43-12-18,18>>^ Por causa disso, também, a multidão saiu ao encontro de Jesus, pois ouviu que ele tinha feito esse sinal.

[[v43-12-19]]

^<<v43-12-19,19>>^ Então os fariseus disseram entre si: — Vocês podem ver que não estão conseguindo nada! Eis que o mundo vai atrás dele.

[[v43-12-20]]

^<<v43-12-20,20>>^ Ora, entre os que foram para adorar durante a festa, havia alguns gregos.

[[v43-12-21]]

^<<v43-12-21,21>>^ Estes se dirigiram a Filipe, que era de Betsaida da Galileia, e lhe pediram: — Senhor, queremos ver Jesus.

[[v43-12-22]]

^<<v43-12-22,22>>^ Filipe foi dizê-lo a André, e André e Filipe o comunicaram a Jesus.

[[v43-12-23]]

^<<v43-12-23,23>>^ Então Jesus se dirigiu a eles, dizendo: — É chegada a hora de ser glorificado o Filho do Homem.

[[v43-12-24]]

^<<v43-12-24,24>>^ Em verdade, em verdade lhes digo: se o grão de trigo, caindo na terra, não morrer, fica ele só; mas, se morrer, produz muito fruto.

[[v43-12-25]]

^<<v43-12-25,25>>^ Quem ama a sua vida perde-a; mas aquele que odeia a sua vida neste mundo irá preservá-la para a vida eterna.

[[v43-12-26]]

^<<v43-12-26,26>>^ Se alguém me serve, siga-me, e, onde eu estou, ali estará também o meu servo. E, se alguém me servir, meu Pai o honrará.

[[v43-12-27]]

^<<v43-12-27,27>>^ — Agora a minha alma está angustiada, e o que direi? "Pai, salva-me desta hora"? Não, pois foi precisamente com este propósito que eu vim para esta hora.

[[v43-12-28]]

^<<v43-12-28,28>>^ Pai, glorifica o teu nome. Então veio uma voz do céu: — Eu já o glorifiquei e ainda o glorificarei.

[[v43-12-29]]

^<<v43-12-29,29>>^ A multidão que ali estava e que ouviu aquela voz dizia ter havido um trovão. Outros diziam: — Foi um anjo que lhe falou.

[[v43-12-30]]

^<<v43-12-30,30>>^ Então Jesus explicou: — Não foi por minha causa que veio esta voz, e sim por causa de vocês.

[[v43-12-31]]

^<<v43-12-31,31>>^ Chegou o momento de este mundo ser julgado, e agora o seu príncipe será expulso.

[[v43-12-32]]

^<<v43-12-32,32>>^ E eu, quando for levantado da terra, atrairei todos a mim.

[[v43-12-33]]

^<<v43-12-33,33>>^ Ele dizia isto, significando com que tipo de morte estava para morrer.

[[v43-12-34]]

^<<v43-12-34,34>>^ A multidão disse: — Nós ouvimos da Lei que o Cristo permanece para sempre. Como, então, você diz que é necessário que o Filho do Homem seja levantado? Quem é esse Filho do Homem?

[[v43-12-35]]

^<<v43-12-35,35>>^ Jesus respondeu: — Ainda por um pouco a luz está com vocês. Andem enquanto vocês têm a luz, para que não sejam surpreendidos pelas trevas. E quem anda nas trevas não sabe para onde vai.

[[v43-12-36]]

^<<v43-12-36,36>>^ Enquanto vocês têm a luz, creiam na luz, para que se tornem filhos da luz. Depois de dizer isso, Jesus foi embora e ocultou-se deles.

[[v43-12-37]]

^<<v43-12-37,37>>^ E, embora tivesse feito tantos sinais na presença deles, não creram nele,

[[v43-12-38]]

^<<v43-12-38,38>>^ para se cumprir a palavra do profeta Isaías, que diz: "Senhor, quem creu em nossa pregação? E a quem foi revelado o braço do Senhor?"

[[v43-12-39]]

^<<v43-12-39,39>>^ Por isso, não podiam crer, porque Isaías disse ainda:

[[v43-12-40]]

^<<v43-12-40,40>>^ "Cegou os olhos deles e endureceu-lhes o coração, para que não vejam com os olhos, nem entendam com o coração, e se convertam, e sejam por mim curados."

[[v43-12-41]]

^<<v43-12-41,41>>^ Isaías disse isso porque viu a glória dele e falou a respeito dele.

[[v43-12-42]]

^<<v43-12-42,42>>^ No entanto, muitos dentre as próprias autoridades creram em Jesus, mas, por causa dos fariseus, não o confessavam, para não serem expulsos da sinagoga.

[[v43-12-43]]

^<<v43-12-43,43>>^ Porque amaram mais a glória dos homens do que a glória de Deus.

[[v43-12-44]]

^<<v43-12-44,44>>^ E Jesus clamou, dizendo: — Quem crê em mim crê não em mim, mas naquele que me enviou.

[[v43-12-45]]

^<<v43-12-45,45>>^ E quem vê a mim vê aquele que me enviou.

[[v43-12-46]]

^<<v43-12-46,46>>^ Eu vim como luz para o mundo, a fim de que todo aquele que crê em mim não permaneça nas trevas.

[[v43-12-47]]

^<<v43-12-47,47>>^ Se alguém ouvir as minhas palavras e não as guardar, eu não o julgo. Porque eu não vim para julgar o mundo, e sim para salvá-lo.

[[v43-12-48]]

^<<v43-12-48,48>>^ Quem me rejeita e não recebe as minhas palavras tem quem o julgue; a própria palavra que falei, essa o julgará no último dia.

[[v43-12-49]]

^<<v43-12-49,49>>^ Porque eu não falei por mim mesmo, mas o Pai, que me enviou, esse me ordenou o que dizer e o que anunciar.

[[v43-12-50]]

^<<v43-12-50,50>>^ E sei que o seu mandamento é a vida eterna. Portanto, as coisas que eu digo, digo exatamente assim como o Pai me falou.

'''

xref:043-joao/043-joao-011.adoc#v43-11-0[&#60; Capítulo Anterior] | <<v43-12-0,Topo>> | xref:043-joao/043-joao-013.adoc#v43-13-0[Próximo Capítulo &#62;]