include::./index.adoc[]

[[v43-6-0]]
=== João, 6
// naa ?, NAA - Nova Almeida Atualizada

[[v43-6-1]]

^<<v43-6-1,1>>^ Depois dessas coisas, Jesus atravessou o mar da Galileia, que é o de Tiberíades.

[[v43-6-2]]

^<<v43-6-2,2>>^ Uma grande multidão o seguia, porque tinham visto os sinais que ele fazia na cura dos enfermos.

[[v43-6-3]]

^<<v43-6-3,3>>^ Então Jesus subiu ao monte e sentou-se ali com os seus discípulos.

[[v43-6-4]]

^<<v43-6-4,4>>^ Ora, a Páscoa, festa dos judeus, estava próxima.

[[v43-6-5]]

^<<v43-6-5,5>>^ Então Jesus, erguendo os olhos e vendo que uma grande multidão se aproximava, disse a Filipe: — Onde compraremos pão para lhes dar de comer?

[[v43-6-6]]

^<<v43-6-6,6>>^ Mas Jesus dizia isto para testá-lo, porque sabia o que estava para fazer.

[[v43-6-7]]

^<<v43-6-7,7>>^ Filipe respondeu: — Nem mesmo duzentos denários de pão seriam suficientes para que cada um recebesse um pedaço.

[[v43-6-8]]

^<<v43-6-8,8>>^ Um dos discípulos, chamado André, irmão de Simão Pedro, disse a Jesus:

[[v43-6-9]]

^<<v43-6-9,9>>^ — Aqui está um menino que tem cinco pães de cevada e dois peixinhos. Mas o que é isto para tanta gente?

[[v43-6-10]]

^<<v43-6-10,10>>^ Jesus disse: — Façam com que todos se assentem no chão. Havia muita relva naquele lugar. Assim, os homens se assentaram, e eram quase cinco mil.

[[v43-6-11]]

^<<v43-6-11,11>>^ Então Jesus pegou os pães e, tendo dado graças, distribuiu-os entre eles; e também igualmente os peixes, tanto quanto queriam.

[[v43-6-12]]

^<<v43-6-12,12>>^ E, quando já estavam satisfeitos, Jesus disse aos seus discípulos: — Recolham os pedaços que sobraram, para que nada se perca.

[[v43-6-13]]

^<<v43-6-13,13>>^ Assim, pois, o fizeram e encheram doze cestos de pedaços dos cinco pães de cevada, que sobraram depois que todos tinham comido.

[[v43-6-14]]

^<<v43-6-14,14>>^ Quando as pessoas viram o sinal que Jesus havia feito, disseram: — Este é verdadeiramente o profeta que devia vir ao mundo.

[[v43-6-15]]

^<<v43-6-15,15>>^ Jesus ficou sabendo que estavam para vir com a intenção de fazê-lo rei à força. Então ele se retirou outra vez, sozinho, para o monte.

[[v43-6-16]]

^<<v43-6-16,16>>^ Ao final do dia, os discípulos de Jesus desceram para o mar.

[[v43-6-17]]

^<<v43-6-17,17>>^ E, entrando num barco, passaram para o outro lado, rumo a Cafarnaum. Já estava escuro, e Jesus ainda não tinha ido até onde eles estavam.

[[v43-6-18]]

^<<v43-6-18,18>>^ E o mar começava a ficar agitado, porque soprava um vento forte.

[[v43-6-19]]

^<<v43-6-19,19>>^ Os discípulos já tinham navegado uns cinco ou seis quilômetros, quando viram Jesus andando sobre o mar, aproximando-se do barco; e ficaram com medo.

[[v43-6-20]]

^<<v43-6-20,20>>^ Mas Jesus lhes disse: — Sou eu. Não tenham medo!

[[v43-6-21]]

^<<v43-6-21,21>>^ Então eles o receberam com alegria, e logo o barco chegou ao seu destino.

[[v43-6-22]]

^<<v43-6-22,22>>^ No dia seguinte, a multidão que tinha ficado do outro lado do mar notou que ali havia apenas um pequeno barco e que Jesus não tinha entrado nele com os seus discípulos, tendo estes partido sozinhos.

[[v43-6-23]]

^<<v43-6-23,23>>^ Entretanto, outros barquinhos de Tiberíades se aproximaram do lugar onde a multidão havia comido o pão depois que o Senhor deu graças.

[[v43-6-24]]

^<<v43-6-24,24>>^ Quando aquela multidão viu que Jesus não estava ali nem os seus discípulos, entraram nos barcos e partiram para Cafarnaum à procura de Jesus.

[[v43-6-25]]

^<<v43-6-25,25>>^ E, tendo-o encontrado no outro lado do mar, lhe perguntaram: — Mestre, quando o senhor chegou aqui?

[[v43-6-26]]

^<<v43-6-26,26>>^ Jesus respondeu: — Em verdade, em verdade lhes digo que vocês estão me procurando não porque viram sinais, mas porque comeram os pães e ficaram satisfeitos.

[[v43-6-27]]

^<<v43-6-27,27>>^ Trabalhem, não pela comida que se estraga, mas pela que permanece para a vida eterna, a qual o Filho do Homem dará a vocês; porque Deus, o Pai, o confirmou com o seu selo.

[[v43-6-28]]

^<<v43-6-28,28>>^ Então lhe perguntaram: — Que faremos para realizar as obras de Deus?

[[v43-6-29]]

^<<v43-6-29,29>>^ Jesus respondeu: — A obra de Deus é esta: que vocês creiam naquele que ele enviou.

[[v43-6-30]]

^<<v43-6-30,30>>^ Então eles disseram: — Que sinal o senhor fará para que vejamos e creiamos no senhor? O que o senhor pode fazer?

[[v43-6-31]]

^<<v43-6-31,31>>^ Nossos pais comeram o maná no deserto, como está escrito: "Deu-lhes a comer pão do céu."

[[v43-6-32]]

^<<v43-6-32,32>>^ Jesus lhes disse: — Em verdade, em verdade lhes digo que não foi Moisés quem deu o pão do céu para vocês; quem lhes dá o verdadeiro pão do céu é meu Pai.

[[v43-6-33]]

^<<v43-6-33,33>>^ Porque o pão de Deus é o que desce do céu e dá vida ao mundo.

[[v43-6-34]]

^<<v43-6-34,34>>^ Então lhe disseram: — Senhor, dê-nos sempre desse pão.

[[v43-6-35]]

^<<v43-6-35,35>>^ Jesus respondeu: — Eu sou o pão da vida. Quem vem a mim jamais terá fome, e quem crê em mim jamais terá sede.

[[v43-6-36]]

^<<v43-6-36,36>>^ Porém eu já disse que vocês não creem, embora estejam me vendo.

[[v43-6-37]]

^<<v43-6-37,37>>^ Todo aquele que o Pai me dá, esse virá a mim; e o que vem a mim, de modo nenhum o lançarei fora.

[[v43-6-38]]

^<<v43-6-38,38>>^ Porque eu desci do céu, não para fazer a minha própria vontade, mas a vontade daquele que me enviou.

[[v43-6-39]]

^<<v43-6-39,39>>^ E a vontade de quem me enviou é esta: que eu não perca nenhum de todos os que ele me deu; pelo contrário, eu o ressuscitarei no último dia.

[[v43-6-40]]

^<<v43-6-40,40>>^ De fato, a vontade de meu Pai é que todo aquele que vir o Filho e nele crer tenha a vida eterna; e eu o ressuscitarei no último dia.

[[v43-6-41]]

^<<v43-6-41,41>>^ Então os judeus começaram a murmurar contra ele, porque tinha dito: "Eu sou o pão que desceu do céu."

[[v43-6-42]]

^<<v43-6-42,42>>^ E diziam: — Este não é Jesus, o filho de José? Por acaso não conhecemos o pai e a mãe dele? Como é que ele agora diz: "Desci do céu"?

[[v43-6-43]]

^<<v43-6-43,43>>^ Jesus respondeu: — Não fiquem murmurando entre vocês.

[[v43-6-44]]

^<<v43-6-44,44>>^ Ninguém pode vir a mim se o Pai, que me enviou, não o trouxer; e eu o ressuscitarei no último dia.

[[v43-6-45]]

^<<v43-6-45,45>>^ Está escrito nos Profetas: "E todos serão ensinados por Deus." Portanto, todo aquele que ouviu e aprendeu do Pai, esse vem a mim.

[[v43-6-46]]

^<<v43-6-46,46>>^ Não que alguém tenha visto o Pai, a não ser aquele que vem de Deus; este já viu o Pai.

[[v43-6-47]]

^<<v43-6-47,47>>^ — Em verdade, em verdade lhes digo: quem crê em mim tem a vida eterna.

[[v43-6-48]]

^<<v43-6-48,48>>^ Eu sou o pão da vida.

[[v43-6-49]]

^<<v43-6-49,49>>^ Os pais de vocês comeram o maná no deserto e morreram.

[[v43-6-50]]

^<<v43-6-50,50>>^ Este é o pão que desce do céu, para que todo o que dele comer não pereça.

[[v43-6-51]]

^<<v43-6-51,51>>^ Eu sou o pão vivo que desceu do céu; se alguém comer deste pão, viverá eternamente. E o pão que eu darei pela vida do mundo é a minha carne.

[[v43-6-52]]

^<<v43-6-52,52>>^ Então os judeus começaram a discutir entre si, dizendo: — Como é que este pode nos dar a sua própria carne para comer?

[[v43-6-53]]

^<<v43-6-53,53>>^ Jesus respondeu: — Em verdade, em verdade lhes digo que, se vocês não comerem a carne do Filho do Homem e não beberem o seu sangue, não terão vida em vocês mesmos.

[[v43-6-54]]

^<<v43-6-54,54>>^ Quem come a minha carne e bebe o meu sangue tem a vida eterna, e eu o ressuscitarei no último dia.

[[v43-6-55]]

^<<v43-6-55,55>>^ Pois a minha carne é verdadeira comida, e o meu sangue é verdadeira bebida.

[[v43-6-56]]

^<<v43-6-56,56>>^ Quem come a minha carne e bebe o meu sangue permanece em mim, e eu permaneço nele.

[[v43-6-57]]

^<<v43-6-57,57>>^ Assim como o Pai, que vive, me enviou, e igualmente eu vivo por causa do Pai, também quem de mim se alimenta viverá por mim.

[[v43-6-58]]

^<<v43-6-58,58>>^ Este é o pão que desceu do céu, em nada semelhante àquele que os pais de vocês comeram e, mesmo assim, morreram; quem comer este pão viverá eternamente.

[[v43-6-59]]

^<<v43-6-59,59>>^ Jesus disse essas coisas quando ensinava na sinagoga de Cafarnaum.

[[v43-6-60]]

^<<v43-6-60,60>>^ Muitos dos seus discípulos, tendo ouvido tais palavras, disseram: — Duro é este discurso; quem pode suportá-lo?

[[v43-6-61]]

^<<v43-6-61,61>>^ Mas Jesus, sabendo por si mesmo que os seus discípulos murmuravam a respeito do que ele havia falado, disse-lhes: — Isto escandaliza vocês?

[[v43-6-62]]

^<<v43-6-62,62>>^ Que acontecerá, então, se virem o Filho do Homem subir para o lugar onde primeiro estava?

[[v43-6-63]]

^<<v43-6-63,63>>^ O Espírito é o que vivifica; a carne para nada aproveita. As palavras que eu lhes tenho falado são espírito e são vida.

[[v43-6-64]]

^<<v43-6-64,64>>^ Mas há descrentes entre vocês. Ora, Jesus sabia, desde o princípio, quais eram os que não criam e quem iria traí-lo.

[[v43-6-65]]

^<<v43-6-65,65>>^ E prosseguiu: — Por causa disto é que falei para vocês que ninguém poderá vir a mim, se não lhe for concedido pelo Pai.

[[v43-6-66]]

^<<v43-6-66,66>>^ Diante disso, muitos dos seus discípulos o abandonaram e já não andavam com ele.

[[v43-6-67]]

^<<v43-6-67,67>>^ Então Jesus perguntou aos doze: — Será que vocês também querem se retirar?

[[v43-6-68]]

^<<v43-6-68,68>>^ Simão Pedro respondeu: — Senhor, para quem iremos? O senhor tem as palavras da vida eterna,

[[v43-6-69]]

^<<v43-6-69,69>>^ e nós temos crido e conhecido que o senhor é o Santo de Deus.

[[v43-6-70]]

^<<v43-6-70,70>>^ Então Jesus lhes disse: — Não é fato que eu escolhi vocês, os doze? Mas um de vocês é um diabo.

[[v43-6-71]]

^<<v43-6-71,71>>^ Ele se referia a Judas, filho de Simão Iscariotes, porque este, sendo um dos doze, era quem o haveria de trair.

'''

xref:043-joao/043-joao-005.adoc#v43-5-0[&#60; Capítulo Anterior] | <<v43-6-0,Topo>> | xref:043-joao/043-joao-007.adoc#v43-7-0[Próximo Capítulo &#62;]