include::./index.adoc[]

[[v43-5-0]]
=== João, 5
// naa ?, NAA - Nova Almeida Atualizada

[[v43-5-1]]

^<<v43-5-1,1>>^ Passadas essas coisas, havia uma festa dos judeus, e Jesus foi para Jerusalém.

[[v43-5-2]]

^<<v43-5-2,2>>^ Existe ali, junto ao Portão das Ovelhas, um tanque, chamado em hebraico Betesda, o qual tem cinco pórticos.

[[v43-5-3]]

^<<v43-5-3,3>>^ Nestes jazia uma multidão de enfermos, cegos, coxos, paralíticos

[[v43-5-4]]

^<<v43-5-4,4>>^ &#91;esperando que a água se movesse. Porque um anjo descia de tempos em tempos, agitando-a; e o primeiro a entrar no tanque, uma vez agitada a água, sarava de qualquer doença que tivesse&#93;.

[[v43-5-5]]

^<<v43-5-5,5>>^ Estava ali um homem enfermo havia trinta e oito anos.

[[v43-5-6]]

^<<v43-5-6,6>>^ Jesus, vendo-o deitado e sabendo que estava assim havia muito tempo, perguntou: — Você quer ser curado?

[[v43-5-7]]

^<<v43-5-7,7>>^ O enfermo respondeu: — Senhor, não tenho ninguém que me ponha no tanque, quando a água é agitada. Quando tento entrar, outro enfermo chega antes de mim.

[[v43-5-8]]

^<<v43-5-8,8>>^ Então Jesus lhe disse: — Levante-se, pegue o seu leito e ande.

[[v43-5-9]]

^<<v43-5-9,9>>^ Imediatamente o homem se viu curado e, pegando o leito, começou a andar. E aquele dia era sábado.

[[v43-5-10]]

^<<v43-5-10,10>>^ Por isso, os judeus disseram ao que tinha sido curado: — É sábado, e neste dia você não tem permissão para carregar o seu leito.

[[v43-5-11]]

^<<v43-5-11,11>>^ Ao que ele lhes respondeu: — O mesmo que me curou me disse: "Pegue o seu leito e ande."

[[v43-5-12]]

^<<v43-5-12,12>>^ Perguntaram-lhe: — Quem é o homem que disse a você: "Pegue o seu leito e ande"?

[[v43-5-13]]

^<<v43-5-13,13>>^ Aquele que tinha sido curado não soube responder, porque Jesus tinha se retirado, por haver muita gente naquele lugar.

[[v43-5-14]]

^<<v43-5-14,14>>^ Mais tarde, Jesus o encontrou no templo e lhe disse: — Olhe, você foi curado. Não peque mais, para que não lhe aconteça coisa pior.

[[v43-5-15]]

^<<v43-5-15,15>>^ O homem se retirou e disse aos judeus que tinha sido Jesus quem o havia curado.

[[v43-5-16]]

^<<v43-5-16,16>>^ E por isso os judeus perseguiam Jesus, porque fazia essas coisas no sábado.

[[v43-5-17]]

^<<v43-5-17,17>>^ Mas Jesus lhes disse: — Meu Pai trabalha até agora, e eu trabalho também.

[[v43-5-18]]

^<<v43-5-18,18>>^ Por isso, os judeus cada vez mais queriam matá-lo, porque além de desrespeitar o sábado, também dizia que Deus era seu próprio Pai, fazendo-se igual a Deus.

[[v43-5-19]]

^<<v43-5-19,19>>^ Então Jesus lhes disse: — Em verdade, em verdade lhes digo que o Filho nada pode fazer por si mesmo, senão somente aquilo que vê o Pai fazer; porque tudo o que este fizer, o Filho também faz.

[[v43-5-20]]

^<<v43-5-20,20>>^ Porque o Pai ama o Filho e lhe mostra tudo o que faz; e maiores obras do que estas lhe mostrará, para que vocês fiquem maravilhados.

[[v43-5-21]]

^<<v43-5-21,21>>^ Pois assim como o Pai ressuscita e vivifica os mortos, assim também o Filho vivifica aqueles a quem quer.

[[v43-5-22]]

^<<v43-5-22,22>>^ E o Pai não julga ninguém, mas confiou todo julgamento ao Filho,

[[v43-5-23]]

^<<v43-5-23,23>>^ para que todos honrem o Filho assim como honram o Pai. Quem não honra o Filho não honra o Pai que o enviou.

[[v43-5-24]]

^<<v43-5-24,24>>^ — Em verdade, em verdade lhes digo: quem ouve a minha palavra e crê naquele que me enviou tem a vida eterna, não entra em juízo, mas passou da morte para a vida.

[[v43-5-25]]

^<<v43-5-25,25>>^ Em verdade, em verdade lhes digo que vem a hora — e já chegou — em que os mortos ouvirão a voz do Filho de Deus; e os que a ouvirem viverão.

[[v43-5-26]]

^<<v43-5-26,26>>^ Porque assim como o Pai tem vida em si mesmo, também concedeu ao Filho ter vida em si mesmo.

[[v43-5-27]]

^<<v43-5-27,27>>^ E lhe deu autoridade para julgar, porque é o Filho do Homem.

[[v43-5-28]]

^<<v43-5-28,28>>^ Não fiquem maravilhados com isso, porque vem a hora em que todos os que se acham nos túmulos ouvirão a voz dele e sairão:

[[v43-5-29]]

^<<v43-5-29,29>>^ os que tiverem feito o bem, para a ressurreição da vida; e os que tiverem praticado o mal, para a ressurreição do juízo.

[[v43-5-30]]

^<<v43-5-30,30>>^ — Eu nada posso fazer por mim mesmo; assim como ouço, julgo. O meu juízo é justo, porque não procuro a minha própria vontade, e sim a daquele que me enviou.

[[v43-5-31]]

^<<v43-5-31,31>>^ Se eu dou testemunho a respeito de mim mesmo, o meu testemunho não é verdadeiro.

[[v43-5-32]]

^<<v43-5-32,32>>^ Outro é o que dá testemunho a respeito de mim, e sei que o testemunho que ele dá a respeito de mim é verdadeiro.

[[v43-5-33]]

^<<v43-5-33,33>>^ Vocês mandaram mensageiros a João, e ele deu testemunho da verdade.

[[v43-5-34]]

^<<v43-5-34,34>>^ Eu, porém, não recebo testemunho humano, mas digo essas coisas para que vocês sejam salvos.

[[v43-5-35]]

^<<v43-5-35,35>>^ — João era a lâmpada que estava acesa e iluminava, e, por algum tempo, vocês quiseram se alegrar com a sua luz.

[[v43-5-36]]

^<<v43-5-36,36>>^ Mas eu tenho maior testemunho que o de João; porque as obras que o Pai me confiou para que eu as realizasse, essas que eu faço testemunham a meu respeito de que o Pai me enviou.

[[v43-5-37]]

^<<v43-5-37,37>>^ O Pai, que me enviou, esse mesmo é que tem dado testemunho de mim. Vocês nunca ouviram a voz dele, nem viram a sua forma.

[[v43-5-38]]

^<<v43-5-38,38>>^ Também não têm a palavra dele permanente em vocês, porque não creem naquele a quem ele enviou.

[[v43-5-39]]

^<<v43-5-39,39>>^ Vocês examinam as Escrituras, porque julgam ter nelas a vida eterna, e são elas mesmas que testificam de mim.

[[v43-5-40]]

^<<v43-5-40,40>>^ Contudo, vocês não querem vir a mim para ter vida.

[[v43-5-41]]

^<<v43-5-41,41>>^ Eu não aceito glória que vem de pessoas;

[[v43-5-42]]

^<<v43-5-42,42>>^ sei, entretanto, que vocês não têm o amor de Deus em vocês.

[[v43-5-43]]

^<<v43-5-43,43>>^ Eu vim em nome de meu Pai, e vocês não me recebem; se outro vier em seu próprio nome, vocês certamente o receberão.

[[v43-5-44]]

^<<v43-5-44,44>>^ Como podem crer, vocês que aceitam glória uns dos outros e não procuram a glória que vem do Deus único?

[[v43-5-45]]

^<<v43-5-45,45>>^ Não pensem que eu os acusarei diante do Pai; quem acusa vocês é Moisés, em quem puseram a sua esperança.

[[v43-5-46]]

^<<v43-5-46,46>>^ Porque, se vocês, de fato, cressem em Moisés, também creriam em mim; pois ele escreveu a meu respeito.

[[v43-5-47]]

^<<v43-5-47,47>>^ Se, porém, não creem nos escritos dele, como crerão nas minhas palavras?

'''

xref:043-joao/043-joao-004.adoc#v43-4-0[&#60; Capítulo Anterior] | <<v43-5-0,Topo>> | xref:043-joao/043-joao-006.adoc#v43-6-0[Próximo Capítulo &#62;]