include::./index.adoc[]

[[v43-1-0]]
=== João, 1
// naa ?, NAA - Nova Almeida Atualizada

[[v43-1-1]]

^<<v43-1-1,1>>^ No princípio era o Verbo, e o Verbo estava com Deus, e o Verbo era Deus.

[[v43-1-2]]

^<<v43-1-2,2>>^ Ele estava no princípio com Deus.

[[v43-1-3]]

^<<v43-1-3,3>>^ Todas as coisas foram feitas por ele, e, sem ele, nada do que foi feito se fez.

[[v43-1-4]]

^<<v43-1-4,4>>^ A vida estava nele e a vida era a luz dos homens.

[[v43-1-5]]

^<<v43-1-5,5>>^ A luz resplandece nas trevas, e as trevas não prevaleceram contra ela.

[[v43-1-6]]

^<<v43-1-6,6>>^ Houve um homem enviado por Deus, e o nome dele era João.

[[v43-1-7]]

^<<v43-1-7,7>>^ Este veio como testemunha para testificar a respeito da luz, para que todos viessem a crer por meio dele.

[[v43-1-8]]

^<<v43-1-8,8>>^ Ele não era a luz, mas veio para dar testemunho da luz,

[[v43-1-9]]

^<<v43-1-9,9>>^ a verdadeira luz, que, vinda ao mundo, ilumina toda a humanidade.

[[v43-1-10]]

^<<v43-1-10,10>>^ O Verbo estava no mundo, o mundo foi feito por meio dele, mas o mundo não o conheceu.

[[v43-1-11]]

^<<v43-1-11,11>>^ Veio para o que era seu, e os seus não o receberam.

[[v43-1-12]]

^<<v43-1-12,12>>^ Mas, a todos quantos o receberam, deu-lhes o poder de serem feitos filhos de Deus, a saber, aos que creem no seu nome,

[[v43-1-13]]

^<<v43-1-13,13>>^ os quais não nasceram do sangue, nem da vontade da carne, nem da vontade do homem, mas de Deus.

[[v43-1-14]]

^<<v43-1-14,14>>^ E o Verbo se fez carne e habitou entre nós, cheio de graça e de verdade, e vimos a sua glória, glória como do unigênito do Pai.

[[v43-1-15]]

^<<v43-1-15,15>>^ João dá testemunho a respeito dele e exclama: — Este é aquele de quem eu dizia: "Ele vem depois de mim, mas é mais importante do que eu, pois já existia antes de mim."

[[v43-1-16]]

^<<v43-1-16,16>>^ Porque todos nós temos recebido da sua plenitude e graça sobre graça.

[[v43-1-17]]

^<<v43-1-17,17>>^ Porque a lei foi dada por meio de Moisés; a graça e a verdade vieram por meio de Jesus Cristo.

[[v43-1-18]]

^<<v43-1-18,18>>^ Ninguém jamais viu Deus; o Deus unigênito, que está junto do Pai, é quem o revelou.

[[v43-1-19]]

^<<v43-1-19,19>>^ Este foi o testemunho de João, quando os judeus lhe enviaram de Jerusalém sacerdotes e levitas para perguntar: "Quem é você?"

[[v43-1-20]]

^<<v43-1-20,20>>^ Ele confessou e não negou; confessou: — Eu não sou o Cristo.

[[v43-1-21]]

^<<v43-1-21,21>>^ Diante disso, lhe perguntaram: — Quem é você, então? Você é Elias? Ele disse: — Não sou. Então perguntaram: — Você é o profeta? Ele respondeu: — Não, não sou.

[[v43-1-22]]

^<<v43-1-22,22>>^ Disseram-lhe, então: — Diga quem é você, para podermos dar uma resposta àqueles que nos enviaram. O que é que você diz a respeito de si mesmo?

[[v43-1-23]]

^<<v43-1-23,23>>^ Então ele respondeu: — Eu sou "a voz do que clama no deserto: Endireitem o caminho do Senhor", como disse o profeta Isaías.

[[v43-1-24]]

^<<v43-1-24,24>>^ Ora, os que haviam sido enviados eram do grupo dos fariseus.

[[v43-1-25]]

^<<v43-1-25,25>>^ E perguntaram a João: — Então por que você batiza, se não é o Cristo, nem Elias, nem o profeta?

[[v43-1-26]]

^<<v43-1-26,26>>^ João respondeu: — Eu batizo com água, mas no meio de vocês está alguém que vocês não conhecem.

[[v43-1-27]]

^<<v43-1-27,27>>^ Ele vem depois de mim, mas não sou digno de desamarrar as correias das suas sandálias.

[[v43-1-28]]

^<<v43-1-28,28>>^ Essas coisas aconteceram em Betânia, do outro lado do Jordão, onde João estava batizando.

[[v43-1-29]]

^<<v43-1-29,29>>^ No dia seguinte, vendo que Jesus vinha em sua direção, João disse: — Eis o Cordeiro de Deus, que tira o pecado do mundo!

[[v43-1-30]]

^<<v43-1-30,30>>^ Este é aquele a respeito de quem eu falava, quando disse: "Depois de mim vem um homem que é mais importante do que eu, porque já existia antes de mim."

[[v43-1-31]]

^<<v43-1-31,31>>^ Eu mesmo não o conhecia, mas vim batizando com água a fim de que ele fosse manifestado a Israel.

[[v43-1-32]]

^<<v43-1-32,32>>^ E João testemunhou, dizendo: — Vi o Espírito descer do céu como pomba e pousar sobre ele.

[[v43-1-33]]

^<<v43-1-33,33>>^ Eu não o conhecia; aquele, porém, que me enviou a batizar com água me disse: "Aquele sobre quem você vir descer e pousar o Espírito, esse é o que batiza com o Espírito Santo."

[[v43-1-34]]

^<<v43-1-34,34>>^ Pois eu mesmo vi e dou testemunho de que ele é o Filho de Deus.

[[v43-1-35]]

^<<v43-1-35,35>>^ No dia seguinte, João estava outra vez na companhia de dois dos seus discípulos

[[v43-1-36]]

^<<v43-1-36,36>>^ e, vendo Jesus passar, disse: — Eis o Cordeiro de Deus!

[[v43-1-37]]

^<<v43-1-37,37>>^ Os dois discípulos, ouvindo-o dizer isso, seguiram Jesus.

[[v43-1-38]]

^<<v43-1-38,38>>^ E Jesus, voltando-se e vendo que o seguiam, disse-lhes: — O que vocês estão procurando? Eles disseram: — Rabi, onde o senhor mora? ("Rabi" quer dizer "Mestre".)

[[v43-1-39]]

^<<v43-1-39,39>>^ Jesus respondeu: — Venham ver! Então eles foram, viram onde Jesus estava morando e ficaram com ele aquele dia. Eram mais ou menos quatro horas da tarde.

[[v43-1-40]]

^<<v43-1-40,40>>^ André, o irmão de Simão Pedro, era um dos dois que tinham ouvido o testemunho de João e seguido Jesus.

[[v43-1-41]]

^<<v43-1-41,41>>^ Ele encontrou primeiro o seu próprio irmão, Simão, a quem disse: — Achamos o Messias! ("Messias" quer dizer "Cristo".)

[[v43-1-42]]

^<<v43-1-42,42>>^ E o levou a Jesus. Jesus olhou para ele e disse: — Você é Simão, filho de João, mas agora será chamado Cefas.  ("Cefas" quer dizer "Pedro".)

[[v43-1-43]]

^<<v43-1-43,43>>^ No dia seguinte, Jesus resolveu ir para a Galileia e encontrou Filipe, a quem disse: — Siga-me.

[[v43-1-44]]

^<<v43-1-44,44>>^ Esse Filipe era de Betsaida, cidade de André e de Pedro.

[[v43-1-45]]

^<<v43-1-45,45>>^ Filipe encontrou Natanael e lhe disse: — Achamos aquele de quem Moisés escreveu na Lei, e a quem se referiram os profetas: Jesus, o Nazareno, filho de José.

[[v43-1-46]]

^<<v43-1-46,46>>^ Então Natanael perguntou: — De Nazaré pode sair alguma coisa boa? Filipe respondeu: — Venha ver!

[[v43-1-47]]

^<<v43-1-47,47>>^ Jesus viu Natanael se aproximar e disse a respeito dele: — Eis um verdadeiro israelita, em quem não existe fingimento algum!

[[v43-1-48]]

^<<v43-1-48,48>>^ Natanael perguntou a Jesus: — De onde o senhor me conhece? Jesus respondeu: — Antes de Filipe chamá-lo, eu já tinha visto você debaixo da figueira.

[[v43-1-49]]

^<<v43-1-49,49>>^ Então Natanael exclamou: — Mestre, o senhor é o Filho de Deus! O senhor é o Rei de Israel!

[[v43-1-50]]

^<<v43-1-50,50>>^ Ao que Jesus lhe respondeu: — Você crê porque eu disse que tinha visto você debaixo da figueira? Pois você verá coisas maiores do que estas.

[[v43-1-51]]

^<<v43-1-51,51>>^ E acrescentou: — Em verdade, em verdade lhes digo que vocês verão o céu aberto e os anjos de Deus subindo e descendo sobre o Filho do Homem.

'''

xref:042-lucas/042-lucas-024.adoc#v42-24-0[&#60; Capítulo Anterior] | <<v43-1-0,Topo>> | xref:043-joao/043-joao-002.adoc#v43-2-0[Próximo Capítulo &#62;]