include::./index.adoc[]

[[v43-18-0]]
=== João, 18
// naa ?, NAA - Nova Almeida Atualizada

[[v43-18-1]]

^<<v43-18-1,1>>^ Depois de dizer isso, Jesus saiu juntamente com os seus discípulos para o outro lado do ribeiro de Cedrom, onde havia um jardim; e aí entrou com eles.

[[v43-18-2]]

^<<v43-18-2,2>>^ Judas, o traidor, também conhecia aquele lugar, porque Jesus muitas vezes havia se reunido ali com os seus discípulos.

[[v43-18-3]]

^<<v43-18-3,3>>^ Tendo, pois, Judas recebido a escolta e alguns guardas da parte dos principais sacerdotes e fariseus, chegou a esse lugar com lanternas, tochas e armas.

[[v43-18-4]]

^<<v43-18-4,4>>^ Então Jesus, sabendo de tudo o que ia acontecer com ele, adiantou-se e perguntou-lhes: — A quem vocês estão procurando?

[[v43-18-5]]

^<<v43-18-5,5>>^ Eles responderam: — A Jesus, o Nazareno. Então Jesus lhes disse: — Sou eu. Ora, Judas, o traidor, também estava com eles.

[[v43-18-6]]

^<<v43-18-6,6>>^ Quando Jesus lhes disse: "Sou eu", recuaram e caíram por terra.

[[v43-18-7]]

^<<v43-18-7,7>>^ Jesus, de novo, lhes perguntou: — A quem vocês estão procurando? Responderam: — A Jesus, o Nazareno.

[[v43-18-8]]

^<<v43-18-8,8>>^ Então Jesus disse: — Já lhes falei que sou eu. Se é a mim que vocês estão procurando, deixem que estes vão embora.

[[v43-18-9]]

^<<v43-18-9,9>>^ Ele disse isso para se cumprir a palavra que tinha dito anteriormente: "Não perdi nenhum dos que me deste."

[[v43-18-10]]

^<<v43-18-10,10>>^ Então Simão Pedro puxou da espada que trazia e feriu o servo do sumo sacerdote, cortando-lhe a orelha direita. E o nome do servo era Malco.

[[v43-18-11]]

^<<v43-18-11,11>>^ Mas Jesus disse a Pedro: — Guarde a espada na bainha! Por acaso não beberei o cálice que o Pai me deu?

[[v43-18-12]]

^<<v43-18-12,12>>^ Assim, a escolta, o comandante e os guardas dos judeus prenderam Jesus e o amarraram.

[[v43-18-13]]

^<<v43-18-13,13>>^ Então o levaram primeiramente a Anás, sogro de Caifás, sumo sacerdote naquele ano.

[[v43-18-14]]

^<<v43-18-14,14>>^ Ora, Caifás era quem havia declarado aos judeus ser conveniente morrer um homem pelo povo.

[[v43-18-15]]

^<<v43-18-15,15>>^ Simão Pedro e outro discípulo seguiam Jesus. Esse discípulo era conhecido do sumo sacerdote e, por isso, conseguiu entrar no pátio da casa deste com Jesus.

[[v43-18-16]]

^<<v43-18-16,16>>^ Pedro, porém, ficou de fora, junto à porta. O outro discípulo, que era conhecido do sumo sacerdote, saiu, falou com a encarregada da porta e levou Pedro para dentro.

[[v43-18-17]]

^<<v43-18-17,17>>^ Então a empregada, encarregada da porta, perguntou a Pedro: — Você também não é um dos discípulos desse homem? Ele respondeu: — Não, não sou.

[[v43-18-18]]

^<<v43-18-18,18>>^ Os servos e os guardas estavam ali, tendo acendido uma fogueira por causa do frio, e se aqueciam. Pedro estava no meio deles, aquecendo-se também.

[[v43-18-19]]

^<<v43-18-19,19>>^ Então o sumo sacerdote interrogou Jesus a respeito dos seus discípulos e da sua doutrina.

[[v43-18-20]]

^<<v43-18-20,20>>^ Jesus lhe respondeu: — Eu tenho falado francamente ao mundo. Sempre ensinei, tanto nas sinagogas como no templo, onde todos os judeus se reúnem, e não disse nada em segredo.

[[v43-18-21]]

^<<v43-18-21,21>>^ Por que o senhor está perguntando para mim? Pergunte aos que ouviram o que lhes falei. Eles sabem muito bem o que eu disse.

[[v43-18-22]]

^<<v43-18-22,22>>^ Quando Jesus disse isto, um dos guardas que estavam ali deu-lhe uma bofetada, dizendo: — É assim que você fala com o sumo sacerdote?

[[v43-18-23]]

^<<v43-18-23,23>>^ Jesus lhe respondeu: — Se falei mal, dê testemunho do mal. Mas, se falei bem, por que você está me batendo?

[[v43-18-24]]

^<<v43-18-24,24>>^ Então Anás o enviou, amarrado, à presença de Caifás, o sumo sacerdote.

[[v43-18-25]]

^<<v43-18-25,25>>^ Simão Pedro estava em pé, aquecendo-se. Então lhe perguntaram: — Você também não é um dos discípulos dele? Ele negou e disse: — Não, não sou.

[[v43-18-26]]

^<<v43-18-26,26>>^ Um dos servos do sumo sacerdote, parente daquele a quem Pedro tinha decepado a orelha, perguntou: — Não é verdade que eu vi você no jardim com ele?

[[v43-18-27]]

^<<v43-18-27,27>>^ De novo, Pedro negou. E no mesmo instante o galo cantou.

[[v43-18-28]]

^<<v43-18-28,28>>^ Depois, levaram Jesus da casa de Caifás para o Pretório. Era cedo de manhã. Eles não entraram no Pretório para não se contaminar, pois somente assim poderiam comer a Páscoa.

[[v43-18-29]]

^<<v43-18-29,29>>^ Então Pilatos saiu para falar com eles e perguntou: — Que acusação vocês trazem contra este homem?

[[v43-18-30]]

^<<v43-18-30,30>>^ Eles responderam: — Se este não fosse malfeitor, não o teríamos entregue ao senhor.

[[v43-18-31]]

^<<v43-18-31,31>>^ Então Pilatos disse: — Levem-no daqui e julguem-no segundo a lei de vocês. Ao que os judeus responderam: — Não nos é lícito matar ninguém.

[[v43-18-32]]

^<<v43-18-32,32>>^ Isso aconteceu para que se cumprisse a palavra de Jesus, significando com que tipo de morte estava para morrer.

[[v43-18-33]]

^<<v43-18-33,33>>^ Pilatos entrou novamente no Pretório, chamou Jesus e lhe perguntou: — Você é o rei dos judeus?

[[v43-18-34]]

^<<v43-18-34,34>>^ Jesus respondeu: — Esta pergunta vem do senhor mesmo ou foram outros que lhe falaram a meu respeito?

[[v43-18-35]]

^<<v43-18-35,35>>^ Pilatos respondeu: — Por acaso sou judeu? A sua própria gente e os principais sacerdotes é que o entregaram a mim. Que foi que você fez?

[[v43-18-36]]

^<<v43-18-36,36>>^ Jesus respondeu: — O meu Reino não é deste mundo. Se o meu Reino fosse deste mundo, os meus ministros se empenhariam por mim, para que eu não fosse entregue aos judeus. Mas agora o meu Reino não é daqui.

[[v43-18-37]]

^<<v43-18-37,37>>^ Pilatos perguntou: — Então você é rei? Jesus respondeu: — O senhor está dizendo que sou rei. Eu para isso nasci e para isso vim ao mundo, a fim de dar testemunho da verdade. Todo aquele que é da verdade ouve a minha voz.

[[v43-18-38]]

^<<v43-18-38,38>>^ Pilatos perguntou: — O que é a verdade? Depois de dizer isso, Pilatos voltou aos judeus e lhes disse: — Eu não acho nele crime algum.

[[v43-18-39]]

^<<v43-18-39,39>>^ Mas é costume entre vocês que eu solte alguém por ocasião da Páscoa. Vocês querem que eu lhes solte o rei dos judeus?

[[v43-18-40]]

^<<v43-18-40,40>>^ Então todos gritaram, novamente: — Não este, mas Barrabás! Ora, Barrabás era salteador.

'''

xref:043-joao/043-joao-017.adoc#v43-17-0[&#60; Capítulo Anterior] | <<v43-18-0,Topo>> | xref:043-joao/043-joao-019.adoc#v43-19-0[Próximo Capítulo &#62;]