include::./index.adoc[]

[[v43-9-0]]
=== João, 9
// naa ?, NAA - Nova Almeida Atualizada

[[v43-9-1]]

^<<v43-9-1,1>>^ Enquanto Jesus caminhava, viu um homem cego de nascença.

[[v43-9-2]]

^<<v43-9-2,2>>^ E os seus discípulos perguntaram: — Mestre, quem pecou para que este homem nascesse cego? Ele ou os pais dele?

[[v43-9-3]]

^<<v43-9-3,3>>^ Jesus respondeu: — Nem ele pecou, nem os pais dele; mas isso aconteceu para que nele se manifestem as obras de Deus.

[[v43-9-4]]

^<<v43-9-4,4>>^ É necessário que façamos as obras daquele que me enviou enquanto é dia; a noite vem, quando ninguém pode trabalhar.

[[v43-9-5]]

^<<v43-9-5,5>>^ Enquanto estou no mundo, sou a luz do mundo.

[[v43-9-6]]

^<<v43-9-6,6>>^ Depois de dizer isso, Jesus cuspiu na terra, fez lama com a saliva e com a lama untou os olhos do cego.

[[v43-9-7]]

^<<v43-9-7,7>>^ Então disse ao cego: — Vá lavar-se no tanque de Siloé. Siloé quer dizer "Enviado". O cego foi, lavou-se e voltou vendo.

[[v43-9-8]]

^<<v43-9-8,8>>^ Então os vizinhos e os que antes o conheciam de vista, como mendigo, perguntavam: — Não é este o que ficava sentado pedindo esmolas?

[[v43-9-9]]

^<<v43-9-9,9>>^ Uns diziam: — É ele. Outros: — Não, mas se parece com ele. O homem dizia: — Sou eu.

[[v43-9-10]]

^<<v43-9-10,10>>^ Então lhe perguntaram: — Como foram abertos os seus olhos?

[[v43-9-11]]

^<<v43-9-11,11>>^ Ele respondeu: — O homem chamado Jesus fez lama, passou nos meus olhos e disse: "Vá ao tanque de Siloé e lave-se." Então fui, lavei-me e estou vendo.

[[v43-9-12]]

^<<v43-9-12,12>>^ Eles perguntaram: — Onde está ele? Respondeu: — Não sei.

[[v43-9-13]]

^<<v43-9-13,13>>^ Levaram aos fariseus aquele que antes era cego.

[[v43-9-14]]

^<<v43-9-14,14>>^ E era sábado o dia em que Jesus fez a lama e lhe abriu os olhos.

[[v43-9-15]]

^<<v43-9-15,15>>^ Então os fariseus lhe perguntaram outra vez como podia ver. Ele respondeu: — Ele pôs lama sobre os meus olhos, lavei-me e estou vendo.

[[v43-9-16]]

^<<v43-9-16,16>>^ Por isso, alguns dos fariseus diziam: — Esse homem não é de Deus, porque não guarda o sábado. Mas outros diziam: — Como pode um homem pecador fazer sinais como estes? E houve divisão entre eles.

[[v43-9-17]]

^<<v43-9-17,17>>^ De novo perguntaram ao cego: — O que você diz a respeito dele, uma vez que lhe abriu os olhos? Ele respondeu: — É um profeta.

[[v43-9-18]]

^<<v43-9-18,18>>^ Os judeus não acreditaram que ele tinha sido cego e que agora podia ver, enquanto não chamaram os pais dele

[[v43-9-19]]

^<<v43-9-19,19>>^ e lhes perguntaram: — É este o filho de vocês, que vocês dizem que nasceu cego? Como é que agora ele está vendo?

[[v43-9-20]]

^<<v43-9-20,20>>^ Então os pais responderam: — Sabemos que este é o nosso filho e que nasceu cego,

[[v43-9-21]]

^<<v43-9-21,21>>^ mas não sabemos como agora está vendo. E também não sabemos quem lhe abriu os olhos. Perguntem a ele, pois já tem idade e poderá falar por si mesmo.

[[v43-9-22]]

^<<v43-9-22,22>>^ Os pais dele disseram isso porque estavam com medo dos judeus, pois estes já tinham combinado que, se alguém confessasse que Jesus era o Cristo, seria expulso da sinagoga.

[[v43-9-23]]

^<<v43-9-23,23>>^ Foi por isso que os pais dele disseram: "Ele já tem idade e poderá falar por si mesmo."

[[v43-9-24]]

^<<v43-9-24,24>>^ Então chamaram, pela segunda vez, o homem que tinha sido cego e lhe disseram: — Diga a verdade diante de Deus; nós sabemos que esse homem é pecador.

[[v43-9-25]]

^<<v43-9-25,25>>^ Ele respondeu: — Se é pecador, não sei. Uma coisa sei: eu era cego e agora vejo.

[[v43-9-26]]

^<<v43-9-26,26>>^ Perguntaram-lhe outra vez: — O que ele fez a você? Como lhe abriu os olhos?

[[v43-9-27]]

^<<v43-9-27,27>>^ Ele respondeu: — Já lhes disse, mas vocês não ouviram. Por que querem ouvir outra vez? Por acaso vocês também querem se tornar discípulos dele?

[[v43-9-28]]

^<<v43-9-28,28>>^ Então o insultaram e lhe disseram: — Discípulo dele é você! Nós somos discípulos de Moisés.

[[v43-9-29]]

^<<v43-9-29,29>>^ Sabemos que Deus falou a Moisés, mas este nem sabemos de onde é.

[[v43-9-30]]

^<<v43-9-30,30>>^ O homem respondeu: — É estranho que vocês não saibam de onde ele é, mas ele me abriu os olhos.

[[v43-9-31]]

^<<v43-9-31,31>>^ Sabemos que Deus não atende a pecadores. Pelo contrário, se alguém teme a Deus e pratica a sua vontade, a este atende.

[[v43-9-32]]

^<<v43-9-32,32>>^ Desde que o mundo existe, jamais se ouviu que alguém tenha aberto os olhos a um cego de nascença.

[[v43-9-33]]

^<<v43-9-33,33>>^ Se este homem não fosse de Deus, não poderia ter feito nada.

[[v43-9-34]]

^<<v43-9-34,34>>^ Mas eles disseram: — Você nasceu cheio de pecado e quer nos ensinar? E o expulsaram.

[[v43-9-35]]

^<<v43-9-35,35>>^ Jesus ouviu que eles tinham expulsado o homem. Ao encontrá-lo, perguntou: — Você crê no Filho do Homem?

[[v43-9-36]]

^<<v43-9-36,36>>^ Ele respondeu: — Quem é, Senhor, para que eu creia nele?

[[v43-9-37]]

^<<v43-9-37,37>>^ E Jesus lhe disse: — Você já o tem visto, e é aquele que está falando com você.

[[v43-9-38]]

^<<v43-9-38,38>>^ Então ele afirmou: — Eu creio, Senhor! E o adorou.

[[v43-9-39]]

^<<v43-9-39,39>>^ Jesus continuou: — Eu vim a este mundo para juízo, a fim de que os que não veem vejam, e os que veem se tornem cegos.

[[v43-9-40]]

^<<v43-9-40,40>>^ Alguns dos fariseus que estavam perto dele perguntaram-lhe: — Por acaso também nós somos cegos?

[[v43-9-41]]

^<<v43-9-41,41>>^ Jesus respondeu: — Se vocês fossem cegos, não teriam pecado algum. Mas, porque agora dizem: "Nós vemos", o pecado de vocês permanece.

'''

xref:043-joao/043-joao-008.adoc#v43-8-0[&#60; Capítulo Anterior] | <<v43-9-0,Topo>> | xref:043-joao/043-joao-010.adoc#v43-10-0[Próximo Capítulo &#62;]