include::./index.adoc[]

[[v43-19-0]]
=== João, 19
// naa ?, NAA - Nova Almeida Atualizada

[[v43-19-1]]

^<<v43-19-1,1>>^ Por isso, Pilatos tomou Jesus e mandou açoitá-lo.

[[v43-19-2]]

^<<v43-19-2,2>>^ Os soldados teceram uma coroa de espinhos e a puseram na cabeça de Jesus. Também o vestiram com um manto de púrpura.

[[v43-19-3]]

^<<v43-19-3,3>>^ Chegavam-se a ele e diziam: — Salve, rei dos judeus! E davam-lhe bofetadas.

[[v43-19-4]]

^<<v43-19-4,4>>^ Pilatos saiu outra vez e disse aos judeus: — Eis que eu o apresento a vocês, para que saibam que não encontro nele crime algum.

[[v43-19-5]]

^<<v43-19-5,5>>^ Então Jesus saiu, trazendo a coroa de espinhos e o manto de púrpura. E Pilatos lhes disse: — Eis o homem!

[[v43-19-6]]

^<<v43-19-6,6>>^ Quando viram Jesus, os principais sacerdotes e os seus guardas gritaram: — Crucifique! Crucifique! Pilatos repetiu: — Levem-no daqui vocês mesmos e o crucifiquem, porque eu não encontro nele crime algum.

[[v43-19-7]]

^<<v43-19-7,7>>^ Os judeus responderam: — Temos uma lei e, segundo essa lei, ele deve morrer, porque se fez Filho de Deus.

[[v43-19-8]]

^<<v43-19-8,8>>^ Pilatos, ouvindo tal declaração, ficou ainda mais atemorizado

[[v43-19-9]]

^<<v43-19-9,9>>^ e, entrando outra vez no Pretório, perguntou a Jesus: — De onde você é? Mas Jesus não lhe deu resposta.

[[v43-19-10]]

^<<v43-19-10,10>>^ Então Pilatos o advertiu: — Você não me responde? Não sabe que tenho autoridade tanto para soltar você como para crucificá-lo?

[[v43-19-11]]

^<<v43-19-11,11>>^ Jesus respondeu: — O senhor não teria nenhuma autoridade sobre mim se de cima não lhe fosse dada. Por isso, quem me entregou ao senhor tem maior pecado.

[[v43-19-12]]

^<<v43-19-12,12>>^ A partir desse momento, Pilatos queria soltá-lo, mas os judeus gritavam: — Se você soltar este homem, não é amigo de César! Todo aquele que se faz rei é contra César!

[[v43-19-13]]

^<<v43-19-13,13>>^ Quando Pilatos ouviu essas palavras, trouxe Jesus para fora e sentou-se no tribunal, no lugar chamado Pavimento, em hebraico Gabatá.

[[v43-19-14]]

^<<v43-19-14,14>>^ E era a preparação da Páscoa, por volta do meio-dia. E Pilatos disse aos judeus: — Eis aqui o rei de vocês.

[[v43-19-15]]

^<<v43-19-15,15>>^ Eles, porém, clamavam: — Fora! Fora! Crucifique-o! Então Pilatos perguntou: — Devo crucificar o rei de vocês? Os principais sacerdotes responderam: — Não temos rei, senão César!

[[v43-19-16]]

^<<v43-19-16,16>>^ Então Pilatos entregou Jesus para ser crucificado, e eles o levaram.

[[v43-19-17]]

^<<v43-19-17,17>>^ Jesus, carregando ele mesmo a sua cruz, saiu para o lugar chamado Calvário, Gólgota em hebraico.

[[v43-19-18]]

^<<v43-19-18,18>>^ Ali o crucificaram e com ele outros dois, um de cada lado, e Jesus no meio.

[[v43-19-19]]

^<<v43-19-19,19>>^ Pilatos escreveu também um título e o colocou no alto da cruz. E o que estava escrito era: " Jesus Nazareno, o Rei dos Judeus ".

[[v43-19-20]]

^<<v43-19-20,20>>^ Muitos judeus leram este título, porque o lugar em que Jesus havia sido crucificado era perto da cidade; e estava escrito em hebraico, latim e grego.

[[v43-19-21]]

^<<v43-19-21,21>>^ Os principais sacerdotes dos judeus disseram a Pilatos: — Não escreva: "Rei dos judeus", e sim: "Ele disse: Sou o rei dos judeus."

[[v43-19-22]]

^<<v43-19-22,22>>^ Pilatos respondeu: — O que escrevi escrevi.

[[v43-19-23]]

^<<v43-19-23,23>>^ Os soldados, pois, quando crucificaram Jesus, pegaram as roupas dele e dividiram em quatro partes, uma parte para cada soldado; e pegaram também a túnica. A túnica, porém, era sem costura, toda tecida de alto a baixo.

[[v43-19-24]]

^<<v43-19-24,24>>^ Por isso, os soldados disseram uns aos outros: — Não a rasguemos, mas vamos tirar a sorte para ver quem ficará com ela. Isso aconteceu para que se cumprisse a Escritura, que diz: "Repartiram entre si as minhas roupas e sobre a minha túnica lançaram sortes." E foi isso que os soldados fizeram.

[[v43-19-25]]

^<<v43-19-25,25>>^ E junto à cruz estavam a mãe de Jesus, a irmã dela, Maria, mulher de Clopas, e Maria Madalena.

[[v43-19-26]]

^<<v43-19-26,26>>^ Vendo Jesus a sua mãe e junto dela o discípulo amado, disse: — Mulher, eis aí o seu filho.

[[v43-19-27]]

^<<v43-19-27,27>>^ Depois, disse ao discípulo: — Eis aí a sua mãe. Dessa hora em diante, o discípulo a tomou para casa.

[[v43-19-28]]

^<<v43-19-28,28>>^ Depois, vendo Jesus que tudo já estava consumado, para que se cumprisse a Escritura, disse: — Tenho sede!

[[v43-19-29]]

^<<v43-19-29,29>>^ Estava ali um vaso cheio de vinagre. Embeberam de vinagre uma esponja e, fixando-a num caniço de hissopo, aproximaram a esponja da boca de Jesus.

[[v43-19-30]]

^<<v43-19-30,30>>^ Quando Jesus tomou o vinagre, disse: — Está consumado! E, inclinando a cabeça, entregou o espírito.

[[v43-19-31]]

^<<v43-19-31,31>>^ Então, para que os corpos não ficassem na cruz durante o sábado, visto que era o dia da preparação e era grande o dia daquele sábado, os judeus pediram a Pilatos que fossem quebradas as pernas dos crucificados e fossem tirados das cruzes.

[[v43-19-32]]

^<<v43-19-32,32>>^ Os soldados quebraram as pernas dos homens que tinham sido crucificados com Jesus, primeiro de um, depois do outro.

[[v43-19-33]]

^<<v43-19-33,33>>^ Quando, porém, chegaram a Jesus, vendo que já estava morto, não lhe quebraram as pernas.

[[v43-19-34]]

^<<v43-19-34,34>>^ Mas um dos soldados lhe abriu o lado com uma lança, e logo saiu sangue e água.

[[v43-19-35]]

^<<v43-19-35,35>>^ Aquele que viu isso dá testemunho, e o testemunho dele é verdadeiro. E ele sabe que diz a verdade, para que também vocês creiam.

[[v43-19-36]]

^<<v43-19-36,36>>^ E isso aconteceu para que se cumprisse a Escritura: "Nenhum dos seus ossos será quebrado."

[[v43-19-37]]

^<<v43-19-37,37>>^ E outra vez diz a Escritura: "Olharão para aquele a quem traspassaram."

[[v43-19-38]]

^<<v43-19-38,38>>^ Depois disso, José de Arimateia, que era discípulo de Jesus — ainda que em segredo, porque tinha medo dos judeus —, pediu a Pilatos permissão para tirar o corpo de Jesus. E Pilatos deu permissão. Então José de Arimateia foi e retirou o corpo de Jesus.

[[v43-19-39]]

^<<v43-19-39,39>>^ E Nicodemos, aquele que anteriormente tinha ido falar com Jesus à noite, também foi, levando cerca de trinta e cinco quilos de um composto de mirra e aloés.

[[v43-19-40]]

^<<v43-19-40,40>>^ Tomaram, pois, o corpo de Jesus e o envolveram em lençóis com os óleos aromáticos, como é costume entre os judeus na preparação para o sepultamento.

[[v43-19-41]]

^<<v43-19-41,41>>^ No lugar onde Jesus foi crucificado havia um jardim; neste jardim havia um túmulo novo, no qual ninguém ainda tinha sido colocado.

[[v43-19-42]]

^<<v43-19-42,42>>^ Ali, por causa da preparação dos judeus e porque o túmulo ficava perto, colocaram o corpo de Jesus.

'''

xref:043-joao/043-joao-018.adoc#v43-18-0[&#60; Capítulo Anterior] | <<v43-19-0,Topo>> | xref:043-joao/043-joao-020.adoc#v43-20-0[Próximo Capítulo &#62;]