include::./index.adoc[]

[[v43-17-0]]
=== João, 17
// naa ?, NAA - Nova Almeida Atualizada

[[v43-17-1]]

^<<v43-17-1,1>>^ Depois de dizer essas coisas, Jesus levantou os olhos ao céu e disse: — Pai, é chegada a hora. Glorifica o teu Filho, para que o Filho glorifique a ti,

[[v43-17-2]]

^<<v43-17-2,2>>^ assim como lhe deste autoridade sobre toda a humanidade, a fim de que ele conceda a vida eterna a todos os que lhe deste.

[[v43-17-3]]

^<<v43-17-3,3>>^ E a vida eterna é esta: que conheçam a ti, o único Deus verdadeiro, e a Jesus Cristo, a quem enviaste.

[[v43-17-4]]

^<<v43-17-4,4>>^ Eu te glorifiquei na terra, realizando a obra que me deste para fazer.

[[v43-17-5]]

^<<v43-17-5,5>>^ E agora, ó Pai, glorifica-me contigo mesmo com a glória que eu tive junto de ti, antes que houvesse mundo.

[[v43-17-6]]

^<<v43-17-6,6>>^ Manifestei o teu nome àqueles que me deste do mundo. Eram teus, tu os deste a mim, e eles têm guardado a tua palavra.

[[v43-17-7]]

^<<v43-17-7,7>>^ Agora eles reconhecem que todas as coisas que me tens dado provêm de ti,

[[v43-17-8]]

^<<v43-17-8,8>>^ porque eu lhes tenho transmitido as palavras que me deste, e eles as receberam, verdadeiramente reconheceram que saí de ti e creram que tu me enviaste.

[[v43-17-9]]

^<<v43-17-9,9>>^ — É por eles que eu peço; não peço pelo mundo, mas por aqueles que me deste, porque são teus.

[[v43-17-10]]

^<<v43-17-10,10>>^ Todas as minhas coisas são tuas, e as tuas coisas são minhas; e, neles, eu sou glorificado.

[[v43-17-11]]

^<<v43-17-11,11>>^ Já não estou no mundo, mas eles continuam no mundo, enquanto eu vou para junto de ti. Pai santo, guarda-os em teu nome, que me deste, para que eles sejam um, assim como nós somos um.

[[v43-17-12]]

^<<v43-17-12,12>>^ Quando eu estava com eles, guardava-os no teu nome, que me deste; eu os protegi e nenhum deles se perdeu, exceto o filho da perdição, para que se cumprisse a Escritura.

[[v43-17-13]]

^<<v43-17-13,13>>^ Mas agora vou para junto de ti e isto falo no mundo para que eles tenham a minha alegria completa em si mesmos.

[[v43-17-14]]

^<<v43-17-14,14>>^ Eu lhes tenho dado a tua palavra, e o mundo os odiou, porque eles não são do mundo, como também eu não sou.

[[v43-17-15]]

^<<v43-17-15,15>>^ Não peço que os tires do mundo, mas que os guardes do mal.

[[v43-17-16]]

^<<v43-17-16,16>>^ Eles não são do mundo, como também eu não sou.

[[v43-17-17]]

^<<v43-17-17,17>>^ Santifica-os na verdade; a tua palavra é a verdade.

[[v43-17-18]]

^<<v43-17-18,18>>^ Assim como tu me enviaste ao mundo, também eu os enviei ao mundo.

[[v43-17-19]]

^<<v43-17-19,19>>^ E a favor deles eu me santifico, para que eles também sejam santificados na verdade.

[[v43-17-20]]

^<<v43-17-20,20>>^ — Não peço somente por estes, mas também por aqueles que vierem a crer em mim, por meio da palavra que eles falarem,

[[v43-17-21]]

^<<v43-17-21,21>>^ a fim de que todos sejam um. E como tu, ó Pai, estás em mim e eu em ti, também eles estejam em nós, para que o mundo creia que tu me enviaste.

[[v43-17-22]]

^<<v43-17-22,22>>^ Eu lhes transmiti a glória que me deste, para que sejam um, como nós o somos;

[[v43-17-23]]

^<<v43-17-23,23>>^ eu neles, e tu em mim, a fim de que sejam aperfeiçoados na unidade, para que o mundo conheça que tu me enviaste e os amaste, como também amaste a mim.

[[v43-17-24]]

^<<v43-17-24,24>>^ — Pai, a minha vontade é que, onde eu estou, também estejam comigo os que me deste, para que vejam a minha glória que me conferiste, porque me amaste antes da fundação do mundo.

[[v43-17-25]]

^<<v43-17-25,25>>^ Pai justo, o mundo não te conheceu. Eu, porém, te conheci, e também estes reconheceram que tu me enviaste.

[[v43-17-26]]

^<<v43-17-26,26>>^ Eu lhes fiz conhecer o teu nome e ainda o farei conhecer, a fim de que o amor com que me amaste esteja neles, e eu neles esteja.

'''

xref:043-joao/043-joao-016.adoc#v43-16-0[&#60; Capítulo Anterior] | <<v43-17-0,Topo>> | xref:043-joao/043-joao-018.adoc#v43-18-0[Próximo Capítulo &#62;]