include::./index.adoc[]

[[v43-21-0]]
=== João, 21
// naa ?, NAA - Nova Almeida Atualizada

[[v43-21-1]]

^<<v43-21-1,1>>^ Depois disso, Jesus se manifestou outra vez aos discípulos junto ao mar de Tiberíades. Foi assim que ele se manifestou:

[[v43-21-2]]

^<<v43-21-2,2>>^ Estavam juntos Simão Pedro, Tomé, chamado Dídimo, Natanael, que era de Caná da Galileia, os filhos de Zebedeu e mais dois discípulos de Jesus.

[[v43-21-3]]

^<<v43-21-3,3>>^ Simão Pedro disse aos outros: — Vou pescar. Os outros responderam: — Nós também vamos com você. Foram e entraram no barco, mas, naquela noite, não pegaram nada.

[[v43-21-4]]

^<<v43-21-4,4>>^ Ao romper o dia, Jesus estava na praia, mas os discípulos não reconheceram que era ele.

[[v43-21-5]]

^<<v43-21-5,5>>^ Jesus lhes perguntou: — Filhos, será que vocês têm aí alguma coisa para comer? Eles responderam: — Não.

[[v43-21-6]]

^<<v43-21-6,6>>^ Então Jesus disse: — Joguem a rede à direita do barco e vocês acharão. Assim fizeram e já não podiam puxar a rede, tão grande era a quantidade de peixes.

[[v43-21-7]]

^<<v43-21-7,7>>^ E o discípulo a quem Jesus amava disse a Pedro: — É o Senhor! Simão Pedro, ouvindo que era o Senhor, cingiu-se com a sua túnica, porque tinha tirado a roupa, e lançou-se ao mar.

[[v43-21-8]]

^<<v43-21-8,8>>^ Os outros discípulos vieram no barquinho puxando a rede com os peixes, porque estavam somente a uns noventa metros da margem.

[[v43-21-9]]

^<<v43-21-9,9>>^ Ao saltarem em terra, viram ali umas brasas com peixe por cima; e também havia pão.

[[v43-21-10]]

^<<v43-21-10,10>>^ Jesus lhes disse: — Tragam alguns dos peixes que vocês acabaram de pegar.

[[v43-21-11]]

^<<v43-21-11,11>>^ Simão Pedro entrou no barco e arrastou a rede para a terra. A rede estava cheia, com cento e cinquenta e três grandes peixes. E, mesmo sendo tantos peixes, a rede não se rompeu.

[[v43-21-12]]

^<<v43-21-12,12>>^ Jesus disse a eles: — Venham comer. Nenhum dos discípulos ousava perguntar: "Quem é você?" Porque sabiam que era o Senhor.

[[v43-21-13]]

^<<v43-21-13,13>>^ Jesus veio, pegou o pão e deu a eles. Depois fez a mesma coisa com o peixe.

[[v43-21-14]]

^<<v43-21-14,14>>^ E esta já era a terceira vez que Jesus se manifestava aos seus discípulos depois de ressuscitado dentre os mortos.

[[v43-21-15]]

^<<v43-21-15,15>>^ Depois de terem comido, Jesus perguntou a Simão Pedro: — Simão, filho de João, você me ama mais do que estes outros me amam? Ele respondeu: — Sim, o Senhor sabe que eu o amo. Jesus lhe disse: — Apascente os meus cordeiros.

[[v43-21-16]]

^<<v43-21-16,16>>^ Jesus perguntou pela segunda vez: — Simão, filho de João, você me ama? Ele respondeu: — Sim, o Senhor sabe que eu o amo. Jesus lhe disse: — Pastoreie as minhas ovelhas.

[[v43-21-17]]

^<<v43-21-17,17>>^ Pela terceira vez Jesus lhe perguntou: — Simão, filho de João, você me ama? Pedro ficou triste por Jesus ter perguntado pela terceira vez: "Você me ama?" E respondeu: — O Senhor sabe todas as coisas; sabe que eu o amo. Jesus lhe disse: — Apascente as minhas ovelhas.

[[v43-21-18]]

^<<v43-21-18,18>>^ Em verdade, em verdade lhe digo que, quando era mais moço, você se cingia e andava por onde queria. Mas, quando você for velho, estenderá as mãos, e outro o cingirá e o levará para onde você não quer ir.

[[v43-21-19]]

^<<v43-21-19,19>>^ Jesus disse isso para significar com que tipo de morte Pedro havia de glorificar a Deus. Depois de falar assim, Jesus acrescentou: — Siga-me.

[[v43-21-20]]

^<<v43-21-20,20>>^ Então Pedro, voltando-se, viu que o discípulo a quem Jesus amava vinha seguindo; era o mesmo que na ceia havia se reclinado sobre o peito de Jesus para perguntar: "Senhor, quem é o traidor?"

[[v43-21-21]]

^<<v43-21-21,21>>^ Ao vê-lo, Pedro perguntou a Jesus: — Senhor, e quanto a este?

[[v43-21-22]]

^<<v43-21-22,22>>^ Jesus respondeu: — Se eu quero que ele permaneça até que eu venha, o que você tem com isso? Quanto a você, siga-me.

[[v43-21-23]]

^<<v43-21-23,23>>^ Então se espalhou entre os irmãos a notícia de que aquele discípulo não morreria. Ora, Jesus não tinha dito que tal discípulo não morreria, mas: "Se eu quero que ele permaneça até que eu venha, o que você tem com isso?"

[[v43-21-24]]

^<<v43-21-24,24>>^ Este é o discípulo que dá testemunho a respeito destas coisas e que as escreveu; e sabemos que o seu testemunho é verdadeiro.

[[v43-21-25]]

^<<v43-21-25,25>>^ Há, porém, ainda muitas outras coisas que Jesus fez. Se todas elas fossem relatadas uma por uma, penso que nem no mundo inteiro caberiam os livros que seriam escritos.

'''

xref:043-joao/043-joao-020.adoc#v43-20-0[&#60; Capítulo Anterior] | <<v43-21-0,Topo>> | xref:044-atos/044-atos-001.adoc#v44-1-0[Próximo Capítulo &#62;]