include::./index.adoc[]

[[v43-2-0]]
=== João, 2
// naa ?, NAA - Nova Almeida Atualizada

[[v43-2-1]]

^<<v43-2-1,1>>^ Três dias depois, houve um casamento em Caná da Galileia, e a mãe de Jesus estava ali.

[[v43-2-2]]

^<<v43-2-2,2>>^ Jesus também foi convidado, com os seus discípulos, para o casamento.

[[v43-2-3]]

^<<v43-2-3,3>>^ Tendo acabado o vinho, a mãe de Jesus lhe disse: — Eles não têm mais vinho.

[[v43-2-4]]

^<<v43-2-4,4>>^ Mas Jesus respondeu: — Por que a senhora está me dizendo isso? Ainda não é chegada a minha hora.

[[v43-2-5]]

^<<v43-2-5,5>>^ Então ela falou aos serventes: — Façam tudo o que ele disser.

[[v43-2-6]]

^<<v43-2-6,6>>^ Estavam ali seis potes de pedra, que os judeus usavam para as purificações, e em cada um cabiam cerca de cem litros.

[[v43-2-7]]

^<<v43-2-7,7>>^ Jesus lhes disse: — Encham de água esses potes. E eles os encheram totalmente.

[[v43-2-8]]

^<<v43-2-8,8>>^ Então lhes disse: — Agora tirem um pouco e levem ao responsável pela festa. Eles o fizeram.

[[v43-2-9]]

^<<v43-2-9,9>>^ Quando o responsável pela festa provou a água transformada em vinho — ele não sabia de onde tinha vindo, por mais que os serventes que haviam tirado a água soubessem —, chamou o noivo

[[v43-2-10]]

^<<v43-2-10,10>>^ e lhe disse: — Todos costumam servir primeiro o vinho bom e, quando já beberam muito, servem o vinho inferior; você, porém, guardou o melhor vinho até agora!

[[v43-2-11]]

^<<v43-2-11,11>>^ Assim, em Caná da Galileia, Jesus deu início a seus sinais. Ele manifestou a sua glória, e os seus discípulos creram nele.

[[v43-2-12]]

^<<v43-2-12,12>>^ Depois disso, ele foi a Cafarnaum, com sua mãe, seus irmãos e seus discípulos; e ficaram ali não muitos dias.

[[v43-2-13]]

^<<v43-2-13,13>>^ Estando próxima a Páscoa dos judeus, Jesus foi para Jerusalém.

[[v43-2-14]]

^<<v43-2-14,14>>^ E encontrou no templo os que vendiam bois, ovelhas e pombas e também os cambistas assentados.

[[v43-2-15]]

^<<v43-2-15,15>>^ Tendo feito um chicote de cordas, expulsou todos do templo, com as ovelhas e os bois. Derramou o dinheiro dos cambistas pelo chão, virou as mesas

[[v43-2-16]]

^<<v43-2-16,16>>^ e disse aos que vendiam as pombas: — Tirem estas coisas daqui! Não façam da casa de meu Pai uma casa de negócio!

[[v43-2-17]]

^<<v43-2-17,17>>^ Os seus discípulos se lembraram que está escrito: "O zelo da tua casa me consumirá."

[[v43-2-18]]

^<<v43-2-18,18>>^ Então os judeus lhe perguntaram: — Que sinal você nos mostra para fazer essas coisas?

[[v43-2-19]]

^<<v43-2-19,19>>^ Jesus lhes respondeu: — Destruam este santuário, e em três dias eu o levantarei.

[[v43-2-20]]

^<<v43-2-20,20>>^ Os judeus responderam: — Este santuário foi edificado em quarenta e seis anos, e você quer levantá-lo em três dias?

[[v43-2-21]]

^<<v43-2-21,21>>^ Ele, porém, se referia ao santuário do seu corpo.

[[v43-2-22]]

^<<v43-2-22,22>>^ Quando, pois, Jesus ressuscitou dentre os mortos, os discípulos dele se lembraram que ele tinha dito isso e creram na Escritura e na palavra de Jesus.

[[v43-2-23]]

^<<v43-2-23,23>>^ Estando Jesus em Jerusalém, durante a Festa da Páscoa, muitos creram no seu nome quando viram os sinais que ele fazia.

[[v43-2-24]]

^<<v43-2-24,24>>^ Mas o próprio Jesus não confiava neles, porque conhecia a todos.

[[v43-2-25]]

^<<v43-2-25,25>>^ E não precisava que alguém lhe desse testemunho a respeito das pessoas, porque ele mesmo sabia o que era a natureza humana.

'''

xref:043-joao/043-joao-001.adoc#v43-1-0[&#60; Capítulo Anterior] | <<v43-2-0,Topo>> | xref:043-joao/043-joao-003.adoc#v43-3-0[Próximo Capítulo &#62;]