include::./index.adoc[]

[[v43-10-0]]
=== João, 10
// naa ?, NAA - Nova Almeida Atualizada

[[v43-10-1]]

^<<v43-10-1,1>>^ — Em verdade, em verdade lhes digo: quem não entra no curral das ovelhas pela porta, mas sobe por outro lugar, esse é ladrão e salteador.

[[v43-10-2]]

^<<v43-10-2,2>>^ Aquele, porém, que entra pela porta, esse é o pastor das ovelhas.

[[v43-10-3]]

^<<v43-10-3,3>>^ Para este o porteiro abre, as ovelhas ouvem a sua voz, ele chama as suas próprias ovelhas pelo nome e as conduz para fora.

[[v43-10-4]]

^<<v43-10-4,4>>^ Depois de levar para fora todas as que lhe pertencem, vai na frente delas, e elas o seguem, porque reconhecem a voz dele.

[[v43-10-5]]

^<<v43-10-5,5>>^ Mas de modo nenhum seguirão o estranho; pelo contrário, fugirão dele, porque não conhecem a voz dos estranhos.

[[v43-10-6]]

^<<v43-10-6,6>>^ Jesus fez esta comparação, mas eles não compreenderam o sentido daquilo que ele falava.

[[v43-10-7]]

^<<v43-10-7,7>>^ Então Jesus disse mais uma vez: — Em verdade, em verdade lhes digo que eu sou a porta das ovelhas.

[[v43-10-8]]

^<<v43-10-8,8>>^ Todos os que vieram antes de mim são ladrões e salteadores, mas as ovelhas não lhes deram ouvidos.

[[v43-10-9]]

^<<v43-10-9,9>>^ Eu sou a porta. Se alguém entrar por mim, será salvo; entrará, sairá e achará pastagem.

[[v43-10-10]]

^<<v43-10-10,10>>^ O ladrão vem somente para roubar, matar e destruir; eu vim para que tenham vida e a tenham em abundância.

[[v43-10-11]]

^<<v43-10-11,11>>^ — Eu sou o bom pastor. O bom pastor dá a vida pelas ovelhas.

[[v43-10-12]]

^<<v43-10-12,12>>^ O mercenário, que não é pastor, a quem não pertencem as ovelhas, vê o lobo chegando, abandona as ovelhas e foge; então o lobo as arrebata e dispersa.

[[v43-10-13]]

^<<v43-10-13,13>>^ O mercenário foge, porque é mercenário e não se importa com as ovelhas.

[[v43-10-14]]

^<<v43-10-14,14>>^ Eu sou o bom pastor. Conheço as minhas ovelhas, e elas me conhecem,

[[v43-10-15]]

^<<v43-10-15,15>>^ assim como o Pai me conhece, e eu conheço o Pai; e dou a minha vida pelas ovelhas.

[[v43-10-16]]

^<<v43-10-16,16>>^ Ainda tenho outras ovelhas, não deste aprisco. Preciso trazer também estas. Elas ouvirão a minha voz e, então, haverá um só rebanho e um só pastor.

[[v43-10-17]]

^<<v43-10-17,17>>^ Por isso, o Pai me ama, porque eu dou a minha vida para recebê-la outra vez.

[[v43-10-18]]

^<<v43-10-18,18>>^ Ninguém tira a minha vida; pelo contrário, eu espontaneamente a dou. Tenho autoridade para entregá-la e também para reavê-la. Este mandato recebi de meu Pai.

[[v43-10-19]]

^<<v43-10-19,19>>^ Por causa dessas palavras, houve nova divisão entre os judeus.

[[v43-10-20]]

^<<v43-10-20,20>>^ Muitos deles diziam: — Ele tem demônio e enlouqueceu. Por que vocês ouvem o que ele diz?

[[v43-10-21]]

^<<v43-10-21,21>>^ Outros diziam: — Este modo de falar não é de endemoniado. Será que um demônio pode abrir os olhos aos cegos?

[[v43-10-22]]

^<<v43-10-22,22>>^ Celebrava-se em Jerusalém a Festa da Dedicação. Era inverno.

[[v43-10-23]]

^<<v43-10-23,23>>^ Jesus passeava no templo, no Pórtico de Salomão.

[[v43-10-24]]

^<<v43-10-24,24>>^ Então os judeus o rodearam e disseram: — Até quando você nos deixará nesse suspense? Se você é o Cristo, diga francamente.

[[v43-10-25]]

^<<v43-10-25,25>>^ Jesus respondeu: — Já falei, mas vocês não acreditam. As obras que eu faço em nome do meu Pai dão testemunho de mim.

[[v43-10-26]]

^<<v43-10-26,26>>^ Mas vocês não creem, porque não são das minhas ovelhas.

[[v43-10-27]]

^<<v43-10-27,27>>^ As minhas ovelhas ouvem a minha voz; eu as conheço, e elas me seguem.

[[v43-10-28]]

^<<v43-10-28,28>>^ Eu lhes dou a vida eterna; jamais perecerão, e ninguém as arrebatará da minha mão.

[[v43-10-29]]

^<<v43-10-29,29>>^ Aquilo que meu Pai me deu é maior do que tudo, e da mão do Pai ninguém pode arrebatar.

[[v43-10-30]]

^<<v43-10-30,30>>^ Eu e o Pai somos um.

[[v43-10-31]]

^<<v43-10-31,31>>^ Os judeus mais uma vez pegaram pedras com a intenção de apedrejá-lo.

[[v43-10-32]]

^<<v43-10-32,32>>^ Mas Jesus lhes disse: — Tenho mostrado a vocês muitas obras boas da parte do Pai. Por qual delas querem me apedrejar?

[[v43-10-33]]

^<<v43-10-33,33>>^ Os judeus responderam: — Não é por obra boa que queremos apedrejá-lo, e sim por causa da blasfêmia. Pois, sendo você apenas um homem, está se fazendo de Deus.

[[v43-10-34]]

^<<v43-10-34,34>>^ Jesus disse: — Não está escrito na Lei de vocês: "Eu disse: vocês são deuses"?

[[v43-10-35]]

^<<v43-10-35,35>>^ Se ele chamou deuses àqueles a quem foi dirigida a palavra de Deus — e a Escritura não pode falhar —,

[[v43-10-36]]

^<<v43-10-36,36>>^ então como vocês dizem que aquele que o Pai santificou e enviou ao mundo está blasfemando, só porque declarei que sou Filho de Deus?

[[v43-10-37]]

^<<v43-10-37,37>>^ Se não faço as obras do meu Pai, não acreditem em mim.

[[v43-10-38]]

^<<v43-10-38,38>>^ Mas, se faço, e vocês não creem em mim, creiam pelo menos nas obras, para que vocês possam saber e compreender que o Pai está em mim e que eu estou no Pai.

[[v43-10-39]]

^<<v43-10-39,39>>^ Então tentaram outra vez prendê-lo, mas ele se livrou das mãos deles.

[[v43-10-40]]

^<<v43-10-40,40>>^ Novamente Jesus se retirou para além do Jordão, para o lugar onde João batizava no início; e ali permaneceu.

[[v43-10-41]]

^<<v43-10-41,41>>^ E muitos iam até ele e diziam: — João não fez nenhum sinal, mas tudo o que ele disse a respeito deste homem era verdade.

[[v43-10-42]]

^<<v43-10-42,42>>^ E naquele lugar muitos creram nele.

'''

xref:043-joao/043-joao-009.adoc#v43-9-0[&#60; Capítulo Anterior] | <<v43-10-0,Topo>> | xref:043-joao/043-joao-011.adoc#v43-11-0[Próximo Capítulo &#62;]