include::./index.adoc[]

[[v43-8-0]]
=== João, 8
// naa ?, NAA - Nova Almeida Atualizada

[[v43-8-1]]

^<<v43-8-1,1>>^ Jesus, no entanto, foi para o monte das Oliveiras.

[[v43-8-2]]

^<<v43-8-2,2>>^ De madrugada, voltou novamente para o templo, e todo o povo se reuniu em volta dele; e Jesus, assentado, os ensinava.

[[v43-8-3]]

^<<v43-8-3,3>>^ Então os escribas e fariseus trouxeram à presença dele uma mulher surpreendida em adultério e, fazendo-a ficar em pé no meio de todos,

[[v43-8-4]]

^<<v43-8-4,4>>^ disseram a Jesus: — Mestre, esta mulher foi surpreendida em flagrante adultério.

[[v43-8-5]]

^<<v43-8-5,5>>^ Na Lei, Moisés nos ordenou que tais mulheres sejam apedrejadas. E o senhor, o que tem a dizer?

[[v43-8-6]]

^<<v43-8-6,6>>^ Eles diziam isso tentando-o, para terem de que o acusar. Mas Jesus, inclinando-se, escrevia na terra com o dedo.

[[v43-8-7]]

^<<v43-8-7,7>>^ Como eles insistiam na pergunta, Jesus se levantou e lhes disse: — Quem de vocês estiver sem pecado seja o primeiro a atirar uma pedra nela.

[[v43-8-8]]

^<<v43-8-8,8>>^ E, inclinando-se novamente, continuou a escrever no chão.

[[v43-8-9]]

^<<v43-8-9,9>>^ Mas eles, ouvindo essa resposta, foram saindo um por um, a começar pelos mais velhos até os últimos, ficando só Jesus e a mulher em pé diante dele.

[[v43-8-10]]

^<<v43-8-10,10>>^ Levantando-se, Jesus perguntou a ela: — Mulher, onde estão eles? Ninguém condenou você?

[[v43-8-11]]

^<<v43-8-11,11>>^ Ela respondeu: — Ninguém, Senhor! Então Jesus disse: — Também eu não a condeno; vá e não peque mais.

[[v43-8-12]]

^<<v43-8-12,12>>^ De novo, Jesus lhes falou, dizendo: — Eu sou a luz do mundo. Quem me segue não andará nas trevas; pelo contrário, terá a luz da vida.

[[v43-8-13]]

^<<v43-8-13,13>>^ Então os fariseus lhe disseram: — Você dá testemunho de si mesmo. O testemunho que você dá não é verdadeiro.

[[v43-8-14]]

^<<v43-8-14,14>>^ Jesus respondeu: — Ainda que eu dê testemunho a respeito de mim mesmo, o meu testemunho é verdadeiro, porque sei de onde vim e para onde vou; mas vocês não sabem de onde venho, nem para onde vou.

[[v43-8-15]]

^<<v43-8-15,15>>^ Vocês julgam segundo a carne; eu não julgo ninguém.

[[v43-8-16]]

^<<v43-8-16,16>>^ E, se eu julgo, o meu juízo é verdadeiro, porque não sou só eu que julgo, mas eu e o Pai, que me enviou.

[[v43-8-17]]

^<<v43-8-17,17>>^ Também na Lei de vocês está escrito que o testemunho de duas pessoas é verdadeiro.

[[v43-8-18]]

^<<v43-8-18,18>>^ Eu dou testemunho de mim mesmo, e o Pai, que me enviou, também dá testemunho de mim.

[[v43-8-19]]

^<<v43-8-19,19>>^ Então eles lhe perguntaram: — Onde está o seu Pai? Jesus respondeu: — Vocês não conhecem a mim e não conhecem o meu Pai; se conhecessem a mim, também conheceriam o meu Pai.

[[v43-8-20]]

^<<v43-8-20,20>>^ Jesus proferiu essas palavras perto da caixa de ofertas, quando ensinava no templo. Ninguém o prendeu, porque ainda não havia chegado a sua hora.

[[v43-8-21]]

^<<v43-8-21,21>>^ Outra vez Jesus lhes falou, dizendo: — Eu vou embora, e vocês vão me procurar, mas perecerão no seu pecado. Para onde eu vou vocês não podem ir.

[[v43-8-22]]

^<<v43-8-22,22>>^ Então os judeus diziam: — Será que ele tem a intenção de se suicidar? Porque diz: "Para onde eu vou vocês não podem ir."

[[v43-8-23]]

^<<v43-8-23,23>>^ Jesus lhes disse: — Vocês são daqui de baixo, eu sou lá de cima. Vocês são deste mundo, eu deste mundo não sou.

[[v43-8-24]]

^<<v43-8-24,24>>^ Por isso, eu lhes disse que vocês morrerão em seus pecados. Porque, se não crerem que Eu Sou , vocês morrerão nos seus pecados.

[[v43-8-25]]

^<<v43-8-25,25>>^ Então lhe perguntaram: — Quem é você? Jesus respondeu: — O que é que eu tenho dito a vocês desde o princípio?

[[v43-8-26]]

^<<v43-8-26,26>>^ Muitas coisas tenho para falar e julgar a respeito de vocês. Porém aquele que me enviou é verdadeiro, de modo que as coisas que dele ouvi, essas digo ao mundo.

[[v43-8-27]]

^<<v43-8-27,27>>^ Eles não entenderam que Jesus lhes falava do Pai.

[[v43-8-28]]

^<<v43-8-28,28>>^ Então Jesus disse: — Quando vocês levantarem o Filho do Homem, então saberão que Eu Sou  e que nada faço por mim mesmo; mas falo como o Pai me ensinou.

[[v43-8-29]]

^<<v43-8-29,29>>^ E aquele que me enviou está comigo, não me deixou só, porque eu faço sempre o que lhe agrada.

[[v43-8-30]]

^<<v43-8-30,30>>^ Quando Jesus disse isto, muitos creram nele.

[[v43-8-31]]

^<<v43-8-31,31>>^ Então Jesus disse aos judeus que haviam crido nele: — Se vocês permanecerem na minha palavra, são verdadeiramente meus discípulos,

[[v43-8-32]]

^<<v43-8-32,32>>^ conhecerão a verdade, e a verdade os libertará.

[[v43-8-33]]

^<<v43-8-33,33>>^ Eles responderam: — Somos descendência de Abraão e jamais fomos escravos de ninguém. Como você pode dizer que seremos livres?

[[v43-8-34]]

^<<v43-8-34,34>>^ Jesus respondeu: — Em verdade, em verdade lhes digo que todo o que comete pecado é escravo do pecado.

[[v43-8-35]]

^<<v43-8-35,35>>^ O escravo não fica sempre na casa; o filho, sim, fica para sempre.

[[v43-8-36]]

^<<v43-8-36,36>>^ Se, pois, o Filho os libertar, vocês serão verdadeiramente livres.

[[v43-8-37]]

^<<v43-8-37,37>>^ Bem sei que vocês são descendência de Abraão; no entanto, estão querendo me matar, porque a minha palavra não está em vocês.

[[v43-8-38]]

^<<v43-8-38,38>>^ Eu falo das coisas que vi junto de meu Pai; vocês, porém, fazem o que ouviram do pai de vocês.

[[v43-8-39]]

^<<v43-8-39,39>>^ Então lhe disseram: — Nosso pai é Abraão. Mas Jesus respondeu: — Se vocês fossem filhos de Abraão, fariam as obras que ele fez.

[[v43-8-40]]

^<<v43-8-40,40>>^ Mas agora vocês estão querendo me matar, a mim que lhes falei a verdade que ouvi de Deus; Abraão não fez isso.

[[v43-8-41]]

^<<v43-8-41,41>>^ Vocês fazem as obras do pai de vocês. Eles responderam: — Nós não somos filhos ilegítimos. Temos um pai, que é Deus.

[[v43-8-42]]

^<<v43-8-42,42>>^ Jesus disse: — Se Deus fosse, de fato, o pai de vocês, certamente me amariam, porque eu vim de Deus e aqui estou; pois não vim de mim mesmo, mas ele me enviou.

[[v43-8-43]]

^<<v43-8-43,43>>^ Por que vocês não compreendem a minha linguagem? É porque vocês são incapazes de ouvir a minha palavra.

[[v43-8-44]]

^<<v43-8-44,44>>^ Vocês são do diabo, que é o pai de vocês, e querem satisfazer os desejos dele. Ele foi assassino desde o princípio e jamais se firmou na verdade, porque nele não há verdade. Quando ele profere mentira, fala do que lhe é próprio, porque é mentiroso e pai da mentira.

[[v43-8-45]]

^<<v43-8-45,45>>^ Mas, porque eu digo a verdade, vocês não creem em mim.

[[v43-8-46]]

^<<v43-8-46,46>>^ Quem de vocês me convence de pecado? Se digo a verdade, por que não creem em mim?

[[v43-8-47]]

^<<v43-8-47,47>>^ Quem é de Deus ouve as palavras de Deus; por isso, vocês não me ouvem, porque não são de Deus.

[[v43-8-48]]

^<<v43-8-48,48>>^ Os judeus disseram a Jesus: — Será que não temos razão em dizer que você é samaritano e tem demônio?

[[v43-8-49]]

^<<v43-8-49,49>>^ Jesus respondeu: — Eu não tenho demônio; pelo contrário, honro o meu Pai, mas vocês me desonram.

[[v43-8-50]]

^<<v43-8-50,50>>^ Eu não procuro a minha própria glória; há quem a busque e julgue.

[[v43-8-51]]

^<<v43-8-51,51>>^ Em verdade, em verdade lhes digo que, se alguém guardar a minha palavra, não verá a morte eternamente.

[[v43-8-52]]

^<<v43-8-52,52>>^ Então os judeus disseram: — Agora estamos certos de que você tem demônio. Abraão morreu, e também os profetas, e você diz: "Se alguém guardar a minha palavra, não provará a morte eternamente."

[[v43-8-53]]

^<<v43-8-53,53>>^ Você não está querendo dizer que é maior do que Abraão, o nosso pai, que morreu? Também os profetas morreram. Quem você pensa que é?

[[v43-8-54]]

^<<v43-8-54,54>>^ Jesus respondeu: — Se eu glorifico a mim mesmo, a minha glória não é nada. Quem me glorifica é o meu Pai, o qual vocês dizem que é o Deus de vocês.

[[v43-8-55]]

^<<v43-8-55,55>>^ Entretanto, vocês não o conhecem; eu, porém, o conheço. Se eu disser que não o conheço, serei como vocês: mentiroso; mas eu o conheço e guardo a sua palavra.

[[v43-8-56]]

^<<v43-8-56,56>>^ Abraão, o pai de vocês, alegrou-se por ver o meu dia; e ele viu esse dia e ficou alegre.

[[v43-8-57]]

^<<v43-8-57,57>>^ Então os judeus lhe perguntaram: — Você não tem nem cinquenta anos e viu Abraão?

[[v43-8-58]]

^<<v43-8-58,58>>^ Jesus respondeu: — Em verdade, em verdade lhes digo que, antes que Abraão existisse, Eu Sou .

[[v43-8-59]]

^<<v43-8-59,59>>^ Então pegaram pedras para atirar nele, mas Jesus se ocultou e saiu do templo.

'''

xref:043-joao/043-joao-007.adoc#v43-7-0[&#60; Capítulo Anterior] | <<v43-8-0,Topo>> | xref:043-joao/043-joao-009.adoc#v43-9-0[Próximo Capítulo &#62;]