include::./index.adoc[]

[[v43-4-0]]
=== João, 4
// naa ?, NAA - Nova Almeida Atualizada

[[v43-4-1]]

^<<v43-4-1,1>>^ Quando Jesus soube que os fariseus tinham ouvido dizer que ele fazia e batizava mais discípulos do que João

[[v43-4-2]]

^<<v43-4-2,2>>^ — se bem que Jesus mesmo não batizava, e sim os seus discípulos —,

[[v43-4-3]]

^<<v43-4-3,3>>^ deixou a Judeia, retirando-se outra vez para a Galileia.

[[v43-4-4]]

^<<v43-4-4,4>>^ E era-lhe necessário passar pela região da Samaria.

[[v43-4-5]]

^<<v43-4-5,5>>^ Assim, Jesus chegou a uma cidade samaritana, chamada Sicar, perto das terras que Jacó tinha dado a seu filho José.

[[v43-4-6]]

^<<v43-4-6,6>>^ Ali ficava o poço de Jacó. Cansado da viagem, Jesus sentou-se junto ao poço. Era por volta do meio-dia.

[[v43-4-7]]

^<<v43-4-7,7>>^ Nisso veio uma mulher samaritana tirar água. Jesus lhe disse: — Dê-me um pouco de água.

[[v43-4-8]]

^<<v43-4-8,8>>^ Pois os seus discípulos tinham ido à cidade comprar alimentos.

[[v43-4-9]]

^<<v43-4-9,9>>^ Então a mulher samaritana perguntou a Jesus: — Como, sendo o senhor um judeu, pede água a mim, que sou mulher samaritana? Ela disse isso porque os judeus não se dão com os samaritanos.

[[v43-4-10]]

^<<v43-4-10,10>>^ Jesus respondeu: — Se você conhecesse o dom de Deus e quem é que está lhe pedindo água para beber, você pediria, e ele lhe daria água viva.

[[v43-4-11]]

^<<v43-4-11,11>>^ Ao que a mulher respondeu: — O senhor não tem balde e o poço é fundo. De onde vai conseguir essa água viva?

[[v43-4-12]]

^<<v43-4-12,12>>^ Por acaso o senhor é maior do que Jacó, o nosso pai, que nos deu o poço, do qual ele mesmo bebeu, assim como os seus filhos e o seu gado?

[[v43-4-13]]

^<<v43-4-13,13>>^ Jesus respondeu: — Quem beber desta água voltará a ter sede,

[[v43-4-14]]

^<<v43-4-14,14>>^ mas aquele que beber da água que eu lhe der nunca mais terá sede. Pelo contrário, a água que eu lhe der será nele uma fonte a jorrar para a vida eterna.

[[v43-4-15]]

^<<v43-4-15,15>>^ A mulher lhe disse: — Senhor, quero que me dê essa água para que eu não mais tenha sede, nem precise vir aqui buscá-la.

[[v43-4-16]]

^<<v43-4-16,16>>^ Jesus disse: — Vá, chame o seu marido e volte aqui.

[[v43-4-17]]

^<<v43-4-17,17>>^ Ao que a mulher respondeu: — Não tenho marido. Então Jesus disse: — Você tem razão ao dizer que não tem marido.

[[v43-4-18]]

^<<v43-4-18,18>>^ Porque já teve cinco, e esse que agora tem não é seu marido. O que você disse é verdade.

[[v43-4-19]]

^<<v43-4-19,19>>^ A mulher então lhe disse: — Agora eu sei que o senhor é um profeta!

[[v43-4-20]]

^<<v43-4-20,20>>^ Nossos pais adoravam neste monte, mas vocês dizem que em Jerusalém é o lugar onde se deve adorar.

[[v43-4-21]]

^<<v43-4-21,21>>^ Jesus respondeu: — Mulher, acredite no que digo: vem a hora em que nem neste monte nem em Jerusalém vocês adorarão o Pai.

[[v43-4-22]]

^<<v43-4-22,22>>^ Vocês adoram o que não conhecem; nós adoramos o que conhecemos, porque a salvação vem dos judeus.

[[v43-4-23]]

^<<v43-4-23,23>>^ Mas vem a hora — e já chegou — em que os verdadeiros adoradores adorarão o Pai em espírito e em verdade. Porque são esses que o Pai procura para seus adoradores.

[[v43-4-24]]

^<<v43-4-24,24>>^ Deus é Espírito, e é necessário que os seus adoradores o adorem em espírito e em verdade.

[[v43-4-25]]

^<<v43-4-25,25>>^ A mulher respondeu: — Eu sei que virá o Messias, chamado Cristo. Quando ele vier, nos anunciará todas as coisas.

[[v43-4-26]]

^<<v43-4-26,26>>^ Então Jesus disse: — Eu sou o Messias, eu que estou falando com você.

[[v43-4-27]]

^<<v43-4-27,27>>^ Naquele momento, chegaram os discípulos de Jesus e se admiraram ao vê-lo falando com uma mulher. Mas nenhum deles perguntou: "O que você está querendo?" Ou: "Por que o senhor está falando com ela?"

[[v43-4-28]]

^<<v43-4-28,28>>^ Quanto à mulher, deixou o seu cântaro, foi à cidade e disse ao povo:

[[v43-4-29]]

^<<v43-4-29,29>>^ — Venham comigo e vejam um homem que me disse tudo o que eu já fiz. Não seria ele, por acaso, o Cristo?

[[v43-4-30]]

^<<v43-4-30,30>>^ Então saíram da cidade e foram até onde Jesus estava.

[[v43-4-31]]

^<<v43-4-31,31>>^ Enquanto isso, os discípulos pediam a Jesus, dizendo: — Mestre, coma!

[[v43-4-32]]

^<<v43-4-32,32>>^ Mas ele lhes disse: — Tenho para comer uma comida que vocês não conhecem.

[[v43-4-33]]

^<<v43-4-33,33>>^ Então os discípulos começaram a dizer entre si: — Será que alguém lhe trouxe algo para comer?

[[v43-4-34]]

^<<v43-4-34,34>>^ Jesus lhes declarou: — A minha comida consiste em fazer a vontade daquele que me enviou e realizar a sua obra.

[[v43-4-35]]

^<<v43-4-35,35>>^ Vocês não dizem que ainda faltam quatro meses até a colheita? Eu, porém, lhes digo: Levantem os olhos e vejam os campos, pois estão maduros para a colheita.

[[v43-4-36]]

^<<v43-4-36,36>>^ Quem colhe recebe desde já a recompensa e ajunta o seu fruto para a vida eterna, para que se alegrem ao mesmo tempo o que semeia e o que colhe.

[[v43-4-37]]

^<<v43-4-37,37>>^ Pois, no caso, é verdadeiro o ditado: "Um é o que semeia, outro é o que colhe."

[[v43-4-38]]

^<<v43-4-38,38>>^ Eu os enviei a colher o que vocês não semearam; outros trabalharam, e vocês aproveitaram o trabalho deles.

[[v43-4-39]]

^<<v43-4-39,39>>^ Muitos samaritanos daquela cidade creram em Jesus, por causa do testemunho da mulher, que tinha dito: "Ele me disse tudo o que eu já fiz."

[[v43-4-40]]

^<<v43-4-40,40>>^ Quando, pois, os samaritanos foram até Jesus, pediram-lhe que permanecesse com eles; e Jesus ficou ali dois dias.

[[v43-4-41]]

^<<v43-4-41,41>>^ Muitos outros creram nele, por causa da palavra de Jesus.

[[v43-4-42]]

^<<v43-4-42,42>>^ E diziam à mulher: — Agora não é mais por causa do que você falou que nós cremos, mas porque nós mesmos ouvimos, e sabemos que este é verdadeiramente o Salvador do mundo.

[[v43-4-43]]

^<<v43-4-43,43>>^ Passados dois dias, Jesus saiu dali e foi para a Galileia.

[[v43-4-44]]

^<<v43-4-44,44>>^ Porque o próprio Jesus testemunhou que um profeta não tem honra na sua própria terra.

[[v43-4-45]]

^<<v43-4-45,45>>^ Assim, quando chegou à Galileia, os galileus o receberam, porque viram todas as coisas que Jesus tinha feito em Jerusalém, por ocasião da festa, à qual eles também tinham comparecido.

[[v43-4-46]]

^<<v43-4-46,46>>^ Jesus foi outra vez a Caná da Galileia, onde tinha transformado água em vinho. E havia ali um oficial do rei, cujo filho estava doente em Cafarnaum.

[[v43-4-47]]

^<<v43-4-47,47>>^ Quando ouviu dizer que Jesus tinha vindo da Judeia para a Galileia, foi até ele e pediu-lhe que fosse curar o seu filho, que estava morrendo.

[[v43-4-48]]

^<<v43-4-48,48>>^ Então Jesus lhe disse: — Se vocês não virem sinais e prodígios, de modo nenhum crerão.

[[v43-4-49]]

^<<v43-4-49,49>>^ O oficial pediu mais uma vez: — Senhor, venha, antes que o meu filho morra!

[[v43-4-50]]

^<<v43-4-50,50>>^ Jesus respondeu: — Vá, o seu filho vai viver. O homem creu na palavra de Jesus e partiu.

[[v43-4-51]]

^<<v43-4-51,51>>^ Quando já estava a caminho, os seus servos vieram ao encontro dele, anunciando-lhe que o seu filho estava vivo.

[[v43-4-52]]

^<<v43-4-52,52>>^ Então perguntou a que horas o seu filho havia se sentido melhor. Informaram: — Ontem, à uma hora da tarde a febre o deixou.

[[v43-4-53]]

^<<v43-4-53,53>>^ Com isso, o pai reconheceu que aquela era precisamente a hora em que Jesus tinha dito a ele: "O seu filho vai viver." E ele e toda a sua casa creram.

[[v43-4-54]]

^<<v43-4-54,54>>^ Este foi o segundo sinal que Jesus fez, depois de ir da Judeia para a Galileia.

'''

xref:043-joao/043-joao-003.adoc#v43-3-0[&#60; Capítulo Anterior] | <<v43-4-0,Topo>> | xref:043-joao/043-joao-005.adoc#v43-5-0[Próximo Capítulo &#62;]