include::./index.adoc[]

[[v36-1-0]]
=== Sofonias, 1
// naa ?, NAA - Nova Almeida Atualizada

[[v36-1-1]]

^<<v36-1-1,1>>^ Palavra do Senhor  que veio a Sofonias, filho de Cusi, filho de Gedalias, filho de Amarias, filho de Ezequias, nos dias de Josias, filho de Amom, rei de Judá.

[[v36-1-2]]

^<<v36-1-2,2>>^ "Certamente consumirei todas as coisas sobre a face da terra", diz o Senhor .

[[v36-1-3]]

^<<v36-1-3,3>>^ "Consumirei as pessoas e os animais, consumirei as aves do céu, os peixes do mar, e as ofensas com os ímpios. E exterminarei os seres humanos da face da terra", diz o Senhor .

[[v36-1-4]]

^<<v36-1-4,4>>^ "Estenderei a mão contra Judá e contra todos os moradores de Jerusalém. Exterminarei deste lugar o resto de Baal e a lembrança dos ministros dos ídolos e seus sacerdotes.

[[v36-1-5]]

^<<v36-1-5,5>>^ Exterminarei os que sobre os terraços adoram o exército do céu e os que adoram o Senhor e juram por ele e também por Milcom.

[[v36-1-6]]

^<<v36-1-6,6>>^ Farei desaparecer também os que deixam de seguir o Senhor e os que não buscam o Senhor , nem perguntam por ele."

[[v36-1-7]]

^<<v36-1-7,7>>^ "Calem-se diante do Senhor  Deus, porque o Dia do Senhor  está perto. O Senhor  preparou o sacrifício e santificou os seus convidados.

[[v36-1-8]]

^<<v36-1-8,8>>^ No dia do sacrifício do Senhor , hei de castigar as autoridades, e os filhos do rei, e todos os que se vestem como estrangeiros.

[[v36-1-9]]

^<<v36-1-9,9>>^ Castigarei também, naquele dia, todos aqueles que sobem o pedestal dos ídolos e enchem de violência e engano a casa dos seus senhores."

[[v36-1-10]]

^<<v36-1-10,10>>^ "Naquele dia", diz o Senhor , "se ouvirá um grito desde o Portão dos Peixes, e um uivo desde a parte nova da cidade, e grande lamento desde as colinas.

[[v36-1-11]]

^<<v36-1-11,11>>^ Lamentem, moradores da cidade baixa, porque todos os comerciantes serão mortos e todos os que pesam prata serão destruídos.

[[v36-1-12]]

^<<v36-1-12,12>>^ Naquele tempo, vasculharei Jerusalém com lanternas e castigarei aqueles que estão apegados à borra do vinho e dizem no seu coração: ‘O Senhor  não faz bem nem faz mal.’

[[v36-1-13]]

^<<v36-1-13,13>>^ Por isso, os bens deles serão saqueados, e as suas casas serão destruídas. Eles construirão casas, mas não habitarão nelas; plantarão vinhas, mas não beberão o vinho."

[[v36-1-14]]

^<<v36-1-14,14>>^ "Está perto o grande Dia do Senhor ; está perto e vem chegando depressa. Atenção! O Dia do Senhor  é amargo, e nele clamarão até os poderosos.

[[v36-1-15]]

^<<v36-1-15,15>>^ Aquele dia será um dia de ira, dia de angústia e tribulação, dia de ruína e destruição, dia de trevas e escuridão, dia de nuvens e densas trevas,

[[v36-1-16]]

^<<v36-1-16,16>>^ dia de toque de trombeta e gritos de guerra contra as cidades fortificadas e contra as torres altas.

[[v36-1-17]]

^<<v36-1-17,17>>^ Trarei angústia sobre as pessoas, e elas andarão como se estivessem cegas, porque pecaram contra o Senhor . O sangue dessas pessoas será derramado como pó, e a sua carne será espalhada como esterco.

[[v36-1-18]]

^<<v36-1-18,18>>^ Nem a prata nem o ouro poderão livrá-las no dia da ira do Senhor , mas, pelo fogo do seu zelo, a terra será consumida. Porque ele certamente fará destruição total e repentina de todos os moradores da terra."

'''

xref:035-habacuque/035-habacuque-003.adoc#v35-3-0[&#60; Capítulo Anterior] | <<v36-1-0,Topo>> | xref:036-sofonias/036-sofonias-002.adoc#v36-2-0[Próximo Capítulo &#62;]