include::./index.adoc[]

[[v36-2-0]]
=== Sofonias, 2
// naa ?, NAA - Nova Almeida Atualizada

[[v36-2-1]]

^<<v36-2-1,1>>^ Reúna-se e concentre-se, ó nação sem pudor,

[[v36-2-2]]

^<<v36-2-2,2>>^ antes que saia o decreto e o dia se vá como a palha, antes que venha sobre você o furor da ira do Senhor , sim, antes que venha sobre você o dia da ira do Senhor .

[[v36-2-3]]

^<<v36-2-3,3>>^ Busquem o Senhor , todos vocês, os humildes da terra, que cumprem os seus mandamentos. Busquem a justiça, busquem a humildade. Talvez assim vocês sejam poupados no dia da ira do Senhor .

[[v36-2-4]]

^<<v36-2-4,4>>^ Porque Gaza será abandonada, e Asquelom ficará deserta; Asdode, ao meio-dia, será expulsa, e Ecrom será desarraigada.

[[v36-2-5]]

^<<v36-2-5,5>>^ Ai dos que habitam no litoral, do povo dos queretitas! A palavra do Senhor será contra você, Canaã, terra dos filisteus. "Farei com que você seja destruída, até que não reste um morador sequer."

[[v36-2-6]]

^<<v36-2-6,6>>^ O litoral será de pastagens, com refúgios para os pastores e currais para os rebanhos.

[[v36-2-7]]

^<<v36-2-7,7>>^ O litoral pertencerá ao remanescente da casa de Judá. Ali apascentarão os seus rebanhos e, ao anoitecer, se deitarão nas casas de Asquelom; porque o Senhor , seu Deus, os visitará e mudará a sorte deles.

[[v36-2-8]]

^<<v36-2-8,8>>^ "Ouvi a zombaria de Moabe e as palavras injuriosas dos filhos de Amom, que zombaram do meu povo e se gabaram contra o seu território.

[[v36-2-9]]

^<<v36-2-9,9>>^ Portanto, tão certo como eu vivo", diz o Senhor  dos Exércitos, o Deus de Israel, "Moabe será como Sodoma, e os filhos de Amom, como Gomorra, campo de urtigas, poços de sal e desolação perpétua. O remanescente do meu povo os saqueará, e os sobreviventes da minha nação tomarão posse dos seus territórios."

[[v36-2-10]]

^<<v36-2-10,10>>^ Isso lhes sobrevirá por causa do seu orgulho, porque zombaram e se gabaram contra o povo do Senhor  dos Exércitos.

[[v36-2-11]]

^<<v36-2-11,11>>^ O Senhor  será terrível contra eles, porque aniquilará todos os deuses da terra. E todos os povos das nações, cada um do seu lugar, o adorarão.

[[v36-2-12]]

^<<v36-2-12,12>>^ Também vocês, ó etíopes, serão mortos pela espada do Senhor .

[[v36-2-13]]

^<<v36-2-13,13>>^ Ele estenderá também a mão contra o Norte e destruirá a Assíria; e fará de Nínive uma desolação e terra seca como o deserto.

[[v36-2-14]]

^<<v36-2-14,14>>^ No meio dessa cidade, repousarão os rebanhos e todo tipo de animais. Nos capitéis das colunas se alojarão tanto o pelicano como o ouriço. A voz das aves ressoará nas janelas. Haverá escombros nos umbrais das portas, porque o madeiramento de cedro será arrancado.

[[v36-2-15]]

^<<v36-2-15,15>>^ Esta é a cidade alegre e confiante, que dizia consigo mesma: "Eu sou a única, e não há outra além de mim." Como se tornou em desolação, em pousada de animais! Todos os que passarem por ela hão de vaiar e farão gestos de desprezo.

'''

xref:036-sofonias/036-sofonias-001.adoc#v36-1-0[&#60; Capítulo Anterior] | <<v36-2-0,Topo>> | xref:036-sofonias/036-sofonias-003.adoc#v36-3-0[Próximo Capítulo &#62;]