include::./index.adoc[]

[[v36-3-0]]
=== Sofonias, 3
// naa ?, NAA - Nova Almeida Atualizada

[[v36-3-1]]

^<<v36-3-1,1>>^ Ai da cidade opressora, rebelde e manchada!

[[v36-3-2]]

^<<v36-3-2,2>>^ Não atende ninguém, não aceita disciplina, não confia no Senhor , nem se aproxima do seu Deus.

[[v36-3-3]]

^<<v36-3-3,3>>^ Os seus príncipes são leões rugidores no meio dela, os seus juízes são lobos do anoitecer, que não deixam os ossos para serem roídos no dia seguinte.

[[v36-3-4]]

^<<v36-3-4,4>>^ Os seus profetas são levianos e falsos. Os seus sacerdotes profanam o santuário e fazem violência à lei.

[[v36-3-5]]

^<<v36-3-5,5>>^ O Senhor  é justo, no meio da cidade; ele não comete injustiça. Manhã após manhã, ele traz o seu juízo à luz; não falha. Mas o injusto não sabe o que é vergonha.

[[v36-3-6]]

^<<v36-3-6,6>>^ "Exterminei nações. As suas torres estão destruídas. Tornei desertas as suas praças, a ponto de não haver quem passe por elas. As suas cidades foram destruídas, de maneira que não há ninguém, ninguém que as habite.

[[v36-3-7]]

^<<v36-3-7,7>>^ Eu dizia: ‘Certamente você, Jerusalém, viverá em temor diante de mim e aceitará a disciplina, e, assim, a sua morada não seria destruída, segundo o que eu havia determinado.’ Mas eles se tornaram cada vez mais corruptos em todos os seus atos."

[[v36-3-8]]

^<<v36-3-8,8>>^ "Portanto, esperem por mim", diz o Senhor , "esperem pelo dia em que eu me levantar para tomar o despojo. Porque a minha resolução é ajuntar as nações e congregar os reinos, para fazer cair sobre eles a minha indignação e todo o furor da minha ira. Porque toda esta terra será consumida pelo fogo do meu zelo."

[[v36-3-9]]

^<<v36-3-9,9>>^ "Então darei lábios puros aos povos, para que todos invoquem o nome do Senhor e o sirvam de comum acordo.

[[v36-3-10]]

^<<v36-3-10,10>>^ Dalém dos rios da Etiópia, os meus adoradores, que constituem a filha da minha dispersão, me trarão sacrifícios.

[[v36-3-11]]

^<<v36-3-11,11>>^ Naquele dia, você não terá de se envergonhar de nenhuma das suas rebeliões contra mim, porque tirarei do meio de você, Jerusalém, os que exultam no seu orgulho, e você nunca mais se orgulhará no meu santo monte.

[[v36-3-12]]

^<<v36-3-12,12>>^ Mas deixarei no meio de você um povo modesto e humilde, que confia no nome do Senhor .

[[v36-3-13]]

^<<v36-3-13,13>>^ O remanescente de Israel não cometerá injustiça. Eles não proferirão mentira, e da sua boca não sairão palavras enganosas, porque serão apascentados, se deitarão, e não haverá quem os atemorize."

[[v36-3-14]]

^<<v36-3-14,14>>^ Cante, ó filha de Sião! Grite de alegria, ó Israel! Alegre-se e exulte de todo o coração, ó filha de Jerusalém.

[[v36-3-15]]

^<<v36-3-15,15>>^ O Senhor  retirou as sentenças que eram contra você e afastou os seus inimigos. O Rei de Israel, o Senhor , está no meio de você; você não precisa mais temer nenhum mal.

[[v36-3-16]]

^<<v36-3-16,16>>^ Naquele dia, se dirá a Jerusalém: "Não tenha medo, ó Sião, não desfaleçam as suas mãos."

[[v36-3-17]]

^<<v36-3-17,17>>^ O Senhor , seu Deus, está no meio de você, poderoso para salvar. Ele ficará muito contente com você. Ele a renovará no seu amor, e se encherá de júbilo por causa de você.

[[v36-3-18]]

^<<v36-3-18,18>>^ "Congregarei os que estão entristecidos por se acharem afastados das festas solenes, estes que são do seu meio e sobre os quais pesam afrontas.

[[v36-3-19]]

^<<v36-3-19,19>>^ Eis que, naquele tempo, agirei contra todos os que a afligem. Salvarei os que coxeiam e recolherei os que foram expulsos. Farei deles um louvor e um nome em toda a terra em que foram envergonhados.

[[v36-3-20]]

^<<v36-3-20,20>>^ Naquele tempo, farei com que vocês voltem e os recolherei. Certamente farei de vocês um nome e um louvor entre todos os povos da terra, quando eu restaurar a sorte de vocês diante dos seus próprios olhos", diz o Senhor .

'''

xref:036-sofonias/036-sofonias-002.adoc#v36-2-0[&#60; Capítulo Anterior] | <<v36-3-0,Topo>> | xref:037-ageu/037-ageu-001.adoc#v37-1-0[Próximo Capítulo &#62;]