include::./index.adoc[]

[[v32-4-0]]
=== Jonas, 4
// naa ?, NAA - Nova Almeida Atualizada

[[v32-4-1]]

^<<v32-4-1,1>>^ Mas Jonas ficou muito aborrecido e com raiva.

[[v32-4-2]]

^<<v32-4-2,2>>^ Ele orou ao Senhor  e disse: — Ah! Senhor ! Não foi isso que eu disse, estando ainda na minha terra? Por isso, me adiantei, fugindo para Társis, pois sabia que tu és Deus bondoso e compassivo, tardio em irar-se e grande em misericórdia, e que mudas de ideia quanto ao mal que anunciaste.

[[v32-4-3]]

^<<v32-4-3,3>>^ Agora, Senhor , peço que me tires a vida, porque para mim é melhor morrer do que viver.

[[v32-4-4]]

^<<v32-4-4,4>>^ E o Senhor  disse: — Você acha que é razoável essa sua raiva?

[[v32-4-5]]

^<<v32-4-5,5>>^ Então Jonas saiu da cidade e sentou-se num lugar a leste da mesma. Ali construiu um abrigo, sentou-se na sombra, para ver o que aconteceria com a cidade.

[[v32-4-6]]

^<<v32-4-6,6>>^ Então o Senhor  Deus fez crescer uma planta por cima de Jonas, para que fizesse sombra sobre a sua cabeça, a fim de o livrar do seu desconforto. E Jonas ficou muito contente por causa da planta.

[[v32-4-7]]

^<<v32-4-7,7>>^ Mas no dia seguinte, ao amanhecer, Deus enviou um verme, que atacou a planta, e ela secou.

[[v32-4-8]]

^<<v32-4-8,8>>^ Quando o sol nasceu, Deus fez soprar um vento leste muito quente. O sol bateu na cabeça de Jonas, de maneira que ele quase desmaiou. Então pediu para morrer, dizendo: — Para mim é melhor morrer do que viver!

[[v32-4-9]]

^<<v32-4-9,9>>^ Então Deus perguntou a Jonas: — Você acha que é razoável essa sua raiva por causa da planta? Jonas respondeu: — É tão razoável que até quero morrer!

[[v32-4-10]]

^<<v32-4-10,10>>^ E o Senhor  disse: — Você tem compaixão da planta que não lhe custou nenhum trabalho. Você não a fez crescer. Numa noite ela nasceu e na noite seguinte desapareceu.

[[v32-4-11]]

^<<v32-4-11,11>>^ E você não acha que eu deveria ter muito mais compaixão da grande cidade de Nínive, em que há mais de cento e vinte mil pessoas, que não sabem distinguir entre a mão direita e a mão esquerda, e também muitos animais?

'''

xref:032-jonas/032-jonas-003.adoc#v32-3-0[&#60; Capítulo Anterior] | <<v32-4-0,Topo>> | xref:033-miqueias/033-miqueias-001.adoc#v33-1-0[Próximo Capítulo &#62;]