include::./index.adoc[]

[[v32-3-0]]
=== Jonas, 3
// naa ?, NAA - Nova Almeida Atualizada

[[v32-3-1]]

^<<v32-3-1,1>>^ A palavra do Senhor  veio a Jonas pela segunda vez, dizendo:

[[v32-3-2]]

^<<v32-3-2,2>>^ — Levante-se, vá à grande cidade de Nínive e pregue contra ela a mensagem que eu lhe darei.

[[v32-3-3]]

^<<v32-3-3,3>>^ Jonas se levantou e foi a Nínive, segundo a palavra do Senhor . Ora, Nínive era uma cidade muito importante diante de Deus; eram necessários três dias para percorrê-la.

[[v32-3-4]]

^<<v32-3-4,4>>^ Jonas começou a percorrer a cidade caminho de um dia, e pregava, dizendo: — Ainda quarenta dias, e Nínive será destruída.

[[v32-3-5]]

^<<v32-3-5,5>>^ Os ninivitas creram em Deus. Proclamaram um jejum e vestiram roupa feita de pano de saco, desde o maior até o menor.

[[v32-3-6]]

^<<v32-3-6,6>>^ Quando esta notícia chegou ao rei de Nínive, ele se levantou do seu trono, tirou os trajes reais, cobriu-se de pano de saco e sentou-se sobre cinzas.

[[v32-3-7]]

^<<v32-3-7,7>>^ E mandou proclamar e divulgar em Nínive o seguinte: — Por mandado do rei e dos seus nobres, ninguém — nem mesmo os animais, bois e ovelhas — pode comer coisa alguma; não lhes deem pasto, nem deixem que bebam água.

[[v32-3-8]]

^<<v32-3-8,8>>^ Todos devem ser cobertos de pano de saco, tanto as pessoas como os animais. Então clamarão fortemente a Deus e se converterão, cada um do seu mau caminho e da violência que há nas suas mãos.

[[v32-3-9]]

^<<v32-3-9,9>>^ Quem sabe? Talvez Deus se volte e mude de ideia, e então se afaste do furor da sua ira, para que não pereçamos.

[[v32-3-10]]

^<<v32-3-10,10>>^ Deus viu o que fizeram, como se converteram do seu mau caminho; e Deus mudou de ideia quanto ao mal que tinha dito que lhes faria e não o fez.

'''

xref:032-jonas/032-jonas-002.adoc#v32-2-0[&#60; Capítulo Anterior] | <<v32-3-0,Topo>> | xref:032-jonas/032-jonas-004.adoc#v32-4-0[Próximo Capítulo &#62;]