include::./index.adoc[]

[[v32-1-0]]
=== Jonas, 1
// naa ?, NAA - Nova Almeida Atualizada

[[v32-1-1]]

^<<v32-1-1,1>>^ A palavra do Senhor  veio a Jonas, filho de Amitai, dizendo:

[[v32-1-2]]

^<<v32-1-2,2>>^ — Levante-se, vá à grande cidade de Nínive e pregue contra ela, porque a sua maldade subiu até a minha presença.

[[v32-1-3]]

^<<v32-1-3,3>>^ Jonas se levantou, mas para fugir da presença do Senhor , para Társis. Desceu a Jope, e encontrou um navio que ia para Társis. Pagou a passagem e embarcou no navio, para ir com eles para Társis, para longe da presença do Senhor .

[[v32-1-4]]

^<<v32-1-4,4>>^ Mas o Senhor  lançou sobre o mar um forte vento, e levantou-se uma tempestade tão violenta, que parecia que o navio estava a ponto de se despedaçar.

[[v32-1-5]]

^<<v32-1-5,5>>^ Então os marinheiros ficaram com medo e clamavam cada um ao seu deus. Lançaram no mar a carga que estava no navio, para que ele ficasse mais leve. Jonas, porém, havia descido ao porão do navio; ali havia se deitado, e dormia profundamente.

[[v32-1-6]]

^<<v32-1-6,6>>^ O capitão do navio se aproximou de Jonas e lhe disse: — O que está acontecendo com você? Agarrado no sono? Levante-se, invoque o seu deus! Talvez assim esse deus se lembre de nós, para que não pereçamos.

[[v32-1-7]]

^<<v32-1-7,7>>^ Os marinheiros diziam uns aos outros: — Vamos lançar sortes para descobrir quem é o culpado desse mal que caiu sobre nós. Lançaram sortes, e a sorte caiu sobre Jonas.

[[v32-1-8]]

^<<v32-1-8,8>>^ Então lhe disseram: — Agora nos diga: Quem é o culpado por este mal que nos aconteceu? Qual é a sua ocupação? De onde você vem? Qual a sua terra? E de que povo você é?

[[v32-1-9]]

^<<v32-1-9,9>>^ Jonas respondeu: — Eu sou hebreu e temo o Senhor , o Deus do céu, que fez o mar e a terra.

[[v32-1-10]]

^<<v32-1-10,10>>^ Então os homens ficaram com muito medo e lhe perguntaram: — O que é isso que você fez? Pois aqueles homens sabiam que Jonas estava fugindo da presença do Senhor , porque ele lhes havia contado.

[[v32-1-11]]

^<<v32-1-11,11>>^ Então lhe perguntaram: — O que devemos fazer com você, para que o mar se acalme? Disseram isto porque o mar ia se tornando cada vez mais tempestuoso.

[[v32-1-12]]

^<<v32-1-12,12>>^ Jonas respondeu: — Peguem-me e me lancem no mar; então o mar ficará calmo. Porque eu sei que, por minha causa, esta grande tempestade caiu sobre vocês.

[[v32-1-13]]

^<<v32-1-13,13>>^ Em vez disso, os homens remavam, esforçando-se por alcançar a terra, mas não podiam, porque o mar ia se tornando cada vez mais tempestuoso contra eles.

[[v32-1-14]]

^<<v32-1-14,14>>^ Então clamaram ao Senhor  e disseram: — Ah! Senhor ! Rogamos-te que não nos deixes perecer por causa da vida deste homem, e não faças cair sobre nós este sangue inocente. Porque tu, Senhor , fizeste o que foi do teu agrado.

[[v32-1-15]]

^<<v32-1-15,15>>^ Em seguida, os marinheiros pegaram Jonas e o lançaram no mar; e a fúria do mar se acalmou.

[[v32-1-16]]

^<<v32-1-16,16>>^ Então esses homens temeram muito o Senhor ; ofereceram sacrifícios ao Senhor  e fizeram votos.

[[v32-1-17]]

^<<v32-1-17,17>>^ O Senhor  ordenou que um grande peixe engolisse Jonas. E Jonas esteve três dias e três noites no ventre do peixe.

'''

xref:031-obadias/031-obadias-001.adoc#v31-1-0[&#60; Capítulo Anterior] | <<v32-1-0,Topo>> | xref:032-jonas/032-jonas-002.adoc#v32-2-0[Próximo Capítulo &#62;]