include::./index.adoc[]

[[v47-6-0]]
=== 2 Coríntios, 6
// naa ?, NAA - Nova Almeida Atualizada

[[v47-6-1]]

^<<v47-6-1,1>>^ E nós, na qualidade de cooperadores com ele, também exortamos a que vocês não recebam em vão a graça de Deus.

[[v47-6-2]]

^<<v47-6-2,2>>^ Porque ele diz: "No tempo aceitável escutei você e no dia da salvação eu o socorri." Eis agora o tempo oportuno! Eis agora o dia da salvação!

[[v47-6-3]]

^<<v47-6-3,3>>^ Não queremos dar nenhum motivo de escândalo em coisa alguma, para que o ministério não seja censurado.

[[v47-6-4]]

^<<v47-6-4,4>>^ Pelo contrário, em tudo nos recomendamos a nós mesmos como ministros de Deus: na muita paciência, nas aflições, nas privações, nas angústias,

[[v47-6-5]]

^<<v47-6-5,5>>^ nos açoites, nas prisões, nos tumultos, nos trabalhos, nas vigílias, nos jejuns,

[[v47-6-6]]

^<<v47-6-6,6>>^ na pureza, no saber, na paciência, na bondade, no Espírito Santo, no amor não fingido,

[[v47-6-7]]

^<<v47-6-7,7>>^ na palavra da verdade, no poder de Deus; pelas armas da justiça, tanto para atacar como para defender;

[[v47-6-8]]

^<<v47-6-8,8>>^ por honra e por desonra, por infâmia e por boa fama; como enganadores e sendo verdadeiros;

[[v47-6-9]]

^<<v47-6-9,9>>^ como desconhecidos, mas sendo bem-conhecidos; como se estivéssemos morrendo, mas eis que vivemos; como castigados, porém não mortos;

[[v47-6-10]]

^<<v47-6-10,10>>^ como entristecidos, mas sempre alegres; como pobres, mas enriquecendo a muitos; como nada tendo, mas possuindo tudo.

[[v47-6-11]]

^<<v47-6-11,11>>^ Ó coríntios, temos falado com toda a franqueza e estamos de coração aberto para vocês.

[[v47-6-12]]

^<<v47-6-12,12>>^ Nosso afeto por vocês não tem limites; vocês é que estão limitados em seu afeto por nós.

[[v47-6-13]]

^<<v47-6-13,13>>^ Ora, como justa retribuição — e falo a vocês como a filhos — peço que também vocês abram o seu coração para nós.

[[v47-6-14]]

^<<v47-6-14,14>>^ Não se ponham em jugo desigual com os descrentes. Pois que sociedade pode haver entre a justiça e a iniquidade? Ou que comunhão existe entre a luz e as trevas?

[[v47-6-15]]

^<<v47-6-15,15>>^ Que harmonia pode haver entre Cristo e o Maligno? Ou que união existe entre o crente e o descrente?

[[v47-6-16]]

^<<v47-6-16,16>>^ Que ligação há entre o santuário de Deus e os ídolos? Porque nós somos santuário do Deus vivo, como ele próprio disse: "Habitarei e andarei entre eles; serei o seu Deus, e eles serão o meu povo."

[[v47-6-17]]

^<<v47-6-17,17>>^ Por isso, o Senhor diz: "Saiam do meio deles e separem-se deles. Não toquem em coisa impura, e eu os receberei."

[[v47-6-18]]

^<<v47-6-18,18>>^ "Serei o Pai de vocês, e vocês serão meus filhos e minhas filhas", diz o Senhor Todo-Poderoso.

'''

xref:047-2-corintios/047-2-corintios-005.adoc#v47-5-0[&#60; Capítulo Anterior] | <<v47-6-0,Topo>> | xref:047-2-corintios/047-2-corintios-007.adoc#v47-7-0[Próximo Capítulo &#62;]