include::./index.adoc[]

[[v47-1-0]]
=== 2 Coríntios, 1
// naa ?, NAA - Nova Almeida Atualizada

[[v47-1-1]]

^<<v47-1-1,1>>^ Paulo, apóstolo de Cristo Jesus pela vontade de Deus, e o irmão Timóteo, à igreja de Deus que está em Corinto e a todos os santos em toda a Acaia.

[[v47-1-2]]

^<<v47-1-2,2>>^ Que a graça e a paz de Deus, nosso Pai, e do Senhor Jesus Cristo estejam com vocês.

[[v47-1-3]]

^<<v47-1-3,3>>^ Bendito seja o Deus e Pai de nosso Senhor Jesus Cristo, o Pai de misericórdias e Deus de toda consolação!

[[v47-1-4]]

^<<v47-1-4,4>>^ É ele que nos consola em toda a nossa tribulação, para que, pela consolação que nós mesmos recebemos de Deus, possamos consolar os que estiverem em qualquer espécie de tribulação.

[[v47-1-5]]

^<<v47-1-5,5>>^ Porque, assim como transbordam sobre nós os sofrimentos de Cristo, assim também por meio de Cristo transborda o nosso consolo.

[[v47-1-6]]

^<<v47-1-6,6>>^ Se somos atribulados, é para o consolo e a salvação de vocês; se somos consolados, é também para o consolo de vocês. Esse consolo se torna eficaz na medida em que vocês suportam com paciência os mesmos sofrimentos que nós também suportamos.

[[v47-1-7]]

^<<v47-1-7,7>>^ A nossa esperança em relação a vocês é sólida, sabendo que, assim como vocês são participantes dos sofrimentos, assim também serão participantes da consolação.

[[v47-1-8]]

^<<v47-1-8,8>>^ Porque não queremos, irmãos, que vocês fiquem sem saber que tipo de tribulação nos sobreveio na província da Ásia. Foi algo acima das nossas forças, a ponto de perdermos a esperança até da própria vida.

[[v47-1-9]]

^<<v47-1-9,9>>^ De fato, tivemos em nós mesmos a sentença de morte, para que não confiássemos em nós mesmos, e sim no Deus que ressuscita os mortos,

[[v47-1-10]]

^<<v47-1-10,10>>^ o qual nos livrou e ainda livrará de tão grande morte. Nele temos esperado que ainda continuará a nos livrar,

[[v47-1-11]]

^<<v47-1-11,11>>^ enquanto vocês nos ajudam com orações a nosso favor, para que, por muitos, sejam dadas graças a Deus a nosso respeito, pelo benefício que nos foi concedido por meio da súplica de muitos.

[[v47-1-12]]

^<<v47-1-12,12>>^ Porque a nossa glória é esta: o testemunho da nossa consciência de que com simplicidade e sinceridade de Deus, não com sabedoria humana, mas na graça divina, temos vivido no mundo, especialmente em relação a vocês.

[[v47-1-13]]

^<<v47-1-13,13>>^ Porque nenhuma outra coisa escrevemos para vocês, a não ser aquilo que vocês leem e entendem. E espero que vocês entendam completamente,

[[v47-1-14]]

^<<v47-1-14,14>>^ como também já nos entenderam em parte, que seremos a glória de vocês, assim como vocês também serão a nossa glória no Dia de Jesus, nosso Senhor.

[[v47-1-15]]

^<<v47-1-15,15>>^ Com esta confiança, eu queria primeiro ir encontrar-me com vocês, para que tivessem um segundo benefício.

[[v47-1-16]]

^<<v47-1-16,16>>^ Queria, ao passar por aí, dirigir-me à Macedônia, e da Macedônia voltar a encontrar-me com vocês, sendo então encaminhado por vocês para a Judeia.

[[v47-1-17]]

^<<v47-1-17,17>>^ Ora, ao querer isso, será que agi com leviandade? Ou, ao tomar decisões, será que decido segundo a carne, de modo que haja em mim, simultaneamente, o "sim, sim" e o "não, não"?

[[v47-1-18]]

^<<v47-1-18,18>>^ Mas, como Deus é fiel, a nossa palavra, dirigida a vocês, não é "sim e não".

[[v47-1-19]]

^<<v47-1-19,19>>^ Porque o Filho de Deus, Jesus Cristo, que foi anunciado entre vocês por nós, isto é, por mim, Silvano e Timóteo, não foi "sim e não"; pelo contrário, nele sempre houve o "sim".

[[v47-1-20]]

^<<v47-1-20,20>>^ Porque todas as promessas de Deus têm nele o "sim". Por isso, também por meio dele se diz o "amém" para glória de Deus, por meio de nós.

[[v47-1-21]]

^<<v47-1-21,21>>^ Mas aquele que nos confirma juntamente com vocês em Cristo e que nos ungiu é Deus,

[[v47-1-22]]

^<<v47-1-22,22>>^ que também pôs o seu selo em nós e nos deu o penhor do Espírito em nosso coração.

[[v47-1-23]]

^<<v47-1-23,23>>^ Eu, porém, por minha vida, tomo Deus por testemunha de que foi para poupar vocês que ainda não voltei a Corinto.

[[v47-1-24]]

^<<v47-1-24,24>>^ Não que tenhamos domínio sobre a fé que vocês têm, mas porque somos cooperadores da alegria de vocês. Porque, pela fé, vocês estão firmes.

'''

xref:046-1-corintios/046-1-corintios-016.adoc#v46-16-0[&#60; Capítulo Anterior] | <<v47-1-0,Topo>> | xref:047-2-corintios/047-2-corintios-002.adoc#v47-2-0[Próximo Capítulo &#62;]