include::./index.adoc[]

[[v47-11-0]]
=== 2 Coríntios, 11
// naa ?, NAA - Nova Almeida Atualizada

[[v47-11-1]]

^<<v47-11-1,1>>^ Eu gostaria que vocês me suportassem um pouco mais na minha loucura. Portanto, suportem-me.

[[v47-11-2]]

^<<v47-11-2,2>>^ Tenho zelo por vocês com um zelo que vem de Deus, pois eu preparei vocês para apresentá-los como virgem pura a um só esposo, que é Cristo.

[[v47-11-3]]

^<<v47-11-3,3>>^ Temo que, assim como a serpente, com a sua astúcia, enganou Eva, assim também a mente de vocês seja corrompida e se afaste da simplicidade e pureza devidas a Cristo.

[[v47-11-4]]

^<<v47-11-4,4>>^ Pois, se vem alguém que prega outro Jesus, diferente daquele que nós pregamos, ou se vocês aceitam um espírito diferente daquele que já receberam ou um evangelho diferente do que já aceitaram, vocês toleram isso muito bem.

[[v47-11-5]]

^<<v47-11-5,5>>^ Porque suponho em nada ter sido inferior a esses "superapóstolos".

[[v47-11-6]]

^<<v47-11-6,6>>^ E, embora seja fraco no falar, não o sou no conhecimento. Em tudo e por todos os modos temos manifestado isto a vocês.

[[v47-11-7]]

^<<v47-11-7,7>>^ Será que cometi algum pecado pelo fato de viver humildemente, para que vocês fossem exaltados, visto que lhes anunciei o evangelho de Deus sem cobrar nada?

[[v47-11-8]]

^<<v47-11-8,8>>^ Tirei de outras igrejas, recebendo salário, para poder servir a vocês.

[[v47-11-9]]

^<<v47-11-9,9>>^ E, estando entre vocês, ao passar privações, não me fiz pesado a ninguém; pois os irmãos, quando vieram da Macedônia, supriram o que me faltava. Em tudo, me guardei e me guardarei de ser pesado a vocês.

[[v47-11-10]]

^<<v47-11-10,10>>^ Pela verdade de Cristo que está em mim, garanto que esta glória não me será tirada nas regiões da Acaia.

[[v47-11-11]]

^<<v47-11-11,11>>^ Por quê? Será que é porque não amo vocês? Deus o sabe.

[[v47-11-12]]

^<<v47-11-12,12>>^ Mas o que faço, isso continuarei a fazer, para não dar oportunidade àqueles que a buscam com o objetivo de serem considerados iguais a nós, naquilo em que se gloriam.

[[v47-11-13]]

^<<v47-11-13,13>>^ Porque esses tais são falsos apóstolos, obreiros fraudulentos, disfarçando-se em apóstolos de Cristo.

[[v47-11-14]]

^<<v47-11-14,14>>^ E não é de admirar, porque o próprio Satanás se disfarça de anjo de luz.

[[v47-11-15]]

^<<v47-11-15,15>>^ Portanto, não deveria surpreender que os seus próprios ministros se disfarcem em ministros de justiça. O fim deles será conforme as suas obras.

[[v47-11-16]]

^<<v47-11-16,16>>^ Outra vez digo: ninguém pense que estou louco. Mas, se vocês pensam que sim, recebam-me como um louco, para que também eu me glorie por um instante.

[[v47-11-17]]

^<<v47-11-17,17>>^ O que falo nesta confiança de gloriar-me, não o falo segundo o Senhor, mas como por loucura.

[[v47-11-18]]

^<<v47-11-18,18>>^ E, visto que muitos se gloriam segundo a carne, também eu me gloriarei.

[[v47-11-19]]

^<<v47-11-19,19>>^ Porque, sendo tão sábios, de boa vontade vocês toleram os loucos.

[[v47-11-20]]

^<<v47-11-20,20>>^ Vocês toleram quem os escravize, quem os explore, quem os engane, quem se exalte, quem lhes dê bofetadas no rosto.

[[v47-11-21]]

^<<v47-11-21,21>>^ Para minha vergonha, confesso que fomos fracos demais para isso! Mas, naquilo em que outros têm ousadia — e volto a falar como se fosse louco — também eu a tenho.

[[v47-11-22]]

^<<v47-11-22,22>>^ São hebreus? Eu também! São israelitas? Eu também! São da descendência de Abraão? Eu também!

[[v47-11-23]]

^<<v47-11-23,23>>^ São ministros de Cristo? Falando como se estivesse fora de mim, afirmo que sou ainda mais: em trabalhos, muito mais; em prisões, muito mais; em açoites, sem medida; em perigos de morte, muitas vezes.

[[v47-11-24]]

^<<v47-11-24,24>>^ Cinco vezes recebi dos judeus quarenta açoites menos um.

[[v47-11-25]]

^<<v47-11-25,25>>^ Três vezes fui açoitado com varas. Uma vez fui apedrejado. Três vezes naufraguei. Fiquei uma noite e um dia boiando em alto mar.

[[v47-11-26]]

^<<v47-11-26,26>>^ Em viagens, muitas vezes; em perigos de rios, em perigos de assaltantes, em perigos entre patrícios, em perigos entre gentios, em perigos na cidade, em perigos no deserto, em perigos no mar, em perigos entre falsos irmãos;

[[v47-11-27]]

^<<v47-11-27,27>>^ em trabalhos e fadigas, em vigílias, muitas vezes; em fome e sede, em jejuns, muitas vezes; em frio e nudez.

[[v47-11-28]]

^<<v47-11-28,28>>^ Além das coisas exteriores, ainda pesa sobre mim diariamente a preocupação com todas as igrejas.

[[v47-11-29]]

^<<v47-11-29,29>>^ Quem enfraquece, que eu também não enfraqueça? Quem se escandaliza, que eu não fique indignado?

[[v47-11-30]]

^<<v47-11-30,30>>^ Se tenho de me gloriar, vou me gloriar no que diz respeito à minha fraqueza.

[[v47-11-31]]

^<<v47-11-31,31>>^ O Deus e Pai do Senhor Jesus, que é bendito para sempre, sabe que não minto.

[[v47-11-32]]

^<<v47-11-32,32>>^ Em Damasco, o governador nomeado pelo rei Aretas montou guarda na cidade dos damascenos, para me prender,

[[v47-11-33]]

^<<v47-11-33,33>>^ mas, num grande cesto, me desceram por uma janela da muralha, e assim me livrei das mãos dele.

'''

xref:047-2-corintios/047-2-corintios-010.adoc#v47-10-0[&#60; Capítulo Anterior] | <<v47-11-0,Topo>> | xref:047-2-corintios/047-2-corintios-012.adoc#v47-12-0[Próximo Capítulo &#62;]