include::./index.adoc[]

[[v47-2-0]]
=== 2 Coríntios, 2
// naa ?, NAA - Nova Almeida Atualizada

[[v47-2-1]]

^<<v47-2-1,1>>^ Porque decidi por mim mesmo o seguinte: não voltar a me encontrar com vocês em tristeza.

[[v47-2-2]]

^<<v47-2-2,2>>^ Porque, se eu entristeço vocês, quem me alegrará, senão aquele a quem tenho entristecido?

[[v47-2-3]]

^<<v47-2-3,3>>^ E escrevi isso para que, quando eu for, não seja entristecido por aqueles que deveriam me alegrar, confiando em todos vocês de que a minha alegria é também a alegria de vocês.

[[v47-2-4]]

^<<v47-2-4,4>>^ Porque lhes escrevi no meio de muitos sofrimentos e angústia de coração, com muitas lágrimas, não para que vocês ficassem tristes, mas para que soubessem do amor que tenho por vocês.

[[v47-2-5]]

^<<v47-2-5,5>>^ Ora, se alguém causou tristeza, não o fez a mim, mas, para que eu não seja demasiadamente áspero, digo que em parte causou tristeza a todos vocês.

[[v47-2-6]]

^<<v47-2-6,6>>^ Basta-lhe a punição imposta pela maioria.

[[v47-2-7]]

^<<v47-2-7,7>>^ De modo que, agora, pelo contrário, vocês devem perdoar e consolar, para que esse indivíduo não seja consumido por excessiva tristeza.

[[v47-2-8]]

^<<v47-2-8,8>>^ Por isso, peço que vocês confirmem o amor de vocês para com ele.

[[v47-2-9]]

^<<v47-2-9,9>>^ E foi por isso também que eu lhes escrevi, para ter prova de que, em tudo, vocês são obedientes.

[[v47-2-10]]

^<<v47-2-10,10>>^ A quem vocês perdoam alguma coisa, eu também perdoo. Pois o que perdoei, se é que perdoei alguma coisa, eu o fiz por causa de vocês na presença de Cristo,

[[v47-2-11]]

^<<v47-2-11,11>>^ para que Satanás não alcance vantagem sobre nós, pois não ignoramos quais são as intenções dele.

[[v47-2-12]]

^<<v47-2-12,12>>^ Quando cheguei a Trôade para pregar o evangelho de Cristo, vi que uma porta se havia aberto para mim, no Senhor.

[[v47-2-13]]

^<<v47-2-13,13>>^ No entanto, não tive tranquilidade no meu espírito, porque não encontrei o meu irmão Tito. Por isso, despedindo-me deles, parti para a Macedônia.

[[v47-2-14]]

^<<v47-2-14,14>>^ Graças, porém, a Deus, que, em Cristo, sempre nos conduz em triunfo e, por meio de nós, manifesta a fragrância do seu conhecimento em todos os lugares.

[[v47-2-15]]

^<<v47-2-15,15>>^ Porque nós somos para com Deus o bom perfume de Cristo, tanto entre os que estão sendo salvos como entre os que estão se perdendo.

[[v47-2-16]]

^<<v47-2-16,16>>^ Para com estes, cheiro de morte para morte; para com aqueles, aroma de vida para vida. Quem, porém, é capaz de fazer estas coisas?

[[v47-2-17]]

^<<v47-2-17,17>>^ Porque nós não estamos, como tantos outros, mercadejando a palavra de Deus. Pelo contrário, em Cristo é que falamos na presença de Deus, com sinceridade e da parte do próprio Deus.

'''

xref:047-2-corintios/047-2-corintios-001.adoc#v47-1-0[&#60; Capítulo Anterior] | <<v47-2-0,Topo>> | xref:047-2-corintios/047-2-corintios-003.adoc#v47-3-0[Próximo Capítulo &#62;]