include::./index.adoc[]

[[v47-3-0]]
=== 2 Coríntios, 3
// naa ?, NAA - Nova Almeida Atualizada

[[v47-3-1]]

^<<v47-3-1,1>>^ Estamos começando outra vez a recomendar a nós mesmos? Ou será que temos necessidade, como alguns, de entregar cartas de recomendação para vocês ou pedi-las a vocês?

[[v47-3-2]]

^<<v47-3-2,2>>^ Vocês são a nossa carta, escrita em nosso coração, conhecida e lida por todos.

[[v47-3-3]]

^<<v47-3-3,3>>^ Vocês manifestam que são carta de Cristo, produzida pelo nosso ministério, escrita não com tinta, mas com o Espírito do Deus vivo, não em tábuas de pedra, mas em tábuas de carne, isto é, nos corações.

[[v47-3-4]]

^<<v47-3-4,4>>^ E é por meio de Cristo que temos tal confiança em Deus.

[[v47-3-5]]

^<<v47-3-5,5>>^ Não que, por nós mesmos, sejamos capazes de pensar alguma coisa, como se partisse de nós; pelo contrário, a nossa capacidade vem de Deus,

[[v47-3-6]]

^<<v47-3-6,6>>^ o qual nos capacitou para sermos ministros de uma nova aliança, não da letra, mas do Espírito; porque a letra mata, mas o Espírito vivifica.

[[v47-3-7]]

^<<v47-3-7,7>>^ E, se o ministério da morte, gravado com letras em pedras, se revestiu de glória, a ponto de os filhos de Israel não poderem fixar os olhos na face de Moisés, por causa da glória do seu rosto, ainda que fosse uma glória que estava desaparecendo,

[[v47-3-8]]

^<<v47-3-8,8>>^ como não será de maior glória o ministério do Espírito?

[[v47-3-9]]

^<<v47-3-9,9>>^ Porque, se o ministério da condenação teve glória, em muito maior proporção será glorioso o ministério da justiça.

[[v47-3-10]]

^<<v47-3-10,10>>^ Pois, neste particular, o que era glorioso já não tem mais glória diante da glória atual, que é muito maior.

[[v47-3-11]]

^<<v47-3-11,11>>^ Porque, se o que estava desaparecendo teve a sua glória, muito mais glória tem o que é permanente.

[[v47-3-12]]

^<<v47-3-12,12>>^ Tendo, pois, tal esperança, agimos com muita ousadia.

[[v47-3-13]]

^<<v47-3-13,13>>^ E não somos como Moisés, que punha um véu sobre o rosto, para que os filhos de Israel não pudessem fixar os olhos no fim daquilo que estava desaparecendo.

[[v47-3-14]]

^<<v47-3-14,14>>^ Mas a mente deles se endureceu. Pois, até o dia de hoje, o mesmo véu permanece sobre a leitura da antiga aliança; não foi tirado, pois só em Cristo ele é removido.

[[v47-3-15]]

^<<v47-3-15,15>>^ Mas, até hoje, quando Moisés é lido, o véu está posto sobre o coração deles.

[[v47-3-16]]

^<<v47-3-16,16>>^ Quando, porém, alguém se converte ao Senhor, o véu é tirado.

[[v47-3-17]]

^<<v47-3-17,17>>^ Ora, este Senhor é o Espírito; e onde está o Espírito do Senhor, aí há liberdade.

[[v47-3-18]]

^<<v47-3-18,18>>^ E todos nós, com o rosto descoberto, contemplando a glória do Senhor, somos transformados, de glória em glória, na sua própria imagem, como pelo Senhor, que é o Espírito.

'''

xref:047-2-corintios/047-2-corintios-002.adoc#v47-2-0[&#60; Capítulo Anterior] | <<v47-3-0,Topo>> | xref:047-2-corintios/047-2-corintios-004.adoc#v47-4-0[Próximo Capítulo &#62;]