include::./index.adoc[]

[[v47-4-0]]
=== 2 Coríntios, 4
// naa ?, NAA - Nova Almeida Atualizada

[[v47-4-1]]

^<<v47-4-1,1>>^ Por isso, tendo este ministério, segundo a misericórdia que nos foi dada, não desanimamos.

[[v47-4-2]]

^<<v47-4-2,2>>^ Pelo contrário, rejeitamos as coisas ocultas que trazem vergonha, não agindo com astúcia, nem adulterando a palavra de Deus. E assim, pela manifestação da verdade, nos recomendamos à consciência de todos na presença de Deus.

[[v47-4-3]]

^<<v47-4-3,3>>^ Mas, se o nosso evangelho ainda está encoberto, é para os que se perdem que ele está encoberto,

[[v47-4-4]]

^<<v47-4-4,4>>^ nos quais o deus deste mundo cegou o entendimento dos descrentes, para que não lhes resplandeça a luz do evangelho da glória de Cristo, o qual é a imagem de Deus.

[[v47-4-5]]

^<<v47-4-5,5>>^ Porque não pregamos a nós mesmos, mas a Jesus Cristo como Senhor e a nós mesmos como servos de vocês, por causa de Jesus.

[[v47-4-6]]

^<<v47-4-6,6>>^ Porque Deus, que disse: "Das trevas resplandeça a luz", ele mesmo resplandeceu em nosso coração, para iluminação do conhecimento da glória de Deus na face de Jesus Cristo.

[[v47-4-7]]

^<<v47-4-7,7>>^ Temos, porém, este tesouro em vasos de barro, para que se veja que a excelência do poder provém de Deus, não de nós.

[[v47-4-8]]

^<<v47-4-8,8>>^ Em tudo somos atribulados, porém não angustiados; ficamos perplexos, porém não desanimados;

[[v47-4-9]]

^<<v47-4-9,9>>^ somos perseguidos, porém não abandonados; somos derrubados, porém não destruídos.

[[v47-4-10]]

^<<v47-4-10,10>>^ Levamos sempre no corpo o morrer de Jesus, para que também a vida dele se manifeste em nosso corpo.

[[v47-4-11]]

^<<v47-4-11,11>>^ Porque nós, que vivemos, somos sempre entregues à morte por causa de Jesus, para que também a vida de Jesus se manifeste em nossa carne mortal.

[[v47-4-12]]

^<<v47-4-12,12>>^ De modo que em nós opera a morte; em vocês, a vida.

[[v47-4-13]]

^<<v47-4-13,13>>^ Tendo, porém, o mesmo espírito de fé, como está escrito: "Eu cri, por isso falei", também nós cremos e, por isso, também falamos,

[[v47-4-14]]

^<<v47-4-14,14>>^ sabendo que aquele que ressuscitou o Senhor Jesus também nos ressuscitará com Jesus e nos apresentará juntamente com vocês.

[[v47-4-15]]

^<<v47-4-15,15>>^ Porque tudo isso é para o bem de vocês, para que a graça, multiplicando-se, torne abundantes as ações de graças por meio de muitos, para a glória de Deus.

[[v47-4-16]]

^<<v47-4-16,16>>^ Por isso não desanimamos. Pelo contrário, mesmo que o nosso ser exterior se desgaste, o nosso ser interior se renova dia a dia.

[[v47-4-17]]

^<<v47-4-17,17>>^ Porque a nossa leve e momentânea tribulação produz para nós um eterno peso de glória, acima de toda comparação,

[[v47-4-18]]

^<<v47-4-18,18>>^ na medida em que não olhamos para as coisas que se veem, mas para as que não se veem. Porque as coisas que se veem são temporais, mas as que não se veem são eternas.

'''

xref:047-2-corintios/047-2-corintios-003.adoc#v47-3-0[&#60; Capítulo Anterior] | <<v47-4-0,Topo>> | xref:047-2-corintios/047-2-corintios-005.adoc#v47-5-0[Próximo Capítulo &#62;]