include::./index.adoc[]

[[v47-10-0]]
=== 2 Coríntios, 10
// naa ?, NAA - Nova Almeida Atualizada

[[v47-10-1]]

^<<v47-10-1,1>>^ E eu mesmo, Paulo, peço a vocês, pela mansidão e bondade de Cristo — eu que, na verdade, quando estou com vocês, sou humilde, mas, quando ausente, sou ousado para com vocês —,

[[v47-10-2]]

^<<v47-10-2,2>>^ sim, eu peço que não me obriguem a ser ousado, quando estiver com vocês, servindo-me daquela firmeza com que penso que devo tratar alguns que nos julgam como se andássemos segundo a carne.

[[v47-10-3]]

^<<v47-10-3,3>>^ Porque, embora andemos na carne, não lutamos segundo a carne.

[[v47-10-4]]

^<<v47-10-4,4>>^ Porque as armas da nossa luta não são carnais, mas poderosas em Deus, para destruir fortalezas. Destruímos raciocínios falaciosos

[[v47-10-5]]

^<<v47-10-5,5>>^ e toda arrogância que se levanta contra o conhecimento de Deus, e levamos cativo todo pensamento à obediência de Cristo.

[[v47-10-6]]

^<<v47-10-6,6>>^ E estaremos prontos para punir qualquer desobediência, quando a obediência de vocês estiver completa.

[[v47-10-7]]

^<<v47-10-7,7>>^ Observem o que está evidente. Se alguém confia em si que é de Cristo, pense outra vez consigo mesmo que, assim como ele é de Cristo, também nós o somos.

[[v47-10-8]]

^<<v47-10-8,8>>^ Porque, se eu me gloriar um pouco mais a respeito da nossa autoridade, a qual o Senhor nos conferiu para edificação e não para destruição de vocês, não me envergonharei.

[[v47-10-9]]

^<<v47-10-9,9>>^ Não quero que pareça ser meu objetivo intimidar vocês por meio de cartas.

[[v47-10-10]]

^<<v47-10-10,10>>^ Alguns dizem: "As cartas são graves e fortes, mas a presença pessoal dele é fraca e a sua palavra é desprezível."

[[v47-10-11]]

^<<v47-10-11,11>>^ Que tal pessoa leve em conta o seguinte: o que somos na palavra por cartas, estando ausentes, seremos também em ações, quando presentes.

[[v47-10-12]]

^<<v47-10-12,12>>^ Porque não ousamos nos classificar ou comparar com alguns que louvam a si mesmos. Mas eles, medindo-se consigo mesmos e comparando-se consigo mesmos, revelam falta de entendimento.

[[v47-10-13]]

^<<v47-10-13,13>>^ Nós, porém, não nos gloriaremos além da medida, mas respeitamos o limite da esfera de ação que Deus nos demarcou e que se estende até vocês.

[[v47-10-14]]

^<<v47-10-14,14>>^ Porque não ultrapassamos os nossos limites como se não devêssemos chegar até vocês, pois já chegamos até vocês com o evangelho de Cristo.

[[v47-10-15]]

^<<v47-10-15,15>>^ Não nos gloriamos além da medida no trabalho que outros fizeram, mas temos a esperança de que, à medida que cresce a fé que vocês têm, seremos cada vez mais engrandecidos entre vocês, dentro da nossa esfera de ação,

[[v47-10-16]]

^<<v47-10-16,16>>^ a fim de anunciar o evangelho para além das fronteiras em que vocês se encontram, sem com isto nos gloriarmos de coisas já realizadas na esfera de ação de outros.

[[v47-10-17]]

^<<v47-10-17,17>>^ Aquele, porém, que se gloria, glorie-se no Senhor.

[[v47-10-18]]

^<<v47-10-18,18>>^ Porque não é aprovado quem recomenda a si mesmo, e sim aquele que o Senhor recomenda.

'''

xref:047-2-corintios/047-2-corintios-009.adoc#v47-9-0[&#60; Capítulo Anterior] | <<v47-10-0,Topo>> | xref:047-2-corintios/047-2-corintios-011.adoc#v47-11-0[Próximo Capítulo &#62;]