include::./index.adoc[]

[[v47-9-0]]
=== 2 Coríntios, 9
// naa ?, NAA - Nova Almeida Atualizada

[[v47-9-1]]

^<<v47-9-1,1>>^ Ora, quanto à assistência a favor dos santos, não é necessário que eu escreva a vocês.

[[v47-9-2]]

^<<v47-9-2,2>>^ Porque conheço a boa vontade de vocês, da qual me orgulho diante dos macedônios, dizendo que os irmãos da Acaia estão preparados desde o ano passado. E o zelo de vocês tem estimulado muitos deles.

[[v47-9-3]]

^<<v47-9-3,3>>^ Mas enviei estes irmãos, para que o nosso louvor a respeito de vocês neste particular não se desminta, a fim de que, como venho dizendo, vocês estivessem preparados.

[[v47-9-4]]

^<<v47-9-4,4>>^ Do contrário, se alguns macedônios forem comigo e descobrirem que vocês não estão preparados, isso será uma vergonha para nós — para não dizer que será para vocês também — por toda essa confiança que tivemos em vocês.

[[v47-9-5]]

^<<v47-9-5,5>>^ Portanto, julguei necessário recomendar aos irmãos que me precedessem na visita a vocês e preparassem de antemão a oferta que vocês prometeram, para que esteja pronta como expressão de generosidade e não de avareza.

[[v47-9-6]]

^<<v47-9-6,6>>^ E isto afirmo: aquele que semeia pouco também colherá pouco; e o que semeia com fartura também colherá com fartura.

[[v47-9-7]]

^<<v47-9-7,7>>^ Cada um contribua segundo tiver proposto no coração, não com tristeza ou por necessidade, porque Deus ama quem dá com alegria.

[[v47-9-8]]

^<<v47-9-8,8>>^ Deus pode tornar abundante em vocês toda graça, a fim de que, tendo sempre, em tudo, ampla suficiência, vocês sejam abundantes em toda boa obra,

[[v47-9-9]]

^<<v47-9-9,9>>^ como está escrito: "Distribuiu, deu aos pobres, a sua justiça permanece para sempre."

[[v47-9-10]]

^<<v47-9-10,10>>^ E Deus, que dá semente ao que semeia e pão para alimento, também suprirá e aumentará as sementes e multiplicará os frutos da justiça de vocês.

[[v47-9-11]]

^<<v47-9-11,11>>^ Assim, vocês serão enriquecidos em tudo para toda generosidade, a qual, por meio de nós, resulta em orações de gratidão a Deus.

[[v47-9-12]]

^<<v47-9-12,12>>^ Porque o serviço desta assistência não só supre a necessidade dos santos, mas também transborda em muitas orações de gratidão a Deus.

[[v47-9-13]]

^<<v47-9-13,13>>^ Na prova deste serviço, eles glorificam a Deus pela obediência da confissão que vocês fazem do evangelho de Cristo e pela generosidade com que vocês contribuem para eles e para todos,

[[v47-9-14]]

^<<v47-9-14,14>>^ enquanto eles oram por vocês, com grande afeto, por causa da extraordinária graça de Deus que foi dada a vocês.

[[v47-9-15]]

^<<v47-9-15,15>>^ Graças a Deus pelo seu dom indescritível!

'''

xref:047-2-corintios/047-2-corintios-008.adoc#v47-8-0[&#60; Capítulo Anterior] | <<v47-9-0,Topo>> | xref:047-2-corintios/047-2-corintios-010.adoc#v47-10-0[Próximo Capítulo &#62;]