include::./index.adoc[]

[[v47-12-0]]
=== 2 Coríntios, 12
// naa ?, NAA - Nova Almeida Atualizada

[[v47-12-1]]

^<<v47-12-1,1>>^ Se é necessário que eu me glorie, ainda que não seja conveniente, vou falar a respeito das visões e revelações do Senhor.

[[v47-12-2]]

^<<v47-12-2,2>>^ Conheço um homem em Cristo que, há catorze anos, foi arrebatado até o terceiro céu. Se isso foi no corpo ou fora do corpo, não sei; Deus o sabe.

[[v47-12-3]]

^<<v47-12-3,3>>^ E sei que esse homem — se no corpo ou sem o corpo, não sei; Deus o sabe —

[[v47-12-4]]

^<<v47-12-4,4>>^ foi arrebatado ao paraíso e ouviu palavras indizíveis, que homem nenhum tem permissão para repetir.

[[v47-12-5]]

^<<v47-12-5,5>>^ Desse eu me gloriarei; não, porém, de mim mesmo, a não ser nas minhas fraquezas.

[[v47-12-6]]

^<<v47-12-6,6>>^ Pois, se eu vier a gloriar-me, não serei louco, porque estarei falando a verdade. Mas evito fazer isso para que ninguém se preocupe comigo mais do que vê em mim ou do que ouve de mim.

[[v47-12-7]]

^<<v47-12-7,7>>^ E, para que eu não ficasse orgulhoso com a grandeza das revelações, foi-me posto um espinho na carne, mensageiro de Satanás, para me esbofetear, a fim de que eu não me exalte.

[[v47-12-8]]

^<<v47-12-8,8>>^ Três vezes pedi ao Senhor que o afastasse de mim.

[[v47-12-9]]

^<<v47-12-9,9>>^ Então ele me disse: "A minha graça é o que basta para você, porque o poder se aperfeiçoa na fraqueza."  De boa vontade, pois, mais me gloriarei nas fraquezas, para que sobre mim repouse o poder de Cristo.

[[v47-12-10]]

^<<v47-12-10,10>>^ Por isso, sinto prazer nas fraquezas, nos insultos, nas privações, nas perseguições, nas angústias, por amor de Cristo. Porque, quando sou fraco, então é que sou forte.

[[v47-12-11]]

^<<v47-12-11,11>>^ Fiz-me louco, mas vocês me obrigaram a isso. Eu devia ter sido recomendado por vocês, pois em nada fui inferior a esses "superapóstolos", ainda que nada sou.

[[v47-12-12]]

^<<v47-12-12,12>>^ Pois as minhas credenciais de apóstolo foram apresentadas no meio de vocês, com toda a paciência, por sinais, prodígios e maravilhas.

[[v47-12-13]]

^<<v47-12-13,13>>^ Pois em que vocês foram inferiores às demais igrejas, senão no fato de eu não ter sido pesado a vocês? Perdoem-me esta injustiça.

[[v47-12-14]]

^<<v47-12-14,14>>^ Eis que, pela terceira vez, estou pronto para visitá-los e não serei um peso para vocês. Pois não estou interessado nos bens de vocês, e sim em vocês mesmos. Não são os filhos que devem juntar riquezas para os pais, mas os pais, para os filhos.

[[v47-12-15]]

^<<v47-12-15,15>>^ Eu de boa vontade gastarei e me deixarei gastar em favor de vocês. Se eu os amo cada vez mais, será que vou ser amado cada vez menos?

[[v47-12-16]]

^<<v47-12-16,16>>^ Seja como for, eu não fui um peso para vocês. No entanto, sendo astuto, eu os prendi com astúcia.

[[v47-12-17]]

^<<v47-12-17,17>>^ Será que eu explorei vocês por meio de alguém que lhes enviei?

[[v47-12-18]]

^<<v47-12-18,18>>^ Pedi a Tito que fosse até aí e mandei com ele outro irmão. Será que Tito explorou vocês? Não é verdade que temos andado no mesmo espírito? Não seguimos nas mesmas pisadas?

[[v47-12-19]]

^<<v47-12-19,19>>^ Há muito vocês podem estar pensando que queremos nos defender diante de vocês. Falamos em Cristo diante de Deus, e tudo isto, meus amados, é para a edificação de vocês.

[[v47-12-20]]

^<<v47-12-20,20>>^ Pois tenho receio de que, indo até aí, eu não os encontre na forma em que gostaria de encontrá-los, e que também vocês me achem diferente do que esperavam, e que haja entre vocês briga, inveja, ira, egoísmo, difamação, intriga, orgulho e tumulto.

[[v47-12-21]]

^<<v47-12-21,21>>^ Tenho receio de que, indo outra vez, o meu Deus me humilhe diante de vocês, e eu venha a chorar por muitos que, no passado, pecaram e não se arrependeram da impureza, da imoralidade sexual e da libertinagem que praticaram.

'''

xref:047-2-corintios/047-2-corintios-011.adoc#v47-11-0[&#60; Capítulo Anterior] | <<v47-12-0,Topo>> | xref:047-2-corintios/047-2-corintios-013.adoc#v47-13-0[Próximo Capítulo &#62;]