include::./index.adoc[]

[[v47-5-0]]
=== 2 Coríntios, 5
// naa ?, NAA - Nova Almeida Atualizada

[[v47-5-1]]

^<<v47-5-1,1>>^ Pois sabemos que, se a nossa casa terrestre deste tabernáculo se desfizer, temos da parte de Deus um edifício, uma casa não feita por mãos humanas, eterna, nos céus.

[[v47-5-2]]

^<<v47-5-2,2>>^ E, por isso, neste tabernáculo gememos, desejando muito ser revestidos da nossa habitação celestial;

[[v47-5-3]]

^<<v47-5-3,3>>^ se, de fato, formos encontrados vestidos e não nus.

[[v47-5-4]]

^<<v47-5-4,4>>^ Pois nós, os que estamos neste tabernáculo, gememos angustiados, não por querermos ser despidos, mas revestidos, para que o mortal seja absorvido pela vida.

[[v47-5-5]]

^<<v47-5-5,5>>^ Ora, foi o próprio Deus quem nos preparou para isto, dando-nos o penhor do Espírito.

[[v47-5-6]]

^<<v47-5-6,6>>^ Por isso, temos sempre confiança e sabemos que, enquanto no corpo, estamos ausentes do Senhor.

[[v47-5-7]]

^<<v47-5-7,7>>^ Porque andamos por fé e não pelo que vemos.

[[v47-5-8]]

^<<v47-5-8,8>>^ Sim, temos tal confiança e preferimos deixar o corpo e habitar com o Senhor.

[[v47-5-9]]

^<<v47-5-9,9>>^ É por isso que também nos esforçamos para ser agradáveis a ele, quer presentes, quer ausentes.

[[v47-5-10]]

^<<v47-5-10,10>>^ Porque é necessário que todos nós compareçamos diante do tribunal de Cristo, para que cada um receba segundo o bem ou o mal que tiver feito por meio do corpo.

[[v47-5-11]]

^<<v47-5-11,11>>^ E assim, conhecendo o temor do Senhor, procuramos persuadir as pessoas, mas somos plenamente conhecidos por Deus. E espero que também sejamos reconhecidos na consciência de vocês.

[[v47-5-12]]

^<<v47-5-12,12>>^ Não queremos novamente nos recomendar a vocês; pelo contrário, estamos dando uma oportunidade para vocês se orgulharem por nossa causa, para que tenham o que responder aos que se gloriam na aparência e não no coração.

[[v47-5-13]]

^<<v47-5-13,13>>^ Porque, se enlouquecemos, é para Deus, e, se conservamos o juízo, é para vocês.

[[v47-5-14]]

^<<v47-5-14,14>>^ Pois o amor de Cristo nos domina, porque reconhecemos isto: um morreu por todos; logo, todos morreram.

[[v47-5-15]]

^<<v47-5-15,15>>^ E ele morreu por todos, para que os que vivem não vivam mais para si mesmos, mas para aquele que por eles morreu e ressuscitou.

[[v47-5-16]]

^<<v47-5-16,16>>^ Assim que, nós, daqui por diante, a ninguém conhecemos segundo a carne; e, se antes conhecemos Cristo segundo a carne, já agora não o conhecemos deste modo.

[[v47-5-17]]

^<<v47-5-17,17>>^ E, assim, se alguém está em Cristo, é nova criatura; as coisas antigas já passaram; eis que se fizeram novas.

[[v47-5-18]]

^<<v47-5-18,18>>^ Ora, tudo isso provém de Deus, que nos reconciliou consigo mesmo por meio de Cristo e nos deu o ministério da reconciliação,

[[v47-5-19]]

^<<v47-5-19,19>>^ a saber, que Deus estava em Cristo reconciliando consigo o mundo, não levando em conta os pecados dos seres humanos e nos confiando a palavra da reconciliação.

[[v47-5-20]]

^<<v47-5-20,20>>^ Portanto, somos embaixadores em nome de Cristo, como se Deus exortasse por meio de nós. Em nome de Cristo, pois, pedimos que vocês se reconciliem com Deus.

[[v47-5-21]]

^<<v47-5-21,21>>^ Aquele que não conheceu pecado, Deus o fez pecado por nós, para que, nele, fôssemos feitos justiça de Deus.

'''

xref:047-2-corintios/047-2-corintios-004.adoc#v47-4-0[&#60; Capítulo Anterior] | <<v47-5-0,Topo>> | xref:047-2-corintios/047-2-corintios-006.adoc#v47-6-0[Próximo Capítulo &#62;]