include::./index.adoc[]

[[v10-20-0]]
=== 2 Samuel, 20
// naa ?, NAA - Nova Almeida Atualizada

[[v10-20-1]]

^<<v10-20-1,1>>^ Aconteceu que estava ali um homem perverso, cujo nome era Seba, filho de Bicri, homem de Benjamim. Ele tocou a trombeta e disse: — Não temos parte em Davi, nem herança no filho de Jessé. Cada um para as suas tendas, ó Israel.

[[v10-20-2]]

^<<v10-20-2,2>>^ Então todos os homens de Israel se separaram de Davi e seguiram Seba, filho de Bicri. Mas os homens de Judá se apegaram ao seu rei, conduzindo-o desde o Jordão até Jerusalém.

[[v10-20-3]]

^<<v10-20-3,3>>^ E Davi foi para o seu palácio em Jerusalém. O rei tomou as dez concubinas, que tinha deixado para cuidar do palácio, e as pôs em custódia, e as sustentou, porém não teve relações com elas. Elas ficaram enclausuradas até o dia em que morreram, vivendo como viúvas.

[[v10-20-4]]

^<<v10-20-4,4>>^ O rei disse a Amasa: — Convoque, para dentro de três dias, os homens de Judá e apresente-se aqui.

[[v10-20-5]]

^<<v10-20-5,5>>^ Amasa saiu para convocar os homens de Judá, mas demorou-se além do tempo que lhe havia sido dado.

[[v10-20-6]]

^<<v10-20-6,6>>^ Então Davi disse a Abisai: — Agora Seba, o filho de Bicri, nos fará mais mal do que Absalão. Por isso, pegue os servos do seu senhor e vá atrás dele, para que não ache para si cidades fortificadas e nos escape.

[[v10-20-7]]

^<<v10-20-7,7>>^ Então saíram com ele os soldados de Joabe, a guarda real e todos os valentes. Saíram de Jerusalém para perseguir Seba, filho de Bicri.

[[v10-20-8]]

^<<v10-20-8,8>>^ Quando chegaram à pedra grande que está em Gibeão, Amasa veio ao encontro deles. Joabe usava trajes militares e sobre eles um cinto, no qual, presa aos seus lombos, estava uma espada dentro da bainha. Quando Joabe se adiantou, sua espada caiu.

[[v10-20-9]]

^<<v10-20-9,9>>^ Então Joabe disse a Amasa: — Você vai bem, meu irmão? E, com a mão direita, pegou na barba de Amasa, para o beijar.

[[v10-20-10]]

^<<v10-20-10,10>>^ Amasa não reparou na espada que estava na mão de Joabe. Assim, este o feriu com ela na barriga e lhe derramou por terra os intestinos. Amasa morreu, sem que fosse preciso dar um segundo golpe. Então Joabe e o seu irmão Abisai perseguiram Seba, filho de Bicri.

[[v10-20-11]]

^<<v10-20-11,11>>^ Mas um dos moços de Joabe parou junto do corpo de Amasa e disse: — Quem está do lado de Joabe e é por Davi, siga Joabe!

[[v10-20-12]]

^<<v10-20-12,12>>^ Amasa estava envolto no seu sangue no meio do caminho. Quando o moço viu que todo o povo parava, arrastou Amasa do caminho para o campo e lançou um manto sobre ele. Porque ele via que todo aquele que chegava perto dele parava.

[[v10-20-13]]

^<<v10-20-13,13>>^ Depois que o corpo foi afastado do caminho, todos os homens seguiram Joabe, para perseguirem Seba, filho de Bicri.

[[v10-20-14]]

^<<v10-20-14,14>>^ Seba passou por todas as tribos de Israel até Abel-Bete-Maaca, e apenas os beritas se ajuntaram todos e o seguiram.

[[v10-20-15]]

^<<v10-20-15,15>>^ Joabe e os seus homens vieram e o cercaram em Abel-Bete-Maaca. E levantaram contra a cidade um montão da altura da muralha. E todo o povo que estava com Joabe batia na muralha para a derrubar.

[[v10-20-16]]

^<<v10-20-16,16>>^ Então uma mulher sábia gritou de dentro da cidade: — Escutem! Escutem! Digam a Joabe que venha cá, para que eu fale com ele.

[[v10-20-17]]

^<<v10-20-17,17>>^ Quando ele chegou perto, a mulher perguntou: — Você é Joabe? Ele respondeu: — Eu sou. Ela lhe disse: — Ouça as palavras desta sua serva. Joabe respondeu: — Estou ouvindo.

[[v10-20-18]]

^<<v10-20-18,18>>^ Então ela disse: — Antigamente se costumava dizer: "Peçam conselho na cidade de Abel"; e assim as questões eram resolvidas.

[[v10-20-19]]

^<<v10-20-19,19>>^ Eu sou uma das pacíficas e das fiéis em Israel, e você procura destruir uma cidade que é mãe em Israel. Por que você quer devorar a herança do Senhor ?

[[v10-20-20]]

^<<v10-20-20,20>>^ Então Joabe respondeu: — Longe, longe de mim que eu devore e destrua!

[[v10-20-21]]

^<<v10-20-21,21>>^ A coisa não é assim. Porém um homem da região montanhosa de Efraim, chamado Seba, filho de Bicri, levantou a mão contra o rei, contra Davi. Entreguem-me só este, e eu vou me retirar da cidade. Então a mulher disse a Joabe: — Eis que a cabeça dele será jogada por cima da muralha para você.

[[v10-20-22]]

^<<v10-20-22,22>>^ Então a mulher, na sua sabedoria, foi falar com todo o povo. E cortaram a cabeça de Seba, filho de Bicri, e a jogaram para Joabe. Então Joabe tocou a trombeta, e eles se retiraram da cidade, cada um para a sua casa. E Joabe voltou a Jerusalém, para junto do rei.

[[v10-20-23]]

^<<v10-20-23,23>>^ Joabe era comandante de todo o exército de Israel. Benaia, filho de Joiada, era comandante da guarda real.

[[v10-20-24]]

^<<v10-20-24,24>>^ Adorão era chefe dos que estavam sujeitos a trabalhos forçados. Josafá, filho de Ailude, era o cronista.

[[v10-20-25]]

^<<v10-20-25,25>>^ Seva era o escrivão. Zadoque e Abiatar eram os sacerdotes.

[[v10-20-26]]

^<<v10-20-26,26>>^ E também Ira, o jairita, era ministro de Davi.

'''

xref:010-2-samuel/010-2-samuel-019.adoc#v10-19-0[&#60; Capítulo Anterior] | <<v10-20-0,Topo>> | xref:010-2-samuel/010-2-samuel-021.adoc#v10-21-0[Próximo Capítulo &#62;]