include::./index.adoc[]

[[v10-1-0]]
=== 2 Samuel, 1
// naa ?, NAA - Nova Almeida Atualizada

[[v10-1-1]]

^<<v10-1-1,1>>^ Depois da morte de Saul, quando Davi tinha voltado de derrotar os amalequitas e já estava dois dias em Ziclague,

[[v10-1-2]]

^<<v10-1-2,2>>^ aconteceu que, no terceiro dia, veio do arraial de Saul um homem com as roupas rasgadas e terra sobre a cabeça. Ao chegar diante de Davi, ele se inclinou, prostrando-se em terra.

[[v10-1-3]]

^<<v10-1-3,3>>^ Davi lhe perguntou: — De onde você vem? Ele respondeu: — Fugi do arraial de Israel.

[[v10-1-4]]

^<<v10-1-4,4>>^ Então Davi disse: — Como foi isso? Conte-me o que aconteceu. O moço respondeu: — O povo fugiu da batalha, e muitos foram mortos. Saul e seu filho Jônatas também morreram.

[[v10-1-5]]

^<<v10-1-5,5>>^ Davi perguntou ao moço que lhe trazia as notícias: — Como você sabe que Saul e Jônatas, seu filho, estão mortos?

[[v10-1-6]]

^<<v10-1-6,6>>^ Então o moço portador das notícias disse: — Cheguei, por acaso, ao monte Gilboa, e eis que Saul estava apoiado sobre a sua lança. E os carros de guerra e a cavalaria se aproximavam dele.

[[v10-1-7]]

^<<v10-1-7,7>>^ Olhando ele para trás, me viu e me chamou. Eu disse: "Eis-me aqui."

[[v10-1-8]]

^<<v10-1-8,8>>^ Ele me perguntou: "Quem é você?" Eu respondi: "Eu sou amalequita."

[[v10-1-9]]

^<<v10-1-9,9>>^ Então ele me disse: "Venha aqui e me mate, pois me sinto vencido de cãibra, embora ainda esteja bem lúcido."

[[v10-1-10]]

^<<v10-1-10,10>>^ Então me aproximei dele e o matei, porque eu sabia que ele não viveria depois de ter caído. Peguei a coroa que ele tinha na cabeça e o bracelete e os trouxe aqui ao meu senhor.

[[v10-1-11]]

^<<v10-1-11,11>>^ Então Davi rasgou as suas próprias roupas, e todos os homens que estavam com ele fizeram o mesmo.

[[v10-1-12]]

^<<v10-1-12,12>>^ Prantearam, choraram e jejuaram até a tarde por Saul, por Jônatas, seu filho, pelo povo do Senhor  e pela casa de Israel, porque tinham caído à espada.

[[v10-1-13]]

^<<v10-1-13,13>>^ Então Davi perguntou ao moço portador das notícias: — De onde você é? Ele respondeu: — Sou filho de um homem estrangeiro, amalequita.

[[v10-1-14]]

^<<v10-1-14,14>>^ Davi lhe disse: — Como você não temeu estender a mão para matar o ungido do Senhor ?

[[v10-1-15]]

^<<v10-1-15,15>>^ Então Davi chamou um dos moços e lhe disse: — Vá até lá e mate-o. Ele foi e o matou,

[[v10-1-16]]

^<<v10-1-16,16>>^ enquanto Davi dizia: — O seu sangue caia sobre a sua cabeça, porque a sua própria boca testificou contra você, dizendo: "Matei o ungido do Senhor ."

[[v10-1-17]]

^<<v10-1-17,17>>^ Davi pranteou Saul e seu filho Jônatas com esta lamentação.

[[v10-1-18]]

^<<v10-1-18,18>>^ E ele ordenou que se ensinasse aos filhos de Judá o Hino ao Arco, que está escrito no Livro dos Justos.

[[v10-1-19]]

^<<v10-1-19,19>>^ A sua glória, ó Israel, foi morta sobre os seus montes! Como caíram os valentes!

[[v10-1-20]]

^<<v10-1-20,20>>^ Não anunciem isso em Gate, nem o publiquem nas ruas de Asquelom, para que não se alegrem as filhas dos filisteus, nem saltem de contentamento as filhas dos incircuncisos.

[[v10-1-21]]

^<<v10-1-21,21>>^ Montes de Gilboa, que sobre vocês não caia nem orvalho, nem chuva, nem haja aí campos que produzam ofertas, pois neles foi profanado o escudo dos valentes, o escudo de Saul, que nunca mais será ungido com óleo.

[[v10-1-22]]

^<<v10-1-22,22>>^ Sem sangue dos feridos, sem gordura dos valentes, nunca se recolheu o arco de Jônatas, nem voltou vazia a espada de Saul.

[[v10-1-23]]

^<<v10-1-23,23>>^ Saul e Jônatas, queridos e amáveis, nem na vida nem na morte se separaram! Eram mais ligeiros do que as águias, mais fortes do que os leões.

[[v10-1-24]]

^<<v10-1-24,24>>^ Filhas de Israel, chorem por Saul! Ele as vestia de rico escarlate, e enfeitava com ouro as roupas de vocês.

[[v10-1-25]]

^<<v10-1-25,25>>^ Como caíram os valentes no meio da batalha! Jônatas sobre os montes foi morto!

[[v10-1-26]]

^<<v10-1-26,26>>^ Estou angustiado por sua causa, meu irmão Jônatas; você era amabilíssimo para comigo! Excepcional era o seu amor, ultrapassando o amor de mulheres.

[[v10-1-27]]

^<<v10-1-27,27>>^ Como caíram os valentes, e pereceram as armas de guerra!

'''

xref:009-1-samuel/009-1-samuel-031.adoc#v9-31-0[&#60; Capítulo Anterior] | <<v10-1-0,Topo>> | xref:010-2-samuel/010-2-samuel-002.adoc#v10-2-0[Próximo Capítulo &#62;]