include::./index.adoc[]

[[v10-18-0]]
=== 2 Samuel, 18
// naa ?, NAA - Nova Almeida Atualizada

[[v10-18-1]]

^<<v10-18-1,1>>^ Davi contou os soldados que tinha consigo e pôs sobre eles capitães de mil e capitães de cem.

[[v10-18-2]]

^<<v10-18-2,2>>^ Então Davi enviou o povo: uma terça parte sob o comando de Joabe, outra sob o comando de Abisai, filho de Zeruia e irmão de Joabe, e a outra sob o comando de Itai, o geteu. E o rei disse ao povo: — Eu também irei com vocês.

[[v10-18-3]]

^<<v10-18-3,3>>^ Mas eles disseram: — O senhor não deveria ir, porque, se formos obrigados a fugir, não se importarão conosco, nem ainda que metade de nós morra; mas o senhor vale por dez mil de nós. Será melhor que da cidade o senhor nos preste socorro.

[[v10-18-4]]

^<<v10-18-4,4>>^ Davi respondeu: — O que vocês acharem melhor, isso farei. O rei se pôs ao lado do portão da cidade, e todo o povo saiu a centenas e a milhares.

[[v10-18-5]]

^<<v10-18-5,5>>^ E o rei deu ordem a Joabe, a Abisai e a Itai, dizendo: — Por amor a mim, tratem com brandura o jovem Absalão. Todo o povo ouviu quando o rei dava a ordem a todos os capitães a respeito de Absalão.

[[v10-18-6]]

^<<v10-18-6,6>>^ Assim, o povo saiu ao campo, a encontrar-se com Israel, e a batalha teve lugar na floresta de Efraim.

[[v10-18-7]]

^<<v10-18-7,7>>^ Ali, o povo de Israel foi batido diante dos servos de Davi; e, naquele mesmo dia, houve ali grande derrota, com a perda de vinte mil homens.

[[v10-18-8]]

^<<v10-18-8,8>>^ A batalha se estendeu por toda aquela região, e, naquele dia, a floresta consumiu mais gente do que a espada.

[[v10-18-9]]

^<<v10-18-9,9>>^ Absalão, montado em sua mula, encontrou-se com os homens de Davi. Quando a mula passou debaixo dos ramos de um grande carvalho, a cabeça de Absalão ficou presa nos ramos. Ele ficou pendurado entre o céu e a terra, enquanto a mula, que ele montava, passou adiante.

[[v10-18-10]]

^<<v10-18-10,10>>^ Um homem viu isso e foi dizer a Joabe: — Eu vi Absalão pendurado num carvalho.

[[v10-18-11]]

^<<v10-18-11,11>>^ Então Joabe disse ao homem que lhe trouxe a notícia: — O quê?! Você o viu? E por que não o abateu ali mesmo, derrubando-o por terra? Eu teria dado a você dez moedas de prata e um cinto.

[[v10-18-12]]

^<<v10-18-12,12>>^ Mas o homem disse a Joabe: — Ainda que me pusessem nas mãos mil moedas de prata, não estenderia a mão contra o filho do rei, pois ouvimos muito bem que o rei deu uma ordem ao senhor, a Abisai e a Itai, dizendo: "Poupem o jovem Absalão".

[[v10-18-13]]

^<<v10-18-13,13>>^ Se eu tivesse agido traiçoeiramente contra a vida dele, nada disso poderia ser escondido do rei, e nem mesmo o senhor me defenderia.

[[v10-18-14]]

^<<v10-18-14,14>>^ Então Joabe disse: — Não vou perder mais tempo com você. Joabe pegou três dardos e com eles traspassou o coração de Absalão, enquanto ele ainda estava vivo, pendurado no carvalho.

[[v10-18-15]]

^<<v10-18-15,15>>^ Dez jovens, que levavam as armas de Joabe, cercaram Absalão e acabaram de matá-lo.

[[v10-18-16]]

^<<v10-18-16,16>>^ Então Joabe tocou a trombeta, e o povo voltou de perseguir Israel, porque Joabe deteve o povo.

[[v10-18-17]]

^<<v10-18-17,17>>^ Levaram Absalão e o jogaram numa grande cova na floresta. E levantaram sobre ele um enorme monte de pedras. E todo o Israel fugiu, cada um para a sua casa.

[[v10-18-18]]

^<<v10-18-18,18>>^ Ora, quando ainda vivia, Absalão tinha levantado para si uma coluna, que está no vale do Rei, porque dizia: "Não tenho nenhum filho para conservar a memória do meu nome." E deu o seu próprio nome à coluna, que até hoje se chama o Monumento de Absalão.

[[v10-18-19]]

^<<v10-18-19,19>>^ Então Aimaás, filho de Zadoque, disse a Joabe: — Deixe que eu vá correndo dar ao rei a notícia de que o Senhor  Deus já o livrou das mãos de seus inimigos.

[[v10-18-20]]

^<<v10-18-20,20>>^ Mas Joabe lhe disse: — Hoje você não será o portador de boas notícias. Você poderá fazer isso outro dia, mas hoje não, porque está morto o filho do rei.

[[v10-18-21]]

^<<v10-18-21,21>>^ Então Joabe disse a um etíope: — Vá e diga ao rei o que você viu. Ele inclinou-se diante de Joabe e saiu correndo.

[[v10-18-22]]

^<<v10-18-22,22>>^ Porém Aimaás, filho de Zadoque, tornou a falar com Joabe: — Aconteça o que acontecer, deixe-me também correr atrás do etíope. Joabe perguntou: — Por que você quer correr, meu filho, se não terá recompensa pela notícia?

[[v10-18-23]]

^<<v10-18-23,23>>^ Aimaás respondeu: — Aconteça o que acontecer, vou correr. Então Joabe lhe disse: — Corra. Aimaás correu pelo caminho da planície e passou o etíope.

[[v10-18-24]]

^<<v10-18-24,24>>^ Davi estava sentado entre os dois portões da entrada da cidade. A sentinela subiu ao terraço do portão sobre a muralha e, levantando os olhos, viu que um homem vinha correndo sozinho.

[[v10-18-25]]

^<<v10-18-25,25>>^ A sentinela gritou e avisou o rei. O rei disse: — Se vem sozinho, traz boas notícias. E vinha andando e chegando.

[[v10-18-26]]

^<<v10-18-26,26>>^ Então a sentinela viu outro homem que corria e gritou para o porteiro: — Eis que vem outro homem correndo sozinho. Então o rei disse: — Também este traz boas notícias.

[[v10-18-27]]

^<<v10-18-27,27>>^ A sentinela continuou: — Vejo o jeito de correr do primeiro. Parece ser o jeito de correr de Aimaás, filho de Zadoque. Então o rei disse: — Este homem é de bem e trará boas notícias.

[[v10-18-28]]

^<<v10-18-28,28>>^ Aimaás gritou e disse ao rei: — Paz! Inclinou-se diante do rei com o rosto em terra e disse: — Bendito seja o Senhor , seu Deus, que nos entregou os homens que levantaram a mão contra o rei, meu senhor.

[[v10-18-29]]

^<<v10-18-29,29>>^ Então o rei perguntou: — Vai bem o jovem Absalão? Aimaás respondeu: — Vi um grande alvoroço, quando Joabe enviou este seu servo, ó rei, porém não sei o que era.

[[v10-18-30]]

^<<v10-18-30,30>>^ O rei disse: — Fique ali ao lado e espere. Ele ficou ao lado e esperou.

[[v10-18-31]]

^<<v10-18-31,31>>^ Então o etíope chegou e disse: — Boas notícias para o rei, meu senhor! Hoje o Senhor  Deus livrou o rei das mãos de todos os que se levantaram contra ele.

[[v10-18-32]]

^<<v10-18-32,32>>^ Então o rei perguntou ao etíope: — Vai bem o jovem Absalão? O etíope respondeu: — Que aquilo que aconteceu com aquele jovem aconteça com os inimigos do rei, meu senhor, e todos os que se levantam contra ele.

[[v10-18-33]]

^<<v10-18-33,33>>^ Então o rei, profundamente comovido, subiu à sala que estava por cima do portão e chorou. E, andando, dizia: — Meu filho Absalão, meu filho, meu filho Absalão! Quem me dera que eu tivesse morrido em seu lugar, Absalão, meu filho, meu filho!

'''

xref:010-2-samuel/010-2-samuel-017.adoc#v10-17-0[&#60; Capítulo Anterior] | <<v10-18-0,Topo>> | xref:010-2-samuel/010-2-samuel-019.adoc#v10-19-0[Próximo Capítulo &#62;]