include::./index.adoc[]

[[v10-13-0]]
=== 2 Samuel, 13
// naa ?, NAA - Nova Almeida Atualizada

[[v10-13-1]]

^<<v10-13-1,1>>^ Passado algum tempo, aconteceu o seguinte. Absalão, filho de Davi, tinha uma irmã muito bonita, cujo nome era Tamar. Amnom, filho de Davi, apaixonou-se por ela.

[[v10-13-2]]

^<<v10-13-2,2>>^ Amnom ficou angustiado por causa de Tamar, sua irmã, a ponto de adoecer, pois, sendo ela virgem, parecia impossível para ele fazer alguma coisa com ela.

[[v10-13-3]]

^<<v10-13-3,3>>^ Mas Amnom tinha um amigo que se chamava Jonadabe, filho de Simeia, irmão de Davi. Jonadabe era um homem muito esperto.

[[v10-13-4]]

^<<v10-13-4,4>>^ E ele disse a Amnom: — Por que você está emagrecendo tanto dia após dia, ó filho do rei? Por que não me conta o que está acontecendo? Então Amnom disse: — Estou apaixonado por Tamar, irmã de Absalão, meu irmão por parte de pai.

[[v10-13-5]]

^<<v10-13-5,5>>^ Jonadabe respondeu: — Deite-se na sua cama e finja que está doente. Quando o seu pai vier visitá-lo, diga-lhe: "Por favor, permita que a minha irmã Tamar venha e me dê de comer. Que ela prepare a comida diante de mim, para que eu coma de sua mão."

[[v10-13-6]]

^<<v10-13-6,6>>^ E assim Amnom deitou-se e fingiu que estava doente. Quando o rei foi visitá-lo, Amnom lhe disse: — Por favor, permita que a minha irmã Tamar venha e prepare dois bolos diante de mim, para que eu coma de sua mão.

[[v10-13-7]]

^<<v10-13-7,7>>^ Então Davi mandou dizer a Tamar em seu palácio: — Por favor, vá à casa de seu irmão Amnom e prepare alguma comida para ele.

[[v10-13-8]]

^<<v10-13-8,8>>^ Tamar foi à casa de Amnom, seu irmão, e ele estava deitado. Ela pegou a massa e a amassou, fez bolos diante dele e os assou.

[[v10-13-9]]

^<<v10-13-9,9>>^ Pegou a assadeira e tirou os bolos diante dele, mas ele não quis comer. Amnom disse: — Mandem que todos saiam da minha presença. E todos saíram.

[[v10-13-10]]

^<<v10-13-10,10>>^ E Amnom disse a Tamar: — Traga a comida ao meu quarto, e comerei da sua mão. Tamar pegou os bolos que havia feito e os levou a Amnom, seu irmão, no quarto.

[[v10-13-11]]

^<<v10-13-11,11>>^ Quando ela oferecia os bolos para que ele comesse, Amnom agarrou-a e lhe disse: — Venha, deite-se comigo, minha irmã.

[[v10-13-12]]

^<<v10-13-12,12>>^ Porém ela respondeu: — Não, meu irmão, não me force, porque não se faz uma coisa dessas em Israel. Não faça essa loucura!

[[v10-13-13]]

^<<v10-13-13,13>>^ Porque, aonde iria eu com a minha vergonha? E você seria como um dos loucos de Israel. Agora, por favor, fale com o rei; ele não impedirá que eu case com você.

[[v10-13-14]]

^<<v10-13-14,14>>^ Mas Amnom não quis dar ouvidos ao que Tamar dizia; pelo contrário, sendo mais forte do que ela, forçou-a e teve relações com ela.

[[v10-13-15]]

^<<v10-13-15,15>>^ Depois Amnom sentiu por ela grande aversão, e maior era a aversão que sentiu por ela do que o amor com que a tinha amado. Então disse: — Levante-se e saia daqui!

[[v10-13-16]]

^<<v10-13-16,16>>^ Mas Tamar respondeu: — Não, meu irmão! Porque mandar-me embora seria um mal maior do que o outro que você me fez. Porém ele não a quis ouvir.

[[v10-13-17]]

^<<v10-13-17,17>>^ Chamou o moço que o servia e lhe disse: — Ponha esta mulher para fora e tranque a porta.

[[v10-13-18]]

^<<v10-13-18,18>>^ Tamar vestia uma túnica talar de mangas compridas, porque assim se vestiam as filhas do rei que ainda eram virgens. O servo a pôs para fora e trancou a porta.

[[v10-13-19]]

^<<v10-13-19,19>>^ Então Tamar colocou cinza sobre a cabeça, rasgou a túnica talar de mangas compridas que vestia, pôs as mãos sobre a cabeça e saiu, andando e clamando.

[[v10-13-20]]

^<<v10-13-20,20>>^ Absalão, seu irmão, lhe disse: — Foi o seu irmão Amnom que esteve com você? Agora, minha irmã, fique calada; ele é seu irmão. Que o seu coração não fique angustiado por causa disso. E assim Tamar, desolada, ficou na casa de Absalão, seu irmão.

[[v10-13-21]]

^<<v10-13-21,21>>^ Quando o rei Davi soube de tudo isso, ficou furioso.

[[v10-13-22]]

^<<v10-13-22,22>>^ Porém Absalão não falou com Amnom nem mal nem bem, porque odiava Amnom, por ter este violentado Tamar, sua irmã.

[[v10-13-23]]

^<<v10-13-23,23>>^ Passados dois anos, Absalão tosquiava as suas ovelhas em Baal-Hazor, perto de Efraim, e convidou todos os filhos do rei para irem até lá.

[[v10-13-24]]

^<<v10-13-24,24>>^ Absalão foi falar com o rei e disse: — Eis que este seu servo está fazendo a tosquia das ovelhas. Peço que o rei e os seus servidores acompanhem este seu servo.

[[v10-13-25]]

^<<v10-13-25,25>>^ O rei, porém, disse a Absalão: — Não, meu filho, não vamos todos juntos, para não sermos pesados a você. Absalão insistiu, mas o rei não quis ir; contudo, o abençoou.

[[v10-13-26]]

^<<v10-13-26,26>>^ Então Absalão disse: — Se o rei não quer ir, pelo menos deixe que meu irmão Amnom nos acompanhe. Porém o rei lhe disse: — Por que ele iria com você?

[[v10-13-27]]

^<<v10-13-27,27>>^ Absalão insistiu, e o rei deixou que Amnom e todos os filhos do rei fossem com ele.

[[v10-13-28]]

^<<v10-13-28,28>>^ Absalão deu ordem aos seus moços, dizendo: — Fiquem atentos! Quando o coração de Amnom estiver alegre de vinho, e eu der uma ordem para matá-lo, então matem-no. Não tenham medo, pois sou eu quem está ordenando. Sejam fortes e valentes.

[[v10-13-29]]

^<<v10-13-29,29>>^ E os moços de Absalão fizeram com Amnom como Absalão lhes havia ordenado. Então todos os filhos do rei se levantaram, cada um montou a sua mula, e fugiram.

[[v10-13-30]]

^<<v10-13-30,30>>^ Estavam eles ainda a caminho, quando chegou a Davi esta notícia: "Absalão matou todos os filhos do rei, e nenhum deles escapou."

[[v10-13-31]]

^<<v10-13-31,31>>^ Então o rei se levantou, rasgou as suas roupas e se lançou por terra. E todos os seus servos que estavam presentes rasgaram também as suas roupas.

[[v10-13-32]]

^<<v10-13-32,32>>^ Mas Jonadabe, filho de Simeia, irmão de Davi, tomou a palavra e disse: — Não pense o meu senhor que mataram todos os jovens, filhos do rei, porque somente Amnom morreu. Absalão tinha resolvido fazer isso, desde o dia em que a sua irmã Tamar foi violentada por Amnom.

[[v10-13-33]]

^<<v10-13-33,33>>^ Portanto, que o rei, meu senhor, não ponha na cabeça essa ideia de que todos os filhos do rei morreram, porque só Amnom morreu.

[[v10-13-34]]

^<<v10-13-34,34>>^ Enquanto isso, Absalão fugiu. O moço que estava de guarda, levantando os olhos, viu que vinha muito povo pelo caminho por detrás dele, pelo lado do monte.

[[v10-13-35]]

^<<v10-13-35,35>>^ Então Jonadabe disse ao rei: — Eis aí vêm os filhos do rei! Como este seu servo falou, assim aconteceu.

[[v10-13-36]]

^<<v10-13-36,36>>^ Mal tinha ele acabado de falar, chegaram os filhos do rei e, levantando a voz, choraram. Também o rei e todos os seus servos choraram amargamente.

[[v10-13-37]]

^<<v10-13-37,37>>^ Absalão, porém, fugiu e foi ficar com Talmai, filho de Amiúde, rei de Gesur. E Davi pranteava por seu filho todos os dias.

[[v10-13-38]]

^<<v10-13-38,38>>^ Assim, Absalão fugiu, indo para Gesur, onde ficou três anos.

[[v10-13-39]]

^<<v10-13-39,39>>^ Então o rei Davi cessou de perseguir Absalão, porque já tinha se consolado a respeito de Amnom, que era morto.

'''

xref:010-2-samuel/010-2-samuel-012.adoc#v10-12-0[&#60; Capítulo Anterior] | <<v10-13-0,Topo>> | xref:010-2-samuel/010-2-samuel-014.adoc#v10-14-0[Próximo Capítulo &#62;]