include::./index.adoc[]

[[v10-2-0]]
=== 2 Samuel, 2
// naa ?, NAA - Nova Almeida Atualizada

[[v10-2-1]]

^<<v10-2-1,1>>^ Depois disto, Davi consultou o Senhor , dizendo: — Devo ir a alguma das cidades de Judá? E o Senhor  respondeu: — Vá, sim. Davi perguntou: — Para onde devo ir? O Senhor  respondeu: — Para Hebrom.

[[v10-2-2]]

^<<v10-2-2,2>>^ Davi foi para lá, levando consigo as suas duas mulheres, Ainoã, a jezreelita, e Abigail, a viúva de Nabal, o carmelita.

[[v10-2-3]]

^<<v10-2-3,3>>^ Davi levou também os homens que estavam com ele, cada um com a sua família, e eles ficaram morando nas aldeias de Hebrom.

[[v10-2-4]]

^<<v10-2-4,4>>^ Então vieram os homens de Judá e ali ungiram Davi rei sobre a casa de Judá. E informaram a Davi que os homens de Jabes-Gileade tinham sepultado Saul.

[[v10-2-5]]

^<<v10-2-5,5>>^ Então Davi enviou mensageiros aos homens de Jabes-Gileade para dizer-lhes: — Benditos do Senhor  sejam vocês, por este ato de bondade para com o seu senhor, para com Saul, pois vocês o sepultaram!

[[v10-2-6]]

^<<v10-2-6,6>>^ E agora que o Senhor  use de misericórdia e fidelidade para com vocês. E eu também os tratarei bem por causa do que vocês fizeram.

[[v10-2-7]]

^<<v10-2-7,7>>^ E agora sejam fortes e valentes, porque Saul, o senhor de vocês, está morto, e os da casa de Judá me ungiram para ser o seu rei.

[[v10-2-8]]

^<<v10-2-8,8>>^ Abner, filho de Ner, capitão do exército de Saul, levou Isbosete, filho de Saul, para Maanaim,

[[v10-2-9]]

^<<v10-2-9,9>>^ e o constituiu rei sobre Gileade, sobre os assuritas, sobre Jezreel, Efraim, Benjamim e sobre todo o Israel.

[[v10-2-10]]

^<<v10-2-10,10>>^ Isbosete, filho de Saul, tinha quarenta anos de idade quando começou a reinar sobre Israel, e reinou dois anos. Somente a casa de Judá seguia Davi.

[[v10-2-11]]

^<<v10-2-11,11>>^ O tempo que Davi reinou em Hebrom sobre a casa de Judá foram sete anos e seis meses.

[[v10-2-12]]

^<<v10-2-12,12>>^ Abner, filho de Ner, e os homens de Isbosete, filho de Saul, saíram de Maanaim e foram para Gibeão.

[[v10-2-13]]

^<<v10-2-13,13>>^ Joabe, filho de Zeruia, e os servos de Davi também saíram, e os dois grupos se encontraram perto da cisterna de Gibeão. Um grupo parou do lado de cá da cisterna, e o outro, do lado de lá.

[[v10-2-14]]

^<<v10-2-14,14>>^ Então Abner disse a Joabe: — Que os moços se levantem e lutem diante de nós. Joabe respondeu: — Está bem!

[[v10-2-15]]

^<<v10-2-15,15>>^ Então se levantaram e avançaram em igual número: doze de Benjamim, da parte de Isbosete, filho de Saul, e doze dos homens de Davi.

[[v10-2-16]]

^<<v10-2-16,16>>^ Cada um pegou o seu adversário pela cabeça, meteu-lhe a espada no lado, e caíram mortos juntos. Por isso aquele lugar foi chamado de Campo das Espadas. Fica perto de Gibeão.

[[v10-2-17]]

^<<v10-2-17,17>>^ Houve um combate intenso naquele dia, e Abner e os homens de Israel foram derrotados pelos homens de Davi.

[[v10-2-18]]

^<<v10-2-18,18>>^ Estavam ali os três filhos de Zeruia: Joabe, Abisai e Asael. Asael, que era ligeiro como uma gazela selvagem,

[[v10-2-19]]

^<<v10-2-19,19>>^ perseguiu Abner e, na sua perseguição, não se desviou nem para a direita nem para a esquerda.

[[v10-2-20]]

^<<v10-2-20,20>>^ Então Abner olhou para trás e perguntou: — É você, Asael? Ele respondeu: — Sou eu mesmo.

[[v10-2-21]]

^<<v10-2-21,21>>^ Então Abner disse: — Desvie-se para a direita ou para a esquerda, agarre um dos soldados e pegue a armadura dele. Porém Asael não desistiu de perseguir Abner.

[[v10-2-22]]

^<<v10-2-22,22>>^ Então Abner disse mais uma vez: — Pare de me perseguir! Do contrário, vou ter de matá-lo. E, depois, como poderia eu olhar no rosto de seu irmão Joabe?

[[v10-2-23]]

^<<v10-2-23,23>>^ Como Asael não quis deixar de persegui-lo, Abner o feriu na barriga com a extremidade inferior da lança, que lhe saiu pelas costas. Asael caiu e morreu ali mesmo. Todos os que chegavam ao lugar em que Asael tinha caído morto paravam.

[[v10-2-24]]

^<<v10-2-24,24>>^ Porém Joabe e Abisai perseguiram Abner. O sol se pôs quando eles chegaram à colina de Amá, que está em frente de Giá, no caminho do deserto de Gibeão.

[[v10-2-25]]

^<<v10-2-25,25>>^ Os filhos de Benjamim se reuniram em volta de Abner, formando uma só tropa, e se puseram no alto de uma colina.

[[v10-2-26]]

^<<v10-2-26,26>>^ Então Abner gritou para Joabe: — Será que a espada vai consumir para sempre? Você não sabe que serão amargas as suas consequências? Até quando você vai esperar para ordenar ao povo que deixe de perseguir os seus irmãos?

[[v10-2-27]]

^<<v10-2-27,27>>^ Joabe respondeu: — Tão certo como vive Deus, se você não tivesse falado, só amanhã cedo o povo cessaria de perseguir cada um o seu irmão.

[[v10-2-28]]

^<<v10-2-28,28>>^ Então Joabe tocou a trombeta, e todo o povo parou, e eles não perseguiram mais Israel e a luta acabou.

[[v10-2-29]]

^<<v10-2-29,29>>^ Abner e seus homens marcharam toda aquela noite pela planície. Passaram o Jordão e, caminhando toda a manhã, chegaram a Maanaim.

[[v10-2-30]]

^<<v10-2-30,30>>^ Joabe deixou de perseguir Abner. E, tendo reunido todo o povo, verificou que faltavam dezenove dos homens de Davi, além de Asael.

[[v10-2-31]]

^<<v10-2-31,31>>^ Porém os servos de Davi tinham matado, dentre os de Benjamim e dentre os soldados de Abner, trezentos e sessenta homens.

[[v10-2-32]]

^<<v10-2-32,32>>^ Levaram Asael e o sepultaram no túmulo de seu pai, em Belém. Joabe e seus homens caminharam toda aquela noite, e, ao amanhecer, chegaram a Hebrom.

'''

xref:010-2-samuel/010-2-samuel-001.adoc#v10-1-0[&#60; Capítulo Anterior] | <<v10-2-0,Topo>> | xref:010-2-samuel/010-2-samuel-003.adoc#v10-3-0[Próximo Capítulo &#62;]