include::./index.adoc[]

[[v10-22-0]]
=== 2 Samuel, 22
// naa ?, NAA - Nova Almeida Atualizada

[[v10-22-1]]

^<<v10-22-1,1>>^ Davi falou ao Senhor  as palavras deste cântico, no dia em que o Senhor  o livrou das mãos de todos os seus inimigos e das mãos de Saul.

[[v10-22-2]]

^<<v10-22-2,2>>^ Ele disse: O Senhor  é a minha rocha, a minha fortaleza, o meu libertador;

[[v10-22-3]]

^<<v10-22-3,3>>^ o meu Deus, o meu rochedo em que me refugio; o meu escudo, a força da minha salvação, o meu alto refúgio. Ó Deus, tu me salvas da violência.

[[v10-22-4]]

^<<v10-22-4,4>>^ Invoco o Senhor , digno de ser louvado, e serei salvo dos meus inimigos.

[[v10-22-5]]

^<<v10-22-5,5>>^ Porque ondas de morte me cercaram, torrentes de perdição me impuseram terror.

[[v10-22-6]]

^<<v10-22-6,6>>^ Cadeias infernais me envolveram, e tramas de morte me surpreenderam.

[[v10-22-7]]

^<<v10-22-7,7>>^ Na minha angústia, invoquei o Senhor ; gritei por socorro ao meu Deus. Do seu templo ele ouviu a minha voz, e o meu clamor chegou aos seus ouvidos.

[[v10-22-8]]

^<<v10-22-8,8>>^ Então a terra se abalou e tremeu; vacilaram também os fundamentos dos céus e se abalaram, porque ele estava irado.

[[v10-22-9]]

^<<v10-22-9,9>>^ Das suas narinas subiu fumaça, e fogo devorador saiu da sua boca; dele saíram brasas ardentes.

[[v10-22-10]]

^<<v10-22-10,10>>^ Ele baixou os céus e desceu, e teve sob os pés densa escuridão.

[[v10-22-11]]

^<<v10-22-11,11>>^ Cavalgava um querubim e voou; foi levado sobre as asas do vento.

[[v10-22-12]]

^<<v10-22-12,12>>^ Por abrigo pôs ao redor de si trevas, ajuntamento de águas, nuvens dos céus.

[[v10-22-13]]

^<<v10-22-13,13>>^ Do resplendor que diante dele havia, brasas de fogo se acenderam.

[[v10-22-14]]

^<<v10-22-14,14>>^ O Senhor  trovejou desde os céus; o Altíssimo levantou a sua voz.

[[v10-22-15]]

^<<v10-22-15,15>>^ Atirou as suas flechas e espalhou os meus inimigos; multiplicou os seus raios e os dispersou.

[[v10-22-16]]

^<<v10-22-16,16>>^ Então se viu o leito do mar, e se descobriram os fundamentos do mundo, pela repreensão do Senhor , pelo sopro irado das suas narinas.

[[v10-22-17]]

^<<v10-22-17,17>>^ Do alto o Senhor  me estendeu a mão e me segurou; ele me tirou das águas profundas.

[[v10-22-18]]

^<<v10-22-18,18>>^ Livrou-me de forte inimigo e dos que me odiavam, pois eram mais poderosos do que eu.

[[v10-22-19]]

^<<v10-22-19,19>>^ Eles me atacaram no dia da minha calamidade, mas o Senhor  me serviu de amparo.

[[v10-22-20]]

^<<v10-22-20,20>>^ Trouxe-me para um lugar espaçoso; livrou-me, porque ele se agradou de mim.

[[v10-22-21]]

^<<v10-22-21,21>>^ O Senhor  me retribuiu segundo a minha justiça; recompensou-me conforme a pureza das minhas mãos.

[[v10-22-22]]

^<<v10-22-22,22>>^ Pois tenho guardado os caminhos do Senhor e não me afastei perversamente do meu Deus.

[[v10-22-23]]

^<<v10-22-23,23>>^ Porque todos os seus juízos estão diante de mim, e não rejeitei os seus preceitos.

[[v10-22-24]]

^<<v10-22-24,24>>^ Também fui íntegro para com ele e me guardei da iniquidade.

[[v10-22-25]]

^<<v10-22-25,25>>^ Por isso, o Senhor  me retribuiu segundo a minha justiça, conforme a minha pureza, na sua presença.

[[v10-22-26]]

^<<v10-22-26,26>>^ Para com quem é fiel, fiel te mostras; com o íntegro, também íntegro.

[[v10-22-27]]

^<<v10-22-27,27>>^ Com o puro, puro te mostras; com o perverso, inflexível.

[[v10-22-28]]

^<<v10-22-28,28>>^ Tu salvas o povo humilde, mas, com um lance de vista, abates os orgulhosos.

[[v10-22-29]]

^<<v10-22-29,29>>^ Tu, Senhor , és a minha lâmpada; o Senhor  derrama luz nas minhas trevas.

[[v10-22-30]]

^<<v10-22-30,30>>^ Pois contigo posso atacar exércitos, com o meu Deus salto muralhas.

[[v10-22-31]]

^<<v10-22-31,31>>^ O caminho de Deus é perfeito; a palavra do Senhor  é confiável; ele é escudo para todos os que nele se refugiam.

[[v10-22-32]]

^<<v10-22-32,32>>^ Pois quem é Deus além do Senhor ? E quem é rochedo, a não ser o nosso Deus?

[[v10-22-33]]

^<<v10-22-33,33>>^ Deus é a minha fortaleza e a minha força e ele aperfeiçoa o meu caminho.

[[v10-22-34]]

^<<v10-22-34,34>>^ Ele deu aos meus pés a ligeireza das corças e me firmou nas minhas alturas.

[[v10-22-35]]

^<<v10-22-35,35>>^ Ele treinou as minhas mãos para o combate, tanto que os meus braços vergaram um arco de bronze.

[[v10-22-36]]

^<<v10-22-36,36>>^ Também me deste o escudo da tua salvação, e a tua clemência me engrandeceu.

[[v10-22-37]]

^<<v10-22-37,37>>^ Alargaste o caminho sob meus passos, e os meus pés não vacilaram.

[[v10-22-38]]

^<<v10-22-38,38>>^ Persegui os meus inimigos e os derrotei, e só voltei depois de ter acabado com eles.

[[v10-22-39]]

^<<v10-22-39,39>>^ Acabei com eles, esmagando-os a tal ponto, que não puderam se levantar; caíram sob os meus pés.

[[v10-22-40]]

^<<v10-22-40,40>>^ Pois me cingiste de força para o combate e me submeteste os que se levantaram contra mim.

[[v10-22-41]]

^<<v10-22-41,41>>^ Também puseste em fuga os meus inimigos, e os que me odiavam, eu os exterminei.

[[v10-22-42]]

^<<v10-22-42,42>>^ Olharam, mas não houve quem os salvasse; olharam para o Senhor , mas ele não respondeu.

[[v10-22-43]]

^<<v10-22-43,43>>^ Então os moí como o pó da terra; esmaguei-os e, como a lama das ruas, os amassei.

[[v10-22-44]]

^<<v10-22-44,44>>^ Dos conflitos do meu povo me livraste e me fizeste cabeça das nações; um povo que eu não conhecia me serviu.

[[v10-22-45]]

^<<v10-22-45,45>>^ Os estrangeiros se mostram submissos a mim; bastou-lhes ouvir a minha voz, logo me obedeceram.

[[v10-22-46]]

^<<v10-22-46,46>>^ Os estrangeiros fraquejaram e, tremendo, saíram das suas fortalezas.

[[v10-22-47]]

^<<v10-22-47,47>>^ O Senhor  vive! Bendita seja a minha rocha! Exaltado seja o meu Deus, a rocha da minha salvação!

[[v10-22-48]]

^<<v10-22-48,48>>^ O Deus que por mim tomou vingança e me submeteu povos;

[[v10-22-49]]

^<<v10-22-49,49>>^ o Deus que me tirou do meio dos meus inimigos; sim, tu que me exaltaste acima dos meus adversários e me livraste dos homens violentos.

[[v10-22-50]]

^<<v10-22-50,50>>^ Por isso, eu te glorificarei entre os gentios, ó Senhor , e cantarei louvores ao teu nome.

[[v10-22-51]]

^<<v10-22-51,51>>^ É ele quem dá grandes vitórias ao seu rei e usa de misericórdia para com o seu ungido, com Davi e sua posteridade, para sempre.

'''

xref:010-2-samuel/010-2-samuel-021.adoc#v10-21-0[&#60; Capítulo Anterior] | <<v10-22-0,Topo>> | xref:010-2-samuel/010-2-samuel-023.adoc#v10-23-0[Próximo Capítulo &#62;]