include::./index.adoc[]

[[v10-21-0]]
=== 2 Samuel, 21
// naa ?, NAA - Nova Almeida Atualizada

[[v10-21-1]]

^<<v10-21-1,1>>^ Nos dias do rei Davi houve uma fome de três anos consecutivos. Davi consultou o Senhor , e o Senhor  lhe disse: — É por causa de Saul e de sua família sanguinária, porque ele matou os gibeonitas.

[[v10-21-2]]

^<<v10-21-2,2>>^ Então o rei chamou os gibeonitas e falou com eles. Os gibeonitas não eram dos filhos de Israel, mas do resto dos amorreus. Os filhos de Israel lhes tinham jurado poupá-los, porém Saul procurou destruí-los no seu zelo pelos filhos de Israel e de Judá.

[[v10-21-3]]

^<<v10-21-3,3>>^ Davi perguntou aos gibeonitas: — O que vocês querem que eu faça por vocês? E que resgate lhes darei, para que abençoem a herança do Senhor ?

[[v10-21-4]]

^<<v10-21-4,4>>^ Os gibeonitas responderam: — A nossa questão com Saul e com a sua casa não tem nada a ver com prata nem com ouro. Também não pretendemos matar pessoa alguma em Israel. Então Davi disse: — O que vocês disserem, isso farei por vocês.

[[v10-21-5]]

^<<v10-21-5,5>>^ Eles responderam ao rei: — Quanto ao homem que nos destruiu e procurou que fôssemos exterminados, sem que pudéssemos subsistir dentro das fronteiras de Israel,

[[v10-21-6]]

^<<v10-21-6,6>>^ que nos sejam dados sete homens dos seus descendentes, para que os enforquemos diante do Senhor , em Gibeá de Saul, o eleito do Senhor . E o rei disse: — Eu vou dar.

[[v10-21-7]]

^<<v10-21-7,7>>^ Mas o rei poupou Mefibosete, filho de Jônatas, filho de Saul, por causa do juramento ao Senhor  feito entre Davi e Jônatas, filho de Saul.

[[v10-21-8]]

^<<v10-21-8,8>>^ Porém o rei pegou os dois filhos que Rispa, filha de Aiá, tinha tido de Saul, a saber, Armoni e Mefibosete. Pegou também os cinco filhos que Merabe, filha de Saul, tinha tido de Adriel, filho de Barzilai, meolatita.

[[v10-21-9]]

^<<v10-21-9,9>>^ Davi os entregou nas mãos dos gibeonitas, que os enforcaram no monte, diante do Senhor , e os sete morreram ao mesmo tempo. Foram mortos nos dias da colheita, nos primeiros dias, no princípio da colheita da cevada.

[[v10-21-10]]

^<<v10-21-10,10>>^ Então Rispa, filha de Aiá, pegou um pano de saco e o estendeu para si sobre uma rocha, desde o princípio da colheita até que caiu água do céu sobre os corpos. E não deixou que as aves do céu se aproximassem deles de dia, nem os animais do campo, de noite.

[[v10-21-11]]

^<<v10-21-11,11>>^ Contaram a Davi o que Rispa, filha de Aiá e concubina de Saul, havia feito.

[[v10-21-12]]

^<<v10-21-12,12>>^ Então Davi foi e tomou os ossos de Saul e os ossos de Jônatas, seu filho, dos moradores de Jabes-Gileade, os quais os furtaram da praça de Bete-Seã, onde os filisteus os tinham pendurado, no dia em que mataram Saul em Gilboa.

[[v10-21-13]]

^<<v10-21-13,13>>^ Dali, transportou os ossos de Saul e os ossos de Jônatas, seu filho; e ajuntaram também os ossos dos enforcados.

[[v10-21-14]]

^<<v10-21-14,14>>^ Sepultaram os ossos de Saul e de Jônatas, seu filho, na terra de Benjamim, em Zela, no túmulo de Quis, seu pai. Fizeram tudo o que o rei havia ordenado. Depois disto, Deus se tornou favorável para com a terra.

[[v10-21-15]]

^<<v10-21-15,15>>^ De novo, os filisteus fizeram guerra contra Israel. Davi foi com os seus soldados, e lutaram contra os filisteus. E Davi ficou muito cansado.

[[v10-21-16]]

^<<v10-21-16,16>>^ Isbi-Benobe descendia dos gigantes. O peso do bronze de sua lança era de quase quatro quilos, e estava cingido de uma armadura nova. Este disse que mataria Davi.

[[v10-21-17]]

^<<v10-21-17,17>>^ Porém Abisai, filho de Zeruia, socorreu Davi, atacou o filisteu e o matou. Então os homens de Davi lhe juraram, dizendo: — Nunca mais o senhor sairá conosco à batalha, para que a lâmpada de Israel não se apague.

[[v10-21-18]]

^<<v10-21-18,18>>^ Depois disto houve ainda, em Gobe, outra batalha contra os filisteus. Foi então que Sibecai, o husatita, matou Safe, que era descendente dos gigantes.

[[v10-21-19]]

^<<v10-21-19,19>>^ Houve ainda, em Gobe, outra batalha contra os filisteus, e Elanã, filho de Jaaré-Oregim, o belemita, matou Golias, o geteu, cuja lança tinha a haste como eixo de tecelão.

[[v10-21-20]]

^<<v10-21-20,20>>^ Houve ainda outra batalha em Gate. Ali havia um homem de grande estatura, que tinha seis dedos em cada mão e em cada pé, vinte e quatro ao todo; também este descendia dos gigantes.

[[v10-21-21]]

^<<v10-21-21,21>>^ Quando ele insultou Israel, Jônatas, filho de Simeia, irmão de Davi, o matou.

[[v10-21-22]]

^<<v10-21-22,22>>^ Esses quatro eram descendentes dos gigantes em Gate, e foram mortos por Davi e seus soldados.

'''

xref:010-2-samuel/010-2-samuel-020.adoc#v10-20-0[&#60; Capítulo Anterior] | <<v10-21-0,Topo>> | xref:010-2-samuel/010-2-samuel-022.adoc#v10-22-0[Próximo Capítulo &#62;]