include::./index.adoc[]

[[v10-9-0]]
=== 2 Samuel, 9
// naa ?, NAA - Nova Almeida Atualizada

[[v10-9-1]]

^<<v10-9-1,1>>^ Um dia Davi perguntou: — Será que resta ainda alguém da família de Saul, para que eu use de bondade para com ele, por causa de Jônatas?

[[v10-9-2]]

^<<v10-9-2,2>>^ Havia um servo na casa de Saul cujo nome era Ziba. Chamaram-no, pedindo que viesse falar com Davi. O rei perguntou: — Você é Ziba? Ele respondeu: — Sou eu mesmo, seu servo.

[[v10-9-3]]

^<<v10-9-3,3>>^ Então Davi perguntou: — Existe mais alguém da família de Saul para que eu use da bondade de Deus para com ele? Ziba respondeu: — Ainda existe um filho de Jônatas, aleijado de ambos os pés. Então o rei perguntou:

[[v10-9-4]]

^<<v10-9-4,4>>^ — E onde está ele? Ziba respondeu: — Ele está na casa de Maquir, filho de Amiel, em Lo-Debar.

[[v10-9-5]]

^<<v10-9-5,5>>^ Então o rei Davi mandou trazê-lo de Lo-Debar, da casa de Maquir, filho de Amiel.

[[v10-9-6]]

^<<v10-9-6,6>>^ Quando Mefibosete, filho de Jônatas, filho de Saul, chegou diante de Davi, inclinou-se, prostrando-se com o rosto em terra. Davi disse: — Mefibosete! Ele respondeu: — Aqui estou. Às suas ordens!

[[v10-9-7]]

^<<v10-9-7,7>>^ Então Davi lhe disse: — Não tenha medo, porque serei bondoso com você por causa de Jônatas, seu pai. Vou restituir a você todas as terras de Saul, seu pai, e você sentará sempre à minha mesa para comer.

[[v10-9-8]]

^<<v10-9-8,8>>^ Então Mefibosete se inclinou e disse: — Quem é este seu servo, para que o meu senhor tenha olhado para um cão morto como eu?

[[v10-9-9]]

^<<v10-9-9,9>>^ Então Davi chamou Ziba, servo de Saul, e lhe disse: — Tudo o que pertencia a Saul e a toda a casa dele eu dei ao neto de seu senhor.

[[v10-9-10]]

^<<v10-9-10,10>>^ Você, os seus filhos e os seus servos cultivarão a terra para ele e recolherão os frutos, para que a casa de seu senhor tenha o que comer. Porém Mefibosete, neto de seu senhor, sentará sempre à minha mesa para comer. Ziba tinha quinze filhos e vinte servos.

[[v10-9-11]]

^<<v10-9-11,11>>^ Ziba disse ao rei: — Farei tudo o que o rei, meu senhor, ordena a este seu servo. E assim Mefibosete passou a fazer as refeições à mesa de Davi, como um dos filhos do rei.

[[v10-9-12]]

^<<v10-9-12,12>>^ Mefibosete tinha um filho pequeno chamado Mica. Todos os que moravam na casa de Ziba eram servos de Mefibosete.

[[v10-9-13]]

^<<v10-9-13,13>>^ Mefibosete morava em Jerusalém, porque fazia as refeições sempre à mesa do rei. Ele era coxo de ambos os pés.

'''

xref:010-2-samuel/010-2-samuel-008.adoc#v10-8-0[&#60; Capítulo Anterior] | <<v10-9-0,Topo>> | xref:010-2-samuel/010-2-samuel-010.adoc#v10-10-0[Próximo Capítulo &#62;]