include::./index.adoc[]

[[v10-3-0]]
=== 2 Samuel, 3
// naa ?, NAA - Nova Almeida Atualizada

[[v10-3-1]]

^<<v10-3-1,1>>^ Durou muito tempo a guerra entre a casa de Saul e a casa de Davi. Davi se fortalecia cada vez mais, enquanto a casa de Saul se enfraquecia.

[[v10-3-2]]

^<<v10-3-2,2>>^ Em Hebrom, nasceram filhos a Davi. O primogênito foi Amnom, de Ainoã, a jezreelita.

[[v10-3-3]]

^<<v10-3-3,3>>^ O segundo foi Quileabe, de Abigail, viúva de Nabal, o carmelita. O terceiro foi Absalão, filho de Maaca, filha de Talmai, rei de Gesur.

[[v10-3-4]]

^<<v10-3-4,4>>^ O quarto foi Adonias, filho de Hagite. O quinto foi Sefatias, filho de Abital.

[[v10-3-5]]

^<<v10-3-5,5>>^ O sexto foi Itreão, de Eglá, mulher de Davi. Estes filhos de Davi nasceram em Hebrom.

[[v10-3-6]]

^<<v10-3-6,6>>^ Enquanto durou a guerra entre a casa de Saul e a casa de Davi, Abner se tornava cada vez mais poderoso na casa de Saul.

[[v10-3-7]]

^<<v10-3-7,7>>^ Saul teve uma concubina chamada Rispa, filha de Aiá. Isbosete perguntou a Abner: — Por que você teve relações com a concubina de meu pai?

[[v10-3-8]]

^<<v10-3-8,8>>^ Abner ficou indignado com as palavras de Isbosete e disse: — Sou eu um cão a serviço de Judá? Ainda hoje sou fiel à casa de Saul, seu pai, e aos irmãos e amigos dele e não entreguei você nas mãos de Davi. No entanto, hoje você quer me culpar por causa dessa mulher!

[[v10-3-9]]

^<<v10-3-9,9>>^ Que Deus me castigue se eu não fizer por Davi o que o Senhor  lhe prometeu,

[[v10-3-10]]

^<<v10-3-10,10>>^ transferindo o reino da casa de Saul e estabelecendo o trono de Davi sobre Israel e sobre Judá, desde Dã até Berseba.

[[v10-3-11]]

^<<v10-3-11,11>>^ E Isbosete não pôde dizer nada a Abner, porque tinha medo dele.

[[v10-3-12]]

^<<v10-3-12,12>>^ Então Abner enviou mensageiros a Davi, dizendo: — De quem é a terra? Faça uma aliança comigo, e eu o ajudarei a fazer com que todo o Israel se junte a você.

[[v10-3-13]]

^<<v10-3-13,13>>^ Davi respondeu: — Muito bem. Farei uma aliança com você, porém uma coisa exijo: quando vier falar comigo, você não verá a minha face, se primeiro não me trouxer Mical, filha de Saul.

[[v10-3-14]]

^<<v10-3-14,14>>^ Davi também enviou mensageiros a Isbosete, filho de Saul, dizendo: — Dê-me de volta a minha mulher Mical. Para poder casar com ela dei como pagamento cem prepúcios de filisteus.

[[v10-3-15]]

^<<v10-3-15,15>>^ Então Isbosete mandou tirá-la do seu marido Paltiel, filho de Laís.

[[v10-3-16]]

^<<v10-3-16,16>>^ Seu marido a acompanhou, caminhando e chorando atrás dela, até Baurim. Então Abner disse a ele: — Agora vá e volte para casa. E ele voltou.

[[v10-3-17]]

^<<v10-3-17,17>>^ Abner falou com os anciãos de Israel, dizendo: — No passado, vocês queriam que Davi reinasse sobre vocês.

[[v10-3-18]]

^<<v10-3-18,18>>^ Façam isto agora, porque o Senhor  falou a Davi, dizendo: "Por meio de Davi, meu servo, livrarei o meu povo das mãos dos filisteus e das mãos de todos os seus inimigos."

[[v10-3-19]]

^<<v10-3-19,19>>^ Abner falou também com a tribo de Benjamim. E então ele foi dizer a Davi, em Hebrom, tudo o que agradava a Israel e a toda a casa de Benjamim.

[[v10-3-20]]

^<<v10-3-20,20>>^ Abner foi falar com Davi, em Hebrom, e vinte homens estavam com ele. Davi ofereceu um banquete a Abner e aos homens que tinham vindo com ele.

[[v10-3-21]]

^<<v10-3-21,21>>^ Então Abner disse a Davi: — Eu me levantarei e irei para ajuntar todo o Israel ao rei, meu senhor, para fazerem aliança com o rei. E meu senhor reinará sobre tudo o que quiser. Então Davi deixou que Abner partisse, e ele se foi em paz.

[[v10-3-22]]

^<<v10-3-22,22>>^ Eis que os servos de Davi e Joabe vieram de uma investida e traziam consigo grande despojo. Mas Abner já não estava com Davi, em Hebrom, porque este o havia deixado ir embora, e ele tinha ido em paz.

[[v10-3-23]]

^<<v10-3-23,23>>^ Quando Joabe chegou com toda a tropa que estava com ele, disseram-lhe: — Abner, filho de Ner, veio falar com o rei, que deixou que ele fosse embora em paz.

[[v10-3-24]]

^<<v10-3-24,24>>^ Então Joabe foi falar com o rei e lhe disse: — O que foi que o senhor fez? Eis que Abner esteve aqui e o senhor o deixou ir embora. Agora ele se foi!

[[v10-3-25]]

^<<v10-3-25,25>>^ O senhor bem conhece Abner, filho de Ner. Veio para enganá-lo, para observar os seus movimentos e sondar todos os seus planos.

[[v10-3-26]]

^<<v10-3-26,26>>^ Ao sair da presença de Davi, Joabe enviou mensageiros atrás de Abner, e eles o trouxeram de volta desde a cisterna de Sirá, sem que Davi o soubesse.

[[v10-3-27]]

^<<v10-3-27,27>>^ Quando Abner voltou a Hebrom, Joabe o levou para um lado, no interior do portão da cidade, para lhe falar em segredo, e ali o feriu na barriga. E assim Abner morreu, por ter derramado o sangue de Asael, irmão de Joabe.

[[v10-3-28]]

^<<v10-3-28,28>>^ Depois, quando Davi ficou sabendo, disse: — Eu e o meu reino somos inocentes diante do Senhor , para sempre, do sangue de Abner, filho de Ner.

[[v10-3-29]]

^<<v10-3-29,29>>^ Que este sangue caia sobre a cabeça de Joabe e sobre toda a casa de seu pai! Que nunca falte na casa de Joabe quem tenha corrimento, quem seja leproso, quem se apoie em muleta, quem caia à espada, quem necessite de pão.

[[v10-3-30]]

^<<v10-3-30,30>>^ Assim, Joabe e seu irmão Abisai mataram Abner, porque este tinha matado Asael, o irmão deles, na batalha de Gibeão.

[[v10-3-31]]

^<<v10-3-31,31>>^ Então Davi disse a Joabe e a todo o povo que estava com ele: — Rasguem as suas roupas, vistam-se de panos de saco e façam lamentação por Abner. E o próprio rei Davi ia seguindo o caixão.

[[v10-3-32]]

^<<v10-3-32,32>>^ Sepultaram Abner em Hebrom. O rei levantou a voz e chorou junto à sepultura de Abner. E todo o povo também chorou.

[[v10-3-33]]

^<<v10-3-33,33>>^ E o rei fez a seguinte lamentação por Abner: Por que Abner teve de morrer como se fosse um tolo?

[[v10-3-34]]

^<<v10-3-34,34>>^ As suas mãos não estavam atadas, nem estavam acorrentados os seus pés. Você caiu como quem cai diante dos filhos da maldade! E todo o povo chorou muito mais por ele.

[[v10-3-35]]

^<<v10-3-35,35>>^ Então todo o povo veio fazer com que Davi comesse pão, sendo ainda dia. Mas Davi fez este juramento: — Que Deus me castigue severamente se eu provar pão ou qualquer outra coisa antes que o sol se ponha.

[[v10-3-36]]

^<<v10-3-36,36>>^ Todo o povo notou isso e aprovou essa atitude, assim como aprovava tudo o que o rei fazia.

[[v10-3-37]]

^<<v10-3-37,37>>^ Naquele dia, todo o povo e todo o Israel ficaram sabendo que o rei não tinha nada a ver com a morte de Abner, filho de Ner.

[[v10-3-38]]

^<<v10-3-38,38>>^ Então o rei disse aos seus servos: — Saibam que hoje caiu em Israel um príncipe e um grande homem.

[[v10-3-39]]

^<<v10-3-39,39>>^ Hoje sou fraco, embora ungido rei. Esses homens, os filhos de Zeruia, são mais fortes do que eu. Que o Senhor  retribua ao que fez esse mal como ele merece.

'''

xref:010-2-samuel/010-2-samuel-002.adoc#v10-2-0[&#60; Capítulo Anterior] | <<v10-3-0,Topo>> | xref:010-2-samuel/010-2-samuel-004.adoc#v10-4-0[Próximo Capítulo &#62;]