include::./index.adoc[]

[[v10-12-0]]
=== 2 Samuel, 12
// naa ?, NAA - Nova Almeida Atualizada

[[v10-12-1]]

^<<v10-12-1,1>>^ O Senhor  enviou Natã a Davi. Natã foi falar com Davi e lhe disse: — Havia numa cidade dois homens, um rico e outro pobre.

[[v10-12-2]]

^<<v10-12-2,2>>^ O rico tinha ovelhas e gado em grande número,

[[v10-12-3]]

^<<v10-12-3,3>>^ mas o pobre não tinha coisa nenhuma, a não ser uma cordeirinha que havia comprado. Ele a criou, e ela cresceu em sua casa, junto com os seus filhos. Comia da sua comida e bebia do seu copo. Dormia nos seus braços, e ele a tinha como filha.

[[v10-12-4]]

^<<v10-12-4,4>>^ Certo dia chegou um viajante à casa do homem rico, e este não quis pegar uma das suas ovelhas ou um dos seus bois para dar de comer ao visitante que havia chegado; em vez disso, pegou a cordeirinha do homem pobre e a preparou para o homem que havia chegado.

[[v10-12-5]]

^<<v10-12-5,5>>^ Então o furor de Davi se acendeu contra aquele homem, e ele disse a Natã: — Tão certo como vive o Senhor , o homem que fez isso deve ser morto.

[[v10-12-6]]

^<<v10-12-6,6>>^ E pela cordeirinha restituirá quatro vezes, porque fez uma coisa dessas e porque não se compadeceu.

[[v10-12-7]]

^<<v10-12-7,7>>^ Então Natã disse a Davi: — Esse homem é você. Assim diz o Senhor , o Deus de Israel: "Eu o ungi rei sobre Israel e eu o livrei das mãos de Saul.

[[v10-12-8]]

^<<v10-12-8,8>>^ Eu lhe dei a casa de seu senhor e as mulheres de seu senhor em seus braços. Também lhe dei a casa de Israel e de Judá. E, se isto fosse pouco, eu teria acrescentado tais e tais coisas.

[[v10-12-9]]

^<<v10-12-9,9>>^ Por que, então, você desprezou a palavra do Senhor , fazendo o que era mau aos olhos dele? Com a espada você matou Urias, o heteu. Você tomou por esposa a mulher dele, depois de o matar com a espada dos filhos de Amom.

[[v10-12-10]]

^<<v10-12-10,10>>^ Agora, pois, a espada jamais se afastará da sua casa, porque você me desprezou e tomou a mulher de Urias, o heteu, para ser sua mulher."

[[v10-12-11]]

^<<v10-12-11,11>>^ Assim diz o Senhor : "Eis que farei com que de sua própria casa venha o mal sobre você. Tomarei as suas mulheres à sua própria vista e as darei a outro homem, que se deitará com elas em plena luz do dia.

[[v10-12-12]]

^<<v10-12-12,12>>^ Porque você o fez em segredo, mas eu farei isso diante de todo o Israel e em plena luz do dia."

[[v10-12-13]]

^<<v10-12-13,13>>^ Então Davi disse a Natã: — Pequei contra o Senhor . E Natã respondeu: — Também o Senhor  perdoou o seu pecado; você não morrerá.

[[v10-12-14]]

^<<v10-12-14,14>>^ Mas, porque com isto você deu motivo a que os inimigos do Senhor  blasfemassem, também o filho que lhe nasceu morrerá.

[[v10-12-15]]

^<<v10-12-15,15>>^ Então Natã foi para a sua casa. E o Senhor  feriu a criança que a mulher de Urias teve com Davi; e a criança adoeceu gravemente.

[[v10-12-16]]

^<<v10-12-16,16>>^ Davi suplicou a Deus pela criança. Davi jejuava e, entrando em casa, passava a noite deitado no chão.

[[v10-12-17]]

^<<v10-12-17,17>>^ Então os anciãos do seu palácio se aproximaram dele, para o levantar do chão; porém ele não quis e não comeu com eles.

[[v10-12-18]]

^<<v10-12-18,18>>^ No sétimo dia, a criança morreu. E os servos de Davi ficaram com medo de informá-lo de que a criança estava morta, porque diziam: — Quando a criança ainda estava viva, falávamos com ele, mas ele não dava ouvidos à nossa voz. Como, então, vamos dizer a ele que a criança morreu? Poderá fazer alguma loucura!

[[v10-12-19]]

^<<v10-12-19,19>>^ Mas Davi notou que os seus servos cochichavam uns com os outros e entendeu que a criança havia morrido. Então perguntou: — A criança morreu? Eles responderam: — Morreu.

[[v10-12-20]]

^<<v10-12-20,20>>^ Então Davi se levantou do chão, lavou-se, ungiu-se, trocou de roupa, entrou na Casa do Senhor  e adorou. Depois, voltou para o palácio e pediu comida; puseram-na diante dele, e ele comeu.

[[v10-12-21]]

^<<v10-12-21,21>>^ O seus servos lhe disseram: — Que é isto que o senhor fez? Pela criança viva o senhor jejuou e chorou, mas, depois que ela morreu, se levantou e se pôs a comer!

[[v10-12-22]]

^<<v10-12-22,22>>^ Davi respondeu: — Enquanto a criança ainda estava viva, jejuei e chorei, porque dizia: "Talvez o Senhor  se compadeça de mim, e a criança continuará viva."

[[v10-12-23]]

^<<v10-12-23,23>>^ Mas agora que ela morreu, por que jejuar? Poderei eu trazê-la de volta? Eu irei até ela, mas ela não voltará para mim.

[[v10-12-24]]

^<<v10-12-24,24>>^ Então Davi consolou Bate-Seba, sua mulher. Teve relações com ela, e ela teve um filho, a quem Davi deu o nome de Salomão; e o Senhor  o amou.

[[v10-12-25]]

^<<v10-12-25,25>>^ Davi o entregou nas mãos do profeta Natã, e este lhe chamou Jedidias, por causa do Senhor .

[[v10-12-26]]

^<<v10-12-26,26>>^ Enquanto isso, Joabe atacou Rabá, dos filhos de Amom, e tomou a cidade real.

[[v10-12-27]]

^<<v10-12-27,27>>^ Então Joabe mandou mensageiros a Davi, dizendo: — Lutei contra Rabá e tomei a cidade das águas.

[[v10-12-28]]

^<<v10-12-28,28>>^ Reúna agora o resto do exército e cerque a cidade para tomá-la; do contrário, se eu a tomar, ela poderia ser chamada pelo meu nome.

[[v10-12-29]]

^<<v10-12-29,29>>^ Então Davi reuniu todo o povo, marchou para Rabá, lutou contra ela, e a tomou.

[[v10-12-30]]

^<<v10-12-30,30>>^ Tirou a coroa da cabeça do seu rei. O peso da coroa era de trinta e quatro quilos de ouro, e havia nela pedras preciosas. Essa coroa foi posta na cabeça de Davi. E da cidade ele levou muitos despojos.

[[v10-12-31]]

^<<v10-12-31,31>>^ Também trouxe o povo que havia nela, e os fez trabalhar com serras, picaretas, machados de ferro e em fornos de tijolos. Davi fez o mesmo com todas as cidades dos filhos de Amom. Depois voltou com todo o exército para Jerusalém.

'''

xref:010-2-samuel/010-2-samuel-011.adoc#v10-11-0[&#60; Capítulo Anterior] | <<v10-12-0,Topo>> | xref:010-2-samuel/010-2-samuel-013.adoc#v10-13-0[Próximo Capítulo &#62;]