include::./index.adoc[]

[[v10-4-0]]
=== 2 Samuel, 4
// naa ?, NAA - Nova Almeida Atualizada

[[v10-4-1]]

^<<v10-4-1,1>>^ Quando Isbosete, o filho de Saul, soube que Abner tinha sido morto em Hebrom, as suas mãos desfaleceram; e todo o Israel ficou consternado.

[[v10-4-2]]

^<<v10-4-2,2>>^ Esse filho de Saul tinha a seu serviço dois homens, capitães de tropas. Um se chamava Baaná e o outro, Recabe. Eram filhos de Rimom, o beerotita, dos filhos de Benjamim, porque também a cidade de Beerote era considerada como pertencente a Benjamim.

[[v10-4-3]]

^<<v10-4-3,3>>^ Os beerotitas tinham fugido para Gitaim e ali vivem como estrangeiros até o dia de hoje.

[[v10-4-4]]

^<<v10-4-4,4>>^ Jônatas, filho de Saul, tinha um filho aleijado dos pés. Ele tinha cinco anos de idade quando de Jezreel chegaram as notícias da morte de Saul e de Jônatas. Então sua ama o pegou e fugiu. Aconteceu que, apressando-se ela a fugir, ele caiu e ficou manco. Seu nome era Mefibosete.

[[v10-4-5]]

^<<v10-4-5,5>>^ Recabe e Baaná, filhos de Rimom, beerotita, chegaram à casa de Isbosete, no maior calor do dia, estando este a dormir, ao meio-dia.

[[v10-4-6]]

^<<v10-4-6,6>>^ Ali, entraram para o interior da casa, como que vindo buscar trigo, e o feriram na barriga. Depois, Recabe e Baaná, seu irmão, fugiram.

[[v10-4-7]]

^<<v10-4-7,7>>^ Eles tinham entrado na casa enquanto Isbosete estava deitado em sua cama, no quarto de dormir, feriram-no e o mataram. Depois cortaram a cabeça dele e a levaram, andando toda a noite pelo caminho da planície.

[[v10-4-8]]

^<<v10-4-8,8>>^ Levaram a cabeça de Isbosete ao rei Davi, em Hebrom, e lhe disseram: — Aqui está a cabeça de Isbosete, filho de seu inimigo Saul, que queria matá-lo. Assim, hoje o Senhor  Deus vingou o rei, meu senhor, de Saul e da sua descendência.

[[v10-4-9]]

^<<v10-4-9,9>>^ Porém Davi respondeu a Recabe e a Baaná, seu irmão, filhos de Rimom, o beerotita, dizendo: — Tão certo como vive o Senhor , que remiu a minha alma de toda a angústia,

[[v10-4-10]]

^<<v10-4-10,10>>^ quando alguém me trouxe a notícia de que Saul estava morto, pensando que me trazia uma boa notícia, como recompensa eu o agarrei e matei em Ziclague.

[[v10-4-11]]

^<<v10-4-11,11>>^ Muito mais agora que homens perversos mataram um homem justo em sua casa, deitado no seu leito, será que eu não requereria o sangue dele das mãos de vocês e não os exterminaria da face da terra?

[[v10-4-12]]

^<<v10-4-12,12>>^ Então Davi deu ordem aos seus moços e eles mataram Recabe e Baaná. Depois, cortaram as mãos e os pés deles, e os penduraram junto à cisterna em Hebrom. Porém pegaram a cabeça de Isbosete e a sepultaram no túmulo de Abner, em Hebrom.

'''

xref:010-2-samuel/010-2-samuel-003.adoc#v10-3-0[&#60; Capítulo Anterior] | <<v10-4-0,Topo>> | xref:010-2-samuel/010-2-samuel-005.adoc#v10-5-0[Próximo Capítulo &#62;]