include::./index.adoc[]

[[v10-16-0]]
=== 2 Samuel, 16
// naa ?, NAA - Nova Almeida Atualizada

[[v10-16-1]]

^<<v10-16-1,1>>^ Davi tinha acabado de passar o alto do monte das Oliveiras quando Ziba, servo de Mefibosete, veio ao encontro dele com dois jumentos encilhados, trazendo duzentos pães, cem cachos de passas, cem frutas de verão e um odre de vinho.

[[v10-16-2]]

^<<v10-16-2,2>>^ O rei perguntou a Ziba: — O que você pretende com isto? Ziba respondeu: — Os jumentos são para a casa do rei, para serem montados; o pão e as frutas de verão, para os moços comerem; o vinho, para os cansados no deserto beberem.

[[v10-16-3]]

^<<v10-16-3,3>>^ Então o rei perguntou: — Onde está o neto de seu senhor? Ziba respondeu: — Eis que ficou em Jerusalém, pois disse: "Hoje a casa de Israel me restituirá o reino de meu avô."

[[v10-16-4]]

^<<v10-16-4,4>>^ Então o rei disse a Ziba: — Tudo o que pertence a Mefibosete é seu. Ziba respondeu: — Eu me inclino e que eu encontre favor diante do rei, meu senhor.

[[v10-16-5]]

^<<v10-16-5,5>>^ Quando o rei Davi chegou a Baurim, eis que dali saiu um homem da família da casa de Saul, cujo nome era Simei, filho de Gera; saiu e ia amaldiçoando.

[[v10-16-6]]

^<<v10-16-6,6>>^ Atirava pedras contra Davi e contra todos os seus servos, embora todo o povo e todos os valentes estivessem à direita e à esquerda do rei.

[[v10-16-7]]

^<<v10-16-7,7>>^ Enquanto amaldiçoava, Simei dizia: — Fora daqui! Fora daqui, assassino! Homem maligno!

[[v10-16-8]]

^<<v10-16-8,8>>^ O Senhor  Deus o está castigando por todo o sangue derramado na casa de Saul, cujo reino você usurpou. O Senhor  já entregou o reino nas mãos de seu filho Absalão. Agora você caiu em desgraça, porque é um assassino!

[[v10-16-9]]

^<<v10-16-9,9>>^ Então Abisai, filho de Zeruia, disse ao rei: — Por que este cão morto amaldiçoaria meu senhor, o rei? Deixe que vá até lá e corte a cabeça dele.

[[v10-16-10]]

^<<v10-16-10,10>>^ Mas o rei disse: — Que tenho eu a ver com vocês, filhos de Zeruia? Deixem que amaldiçoe! Pois, se o Senhor  lhe disse: "Amaldiçoe Davi", quem poderia perguntar: "Por que você está fazendo isso?"

[[v10-16-11]]

^<<v10-16-11,11>>^ E Davi disse a Abisai e a todos os seus servos: — Se o meu próprio filho quer me matar, que dizer desse benjamita? Deixem-no em paz. Que amaldiçoe, pois o Senhor  lhe ordenou.

[[v10-16-12]]

^<<v10-16-12,12>>^ Talvez o Senhor  olhe para a minha aflição e o Senhor  reverta em bênção a maldição que ele está proferindo no dia de hoje.

[[v10-16-13]]

^<<v10-16-13,13>>^ E assim Davi e os seus homens prosseguiam o seu caminho. Também Simei ia pela encosta do monte, ao lado dele, caminhando e amaldiçoando, e atirava pedras e terra contra ele.

[[v10-16-14]]

^<<v10-16-14,14>>^ O rei e todo o povo que ia com ele chegaram exaustos ao Jordão e ali descansaram.

[[v10-16-15]]

^<<v10-16-15,15>>^ Absalão e todo o povo, homens de Israel, entraram em Jerusalém, e Aitofel estava com ele.

[[v10-16-16]]

^<<v10-16-16,16>>^ Quando Husai, o arquita, amigo de Davi, se apresentou a Absalão, disse a ele: — Viva o rei! Viva o rei!

[[v10-16-17]]

^<<v10-16-17,17>>^ Porém Absalão disse a Husai: — É esta a sua fidelidade para com o seu amigo Davi? Por que você não foi com o seu amigo?

[[v10-16-18]]

^<<v10-16-18,18>>^ Husai respondeu a Absalão: — Não! Aquele a quem o Senhor  elegeu e que foi escolhido por todo este povo e todos os homens de Israel, dele serei e com ele ficarei.

[[v10-16-19]]

^<<v10-16-19,19>>^ Além disso, a quem serviria eu? Será que não seria ao filho do rei? Como servi ao seu pai, assim servirei a você.

[[v10-16-20]]

^<<v10-16-20,20>>^ Então Absalão perguntou a Aitofel: — O que vocês aconselham que devemos fazer?

[[v10-16-21]]

^<<v10-16-21,21>>^ Aitofel respondeu a Absalão: — Tenha relações com as concubinas de seu pai, que ele deixou para cuidar do palácio. Todo o Israel ficará sabendo que você se fez odioso para com o seu pai, e todos os que estão com você ficarão animados.

[[v10-16-22]]

^<<v10-16-22,22>>^ Então armaram uma tenda para Absalão no terraço, e ali, à vista de todo o Israel, ele teve relações com as concubinas de seu pai.

[[v10-16-23]]

^<<v10-16-23,23>>^ O conselho que Aitofel dava, naqueles dias, era como resposta de Deus a uma consulta; tanto Davi como Absalão seguiam os conselhos de Aitofel.

'''

xref:010-2-samuel/010-2-samuel-015.adoc#v10-15-0[&#60; Capítulo Anterior] | <<v10-16-0,Topo>> | xref:010-2-samuel/010-2-samuel-017.adoc#v10-17-0[Próximo Capítulo &#62;]