include::./index.adoc[]

[[v10-7-0]]
=== 2 Samuel, 7
// naa ?, NAA - Nova Almeida Atualizada

[[v10-7-1]]

^<<v10-7-1,1>>^ E aconteceu que, quando o rei Davi já morava em seu palácio, pois o Senhor  lhe tinha dado descanso de todos os seus inimigos ao redor,

[[v10-7-2]]

^<<v10-7-2,2>>^ o rei disse ao profeta Natã: — Veja! Estou morando num palácio feito de cedro, mas a arca de Deus se encontra numa tenda.

[[v10-7-3]]

^<<v10-7-3,3>>^ Então Natã disse ao rei: — Vá e faça tudo o que estiver em seu coração, porque o Senhor  está com você.

[[v10-7-4]]

^<<v10-7-4,4>>^ Porém, naquela mesma noite, a palavra do Senhor  veio a Natã, dizendo:

[[v10-7-5]]

^<<v10-7-5,5>>^ — Vá e diga ao meu servo Davi: Assim diz o Senhor : "Você quer edificar um templo para minha habitação?

[[v10-7-6]]

^<<v10-7-6,6>>^ Desde o dia em que tirei os filhos de Israel do Egito até o dia de hoje, não habitei em nenhum templo, mas tenho andado em tenda, em tabernáculo.

[[v10-7-7]]

^<<v10-7-7,7>>^ Em todos os lugares em que andei com todos os filhos de Israel, por acaso falei alguma palavra com qualquer das suas tribos, a quem mandei apascentar o meu povo de Israel, dizendo: ‘Por que vocês não construíram um templo de cedro para mim?’"

[[v10-7-8]]

^<<v10-7-8,8>>^ — Agora diga ao meu servo Davi: Assim diz o Senhor  dos Exércitos: "Eu tirei você das pastagens e do trabalho de andar atrás das ovelhas, para que você fosse príncipe sobre o meu povo, sobre Israel.

[[v10-7-9]]

^<<v10-7-9,9>>^ Estive com você por onde quer que você andou e eliminei todos os seus inimigos diante de você. Engrandecerei o seu nome, como só os grandes têm na terra.

[[v10-7-10]]

^<<v10-7-10,10>>^ Prepararei um lugar para o meu povo, para Israel, e o plantarei para que habite no seu lugar e não seja mais perturbado. E jamais os filhos da perversidade o afligirão, como no passado,

[[v10-7-11]]

^<<v10-7-11,11>>^ desde o dia em que mandei que houvesse juízes sobre o meu povo de Israel. Eu lhe darei descanso de todos os seus inimigos. O Senhor  também lhe faz saber que ele, o Senhor , fará uma casa para você.

[[v10-7-12]]

^<<v10-7-12,12>>^ Quando os seus dias se completarem e você descansar com os seus pais, então farei surgir depois de você o seu descendente, que procederá de você, e estabelecerei o seu reino.

[[v10-7-13]]

^<<v10-7-13,13>>^ Este edificará um templo ao meu nome, e eu estabelecerei para sempre o trono do seu reino.

[[v10-7-14]]

^<<v10-7-14,14>>^ Eu lhe serei por pai, e ele me será por filho. Se vier a transgredir, eu o castigarei com varas de homens e com açoites de filhos de homens.

[[v10-7-15]]

^<<v10-7-15,15>>^ Mas a minha misericórdia não se afastará dele, como a retirei de Saul, a quem tirei de diante de você.

[[v10-7-16]]

^<<v10-7-16,16>>^ Quanto a você, a sua casa e o seu reino serão firmados para sempre diante de mim; o seu trono será estabelecido para sempre."

[[v10-7-17]]

^<<v10-7-17,17>>^ Segundo todas estas palavras e conforme toda esta visão, assim Natã falou com Davi.

[[v10-7-18]]

^<<v10-7-18,18>>^ Então o rei Davi se pôs diante do Senhor  e disse: — Quem sou eu, Senhor  Deus, e qual é a minha casa, para que me tenhas trazido até aqui?

[[v10-7-19]]

^<<v10-7-19,19>>^ E como se isto ainda fosse pouco aos teus olhos, Senhor  Deus, também falaste a respeito da casa de teu servo para tempos distantes; e isto é instrução para toda a humanidade, ó Senhor  Deus.

[[v10-7-20]]

^<<v10-7-20,20>>^ Que mais ainda te poderá dizer Davi? Pois tu conheces bem o teu servo, ó Senhor  Deus.

[[v10-7-21]]

^<<v10-7-21,21>>^ Por causa da tua palavra e segundo o teu coração, fizeste toda esta grandeza, dando-a a conhecer a teu servo.

[[v10-7-22]]

^<<v10-7-22,22>>^ Portanto, grandioso és tu, ó Senhor  Deus, porque não há ninguém semelhante a ti, e não há outro Deus além de ti, segundo tudo o que nós mesmos temos ouvido.

[[v10-7-23]]

^<<v10-7-23,23>>^ Quem há como o teu povo, como Israel, gente única na terra, a quem Deus foi resgatar para ser o seu povo? Fizeste para ti mesmo um nome e fizeste por teu povo estas grandes e tremendas coisas, para a tua terra, diante do teu povo, que resgataste do Egito, desterrando as nações e os seus deuses.

[[v10-7-24]]

^<<v10-7-24,24>>^ Estabeleceste o teu povo de Israel por teu povo para sempre e tu, ó Senhor , te fizeste o seu Deus.

[[v10-7-25]]

^<<v10-7-25,25>>^ — E agora, Senhor  Deus, quanto a esta palavra que disseste a respeito de teu servo e a respeito da sua casa, confirma-a para sempre; e faze como falaste.

[[v10-7-26]]

^<<v10-7-26,26>>^ Seja para sempre engrandecido o teu nome, e que se diga: "O Senhor  dos Exércitos é Deus sobre Israel!" E a casa de Davi, teu servo, será estabelecida diante de ti.

[[v10-7-27]]

^<<v10-7-27,27>>^ Pois tu, ó Senhor  dos Exércitos, Deus de Israel, fizeste ao teu servo esta revelação, dizendo: "Edificarei uma casa para você." Por isso, o teu servo se animou para fazer-te esta oração.

[[v10-7-28]]

^<<v10-7-28,28>>^ — Agora, pois, ó Senhor  Deus, tu mesmo és Deus, e as tuas palavras são verdade, e tens prometido ao teu servo este bem.

[[v10-7-29]]

^<<v10-7-29,29>>^ Queiras, agora, abençoar a casa do teu servo, a fim de permanecer para sempre diante de ti, pois tu, ó Senhor  Deus, o disseste; e, com a tua bênção, a casa do teu servo será abençoada para sempre.

'''

xref:010-2-samuel/010-2-samuel-006.adoc#v10-6-0[&#60; Capítulo Anterior] | <<v10-7-0,Topo>> | xref:010-2-samuel/010-2-samuel-008.adoc#v10-8-0[Próximo Capítulo &#62;]