include::./index.adoc[]

[[v10-24-0]]
=== 2 Samuel, 24
// naa ?, NAA - Nova Almeida Atualizada

[[v10-24-1]]

^<<v10-24-1,1>>^ Mais uma vez a ira do Senhor  se acendeu contra os israelitas, e ele incitou Davi contra eles, dizendo: — Vá e levante o censo de Israel e de Judá.

[[v10-24-2]]

^<<v10-24-2,2>>^ O rei disse a Joabe, comandante do seu exército: — Percorra todas as tribos de Israel, desde Dã até Berseba, e levante o censo do povo, para que eu saiba o seu número.

[[v10-24-3]]

^<<v10-24-3,3>>^ Então Joabe disse ao rei: — Que o Senhor , seu Deus, multiplique este povo cem vezes mais, e que o rei, meu senhor, o veja! Mas por que o rei, meu senhor, quer fazer uma coisa dessas?

[[v10-24-4]]

^<<v10-24-4,4>>^ Porém a palavra do rei prevaleceu contra Joabe e contra os chefes do exército. Então eles saíram da presença do rei, para levantar o censo do povo de Israel.

[[v10-24-5]]

^<<v10-24-5,5>>^ Passaram o Jordão e acamparam em Aroer, à direita da cidade que está no meio do vale de Gade, e foram a Jazer.

[[v10-24-6]]

^<<v10-24-6,6>>^ Dali foram a Gileade e chegaram até Cades, na terra dos heteus. Seguiram a Dã-Jaã e viraram-se para Sidom.

[[v10-24-7]]

^<<v10-24-7,7>>^ Chegaram à fortaleza de Tiro e a todas as cidades dos heveus e dos cananeus, de onde saíram para o Sul de Judá, a Berseba.

[[v10-24-8]]

^<<v10-24-8,8>>^ Assim, percorreram toda a terra e, depois de nove meses e vinte dias, chegaram a Jerusalém.

[[v10-24-9]]

^<<v10-24-9,9>>^ Joabe apresentou ao rei o resultado do recenseamento do povo: havia em Israel oitocentos mil homens de guerra, que puxavam da espada; e em Judá eram quinhentos mil.

[[v10-24-10]]

^<<v10-24-10,10>>^ Depois de haver recenseado o povo, Davi ficou com dor no coração. Ele disse ao Senhor : — Cometi um grande pecado ao fazer o que fiz. Mas agora, ó Senhor , peço-te que perdoes a iniquidade do teu servo, porque fiz uma grande loucura.

[[v10-24-11]]

^<<v10-24-11,11>>^ Quando Davi se levantou pela manhã, a palavra do Senhor  veio ao profeta Gade, vidente de Davi, dizendo:

[[v10-24-12]]

^<<v10-24-12,12>>^ — Vá e diga a Davi: Assim diz o Senhor : "Eu lhe ofereço três opções; escolha uma delas, para que eu a execute contra você."

[[v10-24-13]]

^<<v10-24-13,13>>^ Gade foi falar com Davi e lhe comunicou isso, dizendo: — Você quer sete anos de fome na sua terra, três meses fugindo dos seus inimigos, que vão persegui-lo, ou três dias de peste na sua terra? Decida, agora, e diga que resposta devo dar ao que me enviou.

[[v10-24-14]]

^<<v10-24-14,14>>^ Então Davi disse a Gade: — Estou muito angustiado. Porém é preferível que caiamos nas mãos do Senhor , porque muitas são as suas misericórdias; não quero cair nas mãos dos homens.

[[v10-24-15]]

^<<v10-24-15,15>>^ Então o Senhor  enviou a peste a Israel, desde a manhã até o tempo que havia determinado. E, desde Dã até Berseba, morreram setenta mil homens do povo.

[[v10-24-16]]

^<<v10-24-16,16>>^ Quando o Anjo do Senhor  estendeu a mão sobre Jerusalém, para a destruir, o Senhor  mudou de ideia quanto a este mal e disse ao Anjo que fazia a destruição entre o povo: — Basta! Retire a sua mão. O Anjo estava junto à eira de Araúna, o jebuseu.

[[v10-24-17]]

^<<v10-24-17,17>>^ Ao ver o Anjo que feria o povo, Davi falou ao Senhor  e disse: — Eu é que pequei. Eu é que fiz essa perversidade. Mas estas ovelhas o que fizeram? Que a tua mão seja contra mim e contra a casa de meu pai.

[[v10-24-18]]

^<<v10-24-18,18>>^ Naquele mesmo dia, Gade foi falar com Davi e lhe disse: — Vá e edifique um altar ao Senhor  na eira de Araúna, o jebuseu.

[[v10-24-19]]

^<<v10-24-19,19>>^ Davi foi segundo a palavra de Gade, como o Senhor  lhe havia ordenado.

[[v10-24-20]]

^<<v10-24-20,20>>^ Araúna viu, do alto, que o rei e os seus homens vinham ao seu encontro. Saiu e se inclinou diante do rei, com o rosto em terra.

[[v10-24-21]]

^<<v10-24-21,21>>^ E perguntou: — Por que o rei, meu senhor, vem até este seu servo? Davi respondeu: — Para comprar de você esta eira, a fim de edificar nela um altar ao Senhor , para que cesse a praga no meio do povo.

[[v10-24-22]]

^<<v10-24-22,22>>^ Então Araúna disse a Davi: — Que o rei, meu senhor, tome e ofereça o que bem quiser. Aqui estão os bois para o holocausto, o debulhador de cereais e a canga dos bois para a lenha.

[[v10-24-23]]

^<<v10-24-23,23>>^ Tudo isto, ó rei, Araúna oferece ao rei. E acrescentou: — Que o Senhor , seu Deus, aceite a sua oferta.

[[v10-24-24]]

^<<v10-24-24,24>>^ Porém o rei disse a Araúna: — Não! Eu vou comprar de você pelo que vale. Porque não oferecerei ao Senhor , meu Deus, holocaustos que não me custem nada. Assim, Davi comprou a eira e os bois por cinquenta moedas de prata.

[[v10-24-25]]

^<<v10-24-25,25>>^ Davi edificou ali um altar ao Senhor  e apresentou holocaustos e ofertas pacíficas. Assim, o Senhor  se tornou favorável para com a terra, e a praga cessou no meio de Israel.

'''

xref:010-2-samuel/010-2-samuel-023.adoc#v10-23-0[&#60; Capítulo Anterior] | <<v10-24-0,Topo>> | xref:011-1-reis/011-1-reis-001.adoc#v11-1-0[Próximo Capítulo &#62;]