include::./index.adoc[]

[[v10-19-0]]
=== 2 Samuel, 19
// naa ?, NAA - Nova Almeida Atualizada

[[v10-19-1]]

^<<v10-19-1,1>>^ Disseram a Joabe: — Eis que o rei anda chorando e se lamentando por Absalão.

[[v10-19-2]]

^<<v10-19-2,2>>^ Assim, a vitória se tornou, naquele mesmo dia, em luto para todo o povo, porque, naquele dia, o povo tinha ouvido dizer: "O rei está de luto por causa de seu filho."

[[v10-19-3]]

^<<v10-19-3,3>>^ Naquele mesmo dia, o povo entrou às escondidas na cidade, como o faz quando foge envergonhado da batalha.

[[v10-19-4]]

^<<v10-19-4,4>>^ O rei tinha coberto o rosto e exclamava em alta voz: — Meu filho Absalão! Absalão, meu filho! Meu filho!

[[v10-19-5]]

^<<v10-19-5,5>>^ Então Joabe entrou na casa do rei e lhe disse: — Hoje o rei envergonhou a face de todos os seus servos, que hoje mesmo livraram a sua vida, a vida de seus filhos e de suas filhas e a vida de suas mulheres e de suas concubinas.

[[v10-19-6]]

^<<v10-19-6,6>>^ Você ama os que o odeiam e odeia os que o amam. Hoje dá a entender que os seus comandantes e soldados não têm qualquer valor. Porque agora entendo que, se Absalão estivesse vivo e todos nós hoje estivéssemos mortos, então você estaria contente.

[[v10-19-7]]

^<<v10-19-7,7>>^ Agora, levante-se, saia e diga uma palavra de encorajamento aos seus soldados. Juro pelo Senhor  que, se não sair, nem um só homem ficará com você esta noite. E este mal seria maior do que todos que têm vindo sobre você desde a sua mocidade até agora.

[[v10-19-8]]

^<<v10-19-8,8>>^ Então o rei se levantou e sentou junto ao portão da cidade. E anunciaram isso a todo o povo, dizendo: — Eis que o rei está sentado junto ao portão da cidade. E todo o povo veio apresentar-se diante do rei. Ora, Israel havia fugido, cada um para a sua tenda.

[[v10-19-9]]

^<<v10-19-9,9>>^ Todo o povo, em todas as tribos de Israel, andava discutindo entre si, dizendo: — O rei nos tirou das mãos de nossos inimigos, livrou-nos das mãos dos filisteus e, agora, fugiu da terra por causa de Absalão.

[[v10-19-10]]

^<<v10-19-10,10>>^ Absalão, a quem ungimos sobre nós, morreu na batalha. Agora por que vocês estão calados e não fazem com que o rei volte?

[[v10-19-11]]

^<<v10-19-11,11>>^ Então o rei Davi mandou dizer aos sacerdotes Zadoque e Abiatar: — Perguntem aos anciãos de Judá: "Por que vocês seriam os últimos a trazer o rei de volta ao seu palácio, visto que aquilo que todo o Israel dizia já chegou aos ouvidos do rei?

[[v10-19-12]]

^<<v10-19-12,12>>^ Vocês são meus irmãos. São do mesmo povo que eu. Por que, então, seriam os últimos a trazer o rei de volta?"

[[v10-19-13]]

^<<v10-19-13,13>>^ Digam a Amasa: "Você não é da mesma família que eu? Que Deus me castigue se você não vier a ser para sempre comandante do meu exército, em lugar de Joabe."

[[v10-19-14]]

^<<v10-19-14,14>>^ Com isto o rei moveu o coração de todos os homens de Judá, como se fossem um só homem. E mandaram dizer ao rei: — Volte com todos os seus servos.

[[v10-19-15]]

^<<v10-19-15,15>>^ Então o rei voltou e chegou ao Jordão. E os homens de Judá foram a Gilgal, para encontrar-se com o rei, a fim de fazê-lo passar o Jordão.

[[v10-19-16]]

^<<v10-19-16,16>>^ Simei, filho de Gera, benjamita, que era de Baurim, apressou-se e desceu com os homens de Judá a encontrar-se com o rei Davi.

[[v10-19-17]]

^<<v10-19-17,17>>^ Com ele estavam mil homens de Benjamim, bem como Ziba, servo da casa de Saul, acompanhado de seus quinze filhos e seus vinte servos. Entraram no Jordão à vista do rei

[[v10-19-18]]

^<<v10-19-18,18>>^ e o atravessaram, para fazerem passar a casa real e para fazerem o que lhe era agradável. Então Simei, filho de Gera, prostrou-se diante do rei, quando este ia passar o Jordão,

[[v10-19-19]]

^<<v10-19-19,19>>^ e lhe disse: — Que o meu senhor, o rei, não me tenha por culpado nem se lembre do mal que este seu servo cometeu no dia em que o rei, meu senhor, saiu de Jerusalém. Que o rei não guarde isso em seu coração.

[[v10-19-20]]

^<<v10-19-20,20>>^ Porque este seu servo sabe que pecou. Por isso, de toda a casa de José, sou hoje o primeiro que veio encontrar-se com o rei, meu senhor.

[[v10-19-21]]

^<<v10-19-21,21>>^ Então Abisai, filho de Zeruia, disse: — Será que Simei não deveria morrer pelo que fez? Ele amaldiçoou o ungido do Senhor !

[[v10-19-22]]

^<<v10-19-22,22>>^ Porém Davi disse: — Que tenho eu a ver com vocês, filhos de Zeruia? Querem agora se tornar meus adversários? Morreria alguém hoje em Israel? Será que eu não sei que hoje novamente sou rei sobre Israel?

[[v10-19-23]]

^<<v10-19-23,23>>^ Então o rei disse a Simei: — Você não será morto. E o rei jurou que seria assim.

[[v10-19-24]]

^<<v10-19-24,24>>^ Também Mefibosete, neto de Saul, desceu a encontrar-se com o rei. Ele não tinha tratado dos pés, nem aparado a barba, nem lavado as roupas, desde o dia em que o rei tinha saído até o dia em que voltou em paz.

[[v10-19-25]]

^<<v10-19-25,25>>^ Quando ele chegou de Jerusalém para encontrar-se com o rei, este lhe perguntou: — Por que você não foi comigo, Mefibosete?

[[v10-19-26]]

^<<v10-19-26,26>>^ Ele respondeu: — Ó rei, meu senhor, o meu criado me enganou. Porque este seu servo dizia: "Vou mandar preparar um jumento e montarei nele para ir com o rei." Porque este seu servo é coxo.

[[v10-19-27]]

^<<v10-19-27,27>>^ Além do mais, o meu criado falsamente acusou este seu servo diante do rei, meu senhor. Porém o rei, meu senhor, é como um anjo de Deus; que faça o que achar melhor.

[[v10-19-28]]

^<<v10-19-28,28>>^ Porque toda a casa de meu pai era digna de morte diante do rei, meu senhor, mas o rei pôs este seu servo entre os que sentam à sua mesa para comer. Que direito ainda tenho? Que mais posso pedir ao rei?

[[v10-19-29]]

^<<v10-19-29,29>>^ Então o rei disse: — Por que você ainda fala dos seus negócios? Eu decido que você e Ziba repartam as terras.

[[v10-19-30]]

^<<v10-19-30,30>>^ Mas Mefibosete disse ao rei: — Que ele fique com tudo, uma vez que o rei, meu senhor, já voltou em paz à sua casa.

[[v10-19-31]]

^<<v10-19-31,31>>^ Também Barzilai, o gileadita, desceu de Rogelim e passou com o rei o Jordão, para o acompanhar até o outro lado.

[[v10-19-32]]

^<<v10-19-32,32>>^ Barzilai era bem velho, da idade de oitenta anos. Ele havia sustentado o rei quando este estava em Maanaim, porque era um homem muito rico.

[[v10-19-33]]

^<<v10-19-33,33>>^ O rei disse a Barzilai: — Venha comigo, e eu o sustentarei em Jerusalém.

[[v10-19-34]]

^<<v10-19-34,34>>^ Mas Barzilai respondeu ao rei: — Quantos serão ainda os dias dos anos da minha vida? Não vale a pena subir com o rei a Jerusalém.

[[v10-19-35]]

^<<v10-19-35,35>>^ Hoje tenho oitenta anos. Poderia eu discernir entre o que é bom e o que é mau? Poderia este seu servo perceber o sabor do que come e do que bebe? Poderia eu ainda ouvir a voz dos cantores e cantoras? E por que este seu servo se tornaria ainda um peso ao rei, meu senhor?

[[v10-19-36]]

^<<v10-19-36,36>>^ Este seu servo irá com o rei só um pouco além do Jordão. Por que o rei iria me retribuir com tal recompensa?

[[v10-19-37]]

^<<v10-19-37,37>>^ Deixe que este seu servo volte, e morrerei na minha cidade e serei sepultado junto de meu pai e de minha mãe. Mas aqui está o seu servo Quimã. Deixe que ele passe com o rei, meu senhor. Faça por ele o que achar melhor.

[[v10-19-38]]

^<<v10-19-38,38>>^ O rei respondeu: — Quimã passará comigo, e eu farei por ele o que você achar melhor. E tudo o que você me pedir, isso farei por você.

[[v10-19-39]]

^<<v10-19-39,39>>^ Todo o povo passou o Jordão, e o rei também passou. E o rei beijou Barzilai e o abençoou. E Barzilai voltou para casa.

[[v10-19-40]]

^<<v10-19-40,40>>^ Dali o rei foi para Gilgal, e Quimã foi com ele. Todo o povo de Judá e metade do povo de Israel acompanharam o rei.

[[v10-19-41]]

^<<v10-19-41,41>>^ Eis que todos os homens de Israel vieram falar com o rei e lhe disseram: — Por que os nossos irmãos, os homens de Judá, roubaram o rei e o trouxeram para este lado do Jordão com a casa dele e todos os servos de Davi?

[[v10-19-42]]

^<<v10-19-42,42>>^ Então todos os homens de Judá responderam aos homens de Israel: — Porque o rei é nosso parente. E por que estão irados por causa disso? Será que comemos à custa do rei ou ele nos deu algum presente?

[[v10-19-43]]

^<<v10-19-43,43>>^ E os homens de Israel responderam aos homens de Judá e disseram: — Nós temos dez vezes mais direito sobre o rei do que vocês, e Davi é mais nosso do que de vocês. Por que, então, fizeram pouco caso de nós? Não fomos nós os primeiros a falar em trazer o nosso rei de volta? Porém a palavra dos homens de Judá foi mais dura do que a palavra dos homens de Israel.

'''

xref:010-2-samuel/010-2-samuel-018.adoc#v10-18-0[&#60; Capítulo Anterior] | <<v10-19-0,Topo>> | xref:010-2-samuel/010-2-samuel-020.adoc#v10-20-0[Próximo Capítulo &#62;]