include::./index.adoc[]

[[v30-5-0]]
=== Amós, 5
// naa ?, NAA - Nova Almeida Atualizada

[[v30-5-1]]

^<<v30-5-1,1>>^ Ouçam esta palavra que falo contra vocês, ó casa de Israel. É uma lamentação.

[[v30-5-2]]

^<<v30-5-2,2>>^ "Caiu a virgem de Israel, para nunca mais se levantar! Está estendida na sua própria terra, e não há quem a levante."

[[v30-5-3]]

^<<v30-5-3,3>>^ Porque assim diz o Senhor  Deus: "A cidade da qual saem mil conservará apenas cem, e aquela da qual saem cem conservará apenas dez para a casa de Israel."

[[v30-5-4]]

^<<v30-5-4,4>>^ Pois assim diz o Senhor  à casa de Israel: "Busquem a mim e vocês viverão.

[[v30-5-5]]

^<<v30-5-5,5>>^ Porém não busquem Betel, nem venham a Gilgal, nem passem a Berseba. Porque Gilgal certamente será levada cativa, e Betel será reduzida a nada.

[[v30-5-6]]

^<<v30-5-6,6>>^ Busquem o Senhor e vocês viverão. Do contrário, ele irromperá na casa de José como um fogo que a consome, e não haverá em Betel quem consiga apagá-lo.

[[v30-5-7]]

^<<v30-5-7,7>>^ Vocês que transformam o juízo em veneno e lançam por terra a justiça,

[[v30-5-8]]

^<<v30-5-8,8>>^ busquem aquele que fez o Sete-estrelo e o Órion; aquele que torna as densas trevas em manhã e muda o dia em noite; aquele que chama as águas do mar e as derrama sobre a terra; Senhor  é o seu nome.

[[v30-5-9]]

^<<v30-5-9,9>>^ É ele que faz vir súbita destruição sobre o forte e ruína contra a fortaleza."

[[v30-5-10]]

^<<v30-5-10,10>>^ "Vocês odeiam quem os repreende no tribunal e detestam quem fala com sinceridade.

[[v30-5-11]]

^<<v30-5-11,11>>^ Portanto, visto que pisam os pobres e deles exigem tributo de trigo, vocês não habitarão nas casas de pedras lavradas que construíram, nem beberão o vinho das belas videiras que plantaram.

[[v30-5-12]]

^<<v30-5-12,12>>^ Porque sei que são muitas as suas transgressões e que são graves os pecados que vocês cometem. Vocês afligem os justos, aceitam suborno e rejeitam as causas dos necessitados no tribunal.

[[v30-5-13]]

^<<v30-5-13,13>>^ Por isso, numa época de tanta corrupção, quem é prudente prefere ficar calado."

[[v30-5-14]]

^<<v30-5-14,14>>^ "Busquem o bem e não o mal, para que vocês vivam. E assim o Senhor , o Deus dos Exércitos, estará com vocês, como vocês dizem.

[[v30-5-15]]

^<<v30-5-15,15>>^ Odeiem o mal e amem o bem. Promovam a justiça nos tribunais. Talvez o Senhor , o Deus dos Exércitos, se compadeça do remanescente de José."

[[v30-5-16]]

^<<v30-5-16,16>>^ Portanto, assim diz o Senhor, o Senhor , Deus dos Exércitos: "Em todas as praças haverá pranto, e em todas as ruas dirão: ‘Ai! Ai!’ Chamarão os lavradores para o pranto e, para o choro, os que sabem prantear.

[[v30-5-17]]

^<<v30-5-17,17>>^ Em todas as vinhas haverá pranto, porque passarei pelo meio de vocês", diz o Senhor .

[[v30-5-18]]

^<<v30-5-18,18>>^ "Ai dos que desejam o Dia do Senhor ! Para que vocês desejam o Dia do Senhor ? Será um dia de trevas e não de luz.

[[v30-5-19]]

^<<v30-5-19,19>>^ Será como se um homem fugisse de um leão e lhe saísse ao encontro um urso; ou como se, entrando em casa e encostando a mão na parede, fosse mordido por uma cobra.

[[v30-5-20]]

^<<v30-5-20,20>>^ O dia do Senhor  será um dia de trevas e não de luz! Será um dia de completa escuridão, sem nenhuma claridade!"

[[v30-5-21]]

^<<v30-5-21,21>>^ "Eu odeio e desprezo as suas festas e com as suas reuniões solenes não tenho nenhum prazer.

[[v30-5-22]]

^<<v30-5-22,22>>^ Mesmo que vocês me ofereçam holocaustos e ofertas de cereais, não me agradarei deles. Quanto às suas ofertas pacíficas de animais gordos, nem sequer olharei para elas.

[[v30-5-23]]

^<<v30-5-23,23>>^ Afastem de mim o barulho dos seus cânticos, porque não ouvirei as melodias das suas liras.

[[v30-5-24]]

^<<v30-5-24,24>>^ Em vez disso, corra o juízo como as águas, e a justiça, como um ribeiro perene."

[[v30-5-25]]

^<<v30-5-25,25>>^ — Casa de Israel, por acaso vocês me apresentaram sacrifícios e ofertas de cereais durante os quarenta anos no deserto?

[[v30-5-26]]

^<<v30-5-26,26>>^ Pelo contrário, levaram o seu rei Sicute e Quium, o seu deus-estrela, imagens que vocês fizeram para si mesmos.

[[v30-5-27]]

^<<v30-5-27,27>>^ Por isso, vou mandar vocês ao exílio para além de Damasco, diz o Senhor , cujo nome é Deus dos Exércitos.

'''

xref:030-amos/030-amos-004.adoc#v30-4-0[&#60; Capítulo Anterior] | <<v30-5-0,Topo>> | xref:030-amos/030-amos-006.adoc#v30-6-0[Próximo Capítulo &#62;]