include::./index.adoc[]

[[v30-4-0]]
=== Amós, 4
// naa ?, NAA - Nova Almeida Atualizada

[[v30-4-1]]

^<<v30-4-1,1>>^ "Ouçam esta palavra, vacas de Basã, vocês que estão no monte de Samaria, que oprimem os pobres, esmagam os necessitados e dizem aos maridos: ‘Tragam vinho, e vamos beber!’

[[v30-4-2]]

^<<v30-4-2,2>>^ O Senhor  Deus jurou pela sua santidade que virão dias em que vocês serão arrastadas com ganchos; até as últimas de vocês serão levadas com anzóis de pesca.

[[v30-4-3]]

^<<v30-4-3,3>>^ Vocês sairão em fila pelas brechas e serão lançadas na direção do monte Hermom", diz o Senhor .

[[v30-4-4]]

^<<v30-4-4,4>>^ "Venham a Betel e pequem! Venham a Gilgal e pequem ainda mais! Cada manhã, tragam os seus sacrifícios e, de três em três dias, os seus dízimos!

[[v30-4-5]]

^<<v30-4-5,5>>^ Ofereçam sacrifícios de louvor com pão levedado e proclamem ofertas voluntárias! Tornem isso público, porque é disso que vocês gostam, ó filhos de Israel", diz o Senhor  Deus.

[[v30-4-6]]

^<<v30-4-6,6>>^ "Também deixei que vocês ficassem sem ter o que mastigar em todas as suas cidades e com falta de pão em todos os lugares, mas vocês não se converteram a mim", diz o Senhor .

[[v30-4-7]]

^<<v30-4-7,7>>^ "Além disso, retive a chuva, faltando ainda três meses para a colheita. Fiz chover sobre uma cidade e sobre a outra, não; um campo teve chuva, mas o outro, que ficou sem chuva, secou.

[[v30-4-8]]

^<<v30-4-8,8>>^ Pessoas de duas ou três cidades se dirigiram a outra cidade para beber água, sem conseguirem matar a sede, mas vocês não se converteram a mim", diz o Senhor .

[[v30-4-9]]

^<<v30-4-9,9>>^ "Eu os castiguei com o crestamento e a ferrugem. Os gafanhotos devoraram as hortas e as vinhas, as figueiras e as oliveiras, mas vocês não se converteram a mim", diz o Senhor .

[[v30-4-10]]

^<<v30-4-10,10>>^ "Enviei a peste contra vocês, assim como havia feito no Egito. Matei os seus jovens à espada, deixei que os seus cavalos fossem capturados, e fiz com que o mau cheiro dos acampamentos chegasse aos seus narizes, mas vocês não se converteram a mim", diz o Senhor .

[[v30-4-11]]

^<<v30-4-11,11>>^ "Destruí alguns de vocês, como Deus destruiu Sodoma e Gomorra. Vocês foram como um toco de lenha tirado do fogo, mas não se converteram a mim", diz o Senhor .

[[v30-4-12]]

^<<v30-4-12,12>>^ "Portanto, assim farei com você, Israel! E, porque farei isso com você, prepare-se, ó Israel, para se encontrar com o seu Deus!

[[v30-4-13]]

^<<v30-4-13,13>>^ Porque é ele quem forma os montes, cria o vento e declara aos seres humanos qual é o seu pensamento; ele faz da manhã trevas e anda sobre os altos da terra; Senhor , Deus dos Exércitos, é o seu nome."

'''

xref:030-amos/030-amos-003.adoc#v30-3-0[&#60; Capítulo Anterior] | <<v30-4-0,Topo>> | xref:030-amos/030-amos-005.adoc#v30-5-0[Próximo Capítulo &#62;]