include::./index.adoc[]

[[v30-7-0]]
=== Amós, 7
// naa ?, NAA - Nova Almeida Atualizada

[[v30-7-1]]

^<<v30-7-1,1>>^ O Senhor  Deus me mostrou o seguinte: eis que ele formava uma nuvem de gafanhotos no momento em que começavam a brotar as plantas da entressafra, ou seja, a cultura tardia que vinha depois de concluída a colheita reservada ao rei.

[[v30-7-2]]

^<<v30-7-2,2>>^ Quando tinham acabado de comer toda a plantação, eu disse: — Senhor  Deus, perdoa, por favor! Como poderá Jacó sobreviver? Pois ele é pequeno.

[[v30-7-3]]

^<<v30-7-3,3>>^ Então o Senhor  mudou de ideia em relação a isso e falou: — Isso não vai acontecer.

[[v30-7-4]]

^<<v30-7-4,4>>^ Depois, o Senhor  Deus me mostrou o seguinte: eis que o Senhor  Deus chamou o fogo para exercer a sua justiça. Este fogo consumiu o grande abismo e começava a devorar a terra.

[[v30-7-5]]

^<<v30-7-5,5>>^ Então eu disse: — Senhor  Deus, para, por favor! Como poderá Jacó sobreviver? Pois ele é pequeno.

[[v30-7-6]]

^<<v30-7-6,6>>^ E o Senhor  mudou de ideia em relação a isso e falou: — Também isso não vai acontecer.

[[v30-7-7]]

^<<v30-7-7,7>>^ Mostrou-me também isto: eis que o Senhor estava sobre um muro levantado a prumo, e tinha um prumo na mão.

[[v30-7-8]]

^<<v30-7-8,8>>^ O Senhor  me perguntou: — O que você está vendo, Amós? Respondi: — Um prumo. Então o Senhor disse: — Eis que eu porei o prumo no meio do meu povo de Israel; não posso mais ignorar o que fazem.

[[v30-7-9]]

^<<v30-7-9,9>>^ Os lugares altos de Isaque serão assolados, e os santuários de Israel serão destruídos. E eu me levantarei com a espada contra a casa de Jeroboão.

[[v30-7-10]]

^<<v30-7-10,10>>^ Então Amazias, o sacerdote de Betel, mandou dizer a Jeroboão, rei de Israel: — Amós está conspirando contra o rei no meio da casa de Israel. A terra não pode suportar todas as suas palavras.

[[v30-7-11]]

^<<v30-7-11,11>>^ Porque assim diz Amós: "Jeroboão morrerá à espada, e Israel certamente será levado para fora de sua terra, em cativeiro."

[[v30-7-12]]

^<<v30-7-12,12>>^ Depois Amazias disse a Amós: — Saia daqui, vidente! Fuja para a terra de Judá e vá ganhar a vida por lá. Em Judá você pode profetizar.

[[v30-7-13]]

^<<v30-7-13,13>>^ Mas em Betel, daqui em diante, você não poderá profetizar, porque este é o santuário do rei e o templo do reino.

[[v30-7-14]]

^<<v30-7-14,14>>^ Amós respondeu e disse a Amazias: — Eu não sou profeta nem discípulo de profeta. Eu cuido de gado e colho sicômoros.

[[v30-7-15]]

^<<v30-7-15,15>>^ Mas o Senhor  me tirou do trabalho de andar atrás do gado e me disse: "Vá e profetize ao meu povo de Israel."

[[v30-7-16]]

^<<v30-7-16,16>>^ Portanto, agora ouça a palavra do Senhor . Você diz: "Não profetize contra Israel nem fale contra a casa de Isaque."

[[v30-7-17]]

^<<v30-7-17,17>>^ Pois bem, assim diz o Senhor : "A sua mulher se prostituirá na cidade, e os seus filhos e as suas filhas cairão à espada. A sua terra será repartida a cordel, e você morrerá numa terra impura. E Israel certamente será levado cativo para fora da sua terra."

'''

xref:030-amos/030-amos-006.adoc#v30-6-0[&#60; Capítulo Anterior] | <<v30-7-0,Topo>> | xref:030-amos/030-amos-008.adoc#v30-8-0[Próximo Capítulo &#62;]