include::./index.adoc[]

[[v30-6-0]]
=== Amós, 6
// naa ?, NAA - Nova Almeida Atualizada

[[v30-6-1]]

^<<v30-6-1,1>>^ "Ai dos que andam à vontade em Sião e dos que vivem sem receio no monte de Samaria, homens notáveis da principal das nações, aos quais se dirige a casa de Israel!

[[v30-6-2]]

^<<v30-6-2,2>>^ Vão à cidade de Calné e olhem. Dali, vão à grande cidade de Hamate e, depois, desçam até Gate dos filisteus. Será que eles são melhores do que os reinos de vocês? Ou será que o território deles é maior do que o de vocês?

[[v30-6-3]]

^<<v30-6-3,3>>^ Vocês imaginam que o dia mau está longe, mas estão fazendo com que o trono da violência se aproxime.

[[v30-6-4]]

^<<v30-6-4,4>>^ Vocês dormem em camas de marfim e se espreguiçam sobre os seus leitos. Comem os cordeiros do rebanho e os bezerros que estão na engorda.

[[v30-6-5]]

^<<v30-6-5,5>>^ Ficam cantando à toa ao som da lira e, como Davi, inventam instrumentos musicais.

[[v30-6-6]]

^<<v30-6-6,6>>^ Bebem vinho em taças e se ungem com o mais excelente óleo, mas não se afligem com a ruína de José.

[[v30-6-7]]

^<<v30-6-7,7>>^ Portanto, vocês estarão entre os primeiros que serão levados para o cativeiro, e cessarão as festanças dos que gostam de se espreguiçar."

[[v30-6-8]]

^<<v30-6-8,8>>^ O Senhor  Deus jurou por si mesmo. O Senhor , o Deus dos Exércitos, diz: "Eu detesto o orgulho de Jacó e odeio os seus palácios. Abandonarei a cidade e tudo o que nela há."

[[v30-6-9]]

^<<v30-6-9,9>>^ Se numa casa ficarem dez homens, também esses morrerão.

[[v30-6-10]]

^<<v30-6-10,10>>^ E, se um parente chegado, o qual os há de queimar, pega os cadáveres para os levar para fora da casa e pergunta ao que estiver lá dentro: "Há mais alguém com você?" E este responder: "Não, não há"; então lhe dirá: "Cale-se! Não mencione o nome do Senhor ."

[[v30-6-11]]

^<<v30-6-11,11>>^ Pois eis que o Senhor  ordena, e será destroçada a casa grande, e a pequena será feita em pedaços.

[[v30-6-12]]

^<<v30-6-12,12>>^ "Será que os cavalos podem correr sobre as rochas? Será que é possível lavrá-las com bois? No entanto, vocês transformaram o juízo em veneno e o fruto da justiça, em alosna.

[[v30-6-13]]

^<<v30-6-13,13>>^ Vocês se alegram por terem conquistado Lo-Debar, e dizem: ‘Não é fato que, com as nossas próprias forças, nos apoderamos de Carnaim?’

[[v30-6-14]]

^<<v30-6-14,14>>^ Pois eis que trarei contra vocês, ó casa de Israel, uma nação que os oprimirá, desde a entrada de Hamate até o ribeiro da Arabá", diz o Senhor , o Deus dos Exércitos.

'''

xref:030-amos/030-amos-005.adoc#v30-5-0[&#60; Capítulo Anterior] | <<v30-6-0,Topo>> | xref:030-amos/030-amos-007.adoc#v30-7-0[Próximo Capítulo &#62;]