include::./index.adoc[]

[[v30-8-0]]
=== Amós, 8
// naa ?, NAA - Nova Almeida Atualizada

[[v30-8-1]]

^<<v30-8-1,1>>^ O Senhor  Deus também me mostrou o seguinte: um cesto de frutos de verão.

[[v30-8-2]]

^<<v30-8-2,2>>^ E perguntou: — O que você está vendo, Amós? E eu respondi: — Um cesto de frutos de verão. Então o Senhor  me disse: "Chegou o fim para o meu povo de Israel; não posso mais ignorar o que fazem.

[[v30-8-3]]

^<<v30-8-3,3>>^ Naquele dia", diz o Senhor  Deus, "os cânticos do templo serão gritos de dor. Muitos cadáveres! Cadáveres jogados por toda parte! Silêncio!"

[[v30-8-4]]

^<<v30-8-4,4>>^ Ouçam isto, vocês que pisam os necessitados e destroem os miseráveis da terra,

[[v30-8-5]]

^<<v30-8-5,5>>^ dizendo: "Quando passará a Festa da Lua Nova, para vendermos os cereais? E o sábado, para abrirmos os celeiros de trigo, diminuindo a quantidade, aumentando o peso e enganando com balanças desonestas,

[[v30-8-6]]

^<<v30-8-6,6>>^ para comprarmos os pobres por dinheiro e os necessitados por um par de sandálias e vendermos o refugo do trigo?"

[[v30-8-7]]

^<<v30-8-7,7>>^ O Senhor  jurou pela glória de Jacó, dizendo: "Nunca me esquecerei de nenhuma das suas obras!

[[v30-8-8]]

^<<v30-8-8,8>>^ Por causa disto, será que a terra não vai tremer? E não estarão enlutados todos os seus moradores? Toda a terra se levantará como o Nilo, será agitada e abaixará como o rio do Egito."

[[v30-8-9]]

^<<v30-8-9,9>>^ "Naquele dia", diz o Senhor  Deus, "farei com que o sol se ponha ao meio-dia e com que a terra se cubra de trevas em pleno dia.

[[v30-8-10]]

^<<v30-8-10,10>>^ Transformarei as suas festas em luto e todos os seus cânticos em lamentações. Vou fazer com que todos vistam roupas feitas de pano de saco e rapem a cabeça. Farei com que isso seja como luto por um filho único, luto cujo fim será como dia de amargura."

[[v30-8-11]]

^<<v30-8-11,11>>^ "Eis que vêm dias", diz o Senhor  Deus, "em que enviarei sobre a terra fome — não de pão, e sede — não de água, mas de ouvir as palavras do Senhor .

[[v30-8-12]]

^<<v30-8-12,12>>^ Andarão de mar a mar e do Norte até o Oriente; correrão por toda parte, procurando a palavra do Senhor , mas não a acharão.

[[v30-8-13]]

^<<v30-8-13,13>>^ Naquele dia, as moças bonitas e os jovens desmaiarão de sede,

[[v30-8-14]]

^<<v30-8-14,14>>^ os que agora juram pelo ídolo de Samaria e dizem: ‘Tão certo como vive o seu deus, ó Dã!’ E: ‘Tão certo como vive o culto de Berseba!’ Esses mesmos cairão e nunca mais se levantarão."

'''

xref:030-amos/030-amos-007.adoc#v30-7-0[&#60; Capítulo Anterior] | <<v30-8-0,Topo>> | xref:030-amos/030-amos-009.adoc#v30-9-0[Próximo Capítulo &#62;]