include::./index.adoc[]

[[v30-2-0]]
=== Amós, 2
// naa ?, NAA - Nova Almeida Atualizada

[[v30-2-1]]

^<<v30-2-1,1>>^ Assim diz o Senhor : "Por três transgressões de Moabe, sim, por causa de quatro, não suspenderei o castigo. Porque queimou os ossos do rei de Edom, até reduzi-los a cinza.

[[v30-2-2]]

^<<v30-2-2,2>>^ Por isso, porei fogo em Moabe, fogo que consumirá as fortalezas de Queriote. Moabe morrerá entre grande estrondo, alarido e som de trombeta.

[[v30-2-3]]

^<<v30-2-3,3>>^ Eliminarei do meio dele o juiz, e juntamente com ele matarei todos os seus príncipes", diz o Senhor .

[[v30-2-4]]

^<<v30-2-4,4>>^ Assim diz o Senhor : "Por três transgressões de Judá, sim, por causa de quatro, não suspenderei o castigo. Porque rejeitaram a lei do Senhor e não guardaram os seus estatutos. Os falsos deuses os enganaram, deuses que os pais deles haviam seguido.

[[v30-2-5]]

^<<v30-2-5,5>>^ Por isso, porei fogo em Judá, fogo que consumirá as fortalezas de Jerusalém."

[[v30-2-6]]

^<<v30-2-6,6>>^ Assim diz o Senhor : "Por três transgressões de Israel, sim, por causa de quatro, não suspenderei o castigo. Porque vendem o justo por dinheiro e condenam o necessitado por causa de um par de sandálias.

[[v30-2-7]]

^<<v30-2-7,7>>^ Esmagam no pó da terra a cabeça dos pobres e pervertem o caminho dos necessitados. Um homem e seu pai têm relações com a mesma jovem e, assim, profanam o meu santo nome.

[[v30-2-8]]

^<<v30-2-8,8>>^ Eles se deitam ao lado de qualquer altar sobre roupas recebidas como penhor e, no templo do seu deus, bebem o vinho dos que foram multados."

[[v30-2-9]]

^<<v30-2-9,9>>^ "Todavia, fui eu que destruí diante deles os amorreus, que eram tão altos como os cedros e tão fortes como os carvalhos; destruí os seus frutos por cima e as suas raízes por baixo.

[[v30-2-10]]

^<<v30-2-10,10>>^ Também fui eu que tirei vocês da terra do Egito e durante quarenta anos os conduzi pelo deserto, para que vocês pudessem tomar posse da terra dos amorreus.

[[v30-2-11]]

^<<v30-2-11,11>>^ Escolhi alguns dos seus filhos para serem profetas e alguns dos seus jovens para serem nazireus. Não é isto assim, filhos de Israel?" — diz o Senhor .

[[v30-2-12]]

^<<v30-2-12,12>>^ "Mas vocês deram vinho aos nazireus e ordenaram aos profetas que não profetizassem."

[[v30-2-13]]

^<<v30-2-13,13>>^ "Como faz um carro carregado de feixes, eu os esmagarei ali onde vocês se encontram.

[[v30-2-14]]

^<<v30-2-14,14>>^ Os mais ágeis não encontrarão refúgio, os fortes não poderão usar a sua força, e os valentes não conseguirão salvar a sua vida.

[[v30-2-15]]

^<<v30-2-15,15>>^ Os que manejam o arco não resistirão, os mais velozes não conseguirão fugir, e os que vão montados a cavalo não conseguirão salvar a sua vida.

[[v30-2-16]]

^<<v30-2-16,16>>^ Até mesmo os mais corajosos entre os valentes fugirão nus naquele dia", diz o Senhor .

'''

xref:030-amos/030-amos-001.adoc#v30-1-0[&#60; Capítulo Anterior] | <<v30-2-0,Topo>> | xref:030-amos/030-amos-003.adoc#v30-3-0[Próximo Capítulo &#62;]