include::./index.adoc[]

[[v30-3-0]]
=== Amós, 3
// naa ?, NAA - Nova Almeida Atualizada

[[v30-3-1]]

^<<v30-3-1,1>>^ Ouçam a palavra que o Senhor  fala contra vocês, filhos de Israel, contra toda a família que ele tirou da terra do Egito. Ele diz:

[[v30-3-2]]

^<<v30-3-2,2>>^ "De todas as famílias da terra, somente a vocês eu escolhi; portanto, eu os punirei por todas as suas iniquidades.

[[v30-3-3]]

^<<v30-3-3,3>>^ Será que dois andarão juntos, se não estiverem de acordo?

[[v30-3-4]]

^<<v30-3-4,4>>^ Será que o leão vai rugir na floresta, sem que tenha encontrado presa? Será que o leãozinho fará ouvir a sua voz no covil, se não tiver apanhado nada?

[[v30-3-5]]

^<<v30-3-5,5>>^ Será que a ave cairá na armadilha, se o laço não estiver armado? Será que o laço se levanta do chão, sem que tenha apanhado alguma coisa?

[[v30-3-6]]

^<<v30-3-6,6>>^ Será possível tocar a trombeta na cidade, sem que o povo comece a tremer? Será que sobrevirá algum mal à cidade, sem que o Senhor  o tenha feito?"

[[v30-3-7]]

^<<v30-3-7,7>>^ "Certamente o Senhor  Deus não fará coisa alguma, sem primeiro revelar o seu segredo aos seus servos, os profetas.

[[v30-3-8]]

^<<v30-3-8,8>>^ O leão rugiu, quem não ficará com medo? O Senhor  Deus falou, quem não profetizará?"

[[v30-3-9]]

^<<v30-3-9,9>>^ "Proclamem nas fortalezas de Asdode e nos palácios da terra do Egito o seguinte: ‘Reúnam-se nos montes de Samaria e vejam que grandes tumultos lá existem e que opressões há no meio dela.’

[[v30-3-10]]

^<<v30-3-10,10>>^ Porque o povo de Samaria não sabe fazer o que é reto", diz o Senhor , "e entesoura nos seus palácios a violência e a devastação."

[[v30-3-11]]

^<<v30-3-11,11>>^ Portanto, assim diz o Senhor  Deus: "Um inimigo cercará a sua terra, destruirá o seu poder, e os seus palácios serão saqueados."

[[v30-3-12]]

^<<v30-3-12,12>>^ Assim diz o Senhor : — Como o pastor livra da boca do leão as duas pernas ou um pedacinho da orelha de um animal, assim serão salvos os filhos de Israel que vivem em Samaria com apenas o canto da cama e parte do leito.

[[v30-3-13]]

^<<v30-3-13,13>>^ "Ouçam e deem testemunho contra a casa de Jacó", diz o Senhor  Deus, o Deus dos Exércitos:

[[v30-3-14]]

^<<v30-3-14,14>>^ "No dia em que eu punir Israel, por causa das suas transgressões, visitarei também os altares de Betel; e as pontas do altar serão cortadas e cairão por terra.

[[v30-3-15]]

^<<v30-3-15,15>>^ Derrubarei a casa de inverno com a casa de verão; as casas de marfim ficarão em ruínas, e as grandes casas serão destruídas", diz o Senhor .

'''

xref:030-amos/030-amos-002.adoc#v30-2-0[&#60; Capítulo Anterior] | <<v30-3-0,Topo>> | xref:030-amos/030-amos-004.adoc#v30-4-0[Próximo Capítulo &#62;]