include::./index.adoc[]

[[v66-20-0]]
=== Apocalipse, 20
// naa ?, NAA - Nova Almeida Atualizada

[[v66-20-1]]

^<<v66-20-1,1>>^ Então vi descer do céu um anjo que tinha na mão a chave do abismo e uma grande corrente.

[[v66-20-2]]

^<<v66-20-2,2>>^ Ele segurou o dragão, a antiga serpente, que é o diabo, Satanás, e o prendeu por mil anos.

[[v66-20-3]]

^<<v66-20-3,3>>^ Lançou-o no abismo, fechou-o e pôs selo sobre ele, para que não mais enganasse as nações até se completarem os mil anos. Depois disso, é necessário que ele seja solto por um pouco de tempo.

[[v66-20-4]]

^<<v66-20-4,4>>^ Vi também tronos, e nestes sentaram-se aqueles aos quais foi dada autoridade para julgar. Vi ainda as almas dos que foram decapitados por terem dado testemunho de Jesus e proclamado a palavra de Deus. Estes são os que não adoraram a besta nem a sua imagem, e não receberam a sua marca na testa e na mão; e viveram e reinaram com Cristo durante mil anos.

[[v66-20-5]]

^<<v66-20-5,5>>^ Os restantes dos mortos não reviveram até que se completassem os mil anos. Esta é a primeira ressurreição.

[[v66-20-6]]

^<<v66-20-6,6>>^ Bem-aventurado e santo é aquele que tem parte na primeira ressurreição. Sobre esses a segunda morte não tem poder; pelo contrário, serão sacerdotes de Deus e de Cristo e reinarão com ele os mil anos.

[[v66-20-7]]

^<<v66-20-7,7>>^ Quando, porém, se completarem os mil anos, Satanás será solto da sua prisão

[[v66-20-8]]

^<<v66-20-8,8>>^ e sairá para enganar as nações que estão nos quatro cantos da terra, Gogue e Magogue, a fim de reuni-las para a batalha. O número dessas é como a areia do mar.

[[v66-20-9]]

^<<v66-20-9,9>>^ Marcharam, então, pela superfície da terra e cercaram o acampamento dos santos e a cidade amada. Porém, desceu fogo do céu e os consumiu.

[[v66-20-10]]

^<<v66-20-10,10>>^ O diabo, que os tinha enganado, foi lançado no lago de fogo e enxofre, onde já se encontram a besta e o falso profeta; e serão atormentados de dia e de noite, para todo o sempre.

[[v66-20-11]]

^<<v66-20-11,11>>^ Vi um grande trono branco e aquele que está sentado nele. A terra e o céu fugiram da presença dele, e não se achou lugar para eles.

[[v66-20-12]]

^<<v66-20-12,12>>^ Vi também os mortos, os grandes e os pequenos, que estavam em pé diante do trono. Então foram abertos livros. Ainda outro livro, o Livro da Vida, foi aberto. E os mortos foram julgados, segundo as suas obras, conforme o que estava escrito nos livros.

[[v66-20-13]]

^<<v66-20-13,13>>^ O mar entregou os mortos que nele estavam. A morte e o inferno entregaram os mortos que neles havia. E foram julgados, um por um, segundo as suas obras.

[[v66-20-14]]

^<<v66-20-14,14>>^ Então a morte e o inferno foram lançados no lago de fogo. Esta é a segunda morte, o lago de fogo.

[[v66-20-15]]

^<<v66-20-15,15>>^ E, se alguém não foi achado inscrito no Livro da Vida, esse foi lançado no lago de fogo.

'''

xref:066-apocalipse/066-apocalipse-019.adoc#v66-19-0[&#60; Capítulo Anterior] | <<v66-20-0,Topo>> | xref:066-apocalipse/066-apocalipse-021.adoc#v66-21-0[Próximo Capítulo &#62;]