include::./index.adoc[]

[[v66-6-0]]
=== Apocalipse, 6
// naa ?, NAA - Nova Almeida Atualizada

[[v66-6-1]]

^<<v66-6-1,1>>^ Vi quando o Cordeiro quebrou o primeiro dos sete selos e ouvi um dos quatro seres viventes dizendo, como se fosse som de trovão: — Venha!

[[v66-6-2]]

^<<v66-6-2,2>>^ Vi, então, e eis um cavalo branco. O seu cavaleiro tinha um arco, e foi-lhe dada uma coroa. E ele saiu vencendo e para vencer.

[[v66-6-3]]

^<<v66-6-3,3>>^ Quando o Cordeiro quebrou o segundo selo, ouvi o segundo ser vivente dizendo: — Venha!

[[v66-6-4]]

^<<v66-6-4,4>>^ E saiu outro cavalo, que era vermelho. E ao seu cavaleiro foi dado poder para tirar a paz da terra e fazer com que os homens matassem uns aos outros. Também lhe foi dada uma grande espada.

[[v66-6-5]]

^<<v66-6-5,5>>^ Quando o Cordeiro quebrou o terceiro selo, ouvi o terceiro ser vivente dizendo: — Venha! Então olhei, e eis um cavalo preto e o seu cavaleiro com uma balança na mão.

[[v66-6-6]]

^<<v66-6-6,6>>^ E ouvi o que parecia uma voz no meio dos quatro seres viventes dizendo: — Uma medida de trigo por um denário; três medidas de cevada por um denário; e não danifique o azeite e o vinho.

[[v66-6-7]]

^<<v66-6-7,7>>^ Quando o Cordeiro quebrou o quarto selo, ouvi a voz do quarto ser vivente dizendo: — Venha!

[[v66-6-8]]

^<<v66-6-8,8>>^ Vi, então, e eis um cavalo amarelo. O seu cavaleiro se chamava Morte, e o inferno o estava seguindo. E lhes foi dada autoridade sobre a quarta parte da terra para matar à espada, pela fome, com a mortandade e por meio dos animais selvagens da terra.

[[v66-6-9]]

^<<v66-6-9,9>>^ Quando o Cordeiro quebrou o quinto selo, vi, debaixo do altar, as almas daqueles que tinham sido mortos por causa da palavra de Deus e por causa do testemunho que deram.

[[v66-6-10]]

^<<v66-6-10,10>>^ Clamaram com voz forte, dizendo: — Até quando, ó Soberano Senhor, santo e verdadeiro, não julgas, nem vingas o nosso sangue dos que habitam sobre a terra?

[[v66-6-11]]

^<<v66-6-11,11>>^ Então a cada um deles foi dada uma veste branca, e lhes foi pedido que repousassem ainda por pouco tempo, até que também se completasse o número dos seus conservos e seus irmãos que iam ser mortos como eles tinham sido.

[[v66-6-12]]

^<<v66-6-12,12>>^ Vi quando o Cordeiro quebrou o sexto selo. Houve um grande terremoto, o sol se tornou negro como pano de saco feito de crina, a lua ficou toda vermelha como sangue,

[[v66-6-13]]

^<<v66-6-13,13>>^ as estrelas do céu caíram sobre a terra, como a figueira deixa cair os seus figos verdes quando sacudida por um vento forte,

[[v66-6-14]]

^<<v66-6-14,14>>^ e o céu recolheu-se como um pergaminho quando se enrola. Então todos os montes e as ilhas foram movidos do seu lugar.

[[v66-6-15]]

^<<v66-6-15,15>>^ Os reis da terra, os grandes, os comandantes, os ricos, os poderosos e todo escravo e todo livre se esconderam nas cavernas e nos penhascos dos montes

[[v66-6-16]]

^<<v66-6-16,16>>^ e disseram aos montes e aos rochedos: — Caiam sobre nós e nos escondam da face daquele que está sentado no trono e da ira do Cordeiro!

[[v66-6-17]]

^<<v66-6-17,17>>^ Porque chegou o grande Dia da ira deles, e quem poderá subsistir?

'''

xref:066-apocalipse/066-apocalipse-005.adoc#v66-5-0[&#60; Capítulo Anterior] | <<v66-6-0,Topo>> | xref:066-apocalipse/066-apocalipse-007.adoc#v66-7-0[Próximo Capítulo &#62;]