include::./index.adoc[]

[[v66-5-0]]
=== Apocalipse, 5
// naa ?, NAA - Nova Almeida Atualizada

[[v66-5-1]]

^<<v66-5-1,1>>^ Vi, na mão direita daquele que estava sentado no trono, um livro em forma de rolo escrito por dentro e por fora, e selado com sete selos.

[[v66-5-2]]

^<<v66-5-2,2>>^ Vi, também, um anjo forte, que proclamava com voz forte: — Quem é digno de quebrar os selos e abrir o livro?

[[v66-5-3]]

^<<v66-5-3,3>>^ Ora, nem no céu, nem sobre a terra, nem debaixo da terra, ninguém podia abrir o livro, nem mesmo olhar para ele.

[[v66-5-4]]

^<<v66-5-4,4>>^ E eu chorava muito, porque ninguém foi achado digno de abrir o livro, nem mesmo de olhar para ele.

[[v66-5-5]]

^<<v66-5-5,5>>^ Então um dos anciãos me disse: — Não chore! Eis que o Leão da tribo de Judá, a Raiz de Davi, venceu para quebrar os sete selos e abrir o livro.

[[v66-5-6]]

^<<v66-5-6,6>>^ Então vi, no meio do trono e dos quatro seres viventes e entre os anciãos, em pé, um Cordeiro que parecia que tinha sido morto. Ele tinha sete chifres, bem como sete olhos, que são os sete espíritos de Deus enviados por toda a terra.

[[v66-5-7]]

^<<v66-5-7,7>>^ O Cordeiro foi e pegou o livro da mão direita daquele que estava sentado no trono.

[[v66-5-8]]

^<<v66-5-8,8>>^ E, quando ele pegou o livro, os quatro seres viventes e os vinte e quatro anciãos se prostraram diante do Cordeiro, tendo cada um deles uma harpa e taças de ouro cheias de incenso, que são as orações dos santos,

[[v66-5-9]]

^<<v66-5-9,9>>^ e cantavam um cântico novo, dizendo: "Digno és de pegar o livro e de quebrar os selos, porque foste morto e com o teu sangue compraste para Deus os que procedem de toda tribo, língua, povo e nação

[[v66-5-10]]

^<<v66-5-10,10>>^ e para o nosso Deus os constituíste reino e sacerdotes; e eles reinarão sobre a terra."

[[v66-5-11]]

^<<v66-5-11,11>>^ Vi e ouvi uma voz de muitos anjos ao redor do trono, dos seres viventes e dos anciãos, cujo número era de milhões de milhões e milhares de milhares,

[[v66-5-12]]

^<<v66-5-12,12>>^ proclamando com voz forte: "Digno é o Cordeiro que foi morto de receber o poder, a riqueza, a sabedoria, a força, a honra, a glória e o louvor."

[[v66-5-13]]

^<<v66-5-13,13>>^ Então ouvi que toda criatura que há no céu e sobre a terra, debaixo da terra e sobre o mar, e tudo o que neles há, estava dizendo: "Àquele que está sentado no trono e ao Cordeiro sejam o louvor, a honra, a glória e o domínio para todo o sempre."

[[v66-5-14]]

^<<v66-5-14,14>>^ E os quatro seres viventes respondiam: "Amém!" Também os anciãos se prostraram e adoraram.

'''

xref:066-apocalipse/066-apocalipse-004.adoc#v66-4-0[&#60; Capítulo Anterior] | <<v66-5-0,Topo>> | xref:066-apocalipse/066-apocalipse-006.adoc#v66-6-0[Próximo Capítulo &#62;]