include::./index.adoc[]

[[v66-11-0]]
=== Apocalipse, 11
// naa ?, NAA - Nova Almeida Atualizada

[[v66-11-1]]

^<<v66-11-1,1>>^ Foi-me dado um caniço semelhante a uma vara, e também me foi dito: — Levante-se e vá medir o santuário de Deus, o altar, e os que adoram no santuário.

[[v66-11-2]]

^<<v66-11-2,2>>^ Mas deixe de lado o átrio exterior do santuário e não o meça, porque esse átrio foi dado aos gentios, que, por quarenta e dois meses, pisarão a cidade santa.

[[v66-11-3]]

^<<v66-11-3,3>>^ Darei autoridade às minhas duas testemunhas para que profetizem durante mil duzentos e sessenta dias, vestidas de pano de saco.

[[v66-11-4]]

^<<v66-11-4,4>>^ São estas as duas oliveiras e os dois candelabros que estão em pé diante do Senhor da terra.

[[v66-11-5]]

^<<v66-11-5,5>>^ Se alguém pretende causar-lhes dano, da boca dessas testemunhas sai fogo e devora os inimigos; sim, se alguém pretender causar-lhes dano, certamente deve morrer.

[[v66-11-6]]

^<<v66-11-6,6>>^ Elas têm autoridade para fechar o céu, para que não chova durante os dias em que profetizarem. Têm autoridade também sobre as águas, para transformá-las em sangue, bem como para ferir a terra com todo tipo de flagelos, tantas vezes quantas quiserem.

[[v66-11-7]]

^<<v66-11-7,7>>^ Quando tiverem, então, concluído o testemunho que devem dar, a besta que surge do abismo fará guerra contra elas; a besta vencerá e matará as testemunhas.

[[v66-11-8]]

^<<v66-11-8,8>>^ E os seus cadáveres ficarão estirados na praça da grande cidade que, espiritualmente, se chama Sodoma e Egito, onde também o seu Senhor foi crucificado.

[[v66-11-9]]

^<<v66-11-9,9>>^ Então, muitos dentre os povos, tribos, línguas e nações contemplarão os cadáveres das duas testemunhas, por três dias e meio, e não permitirão que esses cadáveres sejam sepultados.

[[v66-11-10]]

^<<v66-11-10,10>>^ Os que habitam sobre a terra se alegrarão por causa da morte dessas duas testemunhas, realizarão festas e enviarão presentes uns aos outros, porque esses dois profetas atormentaram os que moram sobre a terra.

[[v66-11-11]]

^<<v66-11-11,11>>^ Mas, depois dos três dias e meio, entrou neles um espírito de vida vindo da parte de Deus, e eles se ergueram sobre os pés, e aqueles que os viram ficaram com muito medo.

[[v66-11-12]]

^<<v66-11-12,12>>^ E as duas testemunhas ouviram uma voz forte vinda do céu, dizendo-lhes: — Subam para cá. E subiram ao céu numa nuvem, e os seus inimigos as contemplaram.

[[v66-11-13]]

^<<v66-11-13,13>>^ Naquela hora, houve grande terremoto, e ruiu a décima parte da cidade. Nesse terremoto, morreram sete mil pessoas. As outras pessoas ficaram aterrorizadas e deram glória ao Deus do céu.

[[v66-11-14]]

^<<v66-11-14,14>>^ Passou o segundo ai. Eis que, sem demora, vem o terceiro ai.

[[v66-11-15]]

^<<v66-11-15,15>>^ O sétimo anjo tocou a trombeta, e houve no céu vozes fortes, dizendo: "O reino do mundo se tornou de nosso Senhor e do seu Cristo, e ele reinará para todo o sempre."

[[v66-11-16]]

^<<v66-11-16,16>>^ E os vinte e quatro anciãos que estavam sentados no seu trono, diante de Deus, prostraram-se sobre o seu rosto e adoraram a Deus,

[[v66-11-17]]

^<<v66-11-17,17>>^ dizendo: "Graças te damos, Senhor Deus, Todo-Poderoso, que és e que eras, porque assumiste o teu grande poder e passaste a reinar.

[[v66-11-18]]

^<<v66-11-18,18>>^ Na verdade, as nações se enfureceram; chegou, porém, a tua ira, e o tempo determinado para serem julgados os mortos, para se dar o galardão aos teus servos, os profetas, aos santos e aos que temem o teu nome, tanto aos pequenos como aos grandes, e para destruíres os que destroem a terra."

[[v66-11-19]]

^<<v66-11-19,19>>^ Abriu-se, então, o santuário de Deus, que se acha no céu, e foi vista a arca da sua aliança no seu santuário, e sobrevieram relâmpagos, vozes, trovões, terremoto e forte chuva de granizo.

'''

xref:066-apocalipse/066-apocalipse-010.adoc#v66-10-0[&#60; Capítulo Anterior] | <<v66-11-0,Topo>> | xref:066-apocalipse/066-apocalipse-012.adoc#v66-12-0[Próximo Capítulo &#62;]