include::./index.adoc[]

[[v66-14-0]]
=== Apocalipse, 14
// naa ?, NAA - Nova Almeida Atualizada

[[v66-14-1]]

^<<v66-14-1,1>>^ Olhei, e eis que o Cordeiro estava em pé sobre o monte Sião. Com ele estavam cento e quarenta e quatro mil, que tinham escrito na testa o nome do Cordeiro e o nome de seu Pai.

[[v66-14-2]]

^<<v66-14-2,2>>^ Ouvi uma voz do céu como som de muitas águas, como som de um forte trovão. A voz que ouvi era como de harpistas quando tocam as suas harpas.

[[v66-14-3]]

^<<v66-14-3,3>>^ Entoavam um cântico novo diante do trono, diante dos quatro seres viventes e dos anciãos. E ninguém podia aprender o cântico, senão os cento e quarenta e quatro mil que foram comprados da terra.

[[v66-14-4]]

^<<v66-14-4,4>>^ Estes são os que não se macularam com mulheres, porque são virgens. Eles seguem o Cordeiro por onde quer que ele vá. São os que foram comprados dentre todos os seres humanos, primícias para Deus e para o Cordeiro;

[[v66-14-5]]

^<<v66-14-5,5>>^ e não se achou mentira na sua boca; não têm mácula.

[[v66-14-6]]

^<<v66-14-6,6>>^ Vi outro anjo voando pelo meio do céu, tendo um evangelho eterno para pregar aos que habitam na terra, e a cada nação, tribo, língua e povo,

[[v66-14-7]]

^<<v66-14-7,7>>^ dizendo com voz forte: — Temam a Deus e deem glória a ele, pois é chegada a hora em que ele vai julgar. E adorem aquele que fez o céu, a terra, o mar e as fontes das águas.

[[v66-14-8]]

^<<v66-14-8,8>>^ Seguiu-se outro anjo, o segundo, dizendo: — Caiu! Caiu a grande Babilônia que fez com que todas as nações bebessem o vinho do furor da sua prostituição.

[[v66-14-9]]

^<<v66-14-9,9>>^ Seguiu-se a estes outro anjo, o terceiro, dizendo com voz forte: — Se alguém adora a besta e a sua imagem e recebe a sua marca na testa ou na mão,

[[v66-14-10]]

^<<v66-14-10,10>>^ também esse beberá do vinho do furor de Deus, preparado, sem mistura, no cálice da sua ira, e será atormentado com fogo e enxofre, diante dos santos anjos e na presença do Cordeiro.

[[v66-14-11]]

^<<v66-14-11,11>>^ A fumaça do seu tormento sobe para todo o sempre. E os adoradores da besta e da sua imagem e quem quer que receba a marca do nome da besta não têm descanso algum, nem de dia nem de noite.

[[v66-14-12]]

^<<v66-14-12,12>>^ Aqui está a perseverança dos santos, os que guardam os mandamentos de Deus e a fé em Jesus.

[[v66-14-13]]

^<<v66-14-13,13>>^ Então ouvi uma voz do céu, dizendo: — Escreva: "Bem-aventurados os mortos que, desde agora, morrem no Senhor." — Sim — diz o Espírito —, para que descansem das suas fadigas, pois as suas obras os acompanham.

[[v66-14-14]]

^<<v66-14-14,14>>^ Olhei, e eis uma nuvem branca, e sentado sobre a nuvem um semelhante a filho de homem, tendo na cabeça uma coroa de ouro e na mão uma foice afiada.

[[v66-14-15]]

^<<v66-14-15,15>>^ Outro anjo saiu do santuário, gritando com voz forte para aquele que estava sentado sobre a nuvem: — Pegue a sua foice e comece a colher, pois chegou a hora da colheita, visto que os campos da terra já amadureceram!

[[v66-14-16]]

^<<v66-14-16,16>>^ E aquele que estava sentado sobre a nuvem passou a sua foice sobre a terra e fez a colheita.

[[v66-14-17]]

^<<v66-14-17,17>>^ Então outro anjo saiu do santuário que se encontra no céu, tendo também ele uma foice afiada.

[[v66-14-18]]

^<<v66-14-18,18>>^ Ainda outro anjo saiu do altar, o anjo que tem autoridade sobre o fogo, e clamou com voz forte ao que tinha a foice afiada, dizendo: — Pegue a sua foice afiada e ajunte os cachos da videira da terra, porque as suas uvas estão maduras!

[[v66-14-19]]

^<<v66-14-19,19>>^ Então o anjo passou a sua foice na terra, ajuntou os cachos da videira da terra e os lançou no grande lagar da ira de Deus.

[[v66-14-20]]

^<<v66-14-20,20>>^ O lagar foi pisado fora da cidade. E correu sangue do lagar, chegando até a altura dos freios dos cavalos, numa extensão de cerca de trezentos quilômetros.

'''

xref:066-apocalipse/066-apocalipse-013.adoc#v66-13-0[&#60; Capítulo Anterior] | <<v66-14-0,Topo>> | xref:066-apocalipse/066-apocalipse-015.adoc#v66-15-0[Próximo Capítulo &#62;]