include::./index.adoc[]

[[v66-8-0]]
=== Apocalipse, 8
// naa ?, NAA - Nova Almeida Atualizada

[[v66-8-1]]

^<<v66-8-1,1>>^ Quando o Cordeiro quebrou o sétimo selo, houve silêncio no céu durante quase meia hora.

[[v66-8-2]]

^<<v66-8-2,2>>^ Então vi os sete anjos que estão em pé diante de Deus, e lhes foram dadas sete trombetas.

[[v66-8-3]]

^<<v66-8-3,3>>^ Veio outro anjo e ficou em pé junto ao altar, com um incensário de ouro, e lhe foi dado muito incenso para oferecê-lo com as orações de todos os santos sobre o altar de ouro que está diante do trono.

[[v66-8-4]]

^<<v66-8-4,4>>^ E da mão do anjo subiu à presença de Deus a fumaça do incenso, com as orações dos santos.

[[v66-8-5]]

^<<v66-8-5,5>>^ Então o anjo pegou o incensário, encheu-o do fogo do altar e o atirou à terra. E houve trovões, vozes, relâmpagos e terremoto.

[[v66-8-6]]

^<<v66-8-6,6>>^ Então os sete anjos que tinham as sete trombetas se prepararam para tocar.

[[v66-8-7]]

^<<v66-8-7,7>>^ O primeiro anjo tocou a trombeta, e houve granizo e fogo misturados com sangue, e foram atirados à terra. Então foi queimada a terça parte da terra, foi queimada a terça parte das árvores, e também toda a erva verde foi queimada.

[[v66-8-8]]

^<<v66-8-8,8>>^ O segundo anjo tocou a trombeta, e uma espécie de grande montanha em chamas foi atirada ao mar. Uma terça parte do mar se transformou em sangue,

[[v66-8-9]]

^<<v66-8-9,9>>^ e morreu a terça parte das criaturas do mar, e foi destruída a terça parte das embarcações.

[[v66-8-10]]

^<<v66-8-10,10>>^ O terceiro anjo tocou a trombeta, e uma grande estrela, queimando como uma tocha, caiu do céu sobre a terça parte dos rios e sobre as fontes das águas.

[[v66-8-11]]

^<<v66-8-11,11>>^ O nome da estrela é Absinto. E a terça parte das águas se transformou em absinto, e muitas pessoas morreram por causa dessas águas, porque se tornaram amargas.

[[v66-8-12]]

^<<v66-8-12,12>>^ O quarto anjo tocou a trombeta, e foi ferida a terça parte do sol, da lua e das estrelas, para que a terça parte deles escurecesse e uma terça parte do dia, e também da noite, ficasse sem luz.

[[v66-8-13]]

^<<v66-8-13,13>>^ Então vi e ouvi uma águia que, voando pelo meio do céu, dizia com voz forte: — Ai! Ai! Ai dos que moram na terra, por causa do som das outras trombetas que os três anjos ainda vão tocar!

'''

xref:066-apocalipse/066-apocalipse-007.adoc#v66-7-0[&#60; Capítulo Anterior] | <<v66-8-0,Topo>> | xref:066-apocalipse/066-apocalipse-009.adoc#v66-9-0[Próximo Capítulo &#62;]