include::./index.adoc[]

[[v66-21-0]]
=== Apocalipse, 21
// naa ?, NAA - Nova Almeida Atualizada

[[v66-21-1]]

^<<v66-21-1,1>>^ E vi novo céu e nova terra, pois o primeiro céu e a primeira terra passaram, e o mar já não existe.

[[v66-21-2]]

^<<v66-21-2,2>>^ Vi também a cidade santa, a nova Jerusalém, que descia do céu, da parte de Deus, preparada como uma noiva enfeitada para o seu noivo.

[[v66-21-3]]

^<<v66-21-3,3>>^ Então ouvi uma voz forte que vinha do trono e dizia: — Eis o tabernáculo de Deus com os seres humanos. Deus habitará com eles. Eles serão povos de Deus, e Deus mesmo estará com eles e será o Deus deles.

[[v66-21-4]]

^<<v66-21-4,4>>^ E lhes enxugará dos olhos toda lágrima. E já não existirá mais morte, já não haverá luto, nem pranto, nem dor, porque as primeiras coisas passaram.

[[v66-21-5]]

^<<v66-21-5,5>>^ E aquele que estava sentado no trono disse: — Eis que faço novas todas as coisas. E acrescentou: — Escreva, porque estas palavras são fiéis e verdadeiras.

[[v66-21-6]]

^<<v66-21-6,6>>^ Disse-me ainda: — Tudo está feito! Eu sou o Alfa e o Ômega, o Princípio e o Fim. Eu, a quem tem sede, darei de graça da fonte da água da vida.

[[v66-21-7]]

^<<v66-21-7,7>>^ O vencedor herdará estas coisas, e eu serei o Deus dele e ele será o meu filho.

[[v66-21-8]]

^<<v66-21-8,8>>^ Quanto, porém, aos covardes, aos incrédulos, aos abomináveis, aos assassinos, aos imorais, aos feiticeiros, aos idólatras e a todos os mentirosos, a parte que lhes cabe será no lago que está queimando com fogo e enxofre, a saber, a segunda morte.

[[v66-21-9]]

^<<v66-21-9,9>>^ Então veio um dos sete anjos que tinham as sete taças cheias dos últimos sete flagelos e falou comigo, dizendo: — Venha, vou mostrar-lhe a noiva, a esposa do Cordeiro.

[[v66-21-10]]

^<<v66-21-10,10>>^ E ele me levou, no Espírito, a uma grande e elevada montanha e me mostrou a cidade santa, Jerusalém, que descia do céu, da parte de Deus,

[[v66-21-11]]

^<<v66-21-11,11>>^ a qual tem a glória de Deus. O seu brilho era semelhante a uma pedra preciosíssima, como pedra de jaspe cristalina.

[[v66-21-12]]

^<<v66-21-12,12>>^ Tinha uma muralha grande e alta, com doze portões, e, junto aos portões, doze anjos. Sobre os portões estavam escritos nomes, a saber, os nomes das doze tribos dos filhos de Israel.

[[v66-21-13]]

^<<v66-21-13,13>>^ Três portões se achavam a leste, três, ao norte, três, ao sul, e três, a oeste.

[[v66-21-14]]

^<<v66-21-14,14>>^ A muralha da cidade tinha doze fundamentos, e sobre estes estavam os doze nomes dos doze apóstolos do Cordeiro.

[[v66-21-15]]

^<<v66-21-15,15>>^ Aquele que falava comigo tinha por medida uma vara de ouro para medir a cidade, os seus portões e a sua muralha.

[[v66-21-16]]

^<<v66-21-16,16>>^ A cidade tinha a forma de um quadrado, de comprimento e largura iguais. E mediu a cidade com a vara, e tinha doze mil estádios. O seu comprimento, largura e altura são iguais.

[[v66-21-17]]

^<<v66-21-17,17>>^ Mediu também a sua muralha, e tinha cento e quarenta e quatro côvados, pela medida humana que o anjo usava.

[[v66-21-18]]

^<<v66-21-18,18>>^ A muralha é feita de jaspe e a cidade é de ouro puro, semelhante a vidro límpido.

[[v66-21-19]]

^<<v66-21-19,19>>^ Os alicerces da muralha da cidade estão enfeitados de todo tipo de pedras preciosas. O primeiro alicerce é de jaspe; o segundo, de safira; o terceiro, de calcedônia; o quarto, de esmeralda;

[[v66-21-20]]

^<<v66-21-20,20>>^ o quinto, de sardônio; o sexto, de sárdio; o sétimo, de crisólito; o oitavo, de berilo; o nono, de topázio; o décimo, de crisópraso; o décimo primeiro, de jacinto; e o décimo segundo, de ametista.

[[v66-21-21]]

^<<v66-21-21,21>>^ Os doze portões são doze pérolas, e cada um desses portões é feito de uma só pérola. A praça da cidade é de ouro puro, como vidro transparente.

[[v66-21-22]]

^<<v66-21-22,22>>^ Não vi nenhum santuário na cidade, porque o seu santuário é o Senhor, o Deus Todo-Poderoso, e o Cordeiro.

[[v66-21-23]]

^<<v66-21-23,23>>^ A cidade não precisa do sol nem da lua para lhe dar claridade, pois a glória de Deus a ilumina, e o Cordeiro é a sua lâmpada.

[[v66-21-24]]

^<<v66-21-24,24>>^ As nações andarão mediante a sua luz, e os reis da terra lhe trazem a sua glória.

[[v66-21-25]]

^<<v66-21-25,25>>^ Os seus portões jamais se fecharão de dia, pois nela não haverá noite.

[[v66-21-26]]

^<<v66-21-26,26>>^ E lhe trarão a glória e a honra das nações.

[[v66-21-27]]

^<<v66-21-27,27>>^ Nela não entrará nada que seja impuro, nem o que pratica abominação e mentira, mas somente os inscritos no Livro da Vida do Cordeiro.

'''

xref:066-apocalipse/066-apocalipse-020.adoc#v66-20-0[&#60; Capítulo Anterior] | <<v66-21-0,Topo>> | xref:066-apocalipse/066-apocalipse-022.adoc#v66-22-0[Próximo Capítulo &#62;]