include::./index.adoc[]

[[v66-17-0]]
=== Apocalipse, 17
// naa ?, NAA - Nova Almeida Atualizada

[[v66-17-1]]

^<<v66-17-1,1>>^ Um dos sete anjos que tinham as sete taças veio e falou comigo, dizendo: — Venha! Vou lhe mostrar o julgamento da grande prostituta que está sentada sobre muitas águas.

[[v66-17-2]]

^<<v66-17-2,2>>^ Os reis da terra se prostituíram com ela, e os que habitam na terra se embriagaram com o vinho da sua prostituição.

[[v66-17-3]]

^<<v66-17-3,3>>^ O anjo me transportou, no Espírito, a um deserto, e vi uma mulher montada numa besta escarlate, besta repleta de nomes de blasfêmia, com sete cabeças e dez chifres.

[[v66-17-4]]

^<<v66-17-4,4>>^ A mulher estava vestida de púrpura e de escarlate, enfeitada com ouro, pedras preciosas e pérolas, tendo na mão um cálice de ouro transbordante de abominações e das imundícias da sua prostituição.

[[v66-17-5]]

^<<v66-17-5,5>>^ Na sua testa estava escrito um nome, um mistério: " Babilônia, a Grande, a Mãe das Prostitutas e das Abominações da Terra ".

[[v66-17-6]]

^<<v66-17-6,6>>^ Então vi a mulher embriagada com o sangue dos santos e com o sangue das testemunhas de Jesus. E, quando a vi, admirei-me com grande espanto.

[[v66-17-7]]

^<<v66-17-7,7>>^ O anjo, porém, me disse: — Por que você ficou admirado? Vou lhe explicar o mistério da mulher e da besta que tem as sete cabeças e os dez chifres e que leva a mulher:

[[v66-17-8]]

^<<v66-17-8,8>>^ a besta que você viu era e não é mais, e está para emergir do abismo, e caminha para a destruição. E aqueles que habitam sobre a terra, cujos nomes não foram escritos no Livro da Vida desde a fundação do mundo, se admirarão, vendo a besta que era e não é mais, mas tornará a aparecer.

[[v66-17-9]]

^<<v66-17-9,9>>^ — Aqui está a mente que tem sabedoria: as sete cabeças são sete montes, nos quais a mulher está sentada. São também sete reis,

[[v66-17-10]]

^<<v66-17-10,10>>^ dos quais cinco caíram, um existe e o outro ainda não chegou; e, quando chegar, tem de durar pouco tempo.

[[v66-17-11]]

^<<v66-17-11,11>>^ E a besta, que era e não é mais, é também o oitavo rei, mas faz parte dos sete, e caminha para a destruição.

[[v66-17-12]]

^<<v66-17-12,12>>^ — Os dez chifres que você viu são dez reis, que ainda não receberam reino, mas recebem autoridade como reis, com a besta, durante uma hora.

[[v66-17-13]]

^<<v66-17-13,13>>^ Estes têm um mesmo propósito e oferecem à besta o poder e a autoridade que possuem.

[[v66-17-14]]

^<<v66-17-14,14>>^ Lutarão contra o Cordeiro, e o Cordeiro os vencerá, pois é o Senhor dos senhores e o Rei dos reis; serão vencedores também os chamados, eleitos e fiéis que estão com o Cordeiro.

[[v66-17-15]]

^<<v66-17-15,15>>^ O anjo disse ainda: — As águas que você viu, onde a prostituta está sentada, são povos, multidões, nações e línguas.

[[v66-17-16]]

^<<v66-17-16,16>>^ Os dez chifres que você viu e a besta, esses odiarão a prostituta. Eles a deixarão devastada e nua, comerão as carnes dela, e a queimarão no fogo.

[[v66-17-17]]

^<<v66-17-17,17>>^ Porque Deus incutiu no coração deles que realizem o seu propósito, executem-no de comum acordo e deem à besta o reino que possuem, até que se cumpram as palavras de Deus.

[[v66-17-18]]

^<<v66-17-18,18>>^ — A mulher que você viu é a grande cidade que domina sobre os reis da terra.

'''

xref:066-apocalipse/066-apocalipse-016.adoc#v66-16-0[&#60; Capítulo Anterior] | <<v66-17-0,Topo>> | xref:066-apocalipse/066-apocalipse-018.adoc#v66-18-0[Próximo Capítulo &#62;]