include::./index.adoc[]

[[v66-9-0]]
=== Apocalipse, 9
// naa ?, NAA - Nova Almeida Atualizada

[[v66-9-1]]

^<<v66-9-1,1>>^ O quinto anjo tocou a trombeta, e vi uma estrela que tinha caído do céu sobre a terra. E lhe foi dada a chave do poço do abismo.

[[v66-9-2]]

^<<v66-9-2,2>>^ Ela abriu o poço do abismo, e dele saiu fumaça como a fumaça de uma grande fornalha. E o sol e o ar se escureceram com a fumaça saída do poço.

[[v66-9-3]]

^<<v66-9-3,3>>^ Também da fumaça saíram gafanhotos para a terra; e lhes foi dado poder como o poder que têm os escorpiões da terra.

[[v66-9-4]]

^<<v66-9-4,4>>^ E lhes foi dito que não causassem dano à erva da terra, nem a qualquer coisa verde, nem a árvore alguma, e tão somente às pessoas que não têm o selo de Deus na testa.

[[v66-9-5]]

^<<v66-9-5,5>>^ Também não lhes foi permitido que os matassem, mas que os atormentassem durante cinco meses. E o seu tormento era como tormento de escorpião quando fere alguém.

[[v66-9-6]]

^<<v66-9-6,6>>^ Naqueles dias, as pessoas buscarão a morte e não a encontrarão; também terão desejo de morrer, mas a morte fugirá delas.

[[v66-9-7]]

^<<v66-9-7,7>>^ O aspecto dos gafanhotos era semelhante a cavalos preparados para a batalha. Na cabeça deles havia como que coroas parecendo de ouro, e o rosto deles era como rosto de um ser humano.

[[v66-9-8]]

^<<v66-9-8,8>>^ Tinham também cabelos, como cabelos de mulher; e os dentes eram como dentes de leão.

[[v66-9-9]]

^<<v66-9-9,9>>^ Tinham couraças, como couraças de ferro. O barulho que as suas asas faziam era como o barulho de carros puxados por muitos cavalos, quando correm para a batalha.

[[v66-9-10]]

^<<v66-9-10,10>>^ Tinham ainda cauda, como escorpiões, e um ferrão. Na cauda tinham poder para causar dano às pessoas, por cinco meses.

[[v66-9-11]]

^<<v66-9-11,11>>^ Tinham por rei sobre eles o anjo do abismo, cujo nome em hebraico é Abadom, e em grego, Apoliom.

[[v66-9-12]]

^<<v66-9-12,12>>^ O primeiro ai passou. Eis que, depois destas coisas, vêm ainda dois ais.

[[v66-9-13]]

^<<v66-9-13,13>>^ O sexto anjo tocou a trombeta, e ouvi uma voz que vinha das quatro pontas do altar de ouro que se encontra na presença de Deus,

[[v66-9-14]]

^<<v66-9-14,14>>^ dizendo ao sexto anjo, o mesmo que tem a trombeta: — Solte os quatro anjos que estão amarrados junto ao grande rio Eufrates.

[[v66-9-15]]

^<<v66-9-15,15>>^ Então foram soltos os quatro anjos que se achavam preparados para a hora, o dia, o mês e o ano, para que matassem a terça parte da humanidade.

[[v66-9-16]]

^<<v66-9-16,16>>^ O número dos exércitos da cavalaria era de vinte mil vezes dez milhares; eu ouvi o seu número.

[[v66-9-17]]

^<<v66-9-17,17>>^ Assim, nesta visão, pude ver que os cavalos e os seus cavaleiros tinham couraças cor de fogo, de jacinto e de enxofre. A cabeça dos cavalos era como cabeça de leão, e de sua boca saíam fogo, fumaça e enxofre.

[[v66-9-18]]

^<<v66-9-18,18>>^ Por meio destes três flagelos, a saber, pelo fogo, pela fumaça e pelo enxofre que saíam da boca dos cavalos, foi morta a terça parte da humanidade.

[[v66-9-19]]

^<<v66-9-19,19>>^ Pois a força dos cavalos estava na boca e na cauda deles. As caudas deles eram semelhantes a serpentes, com cabeças, e com elas causavam dano.

[[v66-9-20]]

^<<v66-9-20,20>>^ O resto da humanidade, isto é, aqueles que não foram mortos por esses flagelos, não se arrependeu das obras das suas mãos: eles não deixaram de adorar os demônios e os ídolos de ouro, de prata, de bronze, de pedra e de madeira, que não podem ver, nem ouvir, nem andar.

[[v66-9-21]]

^<<v66-9-21,21>>^ Também não se arrependeram dos seus homicídios, nem das suas feitiçarias, nem da sua imoralidade sexual, nem dos seus furtos.

'''

xref:066-apocalipse/066-apocalipse-008.adoc#v66-8-0[&#60; Capítulo Anterior] | <<v66-9-0,Topo>> | xref:066-apocalipse/066-apocalipse-010.adoc#v66-10-0[Próximo Capítulo &#62;]