include::./index.adoc[]

[[v66-7-0]]
=== Apocalipse, 7
// naa ?, NAA - Nova Almeida Atualizada

[[v66-7-1]]

^<<v66-7-1,1>>^ Depois disso, vi quatro anjos em pé nos quatro cantos da terra, segurando os quatro ventos da terra, para que nenhum vento soprasse sobre a terra, nem sobre o mar, nem sobre árvore alguma.

[[v66-7-2]]

^<<v66-7-2,2>>^ Vi outro anjo que subia do nascente do sol, tendo o selo do Deus vivo. Ele gritou com voz bem forte aos quatro anjos, aqueles que tinham recebido poder para causar dano à terra e ao mar,

[[v66-7-3]]

^<<v66-7-3,3>>^ dizendo: — Não danifiquem nem a terra, nem o mar, nem as árvores, até marcarmos com um selo a testa dos servos do nosso Deus.

[[v66-7-4]]

^<<v66-7-4,4>>^ Então ouvi o número dos que foram marcados com selo. Eram cento e quarenta e quatro mil, de todas as tribos dos filhos de Israel.

[[v66-7-5]]

^<<v66-7-5,5>>^ Da tribo de Judá foram marcados com selo doze mil; da tribo de Rúben, doze mil; da tribo de Gade, doze mil;

[[v66-7-6]]

^<<v66-7-6,6>>^ da tribo de Aser, doze mil; da tribo de Naftali, doze mil; da tribo de Manassés, doze mil;

[[v66-7-7]]

^<<v66-7-7,7>>^ da tribo de Simeão, doze mil; da tribo de Levi, doze mil; da tribo de Issacar, doze mil;

[[v66-7-8]]

^<<v66-7-8,8>>^ da tribo de Zebulom, doze mil; da tribo de José, doze mil; da tribo de Benjamim foram marcados com selo doze mil.

[[v66-7-9]]

^<<v66-7-9,9>>^ Depois destas coisas, vi, e eis grande multidão que ninguém podia contar, de todas as nações, tribos, povos e línguas, em pé diante do trono e diante do Cordeiro, vestidos de vestes brancas, com ramos de palmeira nas mãos.

[[v66-7-10]]

^<<v66-7-10,10>>^ E clamavam com voz forte, dizendo: "Ao nosso Deus, que está sentado no trono, e ao Cordeiro, pertence a salvação."

[[v66-7-11]]

^<<v66-7-11,11>>^ Todos os anjos estavam em pé rodeando o trono, os anciãos e os quatro seres viventes, e diante do trono se prostraram sobre o seu rosto, e adoraram a Deus,

[[v66-7-12]]

^<<v66-7-12,12>>^ dizendo: "Amém! O louvor, a glória, a sabedoria, as ações de graças, a honra, o poder e a força sejam ao nosso Deus, para todo o sempre. Amém!"

[[v66-7-13]]

^<<v66-7-13,13>>^ Um dos anciãos tomou a palavra e me perguntou: — Quem são e de onde vieram estes que estão vestidos de branco?

[[v66-7-14]]

^<<v66-7-14,14>>^ Respondi: — O senhor sabe. Então ele me disse: — Estes são os que vêm da grande tribulação, que lavaram suas vestes e as alvejaram no sangue do Cordeiro.

[[v66-7-15]]

^<<v66-7-15,15>>^ Por isso, estão diante do trono de Deus e o adoram de dia e de noite no seu santuário. E aquele que está sentado no trono estenderá sobre eles o seu tabernáculo.

[[v66-7-16]]

^<<v66-7-16,16>>^ Jamais terão fome, nunca mais terão sede, não cairá sobre eles o sol, nem qualquer outro calor forte,

[[v66-7-17]]

^<<v66-7-17,17>>^ pois o Cordeiro que está no meio do trono os apascentará e os guiará para as fontes da água da vida. E Deus lhes enxugará dos olhos toda lágrima.

'''

xref:066-apocalipse/066-apocalipse-006.adoc#v66-6-0[&#60; Capítulo Anterior] | <<v66-7-0,Topo>> | xref:066-apocalipse/066-apocalipse-008.adoc#v66-8-0[Próximo Capítulo &#62;]