include::./index.adoc[]

[[v66-19-0]]
=== Apocalipse, 19
// naa ?, NAA - Nova Almeida Atualizada

[[v66-19-1]]

^<<v66-19-1,1>>^ Depois destas coisas, ouvi no céu o que parecia ser a voz forte de uma grande multidão, dizendo: "Aleluia! A salvação, a glória e o poder são do nosso Deus,

[[v66-19-2]]

^<<v66-19-2,2>>^ porque verdadeiros e justos são os seus juízos, pois julgou a grande prostituta que corrompia a terra com a sua prostituição e das mãos dela vingou o sangue dos seus servos."

[[v66-19-3]]

^<<v66-19-3,3>>^ E disseram pela segunda vez: "Aleluia! E a sua fumaça sobe para todo o sempre."

[[v66-19-4]]

^<<v66-19-4,4>>^ Os vinte e quatro anciãos e os quatro seres viventes se prostraram e adoraram a Deus, que está sentado no trono, dizendo: "Amém! Aleluia!"

[[v66-19-5]]

^<<v66-19-5,5>>^ E do trono saiu uma voz, que dizia: "Louvem o nosso Deus, todos vocês, os seus servos, todos os que o temem, os pequenos e os grandes."

[[v66-19-6]]

^<<v66-19-6,6>>^ Então ouvi o que parecia ser a voz de uma grande multidão, uma voz como de muitas águas e como de fortes trovões, dizendo: "Aleluia! Pois reina o Senhor, nosso Deus, o Todo-Poderoso.

[[v66-19-7]]

^<<v66-19-7,7>>^ Alegremo-nos, exultemos e demos-lhe a glória, porque chegou a hora das bodas do Cordeiro, e a noiva dele já se preparou.

[[v66-19-8]]

^<<v66-19-8,8>>^ A ela foi permitido vestir-se de linho finíssimo, resplandecente e puro." Porque o linho finíssimo são os atos de justiça dos santos.

[[v66-19-9]]

^<<v66-19-9,9>>^ Então o anjo me disse: — Escreva: "Bem-aventurados aqueles que são chamados à ceia das bodas do Cordeiro." E acrescentou: — São estas as verdadeiras palavras de Deus.

[[v66-19-10]]

^<<v66-19-10,10>>^ Prostrei-me diante dos seus pés para adorá-lo. O anjo, porém, me disse: — Não faça isso! Sou um servo de Deus, assim como são você e os seus irmãos que guardam o testemunho de Jesus. Adore a Deus! Pois o testemunho de Jesus é o espírito da profecia.

[[v66-19-11]]

^<<v66-19-11,11>>^ Vi o céu aberto, e eis um cavalo branco. O seu cavaleiro se chama Fiel e Verdadeiro e julga e combate com justiça.

[[v66-19-12]]

^<<v66-19-12,12>>^ Os seus olhos são como chama de fogo; na cabeça dele há muitos diademas; tem um nome escrito que ninguém conhece, a não ser ele mesmo.

[[v66-19-13]]

^<<v66-19-13,13>>^ Está vestido com um manto encharcado de sangue, e o seu nome é "Verbo de Deus".

[[v66-19-14]]

^<<v66-19-14,14>>^ Os exércitos do céu o seguiam, montados em cavalos brancos e vestidos de linho finíssimo, branco e puro.

[[v66-19-15]]

^<<v66-19-15,15>>^ Da sua boca sai uma espada afiada, para com ela ferir as nações. Ele mesmo as regerá com cetro de ferro e ele mesmo é o que pisa o lagar do vinho do furor da ira do Deus Todo-Poderoso.

[[v66-19-16]]

^<<v66-19-16,16>>^ No seu manto e na sua coxa está escrito um nome: " Rei dos reis e Senhor dos senhores ".

[[v66-19-17]]

^<<v66-19-17,17>>^ Então vi um anjo posto em pé no sol. Ele gritou com voz forte, dizendo a todas as aves que voam pelo meio do céu: — Venham, reúnam-se para a grande ceia de Deus,

[[v66-19-18]]

^<<v66-19-18,18>>^ para comer carne de reis, carne de comandantes, carne de poderosos, carne de cavalos e seus cavaleiros, carne de todos, quer livres, quer escravos, tanto pequenos como grandes.

[[v66-19-19]]

^<<v66-19-19,19>>^ E vi a besta e os reis da terra, com os seus exércitos, reunidos para fazer guerra contra aquele que estava montado no cavalo e contra o seu exército.

[[v66-19-20]]

^<<v66-19-20,20>>^ Mas a besta foi presa, e com ela foi preso o falso profeta que, com os sinais feitos diante da besta, seduziu aqueles que receberam a marca da besta e eram os adoradores da sua imagem. Os dois foram lançados vivos dentro do lago de fogo que queima com enxofre.

[[v66-19-21]]

^<<v66-19-21,21>>^ Os outros foram mortos com a espada que saía da boca daquele que estava montado no cavalo. E todas as aves se fartaram das suas carnes.

'''

xref:066-apocalipse/066-apocalipse-018.adoc#v66-18-0[&#60; Capítulo Anterior] | <<v66-19-0,Topo>> | xref:066-apocalipse/066-apocalipse-020.adoc#v66-20-0[Próximo Capítulo &#62;]