include::./index.adoc[]

[[v66-1-0]]
=== Apocalipse, 1
// naa ?, NAA - Nova Almeida Atualizada

[[v66-1-1]]

^<<v66-1-1,1>>^ Revelação de Jesus Cristo, a qual Deus lhe deu para mostrar aos seus servos as coisas que em breve devem acontecer e que ele, enviando o seu anjo, deu a conhecer ao seu servo João,

[[v66-1-2]]

^<<v66-1-2,2>>^ que atestou a palavra de Deus e o testemunho de Jesus Cristo, quanto a tudo o que viu.

[[v66-1-3]]

^<<v66-1-3,3>>^ Bem-aventurado aquele que lê, e bem-aventurados aqueles que ouvem as palavras da profecia e guardam as coisas nela escritas, pois o tempo está próximo.

[[v66-1-4]]

^<<v66-1-4,4>>^ João, às sete igrejas que estão na província da Ásia: Que a graça e a paz estejam com vocês, da parte daquele que é, que era e que há de vir, da parte dos sete espíritos que estão diante do seu trono

[[v66-1-5]]

^<<v66-1-5,5>>^ e da parte de Jesus Cristo, a Fiel Testemunha, o Primogênito dos mortos e o Soberano dos reis da terra. Àquele que nos ama e, pelo seu sangue, nos libertou dos nossos pecados,

[[v66-1-6]]

^<<v66-1-6,6>>^ e nos constituiu reino, sacerdotes para o seu Deus e Pai, a ele a glória e o domínio para todo o sempre. Amém!

[[v66-1-7]]

^<<v66-1-7,7>>^ Eis que ele vem com as nuvens, e todo olho o verá, até mesmo aqueles que o traspassaram. E todas as tribos da terra se lamentarão por causa dele. Certamente. Amém!

[[v66-1-8]]

^<<v66-1-8,8>>^ "Eu sou o Alfa e o Ômega", diz o Senhor Deus, "aquele que é, que era e que há de vir, o Todo-Poderoso."

[[v66-1-9]]

^<<v66-1-9,9>>^ Eu, João, irmão e companheiro de vocês na tribulação, no reino e na perseverança em Jesus, estava na ilha chamada Patmos, por causa da palavra de Deus e do testemunho de Jesus.

[[v66-1-10]]

^<<v66-1-10,10>>^ Achei-me no Espírito, no dia do Senhor, e ouvi atrás de mim uma voz forte, como de trombeta,

[[v66-1-11]]

^<<v66-1-11,11>>^ dizendo: — Escreva num livro o que você vê e mande-o às sete igrejas: Éfeso, Esmirna, Pérgamo, Tiatira, Sardes, Filadélfia e Laodiceia.

[[v66-1-12]]

^<<v66-1-12,12>>^ Voltei-me para ver quem falava comigo e, ao me voltar, vi sete candelabros de ouro

[[v66-1-13]]

^<<v66-1-13,13>>^ e, no meio dos candelabros, um semelhante a um filho de homem, com vestes talares e cingido, à altura do peito, com um cinto de ouro.

[[v66-1-14]]

^<<v66-1-14,14>>^ A cabeça e os cabelos dele eram brancos como alva lã, como neve. Os olhos eram como chama de fogo.

[[v66-1-15]]

^<<v66-1-15,15>>^ Os seus pés eram semelhantes ao bronze polido, como que refinado numa fornalha. A voz era como som de muitas águas.

[[v66-1-16]]

^<<v66-1-16,16>>^ Na mão direita ele tinha sete estrelas, e da sua boca saía uma afiada espada de dois gumes. O seu rosto brilhava como o sol na sua força.

[[v66-1-17]]

^<<v66-1-17,17>>^ Ao vê-lo, caí aos seus pés como morto. Porém ele pôs sobre mim a mão direita, dizendo: — Não tenha medo. Eu sou o primeiro e o último

[[v66-1-18]]

^<<v66-1-18,18>>^ e aquele que vive. Estive morto, mas eis que estou vivo para todo o sempre e tenho as chaves da morte e do inferno.

[[v66-1-19]]

^<<v66-1-19,19>>^ Escreva, pois, as coisas que você viu, as que são e as que hão de acontecer depois destas.

[[v66-1-20]]

^<<v66-1-20,20>>^ Quanto ao mistério das sete estrelas que você viu na minha mão direita e quanto aos sete candelabros de ouro, as sete estrelas são os anjos das sete igrejas, e os sete candelabros são as sete igrejas.

'''

xref:065-judas/065-judas-001.adoc#v65-1-0[&#60; Capítulo Anterior] | <<v66-1-0,Topo>> | xref:066-apocalipse/066-apocalipse-002.adoc#v66-2-0[Próximo Capítulo &#62;]