include::./index.adoc[]

[[v66-18-0]]
=== Apocalipse, 18
// naa ?, NAA - Nova Almeida Atualizada

[[v66-18-1]]

^<<v66-18-1,1>>^ Depois destas coisas, vi descer do céu outro anjo, que tinha grande autoridade, e a terra se iluminou com a sua glória.

[[v66-18-2]]

^<<v66-18-2,2>>^ Então exclamou com potente voz, dizendo: — Caiu! Caiu a grande Babilônia! Ela se tornou morada de demônios, refúgio de toda espécie de espírito imundo e esconderijo de todo tipo de ave imunda e detestável,

[[v66-18-3]]

^<<v66-18-3,3>>^ pois todas as nações beberam do vinho do furor da sua prostituição. Com ela se prostituíram os reis da terra. Também os mercadores da terra se enriqueceram à custa da sua luxúria.

[[v66-18-4]]

^<<v66-18-4,4>>^ Ouvi outra voz do céu, dizendo: "Saiam dela, povo meu, para que vocês não sejam cúmplices em seus pecados e para que os seus flagelos não caiam sobre vocês.

[[v66-18-5]]

^<<v66-18-5,5>>^ Porque os pecados dela se acumularam até o céu, e Deus se lembrou das injustiças que ela praticou.

[[v66-18-6]]

^<<v66-18-6,6>>^ Retribuam-lhe como também ela retribuiu, paguem-lhe em dobro segundo as suas obras e, no cálice em que ela misturou bebidas, misturem dobrado para ela.

[[v66-18-7]]

^<<v66-18-7,7>>^ O quanto a si mesma glorificou e viveu em luxúria, deem a ela em igual medida tormento e pranto. Porque ela pensa assim: ‘Estou sentada como rainha. Não sou viúva. Nunca saberei o que é pranto!’

[[v66-18-8]]

^<<v66-18-8,8>>^ Por isso, em um só dia sobrevirão os seus flagelos: morte, pranto e fome; e será queimada no fogo, porque poderoso é o Senhor Deus, que a julga."

[[v66-18-9]]

^<<v66-18-9,9>>^ Os reis da terra, que com ela se prostituíram e viveram em luxúria, vão chorar e se lamentar por causa dela, quando virem a fumaça do seu incêndio.

[[v66-18-10]]

^<<v66-18-10,10>>^ E, conservando-se de longe, com medo do seu tormento, dizem: "Ai! Ai de você, grande cidade, Babilônia, cidade poderosa! Pois em uma só hora chegou o seu juízo."

[[v66-18-11]]

^<<v66-18-11,11>>^ E, por causa dela, choram e pranteiam os mercadores da terra, porque ninguém mais compra a sua mercadoria,

[[v66-18-12]]

^<<v66-18-12,12>>^ mercadoria de ouro, de prata, de pedras preciosas, de pérolas, de linho finíssimo, de púrpura, de seda, de escarlate; e toda espécie de madeira odorífera, todo gênero de objeto de marfim, toda qualidade de móvel de madeira cara, de bronze, de ferro e de mármore;

[[v66-18-13]]

^<<v66-18-13,13>>^ e canela de cheiro, especiarias, incenso, perfume, mirra, vinho, azeite, boa farinha, trigo, gado e ovelhas; e de cavalos, de carruagens, de escravos e até almas humanas.

[[v66-18-14]]

^<<v66-18-14,14>>^ Eles dizem: "O fruto que tanto lhe apeteceu se afastou de você, e para você se extinguiu tudo o que é delicado e esplêndido, e nunca mais serão achados."

[[v66-18-15]]

^<<v66-18-15,15>>^ Os mercadores destas coisas, que, por meio dela, se enriqueceram, ficarão de longe, com medo do seu tormento, chorando e pranteando,

[[v66-18-16]]

^<<v66-18-16,16>>^ dizendo: "Ai! Ai da grande cidade, que estava vestida de linho finíssimo, de púrpura e de escarlate, enfeitada com ouro, pedras preciosas e pérolas,

[[v66-18-17]]

^<<v66-18-17,17>>^ porque em uma só hora ficou devastada tamanha riqueza!" E todos os pilotos, e todos aqueles que viajam pelo mar, e marinheiros, e os que ganham a vida no mar ficaram de longe.

[[v66-18-18]]

^<<v66-18-18,18>>^ Então, vendo a fumaça do seu incêndio, gritavam: — Que cidade se compara à grande cidade?

[[v66-18-19]]

^<<v66-18-19,19>>^ Lançaram pó sobre a cabeça e, chorando e pranteando, gritavam: "Ai! Ai da grande cidade, na qual se enriqueceram todos os que possuíam navios no mar, à custa da sua riqueza, porque em uma só hora foi devastada!

[[v66-18-20]]

^<<v66-18-20,20>>^ Alegrem-se por causa dela, ó céus, e também vocês, santos, apóstolos e profetas, porque Deus julgou a causa de vocês contra ela."

[[v66-18-21]]

^<<v66-18-21,21>>^ Então um anjo forte levantou uma pedra do tamanho de uma grande pedra de moinho e lançou-a no mar, dizendo: "Assim, com ímpeto, será lançada Babilônia, a grande cidade, e nunca mais será achada.

[[v66-18-22]]

^<<v66-18-22,22>>^ Em você nunca mais será ouvido o som de harpistas, de músicos, de tocadores de flauta e de trombeta. Em você nunca mais se achará artífice nenhum de qualquer arte que seja, e nunca jamais se ouvirá em você o ruído de pedra de moinho.

[[v66-18-23]]

^<<v66-18-23,23>>^ Também nunca mais brilhará em você a luz de uma lamparina, e nunca mais se ouvirá em você uma voz de noivo ou de noiva, pois os seus mercadores foram os grandes da terra, porque com a sua feitiçaria você seduziu todas as nações.

[[v66-18-24]]

^<<v66-18-24,24>>^ E nela foi encontrado sangue de profetas, de santos e de todos os que foram mortos sobre a terra."

'''

xref:066-apocalipse/066-apocalipse-017.adoc#v66-17-0[&#60; Capítulo Anterior] | <<v66-18-0,Topo>> | xref:066-apocalipse/066-apocalipse-019.adoc#v66-19-0[Próximo Capítulo &#62;]