include::./index.adoc[]

[[v66-16-0]]
=== Apocalipse, 16
// naa ?, NAA - Nova Almeida Atualizada

[[v66-16-1]]

^<<v66-16-1,1>>^ Ouvi uma voz forte, vinda do santuário, dizendo aos sete anjos: — Vão e derramem sobre a terra as sete taças da ira de Deus.

[[v66-16-2]]

^<<v66-16-2,2>>^ O primeiro anjo foi e derramou a sua taça sobre a terra, e apareceram úlceras malignas e dolorosas nas pessoas que tinham a marca da besta e que adoravam a sua imagem.

[[v66-16-3]]

^<<v66-16-3,3>>^ O segundo anjo derramou a sua taça no mar, e o mar se transformou em sangue, como de um morto, e morreu todo ser vivo que havia no mar.

[[v66-16-4]]

^<<v66-16-4,4>>^ O terceiro anjo derramou a sua taça nos rios e nas fontes de água, e eles se transformaram em sangue.

[[v66-16-5]]

^<<v66-16-5,5>>^ Então ouvi o anjo das águas dizendo: "Tu és justo, tu que és e que eras, o Santo, pois julgaste estas coisas.

[[v66-16-6]]

^<<v66-16-6,6>>^ Porque derramaram sangue de santos e de profetas, também lhes deste sangue para beber. É o que merecem."

[[v66-16-7]]

^<<v66-16-7,7>>^ Ouvi uma voz do altar, que dizia: "Certamente, ó Senhor Deus, Todo-Poderoso, verdadeiros e justos são os teus juízos."

[[v66-16-8]]

^<<v66-16-8,8>>^ O quarto anjo derramou a sua taça sobre o sol, e lhe foi dado queimar a humanidade com fogo.

[[v66-16-9]]

^<<v66-16-9,9>>^ As pessoas se queimaram com o intenso calor e blasfemaram contra o nome de Deus, que tem autoridade sobre estes flagelos. Porém, não se arrependeram para darem glória a Deus.

[[v66-16-10]]

^<<v66-16-10,10>>^ O quinto anjo derramou a sua taça sobre o trono da besta. O reino da besta ficou em trevas, e as pessoas mordiam a língua por causa da dor que sentiam

[[v66-16-11]]

^<<v66-16-11,11>>^ e blasfemavam contra o Deus do céu por causa das angústias e das úlceras que sofriam. Porém, não se arrependeram de suas obras.

[[v66-16-12]]

^<<v66-16-12,12>>^ O sexto anjo derramou a sua taça sobre o grande rio Eufrates. As águas do rio secaram, para que se preparasse o caminho dos reis que vêm do Oriente.

[[v66-16-13]]

^<<v66-16-13,13>>^ Então vi sair da boca do dragão, da boca da besta e da boca do falso profeta três espíritos imundos semelhantes a rãs.

[[v66-16-14]]

^<<v66-16-14,14>>^ São espíritos de demônios, operadores de sinais, e se dirigem aos reis do mundo inteiro a fim de ajuntá-los para a batalha do grande Dia do Deus Todo-Poderoso.

[[v66-16-15]]

^<<v66-16-15,15>>^ "Eis que venho como vem o ladrão. Bem-aventurado aquele que vigia e guarda as suas vestes, para que não ande nu, e não se veja a sua vergonha."

[[v66-16-16]]

^<<v66-16-16,16>>^ Então ajuntaram os reis no lugar que em hebraico se chama Armagedom.

[[v66-16-17]]

^<<v66-16-17,17>>^ Então o sétimo anjo derramou a sua taça pelo ar. E uma voz forte saiu do santuário, do lado do trono, dizendo: — Está feito!

[[v66-16-18]]

^<<v66-16-18,18>>^ E sobrevieram relâmpagos, vozes e trovões, e ocorreu um grande terremoto, como nunca houve igual desde que há gente sobre a terra, tal foi o terremoto, forte e grande.

[[v66-16-19]]

^<<v66-16-19,19>>^ E a grande cidade se dividiu em três partes, e caíram as cidades das nações. E Deus se lembrou da grande Babilônia para dar-lhe o cálice do vinho do furor da sua ira.

[[v66-16-20]]

^<<v66-16-20,20>>^ Todas as ilhas fugiram, e os montes não foram achados.

[[v66-16-21]]

^<<v66-16-21,21>>^ Também desabou do céu sobre as pessoas uma grande chuva de granizo, com pedras que pesavam mais de trinta quilos. E, por causa do flagelo da chuva de pedras, as pessoas blasfemaram contra Deus, porque esse flagelo do granizo era terrível.

'''

xref:066-apocalipse/066-apocalipse-015.adoc#v66-15-0[&#60; Capítulo Anterior] | <<v66-16-0,Topo>> | xref:066-apocalipse/066-apocalipse-017.adoc#v66-17-0[Próximo Capítulo &#62;]