include::./index.adoc[]

[[v66-12-0]]
=== Apocalipse, 12
// naa ?, NAA - Nova Almeida Atualizada

[[v66-12-1]]

^<<v66-12-1,1>>^ Viu-se grande sinal no céu: uma mulher vestida do sol com a lua debaixo dos pés e uma coroa de doze estrelas na cabeça.

[[v66-12-2]]

^<<v66-12-2,2>>^ A mulher estava grávida e gritava com dores de parto, sofrendo tormentos para dar à luz.

[[v66-12-3]]

^<<v66-12-3,3>>^ Viu-se, também, outro sinal no céu, e eis um dragão, grande, vermelho, com sete cabeças e dez chifres, e, nas cabeças, sete diademas.

[[v66-12-4]]

^<<v66-12-4,4>>^ A sua cauda arrastou a terça parte das estrelas do céu, as quais lançou para a terra. E o dragão se deteve diante da mulher que estava para dar à luz, a fim de devorar o filho dela quando nascesse.

[[v66-12-5]]

^<<v66-12-5,5>>^ Ela deu à luz um filho homem, que há de governar todas as nações com cetro de ferro. E o filho da mulher foi arrebatado para junto de Deus e do seu trono.

[[v66-12-6]]

^<<v66-12-6,6>>^ A mulher, porém, fugiu para o deserto, onde Deus lhe havia preparado um lugar, para que nele a sustentem durante mil duzentos e sessenta dias.

[[v66-12-7]]

^<<v66-12-7,7>>^ Então estourou a guerra no céu. Miguel e os seus anjos lutaram contra o dragão. Também o dragão e os seus anjos lutaram,

[[v66-12-8]]

^<<v66-12-8,8>>^ mas não conseguiram sair vitoriosos e não havia mais lugar para eles no céu.

[[v66-12-9]]

^<<v66-12-9,9>>^ E foi expulso o grande dragão, a antiga serpente, que se chama diabo e Satanás, o sedutor de todo o mundo. Ele foi atirado para a terra, e, com ele, os seus anjos.

[[v66-12-10]]

^<<v66-12-10,10>>^ Então ouvi uma voz forte no céu, proclamando: "Agora veio a salvação, o poder, o reino do nosso Deus e a autoridade do seu Cristo, pois foi expulso o acusador de nossos irmãos, o mesmo que os acusa de dia e de noite diante do nosso Deus.

[[v66-12-11]]

^<<v66-12-11,11>>^ Eles o venceram por causa do sangue do Cordeiro e por causa da palavra do testemunho que deram e, mesmo diante da morte, não amaram a própria vida.

[[v66-12-12]]

^<<v66-12-12,12>>^ Por isso, alegrem-se, ó céus, e vocês que neles habitam. Ai da terra e do mar, pois o diabo desceu até vocês, cheio de fúria, sabendo que pouco tempo lhe resta."

[[v66-12-13]]

^<<v66-12-13,13>>^ Quando o dragão viu que tinha sido atirado para a terra, perseguiu a mulher que tinha dado à luz o filho homem.

[[v66-12-14]]

^<<v66-12-14,14>>^ Mas foram dadas à mulher as duas asas da grande águia, para que voasse para o deserto, para o seu lugar, aí onde é sustentada durante um tempo, tempos e metade de um tempo, fora do alcance da serpente.

[[v66-12-15]]

^<<v66-12-15,15>>^ Então, a serpente lançou da boca água como um rio atrás da mulher, a fim de fazer com que ela fosse arrastada pelas águas.

[[v66-12-16]]

^<<v66-12-16,16>>^ A terra, porém, socorreu a mulher: abriu a sua boca e engoliu o rio que o dragão tinha lançado de sua boca.

[[v66-12-17]]

^<<v66-12-17,17>>^ O dragão ficou irado com a mulher e foi travar guerra com o restante da descendência dela, ou seja, os que guardam os mandamentos de Deus e têm o testemunho de Jesus.

[[v66-12-18]]

^<<v66-12-18,18>>^ E o dragão se pôs em pé sobre a areia do mar.

'''

xref:066-apocalipse/066-apocalipse-011.adoc#v66-11-0[&#60; Capítulo Anterior] | <<v66-12-0,Topo>> | xref:066-apocalipse/066-apocalipse-013.adoc#v66-13-0[Próximo Capítulo &#62;]