include::./index.adoc[]

[[v66-3-0]]
=== Apocalipse, 3
// naa ?, NAA - Nova Almeida Atualizada

[[v66-3-1]]

^<<v66-3-1,1>>^ — Ao anjo da igreja em Sardes escreva: "Estas coisas diz aquele que tem os sete espíritos de Deus e as sete estrelas: Conheço as obras que você realiza, que você tem fama de estar vivo, mas está morto.

[[v66-3-2]]

^<<v66-3-2,2>>^ Fique vigiando e fortaleça o restante que estava para morrer, porque verifiquei que as obras que você realiza não são íntegras na presença do meu Deus.

[[v66-3-3]]

^<<v66-3-3,3>>^ Lembre-se, pois, do que você recebeu e ouviu; guarde-o e arrependa-se. Se você não vigiar, virei como ladrão, e você de modo nenhum saberá em que hora virei contra você.

[[v66-3-4]]

^<<v66-3-4,4>>^ Mas você tem aí em Sardes umas poucas pessoas que não contaminaram as suas vestes. Elas andarão comigo, vestidas de branco, pois são dignas.

[[v66-3-5]]

^<<v66-3-5,5>>^ O vencedor será assim vestido de branco, e de modo nenhum apagarei o seu nome do Livro da Vida. Pelo contrário, confessarei o seu nome diante de meu Pai e diante dos seus anjos.

[[v66-3-6]]

^<<v66-3-6,6>>^ Quem tem ouvidos, ouça o que o Espírito diz às igrejas."

[[v66-3-7]]

^<<v66-3-7,7>>^ — Ao anjo da igreja em Filadélfia escreva: "Estas coisas diz o santo, o verdadeiro, aquele que tem a chave de Davi, que abre, e ninguém fechará, e que fecha, e ninguém abrirá.

[[v66-3-8]]

^<<v66-3-8,8>>^ Conheço as obras que você realiza. Eis que tenho posto diante de você uma porta aberta, a qual ninguém pode fechar. Sei que você tem pouca força, mas guardou a minha palavra e não negou o meu nome.

[[v66-3-9]]

^<<v66-3-9,9>>^ Eis o que eu farei com alguns dos que são da sinagoga de Satanás, desses que se declaram judeus e não são, mas mentem. Eis que farei com que venham até você, prostrem-se aos seus pés e reconheçam que eu amo você.

[[v66-3-10]]

^<<v66-3-10,10>>^ Você guardou a palavra da minha perseverança. Por isso, também eu o guardarei da hora da provação que há de vir sobre o mundo inteiro, para pôr à prova os que habitam sobre a terra.

[[v66-3-11]]

^<<v66-3-11,11>>^ Venho sem demora. Conserve o que você tem, para que ninguém tome a sua coroa.

[[v66-3-12]]

^<<v66-3-12,12>>^ Ao vencedor, farei com que seja uma coluna no santuário do meu Deus, e dali jamais sairá. Gravarei sobre ele o nome do meu Deus, o nome da cidade do meu Deus, a nova Jerusalém que desce do céu, vinda da parte do meu Deus, e o meu novo nome.

[[v66-3-13]]

^<<v66-3-13,13>>^ Quem tem ouvidos, ouça o que o Espírito diz às igrejas."

[[v66-3-14]]

^<<v66-3-14,14>>^ — Ao anjo da igreja em Laodiceia escreva: "Estas coisas diz o Amém, a testemunha fiel e verdadeira, o princípio da criação de Deus.

[[v66-3-15]]

^<<v66-3-15,15>>^ Conheço as obras que você realiza, que você não é nem frio nem quente. Quem dera você fosse frio ou quente!

[[v66-3-16]]

^<<v66-3-16,16>>^ Assim, porque você é morno, e não é nem quente nem frio, estou a ponto de vomitá-lo da minha boca.

[[v66-3-17]]

^<<v66-3-17,17>>^ Você diz: ‘Sou rico, estou bem de vida e não preciso de nada.’ Mas você não sabe que é infeliz, sim, miserável, pobre, cego e nu.

[[v66-3-18]]

^<<v66-3-18,18>>^ Aconselho que você compre de mim ouro refinado pelo fogo, para que você seja, de fato, rico. Compre vestes brancas para se vestir, a fim de que a vergonha de sua nudez não fique evidente, e colírio para ungir os olhos, a fim de que você possa ver.

[[v66-3-19]]

^<<v66-3-19,19>>^ Eu repreendo e disciplino aqueles que amo. Portanto, seja zeloso e arrependa-se.

[[v66-3-20]]

^<<v66-3-20,20>>^ Eis que estou à porta e bato; se alguém ouvir a minha voz e abrir a porta, entrarei em sua casa e cearei com ele, e ele, comigo.

[[v66-3-21]]

^<<v66-3-21,21>>^ Ao vencedor, darei o direito de sentar-se comigo no meu trono, assim como também eu venci e me sentei com o meu Pai no seu trono.

[[v66-3-22]]

^<<v66-3-22,22>>^ Quem tem ouvidos, ouça o que o Espírito diz às igrejas."

'''

xref:066-apocalipse/066-apocalipse-002.adoc#v66-2-0[&#60; Capítulo Anterior] | <<v66-3-0,Topo>> | xref:066-apocalipse/066-apocalipse-004.adoc#v66-4-0[Próximo Capítulo &#62;]