include::./index.adoc[]

[[v46-8-0]]
=== 1 Coríntios, 8
// naa ?, NAA - Nova Almeida Atualizada

[[v46-8-1]]

^<<v46-8-1,1>>^ No que se refere às coisas sacrificadas a ídolos, sabemos que todos temos conhecimento. O conhecimento leva ao orgulho, mas o amor edifica.

[[v46-8-2]]

^<<v46-8-2,2>>^ Se alguém julga conhecer alguma coisa, ainda não conhece como deveria conhecer.

[[v46-8-3]]

^<<v46-8-3,3>>^ Mas, se alguém ama a Deus, esse é conhecido por ele.

[[v46-8-4]]

^<<v46-8-4,4>>^ Quanto a comer alimentos sacrificados a ídolos, sabemos que o ídolo, por si mesmo, nada é no mundo e que não há senão um só Deus.

[[v46-8-5]]

^<<v46-8-5,5>>^ Porque, ainda que existam alguns que são chamados de deuses, quer no céu ou sobre a terra — como há muitos "deuses" e muitos "senhores" —,

[[v46-8-6]]

^<<v46-8-6,6>>^ para nós, porém, há um só Deus, o Pai, de quem são todas as coisas e para quem existimos, e um só Senhor, Jesus Cristo, por meio de quem todas as coisas existem e por meio de quem também nós existimos.

[[v46-8-7]]

^<<v46-8-7,7>>^ Entretanto, nem todos têm esse conhecimento. Alguns, acostumados até agora com o ídolo, ainda comem desses alimentos como se fossem sacrificados a ídolos; e a consciência destes, por ser fraca, vem a contaminar-se.

[[v46-8-8]]

^<<v46-8-8,8>>^ Não é a comida que nos torna agradáveis a Deus, pois nada perderemos, se não comermos, e nada ganharemos, se comermos.

[[v46-8-9]]

^<<v46-8-9,9>>^ Mas tenham cuidado para que essa liberdade de vocês não venha, de algum modo, a ser tropeço para os fracos.

[[v46-8-10]]

^<<v46-8-10,10>>^ Porque, se alguém enxergar você, que tem conhecimento, sentado à mesa no templo de um ídolo, será que a consciência do que é fraco não vai ser induzida a participar de comidas sacrificadas a ídolos?

[[v46-8-11]]

^<<v46-8-11,11>>^ E, assim, por causa do conhecimento que você tem, perde-se o irmão fraco, pelo qual Cristo morreu.

[[v46-8-12]]

^<<v46-8-12,12>>^ E, deste modo, pecando contra os irmãos, ferindo a consciência fraca que eles têm, é contra Cristo que vocês estão pecando.

[[v46-8-13]]

^<<v46-8-13,13>>^ E, por isso, se a comida serve de escândalo ao meu irmão, nunca mais comerei carne, para que não venha a escandalizá-lo.

'''

xref:046-1-corintios/046-1-corintios-007.adoc#v46-7-0[&#60; Capítulo Anterior] | <<v46-8-0,Topo>> | xref:046-1-corintios/046-1-corintios-009.adoc#v46-9-0[Próximo Capítulo &#62;]