include::./index.adoc[]

[[v46-13-0]]
=== 1 Coríntios, 13
// naa ?, NAA - Nova Almeida Atualizada

[[v46-13-1]]

^<<v46-13-1,1>>^ Ainda que eu fale as línguas dos homens e dos anjos, se não tiver amor, serei como o bronze que soa ou como o címbalo que retine.

[[v46-13-2]]

^<<v46-13-2,2>>^ Ainda que eu tenha o dom de profetizar e conheça todos os mistérios e toda a ciência; ainda que eu tenha tamanha fé, a ponto de transportar montes, se não tiver amor, nada serei.

[[v46-13-3]]

^<<v46-13-3,3>>^ E ainda que eu distribua todos os meus bens entre os pobres e ainda que entregue o meu próprio corpo para ser queimado, se não tiver amor, isso de nada me adiantará.

[[v46-13-4]]

^<<v46-13-4,4>>^ O amor é paciente e bondoso. O amor não arde em ciúmes, não se envaidece, não é orgulhoso,

[[v46-13-5]]

^<<v46-13-5,5>>^ não se conduz de forma inconveniente, não busca os seus interesses, não se irrita, não se ressente do mal.

[[v46-13-6]]

^<<v46-13-6,6>>^ O amor não se alegra com a injustiça, mas se alegra com a verdade.

[[v46-13-7]]

^<<v46-13-7,7>>^ O amor tudo sofre, tudo crê, tudo espera, tudo suporta.

[[v46-13-8]]

^<<v46-13-8,8>>^ O amor jamais acaba. Havendo profecias, desaparecerão; havendo línguas, cessarão; havendo ciência, passará.

[[v46-13-9]]

^<<v46-13-9,9>>^ Pois o nosso conhecimento é incompleto e a nossa profecia é incompleta.

[[v46-13-10]]

^<<v46-13-10,10>>^ Mas, quando vier o que é completo, então o que é incompleto será aniquilado.

[[v46-13-11]]

^<<v46-13-11,11>>^ Quando eu era menino, falava como menino, sentia como menino, pensava como menino; quando cheguei a ser homem, desisti das coisas próprias de menino.

[[v46-13-12]]

^<<v46-13-12,12>>^ Porque agora vemos como num espelho, de forma obscura; depois veremos face a face. Agora meu conhecimento é incompleto; depois conhecerei como também sou conhecido.

[[v46-13-13]]

^<<v46-13-13,13>>^ Agora, pois, permanecem a fé, a esperança e o amor, estes três; porém o maior deles é o amor.

'''

xref:046-1-corintios/046-1-corintios-012.adoc#v46-12-0[&#60; Capítulo Anterior] | <<v46-13-0,Topo>> | xref:046-1-corintios/046-1-corintios-014.adoc#v46-14-0[Próximo Capítulo &#62;]