include::./index.adoc[]

[[v46-4-0]]
=== 1 Coríntios, 4
// naa ?, NAA - Nova Almeida Atualizada

[[v46-4-1]]

^<<v46-4-1,1>>^ Assim, pois, importa que todos nos considerem como ministros de Cristo e encarregados dos mistérios de Deus.

[[v46-4-2]]

^<<v46-4-2,2>>^ Ora, além disso, o que se requer destes encarregados é que cada um deles seja encontrado fiel.

[[v46-4-3]]

^<<v46-4-3,3>>^ Mas a mim pouco importa ser julgado por vocês ou por um tribunal humano; nem eu julgo a mim mesmo.

[[v46-4-4]]

^<<v46-4-4,4>>^ Porque a consciência não me acusa de nada. Mas nem por isso me dou por justificado, pois quem me julga é o Senhor.

[[v46-4-5]]

^<<v46-4-5,5>>^ Portanto, não julguem nada antes do tempo, até que venha o Senhor, o qual não somente trará à plena luz as coisas ocultas das trevas, mas também manifestará os desígnios dos corações. E então cada um receberá o seu louvor da parte de Deus.

[[v46-4-6]]

^<<v46-4-6,6>>^ Meus irmãos, apliquei estas coisas figuradamente a mim mesmo e a Apolo, por causa de vocês, para que por nosso exemplo vocês aprendam isto: "Não ultrapassem o que está escrito", para que ninguém se encha de orgulho a favor de um em prejuízo de outro.

[[v46-4-7]]

^<<v46-4-7,7>>^ Pois quem é que faz com que você sobressaia? E o que é que você tem que não tenha recebido? E, se o recebeu, por que se gloria, como se não o tivesse recebido?

[[v46-4-8]]

^<<v46-4-8,8>>^ Vocês já estão fartos! Já são ricos! Chegaram a reinar sem nós! Sim, quem dera que vocês fossem reis, para que também nós viéssemos a reinar com vocês!

[[v46-4-9]]

^<<v46-4-9,9>>^ Porque me parece que Deus pôs a nós, os apóstolos, em último lugar, como se fôssemos condenados à morte. Porque nos tornamos espetáculo para o mundo, tanto para os anjos como para os seres humanos.

[[v46-4-10]]

^<<v46-4-10,10>>^ Nós somos loucos por causa de Cristo, e vocês são sábios em Cristo. Nós somos fracos, e vocês são fortes; vocês são honrados, e nós somos desprezados.

[[v46-4-11]]

^<<v46-4-11,11>>^ Até a presente hora, sofremos fome, sede e nudez; somos esbofeteados e não temos morada certa;

[[v46-4-12]]

^<<v46-4-12,12>>^ e nos afadigamos, trabalhando com as nossas próprias mãos. Quando somos insultados, bendizemos; quando somos perseguidos, suportamos;

[[v46-4-13]]

^<<v46-4-13,13>>^ quando somos caluniados, procuramos conciliação. Até agora, temos chegado a ser considerados lixo do mundo, escória de todos.

[[v46-4-14]]

^<<v46-4-14,14>>^ Não escrevo estas coisas para que vocês fiquem envergonhados; pelo contrário, para admoestá-los como a meus filhos amados.

[[v46-4-15]]

^<<v46-4-15,15>>^ Porque, ainda que vocês tivessem milhares de instrutores em Cristo, não teriam muitos pais, pois eu gerei vocês em Cristo Jesus, pelo evangelho.

[[v46-4-16]]

^<<v46-4-16,16>>^ Portanto, eu peço a vocês que sejam meus imitadores.

[[v46-4-17]]

^<<v46-4-17,17>>^ Por esta causa, eu enviei até vocês Timóteo, que é meu filho amado e fiel no Senhor, o qual fará com que vocês se lembrem dos meus caminhos em Cristo Jesus, como, por toda parte, ensino em cada igreja.

[[v46-4-18]]

^<<v46-4-18,18>>^ Alguns de vocês se encheram de orgulho, como se eu não fosse mais visitá-los.

[[v46-4-19]]

^<<v46-4-19,19>>^ Mas, em breve, se o Senhor quiser, irei visitá-los, e então conhecerei não a palavra, mas o poder desses orgulhosos.

[[v46-4-20]]

^<<v46-4-20,20>>^ Porque o Reino de Deus consiste não em palavra, mas em poder.

[[v46-4-21]]

^<<v46-4-21,21>>^ O que vocês preferem? Que eu vá até aí com um chicote ou com amor e espírito de mansidão?

'''

xref:046-1-corintios/046-1-corintios-003.adoc#v46-3-0[&#60; Capítulo Anterior] | <<v46-4-0,Topo>> | xref:046-1-corintios/046-1-corintios-005.adoc#v46-5-0[Próximo Capítulo &#62;]