include::./index.adoc[]

[[v46-1-0]]
=== 1 Coríntios, 1
// naa ?, NAA - Nova Almeida Atualizada

[[v46-1-1]]

^<<v46-1-1,1>>^ Paulo, chamado pela vontade de Deus para ser apóstolo de Cristo Jesus, e o irmão Sóstenes,

[[v46-1-2]]

^<<v46-1-2,2>>^ à igreja de Deus que está em Corinto, aos santificados em Cristo Jesus, chamados para ser santos, com todos os que em todos os lugares invocam o nome de nosso Senhor Jesus Cristo, Senhor deles e nosso.

[[v46-1-3]]

^<<v46-1-3,3>>^ Que a graça e a paz de Deus, nosso Pai, e do Senhor Jesus Cristo estejam com vocês.

[[v46-1-4]]

^<<v46-1-4,4>>^ Sempre dou graças ao meu Deus por vocês, por causa da graça de Deus que foi dada a vocês em Cristo Jesus.

[[v46-1-5]]

^<<v46-1-5,5>>^ Porque em tudo vocês foram enriquecidos nele, em toda a palavra e em todo o conhecimento,

[[v46-1-6]]

^<<v46-1-6,6>>^ assim como o testemunho de Cristo tem sido confirmado em vocês,

[[v46-1-7]]

^<<v46-1-7,7>>^ de maneira que não lhes falta nenhum dom, enquanto aguardam a revelação de nosso Senhor Jesus Cristo.

[[v46-1-8]]

^<<v46-1-8,8>>^ Ele também os confirmará até o fim, para que vocês sejam irrepreensíveis no Dia de nosso Senhor Jesus Cristo.

[[v46-1-9]]

^<<v46-1-9,9>>^ Fiel é Deus, pelo qual vocês foram chamados à comunhão de seu Filho Jesus Cristo, nosso Senhor.

[[v46-1-10]]

^<<v46-1-10,10>>^ Irmãos, pelo nome de nosso Senhor Jesus Cristo, peço-lhes que todos estejam de acordo naquilo que falam e que não haja divisões entre vocês; pelo contrário, que vocês sejam unidos no mesmo modo de pensar e num mesmo propósito.

[[v46-1-11]]

^<<v46-1-11,11>>^ Pois, meus irmãos, fui informado a respeito de vocês por alguns membros da casa de Cloe de que há brigas entre vocês.

[[v46-1-12]]

^<<v46-1-12,12>>^ Refiro-me ao fato de cada um de vocês dizer: "Eu sou de Paulo", "Eu sou de Apolo", "Eu sou de Cefas", "Eu sou de Cristo".

[[v46-1-13]]

^<<v46-1-13,13>>^ Será que Cristo está dividido? Será que Paulo foi crucificado por vocês ou será que vocês foram batizados em nome de Paulo?

[[v46-1-14]]

^<<v46-1-14,14>>^ Dou graças a Deus por não ter batizado nenhum de vocês, exceto Crispo e Gaio,

[[v46-1-15]]

^<<v46-1-15,15>>^ para que ninguém diga que vocês foram batizados em meu nome.

[[v46-1-16]]

^<<v46-1-16,16>>^ Batizei também a casa de Estéfanas. Além destes, não me lembro se batizei algum outro.

[[v46-1-17]]

^<<v46-1-17,17>>^ Afinal, Cristo não me enviou para batizar, mas para pregar o evangelho, não com sabedoria de palavra, para que não se anule a cruz de Cristo.

[[v46-1-18]]

^<<v46-1-18,18>>^ Certamente a palavra da cruz é loucura para os que se perdem, mas para nós, que somos salvos, ela é poder de Deus.

[[v46-1-19]]

^<<v46-1-19,19>>^ Pois está escrito: "Destruirei a sabedoria dos sábios e aniquilarei a inteligência dos inteligentes."

[[v46-1-20]]

^<<v46-1-20,20>>^ Onde está o sábio? Onde está o escriba? Onde está o questionador deste mundo? Não é fato que Deus tornou louca a sabedoria deste mundo?

[[v46-1-21]]

^<<v46-1-21,21>>^ Visto que, na sabedoria de Deus, o mundo não o conheceu por sua própria sabedoria, Deus achou por bem salvar os que creem por meio da loucura da pregação.

[[v46-1-22]]

^<<v46-1-22,22>>^ Porque os judeus pedem sinais e os gregos buscam sabedoria,

[[v46-1-23]]

^<<v46-1-23,23>>^ mas nós pregamos o Cristo crucificado, escândalo para os judeus, loucura para os gentios.

[[v46-1-24]]

^<<v46-1-24,24>>^ Mas, para os que foram chamados, tanto judeus como gregos, Cristo é o poder de Deus e a sabedoria de Deus.

[[v46-1-25]]

^<<v46-1-25,25>>^ Porque a loucura de Deus é mais sábia do que a sabedoria humana, e a fraqueza de Deus é mais forte do que a força humana.

[[v46-1-26]]

^<<v46-1-26,26>>^ Irmãos, considerem a vocação de vocês. Não foram chamados muitos sábios segundo a carne, nem muitos poderosos, nem muitos de nobre nascimento.

[[v46-1-27]]

^<<v46-1-27,27>>^ Pelo contrário, Deus escolheu as coisas loucas do mundo para envergonhar os sábios e escolheu as coisas fracas do mundo para envergonhar as fortes.

[[v46-1-28]]

^<<v46-1-28,28>>^ E Deus escolheu as coisas humildes do mundo, e as desprezadas, e aquelas que não são, para reduzir a nada as que são,

[[v46-1-29]]

^<<v46-1-29,29>>^ a fim de que ninguém se glorie na presença de Deus.

[[v46-1-30]]

^<<v46-1-30,30>>^ Mas vocês são dele, em Cristo Jesus, o qual se tornou para nós, da parte de Deus, sabedoria, justiça, santificação e redenção,

[[v46-1-31]]

^<<v46-1-31,31>>^ para que, como está escrito, "aquele que se gloria, glorie-se no Senhor".

'''

xref:045-romanos/045-romanos-016.adoc#v45-16-0[&#60; Capítulo Anterior] | <<v46-1-0,Topo>> | xref:046-1-corintios/046-1-corintios-002.adoc#v46-2-0[Próximo Capítulo &#62;]