include::./index.adoc[]

[[v46-6-0]]
=== 1 Coríntios, 6
// naa ?, NAA - Nova Almeida Atualizada

[[v46-6-1]]

^<<v46-6-1,1>>^ Quando algum de vocês tem uma questão contra outro, como se atreve a submeter isso a juízo diante dos injustos e não diante dos santos?

[[v46-6-2]]

^<<v46-6-2,2>>^ Ou vocês não sabem que os santos hão de julgar o mundo? Ora, se o mundo deverá ser julgado por vocês, será que vocês não são competentes para julgar as coisas mínimas?

[[v46-6-3]]

^<<v46-6-3,3>>^ Por acaso vocês não sabem que havemos de julgar os próprios anjos? Quanto mais as coisas desta vida!

[[v46-6-4]]

^<<v46-6-4,4>>^ Portanto, quando precisam julgar negócios terrenos, por que vocês constituem como juízes aqueles que não têm nenhuma aceitação na igreja?

[[v46-6-5]]

^<<v46-6-5,5>>^ Digo isso para a vergonha de vocês. Será que não existe nem ao menos um sábio entre vocês, que possa julgar entre seus irmãos?

[[v46-6-6]]

^<<v46-6-6,6>>^ Mas um irmão vai a juízo contra outro irmão, e isto diante de não crentes!

[[v46-6-7]]

^<<v46-6-7,7>>^ O simples fato de moverem ações uns contra os outros já é completa derrota para vocês. Por que não preferem sofrer a injustiça? Por que não preferem ficar com o prejuízo?

[[v46-6-8]]

^<<v46-6-8,8>>^ Mas vocês mesmos cometem injustiça e causam prejuízo, e isto aos próprios irmãos!

[[v46-6-9]]

^<<v46-6-9,9>>^ Ou vocês não sabem que os injustos não herdarão o Reino de Deus? Não se enganem: nem imorais, nem idólatras, nem adúlteros, nem afeminados, nem homossexuais,

[[v46-6-10]]

^<<v46-6-10,10>>^ nem ladrões, nem avarentos, nem bêbados, nem maldizentes, nem roubadores herdarão o Reino de Deus.

[[v46-6-11]]

^<<v46-6-11,11>>^ Alguns de vocês eram assim. Mas vocês foram lavados, foram santificados, foram justificados no nome do Senhor Jesus Cristo e no Espírito do nosso Deus.

[[v46-6-12]]

^<<v46-6-12,12>>^ "Todas as coisas me são lícitas", mas nem todas convêm. "Todas as coisas me são lícitas", mas eu não me deixarei dominar por nenhuma delas.

[[v46-6-13]]

^<<v46-6-13,13>>^ "Os alimentos são para o estômago, e o estômago existe para os alimentos." Mas Deus destruirá tanto o estômago quanto os alimentos. Porém o corpo não é para a imoralidade, mas para o Senhor, e o Senhor, para o corpo.

[[v46-6-14]]

^<<v46-6-14,14>>^ Deus ressuscitou o Senhor e também nos ressuscitará pelo seu poder.

[[v46-6-15]]

^<<v46-6-15,15>>^ Vocês não sabem que o corpo de cada um de vocês é membro de Cristo? E será que eu tomaria os membros de Cristo e os faria membros de uma prostituta? De modo nenhum!

[[v46-6-16]]

^<<v46-6-16,16>>^ Ou não sabem que o homem que se une à prostituta forma um só corpo com ela? Porque, como se diz, "os dois se tornarão uma só carne".

[[v46-6-17]]

^<<v46-6-17,17>>^ Mas aquele que se une ao Senhor é um só espírito com ele.

[[v46-6-18]]

^<<v46-6-18,18>>^ Fujam da imoralidade sexual! Qualquer outro pecado que uma pessoa cometer é fora do corpo; mas aquele que pratica imoralidade sexual peca contra o próprio corpo.

[[v46-6-19]]

^<<v46-6-19,19>>^ Será que vocês não sabem que o corpo de vocês é santuário do Espírito Santo, que está em vocês e que vocês receberam de Deus, e que vocês não pertencem a vocês mesmos?

[[v46-6-20]]

^<<v46-6-20,20>>^ Porque vocês foram comprados por preço. Agora, pois, glorifiquem a Deus no corpo de vocês.

'''

xref:046-1-corintios/046-1-corintios-005.adoc#v46-5-0[&#60; Capítulo Anterior] | <<v46-6-0,Topo>> | xref:046-1-corintios/046-1-corintios-007.adoc#v46-7-0[Próximo Capítulo &#62;]