include::./index.adoc[]

[[v46-16-0]]
=== 1 Coríntios, 16
// naa ?, NAA - Nova Almeida Atualizada

[[v46-16-1]]

^<<v46-16-1,1>>^ Quanto à coleta para os santos, façam também vocês como ordenei às igrejas da Galácia.

[[v46-16-2]]

^<<v46-16-2,2>>^ No primeiro dia da semana, cada um de vocês separe uma quantia, conforme a sua prosperidade, e vá juntando, para que não seja necessário fazer coletas quando eu for.

[[v46-16-3]]

^<<v46-16-3,3>>^ E, quando eu tiver chegado, enviarei, com cartas, aqueles que vocês aprovarem, para que levem a oferta de vocês a Jerusalém.

[[v46-16-4]]

^<<v46-16-4,4>>^ Se for conveniente que eu também vá, eles irão comigo.

[[v46-16-5]]

^<<v46-16-5,5>>^ Irei visitar vocês por ocasião da minha passagem pela Macedônia, porque devo passar pela Macedônia.

[[v46-16-6]]

^<<v46-16-6,6>>^ E bem pode ser que eu me demore ou mesmo passe o inverno com vocês, para que vocês me encaminhem nas viagens que eu tenha de fazer.

[[v46-16-7]]

^<<v46-16-7,7>>^ Porque não quero, agora, ver vocês apenas de passagem, pois espero permanecer algum tempo com vocês, se o Senhor o permitir.

[[v46-16-8]]

^<<v46-16-8,8>>^ Mas ficarei em Éfeso até o Pentecostes,

[[v46-16-9]]

^<<v46-16-9,9>>^ porque uma porta grande e oportuna para o trabalho se abriu para mim; e há muitos adversários.

[[v46-16-10]]

^<<v46-16-10,10>>^ E, se Timóteo for, façam tudo para que não tenha nada a temer enquanto estiver entre vocês, porque trabalha na obra do Senhor, como também eu.

[[v46-16-11]]

^<<v46-16-11,11>>^ Portanto, que ninguém o despreze. Ajudem-no a continuar a viagem em paz, para que venha até aqui, visto que o espero com os irmãos.

[[v46-16-12]]

^<<v46-16-12,12>>^ Quanto ao irmão Apolo, muito lhe tenho recomendado que fosse visitar vocês em companhia dos irmãos, mas ele não quis de jeito nenhum ir agora; irá, porém, quando tiver oportunidade.

[[v46-16-13]]

^<<v46-16-13,13>>^ Fiquem alertas, permaneçam firmes na fé, mostrem coragem, sejam fortes.

[[v46-16-14]]

^<<v46-16-14,14>>^ Façam todas as coisas com amor.

[[v46-16-15]]

^<<v46-16-15,15>>^ E agora, irmãos, eu peço a vocês o seguinte: os membros da casa de Estéfanas são as primícias da Acaia e eles se consagraram ao serviço dos santos.

[[v46-16-16]]

^<<v46-16-16,16>>^ Portanto, sujeitem-se a pessoas como eles, bem como a todo aquele que é cooperador e obreiro.

[[v46-16-17]]

^<<v46-16-17,17>>^ Alegro-me com a vinda de Estéfanas, de Fortunato e de Acaico, porque eles supriram o que faltava da parte de vocês.

[[v46-16-18]]

^<<v46-16-18,18>>^ Porque trouxeram refrigério ao meu espírito e ao de vocês também. Deem o devido reconhecimento a homens como esses.

[[v46-16-19]]

^<<v46-16-19,19>>^ As igrejas da província da Ásia mandam saudações. Também Áquila e Priscila mandam cordiais saudações no Senhor, juntamente com a igreja que se reúne na casa deles.

[[v46-16-20]]

^<<v46-16-20,20>>^ Todos os irmãos mandam saudações. Saúdem uns aos outros com um beijo santo.

[[v46-16-21]]

^<<v46-16-21,21>>^ Eu, Paulo, escrevo a saudação de próprio punho.

[[v46-16-22]]

^<<v46-16-22,22>>^ Se alguém não ama o Senhor, seja anátema. Maranata!

[[v46-16-23]]

^<<v46-16-23,23>>^ A graça do Senhor Jesus esteja com vocês.

[[v46-16-24]]

^<<v46-16-24,24>>^ O meu amor esteja com todos vocês, em Cristo Jesus.

'''

xref:046-1-corintios/046-1-corintios-015.adoc#v46-15-0[&#60; Capítulo Anterior] | <<v46-16-0,Topo>> | xref:047-2-corintios/047-2-corintios-001.adoc#v47-1-0[Próximo Capítulo &#62;]