include::./index.adoc[]

[[v46-11-0]]
=== 1 Coríntios, 11
// naa ?, NAA - Nova Almeida Atualizada

[[v46-11-1]]

^<<v46-11-1,1>>^ Sejam meus imitadores, como também eu sou imitador de Cristo.

[[v46-11-2]]

^<<v46-11-2,2>>^ Eu os elogio porque em tudo vocês se lembram de mim e retêm as tradições assim como eu as transmiti a vocês.

[[v46-11-3]]

^<<v46-11-3,3>>^ Quero, porém, que saibam que Cristo é o cabeça de todo homem, e o homem é o cabeça da mulher, e Deus é o cabeça de Cristo.

[[v46-11-4]]

^<<v46-11-4,4>>^ Todo homem que ora ou profetiza com a cabeça coberta desonra a sua própria cabeça.

[[v46-11-5]]

^<<v46-11-5,5>>^ Toda mulher, porém, que ora ou profetiza com a cabeça descoberta desonra a sua própria cabeça, porque é como se a tivesse rapada.

[[v46-11-6]]

^<<v46-11-6,6>>^ Portanto, se a mulher não cobre a cabeça, nesse caso, que rape o cabelo. Mas, se é vergonhoso para a mulher tosquiar-se ou rapar o cabelo, que ela cubra a cabeça.

[[v46-11-7]]

^<<v46-11-7,7>>^ Porque o homem não deve cobrir a cabeça, por ser ele imagem e glória de Deus, mas a mulher é glória do homem.

[[v46-11-8]]

^<<v46-11-8,8>>^ Porque o homem não foi feito da mulher, mas a mulher foi feita do homem.

[[v46-11-9]]

^<<v46-11-9,9>>^ Porque também o homem não foi criado por causa da mulher, e sim a mulher por causa do homem.

[[v46-11-10]]

^<<v46-11-10,10>>^ Portanto, por causa dos anjos, a mulher deve trazer um sinal de autoridade na cabeça.

[[v46-11-11]]

^<<v46-11-11,11>>^ No Senhor, todavia, nem a mulher é independente do homem, nem o homem é independente da mulher.

[[v46-11-12]]

^<<v46-11-12,12>>^ Porque, assim como a mulher foi feita do homem, assim também o homem nasce da mulher; e tudo vem de Deus.

[[v46-11-13]]

^<<v46-11-13,13>>^ Julguem entre vocês mesmos: é próprio que a mulher ore a Deus com a cabeça descoberta?

[[v46-11-14]]

^<<v46-11-14,14>>^ Ou a própria natureza não lhes ensina que é desonroso para o homem usar cabelo comprido?

[[v46-11-15]]

^<<v46-11-15,15>>^ E que, tratando-se da mulher, é para ela uma glória? Pois o cabelo lhe foi dado em lugar de véu.

[[v46-11-16]]

^<<v46-11-16,16>>^ Mas, se alguém quiser discutir essa questão, saiba que nós não temos tal costume, nem as igrejas de Deus.

[[v46-11-17]]

^<<v46-11-17,17>>^ Mas nisto que agora prescrevo, não posso elogiá-los, porque vocês se reúnem não para melhor, e sim para pior.

[[v46-11-18]]

^<<v46-11-18,18>>^ Porque, antes de tudo, estou informado de que, quando se reúnem na igreja, existem divisões entre vocês, e eu, em parte, acredito que isso é verdade.

[[v46-11-19]]

^<<v46-11-19,19>>^ E é até necessário que haja partidos entre vocês, para que também os aprovados se tornem conhecidos entre vocês.

[[v46-11-20]]

^<<v46-11-20,20>>^ Quando, pois, se reúnem no mesmo lugar, não é a ceia do Senhor que vocês comem.

[[v46-11-21]]

^<<v46-11-21,21>>^ Porque, quando comem, cada um toma antecipadamente a sua própria ceia, e enquanto um fica com fome outro fica embriagado.

[[v46-11-22]]

^<<v46-11-22,22>>^ Será que vocês não têm casas onde podem comer e beber? Ou menosprezam a igreja de Deus e envergonham os que nada têm? Que posso dizer a vocês? Devo elogiá-los? Nisto certamente não posso elogiá-los.

[[v46-11-23]]

^<<v46-11-23,23>>^ Porque eu recebi do Senhor o que também lhes entreguei: que o Senhor Jesus, na noite em que foi traído, pegou um pão

[[v46-11-24]]

^<<v46-11-24,24>>^ e, tendo dado graças, o partiu e disse: "Isto é o meu corpo, que é dado por vocês; façam isto em memória de mim."

[[v46-11-25]]

^<<v46-11-25,25>>^ Do mesmo modo, depois da ceia, pegou também o cálice, dizendo: "Este cálice é a nova aliança no meu sangue; façam isto, todas as vezes que o beberem, em memória de mim."

[[v46-11-26]]

^<<v46-11-26,26>>^ Porque, todas as vezes que comerem este pão e beberem o cálice, vocês anunciam a morte do Senhor, até que ele venha.

[[v46-11-27]]

^<<v46-11-27,27>>^ Por isso, aquele que comer o pão ou beber o cálice do Senhor indignamente será réu do corpo e do sangue do Senhor.

[[v46-11-28]]

^<<v46-11-28,28>>^ Que cada um examine a si mesmo e, assim, coma do pão e beba do cálice.

[[v46-11-29]]

^<<v46-11-29,29>>^ Pois quem come e bebe sem discernir o corpo, come e bebe juízo para si.

[[v46-11-30]]

^<<v46-11-30,30>>^ É por isso que há entre vocês muitos fracos e doentes e não poucos que dormem.

[[v46-11-31]]

^<<v46-11-31,31>>^ Porque, se julgássemos a nós mesmos, não seríamos julgados.

[[v46-11-32]]

^<<v46-11-32,32>>^ Mas, quando julgados, somos disciplinados pelo Senhor, para não sermos condenados com o mundo.

[[v46-11-33]]

^<<v46-11-33,33>>^ Assim, meus irmãos, quando vocês se reúnem para comer, esperem uns pelos outros.

[[v46-11-34]]

^<<v46-11-34,34>>^ Se alguém tem fome, que coma em casa, a fim de que vocês não se reúnam para juízo. Quanto às demais coisas, eu as ordenarei quando for aí.

'''

xref:046-1-corintios/046-1-corintios-010.adoc#v46-10-0[&#60; Capítulo Anterior] | <<v46-11-0,Topo>> | xref:046-1-corintios/046-1-corintios-012.adoc#v46-12-0[Próximo Capítulo &#62;]