include::./index.adoc[]

[[v46-10-0]]
=== 1 Coríntios, 10
// naa ?, NAA - Nova Almeida Atualizada

[[v46-10-1]]

^<<v46-10-1,1>>^ Ora, irmãos, não quero que vocês ignorem que os nossos pais estiveram todos sob a nuvem, e todos passaram pelo mar,

[[v46-10-2]]

^<<v46-10-2,2>>^ e todos, em Moisés, foram batizados, tanto na nuvem como no mar.

[[v46-10-3]]

^<<v46-10-3,3>>^ Todos eles comeram do mesmo alimento espiritual

[[v46-10-4]]

^<<v46-10-4,4>>^ e beberam da mesma bebida espiritual. Porque bebiam de uma pedra espiritual que os seguia; e a pedra era Cristo.

[[v46-10-5]]

^<<v46-10-5,5>>^ Mas Deus não se agradou da maioria deles, razão pela qual ficaram prostrados no deserto.

[[v46-10-6]]

^<<v46-10-6,6>>^ Ora, estas coisas se tornaram exemplos para nós, a fim de que não cobicemos as coisas más, como eles cobiçaram.

[[v46-10-7]]

^<<v46-10-7,7>>^ Não sejam idólatras, como alguns deles foram, conforme está escrito: "O povo assentou-se para comer e beber e levantou-se para se divertir."

[[v46-10-8]]

^<<v46-10-8,8>>^ E não pratiquemos imoralidade, como alguns deles o fizeram e caíram mortos, num só dia, vinte e três mil.

[[v46-10-9]]

^<<v46-10-9,9>>^ Não ponhamos Cristo à prova, como alguns deles fizeram e foram mortos pelas serpentes.

[[v46-10-10]]

^<<v46-10-10,10>>^ Não fiquem murmurando, como alguns deles murmuraram e foram destruídos pelo exterminador.

[[v46-10-11]]

^<<v46-10-11,11>>^ Estas coisas aconteceram com eles para servir de exemplo e foram escritas como advertência a nós, para quem o fim dos tempos tem chegado.

[[v46-10-12]]

^<<v46-10-12,12>>^ Por isso, aquele que pensa estar em pé veja que não caia.

[[v46-10-13]]

^<<v46-10-13,13>>^ Não sobreveio a vocês nenhuma tentação que não fosse humana; mas Deus é fiel e não permitirá que vocês sejam tentados além do que podem suportar; pelo contrário, juntamente com a tentação proverá livramento, para que vocês a possam suportar.

[[v46-10-14]]

^<<v46-10-14,14>>^ Portanto, meus amados, fujam da idolatria.

[[v46-10-15]]

^<<v46-10-15,15>>^ Falo como a pessoas sábias; julguem vocês mesmos o que digo.

[[v46-10-16]]

^<<v46-10-16,16>>^ Não é fato que o cálice da bênção que abençoamos é a comunhão do sangue de Cristo? E não é fato que o pão que partimos é a comunhão do corpo de Cristo?

[[v46-10-17]]

^<<v46-10-17,17>>^ Porque nós, embora muitos, somos unicamente um pão, um só corpo; porque todos participamos do único pão.

[[v46-10-18]]

^<<v46-10-18,18>>^ Considerem o Israel segundo a carne. Não é verdade que aqueles que se alimentam dos sacrifícios são participantes do altar?

[[v46-10-19]]

^<<v46-10-19,19>>^ O que quero dizer com isto? Que o que é sacrificado ao ídolo é alguma coisa? Ou que o próprio ídolo tem algum valor?

[[v46-10-20]]

^<<v46-10-20,20>>^ Não! Digo que as coisas que eles sacrificam são sacrificadas a demônios e não a Deus; e eu não quero que vocês estejam em comunhão com os demônios.

[[v46-10-21]]

^<<v46-10-21,21>>^ Vocês não podem beber o cálice do Senhor e o cálice dos demônios; não podem ser participantes da mesa do Senhor e da mesa dos demônios.

[[v46-10-22]]

^<<v46-10-22,22>>^ Ou provocaremos ciúmes no Senhor? Somos, por acaso, mais fortes do que ele?

[[v46-10-23]]

^<<v46-10-23,23>>^ "Todas as coisas são lícitas", mas nem todas convêm; "todas as coisas são lícitas", mas nem todas edificam.

[[v46-10-24]]

^<<v46-10-24,24>>^ Ninguém busque o seu próprio interesse, e sim o de seu próximo.

[[v46-10-25]]

^<<v46-10-25,25>>^ Comam de tudo o que se vende no mercado, sem questionamento algum por motivo de consciência.

[[v46-10-26]]

^<<v46-10-26,26>>^ Porque do Senhor é a terra e a sua plenitude.

[[v46-10-27]]

^<<v46-10-27,27>>^ Se alguém que não é crente convidá-los para comer, e vocês quiserem ir, comam de tudo o que for posto diante de vocês, sem questionamento algum por motivo de consciência.

[[v46-10-28]]

^<<v46-10-28,28>>^ Porém, se alguém disser a vocês: "Isto é coisa sacrificada a ídolo", não comam, por causa daquele que deu a informação e por motivo de consciência;

[[v46-10-29]]

^<<v46-10-29,29>>^ consciência, digo, não a sua propriamente, mas a do outro. "Pois, por que a minha liberdade deve ser julgada pela consciência de outra pessoa?

[[v46-10-30]]

^<<v46-10-30,30>>^ Se eu participo com gratidão, por que sou criticado por causa daquilo por que dou graças?"

[[v46-10-31]]

^<<v46-10-31,31>>^ Portanto, se vocês comem, ou bebem ou fazem qualquer outra coisa, façam tudo para a glória de Deus.

[[v46-10-32]]

^<<v46-10-32,32>>^ Não se tornem motivo de tropeço nem para judeus, nem para gentios, nem para a igreja de Deus,

[[v46-10-33]]

^<<v46-10-33,33>>^ assim como também eu procuro, em tudo, ser agradável a todos, não buscando o meu próprio interesse, mas o de muitos, para que sejam salvos.

'''

xref:046-1-corintios/046-1-corintios-009.adoc#v46-9-0[&#60; Capítulo Anterior] | <<v46-10-0,Topo>> | xref:046-1-corintios/046-1-corintios-011.adoc#v46-11-0[Próximo Capítulo &#62;]