include::./index.adoc[]

[[v46-5-0]]
=== 1 Coríntios, 5
// naa ?, NAA - Nova Almeida Atualizada

[[v46-5-1]]

^<<v46-5-1,1>>^ Ouve-se por aí que entre vocês existe imoralidade, e imoralidade tal como não existe nem mesmo entre os gentios, isto é, que alguém se atreva a possuir a mulher de seu próprio pai.

[[v46-5-2]]

^<<v46-5-2,2>>^ E vocês andam cheios de orgulho, quando deveriam ter lamentado e tirado do meio de vocês quem fez uma coisa dessas.

[[v46-5-3]]

^<<v46-5-3,3>>^ Eu, na verdade, ainda que fisicamente ausente, mas presente em espírito, já sentenciei, como se estivesse presente, o autor de tal infâmia.

[[v46-5-4]]

^<<v46-5-4,4>>^ Em nome de nosso Senhor Jesus, reunidos vocês e o meu espírito, com o poder de Jesus, nosso Senhor,

[[v46-5-5]]

^<<v46-5-5,5>>^ que esse tal seja entregue a Satanás para a destruição da carne, a fim de que o espírito seja salvo no Dia do Senhor.

[[v46-5-6]]

^<<v46-5-6,6>>^ Não é bom esse orgulho que vocês têm. Por acaso vocês não sabem que um pouco de fermento leveda a massa toda?

[[v46-5-7]]

^<<v46-5-7,7>>^ Joguem fora o velho fermento, para que vocês sejam nova massa, como, de fato, já são, sem fermento. Pois também Cristo, nosso Cordeiro pascal, foi sacrificado.

[[v46-5-8]]

^<<v46-5-8,8>>^ Por isso, celebremos a festa não com o velho fermento, nem com o fermento do mal e da maldade, mas com o pão sem fermento, o pão da sinceridade e da verdade.

[[v46-5-9]]

^<<v46-5-9,9>>^ Na outra carta, já escrevi a vocês que não se associassem com os impuros.

[[v46-5-10]]

^<<v46-5-10,10>>^ Refiro-me, com isto, não propriamente aos impuros deste mundo, aos avarentos, ladrões ou idólatras, pois, neste caso, vocês teriam de sair do mundo.

[[v46-5-11]]

^<<v46-5-11,11>>^ Mas, agora, escrevo a vocês que não se associem com alguém que, dizendo-se irmão, for devasso, avarento, idólatra, maldizente, bêbado ou ladrão; nem mesmo comam com alguém assim.

[[v46-5-12]]

^<<v46-5-12,12>>^ Pois com que direito haveria eu de julgar os de fora? Mas será que vocês não devem julgar os de dentro?

[[v46-5-13]]

^<<v46-5-13,13>>^ Os de fora, esses Deus julgará. Expulsem o malfeitor do meio de vocês.

'''

xref:046-1-corintios/046-1-corintios-004.adoc#v46-4-0[&#60; Capítulo Anterior] | <<v46-5-0,Topo>> | xref:046-1-corintios/046-1-corintios-006.adoc#v46-6-0[Próximo Capítulo &#62;]