include::./index.adoc[]

[[v46-9-0]]
=== 1 Coríntios, 9
// naa ?, NAA - Nova Almeida Atualizada

[[v46-9-1]]

^<<v46-9-1,1>>^ Será que eu não sou um homem livre? Não sou apóstolo? Não vi Jesus, nosso Senhor? Por acaso vocês não são fruto do meu trabalho no Senhor?

[[v46-9-2]]

^<<v46-9-2,2>>^ Se não sou apóstolo para outros, certamente o sou para vocês! Porque vocês são o selo do meu apostolado no Senhor.

[[v46-9-3]]

^<<v46-9-3,3>>^ A minha defesa diante dos que me questionam é esta:

[[v46-9-4]]

^<<v46-9-4,4>>^ será que nós não temos o direito de comer e beber?

[[v46-9-5]]

^<<v46-9-5,5>>^ Será que não temos o direito de levar conosco uma mulher crente como esposa, como fazem os demais apóstolos, os irmãos do Senhor e Cefas?

[[v46-9-6]]

^<<v46-9-6,6>>^ Ou será que somente eu e Barnabé temos de trabalhar para viver?

[[v46-9-7]]

^<<v46-9-7,7>>^ Quem é que vai à guerra às suas próprias custas? Quem planta uma vinha e não come do seu fruto? Ou quem apascenta um rebanho e não se alimenta do leite do rebanho?

[[v46-9-8]]

^<<v46-9-8,8>>^ Será que eu digo isso apenas como homem? Não é verdade que a lei também o diz?

[[v46-9-9]]

^<<v46-9-9,9>>^ Porque na Lei de Moisés está escrito: "Não amarre a boca do boi quando ele pisa o trigo." Por acaso Deus está preocupado com bois?

[[v46-9-10]]

^<<v46-9-10,10>>^ Será que não é certamente por nossa causa que ele está dizendo isso? É claro que é por nossa causa que isso está escrito. Pois quem lavra deve fazê-lo com esperança e o que colhe deve fazê-lo na esperança de receber a parte que lhe é devida.

[[v46-9-11]]

^<<v46-9-11,11>>^ Se nós semeamos entre vocês as coisas espirituais, será muito recolhermos de vocês bens materiais?

[[v46-9-12]]

^<<v46-9-12,12>>^ Se outros participam desse direito sobre vocês, não o temos nós em maior medida? Entretanto, não fizemos uso desse direito. Pelo contrário, suportamos tudo, para não criarmos qualquer obstáculo ao evangelho de Cristo.

[[v46-9-13]]

^<<v46-9-13,13>>^ Vocês não sabem que os que prestam serviços sagrados se alimentam do próprio templo e que os que servem ao altar participam do que é oferecido sobre o altar?

[[v46-9-14]]

^<<v46-9-14,14>>^ Assim também o Senhor ordenou aos que pregam o evangelho que vivam do evangelho.

[[v46-9-15]]

^<<v46-9-15,15>>^ Eu, porém, não tenho feito uso de nenhuma destas coisas e não escrevo isto para que assim se faça comigo. Preferiria morrer a deixar que alguém me tire esta glória.

[[v46-9-16]]

^<<v46-9-16,16>>^ Se anuncio o evangelho, não tenho de que me gloriar, pois sobre mim pesa essa obrigação; porque ai de mim se não pregar o evangelho!

[[v46-9-17]]

^<<v46-9-17,17>>^ Se o faço de livre vontade, tenho recompensa; mas, se o faço por obrigação, é porque uma responsabilidade me foi confiada.

[[v46-9-18]]

^<<v46-9-18,18>>^ Nesse caso, qual é a minha recompensa? É que, anunciando o evangelho, eu o apresente de graça, para não me valer do direito que ele me dá.

[[v46-9-19]]

^<<v46-9-19,19>>^ Porque, sendo livre de todos, fiz-me escravo de todos, a fim de ganhar o maior número possível.

[[v46-9-20]]

^<<v46-9-20,20>>^ Para com os judeus, fiz-me como judeu, a fim de ganhar os judeus; para os que vivem sob o regime da Lei, como se eu mesmo assim vivesse, para ganhar os que vivem debaixo da Lei, embora eu não esteja debaixo da Lei.

[[v46-9-21]]

^<<v46-9-21,21>>^ Aos sem lei, como se eu mesmo o fosse, não estando sem lei para com Deus, mas debaixo da lei de Cristo, para ganhar os que vivem fora do regime da lei.

[[v46-9-22]]

^<<v46-9-22,22>>^ Fiz-me fraco para com os fracos, a fim de ganhar os fracos. Fiz-me tudo para com todos, a fim de, por todos os modos, salvar alguns.

[[v46-9-23]]

^<<v46-9-23,23>>^ Tudo faço por causa do evangelho, para ser também participante dele.

[[v46-9-24]]

^<<v46-9-24,24>>^ Vocês não sabem que os que correm no estádio, todos, na verdade, correm, mas um só leva o prêmio? Corram de tal maneira que ganhem o prêmio.

[[v46-9-25]]

^<<v46-9-25,25>>^ Todo atleta em tudo se domina; aqueles, para alcançar uma coroa corruptível; nós, porém, a incorruptível.

[[v46-9-26]]

^<<v46-9-26,26>>^ Assim corro também eu, não sem meta; assim luto, não como desferindo golpes no ar.

[[v46-9-27]]

^<<v46-9-27,27>>^ Mas esmurro o meu corpo e o reduzo à escravidão, para que, tendo pregado a outros, não venha eu mesmo a ser desqualificado.

'''

xref:046-1-corintios/046-1-corintios-008.adoc#v46-8-0[&#60; Capítulo Anterior] | <<v46-9-0,Topo>> | xref:046-1-corintios/046-1-corintios-010.adoc#v46-10-0[Próximo Capítulo &#62;]