include::./index.adoc[]

[[v46-14-0]]
=== 1 Coríntios, 14
// naa ?, NAA - Nova Almeida Atualizada

[[v46-14-1]]

^<<v46-14-1,1>>^ Sigam o amor e procurem com zelo os dons espirituais, principalmente o de profetizar.

[[v46-14-2]]

^<<v46-14-2,2>>^ Pois quem fala em línguas não fala para as pessoas, mas fala para Deus; ninguém o entende, pois, por meio do Espírito, fala mistérios.

[[v46-14-3]]

^<<v46-14-3,3>>^ Mas o que profetiza fala para as pessoas, edificando, exortando e consolando.

[[v46-14-4]]

^<<v46-14-4,4>>^ O que fala em línguas a si mesmo edifica, mas o que profetiza edifica a igreja.

[[v46-14-5]]

^<<v46-14-5,5>>^ Eu quero que vocês todos falem em línguas, mas muito mais que profetizem. Pois quem profetiza é superior ao que fala em línguas, a não ser que as interprete, para que a igreja receba edificação.

[[v46-14-6]]

^<<v46-14-6,6>>^ E, agora, irmãos, se eu for até aí falando em línguas, que proveito vocês terão, se eu não falar por meio de revelação, de conhecimento, de profecia ou de doutrina?

[[v46-14-7]]

^<<v46-14-7,7>>^ É assim com instrumentos inanimados, como a flauta ou a harpa, quando emitem sons. Se não emitirem sons bem distintos, como se poderá reconhecer o que se toca na flauta ou na harpa?

[[v46-14-8]]

^<<v46-14-8,8>>^ Pois também se a trombeta der som incerto, quem se preparará para a batalha?

[[v46-14-9]]

^<<v46-14-9,9>>^ Assim também vocês, se com a língua não disserem palavra compreensível, como se entenderá o que é dito? Porque vocês estarão como que falando ao vento.

[[v46-14-10]]

^<<v46-14-10,10>>^ Há, sem dúvida, muitos tipos de vozes no mundo, e nenhuma delas é sem sentido.

[[v46-14-11]]

^<<v46-14-11,11>>^ Mas, se eu não entender o significado da voz, serei estrangeiro para aquele que fala, e ele será estrangeiro para mim.

[[v46-14-12]]

^<<v46-14-12,12>>^ Assim, também vocês, visto que desejam dons espirituais, procurem progredir, para a edificação da igreja.

[[v46-14-13]]

^<<v46-14-13,13>>^ Por isso, quem fala em línguas, ore para que as possa interpretar.

[[v46-14-14]]

^<<v46-14-14,14>>^ Porque, se eu orar em línguas, o meu espírito, de fato, ora, mas a minha mente fica infrutífera.

[[v46-14-15]]

^<<v46-14-15,15>>^ Que farei, então? Vou orar com o espírito, mas também vou orar com a mente; vou cantar com o espírito, mas também vou cantar com a mente.

[[v46-14-16]]

^<<v46-14-16,16>>^ Se você louvar apenas em espírito, como o não instruído poderá dizer o "amém" depois da oração de agradecimento que você fez? Porque ele não entende o que você diz.

[[v46-14-17]]

^<<v46-14-17,17>>^ A sua oração de agradecimento pode ser muito boa, mas o outro não é edificado.

[[v46-14-18]]

^<<v46-14-18,18>>^ Dou graças a Deus, porque falo em línguas mais do que todos vocês.

[[v46-14-19]]

^<<v46-14-19,19>>^ Contudo, na igreja prefiro falar cinco palavras com o meu entendimento, para instruir os outros, do que falar dez mil palavras em línguas.

[[v46-14-20]]

^<<v46-14-20,20>>^ Irmãos, não sejam meninos no entendimento. Quanto à maldade, sim, sejam crianças; mas, quanto ao entendimento, sejam pessoas maduras.

[[v46-14-21]]

^<<v46-14-21,21>>^ Na lei está escrito: "Falarei a este povo por meio de homens de outras línguas e por meio de lábios de outros povos, e nem assim me ouvirão, diz o Senhor."

[[v46-14-22]]

^<<v46-14-22,22>>^ Portanto, as línguas constituem um sinal não para os que creem, mas para os que não creem; a profecia, no entanto, não é para os que não creem, e sim para os que creem.

[[v46-14-23]]

^<<v46-14-23,23>>^ Assim, se toda a igreja se reunir no mesmo lugar e todos se puserem a falar em línguas, no caso de entrarem pessoas não instruídas ou não crentes, será que não vão dizer que vocês estão loucos?

[[v46-14-24]]

^<<v46-14-24,24>>^ Porém, se todos profetizarem, e entrar ali um não crente ou não instruído, ele será convencido por todos e julgado por todos.

[[v46-14-25]]

^<<v46-14-25,25>>^ Os segredos que ele tem no coração se tornarão manifestos, e, assim, prostrando-se com o rosto em terra, adorará a Deus, testemunhando que Deus está, de fato, no meio de vocês.

[[v46-14-26]]

^<<v46-14-26,26>>^ Que fazer, então, irmãos? Quando vocês se reúnem, um tem um salmo, outro tem um ensino, este traz uma revelação, aquele fala em línguas, e ainda outro faz a interpretação. Que tudo seja feito para edificação.

[[v46-14-27]]

^<<v46-14-27,27>>^ No caso de alguém falar em línguas, que não sejam mais do que dois ou, quando muito, três, e isto sucessivamente, e haja alguém que interprete.

[[v46-14-28]]

^<<v46-14-28,28>>^ Mas, não havendo quem interprete, fique calado na igreja, falando consigo mesmo e com Deus.

[[v46-14-29]]

^<<v46-14-29,29>>^ Tratando-se de profetas, falem apenas dois ou três, e os outros julguem.

[[v46-14-30]]

^<<v46-14-30,30>>^ Se, porém, vier uma revelação a alguém que esteja sentado, cale-se o primeiro.

[[v46-14-31]]

^<<v46-14-31,31>>^ Porque todos poderão profetizar, um após outro, para que todos aprendam e sejam consolados.

[[v46-14-32]]

^<<v46-14-32,32>>^ Os espíritos dos profetas estão sujeitos aos próprios profetas,

[[v46-14-33]]

^<<v46-14-33,33>>^ porque Deus não é Deus de confusão, e sim de paz. Como em todas as igrejas dos santos,

[[v46-14-34]]

^<<v46-14-34,34>>^ que as mulheres se conservem caladas nas igrejas, porque não lhes é permitido falar; mas estejam submissas, como também a lei o determina.

[[v46-14-35]]

^<<v46-14-35,35>>^ Se, porém, querem aprender alguma coisa, perguntem em casa ao seu próprio marido; porque para a mulher é vergonhoso falar na igreja.

[[v46-14-36]]

^<<v46-14-36,36>>^ Por acaso a palavra de Deus se originou no meio de vocês? Ou será que ela veio exclusivamente para vocês?

[[v46-14-37]]

^<<v46-14-37,37>>^ Se alguém se considera profeta ou espiritual, reconheça que é mandamento do Senhor o que estou escrevendo para vocês.

[[v46-14-38]]

^<<v46-14-38,38>>^ E, se alguém o ignorar, será ignorado.

[[v46-14-39]]

^<<v46-14-39,39>>^ Portanto, meus irmãos, procurem com zelo o dom de profetizar e não proíbam que se fale em línguas.

[[v46-14-40]]

^<<v46-14-40,40>>^ Tudo, porém, seja feito com decência e ordem.

'''

xref:046-1-corintios/046-1-corintios-013.adoc#v46-13-0[&#60; Capítulo Anterior] | <<v46-14-0,Topo>> | xref:046-1-corintios/046-1-corintios-015.adoc#v46-15-0[Próximo Capítulo &#62;]