include::./index.adoc[]

[[v46-15-0]]
=== 1 Coríntios, 15
// naa ?, NAA - Nova Almeida Atualizada

[[v46-15-1]]

^<<v46-15-1,1>>^ Irmãos, venho lembrar-lhes o evangelho que anunciei a vocês, o qual vocês receberam e no qual continuam firmes.

[[v46-15-2]]

^<<v46-15-2,2>>^ Por meio dele vocês também são salvos, se retiverem a palavra assim tal como a preguei a vocês, a menos que tenham crido em vão.

[[v46-15-3]]

^<<v46-15-3,3>>^ Antes de tudo, entreguei a vocês o que também recebi: que Cristo morreu pelos nossos pecados, segundo as Escrituras,

[[v46-15-4]]

^<<v46-15-4,4>>^ e que foi sepultado e ressuscitou ao terceiro dia, segundo as Escrituras.

[[v46-15-5]]

^<<v46-15-5,5>>^ E apareceu a Cefas e, depois, aos doze.

[[v46-15-6]]

^<<v46-15-6,6>>^ Depois, foi visto por mais de quinhentos irmãos de uma só vez, dos quais a maioria ainda vive; porém alguns já dormem.

[[v46-15-7]]

^<<v46-15-7,7>>^ Depois, foi visto por Tiago e, mais tarde, por todos os apóstolos.

[[v46-15-8]]

^<<v46-15-8,8>>^ Por último, depois de todos, foi visto também por mim, como por um nascido fora de tempo.

[[v46-15-9]]

^<<v46-15-9,9>>^ Porque eu sou o menor dos apóstolos, e nem mesmo sou digno de ser chamado apóstolo, pois persegui a igreja de Deus.

[[v46-15-10]]

^<<v46-15-10,10>>^ Mas, pela graça de Deus, sou o que sou. E a sua graça, que me foi concedida, não se tornou vã. Pelo contrário, trabalhei muito mais do que todos eles; todavia, não eu, mas a graça de Deus comigo.

[[v46-15-11]]

^<<v46-15-11,11>>^ Portanto, seja eu ou sejam eles, assim pregamos e assim vocês creram.

[[v46-15-12]]

^<<v46-15-12,12>>^ Ora, se o que se prega é que Cristo ressuscitou dentre os mortos, como alguns de vocês afirmam que não há ressurreição de mortos?

[[v46-15-13]]

^<<v46-15-13,13>>^ E, se não há ressurreição de mortos, então Cristo não ressuscitou.

[[v46-15-14]]

^<<v46-15-14,14>>^ E, se Cristo não ressuscitou, é vã a nossa pregação, e é vã a fé que vocês têm.

[[v46-15-15]]

^<<v46-15-15,15>>^ Além disso, somos tidos por falsas testemunhas de Deus, porque temos testemunhado contra Deus que ele ressuscitou a Cristo, ao qual ele não ressuscitou, se é certo que os mortos não ressuscitam.

[[v46-15-16]]

^<<v46-15-16,16>>^ Porque, se os mortos não ressuscitam, também Cristo não ressuscitou.

[[v46-15-17]]

^<<v46-15-17,17>>^ E, se Cristo não ressuscitou, é vã a fé que vocês têm, e vocês ainda permanecem nos seus pecados.

[[v46-15-18]]

^<<v46-15-18,18>>^ E ainda mais: os que adormeceram em Cristo estão perdidos.

[[v46-15-19]]

^<<v46-15-19,19>>^ Se a nossa esperança em Cristo se limita apenas a esta vida, somos as pessoas mais infelizes deste mundo.

[[v46-15-20]]

^<<v46-15-20,20>>^ Mas, de fato, Cristo ressuscitou dentre os mortos, sendo ele as primícias dos que dormem.

[[v46-15-21]]

^<<v46-15-21,21>>^ Visto que a morte veio por um homem, também por um homem veio a ressurreição dos mortos.

[[v46-15-22]]

^<<v46-15-22,22>>^ Porque, assim como, em Adão, todos morrem, assim também todos serão vivificados em Cristo.

[[v46-15-23]]

^<<v46-15-23,23>>^ Cada um, porém, na sua ordem: Cristo, as primícias; depois, os que são de Cristo, na sua vinda.

[[v46-15-24]]

^<<v46-15-24,24>>^ E então virá o fim, quando ele entregar o Reino ao Deus e Pai, quando houver destruído todo principado, bem como toda potestade e poder.

[[v46-15-25]]

^<<v46-15-25,25>>^ Porque é necessário que ele reine até que tenha posto todos os inimigos debaixo dos seus pés.

[[v46-15-26]]

^<<v46-15-26,26>>^ O último inimigo a ser destruído é a morte.

[[v46-15-27]]

^<<v46-15-27,27>>^ Porque "ele sujeitou todas as coisas debaixo dos seus pés". E, quando diz que todas as coisas lhe estão sujeitas, certamente exclui aquele que tudo lhe sujeitou.

[[v46-15-28]]

^<<v46-15-28,28>>^ Quando, porém, todas as coisas lhe estiverem sujeitas, então o próprio Filho também se sujeitará àquele que todas as coisas lhe sujeitou, para que Deus seja tudo em todos.

[[v46-15-29]]

^<<v46-15-29,29>>^ De outra maneira, que farão os que se batizam por causa dos mortos? Se de fato os mortos não ressuscitam, por que se batizam por causa deles?

[[v46-15-30]]

^<<v46-15-30,30>>^ E por que também nós nos expomos a perigos a toda hora?

[[v46-15-31]]

^<<v46-15-31,31>>^ Dia após dia, morro! Eu afirmo isso, irmãos, pelo orgulho que tenho de vocês, em Cristo Jesus, nosso Senhor.

[[v46-15-32]]

^<<v46-15-32,32>>^ Se, como homem, lutei em Éfeso contra feras, qual foi o meu proveito? Se os mortos não ressuscitam, "comamos e bebamos, porque amanhã morreremos".

[[v46-15-33]]

^<<v46-15-33,33>>^ Não se enganem: "As más companhias corrompem os bons costumes."

[[v46-15-34]]

^<<v46-15-34,34>>^ Voltem à sobriedade, como convém, e não pequem. Porque alguns ainda não têm conhecimento de Deus. Digo isto para vergonha de vocês.

[[v46-15-35]]

^<<v46-15-35,35>>^ Mas alguém dirá: "Como é que os mortos ressuscitam? E com que corpo virão?"

[[v46-15-36]]

^<<v46-15-36,36>>^ Insensato! O que você semeia não nasce, se primeiro não morrer.

[[v46-15-37]]

^<<v46-15-37,37>>^ E, quando semeia, você não semeia o corpo que há de ser, mas o simples grão, como de trigo ou de qualquer outra semente.

[[v46-15-38]]

^<<v46-15-38,38>>^ Mas Deus lhe dá corpo como ele quer dar e a cada uma das sementes dá o seu corpo apropriado.

[[v46-15-39]]

^<<v46-15-39,39>>^ Nem toda carne é a mesma; porém uma é a carne dos seres humanos; outra, a dos animais; outra, a das aves; e outra, a dos peixes.

[[v46-15-40]]

^<<v46-15-40,40>>^ Também há corpos celestiais e corpos terrestres; e, sem dúvida, uma é a glória dos celestiais, e outra, a dos terrestres.

[[v46-15-41]]

^<<v46-15-41,41>>^ Uma é a glória do sol; outra, a glória da lua; e outra, a das estrelas. Porque até entre estrela e estrela há diferenças de glória.

[[v46-15-42]]

^<<v46-15-42,42>>^ Pois assim também é a ressurreição dos mortos. Semeia-se o corpo na corrupção, ressuscita na incorrupção. Semeia-se em desonra, ressuscita em glória.

[[v46-15-43]]

^<<v46-15-43,43>>^ Semeia-se em fraqueza, ressuscita em poder.

[[v46-15-44]]

^<<v46-15-44,44>>^ Semeia-se corpo natural, ressuscita corpo espiritual. Se há corpo natural, há também corpo espiritual.

[[v46-15-45]]

^<<v46-15-45,45>>^ Pois assim está escrito: "O primeiro homem, Adão, se tornou um ser vivente." Mas o último Adão é espírito vivificante.

[[v46-15-46]]

^<<v46-15-46,46>>^ O que vem primeiro não é o espiritual, e sim o natural; depois vem o espiritual.

[[v46-15-47]]

^<<v46-15-47,47>>^ O primeiro homem, formado do pó da terra, é terreno; o segundo homem é do céu.

[[v46-15-48]]

^<<v46-15-48,48>>^ Como foi o homem terreno, assim também são os demais que são feitos do pó da terra; e, como é o homem celestial, assim também são os celestiais.

[[v46-15-49]]

^<<v46-15-49,49>>^ E, assim como trouxemos a imagem do homem terreno, traremos também a imagem do homem celestial.

[[v46-15-50]]

^<<v46-15-50,50>>^ Com isto quero dizer, irmãos, que a carne e o sangue não podem herdar o Reino de Deus, nem a corrupção herdar a incorrupção.

[[v46-15-51]]

^<<v46-15-51,51>>^ Eis que vou lhes revelar um mistério: nem todos dormiremos, mas todos seremos transformados

[[v46-15-52]]

^<<v46-15-52,52>>^ num momento, num abrir e fechar de olhos, ao ressoar da última trombeta. A trombeta soará, os mortos ressuscitarão incorruptíveis, e nós seremos transformados.

[[v46-15-53]]

^<<v46-15-53,53>>^ Porque é necessário que este corpo corruptível se revista da incorruptibilidade, e que o corpo mortal se revista da imortalidade.

[[v46-15-54]]

^<<v46-15-54,54>>^ E, quando este corpo corruptível se revestir de incorruptibilidade e o que é mortal se revestir de imortalidade, então se cumprirá a palavra que está escrita: "Tragada foi a morte pela vitória."

[[v46-15-55]]

^<<v46-15-55,55>>^ "Onde está, ó morte, a sua vitória? Onde está, ó morte, o seu aguilhão?"

[[v46-15-56]]

^<<v46-15-56,56>>^ O aguilhão da morte é o pecado, e a força do pecado é a lei.

[[v46-15-57]]

^<<v46-15-57,57>>^ Graças a Deus, que nos dá a vitória por meio de nosso Senhor Jesus Cristo.

[[v46-15-58]]

^<<v46-15-58,58>>^ Portanto, meus amados irmãos, sejam firmes, inabaláveis e sempre abundantes na obra do Senhor, sabendo que, no Senhor, o trabalho de vocês não é vão.

'''

xref:046-1-corintios/046-1-corintios-014.adoc#v46-14-0[&#60; Capítulo Anterior] | <<v46-15-0,Topo>> | xref:046-1-corintios/046-1-corintios-016.adoc#v46-16-0[Próximo Capítulo &#62;]