include::./index.adoc[]

[[v9-2-0]]
=== 1 Samuel, 2
// naa ?, NAA - Nova Almeida Atualizada

[[v9-2-1]]

^<<v9-2-1,1>>^ Então Ana orou assim: O meu coração exulta no Senhor . A minha força está exaltada no Senhor . A minha boca se ri dos meus inimigos, porque me alegro na tua salvação.

[[v9-2-2]]

^<<v9-2-2,2>>^ Ninguém é santo como o Senhor , porque não há outro além de ti, e não há rocha como o nosso Deus.

[[v9-2-3]]

^<<v9-2-3,3>>^ Não multipliquem palavras de orgulho; que não saiam palavras arrogantes da boca de vocês. Porque o Senhor é o Deus da sabedoria e ele pesa na sua balança todos os feitos das pessoas.

[[v9-2-4]]

^<<v9-2-4,4>>^ O arco dos fortes é quebrado, porém os fracos são revestidos de força.

[[v9-2-5]]

^<<v9-2-5,5>>^ Os que antes estavam fartos hoje trabalham pela comida, mas os que andavam famintos não têm mais fome. Até a mulher estéril tem sete filhos, e a que tinha muitos filhos perde o vigor.

[[v9-2-6]]

^<<v9-2-6,6>>^ O Senhor  é quem tira a vida e quem a dá; ele faz descer à sepultura e faz subir.

[[v9-2-7]]

^<<v9-2-7,7>>^ O Senhor  empobrece e enriquece; humilha e também exalta.

[[v9-2-8]]

^<<v9-2-8,8>>^ Levanta o pobre do pó e tira o necessitado do monte de lixo, para o fazer assentar ao lado de príncipes, para o fazer herdar o trono de glória. Porque do Senhor são as colunas da terra, e ele firmou o mundo sobre elas.

[[v9-2-9]]

^<<v9-2-9,9>>^ Ele guarda os pés dos seus santos, mas os perversos emudecem nas trevas da morte, porque o homem não prevalece pela força.

[[v9-2-10]]

^<<v9-2-10,10>>^ O Senhor  destrói os seus inimigos; dos céus troveja contra eles. O Senhor  julga as extremidades da terra, dá força ao seu rei e exalta o poder do seu ungido.

[[v9-2-11]]

^<<v9-2-11,11>>^ Então Elcana voltou para a sua casa, em Ramá. Mas o menino ficou servindo o Senhor , diante do sacerdote Eli.

[[v9-2-12]]

^<<v9-2-12,12>>^ Os filhos de Eli eram homens malignos e não se importavam com o Senhor .

[[v9-2-13]]

^<<v9-2-13,13>>^ O costume desses sacerdotes com o povo era este: quando alguém oferecia um sacrifício, o servo do sacerdote vinha com um garfo de três dentes na mão e, enquanto a carne estava cozinhando,

[[v9-2-14]]

^<<v9-2-14,14>>^ enfiava o garfo na caldeira, na panela, no caldeirão ou na marmita, e tudo o que o garfo tirava o sacerdote pegava para si. Assim se fazia a todo o Israel que ia ali, a Siló.

[[v9-2-15]]

^<<v9-2-15,15>>^ Também antes de se queimar a gordura, o servo do sacerdote vinha e dizia ao homem que estava oferecendo o sacrifício: "Dê um pedaço desta carne para o sacerdote assar. Ele não aceitará de você carne cozida, mas apenas crua."

[[v9-2-16]]

^<<v9-2-16,16>>^ Se o ofertante lhe respondia: "Deixe que primeiro queime a gordura, depois você pode pegar o quanto quiser", o servo do sacerdote dizia: "Não. Você tem de entregar essa carne agora. Se não, eu a pegarei à força."

[[v9-2-17]]

^<<v9-2-17,17>>^ Era, pois, muito grave o pecado desses moços diante do Senhor , porque eles desprezavam a oferta do Senhor .

[[v9-2-18]]

^<<v9-2-18,18>>^ Samuel ministrava diante do Senhor , sendo ainda menino, vestido de uma estola sacerdotal de linho.

[[v9-2-19]]

^<<v9-2-19,19>>^ Sua mãe lhe fazia uma túnica pequena e, de ano em ano, a levava para ele quando ia com o seu marido oferecer o sacrifício anual.

[[v9-2-20]]

^<<v9-2-20,20>>^ Eli abençoava Elcana e a sua mulher e dizia: — Que o Senhor  dê a você filhos desta mulher, em lugar do filho que devolveu ao Senhor . E voltavam para a sua casa.

[[v9-2-21]]

^<<v9-2-21,21>>^ Assim, o Senhor  abençoou Ana e ela engravidava. Teve mais três filhos e duas filhas. E o menino Samuel crescia diante do Senhor .

[[v9-2-22]]

^<<v9-2-22,22>>^ Eli já era muito velho e ouvia tudo o que os seus filhos faziam a todo o Israel e de como se deitavam com as mulheres que serviam à porta da tenda do encontro.

[[v9-2-23]]

^<<v9-2-23,23>>^ E disse-lhes: — Por que vocês fazem essas coisas? Pois de todo este povo ouço constantemente falar das coisas más que vocês fazem.

[[v9-2-24]]

^<<v9-2-24,24>>^ Não, meus filhos, porque não é boa fama esta que ouço. Vocês estão levando o povo do Senhor  a transgredir.

[[v9-2-25]]

^<<v9-2-25,25>>^ Se um homem pecar contra o seu próximo, Deus será o árbitro. Mas, se ele pecar contra o Senhor , quem intercederá por ele? Mas eles não ouviram a voz de seu pai, porque o Senhor  os queria matar.

[[v9-2-26]]

^<<v9-2-26,26>>^ E o jovem Samuel crescia em estatura e no favor do Senhor  e dos homens.

[[v9-2-27]]

^<<v9-2-27,27>>^ Um homem de Deus veio a Eli e disse: — Assim diz o Senhor : "Por acaso não me manifestei à casa de seu pai, quando os israelitas ainda estavam no Egito, na casa de Faraó?

[[v9-2-28]]

^<<v9-2-28,28>>^ Eu o escolhi dentre todas as tribos de Israel para ser o meu sacerdote, para subir ao meu altar, para queimar o incenso e para usar a estola sacerdotal diante de mim. E dei à casa de seu pai todas as ofertas queimadas dos filhos de Israel.

[[v9-2-29]]

^<<v9-2-29,29>>^ Por que tratam com desprezo os meus sacrifícios e as minhas ofertas de cereais, que ordenei que se fizessem na minha morada? E, você, por que honra os seus filhos mais do que a mim, para que você e eles engordem com as melhores partes de todas as ofertas do meu povo de Israel?"

[[v9-2-30]]

^<<v9-2-30,30>>^ — Portanto, o Senhor , o Deus de Israel, diz: "Na verdade, eu prometi que a sua casa e a casa de seu pai andariam diante de mim para sempre. Mas agora o Senhor  diz: Longe de mim tal coisa, porque honrarei aqueles que me honram, porém desprezarei os que me desprezam.

[[v9-2-31]]

^<<v9-2-31,31>>^ Eis que vêm dias em que acabarei com o seu poder e com o poder da casa de seu pai, para que ninguém em sua casa chegue a ficar velho.

[[v9-2-32]]

^<<v9-2-32,32>>^ E você verá a aflição da morada de Deus, juntamente com o bem que farei a Israel. Mas ninguém da sua casa chegará à velhice.

[[v9-2-33]]

^<<v9-2-33,33>>^ O homem, porém, da sua linhagem a quem eu não afastar do meu altar será poupado apenas para lhe consumir os olhos e lhe entristecer a alma. E todos os descendentes da sua casa morrerão na flor da idade.

[[v9-2-34]]

^<<v9-2-34,34>>^ E o que vier a acontecer com os seus dois filhos, Hofni e Fineias, será um sinal para você: ambos morrerão no mesmo dia.

[[v9-2-35]]

^<<v9-2-35,35>>^ Então suscitarei para mim um sacerdote fiel, que fará segundo o que tenho no coração e na mente. Eu lhe edificarei uma casa estável, e ele andará diante do meu ungido para sempre.

[[v9-2-36]]

^<<v9-2-36,36>>^ E todo aquele que restar da sua casa virá a inclinar-se diante dele, para obter uma moeda de prata e um bocado de pão. E dirá: ‘Peço que você me dê um dos cargos sacerdotais, para que eu tenha um pedaço de pão para comer.’"

'''

xref:009-1-samuel/009-1-samuel-001.adoc#v9-1-0[&#60; Capítulo Anterior] | <<v9-2-0,Topo>> | xref:009-1-samuel/009-1-samuel-003.adoc#v9-3-0[Próximo Capítulo &#62;]