include::./index.adoc[]

[[v9-3-0]]
=== 1 Samuel, 3
// naa ?, NAA - Nova Almeida Atualizada

[[v9-3-1]]

^<<v9-3-1,1>>^ O menino Samuel servia o Senhor , diante de Eli. Naqueles dias, a palavra do Senhor  era muito rara; as visões não eram frequentes.

[[v9-3-2]]

^<<v9-3-2,2>>^ Certo dia, o sacerdote Eli, cujos olhos já começavam a escurecer-se, a ponto de não poder ver, estava deitado no lugar de costume.

[[v9-3-3]]

^<<v9-3-3,3>>^ Também Samuel estava deitado no templo do Senhor , onde estava a arca da aliança. Antes que a lâmpada de Deus se apagasse,

[[v9-3-4]]

^<<v9-3-4,4>>^ o Senhor  chamou o menino: — Samuel, Samuel! Este respondeu: — Eis-me aqui!

[[v9-3-5]]

^<<v9-3-5,5>>^ Então correu para onde estava Eli e disse: — Eis-me aqui, pois você me chamou. Mas Eli respondeu: — Eu não chamei você. Vá deitar. Ele foi e se deitou.

[[v9-3-6]]

^<<v9-3-6,6>>^ O Senhor  tornou a chamar: — Samuel! Este se levantou, foi até Eli e disse: — Eis-me aqui, pois você me chamou. Mas Eli respondeu: — Meu filho, eu não chamei você. Vá deitar.

[[v9-3-7]]

^<<v9-3-7,7>>^ Porém Samuel ainda não conhecia o Senhor , e a palavra do Senhor  ainda não havia sido manifestada a ele.

[[v9-3-8]]

^<<v9-3-8,8>>^ E o Senhor  chamou Samuel pela terceira vez. Ele se levantou, foi até Eli e disse: — Eis-me aqui, pois você me chamou. Então Eli entendeu que era o Senhor  quem chamava o menino.

[[v9-3-9]]

^<<v9-3-9,9>>^ Por isso, Eli disse a Samuel: — Vá deitar. Se alguém chamar, diga: "Fala, Senhor , porque o teu servo ouve." E Samuel foi para o seu lugar e se deitou.

[[v9-3-10]]

^<<v9-3-10,10>>^ Então o Senhor  veio e ali esteve, e chamou como das outras vezes: — Samuel, Samuel! Este respondeu: — Fala, porque o teu servo ouve.

[[v9-3-11]]

^<<v9-3-11,11>>^ E o Senhor  disse a Samuel: — Eis que vou fazer uma coisa tal em Israel, que todos os que a ouvirem ficarão com os dois ouvidos tinindo.

[[v9-3-12]]

^<<v9-3-12,12>>^ Naquele dia farei contra Eli tudo o que eu disse a respeito da casa dele, do começo ao fim.

[[v9-3-13]]

^<<v9-3-13,13>>^ Porque eu já disse a ele que julgarei a sua casa para sempre, pela iniquidade que ele bem conhecia, porque os seus filhos trouxeram maldição sobre si, e ele não os repreendeu.

[[v9-3-14]]

^<<v9-3-14,14>>^ Portanto, jurei à casa de Eli que a sua iniquidade nunca será expiada, nem com sacrifício, nem com oferta de cereais.

[[v9-3-15]]

^<<v9-3-15,15>>^ Samuel ficou deitado até de manhã e, então, abriu os portões da Casa do Senhor . Mas estava com medo de relatar a visão a Eli.

[[v9-3-16]]

^<<v9-3-16,16>>^ Então Eli chamou Samuel e disse: — Samuel, meu filho! Ele respondeu: — Eis-me aqui!

[[v9-3-17]]

^<<v9-3-17,17>>^ Então Eli disse: — O que foi que o Senhor  lhe falou? Peço que você não esconda nada de mim. Que Deus faça com você o que bem quiser se você me esconder alguma coisa de tudo o que ele falou.

[[v9-3-18]]

^<<v9-3-18,18>>^ Então Samuel lhe contou tudo, sem esconder nada. E Eli disse: — Ele é o Senhor . Que ele faça o que achar melhor.

[[v9-3-19]]

^<<v9-3-19,19>>^ Samuel crescia, e o Senhor  estava com ele e não deixou que nenhuma de suas palavras caísse por terra.

[[v9-3-20]]

^<<v9-3-20,20>>^ Todo o Israel, desde Dã até Berseba, reconheceu que Samuel estava confirmado como profeta do Senhor .

[[v9-3-21]]

^<<v9-3-21,21>>^ O Senhor  continuou a aparecer em Siló, porque em Siló o Senhor  se manifestava a Samuel por meio da palavra do Senhor .

'''

xref:009-1-samuel/009-1-samuel-002.adoc#v9-2-0[&#60; Capítulo Anterior] | <<v9-3-0,Topo>> | xref:009-1-samuel/009-1-samuel-004.adoc#v9-4-0[Próximo Capítulo &#62;]