include::./index.adoc[]

[[v9-9-0]]
=== 1 Samuel, 9
// naa ?, NAA - Nova Almeida Atualizada

[[v9-9-1]]

^<<v9-9-1,1>>^ Havia um homem de Benjamim, cujo nome era Quis, filho de Abiel, filho de Zeror, filho de Becorate, filho de Afias, benjamita, dono de muitos bens.

[[v9-9-2]]

^<<v9-9-2,2>>^ Ele tinha um filho chamado Saul, moço e tão belo, que entre os filhos de Israel não havia outro mais belo do que ele. Dos ombros para cima, ele sobressaía a todo o povo.

[[v9-9-3]]

^<<v9-9-3,3>>^ E aconteceu que as jumentas de Quis, pai de Saul, se extraviaram. Então Quis disse a Saul, seu filho: — Leve agora com você um dos servos e vá procurar as jumentas.

[[v9-9-4]]

^<<v9-9-4,4>>^ Eles atravessaram a região montanhosa de Efraim e a terra de Salisa, mas não as encontraram. Depois, passaram à terra de Saalim, mas as jumentas não estavam ali. Então atravessaram o território de Benjamim, mas também não as encontraram.

[[v9-9-5]]

^<<v9-9-5,5>>^ Quando chegaram à terra de Zufe, Saul disse ao servo que estava com ele: — Vamos voltar, porque, se não, o meu pai vai deixar de se preocupar com as jumentas para começar a se afligir por causa de nós.

[[v9-9-6]]

^<<v9-9-6,6>>^ Porém o servo respondeu: — Nesta cidade mora um homem de Deus que é muito estimado. Tudo o que ele diz acontece. Vamos agora até lá. Talvez ele possa nos mostrar o caminho que devemos seguir.

[[v9-9-7]]

^<<v9-9-7,7>>^ Então Saul disse ao servo: — Mas, se formos para lá, o que levaremos para aquele homem? Porque o pão que tínhamos em nossas sacolas acabou, e não temos nenhum presente para levar ao homem de Deus. Ou será que temos?

[[v9-9-8]]

^<<v9-9-8,8>>^ O servo respondeu a Saul: — Tenho ainda em mãos três gramas de prata, que darei ao homem de Deus, para que nos mostre o caminho.

[[v9-9-9]]

^<<v9-9-9,9>>^ (Antigamente, em Israel, quando alguém ia consultar a Deus, dizia: "Vamos falar com o vidente." Porque antigamente o profeta de hoje se chamava vidente.)

[[v9-9-10]]

^<<v9-9-10,10>>^ Então Saul disse ao servo: — Você tem razão. Vamos lá! E foram à cidade onde morava o homem de Deus.

[[v9-9-11]]

^<<v9-9-11,11>>^ Quando subiam pela encosta da cidade, encontraram umas moças que saíam a tirar água e lhes perguntaram: — O vidente está aqui?

[[v9-9-12]]

^<<v9-9-12,12>>^ Elas responderam: — Está. Eis que ali vai ele, à sua frente. Vão depressa! Hoje ele veio à cidade, porque o povo vai oferecer um sacrifício no lugar alto.

[[v9-9-13]]

^<<v9-9-13,13>>^ Ao entrarem na cidade, vocês o encontrarão, antes que ele suba ao lugar alto para comer. Porque o povo não comerá enquanto ele não chegar, porque ele tem de abençoar o sacrifício, e só depois os convidados irão comer. Vão agora, porque hoje vocês o acharão.

[[v9-9-14]]

^<<v9-9-14,14>>^ Então eles foram até a cidade. Quando estavam entrando, eis que Samuel saiu ao encontro deles, para subir ao lugar alto.

[[v9-9-15]]

^<<v9-9-15,15>>^ Ora, um dia antes de Saul chegar, o Senhor  tinha revelado isso a Samuel, dizendo:

[[v9-9-16]]

^<<v9-9-16,16>>^ — Amanhã a estas horas, enviarei a você um homem da terra de Benjamim, o qual você ungirá por príncipe sobre o meu povo de Israel. E ele livrará o meu povo das mãos dos filisteus. Porque olhei para o meu povo, pois o seu clamor chegou a mim.

[[v9-9-17]]

^<<v9-9-17,17>>^ Quando Samuel viu Saul, o Senhor  lhe disse: — Eis o homem de quem lhe falei. Este dominará sobre o meu povo.

[[v9-9-18]]

^<<v9-9-18,18>>^ Saul se aproximou de Samuel no meio do portão e disse: — Peço que, por favor, me mostre onde é a casa do vidente.

[[v9-9-19]]

^<<v9-9-19,19>>^ Samuel respondeu a Saul: — Eu sou o vidente. Suba adiante de mim ao lugar alto. Hoje vocês comerão comigo. Pela manhã eu o deixarei ir e lhe contarei tudo o que está no seu coração.

[[v9-9-20]]

^<<v9-9-20,20>>^ Quanto às jumentas que se perderam há três dias, não se preocupe com elas, porque já foram encontradas. E para quem está reservado tudo o que é precioso em Israel? Será que não é para você e para toda a casa de seu pai?

[[v9-9-21]]

^<<v9-9-21,21>>^ Então Saul respondeu: — Por acaso não sou eu um benjamita, da menor das tribos de Israel? E não é a minha família a menor de todas as famílias da tribo de Benjamim? Por que, então, você me fala com tais palavras?

[[v9-9-22]]

^<<v9-9-22,22>>^ Samuel levou Saul e o servo dele à sala de jantar e lhes deu o lugar de honra entre os convidados, que eram cerca de trinta pessoas.

[[v9-9-23]]

^<<v9-9-23,23>>^ Então Samuel disse ao cozinheiro: — Traga aquela porção que eu lhe entreguei, aquela que eu lhe pedi para deixar reservada.

[[v9-9-24]]

^<<v9-9-24,24>>^ O cozinheiro pegou a coxa com o que havia nela e a pôs diante de Saul. Então Samuel disse: — Aqui está o que foi reservado. Pegue e coma, pois foi guardado para você para esta ocasião, quando eu disse: "Convidei o povo." Assim, Saul comeu com Samuel naquele dia.

[[v9-9-25]]

^<<v9-9-25,25>>^ Depois que desceram do lugar alto para a cidade, Samuel falou com Saul no terraço.

[[v9-9-26]]

^<<v9-9-26,26>>^ Levantaram-se de madrugada, quase ao raiar do dia, e Samuel chamou Saul para o terraço, dizendo: — Levante-se, e eu irei com você para lhe indicar o caminho. Saul levantou-se, e saíram ambos, ele e Samuel.

[[v9-9-27]]

^<<v9-9-27,27>>^ Quando estavam chegando à extremidade da cidade, Samuel disse a Saul: — Diga ao servo que passe à frente de nós. E você, quando ele tiver ido embora, espere um pouco, para que eu possa transmitir a você a palavra de Deus.

'''

xref:009-1-samuel/009-1-samuel-008.adoc#v9-8-0[&#60; Capítulo Anterior] | <<v9-9-0,Topo>> | xref:009-1-samuel/009-1-samuel-010.adoc#v9-10-0[Próximo Capítulo &#62;]