include::./index.adoc[]

[[v9-6-0]]
=== 1 Samuel, 6
// naa ?, NAA - Nova Almeida Atualizada

[[v9-6-1]]

^<<v9-6-1,1>>^ A arca do Senhor  esteve sete meses na terra dos filisteus.

[[v9-6-2]]

^<<v9-6-2,2>>^ Estes chamaram os sacerdotes e os adivinhos e perguntaram: — Que faremos com a arca do Senhor ? Digam-nos como a devolveremos para o seu lugar.

[[v9-6-3]]

^<<v9-6-3,3>>^ Eles responderam: — Se devolverem a arca do Deus de Israel, não a mandem vazia, mas enviem também a ele uma oferta pela culpa. Então vocês serão curados e saberão por que a mão dele continua pesando sobre vocês.

[[v9-6-4]]

^<<v9-6-4,4>>^ Então os filisteus perguntaram: — Que oferta pela culpa devemos mandar? Os sacerdotes e adivinhos responderam: — Mandem cinco tumores de ouro e cinco ratos de ouro, segundo o número dos governantes dos filisteus, porque a praga é uma e a mesma sobre todos vocês e sobre todos os seus governantes.

[[v9-6-5]]

^<<v9-6-5,5>>^ Façam imitações dos tumores e dos ratos que andam destruindo a terra, e deem glória ao Deus de Israel. Assim ele talvez alivie a sua mão de cima de vocês e do deus e da terra de vocês.

[[v9-6-6]]

^<<v9-6-6,6>>^ Por que vocês endureceriam o coração, como os egípcios e Faraó fizeram? Não é verdade que, depois que Deus os maltratou, eles deixaram os israelitas sair, e eles foram embora?

[[v9-6-7]]

^<<v9-6-7,7>>^ — Agora, pois, façam um carro novo, arranjem duas vacas com crias, sobre as quais nunca foi colocado jugo, e amarrem as duas ao carro; quanto aos bezerros, levem-nos para casa.

[[v9-6-8]]

^<<v9-6-8,8>>^ Então peguem a arca do Senhor  e a ponham sobre o carro. E num cofre, ao lado dele, ponham as figuras de ouro que vocês vão lhe enviar como oferta pela culpa; depois, deixem o carro ir.

[[v9-6-9]]

^<<v9-6-9,9>>^ Fiquem observando: se ele subir pelo caminho de Bete-Semes, que leva a seu território, então foi o Deus de Israel que nos fez este grande mal. Mas, se não, saberemos que não foi a sua mão que nos atingiu, e que isso nos aconteceu por acaso.

[[v9-6-10]]

^<<v9-6-10,10>>^ Os homens fizeram isso: pegaram duas vacas com crias e as amarraram ao carro; e encerraram os seus bezerros em casa.

[[v9-6-11]]

^<<v9-6-11,11>>^ Puseram a arca do Senhor  sobre o carro, junto com o cofre que continha os ratos de ouro e as imitações dos tumores.

[[v9-6-12]]

^<<v9-6-12,12>>^ As vacas se encaminharam diretamente para Bete-Semes e, andando e berrando, seguiam sempre por esse mesmo caminho, sem se desviarem nem para a direita nem para a esquerda. Os governantes dos filisteus foram atrás delas, até a fronteira com Bete-Semes.

[[v9-6-13]]

^<<v9-6-13,13>>^ O povo de Bete-Semes andava fazendo a colheita do trigo no vale. Quando levantaram os olhos, viram a arca e ficaram muito contentes.

[[v9-6-14]]

^<<v9-6-14,14>>^ O carro veio até o campo de Josué, o bete-semita, e parou ali, onde havia uma grande pedra. Eles cortaram a madeira do carro em pedaços e ofereceram as vacas ao Senhor , em holocausto.

[[v9-6-15]]

^<<v9-6-15,15>>^ Os levitas desceram a arca do Senhor  e também o cofre que estava junto a ela, em que estavam os objetos de ouro, e os puseram sobre a grande pedra. No mesmo dia, os homens de Bete-Semes ofereceram holocaustos e sacrifícios ao Senhor .

[[v9-6-16]]

^<<v9-6-16,16>>^ Os cinco governantes dos filisteus viram aquilo e voltaram para Ecrom no mesmo dia.

[[v9-6-17]]

^<<v9-6-17,17>>^ Estes são os tumores de ouro que os filisteus enviaram ao Senhor  como oferta pela culpa: um por Asdode; outro por Gaza; outro por Asquelom; outro por Gate; e outro por Ecrom.

[[v9-6-18]]

^<<v9-6-18,18>>^ Enviaram também os ratos de ouro, segundo o número de todas as cidades dos filisteus, pertencentes aos cinco governantes, desde as cidades fortificadas até as aldeias campestres. A grande pedra, sobre a qual puseram a arca do Senhor , está até o dia de hoje no campo de Josué, o bete-semita.

[[v9-6-19]]

^<<v9-6-19,19>>^ O Senhor  feriu os homens de Bete-Semes, porque olharam para dentro da arca do Senhor , matando setenta deles. Então o povo chorou, porque o Senhor  tinha feito tão grande matança entre eles.

[[v9-6-20]]

^<<v9-6-20,20>>^ Os homens de Bete-Semes disseram: — Quem poderia estar diante do Senhor , este Deus santo? E para onde subirá, para que fique longe de nós?

[[v9-6-21]]

^<<v9-6-21,21>>^ Então enviaram mensageiros aos moradores de Quiriate-Jearim, dizendo: — Os filisteus devolveram a arca do Senhor . Venham até aqui e levem a arca com vocês.

'''

xref:009-1-samuel/009-1-samuel-005.adoc#v9-5-0[&#60; Capítulo Anterior] | <<v9-6-0,Topo>> | xref:009-1-samuel/009-1-samuel-007.adoc#v9-7-0[Próximo Capítulo &#62;]