include::./index.adoc[]

[[v9-25-0]]
=== 1 Samuel, 25
// naa ?, NAA - Nova Almeida Atualizada

[[v9-25-1]]

^<<v9-25-1,1>>^ Samuel morreu, e todos os filhos de Israel se juntaram e o prantearam. E o sepultaram na sua casa, em Ramá. Davi se levantou e foi ao deserto de Parã.

[[v9-25-2]]

^<<v9-25-2,2>>^ Havia um homem, em Maom, que tinha as suas propriedades no Carmelo. Era um homem muito rico: tinha três mil ovelhas e mil cabras. E ele estava tosquiando as suas ovelhas no Carmelo.

[[v9-25-3]]

^<<v9-25-3,3>>^ O nome desse homem era Nabal, e a mulher dele se chamava Abigail. Ela era inteligente e bonita, porém Nabal era grosseiro e mau em tudo o que fazia. Era descendente de Calebe.

[[v9-25-4]]

^<<v9-25-4,4>>^ Quando Davi, no deserto, ouviu dizer que Nabal tosquiava as suas ovelhas,

[[v9-25-5]]

^<<v9-25-5,5>>^ enviou dez rapazes e lhes disse: — Vão ao Carmelo falar com Nabal e perguntem-lhe, em meu nome, como está.

[[v9-25-6]]

^<<v9-25-6,6>>^ Digam àquele afortunado: "Paz para você, paz para a sua casa e paz para tudo o que é seu!

[[v9-25-7]]

^<<v9-25-7,7>>^ Soube que você está fazendo a tosquia das suas ovelhas. Os seus pastores estiveram conosco e nós não os maltratamos e nada lhes faltou durante todo o tempo em que estiveram no Carmelo.

[[v9-25-8]]

^<<v9-25-8,8>>^ Pergunte aos seus moços, e eles lhe dirão. Portanto, que os meus rapazes encontrem favor em sua presença, porque chegamos em boa hora. Por favor, dê a estes seus servos e a Davi, seu filho, qualquer coisa que você tiver à mão."

[[v9-25-9]]

^<<v9-25-9,9>>^ Os rapazes de Davi foram e falaram a Nabal todas essas palavras em nome de Davi. Depois, ficaram esperando.

[[v9-25-10]]

^<<v9-25-10,10>>^ E Nabal deu a seguinte resposta aos servos de Davi: — Quem é Davi? E quem é o filho de Jessé? Muitos são, hoje em dia, os servos que fogem do seu senhor.

[[v9-25-11]]

^<<v9-25-11,11>>^ Vocês acham que eu vou pegar o meu pão, a minha água e a carne dos animais que abati para os meus tosquiadores e dar a homens que eu não sei de onde vêm?

[[v9-25-12]]

^<<v9-25-12,12>>^ Então os rapazes de Davi se puseram a caminho e voltaram. Ao chegarem, disseram a Davi tudo o que Nabal havia falado.

[[v9-25-13]]

^<<v9-25-13,13>>^ Então Davi disse aos seus homens: — Que cada um cinja a sua espada! E cada um cingiu a sua espada, e também Davi cingiu a sua. Cerca de quatrocentos homens seguiram Davi, enquanto duzentos ficaram com a bagagem.

[[v9-25-14]]

^<<v9-25-14,14>>^ Nesse meio-tempo, um dos moços de Nabal foi falar com Abigail, a mulher de Nabal, dizendo: — Davi enviou do deserto mensageiros para saudar o nosso senhor, mas ele os pôs a correr.

[[v9-25-15]]

^<<v9-25-15,15>>^ No entanto, aqueles homens nos têm sido muito bons, e nunca fomos maltratados por eles e de nenhuma coisa sentimos falta em todos os dias de nosso trato com eles, quando estávamos no campo.

[[v9-25-16]]

^<<v9-25-16,16>>^ Eles eram como um muro ao nosso redor, tanto de dia como de noite, todos os dias que estivemos com eles apascentando as ovelhas.

[[v9-25-17]]

^<<v9-25-17,17>>^ E agora pense bem e veja o que pode fazer, porque o mal já está determinado contra o nosso senhor e contra toda a sua casa; ele é homem maligno, e não há quem consiga falar com ele.

[[v9-25-18]]

^<<v9-25-18,18>>^ Então Abigail pegou, a toda pressa, duzentos pães, dois odres de vinho, cinco ovelhas preparadas, cinco medidas de trigo tostado, cem cachos de passas e duzentas pastas de figos, e pôs tudo sobre jumentos.

[[v9-25-19]]

^<<v9-25-19,19>>^ Então disse aos seus servos: — Vão na minha frente, que eu vou logo atrás. Porém ela não contou nada a seu marido Nabal.

[[v9-25-20]]

^<<v9-25-20,20>>^ Enquanto ela, cavalgando um jumento, descia, encoberta pelo monte, Davi e seus homens também desciam, e ela se encontrou com eles.

[[v9-25-21]]

^<<v9-25-21,21>>^ Ora, Davi tinha dito: — Com certeza, de nada adiantou ter protegido tudo o que esse homem possui no deserto, e de nada sentiu falta de tudo o que lhe pertence; ele me pagou o bem com o mal.

[[v9-25-22]]

^<<v9-25-22,22>>^ Que Deus me castigue, se, até o amanhecer, eu não matar todos os do sexo masculino que estão com ele.

[[v9-25-23]]

^<<v9-25-23,23>>^ Quando Abigail viu Davi, desceu depressa do jumento e prostrou-se sobre o rosto diante de Davi, inclinando-se até o chão.

[[v9-25-24]]

^<<v9-25-24,24>>^ Lançou-se aos pés de Davi e disse: — Meu senhor, que a culpa recaia sobre mim. Permita que esta sua serva fale e escute as palavras da sua serva.

[[v9-25-25]]

^<<v9-25-25,25>>^ Que o meu senhor não se importe com aquele homem maligno, a saber, com Nabal, porque ele é o que significa o seu nome. Nabal é o seu nome, e a tolice o acompanha. Eu, porém, esta sua serva, não vi os rapazes que o meu senhor mandou.

[[v9-25-26]]

^<<v9-25-26,26>>^ Agora, meu senhor, tão certo como vive o Senhor  Deus e tão certo como vive a sua alma, foi o Senhor  Deus quem o impediu de derramar sangue e de fazer justiça com as próprias mãos. Que os seus inimigos e os que procuram fazer mal ao meu senhor sejam como Nabal.

[[v9-25-27]]

^<<v9-25-27,27>>^ Este é o presente que esta sua serva trouxe ao meu senhor; que ele seja dado aos rapazes que seguem o meu senhor.

[[v9-25-28]]

^<<v9-25-28,28>>^ Perdoe a transgressão desta sua serva. Pois o Senhor  Deus certamente firmará a casa de meu senhor, porque ele está travando as batalhas do Senhor  Deus. E que não se ache mal em meu senhor durante toda a sua vida.

[[v9-25-29]]

^<<v9-25-29,29>>^ E, se algum homem se levantar para o perseguir e tirar-lhe a vida, a vida de meu senhor será atada no feixe dos que vivem com o Senhor , seu Deus. Porém a vida de seus inimigos, este a lançará fora como se a atirasse da cavidade de uma funda.

[[v9-25-30]]

^<<v9-25-30,30>>^ E, quando o Senhor  Deus tiver feito a meu senhor todo o bem que falou a seu respeito e o tiver colocado como príncipe sobre Israel,

[[v9-25-31]]

^<<v9-25-31,31>>^ então meu senhor não terá motivo de pesar ou de remorso por ter derramado sangue inocente e por ter se vingado com as próprias mãos. E, quando o Senhor  Deus tiver feito o bem a meu senhor, então lembre-se desta sua serva.

[[v9-25-32]]

^<<v9-25-32,32>>^ Então Davi disse a Abigail: — Bendito o Senhor , Deus de Israel, que hoje mandou você ao meu encontro.

[[v9-25-33]]

^<<v9-25-33,33>>^ Bendita seja a sua prudência, e bendita seja você mesma, que hoje me impediu de derramar sangue e de me vingar com as minhas próprias mãos.

[[v9-25-34]]

^<<v9-25-34,34>>^ Porque, tão certo como vive o Senhor , Deus de Israel, que me impediu de fazer mal a você, se você não tivesse se apressado e não tivesse vindo ao meu encontro, não teria ficado a Nabal, até o amanhecer, nem um sequer do sexo masculino.

[[v9-25-35]]

^<<v9-25-35,35>>^ Então Davi recebeu da mão de Abigail o que esta lhe havia trazido e lhe disse: — Volte em paz para a sua casa. Como você pode ver, dei ouvidos ao que você me falou e atendi o seu pedido.

[[v9-25-36]]

^<<v9-25-36,36>>^ Abigail voltou para junto de Nabal. Eis que ele fazia em casa um banquete, como banquete de rei. O seu coração estava alegre, e ele, bastante embriagado. Por isso ela não lhe contou absolutamente nada, até o amanhecer.

[[v9-25-37]]

^<<v9-25-37,37>>^ Pela manhã, quando Nabal já estava livre do vinho, sua mulher lhe contou tudo. Então o coração dele amorteceu dentro do peito, e ele ficou como uma pedra.

[[v9-25-38]]

^<<v9-25-38,38>>^ Passados uns dez dias, o Senhor  feriu Nabal, e ele morreu.

[[v9-25-39]]

^<<v9-25-39,39>>^ Quando Davi soube que Nabal havia morrido, disse: — Bendito seja o Senhor , que pleiteou a causa da afronta que recebi de Nabal e livrou este seu servo de fazer o mal. O Senhor  fez com que a maldade de Nabal caísse sobre a própria cabeça dele. Então Davi mandou um recado a Abigail, dizendo que desejava tomá-la por mulher.

[[v9-25-40]]

^<<v9-25-40,40>>^ Os servos de Davi foram até Abigail, no Carmelo, e lhe disseram: — Davi nos mandou buscá-la para que a senhora seja sua mulher.

[[v9-25-41]]

^<<v9-25-41,41>>^ Então ela se levantou, se inclinou com o rosto em terra e disse: — Eis que esta sua serva servirá de criada para lavar os pés dos criados de meu senhor.

[[v9-25-42]]

^<<v9-25-42,42>>^ Abigail se dispôs imediatamente e montou o seu jumento. E ela, acompanhada pelas cinco moças que a serviam, seguiu os mensageiros de Davi, que a recebeu por mulher.

[[v9-25-43]]

^<<v9-25-43,43>>^ Davi também havia tomado por mulher Ainoã de Jezreel, e ambas foram suas mulheres.

[[v9-25-44]]

^<<v9-25-44,44>>^ Saul tinha dado sua filha Mical, mulher de Davi, a Palti, filho de Laís, que era de Galim.

'''

xref:009-1-samuel/009-1-samuel-024.adoc#v9-24-0[&#60; Capítulo Anterior] | <<v9-25-0,Topo>> | xref:009-1-samuel/009-1-samuel-026.adoc#v9-26-0[Próximo Capítulo &#62;]