include::./index.adoc[]

[[v9-24-0]]
=== 1 Samuel, 24
// naa ?, NAA - Nova Almeida Atualizada

[[v9-24-1]]

^<<v9-24-1,1>>^ Quando Saul voltou de perseguir os filisteus, foi-lhe dito: — Eis que Davi está no deserto de En-Gedi.

[[v9-24-2]]

^<<v9-24-2,2>>^ Então Saul tomou três mil homens, escolhidos dentre todo o Israel, e foi ao encalço de Davi e dos seus homens, nas encostas das rochas das cabras selvagens.

[[v9-24-3]]

^<<v9-24-3,3>>^ Chegou a uns currais de ovelhas no caminho, onde havia uma caverna. Saul entrou nela, para fazer as suas necessidades. Ora, Davi e os seus homens estavam sentados no mais interior da caverna.

[[v9-24-4]]

^<<v9-24-4,4>>^ Então eles disseram a Davi: — Hoje é o dia do qual o Senhor  lhe falou: "Eis que eu entrego o seu inimigo nas suas mãos, e você fará com ele o que bem quiser." Então Davi se levantou e, sem ser notado, cortou a ponta do manto de Saul.

[[v9-24-5]]

^<<v9-24-5,5>>^ Mas depois Davi ficou com dor no coração por ter cortado a ponta do manto de Saul

[[v9-24-6]]

^<<v9-24-6,6>>^ e disse aos seus homens: — O Senhor  Deus me livre de fazer tal coisa ao meu senhor, isto é, que eu estenda a mão contra ele, pois é o ungido do Senhor .

[[v9-24-7]]

^<<v9-24-7,7>>^ Com estas palavras, Davi conteve os seus homens e não permitiu que se levantassem contra Saul. Então Saul se levantou, saiu da caverna e seguiu o seu caminho.

[[v9-24-8]]

^<<v9-24-8,8>>^ Depois, também Davi se levantou e, saindo da caverna, gritou a Saul, dizendo: — Ó rei, meu senhor! Quando Saul olhou para trás, Davi se inclinou e lhe fez reverência, com o rosto em terra.

[[v9-24-9]]

^<<v9-24-9,9>>^ E Davi disse a Saul: — Por que o senhor dá atenção às palavras dos que dizem que Davi quer fazer-lhe mal?

[[v9-24-10]]

^<<v9-24-10,10>>^ Eis que hoje o meu senhor pode ver com os seus próprios olhos que o Senhor  Deus o pôs nas minhas mãos nesta caverna, e alguns disseram que eu deveria matá-lo. Mas eu o poupei, porque disse: "Não estenderei a mão contra o meu senhor, pois é o ungido de Deus."

[[v9-24-11]]

^<<v9-24-11,11>>^ Veja, meu pai, veja aqui na minha mão a ponta do seu manto. Por eu haver cortado a ponta do seu manto sem matá-lo, reconheça e veja que não há em mim nem mal nem rebeldia. Nunca pequei contra o rei, ainda que ele esteja à caça da minha vida para tirá-la de mim.

[[v9-24-12]]

^<<v9-24-12,12>>^ Que o Senhor  Deus julgue entre nós dois e me vingue do rei; porém não estenderei a minha mão contra o rei.

[[v9-24-13]]

^<<v9-24-13,13>>^ Como o provérbio dos antigos diz: "Dos perversos procede a perversidade." Mas eu não estenderei a minha mão contra o senhor, meu rei.

[[v9-24-14]]

^<<v9-24-14,14>>^ Atrás de quem saiu o rei de Israel? A quem persegue? A um cão morto? A uma pulga?

[[v9-24-15]]

^<<v9-24-15,15>>^ Que o Senhor  Deus seja o meu juiz e julgue entre nós dois. Que ele examine e defenda a minha causa, me faça justiça e me livre das mãos do rei.

[[v9-24-16]]

^<<v9-24-16,16>>^ Quando Davi acabou de falar todas estas palavras, Saul disse: — É esta a sua voz, meu filho Davi? E Saul chorou em alta voz.

[[v9-24-17]]

^<<v9-24-17,17>>^ Então disse a Davi: — Você é mais justo do que eu, pois me recompensou com o bem, enquanto eu o recompensei com o mal.

[[v9-24-18]]

^<<v9-24-18,18>>^ Hoje você mostrou que me fez o bem, pois o Senhor  me havia posto em suas mãos, e você não me matou.

[[v9-24-19]]

^<<v9-24-19,19>>^ Porque quem é que encontra o inimigo e o deixa ir sem lhe fazer mal? Que o Senhor  lhe pague com o bem por aquilo que você fez por mim no dia de hoje.

[[v9-24-20]]

^<<v9-24-20,20>>^ Agora tenho certeza de que você será rei e de que o reino de Israel se manterá firme na sua mão.

[[v9-24-21]]

^<<v9-24-21,21>>^ Portanto, jure pelo Senhor  que você não eliminará a minha descendência, nem apagará o meu nome da casa de meu pai.

[[v9-24-22]]

^<<v9-24-22,22>>^ E Davi jurou a Saul. Este foi para casa, mas Davi e os seus homens foram ao lugar seguro.

'''

xref:009-1-samuel/009-1-samuel-023.adoc#v9-23-0[&#60; Capítulo Anterior] | <<v9-24-0,Topo>> | xref:009-1-samuel/009-1-samuel-025.adoc#v9-25-0[Próximo Capítulo &#62;]