include::./index.adoc[]

[[v9-14-0]]
=== 1 Samuel, 14
// naa ?, NAA - Nova Almeida Atualizada

[[v9-14-1]]

^<<v9-14-1,1>>^ Um dia, Jônatas, filho de Saul, disse ao seu jovem escudeiro: — Venha, vamos até a guarnição dos filisteus, que está do outro lado. Porém ele não contou isso a seu pai.

[[v9-14-2]]

^<<v9-14-2,2>>^ Saul se encontrava na extremidade de Gibeá, debaixo da romãzeira em Migrom. E o povo que estava com ele eram cerca de seiscentos homens.

[[v9-14-3]]

^<<v9-14-3,3>>^ Aías, filho de Aitube, irmão de Icabô, filho de Fineias, filho de Eli, sacerdote do Senhor  em Siló, trazia a estola sacerdotal. O povo não sabia que Jônatas tinha ido.

[[v9-14-4]]

^<<v9-14-4,4>>^ Entre os desfiladeiros pelos quais Jônatas procurava passar à guarnição dos filisteus, havia um penhasco íngreme de um lado, e outro penhasco íngreme do outro lado. Um se chamava Bozez; o outro, Sené.

[[v9-14-5]]

^<<v9-14-5,5>>^ Um deles se erguia ao norte, diante de Micmás; o outro, ao sul, diante de Geba.

[[v9-14-6]]

^<<v9-14-6,6>>^ Jônatas disse ao seu escudeiro: — Venha, vamos até a guarnição desses incircuncisos. Talvez o Senhor  nos ajude, porque nada pode impedir o Senhor  de livrar, seja com muitos ou com poucos.

[[v9-14-7]]

^<<v9-14-7,7>>^ Então o escudeiro disse: — Faça tudo o que estiver em seu coração. Eu estou com você e farei o que você decidir.

[[v9-14-8]]

^<<v9-14-8,8>>^ Jônatas respondeu: — Então vamos atravessar na direção daqueles homens e deixar que eles nos vejam.

[[v9-14-9]]

^<<v9-14-9,9>>^ Se nos disserem assim: "Fiquem parados até que cheguemos perto de vocês", então ficaremos onde estamos e não subiremos a eles.

[[v9-14-10]]

^<<v9-14-10,10>>^ Porém se disserem: "Subam até aqui", então subiremos, pois o Senhor  os entregou em nossas mãos. Isto nos servirá de sinal.

[[v9-14-11]]

^<<v9-14-11,11>>^ Quando os dois se deixaram ver pela guarnição dos filisteus, estes disseram: — Eis que os hebreus estão saindo dos buracos onde estavam escondidos.

[[v9-14-12]]

^<<v9-14-12,12>>^ Os homens da guarnição disseram a Jônatas e ao seu escudeiro: — Subam até aqui e nós daremos uma lição em vocês. Então Jônatas disse ao escudeiro: — Venha atrás de mim, porque o Senhor  os entregou nas mãos de Israel.

[[v9-14-13]]

^<<v9-14-13,13>>^ Então Jônatas subiu engatinhando, e o seu escudeiro foi atrás. Os filisteus caíram diante de Jônatas, e o seu escudeiro os matava atrás dele.

[[v9-14-14]]

^<<v9-14-14,14>>^ Neste primeiro ataque, Jônatas e o seu escudeiro mataram perto de vinte homens, numa pequena área de terra.

[[v9-14-15]]

^<<v9-14-15,15>>^ Houve grande espanto no arraial, no campo e entre todo o povo. Também a guarnição e os saqueadores tremeram, e até a terra tremeu. Foi um terror causado por Deus.

[[v9-14-16]]

^<<v9-14-16,16>>^ Em Gibeá de Benjamim, as sentinelas de Saul olharam e eis que a multidão dos filisteus se dispersava, correndo uns para cá, outros para lá.

[[v9-14-17]]

^<<v9-14-17,17>>^ Então Saul disse ao povo que estava com ele: — Contem os soldados e vejam quem é que saiu do acampamento. Contaram, e eis que nem Jônatas nem o seu escudeiro estavam ali.

[[v9-14-18]]

^<<v9-14-18,18>>^ Saul disse a Aías: — Traga aqui a arca de Deus. Isso porque, naquele dia, ela estava com os filhos de Israel.

[[v9-14-19]]

^<<v9-14-19,19>>^ Enquanto Saul falava ao sacerdote, o alvoroço que havia no arraial dos filisteus aumentava cada vez mais. Então Saul disse ao sacerdote: — Desista de trazer a arca.

[[v9-14-20]]

^<<v9-14-20,20>>^ Saul e todo o povo que estava com ele se reuniram e foram à batalha. E eis que a espada de um era contra o outro, e houve grande tumulto.

[[v9-14-21]]

^<<v9-14-21,21>>^ Também os hebreus que anteriormente haviam estado com os filisteus e que tinham ido com eles ao arraial, também estes se juntaram com os israelitas que estavam com Saul e Jônatas.

[[v9-14-22]]

^<<v9-14-22,22>>^ Quando todos os homens de Israel que estavam escondidos na região montanhosa de Efraim ouviram que os filisteus estavam fugindo, também eles entraram na batalha e os perseguiram.

[[v9-14-23]]

^<<v9-14-23,23>>^ Assim o Senhor  livrou Israel naquele dia. E a batalha passou além de Bete-Áven.

[[v9-14-24]]

^<<v9-14-24,24>>^ Naquele dia os homens de Israel estavam angustiados, porque Saul havia levado o povo a fazer um juramento, dizendo: — Maldito o homem que comer algo antes de anoitecer, antes de eu me vingar dos meus inimigos. Por isso todo o povo se absteve de comer naquele dia.

[[v9-14-25]]

^<<v9-14-25,25>>^ Todo o povo chegou a um bosque onde havia mel no chão.

[[v9-14-26]]

^<<v9-14-26,26>>^ Quando o povo entrou no bosque, eis que o mel estava escorrendo. Mas ninguém provou do mel, porque o povo estava com medo do juramento.

[[v9-14-27]]

^<<v9-14-27,27>>^ Jônatas, porém, não sabia que o pai havia levado o povo a fazer aquele juramento. Por isso, estendeu a ponta da vara que tinha na mão, e a molhou no favo de mel. Quando comeu, os seus olhos voltaram a brilhar.

[[v9-14-28]]

^<<v9-14-28,28>>^ Então alguém do meio do povo disse: — O seu pai levou o povo a jurar solenemente, dizendo: "Maldito o homem que comer algo no dia de hoje." Por isso o povo está exausto.

[[v9-14-29]]

^<<v9-14-29,29>>^ Então Jônatas disse: — Meu pai trouxe desastre sobre a terra. Vejam como os meus olhos brilham por ter eu provado um pouco deste mel.

[[v9-14-30]]

^<<v9-14-30,30>>^ Teria sido muito melhor se hoje o povo tivesse comido livremente do que encontrou entre os despojos de seus inimigos. A derrota dos filisteus teria sido bem maior!

[[v9-14-31]]

^<<v9-14-31,31>>^ Naquele dia derrotaram os filisteus, desde Micmás até Aijalom. O povo estava muito exausto.

[[v9-14-32]]

^<<v9-14-32,32>>^ Então, lançando-se sobre o despojo, pegaram ovelhas, bois e bezerros, e os mataram no chão, e comeram a carne com sangue.

[[v9-14-33]]

^<<v9-14-33,33>>^ Foram contar isto a Saul, dizendo: — Eis que o povo está pecando contra o Senhor , porque comem a carne com sangue. Saul gritou: — Traidores! Rolem para aqui uma grande pedra.

[[v9-14-34]]

^<<v9-14-34,34>>^ E Saul disse mais: — Espalhem-se entre o povo e digam a eles que cada um me traga o seu boi, a sua ovelha, e que os matem aqui, e então comam. E que não pequem contra o Senhor , comendo carne com sangue. Então todo o povo trouxe, de noite, cada um o seu boi e o matou ali.

[[v9-14-35]]

^<<v9-14-35,35>>^ E Saul edificou um altar ao Senhor . Foi o primeiro altar que lhe edificou.

[[v9-14-36]]

^<<v9-14-36,36>>^ Então Saul disse: — Vamos descer esta noite no encalço dos filisteus. Vamos saqueá-los até o raiar do dia, e não deixemos que fique nem sequer um deles. Eles responderam: — Faça como achar melhor.

[[v9-14-37]]

^<<v9-14-37,37>>^ Mas o sacerdote disse: — Vamos primeiro nos aproximar de Deus. Então Saul consultou a Deus, dizendo: — Devo descer no encalço dos filisteus? Tu os entregarás nas mãos de Israel? Porém naquele dia Deus não lhe respondeu.

[[v9-14-38]]

^<<v9-14-38,38>>^ Então Saul disse: — Venham cá, todos os chefes do povo, e informem-se e descubram qual é o pecado que foi cometido hoje.

[[v9-14-39]]

^<<v9-14-39,39>>^ Porque tão certo como vive o Senhor , que salva Israel, ainda que o meu filho Jônatas seja o culpado, certamente morrerá. Porém ninguém de todo o povo lhe respondeu.

[[v9-14-40]]

^<<v9-14-40,40>>^ Então Saul disse a todo o Israel: — Fiquem vocês de um lado, e eu e o meu filho Jônatas ficaremos do outro. E o povo disse a Saul: — Faça como achar melhor.

[[v9-14-41]]

^<<v9-14-41,41>>^ Então Saul falou ao Senhor , Deus de Israel: — Mostra a verdade. Então Jônatas e Saul foram indicados por sorteio, e o povo saiu livre.

[[v9-14-42]]

^<<v9-14-42,42>>^ Então Saul disse: — Lancem a sorte entre mim e Jônatas, meu filho. E Jônatas foi indicado.

[[v9-14-43]]

^<<v9-14-43,43>>^ Então Saul disse a Jônatas: — Diga-me o que foi que você fez. E Jônatas respondeu: — Eu apenas provei um pouco de mel com a ponta da vara que tinha na mão. Eis-me aqui; estou pronto para morrer.

[[v9-14-44]]

^<<v9-14-44,44>>^ Então Saul disse: — Que Deus me castigue se você não for morto, Jônatas.

[[v9-14-45]]

^<<v9-14-45,45>>^ Porém o povo disse a Saul: — Como é que Jônatas pode ser morto, ele que efetuou tamanha salvação em Israel? Nada disso! Tão certo como vive o Senhor , nem um de seus cabelos cairá no chão! Pois foi com a ajuda de Deus que ele fez isso, hoje. Assim o povo salvou Jônatas, para que não morresse.

[[v9-14-46]]

^<<v9-14-46,46>>^ E Saul deixou de perseguir os filisteus, e estes voltaram para a sua terra.

[[v9-14-47]]

^<<v9-14-47,47>>^ Quando assumiu o reinado de Israel, Saul lutou contra todos os seus inimigos ao redor: contra Moabe, os filhos de Amom e Edom; contra os reis de Zobá e os filisteus; e, para onde quer que se voltava, era vitorioso.

[[v9-14-48]]

^<<v9-14-48,48>>^ Lutou com coragem, derrotando os amalequitas e libertando Israel das mãos dos que o saqueavam.

[[v9-14-49]]

^<<v9-14-49,49>>^ Os filhos de Saul eram Jônatas, Isvi e Malquisua. Os nomes de suas duas filhas eram Merabe, a mais velha, e Mical, a mais nova.

[[v9-14-50]]

^<<v9-14-50,50>>^ A mulher de Saul se chamava Ainoã, filha de Aimaás. O nome do general do seu exército era Abner, filho de Ner, tio de Saul.

[[v9-14-51]]

^<<v9-14-51,51>>^ Quis era pai de Saul; e Ner, pai de Abner, era filho de Abiel.

[[v9-14-52]]

^<<v9-14-52,52>>^ Durante todo o reinado de Saul, houve forte guerra contra os filisteus. Por isso, sempre que via um homem forte e valente, Saul o agregava a si.

'''

xref:009-1-samuel/009-1-samuel-013.adoc#v9-13-0[&#60; Capítulo Anterior] | <<v9-14-0,Topo>> | xref:009-1-samuel/009-1-samuel-015.adoc#v9-15-0[Próximo Capítulo &#62;]