include::./index.adoc[]

[[v9-11-0]]
=== 1 Samuel, 11
// naa ?, NAA - Nova Almeida Atualizada

[[v9-11-1]]

^<<v9-11-1,1>>^ Então Naás, que era amonita, foi e sitiou Jabes-Gileade. E todos os homens de Jabes disseram a Naás: — Faça uma aliança conosco, e nós o serviremos.

[[v9-11-2]]

^<<v9-11-2,2>>^ Porém Naás, o amonita, respondeu: — Farei aliança com vocês sob a condição de que seja vazado o olho direito de cada um de vocês. Assim, trarei vergonha sobre todo o Israel.

[[v9-11-3]]

^<<v9-11-3,3>>^ Então os anciãos de Jabes lhe disseram: — Dê-nos sete dias para enviar mensageiros por todo o território de Israel. Se não houver ninguém que nos livre, então nos entregaremos a você.

[[v9-11-4]]

^<<v9-11-4,4>>^ Quando os mensageiros chegaram a Gibeá, onde morava Saul, relataram este caso ao povo. Então todo o povo chorou em alta voz.

[[v9-11-5]]

^<<v9-11-5,5>>^ Eis que Saul voltava do campo, atrás dos bois, e perguntou: — Que tem o povo? Por que estão chorando? Então lhe contaram o que os homens de Jabes haviam relatado.

[[v9-11-6]]

^<<v9-11-6,6>>^ Quando Saul ouviu estas palavras, o Espírito de Deus se apossou dele, e ficou furioso.

[[v9-11-7]]

^<<v9-11-7,7>>^ Pegou uma junta de bois, cortou-os em pedaços e os enviou a todo o território de Israel por meio de mensageiros que dissessem: — Assim se fará com os bois de todo aquele que não seguir Saul e Samuel. Então o temor do Senhor  caiu sobre o povo, e saíram como se fossem um só homem.

[[v9-11-8]]

^<<v9-11-8,8>>^ Saul contou-os em Bezeque. Dos filhos de Israel, havia trezentos mil; dos homens de Judá, trinta mil.

[[v9-11-9]]

^<<v9-11-9,9>>^ Então disseram aos mensageiros que tinham vindo de Jabes: — Digam aos homens de Jabes-Gileade que amanhã, quando o sol aquentar, vocês serão socorridos. Os mensageiros foram, anunciaram isto aos homens de Jabes, e estes se alegraram.

[[v9-11-10]]

^<<v9-11-10,10>>^ Então disseram aos amonitas: — Amanhã nós nos entregaremos, e vocês poderão fazer conosco o que bem quiserem.

[[v9-11-11]]

^<<v9-11-11,11>>^ Aconteceu que, no dia seguinte, Saul dividiu o povo em três companhias, que, pela vigília da manhã, vieram para o meio do arraial e atacaram os amonitas, até que se fez sentir o calor do dia. Os sobreviventes se espalharam, e não ficaram dois deles juntos.

[[v9-11-12]]

^<<v9-11-12,12>>^ Então o povo disse a Samuel: — Quem são aqueles que diziam que Saul não deveria reinar sobre nós? Tragam-nos para aqui, para que os matemos.

[[v9-11-13]]

^<<v9-11-13,13>>^ Porém Saul disse: — Hoje ninguém será morto, porque no dia de hoje o Senhor  salvou Israel.

[[v9-11-14]]

^<<v9-11-14,14>>^ E Samuel disse ao povo: — Venham, vamos a Gilgal e renovemos ali o reino.

[[v9-11-15]]

^<<v9-11-15,15>>^ E todo o povo partiu para Gilgal, onde proclamaram Saul seu rei, diante do Senhor , a cuja presença trouxeram ofertas pacíficas. E Saul muito se alegrou ali com todos os homens de Israel.

'''

xref:009-1-samuel/009-1-samuel-010.adoc#v9-10-0[&#60; Capítulo Anterior] | <<v9-11-0,Topo>> | xref:009-1-samuel/009-1-samuel-012.adoc#v9-12-0[Próximo Capítulo &#62;]