include::./index.adoc[]

[[v9-22-0]]
=== 1 Samuel, 22
// naa ?, NAA - Nova Almeida Atualizada

[[v9-22-1]]

^<<v9-22-1,1>>^ Davi saiu daquele lugar e se refugiou na caverna de Adulão. Quando os seus irmãos e toda a casa de seu pai souberam disso, foram ficar com ele.

[[v9-22-2]]

^<<v9-22-2,2>>^ Ajuntaram-se a ele todos os homens que estavam em dificuldades, os que tinham dívidas, e todos os amargurados de espírito, e Davi se tornou o chefe deles. E havia com ele uns quatrocentos homens.

[[v9-22-3]]

^<<v9-22-3,3>>^ Daquele lugar Davi foi a Mispa, em Moabe, e disse ao rei de Moabe: — Deixe que o meu pai e a minha mãe fiquem com vocês, até que eu saiba o que Deus vai fazer de mim.

[[v9-22-4]]

^<<v9-22-4,4>>^ Davi levou-os ao rei de Moabe, e eles moraram com ele durante todo o tempo em que Davi esteve naquele lugar seguro.

[[v9-22-5]]

^<<v9-22-5,5>>^ Porém o profeta Gade disse a Davi: — Não fique neste lugar seguro; vá e entre na terra de Judá. Então Davi saiu e foi para o bosque de Herete.

[[v9-22-6]]

^<<v9-22-6,6>>^ Saul ficou sabendo que Davi e os homens que o acompanhavam foram descobertos. Saul se encontrava em Gibeá, debaixo de um arvoredo, numa colina, com a sua lança na mão, e todos os seus servos estavam com ele.

[[v9-22-7]]

^<<v9-22-7,7>>^ Saul disse aos servos que o rodeavam: — Escutem, filhos de Benjamim! Será que o filho de Jessé dará também a todos vocês terras e vinhas e fará de todos vocês chefes de milhares e chefes de centenas,

[[v9-22-8]]

^<<v9-22-8,8>>^ para que todos vocês tenham conspirado contra mim? Não houve ninguém que me avisasse que o meu filho fez aliança com o filho de Jessé. Não há nenhum de vocês que tenha pena de mim e me conte que o meu filho instigou contra mim o meu servo, para me armar ciladas, como se vê neste dia.

[[v9-22-9]]

^<<v9-22-9,9>>^ Então Doegue, o edomita, que também estava com os servos de Saul, disse: — Eu vi o filho de Jessé chegar a Nobe, para falar com Aimeleque, filho de Aitube.

[[v9-22-10]]

^<<v9-22-10,10>>^ A pedido dele, Aimeleque consultou o Senhor . Também lhe deu mantimento e a espada de Golias, o filisteu.

[[v9-22-11]]

^<<v9-22-11,11>>^ Então o rei mandou chamar o sacerdote Aimeleque, filho de Aitube, e toda a casa de seu pai, a saber, os sacerdotes que estavam em Nobe. E todos eles vieram ao rei.

[[v9-22-12]]

^<<v9-22-12,12>>^ Saul disse: — Escute, filho de Aitube! Este respondeu: — Eis-me aqui, meu senhor!

[[v9-22-13]]

^<<v9-22-13,13>>^ Então Saul lhe disse: — Por que você conspirou contra mim, você e o filho de Jessé? Pois você lhe deu pão e espada e consultou Deus a favor dele, para que se levantasse contra mim e me armasse ciladas, como hoje se vê.

[[v9-22-14]]

^<<v9-22-14,14>>^ Aimeleque respondeu ao rei: — E quem, entre todos os seus servos, é tão fiel quanto Davi, o genro do rei, chefe da sua guarda pessoal e honrado na sua casa?

[[v9-22-15]]

^<<v9-22-15,15>>^ Por acaso foi essa a primeira vez que consultei Deus em favor dele? Não! Que o rei jamais acuse este seu servo, nem ninguém da casa de meu pai, pois este seu servo de nada soube de tudo isso, nem muito nem pouco.

[[v9-22-16]]

^<<v9-22-16,16>>^ O rei respondeu: — Aimeleque, você certamente morrerá, você e toda a casa de seu pai.

[[v9-22-17]]

^<<v9-22-17,17>>^ Então o rei disse aos guardas que o rodeavam: — Voltem-se e matem os sacerdotes do Senhor , porque também estão de mãos dadas com Davi e porque souberam que fugiu e não me disseram nada. Porém os servos do rei não quiseram estender as mãos contra os sacerdotes do Senhor .

[[v9-22-18]]

^<<v9-22-18,18>>^ Então o rei disse a Doegue: — Volte-se você e mate os sacerdotes. Então Doegue, o edomita, se voltou e investiu contra os sacerdotes. Naquele dia ele matou oitenta e cinco homens que vestiam estola sacerdotal de linho.

[[v9-22-19]]

^<<v9-22-19,19>>^ Também a Nobe, a cidade desses sacerdotes, passou a fio de espada. Matou homens e mulheres, meninos e crianças de peito, bois, jumentos e ovelhas.

[[v9-22-20]]

^<<v9-22-20,20>>^ Porém dos filhos de Aimeleque, filho de Aitube, um só, cujo nome era Abiatar, se salvou e fugiu para Davi.

[[v9-22-21]]

^<<v9-22-21,21>>^ Abiatar anunciou a Davi que Saul tinha matado os sacerdotes do Senhor .

[[v9-22-22]]

^<<v9-22-22,22>>^ Então Davi disse a Abiatar: — Naquele dia, quando vi que Doegue, o edomita, estava ali, eu sabia que ele não deixaria de contar tudo a Saul. Eu fui a causa da morte de todas as pessoas da casa de seu pai.

[[v9-22-23]]

^<<v9-22-23,23>>^ Fique comigo, não tenha medo, porque quem procura a minha morte procura também a sua; mas comigo você estará a salvo.

'''

xref:009-1-samuel/009-1-samuel-021.adoc#v9-21-0[&#60; Capítulo Anterior] | <<v9-22-0,Topo>> | xref:009-1-samuel/009-1-samuel-023.adoc#v9-23-0[Próximo Capítulo &#62;]