include::./index.adoc[]

[[v9-15-0]]
=== 1 Samuel, 15
// naa ?, NAA - Nova Almeida Atualizada

[[v9-15-1]]

^<<v9-15-1,1>>^ Samuel disse a Saul: — Foi a mim que o Senhor  enviou para ungir você como rei sobre Israel, o povo dele. Agora ouça as palavras do Senhor .

[[v9-15-2]]

^<<v9-15-2,2>>^ Assim diz o Senhor  dos Exércitos: "Castigarei Amaleque pelo que fez a Israel, colocando-se no caminho de Israel, quando este saía do Egito.

[[v9-15-3]]

^<<v9-15-3,3>>^ Portanto, vá e ataque os amalequitas, destruindo totalmente aquilo que eles tiverem. Não poupe ninguém. Mate homens e mulheres, meninos e crianças de peito, bois e ovelhas, camelos e jumentos."

[[v9-15-4]]

^<<v9-15-4,4>>^ Saul convocou o povo e fez a contagem em Telaim: duzentos mil homens de infantaria e dez mil homens de Judá.

[[v9-15-5]]

^<<v9-15-5,5>>^ Saul foi à cidade de Amaleque e pôs emboscadas no vale.

[[v9-15-6]]

^<<v9-15-6,6>>^ Então disse aos queneus: — Vão embora, afastem-se e saiam do meio dos amalequitas, para que eu não destrua vocês juntamente com eles, porque vocês usaram de misericórdia para com todos os filhos de Israel, quando eles saíram do Egito. Assim, os queneus se retiraram do meio dos amalequitas.

[[v9-15-7]]

^<<v9-15-7,7>>^ Então Saul derrotou os amalequitas, desde Havilá até chegar a Sur, que está diante do Egito.

[[v9-15-8]]

^<<v9-15-8,8>>^ Tomou vivo Agague, rei dos amalequitas, porém destruiu todo o povo a fio de espada.

[[v9-15-9]]

^<<v9-15-9,9>>^ Mas Saul e o povo pouparam Agague, o melhor das ovelhas e dos bois, os animais gordos, os cordeiros e tudo o mais que era bom. A isso não quiseram destruir totalmente; porém toda coisa sem valor e desprezível destruíram.

[[v9-15-10]]

^<<v9-15-10,10>>^ Então a palavra do Senhor  veio a Samuel, dizendo:

[[v9-15-11]]

^<<v9-15-11,11>>^ — Lamento haver constituído Saul como rei, porque deixou de me seguir e não executou as minhas palavras. Então Samuel ficou triste e clamou ao Senhor  durante toda a noite.

[[v9-15-12]]

^<<v9-15-12,12>>^ Samuel madrugou para encontrar Saul pela manhã. Mas anunciaram a Samuel: — Saul já chegou ao Carmelo, e eis que levantou para si um monumento; depois, dando volta, passou e desceu a Gilgal.

[[v9-15-13]]

^<<v9-15-13,13>>^ Samuel encontrou Saul, e este lhe disse: — Que você seja bendito do Senhor ! Executei as palavras do Senhor .

[[v9-15-14]]

^<<v9-15-14,14>>^ Mas Samuel perguntou: — Então que balido de ovelhas é este nos meus ouvidos e o mugido de bois que estou escutando?

[[v9-15-15]]

^<<v9-15-15,15>>^ Saul respondeu: — Trouxeram isso dos amalequitas. Porque o povo guardou o melhor das ovelhas e dos bois, para os sacrificar ao Senhor , o seu Deus. O resto nós destruímos totalmente.

[[v9-15-16]]

^<<v9-15-16,16>>^ Então Samuel disse a Saul: — Espere! Vou declarar a você o que o Senhor  me disse esta noite. Saul respondeu: — Fale.

[[v9-15-17]]

^<<v9-15-17,17>>^ Samuel continuou: — Não é verdade que, mesmo sendo pequeno aos seus próprios olhos, você foi colocado por cabeça das tribos de Israel? O Senhor  o ungiu como rei sobre Israel.

[[v9-15-18]]

^<<v9-15-18,18>>^ O Senhor  o enviou a este caminho e disse: "Vá e destrua totalmente esses pecadores, os amalequitas, e lute contra eles, até exterminá-los."

[[v9-15-19]]

^<<v9-15-19,19>>^ Por que, então, você não deu ouvidos à voz do Senhor , mas se lançou sobre o despojo e fez o que era mau aos olhos do Senhor ?

[[v9-15-20]]

^<<v9-15-20,20>>^ Então Saul disse a Samuel: — Pelo contrário, dei ouvidos à voz do Senhor  e segui o caminho pelo qual o Senhor  me enviou. Eu trouxe Agague, o rei de Amaleque, e destruí totalmente os amalequitas.

[[v9-15-21]]

^<<v9-15-21,21>>^ Mas o povo pegou do despojo ovelhas e bois, o melhor do que estava destinado à destruição para oferecer ao Senhor , o seu Deus, em Gilgal.

[[v9-15-22]]

^<<v9-15-22,22>>^ Porém Samuel disse: — Será que o Senhor  tem mais prazer em holocaustos e sacrifícios do que no obedecer à sua palavra? Eis que o obedecer é melhor do que o sacrificar, e o ouvir é melhor do que a gordura de carneiros.

[[v9-15-23]]

^<<v9-15-23,23>>^ Porque a rebelião é como o pecado da feitiçaria, e a obstinação é como a idolatria e o culto a ídolos do lar. Por você ter rejeitado a palavra do Senhor , também ele o rejeitou como rei.

[[v9-15-24]]

^<<v9-15-24,24>>^ Então Saul disse a Samuel: — Pequei, pois transgredi o mandamento do Senhor  e as palavras que você falou; porque temi o povo e dei ouvidos à voz deles.

[[v9-15-25]]

^<<v9-15-25,25>>^ Mas agora peço que você perdoe o meu pecado e volte comigo, para que eu adore o Senhor .

[[v9-15-26]]

^<<v9-15-26,26>>^ Porém Samuel disse a Saul: — Não voltarei com você. Por você ter rejeitado a palavra do Senhor , ele também o rejeitou como rei sobre Israel.

[[v9-15-27]]

^<<v9-15-27,27>>^ Quando Samuel se virou para ir embora, Saul o segurou pela borda do manto, e este se rasgou.

[[v9-15-28]]

^<<v9-15-28,28>>^ Então Samuel lhe disse: — Hoje o Senhor  rasgou das suas mãos o reino de Israel e o deu a alguém que é melhor do que você.

[[v9-15-29]]

^<<v9-15-29,29>>^ Também a Glória de Israel não mente, nem muda de ideia, porque não é homem, para que mude de ideia.

[[v9-15-30]]

^<<v9-15-30,30>>^ Então Saul disse: — Pequei! Mas honre-me, agora, diante dos anciãos do meu povo e diante de Israel. Volte comigo, para que eu adore o Senhor , seu Deus.

[[v9-15-31]]

^<<v9-15-31,31>>^ Então Samuel seguiu Saul, e este adorou o Senhor .

[[v9-15-32]]

^<<v9-15-32,32>>^ Samuel disse: — Tragam aqui Agague, rei dos amalequitas. Agague veio a ele, confiante, e disse: — Certamente já passou a amargura da morte.

[[v9-15-33]]

^<<v9-15-33,33>>^ Mas Samuel disse: — Assim como a sua espada deixou muitas mulheres sem filhos, também a sua mãe ficará sem o seu filho. E Samuel despedaçou Agague diante do Senhor , em Gilgal.

[[v9-15-34]]

^<<v9-15-34,34>>^ Então Samuel foi para Ramá, e Saul voltou para a sua casa, em Gibeá de Saul.

[[v9-15-35]]

^<<v9-15-35,35>>^ Até o final de sua vida, Samuel nunca mais viu Saul; porém tinha pena de Saul. O Senhor  lamentou haver constituído Saul como rei sobre Israel.

'''

xref:009-1-samuel/009-1-samuel-014.adoc#v9-14-0[&#60; Capítulo Anterior] | <<v9-15-0,Topo>> | xref:009-1-samuel/009-1-samuel-016.adoc#v9-16-0[Próximo Capítulo &#62;]