include::./index.adoc[]

[[v9-28-0]]
=== 1 Samuel, 28
// naa ?, NAA - Nova Almeida Atualizada

[[v9-28-1]]

^<<v9-28-1,1>>^ E aconteceu que, naqueles dias, os filisteus reuniram os seus exércitos para a guerra, para lutar contra Israel. Então Aquis disse a Davi: — Fique sabendo que você irá comigo para a batalha, você e os seus homens.

[[v9-28-2]]

^<<v9-28-2,2>>^ Então Davi disse a Aquis: — Assim você saberá o quanto este seu servo pode fazer. Aquis respondeu: — Por isso, você será meu guarda pessoal para sempre.

[[v9-28-3]]

^<<v9-28-3,3>>^ Samuel já havia morrido, e todo o Israel o tinha chorado e o tinha sepultado em Ramá, que era a sua cidade. Saul havia desterrado os médiuns e os adivinhos.

[[v9-28-4]]

^<<v9-28-4,4>>^ Os filisteus se reuniram e foram acampar em Suném. Saul reuniu todo o Israel, e eles acamparam em Gilboa.

[[v9-28-5]]

^<<v9-28-5,5>>^ Quando Saul viu o acampamento dos filisteus, foi tomado de medo, e muito se estremeceu o seu coração.

[[v9-28-6]]

^<<v9-28-6,6>>^ Saul consultou o Senhor , porém o Senhor  não lhe respondeu, nem por sonhos, nem por Urim, nem por profetas.

[[v9-28-7]]

^<<v9-28-7,7>>^ Então Saul disse aos seus servos: — Procurem uma mulher que seja médium, para que eu me encontre com ela e a consulte. Os servos responderam: — Há uma mulher em En-Dor que é médium.

[[v9-28-8]]

^<<v9-28-8,8>>^ Saul se disfarçou, vestiu outras roupas e se foi, acompanhado de dois homens. Chegaram de noite à casa da mulher, e Saul lhe disse: — Peço que você adivinhe para mim pela necromancia e me faça subir aquele que eu lhe disser.

[[v9-28-9]]

^<<v9-28-9,9>>^ Mas a mulher respondeu: — Você sabe muito bem o que Saul fez: eliminou da terra os médiuns e adivinhos. Então por que você está me preparando uma armadilha, que pode me levar à morte?

[[v9-28-10]]

^<<v9-28-10,10>>^ Então Saul lhe jurou pelo Senhor , dizendo: — Tão certo como vive o Senhor , nenhum castigo lhe sobrevirá por isso.

[[v9-28-11]]

^<<v9-28-11,11>>^ Então a mulher perguntou: — Quem você quer que eu faça subir? Ele respondeu: — Samuel.

[[v9-28-12]]

^<<v9-28-12,12>>^ Quando a mulher viu Samuel, gritou em alta voz e disse a Saul: — Por que você me enganou? Pois você mesmo é Saul.

[[v9-28-13]]

^<<v9-28-13,13>>^ Mas o rei disse à mulher: — Não tenha medo! O que você está vendo? A mulher respondeu a Saul: — Vejo um deus subindo da terra.

[[v9-28-14]]

^<<v9-28-14,14>>^ Ele perguntou: — Como é a sua figura? Ela respondeu: — Vem subindo um ancião e está enrolado numa capa. Então Saul entendeu que se tratava de Samuel. Ele se inclinou com o rosto em terra e se prostrou.

[[v9-28-15]]

^<<v9-28-15,15>>^ Samuel perguntou a Saul: — Por que você foi me perturbar, fazendo-me subir? Então Saul disse: — É que estou muito angustiado, porque os filisteus guerreiam contra mim, e Deus se afastou de mim e já não me responde, nem pelo ministério dos profetas, nem por sonhos. Por isso o chamei para que você me revele o que devo fazer.

[[v9-28-16]]

^<<v9-28-16,16>>^ Então Samuel disse: — Por que você pergunta a mim, visto que o Senhor  se afastou de você e se tornou seu inimigo?

[[v9-28-17]]

^<<v9-28-17,17>>^ Porque o Senhor  fez com você o que havia anunciado por meio de mim: rasgou das suas mãos o reino e o deu a alguém outro, que é Davi.

[[v9-28-18]]

^<<v9-28-18,18>>^ Você não deu ouvidos à voz do Senhor  e não executou o que ele, no furor da sua ira, ordenou contra Amaleque, por isso o Senhor  fez isso com você, hoje.

[[v9-28-19]]

^<<v9-28-19,19>>^ O Senhor  entregará também Israel, com você, nas mãos dos filisteus, e, amanhã, você e os seus filhos estarão comigo. O Senhor  também entregará o acampamento de Israel nas mãos dos filisteus.

[[v9-28-20]]

^<<v9-28-20,20>>^ De repente, Saul caiu estendido no chão e ficou com muito medo por causa das palavras de Samuel. Faltavam-lhe as forças, porque não tinha comido nada todo aquele dia e toda aquela noite.

[[v9-28-21]]

^<<v9-28-21,21>>^ A mulher se aproximou de Saul e, vendo que ele estava muito perturbado, disse a ele: — Veja, esta sua serva deu ouvidos à sua voz. Eu arrisquei a minha vida e fiz o que o senhor me pediu.

[[v9-28-22]]

^<<v9-28-22,22>>^ Então agora é a sua vez de ouvir as palavras desta sua serva: deixe que eu traga um pouco de comida. Coma, para que o senhor tenha forças e possa seguir o seu caminho.

[[v9-28-23]]

^<<v9-28-23,23>>^ Porém ele recusou, dizendo: — Não vou comer. Mas os seus servos e a mulher insistiram, e então ele concordou. Levantou-se do chão e sentou-se na cama.

[[v9-28-24]]

^<<v9-28-24,24>>^ A mulher tinha em casa um bezerro gordo, que ela se apressou em matar. Pegou também farinha, amassou-a e fez alguns pães sem fermento.

[[v9-28-25]]

^<<v9-28-25,25>>^ E trouxe a comida a Saul e os seus servos, e eles comeram. Depois, se levantaram e foram embora naquela mesma noite.

'''

xref:009-1-samuel/009-1-samuel-027.adoc#v9-27-0[&#60; Capítulo Anterior] | <<v9-28-0,Topo>> | xref:009-1-samuel/009-1-samuel-029.adoc#v9-29-0[Próximo Capítulo &#62;]