include::./index.adoc[]

[[v9-21-0]]
=== 1 Samuel, 21
// naa ?, NAA - Nova Almeida Atualizada

[[v9-21-1]]

^<<v9-21-1,1>>^ Então Davi foi até Nobe, ao sacerdote Aimeleque. Aimeleque, tremendo, saiu ao encontro de Davi e perguntou: — Por que você está sozinho e ninguém veio com você?

[[v9-21-2]]

^<<v9-21-2,2>>^ Davi respondeu ao sacerdote Aimeleque: — O rei me deu uma ordem e me disse que ninguém deveria saber por que ele me enviou e qual é a tarefa de que me incumbiu. Quanto aos meus soldados, combinei que me encontrassem em tal e tal lugar.

[[v9-21-3]]

^<<v9-21-3,3>>^ Agora, o que você tem à mão? Dê-me cinco pães ou o que puder encontrar.

[[v9-21-4]]

^<<v9-21-4,4>>^ O sacerdote respondeu a Davi, dizendo: — Não tenho pão comum à mão. Há, porém, pão sagrado, se ao menos os seus soldados se abstiveram das mulheres.

[[v9-21-5]]

^<<v9-21-5,5>>^ Davi respondeu ao sacerdote: — Sim, como sempre, quando saio à campanha, foram-nos vedadas as mulheres, e os corpos dos soldados não estão imundos. Se isso acontece em viagem comum, quanto mais serão puros hoje!

[[v9-21-6]]

^<<v9-21-6,6>>^ Então o sacerdote deu a Davi o pão sagrado, porque não havia ali outro, a não ser os pães da proposição, que tinham sido tirados de diante do Senhor , quando foram trocados, no devido dia, por pão quente.

[[v9-21-7]]

^<<v9-21-7,7>>^ Acontece que estava ali, naquele dia, um dos servos de Saul, detido diante do Senhor , cujo nome era Doegue, edomita, o chefe dos pastores de Saul.

[[v9-21-8]]

^<<v9-21-8,8>>^ Davi disse a Aimeleque: — Você tem aqui à mão uma lança ou uma espada? Eu não trouxe comigo nem a minha espada nem as minhas armas, porque a ordem do rei era urgente.

[[v9-21-9]]

^<<v9-21-9,9>>^ O sacerdote respondeu: — A espada de Golias, o filisteu, a quem você matou no vale de Elá, está aqui, enrolada num pano atrás da estola sacerdotal. Se quiser levá-la, leve-a, porque não há outra aqui, a não ser essa. Davi disse: — Não há outra semelhante; dê-me essa espada.

[[v9-21-10]]

^<<v9-21-10,10>>^ Naquele dia, Davi se levantou e fugiu de Saul. Ele foi procurar Aquis, rei de Gate.

[[v9-21-11]]

^<<v9-21-11,11>>^ Porém os servos de Aquis lhe disseram: — Este não é Davi, o rei da terra? Não é a respeito dele que se cantava nas danças, dizendo: Saul matou os seus milhares, porém Davi, os seus dez milhares?

[[v9-21-12]]

^<<v9-21-12,12>>^ Davi guardou essas palavras no coração e teve muito medo de Aquis, rei de Gate.

[[v9-21-13]]

^<<v9-21-13,13>>^ Por isso mudou o seu comportamento diante deles, fingindo-se de louco nas mãos deles. Fazia riscos nos batentes dos portões e deixava escorrer saliva pela barba.

[[v9-21-14]]

^<<v9-21-14,14>>^ Então Aquis disse aos seus servos: — Vocês estão vendo que este homem está louco. Por que o trouxeram para cá?

[[v9-21-15]]

^<<v9-21-15,15>>^ Será que estou com falta de doidos, para que vocês me trouxessem este para fazer doidices diante de mim? Devo deixar que este entre em minha casa?

'''

xref:009-1-samuel/009-1-samuel-020.adoc#v9-20-0[&#60; Capítulo Anterior] | <<v9-21-0,Topo>> | xref:009-1-samuel/009-1-samuel-022.adoc#v9-22-0[Próximo Capítulo &#62;]