include::./index.adoc[]

[[v9-27-0]]
=== 1 Samuel, 27
// naa ?, NAA - Nova Almeida Atualizada

[[v9-27-1]]

^<<v9-27-1,1>>^ Davi disse consigo mesmo: — Pode ser que algum dia eu venha a perecer nas mãos de Saul. Portanto, não há nada melhor para mim do que fugir para a terra dos filisteus. Isto para que Saul perca de todo as esperanças e deixe de me procurar em toda a terra de Israel; assim, me livrarei das mãos dele.

[[v9-27-2]]

^<<v9-27-2,2>>^ Davi se levantou e, com os seiscentos homens que estavam com ele, foi até Aquis, filho de Maoque, rei de Gate.

[[v9-27-3]]

^<<v9-27-3,3>>^ Davi ficou morando com Aquis, na cidade de Gate, ele e os seus homens, cada um com a sua família. Davi foi com as suas duas mulheres: Ainoã, a jezreelita, e Abigail, a viúva de Nabal, o carmelita.

[[v9-27-4]]

^<<v9-27-4,4>>^ Quando Saul foi avisado de que Davi tinha fugido para Gate, desistiu de o perseguir.

[[v9-27-5]]

^<<v9-27-5,5>>^ Davi disse a Aquis: — Se encontrei favor em sua presença, dê-me um lugar numa das cidades do interior, para que eu more ali. Por que este seu servo ficaria morando com você na cidade real?

[[v9-27-6]]

^<<v9-27-6,6>>^ Então, naquele dia, Aquis deu a Davi a cidade de Ziclague. Por isso, Ziclague pertence aos reis de Judá até o dia de hoje.

[[v9-27-7]]

^<<v9-27-7,7>>^ E todo o tempo que Davi permaneceu na terra dos filisteus foi um ano e quatro meses.

[[v9-27-8]]

^<<v9-27-8,8>>^ Davi ia com os seus homens, e eles atacavam os gesuritas, os gersitas e os amalequitas, porque estes eram os moradores da terra desde Telã, na direção de Sur, até a terra do Egito.

[[v9-27-9]]

^<<v9-27-9,9>>^ Quando Davi atacava aquela terra, não deixava com vida nem homem nem mulher, e tomava as ovelhas, os bois, os jumentos, os camelos e as roupas. Então voltava e vinha para junto de Aquis.

[[v9-27-10]]

^<<v9-27-10,10>>^ Quando Aquis perguntava: "Quem foi que você atacou hoje?", Davi respondia: "Ataquei o Sul de Judá, o Sul dos jerameelitas, e o Sul dos queneus."

[[v9-27-11]]

^<<v9-27-11,11>>^ Davi não deixava com vida nem homem nem mulher, para os trazer a Gate, pois dizia: "Para que não nos denunciem, dizendo: ‘É assim que Davi fazia.’" Este era o seu modo de agir durante todo o tempo em que morou na terra dos filisteus.

[[v9-27-12]]

^<<v9-27-12,12>>^ Aquis confiava em Davi, dizendo: — Ele levou o seu povo de Israel a odiá-lo de verdade, e por isso será meu servo para sempre.

'''

xref:009-1-samuel/009-1-samuel-026.adoc#v9-26-0[&#60; Capítulo Anterior] | <<v9-27-0,Topo>> | xref:009-1-samuel/009-1-samuel-028.adoc#v9-28-0[Próximo Capítulo &#62;]