include::./index.adoc[]

[[v9-31-0]]
=== 1 Samuel, 31
// naa ?, NAA - Nova Almeida Atualizada

[[v9-31-1]]

^<<v9-31-1,1>>^ Os filisteus lutaram contra Israel. E os homens de Israel, fugindo da presença dos filisteus, caíram mortos no monte Gilboa.

[[v9-31-2]]

^<<v9-31-2,2>>^ Os filisteus seguiram de perto Saul e seus filhos e mataram Jônatas, Abinadabe e Malquisua, filhos de Saul.

[[v9-31-3]]

^<<v9-31-3,3>>^ A batalha se intensificou contra Saul. Os flecheiros o avistaram e ele foi ferido gravemente.

[[v9-31-4]]

^<<v9-31-4,4>>^ Então Saul disse ao seu escudeiro: — Arranque a sua espada e atravesse-me com ela, para que não venham esses incircuncisos, me atravessem com a espada e zombem de mim. Mas o seu escudeiro não quis fazer isso, porque estava com muito medo. Então Saul pegou a sua própria espada e se lançou sobre ela.

[[v9-31-5]]

^<<v9-31-5,5>>^ Quando o escudeiro viu que Saul estava morto, também se lançou sobre a sua espada e morreu com ele.

[[v9-31-6]]

^<<v9-31-6,6>>^ E assim morreram juntamente naquele dia Saul, os seus três filhos, o seu escudeiro e todos os seus soldados.

[[v9-31-7]]

^<<v9-31-7,7>>^ Quando os homens de Israel que estavam no outro lado do vale e no outro lado do Jordão viram que o exército de Israel fugiu e que Saul e seus filhos estavam mortos, abandonaram as cidades e fugiram. E vieram os filisteus e habitaram nelas.

[[v9-31-8]]

^<<v9-31-8,8>>^ E aconteceu que no dia seguinte, quando os filisteus foram tirar os despojos dos mortos, encontraram Saul e os seus três filhos caídos no monte Gilboa.

[[v9-31-9]]

^<<v9-31-9,9>>^ Cortaram a cabeça de Saul e o despojaram das suas armas. Enviaram mensageiros pela terra dos filisteus, ao redor, para levar as boas-novas ao templo dos seus ídolos e ao povo.

[[v9-31-10]]

^<<v9-31-10,10>>^ Puseram as armas de Saul no templo de Astarote, e o seu corpo afixaram na muralha de Bete-Seã.

[[v9-31-11]]

^<<v9-31-11,11>>^ Quando os moradores de Jabes-Gileade ouviram o que os filisteus haviam feito com Saul,

[[v9-31-12]]

^<<v9-31-12,12>>^ todos os homens valentes se levantaram, caminharam toda a noite, tiraram o corpo de Saul e os corpos de seus filhos da muralha de Bete-Seã e os levaram a Jabes, onde os queimaram.

[[v9-31-13]]

^<<v9-31-13,13>>^ Depois pegaram os ossos deles e os sepultaram debaixo de um arvoredo, em Jabes. E jejuaram sete dias.

'''

xref:009-1-samuel/009-1-samuel-030.adoc#v9-30-0[&#60; Capítulo Anterior] | <<v9-31-0,Topo>> | xref:010-2-samuel/010-2-samuel-001.adoc#v10-1-0[Próximo Capítulo &#62;]