include::./index.adoc[]

[[v9-18-0]]
=== 1 Samuel, 18
// naa ?, NAA - Nova Almeida Atualizada

[[v9-18-1]]

^<<v9-18-1,1>>^ Depois de Davi ter falado com Saul, a alma de Jônatas se ligou com a de Davi numa profunda amizade. E Jônatas o amou como à sua própria alma.

[[v9-18-2]]

^<<v9-18-2,2>>^ Naquele dia, Saul reteve Davi e não permitiu que ele voltasse para a casa de seu pai.

[[v9-18-3]]

^<<v9-18-3,3>>^ Jônatas e Davi fizeram uma aliança, porque Jônatas o amava como à sua própria alma.

[[v9-18-4]]

^<<v9-18-4,4>>^ Jônatas tirou a capa que vestia e a deu a Davi. Deu também a sua armadura, inclusive a espada, o arco e o cinto.

[[v9-18-5]]

^<<v9-18-5,5>>^ Davi saía aonde quer que Saul o enviava e tinha êxito, de modo que Saul o pôs sobre tropas do seu exército. E Davi era benquisto de todo o povo e até dos próprios servos de Saul.

[[v9-18-6]]

^<<v9-18-6,6>>^ E aconteceu que, quando eles estavam voltando para casa, depois de Davi ter matado o filisteu, as mulheres de todas as cidades de Israel saíram ao encontro do rei Saul, cantando e dançando, com tamborins, com alegria e com instrumentos musicais.

[[v9-18-7]]

^<<v9-18-7,7>>^ As mulheres se alegravam e, cantando alternadamente, diziam: Saul matou os seus milhares, porém Davi, os seus dez milhares.

[[v9-18-8]]

^<<v9-18-8,8>>^ Saul se indignou muito, pois estas palavras lhe desagradaram em extremo. Ele disse: — Para Davi elas deram dez milhares, mas para mim apenas milhares. Na verdade, o que lhe falta, a não ser o reino?

[[v9-18-9]]

^<<v9-18-9,9>>^ Daquele dia em diante, Saul não via Davi com bons olhos.

[[v9-18-10]]

^<<v9-18-10,10>>^ No dia seguinte, um espírito mau, vindo da parte de Deus, se apossou de Saul, que teve uma crise de raiva em sua casa. Davi, como nos outros dias, dedilhava a harpa. Saul, porém, tinha na mão uma lança,

[[v9-18-11]]

^<<v9-18-11,11>>^ que ele atirou, pensando assim: — Encravarei Davi na parede. Porém Davi se desviou dele por duas vezes.

[[v9-18-12]]

^<<v9-18-12,12>>^ Saul tinha medo de Davi, porque o Senhor  estava com este e tinha abandonado Saul.

[[v9-18-13]]

^<<v9-18-13,13>>^ Por isso Saul o afastou de si e o pôs por chefe de mil. Davi fazia saídas e entradas militares diante do povo.

[[v9-18-14]]

^<<v9-18-14,14>>^ Davi tinha êxito em todos os seus empreendimentos, pois o Senhor  estava com ele.

[[v9-18-15]]

^<<v9-18-15,15>>^ Vendo que Davi tinha êxito, Saul ficou com medo dele.

[[v9-18-16]]

^<<v9-18-16,16>>^ Porém todo o Israel e Judá amavam Davi, porque fazia saídas e entradas militares diante deles.

[[v9-18-17]]

^<<v9-18-17,17>>^ Saul disse a Davi: — Aqui está Merabe, a minha filha mais velha. Eu a darei a você em casamento, com a condição de que você seja um filho valente e trave as batalhas do Senhor . Porque Saul pensava assim: "Não seja contra ele a minha mão, e sim a dos filisteus."

[[v9-18-18]]

^<<v9-18-18,18>>^ Mas Davi respondeu a Saul: — Quem sou eu, e quem são os meus parentes, a família de meu pai em Israel, para que eu seja genro do rei?

[[v9-18-19]]

^<<v9-18-19,19>>^ Mas aconteceu que, na época em que Merabe, filha de Saul, devia ser dada em casamento a Davi, foi dada por mulher a Adriel, meolatita.

[[v9-18-20]]

^<<v9-18-20,20>>^ Mas Mical, a outra filha de Saul, amava Davi. Contaram isso a Saul, e isso agradou a ele.

[[v9-18-21]]

^<<v9-18-21,21>>^ Saul pensava assim: "Eu a darei em casamento a Davi, para que ela lhe sirva de armadilha e para que a mão dos filisteus venha a ser contra ele." Por isso Saul disse a Davi: — Com esta segunda você será hoje o meu genro.

[[v9-18-22]]

^<<v9-18-22,22>>^ Saul ordenou que os seus servos falassem confidencialmente com Davi, dizendo: — O rei tem afeição por você, e todos os servos dele amam você. Sendo assim, concorde em ser genro do rei.

[[v9-18-23]]

^<<v9-18-23,23>>^ Os servos de Saul falaram estas palavras a Davi, o qual respondeu: — Vocês acham que é pouca coisa ser genro do rei, sendo eu um homem pobre e sem importância?

[[v9-18-24]]

^<<v9-18-24,24>>^ Os servos de Saul lhe contaram isto, dizendo: — Estas foram as palavras que Davi falou.

[[v9-18-25]]

^<<v9-18-25,25>>^ Então Saul ordenou que dissessem a Davi: — O rei não deseja dote algum, mas cem prepúcios de filisteus, como vingança contra os seus inimigos. Porque Saul tentava fazer com que Davi fosse morto pelos filisteus.

[[v9-18-26]]

^<<v9-18-26,26>>^ Quando os servos de Saul relataram estas palavras a Davi, este gostou da ideia de vir a ser genro do rei. Antes de vencido o prazo,

[[v9-18-27]]

^<<v9-18-27,27>>^ Davi se levantou e partiu com os seus homens, e mataram duzentos filisteus. Trouxe os seus prepúcios e os entregou todos ao rei, para que assim se tornasse seu genro. Então Saul lhe deu a sua filha Mical em casamento.

[[v9-18-28]]

^<<v9-18-28,28>>^ Saul viu e reconheceu que o Senhor  estava com Davi; e Mical, filha de Saul, o amava.

[[v9-18-29]]

^<<v9-18-29,29>>^ Então Saul ficou com mais medo ainda de Davi e continuamente foi seu inimigo.

[[v9-18-30]]

^<<v9-18-30,30>>^ Cada vez que os chefes dos filisteus saíam à batalha, Davi obtinha mais êxito do que todos os servos de Saul. E assim o nome de Davi se tornou muito estimado.

'''

xref:009-1-samuel/009-1-samuel-017.adoc#v9-17-0[&#60; Capítulo Anterior] | <<v9-18-0,Topo>> | xref:009-1-samuel/009-1-samuel-019.adoc#v9-19-0[Próximo Capítulo &#62;]