include::./index.adoc[]

[[v9-5-0]]
=== 1 Samuel, 5
// naa ?, NAA - Nova Almeida Atualizada

[[v9-5-1]]

^<<v9-5-1,1>>^ Os filisteus tomaram a arca de Deus e a levaram de Ebenézer a Asdode.

[[v9-5-2]]

^<<v9-5-2,2>>^ Os filisteus tomaram a arca de Deus e a colocaram no templo de Dagom, ao lado da imagem de Dagom.

[[v9-5-3]]

^<<v9-5-3,3>>^ Quando os moradores de Asdode se levantaram de madrugada, no dia seguinte, eis que Dagom estava caído com o rosto em terra, diante da arca do Senhor . Eles pegaram a imagem de Dagom e a puseram de volta no seu lugar.

[[v9-5-4]]

^<<v9-5-4,4>>^ Levantando-se de madrugada no dia seguinte, pela manhã, eis que Dagom estava caído de bruços diante da arca do Senhor . A cabeça de Dagom e as duas mãos estavam cortadas e se encontravam na soleira da porta; apenas o tronco dele estava inteiro.

[[v9-5-5]]

^<<v9-5-5,5>>^ Por isso, os sacerdotes de Dagom e todos os que entram no seu templo em Asdode não pisam na soleira da porta, até o dia de hoje.

[[v9-5-6]]

^<<v9-5-6,6>>^ Porém a mão do Senhor  castigou duramente os moradores de Asdode, e os assolou, e os feriu com tumores, tanto em Asdode como nos seus arredores.

[[v9-5-7]]

^<<v9-5-7,7>>^ Quando os homens de Asdode viram o que estava acontecendo, disseram: — A arca do Deus de Israel não deve ficar entre nós, pois a sua mão é dura sobre nós e sobre Dagom, nosso deus.

[[v9-5-8]]

^<<v9-5-8,8>>^ Então enviaram mensageiros e reuniram todos os governantes dos filisteus, e perguntaram: — Que faremos com a arca do Deus de Israel? Eles responderam: — Que a arca do Deus de Israel seja levada até Gate e, depois, de cidade em cidade. E a levaram até Gate.

[[v9-5-9]]

^<<v9-5-9,9>>^ Depois que a levaram, a mão do Senhor  foi contra aquela cidade, causando grande terror; pois feriu os homens daquela cidade, desde o pequeno até o grande; e lhes nasceram tumores.

[[v9-5-10]]

^<<v9-5-10,10>>^ Então enviaram a arca de Deus a Ecrom. Mas, quando a arca chegou lá, os ecronitas exclamaram: — Trouxeram a arca do Deus de Israel até aqui para matar a nós e a nosso povo.

[[v9-5-11]]

^<<v9-5-11,11>>^ Então enviaram mensageiros e reuniram todos os governantes dos filisteus, e disseram: — Devolvam a arca do Deus de Israel. Que ela volte ao seu lugar, para que não mate nem a nós nem ao nosso povo. Porque havia terror de morte em toda a cidade, e a mão de Deus castigou duramente ali.

[[v9-5-12]]

^<<v9-5-12,12>>^ Os homens que não morriam eram atingidos com os tumores, e o clamor da cidade subiu até o céu.

'''

xref:009-1-samuel/009-1-samuel-004.adoc#v9-4-0[&#60; Capítulo Anterior] | <<v9-5-0,Topo>> | xref:009-1-samuel/009-1-samuel-006.adoc#v9-6-0[Próximo Capítulo &#62;]