include::./index.adoc[]

[[v9-20-0]]
=== 1 Samuel, 20
// naa ?, NAA - Nova Almeida Atualizada

[[v9-20-1]]

^<<v9-20-1,1>>^ Então Davi fugiu da casa dos profetas, em Ramá, foi até o lugar onde Jônatas estava e lhe perguntou: — O que foi que eu fiz? Qual é a minha culpa? E qual é o meu pecado diante de seu pai, que procura tirar-me a vida?

[[v9-20-2]]

^<<v9-20-2,2>>^ Jônatas respondeu: — Nada disso! Você não será morto. Meu pai não faz coisa nenhuma, nem grande nem pequena, sem primeiro me dizer. Por que, então, meu pai esconderia isso de mim? Não há nada disso.

[[v9-20-3]]

^<<v9-20-3,3>>^ Então Davi respondeu enfaticamente: — Seu pai sabe muito bem que encontrei favor diante de você. Assim, ele resolveu que você não deve ficar sabendo disso, para não se entristecer. Mas tão certo como vive o Senhor , e como você vive, Jônatas, há apenas um passo entre mim e a morte.

[[v9-20-4]]

^<<v9-20-4,4>>^ Jônatas disse a Davi: — Farei tudo o que você quiser que eu faça.

[[v9-20-5]]

^<<v9-20-5,5>>^ Davi disse a Jônatas: — Amanhã é a Festa da Lua Nova, em que sem falta deveria assentar-me com o rei para comer. Mas deixe que eu vá embora, para me esconder no campo, até a tarde do terceiro dia.

[[v9-20-6]]

^<<v9-20-6,6>>^ Se o seu pai notar a minha ausência, diga o seguinte: "Davi me pediu muito que o deixasse ir a toda pressa a Belém, sua cidade, porque lá será oferecido o sacrifício anual para toda a família."

[[v9-20-7]]

^<<v9-20-7,7>>^ Se ele disser: "Está bem", então este seu servo terá paz. Porém, se ficar com muita raiva, saiba que ele já decidiu me fazer mal.

[[v9-20-8]]

^<<v9-20-8,8>>^ Use, pois, de misericórdia para com este seu servo, porque você me fez entrar em aliança no Senhor  com você. Mas, se sou culpado, mate-me você mesmo. Por que você me levaria ao seu pai?

[[v9-20-9]]

^<<v9-20-9,9>>^ Então Jônatas disse: — Nada disso! Se eu de algum modo soubesse que o meu pai está determinado a trazer esse mal sobre você, acha que eu não avisaria você?

[[v9-20-10]]

^<<v9-20-10,10>>^ Então Davi perguntou: — Quem irá me avisar, se, por acaso, o seu pai lhe responder asperamente?

[[v9-20-11]]

^<<v9-20-11,11>>^ Jônatas respondeu: — Venha, vamos ao campo. E eles foram.

[[v9-20-12]]

^<<v9-20-12,12>>^ Jônatas disse a Davi: — O Senhor , Deus de Israel, seja testemunha. Amanhã ou depois de amanhã, a estas horas sondarei meu pai. Se houver algo favorável a Davi, eu lhe mandarei dizer.

[[v9-20-13]]

^<<v9-20-13,13>>^ Mas, se meu pai quiser fazer mal a você, que o Senhor  faça com Jônatas o que bem quiser, se eu não o avisar disso e não o deixar ir embora, para que você siga em paz. E que o Senhor  esteja com você, como tem estado com o meu pai.

[[v9-20-14]]

^<<v9-20-14,14>>^ E, se eu, então, ainda viver, use para comigo da bondade do Senhor , para que eu não morra.

[[v9-20-15]]

^<<v9-20-15,15>>^ Nem tampouco jamais afaste da minha casa a sua bondade; nem ainda quando o Senhor  eliminar da face da terra todos os inimigos de Davi.

[[v9-20-16]]

^<<v9-20-16,16>>^ Assim, Jônatas fez aliança com a casa de Davi, dizendo: — Que o Senhor  vingue os inimigos de Davi.

[[v9-20-17]]

^<<v9-20-17,17>>^ Jônatas fez com que Davi jurasse de novo, pelo amor que lhe tinha, porque Jônatas o amava com todo o amor da sua alma.

[[v9-20-18]]

^<<v9-20-18,18>>^ Jônatas disse a Davi: — Amanhã é a Festa da Lua Nova. Eles vão perguntar por você, porque o seu lugar estará vazio.

[[v9-20-19]]

^<<v9-20-19,19>>^ No terceiro dia, vá depressa ao lugar onde você se escondeu no dia do combinado e fique junto à pedra de Ezel.

[[v9-20-20]]

^<<v9-20-20,20>>^ Atirarei três flechas para aquele lado, como quem atira ao alvo.

[[v9-20-21]]

^<<v9-20-21,21>>^ Eis que mandarei o moço e lhe direi: "Vá, procure as flechas." Se eu disser ao moço: "Olhe, as flechas estão para cá de você; traga-as", então venha, Davi, porque, tão certo como vive o Senhor , você terá paz, e nada há que temer.

[[v9-20-22]]

^<<v9-20-22,22>>^ Porém, se eu disser ao moço: "Olhe, as flechas estão mais para lá de você", vá embora, porque o Senhor  manda que você vá.

[[v9-20-23]]

^<<v9-20-23,23>>^ Quanto àquilo de que eu e você falamos, eis que o Senhor  é nossa testemunha para sempre.

[[v9-20-24]]

^<<v9-20-24,24>>^ Então Davi se escondeu no campo. E, sendo a Festa da Lua Nova, o rei se pôs à mesa para comer.

[[v9-20-25]]

^<<v9-20-25,25>>^ O rei sentou-se na sua cadeira, segundo o costume, no lugar junto à parede. Jônatas ficou na frente dele, e Abner sentou-se ao lado de Saul. Mas o lugar de Davi estava desocupado.

[[v9-20-26]]

^<<v9-20-26,26>>^ Porém, naquele dia, Saul não disse nada, pois pensava: "Deve ter acontecido alguma coisa com ele. Ele está cerimonialmente impuro. Certamente está impuro."

[[v9-20-27]]

^<<v9-20-27,27>>^ No dia seguinte, o segundo dia da Festa da Lua Nova, o lugar de Davi continuava desocupado. Então Saul perguntou a Jônatas, seu filho: — Por que o filho de Jessé não veio comer, nem ontem nem hoje?

[[v9-20-28]]

^<<v9-20-28,28>>^ Jônatas respondeu: — Davi me pediu, encarecidamente, que o deixasse ir a Belém.

[[v9-20-29]]

^<<v9-20-29,29>>^ Ele me disse: "Peço que você me deixe ir, porque a nossa família tem um sacrifício na cidade, e um de meus irmãos insiste comigo para que eu vá. Portanto, se encontrei favor aos seus olhos, peço que me deixe partir, para que eu veja os meus irmãos." Por isso, não veio à mesa do rei.

[[v9-20-30]]

^<<v9-20-30,30>>^ Então Saul ficou irado com Jônatas e lhe disse: — Seu filho de mulher vadia e rebelde! Você acha que eu não sei que você elegeu o filho de Jessé, para vergonha sua e para vergonha de sua mãe?

[[v9-20-31]]

^<<v9-20-31,31>>^ Pois, enquanto o filho de Jessé viver sobre a terra, nem você estará seguro, nem seguro estará o seu reino. Por isso, mande buscá-lo, agora, porque deve morrer.

[[v9-20-32]]

^<<v9-20-32,32>>^ Então Jônatas perguntou a Saul, seu pai: — Por que ele deve morrer? O que foi que ele fez?

[[v9-20-33]]

^<<v9-20-33,33>>^ Então Saul atirou a sua lança contra Jônatas para matá-lo. Com isso Jônatas entendeu que, de fato, seu pai já havia decidido matar Davi.

[[v9-20-34]]

^<<v9-20-34,34>>^ Por isso, Jônatas, com muita raiva, se levantou da mesa e, neste segundo dia da Festa da Lua Nova, não comeu pão, pois ficou muito sentido por causa de Davi, a quem seu pai havia insultado.

[[v9-20-35]]

^<<v9-20-35,35>>^ Na manhã seguinte, Jônatas saiu ao campo, no tempo combinado com Davi, e levou consigo um rapazinho.

[[v9-20-36]]

^<<v9-20-36,36>>^ Então disse ao seu rapaz: — Corra e busque as flechas que eu atirar. O rapaz correu, e ele atirou uma flecha, que fez passar além do rapaz.

[[v9-20-37]]

^<<v9-20-37,37>>^ Quando o rapaz chegou ao lugar da flecha que Jônatas havia atirado, Jônatas gritou atrás dele: — A flecha não está mais para lá de você?

[[v9-20-38]]

^<<v9-20-38,38>>^ Jônatas gritou mais uma vez: — Vamos! Depressa! Não fique aí parado! O rapaz de Jônatas apanhou as flechas e voltou ao seu senhor.

[[v9-20-39]]

^<<v9-20-39,39>>^ O rapaz não entendeu coisa alguma, pois só Jônatas e Davi sabiam deste combinado.

[[v9-20-40]]

^<<v9-20-40,40>>^ Então Jônatas deu as suas armas ao rapaz que o acompanhava e lhe disse: — Vá, leve-as para a cidade.

[[v9-20-41]]

^<<v9-20-41,41>>^ Quando o rapaz foi embora, Davi se levantou do lado do monte de pedras e se prostrou com o rosto em terra três vezes. E beijaram um ao outro e choraram juntos; Davi, porém, muito mais.

[[v9-20-42]]

^<<v9-20-42,42>>^ Então Jônatas disse a Davi: — Vá em paz, porque ambos juramos em nome do Senhor , dizendo: "O Senhor  seja para sempre testemunha entre mim e você e entre a minha descendência e a sua descendência."

[[v9-20-43]]

^<<v9-20-43,43>>^ Então Davi se levantou e foi embora. E Jônatas voltou para a cidade.

'''

xref:009-1-samuel/009-1-samuel-019.adoc#v9-19-0[&#60; Capítulo Anterior] | <<v9-20-0,Topo>> | xref:009-1-samuel/009-1-samuel-021.adoc#v9-21-0[Próximo Capítulo &#62;]