include::./index.adoc[]

[[v9-30-0]]
=== 1 Samuel, 30
// naa ?, NAA - Nova Almeida Atualizada

[[v9-30-1]]

^<<v9-30-1,1>>^ Aconteceu que, ao terceiro dia, quando Davi e os seus homens chegaram a Ziclague, os amalequitas já tinham invadido o Sul e a cidade de Ziclague. Tomaram Ziclague e a incendiaram.

[[v9-30-2]]

^<<v9-30-2,2>>^ Levaram cativas as mulheres que lá estavam, mas não mataram ninguém, nem pequenos nem grandes; tão somente os levaram consigo e foram embora.

[[v9-30-3]]

^<<v9-30-3,3>>^ Davi e os seus homens chegaram à cidade, e viram que tinha sido queimada, e que as suas mulheres, os seus filhos e as suas filhas haviam sido levados cativos.

[[v9-30-4]]

^<<v9-30-4,4>>^ Então Davi e o povo que estava com ele ergueram a voz e choraram, até não terem mais forças para chorar.

[[v9-30-5]]

^<<v9-30-5,5>>^ Também as duas mulheres de Davi tinham sido levadas: Ainoã, a jezreelita, e Abigail, a viúva de Nabal, o carmelita.

[[v9-30-6]]

^<<v9-30-6,6>>^ Davi ficou muito angustiado, pois o povo falava de apedrejá-lo, porque todos estavam amargurados, cada um por causa de seus filhos e suas filhas. Mas Davi se reanimou no Senhor , seu Deus.

[[v9-30-7]]

^<<v9-30-7,7>>^ Davi disse a Abiatar, o sacerdote, filho de Aimeleque: — Traga aqui a estola sacerdotal. E Abiatar a trouxe a Davi.

[[v9-30-8]]

^<<v9-30-8,8>>^ Então Davi consultou o Senhor , dizendo: — Devo perseguir esse bando? Conseguirei alcançá-lo? O Senhor  respondeu: — Persiga o bando, porque você certamente o alcançará e libertará os cativos.

[[v9-30-9]]

^<<v9-30-9,9>>^ Então Davi partiu, ele e os seiscentos homens que com ele estavam, e chegaram ao ribeiro de Besor, onde os retardatários ficaram.

[[v9-30-10]]

^<<v9-30-10,10>>^ Davi e quatrocentos homens continuaram a perseguição, mas duzentos ficaram atrás, por não poderem passar o ribeiro de Besor, de tão cansados que estavam.

[[v9-30-11]]

^<<v9-30-11,11>>^ Encontraram no campo um homem egípcio e o trouxeram a Davi. Deram-lhe pão, e ele comeu, e deram-lhe água para beber.

[[v9-30-12]]

^<<v9-30-12,12>>^ Deram-lhe também um pedaço de pasta de figos secos e dois cachos de passas, e ele comeu. Assim, recobrou as forças, pois havia três dias e três noites que não comia pão, nem bebia água.

[[v9-30-13]]

^<<v9-30-13,13>>^ Então Davi lhe perguntou: — De quem você é e de onde você vem? O moço egípcio respondeu: — Sou servo de um amalequita, e meu senhor me deixou aqui, porque adoeci há três dias.

[[v9-30-14]]

^<<v9-30-14,14>>^ Nós invadimos o lado sul dos queretitas, o território de Judá e o lado sul de Calebe e pusemos fogo em Ziclague.

[[v9-30-15]]

^<<v9-30-15,15>>^ Então Davi lhe perguntou: — Você poderia me levar até esse bando? Ele respondeu: — Jure por Deus que não vai me matar, nem me entregar nas mãos de meu senhor, e eu o levarei até esse bando.

[[v9-30-16]]

^<<v9-30-16,16>>^ E ele levou Davi até lá. Eis que os amalequitas estavam espalhados por toda a região, comendo, bebendo e fazendo festa por todo aquele grande despojo que tomaram da terra dos filisteus e da terra de Judá.

[[v9-30-17]]

^<<v9-30-17,17>>^ Davi os atacou e lutou contra eles, desde o crepúsculo até a tarde do dia seguinte, e nenhum deles escapou, a não ser quatrocentos moços que montaram em camelos e fugiram.

[[v9-30-18]]

^<<v9-30-18,18>>^ Assim, Davi salvou tudo o que os amalequitas tinham levado. Também salvou as suas duas mulheres.

[[v9-30-19]]

^<<v9-30-19,19>>^ Não lhes faltou coisa alguma, nem pequena nem grande, nem os filhos, nem as filhas, nem o despojo, nada do que lhes haviam tomado: Davi trouxe tudo de volta.

[[v9-30-20]]

^<<v9-30-20,20>>^ Davi também tomou todas as ovelhas e o gado. Então levaram esses animais diante de Davi e disseram: — Este é o despojo de Davi.

[[v9-30-21]]

^<<v9-30-21,21>>^ Quando Davi se aproximou dos duzentos homens que, de tão cansados que estavam, não o puderam seguir e ficaram no ribeiro de Besor, estes saíram ao encontro de Davi e do povo que vinha com ele. Davi se aproximou deles e os saudou cordialmente.

[[v9-30-22]]

^<<v9-30-22,22>>^ Então todos os perversos e malignos, dentre os homens que tinham ido com Davi, disseram: — Uma vez que não foram conosco, não lhes daremos nada do despojo que salvamos. Que cada um leve a sua mulher e os seus filhos e se vá embora.

[[v9-30-23]]

^<<v9-30-23,23>>^ Porém Davi disse: — Meus irmãos, não façam isto com o que o Senhor  nos deu. Ele nos guardou e entregou em nossas mãos o bando que vinha contra nós.

[[v9-30-24]]

^<<v9-30-24,24>>^ E quem lhes daria ouvidos nisso? Porque a mesma parte que cabe aos que foram à batalha será também a parte dos que ficaram com a bagagem; receberão partes iguais.

[[v9-30-25]]

^<<v9-30-25,25>>^ E assim, desde aquele dia em diante, isso foi estabelecido por estatuto e direito em Israel, até o dia de hoje.

[[v9-30-26]]

^<<v9-30-26,26>>^ Quando Davi chegou a Ziclague, enviou parte do despojo aos anciãos de Judá, seus amigos, dizendo: — Este é um presente para vocês, tirado do despojo dos inimigos do Senhor .

[[v9-30-27]]

^<<v9-30-27,27>>^ Ele enviou esse presente aos anciãos de Betel, de Ramote do Neguebe, de Jatir,

[[v9-30-28]]

^<<v9-30-28,28>>^ de Aroer, de Sifmote, de Estemoa,

[[v9-30-29]]

^<<v9-30-29,29>>^ de Racal, das cidades dos jerameelitas e dos queneus,

[[v9-30-30]]

^<<v9-30-30,30>>^ de Horma, de Borasã, de Atace,

[[v9-30-31]]

^<<v9-30-31,31>>^ de Hebrom e de todos os lugares em que Davi tinha passado, ele e os seus homens.

'''

xref:009-1-samuel/009-1-samuel-029.adoc#v9-29-0[&#60; Capítulo Anterior] | <<v9-30-0,Topo>> | xref:009-1-samuel/009-1-samuel-031.adoc#v9-31-0[Próximo Capítulo &#62;]