include::./index.adoc[]

[[v9-23-0]]
=== 1 Samuel, 23
// naa ?, NAA - Nova Almeida Atualizada

[[v9-23-1]]

^<<v9-23-1,1>>^ Então disseram a Davi: — Eis que os filisteus estão atacando a cidade de Queila e saqueando as eiras.

[[v9-23-2]]

^<<v9-23-2,2>>^ Davi consultou o Senhor , perguntando: — Devo ir e atacar esses filisteus? O Senhor  respondeu a Davi: — Vá, ataque os filisteus, e livre a cidade de Queila.

[[v9-23-3]]

^<<v9-23-3,3>>^ Porém os homens de Davi lhe disseram: — Temos medo aqui em Judá, quanto mais indo a Queila lutar contra as tropas dos filisteus.

[[v9-23-4]]

^<<v9-23-4,4>>^ Então Davi tornou a consultar o Senhor , e o Senhor  lhe respondeu: — Levante-se e vá até Queila, porque estou entregando os filisteus em suas mãos.

[[v9-23-5]]

^<<v9-23-5,5>>^ Então Davi e os seus homens foram a Queila, lutaram contra os filisteus e tomaram todo o gado deles. E causaram grande matança entre eles. Assim, Davi salvou os moradores de Queila.

[[v9-23-6]]

^<<v9-23-6,6>>^ Aconteceu que, quando Abiatar, filho de Aimeleque, fugiu para junto de Davi, em Queila, levou a estola sacerdotal.

[[v9-23-7]]

^<<v9-23-7,7>>^ Foi anunciado a Saul que Davi tinha ido a Queila. Então Saul disse: — Deus o entregou nas minhas mãos. Está cercado, pois entrou numa cidade de portões e ferrolhos.

[[v9-23-8]]

^<<v9-23-8,8>>^ Então Saul mandou chamar todo o povo para a batalha, para que descessem a Queila e cercassem Davi e os seus homens.

[[v9-23-9]]

^<<v9-23-9,9>>^ Quando Davi soube que Saul maquinava o mal contra ele, disse ao sacerdote Abiatar: — Traga aqui a estola sacerdotal.

[[v9-23-10]]

^<<v9-23-10,10>>^ Então Davi orou: — Ó Senhor , Deus de Israel, teu servo ouviu que Saul, de fato, procura vir a Queila, para destruir a cidade por minha causa.

[[v9-23-11]]

^<<v9-23-11,11>>^ Será que os moradores de Queila me entregarão nas mãos dele? Será que Saul virá mesmo, como o teu servo ouviu? Ah! Senhor , Deus de Israel, revela isto ao teu servo. E o Senhor  lhe disse: — Ele virá.

[[v9-23-12]]

^<<v9-23-12,12>>^ Então Davi perguntou: — E será que os moradores de Queila me entregarão, juntamente com os meus servos, nas mãos de Saul? O Senhor  respondeu: — Entregarão.

[[v9-23-13]]

^<<v9-23-13,13>>^ Então Davi e os seus homens, que eram uns seiscentos, saíram de Queila e se foram sem rumo certo. Quando foi anunciado a Saul que Davi tinha fugido de Queila, deixou de persegui-lo.

[[v9-23-14]]

^<<v9-23-14,14>>^ Davi permaneceu no deserto, nos lugares seguros, e ficou na região montanhosa no deserto de Zife. Saul buscava-o todos os dias, porém Deus não o entregou nas suas mãos.

[[v9-23-15]]

^<<v9-23-15,15>>^ Quando Davi percebeu que Saul tinha saído para tirar-lhe a vida, ficou no deserto de Zife, em Horesa.

[[v9-23-16]]

^<<v9-23-16,16>>^ Então Jônatas, filho de Saul, se levantou e foi falar com Davi, em Horesa, e lhe fortaleceu a confiança em Deus.

[[v9-23-17]]

^<<v9-23-17,17>>^ Jônatas disse: — Não tenha medo, porque a mão de Saul, meu pai, não encontrará você. Você será rei de Israel, e eu serei o segundo depois de você, o que também Saul, meu pai, bem sabe.

[[v9-23-18]]

^<<v9-23-18,18>>^ E ambos fizeram aliança diante do Senhor . Davi ficou em Horesa, e Jônatas voltou para casa.

[[v9-23-19]]

^<<v9-23-19,19>>^ Então os zifeus foram falar com Saul, em Gibeá, dizendo: — Não é verdade que Davi está escondido entre nós, nos lugares seguros de Horesa, no monte Haquila, ao sul de Jesimom?

[[v9-23-20]]

^<<v9-23-20,20>>^ Agora, ó rei, conforme o desejo do seu coração, venha, que a nós nos compete entregar Davi nas mãos do rei.

[[v9-23-21]]

^<<v9-23-21,21>>^ Saul respondeu: — Que vocês sejam benditos do Senhor , porque tiveram pena de mim.

[[v9-23-22]]

^<<v9-23-22,22>>^ Vão, agora, e informem-se ainda melhor. Descubram o lugar que ele frequenta e quem o viu ali, porque me foi dito que ele é muito astuto.

[[v9-23-23]]

^<<v9-23-23,23>>^ Por isso, prestem bem atenção e informem-se a respeito de todos os esconderijos em que ele se oculta. Voltem para cá com informações seguras, e então eu irei com vocês. Se ele estiver na região, irei procurá-lo entre todos os milhares de Judá.

[[v9-23-24]]

^<<v9-23-24,24>>^ Então eles se levantaram e se foram a Zife, adiante de Saul. Ora, Davi e os seus homens estavam no deserto de Maom, na planície, ao sul de Jesimom.

[[v9-23-25]]

^<<v9-23-25,25>>^ Saul e os seus homens foram ao encalço dele, e isto foi dito a Davi. Por isso ele foi para a rocha que está no deserto de Maom. Quando Saul soube disso, perseguiu Davi no deserto de Maom.

[[v9-23-26]]

^<<v9-23-26,26>>^ Saul ia de um lado do monte, e Davi e os seus homens, do outro. Davi se apressou em fugir para escapar de Saul, porém este e os seus homens cercaram Davi e os seus homens para os prender.

[[v9-23-27]]

^<<v9-23-27,27>>^ Então veio um mensageiro a Saul, dizendo: — Venha depressa, porque os filisteus invadiram a terra.

[[v9-23-28]]

^<<v9-23-28,28>>^ Por isso Saul desistiu de perseguir Davi e foi lutar contra os filisteus. Por esta razão, aquele lugar se chamou Sela-Hamalecote.

[[v9-23-29]]

^<<v9-23-29,29>>^ Davi partiu daquele lugar e ficou nos lugares seguros de En-Gedi.

'''

xref:009-1-samuel/009-1-samuel-022.adoc#v9-22-0[&#60; Capítulo Anterior] | <<v9-23-0,Topo>> | xref:009-1-samuel/009-1-samuel-024.adoc#v9-24-0[Próximo Capítulo &#62;]