include::./index.adoc[]

[[v9-13-0]]
=== 1 Samuel, 13
// naa ?, NAA - Nova Almeida Atualizada

[[v9-13-1]]

^<<v9-13-1,1>>^ Saul havia reinado em Israel durante um ano. No segundo ano do seu reinado sobre o povo,

[[v9-13-2]]

^<<v9-13-2,2>>^ escolheu três mil homens de Israel: dois mil estavam com Saul em Micmás e na região montanhosa de Betel, e mil estavam com Jônatas em Gibeá de Benjamim. Saul despediu o resto do povo, cada um para a sua casa.

[[v9-13-3]]

^<<v9-13-3,3>>^ Jônatas derrotou a guarnição dos filisteus que estava em Gibeá, e os filisteus ficaram sabendo disso. Então Saul mandou tocar a trombeta por toda a terra, dizendo: — Que os hebreus escutem isto.

[[v9-13-4]]

^<<v9-13-4,4>>^ E todo o Israel ouviu dizer: "Saul derrotou a guarnição dos filisteus, e agora os filisteus estão com ódio de Israel." Então o povo foi convocado para se juntar a Saul, em Gilgal.

[[v9-13-5]]

^<<v9-13-5,5>>^ Os filisteus se reuniram para lutar contra Israel com trinta mil carros de guerra, seis mil cavaleiros e povo em multidão como a areia que está na praia do mar. Eles foram e acamparam em Micmás, a leste de Bete-Áven.

[[v9-13-6]]

^<<v9-13-6,6>>^ Quando os homens de Israel viram que estavam em apuros (porque o povo estava angustiado), se esconderam em cavernas e em buracos, entre rochas, em túmulos e cisternas.

[[v9-13-7]]

^<<v9-13-7,7>>^ Também alguns dos hebreus passaram o Jordão e foram para a terra de Gade e Gileade. E o povo que permaneceu com Saul, estando este ainda em Gilgal, se encheu de temor.

[[v9-13-8]]

^<<v9-13-8,8>>^ Saul esperou sete dias, segundo o prazo determinado por Samuel. Mas como Samuel não vinha a Gilgal, o povo foi se espalhando dali.

[[v9-13-9]]

^<<v9-13-9,9>>^ Então Saul disse: — Tragam-me aqui o holocausto e as ofertas pacíficas. E ofereceu o holocausto.

[[v9-13-10]]

^<<v9-13-10,10>>^ Mal tinha ele acabado de oferecer o holocausto, eis que chegou Samuel. Saul saiu ao encontro dele, para o saudar.

[[v9-13-11]]

^<<v9-13-11,11>>^ Samuel perguntou: — O que foi que você fez? Saul respondeu: — Vendo que o povo ia se espalhando daqui, e que você não vinha no prazo combinado, e que os filisteus já tinham se ajuntado em Micmás,

[[v9-13-12]]

^<<v9-13-12,12>>^ eu disse comigo: "Agora os filisteus virão contra mim em Gilgal, e ainda não busquei a face do Senhor ." Assim, forçado pelas circunstâncias, ofereci holocaustos.

[[v9-13-13]]

^<<v9-13-13,13>>^ Então Samuel disse a Saul: — Você cometeu uma loucura, não guardando o mandamento que o Senhor , seu Deus, lhe ordenou. Pois o Senhor  teria confirmado para sempre o seu reinado sobre Israel.

[[v9-13-14]]

^<<v9-13-14,14>>^ Mas agora o seu reinado não subsistirá. O Senhor  buscou para si um homem segundo o seu coração e já lhe ordenou que seja príncipe sobre o seu povo, porque você não guardou o que o Senhor  lhe ordenou.

[[v9-13-15]]

^<<v9-13-15,15>>^ Então Samuel se levantou e foi de Gilgal a Gibeá de Benjamim. Saul contou o povo que estava com ele: eram cerca de seiscentos homens.

[[v9-13-16]]

^<<v9-13-16,16>>^ Saul, o seu filho Jônatas e o povo que estava com eles ficaram em Geba de Benjamim, enquanto os filisteus estavam acampados em Micmás.

[[v9-13-17]]

^<<v9-13-17,17>>^ Os saqueadores saíram do campo dos filisteus em três tropas. Uma delas tomou o caminho de Ofra à terra de Sual;

[[v9-13-18]]

^<<v9-13-18,18>>^ a outra tomou o caminho de Bete-Horom; e a terceira, o caminho de onde se avista o vale de Zeboim, na direção do deserto.

[[v9-13-19]]

^<<v9-13-19,19>>^ Ora, em toda a terra de Israel não havia um único ferreiro, porque os filisteus tinham dito: "Para que os hebreus não façam espadas, nem lanças."

[[v9-13-20]]

^<<v9-13-20,20>>^ Por isso todo o Israel tinha de ir aos filisteus para amolar as lâminas dos arados, as enxadas, os machados e as foices.

[[v9-13-21]]

^<<v9-13-21,21>>^ Os filisteus cobravam dos israelitas oito gramas de prata para amolar os fios das lâminas e das enxadas e quatro gramas de prata para amolar machados e aguilhadas.

[[v9-13-22]]

^<<v9-13-22,22>>^ Por isso, no dia da batalha, não se achou nem espada, nem lança na mão de nenhum do povo que estava com Saul e com Jônatas; só Saul e seu filho Jônatas tinham essas armas.

[[v9-13-23]]

^<<v9-13-23,23>>^ A guarnição dos filisteus saiu ao desfiladeiro de Micmás.

'''

xref:009-1-samuel/009-1-samuel-012.adoc#v9-12-0[&#60; Capítulo Anterior] | <<v9-13-0,Topo>> | xref:009-1-samuel/009-1-samuel-014.adoc#v9-14-0[Próximo Capítulo &#62;]