include::./index.adoc[]

[[v8-1-0]]
=== Rute, 1
// naa ?, NAA - Nova Almeida Atualizada

[[v8-1-1]]

^<<v8-1-1,1>>^ Nos dias em que os juízes julgavam, houve fome na terra de Israel. E um homem de Belém de Judá foi morar por algum tempo na terra de Moabe, com a sua mulher e os seus dois filhos.

[[v8-1-2]]

^<<v8-1-2,2>>^ Este homem se chamava Elimeleque, e sua mulher se chamava Noemi. Os filhos se chamavam Malom e Quiliom. Eram efrateus, de Belém de Judá. Foram à terra de Moabe e ficaram ali.

[[v8-1-3]]

^<<v8-1-3,3>>^ Algum tempo depois, Elimeleque, o marido de Noemi, morreu, e ela ficou sozinha com os dois filhos.

[[v8-1-4]]

^<<v8-1-4,4>>^ Estes casaram com mulheres moabitas. O nome de uma delas era Orfa, e o nome da outra era Rute. E ficaram ali quase dez anos.

[[v8-1-5]]

^<<v8-1-5,5>>^ Depois morreram também Malom e Quiliom, os dois filhos de Noemi. E assim ela ficou sozinha, sem os dois filhos e sem o marido.

[[v8-1-6]]

^<<v8-1-6,6>>^ Então Noemi voltou da terra de Moabe com as suas noras, porque ainda em Moabe ouviu que o Senhor  havia se lembrado do seu povo, dando-lhe alimento.

[[v8-1-7]]

^<<v8-1-7,7>>^ Assim, ela saiu do lugar onde havia morado, e as duas noras estavam com ela. Enquanto caminhavam, voltando para a terra de Judá,

[[v8-1-8]]

^<<v8-1-8,8>>^ Noemi disse às suas noras: — Vão agora e voltem cada uma para a casa de sua mãe. E que o Senhor  seja bondoso com vocês, assim como vocês foram bondosas com os que morreram e comigo.

[[v8-1-9]]

^<<v8-1-9,9>>^ O Senhor  faça com que vocês sejam felizes, cada uma na casa de seu novo marido. E deu um beijo em cada uma delas. Elas, porém, começaram a chorar alto

[[v8-1-10]]

^<<v8-1-10,10>>^ e lhe disseram: — Não! Nós iremos com a senhora para junto do seu povo.

[[v8-1-11]]

^<<v8-1-11,11>>^ Mas Noemi disse: — Voltem, minhas filhas! Por que vocês iriam comigo? Vocês acham que eu ainda tenho filhos em meu ventre, para que casem com vocês?

[[v8-1-12]]

^<<v8-1-12,12>>^ Voltem, minhas filhas! Vão embora, porque sou velha demais para ter marido. E ainda que eu dissesse: "Tenho esperança", ou ainda que casasse esta noite e tivesse filhos,

[[v8-1-13]]

^<<v8-1-13,13>>^ será que vocês iriam esperar até que eles viessem a crescer? Ficariam tanto tempo sem casar? Não, minhas filhas! A minha amargura é maior do que a de vocês, porque o Senhor  descarregou a sua mão contra mim.

[[v8-1-14]]

^<<v8-1-14,14>>^ Então, de novo, choraram em alta voz. Orfa, com um beijo, se despediu de sua sogra, porém Rute se apegou a ela.

[[v8-1-15]]

^<<v8-1-15,15>>^ Então Noemi disse: — Veja! A sua cunhada voltou para o seu povo e para os seus deuses. Vá você também com ela.

[[v8-1-16]]

^<<v8-1-16,16>>^ Porém Rute respondeu: — Não insista para que eu a deixe nem me obrigue a não segui-la! Porque aonde quer que você for, irei eu; e onde quer que pousar, ali pousarei eu. O seu povo é o meu povo, e o seu Deus é o meu Deus.

[[v8-1-17]]

^<<v8-1-17,17>>^ Onde quer que você morrer, morrerei eu e aí serei sepultada. Que o Senhor  me castigue, se outra coisa que não seja a morte me separar de você.

[[v8-1-18]]

^<<v8-1-18,18>>^ Quando Noemi viu que Rute estava mesmo decidida a acompanhá-la, deixou de insistir com ela.

[[v8-1-19]]

^<<v8-1-19,19>>^ Então ambas se foram, até que chegaram a Belém. E aconteceu que, ao chegarem ali, toda a cidade se comoveu por causa delas. E as mulheres perguntavam: — Essa não é a Noemi?

[[v8-1-20]]

^<<v8-1-20,20>>^ Porém ela lhes dizia: — Não me chamem de Noemi, mas de Mara, porque o Todo-Poderoso me deu muita amargura.

[[v8-1-21]]

^<<v8-1-21,21>>^ Quando saí daqui, eu era plena, mas o Senhor  me fez voltar vazia. Por que, então, querem me chamar de Noemi, se o Senhor  deu testemunho contra mim e o Todo-Poderoso me afligiu?

[[v8-1-22]]

^<<v8-1-22,22>>^ Foi assim que Noemi voltou da terra de Moabe, com Rute, sua nora, a moabita. E chegaram a Belém no começo da colheita da cevada.

'''

xref:007-juizes/007-juizes-021.adoc#v7-21-0[&#60; Capítulo Anterior] | <<v8-1-0,Topo>> | xref:008-rute/008-rute-002.adoc#v8-2-0[Próximo Capítulo &#62;]