include::./index.adoc[]

[[v8-2-0]]
=== Rute, 2
// naa ?, NAA - Nova Almeida Atualizada

[[v8-2-1]]

^<<v8-2-1,1>>^ Noemi tinha um parente de seu marido, dono de muitos bens, da família de Elimeleque, o qual se chamava Boaz.

[[v8-2-2]]

^<<v8-2-2,2>>^ Rute, a moabita, disse a Noemi: — Deixe-me ir ao campo para apanhar espigas atrás daquele que me permitir fazer isso. Noemi respondeu: — Vá, minha filha!

[[v8-2-3]]

^<<v8-2-3,3>>^ Ela se foi, chegou ao campo e apanhava espigas atrás dos ceifeiros. Por casualidade entrou na parte do campo que pertencia a Boaz, que era da família de Elimeleque.

[[v8-2-4]]

^<<v8-2-4,4>>^ Eis que Boaz veio de Belém e disse aos ceifeiros: — Que o Senhor  esteja com vocês! E eles responderam: — Que o Senhor  o abençoe!

[[v8-2-5]]

^<<v8-2-5,5>>^ Depois, Boaz perguntou ao servo encarregado dos ceifeiros: — De quem é essa moça?

[[v8-2-6]]

^<<v8-2-6,6>>^ O servo respondeu: — Essa é a moça moabita que veio com Noemi da terra de Moabe.

[[v8-2-7]]

^<<v8-2-7,7>>^ Ela me pediu que a deixasse recolher espigas e ajuntá-las entre os feixes após os ceifeiros. Assim, ela veio e ficou aqui desde a manhã até agora. Só parou um pouco para descansar no abrigo.

[[v8-2-8]]

^<<v8-2-8,8>>^ Então Boaz disse a Rute: — Escute, minha filha, você não precisa ir colher em outro campo, nem se afastar daqui. Fique aqui com as minhas servas.

[[v8-2-9]]

^<<v8-2-9,9>>^ Fique atenta ao campo onde forem colher e vá atrás delas. Eu dei ordem aos servos para que não toquem em você. Quando você ficar com sede, vá até as vasilhas e beba da água que os servos tiraram.

[[v8-2-10]]

^<<v8-2-10,10>>^ Então Rute se inclinou e, encostando o rosto no chão, disse a Boaz: — Por que o senhor está me favorecendo e se importa comigo, se eu sou uma estrangeira?

[[v8-2-11]]

^<<v8-2-11,11>>^ Boaz respondeu: — Já me contaram tudo o que você fez pela sua sogra, depois que você perdeu o marido. Sei que você deixou pai, mãe e a terra onde nasceu e veio para um povo que antes disso você não conhecia.

[[v8-2-12]]

^<<v8-2-12,12>>^ O Senhor  lhe pague pelo bem que você fez. Que você receba uma grande recompensa do Senhor , Deus de Israel, sob cujas asas você veio buscar refúgio.

[[v8-2-13]]

^<<v8-2-13,13>>^ Então Rute disse: — Meu caro senhor, você está me favorecendo muito, pois me consolou e falou ao coração desta sua serva, e eu nem mesmo sou como uma das suas servas.

[[v8-2-14]]

^<<v8-2-14,14>>^ Na hora de comer, Boaz disse a Rute: — Venha para cá e coma do pão. Molhe o seu bocado no vinho. Ela se sentou ao lado dos ceifeiros, e Boaz lhe deu grãos tostados de cereais. Ela comeu até ficar satisfeita, e ainda sobrou.

[[v8-2-15]]

^<<v8-2-15,15>>^ Quando ela se levantou para ir apanhar espigas, Boaz deu esta ordem aos seus servos: — Deixem que ela apanhe espigas até no meio dos feixes e não sejam rudes com ela.

[[v8-2-16]]

^<<v8-2-16,16>>^ Tirem também algumas espigas dos feixes e deixem cair, para que ela as apanhe, e não a repreendam.

[[v8-2-17]]

^<<v8-2-17,17>>^ E assim Rute esteve apanhando espigas naquele campo até de tarde. Depois debulhou o que havia apanhado, e foi quase vinte litros de cevada.

[[v8-2-18]]

^<<v8-2-18,18>>^ Ela pegou o cereal e voltou para a cidade. E a sogra viu o quanto de cereal ela havia conseguido apanhar. Rute também deu para a sogra a comida que lhe havia sobrado, depois que ela comeu até ficar satisfeita.

[[v8-2-19]]

^<<v8-2-19,19>>^ Então Noemi perguntou: — Onde você foi colher hoje? Onde trabalhou? Bendito seja aquele que acolheu você com tanta generosidade! E Rute contou à sua sogra onde havia trabalhado. E acrescentou: — O nome do homem com quem trabalhei hoje é Boaz.

[[v8-2-20]]

^<<v8-2-20,20>>^ Então Noemi disse à sua nora: — Que ele seja abençoado pelo Senhor  Deus, que não deixou de ser bondoso, nem para com os vivos nem para com os mortos. E Noemi acrescentou: — Esse homem é nosso parente chegado e um dos nossos resgatadores.

[[v8-2-21]]

^<<v8-2-21,21>>^ Então Rute, a moabita, disse: — Ele também me disse que eu posso continuar com os servos dele, até que eles terminem de fazer a colheita.

[[v8-2-22]]

^<<v8-2-22,22>>^ Noemi respondeu: — É melhor mesmo que você vá com as servas dele, minha filha. Noutro campo, poderiam maltratar você.

[[v8-2-23]]

^<<v8-2-23,23>>^ Assim Rute ficou na companhia das servas de Boaz, para apanhar espigas, até que a colheita da cevada e do trigo se acabou. E continuou morando com a sua sogra.

'''

xref:008-rute/008-rute-001.adoc#v8-1-0[&#60; Capítulo Anterior] | <<v8-2-0,Topo>> | xref:008-rute/008-rute-003.adoc#v8-3-0[Próximo Capítulo &#62;]