include::./index.adoc[]

[[v12-13-0]]
=== 2 Reis, 13
// naa ?, NAA - Nova Almeida Atualizada

[[v12-13-1]]

^<<v12-13-1,1>>^ No vigésimo terceiro ano do reinado de Joás, filho de Acazias, rei de Judá, Jeoacaz, filho de Jeú, começou a reinar sobre Israel, em Samaria, e reinou dezessete anos.

[[v12-13-2]]

^<<v12-13-2,2>>^ Jeoacaz fez o que era mau aos olhos do Senhor  e andou nos pecados de Jeroboão, filho de Nebate, que este levou Israel a cometer; não se afastou deles.

[[v12-13-3]]

^<<v12-13-3,3>>^ Por isso a ira do Senhor  se acendeu contra Israel, e ele os entregou nas mãos de Hazael, rei da Síria, e nas mãos de Ben-Hadade, filho de Hazael, todos aqueles dias.

[[v12-13-4]]

^<<v12-13-4,4>>^ Porém Jeoacaz fez súplicas diante do Senhor , e o Senhor  o ouviu, pois viu a opressão com que o rei da Síria atormentava Israel.

[[v12-13-5]]

^<<v12-13-5,5>>^ O Senhor  deu um salvador a Israel, de modo que os filhos de Israel se livraram do poder dos sírios e puderam morar, de novo, em suas casas, como antes.

[[v12-13-6]]

^<<v12-13-6,6>>^ Contudo, não se afastaram dos pecados da casa de Jeroboão, que este levou Israel a cometer, mas andaram neles; e também o poste da deusa Aserá permaneceu em Samaria.

[[v12-13-7]]

^<<v12-13-7,7>>^ Do exército de Jeoacaz só restaram cinquenta cavaleiros, dez carros de guerra e dez mil soldados de infantaria, porque o rei da Síria havia destruído os demais, reduzindo-os a pó.

[[v12-13-8]]

^<<v12-13-8,8>>^ Quanto aos demais atos de Jeoacaz, a tudo o que fez e ao seu poder, não está tudo escrito no Livro da História dos Reis de Israel?

[[v12-13-9]]

^<<v12-13-9,9>>^ Jeoacaz morreu e foi sepultado em Samaria. E Jeoás, seu filho, reinou em seu lugar.

[[v12-13-10]]

^<<v12-13-10,10>>^ No trigésimo sétimo ano do reinado de Joás, rei de Judá, Jeoás, filho de Jeoacaz, começou a reinar sobre Israel, em Samaria; e reinou dezesseis anos.

[[v12-13-11]]

^<<v12-13-11,11>>^ Fez o que era mau aos olhos do Senhor . Não se afastou de nenhum dos pecados de Jeroboão, filho de Nebate, que este levou Israel a cometer; porém andou neles.

[[v12-13-12]]

^<<v12-13-12,12>>^ Quanto aos demais atos de Jeoás, a tudo o que fez e ao seu poder, com que lutou contra Amazias, rei de Judá, não está tudo escrito no Livro da História dos Reis de Israel?

[[v12-13-13]]

^<<v12-13-13,13>>^ Jeoás morreu, e no seu trono se assentou Jeroboão. Jeoás foi sepultado em Samaria, junto aos reis de Israel.

[[v12-13-14]]

^<<v12-13-14,14>>^ Quando Eliseu estava sofrendo da enfermidade da qual viria a morrer, Jeoás, rei de Israel, foi visitá-lo. Chorou diante dele e disse: — Meu pai, meu pai! Carros de Israel e seus cavaleiros!

[[v12-13-15]]

^<<v12-13-15,15>>^ Então Eliseu disse ao rei: — Pegue um arco e algumas flechas. Jeoás pegou o arco e as flechas.

[[v12-13-16]]

^<<v12-13-16,16>>^ Eliseu disse ao rei de Israel: — Empunhe o arco. O rei fez assim. Então Eliseu pôs as mãos sobre as mãos do rei

[[v12-13-17]]

^<<v12-13-17,17>>^ e disse: — Abra a janela que dá para o leste. O rei a abriu. Eliseu continuou: — Atire! E o rei atirou. Então Eliseu disse: — Flecha da vitória do Senhor ! Flecha da vitória contra os sírios! Você vencerá os sírios em Afeca, até acabar com eles.

[[v12-13-18]]

^<<v12-13-18,18>>^ Eliseu disse mais: — Pegue as flechas. Ele as pegou. Então disse ao rei de Israel: — Atire contra o chão. O rei fez isso três vezes e parou.

[[v12-13-19]]

^<<v12-13-19,19>>^ Então o homem de Deus ficou indignado com ele e disse: — Você deveria ter atirado cinco ou seis vezes e assim venceria os sírios até acabar com eles; mas agora vai vencê-los só três vezes.

[[v12-13-20]]

^<<v12-13-20,20>>^ Eliseu morreu, e o sepultaram. Ora, bandos dos moabitas costumavam invadir a terra, no começo do ano.

[[v12-13-21]]

^<<v12-13-21,21>>^ Aconteceu que, enquanto alguns sepultavam um homem, eis que viram um desses bandos. Então jogaram o homem na sepultura de Eliseu e fugiram. Quando o cadáver tocou nos ossos de Eliseu, o homem reviveu e se levantou sobre os pés.

[[v12-13-22]]

^<<v12-13-22,22>>^ Hazael, rei da Síria, oprimiu Israel durante todo o reinado de Jeoacaz.

[[v12-13-23]]

^<<v12-13-23,23>>^ Porém o Senhor  teve misericórdia de Israel, se compadeceu deles e voltou-se para eles, por amor da aliança com Abraão, Isaque e Jacó; e não quis destruí-los e, até agora, ainda não os expulsou da sua presença.

[[v12-13-24]]

^<<v12-13-24,24>>^ Hazael, rei da Síria, morreu, e Ben-Hadade, seu filho, reinou em seu lugar.

[[v12-13-25]]

^<<v12-13-25,25>>^ Jeoás, filho de Jeoacaz, retomou das mãos de Ben-Hadade as cidades que, na guerra, este havia tomado de Jeoacaz, seu pai. Três vezes Jeoás o derrotou e recuperou as cidades de Israel.

'''

xref:012-2-reis/012-2-reis-012.adoc#v12-12-0[&#60; Capítulo Anterior] | <<v12-13-0,Topo>> | xref:012-2-reis/012-2-reis-014.adoc#v12-14-0[Próximo Capítulo &#62;]