include::./index.adoc[]

[[v12-18-0]]
=== 2 Reis, 18
// naa ?, NAA - Nova Almeida Atualizada

[[v12-18-1]]

^<<v12-18-1,1>>^ No terceiro ano do reinado de Oseias, filho de Elá, rei de Israel, Ezequias, filho de Acaz, rei de Judá, começou a reinar.

[[v12-18-2]]

^<<v12-18-2,2>>^ Tinha vinte e cinco anos de idade quando começou a reinar e reinou vinte e nove anos em Jerusalém. A mãe dele se chamava Abi e era filha de Zacarias.

[[v12-18-3]]

^<<v12-18-3,3>>^ Ezequias fez o que era reto aos olhos do Senhor , segundo tudo o que Davi, seu pai, havia feito.

[[v12-18-4]]

^<<v12-18-4,4>>^ Removeu os lugares altos, quebrou as colunas e derrubou o poste da deusa Aserá. Também fez em pedaços a serpente de bronze que Moisés havia feito. Os filhos de Israel chamavam essa serpente de Neustã e até aquele dia lhe queimavam incenso.

[[v12-18-5]]

^<<v12-18-5,5>>^ Ezequias confiou no Senhor , Deus de Israel, de maneira que não houve ninguém como ele entre todos os reis de Judá, nem antes nem depois dele.

[[v12-18-6]]

^<<v12-18-6,6>>^ Porque se apegou ao Senhor , não deixou de segui-lo e guardou os mandamentos que o Senhor  ordenou a Moisés.

[[v12-18-7]]

^<<v12-18-7,7>>^ Assim, o Senhor  estava com ele, e ele teve êxito em todos os seus empreendimentos. Rebelou-se contra o rei da Assíria e não o serviu.

[[v12-18-8]]

^<<v12-18-8,8>>^ Derrotou os filisteus até Gaza e o seu território, desde a torre dos vigias até a cidade fortificada.

[[v12-18-9]]

^<<v12-18-9,9>>^ No quarto ano do reinado de Ezequias, que era o sétimo ano do reinado de Oseias, filho de Elá, rei de Israel, Salmaneser, rei da Assíria, atacou a cidade de Samaria e a cercou.

[[v12-18-10]]

^<<v12-18-10,10>>^ Ao fim de três anos, a cidade foi conquistada. Sim, no ano sexto do reinado de Ezequias, que era o nono ano do reinado de Oseias, rei de Israel, Samaria foi conquistada.

[[v12-18-11]]

^<<v12-18-11,11>>^ O rei da Assíria levou os israelitas para a Assíria e os fez habitar em Hala, junto a Habor, rio de Gozã, e nas cidades dos medos.

[[v12-18-12]]

^<<v12-18-12,12>>^ Isso aconteceu porque não obedeceram à voz do Senhor , seu Deus, mas quebraram a sua aliança, a saber, tudo o que Moisés, servo do Senhor , havia ordenado; não o ouviram, nem o fizeram.

[[v12-18-13]]

^<<v12-18-13,13>>^ No décimo quarto ano do reinado de Ezequias, Senaqueribe, rei da Assíria, atacou todas as cidades fortificadas de Judá e as conquistou.

[[v12-18-14]]

^<<v12-18-14,14>>^ Então Ezequias, rei de Judá, enviou mensageiros ao rei da Assíria, que estava em Laquis, dizendo: — Eu errei. Pare de me atacar, e cumprirei tudo o que você me impuser. Então o rei da Assíria impôs a Ezequias, rei de Judá, um tributo de dez toneladas de prata e uma tonelada de ouro.

[[v12-18-15]]

^<<v12-18-15,15>>^ Ezequias deu toda a prata que havia na Casa do Senhor  e nos tesouros do palácio real.

[[v12-18-16]]

^<<v12-18-16,16>>^ Foi quando Ezequias arrancou o ouro que havia nas portas do templo do Senhor  e nas ombreiras, o ouro com que ele, o rei de Judá, as havia revestido, e o deu ao rei da Assíria.

[[v12-18-17]]

^<<v12-18-17,17>>^ Mas o rei da Assíria, que estava em Laquis, enviou Tartã, Rabe-Saris e Rabsaqué, com um grande exército, ao rei Ezequias, em Jerusalém. Eles vieram a Jerusalém e, quando chegaram, pararam na extremidade do aqueduto do tanque superior, junto ao caminho do campo do Lavandeiro.

[[v12-18-18]]

^<<v12-18-18,18>>^ Mandaram chamar o rei, e quem saiu ao encontro deles foram Eliaquim, filho de Hilquias, o responsável pelo palácio, Sebna, o escrivão, e Joá, filho de Asafe, o cronista.

[[v12-18-19]]

^<<v12-18-19,19>>^ Rabsaqué disse: — Digam a Ezequias: Assim diz o grande rei, o rei da Assíria: "Que confiança é essa que você tem?

[[v12-18-20]]

^<<v12-18-20,20>>^ Bem posso dizer que o seu conselho e o seu poder para a guerra são meras palavras. Em quem você está confiando agora, para que se rebele contra mim?

[[v12-18-21]]

^<<v12-18-21,21>>^ Você confia nesse bordão de caniço esmagado que é o Egito. Se alguém se apoiar no caniço, ele vai espetar e furar a mão. Assim é Faraó, rei do Egito, para todos os que nele confiam.

[[v12-18-22]]

^<<v12-18-22,22>>^ Mas, se vocês me dizem: ‘Confiamos no Senhor , nosso Deus’, eu pergunto: não é esse aquele cujos lugares altos e altares Ezequias removeu, dizendo a Judá e a Jerusalém que deveriam adorar somente diante do altar em Jerusalém?

[[v12-18-23]]

^<<v12-18-23,23>>^ Agora, pois, comprometa-se com meu senhor, o rei da Assíria, e eu lhe darei dois mil cavalos, se você puder achar cavaleiros para montá-los.

[[v12-18-24]]

^<<v12-18-24,24>>^ Como você poderia repelir um oficial do meu senhor, o rei, mesmo que seja um dos menores, e confiar no Egito para obter carros de guerra e cavaleiros?

[[v12-18-25]]

^<<v12-18-25,25>>^ Será que você pensa que é sem o consentimento do Senhor  Deus que eu vim contra este lugar, para o destruir? Foi o próprio Senhor  quem ordenou que eu atacasse esta terra e a destruísse."

[[v12-18-26]]

^<<v12-18-26,26>>^ Então Eliaquim, filho de Hilquias, Sebna e Joá disseram a Rabsaqué: — Por favor, fale com estes seus servos em aramaico, porque nós o entendemos. Não fale em hebraico, aos ouvidos do povo que está sobre a muralha.

[[v12-18-27]]

^<<v12-18-27,27>>^ Mas Rabsaqué lhes respondeu: — Você pensa que o meu senhor me enviou para dizer estas palavras apenas a você e ao seu rei? Ele me enviou para falar também aos homens que estão sentados sobre a muralha e que, junto com vocês, terão de comer o seu próprio excremento e beber a sua própria urina!

[[v12-18-28]]

^<<v12-18-28,28>>^ Então Rabsaqué se pôs em pé e gritou em hebraico: — Escutem as palavras do grande rei, o rei da Assíria.

[[v12-18-29]]

^<<v12-18-29,29>>^ Assim diz o rei: "Não deixem que Ezequias os engane, pois ele não poderá livrá-los da minha mão.

[[v12-18-30]]

^<<v12-18-30,30>>^ Não deixem que Ezequias os leve a confiar no Senhor , dizendo: ‘O Senhor  certamente nos livrará, e esta cidade não será entregue nas mãos do rei da Assíria.’

[[v12-18-31]]

^<<v12-18-31,31>>^ Não deem ouvidos a Ezequias. Porque assim diz o rei da Assíria: ‘Façam as pazes comigo e se entreguem. Então cada um comerá da sua própria videira e da sua própria figueira, e beberá a água da sua própria cisterna,

[[v12-18-32]]

^<<v12-18-32,32>>^ até que eu venha e os leve para uma terra como a de vocês, terra de cereal e de vinho, terra de pão e de vinhas, terra de oliveiras e de mel, para que vocês vivam e não morram.’ Não deem ouvidos a Ezequias, porque ele está enganando vocês, ao dizer: ‘O Senhor  nos livrará.’

[[v12-18-33]]

^<<v12-18-33,33>>^ Será que os deuses das nações puderam livrar, cada um a sua terra, das mãos do rei da Assíria?

[[v12-18-34]]

^<<v12-18-34,34>>^ Onde estão os deuses de Hamate e de Arpade? Onde estão os deuses de Sefarvaim, Hena e Iva? Será que eles livraram Samaria das minhas mãos?

[[v12-18-35]]

^<<v12-18-35,35>>^ De todos os deuses destes países, quais foram os que livraram a sua terra das minhas mãos? Então como o Senhor  poderá livrar Jerusalém das minhas mãos?"

[[v12-18-36]]

^<<v12-18-36,36>>^ O povo ficou calado e não lhe respondeu palavra, porque assim lhe havia ordenado o rei: "Não lhe respondam."

[[v12-18-37]]

^<<v12-18-37,37>>^ Então Eliaquim, filho de Hilquias, o responsável pelo palácio, e Sebna, o escrivão, e Joá, filho de Asafe, o cronista, voltaram para junto do rei Ezequias, com as suas roupas rasgadas, e lhe contaram o que Rabsaqué tinha dito.

'''

xref:012-2-reis/012-2-reis-017.adoc#v12-17-0[&#60; Capítulo Anterior] | <<v12-18-0,Topo>> | xref:012-2-reis/012-2-reis-019.adoc#v12-19-0[Próximo Capítulo &#62;]