include::./index.adoc[]

[[v12-7-0]]
=== 2 Reis, 7
// naa ?, NAA - Nova Almeida Atualizada

[[v12-7-1]]

^<<v12-7-1,1>>^ Então Eliseu disse: — Ouçam a palavra do Senhor . Assim diz o Senhor : "Amanhã, a estas horas mais ou menos, junto ao portão de Samaria, uma medida da melhor farinha será vendida por uma moeda de prata, e duas medidas de cevada serão vendidas por uma moeda de prata."

[[v12-7-2]]

^<<v12-7-2,2>>^ Porém o capitão em cujo braço o rei se apoiava respondeu ao homem de Deus: — Mesmo que o Senhor  Deus fizesse janelas no céu, será que isso poderia acontecer? O profeta respondeu: — Eis que você verá isso com os seus próprios olhos, mas não comerá disso.

[[v12-7-3]]

^<<v12-7-3,3>>^ Quatro homens leprosos estavam à entrada do portão da cidade. Eles disseram uns aos outros: — Para que vamos ficar aqui sentados até morrer?

[[v12-7-4]]

^<<v12-7-4,4>>^ Se decidirmos entrar na cidade, há fome na cidade, e morreremos lá; se ficarmos sentados aqui, também morreremos. Vamos então para o arraial do sírios e nos entreguemos a eles. Se nos deixarem viver, viveremos; se nos matarem, apenas morreremos.

[[v12-7-5]]

^<<v12-7-5,5>>^ Ao anoitecer, eles se levantaram para ir até o arraial dos sírios. Quando chegaram às imediações do arraial, eis que lá não havia ninguém.

[[v12-7-6]]

^<<v12-7-6,6>>^ Porque o Senhor tinha feito com que no arraial dos sírios se ouvisse um ruído de carros de guerra e de cavalos e o ruído de um grande exército, de maneira que disseram uns aos outros: — Eis que o rei de Israel contratou os reis dos heteus e os reis dos egípcios, para virem contra nós.

[[v12-7-7]]

^<<v12-7-7,7>>^ Por isso, ao anoitecer, eles se levantaram e fugiram, abandonando as suas tendas, os seus cavalos e os seus jumentos, e deixando o arraial como estava. Fugiram para salvar a sua vida.

[[v12-7-8]]

^<<v12-7-8,8>>^ Assim, quando aqueles leprosos chegaram às imediações do arraial, entraram numa tenda, comeram e beberam; depois levaram dali prata, ouro e roupas; então se foram e esconderam tudo. Voltaram, entraram em outra tenda, e dali também levaram o que havia e esconderam.

[[v12-7-9]]

^<<v12-7-9,9>>^ Então disseram uns aos outros: — Não é certo o que estamos fazendo. Este dia é um dia de boas-novas, e nós nos calamos. Se esperarmos até a luz da manhã, seremos tidos por culpados. Vamos agora mesmo anunciar isto no palácio real.

[[v12-7-10]]

^<<v12-7-10,10>>^ Assim, eles foram e gritaram para os porteiros da cidade, anunciando o seguinte: — Fomos ao arraial dos sírios, e lá não vimos nem ouvimos ninguém. Encontramos apenas os cavalos e os jumentos amarrados, e as tendas como estavam.

[[v12-7-11]]

^<<v12-7-11,11>>^ Então os porteiros gritaram e fizeram anunciar a notícia no interior do palácio real.

[[v12-7-12]]

^<<v12-7-12,12>>^ O rei se levantou de noite e disse a seus servos: — Deixem que eu explique a vocês o que os sírios nos fizeram. Eles sabem que nós estamos famintos. Por isso, saíram do arraial e se esconderam no campo, pensando assim: "Quando eles saírem da cidade, nós os apanharemos vivos e entraremos na cidade."

[[v12-7-13]]

^<<v12-7-13,13>>^ Então um dos servos do rei tomou a palavra e disse: — Vamos enviar alguns homens com cinco dos cavalos que ainda restam na cidade e ver o que acontece. Se morrerem, apenas terão a mesma sorte da multidão dos israelitas que já morreram.

[[v12-7-14]]

^<<v12-7-14,14>>^ Assim, pegaram dois carros de guerra com cavalos, e o rei enviou os homens atrás do exército dos sírios, dizendo: — Vão ver o que está acontecendo.

[[v12-7-15]]

^<<v12-7-15,15>>^ Eles foram atrás dos sírios até o Jordão, e eis que todo o caminho estava cheio de roupas e de armas que os sírios, na sua pressa, tinham jogado fora. Os mensageiros voltaram e anunciaram isto ao rei.

[[v12-7-16]]

^<<v12-7-16,16>>^ Então o povo saiu e saqueou o arraial dos sírios. E assim uma medida da melhor farinha era vendida por uma moeda de prata, e duas medidas de cevada, por uma moeda de prata, segundo a palavra do Senhor .

[[v12-7-17]]

^<<v12-7-17,17>>^ O capitão em cujo braço o rei tinha se apoiado foi encarregado pelo rei de guardar o portão da cidade, mas o povo o atropelou junto ao portão e ele morreu, como o homem de Deus tinha dito quando o rei foi falar com ele.

[[v12-7-18]]

^<<v12-7-18,18>>^ Assim se cumpriu o que o homem de Deus tinha falado ao rei: "Amanhã, a estas horas mais ou menos, junto ao portão de Samaria, duas medidas de cevada serão vendidas por uma moeda de prata, e uma medida da melhor farinha será vendida por uma moeda de prata."

[[v12-7-19]]

^<<v12-7-19,19>>^ Aquele capitão havia respondido ao homem de Deus: "Mesmo que o Senhor  Deus fizesse janelas no céu, será que isso poderia acontecer, segundo essa palavra?" Ao que o profeta havia respondido: "Eis que você verá isso com os seus próprios olhos, mas não comerá disso."

[[v12-7-20]]

^<<v12-7-20,20>>^ E assim aconteceu com ele, porque o povo o atropelou junto ao portão, e ele morreu.

'''

xref:012-2-reis/012-2-reis-006.adoc#v12-6-0[&#60; Capítulo Anterior] | <<v12-7-0,Topo>> | xref:012-2-reis/012-2-reis-008.adoc#v12-8-0[Próximo Capítulo &#62;]