include::./index.adoc[]

[[v12-15-0]]
=== 2 Reis, 15
// naa ?, NAA - Nova Almeida Atualizada

[[v12-15-1]]

^<<v12-15-1,1>>^ No vigésimo sétimo ano do reinado de Jeroboão, rei de Israel, Azarias, filho de Amazias, rei de Judá, começou a reinar.

[[v12-15-2]]

^<<v12-15-2,2>>^ Tinha dezesseis anos de idade quando começou a reinar e reinou cinquenta e dois anos em Jerusalém. A mãe dele se chamava Jecolias e era de Jerusalém.

[[v12-15-3]]

^<<v12-15-3,3>>^ Ele fez o que era reto aos olhos do Senhor , segundo tudo o que Amazias, seu pai, havia feito.

[[v12-15-4]]

^<<v12-15-4,4>>^ Apenas os lugares altos não foram tirados, e o povo ainda sacrificava e queimava incenso nesses altos.

[[v12-15-5]]

^<<v12-15-5,5>>^ O Senhor  feriu o rei, e ele ficou leproso até o dia da sua morte e morava numa casa separada. Jotão, filho do rei, era responsável pelo palácio e governava o povo da terra.

[[v12-15-6]]

^<<v12-15-6,6>>^ Quanto aos demais atos de Azarias e a tudo o que fez, não está tudo escrito no Livro da História dos Reis de Judá?

[[v12-15-7]]

^<<v12-15-7,7>>^ Azarias morreu e foi sepultado no túmulo de seus pais, na Cidade de Davi; e Jotão, seu filho, reinou em seu lugar.

[[v12-15-8]]

^<<v12-15-8,8>>^ No trigésimo oitavo ano do reinado de Azarias, rei de Judá, Zacarias, filho de Jeroboão, reinou sobre Israel, em Samaria, durante seis meses.

[[v12-15-9]]

^<<v12-15-9,9>>^ Fez o que era mau aos olhos do Senhor , como tinham feito seus pais. Não se afastou dos pecados de Jeroboão, filho de Nebate, que este levou Israel a cometer.

[[v12-15-10]]

^<<v12-15-10,10>>^ Salum, filho de Jabes, conspirou contra ele, atacou-o diante do povo, matou-o e reinou em seu lugar.

[[v12-15-11]]

^<<v12-15-11,11>>^ Quanto aos demais atos de Zacarias, está tudo escrito no Livro da História dos Reis de Israel.

[[v12-15-12]]

^<<v12-15-12,12>>^ Esta foi a palavra que o Senhor  falou a Jeú: "Os seus filhos, até a quarta geração, se assentarão no trono de Israel." E assim aconteceu.

[[v12-15-13]]

^<<v12-15-13,13>>^ Salum, filho de Jabes, começou a reinar no trigésimo nono ano do reinado de Uzias, rei de Judá; e reinou durante um mês em Samaria.

[[v12-15-14]]

^<<v12-15-14,14>>^ Menaém, filho de Gadi, foi de Tirza a Samaria, atacou Salum, filho de Jabes, matou-o e reinou em seu lugar.

[[v12-15-15]]

^<<v12-15-15,15>>^ Quanto aos demais atos de Salum e a conspiração que fez, está tudo escrito no Livro da História dos Reis de Israel.

[[v12-15-16]]

^<<v12-15-16,16>>^ Saindo de Tirza, Menaém destruiu a cidade de Tifsa e todos os seus moradores, bem como toda aquela região. Porque não abriram o portão da cidade, ele a devastou. Até rasgou o ventre de todas as mulheres grávidas.

[[v12-15-17]]

^<<v12-15-17,17>>^ Desde o trigésimo nono ano do reinado de Azarias, rei de Judá, Menaém, filho de Gadi, começou a reinar sobre Israel e reinou dez anos em Samaria.

[[v12-15-18]]

^<<v12-15-18,18>>^ Fez o que era mau aos olhos do Senhor . Durante todos os seus dias não se afastou dos pecados de Jeroboão, filho de Nebate, que este levou Israel a cometer.

[[v12-15-19]]

^<<v12-15-19,19>>^ Então Pul, rei da Assíria, veio contra a terra, e Menaém lhe entregou trinta e quatro toneladas de prata, para que este o ajudasse a consolidar o seu reino.

[[v12-15-20]]

^<<v12-15-20,20>>^ Para pagar ao rei da Assíria, Menaém exigiu dinheiro de todos os poderosos e ricos em Israel, seiscentos gramas de prata por cabeça. E assim o rei da Assíria deu a volta e não se demorou ali na terra.

[[v12-15-21]]

^<<v12-15-21,21>>^ Quanto aos demais atos de Menaém e a tudo o que fez, não está tudo escrito no Livro da História dos Reis de Israel?

[[v12-15-22]]

^<<v12-15-22,22>>^ Menaém morreu, e Pecaías, seu filho, reinou em seu lugar.

[[v12-15-23]]

^<<v12-15-23,23>>^ No quinquagésimo ano do reinado de Azarias, rei de Judá, Pecaías, filho de Menaém, começou a reinar; e reinou sobre Israel, em Samaria, dois anos.

[[v12-15-24]]

^<<v12-15-24,24>>^ Fez o que era mau aos olhos do Senhor ; não se afastou dos pecados de Jeroboão, filho de Nebate, que este levou Israel a cometer.

[[v12-15-25]]

^<<v12-15-25,25>>^ Peca, seu capitão, filho de Remalias, conspirou contra ele e o feriu em Samaria, na fortaleza do palácio real, juntamente com Argobe e com Arié; com Peca estavam cinquenta homens dos gileaditas; Peca o matou e reinou em seu lugar.

[[v12-15-26]]

^<<v12-15-26,26>>^ Quanto aos demais atos de Pecaías e a tudo o que fez, está tudo escrito no Livro da História dos Reis de Israel.

[[v12-15-27]]

^<<v12-15-27,27>>^ No quinquagésimo segundo ano do reinado de Azarias, rei de Judá, Peca, filho de Remalias, começou a reinar; e reinou sobre Israel, em Samaria, vinte anos.

[[v12-15-28]]

^<<v12-15-28,28>>^ Fez o que era mau aos olhos do Senhor . Não se afastou dos pecados de Jeroboão, filho de Nebate, que este levou Israel a cometer.

[[v12-15-29]]

^<<v12-15-29,29>>^ Nos dias de Peca, rei de Israel, Tiglate-Pileser, rei da Assíria, veio e conquistou Ijom, Abel-Bete-Maaca, Janoa, Quedes, Hazor, as regiões de Gileade e da Galileia, toda a terra de Naftali, e levou os seus habitantes para a Assíria.

[[v12-15-30]]

^<<v12-15-30,30>>^ Oseias, filho de Elá, conspirou contra Peca, filho de Remalias, atacou-o e o matou, e reinou em seu lugar, no vigésimo ano do reinado de Jotão, filho de Uzias.

[[v12-15-31]]

^<<v12-15-31,31>>^ Quanto aos demais atos de Peca e a tudo o que fez, está tudo escrito no Livro da História dos Reis de Israel.

[[v12-15-32]]

^<<v12-15-32,32>>^ No segundo ano do reinado de Peca, filho de Remalias, rei de Israel, Jotão, filho de Uzias, rei de Judá, começou a reinar.

[[v12-15-33]]

^<<v12-15-33,33>>^ Ele tinha vinte e cinco anos de idade quando começou a reinar e reinou dezesseis anos em Jerusalém. A mãe dele se chamava Jerusa e era filha de Zadoque.

[[v12-15-34]]

^<<v12-15-34,34>>^ Fez o que era reto aos olhos do Senhor , segundo tudo o que Uzias, seu pai, havia feito.

[[v12-15-35]]

^<<v12-15-35,35>>^ Apenas os lugares altos não foram tirados, e o povo ainda sacrificava e queimava incenso nesses altos. Jotão construiu o Portão de Cima da Casa do Senhor .

[[v12-15-36]]

^<<v12-15-36,36>>^ Quanto aos demais atos de Jotão e a tudo o que fez, não está tudo escrito no Livro da História dos Reis de Judá?

[[v12-15-37]]

^<<v12-15-37,37>>^ Naqueles dias, o Senhor  começou a enviar Rezim, rei da Síria, e Peca, filho de Remalias, contra Judá.

[[v12-15-38]]

^<<v12-15-38,38>>^ Jotão morreu e foi sepultado no túmulo de seus pais, na Cidade de Davi, seu pai. E Acaz, seu filho, reinou em seu lugar.

'''

xref:012-2-reis/012-2-reis-014.adoc#v12-14-0[&#60; Capítulo Anterior] | <<v12-15-0,Topo>> | xref:012-2-reis/012-2-reis-016.adoc#v12-16-0[Próximo Capítulo &#62;]