include::./index.adoc[]

[[v12-8-0]]
=== 2 Reis, 8
// naa ?, NAA - Nova Almeida Atualizada

[[v12-8-1]]

^<<v12-8-1,1>>^ Eliseu falou àquela mulher cujo filho ele havia restaurado à vida, dizendo: — Levante-se e saia daqui com os membros de sua casa e fique peregrinando onde você puder peregrinar, porque o Senhor  determinou que haverá uma fome neste país, a qual irá durar sete anos.

[[v12-8-2]]

^<<v12-8-2,2>>^ A mulher se levantou e fez segundo a palavra do homem de Deus: saiu com os de sua casa e peregrinou durante sete anos na terra dos filisteus.

[[v12-8-3]]

^<<v12-8-3,3>>^ Ao final dos sete anos, a mulher voltou da terra dos filisteus e foi falar com o rei, para reclamar a sua casa e as suas terras.

[[v12-8-4]]

^<<v12-8-4,4>>^ O rei estava falando com Geazi, o servo do homem de Deus, dizendo: — Conte-me todas as grandes obras que Eliseu tem feito.

[[v12-8-5]]

^<<v12-8-5,5>>^ Ele estava contando ao rei como Eliseu havia restaurado à vida um morto, quando a mulher cujo filho ele havia restaurado à vida chegou para reclamar a sua casa e as suas terras. Então Geazi disse: — Ó rei, meu senhor, esta é a mulher, e este é o filho dela, a quem Eliseu restaurou à vida.

[[v12-8-6]]

^<<v12-8-6,6>>^ O rei interrogou a mulher, e ela lhe contou tudo. Então o rei colocou um oficial à disposição da mulher e lhe deu a seguinte ordem: — Faça com que lhe seja restituído tudo o que era dela, inclusive todas as rendas do campo desde o dia em que deixou a terra até agora.

[[v12-8-7]]

^<<v12-8-7,7>>^ Eliseu foi a Damasco. Ben-Hadade, o rei da Síria, estava doente, e lhe anunciaram, dizendo: — O homem de Deus chegou aqui.

[[v12-8-8]]

^<<v12-8-8,8>>^ Então o rei disse a Hazael: — Pegue um presente e vá encontrar-se com o homem de Deus. Por meio dele, pergunte ao Senhor  Deus se vou sarar desta doença.

[[v12-8-9]]

^<<v12-8-9,9>>^ Assim, Hazael foi encontrar-se com Eliseu, levando consigo um presente, a saber, quarenta camelos carregados de tudo o que era bom de Damasco. Ele chegou, apresentou-se diante dele e disse: — O seu filho Ben-Hadade, rei da Síria, me enviou para perguntar se ele vai sarar da sua doença.

[[v12-8-10]]

^<<v12-8-10,10>>^ Eliseu lhe respondeu: — Vá e diga ao rei que ele certamente vai sarar. Porém o Senhor  me mostrou que ele certamente morrerá.

[[v12-8-11]]

^<<v12-8-11,11>>^ Eliseu olhou para Hazael e tanto lhe fitou os olhos, que este ficou envergonhado. E o homem de Deus chorou.

[[v12-8-12]]

^<<v12-8-12,12>>^ Então Hazael perguntou: — Por que meu senhor está chorando? Ele respondeu: — Porque sei o mal que você vai fazer aos filhos de Israel. Você vai pôr fogo nas suas fortalezas, vai matar à espada os seus jovens, esmagar os seus pequeninos e rasgar o ventre das mulheres grávidas.

[[v12-8-13]]

^<<v12-8-13,13>>^ Hazael perguntou: — Mas o que é este seu servo, este cão, para fazer tão grandes coisas? Eliseu disse: — O Senhor  me mostrou que você será o rei da Síria.

[[v12-8-14]]

^<<v12-8-14,14>>^ Então Hazael deixou Eliseu e voltou para junto de seu senhor, o rei, que lhe perguntou: — O que foi que Eliseu disse a você? Hazael respondeu: — Ele me disse que o senhor certamente vai sarar.

[[v12-8-15]]

^<<v12-8-15,15>>^ No dia seguinte, Hazael pegou um cobertor, molhou-o em água e o estendeu sobre o rosto do rei até que morreu; e Hazael reinou em seu lugar.

[[v12-8-16]]

^<<v12-8-16,16>>^ No quinto ano do reinado de Jorão, filho de Acabe, rei de Israel, quando Josafá ainda reinava em Judá, Jeorão, filho de Josafá, rei de Judá, começou a reinar.

[[v12-8-17]]

^<<v12-8-17,17>>^ Ele tinha trinta e dois anos de idade quando começou a reinar e reinou oito anos em Jerusalém.

[[v12-8-18]]

^<<v12-8-18,18>>^ Andou nos caminhos dos reis de Israel, como também fizeram os da casa de Acabe, porque era casado com uma filha dele. E Jeorão fez o que era mau aos olhos do Senhor .

[[v12-8-19]]

^<<v12-8-19,19>>^ Porém o Senhor  não quis destruir Judá por amor a Davi, seu servo, segundo a promessa que lhe havia feito de dar uma lâmpada a ele e aos seus filhos para sempre.

[[v12-8-20]]

^<<v12-8-20,20>>^ Nos dias de Jeorão, os edomitas se revoltaram contra o poder de Judá e constituíram o seu próprio rei.

[[v12-8-21]]

^<<v12-8-21,21>>^ Por isso, Jeorão foi a Zair com todos os seus carros de guerra. Ele se levantou de noite e atacou os edomitas que o cercavam e os capitães dos carros de guerra; mas o povo de Jeorão fugiu para as suas tendas.

[[v12-8-22]]

^<<v12-8-22,22>>^ Assim, Edom se rebelou para se livrar do poder de Judá até o dia de hoje. Na mesma época a cidade de Libna também se rebelou.

[[v12-8-23]]

^<<v12-8-23,23>>^ Quanto aos demais atos de Jeorão e a tudo o que ele fez, não está tudo escrito no Livro da História dos Reis de Judá?

[[v12-8-24]]

^<<v12-8-24,24>>^ Jeorão morreu e foi sepultado nos túmulos de seus pais, na Cidade de Davi. E Acazias, filho de Jeorão, reinou em seu lugar.

[[v12-8-25]]

^<<v12-8-25,25>>^ No décimo segundo ano do reinado de Jorão, filho de Acabe, rei de Israel, Acazias, filho de Jeorão, rei de Judá, começou a reinar.

[[v12-8-26]]

^<<v12-8-26,26>>^ Acazias tinha vinte e dois anos de idade quando começou a reinar e reinou um ano em Jerusalém. A mãe dele, que era filha de Onri, rei de Israel, se chamava Atalia.

[[v12-8-27]]

^<<v12-8-27,27>>^ Acazias andou no caminho da casa de Acabe e fez o que era mau aos olhos do Senhor , como os da casa de Acabe, porque era casado com uma filha dele.

[[v12-8-28]]

^<<v12-8-28,28>>^ Acazias foi com Jorão, filho de Acabe, a Ramote-Gileade, para guerrear contra Hazael, rei da Síria; e os sírios feriram Jorão.

[[v12-8-29]]

^<<v12-8-29,29>>^ Então o rei Jorão voltou para Jezreel, para curar-se das feridas que os sírios lhe fizeram em Ramá, quando lutou contra Hazael, rei da Síria. E Acazias, filho de Jeorão, rei de Judá, foi a Jezreel para visitar Jorão, filho de Acabe, que estava doente.

'''

xref:012-2-reis/012-2-reis-007.adoc#v12-7-0[&#60; Capítulo Anterior] | <<v12-8-0,Topo>> | xref:012-2-reis/012-2-reis-009.adoc#v12-9-0[Próximo Capítulo &#62;]