include::./index.adoc[]

[[v12-12-0]]
=== 2 Reis, 12
// naa ?, NAA - Nova Almeida Atualizada

[[v12-12-1]]

^<<v12-12-1,1>>^ No sétimo ano do reinado de Jeú, Joás começou a reinar. Ele reinou quarenta anos em Jerusalém. A mãe dele se chamava Zíbia e era de Berseba.

[[v12-12-2]]

^<<v12-12-2,2>>^ Joás fez o que era reto aos olhos do Senhor , todos os dias em que o sacerdote Joiada o dirigia.

[[v12-12-3]]

^<<v12-12-3,3>>^ Apenas os lugares altos não foram tirados, e o povo ainda sacrificava e queimava incenso nesses altos.

[[v12-12-4]]

^<<v12-12-4,4>>^ Joás disse aos sacerdotes: — Todo o dinheiro das coisas santas que for trazido à Casa do Senhor , a saber, a taxa pessoal, o resgate de pessoas segundo a sua avaliação e todo o dinheiro que cada um trouxer voluntariamente para a Casa do Senhor ,

[[v12-12-5]]

^<<v12-12-5,5>>^ deverá ser recebido pelos sacerdotes, cada um dos seus conhecidos; e que os sacerdotes reparem os estragos do templo, sempre que houver um reparo a fazer.

[[v12-12-6]]

^<<v12-12-6,6>>^ Mas, no vigésimo terceiro ano do reinado de Joás, os sacerdotes ainda não tinham reparado os estragos do templo.

[[v12-12-7]]

^<<v12-12-7,7>>^ Então o rei Joás chamou o sacerdote Joiada e os outros sacerdotes e lhes disse: — Por que vocês não estão reparando os estragos do templo? Agora, pois, não recebam mais dinheiro de seus conhecidos, mas entreguem-no para a reparação dos estragos do templo.

[[v12-12-8]]

^<<v12-12-8,8>>^ Os sacerdotes concordaram em não mais receber dinheiro do povo e concordaram também que não ficariam encarregados de reparar os estragos do templo.

[[v12-12-9]]

^<<v12-12-9,9>>^ Então o sacerdote Joiada pegou uma caixa, fez um buraco na tampa, e a pôs junto ao altar, à direita de quem entrava na Casa do Senhor . Os sacerdotes que guardavam a entrada da porta depositavam ali todo o dinheiro que era trazido à Casa do Senhor .

[[v12-12-10]]

^<<v12-12-10,10>>^ Quando viam que já havia muito dinheiro na caixa, o escrivão do rei e o sumo sacerdote vinham, contavam e ensacavam o dinheiro que se achava na Casa do Senhor .

[[v12-12-11]]

^<<v12-12-11,11>>^ O dinheiro, depois de pesado, era entregue aos que dirigiam a obra e tinham a seu encargo a Casa do Senhor . Estes pagavam aos carpinteiros e aos construtores que reparavam a Casa do Senhor ,

[[v12-12-12]]

^<<v12-12-12,12>>^ e também aos pedreiros e aos cortadores de pedras. Também compravam madeira e pedras lavradas para repararem os estragos da Casa do Senhor , e custeavam todo o necessário para a conservação da Casa do Senhor .

[[v12-12-13]]

^<<v12-12-13,13>>^ Mas, do dinheiro que era trazido à Casa do Senhor , não se faziam nem taças de prata, nem apagadores, nem bacias, nem trombetas, nem qualquer outro vaso de ouro ou de prata para a Casa do Senhor .

[[v12-12-14]]

^<<v12-12-14,14>>^ Porque davam o dinheiro aos que dirigiam a obra e reparavam com ele a Casa do Senhor .

[[v12-12-15]]

^<<v12-12-15,15>>^ Também não pediam contas aos homens em cujas mãos entregavam aquele dinheiro, para o dar aos que faziam a obra, porque eram honestos.

[[v12-12-16]]

^<<v12-12-16,16>>^ Mas o dinheiro de oferta pela culpa e o dinheiro de oferta pelos pecados não era trazido à Casa do Senhor ; ficava para os sacerdotes.

[[v12-12-17]]

^<<v12-12-17,17>>^ Nessa época Hazael, rei da Síria, atacou e conquistou a cidade de Gate. Depois Hazael resolveu marchar contra Jerusalém.

[[v12-12-18]]

^<<v12-12-18,18>>^ Porém Joás, rei de Judá, pegou todas as coisas santas que Josafá, Jeorão e Acazias, seus pais, reis de Judá, haviam dedicado, bem como todo o ouro que havia nos tesouros da Casa do Senhor  e no palácio real e os mandou a Hazael, rei da Síria; e este se retirou de Jerusalém.

[[v12-12-19]]

^<<v12-12-19,19>>^ Quanto aos demais atos de Joás e a tudo o que fez, não está tudo escrito no Livro da História dos Reis de Judá?

[[v12-12-20]]

^<<v12-12-20,20>>^ Os servos de Joás se levantaram, fizeram uma conspiração e mataram Joás na casa de Milo, que fica na descida para Sila.

[[v12-12-21]]

^<<v12-12-21,21>>^ Jozacar, filho de Simeate, e Jozabade, filho de Somer, servos de Joás, o atacaram, e ele morreu. Joás foi sepultado no túmulo de seus pais na Cidade de Davi, e Amazias, seu filho, reinou em seu lugar.

'''

xref:012-2-reis/012-2-reis-011.adoc#v12-11-0[&#60; Capítulo Anterior] | <<v12-12-0,Topo>> | xref:012-2-reis/012-2-reis-013.adoc#v12-13-0[Próximo Capítulo &#62;]