include::./index.adoc[]

[[v12-14-0]]
=== 2 Reis, 14
// naa ?, NAA - Nova Almeida Atualizada

[[v12-14-1]]

^<<v12-14-1,1>>^ No segundo ano do reinado de Jeoás, filho de Jeoacaz, rei de Israel, Amazias, filho de Joás, rei de Judá, começou a reinar.

[[v12-14-2]]

^<<v12-14-2,2>>^ Tinha vinte e cinco anos de idade quando começou a reinar e reinou vinte e nove anos em Jerusalém. A mãe dele se chamava Jeoadã e era de Jerusalém.

[[v12-14-3]]

^<<v12-14-3,3>>^ Amazias fez o que era reto aos olhos do Senhor , ainda que não como Davi, seu pai; mas fez segundo tudo o que o seu pai Joás havia feito.

[[v12-14-4]]

^<<v12-14-4,4>>^ Apenas os lugares altos não foram tirados, e o povo ainda sacrificava e queimava incenso nesses altos.

[[v12-14-5]]

^<<v12-14-5,5>>^ Logo que o reino foi confirmado nas suas mãos, matou os servos que tinham assassinado o rei, seu pai.

[[v12-14-6]]

^<<v12-14-6,6>>^ No entanto, não matou os filhos dos assassinos, mas fez segundo está escrito no Livro da Lei de Moisés, no qual o Senhor  deu ordem, dizendo: "Os pais não serão mortos por causa dos filhos, nem os filhos serão mortos por causa dos pais; cada qual será morto pelo seu próprio pecado."

[[v12-14-7]]

^<<v12-14-7,7>>^ Amazias matou dez mil edomitas no vale do Sal e conquistou a cidade de Sela na guerra, dando-lhe o nome de Jocteel, que ela conserva até o dia de hoje.

[[v12-14-8]]

^<<v12-14-8,8>>^ Então Amazias enviou mensageiros a Jeoás, filho de Jeoacaz, filho de Jeú, rei de Israel, dizendo: — Venha me enfrentar no campo de batalha.

[[v12-14-9]]

^<<v12-14-9,9>>^ Porém Jeoás, rei de Israel, respondeu a Amazias, rei de Judá: — O espinheiro que está no Líbano mandou dizer ao cedro que lá está: "Dê a sua filha por mulher ao meu filho." Mas um animal selvagem, que estava no Líbano, passou e pisoteou o espinheiro.

[[v12-14-10]]

^<<v12-14-10,10>>^ Na verdade, você derrotou os edomitas, e o seu coração se encheu de orgulho. Glorie-se disso e fique em casa. Por que provocar um mal que trará somente desgraça para você e para Judá?

[[v12-14-11]]

^<<v12-14-11,11>>^ Mas Amazias não quis atendê-lo. Então Jeoás, rei de Israel, avançou contra Amazias, rei de Judá, e eles se enfrentaram em Bete-Semes, que está em Judá.

[[v12-14-12]]

^<<v12-14-12,12>>^ Judá foi derrotado por Israel, e os soldados tiveram de fugir para as suas casas.

[[v12-14-13]]

^<<v12-14-13,13>>^ Jeoás, rei de Israel, prendeu Amazias, rei de Judá, filho de Joás, filho de Acazias, em Bete-Semes. Então foi a Jerusalém e derrubou uma parte da muralha da cidade, desde o Portão de Efraim até o Portão da Esquina, numa extensão de mais ou menos duzentos metros.

[[v12-14-14]]

^<<v12-14-14,14>>^ Pegou todo o ouro, a prata e todos os utensílios que havia na Casa do Senhor  e nos tesouros do palácio real, bem como alguns reféns; e voltou para Samaria.

[[v12-14-15]]

^<<v12-14-15,15>>^ Quanto aos demais atos de Jeoás, ao que fez e ao seu poder, com que lutou contra Amazias, rei de Judá, não está tudo escrito no Livro da História dos Reis de Israel?

[[v12-14-16]]

^<<v12-14-16,16>>^ Jeoás morreu e foi sepultado em Samaria, junto aos reis de Israel. E Jeroboão, seu filho, reinou em seu lugar.

[[v12-14-17]]

^<<v12-14-17,17>>^ Amazias, filho de Joás, rei de Judá, viveu quinze anos depois da morte de Jeoás, filho de Jeoacaz, rei de Israel.

[[v12-14-18]]

^<<v12-14-18,18>>^ Quanto aos demais atos de Amazias, não está tudo escrito no Livro da História dos Reis de Judá?

[[v12-14-19]]

^<<v12-14-19,19>>^ Conspiraram contra ele em Jerusalém, e ele fugiu para Laquis; porém enviaram homens atrás dele até Laquis e o mataram.

[[v12-14-20]]

^<<v12-14-20,20>>^ Trouxeram-no sobre cavalos e o sepultaram em Jerusalém, junto a seus pais, na Cidade de Davi.

[[v12-14-21]]

^<<v12-14-21,21>>^ Todo o povo de Judá tomou Uzias, que tinha dezesseis anos de idade, e o constituiu rei em lugar de Amazias, seu pai.

[[v12-14-22]]

^<<v12-14-22,22>>^ Depois da morte de seu pai, Uzias reconstruiu Elate e a restituiu a Judá.

[[v12-14-23]]

^<<v12-14-23,23>>^ No décimo quinto ano do reinado de Amazias, filho de Joás, rei de Judá, Jeroboão, filho de Jeoás, rei de Israel, começou a reinar em Samaria; e reinou quarenta e um anos.

[[v12-14-24]]

^<<v12-14-24,24>>^ Jeroboão fez o que era mau aos olhos do Senhor . Jamais se afastou de nenhum dos pecados de Jeroboão, filho de Nebate, que este levou Israel a cometer.

[[v12-14-25]]

^<<v12-14-25,25>>^ Restabeleceu os limites de Israel, desde a entrada de Hamate até o mar da Arabá, segundo a palavra do Senhor , Deus de Israel, anunciada por meio de seu servo Jonas, filho de Amitai, o profeta, que era de Gate-Hefer.

[[v12-14-26]]

^<<v12-14-26,26>>^ Porque o Senhor  viu que a aflição de Israel era muito amarga, porque não havia nem escravo, nem livre, nem quem socorresse Israel.

[[v12-14-27]]

^<<v12-14-27,27>>^ O Senhor  ainda não havia falado em apagar o nome de Israel da face da terra; porém os livrou por meio de Jeroboão, filho de Jeoás.

[[v12-14-28]]

^<<v12-14-28,28>>^ Quanto aos demais atos de Jeroboão, tudo o que fez, o seu poder, como lutou e como reconquistou Damasco e Hamate, pertencentes a Judá, para Israel, não está tudo escrito no Livro da História dos Reis de Israel?

[[v12-14-29]]

^<<v12-14-29,29>>^ Jeroboão morreu e foi sepultado nos túmulos dos reis de Israel; e Zacarias, seu filho, reinou em seu lugar.

'''

xref:012-2-reis/012-2-reis-013.adoc#v12-13-0[&#60; Capítulo Anterior] | <<v12-14-0,Topo>> | xref:012-2-reis/012-2-reis-015.adoc#v12-15-0[Próximo Capítulo &#62;]