include::./index.adoc[]

[[v12-17-0]]
=== 2 Reis, 17
// naa ?, NAA - Nova Almeida Atualizada

[[v12-17-1]]

^<<v12-17-1,1>>^ No décimo segundo ano do reinado de Acaz, rei de Judá, Oseias, filho de Elá, começou a reinar; e reinou sobre Israel, em Samaria, nove anos.

[[v12-17-2]]

^<<v12-17-2,2>>^ Fez o que era mau aos olhos do Senhor , porém não como os reis de Israel que vieram antes dele.

[[v12-17-3]]

^<<v12-17-3,3>>^ Salmaneser, rei da Assíria, fez guerra contra Oseias, e este ficou sendo servo dele e lhe pagava tributo.

[[v12-17-4]]

^<<v12-17-4,4>>^ Porém o rei da Assíria descobriu que Oseias estava conspirando contra ele. Oseias tinha mandado mensageiros a Sô, rei do Egito, e não mais pagava tributo ao rei da Assíria, como anteriormente fazia de ano em ano. Por isso, o rei da Assíria prendeu Oseias e o lançou num cárcere.

[[v12-17-5]]

^<<v12-17-5,5>>^ Depois, o rei da Assíria passou por toda a terra, foi até a cidade de Samaria e a sitiou por três anos.

[[v12-17-6]]

^<<v12-17-6,6>>^ No nono ano do reinado de Oseias, o rei da Assíria conquistou Samaria e levou os israelitas para a Assíria. Ele os fez habitar em Hala, junto a Habor, rio de Gozã, e nas cidades dos medos.

[[v12-17-7]]

^<<v12-17-7,7>>^ Isso aconteceu porque os filhos de Israel pecaram contra o Senhor , seu Deus, que os tirou da terra do Egito e os livrou do poder de Faraó, rei do Egito; e temeram outros deuses.

[[v12-17-8]]

^<<v12-17-8,8>>^ Andaram nos estatutos das nações que o Senhor  expulsou de diante dos filhos de Israel e nos costumes estabelecidos pelos reis de Israel.

[[v12-17-9]]

^<<v12-17-9,9>>^ Os filhos de Israel fizeram contra o Senhor , seu Deus, o que não era reto; edificaram para si lugares altos em todas as suas cidades, desde a torre dos vigias até a cidade fortificada.

[[v12-17-10]]

^<<v12-17-10,10>>^ Levantaram para si colunas e postes da deusa Aserá, em todas as colinas mais elevadas e debaixo de todas as árvores frondosas.

[[v12-17-11]]

^<<v12-17-11,11>>^ Queimaram ali incenso em todos os lugares altos, como as nações que o Senhor  havia expulsado de diante deles. Cometeram ações perversas para provocarem o Senhor  à ira

[[v12-17-12]]

^<<v12-17-12,12>>^ e serviram os ídolos, dos quais o Senhor  lhes tinha dito: "Não façam estas coisas."

[[v12-17-13]]

^<<v12-17-13,13>>^ O Senhor  advertiu Israel e Judá por meio de todos os profetas e de todos os videntes, dizendo: "Voltem-se dos seus maus caminhos e guardem os meus mandamentos e os meus estatutos, segundo toda a Lei que ordenei aos pais de vocês e que lhes enviei por meio dos meus servos, os profetas."

[[v12-17-14]]

^<<v12-17-14,14>>^ Porém eles não quiseram ouvir; se tornaram obstinados e foram teimosos como os seus pais, que não creram no Senhor , seu Deus.

[[v12-17-15]]

^<<v12-17-15,15>>^ Rejeitaram os estatutos e a aliança que Deus tinha feito com os pais deles, e desprezaram as suas advertências. Seguiram os ídolos sem valor, e assim eles mesmos se tornaram sem valor. Seguiram as nações que estavam ao redor deles, das quais o Senhor  lhes havia ordenado que não as imitassem.

[[v12-17-16]]

^<<v12-17-16,16>>^ Desprezaram todos os mandamentos do Senhor , seu Deus, e fizeram para si imagens de fundição, dois bezerros; fizeram um poste da deusa Aserá, e adoraram todo o exército do céu, e serviram Baal.

[[v12-17-17]]

^<<v12-17-17,17>>^ Também queimaram os seus filhos e as suas filhas como sacrifício, deram-se à prática de adivinhações e acreditaram em agouros; e venderam-se para fazer o que era mau aos olhos do Senhor , para o provocarem à ira.

[[v12-17-18]]

^<<v12-17-18,18>>^ Por isso o Senhor  muito se indignou contra Israel e o afastou da sua presença; e nada mais ficou, a não ser a tribo de Judá.

[[v12-17-19]]

^<<v12-17-19,19>>^ Também Judá não guardou os mandamentos do Senhor , seu Deus; pelo contrário, andaram nos costumes que Israel introduziu.

[[v12-17-20]]

^<<v12-17-20,20>>^ Por isso o Senhor  rejeitou toda a descendência de Israel, e os afligiu, e os entregou nas mãos dos espoliadores, até que os expulsou da sua presença.

[[v12-17-21]]

^<<v12-17-21,21>>^ Pois, quando ele separou Israel da casa de Davi, e eles fizeram de Jeroboão, filho de Nebate, o seu rei, Jeroboão levou Israel a abandonar o Senhor  e o levou a cometer grande pecado.

[[v12-17-22]]

^<<v12-17-22,22>>^ Assim, os filhos de Israel andaram em todos os pecados que Jeroboão tinha cometido; nunca se afastaram deles,

[[v12-17-23]]

^<<v12-17-23,23>>^ até que o Senhor  afastou Israel da sua presença, como havia falado pelo ministério de todos os seus servos, os profetas. E assim Israel foi levado cativo da sua terra para a Assíria, onde permanece até o dia de hoje.

[[v12-17-24]]

^<<v12-17-24,24>>^ O rei da Assíria trouxe gente da Babilônia, de Cuta, de Ava, de Hamate e de Sefarvaim e os fez morar nas cidades de Samaria, em lugar dos filhos de Israel. Tomaram posse de Samaria e habitaram nas suas cidades.

[[v12-17-25]]

^<<v12-17-25,25>>^ A princípio, quando passaram a morar ali, não temeram o Senhor . Então o Senhor  mandou para o meio deles leões, que mataram alguns do povo.

[[v12-17-26]]

^<<v12-17-26,26>>^ Por isso disseram ao rei da Assíria: — Os povos que o senhor, ó rei, transportou e fez habitar nas cidades de Samaria não sabem a maneira de servir o deus daquela terra e por isso ele mandou leões para o meio deles. Os leões estão matando aquelas pessoas, porque elas não sabem como servir o deus daquela terra.

[[v12-17-27]]

^<<v12-17-27,27>>^ Então o rei da Assíria mandou dizer: — Levem para lá um dos sacerdotes que vocês trouxeram de lá. Que ele vá, fique morando lá, e lhes ensine a maneira de servir o deus daquela terra.

[[v12-17-28]]

^<<v12-17-28,28>>^ Assim um dos sacerdotes que havia sido levado de Samaria foi e ficou morando em Betel. E lhes ensinava como deviam temer o Senhor .

[[v12-17-29]]

^<<v12-17-29,29>>^ Porém cada nação fez ainda os seus próprios deuses nas cidades em que morava, e os puseram nos santuários dos lugares altos que os samaritanos tinham feito.

[[v12-17-30]]

^<<v12-17-30,30>>^ Os da Babilônia fizeram Sucote-Benote; os de Cuta fizeram Nergal; os de Hamate fizeram Asima;

[[v12-17-31]]

^<<v12-17-31,31>>^ os aveus fizeram Nibaz e Tartaque; e os sefarvitas queimavam seus filhos a Adrameleque e a Anameleque, deuses de Sefarvaim.

[[v12-17-32]]

^<<v12-17-32,32>>^ Mas adoravam também o Senhor . Constituíram como sacerdotes dos lugares altos homens tirados do meio do povo, os quais oficiavam a favor deles nos santuários dos altos.

[[v12-17-33]]

^<<v12-17-33,33>>^ E assim eles adoravam o Senhor  e, ao mesmo tempo, serviam os seus próprios deuses, segundo o costume das nações do meio das quais tinham sido trazidos.

[[v12-17-34]]

^<<v12-17-34,34>>^ Até o dia de hoje fazem segundo os antigos costumes. Não temem o Senhor , não fazem segundo os seus estatutos e juízos, nem segundo a lei e o mandamento que o Senhor  ordenou aos filhos de Jacó, a quem deu o nome de Israel.

[[v12-17-35]]

^<<v12-17-35,35>>^ Ora, o Senhor  tinha feito uma aliança com eles e lhes havia ordenado o seguinte: "Não temam outros deuses; não se prostrem diante deles, não os sirvam, nem lhes ofereçam sacrifícios.

[[v12-17-36]]

^<<v12-17-36,36>>^ Mas temam o Senhor , que os tirou da terra do Egito com grande poder e com braço estendido; prostrem-se diante dele e a ele ofereçam sacrifícios.

[[v12-17-37]]

^<<v12-17-37,37>>^ Tenham o cuidado de observar todos os dias os estatutos e os juízos, a lei e o mandamento que ele lhes deu por escrito. Não adorem outros deuses.

[[v12-17-38]]

^<<v12-17-38,38>>^ Não se esqueçam da aliança que fiz com vocês e não adorem outros deuses.

[[v12-17-39]]

^<<v12-17-39,39>>^ Mas adorem o Senhor , seu Deus, e ele os livrará das mãos de todos os seus inimigos."

[[v12-17-40]]

^<<v12-17-40,40>>^ Eles, porém, não deram ouvidos a isso e continuaram a fazer segundo o seu antigo costume.

[[v12-17-41]]

^<<v12-17-41,41>>^ Assim, estas nações adoravam o Senhor  e serviam as suas próprias imagens de escultura. Como fizeram os seus pais, assim fazem também os seus filhos e os filhos de seus filhos, até o dia de hoje.

'''

xref:012-2-reis/012-2-reis-016.adoc#v12-16-0[&#60; Capítulo Anterior] | <<v12-17-0,Topo>> | xref:012-2-reis/012-2-reis-018.adoc#v12-18-0[Próximo Capítulo &#62;]