include::./index.adoc[]

[[v12-23-0]]
=== 2 Reis, 23
// naa ?, NAA - Nova Almeida Atualizada

[[v12-23-1]]

^<<v12-23-1,1>>^ Então o rei deu ordem, e todos os anciãos de Judá e de Jerusalém se ajuntaram a ele.

[[v12-23-2]]

^<<v12-23-2,2>>^ O rei subiu à Casa do Senhor , e com ele foram todos os homens de Judá, todos os moradores de Jerusalém, os sacerdotes, os profetas e todo o povo, desde o menor até o maior. E o rei leu diante deles todas as palavras do Livro da Aliança que havia sido encontrado na Casa do Senhor .

[[v12-23-3]]

^<<v12-23-3,3>>^ O rei se pôs em pé junto à coluna e fez aliança diante do Senhor , para o seguir, guardar os seus mandamentos, os seus testemunhos e os seus estatutos, de todo o coração e de toda a alma, cumprindo as palavras desta aliança, que estavam escritas naquele livro. E todo o povo concordou com esta aliança.

[[v12-23-4]]

^<<v12-23-4,4>>^ Então o rei ordenou ao sumo sacerdote Hilquias, aos sacerdotes da segunda ordem e aos guardas da porta que tirassem do templo do Senhor  todos os utensílios que tinham sido feitos para Baal, para o poste da deusa Aserá e para todo o exército dos céus. Ele os queimou fora de Jerusalém, nos campos do Cedrom, e levou as cinzas para Betel.

[[v12-23-5]]

^<<v12-23-5,5>>^ Josias destituiu os sacerdotes que os reis de Judá haviam escolhido para queimar incenso sobre os lugares altos nas cidades de Judá e ao redor de Jerusalém, bem como os que queimavam incenso a Baal, ao sol, à lua, aos planetas e a todo o exército dos céus.

[[v12-23-6]]

^<<v12-23-6,6>>^ Também tirou da Casa do Senhor  o poste da deusa Aserá, que levou para fora de Jerusalém até o vale do Cedrom, onde o queimou e o reduziu a pó, que lançou sobre as sepulturas do povo simples.

[[v12-23-7]]

^<<v12-23-7,7>>^ Também destruiu as dependências dos prostitutos cultuais que estavam na Casa do Senhor , onde as mulheres teciam tendas para o poste da deusa Aserá.

[[v12-23-8]]

^<<v12-23-8,8>>^ Josias trouxe todos os sacerdotes das cidades de Judá e profanou os lugares altos em que os sacerdotes queimavam incenso, desde Geba até Berseba. Derrubou os altares das portas, que estavam à entrada do portão de Josué, governador da cidade, e que ficavam à esquerda de quem entrava por ela.

[[v12-23-9]]

^<<v12-23-9,9>>^ Os sacerdotes dos lugares altos não ofereciam sacrifícios sobre o altar do Senhor , em Jerusalém, mas comiam pães sem fermento no meio de seus irmãos.

[[v12-23-10]]

^<<v12-23-10,10>>^ Josias também profanou Tofete, que ficava no vale dos filhos de Hinom, para que ninguém queimasse o seu filho ou a sua filha como sacrifício a Moloque.

[[v12-23-11]]

^<<v12-23-11,11>>^ Também tirou os cavalos que os reis de Judá tinham dedicado ao sol, à entrada da Casa do Senhor , perto da câmara de Natã-Meleque, o camareiro, a qual ficava no átrio; e queimou os carros dedicados ao sol.

[[v12-23-12]]

^<<v12-23-12,12>>^ O rei também derrubou os altares que estavam sobre a sala de Acaz, sobre o terraço, altares que foram feitos pelos reis de Judá, bem como os altares que Manassés tinha construído nos dois átrios da Casa do Senhor . Ele os fez em pedaços, tirou dali e lançou o pó deles no ribeiro de Cedrom.

[[v12-23-13]]

^<<v12-23-13,13>>^ O rei profanou também os lugares altos que estavam a leste de Jerusalém, ao sul do monte da Destruição, os quais Salomão, rei de Israel, havia construído para Astarote, abominação dos sidônios, para Quemos, abominação dos moabitas, e para Milcom, abominação dos filhos de Amom.

[[v12-23-14]]

^<<v12-23-14,14>>^ Semelhantemente, fez em pedaços as colunas, cortou os postes da deusa Aserá e encheu de ossos humanos o lugar onde haviam estado.

[[v12-23-15]]

^<<v12-23-15,15>>^ Josias também derrubou o altar que estava em Betel e o lugar alto que Jeroboão, filho de Nebate, havia construído para levar Israel a pecar. Destruiu o lugar alto, reduziu a pó o seu altar e queimou o poste da deusa Aserá.

[[v12-23-16]]

^<<v12-23-16,16>>^ Quando Josias olhou ao seu redor, viu as sepulturas que estavam ali no monte; mandou tirar delas os ossos e os queimou sobre o altar. E assim ele profanou o altar, segundo a palavra do Senhor  proclamada pelo homem de Deus que havia predito estas coisas.

[[v12-23-17]]

^<<v12-23-17,17>>^ Então o rei perguntou: — Que monumento é este que estou vendo? Os homens da cidade responderam: — É a sepultura do homem de Deus que veio de Judá e proclamou estas coisas que o senhor acaba de fazer contra o altar de Betel.

[[v12-23-18]]

^<<v12-23-18,18>>^ Josias disse: — Deixem-no estar; ninguém mexa nos ossos dele. Assim, deixaram estar os seus ossos com os ossos do profeta que tinha vindo de Samaria.

[[v12-23-19]]

^<<v12-23-19,19>>^ Josias também tirou todos os santuários dos lugares altos que havia nas cidades de Samaria e que os reis de Israel tinham feito para provocarem o Senhor  à ira; e fez com esses santuários o mesmo que havia feito em Betel.

[[v12-23-20]]

^<<v12-23-20,20>>^ E também matou todos os sacerdotes dos lugares altos que havia ali, sobre os altares, e queimou ossos humanos sobre eles. Depois voltou para Jerusalém.

[[v12-23-21]]

^<<v12-23-21,21>>^ O rei deu ordem a todo o povo, dizendo: — Celebrem a Páscoa ao Senhor , o Deus de vocês, como está escrito neste Livro da Aliança.

[[v12-23-22]]

^<<v12-23-22,22>>^ Porque nunca se celebrou uma Páscoa como esta desde os dias dos juízes que julgaram Israel, nem durante os dias dos reis de Israel, nem nos dias dos reis de Judá.

[[v12-23-23]]

^<<v12-23-23,23>>^ Porém no décimo oitavo ano do reinado de Josias esta Páscoa foi celebrada ao Senhor , em Jerusalém.

[[v12-23-24]]

^<<v12-23-24,24>>^ Josias também eliminou os médiuns, os feiticeiros, os ídolos do lar, os ídolos e todas as abominações que se viam na terra de Judá e em Jerusalém, para cumprir as palavras da lei, que estavam escritas no livro que o sacerdote Hilquias havia achado na Casa do Senhor .

[[v12-23-25]]

^<<v12-23-25,25>>^ Antes dele, não houve rei que lhe fosse semelhante, que se convertesse ao Senhor  de todo o seu coração, de toda a sua alma e com todas as suas forças, segundo toda a Lei de Moisés; e, depois dele, nunca se levantou outro igual.

[[v12-23-26]]

^<<v12-23-26,26>>^ No entanto, o Senhor  não desistiu do furor da sua grande ira, ira que se acendeu contra Judá por causa de todas as provocações com que Manassés o tinha irritado.

[[v12-23-27]]

^<<v12-23-27,27>>^ O Senhor  disse: — Removerei da minha presença também Judá, como removi Israel, e rejeitarei Jerusalém, a cidade que escolhi, e o templo do qual eu disse: "O meu nome estará ali."

[[v12-23-28]]

^<<v12-23-28,28>>^ Quanto aos demais atos de Josias e a tudo o que fez, não está tudo escrito no Livro da História dos Reis de Judá?

[[v12-23-29]]

^<<v12-23-29,29>>^ Nos dias de Josias, Faraó Neco, rei do Egito, marchou em direção ao rio Eufrates, para ajudar o rei da Assíria. O rei Josias saiu para lutar contra ele, mas Faraó Neco o matou, em Megido, no primeiro encontro.

[[v12-23-30]]

^<<v12-23-30,30>>^ De Megido, os seus servos o levaram morto e, num carro, o transportaram para Jerusalém, onde o sepultaram no seu túmulo. O povo da terra tomou Joacaz, filho de Josias, e o ungiu, e o fez rei em lugar de seu pai.

[[v12-23-31]]

^<<v12-23-31,31>>^ Joacaz tinha vinte e três anos de idade quando começou a reinar e reinou três meses em Jerusalém. A mãe dele se chamava Hamutal e era filha de Jeremias, de Libna.

[[v12-23-32]]

^<<v12-23-32,32>>^ Joacaz fez o que era mau aos olhos do Senhor , segundo tudo o que os seus pais haviam feito.

[[v12-23-33]]

^<<v12-23-33,33>>^ Porém Faraó Neco mandou prendê-lo em Ribla, na terra de Hamate, para que não reinasse em Jerusalém; e impôs à terra um tributo de três mil e quatrocentos quilos de prata e trinta e quatro quilos de ouro.

[[v12-23-34]]

^<<v12-23-34,34>>^ Faraó Neco colocou Eliaquim, filho de Josias, como rei em lugar de Josias, seu pai, e mudou o nome dele para Jeoaquim. Mas levou Joacaz consigo para o Egito, onde ele morreu.

[[v12-23-35]]

^<<v12-23-35,35>>^ Jeoaquim entregou aquela prata e aquele ouro a Faraó. Mas, para dar esse dinheiro segundo a ordem de Faraó, Jeoaquim estabeleceu um imposto sobre a terra. Do povo da terra exigiu prata e ouro, de cada um segundo as suas posses, para o dar a Faraó Neco.

[[v12-23-36]]

^<<v12-23-36,36>>^ Jeoaquim tinha vinte e cinco anos de idade quando começou a reinar e reinou onze anos em Jerusalém. A mãe dele se chamava Zebida e era filha de Pedaías, de Ruma.

[[v12-23-37]]

^<<v12-23-37,37>>^ Jeoaquim fez o que era mau aos olhos do Senhor , segundo tudo o que os seus pais haviam feito.

'''

xref:012-2-reis/012-2-reis-022.adoc#v12-22-0[&#60; Capítulo Anterior] | <<v12-23-0,Topo>> | xref:012-2-reis/012-2-reis-024.adoc#v12-24-0[Próximo Capítulo &#62;]