include::./index.adoc[]

[[v12-4-0]]
=== 2 Reis, 4
// naa ?, NAA - Nova Almeida Atualizada

[[v12-4-1]]

^<<v12-4-1,1>>^ Certa mulher, viúva de um dos discípulos dos profetas, clamou a Eliseu, dizendo: — O meu marido, seu servo, está morto, e o senhor sabe que esse seu servo temia o Senhor  Deus. Mas veio o credor para levar os meus dois filhos como escravos.

[[v12-4-2]]

^<<v12-4-2,2>>^ Eliseu perguntou à mulher: — O que posso fazer por você? Diga-me o que é que você tem em casa. Ela respondeu: — Esta sua serva não tem nada em casa, a não ser um jarro de azeite.

[[v12-4-3]]

^<<v12-4-3,3>>^ Então Eliseu disse: — Vá, peça emprestadas vasilhas a todos os seus vizinhos; vasilhas vazias, muitas vasilhas.

[[v12-4-4]]

^<<v12-4-4,4>>^ Depois entre em casa, feche a porta atrás de você e dos seus filhos, e derrame o azeite em todas aquelas vasilhas. Ponha à parte as que forem ficando cheias.

[[v12-4-5]]

^<<v12-4-5,5>>^ A mulher foi embora dali e fechou a porta atrás de si e dos seus filhos. Estes lhe passavam as vasilhas, e ela as enchia.

[[v12-4-6]]

^<<v12-4-6,6>>^ Quando todas estavam cheias, ela disse a um dos filhos: — Traga-me mais uma vasilha. Mas ele respondeu: — Não há mais vasilha nenhuma. E o azeite parou.

[[v12-4-7]]

^<<v12-4-7,7>>^ Então ela foi e contou ao homem de Deus. Ele disse: — Vá, venda o azeite e pague a sua dívida; e você e os seus filhos vivam do que sobrar.

[[v12-4-8]]

^<<v12-4-8,8>>^ Certo dia, Eliseu passou por Suném, onde morava uma mulher rica, que insistiu para que ele ficasse para uma refeição. Assim, todas as vezes que passava por lá, entrava para fazer uma refeição.

[[v12-4-9]]

^<<v12-4-9,9>>^ Ela disse ao seu marido: — Vejo que este que passa sempre por aqui é um santo homem de Deus.

[[v12-4-10]]

^<<v12-4-10,10>>^ Vamos fazer um quarto pequeno no terraço da casa e colocar nele uma cama, uma mesa, uma cadeira e uma lamparina; assim, quando ele vier à nossa casa, poderá ficar ali.

[[v12-4-11]]

^<<v12-4-11,11>>^ Um dia, vindo o profeta para ali, retirou-se para o quarto e se deitou.

[[v12-4-12]]

^<<v12-4-12,12>>^ Então disse ao seu servo Geazi: — Vá chamar esta sunamita. Ele a chamou, e ela se pôs diante do profeta.

[[v12-4-13]]

^<<v12-4-13,13>>^ Este tinha dito a Geazi que dissesse a ela: — A senhora nos tem tratado com muito cuidado. O que podemos fazer pela senhora? Podemos falar em seu favor junto ao rei ou ao comandante do exército? Ela havia respondido: — Eu estou bem, vivendo no meio do meu povo.

[[v12-4-14]]

^<<v12-4-14,14>>^ Então o profeta perguntou a Geazi: — O que se pode fazer por ela? Geazi respondeu: — Ora, ela não tem filhos, e o marido dela é velho.

[[v12-4-15]]

^<<v12-4-15,15>>^ Eliseu disse: — Vá chamá-la. Ele a chamou, e ela se pôs à porta.

[[v12-4-16]]

^<<v12-4-16,16>>^ Então o profeta disse à mulher: — Por este tempo, daqui a um ano, você terá um filho nos braços. Ela disse: — Não, meu senhor, homem de Deus, não minta para esta sua serva.

[[v12-4-17]]

^<<v12-4-17,17>>^ A mulher engravidou e, no ano seguinte, no tempo determinado, deu à luz um filho, como Eliseu tinha dito.

[[v12-4-18]]

^<<v12-4-18,18>>^ O menino cresceu e, certo dia, foi encontrar-se com o seu pai, que estava no campo com os ceifeiros.

[[v12-4-19]]

^<<v12-4-19,19>>^ De repente ele disse a seu pai: — Ai! A minha cabeça! A minha cabeça! Então o pai disse a um dos servos: — Leve-o para a mãe.

[[v12-4-20]]

^<<v12-4-20,20>>^ Ele o tomou e o levou para a mãe. O menino ficou sentado no colo dela até o meio-dia, e então morreu.

[[v12-4-21]]

^<<v12-4-21,21>>^ Ela subiu e o deitou sobre a cama do homem de Deus; fechou a porta e saiu.

[[v12-4-22]]

^<<v12-4-22,22>>^ Chamou o marido e lhe disse: — Mande-me um dos servos e uma das jumentas. Preciso ir depressa falar com o homem de Deus e voltar.

[[v12-4-23]]

^<<v12-4-23,23>>^ O marido perguntou: — Por que você quer falar com ele hoje? Não é dia de Festa da Lua Nova nem sábado. Ela respondeu: — Não faz mal.

[[v12-4-24]]

^<<v12-4-24,24>>^ Então ela mandou preparar a jumenta e disse ao servo: — Pegue as rédeas e vamos! Não diminua a marcha, a não ser quando eu disser.

[[v12-4-25]]

^<<v12-4-25,25>>^ E assim ela partiu e foi falar com o homem de Deus, no monte Carmelo. Ao vê-la de longe, o homem de Deus disse a Geazi, seu servo: — Veja! É a sunamita.

[[v12-4-26]]

^<<v12-4-26,26>>^ Corra ao seu encontro e pergunte a ela: "Vai tudo bem com você, com o seu marido, com o menino?" Ela respondeu: — Vai tudo bem.

[[v12-4-27]]

^<<v12-4-27,27>>^ Quando ela chegou ao homem de Deus, no monte, agarrou-se aos pés dele. Geazi se aproximou para arrancá-la, mas o homem de Deus lhe disse: — Deixe-a, porque a sua alma está em amargura, e o Senhor  escondeu isso de mim; não me revelou nada a respeito.

[[v12-4-28]]

^<<v12-4-28,28>>^ Então a mulher disse: — Por acaso eu pedi a meu senhor algum filho? Eu não lhe disse que não me enganasse?

[[v12-4-29]]

^<<v12-4-29,29>>^ Então o profeta disse a Geazi: — Cinja os lombos, pegue o meu bordão e vá. Se encontrar alguém, não o cumprimente; e, se alguém cumprimentar você, não responda. Ponha o meu bordão sobre o rosto do menino.

[[v12-4-30]]

^<<v12-4-30,30>>^ Porém a mãe do menino disse: — Tão certo como vive o Senhor , e como você vive, não o deixarei. Então Eliseu se levantou e foi com ela.

[[v12-4-31]]

^<<v12-4-31,31>>^ Geazi foi adiante deles e pôs o bordão sobre o rosto do menino. Porém não houve nele voz nem sinal de vida. Então voltou para encontrar-se com Eliseu e lhe disse: — O menino não acordou.

[[v12-4-32]]

^<<v12-4-32,32>>^ Quando o profeta chegou à casa, eis que o menino estava morto sobre a cama.

[[v12-4-33]]

^<<v12-4-33,33>>^ Então ele entrou, fechou a porta e orou ao Senhor .

[[v12-4-34]]

^<<v12-4-34,34>>^ Subiu à cama, deitou-se sobre o menino e, pondo a sua boca sobre a boca dele, os seus olhos sobre os olhos dele e as suas mãos sobre as mãos dele, se estendeu sobre ele; e o corpo do menino aqueceu.

[[v12-4-35]]

^<<v12-4-35,35>>^ Eliseu se levantou e andou no quarto de um lado para outro. Tornou a subir à cama, e se estendeu sobre o menino; este espirrou sete vezes e abriu os olhos.

[[v12-4-36]]

^<<v12-4-36,36>>^ Então Eliseu chamou Geazi e disse: — Chame a sunamita. Ele a chamou. Quando ela chegou, Eliseu disse: — Pegue o seu filho.

[[v12-4-37]]

^<<v12-4-37,37>>^ Ela entrou, lançou-se aos pés de Eliseu e prostrou-se em terra; pegou o seu filho e saiu.

[[v12-4-38]]

^<<v12-4-38,38>>^ Eliseu voltou para Gilgal. Havia fome naquela terra. Quando os discípulos dos profetas estavam sentados diante dele, Eliseu disse ao seu servo: — Ponha a panela grande no fogo e faça um cozido para os discípulos dos profetas.

[[v12-4-39]]

^<<v12-4-39,39>>^ Então um deles saiu para o campo a fim de apanhar ervas. Ele achou uma trepadeira silvestre e, colhendo os frutos, encheu a sua capa com eles. Voltou para casa, cortou os frutos em pedaços e os pôs na panela, mesmo sem saber o que eram.

[[v12-4-40]]

^<<v12-4-40,40>>^ Depois, deram de comer aos homens. Enquanto comiam do cozido, gritaram: — Morte na panela, ó homem de Deus! E não puderam comer.

[[v12-4-41]]

^<<v12-4-41,41>>^ Mas Eliseu disse: — Tragam farinha. Ele a colocou na panela e disse: — Sirva às pessoas para que comam. E já não havia mal nenhum na panela.

[[v12-4-42]]

^<<v12-4-42,42>>^ Um homem veio de Baal-Salisa e trouxe ao homem de Deus pães das primícias, vinte pães de cevada, e espigas verdes numa sacola. Eliseu disse: — Dê às pessoas para que comam.

[[v12-4-43]]

^<<v12-4-43,43>>^ Porém o seu servo lhe disse: — Como vou pôr isto diante de cem homens? Eliseu tornou a dizer: — Dê às pessoas para que comam. Porque assim diz o Senhor : "Comerão, e ainda vai sobrar."

[[v12-4-44]]

^<<v12-4-44,44>>^ Então o servo pôs a comida diante deles; comeram, e ainda sobrou, conforme a palavra do Senhor .

'''

xref:012-2-reis/012-2-reis-003.adoc#v12-3-0[&#60; Capítulo Anterior] | <<v12-4-0,Topo>> | xref:012-2-reis/012-2-reis-005.adoc#v12-5-0[Próximo Capítulo &#62;]