include::./index.adoc[]

[[v12-16-0]]
=== 2 Reis, 16
// naa ?, NAA - Nova Almeida Atualizada

[[v12-16-1]]

^<<v12-16-1,1>>^ No décimo sétimo ano do reinado de Peca, filho de Remalias, Acaz, filho de Jotão, rei de Judá, começou a reinar.

[[v12-16-2]]

^<<v12-16-2,2>>^ Acaz tinha vinte anos de idade quando começou a reinar e reinou dezesseis anos em Jerusalém. Não fez o que era reto aos olhos do Senhor , seu Deus, ao contrário de Davi, seu pai.

[[v12-16-3]]

^<<v12-16-3,3>>^ Andou no caminho dos reis de Israel e até queimou o seu filho como sacrifício, segundo as abominações dos gentios, que o Senhor  havia expulsado de diante dos filhos de Israel.

[[v12-16-4]]

^<<v12-16-4,4>>^ Também sacrificou e queimou incenso nos lugares altos, nas colinas e debaixo de toda árvore frondosa.

[[v12-16-5]]

^<<v12-16-5,5>>^ Então Rezim, rei da Síria, e Peca, filho de Remalias, rei de Israel, subiram a Jerusalém para lutar contra ela. Cercaram Acaz, mas não conseguiram derrotá-lo.

[[v12-16-6]]

^<<v12-16-6,6>>^ Naquele tempo, Rezim, rei da Síria, restituiu Elate à Síria e expulsou dela os homens de Judá. Os sírios foram para Elate e ficaram morando ali até o dia de hoje.

[[v12-16-7]]

^<<v12-16-7,7>>^ Acaz enviou mensageiros a Tiglate-Pileser, rei da Assíria, dizendo: — Eu sou seu servo e seu filho. Venha me livrar do poder do rei da Síria e do poder do rei de Israel, que se levantam contra mim.

[[v12-16-8]]

^<<v12-16-8,8>>^ Acaz pegou a prata e o ouro que havia na Casa do Senhor  e nos tesouros do palácio real e mandou de presente ao rei da Assíria.

[[v12-16-9]]

^<<v12-16-9,9>>^ O rei da Assíria lhe deu ouvidos, subiu contra Damasco, tomou-a, levou o povo para Quir e matou Rezim.

[[v12-16-10]]

^<<v12-16-10,10>>^ Então o rei Acaz foi a Damasco para se encontrar com Tiglate-Pileser, rei da Assíria. Ao ver ali um altar, enviou ao sacerdote Urias o modelo do altar e a planta segundo a qual tinha sido feito.

[[v12-16-11]]

^<<v12-16-11,11>>^ Urias, o sacerdote, edificou um altar segundo tudo o que o rei Acaz havia ordenado de Damasco; o sacerdote Urias fez isso antes que o rei Acaz viesse de Damasco.

[[v12-16-12]]

^<<v12-16-12,12>>^ Quando o rei voltou de Damasco, viu o altar, aproximou-se dele e nele sacrificou.

[[v12-16-13]]

^<<v12-16-13,13>>^ Queimou o seu holocausto e a sua oferta de cereais, derramou a sua libação e aspergiu o sangue das suas ofertas pacíficas naquele altar.

[[v12-16-14]]

^<<v12-16-14,14>>^ O altar de bronze, que estava diante do Senhor , ele o tirou da frente do templo, do lugar entre o altar dele e a Casa do Senhor , e o pôs ao lado do seu altar, do lado norte.

[[v12-16-15]]

^<<v12-16-15,15>>^ O rei Acaz também ordenou ao sacerdote Urias, dizendo: — Use este altar grande para o holocausto da manhã, para a oferta de cereais da tarde, para o holocausto do rei e a sua oferta de cereais, e para o holocausto de todo o povo da terra, a sua oferta de cereais e as suas libações. Todo o sangue dos holocaustos e todo o sangue dos sacrifícios você deve aspergir nele. Mas o altar de bronze ficará para a minha deliberação posterior.

[[v12-16-16]]

^<<v12-16-16,16>>^ E o sacerdote Urias fez tudo como o rei Acaz lhe havia ordenado.

[[v12-16-17]]

^<<v12-16-17,17>>^ O rei Acaz cortou os painéis dos suportes e tirou as pias que estavam em cima deles. Pegou também o mar de fundição e o tirou de sobre os touros de bronze, que estavam debaixo dele, e o pôs sobre um pavimento de pedra.

[[v12-16-18]]

^<<v12-16-18,18>>^ Também, por causa do rei da Assíria, retirou da Casa do Senhor  a estrutura coberta para uso no sábado, que tinha sido construída no templo, e a entrada real pelo lado de fora.

[[v12-16-19]]

^<<v12-16-19,19>>^ Quanto aos demais atos de Acaz e ao que fez, não está tudo escrito no Livro da História dos Reis de Judá?

[[v12-16-20]]

^<<v12-16-20,20>>^ Acaz morreu e foi sepultado junto a seus pais, na Cidade de Davi; e Ezequias, seu filho, reinou em seu lugar.

'''

xref:012-2-reis/012-2-reis-015.adoc#v12-15-0[&#60; Capítulo Anterior] | <<v12-16-0,Topo>> | xref:012-2-reis/012-2-reis-017.adoc#v12-17-0[Próximo Capítulo &#62;]