include::./index.adoc[]

[[v12-20-0]]
=== 2 Reis, 20
// naa ?, NAA - Nova Almeida Atualizada

[[v12-20-1]]

^<<v12-20-1,1>>^ Por esse tempo, Ezequias adoeceu de uma enfermidade mortal. O profeta Isaías, filho de Amoz, foi visitá-lo e lhe disse: — Assim diz o Senhor : "Ponha em ordem a sua casa, porque você morrerá; você não vai escapar."

[[v12-20-2]]

^<<v12-20-2,2>>^ Então Ezequias virou o rosto para a parede e orou ao Senhor , dizendo:

[[v12-20-3]]

^<<v12-20-3,3>>^ — Ó Senhor , lembra-te de que andei diante de ti com fidelidade, com coração íntegro, e fiz o que era reto aos teus olhos. E Ezequias chorou amargamente.

[[v12-20-4]]

^<<v12-20-4,4>>^ Antes que Isaías tivesse saído do pátio central, a palavra do Senhor  veio a ele, dizendo:

[[v12-20-5]]

^<<v12-20-5,5>>^ — Volte e diga a Ezequias, príncipe do meu povo: Assim diz o Senhor , o Deus de Davi, seu pai: "Ouvi a sua oração e vi as suas lágrimas. Eis que eu vou curá-lo e, ao terceiro dia, você subirá à Casa do Senhor .

[[v12-20-6]]

^<<v12-20-6,6>>^ Acrescentarei quinze anos à sua vida e livrarei das mãos do rei da Assíria tanto você quanto esta cidade. Defenderei esta cidade por amor de mim e por amor a Davi, meu servo."

[[v12-20-7]]

^<<v12-20-7,7>>^ Isaías disse mais: — Peguem uma pasta de figos. Eles a pegaram e a puseram sobre a úlcera. E Ezequias recuperou a saúde.

[[v12-20-8]]

^<<v12-20-8,8>>^ Ezequias perguntou a Isaías: — Qual será o sinal de que o Senhor  me curará e de que, ao terceiro dia, subirei à Casa do Senhor ?

[[v12-20-9]]

^<<v12-20-9,9>>^ Isaías respondeu: — Este é o sinal que você receberá do Senhor  para indicar que ele cumprirá o que prometeu: você quer que a sombra se adiante dez graus ou que retroceda dez graus?

[[v12-20-10]]

^<<v12-20-10,10>>^ Ezequias respondeu: — É fácil a sombra adiantar dez graus. Mas que não seja assim; pelo contrário, que ela retroceda dez graus.

[[v12-20-11]]

^<<v12-20-11,11>>^ Então o profeta Isaías clamou ao Senhor  e ele fez retroceder dez graus a sombra lançada pelo sol declinante no relógio de Acaz.

[[v12-20-12]]

^<<v12-20-12,12>>^ Nesse tempo, Merodaque-Baladã, filho de Baladã, rei da Babilônia, enviou cartas e um presente a Ezequias, porque soube que ele havia estado doente.

[[v12-20-13]]

^<<v12-20-13,13>>^ Ezequias recebeu bem os mensageiros e lhes mostrou toda a casa do seu tesouro, a prata, o ouro, as especiarias, os óleos finos, o seu arsenal e tudo o que havia nos seus tesouros. Não houve nada em seu palácio nem em todo o seu domínio que Ezequias não lhes mostrasse.

[[v12-20-14]]

^<<v12-20-14,14>>^ Então o profeta Isaías foi falar com o rei Ezequias e lhe disse: — Que foi que aqueles homens disseram e de onde vieram? Ezequias respondeu: — Vieram de uma terra distante, da Babilônia.

[[v12-20-15]]

^<<v12-20-15,15>>^ Isaías perguntou: — O que eles viram no seu palácio? Ezequias respondeu: — Viram tudo o que há em meu palácio. Não houve nada nos meus tesouros que eu não lhes mostrasse.

[[v12-20-16]]

^<<v12-20-16,16>>^ Então Isaías disse a Ezequias: — Ouça a palavra do Senhor :

[[v12-20-17]]

^<<v12-20-17,17>>^ "Eis que virão dias em que tudo o que houver no seu palácio, isto é, tudo o que os seus pais ajuntaram até o dia de hoje, será levado para a Babilônia; não ficará coisa alguma, diz o Senhor .

[[v12-20-18]]

^<<v12-20-18,18>>^ Alguns dos seus próprios filhos, gerados por você, serão levados, para que sejam eunucos no palácio do rei da Babilônia."

[[v12-20-19]]

^<<v12-20-19,19>>^ Então Ezequias disse a Isaías: — Boa é a palavra do Senhor  que você falou. Pois ele pensava assim: "Enquanto eu viver haverá paz e segurança."

[[v12-20-20]]

^<<v12-20-20,20>>^ Quanto aos demais atos de Ezequias, a todo o seu poder, como fez o tanque e o aqueduto e trouxe água para dentro da cidade, não está tudo escrito no Livro da História dos Reis de Judá?

[[v12-20-21]]

^<<v12-20-21,21>>^ Ezequias morreu, e Manassés, seu filho, reinou em seu lugar.

'''

xref:012-2-reis/012-2-reis-019.adoc#v12-19-0[&#60; Capítulo Anterior] | <<v12-20-0,Topo>> | xref:012-2-reis/012-2-reis-021.adoc#v12-21-0[Próximo Capítulo &#62;]