include::./index.adoc[]

[[v12-11-0]]
=== 2 Reis, 11
// naa ?, NAA - Nova Almeida Atualizada

[[v12-11-1]]

^<<v12-11-1,1>>^ Quando Atalia, mãe de Acazias, viu que seu filho era morto, levantou-se e destruiu toda a descendência real.

[[v12-11-2]]

^<<v12-11-2,2>>^ Mas Jeoseba, filha do rei Jorão e irmã de Acazias, raptou Joás, filho de Acazias, do meio dos filhos do rei que seriam mortos e o pôs, juntamente com a sua babá, numa câmara interior; e, assim, o esconderam de Atalia, e ele não foi morto.

[[v12-11-3]]

^<<v12-11-3,3>>^ Joás esteve com ela, escondido na Casa do Senhor , durante seis anos; e Atalia reinava no país.

[[v12-11-4]]

^<<v12-11-4,4>>^ No sétimo ano, Joiada mandou chamar os capitães dos cários e da guarda e reuniu-se com eles na Casa do Senhor . Fez uma aliança com eles, pedindo que jurassem na Casa do Senhor . Então lhes mostrou o filho do rei

[[v12-11-5]]

^<<v12-11-5,5>>^ e lhes deu ordem, dizendo: — Isto é o que vocês devem fazer: uma terça parte de vocês, que entram de serviço no sábado, fará a guarda do palácio real;

[[v12-11-6]]

^<<v12-11-6,6>>^ outra terça parte estará ao portão Sur; e a outra terça parte, ao portão detrás da guarda; assim, vocês farão a guarda e a defesa deste palácio.

[[v12-11-7]]

^<<v12-11-7,7>>^ Os dois grupos que saem de serviço no sábado, estes todos farão a guarda da Casa do Senhor , junto ao rei.

[[v12-11-8]]

^<<v12-11-8,8>>^ Vocês devem rodear o rei, cada um de armas na mão. E, se alguém quiser entrar nas fileiras, que seja morto. Vocês devem acompanhar o rei aonde quer que ele for.

[[v12-11-9]]

^<<v12-11-9,9>>^ Os capitães de cem fizeram tudo o que o sacerdote Joiada lhes havia ordenado. Cada um reuniu os seus soldados, tanto os que entravam de serviço no sábado como os que saíam de serviço no sábado, e os levou ao sacerdote Joiada.

[[v12-11-10]]

^<<v12-11-10,10>>^ O sacerdote entregou aos capitães de cem as lanças e os escudos que haviam sido do rei Davi e que estavam na Casa do Senhor .

[[v12-11-11]]

^<<v12-11-11,11>>^ Os guardas se puseram, cada um de armas na mão, desde o lado direito da casa real até o seu lado esquerdo, e até o altar, e até o templo, para rodear o rei.

[[v12-11-12]]

^<<v12-11-12,12>>^ Então Joiada trouxe para fora Joás, o filho do rei, pôs a coroa na cabeça dele e lhe entregou o Livro do Testemunho. Eles o constituíram rei, o ungiram, bateram palmas e gritaram: — Viva o rei!

[[v12-11-13]]

^<<v12-11-13,13>>^ Quando Atalia ouviu o barulho dos guardas e do povo, veio para onde o povo estava, na Casa do Senhor .

[[v12-11-14]]

^<<v12-11-14,14>>^ Olhou, e eis que o rei estava junto à coluna, segundo o costume. Os capitães e os tocadores de trombetas estavam ao lado do rei, e todo o povo da terra se alegrava e tocava trombetas. Então Atalia rasgou as suas roupas e gritou: — Traição! Traição!

[[v12-11-15]]

^<<v12-11-15,15>>^ Porém o sacerdote Joiada deu ordem aos capitães que comandavam as tropas, dizendo: — Façam-na sair por entre as fileiras e, se alguém a seguir, matem-no à espada. Porque o sacerdote tinha dito: "Não a matem na Casa do Senhor ."

[[v12-11-16]]

^<<v12-11-16,16>>^ Então eles a prenderam; e ela, pelo caminho da entrada dos cavalos, foi para o palácio real, onde a mataram.

[[v12-11-17]]

^<<v12-11-17,17>>^ Joiada fez uma aliança entre o Senhor , o rei e o povo, para serem eles o povo do Senhor . Fez também uma aliança entre o rei e o povo.

[[v12-11-18]]

^<<v12-11-18,18>>^ Então todo o povo da terra entrou no templo de Baal e o derrubaram, despedaçando os altares e as imagens de Baal. Matã, o sacerdote de Baal, foi morto diante dos altares. O sacerdote Joiada pôs guardas sobre a Casa do Senhor .

[[v12-11-19]]

^<<v12-11-19,19>>^ Reuniu os capitães dos cários, os da guarda e todo o povo da terra, e todos estes conduziram o rei desde a Casa do Senhor  até o palácio real, passando pelo portão da guarda. E Joás sentou-se no trono dos reis.

[[v12-11-20]]

^<<v12-11-20,20>>^ Todo o povo da terra se alegrou, e a cidade ficou tranquila, depois que mataram Atalia à espada, junto ao palácio real.

[[v12-11-21]]

^<<v12-11-21,21>>^ Joás tinha sete anos de idade quando o fizeram rei.

'''

xref:012-2-reis/012-2-reis-010.adoc#v12-10-0[&#60; Capítulo Anterior] | <<v12-11-0,Topo>> | xref:012-2-reis/012-2-reis-012.adoc#v12-12-0[Próximo Capítulo &#62;]