include::./index.adoc[]

[[v12-21-0]]
=== 2 Reis, 21
// naa ?, NAA - Nova Almeida Atualizada

[[v12-21-1]]

^<<v12-21-1,1>>^ Manassés tinha doze anos de idade quando começou a reinar e reinou cinquenta e cinco anos em Jerusalém. A mãe dele se chamava Hefzibá.

[[v12-21-2]]

^<<v12-21-2,2>>^ Fez o que era mau aos olhos do Senhor , segundo as coisas abomináveis das nações que o Senhor  havia expulsado de diante dos filhos de Israel.

[[v12-21-3]]

^<<v12-21-3,3>>^ Pois reconstruiu os lugares altos que Ezequias, seu pai, havia destruído, levantou altares a Baal, fez um poste da deusa Aserá como o que Acabe, rei de Israel, havia feito, prostrou-se diante de todo o exército dos céus e o serviu.

[[v12-21-4]]

^<<v12-21-4,4>>^ Edificou altares na Casa do Senhor , a respeito da qual o Senhor  tinha dito: "Em Jerusalém porei o meu nome."

[[v12-21-5]]

^<<v12-21-5,5>>^ Também edificou altares a todo o exército dos céus nos dois átrios da Casa do Senhor .

[[v12-21-6]]

^<<v12-21-6,6>>^ E queimou o seu filho em sacrifício, adivinhava pelas nuvens, era agoureiro e tratava com médiuns e feiticeiros. Fazia continuamente o que era mau aos olhos do Senhor , para o provocar à ira.

[[v12-21-7]]

^<<v12-21-7,7>>^ Também pegou a imagem de escultura da deusa Aserá que ele tinha feito e a colocou no templo a respeito do qual o Senhor  tinha dito a Davi e a seu filho Salomão: "Neste templo e em Jerusalém, que escolhi de todas as tribos de Israel, porei o meu nome para sempre.

[[v12-21-8]]

^<<v12-21-8,8>>^ E não farei com que os pés de Israel andem errantes, longe da terra que dei aos seus pais, desde que eles tenham o cuidado de fazer segundo tudo o que lhes tenho mandado e conforme toda a Lei que Moisés, meu servo, lhes ordenou."

[[v12-21-9]]

^<<v12-21-9,9>>^ Eles, porém, não ouviram. Manassés de tal modo os levou a andar errantes, que fizeram pior do que as nações que o Senhor  tinha destruído de diante dos filhos de Israel.

[[v12-21-10]]

^<<v12-21-10,10>>^ Então o Senhor  falou por meio de seus servos, os profetas, dizendo:

[[v12-21-11]]

^<<v12-21-11,11>>^ — Visto que Manassés, rei de Judá, cometeu estas abominações, fazendo pior do que tudo o que os amorreus fizeram antes dele, e também levou Judá a pecar com os ídolos dele,

[[v12-21-12]]

^<<v12-21-12,12>>^ assim diz o Senhor , Deus de Israel: Eis que trarei uma desgraça tão grande sobre Jerusalém e Judá, que todo aquele que ouvir a respeito dela ficará com os dois ouvidos tinindo.

[[v12-21-13]]

^<<v12-21-13,13>>^ Estenderei sobre Jerusalém o cordel de Samaria e o prumo da casa de Acabe. Eliminarei Jerusalém, como quem elimina a sujeira de um prato, limpando e virando-o de boca para baixo.

[[v12-21-14]]

^<<v12-21-14,14>>^ Abandonarei o remanescente da minha herança e o entregarei nas mãos de seus inimigos; servirá de presa e despojo para todos os seus inimigos.

[[v12-21-15]]

^<<v12-21-15,15>>^ Porque fizeram o que era mau aos meus olhos e me provocaram à ira, desde o dia em que os pais deles saíram do Egito até o dia de hoje.

[[v12-21-16]]

^<<v12-21-16,16>>^ Além disso, Manassés derramou muitíssimo sangue inocente, até encher Jerusalém de um extremo ao outro, sem falar do seu pecado, com que levou Judá a pecar, praticando o que era mau aos olhos do Senhor .

[[v12-21-17]]

^<<v12-21-17,17>>^ Quanto aos demais atos de Manassés, a tudo o que fez e ao seu pecado, que cometeu, não está tudo escrito no Livro da História dos Reis de Judá?

[[v12-21-18]]

^<<v12-21-18,18>>^ Manassés morreu e foi sepultado no jardim da sua própria casa, no jardim de Uzá. E Amom, seu filho, reinou em seu lugar.

[[v12-21-19]]

^<<v12-21-19,19>>^ Amom tinha vinte e dois anos de idade quando começou a reinar e reinou dois anos em Jerusalém. A mãe dele se chamava Mesulemete e era filha de Haruz, de Jotbá.

[[v12-21-20]]

^<<v12-21-20,20>>^ Amom fez o que era mau aos olhos do Senhor , como Manassés, seu pai, havia feito.

[[v12-21-21]]

^<<v12-21-21,21>>^ Andou em todo o caminho em que o pai dele tinha andado, serviu os ídolos a que o pai dele havia servido e os adorou.

[[v12-21-22]]

^<<v12-21-22,22>>^ Assim, ele abandonou o Senhor , Deus de seus pais, e não andou no caminho do Senhor .

[[v12-21-23]]

^<<v12-21-23,23>>^ Os servos do rei Amom conspiraram contra ele e o mataram em sua própria casa.

[[v12-21-24]]

^<<v12-21-24,24>>^ Porém o povo daquela terra matou todos os que conspiraram contra o rei Amom e proclamou Josias, filho de Amom, rei em seu lugar.

[[v12-21-25]]

^<<v12-21-25,25>>^ Quanto aos demais atos de Amom e a tudo o que fez, não está tudo escrito no Livro da História dos Reis de Judá?

[[v12-21-26]]

^<<v12-21-26,26>>^ Amom foi sepultado em seu túmulo, no jardim de Uzá. E Josias, seu filho, reinou em seu lugar.

'''

xref:012-2-reis/012-2-reis-020.adoc#v12-20-0[&#60; Capítulo Anterior] | <<v12-21-0,Topo>> | xref:012-2-reis/012-2-reis-022.adoc#v12-22-0[Próximo Capítulo &#62;]