include::./index.adoc[]

[[v12-3-0]]
=== 2 Reis, 3
// naa ?, NAA - Nova Almeida Atualizada

[[v12-3-1]]

^<<v12-3-1,1>>^ Jorão, filho de Acabe, começou a reinar sobre Israel, em Samaria, no décimo oitavo ano do reinado de Josafá, rei de Judá; e reinou doze anos.

[[v12-3-2]]

^<<v12-3-2,2>>^ Fez o que era mau aos olhos do Senhor , porém não como o seu pai, nem como a sua mãe, porque tirou a coluna de Baal, que o seu pai havia feito.

[[v12-3-3]]

^<<v12-3-3,3>>^ No entanto, aderiu aos pecados de Jeroboão, filho de Nebate, que havia levado Israel a pecar, e não se afastou deles.

[[v12-3-4]]

^<<v12-3-4,4>>^ Mesa, rei dos moabitas, era criador de gado e pagava o seu tributo ao rei de Israel com cem mil cordeiros e a lã de cem mil carneiros.

[[v12-3-5]]

^<<v12-3-5,5>>^ Mas depois da morte de Acabe, o rei dos moabitas se revoltou contra o rei de Israel.

[[v12-3-6]]

^<<v12-3-6,6>>^ Por isso, naquele instante Jorão saiu de Samaria e reuniu todo o exército de Israel.

[[v12-3-7]]

^<<v12-3-7,7>>^ Mandou dizer a Josafá, rei de Judá: — O rei de Moabe se revoltou contra mim. Você irá comigo à guerra contra Moabe? Josafá respondeu: — Irei. Sou como você é, o meu povo é como o seu povo, e os meus cavalos são como os seus cavalos.

[[v12-3-8]]

^<<v12-3-8,8>>^ E Josafá perguntou: — Por que caminho iremos? Jorão respondeu: — Pelo caminho do deserto de Edom.

[[v12-3-9]]

^<<v12-3-9,9>>^ Partiram o rei de Israel, o rei de Judá e o rei de Edom. Após sete dias de marcha, não havia água para o exército e para os animais que os seguiam.

[[v12-3-10]]

^<<v12-3-10,10>>^ Então o rei de Israel disse: — Ah! O Senhor  chamou estes três reis para os entregar nas mãos de Moabe.

[[v12-3-11]]

^<<v12-3-11,11>>^ Josafá perguntou: — Não há, aqui, algum profeta do Senhor , para que consultemos o Senhor  por meio dele? Um dos servos do rei de Israel respondeu: — Aqui está Eliseu, filho de Safate, que era servo de Elias.

[[v12-3-12]]

^<<v12-3-12,12>>^ Josafá disse: — Está com ele a palavra do Senhor . Então o rei de Israel, Josafá e o rei de Edom foram falar com Eliseu.

[[v12-3-13]]

^<<v12-3-13,13>>^ Mas Eliseu disse ao rei de Israel: — Que tenho eu a ver com você? Vá falar com os profetas de seu pai e os profetas de sua mãe. Porém o rei de Israel lhe disse: — Não, porque o Senhor  Deus é quem chamou estes três reis para os entregar nas mãos de Moabe.

[[v12-3-14]]

^<<v12-3-14,14>>^ Eliseu disse: — Tão certo como vive o Senhor  dos Exércitos, em cuja presença estou, se eu não respeitasse a presença de Josafá, rei de Judá, não daria atenção nem olharia para você.

[[v12-3-15]]

^<<v12-3-15,15>>^ Agora me tragam um músico. Enquanto o músico tocava, o poder de Deus veio sobre Eliseu.

[[v12-3-16]]

^<<v12-3-16,16>>^ Este disse: — Assim diz o Senhor : "Façam, neste vale, covas e mais covas.

[[v12-3-17]]

^<<v12-3-17,17>>^ Porque assim diz o Senhor : Vocês não sentirão vento, nem verão chuva, mas este vale se encherá de água; e vocês beberão, bem como o seu gado e os seus animais."

[[v12-3-18]]

^<<v12-3-18,18>>^ Mas isto ainda é pouco aos olhos do Senhor . Ele também entregará Moabe nas suas mãos.

[[v12-3-19]]

^<<v12-3-19,19>>^ Vocês conquistarão todas as cidades fortificadas e todas as cidades principais. Cortarão todas as árvores frutíferas, taparão todas as fontes de água e danificarão com pedras todos os campos de cultivo.

[[v12-3-20]]

^<<v12-3-20,20>>^ E aconteceu que, no dia seguinte, na hora do sacrifício da manhã, eis que água vinha descendo dos lados de Edom; e a terra se encheu de água.

[[v12-3-21]]

^<<v12-3-21,21>>^ Quando todos os moabitas ouviram que os reis tinham vindo para lutar contra eles, convocaram todos os que estavam aptos para a guerra, desde o mais novo até o mais velho, e tomaram posição nas fronteiras.

[[v12-3-22]]

^<<v12-3-22,22>>^ Os moabitas se levantaram de madrugada e, quando o sol raiou sobre as águas, viram que as águas diante deles estavam vermelhas como sangue.

[[v12-3-23]]

^<<v12-3-23,23>>^ E disseram: — Isto é sangue! Certamente os reis se destruíram e se mataram um ao outro! Agora, moabitas, é hora de pegar os despojos!

[[v12-3-24]]

^<<v12-3-24,24>>^ Mas, quando eles chegaram ao arraial de Israel, os israelitas se levantaram e atacaram os moabitas, os quais fugiram deles. Os israelitas entraram na terra e também aí mataram os moabitas.

[[v12-3-25]]

^<<v12-3-25,25>>^ Arrasaram as cidades, e cada um lançou uma pedra em todos os campos de cultivo, e os entulharam. Taparam todas as fontes de águas e cortaram todas as árvores frutíferas. Só Quir-Haresete ficou com suas muralhas; mas os que atiravam com fundas a cercaram e atacaram.

[[v12-3-26]]

^<<v12-3-26,26>>^ Quando o rei de Moabe percebeu que estava perdendo a batalha, tomou consigo setecentos homens armados com espada para abrir caminho e chegar até o rei de Edom, porém não puderam.

[[v12-3-27]]

^<<v12-3-27,27>>^ Então pegou o seu filho primogênito, que havia de reinar em seu lugar, e o ofereceu em holocausto sobre a muralha. Houve grande ira contra Israel e, por isso, eles se retiraram dali e voltaram para a sua própria terra.

'''

xref:012-2-reis/012-2-reis-002.adoc#v12-2-0[&#60; Capítulo Anterior] | <<v12-3-0,Topo>> | xref:012-2-reis/012-2-reis-004.adoc#v12-4-0[Próximo Capítulo &#62;]