include::./index.adoc[]

[[v12-10-0]]
=== 2 Reis, 10
// naa ?, NAA - Nova Almeida Atualizada

[[v12-10-1]]

^<<v12-10-1,1>>^ Acabe tinha setenta filhos em Samaria. Jeú escreveu cartas e as enviou a Samaria, aos chefes da cidade, aos anciãos e aos tutores dos filhos de Acabe, dizendo:

[[v12-10-2]]

^<<v12-10-2,2>>^ — Logo que esta carta chegar até vocês — pois estão com vocês os filhos de seu senhor, o rei, bem como os carros de guerra, os cavalos, a cidade fortificada e as armas —,

[[v12-10-3]]

^<<v12-10-3,3>>^ escolham o melhor e mais capaz dos filhos de seu senhor, ponham-no sobre o trono de seu pai e lutem pela casa de seu senhor.

[[v12-10-4]]

^<<v12-10-4,4>>^ Porém eles temeram muitíssimo e disseram: — Dois reis não puderam resistir a ele; como poderemos nós fazê-lo?

[[v12-10-5]]

^<<v12-10-5,5>>^ Então o responsável pelo palácio, o responsável pela cidade, os anciãos e os tutores mandaram dizer a Jeú: — Somos os seus servos e faremos tudo o que o senhor nos ordenar. A ninguém constituiremos rei; faça o que achar melhor.

[[v12-10-6]]

^<<v12-10-6,6>>^ Então Jeú lhes escreveu outra carta, dizendo: "Se vocês estão do meu lado e querem obedecer-me, então peguem as cabeças dos filhos do rei, seu senhor, e amanhã a estas horas venham a mim a Jezreel." Ora, os filhos do rei, que eram setenta, estavam com os homens importantes da cidade, que os criavam.

[[v12-10-7]]

^<<v12-10-7,7>>^ Quando receberam a carta, tomaram os filhos do rei e os mataram, setenta homens, e puseram as cabeças deles em cestos, que enviaram a Jeú, em Jezreel.

[[v12-10-8]]

^<<v12-10-8,8>>^ Um mensageiro foi até Jeú e lhe disse: — Trouxeram as cabeças dos filhos do rei. Jeú disse: — Ponham as cabeças em dois montões à entrada do portão, até pela manhã.

[[v12-10-9]]

^<<v12-10-9,9>>^ Pela manhã, Jeú saiu, parou e disse a todo o povo: — Vocês não têm culpa. Eis que eu conspirei contra o meu senhor e o matei. Mas quem matou todos estes?

[[v12-10-10]]

^<<v12-10-10,10>>^ Portanto, saibam agora que, da palavra do Senhor , pronunciada contra a casa de Acabe, nada cairá em terra, porque o Senhor  fez o que falou por meio do seu servo Elias.

[[v12-10-11]]

^<<v12-10-11,11>>^ Então Jeú matou todos os que restavam da casa de Acabe em Jezreel, bem como todos os seus homens importantes, os seus conhecidos e os seus sacerdotes, até não sobrar nem sequer um deles.

[[v12-10-12]]

^<<v12-10-12,12>>^ Depois ele se levantou e partiu rumo a Samaria. No caminho, quando estava em Bete-Equede dos Pastores,

[[v12-10-13]]

^<<v12-10-13,13>>^ Jeú encontrou parentes de Acazias, rei de Judá, e perguntou: — Quem são vocês? Eles responderam: — Somos parentes de Acazias. Estamos indo saudar os filhos do rei e os filhos da rainha-mãe.

[[v12-10-14]]

^<<v12-10-14,14>>^ Então Jeú disse: — Prendam-nos vivos. Eles os prenderam e os mataram junto ao poço de Bete-Equede. Eram quarenta e dois homens, e nenhum deles escapou com vida.

[[v12-10-15]]

^<<v12-10-15,15>>^ Jeú saiu dali e encontrou Jonadabe, filho de Recabe, que vinha ao encontro dele. Jeú saudou-o e lhe perguntou: — Você tem o coração sincero para comigo, assim como o meu coração é sincero para com você? Jonadabe respondeu: — Tenho. Então Jeú disse: — Se é assim, me dê a sua mão. E Jonadabe deu-lhe a mão. Jeú o fez subir na sua carruagem

[[v12-10-16]]

^<<v12-10-16,16>>^ e lhe disse: — Venha comigo e você verá o meu zelo para com o Senhor . E, assim, Jeú o levou na sua carruagem.

[[v12-10-17]]

^<<v12-10-17,17>>^ Quando Jeú chegou a Samaria, matou todos os que restavam da casa de Acabe, até destruí-los, segundo a palavra que o Senhor  tinha anunciado a Elias.

[[v12-10-18]]

^<<v12-10-18,18>>^ Jeú reuniu todo o povo e disse: — Acabe serviu pouco a Baal; Jeú, porém, o servirá muito.

[[v12-10-19]]

^<<v12-10-19,19>>^ Por isso, tragam, agora, à minha presença todos os profetas de Baal, todos os seus adoradores e todos os seus sacerdotes. Que não falte nenhum, pois tenho um grande sacrifício a oferecer a Baal. Todo aquele que faltar será morto. Porém Jeú fazia isto com astúcia, para destruir os adoradores de Baal.

[[v12-10-20]]

^<<v12-10-20,20>>^ Depois Jeú disse: — Proclamem uma reunião solene em honra a Baal. E a proclamação foi feita.

[[v12-10-21]]

^<<v12-10-21,21>>^ Jeú enviou mensageiros por todo o Israel. Vieram todos os adoradores de Baal, e não ficou um só que não viesse. Entraram no templo de Baal, que se encheu de uma extremidade à outra.

[[v12-10-22]]

^<<v12-10-22,22>>^ Então Jeú disse ao encarregado das vestimentas: — Traga vestimentas para todos os adoradores de Baal. E ele trouxe vestimentas para eles.

[[v12-10-23]]

^<<v12-10-23,23>>^ Depois disso, Jeú entrou com Jonadabe, filho de Recabe, no templo de Baal e disse aos adoradores de Baal: — Olhem bem e assegurem-se de que não se encontra aqui entre vocês nenhum dos servos do Senhor , mas somente os adoradores de Baal.

[[v12-10-24]]

^<<v12-10-24,24>>^ E, quando eles entraram para oferecer sacrifícios e holocaustos, Jeú colocou do lado de fora oitenta homens e disse-lhes: — Se escapar algum dos homens que eu entregar nas mãos de vocês, aquele que o deixou escapar pagará por isso com a sua própria vida.

[[v12-10-25]]

^<<v12-10-25,25>>^ Logo que acabou de oferecer o holocausto, Jeú ordenou aos guardas e aos capitães: — Entrem e matem todos! Não deixem que nenhum escape! E eles os mataram a fio de espada. Os guardas e os capitães os lançaram fora. Depois entraram no mais interior do templo de Baal,

[[v12-10-26]]

^<<v12-10-26,26>>^ tiraram as colunas que estavam no templo de Baal e as queimaram.

[[v12-10-27]]

^<<v12-10-27,27>>^ Também destruíram a coluna de Baal e derrubaram o templo de Baal, transformando-o numa latrina, que existe até o dia de hoje.

[[v12-10-28]]

^<<v12-10-28,28>>^ Assim, Jeú acabou com o culto a Baal em Israel.

[[v12-10-29]]

^<<v12-10-29,29>>^ Mas Jeú não se afastou dos pecados de Jeroboão, filho de Nebate, que este levou Israel a cometer, a saber, dos bezerros de ouro que estavam em Betel e em Dã.

[[v12-10-30]]

^<<v12-10-30,30>>^ Por isso o Senhor  disse a Jeú: — Visto que você fez bem em realizar o que é reto aos meus olhos e fez com a casa de Acabe segundo tudo o que era do meu propósito, os seus filhos até a quarta geração se assentarão no trono de Israel.

[[v12-10-31]]

^<<v12-10-31,31>>^ Mas Jeú não teve cuidado de andar de todo o seu coração na Lei do Senhor , Deus de Israel, nem se afastou dos pecados que Jeroboão levou Israel a cometer.

[[v12-10-32]]

^<<v12-10-32,32>>^ Naqueles dias, o Senhor  começou a diminuir os limites de Israel. O rei Hazael conquistou todo o território

[[v12-10-33]]

^<<v12-10-33,33>>^ desde o Jordão para o nascente do sol, toda a terra de Gileade, os gaditas, os rubenitas e os manassitas, desde Aroer, que está junto ao vale de Arnom, a saber, Gileade e Basã.

[[v12-10-34]]

^<<v12-10-34,34>>^ Quanto aos demais atos de Jeú e a tudo o que fez, e a todo o seu poder, não está tudo escrito no Livro da História dos Reis de Israel?

[[v12-10-35]]

^<<v12-10-35,35>>^ Jeú morreu e foi sepultado em Samaria. E Jeoacaz, seu filho, reinou em seu lugar.

[[v12-10-36]]

^<<v12-10-36,36>>^ Jeú reinou sobre Israel em Samaria vinte e oito anos.

'''

xref:012-2-reis/012-2-reis-009.adoc#v12-9-0[&#60; Capítulo Anterior] | <<v12-10-0,Topo>> | xref:012-2-reis/012-2-reis-011.adoc#v12-11-0[Próximo Capítulo &#62;]