include::./index.adoc[]

[[v12-9-0]]
=== 2 Reis, 9
// naa ?, NAA - Nova Almeida Atualizada

[[v12-9-1]]

^<<v12-9-1,1>>^ Então o profeta Eliseu chamou um dos discípulos dos profetas e lhe disse: — Prepare-se, leve com você este vaso de azeite e vá até Ramote-Gileade.

[[v12-9-2]]

^<<v12-9-2,2>>^ Quando chegar lá, procure Jeú, filho de Josafá, filho de Ninsi. Entre no lugar onde ele estiver, peça que ele se levante do meio de seus companheiros e leve-o para uma câmara interior.

[[v12-9-3]]

^<<v12-9-3,3>>^ Pegue o vaso de azeite, derrame o azeite sobre a cabeça dele e diga: Assim diz o Senhor : "Eu o ungi para ser rei sobre Israel." Depois, abra a porta e fuja depressa.

[[v12-9-4]]

^<<v12-9-4,4>>^ O rapaz, o jovem profeta, foi até Ramote-Gileade.

[[v12-9-5]]

^<<v12-9-5,5>>^ Quando chegou lá, eis que os capitães do exército estavam reunidos. Ele disse: — Capitão, tenho uma mensagem para o senhor. Ao que Jeú perguntou: — Para qual de nós? O rapaz respondeu: — Para o senhor, capitão!

[[v12-9-6]]

^<<v12-9-6,6>>^ Então Jeú se levantou e entrou na casa. O jovem derramou o azeite sobre a cabeça de Jeú e lhe disse: — Assim diz o Senhor , Deus de Israel: "Eu o ungi para ser rei sobre o povo do Senhor , sobre Israel.

[[v12-9-7]]

^<<v12-9-7,7>>^ Você porá fim à casa de Acabe, seu senhor, para que eu vingue da mão de Jezabel o sangue de meus servos, os profetas, e o sangue de todos os servos do Senhor .

[[v12-9-8]]

^<<v12-9-8,8>>^ Toda a casa de Acabe perecerá. Eliminarei de Acabe todos do sexo masculino, quer escravo, quer livre, em Israel.

[[v12-9-9]]

^<<v12-9-9,9>>^ Porque farei com a casa de Acabe o mesmo que fiz com a casa de Jeroboão, filho de Nebate, e com a casa de Baasa, filho de Aías.

[[v12-9-10]]

^<<v12-9-10,10>>^ Os cães devorarão Jezabel no campo de Jezreel; não haverá quem a sepulte." Dito isto, abriu a porta e fugiu.

[[v12-9-11]]

^<<v12-9-11,11>>^ Jeú saiu e voltou para junto dos outros servos de seu senhor, que lhe perguntaram: — Está tudo bem? Por que esse louco veio falar com você? Ele respondeu: — Vocês conhecem esse homem e sabem as coisas que ele anda dizendo.

[[v12-9-12]]

^<<v12-9-12,12>>^ Mas eles disseram: — É mentira! Por favor, conte-nos o que ele disse. Então Jeú disse: — Assim e assim me falou, a saber: Assim diz o Senhor : "Eu o ungi para ser rei sobre Israel."

[[v12-9-13]]

^<<v12-9-13,13>>^ Então eles se apressaram e, tomando cada um o seu manto, os puseram debaixo dele, sobre os degraus, e tocaram a trombeta, e disseram: — Jeú é rei!

[[v12-9-14]]

^<<v12-9-14,14>>^ Assim, Jeú, filho de Josafá, filho de Ninsi, conspirou contra Jorão. Ora, Jorão tinha estado em Ramote-Gileade, ele e todo o Israel, para defendê-la de Hazael, rei da Síria.

[[v12-9-15]]

^<<v12-9-15,15>>^ Porém o rei Jorão voltou a Jezreel para se curar dos ferimentos que os sírios lhe haviam causado, quando lutou contra Hazael, rei da Síria. Jeú disse aos demais capitães do exército: — Se é da vontade de vocês, que ninguém saia escondido da cidade, para ir anunciar isto em Jezreel.

[[v12-9-16]]

^<<v12-9-16,16>>^ Então Jeú subiu num carro de guerra e foi para Jezreel, porque Jorão estava de cama ali. Também Acazias, rei de Judá, tinha ido visitar Jorão.

[[v12-9-17]]

^<<v12-9-17,17>>^ A sentinela que estava na torre de Jezreel viu a tropa de Jeú, que se aproximava, e disse: — Vejo uma tropa. Jorão disse: — Chame um cavaleiro e diga que vá ao encontro deles, para perguntar: "Vocês vêm em paz?"

[[v12-9-18]]

^<<v12-9-18,18>>^ O cavaleiro foi ao encontro de Jeú e disse: — Assim diz o rei: "Vocês vêm em paz?" Jeú respondeu: — O que você tem a ver com a paz? Passe para trás de mim. A sentinela deu aviso, dizendo: — O mensageiro chegou até eles, mas não está voltando.

[[v12-9-19]]

^<<v12-9-19,19>>^ Então o rei Jorão mandou outro cavaleiro. Quando ele chegou até eles, disse: — Assim diz o rei: "Vocês vêm em paz?" Jeú respondeu: — O que você tem a ver com a paz? Passe para trás de mim.

[[v12-9-20]]

^<<v12-9-20,20>>^ A sentinela deu aviso, dizendo: — Também este chegou até eles, mas não está voltando. E o guiar do carro parece como o de Jeú, filho de Ninsi, porque ele está guiando como um louco.

[[v12-9-21]]

^<<v12-9-21,21>>^ Jorão disse: — Preparem o meu carro de guerra! E eles o prepararam. Jorão, rei de Israel, saiu, e Acazias, rei de Judá, foi com ele, cada um em seu carro de guerra. Foram ao encontro de Jeú, e o acharam no campo de Nabote, o jezreelita.

[[v12-9-22]]

^<<v12-9-22,22>>^ Ao ver Jeú, o rei Jorão perguntou: — Jeú, você vem em paz? Ele respondeu: — Que paz, se ainda continuam as prostituições de sua mãe Jezabel e as suas muitas feitiçarias?

[[v12-9-23]]

^<<v12-9-23,23>>^ Então Jorão deu meia-volta e fugiu, gritando para Acazias: — É uma traição, Acazias!

[[v12-9-24]]

^<<v12-9-24,24>>^ Mas Jeú entesou o seu arco com toda a força e atingiu Jorão entre os ombros; a flecha atravessou o coração, e ele caiu morto no seu carro de guerra.

[[v12-9-25]]

^<<v12-9-25,25>>^ Então Jeú disse a Bidcar, seu capitão: — Levante-o e jogue-o no campo que era de Nabote, o jezreelita. Lembre-se de que, quando eu e você, juntos, vínhamos andando a cavalo atrás de Acabe, o pai de Jorão, o Senhor  Deus pronunciou contra ele esta sentença:

[[v12-9-26]]

^<<v12-9-26,26>>^ "Tão certo como vi ontem à tarde o sangue de Nabote e o sangue de seus filhos, diz o Senhor , assim neste campo eu darei a retribuição que você merece", diz o Senhor . Agora, pois, pegue-o e jogue-o neste campo, segundo a palavra do Senhor .

[[v12-9-27]]

^<<v12-9-27,27>>^ À vista disto, Acazias, rei de Judá, fugiu pelo caminho de Bete-Hagã. Mas Jeú o perseguiu e disse: — Matem também a este! E eles o atingiram dentro do carro de guerra, na subida de Gur, perto de Ibleão. Acazias fugiu para Megido, onde morreu.

[[v12-9-28]]

^<<v12-9-28,28>>^ Os servos dele o levaram, num carro, para Jerusalém e o sepultaram no seu túmulo junto a seus pais, na Cidade de Davi.

[[v12-9-29]]

^<<v12-9-29,29>>^ Acazias havia começado a reinar sobre Judá no décimo primeiro ano do reinado de Jorão, filho de Acabe.

[[v12-9-30]]

^<<v12-9-30,30>>^ Jeú chegou a Jezreel, e Jezabel ficou sabendo disso. Então ela se pintou em volta dos olhos, enfeitou a cabeça e olhou pela janela.

[[v12-9-31]]

^<<v12-9-31,31>>^ Quando Jeú entrou pelo portão do palácio, ela gritou: — Correu tudo bem com Zinri, o assassino do seu senhor?

[[v12-9-32]]

^<<v12-9-32,32>>^ Jeú ergueu o rosto, olhou para a janela e perguntou: — Quem está do meu lado? Quem? E dois ou três oficiais olharam para ele.

[[v12-9-33]]

^<<v12-9-33,33>>^ Então ele disse: — Joguem-na pela janela! E eles a jogaram. O sangue dela salpicou a parede e os cavalos, e Jeú a atropelou.

[[v12-9-34]]

^<<v12-9-34,34>>^ Jeú entrou no palácio, comeu e bebeu. Depois disse: — Tomem conta daquela maldita e sepultem o corpo, porque ela é filha de rei.

[[v12-9-35]]

^<<v12-9-35,35>>^ Mas os que foram sepultá-la não acharam dela nada mais do que a caveira, os pés e as palmas das mãos.

[[v12-9-36]]

^<<v12-9-36,36>>^ Então voltaram e contaram isso a Jeú. Ele disse: — Esta é a palavra do Senhor , que ele falou por meio de Elias, o tesbita, seu servo, dizendo: "No campo de Jezreel, os cães comerão a carne de Jezabel.

[[v12-9-37]]

^<<v12-9-37,37>>^ O cadáver de Jezabel será como esterco sobre a terra no campo de Jezreel, de maneira que ninguém poderá dizer: ‘Esta é Jezabel.’"

'''

xref:012-2-reis/012-2-reis-008.adoc#v12-8-0[&#60; Capítulo Anterior] | <<v12-9-0,Topo>> | xref:012-2-reis/012-2-reis-010.adoc#v12-10-0[Próximo Capítulo &#62;]