include::./index.adoc[]

[[v12-6-0]]
=== 2 Reis, 6
// naa ?, NAA - Nova Almeida Atualizada

[[v12-6-1]]

^<<v12-6-1,1>>^ Os discípulos dos profetas disseram a Eliseu: — Eis que o lugar em que moramos com você é pequeno demais para nós.

[[v12-6-2]]

^<<v12-6-2,2>>^ Vamos até o Jordão, tomemos de lá cada um de nós uma viga e construamos um lugar para morar. Ele respondeu: — Vão.

[[v12-6-3]]

^<<v12-6-3,3>>^ Mas um deles disse: — Tenha a bondade de ir com estes seus servos. Eliseu disse: — Eu irei.

[[v12-6-4]]

^<<v12-6-4,4>>^ E foi com eles. Quando chegaram ao Jordão, cortaram madeira.

[[v12-6-5]]

^<<v12-6-5,5>>^ Aconteceu que, enquanto um deles derrubava um tronco, o machado caiu na água. Ele gritou: — Ai! Meu senhor! O machado era emprestado.

[[v12-6-6]]

^<<v12-6-6,6>>^ O homem de Deus perguntou: — Onde caiu? Ele mostrou-lhe o lugar. Então Eliseu cortou um galho, jogou-o na água naquele lugar, e fez o ferro flutuar.

[[v12-6-7]]

^<<v12-6-7,7>>^ Então disse: — Pegue-o. O homem estendeu a mão e o pegou.

[[v12-6-8]]

^<<v12-6-8,8>>^ O rei da Síria estava em guerra contra Israel. E, em conselho com os seus oficiais, disse: — Em tal e tal lugar estará o meu acampamento.

[[v12-6-9]]

^<<v12-6-9,9>>^ Mas o homem de Deus mandou dizer ao rei de Israel: — Evite passar por tal lugar, porque os sírios estão descendo para ali.

[[v12-6-10]]

^<<v12-6-10,10>>^ O rei de Israel enviou tropas ao lugar de que o homem de Deus lhe havia falado e de que o tinha avisado, e, assim, se salvou mais do que uma ou duas vezes.

[[v12-6-11]]

^<<v12-6-11,11>>^ O rei da Síria ficou angustiado com este incidente. Então chamou os seus servos e perguntou: — Vocês não vão me dizer quem dos nossos está do lado do rei de Israel?

[[v12-6-12]]

^<<v12-6-12,12>>^ Um dos servos respondeu: — Ninguém, ó rei, meu senhor. Mas o profeta Eliseu, que está em Israel, conta ao rei de Israel as palavras que o senhor fala no seu quarto de dormir.

[[v12-6-13]]

^<<v12-6-13,13>>^ Então o rei disse: — Vão e descubram onde ele está, para que eu mande prendê-lo. E contaram ao rei: — Eis que ele está em Dotã.

[[v12-6-14]]

^<<v12-6-14,14>>^ Então o rei enviou para lá cavalos, carros de guerra e um grande exército. Eles chegaram de noite e cercaram a cidade.

[[v12-6-15]]

^<<v12-6-15,15>>^ O servo do homem de Deus levantou-se bem cedo e, ao sair, eis que tropas, cavalos e carros de guerra haviam cercado a cidade. Então o moço disse a Eliseu: — Ai, meu senhor! Que faremos?

[[v12-6-16]]

^<<v12-6-16,16>>^ Ele respondeu: — Não tenha medo, porque são mais os que estão conosco do que os que estão com eles.

[[v12-6-17]]

^<<v12-6-17,17>>^ E Eliseu orou e disse: — Senhor , peço-te que abras os olhos dele para que veja. O Senhor  abriu os olhos do moço, e ele viu que o monte estava cheio de cavalos e carros de fogo, ao redor de Eliseu.

[[v12-6-18]]

^<<v12-6-18,18>>^ E, quando os sírios desceram contra ele, Eliseu orou ao Senhor  e disse: — Peço-te que firas esta gente de cegueira. E ele os feriu de cegueira, conforme a palavra de Eliseu.

[[v12-6-19]]

^<<v12-6-19,19>>^ Então Eliseu lhes disse: — Não é este o caminho, nem esta a cidade; sigam-me, e eu os guiarei ao homem que vocês estão procurando. E os guiou à cidade de Samaria.

[[v12-6-20]]

^<<v12-6-20,20>>^ Quando eles chegaram a Samaria, Eliseu disse: — Ó Senhor , abre os olhos destes homens para que vejam. E o Senhor  abriu os olhos deles, e viram; e eis que estavam dentro de Samaria.

[[v12-6-21]]

^<<v12-6-21,21>>^ Quando o rei de Israel os viu, perguntou a Eliseu: — Meu pai, devo matá-los? Devo matá-los?

[[v12-6-22]]

^<<v12-6-22,22>>^ Ele respondeu: — Não os mate! Você mataria aqueles que fizesse prisioneiros com a sua espada e o seu arco? Ordena que lhes deem pão e água, para que comam, bebam e voltem para o seu senhor.

[[v12-6-23]]

^<<v12-6-23,23>>^ Então o rei ofereceu-lhes um grande banquete, e comeram e beberam. Ele os despediu e eles voltaram para o seu senhor. E da parte da Síria não houve mais investidas na terra de Israel.

[[v12-6-24]]

^<<v12-6-24,24>>^ Depois disto, Ben-Hadade, rei da Síria, ajuntou todo o seu exército, foi e sitiou a cidade de Samaria.

[[v12-6-25]]

^<<v12-6-25,25>>^ Houve grande fome em Samaria. Eis que a sitiaram, a ponto de se vender a cabeça de um jumento por oitenta moedas de prata e um pouco de esterco de pomba por cinco moedas de prata.

[[v12-6-26]]

^<<v12-6-26,26>>^ Quando o rei de Israel vinha passando, andando sobre a muralha, uma mulher gritou: — Ajude-me, ó rei, meu senhor!

[[v12-6-27]]

^<<v12-6-27,27>>^ Ele respondeu: Se o Senhor  Deus não ajudar você, com que poderei eu ajudá-la? Com a eira ou com o lagar?

[[v12-6-28]]

^<<v12-6-28,28>>^ E o rei acrescentou: — Qual é o seu problema? Ela respondeu: — Esta mulher me disse: "Dê o seu filho, para que hoje o comamos, e amanhã comeremos o meu."

[[v12-6-29]]

^<<v12-6-29,29>>^ Assim, cozinhamos o meu filho e o comemos. Mas no outro dia, quando eu disse a ela: "Dê o seu filho, para que o comamos", ela o escondeu.

[[v12-6-30]]

^<<v12-6-30,30>>^ Ao ouvir as palavras da mulher, o rei rasgou as suas roupas. Como ele estava andando sobre a muralha, o povo olhou e viu que, por baixo, sobre a pele, o rei estava usando pano de saco.

[[v12-6-31]]

^<<v12-6-31,31>>^ Então o rei disse: — Que Deus me castigue se até o final do dia Eliseu, filho de Safate, ainda estiver com a cabeça sobre os ombros.

[[v12-6-32]]

^<<v12-6-32,32>>^ Eliseu estava sentado em sua casa, juntamente com os anciãos. O rei enviou um homem à sua frente. Mas, antes que o mensageiro chegasse, Eliseu disse aos anciãos: — Vocês estão vendo como aquele filho de um assassino mandou alguém para cortar a minha cabeça? Quando o mensageiro vier, fechem a porta e empurrem-no com ela. Não é fato que logo depois dele se ouvirá o barulho dos passos de seu senhor?

[[v12-6-33]]

^<<v12-6-33,33>>^ Enquanto Eliseu ainda falava com eles, chegou o rei, que disse: — Eis que este mal vem do Senhor  Deus. Que mais poderia eu esperar do Senhor ?

'''

xref:012-2-reis/012-2-reis-005.adoc#v12-5-0[&#60; Capítulo Anterior] | <<v12-6-0,Topo>> | xref:012-2-reis/012-2-reis-007.adoc#v12-7-0[Próximo Capítulo &#62;]