include::./index.adoc[]

[[v12-5-0]]
=== 2 Reis, 5
// naa ?, NAA - Nova Almeida Atualizada

[[v12-5-1]]

^<<v12-5-1,1>>^ Naamã, comandante do exército do rei da Síria, era grande homem diante do seu senhor e de muito conceito, porque por meio dele o Senhor  tinha dado a vitória à Síria. Ele era herói de guerra, porém sofria de lepra.

[[v12-5-2]]

^<<v12-5-2,2>>^ Tropas saíram da Síria, e da terra de Israel levaram cativa uma menina, que ficou ao serviço da mulher de Naamã.

[[v12-5-3]]

^<<v12-5-3,3>>^ Um dia a menina disse à sua senhora: — Quem dera o meu senhor estivesse na presença do profeta que está em Samaria; ele o curaria da sua lepra.

[[v12-5-4]]

^<<v12-5-4,4>>^ Então Naamã foi contar isso ao seu senhor, dizendo: — Assim e assim falou a jovem que é da terra de Israel.

[[v12-5-5]]

^<<v12-5-5,5>>^ O rei da Síria respondeu: — Vá! Eu enviarei uma carta ao rei de Israel. Então Naamã partiu e levou consigo trezentos e quarenta quilos de prata, setenta e dois quilos de ouro e dez mudas de roupa.

[[v12-5-6]]

^<<v12-5-6,6>>^ Levou também ao rei de Israel a carta, que dizia: "Tão logo esta carta chegar a você, saiba que eu lhe enviei Naamã, meu servo, para que você o cure da sua lepra."

[[v12-5-7]]

^<<v12-5-7,7>>^ Quando o rei de Israel acabou de ler a carta, rasgou as suas roupas em sinal de medo e disse: — Por acaso sou Deus, com poder de tirar a vida ou dá-la, para que este envie a mim um homem para eu curá-lo de sua lepra? Como vocês podem notar e ver, ele está procurando um pretexto contra mim.

[[v12-5-8]]

^<<v12-5-8,8>>^ Mas, quando Eliseu, homem de Deus, ouviu que o rei de Israel havia rasgado as suas roupas, mandou dizer ao rei: — Por que o senhor rasgou as suas roupas? Deixe-o vir a mim, e ele saberá que há profeta em Israel.

[[v12-5-9]]

^<<v12-5-9,9>>^ Então Naamã foi com os seus cavalos e os seus carros e parou à porta da casa de Eliseu.

[[v12-5-10]]

^<<v12-5-10,10>>^ Eliseu lhe mandou um mensageiro, dizendo: — Vá e lave-se sete vezes no Jordão, e a sua carne será restaurada, e você ficará limpo.

[[v12-5-11]]

^<<v12-5-11,11>>^ Mas Naamã ficou indignado e se foi, dizendo: — Eu pensava que ele certamente sairia para falar comigo, ficaria em pé, invocaria o nome do Senhor , seu Deus, passaria a mão sobre o lugar da lepra e restauraria o leproso.

[[v12-5-12]]

^<<v12-5-12,12>>^ Por acaso não são Abana e Farfar, rios de Damasco, melhores do que todas as águas de Israel? Será que eu não poderia me lavar neles e ficar limpo? Deu meia-volta e foi embora muito irritado.

[[v12-5-13]]

^<<v12-5-13,13>>^ Então os seus oficiais se aproximaram e lhe disseram: — Meu pai, se o profeta tivesse dito alguma coisa difícil, por acaso o senhor não faria? Muito mais agora que ele apenas disse: "Lave-se e você ficará limpo."

[[v12-5-14]]

^<<v12-5-14,14>>^ Então Naamã desceu e mergulhou no Jordão sete vezes, conforme a palavra do homem de Deus; e a sua pele se tornou como a pele de uma criança, e ficou limpo.

[[v12-5-15]]

^<<v12-5-15,15>>^ Depois ele voltou ao homem de Deus, ele e toda a sua comitiva. Veio, pôs-se diante dele e disse: — Eis que, agora, reconheço que em toda a terra não há Deus, a não ser em Israel. E agora, por favor, aceite um presente deste seu servo.

[[v12-5-16]]

^<<v12-5-16,16>>^ Porém ele respondeu: — Tão certo como vive o Senhor , em cuja presença estou, não aceitarei nada. Naamã insistiu com ele para que aceitasse, mas ele recusou.

[[v12-5-17]]

^<<v12-5-17,17>>^ Então Naamã disse: — Se você não quer, então peço que seja permitido a este seu servo levar duas mulas carregadas de terra; porque este seu servo nunca mais oferecerá holocausto nem sacrifício a outros deuses, a não ser ao Senhor .

[[v12-5-18]]

^<<v12-5-18,18>>^ Mas que o Senhor  Deus perdoe o seu servo uma coisa: quando meu senhor, o rei, entrar no templo de Rimom para ali adorar, e ele se encostar no meu braço, e eu também tiver de me encurvar no templo de Rimom, quando assim me prostrar no templo de Rimom, que o Senhor  Deus perdoe este seu servo por isso.

[[v12-5-19]]

^<<v12-5-19,19>>^ Eliseu lhe disse: — Vá em paz. Quando Naamã tinha se afastado certa distância,

[[v12-5-20]]

^<<v12-5-20,20>>^ Geazi, o servo de Eliseu, homem de Deus, disse consigo: — Eis que meu senhor foi generoso demais com este sírio Naamã, recusando o que ele trazia. Mas, tão certo como vive o Senhor , vou correr atrás dele e receberei dele alguma coisa.

[[v12-5-21]]

^<<v12-5-21,21>>^ Então Geazi correu atrás de Naamã. Quando Naamã viu que alguém vinha correndo atrás dele, saltou da carruagem para ir ao encontro dele. Então perguntou: — Está tudo bem?

[[v12-5-22]]

^<<v12-5-22,22>>^ Ele respondeu: — Sim, tudo bem. Meu senhor me mandou dizer: "Eis que agora mesmo vieram da região montanhosa de Efraim dois jovens que fazem parte do grupo dos discípulos dos profetas. Por favor, dê-lhes trinta e quatro quilos de prata e duas mudas de roupa."

[[v12-5-23]]

^<<v12-5-23,23>>^ Naamã disse: — Tenha a bondade de levar sessenta e oito quilos. Insistiu com ele e amarrou sessenta e oito quilos de prata em dois sacos e duas mudas de roupa. Pôs isso sobre os ombros de dois dos seus servos, para que o levassem à frente de Geazi.

[[v12-5-24]]

^<<v12-5-24,24>>^ Quando ele chegou à colina, pegou os sacos que os servos traziam e os depositou na casa. Então despediu aqueles homens, que se foram.

[[v12-5-25]]

^<<v12-5-25,25>>^ Ele, porém, entrou e se pôs diante de seu senhor. Eliseu perguntou: — De onde você vem, Geazi? Ele respondeu: — Este seu servo não foi a lugar nenhum.

[[v12-5-26]]

^<<v12-5-26,26>>^ Porém Eliseu disse: — Você acha que eu não estava com você em espírito quando aquele homem voltou da sua carruagem, para encontrar-se com você? Será que esta era a ocasião para você aceitar prata e aceitar roupas, olivais e vinhas, ovelhas e bois, servos e servas?

[[v12-5-27]]

^<<v12-5-27,27>>^ Portanto, a lepra de Naamã se pegará a você e à sua descendência para sempre. E Geazi saiu da presença de Eliseu já leproso, branco como a neve.

'''

xref:012-2-reis/012-2-reis-004.adoc#v12-4-0[&#60; Capítulo Anterior] | <<v12-5-0,Topo>> | xref:012-2-reis/012-2-reis-006.adoc#v12-6-0[Próximo Capítulo &#62;]