include::./index.adoc[]

[[v1-34-0]]
=== Gênesis, 34
// naa ?, NAA - Nova Almeida Atualizada

[[v1-34-1]]

^<<v1-34-1,1>>^ Ora, Diná, a filha que Lia teve com Jacó, saiu para ver as filhas da terra.

[[v1-34-2]]

^<<v1-34-2,2>>^ Quem a viu foi Siquém, filho do heveu Hamor, que era príncipe daquela terra. Tomando-a, ele teve relações com ela e assim a humilhou.

[[v1-34-3]]

^<<v1-34-3,3>>^ Siquém se apegou a Diná, filha de Jacó, amou a jovem e lhe falou ao coração.

[[v1-34-4]]

^<<v1-34-4,4>>^ Então Siquém disse a seu pai Hamor: — Consiga-me esta jovem para que seja a minha esposa.

[[v1-34-5]]

^<<v1-34-5,5>>^ Quando Jacó ficou sabendo que Diná, sua filha, havia sido desonrada por Siquém, os seus filhos estavam no campo com o gado. Por isso, calou-se e esperou até que eles voltassem.

[[v1-34-6]]

^<<v1-34-6,6>>^ Então Hamor, o pai de Siquém, saiu para falar com Jacó.

[[v1-34-7]]

^<<v1-34-7,7>>^ Quando os filhos de Jacó vieram do campo e ouviram o que havia acontecido, indignaram-se e ficaram muito irados, pois Siquém havia praticado uma afronta em Israel, violentando a filha de Jacó, que era algo que não se devia fazer.

[[v1-34-8]]

^<<v1-34-8,8>>^ Mas Hamor falou com eles, dizendo: — Meu filho Siquém está profundamente apaixonado pela filha de vocês. Peço que ela lhe seja dada por esposa.

[[v1-34-9]]

^<<v1-34-9,9>>^ Tornem-se nossos parentes; deem as filhas de vocês para nós e vocês tomem as nossas filhas.

[[v1-34-10]]

^<<v1-34-10,10>>^ Vocês habitarão em nosso meio, a terra estará ao seu dispor. Morem nela, negociem e adquiram propriedades.

[[v1-34-11]]

^<<v1-34-11,11>>^ E o próprio Siquém disse ao pai e aos irmãos de Diná: — Que eu obtenha este favor diante de vocês e lhes darei o que me pedirem.

[[v1-34-12]]

^<<v1-34-12,12>>^ Aumentem em muito o dote de casamento e as dádivas, e darei o que me pedirem; deem-me, porém, a moça por esposa.

[[v1-34-13]]

^<<v1-34-13,13>>^ Então os filhos de Jacó, por haver Siquém desonrado Diná, a irmã deles, responderam com astúcia a Siquém e a seu pai Hamor e lhes disseram:

[[v1-34-14]]

^<<v1-34-14,14>>^ — Não podemos fazer isso, dar a nossa irmã a um homem que ainda não foi circuncidado, porque isso seria uma vergonha para nós.

[[v1-34-15]]

^<<v1-34-15,15>>^ Sob uma única condição permitiremos: que vocês se tornem como nós, circuncidando todos os do sexo masculino.

[[v1-34-16]]

^<<v1-34-16,16>>^ Então lhes daremos as nossas filhas, tomaremos para nós as filhas de vocês, habitaremos no meio de vocês e seremos um só povo.

[[v1-34-17]]

^<<v1-34-17,17>>^ Se, porém, não ouvirem e não quiserem ser circuncidados, tomaremos a nossa filha e iremos embora.

[[v1-34-18]]

^<<v1-34-18,18>>^ Tais palavras agradaram Hamor e Siquém, seu filho.

[[v1-34-19]]

^<<v1-34-19,19>>^ O jovem não tardou em fazer o que foi solicitado, porque amava a filha de Jacó e era o mais honrado de toda a casa de seu pai.

[[v1-34-20]]

^<<v1-34-20,20>>^ Assim, Hamor e Siquém, seu filho, vieram ao portão da sua cidade e falaram aos homens da cidade:

[[v1-34-21]]

^<<v1-34-21,21>>^ — Esses homens são pacíficos em relação a nós. Portanto, deixem que morem na terra e negociem nela. A terra é bastante espaçosa para contê-los. Vamos tomar as filhas deles por esposas e dar também as nossas filhas a eles.

[[v1-34-22]]

^<<v1-34-22,22>>^ Mas eles só concordarão em morar conosco, tornando-nos um só povo, se todos os homens em nosso meio se deixarem circuncidar, como eles são circuncidados.

[[v1-34-23]]

^<<v1-34-23,23>>^ Não é verdade que o gado, os bens e todos os animais deles serão nossos? Portanto, vamos concordar e eles ficarão morando entre nós.

[[v1-34-24]]

^<<v1-34-24,24>>^ E todos os que saíam do portão da cidade deram ouvidos a Hamor e a Siquém, seu filho. E todos os do sexo masculino foram circuncidados, todos os que saíam pelo portão da cidade.

[[v1-34-25]]

^<<v1-34-25,25>>^ No terceiro dia, quando os homens sentiam mais forte a dor, dois filhos de Jacó, Simeão e Levi, irmãos de Diná, pegaram cada um a sua espada, entraram inesperadamente na cidade e mataram todos os homens.

[[v1-34-26]]

^<<v1-34-26,26>>^ Passaram também ao fio da espada Hamor e seu filho Siquém; tiraram Diná da casa de Siquém e saíram.

[[v1-34-27]]

^<<v1-34-27,27>>^ Os filhos de Jacó vieram, passaram por cima dos cadáveres, e saquearam a cidade, porque a irmã deles havia sido desonrada.

[[v1-34-28]]

^<<v1-34-28,28>>^ Levaram deles os rebanhos, os bois, os jumentos e o que havia na cidade e no campo.

[[v1-34-29]]

^<<v1-34-29,29>>^ Pegaram todos os bens, levaram cativas as mulheres e todas as crianças, e saquearam tudo o que havia nas casas.

[[v1-34-30]]

^<<v1-34-30,30>>^ Então Jacó disse a Simeão e a Levi: — Vocês me criaram um problema e me fizeram odioso entre os moradores desta terra, entre os cananeus e os ferezeus. Como somos pouca gente, eles se reunirão contra mim, e serei destruído, eu e a minha casa.

[[v1-34-31]]

^<<v1-34-31,31>>^ Eles responderam: — E que direito ele tinha de tratar a nossa irmã como se fosse prostituta?

'''

xref:001-genesis/001-genesis-033.adoc#v1-33-0[&#60; Capítulo Anterior] | <<v1-34-0,Topo>> | xref:001-genesis/001-genesis-035.adoc#v1-35-0[Próximo Capítulo &#62;]