include::./index.adoc[]

[[v1-19-0]]
=== Gênesis, 19
// naa ?, NAA - Nova Almeida Atualizada

[[v1-19-1]]

^<<v1-19-1,1>>^ Ao anoitecer, os dois anjos chegaram a Sodoma. Ló estava sentado junto ao portão da cidade. Quando viu os anjos, levantou-se e, indo ao encontro deles, prostrou-se com o rosto em terra

[[v1-19-2]]

^<<v1-19-2,2>>^ e lhes disse: — Por favor, meus senhores, venham para a casa deste servo de vocês. Poderão passar a noite, lavar os pés, levantar-se de madrugada e seguir o seu caminho. Mas eles responderam: — Não; passaremos a noite na praça.

[[v1-19-3]]

^<<v1-19-3,3>>^ Ló insistiu tanto, que eles foram e entraram na casa dele. Deu-lhes um banquete, fez assar uns pães sem fermento, e eles comeram.

[[v1-19-4]]

^<<v1-19-4,4>>^ Mas, antes que eles se deitassem, os homens daquela cidade cercaram a casa. Eram os homens de Sodoma, tanto os moços como os velhos, sim, todo o povo de todos os lados.

[[v1-19-5]]

^<<v1-19-5,5>>^ E chamaram Ló e lhe disseram: — Onde estão os homens que, à noitinha, entraram na sua casa? Traga-os aqui fora para que abusemos deles.

[[v1-19-6]]

^<<v1-19-6,6>>^ Então Ló foi até a porta, fechou-a atrás de si

[[v1-19-7]]

^<<v1-19-7,7>>^ e lhes disse: — Meus irmãos, peço-lhes que não cometam essa maldade.

[[v1-19-8]]

^<<v1-19-8,8>>^ Olhem aqui! Tenho duas filhas, virgens, e vou trazê-las para vocês. Façam com elas o que quiserem, porém não façam nada a estes homens, porque se acham sob a proteção do meu teto.

[[v1-19-9]]

^<<v1-19-9,9>>^ Eles, porém, disseram: — Saia daí! E acrescentaram: — Ele é estrangeiro, veio morar entre nós e pretende ser juiz em tudo? Vamos fazer com você pior do que com eles. E atiraram-se contra o homem, contra Ló, e se aproximaram para arrombar a porta.

[[v1-19-10]]

^<<v1-19-10,10>>^ Porém os homens, estendendo a mão, puxaram Ló para dentro e fecharam a porta.

[[v1-19-11]]

^<<v1-19-11,11>>^ E feriram de cegueira os que estavam do lado de fora, desde o menor até o maior, de modo que se cansaram à procura da porta.

[[v1-19-12]]

^<<v1-19-12,12>>^ Então os homens disseram a Ló: — Você tem aqui mais alguém dos seus? Genro, filhos, filhas, todos quantos você tem na cidade, faça-os sair daqui,

[[v1-19-13]]

^<<v1-19-13,13>>^ pois vamos destruir este lugar, porque o seu clamor tem aumentado, chegando até a presença do Senhor , e o Senhor  nos enviou a destruí-lo.

[[v1-19-14]]

^<<v1-19-14,14>>^ Então Ló saiu e foi falar com os seus genros, os que estavam para casar com as suas filhas. Ele disse: — Levantem-se e saiam deste lugar, porque o Senhor  vai destruir a cidade. Mas eles pensaram que Ló estava brincando.

[[v1-19-15]]

^<<v1-19-15,15>>^ Ao amanhecer, os anjos apressaram Ló, dizendo: — Levante-se, pegue a sua mulher e as suas duas filhas, que aqui se encontram, e saia daqui, para que você não morra quando a cidade for castigada.

[[v1-19-16]]

^<<v1-19-16,16>>^ Como, porém, ele se demorasse, aqueles homens o pegaram pela mão, a ele, a sua mulher e as duas filhas, sendo-lhe o Senhor  misericordioso, e o tiraram, e o puseram fora da cidade.

[[v1-19-17]]

^<<v1-19-17,17>>^ Havendo-os levado para fora, um deles disse: — Corra, para sair daqui com vida! Não olhe para trás, nem pare em toda a campina. Fuja para o monte, para que você não morra.

[[v1-19-18]]

^<<v1-19-18,18>>^ Mas Ló disse a eles: — Assim não, meu Senhor!

[[v1-19-19]]

^<<v1-19-19,19>>^ Eis que o teu servo encontrou favor diante dos teus olhos, e engrandeceste a tua misericórdia para comigo, salvando-me a vida. Mas não posso fugir para o monte, pois receio que a destruição vá me alcançar, e eu morra.

[[v1-19-20]]

^<<v1-19-20,20>>^ Eis aqui perto uma cidadezinha para a qual eu posso fugir. Ela é bem pequena. Permita que eu fuja para lá — ela é bem pequena, não é verdade? —, e nela poderei salvar a minha vida.

[[v1-19-21]]

^<<v1-19-21,21>>^ O anjo respondeu: — Quanto a isso, estou de acordo, para não destruir a cidade de que você acaba de falar.

[[v1-19-22]]

^<<v1-19-22,22>>^ Vá depressa e refugie-se nela; pois nada posso fazer, enquanto você não tiver chegado lá. Por isso, a cidade recebeu o nome de Zoar.

[[v1-19-23]]

^<<v1-19-23,23>>^ O sol estava nascendo sobre a terra, quando Ló entrou em Zoar.

[[v1-19-24]]

^<<v1-19-24,24>>^ Então o Senhor  fez chover enxofre e fogo sobre Sodoma e Gomorra. Isso veio da parte do Senhor , desde os céus.

[[v1-19-25]]

^<<v1-19-25,25>>^ Ele destruiu aquelas cidades, e toda a campina, e todos os moradores das cidades, e o que nascia na terra.

[[v1-19-26]]

^<<v1-19-26,26>>^ E a mulher de Ló olhou para trás e virou uma estátua de sal.

[[v1-19-27]]

^<<v1-19-27,27>>^ Na manhã seguinte, Abraão se levantou de madrugada e foi para o lugar onde tinha estado na presença do Senhor .

[[v1-19-28]]

^<<v1-19-28,28>>^ Abraão olhou para Sodoma e Gomorra e para toda a terra da campina e viu que da terra subia fumaça, como se fosse a fumaça de uma fornalha.

[[v1-19-29]]

^<<v1-19-29,29>>^ Assim, quando destruiu as cidades da campina, Deus se lembrou de Abraão e tirou Ló do meio da destruição, quando subverteu as cidades em que Ló tinha morado.

[[v1-19-30]]

^<<v1-19-30,30>>^ Ló partiu de Zoar e habitou no monte, ele e as duas filhas, porque receavam permanecer em Zoar. Ló habitou numa caverna, e com ele as duas filhas.

[[v1-19-31]]

^<<v1-19-31,31>>^ Então a primogênita disse à mais moça: — Nosso pai está velho, e não há homem na terra que venha unir-se conosco, segundo o costume de toda terra.

[[v1-19-32]]

^<<v1-19-32,32>>^ Venha, vamos embebedá-lo com vinho, deitemo-nos com ele e conservemos a descendência de nosso pai.

[[v1-19-33]]

^<<v1-19-33,33>>^ Naquela noite, deram de beber vinho a seu pai. E, entrando a primogênita, se deitou com ele, sem que ele o notasse, nem quando ela se deitou, nem quando se levantou.

[[v1-19-34]]

^<<v1-19-34,34>>^ No dia seguinte, a primogênita disse à mais nova: — Ontem à noite, deitei-me com o meu pai. Vamos embebedá-lo também esta noite; entre e deite-se com ele, para que preservemos a descendência de nosso pai.

[[v1-19-35]]

^<<v1-19-35,35>>^ De novo, naquela noite, deram de beber vinho a seu pai. E, entrando a mais nova, se deitou com ele, sem que ele o notasse, nem quando ela se deitou, nem quando se levantou.

[[v1-19-36]]

^<<v1-19-36,36>>^ E assim as duas filhas de Ló ficaram grávidas do próprio pai.

[[v1-19-37]]

^<<v1-19-37,37>>^ A primogênita deu à luz um filho e lhe deu o nome de Moabe. Este é o pai dos moabitas, até o dia de hoje.

[[v1-19-38]]

^<<v1-19-38,38>>^ A mais nova também deu à luz um filho e lhe deu o nome de Ben-Ami. Este é o pai dos amonitas, até o dia de hoje.

'''

xref:001-genesis/001-genesis-018.adoc#v1-18-0[&#60; Capítulo Anterior] | <<v1-19-0,Topo>> | xref:001-genesis/001-genesis-020.adoc#v1-20-0[Próximo Capítulo &#62;]