include::./index.adoc[]

[[v1-24-0]]
=== Gênesis, 24
// naa ?, NAA - Nova Almeida Atualizada

[[v1-24-1]]

^<<v1-24-1,1>>^ Abraão já era velho, de idade bem avançada, e o Senhor  o havia abençoado em tudo.

[[v1-24-2]]

^<<v1-24-2,2>>^ Abraão disse ao mais antigo servo da sua casa, que governava tudo o que possuía: — Ponha a sua mão por baixo da minha coxa,

[[v1-24-3]]

^<<v1-24-3,3>>^ para que eu faça com que você jure pelo Senhor , Deus do céu e da terra, que você não buscará uma esposa para o meu filho entre as filhas dos cananeus, no meio dos quais estou morando,

[[v1-24-4]]

^<<v1-24-4,4>>^ mas que você irá à minha parentela e ali buscará uma esposa para Isaque, meu filho.

[[v1-24-5]]

^<<v1-24-5,5>>^ Então o servo disse: — Talvez a mulher não queira vir comigo para esta terra. Nesse caso, devo levar o seu filho à terra de onde o senhor veio?

[[v1-24-6]]

^<<v1-24-6,6>>^ Abraão respondeu: — Cuidado! Não faça o meu filho voltar para lá.

[[v1-24-7]]

^<<v1-24-7,7>>^ O Senhor , Deus do céu, que me tirou da casa de meu pai e da terra dos meus parentes, e que me falou, e jurou, dizendo: "À sua descendência darei esta terra", ele enviará o seu anjo adiante de você, para que lá você encontre uma esposa para o meu filho.

[[v1-24-8]]

^<<v1-24-8,8>>^ Caso a mulher não queira vir, você ficará desobrigado do seu juramento; entretanto, não leve o meu filho para lá.

[[v1-24-9]]

^<<v1-24-9,9>>^ Com isso, o servo pôs a sua mão por baixo da coxa de Abraão, seu senhor, e jurou fazer segundo o resolvido.

[[v1-24-10]]

^<<v1-24-10,10>>^ O servo pegou dez dos camelos do seu senhor e, levando consigo uma parte dos bens dele, levantou-se e partiu para a Mesopotâmia, para a cidade onde Naor havia morado.

[[v1-24-11]]

^<<v1-24-11,11>>^ Fora da cidade, fez os camelos se ajoelharem junto a um poço de água. Era de tardinha, a hora em que as moças saem para tirar água.

[[v1-24-12]]

^<<v1-24-12,12>>^ Então o servo orou: — Ó Senhor , Deus de meu senhor Abraão, peço-te que me ajudes hoje e sejas bondoso para com o meu senhor Abraão!

[[v1-24-13]]

^<<v1-24-13,13>>^ Eis que estou ao pé da fonte de água, e as filhas dos homens desta cidade saem para tirar água.

[[v1-24-14]]

^<<v1-24-14,14>>^ Concede, pois, que a moça a quem eu disser: "Incline o cântaro para que eu beba"; e ela me responder: "Beba, e darei ainda de beber aos seus camelos", seja a que designaste para o teu servo Isaque; e nisso verei que foste bondoso para com o meu senhor.

[[v1-24-15]]

^<<v1-24-15,15>>^ Antes que ele acabasse de orar, eis que surgiu Rebeca, filha de Betuel, filho de Milca, mulher de Naor, irmão de Abraão, trazendo um cântaro sobre o ombro.

[[v1-24-16]]

^<<v1-24-16,16>>^ A moça era muito bonita, virgem, a quem nenhum homem havia possuído. Ela desceu até a fonte, encheu o seu cântaro e subiu.

[[v1-24-17]]

^<<v1-24-17,17>>^ Então o servo correu ao encontro dela e disse: — Peço que me deixe beber um pouco da água do seu cântaro.

[[v1-24-18]]

^<<v1-24-18,18>>^ Ela respondeu: — Beba, meu senhor. E prontamente, baixando o cântaro para a mão, deu-lhe de beber.

[[v1-24-19]]

^<<v1-24-19,19>>^ Depois de lhe dar de beber, disse: — Vou tirar água também para os seus camelos, até que todos bebam.

[[v1-24-20]]

^<<v1-24-20,20>>^ E, apressando-se em despejar o cântaro no bebedouro, correu outra vez ao poço para tirar mais água; ela tirou água para todos os camelos.

[[v1-24-21]]

^<<v1-24-21,21>>^ O homem a observava, em silêncio, atentamente, para saber se o Senhor  teria levado a bom termo a sua jornada ou não.

[[v1-24-22]]

^<<v1-24-22,22>>^ Quando os camelos acabaram de beber, o homem pegou um pendente de ouro pesando seis gramas e duas pulseiras para as mãos dela, pesando cento e vinte gramas de ouro.

[[v1-24-23]]

^<<v1-24-23,23>>^ Em seguida perguntou: — Diga-me: De quem você é filha? Será que na casa de seu pai haveria lugar para eu e os que estão comigo passarmos a noite?

[[v1-24-24]]

^<<v1-24-24,24>>^ Ela respondeu: — Sou filha de Betuel, que é filho de Milca e de Naor.

[[v1-24-25]]

^<<v1-24-25,25>>^ E acrescentou: — Temos palha, muito pasto e lugar para passar a noite.

[[v1-24-26]]

^<<v1-24-26,26>>^ Então o homem se inclinou e adorou o Senhor .

[[v1-24-27]]

^<<v1-24-27,27>>^ E disse: — Bendito seja o Senhor , Deus de meu senhor Abraão, que não retirou a sua bondade e a sua verdade do meu senhor. Quanto a mim, estando no caminho, o Senhor  me guiou à casa dos parentes do meu senhor.

[[v1-24-28]]

^<<v1-24-28,28>>^ E a moça correu e contou tudo aos da casa de sua mãe.

[[v1-24-29]]

^<<v1-24-29,29>>^ Ora, Rebeca tinha um irmão, chamado Labão. Este correu ao encontro do homem junto à fonte.

[[v1-24-30]]

^<<v1-24-30,30>>^ Acontece que Labão tinha visto o pendente e as pulseiras nas mãos de sua irmã e ouvido as palavras de Rebeca, sua irmã, que dizia: "Ele me falou assim e assim." Por isso foi até onde ele estava e o encontrou em pé junto aos camelos, ao lado da fonte.

[[v1-24-31]]

^<<v1-24-31,31>>^ E Labão disse: — Entre, bendito do Senhor ! Por que você está aí fora? Já preparei a casa e o lugar para os camelos.

[[v1-24-32]]

^<<v1-24-32,32>>^ Então o homem entrou na casa. Descarregaram os camelos e lhes deram forragem e pasto. Também trouxeram água para que ele e os homens que estavam com ele lavassem os pés.

[[v1-24-33]]

^<<v1-24-33,33>>^ Puseram comida diante dele. Porém ele disse: — Não vou comer enquanto não disser o que tenho para dizer. Labão respondeu: — Diga.

[[v1-24-34]]

^<<v1-24-34,34>>^ Então ele disse: — Sou servo de Abraão.

[[v1-24-35]]

^<<v1-24-35,35>>^ O Senhor  tem abençoado muito o meu senhor, e ele se tornou um grande homem. O Senhor  lhe deu ovelhas e bois, prata e ouro, servos e servas, camelos e jumentos.

[[v1-24-36]]

^<<v1-24-36,36>>^ Sara, mulher do meu senhor, já era idosa quando lhe deu à luz um filho, a quem o meu senhor deu tudo o que tem.

[[v1-24-37]]

^<<v1-24-37,37>>^ E meu senhor me fez jurar, dizendo: "Não busque uma esposa para o meu filho entre as mulheres dos cananeus, em cuja terra estou morando.

[[v1-24-38]]

^<<v1-24-38,38>>^ Pelo contrário, vá à casa de meu pai e à minha família e ali busque uma esposa para o meu filho."

[[v1-24-39]]

^<<v1-24-39,39>>^ Respondi ao meu senhor: "Talvez a mulher não queira me acompanhar."

[[v1-24-40]]

^<<v1-24-40,40>>^ Ele me disse: "O Senhor , em cuja presença eu ando, enviará o seu Anjo com você e levará a bom termo a sua jornada, para que, da minha família e da casa de meu pai, você traga uma esposa para o meu filho.

[[v1-24-41]]

^<<v1-24-41,41>>^ Você estará desobrigado do seu juramento, caso você for até a minha família e eles não quiserem dar a moça a você; neste caso, você estará desobrigado do juramento."

[[v1-24-42]]

^<<v1-24-42,42>>^ — Hoje, pois, quando cheguei à fonte, eu disse: "Ó Senhor , Deus de meu senhor Abraão, leva a bom termo a jornada em que sigo.

[[v1-24-43]]

^<<v1-24-43,43>>^ Eis-me agora junto à fonte de água. A moça que sair para tirar água, a quem eu disser: ‘Dê-me um pouco de água do seu cântaro’,

[[v1-24-44]]

^<<v1-24-44,44>>^ e ela me responder: ‘Beba, e também tirarei água para os seus camelos’, seja essa a mulher que o Senhor  designou para o filho de meu senhor."

[[v1-24-45]]

^<<v1-24-45,45>>^ — Antes que eu acabasse de orar em meu íntimo, eis que veio Rebeca trazendo o seu cântaro sobre o ombro. Ela desceu à fonte e tirou água. E eu lhe disse: "Peço que me dê de beber."

[[v1-24-46]]

^<<v1-24-46,46>>^ Ela prontamente baixou o cântaro do ombro e disse: "Beba, e também darei de beber aos seus camelos." Bebi, e ela deu de beber aos camelos.

[[v1-24-47]]

^<<v1-24-47,47>>^ Daí lhe perguntei: "De quem você é filha?" Ela respondeu: "Filha de Betuel, que é filho de Naor e Milca." Então lhe pus o pendente no nariz e as pulseiras nas mãos.

[[v1-24-48]]

^<<v1-24-48,48>>^ E, prostrando-me, adorei o Senhor  e louvei o Senhor , Deus do meu senhor Abraão, que me havia conduzido por um caminho direito, a fim de encontrar para o filho do meu senhor uma filha do seu parente.

[[v1-24-49]]

^<<v1-24-49,49>>^ Agora, pois, se estiverem dispostos a usar de bondade e de fidelidade para com o meu senhor, digam; do contrário, digam também, para que eu siga o meu caminho, para a direita ou para a esquerda.

[[v1-24-50]]

^<<v1-24-50,50>>^ Labão e Betuel responderam: — Isto procede do Senhor . Nada temos a dizer, nem a favor nem contra.

[[v1-24-51]]

^<<v1-24-51,51>>^ Aqui está Rebeca; leve-a com você e que ela seja a mulher do filho do seu senhor, segundo a palavra do Senhor  Deus.

[[v1-24-52]]

^<<v1-24-52,52>>^ Quando o servo de Abraão ouviu tais palavras, prostrou-se em terra diante do Senhor .

[[v1-24-53]]

^<<v1-24-53,53>>^ Tirou joias de ouro e de prata e vestidos e os deu a Rebeca. Também deu ricos presentes ao irmão e à mãe dela.

[[v1-24-54]]

^<<v1-24-54,54>>^ Depois, comeram e beberam, ele e os homens que estavam com ele, e passaram a noite. De madrugada, quando se levantaram, o servo disse: — Permitam que eu volte ao meu senhor.

[[v1-24-55]]

^<<v1-24-55,55>>^ Mas o irmão e a mãe da moça disseram: — Deixe que ela fique conosco mais alguns dias, pelo menos dez; e depois poderá ir.

[[v1-24-56]]

^<<v1-24-56,56>>^ Ele, porém, lhes disse: — Não me detenham, pois o Senhor  me tem levado a bom termo na jornada; deixem que eu volte ao meu senhor.

[[v1-24-57]]

^<<v1-24-57,57>>^ Disseram: — Vamos chamar a moça para ver o que ela diz.

[[v1-24-58]]

^<<v1-24-58,58>>^ Chamaram, pois, Rebeca e lhe perguntaram: — Você quer ir com este homem? Ela respondeu: — Sim, quero.

[[v1-24-59]]

^<<v1-24-59,59>>^ Então deixaram que Rebeca, a irmã deles, partisse, junto com a sua ama, com o servo de Abraão e os homens que estavam com ele.

[[v1-24-60]]

^<<v1-24-60,60>>^ Abençoaram Rebeca e lhe disseram: — Que você, nossa irmã, seja a mãe de milhares de milhares, e que a sua descendência tome posse das cidades dos seus inimigos.

[[v1-24-61]]

^<<v1-24-61,61>>^ Então Rebeca se levantou com as suas servas e, montando os camelos, seguiram o homem. O servo de Abraão tomou Rebeca e partiu.

[[v1-24-62]]

^<<v1-24-62,62>>^ Ora, Isaque veio de Beer-Laai-Roi, porque morava na terra do Neguebe.

[[v1-24-63]]

^<<v1-24-63,63>>^ Ao cair da tarde, Isaque saiu para meditar no campo. Erguendo os olhos, viu, e eis que vinham camelos.

[[v1-24-64]]

^<<v1-24-64,64>>^ Também Rebeca levantou os olhos e, vendo Isaque, desceu do camelo,

[[v1-24-65]]

^<<v1-24-65,65>>^ e perguntou ao servo: — Quem é aquele homem que vem pelo campo ao nosso encontro? O servo respondeu: — É o meu senhor. Então ela pegou o véu e se cobriu.

[[v1-24-66]]

^<<v1-24-66,66>>^ O servo contou a Isaque todas as coisas que havia feito.

[[v1-24-67]]

^<<v1-24-67,67>>^ Isaque a conduziu até a tenda de Sara, mãe dele. Ele tomou Rebeca, e esta se tornou a mulher dele. Ele a amou; e assim Isaque foi consolado depois da morte de sua mãe.

'''

xref:001-genesis/001-genesis-023.adoc#v1-23-0[&#60; Capítulo Anterior] | <<v1-24-0,Topo>> | xref:001-genesis/001-genesis-025.adoc#v1-25-0[Próximo Capítulo &#62;]