include::./index.adoc[]

[[v1-4-0]]
=== Gênesis, 4
// naa ?, NAA - Nova Almeida Atualizada

[[v1-4-1]]

^<<v1-4-1,1>>^ Adão teve relações com Eva, a sua mulher. Ela ficou grávida e deu à luz Caim. Então ela disse: — Adquiri um varão com o auxílio do Senhor .

[[v1-4-2]]

^<<v1-4-2,2>>^ Depois, deu à luz Abel, irmão de Caim. Abel foi pastor de ovelhas, e Caim foi agricultor.

[[v1-4-3]]

^<<v1-4-3,3>>^ Aconteceu que, ao fim de um certo tempo, Caim trouxe do fruto da terra uma oferta ao Senhor .

[[v1-4-4]]

^<<v1-4-4,4>>^ Abel, por sua vez, trouxe das primícias do seu rebanho e da gordura deste. O Senhor  se agradou de Abel e de sua oferta,

[[v1-4-5]]

^<<v1-4-5,5>>^ mas de Caim e de sua oferta não se agradou. Caim ficou muito irritado e fechou a cara.

[[v1-4-6]]

^<<v1-4-6,6>>^ Então o Senhor  lhe disse: — Por que você anda irritado? E por que essa cara fechada?

[[v1-4-7]]

^<<v1-4-7,7>>^ Se fizer o que é certo, não é verdade que você será aceito? Mas, se não fizer o que é certo, eis que o pecado está à porta, à sua espera. O desejo dele será contra você, mas é necessário que você o domine.

[[v1-4-8]]

^<<v1-4-8,8>>^ Caim disse a Abel, seu irmão: — Vamos ao campo. Estando eles no campo, Caim se levantou contra Abel, o seu irmão, e o matou.

[[v1-4-9]]

^<<v1-4-9,9>>^ O Senhor  disse a Caim: — Onde está Abel, o seu irmão? Ele respondeu: — Não sei; por acaso sou o guardador do meu irmão?

[[v1-4-10]]

^<<v1-4-10,10>>^ E o Senhor  disse: — O que foi que você fez? A voz do sangue do seu irmão clama da terra a mim.

[[v1-4-11]]

^<<v1-4-11,11>>^ E agora você é maldito sobre a terra, cuja boca se abriu para receber da sua mão o sangue do seu irmão.

[[v1-4-12]]

^<<v1-4-12,12>>^ Quando você cultivar o solo, ele não lhe dará a sua força; você será fugitivo e errante pela terra.

[[v1-4-13]]

^<<v1-4-13,13>>^ Então Caim disse ao Senhor : — Meu castigo é tão grande, que não poderei suportá-lo.

[[v1-4-14]]

^<<v1-4-14,14>>^ Eis que hoje me expulsas da face da terra, e da tua presença terei de me esconder; serei fugitivo e errante pela terra; quem se encontrar comigo me matará.

[[v1-4-15]]

^<<v1-4-15,15>>^ O Senhor , porém, lhe disse: — Não! E, se alguém matar Caim, será vingado sete vezes. E o Senhor  pôs um sinal em Caim para que, se alguém viesse a encontrá-lo, não o matasse.

[[v1-4-16]]

^<<v1-4-16,16>>^ E Caim se retirou da presença do Senhor  e habitou na terra de Node, a leste do Éden.

[[v1-4-17]]

^<<v1-4-17,17>>^ E Caim teve relações com sua mulher; ela ficou grávida e deu à luz Enoque. Caim edificou uma cidade e a chamou de Enoque, o nome de seu filho.

[[v1-4-18]]

^<<v1-4-18,18>>^ A Enoque nasceu Irade. Irade gerou Meujael, Meujael gerou Metusael, e Metusael gerou Lameque.

[[v1-4-19]]

^<<v1-4-19,19>>^ Lameque tomou para si duas esposas: o nome de uma era Ada, e o nome da outra era Zilá.

[[v1-4-20]]

^<<v1-4-20,20>>^ Ada deu à luz Jabal, que foi o pai dos que habitam em tendas e possuem gado.

[[v1-4-21]]

^<<v1-4-21,21>>^ O nome de seu irmão era Jubal, que foi o pai de todos os que tocam harpa e flauta.

[[v1-4-22]]

^<<v1-4-22,22>>^ Zilá, por sua vez, deu à luz Tubalcaim, artífice de todo instrumento cortante, de bronze e de ferro; a irmã de Tubalcaim foi Naamá.

[[v1-4-23]]

^<<v1-4-23,23>>^ E Lameque disse às suas esposas: "Ada e Zilá, ouçam o que eu digo; vocês, mulheres de Lameque, escutem o que passo a dizer: Matei um homem porque me feriu; e um jovem porque me machucou.

[[v1-4-24]]

^<<v1-4-24,24>>^ Se Caim é vingado sete vezes, Lameque será vingado setenta vezes sete."

[[v1-4-25]]

^<<v1-4-25,25>>^ Adão tornou a ter relações com sua mulher. E ela deu à luz um filho, a quem pôs o nome de Sete, dizendo: — Deus me concedeu outro descendente em lugar de Abel, que Caim matou.

[[v1-4-26]]

^<<v1-4-26,26>>^ A Sete nasceu-lhe também um filho, ao qual pôs o nome de Enos. Foi nesse tempo que se começou a invocar o nome do Senhor .

'''

xref:001-genesis/001-genesis-003.adoc#v1-3-0[&#60; Capítulo Anterior] | <<v1-4-0,Topo>> | xref:001-genesis/001-genesis-005.adoc#v1-5-0[Próximo Capítulo &#62;]