include::./index.adoc[]

[[v1-27-0]]
=== Gênesis, 27
// naa ?, NAA - Nova Almeida Atualizada

[[v1-27-1]]

^<<v1-27-1,1>>^ Quando Isaque envelheceu e os seus olhos se enfraqueceram, a ponto de não mais poder ver, chamou Esaú, seu filho mais velho, e lhe disse: — Meu filho! Esaú respondeu: — Aqui estou!

[[v1-27-2]]

^<<v1-27-2,2>>^ O pai lhe disse: — Estou velho e não sei o dia da minha morte.

[[v1-27-3]]

^<<v1-27-3,3>>^ Pegue agora as suas armas, a sua aljava e o seu arco, vá ao campo e apanhe para mim alguma caça.

[[v1-27-4]]

^<<v1-27-4,4>>^ Faça uma comida saborosa, como eu aprecio, e traga aqui para mim, para que eu coma e abençoe você antes que eu morra.

[[v1-27-5]]

^<<v1-27-5,5>>^ Rebeca esteve escutando enquanto Isaque falava com Esaú, seu filho. E Esaú foi ao campo para apanhar a caça e trazê-la.

[[v1-27-6]]

^<<v1-27-6,6>>^ Então Rebeca disse a Jacó, seu filho: — Ouvi seu pai falar com Esaú, o seu irmão. Ele disse:

[[v1-27-7]]

^<<v1-27-7,7>>^ "Traga uma caça e faça uma comida saborosa para mim, para que eu coma e o abençoe na presença do Senhor , antes que eu morra."

[[v1-27-8]]

^<<v1-27-8,8>>^ Agora, meu filho, escute as minhas palavras e faça o que lhe ordeno.

[[v1-27-9]]

^<<v1-27-9,9>>^ Vá ao rebanho e traga-me dois bons cabritos. Deles farei uma saborosa comida para o seu pai, como ele aprecia.

[[v1-27-10]]

^<<v1-27-10,10>>^ Você a levará ao seu pai, para que a coma e o abençoe, antes que ele morra.

[[v1-27-11]]

^<<v1-27-11,11>>^ Mas Jacó disse a Rebeca, sua mãe: — Esaú, meu irmão, é um homem peludo, e eu sou um homem de pele lisa.

[[v1-27-12]]

^<<v1-27-12,12>>^ Se o meu pai me apalpar, passarei a ser visto por ele como zombador e trarei sobre mim maldição e não bênção.

[[v1-27-13]]

^<<v1-27-13,13>>^ A mãe respondeu: — Caia sobre mim essa maldição, meu filho. Faça somente o que eu digo: vá e traga os cabritos para mim.

[[v1-27-14]]

^<<v1-27-14,14>>^ Ele foi, pegou os cabritos e os trouxe a sua mãe, que fez uma saborosa comida, como o pai dele apreciava.

[[v1-27-15]]

^<<v1-27-15,15>>^ Depois, Rebeca pegou a melhor roupa de Esaú, seu filho mais velho, roupa que tinha consigo em casa, e vestiu Jacó, seu filho mais novo.

[[v1-27-16]]

^<<v1-27-16,16>>^ Com a pele dos cabritos cobriu-lhe as mãos e a lisura do pescoço.

[[v1-27-17]]

^<<v1-27-17,17>>^ Então entregou a Jacó, seu filho, a comida saborosa e o pão que havia preparado.

[[v1-27-18]]

^<<v1-27-18,18>>^ Jacó foi a seu pai e disse: — Meu pai! Ele respondeu: — Fale! Quem é você, meu filho?

[[v1-27-19]]

^<<v1-27-19,19>>^ Jacó respondeu a seu pai: — Sou Esaú, seu filho primogênito. Fiz o que o senhor ordenou. Levante-se, por favor; sente-se e coma da minha caça, para que depois o senhor me abençoe.

[[v1-27-20]]

^<<v1-27-20,20>>^ Isaque perguntou a seu filho: — Como foi que você conseguiu achar a caça tão depressa, meu filho? Ele respondeu: — Porque o Senhor , seu Deus, a mandou ao meu encontro.

[[v1-27-21]]

^<<v1-27-21,21>>^ Então Isaque disse a Jacó: — Chegue mais perto, para que eu o apalpe, meu filho, e veja se você é meu filho Esaú ou não.

[[v1-27-22]]

^<<v1-27-22,22>>^ Jacó se aproximou de Isaque, seu pai, que o apalpou e disse: — A voz é de Jacó, mas as mãos são de Esaú.

[[v1-27-23]]

^<<v1-27-23,23>>^ E não o reconheceu, porque as mãos realmente estavam peludas como as de seu irmão Esaú. E o abençoou.

[[v1-27-24]]

^<<v1-27-24,24>>^ Então perguntou: — Você é mesmo o meu filho Esaú? Ele respondeu: — Eu sou.

[[v1-27-25]]

^<<v1-27-25,25>>^ Então disse: — Traga isso para perto de mim, para que eu coma da caça de meu filho e o abençoe. Jacó a levou até ele e o pai comeu. Trouxe-lhe também vinho, e ele bebeu.

[[v1-27-26]]

^<<v1-27-26,26>>^ Então Isaque, seu pai, lhe disse: — Venha cá e me dê um beijo, meu filho.

[[v1-27-27]]

^<<v1-27-27,27>>^ Ele se aproximou e o beijou. Então o pai aspirou o cheiro da roupa dele e o abençoou. Ele disse: Eis que o cheiro do meu filho é como o cheiro do campo, que o Senhor  abençoou;

[[v1-27-28]]

^<<v1-27-28,28>>^ Deus lhe dê do orvalho do céu, e da exuberância da terra, e fartura de trigo e de vinho.

[[v1-27-29]]

^<<v1-27-29,29>>^ Que povos sirvam você, e nações o reverenciem. Que você seja senhor de seus irmãos, e os filhos de sua mãe se curvem diante de você. Maldito seja quem o amaldiçoar, e bendito quem o abençoar.

[[v1-27-30]]

^<<v1-27-30,30>>^ E aconteceu que, depois que Isaque abençoou Jacó e este tinha acabado de sair da presença de seu pai, chegou Esaú, seu irmão, vindo da sua caçada.

[[v1-27-31]]

^<<v1-27-31,31>>^ Ele também fez uma comida saborosa e a levou ao seu pai. E lhe disse: — Levante-se, meu pai, e coma da caça de seu filho, para que o senhor me abençoe.

[[v1-27-32]]

^<<v1-27-32,32>>^ Então Isaque, o pai dele, perguntou: — Quem é você? Ele respondeu: — Sou o seu filho, o seu primogênito; sou Esaú.

[[v1-27-33]]

^<<v1-27-33,33>>^ Isaque estremeceu, sentindo uma violenta comoção. E disse: — Mas então quem foi aquele que apanhou a caça e trouxe para mim? Eu comi tudo, antes que você chegasse, e o abençoei, e ele será abençoado.

[[v1-27-34]]

^<<v1-27-34,34>>^ Ao ouvir tais palavras de seu pai, Esaú deu um grito cheio de amargura e disse: — Abençoe também a mim, meu pai!

[[v1-27-35]]

^<<v1-27-35,35>>^ Mas Isaque respondeu: — Seu irmão veio e, com astúcia, tomou a bênção que era sua.

[[v1-27-36]]

^<<v1-27-36,36>>^ Esaú disse: — Não é com razão que ele se chama Jacó? Pois já duas vezes me enganou: tirou-me o direito de primogenitura e agora tomou a bênção que era minha. E perguntou: — Então o senhor não reservou nenhuma bênção para mim?

[[v1-27-37]]

^<<v1-27-37,37>>^ Isaque respondeu a Esaú: — Eis que o constituí senhor sobre você, e fiz com que todos os parentes sejam servos dele; de trigo e de vinho o supri. Assim, o que posso fazer por você, meu filho?

[[v1-27-38]]

^<<v1-27-38,38>>^ Esaú disse a seu pai: — Será que o senhor, meu pai, tem somente uma bênção? Abençoe também a mim, meu pai. E, levantando Esaú a voz, chorou.

[[v1-27-39]]

^<<v1-27-39,39>>^ Então Isaque, seu pai, disse: Sua habitação será longe dos lugares férteis da terra, longe do orvalho que cai do alto.

[[v1-27-40]]

^<<v1-27-40,40>>^ Você viverá da sua espada e servirá o seu irmão; quando, porém, você se libertar, sacudirá do seu pescoço o jugo dele.

[[v1-27-41]]

^<<v1-27-41,41>>^ Esaú passou a odiar Jacó por causa da bênção com que seu pai o tinha abençoado. E disse em seu íntimo: — Os dias de luto por meu pai se aproximam; então matarei meu irmão Jacó.

[[v1-27-42]]

^<<v1-27-42,42>>^ Chegaram aos ouvidos de Rebeca estas palavras de Esaú, seu filho mais velho. Então ela mandou chamar Jacó, seu filho mais moço, e lhe disse: — Eis que o seu irmão Esaú se consola fazendo planos para matá-lo.

[[v1-27-43]]

^<<v1-27-43,43>>^ Agora, pois, meu filho, ouça bem o que vou dizer: levante-se e fuja para a casa de Labão, meu irmão, em Harã.

[[v1-27-44]]

^<<v1-27-44,44>>^ Fique com ele alguns dias, até que passe o furor de seu irmão,

[[v1-27-45]]

^<<v1-27-45,45>>^ e cesse o rancor dele contra você, e se esqueça do que você lhe fez. Quando isso acontecer, enviarei alguém para trazer você de volta. Não posso perder os meus dois filhos num só dia!

[[v1-27-46]]

^<<v1-27-46,46>>^ Então Rebeca disse a Isaque: — Estou aborrecida da vida por causa das filhas de Hete. Se Jacó tomar esposa dentre as filhas de Hete, tais como estas, as filhas desta terra, de que me servirá a vida?

'''

xref:001-genesis/001-genesis-026.adoc#v1-26-0[&#60; Capítulo Anterior] | <<v1-27-0,Topo>> | xref:001-genesis/001-genesis-028.adoc#v1-28-0[Próximo Capítulo &#62;]