include::./index.adoc[]

[[v1-36-0]]
=== Gênesis, 36
// naa ?, NAA - Nova Almeida Atualizada

[[v1-36-1]]

^<<v1-36-1,1>>^ São estes os descendentes de Esaú, que é Edom.

[[v1-36-2]]

^<<v1-36-2,2>>^ Esaú tomou por mulheres dentre as filhas de Canaã: Ada, filha de Elom, heteu; Oolibama, filha de Aná, filho de Zibeão, heveu;

[[v1-36-3]]

^<<v1-36-3,3>>^ e Basemate, filha de Ismael, irmã de Nebaiote.

[[v1-36-4]]

^<<v1-36-4,4>>^ De Ada teve Esaú um filho chamado Elifaz e de Basemate lhe nasceu Reuel.

[[v1-36-5]]

^<<v1-36-5,5>>^ A Oolibama nasceu Jeús, Jalão e Corá. Estes são os filhos de Esaú, que lhe nasceram na terra de Canaã.

[[v1-36-6]]

^<<v1-36-6,6>>^ Esaú tomou as suas mulheres, os seus filhos, as suas filhas, todas as pessoas de sua casa, o seu rebanho, todo o seu gado, todos os bens, tudo o que havia adquirido na terra de Canaã e os levou para outra terra, longe de seu irmão Jacó.

[[v1-36-7]]

^<<v1-36-7,7>>^ Porque os bens deles eram muitos para habitarem juntos e a terra de suas peregrinações não os podia sustentar por causa do seu gado.

[[v1-36-8]]

^<<v1-36-8,8>>^ Então Esaú, que é Edom, habitou no monte Seir.

[[v1-36-9]]

^<<v1-36-9,9>>^ Esta é a descendência de Esaú, pai dos edomitas, no monte Seir.

[[v1-36-10]]

^<<v1-36-10,10>>^ São estes os nomes dos filhos de Esaú: Elifaz, filho de Ada, mulher de Esaú; Reuel, filho de Basemate, mulher de Esaú.

[[v1-36-11]]

^<<v1-36-11,11>>^ Os filhos de Elifaz foram: Temã, Omar, Zefô, Gaetã e Quenaz.

[[v1-36-12]]

^<<v1-36-12,12>>^ Timna era concubina de Elifaz, filho de Esaú; ela deu à luz Amaleque. Estes são os filhos de Ada, mulher de Esaú.

[[v1-36-13]]

^<<v1-36-13,13>>^ E os filhos de Reuel são estes: Naate, Zerá, Samá e Mizá; estes foram os filhos de Basemate, mulher de Esaú.

[[v1-36-14]]

^<<v1-36-14,14>>^ E são estes os filhos de Oolibama, filha de Aná, filho de Zibeão, mulher de Esaú; ela deu a Esaú: Jeús, Jalão e Corá.

[[v1-36-15]]

^<<v1-36-15,15>>^ São estes os chefes dos filhos de Esaú; os filhos de Elifaz, o primogênito de Esaú: os chefes Temã, Omar, Zefô, Quenaz,

[[v1-36-16]]

^<<v1-36-16,16>>^ Corá, Gaetã, Amaleque. Estes são os chefes que nasceram a Elifaz na terra de Edom; são os filhos de Ada.

[[v1-36-17]]

^<<v1-36-17,17>>^ São estes os filhos de Reuel, filho de Esaú: os chefes Naate, Zerá, Samá e Mizá. Estes são os chefes que nasceram a Reuel na terra de Edom; são os filhos de Basemate, mulher de Esaú.

[[v1-36-18]]

^<<v1-36-18,18>>^ São estes os filhos de Oolibama, mulher de Esaú: os chefes Jeús, Jalão e Corá. Estes são os chefes que descendem de Oolibama, filha de Aná e mulher de Esaú.

[[v1-36-19]]

^<<v1-36-19,19>>^ São estes os filhos de Esaú, isto é, Edom, e esses são os seus chefes.

[[v1-36-20]]

^<<v1-36-20,20>>^ São estes os filhos de Seir, o horeu, moradores da terra: Lotã, Sobal, Zibeão e Aná,

[[v1-36-21]]

^<<v1-36-21,21>>^ Disom, Eser e Disã. Estes são os chefes dos horeus, filhos de Seir na terra de Edom.

[[v1-36-22]]

^<<v1-36-22,22>>^ Os filhos de Lotã são Hori e Homã; a irmã de Lotã é Timna.

[[v1-36-23]]

^<<v1-36-23,23>>^ São estes os filhos de Sobal: Alvã, Manaate, Ebal, Sefô e Onã.

[[v1-36-24]]

^<<v1-36-24,24>>^ São estes os filhos de Zibeão: Aiá e Aná; este é o Aná que achou as fontes termais no deserto, quando apascentava os jumentos de Zibeão, seu pai.

[[v1-36-25]]

^<<v1-36-25,25>>^ São estes os filhos de Aná: Disom e Oolibama, a filha de Aná.

[[v1-36-26]]

^<<v1-36-26,26>>^ Estes são os filhos de Disom: Hendã, Esbã, Itrã e Querã.

[[v1-36-27]]

^<<v1-36-27,27>>^ São estes os filhos de Eser: Bilã, Zaavã e Acã.

[[v1-36-28]]

^<<v1-36-28,28>>^ São estes os filhos de Disã: Uz e Arã.

[[v1-36-29]]

^<<v1-36-29,29>>^ São estes os chefes dos horeus: Lotã, Sobal, Zibeão, Aná,

[[v1-36-30]]

^<<v1-36-30,30>>^ Disom, Eser e Disã. Estes são os chefes dos horeus na terra de Seir.

[[v1-36-31]]

^<<v1-36-31,31>>^ São estes os reis que reinaram na terra de Edom, antes que houvesse rei sobre os filhos de Israel.

[[v1-36-32]]

^<<v1-36-32,32>>^ Em Edom reinou Belá, filho de Beor, e o nome da sua cidade era Dinabá.

[[v1-36-33]]

^<<v1-36-33,33>>^ Belá morreu, e, em seu lugar, reinou Jobabe, filho de Zerá, de Bozra.

[[v1-36-34]]

^<<v1-36-34,34>>^ Morreu Jobabe, e, em seu lugar, reinou Husão, da terra dos temanitas.

[[v1-36-35]]

^<<v1-36-35,35>>^ Morreu Husão, e, em seu lugar, reinou Hadade, filho de Bedade, o que derrotou Midiã no campo de Moabe. O nome da sua cidade era Avite.

[[v1-36-36]]

^<<v1-36-36,36>>^ Morreu Hadade, e, em seu lugar, reinou Samlá, de Masreca.

[[v1-36-37]]

^<<v1-36-37,37>>^ Morreu Samlá, e, em seu lugar, reinou Saul, de Reobote, junto ao Eufrates.

[[v1-36-38]]

^<<v1-36-38,38>>^ Morreu Saul, e, em seu lugar, reinou Baal-Hanã, filho de Acbor.

[[v1-36-39]]

^<<v1-36-39,39>>^ Morreu Baal-Hanã, filho de Acbor, e, em seu lugar, reinou Hadar. O nome de sua cidade era Paú, e o de sua mulher era Meetabel, filha de Matrede, filha de Me-Zaabe.

[[v1-36-40]]

^<<v1-36-40,40>>^ São estes os nomes dos chefes de Esaú, segundo as suas famílias, os seus lugares e os seus nomes: os chefes Timna, Alva, Jetete,

[[v1-36-41]]

^<<v1-36-41,41>>^ Oolibama, Elá, Pinom,

[[v1-36-42]]

^<<v1-36-42,42>>^ Quenaz, Temã, Mibzar,

[[v1-36-43]]

^<<v1-36-43,43>>^ Magdiel e Irã. Estes são os chefes de Edom, segundo as suas habitações na terra que possuíam. Este é Esaú, pai dos edomitas.

'''

xref:001-genesis/001-genesis-035.adoc#v1-35-0[&#60; Capítulo Anterior] | <<v1-36-0,Topo>> | xref:001-genesis/001-genesis-037.adoc#v1-37-0[Próximo Capítulo &#62;]