include::./index.adoc[]

[[v1-38-0]]
=== Gênesis, 38
// naa ?, NAA - Nova Almeida Atualizada

[[v1-38-1]]

^<<v1-38-1,1>>^ Aconteceu, por esse tempo, que Judá se afastou de seus irmãos e se hospedou na casa de um adulamita, chamado Hira.

[[v1-38-2]]

^<<v1-38-2,2>>^ Ali Judá viu a filha de um cananeu, chamado Sua; ele a tomou por mulher e teve relações com ela.

[[v1-38-3]]

^<<v1-38-3,3>>^ A mulher ficou grávida e deu à luz um filho, e Judá lhe deu o nome de Er.

[[v1-38-4]]

^<<v1-38-4,4>>^ Ela ficou grávida outra vez e deu à luz um filho, a quem ela deu o nome de Onã.

[[v1-38-5]]

^<<v1-38-5,5>>^ Mais uma vez ela ficou grávida e deu à luz outro filho, a quem ela chamou de Selá. Ela estava em Quezibe quando o teve.

[[v1-38-6]]

^<<v1-38-6,6>>^ Judá tomou uma esposa para Er, o seu primogênito; o nome dela era Tamar.

[[v1-38-7]]

^<<v1-38-7,7>>^ No entanto, Er, o primogênito de Judá, era mau aos olhos do Senhor , e por isso o Senhor  fez com que ele morresse.

[[v1-38-8]]

^<<v1-38-8,8>>^ Então Judá disse a Onã: — Tenha relações com a mulher do seu irmão, cumpra a obrigação de cunhado e dê uma descendência ao seu irmão.

[[v1-38-9]]

^<<v1-38-9,9>>^ Mas Onã sabia que o filho não seria considerado seu. Por isso, todas as vezes que tinha relações com a mulher de seu irmão deixava o sêmen cair na terra, para não dar descendência a seu irmão.

[[v1-38-10]]

^<<v1-38-10,10>>^ Isso, porém, que fazia, era mau aos olhos do Senhor , e por isso fez com que também este morresse.

[[v1-38-11]]

^<<v1-38-11,11>>^ Então Judá disse a Tamar, sua nora: — Continue viúva na casa de seu pai, até que Selá, meu filho, cresça. Pois Judá pensava assim: "É para que não morra também este, como os seus irmãos." Assim, Tamar se foi, passando a morar na casa do pai dela.

[[v1-38-12]]

^<<v1-38-12,12>>^ Algum tempo depois morreu a mulher de Judá, que era filha de Sua. Quando terminou o período de luto, Judá foi até onde estavam os tosquiadores de suas ovelhas, em Timna, ele e seu amigo Hira, o adulamita.

[[v1-38-13]]

^<<v1-38-13,13>>^ E alguém foi dizer a Tamar: — Eis que o seu sogro está a caminho de Timna, para tosquiar as ovelhas.

[[v1-38-14]]

^<<v1-38-14,14>>^ Então ela tirou as suas roupas de viúva, e, cobrindo-se com um véu, se disfarçou e se sentou à entrada de Enaim, no caminho de Timna. Porque ela sabia que Selá já era homem, e ela não lhe havia sido dada por mulher.

[[v1-38-15]]

^<<v1-38-15,15>>^ Quando Judá a viu, pensou que se tratava de uma prostituta, pois ela havia coberto o rosto.

[[v1-38-16]]

^<<v1-38-16,16>>^ Então se dirigiu a ela no caminho e lhe disse: — Venha, quero ter relações com você! Acontece que ele não sabia que ela era a sua nora. Ela respondeu: — O que você me dá para ter relações comigo?

[[v1-38-17]]

^<<v1-38-17,17>>^ Ele respondeu: — Eu mando para você um cabrito do meu rebanho. Ela perguntou: — Você deixa comigo alguma garantia até mandar o cabrito?

[[v1-38-18]]

^<<v1-38-18,18>>^ Ele respondeu: — Que garantia posso deixar com você? Ela disse: — O seu selo, o seu cordão e o cajado que você tem na mão. Ele lhe deu os objetos, teve relações com ela, e ela ficou grávida dele.

[[v1-38-19]]

^<<v1-38-19,19>>^ Tamar se levantou e foi embora. Tirou o véu e pôs outra vez as suas roupas de viúva.

[[v1-38-20]]

^<<v1-38-20,20>>^ Judá enviou o cabrito, por meio do adulamita, seu amigo, para reaver a garantia que tinha deixado com a mulher, mas ele não a encontrou.

[[v1-38-21]]

^<<v1-38-21,21>>^ Então o amigo de Judá perguntou aos homens daquele lugar: — Onde está a prostituta cultual que costumava ficar junto ao caminho de Enaim? Responderam: — Aqui não havia nenhuma prostituta cultual.

[[v1-38-22]]

^<<v1-38-22,22>>^ Ele voltou a Judá e disse: — Não encontrei a mulher. E além disso os homens do lugar me disseram que lá nunca houve nenhuma prostituta cultual.

[[v1-38-23]]

^<<v1-38-23,23>>^ Judá respondeu: — Que ela fique com aquelas coisas para si, para que não venhamos a passar vergonha. Eis que mandei o cabrito, mas você não encontrou a mulher.

[[v1-38-24]]

^<<v1-38-24,24>>^ Passados quase três meses, foram dizer a Judá: — A sua nora Tamar se prostituiu, pois está grávida. Ao que Judá respondeu: — Tragam-na para fora para que seja queimada.

[[v1-38-25]]

^<<v1-38-25,25>>^ Quando a estavam trazendo para fora, ela mandou dizer ao sogro: — Eu estou grávida do homem a quem pertencem estas coisas. E disse mais: — Veja se reconhece de quem é este selo, este cordão e este cajado.

[[v1-38-26]]

^<<v1-38-26,26>>^ Judá os reconheceu e disse: — Ela é mais justa do que eu, porque não a dei a Selá, meu filho. E nunca mais teve relações com ela.

[[v1-38-27]]

^<<v1-38-27,27>>^ E aconteceu que, estando ela para dar à luz, havia gêmeos no seu ventre.

[[v1-38-28]]

^<<v1-38-28,28>>^ Ao nascerem, um pôs a mão para fora, e a parteira, tomando-a, amarrou nela um fio vermelho, dizendo: — Este saiu primeiro.

[[v1-38-29]]

^<<v1-38-29,29>>^ Mas, recolhendo ele a mão, o outro nasceu primeiro. E a parteira disse: — Como você rompeu a saída? E lhe deram o nome de Perez.

[[v1-38-30]]

^<<v1-38-30,30>>^ Depois nasceu o irmão, em cuja mão estava o fio vermelho. E lhe deram o nome de Zera.

'''

xref:001-genesis/001-genesis-037.adoc#v1-37-0[&#60; Capítulo Anterior] | <<v1-38-0,Topo>> | xref:001-genesis/001-genesis-039.adoc#v1-39-0[Próximo Capítulo &#62;]