include::./index.adoc[]

[[v1-41-0]]
=== Gênesis, 41
// naa ?, NAA - Nova Almeida Atualizada

[[v1-41-1]]

^<<v1-41-1,1>>^ Passados dois anos completos, Faraó teve um sonho e eis que estava em pé junto ao rio Nilo.

[[v1-41-2]]

^<<v1-41-2,2>>^ Do rio subiam sete vacas de boa aparência e gordas e pastavam no meio dos juncos.

[[v1-41-3]]

^<<v1-41-3,3>>^ Após elas subiam do rio outras sete vacas, de aparência feia e magras; e pararam junto às primeiras, na margem do rio.

[[v1-41-4]]

^<<v1-41-4,4>>^ As vacas de aparência feia e magras engoliam as sete vacas de boa aparência e gordas. Então Faraó acordou.

[[v1-41-5]]

^<<v1-41-5,5>>^ Tornando a dormir, sonhou outra vez. De uma só haste saíam sete espigas cheias e boas.

[[v1-41-6]]

^<<v1-41-6,6>>^ E após elas nasciam sete espigas mirradas e queimadas pelo vento leste.

[[v1-41-7]]

^<<v1-41-7,7>>^ As espigas mirradas devoravam as sete espigas grandes e cheias. Então Faraó acordou. Tinha sido um sonho.

[[v1-41-8]]

^<<v1-41-8,8>>^ De manhã, ao despertar muito perturbado, mandou chamar todos os magos do Egito e todos os seus sábios. Contou-lhes os seus sonhos, mas não havia ninguém que pudesse dar a interpretação.

[[v1-41-9]]

^<<v1-41-9,9>>^ Então o copeiro-chefe disse a Faraó: — Hoje me lembro das minhas ofensas.

[[v1-41-10]]

^<<v1-41-10,10>>^ Quando Faraó ficou irado com os seus servos e me pôs na prisão, na casa do comandante da guarda, a mim e ao padeiro-chefe,

[[v1-41-11]]

^<<v1-41-11,11>>^ tivemos um sonho na mesma noite, eu e ele. Sonhamos, e cada sonho tinha o seu próprio significado.

[[v1-41-12]]

^<<v1-41-12,12>>^ Achava-se conosco um jovem hebreu, escravo do comandante da guarda. Contamos a ele os nossos sonhos, e ele nos deu a interpretação, a cada um segundo o seu sonho.

[[v1-41-13]]

^<<v1-41-13,13>>^ E tal como nos interpretou, assim aconteceu: eu fui restituído ao meu cargo, e o outro foi enforcado.

[[v1-41-14]]

^<<v1-41-14,14>>^ Então Faraó mandou chamar José, e o fizeram sair às pressas da masmorra. Ele se barbeou, mudou de roupa e foi apresentar-se a Faraó.

[[v1-41-15]]

^<<v1-41-15,15>>^ Este lhe disse: — Tive um sonho, e não há quem o interprete. Porém ouvi falar a respeito de você que, quando ouve um sonho, é capaz de interpretá-lo.

[[v1-41-16]]

^<<v1-41-16,16>>^ José respondeu: — Isso não está em mim; mas Deus dará resposta favorável a Faraó.

[[v1-41-17]]

^<<v1-41-17,17>>^ Então Faraó disse a José: — No meu sonho, eu estava em pé na margem do Nilo,

[[v1-41-18]]

^<<v1-41-18,18>>^ e eis que subiam dele sete vacas gordas e de boa aparência e pastavam no meio dos juncos.

[[v1-41-19]]

^<<v1-41-19,19>>^ Após estas subiam outras vacas, fracas, muito feias e magras. Eu nunca tinha visto vacas tão feias, em toda a terra do Egito.

[[v1-41-20]]

^<<v1-41-20,20>>^ E as vacas magras e ruins devoravam as primeiras sete vacas gordas.

[[v1-41-21]]

^<<v1-41-21,21>>^ E, depois de as terem engolido, não davam aparência de que as tinham devorado, pois o aspecto delas continuava ruim como no princípio. Então acordei.

[[v1-41-22]]

^<<v1-41-22,22>>^ Depois, vi, em meu sonho, que sete espigas saíam da mesma haste, cheias e boas.

[[v1-41-23]]

^<<v1-41-23,23>>^ Depois delas nasceram sete espigas secas, mirradas e queimadas pelo vento leste.

[[v1-41-24]]

^<<v1-41-24,24>>^ As sete espigas mirradas devoravam as sete espigas boas. Contei isso aos magos, mas ninguém foi capaz de me dar a interpretação.

[[v1-41-25]]

^<<v1-41-25,25>>^ Então José respondeu: — O sonho de Faraó é apenas um; Deus revelou a Faraó o que ele vai fazer.

[[v1-41-26]]

^<<v1-41-26,26>>^ As sete vacas boas serão sete anos; as sete espigas boas, também sete anos; o sonho é um só.

[[v1-41-27]]

^<<v1-41-27,27>>^ As sete vacas magras e feias, que subiam após as primeiras, serão sete anos, bem como as sete espigas mirradas e queimadas pelo vento leste serão sete anos de fome.

[[v1-41-28]]

^<<v1-41-28,28>>^ — Esta é a palavra, como acabo de dizer a Faraó: Deus manifestou a Faraó o que ele vai fazer.

[[v1-41-29]]

^<<v1-41-29,29>>^ Eis que vêm sete anos de grande abundância por toda a terra do Egito.

[[v1-41-30]]

^<<v1-41-30,30>>^ Depois virão sete anos de fome. Toda aquela abundância será esquecida na terra do Egito e a fome consumirá a terra;

[[v1-41-31]]

^<<v1-41-31,31>>^ e não será lembrada a abundância na terra, por causa da fome que seguirá, porque será gravíssima.

[[v1-41-32]]

^<<v1-41-32,32>>^ O sonho de Faraó foi repetido, porque a coisa é estabelecida por Deus, e Deus se apressa a fazê-la.

[[v1-41-33]]

^<<v1-41-33,33>>^ — Agora, pois, Faraó devia escolher um homem ajuizado e sábio e encarregá-lo de dirigir a terra do Egito.

[[v1-41-34]]

^<<v1-41-34,34>>^ Faraó devia fazer isto: pôr administradores sobre a terra e recolher a quinta parte dos frutos da terra do Egito nos sete anos de fartura.

[[v1-41-35]]

^<<v1-41-35,35>>^ Esses administradores deviam ajuntar toda a colheita dos bons anos que virão, recolher cereal por ordem de Faraó, para mantimento nas cidades, e guardá-lo em armazéns.

[[v1-41-36]]

^<<v1-41-36,36>>^ Assim, o mantimento servirá para abastecer a terra nos sete anos da fome que haverá no Egito, para que a terra não seja destruída pela fome.

[[v1-41-37]]

^<<v1-41-37,37>>^ O conselho agradou a Faraó e a todos os seus oficiais.

[[v1-41-38]]

^<<v1-41-38,38>>^ Então Faraó perguntou aos seus oficiais: — Será que poderíamos achar alguém melhor do que José, um homem em quem está o Espírito de Deus?

[[v1-41-39]]

^<<v1-41-39,39>>^ Depois, Faraó disse a José: — Visto que Deus revelou tudo isto a você, não há ninguém tão ajuizado e sábio como você.

[[v1-41-40]]

^<<v1-41-40,40>>^ Você será o administrador da minha casa, e todo o meu povo obedecerá à sua palavra. Somente no trono eu serei maior do que você.

[[v1-41-41]]

^<<v1-41-41,41>>^ E Faraó disse mais a José: — Eis que eu o constituo autoridade sobre toda a terra do Egito.

[[v1-41-42]]

^<<v1-41-42,42>>^ Então Faraó tirou o seu anel-sinete da mão e o pôs no dedo de José. Mandou que o vestissem com roupas de linho fino e lhe pôs no pescoço um colar de ouro.

[[v1-41-43]]

^<<v1-41-43,43>>^ E o fez subir na sua segunda carruagem, e clamavam diante dele: "Inclinem-se todos!" Desse modo, deu-lhe autoridade sobre toda a terra do Egito.

[[v1-41-44]]

^<<v1-41-44,44>>^ Disse ainda Faraó a José: — Eu sou Faraó, mas sem a sua ordem ninguém poderá fazer nada em toda a terra do Egito.

[[v1-41-45]]

^<<v1-41-45,45>>^ E Faraó chamou José de Zafenate-Paneia e lhe deu por mulher Asenate, filha de Potífera, sacerdote de Om. E José percorreu toda a terra do Egito.

[[v1-41-46]]

^<<v1-41-46,46>>^ José tinha trinta anos de idade quando se apresentou a Faraó, rei do Egito, e andou por toda a terra do Egito.

[[v1-41-47]]

^<<v1-41-47,47>>^ Nos sete anos de fartura a terra produziu com abundância.

[[v1-41-48]]

^<<v1-41-48,48>>^ E José ajuntou todo o mantimento que houve na terra do Egito durante os sete anos e o guardou nas cidades; o mantimento do campo ao redor de cada cidade foi guardado na mesma cidade.

[[v1-41-49]]

^<<v1-41-49,49>>^ Assim, José ajuntou muitíssimo cereal, como a areia do mar, até perder a conta, porque ia além das medidas.

[[v1-41-50]]

^<<v1-41-50,50>>^ Antes de chegar a fome, nasceram dois filhos a José, os quais lhe deu Asenate, filha de Potífera, sacerdote de Om.

[[v1-41-51]]

^<<v1-41-51,51>>^ Ao primogênito José chamou de Manassés, pois disse: "Deus me fez esquecer todo o meu trabalho e toda a casa de meu pai."

[[v1-41-52]]

^<<v1-41-52,52>>^ Ao segundo deu o nome de Efraim, pois disse: "Deus me fez próspero na terra da minha aflição."

[[v1-41-53]]

^<<v1-41-53,53>>^ Passados os sete anos de abundância que houve na terra do Egito,

[[v1-41-54]]

^<<v1-41-54,54>>^ começaram os sete anos de fome, como José havia predito. E havia fome em todas as terras, mas em toda a terra do Egito havia pão.

[[v1-41-55]]

^<<v1-41-55,55>>^ Quando toda a terra do Egito começou a sentir a fome, o povo clamou a Faraó por pão; e Faraó dizia a todos os egípcios: — Vão falar com José e façam o que ele disser.

[[v1-41-56]]

^<<v1-41-56,56>>^ Havendo, pois, fome sobre toda a terra, José abriu todos os celeiros e vendia aos egípcios; porque a fome aumentava na terra do Egito.

[[v1-41-57]]

^<<v1-41-57,57>>^ E todas as terras vinham ao Egito para comprar de José, porque a fome aumentava em todo o mundo.

'''

xref:001-genesis/001-genesis-040.adoc#v1-40-0[&#60; Capítulo Anterior] | <<v1-41-0,Topo>> | xref:001-genesis/001-genesis-042.adoc#v1-42-0[Próximo Capítulo &#62;]