include::./index.adoc[]

[[v1-28-0]]
=== Gênesis, 28
// naa ?, NAA - Nova Almeida Atualizada

[[v1-28-1]]

^<<v1-28-1,1>>^ Isaque chamou Jacó e, dando-lhe a sua bênção, lhe ordenou, dizendo: — Não escolha uma esposa dentre as filhas de Canaã.

[[v1-28-2]]

^<<v1-28-2,2>>^ Levante-se e vá a Padã-Arã, à casa de Betuel, pai de sua mãe, e tome lá por esposa uma das filhas de Labão, irmão de sua mãe.

[[v1-28-3]]

^<<v1-28-3,3>>^ Que o Deus Todo-Poderoso o abençoe, faça com que seja fecundo e o multiplique para que você venha a ser uma multidão de povos.

[[v1-28-4]]

^<<v1-28-4,4>>^ Que ele lhe dê a bênção de Abraão, a você e à sua descendência, para que você possua a terra de suas peregrinações, concedida por Deus a Abraão.

[[v1-28-5]]

^<<v1-28-5,5>>^ Assim, Isaque despediu Jacó, que se foi a Padã-Arã, à casa de Labão, filho de Betuel, o arameu, irmão de Rebeca, mãe de Jacó e de Esaú.

[[v1-28-6]]

^<<v1-28-6,6>>^ Esaú viu que Isaque havia abençoado Jacó e o havia mandado a Padã-Arã, para tomar de lá esposa para si, e que, ao abençoá-lo, lhe havia ordenado que não escolhesse uma esposa dentre as filhas de Canaã.

[[v1-28-7]]

^<<v1-28-7,7>>^ Soube também que Jacó, obedecendo ao seu pai e à sua mãe, havia ido a Padã-Arã.

[[v1-28-8]]

^<<v1-28-8,8>>^ Sabendo também que Isaque, seu pai, não via com bons olhos as filhas de Canaã,

[[v1-28-9]]

^<<v1-28-9,9>>^ Esaú foi à casa de Ismael e, além das mulheres que já tinha, tomou por mulher Maalate, filha de Ismael, filho de Abraão, e irmã de Nebaiote.

[[v1-28-10]]

^<<v1-28-10,10>>^ Jacó partiu de Berseba e seguiu para Harã.

[[v1-28-11]]

^<<v1-28-11,11>>^ Quando chegou a certo lugar, ali passou a noite, porque o sol já se havia posto. Pegou uma das pedras do lugar, fez dela o seu travesseiro e se deitou ali mesmo para dormir.

[[v1-28-12]]

^<<v1-28-12,12>>^ E sonhou: Eis que estava posta na terra uma escada cujo topo atingia o céu, e os anjos de Deus subiam e desciam por ela.

[[v1-28-13]]

^<<v1-28-13,13>>^ E eis que o Senhor  estava perto dele e lhe disse: — Eu sou o Senhor , Deus de Abraão, seu pai, e Deus de Isaque. A terra em que agora você está deitado, eu a darei a você e à sua descendência.

[[v1-28-14]]

^<<v1-28-14,14>>^ A sua descendência será como o pó da terra; você se estenderá para o oeste e para o leste, para o norte e para o sul. Em você e na sua descendência serão benditas todas as famílias da terra.

[[v1-28-15]]

^<<v1-28-15,15>>^ Eis que eu estou com você e o guardarei por onde quer que você for. Farei com que você volte para esta terra, porque não o abandonarei até que eu cumpra aquilo que lhe prometi.

[[v1-28-16]]

^<<v1-28-16,16>>^ Quando Jacó despertou do sono, disse: — Na verdade, o Senhor  está neste lugar, e eu não o sabia.

[[v1-28-17]]

^<<v1-28-17,17>>^ E, temendo, disse: — Quão temível é este lugar! É a casa de Deus, a porta dos céus.

[[v1-28-18]]

^<<v1-28-18,18>>^ Na manhã seguinte, Jacó levantou-se de madrugada, pegou a pedra que havia usado como travesseiro e a pôs em pé como coluna. E sobre o topo dela derramou azeite.

[[v1-28-19]]

^<<v1-28-19,19>>^ E ao lugar, cidade que antes se chamava Luz, deu o nome de Betel.

[[v1-28-20]]

^<<v1-28-20,20>>^ Jacó fez também um voto, dizendo: — Se Deus for comigo, e me guardar nesta jornada que empreendo, e me der pão para comer e roupa para vestir,

[[v1-28-21]]

^<<v1-28-21,21>>^ de maneira que eu volte em paz para a casa de meu pai, então o Senhor  será o meu Deus;

[[v1-28-22]]

^<<v1-28-22,22>>^ e a pedra, que pus como coluna, será a casa de Deus; e, de tudo o que me concederes, certamente te darei o dízimo.

'''

xref:001-genesis/001-genesis-027.adoc#v1-27-0[&#60; Capítulo Anterior] | <<v1-28-0,Topo>> | xref:001-genesis/001-genesis-029.adoc#v1-29-0[Próximo Capítulo &#62;]