include::./index.adoc[]

[[v1-43-0]]
=== Gênesis, 43
// naa ?, NAA - Nova Almeida Atualizada

[[v1-43-1]]

^<<v1-43-1,1>>^ A fome continuava gravíssima na terra.

[[v1-43-2]]

^<<v1-43-2,2>>^ Quando eles acabaram de consumir o cereal que tinham trazido do Egito, Jacó disse aos filhos: — Voltem e comprem mais um pouco de mantimento para nós.

[[v1-43-3]]

^<<v1-43-3,3>>^ Mas Judá lhe disse: — Aquele homem nos advertiu solenemente, dizendo: "Vocês não verão o meu rosto, se o outro irmão não vier com vocês."

[[v1-43-4]]

^<<v1-43-4,4>>^ Se o senhor resolver enviar conosco o nosso irmão, iremos e compraremos mantimento para o senhor.

[[v1-43-5]]

^<<v1-43-5,5>>^ Mas, se o senhor não o enviar, não iremos, pois o homem nos disse: "Vocês não verão o meu rosto, se o outro irmão não vier com vocês."

[[v1-43-6]]

^<<v1-43-6,6>>^ Israel respondeu: — Por que vocês me fizeram esse mal, dando a saber àquele homem que vocês tinham outro irmão?

[[v1-43-7]]

^<<v1-43-7,7>>^ Eles responderam: — O homem nos fez perguntas específicas a respeito de nós e de nossa parentela, dizendo: "O pai de vocês ainda é vivo? Vocês têm outro irmão?" Nós apenas respondemos o que ele nos perguntou. Como podíamos adivinhar que ele nos diria: "Tragam o outro irmão?"

[[v1-43-8]]

^<<v1-43-8,8>>^ Então Judá disse a Israel, seu pai: — Deixe o jovem ir comigo, e nos levantaremos e iremos, para que vivamos e não morramos, nem nós, nem o senhor, nem os nossos filhinhos.

[[v1-43-9]]

^<<v1-43-9,9>>^ Eu serei responsável por ele; da minha mão o senhor poderá requerê-lo. Se eu não o trouxer de volta e não o puser diante do senhor, serei culpado para com o senhor pelo resto da minha vida.

[[v1-43-10]]

^<<v1-43-10,10>>^ Se não nos tivéssemos demorado, já teríamos ido e voltado duas vezes.

[[v1-43-11]]

^<<v1-43-11,11>>^ Então Israel, seu pai, disse: — Se é assim, então façam o seguinte: peguem do mais precioso desta terra, ponham nos sacos para o mantimento e levem de presente a esse homem: um pouco de bálsamo e um pouco de mel, especiarias e mirra, nozes de pistácia e amêndoas.

[[v1-43-12]]

^<<v1-43-12,12>>^ Levem dinheiro em dobro. E devolvam o dinheiro restituído na boca dos sacos de cereal; é possível que tenha havido algum engano.

[[v1-43-13]]

^<<v1-43-13,13>>^ Levem também o irmão de vocês. Levantem-se e voltem àquele homem.

[[v1-43-14]]

^<<v1-43-14,14>>^ Deus Todo-Poderoso lhes dê misericórdia diante do homem, para que restitua o outro irmão e deixe que Benjamim volte com vocês. Quanto a mim, se eu perder os filhos, sem filhos ficarei.

[[v1-43-15]]

^<<v1-43-15,15>>^ Então os homens pegaram os presentes, o dinheiro em dobro e Benjamim; levantaram-se, foram ao Egito e se apresentaram diante de José.

[[v1-43-16]]

^<<v1-43-16,16>>^ Quando José viu que Benjamim estava com eles, disse ao administrador de sua casa: — Leve estes homens para casa, mate um animal e prepare tudo, pois estes homens comerão comigo ao meio-dia.

[[v1-43-17]]

^<<v1-43-17,17>>^ Ele fez como José lhe havia ordenado e levou os homens para a casa de José.

[[v1-43-18]]

^<<v1-43-18,18>>^ Os homens tiveram medo, porque foram levados à casa de José. E diziam: — É por causa do dinheiro que da outra vez voltou nos sacos de cereal que nós fomos trazidos para cá, para que possa nos acusar e atacar, nos escravizar e tomar os nossos jumentos.

[[v1-43-19]]

^<<v1-43-19,19>>^ E se aproximaram do administrador da casa de José, e lhe falaram à porta,

[[v1-43-20]]

^<<v1-43-20,20>>^ e disseram: — Meu senhor, já estivemos aqui uma vez para comprar mantimento.

[[v1-43-21]]

^<<v1-43-21,21>>^ Mas, quando chegamos à estalagem, ao abrir os sacos de cereal, eis que o dinheiro de cada um estava na boca do saco de cereal, nosso dinheiro intacto. Por isso, trouxemos esse dinheiro de volta.

[[v1-43-22]]

^<<v1-43-22,22>>^ Trouxemos também outro dinheiro conosco, para comprar mantimento. Não sabemos quem pôs o nosso dinheiro nos sacos de cereal.

[[v1-43-23]]

^<<v1-43-23,23>>^ O administrador disse: — Que a paz esteja com vocês! Não tenham medo. O seu Deus e o Deus do pai de vocês colocou esse tesouro nos sacos de cereal. Eu recebi o dinheiro que vocês trouxeram. Então ele trouxe Simeão para fora.

[[v1-43-24]]

^<<v1-43-24,24>>^ Depois, o administrador levou aqueles homens à casa de José e lhes deu água, e eles lavaram os pés. Também deu ração aos seus jumentos.

[[v1-43-25]]

^<<v1-43-25,25>>^ Então prepararam o presente, para quando José viesse ao meio-dia, pois ouviram que ali haviam de comer.

[[v1-43-26]]

^<<v1-43-26,26>>^ Quando José chegou à sua casa, trouxeram-lhe para dentro o presente que tinham em mãos e se inclinaram até o chão diante dele.

[[v1-43-27]]

^<<v1-43-27,27>>^ Ele lhes perguntou como tinham passado e disse: — O pai de vocês, aquele velho de quem me falaram, vai bem? Ainda vive?

[[v1-43-28]]

^<<v1-43-28,28>>^ Responderam: — O seu servo, nosso pai, vai bem e ainda vive. E abaixaram a cabeça e se inclinaram.

[[v1-43-29]]

^<<v1-43-29,29>>^ Quando José levantou os olhos, viu Benjamim, seu irmão, filho de sua mãe, e disse: — É este o irmão mais novo de vocês, de quem me falaram? E acrescentou: — Deus lhe conceda a sua graça, meu filho.

[[v1-43-30]]

^<<v1-43-30,30>>^ José, profundamente emocionado por causa do seu irmão, apressou-se e procurou um lugar onde chorar. Entrou no quarto e ali chorou.

[[v1-43-31]]

^<<v1-43-31,31>>^ Depois, lavou o rosto e saiu; conteve-se e disse: — Sirvam a refeição.

[[v1-43-32]]

^<<v1-43-32,32>>^ Serviram a comida dele numa mesa à parte, e a comida deles também numa mesa à parte. Também os egípcios que comiam com ele foram servidos numa mesa à parte, porque os egípcios não podiam comer com os hebreus, pois isso é abominação para os egípcios.

[[v1-43-33]]

^<<v1-43-33,33>>^ E sentaram-se diante dele por ordem de idade, desde o mais velho ao mais novo. Eles olhavam uns para os outros cheios de espanto.

[[v1-43-34]]

^<<v1-43-34,34>>^ Então José lhes apresentou as porções que estavam diante dele, e a porção de Benjamim era cinco vezes maior do que a dos outros. E beberam com ele até ficarem alegres.

'''

xref:001-genesis/001-genesis-042.adoc#v1-42-0[&#60; Capítulo Anterior] | <<v1-43-0,Topo>> | xref:001-genesis/001-genesis-044.adoc#v1-44-0[Próximo Capítulo &#62;]