include::./index.adoc[]

[[v1-15-0]]
=== Gênesis, 15
// naa ?, NAA - Nova Almeida Atualizada

[[v1-15-1]]

^<<v1-15-1,1>>^ Depois destes acontecimentos, a palavra do Senhor  veio a Abrão, numa visão, dizendo: — Não tenha medo, Abrão, eu sou o seu escudo, e lhe darei uma grande recompensa.

[[v1-15-2]]

^<<v1-15-2,2>>^ Abrão respondeu: — Senhor  Deus, que me darás, se continuo sem filhos e o herdeiro da minha casa é o damasceno Eliézer?

[[v1-15-3]]

^<<v1-15-3,3>>^ Abrão continuou: — Tu não me deste descendência, e um servo nascido na minha casa será o meu herdeiro.

[[v1-15-4]]

^<<v1-15-4,4>>^ E eis que a palavra do Senhor  veio a ele, dizendo: — Esse não será o seu herdeiro. Pelo contrário, aquele que será gerado por você, esse será o seu herdeiro.

[[v1-15-5]]

^<<v1-15-5,5>>^ Então o Senhor  levou-o para fora e disse: — Olhe para os céus e conte as estrelas, se puder contá-las. E lhe disse: — Assim será a sua posteridade.

[[v1-15-6]]

^<<v1-15-6,6>>^ Abrão creu no Senhor , e isso lhe foi atribuído para justiça.

[[v1-15-7]]

^<<v1-15-7,7>>^ O Senhor  disse também: — Eu sou o Senhor  que o tirei de Ur dos caldeus, para lhe dar esta terra como herança.

[[v1-15-8]]

^<<v1-15-8,8>>^ Mas Abrão perguntou: — Senhor  Deus, como saberei que vou herdar essa terra?

[[v1-15-9]]

^<<v1-15-9,9>>^ O Senhor  respondeu: — Traga-me uma novilha, uma cabra e um cordeiro, cada qual de três anos, uma rolinha e um pombinho.

[[v1-15-10]]

^<<v1-15-10,10>>^ Abrão trouxe todos esses animais, cortou-os pelo meio e pôs as metades umas diante das outras. As aves, porém, não cortou pelo meio.

[[v1-15-11]]

^<<v1-15-11,11>>^ Aves de rapina desciam sobre os cadáveres, porém Abrão as enxotava.

[[v1-15-12]]

^<<v1-15-12,12>>^ Ao pôr do sol, um profundo sono caiu sobre Abrão, e grande pavor e densas trevas tomaram conta dele.

[[v1-15-13]]

^<<v1-15-13,13>>^ Então o Senhor  lhe disse: — Fique sabendo, com certeza, que a sua posteridade será peregrina em terra alheia, será reduzida à escravidão e será afligida durante quatrocentos anos.

[[v1-15-14]]

^<<v1-15-14,14>>^ Mas eu castigarei a nação que os escravizar. Depois eles sairão com muitas riquezas.

[[v1-15-15]]

^<<v1-15-15,15>>^ E você irá para junto de seus pais em paz; será sepultado em boa velhice.

[[v1-15-16]]

^<<v1-15-16,16>>^ Na quarta geração, voltarão para cá; porque a medida da iniquidade dos amorreus ainda não se encheu.

[[v1-15-17]]

^<<v1-15-17,17>>^ Quando o sol se pôs e houve densas trevas, eis que um fogareiro fumegante e uma tocha de fogo passaram entre aqueles pedaços dos animais.

[[v1-15-18]]

^<<v1-15-18,18>>^ Naquele mesmo dia, o Senhor  fez aliança com Abrão, dizendo: — À sua descendência dei esta terra, desde o rio do Egito até o grande rio Eufrates:

[[v1-15-19]]

^<<v1-15-19,19>>^ a terra dos queneus, dos quenezeus, dos cadmoneus,

[[v1-15-20]]

^<<v1-15-20,20>>^ dos heteus, dos ferezeus, dos refains,

[[v1-15-21]]

^<<v1-15-21,21>>^ dos amorreus, dos cananeus, dos girgaseus e dos jebuseus.

'''

xref:001-genesis/001-genesis-014.adoc#v1-14-0[&#60; Capítulo Anterior] | <<v1-15-0,Topo>> | xref:001-genesis/001-genesis-016.adoc#v1-16-0[Próximo Capítulo &#62;]