include::./index.adoc[]

[[v1-3-0]]
=== Gênesis, 3
// naa ?, NAA - Nova Almeida Atualizada

[[v1-3-1]]

^<<v1-3-1,1>>^ Mas a serpente, mais astuta que todos os animais selvagens que o Senhor  Deus tinha feito, disse à mulher: — É verdade que Deus disse: "Não comam do fruto de nenhuma árvore do jardim"?

[[v1-3-2]]

^<<v1-3-2,2>>^ A mulher respondeu à serpente: — Do fruto das árvores do jardim podemos comer,

[[v1-3-3]]

^<<v1-3-3,3>>^ mas do fruto da árvore que está no meio do jardim, Deus disse: "Vocês não devem comer dele, nem tocar nele, para que não venham a morrer."

[[v1-3-4]]

^<<v1-3-4,4>>^ Então a serpente disse à mulher: — É certo que vocês não morrerão.

[[v1-3-5]]

^<<v1-3-5,5>>^ Porque Deus sabe que, no dia em que dele comerem, os olhos de vocês se abrirão e, como Deus, vocês serão conhecedores do bem e do mal.

[[v1-3-6]]

^<<v1-3-6,6>>^ Vendo a mulher que a árvore era boa para se comer, agradável aos olhos e árvore desejável para dar entendimento, tomou do seu fruto e comeu; e deu também ao marido, e ele comeu.

[[v1-3-7]]

^<<v1-3-7,7>>^ Então os olhos de ambos se abriram; e, percebendo que estavam nus, costuraram folhas de figueira e fizeram cintas para si.

[[v1-3-8]]

^<<v1-3-8,8>>^ Ao ouvirem a voz do Senhor  Deus, que andava no jardim quando soprava o vento suave da tarde, o homem e a sua mulher se esconderam da presença do Senhor  Deus, entre as árvores do jardim.

[[v1-3-9]]

^<<v1-3-9,9>>^ E o Senhor  Deus chamou o homem e lhe perguntou: — Onde você está?

[[v1-3-10]]

^<<v1-3-10,10>>^ Ele respondeu: — Ouvi a tua voz no jardim, e, porque estava nu, tive medo, e me escondi.

[[v1-3-11]]

^<<v1-3-11,11>>^ Deus perguntou: — Quem lhe disse que você estava nu? Você comeu da árvore da qual ordenei que não comesse?

[[v1-3-12]]

^<<v1-3-12,12>>^ Então o homem disse: — A mulher que me deste para estar comigo, ela me deu da árvore, e eu comi.

[[v1-3-13]]

^<<v1-3-13,13>>^ Então o Senhor  Deus disse à mulher: — Que é isso que você fez? A mulher respondeu: — A serpente me enganou, e eu comi.

[[v1-3-14]]

^<<v1-3-14,14>>^ Então o Senhor  Deus disse à serpente: — Por causa do que você fez, você é maldita entre todos os animais domésticos e entre todos os animais selvagens. Você rastejará sobre o seu ventre e comerá pó todos os dias da sua vida.

[[v1-3-15]]

^<<v1-3-15,15>>^ Porei inimizade entre você e a mulher, entre a sua descendência e o descendente dela. Este lhe ferirá a cabeça, e você lhe ferirá o calcanhar.

[[v1-3-16]]

^<<v1-3-16,16>>^ E à mulher ele disse: — Aumentarei em muito os seus sofrimentos na gravidez; com dor você dará à luz filhos. O seu desejo será para o seu marido, e ele a governará.

[[v1-3-17]]

^<<v1-3-17,17>>^ E a Adão disse: — Por ter dado ouvidos à voz de sua mulher e comido da árvore que eu havia ordenado que não comesse, maldita é a terra por sua causa; em fadigas você obterá dela o sustento durante os dias de sua vida.

[[v1-3-18]]

^<<v1-3-18,18>>^ Ela produzirá também espinhos e ervas daninhas, e você comerá a erva do campo.

[[v1-3-19]]

^<<v1-3-19,19>>^ No suor do seu rosto você comerá o seu pão, até que volte à terra, pois dela você foi formado; porque você é pó, e ao pó voltará.

[[v1-3-20]]

^<<v1-3-20,20>>^ E o homem deu à sua mulher o nome de Eva, por ser a mãe de todos os seres humanos.

[[v1-3-21]]

^<<v1-3-21,21>>^ O Senhor  Deus fez roupas de peles, com as quais vestiu Adão e sua mulher.

[[v1-3-22]]

^<<v1-3-22,22>>^ Então o Senhor  Deus disse: — Eis que o homem se tornou como um de nós, conhecedor do bem e do mal. É preciso impedir que estenda a mão, tome também da árvore da vida, coma e viva eternamente.

[[v1-3-23]]

^<<v1-3-23,23>>^ Por isso o Senhor  Deus o lançou fora do jardim do Éden, para cultivar a terra da qual havia sido tomado.

[[v1-3-24]]

^<<v1-3-24,24>>^ E, depois de lançar fora o homem, Deus colocou querubins a leste do jardim do Éden e uma espada flamejante que se movia em todas as direções, para guardar o caminho da árvore da vida.

'''

xref:001-genesis/001-genesis-002.adoc#v1-2-0[&#60; Capítulo Anterior] | <<v1-3-0,Topo>> | xref:001-genesis/001-genesis-004.adoc#v1-4-0[Próximo Capítulo &#62;]