include::./index.adoc[]

[[v1-37-0]]
=== Gênesis, 37
// naa ?, NAA - Nova Almeida Atualizada

[[v1-37-1]]

^<<v1-37-1,1>>^ Jacó habitou na terra das peregrinações de seu pai, na terra de Canaã.

[[v1-37-2]]

^<<v1-37-2,2>>^ Esta é a história de Jacó. Quando José tinha dezessete anos, apascentava os rebanhos com os seus irmãos. Sendo ainda jovem, acompanhava os filhos de Bila e os filhos de Zilpa, mulheres de seu pai; e trazia más notícias deles a seu pai.

[[v1-37-3]]

^<<v1-37-3,3>>^ Ora, Israel amava mais José do que todos os seus outros filhos, porque era filho da sua velhice; e mandou fazer para ele uma túnica talar de mangas compridas.

[[v1-37-4]]

^<<v1-37-4,4>>^ Quando os seus irmãos viram que o pai o amava mais do que todos os outros filhos, odiaram-no e já não podiam falar com ele de forma pacífica.

[[v1-37-5]]

^<<v1-37-5,5>>^ José teve um sonho e o contou aos seus irmãos; por isso, o odiaram ainda mais.

[[v1-37-6]]

^<<v1-37-6,6>>^ Ele lhes disse: — Peço que ouçam o sonho que tive.

[[v1-37-7]]

^<<v1-37-7,7>>^ Sonhei que estávamos amarrando feixes no campo, e eis que o meu feixe se levantou e ficou em pé, enquanto os feixes de vocês o rodeavam e se inclinavam diante do meu.

[[v1-37-8]]

^<<v1-37-8,8>>^ Então os irmãos lhe disseram: — Você pensa que vai mesmo reinar sobre nós? Pensa que realmente dominará sobre nós? E com isso o odiavam ainda mais, por causa dos seus sonhos e de suas palavras.

[[v1-37-9]]

^<<v1-37-9,9>>^ José teve ainda outro sonho, que ele contou aos seus irmãos, dizendo: — Sonhei também que o sol, a lua e onze estrelas se inclinavam diante de mim.

[[v1-37-10]]

^<<v1-37-10,10>>^ Quando José contou esse sonho ao pai e aos seus irmãos, o pai o repreendeu, dizendo: — Que sonho é esse que você teve? Você está querendo dizer que eu, a sua mãe e os seus irmãos iremos e nos inclinaremos até o chão diante de você?

[[v1-37-11]]

^<<v1-37-11,11>>^ Os irmãos tinham inveja dele; o pai, no entanto, guardou aquilo no coração.

[[v1-37-12]]

^<<v1-37-12,12>>^ Como os irmãos foram apascentar o rebanho do pai, em Siquém,

[[v1-37-13]]

^<<v1-37-13,13>>^ Israel perguntou a José: — Os seus irmãos não estão apascentando o rebanho em Siquém? Venha, pois vou mandar você até eles. José respondeu: — Eis-me aqui.

[[v1-37-14]]

^<<v1-37-14,14>>^ Israel continuou: — Vá, agora, e veja se está tudo bem com os seus irmãos e com o rebanho; e traga-me notícias. Assim, o enviou do vale de Hebrom, e ele foi a Siquém.

[[v1-37-15]]

^<<v1-37-15,15>>^ E um homem encontrou José, que andava errante pelo campo, e lhe perguntou: — O que você está procurando?

[[v1-37-16]]

^<<v1-37-16,16>>^ Ele respondeu: — Estou procurando os meus irmãos. Por favor, pode me dizer onde eles estão apascentando o rebanho?

[[v1-37-17]]

^<<v1-37-17,17>>^ O homem respondeu: — Foram embora daqui. Ouvi quando disseram: "Vamos a Dotã." Então José seguiu atrás dos irmãos e os encontrou em Dotã.

[[v1-37-18]]

^<<v1-37-18,18>>^ De longe eles o viram e, antes que chegasse, conspiraram contra ele para o matar.

[[v1-37-19]]

^<<v1-37-19,19>>^ Disseram uns aos outros: — Lá vem o grande sonhador!

[[v1-37-20]]

^<<v1-37-20,20>>^ Venham, pois, agora, vamos matá-lo e jogar o corpo numa destas cisternas. Diremos que um animal selvagem o devorou. Vejamos em que vão dar os sonhos dele.

[[v1-37-21]]

^<<v1-37-21,21>>^ Mas Rúben, ouvindo isso, livrou-o das mãos deles e disse: — Não lhe tiremos a vida.

[[v1-37-22]]

^<<v1-37-22,22>>^ Rúben disse mais: — Não derramem sangue. Joguem o rapaz naquela cisterna que está no deserto, e não lhe façam mal. Rúben disse isto para o livrar deles, a fim de levá-lo de volta ao pai.

[[v1-37-23]]

^<<v1-37-23,23>>^ Mas, logo que José chegou a seus irmãos, despiram-no da túnica, a túnica talar de mangas compridas que trazia,

[[v1-37-24]]

^<<v1-37-24,24>>^ e o jogaram na cisterna. A cisterna estava vazia, sem água.

[[v1-37-25]]

^<<v1-37-25,25>>^ Depois sentaram-se para comer. Levantando os olhos, viram que uma caravana de ismaelitas vinha de Gileade. Seus camelos traziam especiarias, bálsamo e mirra, que levavam para o Egito.

[[v1-37-26]]

^<<v1-37-26,26>>^ Então Judá disse aos irmãos: — O que vamos ganhar se matarmos o nosso irmão e depois escondermos a sua morte?

[[v1-37-27]]

^<<v1-37-27,27>>^ Venham, vamos vendê-lo aos ismaelitas. Não lhe façamos mal, pois é nosso irmão, é do nosso sangue. Seus irmãos concordaram.

[[v1-37-28]]

^<<v1-37-28,28>>^ E, quando os mercadores midianitas passaram, os irmãos de José o tiraram da cisterna e o venderam aos ismaelitas por vinte moedas de prata. E os ismaelitas levaram José para o Egito.

[[v1-37-29]]

^<<v1-37-29,29>>^ Quando Rúben voltou à cisterna, eis que José não estava nela; então rasgou as suas roupas.

[[v1-37-30]]

^<<v1-37-30,30>>^ E, voltando aos seus irmãos, disse: — O rapaz não está mais lá! E agora, o que eu vou fazer?

[[v1-37-31]]

^<<v1-37-31,31>>^ Então pegaram a túnica de José, mataram um bode e molharam a túnica no sangue.

[[v1-37-32]]

^<<v1-37-32,32>>^ E enviaram a túnica de mangas compridas ao pai com este recado: — Achamos isto. Veja se é ou não a túnica de seu filho.

[[v1-37-33]]

^<<v1-37-33,33>>^ Ele a reconheceu e disse: — É a túnica de meu filho. Um animal selvagem o devorou. Certamente José foi despedaçado.

[[v1-37-34]]

^<<v1-37-34,34>>^ Então Jacó rasgou as suas roupas, vestiu-se de pano de saco e lamentou o filho durante muitos dias.

[[v1-37-35]]

^<<v1-37-35,35>>^ Todos os seus filhos e todas as suas filhas vieram, para o consolar; ele, porém, recusou ser consolado e disse: — Chorando, descerei à sepultura para junto do meu filho. E continuou a chorar pelo filho.

[[v1-37-36]]

^<<v1-37-36,36>>^ Enquanto isso, no Egito, os midianitas venderam José a Potifar, oficial de Faraó, comandante da guarda.

'''

xref:001-genesis/001-genesis-036.adoc#v1-36-0[&#60; Capítulo Anterior] | <<v1-37-0,Topo>> | xref:001-genesis/001-genesis-038.adoc#v1-38-0[Próximo Capítulo &#62;]