include::./index.adoc[]

[[v1-7-0]]
=== Gênesis, 7
// naa ?, NAA - Nova Almeida Atualizada

[[v1-7-1]]

^<<v1-7-1,1>>^ O Senhor  disse a Noé: — Entre na arca, você e toda a sua família, porque reconheço que você tem sido justo diante de mim no meio desta geração.

[[v1-7-2]]

^<<v1-7-2,2>>^ De todo animal puro leve com você sete pares: o macho e sua fêmea. Mas dos animais impuros leve um par: o macho e sua fêmea.

[[v1-7-3]]

^<<v1-7-3,3>>^ Também das aves dos céus leve sete pares: macho e fêmea, para se conservar a semente sobre a face da terra.

[[v1-7-4]]

^<<v1-7-4,4>>^ Porque, daqui a sete dias, farei chover sobre a terra durante quarenta dias e quarenta noites; e farei desaparecer da superfície da terra todos os seres que fiz.

[[v1-7-5]]

^<<v1-7-5,5>>^ E Noé fez tudo como o Senhor  lhe havia ordenado.

[[v1-7-6]]

^<<v1-7-6,6>>^ Noé tinha seiscentos anos de idade quando as águas do dilúvio inundaram a terra.

[[v1-7-7]]

^<<v1-7-7,7>>^ Por causa das águas do dilúvio, Noé entrou na arca, ele com os seus filhos, a sua mulher e as mulheres dos seus filhos.

[[v1-7-8]]

^<<v1-7-8,8>>^ Dos animais puros, dos animais impuros, das aves e de todo animal que rasteja sobre a terra,

[[v1-7-9]]

^<<v1-7-9,9>>^ entraram para junto de Noé, na arca, de dois em dois, macho e fêmea, como Deus havia ordenado a Noé.

[[v1-7-10]]

^<<v1-7-10,10>>^ E aconteceu que, depois de sete dias, vieram sobre a terra as águas do dilúvio.

[[v1-7-11]]

^<<v1-7-11,11>>^ No ano seiscentos da vida de Noé, aos dezessete dias do segundo mês, nesse dia romperam-se todas as fontes do grande abismo, e as comportas dos céus se abriram,

[[v1-7-12]]

^<<v1-7-12,12>>^ e caiu chuva sobre a terra durante quarenta dias e quarenta noites.

[[v1-7-13]]

^<<v1-7-13,13>>^ Nesse mesmo dia entraram na arca Noé, os seus filhos Sem, Cam e Jafé, a mulher dele e as mulheres dos seus filhos.

[[v1-7-14]]

^<<v1-7-14,14>>^ Entraram eles e todos os animais segundo as suas espécies, todo gado segundo as suas espécies, todos os animais que rastejam sobre a terra segundo as suas espécies, todas as aves segundo as suas espécies, todos os pássaros e tudo o que tem asa.

[[v1-7-15]]

^<<v1-7-15,15>>^ De todos os seres em que havia fôlego de vida, entraram na arca de dois em dois, para junto de Noé;

[[v1-7-16]]

^<<v1-7-16,16>>^ eram macho e fêmea os que entraram de todos os seres vivos, como Deus havia ordenado a Noé; e o Senhor  fechou a porta da arca.

[[v1-7-17]]

^<<v1-7-17,17>>^ O dilúvio durou quarenta dias sobre a terra. As águas subiram e elevaram a arca sobre a terra.

[[v1-7-18]]

^<<v1-7-18,18>>^ As águas prevaleceram e aumentaram muito na terra; a arca, porém, flutuava sobre as águas.

[[v1-7-19]]

^<<v1-7-19,19>>^ As águas prevaleceram excessivamente sobre a terra e cobriram todos os altos montes que havia debaixo do céu.

[[v1-7-20]]

^<<v1-7-20,20>>^ As águas ficaram sete metros acima deles; e os montes foram cobertos.

[[v1-7-21]]

^<<v1-7-21,21>>^ E morreram todos os seres vivos que se moviam sobre a terra: aves, animais domésticos, animais selvagens, e todos os enxames de criaturas que povoam a terra, e todos os seres humanos.

[[v1-7-22]]

^<<v1-7-22,22>>^ Tudo o que havia em terra seca e que tinha fôlego de vida em suas narinas morreu.

[[v1-7-23]]

^<<v1-7-23,23>>^ Assim, foram exterminados todos os seres que havia sobre a face da terra: as pessoas e os animais, os seres que rastejam e as aves dos céus foram extintos da terra; ficou somente Noé e os que com ele estavam na arca.

[[v1-7-24]]

^<<v1-7-24,24>>^ E as águas prevaleceram sobre a terra durante cento e cinquenta dias.

'''

xref:001-genesis/001-genesis-006.adoc#v1-6-0[&#60; Capítulo Anterior] | <<v1-7-0,Topo>> | xref:001-genesis/001-genesis-008.adoc#v1-8-0[Próximo Capítulo &#62;]