include::./index.adoc[]

[[v1-50-0]]
=== Gênesis, 50
// naa ?, NAA - Nova Almeida Atualizada

[[v1-50-1]]

^<<v1-50-1,1>>^ Então José se lançou sobre o rosto de seu pai, chorou sobre ele e o beijou.

[[v1-50-2]]

^<<v1-50-2,2>>^ José ordenou a seus servos, aos que eram médicos, que embalsamassem o corpo de seu pai. E os médicos embalsamaram Israel,

[[v1-50-3]]

^<<v1-50-3,3>>^ gastando nisso quarenta dias, pois assim se cumprem os dias do embalsamamento; e os egípcios ficaram de luto setenta dias.

[[v1-50-4]]

^<<v1-50-4,4>>^ Passados os dias de luto, José falou à casa de Faraó: — Se agora encontrei favor diante de vocês, peço que falem aos ouvidos de Faraó, dizendo:

[[v1-50-5]]

^<<v1-50-5,5>>^ "Meu pai me fez jurar, declarando: ‘Eis que estou morrendo; sepulte-me no túmulo que abri para mim na terra de Canaã.’ Agora, quero ir e sepultar meu pai; depois voltarei."

[[v1-50-6]]

^<<v1-50-6,6>>^ Faraó respondeu: — Vá e sepulte o seu pai como ele fez você jurar.

[[v1-50-7]]

^<<v1-50-7,7>>^ José partiu para sepultar o seu pai. Com ele foram todos os oficiais de Faraó, os principais da sua casa e todos os principais da terra do Egito,

[[v1-50-8]]

^<<v1-50-8,8>>^ bem como toda a casa de José, e seus irmãos, e a casa de seu pai. Deixaram na terra de Gósen somente as crianças, os rebanhos e o gado.

[[v1-50-9]]

^<<v1-50-9,9>>^ E foram também com ele tanto carruagens como cavaleiros; e o cortejo foi muito grande.

[[v1-50-10]]

^<<v1-50-10,10>>^ Quando eles chegaram à eira de Atade, que fica do outro lado do Jordão, fizeram ali grande e intensa lamentação; e José pranteou seu pai durante sete dias.

[[v1-50-11]]

^<<v1-50-11,11>>^ Quando os moradores da terra, os cananeus, viram o luto na eira de Atade, disseram: — Como é grande este pranto dos egípcios! E por isso aquele lugar foi chamado de Abel-Mizraim; fica do outro lado do Jordão.

[[v1-50-12]]

^<<v1-50-12,12>>^ Os filhos de Jacó fizeram como ele lhes havia ordenado:

[[v1-50-13]]

^<<v1-50-13,13>>^ levaram-no para a terra de Canaã e o sepultaram na caverna do campo de Macpela, que, juntamente com o campo, Abraão havia comprado de Efrom, o heteu, para ser lugar de sepultura. Esse lugar fica em frente a Manre.

[[v1-50-14]]

^<<v1-50-14,14>>^ Depois disso, José voltou para o Egito, ele, os seus irmãos e todos os que o haviam acompanhado para sepultar o seu pai.

[[v1-50-15]]

^<<v1-50-15,15>>^ Vendo os irmãos de José que seu pai já era morto, disseram: — É possível que José tenha ódio de nós; certamente nos retribuirá todo o mal que lhe fizemos.

[[v1-50-16]]

^<<v1-50-16,16>>^ Por isso, mandaram dizer a José: — O seu pai, antes de morrer, ordenou o seguinte:

[[v1-50-17]]

^<<v1-50-17,17>>^ "É isto que vocês dirão a José: ‘Perdoe, por favor, a transgressão dos seus irmãos e o pecado que cometeram, porque eles lhe fizeram mal.’" Agora pedimos que perdoe a transgressão dos servos do Deus de seu pai. Ao ouvir estas palavras, José chorou.

[[v1-50-18]]

^<<v1-50-18,18>>^ Depois, vieram também os seus irmãos, prostraram-se diante dele e disseram: — Eis-nos aqui; somos seus servos.

[[v1-50-19]]

^<<v1-50-19,19>>^ Mas José respondeu: — Não tenham medo; será que eu estou no lugar de Deus?

[[v1-50-20]]

^<<v1-50-20,20>>^ Vocês, na verdade, planejaram o mal contra mim; porém Deus o tornou em bem, para fazer, como estão vendo agora, que se conserve a vida de muita gente.

[[v1-50-21]]

^<<v1-50-21,21>>^ Portanto, não tenham medo; eu sustentarei vocês e os seus filhos. E assim José os consolou e lhes falou ao coração.

[[v1-50-22]]

^<<v1-50-22,22>>^ José ficou morando no Egito, ele e a casa de seu pai. Viveu cento e dez anos.

[[v1-50-23]]

^<<v1-50-23,23>>^ José viu os filhos de Efraim até a terceira geração; também os filhos de Maquir, filho de Manassés, os quais José tomou sobre os seus joelhos.

[[v1-50-24]]

^<<v1-50-24,24>>^ José disse a seus irmãos: — Eu vou morrer em breve. Mas Deus certamente visitará vocês e fará com que saiam desta terra para ir à terra que jurou dar a Abraão, a Isaque e a Jacó.

[[v1-50-25]]

^<<v1-50-25,25>>^ José pediu aos filhos de Israel que fizessem um juramento, dizendo: — Deus certamente visitará vocês. Quando isso acontecer, levem os meus ossos daqui.

[[v1-50-26]]

^<<v1-50-26,26>>^ José morreu com a idade de cento e dez anos. Eles embalsamaram o seu corpo e o puseram num caixão, no Egito.

'''

xref:001-genesis/001-genesis-049.adoc#v1-49-0[&#60; Capítulo Anterior] | <<v1-50-0,Topo>> | xref:002-exodo/002-exodo-001.adoc#v2-1-0[Próximo Capítulo &#62;]