include::./index.adoc[]

[[v1-29-0]]
=== Gênesis, 29
// naa ?, NAA - Nova Almeida Atualizada

[[v1-29-1]]

^<<v1-29-1,1>>^ Jacó se pôs a caminho e foi à terra do povo do Oriente.

[[v1-29-2]]

^<<v1-29-2,2>>^ Olhou, e eis um poço no campo e três rebanhos de ovelhas deitados junto dele, porque daquele poço davam de beber aos rebanhos. E havia uma grande pedra que tapava a boca do poço.

[[v1-29-3]]

^<<v1-29-3,3>>^ Ajuntavam-se ali todos os rebanhos, os pastores removiam a pedra da boca do poço, davam de beber às ovelhas e tornavam a colocá-la no seu devido lugar.

[[v1-29-4]]

^<<v1-29-4,4>>^ Jacó perguntou aos pastores: — De onde são vocês, meus irmãos? Responderam: — Somos de Harã.

[[v1-29-5]]

^<<v1-29-5,5>>^ Perguntou-lhes: — Vocês conhecem Labão, filho de Naor? Responderam: — Conhecemos.

[[v1-29-6]]

^<<v1-29-6,6>>^ Jacó perguntou ainda: — Ele vai bem? Eles responderam: — Sim, vai bem. Olhe! Raquel, a filha dele, vem vindo aí com as ovelhas.

[[v1-29-7]]

^<<v1-29-7,7>>^ Então Jacó disse: — É ainda pleno dia, não é tempo de recolher os rebanhos. Deem de beber às ovelhas e vão apascentá-las.

[[v1-29-8]]

^<<v1-29-8,8>>^ Mas eles responderam: — Não podemos, enquanto não se ajuntarem todos os rebanhos, seja removida a pedra da boca do poço e demos de beber às ovelhas.

[[v1-29-9]]

^<<v1-29-9,9>>^ Enquanto Jacó ainda falava, chegou Raquel com as ovelhas de seu pai, porque era pastora.

[[v1-29-10]]

^<<v1-29-10,10>>^ Quando Jacó viu Raquel, filha de Labão, irmão de sua mãe, e as ovelhas de Labão, aproximou-se, removeu a pedra da boca do poço e deu de beber ao rebanho de Labão, irmão de sua mãe.

[[v1-29-11]]

^<<v1-29-11,11>>^ Feito isso, Jacó beijou Raquel e, erguendo a voz, chorou.

[[v1-29-12]]

^<<v1-29-12,12>>^ Então Jacó contou a Raquel que ele era parente de seu pai, pois era filho de Rebeca. Ela correu e o comunicou a seu pai.

[[v1-29-13]]

^<<v1-29-13,13>>^ Quando Labão ouviu as novas de Jacó, filho de sua irmã, correu ao encontro dele, abraçou-o, beijou-o e o levou para casa. E Jacó contou a Labão tudo o que havia acontecido.

[[v1-29-14]]

^<<v1-29-14,14>>^ Então Labão disse: — De fato, você é meu osso e minha carne. Jacó ficou na casa de Labão durante um mês.

[[v1-29-15]]

^<<v1-29-15,15>>^ Depois, Labão disse a Jacó: — Será que você vai trabalhar de graça, só por ser meu parente? Diga-me qual deve ser o seu salário.

[[v1-29-16]]

^<<v1-29-16,16>>^ Ora, Labão tinha duas filhas: Lia, a mais velha, e Raquel, a mais nova.

[[v1-29-17]]

^<<v1-29-17,17>>^ Lia tinha uns olhos sem brilho, porém Raquel era bonita e formosa.

[[v1-29-18]]

^<<v1-29-18,18>>^ Como Jacó amava Raquel, disse a Labão: — Trabalharei para o senhor durante sete anos para poder casar com Raquel, sua filha mais nova.

[[v1-29-19]]

^<<v1-29-19,19>>^ Labão respondeu: — É melhor dá-la a você do que a outro homem. Fique aqui comigo.

[[v1-29-20]]

^<<v1-29-20,20>>^ Assim, por amor a Raquel, Jacó trabalhou durante sete anos. E esses anos lhe pareceram como poucos dias, pelo muito que a amava.

[[v1-29-21]]

^<<v1-29-21,21>>^ Então ele disse a Labão: — Dê-me a minha mulher, pois já venceu o prazo, para que eu me case com ela.

[[v1-29-22]]

^<<v1-29-22,22>>^ Assim, Labão reuniu todos os homens do lugar e deu um banquete.

[[v1-29-23]]

^<<v1-29-23,23>>^ À noite, ele trouxe Lia, sua filha, e a entregou a Jacó. E eles tiveram relações.

[[v1-29-24]]

^<<v1-29-24,24>>^ (Labão tinha dado sua serva Zilpa para que fosse serva de Lia, sua filha.)

[[v1-29-25]]

^<<v1-29-25,25>>^ Ao amanhecer, Jacó viu que era Lia. Por isso, disse a Labão: — O que é isso que o senhor fez comigo? Não é verdade que eu trabalhei por amor a Raquel? Por que, então, o senhor me enganou?

[[v1-29-26]]

^<<v1-29-26,26>>^ Labão respondeu: — Em nossa terra não se costuma dar em casamento a mais nova antes da primogênita.

[[v1-29-27]]

^<<v1-29-27,27>>^ Complete a semana de festa de casamento da primogênita. Depois, daremos a você também a outra, pelo trabalho de mais sete anos que você ainda me servirá.

[[v1-29-28]]

^<<v1-29-28,28>>^ Jacó fez o que Labão pediu e completou a semana de festa da primogênita. Depois, Labão lhe deu por mulher a sua filha Raquel.

[[v1-29-29]]

^<<v1-29-29,29>>^ (Labão tinha dado sua serva Bila para que fosse serva de Raquel, sua filha.)

[[v1-29-30]]

^<<v1-29-30,30>>^ E Jacó teve relações também com Raquel. Ele amava Raquel mais do que amava Lia. E continuou trabalhando para Labão durante mais sete anos.

[[v1-29-31]]

^<<v1-29-31,31>>^ Quando o Senhor  viu que Lia era desprezada, fez com que ela fosse fecunda, ao passo que Raquel era estéril.

[[v1-29-32]]

^<<v1-29-32,32>>^ Assim, Lia ficou grávida e deu à luz um filho, a quem deu o nome de Rúben, pois disse: — O Senhor  viu a minha aflição. Por isso, agora meu marido vai me amar.

[[v1-29-33]]

^<<v1-29-33,33>>^ Ela ficou grávida outra vez e deu à luz um filho. E disse: — O Senhor  ouviu que eu era desprezada e me deu mais este filho. E deu-lhe o nome de Simeão.

[[v1-29-34]]

^<<v1-29-34,34>>^ Lia ficou grávida ainda outra vez e deu à luz um filho. E disse: — Agora, desta vez, o meu marido se unirá mais a mim, porque lhe dei à luz três filhos. Por isso lhe deu o nome de Levi.

[[v1-29-35]]

^<<v1-29-35,35>>^ Mais uma vez ela ficou grávida e deu à luz um filho. Então disse: — Desta vez louvarei o Senhor . E por isso lhe deu o nome de Judá. E depois disso não teve mais filhos.

'''

xref:001-genesis/001-genesis-028.adoc#v1-28-0[&#60; Capítulo Anterior] | <<v1-29-0,Topo>> | xref:001-genesis/001-genesis-030.adoc#v1-30-0[Próximo Capítulo &#62;]