include::./index.adoc[]

[[v1-18-0]]
=== Gênesis, 18
// naa ?, NAA - Nova Almeida Atualizada

[[v1-18-1]]

^<<v1-18-1,1>>^ O Senhor  apareceu a Abraão nos carvalhais de Manre, quando ele estava assentado à entrada da tenda, no maior calor do dia.

[[v1-18-2]]

^<<v1-18-2,2>>^ Abraão levantou os olhos, olhou, e eis que três homens estavam em pé diante dele. Ao vê-los, Abraão correu da porta da tenda ao encontro deles, prostrou-se em terra

[[v1-18-3]]

^<<v1-18-3,3>>^ e disse: — Senhor meu, se eu puder obter favor diante de seus olhos, peço que não passe adiante sem ficar um pouco com este seu servo.

[[v1-18-4]]

^<<v1-18-4,4>>^ Vou pedir que se traga um pouco de água, para que lavem os pés e descansem debaixo desta árvore.

[[v1-18-5]]

^<<v1-18-5,5>>^ Trarei um pouco de comida, para que refaçam as forças, visto que chegaram até este servo de vocês; depois, poderão seguir adiante. Responderam: — Faça como você disse.

[[v1-18-6]]

^<<v1-18-6,6>>^ Abraão correu para a tenda de Sara e lhe disse: — Amasse depressa três medidas da melhor farinha e faça pão.

[[v1-18-7]]

^<<v1-18-7,7>>^ Abraão, por sua vez, correu ao gado, pegou um novilho tenro e bom, e o entregou a um empregado, que se apressou em prepará-lo.

[[v1-18-8]]

^<<v1-18-8,8>>^ Pegou também coalhada e leite e o novilho que tinha mandado preparar e pôs tudo diante deles; e permaneceu em pé junto a eles debaixo da árvore; e eles comeram.

[[v1-18-9]]

^<<v1-18-9,9>>^ Então lhe perguntaram: — Onde está Sara, a sua mulher? Ele respondeu: — Está aí na tenda.

[[v1-18-10]]

^<<v1-18-10,10>>^ Um deles disse: — Certamente voltarei a você, daqui a um ano; e Sara, a sua mulher, dará à luz um filho. Sara estava escutando, à porta da tenda, atrás de Abraão.

[[v1-18-11]]

^<<v1-18-11,11>>^ Abraão e Sara já eram velhos, avançados em idade; e a Sara já lhe havia cessado o costume das mulheres.

[[v1-18-12]]

^<<v1-18-12,12>>^ Por isso Sara riu em seu íntimo, dizendo consigo mesma: — Depois de velha, e velho também o meu senhor, terei ainda prazer?

[[v1-18-13]]

^<<v1-18-13,13>>^ Então o Senhor  perguntou a Abraão: — Por que Sara riu, dizendo: "Será verdade que darei ainda à luz, sendo velha?"

[[v1-18-14]]

^<<v1-18-14,14>>^ Por acaso, existe algo demasiadamente difícil para o Senhor ? Daqui a um ano, neste mesmo tempo, voltarei a você, e Sara terá um filho.

[[v1-18-15]]

^<<v1-18-15,15>>^ Então Sara teve medo e negou, dizendo: — Eu não ri. Ele, porém, disse: — Não é verdade; é certo que você riu.

[[v1-18-16]]

^<<v1-18-16,16>>^ Quando aqueles homens se levantaram dali, olharam para Sodoma; e Abraão ia com eles, para os encaminhar.

[[v1-18-17]]

^<<v1-18-17,17>>^ O Senhor  disse: — Será que eu devo esconder de Abraão o que estou para fazer,

[[v1-18-18]]

^<<v1-18-18,18>>^ visto que Abraão certamente virá a ser uma grande e poderosa nação, e nele serão benditas todas as nações da terra?

[[v1-18-19]]

^<<v1-18-19,19>>^ Porque eu o escolhi para que ordene aos seus filhos e a sua casa depois dele, a fim de que guardem o caminho do Senhor  e pratiquem a justiça e o juízo, para que o Senhor  faça vir sobre Abraão o que lhe prometeu.

[[v1-18-20]]

^<<v1-18-20,20>>^ Então o Senhor  disse: — O clamor contra Sodoma e Gomorra tem aumentado, e o seu pecado é gravíssimo.

[[v1-18-21]]

^<<v1-18-21,21>>^ Descerei e verei se, de fato, o que têm praticado corresponde a esse clamor que veio até mim. E, se este não for o caso, eu ficarei sabendo.

[[v1-18-22]]

^<<v1-18-22,22>>^ Assim, aqueles homens partiram dali e foram para Sodoma; mas Abraão ainda permaneceu na presença do Senhor .

[[v1-18-23]]

^<<v1-18-23,23>>^ E, aproximando-se, Abraão perguntou: — Será que vais destruir o justo com o ímpio?

[[v1-18-24]]

^<<v1-18-24,24>>^ Se houver, por acaso, cinquenta justos na cidade, ainda assim destruirás e não pouparás o lugar por amor dos cinquenta justos que nela se encontram?

[[v1-18-25]]

^<<v1-18-25,25>>^ Longe de ti fazeres tal coisa: matar o justo com o ímpio, como se o justo fosse igual ao ímpio. Longe de ti! Será que o Juiz de toda a terra não faria justiça?

[[v1-18-26]]

^<<v1-18-26,26>>^ Então o Senhor  disse: — Se eu encontrar cinquenta justos dentro da cidade de Sodoma, pouparei a cidade toda por amor a eles.

[[v1-18-27]]

^<<v1-18-27,27>>^ Abraão continuou: — Eis que me atrevi a falar ao Senhor, eu que sou pó e cinza.

[[v1-18-28]]

^<<v1-18-28,28>>^ Caso faltarem cinco para cinquenta justos, destruirás por isso toda a cidade? Deus respondeu: — Não a destruirei se eu encontrar ali quarenta e cinco.

[[v1-18-29]]

^<<v1-18-29,29>>^ Então Abraão disse: — E se, por acaso, houver ali apenas quarenta? Deus respondeu: — Não o farei por amor aos quarenta.

[[v1-18-30]]

^<<v1-18-30,30>>^ Abraão insistiu: — Não se ire o Senhor, se eu continuar a falar. E se houver ali apenas trinta? O Senhor  respondeu: — Não o farei se eu encontrar ali trinta.

[[v1-18-31]]

^<<v1-18-31,31>>^ Abraão continuou: — Eis que me atrevi a falar ao Senhor. E se, por acaso, houver ali apenas vinte? O Senhor  respondeu: — Não a destruirei por amor aos vinte.

[[v1-18-32]]

^<<v1-18-32,32>>^ Finalmente Abraão disse: — Não se ire o Senhor, se lhe falo somente mais esta vez. E se, por acaso, houver ali apenas dez? O Senhor  respondeu: — Não a destruirei por amor aos dez.

[[v1-18-33]]

^<<v1-18-33,33>>^ Quando acabou de falar com Abraão, o Senhor  se retirou, e Abraão voltou para onde estava antes.

'''

xref:001-genesis/001-genesis-017.adoc#v1-17-0[&#60; Capítulo Anterior] | <<v1-18-0,Topo>> | xref:001-genesis/001-genesis-019.adoc#v1-19-0[Próximo Capítulo &#62;]