include::./index.adoc[]

[[v1-32-0]]
=== Gênesis, 32
// naa ?, NAA - Nova Almeida Atualizada

[[v1-32-1]]

^<<v1-32-1,1>>^ Também Jacó seguiu o seu caminho, e anjos de Deus foram encontrar-se com ele.

[[v1-32-2]]

^<<v1-32-2,2>>^ Quando Jacó os viu, disse: — Este é o acampamento de Deus. E deu àquele lugar o nome de Maanaim.

[[v1-32-3]]

^<<v1-32-3,3>>^ Então Jacó enviou mensageiros adiante de si a Esaú, seu irmão, à terra de Seir, território de Edom.

[[v1-32-4]]

^<<v1-32-4,4>>^ E lhes deu esta ordem: — Assim vocês falarão a meu senhor Esaú: "O seu servo Jacó manda dizer isto: ‘Como estrangeiro morei com Labão, em cuja companhia fiquei até agora.

[[v1-32-5]]

^<<v1-32-5,5>>^ Tenho bois, jumentos, rebanhos, servos e servas. Envio este comunicado a meu senhor, para encontrar favor na sua presença.’"

[[v1-32-6]]

^<<v1-32-6,6>>^ Os mensageiros voltaram a Jacó, dizendo: — Fomos até o seu irmão Esaú. Também ele está vindo para se encontrar com o senhor, e quatrocentos homens estão com ele.

[[v1-32-7]]

^<<v1-32-7,7>>^ Então Jacó teve medo e ficou angustiado. Dividiu em dois grupos o povo que estava com ele, e também os rebanhos, os bois e os camelos.

[[v1-32-8]]

^<<v1-32-8,8>>^ Pois pensou: "Se Esaú vier e atacar um grupo, o outro grupo escapará."

[[v1-32-9]]

^<<v1-32-9,9>>^ E Jacó orou: — Deus de meu pai Abraão e Deus de meu pai Isaque, ó Senhor , que me disseste: "Volte para a sua terra e para a sua parentela, e eu farei bem a você",

[[v1-32-10]]

^<<v1-32-10,10>>^ sou indigno de todas as misericórdias e de toda a fidelidade que tens usado para com o teu servo. Pois com apenas o meu cajado atravessei este Jordão; já agora sou dois grupos.

[[v1-32-11]]

^<<v1-32-11,11>>^ Livra-me das mãos de meu irmão Esaú, porque temo que ele venha e ataque a mim e às mães com os filhos.

[[v1-32-12]]

^<<v1-32-12,12>>^ Pois tu disseste: "Certamente serei bondoso com você e lhe darei uma descendência como a areia do mar, que, de tão numerosa, não se pode contar."

[[v1-32-13]]

^<<v1-32-13,13>>^ Depois de passar ali aquela noite, Jacó separou do que tinha consigo um presente para o seu irmão Esaú:

[[v1-32-14]]

^<<v1-32-14,14>>^ duzentas cabras e vinte bodes, duzentas ovelhas e vinte carneiros,

[[v1-32-15]]

^<<v1-32-15,15>>^ trinta camelas de leite com as suas crias, quarenta vacas e dez touros, vinte jumentas e dez jumentinhos.

[[v1-32-16]]

^<<v1-32-16,16>>^ Entregou-os aos seus servos, cada rebanho à parte. Então disse aos servos: — Vão à minha frente e deixem espaço entre rebanho e rebanho.

[[v1-32-17]]

^<<v1-32-17,17>>^ Ordenou ao primeiro servo, dizendo: — Quando Esaú, meu irmão, se encontrar com você e perguntar: "De quem você é, para onde você vai, de quem são estes animais que você vem trazendo?",

[[v1-32-18]]

^<<v1-32-18,18>>^ responda: "São do seu servo Jacó. É um presente que ele está enviando ao meu senhor Esaú. E eis que ele mesmo vem vindo atrás de nós."

[[v1-32-19]]

^<<v1-32-19,19>>^ Jacó ordenou também ao segundo, ao terceiro e a todos os que vinham conduzindo os rebanhos: — É assim que vocês devem falar com Esaú, quando se encontrarem com ele.

[[v1-32-20]]

^<<v1-32-20,20>>^ Também dirão: "Eis que o seu servo Jacó vem vindo atrás de nós." Porque Jacó pensava assim: "Eu o aplacarei com o presente que me antecede. Depois eu o verei pessoalmente e talvez ele me dê boa acolhida."

[[v1-32-21]]

^<<v1-32-21,21>>^ Assim, mandou os presentes à sua frente. Ele, porém, ficou aquela noite no acampamento.

[[v1-32-22]]

^<<v1-32-22,22>>^ Naquela mesma noite, Jacó se levantou, tomou suas duas mulheres, suas duas servas e seus onze filhos e transpôs o vau do Jaboque.

[[v1-32-23]]

^<<v1-32-23,23>>^ Reuniu todos e fez com que passassem o ribeiro. Também fez passar tudo o que lhe pertencia.

[[v1-32-24]]

^<<v1-32-24,24>>^ Jacó ficou sozinho, e um homem lutava com ele, até o romper do dia.

[[v1-32-25]]

^<<v1-32-25,25>>^ Vendo este que não podia com Jacó, tocou-lhe na articulação da coxa, de modo que a junta da coxa de Jacó se deslocou, na luta com o homem.

[[v1-32-26]]

^<<v1-32-26,26>>^ Então o homem disse: — Deixe-me ir, pois já rompeu o dia. Jacó respondeu: — Não o deixarei ir se você não me abençoar.

[[v1-32-27]]

^<<v1-32-27,27>>^ Então o homem perguntou: — Como você se chama? Ele respondeu: — Jacó.

[[v1-32-28]]

^<<v1-32-28,28>>^ Então disse: — Seu nome não será mais Jacó, e sim Israel, pois você lutou com Deus e com os homens e prevaleceu.

[[v1-32-29]]

^<<v1-32-29,29>>^ Jacó disse: — Por favor, diga-me como você se chama. Ele respondeu: — Por que você pergunta pelo meu nome? E o abençoou ali.

[[v1-32-30]]

^<<v1-32-30,30>>^ Jacó deu àquele lugar o nome de Peniel, pois disse: "Vi Deus face a face, e a minha vida foi salva."

[[v1-32-31]]

^<<v1-32-31,31>>^ Nasceu-lhe o sol, quando ele atravessava Peniel. E mancava por causa da coxa.

[[v1-32-32]]

^<<v1-32-32,32>>^ Por isso, os filhos de Israel não comem, até hoje, o nervo do quadril, na articulação da coxa, porque o homem tocou a articulação da coxa de Jacó no nervo do quadril.

'''

xref:001-genesis/001-genesis-031.adoc#v1-31-0[&#60; Capítulo Anterior] | <<v1-32-0,Topo>> | xref:001-genesis/001-genesis-033.adoc#v1-33-0[Próximo Capítulo &#62;]