include::./index.adoc[]

[[v1-47-0]]
=== Gênesis, 47
// naa ?, NAA - Nova Almeida Atualizada

[[v1-47-1]]

^<<v1-47-1,1>>^ Então José foi e deu a notícia a Faraó: — O meu pai e os meus irmãos, com os seus rebanhos e o seu gado, com tudo o que têm, chegaram da terra de Canaã; e eis que estão na terra de Gósen.

[[v1-47-2]]

^<<v1-47-2,2>>^ E levou cinco dos seus irmãos e os apresentou a Faraó.

[[v1-47-3]]

^<<v1-47-3,3>>^ Então Faraó perguntou aos irmãos de José: — Qual é o trabalho de vocês? Eles responderam: — Nós, seus servos, somos pastores de rebanho, como já foram os nossos pais.

[[v1-47-4]]

^<<v1-47-4,4>>^ Disseram mais a Faraó: — Viemos para morar nesta terra, porque na terra de Canaã não há pasto para o rebanho destes seus servos, pois a fome é severa. E agora pedimos que o senhor permita que estes seus servos morem na terra de Gósen.

[[v1-47-5]]

^<<v1-47-5,5>>^ Então Faraó disse a José: — Seu pai e seus irmãos vieram para junto de você.

[[v1-47-6]]

^<<v1-47-6,6>>^ A terra do Egito está à sua disposição. Faça com que seu pai e seus irmãos se estabeleçam na melhor região da terra; que morem na terra de Gósen. Se souber que há no meio deles homens capazes, ponha-os por responsáveis pelo gado que me pertence.

[[v1-47-7]]

^<<v1-47-7,7>>^ José levou Jacó, seu pai, e o apresentou a Faraó; e Jacó abençoou Faraó.

[[v1-47-8]]

^<<v1-47-8,8>>^ Então Faraó perguntou a Jacó: — Quantos anos o senhor já tem?

[[v1-47-9]]

^<<v1-47-9,9>>^ Jacó lhe respondeu: — São cento e trinta anos de peregrinação. Foram poucos e maus os anos de minha vida e não chegam aos anos de vida de meus pais, nos dias das suas peregrinações.

[[v1-47-10]]

^<<v1-47-10,10>>^ Depois Jacó abençoou Faraó e saiu de sua presença.

[[v1-47-11]]

^<<v1-47-11,11>>^ Então José estabeleceu seu pai e seus irmãos e lhes deu propriedades na terra do Egito, no melhor da terra, na terra de Ramessés, como Faraó havia ordenado.

[[v1-47-12]]

^<<v1-47-12,12>>^ E José providenciou alimento para seu pai, seus irmãos e toda a casa de seu pai, segundo o número de seus filhos.

[[v1-47-13]]

^<<v1-47-13,13>>^ Não havia alimento em toda a terra, porque a fome era muito grande. Assim, o povo do Egito e o povo de Canaã desfaleciam por causa da fome.

[[v1-47-14]]

^<<v1-47-14,14>>^ Então José arrecadou todo o dinheiro que havia na terra do Egito e na terra de Canaã, pelo cereal que compravam, e o recolheu à casa de Faraó.

[[v1-47-15]]

^<<v1-47-15,15>>^ Quando acabou o dinheiro na terra do Egito e na terra de Canaã, todos os egípcios foram a José e disseram: — Queremos comida! Por que o senhor nos deixaria morrer em sua presença só porque o dinheiro acabou?

[[v1-47-16]]

^<<v1-47-16,16>>^ José respondeu: — Se vocês não têm dinheiro, tragam o seu gado. Em troca do gado eu lhes darei comida.

[[v1-47-17]]

^<<v1-47-17,17>>^ Então trouxeram o seu gado a José e ele lhes deu mantimento em troca de cavalos, rebanhos, gado e jumentos. E José os sustentou aquele ano em troca de todo o gado deles.

[[v1-47-18]]

^<<v1-47-18,18>>^ Tendo acabado aquele ano, foram a José no ano seguinte e lhe disseram: — Não podemos esconder de meu senhor que o dinheiro acabou e que meu senhor já é dono dos animais. Nada mais nos resta diante de meu senhor, a não ser o nosso corpo e a nossa terra.

[[v1-47-19]]

^<<v1-47-19,19>>^ Por que o senhor nos deixaria perecer em sua presença, tanto a nós como à nossa terra? Compre a nós e a nossa terra em troca de mantimento, e nós e a nossa terra seremos escravos de Faraó. Dê-nos semente para que vivamos e não morramos, e a terra não fique deserta.

[[v1-47-20]]

^<<v1-47-20,20>>^ Assim, José comprou toda a terra do Egito para Faraó, porque os egípcios venderam cada um o seu campo, porque a fome era extrema sobre eles. E a terra passou a ser de Faraó.

[[v1-47-21]]

^<<v1-47-21,21>>^ Quanto ao povo, ele o escravizou de uma a outra extremidade da terra do Egito.

[[v1-47-22]]

^<<v1-47-22,22>>^ José só não comprou a terra dos sacerdotes, porque os sacerdotes recebiam uma porção de mantimento de Faraó e viviam dessa porção que Faraó lhes dava; por isso, não venderam a sua terra.

[[v1-47-23]]

^<<v1-47-23,23>>^ Então José disse ao povo: — Eis que hoje comprei vocês e a terra de vocês para Faraó. Aqui estão as sementes, para que semeiem a terra.

[[v1-47-24]]

^<<v1-47-24,24>>^ Das colheitas vocês darão a quinta parte a Faraó. As outras quatro partes serão de vocês, para semear o campo e para servir de alimento a vocês, aos que estão em suas casas, e para alimentar os seus filhos.

[[v1-47-25]]

^<<v1-47-25,25>>^ Eles disseram a José: — O senhor salvou a nossa vida! Que possamos alcançar favor diante de meu senhor e seremos escravos de Faraó.

[[v1-47-26]]

^<<v1-47-26,26>>^ E José estabeleceu por lei até o dia de hoje que, na terra do Egito, um quinto pertence a Faraó. Só a terra dos sacerdotes não ficou sendo de Faraó.

[[v1-47-27]]

^<<v1-47-27,27>>^ Assim, Israel habitou na terra do Egito, na terra de Gósen. Nela adquiriram propriedades, e foram fecundos, e muito se multiplicaram.

[[v1-47-28]]

^<<v1-47-28,28>>^ Jacó viveu na terra do Egito dezessete anos. Assim, os dias de Jacó, os anos da sua vida, foram cento e quarenta e sete.

[[v1-47-29]]

^<<v1-47-29,29>>^ Aproximando-se, pois, o tempo da morte de Israel, chamou o seu filho José e lhe disse: — Se agora alcancei favor diante de você, peço que ponha a sua mão debaixo da minha coxa e use de bondade e fidelidade para comigo; peço que você não me sepulte no Egito,

[[v1-47-30]]

^<<v1-47-30,30>>^ mas que eu possa descansar com os meus pais. Por isso, você me levará do Egito e me colocará na sepultura deles. José respondeu: — Farei o que o senhor me pede.

[[v1-47-31]]

^<<v1-47-31,31>>^ Então Jacó lhe disse: — Jure para mim. José jurou e Israel se inclinou sobre a cabeceira da cama.

'''

xref:001-genesis/001-genesis-046.adoc#v1-46-0[&#60; Capítulo Anterior] | <<v1-47-0,Topo>> | xref:001-genesis/001-genesis-048.adoc#v1-48-0[Próximo Capítulo &#62;]