include::./index.adoc[]

[[v1-35-0]]
=== Gênesis, 35
// naa ?, NAA - Nova Almeida Atualizada

[[v1-35-1]]

^<<v1-35-1,1>>^ Deus disse a Jacó: — Levante-se, vá para Betel e habite ali. Faça ali um altar ao Deus que lhe apareceu quando você fugia do seu irmão Esaú.

[[v1-35-2]]

^<<v1-35-2,2>>^ Então Jacó disse à sua família e a todos os que estavam com ele: — Joguem fora os deuses estranhos que há no meio de vocês, purifiquem-se e troquem de roupa.

[[v1-35-3]]

^<<v1-35-3,3>>^ Vamos nos preparar e ir para Betel. Farei ali um altar ao Deus que me respondeu no dia da minha angústia e me acompanhou no caminho por onde andei.

[[v1-35-4]]

^<<v1-35-4,4>>^ Então deram a Jacó todos os deuses estranhos que tinham em mãos e as argolas que lhes pendiam das orelhas. E Jacó os escondeu debaixo do carvalho que está junto a Siquém.

[[v1-35-5]]

^<<v1-35-5,5>>^ Quando eles partiram, o terror de Deus invadiu as cidades vizinhas, e não perseguiram os filhos de Jacó.

[[v1-35-6]]

^<<v1-35-6,6>>^ Assim, Jacó chegou a Luz, chamada Betel, que fica na terra de Canaã, ele e todo o povo que estava com ele.

[[v1-35-7]]

^<<v1-35-7,7>>^ E edificou ali um altar. E àquele lugar deu o nome de El-Betel, porque ali Deus havia se revelado a ele quando estava fugindo do seu irmão.

[[v1-35-8]]

^<<v1-35-8,8>>^ Débora, a ama de Rebeca, morreu e foi sepultada ao pé de Betel, debaixo do carvalho que se chama Alom-Bacute.

[[v1-35-9]]

^<<v1-35-9,9>>^ Depois que Jacó havia retornado de Padã-Arã, Deus lhe apareceu outra vez e o abençoou.

[[v1-35-10]]

^<<v1-35-10,10>>^ Deus disse a ele: — Você se chama Jacó, mas o seu nome não será mais Jacó; o seu nome será Israel. E lhe deu o nome de Israel.

[[v1-35-11]]

^<<v1-35-11,11>>^ Disse-lhe mais: — Eu sou o Deus Todo-Poderoso; seja fecundo e multiplique-se; uma nação e multidão de nações sairão de você, e reis procederão de você.

[[v1-35-12]]

^<<v1-35-12,12>>^ A terra que dei a Abraão e a Isaque darei também a você e, depois de você, à sua descendência.

[[v1-35-13]]

^<<v1-35-13,13>>^ E Deus se retirou dele, elevando-se do lugar onde lhe havia falado.

[[v1-35-14]]

^<<v1-35-14,14>>^ Então Jacó pôs uma coluna de pedra no lugar onde Deus havia falado com ele e derramou uma libação e azeite sobre ela.

[[v1-35-15]]

^<<v1-35-15,15>>^ Ao lugar onde Deus lhe havia falado, Jacó deu o nome de Betel.

[[v1-35-16]]

^<<v1-35-16,16>>^ Partiram de Betel, e, havendo ainda pequena distância para chegar a Efrata, Raquel deu à luz um filho, num parto que foi muito difícil.

[[v1-35-17]]

^<<v1-35-17,17>>^ Em meio às dores, a parteira disse a Raquel: — Não tenha medo, pois você ainda terá este filho.

[[v1-35-18]]

^<<v1-35-18,18>>^ Ao sair-lhe a alma (porque morreu), deu ao filho o nome de Benoni. Mas seu pai lhe chamou Benjamim.

[[v1-35-19]]

^<<v1-35-19,19>>^ Assim, Raquel morreu e foi sepultada no caminho de Efrata, que é Belém.

[[v1-35-20]]

^<<v1-35-20,20>>^ Jacó levantou uma coluna sobre a sepultura de Raquel. Essa é a coluna da sepultura de Raquel até o dia de hoje.

[[v1-35-21]]

^<<v1-35-21,21>>^ Então Israel partiu e armou a sua tenda além da torre de Éder.

[[v1-35-22]]

^<<v1-35-22,22>>^ E aconteceu que, habitando Israel naquela terra, Rúben foi e se deitou com Bila, concubina de seu pai. E Israel ficou sabendo disso. Eram doze os filhos de Israel.

[[v1-35-23]]

^<<v1-35-23,23>>^ Rúben, o primogênito de Jacó, Simeão, Levi, Judá, Issacar e Zebulom, filhos de Lia;

[[v1-35-24]]

^<<v1-35-24,24>>^ José e Benjamim, filhos de Raquel;

[[v1-35-25]]

^<<v1-35-25,25>>^ Dã e Naftali, filhos de Bila, serva de Raquel;

[[v1-35-26]]

^<<v1-35-26,26>>^ e Gade e Aser, filhos de Zilpa, serva de Lia. São estes os filhos de Jacó, que lhe nasceram em Padã-Arã.

[[v1-35-27]]

^<<v1-35-27,27>>^ Jacó veio a Isaque, seu pai, a Manre, a Quiriate-Arba (que é Hebrom), onde peregrinaram Abraão e Isaque.

[[v1-35-28]]

^<<v1-35-28,28>>^ Os dias da vida de Isaque foram cento e oitenta anos.

[[v1-35-29]]

^<<v1-35-29,29>>^ Após uma longa velhice, Isaque expirou e morreu, sendo reunido ao seu povo; e Esaú e Jacó, seus filhos, o sepultaram.

'''

xref:001-genesis/001-genesis-034.adoc#v1-34-0[&#60; Capítulo Anterior] | <<v1-35-0,Topo>> | xref:001-genesis/001-genesis-036.adoc#v1-36-0[Próximo Capítulo &#62;]