include::./index.adoc[]

[[v1-42-0]]
=== Gênesis, 42
// naa ?, NAA - Nova Almeida Atualizada

[[v1-42-1]]

^<<v1-42-1,1>>^ Quando Jacó soube que havia mantimento no Egito, disse a seus filhos: — Por que vocês estão aí olhando uns para os outros?

[[v1-42-2]]

^<<v1-42-2,2>>^ E acrescentou: — Ouvi dizer que há cereais no Egito. Vão até lá e comprem cereais, para que vivamos e não morramos.

[[v1-42-3]]

^<<v1-42-3,3>>^ Então dez dos irmãos de José foram, para comprar cereal do Egito.

[[v1-42-4]]

^<<v1-42-4,4>>^ Mas Jacó não enviou Benjamim, o irmão de José, na companhia dos irmãos, porque dizia: "E se lhe acontecer algum desastre?"

[[v1-42-5]]

^<<v1-42-5,5>>^ Entre os que iam, pois, para lá, foram também os filhos de Israel, pois havia fome na terra de Canaã.

[[v1-42-6]]

^<<v1-42-6,6>>^ José era governador daquela terra; era ele quem vendia a todos os povos da terra. Os irmãos de José vieram e se prostraram com o rosto em terra, diante dele.

[[v1-42-7]]

^<<v1-42-7,7>>^ Quando José viu os seus irmãos, reconheceu-os, porém não se deu a conhecer. Foi ríspido com eles e lhes perguntou: — De onde vocês vêm? Responderam: — Da terra de Canaã, para comprar mantimento.

[[v1-42-8]]

^<<v1-42-8,8>>^ José reconheceu os irmãos, mas eles não o reconheceram.

[[v1-42-9]]

^<<v1-42-9,9>>^ Então José se lembrou dos sonhos que teve a respeito deles e lhes disse: — Vocês são espiões e vieram para ver os pontos fracos da terra.

[[v1-42-10]]

^<<v1-42-10,10>>^ Eles responderam: — Não, meu senhor. Estes seus servos vieram só para comprar mantimento.

[[v1-42-11]]

^<<v1-42-11,11>>^ Somos todos filhos de um mesmo homem; somos homens honestos; estes seus servos não são espiões.

[[v1-42-12]]

^<<v1-42-12,12>>^ Ele, porém, lhes respondeu: — Nada disso! Pelo contrário, vocês vieram para ver os pontos fracos da terra.

[[v1-42-13]]

^<<v1-42-13,13>>^ Eles disseram: — Nós, seus servos, somos doze irmãos, filhos de um homem na terra de Canaã. O mais novo está hoje com o nosso pai, outro já não existe.

[[v1-42-14]]

^<<v1-42-14,14>>^ Então José lhes disse: — É como já falei: vocês são espiões.

[[v1-42-15]]

^<<v1-42-15,15>>^ Nisto vocês serão provados: juro pela vida de Faraó que vocês não sairão daqui, sem que primeiro venha o irmão mais novo de vocês.

[[v1-42-16]]

^<<v1-42-16,16>>^ Enviem um de vocês, que busque o seu irmão. Vocês ficarão detidos para que sejam provadas as palavras de vocês, se há verdade no que dizem; ou se não, juro pela vida de Faraó que vocês são espiões.

[[v1-42-17]]

^<<v1-42-17,17>>^ E deixou todos presos por três dias.

[[v1-42-18]]

^<<v1-42-18,18>>^ No terceiro dia, José lhes disse: — Façam o seguinte e viverão, pois temo a Deus.

[[v1-42-19]]

^<<v1-42-19,19>>^ Se são homens honestos, que um de vocês fique detido aqui onde estão presos; os outros podem ir, levando cereal para matar a fome das suas famílias.

[[v1-42-20]]

^<<v1-42-20,20>>^ E tragam-me o seu irmão mais novo, com o que serão verificadas as palavras de vocês, e vocês não morrerão. E eles se dispuseram a fazê-lo.

[[v1-42-21]]

^<<v1-42-21,21>>^ Então disseram entre si: — Na verdade, estamos sendo castigados por causa de nosso irmão, pois vimos a angústia de sua alma, quando nos pedia, e não lhe demos ouvidos; por isso, nos sobrevém agora esta ansiedade.

[[v1-42-22]]

^<<v1-42-22,22>>^ Rúben respondeu-lhes: — Não é verdade que eu disse: "Não pequem contra o jovem"? Mas vocês não quiseram me ouvir. Pois agora estão vendo que o sangue dele está sendo requerido de nós.

[[v1-42-23]]

^<<v1-42-23,23>>^ Eles, porém, não sabiam que José os entendia, porque lhes falava por meio de um intérprete.

[[v1-42-24]]

^<<v1-42-24,24>>^ E, retirando-se deles, José chorou. Depois, voltando para junto deles, lhes falou outra vez. Escolheu Simeão e o algemou na presença deles.

[[v1-42-25]]

^<<v1-42-25,25>>^ José ordenou que lhes enchessem de cereal os sacos, e lhes restituíssem o dinheiro, a cada um no saco de cereal, e os suprissem de comida para o caminho. E assim foi feito.

[[v1-42-26]]

^<<v1-42-26,26>>^ E carregaram o cereal sobre os seus jumentos e partiram dali.

[[v1-42-27]]

^<<v1-42-27,27>>^ Quando um deles abriu o saco de cereal, para dar de comer ao seu jumento na estalagem, encontrou o dinheiro na boca do saco de cereal.

[[v1-42-28]]

^<<v1-42-28,28>>^ Então disse aos irmãos: — Devolveram o meu dinheiro. Está aqui na boca do saco de cereal. O coração dos irmãos se encheu de medo, e, tremendo, entreolhavam-se, dizendo: — O que é isto que Deus nos fez?

[[v1-42-29]]

^<<v1-42-29,29>>^ E vieram para Jacó, seu pai, na terra de Canaã, e lhe contaram tudo o que lhes havia acontecido, dizendo:

[[v1-42-30]]

^<<v1-42-30,30>>^ — O homem, o senhor da terra, falou conosco de maneira ríspida e nos tratou como espiões da terra.

[[v1-42-31]]

^<<v1-42-31,31>>^ Dissemos a ele: "Somos homens honestos e não espiões.

[[v1-42-32]]

^<<v1-42-32,32>>^ Somos doze irmãos, filhos de um mesmo pai; um já não existe, e o mais novo está hoje com o nosso pai na terra de Canaã."

[[v1-42-33]]

^<<v1-42-33,33>>^ Então o homem, o senhor da terra, respondeu: "Nisto saberei que vocês são homens honestos: deixem comigo um de seus irmãos, peguem o cereal para remediar a fome de suas casas e vão embora.

[[v1-42-34]]

^<<v1-42-34,34>>^ Mas tragam-me o seu irmão mais novo. Assim saberei que vocês não são espiões, mas homens honestos. Então entregarei o irmão de vocês, e vocês poderão negociar na terra."

[[v1-42-35]]

^<<v1-42-35,35>>^ Aconteceu que, quando foram despejar o cereal que havia nos sacos, cada um tinha a sua trouxinha de dinheiro no saco de cereal. Ao ver as trouxinhas com o dinheiro, eles e o seu pai ficaram com medo.

[[v1-42-36]]

^<<v1-42-36,36>>^ Então Jacó, o pai deles, disse: — Vocês vão me deixar sem filhos. José se foi. Simeão se foi. Agora querem levar Benjamim! Todas essas coisas acontecem contra mim.

[[v1-42-37]]

^<<v1-42-37,37>>^ Mas Rúben disse a seu pai: — O senhor pode matar os meus dois filhos, se eu não trouxer Benjamim de volta. Deixe que eu tome conta dele, e o trarei de volta para o senhor.

[[v1-42-38]]

^<<v1-42-38,38>>^ Mas Jacó respondeu: — O meu filho não irá com vocês. O irmão dele está morto, e ele é o único que ficou. Se lhe acontece algum desastre no caminho, vocês farão descer os meus cabelos brancos com tristeza à sepultura.

'''

xref:001-genesis/001-genesis-041.adoc#v1-41-0[&#60; Capítulo Anterior] | <<v1-42-0,Topo>> | xref:001-genesis/001-genesis-043.adoc#v1-43-0[Próximo Capítulo &#62;]