include::./index.adoc[]

[[v1-30-0]]
=== Gênesis, 30
// naa ?, NAA - Nova Almeida Atualizada

[[v1-30-1]]

^<<v1-30-1,1>>^ Quando Raquel viu que não dava filhos a Jacó, teve ciúmes de sua irmã e disse a Jacó: — Dê-me filhos, do contrário morrerei.

[[v1-30-2]]

^<<v1-30-2,2>>^ Então Jacó ficou irado com Raquel e disse: — Será que eu estou em lugar de Deus, que a impediu de ter filhos?

[[v1-30-3]]

^<<v1-30-3,3>>^ Então Raquel disse: — Eis aqui Bila, minha serva; tenha relações com ela, para que dê à luz e eu traga filhos ao meu colo por meio dela.

[[v1-30-4]]

^<<v1-30-4,4>>^ Assim, Raquel lhe deu Bila, sua serva, por mulher; e Jacó teve relações com ela.

[[v1-30-5]]

^<<v1-30-5,5>>^ Bila ficou grávida e deu à luz um filho a Jacó.

[[v1-30-6]]

^<<v1-30-6,6>>^ Então Raquel disse: — Deus me fez justiça; ouviu a minha voz e me deu um filho. Por isso lhe chamou Dã.

[[v1-30-7]]

^<<v1-30-7,7>>^ Outra vez Bila, serva de Raquel, ficou grávida e deu à luz o segundo filho a Jacó.

[[v1-30-8]]

^<<v1-30-8,8>>^ Raquel disse: — Com grandes lutas tenho competido com minha irmã e consegui vencer. Por isso deu ao filho o nome de Naftali.

[[v1-30-9]]

^<<v1-30-9,9>>^ Quando Lia viu que ela mesma tinha cessado de ter filhos, tomou a sua serva Zilpa e a deu a Jacó por mulher.

[[v1-30-10]]

^<<v1-30-10,10>>^ Zilpa, serva de Lia, deu a Jacó um filho.

[[v1-30-11]]

^<<v1-30-11,11>>^ Lia disse: — Afortunada! E deu ao filho o nome de Gade.

[[v1-30-12]]

^<<v1-30-12,12>>^ Depois, Zilpa, serva de Lia, deu o segundo filho a Jacó.

[[v1-30-13]]

^<<v1-30-13,13>>^ Então Lia disse: — É a minha felicidade! Porque as mulheres dirão que sou feliz. E lhe deu o nome de Aser.

[[v1-30-14]]

^<<v1-30-14,14>>^ Nos dias da colheita do trigo, Rúben saiu e achou umas mandrágoras no campo. Ele as trouxe para Lia, sua mãe. Então Raquel disse a Lia: — Dê-me algumas das mandrágoras que o seu filho trouxe.

[[v1-30-15]]

^<<v1-30-15,15>>^ Mas Lia respondeu: — Você acha pouco o fato de ter tomado de mim o marido? Vai tomar também as mandrágoras de meu filho? Raquel respondeu: — Ele poderá ter relações com você esta noite, em troca das mandrágoras de seu filho.

[[v1-30-16]]

^<<v1-30-16,16>>^ À tarde, quando Jacó voltava do campo, Lia saiu ao encontro dele e lhe disse: — Esta noite você terá relações comigo, pois eu aluguei você pelas mandrágoras de meu filho. E naquela noite Jacó teve relações com ela.

[[v1-30-17]]

^<<v1-30-17,17>>^ Deus ouviu Lia, ela ficou grávida e deu à luz o quinto filho.

[[v1-30-18]]

^<<v1-30-18,18>>^ Então Lia disse: — Deus me recompensou, porque dei a minha serva ao meu marido. E deu ao filho o nome de Issacar.

[[v1-30-19]]

^<<v1-30-19,19>>^ E Lia engravidou mais uma vez e deu a Jacó o sexto filho.

[[v1-30-20]]

^<<v1-30-20,20>>^ E disse: — Deus me concedeu excelente dádiva. Agora meu marido vai permanecer comigo, porque lhe dei seis filhos. E ela deu ao filho o nome de Zebulom.

[[v1-30-21]]

^<<v1-30-21,21>>^ Depois disto, deu à luz uma filha e lhe chamou Diná.

[[v1-30-22]]

^<<v1-30-22,22>>^ Deus lembrou-se de Raquel, ouviu-a e a fez fecunda.

[[v1-30-23]]

^<<v1-30-23,23>>^ Ela engravidou e deu à luz um filho. Então disse: — Deus tirou de mim o meu vexame.

[[v1-30-24]]

^<<v1-30-24,24>>^ E deu ao filho o nome de José, dizendo: — Que o Senhor  me dê ainda outro filho.

[[v1-30-25]]

^<<v1-30-25,25>>^ Depois que Raquel deu à luz José, Jacó disse a Labão: — Deixe-me voltar ao meu lugar e à minha terra.

[[v1-30-26]]

^<<v1-30-26,26>>^ Dê-me os meus filhos e as mulheres, pelas quais trabalhei para o senhor, e partirei. O senhor sabe muito bem quanto e de que maneira o servi.

[[v1-30-27]]

^<<v1-30-27,27>>^ Labão lhe respondeu: — Se puder me fazer este favor, peço que fique comigo. Descobri por meio de adivinhações que o Senhor  Deus me abençoou por causa de você.

[[v1-30-28]]

^<<v1-30-28,28>>^ E Labão continuou: — Fixe o seu salário, que eu pagarei.

[[v1-30-29]]

^<<v1-30-29,29>>^ Então Jacó disse: — O senhor sabe como tenho trabalhado e como cuidei do seu gado.

[[v1-30-30]]

^<<v1-30-30,30>>^ Porque o pouco que o senhor tinha antes de eu chegar foi aumentado grandemente; e o Senhor  Deus o abençoou com o meu trabalho. Mas quando vou começar a trabalhar também por minha própria casa?

[[v1-30-31]]

^<<v1-30-31,31>>^ Labão perguntou a Jacó: — Quanto você quer que eu lhe dê? Jacó respondeu: — Não precisa me dar nada. Voltarei a apascentar e a guardar o seu rebanho, se o senhor concordar com isto:

[[v1-30-32]]

^<<v1-30-32,32>>^ Passarei hoje por todo o seu rebanho, separando para mim todas as ovelhas salpicadas e malhadas, todos os cordeiros negros, e todas as cabras malhadas e salpicadas. Isto será o meu salário.

[[v1-30-33]]

^<<v1-30-33,33>>^ Assim, a minha justiça responderá por mim, no dia de amanhã, quando o senhor vier conferir o meu salário. As cabras que não forem salpicadas e malhadas e as ovelhas que não forem negras, caso forem achadas comigo, o senhor pode considerá-las como roubadas.

[[v1-30-34]]

^<<v1-30-34,34>>^ Labão disse: — Está bem. Seja como você disse.

[[v1-30-35]]

^<<v1-30-35,35>>^ Mas, naquele mesmo dia, Labão separou os bodes listrados e malhados e todas as cabras salpicadas e malhadas, todos os que tinham alguma brancura e todos os cordeiros pretos; e os passou às mãos de seus filhos.

[[v1-30-36]]

^<<v1-30-36,36>>^ E pôs a distância de três dias de viagem entre si e Jacó. E Jacó apascentava o restante dos rebanhos de Labão.

[[v1-30-37]]

^<<v1-30-37,37>>^ Jacó pegou galhos verdes de álamo, de aveleira e de plátano e lhes removeu a casca, em riscas abertas, deixando aparecer a brancura dos galhos.

[[v1-30-38]]

^<<v1-30-38,38>>^ Pôs esses galhos descascados em frente ao rebanho, nos canais de água e nos bebedouros, aonde os rebanhos vinham para beber água. E como acasalavam quando vinham beber,

[[v1-30-39]]

^<<v1-30-39,39>>^ as ovelhas ficavam prenhes diante dos galhos e davam crias listradas, salpicadas e malhadas.

[[v1-30-40]]

^<<v1-30-40,40>>^ Então Jacó separou os cordeiros e virou o rebanho para o lado dos animais listrados e dos animais pretos nos rebanhos de Labão; e pôs o seu rebanho à parte e não o juntou com o rebanho de Labão.

[[v1-30-41]]

^<<v1-30-41,41>>^ E, todas as vezes que as ovelhas fortes ficavam prenhes, Jacó punha os galhos à vista do rebanho nos canais de água, para que ficassem prenhes diante dos galhos.

[[v1-30-42]]

^<<v1-30-42,42>>^ Porém, quando o rebanho era fraco, não punha os galhos. Assim, os animais fracos eram de Labão, e os fortes eram de Jacó.

[[v1-30-43]]

^<<v1-30-43,43>>^ E o homem se tornou mais e mais rico; teve muitos rebanhos, servas, servos, camelos e jumentos.

'''

xref:001-genesis/001-genesis-029.adoc#v1-29-0[&#60; Capítulo Anterior] | <<v1-30-0,Topo>> | xref:001-genesis/001-genesis-031.adoc#v1-31-0[Próximo Capítulo &#62;]