include::./index.adoc[]

[[v1-21-0]]
=== Gênesis, 21
// naa ?, NAA - Nova Almeida Atualizada

[[v1-21-1]]

^<<v1-21-1,1>>^ O Senhor  visitou Sara, como tinha dito, e cumpriu o que lhe havia prometido.

[[v1-21-2]]

^<<v1-21-2,2>>^ Sara ficou grávida e deu à luz um filho a Abraão na sua velhice, no tempo determinado, de que Deus lhe havia falado.

[[v1-21-3]]

^<<v1-21-3,3>>^ Ao filho que lhe nasceu, que Sara lhe dera à luz, Abraão deu o nome de Isaque.

[[v1-21-4]]

^<<v1-21-4,4>>^ Abraão circuncidou o seu filho Isaque, quando ele tinha oito dias, segundo Deus lhe havia ordenado.

[[v1-21-5]]

^<<v1-21-5,5>>^ Abraão tinha cem anos quando lhe nasceu Isaque, seu filho.

[[v1-21-6]]

^<<v1-21-6,6>>^ E Sara disse: — Deus me deu motivo de riso. E todo aquele que ouvir isso vai rir comigo.

[[v1-21-7]]

^<<v1-21-7,7>>^ E acrescentou: — Quem diria a Abraão que Sara ainda amamentaria um filho? Pois na sua velhice lhe dei um filho.

[[v1-21-8]]

^<<v1-21-8,8>>^ Isaque cresceu e foi desmamado. Nesse dia em que o menino foi desmamado, Abraão deu um grande banquete.

[[v1-21-9]]

^<<v1-21-9,9>>^ Sara viu que o filho que Agar, a egípcia, teve com Abraão estava zombando de Isaque.

[[v1-21-10]]

^<<v1-21-10,10>>^ Então Sara disse a Abraão: — Mande embora essa escrava e o filho dela, porque o filho dessa escrava não será herdeiro com o meu filho Isaque.

[[v1-21-11]]

^<<v1-21-11,11>>^ Abraão ficou muito incomodado com isso, por causa de seu filho.

[[v1-21-12]]

^<<v1-21-12,12>>^ Mas Deus disse a Abraão: — Não fique incomodado por causa do menino e por causa da escrava. Faça tudo o que Sara disser, porque por meio de Isaque será chamada a sua descendência.

[[v1-21-13]]

^<<v1-21-13,13>>^ Mas também do filho da escrava farei uma grande nação, porque ele é seu descendente.

[[v1-21-14]]

^<<v1-21-14,14>>^ Na manhã seguinte, Abraão levantou-se de madrugada, pegou pão e um odre de água, pôs tudo sobre as costas de Agar, deu-lhe o menino e a despediu. Ela saiu, andando sem rumo pelo deserto de Berseba.

[[v1-21-15]]

^<<v1-21-15,15>>^ Quando acabou a água que havia no odre, Agar colocou o menino debaixo de um dos arbustos.

[[v1-21-16]]

^<<v1-21-16,16>>^ E, afastando-se, foi sentar-se em frente, à distância de um tiro de arco, porque dizia: — Assim, não verei o menino morrer. E, sentando-se em frente dele, levantou a voz e chorou.

[[v1-21-17]]

^<<v1-21-17,17>>^ Deus, porém, ouviu a voz do menino. E, do céu, o Anjo de Deus chamou Agar e lhe disse: — O que é que você tem, Agar? Não tenha medo, porque Deus ouviu a voz do menino, aí onde ele está.

[[v1-21-18]]

^<<v1-21-18,18>>^ Ponha-se em pé, levante o menino e segure-o pela mão, porque eu farei dele um grande povo.

[[v1-21-19]]

^<<v1-21-19,19>>^ Então Deus lhe abriu os olhos, e ela viu um poço de água. E, indo até o poço, encheu o odre de água, e deu de beber ao menino.

[[v1-21-20]]

^<<v1-21-20,20>>^ Deus estava com o menino, que cresceu, morou no deserto e se tornou flecheiro.

[[v1-21-21]]

^<<v1-21-21,21>>^ Ele morava no deserto de Parã, e a mãe dele o casou com uma mulher da terra do Egito.

[[v1-21-22]]

^<<v1-21-22,22>>^ Por esse tempo, Abimeleque e Ficol, comandante do seu exército, disseram a Abraão: — Deus está com você em tudo o que você faz.

[[v1-21-23]]

^<<v1-21-23,23>>^ Portanto, aqui neste lugar, jure por Deus que você não enganará a mim, nem a meu filho, nem a meu neto, e que tratará a mim e a terra em que você tem morado com a mesma bondade com que eu tratei você.

[[v1-21-24]]

^<<v1-21-24,24>>^ Abraão respondeu: — Eu juro.

[[v1-21-25]]

^<<v1-21-25,25>>^ Mas Abraão repreendeu Abimeleque por causa de um poço de água que os servos deste haviam tomado à força.

[[v1-21-26]]

^<<v1-21-26,26>>^ Abimeleque disse: — Não sei quem fez isso. Além do mais, você nunca me falou nada e eu não tinha ouvido nada a respeito, a não ser hoje.

[[v1-21-27]]

^<<v1-21-27,27>>^ Então Abraão pegou ovelhas e bois e os deu a Abimeleque. E os dois fizeram uma aliança.

[[v1-21-28]]

^<<v1-21-28,28>>^ Abraão pôs à parte sete cordeiras do rebanho.

[[v1-21-29]]

^<<v1-21-29,29>>^ Abimeleque perguntou a Abraão: — Que significam as sete cordeiras que você pôs à parte?

[[v1-21-30]]

^<<v1-21-30,30>>^ Abraão respondeu: — Você receberá das minhas mãos as sete cordeiras, para que me sirvam de testemunho de que eu cavei este poço.

[[v1-21-31]]

^<<v1-21-31,31>>^ Por isso aquele lugar foi chamado de Berseba, porque ali os dois fizeram um juramento.

[[v1-21-32]]

^<<v1-21-32,32>>^ Assim, fizeram aliança em Berseba. Depois Abimeleque e Ficol, comandante do seu exército, voltaram para as terras dos filisteus.

[[v1-21-33]]

^<<v1-21-33,33>>^ Abraão plantou uma tamargueira em Berseba e invocou ali o nome do Senhor , o Deus Eterno.

[[v1-21-34]]

^<<v1-21-34,34>>^ E por muito tempo Abraão morou na terra dos filisteus.

'''

xref:001-genesis/001-genesis-020.adoc#v1-20-0[&#60; Capítulo Anterior] | <<v1-21-0,Topo>> | xref:001-genesis/001-genesis-022.adoc#v1-22-0[Próximo Capítulo &#62;]