include::./index.adoc[]

[[v1-48-0]]
=== Gênesis, 48
// naa ?, NAA - Nova Almeida Atualizada

[[v1-48-1]]

^<<v1-48-1,1>>^ Passadas estas coisas, disseram a José: — Seu pai está doente. Então José tomou consigo seus dois filhos, Manassés e Efraim.

[[v1-48-2]]

^<<v1-48-2,2>>^ E avisaram a Jacó: — Eis que o seu filho José vem visitá-lo. Israel fez um esforço e se sentou na cama.

[[v1-48-3]]

^<<v1-48-3,3>>^ Então Jacó disse a José: — O Deus Todo-Poderoso me apareceu na cidade de Luz, na terra de Canaã, me abençoou

[[v1-48-4]]

^<<v1-48-4,4>>^ e me disse: "Eis que eu o farei fecundo e o multiplicarei. De você farei uma multidão de povos e à sua descendência darei esta terra como propriedade perpétua."

[[v1-48-5]]

^<<v1-48-5,5>>^ E agora os seus dois filhos, que lhe nasceram na terra do Egito antes que eu viesse para junto de você aqui no Egito, são meus. Efraim e Manassés serão meus, assim como Rúben e Simeão são meus.

[[v1-48-6]]

^<<v1-48-6,6>>^ Mas os filhos que você gerar depois deles serão seus; segundo o nome de um de seus irmãos serão chamados na sua herança.

[[v1-48-7]]

^<<v1-48-7,7>>^ Quando eu vinha de Padã, para minha tristeza morreu Raquel na terra de Canaã, no caminho, a pouca distância de Efrata; eu a sepultei ali no caminho de Efrata, que é Belém.

[[v1-48-8]]

^<<v1-48-8,8>>^ Quando Israel viu os filhos de José, perguntou: — Quem são estes?

[[v1-48-9]]

^<<v1-48-9,9>>^ José respondeu a seu pai: — São meus filhos, que Deus me deu aqui. Israel disse: — Traga-os para perto de mim, para que eu os abençoe.

[[v1-48-10]]

^<<v1-48-10,10>>^ Os olhos de Israel já estavam fracos por causa da velhice, de modo que não podia ver bem. Por isso José levou os filhos para perto dele; e ele os beijou e os abraçou.

[[v1-48-11]]

^<<v1-48-11,11>>^ Então Israel disse a José: — Eu não esperava ver o seu rosto outra vez; e eis que Deus me permitiu ver também os seus filhos.

[[v1-48-12]]

^<<v1-48-12,12>>^ E José, tirando-os dentre os joelhos de seu pai, se prostrou com o rosto em terra, diante dele.

[[v1-48-13]]

^<<v1-48-13,13>>^ Depois José pegou os dois filhos e os colocou diante do pai. Pegou Efraim com a mão direita, para que ficasse à esquerda de Israel, e Manassés com a mão esquerda, para que ficasse à direita de Israel.

[[v1-48-14]]

^<<v1-48-14,14>>^ Mas Israel estendeu a mão direita e a pôs sobre a cabeça de Efraim, que era o mais novo, e pôs a mão esquerda sobre a cabeça de Manassés, cruzando assim as mãos, mesmo sendo Manassés o primogênito.

[[v1-48-15]]

^<<v1-48-15,15>>^ E Israel abençoou José, dizendo: — O Deus em cuja presença andaram meus pais Abraão e Isaque, o Deus que tem sido o meu pastor durante a minha vida até este dia,

[[v1-48-16]]

^<<v1-48-16,16>>^ o Anjo que me tem livrado de todo mal, abençoe estes meninos! Que por meio deles seja lembrado o meu nome e o nome de meus pais Abraão e Isaque! Que cresçam e se tornem uma multidão sobre a terra.

[[v1-48-17]]

^<<v1-48-17,17>>^ José viu que seu pai havia posto a mão direita sobre a cabeça de Efraim e isto não lhe agradou. Pegou a mão de seu pai para mudá-la da cabeça de Efraim para a cabeça de Manassés.

[[v1-48-18]]

^<<v1-48-18,18>>^ E José disse ao pai: — Não assim, meu pai, pois o primogênito é este; ponha a mão direita sobre a cabeça dele.

[[v1-48-19]]

^<<v1-48-19,19>>^ Mas seu pai recusou e disse: — Eu sei, meu filho, eu sei. Ele também será um povo, também ele será grande. Mas o seu irmão menor será maior do que ele, e a sua descendência será uma multidão de nações.

[[v1-48-20]]

^<<v1-48-20,20>>^ Assim, os abençoou naquele dia, declarando: — Por vocês Israel abençoará, dizendo: "Deus faça com você como fez com Efraim e com Manassés." E assim Israel pôs Efraim antes de Manassés.

[[v1-48-21]]

^<<v1-48-21,21>>^ Depois Israel disse a José: — Eis que estou morrendo, mas Deus estará com vocês e os fará voltar à terra de seus pais.

[[v1-48-22]]

^<<v1-48-22,22>>^ Dou a você uma parte a mais que a seus irmãos, um declive montanhoso, o qual tomei das mãos dos amorreus com a minha espada e com o meu arco.

'''

xref:001-genesis/001-genesis-047.adoc#v1-47-0[&#60; Capítulo Anterior] | <<v1-48-0,Topo>> | xref:001-genesis/001-genesis-049.adoc#v1-49-0[Próximo Capítulo &#62;]