include::./index.adoc[]

[[v1-26-0]]
=== Gênesis, 26
// naa ?, NAA - Nova Almeida Atualizada

[[v1-26-1]]

^<<v1-26-1,1>>^ Sobreveio fome à terra, assim como tinha acontecido nos dias de Abraão. Então Isaque foi a Gerar, encontrar-se com Abimeleque, rei dos filisteus.

[[v1-26-2]]

^<<v1-26-2,2>>^ O Senhor  apareceu a Isaque e lhe disse: — Não desça ao Egito, mas fique na terra que eu lhe indicar.

[[v1-26-3]]

^<<v1-26-3,3>>^ Habite nela, e serei com você e o abençoarei. Porque a você e à sua descendência darei todas estas terras e confirmarei o juramento que fiz a Abraão, o seu pai.

[[v1-26-4]]

^<<v1-26-4,4>>^ Multiplicarei a sua descendência como as estrelas dos céus e a ela darei todas estas terras. Na sua descendência serão benditas todas as nações da terra,

[[v1-26-5]]

^<<v1-26-5,5>>^ porque Abraão obedeceu à minha palavra e guardou os meus mandamentos, os meus preceitos, os meus estatutos e as minhas leis.

[[v1-26-6]]

^<<v1-26-6,6>>^ Isaque, pois, ficou em Gerar.

[[v1-26-7]]

^<<v1-26-7,7>>^ Quando os homens daquele lugar perguntaram a respeito de sua mulher, ele disse: "É minha irmã." Ele tinha medo de dizer: "É minha mulher", porque pensava assim: "Os homens do lugar me matarão por causa de Rebeca, porque ela é muito bonita."

[[v1-26-8]]

^<<v1-26-8,8>>^ Depois que Isaque havia permanecido ali por muito tempo, Abimeleque, rei dos filisteus, olhou por uma janela e viu que Isaque acariciava Rebeca, sua mulher.

[[v1-26-9]]

^<<v1-26-9,9>>^ Então Abimeleque chamou Isaque e lhe disse: — É evidente que ela é a sua mulher! Como é que você disse que ela era a sua irmã? Isaque respondeu: — É que eu pensei que poderiam me matar por causa dela.

[[v1-26-10]]

^<<v1-26-10,10>>^ Então Abimeleque disse: — O que é isso que você fez conosco? Facilmente alguém do povo poderia ter se deitado com a sua mulher, e você teria trazido culpa sobre nós.

[[v1-26-11]]

^<<v1-26-11,11>>^ Então Abimeleque deu esta ordem a todo o povo: — Quem tocar neste homem ou na sua mulher certamente morrerá.

[[v1-26-12]]

^<<v1-26-12,12>>^ Isaque semeou naquela terra e, no mesmo ano, recolheu cem por um, porque o Senhor  o abençoava.

[[v1-26-13]]

^<<v1-26-13,13>>^ Ele enriqueceu, continuou prosperando, ficou riquíssimo.

[[v1-26-14]]

^<<v1-26-14,14>>^ Tinha ovelhas e bois e grande número de servos, de maneira que os filisteus tinham inveja dele.

[[v1-26-15]]

^<<v1-26-15,15>>^ E, por isso, lhe entulharam todos os poços que os servos de seu pai haviam cavado, nos dias de Abraão, enchendo-os de terra.

[[v1-26-16]]

^<<v1-26-16,16>>^ Abimeleque disse a Isaque: — Saia da nossa terra, porque você já é muito mais poderoso do que nós.

[[v1-26-17]]

^<<v1-26-17,17>>^ Então Isaque saiu dali e se acampou no vale de Gerar, onde ficou morando.

[[v1-26-18]]

^<<v1-26-18,18>>^ Isaque tornou a abrir os poços que haviam sido cavados nos dias de Abraão, seu pai, porque os filisteus os haviam entulhado depois da morte de Abraão, e lhes deu os mesmos nomes que o seu pai já lhes tinha dado.

[[v1-26-19]]

^<<v1-26-19,19>>^ Os servos de Isaque cavaram no vale e acharam um poço de água nascente.

[[v1-26-20]]

^<<v1-26-20,20>>^ Mas os pastores de Gerar entraram em conflito com os pastores de Isaque, dizendo: — Esta água é nossa! Por isso, Isaque chamou o poço de Eseque, porque entraram em conflito com ele.

[[v1-26-21]]

^<<v1-26-21,21>>^ Então cavaram outro poço e também por causa desse houve conflito. Por isso, recebeu o nome de Sitna.

[[v1-26-22]]

^<<v1-26-22,22>>^ Partindo dali, Isaque cavou ainda outro poço. E, como por esse não houve conflito, deu-lhe o nome de Reobote. Ele disse: — Porque agora o Senhor  abriu espaço para nós e vamos prosperar nesta terra.

[[v1-26-23]]

^<<v1-26-23,23>>^ Dali Isaque foi para Berseba.

[[v1-26-24]]

^<<v1-26-24,24>>^ Na mesma noite, o Senhor  lhe apareceu e disse: — Eu sou o Deus de seu pai Abraão. Não tenha medo, porque eu estou com você. Eu o abençoarei e multiplicarei a sua descendência por amor de Abraão, meu servo.

[[v1-26-25]]

^<<v1-26-25,25>>^ Então Isaque levantou ali um altar e, tendo invocado o nome do Senhor , armou a sua tenda; e os servos de Isaque abriram ali um poço.

[[v1-26-26]]

^<<v1-26-26,26>>^ Abimeleque, seu amigo Austate e Ficol, comandante do seu exército, saíram de Gerar para encontrar Isaque.

[[v1-26-27]]

^<<v1-26-27,27>>^ Isaque perguntou: — Por que vocês vieram à minha presença, se me odeiam e me expulsaram do meio de vocês?

[[v1-26-28]]

^<<v1-26-28,28>>^ Eles responderam: — Vimos claramente que o Senhor  está com você. Então pensamos que seria bom se houvesse um juramento entre nós e você. Queremos fazer uma aliança com você.

[[v1-26-29]]

^<<v1-26-29,29>>^ Você jura que não nos fará mal, assim como nós também não fizemos nenhum mal a você, mas fizemos somente o bem e o deixamos ir em paz. Você é agora o abençoado do Senhor .

[[v1-26-30]]

^<<v1-26-30,30>>^ Então Isaque lhes deu um banquete, e comeram e beberam.

[[v1-26-31]]

^<<v1-26-31,31>>^ Levantando-se de madrugada, juraram de parte a parte. Isaque os despediu, e eles se foram em paz.

[[v1-26-32]]

^<<v1-26-32,32>>^ Nesse mesmo dia, vieram os servos de Isaque e, dando-lhe notícia do poço que tinham cavado, lhe disseram: — Achamos água.

[[v1-26-33]]

^<<v1-26-33,33>>^ Ao poço, Isaque deu o nome de Seba. Por isso, Berseba é o nome daquela cidade até o dia de hoje.

[[v1-26-34]]

^<<v1-26-34,34>>^ Quando Esaú tinha quarenta anos de idade, tomou por esposa Judite, filha de Beeri, heteu, e Basemate, filha de Elom, heteu.

[[v1-26-35]]

^<<v1-26-35,35>>^ Essas duas se tornaram amargura de espírito para Isaque e para Rebeca.

'''

xref:001-genesis/001-genesis-025.adoc#v1-25-0[&#60; Capítulo Anterior] | <<v1-26-0,Topo>> | xref:001-genesis/001-genesis-027.adoc#v1-27-0[Próximo Capítulo &#62;]