include::./index.adoc[]

[[v1-25-0]]
=== Gênesis, 25
// naa ?, NAA - Nova Almeida Atualizada

[[v1-25-1]]

^<<v1-25-1,1>>^ Abraão casou com outra mulher, que se chamava Quetura.

[[v1-25-2]]

^<<v1-25-2,2>>^ Ela lhe deu à luz Zinrã, Jocsã, Medã, Midiã, Isbaque e Sua.

[[v1-25-3]]

^<<v1-25-3,3>>^ Jocsã gerou Seba e Dedã. Os filhos de Dedã foram: Assurim, Letusim e Leumim.

[[v1-25-4]]

^<<v1-25-4,4>>^ Os filhos de Midiã foram: Efá, Éfer, Enoque, Abida e Elda. Todos estes foram filhos de Quetura.

[[v1-25-5]]

^<<v1-25-5,5>>^ Abraão deu tudo o que tinha a Isaque.

[[v1-25-6]]

^<<v1-25-6,6>>^ Porém, aos filhos das concubinas que tinha, Abraão deu presentes e, ainda em vida, os separou de seu filho Isaque, enviando-os para a terra do Oriente.

[[v1-25-7]]

^<<v1-25-7,7>>^ Os dias da vida de Abraão foram cento e setenta e cinco anos.

[[v1-25-8]]

^<<v1-25-8,8>>^ Abraão expirou e morreu após uma longa velhice, e foi reunido ao seu povo.

[[v1-25-9]]

^<<v1-25-9,9>>^ Os filhos dele, Isaque e Ismael, o sepultaram na caverna de Macpela, no campo de Efrom, filho de Zoar, o heteu, em frente de Manre,

[[v1-25-10]]

^<<v1-25-10,10>>^ o campo que Abraão havia comprado dos filhos de Hete. Ali foram sepultados Abraão e Sara, sua mulher.

[[v1-25-11]]

^<<v1-25-11,11>>^ Depois da morte de Abraão, Deus abençoou Isaque, o filho dele. Isaque morava perto de Beer-Laai-Roi.

[[v1-25-12]]

^<<v1-25-12,12>>^ São estas as gerações de Ismael, filho de Abraão, que Agar, egípcia, serva de Sara, lhe deu à luz.

[[v1-25-13]]

^<<v1-25-13,13>>^ Estes são os nomes dos filhos de Ismael, por ordem de nascimento: o primogênito de Ismael foi Nebaiote; depois, Quedar, Abdeel, Mibsão,

[[v1-25-14]]

^<<v1-25-14,14>>^ Misma, Dumá, Massá,

[[v1-25-15]]

^<<v1-25-15,15>>^ Hadade, Tema, Jetur, Nafis e Quedemá.

[[v1-25-16]]

^<<v1-25-16,16>>^ Estes são os filhos de Ismael e estes são os seus nomes pelas suas aldeias e pelos seus acampamentos: doze príncipes de seus povos.

[[v1-25-17]]

^<<v1-25-17,17>>^ E os anos da vida de Ismael foram cento e trinta e sete; e morreu e foi reunido ao seu povo.

[[v1-25-18]]

^<<v1-25-18,18>>^ Os filhos de Ismael habitaram desde Havilá até Sur, nas imediações do Egito, no caminho para a Assíria. Ele se estabeleceu diante de todos os seus irmãos.

[[v1-25-19]]

^<<v1-25-19,19>>^ São estas as gerações de Isaque, filho de Abraão. Abraão gerou Isaque.

[[v1-25-20]]

^<<v1-25-20,20>>^ Ele tinha quarenta anos quando tomou por esposa Rebeca, filha de Betuel, o arameu de Padã-Arã, e irmã de Labão, o arameu.

[[v1-25-21]]

^<<v1-25-21,21>>^ Isaque orou ao Senhor  por sua mulher, porque ela era estéril. O Senhor  ouviu as orações dele, e Rebeca, a mulher de Isaque, ficou grávida.

[[v1-25-22]]

^<<v1-25-22,22>>^ Os filhos lutavam no ventre dela. Então ela disse: "Por que isso está acontecendo comigo?" E ela foi consultar o Senhor .

[[v1-25-23]]

^<<v1-25-23,23>>^ E o Senhor  lhe respondeu: "Duas nações estão no seu ventre, dois povos, nascidos de você, se dividirão: um povo será mais forte do que o outro, e o mais velho servirá o mais moço."

[[v1-25-24]]

^<<v1-25-24,24>>^ Cumpridos os dias para que desse à luz, eis que havia gêmeos no seu ventre.

[[v1-25-25]]

^<<v1-25-25,25>>^ Nasceu o primeiro, ruivo, todo revestido de pelo; por isso, deram-lhe o nome de Esaú.

[[v1-25-26]]

^<<v1-25-26,26>>^ Depois, nasceu o irmão. Com a mão segurava o calcanhar de Esaú, e por isso lhe deram o nome de Jacó. Isaque tinha sessenta anos quando Rebeca deu à luz.

[[v1-25-27]]

^<<v1-25-27,27>>^ Cresceram os meninos. Esaú tornou-se perito caçador, homem do campo; Jacó, porém, era homem pacato e morava em tendas.

[[v1-25-28]]

^<<v1-25-28,28>>^ Isaque amava Esaú, porque se saboreava de sua caça; Rebeca, porém, amava Jacó.

[[v1-25-29]]

^<<v1-25-29,29>>^ Jacó tinha feito um ensopado, quando Esaú, exausto, veio do campo

[[v1-25-30]]

^<<v1-25-30,30>>^ e lhe disse: — Por favor, me deixe comer um pouco da coisa vermelha, essa coisa vermelha aí, pois estou exausto. (Por isso deram-lhe o nome de Edom.)

[[v1-25-31]]

^<<v1-25-31,31>>^ Jacó respondeu: — Primeiro me venda o seu direito de primogenitura.

[[v1-25-32]]

^<<v1-25-32,32>>^ Ele respondeu: — Estou morrendo de fome; de que me vale o direito de primogenitura?

[[v1-25-33]]

^<<v1-25-33,33>>^ Então Jacó disse: — Primeiro jure. Esaú jurou e vendeu o seu direito de primogenitura a Jacó.

[[v1-25-34]]

^<<v1-25-34,34>>^ E Jacó deu a Esaú pão e o ensopado de lentilhas; ele comeu e bebeu, levantou-se e saiu. Assim, Esaú desprezou o seu direito de primogenitura.

'''

xref:001-genesis/001-genesis-024.adoc#v1-24-0[&#60; Capítulo Anterior] | <<v1-25-0,Topo>> | xref:001-genesis/001-genesis-026.adoc#v1-26-0[Próximo Capítulo &#62;]