include::./index.adoc[]

[[v1-44-0]]
=== Gênesis, 44
// naa ?, NAA - Nova Almeida Atualizada

[[v1-44-1]]

^<<v1-44-1,1>>^ José deu esta ordem ao administrador da sua casa: — Encha de mantimento os sacos que estes homens trouxeram, quanto puderem levar, e ponha o dinheiro de cada um na boca do saco de mantimento.

[[v1-44-2]]

^<<v1-44-2,2>>^ E coloque o meu copo de prata na boca do saco de mantimento do mais novo, junto com o dinheiro do seu cereal. E o administrador fez como José havia ordenado.

[[v1-44-3]]

^<<v1-44-3,3>>^ De manhã, quando já estava claro, os homens partiram, eles com os seus jumentos.

[[v1-44-4]]

^<<v1-44-4,4>>^ Saíram da cidade e, antes que pudessem ter se distanciado, José disse ao administrador de sua casa: — Levante-se e vá atrás daqueles homens. E, alcançando-os, diga o seguinte: "Por que vocês pagaram o bem com o mal?

[[v1-44-5]]

^<<v1-44-5,5>>^ Não é este o copo em que bebe o meu senhor e que ele usa para fazer as suas adivinhações? Vocês fizeram algo muito errado."

[[v1-44-6]]

^<<v1-44-6,6>>^ O administrador os alcançou e lhes falou essas palavras.

[[v1-44-7]]

^<<v1-44-7,7>>^ Então eles responderam: — Por que o meu senhor está dizendo uma coisa dessas? Longe de nós, seus servos, fazer uma coisa assim.

[[v1-44-8]]

^<<v1-44-8,8>>^ O dinheiro que achamos na boca dos sacos de mantimento nós trouxemos de volta da terra de Canaã; como, então, iríamos roubar prata ou ouro da casa do seu senhor?

[[v1-44-9]]

^<<v1-44-9,9>>^ Se algum de nós tiver esse copo, será morto; e nós ainda seremos escravos do meu senhor.

[[v1-44-10]]

^<<v1-44-10,10>>^ O administrador respondeu: — Que seja como vocês disseram. Aquele com quem for encontrado o copo será meu escravo; os outros ficam livres.

[[v1-44-11]]

^<<v1-44-11,11>>^ Eles se apressaram; cada um colocou o seu saco de mantimento no chão e o abriu.

[[v1-44-12]]

^<<v1-44-12,12>>^ O administrador os examinou, começando do mais velho e acabando no mais novo; e o copo foi encontrado no saco de mantimento de Benjamim.

[[v1-44-13]]

^<<v1-44-13,13>>^ Então eles rasgaram as suas roupas; cada um carregou de novo o seu jumento, e eles voltaram para a cidade.

[[v1-44-14]]

^<<v1-44-14,14>>^ Quando Judá e seus irmãos chegaram à casa de José, este ainda estava ali. E prostraram-se em terra diante dele.

[[v1-44-15]]

^<<v1-44-15,15>>^ José lhes perguntou: — O que é isso que vocês fizeram? Vocês não sabiam que um homem como eu é capaz de adivinhar?

[[v1-44-16]]

^<<v1-44-16,16>>^ Então Judá respondeu: — Que podemos dizer a meu senhor? Que podemos falar? E como vamos nos justificar? Deus descobriu a nossa culpa. Eis que somos escravos de meu senhor, tanto nós como aquele em cuja mão se achou o copo.

[[v1-44-17]]

^<<v1-44-17,17>>^ Mas José disse: — Longe de mim fazer uma coisa dessas! O homem em cuja mão foi encontrado o copo, esse será meu escravo; os outros podem voltar em paz para junto de seu pai.

[[v1-44-18]]

^<<v1-44-18,18>>^ Então Judá se aproximou dele e disse: — Meu senhor, permita que este seu servo diga uma palavra aos ouvidos do meu senhor, e não se acenda a sua ira contra este seu servo, pois o senhor é como o próprio Faraó.

[[v1-44-19]]

^<<v1-44-19,19>>^ Meu senhor perguntou a seus servos: "Vocês têm pai ou mais algum irmão?"

[[v1-44-20]]

^<<v1-44-20,20>>^ E respondemos a meu senhor: "Temos um pai já velho e um filho da sua velhice, o mais novo, cujo irmão é morto; e só ele ficou de sua mãe, e seu pai o ama."

[[v1-44-21]]

^<<v1-44-21,21>>^ Então o senhor disse a estes seus servos: "Tragam o jovem, para que eu o veja."

[[v1-44-22]]

^<<v1-44-22,22>>^ Respondemos ao meu senhor: "O jovem não pode deixar o pai; se deixar o pai, este morrerá."

[[v1-44-23]]

^<<v1-44-23,23>>^ Então meu senhor disse a estes seus servos: "Se o irmão mais novo não vier com vocês, nunca mais vocês verão o meu rosto."

[[v1-44-24]]

^<<v1-44-24,24>>^ — Quando voltamos à casa de meu pai, que é seu servo, e repetimos a ele as palavras de meu senhor,

[[v1-44-25]]

^<<v1-44-25,25>>^ nosso pai disse: "Voltem e comprem um pouco de mantimento."

[[v1-44-26]]

^<<v1-44-26,26>>^ Nós respondemos: "Não podemos ir para lá. Mas, se o nosso irmão mais moço for conosco, iremos. Porque não podemos ver a face do homem, se este nosso irmão mais moço não estiver conosco."

[[v1-44-27]]

^<<v1-44-27,27>>^ Então nos disse o seu servo, nosso pai: "Vocês sabem que a minha mulher me deu dois filhos.

[[v1-44-28]]

^<<v1-44-28,28>>^ Um se ausentou de mim, e eu disse: ‘Certamente foi despedaçado, e até agora não mais o vi.’

[[v1-44-29]]

^<<v1-44-29,29>>^ Se agora vocês me tirarem também este da minha presença, e lhe acontecer algum desastre, farão descer os meus cabelos brancos com tristeza à sepultura."

[[v1-44-30]]

^<<v1-44-30,30>>^ — Agora, pois, se eu voltar para junto de meu pai, seu servo, sem que o jovem vá conosco, visto que a alma de meu pai está ligada com a alma dele,

[[v1-44-31]]

^<<v1-44-31,31>>^ vendo ele que o jovem não está conosco, morrerá; e estes seus servos farão descer os cabelos brancos de nosso pai, seu servo, com tristeza à sepultura.

[[v1-44-32]]

^<<v1-44-32,32>>^ Porque este seu servo ficou responsável por este jovem diante de meu pai, dizendo: "Se eu não o trouxer de volta, serei culpado para com o meu pai pelo resto da minha vida."

[[v1-44-33]]

^<<v1-44-33,33>>^ Agora, pois, que este seu servo fique em lugar do jovem como escravo de meu senhor, e que o jovem volte com os seus irmãos.

[[v1-44-34]]

^<<v1-44-34,34>>^ Porque como poderei voltar a meu pai, se o jovem não for comigo? Eu não poderia ver esse mal se abatendo sobre o meu pai.

'''

xref:001-genesis/001-genesis-043.adoc#v1-43-0[&#60; Capítulo Anterior] | <<v1-44-0,Topo>> | xref:001-genesis/001-genesis-045.adoc#v1-45-0[Próximo Capítulo &#62;]