include::./index.adoc[]

[[v1-23-0]]
=== Gênesis, 23
// naa ?, NAA - Nova Almeida Atualizada

[[v1-23-1]]

^<<v1-23-1,1>>^ Sara viveu cento e vinte e sete anos.

[[v1-23-2]]

^<<v1-23-2,2>>^ Morreu em Quiriate-Arba, que é Hebrom, na terra de Canaã. Abraão veio lamentar Sara e chorar por ela.

[[v1-23-3]]

^<<v1-23-3,3>>^ Depois, Abraão levantou-se da presença da falecida e falou aos filhos de Hete:

[[v1-23-4]]

^<<v1-23-4,4>>^ — Sou estrangeiro e morador entre vocês. Deixem-me adquirir uma sepultura na terra de vocês, para que eu possa sepultar a minha falecida mulher.

[[v1-23-5]]

^<<v1-23-5,5>>^ Os filhos de Hete responderam a Abraão, dizendo:

[[v1-23-6]]

^<<v1-23-6,6>>^ — Escute: o senhor é um príncipe de Deus em nosso meio. Sepulte a falecida numa das nossas melhores sepulturas. Nenhum de nós se recusará a ceder a sua própria sepultura, para que você sepulte a sua falecida.

[[v1-23-7]]

^<<v1-23-7,7>>^ Então Abraão se levantou e se inclinou diante do povo da terra, diante dos filhos de Hete.

[[v1-23-8]]

^<<v1-23-8,8>>^ E lhes falou, dizendo: — Se é do agrado de vocês que eu sepulte a minha falecida, escutem-me e intercedam por mim junto a Efrom, filho de Zoar,

[[v1-23-9]]

^<<v1-23-9,9>>^ para que ele me ceda a caverna de Macpela, que pertence a ele e que fica no extremo do seu campo. Que ele a entregue a mim pelo devido preço, para que eu tenha uma sepultura entre vocês.

[[v1-23-10]]

^<<v1-23-10,10>>^ Ora, Efrom, o heteu, estava sentado no meio dos filhos de Hete. Ele respondeu a Abraão, de maneira que pudesse ser ouvido pelos filhos de Hete, a saber, por todos os que entravam pelo portão da cidade:

[[v1-23-11]]

^<<v1-23-11,11>>^ — De modo nenhum, meu senhor. Escute: eu lhe dou o campo e também a caverna que nele está. Na presença dos filhos do meu povo eu lhe dou isso; sepulte a sua falecida.

[[v1-23-12]]

^<<v1-23-12,12>>^ Então Abraão se inclinou diante do povo da terra

[[v1-23-13]]

^<<v1-23-13,13>>^ e falou a Efrom, na presença do povo da terra, dizendo: — Mas, se você concorda, escute: pagarei o preço do campo; aceite-o de mim, e sepultarei ali a minha falecida.

[[v1-23-14]]

^<<v1-23-14,14>>^ Efrom respondeu:

[[v1-23-15]]

^<<v1-23-15,15>>^ — Meu senhor, escute: um terreno que vale quatrocentas barras de prata, que é isso entre mim e você? Sepulte ali a sua falecida.

[[v1-23-16]]

^<<v1-23-16,16>>^ Abraão ouviu Efrom dizer isso e pesou-lhe a prata de que este lhe tinha falado na presença dos filhos de Hete, a saber, quatro quilos e meio de prata, segundo o peso usado entre os mercadores.

[[v1-23-17]]

^<<v1-23-17,17>>^ Assim, o campo de Efrom, que estava em Macpela, em frente de Manre, o campo, a caverna e todo o arvoredo que nele havia, e todo o terreno ao redor

[[v1-23-18]]

^<<v1-23-18,18>>^ passaram a ser propriedade de Abraão, na presença dos filhos de Hete, a saber, de todos os que entravam pelo portão da cidade.

[[v1-23-19]]

^<<v1-23-19,19>>^ Depois, Abraão sepultou Sara, a sua mulher, na caverna do campo de Macpela, em frente de Manre, que é Hebrom, na terra de Canaã.

[[v1-23-20]]

^<<v1-23-20,20>>^ E assim, pelos filhos de Hete, se confirmou a Abraão o direito do campo e da caverna que nele estava, como propriedade para servir de sepultura.

'''

xref:001-genesis/001-genesis-022.adoc#v1-22-0[&#60; Capítulo Anterior] | <<v1-23-0,Topo>> | xref:001-genesis/001-genesis-024.adoc#v1-24-0[Próximo Capítulo &#62;]