include::./index.adoc[]

[[v1-5-0]]
=== Gênesis, 5
// naa ?, NAA - Nova Almeida Atualizada

[[v1-5-1]]

^<<v1-5-1,1>>^ Este é o livro da genealogia de Adão. No dia em que Deus criou o ser humano, à semelhança de Deus o fez.

[[v1-5-2]]

^<<v1-5-2,2>>^ Deus os criou homem e mulher, os abençoou e lhes deu o nome de "ser humano", no dia em que foram criados.

[[v1-5-3]]

^<<v1-5-3,3>>^ Adão viveu cento e trinta anos, e gerou um filho à sua semelhança, conforme a sua imagem, e lhe deu o nome de Sete.

[[v1-5-4]]

^<<v1-5-4,4>>^ Depois que gerou esse filho, Adão viveu oitocentos anos; e teve filhos e filhas.

[[v1-5-5]]

^<<v1-5-5,5>>^ Todos os dias da vida de Adão foram novecentos e trinta anos; e morreu.

[[v1-5-6]]

^<<v1-5-6,6>>^ Sete viveu cento e cinco anos e gerou Enos.

[[v1-5-7]]

^<<v1-5-7,7>>^ Depois que gerou Enos, Sete viveu oitocentos e sete anos; e teve filhos e filhas.

[[v1-5-8]]

^<<v1-5-8,8>>^ Todos os dias de Sete foram novecentos e doze anos; e morreu.

[[v1-5-9]]

^<<v1-5-9,9>>^ Enos viveu noventa anos e gerou Cainã.

[[v1-5-10]]

^<<v1-5-10,10>>^ Depois que gerou Cainã, Enos viveu oitocentos e quinze anos; e teve filhos e filhas.

[[v1-5-11]]

^<<v1-5-11,11>>^ Todos os dias de Enos foram novecentos e cinco anos; e morreu.

[[v1-5-12]]

^<<v1-5-12,12>>^ Cainã viveu setenta anos e gerou Maalalel.

[[v1-5-13]]

^<<v1-5-13,13>>^ Depois que gerou Maalalel, Cainã viveu oitocentos e quarenta anos; e teve filhos e filhas.

[[v1-5-14]]

^<<v1-5-14,14>>^ Todos os dias de Cainã foram novecentos e dez anos; e morreu.

[[v1-5-15]]

^<<v1-5-15,15>>^ Maalalel viveu sessenta e cinco anos e gerou Jarede.

[[v1-5-16]]

^<<v1-5-16,16>>^ Depois que gerou Jarede, Maalalel viveu oitocentos e trinta anos; e teve filhos e filhas.

[[v1-5-17]]

^<<v1-5-17,17>>^ Todos os dias de Maalalel foram oitocentos e noventa e cinco anos; e morreu.

[[v1-5-18]]

^<<v1-5-18,18>>^ Jarede viveu cento e sessenta e dois anos e gerou Enoque.

[[v1-5-19]]

^<<v1-5-19,19>>^ Depois que gerou Enoque, Jarede viveu oitocentos anos; e teve filhos e filhas.

[[v1-5-20]]

^<<v1-5-20,20>>^ Todos os dias de Jarede foram novecentos e sessenta e dois anos; e morreu.

[[v1-5-21]]

^<<v1-5-21,21>>^ Enoque viveu sessenta e cinco anos e gerou Metusalém.

[[v1-5-22]]

^<<v1-5-22,22>>^ Enoque andou com Deus; e, depois que gerou Metusalém, viveu trezentos anos; e teve filhos e filhas.

[[v1-5-23]]

^<<v1-5-23,23>>^ Todos os dias de Enoque foram trezentos e sessenta e cinco anos.

[[v1-5-24]]

^<<v1-5-24,24>>^ Enoque andou com Deus e não foi mais visto, porque Deus o levou para junto de si.

[[v1-5-25]]

^<<v1-5-25,25>>^ Metusalém viveu cento e oitenta e sete anos e gerou Lameque.

[[v1-5-26]]

^<<v1-5-26,26>>^ Depois que gerou Lameque, Metusalém viveu setecentos e oitenta e dois anos; e teve filhos e filhas.

[[v1-5-27]]

^<<v1-5-27,27>>^ Todos os dias de Metusalém foram novecentos e sessenta e nove anos; e morreu.

[[v1-5-28]]

^<<v1-5-28,28>>^ Lameque viveu cento e oitenta e dois anos e gerou um filho.

[[v1-5-29]]

^<<v1-5-29,29>>^ Deu-lhe o nome de Noé, dizendo: — Este nos consolará dos nossos trabalhos e das fadigas de nossas mãos, nesta terra que o Senhor  amaldiçoou.

[[v1-5-30]]

^<<v1-5-30,30>>^ Depois que gerou Noé, Lameque viveu quinhentos e noventa e cinco anos; e teve filhos e filhas.

[[v1-5-31]]

^<<v1-5-31,31>>^ Todos os dias de Lameque foram setecentos e setenta e sete anos; e morreu.

[[v1-5-32]]

^<<v1-5-32,32>>^ Noé tinha quinhentos anos de idade e gerou Sem, Cam e Jafé.

'''

xref:001-genesis/001-genesis-004.adoc#v1-4-0[&#60; Capítulo Anterior] | <<v1-5-0,Topo>> | xref:001-genesis/001-genesis-006.adoc#v1-6-0[Próximo Capítulo &#62;]