include::./index.adoc[]

[[v1-31-0]]
=== Gênesis, 31
// naa ?, NAA - Nova Almeida Atualizada

[[v1-31-1]]

^<<v1-31-1,1>>^ Jacó ouvia os comentários dos filhos de Labão, que diziam: — Jacó se apossou de tudo o que era de nosso pai. Ele juntou toda essa riqueza a partir do que era de nosso pai.

[[v1-31-2]]

^<<v1-31-2,2>>^ Jacó, por sua vez, reparou que o rosto de Labão não lhe era favorável como anteriormente.

[[v1-31-3]]

^<<v1-31-3,3>>^ E o Senhor  disse a Jacó: — Volte para a terra de seus pais e para a sua parentela; e eu estarei com você.

[[v1-31-4]]

^<<v1-31-4,4>>^ Então Jacó mandou vir Raquel e Lia ao campo, para junto do seu rebanho,

[[v1-31-5]]

^<<v1-31-5,5>>^ e lhes disse: — Vejo que o rosto do pai de vocês não me é favorável como anteriormente; porém o Deus de meu pai tem estado comigo.

[[v1-31-6]]

^<<v1-31-6,6>>^ Vocês mesmas sabem que com todo empenho tenho trabalhado para o pai de vocês,

[[v1-31-7]]

^<<v1-31-7,7>>^ mas ele me tem enganado e por dez vezes mudou o meu salário; porém Deus não permitiu que ele me prejudicasse.

[[v1-31-8]]

^<<v1-31-8,8>>^ Se ele dizia: "Os salpicados serão o seu salário", então todos os rebanhos davam salpicados; e, se ele dizia: "Os listrados serão o seu salário", então os rebanhos todos davam listrados.

[[v1-31-9]]

^<<v1-31-9,9>>^ Assim, Deus tirou o gado do pai de vocês e o deu a mim.

[[v1-31-10]]

^<<v1-31-10,10>>^ — Pois, chegado o tempo em que os animais acasalavam, levantei os olhos e vi em sonhos que os machos que cobriam as ovelhas eram listrados, salpicados e malhados.

[[v1-31-11]]

^<<v1-31-11,11>>^ E o Anjo de Deus me disse em sonho: "Jacó!" E eu respondi: "Eis-me aqui!"

[[v1-31-12]]

^<<v1-31-12,12>>^ Ele continuou: "Levante agora os olhos e veja que todos os machos que cobrem o rebanho são listrados, salpicados e malhados, porque vejo tudo o que Labão está fazendo com você.

[[v1-31-13]]

^<<v1-31-13,13>>^ Eu sou o Deus de Betel, onde você ungiu uma coluna, onde me fez um voto. Levante-se agora, saia desta terra e volte para a terra de sua parentela."

[[v1-31-14]]

^<<v1-31-14,14>>^ Então Raquel e Lia disseram: — Será que ainda existe para nós parte ou herança na casa de nosso pai?

[[v1-31-15]]

^<<v1-31-15,15>>^ Não é verdade que ele nos considera como estrangeiras? Pois nos vendeu e consumiu tudo o que nos era devido.

[[v1-31-16]]

^<<v1-31-16,16>>^ Porque toda a riqueza que Deus tirou de nosso pai é nossa e de nossos filhos; agora, pois, faça tudo o que Deus pediu que você fizesse.

[[v1-31-17]]

^<<v1-31-17,17>>^ Então Jacó se levantou e, fazendo montar seus filhos e suas mulheres em camelos,

[[v1-31-18]]

^<<v1-31-18,18>>^ levou todo o seu gado e todos os seus bens que chegou a possuir, o gado de sua propriedade que havia acumulado em Padã-Arã, para ir a Isaque, seu pai, à terra de Canaã.

[[v1-31-19]]

^<<v1-31-19,19>>^ Enquanto Labão tinha ido fazer a tosquia das ovelhas, Raquel roubou os ídolos do lar que pertenciam a seu pai.

[[v1-31-20]]

^<<v1-31-20,20>>^ E Jacó enganou Labão, o arameu, não revelando que tinha planos de fugir.

[[v1-31-21]]

^<<v1-31-21,21>>^ E fugiu com tudo o que lhe pertencia. Levantou-se, passou o Eufrates e tomou o rumo dos montes de Gileade.

[[v1-31-22]]

^<<v1-31-22,22>>^ No terceiro dia, Labão foi avisado de que Jacó ia fugindo.

[[v1-31-23]]

^<<v1-31-23,23>>^ Reuniu os seus parentes e saiu no encalço de Jacó, por sete dias de viagem, e o alcançou nos montes de Gileade.

[[v1-31-24]]

^<<v1-31-24,24>>^ De noite, porém, Deus veio em sonhos a Labão, o arameu, e lhe disse: — Cuidado! Não fale a Jacó nem bem nem mal.

[[v1-31-25]]

^<<v1-31-25,25>>^ Labão alcançou Jacó. Este havia armado a sua tenda naqueles montes. Também Labão armou a sua tenda com os seus parentes, nos montes de Gileade.

[[v1-31-26]]

^<<v1-31-26,26>>^ E Labão disse a Jacó: — Que foi que você fez? Você me enganou e levou as minhas filhas como se fossem prisioneiras de guerra.

[[v1-31-27]]

^<<v1-31-27,27>>^ Por que você fugiu em segredo, e me enganou, e não me disse nada? Eu o teria despedido com alegria, com cânticos, com tamborins e com harpa.

[[v1-31-28]]

^<<v1-31-28,28>>^ E por que não permitiu que eu beijasse meus netos e minhas filhas? Nisso você agiu como um tolo.

[[v1-31-29]]

^<<v1-31-29,29>>^ Tenho em minhas mãos poder para fazer mal a vocês, mas ontem à noite o Deus do pai de vocês me falou e disse: "Cuidado! Não fale a Jacó nem bem nem mal."

[[v1-31-30]]

^<<v1-31-30,30>>^ E agora que você partiu de vez, pois está com saudades da casa de seu pai, por que roubou os meus deuses?

[[v1-31-31]]

^<<v1-31-31,31>>^ Jacó respondeu: — Porque tive medo. Pensei assim: para que não aconteça que me tome à força as suas filhas.

[[v1-31-32]]

^<<v1-31-32,32>>^ Que seja morto aquele com quem o senhor achar os seus deuses. Na presença de nossos parentes, verifique o que pertence ao senhor e, se estiver comigo, pode levar embora. Acontece que Jacó não sabia que Raquel os havia roubado.

[[v1-31-33]]

^<<v1-31-33,33>>^ Labão entrou na tenda de Jacó, na tenda de Lia e na tenda das duas servas, mas não achou nada. Tendo saído da tenda de Lia, entrou na tenda de Raquel.

[[v1-31-34]]

^<<v1-31-34,34>>^ Ora, Raquel havia pegado os ídolos do lar e, depois de colocá-los na sela de um camelo, estava sentada sobre eles. Labão apalpou toda a tenda e não os achou.

[[v1-31-35]]

^<<v1-31-35,35>>^ Então Raquel disse ao pai: — Não fique zangado, meu senhor, por eu não poder me levantar na sua presença, pois estou no meu período menstrual. Ele procurou, mas não encontrou os ídolos do lar.

[[v1-31-36]]

^<<v1-31-36,36>>^ Então Jacó ficou zangado e discutiu com Labão. Dirigiu-se a Labão, dizendo: — Qual é a minha transgressão? Qual o meu pecado, para o senhor me perseguir com tanta fúria?

[[v1-31-37]]

^<<v1-31-37,37>>^ Havendo apalpado todos os meus utensílios, quais foram os utensílios de sua casa que o senhor encontrou? Coloque-os aqui diante dos meus parentes e dos seus parentes, para que julguem entre nós dois.

[[v1-31-38]]

^<<v1-31-38,38>>^ Vinte anos eu estive com o senhor. As suas ovelhas e as suas cabras nunca perderam as crias, e não comi um só carneiro do seu rebanho.

[[v1-31-39]]

^<<v1-31-39,39>>^ Não lhe apresentei os animais que eram despedaçados pelas feras; assumi o prejuízo. Da minha mão o senhor o requeria, tanto o roubado de dia como de noite.

[[v1-31-40]]

^<<v1-31-40,40>>^ De maneira que eu andava, de dia consumido pelo calor, de noite, pela geada; e o meu sono me fugia dos olhos.

[[v1-31-41]]

^<<v1-31-41,41>>^ Vinte anos permaneci em sua casa. Catorze anos trabalhei para o senhor pelas suas duas filhas e seis anos trabalhei para conseguir o seu rebanho; dez vezes o senhor mudou o meu salário.

[[v1-31-42]]

^<<v1-31-42,42>>^ Se não fosse o Deus de meu pai, o Deus de Abraão e o Temor de Isaque, por certo o senhor me despediria agora de mãos vazias. Mas Deus viu o meu sofrimento e o trabalho das minhas mãos e ontem à noite ele repreendeu o senhor.

[[v1-31-43]]

^<<v1-31-43,43>>^ Então Labão respondeu a Jacó: — As filhas são minhas filhas, os filhos são meus netos, os rebanhos são meus rebanhos, e tudo o que você está vendo é meu. Que posso fazer hoje a estas minhas filhas ou aos filhos que elas deram à luz?

[[v1-31-44]]

^<<v1-31-44,44>>^ Venha, pois, e façamos uma aliança, eu e você, que sirva de testemunho entre mim e você.

[[v1-31-45]]

^<<v1-31-45,45>>^ Então Jacó tomou uma pedra e a erigiu por coluna.

[[v1-31-46]]

^<<v1-31-46,46>>^ E disse aos seus parentes: — Ajuntem pedras. Eles foram ajuntar pedras e fizeram um montão, ao lado do qual comeram.

[[v1-31-47]]

^<<v1-31-47,47>>^ Labão deu-lhe o nome de Jegar-Saaduta, mas Jacó lhe chamou Galeede.

[[v1-31-48]]

^<<v1-31-48,48>>^ E Labão disse: — Seja hoje este montão de pedras por testemunha entre mim e você. Por isso foi chamado de Galeede

[[v1-31-49]]

^<<v1-31-49,49>>^ e Mispa, pois disse: — Que o Senhor  vigie entre mim e você e nos julgue quando estivermos separados um do outro.

[[v1-31-50]]

^<<v1-31-50,50>>^ Se você maltratar as minhas filhas e tomar outras mulheres além delas, não estando ninguém conosco, lembre-se de que Deus é testemunha entre mim e você.

[[v1-31-51]]

^<<v1-31-51,51>>^ E Labão continuou: — Eis aqui este montão de pedras e esta coluna que levantei entre mim e você.

[[v1-31-52]]

^<<v1-31-52,52>>^ Seja o montão testemunha, e seja a coluna testemunha de que para mal não passarei para o lado de lá do montão e você não passará para o lado de cá do montão e da coluna.

[[v1-31-53]]

^<<v1-31-53,53>>^ O Deus de Abraão e o Deus de Naor, o Deus do pai deles, julgue entre nós. E Jacó jurou pelo Temor de Isaque, seu pai.

[[v1-31-54]]

^<<v1-31-54,54>>^ E Jacó ofereceu um sacrifício na montanha e convidou seus parentes para uma refeição. Eles comeram e passaram a noite na montanha.

[[v1-31-55]]

^<<v1-31-55,55>>^ Na manhã seguinte, Labão se levantou de madrugada, beijou os seus netos e as suas filhas e os abençoou. E, partindo, voltou para a sua casa.

'''

xref:001-genesis/001-genesis-030.adoc#v1-30-0[&#60; Capítulo Anterior] | <<v1-31-0,Topo>> | xref:001-genesis/001-genesis-032.adoc#v1-32-0[Próximo Capítulo &#62;]