include::./index.adoc[]

[[v1-12-0]]
=== Gênesis, 12
// naa ?, NAA - Nova Almeida Atualizada

[[v1-12-1]]

^<<v1-12-1,1>>^ O Senhor  disse a Abrão: — Saia da sua terra, da sua parentela e da casa do seu pai e vá para a terra que lhe mostrarei.

[[v1-12-2]]

^<<v1-12-2,2>>^ Farei de você uma grande nação, e o abençoarei, e engrandecerei o seu nome. Seja uma bênção!

[[v1-12-3]]

^<<v1-12-3,3>>^ Abençoarei aqueles que o abençoarem e amaldiçoarei aquele que o amaldiçoar. Em você serão benditas todas as famílias da terra.

[[v1-12-4]]

^<<v1-12-4,4>>^ Partiu, pois, Abrão, como o Senhor  lhe havia ordenado. E Ló foi com ele. Abrão tinha setenta e cinco anos quando saiu de Harã.

[[v1-12-5]]

^<<v1-12-5,5>>^ Abrão levou consigo a sua mulher Sarai, o seu sobrinho Ló, todos os bens que haviam adquirido e as pessoas que lhes foram acrescentadas em Harã. Partiram para a terra de Canaã e lá chegaram.

[[v1-12-6]]

^<<v1-12-6,6>>^ Abrão atravessou a terra até Siquém, até o carvalho de Moré. Nesse tempo os cananeus habitavam essa terra.

[[v1-12-7]]

^<<v1-12-7,7>>^ O Senhor  apareceu a Abrão e lhe disse: — Darei esta terra à sua descendência. Ali Abrão edificou um altar ao Senhor , que lhe tinha aparecido.

[[v1-12-8]]

^<<v1-12-8,8>>^ Passando dali para o monte a leste de Betel, armou a sua tenda, ficando Betel a oeste e Ai a leste. Ali edificou um altar ao Senhor  e invocou o nome do Senhor .

[[v1-12-9]]

^<<v1-12-9,9>>^ Depois, Abrão partiu dali, indo sempre na direção do Neguebe.

[[v1-12-10]]

^<<v1-12-10,10>>^ Havia fome naquela terra. Assim, Abrão foi para o Egito, para ali ficar, porque era grande a fome na terra.

[[v1-12-11]]

^<<v1-12-11,11>>^ Quando se aproximava do Egito, quase ao entrar, disse a Sarai, sua mulher: — Ora, bem sei que você é uma mulher muito bonita.

[[v1-12-12]]

^<<v1-12-12,12>>^ Os egípcios, quando virem você, vão dizer: "Essa é a mulher dele." Então eles vão me matar, deixando você com vida.

[[v1-12-13]]

^<<v1-12-13,13>>^ Diga, pois, que você é minha irmã, para que me tratem bem por sua causa e, por amor a você, me conservem a vida.

[[v1-12-14]]

^<<v1-12-14,14>>^ Tendo Abrão entrado no Egito, os egípcios viram que a mulher era, de fato, muito bonita.

[[v1-12-15]]

^<<v1-12-15,15>>^ Os príncipes de Faraó a viram e foram elogiá-la diante de Faraó. E a mulher foi levada para a casa de Faraó.

[[v1-12-16]]

^<<v1-12-16,16>>^ Este, por causa dela, tratou bem a Abrão, o qual veio a ter ovelhas, bois, jumentos, escravos e escravas, jumentas e camelos.

[[v1-12-17]]

^<<v1-12-17,17>>^ Porém o Senhor  puniu Faraó e a sua casa com grandes pragas, por causa de Sarai, mulher de Abrão.

[[v1-12-18]]

^<<v1-12-18,18>>^ Faraó chamou Abrão e lhe disse: — O que é isso que você fez comigo? Por que não me disse que ela era a sua mulher?

[[v1-12-19]]

^<<v1-12-19,19>>^ E por que me disse que ela era sua irmã? Foi por isso que a tomei para ser minha mulher. Agora, pois, aqui está a sua mulher; tome-a e vá embora daqui.

[[v1-12-20]]

^<<v1-12-20,20>>^ E Faraó deu ordens aos seus servos a respeito de Abrão e eles o acompanharam, a ele, a sua mulher e a tudo o que possuía.

'''

xref:001-genesis/001-genesis-011.adoc#v1-11-0[&#60; Capítulo Anterior] | <<v1-12-0,Topo>> | xref:001-genesis/001-genesis-013.adoc#v1-13-0[Próximo Capítulo &#62;]