include::./index.adoc[]

[[v1-33-0]]
=== Gênesis, 33
// naa ?, NAA - Nova Almeida Atualizada

[[v1-33-1]]

^<<v1-33-1,1>>^ Quando Jacó ergueu os olhos, viu que Esaú se aproximava, e com ele quatrocentos homens. Então repartiu os filhos entre Lia, Raquel e as duas servas.

[[v1-33-2]]

^<<v1-33-2,2>>^ Pôs as servas e seus filhos à frente, Lia e seus filhos atrás deles e Raquel e José por último.

[[v1-33-3]]

^<<v1-33-3,3>>^ E ele mesmo, adiantando-se, prostrou-se em terra sete vezes, até aproximar-se de seu irmão.

[[v1-33-4]]

^<<v1-33-4,4>>^ Então Esaú correu ao encontro dele e o abraçou; pôs os braços em volta do pescoço dele e o beijou; e choraram.

[[v1-33-5]]

^<<v1-33-5,5>>^ Daí, levantando os olhos, Esaú viu as mulheres e os meninos e disse: — Quem são estes que estão com você? Jacó respondeu: — Os filhos com que Deus agraciou este seu servo.

[[v1-33-6]]

^<<v1-33-6,6>>^ Então se aproximaram as servas, elas e seus filhos, e se prostraram.

[[v1-33-7]]

^<<v1-33-7,7>>^ Chegaram também Lia e seus filhos e se prostraram. Por último chegaram José e Raquel e se prostraram.

[[v1-33-8]]

^<<v1-33-8,8>>^ Esaú perguntou: — Qual é o seu propósito com todos esses grupos que encontrei? Jacó respondeu: — É para obter favor na presença de meu senhor.

[[v1-33-9]]

^<<v1-33-9,9>>^ Então Esaú disse: — Eu tenho muitos bens, meu irmão; guarde o que você tem.

[[v1-33-10]]

^<<v1-33-10,10>>^ Mas Jacó insistiu: — Não recuse. Se alcancei favor na sua presença, peço que aceite o meu presente, porque ver o seu rosto é como contemplar o semblante de Deus; e você me acolheu tão bem.

[[v1-33-11]]

^<<v1-33-11,11>>^ Portanto, aceite o meu presente, que eu lhe trouxe. Porque Deus tem sido generoso para comigo, e tenho fartura. E insistiu com ele, até que o aceitou.

[[v1-33-12]]

^<<v1-33-12,12>>^ Então Esaú disse: — Vamos partir e seguir viagem. Eu irei à sua frente.

[[v1-33-13]]

^<<v1-33-13,13>>^ Porém Jacó lhe disse: — Meu senhor sabe que estes meninos são fracos, e tenho comigo ovelhas e vacas de leite. Se forçados a caminhar demais um só dia, morrerão todos os rebanhos.

[[v1-33-14]]

^<<v1-33-14,14>>^ Passe meu senhor adiante de seu servo; eu seguirei aos poucos, no passo do gado que me vai à frente e no passo dos meninos, até chegar a meu senhor, em Seir.

[[v1-33-15]]

^<<v1-33-15,15>>^ Esaú respondeu: — Então permita que eu deixe com você alguns dessa gente que está comigo. Jacó respondeu: — Para quê? Basta que eu alcance favor aos olhos de meu senhor.

[[v1-33-16]]

^<<v1-33-16,16>>^ Assim, naquele dia Esaú voltou para Seir, pelo caminho por onde tinha vindo.

[[v1-33-17]]

^<<v1-33-17,17>>^ E Jacó foi para Sucote, e edificou para si uma casa, e fez cabanas para o seu gado. Por isso, o lugar se chamou Sucote.

[[v1-33-18]]

^<<v1-33-18,18>>^ Voltando de Padã-Arã, Jacó chegou são e salvo à cidade de Siquém, que está na terra de Canaã, e armou a sua tenda junto da cidade.

[[v1-33-19]]

^<<v1-33-19,19>>^ A parte do campo, onde tinha armado a sua tenda, ele a comprou dos filhos de Hamor, pai de Siquém, por cem peças de dinheiro.

[[v1-33-20]]

^<<v1-33-20,20>>^ E levantou ali um altar e lhe deu o nome de "Deus, o Deus de Israel".

'''

xref:001-genesis/001-genesis-032.adoc#v1-32-0[&#60; Capítulo Anterior] | <<v1-33-0,Topo>> | xref:001-genesis/001-genesis-034.adoc#v1-34-0[Próximo Capítulo &#62;]