include::./index.adoc[]

[[v1-2-0]]
=== Gênesis, 2
// naa ?, NAA - Nova Almeida Atualizada

[[v1-2-1]]

^<<v1-2-1,1>>^ Assim, pois, foram acabados os céus e a terra e tudo o que neles há.

[[v1-2-2]]

^<<v1-2-2,2>>^ E, havendo Deus terminado no sétimo dia a sua obra, que tinha feito, descansou nesse dia de toda a obra que tinha feito.

[[v1-2-3]]

^<<v1-2-3,3>>^ E Deus abençoou o sétimo dia e o santificou; porque nele descansou de toda a obra que, como Criador, tinha feito.

[[v1-2-4]]

^<<v1-2-4,4>>^ Esta é a gênese dos céus e da terra quando foram criados, quando o Senhor  Deus os criou.

[[v1-2-5]]

^<<v1-2-5,5>>^ Não havia ainda nenhuma planta do campo na terra, pois ainda nenhuma erva do campo havia brotado; porque o Senhor  Deus não tinha feito chover sobre a terra, e também não havia ninguém para cultivar o solo.

[[v1-2-6]]

^<<v1-2-6,6>>^ Mas uma neblina subia da terra e regava toda a superfície do solo.

[[v1-2-7]]

^<<v1-2-7,7>>^ Então o Senhor  Deus formou o homem do pó da terra e lhe soprou nas narinas o fôlego de vida, e o homem se tornou um ser vivente.

[[v1-2-8]]

^<<v1-2-8,8>>^ E o Senhor  Deus plantou um jardim no Éden, na direção do Oriente, e pôs nele o homem que havia formado.

[[v1-2-9]]

^<<v1-2-9,9>>^ Do solo o Senhor  Deus fez brotar todo tipo de árvores agradáveis à vista e boas para alimento; e também a árvore da vida no meio do jardim e a árvore do conhecimento do bem e do mal.

[[v1-2-10]]

^<<v1-2-10,10>>^ E um rio saía do Éden para regar o jardim e de lá se dividia, repartindo-se em quatro braços.

[[v1-2-11]]

^<<v1-2-11,11>>^ O nome do primeiro é Pisom, que rodeia a terra de Havilá, onde há ouro.

[[v1-2-12]]

^<<v1-2-12,12>>^ O ouro dessa terra é bom; também se encontram lá o bdélio e a pedra de ônix.

[[v1-2-13]]

^<<v1-2-13,13>>^ O nome do segundo rio é Giom; é o que rodeia a terra de Cuxe.

[[v1-2-14]]

^<<v1-2-14,14>>^ O nome do terceiro rio é Tigre; é o que corre pelo leste da Assíria. E o quarto rio é o Eufrates.

[[v1-2-15]]

^<<v1-2-15,15>>^ O Senhor  Deus tomou o homem e o colocou no jardim do Éden para o cultivar e o guardar.

[[v1-2-16]]

^<<v1-2-16,16>>^ E o Senhor  Deus ordenou ao homem: — De toda árvore do jardim você pode comer livremente,

[[v1-2-17]]

^<<v1-2-17,17>>^ mas da árvore do conhecimento do bem e do mal você não deve comer; porque, no dia em que dela comer, você certamente morrerá.

[[v1-2-18]]

^<<v1-2-18,18>>^ O Senhor  Deus disse ainda: — Não é bom que o homem esteja só; farei para ele uma auxiliadora que seja semelhante a ele.

[[v1-2-19]]

^<<v1-2-19,19>>^ Havendo, pois, o Senhor  Deus formado da terra todos os animais do campo e todas as aves dos céus, trouxe-os a Adão, para ver que nome lhes daria; e o nome que ele desse a todos os seres vivos, esse seria o nome deles.

[[v1-2-20]]

^<<v1-2-20,20>>^ O homem deu nome a todos os animais domésticos, às aves dos céus e a todos os animais selvagens; mas para o homem não se achava uma auxiliadora que fosse semelhante a ele.

[[v1-2-21]]

^<<v1-2-21,21>>^ Então o Senhor  Deus fez cair um pesado sono sobre o homem, e este adormeceu. Tirou-lhe uma das costelas e fechou o lugar com carne.

[[v1-2-22]]

^<<v1-2-22,22>>^ E da costela que havia tirado do homem, o Senhor  Deus formou uma mulher e a levou até ele.

[[v1-2-23]]

^<<v1-2-23,23>>^ E o homem disse: "Esta, afinal, é osso dos meus ossos e carne da minha carne; será chamada varoa, porque do varão foi tirada."

[[v1-2-24]]

^<<v1-2-24,24>>^ Por isso, o homem deixa pai e mãe e se une à sua mulher, tornando-se os dois uma só carne.

[[v1-2-25]]

^<<v1-2-25,25>>^ Ora, um e outro, o homem e a sua mulher, estavam nus e não se envergonhavam.

'''

xref:001-genesis/001-genesis-001.adoc#v1-1-0[&#60; Capítulo Anterior] | <<v1-2-0,Topo>> | xref:001-genesis/001-genesis-003.adoc#v1-3-0[Próximo Capítulo &#62;]