include::./index.adoc[]

[[v1-20-0]]
=== Gênesis, 20
// naa ?, NAA - Nova Almeida Atualizada

[[v1-20-1]]

^<<v1-20-1,1>>^ Abraão partiu dali e foi para a terra do Neguebe. Habitou entre Cades e Sur e morou em Gerar.

[[v1-20-2]]

^<<v1-20-2,2>>^ Abraão dizia que Sara, a mulher dele, era sua irmã. Então Abimeleque, rei de Gerar, mandou buscá-la.

[[v1-20-3]]

^<<v1-20-3,3>>^ Deus, porém, veio a Abimeleque em sonhos de noite e lhe disse: — Você vai ser castigado com a morte por causa da mulher que tomou, porque ela tem marido.

[[v1-20-4]]

^<<v1-20-4,4>>^ Ora, Abimeleque ainda não havia se aproximado de Sara e por isso disse: — Senhor, matarás até uma nação inocente?

[[v1-20-5]]

^<<v1-20-5,5>>^ Não foi ele mesmo que me disse: "É minha irmã"? E ela também me disse: "Ele é meu irmão." Com sinceridade de coração e na minha inocência foi que eu fiz isso.

[[v1-20-6]]

^<<v1-20-6,6>>^ Deus respondeu-lhe em sonho: — Bem sei que com sinceridade de coração você fez isso. Por isso impedi que você pecasse contra mim e não permiti que você tocasse nela.

[[v1-20-7]]

^<<v1-20-7,7>>^ Agora devolva a mulher a seu marido, pois ele é profeta e intercederá por você, e você viverá. Mas, se não a devolver, saiba que você certamente morrerá, você e tudo o que é seu.

[[v1-20-8]]

^<<v1-20-8,8>>^ Abimeleque levantou-se de madrugada, chamou todos os seus servos e lhes contou todas essas coisas. E os homens ficaram com muito medo.

[[v1-20-9]]

^<<v1-20-9,9>>^ Então Abimeleque chamou Abraão e lhe disse: — O que é isso que você fez conosco? Em que foi que pequei contra você, para que você trouxesse tamanho pecado sobre mim e sobre o meu reino? O que você me fez é coisa que não se deve fazer.

[[v1-20-10]]

^<<v1-20-10,10>>^ E Abimeleque perguntou a Abraão: — O que é que levou você a fazer uma coisa dessas?

[[v1-20-11]]

^<<v1-20-11,11>>^ Abraão respondeu: — É que eu pensei: "Certamente não há temor de Deus neste lugar, e eles me matarão por causa de minha mulher."

[[v1-20-12]]

^<<v1-20-12,12>>^ Por outro lado, ela é, de fato, minha irmã por parte de pai, embora não por parte de mãe; e veio a ser minha mulher.

[[v1-20-13]]

^<<v1-20-13,13>>^ Quando Deus me fez sair da casa de meu pai para andar errante por aí, eu disse a ela: "Este é o favor que você me fará: em todo lugar para onde formos você dirá que eu sou o seu irmão."

[[v1-20-14]]

^<<v1-20-14,14>>^ Então Abimeleque tomou ovelhas, bois, servos e servas e os deu a Abraão; e lhe devolveu Sara, sua mulher.

[[v1-20-15]]

^<<v1-20-15,15>>^ Abimeleque disse: — A minha terra está diante de você; more onde melhor lhe parecer.

[[v1-20-16]]

^<<v1-20-16,16>>^ E a Sara ele disse: — Dei mil moedas de prata ao seu irmão, como compensação por tudo o que aconteceu com você; e diante de todos você está justificada.

[[v1-20-17]]

^<<v1-20-17,17>>^ Abraão intercedeu junto a Deus e ele curou Abimeleque, a mulher e as servas dele, de modo que elas pudessem ter filhos.

[[v1-20-18]]

^<<v1-20-18,18>>^ Porque o Senhor  havia tornado estéreis todas as mulheres da casa de Abimeleque, por causa de Sara, mulher de Abraão.

'''

xref:001-genesis/001-genesis-019.adoc#v1-19-0[&#60; Capítulo Anterior] | <<v1-20-0,Topo>> | xref:001-genesis/001-genesis-021.adoc#v1-21-0[Próximo Capítulo &#62;]