include::./index.adoc[]

[[v1-14-0]]
=== Gênesis, 14
// naa ?, NAA - Nova Almeida Atualizada

[[v1-14-1]]

^<<v1-14-1,1>>^ Naquele tempo Anrafel, rei de Sinar, Arioque, rei de Elasar, Quedorlaomer, rei de Elão, e Tidal, rei de Goim,

[[v1-14-2]]

^<<v1-14-2,2>>^ fizeram guerra contra Bera, rei de Sodoma, contra Birsa, rei de Gomorra, contra Sinabe, rei de Admá, contra Semeber, rei de Zeboim, e contra o rei de Bela, também chamada de Zoar.

[[v1-14-3]]

^<<v1-14-3,3>>^ Todos estes se ajuntaram no vale de Sidim, onde fica o mar Salgado.

[[v1-14-4]]

^<<v1-14-4,4>>^ Durante doze anos serviram Quedorlaomer, porém no décimo terceiro eles se rebelaram.

[[v1-14-5]]

^<<v1-14-5,5>>^ No décimo quarto ano, veio Quedorlaomer e os reis que estavam com ele e derrotaram os refains em Asterote-Carnaim, e os zuzins em Hã, e os emins em Savé-Quiriataim,

[[v1-14-6]]

^<<v1-14-6,6>>^ e os horeus no seu monte Seir, até El-Parã, que está junto ao deserto.

[[v1-14-7]]

^<<v1-14-7,7>>^ De volta passaram em En-Mispate, que é Cades, e conquistaram toda a terra dos amalequitas e dos amorreus, que moravam em Hazazom-Tamar.

[[v1-14-8]]

^<<v1-14-8,8>>^ Então saíram os reis de Sodoma, de Gomorra, de Admá, de Zeboim e de Bela, que é Zoar, e se prepararam para a batalha contra eles no vale de Sidim,

[[v1-14-9]]

^<<v1-14-9,9>>^ contra Quedorlaomer, rei de Elão, contra Tidal, rei de Goim, contra Anrafel, rei de Sinar, contra Arioque, rei de Elasar. Eram quatro reis contra cinco.

[[v1-14-10]]

^<<v1-14-10,10>>^ Ora, o vale de Sidim estava cheio de poços de betume. Os reis de Sodoma e de Gomorra fugiram. Alguns caíram nesses poços, e os restantes fugiram para um monte.

[[v1-14-11]]

^<<v1-14-11,11>>^ Os reis vitoriosos pegaram todos os bens de Sodoma e de Gomorra e todo o seu mantimento e se foram.

[[v1-14-12]]

^<<v1-14-12,12>>^ Apossaram-se também de Ló, sobrinho de Abrão, que morava em Sodoma, e dos seus bens; e partiram.

[[v1-14-13]]

^<<v1-14-13,13>>^ Porém um homem que conseguiu escapar veio e contou tudo a Abrão, o hebreu. Este morava junto dos carvalhais de Manre, o amorreu, irmão de Escol e de Aner, os quais eram aliados de Abrão.

[[v1-14-14]]

^<<v1-14-14,14>>^ Quando Abrão soube que o seu sobrinho estava preso, fez sair trezentos e dezoito homens dos mais capazes, nascidos em sua casa, e perseguiu os inimigos até Dã.

[[v1-14-15]]

^<<v1-14-15,15>>^ E, de noite, Abrão dividiu os seus homens em grupos, derrotou os inimigos e os perseguiu até Hobá, que fica ao norte de Damasco.

[[v1-14-16]]

^<<v1-14-16,16>>^ Trouxe de novo todos os bens, e também o seu sobrinho Ló, os bens dele, e ainda as mulheres, e o povo.

[[v1-14-17]]

^<<v1-14-17,17>>^ Quando Abrão regressava, depois de derrotar Quedorlaomer e os reis que estavam com ele, o rei de Sodoma foi ao encontro dele no vale de Savé, que é o vale do Rei.

[[v1-14-18]]

^<<v1-14-18,18>>^ E Melquisedeque, rei de Salém, trouxe pão e vinho. Ele era sacerdote do Deus Altíssimo.

[[v1-14-19]]

^<<v1-14-19,19>>^ Ele abençoou Abrão e disse: "Abrão seja abençoado pelo Deus Altíssimo, que criou os céus e a terra.

[[v1-14-20]]

^<<v1-14-20,20>>^ E bendito seja o Deus Altíssimo, que entregou os adversários de você nas suas mãos." E Abrão deu a Melquisedeque o dízimo de tudo.

[[v1-14-21]]

^<<v1-14-21,21>>^ Então o rei de Sodoma disse a Abrão: — Dê-me as pessoas e fique com os bens para você.

[[v1-14-22]]

^<<v1-14-22,22>>^ Mas Abrão lhe respondeu: — Juro pelo Senhor , o Deus Altíssimo, que criou os céus e a terra,

[[v1-14-23]]

^<<v1-14-23,23>>^ que nada tomarei de tudo o que é seu, nem um fio, nem uma correia de sandália, para que você não diga: "Fui eu que enriqueci Abrão."

[[v1-14-24]]

^<<v1-14-24,24>>^ Nada quero para mim, a não ser o que os rapazes comeram e a parte que toca a Aner, Escol e Manre, os homens que foram comigo; que estes fiquem com a parte deles.

'''

xref:001-genesis/001-genesis-013.adoc#v1-13-0[&#60; Capítulo Anterior] | <<v1-14-0,Topo>> | xref:001-genesis/001-genesis-015.adoc#v1-15-0[Próximo Capítulo &#62;]