include::./index.adoc[]

[[v51-1-0]]
=== Colossenses, 1
// naa ?, NAA - Nova Almeida Atualizada

[[v51-1-1]]

^<<v51-1-1,1>>^ Paulo, apóstolo de Cristo Jesus, pela vontade de Deus, e o irmão Timóteo,

[[v51-1-2]]

^<<v51-1-2,2>>^ aos santos e fiéis irmãos em Cristo que estão em Colossos. Que a graça e a paz de Deus, nosso Pai, estejam com vocês.

[[v51-1-3]]

^<<v51-1-3,3>>^ Damos sempre graças a Deus, Pai de nosso Senhor Jesus Cristo, quando oramos por vocês,

[[v51-1-4]]

^<<v51-1-4,4>>^ desde que ouvimos da fé que vocês têm em Cristo Jesus e do amor que vocês têm por todos os santos,

[[v51-1-5]]

^<<v51-1-5,5>>^ por causa da esperança que está guardada para vocês nos céus. Desta esperança vocês ouviram falar anteriormente por meio da palavra da verdade do evangelho,

[[v51-1-6]]

^<<v51-1-6,6>>^ que chegou até vocês. Esse evangelho está produzindo fruto e crescendo em todo o mundo, assim como acontece entre vocês, desde o dia em que ouviram e entenderam a graça de Deus na verdade.

[[v51-1-7]]

^<<v51-1-7,7>>^ Isso vocês aprenderam de Epafras, nosso amado conservo e, em relação a vocês, fiel ministro de Cristo,

[[v51-1-8]]

^<<v51-1-8,8>>^ o qual também nos contou do amor que vocês têm no Espírito.

[[v51-1-9]]

^<<v51-1-9,9>>^ Por esta razão, também nós, desde o dia em que soubemos disso, não deixamos de orar por vocês e de pedir que transbordem do pleno conhecimento da vontade de Deus, em toda a sabedoria e entendimento espiritual.

[[v51-1-10]]

^<<v51-1-10,10>>^ Dessa maneira, poderão viver de modo digno do Senhor, para o seu inteiro agrado, frutificando em toda boa obra e crescendo no conhecimento de Deus.

[[v51-1-11]]

^<<v51-1-11,11>>^ Assim, vocês serão fortalecidos com todo o poder, segundo a força da sua glória, em toda a perseverança e paciência, com alegria,

[[v51-1-12]]

^<<v51-1-12,12>>^ dando graças ao Pai, que os capacitou a participar da herança dos santos na luz.

[[v51-1-13]]

^<<v51-1-13,13>>^ Ele nos libertou do poder das trevas e nos transportou para o Reino do seu Filho amado,

[[v51-1-14]]

^<<v51-1-14,14>>^ em quem temos a redenção, a remissão dos pecados.

[[v51-1-15]]

^<<v51-1-15,15>>^ Ele é a imagem do Deus invisível, o primogênito de toda a criação.

[[v51-1-16]]

^<<v51-1-16,16>>^ Pois nele foram criadas todas as coisas, nos céus e sobre a terra, as visíveis e as invisíveis, sejam tronos, sejam soberanias, quer principados, quer potestades. Tudo foi criado por meio dele e para ele.

[[v51-1-17]]

^<<v51-1-17,17>>^ Ele é antes de todas as coisas. Nele tudo subsiste.

[[v51-1-18]]

^<<v51-1-18,18>>^ Ele é a cabeça do corpo, que é a igreja. Ele é o princípio, o primogênito dentre os mortos, para ter a primazia em todas as coisas.

[[v51-1-19]]

^<<v51-1-19,19>>^ Porque Deus achou por bem que, nele, residisse toda a plenitude

[[v51-1-20]]

^<<v51-1-20,20>>^ e que, havendo feito a paz pelo sangue da sua cruz, por meio dele, reconciliasse consigo mesmo todas as coisas, quer sobre a terra, quer nos céus.

[[v51-1-21]]

^<<v51-1-21,21>>^ E vocês que, no passado, eram estranhos e inimigos no entendimento pelas obras más que praticavam,

[[v51-1-22]]

^<<v51-1-22,22>>^ agora, porém, ele os reconciliou no corpo da sua carne, mediante a sua morte, para apresentá-los diante dele santos, inculpáveis e irrepreensíveis,

[[v51-1-23]]

^<<v51-1-23,23>>^ se é que vocês permanecem na fé, alicerçados e firmes, não se deixando afastar da esperança do evangelho que vocês ouviram e que foi pregado a toda criatura debaixo do céu, e do qual eu, Paulo, me tornei ministro.

[[v51-1-24]]

^<<v51-1-24,24>>^ Agora me alegro nos meus sofrimentos por vocês e preencho o que resta das aflições de Cristo, na minha carne, a favor do seu corpo, que é a igreja,

[[v51-1-25]]

^<<v51-1-25,25>>^ da qual me tornei ministro de acordo com a dispensação da parte de Deus, que me foi confiada em favor de vocês, para dar pleno cumprimento à palavra de Deus:

[[v51-1-26]]

^<<v51-1-26,26>>^ o mistério que esteve escondido durante séculos e gerações, mas que agora foi manifestado aos seus santos.

[[v51-1-27]]

^<<v51-1-27,27>>^ A estes Deus quis dar a conhecer a riqueza da glória deste mistério entre os gentios, que é Cristo em vocês, a esperança da glória.

[[v51-1-28]]

^<<v51-1-28,28>>^ Este Cristo nós anunciamos, advertindo a todos e ensinando a cada um em toda a sabedoria, a fim de que apresentemos cada pessoa perfeita em Cristo.

[[v51-1-29]]

^<<v51-1-29,29>>^ É para esse fim que eu me empenho, esforçando-me o mais possível, segundo o poder de Cristo que opera poderosamente em mim.

'''

xref:050-filipenses/050-filipenses-004.adoc#v50-4-0[&#60; Capítulo Anterior] | <<v51-1-0,Topo>> | xref:051-colossenses/051-colossenses-002.adoc#v51-2-0[Próximo Capítulo &#62;]