include::./index.adoc[]

[[v51-4-0]]
=== Colossenses, 4
// naa ?, NAA - Nova Almeida Atualizada

[[v51-4-1]]

^<<v51-4-1,1>>^ Senhores, tratem os seus servos com justiça e igualdade, sabendo que também vocês têm um Senhor no céu.

[[v51-4-2]]

^<<v51-4-2,2>>^ Continuem a orar, vigiando em oração com ação de graças.

[[v51-4-3]]

^<<v51-4-3,3>>^ Ao mesmo tempo, orem também por nós, para que Deus nos abra uma porta à palavra, a fim de falarmos do mistério de Cristo, pelo qual também estou algemado.

[[v51-4-4]]

^<<v51-4-4,4>>^ Orem para que eu torne esse mistério conhecido, como me cumpre fazer.

[[v51-4-5]]

^<<v51-4-5,5>>^ Sejam sábios no modo de agir com os que são de fora e aproveitem bem o tempo.

[[v51-4-6]]

^<<v51-4-6,6>>^ Que a palavra dita por vocês seja sempre agradável, temperada com sal, para que saibam como devem responder a cada um.

[[v51-4-7]]

^<<v51-4-7,7>>^ Quanto à minha situação, Tíquico, irmão amado, fiel ministro e conservo no Senhor, lhes dará todas as informações.

[[v51-4-8]]

^<<v51-4-8,8>>^ Eu o estou enviando com o expresso propósito de lhes dar conhecimento da nossa situação e de alentar o coração de vocês.

[[v51-4-9]]

^<<v51-4-9,9>>^ Com ele estou enviando Onésimo, o fiel e amado irmão, que é da igreja de vocês. Eles contarão a vocês tudo o que está acontecendo aqui.

[[v51-4-10]]

^<<v51-4-10,10>>^ Aristarco, que está preso comigo, manda saudações; e também Marcos, primo de Barnabé. A respeito dele vocês já receberam instruções; se ele for até aí, recebam-no bem.

[[v51-4-11]]

^<<v51-4-11,11>>^ Também Jesus, conhecido por Justo, manda saudações. Estes são os únicos da circuncisão que cooperam pessoalmente comigo pelo Reino de Deus. Eles têm sido o meu consolo.

[[v51-4-12]]

^<<v51-4-12,12>>^ Epafras, que é da igreja de vocês, manda saudações. Ele é um servo de Cristo Jesus que está sempre lutando por vocês em oração, para que vocês se conservem maduros e plenamente convictos em toda a vontade de Deus.

[[v51-4-13]]

^<<v51-4-13,13>>^ E posso testemunhar a respeito de Epafras de que muito se empenha por vocês, pelos de Laodiceia e pelos de Hierápolis.

[[v51-4-14]]

^<<v51-4-14,14>>^ Lucas, o médico amado, e também Demas mandam saudações.

[[v51-4-15]]

^<<v51-4-15,15>>^ Saúdem os irmãos de Laodiceia, bem como Ninfa e a igreja que se reúne na casa dela.

[[v51-4-16]]

^<<v51-4-16,16>>^ E, depois que esta carta tiver sido lida entre vocês, façam com que seja lida também na igreja dos laodicenses. E vocês, leiam também a carta que vier de Laodiceia.

[[v51-4-17]]

^<<v51-4-17,17>>^ E digam a Arquipo: "Atente para o ministério que você recebeu no Senhor, cumprindo bem a sua tarefa."

[[v51-4-18]]

^<<v51-4-18,18>>^ A saudação é de próprio punho: Paulo. Lembrem-se das minhas algemas. A graça esteja com vocês.

'''

xref:051-colossenses/051-colossenses-003.adoc#v51-3-0[&#60; Capítulo Anterior] | <<v51-4-0,Topo>> | xref:052-1-tessalonicenses/052-1-tessalonicenses-001.adoc#v52-1-0[Próximo Capítulo &#62;]