include::./index.adoc[]

[[v51-2-0]]
=== Colossenses, 2
// naa ?, NAA - Nova Almeida Atualizada

[[v51-2-1]]

^<<v51-2-1,1>>^ Quero que saibam quão grande tem sido a nossa luta por vocês, pelos que moram em Laodiceia e por muitos outros que não me viram face a face.

[[v51-2-2]]

^<<v51-2-2,2>>^ Faço isto para que o coração deles seja consolado e para que eles, vinculados em amor, tenham toda a riqueza da plena convicção do entendimento, para conhecimento do mistério de Deus, que é Cristo,

[[v51-2-3]]

^<<v51-2-3,3>>^ em quem estão ocultos todos os tesouros da sabedoria e do conhecimento.

[[v51-2-4]]

^<<v51-2-4,4>>^ Digo isso a vocês para que ninguém os engane com argumentos falaciosos.

[[v51-2-5]]

^<<v51-2-5,5>>^ Porque, embora ausente em pessoa, em espírito estou com vocês, alegrando-me e verificando a boa ordem de vocês e a firmeza da fé que têm em Cristo.

[[v51-2-6]]

^<<v51-2-6,6>>^ Portanto, assim como vocês receberam Cristo Jesus, o Senhor, continuem a viver nele,

[[v51-2-7]]

^<<v51-2-7,7>>^ estando enraizados e edificados nele, e confirmados na fé, como foi ensinado a vocês, crescendo em ação de graças.

[[v51-2-8]]

^<<v51-2-8,8>>^ Tenham cuidado para que ninguém venha a enredá-los com sua filosofia e vãs sutilezas, conforme a tradição dos homens, conforme os rudimentos do mundo e não segundo Cristo.

[[v51-2-9]]

^<<v51-2-9,9>>^ Porque nele habita corporalmente toda a plenitude da divindade.

[[v51-2-10]]

^<<v51-2-10,10>>^ Também, nele, vocês receberam a plenitude. Ele é o cabeça de todo principado e potestade.

[[v51-2-11]]

^<<v51-2-11,11>>^ Nele também vocês foram circuncidados, não com uma circuncisão feita por mãos humanas, mas pela remoção do corpo da carne, que é a circuncisão de Cristo,

[[v51-2-12]]

^<<v51-2-12,12>>^ tendo sido sepultados juntamente com ele no batismo, no qual vocês também foram ressuscitados por meio da fé no poder de Deus que o ressuscitou dentre os mortos.

[[v51-2-13]]

^<<v51-2-13,13>>^ E quando vocês estavam mortos nos seus pecados e na incircuncisão da carne, ele lhes deu vida juntamente com Cristo, perdoando todos os nossos pecados.

[[v51-2-14]]

^<<v51-2-14,14>>^ Cancelando o escrito de dívida que era contra nós e que constava de ordenanças, o qual nos era prejudicial, removeu-o inteiramente, cravando-o na cruz.

[[v51-2-15]]

^<<v51-2-15,15>>^ E, despojando os principados e as potestades, publicamente os expôs ao desprezo, triunfando sobre eles na cruz.

[[v51-2-16]]

^<<v51-2-16,16>>^ Portanto, que ninguém julgue vocês por causa de comida e bebida, ou dia de festa, ou lua nova, ou sábados,

[[v51-2-17]]

^<<v51-2-17,17>>^ porque tudo isso tem sido sombra das coisas que haviam de vir; porém o corpo é de Cristo.

[[v51-2-18]]

^<<v51-2-18,18>>^ Não deixem que ninguém se faça de árbitro para desqualificar vocês, com pretexto de humildade e culto de anjos, baseando-se em visões, estando cheio de orgulho, sem motivo algum, na sua mente carnal,

[[v51-2-19]]

^<<v51-2-19,19>>^ e não retendo a cabeça, a partir da qual todo o corpo, suprido e bem-vinculado por suas juntas e ligamentos, cresce o crescimento que vem de Deus.

[[v51-2-20]]

^<<v51-2-20,20>>^ Se vocês morreram com Cristo para os rudimentos do mundo, por que se sujeitam a regras, como se ainda vivessem no mundo?

[[v51-2-21]]

^<<v51-2-21,21>>^ "Não toque nisto", "não coma disso", "não pegue naquilo".

[[v51-2-22]]

^<<v51-2-22,22>>^ Todas estas coisas se destroem com o uso; são preceitos e doutrinas dos homens.

[[v51-2-23]]

^<<v51-2-23,23>>^ De fato, essas coisas têm aparência de sabedoria, ao promoverem um culto que as pessoas inventam, falsa humildade e tratamento austero do corpo. Mas elas não têm valor algum na luta contra as inclinações da carne.

'''

xref:051-colossenses/051-colossenses-001.adoc#v51-1-0[&#60; Capítulo Anterior] | <<v51-2-0,Topo>> | xref:051-colossenses/051-colossenses-003.adoc#v51-3-0[Próximo Capítulo &#62;]