include::./index.adoc[]

[[v51-3-0]]
=== Colossenses, 3
// naa ?, NAA - Nova Almeida Atualizada

[[v51-3-1]]

^<<v51-3-1,1>>^ Portanto, se vocês foram ressuscitados juntamente com Cristo, busquem as coisas lá do alto, onde Cristo vive, assentado à direita de Deus.

[[v51-3-2]]

^<<v51-3-2,2>>^ Pensem nas coisas lá do alto, e não nas que são aqui da terra.

[[v51-3-3]]

^<<v51-3-3,3>>^ Porque vocês morreram, e a vida de vocês está oculta juntamente com Cristo, em Deus.

[[v51-3-4]]

^<<v51-3-4,4>>^ Quando Cristo, que é a vida de vocês, se manifestar, então vocês também serão manifestados com ele, em glória.

[[v51-3-5]]

^<<v51-3-5,5>>^ Portanto, façam morrer tudo o que pertence à natureza terrena: imoralidade sexual, impureza, paixões, maus desejos e a avareza, que é idolatria;

[[v51-3-6]]

^<<v51-3-6,6>>^ por causa destas coisas é que vem a ira de Deus sobre os filhos da desobediência.

[[v51-3-7]]

^<<v51-3-7,7>>^ Vocês também andaram nessas mesmas coisas, no passado, quando viviam nelas.

[[v51-3-8]]

^<<v51-3-8,8>>^ Agora, porém, abandonem igualmente todas estas coisas: ira, indignação, maldade, blasfêmia, linguagem obscena no falar.

[[v51-3-9]]

^<<v51-3-9,9>>^ Não mintam uns aos outros, uma vez que vocês se despiram da velha natureza com as suas práticas

[[v51-3-10]]

^<<v51-3-10,10>>^ e se revestiram da nova natureza que se renova para o pleno conhecimento, segundo a imagem daquele que a criou.

[[v51-3-11]]

^<<v51-3-11,11>>^ Aqui não pode haver mais grego e judeu, circuncisão e incircuncisão, bárbaro, cita, escravo, livre, mas Cristo é tudo e está em todos.

[[v51-3-12]]

^<<v51-3-12,12>>^ Portanto, como eleitos de Deus, santos e amados, revistam-se de profunda compaixão, de bondade, de humildade, de mansidão, de paciência.

[[v51-3-13]]

^<<v51-3-13,13>>^ Suportem-se uns aos outros e perdoem-se mutuamente, caso alguém tenha motivo de queixa contra outra pessoa. Assim como o Senhor perdoou vocês, perdoem também uns aos outros.

[[v51-3-14]]

^<<v51-3-14,14>>^ Acima de tudo isto, porém, esteja o amor, que é o vínculo da perfeição.

[[v51-3-15]]

^<<v51-3-15,15>>^ Que a paz de Cristo seja o árbitro no coração de vocês, pois foi para essa paz que vocês foram chamados em um só corpo. E sejam agradecidos.

[[v51-3-16]]

^<<v51-3-16,16>>^ Que a palavra de Cristo habite ricamente em vocês. Instruam e aconselhem-se mutuamente em toda a sabedoria, louvando a Deus com salmos, hinos e cânticos espirituais, com gratidão no coração.

[[v51-3-17]]

^<<v51-3-17,17>>^ E tudo o que fizerem, seja em palavra, seja em ação, façam em nome do Senhor Jesus, dando por ele graças a Deus Pai.

[[v51-3-18]]

^<<v51-3-18,18>>^ Esposas, que cada uma de vocês se sujeite a seu próprio marido, como convém no Senhor.

[[v51-3-19]]

^<<v51-3-19,19>>^ Maridos, que cada um de vocês ame a sua esposa e não a trate com amargura.

[[v51-3-20]]

^<<v51-3-20,20>>^ Filhos, em tudo obedeçam a seus pais, pois fazer isso é agradável diante do Senhor.

[[v51-3-21]]

^<<v51-3-21,21>>^ Pais, não irritem os seus filhos, para que eles não fiquem desanimados.

[[v51-3-22]]

^<<v51-3-22,22>>^ Servos, obedeçam em tudo a seus senhores aqui na terra, não servindo apenas quando estão sendo vigiados, visando somente agradar pessoas, mas com sinceridade de coração, temendo o Senhor.

[[v51-3-23]]

^<<v51-3-23,23>>^ Tudo o que fizerem, façam de todo o coração, como para o Senhor e não para as pessoas,

[[v51-3-24]]

^<<v51-3-24,24>>^ sabendo que receberão do Senhor a recompensa da herança. É a Cristo, o Senhor, que vocês estão servindo.

[[v51-3-25]]

^<<v51-3-25,25>>^ E quem fizer injustiça receberá em troca a injustiça feita. E nisto ninguém será tratado com parcialidade.

'''

xref:051-colossenses/051-colossenses-002.adoc#v51-2-0[&#60; Capítulo Anterior] | <<v51-3-0,Topo>> | xref:051-colossenses/051-colossenses-004.adoc#v51-4-0[Próximo Capítulo &#62;]