include::./index.adoc[]

[[v35-2-0]]
=== Habacuque, 2
// naa ?, NAA - Nova Almeida Atualizada

[[v35-2-1]]

^<<v35-2-1,1>>^ Estarei na minha torre de vigia, ficarei na fortaleza e vigiarei para ver o que Deus me dirá e que resposta eu terei à minha queixa.

[[v35-2-2]]

^<<v35-2-2,2>>^ O Senhor  me respondeu e disse: "Escreva a visão, torne-a bem legível sobre tábuas, para que possa ser lida até por quem passa correndo.

[[v35-2-3]]

^<<v35-2-3,3>>^ Porque a visão ainda está para se cumprir no tempo determinado; ela se apressa para o fim e não falhará. Mesmo que pareça demorar, espere, porque certamente virá; não tardará."

[[v35-2-4]]

^<<v35-2-4,4>>^ "Eis que a sua alma está orgulhosa! A sua alma não é reta nele; mas o justo viverá pela sua fé.

[[v35-2-5]]

^<<v35-2-5,5>>^ Assim como o vinho é enganoso, também o arrogante não se contém. O seu apetite é como a sepultura; ele é como a morte, que nunca se farta. Ele ajunta para si todas as nações e congrega todos os povos."

[[v35-2-6]]

^<<v35-2-6,6>>^ Não é fato que todos esses povos proferirão contra ele um provérbio, um dito em tom de zombaria? Eles dirão: Ai daquele que acumula o que não é seu — até quando? —, e daquele que se enche de coisas penhoradas!

[[v35-2-7]]

^<<v35-2-7,7>>^ Será que não se levantarão de repente contra você os seus credores? E não despertarão aqueles que farão você tremer? Você lhes servirá de despojo.

[[v35-2-8]]

^<<v35-2-8,8>>^ Visto que você despojou muitas nações, todos os povos que restaram virão despojá-lo. Porque você derramou muito sangue e cometeu violência contra a terra, contra as cidades e contra todos os seus moradores.

[[v35-2-9]]

^<<v35-2-9,9>>^ Ai daquele que ajunta em sua casa bens mal-adquiridos, para pôr o seu ninho num lugar bem alto, a fim de livrar-se das garras do mal!

[[v35-2-10]]

^<<v35-2-10,10>>^ Os seus planos resultarão em vergonha para a sua casa. Ao destruir muitos povos, você pecou contra a sua própria vida.

[[v35-2-11]]

^<<v35-2-11,11>>^ Porque as pedras das paredes clamarão contra você, e as vigas do madeiramento farão eco.

[[v35-2-12]]

^<<v35-2-12,12>>^ Ai daquele que edifica uma cidade com sangue e a fundamenta na iniquidade!

[[v35-2-13]]

^<<v35-2-13,13>>^ Será que não é a vontade do Senhor  dos Exércitos que os povos trabalhem para o fogo e que as nações se fatiguem em vão?

[[v35-2-14]]

^<<v35-2-14,14>>^ Porque a terra se encherá do conhecimento da glória do Senhor , como as águas cobrem o mar.

[[v35-2-15]]

^<<v35-2-15,15>>^ Ai daquele que dá ao seu companheiro vinho misturado com o seu furor, e que o embebeda para lhe contemplar a nudez!

[[v35-2-16]]

^<<v35-2-16,16>>^ Você ficará coberto de vergonha em vez de honra. Beba você também e mostre a sua incircuncisão! Chegará a sua vez de pegar o cálice da mão direita do Senhor , e a sua glória se transformará em vergonha.

[[v35-2-17]]

^<<v35-2-17,17>>^ Porque a violência contra o Líbano cairá sobre você, e você ficará apavorado por ter destruído os animais. Porque você derramou muito sangue e cometeu violência contra a terra, contra as cidades e contra todos os seus moradores.

[[v35-2-18]]

^<<v35-2-18,18>>^ Para que serve o ídolo, visto que o seu artífice o esculpiu? E de que serve a imagem de fundição, mestra de mentiras, para que o artífice confie na sua obra, fazendo ídolos mudos?

[[v35-2-19]]

^<<v35-2-19,19>>^ Ai daquele que diz à madeira: "Acorde!" E à pedra muda: "Levante-se!" Pode o ídolo ensinar? Eis que está coberto de ouro e de prata, mas, no seu interior, não há fôlego nenhum.

[[v35-2-20]]

^<<v35-2-20,20>>^ O Senhor , porém, está no seu santo templo; cale-se diante dele toda a terra.

'''

xref:035-habacuque/035-habacuque-001.adoc#v35-1-0[&#60; Capítulo Anterior] | <<v35-2-0,Topo>> | xref:035-habacuque/035-habacuque-003.adoc#v35-3-0[Próximo Capítulo &#62;]