include::./index.adoc[]

[[v35-3-0]]
=== Habacuque, 3
// naa ?, NAA - Nova Almeida Atualizada

[[v35-3-1]]

^<<v35-3-1,1>>^ Oração do profeta Habacuque sob a forma de canto.

[[v35-3-2]]

^<<v35-3-2,2>>^ Senhor , tenho ouvido a tua fama, e me sinto alarmado. Aviva a tua obra, ó Senhor , no decorrer dos anos, e, no decurso dos anos, faze-a conhecida. Na tua ira, lembra-te da misericórdia.

[[v35-3-3]]

^<<v35-3-3,3>>^ Deus vem de Temã, o Santo vem do monte Parã. A sua glória cobre os céus, e a terra se enche do seu louvor.

[[v35-3-4]]

^<<v35-3-4,4>>^ O seu resplendor é como a luz, e raios brilham da sua mão; o seu poder se esconde ali.

[[v35-3-5]]

^<<v35-3-5,5>>^ Adiante dele vai a peste, e a pestilência segue os seus passos.

[[v35-3-6]]

^<<v35-3-6,6>>^ Ele para e faz a terra tremer; olha e sacode as nações. Esmigalham-se os montes primitivos; as colinas antigas se abatem. Os caminhos de Deus são eternos.

[[v35-3-7]]

^<<v35-3-7,7>>^ Vejo as tendas de Cusã em aflição; os acampamentos da terra de Midiã tremem.

[[v35-3-8]]

^<<v35-3-8,8>>^ Acaso é contra os rios, Senhor , que estás irado? É contra os ribeiros a tua ira ou contra o mar, o teu furor, já que andas montado nos teus cavalos, nos teus carros de vitória?

[[v35-3-9]]

^<<v35-3-9,9>>^ Preparas o teu arco; a tua aljava está cheia de flechas. Tu fendes a terra com rios.

[[v35-3-10]]

^<<v35-3-10,10>>^ Os montes te veem e se contorcem; torrentes de água passam. As profundezas do mar fazem ouvir a sua voz e levantam bem alto as suas mãos.

[[v35-3-11]]

^<<v35-3-11,11>>^ O sol e a lua param nas suas moradas, ao resplandecer a luz das tuas flechas sibilantes, ao fulgor do relâmpago da tua lança.

[[v35-3-12]]

^<<v35-3-12,12>>^ Na tua indignação, marchas pela terra; na tua ira, pisas as nações.

[[v35-3-13]]

^<<v35-3-13,13>>^ Tu sais para salvar o teu povo, para salvar o teu ungido. Feres o chefe da casa dos ímpios, deixando-o descoberto dos pés à cabeça.

[[v35-3-14]]

^<<v35-3-14,14>>^ Traspassas a cabeça dos guerreiros do inimigo com as suas próprias lanças, os quais, como tempestade, avançam para me destruir; alegram-se, como se estivessem para devorar o pobre em segredo.

[[v35-3-15]]

^<<v35-3-15,15>>^ Marchas com os teus cavalos pelo mar, pela massa de grandes águas.

[[v35-3-16]]

^<<v35-3-16,16>>^ Ouvi isso, e o meu íntimo se comoveu; os meus lábios tremeram ao ouvir a sua voz. A podridão entrou nos meus ossos, e os meus joelhos vacilaram, pois, em silêncio, devo esperar o dia da angústia, que virá contra o povo que nos ataca.

[[v35-3-17]]

^<<v35-3-17,17>>^ Ainda que a figueira não floresça, nem haja fruto na videira; ainda que a colheita da oliveira decepcione, e os campos não produzam mantimento; ainda que as ovelhas desapareçam do aprisco, e nos currais não haja mais gado,

[[v35-3-18]]

^<<v35-3-18,18>>^ mesmo assim eu me alegro no Senhor , e exulto no Deus da minha salvação.

[[v35-3-19]]

^<<v35-3-19,19>>^ O Senhor  Deus é a minha fortaleza. Ele dá aos meus pés a ligeireza das corças, e me faz andar nas minhas alturas. Ao mestre de canto. Para instrumentos de cordas.

'''

xref:035-habacuque/035-habacuque-002.adoc#v35-2-0[&#60; Capítulo Anterior] | <<v35-3-0,Topo>> | xref:036-sofonias/036-sofonias-001.adoc#v36-1-0[Próximo Capítulo &#62;]