include::./index.adoc[]

[[v35-1-0]]
=== Habacuque, 1
// naa ?, NAA - Nova Almeida Atualizada

[[v35-1-1]]

^<<v35-1-1,1>>^ Sentença revelada ao profeta Habacuque.

[[v35-1-2]]

^<<v35-1-2,2>>^ Até quando, Senhor , clamarei pedindo ajuda, e tu não me ouvirás? Até quando gritarei: "Violência!", e tu não salvarás?

[[v35-1-3]]

^<<v35-1-3,3>>^ Por que me fazes ver a iniquidade? Por que toleras a opressão? Pois a destruição e a violência estão diante de mim; há litígios e surgem discórdias.

[[v35-1-4]]

^<<v35-1-4,4>>^ Por isso, a lei se afrouxa e a justiça nunca se manifesta. Porque os ímpios cercam os justos, e assim a justiça é torcida.

[[v35-1-5]]

^<<v35-1-5,5>>^ "Olhem entre as nações e vejam; fiquem maravilhados e admirados. Porque, no tempo de vocês, eu realizo obra tal que vocês não acreditarão se alguém lhes contar.

[[v35-1-6]]

^<<v35-1-6,6>>^ Pois eis que trago os caldeus, nação cruel e impetuosa, que marcham pela largura da terra, para apoderar-se de moradas que não são suas.

[[v35-1-7]]

^<<v35-1-7,7>>^ Eles são pavorosos e terríveis; fazem as suas próprias leis e impõem a sua dignidade.

[[v35-1-8]]

^<<v35-1-8,8>>^ Os seus cavalos são mais ligeiros do que os leopardos, mais ferozes do que os lobos ao anoitecer. Os seus cavaleiros se espalham por toda parte; sim, os seus cavaleiros chegam de longe, voam como a águia que se precipita para devorar.

[[v35-1-9]]

^<<v35-1-9,9>>^ Eles todos vêm para fazer violência. Estão determinados a seguir em frente. Reúnem os cativos como se ajunta areia.

[[v35-1-10]]

^<<v35-1-10,10>>^ Zombam dos reis; os príncipes são motivo de riso para eles. Riem de todas as fortalezas, porque, amontoando terra, as conquistam.

[[v35-1-11]]

^<<v35-1-11,11>>^ Então passam como passa o vento e seguem adiante. Tornam-se culpados estes cujo deus é a própria força."

[[v35-1-12]]

^<<v35-1-12,12>>^ Não és tu desde a eternidade, ó Senhor , meu Deus, ó meu Santo? Não morreremos. Ó Senhor , puseste aquele povo para executar juízo; tu, ó Rocha, o estabeleceste para servir de disciplina.

[[v35-1-13]]

^<<v35-1-13,13>>^ Tu és tão puro de olhos, que não podes suportar o mal nem tolerar a opressão. Por que, então, toleras os traidores e te calas quando os perversos devoram aqueles que são mais justos do que eles?

[[v35-1-14]]

^<<v35-1-14,14>>^ Por que tratas as pessoas como se fossem peixes do mar, como se fossem animais que rastejam, que não têm quem os governe?

[[v35-1-15]]

^<<v35-1-15,15>>^ O inimigo pesca todos com o anzol, apanha-os na sua rede e os ajunta na sua rede de arrastão; então ele se alegra e fica contente.

[[v35-1-16]]

^<<v35-1-16,16>>^ Por isso, ele oferece sacrifício à sua rede e queima incenso à sua rede de arrastão, pois é por meio delas que aumentou as suas riquezas e tem abundância de comida.

[[v35-1-17]]

^<<v35-1-17,17>>^ Mas será que ele continuará a esvaziar a sua rede? Será que continuará a matar os povos sem dó nem piedade?

'''

xref:034-naum/034-naum-003.adoc#v34-3-0[&#60; Capítulo Anterior] | <<v35-1-0,Topo>> | xref:035-habacuque/035-habacuque-002.adoc#v35-2-0[Próximo Capítulo &#62;]