include::./index.adoc[]

[[v33-4-0]]
=== Miquéias, 4
// naa ?, NAA - Nova Almeida Atualizada

[[v33-4-1]]

^<<v33-4-1,1>>^ Nos últimos dias, o monte do templo do Senhor será estabelecido no alto dos montes e se elevará sobre as colinas, e para ele afluirão os povos.

[[v33-4-2]]

^<<v33-4-2,2>>^ Muitas nações virão e dirão: "Venham, subamos ao monte do Senhor e ao templo do Deus de Jacó, para que nos ensine os seus caminhos, e andemos nas suas veredas." Porque de Sião sairá a lei, e a palavra do Senhor , de Jerusalém.

[[v33-4-3]]

^<<v33-4-3,3>>^ Ele julgará entre muitos povos e corrigirá nações poderosas e distantes. Estas transformarão as suas espadas em lâminas de arados e as suas lanças, em foices. Nação não levantará a espada contra nação, nem aprenderão mais a guerra.

[[v33-4-4]]

^<<v33-4-4,4>>^ Mas cada um se assentará debaixo da sua videira e debaixo da sua figueira, e não haverá quem os atemorize, porque a boca do Senhor  dos Exércitos o disse.

[[v33-4-5]]

^<<v33-4-5,5>>^ Porque todos os povos andam, cada um em nome do seu deus; mas, quanto a nós, andaremos em nome do Senhor , nosso Deus, para todo o sempre.

[[v33-4-6]]

^<<v33-4-6,6>>^ "Naquele dia", diz o Senhor , "congregarei os que coxeiam e recolherei os que foram expulsos e os que eu tinha afligido.

[[v33-4-7]]

^<<v33-4-7,7>>^ Dos que coxeiam farei um remanescente e dos que foram lançados para longe, uma nação poderosa; e o Senhor  reinará sobre eles no monte Sião, desde agora e para sempre.

[[v33-4-8]]

^<<v33-4-8,8>>^ A você, ó torre do rebanho, monte da filha de Sião, a você virá, sim, virá o primeiro domínio, o reino da filha de Jerusalém."

[[v33-4-9]]

^<<v33-4-9,9>>^ Agora, por que você está gritando tão alto? Será porque você não tem rei? Morreram os seus conselheiros? Apoderou-se de você a dor como da mulher que está dando à luz?

[[v33-4-10]]

^<<v33-4-10,10>>^ Suporte as dores e faça força, filha de Sião, como a mulher que está dando à luz. Porque agora vocês terão de sair da cidade e morar nos campos; vocês irão para a Babilônia. Ali, porém, vocês serão libertados; ali, o Senhor  os remirá das mãos dos inimigos.

[[v33-4-11]]

^<<v33-4-11,11>>^ Agora muitas nações se reuniram contra você, dizendo: "Que Jerusalém seja profanada! Que os nossos olhos se deliciem com a ruína de Sião!"

[[v33-4-12]]

^<<v33-4-12,12>>^ Mas essas nações não conhecem os pensamentos do Senhor , nem entendem o seu plano: ele as ajuntou como feixes a serem batidos na eira.

[[v33-4-13]]

^<<v33-4-13,13>>^ Levante-se e comece a debulhar, ó filha de Sião, porque eu lhe darei chifres de ferro e cascos de bronze. Você esmagará muitos povos, e as riquezas que eles adquiriram serão dedicadas ao Senhor , e os bens que eles conquistaram pela força serão consagrados ao Senhor de toda a terra.

'''

xref:033-miqueias/033-miqueias-003.adoc#v33-3-0[&#60; Capítulo Anterior] | <<v33-4-0,Topo>> | xref:033-miqueias/033-miqueias-005.adoc#v33-5-0[Próximo Capítulo &#62;]