include::./index.adoc[]

[[v33-6-0]]
=== Miquéias, 6
// naa ?, NAA - Nova Almeida Atualizada

[[v33-6-1]]

^<<v33-6-1,1>>^ Escutem agora o que diz o Senhor : "Levante-se, defenda a sua causa diante dos montes, e que as colinas ouçam a sua voz.

[[v33-6-2]]

^<<v33-6-2,2>>^ Ó montes, escutem a controvérsia do Senhor , e vocês, duráveis fundamentos da terra, prestem atenção, porque o Senhor tem uma controvérsia com o seu povo e entrará em juízo com Israel."

[[v33-6-3]]

^<<v33-6-3,3>>^ "Meu povo, o que foi que eu lhe fiz? E como foi que eu o levei a ficar cansado? Responda!

[[v33-6-4]]

^<<v33-6-4,4>>^ Pois eu o tirei da terra do Egito e o resgatei da casa da servidão, e enviei adiante de você Moisés, Arão e Miriã.

[[v33-6-5]]

^<<v33-6-5,5>>^ Meu povo, lembre-se do que Balaque, rei de Moabe, havia planejado e do que Balaão, filho de Beor, lhe respondeu. Lembre-se também do que aconteceu desde Sitim até Gilgal, para que você conheça os atos de justiça do Senhor ."

[[v33-6-6]]

^<<v33-6-6,6>>^ Com que me apresentarei ao Senhor e me inclinarei diante do Deus excelso? Virei diante dele com holocaustos, com bezerros de um ano?

[[v33-6-7]]

^<<v33-6-7,7>>^ Será que o Senhor  se agrada com milhares de carneiros, com dez mil ribeiros de azeite? Darei o meu primogênito pela minha transgressão, o fruto do meu corpo, pelo pecado da minha alma?

[[v33-6-8]]

^<<v33-6-8,8>>^ Ele já mostrou a você o que é bom; e o que o Senhor  pede de você? Que pratique a justiça, ame a misericórdia e ande humildemente com o seu Deus.

[[v33-6-9]]

^<<v33-6-9,9>>^ A voz do Senhor se dirige à cidade, e é verdadeira sabedoria temer o seu nome. "Escutem, ó tribo e todos os moradores!

[[v33-6-10]]

^<<v33-6-10,10>>^ Ainda se encontram, na casa dos ímpios, os tesouros da impiedade e a medida falsa que eu detesto?

[[v33-6-11]]

^<<v33-6-11,11>>^ Poderei eu inocentar balanças desonestas e uma bolsa com pesos adulterados?

[[v33-6-12]]

^<<v33-6-12,12>>^ Porque os ricos da cidade estão cheios de violência; os seus habitantes falam mentiras e a língua deles é enganosa.

[[v33-6-13]]

^<<v33-6-13,13>>^ Assim, também eu passarei a feri-los e os destruirei por causa dos seus pecados.

[[v33-6-14]]

^<<v33-6-14,14>>^ Vocês comerão, mas não ficarão satisfeitos; a fome continuará nas suas entranhas. Tentarão pôr os seus bens a salvo, mas não conseguirão preservá-los; e aquilo que preservarem, eu entregarei à espada.

[[v33-6-15]]

^<<v33-6-15,15>>^ Vocês irão semear, mas não colherão nada; vocês esmagarão as azeitonas, mas não se ungirão com o azeite; pisarão as uvas, mas não beberão o vinho.

[[v33-6-16]]

^<<v33-6-16,16>>^ Vocês observaram os estatutos de Onri e todas as obras da casa de Acabe e andaram nos conselhos deles. Por isso, farei de Jerusalém um lugar desolado, e dos seus moradores um objeto de vaias. E vocês terão de suportar a zombaria dos povos."

'''

xref:033-miqueias/033-miqueias-005.adoc#v33-5-0[&#60; Capítulo Anterior] | <<v33-6-0,Topo>> | xref:033-miqueias/033-miqueias-007.adoc#v33-7-0[Próximo Capítulo &#62;]