include::./index.adoc[]

[[v33-2-0]]
=== Miquéias, 2
// naa ?, NAA - Nova Almeida Atualizada

[[v33-2-1]]

^<<v33-2-1,1>>^ "Ai daqueles que, ainda no seu leito, imaginam a iniquidade e planejam o mal! Ao amanhecer, eles o praticam, porque têm poder para tanto.

[[v33-2-2]]

^<<v33-2-2,2>>^ Cobiçam campos e se apossam deles; cobiçam casas e as tomam; assim, fazem violência a um homem e à sua casa, a uma pessoa e à sua herança."

[[v33-2-3]]

^<<v33-2-3,3>>^ Portanto, assim diz o Senhor : "Eis que estou forjando uma calamidade contra esta família, da qual vocês não livrarão o seu pescoço. Vocês não andarão mais de cabeça erguida, porque será um tempo de calamidade.

[[v33-2-4]]

^<<v33-2-4,4>>^ Naquele dia, se criará um provérbio a respeito de vocês e se entoará a seguinte lamentação: ‘Estamos completamente arruinados! A porção do meu povo, Deus a trocou! Como ele tirou o que era nosso! Entregou os nossos campos aos rebeldes!’

[[v33-2-5]]

^<<v33-2-5,5>>^ Portanto, na congregação do Senhor , quando a terra for dividida por sorteio, vocês não receberão nem uma parte dela."

[[v33-2-6]]

^<<v33-2-6,6>>^ "Eles dizem: ‘Não profetizem. Não profetizem tais coisas, porque a desgraça não cairá sobre nós.

[[v33-2-7]]

^<<v33-2-7,7>>^ Tais coisas anunciadas não alcançarão a casa de Jacó. Estaria o Espírito do Senhor  irritado? Será que ele agiria assim?’" "De fato, as minhas palavras fazem o bem ao que anda retamente.

[[v33-2-8]]

^<<v33-2-8,8>>^ Mas, há pouco, o meu povo se levantou como um inimigo. Além da roupa, vocês arrancam a capa daqueles que passam seguros, sem pensar em guerra.

[[v33-2-9]]

^<<v33-2-9,9>>^ Vocês expulsam do seu lar querido as mulheres de meu povo; dos filhinhos delas vocês tiram a minha glória, para sempre.

[[v33-2-10]]

^<<v33-2-10,10>>^ Levantem-se e vão embora! Porque este não é o lugar de descanso. Vão embora por causa da impureza que traz destruição, sim, destruição enorme.

[[v33-2-11]]

^<<v33-2-11,11>>^ Se alguém, seguindo o vento e a falsidade, inventar uma mentira do tipo: ‘Eu lhes profetizarei a respeito de vinho e de bebida forte’, esse tal será o profeta deste povo."

[[v33-2-12]]

^<<v33-2-12,12>>^ "Certamente eu ajuntarei todos vocês, casa de Jacó; certamente congregarei o remanescente de Israel. Eu os porei todos juntos, como ovelhas no aprisco, como rebanho no meio de sua pastagem; farão muito barulho, por causa da multidão de pessoas.

[[v33-2-13]]

^<<v33-2-13,13>>^ Diante deles virá o que abre caminho; eles abrirão caminho, entrarão pelo portão e sairão por ele; e o seu Rei irá adiante deles; sim, o Senhor  irá à frente deles."

'''

xref:033-miqueias/033-miqueias-001.adoc#v33-1-0[&#60; Capítulo Anterior] | <<v33-2-0,Topo>> | xref:033-miqueias/033-miqueias-003.adoc#v33-3-0[Próximo Capítulo &#62;]