include::./index.adoc[]

[[v33-5-0]]
=== Miquéias, 5
// naa ?, NAA - Nova Almeida Atualizada

[[v33-5-1]]

^<<v33-5-1,1>>^ Agora ajunte-se em tropas, ó filha de tropas, porque fomos sitiados, e ferirão com uma vara a face do juiz de Israel.

[[v33-5-2]]

^<<v33-5-2,2>>^ "E você, Belém-Efrata, que é pequena demais para figurar como grupo de milhares de Judá, de você me sairá aquele que há de reinar em Israel, e cujas origens são desde os tempos antigos, desde os dias da eternidade."

[[v33-5-3]]

^<<v33-5-3,3>>^ Portanto, o Senhor  os entregará até o tempo em que a que está em dores tiver dado à luz; então o restante de seus irmãos voltará aos filhos de Israel.

[[v33-5-4]]

^<<v33-5-4,4>>^ Ele se manterá firme e apascentará o povo na força do Senhor , na majestade do nome do Senhor , seu Deus; e eles habitarão seguros, porque, agora, ele será engrandecido até os confins da terra.

[[v33-5-5]]

^<<v33-5-5,5>>^ E ele será a nossa paz. Quando a Assíria vier à nossa terra e quando entrar em nossas fortalezas, levantaremos contra ela sete pastores e oito chefes do povo.

[[v33-5-6]]

^<<v33-5-6,6>>^ Estes dominarão a terra da Assíria com a espada, e a terra de Ninrode, dentro de suas próprias portas. Assim, nos livrará da Assíria, quando esta vier à nossa terra e invadir as nossas fronteiras.

[[v33-5-7]]

^<<v33-5-7,7>>^ O remanescente de Jacó estará no meio de muitos povos como orvalho do Senhor , como chuvisco sobre a relva, que não espera pelo homem, nem depende dos filhos de homens.

[[v33-5-8]]

^<<v33-5-8,8>>^ O remanescente de Jacó estará entre as nações, no meio de muitos povos, como um leão entre os animais da floresta, como um leãozinho entre os rebanhos de ovelhas, o qual, se passar, ataca e despedaça a presa, sem que ninguém a possa livrar.

[[v33-5-9]]

^<<v33-5-9,9>>^ A sua mão se exaltará sobre os seus adversários, e todos os seus inimigos serão eliminados.

[[v33-5-10]]

^<<v33-5-10,10>>^ "Naquele dia", diz o Senhor , "eliminarei do meio de vocês os cavalos e destruirei os carros de guerra;

[[v33-5-11]]

^<<v33-5-11,11>>^ destruirei as cidades da sua terra e derrubarei todas as fortalezas de vocês;

[[v33-5-12]]

^<<v33-5-12,12>>^ arrancarei as feitiçarias das suas mãos, e vocês não mais terão adivinhos;

[[v33-5-13]]

^<<v33-5-13,13>>^ do meio de vocês eliminarei as imagens de escultura e as colunas, e vocês não mais se inclinarão diante do que fizeram com as suas próprias mãos;

[[v33-5-14]]

^<<v33-5-14,14>>^ eliminarei do meio de vocês os postes da deusa Aserá e destruirei as cidades de vocês.

[[v33-5-15]]

^<<v33-5-15,15>>^ Com ira e furor, eu me vingarei das nações que não me obedeceram."

'''

xref:033-miqueias/033-miqueias-004.adoc#v33-4-0[&#60; Capítulo Anterior] | <<v33-5-0,Topo>> | xref:033-miqueias/033-miqueias-006.adoc#v33-6-0[Próximo Capítulo &#62;]