include::./index.adoc[]

[[v49-6-0]]
=== Efésios, 6
// naa ?, NAA - Nova Almeida Atualizada

[[v49-6-1]]

^<<v49-6-1,1>>^ Filhos, obedeçam a seus pais no Senhor, pois isto é justo.

[[v49-6-2]]

^<<v49-6-2,2>>^ "Honre o seu pai e a sua mãe", que é o primeiro mandamento com promessa,

[[v49-6-3]]

^<<v49-6-3,3>>^ "para que tudo corra bem com você, e você tenha uma longa vida sobre a terra".

[[v49-6-4]]

^<<v49-6-4,4>>^ E vocês, pais, não provoquem os seus filhos à ira, mas tratem de criá-los na disciplina e na admoestação do Senhor.

[[v49-6-5]]

^<<v49-6-5,5>>^ Quanto a vocês, servos, obedeçam a seus senhores aqui na terra com temor e tremor, com sinceridade de coração, como a Cristo,

[[v49-6-6]]

^<<v49-6-6,6>>^ não servindo apenas quando estão sendo vigiados, somente para agradar pessoas, mas como servos de Cristo, fazendo de coração a vontade de Deus.

[[v49-6-7]]

^<<v49-6-7,7>>^ Sirvam de boa vontade, como se estivessem trabalhando para o Senhor e não para pessoas,

[[v49-6-8]]

^<<v49-6-8,8>>^ sabendo que cada um, se fizer alguma coisa boa, receberá isso outra vez do Senhor, seja servo, seja livre.

[[v49-6-9]]

^<<v49-6-9,9>>^ E vocês, senhores, façam o mesmo com os servos, deixando as ameaças, sabendo que o Senhor, tanto deles como de vocês, está nos céus, e que ele não trata as pessoas com parcialidade.

[[v49-6-10]]

^<<v49-6-10,10>>^ Quanto ao mais, sejam fortalecidos no Senhor e na força do seu poder.

[[v49-6-11]]

^<<v49-6-11,11>>^ Vistam-se com toda a armadura de Deus, para poderem ficar firmes contra as ciladas do diabo.

[[v49-6-12]]

^<<v49-6-12,12>>^ Porque a nossa luta não é contra o sangue e a carne, mas contra os principados e as potestades, contra os dominadores deste mundo tenebroso, contra as forças espirituais do mal, nas regiões celestiais.

[[v49-6-13]]

^<<v49-6-13,13>>^ Por isso, peguem toda a armadura de Deus, para que vocês possam resistir no dia mau e, depois de terem vencido tudo, permanecer inabaláveis.

[[v49-6-14]]

^<<v49-6-14,14>>^ Portanto, fiquem firmes, cingindo-se com a verdade e vestindo a couraça da justiça.

[[v49-6-15]]

^<<v49-6-15,15>>^ Tenham os pés calçados com a preparação do evangelho da paz,

[[v49-6-16]]

^<<v49-6-16,16>>^ segurando sempre o escudo da fé, com o qual poderão apagar todos os dardos inflamados do Maligno.

[[v49-6-17]]

^<<v49-6-17,17>>^ Usem também o capacete da salvação e a espada do Espírito, que é a palavra de Deus.

[[v49-6-18]]

^<<v49-6-18,18>>^ Orem em todo tempo no Espírito, com todo tipo de oração e súplica, e para isto vigiem com toda perseverança e súplica por todos os santos.

[[v49-6-19]]

^<<v49-6-19,19>>^ E orem também por mim, para que, no abrir da minha boca, me seja dada a palavra, para com ousadia tornar conhecido o mistério do evangelho,

[[v49-6-20]]

^<<v49-6-20,20>>^ pelo qual sou embaixador em cadeias, para que, em Cristo, eu seja ousado para falar, como me cumpre fazer.

[[v49-6-21]]

^<<v49-6-21,21>>^ E, para que saibam como estou e o que estou fazendo, Tíquico, o irmão amado e fiel ministro do Senhor, lhes dará todas as informações.

[[v49-6-22]]

^<<v49-6-22,22>>^ Eu o estou enviando a vocês com esta finalidade: para que conheçam a nossa situação e para que ele console o coração de vocês.

[[v49-6-23]]

^<<v49-6-23,23>>^ Paz seja com os irmãos e amor com fé, da parte de Deus Pai e do Senhor Jesus Cristo.

[[v49-6-24]]

^<<v49-6-24,24>>^ A graça esteja com todos os que amam sinceramente o nosso Senhor Jesus Cristo.

'''

xref:049-efesios/049-efesios-005.adoc#v49-5-0[&#60; Capítulo Anterior] | <<v49-6-0,Topo>> | xref:050-filipenses/050-filipenses-001.adoc#v50-1-0[Próximo Capítulo &#62;]