include::./index.adoc[]

[[v49-1-0]]
=== Efésios, 1
// naa ?, NAA - Nova Almeida Atualizada

[[v49-1-1]]

^<<v49-1-1,1>>^ Paulo, apóstolo de Cristo Jesus pela vontade de Deus, aos santos que vivem em Éfeso e são fiéis em Cristo Jesus.

[[v49-1-2]]

^<<v49-1-2,2>>^ Que a graça e a paz de Deus, nosso Pai, e do Senhor Jesus Cristo estejam com vocês.

[[v49-1-3]]

^<<v49-1-3,3>>^ Bendito seja o Deus e Pai de nosso Senhor Jesus Cristo, que nos abençoou com todas as bênçãos espirituais nas regiões celestiais em Cristo.

[[v49-1-4]]

^<<v49-1-4,4>>^ Antes da fundação do mundo, Deus nos escolheu, nele, para sermos santos e irrepreensíveis diante dele. Em amor

[[v49-1-5]]

^<<v49-1-5,5>>^ nos predestinou para ele, para sermos adotados como seus filhos, por meio de Jesus Cristo, segundo o propósito de sua vontade,

[[v49-1-6]]

^<<v49-1-6,6>>^ para louvor da glória de sua graça, que ele nos concedeu gratuitamente no Amado.

[[v49-1-7]]

^<<v49-1-7,7>>^ Nele temos a redenção, pelo seu sangue, a remissão dos pecados, segundo a riqueza da sua graça,

[[v49-1-8]]

^<<v49-1-8,8>>^ que Deus derramou abundantemente sobre nós em toda a sabedoria e entendimento.

[[v49-1-9]]

^<<v49-1-9,9>>^ Ele nos revelou o mistério da sua vontade, segundo o seu propósito, que ele apresentou em Cristo,

[[v49-1-10]]

^<<v49-1-10,10>>^ de fazer convergir nele, na dispensação da plenitude dos tempos, todas as coisas, tanto as do céu como as da terra.

[[v49-1-11]]

^<<v49-1-11,11>>^ Em Cristo fomos também feitos herança, predestinados segundo o propósito daquele que faz todas as coisas conforme o conselho da sua vontade,

[[v49-1-12]]

^<<v49-1-12,12>>^ a fim de sermos para louvor da sua glória, nós, os que de antemão esperamos em Cristo.

[[v49-1-13]]

^<<v49-1-13,13>>^ Nele também vocês, depois que ouviram a palavra da verdade, o evangelho da salvação, tendo nele também crido, receberam o selo do Espírito Santo da promessa.

[[v49-1-14]]

^<<v49-1-14,14>>^ O Espírito é o penhor da nossa herança, até o resgate da sua propriedade, em louvor da sua glória.

[[v49-1-15]]

^<<v49-1-15,15>>^ Por isso, também eu, tendo ouvido a respeito da fé que vocês têm no Senhor Jesus e do amor para com todos os santos,

[[v49-1-16]]

^<<v49-1-16,16>>^ não cesso de dar graças por vocês, mencionando-os nas minhas orações.

[[v49-1-17]]

^<<v49-1-17,17>>^ Peço ao Deus de nosso Senhor Jesus Cristo, o Pai da glória, que conceda a vocês espírito de sabedoria e de revelação no pleno conhecimento dele.

[[v49-1-18]]

^<<v49-1-18,18>>^ Peço que ele ilumine os olhos do coração de vocês, para que saibam qual é a esperança da vocação de vocês, qual é a riqueza da glória da sua herança nos santos

[[v49-1-19]]

^<<v49-1-19,19>>^ e qual é a suprema grandeza do seu poder sobre nós, os que cremos, segundo a eficácia da força do seu poder.

[[v49-1-20]]

^<<v49-1-20,20>>^ Ele exerceu esse poder em Cristo, ressuscitando-o dentre os mortos e fazendo-o sentar à sua direita nas regiões celestiais,

[[v49-1-21]]

^<<v49-1-21,21>>^ acima de todo principado, potestade, poder, domínio e de todo nome que se possa mencionar, não só no presente século, mas também no vindouro.

[[v49-1-22]]

^<<v49-1-22,22>>^ E sujeitou todas as coisas debaixo dos pés de Cristo e, para ser o cabeça sobre todas as coisas, o deu à igreja,

[[v49-1-23]]

^<<v49-1-23,23>>^ a qual é o seu corpo, a plenitude daquele que a tudo enche em todas as coisas.

'''

xref:048-galatas/048-galatas-006.adoc#v48-6-0[&#60; Capítulo Anterior] | <<v49-1-0,Topo>> | xref:049-efesios/049-efesios-002.adoc#v49-2-0[Próximo Capítulo &#62;]