include::./index.adoc[]

[[v49-4-0]]
=== Efésios, 4
// naa ?, NAA - Nova Almeida Atualizada

[[v49-4-1]]

^<<v49-4-1,1>>^ Por isso eu, o prisioneiro no Senhor, peço que vocês vivam de maneira digna da vocação a que foram chamados,

[[v49-4-2]]

^<<v49-4-2,2>>^ com toda a humildade e mansidão, com longanimidade, suportando uns aos outros em amor,

[[v49-4-3]]

^<<v49-4-3,3>>^ fazendo tudo para preservar a unidade do Espírito no vínculo da paz.

[[v49-4-4]]

^<<v49-4-4,4>>^ Há somente um corpo e um só Espírito, como também é uma só a esperança para a qual vocês foram chamados.

[[v49-4-5]]

^<<v49-4-5,5>>^ Há um só Senhor, uma só fé, um só batismo,

[[v49-4-6]]

^<<v49-4-6,6>>^ um só Deus e Pai de todos, o qual é sobre todos, age por meio de todos e está em todos.

[[v49-4-7]]

^<<v49-4-7,7>>^ E a graça foi concedida a cada um de nós segundo a medida do dom de Cristo.

[[v49-4-8]]

^<<v49-4-8,8>>^ Por isso diz: "Quando ele subiu às alturas, levou cativo o cativeiro e concedeu dons aos homens."

[[v49-4-9]]

^<<v49-4-9,9>>^ Ora, o que quer dizer "ele subiu", senão que também havia descido até as regiões inferiores da terra?

[[v49-4-10]]

^<<v49-4-10,10>>^ Aquele que desceu é também o mesmo que subiu acima de todos os céus, para encher todas as coisas.

[[v49-4-11]]

^<<v49-4-11,11>>^ E ele mesmo concedeu uns para apóstolos, outros para profetas, outros para evangelistas e outros para pastores e mestres,

[[v49-4-12]]

^<<v49-4-12,12>>^ com vistas ao aperfeiçoamento dos santos para o desempenho do seu serviço, para a edificação do corpo de Cristo,

[[v49-4-13]]

^<<v49-4-13,13>>^ até que todos cheguemos à unidade da fé e do pleno conhecimento do Filho de Deus, ao estado de pessoa madura, à medida da estatura da plenitude de Cristo,

[[v49-4-14]]

^<<v49-4-14,14>>^ para que não mais sejamos como crianças, arrastados pelas ondas e levados de um lado para outro por qualquer vento de doutrina, pela artimanha das pessoas, pela astúcia com que induzem ao erro.

[[v49-4-15]]

^<<v49-4-15,15>>^ Mas, seguindo a verdade em amor, cresçamos em tudo naquele que é a cabeça, Cristo,

[[v49-4-16]]

^<<v49-4-16,16>>^ de quem todo o corpo, bem-ajustado e consolidado pelo auxílio de todas as juntas, segundo a justa cooperação de cada parte, efetua o seu próprio crescimento para a edificação de si mesmo em amor.

[[v49-4-17]]

^<<v49-4-17,17>>^ Isto, portanto, digo e no Senhor testifico: não vivam mais como os gentios, que vivem na vaidade dos seus próprios pensamentos,

[[v49-4-18]]

^<<v49-4-18,18>>^ tendo o seu entendimento obscurecido, separados da vida que Deus concede, por causa da ignorância em que vivem, pela dureza do seu coração.

[[v49-4-19]]

^<<v49-4-19,19>>^ Tendo-se tornado insensíveis, eles se entregaram à libertinagem para, de forma desenfreada, cometer todo tipo de impureza.

[[v49-4-20]]

^<<v49-4-20,20>>^ Mas não foi assim que vocês aprenderam de Cristo,

[[v49-4-21]]

^<<v49-4-21,21>>^ se é que, de fato, ouviram falar dele e nele foram instruídos, segundo é a verdade em Jesus.

[[v49-4-22]]

^<<v49-4-22,22>>^ Quanto à maneira antiga de viver, vocês foram instruídos a deixar de lado a velha natureza, que se corrompe segundo desejos enganosos,

[[v49-4-23]]

^<<v49-4-23,23>>^ a se deixar renovar no espírito do entendimento de vocês,

[[v49-4-24]]

^<<v49-4-24,24>>^ e a se revestir da nova natureza, criada segundo Deus, em justiça e retidão procedentes da verdade.

[[v49-4-25]]

^<<v49-4-25,25>>^ Por isso, deixando a mentira, que cada um fale a verdade com o seu próximo, porque somos membros do mesmo corpo.

[[v49-4-26]]

^<<v49-4-26,26>>^ Fiquem irados e não pequem. Não deixem que o sol se ponha sobre a ira de vocês,

[[v49-4-27]]

^<<v49-4-27,27>>^ nem deem lugar ao diabo.

[[v49-4-28]]

^<<v49-4-28,28>>^ Aquele que roubava não roube mais; pelo contrário, trabalhe, fazendo com as próprias mãos o que é bom, para que tenha o que repartir com o necessitado.

[[v49-4-29]]

^<<v49-4-29,29>>^ Não saia da boca de vocês nenhuma palavra suja, mas unicamente a que for boa para edificação, conforme a necessidade, e, assim, transmita graça aos que ouvem.

[[v49-4-30]]

^<<v49-4-30,30>>^ E não entristeçam o Espírito Santo de Deus, no qual vocês foram selados para o dia da redenção.

[[v49-4-31]]

^<<v49-4-31,31>>^ Que não haja no meio de vocês qualquer amargura, indignação, ira, gritaria e blasfêmia, bem como qualquer maldade.

[[v49-4-32]]

^<<v49-4-32,32>>^ Pelo contrário, sejam bondosos e compassivos uns para com os outros, perdoando uns aos outros, como também Deus, em Cristo, perdoou vocês.

'''

xref:049-efesios/049-efesios-003.adoc#v49-3-0[&#60; Capítulo Anterior] | <<v49-4-0,Topo>> | xref:049-efesios/049-efesios-005.adoc#v49-5-0[Próximo Capítulo &#62;]