include::./index.adoc[]

[[v37-1-0]]
=== Ageu, 1
// naa ?, NAA - Nova Almeida Atualizada

[[v37-1-1]]

^<<v37-1-1,1>>^ No segundo ano do reinado de Dario, no sexto mês, no primeiro dia do mês, por meio do profeta Ageu, a palavra do Senhor  veio a Zorobabel, filho de Salatiel, governador de Judá, e a Josué, filho de Jozadaque, o sumo sacerdote, dizendo:

[[v37-1-2]]

^<<v37-1-2,2>>^ — Assim diz o Senhor  dos Exércitos: Este povo diz: "Ainda não chegou o tempo, o tempo em que a Casa do Senhor  deve ser reconstruída."

[[v37-1-3]]

^<<v37-1-3,3>>^ Por isso, a palavra do Senhor  veio por meio do profeta Ageu, dizendo:

[[v37-1-4]]

^<<v37-1-4,4>>^ — Acaso é tempo de vocês morarem em casas luxuosas, enquanto este templo permanece em ruínas?

[[v37-1-5]]

^<<v37-1-5,5>>^ Portanto, assim diz o Senhor  dos Exércitos: Considerem o que tem acontecido com vocês.

[[v37-1-6]]

^<<v37-1-6,6>>^ Vocês semearam muito e colheram pouco; comem, mas isso não chega para matar a fome; bebem, mas isso não dá para ficarem satisfeitos; põem roupa, mas ninguém se aquece; e o que recebe salário, recebe-o para colocá-lo numa sacola furada.

[[v37-1-7]]

^<<v37-1-7,7>>^ — Assim diz o Senhor  dos Exércitos: Considerem o que tem acontecido com vocês.

[[v37-1-8]]

^<<v37-1-8,8>>^ Vão até o monte, tragam madeira e reconstruam o templo. Dele me agradarei e serei glorificado, diz o Senhor .

[[v37-1-9]]

^<<v37-1-9,9>>^ Vocês esperavam que fosse muito, mas o que veio foi pouco, e esse pouco, quando o levaram para casa, eu o dissipei com um sopro. E por quê? — pergunta o Senhor  dos Exércitos. Porque o meu templo permanece em ruínas, enquanto cada um de vocês corre por causa de sua própria casa.

[[v37-1-10]]

^<<v37-1-10,10>>^ Por isso, os céus retêm o seu orvalho, e a terra não produz os seus frutos.

[[v37-1-11]]

^<<v37-1-11,11>>^ Fiz vir a seca sobre a terra e sobre os montes, sobre o cereal, sobre o vinho, sobre o azeite, sobre o que o solo produz, sobre as pessoas, sobre os animais e sobre todo trabalho das mãos.

[[v37-1-12]]

^<<v37-1-12,12>>^ Então Zorobabel, filho de Salatiel, e Josué, filho de Jozadaque, o sumo sacerdote, e todo o remanescente do povo atenderam à voz do Senhor , seu Deus, e às palavras do profeta Ageu, as quais o Senhor , seu Deus, havia ordenado que ele dissesse. E o povo temeu diante do Senhor .

[[v37-1-13]]

^<<v37-1-13,13>>^ Então Ageu, o enviado do Senhor , falou ao povo, segundo a mensagem do Senhor , dizendo: — Eu estou com vocês, diz o Senhor .

[[v37-1-14]]

^<<v37-1-14,14>>^ O Senhor  despertou o espírito de Zorobabel, filho de Salatiel, governador de Judá, e o espírito de Josué, filho de Jozadaque, o sumo sacerdote, e o espírito de todo o remanescente do povo; eles vieram e começaram a trabalhar no templo do Senhor  dos Exércitos, seu Deus.

[[v37-1-15]]

^<<v37-1-15,15>>^ Era o vigésimo quarto dia do sexto mês do segundo ano do reinado de Dario.

'''

xref:036-sofonias/036-sofonias-003.adoc#v36-3-0[&#60; Capítulo Anterior] | <<v37-1-0,Topo>> | xref:037-ageu/037-ageu-002.adoc#v37-2-0[Próximo Capítulo &#62;]