include::./index.adoc[]

[[v60-4-0]]
=== 1 Pedro, 4
// naa ?, NAA - Nova Almeida Atualizada

[[v60-4-1]]

^<<v60-4-1,1>>^ Ora, tendo Cristo sofrido na carne, estejam também vocês armados do mesmo pensamento. Pois aquele que sofreu na carne rompeu com o pecado,

[[v60-4-2]]

^<<v60-4-2,2>>^ para que, no tempo que lhes resta na carne, vocês não vivam mais de acordo com as paixões humanas, mas segundo a vontade de Deus.

[[v60-4-3]]

^<<v60-4-3,3>>^ Porque basta que, no passado, vocês tenham feito a vontade dos gentios, tendo andado em práticas libertinas, desejos carnais, bebedeiras, orgias, embriaguez e em detestáveis idolatrias.

[[v60-4-4]]

^<<v60-4-4,4>>^ Por isso, falando mal de vocês, estranham que vocês não se juntam com eles no mesmo excesso de devassidão,

[[v60-4-5]]

^<<v60-4-5,5>>^ eles que terão de prestar contas àquele que é competente para julgar vivos e mortos.

[[v60-4-6]]

^<<v60-4-6,6>>^ Pois, para este fim, o evangelho foi pregado também a mortos, para que, mesmo julgados na carne segundo os homens, vivam em espírito segundo Deus.

[[v60-4-7]]

^<<v60-4-7,7>>^ O fim de todas as coisas está próximo; portanto, sejam criteriosos e sóbrios para poderem orar.

[[v60-4-8]]

^<<v60-4-8,8>>^ Acima de tudo, porém, tenham muito amor uns para com os outros, porque o amor cobre a multidão de pecados.

[[v60-4-9]]

^<<v60-4-9,9>>^ Sejam mutuamente hospitaleiros, sem murmuração.

[[v60-4-10]]

^<<v60-4-10,10>>^ Sirvam uns aos outros, cada um conforme o dom que recebeu, como encarregados de administrar bem a multiforme graça de Deus.

[[v60-4-11]]

^<<v60-4-11,11>>^ Se alguém fala, fale de acordo com os oráculos de Deus; se alguém serve, faça-o na força que Deus lhe dá, para que, em todas as coisas, Deus seja glorificado, por meio de Jesus Cristo, a quem pertence a glória e o domínio para todo o sempre. Amém!

[[v60-4-12]]

^<<v60-4-12,12>>^ Amados, não estranhem o fogo que surge no meio de vocês, destinado a pô-los à prova, como se alguma coisa extraordinária estivesse acontecendo.

[[v60-4-13]]

^<<v60-4-13,13>>^ Pelo contrário, alegrem-se na medida em que são coparticipantes dos sofrimentos de Cristo, para que também, na revelação de sua glória, vocês se alegrem, exultando.

[[v60-4-14]]

^<<v60-4-14,14>>^ Se são insultados por causa do nome de Cristo, vocês são bem-aventurados, porque o Espírito da glória, que é o Espírito de Deus, repousa sobre vocês.

[[v60-4-15]]

^<<v60-4-15,15>>^ Que nenhum de vocês sofra como assassino, ou ladrão, ou malfeitor, ou como quem se mete na vida dos outros.

[[v60-4-16]]

^<<v60-4-16,16>>^ Mas, se sofrer como cristão, não se envergonhe; pelo contrário, glorifique a Deus por causa disso.

[[v60-4-17]]

^<<v60-4-17,17>>^ Porque chegou o tempo de começar o juízo pela casa de Deus; e, se começa por nós, qual será o fim daqueles que não obedecem ao evangelho de Deus?

[[v60-4-18]]

^<<v60-4-18,18>>^ E, "se é com dificuldade que o justo é salvo, que será do ímpio e do pecador?"

[[v60-4-19]]

^<<v60-4-19,19>>^ Por isso, também os que sofrem segundo a vontade de Deus entreguem a sua alma ao fiel Criador, na prática do bem.

'''

xref:060-1-pedro/060-1-pedro-003.adoc#v60-3-0[&#60; Capítulo Anterior] | <<v60-4-0,Topo>> | xref:060-1-pedro/060-1-pedro-005.adoc#v60-5-0[Próximo Capítulo &#62;]