include::./index.adoc[]

[[v60-5-0]]
=== 1 Pedro, 5
// naa ?, NAA - Nova Almeida Atualizada

[[v60-5-1]]

^<<v60-5-1,1>>^ Aos presbíteros que há entre vocês, eu, presbítero como eles, testemunha dos sofrimentos de Cristo e, ainda, coparticipante da glória que há de ser revelada, peço

[[v60-5-2]]

^<<v60-5-2,2>>^ que pastoreiem o rebanho de Deus que há entre vocês, não por obrigação, mas espontaneamente, como Deus quer; não por ganância, mas de boa vontade;

[[v60-5-3]]

^<<v60-5-3,3>>^ não como dominadores dos que lhes foram confiados, mas sendo exemplos para o rebanho.

[[v60-5-4]]

^<<v60-5-4,4>>^ E, quando o Supremo Pastor se manifestar, vocês receberão a coroa da glória, que nunca perde o seu brilho.

[[v60-5-5]]

^<<v60-5-5,5>>^ Peço igualmente aos jovens: estejam sujeitos aos que são mais velhos. Que todos se revistam de humildade no trato de uns com os outros, porque "Deus resiste aos soberbos, mas dá graça aos humildes."

[[v60-5-6]]

^<<v60-5-6,6>>^ Portanto, humilhem-se debaixo da poderosa mão de Deus, para que ele, em tempo oportuno, os exalte.

[[v60-5-7]]

^<<v60-5-7,7>>^ Lancem sobre ele todas as suas ansiedades, porque ele cuida de vocês.

[[v60-5-8]]

^<<v60-5-8,8>>^ Sejam sóbrios e vigilantes. O inimigo de vocês, o diabo, anda em derredor, como leão que ruge procurando alguém para devorar.

[[v60-5-9]]

^<<v60-5-9,9>>^ Resistam-lhe, firmes na fé, certos de que os irmãos de vocês, espalhados pelo mundo, estão passando por sofrimentos iguais aos de vocês.

[[v60-5-10]]

^<<v60-5-10,10>>^ E o Deus de toda a graça, que em Cristo os chamou à sua eterna glória, depois de vocês terem sofrido por um pouco, ele mesmo irá aperfeiçoar, firmar, fortificar e fundamentar vocês.

[[v60-5-11]]

^<<v60-5-11,11>>^ A ele seja o domínio para sempre. Amém!

[[v60-5-12]]

^<<v60-5-12,12>>^ Por meio de Silvano, que considero um irmão fiel, escrevo para vocês de forma resumida, exortando e testemunhando que esta é a genuína graça de Deus. Continuem firmes nessa graça.

[[v60-5-13]]

^<<v60-5-13,13>>^ Aquela que se encontra na Babilônia, também eleita, manda saudações, e o mesmo faz o meu filho Marcos.

[[v60-5-14]]

^<<v60-5-14,14>>^ Saúdem uns aos outros com um beijo fraterno. Paz a todos vocês que estão em Cristo.

'''

xref:060-1-pedro/060-1-pedro-004.adoc#v60-4-0[&#60; Capítulo Anterior] | <<v60-5-0,Topo>> | xref:061-2-pedro/061-2-pedro-001.adoc#v61-1-0[Próximo Capítulo &#62;]