include::./index.adoc[]

[[v60-1-0]]
=== 1 Pedro, 1
// naa ?, NAA - Nova Almeida Atualizada

[[v60-1-1]]

^<<v60-1-1,1>>^ Pedro, apóstolo de Jesus Cristo, aos eleitos que são forasteiros da Diáspora no Ponto, na Galácia, na Capadócia, na Ásia e na Bitínia,

[[v60-1-2]]

^<<v60-1-2,2>>^ eleitos, segundo a presciência de Deus Pai, em santificação do Espírito, para a obediência e a aspersão do sangue de Jesus Cristo. Que a graça e a paz lhes sejam multiplicadas.

[[v60-1-3]]

^<<v60-1-3,3>>^ Bendito seja o Deus e Pai de nosso Senhor Jesus Cristo, que, segundo a sua grande misericórdia, nos regenerou para uma viva esperança, mediante a ressurreição de Jesus Cristo dentre os mortos,

[[v60-1-4]]

^<<v60-1-4,4>>^ para uma herança que não pode ser destruída, que não fica manchada, que não murcha e que está reservada nos céus para vocês,

[[v60-1-5]]

^<<v60-1-5,5>>^ que são guardados pelo poder de Deus, mediante a fé, para a salvação preparada para ser revelada no último tempo.

[[v60-1-6]]

^<<v60-1-6,6>>^ Nisso vocês exultam, embora, no presente, por breve tempo, se necessário, sejam contristados por várias provações,

[[v60-1-7]]

^<<v60-1-7,7>>^ para que, uma vez confirmado o valor da fé que vocês têm, muito mais preciosa do que o ouro perecível, mesmo apurado pelo fogo, resulte em louvor, glória e honra na revelação de Jesus Cristo.

[[v60-1-8]]

^<<v60-1-8,8>>^ Mesmo sem tê-lo visto vocês o amam. Mesmo não o vendo agora, mas crendo nele, exultam com uma alegria indescritível e cheia de glória,

[[v60-1-9]]

^<<v60-1-9,9>>^ obtendo o alvo dessa fé: a salvação da alma.

[[v60-1-10]]

^<<v60-1-10,10>>^ Foi a respeito desta salvação que os profetas indagaram e investigaram. Eles profetizaram a respeito da graça destinada a vocês,

[[v60-1-11]]

^<<v60-1-11,11>>^ investigando qual a ocasião ou quais as circunstâncias oportunas que eram indicadas pelo Espírito de Cristo, que neles estava, ao predizer os sofrimentos que Cristo teria de suportar e as glórias que viriam depois desses sofrimentos.

[[v60-1-12]]

^<<v60-1-12,12>>^ A eles foi revelado que, não para si mesmos, mas para vocês, ministravam as coisas que, agora, foram anunciadas a vocês por aqueles que, pelo Espírito Santo enviado do céu, lhes pregaram o evangelho, coisas essas que anjos desejam contemplar.

[[v60-1-13]]

^<<v60-1-13,13>>^ Por isso, preparando o seu entendimento, sejam sóbrios e esperem inteiramente na graça que lhes está sendo trazida na revelação de Jesus Cristo.

[[v60-1-14]]

^<<v60-1-14,14>>^ Como filhos obedientes, não vivam conforme as paixões que vocês tinham anteriormente, quando ainda estavam na ignorância.

[[v60-1-15]]

^<<v60-1-15,15>>^ Pelo contrário, assim como é santo aquele que os chamou, sejam santos vocês também em tudo o que fizerem,

[[v60-1-16]]

^<<v60-1-16,16>>^ porque está escrito: "Sejam santos, porque eu sou santo."

[[v60-1-17]]

^<<v60-1-17,17>>^ E, se vocês invocam como Pai aquele que, sem parcialidade, julga segundo as obras de cada um, vivam em temor durante o tempo da peregrinação de vocês,

[[v60-1-18]]

^<<v60-1-18,18>>^ sabendo que não foi mediante coisas perecíveis, como prata ou ouro, que vocês foram resgatados da vida inútil que seus pais lhes legaram,

[[v60-1-19]]

^<<v60-1-19,19>>^ mas pelo precioso sangue de Cristo, como de um cordeiro sem defeito e sem mácula.

[[v60-1-20]]

^<<v60-1-20,20>>^ Ele foi conhecido antes da fundação do mundo, mas foi manifestado nestes últimos tempos, em favor de vocês.

[[v60-1-21]]

^<<v60-1-21,21>>^ Por meio dele, vocês creem em Deus, o qual o ressuscitou dentre os mortos e lhe deu glória, para que a fé e a esperança de vocês estejam em Deus.

[[v60-1-22]]

^<<v60-1-22,22>>^ Tendo purificado a alma pela obediência à verdade, e com vistas ao amor fraternal não fingido, amem intensamente uns aos outros de coração puro.

[[v60-1-23]]

^<<v60-1-23,23>>^ Porque vocês foram regenerados não de semente corruptível, mas de semente incorruptível, mediante a palavra de Deus, a qual vive e é permanente.

[[v60-1-24]]

^<<v60-1-24,24>>^ Porque "toda a humanidade é como a erva do campo, e toda a sua glória é como a flor da erva. A erva seca, e a flor cai;

[[v60-1-25]]

^<<v60-1-25,25>>^ mas a palavra do Senhor permanece para sempre." Esta palavra é o evangelho que foi anunciado a vocês.

'''

xref:059-tiago/059-tiago-005.adoc#v59-5-0[&#60; Capítulo Anterior] | <<v60-1-0,Topo>> | xref:060-1-pedro/060-1-pedro-002.adoc#v60-2-0[Próximo Capítulo &#62;]