include::./index.adoc[]

[[v60-2-0]]
=== 1 Pedro, 2
// naa ?, NAA - Nova Almeida Atualizada

[[v60-2-1]]

^<<v60-2-1,1>>^ Portanto, abandonem toda maldade, todo engano, hipocrisia e inveja, bem como todo tipo de maledicência.

[[v60-2-2]]

^<<v60-2-2,2>>^ Como crianças recém-nascidas, desejem o genuíno leite espiritual, para que, por ele, lhes seja dado crescimento para a salvação,

[[v60-2-3]]

^<<v60-2-3,3>>^ se é que vocês já têm a experiência de que o Senhor é bondoso.

[[v60-2-4]]

^<<v60-2-4,4>>^ Chegando-se a ele, a pedra que vive, rejeitada, sim, pelos homens, mas para com Deus eleita e preciosa,

[[v60-2-5]]

^<<v60-2-5,5>>^ também vocês, como pedras que vivem, são edificados casa espiritual para serem sacerdócio santo, a fim de oferecerem sacrifícios espirituais agradáveis a Deus por meio de Jesus Cristo.

[[v60-2-6]]

^<<v60-2-6,6>>^ Pois isso está na Escritura: "Eis que ponho em Sião uma pedra angular, eleita e preciosa; e quem nela crer não será envergonhado."

[[v60-2-7]]

^<<v60-2-7,7>>^ Portanto, para vocês, os que creem, esta pedra é preciosa. Mas, para os descrentes, "A pedra que os construtores rejeitaram, essa veio a ser a pedra angular."

[[v60-2-8]]

^<<v60-2-8,8>>^ E: "Pedra de tropeço e rocha de ofensa." São estes os que tropeçam na palavra, sendo desobedientes, para o que também foram destinados.

[[v60-2-9]]

^<<v60-2-9,9>>^ Vocês, porém, são geração eleita, sacerdócio real, nação santa, povo de propriedade exclusiva de Deus, a fim de proclamar as virtudes daquele que os chamou das trevas para a sua maravilhosa luz.

[[v60-2-10]]

^<<v60-2-10,10>>^ Antes, vocês nem eram povo, mas agora são povo de Deus; antes, não tinham alcançado misericórdia, mas agora alcançaram misericórdia.

[[v60-2-11]]

^<<v60-2-11,11>>^ Amados, peço a vocês, como peregrinos e forasteiros que são, que se abstenham das paixões carnais, que fazem guerra contra a alma,

[[v60-2-12]]

^<<v60-2-12,12>>^ tendo conduta exemplar no meio dos gentios, para que, quando eles os acusarem de malfeitores, observando as boas obras que vocês praticam, glorifiquem a Deus no dia da visitação.

[[v60-2-13]]

^<<v60-2-13,13>>^ Por causa do Senhor, estejam sujeitos a toda instituição humana, quer seja ao rei, como soberano,

[[v60-2-14]]

^<<v60-2-14,14>>^ quer seja às autoridades, como enviadas por ele, tanto para castigo dos malfeitores como para louvor dos que praticam o bem.

[[v60-2-15]]

^<<v60-2-15,15>>^ Porque assim é a vontade de Deus, que, pela prática do bem, vocês silenciem a ignorância dos insensatos.

[[v60-2-16]]

^<<v60-2-16,16>>^ Como pessoas livres que são, não usem a liberdade como desculpa para fazer o mal; pelo contrário, vivam como servos de Deus.

[[v60-2-17]]

^<<v60-2-17,17>>^ Tratem todos com honra, amem os irmãos na fé, temam a Deus e honrem o rei.

[[v60-2-18]]

^<<v60-2-18,18>>^ Servos, sejam obedientes ao senhor de vocês, com todo o temor. E não somente se ele for bom e cordial, mas também se for mau.

[[v60-2-19]]

^<<v60-2-19,19>>^ Porque isto é agradável a Deus, que alguém suporte tristezas, sofrendo injustamente, por motivo de sua consciência para com Deus.

[[v60-2-20]]

^<<v60-2-20,20>>^ Pois que glória há, se, pecando e sendo castigados por isso, vocês o suportam com paciência? Se, entretanto, quando praticam o bem, vocês são igualmente afligidos e o suportam com paciência, isto é agradável a Deus.

[[v60-2-21]]

^<<v60-2-21,21>>^ Porque para isto mesmo vocês foram chamados, pois também Cristo sofreu no lugar de vocês, deixando exemplo para que vocês sigam os seus passos.

[[v60-2-22]]

^<<v60-2-22,22>>^ Ele não cometeu pecado, nem foi encontrado engano em sua boca.

[[v60-2-23]]

^<<v60-2-23,23>>^ Pois ele, quando insultado, não revidava com insultos; quando maltratado, não fazia ameaças, mas se entregava àquele que julga retamente,

[[v60-2-24]]

^<<v60-2-24,24>>^ carregando ele mesmo, em seu corpo, sobre o madeiro, os nossos pecados, para que nós, mortos para os pecados, vivamos para a justiça. Pelas feridas dele vocês foram sarados.

[[v60-2-25]]

^<<v60-2-25,25>>^ Porque vocês estavam desgarrados como ovelhas; agora, porém, se converteram ao Pastor e Bispo da alma de vocês.

'''

xref:060-1-pedro/060-1-pedro-001.adoc#v60-1-0[&#60; Capítulo Anterior] | <<v60-2-0,Topo>> | xref:060-1-pedro/060-1-pedro-003.adoc#v60-3-0[Próximo Capítulo &#62;]