include::./index.adoc[]

[[v45-16-0]]
=== Romanos, 16
// naa ?, NAA - Nova Almeida Atualizada

[[v45-16-1]]

^<<v45-16-1,1>>^ Recomendo-lhes a nossa irmã Febe, que está servindo na igreja de Cencreia,

[[v45-16-2]]

^<<v45-16-2,2>>^ para que vocês a recebam no Senhor como convém aos santos e a ajudem em tudo o que de vocês vier a precisar; porque ela tem sido protetora de muitos, inclusive de mim.

[[v45-16-3]]

^<<v45-16-3,3>>^ Saúdem Priscila e Áquila, meus cooperadores em Cristo Jesus,

[[v45-16-4]]

^<<v45-16-4,4>>^ os quais pela minha vida arriscaram a sua própria cabeça; e isto lhes agradeço, não somente eu, mas também todas as igrejas dos gentios.

[[v45-16-5]]

^<<v45-16-5,5>>^ Saúdem igualmente a igreja que se reúne na casa deles. Saúdem meu querido Epêneto, primeiro fruto da fé em Cristo na província da Ásia.

[[v45-16-6]]

^<<v45-16-6,6>>^ Saúdem Maria, que muito trabalhou por vocês.

[[v45-16-7]]

^<<v45-16-7,7>>^ Saúdem Andrônico e Júnias, meus parentes e companheiros de prisão, os quais são bem conhecidos entre os apóstolos e estavam em Cristo antes de mim.

[[v45-16-8]]

^<<v45-16-8,8>>^ Saúdem Amplíato, meu querido amigo no Senhor.

[[v45-16-9]]

^<<v45-16-9,9>>^ Saúdem Urbano, que é nosso cooperador em Cristo, e também meu amado Estáquis.

[[v45-16-10]]

^<<v45-16-10,10>>^ Saúdem Apeles, aprovado em Cristo. Saúdem os da casa de Aristóbulo.

[[v45-16-11]]

^<<v45-16-11,11>>^ Saúdem meu parente Herodião. Saúdem os da casa de Narciso, que estão no Senhor.

[[v45-16-12]]

^<<v45-16-12,12>>^ Saúdem Trifena e Trifosa, as quais trabalham no Senhor. Saúdem a querida Pérside, que também muito trabalhou no Senhor.

[[v45-16-13]]

^<<v45-16-13,13>>^ Saúdem Rufo, eleito no Senhor, e igualmente a mãe dele, que também tem sido mãe para mim.

[[v45-16-14]]

^<<v45-16-14,14>>^ Saúdem Asíncrito, Flegonte, Hermes, Pátrobas, Hermas e os irmãos que se reúnem com eles.

[[v45-16-15]]

^<<v45-16-15,15>>^ Saúdem Filólogo, Júlia, Nereu e sua irmã, Olimpas e todos os santos que se reúnem com eles.

[[v45-16-16]]

^<<v45-16-16,16>>^ Saúdem uns aos outros com um beijo santo. Todas as igrejas de Cristo mandam saudações.

[[v45-16-17]]

^<<v45-16-17,17>>^ Irmãos, peço que notem bem aqueles que provocam divisões e escândalos, em desacordo com a doutrina que vocês aprenderam. Afastem-se deles,

[[v45-16-18]]

^<<v45-16-18,18>>^ porque esses tais não servem a Cristo, nosso Senhor, e sim a seu próprio ventre. Com suaves palavras e lisonjas, enganam o coração das pessoas simples.

[[v45-16-19]]

^<<v45-16-19,19>>^ Pois a obediência de vocês é conhecida por todos; por isso, me alegro por causa de vocês. Quero que sejam sábios no que diz respeito ao bem e simples no que diz respeito ao mal.

[[v45-16-20]]

^<<v45-16-20,20>>^ E o Deus da paz, em breve, esmagará Satanás debaixo dos pés de vocês. A graça de nosso Senhor Jesus esteja com vocês.

[[v45-16-21]]

^<<v45-16-21,21>>^ Timóteo, meu cooperador, manda saudações, assim como Lúcio, Jasom e Sosípatro, meus parentes.

[[v45-16-22]]

^<<v45-16-22,22>>^ Eu, Tércio, que escrevi esta carta, mando saudações no Senhor.

[[v45-16-23]]

^<<v45-16-23,23>>^ Gaio, meu hospedeiro e de toda a igreja, manda saudações. Também mandam saudações Erasto, tesoureiro da cidade, e o irmão Quarto.

[[v45-16-24]]

^<<v45-16-24,24>>^ &#91;A graça de nosso Senhor Jesus Cristo esteja com todos vocês. Amém!&#93;

[[v45-16-25]]

^<<v45-16-25,25>>^ Ora, ao Deus que é poderoso para confirmar vocês segundo o meu evangelho e a pregação de Jesus Cristo, conforme a revelação do mistério guardado em silêncio desde os tempos eternos,

[[v45-16-26]]

^<<v45-16-26,26>>^ e que, agora, tornou-se manifesto e foi dado a conhecer por meio das Escrituras proféticas, segundo o mandamento do Deus eterno, para a obediência da fé, entre todas as nações,

[[v45-16-27]]

^<<v45-16-27,27>>^ a este Deus único e sábio seja dada glória, por meio de Jesus Cristo, para sempre. Amém!

'''

xref:045-romanos/045-romanos-015.adoc#v45-15-0[&#60; Capítulo Anterior] | <<v45-16-0,Topo>> | xref:046-1-corintios/046-1-corintios-001.adoc#v46-1-0[Próximo Capítulo &#62;]