include::./index.adoc[]

[[v45-6-0]]
=== Romanos, 6
// naa ?, NAA - Nova Almeida Atualizada

[[v45-6-1]]

^<<v45-6-1,1>>^ Que diremos, então? Continuaremos no pecado, para que a graça aumente ainda mais?

[[v45-6-2]]

^<<v45-6-2,2>>^ De modo nenhum! Como viveremos ainda no pecado, nós, que já morremos para ele?

[[v45-6-3]]

^<<v45-6-3,3>>^ Ou será que vocês ignoram que todos nós que fomos batizados em Cristo Jesus fomos batizados na sua morte?

[[v45-6-4]]

^<<v45-6-4,4>>^ Fomos sepultados com ele na morte pelo batismo, para que, como Cristo foi ressuscitado dentre os mortos pela glória do Pai, assim também nós andemos em novidade de vida.

[[v45-6-5]]

^<<v45-6-5,5>>^ Porque, se fomos unidos com ele na semelhança da sua morte, certamente o seremos também na semelhança da sua ressurreição,

[[v45-6-6]]

^<<v45-6-6,6>>^ sabendo isto: que a nossa velha natureza foi crucificada com ele, para que o corpo do pecado seja destruído, e não sejamos mais escravos do pecado.

[[v45-6-7]]

^<<v45-6-7,7>>^ Pois quem morreu está justificado do pecado.

[[v45-6-8]]

^<<v45-6-8,8>>^ Ora, se já morremos com Cristo, cremos que também viveremos com ele.

[[v45-6-9]]

^<<v45-6-9,9>>^ Sabemos que, havendo Cristo ressuscitado dentre os mortos, já não morre; a morte já não tem domínio sobre ele.

[[v45-6-10]]

^<<v45-6-10,10>>^ Pois, quanto a ter morrido, de uma vez para sempre morreu para o pecado; mas, quanto a viver, vive para Deus.

[[v45-6-11]]

^<<v45-6-11,11>>^ Assim também vocês considerem-se mortos para o pecado, mas vivos para Deus, em Cristo Jesus.

[[v45-6-12]]

^<<v45-6-12,12>>^ Portanto, não permitam que o pecado reine em seu corpo mortal, fazendo com que vocês obedeçam às suas paixões.

[[v45-6-13]]

^<<v45-6-13,13>>^ Também não ofereçam os membros do corpo ao pecado, como instrumentos de injustiça, mas, como pessoas que passaram da morte para a vida, ofereçam a si mesmos a Deus e ofereçam os seus membros a Deus, como instrumentos de justiça.

[[v45-6-14]]

^<<v45-6-14,14>>^ Porque o pecado não terá domínio sobre vocês, pois vocês não estão debaixo da lei, e sim da graça.

[[v45-6-15]]

^<<v45-6-15,15>>^ E então? Havemos de pecar porque não estamos debaixo da lei, e sim da graça? De modo nenhum!

[[v45-6-16]]

^<<v45-6-16,16>>^ Será que vocês não sabem que, ao se oferecerem como servos para obediência, vocês são servos daquele a quem obedecem, seja do pecado, que leva à morte, ou da obediência, que conduz à justiça?

[[v45-6-17]]

^<<v45-6-17,17>>^ Mas graças a Deus que, tendo sido escravos do pecado, vocês vieram a obedecer de coração à forma de doutrina a que foram entregues.

[[v45-6-18]]

^<<v45-6-18,18>>^ E, uma vez libertados do pecado, foram feitos servos da justiça.

[[v45-6-19]]

^<<v45-6-19,19>>^ Falo em termos humanos, por causa das limitações de vocês. Assim como ofereceram os seus membros para que fossem escravos da impureza e da maldade que leva à maldade, assim ofereçam agora os seus membros para que sejam servos da justiça para a santificação.

[[v45-6-20]]

^<<v45-6-20,20>>^ Porque, quando vocês eram escravos do pecado, estavam livres em relação à justiça.

[[v45-6-21]]

^<<v45-6-21,21>>^ Naquele tempo, que frutos vocês colheram? Somente as coisas de que agora vocês se envergonham. Porque o fim delas é morte.

[[v45-6-22]]

^<<v45-6-22,22>>^ Agora, porém, libertados do pecado, transformados em servos de Deus, o fruto que vocês colhem é para a santificação. E o fim, neste caso, é a vida eterna.

[[v45-6-23]]

^<<v45-6-23,23>>^ Porque o salário do pecado é a morte, mas o dom gratuito de Deus é a vida eterna em Cristo Jesus, nosso Senhor.

'''

xref:045-romanos/045-romanos-005.adoc#v45-5-0[&#60; Capítulo Anterior] | <<v45-6-0,Topo>> | xref:045-romanos/045-romanos-007.adoc#v45-7-0[Próximo Capítulo &#62;]