include::./index.adoc[]

[[v45-3-0]]
=== Romanos, 3
// naa ?, NAA - Nova Almeida Atualizada

[[v45-3-1]]

^<<v45-3-1,1>>^ Qual é, então, a vantagem do judeu? Ou qual a utilidade da circuncisão?

[[v45-3-2]]

^<<v45-3-2,2>>^ Muita, sob todos os aspectos. Principalmente porque aos judeus foram confiados os oráculos de Deus.

[[v45-3-3]]

^<<v45-3-3,3>>^ E então? Se alguns não creram, será que a incredulidade deles anulará a fidelidade de Deus?

[[v45-3-4]]

^<<v45-3-4,4>>^ De modo nenhum! Seja Deus verdadeiro, e todo ser humano, mentiroso, como está escrito: "Para que sejas justificado nas tuas palavras e venhas a vencer quando fores julgado."

[[v45-3-5]]

^<<v45-3-5,5>>^ Mas, se a nossa injustiça evidencia a justiça de Deus, que diremos? Seria Deus injusto por aplicar a sua ira? Falo em termos humanos.

[[v45-3-6]]

^<<v45-3-6,6>>^ É claro que não. Do contrário, como Deus julgará o mundo?

[[v45-3-7]]

^<<v45-3-7,7>>^ E, se a minha mentira faz com que aumente a verdade de Deus para a sua glória, por que ainda sou condenado como pecador?

[[v45-3-8]]

^<<v45-3-8,8>>^ E por que não dizemos, como alguns caluniosamente afirmam que o fazemos: "Pratiquemos o que é mau, para que nos venha o que é bom"? A condenação destes é justa.

[[v45-3-9]]

^<<v45-3-9,9>>^ Que se conclui? Temos nós alguma vantagem? Não, de forma nenhuma. Pois já temos demonstrado que todos, tanto judeus como gregos, estão debaixo do pecado.

[[v45-3-10]]

^<<v45-3-10,10>>^ Como está escrito: "Não há justo, nem um sequer,

[[v45-3-11]]

^<<v45-3-11,11>>^ não há quem entenda, não há quem busque a Deus.

[[v45-3-12]]

^<<v45-3-12,12>>^ Todos se desviaram e juntamente se tornaram inúteis; não há quem faça o bem, não há nem um sequer.

[[v45-3-13]]

^<<v45-3-13,13>>^ A garganta deles é sepulcro aberto; com a língua enganam, veneno de víbora está nos seus lábios.

[[v45-3-14]]

^<<v45-3-14,14>>^ A boca, eles a têm cheia de maldição e amargura;

[[v45-3-15]]

^<<v45-3-15,15>>^ os seus pés são velozes para derramar sangue.

[[v45-3-16]]

^<<v45-3-16,16>>^ Nos seus caminhos, há destruição e miséria;

[[v45-3-17]]

^<<v45-3-17,17>>^ eles não conhecem o caminho da paz.

[[v45-3-18]]

^<<v45-3-18,18>>^ Não há temor de Deus diante de seus olhos."

[[v45-3-19]]

^<<v45-3-19,19>>^ Ora, sabemos que tudo o que a lei diz é dito aos que vivem sob a lei, para que toda boca se cale, e todo o mundo seja culpável diante de Deus.

[[v45-3-20]]

^<<v45-3-20,20>>^ Porque ninguém será justificado diante de Deus por obras da lei, pois pela lei vem o pleno conhecimento do pecado.

[[v45-3-21]]

^<<v45-3-21,21>>^ Mas, agora, sem lei, a justiça de Deus se manifestou, sendo testemunhada pela Lei e pelos Profetas.

[[v45-3-22]]

^<<v45-3-22,22>>^ É a justiça de Deus mediante a fé em Jesus Cristo, para todos e sobre todos os que creem. Porque não há distinção,

[[v45-3-23]]

^<<v45-3-23,23>>^ pois todos pecaram e carecem da glória de Deus,

[[v45-3-24]]

^<<v45-3-24,24>>^ sendo justificados gratuitamente, por sua graça, mediante a redenção que há em Cristo Jesus,

[[v45-3-25]]

^<<v45-3-25,25>>^ a quem Deus apresentou como propiciação, no seu sangue, mediante a fé. Deus fez isso para manifestar a sua justiça, por ter ele, na sua tolerância, deixado impunes os pecados anteriormente cometidos,

[[v45-3-26]]

^<<v45-3-26,26>>^ tendo em vista a manifestação da sua justiça no tempo presente, a fim de que o próprio Deus seja justo e o justificador daquele que tem fé em Jesus.

[[v45-3-27]]

^<<v45-3-27,27>>^ Onde fica, então, o orgulho? Foi totalmente excluído. Por meio de que lei? A lei das obras? Não! Pelo contrário, por meio da lei da fé.

[[v45-3-28]]

^<<v45-3-28,28>>^ Concluímos, pois, que o ser humano é justificado pela fé, independentemente das obras da lei.

[[v45-3-29]]

^<<v45-3-29,29>>^ Ou seria Deus apenas Deus dos judeus? Será que não é também Deus dos gentios? Sim, também dos gentios,

[[v45-3-30]]

^<<v45-3-30,30>>^ visto que Deus é um só, o qual justificará o circunciso a partir da fé e o incircunciso por meio da fé.

[[v45-3-31]]

^<<v45-3-31,31>>^ Anulamos, então, a lei por meio da fé? De modo nenhum! Pelo contrário, confirmamos a lei.

'''

xref:045-romanos/045-romanos-002.adoc#v45-2-0[&#60; Capítulo Anterior] | <<v45-3-0,Topo>> | xref:045-romanos/045-romanos-004.adoc#v45-4-0[Próximo Capítulo &#62;]