include::./index.adoc[]

[[v45-5-0]]
=== Romanos, 5
// naa ?, NAA - Nova Almeida Atualizada

[[v45-5-1]]

^<<v45-5-1,1>>^ Justificados, pois, mediante a fé, temos paz com Deus por meio do nosso Senhor Jesus Cristo,

[[v45-5-2]]

^<<v45-5-2,2>>^ pelo qual obtivemos também acesso, pela fé, a esta graça na qual estamos firmes; e nos gloriamos na esperança da glória de Deus.

[[v45-5-3]]

^<<v45-5-3,3>>^ E não somente isto, mas também nos gloriamos nas tribulações, sabendo que a tribulação produz perseverança,

[[v45-5-4]]

^<<v45-5-4,4>>^ a perseverança produz experiência e a experiência produz esperança.

[[v45-5-5]]

^<<v45-5-5,5>>^ Ora, a esperança não nos deixa decepcionados, porque o amor de Deus é derramado em nosso coração pelo Espírito Santo, que nos foi dado.

[[v45-5-6]]

^<<v45-5-6,6>>^ Porque Cristo, quando nós ainda éramos fracos, morreu a seu tempo pelos ímpios.

[[v45-5-7]]

^<<v45-5-7,7>>^ Dificilmente alguém morreria por um justo, embora por uma pessoa boa alguém talvez tenha coragem para morrer.

[[v45-5-8]]

^<<v45-5-8,8>>^ Mas Deus prova o seu próprio amor para conosco pelo fato de Cristo ter morrido por nós quando ainda éramos pecadores.

[[v45-5-9]]

^<<v45-5-9,9>>^ Logo, muito mais agora, sendo justificados pelo seu sangue, seremos por ele salvos da ira.

[[v45-5-10]]

^<<v45-5-10,10>>^ Porque, se nós, quando inimigos, fomos reconciliados com Deus mediante a morte do seu Filho, muito mais, estando já reconciliados, seremos salvos pela sua vida!

[[v45-5-11]]

^<<v45-5-11,11>>^ E não apenas isto, mas também nos gloriamos em Deus por meio do nosso Senhor Jesus Cristo, mediante o qual recebemos, agora, a reconciliação.

[[v45-5-12]]

^<<v45-5-12,12>>^ Portanto, assim como por um só homem entrou o pecado no mundo, e pelo pecado veio a morte, assim também a morte passou a toda a humanidade, porque todos pecaram.

[[v45-5-13]]

^<<v45-5-13,13>>^ Porque antes de a lei ser dada havia pecado no mundo, mas o pecado não é levado em conta quando não há lei.

[[v45-5-14]]

^<<v45-5-14,14>>^ No entanto, a morte reinou desde Adão até Moisés, mesmo sobre aqueles que não pecaram à semelhança da transgressão de Adão, o qual prefigurava aquele que havia de vir.

[[v45-5-15]]

^<<v45-5-15,15>>^ Mas o dom gratuito não é como a ofensa. Porque, se muitos morreram pela ofensa de um só, muito mais a graça de Deus e o dom pela graça de um só homem, Jesus Cristo, foram abundantes sobre muitos!

[[v45-5-16]]

^<<v45-5-16,16>>^ O dom, entretanto, não é como no caso em que somente um pecou. Porque o julgamento derivou de uma só ofensa, para a condenação; mas a graça deriva de muitas ofensas, para a justificação.

[[v45-5-17]]

^<<v45-5-17,17>>^ Se a morte reinou pela ofensa de um e por meio de um só, muito mais os que recebem a abundância da graça e o dom da justiça reinarão em vida por meio de um só, a saber, Jesus Cristo.

[[v45-5-18]]

^<<v45-5-18,18>>^ Portanto, assim como, por uma só ofensa, veio o juízo sobre todos os seres humanos para condenação, assim também, por um só ato de justiça, veio a graça sobre todos para a justificação que dá vida.

[[v45-5-19]]

^<<v45-5-19,19>>^ Porque, como, pela desobediência de um só homem, muitos se tornaram pecadores, assim também, por meio da obediência de um só, muitos se tornarão justos.

[[v45-5-20]]

^<<v45-5-20,20>>^ A lei veio para que aumentasse a ofensa. Mas onde aumentou o pecado, aumentou muito mais ainda a graça,

[[v45-5-21]]

^<<v45-5-21,21>>^ a fim de que, como o pecado reinou pela morte, assim também a graça reinasse pela justiça que conduz à vida eterna, por meio de Jesus Cristo, nosso Senhor.

'''

xref:045-romanos/045-romanos-004.adoc#v45-4-0[&#60; Capítulo Anterior] | <<v45-5-0,Topo>> | xref:045-romanos/045-romanos-006.adoc#v45-6-0[Próximo Capítulo &#62;]