include::./index.adoc[]

[[v45-4-0]]
=== Romanos, 4
// naa ?, NAA - Nova Almeida Atualizada

[[v45-4-1]]

^<<v45-4-1,1>>^ Que diremos, então, a respeito de Abraão, nosso pai segundo a carne? O que foi que ele conseguiu?

[[v45-4-2]]

^<<v45-4-2,2>>^ Porque, se Abraão foi justificado por obras, tem do que se orgulhar, porém não diante de Deus.

[[v45-4-3]]

^<<v45-4-3,3>>^ Pois o que diz a Escritura? Ela diz: "Abraão creu em Deus, e isso lhe foi atribuído para justiça."

[[v45-4-4]]

^<<v45-4-4,4>>^ Ora, para quem trabalha, o salário não é considerado como favor, mas como dívida.

[[v45-4-5]]

^<<v45-4-5,5>>^ Mas, para quem não trabalha, porém crê naquele que justifica o ímpio, a sua fé lhe é atribuída como justiça.

[[v45-4-6]]

^<<v45-4-6,6>>^ E é assim também que Davi declara ser bem-aventurado aquele a quem Deus atribui justiça, independentemente de obras.

[[v45-4-7]]

^<<v45-4-7,7>>^ Davi disse: "Bem-aventurados aqueles cujas transgressões são perdoadas, e cujos pecados são cobertos;

[[v45-4-8]]

^<<v45-4-8,8>>^ bem-aventurado aquele a quem o Senhor jamais atribuir pecado."

[[v45-4-9]]

^<<v45-4-9,9>>^ Esta bem-aventurança vem apenas sobre os circuncisos ou será que ela vem também sobre os incircuncisos? Porque dizemos: "A fé foi atribuída a Abraão para justiça."

[[v45-4-10]]

^<<v45-4-10,10>>^ Como, pois, lhe foi atribuída? Estando ele já circuncidado ou sendo ainda incircunciso? Não foi no regime da circuncisão, mas quando ele ainda não havia sido circuncidado.

[[v45-4-11]]

^<<v45-4-11,11>>^ E Abraão recebeu o sinal da circuncisão como selo da justiça da fé que teve quando ainda não havia sido circuncidado. E isto para que ele viesse a ser o pai de todos os que creem, embora não circuncidados, a fim de que a justiça fosse atribuída também a eles.

[[v45-4-12]]

^<<v45-4-12,12>>^ Ele é também pai da circuncisão, isto é, daqueles que não são apenas circuncisos, mas também andam nas pisadas da fé que teve Abraão, nosso pai, antes de ser circuncidado.

[[v45-4-13]]

^<<v45-4-13,13>>^ A promessa de que seria herdeiro do mundo não veio a Abraão ou à sua descendência por meio da lei, e sim por meio da justiça da fé.

[[v45-4-14]]

^<<v45-4-14,14>>^ Pois, se os da lei é que são os herdeiros, anula-se a fé e cancela-se a promessa.

[[v45-4-15]]

^<<v45-4-15,15>>^ Porque a lei suscita a ira; mas onde não há lei, também não há transgressão.

[[v45-4-16]]

^<<v45-4-16,16>>^ Essa é a razão por que provém da fé, para que seja segundo a graça, a fim de que a promessa seja garantida para toda a descendência, não somente à descendência que está no regime da lei, mas também à descendência que tem a fé que Abraão teve — porque Abraão é pai de todos nós,

[[v45-4-17]]

^<<v45-4-17,17>>^ como está escrito: "Eu o constituí por pai de muitas nações" — diante daquele em quem Abraão creu, o Deus que vivifica os mortos e chama à existência as coisas que não existem.

[[v45-4-18]]

^<<v45-4-18,18>>^ Abraão, esperando contra a esperança, creu, para vir a ser pai de muitas nações, segundo lhe havia sido dito: "Assim será a sua descendência."

[[v45-4-19]]

^<<v45-4-19,19>>^ E, sem enfraquecer na fé, levou em conta o seu próprio corpo já amortecido, tendo ele quase cem anos, e a esterilidade do ventre de Sara.

[[v45-4-20]]

^<<v45-4-20,20>>^ Não duvidou, por incredulidade, da promessa de Deus; mas, pela fé, se fortaleceu, dando glória a Deus,

[[v45-4-21]]

^<<v45-4-21,21>>^ estando plenamente convicto de que Deus era poderoso para cumprir o que havia prometido.

[[v45-4-22]]

^<<v45-4-22,22>>^ Assim, também isso lhe foi atribuído para justiça.

[[v45-4-23]]

^<<v45-4-23,23>>^ E as palavras "lhe foi atribuído" foram escritas não somente por causa dele,

[[v45-4-24]]

^<<v45-4-24,24>>^ mas também por nossa causa, visto que a nós igualmente nos será atribuído, a saber, a nós que cremos naquele que ressuscitou dentre os mortos a Jesus, nosso Senhor,

[[v45-4-25]]

^<<v45-4-25,25>>^ o qual foi entregue por causa das nossas transgressões e ressuscitou para a nossa justificação.

'''

xref:045-romanos/045-romanos-003.adoc#v45-3-0[&#60; Capítulo Anterior] | <<v45-4-0,Topo>> | xref:045-romanos/045-romanos-005.adoc#v45-5-0[Próximo Capítulo &#62;]