include::./index.adoc[]

[[v45-14-0]]
=== Romanos, 14
// naa ?, NAA - Nova Almeida Atualizada

[[v45-14-1]]

^<<v45-14-1,1>>^ Acolham quem é fraco na fé, não, porém, para discutir opiniões.

[[v45-14-2]]

^<<v45-14-2,2>>^ Um crê que pode comer de tudo, mas quem é fraco na fé come legumes.

[[v45-14-3]]

^<<v45-14-3,3>>^ Quem come de tudo não deve desprezar o que não come; e o que não come não deve julgar o que come de tudo, porque Deus o acolheu.

[[v45-14-4]]

^<<v45-14-4,4>>^ Quem é você para julgar o servo alheio? Para o seu próprio dono é que ele está em pé ou cai; mas ficará em pé, porque o Senhor é poderoso para o manter em pé.

[[v45-14-5]]

^<<v45-14-5,5>>^ Alguns pensam que certos dias são mais importantes do que os demais, mas outros pensam que todos os dias são iguais. Cada um tenha opinião bem-definida em sua própria mente.

[[v45-14-6]]

^<<v45-14-6,6>>^ Quem pensa que certos dias são mais importantes faz isso para o Senhor. Quem come de tudo faz isso para o Senhor, porque dá graças a Deus. E quem não come de tudo é para o Senhor que não come e dá graças a Deus.

[[v45-14-7]]

^<<v45-14-7,7>>^ Porque nenhum de nós vive para si mesmo, nem morre para si.

[[v45-14-8]]

^<<v45-14-8,8>>^ Porque, se vivemos, é para o Senhor que vivemos; se morremos, é para o Senhor que morremos. Quer, pois, vivamos ou morramos, somos do Senhor.

[[v45-14-9]]

^<<v45-14-9,9>>^ Foi precisamente para esse fim que Cristo morreu e tornou a viver: para ser Senhor tanto de mortos como de vivos.

[[v45-14-10]]

^<<v45-14-10,10>>^ Você, porém, por que julga o seu irmão? E você, por que despreza o seu irmão? Pois todos temos de comparecer diante do tribunal de Deus.

[[v45-14-11]]

^<<v45-14-11,11>>^ Como está escrito: "Por minha vida, diz o Senhor, diante de mim se dobrará todo joelho, e toda língua dará louvores a Deus."

[[v45-14-12]]

^<<v45-14-12,12>>^ Assim, pois, cada um de nós prestará contas de si mesmo diante de Deus.

[[v45-14-13]]

^<<v45-14-13,13>>^ Portanto, deixemos de julgar uns aos outros. Pelo contrário, tomem a decisão de não pôr tropeço ou escândalo diante do irmão.

[[v45-14-14]]

^<<v45-14-14,14>>^ Eu sei e estou persuadido, no Senhor Jesus, de que nada é impuro em si mesmo, a não ser para aquele que pensa que alguma coisa é impura; para esse é impura.

[[v45-14-15]]

^<<v45-14-15,15>>^ Se o seu irmão fica triste por causa do que você come, você já não anda segundo o amor. Não faça perecer, por causa daquilo que você come, aquele por quem Cristo morreu.

[[v45-14-16]]

^<<v45-14-16,16>>^ Não seja, pois, difamado aquilo que vocês consideram bom.

[[v45-14-17]]

^<<v45-14-17,17>>^ Porque o Reino de Deus não é comida nem bebida, mas justiça, paz e alegria no Espírito Santo.

[[v45-14-18]]

^<<v45-14-18,18>>^ Aquele que deste modo serve a Cristo é agradável a Deus e aprovado pelas pessoas.

[[v45-14-19]]

^<<v45-14-19,19>>^ Assim, pois, sigamos as coisas que contribuem para a paz e também as que são para a edificação mútua.

[[v45-14-20]]

^<<v45-14-20,20>>^ Não destrua a obra de Deus por causa da comida. Todas as coisas, na verdade, são puras, mas não é bom quando alguém come algo que causa escândalo.

[[v45-14-21]]

^<<v45-14-21,21>>^ É bom não comer carne, nem beber vinho, nem fazer qualquer outra coisa que leve um irmão a tropeçar.

[[v45-14-22]]

^<<v45-14-22,22>>^ A fé que você tem, guarde-a para você mesmo diante de Deus. Bem-aventurado é aquele que não se condena naquilo que aprova.

[[v45-14-23]]

^<<v45-14-23,23>>^ Mas aquele que tem dúvidas é condenado se comer, pois o que ele faz não provém de fé; e tudo o que não provém de fé é pecado.

'''

xref:045-romanos/045-romanos-013.adoc#v45-13-0[&#60; Capítulo Anterior] | <<v45-14-0,Topo>> | xref:045-romanos/045-romanos-015.adoc#v45-15-0[Próximo Capítulo &#62;]