include::./index.adoc[]

[[v45-10-0]]
=== Romanos, 10
// naa ?, NAA - Nova Almeida Atualizada

[[v45-10-1]]

^<<v45-10-1,1>>^ Irmãos, o desejo do meu coração e a minha súplica a Deus em favor deles é para que sejam salvos.

[[v45-10-2]]

^<<v45-10-2,2>>^ Porque dou testemunho a favor deles de que têm zelo por Deus, porém não com entendimento.

[[v45-10-3]]

^<<v45-10-3,3>>^ Desconhecendo a justiça de Deus e procurando estabelecer a sua própria justiça, não se sujeitaram à justiça que vem de Deus.

[[v45-10-4]]

^<<v45-10-4,4>>^ Porque o fim da lei é Cristo, para justiça de todo aquele que crê.

[[v45-10-5]]

^<<v45-10-5,5>>^ Ora, Moisés descreve assim a justiça que procede da lei: "Aquele que observar os seus preceitos por eles viverá."

[[v45-10-6]]

^<<v45-10-6,6>>^ Mas a justiça que procede da fé afirma o seguinte: "Não pergunte em seu coração: Quem subirá ao céu?", isto é, para trazer Cristo lá do alto;

[[v45-10-7]]

^<<v45-10-7,7>>^ ou: "Quem descerá ao abismo?", isto é, para levantar Cristo dentre os mortos.

[[v45-10-8]]

^<<v45-10-8,8>>^ Porém, o que se diz? "A palavra está perto de você, na sua boca e no seu coração", isto é, a palavra da fé que pregamos.

[[v45-10-9]]

^<<v45-10-9,9>>^ Se com a boca você confessar Jesus como Senhor e em seu coração crer que Deus o ressuscitou dentre os mortos, você será salvo.

[[v45-10-10]]

^<<v45-10-10,10>>^ Porque com o coração se crê para a justiça e com a boca se confessa para a salvação.

[[v45-10-11]]

^<<v45-10-11,11>>^ Pois a Escritura diz: "Todo aquele que nele crê não será envergonhado."

[[v45-10-12]]

^<<v45-10-12,12>>^ Porque não há distinção entre judeu e grego, uma vez que o mesmo é o Senhor de todos, rico para com todos os que o invocam.

[[v45-10-13]]

^<<v45-10-13,13>>^ Porque: "Todo aquele que invocar o nome do Senhor será salvo."

[[v45-10-14]]

^<<v45-10-14,14>>^ Como, porém, invocarão aquele em quem não creram? E como crerão naquele de quem nada ouviram? E como ouvirão, se não há quem pregue?

[[v45-10-15]]

^<<v45-10-15,15>>^ E como pregarão, se não forem enviados? Como está escrito: "Quão formosos são os pés dos que anunciam coisas boas!"

[[v45-10-16]]

^<<v45-10-16,16>>^ Mas nem todos obedeceram ao evangelho. Pois Isaías diz: "Senhor, quem creu em nossa pregação?"

[[v45-10-17]]

^<<v45-10-17,17>>^ E, assim, a fé vem pelo ouvir, e o ouvir, pela palavra de Cristo.

[[v45-10-18]]

^<<v45-10-18,18>>^ Mas pergunto: Será que eles não ouviram? É claro que sim! "A voz deles se espalhou por toda a terra, e as palavras deles alcançaram os confins do mundo."

[[v45-10-19]]

^<<v45-10-19,19>>^ Pergunto mais: será que isso não chegou ao conhecimento de Israel? Moisés já dizia: "Eu farei com que vocês fiquem com ciúmes de um povo que não é nação; por meio de gente insensata eu os provocarei à ira."

[[v45-10-20]]

^<<v45-10-20,20>>^ E Isaías é tão ousado que diz: "Fui achado pelos que não me procuravam, revelei-me aos que não perguntavam por mim."

[[v45-10-21]]

^<<v45-10-21,21>>^ Quanto a Israel, porém, diz: "Todo o dia estendi as mãos a um povo desobediente e rebelde."

'''

xref:045-romanos/045-romanos-009.adoc#v45-9-0[&#60; Capítulo Anterior] | <<v45-10-0,Topo>> | xref:045-romanos/045-romanos-011.adoc#v45-11-0[Próximo Capítulo &#62;]