include::./index.adoc[]

[[v45-9-0]]
=== Romanos, 9
// naa ?, NAA - Nova Almeida Atualizada

[[v45-9-1]]

^<<v45-9-1,1>>^ Digo a verdade em Cristo, não minto, e a minha consciência confirma isso por meio do Espírito Santo:

[[v45-9-2]]

^<<v45-9-2,2>>^ sinto grande tristeza e tenho incessante dor no coração.

[[v45-9-3]]

^<<v45-9-3,3>>^ Porque eu mesmo desejaria ser amaldiçoado, separado de Cristo, por amor de meus irmãos, meus compatriotas segundo a carne.

[[v45-9-4]]

^<<v45-9-4,4>>^ São israelitas. A eles pertence a adoção, assim como a glória, as alianças, a promulgação da Lei, o culto e as promessas.

[[v45-9-5]]

^<<v45-9-5,5>>^ Deles são os patriarcas, e também deles descende o Cristo, segundo a carne, o qual é sobre todos, Deus bendito para sempre. Amém!

[[v45-9-6]]

^<<v45-9-6,6>>^ E não pensemos que a palavra de Deus falhou. Porque nem todos os de Israel são, de fato, israelitas,

[[v45-9-7]]

^<<v45-9-7,7>>^ nem por serem descendentes de Abraão são todos filhos. Pelo contrário: "Por meio de Isaque será chamada a sua descendência."

[[v45-9-8]]

^<<v45-9-8,8>>^ Isto é, não são os filhos da carne que são filhos de Deus, mas os filhos da promessa é que são contados como descendência.

[[v45-9-9]]

^<<v45-9-9,9>>^ Porque a palavra da promessa é esta: "Por esse tempo voltarei, e Sara terá um filho."

[[v45-9-10]]

^<<v45-9-10,10>>^ E isto não aconteceu somente com ela, mas também com Rebeca, ao conceber de um só, de Isaque, nosso pai.

[[v45-9-11]]

^<<v45-9-11,11>>^ E os gêmeos ainda não eram nascidos, nem tinham feito o bem ou o mal — para que o propósito de Deus, quanto à eleição, prevalecesse, não por obras, mas por aquele que chama —,

[[v45-9-12]]

^<<v45-9-12,12>>^ quando foi dito a Rebeca: "O mais velho será servo do mais moço."

[[v45-9-13]]

^<<v45-9-13,13>>^ Como está escrito: "Amei Jacó, porém desprezei Esaú."

[[v45-9-14]]

^<<v45-9-14,14>>^ Que diremos, então? Que Deus é injusto? De modo nenhum!

[[v45-9-15]]

^<<v45-9-15,15>>^ Pois ele diz a Moisés: "Terei misericórdia de quem eu tiver misericórdia e terei compaixão de quem eu tiver compaixão."

[[v45-9-16]]

^<<v45-9-16,16>>^ Assim, pois, isto não depende de quem quer ou de quem corre, mas de Deus, que tem misericórdia.

[[v45-9-17]]

^<<v45-9-17,17>>^ Porque a Escritura diz a Faraó: "Foi para isto mesmo que eu o levantei, para mostrar em você o meu poder e para que o meu nome seja anunciado em toda a terra."

[[v45-9-18]]

^<<v45-9-18,18>>^ Logo, Deus tem misericórdia de quem quer e também endurece a quem ele quer.

[[v45-9-19]]

^<<v45-9-19,19>>^ Mas você vai me dizer: "Por que Deus ainda se queixa? Pois quem pode resistir à sua vontade?"

[[v45-9-20]]

^<<v45-9-20,20>>^ Mas quem é você, caro amigo, para discutir com Deus? Será que o objeto pode perguntar a quem o fez: "Por que você me fez assim?"

[[v45-9-21]]

^<<v45-9-21,21>>^ Será que o oleiro não tem direito sobre a massa, para do mesmo barro fazer um vaso para honra e outro para desonra?

[[v45-9-22]]

^<<v45-9-22,22>>^ Que diremos, se Deus, querendo mostrar a sua ira e dar a conhecer o seu poder, suportou com muita paciência os vasos de ira, preparados para a destruição,

[[v45-9-23]]

^<<v45-9-23,23>>^ a fim de que também desse a conhecer as riquezas da sua glória nos vasos de misericórdia, que de antemão preparou para glória?

[[v45-9-24]]

^<<v45-9-24,24>>^ Estes vasos somos nós, a quem também chamou, não só dentre os judeus, mas também dentre os gentios,

[[v45-9-25]]

^<<v45-9-25,25>>^ como também diz em Oseias: "Chamarei de ‘meu povo’ ao que não era meu povo; e de ‘amada’ à que não era amada.

[[v45-9-26]]

^<<v45-9-26,26>>^ E no lugar em que lhes foi dito: ‘Vocês não são o meu povo’, ali mesmo serão chamados ‘filhos do Deus vivo’."

[[v45-9-27]]

^<<v45-9-27,27>>^ Mas Isaías clama a respeito de Israel: "Ainda que o número dos filhos de Israel seja como a areia do mar, o remanescente é que será salvo.

[[v45-9-28]]

^<<v45-9-28,28>>^ Porque o Senhor cumprirá a sua palavra sobre a terra, de forma plena e em breve."

[[v45-9-29]]

^<<v45-9-29,29>>^ Como Isaías já disse: "Se o Senhor dos Exércitos não nos tivesse deixado descendência, nós nos teríamos tornado como Sodoma e semelhantes a Gomorra."

[[v45-9-30]]

^<<v45-9-30,30>>^ Que diremos, então? Que os gentios, que não buscavam a justificação, vieram a alcançá-la, a saber, a justificação que decorre da fé,

[[v45-9-31]]

^<<v45-9-31,31>>^ e que Israel, que buscava a lei de justiça, não chegou a atingir essa lei.

[[v45-9-32]]

^<<v45-9-32,32>>^ Por quê? Porque não a buscou pela fé, mas como que por obras. Tropeçaram na pedra de tropeço,

[[v45-9-33]]

^<<v45-9-33,33>>^ como está escrito: "Eis que ponho em Sião uma pedra de tropeço e rocha de ofensa, e aquele que nela crê não será envergonhado."

'''

xref:045-romanos/045-romanos-008.adoc#v45-8-0[&#60; Capítulo Anterior] | <<v45-9-0,Topo>> | xref:045-romanos/045-romanos-010.adoc#v45-10-0[Próximo Capítulo &#62;]