include::./index.adoc[]

[[v45-15-0]]
=== Romanos, 15
// naa ?, NAA - Nova Almeida Atualizada

[[v45-15-1]]

^<<v45-15-1,1>>^ Ora, nós que somos fortes na fé temos de suportar as debilidades dos fracos e não agradar a nós mesmos.

[[v45-15-2]]

^<<v45-15-2,2>>^ Portanto, cada um de nós agrade ao próximo no que é bom para edificação.

[[v45-15-3]]

^<<v45-15-3,3>>^ Porque também Cristo não agradou a si mesmo; pelo contrário, como está escrito: "Os insultos dos que te insultavam caíram sobre mim."

[[v45-15-4]]

^<<v45-15-4,4>>^ Pois tudo o que no passado foi escrito, para o nosso ensino foi escrito, a fim de que, pela paciência e pela consolação das Escrituras, tenhamos esperança.

[[v45-15-5]]

^<<v45-15-5,5>>^ Ora, o Deus da paciência e da consolação lhes conceda o mesmo modo de pensar de uns para com os outros, segundo Cristo Jesus,

[[v45-15-6]]

^<<v45-15-6,6>>^ para que vocês, unânimes e a uma só voz, glorifiquem o Deus e Pai de nosso Senhor Jesus Cristo.

[[v45-15-7]]

^<<v45-15-7,7>>^ Portanto, acolham uns aos outros, como também Cristo acolheu vocês para a glória de Deus.

[[v45-15-8]]

^<<v45-15-8,8>>^ Pois digo que Cristo foi constituído ministro da circuncisão, em prol da verdade de Deus, para confirmar as promessas feitas aos nossos pais

[[v45-15-9]]

^<<v45-15-9,9>>^ e para que os gentios glorifiquem a Deus por causa da sua misericórdia, como está escrito: "Por isso, eu te glorificarei entre os gentios e cantarei louvores ao teu nome."

[[v45-15-10]]

^<<v45-15-10,10>>^ E também diz: "Alegrem-se, ó gentios, com o povo de Deus."

[[v45-15-11]]

^<<v45-15-11,11>>^ E ainda: "Louvem o Senhor, todos vocês, gentios, e todos os povos o louvem."

[[v45-15-12]]

^<<v45-15-12,12>>^ Também Isaías diz: "Virá a raiz de Jessé, aquele que se levanta para governar os gentios; nele os gentios esperarão."

[[v45-15-13]]

^<<v45-15-13,13>>^ E o Deus da esperança encha vocês de toda alegria e paz na fé que vocês têm, para que sejam ricos de esperança no poder do Espírito Santo.

[[v45-15-14]]

^<<v45-15-14,14>>^ E eu mesmo, meus irmãos, estou certo de que vocês estão cheios de bondade, têm todo o conhecimento e são aptos para admoestar uns aos outros.

[[v45-15-15]]

^<<v45-15-15,15>>^ Entretanto, eu lhes escrevi, em parte mais ousadamente, como para fazer com que vocês se lembrem disso outra vez, por causa da graça que me foi dada por Deus,

[[v45-15-16]]

^<<v45-15-16,16>>^ para que eu seja ministro de Cristo Jesus entre os gentios, no sagrado encargo de anunciar o evangelho de Deus, de modo que a oferta deles seja aceitável, uma vez santificada pelo Espírito Santo.

[[v45-15-17]]

^<<v45-15-17,17>>^ Tenho, pois, motivo de gloriar-me em Cristo Jesus nas coisas concernentes a Deus.

[[v45-15-18]]

^<<v45-15-18,18>>^ Porque não ousarei falar sobre coisa alguma, a não ser sobre aquelas que Cristo fez por meio de mim, para conduzir os gentios à obediência, por palavra e por obras,

[[v45-15-19]]

^<<v45-15-19,19>>^ por força de sinais e prodígios, pelo poder do Espírito de Deus. Assim, desde Jerusalém e arredores até o Ilírico, tenho divulgado o evangelho de Cristo,

[[v45-15-20]]

^<<v45-15-20,20>>^ esforçando-me, deste modo, por pregar o evangelho, não onde Cristo já foi anunciado, para não edificar sobre alicerce alheio.

[[v45-15-21]]

^<<v45-15-21,21>>^ Pelo contrário, como está escrito: "Aqueles que não tiveram notícia dele o verão, e os que nada tinham ouvido a respeito dele o entenderão."

[[v45-15-22]]

^<<v45-15-22,22>>^ Essa foi a razão por que também, muitas vezes, fui impedido de visitá-los.

[[v45-15-23]]

^<<v45-15-23,23>>^ Mas, agora, não tendo mais campo de atividade nestas regiões e desejando há muitos anos visitá-los,

[[v45-15-24]]

^<<v45-15-24,24>>^ penso em fazê-lo quando em viagem para a Espanha. Pois espero que, de passagem, eu possa vê-los e que vocês me encaminhem para lá, depois de haver primeiro desfrutado um pouco a companhia de vocês.

[[v45-15-25]]

^<<v45-15-25,25>>^ Mas agora estou de partida para Jerusalém, a serviço dos santos.

[[v45-15-26]]

^<<v45-15-26,26>>^ Porque a Macedônia e a Acaia resolveram levantar uma coleta em benefício dos pobres dentre os santos que vivem em Jerusalém.

[[v45-15-27]]

^<<v45-15-27,27>>^ Isto lhes pareceu bem, e de fato lhes são devedores. Porque, se os gentios têm sido participantes dos valores espirituais dos judeus, devem também servi-los com bens materiais.

[[v45-15-28]]

^<<v45-15-28,28>>^ Tendo, pois, concluído isto e havendo-lhes consignado este fruto, irei à Espanha, passando por aí.

[[v45-15-29]]

^<<v45-15-29,29>>^ E bem sei que, ao visitá-los, irei na plenitude da bênção de Cristo.

[[v45-15-30]]

^<<v45-15-30,30>>^ Irmãos, por nosso Senhor Jesus Cristo e também pelo amor do Espírito, peço que lutem juntamente comigo nas orações a Deus a meu favor,

[[v45-15-31]]

^<<v45-15-31,31>>^ para que eu me veja livre dos rebeldes que vivem na Judeia, e que este meu serviço em Jerusalém seja bem-aceito pelos santos.

[[v45-15-32]]

^<<v45-15-32,32>>^ Isto para que, pela vontade de Deus, eu chegue à presença de vocês com alegria e possa ter algum descanso na companhia de vocês.

[[v45-15-33]]

^<<v45-15-33,33>>^ E o Deus da paz esteja com todos vocês. Amém!

'''

xref:045-romanos/045-romanos-014.adoc#v45-14-0[&#60; Capítulo Anterior] | <<v45-15-0,Topo>> | xref:045-romanos/045-romanos-016.adoc#v45-16-0[Próximo Capítulo &#62;]