include::./index.adoc[]

[[v45-12-0]]
=== Romanos, 12
// naa ?, NAA - Nova Almeida Atualizada

[[v45-12-1]]

^<<v45-12-1,1>>^ Portanto, irmãos, pelas misericórdias de Deus, peço que ofereçam o seu corpo como sacrifício vivo, santo e agradável a Deus. Este é o culto racional de vocês.

[[v45-12-2]]

^<<v45-12-2,2>>^ E não vivam conforme os padrões deste mundo, mas deixem que Deus os transforme pela renovação da mente, para que possam experimentar qual é a boa, agradável e perfeita vontade de Deus.

[[v45-12-3]]

^<<v45-12-3,3>>^ Porque, pela graça que me foi dada, digo a cada um de vocês que não pense de si mesmo além do que convém. Pelo contrário, pense com moderação, segundo a medida da fé que Deus repartiu a cada um.

[[v45-12-4]]

^<<v45-12-4,4>>^ Porque assim como num só corpo temos muitos membros, mas nem todos os membros têm a mesma função,

[[v45-12-5]]

^<<v45-12-5,5>>^ assim também nós, embora sejamos muitos, somos um só corpo em Cristo e membros uns dos outros.

[[v45-12-6]]

^<<v45-12-6,6>>^ Temos, porém, diferentes dons segundo a graça que nos foi dada: se é profecia, seja segundo a proporção da fé;

[[v45-12-7]]

^<<v45-12-7,7>>^ se é ministério, dediquemo-nos ao ministério; o que ensina dedique-se ao ensino;

[[v45-12-8]]

^<<v45-12-8,8>>^ o que exorta faça-o com dedicação; o que contribui, com generosidade; o que preside, com zelo; quem exerce misericórdia, com alegria.

[[v45-12-9]]

^<<v45-12-9,9>>^ O amor seja sem hipocrisia. Odeiem o mal e apeguem-se ao bem.

[[v45-12-10]]

^<<v45-12-10,10>>^ Amem uns aos outros com amor fraternal. Quanto à honra, deem sempre preferência aos outros.

[[v45-12-11]]

^<<v45-12-11,11>>^ Quanto ao zelo, não sejam preguiçosos. Sejam fervorosos de espírito, servindo o Senhor.

[[v45-12-12]]

^<<v45-12-12,12>>^ Alegrem-se na esperança, sejam pacientes na tribulação e perseverem na oração.

[[v45-12-13]]

^<<v45-12-13,13>>^ Ajudem a suprir as necessidades dos santos. Pratiquem a hospitalidade.

[[v45-12-14]]

^<<v45-12-14,14>>^ Abençoem aqueles que perseguem vocês; abençoem e não amaldiçoem.

[[v45-12-15]]

^<<v45-12-15,15>>^ Alegrem-se com os que se alegram e chorem com os que choram.

[[v45-12-16]]

^<<v45-12-16,16>>^ Tenham o mesmo modo de pensar de uns para com os outros. Em vez de serem orgulhosos, sejam solidários com os humildes. Não sejam sábios aos seus próprios olhos.

[[v45-12-17]]

^<<v45-12-17,17>>^ Não paguem a ninguém mal por mal; procurem fazer o bem diante de todos.

[[v45-12-18]]

^<<v45-12-18,18>>^ Se possível, no que depender de vocês, vivam em paz com todas as pessoas.

[[v45-12-19]]

^<<v45-12-19,19>>^ Meus amados, não façam justiça com as próprias mãos, mas deem lugar à ira de Deus, pois está escrito: "A mim pertence a vingança; eu é que retribuirei, diz o Senhor."

[[v45-12-20]]

^<<v45-12-20,20>>^ Façam o contrário: "Se o seu inimigo tiver fome, dê-lhe de comer; se tiver sede, dê-lhe de beber; porque, fazendo isto, você amontoará brasas vivas sobre a cabeça dele."

[[v45-12-21]]

^<<v45-12-21,21>>^ Não se deixe vencer pelo mal, mas vença o mal com o bem.

'''

xref:045-romanos/045-romanos-011.adoc#v45-11-0[&#60; Capítulo Anterior] | <<v45-12-0,Topo>> | xref:045-romanos/045-romanos-013.adoc#v45-13-0[Próximo Capítulo &#62;]