include::./index.adoc[]

[[v45-13-0]]
=== Romanos, 13
// naa ?, NAA - Nova Almeida Atualizada

[[v45-13-1]]

^<<v45-13-1,1>>^ Que todos estejam sujeitos às autoridades superiores. Porque não há autoridade que não proceda de Deus, e as autoridades que existem foram por ele instituídas.

[[v45-13-2]]

^<<v45-13-2,2>>^ Assim, aquele que se opõe à autoridade resiste à ordenação de Deus, e os que resistem trarão sobre si mesmos condenação.

[[v45-13-3]]

^<<v45-13-3,3>>^ Porque os magistrados não são para temor, quando se faz o bem, e sim quando se faz o mal. Você quer viver sem medo da autoridade? Faça o bem e você terá louvor dela,

[[v45-13-4]]

^<<v45-13-4,4>>^ pois a autoridade é ministro de Deus para o seu bem. Mas, se você fizer o mal, então tenha medo, porque não é sem motivo que a autoridade traz a espada; pois é ministro de Deus, vingador, para castigar quem pratica o mal.

[[v45-13-5]]

^<<v45-13-5,5>>^ Portanto, é necessário que vocês se sujeitem à autoridade, não somente por causa do temor da punição, mas também por dever de consciência.

[[v45-13-6]]

^<<v45-13-6,6>>^ É por isso também que vocês pagam impostos, porque as autoridades são ministros de Deus, atendendo constantemente a este serviço.

[[v45-13-7]]

^<<v45-13-7,7>>^ Paguem a todos o que lhes é devido: a quem tributo, tributo; a quem imposto, imposto; a quem respeito, respeito; a quem honra, honra.

[[v45-13-8]]

^<<v45-13-8,8>>^ Não fiquem devendo nada a ninguém, exceto o amor de uns para com os outros. Pois quem ama o próximo cumpre a lei.

[[v45-13-9]]

^<<v45-13-9,9>>^ Pois estes mandamentos: "Não cometa adultério", "não mate", "não furte", "não cobice", e qualquer outro mandamento que houver, todos se resumem nesta palavra: "Ame o seu próximo como você ama a si mesmo."

[[v45-13-10]]

^<<v45-13-10,10>>^ O amor não pratica o mal contra o próximo. Portanto, o cumprimento da lei é o amor.

[[v45-13-11]]

^<<v45-13-11,11>>^ E digo isto a vocês que conhecem o tempo: já é hora de despertarem do sono, porque a nossa salvação está agora mais perto do que quando no princípio cremos.

[[v45-13-12]]

^<<v45-13-12,12>>^ Vai alta a noite, e o dia vem chegando. Deixemos, pois, as obras das trevas e revistamo-nos das armas da luz.

[[v45-13-13]]

^<<v45-13-13,13>>^ Vivamos dignamente, como em pleno dia, não em orgias e bebedeiras, não em imoralidades e libertinagem, não em discórdias e ciúmes.

[[v45-13-14]]

^<<v45-13-14,14>>^ Mas revistam-se do Senhor Jesus Cristo e não façam nada que venha a satisfazer os desejos da carne.

'''

xref:045-romanos/045-romanos-012.adoc#v45-12-0[&#60; Capítulo Anterior] | <<v45-13-0,Topo>> | xref:045-romanos/045-romanos-014.adoc#v45-14-0[Próximo Capítulo &#62;]