include::./index.adoc[]

[[v52-3-0]]
=== 1 Tessalonicenses, 3
// naa ?, NAA - Nova Almeida Atualizada

[[v52-3-1]]

^<<v52-3-1,1>>^ Por isso, não podendo esperar mais, achamos por bem ficar sozinhos em Atenas

[[v52-3-2]]

^<<v52-3-2,2>>^ e enviar o nosso irmão Timóteo, ministro de Deus no evangelho de Cristo, para fortalecer e animá-los na fé,

[[v52-3-3]]

^<<v52-3-3,3>>^ a fim de que ninguém se inquiete com essas tribulações. Porque vocês mesmos sabem que fomos designados para isto.

[[v52-3-4]]

^<<v52-3-4,4>>^ Pois, quando ainda estávamos com vocês, predissemos que íamos passar por aflições, o que de fato aconteceu e é do conhecimento de vocês.

[[v52-3-5]]

^<<v52-3-5,5>>^ Foi por isso que, já não me sendo possível continuar esperando, mandei perguntar a respeito da fé que vocês têm, temendo que vocês fossem provados pelo tentador e o nosso trabalho se tornasse inútil.

[[v52-3-6]]

^<<v52-3-6,6>>^ Agora, porém, com o regresso de Timóteo, vindo do meio de vocês, trazendo-nos boas notícias a respeito da fé e do amor que vocês têm, e, ainda, de que sempre guardam grata lembrança de nós, desejando muito nos ver, como, aliás, também nós temos vontade de ver vocês,

[[v52-3-7]]

^<<v52-3-7,7>>^ sim, irmãos, por isso, ficamos animados a respeito de vocês, pela fé que vocês têm, apesar de toda a nossa necessidade e tribulação.

[[v52-3-8]]

^<<v52-3-8,8>>^ Porque, agora, vivemos, se vocês estão firmes no Senhor.

[[v52-3-9]]

^<<v52-3-9,9>>^ Pois que ação de graças podemos render a Deus no que se refere a vocês, por toda a alegria com que nos regozijamos por causa de vocês, diante do nosso Deus?

[[v52-3-10]]

^<<v52-3-10,10>>^ Oramos noite e dia, com máximo empenho, para que possamos ir vê-los pessoalmente e suprir o que ainda falta à fé que vocês têm.

[[v52-3-11]]

^<<v52-3-11,11>>^ Que o próprio Deus, o nosso Pai, e Jesus, o nosso Senhor, preparem o nosso caminho para podermos ir visitar vocês.

[[v52-3-12]]

^<<v52-3-12,12>>^ E o Senhor faça com que cresça e aumente o amor de uns para com os outros e para com todos, como também o nosso amor por vocês,

[[v52-3-13]]

^<<v52-3-13,13>>^ a fim de que o coração de vocês seja fortalecido em santidade, isento de culpa, na presença de nosso Deus e Pai, na vinda de nosso Senhor Jesus, com todos os seus santos.

'''

xref:052-1-tessalonicenses/052-1-tessalonicenses-002.adoc#v52-2-0[&#60; Capítulo Anterior] | <<v52-3-0,Topo>> | xref:052-1-tessalonicenses/052-1-tessalonicenses-004.adoc#v52-4-0[Próximo Capítulo &#62;]