include::./index.adoc[]

[[v52-1-0]]
=== 1 Tessalonicenses, 1
// naa ?, NAA - Nova Almeida Atualizada

[[v52-1-1]]

^<<v52-1-1,1>>^ Paulo, Silvano e Timóteo, à igreja dos tessalonicenses, em Deus Pai e no Senhor Jesus Cristo. Que a graça e a paz estejam com vocês.

[[v52-1-2]]

^<<v52-1-2,2>>^ Sempre damos graças a Deus por todos vocês, fazendo menção de vocês em nossas orações e, sem cessar,

[[v52-1-3]]

^<<v52-1-3,3>>^ lembrando-nos, diante do nosso Deus e Pai, da operosidade da fé que vocês têm, da dedicação do amor de vocês e da firmeza da esperança que têm em nosso Senhor Jesus Cristo.

[[v52-1-4]]

^<<v52-1-4,4>>^ Sabemos, irmãos amados por Deus, que ele os escolheu,

[[v52-1-5]]

^<<v52-1-5,5>>^ porque o nosso evangelho não chegou a vocês somente em palavra, mas também em poder, no Espírito Santo e em plena convicção. E vocês sabem muito bem qual foi o nosso modo de agir entre vocês, para o próprio bem de vocês.

[[v52-1-6]]

^<<v52-1-6,6>>^ E vocês se tornaram nossos imitadores e do Senhor, recebendo a palavra com a alegria que vem do Espírito Santo, apesar dos muitos sofrimentos.

[[v52-1-7]]

^<<v52-1-7,7>>^ Assim, vocês se tornaram modelo para todos os crentes na Macedônia e na Acaia.

[[v52-1-8]]

^<<v52-1-8,8>>^ Porque a partir de vocês a palavra do Senhor repercutiu não só na Macedônia e na Acaia, mas a fé que vocês têm em Deus repercutiu em todos os lugares, a ponto de não termos necessidade de dizer mais nada a respeito disso.

[[v52-1-9]]

^<<v52-1-9,9>>^ Porque, no que se refere a nós, as pessoas desses lugares falam sobre como foi a nossa chegada no meio de vocês e como, deixando os ídolos, vocês se converteram a Deus, para servir o Deus vivo e verdadeiro

[[v52-1-10]]

^<<v52-1-10,10>>^ e para aguardar dos céus o seu Filho, a quem ele ressuscitou dentre os mortos, a saber, Jesus, que nos livra da ira vindoura.

'''

xref:051-colossenses/051-colossenses-004.adoc#v51-4-0[&#60; Capítulo Anterior] | <<v52-1-0,Topo>> | xref:052-1-tessalonicenses/052-1-tessalonicenses-002.adoc#v52-2-0[Próximo Capítulo &#62;]