include::./index.adoc[]

[[v52-5-0]]
=== 1 Tessalonicenses, 5
// naa ?, NAA - Nova Almeida Atualizada

[[v52-5-1]]

^<<v52-5-1,1>>^ Irmãos, no que se refere aos tempos e às épocas, não há necessidade de que eu lhes escreva.

[[v52-5-2]]

^<<v52-5-2,2>>^ Porque vocês sabem perfeitamente que o Dia do Senhor vem como ladrão à noite.

[[v52-5-3]]

^<<v52-5-3,3>>^ Quando andarem dizendo: "Paz e segurança", eis que lhes sobrevirá repentina destruição, como vêm as dores de parto à mulher que está para dar à luz; e de modo nenhum escaparão.

[[v52-5-4]]

^<<v52-5-4,4>>^ Mas vocês, irmãos, não estão em trevas, para que esse Dia os apanhe de surpresa como ladrão.

[[v52-5-5]]

^<<v52-5-5,5>>^ Porque vocês todos são filhos da luz e filhos do dia; nós não somos da noite, nem das trevas.

[[v52-5-6]]

^<<v52-5-6,6>>^ Assim, pois, não durmamos como os demais; pelo contrário, vigiemos e sejamos sóbrios.

[[v52-5-7]]

^<<v52-5-7,7>>^ Ora, os que dormem é de noite que dormem, e os que se embriagam é de noite que se embriagam.

[[v52-5-8]]

^<<v52-5-8,8>>^ Nós, porém, que somos do dia, sejamos sóbrios, revestindo-nos da couraça da fé e do amor e tomando como capacete a esperança da salvação.

[[v52-5-9]]

^<<v52-5-9,9>>^ Porque Deus não nos destinou para a ira, mas para alcançar a salvação mediante nosso Senhor Jesus Cristo,

[[v52-5-10]]

^<<v52-5-10,10>>^ que morreu por nós para que, quer vigiemos, quer durmamos, vivamos em união com ele.

[[v52-5-11]]

^<<v52-5-11,11>>^ Portanto, consolem uns aos outros e edifiquem-se mutuamente, como vocês têm feito até agora.

[[v52-5-12]]

^<<v52-5-12,12>>^ Irmãos, pedimos que vocês tenham em grande apreço os que trabalham entre vocês, que os presidem no Senhor e os admoestam.

[[v52-5-13]]

^<<v52-5-13,13>>^ Tenham essas pessoas em máxima consideração, com amor, por causa do trabalho que realizam. Vivam em paz uns com os outros.

[[v52-5-14]]

^<<v52-5-14,14>>^ Também exortamos vocês, irmãos, a que admoestem os que vivem de forma desordenada, consolem os desanimados, amparem os fracos e sejam pacientes com todos.

[[v52-5-15]]

^<<v52-5-15,15>>^ Tenham cuidado para que ninguém retribua aos outros mal por mal; pelo contrário, procurem sempre o bem uns dos outros e o bem de todos.

[[v52-5-16]]

^<<v52-5-16,16>>^ Estejam sempre alegres.

[[v52-5-17]]

^<<v52-5-17,17>>^ Orem sem cessar.

[[v52-5-18]]

^<<v52-5-18,18>>^ Em tudo, deem graças, porque esta é a vontade de Deus para vocês em Cristo Jesus.

[[v52-5-19]]

^<<v52-5-19,19>>^ Não apaguem o Espírito.

[[v52-5-20]]

^<<v52-5-20,20>>^ Não desprezem as profecias.

[[v52-5-21]]

^<<v52-5-21,21>>^ Examinem todas as coisas, retenham o que é bom.

[[v52-5-22]]

^<<v52-5-22,22>>^ Abstenham-se de toda forma de mal.

[[v52-5-23]]

^<<v52-5-23,23>>^ O mesmo Deus da paz os santifique em tudo. E que o espírito, a alma e o corpo de vocês sejam conservados íntegros e irrepreensíveis na vinda de nosso Senhor Jesus Cristo.

[[v52-5-24]]

^<<v52-5-24,24>>^ Fiel é aquele que os chama, o qual também o fará.

[[v52-5-25]]

^<<v52-5-25,25>>^ Irmãos, orem também por nós.

[[v52-5-26]]

^<<v52-5-26,26>>^ Saúdem todos os irmãos com um beijo santo.

[[v52-5-27]]

^<<v52-5-27,27>>^ Peço, com insistência, em nome do Senhor, que esta carta seja lida para todos os irmãos.

[[v52-5-28]]

^<<v52-5-28,28>>^ A graça de nosso Senhor Jesus Cristo esteja com vocês!

'''

xref:052-1-tessalonicenses/052-1-tessalonicenses-004.adoc#v52-4-0[&#60; Capítulo Anterior] | <<v52-5-0,Topo>> | xref:053-2-tessalonicenses/053-2-tessalonicenses-001.adoc#v53-1-0[Próximo Capítulo &#62;]