include::./index.adoc[]

[[v52-2-0]]
=== 1 Tessalonicenses, 2
// naa ?, NAA - Nova Almeida Atualizada

[[v52-2-1]]

^<<v52-2-1,1>>^ Irmãos, vocês sabem muito bem que a nossa chegada no meio de vocês não foi em vão.

[[v52-2-2]]

^<<v52-2-2,2>>^ Pelo contrário, apesar de maltratados e insultados em Filipos, como vocês sabem, tivemos ousada confiança em nosso Deus para anunciar a vocês o evangelho de Deus, em meio a muita luta.

[[v52-2-3]]

^<<v52-2-3,3>>^ Pois a nossa exortação não procede de erro ou de intenções impuras, nem se baseia no engano.

[[v52-2-4]]

^<<v52-2-4,4>>^ Pelo contrário, visto que fomos aprovados por Deus, a ponto de ele nos confiar o evangelho, assim falamos, não para agradar as pessoas, e sim para agradar a Deus, que prova o nosso coração.

[[v52-2-5]]

^<<v52-2-5,5>>^ A verdade, como vocês sabem, é que nunca usamos de linguagem de bajulação, nem de pretextos gananciosos. Deus é testemunha disso.

[[v52-2-6]]

^<<v52-2-6,6>>^ Também jamais andamos buscando elogios das pessoas, nem de vocês, nem de outros.

[[v52-2-7]]

^<<v52-2-7,7>>^ Embora, como apóstolos de Cristo, pudéssemos ter feito exigências, preferimos ser carinhosos quando estivemos aí com vocês, assim como uma mãe que acaricia os próprios filhos.

[[v52-2-8]]

^<<v52-2-8,8>>^ Assim, com muito afeto, estávamos prontos a lhes oferecer não somente o evangelho de Deus, mas até mesmo a própria vida, porque vocês se tornaram muito amados por nós.

[[v52-2-9]]

^<<v52-2-9,9>>^ Pois vocês com certeza se lembram, irmãos, do nosso esforço e fadiga, e de como, trabalhando de noite e de dia para não vivermos à custa de nenhum de vocês, proclamamos a vocês o evangelho de Deus.

[[v52-2-10]]

^<<v52-2-10,10>>^ Vocês e Deus são testemunhas de como nos portamos de maneira piedosa, justa e irrepreensível em relação a vocês, os que creem.

[[v52-2-11]]

^<<v52-2-11,11>>^ E vocês sabem muito bem que tratamos cada um de vocês como um pai trata os seus filhos,

[[v52-2-12]]

^<<v52-2-12,12>>^ exortando, consolando e admoestando vocês a viverem de uma maneira digna de Deus, que os chama para o seu Reino e a sua glória.

[[v52-2-13]]

^<<v52-2-13,13>>^ Temos mais uma razão para, incessantemente, dar graças a Deus: é que, ao receberem a palavra que de nós ouviram, que é de Deus, vocês a acolheram não como palavra humana, e sim como, em verdade é, a palavra de Deus, a qual está atuando eficazmente em vocês, os que creem.

[[v52-2-14]]

^<<v52-2-14,14>>^ Tanto é assim, irmãos, que vocês se tornaram imitadores das igrejas de Deus que se encontram na Judeia e que estão em Cristo Jesus; porque também vocês sofreram, da parte de seus patrícios, as mesmas coisas que eles, por sua vez, sofreram dos judeus,

[[v52-2-15]]

^<<v52-2-15,15>>^ os quais não somente mataram o Senhor Jesus e os profetas, como também nos perseguiram, não agradam a Deus e são adversários de todos,

[[v52-2-16]]

^<<v52-2-16,16>>^ a ponto de nos impedirem de falar aos gentios para que estes sejam salvos, a fim de encherem sempre a medida de seus pecados. A ira, porém, caiu sobre eles, definitivamente.

[[v52-2-17]]

^<<v52-2-17,17>>^ E nós, irmãos, estando separados de vocês por breve tempo, ficando longe dos olhos, mas perto do coração, com muito mais empenho e com grande desejo procuramos ir vê-los pessoalmente.

[[v52-2-18]]

^<<v52-2-18,18>>^ Por isso, quisemos ir até vocês — pelo menos eu, Paulo, por mais de uma vez —, porém Satanás nos barrou o caminho.

[[v52-2-19]]

^<<v52-2-19,19>>^ Pois quem é a nossa esperança, ou alegria, ou a coroa em que nos gloriamos na presença de nosso Senhor Jesus em sua vinda? Não é verdade que são vocês?

[[v52-2-20]]

^<<v52-2-20,20>>^ Sim, vocês são realmente a nossa glória e a nossa alegria!

'''

xref:052-1-tessalonicenses/052-1-tessalonicenses-001.adoc#v52-1-0[&#60; Capítulo Anterior] | <<v52-2-0,Topo>> | xref:052-1-tessalonicenses/052-1-tessalonicenses-003.adoc#v52-3-0[Próximo Capítulo &#62;]