include::./index.adoc[]

[[v52-4-0]]
=== 1 Tessalonicenses, 4
// naa ?, NAA - Nova Almeida Atualizada

[[v52-4-1]]

^<<v52-4-1,1>>^ Finalmente, irmãos, pedimos a vocês e os exortamos no Senhor Jesus que, assim como aprenderam de nós a maneira como devem viver e agradar a Deus, e efetivamente o estão fazendo, vocês continuem progredindo cada vez mais.

[[v52-4-2]]

^<<v52-4-2,2>>^ Porque vocês sabem quantas instruções demos a vocês da parte do Senhor Jesus.

[[v52-4-3]]

^<<v52-4-3,3>>^ Pois a vontade de Deus é a santificação de vocês: que se abstenham da imoralidade sexual;

[[v52-4-4]]

^<<v52-4-4,4>>^ que cada um de vocês saiba controlar o seu próprio corpo em santificação e honra,

[[v52-4-5]]

^<<v52-4-5,5>>^ não com desejos imorais, como os gentios que não conhecem a Deus.

[[v52-4-6]]

^<<v52-4-6,6>>^ E que, nesta matéria, ninguém ofenda nem defraude o seu irmão. Porque, contra todas estas coisas, como antes já avisamos e testificamos, o Senhor é o vingador.

[[v52-4-7]]

^<<v52-4-7,7>>^ Pois Deus não nos chamou para a impureza, e sim para a santificação.

[[v52-4-8]]

^<<v52-4-8,8>>^ Portanto, quem rejeita estas coisas não rejeita uma pessoa, mas rejeita Deus, que também dá o seu Espírito Santo a vocês.

[[v52-4-9]]

^<<v52-4-9,9>>^ Quanto ao amor fraternal, não há necessidade de que eu lhes escreva, porque vocês mesmos foram instruídos por Deus a amar uns aos outros.

[[v52-4-10]]

^<<v52-4-10,10>>^ E, na verdade, vocês já estão fazendo isso em relação a todos os irmãos em toda a Macedônia. Porém, irmãos, exortamos vocês a que progridam cada vez mais

[[v52-4-11]]

^<<v52-4-11,11>>^ e se empenhem por viver tranquilamente, cuidar do que é de vocês e trabalhar com as próprias mãos, como ordenamos,

[[v52-4-12]]

^<<v52-4-12,12>>^ para que vocês vivam com dignidade à vista dos de fora, e não venham a precisar de nada.

[[v52-4-13]]

^<<v52-4-13,13>>^ Irmãos, não queremos que vocês ignorem a verdade a respeito dos que dormem, para que não fiquem tristes como os demais, que não têm esperança.

[[v52-4-14]]

^<<v52-4-14,14>>^ Pois, se cremos que Jesus morreu e ressuscitou, assim também Deus, mediante Jesus, trará, na companhia dele, os que dormem.

[[v52-4-15]]

^<<v52-4-15,15>>^ E, pela palavra do Senhor, ainda lhes declaramos o seguinte: nós, os vivos, os que ficarmos até a vinda do Senhor, de modo nenhum precederemos os que dormem.

[[v52-4-16]]

^<<v52-4-16,16>>^ Porque o Senhor mesmo, dada a sua palavra de ordem, ouvida a voz do arcanjo e ressoada a trombeta de Deus, descerá dos céus, e os mortos em Cristo ressuscitarão primeiro;

[[v52-4-17]]

^<<v52-4-17,17>>^ depois, nós, os vivos, os que ficarmos, seremos arrebatados juntamente com eles, entre nuvens, para o encontro com o Senhor nos ares, e, assim, estaremos para sempre com o Senhor.

[[v52-4-18]]

^<<v52-4-18,18>>^ Portanto, consolem uns aos outros com estas palavras.

'''

xref:052-1-tessalonicenses/052-1-tessalonicenses-003.adoc#v52-3-0[&#60; Capítulo Anterior] | <<v52-4-0,Topo>> | xref:052-1-tessalonicenses/052-1-tessalonicenses-005.adoc#v52-5-0[Próximo Capítulo &#62;]