include::./index.adoc[]

[[v18-13-0]]
=== Jó, 13
// naa ?, NAA - Nova Almeida Atualizada

[[v18-13-1]]

^<<v18-13-1,1>>^ "Eis que os meus olhos viram tudo isso, e os meus ouvidos o ouviram e entenderam.

[[v18-13-2]]

^<<v18-13-2,2>>^ O que vocês sabem eu também sei; em nada sou inferior a vocês.

[[v18-13-3]]

^<<v18-13-3,3>>^ Mas falarei ao Todo-Poderoso e quero defender-me diante de Deus.

[[v18-13-4]]

^<<v18-13-4,4>>^ Vocês, porém, cobrem a verdade com mentiras; todos vocês são médicos que não valem nada.

[[v18-13-5]]

^<<v18-13-5,5>>^ Quem dera vocês ficassem completamente calados! Vocês poderiam passar por sábios!"

[[v18-13-6]]

^<<v18-13-6,6>>^ "Ouçam agora a minha defesa e prestem atenção aos argumentos dos meus lábios.

[[v18-13-7]]

^<<v18-13-7,7>>^ Será que vão dizer perversidades em favor de Deus? Vão dizer mentiras a favor dele?

[[v18-13-8]]

^<<v18-13-8,8>>^ Serão parciais por ele? Argumentarão a favor de Deus?

[[v18-13-9]]

^<<v18-13-9,9>>^ Por acaso, seria bom se ele os examinasse? Ou vocês zombariam dele, como zombam das pessoas?

[[v18-13-10]]

^<<v18-13-10,10>>^ Ele certamente os repreenderá, se em oculto forem parciais.

[[v18-13-11]]

^<<v18-13-11,11>>^ A grandeza dele não os amedrontaria? E o terror dele não cairia sobre vocês?

[[v18-13-12]]

^<<v18-13-12,12>>^ As máximas de vocês são provérbios de cinza; as defesas de vocês são muralhas de barro."

[[v18-13-13]]

^<<v18-13-13,13>>^ "Calem-se diante de mim, e eu falarei; que venha sobre mim o que vier.

[[v18-13-14]]

^<<v18-13-14,14>>^ Tomarei a minha carne nos meus dentes e porei a minha vida nas minhas mãos.

[[v18-13-15]]

^<<v18-13-15,15>>^ Eis que ele me matará, já não tenho esperança; mesmo assim defenderei a minha conduta diante dele.

[[v18-13-16]]

^<<v18-13-16,16>>^ Também isto será a minha salvação: o fato de um ímpio não comparecer diante dele.

[[v18-13-17]]

^<<v18-13-17,17>>^ Ouçam com atenção as minhas palavras e escutem a minha exposição.

[[v18-13-18]]

^<<v18-13-18,18>>^ Tenho já bem-encaminhada minha causa e estou certo de que serei justificado."

[[v18-13-19]]

^<<v18-13-19,19>>^ "Quem há que possa entrar em litígio comigo? Se houver, eu fico calado e morro.

[[v18-13-20]]

^<<v18-13-20,20>>^ Concede-me somente duas coisas, ó Deus, e assim não me esconderei de ti:

[[v18-13-21]]

^<<v18-13-21,21>>^ tira a tua mão de cima de mim, e não me amedronte o teu terror."

[[v18-13-22]]

^<<v18-13-22,22>>^ "Interpela-me, e eu responderei; ou deixa-me falar, e tu responderás.

[[v18-13-23]]

^<<v18-13-23,23>>^ Quantas culpas e pecados tenho eu? Mostra-me a minha transgressão e o meu pecado."

[[v18-13-24]]

^<<v18-13-24,24>>^ "Por que escondes o teu rosto e me consideras teu inimigo?

[[v18-13-25]]

^<<v18-13-25,25>>^ Queres aterrorizar uma folha levada pelo vento? E perseguirás a palha seca?"

[[v18-13-26]]

^<<v18-13-26,26>>^ "Pois decretas contra mim coisas amargas e me atribuis as culpas da minha mocidade.

[[v18-13-27]]

^<<v18-13-27,27>>^ Também prendes os meus pés com correntes, observas todos os meus caminhos e traças limites à planta dos meus pés,

[[v18-13-28]]

^<<v18-13-28,28>>^ apesar de eu ser como uma coisa podre que se consome e como a roupa que é comida pela traça."

'''

xref:018-jo/018-jo-012.adoc#v18-12-0[&#60; Capítulo Anterior] | <<v18-13-0,Topo>> | xref:018-jo/018-jo-014.adoc#v18-14-0[Próximo Capítulo &#62;]