include::./index.adoc[]

[[v18-11-0]]
=== Jó, 11
// naa ?, NAA - Nova Almeida Atualizada

[[v18-11-1]]

^<<v18-11-1,1>>^ Então Zofar, o naamatita, tomou a palavra e disse:

[[v18-11-2]]

^<<v18-11-2,2>>^ "Será que todas essas palavras ficarão sem resposta? Por acaso, tem razão o falador?

[[v18-11-3]]

^<<v18-11-3,3>>^ Você pensa, Jó, que o seu palavreado fará calar os homens? E, quando você zomba, pensa que não haverá ninguém que o envergonhe?

[[v18-11-4]]

^<<v18-11-4,4>>^ Pois você diz: ‘A minha doutrina é pura, e sou limpo aos olhos de Deus.’

[[v18-11-5]]

^<<v18-11-5,5>>^ Mas quem dera que Deus falasse e abrisse os seus lábios contra você,

[[v18-11-6]]

^<<v18-11-6,6>>^ e lhe revelasse os segredos da sabedoria, pois a verdadeira sabedoria é multiforme! Saiba, portanto, que Deus permite que seja esquecida parte da sua iniquidade."

[[v18-11-7]]

^<<v18-11-7,7>>^ "Será que você pode desvendar os mistérios de Deus ou descobrir a perfeição do Todo-Poderoso?

[[v18-11-8]]

^<<v18-11-8,8>>^ A sabedoria de Deus é mais elevada do que os céus; o que você poderá fazer? Ela é mais profunda do que o abismo; o que você poderá saber?

[[v18-11-9]]

^<<v18-11-9,9>>^ A sua medida é mais longa do que a terra e mais larga do que o mar.

[[v18-11-10]]

^<<v18-11-10,10>>^ Se ele passa, prende alguém e chama a juízo, quem o poderá impedir?

[[v18-11-11]]

^<<v18-11-11,11>>^ Deus conhece os homens falsos e, sem esforço, vê a iniquidade.

[[v18-11-12]]

^<<v18-11-12,12>>^ Mas os tolos se tornarão sábios quando a cria de uma jumenta selvagem nascer homem."

[[v18-11-13]]

^<<v18-11-13,13>>^ "Se você dispuser o coração e estender as mãos para Deus;

[[v18-11-14]]

^<<v18-11-14,14>>^ se lançar para longe a iniquidade de suas mãos e não permitir que a injustiça habite na sua tenda,

[[v18-11-15]]

^<<v18-11-15,15>>^ então você levantará o seu rosto sem mácula, estará seguro e não temerá.

[[v18-11-16]]

^<<v18-11-16,16>>^ Pois você esquecerá os seus sofrimentos e só lembrará deles como de águas passadas.

[[v18-11-17]]

^<<v18-11-17,17>>^ A sua vida será mais clara que o meio-dia; ainda que haja trevas, serão como a manhã.

[[v18-11-18]]

^<<v18-11-18,18>>^ Você se sentirá seguro, porque haverá esperança; olhará ao redor e dormirá tranquilo.

[[v18-11-19]]

^<<v18-11-19,19>>^ Você se deitará, e ninguém irá atemorizá-lo; e muitos procurarão obter o seu favor.

[[v18-11-20]]

^<<v18-11-20,20>>^ Mas os olhos dos ímpios desfalecerão, sem que encontrem refúgio; a única esperança deles será morrer."

'''

xref:018-jo/018-jo-010.adoc#v18-10-0[&#60; Capítulo Anterior] | <<v18-11-0,Topo>> | xref:018-jo/018-jo-012.adoc#v18-12-0[Próximo Capítulo &#62;]