include::./index.adoc[]

[[v18-22-0]]
=== Jó, 22
// naa ?, NAA - Nova Almeida Atualizada

[[v18-22-1]]

^<<v18-22-1,1>>^ Então Elifaz, o temanita, tomou a palavra e disse:

[[v18-22-2]]

^<<v18-22-2,2>>^ "Pode o homem ser de algum proveito para Deus? Não! O sábio só é útil a si mesmo.

[[v18-22-3]]

^<<v18-22-3,3>>^ Será que o Todo-Poderoso tem interesse em que você seja justo? Será que ele tem algum lucro, se você for perfeito em todos os seus caminhos?

[[v18-22-4]]

^<<v18-22-4,4>>^ Ou será que é por causa do seu temor a Deus que ele o repreende ou entra em juízo contra você?

[[v18-22-5]]

^<<v18-22-5,5>>^ Não é fato que é grande a sua maldade, e incalculável a sua iniquidade?

[[v18-22-6]]

^<<v18-22-6,6>>^ Porque sem motivo você exigiu penhores do seu irmão e despojou das roupas os que estavam seminus.

[[v18-22-7]]

^<<v18-22-7,7>>^ Você não deu água ao cansado e ao faminto você se recusou a dar pão.

[[v18-22-8]]

^<<v18-22-8,8>>^ A terra pertencia ao homem poderoso, e só os privilegiados moravam nela.

[[v18-22-9]]

^<<v18-22-9,9>>^ Você despediu as viúvas de mãos vazias, e os braços dos órfãos foram quebrados.

[[v18-22-10]]

^<<v18-22-10,10>>^ Por isso, você está cercado de laços, e repentino pavor toma conta de você.

[[v18-22-11]]

^<<v18-22-11,11>>^ Está submerso por trevas, que impedem você de enxergar, e pelas águas transbordantes que o cobrem."

[[v18-22-12]]

^<<v18-22-12,12>>^ "Não está Deus nas alturas do céu? Olhe para as estrelas mais altas! Que altura!

[[v18-22-13]]

^<<v18-22-13,13>>^ E você diz: ‘O que é que Deus sabe? Será que ele pode julgar através de densa escuridão?

[[v18-22-14]]

^<<v18-22-14,14>>^ Grossas nuvens o encobrem, de modo que não pode ver; ele só passeia pela abóbada do céu.’"

[[v18-22-15]]

^<<v18-22-15,15>>^ "Você quer seguir a rota antiga, que os iníquos percorreram?

[[v18-22-16]]

^<<v18-22-16,16>>^ Estes foram levados antes do tempo; uma torrente arrastou os seus alicerces.

[[v18-22-17]]

^<<v18-22-17,17>>^ Diziam a Deus: ‘Deixa-nos em paz.’ E perguntavam: ‘O que pode fazer-nos o Todo-Poderoso?’

[[v18-22-18]]

^<<v18-22-18,18>>^ Contudo, foi Deus quem encheu de bens as casas deles. Longe de mim o conselho dos ímpios!

[[v18-22-19]]

^<<v18-22-19,19>>^ Os justos veem a destruição deles e se alegram; o inocente zomba deles,

[[v18-22-20]]

^<<v18-22-20,20>>^ dizendo: ‘Na verdade, os nossos adversários foram destruídos, e o fogo consumiu o resto deles.’"

[[v18-22-21]]

^<<v18-22-21,21>>^ "Portanto, reconcilie-se com Deus, viva em paz com ele e assim lhe sobrevirá o bem.

[[v18-22-22]]

^<<v18-22-22,22>>^ Aceite a instrução que vem da boca de Deus e guarde as palavras dele em seu coração.

[[v18-22-23]]

^<<v18-22-23,23>>^ Se você se converter ao Todo-Poderoso, será restabelecido; se afastar da sua tenda a injustiça

[[v18-22-24]]

^<<v18-22-24,24>>^ e lançar ao pó o seu ouro — o ouro de Ofir entre pedras dos ribeiros —,

[[v18-22-25]]

^<<v18-22-25,25>>^ então o Todo-Poderoso será o seu ouro e a sua prata escolhida.

[[v18-22-26]]

^<<v18-22-26,26>>^ Então você encontrará prazer no Todo-Poderoso e levantará o seu rosto para Deus.

[[v18-22-27]]

^<<v18-22-27,27>>^ Você fará oração, e Deus o ouvirá; e você pagará os seus votos.

[[v18-22-28]]

^<<v18-22-28,28>>^ Se você projetar alguma coisa, ela lhe será bem-sucedida, e a luz brilhará em seus caminhos.

[[v18-22-29]]

^<<v18-22-29,29>>^ Se forem humilhados, você dirá: ‘Para cima!’ E Deus salvará o humilde.

[[v18-22-30]]

^<<v18-22-30,30>>^ Livrará até o que não é inocente; sim, será libertado, porque você tem as mãos limpas."

'''

xref:018-jo/018-jo-021.adoc#v18-21-0[&#60; Capítulo Anterior] | <<v18-22-0,Topo>> | xref:018-jo/018-jo-023.adoc#v18-23-0[Próximo Capítulo &#62;]