include::./index.adoc[]

[[v18-32-0]]
=== Jó, 32
// naa ?, NAA - Nova Almeida Atualizada

[[v18-32-1]]

^<<v18-32-1,1>>^ Aqueles três homens pararam de responder a Jó, porque ele se considerava justo.

[[v18-32-2]]

^<<v18-32-2,2>>^ Então se acendeu a ira de Eliú, filho de Baraquel, o buzita, da família de Rão. Ele ficou indignado contra Jó, porque este pretendia ser mais justo do que Deus.

[[v18-32-3]]

^<<v18-32-3,3>>^ Eliú também ficou irado com os três amigos de Jó, porque, mesmo não tendo o que responder, eles o condenavam.

[[v18-32-4]]

^<<v18-32-4,4>>^ Eliú, porém, havia esperado para falar a Jó, pois os outros eram mais velhos do que ele.

[[v18-32-5]]

^<<v18-32-5,5>>^ Quando Eliú viu que aqueles três homens já não tinham o que responder, ficou irado.

[[v18-32-6]]

^<<v18-32-6,6>>^ Então Eliú, filho de Baraquel, o buzita, tomou a palavra e disse: "Eu sou de menos idade, e vocês são idosos. Por isso, tive receio e fiquei com medo de dar a minha opinião.

[[v18-32-7]]

^<<v18-32-7,7>>^ Pensei assim: ‘Que falem os que têm mais idade, e que a multidão dos anos ensine a sabedoria.’

[[v18-32-8]]

^<<v18-32-8,8>>^ Na verdade, há um espírito no homem, e o sopro do Todo-Poderoso lhe dá entendimento.

[[v18-32-9]]

^<<v18-32-9,9>>^ Os de mais idade não são os sábios, nem são os velhos os que entendem o que é reto.

[[v18-32-10]]

^<<v18-32-10,10>>^ Por isso digo: Escutem o que vou dizer, e também eu darei a minha opinião."

[[v18-32-11]]

^<<v18-32-11,11>>^ "Eis que esperei que vocês falassem e dei ouvidos às suas considerações, enquanto, quem sabe, buscavam o que dizer.

[[v18-32-12]]

^<<v18-32-12,12>>^ Dei atenção ao que diziam, mas nenhum de vocês conseguiu refutar Jó, nem responder aos seus argumentos.

[[v18-32-13]]

^<<v18-32-13,13>>^ Portanto, não me venham com a seguinte desculpa: ‘Descobrimos a sabedoria! Deus pode vencê-lo, e não o homem.’

[[v18-32-14]]

^<<v18-32-14,14>>^ Ora, ele não me dirigiu palavra alguma, e eu não lhe responderei com as palavras que vocês usaram."

[[v18-32-15]]

^<<v18-32-15,15>>^ "Jó, os três estão pasmados, já não respondem, faltam-lhes as palavras.

[[v18-32-16]]

^<<v18-32-16,16>>^ Será que devo esperar, pois não falam, estão parados e nada mais respondem?

[[v18-32-17]]

^<<v18-32-17,17>>^ Também eu de minha parte vou responder e darei a minha opinião.

[[v18-32-18]]

^<<v18-32-18,18>>^ Porque tenho muito que falar, e o meu espírito me constrange.

[[v18-32-19]]

^<<v18-32-19,19>>^ Eis que dentro de mim sou como o vinho, sem respiradouro, como odres novos, prestes a arrebentar.

[[v18-32-20]]

^<<v18-32-20,20>>^ Permitam, pois, que eu fale para poder desabafar; abrirei os lábios e responderei.

[[v18-32-21]]

^<<v18-32-21,21>>^ Não tratarei nenhum de vocês com parcialidade e não vou lisonjear ninguém.

[[v18-32-22]]

^<<v18-32-22,22>>^ Porque não sei lisonjear; se assim fizesse, em breve me levaria o meu Criador."

'''

xref:018-jo/018-jo-031.adoc#v18-31-0[&#60; Capítulo Anterior] | <<v18-32-0,Topo>> | xref:018-jo/018-jo-033.adoc#v18-33-0[Próximo Capítulo &#62;]