include::./index.adoc[]

[[v18-26-0]]
=== Jó, 26
// naa ?, NAA - Nova Almeida Atualizada

[[v18-26-1]]

^<<v18-26-1,1>>^ Então Jó respondeu:

[[v18-26-2]]

^<<v18-26-2,2>>^ "Como você sabe ajudar o que não tem força! Como você sabe socorrer o braço que não tem vigor!

[[v18-26-3]]

^<<v18-26-3,3>>^ Como você sabe aconselhar o que não tem sabedoria e revelar plenitude de verdadeiro conhecimento!

[[v18-26-4]]

^<<v18-26-4,4>>^ Com a ajuda de quem você profere tais palavras? E de quem é o espírito que fala em você?"

[[v18-26-5]]

^<<v18-26-5,5>>^ "Os mortos tremem debaixo das águas com os seus moradores.

[[v18-26-6]]

^<<v18-26-6,6>>^ O mundo dos mortos está desnudo diante de Deus, e não há coberta para o abismo.

[[v18-26-7]]

^<<v18-26-7,7>>^ Ele estende o norte sobre o vazio e faz a terra pairar sobre o nada.

[[v18-26-8]]

^<<v18-26-8,8>>^ Prende as águas em densas nuvens, e as nuvens não se rasgam debaixo delas.

[[v18-26-9]]

^<<v18-26-9,9>>^ Encobre a face do seu trono e sobre ele estende a sua nuvem.

[[v18-26-10]]

^<<v18-26-10,10>>^ Traçou um círculo sobre a superfície das águas, no limite entre a luz e as trevas.

[[v18-26-11]]

^<<v18-26-11,11>>^ As colunas do céu tremem e se espantam diante da sua ameaça.

[[v18-26-12]]

^<<v18-26-12,12>>^ Com a sua força dominou o mar e com o seu entendimento despedaçou o monstro Raabe.

[[v18-26-13]]

^<<v18-26-13,13>>^ Pelo seu sopro o céu se aclarou, a sua mão feriu a serpente veloz.

[[v18-26-14]]

^<<v18-26-14,14>>^ Eis que isto são apenas as bordas dos seus caminhos! Dele temos ouvido apenas um leve sussurro! Mas o trovão do seu poder, quem o entenderá?"

'''

xref:018-jo/018-jo-025.adoc#v18-25-0[&#60; Capítulo Anterior] | <<v18-26-0,Topo>> | xref:018-jo/018-jo-027.adoc#v18-27-0[Próximo Capítulo &#62;]