include::./index.adoc[]

[[v18-2-0]]
=== Jó, 2
// naa ?, NAA - Nova Almeida Atualizada

[[v18-2-1]]

^<<v18-2-1,1>>^ Num dia em que os filhos de Deus vieram apresentar-se diante do Senhor , veio também Satanás entre eles apresentar-se diante do Senhor .

[[v18-2-2]]

^<<v18-2-2,2>>^ Então o Senhor  perguntou a Satanás: — De onde você vem? Satanás respondeu ao Senhor : — De rodear a terra e passear por ela.

[[v18-2-3]]

^<<v18-2-3,3>>^ E o Senhor  disse a Satanás: — Você reparou no meu servo Jó? Não há ninguém como ele na terra. Ele é um homem íntegro e reto, que teme a Deus e se desvia do mal. Ele ainda conserva a sua integridade, embora você me incitasse contra ele, para destruí-lo sem motivo.

[[v18-2-4]]

^<<v18-2-4,4>>^ Então Satanás respondeu ao Senhor : — Pele por pele! Um homem é capaz de dar tudo o que tem pela sua vida.

[[v18-2-5]]

^<<v18-2-5,5>>^ Mas estende a tua mão e toca nos ossos e na carne dele, para ver se ele não blasfema contra ti na tua face.

[[v18-2-6]]

^<<v18-2-6,6>>^ Então o Senhor  disse a Satanás: — Você pode fazer com ele o que quiser; mas poupe-lhe a vida.

[[v18-2-7]]

^<<v18-2-7,7>>^ Então Satanás saiu da presença do Senhor  e feriu Jó com tumores malignos, desde a planta do pé até o alto da cabeça.

[[v18-2-8]]

^<<v18-2-8,8>>^ Jó, sentado em cinza, pegou um caco de barro para com ele raspar as feridas.

[[v18-2-9]]

^<<v18-2-9,9>>^ Então a mulher dele disse: — Você ainda conserva a sua integridade? Amaldiçoe a Deus e morra!

[[v18-2-10]]

^<<v18-2-10,10>>^ Mas Jó respondeu: — Você fala como uma doida. Temos recebido de Deus o bem; por que não receberíamos também o mal? Em tudo isto Jó não pecou com os seus lábios.

[[v18-2-11]]

^<<v18-2-11,11>>^ Quando três amigos de Jó ouviram que todo este mal havia caído sobre ele, vieram, cada um do seu lugar: Elifaz, o temanita, Bildade, o suíta, e Zofar, o naamatita. Tinham combinado ir juntos condoer-se dele e consolá-lo.

[[v18-2-12]]

^<<v18-2-12,12>>^ De longe eles levantaram os olhos e não o reconheceram. Então ergueram a voz e choraram. E cada um, rasgando o seu manto, lançava pó ao ar sobre a cabeça.

[[v18-2-13]]

^<<v18-2-13,13>>^ Sentaram-se com ele no chão durante sete dias e sete noites. E ninguém lhe disse uma só palavra, pois viam que a dor era muito grande.

'''

xref:018-jo/018-jo-001.adoc#v18-1-0[&#60; Capítulo Anterior] | <<v18-2-0,Topo>> | xref:018-jo/018-jo-003.adoc#v18-3-0[Próximo Capítulo &#62;]