include::./index.adoc[]

[[v18-20-0]]
=== Jó, 20
// naa ?, NAA - Nova Almeida Atualizada

[[v18-20-1]]

^<<v18-20-1,1>>^ Então Zofar, o naamatita, tomou a palavra e disse:

[[v18-20-2]]

^<<v18-20-2,2>>^ "Visto que os meus pensamentos me impõem resposta, eu me apresso.

[[v18-20-3]]

^<<v18-20-3,3>>^ Eu ouvi a repreensão, que me envergonha, mas o meu espírito me obriga a responder segundo o meu entendimento."

[[v18-20-4]]

^<<v18-20-4,4>>^ "Será que você não sabe que desde todos os tempos, desde que o ser humano foi posto sobre a terra,

[[v18-20-5]]

^<<v18-20-5,5>>^ o júbilo dos ímpios é breve, e a alegria dos maus é momentânea?

[[v18-20-6]]

^<<v18-20-6,6>>^ Ainda que a sua presunção chegue aos céus, e a sua cabeça atinja as nuvens,

[[v18-20-7]]

^<<v18-20-7,7>>^ como o seu próprio esterco, ele apodrecerá para sempre, e os que o conheceram perguntarão: ‘Onde está ele?’

[[v18-20-8]]

^<<v18-20-8,8>>^ Voará como um sonho e não será encontrado; será afugentado como uma visão da noite.

[[v18-20-9]]

^<<v18-20-9,9>>^ Os olhos que o viram não o verão mais, e o lugar onde ele estava não o verá outra vez.

[[v18-20-10]]

^<<v18-20-10,10>>^ Os seus filhos procurarão aplacar os pobres, e com as suas mãos ele lhes devolverá os seus bens.

[[v18-20-11]]

^<<v18-20-11,11>>^ Ainda que os seus ossos estejam cheios do vigor da sua juventude, esse vigor se deitará com ele no pó."

[[v18-20-12]]

^<<v18-20-12,12>>^ "Ainda que o mal seja doce na sua boca, e ele o esconda debaixo da língua,

[[v18-20-13]]

^<<v18-20-13,13>>^ e o saboreie, e não o queira largar, mas o retenha em sua boca,

[[v18-20-14]]

^<<v18-20-14,14>>^ o fato é que a sua comida se transformará no seu estômago; será veneno de cobra no seu interior.

[[v18-20-15]]

^<<v18-20-15,15>>^ Engoliu riquezas, mas terá de vomitá-las; Deus o obrigará a lançá-las de seu ventre.

[[v18-20-16]]

^<<v18-20-16,16>>^ Sugou veneno de cobra; a mordedura da víbora o matará.

[[v18-20-17]]

^<<v18-20-17,17>>^ Não se deliciará com a vista dos ribeiros e dos rios transbordantes de mel e de leite.

[[v18-20-18]]

^<<v18-20-18,18>>^ Devolverá o fruto do seu trabalho e não o engolirá; do lucro dos seus negócios não tirará prazer nenhum.

[[v18-20-19]]

^<<v18-20-19,19>>^ Porque oprimiu e desamparou os pobres, roubou casas que não construiu.

[[v18-20-20]]

^<<v18-20-20,20>>^ Por não haver limites à sua cobiça, não chegará a salvar as coisas por ele desejadas.

[[v18-20-21]]

^<<v18-20-21,21>>^ Nada escapou à sua cobiça insaciável; por isso a sua prosperidade não durará.

[[v18-20-22]]

^<<v18-20-22,22>>^ Na plenitude da sua riqueza, ficará angustiado; toda a força da miséria virá sobre ele."

[[v18-20-23]]

^<<v18-20-23,23>>^ "Para encher-lhe a barriga, Deus mandará sobre ele o furor da sua ira, que, por alimento, mandará chover sobre ele.

[[v18-20-24]]

^<<v18-20-24,24>>^ Se fugir das armas de ferro, uma flecha de bronze o atravessará.

[[v18-20-25]]

^<<v18-20-25,25>>^ Ele arranca a flecha das suas costas, e esta vem brilhando com o seu fel; e o pavor tomará conta dele.

[[v18-20-26]]

^<<v18-20-26,26>>^ Todas as calamidades serão reservadas contra os seus tesouros; um fogo não aceso por mãos humanas o consumirá e devorará o que ficar na sua tenda."

[[v18-20-27]]

^<<v18-20-27,27>>^ "Os céus manifestarão a sua iniquidade; e a terra se levantará contra ele.

[[v18-20-28]]

^<<v18-20-28,28>>^ As riquezas de sua casa serão levadas embora; como água serão derramadas no dia da ira de Deus.

[[v18-20-29]]

^<<v18-20-29,29>>^ Esta é, da parte de Deus, a sorte do ímpio; esta é a herança decretada por Deus."

'''

xref:018-jo/018-jo-019.adoc#v18-19-0[&#60; Capítulo Anterior] | <<v18-20-0,Topo>> | xref:018-jo/018-jo-021.adoc#v18-21-0[Próximo Capítulo &#62;]