include::./index.adoc[]

[[v18-27-0]]
=== Jó, 27
// naa ?, NAA - Nova Almeida Atualizada

[[v18-27-1]]

^<<v18-27-1,1>>^ Jó continuou em sua fala, dizendo:

[[v18-27-2]]

^<<v18-27-2,2>>^ "Tão certo como vive Deus, que me tirou o direito, o Todo-Poderoso, que amargurou a minha alma,

[[v18-27-3]]

^<<v18-27-3,3>>^ enquanto eu puder respirar e o sopro de Deus estiver nas minhas narinas,

[[v18-27-4]]

^<<v18-27-4,4>>^ nunca os meus lábios falarão injustiça, nem a minha língua pronunciará engano.

[[v18-27-5]]

^<<v18-27-5,5>>^ Longe de mim que eu dê razão a vocês! Até morrer, nunca abrirei mão da minha integridade.

[[v18-27-6]]

^<<v18-27-6,6>>^ À minha justiça me apegarei e não a largarei; a minha consciência não me acusará em toda a minha vida."

[[v18-27-7]]

^<<v18-27-7,7>>^ "Que o meu inimigo seja como o perverso, e o que se levantar contra mim, como o injusto.

[[v18-27-8]]

^<<v18-27-8,8>>^ Porque qual será a esperança do ímpio, quando lhe for tirada a vida, quando Deus lhe arrancar a alma?

[[v18-27-9]]

^<<v18-27-9,9>>^ Será que Deus ouvirá o seu clamor, quando lhe sobrevier a angústia?

[[v18-27-10]]

^<<v18-27-10,10>>^ Será que o ímpio encontrará prazer no Todo-Poderoso e invocará a Deus a todo o momento?"

[[v18-27-11]]

^<<v18-27-11,11>>^ "Vou ensinar a vocês a respeito do poder de Deus e não lhes ocultarei o que está na mente do Todo-Poderoso.

[[v18-27-12]]

^<<v18-27-12,12>>^ Eis que todos vocês já viram isso. Por que, então, ficam repetindo palavras que não fazem sentido?"

[[v18-27-13]]

^<<v18-27-13,13>>^ "Esta é a porção que Deus dará ao perverso, a herança que os opressores receberão do Todo-Poderoso:

[[v18-27-14]]

^<<v18-27-14,14>>^ Se os filhos deles se multiplicarem, será para que sejam mortos à espada; e os seus descendentes passarão fome.

[[v18-27-15]]

^<<v18-27-15,15>>^ Os que sobreviverem, a peste os sepultará, e as suas viúvas não chorarão por eles."

[[v18-27-16]]

^<<v18-27-16,16>>^ "Se o perverso amontoar prata como pó e acumular roupas como barro,

[[v18-27-17]]

^<<v18-27-17,17>>^ poderá até acumular tudo isso, mas o justo é que vestirá as roupas, e o inocente ficará com a prata.

[[v18-27-18]]

^<<v18-27-18,18>>^ A casa que ele edifica é como a da traça, como a cabana que o vigia constrói.

[[v18-27-19]]

^<<v18-27-19,19>>^ Rico, ele se deita com a sua riqueza, mas, quando abre os olhos, ela já se foi.

[[v18-27-20]]

^<<v18-27-20,20>>^ Pavores se apoderam dele como inundação, de noite a tempestade o arrebata.

[[v18-27-21]]

^<<v18-27-21,21>>^ O vento leste o leva, e ele se vai; varre-o com ímpeto do seu lugar.

[[v18-27-22]]

^<<v18-27-22,22>>^ Deus lança isto sobre ele e não o poupa, a ele que procura fugir às pressas da sua mão.

[[v18-27-23]]

^<<v18-27-23,23>>^ Diante de sua queda, as pessoas batem palmas; ao vê-lo ir embora o vaiam com assobios."

'''

xref:018-jo/018-jo-026.adoc#v18-26-0[&#60; Capítulo Anterior] | <<v18-27-0,Topo>> | xref:018-jo/018-jo-028.adoc#v18-28-0[Próximo Capítulo &#62;]