include::./index.adoc[]

[[v18-24-0]]
=== Jó, 24
// naa ?, NAA - Nova Almeida Atualizada

[[v18-24-1]]

^<<v18-24-1,1>>^ "Por que o Todo-Poderoso não designa tempos de julgamento? E por que os que o conhecem não veem tais dias?

[[v18-24-2]]

^<<v18-24-2,2>>^ Há os que removem os marcos de divisa, roubam os rebanhos e os apascentam.

[[v18-24-3]]

^<<v18-24-3,3>>^ Levam o jumento que pertence ao órfão, e, como penhor, ficam com o boi da viúva.

[[v18-24-4]]

^<<v18-24-4,4>>^ Desviam do caminho os necessitados, e os pobres da terra todos têm de se esconder."

[[v18-24-5]]

^<<v18-24-5,5>>^ "Como jumentos selvagens no deserto, os pobres saem para o seu trabalho, à procura de alimento; em campo aberto encontram comida para eles e para os seus filhos.

[[v18-24-6]]

^<<v18-24-6,6>>^ Cortam o seu pasto no campo, e apanham as uvas que ficaram nas vinhas dos ímpios.

[[v18-24-7]]

^<<v18-24-7,7>>^ Passam a noite nus por falta de roupa e não têm cobertas contra o frio.

[[v18-24-8]]

^<<v18-24-8,8>>^ São encharcados pelas chuvas das montanhas e, por falta de abrigo, abraçam-se às rochas.

[[v18-24-9]]

^<<v18-24-9,9>>^ Orfãozinhos são arrancados do peito, e dos pobres se toma penhor.

[[v18-24-10]]

^<<v18-24-10,10>>^ Os pobres andam nus, sem roupa, e, famintos, carregam os feixes.

[[v18-24-11]]

^<<v18-24-11,11>>^ Entre os muros desses perversos espremem o azeite; pisam as uvas no lagar, enquanto padecem sede.

[[v18-24-12]]

^<<v18-24-12,12>>^ Desde as cidades gemem os que estão para morrer, e a alma dos feridos pede socorro, mas Deus não considera isso anormal."

[[v18-24-13]]

^<<v18-24-13,13>>^ "Os perversos são inimigos da luz, não conhecem os seus caminhos, nem permanecem nas suas veredas.

[[v18-24-14]]

^<<v18-24-14,14>>^ O assassino se levanta de madrugada, mata o pobre e o necessitado, e de noite se torna ladrão.

[[v18-24-15]]

^<<v18-24-15,15>>^ O olho do adúltero aguarda o crepúsculo, dizendo: ‘Ninguém me verá’; e cobre o rosto.

[[v18-24-16]]

^<<v18-24-16,16>>^ Nas trevas, ladrões invadem as casas, mas de dia ficam escondidos; não querem nada com a luz.

[[v18-24-17]]

^<<v18-24-17,17>>^ Pois a manhã é para todos eles como sombra de morte, mas os terrores da noite lhes são familiares."

[[v18-24-18]]

^<<v18-24-18,18>>^ "Os perversos são levados rapidamente na superfície das águas; a porção deles na terra é maldita, e por isso já não andam pelo caminho das vinhas.

[[v18-24-19]]

^<<v18-24-19,19>>^ A seca e o calor desfazem as águas da neve; a sepultura faz o mesmo com os que pecaram.

[[v18-24-20]]

^<<v18-24-20,20>>^ A mãe se esquecerá deles, os vermes os comerão com gosto; nunca mais haverá lembrança deles. A injustiça será quebrada como uma árvore.

[[v18-24-21]]

^<<v18-24-21,21>>^ Maltratam as estéreis, que não têm filhos, e não fazem o bem às viúvas.

[[v18-24-22]]

^<<v18-24-22,22>>^ Mas Deus, por sua força, prolonga os dias dos valentes; eles se veem em pé quando desesperavam da vida.

[[v18-24-23]]

^<<v18-24-23,23>>^ Ele lhes dá descanso, e nisso se apoiam; mas os olhos de Deus estão atentos aos caminhos deles.

[[v18-24-24]]

^<<v18-24-24,24>>^ São exaltados por breve tempo; depois, passam, colhidos como todos os demais; são cortados como as espigas do trigo.

[[v18-24-25]]

^<<v18-24-25,25>>^ Se não é assim, quem me desmentirá e anulará as minhas palavras?"

'''

xref:018-jo/018-jo-023.adoc#v18-23-0[&#60; Capítulo Anterior] | <<v18-24-0,Topo>> | xref:018-jo/018-jo-025.adoc#v18-25-0[Próximo Capítulo &#62;]