include::./index.adoc[]

[[v18-18-0]]
=== Jó, 18
// naa ?, NAA - Nova Almeida Atualizada

[[v18-18-1]]

^<<v18-18-1,1>>^ Então Bildade, o suíta, tomou a palavra e disse:

[[v18-18-2]]

^<<v18-18-2,2>>^ "Até quando você andará à caça de palavras? Considere bem, e então falaremos.

[[v18-18-3]]

^<<v18-18-3,3>>^ Por que somos considerados como animais e passamos por tolos aos seus olhos?

[[v18-18-4]]

^<<v18-18-4,4>>^ Você, que se despedaça em sua ira, pensa que a terra será abandonada por sua causa? Você pensa que as rochas devem ser tiradas do seu lugar?"

[[v18-18-5]]

^<<v18-18-5,5>>^ "Na verdade, a luz do ímpio se apagará, e a chama do seu fogo não resplandecerá.

[[v18-18-6]]

^<<v18-18-6,6>>^ A luz se escurecerá na sua tenda, e a sua lâmpada sobre ele se apagará.

[[v18-18-7]]

^<<v18-18-7,7>>^ Os seus passos vigorosos se estreitarão, e a sua própria trama o derrubará.

[[v18-18-8]]

^<<v18-18-8,8>>^ Porque por seus próprios pés é lançado na rede e andará sobre as suas malhas.

[[v18-18-9]]

^<<v18-18-9,9>>^ A armadilha o apanhará pelo calcanhar, e o laço o prenderá.

[[v18-18-10]]

^<<v18-18-10,10>>^ A corda está escondida na terra para apanhá-lo, a armadilha se encontra no seu caminho.

[[v18-18-11]]

^<<v18-18-11,11>>^ Terrores o amedrontam de todos os lados e o perseguem a cada passo.

[[v18-18-12]]

^<<v18-18-12,12>>^ A calamidade virá faminta sobre ele, e a miséria estará alerta ao seu lado.

[[v18-18-13]]

^<<v18-18-13,13>>^ Ela devorará os membros do seu corpo; serão devorados pelo primogênito da morte.

[[v18-18-14]]

^<<v18-18-14,14>>^ O ímpio será arrancado da segurança de sua tenda, e será levado ao rei dos terrores.

[[v18-18-15]]

^<<v18-18-15,15>>^ Nenhum dos seus irá morar na sua tenda; enxofre será espalhado sobre a sua habitação.

[[v18-18-16]]

^<<v18-18-16,16>>^ Por baixo secarão as suas raízes, e por cima murcharão os seus ramos.

[[v18-18-17]]

^<<v18-18-17,17>>^ A sua memória desaparecerá da terra, e pelas praças não terá nome.

[[v18-18-18]]

^<<v18-18-18,18>>^ Da luz o lançarão nas trevas e o afugentarão do mundo.

[[v18-18-19]]

^<<v18-18-19,19>>^ Não terá filho nem posteridade entre o seu povo, nem sobrevivente algum ficará nas suas moradas.

[[v18-18-20]]

^<<v18-18-20,20>>^ Do seu dia se espantarão os do Ocidente, e os do Oriente serão tomados de horror.

[[v18-18-21]]

^<<v18-18-21,21>>^ Tais são, na verdade, as moradas do ímpio, e este é o paradeiro daquele que não conhece Deus."

'''

xref:018-jo/018-jo-017.adoc#v18-17-0[&#60; Capítulo Anterior] | <<v18-18-0,Topo>> | xref:018-jo/018-jo-019.adoc#v18-19-0[Próximo Capítulo &#62;]