include::./index.adoc[]

[[v18-19-0]]
=== Jó, 19
// naa ?, NAA - Nova Almeida Atualizada

[[v18-19-1]]

^<<v18-19-1,1>>^ Então Jó respondeu:

[[v18-19-2]]

^<<v18-19-2,2>>^ "Até quando vocês vão me atormentar e me esmagar com as suas palavras?

[[v18-19-3]]

^<<v18-19-3,3>>^ Já dez vezes vocês me insultaram e não se envergonham de me injuriar.

[[v18-19-4]]

^<<v18-19-4,4>>^ Se eu tivesse realmente cometido algum erro, isso interessaria somente a mim.

[[v18-19-5]]

^<<v18-19-5,5>>^ Se vocês querem se engrandecer contra mim e usam a minha vergonha como argumento contra mim,

[[v18-19-6]]

^<<v18-19-6,6>>^ então saibam que Deus foi injusto comigo e me cercou com a sua rede."

[[v18-19-7]]

^<<v18-19-7,7>>^ "Eis que clamo: ‘Violência!’, mas não sou ouvido; grito: ‘Socorro!’, porém não há justiça.

[[v18-19-8]]

^<<v18-19-8,8>>^ Deus fechou o meu caminho, e não consigo passar; e nas minhas veredas pôs trevas.

[[v18-19-9]]

^<<v18-19-9,9>>^ Despojou-me da minha honra e tirou a coroa da minha cabeça.

[[v18-19-10]]

^<<v18-19-10,10>>^ Arruinou-me de todos os lados, e eu me vou; tirou-me a esperança, como se arranca uma árvore.

[[v18-19-11]]

^<<v18-19-11,11>>^ Acendeu contra mim a sua ira e me trata como um dos seus adversários.

[[v18-19-12]]

^<<v18-19-12,12>>^ Juntas vieram as suas tropas; prepararam contra mim o seu caminho e acamparam ao redor da minha tenda."

[[v18-19-13]]

^<<v18-19-13,13>>^ "Deus levou os meus irmãos para longe de mim, e os que me conhecem, como estranhos, se afastaram de mim.

[[v18-19-14]]

^<<v18-19-14,14>>^ Os meus parentes me abandonaram, e os meus conhecidos se esqueceram de mim.

[[v18-19-15]]

^<<v18-19-15,15>>^ Os que se abrigam na minha casa e as minhas servas me consideram como um estranho; vim a ser um estrangeiro aos olhos deles.

[[v18-19-16]]

^<<v18-19-16,16>>^ Chamo o meu servo, e ele não me responde; tenho de suplicar-lhe, eu mesmo.

[[v18-19-17]]

^<<v18-19-17,17>>^ O meu hálito é intolerável à minha mulher, e pelo mau cheiro sou repugnante aos meus irmãos.

[[v18-19-18]]

^<<v18-19-18,18>>^ Até as crianças me desprezam, e, quando tento me levantar, zombam de mim.

[[v18-19-19]]

^<<v18-19-19,19>>^ Todos os meus amigos íntimos me detestam, e até os que eu amava se voltaram contra mim.

[[v18-19-20]]

^<<v18-19-20,20>>^ Os meus ossos se apegam à minha pele e à minha carne; escapei só com a pele dos meus dentes.

[[v18-19-21]]

^<<v18-19-21,21>>^ Tenham pena de mim, meus amigos, tenham pena de mim, porque a mão de Deus me atingiu.

[[v18-19-22]]

^<<v18-19-22,22>>^ Por que vocês me perseguem como Deus me persegue e não cessam de devorar a minha carne?"

[[v18-19-23]]

^<<v18-19-23,23>>^ "Quem dera fossem agora escritas as minhas palavras! Quem dera fossem gravadas em livro!

[[v18-19-24]]

^<<v18-19-24,24>>^ Que, com pena de ferro e com chumbo, para sempre fossem esculpidas na rocha!

[[v18-19-25]]

^<<v18-19-25,25>>^ Porque eu sei que o meu Redentor vive e por fim se levantará sobre a terra.

[[v18-19-26]]

^<<v18-19-26,26>>^ Depois, revestido este meu corpo da minha pele, em minha carne verei a Deus.

[[v18-19-27]]

^<<v18-19-27,27>>^ Eu o verei por mim mesmo, os meus olhos o verão, e não outros; de saudade o meu coração desfalece dentro de mim."

[[v18-19-28]]

^<<v18-19-28,28>>^ "Se vocês disserem: ‘Como o perseguiremos?’ E: ‘A causa deste mal se acha nele mesmo’,

[[v18-19-29]]

^<<v18-19-29,29>>^ então tenham medo da espada, porque tais acusações merecem o seu furor, para que vocês saibam que há um juízo."

'''

xref:018-jo/018-jo-018.adoc#v18-18-0[&#60; Capítulo Anterior] | <<v18-19-0,Topo>> | xref:018-jo/018-jo-020.adoc#v18-20-0[Próximo Capítulo &#62;]