include::./index.adoc[]

[[v18-33-0]]
=== Jó, 33
// naa ?, NAA - Nova Almeida Atualizada

[[v18-33-1]]

^<<v18-33-1,1>>^ "E agora, Jó, escute os meus argumentos e dê ouvidos a todas as minhas palavras.

[[v18-33-2]]

^<<v18-33-2,2>>^ Passo agora a falar; em minha boca fala a língua.

[[v18-33-3]]

^<<v18-33-3,3>>^ Os meus argumentos provam a sinceridade do meu coração, e os meus lábios proferem o puro saber.

[[v18-33-4]]

^<<v18-33-4,4>>^ O Espírito de Deus me fez, e o sopro do Todo-Poderoso me dá vida."

[[v18-33-5]]

^<<v18-33-5,5>>^ "Responda-me, se for capaz; prepare os seus argumentos e apresente-se diante de mim.

[[v18-33-6]]

^<<v18-33-6,6>>^ Eis que diante de Deus sou igual a você; também eu fui formado do barro.

[[v18-33-7]]

^<<v18-33-7,7>>^ Por isso, não tenha medo de mim; a minha mão não será pesada sobre você."

[[v18-33-8]]

^<<v18-33-8,8>>^ "Na verdade, você falou diante de mim; eu ouvi o som das suas palavras, dizendo:

[[v18-33-9]]

^<<v18-33-9,9>>^ ‘Estou limpo, sem transgressão; sou puro e não tenho iniquidade.

[[v18-33-10]]

^<<v18-33-10,10>>^ Eis que Deus procura pretextos contra mim e me considera seu inimigo.

[[v18-33-11]]

^<<v18-33-11,11>>^ Prendeu os meus pés com correntes e observa todas as minhas veredas.’"

[[v18-33-12]]

^<<v18-33-12,12>>^ "Devo lhe dizer que nisto você não tem razão; porque Deus é maior do que o homem.

[[v18-33-13]]

^<<v18-33-13,13>>^ Por que você discute com ele, afirmando que ele não presta contas de nenhum dos seus atos?

[[v18-33-14]]

^<<v18-33-14,14>>^ Pelo contrário, Deus fala de um modo, sim, de dois modos, mas o homem não atenta para isso.

[[v18-33-15]]

^<<v18-33-15,15>>^ Em sonho ou em visão de noite, quando o sono profundo cai sobre as pessoas, quando adormecem na cama,

[[v18-33-16]]

^<<v18-33-16,16>>^ então lhes abre os ouvidos e lhes sela a sua instrução,

[[v18-33-17]]

^<<v18-33-17,17>>^ para afastar o ser humano dos seus planos e livrá-lo do orgulho;

[[v18-33-18]]

^<<v18-33-18,18>>^ para guardar a sua alma da cova e a sua vida de passar pela espada."

[[v18-33-19]]

^<<v18-33-19,19>>^ "Também no seu leito é castigado com dores, com incessante conflito em seus ossos;

[[v18-33-20]]

^<<v18-33-20,20>>^ de modo que abomina o pão, e detesta até a comida mais saborosa.

[[v18-33-21]]

^<<v18-33-21,21>>^ A sua carne, que se via, agora desaparece, e os seus ossos, que não se viam, agora aparecem.

[[v18-33-22]]

^<<v18-33-22,22>>^ A sua alma está perto da morte, e a sua vida se aproxima dos que trazem a morte."

[[v18-33-23]]

^<<v18-33-23,23>>^ "Se com ele houver um anjo intercessor, um dos milhares, para declarar ao homem o que é certo,

[[v18-33-24]]

^<<v18-33-24,24>>^ então Deus terá misericórdia dele e dirá ao anjo: ‘Livre-o, para que não desça à cova; já achei um resgate para ele.’

[[v18-33-25]]

^<<v18-33-25,25>>^ Então a sua carne recupera o vigor da infância, e ele volta aos dias da juventude.

[[v18-33-26]]

^<<v18-33-26,26>>^ Ele ora a Deus, que se agrada dele; com alegria vê a face de Deus, e Deus lhe restitui a sua justiça.

[[v18-33-27]]

^<<v18-33-27,27>>^ Depois, cantará diante de todos e dirá: ‘Pequei, perverti o direito e não fui punido como merecia.

[[v18-33-28]]

^<<v18-33-28,28>>^ Deus livrou a minha alma de ir para a cova, e a minha vida verá a luz.’"

[[v18-33-29]]

^<<v18-33-29,29>>^ "Eis que Deus faz tudo isto duas e três vezes no seu trato com o ser humano,

[[v18-33-30]]

^<<v18-33-30,30>>^ para reconduzir da cova a sua alma e iluminá-lo com a luz dos viventes."

[[v18-33-31]]

^<<v18-33-31,31>>^ "Agora, Jó, preste atenção e escute o que vou dizer; fique calado, porque vou falar.

[[v18-33-32]]

^<<v18-33-32,32>>^ Se você tem alguma coisa a dizer, diga; fale, porque gostaria de lhe dar razão.

[[v18-33-33]]

^<<v18-33-33,33>>^ Se não, escute o que vou dizer; fique calado, e eu lhe ensinarei a sabedoria."

'''

xref:018-jo/018-jo-032.adoc#v18-32-0[&#60; Capítulo Anterior] | <<v18-33-0,Topo>> | xref:018-jo/018-jo-034.adoc#v18-34-0[Próximo Capítulo &#62;]