include::./index.adoc[]

[[v18-36-0]]
=== Jó, 36
// naa ?, NAA - Nova Almeida Atualizada

[[v18-36-1]]

^<<v18-36-1,1>>^ Eliú seguiu falando e disse:

[[v18-36-2]]

^<<v18-36-2,2>>^ "Mais um pouco de paciência, e eu lhe mostrarei que tenho mais argumentos a favor de Deus.

[[v18-36-3]]

^<<v18-36-3,3>>^ Trarei o meu conhecimento de longe e atribuirei a justiça ao meu Criador.

[[v18-36-4]]

^<<v18-36-4,4>>^ Porque, na verdade, as minhas palavras não são falsas; quem está diante de você é senhor do assunto."

[[v18-36-5]]

^<<v18-36-5,5>>^ "Eis que Deus é grande e não despreza ninguém; ele é grande na força da sua compreensão.

[[v18-36-6]]

^<<v18-36-6,6>>^ Não poupa a vida do ímpio, mas faz justiça aos aflitos.

[[v18-36-7]]

^<<v18-36-7,7>>^ Deus não tira os seus olhos dos justos; pelo contrário, os assenta no trono com os reis, para sempre, e eles são exaltados.

[[v18-36-8]]

^<<v18-36-8,8>>^ Se estão presos com correntes e amarrados com cordas de aflição,

[[v18-36-9]]

^<<v18-36-9,9>>^ ele lhes faz ver as suas obras, as suas transgressões, e que se mostraram arrogantes.

[[v18-36-10]]

^<<v18-36-10,10>>^ Abre-lhes também os ouvidos para a instrução e ordena que se convertam da iniquidade.

[[v18-36-11]]

^<<v18-36-11,11>>^ Se o ouvirem e o servirem, acabarão os seus dias em felicidade e os seus anos em delícias.

[[v18-36-12]]

^<<v18-36-12,12>>^ Porém, se não o ouvirem, serão passados pela espada e morrerão na sua cegueira."

[[v18-36-13]]

^<<v18-36-13,13>>^ "Os ímpios de coração alimentam a ira; e, quando são aprisionados por Deus, não clamam pedindo socorro.

[[v18-36-14]]

^<<v18-36-14,14>>^ Perdem a vida na sua mocidade e morrem entre os prostitutos cultuais.

[[v18-36-15]]

^<<v18-36-15,15>>^ Deus livra o aflito por meio da sua aflição e pelo sofrimento lhe abre os ouvidos."

[[v18-36-16]]

^<<v18-36-16,16>>^ "Assim também a você Deus procura tirar da angústia e levar para um lugar espaçoso, em que não há aperto, e para o conforto de uma mesa cheia de comida saborosa.

[[v18-36-17]]

^<<v18-36-17,17>>^ Mas você se enche do juízo do perverso, e, por isso, o juízo e a justiça o alcançarão.

[[v18-36-18]]

^<<v18-36-18,18>>^ Tenha cuidado para que a ira não o leve a zombar, nem permita que a grande quantia do resgate o desvie.

[[v18-36-19]]

^<<v18-36-19,19>>^ Será que ele levaria em conta as suas lamúrias e todos os seus grandes esforços, para que você se veja livre da sua angústia?

[[v18-36-20]]

^<<v18-36-20,20>>^ Não suspire pela noite, em que povos serão tirados do seu lugar.

[[v18-36-21]]

^<<v18-36-21,21>>^ Cuidado! Não se incline para a iniquidade, você parece preferir a iniquidade à sua miséria."

[[v18-36-22]]

^<<v18-36-22,22>>^ "Eis que Deus se mostra grande em seu poder! Quem é mestre como ele?

[[v18-36-23]]

^<<v18-36-23,23>>^ Quem lhe prescreveu o seu caminho ou quem pode lhe dizer: ‘Cometeste uma injustiça’?

[[v18-36-24]]

^<<v18-36-24,24>>^ Lembre-se de exaltar as obras de Deus, que as pessoas celebram.

[[v18-36-25]]

^<<v18-36-25,25>>^ Toda a humanidade olha para elas; as pessoas as contemplam de longe.

[[v18-36-26]]

^<<v18-36-26,26>>^ Eis que Deus é grande, e não o podemos compreender; o número dos seus anos não se pode calcular."

[[v18-36-27]]

^<<v18-36-27,27>>^ "Ele atrai para si as gotas de água que de seu vapor destilam em chuva,

[[v18-36-28]]

^<<v18-36-28,28>>^ a qual as nuvens derramam e gotejam sobre a terra em grande abundância.

[[v18-36-29]]

^<<v18-36-29,29>>^ Pode alguém entender como ele estende as nuvens e como os trovões ecoam em sua tenda?

[[v18-36-30]]

^<<v18-36-30,30>>^ Eis que ele espalha sobre elas o seu relâmpago e encobre as profundezas do mar.

[[v18-36-31]]

^<<v18-36-31,31>>^ Pois por estas coisas ele julga os povos e lhes dá alimento em abundância.

[[v18-36-32]]

^<<v18-36-32,32>>^ Enche as mãos de relâmpagos e os arremessa contra o adversário.

[[v18-36-33]]

^<<v18-36-33,33>>^ O fragor da tempestade dá notícias a respeito dele, dele que é zeloso na sua ira contra a injustiça."

'''

xref:018-jo/018-jo-035.adoc#v18-35-0[&#60; Capítulo Anterior] | <<v18-36-0,Topo>> | xref:018-jo/018-jo-037.adoc#v18-37-0[Próximo Capítulo &#62;]