include::./index.adoc[]

[[v18-23-0]]
=== Jó, 23
// naa ?, NAA - Nova Almeida Atualizada

[[v18-23-1]]

^<<v18-23-1,1>>^ Então Jó respondeu:

[[v18-23-2]]

^<<v18-23-2,2>>^ "Ainda hoje a minha queixa é de um revoltado, apesar de a minha mão reprimir o meu gemido.

[[v18-23-3]]

^<<v18-23-3,3>>^ Quem dera eu soubesse onde encontrá-lo! Então me chegaria ao seu tribunal.

[[v18-23-4]]

^<<v18-23-4,4>>^ Exporia diante dele a minha causa, encheria a minha boca de argumentos.

[[v18-23-5]]

^<<v18-23-5,5>>^ Saberia com que palavras ele me responderia e entenderia o que ele fosse me dizer.

[[v18-23-6]]

^<<v18-23-6,6>>^ Será que ele discutiria comigo, segundo a grandeza do seu poder? Não! Ele me atenderia.

[[v18-23-7]]

^<<v18-23-7,7>>^ Ali, o homem reto apresentaria a sua causa diante dele, e eu me livraria para sempre do meu juiz."

[[v18-23-8]]

^<<v18-23-8,8>>^ "Se me adianto, Deus não está ali; se volto para trás, não o percebo.

[[v18-23-9]]

^<<v18-23-9,9>>^ Se ele age à minha esquerda, não o vejo; se ele se esconde à minha direita, não o enxergo.

[[v18-23-10]]

^<<v18-23-10,10>>^ Mas ele sabe o meu caminho; se ele me provasse, eu sairia como o ouro.

[[v18-23-11]]

^<<v18-23-11,11>>^ Os meus pés seguiram as suas pisadas; guardei o seu caminho e não me desviei dele.

[[v18-23-12]]

^<<v18-23-12,12>>^ Do mandamento dos seus lábios nunca me afastei; escondi no meu íntimo as palavras da sua boca."

[[v18-23-13]]

^<<v18-23-13,13>>^ "Mas, se Deus resolveu alguma coisa, quem o pode convencer a mudar de ideia? O que ele quer, isso fará.

[[v18-23-14]]

^<<v18-23-14,14>>^ Pois ele cumprirá o que está ordenado a meu respeito e muitas coisas como estas ainda tem planejado.

[[v18-23-15]]

^<<v18-23-15,15>>^ Por isso, fico apavorado na sua presença; e, quando penso nisso, tenho medo dele.

[[v18-23-16]]

^<<v18-23-16,16>>^ Deus é quem fez o meu coração esmorecer; o Todo-Poderoso me encheu de pavor.

[[v18-23-17]]

^<<v18-23-17,17>>^ Porque não estou desfalecido por causa das trevas, nem porque a escuridão cobre o meu rosto."

'''

xref:018-jo/018-jo-022.adoc#v18-22-0[&#60; Capítulo Anterior] | <<v18-23-0,Topo>> | xref:018-jo/018-jo-024.adoc#v18-24-0[Próximo Capítulo &#62;]