include::./index.adoc[]

[[v18-16-0]]
=== Jó, 16
// naa ?, NAA - Nova Almeida Atualizada

[[v18-16-1]]

^<<v18-16-1,1>>^ Então Jó respondeu:

[[v18-16-2]]

^<<v18-16-2,2>>^ "Tenho ouvido muitas coisas como estas. Todos vocês são consoladores que só aumentam o meu sofrimento.

[[v18-16-3]]

^<<v18-16-3,3>>^ Será que não terão fim essas palavras vazias? Ou o que é que instiga você a responder assim?

[[v18-16-4]]

^<<v18-16-4,4>>^ Eu também poderia falar como vocês falam. Se vocês estivessem em meu lugar, eu poderia dirigir-lhes um montão de palavras e balançar a cabeça na presença de vocês.

[[v18-16-5]]

^<<v18-16-5,5>>^ Poderia fortalecê-los com as minhas palavras, e a consolação dos meus lábios abrandaria a dor de vocês.

[[v18-16-6]]

^<<v18-16-6,6>>^ Se eu falar, a minha dor não cessa; se me calar, qual é o meu alívio?"

[[v18-16-7]]

^<<v18-16-7,7>>^ "Na verdade, esgotaste as minhas forças; tu, ó Deus, destruíste toda a minha família.

[[v18-16-8]]

^<<v18-16-8,8>>^ Testemunha disto é que me deixaste enrugado; a minha magreza já se levanta contra mim e me acusa cara a cara."

[[v18-16-9]]

^<<v18-16-9,9>>^ "Na sua ira me despedaçou e me perseguiu; rangeu os dentes contra mim e, como meu adversário, aguça os olhos.

[[v18-16-10]]

^<<v18-16-10,10>>^ Homens abrem a sua boca contra mim, com desprezo me esbofeteiam; todos se ajuntam contra mim.

[[v18-16-11]]

^<<v18-16-11,11>>^ Deus me entrega aos ímpios e me faz cair nas mãos dos perversos.

[[v18-16-12]]

^<<v18-16-12,12>>^ Eu vivia em paz, porém ele me esmagou; pegou-me pelo pescoço e me despedaçou; ele fez de mim o seu alvo.

[[v18-16-13]]

^<<v18-16-13,13>>^ As suas flechas me atingem de todos os lados; atravessa-me os rins, e não me poupa, derrama o meu fel sobre a terra.

[[v18-16-14]]

^<<v18-16-14,14>>^ Ele me fere com golpes e mais golpes; arremete contra mim como um guerreiro."

[[v18-16-15]]

^<<v18-16-15,15>>^ "Costurei uma roupa feita de pano de saco sobre a minha pele e enterrei o meu orgulho no pó.

[[v18-16-16]]

^<<v18-16-16,16>>^ O meu rosto está vermelho de tanto chorar, e sobre as minhas pálpebras está a sombra da morte,

[[v18-16-17]]

^<<v18-16-17,17>>^ embora não haja violência nas minhas mãos, e seja pura a minha oração."

[[v18-16-18]]

^<<v18-16-18,18>>^ "Ó terra, não cubra o meu sangue, e não haja lugar em que se oculte o meu clamor!

[[v18-16-19]]

^<<v18-16-19,19>>^ Já agora a minha testemunha está no céu, e nas alturas se encontra quem advoga a minha causa.

[[v18-16-20]]

^<<v18-16-20,20>>^ Os meus amigos zombam de mim, mas os meus olhos se desfazem em lágrimas diante de Deus,

[[v18-16-21]]

^<<v18-16-21,21>>^ para que ele mantenha o direito do homem contra o próprio Deus e o do filho do homem contra o seu próximo.

[[v18-16-22]]

^<<v18-16-22,22>>^ Porque dentro de poucos anos eu seguirei o caminho de onde não voltarei."

'''

xref:018-jo/018-jo-015.adoc#v18-15-0[&#60; Capítulo Anterior] | <<v18-16-0,Topo>> | xref:018-jo/018-jo-017.adoc#v18-17-0[Próximo Capítulo &#62;]