include::./index.adoc[]

[[v18-30-0]]
=== Jó, 30
// naa ?, NAA - Nova Almeida Atualizada

[[v18-30-1]]

^<<v18-30-1,1>>^ "Mas agora zombam de mim os que têm menos idade do que eu, cujos pais eu não teria aceito nem para colocar ao lado dos cães do meu rebanho.

[[v18-30-2]]

^<<v18-30-2,2>>^ De que também me serviria a força de suas mãos, se eles são homens cujo vigor já desapareceu?

[[v18-30-3]]

^<<v18-30-3,3>>^ Enfraqueceram de tanto passar fome e necessidade; roem a terra seca, desde muito em ruínas e desolada.

[[v18-30-4]]

^<<v18-30-4,4>>^ Apanham malvas e folhas de arbustos e se alimentam de raízes de zimbro.

[[v18-30-5]]

^<<v18-30-5,5>>^ São expulsos do meio das pessoas; grita-se contra eles, como se grita atrás de um ladrão.

[[v18-30-6]]

^<<v18-30-6,6>>^ Têm de morar nos desfiladeiros sombrios, nas cavernas da terra e das rochas.

[[v18-30-7]]

^<<v18-30-7,7>>^ Uivam entre os arbustos e se ajuntam debaixo dos espinheiros.

[[v18-30-8]]

^<<v18-30-8,8>>^ São filhos de doidos, gente sem nome, e são escorraçados da terra."

[[v18-30-9]]

^<<v18-30-9,9>>^ "Mas agora sou a canção de deboche dessa gente; sirvo de provérbio no meio deles.

[[v18-30-10]]

^<<v18-30-10,10>>^ Eles me detestam, fogem para longe de mim e não têm receio de me cuspir no rosto.

[[v18-30-11]]

^<<v18-30-11,11>>^ Deus afrouxou a corda do meu arco e me oprimiu; por isso, sacudiram de si o freio diante de mim.

[[v18-30-12]]

^<<v18-30-12,12>>^ À minha direita se levanta um bando e me empurra, e contra mim prepara o seu caminho de destruição.

[[v18-30-13]]

^<<v18-30-13,13>>^ Arruínam o meu caminho; promovem a minha destruição sem a ajuda de ninguém.

[[v18-30-14]]

^<<v18-30-14,14>>^ Vêm contra mim como por uma grande brecha e se revolvem avante no meio das ruínas.

[[v18-30-15]]

^<<v18-30-15,15>>^ Sobrevieram-me pavores; a minha honra é como que varrida pelo vento; como nuvem passou a minha felicidade."

[[v18-30-16]]

^<<v18-30-16,16>>^ "Agora a minha alma se derrama dentro de mim; os dias da aflição se apoderam de mim.

[[v18-30-17]]

^<<v18-30-17,17>>^ A noite perfura os meus ossos, e o mal que me corrói não descansa.

[[v18-30-18]]

^<<v18-30-18,18>>^ Pela grande violência do meu mal está desfigurada a minha roupa; este mal me envolve como a gola da minha túnica.

[[v18-30-19]]

^<<v18-30-19,19>>^ Deus me lançou na lama, e me tornei semelhante ao pó e à cinza."

[[v18-30-20]]

^<<v18-30-20,20>>^ "Clamo a ti, ó Deus, e não me respondes; estou em pé, mas apenas olhas para mim.

[[v18-30-21]]

^<<v18-30-21,21>>^ Tu foste cruel comigo; e, com a força da tua mão, me atacas.

[[v18-30-22]]

^<<v18-30-22,22>>^ Tu me levantas sobre o vento e me fazes cavalgá-lo; no estrondo da tempestade me jogas de um lado para outro.

[[v18-30-23]]

^<<v18-30-23,23>>^ Pois eu sei que me levarás à morte e à casa destinada a todos os vivos."

[[v18-30-24]]

^<<v18-30-24,24>>^ "Não é fato que de um montão de ruínas um homem estenderá a sua mão? E, na sua desventura, não levantará um grito por socorro?

[[v18-30-25]]

^<<v18-30-25,25>>^ Por acaso, não chorei por aquele que atravessava dias difíceis? Não se angustiou a minha alma pelo necessitado?

[[v18-30-26]]

^<<v18-30-26,26>>^ Quando eu esperava o bem, eis que me veio o mal; esperava a luz, e veio a escuridão."

[[v18-30-27]]

^<<v18-30-27,27>>^ "O meu íntimo se agita sem cessar; e dias de aflição me sobrevêm.

[[v18-30-28]]

^<<v18-30-28,28>>^ Tenho a pele queimada, mas não pelo sol; levanto-me na congregação e clamo por socorro.

[[v18-30-29]]

^<<v18-30-29,29>>^ Sou irmão dos chacais e companheiro de avestruzes.

[[v18-30-30]]

^<<v18-30-30,30>>^ A minha pele escurece e cai; os meus ossos queimam de febre.

[[v18-30-31]]

^<<v18-30-31,31>>^ Por isso, a minha harpa é usada para fazer lamentações, e a minha flauta, para acompanhar os que choram."

'''

xref:018-jo/018-jo-029.adoc#v18-29-0[&#60; Capítulo Anterior] | <<v18-30-0,Topo>> | xref:018-jo/018-jo-031.adoc#v18-31-0[Próximo Capítulo &#62;]