include::./index.adoc[]

[[v18-29-0]]
=== Jó, 29
// naa ?, NAA - Nova Almeida Atualizada

[[v18-29-1]]

^<<v18-29-1,1>>^ Jó continuou em sua fala, dizendo:

[[v18-29-2]]

^<<v18-29-2,2>>^ "Ah! Quem me dera ser como fui nos meses passados, como nos dias em que Deus cuidava de mim!

[[v18-29-3]]

^<<v18-29-3,3>>^ Quando Deus fazia resplandecer a sua lâmpada sobre a minha cabeça, quando eu, guiado por sua luz, caminhava na escuridão.

[[v18-29-4]]

^<<v18-29-4,4>>^ Quem me dera ser como fui nos dias do meu vigor, quando a amizade de Deus estava sobre a minha tenda,

[[v18-29-5]]

^<<v18-29-5,5>>^ quando o Todo-Poderoso ainda estava comigo, e os meus filhos estavam ao meu redor,

[[v18-29-6]]

^<<v18-29-6,6>>^ quando eu lavava os meus pés em leite, e da rocha me corriam rios de azeite.

[[v18-29-7]]

^<<v18-29-7,7>>^ Quando eu me dirigia até o portão da cidade e mandava preparar o meu assento na praça,

[[v18-29-8]]

^<<v18-29-8,8>>^ os moços me viam e se retiravam, e os idosos se levantavam e ficavam em pé.

[[v18-29-9]]

^<<v18-29-9,9>>^ Os príncipes reprimiam as suas palavras e punham a mão sobre a boca.

[[v18-29-10]]

^<<v18-29-10,10>>^ A voz dos nobres emudecia, e a língua deles se apegava ao céu da boca."

[[v18-29-11]]

^<<v18-29-11,11>>^ "O ouvido que me ouvia dizia que eu era feliz; o olho que me via dava testemunho de mim,

[[v18-29-12]]

^<<v18-29-12,12>>^ porque eu livrava os pobres que pediam ajuda e também o órfão que não tinha quem o socorresse.

[[v18-29-13]]

^<<v18-29-13,13>>^ A bênção do que estava prestes a perecer vinha sobre mim, e eu fazia o coração da viúva cantar de alegria.

[[v18-29-14]]

^<<v18-29-14,14>>^ Eu me cobria de retidão, e ela me servia de roupa; a minha justiça era como um manto e um turbante.

[[v18-29-15]]

^<<v18-29-15,15>>^ Eu era os olhos do cego e os pés do aleijado.

[[v18-29-16]]

^<<v18-29-16,16>>^ Era pai dos necessitados e até as causas dos desconhecidos eu examinava.

[[v18-29-17]]

^<<v18-29-17,17>>^ Eu quebrava os queixos dos iníquos e arrancava as vítimas dos dentes deles."

[[v18-29-18]]

^<<v18-29-18,18>>^ "Eu dizia: ‘Vou morrer no meu ninho, e multiplicarei os meus dias como a areia.

[[v18-29-19]]

^<<v18-29-19,19>>^ As minhas raízes se estenderão até as águas, e o orvalho ficará durante a noite sobre os meus ramos.

[[v18-29-20]]

^<<v18-29-20,20>>^ A minha honra se renovará em mim, e o meu arco se reforçará na minha mão.’"

[[v18-29-21]]

^<<v18-29-21,21>>^ "Os que me ouviam esperavam o meu conselho e guardavam silêncio para ouvi-lo.

[[v18-29-22]]

^<<v18-29-22,22>>^ Depois que eu falava, não diziam nada; as minhas palavras caíam sobre eles como orvalho.

[[v18-29-23]]

^<<v18-29-23,23>>^ Esperavam-me como se espera a chuva, abriam a boca como para absorver a chuva fora de época.

[[v18-29-24]]

^<<v18-29-24,24>>^ Quando eu sorria para eles, nem acreditavam; e a luz do meu rosto eles não desprezavam.

[[v18-29-25]]

^<<v18-29-25,25>>^ Eu escolhia o caminho para eles, assentava-me como chefe e vivia como rei entre as suas tropas; eu era como quem consola os que pranteiam."

'''

xref:018-jo/018-jo-028.adoc#v18-28-0[&#60; Capítulo Anterior] | <<v18-29-0,Topo>> | xref:018-jo/018-jo-030.adoc#v18-30-0[Próximo Capítulo &#62;]