include::./index.adoc[]

[[v18-4-0]]
=== Jó, 4
// naa ?, NAA - Nova Almeida Atualizada

[[v18-4-1]]

^<<v18-4-1,1>>^ Então Elifaz, o temanita, tomou a palavra e disse:

[[v18-4-2]]

^<<v18-4-2,2>>^ "Se alguém tentar falar, você terá paciência para ouvir? Mas quem poderá conter as palavras?

[[v18-4-3]]

^<<v18-4-3,3>>^ Veja bem! Você ensinou a muitos e fortaleceu mãos cansadas.

[[v18-4-4]]

^<<v18-4-4,4>>^ As suas palavras sustentaram os que tropeçavam, e você fortaleceu joelhos vacilantes.

[[v18-4-5]]

^<<v18-4-5,5>>^ Mas agora, quando chega a sua vez, você perde a paciência; ao ser atingido, você fica apavorado.

[[v18-4-6]]

^<<v18-4-6,6>>^ Você não tem confiança no seu temor a Deus? Não tem esperança na integridade dos seus caminhos?

[[v18-4-7]]

^<<v18-4-7,7>>^ Pense bem: será que algum inocente já chegou a perecer? E onde os retos foram destruídos?

[[v18-4-8]]

^<<v18-4-8,8>>^ Segundo eu tenho visto, os que lavram a iniquidade e semeiam o mal, isso mesmo eles colhem.

[[v18-4-9]]

^<<v18-4-9,9>>^ Com o hálito de Deus perecem; e com o sopro da sua ira são consumidos.

[[v18-4-10]]

^<<v18-4-10,10>>^ Cessa o bramido do leão e a voz do leão feroz, e os dentes dos leõezinhos são quebrados.

[[v18-4-11]]

^<<v18-4-11,11>>^ O leão morre, porque não há presa, e os filhos da leoa andam dispersos."

[[v18-4-12]]

^<<v18-4-12,12>>^ "Uma palavra me foi trazida em segredo, e os meus ouvidos perceberam um sussurro dela.

[[v18-4-13]]

^<<v18-4-13,13>>^ Entre pensamentos de visões noturnas, quando o sono profundo cai sobre as pessoas,

[[v18-4-14]]

^<<v18-4-14,14>>^ sobrevieram-me o espanto e o tremor, e todos os meus ossos estremeceram.

[[v18-4-15]]

^<<v18-4-15,15>>^ Então um espírito passou por diante de mim; e se arrepiaram os cabelos do meu corpo.

[[v18-4-16]]

^<<v18-4-16,16>>^ Ele parou, mas não reconheci a sua aparência. Um vulto estava diante dos meus olhos; houve silêncio, e ouvi uma voz:

[[v18-4-17]]

^<<v18-4-17,17>>^ ‘Pode um mortal ser justo diante de Deus? Pode alguém ser puro diante do seu Criador?

[[v18-4-18]]

^<<v18-4-18,18>>^ Eis que Deus não confia nos seus servos e aos seus anjos atribui imperfeições;

[[v18-4-19]]

^<<v18-4-19,19>>^ quanto mais àqueles que habitam em casas de barro, cujo fundamento está no pó, e que são esmagados como a traça!

[[v18-4-20]]

^<<v18-4-20,20>>^ Nascem de manhã e à tarde são destruídos; perecem para sempre, sem que ninguém se importe com isso.

[[v18-4-21]]

^<<v18-4-21,21>>^ Se o fio da vida lhes é cortado, morrem e não alcançam a sabedoria.’"

'''

xref:018-jo/018-jo-003.adoc#v18-3-0[&#60; Capítulo Anterior] | <<v18-4-0,Topo>> | xref:018-jo/018-jo-005.adoc#v18-5-0[Próximo Capítulo &#62;]