include::./index.adoc[]

[[v18-9-0]]
=== Jó, 9
// naa ?, NAA - Nova Almeida Atualizada

[[v18-9-1]]

^<<v18-9-1,1>>^ Então Jó respondeu:

[[v18-9-2]]

^<<v18-9-2,2>>^ "Na verdade, sei que assim é; porque, como pode o mortal ser justo diante de Deus?

[[v18-9-3]]

^<<v18-9-3,3>>^ Se quiser discutir com ele, nem a uma de mil coisas lhe poderá responder.

[[v18-9-4]]

^<<v18-9-4,4>>^ Ele é sábio de coração e grande em poder; quem ousou desafiá-lo e sobreviveu?

[[v18-9-5]]

^<<v18-9-5,5>>^ Ele é quem remove os montes, sem que saibam que na sua ira ele os transtorna.

[[v18-9-6]]

^<<v18-9-6,6>>^ Deus remove a terra do seu lugar, e faz as suas colunas estremecerem.

[[v18-9-7]]

^<<v18-9-7,7>>^ Ele dá uma ordem ao sol, e este não sai, e sela as estrelas.

[[v18-9-8]]

^<<v18-9-8,8>>^ Sozinho ele estende os céus e anda sobre as costas do mar.

[[v18-9-9]]

^<<v18-9-9,9>>^ Ele fez a Ursa Maior, o Órion, o Sete-estrelo e as constelações do Sul.

[[v18-9-10]]

^<<v18-9-10,10>>^ Deus faz coisas grandes e insondáveis, e maravilhas que não se podem enumerar.

[[v18-9-11]]

^<<v18-9-11,11>>^ Eis que ele passa por mim, e não o vejo; segue diante de mim, e não o percebo.

[[v18-9-12]]

^<<v18-9-12,12>>^ Eis que arrebata a presa! Quem o pode impedir? Quem lhe dirá: ‘O que estás fazendo?’

[[v18-9-13]]

^<<v18-9-13,13>>^ Deus não revogará a sua própria ira; debaixo dele se curvam os ajudantes do monstro Raabe."

[[v18-9-14]]

^<<v18-9-14,14>>^ "Como então poderei eu responder a ele? Como escolher as minhas palavras, para argumentar com ele?

[[v18-9-15]]

^<<v18-9-15,15>>^ Ainda que eu fosse justo, não lhe responderia; pelo contrário, pediria misericórdia ao meu Juiz.

[[v18-9-16]]

^<<v18-9-16,16>>^ Ainda que eu o chamasse e ele me respondesse, nem por isso eu creria que ele deu ouvidos à minha voz.

[[v18-9-17]]

^<<v18-9-17,17>>^ Porque me esmaga com uma tempestade e sem motivo multiplica as minhas feridas.

[[v18-9-18]]

^<<v18-9-18,18>>^ Não me permite respirar, porque me enche de amargura.

[[v18-9-19]]

^<<v18-9-19,19>>^ Se é uma questão de força, ele é o forte; se é uma questão de justiça, ele dirá: ‘Quem pode me intimar?’

[[v18-9-20]]

^<<v18-9-20,20>>^ Ainda que eu seja justo, a minha boca me condenará; embora eu seja íntegro, ela me declarará culpado.

[[v18-9-21]]

^<<v18-9-21,21>>^ Eu sou íntegro, mas não me importo comigo, não faço caso da minha vida.

[[v18-9-22]]

^<<v18-9-22,22>>^ Para mim, é tudo a mesma coisa; por isso, digo: ele destrói tanto os íntegros como os perversos.

[[v18-9-23]]

^<<v18-9-23,23>>^ Se um flagelo mata de repente, ele rirá do desespero dos inocentes.

[[v18-9-24]]

^<<v18-9-24,24>>^ A terra está entregue nas mãos dos ímpios, e Deus ainda cobre o rosto dos juízes. Se ele não é o causador disso, quem seria?"

[[v18-9-25]]

^<<v18-9-25,25>>^ "Os meus dias são mais velozes do que um corredor; fogem sem ter visto a felicidade.

[[v18-9-26]]

^<<v18-9-26,26>>^ Passam como barcos de junco, como a águia que se lança sobre a presa.

[[v18-9-27]]

^<<v18-9-27,27>>^ Se eu disser: ‘Vou esquecer a minha queixa, deixarei o meu ar triste e ficarei contente’;

[[v18-9-28]]

^<<v18-9-28,28>>^ ainda assim todas as minhas dores me apavoram, porque bem sei que não me considerarás inocente.

[[v18-9-29]]

^<<v18-9-29,29>>^ Eu serei condenado; por que, pois, trabalho em vão?

[[v18-9-30]]

^<<v18-9-30,30>>^ Ainda que me lave com água de neve e purifique as minhas mãos com sabão,

[[v18-9-31]]

^<<v18-9-31,31>>^ mesmo assim me submergirás no lodo, e as minhas próprias roupas terão nojo de mim.

[[v18-9-32]]

^<<v18-9-32,32>>^ Porque ele não é ser humano, como eu, a quem eu responda, se formos juntos ao tribunal.

[[v18-9-33]]

^<<v18-9-33,33>>^ Não há entre nós árbitro que ponha a mão sobre nós dois.

[[v18-9-34]]

^<<v18-9-34,34>>^ Que ele tire a sua vara de cima de mim, e que o seu terror não me amedronte!

[[v18-9-35]]

^<<v18-9-35,35>>^ Então falarei sem o temer; do contrário, eu não estaria em mim."

'''

xref:018-jo/018-jo-008.adoc#v18-8-0[&#60; Capítulo Anterior] | <<v18-9-0,Topo>> | xref:018-jo/018-jo-010.adoc#v18-10-0[Próximo Capítulo &#62;]