include::./index.adoc[]

[[v18-6-0]]
=== Jó, 6
// naa ?, NAA - Nova Almeida Atualizada

[[v18-6-1]]

^<<v18-6-1,1>>^ Então Jó respondeu:

[[v18-6-2]]

^<<v18-6-2,2>>^ "Ah! Se a minha queixa, de fato, pudesse ser pesada, e contra ela, numa balança, se pusesse a minha miséria,

[[v18-6-3]]

^<<v18-6-3,3>>^ esta, na verdade, pesaria mais que a areia dos mares. Por isso é que as minhas palavras foram precipitadas.

[[v18-6-4]]

^<<v18-6-4,4>>^ Porque as flechas do Todo-Poderoso estão cravadas em mim, e o meu espírito sorve o veneno delas; os terrores de Deus se armam contra mim.

[[v18-6-5]]

^<<v18-6-5,5>>^ Será que o jumento selvagem zurra quando está junto à relva? Ou será que o boi berra junto ao seu pasto?

[[v18-6-6]]

^<<v18-6-6,6>>^ Pode-se comer sem sal o que é insípido? Ou haverá sabor na clara do ovo?

[[v18-6-7]]

^<<v18-6-7,7>>^ Aquilo que a minha alma recusava tocar, isso é agora a minha comida repugnante."

[[v18-6-8]]

^<<v18-6-8,8>>^ "Quem dera que se cumprisse o meu pedido, e que Deus me concedesse o que desejo!

[[v18-6-9]]

^<<v18-6-9,9>>^ Que fosse do agrado de Deus esmagar-me, que soltasse a sua mão e acabasse comigo!

[[v18-6-10]]

^<<v18-6-10,10>>^ Isto ainda seria a minha consolação, e eu saltaria de contente na minha dor, que é implacável; porque não tenho negado as palavras do Santo.

[[v18-6-11]]

^<<v18-6-11,11>>^ Por que esperar, se já não tenho forças? Por que prolongar a vida, se o meu fim é certo?

[[v18-6-12]]

^<<v18-6-12,12>>^ Por acaso a minha força é a força da pedra? Ou é de bronze a minha carne?

[[v18-6-13]]

^<<v18-6-13,13>>^ Não encontro socorro em mim mesmo; foram afastados de mim os meus recursos."

[[v18-6-14]]

^<<v18-6-14,14>>^ "Ao aflito deve o amigo mostrar compaixão, mesmo ao que abandonou o temor do Todo-Poderoso.

[[v18-6-15]]

^<<v18-6-15,15>>^ Meus irmãos me enganaram; são como um ribeiro, como a torrente que transborda no vale,

[[v18-6-16]]

^<<v18-6-16,16>>^ turvada com o gelo e com a neve que nela se esconde,

[[v18-6-17]]

^<<v18-6-17,17>>^ torrente que seca quando o tempo aquece, e que no calor desaparece do seu lugar.

[[v18-6-18]]

^<<v18-6-18,18>>^ As caravanas se desviam dos seus caminhos, sobem para lugares desolados e perecem.

[[v18-6-19]]

^<<v18-6-19,19>>^ As caravanas de Temá procuram essa torrente, os viajantes de Sabá por ela suspiram.

[[v18-6-20]]

^<<v18-6-20,20>>^ Ficam envergonhados por terem confiado; quando chegam ali, ficam decepcionados.

[[v18-6-21]]

^<<v18-6-21,21>>^ Assim também vocês não me ajudaram em nada; veem os meus males e ficam com medo.

[[v18-6-22]]

^<<v18-6-22,22>>^ Por acaso pedi que me dessem recompensa? Ou que da riqueza de vocês me trouxessem algum presente?

[[v18-6-23]]

^<<v18-6-23,23>>^ Será que pedi que me livrassem do poder do opressor? Ou que me resgatassem das mãos dos tiranos?"

[[v18-6-24]]

^<<v18-6-24,24>>^ "Ensinem-me, e eu me calarei; mostrem-me em que tenho errado.

[[v18-6-25]]

^<<v18-6-25,25>>^ Como são persuasivas as palavras retas! Mas o que é que a repreensão de vocês repreende?

[[v18-6-26]]

^<<v18-6-26,26>>^ Por acaso vocês pensam em reprovar as minhas palavras, ditas por um desesperado ao vento?

[[v18-6-27]]

^<<v18-6-27,27>>^ Até sobre um órfão vocês lançariam sortes e seriam capazes de vender um amigo!

[[v18-6-28]]

^<<v18-6-28,28>>^ Agora, pois, tenham a bondade de olhar para mim e vejam que não estou mentindo na cara de vocês.

[[v18-6-29]]

^<<v18-6-29,29>>^ Por favor, mudem de parecer, e que não haja injustiça; mudem de parecer, e a justiça da minha causa triunfará.

[[v18-6-30]]

^<<v18-6-30,30>>^ Há iniquidade em meus lábios? Será que a minha boca não consegue discernir coisas perniciosas?"

'''

xref:018-jo/018-jo-005.adoc#v18-5-0[&#60; Capítulo Anterior] | <<v18-6-0,Topo>> | xref:018-jo/018-jo-007.adoc#v18-7-0[Próximo Capítulo &#62;]