include::./index.adoc[]

[[v18-38-0]]
=== Jó, 38
// naa ?, NAA - Nova Almeida Atualizada

[[v18-38-1]]

^<<v18-38-1,1>>^ Então, do meio de um redemoinho, o Senhor  respondeu a Jó e disse:

[[v18-38-2]]

^<<v18-38-2,2>>^ "Quem é este que obscurece os meus planos com palavras sem conhecimento?

[[v18-38-3]]

^<<v18-38-3,3>>^ Cinja os lombos como homem, pois eu lhe farei perguntas, e você me responderá."

[[v18-38-4]]

^<<v18-38-4,4>>^ "Onde você estava, quando eu lancei os fundamentos da terra? Responda, se você tem entendimento.

[[v18-38-5]]

^<<v18-38-5,5>>^ Quem determinou as medidas da terra, se é que você o sabe? Ou quem estendeu sobre ela uma linha de medir?

[[v18-38-6]]

^<<v18-38-6,6>>^ Sobre o que estão firmadas as suas bases ou quem lhe assentou a pedra angular,

[[v18-38-7]]

^<<v18-38-7,7>>^ quando as estrelas da alva, juntas, alegremente cantavam, e todos os filhos de Deus gritavam de alegria?"

[[v18-38-8]]

^<<v18-38-8,8>>^ "Ou quem encerrou o mar com portões, quando irrompeu do ventre,

[[v18-38-9]]

^<<v18-38-9,9>>^ quando eu lhe pus as nuvens por vestimenta e a escuridão por fraldas,

[[v18-38-10]]

^<<v18-38-10,10>>^ quando eu lhe tracei limites, e lhe pus ferrolhos e portas,

[[v18-38-11]]

^<<v18-38-11,11>>^ e disse: ‘Até aqui você pode chegar, mas deste ponto não passará. Aqui se quebrará o orgulho das suas ondas’?"

[[v18-38-12]]

^<<v18-38-12,12>>^ "Alguma vez na vida você deu ordens à madrugada ou mostrou ao amanhecer o seu lugar,

[[v18-38-13]]

^<<v18-38-13,13>>^ para que agarrasse a terra pelas extremidades e dela sacudisse os perversos?

[[v18-38-14]]

^<<v18-38-14,14>>^ A terra se modela como o barro debaixo do selo, e tudo se apresenta como um vestido.

[[v18-38-15]]

^<<v18-38-15,15>>^ Dos ímpios é retirada a sua luz, e o braço levantado para ferir se quebra."

[[v18-38-16]]

^<<v18-38-16,16>>^ "Você foi até as nascentes do mar ou percorreu o mais profundo do abismo?

[[v18-38-17]]

^<<v18-38-17,17>>^ Será que a você foram reveladas as portas da morte? Você viu essas portas da região tenebrosa?

[[v18-38-18]]

^<<v18-38-18,18>>^ Você tem noção clara da largura da terra? Responda, se você sabe tudo isso."

[[v18-38-19]]

^<<v18-38-19,19>>^ "Onde está o caminho para a morada da luz? E, quanto às trevas, onde é o seu lugar,

[[v18-38-20]]

^<<v18-38-20,20>>^ para que você as conduza ao seu território e conheça o caminho para a sua casa?

[[v18-38-21]]

^<<v18-38-21,21>>^ Você sabe isso, porque nesse tempo já era nascido e porque é grande o número dos seus dias!"

[[v18-38-22]]

^<<v18-38-22,22>>^ "Você alguma vez entrou nos depósitos da neve ou viu os reservatórios do granizo,

[[v18-38-23]]

^<<v18-38-23,23>>^ que eu guardo até o tempo da angústia, até o dia da batalha e da guerra?

[[v18-38-24]]

^<<v18-38-24,24>>^ Qual é o caminho para o lugar onde se difunde a luz e onde o vento leste se espalha sobre a terra?"

[[v18-38-25]]

^<<v18-38-25,25>>^ "Quem abriu canais para o aguaceiro ou caminho para os relâmpagos e trovões,

[[v18-38-26]]

^<<v18-38-26,26>>^ para fazer chover sobre a terra onde não há ninguém, e nos lugares desertos onde ninguém mora;

[[v18-38-27]]

^<<v18-38-27,27>>^ para dessedentar a terra deserta e assolada e para fazer crescer os renovos da erva?

[[v18-38-28]]

^<<v18-38-28,28>>^ Por acaso a chuva tem pai? Ou quem gera as gotas de orvalho?

[[v18-38-29]]

^<<v18-38-29,29>>^ De que ventre procede o gelo? E quem dá à luz a geada do céu?

[[v18-38-30]]

^<<v18-38-30,30>>^ As águas ficam duras como a pedra, e a superfície das profundezas se torna compacta."

[[v18-38-31]]

^<<v18-38-31,31>>^ "Será que você pode atar as correntes do Sete-estrelo ou soltar as cordas do Órion?

[[v18-38-32]]

^<<v18-38-32,32>>^ Você pode fazer aparecer as constelações a seu tempo ou guiar a Ursa Maior com os seus filhos?

[[v18-38-33]]

^<<v18-38-33,33>>^ Você conhece as leis que governam os céus, e pode estabelecer a sua influência sobre a terra?"

[[v18-38-34]]

^<<v18-38-34,34>>^ "Você é capaz de levantar a sua voz até as nuvens, para que a abundância das águas cubra você?

[[v18-38-35]]

^<<v18-38-35,35>>^ Você pode dar ordens aos relâmpagos, para que saiam e lhe digam: ‘Às suas ordens!’?

[[v18-38-36]]

^<<v18-38-36,36>>^ Quem pôs sabedoria no coração ou deu entendimento à mente?

[[v18-38-37]]

^<<v18-38-37,37>>^ Quem pode numerar com sabedoria as nuvens? Ou os cântaros dos céus, quem os pode despejar,

[[v18-38-38]]

^<<v18-38-38,38>>^ para que o pó se transforme em massa sólida, e os torrões se apeguem uns aos outros?"

[[v18-38-39]]

^<<v18-38-39,39>>^ "Será que é você que caça a presa para a leoa ou mata a fome dos leõezinhos,

[[v18-38-40]]

^<<v18-38-40,40>>^ quando se agacham nos covis e ficam à espreita nas suas covas?

[[v18-38-41]]

^<<v18-38-41,41>>^ Quem prepara o alimento para o corvo, quando os seus filhotes clamam a Deus e andam vagueando, por não terem o que comer?"

'''

xref:018-jo/018-jo-037.adoc#v18-37-0[&#60; Capítulo Anterior] | <<v18-38-0,Topo>> | xref:018-jo/018-jo-039.adoc#v18-39-0[Próximo Capítulo &#62;]