include::./index.adoc[]

[[v18-28-0]]
=== Jó, 28
// naa ?, NAA - Nova Almeida Atualizada

[[v18-28-1]]

^<<v18-28-1,1>>^ "Na verdade, a prata tem as suas minas, e o ouro, que se refina, tem o seu lugar.

[[v18-28-2]]

^<<v18-28-2,2>>^ O ferro é tirado da terra, e da pedra se funde o cobre.

[[v18-28-3]]

^<<v18-28-3,3>>^ Os homens põem termo à escuridão e até os últimos confins procuram as pedras ocultas nas trevas e na densa escuridão.

[[v18-28-4]]

^<<v18-28-4,4>>^ Abrem entrada para minas longe da habitação dos homens; são esquecidos pelos que passam por cima; e, assim, longe de todos, dependurados em cordas, balançam de um lado para outro.

[[v18-28-5]]

^<<v18-28-5,5>>^ Da terra procede o alimento, mas embaixo ela é revolvida como que pelo fogo.

[[v18-28-6]]

^<<v18-28-6,6>>^ Nas suas pedras se encontra safira, e há pó que contém ouro.

[[v18-28-7]]

^<<v18-28-7,7>>^ Essa vereda, a ave de rapina a ignora, e os olhos do falcão nunca a viram.

[[v18-28-8]]

^<<v18-28-8,8>>^ Feras majestosas nunca pisaram essa vereda, e nenhum leão passou por ali.

[[v18-28-9]]

^<<v18-28-9,9>>^ O homem estende a sua mão contra o rochedo e revolve os montes desde as suas raízes.

[[v18-28-10]]

^<<v18-28-10,10>>^ Abre canais nas pedras, e os seus olhos veem tudo o que há de mais precioso.

[[v18-28-11]]

^<<v18-28-11,11>>^ Tapa os veios de água, e nem uma gota sai deles; e traz à luz o que estava escondido."

[[v18-28-12]]

^<<v18-28-12,12>>^ "Mas onde se achará a sabedoria? E em que lugar estará o entendimento?

[[v18-28-13]]

^<<v18-28-13,13>>^ O ser humano não conhece o valor da sabedoria, e ela não se encontra na terra dos viventes.

[[v18-28-14]]

^<<v18-28-14,14>>^ O abismo diz: ‘Ela não está em mim.’ E o mar diz: ‘Não está comigo.’

[[v18-28-15]]

^<<v18-28-15,15>>^ Não se compra a sabedoria com ouro fino; ela também não pode ser paga com prata.

[[v18-28-16]]

^<<v18-28-16,16>>^ O seu valor não pode ser avaliado pelo ouro de Ofir, nem pelo precioso ônix, nem pela safira.

[[v18-28-17]]

^<<v18-28-17,17>>^ O ouro não se iguala a ela, nem o cristal; não se pode trocá-la por joias de ouro fino.

[[v18-28-18]]

^<<v18-28-18,18>>^ Ela faz esquecer o coral e o cristal; o preço da sabedoria é maior que o das pérolas.

[[v18-28-19]]

^<<v18-28-19,19>>^ O topázio da Etiópia não se compara com ela; não se compra a sabedoria nem com ouro puro.

[[v18-28-20]]

^<<v18-28-20,20>>^ Mas de onde vem a sabedoria? E em que lugar estará o entendimento?

[[v18-28-21]]

^<<v18-28-21,21>>^ Está encoberta aos olhos de todos os seres vivos, e oculta às aves do céu.

[[v18-28-22]]

^<<v18-28-22,22>>^ O abismo e a morte dizem: ‘Ouvimos com os nossos ouvidos a sua fama.’"

[[v18-28-23]]

^<<v18-28-23,23>>^ "Deus lhe entende o caminho, e ele é quem sabe o seu lugar.

[[v18-28-24]]

^<<v18-28-24,24>>^ Porque o seu olhar alcança as extremidades da terra; ele vê tudo o que há debaixo dos céus.

[[v18-28-25]]

^<<v18-28-25,25>>^ Quando Deus regulou o peso do vento e fixou a medida das águas;

[[v18-28-26]]

^<<v18-28-26,26>>^ quando determinou leis para a chuva e caminho para o relâmpago dos trovões,

[[v18-28-27]]

^<<v18-28-27,27>>^ então ele viu a sabedoria e a manifestou; estabeleceu-a e também a examinou.

[[v18-28-28]]

^<<v18-28-28,28>>^ E disse ao ser humano: ‘Eis que o temor do Senhor é a sabedoria, e afastar-se do mal é o entendimento.’"

'''

xref:018-jo/018-jo-027.adoc#v18-27-0[&#60; Capítulo Anterior] | <<v18-28-0,Topo>> | xref:018-jo/018-jo-029.adoc#v18-29-0[Próximo Capítulo &#62;]