include::./index.adoc[]

[[v18-8-0]]
=== Jó, 8
// naa ?, NAA - Nova Almeida Atualizada

[[v18-8-1]]

^<<v18-8-1,1>>^ Então Bildade, o suíta, tomou a palavra e disse:

[[v18-8-2]]

^<<v18-8-2,2>>^ "Até quando você falará estas coisas? E até quando as palavras da sua boca serão como um vento impetuoso?

[[v18-8-3]]

^<<v18-8-3,3>>^ Será que Deus perverteria o direito? Será que o Todo-Poderoso perverteria a justiça?

[[v18-8-4]]

^<<v18-8-4,4>>^ Se os seus filhos pecaram contra ele, também ele os entregou ao poder da transgressão que cometeram.

[[v18-8-5]]

^<<v18-8-5,5>>^ Mas, se você buscar a Deus e pedir misericórdia ao Todo-Poderoso,

[[v18-8-6]]

^<<v18-8-6,6>>^ se você for puro e reto, ele, sem demora, despertará para ajudá-lo e restaurará a justiça da sua morada.

[[v18-8-7]]

^<<v18-8-7,7>>^ O seu primeiro estado parecerá pequeno comparado com a grandeza do seu último estado."

[[v18-8-8]]

^<<v18-8-8,8>>^ "Por favor, pergunte agora aos que são de gerações passadas e atente para a experiência dos pais deles.

[[v18-8-9]]

^<<v18-8-9,9>>^ Porque nós somos de ontem e nada sabemos; pois os nossos dias sobre a terra são como a sombra.

[[v18-8-10]]

^<<v18-8-10,10>>^ Será que os pais não o ensinarão, falando com você? Será que do próprio entendimento não proferirão estas palavras?

[[v18-8-11]]

^<<v18-8-11,11>>^ ‘Pode o papiro crescer fora do pântano? Ou cresce o junco sem água?

[[v18-8-12]]

^<<v18-8-12,12>>^ Quando estão verdes, e ainda não foram colhidos, secam antes de qualquer outra erva.

[[v18-8-13]]

^<<v18-8-13,13>>^ São assim as veredas de todos os que se esquecem de Deus; e a esperança dos ímpios perecerá.

[[v18-8-14]]

^<<v18-8-14,14>>^ A sua firmeza será frustrada, e a sua confiança é teia de aranha.

[[v18-8-15]]

^<<v18-8-15,15>>^ Ele se encosta em sua casa, mas ela não resiste; agarra-se a ela, mas ela não fica em pé.’"

[[v18-8-16]]

^<<v18-8-16,16>>^ "Ele é viçoso diante do sol, e os seus renovos se espalham pelo jardim;

[[v18-8-17]]

^<<v18-8-17,17>>^ as suas raízes se entrelaçam num montão de pedras e penetram até as muralhas.

[[v18-8-18]]

^<<v18-8-18,18>>^ Mas, se o arrancam do seu lugar, este o negará, dizendo: ‘Eu nunca vi você.’

[[v18-8-19]]

^<<v18-8-19,19>>^ Eis no que deu a sua vida! E do pó brotarão outros."

[[v18-8-20]]

^<<v18-8-20,20>>^ "Eis que Deus não rejeita o íntegro, nem toma os malfeitores pela mão.

[[v18-8-21]]

^<<v18-8-21,21>>^ Ele encherá a sua boca de riso e os seus lábios de alegria.

[[v18-8-22]]

^<<v18-8-22,22>>^ Os que o odeiam se cobrirão de vergonha, e a tenda dos ímpios não subsistirá."

'''

xref:018-jo/018-jo-007.adoc#v18-7-0[&#60; Capítulo Anterior] | <<v18-8-0,Topo>> | xref:018-jo/018-jo-009.adoc#v18-9-0[Próximo Capítulo &#62;]