include::./index.adoc[]

[[v18-7-0]]
=== Jó, 7
// naa ?, NAA - Nova Almeida Atualizada

[[v18-7-1]]

^<<v18-7-1,1>>^ "Não é verdade que a vida do ser humano neste mundo é uma luta sem fim? Não são os seus dias como os de um trabalhador diarista?

[[v18-7-2]]

^<<v18-7-2,2>>^ Como o escravo que suspira pela sombra e como o trabalhador que espera pelo seu salário,

[[v18-7-3]]

^<<v18-7-3,3>>^ assim me deram por herança meses de desengano e me proporcionaram noites de aflição.

[[v18-7-4]]

^<<v18-7-4,4>>^ Ao deitar-me, pergunto: quando me levantarei? Mas a noite é longa, e estou farto de me virar na cama, até o amanhecer.

[[v18-7-5]]

^<<v18-7-5,5>>^ O meu corpo está vestido de vermes e de crostas terrosas; a minha pele racha e de novo forma pus.

[[v18-7-6]]

^<<v18-7-6,6>>^ Os meus dias são mais velozes do que a lançadeira do tecelão e se findam sem esperança.

[[v18-7-7]]

^<<v18-7-7,7>>^ Lembra-te, ó Deus, de que a minha vida é um sopro; os meus olhos não tornarão a ver a felicidade.

[[v18-7-8]]

^<<v18-7-8,8>>^ Os olhos de quem agora me vê não me verão mais; os teus olhos me procurarão, mas já terei desaparecido."

[[v18-7-9]]

^<<v18-7-9,9>>^ "Assim como a nuvem se desfaz e passa, aquele que desce à sepultura jamais voltará a subir.

[[v18-7-10]]

^<<v18-7-10,10>>^ Nunca mais voltará para a sua casa, e o lugar onde mora nunca mais o conhecerá.

[[v18-7-11]]

^<<v18-7-11,11>>^ Por isso, não reprimirei a minha boca. Na angústia do meu espírito, falarei; na amargura da minha alma, eu me queixarei.

[[v18-7-12]]

^<<v18-7-12,12>>^ Será que eu sou o mar ou algum monstro marinho, para que me ponhas sob guarda?

[[v18-7-13]]

^<<v18-7-13,13>>^ Quando digo: ‘O meu leito me consolará, a minha cama aliviará a minha queixa’,

[[v18-7-14]]

^<<v18-7-14,14>>^ então me assustas com sonhos e me atemorizas com visões.

[[v18-7-15]]

^<<v18-7-15,15>>^ Por isso, prefiro ser estrangulado; antes a morte do que esta tortura.

[[v18-7-16]]

^<<v18-7-16,16>>^ Estou farto da minha vida; não quero viver para sempre. Deixa-me em paz, porque os meus dias são um sopro."

[[v18-7-17]]

^<<v18-7-17,17>>^ "Que é o homem, para que tu lhe dês tanta importância, para que dês a ele atenção,

[[v18-7-18]]

^<<v18-7-18,18>>^ para que a cada manhã o visites, e que a cada momento o ponhas à prova?

[[v18-7-19]]

^<<v18-7-19,19>>^ Até quando não desviarás de mim o teu olhar? Até quando não me darás tempo de engolir a minha saliva?

[[v18-7-20]]

^<<v18-7-20,20>>^ Se pequei, que mal fiz a ti, ó Espreitador da humanidade? Por que fizeste de mim o teu alvo, tornando-me um peso para mim mesmo?

[[v18-7-21]]

^<<v18-7-21,21>>^ Por que não perdoas a minha transgressão e não tiras a minha iniquidade? Pois agora me deitarei no pó; e, se me procuras, já terei desaparecido."

'''

xref:018-jo/018-jo-006.adoc#v18-6-0[&#60; Capítulo Anterior] | <<v18-7-0,Topo>> | xref:018-jo/018-jo-008.adoc#v18-8-0[Próximo Capítulo &#62;]