include::./index.adoc[]

[[v18-3-0]]
=== Jó, 3
// naa ?, NAA - Nova Almeida Atualizada

[[v18-3-1]]

^<<v18-3-1,1>>^ Depois disto, Jó passou a falar e amaldiçoou o dia do seu nascimento.

[[v18-3-2]]

^<<v18-3-2,2>>^ Jó disse:

[[v18-3-3]]

^<<v18-3-3,3>>^ "Pereça o dia em que nasci e a noite em que se disse: ‘Foi concebido um homem!’

[[v18-3-4]]

^<<v18-3-4,4>>^ Que aquele dia se transforme em trevas, e Deus, lá de cima, não se importe com ele, nem resplandeça sobre ele a luz.

[[v18-3-5]]

^<<v18-3-5,5>>^ Que as trevas e a sombra da morte se apoderem desse dia; que uma nuvem habite sobre ele; que tudo o que pode escurecer o dia o espante.

[[v18-3-6]]

^<<v18-3-6,6>>^ Aquela noite, que dela se apoderem densas trevas; que ela não se alegre entre os dias do ano, nem entre na conta dos meses.

[[v18-3-7]]

^<<v18-3-7,7>>^ Sim, que seja estéril aquela noite, e dela sejam banidos os gritos de alegria.

[[v18-3-8]]

^<<v18-3-8,8>>^ Amaldiçoem-na aqueles que sabem amaldiçoar o dia e sabem instigar o Leviatã.

[[v18-3-9]]

^<<v18-3-9,9>>^ Escureçam-se as estrelas do seu alvorecer; que a noite espere a luz, e a luz não venha; que não veja o despontar da alvorada,

[[v18-3-10]]

^<<v18-3-10,10>>^ pois não fechou as portas do ventre da minha mãe, nem escondeu dos meus olhos o sofrimento."

[[v18-3-11]]

^<<v18-3-11,11>>^ "Por que não morri ao nascer? Por que não expirei ao sair do ventre de minha mãe?

[[v18-3-12]]

^<<v18-3-12,12>>^ Por que houve um colo que me acolhesse, e seios, para que eu mamasse?

[[v18-3-13]]

^<<v18-3-13,13>>^ Porque agora eu repousaria tranquilo; dormiria, e então haveria para mim descanso,

[[v18-3-14]]

^<<v18-3-14,14>>^ com os reis e conselheiros da terra que construíram para si mausoléus;

[[v18-3-15]]

^<<v18-3-15,15>>^ ou com os príncipes que tinham ouro e encheram as suas casas de prata;

[[v18-3-16]]

^<<v18-3-16,16>>^ ou, como aborto oculto, eu não existiria, como crianças que nunca viram a luz.

[[v18-3-17]]

^<<v18-3-17,17>>^ Ali os maus cessam de perturbar, e ali repousam os cansados.

[[v18-3-18]]

^<<v18-3-18,18>>^ Ali os presos juntamente repousam e não ouvem a voz do capataz.

[[v18-3-19]]

^<<v18-3-19,19>>^ Ali está tanto o pequeno como o grande, e o servo fica livre de seu senhor."

[[v18-3-20]]

^<<v18-3-20,20>>^ "Por que se concede luz ao miserável e vida aos de coração amargurado,

[[v18-3-21]]

^<<v18-3-21,21>>^ que esperam a morte, e ela não vem, que cavam em procura dela mais do que tesouros ocultos,

[[v18-3-22]]

^<<v18-3-22,22>>^ que se alegrariam por um túmulo e exultariam se achassem a sepultura?

[[v18-3-23]]

^<<v18-3-23,23>>^ Por que se concede luz ao homem cujo caminho é oculto, e a quem Deus cercou de todos os lados?"

[[v18-3-24]]

^<<v18-3-24,24>>^ "Porque em vez do meu pão me vêm gemidos, e os meus lamentos se derramam como água.

[[v18-3-25]]

^<<v18-3-25,25>>^ Aquilo que temo me sobrevém, e o que receio me acontece.

[[v18-3-26]]

^<<v18-3-26,26>>^ Não tenho descanso, não tenho sossego, não tenho repouso; só tenho inquietação."

'''

xref:018-jo/018-jo-002.adoc#v18-2-0[&#60; Capítulo Anterior] | <<v18-3-0,Topo>> | xref:018-jo/018-jo-004.adoc#v18-4-0[Próximo Capítulo &#62;]