include::./index.adoc[]

[[v18-42-0]]
=== Jó, 42
// naa ?, NAA - Nova Almeida Atualizada

[[v18-42-1]]

^<<v18-42-1,1>>^ Então Jó respondeu ao Senhor  e disse:

[[v18-42-2]]

^<<v18-42-2,2>>^ "Bem sei que tudo podes, e nenhum dos teus planos pode ser frustrado.

[[v18-42-3]]

^<<v18-42-3,3>>^ Tu perguntaste: ‘Quem é este que, sem conhecimento, encobre os meus planos?’ Na verdade, falei do que eu não entendia, coisas que são maravilhosas demais para mim, coisas que eu não conhecia.

[[v18-42-4]]

^<<v18-42-4,4>>^ Disseste: ‘Escute, porque eu vou falar; farei perguntas, e você me responderá.’

[[v18-42-5]]

^<<v18-42-5,5>>^ Eu te conhecia só de ouvir, mas agora os meus olhos te veem.

[[v18-42-6]]

^<<v18-42-6,6>>^ Por isso, me abomino e me arrependo no pó e na cinza."

[[v18-42-7]]

^<<v18-42-7,7>>^ Depois que o Senhor  falou estas palavras a Jó, o Senhor  disse também a Elifaz, o temanita: — A minha ira se acendeu contra você e contra os seus dois amigos, porque vocês não falaram a meu respeito o que é reto, como o meu servo Jó falou.

[[v18-42-8]]

^<<v18-42-8,8>>^ Agora peguem sete novilhos e sete carneiros, e vão até o meu servo Jó, e ofereçam holocaustos em favor de vocês. O meu servo Jó orará por vocês, e eu aceitarei a intercessão dele, para que eu não os trate segundo a falta de juízo de vocês. Porque vocês não falaram a meu respeito o que é reto, como o meu servo Jó falou.

[[v18-42-9]]

^<<v18-42-9,9>>^ Então Elifaz, o temanita, Bildade, o suíta, e Zofar, o naamatita, foram e fizeram o que o Senhor  lhes havia ordenado; e o Senhor  aceitou a oração de Jó.

[[v18-42-10]]

^<<v18-42-10,10>>^ O Senhor  restaurou a sorte de Jó, quando este orou pelos seus amigos, e o Senhor  lhe deu o dobro de tudo o que tinha tido antes.

[[v18-42-11]]

^<<v18-42-11,11>>^ Então vieram a ele todos os seus irmãos, todas as suas irmãs e todos os que o haviam conhecido antes, e comeram com ele em sua casa. E se condoeram dele, e o consolaram por todo o mal que o Senhor  tinha enviado sobre ele. E cada um lhe deu dinheiro e um anel de ouro.

[[v18-42-12]]

^<<v18-42-12,12>>^ O Senhor  abençoou o último estado de Jó mais do que o primeiro. Ele veio a ter catorze mil ovelhas, seis mil camelos, mil juntas de bois e mil jumentas.

[[v18-42-13]]

^<<v18-42-13,13>>^ Também teve outros sete filhos e três filhas.

[[v18-42-14]]

^<<v18-42-14,14>>^ À primeira filha deu o nome de Jemima; à segunda chamou de Quézia; e à terceira, Quéren-Hapuque.

[[v18-42-15]]

^<<v18-42-15,15>>^ Em toda aquela terra não havia mulheres tão bonitas como as filhas de Jó; e seu pai lhes deu herança entre seus irmãos.

[[v18-42-16]]

^<<v18-42-16,16>>^ Depois disto, Jó viveu mais cento e quarenta anos; e viu os seus filhos e os filhos de seus filhos, até a quarta geração.

[[v18-42-17]]

^<<v18-42-17,17>>^ E assim Jó morreu, após uma longa velhice.

'''

xref:018-jo/018-jo-041.adoc#v18-41-0[&#60; Capítulo Anterior] | <<v18-42-0,Topo>> | xref:019-salmos/019-salmos-001.adoc#v19-1-0[Próximo Capítulo &#62;]