include::./index.adoc[]

[[v18-5-0]]
=== Jó, 5
// naa ?, NAA - Nova Almeida Atualizada

[[v18-5-1]]

^<<v18-5-1,1>>^ "Grite agora, para ver se há quem responda! E para qual dos santos anjos você se voltará?

[[v18-5-2]]

^<<v18-5-2,2>>^ Porque a ira mata o insensato, e a inveja destrói o tolo.

[[v18-5-3]]

^<<v18-5-3,3>>^ Eu mesmo vi o insensato lançar raízes, mas logo declarei maldita a sua habitação.

[[v18-5-4]]

^<<v18-5-4,4>>^ Os filhos dele estão longe do socorro; são espezinhados nos tribunais, e não há quem os livre.

[[v18-5-5]]

^<<v18-5-5,5>>^ A sua colheita, o faminto a devora, arrebatando até o que se encontra no meio de espinhos; e o sedento suga os seus bens.

[[v18-5-6]]

^<<v18-5-6,6>>^ Porque a aflição não vem do pó, e o sofrimento não brota do chão.

[[v18-5-7]]

^<<v18-5-7,7>>^ Mas o ser humano nasce para o sofrimento, como as faíscas das brasas voam para cima."

[[v18-5-8]]

^<<v18-5-8,8>>^ "Quanto a mim, eu buscaria a Deus e a ele entregaria a minha causa.

[[v18-5-9]]

^<<v18-5-9,9>>^ Deus faz coisas grandes e insondáveis, maravilhas que não se podem enumerar.

[[v18-5-10]]

^<<v18-5-10,10>>^ Faz chover sobre a terra e envia águas sobre os campos.

[[v18-5-11]]

^<<v18-5-11,11>>^ Põe os abatidos num lugar alto e conduz os enlutados a um lugar seguro.

[[v18-5-12]]

^<<v18-5-12,12>>^ Deus frustra os planos dos astutos, para que não possam realizar seus projetos.

[[v18-5-13]]

^<<v18-5-13,13>>^ Ele apanha os sábios na própria astúcia deles, e o conselho dos que tramam não chega a vingar.

[[v18-5-14]]

^<<v18-5-14,14>>^ De dia eles encontram as trevas, e ao meio-dia andam tateando como se fosse noite.

[[v18-5-15]]

^<<v18-5-15,15>>^ Porém Deus salva da espada que lhes sai da boca, salva os necessitados das mãos dos poderosos.

[[v18-5-16]]

^<<v18-5-16,16>>^ Assim, há esperança para os pobres, e a iniquidade tapa a sua própria boca."

[[v18-5-17]]

^<<v18-5-17,17>>^ "Bem-aventurado é aquele a quem Deus disciplina! Portanto, não despreze a disciplina do Todo-Poderoso.

[[v18-5-18]]

^<<v18-5-18,18>>^ Porque ele faz a ferida e ele mesmo a faz sarar; ele fere, e as suas mãos curam.

[[v18-5-19]]

^<<v18-5-19,19>>^ De seis angústias ele o livrará, e na sétima o mal não tocará em você.

[[v18-5-20]]

^<<v18-5-20,20>>^ Na fome ele livrará você da morte; na guerra, do poder da espada.

[[v18-5-21]]

^<<v18-5-21,21>>^ Você estará abrigado do açoite da língua e, quando vier a destruição, não ficará com medo.

[[v18-5-22]]

^<<v18-5-22,22>>^ Da destruição e da fome você dará risada e dos animais da terra não terá medo.

[[v18-5-23]]

^<<v18-5-23,23>>^ Porque com as pedras do campo você fará aliança, e os animais selvagens viverão em paz com você.

[[v18-5-24]]

^<<v18-5-24,24>>^ Saberá que a sua tenda está em paz; percorrerá as suas posses e não achará falta de nada.

[[v18-5-25]]

^<<v18-5-25,25>>^ Saberá que a sua descendência se multiplicará, e que a sua posteridade será como a erva da terra.

[[v18-5-26]]

^<<v18-5-26,26>>^ Em robusta velhice você descerá à sepultura, como se recolhe o feixe de trigo no tempo certo.

[[v18-5-27]]

^<<v18-5-27,27>>^ Veja bem! Isto é o que investigamos, e assim é. Ouça e medite nisso para o seu bem."

'''

xref:018-jo/018-jo-004.adoc#v18-4-0[&#60; Capítulo Anterior] | <<v18-5-0,Topo>> | xref:018-jo/018-jo-006.adoc#v18-6-0[Próximo Capítulo &#62;]