include::./index.adoc[]

[[v18-14-0]]
=== Jó, 14
// naa ?, NAA - Nova Almeida Atualizada

[[v18-14-1]]

^<<v18-14-1,1>>^ "O ser humano, nascido de mulher, vive breve tempo, cheio de inquietação.

[[v18-14-2]]

^<<v18-14-2,2>>^ Nasce como a flor e murcha; foge como a sombra e não permanece.

[[v18-14-3]]

^<<v18-14-3,3>>^ Sobre ele abres os teus olhos? E me fazes entrar em juízo contigo?

[[v18-14-4]]

^<<v18-14-4,4>>^ Quem poderá tirar coisa pura daquilo que é impuro? Ninguém!

[[v18-14-5]]

^<<v18-14-5,5>>^ Visto que os dias do ser humano estão contados, o número dos seus meses está nas tuas mãos; traçaste limites além dos quais não passará.

[[v18-14-6]]

^<<v18-14-6,6>>^ Desvia dele o teu olhar, para que tenha repouso, até que, como o trabalhador, tenha prazer no seu dia."

[[v18-14-7]]

^<<v18-14-7,7>>^ "Porque há esperança para a árvore, pois, mesmo cortada, voltará a brotar, e não cessarão os seus rebentos.

[[v18-14-8]]

^<<v18-14-8,8>>^ Se as suas raízes envelhecerem na terra, e o seu tronco morrer no chão,

[[v18-14-9]]

^<<v18-14-9,9>>^ ao cheiro das águas brotará e dará ramos como a planta nova.

[[v18-14-10]]

^<<v18-14-10,10>>^ Mas, se alguém morre, fica prostrado; o ser humano expira e para onde vai?"

[[v18-14-11]]

^<<v18-14-11,11>>^ "Como as águas do lago evaporam, e o rio se esgota e seca,

[[v18-14-12]]

^<<v18-14-12,12>>^ assim o ser humano se deita e não se levanta; enquanto existirem os céus, não acordará, nem será despertado do seu sono."

[[v18-14-13]]

^<<v18-14-13,13>>^ "Quem dera me escondesses na sepultura e me ocultasses até que a tua ira passasse! Quem dera me fixasses um prazo e depois te lembrasses de mim!

[[v18-14-14]]

^<<v18-14-14,14>>^ Quando alguém morre, será que volta a viver? Todos os dias da minha luta esperaria, até que viesse a minha mudança.

[[v18-14-15]]

^<<v18-14-15,15>>^ Tu me chamarias, e eu te responderia; terias saudades da obra das tuas mãos;

[[v18-14-16]]

^<<v18-14-16,16>>^ e até contarias os meus passos e não levarias em conta os meus pecados.

[[v18-14-17]]

^<<v18-14-17,17>>^ A minha transgressão estaria selada num saco, e terias encoberto as minhas iniquidades."

[[v18-14-18]]

^<<v18-14-18,18>>^ "Mas como o monte que desmorona e se desfaz, e a rocha que se move do seu lugar,

[[v18-14-19]]

^<<v18-14-19,19>>^ como as águas gastam as pedras, e as cheias levam o pó da terra, assim destróis a esperança humana.

[[v18-14-20]]

^<<v18-14-20,20>>^ Tu prevaleces para sempre contra o ser humano, e ele passa; mudas o semblante dele e o despedes.

[[v18-14-21]]

^<<v18-14-21,21>>^ Os seus filhos recebem honras, e ele não sabe; são humilhados, e ele não percebe.

[[v18-14-22]]

^<<v18-14-22,22>>^ Ele sente as dores apenas de seu próprio corpo, e a sua alma lamenta apenas por si mesma."

'''

xref:018-jo/018-jo-013.adoc#v18-13-0[&#60; Capítulo Anterior] | <<v18-14-0,Topo>> | xref:018-jo/018-jo-015.adoc#v18-15-0[Próximo Capítulo &#62;]