include::./index.adoc[]

[[v18-39-0]]
=== Jó, 39
// naa ?, NAA - Nova Almeida Atualizada

[[v18-39-1]]

^<<v18-39-1,1>>^ "Você sabe o tempo em que as cabras-monteses têm os filhos ou cuidou das corças quando dão suas crias?

[[v18-39-2]]

^<<v18-39-2,2>>^ Pode contar os meses que cumprem? Ou sabe o tempo do seu parto?

[[v18-39-3]]

^<<v18-39-3,3>>^ Elas se encurvam para terem seus filhos, e lançam de si as suas dores.

[[v18-39-4]]

^<<v18-39-4,4>>^ Seus filhos se tornam robustos, crescem no campo aberto, saem e nunca mais voltam para elas.

[[v18-39-5]]

^<<v18-39-5,5>>^ Quem pôs em liberdade o jumento selvagem? Quem soltou as suas cordas?

[[v18-39-6]]

^<<v18-39-6,6>>^ Eu lhe dei o deserto por casa e a terra salgada por morada.

[[v18-39-7]]

^<<v18-39-7,7>>^ Ele se ri do tumulto da cidade, não ouve os gritos do guia.

[[v18-39-8]]

^<<v18-39-8,8>>^ Os montes são o lugar do seu pasto, e anda à procura de tudo o que está verde.

[[v18-39-9]]

^<<v18-39-9,9>>^ Será que o boi selvagem aceitará trabalhar para você? Será que ele passará a noite junto da sua manjedoura?

[[v18-39-10]]

^<<v18-39-10,10>>^ Por acaso você consegue prendê-lo ao arado com cordas? Ou irá ele atrás de você para desfazer os torrões nos campos do vale?

[[v18-39-11]]

^<<v18-39-11,11>>^ Você vai confiar nele, por causa da grande força que ele tem, ou deixará o seu trabalho por conta dele?

[[v18-39-12]]

^<<v18-39-12,12>>^ Você acredita que ele trará para casa o que você semeou e o recolherá na sua eira?"

[[v18-39-13]]

^<<v18-39-13,13>>^ "A avestruz bate alegre as asas, como se tivesse asas e plumagem de cegonha.

[[v18-39-14]]

^<<v18-39-14,14>>^ Ela põe os seus ovos no chão e deixa que sejam chocados na areia,

[[v18-39-15]]

^<<v18-39-15,15>>^ e se esquece de que algum pé os pode esmagar ou de que os animais do campo podem pisá-los.

[[v18-39-16]]

^<<v18-39-16,16>>^ Trata com dureza os seus filhos, como se não fossem seus. Embora seja em vão o seu trabalho, ela está tranquila,

[[v18-39-17]]

^<<v18-39-17,17>>^ porque Deus lhe negou sabedoria e não lhe deu entendimento.

[[v18-39-18]]

^<<v18-39-18,18>>^ Mas, quando de um salto se levanta para correr, ri do cavalo e do cavaleiro."

[[v18-39-19]]

^<<v18-39-19,19>>^ "Por acaso foi você quem deu força ao cavalo ou revestiu o seu pescoço de crinas?

[[v18-39-20]]

^<<v18-39-20,20>>^ É você quem o faz pular como gafanhoto? Terrível é o fogoso respirar das suas ventas.

[[v18-39-21]]

^<<v18-39-21,21>>^ Escarva no vale, satisfeito com a sua força, e sai ao encontro dos inimigos.

[[v18-39-22]]

^<<v18-39-22,22>>^ Zomba do medo e não se espanta; não recua por causa da espada.

[[v18-39-23]]

^<<v18-39-23,23>>^ Sobre ele balança a aljava, cintila a lança e o dardo.

[[v18-39-24]]

^<<v18-39-24,24>>^ Com ímpeto e fúria vai engolindo as distâncias e não se contém ao som do clarim.

[[v18-39-25]]

^<<v18-39-25,25>>^ A cada toque do clarim ele diz: ‘Avante!’ Cheira de longe a batalha, o grito dos comandantes e o alarido de guerra."

[[v18-39-26]]

^<<v18-39-26,26>>^ "Será que é pela inteligência que você tem que o falcão voa, estendendo as suas asas para o Sul?

[[v18-39-27]]

^<<v18-39-27,27>>^ Ou é por uma ordem sua que a águia sobe e faz o seu ninho lá no alto?

[[v18-39-28]]

^<<v18-39-28,28>>^ Ela mora no penhasco onde faz a sua morada, no alto do penhasco, em lugar seguro.

[[v18-39-29]]

^<<v18-39-29,29>>^ Dali, descobre a presa; seus olhos a avistam de longe.

[[v18-39-30]]

^<<v18-39-30,30>>^ Seus filhotes chupam sangue; onde há mortos, ali ela está."

'''

xref:018-jo/018-jo-038.adoc#v18-38-0[&#60; Capítulo Anterior] | <<v18-39-0,Topo>> | xref:018-jo/018-jo-040.adoc#v18-40-0[Próximo Capítulo &#62;]