include::./index.adoc[]

[[v18-1-0]]
=== Jó, 1
// naa ?, NAA - Nova Almeida Atualizada

[[v18-1-1]]

^<<v18-1-1,1>>^ Havia um homem na terra de Uz cujo nome era Jó. Este homem era íntegro e reto, temia a Deus e se desviava do mal.

[[v18-1-2]]

^<<v18-1-2,2>>^ Nasceram-lhe sete filhos e três filhas.

[[v18-1-3]]

^<<v18-1-3,3>>^ Tinha sete mil ovelhas, três mil camelos, quinhentas juntas de bois e quinhentas jumentas. Também tinha muitíssima gente a seu serviço, de maneira que este homem era o maior de todos os do Oriente.

[[v18-1-4]]

^<<v18-1-4,4>>^ Os filhos dele iam às casas uns dos outros e faziam banquetes, cada um por sua vez, e mandavam convidar as suas três irmãs a comerem e beberem com eles.

[[v18-1-5]]

^<<v18-1-5,5>>^ Quando se encerrava um ciclo de banquetes, Jó chamava os seus filhos e os santificava; levantava-se de madrugada e oferecia holocaustos segundo o número de todos eles. Pois Jó pensava assim: "Talvez os meus filhos tenham pecado e blasfemado contra Deus em seu coração." Jó fazia isso continuamente.

[[v18-1-6]]

^<<v18-1-6,6>>^ Num dia em que os filhos de Deus vieram apresentar-se diante do Senhor , veio também Satanás entre eles.

[[v18-1-7]]

^<<v18-1-7,7>>^ Então o Senhor  perguntou a Satanás: — De onde você vem? Satanás respondeu ao Senhor : — De rodear a terra e passear por ela.

[[v18-1-8]]

^<<v18-1-8,8>>^ E o Senhor  disse a Satanás: — Você reparou no meu servo Jó? Não há ninguém como ele na terra. Ele é um homem íntegro e reto, que teme a Deus e se desvia do mal.

[[v18-1-9]]

^<<v18-1-9,9>>^ Então Satanás respondeu ao Senhor : — Será que é sem motivo que Jó teme a Deus?

[[v18-1-10]]

^<<v18-1-10,10>>^ Não é verdade que tu mesmo puseste uma cerca ao redor dele, da sua casa e de tudo o que ele tem? Abençoaste a obra de suas mãos, e os seus bens se multiplicaram na terra.

[[v18-1-11]]

^<<v18-1-11,11>>^ Mas estende a tua mão e toca em tudo o que ele tem, para ver se ele não blasfema contra ti na tua face.

[[v18-1-12]]

^<<v18-1-12,12>>^ Então o Senhor  disse a Satanás: — Você pode fazer o que quiser com tudo o que ele tem; só não estenda a mão contra ele. Então Satanás saiu da presença do Senhor .

[[v18-1-13]]

^<<v18-1-13,13>>^ Um dia, quando os filhos e as filhas de Jó comiam e bebiam vinho na casa do irmão mais velho,

[[v18-1-14]]

^<<v18-1-14,14>>^ veio um mensageiro a Jó e lhe disse: — Os bois estavam lavrando e as jumentas estavam pastando junto a eles.

[[v18-1-15]]

^<<v18-1-15,15>>^ De repente, os sabeus atacaram e levaram tudo. Mataram os servos a fio de espada. Só eu consegui escapar, para trazer a notícia.

[[v18-1-16]]

^<<v18-1-16,16>>^ Enquanto este ainda falava, veio outro mensageiro e disse: — Fogo de Deus caiu do céu e queimou as ovelhas e os servos, destruindo todos eles. Só eu consegui escapar, para trazer a notícia.

[[v18-1-17]]

^<<v18-1-17,17>>^ Enquanto este ainda falava, veio outro mensageiro e disse: — Os caldeus se dividiram em três bandos, atacaram os camelos e os levaram embora. Mataram os servos a fio de espada. Só eu consegui escapar, para trazer a notícia.

[[v18-1-18]]

^<<v18-1-18,18>>^ Também este ainda falava quando veio outro e disse: — Os seus filhos e as suas filhas estavam comendo e bebendo vinho na casa do irmão mais velho.

[[v18-1-19]]

^<<v18-1-19,19>>^ De repente, eis que se levantou um vento muito forte do lado do deserto e bateu contra os quatro cantos da casa. Ela caiu sobre os jovens, e eles morreram. Só eu consegui escapar, para trazer a notícia.

[[v18-1-20]]

^<<v18-1-20,20>>^ Então Jó se levantou, rasgou o seu manto, rapou a cabeça, prostrou-se em terra e adorou.

[[v18-1-21]]

^<<v18-1-21,21>>^ E disse: — Nu saí do ventre de minha mãe e nu voltarei. O Senhor  o deu e o Senhor  o tomou; bendito seja o nome do Senhor !

[[v18-1-22]]

^<<v18-1-22,22>>^ Em tudo isto Jó não pecou, nem atribuiu a Deus falta alguma.

'''

xref:017-ester/017-ester-010.adoc#v17-10-0[&#60; Capítulo Anterior] | <<v18-1-0,Topo>> | xref:018-jo/018-jo-002.adoc#v18-2-0[Próximo Capítulo &#62;]