include::./index.adoc[]

[[v54-2-0]]
=== 1 Timóteo, 2
// naa ?, NAA - Nova Almeida Atualizada

[[v54-2-1]]

^<<v54-2-1,1>>^ Antes de tudo, peço que se façam súplicas, orações, intercessões e ações de graças em favor de todas as pessoas.

[[v54-2-2]]

^<<v54-2-2,2>>^ Orem em favor dos reis e de todos os que exercem autoridade, para que vivamos vida mansa e tranquila, com toda piedade e respeito.

[[v54-2-3]]

^<<v54-2-3,3>>^ Isto é bom e aceitável diante de Deus, nosso Salvador,

[[v54-2-4]]

^<<v54-2-4,4>>^ que deseja que todos sejam salvos e cheguem ao pleno conhecimento da verdade.

[[v54-2-5]]

^<<v54-2-5,5>>^ Porque há um só Deus e um só Mediador entre Deus e a humanidade, Cristo Jesus, homem,

[[v54-2-6]]

^<<v54-2-6,6>>^ que deu a si mesmo em resgate por todos, testemunho que se deve dar em tempos oportunos.

[[v54-2-7]]

^<<v54-2-7,7>>^ Para isto fui designado pregador e apóstolo — afirmo a verdade, não minto —, mestre dos gentios na fé e na verdade.

[[v54-2-8]]

^<<v54-2-8,8>>^ Quero, pois, que os homens orem em todos os lugares, levantando mãos santas, sem ira e sem animosidade.

[[v54-2-9]]

^<<v54-2-9,9>>^ Da mesma forma, que as mulheres, em traje decente, se enfeitem com modéstia e bom senso, não com tranças no cabelo, ouro, pérolas ou roupas caras,

[[v54-2-10]]

^<<v54-2-10,10>>^ porém com boas obras, como convém a mulheres que professam ser piedosas.

[[v54-2-11]]

^<<v54-2-11,11>>^ A mulher aprenda em silêncio, com toda a submissão.

[[v54-2-12]]

^<<v54-2-12,12>>^ E não permito que a mulher ensine, nem que exerça autoridade sobre o homem; esteja, porém, em silêncio.

[[v54-2-13]]

^<<v54-2-13,13>>^ Porque primeiro foi formado Adão, depois Eva.

[[v54-2-14]]

^<<v54-2-14,14>>^ E Adão não foi iludido, mas a mulher, sendo enganada, caiu em transgressão.

[[v54-2-15]]

^<<v54-2-15,15>>^ Mas ela será salva tendo filhos, se permanecer em fé, amor e santificação, com bom senso.

'''

xref:054-1-timoteo/054-1-timoteo-001.adoc#v54-1-0[&#60; Capítulo Anterior] | <<v54-2-0,Topo>> | xref:054-1-timoteo/054-1-timoteo-003.adoc#v54-3-0[Próximo Capítulo &#62;]