include::./index.adoc[]

[[v54-5-0]]
=== 1 Timóteo, 5
// naa ?, NAA - Nova Almeida Atualizada

[[v54-5-1]]

^<<v54-5-1,1>>^ Não repreenda um homem mais velho; pelo contrário, exorte-o como você faria com o seu pai. Trate os mais jovens como irmãos,

[[v54-5-2]]

^<<v54-5-2,2>>^ as mulheres mais velhas, como mães, e as mais jovens, como irmãs, com toda a pureza.

[[v54-5-3]]

^<<v54-5-3,3>>^ Honre as viúvas que não têm ninguém para cuidar delas.

[[v54-5-4]]

^<<v54-5-4,4>>^ Mas, se alguma viúva tem filhos ou netos, que estes aprendam primeiro a exercer piedade para com a própria casa e a recompensar os seus pais, pois isto é aceitável diante de Deus.

[[v54-5-5]]

^<<v54-5-5,5>>^ Aquela que é viúva de fato e não tem ninguém para cuidar dela espera em Deus e persevera em súplicas e orações, noite e dia.

[[v54-5-6]]

^<<v54-5-6,6>>^ Entretanto, a que se entrega aos prazeres, mesmo viva, está morta.

[[v54-5-7]]

^<<v54-5-7,7>>^ Ordene estas coisas, para que sejam irrepreensíveis.

[[v54-5-8]]

^<<v54-5-8,8>>^ Se alguém não tem cuidado dos seus e, especialmente, dos da própria casa, esse negou a fé e é pior do que o descrente.

[[v54-5-9]]

^<<v54-5-9,9>>^ Somente poderá ser incluída na lista de viúvas aquela que tiver mais de sessenta anos, que tiver sido esposa de um só marido

[[v54-5-10]]

^<<v54-5-10,10>>^ e que seja recomendada pelo testemunho de boas obras: se criou filhos, se exercitou hospitalidade, se lavou os pés dos santos, se socorreu os atribulados, se viveu na prática zelosa de todo tipo de boa obra.

[[v54-5-11]]

^<<v54-5-11,11>>^ Mas não inclua na lista viúvas mais novas, porque, quando seus desejos fazem com que se afastem de Cristo, querem casar,

[[v54-5-12]]

^<<v54-5-12,12>>^ tornando-se condenáveis por anularem o seu primeiro compromisso.

[[v54-5-13]]

^<<v54-5-13,13>>^ Além do mais, elas aprendem também a viver ociosas, andando de casa em casa; e não somente ficam ociosas, mas ainda se tornam fofoqueiras e intrometidas, falando o que não devem.

[[v54-5-14]]

^<<v54-5-14,14>>^ Por isso, quero que as viúvas mais novas casem, criem filhos, sejam boas donas de casa e não deem ao adversário motivo algum para falar mal de nós.

[[v54-5-15]]

^<<v54-5-15,15>>^ Pois algumas já se desviaram, seguindo Satanás.

[[v54-5-16]]

^<<v54-5-16,16>>^ Se alguma mulher crente tem viúvas em sua família, socorra-as, para que a igreja não fique sobrecarregada e possa socorrer as viúvas que não têm ninguém.

[[v54-5-17]]

^<<v54-5-17,17>>^ Devem ser considerados merecedores de pagamento em dobro os presbíteros que presidem bem, especialmente os que se esforçam na pregação da palavra e no ensino.

[[v54-5-18]]

^<<v54-5-18,18>>^ Pois a Escritura declara: "Não amordace o boi quando ele pisa o trigo." E, ainda: "O trabalhador é digno do seu salário."

[[v54-5-19]]

^<<v54-5-19,19>>^ Não aceite denúncia contra presbítero, a não ser exclusivamente sob o depoimento de duas ou três testemunhas.

[[v54-5-20]]

^<<v54-5-20,20>>^ Quanto aos que vivem no pecado, repreenda-os na presença de todos, para que também os demais temam.

[[v54-5-21]]

^<<v54-5-21,21>>^ Diante de Deus, de Cristo Jesus e dos anjos eleitos, peço com insistência que você guarde estes conselhos, sem discriminação, nada fazendo com espírito de parcialidade.

[[v54-5-22]]

^<<v54-5-22,22>>^ Não tenha pressa para impor as mãos sobre alguém. Não seja cúmplice dos pecados dos outros. Conserve-se puro.

[[v54-5-23]]

^<<v54-5-23,23>>^ Não beba somente água; beba também um pouco de vinho, por causa do seu estômago e das suas frequentes enfermidades.

[[v54-5-24]]

^<<v54-5-24,24>>^ Os pecados de alguns são notórios, mesmo antes do juízo, mas os de outros só se manifestam mais tarde.

[[v54-5-25]]

^<<v54-5-25,25>>^ Do mesmo modo também as boas obras se evidenciam e aquelas que ainda não são manifestas não poderão ficar escondidas.

'''

xref:054-1-timoteo/054-1-timoteo-004.adoc#v54-4-0[&#60; Capítulo Anterior] | <<v54-5-0,Topo>> | xref:054-1-timoteo/054-1-timoteo-006.adoc#v54-6-0[Próximo Capítulo &#62;]