include::./index.adoc[]

[[v54-1-0]]
=== 1 Timóteo, 1
// naa ?, NAA - Nova Almeida Atualizada

[[v54-1-1]]

^<<v54-1-1,1>>^ Paulo, apóstolo de Cristo Jesus, por ordem de Deus, nosso Salvador, e de Cristo Jesus, nossa esperança,

[[v54-1-2]]

^<<v54-1-2,2>>^ a Timóteo, verdadeiro filho na fé. Que a graça, a misericórdia e a paz, da parte de Deus Pai e de Cristo Jesus, nosso Senhor, estejam com você.

[[v54-1-3]]

^<<v54-1-3,3>>^ Quando eu estava de viagem, rumo à Macedônia, pedi a você que ainda permanecesse em Éfeso para admoestar certas pessoas, a fim de que não ensinem outra doutrina,

[[v54-1-4]]

^<<v54-1-4,4>>^ nem se ocupem com fábulas e genealogias sem fim. Essas coisas mais promovem discussões do que o serviço de Deus, na fé.

[[v54-1-5]]

^<<v54-1-5,5>>^ O objetivo desta admoestação é o amor que procede de um coração puro, de uma boa consciência e de uma fé sem hipocrisia.

[[v54-1-6]]

^<<v54-1-6,6>>^ Algumas pessoas se desviaram destas coisas e se perderam em discussões inúteis,

[[v54-1-7]]

^<<v54-1-7,7>>^ pretendendo passar por mestres da lei, não compreendendo, porém, nem o que dizem, nem os assuntos sobre os quais falam com tanta ousadia.

[[v54-1-8]]

^<<v54-1-8,8>>^ Sabemos que a lei é boa, se alguém se utiliza dela de modo legítimo,

[[v54-1-9]]

^<<v54-1-9,9>>^ tendo em vista que não se promulga lei para quem é justo, mas para os transgressores e rebeldes, para os ímpios e pecadores, para os iníquos e profanos, para os que matam o pai ou a mãe, para os homicidas,

[[v54-1-10]]

^<<v54-1-10,10>>^ para os que praticam a imoralidade, para os que se entregam a práticas homossexuais, para os sequestradores, para os mentirosos, para os que fazem juramento falso e para tudo o que se opõe à sã doutrina,

[[v54-1-11]]

^<<v54-1-11,11>>^ segundo o evangelho da glória do Deus bendito, do qual fui encarregado.

[[v54-1-12]]

^<<v54-1-12,12>>^ Dou graças a Cristo Jesus, nosso Senhor, que me fortaleceu e me considerou fiel, designando-me para o ministério,

[[v54-1-13]]

^<<v54-1-13,13>>^ a mim, que, no passado, era blasfemo, perseguidor e insolente. Mas alcancei misericórdia, pois fiz isso na ignorância, na incredulidade.

[[v54-1-14]]

^<<v54-1-14,14>>^ Transbordou, porém, a graça de nosso Senhor com a fé e o amor que há em Cristo Jesus.

[[v54-1-15]]

^<<v54-1-15,15>>^ Esta palavra é fiel e digna de toda aceitação: que Cristo Jesus veio ao mundo para salvar os pecadores, dos quais eu sou o principal.

[[v54-1-16]]

^<<v54-1-16,16>>^ Mas, por esta mesma razão, me foi concedida misericórdia, para que, em mim, que sou o principal pecador, Cristo Jesus pudesse mostrar a sua completa longanimidade, e eu servisse de modelo para todos os que hão de crer nele para a vida eterna.

[[v54-1-17]]

^<<v54-1-17,17>>^ Assim, ao Rei eterno, imortal, invisível, Deus único, honra e glória para todo o sempre. Amém!

[[v54-1-18]]

^<<v54-1-18,18>>^ Esta é a admoestação que faço a você, meu filho Timóteo, segundo as profecias que anteriormente foram feitas a seu respeito: que, firmado nelas, você combata o bom combate,

[[v54-1-19]]

^<<v54-1-19,19>>^ mantendo a fé e a boa consciência, porque alguns, tendo rejeitado a boa consciência, vieram a naufragar na fé.

[[v54-1-20]]

^<<v54-1-20,20>>^ Entre esses estão Himeneu e Alexandre, os quais entreguei a Satanás para serem castigados, a fim de que aprendam a não blasfemar.

'''

xref:053-2-tessalonicenses/053-2-tessalonicenses-003.adoc#v53-3-0[&#60; Capítulo Anterior] | <<v54-1-0,Topo>> | xref:054-1-timoteo/054-1-timoteo-002.adoc#v54-2-0[Próximo Capítulo &#62;]