include::./index.adoc[]

[[v54-3-0]]
=== 1 Timóteo, 3
// naa ?, NAA - Nova Almeida Atualizada

[[v54-3-1]]

^<<v54-3-1,1>>^ Fiel é a palavra: se alguém deseja o episcopado, excelente obra almeja.

[[v54-3-2]]

^<<v54-3-2,2>>^ É necessário, pois, que o bispo seja irrepreensível, esposo de uma só mulher, moderado, sensato, modesto, hospitaleiro, apto para ensinar;

[[v54-3-3]]

^<<v54-3-3,3>>^ não dado ao vinho, nem violento, porém cordial, inimigo de conflitos, não avarento;

[[v54-3-4]]

^<<v54-3-4,4>>^ e que governe bem a própria casa, criando os filhos sob disciplina, com todo o respeito.

[[v54-3-5]]

^<<v54-3-5,5>>^ Pois, se alguém não sabe governar a própria casa, como cuidará da igreja de Deus?

[[v54-3-6]]

^<<v54-3-6,6>>^ Que o bispo não seja recém-convertido, para não acontecer que fique cheio de orgulho e incorra na condenação do diabo.

[[v54-3-7]]

^<<v54-3-7,7>>^ É necessário, também, que ele tenha bom testemunho dos de fora, a fim de não cair na desonra e no laço do diabo.

[[v54-3-8]]

^<<v54-3-8,8>>^ Do mesmo modo, quanto a diáconos, é necessário que sejam respeitáveis, de uma só palavra, não inclinados a muito vinho, não gananciosos,

[[v54-3-9]]

^<<v54-3-9,9>>^ conservando o mistério da fé com a consciência limpa.

[[v54-3-10]]

^<<v54-3-10,10>>^ Também estes devem ser primeiramente experimentados; e, caso se mostrem irrepreensíveis, que exerçam o diaconato.

[[v54-3-11]]

^<<v54-3-11,11>>^ Do mesmo modo, quanto a mulheres, é necessário que elas sejam respeitáveis, não maldizentes, moderadas e fiéis em tudo.

[[v54-3-12]]

^<<v54-3-12,12>>^ O diácono seja marido de uma só mulher e governe bem os seus filhos e a própria casa.

[[v54-3-13]]

^<<v54-3-13,13>>^ Pois os que desempenharem bem o diaconato alcançarão para si mesmos uma posição de honra e muita ousadia na fé em Cristo Jesus.

[[v54-3-14]]

^<<v54-3-14,14>>^ Escrevo estas coisas a você, esperando ir vê-lo em breve.

[[v54-3-15]]

^<<v54-3-15,15>>^ Mas, se eu demorar, você saberá como se deve proceder na casa de Deus, que é a igreja do Deus vivo, coluna e fundamento da verdade.

[[v54-3-16]]

^<<v54-3-16,16>>^ Sem dúvida, grande é o mistério da piedade: "Aquele que foi manifestado na carne foi justificado em espírito, visto pelos anjos, pregado entre os gentios, crido no mundo, recebido na glória."

'''

xref:054-1-timoteo/054-1-timoteo-002.adoc#v54-2-0[&#60; Capítulo Anterior] | <<v54-3-0,Topo>> | xref:054-1-timoteo/054-1-timoteo-004.adoc#v54-4-0[Próximo Capítulo &#62;]