include::./index.adoc[]

[[v54-6-0]]
=== 1 Timóteo, 6
// naa ?, NAA - Nova Almeida Atualizada

[[v54-6-1]]

^<<v54-6-1,1>>^ Todos os servos que estão debaixo de jugo considerem dignos de toda honra o próprio senhor, para que o nome de Deus e a doutrina não sejam difamados.

[[v54-6-2]]

^<<v54-6-2,2>>^ Também os que têm senhor crente não o tratem com desrespeito, porque é irmão; pelo contrário, trabalhem ainda mais, pois ele, que partilha do seu bom serviço, é crente e amado. Ensine e recomende estas coisas.

[[v54-6-3]]

^<<v54-6-3,3>>^ Se alguém ensina outra doutrina e não concorda com as sãs palavras de nosso Senhor Jesus Cristo e com o ensino segundo a piedade,

[[v54-6-4]]

^<<v54-6-4,4>>^ esse é orgulhoso e não entende nada, mas tem um desejo doentio por discussões e brigas a respeito de palavras. É daí que nascem a inveja, a provocação, as difamações, as suspeitas malignas

[[v54-6-5]]

^<<v54-6-5,5>>^ e as polêmicas sem fim da parte de pessoas cuja mente é pervertida e que estão privadas da verdade, supondo que a piedade é fonte de lucro.

[[v54-6-6]]

^<<v54-6-6,6>>^ De fato, grande fonte de lucro é a piedade com o contentamento.

[[v54-6-7]]

^<<v54-6-7,7>>^ Porque nada trouxemos para o mundo, nem coisa alguma podemos levar dele.

[[v54-6-8]]

^<<v54-6-8,8>>^ Tendo sustento e com que nos vestir, estejamos contentes.

[[v54-6-9]]

^<<v54-6-9,9>>^ Mas os que querem ficar ricos caem em tentação, em armadilhas e em muitos desejos insensatos e nocivos, que levam as pessoas a se afundar na ruína e na perdição.

[[v54-6-10]]

^<<v54-6-10,10>>^ Porque o amor ao dinheiro é a raiz de todos os males; e alguns, nessa cobiça, se desviaram da fé e atormentaram a si mesmos com muitas dores.

[[v54-6-11]]

^<<v54-6-11,11>>^ Mas você, homem de Deus, fuja de tudo isso. Siga a justiça, a piedade, a fé, o amor, a perseverança, a mansidão.

[[v54-6-12]]

^<<v54-6-12,12>>^ Combata o bom combate da fé. Tome posse da vida eterna, para a qual você também foi chamado e da qual fez a boa confissão diante de muitas testemunhas.

[[v54-6-13]]

^<<v54-6-13,13>>^ Diante de Deus, que preserva a vida de todas as coisas, e diante de Cristo Jesus, que, na presença de Pôncio Pilatos, fez a boa confissão, eu exorto você

[[v54-6-14]]

^<<v54-6-14,14>>^ a guardar este mandato imaculado, irrepreensível, até a manifestação de nosso Senhor Jesus Cristo,

[[v54-6-15]]

^<<v54-6-15,15>>^ a qual, no tempo certo, há de ser revelada pelo bendito e único Soberano, o Rei dos reis e Senhor dos senhores,

[[v54-6-16]]

^<<v54-6-16,16>>^ o único que possui imortalidade, que habita em luz inacessível, a quem ninguém jamais viu, nem é capaz de ver. A ele honra e poder eterno. Amém!

[[v54-6-17]]

^<<v54-6-17,17>>^ Exorte os ricos deste mundo a que não sejam orgulhosos, nem depositem a sua esperança na instabilidade da riqueza, mas em Deus, que tudo nos proporciona ricamente para o nosso prazer.

[[v54-6-18]]

^<<v54-6-18,18>>^ Que eles façam o bem, sejam ricos em boas obras, generosos em dar e prontos a repartir;

[[v54-6-19]]

^<<v54-6-19,19>>^ ajuntando para si mesmos um tesouro que é sólido fundamento para o futuro, a fim de tomarem posse da verdadeira vida.

[[v54-6-20]]

^<<v54-6-20,20>>^ E você, ó Timóteo, guarde o que lhe foi confiado, evitando os falatórios inúteis e profanos e as contradições daquilo que falsamente chamam de "conhecimento",

[[v54-6-21]]

^<<v54-6-21,21>>^ pois alguns, professando-o, se desviaram da fé. A graça esteja com vocês.

'''

xref:054-1-timoteo/054-1-timoteo-005.adoc#v54-5-0[&#60; Capítulo Anterior] | <<v54-6-0,Topo>> | xref:055-2-timoteo/055-2-timoteo-001.adoc#v55-1-0[Próximo Capítulo &#62;]