include::./index.adoc[]

[[v44-24-0]]
=== Atos, 24
// naa ?, NAA - Nova Almeida Atualizada

[[v44-24-1]]

^<<v44-24-1,1>>^ Cinco dias depois, o sumo sacerdote Ananias foi até Cesareia com alguns anciãos e com certo orador, chamado Tértulo, os quais apresentaram ao governador a sua acusação contra Paulo.

[[v44-24-2]]

^<<v44-24-2,2>>^ Depois que Paulo foi chamado, Tértulo passou a acusá-lo, dizendo: — Excelentíssimo Félix, tendo nós desfrutado de paz perene por meio do senhor e tendo sido feitas, por seu providente cuidado, notáveis reformas em benefício deste povo,

[[v44-24-3]]

^<<v44-24-3,3>>^ sempre e em todos os lugares, reconhecemos isto com profunda gratidão.

[[v44-24-4]]

^<<v44-24-4,4>>^ Entretanto, para não deter o senhor por muito tempo, peço que, de acordo com a sua clemência, nos ouça por alguns instantes.

[[v44-24-5]]

^<<v44-24-5,5>>^ Porque, tendo nós verificado que este homem é uma peste e promove desordens entre os judeus do mundo inteiro, sendo também o principal agitador da seita dos nazarenos,

[[v44-24-6]]

^<<v44-24-6,6>>^ o qual também tentou profanar o templo, nós o prendemos com o intuito de julgá-lo segundo a nossa Lei.

[[v44-24-7]]

^<<v44-24-7,7>>^ Mas, sobrevindo o comandante Lísias, o arrebatou das nossas mãos com grande violência,

[[v44-24-8]]

^<<v44-24-8,8>>^ ordenando que os seus acusadores viessem à presença do senhor. Se o interrogar, o senhor mesmo poderá tomar conhecimento de todas as coisas de que nós o acusamos.

[[v44-24-9]]

^<<v44-24-9,9>>^ Os judeus também concordaram na acusação, afirmando que estas coisas eram assim.

[[v44-24-10]]

^<<v44-24-10,10>>^ Quando o governador fez sinal para que Paulo falasse, ele disse: — Sabendo que há muitos anos o senhor é juiz desta nação, sinto-me à vontade para me defender.

[[v44-24-11]]

^<<v44-24-11,11>>^ O senhor mesmo pode verificar que não se passaram mais de doze dias desde que fui a Jerusalém para adorar a Deus;

[[v44-24-12]]

^<<v44-24-12,12>>^ e que não me acharam no templo discutindo com ninguém, nem agitando o povo, fosse nas sinagogas ou na cidade;

[[v44-24-13]]

^<<v44-24-13,13>>^ nem podem provar diante do senhor as acusações que agora fazem contra mim.

[[v44-24-14]]

^<<v44-24-14,14>>^ Porém confesso ao senhor que, segundo o Caminho, a que chamam seita, assim eu sirvo ao Deus de nossos pais, acreditando em todas as coisas que concordam com a lei e os escritos dos profetas,

[[v44-24-15]]

^<<v44-24-15,15>>^ tendo esperança em Deus, como também estes a têm, de que haverá ressurreição, tanto de justos como de injustos.

[[v44-24-16]]

^<<v44-24-16,16>>^ Por isso, também me esforço por ter sempre uma consciência pura diante de Deus e dos homens.

[[v44-24-17]]

^<<v44-24-17,17>>^ — Depois de anos, vim trazer donativos para o meu povo e também fazer oferendas,

[[v44-24-18]]

^<<v44-24-18,18>>^ e foi nesta prática que alguns judeus da província da Ásia me encontraram já purificado no templo, sem ajuntamento de povo e sem tumulto,

[[v44-24-19]]

^<<v44-24-19,19>>^ os quais deviam comparecer diante do senhor e fazer as acusações, se tivessem alguma coisa contra mim.

[[v44-24-20]]

^<<v44-24-20,20>>^ Ou então que estes homens que estão aqui digam que crime acharam em mim, por ocasião do meu comparecimento diante do Sinédrio,

[[v44-24-21]]

^<<v44-24-21,21>>^ salvo estas palavras que clamei, estando entre eles: "Hoje estou sendo julgado por vocês por causa da ressurreição dos mortos."

[[v44-24-22]]

^<<v44-24-22,22>>^ Então Félix, conhecendo mais acuradamente as coisas relacionadas com o Caminho, adiou a causa, dizendo: — Quando chegar o comandante Lísias, tomarei uma decisão a respeito do caso de vocês.

[[v44-24-23]]

^<<v44-24-23,23>>^ E ordenou ao centurião que conservasse Paulo na prisão, tratando-o com tolerância e não impedindo que os seus próprios o servissem.

[[v44-24-24]]

^<<v44-24-24,24>>^ Passados alguns dias, Félix veio com Drusila, sua mulher, que era judia. Mandou chamar Paulo e passou a ouvi-lo a respeito da fé em Cristo Jesus.

[[v44-24-25]]

^<<v44-24-25,25>>^ Quando Paulo começou a falar sobre a justiça, o domínio próprio e o Juízo vindouro, Félix ficou amedrontado e disse: — Por agora, você pode retirar-se, e, quando eu tiver oportunidade, mandarei chamá-lo.

[[v44-24-26]]

^<<v44-24-26,26>>^ Ao mesmo tempo, esperava que Paulo lhe desse dinheiro. Por isso, chamando-o mais frequentemente, conversava com ele.

[[v44-24-27]]

^<<v44-24-27,27>>^ Dois anos mais tarde, Félix teve por sucessor Pórcio Festo. E, como Félix queria assegurar o apoio dos judeus, manteve Paulo encarcerado.

'''

xref:044-atos/044-atos-023.adoc#v44-23-0[&#60; Capítulo Anterior] | <<v44-24-0,Topo>> | xref:044-atos/044-atos-025.adoc#v44-25-0[Próximo Capítulo &#62;]