include::./index.adoc[]

[[v44-27-0]]
=== Atos, 27
// naa ?, NAA - Nova Almeida Atualizada

[[v44-27-1]]

^<<v44-27-1,1>>^ Quando foi decidido que devíamos navegar para a Itália, entregaram Paulo e alguns outros presos a um centurião chamado Júlio, do Batalhão Imperial.

[[v44-27-2]]

^<<v44-27-2,2>>^ Embarcando num navio de Adramítio, que estava de partida para costear a província da Ásia, fizemo-nos ao mar, indo conosco Aristarco, um macedônio de Tessalônica.

[[v44-27-3]]

^<<v44-27-3,3>>^ No dia seguinte, chegamos a Sidom. Júlio, tratando Paulo com humanidade, permitiu que ele fosse ver os amigos e obter assistência.

[[v44-27-4]]

^<<v44-27-4,4>>^ Partindo dali, navegamos ao abrigo da ilha de Chipre, porque os ventos eram contrários.

[[v44-27-5]]

^<<v44-27-5,5>>^ E, tendo atravessado o mar ao longo da Cilícia e Panfília, chegamos a Mirra, na Lícia.

[[v44-27-6]]

^<<v44-27-6,6>>^ Nesse porto, o centurião encontrou um navio de Alexandria, que estava de partida para a Itália, e nos fez embarcar nele.

[[v44-27-7]]

^<<v44-27-7,7>>^ Navegando vagarosamente muitos dias, foi com dificuldade que chegamos às imediações de Cnido. Não nos sendo permitido prosseguir, por causa do vento contrário, navegamos ao abrigo de Creta, na altura de Salmona.

[[v44-27-8]]

^<<v44-27-8,8>>^ Costeando a ilha com dificuldade, chegamos a um lugar chamado Bons Portos, perto do qual estava a cidade de Laseia.

[[v44-27-9]]

^<<v44-27-9,9>>^ Depois de muito tempo, tendo-se tornado a navegação perigosa, e já passado o tempo do Dia do Jejum, Paulo os aconselhou,

[[v44-27-10]]

^<<v44-27-10,10>>^ dizendo: — Senhores, vejo que a viagem vai ser trabalhosa, com dano e muito prejuízo, não só da carga e do navio, mas também da nossa vida.

[[v44-27-11]]

^<<v44-27-11,11>>^ Porém o centurião dava mais crédito ao piloto e ao mestre do navio do que ao que Paulo dizia.

[[v44-27-12]]

^<<v44-27-12,12>>^ Não sendo o porto próprio para invernar, a maioria deles era de opinião que deviam partir dali, para ver se podiam chegar a Fenice e aí passar o inverno, visto ser um porto de Creta, que olha para o noroeste e para o sudoeste.

[[v44-27-13]]

^<<v44-27-13,13>>^ Soprando brandamente o vento sul, e pensando eles ter alcançado o que desejavam, levantaram âncora e foram costeando mais de perto a ilha de Creta.

[[v44-27-14]]

^<<v44-27-14,14>>^ Entretanto, não muito depois, desencadeou-se, do lado da ilha, um tufão de vento, chamado Euroaquilão.

[[v44-27-15]]

^<<v44-27-15,15>>^ O navio foi arrastado com violência e, sem poder resistir ao vento, cessamos a manobra e nos fomos deixando levar.

[[v44-27-16]]

^<<v44-27-16,16>>^ Passando ao abrigo de uma ilhota chamada Cauda, com dificuldade conseguimos recolher o bote.

[[v44-27-17]]

^<<v44-27-17,17>>^ Tendo içado o bote, os marinheiros usaram de todos os meios para reforçar o navio com cabos de segurança. E, temendo que fossem encalhar nos bancos de areia de Sirte, desceram as velas e foram à deriva.

[[v44-27-18]]

^<<v44-27-18,18>>^ Açoitados severamente pela tormenta, no dia seguinte começaram a jogar a carga no mar.

[[v44-27-19]]

^<<v44-27-19,19>>^ E, no terceiro dia, nós mesmos, com as próprias mãos, lançamos ao mar a armação do navio.

[[v44-27-20]]

^<<v44-27-20,20>>^ E, não aparecendo, havia já alguns dias, nem sol nem estrelas, caindo sobre nós grande tempestade, dissipou-se, afinal, toda a esperança de salvamento.

[[v44-27-21]]

^<<v44-27-21,21>>^ Havendo todos estado muito tempo sem comer, Paulo, pondo-se em pé no meio deles, disse: — Senhores, na verdade, era preciso terem-me atendido e não partir de Creta, para evitar este dano e perda.

[[v44-27-22]]

^<<v44-27-22,22>>^ Mas agora aconselho que tenham coragem, porque nenhuma vida se perderá, mas somente o navio.

[[v44-27-23]]

^<<v44-27-23,23>>^ Porque, esta mesma noite, um anjo do Deus a quem pertenço e a quem sirvo, esteve comigo,

[[v44-27-24]]

^<<v44-27-24,24>>^ dizendo: "Paulo, não tenha medo! É preciso que você compareça diante de César, e eis que Deus, por sua graça, lhe deu todos os que navegam com você."

[[v44-27-25]]

^<<v44-27-25,25>>^ Portanto, senhores, tenham coragem! Pois eu confio em Deus que tudo vai acontecer conforme me foi dito.

[[v44-27-26]]

^<<v44-27-26,26>>^ Porém é necessário que sejamos arrastados para alguma ilha.

[[v44-27-27]]

^<<v44-27-27,27>>^ Quando chegou a décima quarta noite, sendo nós batidos de um lado para outro no mar Adriático, por volta da meia-noite os marinheiros pressentiram que se aproximavam de alguma terra.

[[v44-27-28]]

^<<v44-27-28,28>>^ E, lançando a sonda, viram que a profundidade era de trinta e seis metros. Passando um pouco mais adiante, tornando a lançar a sonda, viram que a profundidade era de vinte e sete metros.

[[v44-27-29]]

^<<v44-27-29,29>>^ E, receosos de que fôssemos atirados contra lugares rochosos, lançaram da popa quatro âncoras e oravam para que rompesse o dia.

[[v44-27-30]]

^<<v44-27-30,30>>^ Nisto os marinheiros tentaram escapar do navio. Arriaram o bote no mar, a pretexto de que iam largar âncoras da proa.

[[v44-27-31]]

^<<v44-27-31,31>>^ Paulo disse ao centurião e aos soldados: — Se estes não permanecerem a bordo, vocês não poderão se salvar.

[[v44-27-32]]

^<<v44-27-32,32>>^ Então os soldados cortaram os cabos do bote e o deixaram afastar-se.

[[v44-27-33]]

^<<v44-27-33,33>>^ Enquanto amanhecia, Paulo rogava a todos que se alimentassem, dizendo: — Hoje é o décimo quarto dia em que, esperando, vocês estão sem comer, não tendo provado nada.

[[v44-27-34]]

^<<v44-27-34,34>>^ Por isso peço que comam alguma coisa, pois disto depende a sobrevivência de vocês. Porque nenhum de vocês perderá nem mesmo um fio de cabelo.

[[v44-27-35]]

^<<v44-27-35,35>>^ Tendo dito isto, pegando um pão, deu graças a Deus na presença de todos e, depois de o partir, começou a comer.

[[v44-27-36]]

^<<v44-27-36,36>>^ Todos ficaram mais animados e se puseram também a comer.

[[v44-27-37]]

^<<v44-27-37,37>>^ Estávamos no navio duzentas e setenta e seis pessoas ao todo.

[[v44-27-38]]

^<<v44-27-38,38>>^ Refeitos com a comida, aliviaram o navio, jogando o trigo no mar.

[[v44-27-39]]

^<<v44-27-39,39>>^ Quando amanheceu, não reconheceram a terra, mas avistaram uma enseada, onde havia uma praia. Então consultaram entre si se não podiam encalhar ali o navio.

[[v44-27-40]]

^<<v44-27-40,40>>^ Cortando os cabos das âncoras, deixaram que ficassem no mar. Soltaram também as amarras do leme. E, alçando a vela de proa ao vento, dirigiram-se para a praia.

[[v44-27-41]]

^<<v44-27-41,41>>^ Dando, porém, num lugar onde duas correntes se encontravam, encalharam ali o navio; a proa encravou-se e ficou imóvel, mas a popa se despedaçava pela violência das ondas.

[[v44-27-42]]

^<<v44-27-42,42>>^ O parecer dos soldados era que os presos deviam ser mortos, para que nenhum deles fugisse nadando.

[[v44-27-43]]

^<<v44-27-43,43>>^ Mas o centurião, querendo salvar Paulo, impediu-os de fazer isso. Ordenou que os que soubessem nadar fossem os primeiros a lançar-se ao mar e alcançar a terra.

[[v44-27-44]]

^<<v44-27-44,44>>^ Quanto aos demais, que se salvassem, uns, em tábuas, e outros, em destroços do navio. E foi assim que todos se salvaram em terra.

'''

xref:044-atos/044-atos-026.adoc#v44-26-0[&#60; Capítulo Anterior] | <<v44-27-0,Topo>> | xref:044-atos/044-atos-028.adoc#v44-28-0[Próximo Capítulo &#62;]