include::./index.adoc[]

[[v44-9-0]]
=== Atos, 9
// naa ?, NAA - Nova Almeida Atualizada

[[v44-9-1]]

^<<v44-9-1,1>>^ Saulo, respirando ainda ameaças e morte contra os discípulos do Senhor, dirigiu-se ao sumo sacerdote

[[v44-9-2]]

^<<v44-9-2,2>>^ e lhe pediu cartas para as sinagogas de Damasco, a fim de que, caso achasse alguns que eram do Caminho, tanto homens como mulheres, os levasse presos para Jerusalém.

[[v44-9-3]]

^<<v44-9-3,3>>^ Enquanto seguia pelo caminho, ao aproximar-se de Damasco, subitamente uma luz do céu brilhou ao seu redor.

[[v44-9-4]]

^<<v44-9-4,4>>^ Ele caiu por terra e ouviu uma voz que lhe dizia: — Saulo, Saulo, por que você me persegue?

[[v44-9-5]]

^<<v44-9-5,5>>^ Ele perguntou: — Senhor, quem é você? E a resposta foi: — Eu sou Jesus, a quem você persegue.

[[v44-9-6]]

^<<v44-9-6,6>>^ Mas levante-se e entre na cidade, onde lhe dirão o que você deve fazer.

[[v44-9-7]]

^<<v44-9-7,7>>^ Os homens que viajavam com Saulo pararam emudecidos, ouvindo a voz, mas não vendo ninguém.

[[v44-9-8]]

^<<v44-9-8,8>>^ Então Saulo se levantou do chão e, abrindo os olhos, nada podia ver. E, guiando-o pela mão, levaram-no para Damasco.

[[v44-9-9]]

^<<v44-9-9,9>>^ Esteve três dias sem ver, durante os quais nada comeu, nem bebeu.

[[v44-9-10]]

^<<v44-9-10,10>>^ Havia em Damasco um discípulo chamado Ananias. O Senhor lhe apareceu numa visão e disse: — Ananias! Ao que ele respondeu: — Eis-me aqui, Senhor!

[[v44-9-11]]

^<<v44-9-11,11>>^ Então o Senhor lhe disse: — Levante-se e vá à rua que se chama Direita e, na casa de Judas, procure um homem de Tarso chamado Saulo. Ele está orando

[[v44-9-12]]

^<<v44-9-12,12>>^ e, numa visão, viu entrar um homem, chamado Ananias, e impor-lhe as mãos, para que recuperasse a vista.

[[v44-9-13]]

^<<v44-9-13,13>>^ Ananias, porém, respondeu: — Senhor, de muitos tenho ouvido a respeito desse homem, quanto mal tem feito aos teus santos em Jerusalém.

[[v44-9-14]]

^<<v44-9-14,14>>^ E aqui em Damasco ele tem autorização dos principais sacerdotes para prender todos os que invocam o teu nome.

[[v44-9-15]]

^<<v44-9-15,15>>^ Mas o Senhor disse a Ananias: — Vá, porque este é para mim um instrumento escolhido para levar o meu nome diante dos gentios e reis, bem como diante dos filhos de Israel.

[[v44-9-16]]

^<<v44-9-16,16>>^ Pois eu mesmo vou mostrar a ele quanto deve sofrer pelo meu nome.

[[v44-9-17]]

^<<v44-9-17,17>>^ Então Ananias foi e, entrando na casa, impôs as mãos sobre Saulo, dizendo: — Saulo, irmão, o Senhor Jesus, que apareceu a você no caminho para cá, me enviou para que você volte a ver e fique cheio do Espírito Santo.

[[v44-9-18]]

^<<v44-9-18,18>>^ Imediatamente caíram dos olhos de Saulo umas coisas parecidas com escamas, e ele voltou a ver. A seguir, levantou-se e foi batizado.

[[v44-9-19]]

^<<v44-9-19,19>>^ E, depois de comer, sentiu-se fortalecido. Saulo permaneceu alguns dias com os discípulos em Damasco.

[[v44-9-20]]

^<<v44-9-20,20>>^ E logo, nas sinagogas, proclamava Jesus, afirmando que ele é o Filho de Deus.

[[v44-9-21]]

^<<v44-9-21,21>>^ Todos os que ouviam Saulo estavam atônitos e diziam: — Não é este o que exterminava em Jerusalém os que invocam o nome de Jesus e veio para cá precisamente para prender e levá-los aos principais sacerdotes?

[[v44-9-22]]

^<<v44-9-22,22>>^ Saulo, porém, mais e mais se fortalecia e confundia os judeus que moravam em Damasco, demonstrando que Jesus é o Cristo.

[[v44-9-23]]

^<<v44-9-23,23>>^ Decorridos muitos dias, os judeus resolveram matar Saulo,

[[v44-9-24]]

^<<v44-9-24,24>>^ mas ele ficou sabendo do plano deles. Dia e noite guardavam também os portões da cidade, para o matar.

[[v44-9-25]]

^<<v44-9-25,25>>^ Mas os discípulos de Saulo tomaram-no de noite e, colocando-o num cesto, desceram-no pela muralha.

[[v44-9-26]]

^<<v44-9-26,26>>^ Quando chegou a Jerusalém, Saulo procurou juntar-se aos discípulos de Jesus. Porém todos tinham medo dele, não acreditando que ele fosse discípulo.

[[v44-9-27]]

^<<v44-9-27,27>>^ Mas Barnabé, tomando-o consigo, levou-o aos apóstolos. Contou-lhes como Saulo tinha visto o Senhor no caminho, e que o Senhor tinha falado com ele. Também contou como, em Damasco, Saulo tinha pregado ousadamente em nome de Jesus.

[[v44-9-28]]

^<<v44-9-28,28>>^ E Saulo ficou com eles em Jerusalém, entrando e saindo, pregando ousadamente em nome do Senhor.

[[v44-9-29]]

^<<v44-9-29,29>>^ Falava e discutia com os helenistas, mas eles procuravam matá-lo.

[[v44-9-30]]

^<<v44-9-30,30>>^ Quando isto chegou ao conhecimento dos irmãos, levaram Saulo até Cesareia e dali o enviaram para Tarso.

[[v44-9-31]]

^<<v44-9-31,31>>^ Assim, a igreja tinha paz por toda a Judeia, Galileia e Samaria, edificando-se e caminhando no temor do Senhor; e, no consolo do Espírito Santo, crescia em número.

[[v44-9-32]]

^<<v44-9-32,32>>^ Passando Pedro por toda parte, foi também visitar os santos que moravam em Lida.

[[v44-9-33]]

^<<v44-9-33,33>>^ Encontrou ali certo homem, chamado Eneias, que havia oito anos jazia de cama, pois era paralítico.

[[v44-9-34]]

^<<v44-9-34,34>>^ Pedro lhe disse: — Eneias, Jesus Cristo cura você! Levante-se e arrume a sua cama. Ele imediatamente se levantou.

[[v44-9-35]]

^<<v44-9-35,35>>^ Todos os habitantes de Lida e da região de Sarom viram Eneias e se converteram ao Senhor.

[[v44-9-36]]

^<<v44-9-36,36>>^ Em Jope havia uma discípula chamada Tabita, nome este que, traduzido, é Dorcas. Ela era notável pelas boas obras e esmolas que fazia.

[[v44-9-37]]

^<<v44-9-37,37>>^ Aconteceu que, naqueles dias, ela adoeceu e veio a morrer. Depois de a lavarem, puseram o corpo num quarto do andar superior.

[[v44-9-38]]

^<<v44-9-38,38>>^ Como Lida ficava perto de Jope, os discípulos, ouvindo que Pedro estava ali, enviaram-lhe dois homens com o seguinte pedido: — Não se demore em vir até nós.

[[v44-9-39]]

^<<v44-9-39,39>>^ Pedro se aprontou e foi com eles. Quando chegou lá, eles o levaram ao quarto do andar superior. Todas as viúvas o cercaram, chorando e mostrando-lhe túnicas e vestidos que Dorcas tinha feito enquanto estava com elas.

[[v44-9-40]]

^<<v44-9-40,40>>^ Mas Pedro mandou que todos saíssem, ajoelhou-se e orou; depois, voltando-se para o corpo, disse: — Tabita, levante-se! Ela abriu os olhos e, vendo Pedro, sentou-se.

[[v44-9-41]]

^<<v44-9-41,41>>^ Ele, dando-lhe a mão, ajudou-a a ficar em pé; e, chamando os santos, especialmente as viúvas, apresentou-a viva.

[[v44-9-42]]

^<<v44-9-42,42>>^ Isto se tornou conhecido em toda a cidade de Jope, e muitos creram no Senhor.

[[v44-9-43]]

^<<v44-9-43,43>>^ Pedro ficou em Jope muitos dias, na casa de um curtidor chamado Simão.

'''

xref:044-atos/044-atos-008.adoc#v44-8-0[&#60; Capítulo Anterior] | <<v44-9-0,Topo>> | xref:044-atos/044-atos-010.adoc#v44-10-0[Próximo Capítulo &#62;]