include::./index.adoc[]

[[v44-3-0]]
=== Atos, 3
// naa ?, NAA - Nova Almeida Atualizada

[[v44-3-1]]

^<<v44-3-1,1>>^ Pedro e João estavam se dirigindo ao templo para a oração das três horas da tarde.

[[v44-3-2]]

^<<v44-3-2,2>>^ Estava sendo levado um homem, coxo de nascença, que diariamente era colocado à porta do templo chamada Formosa, para pedir esmolas aos que entravam.

[[v44-3-3]]

^<<v44-3-3,3>>^ Quando ele viu Pedro e João, que iam entrar no templo, pediu que lhe dessem uma esmola.

[[v44-3-4]]

^<<v44-3-4,4>>^ Pedro, fitando-o, juntamente com João, disse: — Olhe para nós!

[[v44-3-5]]

^<<v44-3-5,5>>^ Ele os olhava atentamente, esperando receber alguma coisa.

[[v44-3-6]]

^<<v44-3-6,6>>^ Pedro, porém, lhe disse: — Não possuo nem prata nem ouro, mas o que tenho, isso lhe dou: em nome de Jesus Cristo, o Nazareno, levante-se e ande!

[[v44-3-7]]

^<<v44-3-7,7>>^ E, pegando na mão direita do homem, ajudou-o a se levantar. Imediatamente os seus pés e tornozelos se firmaram;

[[v44-3-8]]

^<<v44-3-8,8>>^ e, dando um salto, ficou em pé, começou a andar e entrou com eles no templo, pulando e louvando a Deus.

[[v44-3-9]]

^<<v44-3-9,9>>^ Todo o povo viu o homem andando e louvando a Deus,

[[v44-3-10]]

^<<v44-3-10,10>>^ e reconheceram que ele era o mesmo que pedia esmolas, assentado à Porta Formosa do templo; e ficaram muito admirados e espantados com o que lhe tinha acontecido.

[[v44-3-11]]

^<<v44-3-11,11>>^ Enquanto aquele homem ainda se mantinha ao lado de Pedro e João, todo o povo, perplexo, correu para junto deles no pórtico chamado de Salomão.

[[v44-3-12]]

^<<v44-3-12,12>>^ Quando Pedro viu isso, dirigiu-se ao povo, dizendo: — Israelitas, por que vocês estão admirados com isto ou por que estão com os olhos fixos em nós como se pelo nosso próprio poder ou piedade tivéssemos feito este homem andar?

[[v44-3-13]]

^<<v44-3-13,13>>^ O Deus de Abraão, o Deus de Isaque e o Deus de Jacó, o Deus dos nossos pais, glorificou o seu Servo Jesus, a quem vocês traíram e negaram diante de Pilatos, quando este já havia decidido soltá-lo.

[[v44-3-14]]

^<<v44-3-14,14>>^ Vocês negaram o Santo e o Justo e pediram que fosse solto um assassino.

[[v44-3-15]]

^<<v44-3-15,15>>^ Vocês mataram o Autor da vida, a quem Deus ressuscitou dentre os mortos, do que nós somos testemunhas.

[[v44-3-16]]

^<<v44-3-16,16>>^ Pela fé no nome de Jesus é que esse mesmo nome fortaleceu a este homem que vocês estão vendo e bem conhecem. Sim, a fé que vem por meio de Jesus deu a este homem saúde perfeita na presença de todos vocês.

[[v44-3-17]]

^<<v44-3-17,17>>^ — E agora, irmãos, eu sei que vocês fizeram isso por ignorância, como também as suas autoridades o fizeram.

[[v44-3-18]]

^<<v44-3-18,18>>^ Mas Deus, assim, cumpriu o que tinha anunciado anteriormente pela boca de todos os profetas: que o seu Cristo havia de padecer.

[[v44-3-19]]

^<<v44-3-19,19>>^ Portanto, arrependam-se e se convertam, para que sejam cancelados os seus pecados,

[[v44-3-20]]

^<<v44-3-20,20>>^ a fim de que, da presença do Senhor, venham tempos de refrigério, e que ele envie o Cristo, que já foi designado para vocês, a saber, Jesus,

[[v44-3-21]]

^<<v44-3-21,21>>^ ao qual é necessário que o céu receba até os tempos da restauração de todas as coisas, de que Deus falou por boca dos seus santos profetas desde a antiguidade.

[[v44-3-22]]

^<<v44-3-22,22>>^ Porque Moisés disse: "O Senhor Deus fará com que, do meio dos irmãos de vocês, se levante um profeta semelhante a mim; a esse vocês ouvirão em tudo o que ele lhes disser.

[[v44-3-23]]

^<<v44-3-23,23>>^ Quem não der ouvidos a esse profeta será exterminado do meio do povo."

[[v44-3-24]]

^<<v44-3-24,24>>^ — E todos os profetas, a começar com Samuel, assim como todos os que falaram depois dele, também anunciaram estes dias.

[[v44-3-25]]

^<<v44-3-25,25>>^ Vocês são os filhos dos profetas e da aliança que Deus estabeleceu com os pais de vocês, dizendo a Abraão: "Na sua descendência, serão abençoadas todas as nações da terra."

[[v44-3-26]]

^<<v44-3-26,26>>^ — Tendo Deus ressuscitado o seu Servo, enviou-o primeiramente a vocês para abençoá-los, no sentido de que cada um abandone as suas maldades.

'''

xref:044-atos/044-atos-002.adoc#v44-2-0[&#60; Capítulo Anterior] | <<v44-3-0,Topo>> | xref:044-atos/044-atos-004.adoc#v44-4-0[Próximo Capítulo &#62;]