include::./index.adoc[]

[[v44-18-0]]
=== Atos, 18
// naa ?, NAA - Nova Almeida Atualizada

[[v44-18-1]]

^<<v44-18-1,1>>^ Depois disso, deixando Atenas, Paulo foi a Corinto.

[[v44-18-2]]

^<<v44-18-2,2>>^ Lá, encontrou um judeu chamado Áquila, natural do Ponto, recentemente chegado da Itália, com Priscila, sua mulher, porque o imperador Cláudio havia decretado que todos os judeus deviam sair de Roma. Paulo aproximou-se deles.

[[v44-18-3]]

^<<v44-18-3,3>>^ E, como tinham o mesmo ofício, passou a morar com eles e ali trabalhava. O ofício deles era fazer tendas.

[[v44-18-4]]

^<<v44-18-4,4>>^ E todos os sábados Paulo falava na sinagoga, persuadindo tanto judeus como gregos.

[[v44-18-5]]

^<<v44-18-5,5>>^ Quando Silas e Timóteo chegaram da Macedônia, Paulo se entregou totalmente à palavra, testemunhando aos judeus que Jesus é o Cristo.

[[v44-18-6]]

^<<v44-18-6,6>>^ Como eles se opuseram e blasfemaram, Paulo sacudiu as roupas e disse-lhes: — Que o sangue de vocês caia sobre a cabeça de vocês! Eu estou limpo dele e, a partir de agora, vou para os gentios.

[[v44-18-7]]

^<<v44-18-7,7>>^ Saindo dali, entrou na casa de um homem chamado Tício Justo, que era temente a Deus; a casa dele ficava ao lado da sinagoga.

[[v44-18-8]]

^<<v44-18-8,8>>^ Crispo, o chefe da sinagoga, creu no Senhor, com toda a sua casa; também muitos dos coríntios, ouvindo, creram e foram batizados.

[[v44-18-9]]

^<<v44-18-9,9>>^ Certa noite Paulo teve uma visão em que o Senhor lhe disse: — Não tenha medo! Pelo contrário, fale e não fique calado,

[[v44-18-10]]

^<<v44-18-10,10>>^ porque eu estou com você, e ninguém ousará lhe fazer mal, pois tenho muito povo nesta cidade.

[[v44-18-11]]

^<<v44-18-11,11>>^ Assim, Paulo permaneceu em Corinto um ano e seis meses, ensinando entre eles a palavra de Deus.

[[v44-18-12]]

^<<v44-18-12,12>>^ Quando Gálio era procônsul da Acaia, os judeus, de comum acordo, se levantaram contra Paulo e o levaram ao tribunal,

[[v44-18-13]]

^<<v44-18-13,13>>^ dizendo: — Este homem quer persuadir as pessoas a adorar a Deus de um modo contrário à lei.

[[v44-18-14]]

^<<v44-18-14,14>>^ Quando Paulo ia falar, Gálio disse aos judeus: — Se fosse, de fato, alguma injustiça ou crime de maior gravidade, ó judeus, eu teria motivo para acolher a queixa que vocês estão trazendo.

[[v44-18-15]]

^<<v44-18-15,15>>^ Mas como é uma questão de palavras, de nomes e da própria lei de vocês, resolvam isso vocês mesmos; eu não quero ser juiz dessas coisas!

[[v44-18-16]]

^<<v44-18-16,16>>^ E os expulsou do tribunal.

[[v44-18-17]]

^<<v44-18-17,17>>^ Então todos agarraram Sóstenes, o chefe da sinagoga, e começaram a espancá-lo diante do tribunal; Gálio, todavia, não se incomodava com estas coisas.

[[v44-18-18]]

^<<v44-18-18,18>>^ Paulo ficou ainda muitos dias em Corinto. Por fim, despedindo-se dos irmãos, navegou para a Síria, levando em sua companhia Priscila e Áquila. Antes de embarcar, rapou a cabeça em Cencreia, porque tinha feito um voto.

[[v44-18-19]]

^<<v44-18-19,19>>^ Quando chegaram a Éfeso, Paulo deixou ali Priscila e Áquila. Ele, porém, entrando na sinagoga, pregava aos judeus.

[[v44-18-20]]

^<<v44-18-20,20>>^ Pediram-lhe que ficasse mais algum tempo, mas Paulo não quis.

[[v44-18-21]]

^<<v44-18-21,21>>^ Ao se despedir, disse: — Se Deus quiser, virei visitá-los outra vez. E, embarcando, partiu de Éfeso.

[[v44-18-22]]

^<<v44-18-22,22>>^ Chegando a Cesareia, foi logo para Jerusalém. E, tendo saudado a igreja, seguiu para Antioquia.

[[v44-18-23]]

^<<v44-18-23,23>>^ Havendo passado ali algum tempo, saiu, atravessando sucessivamente a região da Galácia e Frígia, fortalecendo todos os discípulos.

[[v44-18-24]]

^<<v44-18-24,24>>^ Nesse meio-tempo, chegou a Éfeso um judeu, natural de Alexandria, chamado Apolo, homem eloquente e poderoso nas Escrituras.

[[v44-18-25]]

^<<v44-18-25,25>>^ Ele era instruído no caminho do Senhor; e, sendo fervoroso de espírito, falava e ensinava com precisão a respeito de Jesus, conhecendo apenas o batismo de João.

[[v44-18-26]]

^<<v44-18-26,26>>^ Apolo começou a falar ousadamente na sinagoga. Quando Priscila e Áquila o ouviram falar, levaram-no consigo e, com mais exatidão, lhe expuseram o caminho de Deus.

[[v44-18-27]]

^<<v44-18-27,27>>^ Quando ele resolveu percorrer a Acaia, os irmãos o animaram e escreveram aos discípulos para que o recebessem bem. Tendo chegado, Apolo auxiliou muito aqueles que, mediante a graça, haviam crido;

[[v44-18-28]]

^<<v44-18-28,28>>^ porque, com grande poder, convencia publicamente os judeus, provando, por meio das Escrituras, que Jesus é o Cristo.

'''

xref:044-atos/044-atos-017.adoc#v44-17-0[&#60; Capítulo Anterior] | <<v44-18-0,Topo>> | xref:044-atos/044-atos-019.adoc#v44-19-0[Próximo Capítulo &#62;]