include::./index.adoc[]

[[v44-16-0]]
=== Atos, 16
// naa ?, NAA - Nova Almeida Atualizada

[[v44-16-1]]

^<<v44-16-1,1>>^ Paulo chegou também a Derbe e a Listra. Havia ali um discípulo chamado Timóteo, filho de uma judia crente, mas de pai grego.

[[v44-16-2]]

^<<v44-16-2,2>>^ Os irmãos em Listra e Icônio davam bom testemunho dele.

[[v44-16-3]]

^<<v44-16-3,3>>^ Paulo queria que Timóteo fosse em sua companhia e, por isso, circuncidou-o por causa dos judeus daqueles lugares; pois todos sabiam que o pai dele era grego.

[[v44-16-4]]

^<<v44-16-4,4>>^ Ao passar pelas cidades, entregavam aos irmãos as decisões tomadas pelos apóstolos e presbíteros de Jerusalém, para que as observassem.

[[v44-16-5]]

^<<v44-16-5,5>>^ Assim, as igrejas eram fortalecidas na fé e, dia a dia, aumentavam em número.

[[v44-16-6]]

^<<v44-16-6,6>>^ E percorreram a região frígio-gálata, tendo sido impedidos pelo Espírito Santo de pregar a palavra na província da Ásia.

[[v44-16-7]]

^<<v44-16-7,7>>^ Chegando perto de Mísia, tentaram ir para Bitínia, mas o Espírito de Jesus não o permitiu.

[[v44-16-8]]

^<<v44-16-8,8>>^ E, tendo contornado Mísia, foram a Trôade.

[[v44-16-9]]

^<<v44-16-9,9>>^ À noite, Paulo teve uma visão na qual um homem da Macedônia estava em pé e lhe rogava, dizendo: — Passe à Macedônia e ajude-nos.

[[v44-16-10]]

^<<v44-16-10,10>>^ Assim que Paulo teve a visão, imediatamente procuramos partir para aquele destino, concluindo que Deus nos havia chamado para lhes anunciar o evangelho.

[[v44-16-11]]

^<<v44-16-11,11>>^ Tendo, pois, navegado de Trôade, fomos diretamente para Samotrácia e, no dia seguinte, a Neápolis.

[[v44-16-12]]

^<<v44-16-12,12>>^ Dali fomos a Filipos, cidade da Macedônia, primeira do distrito e colônia romana. Nesta cidade, permanecemos alguns dias.

[[v44-16-13]]

^<<v44-16-13,13>>^ No sábado, saímos da cidade para a beira do rio, onde nos pareceu haver um lugar de oração; e, assentando-nos, falamos às mulheres que haviam se reunido ali.

[[v44-16-14]]

^<<v44-16-14,14>>^ Certa mulher, chamada Lídia, da cidade de Tiatira, vendedora de púrpura, temente a Deus, nos escutava; o Senhor lhe abriu o coração para que estivesse atenta ao que Paulo dizia.

[[v44-16-15]]

^<<v44-16-15,15>>^ Depois de ser batizada, ela e toda a sua casa, nos fez este pedido: — Se julgam que eu sou fiel ao Senhor, venham ficar na minha casa. E nos constrangeu a isso.

[[v44-16-16]]

^<<v44-16-16,16>>^ Aconteceu que, indo nós para o lugar de oração, veio ao nosso encontro uma jovem possuída de espírito adivinhador, a qual, adivinhando, dava grande lucro aos seus donos.

[[v44-16-17]]

^<<v44-16-17,17>>^ Seguindo a Paulo e a nós, gritava, dizendo: — Estes homens são servos do Deus Altíssimo e anunciam a vocês o caminho da salvação.

[[v44-16-18]]

^<<v44-16-18,18>>^ Isto se repetiu por muitos dias. Então Paulo, já indignado, voltando-se, disse ao espírito: — Em nome de Jesus Cristo, eu ordeno que você saia dela. E, na mesma hora, o espírito saiu.

[[v44-16-19]]

^<<v44-16-19,19>>^ Quando os donos da jovem viram que se havia desfeito a esperança do lucro, agarraram Paulo e Silas e os arrastaram para a praça, à presença das autoridades.

[[v44-16-20]]

^<<v44-16-20,20>>^ E, levando-os aos magistrados, disseram: — Estes homens, sendo judeus, perturbam a nossa cidade,

[[v44-16-21]]

^<<v44-16-21,21>>^ propagando costumes que não podemos aceitar, nem praticar, porque somos romanos.

[[v44-16-22]]

^<<v44-16-22,22>>^ Então a multidão se levantou unida contra eles, e os magistrados, rasgando-lhes as roupas, mandaram açoitá-los com varas.

[[v44-16-23]]

^<<v44-16-23,23>>^ E, depois de lhes darem muitos açoites, os lançaram na prisão, ordenando ao carcereiro que os guardasse com toda a segurança.

[[v44-16-24]]

^<<v44-16-24,24>>^ Este, recebendo tal ordem, levou-os para o cárcere interior e prendeu os pés deles no tronco.

[[v44-16-25]]

^<<v44-16-25,25>>^ Por volta da meia-noite, Paulo e Silas oravam e cantavam louvores a Deus, e os demais companheiros de prisão escutavam.

[[v44-16-26]]

^<<v44-16-26,26>>^ De repente, sobreveio tamanho terremoto, que sacudiu os alicerces da prisão; todas as portas se abriram e as correntes de todos os presos se soltaram.

[[v44-16-27]]

^<<v44-16-27,27>>^ O carcereiro despertou do sono e, vendo abertas as portas da prisão, puxando da espada, ia suicidar-se, pois pensou que os presos tinham fugido.

[[v44-16-28]]

^<<v44-16-28,28>>^ Mas Paulo gritou bem alto: — Não faça nenhum mal a si mesmo! Estamos todos aqui.

[[v44-16-29]]

^<<v44-16-29,29>>^ Então o carcereiro, tendo pedido uma luz, entrou correndo e, trêmulo, prostrou-se diante de Paulo e Silas.

[[v44-16-30]]

^<<v44-16-30,30>>^ Depois, trazendo-os para fora, disse: — Senhores, que devo fazer para que seja salvo?

[[v44-16-31]]

^<<v44-16-31,31>>^ Eles responderam: — Creia no Senhor Jesus e você será salvo — você e toda a sua casa.

[[v44-16-32]]

^<<v44-16-32,32>>^ E pregaram a palavra de Deus ao carcereiro e a todos os que faziam parte da casa dele.

[[v44-16-33]]

^<<v44-16-33,33>>^ Naquela mesma hora da noite, cuidando deles, lavou-lhes as feridas dos açoites. Logo a seguir, ele e todos os membros da casa dele foram batizados.

[[v44-16-34]]

^<<v44-16-34,34>>^ Então, levando-os para a sua própria casa, deu-lhes de comer; e, com todos os seus, manifestava grande alegria por ter crido em Deus.

[[v44-16-35]]

^<<v44-16-35,35>>^ Quando amanheceu, os magistrados enviaram oficiais de justiça, com a seguinte ordem para o carcereiro: — Ponha aqueles homens em liberdade.

[[v44-16-36]]

^<<v44-16-36,36>>^ Então o carcereiro comunicou isso a Paulo, dizendo: — Os magistrados ordenaram que vocês fossem postos em liberdade. Portanto, vocês podem sair. Vão em paz.

[[v44-16-37]]

^<<v44-16-37,37>>^ Paulo, porém, lhes disse: — Sem ter havido processo formal contra nós, nos açoitaram publicamente e nos jogaram na cadeia, sendo nós cidadãos romanos. Querem agora nos mandar embora sem maior alarde? Nada disso! Pelo contrário, que eles venham e, pessoalmente, nos ponham em liberdade.

[[v44-16-38]]

^<<v44-16-38,38>>^ Os oficiais de justiça comunicaram isso aos magistrados. Quando estes souberam que Paulo e Silas eram cidadãos romanos, ficaram com medo.

[[v44-16-39]]

^<<v44-16-39,39>>^ Então foram até eles e lhes pediram desculpas; e, relaxando-lhes a prisão, pediram que se retirassem da cidade.

[[v44-16-40]]

^<<v44-16-40,40>>^ Tendo saído da prisão, Paulo e Silas dirigiram-se para a casa de Lídia e, vendo os irmãos, os animaram. Depois partiram.

'''

xref:044-atos/044-atos-015.adoc#v44-15-0[&#60; Capítulo Anterior] | <<v44-16-0,Topo>> | xref:044-atos/044-atos-017.adoc#v44-17-0[Próximo Capítulo &#62;]