include::./index.adoc[]

[[v44-13-0]]
=== Atos, 13
// naa ?, NAA - Nova Almeida Atualizada

[[v44-13-1]]

^<<v44-13-1,1>>^ Havia na igreja de Antioquia profetas e mestres: Barnabé; Simeão, chamado Níger; Lúcio, de Cirene; Manaém, que tinha sido criado com Herodes, o tetrarca; e Saulo.

[[v44-13-2]]

^<<v44-13-2,2>>^ Enquanto eles estavam adorando o Senhor e jejuando, o Espírito Santo disse: — Separem-me, agora, Barnabé e Saulo para a obra a que os tenho chamado.

[[v44-13-3]]

^<<v44-13-3,3>>^ Então, jejuando e orando, e impondo as mãos sobre eles, os despediram.

[[v44-13-4]]

^<<v44-13-4,4>>^ Barnabé e Saulo, enviados pelo Espírito Santo, foram até Selêucia e dali navegaram para Chipre.

[[v44-13-5]]

^<<v44-13-5,5>>^ Quando chegaram a Salamina, começaram a anunciar a palavra de Deus nas sinagogas judaicas. Tinham também João como auxiliar.

[[v44-13-6]]

^<<v44-13-6,6>>^ Havendo atravessado toda a ilha até Pafos, encontraram certo judeu, de nome Barjesus, que praticava magia e era falso profeta.

[[v44-13-7]]

^<<v44-13-7,7>>^ Ele estava com o procônsul Sérgio Paulo, que era um homem inteligente. O procônsul, tendo chamado Barnabé e Saulo, desejava ouvir a palavra de Deus.

[[v44-13-8]]

^<<v44-13-8,8>>^ Porém o mago Elimas — e é assim que se traduz o nome dele — se opunha a eles, procurando afastar da fé o procônsul.

[[v44-13-9]]

^<<v44-13-9,9>>^ Mas Saulo, também chamado Paulo, cheio do Espírito Santo, olhando firmemente para Elimas, disse:

[[v44-13-10]]

^<<v44-13-10,10>>^ — Ó filho do diabo, cheio de todo o engano e de toda a maldade, inimigo de toda a justiça, por que você não deixa de perverter os retos caminhos do Senhor?

[[v44-13-11]]

^<<v44-13-11,11>>^ Eis que, agora, a mão do Senhor está contra você, e você ficará cego, não vendo o sol por algum tempo. No mesmo instante, caiu sobre ele névoa e escuridão, e, andando em círculos, procurava quem o guiasse pela mão.

[[v44-13-12]]

^<<v44-13-12,12>>^ Então o procônsul, vendo o que havia acontecido, creu, maravilhado com a doutrina do Senhor.

[[v44-13-13]]

^<<v44-13-13,13>>^ E, navegando de Pafos, Paulo e seus companheiros viajaram a Perge da Panfília. João, porém, deixando-os, voltou para Jerusalém.

[[v44-13-14]]

^<<v44-13-14,14>>^ Mas eles, saindo de Perge, chegaram a Antioquia da Pisídia. No sábado, entraram na sinagoga e sentaram-se.

[[v44-13-15]]

^<<v44-13-15,15>>^ Depois da leitura da Lei e dos Profetas, os chefes da sinagoga mandaram dizer-lhes: — Irmãos, se vocês têm alguma palavra de consolo para o povo, falem.

[[v44-13-16]]

^<<v44-13-16,16>>^ Paulo, levantando-se e fazendo com a mão sinal de silêncio, disse: — Israelitas e todos vocês que temem a Deus, escutem!

[[v44-13-17]]

^<<v44-13-17,17>>^ O Deus do povo de Israel escolheu os nossos pais e exaltou o povo durante a sua peregrinação na terra do Egito, de onde os tirou com braço poderoso.

[[v44-13-18]]

^<<v44-13-18,18>>^ Suportou os maus costumes do povo durante uns quarenta anos no deserto.

[[v44-13-19]]

^<<v44-13-19,19>>^ E, havendo destruído sete nações em Canaã, deu essas terras como herança ao seu povo.

[[v44-13-20]]

^<<v44-13-20,20>>^ Tudo isso levou cerca de quatrocentos e cinquenta anos. Depois disso, lhes deu juízes, até o profeta Samuel.

[[v44-13-21]]

^<<v44-13-21,21>>^ Então eles pediram um rei, e Deus lhes deu Saul, filho de Quis, da tribo de Benjamim, e isto durante quarenta anos.

[[v44-13-22]]

^<<v44-13-22,22>>^ E, tendo tirado Saul, levantou-lhes o rei Davi, do qual também, dando testemunho, disse: "Achei Davi, filho de Jessé, homem segundo o meu coração, que fará toda a minha vontade."

[[v44-13-23]]

^<<v44-13-23,23>>^ Da descendência deste, conforme a promessa, Deus trouxe a Israel o Salvador, que é Jesus.

[[v44-13-24]]

^<<v44-13-24,24>>^ Antes da manifestação dele, João pregou um batismo de arrependimento a todo o povo de Israel.

[[v44-13-25]]

^<<v44-13-25,25>>^ Quando João estava completando a sua carreira, disse: "Quem vocês pensam que sou? Não sou aquele que vocês esperam. Mas depois de mim vem aquele de cujos pés não sou digno de desamarrar as sandálias."

[[v44-13-26]]

^<<v44-13-26,26>>^ — Irmãos, descendência de Abraão e todos vocês que temem a Deus, a nós foi enviada a palavra desta salvação.

[[v44-13-27]]

^<<v44-13-27,27>>^ Pois os moradores e as autoridades de Jerusalém, não conhecendo Jesus nem as palavras dos profetas que são lidas todos os sábados, cumpriram as profecias, quando condenaram Jesus.

[[v44-13-28]]

^<<v44-13-28,28>>^ E, embora não achassem nenhuma causa de morte, pediram a Pilatos que ele fosse morto.

[[v44-13-29]]

^<<v44-13-29,29>>^ Depois de cumprirem tudo o que estava escrito a respeito dele, tirando-o do madeiro, puseram-no em um túmulo.

[[v44-13-30]]

^<<v44-13-30,30>>^ Mas Deus o ressuscitou dentre os mortos,

[[v44-13-31]]

^<<v44-13-31,31>>^ e durante muitos dias ele foi visto pelos que o tinham acompanhado da Galileia para Jerusalém, os quais são agora as suas testemunhas diante do povo.

[[v44-13-32]]

^<<v44-13-32,32>>^ E nós anunciamos a vocês o evangelho da promessa feita aos nossos pais,

[[v44-13-33]]

^<<v44-13-33,33>>^ como Deus a cumpriu plenamente a nós, seus filhos, ressuscitando Jesus, como também está escrito no Salmo número dois: "Você é meu Filho; hoje eu gerei você."

[[v44-13-34]]

^<<v44-13-34,34>>^ — E quanto ao fato de que o ressuscitaria dentre os mortos para que jamais voltasse à corrupção, Deus o expressou desta maneira: "E cumprirei a favor de vocês as santas e fiéis promessas feitas a Davi."

[[v44-13-35]]

^<<v44-13-35,35>>^ — Por isso, também diz em outro Salmo: "Não permitirás que o teu Santo veja corrupção."

[[v44-13-36]]

^<<v44-13-36,36>>^ — Porque tendo Davi, no seu tempo, servido conforme o plano de Deus, morreu, foi sepultado ao lado de seus pais e viu corrupção.

[[v44-13-37]]

^<<v44-13-37,37>>^ Porém aquele a quem Deus ressuscitou não viu corrupção.

[[v44-13-38]]

^<<v44-13-38,38>>^ Portanto, meus irmãos, saibam que é por meio de Jesus que a remissão dos pecados é anunciada a vocês;

[[v44-13-39]]

^<<v44-13-39,39>>^ e, por meio dele, todo o que crê é justificado de todas as coisas das quais vocês não puderam ser justificados pela lei de Moisés.

[[v44-13-40]]

^<<v44-13-40,40>>^ Portanto, tenham cuidado para que não lhes aconteça o que os profetas disseram:

[[v44-13-41]]

^<<v44-13-41,41>>^ "Vejam, ó desprezadores! Fiquem maravilhados e desapareçam, porque, no tempo de vocês, eu realizo obra tal que vocês não acreditarão se alguém lhes contar."

[[v44-13-42]]

^<<v44-13-42,42>>^ Quando Paulo e Barnabé estavam saindo, as pessoas pediram que, no sábado seguinte, lhes falassem estas mesmas palavras.

[[v44-13-43]]

^<<v44-13-43,43>>^ Terminada a reunião na sinagoga, muitos dos judeus e dos prosélitos piedosos seguiram Paulo e Barnabé, e estes, falando com eles, os persuadiam a continuar firmes na graça de Deus.

[[v44-13-44]]

^<<v44-13-44,44>>^ No sábado seguinte, quase toda a cidade se reuniu para ouvir a palavra do Senhor.

[[v44-13-45]]

^<<v44-13-45,45>>^ Mas os judeus, vendo as multidões, ficaram com muita inveja e, blasfemando, contradiziam o que Paulo falava.

[[v44-13-46]]

^<<v44-13-46,46>>^ Então Paulo e Barnabé, falando ousadamente, disseram: — Era necessário pregar a palavra de Deus primeiro a vocês. Mas, como vocês a rejeitam e se julgam indignos da vida eterna, eis que nos voltamos para os gentios.

[[v44-13-47]]

^<<v44-13-47,47>>^ Porque o Senhor assim nos determinou: "Eu coloquei você como luz dos gentios, a fim de que você seja para salvação até os confins da terra."

[[v44-13-48]]

^<<v44-13-48,48>>^ Os gentios, ouvindo isto, se alegravam e glorificavam a palavra do Senhor. E creram todos os que haviam sido destinados para a vida eterna.

[[v44-13-49]]

^<<v44-13-49,49>>^ E a palavra do Senhor se espalhou por toda aquela região.

[[v44-13-50]]

^<<v44-13-50,50>>^ Mas os judeus instigaram as mulheres piedosas de alta posição e os principais da cidade e levantaram perseguição contra Paulo e Barnabé, expulsando-os do seu território.

[[v44-13-51]]

^<<v44-13-51,51>>^ E estes, sacudindo contra eles o pó dos pés, foram para Icônio.

[[v44-13-52]]

^<<v44-13-52,52>>^ Os discípulos, porém, estavam cheios de alegria e do Espírito Santo.

'''

xref:044-atos/044-atos-012.adoc#v44-12-0[&#60; Capítulo Anterior] | <<v44-13-0,Topo>> | xref:044-atos/044-atos-014.adoc#v44-14-0[Próximo Capítulo &#62;]