include::./index.adoc[]

[[v44-20-0]]
=== Atos, 20
// naa ?, NAA - Nova Almeida Atualizada

[[v44-20-1]]

^<<v44-20-1,1>>^ Cessado o tumulto, Paulo mandou chamar os discípulos e, tendo-os encorajado, despediu-se e foi para a Macedônia.

[[v44-20-2]]

^<<v44-20-2,2>>^ Havendo atravessado aquelas terras, fortalecendo os discípulos com muitas exortações, dirigiu-se para a Grécia,

[[v44-20-3]]

^<<v44-20-3,3>>^ onde se demorou três meses. Quando estava para embarcar rumo à Síria, houve uma conspiração por parte dos judeus contra ele. Então decidiu voltar pela Macedônia.

[[v44-20-4]]

^<<v44-20-4,4>>^ Acompanharam-no Sópatro, de Bereia, filho de Pirro; Aristarco e Secundo, de Tessalônica; Gaio, de Derbe; Timóteo; e também Tíquico e Trófimo, da província da Ásia.

[[v44-20-5]]

^<<v44-20-5,5>>^ Estes nos precederam, ficando à nossa espera em Trôade.

[[v44-20-6]]

^<<v44-20-6,6>>^ Depois dos dias dos pães sem fermento, navegamos de Filipos e, em cinco dias, nos encontramos com eles em Trôade, onde passamos uma semana.

[[v44-20-7]]

^<<v44-20-7,7>>^ No primeiro dia da semana, nós nos reunimos a fim de partir o pão. Paulo, que pretendia viajar no dia seguinte, falava aos irmãos e prolongou a mensagem até a meia-noite.

[[v44-20-8]]

^<<v44-20-8,8>>^ Havia muitas lâmpadas no cenáculo onde estávamos reunidos.

[[v44-20-9]]

^<<v44-20-9,9>>^ Um jovem, chamado Êutico, que estava sentado numa janela, adormecendo profundamente durante a prolongada mensagem de Paulo, vencido pelo sono, caiu do terceiro andar abaixo. Quando o levantaram, estava morto.

[[v44-20-10]]

^<<v44-20-10,10>>^ Mas Paulo desceu, inclinou-se sobre ele e, abraçando-o, disse: — Não fiquem alvoroçados, pois ele está vivo.

[[v44-20-11]]

^<<v44-20-11,11>>^ Subindo de novo, Paulo partiu o pão e comeu. E lhes falou ainda muito tempo até o amanhecer. E, assim, partiu.

[[v44-20-12]]

^<<v44-20-12,12>>^ Então conduziram vivo o rapaz e sentiram-se grandemente confortados.

[[v44-20-13]]

^<<v44-20-13,13>>^ Nós, porém, prosseguindo, embarcamos e navegamos para Assôs, onde devíamos receber Paulo, porque assim nos havia sido determinado, devendo ele ir por terra.

[[v44-20-14]]

^<<v44-20-14,14>>^ Quando se reuniu conosco em Assôs, nós o recebemos a bordo e fomos a Mitilene.

[[v44-20-15]]

^<<v44-20-15,15>>^ Dali, navegando, no dia seguinte passamos diante de Quios. Levamos mais um dia até Samos e, um dia depois, chegamos a Mileto.

[[v44-20-16]]

^<<v44-20-16,16>>^ Paulo já tinha resolvido não aportar em Éfeso, pois não queria demorar-se na província da Ásia. Ele tinha pressa, pois queria, caso lhe fosse possível, passar o dia de Pentecostes em Jerusalém.

[[v44-20-17]]

^<<v44-20-17,17>>^ De Mileto, Paulo enviou uma mensagem a Éfeso, pedindo aos presbíteros da igreja que se encontrassem com ele.

[[v44-20-18]]

^<<v44-20-18,18>>^ E, quando chegaram, Paulo lhes disse: — Vocês sabem como me conduzi entre vocês em todo o tempo, desde o primeiro dia em que entrei na província da Ásia,

[[v44-20-19]]

^<<v44-20-19,19>>^ servindo o Senhor com toda a humildade, com lágrimas e com as provações que me sobrevieram pelas ciladas dos judeus.

[[v44-20-20]]

^<<v44-20-20,20>>^ Vocês sabem que jamais deixei de anunciar o que fosse proveitoso e de ensinar isso a vocês publicamente e também de casa em casa,

[[v44-20-21]]

^<<v44-20-21,21>>^ testemunhando tanto a judeus como a gregos o arrependimento para com Deus e a fé em nosso Senhor Jesus Cristo.

[[v44-20-22]]

^<<v44-20-22,22>>^ E, agora, impelido pelo Espírito, vou para Jerusalém, não sabendo o que ali vai me acontecer,

[[v44-20-23]]

^<<v44-20-23,23>>^ exceto que o Espírito Santo, de cidade em cidade, me assegura que prisões e sofrimentos estão à minha espera.

[[v44-20-24]]

^<<v44-20-24,24>>^ Porém em nada considero a vida preciosa para mim mesmo, desde que eu complete a minha carreira e o ministério que recebi do Senhor Jesus para testemunhar o evangelho da graça de Deus.

[[v44-20-25]]

^<<v44-20-25,25>>^ — E agora eu sei que todos vocês, em cujo meio passei pregando o Reino, não mais verão o meu rosto.

[[v44-20-26]]

^<<v44-20-26,26>>^ Portanto, no dia de hoje testifico diante de vocês que estou limpo do sangue de todos,

[[v44-20-27]]

^<<v44-20-27,27>>^ porque jamais deixei de lhes anunciar todo o plano de Deus.

[[v44-20-28]]

^<<v44-20-28,28>>^ Cuidem de vocês mesmos e de todo o rebanho no qual o Espírito Santo os colocou como bispos, para pastorearem a igreja de Deus, a qual ele comprou com o seu próprio sangue.

[[v44-20-29]]

^<<v44-20-29,29>>^ Eu sei que, depois da minha partida, aparecerão no meio de vocês lobos vorazes, que não pouparão o rebanho.

[[v44-20-30]]

^<<v44-20-30,30>>^ E que até mesmo entre vocês se levantarão homens falando coisas pervertidas para arrastar os discípulos atrás de si.

[[v44-20-31]]

^<<v44-20-31,31>>^ Portanto, vigiem, lembrando que, durante três anos, noite e dia, não cessei de admoestar, com lágrimas, cada um de vocês.

[[v44-20-32]]

^<<v44-20-32,32>>^ — Agora, pois, eu os entrego aos cuidados de Deus e à palavra da sua graça, que tem poder para edificá-los e dar herança entre todos os que são santificados.

[[v44-20-33]]

^<<v44-20-33,33>>^ De ninguém cobicei prata, nem ouro, nem roupas;

[[v44-20-34]]

^<<v44-20-34,34>>^ vocês mesmos sabem que estas minhas mãos serviram para o que era necessário a mim e aos que estavam comigo.

[[v44-20-35]]

^<<v44-20-35,35>>^ Em tudo tenho mostrado a vocês que, trabalhando assim, é preciso socorrer os necessitados e lembrar das palavras do próprio Senhor Jesus: "Mais bem-aventurado é dar do que receber."

[[v44-20-36]]

^<<v44-20-36,36>>^ Tendo dito isso, ajoelhando-se, Paulo orou com todos eles.

[[v44-20-37]]

^<<v44-20-37,37>>^ Então houve grande pranto entre todos, e, abraçando Paulo, o beijavam,

[[v44-20-38]]

^<<v44-20-38,38>>^ entristecidos especialmente pela palavra que ele tinha dito: que não mais veriam o seu rosto. E eles o acompanharam até o navio.

'''

xref:044-atos/044-atos-019.adoc#v44-19-0[&#60; Capítulo Anterior] | <<v44-20-0,Topo>> | xref:044-atos/044-atos-021.adoc#v44-21-0[Próximo Capítulo &#62;]