include::./index.adoc[]

[[v44-17-0]]
=== Atos, 17
// naa ?, NAA - Nova Almeida Atualizada

[[v44-17-1]]

^<<v44-17-1,1>>^ Tendo passado por Anfípolis e Apolônia, Paulo e Silas chegaram a Tessalônica, onde havia uma sinagoga dos judeus.

[[v44-17-2]]

^<<v44-17-2,2>>^ Paulo, segundo o seu costume, foi procurá-los e, por três sábados, discutiu com eles a respeito das Escrituras,

[[v44-17-3]]

^<<v44-17-3,3>>^ expondo e demonstrando ter sido necessário que o Cristo padecesse e ressuscitasse dos mortos. Paulo dizia: — Este Jesus, que eu anuncio a vocês, é o Cristo.

[[v44-17-4]]

^<<v44-17-4,4>>^ Alguns deles foram persuadidos e se juntaram a Paulo e Silas. O mesmo aconteceu com numerosa multidão de gregos piedosos e muitas mulheres importantes.

[[v44-17-5]]

^<<v44-17-5,5>>^ Os judeus, porém, movidos de inveja, trazendo consigo alguns homens maus dentre a malandragem, reuniram uma multidão e provocaram um tumulto na cidade. E, atacando de surpresa a casa de Jasom, procuravam trazer Paulo e Silas para o meio do povo.

[[v44-17-6]]

^<<v44-17-6,6>>^ Porém, não os encontrando, arrastaram Jasom e alguns irmãos diante das autoridades, gritando: — Estes que promovem tumulto em todo o mundo chegaram também aqui,

[[v44-17-7]]

^<<v44-17-7,7>>^ e Jasom os hospedou na casa dele. Todos estes agem contra os decretos de César, dizendo que existe outro rei, chamado Jesus.

[[v44-17-8]]

^<<v44-17-8,8>>^ Tanto a multidão como as autoridades ficaram agitadas ao ouvir estas palavras.

[[v44-17-9]]

^<<v44-17-9,9>>^ Porém, depois de terem recebido deles a fiança estipulada, as autoridades soltaram Jasom e os outros.

[[v44-17-10]]

^<<v44-17-10,10>>^ E logo, durante a noite, os irmãos enviaram Paulo e Silas para Bereia. Ali chegados, dirigiram-se à sinagoga dos judeus.

[[v44-17-11]]

^<<v44-17-11,11>>^ Ora, estes de Bereia eram mais nobres do que os de Tessalônica, pois receberam a palavra com toda a avidez, examinando as Escrituras todos os dias para ver se as coisas eram, de fato, assim.

[[v44-17-12]]

^<<v44-17-12,12>>^ Com isso, muitos deles creram, mulheres gregas de alta posição social e muitos homens.

[[v44-17-13]]

^<<v44-17-13,13>>^ Mas, logo que os judeus de Tessalônica souberam que a palavra de Deus era anunciada por Paulo também em Bereia, foram lá agitar e perturbar o povo.

[[v44-17-14]]

^<<v44-17-14,14>>^ Então os irmãos fizeram com que Paulo fosse imediatamente para os lados do mar. Porém Silas e Timóteo continuaram em Bereia.

[[v44-17-15]]

^<<v44-17-15,15>>^ Os responsáveis por Paulo levaram-no até Atenas e regressaram trazendo ordem a Silas e Timóteo para que fossem encontrá-lo o mais depressa possível.

[[v44-17-16]]

^<<v44-17-16,16>>^ Enquanto Paulo os esperava em Atenas, o seu espírito se revoltava em face da idolatria dominante na cidade.

[[v44-17-17]]

^<<v44-17-17,17>>^ Por isso, falava na sinagoga com os judeus e os gentios piedosos; também na praça, todos os dias, com os que se encontravam ali.

[[v44-17-18]]

^<<v44-17-18,18>>^ E alguns dos filósofos epicureus e estoicos discutiam com ele, havendo quem perguntasse: — Que quer dizer esse tagarela? Outros diziam: — Parece pregador de deuses estranhos. Diziam isso porque Paulo pregava Jesus e a ressurreição.

[[v44-17-19]]

^<<v44-17-19,19>>^ Então, tomando-o consigo, levaram-no ao Areópago, dizendo: — Podemos saber que nova doutrina é essa que você ensina?

[[v44-17-20]]

^<<v44-17-20,20>>^ Pois você nos traz aos ouvidos coisas estranhas e queremos saber o que vem a ser isso.

[[v44-17-21]]

^<<v44-17-21,21>>^ Acontece que todos os de Atenas e os estrangeiros residentes não se ocupavam com outra coisa senão dizer ou ouvir as últimas novidades.

[[v44-17-22]]

^<<v44-17-22,22>>^ Então Paulo, levantando-se no meio do Areópago, disse: — Senhores atenienses! Percebo que em tudo vocês são bastante religiosos,

[[v44-17-23]]

^<<v44-17-23,23>>^ porque, andando pela cidade e observando os objetos de culto que vocês têm, encontrei também um altar no qual aparece a seguinte inscrição: " Ao Deus Desconhecido ". Pois esse que vocês adoram sem conhecer é precisamente aquele que eu lhes anuncio.

[[v44-17-24]]

^<<v44-17-24,24>>^ — O Deus que fez o mundo e tudo o que nele existe, sendo ele Senhor do céu e da terra, não habita em santuários feitos por mãos humanas;

[[v44-17-25]]

^<<v44-17-25,25>>^ nem é servido por mãos humanas, como se precisasse de alguma coisa, pois ele mesmo é quem a todos dá vida, respiração e tudo mais.

[[v44-17-26]]

^<<v44-17-26,26>>^ De um só homem fez todas as nações para habitarem sobre a face da terra, havendo fixado os tempos previamente estabelecidos e os limites da sua habitação;

[[v44-17-27]]

^<<v44-17-27,27>>^ para buscarem Deus se, porventura, tateando, o possam achar, ainda que não esteja longe de cada um de nós;

[[v44-17-28]]

^<<v44-17-28,28>>^ pois nele vivemos, nos movemos e existimos, como alguns dos poetas de vocês disseram: "Porque dele também somos geração."

[[v44-17-29]]

^<<v44-17-29,29>>^ Portanto, visto que somos geração de Deus, não devemos pensar que a divindade é semelhante ao ouro, à prata ou à pedra, trabalhados pela arte e imaginação do homem.

[[v44-17-30]]

^<<v44-17-30,30>>^ Deus não levou em conta os tempos da ignorância, mas agora ele ordena a todas as pessoas, em todos os lugares, que se arrependam.

[[v44-17-31]]

^<<v44-17-31,31>>^ Porque Deus estabeleceu um dia em que julgará o mundo com justiça, por meio de um homem que escolheu. E deu certeza disso a todos, ressuscitando-o dentre os mortos.

[[v44-17-32]]

^<<v44-17-32,32>>^ Quando ouviram falar de ressurreição de mortos, uns zombaram, e outros disseram: — A respeito disso ouviremos você em outra ocasião.

[[v44-17-33]]

^<<v44-17-33,33>>^ A essa altura, Paulo se retirou do meio deles.

[[v44-17-34]]

^<<v44-17-34,34>>^ Houve, porém, alguns homens que se juntaram a ele e creram; entre eles estava Dionísio, o areopagita, uma mulher chamada Dâmaris e, com eles, mais algumas pessoas.

'''

xref:044-atos/044-atos-016.adoc#v44-16-0[&#60; Capítulo Anterior] | <<v44-17-0,Topo>> | xref:044-atos/044-atos-018.adoc#v44-18-0[Próximo Capítulo &#62;]