include::./index.adoc[]

[[v44-10-0]]
=== Atos, 10
// naa ?, NAA - Nova Almeida Atualizada

[[v44-10-1]]

^<<v44-10-1,1>>^ Em Cesareia morava um homem chamado Cornélio, que era centurião de uma companhia do exército chamada Italiana.

[[v44-10-2]]

^<<v44-10-2,2>>^ Era piedoso e temente a Deus com toda a sua casa, fazendo muitas esmolas ao povo e orando sempre a Deus.

[[v44-10-3]]

^<<v44-10-3,3>>^ Um dia, por volta das três horas da tarde, durante uma visão, esse homem viu claramente um anjo de Deus que se aproximou dele e lhe disse:

[[v44-10-4]]

^<<v44-10-4,4>>^ — Cornélio! Este, fixando nele os olhos e possuído de temor, perguntou: — O que é, Senhor? E o anjo lhe disse: — As suas orações e as suas esmolas subiram para memória diante de Deus.

[[v44-10-5]]

^<<v44-10-5,5>>^ Agora envie mensageiros a Jope e mande chamar Simão, que também é chamado de Pedro.

[[v44-10-6]]

^<<v44-10-6,6>>^ Ele está hospedado com Simão, curtidor, cuja residência está situada à beira-mar.

[[v44-10-7]]

^<<v44-10-7,7>>^ Logo que o anjo que lhe falava se retirou, Cornélio chamou dois dos seus servos e um soldado piedoso dos que estavam a seu serviço

[[v44-10-8]]

^<<v44-10-8,8>>^ e, depois de lhes explicar tudo, mandou que fossem a Jope.

[[v44-10-9]]

^<<v44-10-9,9>>^ No dia seguinte, enquanto eles viajavam e já estavam perto da cidade de Jope, Pedro subiu ao terraço, por volta do meio-dia, a fim de orar.

[[v44-10-10]]

^<<v44-10-10,10>>^ Estando com fome, quis comer; mas, enquanto lhe preparavam a comida, sobreveio-lhe um êxtase.

[[v44-10-11]]

^<<v44-10-11,11>>^ Viu o céu aberto e um objeto como se fosse um grande lençol, que descia do céu e era baixado à terra pelas quatro pontas,

[[v44-10-12]]

^<<v44-10-12,12>>^ contendo todo tipo de quadrúpedes, répteis da terra e aves do céu.

[[v44-10-13]]

^<<v44-10-13,13>>^ E ouviu-se uma voz que se dirigia a ele: — Levante-se, Pedro! Mate e coma.

[[v44-10-14]]

^<<v44-10-14,14>>^ Mas Pedro respondeu: — De modo nenhum, Senhor! Porque nunca comi nada que fosse impuro ou imundo.

[[v44-10-15]]

^<<v44-10-15,15>>^ Pela segunda vez, a voz lhe falou: — Não considere impuro aquilo que Deus purificou.

[[v44-10-16]]

^<<v44-10-16,16>>^ Isso aconteceu três vezes, e, em seguida, aquele objeto foi levado de volta para o céu.

[[v44-10-17]]

^<<v44-10-17,17>>^ Enquanto Pedro estava perplexo sobre qual seria o significado da visão, eis que os homens enviados por Cornélio, tendo perguntado pela casa de Simão, pararam junto à porta.

[[v44-10-18]]

^<<v44-10-18,18>>^ Chamando, perguntaram se ali estava hospedado Simão, que também é chamado de Pedro.

[[v44-10-19]]

^<<v44-10-19,19>>^ Enquanto Pedro meditava a respeito da visão, o Espírito lhe disse: — Estão aí três homens à sua procura.

[[v44-10-20]]

^<<v44-10-20,20>>^ Portanto, levante-se, desça e vá com eles, sem hesitar; porque eu os enviei.

[[v44-10-21]]

^<<v44-10-21,21>>^ Então Pedro desceu e disse àqueles homens: — Eu sou a pessoa que vocês estão procurando. O que os traz até aqui?

[[v44-10-22]]

^<<v44-10-22,22>>^ Então disseram: — O centurião Cornélio, homem reto e temente a Deus e tendo bom testemunho de toda a nação judaica, foi instruído por um santo anjo a mandar chamar você para a casa dele e ouvir o que você tem a dizer.

[[v44-10-23]]

^<<v44-10-23,23>>^ Pedro, então, convidando-os a entrar, hospedou-os. No dia seguinte, Pedro se aprontou e foi com eles. Também alguns irmãos dos que moravam em Jope foram com ele.

[[v44-10-24]]

^<<v44-10-24,24>>^ No dia seguinte, Pedro chegou a Cesareia. Cornélio estava esperando por eles, tendo reunido os seus parentes e os amigos mais íntimos.

[[v44-10-25]]

^<<v44-10-25,25>>^ Quando Pedro estava por entrar, Cornélio foi ao seu encontro e, prostrando-se aos pés dele, o adorou.

[[v44-10-26]]

^<<v44-10-26,26>>^ Mas Pedro o levantou, dizendo: — Levante-se, porque eu também sou apenas um homem.

[[v44-10-27]]

^<<v44-10-27,27>>^ Falando com ele, Pedro entrou, encontrando muitos reunidos ali,

[[v44-10-28]]

^<<v44-10-28,28>>^ a quem se dirigiu, dizendo: — Vocês bem sabem que um judeu está proibido de se juntar a um gentio ou de entrar na casa dele. Mas Deus me mostrou que não devo considerar ninguém impuro ou imundo.

[[v44-10-29]]

^<<v44-10-29,29>>^ Por isso, uma vez chamado, vim sem vacilar. E agora pergunto: Por que motivo vocês mandaram me chamar?

[[v44-10-30]]

^<<v44-10-30,30>>^ Cornélio respondeu: — Faz hoje quatro dias que, mais ou menos por esta hora, às três da tarde, eu estava orando em minha casa. De repente, se apresentou diante de mim um homem vestido com roupas resplandecentes

[[v44-10-31]]

^<<v44-10-31,31>>^ que disse: "Cornélio, a sua oração foi ouvida e as suas esmolas foram lembradas na presença de Deus.

[[v44-10-32]]

^<<v44-10-32,32>>^ Envie, pois, alguém a Jope e mande chamar Simão, que também é chamado de Pedro; ele está hospedado na casa de Simão, curtidor, à beira-mar."

[[v44-10-33]]

^<<v44-10-33,33>>^ Portanto, sem demora, mandei chamá-lo, e você fez muito bem em vir. Agora estamos todos aqui, na presença de Deus, prontos para ouvir tudo o que o Senhor ordenou a você.

[[v44-10-34]]

^<<v44-10-34,34>>^ Então Pedro começou a falar. Ele disse: — Reconheço por verdade que Deus não trata as pessoas com parcialidade;

[[v44-10-35]]

^<<v44-10-35,35>>^ pelo contrário, em qualquer nação, aquele que o teme e faz o que é justo lhe é aceitável.

[[v44-10-36]]

^<<v44-10-36,36>>^ Esta é a palavra que Deus enviou aos filhos de Israel, anunciando-lhes o evangelho da paz, por meio de Jesus Cristo. Este é o Senhor de todos.

[[v44-10-37]]

^<<v44-10-37,37>>^ Vocês sabem o que aconteceu em toda a Judeia, tendo começado na Galileia depois do batismo que João pregou,

[[v44-10-38]]

^<<v44-10-38,38>>^ como Deus ungiu a Jesus de Nazaré com o Espírito Santo e com poder. Jesus andou por toda parte, fazendo o bem e curando todos os oprimidos do diabo, porque Deus estava com ele.

[[v44-10-39]]

^<<v44-10-39,39>>^ E nós somos testemunhas de tudo o que ele fez na terra dos judeus e em Jerusalém. Depois eles o mataram, pendurando-o num madeiro.

[[v44-10-40]]

^<<v44-10-40,40>>^ Mas Deus o ressuscitou no terceiro dia e concedeu que fosse manifesto,

[[v44-10-41]]

^<<v44-10-41,41>>^ não a todo o povo, mas às testemunhas que foram anteriormente escolhidas por Deus, isto é, a nós que comemos e bebemos com ele, depois que ressurgiu dentre os mortos.

[[v44-10-42]]

^<<v44-10-42,42>>^ Jesus nos mandou pregar ao povo e testemunhar que ele foi constituído por Deus como Juiz de vivos e de mortos.

[[v44-10-43]]

^<<v44-10-43,43>>^ Dele todos os profetas dão testemunho de que, por meio do seu nome, todo o que nele crê recebe remissão dos pecados.

[[v44-10-44]]

^<<v44-10-44,44>>^ Enquanto Pedro falava estas palavras, o Espírito Santo caiu sobre todos os que ouviam a mensagem.

[[v44-10-45]]

^<<v44-10-45,45>>^ E os fiéis que eram da circuncisão, que tinham vindo com Pedro, admiraram-se, porque também sobre os gentios foi derramado o dom do Espírito Santo.

[[v44-10-46]]

^<<v44-10-46,46>>^ Pois eles os ouviam falando em línguas e engrandecendo a Deus. Então Pedro disse:

[[v44-10-47]]

^<<v44-10-47,47>>^ — Será que alguém poderia recusar a água e impedir que sejam batizados estes que, assim como nós, receberam o Espírito Santo?

[[v44-10-48]]

^<<v44-10-48,48>>^ E ordenou que fossem batizados em nome de Jesus Cristo. Então lhe pediram que permanecesse com eles por alguns dias.

'''

xref:044-atos/044-atos-009.adoc#v44-9-0[&#60; Capítulo Anterior] | <<v44-10-0,Topo>> | xref:044-atos/044-atos-011.adoc#v44-11-0[Próximo Capítulo &#62;]