include::./index.adoc[]

[[v44-12-0]]
=== Atos, 12
// naa ?, NAA - Nova Almeida Atualizada

[[v44-12-1]]

^<<v44-12-1,1>>^ Por aquele tempo, o rei Herodes mandou prender alguns da igreja para os maltratar.

[[v44-12-2]]

^<<v44-12-2,2>>^ Mandou matar à espada Tiago, irmão de João.

[[v44-12-3]]

^<<v44-12-3,3>>^ Vendo que isto agradava aos judeus, prosseguiu, mandando prender também Pedro. E eram os dias dos pães sem fermento.

[[v44-12-4]]

^<<v44-12-4,4>>^ Depois de prendê-lo, lançou-o na prisão, entregando-o a quatro escoltas de quatro soldados cada uma, para o guardarem. A intenção de Herodes era apresentá-lo ao povo depois da Páscoa.

[[v44-12-5]]

^<<v44-12-5,5>>^ E assim Pedro estava guardado na prisão; mas havia oração incessante a Deus por parte da igreja a favor dele.

[[v44-12-6]]

^<<v44-12-6,6>>^ Na noite anterior ao dia em que Herodes ia apresentá-lo ao povo, Pedro dormia entre dois soldados, preso com duas correntes. Sentinelas, junto à porta, guardavam a prisão.

[[v44-12-7]]

^<<v44-12-7,7>>^ Eis, porém, que sobreveio um anjo do Senhor, e uma luz iluminou a prisão. O anjo tocou no lado de Pedro e o despertou, dizendo: — Levante-se depressa! Então as correntes caíram das mãos dele.

[[v44-12-8]]

^<<v44-12-8,8>>^ E o anjo continuou: — Coloque o cinto e calce as sandálias. E ele assim o fez. O anjo lhe disse mais: — Ponha a capa e siga-me.

[[v44-12-9]]

^<<v44-12-9,9>>^ Então, saindo, Pedro o seguia, não sabendo que era real o que estava sendo feito pelo anjo; ele pensava que era uma visão.

[[v44-12-10]]

^<<v44-12-10,10>>^ Depois de terem passado a primeira e a segunda sentinela, chegaram ao portão de ferro que dava para a cidade, o qual se abriu automaticamente; e, saindo, enveredaram por uma rua, e logo adiante o anjo se afastou dele.

[[v44-12-11]]

^<<v44-12-11,11>>^ Então Pedro, caindo em si, disse: — Agora sei que, de fato, o Senhor enviou o seu anjo e me livrou da mão de Herodes e de toda a expectativa do povo judeu.

[[v44-12-12]]

^<<v44-12-12,12>>^ Ao se dar conta disso, Pedro resolveu ir à casa de Maria, mãe de João, também chamado Marcos, onde muitas pessoas estavam congregadas e oravam.

[[v44-12-13]]

^<<v44-12-13,13>>^ Quando ele bateu à porta da frente, uma empregada, chamada Rode, foi ver quem era.

[[v44-12-14]]

^<<v44-12-14,14>>^ Reconhecendo a voz de Pedro, ficou tão alegre que nem o fez entrar, mas voltou correndo para anunciar que Pedro estava à porta.

[[v44-12-15]]

^<<v44-12-15,15>>^ Então os outros disseram: — Você ficou louca! Ela, porém, persistia em afirmar que era verdade. Então disseram: — É o anjo dele.

[[v44-12-16]]

^<<v44-12-16,16>>^ Enquanto isso, Pedro continuava batendo. Quando abriram a porta, viram-no e ficaram admirados.

[[v44-12-17]]

^<<v44-12-17,17>>^ Ele, porém, fazendo-lhes sinal com a mão para que se calassem, contou-lhes como o Senhor o tinha tirado da prisão. E acrescentou: — Anunciem isto a Tiago e aos irmãos. E, saindo, foi para outro lugar.

[[v44-12-18]]

^<<v44-12-18,18>>^ Quando amanheceu, houve grande alvoroço entre os soldados sobre o que teria acontecido com Pedro.

[[v44-12-19]]

^<<v44-12-19,19>>^ Herodes, tendo-o procurado e não o achando, submetendo as sentinelas a interrogatório, ordenou que se aplicasse a pena de morte. E, descendo da Judeia para Cesareia, Herodes passou ali algum tempo.

[[v44-12-20]]

^<<v44-12-20,20>>^ Havia uma séria divergência entre Herodes e os moradores de Tiro e de Sidom. Estes, porém, de comum acordo, se apresentaram a ele e, depois de obter o apoio de Blasto, que era assessor do rei, pediram paz, porque a terra deles recebia alimentos do país do rei.

[[v44-12-21]]

^<<v44-12-21,21>>^ Em dia designado, Herodes, vestido de traje real, assentado no trono, dirigiu-lhes a palavra.

[[v44-12-22]]

^<<v44-12-22,22>>^ E o povo gritava: — É voz de um deus, e não de um homem!

[[v44-12-23]]

^<<v44-12-23,23>>^ No mesmo instante, um anjo do Senhor feriu Herodes, por ele não haver dado glória a Deus; e, comido de vermes, morreu.

[[v44-12-24]]

^<<v44-12-24,24>>^ Entretanto, a palavra de Deus crescia e se multiplicava.

[[v44-12-25]]

^<<v44-12-25,25>>^ Barnabé e Saulo, cumprida a sua missão, voltaram de Jerusalém, trazendo consigo João, também chamado Marcos.

'''

xref:044-atos/044-atos-011.adoc#v44-11-0[&#60; Capítulo Anterior] | <<v44-12-0,Topo>> | xref:044-atos/044-atos-013.adoc#v44-13-0[Próximo Capítulo &#62;]