include::./index.adoc[]

[[v44-28-0]]
=== Atos, 28
// naa ?, NAA - Nova Almeida Atualizada

[[v44-28-1]]

^<<v44-28-1,1>>^ Uma vez em terra, verificamos que a ilha se chamava Malta.

[[v44-28-2]]

^<<v44-28-2,2>>^ Os nativos nos trataram com singular humanidade, porque, acendendo uma fogueira, acolheram a todos nós por causa da chuva que caía e por causa do frio.

[[v44-28-3]]

^<<v44-28-3,3>>^ Tendo Paulo ajuntado e atirado à fogueira um feixe de gravetos, uma víbora, fugindo do calor, prendeu-se na mão dele.

[[v44-28-4]]

^<<v44-28-4,4>>^ Quando os nativos viram a víbora pendurada na mão de Paulo, disseram uns aos outros: — Certamente este homem é assassino, porque, salvo do mar, a Justiça não o deixa viver.

[[v44-28-5]]

^<<v44-28-5,5>>^ Porém ele, sacudindo a víbora no fogo, não sofreu mal nenhum.

[[v44-28-6]]

^<<v44-28-6,6>>^ Mas eles esperavam que Paulo viesse a inchar ou a cair morto de repente. Depois de muito esperar, vendo que nada de anormal lhe acontecia, mudando de opinião, diziam que ele era um deus.

[[v44-28-7]]

^<<v44-28-7,7>>^ Perto daquele lugar havia um sítio que pertencia ao homem principal da ilha, chamado Públio, o qual nos recebeu e hospedou com muita bondade durante três dias.

[[v44-28-8]]

^<<v44-28-8,8>>^ Aconteceu que o pai de Públio estava enfermo de disenteria, ardendo em febre. Paulo foi visitá-lo e, orando, impôs-lhe as mãos, e o curou.

[[v44-28-9]]

^<<v44-28-9,9>>^ À vista deste acontecimento, os demais enfermos da ilha vieram e foram curados,

[[v44-28-10]]

^<<v44-28-10,10>>^ os quais nos distinguiram com muitas honrarias; e, tendo nós de prosseguir viagem, nos puseram a bordo tudo o que era necessário.

[[v44-28-11]]

^<<v44-28-11,11>>^ Três meses depois, embarcamos num navio de Alexandria, que tinha passado o inverno na ilha. O navio tinha por emblema os deuses gêmeos Castor e Pólux.

[[v44-28-12]]

^<<v44-28-12,12>>^ Chegando a Siracusa, ficamos ali três dias.

[[v44-28-13]]

^<<v44-28-13,13>>^ Dali, navegando ao longo da costa, chegamos a Régio. No dia seguinte começou a soprar o vento sul e, em dois dias, chegamos a Putéoli,

[[v44-28-14]]

^<<v44-28-14,14>>^ onde encontramos alguns irmãos que nos pediram que ficássemos com eles sete dias; e foi assim que nos dirigimos a Roma.

[[v44-28-15]]

^<<v44-28-15,15>>^ Tendo ali os irmãos ouvido notícias nossas, vieram ao nosso encontro até a Praça de Ápio e as Três Vendas. Ao vê-los, Paulo deu graças a Deus e sentiu-se mais animado.

[[v44-28-16]]

^<<v44-28-16,16>>^ Uma vez em Roma, Paulo recebeu permissão para morar por sua conta, tendo em sua companhia o soldado que o guardava.

[[v44-28-17]]

^<<v44-28-17,17>>^ Três dias depois, ele convocou os principais dos judeus. Quando estavam reunidos, Paulo disse: — Meus irmãos, apesar de nada ter feito contra o povo ou contra os costumes paternos, vim preso desde Jerusalém, entregue nas mãos dos romanos.

[[v44-28-18]]

^<<v44-28-18,18>>^ Estes, depois de me interrogarem, quiseram soltar-me, porque não encontraram em mim nenhum crime passível de morte.

[[v44-28-19]]

^<<v44-28-19,19>>^ Diante da oposição dos judeus, fui obrigado a apelar para César, não tendo eu, porém, nada de que acusar o meu povo.

[[v44-28-20]]

^<<v44-28-20,20>>^ Foi por isto que pedi para vê-los e para falar com vocês; porque é pela esperança de Israel que estou preso com esta corrente.

[[v44-28-21]]

^<<v44-28-21,21>>^ Então eles lhe disseram: — Nós não recebemos da Judeia nenhuma carta que falasse a respeito de você. Também não veio qualquer dos irmãos que nos anunciasse ou dissesse algo de mau a seu respeito.

[[v44-28-22]]

^<<v44-28-22,22>>^ Mas gostaríamos de ouvir o que você pensa, porque sabemos que em todos os lugares essa seita é contestada.

[[v44-28-23]]

^<<v44-28-23,23>>^ Tendo eles marcado um dia, foram em grande número ao encontro de Paulo no lugar onde ele residia. Então, desde a manhã até a tarde, lhes fez uma exposição em testemunho do Reino de Deus, procurando persuadi-los a respeito de Jesus, tanto pela Lei de Moisés como pelos Profetas.

[[v44-28-24]]

^<<v44-28-24,24>>^ Houve alguns que ficaram persuadidos pelo que Paulo dizia; outros, porém, continuaram incrédulos.

[[v44-28-25]]

^<<v44-28-25,25>>^ E, havendo discordância entre eles, começaram a ir embora. Mas, antes que saíssem, Paulo disse estas palavras: — Bem falou o Espírito Santo aos pais de vocês, por meio do profeta Isaías, quando disse:

[[v44-28-26]]

^<<v44-28-26,26>>^ "Vá a este povo e diga: Ouvindo, vocês ouvirão e de modo nenhum entenderão; vendo, vocês verão e de modo nenhum perceberão.

[[v44-28-27]]

^<<v44-28-27,27>>^ Porque o coração deste povo está endurecido; ouviram com os ouvidos tapados e fecharam os olhos; para não acontecer que vejam com os olhos, ouçam com os ouvidos, entendam com o coração, se convertam e sejam por mim curados."

[[v44-28-28]]

^<<v44-28-28,28>>^ E Paulo concluiu: — Portanto, fiquem sabendo que esta salvação que Deus oferece foi enviada aos gentios. E eles a ouvirão.

[[v44-28-29]]

^<<v44-28-29,29>>^ &#91;Ditas estas palavras, os judeus foram embora, tendo entre si grande discussão.&#93;

[[v44-28-30]]

^<<v44-28-30,30>>^ Durante dois anos, Paulo permaneceu na sua própria casa, que tinha alugado, onde recebia todos os que o procuravam.

[[v44-28-31]]

^<<v44-28-31,31>>^ Pregava o Reino de Deus, e, com toda a ousadia, ensinava as coisas referentes ao Senhor Jesus Cristo, sem impedimento algum.

'''

xref:044-atos/044-atos-027.adoc#v44-27-0[&#60; Capítulo Anterior] | <<v44-28-0,Topo>> | xref:045-romanos/045-romanos-001.adoc#v45-1-0[Próximo Capítulo &#62;]