include::./index.adoc[]

[[v44-26-0]]
=== Atos, 26
// naa ?, NAA - Nova Almeida Atualizada

[[v44-26-1]]

^<<v44-26-1,1>>^ A seguir, Agripa, dirigindo-se a Paulo, disse: — Você está autorizado a falar em sua defesa. Então Paulo, estendendo a mão, passou a defender-se nestes termos:

[[v44-26-2]]

^<<v44-26-2,2>>^ — Tenho-me por feliz, ó rei Agripa, pelo privilégio de, hoje, na presença do senhor, poder produzir a minha defesa de todas as acusações que os judeus fazem contra mim,

[[v44-26-3]]

^<<v44-26-3,3>>^ especialmente porque o senhor é versado em todos os costumes e questões que há entre os judeus. Por isso, peço que o senhor me ouça com paciência.

[[v44-26-4]]

^<<v44-26-4,4>>^ — Quanto à minha vida, desde a mocidade, como decorreu desde o princípio entre o meu povo e em Jerusalém, todos os judeus a conhecem;

[[v44-26-5]]

^<<v44-26-5,5>>^ pois, na verdade, eu era conhecido deles desde o princípio, se assim o quiserem testemunhar, porque, na condição de fariseu, vivi conforme o partido mais rigoroso da nossa religião.

[[v44-26-6]]

^<<v44-26-6,6>>^ E agora estou sendo julgado por causa da esperança da promessa feita por Deus aos nossos pais,

[[v44-26-7]]

^<<v44-26-7,7>>^ a qual as nossas doze tribos, servindo a Deus fervorosamente, noite e dia, almejam alcançar. É por causa dessa esperança, ó rei, que eu sou acusado pelos judeus.

[[v44-26-8]]

^<<v44-26-8,8>>^ Por que se julga incrível entre vocês que Deus ressuscite os mortos?

[[v44-26-9]]

^<<v44-26-9,9>>^ — Na verdade, eu pensava que devia fazer muitas coisas contra o nome de Jesus, o Nazareno;

[[v44-26-10]]

^<<v44-26-10,10>>^ e foi exatamente o que fiz em Jerusalém. Havendo eu recebido autorização dos principais sacerdotes, encerrei muitos dos santos na prisão; e, quando os condenavam à morte, eu dava o meu voto contra eles.

[[v44-26-11]]

^<<v44-26-11,11>>^ Muitas vezes, os castiguei por todas as sinagogas, obrigando-os até a blasfemar. E, demasiadamente enfurecido contra eles, eu os perseguia até em cidades estrangeiras.

[[v44-26-12]]

^<<v44-26-12,12>>^ — Com isto em mente, parti para Damasco, levando autorização dos principais sacerdotes e por eles comissionado.

[[v44-26-13]]

^<<v44-26-13,13>>^ Ao meio-dia, ó rei, enquanto eu seguia pelo caminho, vi uma luz no céu, mais resplandecente que o sol, que brilhou ao redor de mim e dos que iam comigo.

[[v44-26-14]]

^<<v44-26-14,14>>^ E, caindo todos nós por terra, ouvi uma voz que me falava em língua hebraica: "Saulo, Saulo, por que você me persegue? É duro para você ficar dando coices contra os aguilhões!"

[[v44-26-15]]

^<<v44-26-15,15>>^ Então eu perguntei: "Senhor, quem é você?" Ao que o Senhor respondeu: "Eu sou Jesus, a quem você persegue.

[[v44-26-16]]

^<<v44-26-16,16>>^ Mas levante-se e fique em pé. Eu apareci a você para constituí-lo ministro e testemunha, tanto das coisas em que você me viu como daquelas pelas quais ainda lhe aparecerei.

[[v44-26-17]]

^<<v44-26-17,17>>^ Vou livrar você do seu próprio povo e dos gentios, para os quais eu o envio,

[[v44-26-18]]

^<<v44-26-18,18>>^ para abrir os olhos deles e convertê-los das trevas para a luz e do poder de Satanás para Deus, a fim de que eles recebam remissão de pecados e herança entre os que são santificados pela fé em mim."

[[v44-26-19]]

^<<v44-26-19,19>>^ — Assim, ó rei Agripa, não fui desobediente à visão celestial,

[[v44-26-20]]

^<<v44-26-20,20>>^ mas anunciei primeiramente aos de Damasco e em Jerusalém, por toda a região da Judeia, e também aos gentios, que se arrependessem e se convertessem a Deus, praticando obras dignas de arrependimento.

[[v44-26-21]]

^<<v44-26-21,21>>^ Por causa disto, alguns judeus me prenderam, quando eu estava no templo, e tentaram me matar.

[[v44-26-22]]

^<<v44-26-22,22>>^ Mas, com a ajuda de Deus, permaneço até o dia de hoje, dando testemunho, tanto a pequenos como a grandes, nada dizendo, a não ser o que os profetas e Moisés disseram que ia acontecer,

[[v44-26-23]]

^<<v44-26-23,23>>^ isto é, que o Cristo devia padecer e, sendo o primeiro da ressurreição dos mortos, anunciaria a luz ao seu próprio povo e aos gentios.

[[v44-26-24]]

^<<v44-26-24,24>>^ Quando Paulo estava dizendo estas coisas em sua defesa, Festo o interrompeu, gritando: — Você está louco, Paulo! Ficou louco de tanto estudar!

[[v44-26-25]]

^<<v44-26-25,25>>^ Paulo, porém, respondeu: — Não estou louco, ó excelentíssimo Festo! Pelo contrário, digo palavras de verdade e de bom senso.

[[v44-26-26]]

^<<v44-26-26,26>>^ Porque tudo isto é do conhecimento do rei, a quem me dirijo com franqueza, pois estou persuadido de que nenhuma destas coisas lhe é oculta, pois nada se passou em algum lugar escondido.

[[v44-26-27]]

^<<v44-26-27,27>>^ — Por isso, pergunto: Rei Agripa, o senhor acredita nos profetas? Eu sei que o senhor acredita.

[[v44-26-28]]

^<<v44-26-28,28>>^ Então Agripa se dirigiu a Paulo e disse: — Por pouco você me convence a me tornar cristão.

[[v44-26-29]]

^<<v44-26-29,29>>^ Paulo respondeu: — Peço a Deus que faça com que, por pouco ou por muito, não apenas o senhor, ó rei, mas todos os que hoje me ouvem venham a ser alguém como eu, mas sem estas correntes.

[[v44-26-30]]

^<<v44-26-30,30>>^ A essa altura, levantou-se o rei, e também o governador, e Berenice, bem como os que estavam assentados com eles.

[[v44-26-31]]

^<<v44-26-31,31>>^ E, ao saírem, falavam uns com os outros, dizendo: — Este homem não fez nada passível de morte ou de prisão.

[[v44-26-32]]

^<<v44-26-32,32>>^ Então Agripa se dirigiu a Festo e disse: — Este homem bem podia ser solto, se não tivesse apelado para César.

'''

xref:044-atos/044-atos-025.adoc#v44-25-0[&#60; Capítulo Anterior] | <<v44-26-0,Topo>> | xref:044-atos/044-atos-027.adoc#v44-27-0[Próximo Capítulo &#62;]