include::./index.adoc[]

[[v44-14-0]]
=== Atos, 14
// naa ?, NAA - Nova Almeida Atualizada

[[v44-14-1]]

^<<v44-14-1,1>>^ Em Icônio, Paulo e Barnabé entraram juntos na sinagoga judaica e falaram de tal modo, que veio a crer grande multidão, tanto de judeus como de gregos.

[[v44-14-2]]

^<<v44-14-2,2>>^ Mas os judeus que não tinham crido incitaram e irritaram os ânimos dos gentios contra os irmãos.

[[v44-14-3]]

^<<v44-14-3,3>>^ Entretanto, Paulo e Barnabé ficaram bastante tempo em Icônio, falando ousadamente no Senhor, o qual confirmava a palavra da sua graça, concedendo que, por mão deles, se fizessem sinais e prodígios.

[[v44-14-4]]

^<<v44-14-4,4>>^ Mas o povo da cidade se dividiu: uns eram pelos judeus; outros, pelos apóstolos.

[[v44-14-5]]

^<<v44-14-5,5>>^ Então surgiu um movimento entre os gentios e os judeus, com o apoio das suas autoridades, para os maltratar e apedrejar.

[[v44-14-6]]

^<<v44-14-6,6>>^ Quando Paulo e Barnabé souberam disso, fugiram para Listra e Derbe, cidades da Licaônia, e para as regiões vizinhas,

[[v44-14-7]]

^<<v44-14-7,7>>^ onde anunciaram o evangelho.

[[v44-14-8]]

^<<v44-14-8,8>>^ Em Listra, costumava estar sentado certo homem aleijado, paralítico desde o seu nascimento, e que nunca tinha conseguido andar.

[[v44-14-9]]

^<<v44-14-9,9>>^ Esse homem ouviu Paulo falar. Quando Paulo fixou nele os olhos e viu que ele tinha fé para ser curado,

[[v44-14-10]]

^<<v44-14-10,10>>^ disse a ele em voz alta: — Levante-se direito sobre os pés! O homem saltou e começou a andar.

[[v44-14-11]]

^<<v44-14-11,11>>^ Quando as multidões viram o que Paulo tinha feito, gritaram em língua licaônica: — Os deuses, em forma de homens, desceram até nós.

[[v44-14-12]]

^<<v44-14-12,12>>^ A Barnabé chamavam Júpiter, e a Paulo, Mercúrio, porque este era o principal portador da palavra.

[[v44-14-13]]

^<<v44-14-13,13>>^ O sacerdote de Júpiter, cujo templo estava em frente da cidade, trazendo touros e grinaldas para junto dos portões da cidade, queria oferecer um sacrifício juntamente com a multidão.

[[v44-14-14]]

^<<v44-14-14,14>>^ Porém, ouvindo isto, os apóstolos Barnabé e Paulo, rasgando as suas roupas, saltaram para o meio da multidão, gritando:

[[v44-14-15]]

^<<v44-14-15,15>>^ — Senhores, por que estão fazendo isto? Nós também somos seres humanos como vocês, sujeitos aos mesmos sentimentos, e anunciamos o evangelho a vocês para que se convertam destas coisas vãs ao Deus vivo, que fez o céu, a terra, o mar e tudo o que neles há.

[[v44-14-16]]

^<<v44-14-16,16>>^ Nas gerações passadas, Deus permitiu que todos os povos andassem nos seus próprios caminhos.

[[v44-14-17]]

^<<v44-14-17,17>>^ Contudo, não deixou de dar testemunho de si mesmo, fazendo o bem, dando a vocês chuvas do céu e estações frutíferas, enchendo o coração de vocês de fartura e de alegria.

[[v44-14-18]]

^<<v44-14-18,18>>^ Dizendo isto, foi ainda com dificuldade que impediram a multidão de lhes oferecer sacrifícios.

[[v44-14-19]]

^<<v44-14-19,19>>^ Entretanto, chegaram judeus de Antioquia e Icônio e, instigando as multidões, apedrejaram Paulo e o arrastaram para fora da cidade, dando-o por morto.

[[v44-14-20]]

^<<v44-14-20,20>>^ Mas, quando os discípulos o rodearam, ele se levantou e entrou na cidade. No dia seguinte, foi com Barnabé para Derbe.

[[v44-14-21]]

^<<v44-14-21,21>>^ E, tendo anunciado o evangelho naquela cidade e feito muitos discípulos, Paulo e Barnabé voltaram para Listra, Icônio e Antioquia,

[[v44-14-22]]

^<<v44-14-22,22>>^ fortalecendo o ânimo dos discípulos, exortando-os a permanecerem firmes na fé e mostrando que, através de muitas tribulações, nos importa entrar no Reino de Deus.

[[v44-14-23]]

^<<v44-14-23,23>>^ E, promovendo-lhes, em cada igreja, a eleição de presbíteros, depois de orar com jejuns, os encomendaram ao Senhor, em quem haviam crido.

[[v44-14-24]]

^<<v44-14-24,24>>^ Atravessando a Pisídia, Paulo e Barnabé se dirigiram à Panfília.

[[v44-14-25]]

^<<v44-14-25,25>>^ E, tendo anunciado a palavra em Perge, foram para Atália

[[v44-14-26]]

^<<v44-14-26,26>>^ e dali navegaram para Antioquia, onde tinham sido recomendados à graça de Deus para a obra que agora tinham terminado.

[[v44-14-27]]

^<<v44-14-27,27>>^ Quando chegaram a Antioquia, reuniram a igreja e relataram tudo o que Deus havia feito com eles e como tinha aberto aos gentios a porta da fé.

[[v44-14-28]]

^<<v44-14-28,28>>^ E permaneceram muito tempo com os discípulos.

'''

xref:044-atos/044-atos-013.adoc#v44-13-0[&#60; Capítulo Anterior] | <<v44-14-0,Topo>> | xref:044-atos/044-atos-015.adoc#v44-15-0[Próximo Capítulo &#62;]