include::./index.adoc[]

[[v44-11-0]]
=== Atos, 11
// naa ?, NAA - Nova Almeida Atualizada

[[v44-11-1]]

^<<v44-11-1,1>>^ Chegou ao conhecimento dos apóstolos e dos irmãos que estavam na Judeia que também os gentios haviam recebido a palavra de Deus.

[[v44-11-2]]

^<<v44-11-2,2>>^ Quando Pedro voltou para Jerusalém, os que eram da circuncisão começaram a questioná-lo, dizendo:

[[v44-11-3]]

^<<v44-11-3,3>>^ — Você entrou na casa de homens incircuncisos e comeu com eles.

[[v44-11-4]]

^<<v44-11-4,4>>^ Então Pedro passou a fazer-lhes uma exposição por ordem, dizendo:

[[v44-11-5]]

^<<v44-11-5,5>>^ — Eu estava na cidade de Jope orando e, num êxtase, tive uma visão em que observei descer um objeto como se fosse um grande lençol baixado do céu pelas quatro pontas e vindo até perto de mim.

[[v44-11-6]]

^<<v44-11-6,6>>^ E, olhando atentamente para dentro daquilo, vi quadrúpedes da terra, feras, répteis e aves do céu.

[[v44-11-7]]

^<<v44-11-7,7>>^ Ouvi também uma voz que me dizia: "Levante-se, Pedro! Mate e coma."

[[v44-11-8]]

^<<v44-11-8,8>>^ Ao que eu respondi: "De modo nenhum, Senhor; porque em minha boca nunca entrou nada que fosse impuro ou imundo."

[[v44-11-9]]

^<<v44-11-9,9>>^ Pela segunda vez, a voz do céu falou: "Não considere impuro aquilo que Deus purificou."

[[v44-11-10]]

^<<v44-11-10,10>>^ Isso se repetiu três vezes, e, de novo, tudo foi recolhido para o céu.

[[v44-11-11]]

^<<v44-11-11,11>>^ E eis que, na mesma hora, pararam diante da casa em que estávamos três homens enviados de Cesareia para se encontrar comigo.

[[v44-11-12]]

^<<v44-11-12,12>>^ Então o Espírito me disse que eu fosse com eles, sem hesitar. Foram comigo também estes seis irmãos; e entramos na casa daquele homem.

[[v44-11-13]]

^<<v44-11-13,13>>^ E ele nos contou como tinha visto na casa dele um anjo, em pé, que lhe disse: "Envie alguém a Jope e mande chamar Simão, que também é chamado de Pedro,

[[v44-11-14]]

^<<v44-11-14,14>>^ o qual lhe dirá palavras mediante as quais você e toda a sua casa serão salvos."

[[v44-11-15]]

^<<v44-11-15,15>>^ — Quando comecei a falar, o Espírito Santo caiu sobre eles, como também sobre nós, no princípio.

[[v44-11-16]]

^<<v44-11-16,16>>^ Então me lembrei da palavra do Senhor, quando disse: "João, na verdade, batizou com água, mas vocês serão batizados com o Espírito Santo."

[[v44-11-17]]

^<<v44-11-17,17>>^ Pois, se Deus deu a eles o mesmo dom que tinha dado a nós quando cremos no Senhor Jesus, quem era eu para que pudesse resistir a Deus?

[[v44-11-18]]

^<<v44-11-18,18>>^ Quando os demais ouviram isso, acalmaram-se e glorificaram a Deus, dizendo: — Então também aos gentios Deus concedeu o arrependimento para a vida!

[[v44-11-19]]

^<<v44-11-19,19>>^ Os que foram dispersos a partir da perseguição que começou com a morte de Estêvão se espalharam até a Fenícia, Chipre e Antioquia, não anunciando a palavra a ninguém que não fosse judeu.

[[v44-11-20]]

^<<v44-11-20,20>>^ Alguns deles, porém, que eram de Chipre e de Cirene e que foram até Antioquia, falavam também aos gregos, anunciando-lhes o evangelho do Senhor Jesus.

[[v44-11-21]]

^<<v44-11-21,21>>^ A mão do Senhor estava com eles, e muitos, crendo, se converteram ao Senhor.

[[v44-11-22]]

^<<v44-11-22,22>>^ A notícia a respeito deles chegou aos ouvidos da igreja que estava em Jerusalém; e enviaram Barnabé até Antioquia.

[[v44-11-23]]

^<<v44-11-23,23>>^ Quando ele chegou e viu a graça de Deus, ficou muito alegre. E exortava todos a que, com firmeza de coração, permanecessem no Senhor.

[[v44-11-24]]

^<<v44-11-24,24>>^ Porque era homem bom, cheio do Espírito Santo e de fé. E muita gente se uniu ao Senhor.

[[v44-11-25]]

^<<v44-11-25,25>>^ Depois Barnabé foi a Tarso à procura de Saulo.

[[v44-11-26]]

^<<v44-11-26,26>>^ E, quando o encontrou, levou-o para Antioquia. E, durante um ano inteiro, se reuniram naquela igreja e ensinaram numerosa multidão. Em Antioquia, os discípulos foram, pela primeira vez, chamados de cristãos.

[[v44-11-27]]

^<<v44-11-27,27>>^ Naqueles dias, alguns profetas foram de Jerusalém para Antioquia.

[[v44-11-28]]

^<<v44-11-28,28>>^ E, apresentando-se um deles, chamado Ágabo, dava a entender, pelo Espírito, que haveria uma grande fome em todo o mundo. Essa fome veio nos dias do imperador Cláudio.

[[v44-11-29]]

^<<v44-11-29,29>>^ Os discípulos, cada um conforme as suas posses, resolveram mandar uma ajuda aos irmãos que moravam na Judeia.

[[v44-11-30]]

^<<v44-11-30,30>>^ E eles o fizeram, enviando essa ajuda aos presbíteros por meio de Barnabé e Saulo.

'''

xref:044-atos/044-atos-010.adoc#v44-10-0[&#60; Capítulo Anterior] | <<v44-11-0,Topo>> | xref:044-atos/044-atos-012.adoc#v44-12-0[Próximo Capítulo &#62;]