include::./index.adoc[]

[[v44-6-0]]
=== Atos, 6
// naa ?, NAA - Nova Almeida Atualizada

[[v44-6-1]]

^<<v44-6-1,1>>^ Naqueles dias, aumentando o número dos discípulos, houve murmuração dos helenistas contra os hebreus, porque as viúvas deles estavam sendo esquecidas na distribuição diária.

[[v44-6-2]]

^<<v44-6-2,2>>^ Então os doze convocaram a comunidade dos discípulos e disseram: — Não é correto que nós abandonemos a palavra de Deus para servir às mesas.

[[v44-6-3]]

^<<v44-6-3,3>>^ Por isso, irmãos, escolham entre vocês sete homens de boa reputação, cheios do Espírito e de sabedoria, para os encarregarmos desse serviço.

[[v44-6-4]]

^<<v44-6-4,4>>^ Quanto a nós, nos consagraremos à oração e ao ministério da palavra.

[[v44-6-5]]

^<<v44-6-5,5>>^ O parecer agradou a todos. Então elegeram Estêvão, homem cheio de fé e do Espírito Santo, Filipe, Prócoro, Nicanor, Timão, Pármenas e Nicolau, prosélito de Antioquia.

[[v44-6-6]]

^<<v44-6-6,6>>^ Apresentaram estes homens aos apóstolos, que, orando, lhes impuseram as mãos.

[[v44-6-7]]

^<<v44-6-7,7>>^ A palavra de Deus crescia e, em Jerusalém, o número dos discípulos aumentava. Também um grande grupo de sacerdotes obedecia à fé.

[[v44-6-8]]

^<<v44-6-8,8>>^ Estêvão, cheio de graça e de poder, fazia prodígios e grandes sinais entre o povo.

[[v44-6-9]]

^<<v44-6-9,9>>^ Então alguns dos que eram da sinagoga chamada dos Libertos, dos cireneus, dos alexandrinos e dos da Cilícia e da província da Ásia se levantaram e discutiam com Estêvão.

[[v44-6-10]]

^<<v44-6-10,10>>^ Mas eles não podiam resistir à sabedoria e ao Espírito, pelo qual ele falava.

[[v44-6-11]]

^<<v44-6-11,11>>^ Então subornaram alguns homens para que dissessem: — Ouvimos este homem proferir blasfêmias contra Moisés e contra Deus.

[[v44-6-12]]

^<<v44-6-12,12>>^ Atiçaram o povo, os anciãos e os escribas e, investindo contra Estêvão, o agarraram e levaram ao Sinédrio.

[[v44-6-13]]

^<<v44-6-13,13>>^ Apresentaram testemunhas falsas, que disseram: — Este homem não para de falar contra o lugar santo e contra a lei.

[[v44-6-14]]

^<<v44-6-14,14>>^ Nós o ouvimos dizer que esse Jesus, o Nazareno, destruirá este lugar e mudará os costumes que Moisés nos deu.

[[v44-6-15]]

^<<v44-6-15,15>>^ Todos os que estavam sentados no Sinédrio, fitando os olhos em Estêvão, viram o seu rosto como se fosse rosto de anjo.

'''

xref:044-atos/044-atos-005.adoc#v44-5-0[&#60; Capítulo Anterior] | <<v44-6-0,Topo>> | xref:044-atos/044-atos-007.adoc#v44-7-0[Próximo Capítulo &#62;]