include::./index.adoc[]

[[v44-25-0]]
=== Atos, 25
// naa ?, NAA - Nova Almeida Atualizada

[[v44-25-1]]

^<<v44-25-1,1>>^ Três dias depois de ter assumido o governo da província, Festo saiu de Cesareia e foi para Jerusalém.

[[v44-25-2]]

^<<v44-25-2,2>>^ E, logo, os principais sacerdotes e os maiorais dos judeus lhe apresentaram queixa a respeito de Paulo.

[[v44-25-3]]

^<<v44-25-3,3>>^ Contra ele, pediram a Festo o favor de mandar que ele fosse trazido a Jerusalém. É que eles tinham armado uma emboscada para matar Paulo no caminho.

[[v44-25-4]]

^<<v44-25-4,4>>^ Festo, porém, respondeu que Paulo continuaria preso em Cesareia e que ele mesmo, muito em breve, partiria para lá.

[[v44-25-5]]

^<<v44-25-5,5>>^ E concluiu: — Aqueles de vocês que estiverem habilitados me acompanhem; e, havendo contra este homem qualquer crime, acusem-no.

[[v44-25-6]]

^<<v44-25-6,6>>^ E, não se demorando entre eles mais de oito ou dez dias, foi para Cesareia. No dia seguinte, assentando-se no tribunal, ordenou que Paulo fosse trazido.

[[v44-25-7]]

^<<v44-25-7,7>>^ Quando Paulo chegou, os judeus que tinham vindo de Jerusalém ficaram em volta dele, fazendo muitas e graves acusações contra ele, as quais, entretanto, não podiam provar.

[[v44-25-8]]

^<<v44-25-8,8>>^ Então Paulo, defendendo-se, disse: — Nenhum pecado cometi contra a lei dos judeus, nem contra o templo, nem contra César.

[[v44-25-9]]

^<<v44-25-9,9>>^ Então Festo, querendo assegurar o apoio dos judeus, perguntou a Paulo: — Você gostaria de ir a Jerusalém e ser ali julgado por mim a respeito destas coisas?

[[v44-25-10]]

^<<v44-25-10,10>>^ Paulo respondeu: — Estou diante do tribunal de César, onde convém que eu seja julgado. Não fiz mal nenhum aos judeus, como o senhor sabe muito bem.

[[v44-25-11]]

^<<v44-25-11,11>>^ Se de fato pratiquei algum mal ou crime digno de morte, estou pronto para morrer. Se, pelo contrário, não são verdadeiras as coisas de que me acusam, ninguém pode me entregar a eles. Apelo para César.

[[v44-25-12]]

^<<v44-25-12,12>>^ Então Festo, tendo falado com o conselho, respondeu: — Já que apelou para César, para César você irá.

[[v44-25-13]]

^<<v44-25-13,13>>^ Passados alguns dias, o rei Agripa e Berenice chegaram a Cesareia a fim de saudar Festo.

[[v44-25-14]]

^<<v44-25-14,14>>^ Como se demorassem ali alguns dias, Festo expôs ao rei o caso de Paulo, dizendo: — Félix deixou aqui preso certo homem,

[[v44-25-15]]

^<<v44-25-15,15>>^ a respeito de quem os principais sacerdotes e os anciãos dos judeus apresentaram queixa, quando eu estive em Jerusalém, pedindo que o condenasse.

[[v44-25-16]]

^<<v44-25-16,16>>^ Eu lhes disse que não é costume dos romanos condenar quem quer que seja, sem que o acusado tenha presentes os seus acusadores e possa defender-se da acusação.

[[v44-25-17]]

^<<v44-25-17,17>>^ Assim, quando eles vieram para cá, sem nenhuma demora, no dia seguinte, assentando-me no tribunal, determinei que o homem fosse trazido.

[[v44-25-18]]

^<<v44-25-18,18>>^ Levantando-se os acusadores, não mencionaram nenhum dos crimes de que eu suspeitava.

[[v44-25-19]]

^<<v44-25-19,19>>^ Traziam contra ele algumas questões referentes à sua própria religião e particularmente a certo morto, chamado Jesus, que Paulo afirma estar vivo.

[[v44-25-20]]

^<<v44-25-20,20>>^ Estando eu perplexo quanto ao modo de investigar estas coisas, perguntei-lhe se queria ir a Jerusalém para ali ser julgado a respeito disso.

[[v44-25-21]]

^<<v44-25-21,21>>^ Mas, havendo Paulo apelado para que ficasse em custódia para o julgamento de César, ordenei que o acusado continuasse detido até que eu o enviasse a César.

[[v44-25-22]]

^<<v44-25-22,22>>^ Então Agripa disse a Festo: — Eu também gostaria de ouvir este homem. Festo respondeu: — Amanhã você poderá ouvi-lo.

[[v44-25-23]]

^<<v44-25-23,23>>^ De fato, no dia seguinte, vindo Agripa e Berenice, com grande pompa, tendo eles entrado na sala de audiência juntamente com oficiais superiores e homens eminentes da cidade, Paulo foi trazido por ordem de Festo.

[[v44-25-24]]

^<<v44-25-24,24>>^ Então Festo disse: — Rei Agripa e todos os senhores aqui presentes, vejam este homem, por causa de quem toda a multidão dos judeus recorreu a mim tanto em Jerusalém como aqui, clamando que não convinha que ele vivesse mais.

[[v44-25-25]]

^<<v44-25-25,25>>^ Porém eu achei que ele não tinha feito nada que fosse passível de morte; entretanto, tendo ele apelado para o imperador, resolvi mandá-lo para lá.

[[v44-25-26]]

^<<v44-25-26,26>>^ No entanto, a respeito dele, nada tenho de mais concreto que possa escrever ao imperador. Por isso, eu o trouxe à presença dos senhores e, especialmente, à sua presença, ó rei Agripa, para que, feita a arguição, eu tenha alguma coisa que escrever.

[[v44-25-27]]

^<<v44-25-27,27>>^ Porque não me parece razoável enviar um preso sem mencionar, ao mesmo tempo, as acusações que existem contra ele.

'''

xref:044-atos/044-atos-024.adoc#v44-24-0[&#60; Capítulo Anterior] | <<v44-25-0,Topo>> | xref:044-atos/044-atos-026.adoc#v44-26-0[Próximo Capítulo &#62;]