include::./index.adoc[]

[[v44-2-0]]
=== Atos, 2
// naa ?, NAA - Nova Almeida Atualizada

[[v44-2-1]]

^<<v44-2-1,1>>^ Ao cumprir-se o dia de Pentecostes, estavam todos reunidos no mesmo lugar.

[[v44-2-2]]

^<<v44-2-2,2>>^ De repente, veio do céu um som, como de um vento impetuoso, e encheu toda a casa onde estavam sentados.

[[v44-2-3]]

^<<v44-2-3,3>>^ E apareceram, distribuídas entre eles, línguas, como de fogo, as quais pousaram sobre cada um deles.

[[v44-2-4]]

^<<v44-2-4,4>>^ Todos ficaram cheios do Espírito Santo e começaram a falar em outras línguas, segundo o Espírito lhes concedia que falassem.

[[v44-2-5]]

^<<v44-2-5,5>>^ Estavam morando em Jerusalém judeus, homens piedosos, vindos de todas as nações debaixo do céu.

[[v44-2-6]]

^<<v44-2-6,6>>^ Assim, quando se fez ouvir aquela voz, afluiu a multidão, que foi tomada de perplexidade, porque cada um os ouvia falar na sua própria língua.

[[v44-2-7]]

^<<v44-2-7,7>>^ Estavam atônitos e se admiravam, dizendo: — Vejam! Não são galileus todos esses que aí estão falando?

[[v44-2-8]]

^<<v44-2-8,8>>^ Então como os ouvimos falar, cada um em nossa própria língua materna?

[[v44-2-9]]

^<<v44-2-9,9>>^ Somos partos, medos, elamitas e os naturais da Mesopotâmia, Judeia, Capadócia, Ponto e Ásia,

[[v44-2-10]]

^<<v44-2-10,10>>^ da Frígia, da Panfília, do Egito e das regiões da Líbia, nas imediações de Cirene, e romanos que aqui residem,

[[v44-2-11]]

^<<v44-2-11,11>>^ tanto judeus como prosélitos, cretenses e árabes. Como os ouvimos falar sobre as grandezas de Deus em nossas próprias línguas?

[[v44-2-12]]

^<<v44-2-12,12>>^ Todos, atônitos e perplexos, perguntavam uns aos outros: — O que será que isso quer dizer?

[[v44-2-13]]

^<<v44-2-13,13>>^ Outros, porém, zombando, diziam: — Estão bêbados!

[[v44-2-14]]

^<<v44-2-14,14>>^ Então Pedro se levantou, junto com os onze, e, erguendo a voz, dirigiu-se à multidão nestes termos: — Homens da Judeia e todos vocês que moram em Jerusalém, tomem conhecimento disto e prestem atenção no que vou dizer.

[[v44-2-15]]

^<<v44-2-15,15>>^ Estes homens não estão bêbados, como vocês estão pensando, porque são apenas nove horas da manhã.

[[v44-2-16]]

^<<v44-2-16,16>>^ Mas o que está acontecendo é o que foi dito por meio do profeta Joel:

[[v44-2-17]]

^<<v44-2-17,17>>^ "E acontecerá nos últimos dias, diz Deus, que derramarei o meu Espírito sobre toda a humanidade. Os filhos e as filhas de vocês profetizarão, os seus jovens terão visões, e os seus velhos sonharão.

[[v44-2-18]]

^<<v44-2-18,18>>^ Até sobre os meus servos e sobre as minhas servas derramarei o meu Espírito naqueles dias, e profetizarão.

[[v44-2-19]]

^<<v44-2-19,19>>^ Mostrarei prodígios em cima no céu e sinais embaixo na terra: sangue, fogo e nuvens de fumaça.

[[v44-2-20]]

^<<v44-2-20,20>>^ O sol se transformará em trevas, e a lua, em sangue, antes que venha o grande e glorioso Dia do Senhor.

[[v44-2-21]]

^<<v44-2-21,21>>^ E acontecerá que todo aquele que invocar o nome do Senhor será salvo."

[[v44-2-22]]

^<<v44-2-22,22>>^ — Israelitas, escutem o que vou dizer: Jesus, o Nazareno, homem aprovado por Deus diante de vocês com milagres, prodígios e sinais, os quais o próprio Deus realizou entre vocês por meio dele, como vocês mesmos sabem,

[[v44-2-23]]

^<<v44-2-23,23>>^ a este, conforme o plano determinado e a presciência de Deus, vocês mataram, crucificando-o por meio de homens maus.

[[v44-2-24]]

^<<v44-2-24,24>>^ Porém Deus o ressuscitou, livrando-o da agonia da morte, porque não era possível que fosse retido por ela.

[[v44-2-25]]

^<<v44-2-25,25>>^ Porque Davi fala a respeito dele, dizendo: "Eu sempre via o Senhor diante de mim, porque ele está à minha direita, para que eu não seja abalado.

[[v44-2-26]]

^<<v44-2-26,26>>^ Por isso, o meu coração se alegra e a minha língua exulta; além disto, também a minha própria carne repousará em esperança,

[[v44-2-27]]

^<<v44-2-27,27>>^ porque não deixarás a minha alma na morte, nem permitirás que o teu Santo veja corrupção.

[[v44-2-28]]

^<<v44-2-28,28>>^ Fizeste-me conhecer os caminhos da vida, e me encherás de alegria na tua presença."

[[v44-2-29]]

^<<v44-2-29,29>>^ — Irmãos, permitam-me falar-lhes claramente a respeito do patriarca Davi: ele morreu e foi sepultado, e o seu túmulo permanece entre nós até hoje.

[[v44-2-30]]

^<<v44-2-30,30>>^ Sendo, pois, profeta e sabendo que Deus lhe havia jurado que um dos seus descendentes se assentaria no seu trono,

[[v44-2-31]]

^<<v44-2-31,31>>^ prevendo isto, referiu-se à ressurreição de Cristo, que nem foi deixado na morte, nem o seu corpo experimentou corrupção.

[[v44-2-32]]

^<<v44-2-32,32>>^ Deus ressuscitou este Jesus, e disto todos nós somos testemunhas.

[[v44-2-33]]

^<<v44-2-33,33>>^ Exaltado, pois, à direita de Deus, tendo recebido do Pai a promessa do Espírito Santo, derramou isto que vocês estão vendo e ouvindo.

[[v44-2-34]]

^<<v44-2-34,34>>^ Porque Davi não subiu aos céus, mas ele mesmo afirma: "Disse o Senhor ao meu Senhor: ‘Sente-se à minha direita,

[[v44-2-35]]

^<<v44-2-35,35>>^ até que eu ponha os seus inimigos por estrado dos seus pés.’"

[[v44-2-36]]

^<<v44-2-36,36>>^ — Portanto, toda a casa de Israel esteja absolutamente certa de que a este Jesus, que vocês crucificaram, Deus o fez Senhor e Cristo.

[[v44-2-37]]

^<<v44-2-37,37>>^ Quando ouviram isso, ficaram muito comovidos e perguntaram a Pedro e aos demais apóstolos: — Que faremos, irmãos?

[[v44-2-38]]

^<<v44-2-38,38>>^ Pedro respondeu: — Arrependam-se, e cada um de vocês seja batizado em nome de Jesus Cristo para remissão dos seus pecados, e vocês receberão o dom do Espírito Santo.

[[v44-2-39]]

^<<v44-2-39,39>>^ Porque a promessa é para vocês e para os seus filhos, e para todos os que ainda estão longe, isto é, para todos aqueles que o Senhor, nosso Deus, chamar.

[[v44-2-40]]

^<<v44-2-40,40>>^ Com muitas outras palavras deu testemunho e exortava-os, dizendo: — Salvem-se desta geração perversa.

[[v44-2-41]]

^<<v44-2-41,41>>^ Então os que aceitaram a palavra de Pedro foram batizados, havendo um acréscimo naquele dia de quase três mil pessoas.

[[v44-2-42]]

^<<v44-2-42,42>>^ E perseveravam na doutrina dos apóstolos e na comunhão, no partir do pão e nas orações.

[[v44-2-43]]

^<<v44-2-43,43>>^ Em cada alma havia temor; e muitos prodígios e sinais eram feitos por meio dos apóstolos.

[[v44-2-44]]

^<<v44-2-44,44>>^ Todos os que criam estavam juntos e tinham tudo em comum.

[[v44-2-45]]

^<<v44-2-45,45>>^ Vendiam as suas propriedades e bens, distribuindo o produto entre todos, à medida que alguém tinha necessidade.

[[v44-2-46]]

^<<v44-2-46,46>>^ Diariamente perseveravam unânimes no templo, partiam pão de casa em casa e tomavam as suas refeições com alegria e singeleza de coração,

[[v44-2-47]]

^<<v44-2-47,47>>^ louvando a Deus e contando com a simpatia de todo o povo. Enquanto isso, o Senhor lhes acrescentava, dia a dia, os que iam sendo salvos.

'''

xref:044-atos/044-atos-001.adoc#v44-1-0[&#60; Capítulo Anterior] | <<v44-2-0,Topo>> | xref:044-atos/044-atos-003.adoc#v44-3-0[Próximo Capítulo &#62;]