include::./index.adoc[]

[[v44-4-0]]
=== Atos, 4
// naa ?, NAA - Nova Almeida Atualizada

[[v44-4-1]]

^<<v44-4-1,1>>^ Enquanto Pedro e João ainda falavam ao povo, chegaram os sacerdotes, o capitão do templo e os saduceus,

[[v44-4-2]]

^<<v44-4-2,2>>^ ressentidos porque os apóstolos estavam ensinando o povo e anunciando, em Jesus, a ressurreição dentre os mortos.

[[v44-4-3]]

^<<v44-4-3,3>>^ Prenderam Pedro e João e os recolheram ao cárcere até o dia seguinte, pois já era tarde.

[[v44-4-4]]

^<<v44-4-4,4>>^ Porém muitos dos que ouviram a palavra creram, subindo o número desses homens a quase cinco mil.

[[v44-4-5]]

^<<v44-4-5,5>>^ No dia seguinte, as autoridades, os anciãos e os escribas se reuniram em Jerusalém

[[v44-4-6]]

^<<v44-4-6,6>>^ com o sumo sacerdote Anás, com Caifás, João, Alexandre e todos os que eram da linhagem do sumo sacerdote.

[[v44-4-7]]

^<<v44-4-7,7>>^ E, colocando os apóstolos diante deles, perguntaram: — Com que poder ou em nome de quem vocês fizeram isso?

[[v44-4-8]]

^<<v44-4-8,8>>^ Então Pedro, cheio do Espírito Santo, lhes disse: — Autoridades do povo e anciãos,

[[v44-4-9]]

^<<v44-4-9,9>>^ visto que hoje somos interrogados a propósito do benefício feito a um homem enfermo e do modo como ele foi curado,

[[v44-4-10]]

^<<v44-4-10,10>>^ saibam os senhores todos e todo o povo de Israel que, em nome de Jesus Cristo, o Nazareno, a quem vocês crucificaram e a quem Deus ressuscitou dentre os mortos, sim, em seu nome é que este está curado na presença de vocês.

[[v44-4-11]]

^<<v44-4-11,11>>^ Este Jesus é a pedra que vocês, os construtores, rejeitaram, mas ele veio a ser a pedra angular.

[[v44-4-12]]

^<<v44-4-12,12>>^ E não há salvação em nenhum outro, porque debaixo do céu não existe nenhum outro nome, dado entre os homens, pelo qual importa que sejamos salvos.

[[v44-4-13]]

^<<v44-4-13,13>>^ Ao verem a ousadia de Pedro e João, sabendo que eram homens iletrados e incultos, ficaram admirados; e reconheceram que eles haviam estado com Jesus.

[[v44-4-14]]

^<<v44-4-14,14>>^ Vendo que o homem que havia sido curado estava com eles, nada tinham a dizer em contrário.

[[v44-4-15]]

^<<v44-4-15,15>>^ E, mandando-os sair do Sinédrio, discutiam entre si,

[[v44-4-16]]

^<<v44-4-16,16>>^ dizendo: — Que faremos com estes homens? Pois todos os moradores de Jerusalém sabem que um sinal notório foi feito por eles, e não o podemos negar.

[[v44-4-17]]

^<<v44-4-17,17>>^ Mas, para que não haja maior divulgação entre o povo, vamos ameaçá-los para não falarem mais neste nome a quem quer que seja.

[[v44-4-18]]

^<<v44-4-18,18>>^ Chamando-os, ordenaram-lhes que de modo nenhum falassem nem ensinassem no nome de Jesus.

[[v44-4-19]]

^<<v44-4-19,19>>^ Mas Pedro e João responderam: — Os senhores mesmos julguem se é justo diante de Deus ouvirmos antes aos senhores do que a Deus;

[[v44-4-20]]

^<<v44-4-20,20>>^ pois nós não podemos deixar de falar das coisas que vimos e ouvimos.

[[v44-4-21]]

^<<v44-4-21,21>>^ Depois, ameaçando-os mais ainda, os soltaram, não tendo achado como os castigar, por causa do povo, porque todos glorificavam a Deus pelo que tinha acontecido.

[[v44-4-22]]

^<<v44-4-22,22>>^ Ora, o homem em quem tinha sido operado esse milagre de cura tinha mais de quarenta anos de idade.

[[v44-4-23]]

^<<v44-4-23,23>>^ Uma vez soltos, Pedro e João procuraram os irmãos e lhes contaram tudo o que os principais sacerdotes e os anciãos lhes tinham falado.

[[v44-4-24]]

^<<v44-4-24,24>>^ Ouvindo isto, unânimes, levantaram a voz a Deus e disseram: — Tu, Soberano Senhor, fizeste o céu, a terra, o mar e tudo o que neles há!

[[v44-4-25]]

^<<v44-4-25,25>>^ Disseste por meio do Espírito Santo, por boca de Davi, nosso pai, teu servo: "Por que se enfureceram os gentios, e os povos imaginaram coisas vãs?

[[v44-4-26]]

^<<v44-4-26,26>>^ Os reis da terra se levantaram, e as autoridades se juntaram contra o Senhor e contra o seu Ungido."

[[v44-4-27]]

^<<v44-4-27,27>>^ — Porque de fato, nesta cidade, Herodes e Pôncio Pilatos, com gentios e gente de Israel, se juntaram contra o teu santo Servo Jesus, a quem ungiste,

[[v44-4-28]]

^<<v44-4-28,28>>^ para fazerem tudo o que a tua mão e o teu propósito predeterminaram.

[[v44-4-29]]

^<<v44-4-29,29>>^ Agora, Senhor, olha para as ameaças deles e concede aos teus servos que anunciem a tua palavra com toda a ousadia,

[[v44-4-30]]

^<<v44-4-30,30>>^ enquanto estendes a tua mão para fazer curas, sinais e prodígios por meio do nome do teu santo Servo Jesus.

[[v44-4-31]]

^<<v44-4-31,31>>^ Tendo eles orado, tremeu o lugar onde estavam reunidos. Todos ficaram cheios do Espírito Santo e, com ousadia, anunciavam a palavra de Deus.

[[v44-4-32]]

^<<v44-4-32,32>>^ Da multidão dos que creram era um o coração e a alma. Ninguém considerava exclusivamente sua nem uma das coisas que possuía; tudo, porém, lhes era comum.

[[v44-4-33]]

^<<v44-4-33,33>>^ Com grande poder, os apóstolos davam testemunho da ressurreição do Senhor Jesus, e em todos eles havia abundante graça.

[[v44-4-34]]

^<<v44-4-34,34>>^ Não havia nenhum necessitado entre eles, porque os que possuíam terras ou casas, vendendo-as, traziam os valores correspondentes

[[v44-4-35]]

^<<v44-4-35,35>>^ e os depositavam aos pés dos apóstolos; então se distribuía a cada um conforme a sua necessidade.

[[v44-4-36]]

^<<v44-4-36,36>>^ Então José, a quem os apóstolos chamavam de Barnabé, que quer dizer filho da consolação, um levita natural de Chipre,

[[v44-4-37]]

^<<v44-4-37,37>>^ vendeu um campo que possuía, trouxe o dinheiro e o depositou aos pés dos apóstolos.

'''

xref:044-atos/044-atos-003.adoc#v44-3-0[&#60; Capítulo Anterior] | <<v44-4-0,Topo>> | xref:044-atos/044-atos-005.adoc#v44-5-0[Próximo Capítulo &#62;]