include::./index.adoc[]

[[v44-23-0]]
=== Atos, 23
// naa ?, NAA - Nova Almeida Atualizada

[[v44-23-1]]

^<<v44-23-1,1>>^ Paulo, fixando os olhos no Sinédrio, disse: — Meus irmãos, tenho vivido até o dia de hoje com a consciência limpa diante de Deus.

[[v44-23-2]]

^<<v44-23-2,2>>^ Mas Ananias, o sumo sacerdote, mandou aos que estavam perto de Paulo que lhe batessem na boca.

[[v44-23-3]]

^<<v44-23-3,3>>^ Então Paulo lhe disse: — Deus há de ferir você, parede branqueada! Você está aí sentado para me julgar de acordo com a Lei e, contra a Lei, ordena que eu seja agredido?

[[v44-23-4]]

^<<v44-23-4,4>>^ Os que estavam ali perguntaram a Paulo: — Você está insultando o sumo sacerdote de Deus?

[[v44-23-5]]

^<<v44-23-5,5>>^ Paulo respondeu: — Eu não sabia, irmãos, que ele é sumo sacerdote. Porque está escrito: "Não fale mal de uma autoridade do seu povo."

[[v44-23-6]]

^<<v44-23-6,6>>^ Como Paulo sabia que uma parte do Sinédrio se compunha de saduceus e outra, de fariseus, exclamou: — Irmãos, eu sou fariseu, filho de fariseus. Estou sendo julgado por causa da esperança e da ressurreição dos mortos!

[[v44-23-7]]

^<<v44-23-7,7>>^ Ditas estas palavras, começou uma grande discussão entre fariseus e saduceus, e o Sinédrio se dividiu.

[[v44-23-8]]

^<<v44-23-8,8>>^ Pois os saduceus dizem que não há ressurreição, nem anjo, nem espírito, ao passo que os fariseus admitem todas essas coisas.

[[v44-23-9]]

^<<v44-23-9,9>>^ Houve, pois, muita gritaria no Sinédrio. E, levantando-se alguns escribas que eram do partido dos fariseus, discutiam, dizendo: — Não achamos neste homem mal algum. E se, de fato, algum espírito ou anjo falou com ele?

[[v44-23-10]]

^<<v44-23-10,10>>^ Como a discussão ficava cada vez mais intensa, o comandante, temendo que Paulo fosse despedaçado por eles, mandou descer a guarda para que o retirassem dali e o levassem para a fortaleza.

[[v44-23-11]]

^<<v44-23-11,11>>^ Na noite seguinte, o Senhor, pondo-se ao lado de Paulo, disse: — Coragem! Pois assim como você deu testemunho a meu respeito em Jerusalém, é necessário que você testemunhe também em Roma.

[[v44-23-12]]

^<<v44-23-12,12>>^ Quando amanheceu, os judeus se reuniram e juraram que não haviam de comer, nem beber, enquanto não matassem Paulo.

[[v44-23-13]]

^<<v44-23-13,13>>^ Eram mais de quarenta os que se envolveram nessa conspiração.

[[v44-23-14]]

^<<v44-23-14,14>>^ Estes foram falar com os principais sacerdotes e os anciãos e disseram: — Juramos, sob pena de maldição, não comer coisa alguma, enquanto não matarmos Paulo.

[[v44-23-15]]

^<<v44-23-15,15>>^ Por isso, agora, juntamente com o Sinédrio, mandem um recado ao comandante para que ele o apresente a vocês, sob o pretexto de que desejam investigar mais acuradamente o caso dele; e nós, antes que ele chegue, estaremos prontos para matá-lo.

[[v44-23-16]]

^<<v44-23-16,16>>^ Mas o filho da irmã de Paulo, tendo ouvido a respeito da trama, foi, entrou na fortaleza e contou tudo a Paulo.

[[v44-23-17]]

^<<v44-23-17,17>>^ Então este, chamando um dos centuriões, disse: — Leve este rapaz ao comandante, porque tem algo a dizer.

[[v44-23-18]]

^<<v44-23-18,18>>^ O centurião levou o rapaz ao comandante e disse: — O prisioneiro Paulo me chamou e pediu que eu trouxesse à sua presença este rapaz, pois tem algo a dizer ao senhor.

[[v44-23-19]]

^<<v44-23-19,19>>^ O comandante pegou o rapaz pela mão e, levando-o para um lado, perguntou-lhe: — O que você tem para me dizer?

[[v44-23-20]]

^<<v44-23-20,20>>^ Ele respondeu: — Os judeus decidiram pedir ao senhor que, amanhã, apresente Paulo ao Sinédrio, sob o pretexto de que desejam fazer uma investigação mais acurada a respeito dele.

[[v44-23-21]]

^<<v44-23-21,21>>^ Não se deixe persuadir, porque mais de quarenta deles armaram uma emboscada. Fizeram um pacto de, sob pena de maldição, não comer, nem beber, enquanto não matarem Paulo; e agora estão prontos, esperando que o senhor prometa atender o pedido deles.

[[v44-23-22]]

^<<v44-23-22,22>>^ Então o comandante despediu o rapaz, recomendando-lhe que não dissesse a ninguém ter lhe trazido estas informações.

[[v44-23-23]]

^<<v44-23-23,23>>^ Chamando dois centuriões, ordenou: — Tenham de prontidão duzentos soldados, setenta cavaleiros e duzentos lanceiros para irem até Cesareia a partir das nove horas da noite.

[[v44-23-24]]

^<<v44-23-24,24>>^ Preparem também animais para fazer Paulo montar e levem-no com segurança ao governador Félix.

[[v44-23-25]]

^<<v44-23-25,25>>^ O comandante escreveu uma carta nestes termos:

[[v44-23-26]]

^<<v44-23-26,26>>^ "Cláudio Lísias ao excelentíssimo governador Félix. Saudações.

[[v44-23-27]]

^<<v44-23-27,27>>^ Este homem foi preso pelos judeus e estava prestes a ser morto por eles, quando eu, sobrevindo com a guarda, o livrei, por saber que ele era romano.

[[v44-23-28]]

^<<v44-23-28,28>>^ Querendo certificar-me do motivo por que o acusavam, levei-o ao Sinédrio deles.

[[v44-23-29]]

^<<v44-23-29,29>>^ Descobri que ele era acusado de coisas referentes à lei que os rege, mas nada que justificasse morte ou mesmo prisão.

[[v44-23-30]]

^<<v44-23-30,30>>^ Sendo eu informado de que ia haver uma emboscada contra o homem, tratei de enviá-lo imediatamente ao senhor, intimando também os acusadores a irem dizer, na sua presença, o que eles têm contra ele. Passe bem."

[[v44-23-31]]

^<<v44-23-31,31>>^ Então os soldados, conforme lhes foi ordenado, pegaram Paulo e, durante a noite, o conduziram até Antipátride.

[[v44-23-32]]

^<<v44-23-32,32>>^ No dia seguinte, voltaram para a fortaleza, tendo deixado os cavaleiros encarregados de seguir viagem com ele.

[[v44-23-33]]

^<<v44-23-33,33>>^ Quando estes chegaram a Cesareia, entregaram a carta ao governador e também lhe apresentaram Paulo.

[[v44-23-34]]

^<<v44-23-34,34>>^ Lida a carta, o governador perguntou de que província Paulo era. E, quando soube que era da Cilícia,

[[v44-23-35]]

^<<v44-23-35,35>>^ disse: — Ouvirei você quando chegarem os seus acusadores. E mandou que ele ficasse preso no Pretório de Herodes.

'''

xref:044-atos/044-atos-022.adoc#v44-22-0[&#60; Capítulo Anterior] | <<v44-23-0,Topo>> | xref:044-atos/044-atos-024.adoc#v44-24-0[Próximo Capítulo &#62;]