include::./index.adoc[]

[[v44-22-0]]
=== Atos, 22
// naa ?, NAA - Nova Almeida Atualizada

[[v44-22-1]]

^<<v44-22-1,1>>^ — Irmãos e pais, escutem agora o que tenho a dizer em minha defesa.

[[v44-22-2]]

^<<v44-22-2,2>>^ Quando ouviram que Paulo lhes falava em língua hebraica, fizeram mais silêncio ainda. Paulo continuou:

[[v44-22-3]]

^<<v44-22-3,3>>^ — Eu sou judeu, nasci em Tarso da Cilícia, mas fui criado nesta cidade e aqui fui instruído aos pés de Gamaliel, segundo o rigor da Lei de nossos antepassados, sendo zeloso para com Deus, assim como todos vocês o são no dia de hoje.

[[v44-22-4]]

^<<v44-22-4,4>>^ Persegui este Caminho até a morte, prendendo homens e mulheres e lançando-os na cadeia.

[[v44-22-5]]

^<<v44-22-5,5>>^ Disto são testemunhas o sumo sacerdote e todos os anciãos. Deles eu recebi cartas para os irmãos judeus de Damasco, e fui até lá para trazer amarrados a Jerusalém os que também lá estivessem, para serem punidos.

[[v44-22-6]]

^<<v44-22-6,6>>^ — Ora, aconteceu que, enquanto eu viajava, já perto de Damasco, quase ao meio-dia, repentinamente, uma grande luz do céu brilhou ao redor de mim.

[[v44-22-7]]

^<<v44-22-7,7>>^ Então caí por terra, ouvindo uma voz que me dizia: "Saulo, Saulo, por que você me persegue?"

[[v44-22-8]]

^<<v44-22-8,8>>^ Perguntei: "Senhor, quem é você?" Ao que me respondeu: "Eu sou Jesus, o Nazareno, a quem você persegue."

[[v44-22-9]]

^<<v44-22-9,9>>^ — Os que estavam comigo viram a luz, sem, contudo, perceber o sentido da voz de quem falava comigo.

[[v44-22-10]]

^<<v44-22-10,10>>^ Então perguntei: "Senhor, o que devo fazer?" E o Senhor me disse: "Levante-se, entre em Damasco, onde lhe dirão tudo o que você precisa fazer."

[[v44-22-11]]

^<<v44-22-11,11>>^ Tendo ficado cego por causa da intensidade daquela luz, guiado pela mão dos que estavam comigo, cheguei a Damasco.

[[v44-22-12]]

^<<v44-22-12,12>>^ — Um homem chamado Ananias, piedoso conforme a Lei, tendo bom testemunho de todos os judeus que ali moravam,

[[v44-22-13]]

^<<v44-22-13,13>>^ veio procurar-me e, chegando perto de mim, disse: "Irmão Saulo, recupere a visão!" Nessa mesma hora, recuperei a visão e olhei para ele.

[[v44-22-14]]

^<<v44-22-14,14>>^ Então ele disse: "O Deus de nossos pais escolheu você de antemão para conhecer a vontade dele, ver o Justo e ouvir a voz dele.

[[v44-22-15]]

^<<v44-22-15,15>>^ Porque você terá de ser testemunha dele diante de todos, anunciando as coisas que você tem visto e ouvido.

[[v44-22-16]]

^<<v44-22-16,16>>^ E agora, o que está esperando? Levante-se, receba o batismo e lave os seus pecados, invocando o nome dele."

[[v44-22-17]]

^<<v44-22-17,17>>^ — Quando voltei para Jerusalém, enquanto orava no templo, sobreveio-me um êxtase,

[[v44-22-18]]

^<<v44-22-18,18>>^ e vi o Senhor. Ele me disse: "Ande logo e saia imediatamente de Jerusalém, porque não aceitarão o seu testemunho a meu respeito."

[[v44-22-19]]

^<<v44-22-19,19>>^ Eu respondi: "Senhor, eles bem sabem que eu ia de sinagoga em sinagoga, prendendo e açoitando os que criam em ti.

[[v44-22-20]]

^<<v44-22-20,20>>^ Quando se derramava o sangue de Estêvão, tua testemunha, eu também estava presente, consentia nisso e até guardei as capas dos que o matavam."

[[v44-22-21]]

^<<v44-22-21,21>>^ Mas ele me disse: "Vá, porque eu o enviarei para longe, aos gentios."

[[v44-22-22]]

^<<v44-22-22,22>>^ Até este ponto a multidão ficou ouvindo. Mas, quando Paulo disse isso, começaram a gritar bem alto: — Fora com ele! Mate-o, porque ele não merece viver!

[[v44-22-23]]

^<<v44-22-23,23>>^ Enquanto eles gritavam, tiravam as suas capas e jogavam poeira para o ar,

[[v44-22-24]]

^<<v44-22-24,24>>^ o comandante ordenou que Paulo fosse recolhido à fortaleza e que, sob açoite, fosse interrogado para saber por que motivo estavam gritando assim contra ele.

[[v44-22-25]]

^<<v44-22-25,25>>^ Quando o estavam amarrando com correias, Paulo perguntou ao centurião que ali estava: — Será que vocês têm o direito de açoitar um cidadão romano, sem que ele tenha sido condenado?

[[v44-22-26]]

^<<v44-22-26,26>>^ Ouvindo isto, o centurião procurou o comandante e lhe disse: — Que é isso que o senhor está prestes a fazer? Saiba que aquele homem é cidadão romano.

[[v44-22-27]]

^<<v44-22-27,27>>^ Então o comandante veio e perguntou a Paulo: — Diga-me uma coisa: você é romano? Paulo respondeu: — Sou.

[[v44-22-28]]

^<<v44-22-28,28>>^ E o comandante disse: — Eu tive de gastar muito dinheiro para conseguir essa cidadania. Ao que Paulo respondeu: — Pois eu a tenho de nascença.

[[v44-22-29]]

^<<v44-22-29,29>>^ Imediatamente se afastaram os que iam interrogá-lo com açoites. O próprio comandante ficou com medo quando soube que Paulo era romano, porque tinha mandado amarrá-lo.

[[v44-22-30]]

^<<v44-22-30,30>>^ No dia seguinte, querendo certificar-se dos motivos por que Paulo vinha sendo acusado pelos judeus, o comandante o soltou e ordenou que se reunissem os principais sacerdotes e todo o Sinédrio. E, mandando trazer Paulo, apresentou-o diante deles.

'''

xref:044-atos/044-atos-021.adoc#v44-21-0[&#60; Capítulo Anterior] | <<v44-22-0,Topo>> | xref:044-atos/044-atos-023.adoc#v44-23-0[Próximo Capítulo &#62;]