include::./index.adoc[]

[[v44-7-0]]
=== Atos, 7
// naa ?, NAA - Nova Almeida Atualizada

[[v44-7-1]]

^<<v44-7-1,1>>^ Então o sumo sacerdote perguntou a Estêvão: — Isso de fato é assim?

[[v44-7-2]]

^<<v44-7-2,2>>^ Estêvão respondeu: — Irmãos e pais, escutem. O Deus da glória apareceu a Abraão, nosso pai, quando este estava na Mesopotâmia, antes de morar em Harã,

[[v44-7-3]]

^<<v44-7-3,3>>^ e lhe disse: "Saia da sua terra e do meio da sua parentela e vá para a terra que eu lhe mostrarei."

[[v44-7-4]]

^<<v44-7-4,4>>^ Então Abraão saiu da terra dos caldeus e foi morar em Harã. E dali, com a morte de seu pai, Deus o trouxe para esta terra em que vocês agora estão morando.

[[v44-7-5]]

^<<v44-7-5,5>>^ Nela, não lhe deu herança, nem sequer o espaço de um pé; mas prometeu dar-lhe a posse dela e, depois dele, à sua descendência, embora Abraão ainda não tivesse filhos.

[[v44-7-6]]

^<<v44-7-6,6>>^ E Deus falou que a descendência dele seria peregrina em terra estrangeira, onde seriam escravizados e maltratados durante quatrocentos anos.

[[v44-7-7]]

^<<v44-7-7,7>>^ — Deus disse ainda: "Castigarei a nação da qual forem escravos; e, depois disso, sairão daí e me servirão neste lugar."

[[v44-7-8]]

^<<v44-7-8,8>>^ Então lhe deu a aliança da circuncisão. Assim, Abraão gerou Isaque e o circuncidou no oitavo dia; e Isaque gerou Jacó, e Jacó gerou os doze patriarcas.

[[v44-7-9]]

^<<v44-7-9,9>>^ — Os patriarcas, invejosos de José, venderam-no para ser levado para o Egito. Mas Deus estava com ele

[[v44-7-10]]

^<<v44-7-10,10>>^ e o livrou de todas as suas aflições, concedendo-lhe também graça e sabedoria diante de Faraó, rei do Egito, que o constituiu governador daquela nação e de toda a casa real.

[[v44-7-11]]

^<<v44-7-11,11>>^ Depois houve fome e grande sofrimento em todo o Egito e em Canaã, e nossos pais não achavam o que comer.

[[v44-7-12]]

^<<v44-7-12,12>>^ Mas, quando Jacó ouviu que no Egito havia trigo, mandou, pela primeira vez, os nossos pais até lá.

[[v44-7-13]]

^<<v44-7-13,13>>^ Na segunda vez, José se fez reconhecer pelos seus irmãos, e o Faraó veio a conhecer a família de José.

[[v44-7-14]]

^<<v44-7-14,14>>^ Então José mandou chamar Jacó, seu pai, e toda a sua parentela, isto é, setenta e cinco pessoas.

[[v44-7-15]]

^<<v44-7-15,15>>^ Jacó foi para o Egito, e ali morreu ele e também os nossos pais.

[[v44-7-16]]

^<<v44-7-16,16>>^ Depois eles foram transportados para Siquém e postos no túmulo que Abraão tinha comprado dos filhos de Hamor, em Siquém, pagando um certo preço.

[[v44-7-17]]

^<<v44-7-17,17>>^ — E, quando já estava próximo o tempo em que Deus cumpriria a promessa feita a Abraão, o povo cresceu e se multiplicou no Egito,

[[v44-7-18]]

^<<v44-7-18,18>>^ até que se levantou ali outro rei, que não conhecia José.

[[v44-7-19]]

^<<v44-7-19,19>>^ Este outro rei tratou com astúcia a nossa gente e torturou os nossos pais, a ponto de forçá-los a abandonar seus meninos recém-nascidos, para que não sobrevivessem.

[[v44-7-20]]

^<<v44-7-20,20>>^ Por esse tempo nasceu Moisés, que era formoso aos olhos de Deus. Durante três meses ele foi mantido na casa de seu pai.

[[v44-7-21]]

^<<v44-7-21,21>>^ Quando tiveram de abandoná-lo, a filha de Faraó o recolheu e criou como seu próprio filho.

[[v44-7-22]]

^<<v44-7-22,22>>^ E Moisés foi educado em toda a ciência dos egípcios e era poderoso em palavras e obras.

[[v44-7-23]]

^<<v44-7-23,23>>^ — Quando completou quarenta anos, Moisés teve a ideia de visitar os seus irmãos, os filhos de Israel.

[[v44-7-24]]

^<<v44-7-24,24>>^ Vendo um homem ser maltratado, saiu em defesa dele e vingou o oprimido, matando o egípcio.

[[v44-7-25]]

^<<v44-7-25,25>>^ Ora, Moisés pensava que seus irmãos entenderiam que Deus queria salvá-los por meio dele; eles, porém, não entenderam.

[[v44-7-26]]

^<<v44-7-26,26>>^ No dia seguinte, Moisés aproximou-se de uns que brigavam e procurou reconduzi-los à paz, dizendo: "Homens, vocês são irmãos; por que estão maltratando um ao outro?"

[[v44-7-27]]

^<<v44-7-27,27>>^ Mas o que agredia o seu próximo repeliu Moisés, dizendo: "Quem colocou você como chefe e juiz sobre nós?

[[v44-7-28]]

^<<v44-7-28,28>>^ Será que quer me matar, assim como ontem matou o egípcio?"

[[v44-7-29]]

^<<v44-7-29,29>>^ Ao ouvir isto, Moisés fugiu e se tornou peregrino na terra de Midiã, onde lhe nasceram dois filhos.

[[v44-7-30]]

^<<v44-7-30,30>>^ — Passados quarenta anos, apareceu-lhe, no deserto do monte Sinai, um anjo, por entre as chamas de uma sarça que estava queimando.

[[v44-7-31]]

^<<v44-7-31,31>>^ Moisés ficou maravilhado diante daquela visão e, aproximando-se para contemplá-la, ouviu-se a voz do Senhor, que disse:

[[v44-7-32]]

^<<v44-7-32,32>>^ "Eu sou o Deus dos seus pais, o Deus de Abraão, de Isaque e de Jacó." Moisés, tremendo de medo, não ousava contemplar a sarça.

[[v44-7-33]]

^<<v44-7-33,33>>^ Então o Senhor disse: "Tire as sandálias dos pés, porque o lugar em que você está é terra santa.

[[v44-7-34]]

^<<v44-7-34,34>>^ Certamente vi o sofrimento do meu povo no Egito, ouvi o seu gemido e desci para libertá-lo. Venha, agora; vou mandar você para o Egito."

[[v44-7-35]]

^<<v44-7-35,35>>^ — A este Moisés, a quem tinham rejeitado, dizendo: "Quem colocou você como chefe e juiz?", Deus enviou como chefe e libertador, com a assistência do anjo que lhe apareceu na sarça.

[[v44-7-36]]

^<<v44-7-36,36>>^ Foi Moisés quem os tirou de lá, fazendo prodígios e sinais na terra do Egito, no mar Vermelho e no deserto, durante quarenta anos.

[[v44-7-37]]

^<<v44-7-37,37>>^ Foi ainda Moisés quem disse aos filhos de Israel: "Deus fará com que, do meio dos irmãos de vocês, se levante um profeta semelhante a mim."

[[v44-7-38]]

^<<v44-7-38,38>>^ É este Moisés quem esteve na congregação no deserto, com o anjo que lhe falava no monte Sinai e com os nossos pais. Foi ele quem recebeu palavras vivas para nos transmitir.

[[v44-7-39]]

^<<v44-7-39,39>>^ — Nossos pais não quiseram obedecer a Moisés, mas o rejeitaram e, no seu coração, voltaram para o Egito,

[[v44-7-40]]

^<<v44-7-40,40>>^ dizendo a Arão: "Faça para nós deuses que vão adiante de nós; porque, quanto a este Moisés, que nos tirou da terra do Egito, não sabemos o que lhe aconteceu."

[[v44-7-41]]

^<<v44-7-41,41>>^ Naqueles dias, fizeram um bezerro e ofereceram sacrifício ao ídolo, alegrando-se com as obras das suas mãos.

[[v44-7-42]]

^<<v44-7-42,42>>^ Mas Deus se afastou e os entregou à adoração das estrelas do céu, como está escrito no Livro dos Profetas: "Ó casa de Israel, será que foi para mim que vocês ofereceram vítimas e sacrifícios no deserto, durante quarenta anos?

[[v44-7-43]]

^<<v44-7-43,43>>^ Não é verdade que vocês levantaram o tabernáculo de Moloque e a estrela de Renfã, o deus de vocês, imagens que vocês fizeram para as adorar? Por isso, vou mandar vocês ao exílio para além da Babilônia."

[[v44-7-44]]

^<<v44-7-44,44>>^ — O tabernáculo do testemunho estava entre nossos pais no deserto, como havia ordenado aquele que disse a Moisés que o fizesse segundo o modelo que tinha visto.

[[v44-7-45]]

^<<v44-7-45,45>>^ Também nossos pais, com Josué, tendo recebido o tabernáculo, o levaram, quando tomaram posse das nações que Deus expulsou da presença deles. Foi assim até os dias de Davi,

[[v44-7-46]]

^<<v44-7-46,46>>^ que obteve o favor de Deus e pediu autorização para construir uma casa para o Deus de Jacó.

[[v44-7-47]]

^<<v44-7-47,47>>^ Mas foi Salomão quem lhe edificou a casa.

[[v44-7-48]]

^<<v44-7-48,48>>^ Entretanto, o Altíssimo não habita em casas feitas por mãos humanas. Como diz o profeta:

[[v44-7-49]]

^<<v44-7-49,49>>^ "O céu é o meu trono, e a terra é o estrado dos meus pés. Que casa vocês edificarão para mim, diz o Senhor, ou qual é o lugar do meu repouso?

[[v44-7-50]]

^<<v44-7-50,50>>^ Não é fato que a minha mão fez todas estas coisas?"

[[v44-7-51]]

^<<v44-7-51,51>>^ — Homens teimosos e incircuncisos de coração e de ouvidos, vocês sempre resistem ao Espírito Santo. Vocês fazem exatamente o mesmo que fizeram os seus pais.

[[v44-7-52]]

^<<v44-7-52,52>>^ Qual dos profetas os pais de vocês não perseguiram? Eles mataram os que anteriormente anunciavam a vinda do Justo, do qual vocês agora se tornaram traidores e assassinos,

[[v44-7-53]]

^<<v44-7-53,53>>^ vocês que receberam a lei por ministério de anjos e não a guardaram.

[[v44-7-54]]

^<<v44-7-54,54>>^ Ao ouvirem isto, ficaram com o coração cheio de raiva e rangiam os dentes contra ele.

[[v44-7-55]]

^<<v44-7-55,55>>^ Mas Estêvão, cheio do Espírito Santo, fitou os olhos no céu e viu a glória de Deus e Jesus, que estava à direita de Deus.

[[v44-7-56]]

^<<v44-7-56,56>>^ Então disse: — Eis que vejo os céus abertos e o Filho do Homem, em pé à direita de Deus.

[[v44-7-57]]

^<<v44-7-57,57>>^ Eles, porém, gritando bem alto, taparam os ouvidos e, unânimes, avançaram contra ele.

[[v44-7-58]]

^<<v44-7-58,58>>^ E, expulsando-o da cidade, o apedrejaram. As testemunhas deixaram as capas deles aos pés de um jovem chamado Saulo.

[[v44-7-59]]

^<<v44-7-59,59>>^ E enquanto o apedrejavam, Estêvão orava, dizendo: — Senhor Jesus, recebe o meu espírito!

[[v44-7-60]]

^<<v44-7-60,60>>^ Então, ajoelhando-se, gritou bem alto: — Senhor, não os condenes por causa deste pecado! E, depois que ele disse isso, morreu.

'''

xref:044-atos/044-atos-006.adoc#v44-6-0[&#60; Capítulo Anterior] | <<v44-7-0,Topo>> | xref:044-atos/044-atos-008.adoc#v44-8-0[Próximo Capítulo &#62;]