include::./index.adoc[]

[[v44-8-0]]
=== Atos, 8
// naa ?, NAA - Nova Almeida Atualizada

[[v44-8-1]]

^<<v44-8-1,1>>^ E Saulo consentia na morte de Estêvão. Naquele dia, teve início uma grande perseguição contra a igreja em Jerusalém. Todos, exceto os apóstolos, foram dispersos pelas regiões da Judeia e da Samaria.

[[v44-8-2]]

^<<v44-8-2,2>>^ Alguns homens piedosos sepultaram Estêvão e fizeram grande lamentação por ele.

[[v44-8-3]]

^<<v44-8-3,3>>^ Saulo, porém, queria destruir a igreja. Indo de casa em casa, arrastava homens e mulheres, lançando-os na prisão.

[[v44-8-4]]

^<<v44-8-4,4>>^ Enquanto isso, os que foram dispersos iam por toda parte pregando a palavra.

[[v44-8-5]]

^<<v44-8-5,5>>^ Filipe foi à cidade de Samaria e anunciava Cristo ao povo dali.

[[v44-8-6]]

^<<v44-8-6,6>>^ As multidões, unânimes, davam atenção às coisas que Filipe dizia, ouvindo-as e vendo os sinais que ele fazia.

[[v44-8-7]]

^<<v44-8-7,7>>^ Pois os espíritos imundos, gritando em alta voz, saíam de muitos que estavam possuídos por eles; e muitos paralíticos e coxos foram curados.

[[v44-8-8]]

^<<v44-8-8,8>>^ E houve grande alegria naquela cidade.

[[v44-8-9]]

^<<v44-8-9,9>>^ Havia naquela cidade um homem chamado Simão, que praticava artes mágicas e deixava o povo de Samaria admirado. Dizia ser alguém muito importante,

[[v44-8-10]]

^<<v44-8-10,10>>^ e todos lhe davam ouvidos, do menor ao maior, dizendo: — Este homem é o poder de Deus, chamado "o Grande Poder".

[[v44-8-11]]

^<<v44-8-11,11>>^ Davam atenção a ele porque durante muito tempo os havia impressionado com as suas artes mágicas.

[[v44-8-12]]

^<<v44-8-12,12>>^ Quando, porém, deram crédito a Filipe, que os evangelizava a respeito do Reino de Deus e do nome de Jesus Cristo, iam sendo batizados, tanto homens como mulheres.

[[v44-8-13]]

^<<v44-8-13,13>>^ O próprio Simão abraçou a fé e, tendo sido batizado, acompanhava Filipe de perto, observando extasiado os sinais e grandes milagres praticados.

[[v44-8-14]]

^<<v44-8-14,14>>^ Quando os apóstolos, que estavam em Jerusalém, ouviram que o povo de Samaria tinha recebido a palavra de Deus, enviaram-lhes Pedro e João.

[[v44-8-15]]

^<<v44-8-15,15>>^ Chegando ali, oraram por eles para que recebessem o Espírito Santo,

[[v44-8-16]]

^<<v44-8-16,16>>^ pois o Espírito ainda não havia descido sobre nenhum deles. Tinham apenas sido batizados em nome do Senhor Jesus.

[[v44-8-17]]

^<<v44-8-17,17>>^ Então lhes impuseram as mãos, e eles receberam o Espírito Santo.

[[v44-8-18]]

^<<v44-8-18,18>>^ Quando Simão viu que, pelo fato de os apóstolos imporem as mãos, era concedido o Espírito Santo, ofereceu-lhes dinheiro,

[[v44-8-19]]

^<<v44-8-19,19>>^ dizendo: — Deem também a mim este poder, para que a pessoa sobre a qual eu impuser as mãos receba o Espírito Santo.

[[v44-8-20]]

^<<v44-8-20,20>>^ Mas Pedro respondeu: — Que o seu dinheiro seja destruído junto com você, pois você pensou que com ele poderia adquirir o dom de Deus!

[[v44-8-21]]

^<<v44-8-21,21>>^ Não existe porção nem parte para você neste ministério, porque o seu coração não é reto diante de Deus.

[[v44-8-22]]

^<<v44-8-22,22>>^ Portanto, arrependa-se desse mal e ore ao Senhor. Talvez ele o perdoe por esse intento do seu coração.

[[v44-8-23]]

^<<v44-8-23,23>>^ Pois vejo que você está cheio de inveja e preso em sua maldade.

[[v44-8-24]]

^<<v44-8-24,24>>^ Simão disse aos apóstolos: — Peço que vocês orem ao Senhor por mim, para que não me sobrevenha nada do que vocês disseram.

[[v44-8-25]]

^<<v44-8-25,25>>^ Eles, porém, tendo dado o seu testemunho e pregado a palavra do Senhor, voltaram para Jerusalém e evangelizavam muitas aldeias dos samaritanos.

[[v44-8-26]]

^<<v44-8-26,26>>^ Um anjo do Senhor disse a Filipe: — Levante-se e vá para o Sul, no caminho que desce de Jerusalém a Gaza; este se acha deserto.

[[v44-8-27]]

^<<v44-8-27,27>>^ Filipe se levantou e foi. Havia um etíope, eunuco, alto oficial de Candace, rainha dos etíopes, o qual era superintendente de todo o seu tesouro. Ele tinha vindo adorar em Jerusalém

[[v44-8-28]]

^<<v44-8-28,28>>^ e estava regressando ao seu país. E, assentado na sua carruagem, vinha lendo o profeta Isaías.

[[v44-8-29]]

^<<v44-8-29,29>>^ Então o Espírito disse a Filipe: — Aproxime-se dessa carruagem e acompanhe-a.

[[v44-8-30]]

^<<v44-8-30,30>>^ Correndo para lá, Filipe ouviu que o homem estava lendo o profeta Isaías. Então perguntou: — O senhor entende o que está lendo?

[[v44-8-31]]

^<<v44-8-31,31>>^ Ele respondeu: — Como poderei entender, se ninguém me explicar? E convidou Filipe a subir e sentar-se ao seu lado.

[[v44-8-32]]

^<<v44-8-32,32>>^ Ora, a passagem da Escritura que ele estava lendo era esta: "Foi levado como ovelha ao matadouro; e, como um cordeiro mudo diante do seu tosquiador, ele não abriu a boca.

[[v44-8-33]]

^<<v44-8-33,33>>^ Na sua humilhação, lhe negaram justiça; quem poderá falar da sua descendência? Porque a vida dele é tirada da terra."

[[v44-8-34]]

^<<v44-8-34,34>>^ Então o eunuco disse a Filipe: — Peço que você me explique a quem se refere o profeta. Fala de si mesmo ou de outra pessoa?

[[v44-8-35]]

^<<v44-8-35,35>>^ Então Filipe explicou. E, começando com esta passagem da Escritura, anunciou-lhe a mensagem de Jesus.

[[v44-8-36]]

^<<v44-8-36,36>>^ Seguindo pelo caminho, chegaram a certo lugar onde havia água. Então o eunuco disse: — Eis aqui água. O que impede que eu seja batizado?

[[v44-8-37]]

^<<v44-8-37,37>>^ &#91;Filipe respondeu: — É lícito, se você crê de todo o coração. Então ele disse: — Creio que Jesus Cristo é o Filho de Deus.&#93;

[[v44-8-38]]

^<<v44-8-38,38>>^ Então mandou parar a carruagem, ambos desceram à água, e Filipe batizou o eunuco.

[[v44-8-39]]

^<<v44-8-39,39>>^ Quando saíram da água, o Espírito do Senhor arrebatou Filipe, e o eunuco não o viu mais; e este foi seguindo o seu caminho, cheio de alegria.

[[v44-8-40]]

^<<v44-8-40,40>>^ Mas Filipe foi visto outra vez em Azoto; e, seguindo viagem, evangelizava todas as cidades até chegar a Cesareia.

'''

xref:044-atos/044-atos-007.adoc#v44-7-0[&#60; Capítulo Anterior] | <<v44-8-0,Topo>> | xref:044-atos/044-atos-009.adoc#v44-9-0[Próximo Capítulo &#62;]