include::./index.adoc[]

[[v65-1-0]]
=== Judas, 1
// naa ?, NAA - Nova Almeida Atualizada

[[v65-1-1]]

^<<v65-1-1,1>>^ Judas, servo de Jesus Cristo e irmão de Tiago, aos que foram chamados, são amados em Deus Pai e guardados em Jesus Cristo.

[[v65-1-2]]

^<<v65-1-2,2>>^ Que a misericórdia, a paz e o amor lhes sejam multiplicados.

[[v65-1-3]]

^<<v65-1-3,3>>^ Amados, quando eu me empenhava para escrever-lhes a respeito da salvação que temos em comum, senti que era necessário corresponder-me com vocês, para exortá-los a lutar pela fé que uma vez por todas foi entregue aos santos.

[[v65-1-4]]

^<<v65-1-4,4>>^ Pois certos indivíduos, cuja sentença de condenação foi promulgada há muito tempo, se infiltraram no meio de vocês sem serem notados. São pessoas ímpias, que transformam em libertinagem a graça do nosso Deus e negam o nosso único Soberano e Senhor, Jesus Cristo.

[[v65-1-5]]

^<<v65-1-5,5>>^ Embora vocês já estejam cientes de tudo de uma vez por todas, quero lembrar-lhes que Jesus, tendo libertado um povo, tirando-o da terra do Egito, destruiu, depois, os que não creram.

[[v65-1-6]]

^<<v65-1-6,6>>^ E a anjos — os que não guardaram o seu estado original, mas abandonaram o seu próprio lugar — ele tem guardado sob trevas, em algemas eternas, para o juízo do grande Dia.

[[v65-1-7]]

^<<v65-1-7,7>>^ Igualmente Sodoma, Gomorra e as cidades vizinhas, que também se entregaram à imoralidade e adotaram práticas contrárias à natureza, foram postas como exemplo do castigo de um fogo eterno.

[[v65-1-8]]

^<<v65-1-8,8>>^ Do mesmo modo também esses, quais sonhadores, contaminam a carne, rejeitam a autoridade e insultam os gloriosos seres celestiais.

[[v65-1-9]]

^<<v65-1-9,9>>^ Contudo, nem mesmo o arcanjo Miguel, quando entrou em conflito com o diabo e discutia a respeito do corpo de Moisés, ousou pronunciar sentença difamatória contra ele. Pelo contrário, disse: "O Senhor repreenda você!"

[[v65-1-10]]

^<<v65-1-10,10>>^ Esses, porém, quanto a tudo o que não entendem, difamam; e, quanto a tudo o que compreendem por instinto natural, como animais irracionais, até nessas coisas se corrompem.

[[v65-1-11]]

^<<v65-1-11,11>>^ Ai deles! Porque seguiram o mesmo caminho de Caim e, movidos por ganância, caíram no erro de Balaão, e foram destruídos na revolta de Corá.

[[v65-1-12]]

^<<v65-1-12,12>>^ Esses são como rochas submersas nas festas de fraternidade que vocês fazem, banqueteando-se com vocês sem qualquer receio. São pastores que apascentam a si mesmos; são nuvens sem água impelidas pelos ventos; são árvores que, em plena estação dos frutos, continuam sem frutos, duplamente mortas e arrancadas pela raiz;

[[v65-1-13]]

^<<v65-1-13,13>>^ são ondas bravias do mar, que espumam as suas próprias sujeiras; são estrelas sem rumo, para as quais está reservada a mais profunda escuridão, para sempre.

[[v65-1-14]]

^<<v65-1-14,14>>^ Foi a respeito deles que também profetizou Enoque, o sétimo depois de Adão, dizendo: "Eis que o Senhor vem com milhares de seus santos,

[[v65-1-15]]

^<<v65-1-15,15>>^ para exercer juízo contra todos e para convencer todos os ímpios a respeito de todas as obras ímpias que praticaram e a respeito de todas as palavras insolentes que ímpios pecadores proferiram contra ele."

[[v65-1-16]]

^<<v65-1-16,16>>^ Esses tais são murmuradores, pessoas descontentes que andam segundo as suas paixões. A sua boca vive falando grandes arrogâncias; adulam os outros por motivos interesseiros.

[[v65-1-17]]

^<<v65-1-17,17>>^ Mas vocês, meus amados, lembrem-se das palavras anteriormente proferidas pelos apóstolos de nosso Senhor Jesus Cristo.

[[v65-1-18]]

^<<v65-1-18,18>>^ Eles diziam a vocês: "Nos últimos tempos, haverá zombadores, andando segundo suas ímpias paixões."

[[v65-1-19]]

^<<v65-1-19,19>>^ São estes os que promovem divisões, seguem os seus próprios instintos e não têm o Espírito.

[[v65-1-20]]

^<<v65-1-20,20>>^ Mas vocês, meus amados, edificando-se na fé santíssima que vocês têm, orando no Espírito Santo,

[[v65-1-21]]

^<<v65-1-21,21>>^ mantenham-se no amor de Deus, esperando a misericórdia do nosso Senhor Jesus Cristo, que conduz para a vida eterna.

[[v65-1-22]]

^<<v65-1-22,22>>^ E tenham compaixão de alguns que estão em dúvida;

[[v65-1-23]]

^<<v65-1-23,23>>^ salvem outros, arrebatando-os do fogo; quanto a outros, sejam também compassivos, mas com temor, detestando até a roupa contaminada pela carne.

[[v65-1-24]]

^<<v65-1-24,24>>^ E ao Deus que é poderoso para evitar que vocês tropecem e que pode apresentá-los irrepreensíveis diante da sua glória, com grande alegria,

[[v65-1-25]]

^<<v65-1-25,25>>^ a este que é o único Deus, nosso Salvador, mediante Jesus Cristo, Senhor nosso, sejam a glória, a majestade, o poder e a autoridade, antes de todas as eras, agora, e por toda a eternidade. Amém!

'''

xref:064-3-joao/064-3-joao-001.adoc#v64-1-0[&#60; Capítulo Anterior] | <<v65-1-0,Topo>> | xref:066-apocalipse/066-apocalipse-001.adoc#v66-1-0[Próximo Capítulo &#62;]