include::./index.adoc[]

[[v14-28-0]]
=== 2 Crônicas, 28
// naa ?, NAA - Nova Almeida Atualizada

[[v14-28-1]]

^<<v14-28-1,1>>^ Acaz tinha vinte anos de idade quando começou a reinar e reinou dezesseis anos em Jerusalém. Não fez o que era reto aos olhos do Senhor , ao contrário de Davi, seu pai.

[[v14-28-2]]

^<<v14-28-2,2>>^ Andou nos caminhos dos reis de Israel e até fez imagens fundidas aos baalins.

[[v14-28-3]]

^<<v14-28-3,3>>^ Também queimou incenso no vale de Ben-Hinom e queimou os seus próprios filhos, segundo as abominações dos gentios, que o Senhor  havia expulsado de diante dos filhos de Israel.

[[v14-28-4]]

^<<v14-28-4,4>>^ Também sacrificou e queimou incenso nos lugares altos, nas colinas e debaixo de toda árvore frondosa.

[[v14-28-5]]

^<<v14-28-5,5>>^ Por isso o Senhor , seu Deus, o entregou nas mãos do rei dos sírios, os quais o derrotaram e fizeram uma grande multidão de prisioneiros, que foram levados para Damasco. Acaz também foi entregue nas mãos do rei de Israel, que lhe impôs grande derrota.

[[v14-28-6]]

^<<v14-28-6,6>>^ Num só dia, Peca, filho de Remalias, matou em Judá cento e vinte mil, todos homens poderosos, por terem abandonado o Senhor , Deus de seus pais.

[[v14-28-7]]

^<<v14-28-7,7>>^ Zicri, homem valente de Efraim, matou Maaseias, filho do rei, Azricão, alto oficial do palácio, e Elcana, o segundo depois do rei.

[[v14-28-8]]

^<<v14-28-8,8>>^ Os filhos de Israel levaram presos de Judá, seu povo irmão, duzentos mil: mulheres, filhos e filhas. Saquearam também muitos despojos, que levaram para Samaria.

[[v14-28-9]]

^<<v14-28-9,9>>^ Havia em Samaria um profeta do Senhor , cujo nome era Odede. Ele saiu ao encontro do exército que voltava para Samaria e lhe disse: — Eis que o Senhor , o Deus dos seus pais, ficou irado com Judá e os entregou nas mãos de vocês, e vocês os mataram com tamanha raiva, que chegou até os céus.

[[v14-28-10]]

^<<v14-28-10,10>>^ Agora vocês estão querendo fazer dos filhos de Judá e de Jerusalém os seus escravos e as suas escravas. Será que vocês não são culpados diante do Senhor , seu Deus?

[[v14-28-11]]

^<<v14-28-11,11>>^ Agora escutem o que vou dizer e mandem de volta os prisioneiros que vocês fizeram entre os seus irmãos, porque o furor da ira do Senhor  está sobre vocês.

[[v14-28-12]]

^<<v14-28-12,12>>^ Então alguns dos chefes dos filhos de Efraim, a saber, Azarias, filho de Joanã, Berequias, filho de Mesilemote, Jeizquias, filho de Salum, e Amasa, filho de Hadlai, se levantaram contra os que voltavam da guerra

[[v14-28-13]]

^<<v14-28-13,13>>^ e lhes disseram: — Não tragam esses prisioneiros para cá, porque vocês estão querendo aumentar ainda mais os nossos pecados e a nossa culpa diante do Senhor . A nossa culpa já é grande, e o furor da ira do Senhor  está sobre Israel.

[[v14-28-14]]

^<<v14-28-14,14>>^ Então os homens armados deixaram os prisioneiros e o despojo diante dos chefes e de toda a congregação.

[[v14-28-15]]

^<<v14-28-15,15>>^ Os homens que foram citados nominalmente se levantaram, cuidaram dos prisioneiros e, com as roupas que estavam no meio dos despojos, vestiram todos os que estavam nus. Deram-lhes roupas, sandálias, comida, bebida, e os ungiram. Fizeram montar em jumentos todos os que estavam fracos, e os levaram até Jericó, a cidade das palmeiras, a seus irmãos. Então voltaram para Samaria.

[[v14-28-16]]

^<<v14-28-16,16>>^ Naquele tempo, o rei Acaz mandou pedir aos reis da Assíria que o ajudassem,

[[v14-28-17]]

^<<v14-28-17,17>>^ porque, de novo, os edomitas tinham vindo e derrotado Judá, levando alguns prisioneiros.

[[v14-28-18]]

^<<v14-28-18,18>>^ Também os filisteus atacaram as cidades da Sefelá e do sul de Judá. Tomaram Bete-Semes, Aijalom, Gederote, Socó e suas aldeias, Timna e suas aldeias e Ginzo e suas aldeias; e ficaram morando ali.

[[v14-28-19]]

^<<v14-28-19,19>>^ Porque o Senhor  humilhou Judá por causa do rei Acaz, porque este havia permitido que Judá caísse em imoralidade e foi completamente infiel ao Senhor .

[[v14-28-20]]

^<<v14-28-20,20>>^ O rei Tiglate-Pileser, da Assíria, atendeu o pedido de Acaz. Porém, em vez de ajudá-lo, deixou-o num aperto ainda maior.

[[v14-28-21]]

^<<v14-28-21,21>>^ Porque Acaz pegou objetos da Casa do Senhor , do palácio real e das casas dos príncipes e os deu ao rei da Assíria; porém isso não lhe serviu de nada.

[[v14-28-22]]

^<<v14-28-22,22>>^ No tempo da sua angústia, foi ainda mais infiel ao Senhor ; ele mesmo, o rei Acaz.

[[v14-28-23]]

^<<v14-28-23,23>>^ Ofereceu sacrifícios aos deuses de Damasco, que o derrotaram, pois pensava: "Visto que os deuses dos reis da Síria os ajudam, eu lhes oferecerei sacrifícios para que ajudem a mim também." Porém eles foram a sua ruína e a de todo o Israel.

[[v14-28-24]]

^<<v14-28-24,24>>^ Acaz ajuntou os utensílios da Casa de Deus, os quebrou em pedaços e fechou os portões da Casa do Senhor ; e fez para si altares em todos os cantos de Jerusalém.

[[v14-28-25]]

^<<v14-28-25,25>>^ Em cada cidade de Judá construiu lugares altos para queimar incenso a outros deuses e assim provocou à ira o Senhor , Deus de seus pais.

[[v14-28-26]]

^<<v14-28-26,26>>^ Quanto aos demais atos de Acaz e a todos os seus caminhos, tanto os primeiros como os últimos, está tudo escrito no Livro da História dos Reis de Judá e de Israel.

[[v14-28-27]]

^<<v14-28-27,27>>^ Acaz morreu e foi sepultado na cidade de Jerusalém, mas não nos túmulos dos reis de Israel. E Ezequias, seu filho, reinou em seu lugar.

'''

xref:014-2-cronicas/014-2-cronicas-027.adoc#v14-27-0[&#60; Capítulo Anterior] | <<v14-28-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-029.adoc#v14-29-0[Próximo Capítulo &#62;]