include::./index.adoc[]

[[v14-18-0]]
=== 2 Crônicas, 18
// naa ?, NAA - Nova Almeida Atualizada

[[v14-18-1]]

^<<v14-18-1,1>>^ Josafá tinha riquezas e glória em abundância, e tornou-se genro de Acabe.

[[v14-18-2]]

^<<v14-18-2,2>>^ Passados alguns anos, Josafá foi visitar Acabe, em Samaria. Acabe matou ovelhas e bois em abundância, para Josafá e para o povo que o acompanhava; e o persuadiu a ir com ele atacar Ramote-Gileade.

[[v14-18-3]]

^<<v14-18-3,3>>^ Acabe, rei de Israel, perguntou a Josafá, rei de Judá: — Você vai comigo a Ramote-Gileade? Josafá respondeu: — Sou como você é, e o meu povo é como o seu povo. Iremos com você à guerra.

[[v14-18-4]]

^<<v14-18-4,4>>^ Josafá disse mais ao rei de Israel: — Consulte primeiro a palavra do Senhor .

[[v14-18-5]]

^<<v14-18-5,5>>^ Então o rei de Israel reuniu os profetas, quatrocentos homens, e lhes perguntou: — Devemos ir e lutar contra Ramote-Gileade ou devo me conter? Eles responderam: — Vá, porque Deus a entregará nas mãos do rei.

[[v14-18-6]]

^<<v14-18-6,6>>^ Mas Josafá perguntou: — Não há aqui ainda algum profeta do Senhor , para o consultarmos?

[[v14-18-7]]

^<<v14-18-7,7>>^ O rei de Israel respondeu a Josafá: — Há um ainda, por meio de quem podemos consultar o Senhor . Mas eu o odeio, porque nunca profetiza de mim o que é bom, mas somente o que é mau.

[[v14-18-8]]

^<<v14-18-8,8>>^ O nome dele é Micaías, filho de Inlá. Josafá disse: — O rei não deveria falar assim. Então o rei de Israel chamou um oficial e disse: — Traga-me depressa Micaías, filho de Inlá.

[[v14-18-9]]

^<<v14-18-9,9>>^ O rei de Israel e Josafá, rei de Judá, estavam assentados, cada um no seu trono, vestidos de trajes reais, numa eira à entrada do portão da cidade de Samaria; e todos os profetas profetizavam diante deles.

[[v14-18-10]]

^<<v14-18-10,10>>^ Zedequias, filho de Quenaana, fez para si uns chifres de ferro e disse: — Assim diz o Senhor : "Com estes você dará chifradas nos sírios até que estejam destruídos."

[[v14-18-11]]

^<<v14-18-11,11>>^ Todos os profetas profetizaram assim, dizendo: — Suba a Ramote-Gileade! Você triunfará! O Senhor  a entregará nas mãos do rei.

[[v14-18-12]]

^<<v14-18-12,12>>^ O mensageiro que tinha ido chamar Micaías falou-lhe, dizendo: — Eis que as palavras dos profetas a uma voz predizem coisas boas para o rei. Portanto, que a sua palavra seja como a de um deles; fale o que é bom.

[[v14-18-13]]

^<<v14-18-13,13>>^ Micaías respondeu: — Tão certo como vive o Senhor , o que o meu Deus me disser, isso falarei.

[[v14-18-14]]

^<<v14-18-14,14>>^ Quando ele chegou à presença do rei, este lhe perguntou: — Micaías, devemos ir a Ramote-Gileade para a batalha ou devo me conter? Ele respondeu: — Vá! Você triunfará! Eles serão entregues nas mãos de vocês.

[[v14-18-15]]

^<<v14-18-15,15>>^ O rei lhe disse: — Quantas vezes devo fazer você jurar que não me fale a não ser a verdade em nome do Senhor ?

[[v14-18-16]]

^<<v14-18-16,16>>^ Então Micaías disse: — Vi todo o Israel disperso pelos montes, como ovelhas que não têm pastor. E o Senhor  Deus disse: "Estes não têm dono; que cada um volte em paz para a sua casa."

[[v14-18-17]]

^<<v14-18-17,17>>^ Então o rei de Israel disse a Josafá: — Eu não disse a você que a meu respeito ele não profetiza o que é bom, mas somente o que é mau?

[[v14-18-18]]

^<<v14-18-18,18>>^ Micaías prosseguiu: — Portanto, ouçam a palavra do Senhor : Vi o Senhor  assentado no seu trono, e todo o exército do céu estava à sua direita e à sua esquerda.

[[v14-18-19]]

^<<v14-18-19,19>>^ Então o Senhor  perguntou: "Quem enganará Acabe, o rei de Israel, para que vá e seja morto em Ramote-Gileade?" E um dizia uma coisa, e outro dizia outra coisa.

[[v14-18-20]]

^<<v14-18-20,20>>^ Então um espírito saiu, se apresentou diante do Senhor  e disse: "Eu o enganarei." O Senhor  perguntou: "Como?"

[[v14-18-21]]

^<<v14-18-21,21>>^ Ele respondeu: "Sairei e serei um espírito mentiroso na boca de todos os profetas do rei." Então o Senhor  disse: "Você conseguirá enganá-lo. Vá e faça assim."

[[v14-18-22]]

^<<v14-18-22,22>>^ E agora eis que o Senhor  pôs esse espírito mentiroso na boca destes seus profetas e o Senhor  declarou que um mal vai lhe acontecer.

[[v14-18-23]]

^<<v14-18-23,23>>^ Então Zedequias, filho de Quenaana, chegou, deu uma bofetada em Micaías e perguntou: — Por qual caminho passou o Espírito do Senhor  ao sair de mim para falar com você?

[[v14-18-24]]

^<<v14-18-24,24>>^ Micaías respondeu: — Eis que você o verá no dia em que estiver correndo de quarto em quarto, tentando se esconder.

[[v14-18-25]]

^<<v14-18-25,25>>^ Então o rei de Israel disse: — Prendam Micaías e levem-no de volta a Amom, governador da cidade, e a Joás, filho do rei.

[[v14-18-26]]

^<<v14-18-26,26>>^ E digam: "Assim diz o rei: Metam este homem na cadeia e o ponham a pão e água, até que eu volte em paz."

[[v14-18-27]]

^<<v14-18-27,27>>^ Micaías disse: — Se o rei de fato voltar em paz, é porque o Senhor  não falou por meio de mim. E acrescentou: — Que todos os povos ouçam isto!

[[v14-18-28]]

^<<v14-18-28,28>>^ O rei de Israel e Josafá, rei de Judá, foram atacar Ramote-Gileade.

[[v14-18-29]]

^<<v14-18-29,29>>^ O rei de Israel disse a Josafá: — Eu vou me disfarçar e entrar no combate, mas você use os seus trajes reais. E assim o rei de Israel se disfarçou, e eles entraram no combate.

[[v14-18-30]]

^<<v14-18-30,30>>^ Ora, o rei da Síria havia ordenado aos capitães dos seus carros de guerra que não lutassem nem contra pequeno nem contra grande, mas somente contra o rei de Israel.

[[v14-18-31]]

^<<v14-18-31,31>>^ Quando os capitães dos carros viram Josafá, disseram: — Aquele é o rei de Israel. E se dirigiram até ele para o atacar. Porém Josafá gritou, e o Senhor  o socorreu; Deus os desviou dele.

[[v14-18-32]]

^<<v14-18-32,32>>^ Quando os capitães dos carros de guerra viram que não era o rei de Israel, deixaram de persegui-lo.

[[v14-18-33]]

^<<v14-18-33,33>>^ Então um homem entesou o arco e, atirando ao acaso, atingiu o rei de Israel por entre as juntas da sua armadura. Então o rei Acabe disse ao condutor do seu carro: — Dê a volta e leve-me para fora do combate, porque estou gravemente ferido.

[[v14-18-34]]

^<<v14-18-34,34>>^ A batalha se intensificou naquele dia. Quanto ao rei de Israel, segurou-se em pé no carro de frente para os sírios, até a tarde. Mas, ao pôr do sol, morreu.

'''

xref:014-2-cronicas/014-2-cronicas-017.adoc#v14-17-0[&#60; Capítulo Anterior] | <<v14-18-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-019.adoc#v14-19-0[Próximo Capítulo &#62;]