include::./index.adoc[]

[[v14-3-0]]
=== 2 Crônicas, 3
// naa ?, NAA - Nova Almeida Atualizada

[[v14-3-1]]

^<<v14-3-1,1>>^ Salomão começou a edificar a Casa do Senhor  em Jerusalém, no monte Moriá, onde o Senhor  havia aparecido a Davi, seu pai, lugar que Davi tinha designado na eira de Ornã, o jebuseu.

[[v14-3-2]]

^<<v14-3-2,2>>^ Começou a edificar no segundo dia do segundo mês, no quarto ano do seu reinado.

[[v14-3-3]]

^<<v14-3-3,3>>^ Foram estas as medidas dos alicerces que Salomão lançou para edificar a Casa de Deus: vinte e sete metros de comprimento por nove de largura, segundo o padrão antigo.

[[v14-3-4]]

^<<v14-3-4,4>>^ O pórtico diante da casa tinha nove metros no sentido da largura do Lugar Santo, e a altura era de cinquenta e quatro metros. Salomão revestiu o interior do pórtico de ouro puro.

[[v14-3-5]]

^<<v14-3-5,5>>^ Também fez forrar de madeira de cipreste a sala grande, revestiu-a de ouro puro e gravou nela palmeiras e correntes.

[[v14-3-6]]

^<<v14-3-6,6>>^ Também enfeitou a sala com pedras preciosas; e o ouro era de Parvaim.

[[v14-3-7]]

^<<v14-3-7,7>>^ Revestiu de ouro a sala, as vigas, os umbrais, as paredes e as portas; e esculpiu querubins nas paredes.

[[v14-3-8]]

^<<v14-3-8,8>>^ Fez o Santo dos Santos, cujo comprimento era de nove metros, segundo a largura da sala grande, e a largura também era de nove metros. Revestiu o seu interior com vinte toneladas de ouro puro.

[[v14-3-9]]

^<<v14-3-9,9>>^ O peso dos pregos era de seiscentos gramas de ouro. Também revestiu de ouro os cenáculos.

[[v14-3-10]]

^<<v14-3-10,10>>^ No Santo dos Santos, Salomão fez dois querubins de madeira e os revestiu de ouro.

[[v14-3-11]]

^<<v14-3-11,11>>^ As asas estendidas dos querubins mediam, juntas, quatro metros e meio; a asa de um deles, de dois metros e vinte e cinco, tocava na parede do templo; e a outra asa, igualmente de dois metros e vinte e cinco, tocava na asa do outro querubim.

[[v14-3-12]]

^<<v14-3-12,12>>^ Também a asa do outro querubim era de dois metros e vinte e cinco e tocava na outra parede; e a outra asa, igualmente de dois metros e vinte e cinco, estava unida à asa do outro querubim. As asas destes querubins se estendiam por nove metros.

[[v14-3-13]]

^<<v14-3-13,13>>^ Eles estavam em pé, com o rosto voltado para o Santo Lugar.

[[v14-3-14]]

^<<v14-3-14,14>>^ Salomão também fez o véu de pano azul, púrpura, carmesim e linho fino; e mandou bordar nele figuras de querubins.

[[v14-3-15]]

^<<v14-3-15,15>>^ Salomão fez também diante da sala duas colunas de quinze metros e meio de altura, com um capitel de dois metros e vinte sobre cada uma delas.

[[v14-3-16]]

^<<v14-3-16,16>>^ Também fez correntes, como as do Santo dos Santos, e as pôs no alto das colunas; fez também cem romãs, as quais pôs nas correntes.

[[v14-3-17]]

^<<v14-3-17,17>>^ Levantou as colunas diante do templo, uma à direita e outra à esquerda. À coluna da direita deu o nome de Jaquim, e à coluna da esquerda deu o nome de Boaz.

'''

xref:014-2-cronicas/014-2-cronicas-002.adoc#v14-2-0[&#60; Capítulo Anterior] | <<v14-3-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-004.adoc#v14-4-0[Próximo Capítulo &#62;]