include::./index.adoc[]

[[v14-16-0]]
=== 2 Crônicas, 16
// naa ?, NAA - Nova Almeida Atualizada

[[v14-16-1]]

^<<v14-16-1,1>>^ No trigésimo sexto ano do reinado de Asa, Baasa, rei de Israel, invadiu Judá e começou a edificar a cidade de Ramá, para impedir a entrada e a saída do território de Asa, rei de Judá.

[[v14-16-2]]

^<<v14-16-2,2>>^ Então Asa tirou prata e ouro dos tesouros da Casa do Senhor  e dos tesouros do palácio real e enviou servos a Ben-Hadade, rei da Síria, que morava em Damasco, dizendo:

[[v14-16-3]]

^<<v14-16-3,3>>^ — Que haja uma aliança entre mim e você, como houve entre o meu pai e o seu pai. Eis que estou lhe enviando prata e ouro. Vá e anule a sua aliança com Baasa, rei de Israel, para que ele se retire do meu território.

[[v14-16-4]]

^<<v14-16-4,4>>^ Ben-Hadade deu ouvidos ao rei Asa e enviou os capitães dos seus exércitos contra as cidades de Israel. Eles conquistaram Ijom, Dã, Abel-Maim e todas as cidades-armazéns de Naftali.

[[v14-16-5]]

^<<v14-16-5,5>>^ Quando Baasa soube disso, deixou de edificar Ramá e não continuou a sua obra.

[[v14-16-6]]

^<<v14-16-6,6>>^ Então o rei Asa reuniu todo o povo de Judá, e trouxeram de Ramá as pedras e a madeira que Baasa havia usado para edificá-la. Com elas Asa edificou Geba e Mispa.

[[v14-16-7]]

^<<v14-16-7,7>>^ Naquele tempo, o vidente Hanani foi falar com Asa, rei de Judá, e lhe disse: — Você confiou no rei da Síria e não confiou no Senhor , seu Deus, e por isso o exército do rei da Síria escapou das suas mãos.

[[v14-16-8]]

^<<v14-16-8,8>>^ Não é verdade que os etíopes e os líbios formavam um grande exército, com muitos carros de guerra e cavaleiros? Mas, porque você confiou no Senhor , ele os entregou nas suas mãos.

[[v14-16-9]]

^<<v14-16-9,9>>^ Porque, quanto ao Senhor , os seus olhos passam por toda a terra, para dar força àqueles cujo coração é totalmente dele. Nisto você cometeu uma loucura. Por isso, de agora em diante haverá guerras contra você.

[[v14-16-10]]

^<<v14-16-10,10>>^ Porém Asa se indignou contra o profeta e o lançou na prisão, porque estava enfurecido contra ele por causa disso. Na mesma ocasião, Asa oprimiu alguns do povo.

[[v14-16-11]]

^<<v14-16-11,11>>^ Eis que os demais atos de Asa, tanto os primeiros como os últimos, está tudo escrito no Livro da História dos Reis de Judá e de Israel.

[[v14-16-12]]

^<<v14-16-12,12>>^ No trigésimo nono ano do seu reinado, Asa contraiu uma doença nos pés, e essa doença era muito grave. Porém, na sua enfermidade ele não recorreu ao Senhor , mas confiou nos médicos.

[[v14-16-13]]

^<<v14-16-13,13>>^ Asa morreu no quadragésimo primeiro ano do seu reinado.

[[v14-16-14]]

^<<v14-16-14,14>>^ Foi sepultado no túmulo que ele tinha mandado abrir para si na Cidade de Davi. Puseram-no sobre um leito cheio de perfumes e de várias especiarias, preparados segundo a arte dos perfumistas. Depois fizeram uma grande fogueira em honra dele.

'''

xref:014-2-cronicas/014-2-cronicas-015.adoc#v14-15-0[&#60; Capítulo Anterior] | <<v14-16-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-017.adoc#v14-17-0[Próximo Capítulo &#62;]