include::./index.adoc[]

[[v14-34-0]]
=== 2 Crônicas, 34
// naa ?, NAA - Nova Almeida Atualizada

[[v14-34-1]]

^<<v14-34-1,1>>^ Josias tinha oito anos de idade quando começou a reinar e reinou trinta e um anos em Jerusalém.

[[v14-34-2]]

^<<v14-34-2,2>>^ Josias fez o que era reto aos olhos do Senhor , andou nos caminhos de Davi, seu pai, e não se desviou nem para a direita nem para a esquerda.

[[v14-34-3]]

^<<v14-34-3,3>>^ No oitavo ano de seu reinado, sendo ainda moço, Josias começou a buscar o Deus de Davi, seu pai. E, no décimo segundo ano, começou a purificar Judá e Jerusalém dos lugares altos, dos postes da deusa Aserá e das imagens de escultura e de fundição.

[[v14-34-4]]

^<<v14-34-4,4>>^ Na presença dele, derrubaram os altares dos baalins. Ele despedaçou os altares do incenso que estavam acima deles. Quebrou os postes da deusa Aserá e as imagens de escultura e de fundição, reduziu-os a pó e o espalhou sobre as sepulturas dos que tinham oferecido sacrifícios a esses ídolos.

[[v14-34-5]]

^<<v14-34-5,5>>^ Queimou os ossos dos sacerdotes pagãos sobre os altares deles e purificou Judá e Jerusalém.

[[v14-34-6]]

^<<v14-34-6,6>>^ Fez o mesmo nas cidades de Manassés, de Efraim e de Simeão, até Naftali, por todos os lados no meio das suas ruínas.

[[v14-34-7]]

^<<v14-34-7,7>>^ Depois de derrubar os altares, os postes da deusa Aserá e as imagens de escultura, até reduzi-los a pó, e depois de despedaçar todos os altares de incenso em toda a terra de Israel, Josias voltou para Jerusalém.

[[v14-34-8]]

^<<v14-34-8,8>>^ No décimo oitavo ano do seu reinado, havendo já purificado a terra e o templo, Josias ordenou que Safã, filho de Azalias, Maaseias, governador da cidade, e Joá, filho de Joacaz, cronista, reparassem a Casa do Senhor , seu Deus.

[[v14-34-9]]

^<<v14-34-9,9>>^ Foram até o sumo sacerdote Hilquias e entregaram o dinheiro que tinha sido trazido à Casa de Deus e que os levitas, guardas da porta, tinham ajuntado, dinheiro provindo das mãos de Manassés, de Efraim e de todo o resto de Israel, bem como de todo o Judá e Benjamim e dos moradores de Jerusalém.

[[v14-34-10]]

^<<v14-34-10,10>>^ Eles o entregaram aos que dirigiam a obra e tinham a seu encargo a Casa do Senhor , para que pagassem àqueles que faziam a obra, trabalhadores na Casa do Senhor , para repararem e restaurarem o templo.

[[v14-34-11]]

^<<v14-34-11,11>>^ Deram o dinheiro aos carpinteiros e aos construtores, para comprarem pedras lavradas e madeiras para as junções e para servirem de vigas para as casas que os reis de Judá deixaram cair em ruína.

[[v14-34-12]]

^<<v14-34-12,12>>^ Esses homens trabalharam fielmente na obra. Os superintendentes deles eram Jaate e Obadias, levitas, dos filhos de Merari, bem como Zacarias e Mesulão, dos filhos dos coatitas, para supervisionar a obra.

[[v14-34-13]]

^<<v14-34-13,13>>^ Todos os levitas peritos em instrumentos musicais eram superintendentes dos carregadores e dirigiam todos os que faziam a obra, em qualquer tipo de trabalho. Outros levitas eram escrivães, oficiais e porteiros.

[[v14-34-14]]

^<<v14-34-14,14>>^ Enquanto se tirava o dinheiro que havia sido trazido à Casa do Senhor , Hilquias, o sacerdote, achou o Livro da Lei do Senhor , dada por meio de Moisés.

[[v14-34-15]]

^<<v14-34-15,15>>^ Então Hilquias disse ao escrivão Safã: — Achei o Livro da Lei na Casa do Senhor .

[[v14-34-16]]

^<<v14-34-16,16>>^ Hilquias entregou o livro a Safã. Então Safã levou o livro ao rei e lhe deu relatório, dizendo: — Tudo o que o senhor, ó rei, encomendou aos seus servos, eles estão fazendo.

[[v14-34-17]]

^<<v14-34-17,17>>^ Contaram o dinheiro que estava na Casa do Senhor  e o entregaram nas mãos dos que dirigem a obra e dos que a executam.

[[v14-34-18]]

^<<v14-34-18,18>>^ E o escrivão Safã acrescentou: — O sacerdote Hilquias me entregou um livro. E Safã leu o livro em voz alta diante do rei.

[[v14-34-19]]

^<<v14-34-19,19>>^ Quando o rei Josias ouviu as palavras da Lei, rasgou as suas roupas.

[[v14-34-20]]

^<<v14-34-20,20>>^ Então deu ordens a Hilquias, a Aicão, filho de Safã, a Abdom, filho de Mica, a Safã, o escrivão, e a Asaías, servo do rei, dizendo:

[[v14-34-21]]

^<<v14-34-21,21>>^ — Vão consultar o Senhor  por mim e pelos que restaram em Israel e Judá, a respeito das palavras deste livro que foi encontrado. Porque é grande o furor do Senhor , que se derramou sobre nós, porque os nossos pais não guardaram a palavra do Senhor , para fazerem segundo tudo o que está escrito neste livro.

[[v14-34-22]]

^<<v14-34-22,22>>^ Então Hilquias e os enviados pelo rei foram falar com a profetisa Hulda, esposa de Salum, encarregado das vestimentas da Casa do Senhor, filho de Tocate, filho de Harás. Hulda morava na parte nova da cidade, em Jerusalém. Eles lhe contaram o que havia acontecido,

[[v14-34-23]]

^<<v14-34-23,23>>^ e ela lhes disse: — Assim diz o Senhor , o Deus de Israel: "Digam ao homem que os enviou a mim:

[[v14-34-24]]

^<<v14-34-24,24>>^ ‘Assim diz o Senhor : Eis que trarei desgraça sobre este lugar e sobre os seus moradores, a saber, todas as maldições escritas no livro que leram diante do rei de Judá.

[[v14-34-25]]

^<<v14-34-25,25>>^ Por terem me abandonado e queimado incenso a outros deuses, para me provocarem à ira com todas as obras das suas mãos, o meu furor se derramou sobre este lugar e não se apagará.’

[[v14-34-26]]

^<<v14-34-26,26>>^ Mas ao rei de Judá, que os enviou para consultar o Senhor , digam o seguinte: ‘Assim diz o Senhor , o Deus de Israel, a respeito das palavras que você ouviu:

[[v14-34-27]]

^<<v14-34-27,27>>^ Visto que o seu coração se enterneceu e você se humilhou diante de Deus, quando ouviu as ameaças que ele fez contra este lugar e contra os seus moradores, e se humilhou diante de mim, rasgou as suas roupas e chorou diante de mim, também eu ouvi a sua oração, diz o Senhor .

[[v14-34-28]]

^<<v14-34-28,28>>^ Deixarei que você morra e seja sepultado em paz, e os seus olhos não verão todo o mal que trarei sobre este lugar e sobre os seus moradores.’" Então eles levaram esta resposta ao rei.

[[v14-34-29]]

^<<v14-34-29,29>>^ Então o rei deu ordem, e todos os anciãos de Judá e de Jerusalém se ajuntaram.

[[v14-34-30]]

^<<v14-34-30,30>>^ O rei subiu à Casa do Senhor , e com ele foram todos os homens de Judá, os moradores de Jerusalém, os sacerdotes, os levitas e todo o povo, desde o maior até o menor. E o rei leu diante deles todas as palavras do Livro da Aliança que havia sido encontrado na Casa do Senhor .

[[v14-34-31]]

^<<v14-34-31,31>>^ O rei se pôs em pé no seu lugar e fez aliança diante do Senhor , para o seguir, guardar os seus mandamentos, os seus testemunhos e os seus estatutos, de todo o seu coração e de toda a sua alma, cumprindo as palavras da aliança, que estavam escritas naquele livro.

[[v14-34-32]]

^<<v14-34-32,32>>^ Todos os que se encontravam em Jerusalém e em Benjamim concordaram com esta aliança; e os moradores de Jerusalém fizeram segundo a aliança de Deus, o Deus dos seus pais.

[[v14-34-33]]

^<<v14-34-33,33>>^ Josias tirou todas as abominações de todas as terras que eram dos filhos de Israel e obrigou todos os que estavam em Israel a servir o Senhor , seu Deus. Enquanto Josias viveu, não deixaram de seguir o Senhor , Deus de seus pais.

'''

xref:014-2-cronicas/014-2-cronicas-033.adoc#v14-33-0[&#60; Capítulo Anterior] | <<v14-34-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-035.adoc#v14-35-0[Próximo Capítulo &#62;]