include::./index.adoc[]

[[v14-21-0]]
=== 2 Crônicas, 21
// naa ?, NAA - Nova Almeida Atualizada

[[v14-21-1]]

^<<v14-21-1,1>>^ Josafá morreu e foi sepultado no túmulo de seus pais, na Cidade de Davi; e Jeorão, seu filho, reinou em seu lugar.

[[v14-21-2]]

^<<v14-21-2,2>>^ Jeorão tinha irmãos, filhos de Josafá. Eles se chamavam Azarias, Jeiel, Zacarias, Azarias, Micael e Sefatias, e eram todos filhos de Josafá, rei de Judá.

[[v14-21-3]]

^<<v14-21-3,3>>^ O pai deles lhes deu muitos presentes de prata, de ouro e de coisas preciosas, além de cidades fortificadas em Judá; porém deu o reino a Jeorão, por ser o primogênito.

[[v14-21-4]]

^<<v14-21-4,4>>^ Tendo Jeorão assumido o reino de seu pai e havendo-se fortalecido, matou à espada todos os seus irmãos e também alguns dos chefes de Israel.

[[v14-21-5]]

^<<v14-21-5,5>>^ Jeorão tinha trinta e dois anos de idade quando começou a reinar e reinou oito anos em Jerusalém.

[[v14-21-6]]

^<<v14-21-6,6>>^ Andou nos caminhos dos reis de Israel, como também fizeram os da casa de Acabe, porque era casado com uma filha dele. E Jeorão fez o que era mau aos olhos do Senhor .

[[v14-21-7]]

^<<v14-21-7,7>>^ Porém o Senhor  não quis destruir a casa de Davi por causa da aliança que havia feito com ele e segundo a promessa que lhe havia feito de dar uma lâmpada a ele e aos seus filhos para sempre.

[[v14-21-8]]

^<<v14-21-8,8>>^ Nos dias de Jeorão, os edomitas se revoltaram contra o poder de Judá e constituíram o seu próprio rei.

[[v14-21-9]]

^<<v14-21-9,9>>^ Por isso Jeorão foi até lá com todos os seus chefes e com todos os seus carros de guerra. Ele se levantou de noite e atacou os edomitas que o cercavam e os capitães dos carros de guerra.

[[v14-21-10]]

^<<v14-21-10,10>>^ Assim, Edom se rebelou para se livrar do poder de Judá até o dia de hoje. Na mesma época a cidade de Libna também se rebelou contra Jeorão, porque este havia abandonado o Senhor , Deus de seus pais.

[[v14-21-11]]

^<<v14-21-11,11>>^ Jeorão também construiu lugares altos nos montes de Judá, seduziu os moradores de Jerusalém à idolatria, e fez com que Judá se afastasse do Senhor .

[[v14-21-12]]

^<<v14-21-12,12>>^ Então lhe chegou às mãos uma carta do profeta Elias, em que estava escrito: "Assim diz o Senhor , Deus de Davi, seu pai: ‘Você não andou nos caminhos de seu pai Josafá, nem nos caminhos de Asa, rei de Judá,

[[v14-21-13]]

^<<v14-21-13,13>>^ mas andou nos caminhos dos reis de Israel e seduziu o povo de Judá e os moradores de Jerusalém à idolatria, segundo a idolatria da casa de Acabe. Além disso, você matou os seus próprios irmãos, da casa de seu pai, que eram melhores do que você.

[[v14-21-14]]

^<<v14-21-14,14>>^ Por isso o Senhor  castigará com um grande flagelo este povo do qual você é rei, bem como os seus filhos, as mulheres que você tem e todas as suas posses.

[[v14-21-15]]

^<<v14-21-15,15>>^ Você terá uma doença grave nos seus intestinos, doença esta que aumentará dia após dia, até que os seus intestinos saiam do corpo.’"

[[v14-21-16]]

^<<v14-21-16,16>>^ O Senhor  despertou contra Jeorão o ânimo dos filisteus e dos árabes que moravam perto dos etíopes.

[[v14-21-17]]

^<<v14-21-17,17>>^ Estes subiram contra o reino de Judá e o invadiram. Levaram embora todos os bens que encontraram no palácio real, inclusive os filhos e as mulheres dele, assim que não lhe deixaram filho algum, a não ser Jeoacaz, o mais moço deles.

[[v14-21-18]]

^<<v14-21-18,18>>^ Depois de tudo isto, o Senhor  feriu Jeorão com uma doença incurável nos intestinos.

[[v14-21-19]]

^<<v14-21-19,19>>^ A doença ia aumentando dia após dia e, ao final de dois anos, os intestinos saíram por causa da doença, e ele morreu com dores horríveis. O seu povo não fez nenhuma fogueira em honra dele, como havia feito para os seus pais.

[[v14-21-20]]

^<<v14-21-20,20>>^ Jeorão tinha trinta e dois anos de idade quando começou a reinar e reinou oito anos em Jerusalém. E se foi sem deixar saudades. Foi sepultado na Cidade de Davi, mas não nos túmulos dos reis.

'''

xref:014-2-cronicas/014-2-cronicas-020.adoc#v14-20-0[&#60; Capítulo Anterior] | <<v14-21-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-022.adoc#v14-22-0[Próximo Capítulo &#62;]