include::./index.adoc[]

[[v14-36-0]]
=== 2 Crônicas, 36
// naa ?, NAA - Nova Almeida Atualizada

[[v14-36-1]]

^<<v14-36-1,1>>^ O povo da terra tomou Joacaz, filho de Josias, e o fez rei em lugar de seu pai, em Jerusalém.

[[v14-36-2]]

^<<v14-36-2,2>>^ Joacaz tinha vinte e três anos de idade quando começou a reinar e reinou três meses em Jerusalém.

[[v14-36-3]]

^<<v14-36-3,3>>^ Porém o rei do Egito o depôs em Jerusalém e impôs à terra um tributo de três mil e quatrocentos quilos de prata e trinta e quatro quilos de ouro.

[[v14-36-4]]

^<<v14-36-4,4>>^ O rei do Egito colocou Eliaquim, irmão de Joacaz, como rei sobre Judá e Jerusalém e mudou o nome dele para Jeoaquim. Mas Neco levou Joacaz, irmão de Eliaquim, para o Egito.

[[v14-36-5]]

^<<v14-36-5,5>>^ Jeoaquim tinha vinte e cinco anos de idade quando começou a reinar e reinou onze anos em Jerusalém. Fez o que era mau aos olhos do Senhor , seu Deus.

[[v14-36-6]]

^<<v14-36-6,6>>^ Nabucodonosor, rei da Babilônia, veio contra ele, amarrou-o com correntes de bronze, para levá-lo para a Babilônia.

[[v14-36-7]]

^<<v14-36-7,7>>^ Nabucodonosor levou também alguns dos utensílios da Casa do Senhor  para a Babilônia, onde os colocou no seu templo.

[[v14-36-8]]

^<<v14-36-8,8>>^ Quanto aos demais atos de Jeoaquim, às abominações que cometeu e ao mais que se achou nele, está tudo escrito no Livro da História dos Reis de Israel e de Judá. E Joaquim, seu filho, reinou em seu lugar.

[[v14-36-9]]

^<<v14-36-9,9>>^ Joaquim tinha dezoito anos de idade quando começou a reinar e reinou três meses e dez dias em Jerusalém. Joaquim fez o que era mau aos olhos do Senhor .

[[v14-36-10]]

^<<v14-36-10,10>>^ Na primavera do ano, o rei Nabucodonosor mandou levá-lo para a Babilônia, com os mais preciosos utensílios da Casa do Senhor . E constituiu Zedequias, irmão de Joaquim, rei sobre Judá e Jerusalém.

[[v14-36-11]]

^<<v14-36-11,11>>^ Zedequias tinha vinte e um anos de idade quando começou a reinar e reinou onze anos em Jerusalém.

[[v14-36-12]]

^<<v14-36-12,12>>^ Zedequias fez o que era mau aos olhos do Senhor , seu Deus, e não se humilhou diante do profeta Jeremias, que falava da parte do Senhor .

[[v14-36-13]]

^<<v14-36-13,13>>^ Também se rebelou contra o rei Nabucodonosor, que o tinha obrigado a jurar fidelidade em nome de Deus. Foi teimoso e tanto endureceu o seu coração, que não voltou ao Senhor , Deus de Israel.

[[v14-36-14]]

^<<v14-36-14,14>>^ Também todos os chefes dos sacerdotes e o povo aumentavam mais e mais as suas transgressões, segundo todas as abominações dos gentios. E contaminaram o templo que o Senhor  tinha santificado em Jerusalém.

[[v14-36-15]]

^<<v14-36-15,15>>^ O Senhor , Deus de seus pais, sempre de novo falou-lhes por meio dos seus mensageiros, porque teve compaixão do seu povo e da sua própria morada.

[[v14-36-16]]

^<<v14-36-16,16>>^ Mas eles zombaram dos mensageiros de Deus, desprezaram as palavras dele e debocharam dos seus profetas, até que a ira do Senhor  veio sobre o seu povo, e não houve mais remédio.

[[v14-36-17]]

^<<v14-36-17,17>>^ Por isso, o Senhor  trouxe contra eles o rei dos caldeus, que matou os seus jovens à espada, na casa do santuário deles. Não teve piedade nem dos jovens nem das moças, nem dos adultos nem dos velhos; entregou todos nas mãos do rei dos caldeus.

[[v14-36-18]]

^<<v14-36-18,18>>^ Todos os utensílios da Casa de Deus, grandes e pequenos, os tesouros da Casa do Senhor  e os tesouros do rei e dos seus príncipes, tudo ele levou para a Babilônia.

[[v14-36-19]]

^<<v14-36-19,19>>^ Os caldeus queimaram a Casa de Deus e derrubaram a muralha de Jerusalém. Queimaram todos os seus palácios, destruindo também todos os seus objetos de valor.

[[v14-36-20]]

^<<v14-36-20,20>>^ Os que escaparam da espada, a esses ele levou para a Babilônia, onde se tornaram escravos dele e de seus filhos, até o tempo do reino da Pérsia.

[[v14-36-21]]

^<<v14-36-21,21>>^ Isto aconteceu para que se cumprisse a palavra do Senhor , por boca de Jeremias, até que a terra desfrutasse dos seus sábados. Durante todos os dias da sua desolação a terra repousou, até que os setenta anos se cumpriram.

[[v14-36-22]]

^<<v14-36-22,22>>^ No primeiro ano do reinado de Ciro, rei da Pérsia, para que se cumprisse a palavra do Senhor , por boca de Jeremias, o Senhor  despertou o espírito de Ciro, rei da Pérsia, que ordenou que se proclamasse em todo o seu reino e que se pusesse por escrito o seguinte:

[[v14-36-23]]

^<<v14-36-23,23>>^ "Assim diz Ciro, rei da Pérsia: O Senhor , Deus dos céus, me deu todos os reinos da terra e me encarregou de lhe edificar um templo em Jerusalém, que fica em Judá. Aquele dentre vocês que for do seu povo, que suba a Jerusalém, e o Senhor , seu Deus, esteja com ele."

'''

xref:014-2-cronicas/014-2-cronicas-035.adoc#v14-35-0[&#60; Capítulo Anterior] | <<v14-36-0,Topo>> | xref:015-esdras/015-esdras-001.adoc#v15-1-0[Próximo Capítulo &#62;]