include::./index.adoc[]

[[v14-14-0]]
=== 2 Crônicas, 14
// naa ?, NAA - Nova Almeida Atualizada

[[v14-14-1]]

^<<v14-14-1,1>>^ Abias morreu, e eles o sepultaram na Cidade de Davi. E Asa, seu filho, reinou em seu lugar. Nos dias dele, a terra esteve em paz durante dez anos.

[[v14-14-2]]

^<<v14-14-2,2>>^ Asa fez o que era bom e reto aos olhos do Senhor , seu Deus.

[[v14-14-3]]

^<<v14-14-3,3>>^ Porque aboliu os altares dos deuses estranhos e o culto nos lugares altos, quebrou as colunas e cortou os postes da deusa Aserá.

[[v14-14-4]]

^<<v14-14-4,4>>^ Ordenou a Judá que buscasse o Senhor , Deus de seus pais, e que observasse a lei e o mandamento.

[[v14-14-5]]

^<<v14-14-5,5>>^ Também aboliu de todas as cidades de Judá o culto nos lugares altos e os altares do incenso. E houve paz no seu reinado.

[[v14-14-6]]

^<<v14-14-6,6>>^ Asa construiu cidades fortificadas em Judá, pois havia paz na terra, e não houve guerra contra ele naqueles anos, porque o Senhor  lhe tinha dado repouso.

[[v14-14-7]]

^<<v14-14-7,7>>^ Ele disse a Judá: — Vamos construir estas cidades, cercá-las de muralhas e torres, portões e ferrolhos, enquanto a terra ainda está em paz diante de nós, pois temos buscado o Senhor , nosso Deus. Nós o temos buscado, e ele nos deu repouso por todos os lados.

[[v14-14-8]]

^<<v14-14-8,8>>^ Então eles construíram e prosperaram. O rei Asa tinha um exército de trezentos mil homens de Judá, que traziam grandes escudos e lança, e duzentos e oitenta mil homens de Benjamim, que traziam escudo e atiravam com arco; todos eram homens valentes.

[[v14-14-9]]

^<<v14-14-9,9>>^ Zerá, o etíope, saiu contra eles com um exército de um milhão de homens e trezentos carros de guerra, e chegou até Maressa.

[[v14-14-10]]

^<<v14-14-10,10>>^ Então Asa saiu contra ele, e eles se prepararam para a batalha no vale de Zefatá, perto de Maressa.

[[v14-14-11]]

^<<v14-14-11,11>>^ Asa clamou ao Senhor , seu Deus, e disse: — Senhor , além de ti não há quem possa socorrer numa batalha entre o poderoso e o fraco. Ajuda-nos, Senhor , nosso Deus, porque em ti confiamos e no teu nome viemos contra esta multidão. Senhor , tu és o nosso Deus; que não prevaleça contra ti o homem.

[[v14-14-12]]

^<<v14-14-12,12>>^ O Senhor  derrotou os etíopes diante de Asa e diante de Judá; e eles fugiram.

[[v14-14-13]]

^<<v14-14-13,13>>^ Asa e o povo que estava com ele os perseguiram até Gerar, e os etíopes foram mortos, sem restar nem um sequer, porque foram destroçados diante do Senhor  e diante do seu exército; e eles levaram dali muitos despojos.

[[v14-14-14]]

^<<v14-14-14,14>>^ Atacaram todas as cidades ao redor de Gerar, porque o terror do Senhor  as havia invadido; e saquearam todas as cidades, porque nelas havia muitos despojos.

[[v14-14-15]]

^<<v14-14-15,15>>^ Também atacaram as tendas dos donos do gado, levaram ovelhas em abundância e camelos e voltaram para Jerusalém.

'''

xref:014-2-cronicas/014-2-cronicas-013.adoc#v14-13-0[&#60; Capítulo Anterior] | <<v14-14-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-015.adoc#v14-15-0[Próximo Capítulo &#62;]