include::./index.adoc[]

[[v14-22-0]]
=== 2 Crônicas, 22
// naa ?, NAA - Nova Almeida Atualizada

[[v14-22-1]]

^<<v14-22-1,1>>^ Em lugar de Jeorão, os moradores de Jerusalém fizeram rei a Acazias, o filho mais moço de Jeorão. Isso porque a tropa que tinha vindo com os árabes e invadido o arraial tinha matado todos os filhos mais velhos do rei. Assim Acazias, filho de Jeorão, rei de Judá, se tornou rei.

[[v14-22-2]]

^<<v14-22-2,2>>^ Acazias tinha vinte e dois anos de idade quando começou a reinar e reinou um ano em Jerusalém.

[[v14-22-3]]

^<<v14-22-3,3>>^ A mãe dele, que era filha de Onri, se chamava Atalia. Acazias também andou nos caminhos da casa de Acabe, porque a mãe dele o aconselhava a cometer iniquidades.

[[v14-22-4]]

^<<v14-22-4,4>>^ Fez o que era mau aos olhos do Senhor , como os da casa de Acabe, porque eles foram os seus conselheiros depois da morte de seu pai, para a sua perdição.

[[v14-22-5]]

^<<v14-22-5,5>>^ Também andou nos conselhos deles e foi com Jorão, filho de Acabe, rei de Israel, a Ramote-Gileade, para guerrear contra Hazael, rei da Síria; e os sírios feriram Jorão.

[[v14-22-6]]

^<<v14-22-6,6>>^ Então ele voltou para Jezreel, para curar-se das feridas que lhe fizeram em Ramá, quando lutou contra Hazael, rei da Síria. E Acazias, filho de Jeorão, rei de Judá, foi a Jezreel visitar Jorão, filho de Acabe, que estava doente.

[[v14-22-7]]

^<<v14-22-7,7>>^ Foi da vontade de Deus que Acazias, para a sua ruína, fosse visitar Jorão. Porque, quando chegou, saiu com Jorão para encontrar-se com Jeú, filho de Ninsi, a quem o Senhor  tinha ungido para exterminar a casa de Acabe.

[[v14-22-8]]

^<<v14-22-8,8>>^ Quando Jeú estava executando juízo contra a casa de Acabe, encontrou os príncipes de Judá e os filhos dos irmãos de Acazias, que estavam ao serviço do rei, e os matou.

[[v14-22-9]]

^<<v14-22-9,9>>^ Depois, mandou procurar Acazias e o encontrou em Samaria, onde se havia escondido. Eles o levaram a Jeú e o mataram. Então o sepultaram, porque disseram: — Ele é neto de Josafá, que buscou o Senhor  de todo o coração. E não havia mais ninguém na casa de Acazias que pudesse ser rei.

[[v14-22-10]]

^<<v14-22-10,10>>^ Quando Atalia, mãe de Acazias, viu que seu filho era morto, levantou-se e destruiu toda a descendência real da casa de Judá.

[[v14-22-11]]

^<<v14-22-11,11>>^ Mas Jeosabeate, filha do rei, raptou Joás, filho de Acazias, do meio dos filhos do rei que seriam mortos e o escondeu, juntamente com a sua babá, numa câmara interior. Assim Jeosabeate, a filha do rei Jeorão, mulher do sacerdote Joiada e irmã de Acazias, o escondeu de Atalia, e ele não foi morto.

[[v14-22-12]]

^<<v14-22-12,12>>^ Joás esteve com eles, escondido na Casa de Deus, durante seis anos; e Atalia reinava no país.

'''

xref:014-2-cronicas/014-2-cronicas-021.adoc#v14-21-0[&#60; Capítulo Anterior] | <<v14-22-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-023.adoc#v14-23-0[Próximo Capítulo &#62;]