include::./index.adoc[]

[[v14-25-0]]
=== 2 Crônicas, 25
// naa ?, NAA - Nova Almeida Atualizada

[[v14-25-1]]

^<<v14-25-1,1>>^ Amazias tinha vinte e cinco anos de idade quando começou a reinar e reinou vinte e nove anos em Jerusalém. A mãe dele se chamava Jeoadã e era de Jerusalém.

[[v14-25-2]]

^<<v14-25-2,2>>^ Amazias fez o que era reto aos olhos do Senhor , mas não com coração íntegro.

[[v14-25-3]]

^<<v14-25-3,3>>^ Logo que o reino foi confirmado nas suas mãos, matou os servos que tinham assassinado o rei, seu pai.

[[v14-25-4]]

^<<v14-25-4,4>>^ No entanto, não matou os filhos deles, mas fez segundo está escrito na Lei, no Livro de Moisés, no qual o Senhor  deu ordem, dizendo: "Os pais não serão mortos por causa dos filhos, nem os filhos serão mortos por causa dos pais; cada qual será morto pelo seu próprio pecado."

[[v14-25-5]]

^<<v14-25-5,5>>^ Amazias congregou os homens de Judá e os pôs, segundo as suas famílias, sob chefes de mil e chefes de cem, por todo o Judá e Benjamim. Contou os que tinham vinte anos de idade para cima e descobriu que havia trezentos mil homens escolhidos capazes de sair à guerra e manejar lança e escudo.

[[v14-25-6]]

^<<v14-25-6,6>>^ Também contratou cem mil homens valentes de Israel por três mil e quatrocentos quilos de prata.

[[v14-25-7]]

^<<v14-25-7,7>>^ Porém certo homem de Deus foi falar com Amazias e disse: — Ó rei, não deixe que o exército de Israel o acompanhe, porque o Senhor  não está com Israel, isto é, com nenhum dos filhos de Efraim.

[[v14-25-8]]

^<<v14-25-8,8>>^ Porém vá sozinho, entre em ação e seja corajoso. Do contrário, Deus faria com que você caísse diante do inimigo, porque Deus tem poder para dar a vitória ou a derrota.

[[v14-25-9]]

^<<v14-25-9,9>>^ Amazias perguntou ao homem de Deus: — E o que será dos três mil e quatrocentos quilos de prata que paguei às tropas de Israel? Ao que o homem de Deus respondeu: — O Senhor  pode lhe dar muito mais do que isso!

[[v14-25-10]]

^<<v14-25-10,10>>^ Então Amazias dispensou as tropas que tinham vindo de Efraim, dizendo que voltassem para casa. Eles ficaram muito irritados com o povo de Judá e voltaram para casa enfurecidos.

[[v14-25-11]]

^<<v14-25-11,11>>^ Amazias tomou coragem e, conduzindo o seu povo, foi até o vale do Sal, onde matou dez mil dos filhos de Seir.

[[v14-25-12]]

^<<v14-25-12,12>>^ Também os filhos de Judá prenderam vivos dez mil e os levaram até o alto de um penhasco, de onde os precipitaram, de modo que todos foram esmigalhados.

[[v14-25-13]]

^<<v14-25-13,13>>^ Porém os homens das tropas que Amazias tinha mandado embora, para que não fossem com ele à guerra, atacaram as cidades de Judá, desde Samaria até Bete-Horom. Mataram três mil e levaram muitos despojos.

[[v14-25-14]]

^<<v14-25-14,14>>^ Quando Amazias voltou da matança dos edomitas, trouxe consigo os deuses dos filhos de Seir, tomou-os por seus deuses, adorou-os e lhes queimou incenso.

[[v14-25-15]]

^<<v14-25-15,15>>^ Então o Senhor  ficou irado com Amazias e enviou-lhe um profeta que lhe disse: — Por que você está buscando deuses que não puderam livrar do seu ataque o povo deles?

[[v14-25-16]]

^<<v14-25-16,16>>^ Enquanto o profeta ainda falava, o rei lhe disse: — Por acaso pusemos você por conselheiro do rei? Pare com isso! Por que teríamos de matar você? Então o profeta parou, mas disse: — Sei que Deus resolveu destruí-lo, porque você fez isso e não deu ouvidos ao meu conselho.

[[v14-25-17]]

^<<v14-25-17,17>>^ Então Amazias, rei de Judá, tomou conselho e enviou mensageiros a Jeoás, filho de Jeoacaz, filho de Jeú, rei de Israel, dizendo: — Venha me enfrentar no campo de batalha.

[[v14-25-18]]

^<<v14-25-18,18>>^ Porém Jeoás, rei de Israel, respondeu a Amazias, rei de Judá: — O espinheiro que está no Líbano mandou dizer ao cedro que lá está: "Dê a sua filha por mulher ao meu filho." Mas um animal selvagem, que estava no Líbano, passou e pisoteou o espinheiro.

[[v14-25-19]]

^<<v14-25-19,19>>^ Você diz: "Eis que derrotei os edomitas", e o seu coração se encheu de orgulho, para você se gloriar. Agora fique em casa. Por que provocar um mal que trará somente desgraça para você e para Judá?

[[v14-25-20]]

^<<v14-25-20,20>>^ Mas Amazias não quis atendê-lo, porque isto vinha de Deus, para entregá-los nas mãos dos inimigos, porque buscaram os deuses dos edomitas.

[[v14-25-21]]

^<<v14-25-21,21>>^ Então Jeoás, rei de Israel, avançou contra Amazias, rei de Judá, e eles se enfrentaram em Bete-Semes, que está em Judá.

[[v14-25-22]]

^<<v14-25-22,22>>^ Judá foi derrotado por Israel, e os soldados tiveram de fugir para as suas casas.

[[v14-25-23]]

^<<v14-25-23,23>>^ Jeoás, rei de Israel, prendeu Amazias, rei de Judá, filho de Joás, filho de Jeoacaz, em Bete-Semes. Levou-o a Jerusalém, onde derrubou uma parte da muralha da cidade, desde o Portão de Efraim até o Portão da Esquina, numa extensão de mais ou menos duzentos metros.

[[v14-25-24]]

^<<v14-25-24,24>>^ Pegou todo o ouro e a prata, e todos os utensílios que havia na Casa de Deus, com Obede-Edom, e os tesouros do palácio real, bem como alguns reféns; e voltou para Samaria.

[[v14-25-25]]

^<<v14-25-25,25>>^ Amazias, filho de Joás, rei de Judá, viveu quinze anos depois da morte de Jeoás, filho de Jeoacaz, rei de Israel.

[[v14-25-26]]

^<<v14-25-26,26>>^ Quanto aos demais atos de Amazias, tanto os primeiros como os últimos, não está tudo escrito no Livro da História dos Reis de Judá e de Israel?

[[v14-25-27]]

^<<v14-25-27,27>>^ Depois que Amazias deixou de seguir o Senhor , conspiraram contra ele em Jerusalém, e ele fugiu para Laquis; porém enviaram homens atrás dele até Laquis e o mataram.

[[v14-25-28]]

^<<v14-25-28,28>>^ Trouxeram-no sobre cavalos e o sepultaram junto a seus pais, na Cidade de Davi.

'''

xref:014-2-cronicas/014-2-cronicas-024.adoc#v14-24-0[&#60; Capítulo Anterior] | <<v14-25-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-026.adoc#v14-26-0[Próximo Capítulo &#62;]