include::./index.adoc[]

[[v14-35-0]]
=== 2 Crônicas, 35
// naa ?, NAA - Nova Almeida Atualizada

[[v14-35-1]]

^<<v14-35-1,1>>^ Josias celebrou a Páscoa ao Senhor , em Jerusalém, e eles mataram os cordeiros da Páscoa no décimo quarto dia do primeiro mês.

[[v14-35-2]]

^<<v14-35-2,2>>^ Josias estabeleceu os sacerdotes nos seus cargos e os animou a servirem na Casa do Senhor .

[[v14-35-3]]

^<<v14-35-3,3>>^ Disse aos levitas que ensinavam a todo o Israel e estavam consagrados ao Senhor : — Ponham a arca sagrada no templo que Salomão, filho de Davi, rei de Israel, construiu. Vocês não precisam mais carregá-la nos ombros. Agora sirvam ao Senhor , o Deus de vocês, e ao seu povo de Israel.

[[v14-35-4]]

^<<v14-35-4,4>>^ Preparem-se segundo as suas famílias, segundo os turnos de vocês, segundo a prescrição de Davi, rei de Israel, e a de Salomão, seu filho.

[[v14-35-5]]

^<<v14-35-5,5>>^ Ministrem no santuário segundo os grupos das famílias de seus irmãos, os filhos do povo; e que haja, para cada grupo, uma parte das famílias dos levitas.

[[v14-35-6]]

^<<v14-35-6,6>>^ Matem os cordeiros da Páscoa, santifiquem-se e façam preparativos para que os seus irmãos comemorem a Páscoa segundo a palavra do Senhor , dada por meio de Moisés.

[[v14-35-7]]

^<<v14-35-7,7>>^ Josias deu ao povo, para todos os que ali estavam, trinta mil cordeiros e cabritos do rebanho, todos para os sacrifícios da Páscoa, além de três mil bois. Tudo isto foi tirado dos bens do rei.

[[v14-35-8]]

^<<v14-35-8,8>>^ Também os seus príncipes fizeram ofertas voluntárias ao povo, aos sacerdotes e aos levitas. Hilquias, Zacarias e Jeiel, chefes da Casa de Deus, deram aos sacerdotes, para os sacrifícios da Páscoa, dois mil e seiscentos cordeiros e cabritos e trezentos bois.

[[v14-35-9]]

^<<v14-35-9,9>>^ Conanias, os seus irmãos Semaías e Natanael, e também Hasabias, Jeiel e Jozabade, chefes dos levitas, apresentaram aos levitas, para os sacrifícios da Páscoa, cinco mil cordeiros e cabritos e quinhentos bois.

[[v14-35-10]]

^<<v14-35-10,10>>^ Assim se preparou o serviço, e os sacerdotes se puseram nos seus lugares com os levitas, pelos seus turnos, segundo a ordem do rei.

[[v14-35-11]]

^<<v14-35-11,11>>^ Então mataram os cordeiros da Páscoa, e os sacerdotes aspergiam o sangue recebido das mãos dos levitas que tiravam a pele dos animais.

[[v14-35-12]]

^<<v14-35-12,12>>^ Puseram de parte o que era para os holocaustos e o deram ao povo, segundo os grupos das famílias, para que estes o oferecessem ao Senhor , como está escrito no Livro de Moisés; e assim fizeram com os bois.

[[v14-35-13]]

^<<v14-35-13,13>>^ Assaram o cordeiro da Páscoa no fogo, segundo o rito. Cozinharam as ofertas sagradas em panelas, em caldeirões e em frigideiras, e as repartiram entre todo o povo.

[[v14-35-14]]

^<<v14-35-14,14>>^ Depois os levitas prepararam o que era deles e dos sacerdotes, porque os sacerdotes, filhos de Arão, se ocuparam, até a noite, com o sacrifício dos holocaustos e da gordura. Foi por isso que os levitas prepararam o que era deles e dos sacerdotes, filhos de Arão.

[[v14-35-15]]

^<<v14-35-15,15>>^ Os cantores, filhos de Asafe, estavam nos seus lugares, segundo o mandado de Davi, de Asafe, de Hemã e de Jedutum, vidente do rei. Também os porteiros estavam junto aos portões; não necessitaram abandonar o seu serviço, porque os seus irmãos, os levitas, preparavam o necessário para eles.

[[v14-35-16]]

^<<v14-35-16,16>>^ Assim se estabeleceu todo o serviço do Senhor , naquele dia, para celebrar a Páscoa e oferecer holocaustos sobre o altar do Senhor , segundo o mandado do rei Josias.

[[v14-35-17]]

^<<v14-35-17,17>>^ Os filhos de Israel que estavam presentes celebraram a Páscoa naquele tempo e a Festa dos Pães sem Fermento, durante sete dias.

[[v14-35-18]]

^<<v14-35-18,18>>^ Nunca se celebrou uma Páscoa como esta em Israel desde os dias do profeta Samuel. E nenhum dos reis de Israel celebrou uma Páscoa como esta que Josias celebrou com os sacerdotes e levitas, e com todo o Judá e Israel, que estavam ali, e com os moradores de Jerusalém.

[[v14-35-19]]

^<<v14-35-19,19>>^ Foi no décimo oitavo ano do reinado de Josias que foi celebrada esta Páscoa.

[[v14-35-20]]

^<<v14-35-20,20>>^ Depois de tudo isto, quando Josias já tinha restaurado o templo, o rei Neco, do Egito, subiu para guerrear em Carquemis, junto ao rio Eufrates. E Josias saiu para lutar contra ele.

[[v14-35-21]]

^<<v14-35-21,21>>^ Então Neco mandou mensageiros a ele, dizendo: — O que você tem contra mim, rei de Judá? Não venho contra você desta vez, mas contra o reino com o qual estou em guerra. E Deus disse que me apressasse. Pare de se opor a Deus, que está comigo, para que ele não o destrua.

[[v14-35-22]]

^<<v14-35-22,22>>^ Mas Josias não voltou atrás. Pelo contrário, se disfarçou para lutar contra ele. Não deu ouvidos às palavras que Neco lhe havia falado da parte de Deus e foi lutar no vale de Megido.

[[v14-35-23]]

^<<v14-35-23,23>>^ Os flecheiros atiraram contra o rei Josias. Então o rei disse aos seus servos: — Tirem-me daqui, porque estou gravemente ferido.

[[v14-35-24]]

^<<v14-35-24,24>>^ Seus servos o tiraram do carro de guerra, levaram-no para o segundo carro que ele tinha e o transportaram para Jerusalém. Ele morreu e foi sepultado nos túmulos de seus pais. Todo o Judá e Jerusalém prantearam Josias.

[[v14-35-25]]

^<<v14-35-25,25>>^ Jeremias compôs uma lamentação sobre Josias, e até o dia de hoje todos os cantores e cantoras, nas suas lamentações, se têm referido a Josias. Isto se tornou um costume em Israel, e essas lamentações estão escritas no Livro das Lamentações.

[[v14-35-26]]

^<<v14-35-26,26>>^ Quanto aos demais atos de Josias e às suas obras de misericórdia, segundo está escrito na Lei do Senhor ,

[[v14-35-27]]

^<<v14-35-27,27>>^ e aos seus atos, tanto os primeiros como os últimos, está tudo escrito no Livro da História dos Reis de Israel e de Judá.

'''

xref:014-2-cronicas/014-2-cronicas-034.adoc#v14-34-0[&#60; Capítulo Anterior] | <<v14-35-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-036.adoc#v14-36-0[Próximo Capítulo &#62;]