include::./index.adoc[]

[[v14-5-0]]
=== 2 Crônicas, 5
// naa ?, NAA - Nova Almeida Atualizada

[[v14-5-1]]

^<<v14-5-1,1>>^ Quando Salomão terminou toda a obra que fez para a Casa do Senhor , trouxe as coisas que Davi, seu pai, havia dedicado: a prata, o ouro e todos os utensílios. Salomão pôs tudo isso entre os tesouros da Casa de Deus.

[[v14-5-2]]

^<<v14-5-2,2>>^ Então Salomão congregou os anciãos de Israel e todos os chefes das tribos, os chefes das famílias dos israelitas, em Jerusalém, para levarem a arca da aliança do Senhor , da Cidade de Davi, que é Sião, para o templo.

[[v14-5-3]]

^<<v14-5-3,3>>^ Todos os homens de Israel se congregaram junto ao rei na ocasião da festa, que foi no sétimo mês.

[[v14-5-4]]

^<<v14-5-4,4>>^ Quando todos os anciãos de Israel chegaram, os levitas pegaram a arca do Senhor

[[v14-5-5]]

^<<v14-5-5,5>>^ e a levaram para cima, com a tenda do encontro e com os utensílios sagrados que nela havia; os levitas sacerdotes é que levaram tudo isso para o templo.

[[v14-5-6]]

^<<v14-5-6,6>>^ O rei Salomão e toda a congregação de Israel, que se havia reunido diante dele, estavam todos diante da arca, sacrificando ovelhas e bois, que, de tão numerosos, não se podiam contar.

[[v14-5-7]]

^<<v14-5-7,7>>^ Os sacerdotes puseram a arca da aliança do Senhor  no seu lugar, no santuário mais interior do templo, que é o Santo dos Santos, debaixo das asas dos querubins.

[[v14-5-8]]

^<<v14-5-8,8>>^ Pois os querubins estendiam as asas sobre o lugar da arca e, do alto, cobriam a arca e os seus cabos.

[[v14-5-9]]

^<<v14-5-9,9>>^ Os cabos sobressaíam tanto, que suas pontas eram vistas do Santo Lugar, diante do Santo dos Santos; porém de fora não podiam ser vistos.

[[v14-5-10]]

^<<v14-5-10,10>>^ E ali estão até o dia de hoje. Nada havia na arca a não ser as duas tábuas que Moisés havia colocado ali em Horebe, quando o Senhor  fez aliança com os filhos de Israel, ao saírem do Egito.

[[v14-5-11]]

^<<v14-5-11,11>>^ Quando os sacerdotes saíram do santuário — porque todos os sacerdotes, que estavam presentes, se santificaram, sem respeitarem os seus turnos —;

[[v14-5-12]]

^<<v14-5-12,12>>^ e quando todos os levitas que eram cantores, isto é, Asafe, Hemã, Jedutum e os filhos e irmãos deles, vestidos de linho fino, estavam em pé no lado leste do altar, com címbalos, harpas e liras, e com eles até cento e vinte sacerdotes, que tocavam as trombetas;

[[v14-5-13]]

^<<v14-5-13,13>>^ e quando em uníssono, ao mesmo tempo, tocaram as trombetas e cantaram para se fazerem ouvir, para louvar e dar graças ao Senhor ; e quando levantaram eles a voz com trombetas, címbalos e outros instrumentos musicais para louvarem o Senhor , porque ele é bom, porque a sua misericórdia dura para sempre, então o templo, a saber, a Casa do Senhor , se encheu de uma nuvem,

[[v14-5-14]]

^<<v14-5-14,14>>^ de maneira que os sacerdotes não puderam permanecer ali para ministrar, por causa da nuvem, porque a glória do Senhor  encheu a Casa de Deus.

'''

xref:014-2-cronicas/014-2-cronicas-004.adoc#v14-4-0[&#60; Capítulo Anterior] | <<v14-5-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-006.adoc#v14-6-0[Próximo Capítulo &#62;]