include::./index.adoc[]

[[v14-24-0]]
=== 2 Crônicas, 24
// naa ?, NAA - Nova Almeida Atualizada

[[v14-24-1]]

^<<v14-24-1,1>>^ Joás tinha sete anos de idade quando começou a reinar e reinou quarenta anos em Jerusalém.

[[v14-24-2]]

^<<v14-24-2,2>>^ A mãe dele se chamava Zíbia e era de Berseba. Joás fez o que era reto aos olhos do Senhor  todos os dias do sacerdote Joiada.

[[v14-24-3]]

^<<v14-24-3,3>>^ Joiada lhe deu duas mulheres, e ele gerou filhos e filhas.

[[v14-24-4]]

^<<v14-24-4,4>>^ Depois disto, Joás decidiu restaurar a Casa do Senhor .

[[v14-24-5]]

^<<v14-24-5,5>>^ Reuniu os sacerdotes e os levitas e lhes disse: — Vão pelas cidades de Judá e levantem de todo o Israel dinheiro para que todos os anos sejam feitos reparos no templo de seu Deus; e façam isso depressa. Porém os levitas não se apressaram.

[[v14-24-6]]

^<<v14-24-6,6>>^ Então o rei mandou chamar o sumo sacerdote Joiada e lhe perguntou: — Por que você não exigiu que os levitas trouxessem de Judá e de Jerusalém o imposto que Moisés, servo do Senhor , pôs sobre a congregação de Israel, para a tenda do testemunho?

[[v14-24-7]]

^<<v14-24-7,7>>^ Porque a perversa Atalia e os seus filhos tinham arruinado a Casa de Deus; e usaram todas as coisas sagradas da Casa do Senhor  no culto aos baalins.

[[v14-24-8]]

^<<v14-24-8,8>>^ O rei deu ordem e fizeram um cofre e o puseram do lado de fora, junto ao portão da Casa do Senhor .

[[v14-24-9]]

^<<v14-24-9,9>>^ Publicou-se, em Judá e em Jerusalém, que trouxessem ao Senhor  o imposto que Moisés, servo de Deus, havia colocado sobre Israel, no deserto.

[[v14-24-10]]

^<<v14-24-10,10>>^ Então todos os chefes e todo o povo se alegraram, trouxeram o imposto e o lançaram no cofre, até ficar cheio.

[[v14-24-11]]

^<<v14-24-11,11>>^ Quando o cofre era levado pelos levitas a uma comissão real, vendo-se que havia muito dinheiro, o escrivão do rei e o comissário do sumo sacerdote esvaziavam o cofre e o levavam de novo ao seu lugar. Assim faziam dia após dia e ajuntaram dinheiro em abundância.

[[v14-24-12]]

^<<v14-24-12,12>>^ O rei e Joiada entregavam esse dinheiro aos que dirigiam a obra e tinham a seu encargo a Casa do Senhor , que contrataram pedreiros e carpinteiros, para restaurarem a Casa do Senhor , e também os que trabalhavam em ferro e em bronze, para repararem a Casa do Senhor .

[[v14-24-13]]

^<<v14-24-13,13>>^ Os que estavam encarregados da obra trabalhavam, e a reparação tinha bom êxito com eles; restauraram a Casa de Deus no seu próprio estado e a consolidaram.

[[v14-24-14]]

^<<v14-24-14,14>>^ Quando acabaram a obra, trouxeram ao rei e a Joiada o resto do dinheiro, de que se fizeram utensílios para a Casa do Senhor , objetos para o culto e para os holocaustos, taças e outros objetos de ouro e de prata. E continuamente ofereceram holocaustos na Casa do Senhor , todos os dias de Joiada.

[[v14-24-15]]

^<<v14-24-15,15>>^ Joiada morreu após uma longa velhice; tinha cento e trinta anos de idade quando morreu.

[[v14-24-16]]

^<<v14-24-16,16>>^ Sepultaram-no na Cidade de Davi com os reis, porque ele tinha feito o bem em Israel e servido a Deus e ao seu templo.

[[v14-24-17]]

^<<v14-24-17,17>>^ Depois da morte de Joiada, os chefes de Judá foram e se prostraram diante do rei, e o rei os ouviu.

[[v14-24-18]]

^<<v14-24-18,18>>^ Então abandonaram a Casa do Senhor , Deus de seus pais, e serviram os postes da deusa Aserá e aos ídolos. E, por esta sua culpa, veio grande ira sobre Judá e Jerusalém.

[[v14-24-19]]

^<<v14-24-19,19>>^ Mas o Senhor  lhes enviou profetas para os reconduzir a si; estes profetas testemunharam contra eles, mas eles não quiseram ouvir.

[[v14-24-20]]

^<<v14-24-20,20>>^ Então o Espírito de Deus se apoderou de Zacarias, filho do sacerdote Joiada. Ele ficou em pé diante do povo e lhes disse: — Assim diz Deus: "Por que vocês estão transgredindo os mandamentos do Senhor ? Vocês não vão prosperar! Por terem abandonado o Senhor , também ele os abandonará."

[[v14-24-21]]

^<<v14-24-21,21>>^ Conspiraram contra ele e o apedrejaram, por ordem do rei, no pátio da Casa do Senhor .

[[v14-24-22]]

^<<v14-24-22,22>>^ Assim, o rei Joás não se lembrou de como Joiada, pai de Zacarias, tinha sido bondoso com ele, e acabou matando o filho dele. Ao morrer, Zacarias disse: — O Senhor  verá isto e o retribuirá.

[[v14-24-23]]

^<<v14-24-23,23>>^ Antes de se findar o ano, o exército dos sírios atacou Joás. Invadiram Judá e Jerusalém, mataram todos os chefes do povo, e levaram os despojos ao rei de Damasco.

[[v14-24-24]]

^<<v14-24-24,24>>^ Embora o exército dos sírios não fosse grande, o Senhor  permitiu que eles vencessem um exército que era muito maior, porque eles tinham abandonado o Senhor , Deus de seus pais. Assim os sírios executaram o juízo de Deus contra Joás.

[[v14-24-25]]

^<<v14-24-25,25>>^ Quando os sírios foram embora, deixando Joás gravemente ferido, os servos de Joás conspiraram contra ele, por causa do sangue do filho do sacerdote Joiada, e o mataram em sua cama.

[[v14-24-26]]

^<<v14-24-26,26>>^ Ele foi sepultado na Cidade de Davi, mas não nos túmulos dos reis. Os que conspiraram contra Joás foram Zabade, filho de Simeate, a amonita, e Jeozabade, filho de Sinrite, a moabita.

[[v14-24-27]]

^<<v14-24-27,27>>^ Quanto aos filhos de Joás, às numerosas sentenças proferidas contra ele e à restauração da Casa de Deus, está tudo escrito no Livro da História dos Reis. E Amazias, filho de Joás, reinou em seu lugar.

'''

xref:014-2-cronicas/014-2-cronicas-023.adoc#v14-23-0[&#60; Capítulo Anterior] | <<v14-24-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-025.adoc#v14-25-0[Próximo Capítulo &#62;]