include::./index.adoc[]

[[v14-20-0]]
=== 2 Crônicas, 20
// naa ?, NAA - Nova Almeida Atualizada

[[v14-20-1]]

^<<v14-20-1,1>>^ Depois disto, os filhos de Moabe e os filhos de Amom, com alguns dos meunitas, vieram para fazer guerra contra Josafá.

[[v14-20-2]]

^<<v14-20-2,2>>^ Então vieram alguns que avisaram Josafá, dizendo: — Uma grande multidão está vindo contra Judá, do outro lado do mar Morto, da Síria. Eis que eles já estão em Hazazom-Tamar, que é En-Gedi.

[[v14-20-3]]

^<<v14-20-3,3>>^ Então Josafá teve medo e decidiu buscar o Senhor ; e proclamou um jejum em todo o Judá.

[[v14-20-4]]

^<<v14-20-4,4>>^ Judá se congregou para pedir socorro ao Senhor . Também de todas as cidades de Judá veio gente para buscar o Senhor .

[[v14-20-5]]

^<<v14-20-5,5>>^ Josafá pôs-se em pé, na congregação de Judá e de Jerusalém, na Casa do Senhor , diante do pátio novo,

[[v14-20-6]]

^<<v14-20-6,6>>^ e disse: — Ó Senhor , Deus de nossos pais, não és tu Deus nos céus? Não és tu que dominas sobre todos os reinos dos povos? Na tua mão está a força e o poder, e não há quem te possa resistir.

[[v14-20-7]]

^<<v14-20-7,7>>^ Ó nosso Deus, acaso não expulsaste os moradores desta terra de diante do teu povo de Israel e não a deste para sempre à posteridade de Abraão, teu amigo?

[[v14-20-8]]

^<<v14-20-8,8>>^ Eles têm morado nela e nela edificaram um santuário ao teu nome, dizendo:

[[v14-20-9]]

^<<v14-20-9,9>>^ "Se algum mal nos sobrevier, espada, juízo, peste ou fome, nós nos apresentaremos diante deste templo e diante de ti, pois o teu nome está neste templo; e clamaremos a ti na nossa angústia, tu nos ouvirás e livrarás."

[[v14-20-10]]

^<<v14-20-10,10>>^ E agora eis que os filhos de Amom e de Moabe e os do monte Seir, cujas terras não permitiste a Israel invadir, quando vinham da terra do Egito, mas deles se desviaram e não os destruíram,

[[v14-20-11]]

^<<v14-20-11,11>>^ eis que eles estão nos recompensando assim: estão vindo para nos expulsar da tua propriedade, que nos deste em herança.

[[v14-20-12]]

^<<v14-20-12,12>>^ Ó nosso Deus, acaso não executarás o teu juízo contra eles? Porque em nós não há força para resistirmos a essa grande multidão que vem contra nós. Não sabemos o que fazer, mas os nossos olhos estão postos em ti.

[[v14-20-13]]

^<<v14-20-13,13>>^ Todos os homens de Judá estavam em pé diante do Senhor , com as suas crianças, as suas mulheres e os seus filhos.

[[v14-20-14]]

^<<v14-20-14,14>>^ Então, no meio da congregação, o Espírito do Senhor  veio sobre Jaaziel, filho de Zacarias, filho de Benaia, filho de Jeiel, filho de Matanias, levita, dos filhos de Asafe.

[[v14-20-15]]

^<<v14-20-15,15>>^ Jaaziel disse: — Escutem com atenção, todo o Judá, moradores de Jerusalém e rei Josafá! Assim diz o Senhor : "Não tenham medo nem se assustem por causa desta grande multidão, pois esta batalha não é de vocês, mas de Deus.

[[v14-20-16]]

^<<v14-20-16,16>>^ Amanhã vocês irão ao encontro deles. Eis que eles virão pela ladeira de Ziz, e vocês os encontrarão no fim do vale, em frente do deserto de Jeruel.

[[v14-20-17]]

^<<v14-20-17,17>>^ Neste encontro, vocês não precisarão lutar. Tomem posição, fiquem parados e vejam a salvação que o Senhor  lhes dará, ó Judá e Jerusalém. Não tenham medo nem se assustem. Amanhã, saiam ao encontro deles, porque o Senhor  está com vocês."

[[v14-20-18]]

^<<v14-20-18,18>>^ Então Josafá se prostrou com o rosto em terra, e todo o Judá e os moradores de Jerusalém também se prostraram diante do Senhor  e o adoraram.

[[v14-20-19]]

^<<v14-20-19,19>>^ Os levitas dos filhos dos coatitas e dos coraítas se levantaram para louvar o Senhor , Deus de Israel, em voz bem alta.

[[v14-20-20]]

^<<v14-20-20,20>>^ Na manhã seguinte, levantaram cedo e foram para o deserto de Tecoa. Ao saírem, Josafá se pôs em pé e disse: — Escutem, povo de Judá e moradores de Jerusalém! Creiam no Senhor , seu Deus, e vocês estarão seguros; creiam nos profetas do Senhor  e vocês serão bem-sucedidos.

[[v14-20-21]]

^<<v14-20-21,21>>^ Depois de se aconselhar com o povo, Josafá designou os que deveriam cantar ao Senhor . Vestidos de ornamentos sagrados e marchando à frente do exército, deveriam louvar a Deus, dizendo: "Deem graças ao Senhor , porque a sua misericórdia dura para sempre."

[[v14-20-22]]

^<<v14-20-22,22>>^ No momento em que eles começaram a cantar e a dar louvores, o Senhor  pôs emboscadas contra os filhos de Amom e de Moabe e os do monte Seir que vieram contra Judá, e foram derrotados.

[[v14-20-23]]

^<<v14-20-23,23>>^ Porque os filhos de Amom e de Moabe se levantaram contra os moradores do monte Seir, para os destruir e exterminar. E, quando eles tinham acabado com os moradores de Seir, atacaram e destruíram-se uns aos outros.

[[v14-20-24]]

^<<v14-20-24,24>>^ Quando os homens de Judá chegaram a um lugar alto de onde se pode olhar para o deserto, procuraram ver a multidão, e eis que somente avistaram cadáveres estendidos no chão; não havia nenhum sobrevivente.

[[v14-20-25]]

^<<v14-20-25,25>>^ Josafá e o seu povo foram saquear os despojos e acharam entre os cadáveres riquezas em abundância e objetos preciosos. Pegaram para si mais do que podiam levar e gastaram três dias para saquear o despojo, de tanto que havia.

[[v14-20-26]]

^<<v14-20-26,26>>^ No quarto dia eles se reuniram no vale de Beraca, onde louvaram o Senhor . Por isso, aquele lugar é chamado de vale de Beraca até o dia de hoje.

[[v14-20-27]]

^<<v14-20-27,27>>^ Então todos os homens de Judá e de Jerusalém voltaram, com Josafá à frente deles. Voltaram para Jerusalém com alegria, porque o Senhor  lhes tinha dado uma grande alegria com a vitória sobre os seus inimigos.

[[v14-20-28]]

^<<v14-20-28,28>>^ Entraram em Jerusalém ao som de liras, harpas e trombetas, e foram para a Casa do Senhor .

[[v14-20-29]]

^<<v14-20-29,29>>^ O terror da parte de Deus veio sobre todos os reinos daquelas terras, quando ouviram que o Senhor  havia lutado contra os inimigos de Israel.

[[v14-20-30]]

^<<v14-20-30,30>>^ Assim, o reino de Josafá teve paz, porque Deus lhe deu repouso por todos os lados.

[[v14-20-31]]

^<<v14-20-31,31>>^ Josafá reinou sobre Judá. Ele tinha trinta e cinco anos de idade quando começou a reinar e reinou vinte e cinco anos em Jerusalém. A mãe dele se chamava Azuba e era filha de Sili.

[[v14-20-32]]

^<<v14-20-32,32>>^ Ele andou no caminho de Asa, seu pai; não se desviou dele e fez o que era reto aos olhos do Senhor .

[[v14-20-33]]

^<<v14-20-33,33>>^ Os lugares altos, porém, não foram destruídos; porque o povo ainda não tinha disposto o coração para com o Deus de seus pais.

[[v14-20-34]]

^<<v14-20-34,34>>^ Quanto aos demais atos de Josafá, tanto os primeiros como os últimos, está tudo escrito nas Crônicas de Jeú, filho de Hanani, que as inseriu na História dos Reis de Israel.

[[v14-20-35]]

^<<v14-20-35,35>>^ Depois disto, Josafá, rei de Judá, se aliou com Acazias, rei de Israel, cuja conduta era ímpia.

[[v14-20-36]]

^<<v14-20-36,36>>^ Aliou-se com ele, para construir navios que fossem a Társis; os navios foram construídos em Eziom-Geber.

[[v14-20-37]]

^<<v14-20-37,37>>^ Então Eliézer, filho de Dodavá, de Maressa, profetizou contra Josafá, dizendo: — Porque você se aliou com Acazias, o Senhor  destruirá o que você construiu. E os navios se quebraram e não puderam ir a Társis.

'''

xref:014-2-cronicas/014-2-cronicas-019.adoc#v14-19-0[&#60; Capítulo Anterior] | <<v14-20-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-021.adoc#v14-21-0[Próximo Capítulo &#62;]