include::./index.adoc[]

[[v14-23-0]]
=== 2 Crônicas, 23
// naa ?, NAA - Nova Almeida Atualizada

[[v14-23-1]]

^<<v14-23-1,1>>^ No sétimo ano, o sacerdote Joiada se animou e entrou em aliança com os capitães de cem: Azarias, filho de Jeroão, Ismael, filho de Joanã, Azarias, filho de Obede, Maaseias, filho de Adaías, e Elisafate, filho de Zicri.

[[v14-23-2]]

^<<v14-23-2,2>>^ Estes percorreram Judá, congregaram os levitas de todas as cidades de Judá e os chefes das famílias de Israel e vieram para Jerusalém.

[[v14-23-3]]

^<<v14-23-3,3>>^ Toda essa congregação fez aliança com o rei na Casa de Deus. Então Joiada lhes disse: — Eis que o filho do rei deve reinar, como o Senhor  Deus falou a respeito dos filhos de Davi.

[[v14-23-4]]

^<<v14-23-4,4>>^ Isto é o que vocês devem fazer: uma terça parte de vocês, sacerdotes e levitas, que entram de serviço no sábado, servirá de guarda dos portões do templo;

[[v14-23-5]]

^<<v14-23-5,5>>^ outra terça parte estará no palácio real; e a outra terça parte, no Portão do Fundamento; e todo o povo estará nos pátios da Casa do Senhor .

[[v14-23-6]]

^<<v14-23-6,6>>^ Que ninguém entre na Casa do Senhor , a não ser os sacerdotes e os levitas que ministram. Estes poderão entrar, porque são santos, mas todo o povo guardará o preceito do Senhor .

[[v14-23-7]]

^<<v14-23-7,7>>^ Os levitas devem rodear o rei, cada um de armas na mão. E, se alguém quiser entrar no templo, que seja morto. Vocês devem acompanhar o rei aonde quer que ele for.

[[v14-23-8]]

^<<v14-23-8,8>>^ Os levitas e todo o Judá fizeram tudo o que o sacerdote Joiada lhes havia ordenado. Cada um reuniu os seus soldados, tanto os que entravam de serviço no sábado como os que saíam de serviço no sábado, porque o sacerdote Joiada não havia dispensado nenhuma das turmas.

[[v14-23-9]]

^<<v14-23-9,9>>^ O sacerdote Joiada entregou aos capitães de cem as lanças, os escudos e os escudos menores que haviam sido do rei Davi e que estavam na Casa de Deus.

[[v14-23-10]]

^<<v14-23-10,10>>^ Dispôs todo o povo, cada um de armas na mão, desde o lado direito do templo até o seu lado esquerdo, e até o altar, e até o templo, para rodear o rei.

[[v14-23-11]]

^<<v14-23-11,11>>^ Então trouxeram para fora o filho do rei, puseram a coroa na cabeça dele, entregaram-lhe o Livro do Testemunho e o constituíram rei. Joiada e seus filhos o ungiram e gritaram: — Viva o rei!

[[v14-23-12]]

^<<v14-23-12,12>>^ Quando a rainha Atalia ouviu o barulho do povo que corria e louvava o rei, veio para onde o povo estava, na Casa do Senhor .

[[v14-23-13]]

^<<v14-23-13,13>>^ Olhou, e eis que o rei estava junto à coluna, à entrada. Os capitães e os tocadores de trombetas estavam ao lado do rei, e todo o povo da terra se alegrava e tocava trombetas. Também os cantores com os instrumentos musicais dirigiam o canto de louvores. Então Atalia rasgou as suas roupas e gritou: — Traição! Traição!

[[v14-23-14]]

^<<v14-23-14,14>>^ Porém o sacerdote Joiada trouxe para fora os capitães que comandavam as tropas e disse-lhes: — Façam-na sair por entre as fileiras e, se alguém a seguir, matem-no à espada. Porque o sacerdote tinha dito: "Não a matem na Casa do Senhor ."

[[v14-23-15]]

^<<v14-23-15,15>>^ Então eles a prenderam; e ela, pelo caminho da entrada dos cavalos, foi para o palácio real, onde a mataram.

[[v14-23-16]]

^<<v14-23-16,16>>^ Joiada fez uma aliança entre si mesmo, todo o povo e o rei, para serem eles o povo do Senhor .

[[v14-23-17]]

^<<v14-23-17,17>>^ Então todo o povo entrou no templo de Baal e o derrubaram, despedaçando os altares e as imagens de Baal. Matã, o sacerdote de Baal, foi morto diante dos altares.

[[v14-23-18]]

^<<v14-23-18,18>>^ Joiada entregou a superintendência da Casa do Senhor  nas mãos dos sacerdotes levitas, que Davi tinha organizado em grupos para cuidarem da Casa do Senhor , para oferecerem os holocaustos do Senhor , como está escrito na Lei de Moisés, com alegria e com canto, segundo a instituição de Davi.

[[v14-23-19]]

^<<v14-23-19,19>>^ Colocou porteiros junto aos portões da Casa do Senhor , para que nela não entrasse ninguém que de alguma forma fosse impuro.

[[v14-23-20]]

^<<v14-23-20,20>>^ Reuniu os capitães de cem, os nobres, os governadores do povo e todo o povo da terra, e todos estes conduziram o rei da Casa do Senhor  até o palácio real, passando pelo portão superior. E assentaram Joás no trono do reino.

[[v14-23-21]]

^<<v14-23-21,21>>^ Todo o povo da terra se alegrou, e a cidade ficou tranquila, depois que mataram Atalia à espada.

'''

xref:014-2-cronicas/014-2-cronicas-022.adoc#v14-22-0[&#60; Capítulo Anterior] | <<v14-23-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-024.adoc#v14-24-0[Próximo Capítulo &#62;]