include::./index.adoc[]

[[v14-29-0]]
=== 2 Crônicas, 29
// naa ?, NAA - Nova Almeida Atualizada

[[v14-29-1]]

^<<v14-29-1,1>>^ Ezequias tinha vinte e cinco anos de idade quando começou a reinar e reinou vinte e nove anos em Jerusalém. A mãe dele se chamava Abia e era filha de Zacarias.

[[v14-29-2]]

^<<v14-29-2,2>>^ Ezequias fez o que era reto aos olhos do Senhor , segundo tudo o que Davi, seu pai, havia feito.

[[v14-29-3]]

^<<v14-29-3,3>>^ No primeiro ano do seu reinado, no primeiro mês, abriu os portões da Casa do Senhor  e os reparou.

[[v14-29-4]]

^<<v14-29-4,4>>^ Trouxe os sacerdotes e os levitas, reuniu-os na praça leste

[[v14-29-5]]

^<<v14-29-5,5>>^ e lhes disse: — Escutem, levitas! Santifiquem agora a si mesmos e santifiquem a Casa do Senhor , Deus de seus pais. Tirem do santuário tudo o que é impuro.

[[v14-29-6]]

^<<v14-29-6,6>>^ Porque nossos pais foram infiéis e fizeram o que era mau aos olhos do Senhor , nosso Deus, e o abandonaram. Desviaram o seu rosto do tabernáculo do Senhor  e lhe viraram as costas.

[[v14-29-7]]

^<<v14-29-7,7>>^ Também fecharam os portões do pórtico, apagaram as lâmpadas, não queimaram incenso, nem ofereceram holocaustos no santuário ao Deus de Israel.

[[v14-29-8]]

^<<v14-29-8,8>>^ Por isso a ira do Senhor  veio sobre Judá e Jerusalém, e ele os transformou em objeto de espanto, de horror e de vaias, como vocês estão vendo com os seus próprios olhos.

[[v14-29-9]]

^<<v14-29-9,9>>^ Porque eis que os nossos pais caíram à espada, e, por isso, os nossos filhos, as nossas filhas e as nossas mulheres foram para o cativeiro.

[[v14-29-10]]

^<<v14-29-10,10>>^ — Agora estou resolvido a fazer uma aliança com o Senhor , Deus de Israel, para que o furor da sua ira se afaste de nós.

[[v14-29-11]]

^<<v14-29-11,11>>^ Meus filhos, não sejam negligentes, pois o Senhor  os escolheu para estarem diante dele para o servirem, para serem os seus ministros e queimarem incenso.

[[v14-29-12]]

^<<v14-29-12,12>>^ Então se levantaram os seguintes levitas: Maate, filho de Amasai, e Joel, filho de Azarias, dos filhos dos coatitas; Quis, filho de Abdi, e Azarias, filho de Jealelel, dos filhos de Merari; Joá, filho de Zima, e Éden, filho de Joá, dos filhos de Gérson;

[[v14-29-13]]

^<<v14-29-13,13>>^ Sinri e Jeuel, dos filhos de Elisafã; Zacarias e Matanias, dos filhos de Asafe;

[[v14-29-14]]

^<<v14-29-14,14>>^ Jeuel e Simei, dos filhos de Hemã; Semaías e Uziel, dos filhos de Jedutum.

[[v14-29-15]]

^<<v14-29-15,15>>^ Congregaram os seus irmãos, santificaram-se e vieram, cumprindo a ordem do rei, segundo as palavras do Senhor , para purificar a Casa do Senhor .

[[v14-29-16]]

^<<v14-29-16,16>>^ Os sacerdotes entraram na Casa do Senhor , para a purificar, e tiraram para fora, ao pátio da Casa do Senhor , todas as coisas impuras que encontraram no templo do Senhor . E os levitas pegaram essas coisas e as levaram para fora, ao vale do Cedrom.

[[v14-29-17]]

^<<v14-29-17,17>>^ Começaram a santificar no primeiro dia do primeiro mês e no oitavo dia do mês chegaram ao pórtico do Senhor . Em oito dias santificaram a Casa do Senhor  e no décimo sexto dia do mês terminaram.

[[v14-29-18]]

^<<v14-29-18,18>>^ Então foram falar com o rei Ezequias no palácio e disseram: — Já purificamos toda a Casa do Senhor , bem como o altar do holocausto com todos os seus utensílios e a mesa da proposição com todos os seus objetos.

[[v14-29-19]]

^<<v14-29-19,19>>^ Também todos os objetos que o rei Acaz, em sua infidelidade, jogou fora durante o seu reinado, nós já preparamos e santificamos; e eis que estão diante do altar do Senhor .

[[v14-29-20]]

^<<v14-29-20,20>>^ Então o rei Ezequias se levantou de madrugada, reuniu os chefes da cidade e subiu à Casa do Senhor .

[[v14-29-21]]

^<<v14-29-21,21>>^ Mandou trazer sete novilhos, sete carneiros, sete cordeiros e sete bodes, como oferta pelo pecado a favor do reino, do santuário e de Judá; e ordenou aos filhos de Arão, os sacerdotes, que os oferecessem sobre o altar do Senhor .

[[v14-29-22]]

^<<v14-29-22,22>>^ Mortos os novilhos, os sacerdotes pegaram o sangue e o aspergiram sobre o altar; mataram os carneiros e aspergiram o sangue sobre o altar; também mataram os cordeiros e aspergiram o sangue sobre o altar.

[[v14-29-23]]

^<<v14-29-23,23>>^ Para oferta pelo pecado, trouxeram os bodes diante do rei e da congregação, e estes puseram as mãos sobre eles.

[[v14-29-24]]

^<<v14-29-24,24>>^ Os sacerdotes os mataram e, com o sangue, fizeram uma oferta pelo pecado, ao pé do altar, para expiação de todo o Israel, porque o rei havia ordenado que se fizesse aquele holocausto e oferta pelo pecado, por todo o Israel.

[[v14-29-25]]

^<<v14-29-25,25>>^ Também pôs os levitas na Casa do Senhor  com címbalos, liras e harpas, segundo o mandado de Davi e de Gade, o vidente do rei, e do profeta Natã. Porque este mandado veio do Senhor , por meio de seus profetas.

[[v14-29-26]]

^<<v14-29-26,26>>^ Os levitas estavam em pé com os instrumentos musicais de Davi, e os sacerdotes tinham as trombetas.

[[v14-29-27]]

^<<v14-29-27,27>>^ Ezequias ordenou que oferecessem o holocausto sobre o altar. No momento em que começou o holocausto, começou também o cântico ao Senhor  com as trombetas, ao som dos instrumentos musicais de Davi, rei de Israel.

[[v14-29-28]]

^<<v14-29-28,28>>^ Toda a congregação se prostrou, quando se entoava o cântico, e as trombetas soavam; tudo isto até findar-se o holocausto.

[[v14-29-29]]

^<<v14-29-29,29>>^ Depois que eles terminaram de oferecer o sacrifício, o rei e todos os que estavam com ele se prostraram e adoraram.

[[v14-29-30]]

^<<v14-29-30,30>>^ Então o rei Ezequias e os chefes ordenaram aos levitas que louvassem o Senhor  com as palavras de Davi e de Asafe, o vidente. Eles o fizeram com alegria, e se inclinaram, e adoraram.

[[v14-29-31]]

^<<v14-29-31,31>>^ Ezequias tomou a palavra e disse: — Agora vocês se consagraram ao Senhor . Venham e tragam sacrifícios e ofertas de ação de graças à Casa do Senhor . A congregação trouxe sacrifícios e ofertas de ação de graças, e todos os que estavam de coração disposto trouxeram holocaustos.

[[v14-29-32]]

^<<v14-29-32,32>>^ O número dos holocaustos que a congregação trouxe foi de setenta bois, cem carneiros e duzentos cordeiros; tudo isto em holocausto para o Senhor .

[[v14-29-33]]

^<<v14-29-33,33>>^ Também foram consagrados seiscentos bois e três mil ovelhas.

[[v14-29-34]]

^<<v14-29-34,34>>^ Os sacerdotes, porém, eram muito poucos e não conseguiam tirar a pele de todos os holocaustos. Por isso os seus irmãos, os levitas, os ajudaram, até findar-se a obra e até que os outros sacerdotes se santificaram. Porque os levitas foram mais retos de coração, para se santificarem, do que os sacerdotes.

[[v14-29-35]]

^<<v14-29-35,35>>^ Além dos holocaustos em abundância, houve também a gordura das ofertas pacíficas e as libações para os holocaustos. Assim se restabeleceu o ministério da Casa do Senhor .

[[v14-29-36]]

^<<v14-29-36,36>>^ Ezequias e todo o povo se alegraram com o que Deus tinha feito pelo povo, porque esta obra foi feita em pouco tempo.

'''

xref:014-2-cronicas/014-2-cronicas-028.adoc#v14-28-0[&#60; Capítulo Anterior] | <<v14-29-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-030.adoc#v14-30-0[Próximo Capítulo &#62;]