include::./index.adoc[]

[[v14-33-0]]
=== 2 Crônicas, 33
// naa ?, NAA - Nova Almeida Atualizada

[[v14-33-1]]

^<<v14-33-1,1>>^ Manassés tinha doze anos de idade quando começou a reinar e reinou cinquenta e cinco anos em Jerusalém.

[[v14-33-2]]

^<<v14-33-2,2>>^ Fez o que era mau aos olhos do Senhor , segundo as coisas abomináveis das nações que o Senhor  havia expulsado de diante dos filhos de Israel.

[[v14-33-3]]

^<<v14-33-3,3>>^ Pois reconstruiu os lugares altos que Ezequias, seu pai, havia derrubado, levantou altares aos baalins, fez postes da deusa Aserá, prostrou-se diante de todo o exército dos céus e o serviu.

[[v14-33-4]]

^<<v14-33-4,4>>^ Edificou altares na Casa do Senhor , a respeito da qual o Senhor  tinha dito: "Em Jerusalém porei o meu nome para sempre."

[[v14-33-5]]

^<<v14-33-5,5>>^ Também edificou altares a todo o exército dos céus nos dois átrios da Casa do Senhor .

[[v14-33-6]]

^<<v14-33-6,6>>^ Ele queimou os seus filhos em sacrifício no vale de Ben-Hinom, adivinhava pelas nuvens, era agoureiro, praticava feitiçarias e tratava com médiuns e feiticeiros. Fazia continuamente o que era mau aos olhos do Senhor , para o provocar à ira.

[[v14-33-7]]

^<<v14-33-7,7>>^ Também pôs a imagem de escultura do ídolo que tinha feito na Casa de Deus, a respeito da qual Deus tinha dito a Davi e a seu filho Salomão: "Neste templo e em Jerusalém, que escolhi de todas as tribos de Israel, porei o meu nome para sempre.

[[v14-33-8]]

^<<v14-33-8,8>>^ E não removerei mais o pé de Israel da terra que destinei aos seus pais, desde que eles tenham o cuidado de fazer tudo o que lhes tenho mandado, conforme toda a lei, os estatutos e os juízos dados por meio de Moisés."

[[v14-33-9]]

^<<v14-33-9,9>>^ Manassés de tal modo levou o povo de Judá e os moradores de Jerusalém a andarem errantes, que fizeram pior do que as nações que o Senhor  tinha destruído de diante dos filhos de Israel.

[[v14-33-10]]

^<<v14-33-10,10>>^ O Senhor  falou a Manassés e ao seu povo, porém não lhe deram ouvidos.

[[v14-33-11]]

^<<v14-33-11,11>>^ Por isso o Senhor  trouxe sobre eles os comandantes do exército do rei da Assíria, que prenderam Manassés com ganchos, amarraram-no com correntes e o levaram para a Babilônia.

[[v14-33-12]]

^<<v14-33-12,12>>^ Ele, angustiado, suplicou ao Senhor , seu Deus, e muito se humilhou diante do Deus de seus pais.

[[v14-33-13]]

^<<v14-33-13,13>>^ Orou ao Senhor , e o Senhor  se tornou favorável para com ele, atendeu-lhe a súplica e o fez voltar para Jerusalém, ao seu reino. Então Manassés reconheceu que o Senhor  é Deus.

[[v14-33-14]]

^<<v14-33-14,14>>^ Depois disto, Manassés construiu a muralha de fora da Cidade de Davi, a oeste de Giom, no vale, e à entrada do Portão dos Peixes, abrangendo Ofel; ele fez uma muralha bem alta. Também pôs chefes militares em todas as cidades fortificadas de Judá.

[[v14-33-15]]

^<<v14-33-15,15>>^ Tirou da Casa do Senhor  os deuses estranhos e o ídolo, bem como todos os altares que havia construído no monte da Casa do Senhor  e em Jerusalém, e os lançou fora da cidade.

[[v14-33-16]]

^<<v14-33-16,16>>^ Restaurou o altar do Senhor , sacrificou sobre ele ofertas pacíficas e de ação de graças e ordenou a Judá que servisse o Senhor , Deus de Israel.

[[v14-33-17]]

^<<v14-33-17,17>>^ Porém o povo ainda sacrificava nos lugares altos, mas somente ao Senhor , seu Deus.

[[v14-33-18]]

^<<v14-33-18,18>>^ Quanto aos demais atos de Manassés, à sua oração ao seu Deus e às palavras dos videntes que lhe falaram em nome do Senhor , Deus de Israel, está tudo escrito na História dos Reis de Israel.

[[v14-33-19]]

^<<v14-33-19,19>>^ A sua oração e como Deus se tornou favorável para com ele, todo o seu pecado, a sua transgressão e os locais onde edificou lugares altos e colocou postes da deusa Aserá e imagens de escultura, antes que se humilhasse, eis que está tudo escrito na História dos Videntes.

[[v14-33-20]]

^<<v14-33-20,20>>^ Manassés morreu e foi sepultado na sua própria casa. E Amom, seu filho, reinou em seu lugar.

[[v14-33-21]]

^<<v14-33-21,21>>^ Amom tinha vinte e dois anos de idade quando começou a reinar e reinou dois anos em Jerusalém.

[[v14-33-22]]

^<<v14-33-22,22>>^ Fez o que era mau aos olhos do Senhor , como Manassés, seu pai, havia feito. Ofereceu sacrifícios a todas as imagens de escultura que Manassés, seu pai, tinha feito e as serviu.

[[v14-33-23]]

^<<v14-33-23,23>>^ Mas não se humilhou diante do Senhor , como Manassés, seu pai, tinha se humilhado; pelo contrário, Amom se tornou mais e mais culpável.

[[v14-33-24]]

^<<v14-33-24,24>>^ Os seus servos conspiraram contra ele e o mataram em sua própria casa.

[[v14-33-25]]

^<<v14-33-25,25>>^ Porém o povo daquela terra matou todos os que conspiraram contra o rei Amom e proclamou Josias, filho de Amom, rei em seu lugar.

'''

xref:014-2-cronicas/014-2-cronicas-032.adoc#v14-32-0[&#60; Capítulo Anterior] | <<v14-33-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-034.adoc#v14-34-0[Próximo Capítulo &#62;]