include::./index.adoc[]

[[v14-8-0]]
=== 2 Crônicas, 8
// naa ?, NAA - Nova Almeida Atualizada

[[v14-8-1]]

^<<v14-8-1,1>>^ Ao fim de vinte anos, Salomão havia terminado a Casa do Senhor  e o seu próprio palácio.

[[v14-8-2]]

^<<v14-8-2,2>>^ Ele também reconstruiu as cidades que Hirão lhe tinha dado e fez habitar nelas os filhos de Israel.

[[v14-8-3]]

^<<v14-8-3,3>>^ Depois Salomão foi a Hamate-Zobá e a conquistou.

[[v14-8-4]]

^<<v14-8-4,4>>^ Também reconstruiu Tadmor, no deserto, e todas as cidades-armazéns em Hamate.

[[v14-8-5]]

^<<v14-8-5,5>>^ Reconstruiu também Bete-Horom-de-Cima e Bete-Horom-de-Baixo, cidades fortificadas com muralhas, portões e ferrolhos,

[[v14-8-6]]

^<<v14-8-6,6>>^ e também Baalate, e todas as cidades-armazéns que Salomão tinha, todas as cidades para os carros de guerra, as cidades para os cavaleiros e tudo o que desejou enfim construir em Jerusalém, no Líbano e em toda a terra do seu domínio.

[[v14-8-7]]

^<<v14-8-7,7>>^ Quanto a todo o povo que restou dos heteus, amorreus, ferezeus, heveus e jebuseus e que não eram de Israel,

[[v14-8-8]]

^<<v14-8-8,8>>^ e aos seus filhos, que restaram depois deles na terra, os quais os filhos de Israel não puderam destruir totalmente, esses Salomão reduziu à condição de trabalhadores forçados, até hoje.

[[v14-8-9]]

^<<v14-8-9,9>>^ Mas Salomão não obrigou nenhum israelita a trabalhar para ele como escravo. Os israelitas eram homens de guerra, seus comandantes, chefes dos seus carros de guerra e dos seus cavaleiros.

[[v14-8-10]]

^<<v14-8-10,10>>^ Estes eram os principais oficiais que o rei Salomão tinha, em número de duzentos e cinquenta, que presidiam sobre o povo.

[[v14-8-11]]

^<<v14-8-11,11>>^ Salomão trouxe a filha de Faraó da Cidade de Davi para o palácio que ele havia construído para ela, pois disse: — Minha esposa não morará no palácio de Davi, rei de Israel, porque os lugares em que entrou a arca do Senhor  são santos.

[[v14-8-12]]

^<<v14-8-12,12>>^ Então Salomão ofereceu holocaustos ao Senhor , sobre o altar que havia edificado ao Senhor  diante do pórtico,

[[v14-8-13]]

^<<v14-8-13,13>>^ e isto segundo o dever de cada dia, conforme o preceito de Moisés, nos sábados, nas Festas da Lua Nova, e nas festas fixas, três vezes por ano: na Festa dos Pães sem Fermento, na Festa das Semanas e na Festa dos Tabernáculos.

[[v14-8-14]]

^<<v14-8-14,14>>^ Também, conforme a ordem de Davi, seu pai, dispôs os turnos dos sacerdotes nos seus ministérios. Também dispôs os turnos dos levitas para os seus cargos, para louvarem a Deus e servirem diante dos sacerdotes, segundo o dever de cada dia, e os porteiros pelos seus turnos a cada porta. Porque esta era a ordem de Davi, o homem de Deus.

[[v14-8-15]]

^<<v14-8-15,15>>^ Não se desviaram do que o rei havia ordenado aos sacerdotes e levitas, em coisa nenhuma, nem no que se refere aos tesouros.

[[v14-8-16]]

^<<v14-8-16,16>>^ Assim foi executada toda a obra de Salomão, desde o dia em que foram lançados os alicerces da Casa do Senhor  até o término da construção. E assim foi concluída a Casa do Senhor .

[[v14-8-17]]

^<<v14-8-17,17>>^ Depois Salomão foi a Eziom-Geber e a Elate, à praia do mar, na terra de Edom.

[[v14-8-18]]

^<<v14-8-18,18>>^ Por meio de seus servos, Hirão enviou navios e marinheiros conhecedores do mar. Eles foram com os servos de Salomão a Ofir e de lá trouxeram mais de quinze toneladas de ouro, que entregaram ao rei Salomão.

'''

xref:014-2-cronicas/014-2-cronicas-007.adoc#v14-7-0[&#60; Capítulo Anterior] | <<v14-8-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-009.adoc#v14-9-0[Próximo Capítulo &#62;]