include::./index.adoc[]

[[v14-4-0]]
=== 2 Crônicas, 4
// naa ?, NAA - Nova Almeida Atualizada

[[v14-4-1]]

^<<v14-4-1,1>>^ Salomão também fez um altar de bronze de nove metros de comprimento, nove metros de largura e quatro metros e meio de altura.

[[v14-4-2]]

^<<v14-4-2,2>>^ Fez também o mar de fundição, redondo, de quatro metros e meio de uma borda até a outra borda, e de dois metros e vinte de altura; e a medida da circunferência correspondia a um fio de treze metros e meio.

[[v14-4-3]]

^<<v14-4-3,3>>^ Por baixo da sua borda, ao redor, havia figuras de touros, dez a cada meio metro; estavam em duas fileiras e foram fundidas quando se fundiu o mar de fundição.

[[v14-4-4]]

^<<v14-4-4,4>>^ O mar de fundição se apoiava sobre doze touros de bronze. Três olhavam para o norte, três, para o oeste, três, para o sul, e três, para o leste. O mar de fundição se apoiava sobre eles, cujas partes posteriores convergiam para dentro.

[[v14-4-5]]

^<<v14-4-5,5>>^ A grossura das paredes desse mar era de quatro dedos, e a sua borda, como borda de copo, era como uma flor de lírio. Nele cabiam cerca de sessenta mil litros.

[[v14-4-6]]

^<<v14-4-6,6>>^ Também fez dez pias e pôs cinco à direita e cinco à esquerda. Nelas era lavado tudo o que se usava nos holocaustos; o mar de fundição, porém, era para que os sacerdotes se lavassem nele.

[[v14-4-7]]

^<<v14-4-7,7>>^ Fez também dez candelabros de ouro, segundo havia sido ordenado, e os pôs no templo, cinco à direita e cinco à esquerda.

[[v14-4-8]]

^<<v14-4-8,8>>^ Também fez dez mesas e as pôs no templo, cinco à direita e cinco à esquerda; também fez cem bacias de ouro.

[[v14-4-9]]

^<<v14-4-9,9>>^ Fez mais o pátio dos sacerdotes e o pátio grande, bem como as portas deles, as quais revestiu de bronze.

[[v14-4-10]]

^<<v14-4-10,10>>^ E pôs o mar de fundição ao lado direito, para o lado sudeste.

[[v14-4-11]]

^<<v14-4-11,11>>^ Depois Hirão fez as panelas, as pás e as bacias. E assim ele terminou de fazer a obra para o rei Salomão, para a Casa de Deus:

[[v14-4-12]]

^<<v14-4-12,12>>^ as duas colunas, os dois capitéis redondos que estavam no alto das duas colunas; as duas redes, para cobrirem os dois capitéis redondos que estavam no alto das colunas;

[[v14-4-13]]

^<<v14-4-13,13>>^ as quatrocentas romãs para as duas redes, isto é, duas fileiras de romãs para cada rede, para cobrirem os dois capitéis redondos que estavam no alto das colunas.

[[v14-4-14]]

^<<v14-4-14,14>>^ Fez também os suportes e as pias sobre eles,

[[v14-4-15]]

^<<v14-4-15,15>>^ o mar de fundição com os doze touros por baixo.

[[v14-4-16]]

^<<v14-4-16,16>>^ Também as panelas, as pás, os garfos e todos os utensílios que Hirão-Abi fez para o rei Salomão, para a Casa do Senhor , eram de bronze purificado.

[[v14-4-17]]

^<<v14-4-17,17>>^ O rei os fez fundir em terra barrenta, na planície do Jordão, entre Sucote e Zereda.

[[v14-4-18]]

^<<v14-4-18,18>>^ Salomão fez todos estes objetos em grande abundância, não se verificando o peso do seu bronze.

[[v14-4-19]]

^<<v14-4-19,19>>^ Salomão também mandou fazer todos os utensílios do Santo Lugar de Deus: o altar de ouro e as mesas, sobre as quais estavam os pães da proposição;

[[v14-4-20]]

^<<v14-4-20,20>>^ e os candelabros com as suas lâmpadas de ouro puro, para as acenderem diante do Santo dos Santos, conforme havia sido ordenado.

[[v14-4-21]]

^<<v14-4-21,21>>^ As flores, as lâmpadas e as pinças eram do mais fino ouro.

[[v14-4-22]]

^<<v14-4-22,22>>^ Também os apagadores, as bacias, as taças e os incensários eram de ouro finíssimo. Quanto à entrada da casa, as portas de dentro do Santo dos Santos e as portas do Santo Lugar do templo eram de ouro.

'''

xref:014-2-cronicas/014-2-cronicas-003.adoc#v14-3-0[&#60; Capítulo Anterior] | <<v14-4-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-005.adoc#v14-5-0[Próximo Capítulo &#62;]