include::./index.adoc[]

[[v14-1-0]]
=== 2 Crônicas, 1
// naa ?, NAA - Nova Almeida Atualizada

[[v14-1-1]]

^<<v14-1-1,1>>^ Salomão, filho de Davi, fortaleceu-se no seu reino, e o Senhor , seu Deus, estava com ele e muito o engrandeceu.

[[v14-1-2]]

^<<v14-1-2,2>>^ Salomão falou a todo o Israel, aos capitães de mil e aos de cem, aos juízes e a todos os chefes em todo o Israel, cabeças de famílias.

[[v14-1-3]]

^<<v14-1-3,3>>^ E foi com toda a congregação ao lugar alto que estava em Gibeão, porque ali estava a tenda do encontro de Deus, que Moisés, servo do Senhor , tinha feito no deserto.

[[v14-1-4]]

^<<v14-1-4,4>>^ Quanto à arca de Deus, Davi a tinha trazido de Quiriate-Jearim para o lugar que lhe havia preparado, porque tinha armado uma tenda para a arca em Jerusalém.

[[v14-1-5]]

^<<v14-1-5,5>>^ Mas o altar de bronze que havia sido feito por Bezalel, filho de Uri, filho de Hur, estava ali diante do tabernáculo do Senhor ; e Salomão e a congregação consultaram o Senhor .

[[v14-1-6]]

^<<v14-1-6,6>>^ Salomão ofereceu ali sacrifícios diante do Senhor , sobre o altar de bronze que estava na tenda do encontro; e ofereceu sobre ele mil holocaustos.

[[v14-1-7]]

^<<v14-1-7,7>>^ Naquela mesma noite, Deus apareceu a Salomão e lhe disse: — Peça o que você quer que eu lhe dê.

[[v14-1-8]]

^<<v14-1-8,8>>^ Salomão respondeu: — Foste muito bondoso com Davi, meu pai, e me fizeste reinar em seu lugar.

[[v14-1-9]]

^<<v14-1-9,9>>^ E agora, ó Senhor  Deus, cumpra-se a tua promessa feita a Davi, meu pai; porque tu me constituíste rei sobre um povo numeroso como o pó da terra.

[[v14-1-10]]

^<<v14-1-10,10>>^ Dá-me, agora, sabedoria e conhecimento, para que eu saiba conduzir-me à frente deste povo; pois quem seria capaz de governar este grande povo?

[[v14-1-11]]

^<<v14-1-11,11>>^ Deus disse a Salomão: — Visto que foi este o desejo do seu coração, e você não pediu riquezas, bens ou honras, nem a morte dos seus inimigos, nem tampouco pediu longevidade, mas sabedoria e conhecimento para poder governar o meu povo, sobre o qual o constituí rei,

[[v14-1-12]]

^<<v14-1-12,12>>^ sabedoria e conhecimento lhe serão dados. E lhe darei também riquezas, bens e honras, como nenhum rei antes de você teve, nem nenhum rei depois de você terá.

[[v14-1-13]]

^<<v14-1-13,13>>^ Salomão voltou para Jerusalém, da sua ida ao lugar alto que ficava em Gibeão, de diante da tenda do encontro; e reinou sobre Israel.

[[v14-1-14]]

^<<v14-1-14,14>>^ Salomão ajuntou carros de guerra e cavaleiros. Tinha mil e quatrocentos carros de guerra e doze mil cavaleiros, que colocou nas cidades onde mantinha os carros, deixando uma parte junto ao rei, em Jerusalém.

[[v14-1-15]]

^<<v14-1-15,15>>^ O rei fez com que, em Jerusalém, a prata e o ouro fossem tão comuns como as pedras, e os cedros fossem tão numerosos como os sicômoros que estão na Sefelá.

[[v14-1-16]]

^<<v14-1-16,16>>^ Os cavalos de Salomão vinham do Egito e da Cilícia, e comerciantes do rei os importavam da Cilícia por certo preço.

[[v14-1-17]]

^<<v14-1-17,17>>^ Importava-se do Egito um carro de guerra por seiscentas moedas de prata e um cavalo, por cento e cinquenta; nas mesmas condições, as caravanas os traziam e os exportavam para todos os reis dos heteus e para os reis da Síria.

'''

xref:013-1-cronicas/013-1-cronicas-029.adoc#v13-29-0[&#60; Capítulo Anterior] | <<v14-1-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-002.adoc#v14-2-0[Próximo Capítulo &#62;]