include::./index.adoc[]

[[v14-27-0]]
=== 2 Crônicas, 27
// naa ?, NAA - Nova Almeida Atualizada

[[v14-27-1]]

^<<v14-27-1,1>>^ Jotão tinha vinte e cinco anos de idade quando começou a reinar e reinou dezesseis anos em Jerusalém. A mãe dele se chamava Jerusa e era filha de Zadoque.

[[v14-27-2]]

^<<v14-27-2,2>>^ Fez o que era reto aos olhos do Senhor , segundo tudo o que Uzias, seu pai, havia feito, exceto que não entrou no templo do Senhor . E o povo continuava na prática do mal.

[[v14-27-3]]

^<<v14-27-3,3>>^ Ele edificou o Portão de Cima da Casa do Senhor  e também edificou muitas obras sobre a Muralha de Ofel.

[[v14-27-4]]

^<<v14-27-4,4>>^ Também construiu cidades na região montanhosa de Judá e castelos e torres nos bosques.

[[v14-27-5]]

^<<v14-27-5,5>>^ Ele também guerreou contra o rei dos filhos de Amom e o derrotou, de modo que os filhos de Amom, naquele ano, lhe deram três mil e quatrocentos quilos de prata, mil toneladas de trigo e mil toneladas de cevada. E eles lhe trouxeram isto também no segundo e no terceiro ano.

[[v14-27-6]]

^<<v14-27-6,6>>^ Assim, Jotão se tornou cada vez mais poderoso, porque dirigia os seus caminhos segundo a vontade do Senhor , seu Deus.

[[v14-27-7]]

^<<v14-27-7,7>>^ Quanto aos demais atos de Jotão, todas as suas guerras e empreendimentos, eis que está tudo escrito no Livro da História dos Reis de Israel e de Judá.

[[v14-27-8]]

^<<v14-27-8,8>>^ Tinha vinte e cinco anos de idade quando começou a reinar e reinou dezesseis anos em Jerusalém.

[[v14-27-9]]

^<<v14-27-9,9>>^ Jotão morreu e foi sepultado na Cidade de Davi. E Acaz, seu filho, reinou em seu lugar.

'''

xref:014-2-cronicas/014-2-cronicas-026.adoc#v14-26-0[&#60; Capítulo Anterior] | <<v14-27-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-028.adoc#v14-28-0[Próximo Capítulo &#62;]