include::./index.adoc[]

[[v14-7-0]]
=== 2 Crônicas, 7
// naa ?, NAA - Nova Almeida Atualizada

[[v14-7-1]]

^<<v14-7-1,1>>^ Quando Salomão acabou de orar, desceu fogo do céu e consumiu o holocausto e os sacrifícios; e a glória do Senhor  encheu o templo.

[[v14-7-2]]

^<<v14-7-2,2>>^ Os sacerdotes não podiam entrar na Casa do Senhor , porque a glória do Senhor  tinha enchido a Casa do Senhor .

[[v14-7-3]]

^<<v14-7-3,3>>^ Todos os filhos de Israel, vendo descer o fogo e a glória do Senhor  sobre o templo, se inclinaram com o rosto em terra sobre o pavimento, adoraram, e louvaram o Senhor , porque ele é bom, porque a sua misericórdia dura para sempre.

[[v14-7-4]]

^<<v14-7-4,4>>^ Então o rei e todo o povo ofereceram sacrifícios ao Senhor .

[[v14-7-5]]

^<<v14-7-5,5>>^ O rei Salomão ofereceu em sacrifício vinte e dois mil bois e cento e vinte mil ovelhas. Assim, o rei e todo o povo consagraram a Casa de Deus.

[[v14-7-6]]

^<<v14-7-6,6>>^ Os sacerdotes estavam nos seus devidos lugares, bem como os levitas com os instrumentos musicais do Senhor , que o rei Davi tinha feito para com eles louvar o Senhor  — porque a sua misericórdia dura para sempre — quando Davi o louvava pelo ministério deles. Os sacerdotes que tocavam as trombetas estavam diante deles, e todo o Israel se mantinha em pé.

[[v14-7-7]]

^<<v14-7-7,7>>^ Salomão consagrou também o meio do átrio que estava diante da Casa do Senhor , pois ali ofereceu os holocaustos e a gordura dos sacrifícios pacíficos. Ele fez isso porque no altar de bronze que Salomão tinha construído não cabiam os holocaustos, as ofertas de cereais e a gordura dos sacrifícios pacíficos.

[[v14-7-8]]

^<<v14-7-8,8>>^ Nesse tempo, Salomão celebrou a festa durante sete dias, e todo o Israel com ele, uma grande congregação, desde a entrada de Hamate até o rio do Egito.

[[v14-7-9]]

^<<v14-7-9,9>>^ No oitavo dia, tiveram uma reunião solene. Porque por sete dias haviam celebrado a consagração do altar, e a festa durou mais sete dias.

[[v14-7-10]]

^<<v14-7-10,10>>^ No vigésimo terceiro dia do sétimo mês, o rei despediu o povo para as suas tendas; e todos voltaram alegres e de coração contente por causa do bem que o Senhor  tinha feito a Davi, a Salomão e a Israel, seu povo.

[[v14-7-11]]

^<<v14-7-11,11>>^ Assim, Salomão acabou de construir a Casa do Senhor  e o palácio real. Tudo o que Salomão tinha planejado fazer na Casa do Senhor  e no seu palácio ele efetuou com sucesso.

[[v14-7-12]]

^<<v14-7-12,12>>^ De noite, o Senhor  apareceu a Salomão e lhe disse: — Ouvi a sua oração e escolhi para mim este lugar para casa do sacrifício.

[[v14-7-13]]

^<<v14-7-13,13>>^ Se eu fechar o céu de modo que não haja chuva, ou se ordenar aos gafanhotos que consumam a terra, ou se enviar a peste entre o meu povo,

[[v14-7-14]]

^<<v14-7-14,14>>^ se o meu povo, que se chama pelo meu nome, se humilhar, orar, me buscar e se converter dos seus maus caminhos, eu ouvirei dos céus, perdoarei os seus pecados e sararei a sua terra.

[[v14-7-15]]

^<<v14-7-15,15>>^ Os meus olhos estarão abertos e os meus ouvidos estarão atentos à oração que se fizer neste lugar.

[[v14-7-16]]

^<<v14-7-16,16>>^ Porque escolhi e santifiquei este templo, para que nele esteja o meu nome para sempre; os meus olhos e o meu coração estarão ali todos os dias.

[[v14-7-17]]

^<<v14-7-17,17>>^ Se você andar diante de mim como fez o seu pai Davi, fazendo segundo tudo o que lhe ordenei e guardando os meus estatutos e os meus juízos,

[[v14-7-18]]

^<<v14-7-18,18>>^ também confirmarei o trono de seu reino, segundo a aliança que fiz com Davi, seu pai, dizendo: "Nunca lhe faltará sucessor que governe em Israel."

[[v14-7-19]]

^<<v14-7-19,19>>^ — Porém, se vocês se afastarem de mim e abandonarem os meus estatutos e os meus mandamentos, que eu lhes prescrevi, e se servirem outros deuses e os adorarem,

[[v14-7-20]]

^<<v14-7-20,20>>^ então os arrancarei da minha terra que lhes dei, e lançarei para longe da minha presença este templo, que santifiquei ao meu nome. E tornarei o templo em motivo de provérbio e de escárnio entre todos os povos.

[[v14-7-21]]

^<<v14-7-21,21>>^ E todo aquele que passar por este templo, agora tão exaltado, ficará espantado e perguntará: "Por que o Senhor  fez isto com esta terra e este templo?"

[[v14-7-22]]

^<<v14-7-22,22>>^ E a resposta será: "Porque deixaram o Senhor , o Deus de seus pais, que os tirou da terra do Egito, e se apegaram a outros deuses, os adoraram e os serviram. Por isso ele trouxe sobre eles todo este mal."

'''

xref:014-2-cronicas/014-2-cronicas-006.adoc#v14-6-0[&#60; Capítulo Anterior] | <<v14-7-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-008.adoc#v14-8-0[Próximo Capítulo &#62;]