include::./index.adoc[]

[[v14-15-0]]
=== 2 Crônicas, 15
// naa ?, NAA - Nova Almeida Atualizada

[[v14-15-1]]

^<<v14-15-1,1>>^ O Espírito de Deus veio sobre Azarias, filho de Odede,

[[v14-15-2]]

^<<v14-15-2,2>>^ que saiu ao encontro de Asa e lhe disse: — Asa e todo o Judá e Benjamim, escutem! O Senhor  está com vocês, enquanto vocês estão com ele. Se o buscarem, ele se deixará achar; mas, se o deixarem, ele também os deixará.

[[v14-15-3]]

^<<v14-15-3,3>>^ Israel esteve por muito tempo sem o verdadeiro Deus, sem sacerdote que o ensinasse e sem Lei.

[[v14-15-4]]

^<<v14-15-4,4>>^ Mas quando, na sua angústia, eles voltaram ao Senhor , Deus de Israel, e o buscaram, foi por eles achado.

[[v14-15-5]]

^<<v14-15-5,5>>^ Naqueles tempos, não havia paz nem para os que saíam nem para os que entravam, mas muitas perturbações sobre todos os moradores daquelas terras.

[[v14-15-6]]

^<<v14-15-6,6>>^ Porque nação contra nação e cidade contra cidade se despedaçavam, porque Deus os afligiu com todo tipo de angústia.

[[v14-15-7]]

^<<v14-15-7,7>>^ Mas sejam fortes e não deixem que as suas mãos desfaleçam, porque a obra de vocês será recompensada.

[[v14-15-8]]

^<<v14-15-8,8>>^ Ao ouvir estas palavras e a profecia do profeta, filho de Odede, Asa se animou e tirou as abominações de toda a terra de Judá e de Benjamim, bem como das cidades que havia conquistado na região montanhosa de Efraim. Ele renovou o altar do Senhor , que estava diante do pórtico do Senhor .

[[v14-15-9]]

^<<v14-15-9,9>>^ Congregou todo o Judá e Benjamim e também os de Efraim, Manassés e Simeão que estavam morando entre eles, porque muitos de Israel passaram para o lado de Asa, vendo que o Senhor , seu Deus, estava com ele.

[[v14-15-10]]

^<<v14-15-10,10>>^ Eles se reuniram em Jerusalém no terceiro mês do décimo quinto ano do reinado de Asa.

[[v14-15-11]]

^<<v14-15-11,11>>^ Naquele dia, ofereceram em sacrifício ao Senhor , do despojo que trouxeram, setecentos bois e sete mil ovelhas.

[[v14-15-12]]

^<<v14-15-12,12>>^ Entraram em aliança de buscar o Senhor , Deus de seus pais, de todo o coração e de toda a alma,

[[v14-15-13]]

^<<v14-15-13,13>>^ e de condenar à morte todos aqueles que não buscassem o Senhor , Deus de Israel, tanto os pequenos como os grandes, tanto homens como mulheres.

[[v14-15-14]]

^<<v14-15-14,14>>^ Juraram ao Senhor , em alta voz, com júbilo e ao som de clarins e trombetas.

[[v14-15-15]]

^<<v14-15-15,15>>^ Todo o Judá se alegrou por causa deste juramento, porque eles juraram de todo o coração e, de toda a boa vontade, buscaram o Senhor , e por eles foi achado. O Senhor  lhes deu paz por toda parte.

[[v14-15-16]]

^<<v14-15-16,16>>^ O rei Asa depôs também Maaca, sua mãe, da dignidade de rainha-mãe, porque ela havia feito uma abominável imagem para servir de poste da deusa Aserá. O rei Asa destruiu essa imagem, que ele reduziu a pó e queimou no vale do Cedrom.

[[v14-15-17]]

^<<v14-15-17,17>>^ Os lugares altos, porém, não foram tirados de Israel. No entanto, o coração de Asa foi fiel ao Senhor  durante toda a sua vida.

[[v14-15-18]]

^<<v14-15-18,18>>^ Ele trouxe à Casa de Deus as coisas consagradas por seu pai e as coisas que ele mesmo havia consagrado: prata, ouro e utensílios.

[[v14-15-19]]

^<<v14-15-19,19>>^ Não houve guerra até o trigésimo quinto ano do reinado de Asa.

'''

xref:014-2-cronicas/014-2-cronicas-014.adoc#v14-14-0[&#60; Capítulo Anterior] | <<v14-15-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-016.adoc#v14-16-0[Próximo Capítulo &#62;]