include::./index.adoc[]

[[v14-2-0]]
=== 2 Crônicas, 2
// naa ?, NAA - Nova Almeida Atualizada

[[v14-2-1]]

^<<v14-2-1,1>>^ Salomão resolveu edificar o templo ao nome do Senhor , bem como um palácio para o seu reino.

[[v14-2-2]]

^<<v14-2-2,2>>^ Salomão designou setenta mil homens para levarem as cargas, oitenta mil para talharem pedras nas montanhas e três mil e seiscentos para dirigirem a obra.

[[v14-2-3]]

^<<v14-2-3,3>>^ Salomão mandou dizer a Hirão, rei de Tiro: — Como você fez com Davi, meu pai, e lhe mandou cedros, para edificar o palácio em que morasse, assim também faça comigo.

[[v14-2-4]]

^<<v14-2-4,4>>^ Eis que estou para edificar um templo ao nome do Senhor , meu Deus, para consagrá-lo a ele, queimar diante dele incenso aromático e lhe apresentar o pão contínuo da proposição e os holocaustos da manhã e da tarde, nos sábados, nas Festas da Lua Nova e nas festividades do Senhor , nosso Deus. Esta é uma obrigação perpétua para Israel.

[[v14-2-5]]

^<<v14-2-5,5>>^ O templo que edificarei será grande, porque o nosso Deus é maior do que todos os deuses.

[[v14-2-6]]

^<<v14-2-6,6>>^ No entanto, quem seria capaz de lhe edificar um templo, visto que os céus e até o céu dos céus não o podem conter? E quem sou eu para lhe edificar um templo, a não ser para queimar incenso diante dele?

[[v14-2-7]]

^<<v14-2-7,7>>^ Portanto, mande-me, agora, um homem que saiba trabalhar em ouro, em prata, em bronze, em ferro, em obras de púrpura, de carmesim e de pano azul; que saiba fazer obras de entalhe juntamente com os peritos que estão comigo em Judá e em Jerusalém, os quais Davi, meu pai, contratou.

[[v14-2-8]]

^<<v14-2-8,8>>^ Mande-me também madeira de cedros, ciprestes e sândalo do Líbano; porque bem sei que os seus servos sabem cortar madeira no Líbano. Eis que os meus servos estarão com os seus servos,

[[v14-2-9]]

^<<v14-2-9,9>>^ para me prepararem muita madeira, porque o templo que edificarei será grande e maravilhoso.

[[v14-2-10]]

^<<v14-2-10,10>>^ Aos seus servos, cortadores da madeira, darei duas mil toneladas de trigo batido, duas mil toneladas de cevada, quatrocentos mil litros de vinho e quatrocentos mil litros de azeite.

[[v14-2-11]]

^<<v14-2-11,11>>^ Hirão, rei de Tiro, respondeu por uma carta que enviou a Salomão, dizendo: — O Senhor  Deus ama o seu povo e, por isso, ele o constituiu rei sobre esse povo.

[[v14-2-12]]

^<<v14-2-12,12>>^ Hirão também disse: — Bendito seja o Senhor , Deus de Israel, que fez os céus e a terra, que deu ao rei Davi um filho sábio, dotado de prudência e entendimento, que edifique um templo ao Senhor  e um palácio para o seu próprio reino.

[[v14-2-13]]

^<<v14-2-13,13>>^ E agora vou enviar um homem sábio de grande entendimento, a saber, Hirão-Abi,

[[v14-2-14]]

^<<v14-2-14,14>>^ filho de uma mulher das filhas de Dã e cujo pai era da cidade de Tiro. Ele sabe trabalhar em ouro, em prata, em bronze, em ferro, em pedras e em madeira, em obras de púrpura, de pano azul e de linho fino e em obras de carmesim. É hábil para toda obra de entalhe e para elaborar qualquer plano que lhe for apresentado, juntamente com os seus peritos e os peritos de Davi, meu senhor, seu pai.

[[v14-2-15]]

^<<v14-2-15,15>>^ Agora, que o meu senhor mande para os seus servos o trigo, a cevada, o azeite e o vinho de que falou.

[[v14-2-16]]

^<<v14-2-16,16>>^ E nós cortaremos tanta madeira no Líbano quanta você precisar e a faremos chegar em jangadas, pelo mar, a Jope, e dali você a levará para Jerusalém.

[[v14-2-17]]

^<<v14-2-17,17>>^ Salomão levantou o censo de todos os homens estrangeiros que havia na terra de Israel, segundo o censo que Davi, o seu pai, havia feito; e acharam-se cento e cinquenta e três mil e seiscentos.

[[v14-2-18]]

^<<v14-2-18,18>>^ Destes, Salomão designou setenta mil para levarem as cargas, oitenta mil para talharem pedras nas montanhas e três mil e seiscentos para dirigirem o trabalho do povo.

'''

xref:014-2-cronicas/014-2-cronicas-001.adoc#v14-1-0[&#60; Capítulo Anterior] | <<v14-2-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-003.adoc#v14-3-0[Próximo Capítulo &#62;]