include::./index.adoc[]

[[v14-26-0]]
=== 2 Crônicas, 26
// naa ?, NAA - Nova Almeida Atualizada

[[v14-26-1]]

^<<v14-26-1,1>>^ Todo o povo de Judá tomou Uzias, que tinha dezesseis anos de idade, e o constituiu rei em lugar de Amazias, seu pai.

[[v14-26-2]]

^<<v14-26-2,2>>^ Depois da morte de seu pai, Uzias reconstruiu Elate e a restituiu a Judá.

[[v14-26-3]]

^<<v14-26-3,3>>^ Uzias tinha dezesseis anos de idade quando começou a reinar e reinou cinquenta e dois anos em Jerusalém. A mãe dele se chamava Jecolias e era de Jerusalém.

[[v14-26-4]]

^<<v14-26-4,4>>^ Ele fez o que era reto aos olhos do Senhor , segundo tudo o que Amazias, seu pai, havia feito.

[[v14-26-5]]

^<<v14-26-5,5>>^ Propôs-se buscar a Deus nos dias de Zacarias, que era sábio nas visões de Deus. Enquanto Uzias buscou o Senhor , Deus o fez prosperar.

[[v14-26-6]]

^<<v14-26-6,6>>^ Ele foi e guerreou contra os filisteus. Destruiu as muralhas de Gate, de Jabné e de Asdode. Construiu cidades no território de Asdode e entre os filisteus.

[[v14-26-7]]

^<<v14-26-7,7>>^ Deus o ajudou contra os filisteus, contra os árabes que moravam em Gur-Baal e contra os meunitas.

[[v14-26-8]]

^<<v14-26-8,8>>^ Os amonitas pagavam tributo a Uzias, que chegou a ser tão poderoso que a sua fama se espalhou até a entrada do Egito.

[[v14-26-9]]

^<<v14-26-9,9>>^ Uzias construiu torres em Jerusalém, junto ao Portão da Esquina, junto ao Portão do Vale e junto ao Portão do Ângulo e as fortificou.

[[v14-26-10]]

^<<v14-26-10,10>>^ Também construiu torres no deserto e cavou muitas cisternas, porque tinha muito gado, tanto na Sefelá como nas campinas. Tinha lavradores e vinhateiros, nos montes e nos campos férteis, porque era amigo da agricultura.

[[v14-26-11]]

^<<v14-26-11,11>>^ Uzias tinha um exército de homens preparados para a guerra, que saíam para a batalha em tropas, segundo a lista feita pelo escrivão Jeiel e pelo oficial Maaseias, sob a direção de Hananias, um dos oficiais do rei.

[[v14-26-12]]

^<<v14-26-12,12>>^ O número total dos chefes das famílias, homens valentes, era de dois mil e seiscentos.

[[v14-26-13]]

^<<v14-26-13,13>>^ Debaixo das suas ordens, havia um exército guerreiro de trezentos e sete mil e quinhentos homens, que faziam a guerra com grande poder, para ajudar o rei contra os seus inimigos.

[[v14-26-14]]

^<<v14-26-14,14>>^ Uzias preparou para todo o exército escudos, lanças, capacetes, couraças e arcos e até fundas para atirar pedras.

[[v14-26-15]]

^<<v14-26-15,15>>^ Em Jerusalém ele fabricou máquinas, inventadas por homens peritos, que foram colocadas nas torres e nos cantos das muralhas, para atirarem flechas e grandes pedras. A fama de Uzias se espalhou até muito longe, porque ele foi maravilhosamente ajudado, até se tornar muito poderoso.

[[v14-26-16]]

^<<v14-26-16,16>>^ Mas, depois que Uzias se tornou poderoso, o coração dele se exaltou para a sua própria ruína. Ele cometeu uma transgressão contra o Senhor , seu Deus, pois entrou no templo do Senhor  para queimar incenso no altar do incenso.

[[v14-26-17]]

^<<v14-26-17,17>>^ Porém o sacerdote Azarias entrou atrás dele, acompanhado de oitenta sacerdotes do Senhor , homens da maior firmeza.

[[v14-26-18]]

^<<v14-26-18,18>>^ Eles enfrentaram o rei Uzias e lhe disseram: — Não compete a você, Uzias, queimar incenso diante do Senhor , mas aos sacerdotes, filhos de Arão, que são consagrados para esse serviço. Saia do santuário, porque você cometeu uma transgressão e isso não lhe trará honra da parte do Senhor  Deus.

[[v14-26-19]]

^<<v14-26-19,19>>^ Então Uzias se indignou. Ele tinha o incensário na mão para queimar incenso. No momento em que ele se indignou contra os sacerdotes, a lepra lhe saiu na testa, ali mesmo, na presença dos sacerdotes, na Casa do Senhor , junto ao altar do incenso.

[[v14-26-20]]

^<<v14-26-20,20>>^ Quando o sumo sacerdote Azarias e todos os sacerdotes se voltaram para ele, eis que ele estava leproso na testa. Então apressadamente o tiraram dali, e até ele mesmo se apressou em sair, visto que o Senhor  o havia ferido.

[[v14-26-21]]

^<<v14-26-21,21>>^ Assim, o rei Uzias ficou leproso até o dia da sua morte. E, por ser leproso, morou numa casa separada, porque foi excluído da Casa do Senhor . E Jotão, seu filho, tinha a seu encargo o palácio real, governando o povo da terra.

[[v14-26-22]]

^<<v14-26-22,22>>^ Quanto aos demais atos de Uzias, tanto os primeiros como os últimos, o profeta Isaías, filho de Amoz, os escreveu.

[[v14-26-23]]

^<<v14-26-23,23>>^ Uzias morreu e foi sepultado no túmulo de seus pais, num cemitério que pertencia aos reis. Porque disseram: "Ele era leproso." E Jotão, seu filho, reinou em seu lugar.

'''

xref:014-2-cronicas/014-2-cronicas-025.adoc#v14-25-0[&#60; Capítulo Anterior] | <<v14-26-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-027.adoc#v14-27-0[Próximo Capítulo &#62;]