include::./index.adoc[]

[[v14-9-0]]
=== 2 Crônicas, 9
// naa ?, NAA - Nova Almeida Atualizada

[[v14-9-1]]

^<<v14-9-1,1>>^ Quando a rainha de Sabá ouviu falar da fama de Salomão, veio a Jerusalém prová-lo com perguntas difíceis. Chegou com uma enorme comitiva, com camelos carregados de especiarias, de ouro em abundância e pedras preciosas. Ela se apresentou diante de Salomão e lhe expôs tudo o que trazia em sua mente.

[[v14-9-2]]

^<<v14-9-2,2>>^ Salomão respondeu todas as perguntas que ela fez, e não houve nada profundo demais que Salomão não pudesse explicar.

[[v14-9-3]]

^<<v14-9-3,3>>^ Quando a rainha de Sabá viu a sabedoria de Salomão, o palácio que ele havia construído,

[[v14-9-4]]

^<<v14-9-4,4>>^ a comida que era servida na mesa dele, o lugar dos seus oficiais, o serviço dos seus criados e os trajes deles, seus copeiros e os trajes deles, e o holocausto que oferecia na Casa do Senhor , ficou como fora de si

[[v14-9-5]]

^<<v14-9-5,5>>^ e disse ao rei: — É verdade o que ouvi na minha terra a respeito de você e a respeito da sua sabedoria.

[[v14-9-6]]

^<<v14-9-6,6>>^ Eu, porém, não acreditava no que se falava, até que vim e vi com os meus próprios olhos. Eis que não me contaram nem a metade da grandeza da sua sabedoria; você supera a fama que ouvi.

[[v14-9-7]]

^<<v14-9-7,7>>^ Felizes os homens à sua volta e felizes estes seus servos que estão sempre diante de você e que ouvem a sua sabedoria!

[[v14-9-8]]

^<<v14-9-8,8>>^ Bendito seja o Senhor , seu Deus, que se agradou de você e o colocou no seu trono como rei para o Senhor , seu Deus. É porque o seu Deus ama Israel e quer estabelecê-lo para sempre que ele o constituiu rei sobre este povo, para que você execute o juízo e a justiça.

[[v14-9-9]]

^<<v14-9-9,9>>^ Ela entregou ao rei quatro toneladas de ouro, grande abundância de especiarias e pedras preciosas. Nunca mais houve especiarias como as que a rainha de Sabá ofereceu ao rei Salomão.

[[v14-9-10]]

^<<v14-9-10,10>>^ Também os servos de Hirão e os servos de Salomão, que tinham trazido ouro de Ofir, trouxeram madeira de sândalo e pedras preciosas.

[[v14-9-11]]

^<<v14-9-11,11>>^ Desta madeira de sândalo o rei mandou fazer corrimões para a Casa do Senhor  e para o palácio real, bem como harpas e liras para os cantores. Nunca antes se tinha visto madeira como esta na terra de Judá.

[[v14-9-12]]

^<<v14-9-12,12>>^ O rei Salomão deu à rainha de Sabá tudo o que ela quis e pediu, além do equivalente ao que ela lhe havia trazido. Então ela voltou e foi para a sua terra, ela e os seus servos.

[[v14-9-13]]

^<<v14-9-13,13>>^ O peso do ouro que se trazia a Salomão a cada ano era de cerca de vinte e três toneladas,

[[v14-9-14]]

^<<v14-9-14,14>>^ além do que entrava dos vendedores e dos negociantes. Também todos os reis da Arábia e os governadores dessa mesma terra traziam a Salomão ouro e prata.

[[v14-9-15]]

^<<v14-9-15,15>>^ O rei Salomão fez duzentos grandes escudos de ouro batido, empregando sete quilos e duzentos gramas de ouro batido em cada escudo.

[[v14-9-16]]

^<<v14-9-16,16>>^ Fez também trezentos escudos menores de ouro batido, empregando três quilos e seiscentos gramas de ouro em cada escudo. E o rei os pôs na Casa do Bosque do Líbano.

[[v14-9-17]]

^<<v14-9-17,17>>^ O rei fez também um grande trono de marfim e o cobriu de ouro puro.

[[v14-9-18]]

^<<v14-9-18,18>>^ O trono tinha seis degraus e um estrado de ouro ligado a ele. De ambos os lados do assento havia um braço, e a figura de um leão junto a cada um dos braços.

[[v14-9-19]]

^<<v14-9-19,19>>^ Doze leões estavam ali sobre os seis degraus, um em cada extremo destes. Nunca se havia feito obra semelhante em nenhum outro reino.

[[v14-9-20]]

^<<v14-9-20,20>>^ Todas as taças que o rei Salomão usava para beber eram de ouro, e também de ouro puro eram todos os objetos da Casa do Bosque do Líbano. Nos dias de Salomão não se dava nenhum valor à prata.

[[v14-9-21]]

^<<v14-9-21,21>>^ Porque o rei tinha navios que iam a Társis, com os servos de Hirão. De três em três anos, os navios voltavam de Társis, trazendo ouro, prata, marfim, bugios e pavões.

[[v14-9-22]]

^<<v14-9-22,22>>^ Assim, o rei Salomão excedeu a todos os reis do mundo, tanto em riqueza como em sabedoria.

[[v14-9-23]]

^<<v14-9-23,23>>^ Todos os reis do mundo queriam ver Salomão para ouvir a sabedoria que Deus tinha posto no coração dele.

[[v14-9-24]]

^<<v14-9-24,24>>^ Cada um trazia o seu presente: objetos de prata e de ouro, roupas, armaduras, especiarias, cavalos e mulas. E foi assim ano após ano.

[[v14-9-25]]

^<<v14-9-25,25>>^ Salomão tinha quatro mil cavalos em estrebarias, para os seus carros de guerra, e doze mil cavaleiros, que colocou nas cidades onde mantinha os carros, deixando uma parte junto ao rei, em Jerusalém.

[[v14-9-26]]

^<<v14-9-26,26>>^ Salomão dominava sobre todos os reis desde o Eufrates até a terra dos filisteus e até a fronteira do Egito.

[[v14-9-27]]

^<<v14-9-27,27>>^ O rei fez com que, em Jerusalém, a prata fosse tão comum como as pedras e os cedros fossem tão numerosos como os sicômoros que estão na Sefelá.

[[v14-9-28]]

^<<v14-9-28,28>>^ Importavam-se cavalos para Salomão, do Egito e de todas as terras.

[[v14-9-29]]

^<<v14-9-29,29>>^ Quanto aos demais atos de Salomão, tanto os primeiros como os últimos, não está tudo escrito no Livro da História de Natã, o profeta, e na Profecia de Aías, o silonita, e nas Visões de Ido, o vidente, a respeito de Jeroboão, filho de Nebate?

[[v14-9-30]]

^<<v14-9-30,30>>^ Salomão reinou sobre todo o Israel, em Jerusalém, durante quarenta anos.

[[v14-9-31]]

^<<v14-9-31,31>>^ Salomão morreu e foi sepultado na Cidade de Davi, seu pai, e Roboão, seu filho, reinou em seu lugar.

'''

xref:014-2-cronicas/014-2-cronicas-008.adoc#v14-8-0[&#60; Capítulo Anterior] | <<v14-9-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-010.adoc#v14-10-0[Próximo Capítulo &#62;]