include::./index.adoc[]

[[v14-13-0]]
=== 2 Crônicas, 13
// naa ?, NAA - Nova Almeida Atualizada

[[v14-13-1]]

^<<v14-13-1,1>>^ No décimo oitavo ano do reinado de Jeroboão, Abias começou a reinar sobre Judá. Ele reinou três anos em Jerusalém.

[[v14-13-2]]

^<<v14-13-2,2>>^ A mãe dele se chamava Micaía e era filha de Uriel, de Gibeá. Também houve guerra entre Abias e Jeroboão.

[[v14-13-3]]

^<<v14-13-3,3>>^ Abias começou a guerra com um exército de valentes guerreiros, de quatrocentos mil homens escolhidos, e Jeroboão pôs em ordem de batalha contra ele um exército de oitocentos mil homens escolhidos, todos valentes guerreiros.

[[v14-13-4]]

^<<v14-13-4,4>>^ Abias pôs-se em pé no alto do monte Zemaraim, que está na região montanhosa de Efraim, e gritou: — Jeroboão e todo o Israel, escutem o que vou dizer!

[[v14-13-5]]

^<<v14-13-5,5>>^ Será que vocês não sabem que o Senhor , o Deus de Israel, deu para sempre a Davi a soberania de Israel, a ele e aos seus filhos, por uma aliança perpétua?

[[v14-13-6]]

^<<v14-13-6,6>>^ Contudo, Jeroboão, filho de Nebate, servo de Salomão, filho de Davi, se levantou e se rebelou contra o seu senhor.

[[v14-13-7]]

^<<v14-13-7,7>>^ Juntaram-se a ele uns homens vadios e malignos, que desafiaram Roboão, filho de Salomão. Como Roboão era ainda jovem e indeciso, não lhes pôde resistir.

[[v14-13-8]]

^<<v14-13-8,8>>^ Agora vocês pensam que podem resistir ao reino do Senhor , que está nas mãos dos filhos de Davi. Vocês são uma grande multidão e estão trazendo com vocês os bezerros de ouro que Jeroboão fez para serem os seus deuses.

[[v14-13-9]]

^<<v14-13-9,9>>^ Não é verdade que vocês expulsaram os sacerdotes do Senhor , os filhos de Arão e os levitas, e escolheram para si outros sacerdotes, como fazem os povos das outras terras? Qualquer um que vem para consagrar-se com um novilho e sete carneiros logo se torna sacerdote daqueles que não são deuses.

[[v14-13-10]]

^<<v14-13-10,10>>^ — Quanto a nós, o Senhor  é o nosso Deus, e nunca o abandonamos. Temos sacerdotes, que ministram ao Senhor , a saber, os filhos de Arão e os levitas na sua obra.

[[v14-13-11]]

^<<v14-13-11,11>>^ Cada dia, de manhã e à tarde, oferecem holocaustos e queimam incenso aromático, colocando em ordem os pães da proposição sobre a mesa puríssima e o candelabro de ouro e as suas lâmpadas para se acenderem cada tarde, porque nós guardamos o preceito do Senhor , nosso Deus, ao passo que vocês o abandonaram.

[[v14-13-12]]

^<<v14-13-12,12>>^ Eis que Deus está conosco, à nossa frente, e também os seus sacerdotes, tocando com as trombetas, para darem o grito de guerra contra vocês, ó filhos de Israel. Não lutem contra o Senhor , o Deus de seus pais, porque vocês não serão bem-sucedidos.

[[v14-13-13]]

^<<v14-13-13,13>>^ Mas Jeroboão ordenou aos que estavam de emboscada que fizessem uma volta e atacassem o exército de Abias pela retaguarda, de maneira que o seu exército estava em frente dos homens de Judá, e a emboscada vinha por detrás deles.

[[v14-13-14]]

^<<v14-13-14,14>>^ Quando os homens de Judá olharam, viram que a batalha estava por diante e por detrás. Então clamaram ao Senhor , e os sacerdotes tocaram as trombetas.

[[v14-13-15]]

^<<v14-13-15,15>>^ Os homens de Judá gritaram. Quando gritavam, Deus derrotou Jeroboão e todo o Israel diante de Abias e de Judá.

[[v14-13-16]]

^<<v14-13-16,16>>^ Os filhos de Israel fugiram de diante de Judá, e Deus os entregou nas suas mãos.

[[v14-13-17]]

^<<v14-13-17,17>>^ Abias e o seu povo fizeram grande matança entre eles, de maneira que morreram quinhentos mil homens escolhidos de Israel.

[[v14-13-18]]

^<<v14-13-18,18>>^ Assim, os filhos de Israel foram humilhados naquele tempo, e os filhos de Judá prevaleceram, porque confiaram no Senhor , Deus de seus pais.

[[v14-13-19]]

^<<v14-13-19,19>>^ Abias perseguiu Jeroboão e lhe tomou as cidades de Betel, Jesana e Efrom, com as suas respectivas vilas.

[[v14-13-20]]

^<<v14-13-20,20>>^ Jeroboão não restaurou mais o seu poder no tempo de Abias. O Senhor  feriu Jeroboão, e ele morreu.

[[v14-13-21]]

^<<v14-13-21,21>>^ Abias, porém, se fortificou. Tomou para si catorze mulheres, e gerou vinte e dois filhos e dezesseis filhas.

[[v14-13-22]]

^<<v14-13-22,22>>^ Quanto aos demais atos de Abias, tanto o que fez como o que disse, está tudo escrito no Livro da História do Profeta Ido.

'''

xref:014-2-cronicas/014-2-cronicas-012.adoc#v14-12-0[&#60; Capítulo Anterior] | <<v14-13-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-014.adoc#v14-14-0[Próximo Capítulo &#62;]