include::./index.adoc[]

[[v14-32-0]]
=== 2 Crônicas, 32
// naa ?, NAA - Nova Almeida Atualizada

[[v14-32-1]]

^<<v14-32-1,1>>^ Depois destas coisas e desta fidelidade, Senaqueribe, rei da Assíria, invadiu Judá e sitiou as cidades fortificadas, com a intenção de conquistá-las.

[[v14-32-2]]

^<<v14-32-2,2>>^ Quando Ezequias viu que Senaqueribe tinha vindo e estava resolvido a atacar Jerusalém,

[[v14-32-3]]

^<<v14-32-3,3>>^ decidiu, em consulta com os seus oficiais e os seus homens valentes, tapar as fontes das águas que havia fora da cidade; e eles o ajudaram.

[[v14-32-4]]

^<<v14-32-4,4>>^ Assim, muito povo se ajuntou, e taparam todas as fontes, bem como o ribeiro que corria pelo meio da terra, pois diziam: "Por que viriam os reis da Assíria e achariam tanta água por aqui?"

[[v14-32-5]]

^<<v14-32-5,5>>^ Ezequias se animou, restaurou a muralha da cidade e construiu torres sobre ela. Levantou também outra muralha por fora, fortificou Milo na Cidade de Davi e fez armas e escudos em abundância.

[[v14-32-6]]

^<<v14-32-6,6>>^ Pôs oficiais de guerra à frente do povo, reuniu-os na praça junto ao portão da cidade e lhes falou ao coração, dizendo:

[[v14-32-7]]

^<<v14-32-7,7>>^ — Sejam fortes e corajosos, não tenham medo, nem se assustem por causa do rei da Assíria, nem por causa de toda a multidão que está com ele, porque conosco está alguém que é maior do que o que está com ele.

[[v14-32-8]]

^<<v14-32-8,8>>^ Com ele está o braço de carne, mas conosco está o Senhor , nosso Deus, para nos ajudar e para guerrear as nossas guerras. O povo se animou com as palavras de Ezequias, rei de Judá.

[[v14-32-9]]

^<<v14-32-9,9>>^ Depois disto, quando Senaqueribe, rei da Assíria, com todo o seu exército sitiava Laquis, ele enviou os seus servos a Ezequias, rei de Judá, e a todo o povo de Judá que estava em Jerusalém, dizendo:

[[v14-32-10]]

^<<v14-32-10,10>>^ — Assim diz Senaqueribe, rei da Assíria: "Em que vocês confiam, vocês que estão aí em Jerusalém, que está sitiada?

[[v14-32-11]]

^<<v14-32-11,11>>^ Por acaso, não é Ezequias quem está incitando vocês, para que morram de fome e de sede, dizendo: ‘O Senhor , nosso Deus, nos livrará das mãos do rei da Assíria?’

[[v14-32-12]]

^<<v14-32-12,12>>^ Não é Ezequias o mesmo que removeu os lugares altos e os altares do Senhor , dizendo a Judá e a Jerusalém: ‘Diante de um só altar vocês devem se prostrar e apenas sobre ele devem queimar incenso?’

[[v14-32-13]]

^<<v14-32-13,13>>^ Vocês não sabem o que eu e os meus pais fizemos com todos os povos das outras terras? Será que os deuses das nações daquelas terras puderam de alguma forma livrar o seu país das minhas mãos?

[[v14-32-14]]

^<<v14-32-14,14>>^ De todos os deuses daquelas nações que os meus pais destruíram, qual deles foi capaz de livrar o seu povo das minhas mãos? Então como o Deus de vocês será capaz de livrá-los das minhas mãos?

[[v14-32-15]]

^<<v14-32-15,15>>^ Portanto, não deixem agora que Ezequias os engane, nem que os incite assim. Não acreditem nele! Porque nenhum deus de nação alguma nem de reino algum foi capaz de livrar o seu povo das minhas mãos, nem das mãos de meus pais. Muito menos o Deus de vocês será capaz de livrá-los das minhas mãos!"

[[v14-32-16]]

^<<v14-32-16,16>>^ Os servos de Senaqueribe falaram ainda mais contra o Senhor  Deus e contra Ezequias, seu servo.

[[v14-32-17]]

^<<v14-32-17,17>>^ Senaqueribe escreveu também cartas para blasfemar do Senhor , Deus de Israel, e para falar contra ele, dizendo: "Assim como os deuses das nações de outras terras não livraram o seu povo das minhas mãos, assim também o Deus de Ezequias não livrará o seu povo das minhas mãos."

[[v14-32-18]]

^<<v14-32-18,18>>^ Os servos gritaram bem alto, em hebraico, ao povo de Jerusalém, que estava sobre a muralha, para os atemorizar e os perturbar, para tomarem a cidade.

[[v14-32-19]]

^<<v14-32-19,19>>^ Falaram do Deus de Jerusalém como falavam dos deuses dos povos da terra, que são obras das mãos dos homens.

[[v14-32-20]]

^<<v14-32-20,20>>^ Então o rei Ezequias e o profeta Isaías, filho de Amoz, oraram por causa disso e clamaram ao céu.

[[v14-32-21]]

^<<v14-32-21,21>>^ E o Senhor  enviou um anjo que destruiu todos os homens valentes, os chefes e os príncipes no arraial do rei da Assíria; e este, com o rosto coberto de vergonha, voltou para a sua terra. Quando ele entrou no templo de seu deus, os seus próprios filhos ali o mataram à espada.

[[v14-32-22]]

^<<v14-32-22,22>>^ Assim o Senhor  livrou Ezequias e os moradores de Jerusalém das mãos de Senaqueribe, rei da Assíria, e das mãos de todos os inimigos; e lhes deu paz por todos os lados.

[[v14-32-23]]

^<<v14-32-23,23>>^ Muitos traziam presentes a Jerusalém ao Senhor  e coisas preciosíssimas a Ezequias, rei de Judá, de modo que, depois disto, foi exaltado à vista de todas as nações.

[[v14-32-24]]

^<<v14-32-24,24>>^ Por esse tempo, Ezequias adoeceu de uma enfermidade mortal. Então orou ao Senhor , que lhe falou e lhe deu um sinal.

[[v14-32-25]]

^<<v14-32-25,25>>^ Mas Ezequias não correspondeu aos benefícios que lhe foram feitos, pois o seu coração se exaltou. Por isso veio grande ira sobre ele e sobre Judá e Jerusalém.

[[v14-32-26]]

^<<v14-32-26,26>>^ Porém Ezequias se humilhou por se ter exaltado o seu coração, ele e os moradores de Jerusalém; e a ira do Senhor  não veio sobre eles nos dias de Ezequias.

[[v14-32-27]]

^<<v14-32-27,27>>^ Ezequias teve riquezas e glória em grande abundância. Construiu depósitos para guardar a prata, o ouro, as pedras preciosas, as especiarias, os escudos e todos os objetos de valor.

[[v14-32-28]]

^<<v14-32-28,28>>^ Também construiu armazéns para a colheita do cereal, do vinho e do azeite, estrebarias para toda espécie de animais e currais para os rebanhos.

[[v14-32-29]]

^<<v14-32-29,29>>^ Edificou cidades e teve ovelhas e vacas em abundância, porque Deus lhe tinha dado muitos bens.

[[v14-32-30]]

^<<v14-32-30,30>>^ Também o mesmo Ezequias tapou o manancial superior das águas de Giom e as canalizou para o oeste da Cidade de Davi. Ezequias prosperou em toda a sua obra.

[[v14-32-31]]

^<<v14-32-31,31>>^ Mas, quando os embaixadores dos príncipes da Babilônia lhe foram enviados para se informarem a respeito do prodígio que tinha acontecido na terra, Deus o desamparou, para prová-lo e para saber tudo o que havia no coração dele.

[[v14-32-32]]

^<<v14-32-32,32>>^ Quanto aos demais atos de Ezequias e às suas obras de misericórdia, está tudo escrito na Visão do Profeta Isaías, filho de Amoz, e no Livro da História dos Reis de Judá e de Israel.

[[v14-32-33]]

^<<v14-32-33,33>>^ Ezequias morreu e foi sepultado na subida para os túmulos dos filhos de Davi. Todo o povo de Judá e os moradores de Jerusalém lhe prestaram honras na sua morte. E Manassés, seu filho, reinou em seu lugar.

'''

xref:014-2-cronicas/014-2-cronicas-031.adoc#v14-31-0[&#60; Capítulo Anterior] | <<v14-32-0,Topo>> | xref:014-2-cronicas/014-2-cronicas-033.adoc#v14-33-0[Próximo Capítulo &#62;]