include::./index.adoc[]

[[v2-6-0]]
=== Êxodo, 6
// naa ?, NAA - Nova Almeida Atualizada

[[v2-6-1]]

^<<v2-6-1,1>>^ Então o Senhor  disse a Moisés: — Agora você verá o que vou fazer a Faraó, pois, por mão poderosa, os deixará ir e, por mão poderosa, os expulsará da sua terra.

[[v2-6-2]]

^<<v2-6-2,2>>^ Deus falou a Moisés e lhe disse: — Eu sou o Senhor .

[[v2-6-3]]

^<<v2-6-3,3>>^ Apareci a Abraão, a Isaque e a Jacó como o Deus Todo-Poderoso; mas pelo meu nome, O Senhor , não lhes fui conhecido.

[[v2-6-4]]

^<<v2-6-4,4>>^ Também estabeleci a minha aliança com eles, para dar-lhes a terra de Canaã, a terra em que viveram como estrangeiros.

[[v2-6-5]]

^<<v2-6-5,5>>^ Eu também ouvi os gemidos dos filhos de Israel, os quais os egípcios escravizam, e me lembrei da minha aliança.

[[v2-6-6]]

^<<v2-6-6,6>>^ Portanto, diga aos filhos de Israel: "Eu sou o Senhor . Vou tirá-los dos trabalhos pesados no Egito, vou livrá-los da escravidão, vou resgatar vocês com braço estendido e com grandes manifestações de juízo.

[[v2-6-7]]

^<<v2-6-7,7>>^ Eu os tomarei por meu povo e serei o seu Deus; e vocês saberão que eu sou o Senhor , seu Deus, que os tiro dos trabalhos pesados no Egito.

[[v2-6-8]]

^<<v2-6-8,8>>^ Eu os levarei para a terra que jurei dar a Abraão, a Isaque e a Jacó; darei essa terra a vocês como herança. Eu sou o Senhor ."

[[v2-6-9]]

^<<v2-6-9,9>>^ Desse modo Moisés falou aos filhos de Israel, mas eles não deram ouvidos a Moisés, por causa da angústia de espírito e da dura escravidão.

[[v2-6-10]]

^<<v2-6-10,10>>^ O Senhor  falou a Moisés, dizendo:

[[v2-6-11]]

^<<v2-6-11,11>>^ — Vá e diga a Faraó, rei do Egito, que deixe que os filhos de Israel saiam de sua terra.

[[v2-6-12]]

^<<v2-6-12,12>>^ Moisés, porém, respondeu ao Senhor , dizendo: — Eis que os filhos de Israel não me têm ouvido; como, pois, me ouvirá Faraó? E não sei falar bem.

[[v2-6-13]]

^<<v2-6-13,13>>^ No entanto, o Senhor  falou a Moisés e a Arão e lhes deu uma ordem para os filhos de Israel e para Faraó, rei do Egito: deveriam tirar os filhos de Israel da terra do Egito.

[[v2-6-14]]

^<<v2-6-14,14>>^ São estes os chefes das famílias: os filhos de Rúben, o primogênito de Israel: Enoque, Palu, Hezrom e Carmi; são estas as famílias de Rúben.

[[v2-6-15]]

^<<v2-6-15,15>>^ Os filhos de Simeão: Jemuel, Jamim, Oade, Jaquim, Zoar e Saul, filho de uma cananeia; são estas as famílias de Simeão.

[[v2-6-16]]

^<<v2-6-16,16>>^ São estes os nomes dos filhos de Levi, segundo as suas gerações: Gérson, Coate e Merari; e os anos da vida de Levi foram cento e trinta e sete.

[[v2-6-17]]

^<<v2-6-17,17>>^ Os filhos de Gérson: Libni e Simei, segundo as suas famílias.

[[v2-6-18]]

^<<v2-6-18,18>>^ Os filhos de Coate: Anrão, Isar, Hebrom e Uziel; e os anos da vida de Coate foram cento e trinta e três.

[[v2-6-19]]

^<<v2-6-19,19>>^ Os filhos de Merari: Mali e Musi; são estas as famílias de Levi, segundo as suas gerações.

[[v2-6-20]]

^<<v2-6-20,20>>^ Anrão tomou por mulher Joquebede, sua tia, e ela lhe deu à luz Arão e Moisés; e os anos da vida de Anrão foram cento e trinta e sete.

[[v2-6-21]]

^<<v2-6-21,21>>^ Os filhos de Isar: Corá, Nefegue e Zicri.

[[v2-6-22]]

^<<v2-6-22,22>>^ Os filhos de Uziel: Misael, Elzafã e Sitri.

[[v2-6-23]]

^<<v2-6-23,23>>^ Arão tomou por mulher Eliseba, filha de Aminadabe, irmã de Naassom; e ela lhe deu à luz Nadabe, Abiú, Eleazar e Itamar.

[[v2-6-24]]

^<<v2-6-24,24>>^ Os filhos de Corá: Assir, Elcana e Abiasafe; são estas as famílias dos coraítas.

[[v2-6-25]]

^<<v2-6-25,25>>^ Eleazar, filho de Arão, tomou por mulher, para si, uma das filhas de Putiel; e ela lhe deu à luz Fineias; são estes os chefes de suas casas, segundo as suas famílias.

[[v2-6-26]]

^<<v2-6-26,26>>^ São estes Arão e Moisés, aos quais o Senhor  disse: "Tirem os filhos de Israel da terra do Egito, segundo os seus exércitos."

[[v2-6-27]]

^<<v2-6-27,27>>^ Foram eles que falaram a Faraó, rei do Egito, a fim de tirar do Egito os filhos de Israel; são estes Moisés e Arão.

[[v2-6-28]]

^<<v2-6-28,28>>^ No dia em que o Senhor  falou a Moisés na terra do Egito,

[[v2-6-29]]

^<<v2-6-29,29>>^ o Senhor  disse a Moisés: — Eu sou o Senhor ; diga a Faraó, rei do Egito, tudo o que eu digo a você.

[[v2-6-30]]

^<<v2-6-30,30>>^ Porém Moisés respondeu na presença do Senhor : — Eu não sei falar bem. Como é que Faraó vai me ouvir?

'''

xref:002-exodo/002-exodo-005.adoc#v2-5-0[&#60; Capítulo Anterior] | <<v2-6-0,Topo>> | xref:002-exodo/002-exodo-007.adoc#v2-7-0[Próximo Capítulo &#62;]