include::./index.adoc[]

[[v2-13-0]]
=== Êxodo, 13
// naa ?, NAA - Nova Almeida Atualizada

[[v2-13-1]]

^<<v2-13-1,1>>^ O Senhor  disse a Moisés:

[[v2-13-2]]

^<<v2-13-2,2>>^ — Consagre-me todo primogênito. Todo o primeiro que sair do ventre de sua mãe entre os israelitas, tanto de homens como de animais, é meu.

[[v2-13-3]]

^<<v2-13-3,3>>^ Moisés disse ao povo: — Lembrem-se deste dia, o dia em que vocês saíram do Egito, da casa da servidão; pois com mão forte o Senhor  os tirou de lá; portanto, não comam pão feito com fermento.

[[v2-13-4]]

^<<v2-13-4,4>>^ Hoje, mês de abibe, vocês estão saindo do Egito.

[[v2-13-5]]

^<<v2-13-5,5>>^ Quando o Senhor  os tiver introduzido na terra dos cananeus, dos heteus, dos amorreus, dos heveus e dos jebuseus, terra que o Senhor  jurou a seus pais que daria a vocês, terra que mana leite e mel, vocês observarão este rito neste mês.

[[v2-13-6]]

^<<v2-13-6,6>>^ Durante sete dias vocês comerão pães sem fermento; e no sétimo dia haverá festa ao Senhor .

[[v2-13-7]]

^<<v2-13-7,7>>^ Durante sete dias vocês comerão pães sem fermento. Nada que tenha sido levedado se encontrará entre vocês nem ainda fermento será encontrado em todo o seu território.

[[v2-13-8]]

^<<v2-13-8,8>>^ — Naquele mesmo dia, vocês dirão a seus filhos: "Isto é pelo que o Senhor  nos fez, quando saímos do Egito."

[[v2-13-9]]

^<<v2-13-9,9>>^ E será como sinal na mão de vocês e por memorial entre os seus olhos, para que a lei do Senhor  esteja na sua boca; pois com mão forte o Senhor  os tirou do Egito.

[[v2-13-10]]

^<<v2-13-10,10>>^ Portanto, guardem esta ordenança no tempo determinado, de ano em ano.

[[v2-13-11]]

^<<v2-13-11,11>>^ — Quando o Senhor  os tiver introduzido na terra dos cananeus, como jurou a vocês e aos seus pais, quando ele lhes tiver dado essa terra,

[[v2-13-12]]

^<<v2-13-12,12>>^ vocês deverão separar para o Senhor  todo primeiro filho homem que nascer e todo primogênito dos seus animais; os filhos e filhotes machos serão do Senhor .

[[v2-13-13]]

^<<v2-13-13,13>>^ Porém todo primogênito da jumenta vocês poderão resgatar com um cordeiro; se não o resgatarem, deverá ser desnucado; mas vocês resgatarão todo primogênito do homem entre os seus filhos.

[[v2-13-14]]

^<<v2-13-14,14>>^ — Se no futuro o seu filho perguntar: "O que significa isso?", você responderá: "O Senhor  com mão forte nos tirou da casa da servidão.

[[v2-13-15]]

^<<v2-13-15,15>>^ Pois aconteceu que, endurecendo-se Faraó para não nos deixar sair, o Senhor  matou todos os primogênitos na terra do Egito, desde o primogênito do homem até o primogênito dos animais; por isso, sacrificamos ao Senhor  todo primeiro filhote macho. Mas a todo primogênito de nossos filhos nós resgatamos."

[[v2-13-16]]

^<<v2-13-16,16>>^ E isto será como sinal nas suas mãos e por frontais entre os seus olhos; porque o Senhor  com mão forte nos tirou do Egito.

[[v2-13-17]]

^<<v2-13-17,17>>^ Quando Faraó deixou o povo ir, Deus não os levou pelo caminho da terra dos filisteus, embora fosse mais perto, pois disse: — Para não acontecer que, vendo a guerra, o povo se arrependa e queira voltar para o Egito.

[[v2-13-18]]

^<<v2-13-18,18>>^ Porém Deus fez o povo rodear pelo caminho do deserto perto do mar Vermelho. Os filhos de Israel saíram do Egito organizados como um exército.

[[v2-13-19]]

^<<v2-13-19,19>>^ Moisés levou consigo também os ossos de José, pois este havia feito com que os filhos de Israel jurassem solenemente, dizendo: "Deus certamente visitará vocês. Quando isso acontecer, levem os meus ossos daqui."

[[v2-13-20]]

^<<v2-13-20,20>>^ Os israelitas partiram de Sucote e acamparam em Etã, à entrada do deserto.

[[v2-13-21]]

^<<v2-13-21,21>>^ O Senhor  ia adiante deles, durante o dia, numa coluna de nuvem, para os guiar pelo caminho; durante a noite, numa coluna de fogo, para os iluminar, a fim de que caminhassem de dia e de noite.

[[v2-13-22]]

^<<v2-13-22,22>>^ A coluna de nuvem nunca se afastou do povo durante o dia, nem a coluna de fogo durante a noite.

'''

xref:002-exodo/002-exodo-012.adoc#v2-12-0[&#60; Capítulo Anterior] | <<v2-13-0,Topo>> | xref:002-exodo/002-exodo-014.adoc#v2-14-0[Próximo Capítulo &#62;]