include::./index.adoc[]

[[v2-10-0]]
=== Êxodo, 10
// naa ?, NAA - Nova Almeida Atualizada

[[v2-10-1]]

^<<v2-10-1,1>>^ O Senhor  disse a Moisés: — Vá falar com Faraó, porque lhe endureci o coração e o coração de seus oficiais, para que eu faça estes meus sinais no meio deles,

[[v2-10-2]]

^<<v2-10-2,2>>^ e para que você possa contar aos seus filhos e aos filhos de seus filhos como zombei dos egípcios e quantos sinais fiz no meio deles, e para que vocês saibam que eu sou o Senhor .

[[v2-10-3]]

^<<v2-10-3,3>>^ Moisés e Arão apresentaram-se a Faraó e lhe disseram: — Assim diz o Senhor , o Deus dos hebreus: "Até quando você se recusará a humilhar-se diante de mim? Deixe o meu povo ir, para que me adore.

[[v2-10-4]]

^<<v2-10-4,4>>^ Se você não deixar o meu povo ir, eis que amanhã trarei gafanhotos ao seu território.

[[v2-10-5]]

^<<v2-10-5,5>>^ Eles cobrirão de tal maneira a face da terra que não será possível ver o chão. Comerão o restante que escapou, o que restou depois da chuva de pedras, e comerão todas as árvores que crescem no campo.

[[v2-10-6]]

^<<v2-10-6,6>>^ Os gafanhotos encherão as suas casas, as casas de todos os seus oficiais e as casas de todos os egípcios, como nunca viram os seus pais, nem os seus antepassados desde o dia em que se estabeleceram na terra até o dia de hoje." Moisés virou-se e saiu da presença de Faraó.

[[v2-10-7]]

^<<v2-10-7,7>>^ Então os oficiais de Faraó disseram: — Até quando este homem será um perigo para nós? Deixe essa gente ir, para que adorem o Senhor , o Deus deles. Será que o rei ainda não sabe que o Egito está arruinado?

[[v2-10-8]]

^<<v2-10-8,8>>^ Então Moisés e Arão foram conduzidos à presença de Faraó, e este lhes disse: — Vão e adorem o Senhor , o seu Deus. Mas eu gostaria de saber quem são os que irão.

[[v2-10-9]]

^<<v2-10-9,9>>^ Moisés respondeu: — Iremos com os nossos jovens, com os nossos velhos, com os filhos, com as filhas, com os nossos rebanhos e com os nossos gados. Iremos, porque temos de celebrar uma festa ao Senhor .

[[v2-10-10]]

^<<v2-10-10,10>>^ Então Faraó disse: — Que o Senhor  esteja de fato com vocês, se eu permitir que vocês saiam e levem junto as crianças. Vejam, vocês têm más intenções.

[[v2-10-11]]

^<<v2-10-11,11>>^ Mas não é assim que vai ser. Vão somente vocês, os homens, e adorem o Senhor , pois é isso o que vocês estão pedindo. E os expulsaram da presença de Faraó.

[[v2-10-12]]

^<<v2-10-12,12>>^ Então o Senhor  disse a Moisés: — Estenda a mão sobre a terra do Egito, para que venham gafanhotos sobre a terra do Egito e comam toda a vegetação da terra, tudo o que a chuva de pedras não destruiu.

[[v2-10-13]]

^<<v2-10-13,13>>^ Moisés estendeu o seu bordão sobre a terra do Egito, e o Senhor  trouxe sobre a terra um vento leste todo aquele dia e toda aquela noite. Quando amanheceu, o vento leste tinha trazido os gafanhotos.

[[v2-10-14]]

^<<v2-10-14,14>>^ E os gafanhotos se espalharam por toda a terra do Egito e pousaram sobre todo o seu território. Eram muito numerosos. Antes destes, nunca houve tantos gafanhotos, nem depois deles virão outros assim.

[[v2-10-15]]

^<<v2-10-15,15>>^ Porque cobriram a superfície de toda a terra, de modo que a terra se escureceu. Devoraram toda a vegetação da terra e todo fruto das árvores que a chuva de pedras não havia destruído. E não restou nada verde nas árvores, nem na vegetação do campo, em toda a terra do Egito.

[[v2-10-16]]

^<<v2-10-16,16>>^ Então Faraó se apressou em chamar Moisés e Arão e lhes disse: — Pequei contra o Senhor , seu Deus, e contra vocês.

[[v2-10-17]]

^<<v2-10-17,17>>^ Agora peço que me perdoem o pecado ainda esta vez e que orem ao Senhor , seu Deus, para que tire de mim esta praga mortal.

[[v2-10-18]]

^<<v2-10-18,18>>^ Moisés saiu da presença de Faraó e orou ao Senhor .

[[v2-10-19]]

^<<v2-10-19,19>>^ Então o Senhor  fez soprar um vento oeste muito forte, que levantou os gafanhotos e os lançou no mar Vermelho. Não restou um só gafanhoto em todo o território do Egito.

[[v2-10-20]]

^<<v2-10-20,20>>^ O Senhor , porém, endureceu o coração de Faraó, e este não deixou ir os filhos de Israel.

[[v2-10-21]]

^<<v2-10-21,21>>^ Então o Senhor  disse a Moisés: — Estenda a mão para o céu, e virão trevas sobre a terra do Egito, trevas que se possam apalpar.

[[v2-10-22]]

^<<v2-10-22,22>>^ Moisés estendeu a mão para o céu, e houve trevas espessas sobre toda a terra do Egito durante três dias.

[[v2-10-23]]

^<<v2-10-23,23>>^ Os egípcios não podiam ver uns aos outros, e ninguém se levantou do seu lugar durante três dias. Porém todos os filhos de Israel tinham claridade nas suas casas.

[[v2-10-24]]

^<<v2-10-24,24>>^ Então Faraó chamou Moisés e lhe disse: — Vão e adorem o Senhor . Fiquem somente os seus rebanhos e o seu gado; as crianças podem ir com vocês.

[[v2-10-25]]

^<<v2-10-25,25>>^ Moisés respondeu: — Então você teria de nos providenciar os animais para os sacrifícios e holocaustos que queremos oferecer ao Senhor , nosso Deus.

[[v2-10-26]]

^<<v2-10-26,26>>^ Por isso os nossos rebanhos irão conosco. Nem um casco de animal ficará para trás, porque temos de escolher alguns para oferecer em sacrifício ao Senhor , nosso Deus. E, enquanto não chegarmos lá, não saberemos com que animais teremos de adorar o Senhor .

[[v2-10-27]]

^<<v2-10-27,27>>^ O Senhor , porém, endureceu o coração de Faraó, e este não quis deixá-los ir.

[[v2-10-28]]

^<<v2-10-28,28>>^ Faraó disse a Moisés: — Saia da minha presença e tenha cuidado para nunca mais aparecer aqui. Porque, no dia em que você tornar a ver o meu rosto, será morto.

[[v2-10-29]]

^<<v2-10-29,29>>^ Moisés respondeu: — Como queira! Nunca mais tornarei a ver o seu rosto.

'''

xref:002-exodo/002-exodo-009.adoc#v2-9-0[&#60; Capítulo Anterior] | <<v2-10-0,Topo>> | xref:002-exodo/002-exodo-011.adoc#v2-11-0[Próximo Capítulo &#62;]