include::./index.adoc[]

[[v2-12-0]]
=== Êxodo, 12
// naa ?, NAA - Nova Almeida Atualizada

[[v2-12-1]]

^<<v2-12-1,1>>^ O Senhor  disse a Moisés e a Arão na terra do Egito:

[[v2-12-2]]

^<<v2-12-2,2>>^ — Este mês será para vocês o principal dos meses; será o primeiro mês do ano.

[[v2-12-3]]

^<<v2-12-3,3>>^ Falem a toda a congregação de Israel, dizendo: No dia dez deste mês, cada um tomará para si um cordeiro, segundo a casa dos pais, um cordeiro para cada família.

[[v2-12-4]]

^<<v2-12-4,4>>^ Mas, se a família for pequena para um cordeiro, então o chefe da família convidará o seu vizinho mais próximo, conforme o número de pessoas. Conforme o que cada um puder comer, por aí vocês calcularão quantos são necessários para o cordeiro.

[[v2-12-5]]

^<<v2-12-5,5>>^ O cordeiro será sem defeito, macho de um ano, podendo também ser um cabrito.

[[v2-12-6]]

^<<v2-12-6,6>>^ Vocês guardarão o cordeiro até o décimo quarto dia deste mês, e todo o ajuntamento da congregação de Israel o matará no crepúsculo da tarde.

[[v2-12-7]]

^<<v2-12-7,7>>^ Pegarão um pouco do sangue e o passarão nas duas ombreiras e na viga superior da porta, nas casas em que o comerem.

[[v2-12-8]]

^<<v2-12-8,8>>^ — Naquela noite, comerão a carne assada no fogo, com pães sem fermento e ervas amargas.

[[v2-12-9]]

^<<v2-12-9,9>>^ Não comam do animal nada cru, nem cozido em água, porém assado ao fogo: a cabeça, as pernas e as vísceras.

[[v2-12-10]]

^<<v2-12-10,10>>^ Não deixem nada do cordeiro até pela manhã; o que, porém, ficar até pela manhã, queimem.

[[v2-12-11]]

^<<v2-12-11,11>>^ É assim que vocês devem comê-lo: já prontos para viajar, com as sandálias nos pés e o cajado na mão. Comam depressa. É a Páscoa do Senhor .

[[v2-12-12]]

^<<v2-12-12,12>>^ Porque, naquela noite, passarei pela terra do Egito e matarei na terra do Egito todos os primogênitos, tanto das pessoas como dos animais, e executarei juízo sobre todos os deuses do Egito. Eu sou o Senhor .

[[v2-12-13]]

^<<v2-12-13,13>>^ — O sangue será um sinal para indicar as casas em que vocês se encontram. Quando eu vir o sangue, passarei por vocês, e não haverá entre vocês praga destruidora, quando eu ferir a terra do Egito.

[[v2-12-14]]

^<<v2-12-14,14>>^ Este dia lhes será por memorial, e vocês o celebrarão como festa ao Senhor ; de geração em geração vocês celebrarão este dia por estatuto perpétuo.

[[v2-12-15]]

^<<v2-12-15,15>>^ — Sete dias vocês comerão pães sem fermento. Logo no primeiro dia, tirem o fermento das suas casas, pois todo aquele que comer coisa levedada, desde o primeiro dia até o sétimo dia, será eliminado de Israel.

[[v2-12-16]]

^<<v2-12-16,16>>^ No primeiro dia vocês terão uma santa convocação, e também no sétimo dia terão santa convocação. Não façam nenhum trabalho nesses dias, exceto o que diz respeito ao comer; somente isso poderão fazer.

[[v2-12-17]]

^<<v2-12-17,17>>^ Guardem a Festa dos Pães sem Fermento, porque nesse mesmo dia tirei os exércitos de vocês da terra do Egito. Portanto, vocês guardarão este dia de geração em geração por estatuto perpétuo.

[[v2-12-18]]

^<<v2-12-18,18>>^ Vocês comerão pães sem fermento desde o dia catorze do primeiro mês, à tarde, até a tarde do dia vinte e um do mesmo mês.

[[v2-12-19]]

^<<v2-12-19,19>>^ Por sete dias, não se ache nenhum fermento em suas casas, porque todo aquele que comer pão levedado será eliminado da congregação de Israel, tanto o estrangeiro como o natural da terra.

[[v2-12-20]]

^<<v2-12-20,20>>^ Não comam nada que tenha fermento. Em todas as suas habitações, comam somente pães sem fermento.

[[v2-12-21]]

^<<v2-12-21,21>>^ Moisés chamou todos os anciãos de Israel e lhes disse: — Escolham e peguem cordeiros para as famílias de vocês, e matem esses animais para celebrar a Páscoa.

[[v2-12-22]]

^<<v2-12-22,22>>^ Peguem ramos de hissopo, molhem no sangue que estiver na bacia e marquem a viga superior da porta e suas ombreiras com o sangue que estiver na bacia. E que nenhum de vocês saia da porta da sua casa até pela manhã.

[[v2-12-23]]

^<<v2-12-23,23>>^ Porque o Senhor  passará para matar os egípcios. Quando, porém, enxergar o sangue na viga superior da porta e em ambas as ombreiras, o Senhor  passará por cima da porta e não permitirá que o Destruidor entre na casa de vocês para matá-los.

[[v2-12-24]]

^<<v2-12-24,24>>^ Portanto, guardem isto por estatuto para vocês e para os seus filhos, para sempre.

[[v2-12-25]]

^<<v2-12-25,25>>^ E, quando estiverem na terra que o Senhor  lhes dará, como prometeu, observem este rito.

[[v2-12-26]]

^<<v2-12-26,26>>^ Quando os seus filhos perguntarem: "Que rito é este?",

[[v2-12-27]]

^<<v2-12-27,27>>^ respondam: "É o sacrifício da Páscoa ao Senhor , que passou por cima das casas dos filhos de Israel no Egito, quando matou os egípcios e livrou as nossas casas." Então o povo se inclinou e adorou.

[[v2-12-28]]

^<<v2-12-28,28>>^ E os filhos de Israel foram e fizeram como o Senhor  havia ordenado a Moisés e Arão.

[[v2-12-29]]

^<<v2-12-29,29>>^ Aconteceu que, à meia-noite, o Senhor  matou todos os primogênitos na terra do Egito, desde o primogênito de Faraó, que se assentava no seu trono, até o primogênito do prisioneiro que estava na cadeia, e todos os primogênitos dos animais.

[[v2-12-30]]

^<<v2-12-30,30>>^ Faraó levantou-se de noite, ele, todos os seus oficiais e todos os egípcios; e houve grande clamor no Egito, pois não havia casa em que não houvesse um morto.

[[v2-12-31]]

^<<v2-12-31,31>>^ Então, naquela mesma noite, Faraó chamou Moisés e Arão e lhes disse: — Levantem-se e saiam do meio do meu povo, vocês e os filhos de Israel! Vão e adorem o Senhor , como vocês disseram.

[[v2-12-32]]

^<<v2-12-32,32>>^ Levem também com vocês as suas ovelhas e o seu gado, como vocês pediram. Vão embora e abençoem também a mim.

[[v2-12-33]]

^<<v2-12-33,33>>^ Os egípcios insistiram com o povo para que saísse da terra o mais depressa possível, pois diziam: — Todos vamos morrer.

[[v2-12-34]]

^<<v2-12-34,34>>^ O povo pegou a sua massa de pão, antes que levedasse, e as suas amassadeiras atadas em trouxas com as suas roupas, sobre os ombros.

[[v2-12-35]]

^<<v2-12-35,35>>^ Os filhos de Israel fizeram conforme a palavra de Moisés e pediram aos egípcios objetos de prata, objetos de ouro e roupas.

[[v2-12-36]]

^<<v2-12-36,36>>^ E o Senhor  fez com que o seu povo encontrasse favor da parte dos egípcios, de maneira que estes lhes davam o que pediam. E despojaram os egípcios.

[[v2-12-37]]

^<<v2-12-37,37>>^ Assim, os filhos de Israel partiram de Ramessés para Sucote. Eram cerca de seiscentos mil a pé, somente de homens, sem contar mulheres e crianças.

[[v2-12-38]]

^<<v2-12-38,38>>^ Saiu também com eles um misto de gente, ovelhas, gado, muitos animais.

[[v2-12-39]]

^<<v2-12-39,39>>^ E assaram pães sem fermento da massa que levaram do Egito, pois a massa não tinha levedado, porque eles foram expulsos do Egito. Não puderam deter-se e não haviam preparado para si provisões.

[[v2-12-40]]

^<<v2-12-40,40>>^ Ora, o tempo que os filhos de Israel habitaram no Egito foi de quatrocentos e trinta anos.

[[v2-12-41]]

^<<v2-12-41,41>>^ Aconteceu que, ao final dos quatrocentos e trinta anos, nesse mesmo dia, todos os exércitos do Senhor  saíram da terra do Egito.

[[v2-12-42]]

^<<v2-12-42,42>>^ Esta noite será dedicada ao Senhor , porque, nela, os tirou da terra do Egito. Esta é a noite do Senhor , que todos os filhos de Israel devem comemorar de geração em geração.

[[v2-12-43]]

^<<v2-12-43,43>>^ O Senhor  disse a Moisés e a Arão: — Esta é a ordenança da Páscoa: nenhum estrangeiro comerá dela.

[[v2-12-44]]

^<<v2-12-44,44>>^ Porém todo escravo comprado por dinheiro, depois de ser circuncidado, comerá da Páscoa.

[[v2-12-45]]

^<<v2-12-45,45>>^ O estrangeiro e o assalariado não comerão dela.

[[v2-12-46]]

^<<v2-12-46,46>>^ O cordeiro deverá ser comido numa só casa. Não levem nada da carne para fora da casa nem lhe quebrem osso nenhum.

[[v2-12-47]]

^<<v2-12-47,47>>^ Toda a congregação de Israel o fará.

[[v2-12-48]]

^<<v2-12-48,48>>^ Porém, se algum estrangeiro se hospedar com você e quiser celebrar a Páscoa do Senhor , que primeiro sejam circuncidadas todas as pessoas do sexo masculino; depois poderá observar a Páscoa, e será como o natural da terra; mas nenhum incircunciso comerá dela.

[[v2-12-49]]

^<<v2-12-49,49>>^ A mesma lei será aplicada ao natural da terra e ao estrangeiro que estiver entre vocês.

[[v2-12-50]]

^<<v2-12-50,50>>^ Assim fizeram todos os filhos de Israel; como o Senhor  havia ordenado a Moisés e a Arão, assim fizeram.

[[v2-12-51]]

^<<v2-12-51,51>>^ Naquele mesmo dia o Senhor  tirou os filhos de Israel do Egito, segundo os seus exércitos.

'''

xref:002-exodo/002-exodo-011.adoc#v2-11-0[&#60; Capítulo Anterior] | <<v2-12-0,Topo>> | xref:002-exodo/002-exodo-013.adoc#v2-13-0[Próximo Capítulo &#62;]