include::./index.adoc[]

[[v2-1-0]]
=== Êxodo, 1
// naa ?, NAA - Nova Almeida Atualizada

[[v2-1-1]]

^<<v2-1-1,1>>^ São estes os nomes dos filhos de Israel que entraram com Jacó no Egito, cada um com a sua família:

[[v2-1-2]]

^<<v2-1-2,2>>^ Rúben, Simeão, Levi e Judá,

[[v2-1-3]]

^<<v2-1-3,3>>^ Issacar, Zebulom e Benjamim,

[[v2-1-4]]

^<<v2-1-4,4>>^ Dã, Naftali, Gade e Aser.

[[v2-1-5]]

^<<v2-1-5,5>>^ Todos os descendentes diretos de Jacó foram setenta; José, porém, já estava no Egito.

[[v2-1-6]]

^<<v2-1-6,6>>^ Com o tempo morreram José, todos os seus irmãos e toda aquela geração.

[[v2-1-7]]

^<<v2-1-7,7>>^ Mas os filhos de Israel foram fecundos, aumentaram muito, se multiplicaram e se tornaram extremamente fortes, de maneira que a terra se encheu deles.

[[v2-1-8]]

^<<v2-1-8,8>>^ Nesse meio-tempo, levantou-se um novo rei sobre o Egito, que não havia conhecido José.

[[v2-1-9]]

^<<v2-1-9,9>>^ Ele disse ao seu povo: — Eis que o povo dos filhos de Israel é mais numeroso e mais forte do que nós.

[[v2-1-10]]

^<<v2-1-10,10>>^ Vejam! Precisamos usar de astúcia para com esse povo, para que não se multiplique, e para evitar que, em caso de guerra, ele se alie aos nossos inimigos, lute contra nós e saia da terra.

[[v2-1-11]]

^<<v2-1-11,11>>^ E os egípcios puseram sobre eles feitores de obras, para os afligir com trabalhos pesados. E assim os israelitas construíram para Faraó as cidades-celeiros de Pitom e Ramessés.

[[v2-1-12]]

^<<v2-1-12,12>>^ Mas quanto mais os afligiam, tanto mais se multiplicavam e tanto mais se espalhavam, de maneira que os egípcios se inquietavam por causa dos filhos de Israel.

[[v2-1-13]]

^<<v2-1-13,13>>^ Então os egípcios, com tirania, escravizaram os filhos de Israel

[[v2-1-14]]

^<<v2-1-14,14>>^ e lhes amargaram a vida com dura servidão: preparar o barro, fabricar tijolos e fazer todo tipo de trabalho no campo. Todo este serviço lhes era imposto com tirania.

[[v2-1-15]]

^<<v2-1-15,15>>^ O rei do Egito deu uma ordem às parteiras hebreias, das quais uma se chamava Sifrá e a outra se chamava Puá.

[[v2-1-16]]

^<<v2-1-16,16>>^ Ele disse: — Quando vocês servirem de parteira às mulheres hebreias, verifiquem se é menino ou menina; se for menino, matem; se for menina, deixem viver.

[[v2-1-17]]

^<<v2-1-17,17>>^ As parteiras, porém, temeram a Deus e não fizeram o que o rei do Egito lhes havia ordenado; pelo contrário, deixaram viver os meninos.

[[v2-1-18]]

^<<v2-1-18,18>>^ Então o rei do Egito chamou as parteiras e lhes perguntou: — Por que vocês fizeram isso e deixaram viver os meninos?

[[v2-1-19]]

^<<v2-1-19,19>>^ As parteiras responderam a Faraó: — É que as mulheres hebreias não são como as egípcias; são vigorosas e dão à luz antes que a parteira chegue.

[[v2-1-20]]

^<<v2-1-20,20>>^ E Deus foi bom para as parteiras; e o povo aumentou e se tornou muito forte.

[[v2-1-21]]

^<<v2-1-21,21>>^ E, porque as parteiras temeram a Deus, ele lhes constituiu família.

[[v2-1-22]]

^<<v2-1-22,22>>^ Então Faraó deu ordem a todo o seu povo, dizendo: — Joguem no rio Nilo todos os meninos hebreus que nascerem; quanto às meninas, deixem viver.

'''

xref:001-genesis/001-genesis-050.adoc#v1-50-0[&#60; Capítulo Anterior] | <<v2-1-0,Topo>> | xref:002-exodo/002-exodo-002.adoc#v2-2-0[Próximo Capítulo &#62;]