include::./index.adoc[]

[[v2-16-0]]
=== Êxodo, 16
// naa ?, NAA - Nova Almeida Atualizada

[[v2-16-1]]

^<<v2-16-1,1>>^ Partiram de Elim, e toda a congregação dos filhos de Israel veio para o deserto de Sim, que está entre Elim e Sinai, aos quinze dias do segundo mês, depois que saíram da terra do Egito.

[[v2-16-2]]

^<<v2-16-2,2>>^ Toda a congregação dos filhos de Israel murmurou contra Moisés e Arão no deserto.

[[v2-16-3]]

^<<v2-16-3,3>>^ Os filhos de Israel disseram a Moisés e Arão: — Quem nos dera tivéssemos morrido pela mão do Senhor  na terra do Egito, quando estávamos sentados junto às panelas de carne e comíamos pão à vontade! Pois vocês nos trouxeram a este deserto a fim de matarem de fome toda esta multidão.

[[v2-16-4]]

^<<v2-16-4,4>>^ Então o Senhor  disse a Moisés: — Eis que farei chover do céu pão para vocês, e o povo sairá e recolherá diariamente a porção para cada dia. Eu os porei à prova para ver se andam na minha lei ou não.

[[v2-16-5]]

^<<v2-16-5,5>>^ No sexto dia prepararão o que recolherem, e será o dobro do que recolhem nos outros dias.

[[v2-16-6]]

^<<v2-16-6,6>>^ Então Moisés e Arão disseram a todos os filhos de Israel: — Hoje à tarde vocês saberão que foi o Senhor  quem os tirou da terra do Egito,

[[v2-16-7]]

^<<v2-16-7,7>>^ e, pela manhã, vocês verão a glória do Senhor , porque ele ouviu as murmurações de vocês contra o Senhor . Pois quem somos nós, para que vocês fiquem murmurando contra nós?

[[v2-16-8]]

^<<v2-16-8,8>>^ Moisés continuou: — Isso acontecerá quando o Senhor , à tarde, lhes der carne para comer e, pela manhã, pão à vontade, porque o Senhor  ouviu as murmurações, com que vocês se queixam contra ele. Pois quem somos nós? Vocês não estão murmurando contra nós, mas contra o Senhor .

[[v2-16-9]]

^<<v2-16-9,9>>^ Então Moisés disse a Arão: — Diga a toda a congregação dos filhos de Israel: "Cheguem-se à presença do Senhor , pois ele ouviu as murmurações de vocês."

[[v2-16-10]]

^<<v2-16-10,10>>^ Enquanto Arão falava a toda a congregação dos filhos de Israel, olharam para o deserto, e eis que a glória do Senhor  apareceu na nuvem.

[[v2-16-11]]

^<<v2-16-11,11>>^ E o Senhor  disse a Moisés:

[[v2-16-12]]

^<<v2-16-12,12>>^ — Tenho ouvido as murmurações dos filhos de Israel. Diga-lhes: "Ao crepúsculo da tarde, vocês comerão carne, e, pela manhã, vocês comerão pão à vontade, e saberão que eu sou o Senhor , seu Deus."

[[v2-16-13]]

^<<v2-16-13,13>>^ À tarde, apareceram codornizes e cobriram o arraial. Pela manhã, havia orvalho ao redor do arraial.

[[v2-16-14]]

^<<v2-16-14,14>>^ E, quando o orvalho que havia caído se evaporou, na superfície do deserto restava uma coisa fina e semelhante a escamas, fina como a geada sobre a terra.

[[v2-16-15]]

^<<v2-16-15,15>>^ Quando os filhos de Israel viram aquilo, perguntaram uns aos outros: — Que é isso? Pois não sabiam o que era. Moisés respondeu: — Isso é o pão que o Senhor  dá a vocês para comerem.

[[v2-16-16]]

^<<v2-16-16,16>>^ Isto é o que o Senhor  ordenou: "Que cada um recolha o que se consegue comer: dois litros por cabeça, segundo o número de pessoas. Cada um pegará para todos os que vivem em sua tenda."

[[v2-16-17]]

^<<v2-16-17,17>>^ Assim o fizeram os filhos de Israel. E recolheram, uns, mais, outros, menos,

[[v2-16-18]]

^<<v2-16-18,18>>^ conforme a medida fixada. E não sobrava para quem havia recolhido muito, nem faltava para quem havia recolhido pouco, pois cada um recolhia o quanto conseguia comer.

[[v2-16-19]]

^<<v2-16-19,19>>^ Então Moisés disse: — Ninguém deixe nada para a manhã seguinte.

[[v2-16-20]]

^<<v2-16-20,20>>^ Eles, porém, não deram ouvidos a Moisés, e alguns deixaram do maná para a manhã seguinte, mas deu bichos e cheirava mal. E Moisés se indignou contra eles.

[[v2-16-21]]

^<<v2-16-21,21>>^ Colhiam-no, pois, manhã após manhã, cada um quanto conseguia comer; porque, vindo o calor do sol, o maná se derretia.

[[v2-16-22]]

^<<v2-16-22,22>>^ No sexto dia, colheram alimento em dobro, quatro litros para cada um. E os principais da congregação vieram e contaram isso a Moisés.

[[v2-16-23]]

^<<v2-16-23,23>>^ Ele respondeu: — Isto é o que disse o Senhor : "Amanhã é repouso, o santo sábado dedicado ao Senhor . O que vocês quiserem assar no forno, assem, e o que quiserem cozinhar em água, cozinhem; e tudo o que sobrar separem, guardando para a manhã seguinte."

[[v2-16-24]]

^<<v2-16-24,24>>^ E guardaram-no até a manhã seguinte, como Moisés havia ordenado; e não cheirou mal, nem deu bichos.

[[v2-16-25]]

^<<v2-16-25,25>>^ Então Moisés disse: — Comam isto hoje, pois hoje é o sábado dedicado ao Senhor ; hoje vocês não encontrarão nada no campo.

[[v2-16-26]]

^<<v2-16-26,26>>^ Seis dias vocês o recolherão, mas o sétimo dia é o sábado; nele, não haverá nada a recolher.

[[v2-16-27]]

^<<v2-16-27,27>>^ No sétimo dia algumas pessoas saíram para o recolher, porém não o acharam.

[[v2-16-28]]

^<<v2-16-28,28>>^ Então o Senhor  disse a Moisés: — Até quando vocês se recusarão a guardar os meus mandamentos e as minhas leis?

[[v2-16-29]]

^<<v2-16-29,29>>^ Vejam! O Senhor  deu a vocês o sábado; por isso, ele, no sexto dia, lhes dá alimento para dois dias; cada um fique onde está, ninguém saia do seu lugar no sétimo dia.

[[v2-16-30]]

^<<v2-16-30,30>>^ Assim, o povo descansou no sétimo dia.

[[v2-16-31]]

^<<v2-16-31,31>>^ A casa de Israel deu àquele alimento o nome de maná. Ele era como semente de coentro, branco e com gosto de bolo de mel.

[[v2-16-32]]

^<<v2-16-32,32>>^ Moisés disse: — Esta é a palavra que o Senhor  ordenou: "Dele você pegará dois litros e guardará para as futuras gerações, para que vejam o pão com que eu os sustentei no deserto, quando os tirei do Egito."

[[v2-16-33]]

^<<v2-16-33,33>>^ Então Moisés disse a Arão: — Pegue um vaso, ponha nele dois litros de maná e coloque-o diante do Senhor , para que seja guardado para as futuras gerações.

[[v2-16-34]]

^<<v2-16-34,34>>^ Como o Senhor  havia ordenado a Moisés, assim Arão o colocou diante da arca do testemunho para o guardar.

[[v2-16-35]]

^<<v2-16-35,35>>^ E os filhos de Israel comeram maná durante quarenta anos, até que entraram em terra habitada. Comeram maná até que chegaram aos limites da terra de Canaã.

[[v2-16-36]]

^<<v2-16-36,36>>^ A porção de maná para cada pessoa era um décimo da medida padrão, que tinha vinte litros.

'''

xref:002-exodo/002-exodo-015.adoc#v2-15-0[&#60; Capítulo Anterior] | <<v2-16-0,Topo>> | xref:002-exodo/002-exodo-017.adoc#v2-17-0[Próximo Capítulo &#62;]