include::./index.adoc[]

[[v2-31-0]]
=== Êxodo, 31
// naa ?, NAA - Nova Almeida Atualizada

[[v2-31-1]]

^<<v2-31-1,1>>^ O Senhor  disse mais a Moisés:

[[v2-31-2]]

^<<v2-31-2,2>>^ — Eis que chamei pelo nome Bezalel, filho de Uri, filho de Hur, da tribo de Judá,

[[v2-31-3]]

^<<v2-31-3,3>>^ e o enchi do Espírito de Deus, de habilidade, de inteligência e de conhecimento, em todo artifício,

[[v2-31-4]]

^<<v2-31-4,4>>^ para elaborar desenhos e trabalhar em ouro, prata e bronze,

[[v2-31-5]]

^<<v2-31-5,5>>^ para lapidação de pedras de engaste, para entalho de madeira, para todo tipo de trabalho artesanal.

[[v2-31-6]]

^<<v2-31-6,6>>^ Escolhi Aoliabe, filho de Aisamaque, da tribo de Dã, para trabalhar com ele. Também dei habilidade a todos os homens hábeis, para que me façam tudo o que tenho ordenado:

[[v2-31-7]]

^<<v2-31-7,7>>^ a tenda do encontro, a arca do testemunho, o propiciatório que está por cima dela e todos os pertences da tenda;

[[v2-31-8]]

^<<v2-31-8,8>>^ a mesa com os seus utensílios, o candelabro de ouro puro com todos os seus utensílios e o altar do incenso;

[[v2-31-9]]

^<<v2-31-9,9>>^ o altar do holocausto com todos os seus utensílios e a bacia com o seu suporte;

[[v2-31-10]]

^<<v2-31-10,10>>^ as vestes finamente tecidas, as vestes sagradas do sacerdote Arão e as vestes de seus filhos, para servirem como sacerdotes;

[[v2-31-11]]

^<<v2-31-11,11>>^ o óleo da unção e o incenso aromático para o santuário; eles farão tudo segundo tenho ordenado.

[[v2-31-12]]

^<<v2-31-12,12>>^ Disse mais o Senhor  a Moisés:

[[v2-31-13]]

^<<v2-31-13,13>>^ — Fale aos filhos de Israel e diga-lhes o seguinte: "Certamente vocês guardarão os meus sábados, pois é sinal entre mim e vocês de geração em geração, para que vocês saibam que eu sou o Senhor , que os santifica.

[[v2-31-14]]

^<<v2-31-14,14>>^ Portanto, guardem o sábado, porque é santo para vocês. Aquele que o profanar morrerá; quem nesse dia fizer alguma obra será eliminado do meio do seu povo.

[[v2-31-15]]

^<<v2-31-15,15>>^ Seis dias se trabalhará, porém o sétimo dia é o sábado do repouso solene, santo ao Senhor ; quem fizer alguma obra no dia do sábado morrerá.

[[v2-31-16]]

^<<v2-31-16,16>>^ Os filhos de Israel guardarão o sábado, celebrando-o por aliança perpétua de geração em geração.

[[v2-31-17]]

^<<v2-31-17,17>>^ Entre mim e os filhos de Israel é sinal para sempre; porque, em seis dias, o Senhor  fez os céus e a terra e, no sétimo dia, descansou e tomou alento."

[[v2-31-18]]

^<<v2-31-18,18>>^ Quando o Senhor  acabou de falar com Moisés no monte Sinai, deu a ele as duas tábuas do testemunho, tábuas de pedra, escritas pelo dedo de Deus.

'''

xref:002-exodo/002-exodo-030.adoc#v2-30-0[&#60; Capítulo Anterior] | <<v2-31-0,Topo>> | xref:002-exodo/002-exodo-032.adoc#v2-32-0[Próximo Capítulo &#62;]