include::./index.adoc[]

[[v2-33-0]]
=== Êxodo, 33
// naa ?, NAA - Nova Almeida Atualizada

[[v2-33-1]]

^<<v2-33-1,1>>^ O Senhor  disse a Moisés: — Suba deste lugar, você e o povo que você tirou da terra do Egito, e vá para a terra a respeito da qual jurei a Abraão, a Isaque e a Jacó, dizendo: "Eu a darei à sua descendência."

[[v2-33-2]]

^<<v2-33-2,2>>^ Enviarei o Anjo adiante de você e expulsarei os cananeus, os amorreus, os heteus, os ferezeus, os heveus e os jebuseus.

[[v2-33-3]]

^<<v2-33-3,3>>^ Vão para uma terra que mana leite e mel. Eu não irei no meio de vocês, porque vocês são um povo teimoso, para que eu não os destrua no caminho.

[[v2-33-4]]

^<<v2-33-4,4>>^ Quando o povo ouviu estas más notícias, pôs-se a prantear, e nenhum deles usou as suas joias.

[[v2-33-5]]

^<<v2-33-5,5>>^ Porque o Senhor  tinha dito a Moisés: "Diga aos filhos de Israel: ‘Vocês são um povo teimoso. Se eu fosse com vocês, ainda que por um momento, eu os destruiria. Portanto, tirem as suas joias, para que eu saiba o que hei de fazer com vocês.’"

[[v2-33-6]]

^<<v2-33-6,6>>^ Então os filhos de Israel tiraram de si as suas joias desde o monte Horebe em diante.

[[v2-33-7]]

^<<v2-33-7,7>>^ Ora, Moisés costumava pegar a tenda e armá-la para si, fora, bem longe do arraial. Ele a chamava de "tenda do encontro". Todo aquele que buscava o Senhor  saía à tenda do encontro, que estava fora do arraial.

[[v2-33-8]]

^<<v2-33-8,8>>^ Quando Moisés saía para a tenda, fora, todo o povo se erguia, cada um em pé à porta da sua tenda, e seguiam-no com os olhos, até ele entrar na tenda.

[[v2-33-9]]

^<<v2-33-9,9>>^ Quando Moisés entrava na tenda, descia a coluna de nuvem e punha-se à porta da tenda; e o Senhor  falava com Moisés.

[[v2-33-10]]

^<<v2-33-10,10>>^ Todo o povo via a coluna de nuvem que se detinha à porta da tenda; todo o povo se levantava, e cada um, à porta da sua tenda, adorava o Senhor .

[[v2-33-11]]

^<<v2-33-11,11>>^ O Senhor  falava com Moisés face a face, como quem fala com o seu amigo. Depois Moisés voltava para o arraial. Porém o moço Josué, seu auxiliar, filho de Num, não se afastava da tenda.

[[v2-33-12]]

^<<v2-33-12,12>>^ Moisés disse ao Senhor : — Eis que me dizes para conduzir este povo, mas não me disseste quem enviarás comigo. Disseste: "Eu conheço você pelo nome e você alcançou favor diante de mim."

[[v2-33-13]]

^<<v2-33-13,13>>^ Agora, se alcancei favor diante de ti, peço que me faças saber neste momento o teu caminho, para que eu te conheça e obtenha favor diante de ti; e lembra-te que esta nação é teu povo.

[[v2-33-14]]

^<<v2-33-14,14>>^ Deus respondeu: — A minha presença irá com você, e eu lhe darei descanso.

[[v2-33-15]]

^<<v2-33-15,15>>^ Então Moisés disse: — Se a tua presença não for comigo, não nos faças sair deste lugar.

[[v2-33-16]]

^<<v2-33-16,16>>^ Pois como se poderá saber que alcançamos favor diante de ti, eu e o teu povo? Será que não é o fato de andares conosco, de maneira que somos separados, eu e o teu povo, de todos os povos da terra?

[[v2-33-17]]

^<<v2-33-17,17>>^ O Senhor  disse a Moisés: — Farei também isto que você falou, porque você alcançou favor diante de mim, e eu o conheço pelo nome.

[[v2-33-18]]

^<<v2-33-18,18>>^ Então Moisés disse: — Peço que me mostres a tua glória.

[[v2-33-19]]

^<<v2-33-19,19>>^ O Senhor  respondeu: — Farei passar toda a minha bondade diante de você e lhe proclamarei o nome do Senhor ; terei misericórdia de quem eu tiver misericórdia e me compadecerei de quem eu me compadecer.

[[v2-33-20]]

^<<v2-33-20,20>>^ E acrescentou: — Você não poderá ver a minha face, porque ninguém verá a minha face e viverá.

[[v2-33-21]]

^<<v2-33-21,21>>^ Disse mais o Senhor : — Eis aqui um lugar perto de mim, onde você ficará sobre a rocha.

[[v2-33-22]]

^<<v2-33-22,22>>^ Quando a minha glória passar, eu porei você numa fenda da rocha e o cobrirei com a mão, até que eu tenha passado.

[[v2-33-23]]

^<<v2-33-23,23>>^ Depois, quando eu tirar a mão, você me verá pelas costas; mas a minha face ninguém verá.

'''

xref:002-exodo/002-exodo-032.adoc#v2-32-0[&#60; Capítulo Anterior] | <<v2-33-0,Topo>> | xref:002-exodo/002-exodo-034.adoc#v2-34-0[Próximo Capítulo &#62;]