include::./index.adoc[]

[[v2-23-0]]
=== Êxodo, 23
// naa ?, NAA - Nova Almeida Atualizada

[[v2-23-1]]

^<<v2-23-1,1>>^ — Não espalhe notícias falsas e não entre em acordo com o ímpio, para ser testemunha maldosa.

[[v2-23-2]]

^<<v2-23-2,2>>^ Não siga a multidão para fazer o mal e, num processo, não deponha com a maioria, para torcer a justiça.

[[v2-23-3]]

^<<v2-23-3,3>>^ Não seja parcial nem mesmo com o pobre nas suas demandas.

[[v2-23-4]]

^<<v2-23-4,4>>^ — Se você encontrar desgarrado o boi ou o jumento do seu inimigo, leve-o sem falta de volta para ele.

[[v2-23-5]]

^<<v2-23-5,5>>^ Se você vir prostrado debaixo da sua carga o jumento daquele que odeia você, não o abandone, mas ajude o dono a erguer o animal.

[[v2-23-6]]

^<<v2-23-6,6>>^ — Não perverta o direito do pobre que vem até você com a sua causa.

[[v2-23-7]]

^<<v2-23-7,7>>^ Fique longe da falsa acusação. Não mate o inocente e o justo, porque não justificarei o ímpio.

[[v2-23-8]]

^<<v2-23-8,8>>^ Não aceite suborno, porque o suborno cega até o perspicaz e perverte as palavras dos justos.

[[v2-23-9]]

^<<v2-23-9,9>>^ — Não oprima o estrangeiro; vocês sabem o que é ser estrangeiro, pois foram estrangeiros na terra do Egito.

[[v2-23-10]]

^<<v2-23-10,10>>^ — Durante seis anos você semeará a sua terra e recolherá os seus frutos.

[[v2-23-11]]

^<<v2-23-11,11>>^ Porém, no sétimo ano, deixe a terra descansar e não a cultive, para que os pobres do seu povo achem o que comer e os animais do campo comam do que sobrar. Faça o mesmo com a sua vinha e com o seu olival.

[[v2-23-12]]

^<<v2-23-12,12>>^ — Seis dias você fará o seu trabalho, mas, no sétimo dia, descanse, para que descanse também o seu boi e o seu jumento, e para que o filho da sua escrava e o estrangeiro se revigorem.

[[v2-23-13]]

^<<v2-23-13,13>>^ — Deem atenção a tudo o que eu tenho dito a vocês. O nome de outros deuses não deve ser lembrado nem pronunciado por vocês.

[[v2-23-14]]

^<<v2-23-14,14>>^ — Três vezes no ano celebrem uma festa para mim.

[[v2-23-15]]

^<<v2-23-15,15>>^ Celebrem a Festa dos Pães sem Fermento; durante sete dias vocês comerão pães sem fermento, como ordenei a vocês. Façam isso no tempo indicado no mês de abibe, porque nesse mês vocês saíram do Egito. Ninguém apareça diante de mim de mãos vazias.

[[v2-23-16]]

^<<v2-23-16,16>>^ Celebrem a Festa da Ceifa, dos primeiros frutos do seu trabalho, do que vocês semeiam no campo, e a Festa da Colheita, ao final do ano, quando vocês recolhem do campo o fruto do seu trabalho.

[[v2-23-17]]

^<<v2-23-17,17>>^ Três vezes por ano, todo homem deve comparecer diante do Senhor  Deus.

[[v2-23-18]]

^<<v2-23-18,18>>^ — Não ofereçam o sangue do meu sacrifício com pão fermentado, nem deixem que a gordura da minha festa fique durante a noite até a manhã seguinte.

[[v2-23-19]]

^<<v2-23-19,19>>^ Tragam as primícias dos frutos de sua terra à casa do Senhor , seu Deus. Não cozinhem o cabrito no leite da sua própria mãe.

[[v2-23-20]]

^<<v2-23-20,20>>^ — Eis que eu envio um Anjo adiante de vocês, para que os guarde pelo caminho e os leve ao lugar que tenho preparado.

[[v2-23-21]]

^<<v2-23-21,21>>^ Deem atenção a ele e ouçam o que ele diz. Não se rebelem contra ele, porque não perdoará a transgressão de vocês; pois nele está o meu nome.

[[v2-23-22]]

^<<v2-23-22,22>>^ Mas, se vocês ouvirem atentamente o que ele disser e fizerem tudo o que eu ordeno, então serei inimigo dos que são inimigos de vocês e adversário dos que são adversários de vocês.

[[v2-23-23]]

^<<v2-23-23,23>>^ Porque o meu Anjo irá adiante de vocês e os levará aos amorreus, aos heteus, aos ferezeus, aos cananeus, aos heveus e aos jebuseus; e eu os destruirei.

[[v2-23-24]]

^<<v2-23-24,24>>^ Não se curvem diante dos deuses deles, nem os adorem, nem sigam os costumes deles; pelo contrário, destruam totalmente esses ídolos e despedacem as suas colunas.

[[v2-23-25]]

^<<v2-23-25,25>>^ Adorem o Senhor , o Deus de vocês, e ele abençoará o pão e a água de vocês. Tirarei as enfermidades do meio de vocês.

[[v2-23-26]]

^<<v2-23-26,26>>^ Na sua terra não haverá mulher que aborte, nem estéril. Darei a vocês uma vida longa.

[[v2-23-27]]

^<<v2-23-27,27>>^ — Enviarei o meu terror diante de vocês, confundindo todos os povos que vocês encontrarem. Farei com que todos os seus inimigos virem as costas e fujam de vocês.

[[v2-23-28]]

^<<v2-23-28,28>>^ Também enviarei vespas diante de vocês, que expulsem os heveus, os cananeus e os heteus de diante de vocês.

[[v2-23-29]]

^<<v2-23-29,29>>^ Não os expulsarei de diante de vocês num só ano, para que a terra não se torne em desolação, e as feras do campo não se multipliquem contra vocês.

[[v2-23-30]]

^<<v2-23-30,30>>^ Pouco a pouco os expulsarei de diante de vocês, até que vocês se multipliquem e tomem posse da terra.

[[v2-23-31]]

^<<v2-23-31,31>>^ Porei as suas fronteiras desde o mar Vermelho até o mar dos filisteus e desde o deserto até o Eufrates; porque entregarei nas suas mãos os moradores da terra, para que vocês os expulsem de diante de vocês.

[[v2-23-32]]

^<<v2-23-32,32>>^ Não façam nenhuma aliança com eles, nem com os deuses deles.

[[v2-23-33]]

^<<v2-23-33,33>>^ Eles não habitarão na sua terra, para que não façam com que vocês pequem contra mim; se adorarem os deuses deles, isso será uma cilada para vocês.

'''

xref:002-exodo/002-exodo-022.adoc#v2-22-0[&#60; Capítulo Anterior] | <<v2-23-0,Topo>> | xref:002-exodo/002-exodo-024.adoc#v2-24-0[Próximo Capítulo &#62;]