include::./index.adoc[]

[[v2-34-0]]
=== Êxodo, 34
// naa ?, NAA - Nova Almeida Atualizada

[[v2-34-1]]

^<<v2-34-1,1>>^ Então o Senhor  disse a Moisés: — Corte duas tábuas de pedra, como as primeiras, e eu escreverei nelas as mesmas palavras que estavam nas primeiras tábuas, que você quebrou.

[[v2-34-2]]

^<<v2-34-2,2>>^ E prepare-se para amanhã, para que você suba, pela manhã, o monte Sinai e se apresente ali diante de mim no alto do monte.

[[v2-34-3]]

^<<v2-34-3,3>>^ Ninguém deverá subir com você, ninguém deverá aparecer em todo o monte; nem ainda ovelhas nem gado devem ser apascentados diante dele.

[[v2-34-4]]

^<<v2-34-4,4>>^ Então Moisés cortou duas tábuas de pedra, como as primeiras. E, levantando-se de madrugada, subiu o monte Sinai, como o Senhor  lhe havia ordenado, levando nas mãos as duas tábuas de pedra.

[[v2-34-5]]

^<<v2-34-5,5>>^ O Senhor  desceu na nuvem, esteve ali junto de Moisés e proclamou o nome do Senhor .

[[v2-34-6]]

^<<v2-34-6,6>>^ O Senhor  passou diante de Moisés e proclamou: — O Senhor ! O Senhor  Deus compassivo e bondoso, tardio em irar-se e grande em misericórdia e fidelidade;

[[v2-34-7]]

^<<v2-34-7,7>>^ que guarda a misericórdia em mil gerações, que perdoa a maldade, a transgressão e o pecado, ainda que não inocente o culpado, e visita a iniquidade dos pais nos filhos e nos filhos dos filhos, até a terceira e quarta geração!

[[v2-34-8]]

^<<v2-34-8,8>>^ E imediatamente Moisés curvou-se para a terra, adorou o Senhor

[[v2-34-9]]

^<<v2-34-9,9>>^ e disse: — Senhor, se agora alcancei favor diante de ti, continua no meio de nós; porque este povo é teimoso. Perdoa a nossa iniquidade e o nosso pecado e toma-nos por tua herança.

[[v2-34-10]]

^<<v2-34-10,10>>^ Então o Senhor  disse: — Eis que eu faço uma aliança. Diante de todo o seu povo farei maravilhas que nunca foram feitas em toda a terra, nem entre nação alguma, de maneira que todo este povo, em cujo meio você está, veja a obra do Senhor ; porque coisa terrível é o que faço com você.

[[v2-34-11]]

^<<v2-34-11,11>>^ — Observe o que hoje eu ordeno a vocês: eis que expulsarei da frente de vocês os amorreus, os cananeus, os heteus, os ferezeus, os heveus e os jebuseus.

[[v2-34-12]]

^<<v2-34-12,12>>^ Abstenham-se de fazer aliança com os moradores da terra para onde vocês vão, para que isso não seja uma armadilha no meio de vocês.

[[v2-34-13]]

^<<v2-34-13,13>>^ Pelo contrário, derrubem os altares deles, quebrem as suas colunas e cortem os postes da deusa Aserá.

[[v2-34-14]]

^<<v2-34-14,14>>^ Porque vocês não devem adorar outro deus; pois o nome do Senhor  é Zeloso; sim, ele é Deus zeloso.

[[v2-34-15]]

^<<v2-34-15,15>>^ Não façam aliança com os moradores da terra, para não acontecer que, em se prostituindo eles com os deuses e lhes sacrificando, alguém os convide, e vocês comam dos seus sacrifícios.

[[v2-34-16]]

^<<v2-34-16,16>>^ Também para que não aconteça que vocês escolham para os seus filhos mulheres do meio das filhas deles, e estas, ao se prostituírem com os deuses que adoram, façam com que também os seus filhos se prostituam com esses deuses.

[[v2-34-17]]

^<<v2-34-17,17>>^ — Não façam deuses de metal para vocês.

[[v2-34-18]]

^<<v2-34-18,18>>^ — Celebrem a Festa dos Pães sem Fermento. Durante sete dias vocês comerão pães sem fermento, como ordenei a vocês. Façam isso no tempo indicado no mês de abibe, porque nesse mês vocês saíram do Egito.

[[v2-34-19]]

^<<v2-34-19,19>>^ Todo o primeiro filho que nascer é meu. Também de todo o seu gado, o primeiro filhote macho de vacas e ovelhas é meu.

[[v2-34-20]]

^<<v2-34-20,20>>^ Mas o jumento que for a primeira cria, esse vocês podem resgatar com um cordeiro; se vocês não o resgatarem, ele deverá ser desnucado. Vocês devem resgatar todos os primogênitos de seus filhos. Ninguém aparecerá diante de mim de mãos vazias.

[[v2-34-21]]

^<<v2-34-21,21>>^ — Seis dias vocês trabalharão, mas no sétimo dia vocês descansarão. Mesmo no tempo de arar e de colher vocês deverão descansar.

[[v2-34-22]]

^<<v2-34-22,22>>^ — Celebrem também a Festa das Semanas, que é a festa das primícias da colheita do trigo, e a Festa da Colheita no fim do ano.

[[v2-34-23]]

^<<v2-34-23,23>>^ — Três vezes por ano, todo homem deve aparecer diante do soberano Senhor , o Deus de Israel.

[[v2-34-24]]

^<<v2-34-24,24>>^ Porque expulsarei as nações de diante de vocês e aumentarei o seu território; ninguém cobiçará a sua terra quando vocês comparecerem na presença do Senhor , seu Deus, três vezes por ano.

[[v2-34-25]]

^<<v2-34-25,25>>^ — Não ofereçam o sangue do meu sacrifício com pão levedado. O sacrifício da Festa da Páscoa não deve ficar da noite para a manhã do dia seguinte.

[[v2-34-26]]

^<<v2-34-26,26>>^ Tragam as primícias dos primeiros frutos da terra à casa do Senhor , seu Deus. Não cozinhem o cabrito no leite da sua própria mãe.

[[v2-34-27]]

^<<v2-34-27,27>>^ O Senhor  disse ainda a Moisés: — Escreva estas palavras, porque, segundo o teor destas palavras, fiz aliança com você e com Israel.

[[v2-34-28]]

^<<v2-34-28,28>>^ E Moisés esteve ali com o Senhor  quarenta dias e quarenta noites. Não comeu pão nem bebeu água. E escreveu nas tábuas as palavras da aliança, as dez palavras.

[[v2-34-29]]

^<<v2-34-29,29>>^ Quando Moisés desceu do monte Sinai, tendo nas mãos as duas tábuas do testemunho, sim, quando desceu do monte, Moisés não sabia que a pele do seu rosto resplandecia, depois de Deus ter falado com ele.

[[v2-34-30]]

^<<v2-34-30,30>>^ Quando Arão e todos os filhos de Israel olharam para Moisés, eis que a pele do seu rosto resplandecia; e ficaram com medo de chegar perto dele.

[[v2-34-31]]

^<<v2-34-31,31>>^ Então Moisés os chamou. Arão e todos os chefes da congregação foram até ele, e Moisés lhes falou.

[[v2-34-32]]

^<<v2-34-32,32>>^ Depois, vieram também todos os filhos de Israel, aos quais Moisés ordenou tudo o que o Senhor  lhe havia falado no monte Sinai.

[[v2-34-33]]

^<<v2-34-33,33>>^ Quando Moisés acabou de falar com eles, pôs um véu sobre o rosto.

[[v2-34-34]]

^<<v2-34-34,34>>^ Porém, quando Moisés vinha diante do Senhor  para falar-lhe, removia o véu até sair; e, saindo, dizia aos filhos de Israel tudo o que lhe tinha sido ordenado.

[[v2-34-35]]

^<<v2-34-35,35>>^ Assim, os filhos de Israel viam o rosto de Moisés, viam que a pele do seu rosto resplandecia; porém Moisés cobria de novo o rosto com o véu até entrar para falar com o Senhor .

'''

xref:002-exodo/002-exodo-033.adoc#v2-33-0[&#60; Capítulo Anterior] | <<v2-34-0,Topo>> | xref:002-exodo/002-exodo-035.adoc#v2-35-0[Próximo Capítulo &#62;]