include::./index.adoc[]

[[v2-14-0]]
=== Êxodo, 14
// naa ?, NAA - Nova Almeida Atualizada

[[v2-14-1]]

^<<v2-14-1,1>>^ O Senhor  disse a Moisés:

[[v2-14-2]]

^<<v2-14-2,2>>^ — Diga aos filhos de Israel que voltem e se acampem diante de Pi-Hairote, entre Migdol e o mar, diante de Baal-Zefom; em frente desse lugar, junto ao mar, vocês acamparão.

[[v2-14-3]]

^<<v2-14-3,3>>^ Então Faraó dirá a respeito dos filhos de Israel: "Estão desorientados na terra, presos no deserto."

[[v2-14-4]]

^<<v2-14-4,4>>^ Eu vou endurecer o coração de Faraó, para que os persiga, e serei glorificado em Faraó e em todo o seu exército. E os egípcios saberão que eu sou o Senhor . Eles assim o fizeram.

[[v2-14-5]]

^<<v2-14-5,5>>^ Quando foi anunciado ao rei do Egito que o povo fugia, ele e os seus oficiais mudaram de ideia a respeito do povo. Disseram: — Que é isto que fizemos, permitindo que Israel nos deixasse de servir?

[[v2-14-6]]

^<<v2-14-6,6>>^ E Faraó aprontou o seu carro de guerra e levou consigo o seu povo.

[[v2-14-7]]

^<<v2-14-7,7>>^ Levou também seiscentos carros de guerra escolhidos e todos os outros carros de guerra do Egito com capitães sobre todos eles.

[[v2-14-8]]

^<<v2-14-8,8>>^ Porque o Senhor  endureceu o coração de Faraó, rei do Egito, para que perseguisse os filhos de Israel. Porém os filhos de Israel saíram, marchando corajosamente.

[[v2-14-9]]

^<<v2-14-9,9>>^ Os egípcios os perseguiram, com todos os cavalos e carros de guerra de Faraó, os seus cavaleiros e o seu exército, e os alcançaram acampados junto ao mar, perto de Pi-Hairote, diante de Baal-Zefom.

[[v2-14-10]]

^<<v2-14-10,10>>^ E, chegando Faraó, os filhos de Israel levantaram os olhos e eis que os egípcios vinham atrás deles, e ficaram com muito medo. Então os filhos de Israel clamaram ao Senhor .

[[v2-14-11]]

^<<v2-14-11,11>>^ Disseram a Moisés: — Será que foi por não haver sepulturas no Egito que você nos tirou de lá, para que morramos neste deserto? O que foi que você fez conosco, tirando-nos do Egito?

[[v2-14-12]]

^<<v2-14-12,12>>^ Não foi isso que dissemos a você no Egito: "Deixe-nos em paz, para que sirvamos os egípcios"? Pois teria sido melhor para nós servir os egípcios do que morrer no deserto.

[[v2-14-13]]

^<<v2-14-13,13>>^ Moisés, porém, respondeu ao povo: — Não tenham medo; fiquem firmes e vejam o livramento que o Senhor  lhes fará no dia de hoje, porque vocês nunca mais verão esses egípcios que hoje vocês estão vendo.

[[v2-14-14]]

^<<v2-14-14,14>>^ O Senhor  lutará por vocês; fiquem calmos.

[[v2-14-15]]

^<<v2-14-15,15>>^ O Senhor  disse a Moisés: — Por que você está clamando a mim? Diga aos filhos de Israel que marchem.

[[v2-14-16]]

^<<v2-14-16,16>>^ E você, levante o seu bordão e estenda a mão sobre o mar. As águas se dividirão, para que os filhos de Israel passem pelo meio do mar em seco.

[[v2-14-17]]

^<<v2-14-17,17>>^ Eis que vou endurecer o coração dos egípcios, para que venham atrás de vocês e entrem no mar. Serei glorificado em Faraó e em todo o seu exército, nos seus carros de guerra e nos seus cavaleiros;

[[v2-14-18]]

^<<v2-14-18,18>>^ e os egípcios saberão que eu sou o Senhor , quando for glorificado em Faraó, nos seus carros de guerra e nos seus cavaleiros.

[[v2-14-19]]

^<<v2-14-19,19>>^ Então o Anjo de Deus, que ia adiante do exército de Israel, se retirou e passou para trás deles. Também a coluna de nuvem se retirou de diante deles, e se pôs atrás deles,

[[v2-14-20]]

^<<v2-14-20,20>>^ e ia entre o exército dos egípcios e o exército de Israel. A nuvem era escuridão para os egípcios, mas iluminava a noite para o povo de Israel, assim que, durante toda a noite, os dois exércitos não puderam se aproximar.

[[v2-14-21]]

^<<v2-14-21,21>>^ Então Moisés estendeu a mão sobre o mar, e o Senhor , por um forte vento leste que soprou toda aquela noite, fez com que o mar se retirasse, tornando-se terra seca, e as águas foram divididas.

[[v2-14-22]]

^<<v2-14-22,22>>^ Os filhos de Israel entraram pelo meio do mar em seco, e as águas foram qual muralha à direita e à esquerda deles.

[[v2-14-23]]

^<<v2-14-23,23>>^ Os egípcios que os perseguiam entraram atrás deles, todos os cavalos de Faraó, os seus carros de guerra e os seus cavaleiros, até o meio do mar.

[[v2-14-24]]

^<<v2-14-24,24>>^ Na vigília da manhã, o Senhor , na coluna de fogo e de nuvem, viu o acampamento dos egípcios e criou alvoroço no acampamento dos egípcios;

[[v2-14-25]]

^<<v2-14-25,25>>^ emperrou as rodas dos carros dos egípcios, fazendo com que andassem com dificuldade. Então os egípcios disseram: — Vamos fugir da presença de Israel, porque o Senhor  está lutando por eles contra os egípcios.

[[v2-14-26]]

^<<v2-14-26,26>>^ O Senhor  disse a Moisés: — Estenda a mão sobre o mar, para que as águas se voltem sobre os egípcios, sobre os seus carros de guerra e sobre os seus cavaleiros.

[[v2-14-27]]

^<<v2-14-27,27>>^ Então Moisés estendeu a mão sobre o mar, e o mar, ao romper da manhã, retomou a sua força. Os egípcios fugiram de encontro a ele, e o Senhor  jogou os egípcios para dentro do mar.

[[v2-14-28]]

^<<v2-14-28,28>>^ As águas voltaram e cobriram os carros de guerra e os cavaleiros de todo o exército de Faraó, que os haviam seguido no mar; nem ao menos um deles escapou com vida.

[[v2-14-29]]

^<<v2-14-29,29>>^ Mas os filhos de Israel caminhavam a pé enxuto pelo meio do mar; e as águas lhes eram quais muralhas, à sua direita e à sua esquerda.

[[v2-14-30]]

^<<v2-14-30,30>>^ Assim o Senhor  livrou Israel, naquele dia, das mãos dos egípcios; e Israel viu os egípcios mortos na praia do mar.

[[v2-14-31]]

^<<v2-14-31,31>>^ E Israel viu o grande poder que o Senhor  havia usado contra os egípcios; e o povo temeu o Senhor  e confiou no Senhor  e em Moisés, seu servo.

'''

xref:002-exodo/002-exodo-013.adoc#v2-13-0[&#60; Capítulo Anterior] | <<v2-14-0,Topo>> | xref:002-exodo/002-exodo-015.adoc#v2-15-0[Próximo Capítulo &#62;]