include::./index.adoc[]

[[v2-11-0]]
=== Êxodo, 11
// naa ?, NAA - Nova Almeida Atualizada

[[v2-11-1]]

^<<v2-11-1,1>>^ O Senhor  disse a Moisés: — Trarei só mais uma praga sobre Faraó e sobre o Egito. Então ele os deixará sair daqui. E, quando deixar que vocês saiam, é certo que ele os expulsará totalmente.

[[v2-11-2]]

^<<v2-11-2,2>>^ Fale, agora, aos ouvidos do povo que todo homem peça ao seu vizinho e que toda mulher peça à sua vizinha objetos de prata e de ouro.

[[v2-11-3]]

^<<v2-11-3,3>>^ E o Senhor  fez com que o seu povo encontrasse favor da parte dos egípcios. Além disso, o próprio Moisés era homem famoso na terra do Egito, aos olhos dos oficiais de Faraó e aos olhos do povo.

[[v2-11-4]]

^<<v2-11-4,4>>^ Moisés disse: — Assim diz o Senhor : "Perto da meia-noite passarei pelo meio do Egito.

[[v2-11-5]]

^<<v2-11-5,5>>^ E todo primogênito na terra do Egito morrerá, desde o primogênito de Faraó, que se assenta no seu trono, até o primogênito da escrava que mói a farinha, e todo primogênito dos animais.

[[v2-11-6]]

^<<v2-11-6,6>>^ Haverá grande clamor em toda a terra do Egito, como nunca houve antes, nem haverá jamais.

[[v2-11-7]]

^<<v2-11-7,7>>^ Porém contra nenhum dos filhos de Israel, desde os homens até os animais, nem mesmo um cão rosnará, para que vocês saibam que o Senhor  fez distinção entre os egípcios e os israelitas."

[[v2-11-8]]

^<<v2-11-8,8>>^ E Moisés continuou: — Então todos esses seus oficiais descerão a mim e se inclinarão diante de mim, dizendo: "Saiam daqui, você e todo o povo que o segue." E, depois disto, sairei. E, enfurecido, Moisés se retirou da presença de Faraó.

[[v2-11-9]]

^<<v2-11-9,9>>^ Então o Senhor  disse a Moisés: — Faraó não vai ouvir vocês, para que as minhas maravilhas se multipliquem na terra do Egito.

[[v2-11-10]]

^<<v2-11-10,10>>^ Moisés e Arão fizeram todas essas maravilhas diante de Faraó. Mas o Senhor  endureceu o coração de Faraó, que não permitiu que os filhos de Israel saíssem da sua terra.

'''

xref:002-exodo/002-exodo-010.adoc#v2-10-0[&#60; Capítulo Anterior] | <<v2-11-0,Topo>> | xref:002-exodo/002-exodo-012.adoc#v2-12-0[Próximo Capítulo &#62;]