include::./index.adoc[]

[[v2-18-0]]
=== Êxodo, 18
// naa ?, NAA - Nova Almeida Atualizada

[[v2-18-1]]

^<<v2-18-1,1>>^ Jetro, sacerdote de Midiã, sogro de Moisés, ouviu todas as coisas que Deus tinha feito por Moisés e por Israel, seu povo; ouviu como o Senhor  havia tirado Israel do Egito.

[[v2-18-2]]

^<<v2-18-2,2>>^ Jetro, sogro de Moisés, foi até ele, levando consigo Zípora, a mulher de Moisés, depois que este a havia enviado até ele,

[[v2-18-3]]

^<<v2-18-3,3>>^ juntamente com os dois filhos dela. Um dos filhos se chamava Gérson, pois Moisés tinha dito: "Fui peregrino em terra estranha."

[[v2-18-4]]

^<<v2-18-4,4>>^ O outro se chamava Eliézer, pois Moisés tinha dito: "O Deus de meu pai foi a minha ajuda e me livrou da espada de Faraó."

[[v2-18-5]]

^<<v2-18-5,5>>^ Jetro, o sogro de Moisés, juntamente com os filhos e a mulher deste, veio a Moisés no deserto onde estava acampado, junto ao monte de Deus.

[[v2-18-6]]

^<<v2-18-6,6>>^ E Jetro mandou dizer a Moisés: "Eu, seu sogro Jetro, estou chegando, com a sua mulher e os seus dois filhos."

[[v2-18-7]]

^<<v2-18-7,7>>^ Então Moisés foi ao encontro do sogro, inclinou-se e o beijou; e, indagando pelo bem-estar um do outro, entraram na tenda.

[[v2-18-8]]

^<<v2-18-8,8>>^ Moisés contou a seu sogro tudo o que o Senhor  havia feito a Faraó e aos egípcios por amor de Israel, e todas as aflições que enfrentaram no Egito, e como o Senhor  os havia livrado.

[[v2-18-9]]

^<<v2-18-9,9>>^ Jetro ficou contente com todo o bem que o Senhor  havia feito a Israel, livrando-o das mãos dos egípcios.

[[v2-18-10]]

^<<v2-18-10,10>>^ E disse: — Bendito seja o Senhor , que libertou vocês das mãos dos egípcios e da mão de Faraó.

[[v2-18-11]]

^<<v2-18-11,11>>^ Agora sei que o Senhor  é maior do que todos os deuses, porque livrou este povo das mãos dos egípcios, quando agiram arrogantemente contra o povo.

[[v2-18-12]]

^<<v2-18-12,12>>^ Então Jetro, sogro de Moisés, ofereceu um holocausto e sacrifícios a Deus. E Arão e todos os anciãos de Israel vieram para comer com o sogro de Moisés, na presença de Deus.

[[v2-18-13]]

^<<v2-18-13,13>>^ No dia seguinte Moisés sentou-se para julgar o povo; e o povo estava em pé diante de Moisés desde a manhã até o pôr do sol.

[[v2-18-14]]

^<<v2-18-14,14>>^ Quando o sogro de Moisés viu tudo o que ele fazia ao povo, perguntou: — Que é isto que você está fazendo ao povo? Por que você fica sentado sozinho e todo o povo está em pé diante de você, desde a manhã até o pôr do sol?

[[v2-18-15]]

^<<v2-18-15,15>>^ Moisés respondeu a seu sogro: — É porque o povo vem a mim para consultar a Deus.

[[v2-18-16]]

^<<v2-18-16,16>>^ Quando eles têm alguma questão, vêm a mim, para que eu julgue entre um e outro, e eu lhes dou a conhecer os estatutos de Deus e as suas leis.

[[v2-18-17]]

^<<v2-18-17,17>>^ O sogro de Moisés, porém, lhe disse: — Não é bom o que você está fazendo.

[[v2-18-18]]

^<<v2-18-18,18>>^ Com certeza todos ficarão cansados, tanto você como este povo que está com você. Isto é pesado demais para você; você não pode fazer isso sozinho.

[[v2-18-19]]

^<<v2-18-19,19>>^ Escute agora o que vou dizer. Eu o aconselharei, e que Deus esteja com você. Represente o povo diante de Deus, leve as suas causas a Deus,

[[v2-18-20]]

^<<v2-18-20,20>>^ ensine-lhes os estatutos e as leis e faça com que conheçam o caminho em que devem andar e a obra que devem fazer.

[[v2-18-21]]

^<<v2-18-21,21>>^ Procure entre o povo homens capazes, tementes a Deus, homens que amam a verdade e odeiam a corrupção. Coloque-os como chefes do povo: chefes de mil, chefes de cem, chefes de cinquenta e chefes de dez,

[[v2-18-22]]

^<<v2-18-22,22>>^ para que julguem este povo em todo tempo. Toda causa grave trarão a você, mas toda causa pequena eles mesmos julgarão; assim será mais fácil para você, e eles o ajudarão a levar essa carga.

[[v2-18-23]]

^<<v2-18-23,23>>^ Se você fizer isto, e se essa for a ordem de Deus, então você poderá suportar e também todo este povo voltará em paz ao seu lugar.

[[v2-18-24]]

^<<v2-18-24,24>>^ Moisés atendeu às palavras de seu sogro e fez tudo o que este lhe tinha dito.

[[v2-18-25]]

^<<v2-18-25,25>>^ Escolheu homens capazes, de todo o Israel, e os constituiu por chefes sobre o povo: chefes de mil, chefes de cem, chefes de cinquenta e chefes de dez.

[[v2-18-26]]

^<<v2-18-26,26>>^ Estes julgaram o povo em todo tempo; a causa grave trouxeram a Moisés e toda causa simples eles mesmos julgaram.

[[v2-18-27]]

^<<v2-18-27,27>>^ Então Moisés se despediu de seu sogro, e este voltou para a sua terra.

'''

xref:002-exodo/002-exodo-017.adoc#v2-17-0[&#60; Capítulo Anterior] | <<v2-18-0,Topo>> | xref:002-exodo/002-exodo-019.adoc#v2-19-0[Próximo Capítulo &#62;]