include::./index.adoc[]

[[v2-19-0]]
=== Êxodo, 19
// naa ?, NAA - Nova Almeida Atualizada

[[v2-19-1]]

^<<v2-19-1,1>>^ No terceiro mês depois da saída dos filhos de Israel da terra do Egito, no primeiro dia desse mês, eles chegaram ao deserto do Sinai.

[[v2-19-2]]

^<<v2-19-2,2>>^ Tendo partido de Refidim, vieram ao deserto do Sinai, no qual acamparam; ali Israel acampou em frente ao monte.

[[v2-19-3]]

^<<v2-19-3,3>>^ Moisés subiu para encontrar-se com Deus. E do monte o Senhor  o chamou e lhe disse: — Assim você falará à casa de Jacó e anunciará aos filhos de Israel:

[[v2-19-4]]

^<<v2-19-4,4>>^ "Vocês viram o que fiz aos egípcios e como levei vocês sobre asas de águia e os trouxe para perto de mim.

[[v2-19-5]]

^<<v2-19-5,5>>^ Agora, pois, se ouvirem atentamente a minha voz e guardarem a minha aliança, vocês serão a minha propriedade peculiar dentre todos os povos. Porque toda a terra é minha,

[[v2-19-6]]

^<<v2-19-6,6>>^ e vocês serão para mim um reino de sacerdotes e uma nação santa." São estas as palavras que você falará aos filhos de Israel.

[[v2-19-7]]

^<<v2-19-7,7>>^ Moisés foi, chamou os anciãos do povo e expôs diante deles todas estas palavras que o Senhor  lhe havia ordenado.

[[v2-19-8]]

^<<v2-19-8,8>>^ Então todo o povo respondeu a uma só voz: — Tudo o que o Senhor  falou faremos. E Moisés relatou ao Senhor  as palavras do povo.

[[v2-19-9]]

^<<v2-19-9,9>>^ O Senhor  disse a Moisés: — Eis que virei a você numa nuvem escura, para que o povo ouça quando eu falar com você e para que também creiam sempre em você. Porque Moisés tinha anunciado as palavras do povo ao Senhor .

[[v2-19-10]]

^<<v2-19-10,10>>^ E o Senhor  disse a Moisés: — Vá ao povo e consagre-o no dia de hoje e amanhã. Que eles lavem as suas roupas

[[v2-19-11]]

^<<v2-19-11,11>>^ e estejam prontos para o terceiro dia, porque no terceiro dia o Senhor , à vista de todo o povo, descerá sobre o monte Sinai.

[[v2-19-12]]

^<<v2-19-12,12>>^ Marque ao redor do monte limites para o povo, dizendo: "Tomem cuidado para não subir o monte, nem tocar a sua extremidade. Todo aquele que tocar o monte será morto.

[[v2-19-13]]

^<<v2-19-13,13>>^ Mão nenhuma tocará nele. Se o fizer, será apedrejado ou flechado; quer seja animal, quer seja homem, não viverá. Quando soar longamente a trombeta, então subirão o monte."

[[v2-19-14]]

^<<v2-19-14,14>>^ Moisés desceu do monte para junto do povo e consagrou o povo; e lavaram as suas roupas.

[[v2-19-15]]

^<<v2-19-15,15>>^ E Moisés disse ao povo: — Estejam prontos no terceiro dia. Que até lá ninguém tenha relações com a sua mulher.

[[v2-19-16]]

^<<v2-19-16,16>>^ Ao amanhecer do terceiro dia, houve trovões e relâmpagos, uma espessa nuvem cobriu o monte, e ouviu-se um forte som de trombeta, de maneira que todo o povo que estava no arraial tremeu de medo.

[[v2-19-17]]

^<<v2-19-17,17>>^ E Moisés levou o povo para fora do arraial ao encontro de Deus; e puseram-se ao pé do monte.

[[v2-19-18]]

^<<v2-19-18,18>>^ Todo o monte Sinai fumegava, porque o Senhor  havia descido sobre ele em fogo. A fumaça subia como fumaça de uma fornalha, e todo o monte tremia com violência.

[[v2-19-19]]

^<<v2-19-19,19>>^ E o som da trombeta ia aumentando cada vez mais. Moisés falava, e Deus lhe respondia no trovão.

[[v2-19-20]]

^<<v2-19-20,20>>^ O Senhor  desceu sobre o monte Sinai, sobre o alto do monte. O Senhor  chamou Moisés para o alto do monte e Moisés foi até lá.

[[v2-19-21]]

^<<v2-19-21,21>>^ E o Senhor  disse a Moisés: — Desça e avise ao povo que não ultrapasse o limite até o Senhor  para vê-lo, para evitar que muitos deles sejam mortos.

[[v2-19-22]]

^<<v2-19-22,22>>^ Também os sacerdotes, que se aproximam do Senhor , devem se consagrar, para que o Senhor  não se volte contra eles.

[[v2-19-23]]

^<<v2-19-23,23>>^ Então Moisés disse ao Senhor : — O povo não poderá subir o monte Sinai, porque tu nos advertiste, dizendo: "Marque limites ao redor do monte e consagre-o."

[[v2-19-24]]

^<<v2-19-24,24>>^ E o Senhor  respondeu: — Vá, desça; depois você subirá, e Arão virá com você; porém os sacerdotes e o povo não devem ultrapassar o limite para subir ao Senhor , para que Deus não se volte contra eles.

[[v2-19-25]]

^<<v2-19-25,25>>^ Então Moisés desceu ao povo e lhe disse tudo isso.

'''

xref:002-exodo/002-exodo-018.adoc#v2-18-0[&#60; Capítulo Anterior] | <<v2-19-0,Topo>> | xref:002-exodo/002-exodo-020.adoc#v2-20-0[Próximo Capítulo &#62;]