include::./index.adoc[]

[[v2-17-0]]
=== Êxodo, 17
// naa ?, NAA - Nova Almeida Atualizada

[[v2-17-1]]

^<<v2-17-1,1>>^ Toda a congregação dos filhos de Israel partiu do deserto de Sim, fazendo suas paradas, segundo o mandamento do Senhor , e acamparam em Refidim; mas ali não havia água para o povo beber.

[[v2-17-2]]

^<<v2-17-2,2>>^ Então o povo discutiu com Moisés e disse: — Dê-nos água para beber. Moisés respondeu: — Por que vocês estão discutindo comigo? Por que estão tentando o Senhor ?

[[v2-17-3]]

^<<v2-17-3,3>>^ Mas ali o povo estava com sede de água e murmurou contra Moisés, dizendo: — Por que você nos tirou do Egito, para nos matar de sede, a nós, a nossos filhos e aos nossos rebanhos?

[[v2-17-4]]

^<<v2-17-4,4>>^ Então Moisés clamou ao Senhor : — Que farei com este povo? Daqui a pouco vão me apedrejar.

[[v2-17-5]]

^<<v2-17-5,5>>^ O Senhor  respondeu: — Passe adiante do povo e leve com você alguns dos anciãos de Israel. Leve também o bordão com que você feriu o rio Nilo e siga em frente.

[[v2-17-6]]

^<<v2-17-6,6>>^ Eis que estarei ali diante de você sobre a rocha em Horebe. Bata na rocha, e dela sairá água; e o povo beberá. Moisés assim o fez na presença dos anciãos de Israel.

[[v2-17-7]]

^<<v2-17-7,7>>^ E chamou o nome daquele lugar Massá e Meribá, por causa da discussão dos filhos de Israel e porque tentaram o Senhor , dizendo: — Está o Senhor  no meio de nós ou não?

[[v2-17-8]]

^<<v2-17-8,8>>^ Então vieram os amalequitas e atacaram Israel em Refidim.

[[v2-17-9]]

^<<v2-17-9,9>>^ Com isso, Moisés ordenou a Josué: — Escolha alguns homens e vá lutar contra os amalequitas. Amanhã eu estarei no alto do monte, e o bordão de Deus estará na minha mão.

[[v2-17-10]]

^<<v2-17-10,10>>^ Josué fez como Moisés lhe havia ordenado e lutou contra os amalequitas. Porém Moisés, Arão e Hur subiram para o alto do monte.

[[v2-17-11]]

^<<v2-17-11,11>>^ Quando Moisés levantava a mão, Israel vencia; quando, porém, ele abaixava a mão, os amalequitas venciam.

[[v2-17-12]]

^<<v2-17-12,12>>^ Quando as mãos de Moisés ficaram pesadas, pegaram uma pedra e a puseram por baixo dele, para que Moisés se sentasse. Arão e Hur sustentavam as mãos de Moisés, um, de um lado, e o outro, do outro; assim as mãos dele ficaram firmes até o pôr do sol.

[[v2-17-13]]

^<<v2-17-13,13>>^ E Josué destruiu os amalequitas a fio de espada.

[[v2-17-14]]

^<<v2-17-14,14>>^ Então o Senhor  disse a Moisés: — Escreva isto para memória num livro e repita-o a Josué, porque eu vou apagar totalmente a memória dos amalequitas da face da terra.

[[v2-17-15]]

^<<v2-17-15,15>>^ E Moisés edificou um altar e lhe deu o nome de O Senhor  É Minha Bandeira.

[[v2-17-16]]

^<<v2-17-16,16>>^ E disse: — Porque o Senhor  jurou, haverá guerra do Senhor  contra os amalequitas de geração em geração.

'''

xref:002-exodo/002-exodo-016.adoc#v2-16-0[&#60; Capítulo Anterior] | <<v2-17-0,Topo>> | xref:002-exodo/002-exodo-018.adoc#v2-18-0[Próximo Capítulo &#62;]