include::./index.adoc[]

[[v2-38-0]]
=== Êxodo, 38
// naa ?, NAA - Nova Almeida Atualizada

[[v2-38-1]]

^<<v2-38-1,1>>^ Fez também o altar do holocausto de madeira de acácia. Seu comprimento era de dois metros e vinte e a largura era de dois metros e vinte; o altar era quadrado. A altura era de um metro e trinta.

[[v2-38-2]]

^<<v2-38-2,2>>^ Nos quatro cantos colocou quatro chifres, os quais formavam uma só peça com o altar; e o revestiu de bronze.

[[v2-38-3]]

^<<v2-38-3,3>>^ Fez também todos os utensílios do altar: recipientes para recolher as suas cinzas, pás, bacias, garfos e braseiros; todos esses utensílios foram feitos de bronze.

[[v2-38-4]]

^<<v2-38-4,4>>^ Fez também para o altar uma grelha de bronze em forma de rede, do rebordo do altar para baixo, a qual chegava até o meio do altar.

[[v2-38-5]]

^<<v2-38-5,5>>^ Fundiu quatro argolas para os quatro cantos da grelha de bronze, para que nelas fossem passados os cabos.

[[v2-38-6]]

^<<v2-38-6,6>>^ Fez também os cabos de madeira de acácia revestidos de bronze.

[[v2-38-7]]

^<<v2-38-7,7>>^ Passou os cabos pelas argolas, de um e de outro lado do altar, para ser levado; oco e de tábuas o fez.

[[v2-38-8]]

^<<v2-38-8,8>>^ Fez também a bacia de bronze, com o seu suporte de bronze, dos espelhos das mulheres que se reuniam para ministrar à porta da tenda do encontro.

[[v2-38-9]]

^<<v2-38-9,9>>^ Fez também o átrio ao lado meridional, que dá para o sul. As cortinas do átrio eram de linho fino retorcido, de quarenta e quatro metros de comprimento.

[[v2-38-10]]

^<<v2-38-10,10>>^ As suas vinte colunas e as suas bases eram de bronze; os ganchos das colunas e as suas vigas superiores eram de prata.

[[v2-38-11]]

^<<v2-38-11,11>>^ De igual modo para o lado norte havia cortinas de quarenta e quatro metros de comprimento; as suas vinte colunas e as suas vinte bases eram de bronze; os ganchos das colunas e as suas vigas superiores eram de prata.

[[v2-38-12]]

^<<v2-38-12,12>>^ Para o lado oeste havia cortinas de vinte e dois metros; as suas colunas eram dez, e as suas bases eram dez; os ganchos das colunas e as suas vigas superiores eram de prata.

[[v2-38-13]]

^<<v2-38-13,13>>^ Do lado leste, para o nascente, as cortinas tinham vinte e dois metros de comprimento.

[[v2-38-14]]

^<<v2-38-14,14>>^ As cortinas para um lado da entrada tinham seis metros e sessenta de comprimento; e as suas colunas eram três, e as suas bases, três.

[[v2-38-15]]

^<<v2-38-15,15>>^ Para o outro lado da entrada do átrio, de um e de outro lado da entrada, havia cortinas de seis metros e sessenta de comprimento; as suas colunas eram três, e as suas bases, três.

[[v2-38-16]]

^<<v2-38-16,16>>^ Todas as cortinas ao redor do átrio eram de linho fino retorcido.

[[v2-38-17]]

^<<v2-38-17,17>>^ As bases das colunas eram de bronze; os ganchos das colunas e as suas vigas superiores eram de prata.

[[v2-38-18]]

^<<v2-38-18,18>>^ O cortinado da porta do átrio era de obra de bordador, de pano azul, púrpura, carmesim e linho fino retorcido; o comprimento era de oito metros e oitenta, e a altura, na largura, era de dois metros e vinte, segundo a medida das cortinas do átrio.

[[v2-38-19]]

^<<v2-38-19,19>>^ As suas quatro colunas e as suas quatro bases eram de bronze, os seus ganchos eram de prata, e o revestimento das suas cabeças e as suas vigas superiores eram de prata.

[[v2-38-20]]

^<<v2-38-20,20>>^ Todos os pregos do tabernáculo e do átrio ao redor eram de bronze.

[[v2-38-21]]

^<<v2-38-21,21>>^ Esta é a enumeração das coisas para o tabernáculo, a saber, o tabernáculo do testemunho, segundo, por ordem de Moisés, foram contadas pelos levitas, sob a direção de Itamar, filho do sacerdote Arão.

[[v2-38-22]]

^<<v2-38-22,22>>^ Bezalel, filho de Uri, filho de Hur, da tribo de Judá, fez tudo o que o Senhor  havia ordenado a Moisés.

[[v2-38-23]]

^<<v2-38-23,23>>^ Com ele estava Aoliabe, filho de Aisamaque, da tribo de Dã, mestre de obras, desenhista e bordador em pano azul, púrpura, carmesim e linho fino.

[[v2-38-24]]

^<<v2-38-24,24>>^ Todo o ouro empregado na obra, em toda a obra do santuário, a saber, o ouro da oferta, foram mil quilos, segundo o peso padrão do santuário.

[[v2-38-25]]

^<<v2-38-25,25>>^ A prata dos arrolados da congregação foram três mil quatrocentos e vinte e um quilos, segundo o peso padrão do santuário:

[[v2-38-26]]

^<<v2-38-26,26>>^ seis gramas por cabeça, isto é, metade do peso padrão, segundo o peso padrão do santuário, de cada um dos arrolados, de vinte anos para cima, que foram seiscentos e três mil quinhentos e cinquenta.

[[v2-38-27]]

^<<v2-38-27,27>>^ Empregaram-se três mil e quatrocentos quilos de prata para fundir as bases do santuário e as bases do véu; para as cem bases, três mil e quatrocentos quilos: trinta e quatro quilos para cada base.

[[v2-38-28]]

^<<v2-38-28,28>>^ Dos vinte e um quilos de prata que restaram, fez os colchetes das colunas, e cobriu as suas cabeças, e lhes fez as vigas superiores.

[[v2-38-29]]

^<<v2-38-29,29>>^ O bronze da oferta foram dois mil e quatrocentos quilos.

[[v2-38-30]]

^<<v2-38-30,30>>^ Dele fez as bases da porta da tenda do encontro, o altar de bronze, a sua grelha de bronze, todos os utensílios do altar,

[[v2-38-31]]

^<<v2-38-31,31>>^ as bases do átrio ao redor, as bases da porta do átrio, todas as estacas do tabernáculo e todas as estacas do átrio ao redor.

'''

xref:002-exodo/002-exodo-037.adoc#v2-37-0[&#60; Capítulo Anterior] | <<v2-38-0,Topo>> | xref:002-exodo/002-exodo-039.adoc#v2-39-0[Próximo Capítulo &#62;]