include::./index.adoc[]

[[v2-29-0]]
=== Êxodo, 29
// naa ?, NAA - Nova Almeida Atualizada

[[v2-29-1]]

^<<v2-29-1,1>>^ — Isto é o que você lhes fará, para os consagrar, a fim de que me sirvam como sacerdotes: separe um novilho e dois carneiros sem defeito;

[[v2-29-2]]

^<<v2-29-2,2>>^ da melhor farinha faça pães e bolos sem fermento amassados com azeite e pãezinhos bem finos untados com azeite.

[[v2-29-3]]

^<<v2-29-3,3>>^ Ponha tudo isso num cesto e ofereça no cesto. Traga também o novilho e os dois carneiros.

[[v2-29-4]]

^<<v2-29-4,4>>^ Então você fará com que Arão e seus filhos se aproximem à porta da tenda do encontro e mandará que se lavem com água.

[[v2-29-5]]

^<<v2-29-5,5>>^ Depois você pegará as vestes, vestirá Arão com a túnica, a sobrepeliz, a estola sacerdotal e o peitoral, e o cingirá com o cinto de obra esmerada da estola sacerdotal.

[[v2-29-6]]

^<<v2-29-6,6>>^ Você porá a mitra na cabeça dele e sobre a mitra, a coroa sagrada.

[[v2-29-7]]

^<<v2-29-7,7>>^ Então você pegará o óleo da unção e o derramará sobre a cabeça dele; assim você o ungirá.

[[v2-29-8]]

^<<v2-29-8,8>>^ Depois você fará com que os filhos de Arão se aproximem e os vestirá com túnicas;

[[v2-29-9]]

^<<v2-29-9,9>>^ também os cingirá com o cinto, Arão e seus filhos, e lhes atará os turbantes, para que tenham o sacerdócio por estatuto perpétuo. Assim você consagrará Arão e os seus filhos.

[[v2-29-10]]

^<<v2-29-10,10>>^ — Você fará chegar o novilho diante da tenda do encontro, e Arão e seus filhos porão as mãos sobre a cabeça dele.

[[v2-29-11]]

^<<v2-29-11,11>>^ Mate o novilho diante do Senhor , à porta da tenda do encontro.

[[v2-29-12]]

^<<v2-29-12,12>>^ Depois, pegue o sangue do novilho e, com o dedo, ponha-o sobre os chifres do altar; o restante do sangue você derramará na base do altar.

[[v2-29-13]]

^<<v2-29-13,13>>^ Pegue também toda a gordura que cobre as entranhas, a membrana do fígado, os dois rins e a gordura que está neles e queime-os sobre o altar;

[[v2-29-14]]

^<<v2-29-14,14>>^ mas a carne do novilho, a pele e os excrementos você queimará fora do arraial; é sacrifício pelo pecado.

[[v2-29-15]]

^<<v2-29-15,15>>^ — Depois você pegará um dos carneiros, e Arão e seus filhos porão as mãos sobre a cabeça dele.

[[v2-29-16]]

^<<v2-29-16,16>>^ Mate o carneiro, pegue o sangue e jogue-o sobre o altar, ao redor.

[[v2-29-17]]

^<<v2-29-17,17>>^ Corte o carneiro em pedaços e, lavadas as entranhas e as pernas, coloque-as sobre os pedaços e sobre a cabeça.

[[v2-29-18]]

^<<v2-29-18,18>>^ Assim, você queimará todo o carneiro sobre o altar; é holocausto para o Senhor , de aroma agradável, oferta queimada ao Senhor .

[[v2-29-19]]

^<<v2-29-19,19>>^ — Depois pegue o outro carneiro, e Arão e seus filhos porão as mãos sobre a cabeça dele.

[[v2-29-20]]

^<<v2-29-20,20>>^ Mate o carneiro, pegue um pouco do sangue e coloque-o na ponta da orelha direita de Arão e na ponta da orelha direita de seus filhos, bem como sobre o polegar da mão direita deles e sobre o polegar do pé direito deles; o restante do sangue você jogará sobre o altar, ao redor.

[[v2-29-21]]

^<<v2-29-21,21>>^ Então pegue um pouco do sangue sobre o altar e um pouco do óleo da unção e faça aspersão sobre Arão e suas vestes e sobre seus filhos e as vestes de seus filhos com ele, para que ele seja santificado, e as suas vestes, e também seus filhos e as vestes de seus filhos com ele.

[[v2-29-22]]

^<<v2-29-22,22>>^ — Depois retire do carneiro a gordura, a cauda gorda, a gordura que cobre as entranhas, a membrana do fígado, os dois rins, a gordura que está neles e a coxa direita — porque é o carneiro da consagração —

[[v2-29-23]]

^<<v2-29-23,23>>^ e pegue também um pão, um bolo de pão azeitado e um pãozinho de massa bem fina do cesto dos pães sem fermento que estão diante do Senhor .

[[v2-29-24]]

^<<v2-29-24,24>>^ Ponha todas estas coisas nas mãos de Arão e dos filhos dele e, movendo-as para a frente e para trás, ofereça-as como ofertas movidas diante do Senhor .

[[v2-29-25]]

^<<v2-29-25,25>>^ Depois pegue todas as coisas das mãos deles e queime-as sobre o altar; é holocausto para o Senhor , de aroma agradável, oferta queimada ao Senhor .

[[v2-29-26]]

^<<v2-29-26,26>>^ — Pegue o peito do carneiro da consagração de Arão e, movendo-o para a frente e para trás, ofereça-o como oferta movida diante do Senhor ; e esta será a porção que fica para você.

[[v2-29-27]]

^<<v2-29-27,27>>^ Consagre o peito da oferta movida e a coxa da porção que foi movida, a qual se tirou do carneiro da consagração, que é de Arão e de seus filhos.

[[v2-29-28]]

^<<v2-29-28,28>>^ Isto será a obrigação perpétua dos filhos de Israel, devida a Arão e seus filhos, por ser a porção do sacerdote, oferecida, da parte dos filhos de Israel, dos sacrifícios pacíficos; é a oferta que eles fazem ao Senhor .

[[v2-29-29]]

^<<v2-29-29,29>>^ — As vestes santas de Arão passarão a seus filhos depois dele, para serem ungidos nelas e consagrados nelas.

[[v2-29-30]]

^<<v2-29-30,30>>^ Sete dias as vestirá o filho que for sacerdote em seu lugar, quando entrar na tenda do encontro para ministrar no santuário.

[[v2-29-31]]

^<<v2-29-31,31>>^ — Pegue o carneiro da consagração e cozinhe a sua carne no lugar santo.

[[v2-29-32]]

^<<v2-29-32,32>>^ E Arão e seus filhos comerão a carne deste carneiro e o pão que está no cesto à porta da tenda do encontro

[[v2-29-33]]

^<<v2-29-33,33>>^ e comerão das coisas com que for feita a expiação, para consagrá-los e para santificá-los; o estranho não comerá delas, porque são santas.

[[v2-29-34]]

^<<v2-29-34,34>>^ Se sobrar alguma coisa da carne das consagrações ou do pão, até pela manhã, queime isso que sobrou; não se comerá, porque é santo.

[[v2-29-35]]

^<<v2-29-35,35>>^ — Assim, pois, você fará com Arão e seus filhos, conforme tudo o que ordenei a você; durante sete dias você os consagrará.

[[v2-29-36]]

^<<v2-29-36,36>>^ Também cada dia prepare um novilho como oferta pelo pecado para as expiações; e você purificará o altar, fazendo expiação por ele mediante oferta pelo pecado; e você o ungirá para consagrá-lo.

[[v2-29-37]]

^<<v2-29-37,37>>^ Durante sete dias você fará expiação pelo altar e o consagrará; e o altar será santíssimo; tudo o que o tocar será santo.

[[v2-29-38]]

^<<v2-29-38,38>>^ — Isto é o que você oferecerá sobre o altar: dois cordeiros de um ano, cada dia, continuamente.

[[v2-29-39]]

^<<v2-29-39,39>>^ Ofereça um cordeiro de manhã e o outro, ao crepúsculo da tarde.

[[v2-29-40]]

^<<v2-29-40,40>>^ Com um cordeiro ofereça dois litros da melhor farinha, amassada com um litro de azeite batido; e, para libação, um litro de vinho.

[[v2-29-41]]

^<<v2-29-41,41>>^ O outro cordeiro você oferecerá ao pôr do sol, como a oferta de cereais e a libação da manhã, de aroma agradável, oferta queimada ao Senhor .

[[v2-29-42]]

^<<v2-29-42,42>>^ — Este será o holocausto contínuo oferecido de geração em geração, à porta da tenda do encontro, diante do Senhor , onde me encontrarei com vocês, para falar com você ali.

[[v2-29-43]]

^<<v2-29-43,43>>^ Ali virei aos filhos de Israel, para que, por minha glória, sejam santificados,

[[v2-29-44]]

^<<v2-29-44,44>>^ e consagrarei a tenda do encontro e o altar. Também santificarei Arão e os seus filhos, para que me sirvam como sacerdotes.

[[v2-29-45]]

^<<v2-29-45,45>>^ E habitarei no meio dos filhos de Israel e serei o seu Deus.

[[v2-29-46]]

^<<v2-29-46,46>>^ E saberão que eu sou o Senhor , seu Deus, que os tirou da terra do Egito, para habitar no meio deles; eu sou o Senhor , o Deus deles.

'''

xref:002-exodo/002-exodo-028.adoc#v2-28-0[&#60; Capítulo Anterior] | <<v2-29-0,Topo>> | xref:002-exodo/002-exodo-030.adoc#v2-30-0[Próximo Capítulo &#62;]