include::./index.adoc[]

[[v2-15-0]]
=== Êxodo, 15
// naa ?, NAA - Nova Almeida Atualizada

[[v2-15-1]]

^<<v2-15-1,1>>^ Então Moisés e os filhos de Israel entoaram este cântico ao Senhor : Cantarei ao Senhor , porque triunfou gloriosamente; lançou no mar o cavalo e o seu cavaleiro.

[[v2-15-2]]

^<<v2-15-2,2>>^ O Senhor  é a minha força e o meu cântico; ele se tornou a minha salvação. Este é o meu Deus; portanto, eu o louvarei; ele é o Deus de meu pai; por isso, o exaltarei.

[[v2-15-3]]

^<<v2-15-3,3>>^ O Senhor  é homem de guerra; Senhor  é o seu nome.

[[v2-15-4]]

^<<v2-15-4,4>>^ Lançou no mar os carros de Faraó e o seu exército; e os seus capitães afogaram-se no mar Vermelho.

[[v2-15-5]]

^<<v2-15-5,5>>^ As águas profundas os cobriram; desceram às profundezas como pedra.

[[v2-15-6]]

^<<v2-15-6,6>>^ A tua mão direita, ó Senhor , é gloriosa em poder; a tua mão direita, ó Senhor , despedaça o inimigo.

[[v2-15-7]]

^<<v2-15-7,7>>^ Na grandeza da tua excelência, derrubas os que se levantam contra ti; envias o teu furor, que os consome como palha.

[[v2-15-8]]

^<<v2-15-8,8>>^ Com o sopro das tuas narinas, amontoaram-se as águas, as correntes pararam em montão; as águas profundas se tornaram sólidas no coração do mar.

[[v2-15-9]]

^<<v2-15-9,9>>^ O inimigo dizia: "Perseguirei, alcançarei, repartirei os despojos; a minha alma se fartará deles, arrancarei a minha espada, e a minha mão os destruirá."

[[v2-15-10]]

^<<v2-15-10,10>>^ Sopraste com o teu vento, e o mar os cobriu; afundaram-se como chumbo em águas impetuosas.

[[v2-15-11]]

^<<v2-15-11,11>>^ Ó Senhor , quem é como tu entre os deuses? Quem é como tu, glorificado em santidade, terrível em feitos gloriosos, que operas maravilhas?

[[v2-15-12]]

^<<v2-15-12,12>>^ Estendeste a mão direita, e a terra os engoliu.

[[v2-15-13]]

^<<v2-15-13,13>>^ Com a tua bondade guiaste o povo que salvaste; com a tua força o levaste à habitação da tua santidade.

[[v2-15-14]]

^<<v2-15-14,14>>^ Os povos ouviram e estremeceram; agonias apoderaram-se dos habitantes da Filístia.

[[v2-15-15]]

^<<v2-15-15,15>>^ Então os chefes de Edom se perturbam, dos poderosos de Moabe se apodera temor, esmorecem todos os habitantes de Canaã.

[[v2-15-16]]

^<<v2-15-16,16>>^ Sobre eles cai espanto e pavor; pela grandeza do teu braço, emudecem como pedra; até que passe o teu povo, ó Senhor , até que passe o povo que adquiriste.

[[v2-15-17]]

^<<v2-15-17,17>>^ Tu o introduzirás e o plantarás no monte da tua herança, no lugar que preparaste, ó Senhor , para a tua habitação, no santuário, ó Senhor, que as tuas mãos estabeleceram.

[[v2-15-18]]

^<<v2-15-18,18>>^ O Senhor  reinará por todo o sempre.

[[v2-15-19]]

^<<v2-15-19,19>>^ Porque os cavalos de Faraó, com os seus carros de guerra e com os seus cavaleiros, entraram no mar, e o Senhor  fez com que as águas do mar voltassem e os cobrissem; mas os filhos de Israel passaram a pé enxuto pelo meio do mar.

[[v2-15-20]]

^<<v2-15-20,20>>^ A profetisa Miriã, irmã de Arão, pegou um tamborim, e todas as mulheres saíram atrás dela com tamborins e com danças.

[[v2-15-21]]

^<<v2-15-21,21>>^ E Miriã lhes respondia: Cantem ao Senhor , porque triunfou gloriosamente e lançou no mar o cavalo e o seu cavaleiro.

[[v2-15-22]]

^<<v2-15-22,22>>^ Moisés fez o povo de Israel partir do mar Vermelho, e eles foram para o deserto de Sur. Caminharam três dias no deserto e não acharam água.

[[v2-15-23]]

^<<v2-15-23,23>>^ Por fim, chegaram a Mara. No entanto, não puderam beber as águas de Mara, porque eram amargas. Por isso aquele lugar foi chamado de Mara.

[[v2-15-24]]

^<<v2-15-24,24>>^ E o povo murmurou contra Moisés, dizendo: — O que vamos beber?

[[v2-15-25]]

^<<v2-15-25,25>>^ Então Moisés clamou ao Senhor , e o Senhor  lhe mostrou um pedaço de madeira. Moisés jogou a madeira nas águas, e as águas se tornaram doces. Ali o Senhor  lhes deu estatutos e uma ordenança, e ali os provou,

[[v2-15-26]]

^<<v2-15-26,26>>^ e disse: — Se vocês ouvirem com atenção a voz do Senhor , seu Deus, fizerem o que é reto diante dos seus olhos, derem ouvidos aos seus mandamentos e guardarem todos os seus estatutos, nenhuma enfermidade virá sobre vocês, das que enviei sobre os egípcios; pois eu sou o Senhor , aquele que cura vocês.

[[v2-15-27]]

^<<v2-15-27,27>>^ Então chegaram a Elim, onde havia doze fontes de água e setenta palmeiras. E acamparam junto das águas.

'''

xref:002-exodo/002-exodo-014.adoc#v2-14-0[&#60; Capítulo Anterior] | <<v2-15-0,Topo>> | xref:002-exodo/002-exodo-016.adoc#v2-16-0[Próximo Capítulo &#62;]