include::./index.adoc[]

[[v2-25-0]]
=== Êxodo, 25
// naa ?, NAA - Nova Almeida Atualizada

[[v2-25-1]]

^<<v2-25-1,1>>^ O Senhor  disse a Moisés:

[[v2-25-2]]

^<<v2-25-2,2>>^ — Diga aos filhos de Israel que me tragam uma oferta. De todo homem cujo coração o mover para isso, dele vocês receberão a minha oferta.

[[v2-25-3]]

^<<v2-25-3,3>>^ Esta é a oferta que dele vocês receberão: ouro, prata e bronze;

[[v2-25-4]]

^<<v2-25-4,4>>^ pano azul, púrpura e carmesim; linho fino; pelos de cabra;

[[v2-25-5]]

^<<v2-25-5,5>>^ peles de carneiro tingidas de vermelho e peles finas; madeira de acácia;

[[v2-25-6]]

^<<v2-25-6,6>>^ azeite para a iluminação; especiarias para o óleo da unção e para o incenso aromático;

[[v2-25-7]]

^<<v2-25-7,7>>^ pedras de ônix e pedras de engaste, para a estola sacerdotal e para o peitoral.

[[v2-25-8]]

^<<v2-25-8,8>>^ E farão para mim um santuário, para que eu possa habitar no meio deles.

[[v2-25-9]]

^<<v2-25-9,9>>^ Segundo tudo o que eu mostrar a você como modelo do tabernáculo e como modelo de todos os seus móveis, assim mesmo vocês o farão.

[[v2-25-10]]

^<<v2-25-10,10>>^ — Também farão uma arca de madeira de acácia, de um metro e dez de comprimento, sessenta e seis centímetros de largura, e sessenta e seis centímetros de altura.

[[v2-25-11]]

^<<v2-25-11,11>>^ Revista a arca de ouro puro. Coloque esse revestimento por dentro e por fora, e ponha um remate de ouro ao redor da arca.

[[v2-25-12]]

^<<v2-25-12,12>>^ Mande fundir quatro argolas de ouro e fixe-as nos quatro cantos da arca: duas argolas num lado dela e duas argolas no outro lado.

[[v2-25-13]]

^<<v2-25-13,13>>^ Faça também cabos grossos de madeira de acácia e revista-os de ouro.

[[v2-25-14]]

^<<v2-25-14,14>>^ Passe os cabos pelas argolas nos lados da arca, para que ela possa ser carregada por meio deles.

[[v2-25-15]]

^<<v2-25-15,15>>^ Os cabos ficarão nas argolas da arca e não serão tirados dela.

[[v2-25-16]]

^<<v2-25-16,16>>^ E você porá na arca o testemunho, que eu lhe darei.

[[v2-25-17]]

^<<v2-25-17,17>>^ — Faça também um propiciatório de ouro puro, de um metro e dez de comprimento e sessenta e seis centímetros de largura.

[[v2-25-18]]

^<<v2-25-18,18>>^ Faça dois querubins de ouro batido, nas duas extremidades do propiciatório.

[[v2-25-19]]

^<<v2-25-19,19>>^ Um querubim deve ficar numa extremidade, e o outro, na outra extremidade. Faça os querubins nas duas extremidades de modo que formem uma só peça com o propiciatório.

[[v2-25-20]]

^<<v2-25-20,20>>^ Os querubins estenderão as asas por cima, cobrindo com elas o propiciatório. Eles estarão de frente um para o outro, olhando para o propiciatório.

[[v2-25-21]]

^<<v2-25-21,21>>^ Ponha o propiciatório em cima da arca; e dentro dela coloque o testemunho, que eu lhe darei.

[[v2-25-22]]

^<<v2-25-22,22>>^ Ali eu me encontrarei com você e, de cima do propiciatório, do meio dos dois querubins que estão sobre a arca do testemunho, falarei com você a respeito de tudo o que eu lhe ordenar para os filhos de Israel.

[[v2-25-23]]

^<<v2-25-23,23>>^ — Faça também uma mesa de madeira de acácia. Terá o comprimento de oitenta e oito centímetros, a largura de quarenta e quatro e a altura de sessenta e seis.

[[v2-25-24]]

^<<v2-25-24,24>>^ Faça um revestimento de ouro puro e ponha um remate de ouro ao redor.

[[v2-25-25]]

^<<v2-25-25,25>>^ Faça também uma borda ao redor, da largura de quatro dedos, e ponha um remate de ouro ao redor da borda.

[[v2-25-26]]

^<<v2-25-26,26>>^ Faça também quatro argolas de ouro e fixe-as nos quatro cantos que estão nos quatro pés da mesa.

[[v2-25-27]]

^<<v2-25-27,27>>^ As argolas devem estar perto da borda, como lugares para os cabos, para que se possa carregar a mesa.

[[v2-25-28]]

^<<v2-25-28,28>>^ Faça estes cabos de madeira de acácia e revista-os de ouro, para que a mesa possa ser carregada por meio deles.

[[v2-25-29]]

^<<v2-25-29,29>>^ Faça também os seus pratos, os seus recipientes para incenso, as suas jarras e as suas taças em que serão oferecidas as libações; faça tudo isso de ouro puro.

[[v2-25-30]]

^<<v2-25-30,30>>^ Ponha sobre a mesa os pães da proposição diante de mim perpetuamente.

[[v2-25-31]]

^<<v2-25-31,31>>^ — Faça também um candelabro de ouro puro; de ouro batido deverá ser feito este candelabro. O seu pedestal, a sua haste, os seus cálices, as suas maçanetas e as suas flores formarão com ele uma só peça.

[[v2-25-32]]

^<<v2-25-32,32>>^ Seis hastes sairão dos lados do candelabro: três de um lado e três do outro.

[[v2-25-33]]

^<<v2-25-33,33>>^ Numa haste haverá três cálices com formato de amêndoas, uma maçaneta e uma flor; na outra haste haverá três cálices com formato de amêndoas, uma maçaneta e uma flor; e assim serão as seis hastes que saem do candelabro.

[[v2-25-34]]

^<<v2-25-34,34>>^ — Mas no candelabro mesmo haverá quatro cálices com formato de amêndoas, com suas maçanetas e com suas flores.

[[v2-25-35]]

^<<v2-25-35,35>>^ Haverá uma maçaneta sob duas hastes que saem dele; e ainda uma maçaneta sob duas outras hastes que saem dele; e ainda mais uma maçaneta sob duas outras hastes que saem dele; assim se fará com as seis hastes que saem do candelabro.

[[v2-25-36]]

^<<v2-25-36,36>>^ As maçanetas e as hastes do candelabro formarão uma só peça com o mesmo; tudo será de uma só peça, obra batida de ouro puro.

[[v2-25-37]]

^<<v2-25-37,37>>^ — Faça também as sete lâmpadas do candelabro, as quais se acenderão para iluminar o espaço diante dele.

[[v2-25-38]]

^<<v2-25-38,38>>^ As suas tesouras de cortar pavios e os seus apagadores serão de ouro puro.

[[v2-25-39]]

^<<v2-25-39,39>>^ Com trinta e quatro quilos de ouro puro se fará o candelabro com todos estes utensílios.

[[v2-25-40]]

^<<v2-25-40,40>>^ Tenha o cuidado de fazer tudo segundo o modelo que foi mostrado a você no monte.

'''

xref:002-exodo/002-exodo-024.adoc#v2-24-0[&#60; Capítulo Anterior] | <<v2-25-0,Topo>> | xref:002-exodo/002-exodo-026.adoc#v2-26-0[Próximo Capítulo &#62;]