include::./index.adoc[]

[[v2-30-0]]
=== Êxodo, 30
// naa ?, NAA - Nova Almeida Atualizada

[[v2-30-1]]

^<<v2-30-1,1>>^ — Faça também um altar para queimar incenso; faça-o de madeira de acácia.

[[v2-30-2]]

^<<v2-30-2,2>>^ Será quadrado, tendo quarenta e cinco centímetros de comprimento e quarenta e cinco de largura; a altura será de noventa centímetros. Os chifres formarão uma só peça com ele.

[[v2-30-3]]

^<<v2-30-3,3>>^ Revista-o de ouro puro, a parte superior, as paredes ao redor e os chifres; ponha também um remate de ouro ao redor.

[[v2-30-4]]

^<<v2-30-4,4>>^ Faça também duas argolas de ouro e coloque-as debaixo do remate; coloque-as de ambos os lados. Por essas argolas serão passados os cabos, quando o altar for transportado.

[[v2-30-5]]

^<<v2-30-5,5>>^ Faça esses cabos de madeira de acácia, revestindo-os de ouro.

[[v2-30-6]]

^<<v2-30-6,6>>^ Ponha o altar em frente do véu que está diante da arca do testemunho, diante do propiciatório que está sobre o testemunho, onde me encontrarei com você.

[[v2-30-7]]

^<<v2-30-7,7>>^ Arão queimará o incenso aromático sobre o altar; cada manhã, quando preparar as lâmpadas, o queimará.

[[v2-30-8]]

^<<v2-30-8,8>>^ Quando, ao crepúsculo da tarde, acender as lâmpadas, o queimará; será incenso contínuo diante do Senhor , de geração em geração.

[[v2-30-9]]

^<<v2-30-9,9>>^ Não ofereçam incenso estranho sobre esse altar, nem holocausto, nem ofertas de cereais. Também não ofereçam libações sobre ele.

[[v2-30-10]]

^<<v2-30-10,10>>^ — Uma vez por ano, Arão fará expiação sobre os chifres do altar com o sangue da oferta pelo pecado; uma vez por ano, fará expiação sobre ele, de geração em geração; é altar santíssimo ao Senhor .

[[v2-30-11]]

^<<v2-30-11,11>>^ O Senhor  disse mais a Moisés:

[[v2-30-12]]

^<<v2-30-12,12>>^ — Quando você fizer recenseamento dos filhos de Israel, cada um deles dará ao Senhor  o resgate de si próprio, quando você fizer a contagem; para que não haja entre eles praga nenhuma, quando você fizer a contagem.

[[v2-30-13]]

^<<v2-30-13,13>>^ Todo aquele que for incluído na lista dará isto: seis gramas, segundo o peso padrão do santuário, que é de doze gramas. Esses seis gramas são a oferta ao Senhor .

[[v2-30-14]]

^<<v2-30-14,14>>^ Todo aquele que for incluído na lista, de vinte anos para cima, dará a oferta ao Senhor .

[[v2-30-15]]

^<<v2-30-15,15>>^ O rico não dará mais de seis gramas, nem o pobre dará menos, quando derem a oferta ao Senhor , para fazerem expiação pela vida de vocês.

[[v2-30-16]]

^<<v2-30-16,16>>^ Você receberá o dinheiro das expiações dos filhos de Israel e o usará para o serviço da tenda do encontro; e será para memória aos filhos de Israel diante do Senhor , para fazerem expiação pela vida de vocês.

[[v2-30-17]]

^<<v2-30-17,17>>^ O Senhor  disse mais a Moisés:

[[v2-30-18]]

^<<v2-30-18,18>>^ — Faça também uma bacia de bronze com o seu suporte de bronze, para lavar. Coloque-a entre a tenda do encontro e o altar e ponha água dentro dela.

[[v2-30-19]]

^<<v2-30-19,19>>^ Nela, Arão e seus filhos lavarão as mãos e os pés.

[[v2-30-20]]

^<<v2-30-20,20>>^ Quando entrarem na tenda do encontro, eles se lavarão com água, para que não morram. Também quando se aproximarem do altar para ministrar, para acender a oferta queimada ao Senhor ,

[[v2-30-21]]

^<<v2-30-21,21>>^ lavarão as mãos e os pés, para que não morram. E isto lhes será por estatuto perpétuo, a ele e à sua posteridade, através de suas gerações.

[[v2-30-22]]

^<<v2-30-22,22>>^ O Senhor  disse mais a Moisés:

[[v2-30-23]]

^<<v2-30-23,23>>^ — Pegue as mais excelentes especiarias: seis quilos de mirra líquida; a metade, a saber, três quilos de cinamomo aromático; três quilos de cálamo aromático;

[[v2-30-24]]

^<<v2-30-24,24>>^ seis quilos de cássia, segundo o peso padrão do santuário; e três litros e meio de azeite de oliveira.

[[v2-30-25]]

^<<v2-30-25,25>>^ Disto você fará o óleo sagrado para a unção, o perfume composto segundo a arte do perfumista; este será o óleo sagrado da unção.

[[v2-30-26]]

^<<v2-30-26,26>>^ Com ele você ungirá a tenda do encontro, a arca do testemunho,

[[v2-30-27]]

^<<v2-30-27,27>>^ a mesa com todos os seus utensílios, o candelabro com os seus utensílios, o altar do incenso,

[[v2-30-28]]

^<<v2-30-28,28>>^ o altar do holocausto com todos os utensílios e a bacia com o seu suporte.

[[v2-30-29]]

^<<v2-30-29,29>>^ Assim você consagrará estas coisas, para que sejam santíssimas; tudo o que tocar nelas será santo.

[[v2-30-30]]

^<<v2-30-30,30>>^ Você ungirá também Arão e os seus filhos e os consagrará para que me sirvam como sacerdotes.

[[v2-30-31]]

^<<v2-30-31,31>>^ Diga aos filhos de Israel: "Este me será o óleo sagrado da unção de geração em geração.

[[v2-30-32]]

^<<v2-30-32,32>>^ Não se ungirá com ele o corpo de quem não for sacerdote. Não façam outro óleo semelhante, da mesma composição; é óleo santo e será santo para vocês.

[[v2-30-33]]

^<<v2-30-33,33>>^ Quem preparar óleo igual a este ou com ele ungir um estranho será eliminado do meio do seu povo."

[[v2-30-34]]

^<<v2-30-34,34>>^ O Senhor  disse a Moisés: — Pegue a mesma quantidade de substâncias aromáticas, estoraque, ônica, gálbano e incenso puro,

[[v2-30-35]]

^<<v2-30-35,35>>^ e com isto faça incenso, perfume segundo a arte do perfumista, temperado com sal, puro e santo.

[[v2-30-36]]

^<<v2-30-36,36>>^ Moa uma parte desse incenso e coloque-o diante da arca do testemunho na tenda do encontro, onde me encontrarei com você. Esse incenso será coisa santíssima para vocês.

[[v2-30-37]]

^<<v2-30-37,37>>^ Porém o incenso que vocês farão, segundo a composição deste, não o façam para seu uso pessoal; santo será para o Senhor .

[[v2-30-38]]

^<<v2-30-38,38>>^ Quem fizer incenso igual a este para o cheirar será eliminado do meio do seu povo.

'''

xref:002-exodo/002-exodo-029.adoc#v2-29-0[&#60; Capítulo Anterior] | <<v2-30-0,Topo>> | xref:002-exodo/002-exodo-031.adoc#v2-31-0[Próximo Capítulo &#62;]