include::./index.adoc[]

[[v2-4-0]]
=== Êxodo, 4
// naa ?, NAA - Nova Almeida Atualizada

[[v2-4-1]]

^<<v2-4-1,1>>^ Moisés respondeu: — Mas eis que eles não vão acreditar em mim, nem ouvirão o que vou dizer, pois dirão: "O Senhor  não apareceu a você."

[[v2-4-2]]

^<<v2-4-2,2>>^ Então o Senhor  perguntou a Moisés: — Que é isso que você tem na mão? Ele respondeu: — Um bordão.

[[v2-4-3]]

^<<v2-4-3,3>>^ Então lhe disse: — Jogue-o no chão. Ele o jogou no chão, e o bordão virou uma serpente. E Moisés fugia dela.

[[v2-4-4]]

^<<v2-4-4,4>>^ Mas o Senhor  disse a Moisés: — Estenda a mão e pegue-a pela cauda. Ele estendeu a mão, pegou-a pela cauda, e ela se transformou em bordão.

[[v2-4-5]]

^<<v2-4-5,5>>^ Então o Senhor  disse: — Isto é para que creiam que o Senhor , o Deus de seus pais, o Deus de Abraão, o Deus de Isaque e o Deus de Jacó, apareceu a você.

[[v2-4-6]]

^<<v2-4-6,6>>^ E o Senhor  continuou: — Ponha, agora, a mão no peito. Ele o fez; e, tirando a mão do peito, eis que ela estava leprosa, branca como a neve.

[[v2-4-7]]

^<<v2-4-7,7>>^ Então o Senhor  disse: — Ponha a mão no peito outra vez. Ele a pôs no peito novamente; e, quando a tirou, eis que se havia tornado como o restante de sua carne.

[[v2-4-8]]

^<<v2-4-8,8>>^ O Senhor  continuou: — Se eles não acreditarem em você, nem atenderem à evidência do primeiro sinal, talvez acreditarão na evidência do segundo.

[[v2-4-9]]

^<<v2-4-9,9>>^ Se eles ainda não acreditarem mediante esses dois sinais, nem ouvirem o que você disser, pegue um pouco de água do rio e derrame na terra seca; e a água que você pegou do rio se transformará em sangue sobre a terra.

[[v2-4-10]]

^<<v2-4-10,10>>^ Então Moisés disse ao Senhor : — Ah! Senhor! Eu nunca fui eloquente, nem no passado, nem depois que falaste a teu servo, pois sou pesado de boca e pesado de língua.

[[v2-4-11]]

^<<v2-4-11,11>>^ O Senhor  respondeu: — Quem fez a boca do homem? Ou quem faz o mudo, ou o surdo, ou o que vê, ou o cego? Não sou eu, o Senhor ?

[[v2-4-12]]

^<<v2-4-12,12>>^ Agora vá, e eu serei com a sua boca e lhe ensinarei o que você deve falar.

[[v2-4-13]]

^<<v2-4-13,13>>^ Porém Moisés respondeu: — Ah! Senhor! Envia alguém outro que quiseres enviar, menos a mim.

[[v2-4-14]]

^<<v2-4-14,14>>^ Então a ira do Senhor  se acendeu contra Moisés. O Senhor  disse: — Arão, o levita, não é seu irmão? Eu sei que ele fala fluentemente. Eis que ele vem ao seu encontro e, ao ver você, se alegrará em seu coração.

[[v2-4-15]]

^<<v2-4-15,15>>^ Você falará com ele e lhe porá na boca as palavras; eu serei com a sua boca e com a dele e ensinarei a vocês o que devem fazer.

[[v2-4-16]]

^<<v2-4-16,16>>^ Ele falará por você ao povo; ele será como se fosse a sua boca, e você será para ele como Deus.

[[v2-4-17]]

^<<v2-4-17,17>>^ Leve, pois, na mão este bordão, com o qual você fará os sinais.

[[v2-4-18]]

^<<v2-4-18,18>>^ Moisés voltou para Jetro, seu sogro, e lhe disse: — Deixe-me voltar aos meus irmãos que estão no Egito para ver se ainda vivem. Jetro respondeu: — Vá em paz.

[[v2-4-19]]

^<<v2-4-19,19>>^ O Senhor  disse a Moisés, em Midiã: — Volte para o Egito, porque já morreram todos os que queriam matar você.

[[v2-4-20]]

^<<v2-4-20,20>>^ Então Moisés tomou a mulher e os filhos, fez com que montassem num jumento e voltou para a terra do Egito. Moisés levava na mão o bordão de Deus.

[[v2-4-21]]

^<<v2-4-21,21>>^ O Senhor  disse a Moisés: — Quando você voltar ao Egito, trate de fazer diante de Faraó todos os milagres que pus em sua mão. Mas eu vou endurecer o coração de Faraó, para que não deixe o povo ir.

[[v2-4-22]]

^<<v2-4-22,22>>^ Diga a Faraó: Assim diz o Senhor : "Israel é meu filho, meu primogênito.

[[v2-4-23]]

^<<v2-4-23,23>>^ E eu digo a você: deixe o meu filho ir, para que me adore; mas, se você não quiser deixá-lo ir, eis que eu matarei seu filho, seu primogênito."

[[v2-4-24]]

^<<v2-4-24,24>>^ Estando Moisés no caminho, numa estalagem, o Senhor  o encontrou e quis matá-lo.

[[v2-4-25]]

^<<v2-4-25,25>>^ Então Zípora pegou uma pedra afiada, cortou o prepúcio de seu filho e com ele tocou os pés de Moisés. E lhe disse: — Sem dúvida, você é para mim um marido de sangue.

[[v2-4-26]]

^<<v2-4-26,26>>^ Assim, o Senhor  o deixou. Ela disse "marido de sangue" por causa da circuncisão.

[[v2-4-27]]

^<<v2-4-27,27>>^ O Senhor  disse a Arão: — Vá encontrar-se com Moisés, no deserto. Ele foi e, encontrando-o no monte de Deus, o beijou.

[[v2-4-28]]

^<<v2-4-28,28>>^ Moisés relatou a Arão todas as palavras do Senhor , com as quais o havia enviado, e todos os sinais que lhe havia mandado realizar.

[[v2-4-29]]

^<<v2-4-29,29>>^ Então Moisés e Arão foram e reuniram todos os anciãos dos filhos de Israel.

[[v2-4-30]]

^<<v2-4-30,30>>^ Arão falou todas as palavras que o Senhor  tinha dito a Moisés, e este fez os sinais diante do povo.

[[v2-4-31]]

^<<v2-4-31,31>>^ E o povo creu. E, quando ouviram que o Senhor  havia visitado os filhos de Israel e visto a aflição deles, inclinaram-se e adoraram.

'''

xref:002-exodo/002-exodo-003.adoc#v2-3-0[&#60; Capítulo Anterior] | <<v2-4-0,Topo>> | xref:002-exodo/002-exodo-005.adoc#v2-5-0[Próximo Capítulo &#62;]