include::./index.adoc[]

[[v2-24-0]]
=== Êxodo, 24
// naa ?, NAA - Nova Almeida Atualizada

[[v2-24-1]]

^<<v2-24-1,1>>^ Deus disse a Moisés: — Subam para junto do Senhor , você, Arão, Nadabe, Abiú e setenta dos anciãos de Israel; e adorem de longe.

[[v2-24-2]]

^<<v2-24-2,2>>^ Só Moisés se aproximará do Senhor ; os outros não se aproximarão, nem o povo subirá com ele.

[[v2-24-3]]

^<<v2-24-3,3>>^ Moisés foi e transmitiu ao povo todas as palavras do Senhor  e todos os estatutos. Então todo o povo respondeu a uma voz e disse: — Tudo o que o Senhor  falou nós faremos.

[[v2-24-4]]

^<<v2-24-4,4>>^ Moisés escreveu todas as palavras do Senhor  e, tendo-se levantado de manhã cedo, edificou um altar ao pé do monte e ergueu doze colunas, segundo as doze tribos de Israel.

[[v2-24-5]]

^<<v2-24-5,5>>^ E enviou alguns jovens dos filhos de Israel, os quais ofereceram ao Senhor  holocaustos e sacrifícios pacíficos de novilhos.

[[v2-24-6]]

^<<v2-24-6,6>>^ Moisés pegou a metade do sangue e o pôs em bacias; e a outra metade aspergiu sobre o altar.

[[v2-24-7]]

^<<v2-24-7,7>>^ Depois pegou o livro da aliança e o leu para o povo. E eles disseram: — Tudo o que o Senhor  falou nós faremos e obedeceremos.

[[v2-24-8]]

^<<v2-24-8,8>>^ Então Moisés pegou aquele sangue, e o aspergiu sobre o povo, e disse: — Eis aqui o sangue da aliança que o Senhor  fez com vocês de acordo com todas estas palavras.

[[v2-24-9]]

^<<v2-24-9,9>>^ Moisés, Arão, Nadabe, Abiú e setenta dos anciãos de Israel subiram o monte.

[[v2-24-10]]

^<<v2-24-10,10>>^ E viram o Deus de Israel, sob cujos pés havia como que uma pavimentação de pedra de safira, que se parecia com o céu na sua claridade.

[[v2-24-11]]

^<<v2-24-11,11>>^ Deus não estendeu a mão contra os escolhidos dos filhos de Israel; eles viram Deus, comeram e beberam.

[[v2-24-12]]

^<<v2-24-12,12>>^ Então o Senhor  disse a Moisés: — Suba para junto de mim, no monte, e fique lá; darei a você tábuas de pedra, a lei e os mandamentos que escrevi, para que você ensine o povo.

[[v2-24-13]]

^<<v2-24-13,13>>^ Moisés se aprontou, juntamente com Josué, seu auxiliar, e subiu o monte de Deus.

[[v2-24-14]]

^<<v2-24-14,14>>^ Ele disse aos anciãos: — Esperem aqui até que voltemos para junto de vocês. Eis que Arão e Hur ficam com vocês; quem tiver alguma questão deve se dirigir a eles.

[[v2-24-15]]

^<<v2-24-15,15>>^ Tendo Moisés subido, uma nuvem cobriu o monte.

[[v2-24-16]]

^<<v2-24-16,16>>^ E a glória do Senhor  pousou sobre o monte Sinai, e a nuvem o cobriu durante seis dias. No sétimo dia, do meio da nuvem o Senhor  chamou Moisés.

[[v2-24-17]]

^<<v2-24-17,17>>^ Aos olhos dos israelitas, o aspecto da glória do Senhor  era como um fogo consumidor no alto do monte.

[[v2-24-18]]

^<<v2-24-18,18>>^ E Moisés, entrando pelo meio da nuvem, subiu o monte; e lá permaneceu quarenta dias e quarenta noites.

'''

xref:002-exodo/002-exodo-023.adoc#v2-23-0[&#60; Capítulo Anterior] | <<v2-24-0,Topo>> | xref:002-exodo/002-exodo-025.adoc#v2-25-0[Próximo Capítulo &#62;]