include::./index.adoc[]

[[v2-5-0]]
=== Êxodo, 5
// naa ?, NAA - Nova Almeida Atualizada

[[v2-5-1]]

^<<v2-5-1,1>>^ Depois Moisés e Arão foram e disseram a Faraó: — Assim diz o Senhor , Deus de Israel: "Deixe o meu povo ir, para que me celebre uma festa no deserto."

[[v2-5-2]]

^<<v2-5-2,2>>^ Faraó respondeu: — Quem é o Senhor  para que eu ouça a sua voz e deixe Israel ir? Não conheço o Senhor  e não deixarei Israel ir.

[[v2-5-3]]

^<<v2-5-3,3>>^ Eles prosseguiram: — O Deus dos hebreus veio ao nosso encontro; portanto, deixe-nos ir caminho de três dias ao deserto, para que ofereçamos sacrifícios ao Senhor , nosso Deus, para evitar que ele venha sobre nós com peste ou com espada.

[[v2-5-4]]

^<<v2-5-4,4>>^ Então o rei do Egito disse: — Moisés e Arão, por que estão afastando o povo das suas tarefas? Voltem ao trabalho!

[[v2-5-5]]

^<<v2-5-5,5>>^ E Faraó disse também: — O povo da terra já é muito e vocês ainda querem que eles descansem de suas tarefas!

[[v2-5-6]]

^<<v2-5-6,6>>^ Naquele mesmo dia Faraó deu uma ordem aos feitores do povo e aos seus capatazes, dizendo:

[[v2-5-7]]

^<<v2-5-7,7>>^ — Daqui em diante não forneçam mais palha ao povo, para fazer tijolos, como antes; que eles mesmos ajuntem para si a palha.

[[v2-5-8]]

^<<v2-5-8,8>>^ Mas exijam deles a mesma quantidade de tijolos que antes faziam. Não diminuam a cota. Eles estão desocupados e, por isso, gritam: "Vamos e sacrifiquemos ao nosso Deus."

[[v2-5-9]]

^<<v2-5-9,9>>^ Imponham mais serviço a esses homens, para que se mantenham ocupados e não deem ouvidos a palavras mentirosas.

[[v2-5-10]]

^<<v2-5-10,10>>^ Então os feitores do povo e seus capatazes foram e falaram ao povo: — Assim diz Faraó: "Não fornecerei mais palha para vocês.

[[v2-5-11]]

^<<v2-5-11,11>>^ Vão vocês mesmos e ajuntem palha onde a puderem achar; porque não haverá redução no trabalho de vocês."

[[v2-5-12]]

^<<v2-5-12,12>>^ Então o povo se espalhou por toda a terra do Egito para ajuntar restolho em lugar de palha.

[[v2-5-13]]

^<<v2-5-13,13>>^ Os feitores os pressionavam, dizendo: — Terminem o trabalho de vocês, a tarefa do dia, como quando havia palha.

[[v2-5-14]]

^<<v2-5-14,14>>^ E os capatazes dos filhos de Israel, que os feitores de Faraó tinham posto sobre eles, foram açoitados. Os feitores perguntavam aos capatazes: — Por que não terminaram nem ontem nem hoje a tarefa de vocês, fazendo tijolos como antes?

[[v2-5-15]]

^<<v2-5-15,15>>^ Então os capatazes dos filhos de Israel foram se queixar a Faraó, dizendo: — Por que o senhor trata assim estes seus servos?

[[v2-5-16]]

^<<v2-5-16,16>>^ Já não nos fornecem palha, mas nos dizem: "Façam tijolos." Eis que estes seus servos são açoitados; porém o seu próprio povo é que tem a culpa.

[[v2-5-17]]

^<<v2-5-17,17>>^ Mas Faraó respondeu: — Vocês são uns desocupados! Vocês estão desocupados e, por isso, dizem: "Vamos e sacrifiquemos ao Senhor ."

[[v2-5-18]]

^<<v2-5-18,18>>^ Voltem, agora, ao trabalho. Vocês não receberão palha, mas terão de produzir a mesma quantidade de tijolos.

[[v2-5-19]]

^<<v2-5-19,19>>^ Então os capatazes dos filhos de Israel se viram em aperto, porque diziam a eles: "Não haverá redução na quantidade de tijolos, na tarefa diária de vocês."

[[v2-5-20]]

^<<v2-5-20,20>>^ Quando saíram da presença de Faraó, encontraram Moisés e Arão, que estavam à espera deles,

[[v2-5-21]]

^<<v2-5-21,21>>^ e lhes disseram: — Que o Senhor  olhe para vocês e os julgue, porque vocês nos fizeram odiosos aos olhos de Faraó e diante dos seus servos, dando-lhes a espada na mão para nos matar.

[[v2-5-22]]

^<<v2-5-22,22>>^ Então Moisés, voltando-se ao Senhor , disse: — Ó Senhor, por que afligiste este povo? Por que me enviaste?

[[v2-5-23]]

^<<v2-5-23,23>>^ Pois, desde que me apresentei a Faraó, para falar-lhe em teu nome, ele tem maltratado este povo; e tu nada fizeste para livrar o teu povo.

'''

xref:002-exodo/002-exodo-004.adoc#v2-4-0[&#60; Capítulo Anterior] | <<v2-5-0,Topo>> | xref:002-exodo/002-exodo-006.adoc#v2-6-0[Próximo Capítulo &#62;]