include::./index.adoc[]

[[v2-3-0]]
=== Êxodo, 3
// naa ?, NAA - Nova Almeida Atualizada

[[v2-3-1]]

^<<v2-3-1,1>>^ Moisés apascentava o rebanho de Jetro, o seu sogro, sacerdote de Midiã. E, levando o rebanho para o lado oeste do deserto, chegou a Horebe, o monte de Deus.

[[v2-3-2]]

^<<v2-3-2,2>>^ Ali o Anjo do Senhor  lhe apareceu numa chama de fogo, no meio de uma sarça. Moisés olhou, e eis que a sarça estava em chamas, mas não se consumia.

[[v2-3-3]]

^<<v2-3-3,3>>^ Então disse consigo mesmo: — Vou até lá para ver essa grande maravilha. Por que a sarça não se queima?

[[v2-3-4]]

^<<v2-3-4,4>>^ Quando o Senhor  viu que ele se aproximava para ver, Deus, do meio da sarça, o chamou e disse: — Moisés! Moisés! Ele respondeu: — Eis-me aqui!

[[v2-3-5]]

^<<v2-3-5,5>>^ Deus continuou: — Não se aproxime! Tire as sandálias dos pés, porque o lugar em que você está é terra santa.

[[v2-3-6]]

^<<v2-3-6,6>>^ Disse mais: — Eu sou o Deus de seu pai, o Deus de Abraão, o Deus de Isaque e o Deus de Jacó. Moisés escondeu o rosto, porque teve medo de olhar para Deus.

[[v2-3-7]]

^<<v2-3-7,7>>^ Então o Senhor  continuou: — Certamente vi a aflição do meu povo, que está no Egito, e ouvi o seu clamor por causa dos seus feitores. Conheço o sofrimento do meu povo.

[[v2-3-8]]

^<<v2-3-8,8>>^ Por isso desci a fim de livrá-lo das mãos dos egípcios e para fazê-lo sair daquela terra e levá-lo para uma terra boa e ampla, terra que mana leite e mel; o lugar do cananeu, do heteu, do amorreu, do ferezeu, do heveu e do jebuseu.

[[v2-3-9]]

^<<v2-3-9,9>>^ Pois o clamor dos filhos de Israel chegou até mim, e também vejo a opressão com que os egípcios os estão oprimindo.

[[v2-3-10]]

^<<v2-3-10,10>>^ Agora venha, e eu o enviarei a Faraó, para que você tire do Egito o meu povo, os filhos de Israel.

[[v2-3-11]]

^<<v2-3-11,11>>^ Então Moisés perguntou a Deus: — Quem sou eu para ir a Faraó e tirar do Egito os filhos de Israel?

[[v2-3-12]]

^<<v2-3-12,12>>^ Deus respondeu: — Eu estarei com você. E este será o sinal de que eu o enviei: depois que você tiver tirado o povo do Egito, vocês adorarão a Deus neste monte.

[[v2-3-13]]

^<<v2-3-13,13>>^ Moisés disse para Deus: — Eis que, quando eu for falar com os filhos de Israel e lhes disser: "O Deus dos seus pais me enviou a vocês", eles vão perguntar: "Qual é o nome dele?" E então o que lhes direi?

[[v2-3-14]]

^<<v2-3-14,14>>^ Deus disse a Moisés: — Eu Sou o Que Sou . Disse mais: — Assim você dirá aos filhos de Israel: " Eu Sou  me enviou a vocês."

[[v2-3-15]]

^<<v2-3-15,15>>^ Deus disse ainda mais a Moisés: — Assim você dirá aos filhos de Israel: "O Senhor , o Deus dos seus pais, o Deus de Abraão, o Deus de Isaque e o Deus de Jacó, me enviou a vocês. Este é o meu nome eternamente, e assim serei lembrado de geração em geração."

[[v2-3-16]]

^<<v2-3-16,16>>^ — Vá, reúna os anciãos de Israel e diga-lhes: "O Senhor , o Deus dos seus pais, o Deus de Abraão, o Deus de Isaque e o Deus de Jacó, me apareceu, dizendo: ‘Em verdade eu os tenho visitado e visto o que tem sido feito com vocês no Egito.

[[v2-3-17]]

^<<v2-3-17,17>>^ E prometi tirá-los da aflição do Egito e levá-los para a terra do cananeu, do heteu, do amorreu, do ferezeu, do heveu e do jebuseu, para uma terra que mana leite e mel.’"

[[v2-3-18]]

^<<v2-3-18,18>>^ E ouvirão o que você vai dizer. E você irá, com os anciãos de Israel, ao rei do Egito e lhe dirá: "O Senhor , o Deus dos hebreus, veio ao nosso encontro. Agora deixe-nos ir caminho de três dias ao deserto, a fim de oferecer sacrifícios ao Senhor , nosso Deus."

[[v2-3-19]]

^<<v2-3-19,19>>^ Eu sei, porém, que o rei do Egito não os deixará ir se não for obrigado por mão forte.

[[v2-3-20]]

^<<v2-3-20,20>>^ Portanto, estenderei a mão e ferirei o Egito com todos os meus prodígios que farei no meio dele. Depois disso, o rei os deixará ir.

[[v2-3-21]]

^<<v2-3-21,21>>^ — Eu farei com que este povo encontre favor diante dos egípcios; e, quando vocês saírem, não será de mãos vazias.

[[v2-3-22]]

^<<v2-3-22,22>>^ Cada mulher pedirá à sua vizinha e à mulher que estiver hospedada em sua casa objetos de prata, objetos de ouro e roupas, que vocês porão sobre os seus filhos e sobre as suas filhas. E assim vocês despojarão os egípcios.

'''

xref:002-exodo/002-exodo-002.adoc#v2-2-0[&#60; Capítulo Anterior] | <<v2-3-0,Topo>> | xref:002-exodo/002-exodo-004.adoc#v2-4-0[Próximo Capítulo &#62;]