include::./index.adoc[]

[[v2-20-0]]
=== Êxodo, 20
// naa ?, NAA - Nova Almeida Atualizada

[[v2-20-1]]

^<<v2-20-1,1>>^ Então Deus falou todas estas palavras:

[[v2-20-2]]

^<<v2-20-2,2>>^ — Eu sou o Senhor , seu Deus, que o tirei da terra do Egito, da casa da servidão.

[[v2-20-3]]

^<<v2-20-3,3>>^ — Não tenha outros deuses diante de mim.

[[v2-20-4]]

^<<v2-20-4,4>>^ — Não faça para você imagem de escultura, nem semelhança alguma do que há em cima no céu, nem embaixo na terra, nem nas águas debaixo da terra.

[[v2-20-5]]

^<<v2-20-5,5>>^ Não adore essas coisas, nem preste culto a elas, porque eu, o Senhor , seu Deus, sou Deus zeloso, que visito a iniquidade dos pais nos filhos até a terceira e quarta geração daqueles que me odeiam,

[[v2-20-6]]

^<<v2-20-6,6>>^ mas faço misericórdia até mil gerações daqueles que me amam e guardam os meus mandamentos.

[[v2-20-7]]

^<<v2-20-7,7>>^ — Não tome o nome do Senhor , seu Deus, em vão, porque o Senhor  não terá por inocente o que tomar o seu nome em vão.

[[v2-20-8]]

^<<v2-20-8,8>>^ — Lembre-se do dia de sábado, para o santificar.

[[v2-20-9]]

^<<v2-20-9,9>>^ Seis dias você trabalhará e fará toda a sua obra,

[[v2-20-10]]

^<<v2-20-10,10>>^ mas o sétimo dia é o sábado dedicado ao Senhor , seu Deus. Não faça nenhum trabalho nesse dia, nem você, nem o seu filho, nem a sua filha, nem o seu servo, nem a sua serva, nem o seu animal, nem o estrangeiro das suas portas para dentro.

[[v2-20-11]]

^<<v2-20-11,11>>^ Porque em seis dias o Senhor  fez os céus e a terra, o mar e tudo o que neles há e, ao sétimo dia, descansou; por isso o Senhor  abençoou o dia de sábado e o santificou.

[[v2-20-12]]

^<<v2-20-12,12>>^ — Honre o seu pai e a sua mãe, para que você tenha uma longa vida na terra que o Senhor , seu Deus, lhe dá.

[[v2-20-13]]

^<<v2-20-13,13>>^ — Não mate.

[[v2-20-14]]

^<<v2-20-14,14>>^ — Não cometa adultério.

[[v2-20-15]]

^<<v2-20-15,15>>^ — Não furte.

[[v2-20-16]]

^<<v2-20-16,16>>^ — Não dê falso testemunho contra o seu próximo.

[[v2-20-17]]

^<<v2-20-17,17>>^ — Não cobice a casa do seu próximo. Não cobice a mulher do seu próximo, nem o seu servo, nem a sua serva, nem o seu boi, nem o seu jumento, nem coisa alguma que pertença ao seu próximo.

[[v2-20-18]]

^<<v2-20-18,18>>^ Todo o povo presenciou os trovões, os relâmpagos, o som da trombeta e o monte fumegante; e o povo, observando, tremeu de medo e ficou de longe.

[[v2-20-19]]

^<<v2-20-19,19>>^ Disseram a Moisés: — Fale-nos você, e ouviremos; porém não fale Deus conosco, para que não morramos.

[[v2-20-20]]

^<<v2-20-20,20>>^ Moisés respondeu ao povo: — Não tenham medo; Deus veio para provar vocês e para que o seu temor esteja diante de vocês, a fim de que não pequem.

[[v2-20-21]]

^<<v2-20-21,21>>^ O povo estava de longe, em pé; Moisés, porém, se aproximou da nuvem escura onde Deus estava.

[[v2-20-22]]

^<<v2-20-22,22>>^ Então o Senhor  disse a Moisés: — Assim você dirá aos filhos de Israel: "Vocês viram que dos céus eu lhes falei.

[[v2-20-23]]

^<<v2-20-23,23>>^ Não façam deuses de prata ao lado de mim, nem façam para vocês deuses de ouro.

[[v2-20-24]]

^<<v2-20-24,24>>^ Façam um altar de terra para mim e sobre ele vocês sacrificarão os seus holocaustos, as suas ofertas pacíficas, as suas ovelhas e os seus bois; em todo lugar onde eu fizer celebrar a memória do meu nome, virei até vocês e os abençoarei.

[[v2-20-25]]

^<<v2-20-25,25>>^ Se vocês fizerem um altar de pedras para mim, não o façam de pedras lavradas; pois, se fizerem uso de ferramentas, vocês terão profanado o altar.

[[v2-20-26]]

^<<v2-20-26,26>>^ Nem subam ao meu altar por degraus, para que ali não seja exposta a sua nudez."

'''

xref:002-exodo/002-exodo-019.adoc#v2-19-0[&#60; Capítulo Anterior] | <<v2-20-0,Topo>> | xref:002-exodo/002-exodo-021.adoc#v2-21-0[Próximo Capítulo &#62;]