include::./index.adoc[]

[[v2-37-0]]
=== Êxodo, 37
// naa ?, NAA - Nova Almeida Atualizada

[[v2-37-1]]

^<<v2-37-1,1>>^ Bezalel fez também a arca de madeira de acácia, de um metro e dez de comprimento, sessenta e seis centímetros de largura e sessenta e seis de altura.

[[v2-37-2]]

^<<v2-37-2,2>>^ Ele a revestiu de ouro puro, por dentro e por fora, e pôs um remate de ouro ao redor.

[[v2-37-3]]

^<<v2-37-3,3>>^ Fundiu para ela quatro argolas de ouro e fixou-as nos quatro cantos da arca: duas argolas num lado dela e duas argolas no outro lado.

[[v2-37-4]]

^<<v2-37-4,4>>^ Fez também cabos grossos de madeira de acácia e os revestiu de ouro.

[[v2-37-5]]

^<<v2-37-5,5>>^ Passou os cabos pelas argolas nos lados da arca, para que ela pudesse ser carregada por meio deles.

[[v2-37-6]]

^<<v2-37-6,6>>^ Fez também o propiciatório de ouro puro, de um metro e dez de comprimento e sessenta e seis centímetros de largura.

[[v2-37-7]]

^<<v2-37-7,7>>^ Fez também dois querubins de ouro, nas duas extremidades do propiciatório.

[[v2-37-8]]

^<<v2-37-8,8>>^ Um querubim, na extremidade de uma parte, e o outro, na extremidade da outra parte; de uma só peça com o propiciatório fez os querubins nas duas extremidades dele.

[[v2-37-9]]

^<<v2-37-9,9>>^ Os querubins estendiam as asas por cima, cobrindo com elas o propiciatório. Estavam de frente um para o outro, olhando para o propiciatório.

[[v2-37-10]]

^<<v2-37-10,10>>^ Fez também a mesa de madeira de acácia. Tinha o comprimento de oitenta e oito centímetros, a largura de quarenta e quatro centímetros, e a altura de sessenta e seis centímetros.

[[v2-37-11]]

^<<v2-37-11,11>>^ Revestiu-a de ouro puro e pôs um remate de ouro ao redor.

[[v2-37-12]]

^<<v2-37-12,12>>^ Também lhe fez uma borda ao redor, da largura de quatro dedos, e pôs um remate ao redor da borda.

[[v2-37-13]]

^<<v2-37-13,13>>^ Também fez quatro argolas de ouro e fixou-as nos quatro cantos que estavam nos quatro pés da mesa.

[[v2-37-14]]

^<<v2-37-14,14>>^ Perto da borda estavam as argolas, como lugares para os cabos, para carregar a mesa.

[[v2-37-15]]

^<<v2-37-15,15>>^ Fez os cabos de madeira de acácia e revestiu-os de ouro, para que a mesa pudesse ser carregada por meio deles.

[[v2-37-16]]

^<<v2-37-16,16>>^ Também fez de ouro puro os utensílios que deveriam estar sobre a mesa: os seus pratos, os seus recipientes para incenso, as suas jarras e as suas taças em que seriam oferecidas as libações.

[[v2-37-17]]

^<<v2-37-17,17>>^ Fez também o candelabro de ouro puro; de ouro batido o fez. O seu pedestal, a sua haste, os seus cálices, as suas maçanetas e as suas flores formavam com ele uma só peça.

[[v2-37-18]]

^<<v2-37-18,18>>^ Seis hastes saíam dos lados do candelabro; três de um lado e três do outro.

[[v2-37-19]]

^<<v2-37-19,19>>^ Numa haste havia três cálices com formato de amêndoas, uma maçaneta e uma flor; na outra haste havia três cálices com formato de amêndoas, uma maçaneta e uma flor; assim eram as seis hastes que saíam do candelabro.

[[v2-37-20]]

^<<v2-37-20,20>>^ Mas no candelabro mesmo havia quatro cálices com formato de amêndoas, com suas maçanetas e com suas flores.

[[v2-37-21]]

^<<v2-37-21,21>>^ Havia uma maçaneta sob duas hastes que saíam dele; e ainda uma maçaneta sob duas outras hastes que saíam dele; e ainda mais uma maçaneta sob duas outras hastes que saíam dele; assim se fez com as seis hastes que saíam do candelabro.

[[v2-37-22]]

^<<v2-37-22,22>>^ As maçanetas e as hastes do candelabro formavam uma só peça com o mesmo; tudo era de uma só peça, obra batida de ouro puro.

[[v2-37-23]]

^<<v2-37-23,23>>^ Fez também as sete lâmpadas do candelabro. As suas tesouras de cortar pavios e os seus apagadores eram de ouro puro.

[[v2-37-24]]

^<<v2-37-24,24>>^ Com trinta e quatro quilos de ouro puro se fez o candelabro com todos os seus utensílios.

[[v2-37-25]]

^<<v2-37-25,25>>^ Fez de madeira de acácia o altar do incenso. Era quadrado, tendo quarenta e cinco centímetros de comprimento e quarenta e cinco de largura; a altura era de noventa centímetros. Os chifres formavam uma só peça com ele.

[[v2-37-26]]

^<<v2-37-26,26>>^ Revestiu-o de ouro puro, a parte superior, as paredes ao redor e os chifres; pôs também um remate de ouro ao redor.

[[v2-37-27]]

^<<v2-37-27,27>>^ Fez também duas argolas de ouro e colocou-as debaixo do remate, de ambos os lados. Por essas argolas foram passadas os cabos, para que se pudesse levar o altar.

[[v2-37-28]]

^<<v2-37-28,28>>^ Fez esses cabos de madeira de acácia, revestindo-os de ouro.

[[v2-37-29]]

^<<v2-37-29,29>>^ Fez também o óleo sagrado para a unção e o incenso aromático, puro, segundo a arte do perfumista.

'''

xref:002-exodo/002-exodo-036.adoc#v2-36-0[&#60; Capítulo Anterior] | <<v2-37-0,Topo>> | xref:002-exodo/002-exodo-038.adoc#v2-38-0[Próximo Capítulo &#62;]