include::./index.adoc[]

[[v2-35-0]]
=== Êxodo, 35
// naa ?, NAA - Nova Almeida Atualizada

[[v2-35-1]]

^<<v2-35-1,1>>^ Moisés convocou toda a congregação dos filhos de Israel e lhes disse: — São estas as palavras que o Senhor  ordenou que se cumprissem:

[[v2-35-2]]

^<<v2-35-2,2>>^ Seis dias vocês trabalharão, mas o sétimo dia lhes será santo, o sábado do repouso solene ao Senhor ; quem nele trabalhar morrerá.

[[v2-35-3]]

^<<v2-35-3,3>>^ Não acendam fogo em nenhuma das suas moradas no dia do sábado.

[[v2-35-4]]

^<<v2-35-4,4>>^ Moisés disse a toda a congregação dos filhos de Israel: — Esta é a palavra que o Senhor  ordenou, dizendo:

[[v2-35-5]]

^<<v2-35-5,5>>^ Separem do que vocês têm uma oferta ao Senhor . Cada um, de coração disposto, voluntariamente a trará por oferta ao Senhor : ouro, prata, bronze,

[[v2-35-6]]

^<<v2-35-6,6>>^ pano azul, púrpura, carmesim, linho fino, pelos de cabra,

[[v2-35-7]]

^<<v2-35-7,7>>^ peles de carneiro tingidas de vermelho, peles finas, madeira de acácia,

[[v2-35-8]]

^<<v2-35-8,8>>^ azeite para a iluminação, especiarias para o óleo da unção e para o incenso aromático,

[[v2-35-9]]

^<<v2-35-9,9>>^ pedras de ônix e pedras de engaste para a estola sacerdotal e para o peitoral.

[[v2-35-10]]

^<<v2-35-10,10>>^ — Venham todos os homens hábeis entre vocês e façam tudo o que o Senhor  ordenou:

[[v2-35-11]]

^<<v2-35-11,11>>^ o tabernáculo com a sua tenda e a sua cobertura, os seus ganchos, as suas tábuas, as suas vigas superiores, as suas colunas e as suas bases;

[[v2-35-12]]

^<<v2-35-12,12>>^ a arca e os seus cabos, o propiciatório e o véu do cortinado;

[[v2-35-13]]

^<<v2-35-13,13>>^ a mesa e os seus cabos, todos os seus utensílios e os pães da proposição;

[[v2-35-14]]

^<<v2-35-14,14>>^ o candelabro da iluminação, os seus utensílios, as suas lâmpadas e o azeite para a iluminação;

[[v2-35-15]]

^<<v2-35-15,15>>^ o altar do incenso e os seus cabos, o óleo da unção, o incenso aromático e o cortinado da porta à entrada do tabernáculo;

[[v2-35-16]]

^<<v2-35-16,16>>^ o altar do holocausto e a sua grelha de bronze, os seus cabos e todos os seus utensílios, a bacia e o seu suporte;

[[v2-35-17]]

^<<v2-35-17,17>>^ as cortinas do átrio, as suas colunas, as suas bases e o cortinado da porta do átrio;

[[v2-35-18]]

^<<v2-35-18,18>>^ as estacas do tabernáculo, as estacas do átrio e as suas cordas;

[[v2-35-19]]

^<<v2-35-19,19>>^ as vestes do ministério para ministrar no santuário, as vestes santas do sacerdote Arão e as vestes de seus filhos, para oficiarem como sacerdotes.

[[v2-35-20]]

^<<v2-35-20,20>>^ Então toda a congregação dos filhos de Israel saiu da presença de Moisés.

[[v2-35-21]]

^<<v2-35-21,21>>^ Todo aquele cujo coração o moveu e cujo espírito o impeliu veio e trouxe a oferta ao Senhor  para a obra da tenda do encontro, para todo o seu serviço e para as vestes sagradas.

[[v2-35-22]]

^<<v2-35-22,22>>^ Vieram homens e mulheres, todos dispostos de coração. Trouxeram fivelas, pendentes, anéis, braceletes, todos os objetos de ouro; todo homem fazia oferta de ouro ao Senhor .

[[v2-35-23]]

^<<v2-35-23,23>>^ E todos os que tinham pano azul, púrpura, carmesim, linho fino, pelos de cabra, peles de carneiro tingidas de vermelho e peles de animais marinhos trouxeram isso também.

[[v2-35-24]]

^<<v2-35-24,24>>^ Todo aquele que fazia oferta de prata ou de bronze trazia isso como oferta ao Senhor ; e todo aquele que possuía madeira de acácia para toda obra do serviço a trazia também.

[[v2-35-25]]

^<<v2-35-25,25>>^ Todas as mulheres hábeis traziam o que, por suas próprias mãos, tinham fiado: pano azul, púrpura, carmesim e linho fino.

[[v2-35-26]]

^<<v2-35-26,26>>^ E todas as mulheres cujo coração as moveu em habilidade fiavam os pelos de cabra.

[[v2-35-27]]

^<<v2-35-27,27>>^ Os chefes traziam pedras de ônix, pedras de engaste para a estola sacerdotal e para o peitoral,

[[v2-35-28]]

^<<v2-35-28,28>>^ as especiarias e o azeite para a iluminação, para o óleo da unção e para o incenso aromático.

[[v2-35-29]]

^<<v2-35-29,29>>^ Os filhos de Israel trouxeram oferta voluntária ao Senhor , a saber, todo homem e mulher cujo coração os dispôs para trazerem uma oferta para toda a obra que o Senhor  havia ordenado que se fizesse por meio de Moisés.

[[v2-35-30]]

^<<v2-35-30,30>>^ Moisés disse aos filhos de Israel: — Eis que o Senhor  chamou por nome Bezalel, filho de Uri, filho de Hur, da tribo de Judá,

[[v2-35-31]]

^<<v2-35-31,31>>^ e o Espírito de Deus o encheu de habilidade, inteligência e conhecimento em todo artifício,

[[v2-35-32]]

^<<v2-35-32,32>>^ para elaborar desenhos e trabalhar em ouro, em prata, em bronze,

[[v2-35-33]]

^<<v2-35-33,33>>^ para lapidação de pedras de engaste, para entalho de madeira e para todo tipo de trabalho artesanal.

[[v2-35-34]]

^<<v2-35-34,34>>^ Também lhe dispôs o coração para ensinar os outros, tanto a ele como a Aoliabe, filho de Aisamaque, da tribo de Dã.

[[v2-35-35]]

^<<v2-35-35,35>>^ Encheu-os de habilidade para fazer toda obra de mestre, até a mais engenhosa, e a do bordador em pano azul, em púrpura, em carmesim e em linho fino, e a do tecelão, sim, todo tipo de trabalho e a elaborar desenhos.

'''

xref:002-exodo/002-exodo-034.adoc#v2-34-0[&#60; Capítulo Anterior] | <<v2-35-0,Topo>> | xref:002-exodo/002-exodo-036.adoc#v2-36-0[Próximo Capítulo &#62;]