include::./index.adoc[]

[[v2-22-0]]
=== Êxodo, 22
// naa ?, NAA - Nova Almeida Atualizada

[[v2-22-1]]

^<<v2-22-1,1>>^ — Se alguém furtar um boi ou uma ovelha e abater ou vender o animal, por um boi pagará cinco bois, e quatro ovelhas por uma ovelha.

[[v2-22-2]]

^<<v2-22-2,2>>^ — Se um ladrão for achado arrombando uma casa e, sendo ferido, morrer, quem o feriu não será culpado do sangue.

[[v2-22-3]]

^<<v2-22-3,3>>^ Se, porém, já havia sol quando isso aconteceu, quem o feriu será culpado do sangue. O ladrão deverá fazer restituição total. Se não tiver com que pagar, será vendido por seu furto.

[[v2-22-4]]

^<<v2-22-4,4>>^ Se aquilo que roubou for achado vivo em seu poder, seja boi, jumento ou ovelha, pagará o dobro.

[[v2-22-5]]

^<<v2-22-5,5>>^ — Se alguém fizer pastar o seu animal num campo ou numa vinha e o largar para comer em campo de outra pessoa, pagará com o melhor do seu próprio campo e o melhor da sua própria vinha.

[[v2-22-6]]

^<<v2-22-6,6>>^ — Se irromper fogo, e pegar nos espinheiros, e destruir os feixes de cereal colhido, ou a plantação que já estiver madura, ou o campo todo, aquele que acendeu o fogo pagará totalmente o queimado.

[[v2-22-7]]

^<<v2-22-7,7>>^ — Se alguém der ao seu próximo dinheiro ou objetos para guardar, e isso for furtado àquele que o recebeu, o ladrão, se for achado, pagará o dobro.

[[v2-22-8]]

^<<v2-22-8,8>>^ Se o ladrão não for achado, então o dono da casa será levado diante dos juízes, a ver se não meteu a mão nos bens do próximo.

[[v2-22-9]]

^<<v2-22-9,9>>^ — Em todo negócio fraudulento, seja a respeito de boi, ou de jumento, ou de ovelhas, ou de roupas, ou de qualquer coisa perdida, de que uma das partes diz: "Isto é meu", a causa de ambas as partes será levada diante dos juízes; aquele a quem os juízes condenarem pagará o dobro ao seu próximo.

[[v2-22-10]]

^<<v2-22-10,10>>^ — Se alguém der ao seu próximo um animal para que tome conta dele, seja jumento, boi, ovelha ou outro animal qualquer, e este morrer, ficar aleijado ou for afugentado, sem que ninguém o veja,

[[v2-22-11]]

^<<v2-22-11,11>>^ então haverá juramento do Senhor  entre ambos, de que não meteu a mão nos bens do seu próximo; o dono aceitará o juramento, e o outro não fará restituição.

[[v2-22-12]]

^<<v2-22-12,12>>^ Porém, se, de fato, o animal tiver sido furtado, terá de pagá-lo ao seu dono.

[[v2-22-13]]

^<<v2-22-13,13>>^ Se for dilacerado, trará o que restou em testemunho disso e não pagará o animal dilacerado.

[[v2-22-14]]

^<<v2-22-14,14>>^ — Se alguém pedir emprestado a seu próximo um animal, e este ficar aleijado ou morrer, não estando presente o dono, aquele que pediu emprestado terá de pagá-lo ao seu dono.

[[v2-22-15]]

^<<v2-22-15,15>>^ Se o dono esteve presente, não o pagará; se foi alugado, o preço do aluguel será o pagamento.

[[v2-22-16]]

^<<v2-22-16,16>>^ — Se alguém seduzir uma virgem que ainda não foi prometida em casamento e tiver relações com ela, pagará seu dote e a tomará por mulher.

[[v2-22-17]]

^<<v2-22-17,17>>^ Se o pai dela definitivamente não quiser dar-lhe a moça em casamento, aquele que a seduziu pagará em dinheiro conforme o dote das virgens.

[[v2-22-18]]

^<<v2-22-18,18>>^ — A feiticeira você não deixará viver.

[[v2-22-19]]

^<<v2-22-19,19>>^ — Quem tiver coito com animal será morto.

[[v2-22-20]]

^<<v2-22-20,20>>^ — Quem sacrificar aos deuses e não somente ao Senhor  será destruído.

[[v2-22-21]]

^<<v2-22-21,21>>^ — Não maltrate o estrangeiro, nem o oprima; porque vocês foram estrangeiros na terra do Egito.

[[v2-22-22]]

^<<v2-22-22,22>>^ Não maltratem as viúvas nem os órfãos.

[[v2-22-23]]

^<<v2-22-23,23>>^ Se de algum modo os maltratarem, e eles clamarem a mim, eu lhes ouvirei o clamor;

[[v2-22-24]]

^<<v2-22-24,24>>^ a minha ira se acenderá, e eu matarei vocês à espada; as suas mulheres ficarão viúvas, e os seus filhos ficarão órfãos.

[[v2-22-25]]

^<<v2-22-25,25>>^ — Se você emprestar dinheiro a alguém do meu povo, ao pobre que está com você, não trate com ele como um credor que impõe juros.

[[v2-22-26]]

^<<v2-22-26,26>>^ Se você pegar o manto do seu próximo como penhor, devolva-o antes do pôr do sol,

[[v2-22-27]]

^<<v2-22-27,27>>^ porque é com ele que se cobre, é a roupa do seu corpo; em que ele se deitaria? Quando ele clamar a mim, eu o ouvirei, porque sou misericordioso.

[[v2-22-28]]

^<<v2-22-28,28>>^ — Não blasfeme contra Deus, nem amaldiçoe uma autoridade do seu povo.

[[v2-22-29]]

^<<v2-22-29,29>>^ — Não demore em trazer ofertas do melhor das suas colheitas e das suas vinhas; entregue-me o primogênito dos seus filhos.

[[v2-22-30]]

^<<v2-22-30,30>>^ Faça o mesmo com as suas vacas e com as suas ovelhas; deixe que a cria fique sete dias com a mãe, mas no oitavo dia você a entregará para mim.

[[v2-22-31]]

^<<v2-22-31,31>>^ — Vocês serão homens consagrados a mim; portanto, não comam carne de animais dilacerados no campo; joguem essa carne aos cães.

'''

xref:002-exodo/002-exodo-021.adoc#v2-21-0[&#60; Capítulo Anterior] | <<v2-22-0,Topo>> | xref:002-exodo/002-exodo-023.adoc#v2-23-0[Próximo Capítulo &#62;]