include::./index.adoc[]

[[v2-32-0]]
=== Êxodo, 32
// naa ?, NAA - Nova Almeida Atualizada

[[v2-32-1]]

^<<v2-32-1,1>>^ O povo viu que Moisés demorava para descer do monte. Então reuniu-se em volta de Arão e lhe disse: — Levante-se, faça para nós deuses que vão adiante de nós; pois, quanto a este Moisés, o homem que nos tirou do Egito, não sabemos o que lhe aconteceu.

[[v2-32-2]]

^<<v2-32-2,2>>^ Arão respondeu: — Tirem as argolas de ouro das orelhas de suas mulheres, de seus filhos e de suas filhas e tragam para mim.

[[v2-32-3]]

^<<v2-32-3,3>>^ Então todo o povo tirou das orelhas as argolas e as trouxe a Arão.

[[v2-32-4]]

^<<v2-32-4,4>>^ Este, recebendo-as das mãos deles, trabalhou o ouro com buril e fez dele um bezerro de metal fundido. Então disseram: — São estes, ó Israel, os seus deuses, que tiraram você da terra do Egito.

[[v2-32-5]]

^<<v2-32-5,5>>^ Arão, vendo isso, edificou um altar diante do bezerro e fez a seguinte proclamação: — Amanhã haverá festa ao Senhor .

[[v2-32-6]]

^<<v2-32-6,6>>^ No dia seguinte, madrugaram, ofereceram holocaustos e trouxeram ofertas pacíficas. E o povo sentou-se para comer e beber e levantou-se para se divertir.

[[v2-32-7]]

^<<v2-32-7,7>>^ Então o Senhor  disse a Moisés: — Vá, desça; porque o seu povo, o povo que você tirou do Egito, se corrompeu

[[v2-32-8]]

^<<v2-32-8,8>>^ e depressa se desviou do caminho que eu lhe havia ordenado; fez para si um bezerro de metal fundido, o adorou e lhe ofereceu sacrifícios, dizendo: "São estes, ó Israel, os seus deuses, que tiraram você da terra do Egito."

[[v2-32-9]]

^<<v2-32-9,9>>^ O Senhor  disse ainda a Moisés: — Tenho visto este povo, e eis que é povo teimoso.

[[v2-32-10]]

^<<v2-32-10,10>>^ Agora, pois, deixe-me, para que se acenda contra eles o meu furor, e eu os consuma; e de você farei uma grande nação.

[[v2-32-11]]

^<<v2-32-11,11>>^ Porém Moisés suplicou ao Senhor , seu Deus, dizendo: — Ó Senhor , por que se acende a tua ira contra o teu povo, que tiraste da terra do Egito com grande poder e forte mão?

[[v2-32-12]]

^<<v2-32-12,12>>^ Por que deixar que os egípcios digam: "Ele os tirou de lá com más intenções, para matá-los nos montes e para eliminá-los da face da terra"? Deixa de lado o furor da tua ira e muda de ideia quanto a este mal contra o teu povo.

[[v2-32-13]]

^<<v2-32-13,13>>^ Lembra-te de Abraão, de Isaque e de Israel, teus servos, aos quais por ti mesmo juraste, dizendo: "Multiplicarei a descendência de vocês como as estrelas do céu, e toda esta terra de que tenho falado, eu a darei à sua descendência, para que a possuam por herança eternamente."

[[v2-32-14]]

^<<v2-32-14,14>>^ Então o Senhor  mudou de ideia quanto ao mal que ele tinha dito que traria sobre o povo.

[[v2-32-15]]

^<<v2-32-15,15>>^ Moisés voltou-se e desceu do monte com as duas tábuas do testemunho nas mãos, tábuas escritas de ambos os lados; de um e de outro lado estavam escritas.

[[v2-32-16]]

^<<v2-32-16,16>>^ As tábuas eram obra de Deus; também o que estava escrito tinha sido escrito pelo próprio Deus, esculpido nas tábuas.

[[v2-32-17]]

^<<v2-32-17,17>>^ Quando Josué ouviu a voz do povo que gritava, disse a Moisés: — Há um alarido de guerra no arraial.

[[v2-32-18]]

^<<v2-32-18,18>>^ Moisés respondeu: — O que ouço não é alarido de vencedores nem de vencidos, mas o alarido de pessoas cantando.

[[v2-32-19]]

^<<v2-32-19,19>>^ Logo que se aproximou do arraial e viu o bezerro e as danças, Moisés ficou muito irado. Arremessou as tábuas de pedra das suas mãos e quebrou-as ao pé do monte.

[[v2-32-20]]

^<<v2-32-20,20>>^ E, pegando o bezerro que tinham feito, queimou-o e o reduziu a pó, que espalhou sobre a água, e deu de beber aos filhos de Israel.

[[v2-32-21]]

^<<v2-32-21,21>>^ Depois, Moisés perguntou a Arão: — O que foi que esse povo fez a você, para que você trouxesse sobre ele tão grande pecado?

[[v2-32-22]]

^<<v2-32-22,22>>^ Arão respondeu: — Não fique irado, meu senhor. Você sabe que este povo é propenso para o mal.

[[v2-32-23]]

^<<v2-32-23,23>>^ Pois me disseram: "Faça para nós deuses que vão adiante de nós; pois, quanto a este Moisés, o homem que nos tirou da terra do Egito, não sabemos o que lhe aconteceu."

[[v2-32-24]]

^<<v2-32-24,24>>^ Então eu lhes disse: "Quem tem ouro, tire-o." Eles o deram para mim, eu o lancei no fogo, e saiu este bezerro.

[[v2-32-25]]

^<<v2-32-25,25>>^ Quando Moisés viu que o povo estava sem controle, pois Arão o tinha deixado à solta para vergonha no meio dos seus inimigos,

[[v2-32-26]]

^<<v2-32-26,26>>^ pôs-se em pé à entrada do arraial e disse: — Quem é do Senhor  venha até mim. Então se juntaram a ele todos os filhos de Levi,

[[v2-32-27]]

^<<v2-32-27,27>>^ aos quais ele disse: — Assim diz o Senhor , o Deus de Israel: "Cada um ponha a espada na cintura. Passem e tornem a passar pelo arraial de porta em porta, e cada um mate o seu irmão, o seu amigo e o seu vizinho."

[[v2-32-28]]

^<<v2-32-28,28>>^ E os filhos de Levi fizeram segundo a palavra de Moisés e, naquele dia, morreram uns três mil homens.

[[v2-32-29]]

^<<v2-32-29,29>>^ Pois Moisés tinha dito: "Consagrem-se hoje ao Senhor , cada um contra o seu filho e contra o seu irmão, para que hoje Deus lhes conceda uma bênção."

[[v2-32-30]]

^<<v2-32-30,30>>^ No dia seguinte, Moisés disse ao povo: — Vocês cometeram um grande pecado. Agora, porém, subirei ao Senhor ; talvez eu possa fazer propiciação pelo pecado de vocês.

[[v2-32-31]]

^<<v2-32-31,31>>^ Moisés voltou ao Senhor  e disse: — Ah! O povo cometeu grande pecado, fazendo para si deuses de ouro.

[[v2-32-32]]

^<<v2-32-32,32>>^ Agora, pois, perdoa-lhe o pecado; ou, se não, peço-te que me risques do livro que escreveste.

[[v2-32-33]]

^<<v2-32-33,33>>^ Então o Senhor  disse a Moisés: — Riscarei do meu livro todo aquele que pecar contra mim.

[[v2-32-34]]

^<<v2-32-34,34>>^ Vá, pois, agora, e conduza o povo para o lugar do qual falei a você. Eis que o meu Anjo irá adiante de você. Porém, no dia da minha visitação, eu os castigarei pelo pecado que cometeram.

[[v2-32-35]]

^<<v2-32-35,35>>^ Assim, o Senhor  feriu o povo, porque fizeram o bezerro — aquele que Arão tinha feito.

'''

xref:002-exodo/002-exodo-031.adoc#v2-31-0[&#60; Capítulo Anterior] | <<v2-32-0,Topo>> | xref:002-exodo/002-exodo-033.adoc#v2-33-0[Próximo Capítulo &#62;]