include::./index.adoc[]

[[v2-36-0]]
=== Êxodo, 36
// naa ?, NAA - Nova Almeida Atualizada

[[v2-36-1]]

^<<v2-36-1,1>>^ Assim, trabalharam Bezalel, Aoliabe e todos os homens hábeis a quem o Senhor  tinha dado habilidade e inteligência para saberem fazer toda obra para o serviço do santuário, segundo tudo o que o Senhor  havia ordenado.

[[v2-36-2]]

^<<v2-36-2,2>>^ Moisés chamou Bezalel, Aoliabe e todos os homens hábeis em cujo coração o Senhor  tinha posto sabedoria, isto é, todos os homens cujo coração os impeliu a vir e fazer a obra.

[[v2-36-3]]

^<<v2-36-3,3>>^ Estes receberam de Moisés todas as ofertas que os filhos de Israel haviam trazido para a obra do serviço do santuário, para fazê-la; e, ainda, cada manhã o povo trazia a Moisés ofertas voluntárias.

[[v2-36-4]]

^<<v2-36-4,4>>^ Então todos os homens sábios que se ocupavam em toda a obra do santuário deixaram o que faziam, vieram

[[v2-36-5]]

^<<v2-36-5,5>>^ e disseram a Moisés: — O povo traz muito mais do que é necessário para o serviço da obra que o Senhor  ordenou que se fizesse.

[[v2-36-6]]

^<<v2-36-6,6>>^ Então Moisés ordenou e a ordem foi proclamada no arraial: — Nenhum homem ou mulher faça mais obra alguma para a oferta do santuário. Assim, o povo foi proibido de trazer mais.

[[v2-36-7]]

^<<v2-36-7,7>>^ Porque o material que tinham era suficiente para toda a obra que se devia fazer e ainda sobrava.

[[v2-36-8]]

^<<v2-36-8,8>>^ Assim, todos os homens hábeis, entre os que faziam a obra, fizeram o tabernáculo com dez cortinas de linho fino retorcido, pano azul, púrpura e carmesim com querubins; de obra de artista as fizeram.

[[v2-36-9]]

^<<v2-36-9,9>>^ O comprimento de cada cortina era de doze metros e meio, e a largura era de um metro e oitenta; todas as cortinas tinham a mesma medida.

[[v2-36-10]]

^<<v2-36-10,10>>^ Cinco cortinas eram ligadas umas às outras; e as outras cinco também eram ligadas umas às outras.

[[v2-36-11]]

^<<v2-36-11,11>>^ Fizeram laçadas de pano azul na borda da cortina que estava na extremidade do primeiro agrupamento; e fizeram o mesmo com a borda da cortina que estava na extremidade do segundo agrupamento.

[[v2-36-12]]

^<<v2-36-12,12>>^ Fizeram cinquenta laçadas numa cortina, e cinquenta laçadas na outra cortina na extremidade do segundo agrupamento; as laçadas eram contrapostas uma à outra.

[[v2-36-13]]

^<<v2-36-13,13>>^ Fizeram cinquenta colchetes de ouro, com os quais prenderam as cortinas uma à outra; e o tabernáculo passou a ser um todo.

[[v2-36-14]]

^<<v2-36-14,14>>^ Fizeram também de pelos de cabra cortinas para servirem de tenda sobre o tabernáculo; fizeram onze cortinas.

[[v2-36-15]]

^<<v2-36-15,15>>^ O comprimento de cada cortina era de treze metros e trinta, e a largura era de um metro e oitenta; as onze cortinas tinham a mesma medida.

[[v2-36-16]]

^<<v2-36-16,16>>^ Juntaram cinco cortinas entre si e, de igual modo, as seis restantes.

[[v2-36-17]]

^<<v2-36-17,17>>^ Fizeram cinquenta laçadas na borda da cortina que estava na extremidade do primeiro agrupamento e cinquenta laçadas na borda da cortina que estava na extremidade do segundo agrupamento.

[[v2-36-18]]

^<<v2-36-18,18>>^ Fizeram também cinquenta colchetes de bronze para ajuntar a tenda, para que viesse a ser um todo.

[[v2-36-19]]

^<<v2-36-19,19>>^ Fizeram também de peles de carneiro tingidas de vermelho uma cobertura para a tenda e outra cobertura de peles finas.

[[v2-36-20]]

^<<v2-36-20,20>>^ Fizeram também de madeira de acácia as tábuas para o tabernáculo, as quais eram colocadas verticalmente.

[[v2-36-21]]

^<<v2-36-21,21>>^ Cada uma das tábuas tinha quatro metros e meio de comprimento e sessenta e sete centímetros de largura.

[[v2-36-22]]

^<<v2-36-22,22>>^ Cada tábua tinha dois encaixes, para que se pudesse unir uma tábua à outra; assim fizeram com todas as tábuas do tabernáculo.

[[v2-36-23]]

^<<v2-36-23,23>>^ No preparar as tábuas para o tabernáculo, colocaram vinte delas para o lado sul.

[[v2-36-24]]

^<<v2-36-24,24>>^ Fizeram também quarenta bases de prata debaixo das vinte tábuas: duas bases debaixo de uma tábua para os seus dois encaixes e duas bases debaixo de outra tábua para os seus dois encaixes.

[[v2-36-25]]

^<<v2-36-25,25>>^ Também fizeram vinte tábuas ao outro lado do tabernáculo, para o lado norte,

[[v2-36-26]]

^<<v2-36-26,26>>^ com as suas quarenta bases de prata: duas bases debaixo de uma tábua e duas bases debaixo de outra tábua.

[[v2-36-27]]

^<<v2-36-27,27>>^ Para o lado posterior do tabernáculo, o lado oeste, fizeram seis tábuas.

[[v2-36-28]]

^<<v2-36-28,28>>^ Fizeram também duas tábuas para os cantos do tabernáculo, na parte posterior,

[[v2-36-29]]

^<<v2-36-29,29>>^ as quais, por baixo, estavam separadas, mas, em cima, se ajustavam à primeira argola; assim se fez com as duas tábuas nos dois cantos.

[[v2-36-30]]

^<<v2-36-30,30>>^ Assim eram as oito tábuas com as suas bases de prata, dezesseis bases: duas bases debaixo de uma tábua e duas debaixo de outra tábua.

[[v2-36-31]]

^<<v2-36-31,31>>^ Fizeram também travessas de madeira de acácia; cinco para as tábuas de um lado do tabernáculo,

[[v2-36-32]]

^<<v2-36-32,32>>^ cinco para as tábuas do outro lado do tabernáculo e cinco para as tábuas do tabernáculo ao lado posterior, que olha para o oeste.

[[v2-36-33]]

^<<v2-36-33,33>>^ A travessa do meio passava ao meio das tábuas, de uma extremidade à outra.

[[v2-36-34]]

^<<v2-36-34,34>>^ Revestiram de ouro as tábuas e de ouro fizeram as suas argolas, pelas quais passavam as travessas, que também foram revestidas de ouro.

[[v2-36-35]]

^<<v2-36-35,35>>^ Fizeram também um véu de pano azul, púrpura, carmesim e linho fino retorcido; fizeram-no com querubins, obra de artista.

[[v2-36-36]]

^<<v2-36-36,36>>^ Penduraram esse véu em quatro colunas de madeira de acácia, revestidas de ouro; os seus colchetes eram de ouro, sobre quatro bases de prata.

[[v2-36-37]]

^<<v2-36-37,37>>^ Fizeram também para a porta da tenda um cortinado de pano azul, púrpura, carmesim e linho fino retorcido, obra de bordador,

[[v2-36-38]]

^<<v2-36-38,38>>^ e as suas cinco colunas, e os seus colchetes. Revestiram de ouro as suas cabeças e as suas molduras, mas as suas cinco bases eram de bronze.

'''

xref:002-exodo/002-exodo-035.adoc#v2-35-0[&#60; Capítulo Anterior] | <<v2-36-0,Topo>> | xref:002-exodo/002-exodo-037.adoc#v2-37-0[Próximo Capítulo &#62;]