include::./index.adoc[]

[[v2-40-0]]
=== Êxodo, 40
// naa ?, NAA - Nova Almeida Atualizada

[[v2-40-1]]

^<<v2-40-1,1>>^ Depois o Senhor  disse a Moisés:

[[v2-40-2]]

^<<v2-40-2,2>>^ — No primeiro dia do primeiro mês, arme o tabernáculo da tenda do encontro.

[[v2-40-3]]

^<<v2-40-3,3>>^ Ponha nele a arca do testemunho e cubra-a com o véu.

[[v2-40-4]]

^<<v2-40-4,4>>^ Ponha nele a mesa e coloque em ordem as coisas que estão sobre ela; ponha nele também o candelabro e monte as suas lâmpadas.

[[v2-40-5]]

^<<v2-40-5,5>>^ Coloque o altar de ouro para o incenso diante da arca do testemunho e pendure o cortinado da porta do tabernáculo.

[[v2-40-6]]

^<<v2-40-6,6>>^ Coloque o altar do holocausto diante da porta do tabernáculo da tenda do encontro.

[[v2-40-7]]

^<<v2-40-7,7>>^ Ponha a bacia entre a tenda do encontro e o altar e encha-a com água.

[[v2-40-8]]

^<<v2-40-8,8>>^ Depois, arme o átrio ao redor e pendure o cortinado à porta do átrio.

[[v2-40-9]]

^<<v2-40-9,9>>^ — Pegue o óleo da unção, e unja o tabernáculo e tudo o que nele está, e consagre-o com todos os seus pertences; e será santo.

[[v2-40-10]]

^<<v2-40-10,10>>^ Unja também o altar do holocausto e todos os seus utensílios e consagre o altar; e o altar se tornará santíssimo.

[[v2-40-11]]

^<<v2-40-11,11>>^ Depois, unja a bacia e o seu suporte e consagre-a.

[[v2-40-12]]

^<<v2-40-12,12>>^ — Faça com que Arão e seus filhos se aproximem da porta da tenda do encontro e mande que se lavem com água.

[[v2-40-13]]

^<<v2-40-13,13>>^ Vista Arão com as vestes sagradas, unja e consagre-o para que me sirva como sacerdote.

[[v2-40-14]]

^<<v2-40-14,14>>^ Faça com que também os filhos de Arão se aproximem, vista-os com as túnicas,

[[v2-40-15]]

^<<v2-40-15,15>>^ e unja-os assim como você ungiu o pai deles, para que me oficiem como sacerdotes; sua unção lhes será por sacerdócio perpétuo de geração em geração.

[[v2-40-16]]

^<<v2-40-16,16>>^ E Moisés fez tudo segundo o Senhor  lhe havia ordenado.

[[v2-40-17]]

^<<v2-40-17,17>>^ No primeiro mês do segundo ano, no primeiro dia do mês, o tabernáculo foi armado.

[[v2-40-18]]

^<<v2-40-18,18>>^ Moisés ergueu o tabernáculo, pôs as suas bases, armou as suas tábuas, colocou nele as suas vigas superiores e levantou as suas colunas;

[[v2-40-19]]

^<<v2-40-19,19>>^ estendeu a tenda sobre o tabernáculo e pôs a cobertura da tenda por cima, segundo o Senhor  havia ordenado a Moisés.

[[v2-40-20]]

^<<v2-40-20,20>>^ Pegou o testemunho e o pôs na arca, passou os cabos na arca e pôs o propiciatório em cima da arca.

[[v2-40-21]]

^<<v2-40-21,21>>^ Introduziu a arca no tabernáculo, pendurou o véu do cortinado e com ele cobriu a arca do testemunho, segundo o Senhor  havia ordenado a Moisés.

[[v2-40-22]]

^<<v2-40-22,22>>^ Pôs também a mesa na tenda do encontro, ao lado do tabernáculo, para o norte, fora do véu,

[[v2-40-23]]

^<<v2-40-23,23>>^ e sobre ela pôs em ordem os pães da proposição diante do Senhor , segundo o Senhor  havia ordenado a Moisés.

[[v2-40-24]]

^<<v2-40-24,24>>^ Pôs também, na tenda do encontro, o candelabro diante da mesa, ao lado do tabernáculo, para o sul,

[[v2-40-25]]

^<<v2-40-25,25>>^ e preparou as lâmpadas diante do Senhor , segundo o Senhor  havia ordenado a Moisés.

[[v2-40-26]]

^<<v2-40-26,26>>^ Pôs o altar de ouro na tenda do encontro, diante do véu,

[[v2-40-27]]

^<<v2-40-27,27>>^ e acendeu sobre ele o incenso aromático, segundo o Senhor  havia ordenado a Moisés.

[[v2-40-28]]

^<<v2-40-28,28>>^ Pendurou também o cortinado da porta do tabernáculo,

[[v2-40-29]]

^<<v2-40-29,29>>^ pôs o altar do holocausto à porta do tabernáculo da tenda do encontro e ofereceu sobre ele holocausto e oferta de cereais, segundo o Senhor  havia ordenado a Moisés.

[[v2-40-30]]

^<<v2-40-30,30>>^ Pôs a bacia entre a tenda do encontro e o altar e a encheu de água, para se lavar.

[[v2-40-31]]

^<<v2-40-31,31>>^ Nela, Moisés, Arão e seus filhos lavavam as mãos e os pés,

[[v2-40-32]]

^<<v2-40-32,32>>^ quando entravam na tenda do encontro e quando se aproximavam do altar, segundo o Senhor  havia ordenado a Moisés.

[[v2-40-33]]

^<<v2-40-33,33>>^ Levantou também o átrio ao redor do tabernáculo e do altar e pendurou o cortinado da porta do átrio. Assim Moisés acabou a obra.

[[v2-40-34]]

^<<v2-40-34,34>>^ Então a nuvem cobriu a tenda do encontro, e a glória do Senhor  encheu o tabernáculo.

[[v2-40-35]]

^<<v2-40-35,35>>^ Moisés não podia entrar na tenda do encontro, porque a nuvem permanecia sobre ela, e a glória do Senhor  enchia o tabernáculo.

[[v2-40-36]]

^<<v2-40-36,36>>^ Quando a nuvem se levantava de sobre o tabernáculo, os filhos de Israel seguiam adiante, em todas as suas jornadas;

[[v2-40-37]]

^<<v2-40-37,37>>^ se a nuvem, porém, não se levantava, não seguiam adiante, até o dia em que ela se levantava.

[[v2-40-38]]

^<<v2-40-38,38>>^ De dia, a nuvem do Senhor  repousava sobre o tabernáculo, e, de noite, havia fogo nela, à vista de toda a casa de Israel, em todas as suas jornadas.

'''

xref:002-exodo/002-exodo-039.adoc#v2-39-0[&#60; Capítulo Anterior] | <<v2-40-0,Topo>> | xref:003-levitico/003-levitico-001.adoc#v3-1-0[Próximo Capítulo &#62;]