include::./index.adoc[]

[[v2-9-0]]
=== Êxodo, 9
// naa ?, NAA - Nova Almeida Atualizada

[[v2-9-1]]

^<<v2-9-1,1>>^ O Senhor  disse a Moisés: — Apresente-se a Faraó e diga-lhe: Assim diz o Senhor , o Deus dos hebreus: "Deixe o meu povo ir, para que me adore.

[[v2-9-2]]

^<<v2-9-2,2>>^ Porque, se você se recusar a deixá-los ir e ainda por força quiser detê-los,

[[v2-9-3]]

^<<v2-9-3,3>>^ eis que a mão do Senhor  trará uma terrível peste sobre o seu rebanho, que está no campo, sobre os cavalos, sobre os jumentos, sobre os camelos, sobre o gado e sobre as ovelhas.

[[v2-9-4]]

^<<v2-9-4,4>>^ E o Senhor  fará distinção entre os rebanhos de Israel e o rebanho do Egito, para que nada morra de tudo o que pertence aos filhos de Israel.

[[v2-9-5]]

^<<v2-9-5,5>>^ O Senhor  designou certo tempo, dizendo: Amanhã o Senhor  fará isto na terra."

[[v2-9-6]]

^<<v2-9-6,6>>^ E o Senhor  o fez no dia seguinte, e todo o rebanho dos egípcios morreu; porém, do rebanho dos israelitas, não morreu um único animal.

[[v2-9-7]]

^<<v2-9-7,7>>^ Faraó mandou verificar, e eis que do rebanho de Israel não havia morrido nem um sequer. Mas o coração de Faraó se endureceu, e ele não deixou o povo ir.

[[v2-9-8]]

^<<v2-9-8,8>>^ Então o Senhor  disse a Moisés e a Arão: — Peguem mãos cheias de cinza de um forno, e que Moisés atire essa cinza para o ar diante de Faraó.

[[v2-9-9]]

^<<v2-9-9,9>>^ Ela se transformará em pó fino sobre toda a terra do Egito e em tumores que se arrebentem em úlceras nas pessoas e nos animais, por toda a terra do Egito.

[[v2-9-10]]

^<<v2-9-10,10>>^ Eles pegaram cinza de um forno e se apresentaram a Faraó. Moisés atirou a cinza para o ar, e ela se transformou em tumores que se arrebentavam em úlceras nas pessoas e nos animais.

[[v2-9-11]]

^<<v2-9-11,11>>^ Os magos não puderam permanecer diante de Moisés, por causa dos tumores, porque havia tumores nos magos e em todos os egípcios.

[[v2-9-12]]

^<<v2-9-12,12>>^ Porém o Senhor  endureceu o coração de Faraó, e este não os ouviu, como o Senhor  tinha dito a Moisés.

[[v2-9-13]]

^<<v2-9-13,13>>^ O Senhor  disse a Moisés: — Levante-se de manhã cedo, apresente-se a Faraó e diga-lhe: Assim diz o Senhor , o Deus dos hebreus: "Deixe o meu povo ir, para que me adore.

[[v2-9-14]]

^<<v2-9-14,14>>^ Pois desta vez enviarei todas as minhas pragas sobre o seu coração, sobre os seus oficiais e sobre o seu povo, para que você saiba que em toda a terra não há ninguém que seja semelhante a mim.

[[v2-9-15]]

^<<v2-9-15,15>>^ Pois eu já poderia ter estendido a mão para ferir você e o seu povo com peste, e você teria sido cortado da terra.

[[v2-9-16]]

^<<v2-9-16,16>>^ Mas, em verdade, foi para isso que eu o mantive: para mostrar a você o meu poder, e para que o meu nome seja anunciado em toda a terra.

[[v2-9-17]]

^<<v2-9-17,17>>^ Você ainda vai se levantar contra o meu povo, para não deixá-lo ir?

[[v2-9-18]]

^<<v2-9-18,18>>^ Eis que amanhã, por este tempo, farei cair uma forte chuva de pedras, como nunca houve no Egito, desde o dia em que foi fundado até hoje.

[[v2-9-19]]

^<<v2-9-19,19>>^ Agora, pois, mande recolher o seu gado e tudo o que você tem no campo. Todas as pessoas e os animais que estiverem no campo e não forem levados para casa morrerão ao cair sobre eles a chuva de pedras."

[[v2-9-20]]

^<<v2-9-20,20>>^ Aqueles oficiais de Faraó que temiam a palavra do Senhor  fizeram com que os seus servos e o seu gado fugissem para as casas;

[[v2-9-21]]

^<<v2-9-21,21>>^ aqueles, porém, que não se importavam com a palavra do Senhor  deixaram que os seus servos e o seu gado ficassem no campo.

[[v2-9-22]]

^<<v2-9-22,22>>^ Então o Senhor  disse a Moisés: — Estenda a mão para o céu, e cairá chuva de pedras em toda a terra do Egito, sobre as pessoas, sobre animais e sobre toda planta do campo na terra do Egito.

[[v2-9-23]]

^<<v2-9-23,23>>^ E Moisés estendeu o seu bordão para o céu e o Senhor  deu trovões e chuva de pedras, e fogo desceu sobre a terra. E o Senhor  fez cair chuva de pedras sobre a terra do Egito.

[[v2-9-24]]

^<<v2-9-24,24>>^ De maneira que havia chuva de pedras e fogo misturado com a chuva de pedras tão grave, como nunca houve em toda a terra do Egito, desde que veio a ser uma nação.

[[v2-9-25]]

^<<v2-9-25,25>>^ Por toda a terra do Egito a chuva de pedras destruiu tudo o que havia no campo, tanto pessoas como animais. A chuva de pedras destruiu também todas as plantas do campo e quebrou todas as árvores do campo.

[[v2-9-26]]

^<<v2-9-26,26>>^ Somente na terra de Gósen, onde estavam os filhos de Israel, não houve chuva de pedras.

[[v2-9-27]]

^<<v2-9-27,27>>^ Então Faraó mandou chamar Moisés e Arão e lhes disse: — Desta vez pequei. O Senhor  é justo, porém eu e o meu povo somos ímpios.

[[v2-9-28]]

^<<v2-9-28,28>>^ Orem ao Senhor , pois já bastam estes grandes trovões e a chuva de pedras. Eu os deixarei ir, e vocês não ficarão mais aqui.

[[v2-9-29]]

^<<v2-9-29,29>>^ Moisés respondeu: — Quando eu sair da cidade, estenderei as mãos ao Senhor . Os trovões cessarão, e já não haverá chuva de pedras, para que você saiba que a terra é do Senhor .

[[v2-9-30]]

^<<v2-9-30,30>>^ Mas quanto a você e aos seus oficiais, eu sei que ainda não temem o Senhor  Deus.

[[v2-9-31]]

^<<v2-9-31,31>>^ O linho e a cevada foram destruídos, pois a cevada já estava na espiga e o linho estava em flor.

[[v2-9-32]]

^<<v2-9-32,32>>^ Porém o trigo e o centeio não sofreram dano, porque ainda não haviam nascido.

[[v2-9-33]]

^<<v2-9-33,33>>^ Moisés saiu da presença de Faraó e da cidade e estendeu as mãos ao Senhor . Cessaram os trovões e a chuva de pedras, e não caiu mais chuva sobre a terra.

[[v2-9-34]]

^<<v2-9-34,34>>^ Quando Faraó viu que cessaram as chuvas, as pedras e os trovões, tornou a pecar e endureceu o coração, ele e os seus oficiais.

[[v2-9-35]]

^<<v2-9-35,35>>^ E assim Faraó, de coração endurecido, não deixou ir os filhos de Israel, como o Senhor  tinha dito a Moisés.

'''

xref:002-exodo/002-exodo-008.adoc#v2-8-0[&#60; Capítulo Anterior] | <<v2-9-0,Topo>> | xref:002-exodo/002-exodo-010.adoc#v2-10-0[Próximo Capítulo &#62;]