include::./index.adoc[]

[[v2-26-0]]
=== Êxodo, 26
// naa ?, NAA - Nova Almeida Atualizada

[[v2-26-1]]

^<<v2-26-1,1>>^ — Faça o tabernáculo, que terá dez cortinas, de linho retorcido, pano azul, púrpura e carmesim; faça as cortinas com querubins, obra de artista.

[[v2-26-2]]

^<<v2-26-2,2>>^ O comprimento de cada cortina será de doze metros e meio, e a largura será de um metro e oitenta; todas as cortinas terão a mesma medida.

[[v2-26-3]]

^<<v2-26-3,3>>^ Cinco cortinas serão ligadas umas às outras; e as outras cinco também ligadas umas às outras.

[[v2-26-4]]

^<<v2-26-4,4>>^ Ponha laçadas de pano azul na borda da cortina na extremidade do primeiro agrupamento; faça o mesmo com a borda da cortina na extremidade do segundo agrupamento.

[[v2-26-5]]

^<<v2-26-5,5>>^ Faça cinquenta laçadas numa cortina, e cinquenta laçadas na outra cortina na extremidade do segundo agrupamento; as laçadas serão contrapostas uma à outra.

[[v2-26-6]]

^<<v2-26-6,6>>^ Faça cinquenta colchetes de ouro, com os quais você prenderá as cortinas uma à outra; e o tabernáculo passará a ser um todo.

[[v2-26-7]]

^<<v2-26-7,7>>^ — Faça também de pelos de cabra cortinas para servirem de tenda sobre o tabernáculo; faça onze cortinas.

[[v2-26-8]]

^<<v2-26-8,8>>^ O comprimento de cada cortina será de treze metros e trinta, e a largura será de um metro e oitenta; as onze cortinas terão a mesma medida.

[[v2-26-9]]

^<<v2-26-9,9>>^ Junte cinco cortinas entre si, e faça o mesmo com as seis restantes; a sexta cortina você dobrará na parte dianteira da tenda.

[[v2-26-10]]

^<<v2-26-10,10>>^ Ponha cinquenta laçadas na borda da cortina que está na extremidade do primeiro agrupamento e cinquenta laçadas na borda da cortina que está na extremidade do segundo agrupamento.

[[v2-26-11]]

^<<v2-26-11,11>>^ Faça também cinquenta colchetes de bronze, e ponha esses colchetes nas laçadas, juntando a tenda, para que venha a ser um todo.

[[v2-26-12]]

^<<v2-26-12,12>>^ A parte que restar das cortinas da tenda, a saber, a meia cortina que sobrar, penderá às costas do tabernáculo.

[[v2-26-13]]

^<<v2-26-13,13>>^ Os quarenta e cinco centímetros de um lado e os quarenta e cinco centímetros de outro lado, do que sobrar no comprimento das cortinas da tenda, penderão de um e de outro lado do tabernáculo para o cobrir.

[[v2-26-14]]

^<<v2-26-14,14>>^ — Faça também de peles de carneiro tingidas de vermelho uma cobertura para a tenda e outra cobertura de peles finas.

[[v2-26-15]]

^<<v2-26-15,15>>^ — Faça também de madeira de acácia as tábuas para o tabernáculo, as quais serão colocadas verticalmente.

[[v2-26-16]]

^<<v2-26-16,16>>^ Cada uma das tábuas terá quatro metros e quarenta e cinco de comprimento e sessenta e sete centímetros de largura.

[[v2-26-17]]

^<<v2-26-17,17>>^ Cada tábua terá dois encaixes, para que se possa unir uma tábua à outra; faça o mesmo com todas as tábuas do tabernáculo.

[[v2-26-18]]

^<<v2-26-18,18>>^ No preparar as tábuas para o tabernáculo, coloque vinte delas para o lado sul.

[[v2-26-19]]

^<<v2-26-19,19>>^ Faça também quarenta bases de prata debaixo das vinte tábuas: duas bases debaixo de uma tábua para os seus dois encaixes e duas bases debaixo de outra tábua para os seus dois encaixes.

[[v2-26-20]]

^<<v2-26-20,20>>^ Também haverá vinte tábuas ao outro lado do tabernáculo, para o lado norte,

[[v2-26-21]]

^<<v2-26-21,21>>^ com as suas quarenta bases de prata: duas bases debaixo de uma tábua e duas bases debaixo de outra tábua.

[[v2-26-22]]

^<<v2-26-22,22>>^ Para o lado posterior do tabernáculo, o lado oeste, faça seis tábuas.

[[v2-26-23]]

^<<v2-26-23,23>>^ Faça também duas tábuas para os cantos do tabernáculo, na parte posterior,

[[v2-26-24]]

^<<v2-26-24,24>>^ as quais, por baixo, estarão separadas, mas, em cima, se ajustarão à primeira argola; assim se fará com as duas tábuas; serão duas para cada um dos dois cantos.

[[v2-26-25]]

^<<v2-26-25,25>>^ Assim serão as oito tábuas com as suas bases de prata, dezesseis bases: duas bases debaixo de uma tábua e duas debaixo de outra tábua.

[[v2-26-26]]

^<<v2-26-26,26>>^ — Faça travessas de madeira de acácia, cinco para as tábuas de um lado do tabernáculo,

[[v2-26-27]]

^<<v2-26-27,27>>^ cinco para as tábuas do outro lado do tabernáculo e cinco para as tábuas do tabernáculo, ao lado posterior, que olha para o oeste.

[[v2-26-28]]

^<<v2-26-28,28>>^ A travessa do meio passará ao meio das tábuas, de uma extremidade à outra.

[[v2-26-29]]

^<<v2-26-29,29>>^ Revista de ouro as tábuas e faça de ouro as suas argolas, pelas quais passarão as travessas, que também deverão ser revestidas de ouro.

[[v2-26-30]]

^<<v2-26-30,30>>^ Faça o tabernáculo segundo o modelo que foi mostrado a você no monte.

[[v2-26-31]]

^<<v2-26-31,31>>^ — Faça também um véu de pano azul, púrpura, carmesim e linho fino retorcido; faça-o com querubins, obra de artista.

[[v2-26-32]]

^<<v2-26-32,32>>^ Pendure esse véu em quatro colunas de madeira de acácia, revestidas de ouro; os seus colchetes serão de ouro, sobre quatro bases de prata.

[[v2-26-33]]

^<<v2-26-33,33>>^ Pendure o véu debaixo dos colchetes e leve para lá a arca do testemunho, para dentro do véu; o véu fará separação entre o Santo Lugar e o Santo dos Santos.

[[v2-26-34]]

^<<v2-26-34,34>>^ — Ponha a cobertura do propiciatório sobre a arca do testemunho no Santo dos Santos.

[[v2-26-35]]

^<<v2-26-35,35>>^ A mesa ficará fora do véu e o candelabro ficará diante da mesa, ao lado do tabernáculo, para o sul; e a mesa ficará para o lado norte.

[[v2-26-36]]

^<<v2-26-36,36>>^ — Faça também para a porta da tenda um cortinado de pano azul, púrpura, carmesim e linho fino retorcido, obra de bordador.

[[v2-26-37]]

^<<v2-26-37,37>>^ Para este cortinado faça cinco colunas de madeira de acácia revestidas de ouro; os seus colchetes serão de ouro, e para as colunas você mandará fundir cinco bases de bronze.

'''

xref:002-exodo/002-exodo-025.adoc#v2-25-0[&#60; Capítulo Anterior] | <<v2-26-0,Topo>> | xref:002-exodo/002-exodo-027.adoc#v2-27-0[Próximo Capítulo &#62;]