include::./index.adoc[]

[[v7-14-0]]
=== Juízes, 14
// naa ?, NAA - Nova Almeida Atualizada

[[v7-14-1]]

^<<v7-14-1,1>>^ Sansão foi a Timna, onde viu uma das filhas dos filisteus.

[[v7-14-2]]

^<<v7-14-2,2>>^ Voltou para casa e disse ao seu pai e à sua mãe: — Vi uma mulher em Timna, das filhas dos filisteus, e agora gostaria que a buscassem para ser a minha esposa.

[[v7-14-3]]

^<<v7-14-3,3>>^ Porém o seu pai e a sua mãe lhe disseram: — Será que não há mulher entre as filhas de seus parentes ou entre todo o nosso povo, para que você tivesse de ir procurar uma esposa no meio dos filisteus, aqueles incircuncisos? Mas Sansão disse ao seu pai: — Busquem essa mulher para mim, porque é só dela que me agrado.

[[v7-14-4]]

^<<v7-14-4,4>>^ Mas o seu pai e a sua mãe não sabiam que isto vinha do Senhor , pois este procurava ocasião contra os filisteus. Porque naquele tempo os filisteus dominavam sobre Israel.

[[v7-14-5]]

^<<v7-14-5,5>>^ Sansão foi com o seu pai e a sua mãe a Timna. Quando chegaram às vinhas de Timna, eis que um leão novo, rugindo, saiu ao encontro dele.

[[v7-14-6]]

^<<v7-14-6,6>>^ Então o Espírito do Senhor  de tal maneira se apossou de Sansão, que ele rasgou o leão como quem rasga um cabrito, sem nada ter nas mãos. Sansão, no entanto, não contou nem a seu pai nem a sua mãe o que havia feito.

[[v7-14-7]]

^<<v7-14-7,7>>^ Então ele foi e falou com aquela mulher, e dela se agradou.

[[v7-14-8]]

^<<v7-14-8,8>>^ Depois de alguns dias, voltou para casar com ela. E, afastando-se do caminho para ver o corpo do leão morto, eis que havia nele um enxame de abelhas com mel.

[[v7-14-9]]

^<<v7-14-9,9>>^ Pegou o favo nas mãos e se foi andando e comendo dele. Quando chegou onde estavam o seu pai e a sua mãe, deu-lhes um pouco do mel, e eles comeram. Mas Sansão não lhes contou que havia tirado o mel do corpo do leão.

[[v7-14-10]]

^<<v7-14-10,10>>^ O pai de Sansão foi à casa daquela mulher, e Sansão deu ali um banquete, como os moços costumavam fazer.

[[v7-14-11]]

^<<v7-14-11,11>>^ Quando os filisteus viram Sansão, convidaram trinta companheiros para estarem com ele.

[[v7-14-12]]

^<<v7-14-12,12>>^ Então Sansão lhes disse: — Vou propor um enigma para que vocês o decifrem. Se, nos sete dias das bodas, vocês puderem decifrá-lo e me explicar o seu significado, darei a vocês trinta túnicas e trinta mudas de roupa.

[[v7-14-13]]

^<<v7-14-13,13>>^ Se não puderem me explicar o significado, vocês me darão as trinta túnicas e as trinta mudas de roupa. E eles disseram: — Apresente-nos o enigma. Queremos ouvi-lo.

[[v7-14-14]]

^<<v7-14-14,14>>^ Sansão disse: "Do que come saiu comida, e do forte saiu doçura." E, em três dias, não puderam decifrar o enigma.

[[v7-14-15]]

^<<v7-14-15,15>>^ No quarto dia, disseram à mulher de Sansão: — Convença o seu marido a nos explicar o enigma. Do contrário, vamos pôr fogo em você e na casa de seu pai. Vocês nos convidaram para poderem se apossar do que é nosso, não foi?

[[v7-14-16]]

^<<v7-14-16,16>>^ Então a mulher de Sansão chorou diante dele e disse: — Você só me odeia! Você não me ama! Pois você deu aos homens do meu povo um enigma a decifrar e ainda não me contou o significado. Mas Sansão respondeu: — Olha! Nem para o meu pai nem para a minha mãe eu contei o significado do enigma. E acha que eu iria contar para você?

[[v7-14-17]]

^<<v7-14-17,17>>^ Ela chorou diante dele os sete dias em que celebravam as bodas. No sétimo dia, Sansão disse a resposta, porque ela não parava de importunar. Então ela declarou o enigma aos homens do seu povo.

[[v7-14-18]]

^<<v7-14-18,18>>^ Assim, no sétimo dia, antes do pôr do sol, os homens daquela cidade disseram a Sansão: Que coisa é mais doce do que o mel e mais forte do que o leão? E Sansão respondeu: "Se vocês não tivessem lavrado com a minha novilha, nunca teriam descoberto o meu enigma."

[[v7-14-19]]

^<<v7-14-19,19>>^ Então o Espírito do Senhor  de tal maneira se apossou de Sansão, que ele desceu até Asquelom, matou trinta homens daquela cidade, pegou as roupas deles e as deu aos que decifraram o enigma. Porém Sansão ficou irado e voltou para a casa do seu pai.

[[v7-14-20]]

^<<v7-14-20,20>>^ Quanto à mulher de Sansão, foi dada em casamento ao homem que tinha sido o seu amigo de honra.

'''

xref:007-juizes/007-juizes-013.adoc#v7-13-0[&#60; Capítulo Anterior] | <<v7-14-0,Topo>> | xref:007-juizes/007-juizes-015.adoc#v7-15-0[Próximo Capítulo &#62;]