include::./index.adoc[]

[[v7-11-0]]
=== Juízes, 11
// naa ?, NAA - Nova Almeida Atualizada

[[v7-11-1]]

^<<v7-11-1,1>>^ Jefté, o gileadita, era homem valente, porém filho de uma prostituta. O pai dele se chamava Gileade.

[[v7-11-2]]

^<<v7-11-2,2>>^ Gileade também teve filhos da sua esposa. Esses filhos cresceram e expulsaram Jefté, dizendo: — Você não herdará nada na casa de nosso pai, porque é filho de outra mulher.

[[v7-11-3]]

^<<v7-11-3,3>>^ Então Jefté fugiu da presença de seus irmãos e foi morar na terra de Tobe. Ali alguns homens sem valor se juntaram a ele e o seguiam.

[[v7-11-4]]

^<<v7-11-4,4>>^ Passado algum tempo, os filhos de Amom entraram em guerra contra Israel.

[[v7-11-5]]

^<<v7-11-5,5>>^ Quando os filhos de Amom atacaram, os anciãos de Gileade foram buscar Jefté na terra de Tobe.

[[v7-11-6]]

^<<v7-11-6,6>>^ E disseram a Jefté: — Venha ser o nosso chefe, para podermos lutar contra os filhos de Amom.

[[v7-11-7]]

^<<v7-11-7,7>>^ Porém Jefté disse aos anciãos de Gileade: — Vocês não são aqueles que me odiaram e me expulsaram da casa de meu pai? Por que vêm a mim agora, quando estão em aperto?

[[v7-11-8]]

^<<v7-11-8,8>>^ Os anciãos de Gileade responderam a Jefté: — É por isso que agora estamos voltando a você. Venha conosco e lute contra os filhos de Amom. Seja o nosso chefe sobre todos os moradores de Gileade.

[[v7-11-9]]

^<<v7-11-9,9>>^ Então Jefté perguntou aos anciãos de Gileade: — Se vocês me fizerem voltar para combater os filhos de Amom, e o Senhor  os entregar nas minhas mãos, então eu serei o chefe de vocês?

[[v7-11-10]]

^<<v7-11-10,10>>^ Os anciãos de Gileade responderam: — O Senhor  é nossa testemunha de que faremos como você diz.

[[v7-11-11]]

^<<v7-11-11,11>>^ Então Jefté foi com os anciãos de Gileade, e o povo o pôs por cabeça e chefe sobre si. E Jefté proferiu todas as suas palavras diante do Senhor , em Mispa.

[[v7-11-12]]

^<<v7-11-12,12>>^ Jefté enviou mensageiros ao rei dos filhos de Amom, dizendo: — O que você tem contra mim, para vir e atacar a minha terra?

[[v7-11-13]]

^<<v7-11-13,13>>^ O rei dos filhos de Amom respondeu aos mensageiros de Jefté: — É porque, quando Israel saiu do Egito, tomou a minha terra desde o Arnom até o Jaboque e até o Jordão. Devolva-me agora essa terra, pacificamente.

[[v7-11-14]]

^<<v7-11-14,14>>^ Porém Jefté tornou a enviar mensageiros ao rei dos filhos de Amom,

[[v7-11-15]]

^<<v7-11-15,15>>^ dizendo: — Assim diz Jefté: "Israel não tomou nem a terra dos moabitas nem a terra dos filhos de Amom.

[[v7-11-16]]

^<<v7-11-16,16>>^ Porque, quando Israel saiu do Egito, andou pelo deserto até o mar Vermelho e chegou a Cades.

[[v7-11-17]]

^<<v7-11-17,17>>^ Então Israel enviou mensageiros ao rei dos edomitas, dizendo: ‘Peço que você me deixe passar pela sua terra.’ Porém o rei dos edomitas não lhe deu ouvidos. Israel mandou pedir a mesma coisa ao rei dos moabitas, mas ele também não quis atender. E, assim, Israel ficou em Cades.

[[v7-11-18]]

^<<v7-11-18,18>>^ Depois, andou pelo deserto, e rodeou a terra dos edomitas e a terra dos moabitas, e chegou a leste da terra destes, e acampou do outro lado do Arnom. Não entrou no território dos moabitas, porque o Arnom é a fronteira deles.

[[v7-11-19]]

^<<v7-11-19,19>>^ Então Israel enviou mensageiros a Seom, rei dos amorreus, rei de Hesbom. Israel lhe disse: ‘Por favor, deixe-nos passar pela sua terra até o nosso destino.’

[[v7-11-20]]

^<<v7-11-20,20>>^ Porém Seom, não confiando em Israel, recusou deixá-lo passar pelo seu território; pelo contrário, reuniu todo o seu povo, acampou em Jaza, e lutou contra Israel.

[[v7-11-21]]

^<<v7-11-21,21>>^ O Senhor , Deus de Israel, entregou Seom e todo o seu povo nas mãos de Israel, que os derrotou. E Israel tomou posse das terras dos amorreus, que moravam naquele lugar.

[[v7-11-22]]

^<<v7-11-22,22>>^ Os israelitas tomaram posse de todo o território dos amorreus, desde o Arnom até o Jaboque e desde o deserto até o Jordão.

[[v7-11-23]]

^<<v7-11-23,23>>^ Assim, o Senhor , Deus de Israel, expulsou os amorreus de diante do seu povo de Israel. E você pretende ser dono desta terra?

[[v7-11-24]]

^<<v7-11-24,24>>^ Não é fato que você considera como sua propriedade aquilo que Quemos, seu deus, lhe dá? Assim nós possuiremos o território de todos os que o Senhor , nosso Deus, expulsou de diante de nós.

[[v7-11-25]]

^<<v7-11-25,25>>^ Você pensa que é melhor do que Balaque, filho de Zipor, rei dos moabitas? Será que alguma vez ele entrou em conflito com Israel ou lutou contra ele?

[[v7-11-26]]

^<<v7-11-26,26>>^ Enquanto Israel morou durante trezentos anos em Hesbom e nas suas vilas, e em Aroer e nas suas vilas, e em todas as cidades que ficam às margens do Arnom, por que vocês, amonitas, não as recuperaram durante esse tempo?

[[v7-11-27]]

^<<v7-11-27,27>>^ Portanto, não sou eu quem pecou contra você! Porém você faz mal em lutar contra mim. O Senhor , que é juiz, julgue hoje entre os filhos de Israel e os filhos de Amom."

[[v7-11-28]]

^<<v7-11-28,28>>^ Porém o rei dos filhos de Amom não deu ouvidos à mensagem que Jefté lhe havia mandado.

[[v7-11-29]]

^<<v7-11-29,29>>^ Então o Espírito do Senhor  veio sobre Jefté. Ele atravessou Gileade e Manassés e, passando por Mispa de Gileade, foi até os filhos de Amom.

[[v7-11-30]]

^<<v7-11-30,30>>^ Jefté fez um voto ao Senhor , dizendo: — Se, de fato, entregares os filhos de Amom nas minhas mãos,

[[v7-11-31]]

^<<v7-11-31,31>>^ quem primeiro sair da porta da minha casa para se encontrar comigo, quando eu voltar vitorioso sobre os filhos de Amom, esse será do Senhor , e eu o oferecerei em holocausto.

[[v7-11-32]]

^<<v7-11-32,32>>^ Assim, Jefté foi de encontro aos filhos de Amom, para lutar contra eles, e o Senhor  os entregou nas mãos de Jefté.

[[v7-11-33]]

^<<v7-11-33,33>>^ Ele os derrotou desde Aroer até as proximidades de Minite — vinte cidades ao todo — e até Abel-Queramim. Foi uma grande derrota para os filhos de Amom, que, assim, foram subjugados pelos filhos de Israel.

[[v7-11-34]]

^<<v7-11-34,34>>^ Quando Jefté voltou para a sua casa, em Mispa, a filha saiu ao seu encontro, tocando o tamborim e dançando. E ela era filha única; ele não tinha outro filho nem filha.

[[v7-11-35]]

^<<v7-11-35,35>>^ Quando Jefté a viu, rasgou as suas roupas e disse: — Ah! Minha filha! Você me prostra por completo! Você passou a ser a causa da minha ruína, porque fiz um voto ao Senhor  e não posso voltar atrás.

[[v7-11-36]]

^<<v7-11-36,36>>^ E ela lhe disse: — Meu pai, você fez um voto ao Senhor . Faça comigo segundo o voto que fez, agora que o Senhor  o vingou dos seus inimigos, os filhos de Amom.

[[v7-11-37]]

^<<v7-11-37,37>>^ E ela disse mais ao seu pai: — Que me seja concedido isto: deixa-me por dois meses, para que eu vá, e desça pelos montes, e chore a minha virgindade, eu e as minhas companheiras.

[[v7-11-38]]

^<<v7-11-38,38>>^ E o pai consentiu, dizendo: — Vá. Deixou-a ir por dois meses. Então ela se foi com as suas companheiras e chorou a sua virgindade pelos montes.

[[v7-11-39]]

^<<v7-11-39,39>>^ Ao fim dos dois meses, ela voltou para seu pai, que lhe fez segundo o voto que tinha feito. Assim, ela nunca teve relações com homem algum. Daqui veio o costume em Israel

[[v7-11-40]]

^<<v7-11-40,40>>^ de as filhas de Israel saírem por quatro dias, todos os anos, a chorar pela filha de Jefté, o gileadita.

'''

xref:007-juizes/007-juizes-010.adoc#v7-10-0[&#60; Capítulo Anterior] | <<v7-11-0,Topo>> | xref:007-juizes/007-juizes-012.adoc#v7-12-0[Próximo Capítulo &#62;]