include::./index.adoc[]

[[v7-2-0]]
=== Juízes, 2
// naa ?, NAA - Nova Almeida Atualizada

[[v7-2-1]]

^<<v7-2-1,1>>^ O Anjo do Senhor  foi de Gilgal a Boquim e disse: — Eu tirei vocês do Egito e os trouxe à terra que, sob juramento, havia prometido aos seus pais. Eu disse: "Nunca invalidarei a minha aliança com vocês.

[[v7-2-2]]

^<<v7-2-2,2>>^ Quanto a vocês, não façam nenhuma aliança com os moradores desta terra; pelo contrário, derrubem os seus altares." No entanto, vocês não obedeceram à minha voz. O que é isso que vocês fizeram?

[[v7-2-3]]

^<<v7-2-3,3>>^ Por isso, também eu disse: "Não expulsarei esses povos da presença de vocês; pelo contrário, eles serão seus adversários, e os deuses deles serão uma armadilha para vocês."

[[v7-2-4]]

^<<v7-2-4,4>>^ Quando o Anjo do Senhor  acabou de falar estas palavras a todos os filhos de Israel, o povo levantou a sua voz e chorou.

[[v7-2-5]]

^<<v7-2-5,5>>^ Por isso aquele lugar foi chamado de Boquim. E ali ofereceram sacrifícios ao Senhor .

[[v7-2-6]]

^<<v7-2-6,6>>^ Depois que Josué despediu o povo, os filhos de Israel se foram, cada um à sua herança, para possuírem a terra.

[[v7-2-7]]

^<<v7-2-7,7>>^ O povo serviu o Senhor  todos os dias de Josué e todos os dias dos anciãos que ainda sobreviveram por muito tempo depois de Josué e que viram todas as grandes obras que o Senhor  tinha feito por Israel.

[[v7-2-8]]

^<<v7-2-8,8>>^ Josué, filho de Num, servo do Senhor , morreu com a idade de cento e dez anos.

[[v7-2-9]]

^<<v7-2-9,9>>^ Foi sepultado em sua própria herança, em Timnate-Heres, na região montanhosa de Efraim, ao norte do monte Gaás.

[[v7-2-10]]

^<<v7-2-10,10>>^ Toda aquela geração também morreu e foi reunida aos seus pais. E, depois dela, se levantou uma nova geração, que não conhecia o Senhor , nem as obras que ele havia feito por Israel.

[[v7-2-11]]

^<<v7-2-11,11>>^ Então os filhos de Israel fizeram o que era mau aos olhos do Senhor , servindo os baalins.

[[v7-2-12]]

^<<v7-2-12,12>>^ Deixaram o Senhor , Deus de seus pais, que os havia tirado da terra do Egito, e seguiram outros deuses, os deuses dos povos que havia ao redor deles, e os adoraram, e provocaram o Senhor  à ira.

[[v7-2-13]]

^<<v7-2-13,13>>^ Porque deixaram o Senhor  e serviram Baal e Astarote.

[[v7-2-14]]

^<<v7-2-14,14>>^ A ira do Senhor  se acendeu contra Israel e ele os entregou nas mãos de ladrões que os despojavam do que possuíam. Ele os entregou nas mãos dos seus inimigos ao redor; e não puderam mais resistir a eles.

[[v7-2-15]]

^<<v7-2-15,15>>^ Por onde quer que fossem, a mão do Senhor  estava contra eles para seu mal, como o Senhor  lhes tinha dito e como lhes havia jurado. E estavam em grande aperto.

[[v7-2-16]]

^<<v7-2-16,16>>^ Então o Senhor  suscitou juízes, que os livraram das mãos dos que os atacavam e roubavam.

[[v7-2-17]]

^<<v7-2-17,17>>^ Mas eles não obedeceram aos seus juízes; pelo contrário, se prostituíram com outros deuses e os adoraram. Depressa se desviaram do caminho por onde andaram seus pais na obediência aos mandamentos do Senhor ; e não fizeram como eles.

[[v7-2-18]]

^<<v7-2-18,18>>^ Quando o Senhor  lhes suscitava juízes, o Senhor  estava com o juiz e os livrava das mãos dos seus inimigos, todos os dias daquele juiz; porque o Senhor  se compadecia deles ante os seus gemidos, por causa dos que os afligiam e oprimiam.

[[v7-2-19]]

^<<v7-2-19,19>>^ Mas, quando o juiz morria, eles voltavam a viver como antes e se tornavam piores do que os seus pais, seguindo outros deuses, servindo-os e adorando-os. Não abandonavam nenhuma das suas práticas, nem a sua obstinação.

[[v7-2-20]]

^<<v7-2-20,20>>^ Por isso a ira do Senhor  se acendeu contra Israel, e ele disse: — Porque este povo transgrediu a minha aliança que eu havia ordenado a seus pais e não deu ouvidos à minha voz,

[[v7-2-21]]

^<<v7-2-21,21>>^ também eu não expulsarei mais de diante deles nenhuma das nações que Josué deixou quando morreu.

[[v7-2-22]]

^<<v7-2-22,22>>^ Por meio delas vou pôr Israel à prova, para ver se o povo guardará ou não o caminho do Senhor , como seus pais o guardaram.

[[v7-2-23]]

^<<v7-2-23,23>>^ Assim, o Senhor  deixou que aquelas nações ficassem e não as expulsou logo, nem as entregou nas mãos de Josué.

'''

xref:007-juizes/007-juizes-001.adoc#v7-1-0[&#60; Capítulo Anterior] | <<v7-2-0,Topo>> | xref:007-juizes/007-juizes-003.adoc#v7-3-0[Próximo Capítulo &#62;]