include::./index.adoc[]

[[v7-20-0]]
=== Juízes, 20
// naa ?, NAA - Nova Almeida Atualizada

[[v7-20-1]]

^<<v7-20-1,1>>^ Todos os filhos de Israel, desde Dã até Berseba, bem como da terra de Gileade, saíram, e a congregação se reuniu diante do Senhor  em Mispa, como se fosse um só homem.

[[v7-20-2]]

^<<v7-20-2,2>>^ Os chefes de todo o povo e todas as tribos de Israel se apresentaram na congregação do povo de Deus. Havia quatrocentos mil soldados de infantaria, que puxavam da espada.

[[v7-20-3]]

^<<v7-20-3,3>>^ E os filhos de Benjamim ouviram que os filhos de Israel haviam se reunido em Mispa. Os filhos de Israel disseram: — Contem-nos como aconteceu essa maldade.

[[v7-20-4]]

^<<v7-20-4,4>>^ Então o levita, marido da mulher assassinada, disse: — Cheguei com a minha concubina a Gibeá, cidade de Benjamim, para passar a noite.

[[v7-20-5]]

^<<v7-20-5,5>>^ Os cidadãos de Gibeá se levantaram contra mim e, à noite, cercaram a casa em que eu estava. Queriam me matar e abusaram da minha concubina, que morreu.

[[v7-20-6]]

^<<v7-20-6,6>>^ Então peguei o corpo da minha concubina, cortei em pedaços, e os mandei por toda a terra da herança de Israel, pois aqueles homens cometeram uma maldade e loucura em Israel.

[[v7-20-7]]

^<<v7-20-7,7>>^ Eis que todos vocês são filhos de Israel; portanto, discutam o assunto e tomem uma decisão.

[[v7-20-8]]

^<<v7-20-8,8>>^ Então todo o povo se levantou como um só homem, dizendo: — Nenhum de nós irá para a sua tenda, e nenhum de nós voltará para casa.

[[v7-20-9]]

^<<v7-20-9,9>>^ Mas isto é o que faremos a Gibeá: um sorteio para ver quem atacará a cidade.

[[v7-20-10]]

^<<v7-20-10,10>>^ De todas as tribos de Israel vamos separar dez homens de cem, e cem de mil, e mil de dez mil, para providenciarem mantimento para o povo, a fim de que este, indo a Gibeá de Benjamim, faça a ela conforme toda a loucura que fez em Israel.

[[v7-20-11]]

^<<v7-20-11,11>>^ Assim, todos os homens de Israel se ajuntaram como se fossem um só homem contra essa cidade.

[[v7-20-12]]

^<<v7-20-12,12>>^ As tribos de Israel enviaram homens por toda a tribo de Benjamim, dizendo: — Que maldade é essa que foi feita no meio de vocês?

[[v7-20-13]]

^<<v7-20-13,13>>^ E agora entreguem-nos aqueles homens, homens malignos, que estão em Gibeá, para que os matemos e tiremos esse mal do meio de Israel. Mas os filhos de Benjamim não quiseram ouvir a voz de seus irmãos, os filhos de Israel.

[[v7-20-14]]

^<<v7-20-14,14>>^ Ao contrário, vindos de suas cidades, se ajuntaram em Gibeá, para saírem à guerra contra os filhos de Israel.

[[v7-20-15]]

^<<v7-20-15,15>>^ E naquele dia os filhos de Benjamim convocaram das suas cidades vinte e seis mil homens que puxavam da espada, além dos moradores de Gibeá, dos quais reuniram setecentos homens escolhidos.

[[v7-20-16]]

^<<v7-20-16,16>>^ Entre todo este povo havia setecentos homens escolhidos, canhotos, que atiravam com a funda e eram capazes de acertar uma pedra num fio de cabelo, sem nunca errar.

[[v7-20-17]]

^<<v7-20-17,17>>^ Dos homens de Israel, além dos de Benjamim, foram convocados quatrocentos mil homens que puxavam da espada. Todos esses eram homens de guerra.

[[v7-20-18]]

^<<v7-20-18,18>>^ Os israelitas se levantaram e foram a Betel. Ali, consultaram a Deus, dizendo: — Quem de nós será o primeiro a lutar contra Benjamim? E o Senhor  respondeu: — Judá irá primeiro.

[[v7-20-19]]

^<<v7-20-19,19>>^ Na manhã seguinte os filhos de Israel se levantaram e acamparam perto de Gibeá.

[[v7-20-20]]

^<<v7-20-20,20>>^ E os homens de Israel saíram à batalha contra a tribo de Benjamim e tomaram posição de ataque contra ela junto a Gibeá.

[[v7-20-21]]

^<<v7-20-21,21>>^ Então os filhos de Benjamim saíram de Gibeá e, naquele dia, mataram vinte e dois mil homens de Israel.

[[v7-20-22]]

^<<v7-20-22,22>>^ Porém o povo dos homens de Israel se animou e eles novamente tomaram posição de ataque no mesmo lugar onde, no primeiro dia, o tinham feito.

[[v7-20-23]]

^<<v7-20-23,23>>^ Antes disso, porém, os filhos de Israel foram e choraram diante do Senhor  até a tarde. E consultaram o Senhor , dizendo: — Devemos atacar outra vez os nossos irmãos da tribo de Benjamim? E o Senhor  respondeu: — Sim, vocês devem atacar.

[[v7-20-24]]

^<<v7-20-24,24>>^ Assim, no dia seguinte, os filhos de Israel marcharam contra os filhos de Benjamim.

[[v7-20-25]]

^<<v7-20-25,25>>^ Também os de Benjamim, no dia seguinte, saíram de Gibeá de encontro a eles. E mataram mais dezoito mil homens, todos dos que puxavam da espada.

[[v7-20-26]]

^<<v7-20-26,26>>^ Então todos os filhos de Israel, todo o povo, foram a Betel, choraram, estiveram ali diante do Senhor  e jejuaram aquele dia até a tarde. E ofereceram holocaustos e ofertas pacíficas diante do Senhor .

[[v7-20-27]]

^<<v7-20-27,27>>^ E os filhos de Israel consultaram o Senhor . Porque naqueles dias a arca da aliança de Deus estava ali em Betel.

[[v7-20-28]]

^<<v7-20-28,28>>^ E Fineias, filho de Eleazar, filho de Arão, ministrava diante dela naqueles dias. Os filhos de Israel perguntaram: — Devemos sair mais uma vez para lutar contra os nossos irmãos da tribo de Benjamim ou devemos desistir? O Senhor  respondeu: — Vão novamente, porque amanhã eu os entregarei nas mãos de vocês.

[[v7-20-29]]

^<<v7-20-29,29>>^ Então Israel pôs emboscadas ao redor de Gibeá.

[[v7-20-30]]

^<<v7-20-30,30>>^ No terceiro dia, os filhos de Israel avançaram contra os filhos de Benjamim e tomaram posição de ataque contra Gibeá, como das outras vezes.

[[v7-20-31]]

^<<v7-20-31,31>>^ Então os filhos de Benjamim saíram de encontro ao povo, e, deixando-se atrair para longe da cidade, começaram a matar alguns do povo de Israel, como haviam feito das outras vezes. Pelas estradas, das quais uma vai para Betel e a outra vai para Gibeá, e no campo, mataram uns trinta homens de Israel.

[[v7-20-32]]

^<<v7-20-32,32>>^ Então os filhos de Benjamim disseram: — Eles estão sendo derrotados, como das outras vezes. Porém os filhos de Israel disseram: — Vamos fugir e atraí-los da cidade para as estradas.

[[v7-20-33]]

^<<v7-20-33,33>>^ Todos os homens de Israel se levantaram do seu lugar e tomaram posição de ataque em Baal-Tamar, e a emboscada de Israel saiu do seu lugar, das vizinhanças de Geba.

[[v7-20-34]]

^<<v7-20-34,34>>^ Dez mil homens escolhidos de todo o Israel vieram contra Gibeá, e a batalha se intensificou. Porém os filhos de Benjamim não imaginavam que o desastre era iminente.

[[v7-20-35]]

^<<v7-20-35,35>>^ Então o Senhor  derrotou Benjamim diante de Israel. E, naquele dia, os filhos de Israel mataram vinte e cinco mil e cem homens de Benjamim, todos dos que puxavam da espada.

[[v7-20-36]]

^<<v7-20-36,36>>^ Então os filhos de Benjamim viram que estavam derrotados. Os homens de Israel foram cedendo terreno aos benjamitas, porque confiavam na emboscada que haviam posto contra Gibeá.

[[v7-20-37]]

^<<v7-20-37,37>>^ A emboscada avançou depressa, investiu contra Gibeá e passou os moradores a fio de espada.

[[v7-20-38]]

^<<v7-20-38,38>>^ Os homens de Israel tinham combinado um sinal com a emboscada, que era fazer subir da cidade uma grande nuvem de fumaça.

[[v7-20-39]]

^<<v7-20-39,39>>^ Então os homens de Israel deviam voltar à batalha. Os filhos de Benjamim tinham começado a atacar os homens de Israel e já tinham matado uns trinta deles. E diziam: — Com certeza eles já estão derrotados, como na batalha anterior.

[[v7-20-40]]

^<<v7-20-40,40>>^ Então a nuvem de fumaça começou a levantar-se da cidade, como se fosse uma coluna. Os filhos de Benjamim olharam para trás, e eis que a fumaça da cidade subia para o céu.

[[v7-20-41]]

^<<v7-20-41,41>>^ Os homens de Israel deram meia-volta, e os filhos de Benjamim ficaram apavorados, porque viram que o desastre era iminente.

[[v7-20-42]]

^<<v7-20-42,42>>^ Eles viraram as costas para os homens de Israel, em busca do caminho do deserto, mas não puderam escapar da batalha; e os que vinham das cidades os destruíram no meio deles.

[[v7-20-43]]

^<<v7-20-43,43>>^ Cercaram os filhos de Benjamim e os perseguiram; e, onde repousavam, ali os alcançavam, até diante de Gibeá, para o nascente do sol.

[[v7-20-44]]

^<<v7-20-44,44>>^ Dos filhos de Benjamim foram mortos dezoito mil homens, todos estes homens valentes.

[[v7-20-45]]

^<<v7-20-45,45>>^ Então se viraram e fugiram na direção do deserto, para a rocha de Rimom. E, ao longo do caminho, os filhos de Israel ainda apanharam mais uns cinco mil homens. Seguiram-nos de perto até Gidom, e mataram mais dois mil homens.

[[v7-20-46]]

^<<v7-20-46,46>>^ Naquele dia, morreram vinte e cinco mil homens dos filhos de Benjamim, todos eles homens valentes que puxavam da espada.

[[v7-20-47]]

^<<v7-20-47,47>>^ Porém seiscentos homens viraram e fugiram para o deserto, para a rocha de Rimom, onde ficaram quatro meses.

[[v7-20-48]]

^<<v7-20-48,48>>^ Os homens de Israel voltaram para os filhos de Benjamim e passaram a fio de espada tudo o que restou da cidade, tanto homens como animais, tudo o que encontraram. E também puseram fogo em todas as cidades que encontraram.

'''

xref:007-juizes/007-juizes-019.adoc#v7-19-0[&#60; Capítulo Anterior] | <<v7-20-0,Topo>> | xref:007-juizes/007-juizes-021.adoc#v7-21-0[Próximo Capítulo &#62;]