include::./index.adoc[]

[[v7-7-0]]
=== Juízes, 7
// naa ?, NAA - Nova Almeida Atualizada

[[v7-7-1]]

^<<v7-7-1,1>>^ Então Jerubaal, isto é, Gideão, se levantou de madrugada, e todo o povo que com ele estava, e acamparam junto à fonte de Harode, de maneira que o arraial dos midianitas ficava ao norte deles, no vale, perto do monte de Moré.

[[v7-7-2]]

^<<v7-7-2,2>>^ O Senhor  disse a Gideão: — É demais o povo que está com você, para eu entregar os midianitas nas suas mãos. Israel poderia se gloriar contra mim, dizendo: "A minha própria mão me livrou."

[[v7-7-3]]

^<<v7-7-3,3>>^ Portanto, anuncie ao povo o seguinte: "Quem estiver assustado e com medo, saia da região montanhosa de Gileade e volte para casa." Então vinte e dois mil homens voltaram, e dez mil ficaram.

[[v7-7-4]]

^<<v7-7-4,4>>^ Então o Senhor  disse a Gideão: — Ainda há povo demais. Faça-os descer até as águas, e ali eu os provarei para você. Aquele de quem eu disser: "Este irá com você", esse de fato irá com você; porém todo aquele de quem eu disser: "Este não irá com você", esse não irá.

[[v7-7-5]]

^<<v7-7-5,5>>^ Gideão fez com que os homens descessem até as águas. Então o Senhor  lhe disse: — Todos os que lamberem a água com a língua, como faz o cachorro, esses você deve pôr à parte, separando-os daqueles que se ajoelharem para beber.

[[v7-7-6]]

^<<v7-7-6,6>>^ O número dos que lamberam, levando a mão à boca, foi de trezentos homens. Todos os outros se ajoelharam para beber a água.

[[v7-7-7]]

^<<v7-7-7,7>>^ Então o Senhor  disse a Gideão: — Com estes trezentos homens que lamberam a água eu livrarei vocês, e entregarei os midianitas nas suas mãos. Diga a todos os outros que voltem para casa.

[[v7-7-8]]

^<<v7-7-8,8>>^ Os trezentos homens pegaram as provisões e as trombetas dos outros. Gideão mandou todos os homens de Israel cada um à sua tenda, porém reteve consigo os trezentos homens. O arraial dos midianitas estava abaixo dele, no vale.

[[v7-7-9]]

^<<v7-7-9,9>>^ Naquela mesma noite, o Senhor  lhe disse: — Levante-se e ataque o arraial, porque o entreguei nas suas mãos.

[[v7-7-10]]

^<<v7-7-10,10>>^ Se você ainda estiver com medo de atacar, desça ao arraial com o seu ajudante Pura

[[v7-7-11]]

^<<v7-7-11,11>>^ e ouça o que eles dizem. Então você ganhará coragem e atacará o arraial. Gideão desceu até a vanguarda do arraial com o seu ajudante Pura.

[[v7-7-12]]

^<<v7-7-12,12>>^ Os midianitas, os amalequitas e todos os povos do Oriente cobriam o vale como uma nuvem de gafanhotos. Os camelos deles eram uma multidão inumerável como a areia que está na praia do mar.

[[v7-7-13]]

^<<v7-7-13,13>>^ Quando Gideão se aproximou, eis que certo homem estava contando um sonho ao seu amigo. Ele dizia: — Tive um sonho. Eis que um pão de cevada vinha rolando dentro do arraial dos midianitas. Bateu contra a tenda, de maneira que esta caiu, se virou de cima para baixo e ficou estendida no chão.

[[v7-7-14]]

^<<v7-7-14,14>>^ O amigo respondeu: — Isso não é outra coisa a não ser a espada de Gideão, filho de Joás, homem israelita. Deus entregou nas mãos dele os midianitas e todo este arraial.

[[v7-7-15]]

^<<v7-7-15,15>>^ Quando Gideão ouviu o relato desse sonho e o seu significado, adorou a Deus. Voltou para o arraial de Israel e disse: — Levantem-se, porque o Senhor  entregou o arraial dos midianitas nas mãos de vocês.

[[v7-7-16]]

^<<v7-7-16,16>>^ Então repartiu os trezentos homens em três companhias e entregou a cada homem uma trombeta e um cântaro vazio, com uma tocha dentro dele.

[[v7-7-17]]

^<<v7-7-17,17>>^ E disse-lhes: — Olhem para mim e façam como eu fizer. Quando eu chegar às imediações do arraial, assim como eu fizer, façam vocês também.

[[v7-7-18]]

^<<v7-7-18,18>>^ Quando eu tocar a trombeta, e todos os que comigo estiverem, então vocês também tocarão a sua trombeta ao redor de todo o arraial e dirão: "Pelo Senhor  e por Gideão!"

[[v7-7-19]]

^<<v7-7-19,19>>^ Gideão e os cem homens que estavam com ele chegaram às imediações do arraial por volta da meia-noite, pouco tempo após a troca das guardas. Tocaram as trombetas e quebraram os cântaros que tinham nas mãos.

[[v7-7-20]]

^<<v7-7-20,20>>^ Assim, as três companhias tocaram as trombetas e despedaçaram os cântaros. Seguravam a tocha na mão esquerda e a trombeta na mão direita. E gritavam: "Uma espada pelo Senhor  e por Gideão!"

[[v7-7-21]]

^<<v7-7-21,21>>^ E cada um permaneceu no seu lugar ao redor do arraial. Todo o exército dos midianitas começou a correr, a gritar e a fugir.

[[v7-7-22]]

^<<v7-7-22,22>>^ Ao soar das trezentas trombetas, o Senhor  tornou a espada de um contra o outro, e isto em todo o arraial, que fugiu na direção de Zererá, até Bete-Sita, até a divisa de Abel-Meolá, perto de Tabate.

[[v7-7-23]]

^<<v7-7-23,23>>^ Então os homens de Israel, de Naftali, de Aser e de todo o Manassés foram convocados e perseguiram os midianitas.

[[v7-7-24]]

^<<v7-7-24,24>>^ Gideão enviou mensageiros a todas as montanhas de Efraim, dizendo: — Desçam para atacar os midianitas e impedir que eles passem pelas águas do Jordão até Bete-Bara. Assim, todos os homens de Efraim foram convocados. E eles cortaram a passagem dos midianitas pelas águas do Jordão, até Bete-Bara.

[[v7-7-25]]

^<<v7-7-25,25>>^ E prenderam dois príncipes dos midianitas, Orebe e Zeebe. Mataram Orebe no rochedo de Orebe e mataram Zeebe no lagar de Zeebe. Perseguiram os midianitas e trouxeram a cabeça de Orebe e a cabeça de Zeebe a Gideão, do outro lado do Jordão.

'''

xref:007-juizes/007-juizes-006.adoc#v7-6-0[&#60; Capítulo Anterior] | <<v7-7-0,Topo>> | xref:007-juizes/007-juizes-008.adoc#v7-8-0[Próximo Capítulo &#62;]