include::./index.adoc[]

[[v7-13-0]]
=== Juízes, 13
// naa ?, NAA - Nova Almeida Atualizada

[[v7-13-1]]

^<<v7-13-1,1>>^ Os filhos de Israel tornaram a fazer o que era mau aos olhos do Senhor , e por isso ele os entregou nas mãos dos filisteus durante quarenta anos.

[[v7-13-2]]

^<<v7-13-2,2>>^ Havia um homem de Zorá, da linhagem de Dã, chamado Manoá, cuja mulher era estéril e não tinha filhos.

[[v7-13-3]]

^<<v7-13-3,3>>^ O Anjo do Senhor  apareceu a essa mulher e lhe disse: — Eis que você é estéril e nunca teve filhos, mas você ficará grávida e dará à luz um filho.

[[v7-13-4]]

^<<v7-13-4,4>>^ Por isso, tenha cuidado e não beba vinho nem bebida forte, e não coma nenhuma comida impura.

[[v7-13-5]]

^<<v7-13-5,5>>^ Porque eis que você ficará grávida e dará à luz um filho sobre cuja cabeça não passará navalha. O menino será nazireu consagrado a Deus desde o ventre de sua mãe, e ele começará a livrar Israel do poder dos filisteus.

[[v7-13-6]]

^<<v7-13-6,6>>^ Então a mulher foi a seu marido e lhe disse: — Um homem de Deus veio falar comigo. A sua aparência era semelhante à de um anjo de Deus, tremenda. Não perguntei de onde ele vinha, e ele não me disse como se chamava.

[[v7-13-7]]

^<<v7-13-7,7>>^ Porém ele me disse: "Eis que você ficará grávida e dará à luz um filho. Por isso, não beba vinho, nem bebida forte, nem coma coisa impura, porque o menino será nazireu consagrado a Deus desde o ventre materno até o dia de sua morte."

[[v7-13-8]]

^<<v7-13-8,8>>^ Então Manoá orou ao Senhor , dizendo: — Ah! Meu Senhor, peço que o homem de Deus que enviaste venha outra vez e nos ensine o que devemos fazer com o menino que há de nascer.

[[v7-13-9]]

^<<v7-13-9,9>>^ Deus ouviu a voz de Manoá, e o Anjo de Deus veio outra vez à mulher, quando ela estava sentada no campo. Porém Manoá, o marido, não estava com ela.

[[v7-13-10]]

^<<v7-13-10,10>>^ A mulher se apressou, correu e deu a notícia a seu marido. Ela lhe disse: — Eis que me apareceu aquele homem que falou comigo no outro dia.

[[v7-13-11]]

^<<v7-13-11,11>>^ Então Manoá se levantou e seguiu a sua mulher. Quando encontrou o homem, perguntou: — Você é o homem que falou com esta mulher? Ele respondeu: — Sim, sou eu.

[[v7-13-12]]

^<<v7-13-12,12>>^ Então Manoá disse: — Quando se cumprirem as palavras que você falou, qual será o modo de viver do menino e o seu serviço?

[[v7-13-13]]

^<<v7-13-13,13>>^ O Anjo do Senhor  disse a Manoá: — A sua mulher deve se guardar de tudo o que eu disse a ela.

[[v7-13-14]]

^<<v7-13-14,14>>^ Não deve comer nada que procede da videira. Não deve beber vinho nem bebida forte, nem comer nada que seja impuro. Ela deve observar tudo o que lhe ordenei.

[[v7-13-15]]

^<<v7-13-15,15>>^ Então Manoá disse ao Anjo do Senhor : — Permita-nos convidá-lo a ficar conosco. Queremos preparar um cabrito para você.

[[v7-13-16]]

^<<v7-13-16,16>>^ Porém o Anjo do Senhor  disse a Manoá: — Ainda que você me convide, não comerei a sua comida. Mas, se você preparar um holocausto, ofereça-o ao Senhor . Acontece que Manoá não sabia que aquele era o Anjo do Senhor .

[[v7-13-17]]

^<<v7-13-17,17>>^ Então Manoá perguntou ao Anjo do Senhor : — Qual é o seu nome, para que possamos honrar você, quando se cumprir aquilo que nos falou?

[[v7-13-18]]

^<<v7-13-18,18>>^ O Anjo do Senhor  respondeu: — Por que você me pergunta pelo meu nome, que é maravilhoso?

[[v7-13-19]]

^<<v7-13-19,19>>^ Então Manoá pegou um cabrito e uma oferta de cereais e os ofereceu sobre uma rocha ao Senhor  Deus. E o Anjo do Senhor  fez algo maravilhoso, enquanto Manoá e a sua mulher estavam observando.

[[v7-13-20]]

^<<v7-13-20,20>>^ Aconteceu que, enquanto a chama que saiu do altar subia para o céu, o Anjo do Senhor  subiu nela. Ao verem isso, Manoá e a sua mulher se prostraram com o rosto em terra.

[[v7-13-21]]

^<<v7-13-21,21>>^ Nunca mais o Anjo do Senhor  apareceu a Manoá, nem à sua mulher. Então Manoá ficou sabendo que aquele era o Anjo do Senhor .

[[v7-13-22]]

^<<v7-13-22,22>>^ Manoá disse à sua mulher: — Certamente vamos morrer, porque vimos Deus.

[[v7-13-23]]

^<<v7-13-23,23>>^ Mas a mulher respondeu: — Se o Senhor  Deus quisesse nos matar, não teria aceito de nossas mãos o holocausto e a oferta de cereais, nem nos teria mostrado tudo isso, nem nos teria revelado essas coisas.

[[v7-13-24]]

^<<v7-13-24,24>>^ Depois, a mulher deu à luz um filho e lhe deu o nome de Sansão. O menino cresceu, e o Senhor  o abençoou.

[[v7-13-25]]

^<<v7-13-25,25>>^ E o Espírito do Senhor  começou a agir nele em Maané-Dã, entre Zorá e Estaol.

'''

xref:007-juizes/007-juizes-012.adoc#v7-12-0[&#60; Capítulo Anterior] | <<v7-13-0,Topo>> | xref:007-juizes/007-juizes-014.adoc#v7-14-0[Próximo Capítulo &#62;]