include::./index.adoc[]

[[v7-16-0]]
=== Juízes, 16
// naa ?, NAA - Nova Almeida Atualizada

[[v7-16-1]]

^<<v7-16-1,1>>^ Sansão foi a Gaza, viu ali uma prostituta e teve relações com ela.

[[v7-16-2]]

^<<v7-16-2,2>>^ Foi dito aos gazitas: — Sansão chegou aqui. Eles cercaram o local e ficaram a noite toda esperando por ele, às escondidas, no portão da cidade. Ficaram em silêncio durante toda a noite, pois diziam: — Vamos esperar até o raiar do dia. Então nós o matamos.

[[v7-16-3]]

^<<v7-16-3,3>>^ Porém Sansão ficou deitado somente até a meia-noite. Então se levantou, pegou ambas as folhas do portão da cidade e as arrancou juntamente com os seus batentes e a tranca. Pôs tudo sobre os ombros e levou ao alto do monte que está em frente de Hebrom.

[[v7-16-4]]

^<<v7-16-4,4>>^ Depois disto, Sansão se apaixonou por uma mulher do vale de Soreque, a qual se chamava Dalila.

[[v7-16-5]]

^<<v7-16-5,5>>^ Então os governantes dos filisteus foram falar com ela e lhe disseram: — Convença-o a revelar em que consiste a sua grande força e como poderíamos dominá-lo e amarrá-lo, para que assim possamos subjugá-lo. Cada um de nós dará a você mil e cem moedas de prata.

[[v7-16-6]]

^<<v7-16-6,6>>^ Então Dalila disse a Sansão: — Peço que você me conte em que consiste a sua grande força e com que você poderia ser amarrado e subjugado.

[[v7-16-7]]

^<<v7-16-7,7>>^ Sansão respondeu: — Se me amarrarem com sete cordas de arco ainda úmidas, ficarei fraco e serei como qualquer outro homem.

[[v7-16-8]]

^<<v7-16-8,8>>^ Os governantes dos filisteus trouxeram a Dalila sete cordas de arco, ainda úmidas; e com as cordas ela o amarrou.

[[v7-16-9]]

^<<v7-16-9,9>>^ Dalila havia deixado alguns homens escondidos no seu quarto. Então ela disse: — Sansão, os filisteus vêm vindo aí! Mas ele arrebentou as cordas de arco como se arrebenta o fio da estopa chamuscada que é colocada perto do fogo. Assim, não se soube em que consistia a força que ele tinha.

[[v7-16-10]]

^<<v7-16-10,10>>^ Então Dalila disse a Sansão: — Eis que você tem zombado de mim e me falou mentiras. Agora, por favor, conte-me como você pode ser amarrado.

[[v7-16-11]]

^<<v7-16-11,11>>^ Ele lhe disse: — Se me amarrarem bem com cordas novas, que nunca foram usadas, ficarei fraco e serei como qualquer outro homem.

[[v7-16-12]]

^<<v7-16-12,12>>^ Dalila pegou cordas novas e o amarrou. Depois disse: — Sansão, os filisteus vêm vindo aí! Dalila havia deixado alguns homens escondidos no seu quarto. Mas Sansão arrebentou as cordas de seus braços como se fossem um fio de linha.

[[v7-16-13]]

^<<v7-16-13,13>>^ Dalila disse a Sansão: — Até agora você tem zombado de mim e só me falou mentiras. Diga-me como você poderia ser amarrado. Ele respondeu: — Se você tecer num tear as sete tranças da minha cabeça e se as prender com um pino de tear, ficarei fraco e serei como qualquer outro homem. Enquanto ele dormia, ela pegou e teceu as sete tranças dele num tear.

[[v7-16-14]]

^<<v7-16-14,14>>^ Prendeu-as com um pino de tear e depois gritou: — Sansão, os filisteus vêm vindo aí! Mas ele despertou do sono, arrancou o pino e tirou o cabelo do tear.

[[v7-16-15]]

^<<v7-16-15,15>>^ Então ela lhe disse: — Como você pode dizer que me ama, se não me revela o seu segredo? Por três vezes você zombou de mim e ainda não me contou em que consiste a sua grande força.

[[v7-16-16]]

^<<v7-16-16,16>>^ Ela o importunava e pressionava todos os dias com a mesma pergunta, de modo que a alma dele se angustiou até a morte.

[[v7-16-17]]

^<<v7-16-17,17>>^ Então ele contou o seu segredo, dizendo: — Nunca foi passada uma navalha na minha cabeça, porque sou nazireu consagrado a Deus desde o ventre de minha mãe. Se o meu cabelo for cortado, a minha força irá embora, ficarei fraco e serei como qualquer outro homem.

[[v7-16-18]]

^<<v7-16-18,18>>^ Quando Dalila viu que ele lhe havia contado o seu segredo, mandou chamar os governantes dos filisteus, dizendo: — Venham mais esta vez, porque agora ele me contou o seu segredo. Então os governantes dos filisteus vieram até ela e trouxeram com eles o dinheiro.

[[v7-16-19]]

^<<v7-16-19,19>>^ Dalila fez com que Sansão dormisse no colo dela e, tendo chamado um homem, mandou rapar-lhe as sete tranças da cabeça, e assim começou a subjugá-lo. Sansão havia perdido a sua força.

[[v7-16-20]]

^<<v7-16-20,20>>^ Então ela gritou: — Sansão, os filisteus vêm vindo aí! Ele despertou do sono e disse consigo mesmo: — Vou sair como nas outras vezes e me livrarei. Mas ele não sabia ainda que o Senhor  já se havia retirado dele.

[[v7-16-21]]

^<<v7-16-21,21>>^ Então os filisteus o agarraram, furaram os olhos dele e o levaram para Gaza. Amarraram-no com correntes de bronze e o puseram a virar um moinho na prisão.

[[v7-16-22]]

^<<v7-16-22,22>>^ Mas o cabelo da sua cabeça, logo após ser rapado, começou a crescer de novo.

[[v7-16-23]]

^<<v7-16-23,23>>^ Os governantes dos filisteus se reuniram para oferecer um grande sacrifício ao seu deus Dagom e para se alegrar. Diziam: — O nosso deus entregou o nosso inimigo Sansão nas nossas mãos.

[[v7-16-24]]

^<<v7-16-24,24>>^ O povo, quando viu Sansão, louvava o seu deus, dizendo: — O nosso deus entregou nas nossas mãos o nosso inimigo, aquele que destruía a nossa terra e multiplicava os nossos mortos.

[[v7-16-25]]

^<<v7-16-25,25>>^ Com alegria no coração, disseram: — Mandem vir Sansão, para que ele nos divirta. Trouxeram Sansão do cárcere, e ele os divertia. Quando o fizeram ficar em pé entre as colunas,

[[v7-16-26]]

^<<v7-16-26,26>>^ Sansão disse ao moço que o guiava pela mão: — Deixe-me apalpar as colunas que sustentam o templo, para que eu possa me encostar nelas.

[[v7-16-27]]

^<<v7-16-27,27>>^ Ora, o templo estava cheio de homens e mulheres, e também ali estavam todos os governantes dos filisteus. E sobre o teto havia uns três mil homens e mulheres, que olhavam enquanto Sansão os divertia.

[[v7-16-28]]

^<<v7-16-28,28>>^ Sansão clamou ao Senhor  e disse: — Senhor  Deus, peço-te que te lembres de mim. Dá-me força só mais esta vez, ó Deus, para que eu me vingue dos filisteus, que furaram os meus olhos.

[[v7-16-29]]

^<<v7-16-29,29>>^ Em seguida, Sansão abraçou-se às duas colunas do meio, que sustentavam o templo, e fez força sobre elas, com a mão direita em uma e com a esquerda na outra.

[[v7-16-30]]

^<<v7-16-30,30>>^ E disse: — Que eu morra com os filisteus. E empurrou com toda a sua força, e o templo caiu sobre os governantes e sobre todo o povo que ali estava. Assim, foram mais os que Sansão matou quando morreu do que os que ele havia matado durante toda a sua vida.

[[v7-16-31]]

^<<v7-16-31,31>>^ Então os seus irmãos e toda a casa de seu pai foram buscar o corpo. Eles o levaram e sepultaram entre Zorá e Estaol, no túmulo de Manoá, seu pai. Sansão julgou Israel durante vinte anos.

'''

xref:007-juizes/007-juizes-015.adoc#v7-15-0[&#60; Capítulo Anterior] | <<v7-16-0,Topo>> | xref:007-juizes/007-juizes-017.adoc#v7-17-0[Próximo Capítulo &#62;]