include::./index.adoc[]

[[v7-6-0]]
=== Juízes, 6
// naa ?, NAA - Nova Almeida Atualizada

[[v7-6-1]]

^<<v7-6-1,1>>^ Os filhos de Israel fizeram o que era mau aos olhos do Senhor  e por isso o Senhor  os entregou nas mãos dos midianitas durante sete anos.

[[v7-6-2]]

^<<v7-6-2,2>>^ Os midianitas prevaleceram contra Israel. E, por causa dos midianitas, os filhos de Israel fizeram para si as covas que estão nos montes, as cavernas e as fortificações.

[[v7-6-3]]

^<<v7-6-3,3>>^ Porque, cada vez que os israelitas semeavam, os midianitas, os amalequitas e os povos do Oriente os atacavam.

[[v7-6-4]]

^<<v7-6-4,4>>^ Acampavam em Israel, destruindo os produtos da terra até a vizinhança de Gaza, e não deixavam em Israel sustento algum, nem ovelhas, nem bois, nem jumentos.

[[v7-6-5]]

^<<v7-6-5,5>>^ Pois vinham com o seu gado e as suas tendas, como uma nuvem de gafanhotos. Eram tantos, que não se podiam contar, nem a eles nem aos seus camelos; e entravam na terra para a destruir.

[[v7-6-6]]

^<<v7-6-6,6>>^ Assim, Israel ficou muito debilitado com a presença dos midianitas. Então os filhos de Israel clamaram ao Senhor .

[[v7-6-7]]

^<<v7-6-7,7>>^ Quando os filhos de Israel clamaram ao Senhor  por causa dos midianitas,

[[v7-6-8]]

^<<v7-6-8,8>>^ o Senhor  lhes enviou um profeta, que lhes disse: — Assim diz o Senhor , Deus de Israel: "Eu tirei vocês do Egito, da casa da servidão.

[[v7-6-9]]

^<<v7-6-9,9>>^ Eu os livrei das mãos dos egípcios e das mãos de todos os opressores. Eu os expulsei e dei a vocês a terra deles.

[[v7-6-10]]

^<<v7-6-10,10>>^ E disse: ‘Eu sou o Senhor , o Deus de vocês; não adorem os deuses dos amorreus, em cuja terra vocês estão morando.’ Mas vocês não deram ouvidos à minha voz."

[[v7-6-11]]

^<<v7-6-11,11>>^ Então o Anjo do Senhor  veio e sentou-se debaixo do carvalho que está em Ofra, que pertencia a Joás, da família de Abiezer. Gideão, filho de Joás, estava malhando o trigo no lagar, para o pôr a salvo dos midianitas.

[[v7-6-12]]

^<<v7-6-12,12>>^ Então o Anjo do Senhor  lhe apareceu e lhe disse: — O Senhor  está com você, homem valente.

[[v7-6-13]]

^<<v7-6-13,13>>^ Gideão respondeu: — Ah! Meu senhor! Se o Senhor  Deus está conosco, por que nos aconteceu tudo isto? E onde estão todas as suas maravilhas que os nossos pais nos contaram? Eles disseram: "O Senhor  nos tirou do Egito!" Porém, agora, o Senhor  nos abandonou e nos entregou nas mãos dos midianitas.

[[v7-6-14]]

^<<v7-6-14,14>>^ Então o Senhor  se virou para Gideão e disse: — Vá nessa força que você tem e livre Israel das mãos dos midianitas. Não é verdade que eu estou enviando você?

[[v7-6-15]]

^<<v7-6-15,15>>^ Gideão respondeu: — Ah! Meu Senhor! Como livrarei Israel? Eis que a minha família é a mais pobre em Manassés, e eu sou o menor na casa de meu pai.

[[v7-6-16]]

^<<v7-6-16,16>>^ Mas o Senhor  disse: — Já que eu estou ao seu lado, você derrotará os midianitas como se fossem um só homem.

[[v7-6-17]]

^<<v7-6-17,17>>^ Gideão respondeu: — Se de fato encontrei favor aos teus olhos, dá-me um sinal de que és tu, Senhor , que estás falando comigo.

[[v7-6-18]]

^<<v7-6-18,18>>^ Peço que não te afastes daqui até que eu volte, traga a minha oferta e a coloque diante de ti. Ele respondeu: — Eu esperarei até que você volte.

[[v7-6-19]]

^<<v7-6-19,19>>^ Gideão entrou em casa, preparou um cabrito e fez pães sem fermento com vinte litros de farinha. Pôs a carne num cesto, e o caldo, numa panela. Depois, trouxe tudo até debaixo do carvalho e o entregou ao Anjo.

[[v7-6-20]]

^<<v7-6-20,20>>^ Porém o Anjo de Deus lhe disse: — Pegue a carne e os pães sem fermento e coloque-os sobre esta rocha. Depois, derrame o caldo em cima. Foi o que Gideão fez.

[[v7-6-21]]

^<<v7-6-21,21>>^ Então o Anjo do Senhor  estendeu a ponta do cajado que trazia na mão e tocou a carne e os pães sem fermento. Saiu fogo da rocha e queimou a carne e os pães. E o Anjo do Senhor  desapareceu da presença dele.

[[v7-6-22]]

^<<v7-6-22,22>>^ Quando Gideão viu que era o Anjo do Senhor , disse: — Ai de mim, Senhor  Deus! Pois vi o Anjo do Senhor  face a face.

[[v7-6-23]]

^<<v7-6-23,23>>^ Mas o Senhor  lhe disse: — Que a paz esteja com você! Não tenha medo! Você não morrerá!

[[v7-6-24]]

^<<v7-6-24,24>>^ Então Gideão edificou ali um altar ao Senhor  e lhe deu o nome de "O Senhor  É Paz". Até o dia de hoje esse altar está em Ofra, que pertence à família de Abiezer.

[[v7-6-25]]

^<<v7-6-25,25>>^ Naquela mesma noite, o Senhor  disse a Gideão: — Leve o touro que pertence a seu pai, a saber, o segundo touro de sete anos, e derrube o altar de Baal que é do seu pai, e corte o poste da deusa Aserá que está junto ao altar.

[[v7-6-26]]

^<<v7-6-26,26>>^ No alto desse lugar fortificado faça para o Senhor , seu Deus, um altar em camadas de pedra. Depois, pegue o segundo touro e ofereça-o em holocausto com a lenha do poste da deusa Aserá que você irá cortar.

[[v7-6-27]]

^<<v7-6-27,27>>^ Então Gideão levou dez homens dos seus servos e fez como o Senhor  lhe havia falado. Mas, porque teve medo da casa de seu pai e dos homens daquela cidade, não o fez de dia, mas de noite.

[[v7-6-28]]

^<<v7-6-28,28>>^ De madrugada, quando os homens daquela cidade se levantaram, eis que o altar de Baal estava derrubado, e o poste da deusa Aserá que estava junto dele, cortado; e o referido segundo touro tinha sido oferecido no altar que havia sido edificado.

[[v7-6-29]]

^<<v7-6-29,29>>^ E diziam uns aos outros: — Quem fez isto? E, perguntando e inquirindo, disseram: — Quem fez isso foi Gideão, o filho de Joás.

[[v7-6-30]]

^<<v7-6-30,30>>^ Então os homens daquela cidade disseram a Joás: — Traga o seu filho para fora, para que seja morto, pois derrubou o altar de Baal e cortou o poste da deusa Aserá que estava junto dele.

[[v7-6-31]]

^<<v7-6-31,31>>^ Porém Joás disse a todos os que se puseram contra ele: — Vocês querem defender a causa de Baal? Vocês querem livrá-lo? Quem defender a causa dele será morto ainda esta manhã. Se ele é deus, que defenda a si mesmo; afinal, derrubaram o seu altar.

[[v7-6-32]]

^<<v7-6-32,32>>^ Naquele dia Gideão passou a ser chamado de Jerubaal, porque foi dito: "Que Baal defenda a sua causa contra ele, pois foi ele quem derrubou o seu altar."

[[v7-6-33]]

^<<v7-6-33,33>>^ Todos os midianitas, amalequitas e povos do Oriente se ajuntaram, passaram o Jordão e acamparam no vale de Jezreel.

[[v7-6-34]]

^<<v7-6-34,34>>^ Então o Espírito do Senhor  revestiu Gideão, que fez soar o alarme, convocando os homens da família de Abiezer a segui-lo.

[[v7-6-35]]

^<<v7-6-35,35>>^ Enviou mensageiros por toda a tribo de Manassés, que também foi convocada a segui-lo. Enviou ainda mensageiros a Aser, a Zebulom e a Naftali, que foram se encontrar com ele.

[[v7-6-36]]

^<<v7-6-36,36>>^ Então Gideão se dirigiu a Deus, dizendo: — Se realmente queres livrar Israel por minha mão, como disseste,

[[v7-6-37]]

^<<v7-6-37,37>>^ eis que eu porei uma porção de lã na eira. Se o orvalho estiver somente nela, e a terra ao redor estiver seca, então saberei que irás livrar Israel por meio de mim, como disseste.

[[v7-6-38]]

^<<v7-6-38,38>>^ E assim aconteceu. No outro dia, Gideão se levantou de madrugada e, apertando a lã, do orvalho que havia nela espremeu uma taça cheia de água.

[[v7-6-39]]

^<<v7-6-39,39>>^ Gideão se dirigiu a Deus mais uma vez, dizendo: — Não se acenda contra mim a tua ira, se eu falar somente mais esta vez. Peço-te que me deixes fazer mais uma prova com a lã: que desta vez só a lã esteja seca, e que haja orvalho na terra ao redor dela.

[[v7-6-40]]

^<<v7-6-40,40>>^ E Deus assim o fez naquela noite, pois só a lã estava seca, e sobre a terra ao redor dela havia orvalho.

'''

xref:007-juizes/007-juizes-005.adoc#v7-5-0[&#60; Capítulo Anterior] | <<v7-6-0,Topo>> | xref:007-juizes/007-juizes-007.adoc#v7-7-0[Próximo Capítulo &#62;]