include::./index.adoc[]

[[v7-1-0]]
=== Juízes, 1
// naa ?, NAA - Nova Almeida Atualizada

[[v7-1-1]]

^<<v7-1-1,1>>^ Depois da morte de Josué, os filhos de Israel consultaram o Senhor , dizendo: — Quem de nós será a primeira tribo a lutar contra os cananeus?

[[v7-1-2]]

^<<v7-1-2,2>>^ O Senhor  respondeu: — A tribo de Judá será a primeira; eis que entreguei a terra nas mãos desta tribo.

[[v7-1-3]]

^<<v7-1-3,3>>^ Então os filhos de Judá disseram aos seus irmãos da tribo de Simeão: — Venham conosco à herança que nos caiu por sorteio, e lutemos contra os cananeus. Depois também nós iremos com vocês à herança que lhes caiu por sorteio. E os filhos de Simeão foram com eles.

[[v7-1-4]]

^<<v7-1-4,4>>^ Os filhos de Judá atacaram, e o Senhor  lhes entregou nas mãos os cananeus e os ferezeus; e, em Bezeque, mataram dez mil homens.

[[v7-1-5]]

^<<v7-1-5,5>>^ Em Bezeque, encontraram Adoni-Bezeque e lutaram contra ele; e derrotaram os cananeus e os ferezeus.

[[v7-1-6]]

^<<v7-1-6,6>>^ Adoni-Bezeque fugiu, mas eles o perseguiram e, prendendo-o, lhe cortaram os polegares das mãos e dos pés.

[[v7-1-7]]

^<<v7-1-7,7>>^ Então Adoni-Bezeque disse: — Setenta reis, a quem haviam sido cortados os polegares das mãos e dos pés, apanhavam migalhas debaixo da minha mesa. Assim como eu fiz, assim Deus me retribuiu. E o levaram a Jerusalém, onde morreu.

[[v7-1-8]]

^<<v7-1-8,8>>^ Os filhos de Judá atacaram Jerusalém e, tomando-a, mataram os seus moradores e puseram fogo na cidade.

[[v7-1-9]]

^<<v7-1-9,9>>^ Depois, os filhos de Judá foram lutar contra os cananeus que habitavam nas montanhas, no Neguebe e na Sefelá.

[[v7-1-10]]

^<<v7-1-10,10>>^ Também atacaram os cananeus que moravam em Hebrom, cujo nome antes era Quiriate-Arba, e derrotaram Sesai, Aimã e Talmai.

[[v7-1-11]]

^<<v7-1-11,11>>^ Dali os filhos de Judá marcharam contra os moradores de Debir, que antes era chamada de Quiriate-Sefer.

[[v7-1-12]]

^<<v7-1-12,12>>^ Então Calebe disse: — Darei a minha filha Acsa por mulher ao homem que atacar e conquistar Quiriate-Sefer.

[[v7-1-13]]

^<<v7-1-13,13>>^ Quem conquistou a cidade foi Otniel, filho de Quenaz, o irmão de Calebe, mais novo do que ele. E Calebe lhe deu a sua filha Acsa por mulher.

[[v7-1-14]]

^<<v7-1-14,14>>^ Esta, quando foi morar com Otniel, insistiu com ele para que pedisse um campo ao pai dela. Quando ela desceu do jumento, Calebe lhe perguntou: — O que é que você quer?

[[v7-1-15]]

^<<v7-1-15,15>>^ Ela respondeu: — Quero que me dê um presente. Já que o senhor me deu uma terra seca, me dê também algumas fontes de água. Então Calebe lhe deu as fontes superiores e as fontes inferiores.

[[v7-1-16]]

^<<v7-1-16,16>>^ Os filhos do queneu, sogro de Moisés, saíram da cidade das palmeiras com os filhos de Judá e foram ao deserto de Judá, que está ao sul de Arade; foram e habitaram com este povo.

[[v7-1-17]]

^<<v7-1-17,17>>^ Os filhos de Judá foram com os seus irmãos da tribo de Simeão e atacaram os cananeus que moravam em Zefate e destruíram totalmente a cidade; por isso, foi chamada de Horma.

[[v7-1-18]]

^<<v7-1-18,18>>^ Também conquistaram Gaza, Asquelom e Ecrom com os seus respectivos territórios.

[[v7-1-19]]

^<<v7-1-19,19>>^ O Senhor  esteve com os filhos de Judá, e estes ocuparam a região das montanhas. Porém não expulsaram os moradores do vale, porque estes tinham carros de ferro.

[[v7-1-20]]

^<<v7-1-20,20>>^ E, como Moisés havia prometido, deram Hebrom a Calebe, e este expulsou dali os três filhos de Anaque.

[[v7-1-21]]

^<<v7-1-21,21>>^ Porém os filhos de Benjamim não expulsaram os jebuseus que moravam em Jerusalém. Assim, os jebuseus vivem com os filhos de Benjamim em Jerusalém até o dia de hoje.

[[v7-1-22]]

^<<v7-1-22,22>>^ A casa de José atacou Betel, e o Senhor  estava com eles.

[[v7-1-23]]

^<<v7-1-23,23>>^ A casa de José enviou homens a espiar Betel, que antes se chamava Luz.

[[v7-1-24]]

^<<v7-1-24,24>>^ Os espias viram um homem que saía da cidade e lhe disseram: — Mostre-nos a entrada da cidade, e teremos misericórdia de você.

[[v7-1-25]]

^<<v7-1-25,25>>^ O homem mostrou a entrada da cidade, e eles mataram os moradores ao fio da espada; mas deixaram ir aquele homem e toda a sua família.

[[v7-1-26]]

^<<v7-1-26,26>>^ Então ele foi para a terra dos heteus, edificou uma cidade, e lhe deu o nome de Luz. E este é o seu nome até o dia de hoje.

[[v7-1-27]]

^<<v7-1-27,27>>^ A tribo de Manassés não expulsou os moradores de Bete-Seã, nem os de Taanaque, nem os de Dor, nem os de Ibleão, nem os de Megido, todas com as suas respectivas aldeias; os cananeus continuaram a viver naquela terra.

[[v7-1-28]]

^<<v7-1-28,28>>^ Quando, porém, Israel se tornou mais forte, sujeitou os cananeus a trabalhos forçados, mas não os expulsou de todo.

[[v7-1-29]]

^<<v7-1-29,29>>^ A tribo de Efraim não expulsou os cananeus, moradores de Gezer. Assim, continuaram a viver com eles em Gezer.

[[v7-1-30]]

^<<v7-1-30,30>>^ A tribo de Zebulom não expulsou os moradores de Quitrom, nem os de Naalol. Os cananeus continuaram com eles, sujeitos a trabalhos forçados.

[[v7-1-31]]

^<<v7-1-31,31>>^ A tribo de Aser não expulsou os moradores de Aco, nem os de Sidom, os de Alabe, os de Aczibe, os de Helba, os de Afeca e os de Reobe.

[[v7-1-32]]

^<<v7-1-32,32>>^ Os aseritas continuaram no meio dos cananeus que moravam na terra, porque não os expulsaram.

[[v7-1-33]]

^<<v7-1-33,33>>^ A tribo de Naftali não expulsou os moradores de Bete-Semes, nem os de Bete-Anate, mas continuou no meio dos cananeus que moravam na terra. No entanto, os moradores de Bete-Semes e Bete-Anate ficaram sujeitos a trabalhos forçados.

[[v7-1-34]]

^<<v7-1-34,34>>^ Os amorreus levaram os filhos de Dã a se retirar para as montanhas e não os deixavam descer ao vale.

[[v7-1-35]]

^<<v7-1-35,35>>^ Os amorreus conseguiram permanecer nas montanhas de Heres, em Aijalom e em Saalabim; no entanto, a mão da casa de José prevaleceu, e os amorreus foram sujeitos a trabalhos forçados.

[[v7-1-36]]

^<<v7-1-36,36>>^ O território dos amorreus ia desde a subida de Acrabim e desde Sela para cima.

'''

xref:006-josue/006-josue-024.adoc#v6-24-0[&#60; Capítulo Anterior] | <<v7-1-0,Topo>> | xref:007-juizes/007-juizes-002.adoc#v7-2-0[Próximo Capítulo &#62;]