include::./index.adoc[]

[[v7-9-0]]
=== Juízes, 9
// naa ?, NAA - Nova Almeida Atualizada

[[v7-9-1]]

^<<v7-9-1,1>>^ Abimeleque, filho de Jerubaal, foi a Siquém, aos parentes de sua mãe, e falou com eles e com toda a geração da casa de seu avô materno, dizendo:

[[v7-9-2]]

^<<v7-9-2,2>>^ — Peço-lhes que perguntem a todos os cidadãos de Siquém: "O que é melhor para vocês: que setenta homens, todos os filhos de Jerubaal, dominem sobre vocês ou que vocês sejam dominados por apenas um?" Lembrem-se também de que eu sou osso e carne de vocês.

[[v7-9-3]]

^<<v7-9-3,3>>^ Então os parentes de sua mãe falaram a todos os cidadãos de Siquém todas aquelas palavras, e o coração deles se inclinou a seguir Abimeleque, porque disseram: "É nosso irmão."

[[v7-9-4]]

^<<v7-9-4,4>>^ E deram-lhe setenta peças de prata, da casa de Baal-Berite, com as quais Abimeleque contratou uns homens levianos e atrevidos, que o seguiram.

[[v7-9-5]]

^<<v7-9-5,5>>^ Foi à casa de seu pai, em Ofra, e matou os seus irmãos, os filhos de Jerubaal, setenta homens, sobre uma pedra. Porém Jotão, o filho mais moço de Jerubaal, escapou, porque havia se escondido.

[[v7-9-6]]

^<<v7-9-6,6>>^ Então se reuniram todos os cidadãos de Siquém e toda Bete-Milo, foram e proclamaram Abimeleque rei, junto ao carvalho memorial que está perto de Siquém.

[[v7-9-7]]

^<<v7-9-7,7>>^ Quando soube disto, Jotão foi e se pôs no alto do monte Gerizim. E, em alta voz, gritou, dizendo: — Cidadãos de Siquém, escutem o que vou dizer, e Deus escutará vocês!

[[v7-9-8]]

^<<v7-9-8,8>>^ Certa vez as árvores foram ungir para si um rei. Disseram à oliveira: "Reine sobre nós."

[[v7-9-9]]

^<<v7-9-9,9>>^ Porém a oliveira lhes respondeu: "Deixaria eu o meu óleo, apreciado por Deus e pelos homens, para dominar sobre as árvores?"

[[v7-9-10]]

^<<v7-9-10,10>>^ Então as árvores disseram à figueira: "Venha você e reine sobre nós."

[[v7-9-11]]

^<<v7-9-11,11>>^ Porém a figueira lhes respondeu: "Deixaria eu a minha doçura, o meu bom fruto, para dominar sobre as árvores?"

[[v7-9-12]]

^<<v7-9-12,12>>^ Então as árvores disseram à videira: "Venha você e reine sobre nós."

[[v7-9-13]]

^<<v7-9-13,13>>^ Porém a videira lhes respondeu: "Deixaria eu o meu vinho, que agrada a Deus e aos homens, para dominar sobre as árvores?"

[[v7-9-14]]

^<<v7-9-14,14>>^ Então todas as árvores disseram ao espinheiro: "Venha você e reine sobre nós."

[[v7-9-15]]

^<<v7-9-15,15>>^ E o espinheiro respondeu às árvores: "Se é verdade que querem me ungir rei sobre vocês, venham e se refugiem debaixo de minha sombra. Mas, se não, que do espinheiro saia fogo que consuma os cedros do Líbano."

[[v7-9-16]]

^<<v7-9-16,16>>^ Jotão continuou: — E agora, se vocês agiram de boa fé e com sinceridade, proclamando Abimeleque como rei; se vocês fizeram o que é correto em relação a Jerubaal e à sua casa, e se o trataram segundo ele merecia pelo que fez

[[v7-9-17]]

^<<v7-9-17,17>>^ — porque o meu pai lutou por vocês, arriscou a vida e os livrou das mãos dos midianitas;

[[v7-9-18]]

^<<v7-9-18,18>>^ mas hoje vocês se levantaram contra a casa de meu pai e mataram os filhos dele, setenta homens, sobre uma pedra; e a Abimeleque, filho da escrava dele, vocês puseram como rei sobre os cidadãos de Siquém, porque é irmão de vocês —,

[[v7-9-19]]

^<<v7-9-19,19>>^ se vocês agiram de boa fé e com sinceridade para com Jerubaal e a sua casa, então alegrem-se com Abimeleque, e que ele também se alegre com vocês.

[[v7-9-20]]

^<<v7-9-20,20>>^ Mas, se este não for o caso, que saia fogo de Abimeleque e consuma os cidadãos de Siquém e Bete-Milo! E que saia fogo dos cidadãos de Siquém e de Bete-Milo, que consuma Abimeleque.

[[v7-9-21]]

^<<v7-9-21,21>>^ Depois disso Jotão fugiu e foi para Beer, onde ficou morando, porque estava com medo de seu irmão Abimeleque.

[[v7-9-22]]

^<<v7-9-22,22>>^ Abimeleque havia dominado sobre Israel durante três anos,

[[v7-9-23]]

^<<v7-9-23,23>>^ quando Deus suscitou um espírito de aversão entre Abimeleque e os cidadãos de Siquém, que foram desleais com Abimeleque.

[[v7-9-24]]

^<<v7-9-24,24>>^ Isto aconteceu para que fosse vingada a violência praticada contra os setenta filhos de Jerubaal, e para que fossem castigados tanto Abimeleque, que era irmão deles e os havia matado, como os cidadãos de Siquém, que contribuíram para que ele matasse os seus próprios irmãos.

[[v7-9-25]]

^<<v7-9-25,25>>^ Os cidadãos de Siquém puseram sobre os altos dos montes homens de emboscada contra Abimeleque, e eles assaltavam todos os que passavam pelo caminho perto deles. E Abimeleque foi informado disso.

[[v7-9-26]]

^<<v7-9-26,26>>^ Gaal, filho de Ebede, veio com os seus irmãos, e se estabeleceram em Siquém. E os cidadãos de Siquém confiaram nele,

[[v7-9-27]]

^<<v7-9-27,27>>^ foram ao campo, cortaram os cachos das vinhas, pisaram as uvas, fizeram festas, foram à casa de seu deus, comeram, beberam e amaldiçoaram Abimeleque.

[[v7-9-28]]

^<<v7-9-28,28>>^ E Gaal, filho de Ebede, disse: — Quem é Abimeleque, e quem somos nós de Siquém, para que o sirvamos? Não é ele filho de Jerubaal? E não é Zebul o seu oficial? Seria melhor servir os homens de Hamor, pai de Siquém. Mas nós, por que serviremos a ele?

[[v7-9-29]]

^<<v7-9-29,29>>^ Quem dera estivesse este povo na minha mão! Eu expulsaria Abimeleque. Eu diria a Abimeleque: "Multiplique o seu exército e venha lutar."

[[v7-9-30]]

^<<v7-9-30,30>>^ Quando Zebul, governador da cidade, ouviu as palavras de Gaal, filho de Ebede, ficou furioso.

[[v7-9-31]]

^<<v7-9-31,31>>^ E enviou, secretamente, mensageiros a Abimeleque, dizendo: — Eis que Gaal, filho de Ebede, e seus irmãos vieram a Siquém e estão alvoroçando a cidade contra você.

[[v7-9-32]]

^<<v7-9-32,32>>^ Levante-se de noite, você e o povo que estiver com você, e ponham-se de emboscada no campo.

[[v7-9-33]]

^<<v7-9-33,33>>^ Levante-se pela manhã, ao sair o sol, e ataque a cidade. Quando Gaal com a sua gente sair para atacar, faça com ele o que estiver ao seu alcance.

[[v7-9-34]]

^<<v7-9-34,34>>^ Assim, Abimeleque se levantou, de noite, e todo o povo que estava com ele, e se puseram de emboscada contra Siquém, em quatro grupos.

[[v7-9-35]]

^<<v7-9-35,35>>^ Gaal, filho de Ebede, saiu e pôs-se à entrada do portão da cidade. Com isto Abimeleque e todo o povo que estava com ele se levantaram das emboscadas.

[[v7-9-36]]

^<<v7-9-36,36>>^ Gaal viu aquele povo e disse a Zebul: — Veja! Vem gente descendo do alto dos montes. Mas Zebul respondeu: — Você está vendo as sombras dos montes. Elas se parecem com homens.

[[v7-9-37]]

^<<v7-9-37,37>>^ Porém Gaal tornou ainda a falar e disse: — Veja! Vem gente descendo bem na nossa frente, e uma tropa vem vindo do caminho do carvalho dos Adivinhos.

[[v7-9-38]]

^<<v7-9-38,38>>^ Então Zebul disse a Gaal: — Onde ficaram, agora, as suas ameaças? Não foi você quem dizia: "Quem é Abimeleque, para que o sirvamos?" Não é este o povo que você desprezou? Pois saia agora e vá lutar contra ele.

[[v7-9-39]]

^<<v7-9-39,39>>^ Gaal saiu à frente dos cidadãos de Siquém e lutou contra Abimeleque.

[[v7-9-40]]

^<<v7-9-40,40>>^ Abimeleque perseguiu Gaal, que fugiu dele. E muitos feridos caíram até a entrada do portão da cidade.

[[v7-9-41]]

^<<v7-9-41,41>>^ Abimeleque ficou em Arumá. E Zebul expulsou Gaal e seus irmãos, para que não ficassem morando em Siquém.

[[v7-9-42]]

^<<v7-9-42,42>>^ No dia seguinte, o povo de Siquém saiu ao campo, e Abimeleque foi avisado disto.

[[v7-9-43]]

^<<v7-9-43,43>>^ Então ele reuniu os seus homens, e os dividiu em três grupos, e os pôs de emboscada no campo. Quando Abimeleque viu que o povo saía da cidade, levantou-se contra eles e os atacou.

[[v7-9-44]]

^<<v7-9-44,44>>^ Abimeleque e o grupo que estava com ele correram e tomaram posição junto à entrada da cidade, enquanto os dois outros grupos atacaram todos os que estavam no campo e os destroçaram.

[[v7-9-45]]

^<<v7-9-45,45>>^ Abimeleque lutou contra a cidade durante todo aquele dia. Tomou a cidade e matou o povo que nela havia. Arrasou a cidade e espalhou sal sobre ela.

[[v7-9-46]]

^<<v7-9-46,46>>^ Todos os cidadãos da Torre de Siquém souberam disso e entraram na fortaleza, no templo de El-Berite.

[[v7-9-47]]

^<<v7-9-47,47>>^ Mas Abimeleque soube que todos os cidadãos da Torre de Siquém se haviam reunido.

[[v7-9-48]]

^<<v7-9-48,48>>^ Então ele subiu o monte Salmom, ele e todo o seu povo. Abimeleque pegou um machado e cortou o galho de uma árvore. Ele o levantou, pôs no ombro e disse ao povo que estava com ele: — O que vocês me viram fazer, façam também vocês, depressa.

[[v7-9-49]]

^<<v7-9-49,49>>^ Assim, cada um deles cortou um galho e seguiu Abimeleque. Puseram os galhos ao redor da fortaleza, e os incendiaram. Assim, morreram todos os que estavam na Torre de Siquém, mais ou menos mil pessoas, homens e mulheres.

[[v7-9-50]]

^<<v7-9-50,50>>^ Então Abimeleque foi a Tebes, sitiou a cidade e a tomou.

[[v7-9-51]]

^<<v7-9-51,51>>^ Havia, porém, no meio da cidade, uma torre forte, e todos os homens e mulheres, todos os moradores da cidade, fugiram para lá. Fecharam as portas da torre e subiram ao terraço.

[[v7-9-52]]

^<<v7-9-52,52>>^ Abimeleque veio até a torre, lutou contra ela e se aproximou da porta para a incendiar.

[[v7-9-53]]

^<<v7-9-53,53>>^ Mas uma mulher jogou uma pedra superior de moinho sobre a cabeça de Abimeleque e lhe quebrou o crânio.

[[v7-9-54]]

^<<v7-9-54,54>>^ Então Abimeleque chamou depressa o moço, seu escudeiro, e lhe disse: — Tire a sua espada e me mate, para que não se diga que uma mulher me matou. O moço o atravessou com a espada, e ele morreu.

[[v7-9-55]]

^<<v7-9-55,55>>^ Quando os homens de Israel viram que Abimeleque já estava morto, foram embora, cada um para a sua casa.

[[v7-9-56]]

^<<v7-9-56,56>>^ Assim, Deus fez cair sobre Abimeleque o mal que ele havia feito a seu pai, ao matar os seus setenta irmãos.

[[v7-9-57]]

^<<v7-9-57,57>>^ De igual modo, Deus fez cair sobre a cabeça dos homens de Siquém todo o mal que haviam praticado. Assim, veio sobre eles a maldição de Jotão, filho de Jerubaal.

'''

xref:007-juizes/007-juizes-008.adoc#v7-8-0[&#60; Capítulo Anterior] | <<v7-9-0,Topo>> | xref:007-juizes/007-juizes-010.adoc#v7-10-0[Próximo Capítulo &#62;]