include::./index.adoc[]

[[v7-5-0]]
=== Juízes, 5
// naa ?, NAA - Nova Almeida Atualizada

[[v7-5-1]]

^<<v7-5-1,1>>^ Naquele dia Débora e Baraque, filho de Abinoão, cantaram assim:

[[v7-5-2]]

^<<v7-5-2,2>>^ Porque os chefes se puseram à frente de Israel, e o povo se ofereceu voluntariamente, bendigam o Senhor !

[[v7-5-3]]

^<<v7-5-3,3>>^ Escutem, ó reis! Ouçam, ó príncipes! Eu, eu mesma cantarei ao Senhor ; salmodiarei ao Senhor , Deus de Israel.

[[v7-5-4]]

^<<v7-5-4,4>>^ Quando tu, ó Senhor , saíste de Seir, marchando desde o campo de Edom, a terra estremeceu; os céus gotejaram, sim, até as nuvens gotejaram água.

[[v7-5-5]]

^<<v7-5-5,5>>^ Os montes tremeram diante do Senhor , e até o Sinai, diante do Senhor , Deus de Israel.

[[v7-5-6]]

^<<v7-5-6,6>>^ Nos dias de Sangar, filho de Anate, nos dias de Jael, cessaram as caravanas; e os viajantes tomavam desvios tortuosos.

[[v7-5-7]]

^<<v7-5-7,7>>^ Ficaram desertas as aldeias em Israel, ficaram desertas até que eu, Débora, me levantei; levantei-me por mãe em Israel.

[[v7-5-8]]

^<<v7-5-8,8>>^ Escolheram-se deuses novos; então a guerra estava às portas; não se via escudo nem lança entre quarenta mil em Israel.

[[v7-5-9]]

^<<v7-5-9,9>>^ Meu coração está com os comandantes de Israel, que, voluntariamente, se ofereceram entre o povo. Bendigam o Senhor .

[[v7-5-10]]

^<<v7-5-10,10>>^ Vocês que cavalgam jumentas brancas, que se assentam em juízo e que andam pelo caminho, falem disto.

[[v7-5-11]]

^<<v7-5-11,11>>^ À música dos distribuidores de água, lá entre os canais dos rebanhos, falem dos atos de justiça do Senhor , das justiças a favor de suas aldeias em Israel. Então o povo do Senhor  pôde descer aos portões da cidade.

[[v7-5-12]]

^<<v7-5-12,12>>^ Desperte, Débora, desperte! Desperte, acorde, entoe um cântico! Levante-se, Baraque, filho de Abinoão, e leve presos os que o prenderam.

[[v7-5-13]]

^<<v7-5-13,13>>^ Então desceu o restante dos nobres, o povo do Senhor  em meu auxílio contra os poderosos.

[[v7-5-14]]

^<<v7-5-14,14>>^ De Efraim, cujas raízes estão na antiga região de Amaleque, desceram guerreiros; depois de você, ó Débora, seguiu Benjamim com seus povos; de Maquir desceram comandantes, e, de Zebulom, os que levam a vara de comando.

[[v7-5-15]]

^<<v7-5-15,15>>^ Também os príncipes de Issacar foram com Débora; Issacar seguiu Baraque, em cujas pegadas foi enviado para o vale. Entre as facções de Rúben houve grande discussão.

[[v7-5-16]]

^<<v7-5-16,16>>^ Por que vocês ficaram entre os currais para ouvir a flauta? Entre as facções de Rúben houve grande discussão.

[[v7-5-17]]

^<<v7-5-17,17>>^ Gileade ficou do outro lado do Jordão, e Dã, por que se deteve junto a seus navios? Aser ficou junto à costa do mar e repousou nas suas baías.

[[v7-5-18]]

^<<v7-5-18,18>>^ Zebulom é povo que arriscou a sua vida, bem como Naftali, nas alturas do campo.

[[v7-5-19]]

^<<v7-5-19,19>>^ Vieram reis e lutaram. Os reis de Canaã lutaram em Taanaque, junto às águas de Megido, mas não levaram nenhum despojo de prata.

[[v7-5-20]]

^<<v7-5-20,20>>^ Lá do céu as estrelas lutaram; desde os lugares dos seus cursos lutaram contra Sísera.

[[v7-5-21]]

^<<v7-5-21,21>>^ O ribeiro de Quisom os arrastou, Quisom, o antigo ribeiro. Avante, ó minha alma, firme!

[[v7-5-22]]

^<<v7-5-22,22>>^ Então os cascos dos cavalos socavam pelo galopar, o galopar dos seus guerreiros.

[[v7-5-23]]

^<<v7-5-23,23>>^ Amaldiçoem Meroz, diz o Anjo do Senhor , amaldiçoem duramente os seus moradores, porque não vieram em socorro do Senhor , em socorro do Senhor e seus heróis.

[[v7-5-24]]

^<<v7-5-24,24>>^ Que a mais bendita entre as mulheres seja Jael, mulher de Héber, o queneu; que seja a mais bendita entre as mulheres que vivem em tendas.

[[v7-5-25]]

^<<v7-5-25,25>>^ Sísera pediu água, e ela lhe deu leite; em taça de príncipes lhe ofereceu nata.

[[v7-5-26]]

^<<v7-5-26,26>>^ Ela estendeu uma das mãos e apanhou a estaca, e, com a mão direita, pegou o martelo dos trabalhadores. Golpeou Sísera, rachou-lhe a cabeça, furou e atravessou-lhe as têmporas.

[[v7-5-27]]

^<<v7-5-27,27>>^ Aos pés dela ele se encurvou, caiu e ficou estirado; a seus pés se encurvou e caiu; onde se encurvou, ali caiu morto.

[[v7-5-28]]

^<<v7-5-28,28>>^ A mãe de Sísera olhava pela janela e exclamava pela grade: "Por que tarda em vir o seu carro? Por que se demoram os passos dos seus cavalos?"

[[v7-5-29]]

^<<v7-5-29,29>>^ As mais sábias das suas damas respondem, e até ela a si mesma respondia:

[[v7-5-30]]

^<<v7-5-30,30>>^ "Não é verdade que acharam e estão repartindo os despojos? Uma ou duas moças para cada homem; tecidos de várias cores para Sísera, tecidos de várias cores de bordados; um ou dois tecidos bordados, para o pescoço da esposa."

[[v7-5-31]]

^<<v7-5-31,31>>^ Assim, ó Senhor , pereçam todos os teus inimigos! Porém os que te amam brilhem como o sol quando se levanta no seu esplendor. E a terra ficou em paz durante quarenta anos.

'''

xref:007-juizes/007-juizes-004.adoc#v7-4-0[&#60; Capítulo Anterior] | <<v7-5-0,Topo>> | xref:007-juizes/007-juizes-006.adoc#v7-6-0[Próximo Capítulo &#62;]