include::./index.adoc[]

[[v7-21-0]]
=== Juízes, 21
// naa ?, NAA - Nova Almeida Atualizada

[[v7-21-1]]

^<<v7-21-1,1>>^ Ora, os homens de Israel tinham feito um juramento em Mispa, dizendo: — Nenhum de nós dará sua filha em casamento aos benjamitas.

[[v7-21-2]]

^<<v7-21-2,2>>^ O povo foi a Betel, e ali ficaram até a tarde diante de Deus, levantaram a voz e choraram amargamente.

[[v7-21-3]]

^<<v7-21-3,3>>^ Disseram: — Ah! Senhor , Deus de Israel, por que aconteceu isto em Israel? Por que hoje falta uma tribo?

[[v7-21-4]]

^<<v7-21-4,4>>^ No dia seguinte, o povo, pela manhã, se levantou e edificou ali um altar. E apresentaram holocaustos e ofertas pacíficas.

[[v7-21-5]]

^<<v7-21-5,5>>^ E os filhos de Israel perguntaram: — Quem de todas as tribos de Israel não compareceu à assembleia do Senhor ? Porque tinham feito um juramento solene: quem não comparecesse à presença do Senhor  em Mispa seria morto.

[[v7-21-6]]

^<<v7-21-6,6>>^ Os filhos de Israel tiveram compaixão de seus irmãos da tribo de Benjamim e disseram: — Hoje foi eliminada uma das tribos de Israel.

[[v7-21-7]]

^<<v7-21-7,7>>^ Como obteremos mulheres para os restantes deles, pois juramos, pelo Senhor , que não lhes daríamos em casamento nenhuma de nossas filhas?

[[v7-21-8]]

^<<v7-21-8,8>>^ E perguntaram: — Há alguma das tribos de Israel que não tenha comparecido à presença do Senhor  em Mispa? E eis que ninguém de Jabes-Gileade tinha ido ao acampamento, à assembleia.

[[v7-21-9]]

^<<v7-21-9,9>>^ Quando contaram o povo, eis que nenhum dos moradores de Jabes-Gileade estava ali.

[[v7-21-10]]

^<<v7-21-10,10>>^ Por isso, a congregação mandou para lá doze mil homens dos mais valentes e lhes ordenou, dizendo: — Vão e matem os moradores de Jabes-Gileade a fio de espada, tanto homens como mulheres e crianças.

[[v7-21-11]]

^<<v7-21-11,11>>^ É isto que vocês devem fazer: Matem todos os homens, bem como todas as mulheres que não forem virgens.

[[v7-21-12]]

^<<v7-21-12,12>>^ E acharam entre os moradores de Jabes-Gileade quatrocentas moças virgens, que nunca haviam tido relações com homem algum; e as trouxeram ao acampamento, em Siló, que fica na terra de Canaã.

[[v7-21-13]]

^<<v7-21-13,13>>^ Então toda a congregação enviou mensageiros aos filhos de Benjamim que estavam na rocha de Rimom, e lhes fizeram uma proposta de paz.

[[v7-21-14]]

^<<v7-21-14,14>>^ Foi nesse tempo que os benjamitas voltaram e receberam aquelas mulheres de Jabes-Gileade que tinham sido conservadas com vida. Porém não havia uma para cada um deles.

[[v7-21-15]]

^<<v7-21-15,15>>^ Então o povo teve compaixão de Benjamim, porque o Senhor  tinha aberto uma brecha nas tribos de Israel.

[[v7-21-16]]

^<<v7-21-16,16>>^ Os anciãos da congregação disseram: — Como obteremos mulheres para os que sobraram, visto que as mulheres dos benjamitas foram exterminadas?

[[v7-21-17]]

^<<v7-21-17,17>>^ Disseram mais: — Deve haver uma herança para os benjamitas que sobraram, pois nenhuma tribo de Israel deve ser destruída.

[[v7-21-18]]

^<<v7-21-18,18>>^ Porém nós não podemos dar a eles as nossas filhas em casamento, porque os filhos de Israel juraram, dizendo: "Maldito o que der mulher aos benjamitas."

[[v7-21-19]]

^<<v7-21-19,19>>^ Então disseram: — Eis que, de ano em ano, há uma solenidade do Senhor  em Siló. Siló fica ao norte de Betel, do lado do nascente do sol, pelo caminho que vai de Betel a Siquém, e ao sul de Lebona.

[[v7-21-20]]

^<<v7-21-20,20>>^ Então deram uma ordem aos filhos de Benjamim, dizendo: — Vão e se escondam nas vinhas.

[[v7-21-21]]

^<<v7-21-21,21>>^ Fiquem vigiando. Quando as moças de Siló saírem a dançar em rodas, saiam das vinhas, e cada um agarre uma mulher para si. E então voltem para a terra de Benjamim.

[[v7-21-22]]

^<<v7-21-22,22>>^ Quando os pais ou os irmãos delas vierem se queixar a nós, diremos: "Tenham pena deles por amor de nós, pois, na guerra contra Jabes-Gileade, não conseguimos mulheres para todos eles. E vocês não as deram a eles, pois neste caso seriam culpados de quebrar o juramento."

[[v7-21-23]]

^<<v7-21-23,23>>^ Assim fizeram os filhos de Benjamim. E dentre as moças que saíram para dançar eles tomaram para si mulheres, conforme o número deles. Depois voltaram para a sua herança, reedificaram as cidades e habitaram nelas.

[[v7-21-24]]

^<<v7-21-24,24>>^ Então os filhos de Israel também partiram dali, cada um para a sua tribo, para a sua família e para a sua herança.

[[v7-21-25]]

^<<v7-21-25,25>>^ Naqueles dias, não havia rei em Israel; cada um fazia o que achava mais certo.

'''

xref:007-juizes/007-juizes-020.adoc#v7-20-0[&#60; Capítulo Anterior] | <<v7-21-0,Topo>> | xref:008-rute/008-rute-001.adoc#v8-1-0[Próximo Capítulo &#62;]