include::./index.adoc[]

[[v7-18-0]]
=== Juízes, 18
// naa ?, NAA - Nova Almeida Atualizada

[[v7-18-1]]

^<<v7-18-1,1>>^ Naqueles dias, não havia rei em Israel, e a tribo dos danitas estava procurando um território para morar, porque, até aquele dia, não tinha recebido herança entre as tribos de Israel.

[[v7-18-2]]

^<<v7-18-2,2>>^ Então os filhos de Dã enviaram cinco homens dentre todas as famílias da sua tribo, homens valentes, de Zorá e de Estaol, para espiar e explorar a terra. E lhes disseram: — Vão e explorem a terra. Chegaram à região montanhosa de Efraim, até a casa de Mica, e ali pernoitaram.

[[v7-18-3]]

^<<v7-18-3,3>>^ Quando se aproximaram da casa de Mica, reconheceram a voz do jovem levita. Chegaram perto dele e lhe perguntaram: — Quem trouxe você para cá? O que você está fazendo aqui? E o que prende você a este lugar?

[[v7-18-4]]

^<<v7-18-4,4>>^ Ele respondeu: — Assim e assim Mica fez comigo: ele me contratou, e eu me tornei o sacerdote dele.

[[v7-18-5]]

^<<v7-18-5,5>>^ E eles lhe disseram: — Então, por favor, consulte a Deus, para que saibamos se o caminho que seguimos irá prosperar.

[[v7-18-6]]

^<<v7-18-6,6>>^ O sacerdote respondeu: — Vão em paz. O caminho de vocês está sob as vistas do Senhor .

[[v7-18-7]]

^<<v7-18-7,7>>^ Os cinco homens partiram e chegaram a Laís. Viram que o povo daquele lugar vivia em segurança, segundo o costume dos sidônios, em paz e sem desconfiar de nada. Nenhuma autoridade havia que, por qualquer coisa, os oprimisse. Moravam longe dos sidônios e não tinham contato com outros povos.

[[v7-18-8]]

^<<v7-18-8,8>>^ Então os cinco homens voltaram a seus irmãos em Zorá e Estaol. E esses irmãos lhes perguntaram: — E então, o que nos dizem?

[[v7-18-9]]

^<<v7-18-9,9>>^ Eles responderam: — Preparem-se e vamos atacá-los. Porque examinamos a terra, e eis que é muito boa. Vão ficar aí parados? Vão depressa e ocupem aquela terra.

[[v7-18-10]]

^<<v7-18-10,10>>^ Quando chegarem lá, vão encontrar um povo que não desconfia de nada. A terra é ampla, e Deus a está entregando nas mãos de vocês. É um lugar em que não falta nada do que existe na terra.

[[v7-18-11]]

^<<v7-18-11,11>>^ Então partiram dali, do meio da tribo dos danitas, de Zorá e de Estaol, seiscentos homens armados com as suas armas de guerra.

[[v7-18-12]]

^<<v7-18-12,12>>^ Subiram e acamparam em Quiriate-Jearim, em Judá. Por isso aquele lugar é chamado de Maané-Dã, até o dia de hoje. Fica a oeste de Quiriate-Jearim.

[[v7-18-13]]

^<<v7-18-13,13>>^ Dali foram para a região montanhosa de Efraim e chegaram à casa de Mica.

[[v7-18-14]]

^<<v7-18-14,14>>^ Os cinco homens que foram espiar a terra de Laís disseram aos seus irmãos: — Vocês sabiam que numa daquelas casas há uma estola sacerdotal, alguns ídolos do lar, uma imagem de escultura e uma de fundição? Decidam, pois, o que vão fazer.

[[v7-18-15]]

^<<v7-18-15,15>>^ Então foram para lá, e chegaram à casa do jovem levita, que era a casa de Mica, e o saudaram.

[[v7-18-16]]

^<<v7-18-16,16>>^ Os seiscentos homens da tribo de Dã, armados com as suas armas de guerra, ficaram à entrada do portão.

[[v7-18-17]]

^<<v7-18-17,17>>^ Porém os cinco homens que tinham ido espiar a terra entraram na casa e apanharam a imagem de escultura, a estola sacerdotal, os ídolos do lar e a imagem de fundição, enquanto o sacerdote estava em pé à entrada do portão com os seiscentos homens que estavam armados com as armas de guerra.

[[v7-18-18]]

^<<v7-18-18,18>>^ Quando eles entraram na casa de Mica e apanharam a imagem de escultura, a estola sacerdotal, os ídolos do lar e a imagem de fundição, o sacerdote perguntou: — O que é que vocês estão fazendo?

[[v7-18-19]]

^<<v7-18-19,19>>^ Eles responderam: — Fique calado. Não diga nada a ninguém. Venha conosco e seja o nosso conselheiro e sacerdote. Ou você acha que é melhor ser sacerdote na casa de um só homem do que ser sacerdote de uma tribo e de uma família em Israel?

[[v7-18-20]]

^<<v7-18-20,20>>^ O sacerdote ficou contente, pegou a estola sacerdotal, os ídolos do lar e a imagem de escultura e entrou no meio do povo.

[[v7-18-21]]

^<<v7-18-21,21>>^ Eles deram meia-volta e partiram, não sem antes colocar diante de si as crianças, o gado e os seus bens.

[[v7-18-22]]

^<<v7-18-22,22>>^ Quando eles já estavam longe da casa de Mica, os vizinhos deste se reuniram e foram atrás dos filhos de Dã.

[[v7-18-23]]

^<<v7-18-23,23>>^ Eles gritaram para os filhos de Dã, que, voltando-se, perguntaram a Mica: — O que é que você quer? Por que você convocou todo esse povo?

[[v7-18-24]]

^<<v7-18-24,24>>^ Mica respondeu: — Vocês pegaram os deuses que eu fiz e também o meu sacerdote e foram embora. O que sobrou para mim? E vocês ainda me perguntam: "O que é que você quer?"

[[v7-18-25]]

^<<v7-18-25,25>>^ Porém os filhos de Dã lhe disseram: — Seria melhor você ficar calado, porque, se não, alguns dos nossos homens poderiam ficar irritados e acabariam atacando você. Nesse caso, perderiam a vida você e os da sua casa.

[[v7-18-26]]

^<<v7-18-26,26>>^ Assim, os filhos de Dã seguiram o seu caminho. E Mica, vendo que eram mais fortes do que ele, deu meia-volta e foi para casa.

[[v7-18-27]]

^<<v7-18-27,27>>^ Os homens de Dã levaram as coisas que Mica havia feito e também o sacerdote dele, e foram a Laís, a um povo que vivia em paz e sem desconfiar de nada. Mataram os moradores a fio de espada e queimaram a cidade.

[[v7-18-28]]

^<<v7-18-28,28>>^ Não houve ninguém que os livrasse, porque moravam longe de Sidom e não tinham contato com outros povos. A cidade ficava no vale junto a Bete-Reobe. Os filhos de Dã reedificaram a cidade e passaram a morar nela.

[[v7-18-29]]

^<<v7-18-29,29>>^ E lhe chamaram Dã, segundo o nome de Dã, seu pai, que era filho de Israel. Porém no passado o nome dessa cidade era Laís.

[[v7-18-30]]

^<<v7-18-30,30>>^ Os filhos de Dã levantaram para si aquela imagem de escultura, e Jônatas, filho de Gérson e neto de Moisés, ele e seus filhos foram sacerdotes da tribo dos danitas até o dia do cativeiro do povo.

[[v7-18-31]]

^<<v7-18-31,31>>^ Assim, pois, a imagem de escultura feita por Mica ficou entre eles durante todo o tempo em que a Casa de Deus esteve em Siló.

'''

xref:007-juizes/007-juizes-017.adoc#v7-17-0[&#60; Capítulo Anterior] | <<v7-18-0,Topo>> | xref:007-juizes/007-juizes-019.adoc#v7-19-0[Próximo Capítulo &#62;]