include::./index.adoc[]

[[v7-8-0]]
=== Juízes, 8
// naa ?, NAA - Nova Almeida Atualizada

[[v7-8-1]]

^<<v7-8-1,1>>^ Então os homens de Efraim disseram a Gideão: — Que é isto que você fez conosco, não nos chamando quando foi lutar contra os midianitas? E discutiram fortemente com ele.

[[v7-8-2]]

^<<v7-8-2,2>>^ Porém ele lhes disse: — Que mais fiz eu, agora, do que vocês? Não é fato que os poucos cachos de uvas deixados por Efraim são melhores do que toda a colheita de Abiezer?

[[v7-8-3]]

^<<v7-8-3,3>>^ Deus entregou nas mãos de vocês os príncipes dos midianitas, Orebe e Zeebe. O que pude eu fazer em comparação com o que vocês fizeram? Depois de ele dizer isto, abrandou-se a ira deles contra Gideão.

[[v7-8-4]]

^<<v7-8-4,4>>^ Quando Gideão chegou ao Jordão, passou com os trezentos homens que com ele estavam, cansados mas ainda perseguindo os inimigos.

[[v7-8-5]]

^<<v7-8-5,5>>^ E disse aos homens de Sucote: — Por favor, deem alguns pães para estes que me seguem, pois estão cansados, e eu vou ao encalço de Zeba e Salmuna, reis dos midianitas.

[[v7-8-6]]

^<<v7-8-6,6>>^ Porém os chefes de Sucote disseram: — Será que você já tem Zeba e Salmuna em seu poder, para que demos pão ao exército que está com você?

[[v7-8-7]]

^<<v7-8-7,7>>^ Então Gideão disse: — Por isso, quando o Senhor  entregar Zeba e Salmuna nas minhas mãos, rasgarei a carne de vocês com espinheiros e outras plantas do deserto.

[[v7-8-8]]

^<<v7-8-8,8>>^ Dali Gideão foi a Penuel e fez o mesmo pedido aos homens daquele lugar. Mas esses de Penuel lhe responderam como os homens de Sucote lhe haviam respondido.

[[v7-8-9]]

^<<v7-8-9,9>>^ Por isso também falou aos homens de Penuel, dizendo: — Quando eu voltar em paz, derrubarei esta torre.

[[v7-8-10]]

^<<v7-8-10,10>>^ Ora, Zeba e Salmuna estavam em Carcor com os seus exércitos, uns quinze mil homens, todos os que restaram do exército de povos do Oriente, pois cento e vinte mil homens que puxavam da espada tinham sido mortos.

[[v7-8-11]]

^<<v7-8-11,11>>^ Gideão foi pelo caminho dos nômades, a leste de Noba e Jogbeá, e atacou aquele exército de surpresa.

[[v7-8-12]]

^<<v7-8-12,12>>^ Zeba e Salmuna fugiram, mas Gideão os perseguiu. Ele prendeu os dois reis dos midianitas, Zeba e Salmuna, e deixou todo aquele exército em pânico.

[[v7-8-13]]

^<<v7-8-13,13>>^ Quando Gideão, filho de Joás, voltou da batalha, pela subida de Heres,

[[v7-8-14]]

^<<v7-8-14,14>>^ prendeu um moço de Sucote e lhe fez perguntas. E o moço deu por escrito o nome dos chefes e anciãos de Sucote, setenta e sete homens.

[[v7-8-15]]

^<<v7-8-15,15>>^ Então Gideão foi falar com os homens de Sucote e lhes disse: — Vejam! Aqui estão Zeba e Salmuna, a respeito dos quais vocês zombaram de mim, dizendo: "Será que você já tem Zeba e Salmuna em seu poder, para que demos pão aos seus homens cansados?"

[[v7-8-16]]

^<<v7-8-16,16>>^ E prendeu os anciãos da cidade. Pegou espinheiros e outras plantas do deserto e, com eles, deu severa lição aos homens de Sucote.

[[v7-8-17]]

^<<v7-8-17,17>>^ Derrubou a torre de Penuel e matou os homens da cidade.

[[v7-8-18]]

^<<v7-8-18,18>>^ Depois perguntou a Zeba e a Salmuna: — Como eram os homens que vocês mataram em Tabor? E eles responderam: — Como você, assim eram eles; cada um se parecia com um filho de rei.

[[v7-8-19]]

^<<v7-8-19,19>>^ Gideão disse: — Eram meus irmãos, filhos de minha mãe. Tão certo como vive o Senhor , se vocês os tivessem deixado com vida, eu não mataria vocês.

[[v7-8-20]]

^<<v7-8-20,20>>^ E disse a Jéter, seu primogênito: — Levante-se e mate-os. Porém o moço não arrancou da sua espada, porque teve medo, pois ainda era jovem.

[[v7-8-21]]

^<<v7-8-21,21>>^ Então Zeba e Salmuna disseram: — Venha você mesmo e nos mate. Pois o homem é conhecido por sua valentia. Gideão foi, matou Zeba e Salmuna e pegou os ornamentos em forma de meia-lua que estavam no pescoço dos camelos deles.

[[v7-8-22]]

^<<v7-8-22,22>>^ Então os homens de Israel disseram a Gideão: — Domine sobre nós, tanto você como o seu filho e o filho de seu filho, porque você nos livrou do poder dos midianitas.

[[v7-8-23]]

^<<v7-8-23,23>>^ Porém Gideão lhes disse: — Não dominarei sobre vocês, nem tampouco meu filho dominará sobre vocês. O Senhor  Deus dominará sobre vocês.

[[v7-8-24]]

^<<v7-8-24,24>>^ E Gideão continuou: — Mas quero fazer um pedido: que cada um de vocês me dê as argolas do seu despojo. É que os midianitas tinham argolas de ouro, pois eram ismaelitas.

[[v7-8-25]]

^<<v7-8-25,25>>^ Então eles responderam: — De bom grado as daremos. E estenderam uma capa, e cada um deles colocou ali uma argola do seu despojo.

[[v7-8-26]]

^<<v7-8-26,26>>^ O peso das argolas de ouro que pediu foi de uns vinte quilos de ouro — sem contar os ornamentos em forma de meia-lua, os pendentes e as roupas de púrpura que os reis dos midianitas usavam, e sem contar os ornamentos que os camelos traziam ao pescoço.

[[v7-8-27]]

^<<v7-8-27,27>>^ Disso Gideão fez uma estola sacerdotal e a pôs na sua cidade, em Ofra. E todo o Israel se prostituiu ali, adorando essa estola. E isso veio a ser um tropeço para Gideão e toda a sua casa.

[[v7-8-28]]

^<<v7-8-28,28>>^ Assim, os midianitas foram subjugados pelos filhos de Israel e nunca mais levantaram a cabeça. E a terra ficou em paz durante quarenta anos nos dias de Gideão.

[[v7-8-29]]

^<<v7-8-29,29>>^ Jerubaal, filho de Joás, retirou-se e ficou morando em sua casa.

[[v7-8-30]]

^<<v7-8-30,30>>^ Gideão teve setenta filhos, todos provindos dele, porque tinha muitas mulheres.

[[v7-8-31]]

^<<v7-8-31,31>>^ A sua concubina, que morava em Siquém, lhe deu também à luz um filho, e ele lhe deu o nome de Abimeleque.

[[v7-8-32]]

^<<v7-8-32,32>>^ Gideão, filho de Joás, morreu em boa velhice e foi sepultado no túmulo de Joás, seu pai, em Ofra, cidade da família de Abiezer.

[[v7-8-33]]

^<<v7-8-33,33>>^ Depois que Gideão morreu, os filhos de Israel voltaram a se prostituir com os baalins e puseram Baal-Berite por deus.

[[v7-8-34]]

^<<v7-8-34,34>>^ Os filhos de Israel não se lembraram do Senhor , seu Deus, que os havia livrado do poder de todos os seus inimigos ao redor.

[[v7-8-35]]

^<<v7-8-35,35>>^ Também não usaram de bondade com a casa de Jerubaal, a saber, Gideão, segundo todo o bem que ele tinha feito a Israel.

'''

xref:007-juizes/007-juizes-007.adoc#v7-7-0[&#60; Capítulo Anterior] | <<v7-8-0,Topo>> | xref:007-juizes/007-juizes-009.adoc#v7-9-0[Próximo Capítulo &#62;]