include::./index.adoc[]

[[v7-4-0]]
=== Juízes, 4
// naa ?, NAA - Nova Almeida Atualizada

[[v7-4-1]]

^<<v7-4-1,1>>^ Os filhos de Israel tornaram a fazer o que era mau aos olhos do Senhor , depois da morte de Eúde.

[[v7-4-2]]

^<<v7-4-2,2>>^ E o Senhor  os entregou nas mãos de Jabim, rei de Canaã, que governava Hazor. O comandante do seu exército era Sísera, que morava em Harosete-Hagoim.

[[v7-4-3]]

^<<v7-4-3,3>>^ Os filhos de Israel clamaram ao Senhor , porque Jabim tinha novecentos carros de ferro e, durante vinte anos, oprimia duramente os filhos de Israel.

[[v7-4-4]]

^<<v7-4-4,4>>^ Débora, profetisa, esposa de Lapidote, julgava Israel naquele tempo.

[[v7-4-5]]

^<<v7-4-5,5>>^ Ela atendia debaixo da palmeira de Débora, entre Ramá e Betel, na região montanhosa de Efraim; e os filhos de Israel vinham até ali para apresentar as suas questões.

[[v7-4-6]]

^<<v7-4-6,6>>^ Débora mandou chamar Baraque, filho de Abinoão, de Quedes de Naftali, e lhe disse: — O Senhor , Deus de Israel, deu a seguinte ordem: "Vá e reúna os seus homens no monte Tabor, escolhendo dez mil homens dos filhos de Naftali e dos filhos de Zebulom.

[[v7-4-7]]

^<<v7-4-7,7>>^ Eu farei com que Sísera, comandante do exército de Jabim, se dirija até você junto ao ribeiro de Quisom, com os seus carros de guerra e as suas tropas; e eu o entregarei nas suas mãos."

[[v7-4-8]]

^<<v7-4-8,8>>^ Então Baraque disse a Débora: — Se você for comigo, irei; mas, se você não for comigo, não irei.

[[v7-4-9]]

^<<v7-4-9,9>>^ Ela respondeu: — Certamente irei com você, mas a honra da investida que você está empreendendo não será sua, porque o Senhor  entregará Sísera nas mãos de uma mulher. E Débora foi com Baraque até Quedes.

[[v7-4-10]]

^<<v7-4-10,10>>^ Então Baraque convocou as tribos de Zebulom e Naftali em Quedes. Dez mil homens o seguiram, e Débora também foi com ele.

[[v7-4-11]]

^<<v7-4-11,11>>^ Ora, Héber, o queneu, tinha se afastado dos queneus, dos filhos de Hobabe, sogro de Moisés, e havia armado as suas tendas até o carvalho de Zaananim, que fica perto de Quedes.

[[v7-4-12]]

^<<v7-4-12,12>>^ Anunciaram a Sísera que Baraque, filho de Abinoão, tinha subido ao monte Tabor.

[[v7-4-13]]

^<<v7-4-13,13>>^ Sísera convocou todos os seus carros de guerra, novecentos carros de ferro, e todo o povo que estava com ele, de Harosete-Hagoim para o ribeiro de Quisom.

[[v7-4-14]]

^<<v7-4-14,14>>^ Então Débora disse a Baraque: — Prepare-se, porque este é o dia em que o Senhor  entregou Sísera em suas mãos. Não é verdade que o Senhor  está indo à sua frente? Então Baraque desceu do monte Tabor, e dez mil homens o seguiram.

[[v7-4-15]]

^<<v7-4-15,15>>^ E o Senhor  derrotou Sísera, todos os seus carros de guerra e todo o seu exército a fio de espada, diante de Baraque; e Sísera saltou do seu carro e fugiu a pé.

[[v7-4-16]]

^<<v7-4-16,16>>^ Mas Baraque perseguiu os carros e os exércitos até Harosete-Hagoim. Todo o exército de Sísera caiu a fio de espada, sem escapar nem sequer um.

[[v7-4-17]]

^<<v7-4-17,17>>^ Porém Sísera fugiu a pé para a tenda de Jael, mulher de Héber, o queneu, pois havia paz entre Jabim, rei de Hazor, e a casa de Héber, o queneu.

[[v7-4-18]]

^<<v7-4-18,18>>^ Jael saiu ao encontro de Sísera e lhe disse: — Entre, meu senhor, entre na minha tenda. Não tenha medo. Ele entrou na tenda de Jael, e ela pôs sobre ele uma coberta.

[[v7-4-19]]

^<<v7-4-19,19>>^ Então Sísera disse: — Por favor, me dê um pouco de água, porque estou com sede. Ela abriu um odre de leite, e deu-lhe de beber. Depois o cobriu novamente.

[[v7-4-20]]

^<<v7-4-20,20>>^ E ele lhe disse mais: — Fique na porta da tenda. Se alguém vier e perguntar se há alguém aqui, responda que não.

[[v7-4-21]]

^<<v7-4-21,21>>^ Então Jael, mulher de Héber, pegou uma estaca da tenda e, lançando mão de um martelo, foi de mansinho até perto dele e lhe cravou a estaca na têmpora, de modo que ela penetrou na terra. Ele estava exausto e dormia profundamente; e foi assim que morreu.

[[v7-4-22]]

^<<v7-4-22,22>>^ E eis que, quando Baraque estava perseguindo Sísera, Jael saiu ao encontro dele e lhe disse: — Venha, e eu lhe mostrarei o homem que você está procurando. Ele a seguiu; e eis que Sísera estava caído, morto, com a estaca fincada na têmpora.

[[v7-4-23]]

^<<v7-4-23,23>>^ Assim, naquele dia, Deus humilhou Jabim, rei de Canaã, diante dos filhos de Israel.

[[v7-4-24]]

^<<v7-4-24,24>>^ E cada vez mais a mão dos filhos de Israel prevalecia contra Jabim, rei de Canaã, até que o exterminaram.

'''

xref:007-juizes/007-juizes-003.adoc#v7-3-0[&#60; Capítulo Anterior] | <<v7-4-0,Topo>> | xref:007-juizes/007-juizes-005.adoc#v7-5-0[Próximo Capítulo &#62;]