include::./index.adoc[]

[[v7-17-0]]
=== Juízes, 17
// naa ?, NAA - Nova Almeida Atualizada

[[v7-17-1]]

^<<v7-17-1,1>>^ Havia um homem da região montanhosa de Efraim cujo nome era Mica.

[[v7-17-2]]

^<<v7-17-2,2>>^ Ele disse à sua mãe: — As mil e cem moedas de prata que lhe foram roubadas, e a respeito das quais a senhora me falou e proferiu maldições, eis que esse dinheiro está comigo; eu o peguei. Então a mãe lhe disse: — Que o Senhor  o abençoe, meu filho!

[[v7-17-3]]

^<<v7-17-3,3>>^ Assim, ele devolveu as mil e cem moedas de prata à sua mãe, que disse: — De minha parte dedico esta prata ao Senhor  Deus a favor de meu filho. Será usada para fazer uma imagem de escultura e uma de fundição. Por isso, agora eu devolvo esta prata a você.

[[v7-17-4]]

^<<v7-17-4,4>>^ Porém o filho devolveu a prata à sua mãe, que pegou duzentas moedas de prata e as deu a um ourives, o qual fez delas uma imagem de escultura e uma de fundição. E a imagem ficou na casa de Mica.

[[v7-17-5]]

^<<v7-17-5,5>>^ E, assim, este homem, Mica, veio a ter um santuário. Fez uma estola sacerdotal, alguns ídolos do lar, e consagrou um de seus filhos para ser o sacerdote.

[[v7-17-6]]

^<<v7-17-6,6>>^ Naqueles dias, não havia rei em Israel; cada um fazia o que achava mais certo.

[[v7-17-7]]

^<<v7-17-7,7>>^ Havia um jovem de Belém de Judá, da tribo de Judá, que era levita e estrangeiro naquele lugar.

[[v7-17-8]]

^<<v7-17-8,8>>^ Esse homem partiu da cidade de Belém de Judá em busca de outro lugar para morar. E assim, seguindo o seu caminho, chegou à região montanhosa de Efraim, até a casa de Mica.

[[v7-17-9]]

^<<v7-17-9,9>>^ E Mica lhe perguntou: — De onde você vem? Ele respondeu: — Sou levita de Belém de Judá e estou procurando um lugar para morar.

[[v7-17-10]]

^<<v7-17-10,10>>^ Então Mica disse: — Fique comigo, como meu conselheiro e sacerdote. Eu lhe darei dez moedas de prata por ano, a roupa e o sustento. O levita entrou

[[v7-17-11]]

^<<v7-17-11,11>>^ e consentiu em ficar com aquele homem. E o jovem era para ele como um de seus filhos.

[[v7-17-12]]

^<<v7-17-12,12>>^ Mica consagrou o jovem levita, que passou a ser o seu sacerdote. E o jovem ficou na casa de Mica.

[[v7-17-13]]

^<<v7-17-13,13>>^ Então Mica disse: — Agora sei que o Senhor  me fará bem, porque tenho um levita como sacerdote.

'''

xref:007-juizes/007-juizes-016.adoc#v7-16-0[&#60; Capítulo Anterior] | <<v7-17-0,Topo>> | xref:007-juizes/007-juizes-018.adoc#v7-18-0[Próximo Capítulo &#62;]