include::./index.adoc[]

[[v7-10-0]]
=== Juízes, 10
// naa ?, NAA - Nova Almeida Atualizada

[[v7-10-1]]

^<<v7-10-1,1>>^ Depois de Abimeleque, Tola, filho de Puá, filho de Dodô, homem de Issacar, se levantou para livrar Israel. Ele morava em Samir, na região montanhosa de Efraim.

[[v7-10-2]]

^<<v7-10-2,2>>^ Julgou Israel durante vinte e três anos. Depois morreu e foi sepultado em Samir.

[[v7-10-3]]

^<<v7-10-3,3>>^ Depois dele se levantou Jair, gileadita, que julgou Israel durante vinte e dois anos.

[[v7-10-4]]

^<<v7-10-4,4>>^ Ele tinha trinta filhos, que cavalgavam trinta jumentos. E eles tinham trinta cidades, a que chamavam Havote-Jair, até o dia de hoje, as quais estão na terra de Gileade.

[[v7-10-5]]

^<<v7-10-5,5>>^ Jair morreu e foi sepultado em Camom.

[[v7-10-6]]

^<<v7-10-6,6>>^ Os filhos de Israel tornaram a fazer o que era mau aos olhos do Senhor  e adoraram os baalins, Astarote, os deuses da Síria e os de Sidom, de Moabe, dos filhos de Amom e dos filisteus. Eles abandonaram o Senhor  e deixaram de adorá-lo.

[[v7-10-7]]

^<<v7-10-7,7>>^ Então a ira do Senhor  se acendeu contra Israel, e ele os entregou nas mãos dos filisteus e nas mãos dos filhos de Amom,

[[v7-10-8]]

^<<v7-10-8,8>>^ os quais, nesse mesmo ano, esmagaram e oprimiram os filhos de Israel. Durante dezoito anos, oprimiram todos os filhos de Israel que estavam do outro lado do Jordão, na terra dos amorreus, que está em Gileade.

[[v7-10-9]]

^<<v7-10-9,9>>^ Os filhos de Amom passaram o Jordão para lutar também contra Judá, contra Benjamim e contra a casa de Efraim, de maneira que Israel se viu muito angustiado.

[[v7-10-10]]

^<<v7-10-10,10>>^ Então os filhos de Israel clamaram ao Senhor , dizendo: — Pecamos contra ti, porque deixamos o nosso Deus e adoramos os baalins.

[[v7-10-11]]

^<<v7-10-11,11>>^ E o Senhor  respondeu aos filhos de Israel: — Quando os egípcios, os amorreus, os filhos de Amom, os filisteus,

[[v7-10-12]]

^<<v7-10-12,12>>^ os sidônios, os amalequitas e os maonitas oprimiam vocês, e vocês clamavam a mim, não é verdade que eu os livrei das mãos deles?

[[v7-10-13]]

^<<v7-10-13,13>>^ Mas vocês me abandonaram e serviram outros deuses. Por isso não os livrarei mais.

[[v7-10-14]]

^<<v7-10-14,14>>^ Vão e clamem aos deuses que vocês escolheram. Que eles os livrem no tempo do aperto.

[[v7-10-15]]

^<<v7-10-15,15>>^ Mas os filhos de Israel disseram ao Senhor : — Nós pecamos. Faze-nos tudo o que te parecer bem, mas, por favor, livra-nos ainda esta vez.

[[v7-10-16]]

^<<v7-10-16,16>>^ E tiraram os deuses estranhos do meio de si e adoraram o Senhor . E ele já não pôde reter a sua compaixão diante da desgraça de Israel.

[[v7-10-17]]

^<<v7-10-17,17>>^ Os filhos de Amom foram convocados e acamparam em Gileade. Os filhos de Israel, por sua vez, se reuniram e acamparam em Mispa.

[[v7-10-18]]

^<<v7-10-18,18>>^ Então o povo, aliás, os chefes de Gileade, disseram uns aos outros: — Quem será o homem que começará a lutar contra os filhos de Amom? Quem fizer isso será o chefe de todos os moradores de Gileade.

'''

xref:007-juizes/007-juizes-009.adoc#v7-9-0[&#60; Capítulo Anterior] | <<v7-10-0,Topo>> | xref:007-juizes/007-juizes-011.adoc#v7-11-0[Próximo Capítulo &#62;]