include::./index.adoc[]

[[v7-12-0]]
=== Juízes, 12
// naa ?, NAA - Nova Almeida Atualizada

[[v7-12-1]]

^<<v7-12-1,1>>^ Então os homens de Efraim foram convocados, passaram para Zafom e disseram a Jefté: — Por que você foi lutar contra os filhos de Amom e não nos chamou para ir com você? Por causa disso vamos queimar a sua casa com você dentro dela.

[[v7-12-2]]

^<<v7-12-2,2>>^ Mas Jefté respondeu: — Eu e o meu povo tivemos uma grande discussão com os filhos de Amom. Chamei vocês, mas vocês não me livraram das mãos deles.

[[v7-12-3]]

^<<v7-12-3,3>>^ Quando vi que vocês não iam me livrar, arrisquei a minha vida e fui lutar contra os filhos de Amom, e o Senhor  os entregou nas minhas mãos. Então por que vocês estão vindo hoje para lutar contra mim?

[[v7-12-4]]

^<<v7-12-4,4>>^ E Jefté reuniu todos os homens de Gileade e lutou contra Efraim. Os homens de Gileade derrotaram os efraimitas, porque estes tinham dito: "Vocês, gileaditas, que moram no meio de Efraim e Manassés, são desertores de Efraim."

[[v7-12-5]]

^<<v7-12-5,5>>^ Porém os gileaditas tomaram os vaus do Jordão que conduzem a Efraim. E, quando algum fugitivo de Efraim dizia: "Quero passar", os homens de Gileade lhe perguntavam: "Você é efraimita?" Se respondesse que não,

[[v7-12-6]]

^<<v7-12-6,6>>^ os homens de Gileade lhe diziam: "Então diga ‘Xibolete’." Se ele dizia "Sibolete", não podendo pronunciar corretamente a palavra, eles o agarravam e matavam nos vaus do Jordão. Assim naquele tempo foram mortos quarenta e dois mil efraimitas.

[[v7-12-7]]

^<<v7-12-7,7>>^ Jefté, o gileadita, julgou Israel durante seis anos. Ele morreu e foi sepultado numa das cidades de Gileade.

[[v7-12-8]]

^<<v7-12-8,8>>^ Depois de Jefté, quem julgou Israel foi Ibsã, que era de Belém.

[[v7-12-9]]

^<<v7-12-9,9>>^ Ele tinha trinta filhos e trinta filhas. Ibsã deu as suas filhas em casamento a homens de fora; e, de fora, trouxe trinta mulheres para os seus filhos. Ibsã julgou Israel durante sete anos.

[[v7-12-10]]

^<<v7-12-10,10>>^ Então morreu e foi sepultado em Belém.

[[v7-12-11]]

^<<v7-12-11,11>>^ Depois de Ibsã, veio Elom, o zebulonita, que julgou Israel durante dez anos.

[[v7-12-12]]

^<<v7-12-12,12>>^ Quando Elom, o zebulonita, morreu, foi sepultado em Aijalom, na terra de Zebulom.

[[v7-12-13]]

^<<v7-12-13,13>>^ Depois de Elom, quem julgou Israel foi Abdom, filho de Hilel, o piratonita.

[[v7-12-14]]

^<<v7-12-14,14>>^ Ele tinha quarenta filhos e trinta netos, que cavalgavam setenta jumentos. Abdom julgou Israel durante oito anos.

[[v7-12-15]]

^<<v7-12-15,15>>^ Então Abdom, filho de Hilel, o piratonita, morreu e foi sepultado em Piratom, na terra de Efraim, na região montanhosa dos amalequitas.

'''

xref:007-juizes/007-juizes-011.adoc#v7-11-0[&#60; Capítulo Anterior] | <<v7-12-0,Topo>> | xref:007-juizes/007-juizes-013.adoc#v7-13-0[Próximo Capítulo &#62;]