include::./index.adoc[]

[[v7-19-0]]
=== Juízes, 19
// naa ?, NAA - Nova Almeida Atualizada

[[v7-19-1]]

^<<v7-19-1,1>>^ Naqueles dias, em que não havia rei em Israel, houve um homem levita, que, peregrinando nos lados da região montanhosa de Efraim, tomou para si uma concubina de Belém de Judá.

[[v7-19-2]]

^<<v7-19-2,2>>^ Porém ela se irritou com ele e, deixando-o, voltou para a casa de seu pai, em Belém de Judá, onde ficou durante uns quatro meses.

[[v7-19-3]]

^<<v7-19-3,3>>^ Seu marido, levando consigo o seu servo e dois jumentos, foi atrás dela para tentar convencê-la a voltar. Ela o fez entrar na casa de seu pai. Este, quando viu o levita, saiu alegre a recebê-lo.

[[v7-19-4]]

^<<v7-19-4,4>>^ O sogro, o pai da moça, convenceu o levita a ficar com ele durante três dias; comeram, beberam, e o casal se alojou ali.

[[v7-19-5]]

^<<v7-19-5,5>>^ No quarto dia, madrugaram e se levantaram para partir. Mas o pai da moça disse a seu genro: — Coma alguma coisa, para você ter mais força para a viagem. Depois disso vocês podem ir embora.

[[v7-19-6]]

^<<v7-19-6,6>>^ Os dois se sentaram, comeram e beberam juntos. Então o pai da moça disse ao homem: — Por favor, fique aqui mais uma noite e alegre o seu coração.

[[v7-19-7]]

^<<v7-19-7,7>>^ Quando o homem se levantou para partir, o seu sogro insistiu para que ficasse, e ele mais uma vez pernoitou ali.

[[v7-19-8]]

^<<v7-19-8,8>>^ No quinto dia, ele se levantou de madrugada para partir, mas o pai da moça lhe disse: — Coma alguma coisa. Fiquem até o entardecer. E ambos comeram juntos.

[[v7-19-9]]

^<<v7-19-9,9>>^ Então o homem se levantou para partir, ele, a sua concubina e o seu servo. Mas o sogro dele, o pai da moça, lhe disse: — Olhe! Está ficando tarde e a noite vem chegando. Passe mais uma noite aqui. Este dia já está acabando. Passe aqui a noite, e alegre o seu coração. Amanhã de madrugada vocês podem se levantar e viajar de volta para casa.

[[v7-19-10]]

^<<v7-19-10,10>>^ Porém o homem não quis passar ali mais uma noite. Ele se levantou, partiu e chegou até a altura de Jebus, isto é, Jerusalém. Com ele iam os dois jumentos encilhados e também a sua concubina.

[[v7-19-11]]

^<<v7-19-11,11>>^ Quando chegaram perto de Jebus, o dia já estava chegando ao fim. Então o servo disse a seu senhor: — Venha, vamos sair da estrada e entrar nessa cidade dos jebuseus e passemos ali a noite.

[[v7-19-12]]

^<<v7-19-12,12>>^ Porém o seu senhor lhe disse: — Não vamos entrar em nenhuma cidade estranha, que não seja dos filhos de Israel. Vamos um pouco mais adiante até Gibeá.

[[v7-19-13]]

^<<v7-19-13,13>>^ E continuou: — Venha, vamos a um desses lugares e pernoitemos em Gibeá ou em Ramá.

[[v7-19-14]]

^<<v7-19-14,14>>^ Assim passaram adiante e continuaram a viagem. E o sol se pôs quando chegaram a Gibeá, que pertence a Benjamim.

[[v7-19-15]]

^<<v7-19-15,15>>^ Saíram da estrada para entrar em Gibeá, a fim de, nela, passarem a noite. O levita entrou e se sentou na praça da cidade, porque não houve quem os recolhesse em casa para ali pernoitarem.

[[v7-19-16]]

^<<v7-19-16,16>>^ Eis que, ao anoitecer, um homem velho estava voltando do seu trabalho no campo. Ele era da região montanhosa de Efraim, mas morava em Gibeá. Os outros habitantes do lugar eram benjamitas.

[[v7-19-17]]

^<<v7-19-17,17>>^ Quando o velho ergueu os olhos e viu o viajante na praça da cidade, perguntou: — Para onde você está indo? E de onde você vem?

[[v7-19-18]]

^<<v7-19-18,18>>^ O levita respondeu: — Estamos viajando de Belém de Judá para os lados da região montanhosa de Efraim, de onde sou. Fui a Belém de Judá e, agora, estou de viagem para a Casa do Senhor . Ninguém me recebeu em sua casa,

[[v7-19-19]]

^<<v7-19-19,19>>^ embora tenhamos palha e pasto para os nossos jumentos, e também pão e vinho para mim, e para esta sua serva, e para o moço que vem com estes seus servos. Não nos falta nada.

[[v7-19-20]]

^<<v7-19-20,20>>^ Então o velho disse: — Que a paz esteja com você! Tudo o que lhe vier a faltar fique a meu encargo. Só não passem a noite na praça.

[[v7-19-21]]

^<<v7-19-21,21>>^ Ele os levou para a sua casa e deu pasto aos jumentos. Depois de lavarem os pés, comeram e beberam.

[[v7-19-22]]

^<<v7-19-22,22>>^ Enquanto eles se alegravam, eis que os homens daquela cidade, homens malignos, cercaram a casa e começaram a bater na porta. E disseram ao velho, o dono da casa: — Traga para fora o homem que entrou em sua casa, para que abusemos dele.

[[v7-19-23]]

^<<v7-19-23,23>>^ O dono da casa saiu para falar com eles e disse: — Não, meus irmãos, não façam esta maldade. Já que o homem está em minha casa, não façam uma loucura dessas.

[[v7-19-24]]

^<<v7-19-24,24>>^ Vejam, aqui estão a minha filha virgem e a concubina dele. Vou pôr as duas para fora e vocês poderão abusar delas e fazer o que bem quiserem. Mas não façam uma loucura dessas com este homem!

[[v7-19-25]]

^<<v7-19-25,25>>^ Porém aqueles homens não o quiseram ouvir. Então o levita pegou a sua concubina e a entregou a eles do lado de fora. E eles a forçaram e abusaram dela toda a noite até pela manhã; e, quando estava amanhecendo, eles a deixaram.

[[v7-19-26]]

^<<v7-19-26,26>>^ Ao amanhecer, a mulher veio e caiu à porta da casa do homem, onde o seu senhor estava hospedado. E ela ficou ali até o clarear do dia.

[[v7-19-27]]

^<<v7-19-27,27>>^ De manhã, quando o seu senhor se levantou e abriu as portas da casa, para continuar a viagem, eis que a mulher, sua concubina, jazia à porta da casa, com as mãos sobre a soleira.

[[v7-19-28]]

^<<v7-19-28,28>>^ Ele lhe disse: — Levante-se, e vamos embora! Porém não houve resposta. Então o homem a pôs sobre o jumento e foi para a sua casa.

[[v7-19-29]]

^<<v7-19-29,29>>^ Chegando a casa, pegou uma faca e cortou o corpo da concubina em doze pedaços. E enviou os pedaços para todas as regiões da terra de Israel.

[[v7-19-30]]

^<<v7-19-30,30>>^ Todos os que viram isso diziam: — Nunca se fez uma coisa dessas, nem se viu nada semelhante desde o dia em que os filhos de Israel saíram da terra do Egito até o dia de hoje. Pensem nisso, discutam entre si e digam o que se deve fazer.

'''

xref:007-juizes/007-juizes-018.adoc#v7-18-0[&#60; Capítulo Anterior] | <<v7-19-0,Topo>> | xref:007-juizes/007-juizes-020.adoc#v7-20-0[Próximo Capítulo &#62;]