include::./index.adoc[]

[[v29-3-0]]
=== Joel, 3
// naa ?, NAA - Nova Almeida Atualizada

[[v29-3-1]]

^<<v29-3-1,1>>^ — Eis que, naqueles dias e naquele tempo, em que mudarei a sorte de Judá e de Jerusalém,

[[v29-3-2]]

^<<v29-3-2,2>>^ congregarei todas as nações e as farei descer ao vale de Josafá. E ali entrarei em juízo contra elas por causa do meu povo e da minha herança, Israel, a quem elas espalharam entre os povos, repartindo a minha terra entre si.

[[v29-3-3]]

^<<v29-3-3,3>>^ Lançaram sortes sobre o meu povo, e deram meninos em troca de prostitutas, e venderam meninas por vinho, que beberam.

[[v29-3-4]]

^<<v29-3-4,4>>^ O que vocês têm contra mim, Tiro, Sidom, e todas as regiões da Filístia? Estão querendo se vingar de mim? Se é isso que vocês querem, sem demora farei com que essa vingança caia sobre a cabeça de vocês.

[[v29-3-5]]

^<<v29-3-5,5>>^ Visto que vocês levaram a minha prata e o meu ouro, e puseram as minhas joias preciosas nos seus templos,

[[v29-3-6]]

^<<v29-3-6,6>>^ e venderam os filhos de Judá e os filhos de Jerusalém aos filhos dos gregos, para afastá-los da sua terra,

[[v29-3-7]]

^<<v29-3-7,7>>^ eis que eu os trarei desse lugar para onde vocês os venderam e farei com que a vingança caia sobre a própria cabeça de vocês.

[[v29-3-8]]

^<<v29-3-8,8>>^ Venderei os filhos e as filhas de vocês aos filhos de Judá, e estes os venderão aos sabeus, que são uma nação distante, porque o Senhor  o disse.

[[v29-3-9]]

^<<v29-3-9,9>>^ — Proclamem isto entre as nações: "Declarem guerra santa e convoquem os valentes. Que todos os homens de guerra se apresentem e se preparem.

[[v29-3-10]]

^<<v29-3-10,10>>^ Transformem as suas lâminas de arado em espadas, e as suas foices, em lanças. Que o fraco diga: ‘Eu sou forte.’"

[[v29-3-11]]

^<<v29-3-11,11>>^ "Todos vocês, povos vizinhos, apressem-se e venham depressa, e reúnam-se ali." Faze descer os teus valentes, ó Senhor !

[[v29-3-12]]

^<<v29-3-12,12>>^ "Que todas as nações se levantem e sigam para o vale de Josafá, porque ali me assentarei para julgar todas as nações vizinhas.

[[v29-3-13]]

^<<v29-3-13,13>>^ Peguem a foice e comecem a colher, porque a plantação está madura. Venham, pisem as uvas, porque o lagar está cheio, os seus compartimentos transbordam. Porque é grande a maldade dessas nações!"

[[v29-3-14]]

^<<v29-3-14,14>>^ "Multidões, multidões no vale da Decisão! Porque o Dia do Senhor está perto, no vale da Decisão.

[[v29-3-15]]

^<<v29-3-15,15>>^ O sol e a lua se escurecem, e as estrelas deixam de brilhar.

[[v29-3-16]]

^<<v29-3-16,16>>^ O Senhor  rugirá de Sião e de Jerusalém fará ouvir a sua voz. Os céus e a terra tremerão, mas o Senhor  será o refúgio do seu povo e a fortaleza dos filhos de Israel."

[[v29-3-17]]

^<<v29-3-17,17>>^ "Assim vocês saberão que eu sou o Senhor , o Deus de vocês, que habito em Sião, o meu santo monte. Jerusalém será santa; estranhos não passarão mais por ela.

[[v29-3-18]]

^<<v29-3-18,18>>^ E acontecerá que, naquele dia, os montes destilarão vinho, e as colinas manarão leite, e todos os rios de Judá estarão cheios de água. Uma fonte sairá da Casa do Senhor e regará o vale de Sitim.

[[v29-3-19]]

^<<v29-3-19,19>>^ O Egito se tornará uma desolação, e Edom se fará um deserto abandonado, por causa da violência que fizeram aos filhos de Judá, em cuja terra derramaram sangue inocente.

[[v29-3-20]]

^<<v29-3-20,20>>^ Judá, porém, será habitada para sempre, e Jerusalém, de geração em geração.

[[v29-3-21]]

^<<v29-3-21,21>>^ Eu vingarei o sangue deles, que ainda não foi vingado." E o Senhor  habitará em Sião.

'''

xref:029-joel/029-joel-002.adoc#v29-2-0[&#60; Capítulo Anterior] | <<v29-3-0,Topo>> | xref:030-amos/030-amos-001.adoc#v30-1-0[Próximo Capítulo &#62;]