include::./index.adoc[]

[[v29-2-0]]
=== Joel, 2
// naa ?, NAA - Nova Almeida Atualizada

[[v29-2-1]]

^<<v29-2-1,1>>^ Toquem a trombeta em Sião e deem o alarme no meu santo monte. Que todos os moradores da terra tremam, porque o Dia do Senhor está chegando; já está próximo.

[[v29-2-2]]

^<<v29-2-2,2>>^ É dia de trevas e escuridão, dia de nuvens e densas trevas! Como a luz do amanhecer sobre os montes, assim se difunde um povo grande e poderoso, como nunca houve igual desde os tempos antigos, nem haverá outro depois dele pelos anos seguintes, de geração em geração.

[[v29-2-3]]

^<<v29-2-3,3>>^ À frente dele vai fogo devorador, atrás dele vêm chamas destruidoras. Diante desse povo, a terra é como o jardim do Éden; mas, atrás dele, fica devastada como um deserto. Nada lhe escapa.

[[v29-2-4]]

^<<v29-2-4,4>>^ A sua aparência é como a de cavalos; e, como cavaleiros, assim correm.

[[v29-2-5]]

^<<v29-2-5,5>>^ Com um estrondo semelhante ao de carros de guerra, eles vêm saltando no alto dos montes, crepitando como chamas de fogo que devoram a palha, como um povo poderoso posto em ordem de combate.

[[v29-2-6]]

^<<v29-2-6,6>>^ Diante deles, os povos tremem; todos os rostos empalidecem.

[[v29-2-7]]

^<<v29-2-7,7>>^ Correm como valentes; como homens de guerra, sobem muros. Cada um vai no seu caminho e não se desvia da sua fileira.

[[v29-2-8]]

^<<v29-2-8,8>>^ Não empurram uns aos outros; cada um segue o seu rumo. Avançam entre as lanças e não se detêm no seu caminho.

[[v29-2-9]]

^<<v29-2-9,9>>^ Invadem a cidade, correm pelas muralhas, sobem pelas paredes das casas, entram pelas janelas como ladrões.

[[v29-2-10]]

^<<v29-2-10,10>>^ Diante deles, a terra treme e os céus se abalam; o sol e a lua se escurecem, e as estrelas deixam de brilhar.

[[v29-2-11]]

^<<v29-2-11,11>>^ O Senhor  levanta a voz diante do seu exército. Porque o seu arraial é enorme, e quem executa as suas ordens é poderoso. Sim, grande e mui terrível é o Dia do Senhor ! Quem o poderá suportar?

[[v29-2-12]]

^<<v29-2-12,12>>^ Ainda assim, agora mesmo, diz o Senhor : "Convertam-se a mim de todo o coração; com jejuns, com choro e com pranto.

[[v29-2-13]]

^<<v29-2-13,13>>^ Rasguem o coração, e não as suas roupas." Convertam-se ao Senhor , seu Deus, porque ele é bondoso e compassivo, tardio em irar-se e grande em misericórdia, e muda de ideia quanto ao mal que havia anunciado.

[[v29-2-14]]

^<<v29-2-14,14>>^ Quem sabe se ele não se voltará e mudará de ideia, e, ao passar, deixe uma bênção, para que vocês possam trazer ofertas de cereais e libações ao Senhor , seu Deus?

[[v29-2-15]]

^<<v29-2-15,15>>^ Toquem a trombeta em Sião, proclamem um santo jejum, convoquem uma reunião solene.

[[v29-2-16]]

^<<v29-2-16,16>>^ Reúnam o povo, santifiquem a congregação, congreguem os anciãos, reúnam as crianças e os que mamam no peito. Que o noivo saia do seu quarto, e a noiva, dos seus aposentos.

[[v29-2-17]]

^<<v29-2-17,17>>^ Que os sacerdotes, ministros do Senhor , chorem entre o pórtico e o altar, e orem: "Poupa o teu povo, ó Senhor , e não faças da tua herança um objeto de deboche e de zombaria entre as nações. Por que hão de dizer entre os povos: ‘Onde está o Deus deles?’"

[[v29-2-18]]

^<<v29-2-18,18>>^ Então o Senhor teve grande amor pela sua terra e se compadeceu do seu povo.

[[v29-2-19]]

^<<v29-2-19,19>>^ O Senhor  respondeu ao seu povo: "Eis que lhes envio o cereal, o vinho e o azeite, e vocês ficarão satisfeitos. Nunca mais farei de vocês motivo de zombaria entre as nações.

[[v29-2-20]]

^<<v29-2-20,20>>^ Mas o invasor que vem do Norte, eu o removerei para longe de vocês e o lançarei para uma terra seca e deserta. Lançarei a sua vanguarda para o mar oriental, e a sua retaguarda, para o mar ocidental. Subirá o seu mau cheiro, e subirá a sua podridão; porque agiu poderosamente."

[[v29-2-21]]

^<<v29-2-21,21>>^ "Não tenha medo, ó terra; alegre-se e exulte, porque o Senhor faz grandes coisas.

[[v29-2-22]]

^<<v29-2-22,22>>^ Não tenham medo, animais selvagens, porque os pastos do deserto reverdecerão, porque as árvores darão os seus frutos, as figueiras e as videiras produzirão com vigor.

[[v29-2-23]]

^<<v29-2-23,23>>^ Filhos de Sião, alegrem-se e exultem no Senhor , seu Deus, porque ele lhes dará as chuvas em justa medida; fará descer, como no passado, as primeiras e as últimas chuvas.

[[v29-2-24]]

^<<v29-2-24,24>>^ As eiras se encherão de trigo, e os lagares transbordarão de vinho e de azeite.

[[v29-2-25]]

^<<v29-2-25,25>>^ Restituirei os anos que foram consumidos pelos gafanhotos — o migrador, o devorador e o destruidor —, o meu grande exército que enviei contra vocês.

[[v29-2-26]]

^<<v29-2-26,26>>^ Vocês terão comida em abundância e ficarão satisfeitos, e louvarão o nome do Senhor , seu Deus, que fez maravilhas em favor de vocês. E nunca mais o meu povo será envergonhado.

[[v29-2-27]]

^<<v29-2-27,27>>^ Vocês saberão que eu estou no meio de Israel, e que eu sou o Senhor , o Deus de vocês, e que não há outro. E nunca mais o meu povo será envergonhado."

[[v29-2-28]]

^<<v29-2-28,28>>^ "E acontecerá, depois disso, que derramarei o meu Espírito sobre toda a humanidade. Os filhos e as filhas de vocês profetizarão, os seus velhos sonharão, e os seus jovens terão visões.

[[v29-2-29]]

^<<v29-2-29,29>>^ Até sobre os servos e sobre as servas derramarei o meu Espírito naqueles dias.

[[v29-2-30]]

^<<v29-2-30,30>>^ Mostrarei prodígios no céu e na terra: sangue, fogo e colunas de fumaça.

[[v29-2-31]]

^<<v29-2-31,31>>^ O sol se transformará em trevas, e a lua, em sangue, antes que venha o grande e terrível Dia do Senhor ."

[[v29-2-32]]

^<<v29-2-32,32>>^ E acontecerá que todo aquele que invocar o nome do Senhor  será salvo. Porque, no monte Sião e em Jerusalém, estarão os que forem salvos, como o Senhor  prometeu; e, entre os sobreviventes, aqueles que o Senhor  chamar.

'''

xref:029-joel/029-joel-001.adoc#v29-1-0[&#60; Capítulo Anterior] | <<v29-2-0,Topo>> | xref:029-joel/029-joel-003.adoc#v29-3-0[Próximo Capítulo &#62;]