include::./index.adoc[]

[[v29-1-0]]
=== Joel, 1
// naa ?, NAA - Nova Almeida Atualizada

[[v29-1-1]]

^<<v29-1-1,1>>^ Palavra do Senhor  que foi dirigida a Joel, filho de Petuel.

[[v29-1-2]]

^<<v29-1-2,2>>^ "Prestem atenção, velhos, e escutem, todos os moradores da terra! Aconteceu algo assim no tempo de vocês ou nos dias de seus pais?

[[v29-1-3]]

^<<v29-1-3,3>>^ Contem isto aos filhos de vocês; que eles o contem aos filhos deles, e que estes falem sobre isso à geração seguinte."

[[v29-1-4]]

^<<v29-1-4,4>>^ "O que o gafanhoto cortador deixou, o gafanhoto migrador comeu; o que o migrador deixou, o gafanhoto devorador comeu; o que o devorador deixou, o gafanhoto destruidor comeu."

[[v29-1-5]]

^<<v29-1-5,5>>^ "Acordem, beberrões, e chorem! Lamentem, todos vocês que gostam de vinho, por causa do vinho novo, pois foi tirado da boca de vocês.

[[v29-1-6]]

^<<v29-1-6,6>>^ Porque veio um povo contra a minha terra, poderoso e inumerável, com dentes como de leão e presas como de leoa.

[[v29-1-7]]

^<<v29-1-7,7>>^ Destruiu as minhas videiras e destroçou as minhas figueiras. Tirou as cascas das árvores e as jogou fora; os galhos ficaram brancos."

[[v29-1-8]]

^<<v29-1-8,8>>^ "Lamentem, assim como a virgem, vestida de roupa feita de pano de saco, lamenta a morte do seu noivo.

[[v29-1-9]]

^<<v29-1-9,9>>^ Na Casa do Senhor , foram cortadas as ofertas de cereais e as libações. Os sacerdotes, ministros do Senhor , estão enlutados.

[[v29-1-10]]

^<<v29-1-10,10>>^ Os campos foram arrasados, e a terra está de luto, porque o cereal foi destruído, o vinho novo acabou, o azeite está no fim."

[[v29-1-11]]

^<<v29-1-11,11>>^ "Fiquem envergonhados, lavradores; lamentem, vinhateiros, por causa do trigo e da cevada, porque a colheita foi destruída.

[[v29-1-12]]

^<<v29-1-12,12>>^ As videiras secaram, as figueiras murcharam, as romãzeiras, as palmeiras e as macieiras também. Todas as árvores do campo secaram, e já não há alegria entre os filhos dos homens."

[[v29-1-13]]

^<<v29-1-13,13>>^ "Sacerdotes, vistam roupa feita de pano de saco e pranteiem. Ministros do altar, lamentem. Ministros do meu Deus, venham e passem a noite vestidos de panos de saco. Porque no templo de seu Deus não há mais ofertas de cereais e libações.

[[v29-1-14]]

^<<v29-1-14,14>>^ Proclamem um santo jejum, convoquem uma reunião solene. Reúnam os anciãos e todos os moradores desta terra na Casa do Senhor , seu Deus, e clamem ao Senhor ."

[[v29-1-15]]

^<<v29-1-15,15>>^ "Ah! Que dia! Porque o Dia do Senhor  está perto e ele vem como destruição da parte do Todo-Poderoso."

[[v29-1-16]]

^<<v29-1-16,16>>^ Por acaso, o alimento não foi destruído diante dos nossos olhos? E, do templo do nosso Deus, não desapareceram a alegria e o regozijo?

[[v29-1-17]]

^<<v29-1-17,17>>^ As sementes secaram debaixo dos seus torrões; os celeiros foram destruídos, os armazéns, derrubados, porque o cereal se perdeu.

[[v29-1-18]]

^<<v29-1-18,18>>^ Como geme o gado! As manadas de bois estão inquietas, porque não têm pasto; também os rebanhos de ovelhas estão sofrendo.

[[v29-1-19]]

^<<v29-1-19,19>>^ A ti, ó Senhor , clamo, porque o fogo devorou as pastagens, e as chamas consumiram todas as árvores do campo.

[[v29-1-20]]

^<<v29-1-20,20>>^ Também todos os animais selvagens suspiram por ti, porque os rios secaram, e o fogo devorou as pastagens.

'''

xref:028-oseias/028-oseias-014.adoc#v28-14-0[&#60; Capítulo Anterior] | <<v29-1-0,Topo>> | xref:029-joel/029-joel-002.adoc#v29-2-0[Próximo Capítulo &#62;]