include::./index.adoc[]

[[v23-56-0]]
=== Isaías, 56
// naa ?, NAA - Nova Almeida Atualizada

[[v23-56-1]]

^<<v23-56-1,1>>^ Assim diz o Senhor : "Mantenham o direito e pratiquem a justiça, porque a minha salvação está prestes a vir, e a minha justiça está prestes a se manifestar.

[[v23-56-2]]

^<<v23-56-2,2>>^ Bem-aventurado quem faz isto, e aquele que nisto se firma, que se guarda de profanar o sábado e guarda a sua mão de cometer algum mal."

[[v23-56-3]]

^<<v23-56-3,3>>^ O estrangeiro que tiver se unido ao Senhor  não deve dizer: "O Senhor  certamente me excluirá do seu povo." E um eunuco não deve dizer: "Eis que eu sou uma árvore seca."

[[v23-56-4]]

^<<v23-56-4,4>>^ Porque assim diz o Senhor : "Aos eunucos que guardam os meus sábados, escolhem aquilo que me agrada e abraçam a minha aliança,

[[v23-56-5]]

^<<v23-56-5,5>>^ darei no meu templo e dentro das minhas muralhas um memorial e um nome melhor do que filhos e filhas; darei a cada um deles um nome eterno, que nunca se apagará.

[[v23-56-6]]

^<<v23-56-6,6>>^ Aos estrangeiros que se aproximam do Senhor , para o servir e para amar o nome do Senhor , sendo deste modo servos deles, sim, todos os que guardam o sábado, não o profanando, e abraçam a minha aliança,

[[v23-56-7]]

^<<v23-56-7,7>>^ também os levarei ao meu santo monte e lhes darei alegria na minha Casa de Oração. Os seus holocaustos e os seus sacrifícios serão aceitos no meu altar, porque a minha casa será chamada ‘Casa de Oração’ para todos os povos."

[[v23-56-8]]

^<<v23-56-8,8>>^ Assim diz o Senhor  Deus, que congrega os dispersos de Israel: "Ainda congregarei outros aos que já se acham reunidos."

[[v23-56-9]]

^<<v23-56-9,9>>^ "Vocês, todos os animais do campo, todos os animais dos bosques, venham comer.

[[v23-56-10]]

^<<v23-56-10,10>>^ Os atalaias de Israel são cegos, nada sabem. Todos são cães mudos, não podem latir. São sonhadores preguiçosos, gostam de dormir.

[[v23-56-11]]

^<<v23-56-11,11>>^ Tais cães são gulosos, nunca se fartam. São pastores que nada compreendem; todos seguem o seu próprio caminho, cada um para a sua ganância, todos sem exceção.

[[v23-56-12]]

^<<v23-56-12,12>>^ Eles dizem: ‘Venham! Vou trazer o vinho! Vamos nos encharcar de bebida forte! O dia de amanhã será como este e ainda maior e mais famoso.’"

'''

xref:023-isaias/023-isaias-055.adoc#v23-55-0[&#60; Capítulo Anterior] | <<v23-56-0,Topo>> | xref:023-isaias/023-isaias-057.adoc#v23-57-0[Próximo Capítulo &#62;]