include::./index.adoc[]

[[v23-29-0]]
=== Isaías, 29
// naa ?, NAA - Nova Almeida Atualizada

[[v23-29-1]]

^<<v23-29-1,1>>^ Ai de Ariel! Ariel, cidade onde Davi acampou! Acrescentem ano a ano, deixem que as festas completem o seu ciclo;

[[v23-29-2]]

^<<v23-29-2,2>>^ no entanto, porei Ariel em aperto, e haverá pranto e lamentação; e ela será para mim como Ariel.

[[v23-29-3]]

^<<v23-29-3,3>>^ Acamparei ao redor de você, vou cercá-la de trincheiras e levantarei rampas de ataque contra você.

[[v23-29-4]]

^<<v23-29-4,4>>^ Então, lançada por terra, do chão você falará, e do pó sairá afogada a sua fala. A sua voz subirá da terra como se fosse a de um fantasma; a sua fala será como um cochicho vindo do pó.

[[v23-29-5]]

^<<v23-29-5,5>>^ Mas a multidão dos seus inimigos será como o pó fino, e a multidão dos tiranos, como a palha que voa. E isso acontecerá de repente, num instante.

[[v23-29-6]]

^<<v23-29-6,6>>^ Do Senhor  dos Exércitos vem o castigo com trovões, com terremotos, grande estrondo, tufão de vento, tempestade e labaredas de um fogo devorador.

[[v23-29-7]]

^<<v23-29-7,7>>^ Como sonho e visão noturna será a multidão de todas as nações que lutam contra Ariel, bem como todos os que lutam contra ela e contra a sua fortaleza e a põem em aperto.

[[v23-29-8]]

^<<v23-29-8,8>>^ Será também como o faminto que sonha que está comendo, mas que, ao acordar, sente-se vazio; ou como a pessoa sedenta que sonha estar bebendo água, mas que, ao acordar, sente-se fraca e ainda com sede. Assim será toda a multidão das nações que lutam contra o monte Sião.

[[v23-29-9]]

^<<v23-29-9,9>>^ Fiquem espantados e continuem assim! Fiquem cegos e continuem sem ver! Eles estão bêbados, mas não de vinho; andam cambaleando, mas não por causa de bebida forte.

[[v23-29-10]]

^<<v23-29-10,10>>^ Porque o Senhor  derramou sobre vocês o espírito de profundo sono; ele fechou os olhos de vocês, que são os profetas, e cobriu a cabeça de vocês, que são os videntes.

[[v23-29-11]]

^<<v23-29-11,11>>^ Para vocês, toda visão já se tornou como as palavras de um livro selado. Se derem o livro a alguém que sabe ler, dizendo: "Leia isto, por favor", ele responderá: "Não posso, porque está selado."

[[v23-29-12]]

^<<v23-29-12,12>>^ E, se derem o livro a quem não sabe ler, dizendo: "Leia isto, por favor", ele responderá: "Não sei ler."

[[v23-29-13]]

^<<v23-29-13,13>>^ O Senhor disse: "Visto que este povo se aproxima de mim e com a sua boca e com os seus lábios me honra, mas o seu coração está longe de mim, e o seu temor para comigo consiste só em mandamentos ensinados por homens,

[[v23-29-14]]

^<<v23-29-14,14>>^ continuarei a fazer obra maravilhosa no meio deste povo. Sim, farei obra maravilhosa e um prodígio, de maneira que a sabedoria dos seus sábios será destruída, e o entendimento dos seus entendidos desaparecerá."

[[v23-29-15]]

^<<v23-29-15,15>>^ Ai dos que escondem profundamente o seu propósito do Senhor ! Ai dos que fazem as suas próprias obras às escuras, e dizem: "Quem nos vê? Quem sabe o que estamos fazendo?"

[[v23-29-16]]

^<<v23-29-16,16>>^ Como vocês invertem as coisas! Será que o oleiro é igual ao barro? Pode a obra dizer ao seu artífice: "Ele não me fez"? Pode a coisa feita dizer do seu oleiro: "Ele não sabe nada"?

[[v23-29-17]]

^<<v23-29-17,17>>^ Não é fato que, dentro de muito pouco tempo, o Líbano se tornará pomar, e o pomar será tido por bosque?

[[v23-29-18]]

^<<v23-29-18,18>>^ Naquele dia, os surdos ouvirão as palavras do livro, e os cegos, livres da escuridão e das trevas, as verão.

[[v23-29-19]]

^<<v23-29-19,19>>^ Os mansos voltarão a se alegrar no Senhor , e os pobres do meio do povo exultarão no Santo de Israel.

[[v23-29-20]]

^<<v23-29-20,20>>^ Pois o tirano será reduzido a nada, o zombador já não existirá, e serão eliminados todos os que buscam o mal,

[[v23-29-21]]

^<<v23-29-21,21>>^ os quais com uma palavra condenam o inocente, põem armadilhas ao que repreende no tribunal, e sem motivo negam ao justo o seu direito.

[[v23-29-22]]

^<<v23-29-22,22>>^ Portanto, a respeito da casa de Jacó, o Senhor , que remiu Abraão, diz o seguinte: "Jacó não será mais envergonhado, nem mais ficará pálido o seu rosto.

[[v23-29-23]]

^<<v23-29-23,23>>^ Pois, quando ele e os seus filhos virem a obra das minhas mãos no meio deles, santificarão o meu nome; sim, santificarão o Santo de Jacó e temerão o Deus de Israel.

[[v23-29-24]]

^<<v23-29-24,24>>^ E os desencaminhados de espírito virão a ter entendimento, e os murmuradores hão de aceitar instrução."

'''

xref:023-isaias/023-isaias-028.adoc#v23-28-0[&#60; Capítulo Anterior] | <<v23-29-0,Topo>> | xref:023-isaias/023-isaias-030.adoc#v23-30-0[Próximo Capítulo &#62;]