include::./index.adoc[]

[[v23-10-0]]
=== Isaías, 10
// naa ?, NAA - Nova Almeida Atualizada

[[v23-10-1]]

^<<v23-10-1,1>>^ Ai dos que decretam leis injustas, dos que escrevem decretos opressivos,

[[v23-10-2]]

^<<v23-10-2,2>>^ para negarem justiça aos pobres, para privarem do seu direito os aflitos do meu povo, a fim de despojarem as viúvas e roubarem os órfãos!

[[v23-10-3]]

^<<v23-10-3,3>>^ Mas o que vocês vão fazer no dia do castigo, na calamidade que vem de longe? A quem vão pedir socorro e onde deixarão a sua glória?

[[v23-10-4]]

^<<v23-10-4,4>>^ Nada mais lhes resta a fazer, a não ser curvar-se entre os prisioneiros e cair entre os mortos. Nem com tudo isto se desviou a ira de Deus, e a mão dele continua estendida.

[[v23-10-5]]

^<<v23-10-5,5>>^ "Ai da Assíria, cetro da minha ira! A vara em sua mão é o instrumento do meu furor.

[[v23-10-6]]

^<<v23-10-6,6>>^ Eu a envio contra uma nação ímpia, e contra o povo da minha indignação lhe dou ordens, para que dele roube a presa e lhe tome o despojo, e o ponha para ser pisado aos pés, como a lama das ruas.

[[v23-10-7]]

^<<v23-10-7,7>>^ Ela, porém, assim não pensa, o seu coração não entende assim; pelo contrário, em seu coração só pensa em destruir e exterminar não poucas nações.

[[v23-10-8]]

^<<v23-10-8,8>>^ Porque diz: ‘Não são meus comandantes todos eles reis?

[[v23-10-9]]

^<<v23-10-9,9>>^ Não é Calno como Carquemis? Não é Hamate como Arpade? E Samaria, como Damasco?

[[v23-10-10]]

^<<v23-10-10,10>>^ O meu poder atingiu os reinos dos ídolos, ainda que as suas imagens de escultura eram melhores do que as de Jerusalém e do que as de Samaria.

[[v23-10-11]]

^<<v23-10-11,11>>^ Será que não posso fazer com Jerusalém e os seus ídolos o mesmo que fiz com Samaria e os seus ídolos?’"

[[v23-10-12]]

^<<v23-10-12,12>>^ Por isso, quando o Senhor tiver acabado toda a sua obra no monte Sião e em Jerusalém, então castigará a arrogância do coração do rei da Assíria e o excessivo orgulho dos seus olhos.

[[v23-10-13]]

^<<v23-10-13,13>>^ Porque o rei disse: "Eu fiz isso com o poder da minha mão e com a minha sabedoria, porque sou inteligente. Removi os limites dos povos, roubei os seus tesouros, e como valente abati os que se assentavam em tronos.

[[v23-10-14]]

^<<v23-10-14,14>>^ Meti a mão nas riquezas dos povos como se mete a mão num ninho; e, como se ajuntam os ovos abandonados, assim eu ajuntei toda a terra, e não houve quem batesse as asas, ou abrisse o bico, ou desse um pio."

[[v23-10-15]]

^<<v23-10-15,15>>^ Será que o machado pode se gloriar contra aquele que corta com ele? Ou será que a serra pode se engrandecer contra o que a maneja? Seria como se o cetro movesse quem o segura ou o bastão levantasse quem não é madeira!

[[v23-10-16]]

^<<v23-10-16,16>>^ Por isso, o Senhor, o Senhor dos Exércitos, fará definhar os soldados deles, todos robustos, e debaixo da sua glória acenderá uma chama, como a chama de fogo.

[[v23-10-17]]

^<<v23-10-17,17>>^ Porque a Luz de Israel virá a ser como fogo, e o seu Santo, como labareda, que, num só dia, queimará e consumirá as ervas daninhas e os espinheiros da Assíria.

[[v23-10-18]]

^<<v23-10-18,18>>^ Também destruirá totalmente a glória da sua floresta e do seu campo fértil; e será como quando um doente vai definhando.

[[v23-10-19]]

^<<v23-10-19,19>>^ As árvores que restarem na sua floresta serão tão poucas, que até uma criança poderá contá-las.

[[v23-10-20]]

^<<v23-10-20,20>>^ Naquele dia, os restantes de Israel e os da casa de Jacó que tiverem escapado nunca mais se apoiarão naquele que os feriu, mas se apoiarão no Senhor , o Santo de Israel.

[[v23-10-21]]

^<<v23-10-21,21>>^ Um resto voltará; sim, um resto de Jacó voltará para o Deus Forte.

[[v23-10-22]]

^<<v23-10-22,22>>^ Porque ainda que o seu povo, ó Israel, seja como a areia do mar, apenas um resto voltará. Uma destruição está determinada, transbordante de justiça.

[[v23-10-23]]

^<<v23-10-23,23>>^ Porque essa destruição, já determinada, o Senhor, o Senhor  dos Exércitos, a executará no meio de toda esta terra.

[[v23-10-24]]

^<<v23-10-24,24>>^ Por isso, assim diz o Senhor, o Senhor  dos Exércitos: — Povo meu, que mora em Sião, não tenha medo da Assíria, quando ela castigar você com uma vara e levantar contra você o seu bastão à maneira dos egípcios.

[[v23-10-25]]

^<<v23-10-25,25>>^ Pois daqui a bem pouco se cumprirá a minha indignação e a minha ira, para a consumir.

[[v23-10-26]]

^<<v23-10-26,26>>^ Porque o Senhor  dos Exércitos suscitará contra ela um flagelo, como a matança de Midiã junto ao rochedo de Orebe. O seu bordão estará sobre o mar, e ele o levantará como fez no Egito.

[[v23-10-27]]

^<<v23-10-27,27>>^ Naquele dia, o peso deles será tirado dos ombros de vocês, e o jugo deles será removido do pescoço de vocês, jugo que será despedaçado por causa da gordura.

[[v23-10-28]]

^<<v23-10-28,28>>^ A Assíria vem a Aiate, passa por Migrom e em Micmás larga a sua bagagem.

[[v23-10-29]]

^<<v23-10-29,29>>^ Passa o desfiladeiro, aloja-se em Geba, já Ramá treme, Gibeá de Saul foge.

[[v23-10-30]]

^<<v23-10-30,30>>^ Grite bem alto, ó filha de Galim! Escute, ó Laís! Pobre Anatote!

[[v23-10-31]]

^<<v23-10-31,31>>^ Madmena se dispersa; os moradores de Gebim fogem para salvar-se.

[[v23-10-32]]

^<<v23-10-32,32>>^ Nesse mesmo dia, a Assíria parará em Nobe; agitará o punho fechado para o monte da filha de Sião, a colina de Jerusalém.

[[v23-10-33]]

^<<v23-10-33,33>>^ Mas eis que o Senhor, o Senhor  dos Exércitos, cortará os ramos com violência; as árvores de grande porte serão derrubadas, e as mais altas serão abatidas.

[[v23-10-34]]

^<<v23-10-34,34>>^ Cortará com o machado as árvores da floresta, e o Líbano cairá pela mão de um poderoso.

'''

xref:023-isaias/023-isaias-009.adoc#v23-9-0[&#60; Capítulo Anterior] | <<v23-10-0,Topo>> | xref:023-isaias/023-isaias-011.adoc#v23-11-0[Próximo Capítulo &#62;]