include::./index.adoc[]

[[v23-26-0]]
=== Isaías, 26
// naa ?, NAA - Nova Almeida Atualizada

[[v23-26-1]]

^<<v23-26-1,1>>^ Naquele dia, se entoará este cântico na terra de Judá: Temos uma cidade forte, na qual Deus põe a salvação como muralha e defesa.

[[v23-26-2]]

^<<v23-26-2,2>>^ Abram os portões, para que entre a nação justa, que guarda a fidelidade.

[[v23-26-3]]

^<<v23-26-3,3>>^ Tu, Senhor , conservarás em perfeita paz aquele cujo propósito é firme, porque ele confia em ti.

[[v23-26-4]]

^<<v23-26-4,4>>^ Confiem sempre no Senhor , porque o Senhor  Deus é uma rocha eterna.

[[v23-26-5]]

^<<v23-26-5,5>>^ Ele derruba os que habitam no alto, na cidade elevada; derruba e humilha até o chão, até o pó.

[[v23-26-6]]

^<<v23-26-6,6>>^ O pé a pisará; os pés dos aflitos, e os passos dos pobres.

[[v23-26-7]]

^<<v23-26-7,7>>^ A vereda do justo é plana; tu, que és justo, aplanas a vereda do justo.

[[v23-26-8]]

^<<v23-26-8,8>>^ Também através dos teus juízos, Senhor , te esperamos; no teu nome e na tua memória está o desejo da nossa alma.

[[v23-26-9]]

^<<v23-26-9,9>>^ Com minha alma suspiro de noite por ti e, com o meu espírito dentro de mim, eu te busco ansiosamente. Porque, quando os teus juízos reinam na terra, os moradores do mundo aprendem a justiça.

[[v23-26-10]]

^<<v23-26-10,10>>^ Ainda que se mostre favor ao ímpio, nem por isso ele aprende a justiça; até na terra da retidão ele comete a iniquidade e não vê a majestade do Senhor .

[[v23-26-11]]

^<<v23-26-11,11>>^ Senhor , a tua mão está levantada, mas eles não a veem! Porém eles verão o teu zelo pelo povo e ficarão envergonhados. Que o teu furor, por causa dos teus adversários, os consuma.

[[v23-26-12]]

^<<v23-26-12,12>>^ Senhor , concede-nos a paz, porque todas as nossas obras tu as fazes por nós.

[[v23-26-13]]

^<<v23-26-13,13>>^ Ó Senhor , nosso Deus, outros senhores têm tido domínio sobre nós, mas nós louvamos unicamente o teu nome.

[[v23-26-14]]

^<<v23-26-14,14>>^ Eles estão mortos, não voltarão a viver; são apenas sombras, não ressuscitarão. Porque tu os castigaste e destruíste, e apagaste completamente a lembrança deles.

[[v23-26-15]]

^<<v23-26-15,15>>^ Tu, Senhor , aumentaste o povo, aumentaste o povo e tens sido glorificado; alargaste todas as fronteiras do país.

[[v23-26-16]]

^<<v23-26-16,16>>^ Senhor , na angústia te buscaram; vindo sobre eles a tua correção, derramaram as suas orações.

[[v23-26-17]]

^<<v23-26-17,17>>^ Como a mulher grávida que vai dar à luz se contorce e grita de dor, assim estávamos nós na tua presença, ó Senhor !

[[v23-26-18]]

^<<v23-26-18,18>>^ Concebemos e nos contorcemos em dores de parto, mas o que demos à luz foi vento; não trouxemos à terra livramento algum, e não nasceram moradores do mundo.

[[v23-26-19]]

^<<v23-26-19,19>>^ Os teus mortos e também o meu cadáver viverão e ressuscitarão. Despertem e cantem de alegria, vocês que habitam no pó, porque o teu orvalho, ó Deus, será como o orvalho de vida, e a terra dará à luz os seus mortos.

[[v23-26-20]]

^<<v23-26-20,20>>^ Meu povo, entrem nos seus quartos e tranquem as portas; escondam-se por um momento, até que passe a ira.

[[v23-26-21]]

^<<v23-26-21,21>>^ Pois eis que o Senhor sai do seu lugar, para castigar a iniquidade dos moradores da terra. A terra deixará aparecer o sangue que embebeu e não encobrirá mais aqueles que foram mortos.

'''

xref:023-isaias/023-isaias-025.adoc#v23-25-0[&#60; Capítulo Anterior] | <<v23-26-0,Topo>> | xref:023-isaias/023-isaias-027.adoc#v23-27-0[Próximo Capítulo &#62;]