include::./index.adoc[]

[[v23-59-0]]
=== Isaías, 59
// naa ?, NAA - Nova Almeida Atualizada

[[v23-59-1]]

^<<v23-59-1,1>>^ Eis que a mão do Senhor não está encolhida, para que não possa salvar; e o seu ouvido não está surdo, para não poder ouvir.

[[v23-59-2]]

^<<v23-59-2,2>>^ Mas as iniquidades de vocês fazem separação entre vocês e o seu Deus; e os pecados que vocês cometem o levam a esconder o seu rosto de vocês, para não ouvir os seus pedidos.

[[v23-59-3]]

^<<v23-59-3,3>>^ Porque as mãos de vocês estão manchadas de sangue, e os seus dedos, de iniquidade; os lábios de vocês falam mentiras, e a sua língua profere maldade.

[[v23-59-4]]

^<<v23-59-4,4>>^ Não há ninguém que clame pela justiça, ninguém que compareça em juízo pela verdade; confiam no que é nulo e andam falando mentiras; concebem o mal e dão à luz a iniquidade.

[[v23-59-5]]

^<<v23-59-5,5>>^ Chocam ovos de cobra e tecem teias de aranha; quem comer os ovos morrerá, e, se um dos ovos é quebrado, sai uma víbora.

[[v23-59-6]]

^<<v23-59-6,6>>^ As suas teias não servem para fazer roupa, ninguém pode se cobrir com o que eles fazem. As obras deles são obras de iniquidade, e atos de violência estão nas suas mãos.

[[v23-59-7]]

^<<v23-59-7,7>>^ Os pés deles correm para o mal, são velozes para derramar sangue inocente. Os pensamentos deles são pensamentos de iniquidade; nos seus caminhos há ruína e destruição.

[[v23-59-8]]

^<<v23-59-8,8>>^ Não conhecem o caminho da paz, nem há justiça nos seus passos. Fizeram para si veredas tortuosas; quem anda por elas não conhece a paz.

[[v23-59-9]]

^<<v23-59-9,9>>^ Por isso, o juízo está longe de nós, e a justiça não nos alcança. Esperamos pela luz, e eis que há só trevas; esperamos pela claridade, mas andamos na escuridão.

[[v23-59-10]]

^<<v23-59-10,10>>^ Apalpamos as paredes como cegos, sim, como os que não têm olhos, andamos apalpando; tropeçamos ao meio-dia como nas trevas e entre os robustos somos como os mortos.

[[v23-59-11]]

^<<v23-59-11,11>>^ Todos nós bramamos como ursos e gememos como pombas; esperamos o juízo, mas ele não aparece; esperamos a salvação, mas ela está longe de nós.

[[v23-59-12]]

^<<v23-59-12,12>>^ Porque as nossas transgressões se multiplicam diante de ti, e os nossos pecados testificam contra nós. As nossas transgressões estão conosco, e conhecemos as nossas iniquidades.

[[v23-59-13]]

^<<v23-59-13,13>>^ Temos sido infiéis e mentimos contra o Senhor ; nós nos afastamos do nosso Deus; pregamos a opressão e a rebeldia; proferimos palavras de falsidade que concebemos em nosso coração.

[[v23-59-14]]

^<<v23-59-14,14>>^ Por isso, o direito se retirou, e a justiça se pôs de longe, porque a verdade anda tropeçando pelas praças, e a retidão não pode entrar.

[[v23-59-15]]

^<<v23-59-15,15>>^ Sim, a verdade sumiu, e quem se desvia do mal é tratado como presa. O Senhor  viu isso e desaprovou o fato de não haver justiça.

[[v23-59-16]]

^<<v23-59-16,16>>^ Viu que não havia ninguém e maravilhou-se de que não houvesse um intercessor; por isso, o seu próprio braço lhe trouxe a salvação, e a sua própria justiça foi o seu apoio.

[[v23-59-17]]

^<<v23-59-17,17>>^ Vestiu-se de justiça, como de uma couraça, e pôs o capacete da salvação na cabeça; pôs sobre si a veste da vingança e se cobriu de zelo, como de um manto.

[[v23-59-18]]

^<<v23-59-18,18>>^ Segundo as obras deles, assim retribuirá: aos seus adversários, furor; aos seus inimigos, o que merecem; às terras do mar, a devida recompensa.

[[v23-59-19]]

^<<v23-59-19,19>>^ Assim, temerão o nome do Senhor desde o poente, e a sua glória, desde o nascente do sol; pois virá como torrente impetuosa, impelida pelo Espírito do Senhor .

[[v23-59-20]]

^<<v23-59-20,20>>^ "O Redentor virá a Sião e aos de Jacó que se converterem", diz o Senhor .

[[v23-59-21]]

^<<v23-59-21,21>>^ — Quanto a mim, esta é a minha aliança com eles, diz o Senhor : o meu Espírito, que está sobre você, e as minhas palavras, que pus na sua boca, não se desviarão dela, nem da boca de seus filhos, nem da boca dos filhos de seus filhos, desde agora e para todo o sempre, diz o Senhor .

'''

xref:023-isaias/023-isaias-058.adoc#v23-58-0[&#60; Capítulo Anterior] | <<v23-59-0,Topo>> | xref:023-isaias/023-isaias-060.adoc#v23-60-0[Próximo Capítulo &#62;]