include::./index.adoc[]

[[v23-43-0]]
=== Isaías, 43
// naa ?, NAA - Nova Almeida Atualizada

[[v23-43-1]]

^<<v23-43-1,1>>^ Mas agora, assim diz o Senhor , que o criou, ó Jacó, e que o formou, ó Israel: "Não tenha medo, porque eu o remi; eu o chamei pelo seu nome; você é meu.

[[v23-43-2]]

^<<v23-43-2,2>>^ Quando você passar pelas águas, eu estarei com você; quando passar pelos rios, eles não o submergirão; quando passar pelo fogo, você não se queimará; as chamas não o atingirão.

[[v23-43-3]]

^<<v23-43-3,3>>^ Porque eu sou o Senhor , seu Deus, o Santo de Israel, o seu Salvador; dei o Egito em resgate por você, e a Etiópia e Sebá para que você fosse meu.

[[v23-43-4]]

^<<v23-43-4,4>>^ Visto que você é precioso aos meus olhos e digno de honra, e porque eu o amo, darei homens por você e povos em troca de sua vida.

[[v23-43-5]]

^<<v23-43-5,5>>^ Não tenha medo, porque eu estarei com você." "Trarei a sua descendência desde o Oriente e a ajuntarei desde o Ocidente.

[[v23-43-6]]

^<<v23-43-6,6>>^ Direi ao Norte: ‘Entregue!’ E ao Sul: ‘Não os impeça de sair!’ Tragam os meus filhos de longe e as minhas filhas dos confins da terra,

[[v23-43-7]]

^<<v23-43-7,7>>^ todos os que são chamados pelo meu nome, e os que criei para minha glória, sim, aqueles que formei e fiz."

[[v23-43-8]]

^<<v23-43-8,8>>^ "Traga o povo que é cego, ainda que tenha olhos, e que é surdo, ainda que tenha ouvidos.

[[v23-43-9]]

^<<v23-43-9,9>>^ Todas as nações se congreguem, e os povos se reúnam. Quem dentre eles pode anunciar isto e mostrar-nos as predições antigas? Que apresentem as suas testemunhas, para que se justifiquem, e para que se ouça e se diga: ‘É verdade!’"

[[v23-43-10]]

^<<v23-43-10,10>>^ "Vocês são as minhas testemunhas", diz o Senhor . "Vocês são o meu servo a quem escolhi, para que vocês saibam, creiam em mim e entendam que eu sou, e que antes de mim deus nenhum se formou, e depois de mim nenhum haverá.

[[v23-43-11]]

^<<v23-43-11,11>>^ Eu, eu sou o Senhor , e fora de mim não há salvador.

[[v23-43-12]]

^<<v23-43-12,12>>^ Eu anunciei salvação, eu a realizei e a fiz ouvir; deus estranho não houve entre vocês, pois vocês são as minhas testemunhas", diz o Senhor . "Eu sou Deus.

[[v23-43-13]]

^<<v23-43-13,13>>^ Ainda antes que houvesse dia, eu sou; e não há quem possa livrar alguém das minhas mãos; agindo eu, quem o impedirá?"

[[v23-43-14]]

^<<v23-43-14,14>>^ Assim diz o Senhor , o seu Redentor, o Santo de Israel: "Por causa de vocês, enviarei inimigos contra a Babilônia e a todos os babilônios farei embarcar como fugitivos nos navios de que se orgulhavam.

[[v23-43-15]]

^<<v23-43-15,15>>^ Eu sou o Senhor , o Santo Deus de vocês, o Criador de Israel e o seu Rei."

[[v23-43-16]]

^<<v23-43-16,16>>^ Assim diz o Senhor , que preparou um caminho no mar e uma vereda nas águas impetuosas;

[[v23-43-17]]

^<<v23-43-17,17>>^ que fez sair os carros de guerra e os cavalos, o exército e a força, e eles jazem ali e jamais se levantarão; estão extintos, apagados como um pavio.

[[v23-43-18]]

^<<v23-43-18,18>>^ "Não fiquem lembrando das coisas passadas, nem pensem nas coisas antigas.

[[v23-43-19]]

^<<v23-43-19,19>>^ Eis que faço uma coisa nova. Agora mesmo ela está saindo à luz. Será que vocês não o percebem? Eis que porei um caminho no deserto e rios nos lugares áridos.

[[v23-43-20]]

^<<v23-43-20,20>>^ Os animais do campo me glorificarão, os chacais e os filhotes de avestruzes, porque porei águas no deserto e rios nos lugares áridos, para dar de beber ao meu povo, ao meu escolhido,

[[v23-43-21]]

^<<v23-43-21,21>>^ a este povo que formei para mim, para celebrar o meu louvor."

[[v23-43-22]]

^<<v23-43-22,22>>^ "Contudo, você não me invocou, ó Jacó; e você se cansou de mim, ó Israel.

[[v23-43-23]]

^<<v23-43-23,23>>^ Você não me trouxe as ovelhas para os holocaustos, nem me honrou com os seus sacrifícios. Não lhe dei trabalho com ofertas de cereais, nem o cansei, pedindo incenso.

[[v23-43-24]]

^<<v23-43-24,24>>^ Você não me comprou cana aromática, nem me satisfez com a gordura dos seus sacrifícios. Mas você me deu trabalho com os seus pecados e me cansou com as suas iniquidades."

[[v23-43-25]]

^<<v23-43-25,25>>^ "Eu, eu mesmo, sou o que apago as suas transgressões por amor de mim; dos pecados que você cometeu não me lembro.

[[v23-43-26]]

^<<v23-43-26,26>>^ Relembre-me o que aconteceu! Vamos juntos ao tribunal! Apresente as suas razões, para que você possa se justificar.

[[v23-43-27]]

^<<v23-43-27,27>>^ O seu primeiro pai pecou, e os seus guias se revoltaram contra mim.

[[v23-43-28]]

^<<v23-43-28,28>>^ Por isso, profanarei os líderes do santuário, e entregarei Jacó à destruição e Israel, à zombaria."

'''

xref:023-isaias/023-isaias-042.adoc#v23-42-0[&#60; Capítulo Anterior] | <<v23-43-0,Topo>> | xref:023-isaias/023-isaias-044.adoc#v23-44-0[Próximo Capítulo &#62;]