include::./index.adoc[]

[[v23-34-0]]
=== Isaías, 34
// naa ?, NAA - Nova Almeida Atualizada

[[v23-34-1]]

^<<v23-34-1,1>>^ Aproximem-se, ó nações, para ouvir, e vocês, povos, escutem! Que a terra e a sua plenitude ouçam; que o mundo e tudo o que ele produz escutem.

[[v23-34-2]]

^<<v23-34-2,2>>^ Porque a indignação do Senhor está contra todas as nações, e o seu furor está contra todo o exército delas; ele as destinou para a destruição e as entregou à matança.

[[v23-34-3]]

^<<v23-34-3,3>>^ Os mortos deles serão lançados fora, e dos seus cadáveres subirá o mau cheiro; os montes se inundarão do sangue deles.

[[v23-34-4]]

^<<v23-34-4,4>>^ Todo o exército dos céus se dissolverá, e os céus se enrolarão como um pergaminho; todo o exército dos céus cairá, como cai a folha da videira e a folha da figueira.

[[v23-34-5]]

^<<v23-34-5,5>>^ Porque a minha espada se embriagou nos céus; eis que, para exercer juízo, ela desce sobre Edom e sobre o povo que destinei para a destruição.

[[v23-34-6]]

^<<v23-34-6,6>>^ A espada do Senhor está cheia de sangue, engrossada da gordura e do sangue de cordeiros e de bodes, da gordura dos rins de carneiros. Porque o Senhor  fará um sacrifício em Bozra e grande matança na terra de Edom.

[[v23-34-7]]

^<<v23-34-7,7>>^ Os bois selvagens cairão com eles, e os novilhos, com os touros. A terra deles ficará embriagada de sangue, e o pó ficará encharcado de gordura.

[[v23-34-8]]

^<<v23-34-8,8>>^ Porque esse será o dia da vingança do Senhor , o ano de retribuições pela causa de Sião.

[[v23-34-9]]

^<<v23-34-9,9>>^ Os ribeiros de Edom se transformarão em piche, e o seu pó, em enxofre; a sua terra se tornará em piche ardente.

[[v23-34-10]]

^<<v23-34-10,10>>^ O fogo não se apagará nem de noite nem de dia, e a sua fumaça subirá para sempre. De geração em geração ficará abandonada, e para todo o sempre ninguém passará por ela.

[[v23-34-11]]

^<<v23-34-11,11>>^ O pelicano e o ouriço tomarão posse do lugar; a coruja e o corvo habitarão nessa terra. O Senhor  estenderá sobre Edom o cordel de destruição e o prumo de ruína.

[[v23-34-12]]

^<<v23-34-12,12>>^ Já não haverá nobres para proclamarem um rei; os seus príncipes já não existem.

[[v23-34-13]]

^<<v23-34-13,13>>^ Nos seus palácios, crescerão espinhos, e as urtigas e os cardos tomarão conta das suas fortalezas. Edom será uma habitação de chacais e morada de avestruzes.

[[v23-34-14]]

^<<v23-34-14,14>>^ Os animais do deserto se encontrarão com as hienas, e os bodes selvagens clamarão uns aos outros; animais noturnos ali pousarão e acharão para si lugar de repouso.

[[v23-34-15]]

^<<v23-34-15,15>>^ Ali a coruja fará o seu ninho, porá os seus ovos e os chocará; e na sua sombra abrigará os seus filhotes. Também ali os abutres se ajuntarão, cada um com o seu par.

[[v23-34-16]]

^<<v23-34-16,16>>^ Procurem no livro do Senhor e leiam: Nenhuma dessas criaturas faltará, e nenhuma estará sem o seu par. Porque a boca do Senhor o ordenou, e o seu Espírito mesmo as ajuntará.

[[v23-34-17]]

^<<v23-34-17,17>>^ Porque ele lançou as sortes a favor delas, e a sua mão lhes repartiu a terra com o cordel; para sempre a possuirão, através das gerações habitarão nela.

'''

xref:023-isaias/023-isaias-033.adoc#v23-33-0[&#60; Capítulo Anterior] | <<v23-34-0,Topo>> | xref:023-isaias/023-isaias-035.adoc#v23-35-0[Próximo Capítulo &#62;]