include::./index.adoc[]

[[v23-19-0]]
=== Isaías, 19
// naa ?, NAA - Nova Almeida Atualizada

[[v23-19-1]]

^<<v23-19-1,1>>^ Sentença contra o Egito. Eis que o Senhor , cavalgando uma nuvem ligeira, vai indo para o Egito. Os ídolos do Egito estremecerão diante dele, e o coração dos egípcios se derreterá dentro deles.

[[v23-19-2]]

^<<v23-19-2,2>>^ "Porque farei com que egípcios se levantem contra egípcios, e cada um lutará contra o seu irmão e cada um contra o seu próximo; cidade contra cidade, reino contra reino.

[[v23-19-3]]

^<<v23-19-3,3>>^ O espírito dos egípcios irá esmorecer dentro deles, e eu farei com que os planos deles fracassem. Eles consultarão os seus ídolos, encantadores, médiuns e feiticeiros.

[[v23-19-4]]

^<<v23-19-4,4>>^ Entregarei os egípcios nas mãos de um senhor cruel, e um rei feroz os dominará", diz o Senhor, o Senhor  dos Exércitos.

[[v23-19-5]]

^<<v23-19-5,5>>^ As águas do mar baixarão, e o rio Nilo se tornará seco e árido.

[[v23-19-6]]

^<<v23-19-6,6>>^ Os canais exalarão mau cheiro, e os braços do Nilo diminuirão até secar; as canas e os juncos murcharão.

[[v23-19-7]]

^<<v23-19-7,7>>^ A relva que está junto ao Nilo, junto às suas margens, e tudo o que foi semeado junto dele secarão, serão levados pelo vento e desaparecerão.

[[v23-19-8]]

^<<v23-19-8,8>>^ Os pescadores gemerão, e lamentarão todos os que lançam anzóis no rio; e os que estendem redes sobre as águas desfalecerão.

[[v23-19-9]]

^<<v23-19-9,9>>^ Os que trabalham em linho fino e os que tecem pano de algodão ficarão decepcionados.

[[v23-19-10]]

^<<v23-19-10,10>>^ Os seus homens importantes serão esmagados, e todos os que trabalham por salário andarão de alma entristecida.

[[v23-19-11]]

^<<v23-19-11,11>>^ Na verdade, os príncipes de Zoã não têm juízo; os sábios conselheiros de Faraó dão conselhos estúpidos. Como vocês podem dizer ao Faraó: "Sou filho de sábios, filho de antigos reis?"

[[v23-19-12]]

^<<v23-19-12,12>>^ Onde estão agora os seus sábios? Que eles agora lhe anunciem ou informem o que o Senhor  dos Exércitos determinou contra o Egito.

[[v23-19-13]]

^<<v23-19-13,13>>^ Os príncipes de Zoã perderam o juízo, e os príncipes de Mênfis estão enganados; os que são a pedra de esquina das suas tribos estão levando o Egito a andar errante.

[[v23-19-14]]

^<<v23-19-14,14>>^ O Senhor  derramou no coração deles um espírito de confusão; eles fizeram o Egito andar errante em toda a sua obra, como o bêbado quando escorrega no seu próprio vômito.

[[v23-19-15]]

^<<v23-19-15,15>>^ Para o Egito, não há obra alguma que possa ser feita pela cabeça ou cauda, pela palma ou junco.

[[v23-19-16]]

^<<v23-19-16,16>>^ Naquele dia, os egípcios serão como mulheres: ficarão tremendo de medo quando se levantar a mão do Senhor  dos Exércitos, que ele agitará contra eles.

[[v23-19-17]]

^<<v23-19-17,17>>^ A terra de Judá será um espanto para o Egito; todo aquele que dela se lembrar ficará apavorado por causa da decisão que o Senhor  dos Exércitos tomou contra eles.

[[v23-19-18]]

^<<v23-19-18,18>>^ Naquele dia, haverá cinco cidades na terra do Egito que falarão a língua de Canaã e farão juramento ao Senhor  dos Exércitos; uma delas se chamará Cidade do Sol.

[[v23-19-19]]

^<<v23-19-19,19>>^ Naquele dia, o Senhor  terá um altar no meio da terra do Egito, e na fronteira do país será levantada uma coluna em honra do Senhor .

[[v23-19-20]]

^<<v23-19-20,20>>^ Servirá de sinal e de testemunho ao Senhor  dos Exércitos na terra do Egito. Quando eles clamarem ao Senhor  por causa dos opressores, ele lhes enviará um salvador e defensor que os há de livrar.

[[v23-19-21]]

^<<v23-19-21,21>>^ O Senhor  se dará a conhecer ao Egito, e os egípcios conhecerão o Senhor  naquele dia. Eles o adorarão com sacrifícios e ofertas de cereais, e farão votos ao Senhor , e os cumprirão.

[[v23-19-22]]

^<<v23-19-22,22>>^ O Senhor  ferirá os egípcios; ele os ferirá, mas depois os curará. Eles se converterão ao Senhor , e ele lhes atenderá as orações e os curará.

[[v23-19-23]]

^<<v23-19-23,23>>^ Naquele dia, haverá uma estrada do Egito até a Assíria. Os assírios irão ao Egito, e os egípcios irão à Assíria; e os egípcios adorarão com os assírios.

[[v23-19-24]]

^<<v23-19-24,24>>^ Naquele dia, Israel será o terceiro com os egípcios e os assírios, uma bênção no meio da terra.

[[v23-19-25]]

^<<v23-19-25,25>>^ O Senhor  dos Exércitos os abençoará, dizendo: "Bendito seja o Egito, meu povo! Bendita seja a Assíria, obra de minhas mãos. E bendito seja Israel, minha herança."

'''

xref:023-isaias/023-isaias-018.adoc#v23-18-0[&#60; Capítulo Anterior] | <<v23-19-0,Topo>> | xref:023-isaias/023-isaias-020.adoc#v23-20-0[Próximo Capítulo &#62;]