include::./index.adoc[]

[[v23-1-0]]
=== Isaías, 1
// naa ?, NAA - Nova Almeida Atualizada

[[v23-1-1]]

^<<v23-1-1,1>>^ Visão que Isaías, filho de Amoz, teve a respeito de Judá e Jerusalém, nos dias de Uzias, Jotão, Acaz e Ezequias, reis de Judá.

[[v23-1-2]]

^<<v23-1-2,2>>^ Escutem, ó céus, e ouça, ó terra, porque o Senhor  é quem fala: "Criei filhos e os fiz crescer, mas eles se revoltaram contra mim.

[[v23-1-3]]

^<<v23-1-3,3>>^ O boi conhece o seu dono, e o jumento, o lugar onde lhe dão comida, mas Israel não tem conhecimento, o meu povo não entende."

[[v23-1-4]]

^<<v23-1-4,4>>^ Ai desta nação pecadora, deste povo carregado de iniquidade! São descendência de malfeitores, filhos que praticam o mal. Rejeitaram o Senhor , desprezaram o Santo de Israel, voltaram para trás.

[[v23-1-5]]

^<<v23-1-5,5>>^ Por que vocês insistem em ser castigados? Por que continuam em rebeldia? Toda a cabeça está doente, e todo o coração está enfermo.

[[v23-1-6]]

^<<v23-1-6,6>>^ Desde a planta do pé até o alto da cabeça não há nada são, a não ser feridas, contusões e chagas abertas, umas e outras que não foram limpas, nem atadas, nem tratadas com azeite.

[[v23-1-7]]

^<<v23-1-7,7>>^ A terra de vocês está devastada, as cidades foram consumidas pelo fogo. Quanto às lavouras, os estrangeiros as devoraram na presença de vocês, e a terra se acha devastada como numa destruição feita por estrangeiros.

[[v23-1-8]]

^<<v23-1-8,8>>^ A filha de Sião foi deixada como cabana na vinha, como choupana no pepinal, como cidade sitiada.

[[v23-1-9]]

^<<v23-1-9,9>>^ Se o Senhor  dos Exércitos não nos tivesse deixado alguns sobreviventes, já nos teríamos tornado como Sodoma e semelhantes a Gomorra.

[[v23-1-10]]

^<<v23-1-10,10>>^ Príncipes de Sodoma, escutem a palavra do Senhor ! Povo de Gomorra, dê ouvidos à lei do nosso Deus!

[[v23-1-11]]

^<<v23-1-11,11>>^ O Senhor  diz: "De que me serve a multidão dos sacrifícios que vocês oferecem? Estou farto dos holocaustos de carneiros e da gordura de animais cevados. Não me agrado do sangue de novilhos, nem de cordeiros, nem de bodes.

[[v23-1-12]]

^<<v23-1-12,12>>^ Quando comparecem diante de mim, quem requereu de vocês esse pisotear dos meus átrios?

[[v23-1-13]]

^<<v23-1-13,13>>^ Não me tragam mais ofertas vãs! O incenso é para mim abominação, e também as Festas da Lua Nova, os sábados e a convocação das assembleias. Não posso suportar iniquidade associada à reunião solene.

[[v23-1-14]]

^<<v23-1-14,14>>^ As Festas da Lua Nova e as solenidades, a minha alma as odeia; já são um peso para mim; estou cansado de suportá-las."

[[v23-1-15]]

^<<v23-1-15,15>>^ "Quando vocês estendem as mãos, eu fecho os meus olhos; sim, quando multiplicam as suas orações, não as ouço, porque as mãos de vocês estão cheias de sangue.

[[v23-1-16]]

^<<v23-1-16,16>>^ Lavem-se e purifiquem-se! Tirem da minha presença a maldade dos seus atos; parem de fazer o mal!

[[v23-1-17]]

^<<v23-1-17,17>>^ Aprendam a fazer o bem; busquem a justiça, repreendam o opressor; garantam o direito dos órfãos, defendam a causa das viúvas."

[[v23-1-18]]

^<<v23-1-18,18>>^ O Senhor  diz: "Venham, pois, e vamos discutir a questão. Ainda que os pecados de vocês sejam como o escarlate, eles se tornarão brancos como a neve; ainda que sejam vermelhos como o carmesim, eles se tornarão como a lã.

[[v23-1-19]]

^<<v23-1-19,19>>^ Se estiverem dispostos e me ouvirem, vocês comerão o melhor desta terra.

[[v23-1-20]]

^<<v23-1-20,20>>^ Mas, se recusarem e forem rebeldes, vocês serão devorados pela espada; porque a boca do Senhor  o disse."

[[v23-1-21]]

^<<v23-1-21,21>>^ Como se fez prostituta a cidade fiel, ela que estava cheia de justiça! Nela habitava a retidão, mas agora só restaram assassinos.

[[v23-1-22]]

^<<v23-1-22,22>>^ Jerusalém, a sua prata se tornou escória, o seu licor se misturou com água.

[[v23-1-23]]

^<<v23-1-23,23>>^ Os seus príncipes são rebeldes e companheiros de ladrões. Cada um deles ama o suborno e corre atrás de recompensas. Eles não defendem o direito do órfão, e a causa das viúvas não chega diante deles.

[[v23-1-24]]

^<<v23-1-24,24>>^ Por isso, o Senhor, o Senhor  dos Exércitos, o Poderoso de Israel, diz: "Ah! Acertarei as contas com os meus adversários e me vingarei dos meus inimigos.

[[v23-1-25]]

^<<v23-1-25,25>>^ Voltarei a minha mão contra você, Jerusalém, purificando-a da sua escória como se faz com potassa e tirando de você todo metal impuro.

[[v23-1-26]]

^<<v23-1-26,26>>^ Eu lhe darei juízes como você tinha antigamente, e conselheiros, como no princípio. Depois disso você será chamada ‘Cidade da Justiça’, ‘Cidade Fiel’."

[[v23-1-27]]

^<<v23-1-27,27>>^ Sião será redimida pelo direito, e os que se arrependem, pela justiça.

[[v23-1-28]]

^<<v23-1-28,28>>^ Mas os transgressores e os pecadores serão juntamente destruídos, e os que deixarem o Senhor perecerão.

[[v23-1-29]]

^<<v23-1-29,29>>^ Vocês terão vergonha dos carvalhos que cobiçaram e ficarão desiludidos por causa dos jardins sagrados que escolheram.

[[v23-1-30]]

^<<v23-1-30,30>>^ Porque vocês serão como o carvalho cujas folhas murcham; serão como um jardim que não tem água.

[[v23-1-31]]

^<<v23-1-31,31>>^ O forte se tornará como estopa, e a sua obra, como faísca; ambos serão queimados juntos, e não haverá quem apague o fogo.

'''

xref:022-canticos/022-canticos-008.adoc#v22-8-0[&#60; Capítulo Anterior] | <<v23-1-0,Topo>> | xref:023-isaias/023-isaias-002.adoc#v23-2-0[Próximo Capítulo &#62;]