include::./index.adoc[]

[[v23-49-0]]
=== Isaías, 49
// naa ?, NAA - Nova Almeida Atualizada

[[v23-49-1]]

^<<v23-49-1,1>>^ Escutem, terras do mar, e vocês, povos de longe, prestem atenção! O Senhor  me chamou desde o meu nascimento, desde o ventre de minha mãe fez menção do meu nome.

[[v23-49-2]]

^<<v23-49-2,2>>^ Ele fez a minha boca como uma espada aguda, na sombra da sua mão me escondeu. Ele fez de mim uma flecha polida, e me guardou na sua aljava.

[[v23-49-3]]

^<<v23-49-3,3>>^ E me disse: "Você é o meu servo, você é Israel, por meio de quem hei de ser glorificado."

[[v23-49-4]]

^<<v23-49-4,4>>^ Mas eu disse: "Tenho trabalhado em vão; gastei as minhas forças por nada e à toa." Todavia, o meu direito está diante do Senhor , a minha recompensa está diante do meu Deus.

[[v23-49-5]]

^<<v23-49-5,5>>^ Mas agora diz o Senhor , que me formou desde o ventre para ser o seu servo, para trazer Jacó de volta e reunir Israel a ele, porque sou glorificado diante do Senhor , e o meu Deus é a minha força.

[[v23-49-6]]

^<<v23-49-6,6>>^ Sim, ele diz: "Para você, é muito pouco ser o meu servo para restaurar as tribos de Jacó e trazer de volta o remanescente de Israel. Farei também com que você seja uma luz para os gentios, para que você seja a minha salvação até os confins da terra."

[[v23-49-7]]

^<<v23-49-7,7>>^ O Senhor , o Redentor e Santo de Israel, diz ao que é desprezado, ao que é detestado pelas nações, ao servo dos dominadores: "Os reis o verão e se levantarão; os príncipes se inclinarão diante de você por amor do Senhor , que é fiel, e do Santo de Israel, que o escolheu."

[[v23-49-8]]

^<<v23-49-8,8>>^ Assim diz o Senhor : "No tempo aceitável eu escutei você e no dia da salvação eu o socorri. Eu o guardarei e o farei mediador da aliança com o povo, para restaurar a terra e repartir as propriedades devastadas,

[[v23-49-9]]

^<<v23-49-9,9>>^ para dizer aos presos: ‘Saiam da prisão!’, e aos que estão em trevas: ‘Venham para fora!’" "Eles pastarão ao longo dos caminhos e em todos os montes desertos terão o seu pasto.

[[v23-49-10]]

^<<v23-49-10,10>>^ Não terão fome nem sede, o calor forte e o sol não os afligirão, porque o que se compadece deles os guiará e os conduzirá aos mananciais das águas.

[[v23-49-11]]

^<<v23-49-11,11>>^ Transformarei todos os meus montes em caminhos, e as minhas estradas serão levantadas.

[[v23-49-12]]

^<<v23-49-12,12>>^ Eis que estes virão de longe, e eis que aqueles virão do Norte e do Ocidente; outros virão da terra de Sinim."

[[v23-49-13]]

^<<v23-49-13,13>>^ Alegrem-se, ó céus, exulte, ó terra, e vocês, montes, cantem de alegria, porque o Senhor  consolou o seu povo e se compadece dos seus aflitos.

[[v23-49-14]]

^<<v23-49-14,14>>^ Mas Sião diz: "O Senhor  me abandonou, o Senhor se esqueceu de mim."

[[v23-49-15]]

^<<v23-49-15,15>>^ O Senhor  responde: "Será que uma mulher pode se esquecer do filho que ainda mama, de maneira que não se compadeça do filho do seu ventre? Mas ainda que esta viesse a se esquecer dele, eu, porém, não me esquecerei de você.

[[v23-49-16]]

^<<v23-49-16,16>>^ Eis que eu gravei você nas palmas das minhas mãos; as suas muralhas estão continuamente diante de mim.

[[v23-49-17]]

^<<v23-49-17,17>>^ Os seus filhos virão depressa, enquanto os que a destruíram e devastaram se afastam de você.

[[v23-49-18]]

^<<v23-49-18,18>>^ Levante os olhos ao redor e veja: todos se reúnem e vêm até você. Tão certo como eu vivo", diz o Senhor , "de todos eles você se vestirá como de um enfeite e deles se cingirá como noiva."

[[v23-49-19]]

^<<v23-49-19,19>>^ "Pois, quanto aos seus lugares desertos e devastados e à sua terra destruída, agora você, ó Sião, certamente será pequena demais para os moradores; e os que a devoravam estarão bem longe.

[[v23-49-20]]

^<<v23-49-20,20>>^ Os filhos que nasceram nos seus dias de luto dirão a você: ‘Este lugar é pequeno demais para nós; dê-nos mais espaço para morar.’

[[v23-49-21]]

^<<v23-49-21,21>>^ Então você pensará assim: ‘Quem me gerou estes filhos? Pois eu era uma mulher sem filhos e estéril, em exílio e abandonada. Quem criou esses filhos para mim? Fui deixada sozinha; e estes onde estavam?’"

[[v23-49-22]]

^<<v23-49-22,22>>^ Assim diz o Senhor  Deus: "Eis que acenarei para as nações e diante dos povos levantarei a minha bandeira; eles trarão nos braços os seus filhos, ó Sião, e as suas filhas serão levadas sobre os ombros.

[[v23-49-23]]

^<<v23-49-23,23>>^ Reis serão os guardiões deles, e rainhas serão as suas babás. Eles se inclinarão diante de você com o rosto em terra e lamberão o pó dos seus pés. Então você saberá que eu sou o Senhor e que os que esperam em mim não serão envergonhados."

[[v23-49-24]]

^<<v23-49-24,24>>^ Será que alguém pode tirar o despojo de um valente? Será que os presos podem fugir do tirano?

[[v23-49-25]]

^<<v23-49-25,25>>^ Mas assim diz o Senhor : "Certamente os presos serão tirados do valente, e o despojo do tirano será resgatado, porque eu lutarei contra os que lutam contra você e salvarei os seus filhos.

[[v23-49-26]]

^<<v23-49-26,26>>^ Farei com que os seus opressores comam a sua própria carne e se embriaguem com o seu próprio sangue, como se fosse vinho novo. Então toda a humanidade saberá que eu sou o Senhor , o seu Salvador e o seu Redentor, o Poderoso de Jacó."

'''

xref:023-isaias/023-isaias-048.adoc#v23-48-0[&#60; Capítulo Anterior] | <<v23-49-0,Topo>> | xref:023-isaias/023-isaias-050.adoc#v23-50-0[Próximo Capítulo &#62;]