include::./index.adoc[]

[[v23-27-0]]
=== Isaías, 27
// naa ?, NAA - Nova Almeida Atualizada

[[v23-27-1]]

^<<v23-27-1,1>>^ Naquele dia, com a sua espada terrível, grande e forte, o Senhor  castigará o Leviatã, serpente veloz, o Leviatã, serpente sinuosa; ele matará o monstro que está no mar.

[[v23-27-2]]

^<<v23-27-2,2>>^ Naquele dia, o Senhor  dirá: "Cantem a respeito da vinha deliciosa!

[[v23-27-3]]

^<<v23-27-3,3>>^ Eu, o Senhor , a vigio e a rego constantemente. De dia e de noite eu cuido dela, para que ninguém lhe faça dano.

[[v23-27-4]]

^<<v23-27-4,4>>^ Não estou irado com ela. Quem me dera ter espinheiros e ervas daninhas diante de mim! Em guerra, eu iria contra eles e os queimaria ao mesmo tempo.

[[v23-27-5]]

^<<v23-27-5,5>>^ Ou que se ponham sob a minha proteção e façam as pazes comigo; sim, que façam as pazes comigo."

[[v23-27-6]]

^<<v23-27-6,6>>^ Virão dias em que Jacó lançará raízes e Israel florescerá e brotará; e encherão o mundo de frutos.

[[v23-27-7]]

^<<v23-27-7,7>>^ Será mesmo que o Senhor castigou Israel como fez com aqueles que castigaram o seu povo? Ou o matou, assim como fez com aqueles que mataram o seu povo?

[[v23-27-8]]

^<<v23-27-8,8>>^ Com "xô!", "xô!" e exílio o trataste; com forte sopro o expulsaste no dia do vento leste.

[[v23-27-9]]

^<<v23-27-9,9>>^ Portanto, com isto será expiada a culpa de Jacó. E este será todo o fruto do perdão do seu pecado: quando ele fizer com que todas as pedras dos altares pagãos sejam esmigalhadas, como se fossem pedras de cal, os postes da deusa Aserá e os altares do incenso não ficarão em pé.

[[v23-27-10]]

^<<v23-27-10,10>>^ Porque a cidade fortificada está solitária; é habitação desamparada e abandonada como um deserto. Ali pastam os bezerros; ali eles se deitam e comem os ramos das árvores.

[[v23-27-11]]

^<<v23-27-11,11>>^ Quando os ramos secam, são quebrados. Então vêm as mulheres e os apanham para fazer fogo. Porque este é um povo que não tem entendimento; por isso, aquele que o fez não terá compaixão dele, e aquele que o formou não será gracioso para com ele.

[[v23-27-12]]

^<<v23-27-12,12>>^ Naquele dia, em que o Senhor  debulhará o seu cereal desde o Eufrates até o ribeiro do Egito, vocês, filhos de Israel, serão colhidos um a um.

[[v23-27-13]]

^<<v23-27-13,13>>^ Naquele dia, se tocará uma grande trombeta, e os que andavam perdidos pela terra da Assíria e os que foram desterrados para a terra do Egito virão e adorarão o Senhor  no monte santo em Jerusalém.

'''

xref:023-isaias/023-isaias-026.adoc#v23-26-0[&#60; Capítulo Anterior] | <<v23-27-0,Topo>> | xref:023-isaias/023-isaias-028.adoc#v23-28-0[Próximo Capítulo &#62;]