include::./index.adoc[]

[[v23-42-0]]
=== Isaías, 42
// naa ?, NAA - Nova Almeida Atualizada

[[v23-42-1]]

^<<v23-42-1,1>>^ "Eis aqui o meu servo, a quem sustenho; o meu escolhido, em quem a minha alma se agrada. Pus sobre ele o meu Espírito, e ele promulgará o direito para os gentios.

[[v23-42-2]]

^<<v23-42-2,2>>^ Não clamará, não gritará, nem fará ouvir na praça a sua voz.

[[v23-42-3]]

^<<v23-42-3,3>>^ Não esmagará a cana quebrada, nem apagará o pavio que fumega; com fidelidade, promulgará o direito.

[[v23-42-4]]

^<<v23-42-4,4>>^ Não desanimará, nem será esmagado até que estabeleça na terra a justiça; e as terras do mar aguardarão a sua doutrina."

[[v23-42-5]]

^<<v23-42-5,5>>^ Assim diz Deus, o Senhor , que criou os céus e os estendeu; que formou a terra e tudo o que ela produz; que dá fôlego de vida ao povo que nela está e o espírito aos que andam nela:

[[v23-42-6]]

^<<v23-42-6,6>>^ "Eu, o Senhor , chamei você em justiça; eu o tomarei pela mão, o guardarei, e farei de você mediador da aliança com o povo e luz para os gentios;

[[v23-42-7]]

^<<v23-42-7,7>>^ para abrir os olhos dos cegos, para tirar da prisão os cativos, e do cárcere, os que jazem em trevas.

[[v23-42-8]]

^<<v23-42-8,8>>^ Eu sou o Senhor : este é o meu nome. Não darei a mais ninguém a minha glória, nem a minha honra, às imagens de escultura."

[[v23-42-9]]

^<<v23-42-9,9>>^ "Eis que as primeiras predições já se cumpriram, e agora eu lhes anuncio coisas novas; e, antes que se cumpram, eu as revelo a vocês."

[[v23-42-10]]

^<<v23-42-10,10>>^ Cantem ao Senhor um cântico novo! Que ele seja louvado desde os confins da terra pelos que navegam no mar, por todas as criaturas que vivem nele, e pelas terras do mar e os seus moradores.

[[v23-42-11]]

^<<v23-42-11,11>>^ Ergam a voz o deserto, as suas cidades e as aldeias habitadas por Quedar; exultem os que habitam em Sela e clamem do alto dos montes;

[[v23-42-12]]

^<<v23-42-12,12>>^ deem honra ao Senhor e anunciem a sua glória nas terras do mar.

[[v23-42-13]]

^<<v23-42-13,13>>^ O Senhor  sairá como valente, despertará o seu zelo como homem de guerra. Clamará, lançará forte grito de guerra e mostrará sua força contra os seus inimigos.

[[v23-42-14]]

^<<v23-42-14,14>>^ "Por muito tempo me calei, estive em silêncio e me contive; mas agora darei gritos como mulher que está dando à luz, e ao mesmo tempo ofegarei, e estarei esbaforido.

[[v23-42-15]]

^<<v23-42-15,15>>^ Devastarei os montes e as colinas, e farei secar toda a sua vegetação; tornarei os rios em terra firme e secarei os lagos.

[[v23-42-16]]

^<<v23-42-16,16>>^ Guiarei os cegos por um caminho que não conhecem, farei com que andem por veredas desconhecidas; tornarei as trevas em luz diante deles e aplanarei os caminhos ásperos. Estas coisas lhes farei e nunca os abandonarei.

[[v23-42-17]]

^<<v23-42-17,17>>^ Retrocederão e ficarão cobertos de vergonha os que confiam em imagens de escultura e que dizem às imagens de fundição: ‘Vocês são os nossos deuses.’"

[[v23-42-18]]

^<<v23-42-18,18>>^ "Escutem, surdos, e vocês, cegos, olhem, para que possam ver.

[[v23-42-19]]

^<<v23-42-19,19>>^ Quem é tão cego como o meu servo, ou tão surdo como o meu mensageiro, a quem envio? Quem é tão cego como o meu amigo, e tão cego como o servo do Senhor ?

[[v23-42-20]]

^<<v23-42-20,20>>^ Você vê muitas coisas, mas não as observa; ainda que tenha os ouvidos abertos, não ouve nada."

[[v23-42-21]]

^<<v23-42-21,21>>^ Foi do agrado do Senhor , por amor da sua própria justiça, engrandecer a lei e torná-la gloriosa.

[[v23-42-22]]

^<<v23-42-22,22>>^ Mas este é um povo roubado e saqueado. Todos estão trancados em cavernas e escondidos em cárceres; foram feitos prisioneiros, e não há ninguém que os livre; foram levados como despojo, e ninguém diz: "Devolva!"

[[v23-42-23]]

^<<v23-42-23,23>>^ Quem de vocês dará ouvidos a isto? Quem dará atenção e ouvirá o que há de ser depois?

[[v23-42-24]]

^<<v23-42-24,24>>^ Quem entregou Jacó por despojo e Israel aos roubadores? Por acaso não foi o Senhor , aquele contra quem pecaram e nos caminhos do qual não queriam andar, não dando ouvidos à sua lei?

[[v23-42-25]]

^<<v23-42-25,25>>^ Por isso derramou sobre eles o furor da sua ira e a violência da guerra; ateou fogo em tudo o que estava em volta deles, mas eles não entenderam; ele os queimou, mas eles não fizeram caso.

'''

xref:023-isaias/023-isaias-041.adoc#v23-41-0[&#60; Capítulo Anterior] | <<v23-42-0,Topo>> | xref:023-isaias/023-isaias-043.adoc#v23-43-0[Próximo Capítulo &#62;]