include::./index.adoc[]

[[v23-18-0]]
=== Isaías, 18
// naa ?, NAA - Nova Almeida Atualizada

[[v23-18-1]]

^<<v23-18-1,1>>^ Ai da terra onde há o roçar de muitas asas de insetos, que está além dos rios da Etiópia,

[[v23-18-2]]

^<<v23-18-2,2>>^ que envia embaixadores por mar em navios de papiro sobre as águas. Vão, mensageiros velozes, a uma nação de homens altos e de pele lustrosa, a um povo que é temido pelos de perto e de longe, a uma nação poderosa e esmagadora, cuja terra é dividida por rios.

[[v23-18-3]]

^<<v23-18-3,3>>^ Todos vocês, habitantes do mundo, os moradores da terra, olhem bem quando a bandeira for levantada nos montes. Quando a trombeta soar, escutem!

[[v23-18-4]]

^<<v23-18-4,4>>^ Porque o Senhor  me disse: "Olhando da minha morada, estarei calmo como o ardor do sol resplandecente, como a nuvem do orvalho no tempo quente da colheita."

[[v23-18-5]]

^<<v23-18-5,5>>^ Porque antes da vindima, caída já a flor, e quando as uvas amadurecem, então podará os brotos com a foice e cortará os ramos que se estendem.

[[v23-18-6]]

^<<v23-18-6,6>>^ Todos serão deixados para as aves dos montes e para os animais selvagens; sobre eles as aves de rapina passarão o verão, e todos os animais selvagens passarão o inverno sobre eles.

[[v23-18-7]]

^<<v23-18-7,7>>^ Naquele tempo, será levado um presente ao Senhor  dos Exércitos por um povo de homens altos e de pele lustrosa, povo que é temido pelos de perto e de longe, por uma nação poderosa e esmagadora, cuja terra é dividida por rios. Esse presente será levado ao lugar do nome do Senhor  dos Exércitos, ao monte Sião.

'''

xref:023-isaias/023-isaias-017.adoc#v23-17-0[&#60; Capítulo Anterior] | <<v23-18-0,Topo>> | xref:023-isaias/023-isaias-019.adoc#v23-19-0[Próximo Capítulo &#62;]