include::./index.adoc[]

[[v23-46-0]]
=== Isaías, 46
// naa ?, NAA - Nova Almeida Atualizada

[[v23-46-1]]

^<<v23-46-1,1>>^ "Bel se encurva, Nebo se abaixa; os ídolos são postos sobre os animais, sobre as bestas. As cargas que vocês costumavam levar são canseira para os animais já cansados.

[[v23-46-2]]

^<<v23-46-2,2>>^ Esses deuses juntamente se abaixam e se encurvam; não podem salvar a carga, mas eles mesmos vão para o cativeiro."

[[v23-46-3]]

^<<v23-46-3,3>>^ "Escutem, ó casa de Jacó e todo o remanescente da casa de Israel, vocês que eu carrego desde o ventre materno e que levo nos braços desde o nascimento.

[[v23-46-4]]

^<<v23-46-4,4>>^ Até a velhice de vocês eu serei o mesmo e ainda quando tiverem cabelos brancos eu os carregarei. Eu os fiz e eu os levarei; eu os carregarei e os salvarei."

[[v23-46-5]]

^<<v23-46-5,5>>^ "Com quem vocês vão me comparar? A quem eu seria igual? E que coisa semelhante confrontarão comigo?

[[v23-46-6]]

^<<v23-46-6,6>>^ Os que gastam o ouro da bolsa e pesam a prata nas balanças contratam um ourives para que faça um deus; e depois se prostram e se inclinam diante dele.

[[v23-46-7]]

^<<v23-46-7,7>>^ Eles o põem sobre os ombros, levam-no e o põem no seu lugar, e aí ele fica; do seu lugar não se move. Recorrem a ele, mas nenhuma resposta ele dá e não livra ninguém da sua tribulação."

[[v23-46-8]]

^<<v23-46-8,8>>^ "Lembrem-se disso e animem-se; pensem a respeito disso, ó rebeldes.

[[v23-46-9]]

^<<v23-46-9,9>>^ Lembrem-se das coisas passadas, das coisas da antiguidade: que eu sou Deus, e não há outro; eu sou Deus, e não há outro semelhante a mim.

[[v23-46-10]]

^<<v23-46-10,10>>^ Desde o princípio anuncio o que há de acontecer e desde a antiguidade revelo as coisas que ainda não sucederam. Eu digo: o meu conselho permanecerá em pé, e farei toda a minha vontade.

[[v23-46-11]]

^<<v23-46-11,11>>^ Chamo uma ave de rapina desde o Oriente; de uma terra longínqua vem o homem do meu conselho. Eu o disse e também o cumprirei; fiz este plano, também o executarei."

[[v23-46-12]]

^<<v23-46-12,12>>^ "Escutem, vocês de coração obstinado, que estão longe da justiça.

[[v23-46-13]]

^<<v23-46-13,13>>^ Faço chegar a minha justiça, e ela não está longe; a minha salvação não tardará. Estabelecerei em Sião o livramento e em Israel, a minha glória."

'''

xref:023-isaias/023-isaias-045.adoc#v23-45-0[&#60; Capítulo Anterior] | <<v23-46-0,Topo>> | xref:023-isaias/023-isaias-047.adoc#v23-47-0[Próximo Capítulo &#62;]