include::./index.adoc[]

[[v23-65-0]]
=== Isaías, 65
// naa ?, NAA - Nova Almeida Atualizada

[[v23-65-1]]

^<<v23-65-1,1>>^ "Fui buscado pelos que não perguntavam por mim; fui achado por aqueles que não me buscavam. A um povo que não se chamava pelo meu nome, eu disse: ‘Eis-me aqui! Eis-me aqui!’

[[v23-65-2]]

^<<v23-65-2,2>>^ Todo o dia estendi as mãos a um povo rebelde, que anda por um caminho que não é bom, seguindo os seus próprios pensamentos.

[[v23-65-3]]

^<<v23-65-3,3>>^ É um povo que de contínuo me irrita abertamente, sacrificando em jardins e queimando incenso sobre altares de tijolos.

[[v23-65-4]]

^<<v23-65-4,4>>^ Eles se assentam entre as sepulturas e passam as noites em lugares misteriosos. Comem carne de porco e nos seus pratos têm ensopado de carne abominável.

[[v23-65-5]]

^<<v23-65-5,5>>^ É um povo que diz: ‘Fique onde você está! Não se aproxime de mim, porque sou mais santo do que você.’ Estes são como fumaça no meu nariz, como fogo que queima o dia todo.

[[v23-65-6]]

^<<v23-65-6,6>>^ Eis que está escrito diante de mim: ‘Não me calarei, mas retribuirei; farei retribuição total

[[v23-65-7]]

^<<v23-65-7,7>>^ pelas iniquidades de vocês e também pelas iniquidades dos seus pais’", diz o Senhor . "Eles queimaram incenso nos montes e me afrontaram nas colinas; por isso, eu os farei pagar integralmente pelas suas obras antigas."

[[v23-65-8]]

^<<v23-65-8,8>>^ Assim diz o Senhor : "Como quando se acha suco num cacho de uvas e se diz: ‘Não o destruam, pois há bênção nele’, assim farei por amor de meus servos e não destruirei todos eles.

[[v23-65-9]]

^<<v23-65-9,9>>^ Farei sair de Jacó descendência e de Judá, um herdeiro que possua os meus montes. Os meus eleitos herdarão a terra, e os meus servos habitarão nela.

[[v23-65-10]]

^<<v23-65-10,10>>^ Sarom servirá de pasto para as ovelhas, e o vale de Acor, de lugar de repouso para o gado, para o meu povo que me buscar."

[[v23-65-11]]

^<<v23-65-11,11>>^ "Mas quanto a vocês que se afastam do Senhor , que se esquecem do meu santo monte, que preparam uma mesa para a deusa Fortuna e misturam vinho para o deus Destino,

[[v23-65-12]]

^<<v23-65-12,12>>^ eu os destinarei à espada, e todos vocês se encurvarão à matança. Porque eu chamei, e vocês não responderam; falei, e não atenderam, mas fizeram o que é mau aos meus olhos e escolheram aquilo em que eu não tenho prazer."

[[v23-65-13]]

^<<v23-65-13,13>>^ Portanto, assim diz o Senhor  Deus: "Eis que os meus servos comerão, mas vocês passarão fome; os meus servos beberão, mas vocês terão sede; os meus servos se alegrarão, mas vocês passarão vergonha;

[[v23-65-14]]

^<<v23-65-14,14>>^ os meus servos cantarão por terem o coração alegre, mas vocês gritarão pela tristeza do coração e uivarão pela angústia de espírito.

[[v23-65-15]]

^<<v23-65-15,15>>^ O nome de vocês será deixado como fórmula de maldição para os meus eleitos. O Senhor  Deus fará com que vocês morram, e aos servos dele chamará por outro nome.

[[v23-65-16]]

^<<v23-65-16,16>>^ Assim, quem quiser ser abençoado na terra, será abençoado pelo Deus da verdade; e quem jurar na terra, jurará pelo Deus da verdade. Porque as angústias passadas serão esquecidas e ficarão escondidas dos meus olhos."

[[v23-65-17]]

^<<v23-65-17,17>>^ "Pois eis que eu crio novos céus e nova terra; e não haverá lembrança das coisas passadas, jamais haverá memória delas.

[[v23-65-18]]

^<<v23-65-18,18>>^ Exultem e alegrem-se para sempre no que eu crio; porque eis que crio para Jerusalém alegria e para o seu povo, exultação.

[[v23-65-19]]

^<<v23-65-19,19>>^ Eu me alegrarei por causa de Jerusalém e exultarei no meu povo, e nunca mais se ouvirá nela nem voz de choro nem de clamor.

[[v23-65-20]]

^<<v23-65-20,20>>^ Não haverá mais nela criança que viva somente alguns dias, nem velho que não complete os seus dias. Porque morrer aos cem anos será morrer ainda jovem, e quem pecar só aos cem anos será amaldiçoado."

[[v23-65-21]]

^<<v23-65-21,21>>^ "Eles construirão casas e nelas habitarão; plantarão vinhas e comerão o seu fruto.

[[v23-65-22]]

^<<v23-65-22,22>>^ Não construirão para que outros habitem, nem plantarão para que outros comam. Porque a longevidade do meu povo será como a da árvore, e os meus eleitos desfrutarão ao máximo as obras das suas próprias mãos.

[[v23-65-23]]

^<<v23-65-23,23>>^ Não farão o seu trabalho em vão, nem irão gerar filhos para a calamidade, porque são a descendência dos benditos do Senhor , e os seus filhos estarão com eles.

[[v23-65-24]]

^<<v23-65-24,24>>^ Antes mesmo que clamem, eu responderei; estando eles ainda falando, eu os ouvirei.

[[v23-65-25]]

^<<v23-65-25,25>>^ O lobo e o cordeiro pastarão juntos, e o leão comerá palha como o boi; pó será a comida da serpente. Não se fará mal nem dano algum em todo o meu santo monte", diz o Senhor .

'''

xref:023-isaias/023-isaias-064.adoc#v23-64-0[&#60; Capítulo Anterior] | <<v23-65-0,Topo>> | xref:023-isaias/023-isaias-066.adoc#v23-66-0[Próximo Capítulo &#62;]