include::./index.adoc[]

[[v23-53-0]]
=== Isaías, 53
// naa ?, NAA - Nova Almeida Atualizada

[[v23-53-1]]

^<<v23-53-1,1>>^ Quem creu em nossa pregação? E a quem foi revelado o braço do Senhor ?

[[v23-53-2]]

^<<v23-53-2,2>>^ Porque foi subindo como um renovo diante dele e como raiz de uma terra seca. Não tinha boa aparência nem formosura; olhamos para ele, mas não havia nenhuma beleza que nos agradasse.

[[v23-53-3]]

^<<v23-53-3,3>>^ Era desprezado e o mais rejeitado entre os homens, homem de dores e que sabe o que é padecer. E, como um de quem os homens escondem o rosto, era desprezado, e dele não fizemos caso.

[[v23-53-4]]

^<<v23-53-4,4>>^ Certamente ele tomou sobre si as nossas enfermidades e as nossas dores levou sobre si; e nós o considerávamos como aflito, ferido de Deus e oprimido.

[[v23-53-5]]

^<<v23-53-5,5>>^ Mas ele foi traspassado por causa das nossas transgressões e esmagado por causa das nossas iniquidades; o castigo que nos traz a paz estava sobre ele, e pelas suas feridas fomos sarados.

[[v23-53-6]]

^<<v23-53-6,6>>^ Todos nós andávamos desgarrados como ovelhas; cada um se desviava pelo seu próprio caminho, mas o Senhor  fez cair sobre ele a iniquidade de todos nós.

[[v23-53-7]]

^<<v23-53-7,7>>^ Ele foi oprimido e humilhado, mas não abriu a boca. Como cordeiro foi levado ao matadouro e, como ovelha muda diante dos seus tosquiadores, ele não abriu a boca.

[[v23-53-8]]

^<<v23-53-8,8>>^ Pela opressão e pelo juízo, ele foi levado, e de sua linhagem, quem se preocupou com ela? Porque ele foi cortado da terra dos viventes; foi ferido por causa da transgressão do meu povo.

[[v23-53-9]]

^<<v23-53-9,9>>^ Designaram-lhe a sepultura com os ímpios, mas com o rico esteve na sua morte, embora não tivesse feito injustiça, e nenhum engano fosse encontrado em sua boca.

[[v23-53-10]]

^<<v23-53-10,10>>^ Todavia, ao Senhor agradou esmagá-lo, fazendo-o sofrer. Quando ele der a sua alma como oferta pelo pecado, verá a sua posteridade e prolongará os seus dias; e a vontade do Senhor prosperará nas suas mãos.

[[v23-53-11]]

^<<v23-53-11,11>>^ Ele verá o fruto do trabalho de sua alma e ficará satisfeito. O meu Servo, o Justo, com o seu conhecimento justificará a muitos, porque as iniquidades deles levará sobre si.

[[v23-53-12]]

^<<v23-53-12,12>>^ Por isso, eu lhe darei a sua parte com os grandes, e com os poderosos ele repartirá o despojo, pois derramou a sua alma na morte e foi contado com os transgressores. Contudo, levou sobre si o pecado de muitos e pelos transgressores intercedeu.

'''

xref:023-isaias/023-isaias-052.adoc#v23-52-0[&#60; Capítulo Anterior] | <<v23-53-0,Topo>> | xref:023-isaias/023-isaias-054.adoc#v23-54-0[Próximo Capítulo &#62;]