include::./index.adoc[]

[[v23-63-0]]
=== Isaías, 63
// naa ?, NAA - Nova Almeida Atualizada

[[v23-63-1]]

^<<v23-63-1,1>>^ "Quem é este que vem de Edom, de Bozra, vestido de roupas vermelhas, roupas vistosas, que vem marchando na plenitude da sua força"? "Sou eu, que falo com justiça, que sou poderoso para salvar."

[[v23-63-2]]

^<<v23-63-2,2>>^ "Por que as suas roupas estão vermelhas? Por que se parecem com as roupas de quem pisa uvas no lagar?"

[[v23-63-3]]

^<<v23-63-3,3>>^ "O lagar, eu o pisei sozinho. Dos povos, ninguém esteve comigo. Pisei as uvas na minha ira; no meu furor, as esmaguei, e o seu sangue respingou nas minhas roupas, e todas elas ficaram manchadas.

[[v23-63-4]]

^<<v23-63-4,4>>^ Porque o dia da vingança estava no meu coração, e o ano da redenção havia chegado.

[[v23-63-5]]

^<<v23-63-5,5>>^ Olhei, e não havia quem me ajudasse; fiquei admirado por não haver quem me apoiasse. Por isso o meu próprio braço me trouxe a salvação, e o meu furor foi o meu apoio.

[[v23-63-6]]

^<<v23-63-6,6>>^ Na minha ira, pisei os povos, no meu furor, embriaguei-os, derramando o seu sangue no chão."

[[v23-63-7]]

^<<v23-63-7,7>>^ Celebrarei as misericórdias do Senhor e os seus atos gloriosos, segundo tudo o que o Senhor nos concedeu e segundo a grande bondade para com a casa de Israel, bondade que usou para com eles, segundo a sua compaixão e segundo a multidão das suas misericórdias.

[[v23-63-8]]

^<<v23-63-8,8>>^ Porque ele dizia: "Certamente eles são o meu povo, filhos que nunca me trairão." E ele se tornou o Salvador deles.

[[v23-63-9]]

^<<v23-63-9,9>>^ Em toda a angústia deles, também ele se angustiava; e o Anjo da sua presença os salvou. Por seu amor e por sua compaixão, ele mesmo os remiu, os tomou e os conduziu todos os dias da antiguidade.

[[v23-63-10]]

^<<v23-63-10,10>>^ Mas eles foram rebeldes e contristaram o seu Espírito Santo. Por isso, ele se tornou inimigo deles e ele mesmo lutou contra eles.

[[v23-63-11]]

^<<v23-63-11,11>>^ Então o povo se lembrou dos dias antigos, lembrou de Moisés, e disse: "Onde está aquele que tirou o seu povo do mar, junto com o pastor do seu rebanho? Onde está o que pôs nele o seu Espírito Santo,

[[v23-63-12]]

^<<v23-63-12,12>>^ aquele que fez com que o seu braço glorioso estivesse à mão direita de Moisés? Onde está aquele que dividiu as águas diante deles, adquirindo para si um nome eterno?

[[v23-63-13]]

^<<v23-63-13,13>>^ Aquele que os guiou pelos abismos, como a um cavalo pelo deserto, de modo que nunca tropeçaram?

[[v23-63-14]]

^<<v23-63-14,14>>^ Como o gado que desce aos vales para repousar, o Espírito do Senhor lhes deu descanso." Assim, guiaste o teu povo, para adquirires um nome glorioso.

[[v23-63-15]]

^<<v23-63-15,15>>^ Olha para nós lá do céu, da tua santa e gloriosa habitação. Onde estão o teu zelo e as tuas obras poderosas? Estás retendo a ternura do teu coração? Já se esgotaram as tuas misericórdias para comigo?

[[v23-63-16]]

^<<v23-63-16,16>>^ Mas tu és o nosso Pai. Abraão não nos conhece e Israel não nos reconhece, mas tu, ó Senhor , és o nosso Pai; nosso Redentor é o teu nome desde a antiguidade.

[[v23-63-17]]

^<<v23-63-17,17>>^ Ó Senhor , por que fazes com que nos desviemos dos teus caminhos? Por que endureces o nosso coração, para que não te temamos? Volta, por amor dos teus servos e das tribos da tua herança.

[[v23-63-18]]

^<<v23-63-18,18>>^ Só por breve tempo o teu santo povo tomou posse do país; nossos adversários pisaram o teu santuário.

[[v23-63-19]]

^<<v23-63-19,19>>^ Tornamo-nos como aqueles sobre quem tu nunca dominaste e como os que nunca se chamaram pelo teu nome.

'''

xref:023-isaias/023-isaias-062.adoc#v23-62-0[&#60; Capítulo Anterior] | <<v23-63-0,Topo>> | xref:023-isaias/023-isaias-064.adoc#v23-64-0[Próximo Capítulo &#62;]