include::./index.adoc[]

[[v23-6-0]]
=== Isaías, 6
// naa ?, NAA - Nova Almeida Atualizada

[[v23-6-1]]

^<<v23-6-1,1>>^ No ano da morte do rei Uzias, eu vi o Senhor assentado sobre um alto e sublime trono, e as abas de suas vestes enchiam o templo.

[[v23-6-2]]

^<<v23-6-2,2>>^ Serafins estavam por cima dele. Cada um tinha seis asas: com duas cobria o rosto, com duas cobria os pés e com duas voava.

[[v23-6-3]]

^<<v23-6-3,3>>^ E clamavam uns para os outros, dizendo: "Santo, santo, santo é o Senhor  dos Exércitos; toda a terra está cheia da sua glória."

[[v23-6-4]]

^<<v23-6-4,4>>^ Os umbrais das portas se moveram com a voz do que clamava, e o templo se encheu de fumaça.

[[v23-6-5]]

^<<v23-6-5,5>>^ Então eu disse: — Ai de mim! Estou perdido! Porque sou homem de lábios impuros, e habito no meio de um povo de lábios impuros; e os meus olhos viram o Rei, o Senhor  dos Exércitos!

[[v23-6-6]]

^<<v23-6-6,6>>^ Então um dos serafins voou para mim, trazendo na mão uma brasa viva, que havia tirado do altar com uma pinça.

[[v23-6-7]]

^<<v23-6-7,7>>^ Com a brasa tocou a minha boca e disse: — Eis que esta brasa tocou os seus lábios. A sua iniquidade foi tirada, e o seu pecado, perdoado.

[[v23-6-8]]

^<<v23-6-8,8>>^ Depois disto, ouvi a voz do Senhor, que dizia: — A quem enviarei, e quem há de ir por nós? Eu respondi: — Eis-me aqui, envia-me a mim.

[[v23-6-9]]

^<<v23-6-9,9>>^ Então ele disse: — Vá e diga a este povo: "Ouçam; ouçam, mas sem entender. Vejam; vejam, mas sem perceber."

[[v23-6-10]]

^<<v23-6-10,10>>^ Torne insensível o coração deste povo, endureça-lhes os ouvidos e feche os olhos deles, para que não venham a ver com os olhos, ouvir com os ouvidos e entender com o coração, e se convertam, e sejam curados.

[[v23-6-11]]

^<<v23-6-11,11>>^ Então eu perguntei: "Até quando, Senhor?" Ele respondeu: "Até que as cidades estejam em ruínas e fiquem sem habitantes, as casas fiquem sem moradores e a terra esteja em ruínas e devastada,

[[v23-6-12]]

^<<v23-6-12,12>>^ e o Senhor  afaste dela o povo, e no meio da terra sejam muitos os lugares abandonados.

[[v23-6-13]]

^<<v23-6-13,13>>^ Mas, se ainda ficar a décima parte dela, tornará a ser destruída. Como o terebinto e como o carvalho, dos quais, depois de derrubados, ainda fica o toco, assim a santa semente será o seu toco."

'''

xref:023-isaias/023-isaias-005.adoc#v23-5-0[&#60; Capítulo Anterior] | <<v23-6-0,Topo>> | xref:023-isaias/023-isaias-007.adoc#v23-7-0[Próximo Capítulo &#62;]