include::./index.adoc[]

[[v23-38-0]]
=== Isaías, 38
// naa ?, NAA - Nova Almeida Atualizada

[[v23-38-1]]

^<<v23-38-1,1>>^ Por esse tempo, Ezequias adoeceu de uma enfermidade mortal. O profeta Isaías, filho de Amoz, foi visitá-lo e lhe disse: — Assim diz o Senhor : "Ponha em ordem a sua casa, porque você morrerá; você não vai escapar."

[[v23-38-2]]

^<<v23-38-2,2>>^ Então Ezequias virou o rosto para a parede e orou ao Senhor .

[[v23-38-3]]

^<<v23-38-3,3>>^ Ezequias disse: — Ó Senhor , lembra-te de que andei diante de ti com fidelidade, com coração íntegro, e fiz o que era reto aos teus olhos. E Ezequias chorou amargamente.

[[v23-38-4]]

^<<v23-38-4,4>>^ Então a palavra do Senhor  veio a Isaías, dizendo:

[[v23-38-5]]

^<<v23-38-5,5>>^ — Vá e diga a Ezequias: Assim diz o Senhor , o Deus de Davi, seu pai: "Ouvi a sua oração e vi as suas lágrimas. Acrescentarei quinze anos à sua vida.

[[v23-38-6]]

^<<v23-38-6,6>>^ Livrarei das mãos do rei da Assíria tanto você quanto esta cidade. Eu defenderei esta cidade.

[[v23-38-7]]

^<<v23-38-7,7>>^ Este é o sinal que você receberá do Senhor  para indicar que ele cumprirá o que prometeu:

[[v23-38-8]]

^<<v23-38-8,8>>^ eis que farei retroceder dez graus a sombra lançada pelo sol declinante no relógio de Acaz." Assim, o sol retrocedeu os dez graus que já havia declinado.

[[v23-38-9]]

^<<v23-38-9,9>>^ Este é o cântico que Ezequias, rei de Israel, escreveu depois de ter estado doente e se ter restabelecido:

[[v23-38-10]]

^<<v23-38-10,10>>^ Eu disse: "Em pleno vigor de meus dias, hei de passar pelas portas do além; fui privado do resto dos meus anos.

[[v23-38-11]]

^<<v23-38-11,11>>^ Eu disse: já não verei o Senhor , o Senhor  na terra dos viventes; jamais verei homem algum entre os moradores do mundo.

[[v23-38-12]]

^<<v23-38-12,12>>^ A minha habitação foi arrancada e removida para longe de mim, como a tenda de um pastor. Como tecelão, enrolei a minha vida; ele me cortará do tear; do dia para a noite darás cabo de mim.

[[v23-38-13]]

^<<v23-38-13,13>>^ Esperei com paciência até a madrugada, mas ele, como leão, quebrou todos os meus ossos; do dia para a noite darás cabo de mim."

[[v23-38-14]]

^<<v23-38-14,14>>^ "Eu sussurrava como a andorinha ou o grou e gemia como a pomba; os meus olhos se cansaram de olhar para cima. Ó Senhor, ando oprimido! Sê tu o meu fiador!

[[v23-38-15]]

^<<v23-38-15,15>>^ Que direi? Como falou, assim ele me fez; andarei vagarosamente pelo resto dos meus anos, por causa da amargura da minha alma."

[[v23-38-16]]

^<<v23-38-16,16>>^ "Senhor, por causa destas coisas vivem os homens, e inteiramente delas depende o meu espírito. Portanto, restaura a minha saúde e faze-me viver.

[[v23-38-17]]

^<<v23-38-17,17>>^ Eis que foi para a minha paz que eu tive grande amargura; tu, porém, amaste a minha alma e a livraste da cova da corrupção, porque lançaste para trás de ti todos os meus pecados.

[[v23-38-18]]

^<<v23-38-18,18>>^ A sepultura não pode te louvar, nem a morte glorificar-te; os que descem à cova não esperam em tua fidelidade.

[[v23-38-19]]

^<<v23-38-19,19>>^ Os vivos, somente os vivos, esses te louvam, como hoje estou fazendo. Os pais darão a conhecer aos filhos a tua fidelidade.

[[v23-38-20]]

^<<v23-38-20,20>>^ O Senhor  veio salvar-me. Por isso, tangendo os instrumentos de cordas, nós o louvaremos todos os dias de nossa vida, na Casa do Senhor ."

[[v23-38-21]]

^<<v23-38-21,21>>^ Ora, Isaías tinha dito: — Peguem uma pasta de figos, ponham como emplastro sobre a úlcera, e ele irá recuperar a saúde.

[[v23-38-22]]

^<<v23-38-22,22>>^ E Ezequias tinha perguntado: — Qual será o sinal de que subirei à Casa do Senhor ?

'''

xref:023-isaias/023-isaias-037.adoc#v23-37-0[&#60; Capítulo Anterior] | <<v23-38-0,Topo>> | xref:023-isaias/023-isaias-039.adoc#v23-39-0[Próximo Capítulo &#62;]