include::./index.adoc[]

[[v23-51-0]]
=== Isaías, 51
// naa ?, NAA - Nova Almeida Atualizada

[[v23-51-1]]

^<<v23-51-1,1>>^ "Escutem, vocês que procuram a justiça, vocês que buscam o Senhor : olhem para a rocha da qual vocês foram cortados e para a pedreira de onde foram tirados.

[[v23-51-2]]

^<<v23-51-2,2>>^ Olhem para Abraão, seu pai, e para Sara, que os deu à luz. Porque Abraão era um só, quando eu o chamei, o abençoei e o multipliquei.

[[v23-51-3]]

^<<v23-51-3,3>>^ Porque o Senhor  terá piedade de Sião; terá piedade de todos os seus lugares desolados. Fará o seu deserto como o Éden, e os seus lugares áridos, como o jardim do Senhor . Ali haverá júbilo e alegria, ações de graças e som de música."

[[v23-51-4]]

^<<v23-51-4,4>>^ "Preste atenção, meu povo, e escute, minha nação! Porque de mim sairá a lei, e estabelecerei o meu direito como luz dos povos.

[[v23-51-5]]

^<<v23-51-5,5>>^ Perto está a minha justiça, a minha salvação já aparece, e os meus braços dominarão os povos. As terras do mar me aguardam e no meu braço esperam.

[[v23-51-6]]

^<<v23-51-6,6>>^ Levantem os olhos para os céus e olhem para a terra, aqui embaixo! Porque os céus desaparecerão como a fumaça, e a terra envelhecerá como a roupa; os seus moradores morrerão como mosquitos, mas a minha salvação durará para sempre, e a minha justiça não será anulada."

[[v23-51-7]]

^<<v23-51-7,7>>^ "Escutem, vocês que conhecem a justiça, vocês, povo em cujo coração está a minha lei: não temam os insultos dos homens, nem fiquem assustados por causa das suas zombarias.

[[v23-51-8]]

^<<v23-51-8,8>>^ Porque as traças os roerão como fazem com a roupa, e os bichos os comerão como fazem com a lã. Mas a minha justiça durará para sempre, e a minha salvação, de geração em geração.

[[v23-51-9]]

^<<v23-51-9,9>>^ Desperta! Desperta, braço do Senhor , e arma-te de força! Desperta como nos dias passados, como nas gerações antigas! Não és tu aquele que cortou Raabe em pedaços e feriu o monstro marinho?

[[v23-51-10]]

^<<v23-51-10,10>>^ Não és tu aquele que secou o mar, as águas do grande abismo? Não abriste um caminho no fundo do mar, para que passassem os remidos?

[[v23-51-11]]

^<<v23-51-11,11>>^ Os resgatados do Senhor voltarão e entrarão em Sião com cânticos de júbilo. Alegria eterna coroará a sua cabeça. Ficarão tomados de júbilo e alegria, e deles fugirão a tristeza e o gemido."

[[v23-51-12]]

^<<v23-51-12,12>>^ "Eu, eu sou aquele que os consola; quem, então, é você, para que tenha medo do homem, que é mortal, ou do filho do homem, que não passa de erva?

[[v23-51-13]]

^<<v23-51-13,13>>^ Por que você se esquece do Senhor , que o criou, que estendeu os céus e fundou a terra, e todo o dia, sem cessar, teme a fúria do opressor, que se prepara para destruir? Onde está a fúria do opressor?

[[v23-51-14]]

^<<v23-51-14,14>>^ O exilado cativo depressa será libertado, lá não morrerá, lá não descerá à sepultura; o seu pão não lhe faltará."

[[v23-51-15]]

^<<v23-51-15,15>>^ "Pois eu sou o Senhor , seu Deus, que agito o mar, de modo que bramem as suas ondas. O meu nome é Senhor  dos Exércitos.

[[v23-51-16]]

^<<v23-51-16,16>>^ Confio a você as minhas palavras e o protejo com a sombra da minha mão, para que eu estenda os céus, firme a terra e diga a Sião: ‘Você é o meu povo.’"

[[v23-51-17]]

^<<v23-51-17,17>>^ Acorde! Acorde e levante-se, ó Jerusalém, você que bebeu da mão do Senhor o cálice da sua ira, você que esgotou o cálice de atordoamento.

[[v23-51-18]]

^<<v23-51-18,18>>^ De todos os filhos que ela teve nenhum a guiou; de todos os filhos que criou nenhum a tomou pela mão.

[[v23-51-19]]

^<<v23-51-19,19>>^ Estas duas coisas lhe sobrevieram, mas quem teve compaixão de você? Houve destruição e ruína, fome e espada, mas quem veio consolar você?

[[v23-51-20]]

^<<v23-51-20,20>>^ Os seus filhos desmaiaram, jazem nas esquinas de todas as ruas, como o antílope na rede. Estão cheios da ira do Senhor e da repreensão do seu Deus.

[[v23-51-21]]

^<<v23-51-21,21>>^ Por isso, agora escute isto, você que está aflita e embriagada, mas não de vinho.

[[v23-51-22]]

^<<v23-51-22,22>>^ Assim diz o seu Senhor, o Senhor , seu Deus, que defenderá a causa do seu povo: "Eis que eu tiro da sua mão o cálice de atordoamento, o cálice da minha ira. Você nunca mais beberá dele.

[[v23-51-23]]

^<<v23-51-23,23>>^ Eu o porei nas mãos dos que a atormentaram, dos que lhe disseram: ‘Abaixe-se, para que passemos por cima de você!’ E você pôs as suas costas como chão e como rua para os que passavam."

'''

xref:023-isaias/023-isaias-050.adoc#v23-50-0[&#60; Capítulo Anterior] | <<v23-51-0,Topo>> | xref:023-isaias/023-isaias-052.adoc#v23-52-0[Próximo Capítulo &#62;]