include::./index.adoc[]

[[v23-30-0]]
=== Isaías, 30
// naa ?, NAA - Nova Almeida Atualizada

[[v23-30-1]]

^<<v23-30-1,1>>^ "Ai dos filhos rebeldes", diz o Senhor , "que executam planos que não procedem de mim e fazem aliança sem consultar o meu Espírito, para acrescentarem pecado sobre pecado!

[[v23-30-2]]

^<<v23-30-2,2>>^ Eles descem ao Egito sem me consultar, buscando refúgio em Faraó e abrigo à sombra do Egito!

[[v23-30-3]]

^<<v23-30-3,3>>^ Mas o refúgio de Faraó se transformará em vergonha para vocês, e o abrigo na sombra do Egito resultará em humilhação.

[[v23-30-4]]

^<<v23-30-4,4>>^ Porque os príncipes de Judá já estão em Zoã, e os seus embaixadores já chegaram a Hanes.

[[v23-30-5]]

^<<v23-30-5,5>>^ Mas todos ficarão envergonhados por causa de um povo que não os ajudará em nada, que não servirá nem de ajuda nem de proveito, porém de vergonha e de vexame."

[[v23-30-6]]

^<<v23-30-6,6>>^ Sentença contra a Besta do Sul. "Atravessando a terra da aflição e da angústia, de onde vêm a leoa, o leão, a víbora e a serpente voadora, os embaixadores levam as suas riquezas em lombo de jumento, e transportam os seus tesouros sobre as corcovas de camelos. Levam as suas riquezas e os seus tesouros a um povo que não lhes será de proveito algum.

[[v23-30-7]]

^<<v23-30-7,7>>^ Pois, quanto ao Egito, o seu auxílio é vão e inútil. Por isso, eu o chamo de ‘Besta que nada faz’."

[[v23-30-8]]

^<<v23-30-8,8>>^ "Agora vá e escreva isso numa tabuinha diante deles, escreva-o num livro, para que fique registrado para os dias vindouros, para sempre, perpetuamente.

[[v23-30-9]]

^<<v23-30-9,9>>^ Porque este é um povo rebelde; são filhos mentirosos, filhos que não querem ouvir a lei do Senhor .

[[v23-30-10]]

^<<v23-30-10,10>>^ Eles dizem aos videntes: ‘Não tenham mais visões!’ E aos profetas: ‘Não profetizem para nós o que é reto; digam-nos coisas agradáveis, profetizem ilusões.

[[v23-30-11]]

^<<v23-30-11,11>>^ Desviem-se do caminho, afastem-se da vereda; não nos falem mais a respeito do Santo de Israel.’"

[[v23-30-12]]

^<<v23-30-12,12>>^ Por isso o Santo de Israel diz: "Vocês rejeitam esta palavra, confiam na opressão e na perversidade e se apoiam sobre isso.

[[v23-30-13]]

^<<v23-30-13,13>>^ Portanto, esta maldade será para vocês como brecha num muro alto, que, formando uma barriga, está prestes a cair, e cuja queda vem de repente, num momento.

[[v23-30-14]]

^<<v23-30-14,14>>^ O Senhor  quebrará esse muro como se quebra o vaso do oleiro, despedaçando-o por completo; não se achará entre os seus cacos um que sirva para tirar brasas da lareira ou apanhar água da cisterna."

[[v23-30-15]]

^<<v23-30-15,15>>^ Porque assim diz o Senhor  Deus, o Santo de Israel: "Na conversão e no descanso está a salvação de vocês; na tranquilidade e na confiança reside a força de vocês. Mas vocês não quiseram.

[[v23-30-16]]

^<<v23-30-16,16>>^ Pelo contrário, disseram: ‘Nada disso! Nós vamos fugir a cavalo!’ Portanto, vocês fugirão. E vocês disseram: ‘Vamos cavalgar sobre cavalos ligeiros!’ Portanto, ligeiros serão aqueles que perseguem vocês.

[[v23-30-17]]

^<<v23-30-17,17>>^ Mil homens fugirão pela ameaça de apenas um; pela ameaça de cinco, todos vocês fugirão, até que sejam deixados como um mastro no alto do monte e como um estandarte no topo da colina."

[[v23-30-18]]

^<<v23-30-18,18>>^ Por isso, o Senhor  espera, para ter misericórdia de vocês, e se levanta, para se compadecer de vocês, porque o Senhor  é Deus de justiça. Bem-aventurados todos os que nele esperam.

[[v23-30-19]]

^<<v23-30-19,19>>^ Porque o povo habitará em Sião, em Jerusalém. Vocês não vão chorar mais. Ele certamente se compadecerá, ao ouvir o clamor de vocês; e, ouvindo-o, lhes responderá.

[[v23-30-20]]

^<<v23-30-20,20>>^ Embora o Senhor lhes dê pão de angústia e água de aflição, os mestres de vocês não se esconderão mais; vocês os verão com os seus próprios olhos.

[[v23-30-21]]

^<<v23-30-21,21>>^ Quando vocês se desviarem para a direita ou para a esquerda, ouvirão atrás de vocês uma palavra, dizendo: "Este é o caminho; andem nele."

[[v23-30-22]]

^<<v23-30-22,22>>^ Vocês tratarão como impuras as imagens esculpidas cobertas de prata e as imagens de fundição revestidas de ouro; vocês as jogarão fora como coisa impura e dirão a cada uma delas: "Fora daqui!"

[[v23-30-23]]

^<<v23-30-23,23>>^ O Senhor lhes dará chuva para as sementes que vocês semearem na terra, e também lhes dará o alimento que a terra produzir, o qual será farto e nutritivo. Naquele dia, o gado de vocês pastará em lugares espaçosos.

[[v23-30-24]]

^<<v23-30-24,24>>^ Os bois e os jumentos que lavram a terra comerão forragem com sal, espalhada com pá e forcado.

[[v23-30-25]]

^<<v23-30-25,25>>^ No dia do grande massacre, quando caírem as torres, haverá ribeiros e correntes de água em todos os montes altos e em todas as colinas elevadas.

[[v23-30-26]]

^<<v23-30-26,26>>^ A luz da lua será como a do sol, e a do sol será sete vezes maior, como a luz de sete dias, no dia em que o Senhor  tratar as fraturas do seu povo e curar a ferida do golpe que ele deu.

[[v23-30-27]]

^<<v23-30-27,27>>^ Eis que o nome do Senhor vem de longe, ardendo na sua ira, no meio de espessas nuvens. Os seus lábios estão cheios de indignação, e a sua língua é como fogo devorador.

[[v23-30-28]]

^<<v23-30-28,28>>^ A sua respiração é como a torrente que transborda e chega até o pescoço. Ele vem peneirar as nações com peneira de destruição; porá na boca dos povos um freio para fazer com que andem errantes.

[[v23-30-29]]

^<<v23-30-29,29>>^ Vocês cantarão como nas noites em que se celebra uma festa santa; terão alegria de coração como a daquele que sai ao som da flauta para ir ao monte do Senhor , à Rocha de Israel.

[[v23-30-30]]

^<<v23-30-30,30>>^ O Senhor  fará ouvir a sua voz majestosa e fará ver o golpe do seu braço, que desce com indignação de ira, no meio de chamas devoradoras, de chuvas torrenciais, de tempestades e de granizo.

[[v23-30-31]]

^<<v23-30-31,31>>^ Porque a Assíria ficará apavorada com a voz do Senhor , quando ele a ferir com o seu bastão.

[[v23-30-32]]

^<<v23-30-32,32>>^ Cada pancada castigadora que o Senhor  lhe der com o bastão será ao som de tamborins e harpas; ele combaterá desferindo golpes contra eles.

[[v23-30-33]]

^<<v23-30-33,33>>^ Porque há muito está preparada a fogueira; sim, preparada para o rei. Ela é profunda e larga, com fogo e lenha em abundância; o sopro do Senhor , como torrente de enxofre, a acenderá.

'''

xref:023-isaias/023-isaias-029.adoc#v23-29-0[&#60; Capítulo Anterior] | <<v23-30-0,Topo>> | xref:023-isaias/023-isaias-031.adoc#v23-31-0[Próximo Capítulo &#62;]