include::./index.adoc[]

[[v23-47-0]]
=== Isaías, 47
// naa ?, NAA - Nova Almeida Atualizada

[[v23-47-1]]

^<<v23-47-1,1>>^ "Desça e sente-se no pó, ó virgem filha da Babilônia; sente-se no chão, pois já não há trono, ó filha dos caldeus. Porque nunca mais você será chamada sensível e delicada.

[[v23-47-2]]

^<<v23-47-2,2>>^ Pegue as pedras do moinho e faça farinha; tire o véu, levante a saia, descubra as pernas e atravesse os rios.

[[v23-47-3]]

^<<v23-47-3,3>>^ A sua nudez será descoberta, e se verá a sua vergonha; tomarei vingança e não pouparei ninguém."

[[v23-47-4]]

^<<v23-47-4,4>>^ Quanto ao nosso Redentor, Senhor  dos Exércitos é o seu nome, o Santo de Israel.

[[v23-47-5]]

^<<v23-47-5,5>>^ "Fique sentada em silêncio e vá para um lugar escuro, ó filha dos caldeus, porque nunca mais você será chamada senhora dos reinos.

[[v23-47-6]]

^<<v23-47-6,6>>^ Eu estava irado contra o meu povo, profanei a minha herança e a entreguei nas suas mãos, mas você não usou de misericórdia com ela e até sobre os velhos você fez muito pesado o seu jugo.

[[v23-47-7]]

^<<v23-47-7,7>>^ Você disse: ‘Eu serei senhora para sempre!’ Até agora você não levou estas coisas a sério, nem se lembrou do seu fim.

[[v23-47-8]]

^<<v23-47-8,8>>^ Agora, pois, escute isto, você que ama os prazeres, que habita segura e que diz a si mesma: ‘Eu sou a única, e não há outra além de mim. Não ficarei viúva, nem conhecerei a perda de filhos.’"

[[v23-47-9]]

^<<v23-47-9,9>>^ "Mas ambas estas coisas virão sobre você num momento, no mesmo dia: perda de filhos e viuvez; virão em cheio sobre você, apesar da multidão das suas feitiçarias e da abundância dos seus encantamentos.

[[v23-47-10]]

^<<v23-47-10,10>>^ Porque você confiou na sua maldade e dizia: ‘Não há quem me veja.’ A sua sabedoria e o seu conhecimento, isso fez com que você se desviasse e dissesse a si mesma: ‘Eu sou a única, e não há outra além de mim.’

[[v23-47-11]]

^<<v23-47-11,11>>^ Por isso, virá sobre você uma desgraça que você não saberá afastar com os seus encantamentos. Cairá sobre você uma calamidade da qual não poderá se livrar por expiação. Porque sobre você virá, de repente, uma desolação como você não imaginava.

[[v23-47-12]]

^<<v23-47-12,12>>^ Continue, pois, com os seus encantamentos e com a multidão das suas feitiçarias em que você tem se fatigado desde a sua mocidade! Talvez você possa tirar algum proveito disso; talvez, com isso, consiga inspirar terror.

[[v23-47-13]]

^<<v23-47-13,13>>^ Você está cansada de tanto ouvir conselhos! Que se levantem, agora, os que dissecam os céus e fitam os astros, os que em cada lua nova predizem o que há de vir sobre você. Que eles a ajudem!

[[v23-47-14]]

^<<v23-47-14,14>>^ Eis que serão como palha, o fogo os queimará; não poderão livrar-se do poder das chamas; nenhuma brasa restará para se aquecerem, nem fogo, para que diante dele se assentem.

[[v23-47-15]]

^<<v23-47-15,15>>^ Isso é o que lhe farão aqueles com quem você se fatigou, aqueles com quem negociou desde a sua mocidade: eles se dispersarão, cambaleantes, cada qual pelo seu caminho; não haverá ninguém para salvá-la."

'''

xref:023-isaias/023-isaias-046.adoc#v23-46-0[&#60; Capítulo Anterior] | <<v23-47-0,Topo>> | xref:023-isaias/023-isaias-048.adoc#v23-48-0[Próximo Capítulo &#62;]