include::./index.adoc[]

[[v23-45-0]]
=== Isaías, 45
// naa ?, NAA - Nova Almeida Atualizada

[[v23-45-1]]

^<<v23-45-1,1>>^ Assim diz o Senhor  ao seu ungido, a Ciro, a quem tomo pela mão direita, para submeter as nações diante dele, para desarmar os reis, e para abrir diante dele os portões, que não se fecharão:

[[v23-45-2]]

^<<v23-45-2,2>>^ "Eu irei adiante de você, endireitarei os caminhos tortuosos, quebrarei os portões de bronze e despedaçarei as trancas de ferro.

[[v23-45-3]]

^<<v23-45-3,3>>^ Darei a você os tesouros escondidos e as riquezas encobertas, para que você saiba que eu sou o Senhor , o Deus de Israel, que o chama pelo seu nome.

[[v23-45-4]]

^<<v23-45-4,4>>^ Por amor do meu servo Jacó e de Israel, meu escolhido, eu o chamei pelo seu nome e lhe dei um título de honra, mesmo que você não me conheça."

[[v23-45-5]]

^<<v23-45-5,5>>^ "Eu sou o Senhor , e não há outro; além de mim não há Deus; eu o cingirei, mesmo que você não me conheça.

[[v23-45-6]]

^<<v23-45-6,6>>^ Para que se saiba, desde o nascente do sol até o poente, que além de mim não há outro; eu sou o Senhor , e não há outro.

[[v23-45-7]]

^<<v23-45-7,7>>^ Eu formo a luz e crio as trevas; promovo a paz e crio os conflitos; eu, o Senhor , faço todas estas coisas."

[[v23-45-8]]

^<<v23-45-8,8>>^ "Que os céus gotejem lá do alto, e as nuvens chovam justiça; que a terra se abra e produza a salvação, e juntamente com ela brote a justiça; eu, o Senhor , as criei."

[[v23-45-9]]

^<<v23-45-9,9>>^ Ai daquele que discute com o seu Criador, sendo um simples caco entre outros cacos de barro! Será que o barro pergunta ao oleiro: "O que você está fazendo?" Ou diz: "Este seu vaso não tem alça!"

[[v23-45-10]]

^<<v23-45-10,10>>^ Ai daquele que diz ao seu pai: "Por que você gerou?" E à sua mãe: "Por que você deu à luz?"

[[v23-45-11]]

^<<v23-45-11,11>>^ Assim diz o Senhor , o Santo de Israel, que formou o seu povo: "Por acaso vocês querem saber as coisas futuras? Querem dar ordens a respeito de meus filhos e a respeito das obras das minhas mãos?

[[v23-45-12]]

^<<v23-45-12,12>>^ Eu fiz a terra e criei nela o ser humano; as minhas mãos estenderam os céus, e a todos os seus exércitos dei as minhas ordens.

[[v23-45-13]]

^<<v23-45-13,13>>^ Eu, na minha justiça, suscitei Ciro e endireitarei todos os seus caminhos. Ele reconstruirá a minha cidade e libertará os meus exilados, não por preço nem por presentes", diz o Senhor  dos Exércitos.

[[v23-45-14]]

^<<v23-45-14,14>>^ Assim diz o Senhor : "A riqueza do Egito, as mercadorias da Etiópia e os sabeus, homens de grande estatura, lhe serão entregues e serão seus. Eles o seguirão, presos com correntes, se prostrarão diante de você e lhe farão as suas súplicas, dizendo: ‘Certamente Deus está com você, e não há outro que seja Deus.’"

[[v23-45-15]]

^<<v23-45-15,15>>^ Verdadeiramente tu és um Deus que se esconde, ó Deus de Israel, ó Salvador.

[[v23-45-16]]

^<<v23-45-16,16>>^ Ficarão envergonhados e serão humilhados todos os que fabricam ídolos; juntos ficarão cobertos de vergonha.

[[v23-45-17]]

^<<v23-45-17,17>>^ Israel, porém, será salvo pelo Senhor com salvação eterna; vocês não serão envergonhados nem humilhados, por toda a eternidade.

[[v23-45-18]]

^<<v23-45-18,18>>^ Porque assim diz o Senhor , que criou os céus — e ele é o único Deus; que formou a terra e a fez — ele a estabeleceu; ele não a criou para ser um caos, mas para ser habitada: "Eu sou o Senhor , e não há outro.

[[v23-45-19]]

^<<v23-45-19,19>>^ Não falei em segredo, nem em algum lugar escuro da terra; eu não disse à descendência de Jacó: ‘Busquem-me em vão’; eu, o Senhor , falo a verdade e proclamo o que é direito."

[[v23-45-20]]

^<<v23-45-20,20>>^ "Reúnam-se e venham; aproximem-se todos juntos, vocês que escaparam das nações. Não sabem nada os que carregam as suas imagens de madeira e fazem súplicas a um deus que não pode salvar.

[[v23-45-21]]

^<<v23-45-21,21>>^ Declarem e apresentem as suas razões. Que tomem conselho uns com os outros. Quem fez ouvir isto desde a antiguidade? Quem desde aquele tempo o anunciou? Será que não fui eu, o Senhor ? Pois não há outro Deus, além de mim, Deus justo e Salvador não há além de mim."

[[v23-45-22]]

^<<v23-45-22,22>>^ "Voltem-se para mim e sejam salvos, vocês, todos os confins da terra; porque eu sou Deus, e não há outro.

[[v23-45-23]]

^<<v23-45-23,23>>^ Por mim mesmo tenho jurado; da minha boca saiu o que é justo, e a minha palavra não tornará atrás. Diante de mim se dobrará todo joelho, e jurará toda língua.

[[v23-45-24]]

^<<v23-45-24,24>>^ De mim se dirá: ‘Tão somente no Senhor há justiça e força.’ Até ele virão e serão envergonhados todos os que se irritarem contra ele.

[[v23-45-25]]

^<<v23-45-25,25>>^ Mas no Senhor  será justificada toda a descendência de Israel e nele se gloriará."

'''

xref:023-isaias/023-isaias-044.adoc#v23-44-0[&#60; Capítulo Anterior] | <<v23-45-0,Topo>> | xref:023-isaias/023-isaias-046.adoc#v23-46-0[Próximo Capítulo &#62;]