include::./index.adoc[]

[[v23-13-0]]
=== Isaías, 13
// naa ?, NAA - Nova Almeida Atualizada

[[v23-13-1]]

^<<v23-13-1,1>>^ Sentença contra a Babilônia que Isaías, filho de Amoz, recebeu numa visão.

[[v23-13-2]]

^<<v23-13-2,2>>^ Sobre um monte escalvado, levantem um estandarte. Ergam a voz para eles, acenem com a mão, para que entrem pelos portões dos príncipes.

[[v23-13-3]]

^<<v23-13-3,3>>^ Eu dei ordens aos meus consagrados, sim, chamei os meus valentes, os que exultam com a minha majestade, para que executem a minha ira.

[[v23-13-4]]

^<<v23-13-4,4>>^ Já se ouve sobre os montes um rumor como o de uma grande multidão, o clamor de reinos e de nações já congregados. O Senhor  dos Exércitos reúne as tropas de guerra.

[[v23-13-5]]

^<<v23-13-5,5>>^ Eles vêm de um país remoto, desde a extremidade dos céus: é o Senhor  e os instrumentos da sua indignação, para destruir toda a terra.

[[v23-13-6]]

^<<v23-13-6,6>>^ Lamentem, pois o Dia do Senhor está perto; ele vem como destruição da parte do Todo-Poderoso.

[[v23-13-7]]

^<<v23-13-7,7>>^ Por isso, todas as mãos desfalecerão, e o coração de todos se derreterá.

[[v23-13-8]]

^<<v23-13-8,8>>^ Ficarão apavorados; angústia e dores tomarão conta deles, e se contorcerão qual mulher que está dando à luz. Olharão espantados uns para os outros, com os rostos da cor do fogo.

[[v23-13-9]]

^<<v23-13-9,9>>^ Eis que vem o Dia do Senhor , dia cruel, com ira e ardente furor, para fazer da terra uma desolação e exterminar dela os pecadores.

[[v23-13-10]]

^<<v23-13-10,10>>^ Porque as estrelas e constelações dos céus não darão a sua luz; o sol, logo ao nascer, se escurecerá, e a lua não fará resplandecer a sua luz.

[[v23-13-11]]

^<<v23-13-11,11>>^ "Castigarei o mundo por causa da sua maldade, e os perversos, por causa da sua iniquidade. Farei cessar a arrogância dos atrevidos e abaterei o orgulho dos violentos.

[[v23-13-12]]

^<<v23-13-12,12>>^ Farei com que as pessoas sejam mais escassas do que o ouro puro, mais raras do que o ouro de Ofir.

[[v23-13-13]]

^<<v23-13-13,13>>^ Portanto, farei estremecer os céus, e a terra será sacudida do seu lugar, por causa da ira do Senhor  dos Exércitos e por causa do dia do seu ardente furor."

[[v23-13-14]]

^<<v23-13-14,14>>^ "Cada um será como a gazela que foge e como o rebanho que ninguém recolhe; cada um voltará para o seu povo e cada um fugirá para a sua terra.

[[v23-13-15]]

^<<v23-13-15,15>>^ Quem for achado será traspassado, e aquele que for apanhado será morto à espada.

[[v23-13-16]]

^<<v23-13-16,16>>^ As crianças serão esmagadas diante dos olhos deles; as casas serão saqueadas, e as mulheres deles, violentadas."

[[v23-13-17]]

^<<v23-13-17,17>>^ "Eis que contra os babilônios eu despertarei os medos, que não farão caso de prata, nem se alegrarão com ouro.

[[v23-13-18]]

^<<v23-13-18,18>>^ As suas flechas matarão os jovens; eles não se compadecerão dos recém-nascidos, e os seus olhos não pouparão as crianças.

[[v23-13-19]]

^<<v23-13-19,19>>^ Babilônia, a joia dos reinos, glória e orgulho dos caldeus, será como Sodoma e Gomorra, quando Deus as destruiu.

[[v23-13-20]]

^<<v23-13-20,20>>^ Nunca mais será habitada, ninguém morará nela de geração em geração. Os árabes não armarão ali as suas tendas, e os pastores não levarão para lá os seus rebanhos.

[[v23-13-21]]

^<<v23-13-21,21>>^ Porém, nela, os animais do deserto repousarão, e as suas casas se encherão de corujas. Ali habitarão os avestruzes, e os bodes selvagens pularão ali.

[[v23-13-22]]

^<<v23-13-22,22>>^ As hienas uivarão nos seus castelos; os chacais, nos seus palácios de prazer. A hora da Babilônia está chegando, e os seus dias não serão prolongados."

'''

xref:023-isaias/023-isaias-012.adoc#v23-12-0[&#60; Capítulo Anterior] | <<v23-13-0,Topo>> | xref:023-isaias/023-isaias-014.adoc#v23-14-0[Próximo Capítulo &#62;]