include::./index.adoc[]

[[v23-22-0]]
=== Isaías, 22
// naa ?, NAA - Nova Almeida Atualizada

[[v23-22-1]]

^<<v23-22-1,1>>^ Sentença contra o vale da Visão. O que aconteceu, para que todo o seu povo esteja subindo aos terraços?

[[v23-22-2]]

^<<v23-22-2,2>>^ Você estava cheia de aclamações, era uma cidade barulhenta, cidade cheia de alegria! Os seus mortos não foram mortos à espada, nem morreram na guerra.

[[v23-22-3]]

^<<v23-22-3,3>>^ Todos os seus chefes fugiram na mesma hora e foram presos sem que fosse atirada uma só flecha. Todos os moradores que foram encontrados foram presos, apesar de já estarem longe na fuga.

[[v23-22-4]]

^<<v23-22-4,4>>^ Portanto, digo: "Não olhem para mim; deixem-me chorar amargamente. Não insistam em querer consolar-me por causa da ruína da filha do meu povo."

[[v23-22-5]]

^<<v23-22-5,5>>^ Porque este é um dia de tumulto, pisoteamento e alvoroço da parte do Senhor, o Senhor  dos Exércitos, no vale da Visão: um derrubar de muralhas e um clamor que vai até os montes.

[[v23-22-6]]

^<<v23-22-6,6>>^ Porque Elão pegou a sua aljava e vem com carros de guerra e cavaleiros; e Quir prepara os escudos.

[[v23-22-7]]

^<<v23-22-7,7>>^ Os seus formosos vales se encheram de carros de guerra, e os cavaleiros se posicionaram junto ao portão.

[[v23-22-8]]

^<<v23-22-8,8>>^ Foi-se a proteção de Judá. Naquele dia, vocês olharam para as armas da Casa do Bosque.

[[v23-22-9]]

^<<v23-22-9,9>>^ Notaram as brechas da Cidade de Davi, que eram muitas, e ajuntaram água no tanque inferior.

[[v23-22-10]]

^<<v23-22-10,10>>^ Também contaram as casas de Jerusalém e derrubaram algumas delas, para reforçar a muralha.

[[v23-22-11]]

^<<v23-22-11,11>>^ Também construíram um reservatório entre as duas muralhas para as águas do tanque velho. Mas vocês não olharam para aquele que fez essas coisas, nem levaram em conta aquele que há muito as formou.

[[v23-22-12]]

^<<v23-22-12,12>>^ Naquele dia, o Senhor, o Senhor  dos Exércitos, os convidava para chorar, prantear, rapar a cabeça e vestir roupa feita de pano de saco.

[[v23-22-13]]

^<<v23-22-13,13>>^ Porém, o que se viu era só festa e alegria. Vocês mataram bois, degolaram ovelhas, comeram carne, beberam vinho e disseram: "Comamos e bebamos, porque amanhã morreremos."

[[v23-22-14]]

^<<v23-22-14,14>>^ Mas o Senhor  dos Exércitos me revelou o seguinte: "Certamente essa maldade não será perdoada, até que vocês morram, diz o Senhor, o Senhor  dos Exércitos."

[[v23-22-15]]

^<<v23-22-15,15>>^ Assim diz o Senhor, o Senhor  dos Exércitos: — Vá falar com esse administrador, com Sebna, o responsável pelo palácio, e pergunte-lhe:

[[v23-22-16]]

^<<v23-22-16,16>>^ "O que você está fazendo aqui? Ou que parente você tem aqui, para que abra aqui uma sepultura para você, lavrando num lugar elevado a sua sepultura, escavando na rocha a sua própria morada?

[[v23-22-17]]

^<<v23-22-17,17>>^ Eis que como homem forte o Senhor  vai jogar você para bem longe. Ele o pegará com firmeza

[[v23-22-18]]

^<<v23-22-18,18>>^ e o fará rolar como uma bola, lançando-o numa terra espaçosa. Ali você morrerá, e ali acabarão os carros da sua glória. Pois você é a vergonha da casa do seu senhor.

[[v23-22-19]]

^<<v23-22-19,19>>^ Eu vou removê-lo do seu ofício, e você será derrubado da sua posição."

[[v23-22-20]]

^<<v23-22-20,20>>^ — Naquele dia, chamarei o meu servo Eliaquim, filho de Hilquias.

[[v23-22-21]]

^<<v23-22-21,21>>^ Eu o vestirei com a túnica que você usava, irei cingi-lo com a faixa que era sua e lhe entregarei nas mãos o poder que você tinha. Ele será como um pai para os moradores de Jerusalém e para a casa de Judá.

[[v23-22-22]]

^<<v23-22-22,22>>^ Porei sobre o ombro dele a chave da casa de Davi. Ele abrirá, e ninguém fechará; fechará, e ninguém abrirá.

[[v23-22-23]]

^<<v23-22-23,23>>^ Vou fincá-lo como estaca em lugar firme, e ele será como um trono de honra para a casa de seu pai.

[[v23-22-24]]

^<<v23-22-24,24>>^ Nele, pendurarão toda a glória da casa de seu pai, a prole e os descendentes, todos os utensílios menores, desde as taças até os jarros.

[[v23-22-25]]

^<<v23-22-25,25>>^ Naquele dia, diz o Senhor  dos Exércitos, a estaca que tinha sido fincada em lugar firme será tirada, será arrancada e cairá, e a carga que nela estava se desprenderá, porque o Senhor  o disse.

'''

xref:023-isaias/023-isaias-021.adoc#v23-21-0[&#60; Capítulo Anterior] | <<v23-22-0,Topo>> | xref:023-isaias/023-isaias-023.adoc#v23-23-0[Próximo Capítulo &#62;]