include::./index.adoc[]

[[v23-62-0]]
=== Isaías, 62
// naa ?, NAA - Nova Almeida Atualizada

[[v23-62-1]]

^<<v23-62-1,1>>^ Por amor de Sião, não me calarei e, por amor de Jerusalém, não me aquietarei, até que a sua justiça saia como um resplendor, e a sua salvação, como uma tocha acesa.

[[v23-62-2]]

^<<v23-62-2,2>>^ As nações verão a sua justiça, ó Jerusalém, e todos os reis contemplarão a sua glória; e você será chamada por um nome novo, que a boca do Senhor  designará.

[[v23-62-3]]

^<<v23-62-3,3>>^ Você será uma coroa de glória na mão do Senhor , um diadema real na mão do seu Deus.

[[v23-62-4]]

^<<v23-62-4,4>>^ Nunca mais a chamarão de "Abandonada", e a sua terra não será mais chamada de "Arrasada". Você será chamada de "Minha Delícia", e a sua terra, de "Casada", porque o Senhor  se delicia em você, e a sua terra se casará.

[[v23-62-5]]

^<<v23-62-5,5>>^ Porque, como o jovem se casa com a moça, assim os seus filhos se casarão com você; como o noivo se alegra com a noiva, assim o seu Deus se alegrará com você.

[[v23-62-6]]

^<<v23-62-6,6>>^ Sobre as suas muralhas, ó Jerusalém, pus guardas, que jamais se calarão, nem de dia nem de noite. Vocês, que farão com que o Senhor  se lembre, não descansem,

[[v23-62-7]]

^<<v23-62-7,7>>^ nem deem a ele descanso até que restabeleça Jerusalém e a ponha por objeto de louvor na terra.

[[v23-62-8]]

^<<v23-62-8,8>>^ O Senhor  jurou pela sua mão direita e pelo seu braço poderoso: "Nunca mais darei o seu cereal como alimento para os seus inimigos, nem os estrangeiros beberão o seu vinho, que você produziu com tanto trabalho.

[[v23-62-9]]

^<<v23-62-9,9>>^ Mas aqueles que ajuntam o cereal serão os que o comerão, louvando o Senhor ; e os que recolhem as uvas beberão o vinho nos átrios do meu santuário."

[[v23-62-10]]

^<<v23-62-10,10>>^ Passem, passem pelas portas! Preparem o caminho para o povo! Aterrem, aterrem a estrada, tirem as pedras, levantem um estandarte para os povos.

[[v23-62-11]]

^<<v23-62-11,11>>^ Eis que o Senhor  fez ouvir até os confins da terra estas palavras: "Digam à filha de Sião: Eis que vem o seu Salvador; com ele vem a sua recompensa, e diante dele vem o seu galardão."

[[v23-62-12]]

^<<v23-62-12,12>>^ Eles serão chamados de "Povo Santo", "Remidos do Senhor ", e você, Jerusalém, será chamada de "Procurada", "Cidade Não Abandonada".

'''

xref:023-isaias/023-isaias-061.adoc#v23-61-0[&#60; Capítulo Anterior] | <<v23-62-0,Topo>> | xref:023-isaias/023-isaias-063.adoc#v23-63-0[Próximo Capítulo &#62;]