include::./index.adoc[]

[[v23-2-0]]
=== Isaías, 2
// naa ?, NAA - Nova Almeida Atualizada

[[v23-2-1]]

^<<v23-2-1,1>>^ Palavra que, em visão, veio a Isaías, filho de Amoz, a respeito de Judá e Jerusalém.

[[v23-2-2]]

^<<v23-2-2,2>>^ Nos últimos dias, o monte do templo do Senhor será estabelecido no alto dos montes e se elevará sobre as colinas, e para ele afluirão todas as nações.

[[v23-2-3]]

^<<v23-2-3,3>>^ Muitos povos virão e dirão: "Venham, subamos ao monte do Senhor e ao templo do Deus de Jacó, para que nos ensine os seus caminhos, e andemos nas suas veredas." Porque de Sião sairá a lei, e a palavra do Senhor , de Jerusalém.

[[v23-2-4]]

^<<v23-2-4,4>>^ Ele julgará entre as nações e corrigirá muitos povos. Estes transformarão as suas espadas em lâminas de arados e as suas lanças, em foices. Nação não levantará a espada contra nação, nem aprenderão mais a guerra.

[[v23-2-5]]

^<<v23-2-5,5>>^ Venham, ó casa de Jacó, e andemos na luz do Senhor .

[[v23-2-6]]

^<<v23-2-6,6>>^ Pois, tu, Senhor , abandonaste o teu povo, a casa de Jacó. Porque eles se encheram da corrupção do Oriente, são adivinhos como os filisteus e se associam com os filhos dos estrangeiros.

[[v23-2-7]]

^<<v23-2-7,7>>^ A terra de Israel está cheia de prata e de ouro, e não têm fim os seus tesouros. Também está cheia de cavalos, e são incontáveis os seus carros de guerra.

[[v23-2-8]]

^<<v23-2-8,8>>^ A terra de Israel também está cheia de ídolos. Eles adoram a obra das suas mãos, aquilo que os seus próprios dedos fizeram.

[[v23-2-9]]

^<<v23-2-9,9>>^ Com isso, o povo se abate e as pessoas se humilham. Não os perdoes, ó Senhor !

[[v23-2-10]]

^<<v23-2-10,10>>^ Entre no meio das rochas e esconda-se no pó, ante o terror do Senhor e a glória da sua majestade.

[[v23-2-11]]

^<<v23-2-11,11>>^ Os olhos arrogantes serão abatidos, e a soberba humana será humilhada; só o Senhor  será exaltado naquele dia.

[[v23-2-12]]

^<<v23-2-12,12>>^ Porque o Dia do Senhor dos Exércitos será contra todos os orgulhosos e arrogantes e contra todos os que se exaltam, para que sejam humilhados;

[[v23-2-13]]

^<<v23-2-13,13>>^ contra todos os cedros do Líbano, altos e imponentes; e contra todos os carvalhos de Basã;

[[v23-2-14]]

^<<v23-2-14,14>>^ contra todos os montes altos e contra todas as colinas elevadas;

[[v23-2-15]]

^<<v23-2-15,15>>^ contra toda torre alta e contra toda muralha firme;

[[v23-2-16]]

^<<v23-2-16,16>>^ contra todos os navios de Társis e contra tudo o que é belo à vista.

[[v23-2-17]]

^<<v23-2-17,17>>^ A arrogância das pessoas será abatida, e a soberba humana será humilhada; só o Senhor  será exaltado naquele dia.

[[v23-2-18]]

^<<v23-2-18,18>>^ Os ídolos serão totalmente destruídos.

[[v23-2-19]]

^<<v23-2-19,19>>^ Então as pessoas se meterão nas cavernas das rochas e nos buracos da terra, ante o terror do Senhor  e a glória da sua majestade, quando ele se levantar para encher a terra de espanto.

[[v23-2-20]]

^<<v23-2-20,20>>^ Naquele dia, as pessoas lançarão aos ratos e aos morcegos os seus ídolos de prata e os seus ídolos de ouro, que fizeram para adorar,

[[v23-2-21]]

^<<v23-2-21,21>>^ e entrarão nas fendas das rochas e nas cavernas dos penhascos, para fugir do terror do Senhor e da glória da sua majestade, quando ele se levantar para encher a terra de espanto.

[[v23-2-22]]

^<<v23-2-22,22>>^ Afastem-se, pois, do ser humano, que só tem vida enquanto respira. Pois em que ele deve ser estimado?

'''

xref:023-isaias/023-isaias-001.adoc#v23-1-0[&#60; Capítulo Anterior] | <<v23-2-0,Topo>> | xref:023-isaias/023-isaias-003.adoc#v23-3-0[Próximo Capítulo &#62;]