include::./index.adoc[]

[[v23-5-0]]
=== Isaías, 5
// naa ?, NAA - Nova Almeida Atualizada

[[v23-5-1]]

^<<v23-5-1,1>>^ Agora cantarei ao meu amado o seu cântico a respeito da sua vinha. O meu amado teve uma vinha numa colina fértil.

[[v23-5-2]]

^<<v23-5-2,2>>^ Ele cavou a terra, tirou as pedras e plantou as melhores mudas de videira. No meio da vinha ele construiu uma torre e fez também um lagar. Ele esperava que desse uvas boas, mas deu uvas bravas.

[[v23-5-3]]

^<<v23-5-3,3>>^ "E agora, ó moradores de Jerusalém e homens de Judá, peço que julguem entre mim e a minha vinha.

[[v23-5-4]]

^<<v23-5-4,4>>^ Que mais se podia fazer à minha vinha, que eu não lhe tenha feito? E como, esperando eu que desse uvas boas, veio a produzir uvas bravas?"

[[v23-5-5]]

^<<v23-5-5,5>>^ "E agora lhes darei a conhecer o que pretendo fazer com a minha vinha: vou tirar a cerca que está ao redor, para que a vinha sirva de pasto; derrubarei o seu muro, para que ela seja pisoteada.

[[v23-5-6]]

^<<v23-5-6,6>>^ Farei dela um lugar abandonado; não será podada, nem cavada, mas crescerão nela espinheiros e ervas daninhas. Também darei ordem às nuvens para que não derramem chuva sobre ela."

[[v23-5-7]]

^<<v23-5-7,7>>^ Porque a vinha do Senhor  dos Exércitos é a casa de Israel, e os homens de Judá são a planta preferida do Senhor . Este esperava retidão, mas eis aí opressão; esperava justiça, mas eis aí clamor por causa da injustiça.

[[v23-5-8]]

^<<v23-5-8,8>>^ Ai dos que ajuntam casas e mais casas, reúnem para si campos e mais campos, até que não haja mais lugar, e ficam como únicos moradores no meio da terra!

[[v23-5-9]]

^<<v23-5-9,9>>^ Eu ouvi o Senhor  dos Exércitos dizer isto: "Na verdade, muitas casas ficarão desertas, até as grandes e belas ficarão sem moradores.

[[v23-5-10]]

^<<v23-5-10,10>>^ Uma grande vinha produzirá somente alguns litros de vinho, e um saco cheio de semente não dará mais do que alguns quilos de trigo."

[[v23-5-11]]

^<<v23-5-11,11>>^ Ai dos que se levantam pela manhã para logo se embriagarem, e continuam até alta noite, até que o vinho os esquente!

[[v23-5-12]]

^<<v23-5-12,12>>^ Liras e harpas, tamborins e flautas — e vinho — não faltam nos seus banquetes; porém não consideram os feitos do Senhor , nem olham para as obras das suas mãos.

[[v23-5-13]]

^<<v23-5-13,13>>^ Portanto, o meu povo será levado cativo por falta de entendimento; os seus nobres passarão fome, e o povo simples morrerá de sede.

[[v23-5-14]]

^<<v23-5-14,14>>^ Por isso, a sepultura aumentou o seu apetite e abriu ao máximo a sua boca. Para lá desce o esplendor de Jerusalém e a sua multidão, o seu ruído e os que nela se alegram.

[[v23-5-15]]

^<<v23-5-15,15>>^ Então o povo será abatido e as pessoas se humilharão; e os olhos dos orgulhosos serão humilhados.

[[v23-5-16]]

^<<v23-5-16,16>>^ Mas o Senhor  dos Exércitos será exaltado em juízo; Deus, o Santo, será santificado em justiça.

[[v23-5-17]]

^<<v23-5-17,17>>^ Então os cordeiros pastarão ali como se estivessem no seu pasto; e os nômades se nutrirão dos campos que os ricos deixaram abandonados.

[[v23-5-18]]

^<<v23-5-18,18>>^ Ai dos que puxam para si a iniquidade com cordões de injustiça, que puxam o pecado como se faz com as cordas de uma carroça!

[[v23-5-19]]

^<<v23-5-19,19>>^ E dizem: "Que Deus se apresse e termine logo a sua obra, para que a vejamos! Que se aproxime e se manifeste o conselho do Santo de Israel, para que o conheçamos!"

[[v23-5-20]]

^<<v23-5-20,20>>^ Ai dos que ao mal chamam bem e ao bem chamam mal; que fazem das trevas luz e da luz fazem trevas; que mudam o amargo em doce e o doce mudam em amargo!

[[v23-5-21]]

^<<v23-5-21,21>>^ Ai dos que são sábios aos seus próprios olhos e inteligentes em seu próprio conceito!

[[v23-5-22]]

^<<v23-5-22,22>>^ Ai dos que são heróis para beber vinho e valentes para misturar bebida forte;

[[v23-5-23]]

^<<v23-5-23,23>>^ que por suborno justificam o ímpio, mas ao justo negam justiça!

[[v23-5-24]]

^<<v23-5-24,24>>^ Portanto, assim como as labaredas consomem a palha, e a erva seca se desfaz pela chama, assim a raiz deles será como podridão, e a flor deles subirá como pó; porque rejeitaram a lei do Senhor  dos Exércitos e desprezaram a palavra do Santo de Israel.

[[v23-5-25]]

^<<v23-5-25,25>>^ Por isso, a ira do Senhor se acendeu contra o seu povo, povo contra o qual estendeu a mão e ao qual castigou. Os montes tremeram e os seus cadáveres são como lixo no meio das ruas. Nem com tudo isto se desviou a ira de Deus, e a mão dele continua estendida.

[[v23-5-26]]

^<<v23-5-26,26>>^ Ele levantará um estandarte para as nações distantes e lhes assobiará para que venham das extremidades da terra; e eis que elas vêm rapidamente, com toda pressa.

[[v23-5-27]]

^<<v23-5-27,27>>^ Não há entre elas quem esteja cansado, nem quem tropece; ninguém dormita, nem dorme. Eles não desatam o cinto dos seus lombos, e as correias das suas sandálias não se rompem.

[[v23-5-28]]

^<<v23-5-28,28>>^ As suas flechas são afiadas, e todos os seus arcos, entesados. Os cascos dos seus cavalos são duros como pedra, e as rodas dos seus carros de guerra são como um redemoinho.

[[v23-5-29]]

^<<v23-5-29,29>>^ O rugido deles é como o do leão; rugem como filhos de leão, e, rosnando, arrebatam a presa e a levam, e não há quem a livre.

[[v23-5-30]]

^<<v23-5-30,30>>^ Naquele dia, o bramido contra eles será como o bramido do mar; se alguém olhar para a terra, eis que só haverá trevas e angústia; a luz se escurecerá em densas nuvens.

'''

xref:023-isaias/023-isaias-004.adoc#v23-4-0[&#60; Capítulo Anterior] | <<v23-5-0,Topo>> | xref:023-isaias/023-isaias-006.adoc#v23-6-0[Próximo Capítulo &#62;]