include::./index.adoc[]

[[v23-35-0]]
=== Isaías, 35
// naa ?, NAA - Nova Almeida Atualizada

[[v23-35-1]]

^<<v23-35-1,1>>^ O deserto e a terra seca se alegrarão; o ermo exultará e florescerá como o narciso.

[[v23-35-2]]

^<<v23-35-2,2>>^ Ele se cobrirá de flores, dará gritos de alegria e exultará. Receberá a glória do Líbano, o esplendor do Carmelo e de Sarom. Eles verão a glória do Senhor , o esplendor do nosso Deus.

[[v23-35-3]]

^<<v23-35-3,3>>^ Fortaleçam as mãos frouxas e firmem os joelhos vacilantes.

[[v23-35-4]]

^<<v23-35-4,4>>^ Digam aos desalentados de coração: "Sejam fortes, não tenham medo. Eis aí está o Deus de vocês. A vingança vem, a retribuição de Deus; ele vem para salvar vocês."

[[v23-35-5]]

^<<v23-35-5,5>>^ Então se abrirão os olhos dos cegos, e se desimpedirão os ouvidos dos surdos;

[[v23-35-6]]

^<<v23-35-6,6>>^ os coxos saltarão como as corças, e a língua dos mudos cantará. Pois águas arrebentarão no deserto, e ribeiros, no ermo.

[[v23-35-7]]

^<<v23-35-7,7>>^ A areia escaldante se transformará em lagos, e a terra seca, em mananciais de água. Onde os chacais costumavam viver, crescerá a erva com canas e juncos.

[[v23-35-8]]

^<<v23-35-8,8>>^ E ali haverá uma estrada, um caminho que será chamado de Caminho Santo. Os impuros não passarão por ele, pois será somente para o povo de Deus. Quem passar por esse caminho, mesmo que seja um tolo, não se perderá.

[[v23-35-9]]

^<<v23-35-9,9>>^ Ali não haverá leão; nenhum animal feroz passará por ele nem será encontrado nele; mas os remidos andarão por esse caminho.

[[v23-35-10]]

^<<v23-35-10,10>>^ Os resgatados do Senhor voltarão e virão a Sião com cânticos de júbilo. Alegria eterna coroará a sua cabeça. Ficarão tomados de júbilo e alegria, e deles fugirão a tristeza e o gemido.

'''

xref:023-isaias/023-isaias-034.adoc#v23-34-0[&#60; Capítulo Anterior] | <<v23-35-0,Topo>> | xref:023-isaias/023-isaias-036.adoc#v23-36-0[Próximo Capítulo &#62;]