include::./index.adoc[]

[[v23-50-0]]
=== Isaías, 50
// naa ?, NAA - Nova Almeida Atualizada

[[v23-50-1]]

^<<v23-50-1,1>>^ Assim diz o Senhor : "Onde está a carta de divórcio que eu entreguei à mãe de vocês e com a qual eu a repudiei? Ou quem é o meu credor, a quem eu os vendi? Eis que vocês foram vendidos por causa das suas iniquidades, e a mãe de vocês foi repudiada por causa das transgressões de vocês.

[[v23-50-2]]

^<<v23-50-2,2>>^ Por que razão, quando eu vim, ninguém apareceu? Quando chamei, ninguém respondeu? Será que a minha mão se encolheu tanto, que já não pode remir? Ou será que já não há força em mim para livrar? Eis que pela minha repreensão eu seco o mar e transformo os rios em deserto, até que os seus peixes cheirem mal; pois, não havendo água, morrem de sede.

[[v23-50-3]]

^<<v23-50-3,3>>^ Posso vestir os céus de escuridão e cobri-los com pano de saco."

[[v23-50-4]]

^<<v23-50-4,4>>^ O Senhor  Deus me deu uma língua erudita, para que eu saiba dizer boa palavra ao cansado. Ele me desperta todas as manhãs; desperta o meu ouvido para que eu ouça como aqueles que aprendem.

[[v23-50-5]]

^<<v23-50-5,5>>^ O Senhor  Deus me abriu os ouvidos, e eu não fui rebelde nem me retraí.

[[v23-50-6]]

^<<v23-50-6,6>>^ Ofereci as costas aos que me batiam e o rosto aos que me arrancavam a barba; não escondi o rosto dos que me afrontavam e cuspiam em mim.

[[v23-50-7]]

^<<v23-50-7,7>>^ Porque o Senhor  Deus me ajuda. Por isso, não serei humilhado; por isso, fiz o meu rosto como uma pedra e sei que não serei envergonhado.

[[v23-50-8]]

^<<v23-50-8,8>>^ Perto está o que me justifica. Quem ousará entrar em litígio comigo? Compareçamos juntos diante do juiz! Quem é o meu adversário? Que se aproxime de mim!

[[v23-50-9]]

^<<v23-50-9,9>>^ Eis que o Senhor  Deus me ajuda. Quem poderá me condenar? Eis que todos eles envelhecerão como a roupa; a traça os comerá.

[[v23-50-10]]

^<<v23-50-10,10>>^ Quem de vocês teme o Senhor e ouve a voz do seu Servo? Aquele que anda em trevas, sem nenhuma luz, confie no nome do Senhor e se firme sobre o seu Deus.

[[v23-50-11]]

^<<v23-50-11,11>>^ Todos vocês que acendem fogo e se armam com flechas incendiárias, andem entre as labaredas do fogo de vocês e entre as flechas que vocês acenderam! De mim lhes sobrevirá isto: vocês se deitarão em tormentos.

'''

xref:023-isaias/023-isaias-049.adoc#v23-49-0[&#60; Capítulo Anterior] | <<v23-50-0,Topo>> | xref:023-isaias/023-isaias-051.adoc#v23-51-0[Próximo Capítulo &#62;]