include::./index.adoc[]

[[v23-23-0]]
=== Isaías, 23
// naa ?, NAA - Nova Almeida Atualizada

[[v23-23-1]]

^<<v23-23-1,1>>^ Sentença contra Tiro. Lamentem, navios de Társis, porque Tiro foi destruída, a ponto de não haver nela casa nenhuma, nem ancoradouro. Da terra de Chipre lhes foi revelado isto.

[[v23-23-2]]

^<<v23-23-2,2>>^ Calem-se, moradores do litoral, vocês que foram enriquecidos pelos mercadores de Sidom, navegando pelo mar.

[[v23-23-3]]

^<<v23-23-3,3>>^ Através das vastas águas, você recebeu o cereal dos canais do Egito e a colheita do Nilo, e você, ó Tiro, se tornou a feira das nações.

[[v23-23-4]]

^<<v23-23-4,4>>^ Fique envergonhada, ó Sidom, porque o mar, a fortaleza do mar, fala, dizendo: "Não tive dores de parto, não dei à luz, não criei rapazes, nem eduquei moças."

[[v23-23-5]]

^<<v23-23-5,5>>^ Quando a notícia a respeito de Tiro chegar ao Egito, eles ficarão angustiados.

[[v23-23-6]]

^<<v23-23-6,6>>^ Fujam para Társis! Lamentem, moradores do litoral.

[[v23-23-7]]

^<<v23-23-7,7>>^ É esta a cidade de vocês que andava exultante, cuja origem é de tempos antigos, cujos pés a levaram até longe para se estabelecer?

[[v23-23-8]]

^<<v23-23-8,8>>^ Quem decretou isso contra Tiro, a cidade distribuidora de coroas, cujos mercadores são príncipes e cujos negociantes são os mais nobres da terra?

[[v23-23-9]]

^<<v23-23-9,9>>^ O Senhor  dos Exércitos decretou isso, para abater o orgulho de toda beleza e humilhar os mais nobres da terra.

[[v23-23-10]]

^<<v23-23-10,10>>^ Percorra livremente como o rio Nilo a sua terra, ó filha de Társis; já não há quem a restrinja.

[[v23-23-11]]

^<<v23-23-11,11>>^ O Senhor  estendeu a mão sobre o mar e abalou os reinos; deu ordens contra Canaã, para que as suas fortalezas fossem destruídas.

[[v23-23-12]]

^<<v23-23-12,12>>^ Ele disse: "Nunca mais você irá se alegrar, ó oprimida virgem filha de Sidom! Levante-se, vá até Chipre, mas nem ali você terá descanso."

[[v23-23-13]]

^<<v23-23-13,13>>^ Eis a terra dos caldeus, povo que não existe mais e que a Assíria havia destinado para os animais do deserto. Eles levantaram suas torres, arrasaram os palácios de Tiro e a deixaram em ruínas.

[[v23-23-14]]

^<<v23-23-14,14>>^ Lamentem, navios de Társis, porque aquela que era a fortaleza de vocês foi destruída!

[[v23-23-15]]

^<<v23-23-15,15>>^ Naquele dia, Tiro ficará no esquecimento por setenta anos, o tempo de vida de um rei. Mas no fim dos setenta anos acontecerá com Tiro o que diz a canção da prostituta:

[[v23-23-16]]

^<<v23-23-16,16>>^ "Pegue a harpa, rodeie a cidade, ó prostituta esquecida; toque bem, cante muitas canções, para que se lembrem de você."

[[v23-23-17]]

^<<v23-23-17,17>>^ Passados os setenta anos, o Senhor  se lembrará de Tiro, e ela voltará ao seu ofício e se prostituirá com todos os reinos da terra.

[[v23-23-18]]

^<<v23-23-18,18>>^ O ganho e o salário de sua impureza serão dedicados ao Senhor . Não serão armazenados, nem guardados, mas o seu ganho será para os que habitam diante do Senhor , para que tenham comida em abundância e roupas finas.

'''

xref:023-isaias/023-isaias-022.adoc#v23-22-0[&#60; Capítulo Anterior] | <<v23-23-0,Topo>> | xref:023-isaias/023-isaias-024.adoc#v23-24-0[Próximo Capítulo &#62;]