include::./index.adoc[]

[[v23-31-0]]
=== Isaías, 31
// naa ?, NAA - Nova Almeida Atualizada

[[v23-31-1]]

^<<v23-31-1,1>>^ Ai dos que descem ao Egito em busca de socorro e se estribam em cavalos! Eles confiam em carros de guerra, porque são muitos, e em cavaleiros, porque são fortes, mas não olham para o Santo de Israel, nem buscam o Senhor .

[[v23-31-2]]

^<<v23-31-2,2>>^ Porém o Senhor  também é sábio e faz vir a desgraça; ele não volta atrás naquilo que falou. Ele se levantará contra a casa dos malfeitores e contra os que ajudam os que praticam o mal.

[[v23-31-3]]

^<<v23-31-3,3>>^ Pois os egípcios são homens e não deuses; os seus cavalos são carne, e não espírito. Quando o Senhor  estender a mão, tropeçará aquele que ajuda e cairá quem é ajudado; e juntos todos perecerão.

[[v23-31-4]]

^<<v23-31-4,4>>^ Porque assim me disse o Senhor : "Como o leão e o filhote do leão rugem sobre a sua presa e, ainda que se convoque contra eles grande número de pastores, não se espantam com o barulho nem se apavoram com os gritos desses pastores, assim o Senhor  dos Exércitos descerá para lutar sobre o monte Sião e sobre a sua colina.

[[v23-31-5]]

^<<v23-31-5,5>>^ Como uma ave paira sobre o seu ninho, assim o Senhor  dos Exércitos defenderá Jerusalém; ele a defenderá e salvará, poupará e livrará."

[[v23-31-6]]

^<<v23-31-6,6>>^ Ó filhos de Israel, voltem-se para aquele contra quem vocês se rebelaram tão profundamente.

[[v23-31-7]]

^<<v23-31-7,7>>^ Pois, naquele dia, cada um de vocês jogará fora os ídolos de prata e os ídolos de ouro que as suas mãos pecaminosas fabricaram.

[[v23-31-8]]

^<<v23-31-8,8>>^ "A Assíria cairá pela espada, não de homem; a espada, não de um ser humano, a destruirá. A Assíria fugirá diante da espada, e os seus jovens serão sujeitos a trabalhos forçados.

[[v23-31-9]]

^<<v23-31-9,9>>^ De medo não enxergará a sua rocha de refúgio; os seus príncipes, apavorados, desertarão a bandeira", diz o Senhor , cujo fogo está em Sião e cuja fornalha está em Jerusalém.

'''

xref:023-isaias/023-isaias-030.adoc#v23-30-0[&#60; Capítulo Anterior] | <<v23-31-0,Topo>> | xref:023-isaias/023-isaias-032.adoc#v23-32-0[Próximo Capítulo &#62;]