include::./index.adoc[]

[[v23-16-0]]
=== Isaías, 16
// naa ?, NAA - Nova Almeida Atualizada

[[v23-16-1]]

^<<v23-16-1,1>>^ Enviem cordeiros ao dominador da terra, desde Sela, pelo deserto, até o monte da filha de Sião.

[[v23-16-2]]

^<<v23-16-2,2>>^ Como pássaro espantado, lançado fora do ninho, assim são as filhas de Moabe nos vaus do rio Arnom. Elas dizem a Judá:

[[v23-16-3]]

^<<v23-16-3,3>>^ "Dê-nos um conselho, tome uma decisão. Faça com que, em pleno meio-dia, a sua sombra seja como noite para nós. Esconda os desterrados e não revele onde estão os fugitivos.

[[v23-16-4]]

^<<v23-16-4,4>>^ Que os desterrados de Moabe possam morar em seu território; sirva-lhes de esconderijo contra o destruidor." Quando o homem violento tiver fim, a destruição for desfeita e o opressor deixar a terra,

[[v23-16-5]]

^<<v23-16-5,5>>^ então um trono será estabelecido em bondade, e sobre ele se assentará com fidelidade, no tabernáculo de Davi, alguém que julgue, busque o juízo e não tarde em fazer justiça.

[[v23-16-6]]

^<<v23-16-6,6>>^ Ouvimos falar da soberba de Moabe, que de fato é extremamente soberbo. Ouvimos falar da sua arrogância, do seu orgulho e do seu furor; mas todo esse seu orgulho é vão.

[[v23-16-7]]

^<<v23-16-7,7>>^ Por isso, Moabe pranteará por Moabe; todos prantearão. Profundamente abatidos, hão de suspirar pelos bolos de passas de Quir-Haresete.

[[v23-16-8]]

^<<v23-16-8,8>>^ Porque os campos de Hesbom estão murchos; os senhores das nações destruíram os melhores ramos da vinha de Sibma, que se estendiam até Jazer e se perdiam no deserto, ramos que se estendiam e passavam além do mar.

[[v23-16-9]]

^<<v23-16-9,9>>^ Por isso, prantearei, com o pranto de Jazer, pela vinha de Sibma. Eu as regarei com as minhas lágrimas, ó Hesbom e Eleale, pois sobre os seus frutos de verão e sobre a sua colheita já caiu o "eia" dos inimigos.

[[v23-16-10]]

^<<v23-16-10,10>>^ Fugiu a alegria e o regozijo dos pomares; nas vinhas já não se canta, nem há júbilo algum. Já não se pisam as uvas nos lagares; eu fiz cessar o "eia" dos pisadores.

[[v23-16-11]]

^<<v23-16-11,11>>^ Por isso, o meu íntimo vibra por Moabe como se fosse harpa, e o meu coração estremece por Quir-Heres.

[[v23-16-12]]

^<<v23-16-12,12>>^ Quando Moabe se apresentar e se cansar nos lugares altos, quando entrar no seu santuário para orar, nada alcançará.

[[v23-16-13]]

^<<v23-16-13,13>>^ Esta é a palavra que o Senhor  há muito pronunciou contra Moabe.

[[v23-16-14]]

^<<v23-16-14,14>>^ Agora, porém, o Senhor  diz: — Daqui a exatamente três anos, será humilhada a glória de Moabe, com toda a sua grande multidão; e o resto que ficar será pouco, pequeno e fraco.

'''

xref:023-isaias/023-isaias-015.adoc#v23-15-0[&#60; Capítulo Anterior] | <<v23-16-0,Topo>> | xref:023-isaias/023-isaias-017.adoc#v23-17-0[Próximo Capítulo &#62;]