include::./index.adoc[]

[[v23-54-0]]
=== Isaías, 54
// naa ?, NAA - Nova Almeida Atualizada

[[v23-54-1]]

^<<v23-54-1,1>>^ "Cante, ó estéril, você que não deu à luz; exulte e grite de alegria, você que nunca sentiu dores de parto! Porque os filhos da mulher solitária são mais numerosos do que os filhos da casada", diz o Senhor .

[[v23-54-2]]

^<<v23-54-2,2>>^ "Alargue o espaço de sua tenda e aumente o toldo de sua habitação; não o impeça; alongue as cordas e firme bem as estacas.

[[v23-54-3]]

^<<v23-54-3,3>>^ Porque você se expandirá para a direita e para a esquerda; a sua posteridade possuirá as nações e fará com que se povoem as cidades arrasadas."

[[v23-54-4]]

^<<v23-54-4,4>>^ "Não tenha medo, porque você não será envergonhada; não tenha vergonha, porque você não sofrerá humilhação. Você se esquecerá da vergonha da sua mocidade e não mais se lembrará da desgraça da sua viuvez.

[[v23-54-5]]

^<<v23-54-5,5>>^ Porque o seu Criador é o seu marido; Senhor  dos Exércitos é o seu nome. O Santo de Israel é o seu Redentor; ele é chamado ‘O Deus de toda a terra’."

[[v23-54-6]]

^<<v23-54-6,6>>^ "Porque o Senhor  chamou você como se chama a mulher abandonada e de espírito abatido, como se chama a mulher da mocidade, que havia sido repudiada, diz o seu Deus.

[[v23-54-7]]

^<<v23-54-7,7>>^ Por um breve momento abandonei você, mas com grande misericórdia tornarei a acolhê-la.

[[v23-54-8]]

^<<v23-54-8,8>>^ Num ímpeto de indignação, escondi de você a minha face por um momento, mas com misericórdia eterna me compadeço de você", diz o Senhor , o seu Redentor.

[[v23-54-9]]

^<<v23-54-9,9>>^ "Porque isto é para mim como as águas de Noé: como jurei que as águas de Noé não mais inundariam a terra, assim jurei que não mais ficaria irado com você, nem a repreenderia.

[[v23-54-10]]

^<<v23-54-10,10>>^ Mesmo que os montes se retirem e as colinas sejam removidas, a minha misericórdia não se afastará de você, e a minha aliança de paz não será removida", diz o Senhor , que se compadece de você.

[[v23-54-11]]

^<<v23-54-11,11>>^ "Ó cidade aflita, sacudida pela tormenta e desconsolada! Eis que eu assentarei as suas pedras com argamassa colorida e lançarei os seus alicerces sobre safiras.

[[v23-54-12]]

^<<v23-54-12,12>>^ As suas torres serão de rubis, os seus portões serão de esmeraldas e toda a sua muralha será de pedras preciosas.

[[v23-54-13]]

^<<v23-54-13,13>>^ Todos os seus filhos serão ensinados pelo Senhor , e será grande a paz de seus filhos.

[[v23-54-14]]

^<<v23-54-14,14>>^ Você será estabelecida em justiça. Ficará longe da opressão, porque não temerá; ficará longe do terror, porque ele não chegará perto de você.

[[v23-54-15]]

^<<v23-54-15,15>>^ Se alguém a atacar, isso não procederá de mim; mas quem a atacar cairá diante de você."

[[v23-54-16]]

^<<v23-54-16,16>>^ "Eis que eu criei o ferreiro, que assopra as brasas no fogo e que produz a arma para o seu devido fim; eu criei também o destruidor, para trazer a ruína.

[[v23-54-17]]

^<<v23-54-17,17>>^ Nenhuma arma forjada contra você prosperará; e você condenará toda língua que quiser acusá-la em juízo. Esta é a herança dos servos do Senhor e a sua justiça que procede de mim", diz o Senhor .

'''

xref:023-isaias/023-isaias-053.adoc#v23-53-0[&#60; Capítulo Anterior] | <<v23-54-0,Topo>> | xref:023-isaias/023-isaias-055.adoc#v23-55-0[Próximo Capítulo &#62;]