include::./index.adoc[]

[[v23-40-0]]
=== Isaías, 40
// naa ?, NAA - Nova Almeida Atualizada

[[v23-40-1]]

^<<v23-40-1,1>>^ "Consolem, consolem o meu povo", diz o Deus de vocês.

[[v23-40-2]]

^<<v23-40-2,2>>^ "Falem ao coração de Jerusalém e anunciem que o tempo da sua escravidão já acabou, que a sua iniquidade está perdoada e que ela já recebeu em dobro das mãos do Senhor por todos os seus pecados."

[[v23-40-3]]

^<<v23-40-3,3>>^ Uma voz clama: "No deserto preparem o caminho do Senhor ! No ermo façam uma estrada reta para o nosso Deus!

[[v23-40-4]]

^<<v23-40-4,4>>^ Todos os vales serão levantados, e todos os montes e colinas serão rebaixados; o que é tortuoso será retificado, e os lugares ásperos serão aplanados.

[[v23-40-5]]

^<<v23-40-5,5>>^ A glória do Senhor se manifestará, e toda a humanidade a verá, pois a boca do Senhor  o disse."

[[v23-40-6]]

^<<v23-40-6,6>>^ Uma voz diz: "Proclame!" E alguém pergunta: "Que hei de proclamar?" Toda a humanidade é erva, e toda a sua glória é como a flor do campo.

[[v23-40-7]]

^<<v23-40-7,7>>^ A erva seca e as flores caem, soprando nelas o hálito do Senhor . Na verdade, o povo é erva.

[[v23-40-8]]

^<<v23-40-8,8>>^ A erva seca e as flores caem, mas a palavra do nosso Deus permanece para sempre.

[[v23-40-9]]

^<<v23-40-9,9>>^ Ó Sião, você que anuncia boas-novas, suba a um alto monte! Ó Jerusalém, você que anuncia boas-novas, levante a sua voz fortemente! Levante-a, não tenha medo. Diga às cidades de Judá: "Eis aí está o seu Deus!"

[[v23-40-10]]

^<<v23-40-10,10>>^ Eis que o Senhor  Deus virá com poder, e o seu braço dominará; eis que o seu galardão está com ele, e diante dele vem a sua recompensa.

[[v23-40-11]]

^<<v23-40-11,11>>^ Como pastor, ele apascentará o seu rebanho; entre os seus braços recolherá os cordeirinhos e os carregará no colo; as que amamentam ele guiará mansamente.

[[v23-40-12]]

^<<v23-40-12,12>>^ Quem na concha de sua mão mediu as águas e tomou a medida dos céus a palmos? Quem recolheu o pó da terra na terça parte de uma vasilha e pesou os montes e as colinas numa balança?

[[v23-40-13]]

^<<v23-40-13,13>>^ Quem guiou o Espírito do Senhor ? Ou, como seu conselheiro, o ensinou?

[[v23-40-14]]

^<<v23-40-14,14>>^ Com quem ele se aconselhou, para que lhe desse compreensão? Quem lhe ensinou a vereda da justiça ou quem lhe ensinou sabedoria? E quem lhe mostrou o caminho de entendimento?

[[v23-40-15]]

^<<v23-40-15,15>>^ Eis que as nações são consideradas por ele como um pingo que cai de um balde e como um grão de pó na balança; eis que ele carrega as ilhas como se fossem pó fino.

[[v23-40-16]]

^<<v23-40-16,16>>^ O Líbano não seria suficiente para o fogo, e os animais de lá não bastariam para um holocausto.

[[v23-40-17]]

^<<v23-40-17,17>>^ Diante dele, todas as nações são como coisa que não é nada; ele as considera menos do que nada, como um vácuo.

[[v23-40-18]]

^<<v23-40-18,18>>^ Com quem vocês querem comparar Deus? Com que imagem vocês o podem confrontar?

[[v23-40-19]]

^<<v23-40-19,19>>^ Quanto à imagem, esta é moldada pelo artífice; depois, o ourives a reveste de ouro e forja correntes de prata para ela.

[[v23-40-20]]

^<<v23-40-20,20>>^ O pobre, que não pode fazer tal oferta, escolhe madeira que não apodrece e procura um artífice perito para fazer uma imagem esculpida que não oscile.

[[v23-40-21]]

^<<v23-40-21,21>>^ Será que vocês não sabem? Será que não ouviram? Será que isso não lhes foi anunciado desde o princípio? Vocês não entenderam isso desde a fundação do mundo? Vocês não atentaram para os fundamentos da terra?

[[v23-40-22]]

^<<v23-40-22,22>>^ Ele é o que está assentado sobre a cúpula da terra, cujos moradores são como gafanhotos. É ele quem estende os céus como cortina e os desenrola como tenda para neles habitar.

[[v23-40-23]]

^<<v23-40-23,23>>^ É ele quem reduz a nada os príncipes e torna em nulidade os juízes da terra.

[[v23-40-24]]

^<<v23-40-24,24>>^ Mal foram plantados e semeados, mal se arraigou na terra o seu tronco, já secam, quando um sopro passa por eles, e uma tempestade os leva como palha.

[[v23-40-25]]

^<<v23-40-25,25>>^ "Com quem vocês vão me comparar? A quem eu seria igual?" — diz o Santo.

[[v23-40-26]]

^<<v23-40-26,26>>^ Levantem os olhos para o alto e vejam. Quem criou estas coisas? Aquele que faz sair o seu exército de estrelas, todas bem-contadas, as quais ele chama pelo nome; por ser ele grande em força e forte em poder, nem uma só vem a faltar.

[[v23-40-27]]

^<<v23-40-27,27>>^ Por que, então, você diz, ó Jacó, e você fala, ó Israel: "O meu caminho está encoberto ao Senhor , e o meu direito passa despercebido ao meu Deus"?

[[v23-40-28]]

^<<v23-40-28,28>>^ Será que você não sabe, nem ouviu que o eterno Deus, o Senhor , o Criador dos confins da terra, nem se cansa, nem se fatiga? A sabedoria dele é insondável.

[[v23-40-29]]

^<<v23-40-29,29>>^ Ele fortalece o cansado e multiplica as forças ao que não tem nenhum vigor.

[[v23-40-30]]

^<<v23-40-30,30>>^ Os jovens se cansam e se fatigam, e os moços, de exaustos, caem,

[[v23-40-31]]

^<<v23-40-31,31>>^ mas os que esperam no Senhor renovam as suas forças, sobem com asas como águias, correm e não se cansam, caminham e não se fatigam.

'''

xref:023-isaias/023-isaias-039.adoc#v23-39-0[&#60; Capítulo Anterior] | <<v23-40-0,Topo>> | xref:023-isaias/023-isaias-041.adoc#v23-41-0[Próximo Capítulo &#62;]