include::./index.adoc[]

[[v23-15-0]]
=== Isaías, 15
// naa ?, NAA - Nova Almeida Atualizada

[[v23-15-1]]

^<<v23-15-1,1>>^ Sentença contra Moabe. Certamente numa noite Ar de Moabe foi arrasada, e ela está destruída; certamente numa noite Quir de Moabe foi arrasada, e ela está destruída.

[[v23-15-2]]

^<<v23-15-2,2>>^ Sobe-se ao templo e a Dibom, aos lugares altos, para chorar. Por Nebo e por Medeba, Moabe lamenta; todas as cabeças são rapadas, e toda barba é cortada.

[[v23-15-3]]

^<<v23-15-3,3>>^ Nas ruas andam vestidos de panos de saco; nos terraços e nas praças todos pranteiam, desatando-se em lágrimas.

[[v23-15-4]]

^<<v23-15-4,4>>^ Tanto Hesbom como Eleale andam gritando; até Jaza se ouve a sua voz. Por isso, os soldados de Moabe clamam; a sua alma treme dentro deles.

[[v23-15-5]]

^<<v23-15-5,5>>^ O meu coração clama por causa de Moabe. Os seus fugitivos vão até a região de Zoar e Eglate-Selisia; vão chorando pela subida de Luíte e no caminho de Horonaim levantam gritos de desespero.

[[v23-15-6]]

^<<v23-15-6,6>>^ Porque as águas de Ninrim desapareceram; seca-se o pasto, acaba-se o capim, e não há mais nada que esteja verde.

[[v23-15-7]]

^<<v23-15-7,7>>^ Por isso, eles mesmos levam a riqueza que adquiriram e guardaram para além do ribeiro dos Salgueiros.

[[v23-15-8]]

^<<v23-15-8,8>>^ Porque o pranto se espalha pelo território de Moabe; o seu clamor chega até Eglaim; o clamor chega até Beer-Elim.

[[v23-15-9]]

^<<v23-15-9,9>>^ As águas de Dimom estão cheias de sangue, mas trarei ainda mais sobre Dimom: um leão para atacar aqueles que escaparem de Moabe e os que permanecerem na terra.

'''

xref:023-isaias/023-isaias-014.adoc#v23-14-0[&#60; Capítulo Anterior] | <<v23-15-0,Topo>> | xref:023-isaias/023-isaias-016.adoc#v23-16-0[Próximo Capítulo &#62;]