include::./index.adoc[]

[[v23-52-0]]
=== Isaías, 52
// naa ?, NAA - Nova Almeida Atualizada

[[v23-52-1]]

^<<v23-52-1,1>>^ Acorde! Acorde, ó Sião, e revista-se de força! Vista as suas roupas finas, ó Jerusalém, cidade santa, porque os incircuncisos e imundos nunca mais entrarão em você.

[[v23-52-2]]

^<<v23-52-2,2>>^ Levante e sacuda a poeira, ó Jerusalém cativa; livre-se das correntes de seu pescoço, ó cativa filha de Sião.

[[v23-52-3]]

^<<v23-52-3,3>>^ Porque assim diz o Senhor : — Por nada vocês foram vendidos, e sem dinheiro serão resgatados.

[[v23-52-4]]

^<<v23-52-4,4>>^ Porque assim diz o Senhor  Deus: — O meu povo no princípio desceu ao Egito, para nele habitar, e a Assíria sem razão o oprimiu.

[[v23-52-5]]

^<<v23-52-5,5>>^ Agora, que farei eu aqui, diz o Senhor , pois o meu povo foi levado por nada? Os seus opressores dão uivos, diz o Senhor , e o meu nome é blasfemado todo o dia, sem cessar.

[[v23-52-6]]

^<<v23-52-6,6>>^ Por isso, o meu povo saberá o meu nome; por isso, naquele dia, saberá que sou eu quem diz: "Eis-me aqui."

[[v23-52-7]]

^<<v23-52-7,7>>^ Quão formosos são sobre os montes os pés do que anuncia boas-novas, que faz ouvir a paz, que anuncia coisas boas, que faz ouvir a salvação, que diz a Sião: "O seu Deus reina!"

[[v23-52-8]]

^<<v23-52-8,8>>^ Eis o grito dos seus atalaias! Eles erguem a voz e juntos gritam de alegria, porque com os seus próprios olhos veem o retorno do Senhor  a Sião.

[[v23-52-9]]

^<<v23-52-9,9>>^ Gritem de alegria e juntas exultem, ó ruínas de Jerusalém, porque o Senhor  consolou o seu povo; ele remiu Jerusalém.

[[v23-52-10]]

^<<v23-52-10,10>>^ O Senhor  desnudou o seu santo braço à vista de todas as nações, e todos os confins da terra verão a salvação do nosso Deus.

[[v23-52-11]]

^<<v23-52-11,11>>^ Fora! Fora! Saiam de lá! Não toquem em coisa impura! Saiam do meio dela, purifiquem-se, vocês que levam os utensílios do Senhor .

[[v23-52-12]]

^<<v23-52-12,12>>^ Porque vocês não sairão às pressas, nem partirão como quem foge. Porque o Senhor  irá adiante de vocês, e o Deus de Israel será a sua retaguarda.

[[v23-52-13]]

^<<v23-52-13,13>>^ "Eis que o meu Servo procederá com prudência; será exaltado e elevado, e será mui sublime.

[[v23-52-14]]

^<<v23-52-14,14>>^ Como muitos pasmaram à vista dele — pois o seu aspecto estava tão desfigurado, mais do que o de outro qualquer, e a sua aparência, mais do que a dos outros filhos dos homens —,

[[v23-52-15]]

^<<v23-52-15,15>>^ assim causará admiração às nações, e os reis fecharão a sua boca por causa dele. Porque verão aquilo que não lhes foi anunciado, e entenderão aquilo que não tinham ouvido."

'''

xref:023-isaias/023-isaias-051.adoc#v23-51-0[&#60; Capítulo Anterior] | <<v23-52-0,Topo>> | xref:023-isaias/023-isaias-053.adoc#v23-53-0[Próximo Capítulo &#62;]