include::./index.adoc[]

[[v23-58-0]]
=== Isaías, 58
// naa ?, NAA - Nova Almeida Atualizada

[[v23-58-1]]

^<<v23-58-1,1>>^ "Grite a plenos pulmões, não se detenha! Erga a voz como a trombeta e anuncie ao meu povo a sua transgressão e à casa de Jacó, os seus pecados.

[[v23-58-2]]

^<<v23-58-2,2>>^ Mesmo neste estado, ainda me procuram dia a dia, têm prazer em saber os meus caminhos. Como povo que pratica a justiça e não deixa o direito do seu Deus, perguntam-me por sentenças justas, têm prazer em se aproximar de Deus,

[[v23-58-3]]

^<<v23-58-3,3>>^ dizendo: ‘Por que jejuamos, se tu nem notas? Por que nos humilhamos, se tu não levas isso em conta?’ Acontece que, no dia em que jejuam, vocês cuidam dos seus próprios interesses e oprimem os seus trabalhadores.

[[v23-58-4]]

^<<v23-58-4,4>>^ Eis que vocês jejuam apenas para discutir, brigar e bater uns nos outros; jejuando assim como hoje, o clamor de vocês não será ouvido lá no alto.

[[v23-58-5]]

^<<v23-58-5,5>>^ Seria este o jejum que escolhi: que num só dia a pessoa se humilhe, incline a sua cabeça como o junco e estenda debaixo de si pano de saco e cinza? É isso o que vocês chamam de jejum e dia aceitável ao Senhor ?

[[v23-58-6]]

^<<v23-58-6,6>>^ Será que não é este o jejum que escolhi: que vocês quebrem as correntes da injustiça, desfaçam as ataduras da servidão, deixem livres os oprimidos e acabem com todo tipo de servidão?

[[v23-58-7]]

^<<v23-58-7,7>>^ Será que não é também que vocês repartam o seu pão com os famintos, recolham em casa os pobres desabrigados, vistam os que encontrarem nus e não voltem as costas ao seu semelhante?"

[[v23-58-8]]

^<<v23-58-8,8>>^ "Então a luz de vocês romperá como a luz do alvorecer, e a sua cura brotará sem demora; a justiça irá adiante de vocês, e a glória do Senhor será a sua retaguarda.

[[v23-58-9]]

^<<v23-58-9,9>>^ Então vocês pedirão ajuda, e o Senhor  responderá; gritarão por socorro, e ele dirá: ‘Eis-me aqui.’" "Se tirarem do meio de vocês todo tipo de servidão, o dedo que ameaça e a linguagem ofensiva;

[[v23-58-10]]

^<<v23-58-10,10>>^ se abrirem o seu coração aos famintos e socorrerem os aflitos, então a luz de vocês nascerá nas trevas, e a escuridão em que vocês se encontram será como a luz do meio-dia.

[[v23-58-11]]

^<<v23-58-11,11>>^ O Senhor  os guiará continuamente, lhes dará de comer até em lugares áridos e fortalecerá os seus ossos. Vocês serão como um jardim regado e como um manancial cujas águas nunca secam.

[[v23-58-12]]

^<<v23-58-12,12>>^ Vocês reconstruirão as antigas ruínas, levantarão os fundamentos de muitas gerações e serão chamados de ‘Reparadores de brechas’ e ‘Restauradores de veredas’, para que o país se torne habitável."

[[v23-58-13]]

^<<v23-58-13,13>>^ "Se vigiarem os seus pés, para não profanarem o sábado; se deixarem de cuidar dos seus próprios interesses no meu santo dia; se chamarem ao sábado de ‘meu prazer’ e ‘santo dia do Senhor , digno de honra’; se guardarem o sábado, não seguindo os seus próprios caminhos, não pretendendo fazer a sua própria vontade, nem falando palavras vãs,

[[v23-58-14]]

^<<v23-58-14,14>>^ então vocês terão no Senhor a sua fonte de alegria. Eu os farei cavalgar sobre os altos da terra e os sustentarei com a herança de Jacó, seu pai. Porque a boca do Senhor  o disse."

'''

xref:023-isaias/023-isaias-057.adoc#v23-57-0[&#60; Capítulo Anterior] | <<v23-58-0,Topo>> | xref:023-isaias/023-isaias-059.adoc#v23-59-0[Próximo Capítulo &#62;]