include::./index.adoc[]

[[v23-37-0]]
=== Isaías, 37
// naa ?, NAA - Nova Almeida Atualizada

[[v23-37-1]]

^<<v23-37-1,1>>^ Quando o rei Ezequias ouviu isto, rasgou as suas roupas, cobriu-se de pano de saco e entrou na Casa do Senhor .

[[v23-37-2]]

^<<v23-37-2,2>>^ Então ele mandou que Eliaquim, o responsável pelo palácio, Sebna, o escrivão, e os anciãos dos sacerdotes, todos vestidos de pano de saco, fossem falar com o profeta Isaías, filho de Amoz.

[[v23-37-3]]

^<<v23-37-3,3>>^ Eles lhe disseram: — Assim diz Ezequias: "Este dia é dia de angústia, de castigo e de vergonha. Como se costuma dizer, chegou a hora de a criança nascer, mas a mãe não tem forças para dar à luz.

[[v23-37-4]]

^<<v23-37-4,4>>^ É bem possível que o Senhor , seu Deus, tenha ouvido as palavras de Rabsaqué, a quem o rei da Assíria, seu senhor, enviou para afrontar o Deus vivo, e repreenda as palavras que ouviu. Portanto, ore pelo resto que ficou."

[[v23-37-5]]

^<<v23-37-5,5>>^ Os servos do rei Ezequias foram falar com Isaías,

[[v23-37-6]]

^<<v23-37-6,6>>^ que lhes disse: — Digam ao rei o seguinte: Assim diz o Senhor : "Não tenha medo por causa das palavras que você ouviu, com as quais os servos do rei da Assíria blasfemaram contra mim.

[[v23-37-7]]

^<<v23-37-7,7>>^ Eis que porei nele um espírito, e ele, ao ouvir certo rumor, voltará para a sua terra; e lá eu farei com que ele seja morto à espada."

[[v23-37-8]]

^<<v23-37-8,8>>^ Rabsaqué voltou e encontrou o rei da Assíria lutando contra Libna, pois tinha ouvido que o rei já se havia retirado de Laquis.

[[v23-37-9]]

^<<v23-37-9,9>>^ Quando o rei ouviu dizer que Tiraca, rei da Etiópia, havia saído para guerrear contra ele, mandou mensageiros a Ezequias, com esta missão:

[[v23-37-10]]

^<<v23-37-10,10>>^ — Digam a Ezequias, rei de Judá: "Não deixe que o seu Deus, em quem você confia, o engane, ao dizer: ‘Jerusalém não será entregue nas mãos do rei da Assíria.’

[[v23-37-11]]

^<<v23-37-11,11>>^ Você já ouviu o que os reis da Assíria fizeram com todas as terras, como as destruíram totalmente. E você pensa que poderá escapar?

[[v23-37-12]]

^<<v23-37-12,12>>^ Será que os deuses das nações livraram os povos que os meus pais destruíram, Gozã, Harã e Rezefe e os filhos de Éden, que estavam em Telassar?

[[v23-37-13]]

^<<v23-37-13,13>>^ Onde está o rei de Hamate, o rei de Arpade, e o rei da cidade de Sefarvaim, de Hena e de Iva?"

[[v23-37-14]]

^<<v23-37-14,14>>^ Ezequias recebeu a carta das mãos dos mensageiros e a leu. Então Ezequias subiu à Casa do Senhor  e estendeu a carta diante do Senhor .

[[v23-37-15]]

^<<v23-37-15,15>>^ E Ezequias orou ao Senhor , dizendo:

[[v23-37-16]]

^<<v23-37-16,16>>^ — Ó Senhor  dos Exércitos, Deus de Israel, que estás entronizado acima dos querubins, somente tu és o Deus de todos os reinos da terra; tu fizeste os céus e a terra.

[[v23-37-17]]

^<<v23-37-17,17>>^ Inclina, ó Senhor , os ouvidos e ouve; abre, Senhor , os olhos e vê; ouve todas as palavras de Senaqueribe, as quais ele enviou para afrontar o Deus vivo.

[[v23-37-18]]

^<<v23-37-18,18>>^ É verdade, Senhor , que os reis da Assíria assolaram todos os países e suas terras

[[v23-37-19]]

^<<v23-37-19,19>>^ e lançaram no fogo os deuses deles, porque não eram deuses, mas objetos de madeira e pedra, feitos por mãos humanas; por isso, os destruíram.

[[v23-37-20]]

^<<v23-37-20,20>>^ Agora, ó Senhor , nosso Deus, livra-nos das mãos dele, para que todos os reinos da terra saibam que só tu és o Senhor .

[[v23-37-21]]

^<<v23-37-21,21>>^ Então Isaías, filho de Amoz, mandou dizer a Ezequias: — Assim diz o Senhor , o Deus de Israel: Visto que você fez uma oração a respeito de Senaqueribe, rei da Assíria,

[[v23-37-22]]

^<<v23-37-22,22>>^ esta é a palavra que o Senhor  falou a respeito dele: "A virgem, a filha de Sião, desdenha e zomba de você; a filha de Jerusalém meneia a cabeça atrás de você.

[[v23-37-23]]

^<<v23-37-23,23>>^ A quem você afrontou e de quem blasfemou? E contra quem você levantou a voz e ergueu os olhos com arrogância? Contra o Santo de Israel.

[[v23-37-24]]

^<<v23-37-24,24>>^ Por meio dos seus servos, você afrontou o Senhor e disse: ‘Com a multidão dos meus carros de guerra eu subi ao alto dos montes, ao mais interior do Líbano. Cortei os seus altos cedros e os seus melhores ciprestes; cheguei ao lugar mais elevado, ao seu denso bosque.

[[v23-37-25]]

^<<v23-37-25,25>>^ Eu mesmo cavei e bebi as águas e com as plantas de meus pés sequei todos os rios do Egito.’"

[[v23-37-26]]

^<<v23-37-26,26>>^ "Por acaso, você não ouviu que há muito tempo eu, o Senhor , determinei estas coisas, e que já desde os dias remotos as tinha planejado? Agora eu as faço acontecer. Eu quis que você reduzisse a montões de ruínas as cidades fortificadas.

[[v23-37-27]]

^<<v23-37-27,27>>^ Por isso, os seus moradores, debilitados, andaram cheios de temor e envergonhados; tornaram-se como a erva do campo, a erva verde e o capim dos telhados queimado antes de amadurecer."

[[v23-37-28]]

^<<v23-37-28,28>>^ "Mas eu sei onde você está; conheço o seu sair e o seu entrar, e o seu furor contra mim.

[[v23-37-29]]

^<<v23-37-29,29>>^ Por causa do seu furor contra mim e porque a sua arrogância subiu até os meus ouvidos, eis que porei o meu anzol no seu nariz e o meu freio na sua boca e farei você voltar pelo caminho por onde veio."

[[v23-37-30]]

^<<v23-37-30,30>>^ — E isto será o sinal para você, rei Ezequias: neste ano, se comerá o que nascer espontaneamente e, no segundo ano, o que daí proceder. Mas no terceiro ano semeiem e colham, plantem vinhas e comam os seus frutos.

[[v23-37-31]]

^<<v23-37-31,31>>^ Aqueles da casa de Judá que escaparam e ficaram como remanescente tornarão a lançar raízes e a dar frutos.

[[v23-37-32]]

^<<v23-37-32,32>>^ Porque de Jerusalém sairá o remanescente, e do monte Sião, o que escapou. O zelo do Senhor  dos Exércitos fará isto.

[[v23-37-33]]

^<<v23-37-33,33>>^ — Portanto, assim diz o Senhor  a respeito do rei da Assíria: "Ele não entrará nesta cidade, nem lançará nela flecha alguma. Não virá diante dela com escudo, nem construirá rampas de ataque contra ela.

[[v23-37-34]]

^<<v23-37-34,34>>^ Pelo caminho por onde vier, por esse voltará; mas nesta cidade não entrará", diz o Senhor .

[[v23-37-35]]

^<<v23-37-35,35>>^ "Porque eu defenderei esta cidade, para a livrar, por amor de mim e por amor do meu servo Davi."

[[v23-37-36]]

^<<v23-37-36,36>>^ Então o Anjo do Senhor  saiu e matou cento e oitenta e cinco mil homens no arraial dos assírios. De manhã, quando os restantes se levantaram, lá estavam todos aqueles cadáveres.

[[v23-37-37]]

^<<v23-37-37,37>>^ Então Senaqueribe, rei da Assíria, levantou acampamento, foi embora, voltou para Nínive e por lá ficou.

[[v23-37-38]]

^<<v23-37-38,38>>^ Certo dia, quando ele estava adorando no templo de seu deus Nisroque, os seus filhos Adrameleque e Sarezer o mataram à espada; depois fugiram para a terra de Ararate. E Esar-Hadom, filho de Senaqueribe, reinou em seu lugar.

'''

xref:023-isaias/023-isaias-036.adoc#v23-36-0[&#60; Capítulo Anterior] | <<v23-37-0,Topo>> | xref:023-isaias/023-isaias-038.adoc#v23-38-0[Próximo Capítulo &#62;]