include::./index.adoc[]

[[v23-36-0]]
=== Isaías, 36
// naa ?, NAA - Nova Almeida Atualizada

[[v23-36-1]]

^<<v23-36-1,1>>^ No décimo quarto ano do reinado de Ezequias, Senaqueribe, rei da Assíria, atacou todas as cidades fortificadas de Judá e as conquistou.

[[v23-36-2]]

^<<v23-36-2,2>>^ O rei da Assíria, que estava em Laquis, enviou Rabsaqué, com um grande exército, a Jerusalém, ao rei Ezequias. Ele parou na extremidade do aqueduto do tanque superior, junto ao caminho do campo do Lavandeiro.

[[v23-36-3]]

^<<v23-36-3,3>>^ Quem saiu ao encontro dele foram Eliaquim, filho de Hilquias, o responsável pelo palácio, Sebna, o escrivão, e Joá, filho de Asafe, o cronista.

[[v23-36-4]]

^<<v23-36-4,4>>^ Rabsaqué disse: — Digam a Ezequias: "Assim diz o grande rei, o rei da Assíria: Que confiança é essa que você tem?

[[v23-36-5]]

^<<v23-36-5,5>>^ Bem posso dizer que o seu conselho e o seu poder para a guerra são meras palavras. Em quem você está confiando, para que se rebele contra mim?

[[v23-36-6]]

^<<v23-36-6,6>>^ Você confia nesse bordão de caniço esmagado que é o Egito. Se alguém se apoiar no caniço, ele vai espetar e furar a mão. Assim é Faraó, rei do Egito, para todos os que nele confiam.

[[v23-36-7]]

^<<v23-36-7,7>>^ Mas, se você me diz: ‘Confiamos no Senhor , nosso Deus’, eu pergunto: não é esse aquele cujos lugares altos e altares Ezequias removeu, dizendo a Judá e a Jerusalém que deveriam adorar somente diante do altar em Jerusalém?"

[[v23-36-8]]

^<<v23-36-8,8>>^ — Agora, pois, comprometa-se com meu senhor, o rei da Assíria, e eu lhe darei dois mil cavalos, se você puder achar cavaleiros para montá-los.

[[v23-36-9]]

^<<v23-36-9,9>>^ Como você poderia repelir um oficial do meu senhor, o rei, mesmo que seja um dos menores, e confiar no Egito para obter carros de guerra e cavaleiros?

[[v23-36-10]]

^<<v23-36-10,10>>^ E será que você pensa que é sem o consentimento do Senhor  Deus que eu vim contra esta terra, para a destruir? Foi o próprio Senhor  quem ordenou que eu atacasse esta terra e a destruísse.

[[v23-36-11]]

^<<v23-36-11,11>>^ Então Eliaquim, Sebna e Joá disseram a Rabsaqué: — Por favor, fale com estes seus servos em aramaico, porque nós o entendemos. Não fale em hebraico, aos ouvidos do povo que está sobre a muralha.

[[v23-36-12]]

^<<v23-36-12,12>>^ Mas Rabsaqué lhes respondeu: — Você pensa que o meu senhor me enviou para dizer estas palavras apenas a você e ao seu rei? Ele me enviou para falar também aos homens que estão sentados sobre a muralha e que, junto com vocês, terão de comer o seu próprio excremento e beber a sua própria urina!

[[v23-36-13]]

^<<v23-36-13,13>>^ Então Rabsaqué se pôs em pé e gritou em hebraico: — Escutem as palavras do grande rei, o rei da Assíria.

[[v23-36-14]]

^<<v23-36-14,14>>^ Assim diz o rei: "Não deixem que Ezequias os engane, pois ele não poderá livrá-los.

[[v23-36-15]]

^<<v23-36-15,15>>^ Não deixem que Ezequias os leve a confiar no Senhor , dizendo: ‘O Senhor  certamente nos livrará, e esta cidade não será entregue nas mãos do rei da Assíria.’

[[v23-36-16]]

^<<v23-36-16,16>>^ Não deem ouvidos a Ezequias. Porque assim diz o rei da Assíria: Façam as pazes comigo e se entreguem. Então cada um comerá da sua própria videira e da sua própria figueira, e beberá a água da sua própria cisterna,

[[v23-36-17]]

^<<v23-36-17,17>>^ até que eu venha e os leve para uma terra como a de vocês, terra de cereal e de vinho, terra de pão e de vinhas.

[[v23-36-18]]

^<<v23-36-18,18>>^ Não deixem que Ezequias os engane, dizendo: ‘O Senhor  nos livrará.’ Será que os deuses das nações puderam livrar, cada um a sua terra, das mãos do rei da Assíria?

[[v23-36-19]]

^<<v23-36-19,19>>^ Onde estão os deuses de Hamate e de Arpade? Onde estão os deuses de Sefarvaim? Será que eles livraram Samaria das minhas mãos?

[[v23-36-20]]

^<<v23-36-20,20>>^ De todos os deuses destes países, quais foram os que livraram a sua terra das minhas mãos? Então como o Senhor  poderá livrar Jerusalém das minhas mãos?"

[[v23-36-21]]

^<<v23-36-21,21>>^ Eles, porém, ficaram calados e não lhe responderam palavra, porque assim lhes havia ordenado o rei: "Não lhe respondam."

[[v23-36-22]]

^<<v23-36-22,22>>^ Então Eliaquim, filho de Hilquias, o responsável pelo palácio, e Sebna, o escrivão, e Joá, filho de Asafe, o cronista, voltaram para junto do rei Ezequias, com as suas roupas rasgadas, e lhe contaram o que Rabsaqué tinha dito.

'''

xref:023-isaias/023-isaias-035.adoc#v23-35-0[&#60; Capítulo Anterior] | <<v23-36-0,Topo>> | xref:023-isaias/023-isaias-037.adoc#v23-37-0[Próximo Capítulo &#62;]