include::./index.adoc[]

[[v23-48-0]]
=== Isaías, 48
// naa ?, NAA - Nova Almeida Atualizada

[[v23-48-1]]

^<<v23-48-1,1>>^ Escutem isto, casa de Jacó, vocês que se chamam pelo nome de Israel e saíram da linhagem de Judá, vocês que juram pelo nome do Senhor e confessam o Deus de Israel, mas não em verdade nem em justiça.

[[v23-48-2]]

^<<v23-48-2,2>>^ Da santa cidade tomam o nome e se firmam sobre o Deus de Israel, cujo nome é Senhor  dos Exércitos.

[[v23-48-3]]

^<<v23-48-3,3>>^ "Desde a antiguidade anunciei as primeiras coisas; a minha boca as pronunciou, e eu as fiz ouvir; de repente agi, e elas se cumpriram.

[[v23-48-4]]

^<<v23-48-4,4>>^ Porque eu sabia que você era obstinado, que o seu pescoço é um tendão de ferro e que a sua testa era de bronze.

[[v23-48-5]]

^<<v23-48-5,5>>^ Por isso, desde aquele tempo eu lhe anunciei essas coisas e as dei a conhecer antes que acontecessem, para que você não dissesse: ‘O meu ídolo fez estas coisas’; ou: ‘A minha imagem de escultura e a minha imagem de fundição as ordenaram.’"

[[v23-48-6]]

^<<v23-48-6,6>>^ "Você já ouviu; agora olhe bem para tudo isto; será que você não vai admitir que falei a verdade? Desde agora lhe anuncio coisas novas e ocultas, que você não conhecia.

[[v23-48-7]]

^<<v23-48-7,7>>^ Foram criadas agora e não há muito tempo, e antes deste dia você não tinha ouvido falar nelas, para que você não diga: ‘Sim, eu já sabia.’

[[v23-48-8]]

^<<v23-48-8,8>>^ Você não ouviu, não conheceu, nem tampouco antecipadamente se abriram os seus ouvidos, porque eu sabia que você não é nada confiável e é chamado de transgressor desde o ventre materno."

[[v23-48-9]]

^<<v23-48-9,9>>^ "Por amor do meu nome, retardarei a minha ira e, por causa da minha honra, me conterei em relação a você, para que eu não venha a exterminá-lo.

[[v23-48-10]]

^<<v23-48-10,10>>^ Eis que refinei você, mas não como a prata; eu o provei na fornalha da aflição.

[[v23-48-11]]

^<<v23-48-11,11>>^ Por amor de mim, por amor de mim é que faço isto; pois como seria profanado o meu nome? Não darei a mais ninguém a minha glória."

[[v23-48-12]]

^<<v23-48-12,12>>^ "Escute, ó Jacó, e também você, Israel, a quem chamei: Eu sou o mesmo, sou o primeiro e também o último.

[[v23-48-13]]

^<<v23-48-13,13>>^ Também a minha mão fundou a terra, e a minha mão direita estendeu os céus; quando eu os chamar, eles se apresentarão juntos."

[[v23-48-14]]

^<<v23-48-14,14>>^ "Reúnam-se, todos vocês, e escutem! Quem, dentre eles, anunciou estas coisas? Aquele a quem o Senhor  amou executará a sua vontade contra a Babilônia, e o seu braço será contra os caldeus.

[[v23-48-15]]

^<<v23-48-15,15>>^ Eu, eu tenho falado; também já o chamei. Eu o trouxe e farei próspero o seu caminho.

[[v23-48-16]]

^<<v23-48-16,16>>^ Aproximem-se de mim e escutem isto: desde o princípio, não falei em segredo; desde o tempo em que isso vem acontecendo, tenho estado lá." "Agora, o Senhor  Deus enviou a mim e o seu Espírito."

[[v23-48-17]]

^<<v23-48-17,17>>^ Assim diz o Senhor , o seu Redentor, o Santo de Israel: "Eu sou o Senhor , o seu Deus, que lhe ensina o que é útil e o guia pelo caminho em que você deve andar.

[[v23-48-18]]

^<<v23-48-18,18>>^ Ah! Se você tivesse dado ouvidos aos meus mandamentos! Então a sua paz seria como um rio, e a sua justiça, como as ondas do mar.

[[v23-48-19]]

^<<v23-48-19,19>>^ Também a sua posteridade seria como a areia, e os seus descendentes, como os grãos da areia; o seu nome nunca seria eliminado nem destruído de diante de mim."

[[v23-48-20]]

^<<v23-48-20,20>>^ Saiam da Babilônia, fujam do meio dos caldeus! Anunciem isto com voz de júbilo; proclamem e levem esta boa notícia até os confins da terra. Digam: "O Senhor  remiu o seu servo Jacó."

[[v23-48-21]]

^<<v23-48-21,21>>^ Não padeceram sede, quando ele os levava pelos desertos; fez brotar para eles água da rocha; fendeu a pedra, e a água jorrou.

[[v23-48-22]]

^<<v23-48-22,22>>^ "Mas para os ímpios não há paz", diz o Senhor .

'''

xref:023-isaias/023-isaias-047.adoc#v23-47-0[&#60; Capítulo Anterior] | <<v23-48-0,Topo>> | xref:023-isaias/023-isaias-049.adoc#v23-49-0[Próximo Capítulo &#62;]