include::./index.adoc[]

[[v23-60-0]]
=== Isaías, 60
// naa ?, NAA - Nova Almeida Atualizada

[[v23-60-1]]

^<<v23-60-1,1>>^ Levante-se, resplandeça, porque já vem a sua luz, e a glória do Senhor está raiando sobre você.

[[v23-60-2]]

^<<v23-60-2,2>>^ Porque eis que as trevas cobrem a terra, e a escuridão envolve os povos; mas sobre você aparece resplandecente o Senhor , e a sua glória já está brilhando sobre você.

[[v23-60-3]]

^<<v23-60-3,3>>^ As nações se encaminham para a sua luz, ó Jerusalém, e os reis são atraídos para o resplendor do seu amanhecer.

[[v23-60-4]]

^<<v23-60-4,4>>^ Levante os olhos ao redor e veja: todos se reúnem e vêm até você. Os seus filhos chegam de longe, e as suas filhas são trazidas nos braços.

[[v23-60-5]]

^<<v23-60-5,5>>^ Ao ver isso, você ficará radiante de alegria; o seu coração baterá forte e se dilatará de júbilo, porque você receberá a abundância do mar, e as riquezas das nações serão trazidas a você.

[[v23-60-6]]

^<<v23-60-6,6>>^ O seu território ficará coberto por uma multidão de camelos, os dromedários de Midiã e de Efa. Todos virão de Sabá; trarão ouro e incenso e publicarão os louvores do Senhor .

[[v23-60-7]]

^<<v23-60-7,7>>^ Todas as ovelhas de Quedar se reunirão junto de você; os carneiros de Nebaiote a servirão; serão aceitos ao serem oferecidos sobre o meu altar, e eu tornarei mais glorioso o templo da minha glória.

[[v23-60-8]]

^<<v23-60-8,8>>^ Quem são estes que vêm voando como nuvens e como pombas voltando ao pombal?

[[v23-60-9]]

^<<v23-60-9,9>>^ Certamente as terras do mar me aguardarão. À frente virão os navios de Társis para trazerem de longe os seus filhos, ó Jerusalém, e, com eles, a prata e o ouro, para a santificação do nome do Senhor , seu Deus, e do Santo de Israel, porque ele revestiu você de glória.

[[v23-60-10]]

^<<v23-60-10,10>>^ "Estrangeiros edificarão as suas muralhas, e os seus reis a servirão. Porque no meu furor eu a castiguei, mas na minha graça tive compaixão de você.

[[v23-60-11]]

^<<v23-60-11,11>>^ Os seus portões estarão sempre abertos; não serão fechados nem de dia nem de noite, para que lhe sejam trazidas as riquezas das nações, e, conduzidos com elas, os seus reis.

[[v23-60-12]]

^<<v23-60-12,12>>^ Porque a nação e o reino que não a servirem perecerão; sim, essas nações serão totalmente arrasadas."

[[v23-60-13]]

^<<v23-60-13,13>>^ "A glória do Líbano virá a você: o cipreste, o olmeiro e o buxo, conjuntamente, para adornarem o lugar do meu santuário; e farei glorioso o lugar em que descansam os meus pés.

[[v23-60-14]]

^<<v23-60-14,14>>^ Também virão e se inclinarão os filhos dos que a oprimiram; todos os que a desprezaram se prostrarão até as plantas dos seus pés e a chamarão ‘Cidade do Senhor ’, a ‘Sião do Santo de Israel’."

[[v23-60-15]]

^<<v23-60-15,15>>^ "Você era uma cidade abandonada e odiada, um lugar onde não passava ninguém, mas eu farei de você uma glória eterna, uma alegria de geração em geração.

[[v23-60-16]]

^<<v23-60-16,16>>^ Você mamará o leite das nações e se alimentará ao peito dos reis; e saberá que eu sou o Senhor , o seu Salvador, o seu Redentor, o Poderoso de Jacó."

[[v23-60-17]]

^<<v23-60-17,17>>^ "Em vez de bronze, eu lhe trarei ouro; em vez de ferro, eu lhe trarei prata; em vez de madeira, bronze, e, em vez de pedras, ferro. Farei com que a paz seja o seu inspetor e com que a justiça seja o seu opressor.

[[v23-60-18]]

^<<v23-60-18,18>>^ Nunca mais se ouvirá falar de violência na sua terra, nem de ruína ou destruição em seu território, mas às suas muralhas você chamará ‘Salvação’, e aos seus portões, ‘Louvor’."

[[v23-60-19]]

^<<v23-60-19,19>>^ "Nunca mais o sol será a sua luz durante o dia, e o resplendor da lua nunca mais a iluminará; pois o Senhor  será a sua luz perpétua, e o seu Deus será a sua glória.

[[v23-60-20]]

^<<v23-60-20,20>>^ O seu sol nunca se porá, e a sua lua nunca minguará, porque o Senhor  será a sua luz perpétua, e os dias do seu luto chegarão ao fim.

[[v23-60-21]]

^<<v23-60-21,21>>^ Todos os do seu povo serão justos e para sempre herdarão a terra; serão renovos que eu plantei, obra das minhas mãos, para que eu seja glorificado.

[[v23-60-22]]

^<<v23-60-22,22>>^ O pequeno virá a ser mil, e o menor, uma nação forte; eu, o Senhor , farei com que, no tempo certo, isso logo se cumpra."

'''

xref:023-isaias/023-isaias-059.adoc#v23-59-0[&#60; Capítulo Anterior] | <<v23-60-0,Topo>> | xref:023-isaias/023-isaias-061.adoc#v23-61-0[Próximo Capítulo &#62;]