include::./index.adoc[]

[[v23-17-0]]
=== Isaías, 17
// naa ?, NAA - Nova Almeida Atualizada

[[v23-17-1]]

^<<v23-17-1,1>>^ Sentença contra Damasco. "Eis que Damasco deixará de ser cidade e será um montão de ruínas.

[[v23-17-2]]

^<<v23-17-2,2>>^ As cidades de Aroer serão abandonadas; hão de ser para os rebanhos, que aí se deitarão sem haver quem os espante.

[[v23-17-3]]

^<<v23-17-3,3>>^ A fortaleza de Efraim desaparecerá, bem como o reino de Damasco; e o restante da Síria será como a glória dos filhos de Israel", diz o Senhor  dos Exércitos.

[[v23-17-4]]

^<<v23-17-4,4>>^ "Naquele dia, a glória de Jacó será diminuída, e a gordura da sua carne desaparecerá.

[[v23-17-5]]

^<<v23-17-5,5>>^ Será como quando o ceifeiro ajunta o trigo e com o braço colhe as espigas; será como quem colhe espigas no vale dos Refains.

[[v23-17-6]]

^<<v23-17-6,6>>^ Mas ainda ficarão algumas espigas, como no sacudir da oliveira; duas ou três azeitonas na ponta do ramo mais alto, e quatro ou cinco nos ramos mais produtivos", diz o Senhor , o Deus de Israel.

[[v23-17-7]]

^<<v23-17-7,7>>^ Naquele dia, as pessoas olharão para o seu Criador, e os seus olhos estarão voltados para o Santo de Israel.

[[v23-17-8]]

^<<v23-17-8,8>>^ Eles não olharão para os altares, obra de suas mãos, nem voltarão os olhos para o que os seus dedos fizeram, nem para os postes da deusa Aserá, nem para os altares do incenso.

[[v23-17-9]]

^<<v23-17-9,9>>^ Naquele dia, as cidades que eles fortificaram ficarão como os lugares abandonados no bosque ou no alto das montanhas, os quais no passado foram abandonados diante da chegada dos filhos de Israel, e haverá desolação.

[[v23-17-10]]

^<<v23-17-10,10>>^ Porque você se esqueceu do Deus da sua salvação e não se lembrou da Rocha da sua fortaleza. Ainda que você faça belas plantações e plante mudas de fora,

[[v23-17-11]]

^<<v23-17-11,11>>^ e, no dia em que você as plantar, as fizer crescer, e na manhã seguinte as fizer florescer, ainda assim a colheita voará no dia da tribulação e das dores incuráveis.

[[v23-17-12]]

^<<v23-17-12,12>>^ Ai do bramido dos grandes povos que bramam como bramam os mares, e do rugido das nações que rugem como rugem as águas impetuosas!

[[v23-17-13]]

^<<v23-17-13,13>>^ As nações rugem como as muitas águas, mas Deus as repreenderá, e fugirão para longe; serão afugentadas como a palha dos montes diante do vento e como pó levado pelo tufão.

[[v23-17-14]]

^<<v23-17-14,14>>^ Ao anoitecer, eis que há pavor, e, antes que amanheça o dia, já não existem. Este é o destino daqueles que nos despojam e a sorte daqueles que nos saqueiam.

'''

xref:023-isaias/023-isaias-016.adoc#v23-16-0[&#60; Capítulo Anterior] | <<v23-17-0,Topo>> | xref:023-isaias/023-isaias-018.adoc#v23-18-0[Próximo Capítulo &#62;]