include::./index.adoc[]

[[v23-7-0]]
=== Isaías, 7
// naa ?, NAA - Nova Almeida Atualizada

[[v23-7-1]]

^<<v23-7-1,1>>^ Nos dias em que Acaz, filho de Jotão, filho de Uzias, era rei de Judá, Rezim, rei da Síria, e Peca, filho de Remalias, rei de Israel, subiram a Jerusalém para lutar contra ela, mas não conseguiram conquistá-la.

[[v23-7-2]]

^<<v23-7-2,2>>^ Quando informaram à casa de Davi que a Síria estava aliada com Efraim, o coração de Acaz e o coração do seu povo ficaram agitados, como se agitam as árvores do bosque com o vento.

[[v23-7-3]]

^<<v23-7-3,3>>^ Então o Senhor  disse a Isaías: — Vá, agora, com o seu filho Sear-Jasube encontrar-se com Acaz, que está na outra extremidade do aqueduto do tanque superior, junto ao caminho do campo do Lavandeiro.

[[v23-7-4]]

^<<v23-7-4,4>>^ Diga-lhe o seguinte: "Tenha cuidado e fique calmo. Não tenha medo nem fique desanimado por causa desses dois tocos de lenha fumegante, por causa do furor da ira de Rezim e da Síria, e do filho de Remalias.

[[v23-7-5]]

^<<v23-7-5,5>>^ Porque a Síria, Efraim e o filho de Remalias resolveram acabar com você, dizendo:

[[v23-7-6]]

^<<v23-7-6,6>>^ ‘Vamos atacar e amedrontar o reino de Judá. Vamos conquistá-lo para nós e fazer reinar no meio dele o filho de Tabeal.’"

[[v23-7-7]]

^<<v23-7-7,7>>^ Assim diz o Senhor  Deus: "Isso não tem nenhuma chance de acontecer.

[[v23-7-8]]

^<<v23-7-8,8>>^ Porque a capital da Síria é Damasco, e o cabeça de Damasco é Rezim. E dentro de sessenta e cinco anos Efraim será destruído e deixará de ser povo.

[[v23-7-9]]

^<<v23-7-9,9>>^ A capital de Efraim é Samaria, e o cabeça de Samaria é o filho de Remalias. Se vocês não crerem, certamente não permanecerão."

[[v23-7-10]]

^<<v23-7-10,10>>^ E o Senhor  continuou a falar com Acaz, dizendo:

[[v23-7-11]]

^<<v23-7-11,11>>^ — Peça ao Senhor , seu Deus, um sinal, quer seja embaixo, nas profundezas, ou em cima, nas alturas.

[[v23-7-12]]

^<<v23-7-12,12>>^ Acaz, porém, disse: — Não pedirei, nem tentarei o Senhor .

[[v23-7-13]]

^<<v23-7-13,13>>^ Então Isaías disse: — Agora escute, ó casa de Davi! Será que não basta vocês abusarem da paciência dos homens? Querem abusar também da paciência do meu Deus?

[[v23-7-14]]

^<<v23-7-14,14>>^ Portanto, o Senhor mesmo lhes dará um sinal: eis que a virgem conceberá e dará à luz um filho e lhe chamará Emanuel.

[[v23-7-15]]

^<<v23-7-15,15>>^ Ele comerá manteiga e mel quando souber desprezar o mal e escolher o bem.

[[v23-7-16]]

^<<v23-7-16,16>>^ Na verdade, antes que este menino saiba desprezar o mal e escolher o bem, a terra daqueles dois reis que você tanto teme será abandonada.

[[v23-7-17]]

^<<v23-7-17,17>>^ — Mas o Senhor  fará vir sobre você, sobre o seu povo e sobre a casa de seu pai dias tais como nunca houve, desde o dia em que Efraim se separou de Judá; ele fará vir o rei da Assíria.

[[v23-7-18]]

^<<v23-7-18,18>>^ Naquele dia, o Senhor  assobiará às moscas que estão no extremo dos rios do Egito e às abelhas que se encontram na terra da Assíria.

[[v23-7-19]]

^<<v23-7-19,19>>^ Elas virão e pousarão todas nos vales profundos, nas fendas das rochas, em todos os espinhos e em todas as pastagens.

[[v23-7-20]]

^<<v23-7-20,20>>^ — Naquele dia, o Senhor o rapará com uma navalha alugada do outro lado do rio, a saber, por meio do rei da Assíria. Rapará a sua cabeça e os cabelos dos seus pés e tirará também a sua barba.

[[v23-7-21]]

^<<v23-7-21,21>>^ Naquele dia, um homem manterá apenas uma vaca nova e duas ovelhas,

[[v23-7-22]]

^<<v23-7-22,22>>^ e será tal a abundância de leite que elas lhe darão, que comerá manteiga. Todo o restante que ficar no meio da terra comerá manteiga e mel.

[[v23-7-23]]

^<<v23-7-23,23>>^ — Também, naquele dia, todo lugar em que houver mil videiras, no valor de mil moedas de prata, será tomado por espinheiros e ervas daninhas.

[[v23-7-24]]

^<<v23-7-24,24>>^ Com flechas e arco se entrará aí, porque os espinheiros e as ervas daninhas cobrirão toda a terra.

[[v23-7-25]]

^<<v23-7-25,25>>^ Quanto a todos os montes, onde se costuma cavar com enxadas, para ali você não irá com medo dos espinhos e das ervas daninhas; eles servirão para pasto dos bois e para serem pisados pelas ovelhas.

'''

xref:023-isaias/023-isaias-006.adoc#v23-6-0[&#60; Capítulo Anterior] | <<v23-7-0,Topo>> | xref:023-isaias/023-isaias-008.adoc#v23-8-0[Próximo Capítulo &#62;]