include::./index.adoc[]

[[v23-12-0]]
=== Isaías, 12
// naa ?, NAA - Nova Almeida Atualizada

[[v23-12-1]]

^<<v23-12-1,1>>^ Naquele dia, você dirá: "Graças te dou, ó Senhor , porque, ainda que te iraste contra mim, a tua ira se retirou, e tu me consolas.

[[v23-12-2]]

^<<v23-12-2,2>>^ Eis que Deus é a minha salvação; confiarei e não temerei, porque o Senhor  Deus é a minha força e o meu cântico; ele se tornou a minha salvação.

[[v23-12-3]]

^<<v23-12-3,3>>^ Com alegria, vocês tirarão água das fontes da salvação."

[[v23-12-4]]

^<<v23-12-4,4>>^ Naquele dia, vocês dirão: "Deem graças ao Senhor , invoquem o seu nome; tornem conhecidos entre os povos os seus feitos, anunciem que é excelso o seu nome.

[[v23-12-5]]

^<<v23-12-5,5>>^ Cantem louvores ao Senhor , porque ele fez coisas grandiosas; saiba-se isto em toda a terra.

[[v23-12-6]]

^<<v23-12-6,6>>^ Exultem e gritem de alegria, ó moradores de Sião, porque grande é o Santo de Israel no meio de vocês."

'''

xref:023-isaias/023-isaias-011.adoc#v23-11-0[&#60; Capítulo Anterior] | <<v23-12-0,Topo>> | xref:023-isaias/023-isaias-013.adoc#v23-13-0[Próximo Capítulo &#62;]