include::./index.adoc[]

[[v23-20-0]]
=== Isaías, 20
// naa ?, NAA - Nova Almeida Atualizada

[[v23-20-1]]

^<<v23-20-1,1>>^ No ano em que Tartã, enviado por Sargão, rei da Assíria, veio a Asdode, atacou a cidade e a conquistou,

[[v23-20-2]]

^<<v23-20-2,2>>^ nesse mesmo tempo o Senhor  falou por meio de Isaías, filho de Amoz, dizendo: — Solte de seus lombos a roupa de pano grosseiro e tire as sandálias dos pés. Isaías fez isso, passando a andar despido e descalço.

[[v23-20-3]]

^<<v23-20-3,3>>^ Então o Senhor  disse: — Assim como o meu servo Isaías andou três anos despido e descalço, como sinal e prenúncio contra o Egito e contra a Etiópia,

[[v23-20-4]]

^<<v23-20-4,4>>^ assim o rei da Assíria levará os presos do Egito e os exilados da Etiópia, tanto moços como velhos, despidos e descalços e com as nádegas descobertas, para vergonha do Egito.

[[v23-20-5]]

^<<v23-20-5,5>>^ Então os israelitas ficarão apavorados e envergonhados por causa dos etíopes, sua esperança, e dos egípcios, sua glória.

[[v23-20-6]]

^<<v23-20-6,6>>^ Os moradores desta região dirão naquele dia: "Vejam o que aconteceu com aqueles em quem esperávamos e a quem recorremos para nos livrar do rei da Assíria! E, agora, como nós vamos escapar?"

'''

xref:023-isaias/023-isaias-019.adoc#v23-19-0[&#60; Capítulo Anterior] | <<v23-20-0,Topo>> | xref:023-isaias/023-isaias-021.adoc#v23-21-0[Próximo Capítulo &#62;]