include::./index.adoc[]

[[v23-57-0]]
=== Isaías, 57
// naa ?, NAA - Nova Almeida Atualizada

[[v23-57-1]]

^<<v23-57-1,1>>^ "Os justos perecem, e não há quem se importa com isso; os piedosos desaparecem sem que alguém considere nesse fato. Pois o justo é levado antes que venha o mal

[[v23-57-2]]

^<<v23-57-2,2>>^ e entra na paz; os que andam em retidão descansam no seu leito."

[[v23-57-3]]

^<<v23-57-3,3>>^ "Mas vocês, filhos de feiticeira, vocês, descendência de adúlteros e de prostitutas, venham cá!

[[v23-57-4]]

^<<v23-57-4,4>>^ De quem vocês estão zombando? Contra quem estão escancarando a boca e mostrando a língua? Por acaso vocês não são filhos da transgressão, descendência da falsidade,

[[v23-57-5]]

^<<v23-57-5,5>>^ vocês que se inflamam em seus desejos junto aos carvalhos, debaixo de toda árvore frondosa, e sacrificam os seus filhos nos vales e nas fendas dos penhascos?

[[v23-57-6]]

^<<v23-57-6,6>>^ Entre as pedras lisas dos ribeiros vocês escolhem os seus ídolos; elas são a sua parte. Sobre elas vocês também oferecem as suas libações e apresentam ofertas de cereais. Será que eu poderia estar contente com estas coisas?

[[v23-57-7]]

^<<v23-57-7,7>>^ Sobre um monte alto e elevado vocês põem o seu leito; para lá vocês sobem para oferecer sacrifícios.

[[v23-57-8]]

^<<v23-57-8,8>>^ Atrás das portas e das ombreiras vocês põem os seus símbolos pagãos. Afastando-se de mim, vocês sobem ao leito e o alargam para os seus amantes, apresentando-lhes as suas exigências. Vocês gostam de se deitar com eles e lhes contemplar a nudez."

[[v23-57-9]]

^<<v23-57-9,9>>^ "Você vai ao rei com óleo e multiplica os seus perfumes; envia os seus embaixadores para longe, até a profundidade da sepultura.

[[v23-57-10]]

^<<v23-57-10,10>>^ Nessa longa viagem você se cansa, mas não diz: ‘É inútil!’ Você encontra novas forças; por isso, não desfalece."

[[v23-57-11]]

^<<v23-57-11,11>>^ "Mas de quem você teve receio ou temor, para que mentisse e não se lembrasse de mim, nem me levasse a sério? Será que é porque me calo, e isso desde muito tempo, e você não me teme?

[[v23-57-12]]

^<<v23-57-12,12>>^ Eu publicarei essa sua justiça e as suas obras, mas isso não a beneficiará em nada.

[[v23-57-13]]

^<<v23-57-13,13>>^ Quando você clamar por ajuda, que a sua coleção de ídolos a livre! O vento levará todos eles; um sopro os arrebatará. Mas o que confia em mim herdará a terra e possuirá o meu santo monte."

[[v23-57-14]]

^<<v23-57-14,14>>^ Então se dirá: "Aterrem, aterrem a estrada, preparem o caminho, tirem os tropeços do caminho do meu povo."

[[v23-57-15]]

^<<v23-57-15,15>>^ Porque assim diz o Alto, o Sublime, que habita a eternidade e cujo nome é Santo: "Habito no alto e santo lugar, mas habito também com o contrito e abatido de espírito, para vivificar o espírito dos abatidos e vivificar o coração dos contritos.

[[v23-57-16]]

^<<v23-57-16,16>>^ Pois não farei litígio para sempre, nem me indignarei continuamente; porque, do contrário, o espírito definharia diante de mim, bem como o fôlego da vida, que eu criei.

[[v23-57-17]]

^<<v23-57-17,17>>^ Por causa da maldade da cobiça do meu povo eu me indignei e o feri; escondi o meu rosto e me indignei, mas, em sua rebeldia, o povo seguiu o seu próprio caminho."

[[v23-57-18]]

^<<v23-57-18,18>>^ "Tenho visto os caminhos do meu povo, mas vou curá-lo; também o guiarei e tornarei a dar consolação, a ele e aos seus pranteadores.

[[v23-57-19]]

^<<v23-57-19,19>>^ Como fruto dos seus lábios criei a paz, paz para os que estão longe e para os que estão perto", diz o Senhor , "e eu o sararei.

[[v23-57-20]]

^<<v23-57-20,20>>^ Mas os ímpios são como o mar agitado, que não se pode aquietar, cujas águas lançam de si lama e lodo.

[[v23-57-21]]

^<<v23-57-21,21>>^ Para os ímpios, diz o meu Deus, não há paz."

'''

xref:023-isaias/023-isaias-056.adoc#v23-56-0[&#60; Capítulo Anterior] | <<v23-57-0,Topo>> | xref:023-isaias/023-isaias-058.adoc#v23-58-0[Próximo Capítulo &#62;]