include::./index.adoc[]

[[v24-20-0]]
=== Jeremias, 20
// naa ?, NAA - Nova Almeida Atualizada

[[v24-20-1]]

^<<v24-20-1,1>>^ Pasur, filho do sacerdote Imer, que era superintendente da Casa do Senhor , ouviu Jeremias profetizando estas coisas

[[v24-20-2]]

^<<v24-20-2,2>>^ e por isso mandou que o profeta fosse açoitado e preso no tronco que ficava junto ao portão superior de Benjamim, na Casa do Senhor . No dia seguinte, Pasur mandou que Jeremias fosse tirado do tronco.

[[v24-20-3]]

^<<v24-20-3,3>>^ Então Jeremias lhe disse: — O Senhor  mudou o seu nome de Pasur para Magor-Missabibe.

[[v24-20-4]]

^<<v24-20-4,4>>^ Pois assim diz o Senhor : "Eis que farei de você um terror para você mesmo e para todos os seus amigos. Eles serão mortos à espada pelos seus inimigos, e você verá isso. Entregarei todo o povo de Judá nas mãos do rei da Babilônia, que os levará presos à Babilônia e os matará à espada.

[[v24-20-5]]

^<<v24-20-5,5>>^ Também entregarei toda a riqueza desta cidade, todo o fruto do seu trabalho e todas as suas coisas preciosas; sim, entregarei todos os tesouros dos reis de Judá nas mãos de seus inimigos, os quais hão de saquear, pegar e levar tudo para a Babilônia.

[[v24-20-6]]

^<<v24-20-6,6>>^ E você, Pasur, e todos os moradores da sua casa serão levados para o cativeiro. Você irá à Babilônia, onde morrerá e será sepultado, você e todos os seus amigos, aos quais você profetizou falsamente."

[[v24-20-7]]

^<<v24-20-7,7>>^ Tu me persuadiste, Senhor , e eu fui persuadido. Foste mais forte do que eu e prevaleceste. Sou motivo de riso o dia inteiro; todos zombam de mim.

[[v24-20-8]]

^<<v24-20-8,8>>^ Porque, sempre que falo, tenho de gritar e clamar: "Violência e destruição!" Por causa da palavra do Senhor , sou objeto de deboche e de zombaria o tempo todo.

[[v24-20-9]]

^<<v24-20-9,9>>^ Quando pensei: "Não me lembrarei dele e não falarei mais em seu nome", então isso se tornou em meu coração como um fogo, encerrado nos meus ossos. Estou cansado de sofrer e não posso mais.

[[v24-20-10]]

^<<v24-20-10,10>>^ Porque ouvi a murmuração de muitos: "Há terror por todos os lados! Denunciem, e nós o denunciaremos!" Todos os meus amigos íntimos esperam que eu tropece e dizem: "Talvez ele se deixe persuadir; então nós o venceremos e dele nos vingaremos."

[[v24-20-11]]

^<<v24-20-11,11>>^ Mas o Senhor  está comigo como um poderoso guerreiro. Por isso, os meus perseguidores tropeçarão e não vencerão. Ficarão muito envergonhados por causa do seu fracasso; sofrerão afronta perpétua, que jamais será esquecida.

[[v24-20-12]]

^<<v24-20-12,12>>^ Ó Senhor  dos Exércitos, que provas o justo e vês o mais íntimo do coração, permite que eu veja a tua vingança contra eles, pois te confiei a minha causa.

[[v24-20-13]]

^<<v24-20-13,13>>^ Cantem ao Senhor ! Louvem o Senhor ! Pois ele livrou a vida do necessitado das mãos dos malfeitores.

[[v24-20-14]]

^<<v24-20-14,14>>^ Maldito o dia em que eu nasci! Não seja bendito o dia em que a minha mãe me deu à luz!

[[v24-20-15]]

^<<v24-20-15,15>>^ Maldito o homem que deu a notícia a meu pai, dizendo: "Nasceu o seu filho! É um menino!", causando-lhe grande alegria.

[[v24-20-16]]

^<<v24-20-16,16>>^ Que esse homem seja como as cidades que o Senhor , sem ter compaixão, destruiu! Que ele ouça gritos de dor pela manhã e alarido de guerra ao meio-dia,

[[v24-20-17]]

^<<v24-20-17,17>>^ porque não me matou no ventre materno. Então a minha mãe teria sido a minha sepultura, e ela teria ficado para sempre grávida.

[[v24-20-18]]

^<<v24-20-18,18>>^ Por que saí do ventre materno tão somente para ver trabalho e tristeza e para que se consumam de vergonha os meus dias?

'''

xref:024-jeremias/024-jeremias-019.adoc#v24-19-0[&#60; Capítulo Anterior] | <<v24-20-0,Topo>> | xref:024-jeremias/024-jeremias-021.adoc#v24-21-0[Próximo Capítulo &#62;]