include::./index.adoc[]

[[v24-11-0]]
=== Jeremias, 11
// naa ?, NAA - Nova Almeida Atualizada

[[v24-11-1]]

^<<v24-11-1,1>>^ Palavra que foi dita a Jeremias da parte do Senhor :

[[v24-11-2]]

^<<v24-11-2,2>>^ — Ouça as palavras desta aliança e fale aos homens de Judá e aos moradores de Jerusalém.

[[v24-11-3]]

^<<v24-11-3,3>>^ Diga-lhes: "Assim diz o Senhor , o Deus de Israel: Maldito aquele que não der ouvidos às palavras desta aliança,

[[v24-11-4]]

^<<v24-11-4,4>>^ que ordenei aos pais de vocês, no dia em que os tirei da terra do Egito, da fornalha de ferro. Eu lhes disse: ‘Deem ouvidos à minha voz e façam tudo o que eu lhes ordeno, e vocês serão o meu povo, e eu serei o seu Deus.

[[v24-11-5]]

^<<v24-11-5,5>>^ Assim confirmarei o juramento que fiz aos pais de vocês de lhes dar uma terra que manasse leite e mel, como se vê neste dia.’" Então eu respondi: — Amém, Senhor !

[[v24-11-6]]

^<<v24-11-6,6>>^ E o Senhor  me disse: — Proclame todas estas palavras nas cidades de Judá e nas ruas de Jerusalém. Diga-lhes que deem ouvidos às palavras desta aliança e que as cumpram.

[[v24-11-7]]

^<<v24-11-7,7>>^ Porque adverti solenemente os pais de vocês, no dia em que os tirei do Egito, até o dia de hoje, testemunhando sempre de novo que dessem ouvidos à minha voz.

[[v24-11-8]]

^<<v24-11-8,8>>^ Mas eles não quiseram ouvir, nem atenderam. Pelo contrário, andaram, cada um, segundo a dureza do seu coração maligno. Por isso, fiz cair sobre eles todas as ameaças desta aliança, a qual lhes ordenei que cumprissem, mas que eles não cumpriram.

[[v24-11-9]]

^<<v24-11-9,9>>^ O Senhor  ainda me disse o seguinte: — Os homens de Judá e os moradores de Jerusalém armaram uma conspiração.

[[v24-11-10]]

^<<v24-11-10,10>>^ Retornaram às maldades de seus primeiros pais, que recusaram ouvir as minhas palavras. Também eles seguiram outros deuses para os servir. A casa de Israel e a casa de Judá quebraram a minha aliança, que eu fiz com os seus pais.

[[v24-11-11]]

^<<v24-11-11,11>>^ Portanto, assim diz o Senhor : "Eis que trarei uma calamidade sobre eles, da qual não poderão escapar. Clamarão a mim, porém não os ouvirei.

[[v24-11-12]]

^<<v24-11-12,12>>^ Então as cidades de Judá e os moradores de Jerusalém irão aos deuses a quem eles queimaram incenso e a eles clamarão; porém estes de modo nenhum os livrarão na hora da calamidade.

[[v24-11-13]]

^<<v24-11-13,13>>^ Porque os seus deuses, ó Judá, são tantos quantas as suas cidades, e os altares que vocês levantaram para a coisa vergonhosa, isto é, para queimar incenso a Baal, são tantos quanto o número das ruas de Jerusalém."

[[v24-11-14]]

^<<v24-11-14,14>>^ — Quanto a você, Jeremias, não interceda por este povo, nem levante por ele clamor ou oração, porque não os ouvirei quando eles clamarem a mim na hora da calamidade.

[[v24-11-15]]

^<<v24-11-15,15>>^ — Que direito tem minha amada na minha casa, ela que cometeu tantas maldades? Será que votos e carnes sacrificadas poderão afastar de você a calamidade? Então você saltaria de prazer.

[[v24-11-16]]

^<<v24-11-16,16>>^ O Senhor  a chamou de oliveira verde, formosa por seus deliciosos frutos. Mas agora, ao som de grande tumulto, acendeu fogo ao redor dela e quebrou os seus ramos.

[[v24-11-17]]

^<<v24-11-17,17>>^ Porque o Senhor  dos Exércitos, que a plantou, anunciou contra você uma calamidade, por causa do mal que a casa de Israel e a casa de Judá praticaram. Porque me provocaram à ira, queimando incenso a Baal.

[[v24-11-18]]

^<<v24-11-18,18>>^ O Senhor  me contou e eu fiquei sabendo; tu me mostraste o que eles estavam planejando.

[[v24-11-19]]

^<<v24-11-19,19>>^ Eu era como um cordeiro manso, que é levado ao matadouro. Eu não sabia que tramavam contra mim, dizendo: "Vamos destruir a árvore com seu fruto. Vamos cortá-lo da terra dos viventes, para que ninguém mais lembre do nome dele."

[[v24-11-20]]

^<<v24-11-20,20>>^ Mas, ó Senhor  dos Exércitos, justo Juiz, que provas o mais íntimo do coração, permite que eu veja a tua vingança contra eles, pois te confiei a minha causa.

[[v24-11-21]]

^<<v24-11-21,21>>^ Portanto, assim diz o Senhor  a respeito dos homens de Anatote que querem me ver morto e dizem: "Não profetize em nome do Senhor , para que não o matemos."

[[v24-11-22]]

^<<v24-11-22,22>>^ Sim, assim diz o Senhor  dos Exércitos: — Eis que eu os punirei. Os jovens morrerão à espada, os seus filhos e as suas filhas morrerão de fome.

[[v24-11-23]]

^<<v24-11-23,23>>^ E não sobrará nenhum deles, porque farei vir a calamidade sobre os homens de Anatote, no ano da sua punição.

'''

xref:024-jeremias/024-jeremias-010.adoc#v24-10-0[&#60; Capítulo Anterior] | <<v24-11-0,Topo>> | xref:024-jeremias/024-jeremias-012.adoc#v24-12-0[Próximo Capítulo &#62;]