include::./index.adoc[]

[[v24-39-0]]
=== Jeremias, 39
// naa ?, NAA - Nova Almeida Atualizada

[[v24-39-1]]

^<<v24-39-1,1>>^ Jerusalém foi tomada. Era o décimo mês do nono ano do reinado de Zedequias, rei de Judá, quando Nabucodonosor, rei da Babilônia, veio com todo o seu exército contra Jerusalém e a sitiou.

[[v24-39-2]]

^<<v24-39-2,2>>^ Era o décimo primeiro ano do reinado de Zedequias, no quarto mês, aos nove do mês, quando foi aberta uma brecha na muralha da cidade.

[[v24-39-3]]

^<<v24-39-3,3>>^ Então todos os oficiais do rei da Babilônia entraram e se assentaram no Portão do Meio: Nergal-Sarezer, Sangar-Nebo, Sarsequim, Rabe-Saris, Nergal-Sarezer, Rabe-Mague e todos os outros oficiais do rei da Babilônia.

[[v24-39-4]]

^<<v24-39-4,4>>^ Quando Zedequias e todos os homens de guerra viram o que havia acontecido, fugiram e, de noite, saíram da cidade, pelo caminho do jardim do rei, pelo portão que ficava entre as duas muralhas. Fugiram na direção do vale do Jordão.

[[v24-39-5]]

^<<v24-39-5,5>>^ Mas o exército dos caldeus os perseguiu e alcançou Zedequias nas campinas de Jericó. Eles o prenderam e o levaram a Ribla, na terra de Hamate, a Nabucodonosor, rei da Babilônia, que lhe pronunciou a sentença.

[[v24-39-6]]

^<<v24-39-6,6>>^ Em Ribla, o rei da Babilônia mandou matar os filhos de Zedequias à vista deste; também mandou matar todas as autoridades de Judá.

[[v24-39-7]]

^<<v24-39-7,7>>^ Mandou furar os olhos de Zedequias e amarrou-o com correntes de bronze, para o levar à Babilônia.

[[v24-39-8]]

^<<v24-39-8,8>>^ Os caldeus queimaram o palácio do rei e as casas do povo e derrubaram as muralhas de Jerusalém.

[[v24-39-9]]

^<<v24-39-9,9>>^ Nebuzaradã, o chefe da guarda, levou cativos para a Babilônia o resto do povo que havia ficado na cidade, os desertores que se entregaram a ele e o restante da população.

[[v24-39-10]]

^<<v24-39-10,10>>^ Porém Nebuzaradã, o chefe da guarda, deixou na terra de Judá alguns dos mais pobres da terra, que nada tinham; e lhes deu vinhas e campos naquele dia.

[[v24-39-11]]

^<<v24-39-11,11>>^ Mas a respeito de Jeremias, Nabucodonosor, rei da Babilônia, tinha dado a seguinte ordem a Nebuzaradã, o chefe da guarda:

[[v24-39-12]]

^<<v24-39-12,12>>^ — Trate de encontrá-lo, cuide bem dele e não lhe faça nenhum mal. Faça com Jeremias o que ele lhe disser.

[[v24-39-13]]

^<<v24-39-13,13>>^ Assim, Nebuzaradã, o chefe da guarda, Nebusazbã, Rabe-Saris, Nergal-Sarezer, Rabe-Mague, e todos os oficiais do rei da Babilônia

[[v24-39-14]]

^<<v24-39-14,14>>^ mandaram tirar Jeremias do pátio da guarda e o entregaram a Gedalias, filho de Aicão, filho de Safã, para que o levasse para casa. Assim Jeremias habitou no meio do povo.

[[v24-39-15]]

^<<v24-39-15,15>>^ Ora, quando Jeremias ainda estava detido no pátio da guarda, a palavra do Senhor  tinha vindo a ele, dizendo:

[[v24-39-16]]

^<<v24-39-16,16>>^ — Vá e diga a Ebede-Meleque, o etíope, que assim diz o Senhor  dos Exércitos, o Deus de Israel: "Eis que eu cumprirei as minhas palavras contra esta cidade para o mal e não para o bem; elas se cumprirão diante de você naquele dia.

[[v24-39-17]]

^<<v24-39-17,17>>^ Mas a você eu livrarei naquele dia, diz o Senhor , e você não será entregue nas mãos dos homens de quem tem medo.

[[v24-39-18]]

^<<v24-39-18,18>>^ Pois eu certamente o salvarei. Você não cairá à espada. A sua vida lhe será por despojo, porque você confiou em mim", diz o Senhor .

'''

xref:024-jeremias/024-jeremias-038.adoc#v24-38-0[&#60; Capítulo Anterior] | <<v24-39-0,Topo>> | xref:024-jeremias/024-jeremias-040.adoc#v24-40-0[Próximo Capítulo &#62;]