include::./index.adoc[]

[[v24-21-0]]
=== Jeremias, 21
// naa ?, NAA - Nova Almeida Atualizada

[[v24-21-1]]

^<<v24-21-1,1>>^ Palavra que foi dita a Jeremias da parte do Senhor , quando o rei Zedequias lhe enviou Pasur, filho de Malquias, e o sacerdote Sofonias, filho de Maaseias:

[[v24-21-2]]

^<<v24-21-2,2>>^ — Pergunte por nós ao Senhor , por que Nabucodonosor, rei da Babilônia, está fazendo guerra contra nós. Talvez o Senhor  nos trate segundo todas as suas maravilhas e faça com que o rei se retire de nós.

[[v24-21-3]]

^<<v24-21-3,3>>^ Então Jeremias mandou que dissessem ao rei Zedequias:

[[v24-21-4]]

^<<v24-21-4,4>>^ — Assim diz o Senhor , o Deus de Israel: "Eis que farei retroceder as armas de guerra que estão nas mãos de vocês e com as quais vocês estão lutando fora das muralhas contra o rei da Babilônia e contra os caldeus, que estão cercando a cidade. Essas armas, eu as ajuntarei no meio desta cidade.

[[v24-21-5]]

^<<v24-21-5,5>>^ Eu mesmo lutarei contra vocês com braço estendido e mão poderosa, com ira, com indignação e grande furor.

[[v24-21-6]]

^<<v24-21-6,6>>^ Matarei os habitantes desta cidade, tanto as pessoas como os animais; morrerão de uma grande peste.

[[v24-21-7]]

^<<v24-21-7,7>>^ Depois disso, diz o Senhor , entregarei Zedequias, rei de Judá, os seus servos e o povo — todos os moradores desta cidade que sobreviverem à peste, à espada e à fome — nas mãos de Nabucodonosor, rei da Babilônia, nas mãos de seus inimigos e nas mãos dos que procuram tirar-lhes a vida. Ele os matará a fio de espada; não os poupará, não se compadecerá, nem terá misericórdia."

[[v24-21-8]]

^<<v24-21-8,8>>^ — A este povo você dirá o seguinte: Assim diz o Senhor : "Eis que ponho diante de vocês o caminho da vida e o caminho da morte.

[[v24-21-9]]

^<<v24-21-9,9>>^ Quem ficar nesta cidade morrerá à espada, de fome ou de peste; mas quem sair e se render aos caldeus, que estão cercando a cidade, não morrerá; conseguirá ao menos salvar a sua vida.

[[v24-21-10]]

^<<v24-21-10,10>>^ Pois voltei o meu rosto contra esta cidade para trazer desgraça e não para fazer-lhe bem, diz o Senhor ; ela será entregue nas mãos do rei da Babilônia, e este a queimará."

[[v24-21-11]]

^<<v24-21-11,11>>^ — À casa do rei de Judá você dirá o seguinte: Escutem a palavra do Senhor !

[[v24-21-12]]

^<<v24-21-12,12>>^ Ó casa de Davi, assim diz o Senhor : "Julguem com retidão todos os dias e livrem o oprimido das mãos do opressor, para que o meu furor não saia como fogo, por causa da maldade do que vocês fazem, e queime, sem que haja quem o possa apagar.

[[v24-21-13]]

^<<v24-21-13,13>>^ Eis que eu sou contra você, ó Moradora do vale, ó Rocha da campina", diz o Senhor . "Sou contra vocês que dizem: ‘Quem descerá contra nós?’ Ou: ‘Quem entrará nas nossas moradas?’

[[v24-21-14]]

^<<v24-21-14,14>>^ Eu os castigarei segundo o fruto das ações de vocês", diz o Senhor ; "acenderei fogo em seu bosque, o qual queimará todos os seus arredores."

'''

xref:024-jeremias/024-jeremias-020.adoc#v24-20-0[&#60; Capítulo Anterior] | <<v24-21-0,Topo>> | xref:024-jeremias/024-jeremias-022.adoc#v24-22-0[Próximo Capítulo &#62;]