include::./index.adoc[]

[[v24-10-0]]
=== Jeremias, 10
// naa ?, NAA - Nova Almeida Atualizada

[[v24-10-1]]

^<<v24-10-1,1>>^ Ouçam a palavra que o Senhor  dirige a vocês, ó casa de Israel.

[[v24-10-2]]

^<<v24-10-2,2>>^ Assim diz o Senhor : "Não aprendam o caminho dos gentios, nem fiquem com medo dos sinais nos céus, porque com eles os gentios se atemorizam.

[[v24-10-3]]

^<<v24-10-3,3>>^ Porque os costumes dos povos são vaidade. Cortam uma árvore do bosque, e um artífice a trabalha com o machado.

[[v24-10-4]]

^<<v24-10-4,4>>^ Com prata e ouro a enfeitam, com pregos e martelos a fixam, para que não caia.

[[v24-10-5]]

^<<v24-10-5,5>>^ Os ídolos são como um espantalho em pepinal; eles não falam. Necessitam de quem os leve, porque não podem andar. Não tenham receio deles, pois não podem fazer mal; também não podem fazer o bem."

[[v24-10-6]]

^<<v24-10-6,6>>^ Não há ninguém semelhante a ti, ó Senhor ! Tu és grande, e grande é o poder do teu nome.

[[v24-10-7]]

^<<v24-10-7,7>>^ Quem não temeria a ti, ó Rei das nações? Porque isto te é devido. Porque entre todos os sábios das nações e em todo o seu reino não há ninguém semelhante a ti.

[[v24-10-8]]

^<<v24-10-8,8>>^ Mas todos eles se tornaram estúpidos e tolos; seu ensino é vão e morto como um pedaço de madeira.

[[v24-10-9]]

^<<v24-10-9,9>>^ Traz-se prata batida de Társis e ouro de Ufaz; os ídolos são obra de artífice e de mãos de ourives. Da cor azul e púrpura são as vestes deles; todos eles são obra de pessoas habilidosas.

[[v24-10-10]]

^<<v24-10-10,10>>^ Mas o Senhor é o verdadeiro Deus; ele é o Deus vivo e o Rei eterno. A terra treme diante do seu furor, e as nações não podem suportar a sua indignação.

[[v24-10-11]]

^<<v24-10-11,11>>^ Digam-lhes o seguinte: "Os deuses que não fizeram os céus e a terra desaparecerão da terra e de debaixo destes céus."

[[v24-10-12]]

^<<v24-10-12,12>>^ O Senhor  fez a terra pelo seu poder. Com a sua sabedoria, estabeleceu o mundo; e, com a sua inteligência, estendeu os céus.

[[v24-10-13]]

^<<v24-10-13,13>>^ Quando ele faz soar a sua voz, logo há tumulto de águas no céu, e nuvens sobem das extremidades da terra. Ele cria os relâmpagos para a chuva e dos seus depósitos faz sair o vento.

[[v24-10-14]]

^<<v24-10-14,14>>^ Todas as pessoas são tolas e não têm conhecimento. Todo ourives é envergonhado pela imagem que ele mesmo esculpiu, pois as suas imagens são falsas, e nelas não há fôlego de vida.

[[v24-10-15]]

^<<v24-10-15,15>>^ São vaidade, obras ridículas. Quando chegar o tempo do seu castigo, virão a perecer.

[[v24-10-16]]

^<<v24-10-16,16>>^ Aquele que é a Porção de Jacó não é semelhante a essas imagens, porque ele é o Criador de todas as coisas e Israel é a tribo da sua herança. Senhor  dos Exércitos é o seu nome.

[[v24-10-17]]

^<<v24-10-17,17>>^ Ajunte do chão os seus pertences, ó filha de Sião, você que mora em lugar sitiado.

[[v24-10-18]]

^<<v24-10-18,18>>^ Porque assim diz o Senhor : "Eis que desta vez lançarei fora os moradores da terra e os angustiarei, para que venham a senti-lo."

[[v24-10-19]]

^<<v24-10-19,19>>^ Ai de mim, por causa da minha ruína! A minha ferida é muito grave! E eu dizia: "Certamente este é o meu sofrimento, e eu posso suportá-lo."

[[v24-10-20]]

^<<v24-10-20,20>>^ A minha tenda foi destruída, todas as cordas se romperam. Os meus filhos se foram e já não existem; não restou ninguém para levantar a minha tenda e erguer as suas lonas.

[[v24-10-21]]

^<<v24-10-21,21>>^ Porque os pastores se tornaram tolos e não buscaram o Senhor ; por isso, não prosperaram, e todos os seus rebanhos se acham dispersos.

[[v24-10-22]]

^<<v24-10-22,22>>^ Eis aí um rumor! Eis que vem grande tumulto da terra do Norte, para fazer das cidades de Judá uma desolação, morada de chacais.

[[v24-10-23]]

^<<v24-10-23,23>>^ Eu sei, ó Senhor , que não cabe ao ser humano determinar o seu caminho, nem cabe ao que anda dirigir os seus passos.

[[v24-10-24]]

^<<v24-10-24,24>>^ Castiga-me, ó Senhor , mas em justa medida; não na tua ira, para que não me reduzas a nada.

[[v24-10-25]]

^<<v24-10-25,25>>^ Derrama o teu furor sobre as nações que não te conhecem e sobre os povos que não invocam o teu nome. Porque foram eles que devoraram Jacó; eles o devoraram, consumiram, e destruíram as suas moradas.

'''

xref:024-jeremias/024-jeremias-009.adoc#v24-9-0[&#60; Capítulo Anterior] | <<v24-10-0,Topo>> | xref:024-jeremias/024-jeremias-011.adoc#v24-11-0[Próximo Capítulo &#62;]