include::./index.adoc[]

[[v24-30-0]]
=== Jeremias, 30
// naa ?, NAA - Nova Almeida Atualizada

[[v24-30-1]]

^<<v24-30-1,1>>^ Palavra que foi dita a Jeremias da parte do Senhor :

[[v24-30-2]]

^<<v24-30-2,2>>^ — Assim diz o Senhor , Deus de Israel: Escreva num livro todas as palavras que eu lhe falei.

[[v24-30-3]]

^<<v24-30-3,3>>^ Porque eis que vêm dias, diz o Senhor , em que mudarei a sorte do meu povo de Israel e de Judá, diz o Senhor . Farei com que voltem para a terra que dei aos seus pais, e eles a possuirão.

[[v24-30-4]]

^<<v24-30-4,4>>^ São estas as palavras que o Senhor  falou a respeito de Israel e de Judá:

[[v24-30-5]]

^<<v24-30-5,5>>^ Assim diz o Senhor : "Ouvimos um grito de terror, um grito de medo e não de paz.

[[v24-30-6]]

^<<v24-30-6,6>>^ Perguntem e vejam se um homem pode dar à luz uma criança? Por que, então, vejo todos esses homens com as mãos na cintura, como se fossem uma mulher que está dando à luz? E por que se tornaram pálidos todos os rostos?

[[v24-30-7]]

^<<v24-30-7,7>>^ Ah! Que grande é aquele dia, e não há outro semelhante! É tempo de angústia para Jacó, mas ele será salvo dela."

[[v24-30-8]]

^<<v24-30-8,8>>^ — Naquele dia, diz o Senhor  dos Exércitos, eu quebrarei o jugo que está sobre o pescoço de vocês e despedaçarei as correias. E nunca mais estrangeiros irão escravizar este povo,

[[v24-30-9]]

^<<v24-30-9,9>>^ que servirá ao Senhor , seu Deus, e também a Davi, que lhes darei como rei.

[[v24-30-10]]

^<<v24-30-10,10>>^ "Portanto, não tenha medo, meu servo Jacó", diz o Senhor , "nem se atemorize, ó Israel. Pois eis que eu o livrarei dessa terra distante e salvarei a sua descendência da terra do exílio. Jacó voltará e ficará tranquilo e sossegado; e não haverá quem o atemorize.

[[v24-30-11]]

^<<v24-30-11,11>>^ Porque eu estou com você para salvá-lo", diz o Senhor . "Por isso, destruirei completamente todas as nações por onde o espalhei. A você eu não destruirei completamente, mas castigarei em justa medida; de modo nenhum deixarei você impune."

[[v24-30-12]]

^<<v24-30-12,12>>^ Porque assim diz o Senhor : "A sua ferida é incurável, o seu ferimento é grave.

[[v24-30-13]]

^<<v24-30-13,13>>^ Não há quem defenda a sua causa; não há remédio nem cura para a sua ferida.

[[v24-30-14]]

^<<v24-30-14,14>>^ Todos os seus amantes se esqueceram de você; já não perguntam por você. Porque eu a feri como se você fosse um inimigo; o castigo foi cruel, por causa da grandeza da sua maldade e da multidão dos seus pecados.

[[v24-30-15]]

^<<v24-30-15,15>>^ Por que você grita por causa da sua ferida? Essa sua dor é incurável. Por causa da grandeza de sua maldade e da multidão dos seus pecados é que eu fiz estas coisas.

[[v24-30-16]]

^<<v24-30-16,16>>^ Por isso, todos os que a devoram serão devorados, e todos os seus inimigos serão levados, cada um deles para o cativeiro. Aqueles que a despojam serão despojados, e entregarei ao saque todos os que a saqueiam.

[[v24-30-17]]

^<<v24-30-17,17>>^ Porque restaurarei a sua saúde e curarei as suas feridas", diz o Senhor . "Porque chamaram você de repudiada, dizendo: ‘É Sião, ninguém mais pergunta por ela.’"

[[v24-30-18]]

^<<v24-30-18,18>>^ Assim diz o Senhor : "Eis que restaurarei a sorte das tendas de Jacó e me compadecerei das suas moradas. A cidade será reedificada sobre o seu montão de ruínas, e o palácio será habitado outra vez.

[[v24-30-19]]

^<<v24-30-19,19>>^ De lá sairão ações de graças e os gritos dos que se alegram. Eu os multiplicarei, e não serão diminuídos; eu os glorificarei, e não serão desprezados.

[[v24-30-20]]

^<<v24-30-20,20>>^ Os seus filhos serão como antigamente, e a sua congregação será firmada diante de mim; e castigarei todos os seus opressores.

[[v24-30-21]]

^<<v24-30-21,21>>^ O seu príncipe procederá deles, do meio deles sairá aquele que há de reinar. Farei com que ele se aproxime, e ele chegará perto de mim; pois quem por si mesmo ousaria aproximar-se de mim?" — diz o Senhor .

[[v24-30-22]]

^<<v24-30-22,22>>^ "Vocês serão o meu povo, e eu serei o seu Deus."

[[v24-30-23]]

^<<v24-30-23,23>>^ Eis a tempestade do Senhor ! O furor saiu, uma tempestade passou sobre a cabeça dos ímpios.

[[v24-30-24]]

^<<v24-30-24,24>>^ O furor da ira do Senhor não se desviará até que ele execute e cumpra os desígnios do seu coração. Nos últimos dias, vocês entenderão isso.

'''

xref:024-jeremias/024-jeremias-029.adoc#v24-29-0[&#60; Capítulo Anterior] | <<v24-30-0,Topo>> | xref:024-jeremias/024-jeremias-031.adoc#v24-31-0[Próximo Capítulo &#62;]