include::./index.adoc[]

[[v24-42-0]]
=== Jeremias, 42
// naa ?, NAA - Nova Almeida Atualizada

[[v24-42-1]]

^<<v24-42-1,1>>^ Então todos os capitães dos exércitos e Joanã, filho de Careá, e Jezanias, filho de Hosaías, e todo o povo, desde o menor até o maior, se aproximaram

[[v24-42-2]]

^<<v24-42-2,2>>^ e disseram ao profeta Jeremias: — Apresentamos a você a nossa humilde súplica, para que você ore ao Senhor , seu Deus, por nós e por este remanescente. Porque, de muitos que éramos, só restamos uns poucos, como você pode ver com os seus próprios olhos.

[[v24-42-3]]

^<<v24-42-3,3>>^ Ore, pedindo que o Senhor , seu Deus, nos mostre o caminho que devemos seguir e o que devemos fazer.

[[v24-42-4]]

^<<v24-42-4,4>>^ O profeta Jeremias respondeu: — Eu ouvi o pedido de vocês. Vou orar ao Senhor , o Deus de vocês, de acordo com o que vocês pediram. Tudo o que o Senhor  lhes disser em resposta, eu o declararei a vocês, sem ocultar nada.

[[v24-42-5]]

^<<v24-42-5,5>>^ Então eles disseram a Jeremias: — Que o Senhor  seja uma testemunha verdadeira e fiel contra nós, se não fizermos conforme toda a palavra que o Senhor , seu Deus, nos disser por meio de você!

[[v24-42-6]]

^<<v24-42-6,6>>^ Seja ela boa ou má, obedeceremos à voz do Senhor , nosso Deus, a quem pedimos que você ore por nós, para que tudo corra bem conosco, ao obedecermos à voz do Senhor , nosso Deus.

[[v24-42-7]]

^<<v24-42-7,7>>^ Depois de dez dias, a palavra do Senhor  veio a Jeremias.

[[v24-42-8]]

^<<v24-42-8,8>>^ Então ele chamou Joanã, filho de Careá, todos os capitães dos exércitos que estavam com ele e todo o povo, desde o menor até o maior,

[[v24-42-9]]

^<<v24-42-9,9>>^ e lhes disse: — Assim diz o Senhor , Deus de Israel, a quem vocês me enviaram para apresentar a súplica de vocês:

[[v24-42-10]]

^<<v24-42-10,10>>^ "Se vocês permanecerem nesta terra, então eu os edificarei e não os derrubarei; eu os plantarei e não os arrancarei, porque estou triste pelo mal que lhes fiz.

[[v24-42-11]]

^<<v24-42-11,11>>^ Não tenham medo do rei da Babilônia, de quem agora vocês estão com medo. Não tenham medo dele, diz o Senhor , porque eu estou com vocês, para os salvar e livrar das mãos dele.

[[v24-42-12]]

^<<v24-42-12,12>>^ Terei misericórdia de vocês, para que ele tenha misericórdia de vocês e os faça voltar a esta terra."

[[v24-42-13]]

^<<v24-42-13,13>>^ — Mas, se vocês disserem: "Não ficaremos nesta terra"; se desobedecerem à voz do Senhor , seu Deus,

[[v24-42-14]]

^<<v24-42-14,14>>^ e disserem: "Não! Preferimos ir à terra do Egito, onde não veremos guerra, nem ouviremos som de trombeta, nem passaremos fome, e ali vamos morar",

[[v24-42-15]]

^<<v24-42-15,15>>^ nesse caso, ouça a palavra do Senhor , ó remanescente de Judá. Assim diz o Senhor  dos Exércitos, o Deus de Israel: "Se tiverem o firme propósito de entrar no Egito para morar,

[[v24-42-16]]

^<<v24-42-16,16>>^ então a guerra da qual vocês têm medo os alcançará, e a fome que vocês receiam irá no encalço de vocês até o Egito, onde vocês morrerão.

[[v24-42-17]]

^<<v24-42-17,17>>^ Assim será com todos os que tiverem o propósito de entrar no Egito para morar: morrerão à espada, de fome e de peste. Não haverá um só que sobreviva ou escape do mal que trarei sobre eles."

[[v24-42-18]]

^<<v24-42-18,18>>^ — Porque assim diz o Senhor  dos Exércitos, o Deus de Israel: "Assim como se derramou a minha ira e o meu furor sobre os moradores de Jerusalém, o meu furor se derramará sobre vocês, quando entrarem no Egito. Vocês serão objeto de maldição, de horror, de zombaria e de deboche, e nunca mais verão este lugar."

[[v24-42-19]]

^<<v24-42-19,19>>^ — O Senhor  disse a vocês, que são o remanescente de Judá: "Não vão para o Egito." Estejam certos de que hoje eu faço esta advertência:

[[v24-42-20]]

^<<v24-42-20,20>>^ Vocês estão se enganando, à custa da própria vida. Porque me enviaram ao Senhor , seu Deus, dizendo: "Ore por nós ao Senhor , nosso Deus. Depois, conte-nos tudo o que o Senhor , nosso Deus, disser, e nós o faremos."

[[v24-42-21]]

^<<v24-42-21,21>>^ Mas, agora que eu lhes contei tudo isso, vocês não deram ouvidos à voz do Senhor , seu Deus, não fazendo nada do que ele me mandou dizer.

[[v24-42-22]]

^<<v24-42-22,22>>^ Agora, pois, estejam certos de que morrerão à espada, de fome e de peste no mesmo lugar aonde desejaram ir para morar.

'''

xref:024-jeremias/024-jeremias-041.adoc#v24-41-0[&#60; Capítulo Anterior] | <<v24-42-0,Topo>> | xref:024-jeremias/024-jeremias-043.adoc#v24-43-0[Próximo Capítulo &#62;]