include::./index.adoc[]

[[v24-8-0]]
=== Jeremias, 8
// naa ?, NAA - Nova Almeida Atualizada

[[v24-8-1]]

^<<v24-8-1,1>>^ — Naquele tempo, diz o Senhor , serão tirados das sepulturas os ossos dos reis e das autoridades de Judá, os ossos dos sacerdotes e dos profetas e os ossos dos moradores de Jerusalém.

[[v24-8-2]]

^<<v24-8-2,2>>^ Os ossos serão espalhados ao sol, à lua e a todo o exército do céu, a quem tinham amado, a quem serviram e seguiram, a quem procuraram e diante de quem se prostraram. Não serão recolhidos, nem sepultados; serão como esterco sobre a terra.

[[v24-8-3]]

^<<v24-8-3,3>>^ Todos os que restarem desta nação malvada, em todos os lugares para onde os dispersei, preferirão morrer a ficar vivos, diz o Senhor  dos Exércitos.

[[v24-8-4]]

^<<v24-8-4,4>>^ Diga-lhes mais: Assim diz o Senhor : "Quando as pessoas caem, será que não se levantam? Quando alguém se desvia do caminho, não torna a voltar?

[[v24-8-5]]

^<<v24-8-5,5>>^ Por que, então, este povo de Jerusalém se afasta, em contínua rebeldia? Persiste no engano e não quer voltar.

[[v24-8-6]]

^<<v24-8-6,6>>^ Eu escutei e ouvi, mas eles não falam o que é reto. Ninguém se arrepende da sua maldade. Ninguém pergunta: ‘O que foi que eu fiz de errado?’ Cada um se afasta e segue o seu caminho como um cavalo que arremete com ímpeto na batalha.

[[v24-8-7]]

^<<v24-8-7,7>>^ Até a cegonha no céu conhece as suas estações, e a rolinha, a andorinha e o grou observam o tempo da sua migração. Mas o meu povo não conhece o juízo do Senhor ."

[[v24-8-8]]

^<<v24-8-8,8>>^ "Como vocês podem dizer: ‘Somos sábios, e a lei do Senhor  está conosco’? Na verdade, a falsa pena dos escribas a transformou em mentira.

[[v24-8-9]]

^<<v24-8-9,9>>^ Os sábios serão envergonhados, aterrorizados e presos. Eis que rejeitaram a palavra do Senhor . Que sabedoria é essa que eles têm?

[[v24-8-10]]

^<<v24-8-10,10>>^ Portanto, darei as mulheres deles a outros homens, e os seus campos, a novos possuidores. Porque, desde o menor deles até o maior, cada um está entregue à ganância, e tanto o profeta como o sacerdote usam de falsidade.

[[v24-8-11]]

^<<v24-8-11,11>>^ Curam superficialmente a ferida do meu povo, dizendo: ‘Paz, paz’; quando não há paz.

[[v24-8-12]]

^<<v24-8-12,12>>^ Será que eles ficaram envergonhados por cometerem abominação? Não, eles não ficaram com vergonha. Eles nem sabem o que é envergonhar-se. Portanto, cairão com os que caem; quando eu os castigar, tropeçarão", diz o Senhor .

[[v24-8-13]]

^<<v24-8-13,13>>^ "Eu os consumirei de todo", diz o Senhor . "Não haverá uvas na videira, nem figos na figueira, e as folhas já estão murchas. E já designei os que passarão sobre eles."

[[v24-8-14]]

^<<v24-8-14,14>>^ Por que nós estamos sentados aqui? Reúnam-se! Entremos nas cidades fortificadas e pereçamos ali. Pois o Senhor , nosso Deus, já decretou a nossa morte e nos deu de beber água envenenada, porque pecamos contra o Senhor .

[[v24-8-15]]

^<<v24-8-15,15>>^ Espera-se a paz, e não há nada de bom; espera-se o tempo da cura, e eis o terror.

[[v24-8-16]]

^<<v24-8-16,16>>^ "Desde Dã se ouve o resfolegar dos cavalos do inimigo; toda a terra treme ao som dos relinchos dos seus garanhões. Os inimigos vêm e devoram a terra e a sua abundância, a cidade e os que habitam nela.

[[v24-8-17]]

^<<v24-8-17,17>>^ Porque eis que envio cobras venenosas para o meio de vocês, serpentes contra as quais não há encantamento, e que picarão vocês", diz o Senhor .

[[v24-8-18]]

^<<v24-8-18,18>>^ Ah! Se eu pudesse consolar-me na minha tristeza! O meu coração desfalece dentro de mim.

[[v24-8-19]]

^<<v24-8-19,19>>^ Eis a voz do clamor da filha do meu povo de terra mui remota: "Será que o Senhor não está em Sião? Não está nela o seu Rei?" "Por que vocês me provocaram à ira com as suas imagens de escultura, com os ídolos dos estrangeiros?"

[[v24-8-20]]

^<<v24-8-20,20>>^ Passou a colheita, acabou o verão, e nós não estamos salvos.

[[v24-8-21]]

^<<v24-8-21,21>>^ Tenho o coração partido por causa da ferida da filha do meu povo. Estou de luto; o espanto se apoderou de mim.

[[v24-8-22]]

^<<v24-8-22,22>>^ Será que não há bálsamo em Gileade? Ou não há lá médico? Por que, então, não se realizou cura da filha do meu povo?

'''

xref:024-jeremias/024-jeremias-007.adoc#v24-7-0[&#60; Capítulo Anterior] | <<v24-8-0,Topo>> | xref:024-jeremias/024-jeremias-009.adoc#v24-9-0[Próximo Capítulo &#62;]