include::./index.adoc[]

[[v24-3-0]]
=== Jeremias, 3
// naa ?, NAA - Nova Almeida Atualizada

[[v24-3-1]]

^<<v24-3-1,1>>^ "Se um homem repudiar a sua mulher, e ela o deixar e se tornar esposa de outro homem, será que o primeiro marido poderá voltar para ela? Não seria aquela terra totalmente contaminada por causa disso? Ora, você se prostituiu com muitos amantes e ainda assim quer voltar para mim!" — diz o Senhor .

[[v24-3-2]]

^<<v24-3-2,2>>^ "Levante os olhos aos lugares altos e veja: onde você não se prostituiu? Na beira dos caminhos você se assentava à espera deles como o árabe se assenta no deserto. E assim você contaminou a terra com a sua prostituição e com a sua maldade.

[[v24-3-3]]

^<<v24-3-3,3>>^ É por isso que não tem chovido, e a chuva fora de época não veio. Mas você tem a fronte de prostituta e não quer se envergonhar.

[[v24-3-4]]

^<<v24-3-4,4>>^ Não é fato que agora mesmo você me invoca, dizendo: ‘Meu pai, tu és meu amigo desde a minha mocidade.

[[v24-3-5]]

^<<v24-3-5,5>>^ Conservarás para sempre a tua ira? Ou a reterás até o fim?’ Sim, isso é o que você diz, mas comete maldade até não poder mais."

[[v24-3-6]]

^<<v24-3-6,6>>^ Nos dias do rei Josias, o Senhor  me disse: — Você viu o que fez a rebelde Israel? Foi a todos os montes altos e ficou debaixo de todas as árvores frondosas para entregar-se à prostituição.

[[v24-3-7]]

^<<v24-3-7,7>>^ E, depois de ela ter feito tudo isso, eu pensei que ela voltaria para mim, mas não voltou. E a sua traiçoeira irmã Judá viu isso.

[[v24-3-8]]

^<<v24-3-8,8>>^ Quando, por causa de tudo isso, por ter ela cometido adultério, eu despedi a rebelde Israel e lhe dei carta de divórcio, vi que a irmã dela, a traiçoeira Judá, não ficou com medo, mas também ela foi e se entregou à prostituição.

[[v24-3-9]]

^<<v24-3-9,9>>^ E aconteceu que, pela facilidade com que se entregou à prostituição, ela contaminou a terra; porque adulterou, adorando pedras e árvores.

[[v24-3-10]]

^<<v24-3-10,10>>^ Apesar de tudo isso, a irmã dela, a traiçoeira Judá, não voltou para mim de todo o coração, mas fingidamente, diz o Senhor .

[[v24-3-11]]

^<<v24-3-11,11>>^ O Senhor  me disse: — A rebelde Israel se mostrou mais justa do que a traiçoeira Judá.

[[v24-3-12]]

^<<v24-3-12,12>>^ Vá, pois, e proclame estas palavras para o lado do Norte, dizendo: "Volte, ó rebelde Israel", diz o Senhor , "e não farei cair a minha ira sobre você, porque eu sou compassivo", diz o Senhor , "e não manterei para sempre a minha ira.

[[v24-3-13]]

^<<v24-3-13,13>>^ Tão somente reconheça a sua iniquidade, reconheça que você transgrediu contra o Senhor , seu Deus, e que você se prostituiu com os estranhos debaixo de todas as árvores frondosas e não deu ouvidos à minha voz", diz o Senhor .

[[v24-3-14]]

^<<v24-3-14,14>>^ "Voltem para mim, ó filhos rebeldes", diz o Senhor . "Porque eu é que sou o esposo de vocês. Eu os tomarei, um de cada cidade e dois de cada família, e os levarei a Sião."

[[v24-3-15]]

^<<v24-3-15,15>>^ — Darei a vocês pastores segundo o meu coração, que os apascentem com conhecimento e com inteligência.

[[v24-3-16]]

^<<v24-3-16,16>>^ E, quando vocês se multiplicarem e se tornarem fecundos na terra, então, diz o Senhor , nunca mais se exclamará: "A arca da aliança do Senhor !" Ela não lhes virá à mente, não se lembrarão dela nem dela sentirão falta; e não se fará outra.

[[v24-3-17]]

^<<v24-3-17,17>>^ Naquele tempo, chamarão Jerusalém de "Trono do Senhor ". Nela se reunirão todas as nações em nome do Senhor  e já não andarão segundo a dureza do seu coração maligno.

[[v24-3-18]]

^<<v24-3-18,18>>^ Naqueles dias, a casa de Judá andará com a casa de Israel, e elas virão juntas da terra do Norte para a terra que dei em herança aos pais de vocês.

[[v24-3-19]]

^<<v24-3-19,19>>^ "Eu disse a mim mesmo: Como eu gostaria de colocá-la entre os filhos e dar-lhe a terra desejável, a mais bela herança das nações! Pensei que você me chamaria de ‘pai’ e não se desviaria de mim.

[[v24-3-20]]

^<<v24-3-20,20>>^ Mas, assim como a mulher que, com traição, se afasta do seu marido, assim você foi infiel para comigo, ó casa de Israel", diz o Senhor .

[[v24-3-21]]

^<<v24-3-21,21>>^ "Nos lugares altos, se ouve uma voz: o pranto e as súplicas dos filhos de Israel. Porque eles perverteram o seu caminho e se esqueceram do Senhor , seu Deus.

[[v24-3-22]]

^<<v24-3-22,22>>^ Voltem, filhos rebeldes! Eu curarei as suas rebeliões." O povo responde: "Eis-nos aqui! Vimos ter contigo, porque tu és o Senhor , nosso Deus.

[[v24-3-23]]

^<<v24-3-23,23>>^ Na verdade, não passa de ilusão o que vem das colinas, o barulho que vem das montanhas. Na verdade, a salvação de Israel está no Senhor , nosso Deus."

[[v24-3-24]]

^<<v24-3-24,24>>^ Mas, desde a nossa juventude, a coisa vergonhosa devorou o trabalho de nossos pais: as suas ovelhas e o seu gado, os seus filhos e as suas filhas.

[[v24-3-25]]

^<<v24-3-25,25>>^ Devíamos nos prostrar em nossa vergonha, e deixar que a nossa desonra nos cubra, porque temos pecado contra o Senhor , nosso Deus, nós e nossos pais, desde a nossa mocidade até o dia de hoje; e não demos ouvidos à voz do Senhor , nosso Deus.

'''

xref:024-jeremias/024-jeremias-002.adoc#v24-2-0[&#60; Capítulo Anterior] | <<v24-3-0,Topo>> | xref:024-jeremias/024-jeremias-004.adoc#v24-4-0[Próximo Capítulo &#62;]