include::./index.adoc[]

[[v24-19-0]]
=== Jeremias, 19
// naa ?, NAA - Nova Almeida Atualizada

[[v24-19-1]]

^<<v24-19-1,1>>^ Assim diz o Senhor : — Vá comprar um pote de barro de um oleiro e leve com você alguns dos anciãos do povo e dos anciãos dos sacerdotes.

[[v24-19-2]]

^<<v24-19-2,2>>^ Vá até o vale de Ben-Hinom, que está junto à entrada do Portão dos Cacos, e proclame ali as palavras que eu lhe disser.

[[v24-19-3]]

^<<v24-19-3,3>>^ — Diga o seguinte: "Escutem a palavra do Senhor , ó reis de Judá e moradores de Jerusalém. Assim diz o Senhor  dos Exércitos, o Deus de Israel: Eis que trarei uma calamidade sobre este lugar, e quem ouvir falar dela ficará com os ouvidos tinindo.

[[v24-19-4]]

^<<v24-19-4,4>>^ Porque eles me abandonaram e profanaram este lugar, queimando nele incenso a outros deuses, que nem eles, nem os seus pais, nem os reis de Judá conheceram. E encheram este lugar de sangue de inocentes.

[[v24-19-5]]

^<<v24-19-5,5>>^ Edificaram os altos de Baal, para queimarem os seus filhos no fogo em holocaustos a Baal, o que nunca lhes ordenei, nem falei, nem me passou pela mente.

[[v24-19-6]]

^<<v24-19-6,6>>^ Por isso, eis que vêm dias, diz o Senhor , em que este lugar já não se chamará Tofete, nem vale de Ben-Hinom, mas o vale da Matança.

[[v24-19-7]]

^<<v24-19-7,7>>^ Porque desfarei os planos de Judá e de Jerusalém neste lugar e os farei cair à espada diante de seus inimigos e pela mão dos que procuram tirar-lhes a vida; e darei os seus cadáveres como alimento às aves dos céus e aos animais selvagens.

[[v24-19-8]]

^<<v24-19-8,8>>^ Porei esta cidade por objeto de horror e de vaias. Todo aquele que passar por ela ficará espantado e zombará por causa do desastre que lhe aconteceu.

[[v24-19-9]]

^<<v24-19-9,9>>^ Farei com que comam a carne de seus filhos e a carne de suas filhas, e cada um comerá a carne do seu próximo, na angústia e no aperto em que ficarão com o cerco dos seus inimigos e dos que procuram tirar-lhes a vida."

[[v24-19-10]]

^<<v24-19-10,10>>^ — Depois quebre o pote à vista dos homens que foram com você

[[v24-19-11]]

^<<v24-19-11,11>>^ e diga-lhes: Assim diz o Senhor  dos Exércitos: "Deste modo quebrarei este povo e esta cidade, como se quebra o vaso do oleiro, que não pode mais ser restaurado. Os mortos serão sepultados em Tofete, porque não haverá outro lugar para os sepultar.

[[v24-19-12]]

^<<v24-19-12,12>>^ Assim farei a este lugar, diz o Senhor , e aos seus moradores; e farei com que esta cidade seja como Tofete.

[[v24-19-13]]

^<<v24-19-13,13>>^ As casas de Jerusalém e as casas dos reis de Judá, sobre cujos terraços queimaram incenso a todo o exército dos céus e ofereceram libações a outros deuses, serão imundas como o lugar de Tofete."

[[v24-19-14]]

^<<v24-19-14,14>>^ Jeremias voltou de Tofete, lugar para onde o Senhor  o tinha enviado para profetizar, pôs-se em pé no átrio da Casa do Senhor  e disse a todo o povo:

[[v24-19-15]]

^<<v24-19-15,15>>^ — Assim diz o Senhor  dos Exércitos, o Deus de Israel: "Eis que trarei sobre esta cidade e sobre todos os povoados vizinhos todas as calamidades que pronunciei contra ela, porque foram teimosos e não deram ouvidos às minhas palavras."

'''

xref:024-jeremias/024-jeremias-018.adoc#v24-18-0[&#60; Capítulo Anterior] | <<v24-19-0,Topo>> | xref:024-jeremias/024-jeremias-020.adoc#v24-20-0[Próximo Capítulo &#62;]