include::./index.adoc[]

[[v24-9-0]]
=== Jeremias, 9
// naa ?, NAA - Nova Almeida Atualizada

[[v24-9-1]]

^<<v24-9-1,1>>^ Quem dera a minha cabeça se tornasse em águas, e os meus olhos, em fonte de lágrimas! Então choraria de dia e de noite os mortos da filha do meu povo.

[[v24-9-2]]

^<<v24-9-2,2>>^ Quem me dera eu tivesse no deserto um abrigo para viajantes! Então deixaria o meu povo e me afastaria dele, porque todos eles são adúlteros, são um bando de traidores.

[[v24-9-3]]

^<<v24-9-3,3>>^ Curvam a língua, como se fosse o seu arco, para disparar mentiras. "Fortalecem-se na terra, mas não para a verdade, porque avançam de maldade em maldade e não me conhecem", diz o Senhor .

[[v24-9-4]]

^<<v24-9-4,4>>^ "Que cada um de vocês se proteja do seu amigo e não confie em nenhum irmão. Porque todo irmão é enganador, e todo amigo não faz mais do que espalhar calúnias.

[[v24-9-5]]

^<<v24-9-5,5>>^ Cada um zomba do seu próximo, e não falam a verdade. Ensinam a sua língua a proferir mentiras; cansam-se de tanto praticar a iniquidade.

[[v24-9-6]]

^<<v24-9-6,6>>^ Vivem no meio da falsidade; pela falsidade se recusam a me conhecer", diz o Senhor .

[[v24-9-7]]

^<<v24-9-7,7>>^ Portanto, assim diz o Senhor  dos Exércitos: "Eis que eu os depurarei e os provarei. Pois que outra coisa poderia eu fazer com a filha do meu povo?

[[v24-9-8]]

^<<v24-9-8,8>>^ A língua deles é flecha mortífera; falam mentiras. Com a boca, cada um fala de paz com o seu companheiro, mas no seu interior lhe arma ciladas.

[[v24-9-9]]

^<<v24-9-9,9>>^ Deixaria eu de castigá-los por estas coisas?" — diz o Senhor . "Não deveria eu me vingar de uma nação como esta?"

[[v24-9-10]]

^<<v24-9-10,10>>^ Pelos montes, levantarei choro e pranto e, pelas pastagens do deserto, lamentação. Porque já estão queimadas, e ninguém passa por elas. Já não se ouve ali o mugido de gado; tanto as aves dos céus como os animais fugiram e se foram.

[[v24-9-11]]

^<<v24-9-11,11>>^ Farei de Jerusalém um montão de ruínas, morada de chacais; e das cidades de Judá farei uma desolação, para que fiquem desabitadas.

[[v24-9-12]]

^<<v24-9-12,12>>^ — Quem é o homem sábio, que entenda isto? E a quem falou a boca do Senhor , para que possa explicá-lo? Por que a terra foi destruída e se queimou como deserto pelo qual não passa ninguém?

[[v24-9-13]]

^<<v24-9-13,13>>^ O Senhor  respondeu: — Porque deixaram a minha lei, que pus diante deles, e não deram ouvidos ao que eu disse, nem andaram na minha lei.

[[v24-9-14]]

^<<v24-9-14,14>>^ Pelo contrário, andaram na dureza do seu coração e seguiram os baalins, como os pais deles lhes ensinaram.

[[v24-9-15]]

^<<v24-9-15,15>>^ Portanto, assim diz o Senhor  dos Exércitos, Deus de Israel: Eis que alimentarei este povo com absinto e lhe darei de beber água envenenada.

[[v24-9-16]]

^<<v24-9-16,16>>^ Eu os espalharei entre nações que nem eles nem os seus pais conheceram; e enviarei a espada após eles, até que eu os tenha destruído.

[[v24-9-17]]

^<<v24-9-17,17>>^ Assim diz o Senhor  dos Exércitos: "Considerem e chamem carpideiras, para que venham; mandem procurar mulheres hábeis, para que venham.

[[v24-9-18]]

^<<v24-9-18,18>>^ Que elas se apressem e levantem sobre nós o seu lamento, para que os nossos olhos se desfaçam em lágrimas, e as nossas pálpebras destilem água."

[[v24-9-19]]

^<<v24-9-19,19>>^ Porque uma voz de pranto se ouve de Sião: "Como estamos arruinados! Estamos muito envergonhados! Porque deixamos a nossa terra, e eles derrubaram as nossas casas."

[[v24-9-20]]

^<<v24-9-20,20>>^ Portanto, mulheres, escutem a palavra do Senhor e que os seus ouvidos recebam a palavra da sua boca. Ensinem às suas filhas um canto fúnebre; que cada uma ensine à sua companheira uma lamentação.

[[v24-9-21]]

^<<v24-9-21,21>>^ Porque a morte subiu pelas nossas janelas e entrou em nossos palácios; exterminou as crianças nas ruas e os jovens nas praças.

[[v24-9-22]]

^<<v24-9-22,22>>^ "Fale: Assim diz o Senhor : Os cadáveres das pessoas ficarão espalhados como adubo sobre o campo, como espigas que o ceifeiro deixa para trás, sem que haja quem as recolha."

[[v24-9-23]]

^<<v24-9-23,23>>^ — Assim diz o Senhor : Não se glorie o sábio na sua sabedoria, nem o forte, na sua força, nem o rico, nas suas riquezas.

[[v24-9-24]]

^<<v24-9-24,24>>^ Mas aquele que se gloria, glorie-se nisto: em me conhecer e saber que eu sou o Senhor  e faço misericórdia, juízo e justiça na terra; porque destas coisas me agrado, diz o Senhor .

[[v24-9-25]]

^<<v24-9-25,25>>^ — Eis que vêm dias, diz o Senhor , em que castigarei todos os que são circuncidados apenas na carne:

[[v24-9-26]]

^<<v24-9-26,26>>^ o povo do Egito, de Judá, de Edom, os filhos de Amom, de Moabe, e todos os que cortam o cabelo nas têmporas e vivem no deserto. Porque todas essas nações e toda a casa de Israel são incircuncisos de coração.

'''

xref:024-jeremias/024-jeremias-008.adoc#v24-8-0[&#60; Capítulo Anterior] | <<v24-9-0,Topo>> | xref:024-jeremias/024-jeremias-010.adoc#v24-10-0[Próximo Capítulo &#62;]