include::./index.adoc[]

[[v24-16-0]]
=== Jeremias, 16
// naa ?, NAA - Nova Almeida Atualizada

[[v24-16-1]]

^<<v24-16-1,1>>^ A palavra do Senhor  veio a mim, dizendo:

[[v24-16-2]]

^<<v24-16-2,2>>^ — Não case, nem tenha filhos ou filhas neste lugar.

[[v24-16-3]]

^<<v24-16-3,3>>^ Porque assim diz o Senhor  a respeito dos filhos e das filhas que nascerem neste lugar, a respeito das mães que os tiverem e dos pais que os gerarem nesta terra:

[[v24-16-4]]

^<<v24-16-4,4>>^ Morrerão de doenças terríveis e não serão pranteados, nem sepultados; servirão de esterco para a terra. A espada e a fome os consumirão, e os seus cadáveres servirão de alimento às aves do céu e aos animais selvagens.

[[v24-16-5]]

^<<v24-16-5,5>>^ — Porque assim diz o Senhor : Não entre em casa onde há luto, nem vá pranteá-los ou consolar os enlutados. Porque deste povo retirei a minha paz, diz o Senhor , e também a minha bondade e a minha compaixão.

[[v24-16-6]]

^<<v24-16-6,6>>^ Nesta terra, morrerão tanto grandes como pequenos e não serão sepultados nem prantearão por eles. Não se farão por eles cortes na pele nem por eles se raparão as cabeças.

[[v24-16-7]]

^<<v24-16-7,7>>^ Não se dará pão a quem estiver de luto, para consolá-lo por causa de morte, nem lhe darão de beber do copo da consolação, pelo pai ou pela mãe.

[[v24-16-8]]

^<<v24-16-8,8>>^ — Também não entre numa casa em que há um banquete, para sentar com eles a comer e a beber.

[[v24-16-9]]

^<<v24-16-9,9>>^ Porque assim diz o Senhor  dos Exércitos, o Deus de Israel: Eis que farei cessar neste lugar, diante dos olhos de vocês e enquanto vocês ainda estiverem vivos, o som das festas e da alegria, a voz do noivo e a voz da noiva.

[[v24-16-10]]

^<<v24-16-10,10>>^ — Quando você anunciar a este povo todas estas palavras, eles perguntarão: "Por que o Senhor  nos ameaça com todo este grande mal? Qual é a nossa iniquidade, qual é o nosso pecado, que cometemos contra o Senhor , nosso Deus?"

[[v24-16-11]]

^<<v24-16-11,11>>^ Então você responderá: "Porque os pais de vocês me abandonaram, diz o Senhor , e foram atrás de outros deuses, os serviram e os adoraram; eles me abandonaram e não guardaram a minha lei.

[[v24-16-12]]

^<<v24-16-12,12>>^ Vocês fizeram pior do que os seus pais, porque eis que cada um de vocês anda segundo a dureza do seu coração maligno, para não me dar ouvidos.

[[v24-16-13]]

^<<v24-16-13,13>>^ Portanto, eu os lançarei fora desta terra, para uma terra que nem vocês nem os seus pais conheceram. Ali vocês servirão a outros deuses, dia e noite, porque não terei misericórdia de vocês."

[[v24-16-14]]

^<<v24-16-14,14>>^ — Portanto, eis que vêm dias, diz o Senhor , em que nunca mais se dirá: "Tão certo como vive o Senhor , que tirou os filhos de Israel do Egito."

[[v24-16-15]]

^<<v24-16-15,15>>^ Pelo contrário, se dirá: "Tão certo como vive o Senhor , que tirou os filhos de Israel da terra do Norte e de todas as terras para onde os tinha dispersado." Pois eu os farei voltar para a sua terra, que dei aos seus pais.

[[v24-16-16]]

^<<v24-16-16,16>>^ — Eis que mandarei muitos pescadores, diz o Senhor , os quais os pescarão. Depois, enviarei muitos caçadores, os quais os trarão de todos os montes, de todas as colinas e até das fendas das rochas.

[[v24-16-17]]

^<<v24-16-17,17>>^ Porque os meus olhos estão sobre todos os caminhos deles. Eles não conseguem se esconder de mim, e a iniquidade deles não se encobre aos meus olhos.

[[v24-16-18]]

^<<v24-16-18,18>>^ Primeiramente, pagarei em dobro a sua iniquidade e o seu pecado, porque profanaram a minha terra com os cadáveres dos seus ídolos detestáveis e encheram a minha herança com as suas abominações.

[[v24-16-19]]

^<<v24-16-19,19>>^ Ó Senhor , minha força e minha fortaleza, meu refúgio no dia da angústia, a ti virão as nações desde os confins da terra e dirão: "Nossos pais herdaram só mentiras e coisas vãs, em que não há proveito.

[[v24-16-20]]

^<<v24-16-20,20>>^ Será que o ser humano pode fazer os seus próprios deuses? Esses não são deuses de verdade!"

[[v24-16-21]]

^<<v24-16-21,21>>^ — Portanto, eis que lhes farei conhecer, sim, desta vez lhes farei conhecer a minha força e o meu poder. E saberão que o meu nome é Senhor .

'''

xref:024-jeremias/024-jeremias-015.adoc#v24-15-0[&#60; Capítulo Anterior] | <<v24-16-0,Topo>> | xref:024-jeremias/024-jeremias-017.adoc#v24-17-0[Próximo Capítulo &#62;]