include::./index.adoc[]

[[v24-17-0]]
=== Jeremias, 17
// naa ?, NAA - Nova Almeida Atualizada

[[v24-17-1]]

^<<v24-17-1,1>>^ — O pecado de Judá está escrito com um ponteiro de ferro e com ponta de diamante, gravado na tábua do seu coração e nas pontas dos seus altares.

[[v24-17-2]]

^<<v24-17-2,2>>^ Os seus filhos se lembram dos seus altares e dos postes da deusa Aserá junto às árvores frondosas, sobre as colinas elevadas

[[v24-17-3]]

^<<v24-17-3,3>>^ e nos montes do campo. Darei os seus bens e todos os seus tesouros como despojo, e farei o mesmo com os seus lugares altos por causa do pecado, em todos os seus territórios!

[[v24-17-4]]

^<<v24-17-4,4>>^ Você terá de abandonar a herança que lhe dei. Farei com que você sirva os seus inimigos numa terra que você não conhece. Porque o fogo que você acendeu na minha ira queimará para sempre.

[[v24-17-5]]

^<<v24-17-5,5>>^ Assim diz o Senhor : "Maldito aquele que confia no ser humano, que faz da carne mortal o seu braço e cujo coração se desvia do Senhor !

[[v24-17-6]]

^<<v24-17-6,6>>^ Porque ele será como um arbusto solitário no deserto e não verá quando vier o bem; pelo contrário, morará nos lugares secos do deserto, na terra salgada e inabitável."

[[v24-17-7]]

^<<v24-17-7,7>>^ "Bendito aquele que confia no Senhor e cuja esperança é o Senhor .

[[v24-17-8]]

^<<v24-17-8,8>>^ Porque ele é como a árvore plantada junto às águas, que estende as suas raízes para o ribeiro e não receia quando vem o calor, porque as suas folhas permanecem verdes; e, no ano da seca, não se perturba, nem deixa de dar fruto."

[[v24-17-9]]

^<<v24-17-9,9>>^ "Enganoso é o coração, mais do que todas as coisas, e desesperadamente corrupto. Quem poderá entendê-lo?

[[v24-17-10]]

^<<v24-17-10,10>>^ Eu, o Senhor , sondo o coração. Eu provo os pensamentos, para dar a cada um segundo os seus caminhos, segundo o fruto das suas ações."

[[v24-17-11]]

^<<v24-17-11,11>>^ Como a perdiz que choca ovos que não pôs, assim é aquele que ajunta riquezas desonestamente; no meio da vida ficará sem elas e no seu fim passará por tolo.

[[v24-17-12]]

^<<v24-17-12,12>>^ Um trono de glória enaltecido desde o princípio é o lugar do nosso santuário.

[[v24-17-13]]

^<<v24-17-13,13>>^ Ó Senhor , Esperança de Israel! Todos aqueles que te abandonam serão envergonhados; o nome dos que se afastam de ti será escrito no chão, porque abandonam o Senhor , a fonte das águas vivas.

[[v24-17-14]]

^<<v24-17-14,14>>^ Cura-me, Senhor , e serei curado; salva-me, e serei salvo, porque tu és o meu louvor.

[[v24-17-15]]

^<<v24-17-15,15>>^ Eis que eles me dizem: "Onde está a palavra do Senhor ? Que se cumpra!"

[[v24-17-16]]

^<<v24-17-16,16>>^ Mas eu não me recusei a ser pastor, seguindo-te. Também não desejei o dia da aflição, tu o sabes. O que saiu dos meus lábios está no teu conhecimento.

[[v24-17-17]]

^<<v24-17-17,17>>^ Não sejas para mim motivo de terror; tu és o meu refúgio no dia da calamidade.

[[v24-17-18]]

^<<v24-17-18,18>>^ Que sejam envergonhados os que me perseguem, e não seja eu envergonhado; assombrem-se eles, e não me assombre eu. Traze sobre eles o dia da calamidade e destrói-os com dobrada destruição.

[[v24-17-19]]

^<<v24-17-19,19>>^ Assim me disse o Senhor : — Vá e fique junto ao Portão do Povo, pelo qual entram e saem os reis de Judá; depois, vá também a todos os outros portões de Jerusalém,

[[v24-17-20]]

^<<v24-17-20,20>>^ e diga a todos: "Escutem a palavra do Senhor , vocês, reis de Judá, e todo o Judá, e todos os moradores de Jerusalém que entram por estes portões.

[[v24-17-21]]

^<<v24-17-21,21>>^ Assim diz o Senhor : Para o próprio bem de vocês, tenham o cuidado de não levar cargas no dia de sábado, nem de introduzi-las em Jerusalém pelos portões.

[[v24-17-22]]

^<<v24-17-22,22>>^ Não saiam de casa carregando objetos no dia do sábado, nem façam trabalho algum. Pelo contrário, santifiquem o dia de sábado, como ordenei aos seus pais.

[[v24-17-23]]

^<<v24-17-23,23>>^ Mas eles não me deram ouvidos, nem atenderam; pelo contrário, foram teimosos, e não quiseram ouvir nem aceitar a disciplina.

[[v24-17-24]]

^<<v24-17-24,24>>^ Se de fato me ouvirem, diz o Senhor , não introduzindo cargas pelos portões desta cidade no dia de sábado; se santificarem o dia de sábado, não fazendo nele trabalho algum,

[[v24-17-25]]

^<<v24-17-25,25>>^ então pelos portões desta cidade entrarão reis e príncipes, que se assentarão no trono de Davi, andando em carros e montados em cavalos, eles e os seus príncipes, o povo de Judá e os moradores de Jerusalém; e esta cidade será para sempre habitada.

[[v24-17-26]]

^<<v24-17-26,26>>^ Virão das cidades de Judá e dos arredores de Jerusalém, da terra de Benjamim, da Sefelá, das montanhas e do Sul, trazendo holocaustos, sacrifícios, ofertas de cereais e incenso, oferecendo igualmente sacrifícios de ações de graças na Casa do Senhor .

[[v24-17-27]]

^<<v24-17-27,27>>^ Mas, se não me ouvirem, e, por isso, não santificarem o dia de sábado, e carregarem alguma carga, quando entrarem pelos portões de Jerusalém no dia de sábado, então porei fogo nesses portões. O fogo queimará os palácios de Jerusalém e não se apagará."

'''

xref:024-jeremias/024-jeremias-016.adoc#v24-16-0[&#60; Capítulo Anterior] | <<v24-17-0,Topo>> | xref:024-jeremias/024-jeremias-018.adoc#v24-18-0[Próximo Capítulo &#62;]