include::./index.adoc[]

[[v24-23-0]]
=== Jeremias, 23
// naa ?, NAA - Nova Almeida Atualizada

[[v24-23-1]]

^<<v24-23-1,1>>^ — Ai dos pastores que destroem e dispersam as ovelhas do meu pasto! — diz o Senhor .

[[v24-23-2]]

^<<v24-23-2,2>>^ Portanto, assim diz o Senhor , o Deus de Israel, a respeito dos pastores que apascentam o meu povo: "Vocês dispersaram as minhas ovelhas e as afugentaram, e não cuidaram delas. Mas eu tratarei de castigar vocês por causa das maldades que praticaram, diz o Senhor .

[[v24-23-3]]

^<<v24-23-3,3>>^ Eu mesmo recolherei o remanescente das minhas ovelhas, de todas as terras para onde as tiver dispersado, e as farei voltar aos seus apriscos; serão fecundas e se multiplicarão.

[[v24-23-4]]

^<<v24-23-4,4>>^ Porei sobre elas pastores que as apascentem, e elas jamais terão medo, nem ficarão assustadas; nem uma delas faltará, diz o Senhor ."

[[v24-23-5]]

^<<v24-23-5,5>>^ — Eis que vêm dias, diz o Senhor , em que levantarei a Davi um Renovo justo; e, como rei que é, reinará, agirá com sabedoria e executará o juízo e a justiça na terra.

[[v24-23-6]]

^<<v24-23-6,6>>^ Nos seus dias, Judá será salvo, e Israel habitará seguro. E este será o nome pelo qual será chamado: " Senhor , Justiça Nossa".

[[v24-23-7]]

^<<v24-23-7,7>>^ — Portanto, eis que vêm dias, diz o Senhor , em que nunca mais dirão: "Tão certo como vive o Senhor , que tirou os filhos de Israel da terra do Egito",

[[v24-23-8]]

^<<v24-23-8,8>>^ mas: "Tão certo como vive o Senhor , que tirou e trouxe a descendência da casa de Israel da terra do Norte e de todas as terras para onde os tinha dispersado". E habitarão na sua própria terra.

[[v24-23-9]]

^<<v24-23-9,9>>^ A respeito dos profetas: "O meu coração está partido dentro de mim. Todos os meus ossos estremecem. Sou como um homem embriagado e como um homem vencido pelo vinho, por causa do Senhor e por causa das suas santas palavras.

[[v24-23-10]]

^<<v24-23-10,10>>^ Porque a terra está cheia de adúlteros e chora por causa da maldição divina; os pastos do deserto estão secos. Porque o modo de vida deles é mau, e seu uso da força não é reto."

[[v24-23-11]]

^<<v24-23-11,11>>^ "Pois tanto o profeta como o sacerdote estão contaminados; até na minha casa achei a sua maldade", diz o Senhor .

[[v24-23-12]]

^<<v24-23-12,12>>^ "Portanto, o caminho deles será como lugares escorregadios na escuridão, para a qual serão empurrados e na qual cairão. Porque trarei sobre eles a calamidade, o ano da sua punição", diz o Senhor .

[[v24-23-13]]

^<<v24-23-13,13>>^ "Nos profetas de Samaria vi algo que causa desgosto: profetizaram por Baal e fizeram o meu povo de Israel andar errante.

[[v24-23-14]]

^<<v24-23-14,14>>^ Mas nos profetas de Jerusalém vejo coisa horrenda: cometem adultério, andam com falsidade e fortalecem as mãos dos malfeitores, para que não se convertam da sua maldade. Para mim, todos eles se tornaram como Sodoma, e os moradores de Jerusalém, como Gomorra.

[[v24-23-15]]

^<<v24-23-15,15>>^ Portanto, assim diz o Senhor  dos Exércitos a respeito dos profetas: Eis que os alimentarei com absinto e lhes darei de beber água envenenada; porque dos profetas de Jerusalém se derramou a impiedade sobre toda a terra."

[[v24-23-16]]

^<<v24-23-16,16>>^ Assim diz o Senhor  dos Exércitos: — Não deem ouvidos às palavras dos profetas que profetizam entre vocês e que os enchem de falsas esperanças; falam as visões do seu coração, não o que vem da boca do Senhor .

[[v24-23-17]]

^<<v24-23-17,17>>^ Dizem continuamente aos que me desprezam: "O Senhor  disse: Vocês terão paz"; e a todos os que andam segundo a dureza do seu coração dizem: "Nenhum mal lhes sobrevirá."

[[v24-23-18]]

^<<v24-23-18,18>>^ Porque quem esteve no conselho do Senhor , e viu, e ouviu a sua palavra? Quem esteve atento à sua palavra e a ouviu?

[[v24-23-19]]

^<<v24-23-19,19>>^ Eis a tempestade do Senhor ! O furor saiu, e um vendaval passou sobre a cabeça dos ímpios.

[[v24-23-20]]

^<<v24-23-20,20>>^ A ira do Senhor  não se desviará até que ele execute e cumpra os desígnios do seu coração. Nos últimos dias, vocês entenderão isso claramente.

[[v24-23-21]]

^<<v24-23-21,21>>^ "Não mandei esses profetas, mas eles foram correndo; não lhes falei, mas eles profetizaram.

[[v24-23-22]]

^<<v24-23-22,22>>^ Mas, se tivessem estado no meu conselho, teriam anunciado as minhas palavras ao meu povo e o teriam feito voltar do seu mau caminho e da maldade das suas ações."

[[v24-23-23]]

^<<v24-23-23,23>>^ — Sou eu Deus apenas de perto, diz o Senhor , e não também Deus de longe?

[[v24-23-24]]

^<<v24-23-24,24>>^ Pode alguém se ocultar em esconderijos, de modo que eu não o veja? — diz o Senhor . Não encho eu os céus e a terra? — diz o Senhor .

[[v24-23-25]]

^<<v24-23-25,25>>^ Tenho ouvido o que dizem aqueles profetas, proclamando mentiras em meu nome, dizendo: "Sonhei, sonhei."

[[v24-23-26]]

^<<v24-23-26,26>>^ Até quando acontecerá isso no coração dos profetas que proclamam mentiras, que proclamam só o engano do próprio coração?

[[v24-23-27]]

^<<v24-23-27,27>>^ Até quando tentarão fazer com que o meu povo se esqueça do meu nome por meio dos sonhos que contam uns aos outros, assim como os pais deles se esqueceram do meu nome, por causa de Baal?

[[v24-23-28]]

^<<v24-23-28,28>>^ O profeta que tem um sonho conte-o como um simples sonho. Mas aquele em quem está a minha palavra fale a minha palavra com verdade. O que é que a palha tem a ver com o trigo? — diz o Senhor .

[[v24-23-29]]

^<<v24-23-29,29>>^ Não é a minha palavra como fogo, diz o Senhor , e como um martelo que despedaça a rocha?

[[v24-23-30]]

^<<v24-23-30,30>>^ Portanto, eis que eu sou contra esses profetas, diz o Senhor , que roubam as minhas palavras uns dos outros.

[[v24-23-31]]

^<<v24-23-31,31>>^ Eis que eu sou contra esses profetas, diz o Senhor , que pregam a sua própria palavra e afirmam: "Ele disse."

[[v24-23-32]]

^<<v24-23-32,32>>^ Eis que eu sou contra os que profetizam sonhos mentirosos, diz o Senhor , e os contam, e com as suas mentiras e leviandades fazem o meu povo andar errante. Eu não os enviei, nem lhes dei ordem alguma; e eles não trazem nenhum proveito a este povo, diz o Senhor .

[[v24-23-33]]

^<<v24-23-33,33>>^ — Quando, pois, este povo ou um profeta ou um sacerdote perguntar a você, Jeremias: "Qual é a sentença pesada do Senhor ?", responda: "Vocês são o peso, e eu os lançarei fora", diz o Senhor .

[[v24-23-34]]

^<<v24-23-34,34>>^ E, se um profeta, um sacerdote, ou alguém do povo disser: "Sentença pesada do Senhor ", castigarei esse homem e a sua casa.

[[v24-23-35]]

^<<v24-23-35,35>>^ Em vez disso, cada um deveria perguntar ao seu companheiro e ao seu irmão: "O que o Senhor  respondeu? O que foi que o Senhor  falou?"

[[v24-23-36]]

^<<v24-23-36,36>>^ Mas nunca mais vocês devem fazer menção das palavras "sentença pesada do Senhor ", pois o que se tornará um peso para alguém é a própria palavra que ele falou. Porque vocês torcem as palavras do Deus vivo, do Senhor  dos Exércitos, o nosso Deus.

[[v24-23-37]]

^<<v24-23-37,37>>^ O que você deve perguntar a um profeta é: "O que foi que o Senhor  lhe respondeu? O que foi que o Senhor  falou?"

[[v24-23-38]]

^<<v24-23-38,38>>^ Mas, porque vocês dizem: "Sentença pesada do Senhor ", assim diz o Senhor : Porque vocês continuam a usar as palavras "sentença pesada do Senhor ", quando eu lhes havia proibido de fazer isso,

[[v24-23-39]]

^<<v24-23-39,39>>^ eu os levantarei e os lançarei fora da minha presença, tanto vocês como a cidade que dei a vocês e aos seus pais.

[[v24-23-40]]

^<<v24-23-40,40>>^ Porei sobre vocês perpétuo desprezo e eterna vergonha, que jamais serão esquecidos.

'''

xref:024-jeremias/024-jeremias-022.adoc#v24-22-0[&#60; Capítulo Anterior] | <<v24-23-0,Topo>> | xref:024-jeremias/024-jeremias-024.adoc#v24-24-0[Próximo Capítulo &#62;]