include::./index.adoc[]

[[v24-33-0]]
=== Jeremias, 33
// naa ?, NAA - Nova Almeida Atualizada

[[v24-33-1]]

^<<v24-33-1,1>>^ Quando Jeremias ainda estava encarcerado no pátio da guarda, a palavra do Senhor  veio a ele pela segunda vez, dizendo:

[[v24-33-2]]

^<<v24-33-2,2>>^ — Assim diz o Senhor  que faz estas coisas, o Senhor  que as forma para as estabelecer — Senhor  é o seu nome:

[[v24-33-3]]

^<<v24-33-3,3>>^ Chame por mim e eu responderei; eu lhe anunciarei coisas grandes e ocultas, que você não conhece.

[[v24-33-4]]

^<<v24-33-4,4>>^ Porque assim diz o Senhor , o Deus de Israel, a respeito das casas desta cidade e das casas dos reis de Judá, que foram derrubadas para defender a cidade contra as rampas de ataque e a espada:

[[v24-33-5]]

^<<v24-33-5,5>>^ Quando se der a batalha contra os caldeus, eu as encherei de cadáveres daqueles que serão feridos por minha ira e meu furor. Porque desta cidade escondi o meu rosto, por causa de toda a sua maldade.

[[v24-33-6]]

^<<v24-33-6,6>>^ — Eis que lhe trarei saúde e cura e os sararei; e lhes revelarei abundância de paz e segurança.

[[v24-33-7]]

^<<v24-33-7,7>>^ Restaurarei a sorte de Judá e de Israel e os edificarei como no princípio.

[[v24-33-8]]

^<<v24-33-8,8>>^ Eu os purificarei de toda a sua iniquidade com que pecaram contra mim e perdoarei todas as suas iniquidades com que pecaram e se revoltaram contra mim.

[[v24-33-9]]

^<<v24-33-9,9>>^ Jerusalém será para mim um motivo de fama, louvor e glória, entre todas as nações da terra que ouvirem todo o bem que eu lhe faço. Temerão e tremerão por causa de todo o bem e por causa de toda a paz que eu lhe dou.

[[v24-33-10]]

^<<v24-33-10,10>>^ Assim diz o Senhor : — Neste lugar, que vocês dizem que está deserto, sem pessoas e sem animais, nas cidades de Judá e nas ruas de Jerusalém, que estão arrasadas, sem pessoas, sem moradores e sem animais, ainda se ouvirá

[[v24-33-11]]

^<<v24-33-11,11>>^ o som das festas e da alegria, a voz do noivo e a voz da noiva, e a voz dos que cantam: "Deem graças ao Senhor  dos Exércitos, porque ele é bom, porque a sua misericórdia dura para sempre." — Também se ouvirá a voz dos que trazem ofertas de ações de graças à Casa do Senhor ; porque restaurarei a sorte da terra como no princípio, diz o Senhor .

[[v24-33-12]]

^<<v24-33-12,12>>^ Assim diz o Senhor  dos Exércitos: — Ainda neste lugar, que está deserto, sem pessoas e sem animais, e em todas as suas cidades, haverá moradas onde pastores farão repousar os seus rebanhos.

[[v24-33-13]]

^<<v24-33-13,13>>^ Nas cidades da região montanhosa, nas cidades da Sefelá, nas cidades do Sul, na terra de Benjamim, nos arredores de Jerusalém e nas cidades de Judá, ainda passarão os rebanhos pelas mãos de quem os conte, diz o Senhor .

[[v24-33-14]]

^<<v24-33-14,14>>^ — Eis que vêm dias, diz o Senhor , em que cumprirei a promessa que fiz à casa de Israel e à casa de Judá.

[[v24-33-15]]

^<<v24-33-15,15>>^ Naqueles dias e naquele tempo, farei brotar a Davi um Renovo de justiça, e ele executará o juízo e a justiça na terra.

[[v24-33-16]]

^<<v24-33-16,16>>^ Naqueles dias, Judá será salvo e Jerusalém habitará em segurança; ela será chamada " Senhor , Justiça Nossa".

[[v24-33-17]]

^<<v24-33-17,17>>^ — Porque assim diz o Senhor : Nunca faltará a Davi homem que se assente no trono da casa de Israel,

[[v24-33-18]]

^<<v24-33-18,18>>^ nem aos sacerdotes levitas faltará homem diante de mim, para que ofereça holocausto, queime oferta de cereais e faça sacrifício todos os dias.

[[v24-33-19]]

^<<v24-33-19,19>>^ A palavra do Senhor  veio a Jeremias, dizendo:

[[v24-33-20]]

^<<v24-33-20,20>>^ — Assim diz o Senhor : Se vocês puderem invalidar a minha aliança com o dia e a minha aliança com a noite, de tal modo que não haja nem dia nem noite a seu tempo,

[[v24-33-21]]

^<<v24-33-21,21>>^ então também poderá ser invalidada a minha aliança com Davi, meu servo, para que ele não tenha filho que reine no seu trono. Também poderá ser invalidada a minha aliança com os sacerdotes levitas, meus ministros.

[[v24-33-22]]

^<<v24-33-22,22>>^ Como não se pode contar o exército dos céus nem medir a areia do mar, assim tornarei incontável a descendência de Davi, meu servo, e os levitas que ministram diante de mim.

[[v24-33-23]]

^<<v24-33-23,23>>^ A palavra do Senhor  veio a Jeremias, dizendo:

[[v24-33-24]]

^<<v24-33-24,24>>^ — Você notou o que esse povo está dizendo? Estão dizendo: "As duas famílias que o Senhor  escolheu, essas ele rejeitou." Assim desprezam o meu povo, ao ponto de não considerá-lo mais uma nação.

[[v24-33-25]]

^<<v24-33-25,25>>^ Assim diz o Senhor : — Se a minha aliança com o dia e com a noite não permanecer, e se eu não mantiver as leis fixas dos céus e da terra,

[[v24-33-26]]

^<<v24-33-26,26>>^ então também rejeitarei a descendência de Jacó e de Davi, meu servo, de modo que não tome da sua descendência quem domine sobre a descendência de Abraão, Isaque e Jacó. Porque restaurarei a sua sorte e deles me compadecerei.

'''

xref:024-jeremias/024-jeremias-032.adoc#v24-32-0[&#60; Capítulo Anterior] | <<v24-33-0,Topo>> | xref:024-jeremias/024-jeremias-034.adoc#v24-34-0[Próximo Capítulo &#62;]