include::./index.adoc[]

[[v24-18-0]]
=== Jeremias, 18
// naa ?, NAA - Nova Almeida Atualizada

[[v24-18-1]]

^<<v24-18-1,1>>^ Palavra que foi dita a Jeremias da parte do Senhor :

[[v24-18-2]]

^<<v24-18-2,2>>^ — Levante-se e desça até a casa do oleiro, e lá você ouvirá as minhas palavras.

[[v24-18-3]]

^<<v24-18-3,3>>^ Desci à casa do oleiro, e eis que ele estava trabalhando sobre a roda.

[[v24-18-4]]

^<<v24-18-4,4>>^ Como o vaso que o oleiro fazia de barro se estragou nas suas mãos, ele tornou a fazer dele outro vaso, segundo bem lhe pareceu.

[[v24-18-5]]

^<<v24-18-5,5>>^ Então a palavra do Senhor  veio a mim, dizendo:

[[v24-18-6]]

^<<v24-18-6,6>>^ — Casa de Israel, será que não posso fazer com vocês como fez esse oleiro? — diz o Senhor . Eis que, como o barro na mão do oleiro, assim são vocês na minha mão, ó casa de Israel.

[[v24-18-7]]

^<<v24-18-7,7>>^ No momento em que eu falar a respeito de uma nação ou de um reino para o arrancar, derrubar e destruir,

[[v24-18-8]]

^<<v24-18-8,8>>^ se essa nação se converter da maldade contra a qual eu falei, também eu mudarei de ideia a respeito do mal que pensava fazer-lhe.

[[v24-18-9]]

^<<v24-18-9,9>>^ E, no momento em que eu falar a respeito de uma nação ou de um reino, para o edificar e plantar,

[[v24-18-10]]

^<<v24-18-10,10>>^ se ele fizer o que é mau aos meus olhos e não obedecer à minha voz, então eu mudarei de ideia quanto ao bem que havia prometido fazer.

[[v24-18-11]]

^<<v24-18-11,11>>^ Portanto, fale agora ao povo de Judá e aos moradores de Jerusalém, dizendo: Assim diz o Senhor : "Eis que estou forjando uma calamidade e formando um plano contra vocês. Por isso, convertam-se, cada um de vocês, do seu mau caminho e corrijam a sua conduta e as suas ações."

[[v24-18-12]]

^<<v24-18-12,12>>^ Mas eles dizem: "Não! É inútil! Porque seguiremos os nossos planos, e cada um fará segundo a dureza do seu coração maligno."

[[v24-18-13]]

^<<v24-18-13,13>>^ Portanto, assim diz o Senhor : "Perguntem agora entre os gentios se alguém já ouviu uma coisa dessas. A virgem de Israel fez uma coisa sobremaneira horrenda!

[[v24-18-14]]

^<<v24-18-14,14>>^ Será que a neve deixará o Líbano, a rocha que se ergue na planície? Ou faltarão as águas que vêm de longe, frias e correntes?

[[v24-18-15]]

^<<v24-18-15,15>>^ Mas o meu povo se esqueceu de mim. Queimou incenso aos ídolos, que os fizeram tropeçar nos seus caminhos e nas veredas antigas, para que andassem por desvios, por caminhos não aterrados,

[[v24-18-16]]

^<<v24-18-16,16>>^ para fazerem da sua terra um objeto de horror e de incessantes vaias. Todo aquele que passar por ela ficará espantado e balançará a cabeça.

[[v24-18-17]]

^<<v24-18-17,17>>^ Como vento leste, eu os espalharei diante dos inimigos. Eu lhes mostrarei as costas e não o rosto, no dia da sua calamidade."

[[v24-18-18]]

^<<v24-18-18,18>>^ Então disseram: — Venham! Vamos fazer planos contra Jeremias. Porque não há de faltar a lei ao sacerdote, nem o conselho ao sábio, nem a palavra ao profeta. Venham! Vamos fazer acusações contra ele e não dar atenção a nenhuma das suas palavras.

[[v24-18-19]]

^<<v24-18-19,19>>^ — Olha para mim, Senhor , e ouve a voz dos que me acusam.

[[v24-18-20]]

^<<v24-18-20,20>>^ Por acaso, é com o mal que se paga o bem? Pois abriram uma cova para mim. Lembra-te de que eu compareci à tua presença, para interceder pelo bem-estar deles, para desviar deles a tua ira.

[[v24-18-21]]

^<<v24-18-21,21>>^ Portanto, entrega os filhos deles à fome e ao poder da espada. Que as mulheres sejam roubadas dos filhos e fiquem viúvas. Que os maridos sejam mortos pela peste, e que os jovens sejam mortos à espada na batalha.

[[v24-18-22]]

^<<v24-18-22,22>>^ Ouça-se o clamor que vem de suas casas, quando trouxeres bandos contra eles de repente. Porque abriram uma cova para prender-me e puseram armadilhas para os meus pés.

[[v24-18-23]]

^<<v24-18-23,23>>^ Mas tu, ó Senhor , conheces todos os planos que fizeram contra mim para me matar. Não perdoes a maldade deles, nem apagues o seu pecado de diante da tua face. Sejam eles derrubados diante de ti; age contra eles no tempo da tua ira.

'''

xref:024-jeremias/024-jeremias-017.adoc#v24-17-0[&#60; Capítulo Anterior] | <<v24-18-0,Topo>> | xref:024-jeremias/024-jeremias-019.adoc#v24-19-0[Próximo Capítulo &#62;]