include::./index.adoc[]

[[v24-49-0]]
=== Jeremias, 49
// naa ?, NAA - Nova Almeida Atualizada

[[v24-49-1]]

^<<v24-49-1,1>>^ A respeito dos filhos de Amom, assim diz o Senhor : "Por acaso Israel não tem filhos? Não tem herdeiro? Então por que Milcom herdou o território de Gade, e o seu povo mora nas cidades dessa tribo?

[[v24-49-2]]

^<<v24-49-2,2>>^ Portanto, eis que vêm dias", diz o Senhor , "em que farei ouvir o alarido de guerra em Rabá dos filhos de Amom. Ela se tornará um montão de ruínas, e as suas aldeias serão queimadas; e Israel retomará a herança que lhe havia sido tirada", diz o Senhor .

[[v24-49-3]]

^<<v24-49-3,3>>^ "Chore, povo de Hesbom, porque a cidade de Ai foi destruída. Gritem, filhos de Rabá, vistam roupa feita de pano de saco, lamentem e deem voltas por entre as muralhas. Porque Milcom irá para o cativeiro, junto com os seus sacerdotes e os seus príncipes.

[[v24-49-4]]

^<<v24-49-4,4>>^ Por que você se orgulha nos vales, nos seus vales férteis, ó filha rebelde, que confia nos seus tesouros, dizendo: ‘Quem me atacará?’

[[v24-49-5]]

^<<v24-49-5,5>>^ Eis que de todos os lados trarei terror sobre você", diz o Senhor, o Senhor  dos Exércitos. "Vocês serão dispersos, cada um numa direção, e não haverá quem consiga reunir os fugitivos."

[[v24-49-6]]

^<<v24-49-6,6>>^ — Mas depois disto mudarei a sorte dos filhos de Amom, diz o Senhor.

[[v24-49-7]]

^<<v24-49-7,7>>^ A respeito de Edom, assim diz o Senhor  dos Exércitos: "Por acaso não existe mais sabedoria em Temã? Será que pereceu o conselho dos sábios? Desvaneceu a sabedoria deles?

[[v24-49-8]]

^<<v24-49-8,8>>^ Fujam, voltem, escondam-se em cavernas, ó moradores de Dedã, porque eu trarei sobre ele a ruína de Esaú, o tempo do seu castigo.

[[v24-49-9]]

^<<v24-49-9,9>>^ Se os que colhem uvas fossem até você, não deixariam pelo menos alguns cachos? Se ladrões viessem de noite, não danificariam só o que lhes bastasse?

[[v24-49-10]]

^<<v24-49-10,10>>^ Mas eu despi Esaú, descobri os seus esconderijos, e não poderá se esconder. Está destruída a sua descendência, bem como os seus irmãos e vizinhos, e ele já não existe.

[[v24-49-11]]

^<<v24-49-11,11>>^ Deixe os seus órfãos, que eu os guardarei em vida; e as suas viúvas podem confiar em mim."

[[v24-49-12]]

^<<v24-49-12,12>>^ — Porque assim diz o Senhor : "Se até os que não estavam condenados a beber o cálice terão de bebê-lo, por que você ficaria impune? Você não ficará impune, mas certamente beberá esse cálice.

[[v24-49-13]]

^<<v24-49-13,13>>^ Porque por mim mesmo jurei, diz o Senhor , que Bozra será objeto de horror, de deboche, de desolação e de maldição; e todas as suas cidades se tornarão em ruínas perpétuas."

[[v24-49-14]]

^<<v24-49-14,14>>^ Eu ouvi uma notícia vinda do Senhor , e um mensageiro foi enviado às nações para lhes dizer: "Reúnam-se e venham atacar Edom! Preparem-se para a guerra."

[[v24-49-15]]

^<<v24-49-15,15>>^ "Eis que fiz de você uma nação pequena entre as outras, desprezada entre os povos.

[[v24-49-16]]

^<<v24-49-16,16>>^ O terror que você inspira e o orgulho do seu coração o enganaram. Você, que vive nas fendas das rochas e ocupa as alturas dos montes, ainda que eleve o seu ninho como a águia, de lá eu o derrubarei", diz o Senhor .

[[v24-49-17]]

^<<v24-49-17,17>>^ — Assim, Edom será objeto de horror; todo aquele que passar por ele ficará espantado e zombará por causa do desastre que lhe aconteceu.

[[v24-49-18]]

^<<v24-49-18,18>>^ Como na destruição de Sodoma e Gomorra e das suas cidades vizinhas, diz o Senhor , assim não habitará ninguém ali, nem morará nele homem algum.

[[v24-49-19]]

^<<v24-49-19,19>>^ Eis que, assim como o leão sobe da floresta do Jordão contra o rebanho em pasto verde, assim, num momento, farei com que Edom fuja dali. E estabelecerei sobre ele a quem eu escolher. Pois quem é semelhante a mim? Quem me pedirá contas? E quem é o pastor que me poderá resistir?

[[v24-49-20]]

^<<v24-49-20,20>>^ — Portanto, ouçam a decisão que o Senhor  tomou contra Edom, e os planos que ele fez contra os moradores de Temã. Certamente até os menores do rebanho serão arrastados. Certamente as suas moradas serão destruídas por causa deles.

[[v24-49-21]]

^<<v24-49-21,21>>^ A terra tremerá com o estrondo da sua queda; e os seus gritos serão ouvidos até o mar Vermelho.

[[v24-49-22]]

^<<v24-49-22,22>>^ Eis que um inimigo, como águia, subirá, voará e estenderá as suas asas contra Bozra. Naquele dia, o coração dos valentes de Edom será como o coração da mulher que está em dores de parto.

[[v24-49-23]]

^<<v24-49-23,23>>^ A respeito de Damasco. "As cidades de Hamate e Arpade estão envergonhadas; e, tendo ouvido más notícias, cambaleiam; são como o mar agitado, que não se pode sossegar.

[[v24-49-24]]

^<<v24-49-24,24>>^ Damasco está enfraquecida; virou as costas para fugir. Tremor tomou conta dela; angústia e dores lhe sobrevieram, como de mulher que está dando à luz.

[[v24-49-25]]

^<<v24-49-25,25>>^ Como está abandonada a famosa cidade, a cidade da alegria!

[[v24-49-26]]

^<<v24-49-26,26>>^ Portanto, os seus jovens cairão nas suas praças; todos os homens de guerra serão reduzidos a silêncio naquele dia", diz o Senhor  dos Exércitos.

[[v24-49-27]]

^<<v24-49-27,27>>^ "Porei fogo nas muralhas de Damasco, o qual queimará os palácios de Ben-Hadade."

[[v24-49-28]]

^<<v24-49-28,28>>^ A respeito de Quedar e dos reinos de Hazor, que foram derrotados por Nabucodonosor, rei da Babilônia, assim diz o Senhor : "Levantem-se e ataquem Quedar; destruam esse povo do Oriente.

[[v24-49-29]]

^<<v24-49-29,29>>^ Eles pegarão as suas tendas, os seus rebanhos; levarão embora as lonas das suas tendas, todos os seus bens e os seus camelos; e lhes gritarão: ‘Há terror por todos os lados!’

[[v24-49-30]]

^<<v24-49-30,30>>^ Fujam, afastem-se para bem longe, escondam-se em cavernas, ó moradores de Hazor", diz o Senhor . "Porque Nabucodonosor, rei da Babilônia, tomou uma decisão e formou um plano contra vocês.

[[v24-49-31]]

^<<v24-49-31,31>>^ Levantem-se, babilônios, e ataquem uma nação que vive em paz e sem desconfiar de nada", diz o Senhor ; "que não tem portões, nem ferrolhos; eles vivem isolados.

[[v24-49-32]]

^<<v24-49-32,32>>^ Os seus camelos serão para presa, e os seus muitos rebanhos de gado serão levados como despojo. Espalharei a todos os ventos aqueles que cortam os cabelos nas têmporas e de todos os lados lhes trarei a ruína", diz o Senhor .

[[v24-49-33]]

^<<v24-49-33,33>>^ "Hazor se tornará em morada de chacais, um lugar desolado para sempre. Ninguém vai morar ali, homem nenhum habitará nela."

[[v24-49-34]]

^<<v24-49-34,34>>^ Palavra do Senhor  que veio ao profeta Jeremias a respeito de Elão, no princípio do reinado de Zedequias, rei de Judá.

[[v24-49-35]]

^<<v24-49-35,35>>^ Assim diz o Senhor  dos Exércitos: — Eis que eu quebrarei o arco de Elão, a fonte do seu poder.

[[v24-49-36]]

^<<v24-49-36,36>>^ Trarei sobre Elão os quatro ventos dos quatro cantos da terra e os dispersarei na direção de todos esses ventos; e não haverá país aonde não cheguem os fugitivos de Elão.

[[v24-49-37]]

^<<v24-49-37,37>>^ Farei com que o povo de Elão trema diante dos seus inimigos e diante dos que querem matá-los. Farei vir sobre os elamitas o mal, o furor da minha ira, diz o Senhor ; e enviarei a espada após eles, até que eu os tenha destruído.

[[v24-49-38]]

^<<v24-49-38,38>>^ Porei o meu trono em Elão e destruirei dali o rei e os oficiais, diz o Senhor .

[[v24-49-39]]

^<<v24-49-39,39>>^ Mas, nos últimos dias, mudarei a sorte de Elão, diz o Senhor .

'''

xref:024-jeremias/024-jeremias-048.adoc#v24-48-0[&#60; Capítulo Anterior] | <<v24-49-0,Topo>> | xref:024-jeremias/024-jeremias-050.adoc#v24-50-0[Próximo Capítulo &#62;]