include::./index.adoc[]

[[v24-12-0]]
=== Jeremias, 12
// naa ?, NAA - Nova Almeida Atualizada

[[v24-12-1]]

^<<v24-12-1,1>>^ Justo serias, Senhor , se eu apresentasse a minha causa diante de ti. No entanto, preciso falar contigo a respeito da justiça. Por que o caminho dos ímpios prospera? Por que todos os traidores vivem em paz?

[[v24-12-2]]

^<<v24-12-2,2>>^ Tu os plantas, e eles lançam raízes; crescem e dão fruto. Estás perto dos lábios deles, mas longe do coração.

[[v24-12-3]]

^<<v24-12-3,3>>^ Mas tu, ó Senhor , me conheces; tu me vês e provas o que o meu coração sente em relação a ti. Arranca-os como ovelhas destinadas ao matadouro e separa-os para o dia da matança.

[[v24-12-4]]

^<<v24-12-4,4>>^ Até quando a terra estará de luto, e se secará a erva de todo o campo? Os animais e as aves estão morrendo por causa da maldade dos moradores da terra, que dizem: "Deus não vê aquilo que nos espera."

[[v24-12-5]]

^<<v24-12-5,5>>^ "Jeremias, se você se cansa correndo com homens que vão a pé, como poderá competir com os que vão a cavalo? Se em terra de paz você não se sente seguro, que fará na floresta do Jordão?

[[v24-12-6]]

^<<v24-12-6,6>>^ Porque até mesmo os seus irmãos e a casa de seu pai estão sendo desleais para com você; eles o perseguem com fortes gritos. Não confie neles, ainda que lhe digam coisas boas."

[[v24-12-7]]

^<<v24-12-7,7>>^ "Abandonei o meu templo, rejeitei a minha herança; entreguei aquela que eu mais amava nas mãos de seus inimigos.

[[v24-12-8]]

^<<v24-12-8,8>>^ A minha herança tornou-se para mim como um leão na floresta; levantou a voz contra mim, e por isso eu a odeio.

[[v24-12-9]]

^<<v24-12-9,9>>^ A minha herança é para mim uma ave de rapina de várias cores contra a qual se ajuntam outras aves de rapina. Vão, pois, e reúnam todos os animais do campo; que eles venham para devorá-la.

[[v24-12-10]]

^<<v24-12-10,10>>^ Muitos pastores destruíram a minha vinha e pisaram o meu campo; fizeram da porção que era o meu prazer um deserto.

[[v24-12-11]]

^<<v24-12-11,11>>^ Eles a tornaram em desolação, e, no seu abandono, ela clama a mim; toda a terra está devastada, mas não há ninguém que se importe com isso.

[[v24-12-12]]

^<<v24-12-12,12>>^ Sobre todos os lugares altos do deserto vieram destruidores; porque a espada do Senhor  devora de um a outro extremo da terra; não há paz para ninguém.

[[v24-12-13]]

^<<v24-12-13,13>>^ Semearam trigo e colheram espinhos; cansaram-se, mas sem proveito algum. Ficarão envergonhados das suas colheitas, por causa do furor da ira do Senhor ."

[[v24-12-14]]

^<<v24-12-14,14>>^ Assim diz o Senhor  a respeito de todos os meus maus vizinhos, que se apoderam da minha herança, que deixei ao meu povo de Israel: — Eis que os arrancarei da sua terra, e arrancarei a casa de Judá do meio deles.

[[v24-12-15]]

^<<v24-12-15,15>>^ Depois de os haver arrancado, eu me voltarei e terei compaixão deles e os farei voltar, cada um à sua herança, cada um à sua terra.

[[v24-12-16]]

^<<v24-12-16,16>>^ Se diligentemente aprenderem os caminhos do meu povo; se jurarem pelo meu nome, dizendo: "Tão certo como vive o Senhor ", assim como no passado ensinaram o meu povo a jurar por Baal, então serão edificados no meio do meu povo.

[[v24-12-17]]

^<<v24-12-17,17>>^ Mas, se não quiserem ouvir, arrancarei essa nação; arrancarei e destruirei, diz o Senhor .

'''

xref:024-jeremias/024-jeremias-011.adoc#v24-11-0[&#60; Capítulo Anterior] | <<v24-12-0,Topo>> | xref:024-jeremias/024-jeremias-013.adoc#v24-13-0[Próximo Capítulo &#62;]