include::./index.adoc[]

[[v24-1-0]]
=== Jeremias, 1
// naa ?, NAA - Nova Almeida Atualizada

[[v24-1-1]]

^<<v24-1-1,1>>^ Palavras de Jeremias, filho de Hilquias, um dos sacerdotes que estavam em Anatote, na terra de Benjamim.

[[v24-1-2]]

^<<v24-1-2,2>>^ A palavra do Senhor  veio a ele no décimo terceiro ano do reinado de Josias, filho de Amom e rei de Judá.

[[v24-1-3]]

^<<v24-1-3,3>>^ Veio também nos dias de Jeoaquim, filho de Josias, rei de Judá, até o fim do décimo primeiro ano do reinado de Zedequias, filho de Josias, rei de Judá. No quinto mês desse ano, os moradores de Jerusalém foram levados ao exílio.

[[v24-1-4]]

^<<v24-1-4,4>>^ A palavra do Senhor  veio a mim, dizendo:

[[v24-1-5]]

^<<v24-1-5,5>>^ "Antes de formá-lo no ventre materno, eu já o conhecia; e, antes de você nascer, eu o consagrei e constituí profeta às nações."

[[v24-1-6]]

^<<v24-1-6,6>>^ Então eu disse: — Ah! Senhor  Deus! Eis que não sei falar, porque não passo de uma criança.

[[v24-1-7]]

^<<v24-1-7,7>>^ Mas o Senhor  me disse: "Não diga: ‘Não passo de uma criança.’ Porque a todos a quem eu o enviar, você irá; e tudo o que eu lhe ordenar, você falará.

[[v24-1-8]]

^<<v24-1-8,8>>^ Não tenha medo de ninguém, porque eu estou com você para livrá-lo", diz o Senhor .

[[v24-1-9]]

^<<v24-1-9,9>>^ Depois, o Senhor  estendeu a mão e tocou na minha boca. E o Senhor  me disse: "Eis que ponho as minhas palavras na sua boca.

[[v24-1-10]]

^<<v24-1-10,10>>^ Veja! Hoje eu o constituo sobre as nações e sobre os reinos, para arrancar e derrubar, para destruir e arruinar, e também para edificar e plantar."

[[v24-1-11]]

^<<v24-1-11,11>>^ A palavra do Senhor  veio a mim, dizendo: — O que você está vendo, Jeremias? Respondi: — Vejo um ramo de amendoeira.

[[v24-1-12]]

^<<v24-1-12,12>>^ O Senhor  me disse: — Você viu bem, porque eu estou vigiando para que a minha palavra se cumpra.

[[v24-1-13]]

^<<v24-1-13,13>>^ Outra vez a palavra do Senhor  veio a mim, dizendo: — O que você está vendo? Eu respondi: — Vejo uma panela fervendo, cuja boca se inclina do Norte para cá.

[[v24-1-14]]

^<<v24-1-14,14>>^ Então o Senhor  disse: — Do Norte se derramará o mal sobre todos os habitantes da terra.

[[v24-1-15]]

^<<v24-1-15,15>>^ Pois eis que convoco todas as tribos dos reinos do Norte, diz o Senhor ; elas virão, e cada reino porá o seu trono à entrada dos portões de Jerusalém e contra todas as suas muralhas ao redor e contra todas as cidades de Judá.

[[v24-1-16]]

^<<v24-1-16,16>>^ Pronunciarei as minhas sentenças contra os moradores dessas cidades, por causa de toda a maldade deles; pois me abandonaram, queimaram incenso a deuses estranhos e adoraram as obras das suas próprias mãos.

[[v24-1-17]]

^<<v24-1-17,17>>^ Você, Jeremias, prepare-se e vá dizer-lhes tudo o que eu ordenar a você. Não se assuste por causa deles, para que eu não tenha de fazer com que você fique assustado na presença deles.

[[v24-1-18]]

^<<v24-1-18,18>>^ Quanto a mim, eis que hoje ponho você por cidade fortificada, por coluna de ferro e por muralha de bronze, contra todo o país, contra os reis de Judá, contra as suas autoridades, contra os seus sacerdotes e contra o seu povo.

[[v24-1-19]]

^<<v24-1-19,19>>^ Eles lutarão contra você, mas não conseguirão derrotá-lo; porque eu estou com você para livrá-lo, diz o Senhor .

'''

xref:023-isaias/023-isaias-066.adoc#v23-66-0[&#60; Capítulo Anterior] | <<v24-1-0,Topo>> | xref:024-jeremias/024-jeremias-002.adoc#v24-2-0[Próximo Capítulo &#62;]