include::./index.adoc[]

[[v24-13-0]]
=== Jeremias, 13
// naa ?, NAA - Nova Almeida Atualizada

[[v24-13-1]]

^<<v24-13-1,1>>^ Assim me disse o Senhor : — Vá, compre um cinto de linho e coloque-o em volta da cintura. Não o molhe antes disso.

[[v24-13-2]]

^<<v24-13-2,2>>^ Comprei o cinto, segundo a palavra do Senhor , e o pus em volta da cintura.

[[v24-13-3]]

^<<v24-13-3,3>>^ Então, pela segunda vez a palavra do Senhor  veio a mim, dizendo:

[[v24-13-4]]

^<<v24-13-4,4>>^ — Pegue o cinto que você comprou e que está em volta de sua cintura, vá até o rio Eufrates e esconda-o ali na fenda de uma rocha.

[[v24-13-5]]

^<<v24-13-5,5>>^ Fui e escondi o cinto junto ao rio Eufrates, como o Senhor  me havia ordenado.

[[v24-13-6]]

^<<v24-13-6,6>>^ Passados muitos dias, o Senhor  me disse: — Levante-se, vá até o rio Eufrates e pegue o cinto que eu lhe ordenei que escondesse ali.

[[v24-13-7]]

^<<v24-13-7,7>>^ Fui até o rio Eufrates, cavei e tirei o cinto do lugar onde o havia escondido. E eis que o cinto tinha apodrecido e não prestava para nada.

[[v24-13-8]]

^<<v24-13-8,8>>^ Então a palavra do Senhor  veio a mim, dizendo:

[[v24-13-9]]

^<<v24-13-9,9>>^ — Assim diz o Senhor : Deste modo farei também apodrecer o orgulho de Judá e o grande orgulho de Jerusalém.

[[v24-13-10]]

^<<v24-13-10,10>>^ Este povo mau, que se recusa a ouvir as minhas palavras, que anda segundo a dureza do seu coração e segue outros deuses para os servir e adorar, será tal como este cinto, que não presta para nada.

[[v24-13-11]]

^<<v24-13-11,11>>^ Porque, assim como o cinto se apega à cintura de um homem, assim eu fiz apegar-se a mim toda a casa de Israel e toda a casa de Judá, diz o Senhor , para que me fossem por povo, nome, louvor e glória; mas eles não quiseram ouvir.

[[v24-13-12]]

^<<v24-13-12,12>>^ Diga-lhes também esta palavra: — Assim diz o Senhor , Deus de Israel: Toda jarra deve ficar cheia de vinho. Então eles dirão a você: "Não sabemos nós muito bem que toda jarra deve ficar cheia de vinho?"

[[v24-13-13]]

^<<v24-13-13,13>>^ Mas você responderá: "Assim diz o Senhor : Eis que eu vou encher de embriaguez todos os moradores desta terra: os reis que se assentam no trono de Davi, os sacerdotes, os profetas e todos os moradores de Jerusalém.

[[v24-13-14]]

^<<v24-13-14,14>>^ Eu os farei em pedaços, atirando uns contra os outros, tanto os pais como os filhos, diz o Senhor . Não pouparei, não terei pena, nem terei compaixão deles; nada me impedirá de destruí-los."

[[v24-13-15]]

^<<v24-13-15,15>>^ Ouçam e prestem atenção: não sejam orgulhosos! Porque o Senhor  falou.

[[v24-13-16]]

^<<v24-13-16,16>>^ Deem glória ao Senhor , seu Deus, antes que ele faça vir as trevas, antes que os pés de vocês tropecem nos montes tenebrosos e antes que, esperando vocês a luz, ele a mude em sombra de morte e a reduza à escuridão.

[[v24-13-17]]

^<<v24-13-17,17>>^ Mas, se vocês não quiserem ouvir, eu chorarei em segredo por causa do orgulho de vocês. Chorarei amargamente e os meus olhos se desfarão em lágrimas, porque o rebanho do Senhor foi levado cativo.

[[v24-13-18]]

^<<v24-13-18,18>>^ Diga ao rei e à rainha-mãe: "Humilhem-se e sentem no chão, porque as gloriosas coroas caíram da cabeça de vocês."

[[v24-13-19]]

^<<v24-13-19,19>>^ As cidades do Sul estão fechadas, e não há ninguém que as abra. Todo o Judá foi levado para o exílio, todos cativos.

[[v24-13-20]]

^<<v24-13-20,20>>^ "Levantem os olhos e vejam os que vêm do Norte. Onde está o rebanho que lhe foi confiado, o seu lindo rebanho?

[[v24-13-21]]

^<<v24-13-21,21>>^ O que você dirá, quando ele puser por cabeça sobre você aqueles a quem você ensinou a ser amigos? Será que você não sentirá dores, como as da mulher que está dando à luz?

[[v24-13-22]]

^<<v24-13-22,22>>^ Talvez você se pergunte: ‘Por que me sobrevieram estas coisas?’ Então saiba que foi por causa da multidão de suas maldades que as abas de sua saia foram levantadas e os seus calcanhares sofrem violência."

[[v24-13-23]]

^<<v24-13-23,23>>^ "Será que o etíope pode mudar a sua pele ou o leopardo, as suas manchas? Se fosse possível, também vocês poderiam fazer o bem, estando acostumados a fazer o mal.

[[v24-13-24]]

^<<v24-13-24,24>>^ Por isso eu os espalharei como a palha que é levada pelo vento do deserto.

[[v24-13-25]]

^<<v24-13-25,25>>^ Esta será a parte que lhe cabe, a porção que reservei para você", diz o Senhor , "porque você se esqueceu de mim e confiou em mentiras.

[[v24-13-26]]

^<<v24-13-26,26>>^ Assim, eu mesmo levantarei as abas de sua saia até a altura do seu rosto, e aparecerão as suas vergonhas.

[[v24-13-27]]

^<<v24-13-27,27>>^ Tenho visto as suas abominações sobre as colinas e no campo, a saber, os seus adultérios, os seus relinchos e a vergonha da sua prostituição. Ai de você, Jerusalém! Você não vai se purificar? Quanto tempo isso vai durar?"

'''

xref:024-jeremias/024-jeremias-012.adoc#v24-12-0[&#60; Capítulo Anterior] | <<v24-13-0,Topo>> | xref:024-jeremias/024-jeremias-014.adoc#v24-14-0[Próximo Capítulo &#62;]