include::./index.adoc[]

[[v24-4-0]]
=== Jeremias, 4
// naa ?, NAA - Nova Almeida Atualizada

[[v24-4-1]]

^<<v24-4-1,1>>^ "Se você voltar, ó Israel, volte para mim", diz o Senhor ; "se remover as suas abominações de diante de mim, você não mais andará sem rumo;

[[v24-4-2]]

^<<v24-4-2,2>>^ se jurar em verdade, em juízo e em justiça, dizendo: ‘Tão certo como vive o Senhor ’, então nele serão benditas as nações e nele se gloriarão."

[[v24-4-3]]

^<<v24-4-3,3>>^ Porque assim diz o Senhor  aos homens de Judá e Jerusalém: "Lavrem os campos não cultivados e não semeiem no meio dos espinhos.

[[v24-4-4]]

^<<v24-4-4,4>>^ Deixem-se circuncidar para o Senhor ; circuncidem o seu coração, ó homens de Judá e moradores de Jerusalém, para que o meu furor não saia como fogo, por causa da maldade do que vocês fazem, e queime, sem que haja quem o possa apagar."

[[v24-4-5]]

^<<v24-4-5,5>>^ Anunciem em Judá, proclamem em Jerusalém e digam: "Toquem a trombeta na terra!" Gritem bem alto, dizendo: "Reúnam-se, e entremos nas cidades fortificadas!"

[[v24-4-6]]

^<<v24-4-6,6>>^ Levantem um estandarte, fujam e não se detenham no caminho; porque eu faço vir do Norte um mal, uma grande destruição.

[[v24-4-7]]

^<<v24-4-7,7>>^ Um leão já subiu do seu esconderijo, um destruidor das nações já partiu; já deixou o seu lugar para fazer desta terra uma desolação, a fim de que as suas cidades, ó Judá, sejam destruídas e fiquem desabitadas.

[[v24-4-8]]

^<<v24-4-8,8>>^ Por isso, vistam roupa feita de pano de saco, lamentem e uivem, porque o furor da ira do Senhor não se desviou de nós.

[[v24-4-9]]

^<<v24-4-9,9>>^ — Naquele dia, diz o Senhor , o rei e as autoridades perderão a coragem, os sacerdotes ficarão pasmados, e os profetas, espantados.

[[v24-4-10]]

^<<v24-4-10,10>>^ Então eu disse: — Ah! Senhor  Deus! Na verdade, enganaste completamente este povo e Jerusalém, dizendo: "Vocês terão paz!", quando uma espada lhes penetra até a alma.

[[v24-4-11]]

^<<v24-4-11,11>>^ Naquele tempo, se dirá a este povo e à cidade de Jerusalém: — Um vento abrasador, vindo dos lugares altos do deserto, sopra na direção da filha do meu povo, não para peneirar nem para limpar.

[[v24-4-12]]

^<<v24-4-12,12>>^ Um vento mais forte do que este virá ainda de minha parte, e, então, também eu pronunciarei a sentença contra eles.

[[v24-4-13]]

^<<v24-4-13,13>>^ Eis que o destruidor avança como as nuvens; os seus carros de guerra são como a tempestade; os seus cavalos são mais ligeiros do que as águias. Ai de nós! Estamos perdidos!

[[v24-4-14]]

^<<v24-4-14,14>>^ Lave a maldade do seu coração, ó Jerusalém, para que você seja salva! Até quando você abrigará esses seus maus pensamentos?

[[v24-4-15]]

^<<v24-4-15,15>>^ Uma voz se faz ouvir desde Dã e anuncia a calamidade desde a região montanhosa de Efraim!

[[v24-4-16]]

^<<v24-4-16,16>>^ Anunciem isto às nações e proclamem contra Jerusalém: "De uma terra longínqua vêm sitiadores e levantam a voz contra as cidades de Judá.

[[v24-4-17]]

^<<v24-4-17,17>>^ Como os guardas de um campo, eles cercam Jerusalém, porque ela se rebelou contra mim", diz o Senhor .

[[v24-4-18]]

^<<v24-4-18,18>>^ "A sua conduta e as suas obras fizeram vir estas coisas sobre você, ó Jerusalém; a sua calamidade, que é amarga, atinge até o seu coração."

[[v24-4-19]]

^<<v24-4-19,19>>^ Ah! Meu coração! Meu coração! Eu me contorço em dores. Oh! As paredes do meu coração! Meu coração se agita! Não posso ficar calado, porque ouvi o som da trombeta e os gritos de guerra.

[[v24-4-20]]

^<<v24-4-20,20>>^ Golpe sobre golpe se anuncia, pois a terra toda já está destruída; de repente, foram destruídas as minhas tendas; num momento, foram rasgadas as suas lonas.

[[v24-4-21]]

^<<v24-4-21,21>>^ Até quando terei de ver o estandarte do inimigo, terei de ouvir o som da trombeta?

[[v24-4-22]]

^<<v24-4-22,22>>^ "O meu povo é insensato; eles não me conhecem. São filhos tolos; eles não têm entendimento. São sábios para o mal e não sabem fazer o bem."

[[v24-4-23]]

^<<v24-4-23,23>>^ Olhei para a terra, e eis que ela estava sem forma e vazia; olhei para os céus, e eles não tinham luz.

[[v24-4-24]]

^<<v24-4-24,24>>^ Olhei para os montes, e eis que tremiam; e todas as colinas estremeciam.

[[v24-4-25]]

^<<v24-4-25,25>>^ Olhei, e eis que não havia ninguém, e todas as aves dos céus haviam fugido.

[[v24-4-26]]

^<<v24-4-26,26>>^ Olhei ainda, e eis que a terra fértil era um deserto, e todas as suas cidades estavam derrubadas em ruínas diante do Senhor , diante do furor da sua ira.

[[v24-4-27]]

^<<v24-4-27,27>>^ Pois assim diz o Senhor : "Toda a terra será devastada, porém não vou destruí-la completamente."

[[v24-4-28]]

^<<v24-4-28,28>>^ "Por isso, a terra pranteará, e os céus, lá em cima, escurecerão; porque falei, resolvi, não mudo de ideia nem volto atrás."

[[v24-4-29]]

^<<v24-4-29,29>>^ "Ao clamor dos cavaleiros e dos flecheiros, todas as cidades fogem; entram pelas selvas e sobem pelos penhascos; todas as cidades ficam abandonadas, e já ninguém habita nelas.

[[v24-4-30]]

^<<v24-4-30,30>>^ E você, cidade destruída, por que está fazendo isso? Por que se veste de escarlate, se enfeita com joias de ouro e se pinta em volta dos olhos, se é em vão que você se embeleza? Os seus amantes a desprezam e querem matá-la.

[[v24-4-31]]

^<<v24-4-31,31>>^ Porque ouço um grito como de parturiente, uma angústia como da mulher que está dando à luz o seu primeiro filho. É o grito da filha de Sião, ofegante, que estende as mãos, dizendo: ‘Ai de mim agora! Porque a minha alma desfalece diante dos assassinos.’"

'''

xref:024-jeremias/024-jeremias-003.adoc#v24-3-0[&#60; Capítulo Anterior] | <<v24-4-0,Topo>> | xref:024-jeremias/024-jeremias-005.adoc#v24-5-0[Próximo Capítulo &#62;]