include::./index.adoc[]

[[v24-22-0]]
=== Jeremias, 22
// naa ?, NAA - Nova Almeida Atualizada

[[v24-22-1]]

^<<v24-22-1,1>>^ — Assim diz o Senhor : Desça ao palácio do rei de Judá e anuncie ali esta palavra:

[[v24-22-2]]

^<<v24-22-2,2>>^ Ouça a palavra do Senhor , ó rei de Judá, você que se assenta no trono de Davi. Que ouçam também os seus servos e o seu povo que entra por estas portas.

[[v24-22-3]]

^<<v24-22-3,3>>^ Assim diz o Senhor : Pratiquem o direito e a justiça e livrem o oprimido das mãos do opressor. Não oprimam nem maltratem o estrangeiro, nem o órfão, nem a viúva. Não derramem sangue inocente neste lugar.

[[v24-22-4]]

^<<v24-22-4,4>>^ Porque, se vocês de fato cumprirem esta palavra, então pelas portas deste palácio entrarão os reis que se assentarão no trono de Davi, em carros e montados em cavalos, eles, os seus servos e o seu povo.

[[v24-22-5]]

^<<v24-22-5,5>>^ Mas, se não ouvirem estas palavras, juro por mim mesmo, diz o Senhor , que este palácio se tornará em ruínas.

[[v24-22-6]]

^<<v24-22-6,6>>^ Porque assim diz o Senhor  a respeito do palácio do rei de Judá: "Para mim você é como Gileade e o pico dos montes do Líbano, mas certamente farei de você um deserto e cidades desabitadas.

[[v24-22-7]]

^<<v24-22-7,7>>^ Designarei contra você destruidores, cada um com as suas armas; eles cortarão os seus melhores cedros e os lançarão no fogo."

[[v24-22-8]]

^<<v24-22-8,8>>^ — Muitas nações passarão por esta cidade, e dirão uns aos outros: "Por que o Senhor  fez uma coisa dessas com esta grande cidade?"

[[v24-22-9]]

^<<v24-22-9,9>>^ Então se responderá: "Porque abandonaram a aliança do Senhor , seu Deus, e adoraram outros deuses e os serviram."

[[v24-22-10]]

^<<v24-22-10,10>>^ Não chorem pelo rei morto, nem lamentem a sua perda. Chorem amargamente por aquele que foi para o exílio, porque nunca mais voltará nem verá a terra onde nasceu.

[[v24-22-11]]

^<<v24-22-11,11>>^ Porque assim diz o Senhor  a respeito de Salum, filho de Josias, rei de Judá, que reinou em lugar de Josias, seu pai, e que foi levado deste lugar: — Nunca mais voltará para cá.

[[v24-22-12]]

^<<v24-22-12,12>>^ Porque morrerá no lugar para onde o levaram cativo e nunca mais verá esta terra.

[[v24-22-13]]

^<<v24-22-13,13>>^ "Ai daquele que edifica a sua casa com injustiça e os seus aposentos, contrariando o direito! Que faz o seu próximo trabalhar de graça, sem lhe pagar o salário.

[[v24-22-14]]

^<<v24-22-14,14>>^ Ai daquele que diz: ‘Edificarei para mim uma casa bem grande, com aposentos espaçosos.’ Então ele põe janelas na casa, forra as paredes com cedro, e a pinta de vermelho.

[[v24-22-15]]

^<<v24-22-15,15>>^ Você acha que reinará só porque compete com outros no uso de cedro? Por acaso o seu pai não comeu e bebeu, e não praticou o juízo e a justiça? Por isso, tudo lhe corria bem.

[[v24-22-16]]

^<<v24-22-16,16>>^ Julgou a causa do aflito e do necessitado, e tudo lhe corria bem. Por acaso, não é isso que se chama conhecer-me?" — diz o Senhor .

[[v24-22-17]]

^<<v24-22-17,17>>^ "Mas os seus olhos e o seu coração estão voltados somente para a ganância, para derramar sangue inocente e para levar a efeito a violência e a extorsão."

[[v24-22-18]]

^<<v24-22-18,18>>^ Portanto, assim diz o Senhor  a respeito de Jeoaquim, filho de Josias, rei de Judá: "Não o lamentarão, dizendo: ‘Ai, meu irmão!’ Ou: ‘Ai, minha irmã!’ Nem o lamentarão, dizendo: ‘Ai, senhor!’ Ou: ‘Ai, majestade!’

[[v24-22-19]]

^<<v24-22-19,19>>^ Como se sepulta um jumento, assim o sepultarão: será arrastado e lançado para bem longe, para fora dos portões de Jerusalém."

[[v24-22-20]]

^<<v24-22-20,20>>^ "Suba ao Líbano, ó Jerusalém, e grite; erga a sua voz em Basã e grite desde Abarim, porque todos os seus amantes estão esmagados.

[[v24-22-21]]

^<<v24-22-21,21>>^ Falei com você na sua prosperidade, mas você disse: ‘Não ouvirei.’ Tem sido este o seu caminho, desde a sua mocidade, pois você nunca deu ouvidos à minha voz.

[[v24-22-22]]

^<<v24-22-22,22>>^ O vento apascentará todos os seus pastores, e os seus amantes irão para o cativeiro; então você certamente ficará envergonhada e confusa, por causa de toda a sua maldade.

[[v24-22-23]]

^<<v24-22-23,23>>^ Você, que habita no Líbano e faz o seu ninho nos cedros, como vai gemer quando vierem as dores e as angústias como as da mulher que está dando à luz!"

[[v24-22-24]]

^<<v24-22-24,24>>^ — Tão certo como eu vivo, diz o Senhor , ainda que Jeconias, filho de Jeoaquim, rei de Judá, fosse o anel de selar na minha mão direita, eu dali o arrancaria.

[[v24-22-25]]

^<<v24-22-25,25>>^ Vou entregá-lo, ó rei, nas mãos dos que procuram tirar a sua vida e nas mãos daqueles a quem você teme, a saber, nas mãos de Nabucodonosor, rei da Babilônia, e nas mãos dos caldeus.

[[v24-22-26]]

^<<v24-22-26,26>>^ Lançarei você e a sua mãe, que o pôs no mundo, para outra terra, em que vocês não nasceram; e ali morrerão.

[[v24-22-27]]

^<<v24-22-27,27>>^ Mas à terra da qual eles terão saudades, a essa não voltarão.

[[v24-22-28]]

^<<v24-22-28,28>>^ Será que este Jeconias é como um vaso quebrado e desprezado, do qual ninguém se agrada? Por que é que ele e os seus filhos foram lançados fora, jogados numa terra que não conhecem?

[[v24-22-29]]

^<<v24-22-29,29>>^ Ó terra, terra, terra! Ouça a palavra do Senhor !

[[v24-22-30]]

^<<v24-22-30,30>>^ Assim diz o Senhor : "Registrem que esse homem não teve filhos. É homem que não prosperará nos seus dias, e nenhum dos seus filhos prosperará, para se assentar no trono de Davi e ainda reinar em Judá."

'''

xref:024-jeremias/024-jeremias-021.adoc#v24-21-0[&#60; Capítulo Anterior] | <<v24-22-0,Topo>> | xref:024-jeremias/024-jeremias-023.adoc#v24-23-0[Próximo Capítulo &#62;]