include::./index.adoc[]

[[v24-38-0]]
=== Jeremias, 38
// naa ?, NAA - Nova Almeida Atualizada

[[v24-38-1]]

^<<v24-38-1,1>>^ Sefatias, filho de Matã, Gedalias, filho de Pasur, Jucal, filho de Selemias, e Pasur, filho de Malquias, ouviram as palavras que Jeremias anunciava a todo o povo, dizendo:

[[v24-38-2]]

^<<v24-38-2,2>>^ — Assim diz o Senhor : "Quem ficar nesta cidade morrerá à espada, de fome e de peste; mas aquele que sair e se render aos caldeus viverá; porque a vida lhe será por despojo, e viverá.

[[v24-38-3]]

^<<v24-38-3,3>>^ Assim diz o Senhor : Esta cidade infalivelmente será entregue nas mãos do exército do rei da Babilônia, e este a tomará."

[[v24-38-4]]

^<<v24-38-4,4>>^ Então as autoridades disseram ao rei: — Este homem tem de ser morto, porque, dizendo essas palavras, desfalece as mãos dos homens de guerra que restam nesta cidade e as mãos de todo o povo. Este homem não procura o bem-estar do povo, e sim o mal.

[[v24-38-5]]

^<<v24-38-5,5>>^ O rei Zedequias respondeu: — Eis que ele está nas mãos de vocês, pois o rei nada pode fazer contra vocês.

[[v24-38-6]]

^<<v24-38-6,6>>^ Então eles pegaram Jeremias e o lançaram na cisterna de Malquias, filho do rei, que ficava no pátio da guarda. Desceram Jeremias com cordas. Na cisterna não havia água, apenas lama; e Jeremias se atolou na lama.

[[v24-38-7]]

^<<v24-38-7,7>>^ Ebede-Meleque, o etíope, eunuco que estava na casa do rei, ouviu que tinham colocado Jeremias na cisterna. Quando o rei estava sentado junto ao Portão de Benjamim,

[[v24-38-8]]

^<<v24-38-8,8>>^ Ebede-Meleque saiu da casa do rei e lhe falou:

[[v24-38-9]]

^<<v24-38-9,9>>^ — Ó rei, meu senhor, aqueles homens agiram mal em tudo o que fizeram ao profeta Jeremias, que eles lançaram na cisterna. No lugar onde ele está, morrerá de fome, pois já não há mais pão na cidade.

[[v24-38-10]]

^<<v24-38-10,10>>^ Então o rei deu ordem a Ebede-Meleque, o etíope, dizendo: — Leve com você trinta homens e tire da cisterna o profeta Jeremias, antes que morra.

[[v24-38-11]]

^<<v24-38-11,11>>^ Ebede-Meleque levou os homens consigo e foi à casa do rei, a um lugar debaixo da tesouraria, e pegou algumas roupas usadas e trapos, e os desceu a Jeremias na cisterna, por meio de cordas.

[[v24-38-12]]

^<<v24-38-12,12>>^ Ebede-Meleque, o etíope, disse a Jeremias: — Ponha agora essas roupas usadas e esses trapos nas axilas, por debaixo das cordas. Jeremias o fez.

[[v24-38-13]]

^<<v24-38-13,13>>^ Puxaram Jeremias com as cordas e o tiraram da cisterna; e Jeremias ficou no pátio da guarda.

[[v24-38-14]]

^<<v24-38-14,14>>^ Então o rei Zedequias mandou trazer o profeta Jeremias à sua presença, à terceira entrada na Casa do Senhor , e lhe disse: — Eu quero perguntar algo a você; não esconda nada de mim.

[[v24-38-15]]

^<<v24-38-15,15>>^ Jeremias disse a Zedequias: — Se eu disser algo, por acaso o senhor, ó rei, não me matará? E mesmo que eu lhe dê conselhos, o senhor não me escutará.

[[v24-38-16]]

^<<v24-38-16,16>>^ Então Zedequias jurou secretamente a Jeremias, dizendo: — Tão certo como vive o Senhor , que nos deu a vida, não o matarei, nem o entregarei nas mãos desses homens que querem matá-lo.

[[v24-38-17]]

^<<v24-38-17,17>>^ Então Jeremias disse a Zedequias: — Assim diz o Senhor , o Deus dos Exércitos, Deus de Israel: "Se você se render voluntariamente aos oficiais do rei da Babilônia, então a sua vida será poupada, esta cidade não será queimada, e você e a sua casa ficarão vivos.

[[v24-38-18]]

^<<v24-38-18,18>>^ Mas, se você não se render aos oficiais do rei da Babilônia, então esta cidade será entregue nas mãos dos caldeus, eles a queimarão, e você não escapará das mãos deles."

[[v24-38-19]]

^<<v24-38-19,19>>^ O rei Zedequias disse a Jeremias: — Tenho receio dos judeus que passaram para o lado dos caldeus. Pode acontecer que os caldeus me entreguem nas mãos desses judeus, e eles zombem de mim.

[[v24-38-20]]

^<<v24-38-20,20>>^ Mas Jeremias respondeu: — Eles não o entregarão. Ouça a voz do Senhor  no que estou lhe dizendo. Então tudo lhe correrá bem, e a sua vida será poupada.

[[v24-38-21]]

^<<v24-38-21,21>>^ Mas, se o senhor, ó rei, não quiser se render, isto é o que o Senhor  Deus me mostrou:

[[v24-38-22]]

^<<v24-38-22,22>>^ Todas as mulheres que ficaram na casa do rei de Judá serão levadas aos oficiais do rei da Babilônia e dirão: "Os seus bons amigos, ó rei, o enganaram e dominaram. Mas, agora que os pés do rei se atolaram na lama, eles o abandonaram."

[[v24-38-23]]

^<<v24-38-23,23>>^ — Assim, todas as suas mulheres e os seus filhos serão levados aos caldeus. O senhor, ó rei, não escapará das mãos deles, mas será prisioneiro na mão do rei da Babilônia, e esta cidade será queimada.

[[v24-38-24]]

^<<v24-38-24,24>>^ Então Zedequias disse a Jeremias: — Que ninguém saiba desta conversa, e você não morrerá.

[[v24-38-25]]

^<<v24-38-25,25>>^ Se as autoridades souberem que falei com você, vierem procurá-lo e lhe disserem: "Conte-nos o que foi que você disse ao rei e o que ele disse a você; não esconda nada de nós, e nós não mataremos você",

[[v24-38-26]]

^<<v24-38-26,26>>^ diga: "Apresentei a minha humilde súplica diante do rei para que não me mandasse de volta à casa de Jônatas, para que eu não venha a morrer ali."

[[v24-38-27]]

^<<v24-38-27,27>>^ Quando todas as autoridades se dirigiram a Jeremias e o interrogaram, ele lhes falou como o rei havia ordenado. Então o deixaram em paz, porque ninguém mais ficou sabendo o que foi conversado.

[[v24-38-28]]

^<<v24-38-28,28>>^ Jeremias ficou no pátio da guarda, até o dia em que Jerusalém foi tomada.

'''

xref:024-jeremias/024-jeremias-037.adoc#v24-37-0[&#60; Capítulo Anterior] | <<v24-38-0,Topo>> | xref:024-jeremias/024-jeremias-039.adoc#v24-39-0[Próximo Capítulo &#62;]