include::./index.adoc[]

[[v24-29-0]]
=== Jeremias, 29
// naa ?, NAA - Nova Almeida Atualizada

[[v24-29-1]]

^<<v24-29-1,1>>^ São estas as palavras da carta que o profeta Jeremias enviou de Jerusalém ao resto dos anciãos do cativeiro, aos sacerdotes, aos profetas e a todo o povo que Nabucodonosor havia deportado de Jerusalém para a Babilônia.

[[v24-29-2]]

^<<v24-29-2,2>>^ Isso aconteceu depois que saíram de Jerusalém o rei Jeconias, a rainha-mãe, os oficiais, as autoridades de Judá e Jerusalém e os carpinteiros e ferreiros.

[[v24-29-3]]

^<<v24-29-3,3>>^ A carta foi levada por Elasa, filho de Safã, e por Gemarias, filho de Hilquias, os quais Zedequias, rei de Judá, tinha enviado à Babilônia, a Nabucodonosor, rei da Babilônia. Ela dizia o seguinte:

[[v24-29-4]]

^<<v24-29-4,4>>^ Assim diz o Senhor  dos Exércitos, o Deus de Israel, a todos os exilados que eu deportei de Jerusalém para a Babilônia:

[[v24-29-5]]

^<<v24-29-5,5>>^ "Construam casas e morem nelas; plantem pomares e comam o seu fruto.

[[v24-29-6]]

^<<v24-29-6,6>>^ Casem e tenham filhos e filhas; escolham esposas para os filhos de vocês e deem as suas filhas em casamento, para que tenham filhos e filhas. Aumentem em número e não diminuam aí na Babilônia!

[[v24-29-7]]

^<<v24-29-7,7>>^ Procurem a paz da cidade para onde eu os deportei e orem por ela ao Senhor ; porque na sua paz vocês terão paz.

[[v24-29-8]]

^<<v24-29-8,8>>^ Porque assim diz o Senhor  dos Exércitos, o Deus de Israel: Não se deixem enganar pelos profetas e adivinhos que vivem no meio de vocês. Não deem ouvidos aos sonhadores, que sempre sonham segundo o desejo de vocês.

[[v24-29-9]]

^<<v24-29-9,9>>^ Porque eles profetizam falsamente em meu nome; eu não os enviei", diz o Senhor .

[[v24-29-10]]

^<<v24-29-10,10>>^ Assim diz o Senhor : "Logo que se cumprirem para a Babilônia setenta anos, atentarei para vocês e cumprirei a promessa que fiz a vocês, trazendo-os de volta a este lugar.

[[v24-29-11]]

^<<v24-29-11,11>>^ Eu é que sei que pensamentos tenho a respeito de vocês, diz o Senhor . São pensamentos de paz e não de mal, para dar-lhes um futuro e uma esperança.

[[v24-29-12]]

^<<v24-29-12,12>>^ Então vocês me invocarão, se aproximarão de mim em oração, e eu os ouvirei.

[[v24-29-13]]

^<<v24-29-13,13>>^ Vocês me buscarão e me acharão quando me buscarem de todo o coração.

[[v24-29-14]]

^<<v24-29-14,14>>^ Serei achado por vocês, diz o Senhor , e farei com que mude a sorte de vocês. Eu os congregarei de todas as nações e de todos os lugares para onde os dispersei, diz o Senhor , e trarei vocês de volta ao lugar de onde os mandei para o exílio."

[[v24-29-15]]

^<<v24-29-15,15>>^ Vocês dizem: "O Senhor  nos suscitou profetas na Babilônia."

[[v24-29-16]]

^<<v24-29-16,16>>^ Mas assim diz o Senhor  a respeito do rei que se assenta no trono de Davi e de todo o povo que vive nesta cidade, os irmãos de vocês que não foram com vocês para o exílio.

[[v24-29-17]]

^<<v24-29-17,17>>^ Assim diz o Senhor  dos Exércitos: "Eis que enviarei contra eles a espada, a fome e a peste e farei com que sejam como figos ruins, que são tão ruins que não se podem comer.

[[v24-29-18]]

^<<v24-29-18,18>>^ Eu os perseguirei com a espada, a fome e a peste. Farei deles um motivo de espanto para todos os reinos da terra e os porei por objeto de maldição, de horror, de vaias e de deboche entre todas as nações para onde os tiver dispersado.

[[v24-29-19]]

^<<v24-29-19,19>>^ Porque eles não deram ouvidos às minhas palavras, diz o Senhor , que sempre de novo lhes enviei por meio dos meus servos, os profetas. E vocês também não quiseram ouvir, diz o Senhor .

[[v24-29-20]]

^<<v24-29-20,20>>^ Portanto, escutem a palavra do Senhor , todos vocês exilados, que enviei de Jerusalém para a Babilônia."

[[v24-29-21]]

^<<v24-29-21,21>>^ Assim diz o Senhor  dos Exércitos, o Deus de Israel, a respeito de Acabe, filho de Colaías, e de Zedequias, filho de Maaseias, que estão no meio de vocês e profetizam mentiras em meu nome: "Eis que os entregarei nas mãos de Nabucodonosor, rei da Babilônia, e ele os matará diante dos olhos de vocês.

[[v24-29-22]]

^<<v24-29-22,22>>^ Daí surgirá nova espécie de maldição entre os exilados de Judá que estão na Babilônia: ‘Que o Senhor  faça com você o que fez com Zedequias e Acabe, os quais o rei da Babilônia assou no fogo!’

[[v24-29-23]]

^<<v24-29-23,23>>^ Isso porque fizeram loucura em Israel, cometeram adultério com as mulheres de seus companheiros e anunciaram falsamente em meu nome palavras que não lhes mandei dizer. Eu o sei e sou testemunha disso, diz o Senhor ."

[[v24-29-24]]

^<<v24-29-24,24>>^ — A Semaías, de Neelão, diga que

[[v24-29-25]]

^<<v24-29-25,25>>^ assim diz o Senhor  dos Exércitos, o Deus de Israel: — Em seu próprio nome você enviou cartas a todo o povo que está em Jerusalém, a Sofonias, filho de Maaseias, o sacerdote, e a todos os sacerdotes, dizendo:

[[v24-29-26]]

^<<v24-29-26,26>>^ "O Senhor  o constituiu sacerdote em lugar do sacerdote Joiada, para que, na Casa do Senhor , você se encarregue de todo louco que quer passar por profeta, para lançá-lo na prisão e prendê-lo no tronco.

[[v24-29-27]]

^<<v24-29-27,27>>^ Então, por que você não repreendeu Jeremias, de Anatote, que profetiza no meio de vocês?

[[v24-29-28]]

^<<v24-29-28,28>>^ Pois nos enviou mensageiros à Babilônia para nos dizer: ‘O exílio vai ser longo! Construam casas e morem nelas; plantem pomares e comam o seu fruto.’"

[[v24-29-29]]

^<<v24-29-29,29>>^ O sacerdote Sofonias leu esta carta em voz alta para o profeta Jeremias.

[[v24-29-30]]

^<<v24-29-30,30>>^ Então veio a palavra do Senhor  a Jeremias, dizendo:

[[v24-29-31]]

^<<v24-29-31,31>>^ — Mande dizer a todos os exilados: "Assim diz o Senhor  a respeito de Semaías, de Neelão: Visto que Semaías profetizou a vocês sem que eu o tenha enviado e fez com que vocês confiassem em mentiras,

[[v24-29-32]]

^<<v24-29-32,32>>^ assim diz o Senhor : Eis que castigarei Semaías, de Neelão, e a sua descendência. Ele não terá ninguém que habite entre este povo e não verá o bem que hei de fazer ao meu povo, diz o Senhor , porque pregou rebeldia contra o Senhor ."

'''

xref:024-jeremias/024-jeremias-028.adoc#v24-28-0[&#60; Capítulo Anterior] | <<v24-29-0,Topo>> | xref:024-jeremias/024-jeremias-030.adoc#v24-30-0[Próximo Capítulo &#62;]