include::./index.adoc[]

[[v24-14-0]]
=== Jeremias, 14
// naa ?, NAA - Nova Almeida Atualizada

[[v24-14-1]]

^<<v24-14-1,1>>^ Palavra do Senhor  que veio a Jeremias a respeito da seca:

[[v24-14-2]]

^<<v24-14-2,2>>^ "Judá anda chorando, as suas portas estão abandonadas e, de luto, se curvam até o chão; e o clamor de Jerusalém vai subindo.

[[v24-14-3]]

^<<v24-14-3,3>>^ Os poderosos mandam os servos buscar água. Estes vão às cisternas e não encontram água; voltam com os seus cântaros vazios e, decepcionados e confusos, cobrem a cabeça.

[[v24-14-4]]

^<<v24-14-4,4>>^ Por não ter havido chuva sobre a terra, esta se acha ressequida; e, por isso, os lavradores, decepcionados, cobrem a cabeça.

[[v24-14-5]]

^<<v24-14-5,5>>^ Até as corças no campo têm as suas crias e as abandonam, porque não há capim.

[[v24-14-6]]

^<<v24-14-6,6>>^ Os jumentos selvagens se põem no alto dos morros e, ofegantes, sorvem o vento como chacais; os seus olhos desfalecem, por falta de pasto."

[[v24-14-7]]

^<<v24-14-7,7>>^ Ainda que as nossas maldades testifiquem contra nós, ó Senhor , age por amor do teu nome! Porque as nossas rebeldias se multiplicaram; pecamos contra ti.

[[v24-14-8]]

^<<v24-14-8,8>>^ Ó Esperança de Israel e Redentor do teu povo no tempo da angústia, por que serias como estrangeiro na terra e como viajante que fica só uma noite?

[[v24-14-9]]

^<<v24-14-9,9>>^ Por que serias como homem que foi pego de surpresa, como valente que não pode salvar? Mas tu, ó Senhor , estás em nosso meio, e nós somos chamados pelo teu nome. Não nos abandones!

[[v24-14-10]]

^<<v24-14-10,10>>^ Assim diz o Senhor a respeito deste povo: "Eles gostam de andar errantes e não sabem controlar os pés. Por isso, o Senhor não se agrada deles; agora ele se lembrará das maldades que fizeram e os castigará por causa dos seus pecados."

[[v24-14-11]]

^<<v24-14-11,11>>^ O Senhor  me disse ainda: — Não interceda por este povo para o bem dele.

[[v24-14-12]]

^<<v24-14-12,12>>^ Quando jejuarem, não ouvirei o seu clamor e, quando trouxerem holocaustos e ofertas de cereais, não me agradarei deles. Pelo contrário, eu os consumirei pela guerra, pela fome e pela peste.

[[v24-14-13]]

^<<v24-14-13,13>>^ Então eu disse: — Ah! Senhor  Deus, eis que os profetas lhes dizem: "Vocês não verão a guerra, nem passarão fome. Porque eu lhes darei verdadeira paz neste lugar."

[[v24-14-14]]

^<<v24-14-14,14>>^ E o Senhor  respondeu: — Esses profetas profetizam mentiras em meu nome. Nunca os enviei, nem lhes dei ordem, nem lhes falei. Eles estão profetizando para vocês visões falsas, adivinhações inúteis e engano que procede do seu íntimo.

[[v24-14-15]]

^<<v24-14-15,15>>^ Portanto, assim diz o Senhor  a respeito dos profetas que, profetizando em meu nome, sem que eu os tenha mandado, dizem que não haverá guerra nem fome nesta terra: Esses profetas serão consumidos pela guerra e pela fome.

[[v24-14-16]]

^<<v24-14-16,16>>^ O povo a quem eles profetizam será lançado nas ruas de Jerusalém, por causa da fome e da guerra. Não haverá quem os sepulte — a eles, a suas mulheres, a seus filhos e a suas filhas. Porque derramarei sobre eles a sua maldade.

[[v24-14-17]]

^<<v24-14-17,17>>^ Portanto, diga-lhes esta palavra: "Que os meus olhos derramem lágrimas de noite e de dia, sem cessar. Porque a virgem, filha do meu povo, sofreu um grande golpe; está gravemente ferida.

[[v24-14-18]]

^<<v24-14-18,18>>^ Se saio ao campo, vejo os que foram mortos à espada; se entro na cidade, estão ali os debilitados pela fome. Até os profetas e os sacerdotes vagueiam pela terra e não sabem para onde vão."

[[v24-14-19]]

^<<v24-14-19,19>>^ Será que de todo rejeitaste Judá? Será que a tua alma tem nojo de Sião? Por que nos feriste, e não há cura para nós? Aguardamos a paz, e não há nada de bom; esperamos o tempo da cura, e eis o terror.

[[v24-14-20]]

^<<v24-14-20,20>>^ Conhecemos, ó Senhor , a nossa maldade e a iniquidade de nossos pais; porque temos pecado contra ti.

[[v24-14-21]]

^<<v24-14-21,21>>^ Não nos rejeites, por amor do teu nome; não desprezes o trono da tua glória. Lembra-te e não anules a tua aliança conosco.

[[v24-14-22]]

^<<v24-14-22,22>>^ Será que existe entre os ídolos dos gentios algum que faça chover? Ou podem os céus por si mesmos dar chuvas? Não és tu somente, ó Senhor , nosso Deus, o que fazes isto? Portanto, em ti esperamos, pois tu fazes todas estas coisas.

'''

xref:024-jeremias/024-jeremias-013.adoc#v24-13-0[&#60; Capítulo Anterior] | <<v24-14-0,Topo>> | xref:024-jeremias/024-jeremias-015.adoc#v24-15-0[Próximo Capítulo &#62;]