include::./index.adoc[]

[[v24-36-0]]
=== Jeremias, 36
// naa ?, NAA - Nova Almeida Atualizada

[[v24-36-1]]

^<<v24-36-1,1>>^ No quarto ano do reinado de Jeoaquim, filho de Josias, rei de Judá, esta palavra do Senhor  veio a Jeremias:

[[v24-36-2]]

^<<v24-36-2,2>>^ — Pegue um rolo, um livro, e escreva nele todas as palavras que falei a você contra Israel, contra Judá e contra todas as nações, desde o dia em que comecei a falar com você, nos dias de Josias, até hoje.

[[v24-36-3]]

^<<v24-36-3,3>>^ Talvez os da casa de Judá ouçam todo o mal que eu estou planejando fazer-lhes e venham a converter-se cada um do seu mau caminho, e eu lhes perdoe a iniquidade e o pecado.

[[v24-36-4]]

^<<v24-36-4,4>>^ Então Jeremias chamou Baruque, filho de Nerias, e Baruque escreveu no rolo, segundo o que Jeremias ditava, todas as palavras que o Senhor  lhe havia revelado.

[[v24-36-5]]

^<<v24-36-5,5>>^ Então Jeremias deu a seguinte ordem a Baruque: — Eu estou preso; não posso entrar na Casa do Senhor .

[[v24-36-6]]

^<<v24-36-6,6>>^ Vá você até lá e, do rolo que você escreveu, segundo o que eu ditei, leia em voz alta todas as palavras do Senhor , diante do povo, na Casa do Senhor , no dia de jejum. Leia também diante de todos os de Judá que vêm das suas cidades.

[[v24-36-7]]

^<<v24-36-7,7>>^ Pode ser que as humildes súplicas deles sejam bem-acolhidas pelo Senhor , e cada um se converta do seu mau caminho; porque grande é a ira e o furor que o Senhor  tem manifestado contra este povo.

[[v24-36-8]]

^<<v24-36-8,8>>^ Baruque, filho de Nerias, fez tudo o que o profeta Jeremias lhe havia ordenado e, na Casa do Senhor , leu as palavras do Senhor  que estavam naquele livro.

[[v24-36-9]]

^<<v24-36-9,9>>^ No nono mês do quinto ano do reinado de Jeoaquim, filho de Josias, rei de Judá, apregoaram jejum diante do Senhor  a todo o povo em Jerusalém e a todo o povo que vinha das cidades de Judá a Jerusalém.

[[v24-36-10]]

^<<v24-36-10,10>>^ Então, diante de todo o povo, na Casa do Senhor , na câmara de Gemarias, filho de Safã, o escriba, no átrio superior, à entrada da Porta Nova da Casa do Senhor , Baruque leu as palavras de Jeremias que estavam naquele livro.

[[v24-36-11]]

^<<v24-36-11,11>>^ Quando Micaías, filho de Gemarias, filho de Safã, ouviu todas as palavras do Senhor , que estavam naquele livro,

[[v24-36-12]]

^<<v24-36-12,12>>^ desceu à casa do rei, à câmara do escrivão. Eis que todas as autoridades estavam ali assentadas: o escrivão Elisama, Delaías, filho de Semaías, Elnatã, filho de Acbor, Gemarias, filho de Safã, Zedequias, filho de Hananias, e todas as outras autoridades.

[[v24-36-13]]

^<<v24-36-13,13>>^ Micaías anunciou-lhes todas as palavras que tinha ouvido, quando Baruque leu o livro diante do povo.

[[v24-36-14]]

^<<v24-36-14,14>>^ Então todas as autoridades mandaram Jeudi, filho de Netanias, filho de Selemias, filho de Cusi, dizer a Baruque: — Pegue aquele rolo que você leu diante do povo e venha para cá. Baruque, filho de Nerias, pegou o rolo e foi até eles.

[[v24-36-15]]

^<<v24-36-15,15>>^ Então disseram a ele: — Por favor, sente-se e leia esse rolo para nós. E Baruque o leu diante deles.

[[v24-36-16]]

^<<v24-36-16,16>>^ Quando as autoridades ouviram todas aquelas palavras, entreolharam-se atemorizadas e disseram a Baruque: — Sem dúvida nenhuma, anunciaremos ao rei todas estas palavras.

[[v24-36-17]]

^<<v24-36-17,17>>^ E perguntaram a Baruque: — Diga-nos, por favor, como é que você escreveu todas essas palavras? Foi o profeta que ditou?

[[v24-36-18]]

^<<v24-36-18,18>>^ Baruque respondeu: — Ele pessoalmente ditou todas estas palavras, e eu as escrevi com tinta neste rolo.

[[v24-36-19]]

^<<v24-36-19,19>>^ Então as autoridades disseram a Baruque: — Vá esconder-se, e leve Jeremias com você. Que ninguém saiba onde vocês estão!

[[v24-36-20]]

^<<v24-36-20,20>>^ Depois de terem depositado o rolo na câmara do escrivão Elisama, as autoridades foram ao átrio do palácio real e anunciaram diante do rei todas aquelas palavras.

[[v24-36-21]]

^<<v24-36-21,21>>^ Então o rei mandou que Jeudi fosse buscar o rolo. Jeudi pegou o rolo na câmara do escrivão Elisama e o leu diante do rei e de todas as autoridades que estavam com ele.

[[v24-36-22]]

^<<v24-36-22,22>>^ O rei estava sentado em seus aposentos de inverno, pelo nono mês do ano, e diante dele estava um braseiro aceso.

[[v24-36-23]]

^<<v24-36-23,23>>^ Sempre que Jeudi terminava a leitura de três ou quatro colunas do rolo, o rei as cortava com um canivete de escrivão e lançava no fogo que havia no braseiro, até que todo o rolo se consumiu no fogo que estava no braseiro.

[[v24-36-24]]

^<<v24-36-24,24>>^ Ninguém ficou com medo e ninguém rasgou as suas roupas, nem o rei nem nenhum dos servos que ouviram todas aquelas palavras.

[[v24-36-25]]

^<<v24-36-25,25>>^ Por mais que Elnatã, Delaías e Gemarias tivessem insistido com o rei que não queimasse o rolo, ele não lhes deu ouvidos.

[[v24-36-26]]

^<<v24-36-26,26>>^ Pelo contrário, o rei ordenou a Jerameel, filho de Hameleque, a Seraías, filho de Azriel, e a Selemias, filho de Abdeel, que prendessem Baruque, o escrivão, e Jeremias, o profeta. Mas o Senhor  os havia escondido.

[[v24-36-27]]

^<<v24-36-27,27>>^ Depois que o rei havia queimado o rolo com as palavras ditadas por Jeremias e escritas por Baruque, a palavra do Senhor  veio a Jeremias, dizendo:

[[v24-36-28]]

^<<v24-36-28,28>>^ — Pegue outro rolo e escreva nele todas as palavras que estavam no original, que Jeoaquim, rei de Judá, queimou.

[[v24-36-29]]

^<<v24-36-29,29>>^ E a Jeoaquim, rei de Judá, diga que assim diz o Senhor : "Você queimou aquele rolo e perguntou por que Jeremias escreveu nele que certamente viria o rei da Babilônia, destruiria esta terra e acabaria com as pessoas e os animais.

[[v24-36-30]]

^<<v24-36-30,30>>^ Portanto, assim diz o Senhor , a respeito de Jeoaquim, rei de Judá: Ele não terá quem se assente no trono de Davi, e o seu cadáver será largado ao calor do dia e à geada da noite.

[[v24-36-31]]

^<<v24-36-31,31>>^ Eu o castigarei, bem como a sua descendência e os seus servos, por causa da iniquidade deles. Sobre ele, sobre os moradores de Jerusalém e sobre o povo de Judá farei cair todo o mal que tenho falado contra eles, sem que me ouvissem."

[[v24-36-32]]

^<<v24-36-32,32>>^ Então Jeremias pegou outro rolo e o deu a Baruque, filho de Nerias, o escrivão, o qual escreveu nele, conforme Jeremias ia ditando, todas as palavras do livro que Jeoaquim, rei de Judá, havia queimado. E ainda se acrescentaram a elas muitas palavras semelhantes.

'''

xref:024-jeremias/024-jeremias-035.adoc#v24-35-0[&#60; Capítulo Anterior] | <<v24-36-0,Topo>> | xref:024-jeremias/024-jeremias-037.adoc#v24-37-0[Próximo Capítulo &#62;]