include::./index.adoc[]

[[v24-48-0]]
=== Jeremias, 48
// naa ?, NAA - Nova Almeida Atualizada

[[v24-48-1]]

^<<v24-48-1,1>>^ A respeito de Moabe, assim diz o Senhor  dos Exércitos, o Deus de Israel: "Ai da cidade de Nebo, porque foi destruída! Quiriataim está envergonhada, já foi tomada; a fortaleza está envergonhada e destruída.

[[v24-48-2]]

^<<v24-48-2,2>>^ A glória de Moabe já se foi. Em Hesbom tramaram contra ela, dizendo: ‘Venham, vamos eliminá-la para que não seja mais povo!’ Também você, ó Madmém, será reduzida a silêncio; a espada a perseguirá.

[[v24-48-3]]

^<<v24-48-3,3>>^ Ouve-se um grito desde Horonaim: ‘Ruína e grande destruição!’

[[v24-48-4]]

^<<v24-48-4,4>>^ Moabe está destruída; seus filhinhos fizeram ouvir gritos.

[[v24-48-5]]

^<<v24-48-5,5>>^ Pela subida de Luíte, eles seguem com choro contínuo; na descida de Horonaim, se ouvem gritos angustiosos de ruína.

[[v24-48-6]]

^<<v24-48-6,6>>^ ‘Fujam! Corram para salvar a vida, ainda que vocês venham a ser como o arbusto solitário no deserto.’"

[[v24-48-7]]

^<<v24-48-7,7>>^ "Pois, por ter confiado nas suas obras e nos seus tesouros, também você, Moabe, será tomada. O deus Quemos irá para o cativeiro, junto com os seus sacerdotes e os seus príncipes.

[[v24-48-8]]

^<<v24-48-8,8>>^ O destruidor virá sobre cada uma das cidades, e nenhuma escapará; perecerá o vale, e a planície será destruída, porque o Senhor  o disse.

[[v24-48-9]]

^<<v24-48-9,9>>^ Deem asas a Moabe, para que saia voando; as suas cidades se tornarão em ruínas, e ninguém morará nelas."

[[v24-48-10]]

^<<v24-48-10,10>>^ Maldito aquele que fizer a obra do Senhor  relaxadamente! Maldito aquele que retém a sua espada do sangue!

[[v24-48-11]]

^<<v24-48-11,11>>^ "Moabe esteve despreocupado desde a sua mocidade, como vinho descansando sobre a borra. Não foi mudado de vasilha em vasilha, nem foi para o cativeiro. Por isso, conservou o seu sabor, e o seu aroma não se alterou."

[[v24-48-12]]

^<<v24-48-12,12>>^ — Portanto, eis que vêm dias, diz o Senhor , em que lhe enviarei derramadores, que o derramarão; despejarão as suas vasilhas e as farão em pedaços.

[[v24-48-13]]

^<<v24-48-13,13>>^ Moabe terá vergonha de Quemos, como a casa de Israel se envergonhou de Betel, sua confiança.

[[v24-48-14]]

^<<v24-48-14,14>>^ "Como vocês podem dizer: ‘Somos valentes e homens fortes para a guerra’?

[[v24-48-15]]

^<<v24-48-15,15>>^ Moabe foi destruído e as suas cidades foram invadidas, e os seus melhores jovens foram levados ao matadouro, diz o Rei, cujo nome é Senhor  dos Exércitos.

[[v24-48-16]]

^<<v24-48-16,16>>^ A destruição de Moabe está prestes a vir, e muito se apressa o seu mal."

[[v24-48-17]]

^<<v24-48-17,17>>^ "Tenham pena de Moabe, todos vocês que estão ao seu redor e todos os que conhecem a sua fama. Digam: ‘Como se quebrou a vara forte, o cajado formoso!’

[[v24-48-18]]

^<<v24-48-18,18>>^ Desça da sua glória e sente-se em terra sedenta, ó moradora de Dibom. Porque o destruidor de Moabe sobe contra você e destruirá as suas fortalezas.

[[v24-48-19]]

^<<v24-48-19,19>>^ Fique na beira do caminho e espie, ó moradora de Aroer. Pergunte ao que foge e àquela que escapou: ‘O que foi que aconteceu?’

[[v24-48-20]]

^<<v24-48-20,20>>^ Moabe está envergonhado, porque foi destruído. Chorem e gritem! Anunciem junto ao Arnom que Moabe foi destruído."

[[v24-48-21]]

^<<v24-48-21,21>>^ — O juízo veio também sobre a terra da planície, sobre Holom, Jaza e Mefaate;

[[v24-48-22]]

^<<v24-48-22,22>>^ sobre Dibom, Nebo e Bete-Diblataim;

[[v24-48-23]]

^<<v24-48-23,23>>^ sobre Quiriataim, Bete-Gamul e Bete-Meom;

[[v24-48-24]]

^<<v24-48-24,24>>^ sobre Queriote e Bozra, e até sobre todas as cidades da terra de Moabe, tanto as de longe como as de perto.

[[v24-48-25]]

^<<v24-48-25,25>>^ O poder de Moabe foi eliminado, e o seu braço foi quebrado, diz o Senhor .

[[v24-48-26]]

^<<v24-48-26,26>>^ — Façam com que Moabe fique bêbado, porque se exaltou contra o Senhor . Moabe se revolverá no seu próprio vômito e também ele será motivo de riso.

[[v24-48-27]]

^<<v24-48-27,27>>^ Pois não foi Israel também motivo de riso para você? Mas por acaso foi Israel achado entre ladrões, para que você balance a cabeça, quando fala dele?

[[v24-48-28]]

^<<v24-48-28,28>>^ "Deixem as cidades e vão morar nos rochedos, ó moradores de Moabe. Sejam como as pombas que se aninham nos flancos da boca do abismo.

[[v24-48-29]]

^<<v24-48-29,29>>^ Ouvimos falar da soberba de Moabe, que de fato é extremamente soberbo. Ouvimos falar da sua presunção, do seu orgulho, da sua vaidade e da arrogância do seu coração.

[[v24-48-30]]

^<<v24-48-30,30>>^ Conheço a sua insolência", diz o Senhor , "mas isso não vale nada; as suas arrogâncias nada farão.

[[v24-48-31]]

^<<v24-48-31,31>>^ Por isso, vou chorar por Moabe, sim, gritarei por todo o Moabe; pelos homens de Quir-Heres lamentarei.

[[v24-48-32]]

^<<v24-48-32,32>>^ Mais do que por Jazer, chorarei por você, ó vinha de Sibma. Os seus ramos passaram o mar, chegaram até o mar de Jazer; mas o destruidor caiu sobre os seus frutos de verão e sobre as suas uvas.

[[v24-48-33]]

^<<v24-48-33,33>>^ Fugiu a alegria e o regozijo dos campos férteis de Moabe, pois acabei com o vinho nos lagares. Já não pisam as uvas com gritos de alegria; os gritos não são gritos de alegria."

[[v24-48-34]]

^<<v24-48-34,34>>^ — Ouve-se o grito de Hesbom até Eleale e Jaza, e de Zoar se dão gritos até Horonaim e Eglate-Selisia; porque até as águas de Ninrim secaram.

[[v24-48-35]]

^<<v24-48-35,35>>^ Farei desaparecer de Moabe, diz o Senhor , quem sacrifique nos altos e queime incenso aos seus deuses.

[[v24-48-36]]

^<<v24-48-36,36>>^ — Por isso, o meu coração geme como flauta por causa de Moabe, e como flauta geme por causa do povo de Quir-Heres, porque tudo o que haviam ajuntado se perdeu.

[[v24-48-37]]

^<<v24-48-37,37>>^ Porque toda cabeça será rapada e toda barba, cortada; sobre todas as mãos haverá incisões, e, em volta da cintura, pano de saco.

[[v24-48-38]]

^<<v24-48-38,38>>^ Sobre todos os terraços de Moabe e em todas as suas praças há pranto, porque fiz Moabe em pedaços, como vasilha de barro que ninguém quer, diz o Senhor .

[[v24-48-39]]

^<<v24-48-39,39>>^ Como foi destruído! Como choram! Como, de vergonha, Moabe virou as costas! Assim, Moabe se tornou motivo de riso e de espanto para todos os que estão ao seu redor.

[[v24-48-40]]

^<<v24-48-40,40>>^ Porque assim diz o Senhor : "Eis que uma nação voará como a águia e estenderá as suas asas contra Moabe.

[[v24-48-41]]

^<<v24-48-41,41>>^ As cidades serão tomadas e as fortalezas, ocupadas. Naquele dia, o coração dos valentes de Moabe será como o coração da mulher que está em dores de parto.

[[v24-48-42]]

^<<v24-48-42,42>>^ Moabe será destruído, para que não seja povo, porque se exaltou contra o Senhor .

[[v24-48-43]]

^<<v24-48-43,43>>^ Terror, cova e armadilha esperam por vocês, moradores de Moabe", diz o Senhor .

[[v24-48-44]]

^<<v24-48-44,44>>^ "Aquele que fugir do terror cairá na cova, e, se sair da cova, será apanhado na armadilha; porque trarei sobre ele, sobre Moabe, o ano do seu castigo."

[[v24-48-45]]

^<<v24-48-45,45>>^ "Os que fogem param sem forças à sombra de Hesbom; porém sai fogo de Hesbom e labareda do meio de Seom e devora as têmporas de Moabe e o alto da cabeça desse povo que ama tanto a guerra.

[[v24-48-46]]

^<<v24-48-46,46>>^ Ai de você, Moabe! O povo de Quemos foi destruído; os seus filhos foram feitos cativos, e as suas filhas foram levadas ao cativeiro.

[[v24-48-47]]

^<<v24-48-47,47>>^ Contudo, mudarei a sorte de Moabe, nos últimos dias", diz o Senhor . Até aqui o juízo contra Moabe.

'''

xref:024-jeremias/024-jeremias-047.adoc#v24-47-0[&#60; Capítulo Anterior] | <<v24-48-0,Topo>> | xref:024-jeremias/024-jeremias-049.adoc#v24-49-0[Próximo Capítulo &#62;]