include::./index.adoc[]

[[v24-5-0]]
=== Jeremias, 5
// naa ?, NAA - Nova Almeida Atualizada

[[v24-5-1]]

^<<v24-5-1,1>>^ Deem uma volta pelas ruas de Jerusalém, olhem, investiguem, procurem nas suas praças para ver se acham alguém, se há uma pessoa que pratique a justiça ou busque a verdade. Se acharem, eu perdoarei a cidade.

[[v24-5-2]]

^<<v24-5-2,2>>^ Embora digam: "Tão certo como vive o Senhor ", certamente juram falso.

[[v24-5-3]]

^<<v24-5-3,3>>^ Senhor , por acaso os teus olhos não atentam para a fidelidade? Tu feriste esse povo, mas eles não sentiram nada; tu os consumiste, mas eles não quiseram aceitar a disciplina; endureceram o rosto mais do que uma rocha; não quiseram voltar.

[[v24-5-4]]

^<<v24-5-4,4>>^ Mas eu pensei: "São apenas pobres insensatos, pois não conhecem o caminho do Senhor , o direito do seu Deus.

[[v24-5-5]]

^<<v24-5-5,5>>^ Irei aos poderosos e falarei com eles, porque eles sabem o caminho do Senhor , o direito do seu Deus." Mas todos eles quebraram o jugo e romperam as algemas.

[[v24-5-6]]

^<<v24-5-6,6>>^ Por isso, um leão do bosque os matará, um lobo dos desertos os despedaçará, um leopardo estará à espreita das suas cidades. Quem sair das cidades será devorado; porque as transgressões deles são muitas, e as suas rebeldias se multiplicaram.

[[v24-5-7]]

^<<v24-5-7,7>>^ "Jerusalém, como posso perdoá-la? Os seus filhos me abandonaram e juram pelos que não são deuses. Depois de eu ter-lhes saciado a fome, adulteraram e se reuniram em casas de prostitutas.

[[v24-5-8]]

^<<v24-5-8,8>>^ Como garanhões bem fartos e cheios de desejo, cada um fica rinchando para a mulher do seu próximo.

[[v24-5-9]]

^<<v24-5-9,9>>^ Deixaria eu de castigar estas coisas?" — diz o Senhor . "Não deveria eu me vingar de uma nação como esta?"

[[v24-5-10]]

^<<v24-5-10,10>>^ "Que os inimigos passem pelas carreiras da vinha e a destruam, porém não por completo; tirem os ramos, porque não são do Senhor .

[[v24-5-11]]

^<<v24-5-11,11>>^ Porque a casa de Israel e a casa de Judá foram totalmente infiéis a mim", diz o Senhor .

[[v24-5-12]]

^<<v24-5-12,12>>^ Negaram o Senhor  e disseram: "Não é ele. Nenhum mal nos sobrevirá; não veremos a guerra nem passaremos fome."

[[v24-5-13]]

^<<v24-5-13,13>>^ Os profetas não passam de vento, porque a palavra não está com eles; as suas ameaças se cumprirão contra eles mesmos.

[[v24-5-14]]

^<<v24-5-14,14>>^ Portanto, o Senhor , o Deus dos Exércitos, me disse: "Visto que eles proferiram tais palavras, eis que transformarei em fogo as minhas palavras na sua boca e farei deste povo a lenha; e o fogo os consumirá.

[[v24-5-15]]

^<<v24-5-15,15>>^ Eis que trago contra você uma nação de longe, ó casa de Israel", diz o Senhor ; "nação robusta, nação antiga, nação cuja língua você não conhece; e cuja fala você não entende.

[[v24-5-16]]

^<<v24-5-16,16>>^ A aljava deles é como uma sepultura aberta; todos os seus homens são valentes.

[[v24-5-17]]

^<<v24-5-17,17>>^ Devorarão as colheitas e o pão de vocês, devorarão os seus filhos e as suas filhas; comerão as suas ovelhas e o seu gado; comerão os frutos das suas videiras e figueiras; e com a espada derrubarão as cidades fortificadas em que vocês confiam."

[[v24-5-18]]

^<<v24-5-18,18>>^ — Porém, mesmo naqueles dias, diz o Senhor , não os destruirei completamente.

[[v24-5-19]]

^<<v24-5-19,19>>^ Quando perguntarem: "Por que o Senhor , nosso Deus, nos fez todas essas coisas?", você lhes responderá: "Vocês me abandonaram e serviram a deuses estranhos na terra de vocês. Por isso, terão de servir a estrangeiros numa terra que não é de vocês."

[[v24-5-20]]

^<<v24-5-20,20>>^ Anunciem isto na casa de Jacó e façam uma proclamação em Judá, dizendo:

[[v24-5-21]]

^<<v24-5-21,21>>^ "Escute agora isto, povo tolo e sem entendimento, vocês que têm olhos e não veem, têm ouvidos e não ouvem.

[[v24-5-22]]

^<<v24-5-22,22>>^ Por que não me temem?" — diz o Senhor . "Por que não tremem diante de mim? Pois fui eu que pus a areia como limite do mar, limite perpétuo, que ele não irá ultrapassar. Ainda que se levantem as suas ondas, elas não prevalecerão; ainda que bramem, não passarão daquele limite.

[[v24-5-23]]

^<<v24-5-23,23>>^ Mas este povo tem um coração teimoso e rebelde; desviaram-se e se foram.

[[v24-5-24]]

^<<v24-5-24,24>>^ Em seu coração não dizem: ‘Temamos agora o Senhor , nosso Deus, que nos dá a seu tempo as chuvas, as primeiras e as últimas, e que nos reserva as semanas determinadas da colheita.’

[[v24-5-25]]

^<<v24-5-25,25>>^ As maldades que vocês fizeram desviaram essas coisas boas, e os seus pecados afastaram de vocês o bem.

[[v24-5-26]]

^<<v24-5-26,26>>^ Porque no meio do meu povo se encontram ímpios, que andam espiando, como espreitam os passarinheiros. Como eles, preparam armadilhas e prendem os homens.

[[v24-5-27]]

^<<v24-5-27,27>>^ Como uma gaiola cheia de pássaros, assim as casas deles estão cheias de fraude; por isso, se tornaram poderosos e enriqueceram.

[[v24-5-28]]

^<<v24-5-28,28>>^ Engordaram, ficaram estufados e não há limite para as suas maldades. Não julgam a causa dos órfãos, para que ela prospere, nem defendem o direito dos necessitados.

[[v24-5-29]]

^<<v24-5-29,29>>^ Deixaria eu de castigar estas coisas?" — diz o Senhor . "Não deveria eu me vingar de uma nação como esta?"

[[v24-5-30]]

^<<v24-5-30,30>>^ Coisa espantosa e horrenda se anda fazendo na terra:

[[v24-5-31]]

^<<v24-5-31,31>>^ os profetas profetizam falsamente, e os sacerdotes dominam de mãos dadas com eles. E é o que o meu povo deseja. Porém o que é que vocês farão quando o fim chegar?

'''

xref:024-jeremias/024-jeremias-004.adoc#v24-4-0[&#60; Capítulo Anterior] | <<v24-5-0,Topo>> | xref:024-jeremias/024-jeremias-006.adoc#v24-6-0[Próximo Capítulo &#62;]