include::./index.adoc[]

[[v24-6-0]]
=== Jeremias, 6
// naa ?, NAA - Nova Almeida Atualizada

[[v24-6-1]]

^<<v24-6-1,1>>^ Filhos de Benjamim, fujam do meio de Jerusalém! Toquem a trombeta em Tecoa e levantem o facho de luz em Bete-Haquerém, porque do lado do Norte surge um grande mal, uma grande destruição.

[[v24-6-2]]

^<<v24-6-2,2>>^ Deixarei em ruínas a formosa e delicada filha de Sião.

[[v24-6-3]]

^<<v24-6-3,3>>^ Contra ela virão pastores com os seus rebanhos; levantarão as suas tendas ao redor, e cada um apascentará no seu devido lugar.

[[v24-6-4]]

^<<v24-6-4,4>>^ "Preparem a guerra contra ela! Levantem-se, e vamos atacar ao meio-dia. Ai de nós! Porque o dia já declina, e as sombras da tarde já vão se estendendo!

[[v24-6-5]]

^<<v24-6-5,5>>^ Levantem-se, e vamos atacar de noite e destruir as suas fortalezas."

[[v24-6-6]]

^<<v24-6-6,6>>^ Porque assim diz o Senhor  dos Exércitos: "Cortem árvores e construam rampas de ataque contra Jerusalém. Esta é a cidade que há de ser punida; só há opressão no meio dela.

[[v24-6-7]]

^<<v24-6-7,7>>^ Como o poço conserva frescas as suas águas, assim ela conserva a sua maldade. Violência e destruição se ouvem nela; enfermidade e feridas há diante de mim continuamente.

[[v24-6-8]]

^<<v24-6-8,8>>^ Aceite a disciplina, ó Jerusalém, para que eu não me afaste de você, para que eu não a torne em desolação e terra não habitada."

[[v24-6-9]]

^<<v24-6-9,9>>^ Assim diz o Senhor  dos Exércitos: "Diligentemente se rebuscará o remanescente de Israel como se faz com uma vinha. A exemplo do vindimador, ponha a mão por entre os ramos."

[[v24-6-10]]

^<<v24-6-10,10>>^ A quem falarei e testemunharei, para que ouçam? Eis que os seus ouvidos estão incircuncisos e não podem ouvir. Eis que a palavra do Senhor é para eles objeto de deboche; não gostam dela.

[[v24-6-11]]

^<<v24-6-11,11>>^ Por isso, estou repleto da ira do Senhor ; estou cansado de guardá-la dentro de mim. "Derrame-a sobre as crianças pelas ruas e sobre os jovens nas suas reuniões. Porque até o marido e a mulher serão presos, e também os velhos e os que têm idade avançada.

[[v24-6-12]]

^<<v24-6-12,12>>^ As suas casas serão entregues a outros, os campos e também as mulheres, porque estenderei a mão contra os habitantes desta terra", diz o Senhor .

[[v24-6-13]]

^<<v24-6-13,13>>^ "Porque desde o menor deles até o maior, cada um se dá à ganância, e tanto o profeta como o sacerdote usam de falsidade.

[[v24-6-14]]

^<<v24-6-14,14>>^ Curam superficialmente a ferida do meu povo, dizendo: ‘Paz, paz’; quando não há paz.

[[v24-6-15]]

^<<v24-6-15,15>>^ Será que ficaram envergonhados, porque cometeram abominação? Não, eles não ficaram com vergonha. Eles nem sabem o que é envergonhar-se. Portanto, cairão com os que caem; quando eu os castigar, tropeçarão", diz o Senhor .

[[v24-6-16]]

^<<v24-6-16,16>>^ Assim diz o Senhor : "Ponham-se à beira dos caminhos e olhem; perguntem pelas veredas antigas, qual é o bom caminho; andem por ele e vocês acharão descanso para a sua alma. Mas eles dizem: ‘Não andaremos nele.’

[[v24-6-17]]

^<<v24-6-17,17>>^ Também pus atalaias sobre vocês, dizendo: ‘Fiquem atentos ao som da trombeta.’ Mas eles dizem: ‘Não escutaremos.’

[[v24-6-18]]

^<<v24-6-18,18>>^ Portanto, escutem, ó nações, e saiba, ó congregação, o que vai acontecer com eles!

[[v24-6-19]]

^<<v24-6-19,19>>^ Ouça, ó terra! Eis que eu trarei mal sobre este povo, o próprio fruto dos seus pensamentos, porque não estão atentos às minhas palavras e rejeitam a minha lei.

[[v24-6-20]]

^<<v24-6-20,20>>^ Para que, pois, me vem o incenso de Sabá e a melhor cana aromática de terras distantes? Os holocaustos que vocês oferecem não são aceitáveis, e os seus sacrifícios não me agradam."

[[v24-6-21]]

^<<v24-6-21,21>>^ Portanto, assim diz o Senhor : "Eis que porei tropeços diante deste povo; neles cairão pais e filhos juntamente; o vizinho e o seu companheiro perecerão."

[[v24-6-22]]

^<<v24-6-22,22>>^ Assim diz o Senhor : "Eis que um povo vem da terra do Norte, e uma grande nação se levanta dos confins da terra.

[[v24-6-23]]

^<<v24-6-23,23>>^ Armam-se de arco e de lança; são cruéis e não conhecem a compaixão. O barulho que fazem é como o bramido do mar. Vêm montados em cavalos, como guerreiros em ordem de batalha contra você, ó filha de Sião.

[[v24-6-24]]

^<<v24-6-24,24>>^ Ao ouvirmos a fama deles, as nossas mãos desfaleceram; angústia tomou conta de nós, dores como as da mulher que está dando à luz.

[[v24-6-25]]

^<<v24-6-25,25>>^ Não saiam ao campo, nem andem pelo caminho, porque o inimigo tem espada, e há terror por todos os lados.

[[v24-6-26]]

^<<v24-6-26,26>>^ Ó filha do meu povo, vista roupa feita de pano de saco e role no pó; pranteie como por um filho único, pranto de amarguras; porque de repente virá o destruidor sobre nós."

[[v24-6-27]]

^<<v24-6-27,27>>^ "Jeremias, fiz de você um purificador de metais entre o meu povo, uma fortaleza, para que você examine e venha a conhecer o caminho deles.

[[v24-6-28]]

^<<v24-6-28,28>>^ Todos são mais do que rebeldes e andam espalhando calúnias; são bronze e ferro, são todos corruptores.

[[v24-6-29]]

^<<v24-6-29,29>>^ O fole sopra com força, e o chumbo já se derreteu com o calor. Em vão continua a depuração, porque os maus não são separados.

[[v24-6-30]]

^<<v24-6-30,30>>^ Serão chamados de ‘prata rejeitada’, porque o Senhor  os rejeitou."

'''

xref:024-jeremias/024-jeremias-005.adoc#v24-5-0[&#60; Capítulo Anterior] | <<v24-6-0,Topo>> | xref:024-jeremias/024-jeremias-007.adoc#v24-7-0[Próximo Capítulo &#62;]