include::./index.adoc[]

[[v24-32-0]]
=== Jeremias, 32
// naa ?, NAA - Nova Almeida Atualizada

[[v24-32-1]]

^<<v24-32-1,1>>^ Palavra que foi dita a Jeremias da parte do Senhor , no décimo ano do reinado de Zedequias, rei de Judá, ou décimo oitavo ano do reinado de Nabucodonosor.

[[v24-32-2]]

^<<v24-32-2,2>>^ Ora, nesse tempo o exército do rei da Babilônia cercava Jerusalém, e o profeta Jeremias estava preso no pátio da guarda que estava no palácio do rei de Judá.

[[v24-32-3]]

^<<v24-32-3,3>>^ Pois Zedequias, rei de Judá, o havia encerrado, dizendo: — Como você ousa profetizar que o Senhor  Deus disse que entregará esta cidade nas mãos do rei da Babilônia, e que este a conquistará?

[[v24-32-4]]

^<<v24-32-4,4>>^ Como ousa dizer que Zedequias, rei de Judá, não escapará das mãos dos caldeus, mas infalivelmente será entregue nas mãos do rei da Babilônia, vindo a falar com ele pessoalmente e vendo-o face a face?

[[v24-32-5]]

^<<v24-32-5,5>>^ Como ousa profetizar que ele levará Zedequias para a Babilônia, onde ficará até que o Senhor  atente para ele, como ele mesmo disse, e que, se lutarmos contra os caldeus, não seremos bem-sucedidos?

[[v24-32-6]]

^<<v24-32-6,6>>^ Jeremias disse: — A palavra do Senhor  veio a mim, dizendo:

[[v24-32-7]]

^<<v24-32-7,7>>^ "Eis que Hanamel, filho de seu tio Salum, virá falar com você, dizendo: ‘Compre o meu campo que está em Anatote, pois, pela lei a respeito do resgate, compete a você comprá-lo.’"

[[v24-32-8]]

^<<v24-32-8,8>>^ — Então, exatamente como o Senhor  tinha dito, Hanamel, filho de meu tio, veio falar comigo no pátio da guarda e me disse: "Compre o meu campo que está em Anatote, na terra de Benjamim, porque você tem o direito de posse e de resgate. Compre!" Então entendi que isto era a palavra do Senhor .

[[v24-32-9]]

^<<v24-32-9,9>>^ Assim comprei de Hanamel, filho de meu tio, o campo que está em Anatote e pesei o dinheiro para ele: duzentos gramas de prata.

[[v24-32-10]]

^<<v24-32-10,10>>^ Assinei a escritura, fechei-a com selo, chamei testemunhas e pesei o dinheiro numa balança.

[[v24-32-11]]

^<<v24-32-11,11>>^ Peguei a escritura da compra, tanto a selada, que continha o contrato e as condições, como a cópia aberta,

[[v24-32-12]]

^<<v24-32-12,12>>^ e entreguei essa escritura da compra a Baruque, filho de Nerias, filho de Maaseias, na presença de Hanamel, filho de meu tio, na presença das testemunhas que assinaram a escritura da compra, e na presença de todos os judeus que estavam sentados no pátio da guarda.

[[v24-32-13]]

^<<v24-32-13,13>>^ Na presença deles dei uma ordem a Baruque, dizendo:

[[v24-32-14]]

^<<v24-32-14,14>>^ — Assim diz o Senhor  dos Exércitos, o Deus de Israel: Pegue estas escrituras da compra, tanto a selada como a aberta, e coloque-as num vaso de barro, para que se conservem por muitos dias.

[[v24-32-15]]

^<<v24-32-15,15>>^ Porque assim diz o Senhor  dos Exércitos, o Deus de Israel: Ainda se comprarão casas, campos e vinhas nesta terra.

[[v24-32-16]]

^<<v24-32-16,16>>^ Depois que dei a escritura da compra a Baruque, filho de Nerias, orei ao Senhor , dizendo:

[[v24-32-17]]

^<<v24-32-17,17>>^ — Ah! Senhor  Deus, eis que tu fizeste os céus e a terra com o teu grande poder e com o teu braço estendido; nada é demasiadamente difícil para ti.

[[v24-32-18]]

^<<v24-32-18,18>>^ Tu fazes misericórdia até mil gerações, mas também retribuis a iniquidade dos pais nos filhos. Tu és o grande, o poderoso Deus, cujo nome é Senhor  dos Exércitos,

[[v24-32-19]]

^<<v24-32-19,19>>^ grande em conselho e magnífico em obras. Os teus olhos estão abertos sobre todos os caminhos dos filhos dos homens, para dar a cada um segundo o seu proceder, segundo o fruto das suas obras.

[[v24-32-20]]

^<<v24-32-20,20>>^ Fizeste sinais e maravilhas na terra do Egito até o dia de hoje, tanto em Israel como em toda a humanidade, e assim adquiriste a fama que tens até o dia de hoje.

[[v24-32-21]]

^<<v24-32-21,21>>^ Tiraste o teu povo de Israel da terra do Egito, com sinais e maravilhas, com mão poderosa e braço estendido e com grande espanto,

[[v24-32-22]]

^<<v24-32-22,22>>^ e lhe deste esta terra, que com juramento prometeste aos seus pais, terra que mana leite e mel.

[[v24-32-23]]

^<<v24-32-23,23>>^ Entraram nela e dela tomaram posse, mas não obedeceram à tua voz, nem andaram na tua lei; de tudo o que lhes mandaste que fizessem, nada fizeram. Por isso, trouxeste sobre eles todo este mal.

[[v24-32-24]]

^<<v24-32-24,24>>^ — Eis que rampas de ataque já foram construídas ao redor da cidade, para ser tomada, e a cidade, vencida pela espada, pela fome e pela peste, cairá nas mãos dos caldeus, que lutam contra ela. Como vês, aquilo que disseste aconteceu.

[[v24-32-25]]

^<<v24-32-25,25>>^ No entanto, Senhor  Deus, tu me disseste: "Compre o campo por dinheiro e chame testemunhas", embora a cidade já esteja sendo entregue nas mãos dos caldeus.

[[v24-32-26]]

^<<v24-32-26,26>>^ Então a palavra do Senhor  veio a Jeremias, dizendo:

[[v24-32-27]]

^<<v24-32-27,27>>^ — Eis que eu sou o Senhor , o Deus de toda a humanidade. Será que existe algo demasiadamente difícil para mim?

[[v24-32-28]]

^<<v24-32-28,28>>^ Portanto, assim diz o Senhor : Eis que entregarei esta cidade nas mãos dos caldeus, nas mãos de Nabucodonosor, rei da Babilônia, e ele a tomará.

[[v24-32-29]]

^<<v24-32-29,29>>^ Os caldeus, que lutam contra esta cidade, entrarão nela, porão fogo nesta cidade e queimarão as casas sobre cujos terraços queimaram incenso a Baal e ofereceram libações a outros deuses, para me provocarem à ira.

[[v24-32-30]]

^<<v24-32-30,30>>^ Porque os filhos de Israel e os filhos de Judá só fizeram o que é mau aos meus olhos, desde a sua mocidade. Tudo o que os filhos de Israel fizeram foi provocar-me à ira com as obras das suas mãos, diz o Senhor .

[[v24-32-31]]

^<<v24-32-31,31>>^ Porque esta cidade, desde o dia em que a construíram até o dia de hoje, tem servido para provocar a minha ira e o meu furor. Por isso, vou removê-la da minha presença,

[[v24-32-32]]

^<<v24-32-32,32>>^ por causa de toda a maldade que os filhos de Israel e os filhos de Judá fizeram, para me provocarem à ira, eles, os seus reis, as suas autoridades, os seus sacerdotes e os seus profetas, bem como o povo de Judá e os moradores de Jerusalém.

[[v24-32-33]]

^<<v24-32-33,33>>^ Eles me viraram as costas e não o rosto. E, embora eu os ensinasse sempre de novo, eles não quiseram ouvir, para receberem a advertência.

[[v24-32-34]]

^<<v24-32-34,34>>^ Pelo contrário, puseram as suas abominações no templo que se chama pelo meu nome, para o profanarem.

[[v24-32-35]]

^<<v24-32-35,35>>^ Edificaram os altos de Baal, que estão no vale de Ben-Hinom, para queimarem os seus filhos e as suas filhas em sacrifício a Moloque, algo que nunca lhes ordenei, nem me passou pela mente que fizessem tal abominação, para levarem Judá a pecar.

[[v24-32-36]]

^<<v24-32-36,36>>^ — Agora, pois, assim diz o Senhor , o Deus de Israel, a respeito desta cidade, da qual vocês dizem que já foi entregue nas mãos do rei da Babilônia, pela espada, pela fome e pela peste.

[[v24-32-37]]

^<<v24-32-37,37>>^ Eis que eu os congregarei de todas as terras, para onde os dispersei na minha ira, no meu furor e na minha grande indignação. Eu os farei voltar a este lugar e farei com que nele habitem em segurança.

[[v24-32-38]]

^<<v24-32-38,38>>^ — Eles serão o meu povo, e eu serei o seu Deus.

[[v24-32-39]]

^<<v24-32-39,39>>^ Eu lhes darei um só coração e um só caminho, para que me temam todos os dias, para o seu próprio bem e o bem de seus filhos.

[[v24-32-40]]

^<<v24-32-40,40>>^ Farei com eles uma aliança eterna, segundo a qual não deixarei de lhes fazer o bem; porei o meu temor no coração deles, para que nunca se afastem de mim.

[[v24-32-41]]

^<<v24-32-41,41>>^ Terei alegria em lhes fazer o bem, e os plantarei firmemente nesta terra, de todo o meu coração e de toda a minha alma.

[[v24-32-42]]

^<<v24-32-42,42>>^ — Porque assim diz o Senhor : Assim como fiz vir sobre este povo todo este grande mal, assim lhes trarei todo o bem que lhes estou prometendo.

[[v24-32-43]]

^<<v24-32-43,43>>^ Ainda se comprarão campos nesta terra, da qual vocês dizem: "Está deserta, sem pessoas e sem animais; foi entregue nas mãos dos caldeus."

[[v24-32-44]]

^<<v24-32-44,44>>^ Comprarão campos por dinheiro, assinarão as escrituras e as fecharão com selos, e chamarão testemunhas, na terra de Benjamim, nos arredores de Jerusalém, nas cidades de Judá, nas cidades da região montanhosa, nas cidades da Sefelá e nas cidades do Sul. Porque eu os trarei de volta do cativeiro, diz o Senhor .

'''

xref:024-jeremias/024-jeremias-031.adoc#v24-31-0[&#60; Capítulo Anterior] | <<v24-32-0,Topo>> | xref:024-jeremias/024-jeremias-033.adoc#v24-33-0[Próximo Capítulo &#62;]