include::./index.adoc[]

[[v24-24-0]]
=== Jeremias, 24
// naa ?, NAA - Nova Almeida Atualizada

[[v24-24-1]]

^<<v24-24-1,1>>^ O Senhor  me mostrou dois cestos de figos postos diante do templo do Senhor . Isso aconteceu depois que Nabucodonosor, rei da Babilônia, levou para o cativeiro Jeconias, filho de Jeoaquim, rei de Judá, as autoridades de Judá, os artífices e os ferreiros; ele os levou de Jerusalém à Babilônia.

[[v24-24-2]]

^<<v24-24-2,2>>^ Um cesto tinha figos muito bons, como os figos do começo da colheita, mas o outro tinha figos ruins, que eram tão ruins que não se podiam comer.

[[v24-24-3]]

^<<v24-24-3,3>>^ Então o Senhor  me perguntou: — O que você está vendo, Jeremias? Eu respondi: — Figos! Os figos bons são muito bons e os ruins são muito ruins, tão ruins que não se podem comer.

[[v24-24-4]]

^<<v24-24-4,4>>^ Então a palavra do Senhor  veio a mim, dizendo:

[[v24-24-5]]

^<<v24-24-5,5>>^ — Assim diz o Senhor , o Deus de Israel: Os exilados de Judá, que eu enviei deste lugar para a terra dos caldeus, são como esses figos bons: eu os considero bons.

[[v24-24-6]]

^<<v24-24-6,6>>^ Olharei para eles favoravelmente e os trarei de volta para esta terra. Eu os edificarei e não os destruirei; plantarei e não arrancarei.

[[v24-24-7]]

^<<v24-24-7,7>>^ Eu lhes darei um coração para que me conheçam, para que saibam que eu sou o Senhor . Eles serão o meu povo, e eu serei o seu Deus, porque se voltarão para mim de todo o seu coração.

[[v24-24-8]]

^<<v24-24-8,8>>^ — Como se rejeitam os figos ruins, que são tão ruins que não se podem comer, assim tratarei Zedequias, rei de Judá, diz o Senhor , e os seus oficiais, e o restante de Jerusalém, tanto os que ficaram nesta terra como os que moram na terra do Egito.

[[v24-24-9]]

^<<v24-24-9,9>>^ Farei deles um motivo de espanto, uma calamidade para todos os reinos da terra. Em todos os lugares para onde os dispersarei, serão objeto de deboche, de provérbio, de escárnio e de maldição.

[[v24-24-10]]

^<<v24-24-10,10>>^ Enviarei contra eles a espada, a fome e a peste, até que desapareçam da terra que lhes dei, a eles e aos seus pais.

'''

xref:024-jeremias/024-jeremias-023.adoc#v24-23-0[&#60; Capítulo Anterior] | <<v24-24-0,Topo>> | xref:024-jeremias/024-jeremias-025.adoc#v24-25-0[Próximo Capítulo &#62;]