include::./index.adoc[]

[[v24-7-0]]
=== Jeremias, 7
// naa ?, NAA - Nova Almeida Atualizada

[[v24-7-1]]

^<<v24-7-1,1>>^ Palavra que foi dita a Jeremias da parte do Senhor :

[[v24-7-2]]

^<<v24-7-2,2>>^ — Fique junto à porta da Casa do Senhor  e proclame ali esta palavra: "Escutem a palavra do Senhor , todos de Judá, vocês que entram por estas portas, para adorar o Senhor .

[[v24-7-3]]

^<<v24-7-3,3>>^ Assim diz o Senhor  dos Exércitos, o Deus de Israel: Corrijam a sua conduta e as suas ações, e eu os farei habitar neste lugar.

[[v24-7-4]]

^<<v24-7-4,4>>^ Não confiem em palavras falsas, dizendo: ‘Templo do Senhor ! Templo do Senhor ! Este é o templo do Senhor !’"

[[v24-7-5]]

^<<v24-7-5,5>>^ — Mas, se de fato emendarem os seus caminhos e as suas ações, se de fato praticarem a justiça, cada um com o seu próximo;

[[v24-7-6]]

^<<v24-7-6,6>>^ se não oprimirem o estrangeiro, o órfão e a viúva, nem derramarem sangue inocente neste lugar, nem seguirem outros deuses para o próprio mal de vocês,

[[v24-7-7]]

^<<v24-7-7,7>>^ eu os farei habitar neste lugar, na terra que dei aos pais de vocês, desde os tempos antigos e para sempre.

[[v24-7-8]]

^<<v24-7-8,8>>^ — Eis que vocês confiam em palavras falsas, que não servem para nada.

[[v24-7-9]]

^<<v24-7-9,9>>^ O que é isso? Vocês roubam, matam, cometem adultério e juram falsamente, queimam incenso a Baal e seguem outros deuses que vocês não conheciam no passado,

[[v24-7-10]]

^<<v24-7-10,10>>^ e depois vêm e se põem diante de mim neste templo que se chama pelo meu nome, e dizem: "Estamos salvos!" Sim, só para continuarem a praticar essas abominações!

[[v24-7-11]]

^<<v24-7-11,11>>^ Será que este templo que se chama pelo meu nome é um covil de salteadores aos olhos de vocês? Eis que eu, eu mesmo, vi isso, diz o Senhor .

[[v24-7-12]]

^<<v24-7-12,12>>^ — Mas vão agora ao meu lugar que estava em Siló, onde, no princípio, fiz habitar o meu nome, e vejam o que lhe fiz, por causa da maldade do meu povo de Israel.

[[v24-7-13]]

^<<v24-7-13,13>>^ Agora, visto que vocês fazem todas estas obras, diz o Senhor , e eu falei muitas e muitas vezes, mas vocês não me ouviram, chamei, mas vocês não me responderam,

[[v24-7-14]]

^<<v24-7-14,14>>^ farei também com este templo que se chama pelo meu nome, no qual vocês confiam, e com este lugar, que dei a vocês e aos seus pais, o mesmo que fiz com Siló.

[[v24-7-15]]

^<<v24-7-15,15>>^ Vou expulsar vocês da minha presença, como expulsei todos os seus irmãos, toda a posteridade de Efraim.

[[v24-7-16]]

^<<v24-7-16,16>>^ — Quanto a você, Jeremias, não interceda por este povo, nem levante por ele clamor ou oração, nem insista comigo, porque eu não ouvirei a sua voz.

[[v24-7-17]]

^<<v24-7-17,17>>^ Será que você não enxerga o que andam fazendo nas cidades de Judá e nas ruas de Jerusalém?

[[v24-7-18]]

^<<v24-7-18,18>>^ Os filhos apanham a lenha, os pais acendem o fogo e as mulheres amassam a farinha, para se fazerem bolos à Rainha dos Céus. Também oferecem libações a outros deuses, para me provocarem à ira.

[[v24-7-19]]

^<<v24-7-19,19>>^ Mas será que é a mim que eles provocam à ira? — diz o Senhor . Não seria muito mais a si mesmos, para a sua própria vergonha?

[[v24-7-20]]

^<<v24-7-20,20>>^ — Portanto, assim diz o Senhor  Deus: Eis que a minha ira e o meu furor se derramarão sobre este lugar, sobre as pessoas e sobre os animais, sobre as árvores do campo e sobre os frutos da terra. A minha ira queimará como um fogo e não se apagará.

[[v24-7-21]]

^<<v24-7-21,21>>^ — Assim diz o Senhor  dos Exércitos, o Deus de Israel: Juntem os seus holocaustos aos outros sacrifícios e comam a carne vocês mesmos.

[[v24-7-22]]

^<<v24-7-22,22>>^ No dia em que tirei os pais de vocês da terra do Egito, não falei nem lhes ordenei nada a respeito de holocaustos ou sacrifícios.

[[v24-7-23]]

^<<v24-7-23,23>>^ Mas o que lhes ordenei foi isto: "Deem ouvidos à minha voz, e eu serei o seu Deus, e vocês serão o meu povo. Andem em todo o caminho que eu lhes ordeno, para que tudo lhes vá bem."

[[v24-7-24]]

^<<v24-7-24,24>>^ Mas eles não quiseram ouvir, nem atenderam, porém andaram nos seus próprios conselhos e na dureza do seu coração maligno; andaram para trás e não para a frente.

[[v24-7-25]]

^<<v24-7-25,25>>^ Desde o dia em que os pais de vocês saíram da terra do Egito até hoje, muitas e muitas vezes, todos os dias, eu lhes enviei todos os meus servos, os profetas.

[[v24-7-26]]

^<<v24-7-26,26>>^ Mas vocês não quiseram me ouvir, nem atenderam; foram teimosos e fizeram pior do que os seus pais.

[[v24-7-27]]

^<<v24-7-27,27>>^ — Portanto, Jeremias, você dirá a eles todas estas palavras, mas eles não lhe darão ouvidos; você os chamará, mas eles não responderão.

[[v24-7-28]]

^<<v24-7-28,28>>^ Então você lhes dirá: "Esta é a nação que não dá ouvidos à voz do Senhor , seu Deus, e não aceita a disciplina. A verdade desapareceu; foi eliminada da sua boca."

[[v24-7-29]]

^<<v24-7-29,29>>^ "Corte os seus cabelos consagrados, ó Jerusalém, e jogue-os fora. Comece a prantear sobre o alto dos montes, porque o Senhor  rejeitou e abandonou a geração que é objeto do seu furor."

[[v24-7-30]]

^<<v24-7-30,30>>^ — Porque os filhos de Judá fizeram o que era mau aos meus olhos, diz o Senhor . Puseram os seus ídolos abomináveis no templo que se chama pelo meu nome, para o contaminarem.

[[v24-7-31]]

^<<v24-7-31,31>>^ Edificaram os altos de Tofete, no vale de Ben-Hinom, para queimarem em sacrifício os seus filhos e as suas filhas, algo que nunca ordenei, nem me passou pela mente.

[[v24-7-32]]

^<<v24-7-32,32>>^ Portanto, eis que virão dias, diz o Senhor , em que já não se chamará Tofete, nem vale de Ben-Hinom, mas o vale da Matança. Os mortos serão sepultados em Tofete por não haver outro lugar.

[[v24-7-33]]

^<<v24-7-33,33>>^ Os cadáveres deste povo servirão de alimento às aves dos céus e aos animais selvagens; e não haverá ninguém que os espante.

[[v24-7-34]]

^<<v24-7-34,34>>^ Farei cessar nas cidades de Judá e nas ruas de Jerusalém o som das festas e da alegria, a voz do noivo e a voz da noiva; porque a terra ficará em ruínas.

'''

xref:024-jeremias/024-jeremias-006.adoc#v24-6-0[&#60; Capítulo Anterior] | <<v24-7-0,Topo>> | xref:024-jeremias/024-jeremias-008.adoc#v24-8-0[Próximo Capítulo &#62;]