include::./index.adoc[]

[[v24-40-0]]
=== Jeremias, 40
// naa ?, NAA - Nova Almeida Atualizada

[[v24-40-1]]

^<<v24-40-1,1>>^ Palavra que foi dita a Jeremias da parte do Senhor , depois que Nebuzaradã, o chefe da guarda, o pôs em liberdade em Ramá, estando ele amarrado com correntes no meio de todos os do cativeiro de Jerusalém e de Judá, que estavam sendo levados cativos para a Babilônia.

[[v24-40-2]]

^<<v24-40-2,2>>^ O chefe da guarda chamou Jeremias de lado e lhe disse: — O Senhor , seu Deus, pronunciou esta calamidade contra este lugar.

[[v24-40-3]]

^<<v24-40-3,3>>^ Agora o Senhor  trouxe e fez o que tinha anunciado. Tudo isto aconteceu, porque vocês pecaram contra o Senhor  e não obedeceram à sua voz.

[[v24-40-4]]

^<<v24-40-4,4>>^ Agora, eis que hoje estou soltando as correntes que estavam em suas mãos. Se for do seu agrado ir comigo para a Babilônia, venha, e eu cuidarei bem de você. Mas, se não for do seu agrado ir comigo para a Babilônia, fique aqui. Veja, toda a terra está diante de você. Vá para o lugar que for do seu agrado e melhor para você.

[[v24-40-5]]

^<<v24-40-5,5>>^ Mas, visto que Jeremias demorava a se decidir, o capitão lhe disse: — Volte para junto de Gedalias, filho de Aicão, filho de Safã, a quem o rei da Babilônia nomeou governador das cidades de Judá, e more com ele no meio do povo. Ou, se quiser ir para qualquer outro lugar, vá. O chefe da guarda deu-lhe mantimentos e um presente e o deixou ir.

[[v24-40-6]]

^<<v24-40-6,6>>^ Assim, Jeremias foi para junto de Gedalias, filho de Aicão, em Mispa. E morou com ele no meio do povo que havia ficado na terra.

[[v24-40-7]]

^<<v24-40-7,7>>^ Quando os capitães dos exércitos que estavam no campo, eles e seus soldados, ouviram que o rei da Babilônia havia nomeado Gedalias, filho de Aicão, como governador da terra, e que lhe havia confiado os homens, as mulheres, os meninos e os mais pobres da terra que não foram levados ao exílio, para a Babilônia,

[[v24-40-8]]

^<<v24-40-8,8>>^ foram falar com ele em Mispa. Esses capitães eram Ismael, filho de Netanias, Joanã e Jônatas, filhos de Careá, Seraías, filho de Tanumete, os filhos de Efai, o netofatita, Jezanias, filho do maacatita. Com eles estavam os seus soldados.

[[v24-40-9]]

^<<v24-40-9,9>>^ Gedalias, filho de Aicão, filho de Safã, jurou a esses capitães e aos seus soldados, dizendo: — Vocês não precisam ter medo dos oficiais dos caldeus. Fiquem na terra, sirvam o rei da Babilônia, e tudo irá bem com vocês.

[[v24-40-10]]

^<<v24-40-10,10>>^ Quanto a mim, eis que ficarei em Mispa, para estar às ordens dos caldeus que vierem a nós. Quanto a vocês, colham as uvas para o vinho, as frutas de verão e o azeite. Ponham tudo nas suas vasilhas e morem nas cidades que vocês tomaram.

[[v24-40-11]]

^<<v24-40-11,11>>^ Da mesma forma, todos os judeus que estavam em Moabe, entre os filhos de Amom e em Edom e os que havia em todas aquelas terras ouviram que o rei da Babilônia havia deixado um remanescente em Judá e que havia nomeado Gedalias, filho de Aicão, filho de Safã, como governador sobre eles.

[[v24-40-12]]

^<<v24-40-12,12>>^ Então todos esses judeus voltaram de todos os lugares para onde tinham sido dispersos e vieram à terra de Judá, para junto de Gedalias, em Mispa. E colheram vinho e frutas de verão em grande abundância.

[[v24-40-13]]

^<<v24-40-13,13>>^ Joanã, filho de Careá, e todos os comandantes dos exércitos que estavam no campo foram até Gedalias, em Mispa,

[[v24-40-14]]

^<<v24-40-14,14>>^ e lhe disseram: — Você sabia que Baalis, rei dos filhos de Amom, enviou Ismael, filho de Netanias, para matar você? Mas Gedalias, filho de Aicão, não lhes deu crédito.

[[v24-40-15]]

^<<v24-40-15,15>>^ Então Joanã, filho de Careá, disse a Gedalias em segredo, em Mispa: — Irei agora e matarei Ismael, filho de Netanias, sem que ninguém o saiba. Por que deixar que ele venha para assassiná-lo, fazendo com que todo o Judá que se reuniu à sua volta seja espalhado, e venha a perecer o remanescente de Judá?

[[v24-40-16]]

^<<v24-40-16,16>>^ Mas Gedalias, filho de Aicão, disse a Joanã, filho de Careá: — Não faça isso! Porque isso que você está dizendo a respeito de Ismael é falso.

'''

xref:024-jeremias/024-jeremias-039.adoc#v24-39-0[&#60; Capítulo Anterior] | <<v24-40-0,Topo>> | xref:024-jeremias/024-jeremias-041.adoc#v24-41-0[Próximo Capítulo &#62;]